### PR TITLE
feat: [PL-29446]: Added Selective permission on Resource Group List 

### PR DESCRIPTION
**Pull request by meenakshi-harness**
## Describe your changes
1. We have added selective view permission support in resource group list apis. With this if view permission is given to selected resource group only those will be returned in list calls.
2. Added/Updated the test cases.
3. Test in local for all endpoints

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41618)

### CODE REVIEW

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41618)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java` line 252 at r1](https://reviewable.io/reviews/harness/harness-core/41618#-NJKYPan4akddF1_96GG:-NJKYPan4akddF1_96GH:bumosrn) ([raw file](https://github.com/harness/harness-core/blob/7484215395d4ce48fd074ed86dfaaf136a24ab2a/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java#L252)):*
> ```Java
>         return Page.empty();
>       }
>       criteria.and(ResourceGroupKeys.identifier)
> ```

Can we change to same change as in above API?
resourceGroupFilterDTO.setIdentifierFilter(
          resourceGroups.stream().map(ResourceGroup::getIdentifier).collect(Collectors.toSet()));

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41618)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java` line 252 at r1](https://reviewable.io/reviews/harness/harness-core/41618#-NJKYPan4akddF1_96GG:-NM94VZ76oOgv61w5U_l:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/772ff74f4f531b31d8cad48214d1d2fb64dc4471/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java#L252)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Can we change to same change as in above API?
resourceGroupFilterDTO.setIdentifierFilter(
          resourceGroups.stream().map(ResourceGroup::getIdentifier).collect(Collectors.toSet()));
</blockquote></details>

Done.

**Review by reetika04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41618)* status: 6 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java` line 221 at r2](https://reviewable.io/reviews/harness/harness-core/41618#-NMCiXtE79mbd9GwBCx6:-NMCiXtE79mbd9GwBCx7:b60cbxu) ([raw file](https://github.com/harness/harness-core/blob/328b567b201226afabdc0eadeb9327c06d7a0ddb/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java#L221)):*
> ```Java
>       resourceGroupFilterDTO.setIdentifierFilter(
>           resourceGroups.stream().map(ResourceGroup::getIdentifier).collect(Collectors.toSet()));
>       criteria = getResourceGroupFilterCriteria(resourceGroupFilterDTO);
> ```

Since we have all the data, we donot have to make a db call again. You can use false pagination.

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41618)* status: 6 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java` line 221 at r2](https://reviewable.io/reviews/harness/harness-core/41618#-NMCiXtE79mbd9GwBCx6:-NMbE98J9Hwx1wQMjtXc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/328b567b201226afabdc0eadeb9327c06d7a0ddb/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java#L221)):*
<details><summary><i>Previously, reetika04 (Reetika) wrote…</i></summary><blockquote>

Since we have all the data, we donot have to make a db call again. You can use false pagination.
</blockquote></details>

Done.

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41618#-:-NN29RAn7ycu-CS--fH3:bnfp4nl)* status: Some of the checks are too old. 6 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41618)* status: Some of the checks are too old. 6 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by reetika04 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41618)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41618#-:-NNAEz4W4EYVz_8Xgula:bnfp4nl)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41618)* status: :shipit: complete! ✓

**Pull request merged**
