### PR TITLE
feat: [PL-24395]: Integrate ADO repo find scm api in java client

### PR DESCRIPTION
**Pull request by goelsatyam2**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32135)

### CODE REVIEW

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32135)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java, line 586 at r1](https://reviewable.io/reviews/harness/harness-core/32135#-N-2uTbW2OB1RJfKZL4G:-N-2uTbW2OB1RJfKZL4H:b-r7o1oy) ([raw file](https://github.com/harness/harness-core/blob/1f60808283ce87346c5404dc5e5db9d5157d05f4/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L586)):*
> ```Java
> 
>   @Override
>   public CreateWebhookResponse createWebhook(
> ```

A function with create webhook might already be there ?

**Review by goelsatyam2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32135)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java, line 586 at r1](https://reviewable.io/reviews/harness/harness-core/32135#-N-2uTbW2OB1RJfKZL4G:-N04ARNE28FPQsADiuIe:b94bcrw) ([raw file](https://github.com/harness/harness-core/blob/e33cf32fd8e13f7824ecda595a2b8ba64f59e339/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L586)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

A function with create webhook might already be there ?
</blockquote></details>

I didn't add this function. Gitt diff is mixed up. I have added getUserRepo function,

**Review by DeepakPatankar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32135)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by goelsatyam2** [comment]
Change is not needed.

**Pull request closed without merging**
