### PR TITLE
fix: [CDS-43956]: Fixing SI based license usage reporting

### PR DESCRIPTION
**Pull request by shubham-in10se**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38148)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38148)

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38148)* status: 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java` line 163 at r2](https://reviewable.io/reviews/harness/harness-core/38148#-NDDDa47-wlhfc-748X7:-NDDDa47-wlhfc-748X8:blurar0) ([raw file](https://github.com/harness/harness-core/blob/631a507834f7642de8572cde6dfa363ed14657c0/125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java#L163)):*
> ```Java
> 
>   private String findServiceName(
>       String orgidentifier, String projectidentifier, String serviceId, List<Services> serviceNames) {
> ```

nit: camelCase
___
*[`125-cd-nextgen/src/main/java/io/harness/telemetry/service/CdTelemetryPublisher.java` line 85 at r2](https://reviewable.io/reviews/harness/harness-core/38148#-NDDDt3aD4OQRfm_rimo:-NDDDt3aD4OQRfm_rimp:bgjwen3) ([raw file](https://github.com/harness/harness-core/blob/631a507834f7642de8572cde6dfa363ed14657c0/125-cd-nextgen/src/main/java/io/harness/telemetry/service/CdTelemetryPublisher.java#L85)):*
> ```Java
>   private void sendEvent(String accountId) {
>     if (EmptyPredicate.isNotEmpty(accountId) && !accountId.equals(GLOBAL_ACCOUNT_ID)) {
>       if (true
> ```

Why are we doing this? :thinking:

**Review by vikyathharekal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38148#-:-NDDOffS7lcZyVh2xxDs:bnfp4nl)* status: 2 file(s) to review. 1. unresolved discussions.

**Review by vikyathharekal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38148)* status: 2 file(s) to review. 

___
*[`125-cd-nextgen/src/main/java/io/harness/telemetry/service/CdTelemetryPublisher.java` line 85 at r2](https://reviewable.io/reviews/harness/harness-core/38148#-NDDDt3aD4OQRfm_rimo:-NDD_-5q0BxI8dR1_jgU:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/631a507834f7642de8572cde6dfa363ed14657c0/125-cd-nextgen/src/main/java/io/harness/telemetry/service/CdTelemetryPublisher.java#L85)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

forgot to remove this.
fixed.
Thanks for catching this.
</blockquote></details>

Done

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38148)* status: :shipit: complete! ✓

**Pull request merged**
