### PR TITLE
[fix]: [CDS-72887]: Introduce EngineExpressionResolver to have support for both EngineExpressionEvaluatorResolver and EngineExpressionServiceResolver

### PR DESCRIPTION
**Pull request by archit-harness**
## Describe your changes

**Changes** Introduce EngineExpressionResolver to have support for both EngineExpressionEvaluatorResolver and EngineExpressionServiceResolver

**Impact** Currently the framework is only introduced and files are moved

**Testing** Basic CD and Custom stage pipeline with and without expressions are run

**Improvement** Provide basic parameterField processor support in all engineExpression for other service to utilise and not create their custom ones, thus edge cases will be reduced.

Secondly, this will reduce CI engine expression resolution for Initialise step, where if any step is matrix they use strategy expansion, where they convert into recast map, which has ParameterFieldDocumentMap, whose processor is added to StrategyExpressionEvalutor. After this, recaster conversion is not required, thus CPU processing will be saved and it will be more fast

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50524)

### CODE REVIEW

**Comment by archit-harness** [comment]
trigger uts

**Comment by archit-harness** [comment]
trigger uts

**Comment by archit-harness** [comment]
trigger uts

**Comment by archit-harness** [comment]
trigger uts

**Comment by archit-harness** [comment]
trigger messagecheck

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 10 of 20 files at r1, 5 of 5 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50524)* status: 20 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/expression/EngineExpressionServiceResolver.java` line 42 at r4](https://reviewable.io/reviews/harness/harness-core/50524#-N_IHPWBEcWNsCE07ps_:-N_IHPWBEcWNsCE07psa:bbie574) ([raw file](https://github.com/harness/harness-core/blob/dadd5b0c140c8265103ccbfe6087361bad69ae20/884-pms-commons/src/main/java/io/harness/pms/expression/EngineExpressionServiceResolver.java#L42)):*
> ```Java
>   @Override
>   public Object resolve(Object o, ExpressionMode expressionMode) {
>     // Currently resolve on grpc service is not supported
> ```

This won't ever be supported right as this is for local consumption, can we throw an unsupported exception here?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyExpressionEvaluator.java` line 66 at r4](https://reviewable.io/reviews/harness/harness-core/50524#-N_IIIqu3JzTFAxegnD0:-N_IIIqu3JzTFAxegnD1:b-lfijxl) ([raw file](https://github.com/harness/harness-core/blob/dadd5b0c140c8265103ccbfe6087361bad69ae20/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyExpressionEvaluator.java#L66)):*
> ```Java
>   }
> 
>   public static class StrategyResolveFunctorImpl extends ResolveFunctorImpl {
> ```

Bit confused here, this class only runs in SDK so it should work with ParameterField right? 
___
*[`953-yaml-commons/src/main/java/io/harness/pms/expression/ExpressionModeMapper.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/50524#-N_IHqUKDa5Pvw7grhp4:-N_IHqUKDa5Pvw7grhp5:b-640ite) ([raw file](https://github.com/harness/harness-core/blob/dadd5b0c140c8265103ccbfe6087361bad69ae20/953-yaml-commons/src/main/java/io/harness/pms/expression/ExpressionModeMapper.java#L19)):*
> ```Java
> @UtilityClass
> public class ExpressionModeMapper {
>   public static ExpressionMode fromExpressionModeProto(io.harness.pms.contracts.plan.ExpressionMode mode) {
> ```

why are there two expression modes?

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 10 of 20 files at r1, 5 of 5 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50524)* status: 1 change requests. 1 of 2 approvals obtained.

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50524)* status: 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/expression/EngineExpressionServiceResolver.java` line 42 at r4](https://reviewable.io/reviews/harness/harness-core/50524#-N_IHPWBEcWNsCE07ps_:-N_JFEZl12Y2WCkRJbPx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dadd5b0c140c8265103ccbfe6087361bad69ae20/884-pms-commons/src/main/java/io/harness/pms/expression/EngineExpressionServiceResolver.java#L42)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

This won't ever be supported right as this is for local consumption, can we throw an unsupported exception here?
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyExpressionEvaluator.java` line 66 at r4](https://reviewable.io/reviews/harness/harness-core/50524#-N_IIIqu3JzTFAxegnD0:-N_JFFG-6B1D5rPVwIM9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dadd5b0c140c8265103ccbfe6087361bad69ae20/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyExpressionEvaluator.java#L66)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Bit confused here, this class only runs in SDK so it should work with ParameterField right? 
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/expression/ExpressionModeMapper.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/50524#-N_IHqUKDa5Pvw7grhp4:-N_JFEvY6nJoMe_yUQNP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dadd5b0c140c8265103ccbfe6087361bad69ae20/953-yaml-commons/src/main/java/io/harness/pms/expression/ExpressionModeMapper.java#L19)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

why are there two expression modes?
</blockquote></details>

Done.

**Pull request merged**
