### PR TITLE
feat: [PL-22430]: Added Checks for Operation Annotation

### PR DESCRIPTION
**Pull request by mankrit-singh**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30871)

### CODE REVIEW

**Comment by mankrit-singh** [comment]
trigger messagecheck

**Comment by mankrit-singh** [comment]
trigger messagecheck

**Comment by mankrit-singh** [comment]
trigger tiboostrap1

**Comment by mankrit-singh** [comment]
trigger tiBoostrap1

**Comment by mankrit-singh** [comment]
trigger ti1

**Comment by mankrit-singh** [comment]
trigger ti1

**Comment by mankrit-singh** [comment]
trigger ti4

**Review by rijajoo — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30871)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by rijajoo — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30871#-:-MwW_PXW1IwAkvs8ISKY:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by mankrit-singh** [comment]
trigger authorcheck

**Comment by mankrit-singh** [comment]
trigger authorcheck

**Comment by mankrit-singh** [comment]
trigger authorcheck

**Comment by mankrit-singh** [comment]
trigger authorcheck

**Comment by mankrit-singh** [comment]
trigger authorcheck

**Comment by mankrit-singh** [comment]
trigger authorcheck

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30871)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by rijajoo — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30871)* status: :shipit: complete! ✓

**Pull request merged**
