### PR TITLE
[feat]: [PIE-3844]: Using wait engine to wait pipeline for user input

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33604)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/input/ExecutionInputServiceImpl.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/33604#-N330aqV33K0QuIxPIwD:-N330aqV33K0QuIxPIwE:b5ydpwz) ([raw file](https://github.com/harness/harness-core/blob/d4ba692b37426cf1ade6344b2203d52aa391a31c/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/input/ExecutionInputServiceImpl.java#L32)):*
> ```Java
> 
>   @Override
>   public void continueExecution(String inputInstanceId) {
> ```

Should we return boolean over here?
What would happen if two different users give input at the same time, doneWith should be called only once. We need a way to tell the resource if we were able to continue or not

**Comment by sahilhindwani-harness** [comment]
*[`870-orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/33604#-N331OBF5csS8ZY5lnOk:-N331OBG2cvsMCIN56D1:b1ooccz) ([raw file](https://github.com/harness/harness-core/blob/d4ba692b37426cf1ade6344b2203d52aa391a31c/870-orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java#L54)):*
> ```Java
>   @Override
>   public void notifyError(Map<String, ResponseData> response) {
>     log.error("Execution input failed for nodeExecutionId {}", nodeExecutionId);
> ```

We should mark the pipeline failed over here. Please add a todo

**Comment by sahilhindwani-harness** [comment]
*[`870-orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/33604#-N331Y4YEMqEJZiPHm6j:-N331Y4ZA_DcJadGS6jp:b-98ebci) ([raw file](https://github.com/harness/harness-core/blob/d4ba692b37426cf1ade6344b2203d52aa391a31c/870-orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java#L43)):*
> ```Java
>   @Override
>   public void notifyTimeout(Map<String, ResponseData> responseMap) {
>     log.error("Execution input timed out for nodeExecutionId {}", nodeExecutionId);
> ```

Here also, we will need some action to mark the step as failed. Please add a todo

**Comment by sahilhindwani-harness** [comment]
Let's add test for the newly added code specially any changes in the orchestrationEngine or planNodeExecutionStrategy

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33604)* status: 23 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/33604#-N339Yb72j4kffxpYU5B:-N339Yb72j4kffxpYU5C:bxqmbbt) ([raw file](https://github.com/harness/harness-core/blob/d4ba692b37426cf1ade6344b2203d52aa391a31c/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L117)):*
> ```Java
>           description = PlanExecutionResourceConstants.NODE_EXECUTION_ID_PARAM_MESSAGE) String nodeExecutionId) {
>     ExecutionInputInstance executionInputInstance = executionInputService.getExecutionInputInstance(nodeExecutionId);
>     return ResponseDTO.newResponse(ExecutionInputDTO.builder()
> ```

Mapper to convert from entity to DTO

**Comment by sahilhindwani-harness** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/33604#-N339pvU3taEBtjksgA2:-N339pvU3taEBtjksgA3:b6ol2ro) ([raw file](https://github.com/harness/harness-core/blob/d4ba692b37426cf1ade6344b2203d52aa391a31c/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L125)):*
> ```Java
> 
>   @POST
>   @Path("/{inputInstanceId}")
> ```

revert and please use nodeExecutionId only.

**Comment by sahilhindwani-harness** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceConstants.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/33604#-N339xfJ7Ue8JtT42v9E:-N339xfJ7Ue8JtT42v9F:b-ey43zo) ([raw file](https://github.com/harness/harness-core/blob/d4ba692b37426cf1ade6344b2203d52aa391a31c/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceConstants.java#L22)):*
> ```Java
> 
>   String INPUT_INSTANCE_ID_PARAM_MESSAGE = "The Id of the execution input instance for a step/stage";
> ```

nit: same as above, will be reverted if we use nodeExecutionId

**Comment by sahilhindwani-harness** [comment]
*[`870-orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionHelper.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/33604#-N33AVeNEuW2TgtLtK2Y:-N33AVeNEuW2TgtLtK2Z:b-hi0uhq) ([raw file](https://github.com/harness/harness-core/blob/d4ba692b37426cf1ade6344b2203d52aa391a31c/870-orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionHelper.java#L32)):*
> ```Java
>   @Inject private NodeExecutionService nodeExecutionService;
>   @Inject private WaitNotifyEngine waitNotifyEngine;
>   @Inject ExecutionInputRepository repository;
> ```

nit: Use service

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33604)* status: 25 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/33604#-N339Yb72j4kffxpYU5B:-N33V5GM73_zcv0PWdo6:b1ual6g) ([raw file](https://github.com/harness/harness-core/blob/d4ba692b37426cf1ade6344b2203d52aa391a31c/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L117)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Mapper to convert from entity to DTO
</blockquote></details>

Added todo. Will do it in the next pr.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/33604#-N339pvU3taEBtjksgA2:-N33US246OXhf9D585XD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d4ba692b37426cf1ade6344b2203d52aa391a31c/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L125)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

revert and please use nodeExecutionId only.
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceConstants.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/33604#-N339xfJ7Ue8JtT42v9E:-N33UUQO--g36-KkHpsZ:b-t565eu) ([raw file](https://github.com/harness/harness-core/blob/d4ba692b37426cf1ade6344b2203d52aa391a31c/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceConstants.java#L22)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: same as above, will be reverted if we use nodeExecutionId
</blockquote></details>

This is needed for adding schema description for inputInstanceId field in DTO.
___
*[`870-orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/33604#-N331Y4YEMqEJZiPHm6j:-N33UyON3E8UyQAhu_L0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d4ba692b37426cf1ade6344b2203d52aa391a31c/870-orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java#L43)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Here also, we will need some action to mark the step as failed. Please add a todo
</blockquote></details>

Done.
___
*[`870-orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/33604#-N331OBF5csS8ZY5lnOk:-N33Uzqg4V8kOPs35Vxi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d4ba692b37426cf1ade6344b2203d52aa391a31c/870-orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java#L54)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We should mark the pipeline failed over here. Please add a todo
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/input/ExecutionInputServiceImpl.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/33604#-N330aqV33K0QuIxPIwD:-N33UcXE36sdHEwcvTK1:b-eqn4o5) ([raw file](https://github.com/harness/harness-core/blob/d4ba692b37426cf1ade6344b2203d52aa391a31c/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/input/ExecutionInputServiceImpl.java#L32)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should we return boolean over here?
What would happen if two different users give input at the same time, doneWith should be called only once. We need a way to tell the resource if we were able to continue or not
</blockquote></details>

Added todo. Will take care of this while implementing the merge logic of user input.

**Comment by brijeshdhakar** [comment]
tirgger ti0

**Comment by brijeshdhakar** [comment]
trigger ti0

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 5 of 9 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 6 of 6 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33604)* status: 32 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java` line 144 at r8](https://reviewable.io/reviews/harness/harness-core/33604#-N3J1dZl8dITkVSNo6qr:-N3JBZLkBLAyOFPvE9lH:byvpqtg) ([raw file](https://github.com/harness/harness-core/blob/d0c1d2f4fd7c839bf9ecbde9310f0ef9d75cd8c5/884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java#L144)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

What is use case for running? @sahilhindwani-harness @brijeshdhakar 
</blockquote></details>

I don't think Running is required. Brijesh will update this.

**Comment by sahilhindwani-harness** [comment]
*[`876-orchestration-beans/src/main/java/io/harness/plan/Plan.java` line 86 at r8](https://reviewable.io/reviews/harness/harness-core/33604#-N3J1LJIBCTwTSMeIQWc:-N3JBhGb3gA8X6HiXolG:b-xdgj4m) ([raw file](https://github.com/harness/harness-core/blob/d0c1d2f4fd7c839bf9ecbde9310f0ef9d75cd8c5/876-orchestration-beans/src/main/java/io/harness/plan/Plan.java#L86)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Do we need at Plan level as well? Doesnt planNode containing will solve our problem?
</blockquote></details>

+1, Brijesh can we have a default method in node that would return empty and will only be overridden by planNode?

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33604)* status: 6 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 97 at r8](https://reviewable.io/reviews/harness/harness-core/33604#-N3Iv-8-Cl4m8-ed8cYg:-N3JXlc404tF2BP7xE9D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d0c1d2f4fd7c839bf9ecbde9310f0ef9d75cd8c5/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L97)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

No Archit, that should not be required here.
</blockquote></details>

Done.
___
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java` line 144 at r8](https://reviewable.io/reviews/harness/harness-core/33604#-N3J1dZl8dITkVSNo6qr:-N3JXgJr3gAarJkZUMtY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d0c1d2f4fd7c839bf9ecbde9310f0ef9d75cd8c5/884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java#L144)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I don't think Running is required. Brijesh will update this.
</blockquote></details>

Done.
___
*[`876-orchestration-beans/src/main/java/io/harness/plan/Plan.java` line 86 at r8](https://reviewable.io/reviews/harness/harness-core/33604#-N3J1LJIBCTwTSMeIQWc:-N3JXi-N4POkLUjadUJh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d0c1d2f4fd7c839bf9ecbde9310f0ef9d75cd8c5/876-orchestration-beans/src/main/java/io/harness/plan/Plan.java#L86)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

+1, Brijesh can we have a default method in node that would return empty and will only be overridden by planNode?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`870-orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java` line 58 at r9](https://reviewable.io/reviews/harness/harness-core/33604#-N3JxsfM4cBGZKRumnUj:-N3JxsfM4cBGZKRumnUk:b-bu10hb) ([raw file](https://github.com/harness/harness-core/blob/02f67171f0e5cd6a1131f5a3ada6d850c090e71c/870-orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java#L58)):*
> ```Java
>   @Override
>   public void notify(Map<String, ResponseData> response) {
>     nodeExecutionService.updateStatusWithOps(nodeExecutionId, Status.QUEUED, null, EnumSet.of(Status.INPUT_WAITING));
> ```

nit: Add a note as to why we are marking as queued. You can address it in next PR.

**Comment by sahilhindwani-harness** [comment]
*[`870-orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputHelper.java` line 34 at r9](https://reviewable.io/reviews/harness/harness-core/33604#-N3JyA3d3AZMT7VMFERL:-N3JyA3d3AZMT7VMFERM:b-1r4eda) ([raw file](https://github.com/harness/harness-core/blob/02f67171f0e5cd6a1131f5a3ada6d850c090e71c/870-orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputHelper.java#L34)):*
> ```Java
>   @Inject private ExecutionInputService executionInputService;
>   @Inject @Named(OrchestrationPublisherName.PUBLISHER_NAME) private String publisherName;
>   public void waitForExecutionInput(Ambiance ambiance, NodeExecution nodeExecution, String executionInputTemplate) {
> ```

Do we need ambiance here? Should we use nodeExecution.getAmbiance instead?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33604)* status: 12 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33604)* status: 12 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
Codebase hash change:
Added an entry in kryo registrars that is internal to pipeline service.
It will not affect the delegate communication.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 12 of 23 files at r1, 4 of 9 files at r2, 2 of 2 files at r3, 1 of 6 files at r5, 1 of 1 files at r7, 1 of 1 files at r8, 11 of 12 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33604)* status: :shipit: complete! ✓

**Pull request merged**
