### PR TITLE
fix: [CDS-75478]: Throwing error in case string other than true or false

### PR DESCRIPTION
**Pull request by Y0709**
Currently in parameterDocumentFieldProcessor in case we have passed any string other than true or false in the yaml . We have changed that to work only in case correct values i.e true or false. In case some value is given in boolean parameter field we will throw an error.

Tested this with correct true and false values. 
Also tested with wrong value we are displaying proper error on UI

Screenshot 2023-08-02 at 5 44 09 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51290)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51290)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldMapper.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/51290#-NaqB4yCAdeOQYDtPRcK:-NaqB4yCAdeOQYDtPRcL:b-e03iuf) ([raw file](https://github.com/harness/harness-core/blob/160eb16d5f073f6b2abf756adfb2e31abd2c1f3b/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldMapper.java#L112)):*
> ```Java
> 
>       if (cls.getSimpleName().equals("Boolean")
>           && parameterFieldValueWrapper.getValue().getClass().getSimpleName().equals("String")) {
> ```

@shalini-agr shouldnt this condition be opp? cls be string and parameter will be boolean?
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldProcessor.java` line 139 at r1](https://reviewable.io/reviews/harness/harness-core/51290#-NaqAvcs5GNr1gKgn278:-NaqAvcs5GNr1gKgn279:b-dvaple) ([raw file](https://github.com/harness/harness-core/blob/160eb16d5f073f6b2abf756adfb2e31abd2c1f3b/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldProcessor.java#L139)):*
> ```Java
>         } else if (fieldClass.equals(Boolean.class)) {
>           if (finalValue.getClass().equals(String.class)) {
>             finalValue = BooleanUtils.toBoolean((String) finalValue, "true", "false");
> ```

if you dont pass true/false, i think for other values it will come as null, can you confirm, if yes then we should rely on it



_Code quote:_
```Java
BooleanUtils.toBoolean((String) finalValue,
```

**Comment by shalini-agr** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldProcessor.java` line 139 at r1](https://reviewable.io/reviews/harness/harness-core/51290#-NaqBP1cC-IdSDE5ZZ_4:-NaqBP1cC-IdSDE5ZZ_5:b7bqzh2) ([raw file](https://github.com/harness/harness-core/blob/160eb16d5f073f6b2abf756adfb2e31abd2c1f3b/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldProcessor.java#L139)):*
> ```Java
>         } else if (fieldClass.equals(Boolean.class)) {
>           if (finalValue.getClass().equals(String.class)) {
>             finalValue = BooleanUtils.toBoolean((String) finalValue, "true", "false");
> ```

IMO, we should also support TRUE and FALSE with case insensitive.

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51290)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldProcessor.java` line 139 at r1](https://reviewable.io/reviews/harness/harness-core/51290#-NaqAvcs5GNr1gKgn278:-NaqBkKVDtwLDUrtxENp:b-uxpp4k) ([raw file](https://github.com/harness/harness-core/blob/160eb16d5f073f6b2abf756adfb2e31abd2c1f3b/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldProcessor.java#L139)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

if you dont pass true/false, i think for other values it will come as null, can you confirm, if yes then we should rely on it
</blockquote></details>

In case we dont pass true or false it is throwing an exception which we catch and log after which the string is being returned as it is

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51290)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldMapper.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/51290#-NaqB4yCAdeOQYDtPRcK:-NaqBYEtB2aJSYXyRSrA:bfgcyjb) ([raw file](https://github.com/harness/harness-core/blob/160eb16d5f073f6b2abf756adfb2e31abd2c1f3b/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldMapper.java#L112)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@shalini-agr shouldnt this condition be opp? cls be string and parameter will be boolean?
</blockquote></details>

No, this is correct, cls which comes from documentField is the expected type. Also, yuvraj has tested this locally with a field of expected type boolean and resolved value a string.

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51290)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldProcessor.java` line 139 at r1](https://reviewable.io/reviews/harness/harness-core/51290#-NaqBP1cC-IdSDE5ZZ_4:-NaqGgm49I8PtPGXSaCe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/160eb16d5f073f6b2abf756adfb2e31abd2c1f3b/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldProcessor.java#L139)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

IMO, we should also support TRUE and FALSE with case insensitive.
</blockquote></details>

Done.

**Review by shalini-agr — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51290)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger ut7

**Pull request closed without merging**
