### PR TITLE
techdebt: [PL-29839]: Move Service variable entity out of 930

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
Move Service variable entity out of 930 task package to make delegate mongo independent 

Test performed
-K8 end to end deployment with new and older version of delegate

## Checklist
- [ x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40049)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
we should do an end to end k8 deployment test where we are using a service variable

**Review by raghuAtWings — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40049)* status: 1 change requests. 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
trigger messagecheck

**Review by gn-harness — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40049)* status: Some of the checks are too old. 1 change requests. 1 of 2 approvals obtained.

**Comment by jennyjames21** [comment]
K8 Deployment with older version of delegate 
image
image

**Review by gn-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40049)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40049)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by jennyjames21 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40049#-:-NHVoDIT4WQLqz8S547e:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40049)* status: :shipit: complete! ✓

**Pull request merged**
