### PR TITLE
fix: [CDS-52461]: Adding Harness store support for values override in Apply Step

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43885)

### CODE REVIEW

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43885)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Comment by abhinavsingh1196** [comment]
@namantalaycha10 please add a proper PR description.

**Review by abhinavsingh1196 — DISMISSED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43885)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 401 at r4](https://reviewable.io/reviews/harness/harness-core/43885#-NOPns409vkpbidySNhF:-NOPns41102rpWmBNR46:b4a6rm1) ([raw file](https://github.com/harness/harness-core/blob/fd457a06202f00498a47ac6051c2b0672ca2cd56/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L401)):*
> ```Java
>                                                         .build();
> 
>     List<ManifestOutcome> orderedManifestOutcome = getOrderedManifestOutcome(manifestsOutcome.values());
> ```

nit: `orderedManifestOutcomes`

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43885)* status: Some of the checks are too old.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43885)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java` line 361 at r5](https://reviewable.io/reviews/harness/harness-core/43885#-NPHSf6j7_pv2ulml6RI:-NPHSf6j7_pv2ulml6RJ:byil9ez) ([raw file](https://github.com/harness/harness-core/blob/cd34cb558562d52c74639d89b48eb76fc385d3af/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L361)):*
> ```Java
>     if (isNotEmpty(gitFetchFilesResultMap) || isNotEmpty(helmChartValuesFetchFilesResultMap)
>         || isNotEmpty(customFetchContent) || isNotEmpty(localStoreFetchFilesResultMap)
>         || isEmpty(nativeHelmStepPassThroughData.getManifestOutcomeList())) {
> ```

Why is empty?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 663 at r5](https://reviewable.io/reviews/harness/harness-core/43885#-NPHSjuz6Z_m5IKjuNYF:-NPHSjv-7ifXNqwZn9rm:bbwftmb) ([raw file](https://github.com/harness/harness-core/blob/cd34cb558562d52c74639d89b48eb76fc385d3af/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L663)):*
> ```Java
>     Map<String, LocalStoreFetchFilesResult> localStoreFetchFilesResultMap =
>         k8sStepPassThroughData.getLocalStoreFileMapContents();
>     if (isNotEmpty(k8sStepPassThroughData.getManifestOutcomeList()) || isNotEmpty(gitFetchFilesResultMap)
> ```

We're already doing this at io/harness/cdng/k8s/K8sStepHelper.java:877, why we do need this here as well?

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43885)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java` line 359 at r6](https://reviewable.io/reviews/harness/harness-core/43885#-NPHZZqNCI2m-KXPLwJO:-NPHZZqNCI2m-KXPLwJP:busuwnb) ([raw file](https://github.com/harness/harness-core/blob/1e599c58d1cb0d430bb9641066395c54cb5db8f3/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L359)):*
> ```Java
>     Map<String, LocalStoreFetchFilesResult> localStoreFetchFilesResultMap =
>         nativeHelmStepPassThroughData.getLocalStoreFileMapContents();
>     if (isNotEmpty(gitFetchFilesResultMap) || isNotEmpty(helmChartValuesFetchFilesResultMap)
> ```

this should be just if( isNotEmpty(nativeHelmStepPassThroughData.getManifestOutcomeList()) ) 
everything else doesn't make sense, this condition will always be resolved as true ignoring other

**Review by namantalaycha10 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43885#-:-NPIHMjx9QhymfS9Rinb:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java` line 359 at r6](https://reviewable.io/reviews/harness/harness-core/43885#-NPHZZqNCI2m-KXPLwJO:-NPIG-rQ80UzlWS5HUOo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1e599c58d1cb0d430bb9641066395c54cb5db8f3/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L359)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

this should be just if( isNotEmpty(nativeHelmStepPassThroughData.getManifestOutcomeList()) ) 
everything else doesn't make sense, this condition will always be resolved as true ignoring other 
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 663 at r5](https://reviewable.io/reviews/harness/harness-core/43885#-NPHSjuz6Z_m5IKjuNYF:-NPIHJMXDc_0Qqibo9iY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cd34cb558562d52c74639d89b48eb76fc385d3af/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L663)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We're already doing this at io/harness/cdng/k8s/K8sStepHelper.java:877, why we do need this here as well?
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43885)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by lovish1999 — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r4, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43885)* status: :shipit: complete! ✓

**Pull request merged**
