### PR TITLE
[feat]: [PL-27204]: Added API endpoint to Get Role Assignment with given identifier.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36123)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36123)

**Comment by Jimit09Gandhi** [comment]
trigger messagecheck

**Review by reetika04 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36123)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36123)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java` line 536 at r2](https://reviewable.io/reviews/harness/harness-core/36123#-NBl1uJMEbd5ZDZQAWRj:-NBl1uJMEbd5ZDZQAWRk:bgonar4) ([raw file](https://github.com/harness/harness-core/blob/7b2bf335399f6faf6660c8848d6b7bf24eb406ca/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java#L536)):*
> ```Java
>           throw new NotFoundException("Role Assignment with given identifier doesn't exists");
>         });
>     if (!checkViewPermission(harnessScopeParams, roleAssignment.getPrincipalType())) {
> ```

Shouldn't this be check the first thing to do?

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36123#-:-NBl4EcC71f61_gtasfd:bnfp4nl)* status: 2 file(s) to review.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36123#-:-NBl5FvA8oLMThKA89vd:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
