### PR TITLE
fix: [CDS-78509]: Add index and remove sort for scheduled trigger iterator

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes
This PR adds a specific index for usage of Scheduled triggers iterator queries. Also makes the iterator query unsorted, to avoid in-memory sorting in DB.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52364)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52364)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/beans/entity/NGTriggerEntity.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/52364#-NdFZY3fEr0ov_ve7z3H:-NdFZY3fEr0ov_ve7z3I:b7hyrnb) ([raw file](https://github.com/harness/harness-core/blob/4b2cafbe0ff4e6b9a17ba76f9ef69392961f1a2d/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/beans/entity/NGTriggerEntity.java#L115)):*
> ```Java
>                 .field(NGTriggerEntityKeys.type)
>                 .field(NGTriggerEntityKeys.enabled)
>                 .field(NGTriggerEntityKeys.deleted)
> ```

deleted is not needed in index as its boolean

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52364)* status: 3 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/beans/entity/NGTriggerEntity.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/52364#-NdFZY3fEr0ov_ve7z3H:-NdFiCT21pkIauDXW1jt:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/4b2cafbe0ff4e6b9a17ba76f9ef69392961f1a2d/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/beans/entity/NGTriggerEntity.java#L115)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

deleted is not needed in index as its boolean
</blockquote></details>

done

**Review by sribalij — APPROVED** [review]

**Comment by vcalasansh** [comment]
trigger messagecheck

**Comment by vcalasansh** [comment]
trigger review

**Pull request merged**
