### PR TITLE
fix: [DEL-4828]: fix interval for auto-upgrade

### PR DESCRIPTION
**Pull request by AnupamIO**
https://harness.atlassian.net/browse/DEL-4828

tested changes on pr env, namespace: del-4382d

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37448)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37448)

**Comment by AnupamIO** [comment]
trigger messagecheck

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37448)* status: :shipit: complete! ✓

___
*[`build.properties` line 3 at r1](https://reviewable.io/reviews/harness/harness-core/37448#-NBqQjM4BqRozLeKV9Iv:-NBqQjM4BqRozLeKV9Iw:b-apsakc) ([raw file](https://github.com/harness/harness-core/blob/9d8b51cecd164add09a3686a4fc57803a1a5526f/build.properties#L3)):*
> ```INI
> build.majorVersion=1
> build.minorVersion=0
> build.number=76707
> ```

We don't need to bump up build number here, we can do patch as 001



_Code quote:_
```INI
76707
```

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37448)* status: 1 file(s) to review. 

___
*[`build.properties` line 3 at r1](https://reviewable.io/reviews/harness/harness-core/37448#-NBqQjM4BqRozLeKV9Iv:-NBqTC7L8qNwFC0HPR_S:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9d8b51cecd164add09a3686a4fc57803a1a5526f/build.properties#L3)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

We don't need to bump up build number here, we can do patch as 001
</blockquote></details>

done

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37448)* status: :shipit: complete! ✓

**Pull request merged**
