### PR TITLE
feat: [PL-22671]: Resource Group V2 DTO

### PR DESCRIPTION
**Pull request by reetika04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30747)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30747)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[940-resource-group-beans/src/test/resources/resourcegroups/accountScopeSelectorAtProject.json, line 1 at r1](https://reviewable.io/reviews/harness/harness-core/30747#-MvvATwf7QYBc7rZivdn:-MvvATwf7QYBc7rZivdo:b9orw9s) ([raw file](https://github.com/harness/harness-core/blob/bebbd63f970c093a2f29857e2e021607075cc39e/940-resource-group-beans/src/test/resources/resourcegroups/accountScopeSelectorAtProject.json#L1)):*
> ```JSON
> {
> ```

@reetika04 Can we have example JSONs of a resource group create at account level for all these cases. It will help in validating once if schema user-friendly and can cover all cases:

1. Account scope but no orgs/projects under the account
2. Just all orgs under the account (but no projects under them. account scope is also excluded)
3. Specific orgs (but none of the projects under them. account scope is also excluded)
4. All Projects in an account (but orgs and account scope are excluded)
5. All Projects under an Org (but orgs and account scope are excluded)
6. Specific Projects under an Org (but orgs and account scope are excluded)

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 11 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30747#-:-Mw4jslA7A8N0UpU-FjE:bnfp4nl)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30747)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[940-resource-group-beans/src/main/java/io/harness/resourcegroup/remote/dto/ResourceGroupV2DTO.java, line 36 at r2](https://reviewable.io/reviews/harness/harness-core/30747#-Mw4k8Ai798gQF2W6Ftu:-Mw4k8Ai798gQF2W6Ftv:b-k5r3u6) ([raw file](https://github.com/harness/harness-core/blob/7a9c59ac2442721f302b2f737afac57c701fc75c/940-resource-group-beans/src/main/java/io/harness/resourcegroup/remote/dto/ResourceGroupV2DTO.java#L36)):*
> ```Java
> @OwnedBy(PL)
> @Schema(name = "ResourceGroupV2", description = "Contains information of Resource Group")
> public class ResourceGroupV2DTO {
> ```

TypeAlias annotation is missing

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 3 of 11 files at r1, 8 of 12 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30747#-:-Mw5NPS90Rj9tsV2Y-u5:bnfp4nl)* status: 6 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30747#-:-Mw5O3g_7pTnaV4DFZfO:bnfp4nl)* status: 4 file(s) to review.

**Review by gupta-utkarsh — APPROVED** [review]
> Reviewed 3 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30747)* status: 4 file(s) to review.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30747#-:-Mw5aQyv8pbFw8FIOwel:bnfp4nl)* status: 4 file(s) to review.

**Review by karansiwach360 — APPROVED** [review]
> Reviewed 3 of 11 files at r1, 10 of 12 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30747)* status: 4 file(s) to review.

**Review by gupta-utkarsh — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30747#-:-MwPj5cQ2sgP-bAjCzTi:bnfp4nl)* status: Some of the checks are too old. 4 file(s) to review.

**Review by karansiwach360 — APPROVED** [review]
> Reviewed 1 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30747)* status: Some of the checks are too old. 4 file(s) to review.

**Review by karansiwach360 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30747)* status: 1 of 2 approvals obtained.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30747#-:-MwQ4Aps1sjndOietff9:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
