### PR TITLE
[feat]: [CDS-68391]: Adding Ng Settings Map to populate Execution Settings

### PR DESCRIPTION
**Pull request by ankittiwari-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47226)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/47226#-NURbfVxDo9Cx1YvH-uF:-NURbfVxDo9Cx1YvH-uG:b9oi13w) ([raw file](https://github.com/harness/harness-core/blob/f8a532cae6b193f9222ecd9ed747344a49fc74a3/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto#L35)):*
> ```protobuf
>   bool useMatrixFieldName = 20;
>   repeated PostExecutionRollbackInfo postExecutionRollbackInfo = 21;
>   map<string, string> pmsNGSettings = 22;
> ```

nit: should we rename to settingToValueMap?
and add a comment as to what we are storing here.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 156 at r1](https://reviewable.io/reviews/harness/harness-core/47226#-NURbpt10WLj0RXYE_PQ:-NURbpt10WLj0RXYE_PR:b28er4l) ([raw file](https://github.com/harness/harness-core/blob/f8a532cae6b193f9222ecd9ed747344a49fc74a3/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L156)):*
> ```Java
> 
>   public static final String ENABLE_MATRIX_FIELD_NAME_SETTING = "enable_matrix_label_by_name";
>   public static final String DEFAULT_IMAGE_PULL_POLICY_ADD_ON_CONTANER =
> ```

Can we move these to PipelineSettingService or create a new file called NGPipelineSettingsConstant?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 340 at r1](https://reviewable.io/reviews/harness/harness-core/47226#-NURbz3ZEFgiu638TD0I:-NURbz3ZEFgiu638TD0J:by2z0wa) ([raw file](https://github.com/harness/harness-core/blob/f8a532cae6b193f9222ecd9ed747344a49fc74a3/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L340)):*
> ```Java
> 
>       Call<ResponseDTO<SettingValueResponseDTO>> ngSettings =
>           settingsClient.getSetting(DEFAULT_IMAGE_PULL_POLICY_ADD_ON_CONTANER, pipelineEntity.getAccountIdentifier(),
> ```

Can we use the list api for fetching the settings?
We have group identifier logic in the settings framework, maybe we can keep all execution related settings under one group and then query via that group?

**Comment by ankittiwari-harness** [comment]
> _[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 340 at r1](https://reviewable.io/reviews/harness/harness-core/47226#-NURbz3ZEFgiu638TD0I:-NURbz3ZEFgiu638TD0J:by2z0wa) ([raw file](https://github.com/harness/harness-core/blob/f8a532cae6b193f9222ecd9ed747344a49fc74a3/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L340)):_
> 
> > ```java
> >       Call<ResponseDTO<SettingValueResponseDTO>> ngSettings =
> >           settingsClient.getSetting(DEFAULT_IMAGE_PULL_POLICY_ADD_ON_CONTANER, pipelineEntity.getAccountIdentifier(),
> > ```
> 
> Can we use the list api for fetching the settings? We have group identifier logic in the settings framework, maybe we can keep all execution related settings under one group and then query via that group?

Done

**Comment by ankittiwari-harness** [comment]
> _[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 156 at r1](https://reviewable.io/reviews/harness/harness-core/47226#-NURbpt10WLj0RXYE_PQ:-NURbpt10WLj0RXYE_PR:b28er4l) ([raw file](https://github.com/harness/harness-core/blob/f8a532cae6b193f9222ecd9ed747344a49fc74a3/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L156)):_
> 
> > ```java
> >   public static final String ENABLE_MATRIX_FIELD_NAME_SETTING = "enable_matrix_label_by_name";
> >   public static final String DEFAULT_IMAGE_PULL_POLICY_ADD_ON_CONTANER =
> > ```
> 
> Can we move these to PipelineSettingService or create a new file called NGPipelineSettingsConstant?

Done

**Comment by ankittiwari-harness** [comment]
> _[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 156 at r1](https://reviewable.io/reviews/harness/harness-core/47226#-NURbpt10WLj0RXYE_PQ:-NURbpt10WLj0RXYE_PR:b28er4l) ([raw file](https://github.com/harness/harness-core/blob/f8a532cae6b193f9222ecd9ed747344a49fc74a3/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L156)):_
> 
> > ```java
> >   public static final String ENABLE_MATRIX_FIELD_NAME_SETTING = "enable_matrix_label_by_name";
> >   public static final String DEFAULT_IMAGE_PULL_POLICY_ADD_ON_CONTANER =
> > ```
> 
> Can we move these to PipelineSettingService or create a new file called NGPipelineSettingsConstant?

Done

**Comment by ankittiwari-harness** [comment]
> _[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/47226#-NURbfVxDo9Cx1YvH-uF:-NURbfVxDo9Cx1YvH-uG:b9oi13w) ([raw file](https://github.com/harness/harness-core/blob/f8a532cae6b193f9222ecd9ed747344a49fc74a3/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto#L35)):_
> 
> > ```proto
> >   bool useMatrixFieldName = 20;
> >   repeated PostExecutionRollbackInfo postExecutionRollbackInfo = 21;
> >   map<string, string> pmsNGSettings = 22;
> > ```
> 
> nit: should we rename to settingToValueMap? and add a comment as to what we are storing here.

Done

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 342 at r3](https://reviewable.io/reviews/harness/harness-core/47226#-NUygcnxEjgiij-fK8qn:-NUygcnxEjgiij-fK8qo:bcd9xj3) ([raw file](https://github.com/harness/harness-core/blob/ece8ace24156fa8ebbd8774980a0cd1b99bf6700/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L342)):*
> ```Java
>     // adding metadata populated by Pipeline NG Settings
>     try {
>       Call<ResponseDTO<List<SettingResponseDTO>>> responseDTOCall =
> ```

Please make similar changes in TriggerExecutionHelper#createPlanExecution and add it in execution metadata

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47226)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47226)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by ankittiwari-harness** [comment]
trigger uts

**Comment by ankittiwari-harness** [comment]
trigger ut0, ut1, ut2, ut3

**Comment by ankittiwari-harness** [comment]
trigger review

**Comment by abhayganvir** [comment]
trigger testuts

**Comment by abhayganvir** [comment]
trigger testuts

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47226)* status: :shipit: complete! ✓

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 697 at r4](https://reviewable.io/reviews/harness/harness-core/47226#-NV3UuqS9ro9Q6tBPtrW:-NV3UuqS9ro9Q6tBPtrX:bsygfmp) ([raw file](https://github.com/harness/harness-core/blob/b48bf6ce809d7afc9fb24980465bf78910077bc7/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L697)):*
> ```Java
>         SettingDTO setting = settingDto.getSetting();
>         if (setting.getName().equals(NGPipelineSettingsConstant.ENABLE_MATRIX_FIELD_NAME_SETTING.getName())
>             && setting.getValue().equals("true")) {
> ```

nit, generally we do reverse checks to avoid unwanted NPEs

like "true".equals(someobject.somefield). If someField is null, the expression won't fail.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 704 at r4](https://reviewable.io/reviews/harness/harness-core/47226#-NV3Uo480HmG2Oyj3R7_:-NV3Uo480HmG2Oyj3R7a:b24z4qi) ([raw file](https://github.com/harness/harness-core/blob/b48bf6ce809d7afc9fb24980465bf78910077bc7/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L704)):*
> ```Java
>       }
>     } catch (Exception e) {
>       log.error("Error in fetching pipeline Settings due to {}", e.getMessage());
> ```

should we not log the full exception including stacktrace? Otherwise that info is lost here.

**Review by nishantsaini20 — APPROVED** [review]
Approved for settings.yml changes

**Review by nishantsaini20 — APPROVED** [review]
Approved for settings.yml changes

**Comment by harshjain12** [comment]
trigger testuts

**Pull request merged**
