### PR TITLE
feat:[CDS-44506]: ssh/winrm Support GCR artifact type

### PR DESCRIPTION
**Pull request by vitsafronovici**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44469)

### CODE REVIEW

**Review by ivan-83 — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44469)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44469)* status: 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java` line 110 at r1](https://reviewable.io/reviews/harness/harness-core/44469#-NPNk68VC7eT9JeIxTXj:-NPNk68VC7eT9JeIxTXk:b-6s2wm3) ([raw file](https://github.com/harness/harness-core/blob/1277a18c3c11a64abd512eae9231c7b555df317c/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java#L110)):*
> ```Java
>     if (artifactDelegateConfig instanceof GcrArtifactDelegateConfig) {
>       throw NestedExceptionUtils.hintWithExplanationException(DOWNLOAD_ARTIFACT_NOT_SUPPORTED_FOR_GCR_ARTIFACT_HINT,
>           DOWNLOAD_ARTIFACT_NOT_SUPPORTED_FOR_GCR_ARTIFACT_EXPLANATION,
> ```

now i'm wondering, for artifactory docker registry we are not throwing exception - only for custom artifact sources we do throw. Shall we make it simillar? We only need to implement the same interface which is `SkipCopyArtifactDelegateConfig`. @ivan-83 what do you think?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/44469#-NPNkWbMDHuw_Jr5bwqb:-NPNkWbMDHuw_Jr5bwqc:b-6ezomv) ([raw file](https://github.com/harness/harness-core/blob/1277a18c3c11a64abd512eae9231c7b555df317c/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java#L132)):*
> ```Java
>             new SshCommandExecutionException(COPY_ARTIFACT_NOT_SUPPORTED_FOR_CUSTOM_ARTIFACT));
>       }
>       if (sshCommandTaskParameters.getArtifactDelegateConfig() instanceof GcrArtifactDelegateConfig) {
> ```

same question for ssh copy

**Review by acasian-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44469)* status: :shipit: complete! ✓

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44469)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44469#-:-NPSgaS_8H9-714Joxy0:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 10 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44469#-:-NPShDeq9jJlItM3mU_U:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
