### PR TITLE
feat: [IDP-1435]: IDP Stage - steps and variable creators

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54615)

### CODE REVIEW

**Comment by devesh-harness** [comment]
trigger messagecheck

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54615)* status: Some of the checks are too old. 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/pipeline/provider/IdpPipelineServiceInfoProvider.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/54615#-NiGV3p_3x3mgKU0c0iB:-NiGV3p_3x3mgKU0c0iC:b-e6ewuo) ([raw file](https://github.com/harness/harness-core/blob/5944c24a3ed13c0a6408daeca7872e3b6c0a6120/idp-service/src/main/java/io/harness/idp/pipeline/provider/IdpPipelineServiceInfoProvider.java#L52)):*
> ```Java
>     //    planCreators.add(new IDPStagePlanCreator());
>     //    planCreators.add(new IDPStepPlanCreator());
>     planCreators.add(new RunStepPlanCreator());
> ```

Why not registering IDPStagePlanCreator?
___
*[`idp-service/src/main/java/io/harness/idp/pipeline/provider/IdpPipelineServiceInfoProvider.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/54615#-NiGV8h76bvweoyNMaJH:-NiGV8h76bvweoyNMaJI:bhxa77z) ([raw file](https://github.com/harness/harness-core/blob/5944c24a3ed13c0a6408daeca7872e3b6c0a6120/idp-service/src/main/java/io/harness/idp/pipeline/provider/IdpPipelineServiceInfoProvider.java#L65)):*
> ```Java
>     List<FilterJsonCreator> filterJsonCreators = new ArrayList<>();
>     //    filterJsonCreators.add(new IDPStageFilterCreator());
>     //    filterJsonCreators.add(new IDPStepFilterJsonCreator());
> ```

These should be uncommented right



_Code quote:_
```Java
    //    filterJsonCreators.add(new IDPStageFilterCreator());
    //    filterJsonCreators.add(new IDPStepFilterJsonCreator());
```
___
*[`idp-service/src/main/java/io/harness/idp/pipeline/provider/IdpPipelineServiceInfoProvider.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/54615#-NiGVCs21_wTG3xMqiBI:-NiGVCs21_wTG3xMqiBJ:baqpcyc) ([raw file](https://github.com/harness/harness-core/blob/5944c24a3ed13c0a6408daeca7872e3b6c0a6120/idp-service/src/main/java/io/harness/idp/pipeline/provider/IdpPipelineServiceInfoProvider.java#L75)):*
> ```Java
>     List<VariableCreator> variableCreators = new ArrayList<>();
>     variableCreators.add(new IDPStageVariableCreator());
>     variableCreators.add(new IDPStepVariableCreator());
> ```

IDPStepVariableCreator supports all the 4 step-types. Either keep this or the below individual variable-creators for each step. If any step's variable-creator is not adding any specific variables then use the IDPStepVariableCreator for such steps. 



_Code quote:_
```Java
IDPStepVariableCreator
```
___
*[`idp-service/src/main/java/io/harness/idp/pipeline/registrar/IdpStepRegistrar.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/54615#-NiGVqW-7sOPVmobLo2Y:-NiGVqW-7sOPVmobLo2Z:b-6cnth7) ([raw file](https://github.com/harness/harness-core/blob/5944c24a3ed13c0a6408daeca7872e3b6c0a6120/idp-service/src/main/java/io/harness/idp/pipeline/registrar/IdpStepRegistrar.java#L37)):*
> ```Java
> 
>     engineSteps.put(InitializeTaskStep.STEP_TYPE, InitializeTaskStepV2.class);
>     //    engineSteps.put(IDPStageStepPMS.STEP_TYPE, IDPStageStepPMS.class);
> ```

How is it working after commenting this? Stage should be registered.



_Code quote:_
```Java
 engineSteps.put(IDPStageStepPMS.STEP_TYPE, IDPStageStepPMS.class);
```

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54615)* status: Some of the checks are too old. 10 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/pipeline/provider/IdpPipelineServiceInfoProvider.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/54615#-NiGV3p_3x3mgKU0c0iB:-NiIRZAS9jlZe0AxaZZ2:b-ysqplk) ([raw file](https://github.com/harness/harness-core/blob/5944c24a3ed13c0a6408daeca7872e3b6c0a6120/idp-service/src/main/java/io/harness/idp/pipeline/provider/IdpPipelineServiceInfoProvider.java#L52)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Why not registering IDPStagePlanCreator?
</blockquote></details>

this will be registered this was just done to start the service as on breaking in multiple prs, few of things were in different branches, they will be un commented in final merged branch.
___
*[`idp-service/src/main/java/io/harness/idp/pipeline/provider/IdpPipelineServiceInfoProvider.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/54615#-NiGV8h76bvweoyNMaJH:-NiIRkpE3r76SvyVulV5:b-ysqplk) ([raw file](https://github.com/harness/harness-core/blob/5944c24a3ed13c0a6408daeca7872e3b6c0a6120/idp-service/src/main/java/io/harness/idp/pipeline/provider/IdpPipelineServiceInfoProvider.java#L65)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

These should be uncommented right
</blockquote></details>

this will be registered this was just done to start the service as on breaking in multiple prs, few of things were in different branches, they will be un commented in final merged branch.

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54615)* status: Some of the checks are too old. 10 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/pipeline/registrar/IdpStepRegistrar.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/54615#-NiGVqW-7sOPVmobLo2Y:-NiIRpgV8NfMIR0wGfSz:b-ysqplk) ([raw file](https://github.com/harness/harness-core/blob/5944c24a3ed13c0a6408daeca7872e3b6c0a6120/idp-service/src/main/java/io/harness/idp/pipeline/registrar/IdpStepRegistrar.java#L37)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

How is it working after commenting this? Stage should be registered.
</blockquote></details>

this will be registered this was just done to start the service as on breaking in multiple prs, few of things were in different branches, they will be un commented in final merged branch.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54615)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
