### PR TITLE
fix: [cds-45386] Blank check for service override variables

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
Added blank check for service override variables
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40913)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java` line 153 at r2](https://reviewable.io/reviews/harness/harness-core/40913#-NIBQvsW3Og2n8HLL6p-:-NIBQvsW3Og2n8HLL6p0:b-e6shn5) ([raw file](https://github.com/harness/harness-core/blob/7b44c64e06644162f1406210bb5630a242ed7da0/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java#L153)):*
> ```Java
>       int emptyOverrides = 0;
>       for (NGVariable variableOverride : variableOverrides) {
>         if (StringUtils.isBlank(variableOverride.getName())) {
> ```

lets use StringUtils from `org.apache.commons.lang3`

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40913)* status: 1 file(s) to review. 0 of 1 approvals obtained.

**Comment by vivekkarnatiharness** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java` line 153 at r2](https://reviewable.io/reviews/harness/harness-core/40913#-NIBQvsW3Og2n8HLL6p-:-NIBRiLj8cwq14Xa87aL:btpte1o) ([raw file](https://github.com/harness/harness-core/blob/7b44c64e06644162f1406210bb5630a242ed7da0/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java#L153)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets use StringUtils from `org.apache.commons.lang3` 
</blockquote></details>

fixed it

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40913)* status: :shipit: complete! ✓

**Review by hingerabhinav — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40913)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40913)* status: :shipit: complete! ✓

**Pull request merged**
