### PR TITLE
fix: [CDS-37961]: Changes for overview dashboard

### PR DESCRIPTION
**Pull request by shivamnegi94**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33441)

### CODE REVIEW

**Comment by shivamnegi94** [comment]
trigger messagecheck

**Comment by shivamnegi94** [comment]
trigger ft1

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33441)* status: Some of the checks are too old.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33441)* status: Some of the checks are too old.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33441)* status: :shipit: complete! ✓

**Pull request merged**
