### PR TITLE
techdebt: [DEL-5678]: Granular builds and cycle fixes for 970-api-services-beans

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

This PR breaks down 970-api-services-beans into smaller granular builds and fixes the following cycle - 

.-> //970-api-services-beans/src/main/java/io/harness/k8s/model:module 
|   //970-api-services-beans/src/main/java/io/harness/k8s/manifest:module 
`-- //970-api-services-beans/src/main/java/io/harness/k8s/model:module 

This PR https://github.com/harness/harness-core/pull/42623 fixes the other cycle and contains the rest of the granular builds for 970-api-services-beans.

Tested in PR env for End-to-End K8s deployment workflow.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42577)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 91 of 91 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42577)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`970-api-services-beans/BUILD.bazel` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/42577#-NLew3KoEjp7GOKRMk6F:-NLew3KoEjp7GOKRMk6G:b4c8nhh) ([raw file](https://github.com/harness/harness-core/blob/1449d624b7391ac92ad485e441f1ef278d255a31/970-api-services-beans/BUILD.bazel#L14)):*
> ```Starlark
>     srcs = glob(["src/main/java/**/*.java"]),
>     visibility = ["//visibility:public"],
>     deps = [
> ```

exports?
___
*[`970-api-services-beans/BUILD.bazel` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/42577#-NLew-iG9mKMbuNEqK8y:-NLew-iH15Tp20q4gfqd:b-crfwsh) ([raw file](https://github.com/harness/harness-core/blob/1449d624b7391ac92ad485e441f1ef278d255a31/970-api-services-beans/BUILD.bazel#L126)):*
> ```Starlark
>         "@maven//:com_sumologic_api_client_sumo_java_client",
>         "@maven//:io_fabric8_kubernetes_client",
>         "@maven//:io_harness_ng_license_beans",
> ```

license beans
___
*[`970-api-services-beans/src/main/java/io/harness/logging/serializer/kryo/BUILD.bazel` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/42577#-NLexCaY7Edm_ePtQg-v:-NLexCaY7Edm_ePtQg-w:b-crfwsh) ([raw file](https://github.com/harness/harness-core/blob/1449d624b7391ac92ad485e441f1ef278d255a31/970-api-services-beans/src/main/java/io/harness/logging/serializer/kryo/BUILD.bazel#L19)):*
> ```Starlark
>         "//999-annotations/src/main/java/io/harness/annotations/dev:module",
>         "@maven//:com_esotericsoftware_kryo",
>         "@maven//:io_harness_ng_license_beans",
> ```

license beans

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42577)* status: 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`970-api-services-beans/BUILD.bazel` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/42577#-NLew3KoEjp7GOKRMk6F:-NLgZhYy9eJZXyKytkKQ:br4p4li) ([raw file](https://github.com/harness/harness-core/blob/1449d624b7391ac92ad485e441f1ef278d255a31/970-api-services-beans/BUILD.bazel#L14)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

exports?
</blockquote></details>

Actually as part of this PR I've fixed only one cycle and added most of the granular builds. But there are 8 more granular builds that needs to be added along with another cycle fix. I will raise a separate PR for that and will make it exports as then it will have all granular builds. 
___
*[`970-api-services-beans/BUILD.bazel` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/42577#-NLew-iG9mKMbuNEqK8y:-NLg_-My6QanvRrRxJVq:by96hxd) ([raw file](https://github.com/harness/harness-core/blob/1449d624b7391ac92ad485e441f1ef278d255a31/970-api-services-beans/BUILD.bazel#L126)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

license beans
</blockquote></details>

Yeah, this was causing some peculiar compile issue. Removed it, thanks!
___
*[`970-api-services-beans/src/main/java/io/harness/logging/serializer/kryo/BUILD.bazel` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/42577#-NLexCaY7Edm_ePtQg-v:-NLg_4zr3OkbwJ8Ez9nK:b32n8ta) ([raw file](https://github.com/harness/harness-core/blob/1449d624b7391ac92ad485e441f1ef278d255a31/970-api-services-beans/src/main/java/io/harness/logging/serializer/kryo/BUILD.bazel#L19)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

license beans
</blockquote></details>

Removed it.

**Review by mdmilic — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42577)* status: :shipit: complete! ✓

**Comment by Raghav-Murali** [comment]
trigger checkstylecodeformat, ft1, ft2

**Comment by Raghav-Murali** [comment]
trigger ft1, ft2

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by gn-harness — APPROVED** [review]
> Reviewed 82 of 91 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 4 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42577)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 4 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42577)* status: :shipit: complete! ✓

**Pull request merged**
