### PR TITLE
techdebt: [CDS-82771]: Add jmx agent to debezium service

### PR DESCRIPTION
**Pull request by rohitk-h**
## Describe your changes
- Add JMX java agent to publish JMX metrics for debezium service. We were publish all the JMX metrics on port 73734 for now. The config file is setup to publish all. 
- Updated list of metrics we will publish
- 
[debezium_jmx_metrics.txt](https://github.com/harness/harness-core/files/13382698/debezium_jmx_metrics.txt)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55316)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`debezium-service/config/jmx_prometheus_config.yml` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/55316#-NjGEb3J0TO7DNmvTG3u:-NjGEb3J0TO7DNmvTG3v:ben2p6u) ([raw file](https://github.com/harness/harness-core/blob/277fee69fb45ca175a90efee9ac2e23256ef3028/debezium-service/config/jmx_prometheus_config.yml#L2)):*
> ```YAML
> rules:
>   - pattern: ".*"
> ```

Should we start with only few metrics?

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55316)* status: Some of the checks are too old. 5 file(s) to review. 0 of 2 approvals obtained.

**Comment by rohitk-h** [comment]
*[`debezium-service/config/jmx_prometheus_config.yml` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/55316#-NjGEb3J0TO7DNmvTG3u:-NjOe-XUCC_p1YITtvj2:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/277fee69fb45ca175a90efee9ac2e23256ef3028/debezium-service/config/jmx_prometheus_config.yml#L2)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should we start with only few metrics?
</blockquote></details>

updated

**Review by Raghav-Murali — APPROVED** [review]

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55316)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`debezium-service/container/scripts/start_process.sh` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/55316#-NjRClU51eqqr7AYf0IM:-NjRClU51eqqr7AYf0IN:byd1urg) ([raw file](https://github.com/harness/harness-core/blob/4de74e92b4b0931263cf6248d8075d3dd5307393/debezium-service/container/scripts/start_process.sh#L39)):*
> ```Shell
> 
> if [[ "${ENABLE_JMX_PROMETHEUS}" == "true" ]]; then
>     JAVA_OPTS=$JAVA_OPTS" -javaagent:/opt/harness/jmx_prometheus_javaagent-0.17.0.jar=73734:jmx_prometheus_config.yaml"
> ```

can you use variables for port here as well

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55316)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions.

**Comment by rohitk-h** [comment]
*[`debezium-service/container/scripts/start_process.sh` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/55316#-NjRClU51eqqr7AYf0IM:-NjTWt8h-XnAKR1nHTsA:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/4de74e92b4b0931263cf6248d8075d3dd5307393/debezium-service/container/scripts/start_process.sh#L39)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you use variables for port here as well
</blockquote></details>

updated

**Review by vcalasansh — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55316#-:-NjTXteP8SSroUxQgeHr:bnfp4nl)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by rohitk-h** [comment]
trigger review

**Review by sribalij — DISMISSED** [review]

**Comment by rohitk-h** [comment]
trigger review

**Comment by sribalij** [comment]
trigger review

**Comment by rohitk-h** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55316)* status: 1. unresolved discussions.

**Comment by rohitk-h** [comment]
trigger uts

**Comment by rohitk-h** [comment]
trigger uts

**Comment by rohitk-h** [comment]
trigger uts

**Comment by rohitk-h** [comment]
trigger uts

**Comment by rohitk-h** [comment]
trigger uts

**Comment by rohitk-h** [comment]
trigger ut7

**Review by archit-harness — APPROVED** [review]

**Review by Raghav-Murali — APPROVED** [review]

**Comment by rohitk-h** [comment]
trigger review

**Pull request merged**
