### PR TITLE
[feat]: [PIE-6872]: Add async validation option to pipeline get

### PR DESCRIPTION
**Pull request by namanvermah**
Impact: Additional (optional) flag to get pipeline call whose default value corresponds to the existing behaviour
Testing: E2E testing done locally

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41346)

### CODE REVIEW

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41346)* status: Some of the checks are too old. 4 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41346)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 131 at r2](https://reviewable.io/reviews/harness/harness-core/41346#-NJ41jVTCTN7v3GFsqsx:-NJ41jVV5eDQkL8Bi_s2:b-8s3gs4) ([raw file](https://github.com/harness/harness-core/blob/2ee2d6feb61a29e01d1fdda5e098f25b4c5a0c56/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L131)):*
> ```Java
>     if (validateAsync) {
>       // todo: add schema validations
>       pipelineEntity = pmsPipelineService.getPipeline(account, org, project, pipeline, false, false,
> ```

this method does schema validation as well, plus other validation



_Code quote:_
```Java
pmsPipelineService.getPipeline
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 146 at r2](https://reviewable.io/reviews/harness/harness-core/41346#-NJ41sU7Bjt3I40t40J3:-NJ41sU7Bjt3I40t40J4:bvq90u1) ([raw file](https://github.com/harness/harness-core/blob/2ee2d6feb61a29e01d1fdda5e098f25b4c5a0c56/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L146)):*
> ```Java
>       if (optionalEvent.isPresent()) {
>         validationUUID = optionalEvent.get().getUuid();
>       } else {
> ```

Lets discuss this in a call



_Code quote:_
```Java
      // getting the branch from SCM Git Metadata because the branch in API request can be null, and the default branch
      // value is needed
      String branchFetchedFrom = GitAwareContextHelper.getBranchInSCMGitMetadata();
      String fqn = PipelineAsyncValidationHelper.buildFQN(pipelineEntity.get(), branchFetchedFrom);
      Optional<PipelineValidationEvent> optionalEvent =
          pipelineAsyncValidationService.getLatestEventByFQNAndAction(fqn, Action.CRUD);
      if (optionalEvent.isPresent()) {
        validationUUID = optionalEvent.get().getUuid();
      } else {
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41346)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 140 at r2](https://reviewable.io/reviews/harness/harness-core/41346#-NJEyqwN4TcX1h69oI1C:-NJEyqwN4TcX1h69oI1D:bax7v5x) ([raw file](https://github.com/harness/harness-core/blob/2ee2d6feb61a29e01d1fdda5e098f25b4c5a0c56/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L140)):*
> ```Java
>       // getting the branch from SCM Git Metadata because the branch in API request can be null, and the default branch
>       // value is needed
>       String branchFetchedFrom = GitAwareContextHelper.getBranchInSCMGitMetadata();
> ```

Rename branchFetchedFrom to branchFetchedFromScm



_Code quote:_
```Java
branchFetchedFrom
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41346)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 140 at r2](https://reviewable.io/reviews/harness/harness-core/41346#-NJEyqwN4TcX1h69oI1C:-NJF-i5u9kiY9fT58o2K:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2ee2d6feb61a29e01d1fdda5e098f25b4c5a0c56/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L140)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Rename branchFetchedFrom to branchFetchedFromScm
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41346)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41346)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41346)* status: :shipit: complete! ✓

**Pull request merged**
