### PR TITLE
fix: [CDS-34516]: Create (and delete) temp dir to ensure we don't run…

### PR DESCRIPTION
**Pull request by achyuth-harness**
… into concurrency issues while executing helm repo add, update and pull in parallel

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31268)

### CODE REVIEW

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31268)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 410 at r2](https://reviewable.io/reviews/harness/harness-core/31268#-MxgLCvl2zvTpj6R3G58:-MxgLCvo4xd1OO6CEpzU:b-xb5nx6) ([raw file](https://github.com/harness/harness-core/blob/ff40d21eac757e8879bdde11dcaecfe57fd67182/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L410)):*
> ```Java
>         repoName, dir, chartVersion, checkIncorrectChartVersion);
> 
>     if (deleteRepoCacheDir) {
> ```

deletion should happen in a finally block to make sure it does not get skipped in case of exceptions for eg.

try {
     executeFetchChartFromRepoUseRepoFlag(chartName, chartDirectory, repoDisplayName, helmFetchCommand, timeoutInMillis,
        repoName, dir, chartVersion, checkIncorrectChartVersion)
} finally {
  // Delete dir here
}

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31268)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 410 at r2](https://reviewable.io/reviews/harness/harness-core/31268#-MxgLCvl2zvTpj6R3G58:-MxhNIki6LLNY1V0PHuJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff40d21eac757e8879bdde11dcaecfe57fd67182/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L410)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

deletion should happen in a finally block to make sure it does not get skipped in case of exceptions for eg.

try {
     executeFetchChartFromRepoUseRepoFlag(chartName, chartDirectory, repoDisplayName, helmFetchCommand, timeoutInMillis,
        repoName, dir, chartVersion, checkIncorrectChartVersion)
} finally {
  // Delete dir here
}
</blockquote></details>

Done.

**Review by abosii-harness — DISMISSED** [review]
Do we have any unit tests for this?

> Reviewed 7 of 10 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31268#-:-Mxhb2NW8otNMFTUEpiR:bjfzhkp)* status: 1 change requests. 1. unresolved discussions.

**Review by achyuth-harness — COMMENTED** [review]
Added

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31268#-:-MxiNvEq-vItXYUjA8md:b-8b11j9)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31268)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31268)* status: :shipit: complete! ✓

**Comment by achyuth-harness** [comment]
This PR does NOT have a new task type.

will the new version of the delegate receive old version task and process? -- YES
If new version of the manager receives response for the old task will it be able to handle it successfully? -- YES

cc: @abhinav-harness

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 6 of 10 files at r1, 1 of 2 files at r2, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31268#-:-MxmcZpBBHQJndHFaFJx:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
