### PR TITLE
feat: [DEL-5818]: Add module complexity computation to build cleaner tool

### PR DESCRIPTION
**Pull request by Raghav-Murali**
This PR adds the module complexity computation functionality to the build cleaner tool. A new option `--computeOnlyModuleComplexity` will fetch all the dependencies for the provided module and compute its complexity. The complexity computation takes into account the number of intra module dependencies to predict how complex it could be to break the module into granular targets.

Tested these changes locally for module complexity computation.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43791)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43791)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 293 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOByzLk92srBRz_jS0f:-NOByzLnBASklT7djy5y:b-rqx92q) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L293)):*
> ```Java
>     }
> 
>     return computePathDepth(path.substring(slashIdx)) + 1;
> ```

Seems like you want to count number of occurrences of '/'. Why not do just that, I think recursion is an overkill. You have things like `StringUtils.countMatches(path, "/");`
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOC2RX_4lVBkIheHyTc:-NOC2RXa0jVaiHAJjj5t:b7s3xhm) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L24)):*
> ```Java
>     dependencies = new HashMap<>();
>     dependencies.put("intra", new ArrayList<>());
>     dependencies.put("inter", new ArrayList<>());
> ```

I think having just two separate list instead of this Map would be easier and faster. 



_Code quote:_
```Java
    dependencies = new HashMap<>();
    dependencies.put("intra", new ArrayList<>());
    dependencies.put("inter", new ArrayList<>());
```
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOC1wXC6771bvqWDb0G:-NOC1wXC6771bvqWDb0H:b184r5j) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L38)):*
> ```Java
>     }
> 
>     String parsedDep = dependency.substring(0, slashIndex + 2).substring(2);
> ```

why not dependency.substring(2, slashIndex+2)
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOC0GC65R_nht3GSNEO:-NOC0GC65R_nht3GSNEP:b3yxqxo) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L59)):*
> ```Java
>     int diffPathDeps = 0;
> 
>     System.out.println(" computeIntraModuleComplexity : for subModule { " + subModule + "}");
> ```

Add proper logger
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOC0Ru00GlWtaUXlcxC:-NOC0Ru00GlWtaUXlcxD:b-e1jlff) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L73)):*
> ```Java
>     }
> 
>     return (diffPathDeps * 0.7) + (samePathDeps * 0.3);
> ```

Is this a good metric when some modules moved to using package level targets and some haven't. E.g. lets say you scan 260-delegate which has quite a lot of package level targets used (meaning quite a lot of intra deps) vs 400-rest which have none (hence fewer intra deps). 
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOC1K5h7CtNH85k5Q0B:-NOC1K5i9L5W2xV7Nw9R:b-7fqgrx) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L83)):*
> ```Java
>    * @return
>    */
>   private int comparePaths(String mod1, String mod2) {
> ```

If those are real paths or at least something that looks like a path, you could manipulate them easier if you used `Path` objects. They have bunch of helper methods for these very things.

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43791)* status: Some of the checks are too old. 2 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOReW2jC263M-iwT4Fb:-NOReW2jC263M-iwT4Fc:b-nxjqdl) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L96)):*
> ```Java
>           });
> 
>       computeModuleComplexity();
> ```

return computeModuleComplexity()
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 297 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NORfgco3D1cZL4RFHKj:-NORfgco3D1cZL4RFHKk:b-cp6x0y) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L297)):*
> ```Java
> 
>   /**
>    * Helper method to build the dependency map to
> ```

Can you please add some comments on how is this different from harnessSymbolMap

probably give an example
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 310 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NORfZBy-qc0AYnSBv4z:-NORfZBy-qc0AYnSBv5-:bpuoin5) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L310)):*
> ```Java
> 
>       Set<String> dependencies = getModuleDependencies(path, classpathParser, harnessSymbolMap);
>       if (dependencies.size() == 0) {
> ```

isEmpty?
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NORhdGr8O6KaOwRp7Jl:-NORhdGr8O6KaOwRp7Jm:b-28l2cr) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L20)):*
> ```Java
> 
>   ModuleDependencyInfo(String module, String path) {
>     this.parentModule = module.substring(0, module.indexOf("/"));
> ```

nit: stay consistent with "this" across fields
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOC2RX_4lVBkIheHyTc:-NORhZSD-8qV3DyKpiOk:b32v57) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L24)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I think having just two separate list instead of this Map would be easier and faster. 
</blockquote></details>

+1
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NORmPqS6DhIM5mEm5at:-NORmPqS6DhIM5mEm5au:b-9qpvhd) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L60)):*
> ```Java
> 
>     System.out.println(" computeIntraModuleComplexity : for subModule { " + subModule + "}");
>     for (String intraDep : intraDeps) {
> ```

Can you please add an example to demonstrate the logic for module complexity calculation.

and same for comparePaths function

this is especially confusing when we have "computeIntraM*" and reading diffPathsDeps and samePathsDeps

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43791)* status: Some of the checks are too old. 2 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOReW2jC263M-iwT4Fb:-NOuTFai6jcLgItq-BJq:b-ce3283) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L96)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

return computeModuleComplexity()
</blockquote></details>

It throws an error with this even though computeModuleComplexity() is returning void. 
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 293 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOByzLk92srBRz_jS0f:-NOuV6jND-r37bUHplBl:b-p063i) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L293)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Seems like you want to count number of occurrences of '/'. Why not do just that, I think recursion is an overkill. You have things like `StringUtils.countMatches(path, "/");`
</blockquote></details>

Ah, yes. Will replace it.
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 297 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NORfgco3D1cZL4RFHKj:-NOugj1VDxhaFrWkZG9o:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L297)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Can you please add some comments on how is this different from harnessSymbolMap

probably give an example
</blockquote></details>

Done
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 310 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NORfZBy-qc0AYnSBv4z:-NOugo4YEKU2Qin1sJjW:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L310)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

isEmpty?
</blockquote></details>

Done
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NORhdGr8O6KaOwRp7Jl:-NOugz7M4Drc7wTFoIza:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L20)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

nit: stay consistent with "this" across fields
</blockquote></details>

Done
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOC2RX_4lVBkIheHyTc:-NOuhrxRC1n199NpIk_b:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L24)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOC1wXC6771bvqWDb0G:-NOuifm58eQWox4Ei8vs:b-p2uy0s) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L38)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

why not dependency.substring(2, slashIndex+2)
</blockquote></details>

Yes, will update it.
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOC0GC65R_nht3GSNEO:-NOujVYUC_z9v61p-r9-:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L59)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Add proper logger
</blockquote></details>

Done
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NORmPqS6DhIM5mEm5at:-NOv15rEEn1gegvHOHjY:bx1luwb) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L60)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Can you please add an example to demonstrate the logic for module complexity calculation.

and same for comparePaths function

this is especially confusing when we have "computeIntraM*" and reading diffPathsDeps and samePathsDeps 
</blockquote></details>

Okay, I have added detailed comments with examples for these 2 methods.
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOC0Ru00GlWtaUXlcxC:-NOv1Eh45-aSW352U9-3:b-6znbbc) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L73)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Is this a good metric when some modules moved to using package level targets and some haven't. E.g. lets say you scan 260-delegate which has quite a lot of package level targets used (meaning quite a lot of intra deps) vs 400-rest which have none (hence fewer intra deps). 
</blockquote></details>

So far in all the modules that we added granular build targets and fixed the cycles like 980-commons, 970-api-services-beans, 960-api-services etc. We observed that the modules that had a lot of intra deps had lot more cycles to fix whereas the ones that didn't have much intra deps did not have much cycles. The only exception for this was 960-api-services but rest all the modules adhered to this observation.

So 260-delegate will be having more cycles to fix even after all its inter deps (970-ng-commons, 980-commons etc) are fixed. However, 400-rest might not have any cycles to fix within that module after all its inter deps are fixed.

We're considering this from within a module perspective and hence only intra deps. If it has dependency on other modules then the complexity for those other modules should be looked into to gauge how much work this module would have.
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOC1K5h7CtNH85k5Q0B:-NOv2pSGAJ5G_TRs2nos:b-vh9u5t) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L83)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

If those are real paths or at least something that looks like a path, you could manipulate them easier if you used `Path` objects. They have bunch of helper methods for these very things. 
</blockquote></details>

These are sub-strings of an actual path string.

**Review by mdmilic — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43791)* status: 1 change requests. 4. unresolved discussions. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOC0Ru00GlWtaUXlcxC:-NOvM-rYCoIYajqF7oU3:b-5nllhq) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L73)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

So far in all the modules that we added granular build targets and fixed the cycles like 980-commons, 970-api-services-beans, 960-api-services etc. We observed that the modules that had a lot of intra deps had lot more cycles to fix whereas the ones that didn't have much intra deps did not have much cycles. The only exception for this was 960-api-services but rest all the modules adhered to this observation.

So 260-delegate will be having more cycles to fix even after all its inter deps (970-ng-commons, 980-commons etc) are fixed. However, 400-rest might not have any cycles to fix within that module after all its inter deps are fixed.

We're considering this from within a module perspective and hence only intra deps. If it has dependency on other modules then the complexity for those other modules should be looked into to gauge how much work this module would have.
</blockquote></details>

Lets try it out and see how it goes. I fear that modules that don't use package level targets from their deps are hiding those cycles. 400-rest probably doesn't matter, I think that module should disappear once we pluck everything we need and kill CG manager. 930-delegate-tasks probably has ton of cycles, but I think didn't move to use package level targets (e.g. from 980-commons, it just brings entire 980-commons), so has little intra deps

**Review by gn-harness — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43791)* status: 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained.

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43791)* status: 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/43791#-NOC0Ru00GlWtaUXlcxC:-NP-twInAvy57FTu9eYe:buecixn) ([raw file](https://github.com/harness/harness-core/blob/ae2baa8155f2472ddaed4248313b95575f51d68d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/ModuleDependencyInfo.java#L73)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Lets try it out and see how it goes. I fear that modules that don't use package level targets from their deps are hiding those cycles. 400-rest probably doesn't matter, I think that module should disappear once we pluck everything we need and kill CG manager. 930-delegate-tasks probably has ton of cycles, but I think didn't move to use package level targets (e.g. from 980-commons, it just brings entire 980-commons), so has little intra deps
</blockquote></details>

Yeah, will evaluate the metrics with new modules that we're working on and can improve it.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43791)* status: :shipit: complete! ✓

**Pull request merged**
