### PR TITLE
[feat]: [SRM-13703]: added test cases healthsourceonboardingservice and healthsource serde

### PR DESCRIPTION
**Pull request by n00bitax**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43096)

### CODE REVIEW

**Review by naveen-harness — DISMISSED** [review]

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43096)* status: 8 file(s) to review. 1 change requests. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/resources/HealthSourceOnboardingResourceTest.java` line 196 at r2](https://reviewable.io/reviews/harness/harness-core/43096#-NN-wxCvA7wUcAcn0SGs:-NN-wxCvA7wUcAcn0SGt:bsx4fo8) ([raw file](https://github.com/harness/harness-core/blob/4292987e2c4087004d3bc1e928c07e5bdd285b6d/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/resources/HealthSourceOnboardingResourceTest.java#L196)):*
> ```Java
>     SumologicLogSampleDataRequest request = SumologicLogSampleDataRequest.builder()
>                                                 .type(DataCollectionRequestType.SUMOLOGIC_LOG_SAMPLE_DATA)
>                                                 .from("2022-11-11T03:30:00")
> ```

Use the same variables of startTime and endTime above
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/resources/HealthSourceOnboardingResourceTest.java` line 233 at r2](https://reviewable.io/reviews/harness/harness-core/43096#-NN-vlJh1ndVy3wsgnjj:-NN-vlJh1ndVy3wsgnjk:b-qqylva) ([raw file](https://github.com/harness/harness-core/blob/4292987e2c4087004d3bc1e928c07e5bdd285b6d/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/resources/HealthSourceOnboardingResourceTest.java#L233)):*
> ```Java
>   }
>   /*
>       @Test
> ```

Please remove these.

**Comment by n00bitax** [comment]
trigger messagecheck

**Review by n00bitax — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43096)* status: 589 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/resources/HealthSourceOnboardingResourceTest.java` line 196 at r2](https://reviewable.io/reviews/harness/harness-core/43096#-NN-wxCvA7wUcAcn0SGs:-NN59IoQCNU4VfBhvMWD:b5s32xq) ([raw file](https://github.com/harness/harness-core/blob/4292987e2c4087004d3bc1e928c07e5bdd285b6d/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/resources/HealthSourceOnboardingResourceTest.java#L196)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Use the same variables of startTime and endTime above
</blockquote></details>

derived from same fixes value now
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/resources/HealthSourceOnboardingResourceTest.java` line 233 at r2](https://reviewable.io/reviews/harness/harness-core/43096#-NN-vlJh1ndVy3wsgnjj:-NN59GWp-d3EbO1fzvVU:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/4292987e2c4087004d3bc1e928c07e5bdd285b6d/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/resources/HealthSourceOnboardingResourceTest.java#L233)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Please remove these. 
</blockquote></details>

done

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 2 of 3 files at r2, 581 of 582 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43096)* status: :shipit: complete! ✓

**Pull request merged**
