### PR TITLE
fix: [DEL-5163]: Check to release profile lock

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
- If profile.lock file exists more than 10 mins, then release lock

Test
- Verified profile.lock file set lastModified value correctly
- Manually add profile.lock older than 10 mins, and verified releaselock() getting called

## Checklist
- [ x] I've documented the changes in the PR description.
- [ x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39153)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39153)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 675 at r1](https://reviewable.io/reviews/harness/harness-core/39153#-NF9tblmDpLA75xVLeeC:-NF9tblmDpLA75xVLeeD:b-7vvlcl) ([raw file](https://github.com/harness/harness-core/blob/ed5480a62e6958880f700d1621f6c58264da0cbb/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L675)):*
> ```Java
>       if (!isImmutableDelegate) {
>         // before start profile, add check to see if lock is not released for profile, then release lock
>         if (isLocked(new File("profile"))) {
> ```

isLocked should go inside the releaseLock check, but looking at the releaseLock code it actually checks for this anyway, so you don't need it. Plus you are creating two file objects. 
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1114 at r1](https://reviewable.io/reviews/harness/harness-core/39153#-NF9upuA7SaubDxeD-Ud:-NF9upuA7SaubDxeD-Ue:bqebhii) ([raw file](https://github.com/harness/harness-core/blob/ed5480a62e6958880f700d1621f6c58264da0cbb/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1114)):*
> ```Java
>       File profileFile = new File("profile");
>       try {
>         if (acquireLock(profileFile, ofMinutes(3))) {
> ```

why this change?

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 675 at r1](https://reviewable.io/reviews/harness/harness-core/39153#-NF9tblmDpLA75xVLeeC:-NFAeXqU7a7lgvQh43Ve:bjrheql) ([raw file](https://github.com/harness/harness-core/blob/ed5480a62e6958880f700d1621f6c58264da0cbb/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L675)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

isLocked should go inside the releaseLock check, but looking at the releaseLock code it actually checks for this anyway, so you don't need it. Plus you are creating two file objects. 
</blockquote></details>

this is not finalized. im checking how can issue reported by customer

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1114 at r1](https://reviewable.io/reviews/harness/harness-core/39153#-NF9upuA7SaubDxeD-Ud:-NFAendY3oPISICGh4j8:b8vmhzi) ([raw file](https://github.com/harness/harness-core/blob/ed5480a62e6958880f700d1621f6c58264da0cbb/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1114)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

why this change?
</blockquote></details>

profile check is 3 min interval, so why need 5 min wait time for acquire lock?

**Review by raghuAtWings — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39153)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 675 at r1](https://reviewable.io/reviews/harness/harness-core/39153#-NF9tblmDpLA75xVLeeC:-NFBDQXv7sfBNscHsTAA:b-rcnut8) ([raw file](https://github.com/harness/harness-core/blob/ed5480a62e6958880f700d1621f6c58264da0cbb/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L675)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

this is not finalized. im checking how can issue reported by customer
</blockquote></details>

i think this is not necessary

**Review by raghuAtWings — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39153)* status: 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1158 at r1](https://reviewable.io/reviews/harness/harness-core/39153#-NFBDYCN44xhJS-ssLiD:-NFBDYCN44xhJS-ssLiE:b-w16txs) ([raw file](https://github.com/harness/harness-core/blob/ed5480a62e6958880f700d1621f6c58264da0cbb/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1158)):*
> ```Java
>       } catch (IOException e) {
>         log.error("Error applying profile [{}]", profile.getName(), e);
>       } catch (InterruptedException e) {
> ```

why not add a finally block to release the file ?

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1158 at r1](https://reviewable.io/reviews/harness/harness-core/39153#-NFBDYCN44xhJS-ssLiD:-NFBHtde5_wKFQAgyLH7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed5480a62e6958880f700d1621f6c58264da0cbb/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1158)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why not add a finally block to release the file ?
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1114 at r1](https://reviewable.io/reviews/harness/harness-core/39153#-NF9upuA7SaubDxeD-Ud:-NFBI3zrAwOfS07eiNb6:bsnc5ay) ([raw file](https://github.com/harness/harness-core/blob/ed5480a62e6958880f700d1621f6c58264da0cbb/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1114)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

profile check is 3 min interval, so why need 5 min wait time for acquire lock?
</blockquote></details>

reverted this change

**Review by raghuAtWings — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39153)* status: 1 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1068 at r2](https://reviewable.io/reviews/harness/harness-core/39153#-NFBKCBs17PTFhYmX5Xw:-NFBKCBs17PTFhYmX5Xx:b1e3lh) ([raw file](https://github.com/harness/harness-core/blob/505e78f946915730071ee5bd8d9b7d9cf4769541/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1068)):*
> ```Java
>     File profile = new File("profile");
>     if (shouldContactManager() && !executingProfile.get() && !isLocked(profile) && !frozen.get()) {
>       try {
> ```

this try should be before if block, so in case the profile gets locked, we keep trying to unlock it.

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1068 at r2](https://reviewable.io/reviews/harness/harness-core/39153#-NFBKCBs17PTFhYmX5Xw:-NFBMDnw-bASqU25Ee4S:bd1ohmx) ([raw file](https://github.com/harness/harness-core/blob/505e78f946915730071ee5bd8d9b7d9cf4769541/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1068)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this try should be before if block, so in case the profile gets locked, we keep trying to unlock it. 
</blockquote></details>

So when the profile is executing its possible executor can make another call for checkProfile( interval 3 mins)  so we cant add release lock outside of check

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1068 at r2](https://reviewable.io/reviews/harness/harness-core/39153#-NFBKCBs17PTFhYmX5Xw:-NFBN7pNEDTfA2Bdz6yL:be03t6c) ([raw file](https://github.com/harness/harness-core/blob/505e78f946915730071ee5bd8d9b7d9cf4769541/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1068)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

So when the profile is executing its possible executor can make another call for checkProfile( interval 3 mins)  so we cant add release lock outside of check
</blockquote></details>

in that case should we try to unlock if needed in else block?

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1068 at r2](https://reviewable.io/reviews/harness/harness-core/39153#-NFBKCBs17PTFhYmX5Xw:-NFBNefL7rnMw546Ps0z:b-2e7574) ([raw file](https://github.com/harness/harness-core/blob/505e78f946915730071ee5bd8d9b7d9cf4769541/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1068)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

in that case should we try to unlock if needed in else block?
</blockquote></details>

But how do we know profile has already been executed or not? profile.result & profile exists irrespective of profile run.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39153)* status: 1 change requests. 1. unresolved discussions.

**Review by mdmilic — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39153)* status: :shipit: complete! ✓

**Pull request merged**
