### PR TITLE
[fix]:[pl-27363]: Fix exception throwing format

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Fix exception throwing format for all apis and null is fixed for getTemplate, tested it out for getTemplate with and without versionLabels 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36274)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36274)

**Comment by adivishy1** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 963 at r3](https://reviewable.io/reviews/harness/harness-core/36274#-N9BgiXi5fotxcwcE5I6:-N9BgiXj1ghSkOiAh4o9:bknip0z) ([raw file](https://github.com/harness/harness-core/blob/e2cdb52e24eae363d5b1d050d4bf98d30876dca7/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L963)):*
> ```Java
>   private String getErrorMessage(String templateIdentifier, String versionLabel) {
>     if (EmptyPredicate.isEmpty(versionLabel)) {
>       return String.format("Error while retrieving with stable template with identifier [%s] ", templateIdentifier);
> ```

should be "retrieving stable template" , "with" not required.

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36274)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36274)* status: :shipit: complete! ✓

**Review by inderschera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36274)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 95 at r6](https://reviewable.io/reviews/harness/harness-core/36274#-N9By6-T1pMMg1luq8J3:-N9By6-T1pMMg1luq8J4:b-47zne0) ([raw file](https://github.com/harness/harness-core/blob/beb83febbcb1a920f51dffb7e00645413d4112b8/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L95)):*
> ```Java
>       throw new InvalidRequestException(
>           String.format("Error while retrieving template with identifier [%s] and versionLabel [%s]: %s",
>               templateIdentifier, versionLabel, e.getMessage()));
> ```

Why are we removing these?
These messages were generally helpful for the user to know the the reason of failures.
How will we convey failure reasons to users then?

**Review by bhavya181 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36274)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 3 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36274)* status: :shipit: complete! ✓

**Review by inderschera — APPROVED** [review]
> Reviewed 3 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36274)* status: :shipit: complete! ✓

**Pull request merged**
