### PR TITLE
feat: [PL-26235]: Scope Name Mapper in Access Control

### PR DESCRIPTION
**Pull request by reetika04**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35065)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35065)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/ScopeServiceImpl.java` line 109 at r1](https://reviewable.io/reviews/harness/harness-core/35065#-N6LnFfU-8mNS3fcjVaN:-N6LnFfU-8mNS3fcjVaO:b-z1eran) ([raw file](https://github.com/harness/harness-core/blob/cfec9ce041f504d5f0a99196bf805191de0b69f6/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/ScopeServiceImpl.java#L109)):*
> ```Java
>   }
> 
>   private String getScopeName(Scope scope) {
> ```

Shouldn't this just be instanceName?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/ScopeServiceImpl.java` line 120 at r1](https://reviewable.io/reviews/harness/harness-core/35065#-N6Ln0mk9PmOK4lmwF9G:-N6Ln0mk9PmOK4lmwF9H:b-rm3lrj) ([raw file](https://github.com/harness/harness-core/blob/cfec9ce041f504d5f0a99196bf805191de0b69f6/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/ScopeServiceImpl.java#L120)):*
> ```Java
>   }
> 
>   private ScopeDBO fromScope(Scope scope) {
> ```

Just double check and make sure sure everywhere where Scope and ScopeDBO is created, its created with name.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/persistence/ScopeDaoImpl.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/35065#-N6LmhyXC9bNd9uPoGqx:-N6LmhyXC9bNd9uPoGqy:borv04z) ([raw file](https://github.com/harness/harness-core/blob/cfec9ce041f504d5f0a99196bf805191de0b69f6/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/persistence/ScopeDaoImpl.java#L42)):*
> ```Java
>       ScopeDBO updated = savedScope.get();
>       updated.setName(scope.getName());
>       scopeRepository.save(updated);
> ```

We Should put a return statement at the end of this if block

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35065)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/ScopeServiceImpl.java` line 109 at r1](https://reviewable.io/reviews/harness/harness-core/35065#-N6LnFfU-8mNS3fcjVaN:-N6MYMt-19zgqnn6auE6:bo9nvj1) ([raw file](https://github.com/harness/harness-core/blob/cfec9ce041f504d5f0a99196bf805191de0b69f6/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/ScopeServiceImpl.java#L109)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Shouldn't this just be instanceName?
</blockquote></details>

Instance name only stores the name of the instance Ankit, we are storing the name of the whole scope in this case.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/ScopeServiceImpl.java` line 120 at r1](https://reviewable.io/reviews/harness/harness-core/35065#-N6Ln0mk9PmOK4lmwF9G:-N6MYUf077tDpTOBmZ4u:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cfec9ce041f504d5f0a99196bf805191de0b69f6/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/ScopeServiceImpl.java#L120)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Just double check and make sure sure everywhere where Scope and ScopeDBO is created, its created with name.
</blockquote></details>

Done.

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35065)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/persistence/ScopeDaoImpl.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/35065#-N6LmhyXC9bNd9uPoGqx:-N6MYYKD95H41X5VOPpK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cfec9ce041f504d5f0a99196bf805191de0b69f6/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/persistence/ScopeDaoImpl.java#L42)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We Should put a return statement at the end of this if block
</blockquote></details>

Done.

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35065)* status: 5 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/scopes/harness/HarnessScopeServiceImpl.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/35065#-N6MpbC36AGcBbAGseys:-N6S1O9r-8WlDYoB7o1Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9effef69300d7ce86c0e2aefff6012c6f8f4732e/access-control/service/src/main/java/io/harness/accesscontrol/scopes/harness/HarnessScopeServiceImpl.java#L66)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

This will result in nullPointer.
</blockquote></details>

Done.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/scopes/harness/HarnessScopeServiceImpl.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/35065#-N6Mpf5GE1fB-1AVb4_Q:-N6S1MJ17F_QgWR3krB0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9effef69300d7ce86c0e2aefff6012c6f8f4732e/access-control/service/src/main/java/io/harness/accesscontrol/scopes/harness/HarnessScopeServiceImpl.java#L76)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

This will result in nullPointer.
</blockquote></details>

Done.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/scopes/harness/HarnessScopeServiceImpl.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/35065#-N6MqEzDD7opITev6kZM:-N6S1KZ23N0KtQOYAm5F:b6ecrt4) ([raw file](https://github.com/harness/harness-core/blob/9effef69300d7ce86c0e2aefff6012c6f8f4732e/access-control/service/src/main/java/io/harness/accesscontrol/scopes/harness/HarnessScopeServiceImpl.java#L83)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

We don't need the name of the account?
</blockquote></details>

Added it now.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35065#-:-N6fz2fLDhVg9sjWrdg7:bnfp4nl)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35065)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/ScopeServiceImpl.java` line 109 at r1](https://reviewable.io/reviews/harness/harness-core/35065#-N6LnFfU-8mNS3fcjVaN:-N6g0ihb7wUvNZR1dUDi:b-xiqu1b) ([raw file](https://github.com/harness/harness-core/blob/cfec9ce041f504d5f0a99196bf805191de0b69f6/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/ScopeServiceImpl.java#L109)):*
<details><summary><i>Previously, reetika04 (Reetika) wrote…</i></summary><blockquote>

Instance name only stores the name of the instance Ankit, we are storing the name of the whole scope in this case.
</blockquote></details>

Sorry didn't understand. Lets sync up once.

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35065)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/ScopeServiceImpl.java` line 109 at r1](https://reviewable.io/reviews/harness/harness-core/35065#-N6LnFfU-8mNS3fcjVaN:-N6g3fo94Qhejc1euNkh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cfec9ce041f504d5f0a99196bf805191de0b69f6/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/ScopeServiceImpl.java#L109)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Sorry didn't understand. Lets sync up once.
</blockquote></details>

Done.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35065#-:-N6g41e_4CaF6xyawPyp:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35065#-:-N6gV52TDo839DE9SOD0:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
