### PR TITLE
fix: [CDS-41396]: fail k8s canary delete step in case its some issue …

### PR DESCRIPTION
**Pull request by achyuth-harness**
…other than "resource not found"

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36142)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36142)

**Review by shubham-in10se — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36142)* status: :shipit: complete! ✓

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 1002 at r1](https://reviewable.io/reviews/harness/harness-core/36142#-N8wz0d19RJ1SsIXpHVA:-N8wz0d19RJ1SsIXpHVB:b-qppjrb) ([raw file](https://github.com/harness/harness-core/blob/2d976c7cda4abf70832c9c0ad1bb042fcff13a53/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L1002)):*
> ```Java
>         String reultOutput = result.outputUTF8().toLowerCase();
>         // if result contains "not found" then we don't fail else we fail the step
>         if (!reultOutput.contains("not found")) {
> ```

make this a static String Constant.

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36142)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 1002 at r1](https://reviewable.io/reviews/harness/harness-core/36142#-N8wz0d19RJ1SsIXpHVA:-N8yORrn2AUjEyXhCwy1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2d976c7cda4abf70832c9c0ad1bb042fcff13a53/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L1002)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

make this a static String Constant.
</blockquote></details>

Done.

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36142)* status: :shipit: complete! ✓

**Pull request merged**
