### PR TITLE
feat: [DEL-5314]: create a grpc method to check if a task is supported

### PR DESCRIPTION
**Pull request by arpit3107**
## Describe your changes
Currently if developers want to create a new taskType then they have to use FF to enable it after full development. We want to get this driven from code.

Wiki: https://harness.atlassian.net/wiki/spaces/DEL/pages/21229012403/Proposal+for+Ability+to+release+tasks+based+on+delegate+version

So, this change includes a grpc method which other services can use to check whether a taskType is supported by all delegates or not. Also, there is a rest api which ui can use to check the supportance of taskType.

Tests done:
1. This is addition of new grpc method, so while creating a connector PT from ng-manager, i am also checking the supportance of one taskType manually from code. Will remove this code before merging pr.
2. Tested UI api.
3. Tested grpc method when no delegate is active, v/s when one delegate was active.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39952)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/39952#-NGbnROR-Y-8-4lE4tnl:-NGbnROSEgwLwQecJLxS:b65s01x) ([raw file](https://github.com/harness/harness-core/blob/3287ab05b13623b9cff43c4342ff92b0162b2f72/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L75)):*
> ```Java
>   @Override
>   public boolean isTaskTypeSupported(String taskType, String accountId) {
>     return false;
> ```

why is this method needed or it is false?

**Review by raghuAtWings — COMMENTED** [review]
also please add description and testing you did in the PR description

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39952#-:-NGbnkmrELkbvwjcC-G5:b-986gfs)* status: 12 file(s) to review. 0 of 1 approvals obtained.

**Review by arpit3107 — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39952#-:-NGov6yq9oGoIPDXOJ0N:bb7f2mf)* status: 14 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/39952#-NGbnROR-Y-8-4lE4tnl:-NGov1uS3nOiu1uPz8MQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3287ab05b13623b9cff43c4342ff92b0162b2f72/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L75)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why is this method needed or it is false?
</blockquote></details>

Done.

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, 1 of 1 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39952)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateTaskUIResource.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqXZFi32F8vbsn5mcD:-NGqXZFi32F8vbsn5mcE:b8tv14l) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateTaskUIResource.java#L37)):*
> ```Java
> @Produces("application/json")
> @OwnedBy(DEL)
> public class DelegateTaskUIResource {
> ```

I think the name would violate checkstyle. You can't have two consecutive uppercase letters. Also, not sure if you should put UI in the name. Do we do that in general? I don't think other Resource classes used by UI have this. 
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqZ6fD39alW3FyDVoK:-NGqZ6fD39alW3FyDVoL:bbkls6o) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java#L53)):*
> ```Java
> 
>   @Inject private HPersistence persistence;
>   @Inject private DelegateSetupService delegateSetupService;
> ```

This creates a cyclic dependency. You need to break it. 
i.e. DelegateSetupService depends on DelegateCache and DelegateCache depends on DelegateSetupService



_Code quote:_
```Java
DelegateSetupService
```
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java` line 188 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqYfZI5VRUjLPNF3ME:-NGqYfZI5VRUjLPNF3MF:bti29v2) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java#L188)):*
> ```Java
> 
>   @Override
>   public Set<String> getSetOfSupportedTaskTypes(@NotNull String accountId) {
> ```

Don't put DataType names in the method names. i.e. call it getSupportedTaskTypes
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java` line 198 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqZoopBXagsAKfdGDm:-NGqZooq9UTO-jcingpI:b-h53zxl) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java#L198)):*
> ```Java
> 
>   private Set<String> getIntersectionOfSupportedTaskTypes(@NotNull String accountId) {
>     List<Delegate> delegateList = delegateSetupService.getActiveDelegatesList(accountId);
> ```

Isn't this active delegate list also cached somewhere (I think it is)? I don't think there would be much of performance gain getting it from cache since we do it once per account per expire interval, but what would happen if this goes out of sync with other components that get the active delegate list from cache? Maybe it's safer to just have one source of truth and always get it from cache for all components. Also, don't put data type name in the name of var. Call it activeDelegates



_Code quote:_
```Java
getActiveDelegatesList
```
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java` line 840 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqcy-9C272BrtcIXQp:-NGqcy-9C272BrtcIXQq:b-9r15ix) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L840)):*
> ```Java
> 
>   @Override
>   public List<Delegate> getActiveDelegatesList(@NotNull String accountId) {
> ```

This probably doesn't belong here. If you don't end up using active delegate cache, put it in the DelegateCache directly
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorHeartbeatServiceImpl.java` line 87 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqdV1kEXYGj4W69jRV:-NGqdV1kEXYGj4W69jRW:bcnhame) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorHeartbeatServiceImpl.java#L87)):*
> ```Java
>       PerpetualTaskClientContextDetails taskContext =
>           PerpetualTaskClientContextDetails.newBuilder().setTaskClientParams(clientParams).build();
>       log.info("Arpit: checking for supported task type.");
> ```

You probably forgot to delete this. 
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java` line 21 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqYGCT94hpfToH7AGR:-NGqYGCT94hpfToH7AGS:b-1etv7w) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java#L21)):*
> ```Java
> public interface DelegateServiceConstants {
>   String STREAM_DELEGATE = "/stream/delegate/";
>   Duration HEARTBEAT_EXPIRY_TIME = ofMinutes(5);
> ```

Is this intentional? If yes, why is it needed?

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java` line 21 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqYGCT94hpfToH7AGR:-NGs2Mpp1spK_mrXbgi9:bb3koz8) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java#L21)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Is this intentional? If yes, why is it needed?
</blockquote></details>

@arpit3107 dont change that value? Keep it as 10 mins

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateTaskUIResource.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGsF9ERBAq_Cw5jUtVl:-NGsF9ES49rUoBw0UU8c:b-m4b5vh) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateTaskUIResource.java#L46)):*
> ```Java
> 
>   @GET
>   @Path("supported/all-delegates")
> ```

too long a name, the user should be able to make a call like below. Also this means that this method can be moved to DelegateSetupResource

/api/setup/delegates/is-supported-task?taskType=<XYZ>

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 3 of 11 files at r1, 1 of 1 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39952)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39952)* status: 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateTaskUIResource.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqXZFi32F8vbsn5mcD:-NGuZu8U7TYnDmtMsl-Z:b-de2e72) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateTaskUIResource.java#L37)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I think the name would violate checkstyle. You can't have two consecutive uppercase letters. Also, not sure if you should put UI in the name. Do we do that in general? I don't think other Resource classes used by UI have this. 
</blockquote></details>

deleted this class
___
*[`420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateTaskUIResource.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGsF9ERBAq_Cw5jUtVl:-NGuZyM-8JHfJhduFIIe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateTaskUIResource.java#L46)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

too long a name, the user should be able to make a call like below. Also this means that this method can be moved to DelegateSetupResource

/api/setup/delegates/is-supported-task?taskType=<XYZ>
</blockquote></details>

Done.
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqZ6fD39alW3FyDVoK:-NGuhkUYC6PI8T537z3s:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java#L53)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This creates a cyclic dependency. You need to break it. 
i.e. DelegateSetupService depends on DelegateCache and DelegateCache depends on DelegateSetupService
</blockquote></details>

Done.
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java` line 198 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqZoopBXagsAKfdGDm:-NGupEMBCryC-XX_1DZP:bkedp6c) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java#L198)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Isn't this active delegate list also cached somewhere (I think it is)? I don't think there would be much of performance gain getting it from cache since we do it once per account per expire interval, but what would happen if this goes out of sync with other components that get the active delegate list from cache? Maybe it's safer to just have one source of truth and always get it from cache for all components. Also, don't put data type name in the name of var. Call it activeDelegates
</blockquote></details>

No, active delegates list per account is not cache anywhere. Only delegateId v/s delegateRecord is cached earlier.

We should put this in cache, because developers will call this method about 5-10 times while creating a new task, just like they currently check the FF status at some places.
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java` line 840 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqcy-9C272BrtcIXQp:-NGuphpc4hDIN_zrv1SM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L840)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This probably doesn't belong here. If you don't end up using active delegate cache, put it in the DelegateCache directly
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorHeartbeatServiceImpl.java` line 87 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqdV1kEXYGj4W69jRV:-NGupjTw0NY4lvCcgTOm:bqfhmy2) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorHeartbeatServiceImpl.java#L87)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You probably forgot to delete this. 
</blockquote></details>

this is for testing in pr env
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java` line 21 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqYGCT94hpfToH7AGR:-NGuhMFZ-Kf_EuLmSWBQ:bv734kq) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java#L21)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

@arpit3107 dont change that value? Keep it as 10 mins
</blockquote></details>

yes, currently this variable is not consistent at all the places, at some places its 10 and for some its 5. So, i tried making that consistent.

@jennyjames21 i see 10 mins is only used for checking if the delegate is connecting after long pause. So, i have created a new variable just for that purpose.

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39952)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java` line 799 at r4](https://reviewable.io/reviews/harness/harness-core/39952#-NGvFnh_-tjmAW4KmTPq:-NGvFnh_-tjmAW4KmTPr:bmnji24) ([raw file](https://github.com/harness/harness-core/blob/a78c922e95f04ffc95939bfa1f07501336dedc65/400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java#L799)):*
> ```Java
> 
>   @GET
>   @Path("is-task-supported")
> ```

I'm thinking now this API doesn't belong to `/setup/delegate/` this has nothing to do with setting up or configuring delegate. Also, I think OpenAPI says we shouldn't have `is` in the name, so should be something like `task-supported` or even `/tasks/supported/`
DelegateTaskResource is actually more like DelegateTaskAgentResource and also not suitable. You would probably need to create a new Resource class and register it. 
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java` line 198 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqZoopBXagsAKfdGDm:-NGvIjT3194CgdLULbUB:bamzigz) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java#L198)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

No, active delegates list per account is not cache anywhere. Only delegateId v/s delegateRecord is cached earlier.

We should put this in cache, because developers will call this method about 5-10 times while creating a new task, just like they currently check the FF status at some places.
</blockquote></details>

Ok if active delegates are not cached we don't need to cache them since we are caching task types.

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java` line 21 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqYGCT94hpfToH7AGR:-NGwFubm6XHizTFMs-0W:b-n6c1mo) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java#L21)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

yes, currently this variable is not consistent at all the places, at some places its 10 and for some its 5. So, i tried making that consistent.

@jennyjames21 i see 10 mins is only used for checking if the delegate is connecting after long pause. So, i have created a new variable just for that purpose.
</blockquote></details>

you can create new variable for 5 mins, dont change the existing one.

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39952)* status: 12 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java` line 799 at r4](https://reviewable.io/reviews/harness/harness-core/39952#-NGvFnh_-tjmAW4KmTPq:-NGyuhMBACsVsgy28jZO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a78c922e95f04ffc95939bfa1f07501336dedc65/400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java#L799)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I'm thinking now this API doesn't belong to `/setup/delegate/` this has nothing to do with setting up or configuring delegate. Also, I think OpenAPI says we shouldn't have `is` in the name, so should be something like `task-supported` or even `/tasks/supported/`
DelegateTaskResource is actually more like DelegateTaskAgentResource and also not suitable. You would probably need to create a new Resource class and register it. 
</blockquote></details>

Done.
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java` line 21 at r3](https://reviewable.io/reviews/harness/harness-core/39952#-NGqYGCT94hpfToH7AGR:-NGyucwQ62CtaGddpvPU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac4ab13d7c9f1696c5d16bbaf2f9069828ed75d6/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java#L21)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

you can create new variable for 5 mins, dont change the existing one. 
</blockquote></details>

Done.

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 11 of 11 files at r4, 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39952)* status: 1 change requests. 2. unresolved discussions.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 4 of 5 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39952)* status: 1 change requests. 2. unresolved discussions.

**Review by mdmilic — APPROVED** [review]
> Reviewed 8 of 12 files at r5, 4 of 5 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39952)* status: :shipit: complete! ✓

**Pull request merged**
