### PR TITLE
feat: [IDP-1484][IDP-1485]: Onboard to debezium service for idp-harness collections and push data to postgres for NG dashboards

### PR DESCRIPTION
**Pull request by sathish-soundarapandian**
## Describe your changes
Onboard to debezium service for idp-harness collections and push data to postgres for NG dashboards

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57186)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 34 of 35 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57186)* status: 35 file(s) to review. 0 of 2 approvals obtained. 

___
*[`959-psql-database-models/src/generated/java/io/harness/timescaledb/Indexes.java` line 278 at r3](https://reviewable.io/reviews/harness/harness-core/57186#-NnEYIgCAHcZtuwrpkKn:-NnEYIgCAHcZtuwrpkKo:b-19mghi) ([raw file](https://github.com/harness/harness-core/blob/529c6214c87126b5a765fb4cea54ea56395b60b8/959-psql-database-models/src/generated/java/io/harness/timescaledb/Indexes.java#L278)):*
> ```Java
>               UtilizationData.UTILIZATION_DATA.INSTANCETYPE, UtilizationData.UTILIZATION_DATA.STARTTIME.desc()},
>           true);
>   public static final Index BACKSTAGE_CATALOG_ACCOUNT_IDENTIFIER_CREATED_AT_IDX = Internal.createIndex(
> ```

Looks like the INDEX definitions are sorted. We might want to maintain the ordering. 



_Code quote:_
```Java
BACKSTAGE_CATALO
```
___
*[`959-psql-database-models/src/generated/java/io/harness/timescaledb/Public.java` line 162 at r3](https://reviewable.io/reviews/harness/harness-core/57186#-NnEZKsF6gJdzO-i-XOk:-NnEZKsF6gJdzO-i-XOl:bap8eun) ([raw file](https://github.com/harness/harness-core/blob/529c6214c87126b5a765fb4cea54ea56395b60b8/959-psql-database-models/src/generated/java/io/harness/timescaledb/Public.java#L162)):*
> ```Java
>    * The table <code>public.backstage_catalog</code>.
>    */
>   public final BackstageCatalog BACKSTAGE_CATALOG = BackstageCatalog.BACKSTAGE_CATALOG;
> ```

same comment as previous
___
*[`idp-service/src/main/java/io/harness/idp/events/consumers/BackstageCatalogChangeEventHandler.java` line 71 at r3](https://reviewable.io/reviews/harness/harness-core/57186#-NnEtkoh7WxC8HHl_zCV:-NnEtkoh7WxC8HHl_zCW:btc70z0) ([raw file](https://github.com/harness/harness-core/blob/529c6214c87126b5a765fb4cea54ea56395b60b8/idp-service/src/main/java/io/harness/idp/events/consumers/BackstageCatalogChangeEventHandler.java#L71)):*
> ```Java
>     }
>     try {
>       dsl.insertInto(Tables.BACKSTAGE_CATALOG)
> ```

nit: we have same code for create/update

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57186)* status: 35 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`959-psql-database-models/src/generated/java/io/harness/timescaledb/Indexes.java` line 278 at r3](https://reviewable.io/reviews/harness/harness-core/57186#-NnEYIgCAHcZtuwrpkKn:-NnF4Voo5K6Z_b0eKInb:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/529c6214c87126b5a765fb4cea54ea56395b60b8/959-psql-database-models/src/generated/java/io/harness/timescaledb/Indexes.java#L278)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Looks like the INDEX definitions are sorted. We might want to maintain the ordering.
</blockquote></details>

Done
___
*[`959-psql-database-models/src/generated/java/io/harness/timescaledb/Public.java` line 162 at r3](https://reviewable.io/reviews/harness/harness-core/57186#-NnEZKsF6gJdzO-i-XOk:-NnF4X-UBfWo42yjbxjg:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/529c6214c87126b5a765fb4cea54ea56395b60b8/959-psql-database-models/src/generated/java/io/harness/timescaledb/Public.java#L162)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

same comment as previous
</blockquote></details>

Done
___
*[`idp-service/src/main/java/io/harness/idp/events/consumers/BackstageCatalogChangeEventHandler.java` line 71 at r3](https://reviewable.io/reviews/harness/harness-core/57186#-NnEtkoh7WxC8HHl_zCV:-NnF4Xrs3XBFGD-G_4cR:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/529c6214c87126b5a765fb4cea54ea56395b60b8/idp-service/src/main/java/io/harness/idp/events/consumers/BackstageCatalogChangeEventHandler.java#L71)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

nit: we have same code for create/update
</blockquote></details>

Done

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57186)* status: 35 file(s) to review. 1 of 2 approvals obtained.

**Review by arya-harness — APPROVED** [review]

**Comment by sathish-soundarapandian** [comment]
trigger review

**Pull request merged**
