### PR TITLE
fix: [DEL-4124]: Watcher changes to download version from manager

### PR DESCRIPTION
**Pull request by gaurav-jain1**
Summary:
  As part of this change, introduced a way to generate hmac based jwt, and use it to fetch watcher version from manager's ring.

Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33484)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33484)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 237 at r1](https://reviewable.io/reviews/harness/harness-core/33484#-N2pfcW544DRWwCwlZdu:-N2pfcW544DRWwCwlZdv:b-k7hi8u) ([raw file](https://github.com/harness/harness-core/blob/01aef71f822b6e25249f66b9516ff20ab4e71d49/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L237)):*
> ```Java
> 
>   public static final HttpClient httpClient = new DefaultHttpClient();
>   TokenGeneratorV2 HS256TokenGenerator;
> ```

It should probably fail checkstyle. First letter lower case. Also, we should be able to inject it
___
*[`980-commons/src/main/java/io/harness/security/TokenGeneratorV2.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/33484#-N2peztxCajGdinhWQrK:-N2peztxCajGdinhWQrL:b-sof6a7) ([raw file](https://github.com/harness/harness-core/blob/01aef71f822b6e25249f66b9516ff20ab4e71d49/980-commons/src/main/java/io/harness/security/TokenGeneratorV2.java#L20)):*
> ```Java
>   private static final String HOST_NAME = getLocalHostName();
>   private static final long EXP_DURATION = Duration.ofMinutes(30).toMillis();
>   Algorithm algorithm;
> ```

make it private final

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33484)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1622 at r3](https://reviewable.io/reviews/harness/harness-core/33484#-N3ryrVH8-vEo_On7zyD:-N3ryrVH8-vEo_On7zyE:b-bg0zrf) ([raw file](https://github.com/harness/harness-core/blob/d9c717093879350826e3ca5c1d681d00fc737e21/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1622)):*
> ```Java
>           delegateConfiguration.getAccountId()));
>       if (restResponse != null) {
>         return restResponse.getResource().toString();
> ```

`getResource` should already give you String
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1625 at r3](https://reviewable.io/reviews/harness/harness-core/33484#-N3s1j-p1LGWkqmNsAAe:-N3s1j-q2HDgBo6JhXL4:b-bzxw56) ([raw file](https://github.com/harness/harness-core/blob/d9c717093879350826e3ca5c1d681d00fc737e21/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1625)):*
> ```Java
>       }
>     } catch (Exception e) {
>       // Ignore
> ```

Maybe either add exception log line or in below try so we know the version is fetcher from GCS



_Code quote:_
```Java
      // Ignore
    }
    try {
      // Try fetching watcher version from gcp
```
___
*[`400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/33484#-N3s2Tn75uApWAneNcOq:-N3s2Tn75uApWAneNcOr:bo6jdo) ([raw file](https://github.com/harness/harness-core/blob/d9c717093879350826e3ca5c1d681d00fc737e21/400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java#L55)):*
> ```Java
>     List<String> watcherVersion = accountService.getWatcherVersion(accountId);
>     if (isNotEmpty(watcherVersion)) {
>       return new RestResponse<>(watcherVersion.get(0));
> ```

Are we certain that `get(0)` would always be the primary version?
___
*[`400-rest/src/main/java/software/wings/security/AuthenticationFilter.java` line 423 at r3](https://reviewable.io/reviews/harness/harness-core/33484#-N3s4JSs9jhG3lTQ-FjL:-N3s4JSt1kHo48JM4sFc:bijlvi9) ([raw file](https://github.com/harness/harness-core/blob/d9c717093879350826e3ca5c1d681d00fc737e21/400-rest/src/main/java/software/wings/security/AuthenticationFilter.java#L423)):*
> ```Java
>         final String jwtToken =
>             substringAfter(containerRequestContext.getHeaderString(HttpHeaders.AUTHORIZATION), "Delegate ");
>         Decoder decoder = getUrlDecoder();
> ```

I think you shouldn't do this here, authService (or rather `DelegateTokenAuthenticatorImpl` later on) is already capable on reading headers in a more structured way. You should do it there instead (also this breaks encapsulation)



_Code quote:_
```Java
        Decoder decoder = getUrlDecoder();
        String header = new String(decoder.decode(jwtToken.split("\\.")[0]));
```
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 1374 at r3](https://reviewable.io/reviews/harness/harness-core/33484#-N3s58Wo2tE2pK8wL1AZ:-N3s58Wo2tE2pK8wL1A_:bkmve5x) ([raw file](https://github.com/harness/harness-core/blob/d9c717093879350826e3ca5c1d681d00fc737e21/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L1374)):*
> ```Java
> 
>   @VisibleForTesting
>   String getResponseStringFromUrl() throws IOException {
> ```

Rename the method, since it's specific to fetching watcher version

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33484)* status: Some of the checks are too old. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1622 at r3](https://reviewable.io/reviews/harness/harness-core/33484#-N3ryrVH8-vEo_On7zyD:-N3sQylO93QWU6cYyvE9:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/d9c717093879350826e3ca5c1d681d00fc737e21/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1622)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

`getResource` should already give you String
</blockquote></details>

Done



_Code quote:_
```Java
findExpectedWatcherVersion
```
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1625 at r3](https://reviewable.io/reviews/harness/harness-core/33484#-N3s1j-p1LGWkqmNsAAe:-N3s8wvC7Hosk3D6qGLE:b-7rtizd) ([raw file](https://github.com/harness/harness-core/blob/d9c717093879350826e3ca5c1d681d00fc737e21/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1625)):*
> er add excepti
Done
___
*[`400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/33484#-N3s2Tn75uApWAneNcOq:-N3sRPNv9XHKWwghDG7u:b-dccnq0) ([raw file](https://github.com/harness/harness-core/blob/d9c717093879350826e3ca5c1d681d00fc737e21/400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java#L55)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Are we certain that `get(0)` would always be the primary version?
</blockquote></details>

Yes, ideally we should be maintaining only one version for watcher, since we using List in our RingService, picked up the 0th element in there.
We can have separate PR for converting version List to String
___
*[`400-rest/src/main/java/software/wings/security/AuthenticationFilter.java` line 423 at r3](https://reviewable.io/reviews/harness/harness-core/33484#-N3s4JSs9jhG3lTQ-FjL:-N3sSw5x7QrQi-UkRI9j:b-qegvpg) ([raw file](https://github.com/harness/harness-core/blob/d9c717093879350826e3ca5c1d681d00fc737e21/400-rest/src/main/java/software/wings/security/AuthenticationFilter.java#L423)):*
> ou should do it there 
I can move this logic to authServiceImpl, but essentially we can't read headers in AES128 JWT token as it requires decryption before we can read its content.
So this is a temporary workaround till be migrate to HMAC based jwt token.
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 237 at r1](https://reviewable.io/reviews/harness/harness-core/33484#-N2pfcW544DRWwCwlZdu:-N3sV0cQ-1U4ruf2HLts:bp6dthn) ([raw file](https://github.com/harness/harness-core/blob/01aef71f822b6e25249f66b9516ff20ab4e71d49/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L237)):*
> d probably fail chec
not following your comment here.
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 1374 at r3](https://reviewable.io/reviews/harness/harness-core/33484#-N3s58Wo2tE2pK8wL1AZ:-N3sVHs_-xkGNYZ75sMM:b-nzly6e) ([raw file](https://github.com/harness/harness-core/blob/d9c717093879350826e3ca5c1d681d00fc737e21/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L1374)):*
> , since it's specific to fetching watc
Done
___
*[`980-commons/src/main/java/io/harness/security/TokenGeneratorV2.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/33484#-N2peztxCajGdinhWQrK:-N3sWp_R0xxVbVG6Gatz:b8joa7v) ([raw file](https://github.com/harness/harness-core/blob/01aef71f822b6e25249f66b9516ff20ab4e71d49/980-commons/src/main/java/io/harness/security/TokenGeneratorV2.java#L20)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

make it private final
</blockquote></details>

changes no longer needed

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/delegate/service/DelegateVersionService.java` line 99 at r5](https://reviewable.io/reviews/harness/harness-core/33484#-N4a1QhQ2bv1FAHmFi6z:-N4a1QhQ2bv1FAHmFi7-:b-rqn45e) ([raw file](https://github.com/harness/harness-core/blob/4086106dc307f81cdcaada0a2b6298e4d4ad4bde/400-rest/src/main/java/io/harness/delegate/service/DelegateVersionService.java#L99)):*
> ```Java
>   public List<String> getWatcherJarVersions(final String accountId) {
>     // TODO: use getWatcherJarVersionFromRing() once watcher is ready to enable from delegate Ring.
>     return singletonList(delegateService.getLatestWatcherVersion(accountId));
> ```

this should not be list

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/delegate/service/DelegateVersionService.java` line 99 at r5](https://reviewable.io/reviews/harness/harness-core/33484#-N4a1QhQ2bv1FAHmFi6z:-N4a7IvX9wK8quaWBxJR:b-mtgw7m) ([raw file](https://github.com/harness/harness-core/blob/4086106dc307f81cdcaada0a2b6298e4d4ad4bde/400-rest/src/main/java/io/harness/delegate/service/DelegateVersionService.java#L99)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this should not be list
</blockquote></details>

also change the interval to check for watcher version to be 30 mins or more

**Review by mdmilic — APPROVED** [review]
> Reviewed 5 of 7 files at r4, 3 of 5 files at r5, 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33484)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1242 at r6](https://reviewable.io/reviews/harness/harness-core/33484#-N5HnyY77OCG22tkmeGL:-N5HnyY77OCG22tkmeGM:b6evjie) ([raw file](https://github.com/harness/harness-core/blob/379b0596e6b36dd3ebaa72b0f653935d82aa41cb/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1242)):*
> ```Java
>   }
> 
>   public String getLatestWatcherVersion(String accountId) {
> ```

I think this is not used, you could probably remove it
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 1381 at r6](https://reviewable.io/reviews/harness/harness-core/33484#-N5HpA3cDHWRz_ozp42v:-N5HpA3cDHWRz_ozp42w:b610rnl) ([raw file](https://github.com/harness/harness-core/blob/379b0596e6b36dd3ebaa72b0f653935d82aa41cb/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L1381)):*
> ```Java
>             () -> SafeHttpCall.execute(managerClient.getWatcherVersion(watcherConfiguration.getAccountId())));
>         if (restResponse != null) {
>           return restResponse.getResource().toString();
> ```

You don't need toString()

**Review by arpit3107 — APPROVED** [review]
> Reviewed 1 of 10 files at r3, 3 of 10 files at r6, 13 of 15 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33484)* status: :shipit: complete! ✓

**Pull request merged**
