### PR TITLE
feat: [CI-4555]: Add active committer count as telemetry

### PR DESCRIPTION
**Pull request by jamie-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34540)

### CODE REVIEW

**Review by jamie-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34540)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`310-ci-manager/src/main/java/io/harness/core/ci/services/CIOverviewDashboardServiceImpl.java` line 209 at r1](https://reviewable.io/reviews/harness/harness-core/34540#-N57BQzQ8zjazeuhWTHm:-N57IBLv8lNv6WC8Jj27:bqsgzmo) ([raw file](https://github.com/harness/harness-core/blob/4d69d714f90a18e3f3bf41a58b6429fd50c9301d/310-ci-manager/src/main/java/io/harness/core/ci/services/CIOverviewDashboardServiceImpl.java#L209)):*
<details><summary><i>Previously, hemanthmantri (Hemanth Mantri) wrote…</i></summary><blockquote>

Can we not just populate these into a full query?
</blockquote></details>

No, prepare statement set is used to avoid input injection

**Review by jamie-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34540)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`310-ci-manager/src/main/java/io/harness/core/ci/services/CIOverviewDashboardServiceImpl.java` line 212 at r1](https://reviewable.io/reviews/harness/harness-core/34540#-N57BH-72xOeJhPdSTEr:-N57IHCX5zf8T-Ht8bt8:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/4d69d714f90a18e3f3bf41a58b6429fd50c9301d/310-ci-manager/src/main/java/io/harness/core/ci/services/CIOverviewDashboardServiceImpl.java#L212)):*
<details><summary><i>Previously, hemanthmantri (Hemanth Mantri) wrote…</i></summary><blockquote>

2 lines above are unused.
</blockquote></details>

removed

**Review by hemanthmantri — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34540)* status: 4 file(s) to review.

**Comment by jamie-harness** [comment]
I think this approach won't work. Doing a different approach

**Pull request closed without merging**
