### PR TITLE
techdebt: [CDS-54019]: Adding UT for Modify PR / SvcEnvCount

### PR DESCRIPTION
**Pull request by mankrit-singh**
## Describe your changes
Adding UT for Modify PR / SvcEnvCount

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45106)

### CODE REVIEW

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45106)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 609 at r2](https://reviewable.io/reviews/harness/harness-core/45106#-NQUj3BS8gfCmNQyrryY:-NQUj3BS8gfCmNQyrryZ:b2kelj) ([raw file](https://github.com/harness/harness-core/blob/7e082bffd270044aa6b9ce2d8adb70b2d3d5b88c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L609)):*
> ```Java
>     for (EnvironmentMapResponse environmentMapResponse : environmentMapList) {
>       Map<String, String> envMap = environmentMapResponse.getEnvironmentsMapList();
>       if (envMap.containsKey("environmentRef")) {
> ```

The put on this key can change independently and this code will break.

Can we reference the keys instead of hard-coding?

**Review by mankrit-singh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45106)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 609 at r2](https://reviewable.io/reviews/harness/harness-core/45106#-NQUj3BS8gfCmNQyrryY:-NQUl0ic6JZ1oSD9k_mS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7e082bffd270044aa6b9ce2d8adb70b2d3d5b88c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L609)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

The put on this key can change independently and this code will break.

Can we reference the keys instead of hard-coding?
</blockquote></details>

Done.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45106)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45106)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by anshul-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45106)* status: :shipit: complete! ✓

**Pull request merged**
