### PR TITLE
fix: [CI-3357]: fixed the clone codebase npe

### PR DESCRIPTION
**Pull request by aman-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30489)

### CODE REVIEW

**Review by shubham149 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30489)* status: Some of the checks are too old.

**Comment by aman-harness** [comment]
trigger message_metadata

**Comment by aman-harness** [comment]
trigger messagecheck

**Review by shubham149 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30489)* status: Some of the checks are too old.

**Comment by aman-harness** [comment]
trigger messagecheck

**Comment by aman-harness** [comment]
trigger messagecheck

**Review by shubham149 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30489)* status: Some of the checks are too old.

**Review by shubham149 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30489#-:-MvIFPIz19zTKubN8EIV:bnfp4nl)* status: Some of the checks are too old.

**Review by USB-05 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30489)* status: Some of the checks are too old.

**Pull request merged**
