### PR TITLE
feat: [PL-26992]: Added access control for settings APIs

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35692)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35692)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/35692#-N7p8vIL5Ak54UTiZZjp:-N7p8vIM6wPGUNDdnBMf:bl0edpl) ([raw file](https://github.com/harness/harness-core/blob/b9bca870fef875b32dad4d855a12d33d6ff0c563/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java#L45)):*
> ```Java
>   public ResponseDTO<SettingValueResponseDTO> get(
>       String identifier, String accountIdentifier, String orgIdentifier, String projectIdentifier) {
>     accessControlClient.checkForAccessOrThrow(ResourceScope.of(accountIdentifier, orgIdentifier, projectIdentifier),
> ```

We can use annotation NGAccessControlCheck instead.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35692)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/35692#-N7p8vIL5Ak54UTiZZjp:-N7pK-bx-biTNON6MEJp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b9bca870fef875b32dad4d855a12d33d6ff0c563/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java#L45)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

We can use annotation NGAccessControlCheck instead.
</blockquote></details>

Done.

**Comment by tiwaritejas** [comment]
trigger ti1

**Comment by tiwaritejas** [comment]
trigger ti4

**Review by reetika04 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35692)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35692)* status: :shipit: complete! ✓

**Pull request merged**
