### PR TITLE
fix: [CDS-86793]: Acorns Pipeline is stuck in running state

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56702)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 120 at r1](https://reviewable.io/reviews/harness/harness-core/56702#-NlXKRxQ7aOnEaryMVzr:-NlXKRxQ7aOnEaryMVzs:b2qmkzk) ([raw file](https://github.com/harness/harness-core/blob/01787d43c84c46b9e10d7678e73975ff4444ff76/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L120)):*
> ```Java
>       // Update Max concurrency in graph (consumed by UI) if the type of strategy is not parallelism
>       // For parallelism, the maxConcurrency cannot be defined via yaml, so we are ignoring its addition in graph.
>       if (!StrategyType.PARALLELISM.name().equals(graphLayoutNode.get(nodeExecution.getNodeId()).getNodeType())) {
> ```

Can we add a test for the same?

**Comment by prashantsharma04** [comment]
trigger uts

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56702)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 120 at r1](https://reviewable.io/reviews/harness/harness-core/56702#-NlXKRxQ7aOnEaryMVzr:-NlXoAWq5-jeWKajhcy4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/01787d43c84c46b9e10d7678e73975ff4444ff76/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L120)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we add a test for the same?
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56702)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56702)* status: 2 file(s) to review.

**Comment by prashantsharma04** [comment]
trigger review

**Comment by rohitk-h** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 121 at r2](https://reviewable.io/reviews/harness/harness-core/56702#-Nldfie-22lGeZIizXnb:-Nldfie-22lGeZIizXnc:bqii11n) ([raw file](https://github.com/harness/harness-core/blob/fe274e8dc9285612aaedcc94b954a037a5ae4304/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L121)):*
> ```Java
>       // For parallelism, the maxConcurrency cannot be defined via yaml, so we are ignoring its addition in graph.
>       String nodeType = graphLayoutNode.get(nodeExecution.getNodeId()).getNodeType();
>       if (nodeType == null) {
> ```

Is this just a logging change then?

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56702)* status: 2 file(s) to review. 1. unresolved discussions. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 121 at r2](https://reviewable.io/reviews/harness/harness-core/56702#-Nldfie-22lGeZIizXnb:-NlgEyno9YGf3RT60WnV:bvpd6bg) ([raw file](https://github.com/harness/harness-core/blob/fe274e8dc9285612aaedcc94b954a037a5ae4304/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L121)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Is this just a logging change then?
</blockquote></details>

No. We have handled null pointer exception as well.
Before this change, it was nodeType.equals(some constant). Ideally it should be (some constant).equals(nodeType)

**Pull request merged**
