### PR TITLE
[feat]: [SRM-10558]: Adding node for (optional) monitored service spec in CDNG verify step yaml.

### PR DESCRIPTION
**Pull request by dhruv-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33049)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33049)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/ConfiguredMonitoredServiceSpec.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/33049#-N1n3r-s-93iK7j0tODU:-N1n3r-s-93iK7j0tODV:b6k6nbk) ([raw file](https://github.com/harness/harness-core/blob/328dffac4591d7437bd67b7baf605a10569621c1/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/ConfiguredMonitoredServiceSpec.java#L33)):*
> ```Java
>   @Override
>   public String getType() {
>     return "Configured";
> ```

We can define the enum for it. Will be much easier to handle flows with it.

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33049)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/TemplateMonitoredServiceSpec.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/33049#-N1qerbCBx7iqC7zIQF8:-N1qerbCBx7iqC7zIQF9:b4u9gyh) ([raw file](https://github.com/harness/harness-core/blob/328dffac4591d7437bd67b7baf605a10569621c1/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/TemplateMonitoredServiceSpec.java#L32)):*
> ```Java
>   @NotNull
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH)
>   ParameterField<String> monitoredServiceTemplateRef;
> ```

let's add versionLabel as well.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33049)* status: Some of the checks are too old.

**Review by deepak-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33049#-:-N2GqJz4BnVsjGWj5Y-x:bnfp4nl)* status: Some of the checks are too old.

**Comment by dhruv-harness** [comment]
trigger recency

**Pull request merged**
