### PR TITLE
fix: [CDS-43041]: Fixing custom remote store flow and logs for Harness Store.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
Need to show cause of failure instead of just NPE.

Remove the unnecessary GIT_FILES_FETCH_TASK_NG delegate call when not required.

Display logs of files fetched from Harness Store, Custom Store, Http/S3/GCS store.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37376)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* Code issue 3 Code issues 
* Anti-pattern 4 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37376)

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 146 at r2](https://reviewable.io/reviews/harness/harness-core/37376#-NBlFo_04hvNZzDuEARf:-NBlFo_04hvNZzDuEARg:bm1v93d) ([raw file](https://github.com/harness/harness-core/blob/9167d5241711493b79e932c8b68750190f5a64df/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L146)):*
> ```Java
>   private static final Set<String> VALUES_YAML_SUPPORTED_MANIFEST_TYPES =
>       ImmutableSet.of(ManifestType.K8Manifest, ManifestType.HelmChart);
>   protected static final Set<String> HELM_SPECIFIC_STORE_TYPES =
> ```

nit: this can be HELM_CHART_REPO_STORE_TYPES. like we categorise in cg helmSourceRepo vs helmChartRepo

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 273 at r2](https://reviewable.io/reviews/harness/harness-core/37376#-NBlH1TU4jQe9rLFI63-:-NBlH1TU4jQe9rLFI630:by5cal7) ([raw file](https://github.com/harness/harness-core/blob/9167d5241711493b79e932c8b68750190f5a64df/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L273)):*
> ```Java
>                                                          .build())
>                                .build());
>         if (!isEmpty(store.getDelegateSelectors().getValue())) {
> ```

Lets check if store.delegateSelectors() itself doesn't get null.



_Code quote:_
```Java
 if (!isEmpty(store.getDelegateSelectors().getValue())) {
```

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 238 at r2](https://reviewable.io/reviews/harness/harness-core/37376#-NBlHVaFAVE1U-rjNSET:-NBlHVaFAVE1U-rjNSEU:b5ld9zn) ([raw file](https://github.com/harness/harness-core/blob/9167d5241711493b79e932c8b68750190f5a64df/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L238)):*
> ```Java
>   protected TaskChainResponse prepareCustomFetchManifestAndValuesTaskChainResponse(StoreConfig storeConfig,
>       Ambiance ambiance, StepElementParameters stepElementParameters, List<ManifestOutcome> paramsOrValuesManifests,
>       K8sStepPassThroughData k8sStepPassThroughData, boolean shouldOpenLogStream, boolean closeLogStream) {
> ```

nit: Lets have consistant naming between these two boolean. shouldOpenLogStream & shouldCloseLogStream



_Code quote:_
```Java
prepareCustomFetchManifestAndValuesTaskChainResponse(S
```

**Comment by tchaurasiya** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/manifests/request/CustomManifestValuesFetchParams.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/37376#-NBlI0j5Bp0RJeyvVl4L:-NBlI0j5Bp0RJeyvVl4M:b5ld9zn) ([raw file](https://github.com/harness/harness-core/blob/9167d5241711493b79e932c8b68750190f5a64df/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/manifests/request/CustomManifestValuesFetchParams.java#L44)):*
> ```Java
>   @Expression(ALLOW_SECRETS) private CustomManifestSource customManifestSource;
>   boolean shouldOpenLogStream;
>   boolean closeLogStream;
> ```

nit: Lets have consistant naming between these two boolean. shouldOpenLogStream & shouldCloseLogStream

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37376)* status: 10 file(s) to review. 0 of 1 approvals obtained.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 755 at r2](https://reviewable.io/reviews/harness/harness-core/37376#-NBlIUfcCDVNM2v9tY0w:-NBlIUfcCDVNM2v9tY0x:b94b11j) ([raw file](https://github.com/harness/harness-core/blob/9167d5241711493b79e932c8b68750190f5a64df/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L755)):*
> ```Java
>   }
> 
>   public boolean shouldCloseLogStreamForCustomRemote(List<? extends ManifestOutcome> manifestOutcomes) {
> ```

Can be private if not getting used out of this class.
Else we can it public static if its a utility method

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 755 at r2](https://reviewable.io/reviews/harness/harness-core/37376#-NBlKlRhCY1ThCvB4wpw:-NBlKlRhCY1ThCvB4wpx:b-55p0aq) ([raw file](https://github.com/harness/harness-core/blob/9167d5241711493b79e932c8b68750190f5a64df/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L755)):*
> ```Java
>   }
> 
>   public boolean shouldCloseLogStreamForCustomRemote(List<? extends ManifestOutcome> manifestOutcomes) {
> ```

nit: name of method should depict what its doing, Not where it is getting used.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 238 at r2](https://reviewable.io/reviews/harness/harness-core/37376#-NBpfw5U1WKILld52CjG:-NBpfw5U1WKILld52CjH:b-pevmjj) ([raw file](https://github.com/harness/harness-core/blob/9167d5241711493b79e932c8b68750190f5a64df/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L238)):*
> ```Java
>   protected TaskChainResponse prepareCustomFetchManifestAndValuesTaskChainResponse(StoreConfig storeConfig,
>       Ambiance ambiance, StepElementParameters stepElementParameters, List<ManifestOutcome> paramsOrValuesManifests,
>       K8sStepPassThroughData k8sStepPassThroughData, boolean shouldOpenLogStream, boolean closeLogStream) {
> ```

we should use ```K8sStepPassThroughData``` to pass around booleans

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 423 at r2](https://reviewable.io/reviews/harness/harness-core/37376#-NBpg73QCKoLkVu9irq7:-NBpg73QCKoLkVu9irq8:b-emas7b) ([raw file](https://github.com/harness/harness-core/blob/9167d5241711493b79e932c8b68750190f5a64df/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L423)):*
> ```Java
>   protected TaskChainResponse prepareHelmFetchValuesTaskChainResponse(Ambiance ambiance,
>       StepElementParameters stepElementParameters, List<ValuesManifestOutcome> aggregatedValuesManifests,
>       K8sStepPassThroughData k8sStepPassThroughData, boolean shouldOpenLogStream, boolean closeLogStream) {
> ```

we should use K8sStepPassThroughData to pass around booleans

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37376)* status: 10 file(s) to review. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 146 at r2](https://reviewable.io/reviews/harness/harness-core/37376#-NBlFo_04hvNZzDuEARf:-NDWR3VKBi2Nyjd27VZE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9167d5241711493b79e932c8b68750190f5a64df/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L146)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

nit: this can be HELM_CHART_REPO_STORE_TYPES. like we categorise in cg helmSourceRepo vs helmChartRepo
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 238 at r2](https://reviewable.io/reviews/harness/harness-core/37376#-NBlHVaFAVE1U-rjNSET:-NDWR5Gx5pxmHixB2jIS:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9167d5241711493b79e932c8b68750190f5a64df/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L238)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

nit: Lets have consistant naming between these two boolean. shouldOpenLogStream & shouldCloseLogStream
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 238 at r2](https://reviewable.io/reviews/harness/harness-core/37376#-NBpfw5U1WKILld52CjG:-NDWR6DQ7j8cn2Ih5tCW:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9167d5241711493b79e932c8b68750190f5a64df/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L238)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should use ```K8sStepPassThroughData``` to pass around booleans
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 273 at r2](https://reviewable.io/reviews/harness/harness-core/37376#-NBlH1TU4jQe9rLFI63-:-NDWR7Cn0yKUJJP-iGiB:b1niyud) ([raw file](https://github.com/harness/harness-core/blob/9167d5241711493b79e932c8b68750190f5a64df/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L273)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Lets check if store.delegateSelectors() itself doesn't get null.
</blockquote></details>

It can only be null if store is null. The delegateSelector is a parametric field. Therefore a parametricField object is assigned to delegate selector with null value and expressions if no delegate is passed in the delegate selector.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 423 at r2](https://reviewable.io/reviews/harness/harness-core/37376#-NBpg73QCKoLkVu9irq7:-NDWRj_L8a0ZmRCSLdaS:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9167d5241711493b79e932c8b68750190f5a64df/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L423)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should use K8sStepPassThroughData to pass around booleans
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 755 at r2](https://reviewable.io/reviews/harness/harness-core/37376#-NBlIUfcCDVNM2v9tY0w:-NDWRkh2B_ARPCovW-QV:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9167d5241711493b79e932c8b68750190f5a64df/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L755)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Can be private if not getting used out of this class.
Else we can it public static if its a utility method
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 755 at r2](https://reviewable.io/reviews/harness/harness-core/37376#-NBlKlRhCY1ThCvB4wpw:-NDWRm8d7nrsnE7ARosx:b-eh22uc) ([raw file](https://github.com/harness/harness-core/blob/9167d5241711493b79e932c8b68750190f5a64df/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L755)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

nit: name of method should depict what its doing, Not where it is getting used.
</blockquote></details>

Removed it. Made it more generalised.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/manifests/request/CustomManifestValuesFetchParams.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/37376#-NBlI0j5Bp0RJeyvVl4L:-NDWRrvC5QUUzAB-47eN:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9167d5241711493b79e932c8b68750190f5a64df/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/manifests/request/CustomManifestValuesFetchParams.java#L44)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

nit: Lets have consistant naming between these two boolean. shouldOpenLogStream & shouldCloseLogStream
</blockquote></details>

Done

**Review by achyuth-harness — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37376)* status: 5. unresolved discussions.

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37376)* status: 2. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37376)* status: :shipit: complete! ✓

**Pull request merged**
