### PR TITLE
feat: [CDS-38929]: Added support for ConfigFile inline

### PR DESCRIPTION
**Pull request by ivan-83**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34480)

### CODE REVIEW

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 12 of 19 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34480)* status: :shipit: complete! ✓

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 12 of 19 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34480)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java` line 124 at r2](https://reviewable.io/reviews/harness/harness-core/34480#-N54-wvE1Pfus0Pi8tTv:-N54-wvFDsR1G6wTynZ2:b-i8tk8p) ([raw file](https://github.com/harness/harness-core/blob/7069456deafe052bd2d01fe5410b660d07f8f8a2/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java#L124)):*
> ```Java
>     NGAccess ngAccess = AmbianceUtils.getNgAccess(ambiance);
>     if (isNotEmpty(files)) {
>       HarnessStoreFile harnessStoreFile = files.get(0);
> ```

let's double check with Meenakshi if having a single file is ok

**Review by vladimir-peric — DISMISSED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34480)* status: :shipit: complete! ✓

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 4 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34480)* status: :shipit: complete! ✓

**Review by vladimir-peric — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34480)* status: :shipit: complete! ✓

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34480)* status: :shipit: complete! ✓

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34480)* status: :shipit: complete! ✓

**Pull request merged**
