### PR TITLE
feat: [PIE-4592]: Support for stage and step expression in strategy

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35679)

### CODE REVIEW

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35679)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35679)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StageStrategyUtils.java` line 270 at r1](https://reviewable.io/reviews/harness/harness-core/35679#-N7oM7nt0bGHp_e9BKbQ:-N7oM7nt0bGHp_e9BKbR:bz44ljd) ([raw file](https://github.com/harness/harness-core/blob/bcf89f6441d4af41736ba21fd092a19fa466f97b/878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StageStrategyUtils.java#L270)):*
> ```Java
>    * @param level
>    * @return
>    */
> ```

Isnt there any generic strategyUtils, or rename this class



_Code quote:_
```Java
  /**
   * This is used to fetch strategy object map at a given level
   * @param level
   * @return
   */
```

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StageStrategyUtils.java` line 270 at r1](https://reviewable.io/reviews/harness/harness-core/35679#-N7oM7nt0bGHp_e9BKbQ:-N7oMpylB1kdgWdDq3Po:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bcf89f6441d4af41736ba21fd092a19fa466f97b/878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StageStrategyUtils.java#L270)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Isnt there any generic strategyUtils, or rename this class
</blockquote></details>

Done.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35679)* status: :shipit: complete! ✓

**Pull request merged**
