### PR TITLE
Fix: [CDS-2170]: Adds support for workflow variables rendering for Cloud Formation - Git

### PR DESCRIPTION
**Pull request by gitNavV**
- **Problem**
We use `renderExpression` to render workflow variables to Inline and S3 templates , but in case of Git templates, we were missing this logic on the manager side, and were fetching the template on the delegate side, due to which, we were not able to call `renderExpression` as this is not available on delegate side.

- **Solution**
We have moved the template fetching logic to manager side, even for Git templates, and now we render them similar to how we render parameters file from Git, we then fetch the contents of the template and run it through `renderExpression` to render workflow variables in it.
---
**You can use the following comments to re-trigger PR Checks**

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30658)

### CODE REVIEW

**Comment by gitNavV** [comment]
trigger messagecheck

**Comment by gitNavV** [comment]
trigger authorcheck

**Comment by gitNavV** [comment]
trigger ti3

**Comment by arvind-choudhary-h** [comment]
___
*[.mailmap, line 18 at r4](https://reviewable.io/reviews/harness/harness-core/30658#-Mw1FEXz7Jxa4e3yr1Ll:-Mw1FEXz7Jxa4e3yr1Lm:bit2qaf) ([raw file](https://github.com/harness/harness-core/blob/72c316716ba5c7e87be1c8780d994a7562e699cb/.mailmap#L18)):*
> ```
> Michael Katz <michael.katz@harness.io>              michael-katz <48811122+michael-katz@users.noreply.github.com>
> Munish Jalota <munish.jalota@harness.io>            munishjalota <82614571+munishjalota@users.noreply.github.com>
> Navneet Das <munish.jalota@harness.io>              gitNavV <6997802+gitNavV@users.noreply.github.com>
> ```

email needs to be updated.

**Comment by arvind-choudhary-h** [comment]
___
*[400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java, line 549 at r4](https://reviewable.io/reviews/harness/harness-core/30658#-Mw1LPbd52GFClVc8RYA:-Mw1L-Lw5PbbkR1Y8vSY:b3f6bs4) ([raw file](https://github.com/harness/harness-core/blob/72c316716ba5c7e87be1c8780d994a7562e699cb/400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java#L549)):*
> ```Java
>       gitTemplateBody = files.get(0).getFileContent();
>     } else {
>       for (int i = 0; i < files.stream().count(); i++) {
> ```

How are you filtering with git template file path? The code shows it will pick any file if it's not parameter file.



_Code quote:_
```Java
CF_PARAMETERS
```

**Comment by gitNavV** [comment]
> _[400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java, line 549 at r4](https://reviewable.io/reviews/harness/harness-core/30658#-Mw1LPbd52GFClVc8RYA:-Mw1L-Lw5PbbkR1Y8vSY:b3f6bs4) ([raw file](https://github.com/harness/harness-core/blob/72c316716ba5c7e87be1c8780d994a7562e699cb/400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java#L549)):_
> 
> > ```java
> >       gitTemplateBody = files.get(0).getFileContent();
> >     } else {
> >       for (int i = 0; i < files.stream().count(); i++) {
> > ```
> 
> How are you filtering with git template file path? The code shows it will pick any file if it's not parameter file.
> 
> _Code quote:_
> 
> ```java
> CF_PARAMETERS
> ```

Do we have any other paths?

**Comment by arvind-choudhary-h** [comment]
___
*[400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java, line 549 at r4](https://reviewable.io/reviews/harness/harness-core/30658#-Mw1LPbd52GFClVc8RYA:-Mw1LvWf4z6XpvfMq8EM:b-yov6c5) ([raw file](https://github.com/harness/harness-core/blob/72c316716ba5c7e87be1c8780d994a7562e699cb/400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java#L549)):*
<details><summary><i>Previously, gitNavV (Navneet Das) wrote…</i></summary><blockquote>

Do we have any other paths?
</blockquote></details>

It's in GitFileConfig. The path which is provided by Infrastructure Provisioner.

**Comment by arvind-choudhary-h** [comment]
___
*[400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java, line 549 at r4](https://reviewable.io/reviews/harness/harness-core/30658#-Mw1LPbd52GFClVc8RYA:-Mw1MSmZ3eGynbL2VFC0:bcd5lg5) ([raw file](https://github.com/harness/harness-core/blob/72c316716ba5c7e87be1c8780d994a7562e699cb/400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java#L549)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

It's in GitFileConfig. The path which is provided by Infrastructure Provisioner.
</blockquote></details>

You can take reference from this method:



_Code quote (from 400-rest/src/main/java/software/wings/delegatetasks/cloudformation/cloudformationtaskhandler/CloudFormationCreateStackHandler.java):_
```Java
  private void setRequestDataFromGit(CloudFormationCreateStackRequest request) {
    GitOperationContext gitOperationContext = gitUtilsDelegate.cloneRepo(
        request.getGitConfig(), request.getGitFileConfig(), request.getSourceRepoEncryptionDetails());
    String templatePathRepo =
        gitUtilsDelegate.resolveAbsoluteFilePath(gitOperationContext, request.getGitFileConfig().getFilePath());
    request.setData(gitUtilsDelegate.getRequestDataFromFile(templatePathRepo));
    request.setCreateType(CLOUD_FORMATION_STACK_CREATE_BODY);
  }
```

**Comment by gitNavV** [comment]
> _[.mailmap, line 18 at r4](https://reviewable.io/reviews/harness/harness-core/30658#-Mw1FEXz7Jxa4e3yr1Ll:-Mw1FEXz7Jxa4e3yr1Lm:bit2qaf) ([raw file](https://github.com/harness/harness-core/blob/72c316716ba5c7e87be1c8780d994a7562e699cb/.mailmap#L18)):_
> 
> > ```
> > Michael Katz <michael.katz@harness.io>              michael-katz <48811122+michael-katz@users.noreply.github.com>
> > Munish Jalota <munish.jalota@harness.io>            munishjalota <82614571+munishjalota@users.noreply.github.com>
> > Navneet Das <munish.jalota@harness.io>              gitNavV <6997802+gitNavV@users.noreply.github.com>
> > ```
> 
> email needs to be updated.

Done.

**Comment by gitNavV** [comment]
> _[400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java, line 549 at r4](https://reviewable.io/reviews/harness/harness-core/30658#-Mw1LPbd52GFClVc8RYA:-Mw1L-Lw5PbbkR1Y8vSY:b3f6bs4) ([raw file](https://github.com/harness/harness-core/blob/72c316716ba5c7e87be1c8780d994a7562e699cb/400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java#L549)):_
> 
> > ```java
> >       gitTemplateBody = files.get(0).getFileContent();
> >     } else {
> >       for (int i = 0; i < files.stream().count(); i++) {
> > ```
> 
> How are you filtering with git template file path? The code shows it will pick any file if it's not parameter file.
> 
> _Code quote:_
> 
> ```java
> CF_PARAMETERS
> ```

Fixed in 1e0dee9ab2c9851393e3c9eba3c0e4e8f80baa15.

**Comment by gitNavV** [comment]
trigger feature-build

**Comment by gitNavV** [comment]
@arvind-choudhary-h Could you please review this commit - 0c756fef958bee8af237e055a33ca3e6578eb1dc?

Needed to change this to preserve the path value after control gets shifted to Delegate and then back to Manager.

**Comment by gitNavV** [comment]
trigger feature-build

**Comment by arvind-choudhary-h** [comment]
___
*[.mailmap, line 18 at r4](https://reviewable.io/reviews/harness/harness-core/30658#-Mw1FEXz7Jxa4e3yr1Ll:-Mw5EKcZ6Evqy3RrbKiQ:b-q158p0) ([raw file](https://github.com/harness/harness-core/blob/72c316716ba5c7e87be1c8780d994a7562e699cb/.mailmap#L18)):*
<details><summary><i>Previously, gitNavV (Navneet Das) wrote…</i></summary><blockquote>

Updated in 4a76ebddd96b5438c297a210699187febe7d0844.
</blockquote></details>

This is yet to be updated.

**Comment by gitNavV** [comment]
> _[.mailmap, line 18 at r4](https://reviewable.io/reviews/harness/harness-core/30658#-Mw1FEXz7Jxa4e3yr1Ll:-Mw5EKcZ6Evqy3RrbKiQ:b-q158p0) ([raw file](https://github.com/harness/harness-core/blob/72c316716ba5c7e87be1c8780d994a7562e699cb/.mailmap#L18)):_
> 
> Previously, gitNavV (Navneet Das) wrote…
> > Updated in [4a76ebd](https://github.com/harness/harness-core/commit/4a76ebddd96b5438c297a210699187febe7d0844).
> 
> This is yet to be updated.

This is updated, what's left? - https://github.com/harness/harness-core/pull/30658/files#diff-cfe707d774682f3bbb07d3be5119da9938f80153b7d2cc168c02de9b8595caccR18

**Comment by gitNavV** [comment]
> _[.mailmap, line 18 at r4](https://reviewable.io/reviews/harness/harness-core/30658#-Mw1FEXz7Jxa4e3yr1Ll:-Mw5EKcZ6Evqy3RrbKiQ:b-q158p0) ([raw file](https://github.com/harness/harness-core/blob/72c316716ba5c7e87be1c8780d994a7562e699cb/.mailmap#L18)):_
> 
> Previously, gitNavV (Navneet Das) wrote…
> This is yet to be updated.

Not sure, what happened with this commit - 4a76ebddd96b5438c297a210699187febe7d0844

Updated again in 6ef32b1325ae1c9ddffc4aba890bc0a3fab84fd9.

**Comment by gitNavV** [comment]
trigger feature-build

**Comment by arvind-choudhary-h** [comment]
trigger feature-build

**Review by arvind-choudhary-h — DISMISSED** [review]
> Reviewed 1 of 2 files at r3, 6 of 7 files at r4, 1 of 2 files at r5, 2 of 2 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 1 of 1 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30658)* status: :shipit: complete! ✓

**Comment by arvind-choudhary-h** [comment]
trigger feature-build

**Comment by arvind-choudhary-h** [comment]
trigger feature-build

**Review by arvind-choudhary-h — DISMISSED** [review]
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30658)* status: :shipit: complete! ✓

**Comment by gitNavV** [comment]
trigger ti3

**Comment by gitNavV** [comment]
trigger ti1

**Comment by gitNavV** [comment]
trigger feature-build

**Comment by gitNavV** [comment]
trigger ti3

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 1 of 1 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30658)* status: :shipit: complete! ✓

**Pull request merged**
