### PR TITLE
fix: [DEL-3055]: Separating heatbeat from system executor in delegate agent

### PR DESCRIPTION
**Pull request by gaurav-jain1**
… executor

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/29966)

### CODE REVIEW

**Review by mdmilic — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29966)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java, line 631 at r1](https://reviewable.io/reviews/harness/harness-core/29966#-Mte6OWF4G2_UDYiw22V:-Mte6OWG50TJbt4CFdEq:b-wihv3q) ([raw file](https://github.com/harness/harness-core/blob/d474255a1b9d3bb2071c2169c99b2b2bbcac0a49/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L631)):*
> ```Java
>     ScheduledExecutorService healthMonitorExecutor = new ScheduledThreadPoolExecutor(
>         1, new ThreadFactoryBuilder().setNameFormat("healthMonitor-%d").setPriority(Thread.MAX_PRIORITY).build());
>     Runtime.getRuntime().addShutdownHook(new Thread(healthMonitorExecutor::shutdownNow));
> ```

We should avoid doing shutdown hooks here. I've created a more centralised place to do it in a separate PR (from the startup class, should get merged soon for you to sync). Also, this particular hook is not too useful, so I just removed them from all executor services. 
___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 626 at r1](https://reviewable.io/reviews/harness/harness-core/29966#-Mte79ptCmCIMgyfK7j6:-Mte79pu4t6Heru5AHp9:b-5eg0kp) ([raw file](https://github.com/harness/harness-core/blob/d474255a1b9d3bb2071c2169c99b2b2bbcac0a49/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L626)):*
> ```Java
> 
>         startHeartbeat(builder, socket);
>         // TODO(Abhinav): Check if we can avoid separate call for ECS delegates.
> ```

We should probably resolve this TODO

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29966)* status: 1 change requests. 6. unresolved discussions.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29966)* status: 1 change requests. 6. unresolved discussions.

**Review by abhinav-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29966)* status: 1 change requests. 6. unresolved discussions.

**Review by arpit3107 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29966#-:-Mtv0Pj87D3HiCThTHgy:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 6. unresolved discussions.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29966)* status: 6. unresolved discussions.

**Review by mdmilic — APPROVED** [review]
> Reviewed all commit messages.
> Dismissed @bharatgoelharness from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29966)* status: :shipit: complete! ✓

*[a discussion](https://reviewable.io/reviews/harness/harness-core/29966#-Mte85Hi-tGGI3Spq-oS:-MtyK2ShBDZgyO4eM_HP:b-r8urw6) (no related file):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

IMO its about the use case. Heartbeat is a standard mechanism to verify on service health. I am not the expert on k8, so cannot comment on the strict need to have that. We can revisit this based on usecase and demand.
</blockquote></details>

It is, but it's not only the point in heartbeating, the point is in hearbeat doing some meaningful check or running on some meaningful thread. For us it only proves that JVM is alive, nothing else. In delegate agent, if heartbeat thread is the only one alive and all others stopped or deadlocked, it would still hearbeat and say it's alive, which really isn't. So that's why I say our current implementation is (almost) pointless.
I agree though this is a future improvement so, resolving the comment. 

---

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29966)* status: Some of the checks are too old. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/29966#-Mte85Hi-tGGI3Spq-oS:-MuFUNGy9QT92nG_otox:bw3siyk) (no related file):*
> , it would still hearbeat and say it's alive, which really isn't. So that's why I say our current implementation is (almost) pointless.
Got it what you want to convey, we can certainly make this mechanism more robust by getting the internal health of agent. Probably a good problem to solve.

---

**Review by bharatgoelharness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29966)* status: Some of the checks are too old.

**Review by bharatgoelharness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29966#-:-MuKRy2b8b31UIIDq7sR:bnfp4nl)* status: Some of the checks are too old.

**Review by bharatgoelharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29966)* status: Some of the checks are too old.

**Review by bharatgoelharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29966)* status: Some of the checks are too old. 

___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 1431 at r1](https://reviewable.io/reviews/harness/harness-core/29966#-MtaUQGxW3OZMftdYsrx-r1-1431:-MuKSEGU4OzaqkH9g1Nb:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/d474255a1b9d3bb2071c2169c99b2b2bbcac0a49/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1431)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

I discussed this with Raghu and concluded that we should have max thread limit for scheduled executors to avoid having infinite number of threads. But looks like we don't have this facility with ScheduledThreadPoolExecutor. Hence leaving this as is for now.
</blockquote></details>

ok

**Review by bharatgoelharness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29966#-:-MuKSRxK57QvDb-I_jWg:bnfp4nl)* status: Some of the checks are too old.

**Review by bharatgoelharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29966)* status: Some of the checks are too old.

**Review by bharatgoelharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29966)* status: Some of the checks are too old. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/29966#-Mte85Hi-tGGI3Spq-oS:-MuKSjgVAM179Kygq90x:b2ni9ah) (no related file):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

> , it would still hearbeat and say it's alive, which really isn't. So that's why I say our current implementation is (almost) pointless.
Got it what you want to convey, we can certainly make this mechanism more robust by getting the internal health of agent. Probably a good problem to solve.
</blockquote></details>

ok

---
*[a discussion](https://reviewable.io/reviews/harness/harness-core/29966#-Mte9EkwEXiEQWjdhfJ8:-MuKSkozAnU2hie8RSr-:b32wtd) (no related file):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok

---

**Review by gaurav-jain1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29966)* status: 1 file(s) to review.

**Pull request merged**
