### PR TITLE
feat: [CDS-50706]: cascade deletion for org level CD entities

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
Cascade deletion for Service, Env, Env Groups, Infra, Service Overrides, Clusters at Org level
Account level cascade deletion to be done later

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42624)

### CODE REVIEW

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Comment by vivekkarnatiharness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/EnvironmentGroupEntityCrudStreamListener.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/42624#-NLuPbVNCMFW-f6ZCX2y:-NLuPbVNCMFW-f6ZCX2z:b6behyp) ([raw file](https://github.com/harness/harness-core/blob/b6f377c942d1a5da651656bf737203009a690c02/120-ng-manager/src/main/java/io/harness/ng/core/event/EnvironmentGroupEntityCrudStreamListener.java#L41)):*
> ```Java
>     if (message != null && message.hasMessage()) {
>       Map<String, String> metadataMap = message.getMessage().getMetadataMap();
>       if (metadataMap.get(ENTITY_TYPE) != null && PROJECT_ENTITY.equals(metadataMap.get(ENTITY_TYPE))) {
> ```

metadataMap can be null,why have we removed null check

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42624)* status: 18 file(s) to review. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/EnvironmentGroupEntityCrudStreamListener.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/42624#-NLuPbVNCMFW-f6ZCX2y:-NLuSxrTCQkch1DlTNPR:b-uv771l) ([raw file](https://github.com/harness/harness-core/blob/b6f377c942d1a5da651656bf737203009a690c02/120-ng-manager/src/main/java/io/harness/ng/core/event/EnvironmentGroupEntityCrudStreamListener.java#L41)):*
<details><summary><i>Previously, vivekkarnatiharness wrote…</i></summary><blockquote>

metadataMap can be null,why have we removed null check
</blockquote></details>

metaDataMap will not be null. 



_Code snippet:_
```Java
In proto3, all fields are "optional" (in that it is not an error if the sender fails to set them). But, fields are no longer "nullable", in that there's no way to tell the difference between a field being explicitly set to its default value vs. not having been set at all.
```

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42624)* status: 20 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/ProjectEntityCRUDStreamListener.java` line 200 at r2](https://reviewable.io/reviews/harness/harness-core/42624#-NLjHMK5ocFq7cEeinsQ-r2-200:-NLyAVzfCb6OXzRmtq6y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b6f377c942d1a5da651656bf737203009a690c02/120-ng-manager/src/main/java/io/harness/ng/core/event/ProjectEntityCRUDStreamListener.java#L200)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we not delete environment groups here itself ?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/services/EnvironmentGroupService.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/42624#-NLtVpeZyoNBlOGTBAHa-r2-34:-NLyAYvREwd4Ngk6jpJF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b6f377c942d1a5da651656bf737203009a690c02/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/services/EnvironmentGroupService.java#L34)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This method should return boolean indicating the status of deletion
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/service/ClusterService.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/42624#-NLjHMK5ocFq7cEeinsS-r2-122:-NLyAaS0CpKsHxRtYf3r:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b6f377c942d1a5da651656bf737203009a690c02/127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/service/ClusterService.java#L122)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

@NotNull is redundant. primitive boolean can never be null
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 399 at r2](https://reviewable.io/reviews/harness/harness-core/42624#-NLjHMK5ocFq7cEeinsW-r2-399:-NLuXB4h20HENvL2rsic:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b6f377c942d1a5da651656bf737203009a690c02/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L399)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

infrastructureEntityListForProjectIdentifier looks confusing. Can we just call it infrastructures ?
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 400 at r2](https://reviewable.io/reviews/harness/harness-core/42624#-NLjHMK5ocFq7cEeinsW-r2-400:-NLuXBUN81qKqd4HuZ7_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b6f377c942d1a5da651656bf737203009a690c02/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L400)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

getAllInfrastructureFromProjectIdentifier is confusing, we should call it getInfrastructures(..)
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 812 at r2](https://reviewable.io/reviews/harness/harness-core/42624#-NLjHMK5ocFq7cEeinsY-r2-812:-NLuVA4G-1a10dYPGYBZ:b-ovy1fb) ([raw file](https://github.com/harness/harness-core/blob/b6f377c942d1a5da651656bf737203009a690c02/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L812)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We should follow consistent naming for our interface methods

forceDeleteAllInProject
forceDeleteAllOrgLevelServices

are not consistently named. Please check this in other interfaces as well
</blockquote></details>

I was thinking forceDeleteAllInOrg might be confusing in its use. I have added a javadoc for the same.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java` line 262 at r2](https://reviewable.io/reviews/harness/harness-core/42624#-NLjHMK5ocFq7cEeins_-r2-262:-NLuXaVgEZqSCY5zSkmJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b6f377c942d1a5da651656bf737203009a690c02/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java#L262)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

getServiceOverrideEqualityCriteriaForProj is confusing. Please check this for all other implementations eg. service/env/env group
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 14 of 18 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42624)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Review by hingerabhinav — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42624#-:-NM1n9lO1cgTYZKuv85j:bnfp4nl)* status: :shipit: complete! ✓

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 14 of 18 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42624)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42624)* status: :shipit: complete! ✓

**Pull request merged**
