### PR TITLE
fix:[DEL-5980]: deprecate LOG_STREAM_SERVICE_URL environment variable

### PR DESCRIPTION
**Pull request by xingchi-jin**
## Describe your changes
LOG_STREAM_SERVICE_URL could've been derived from manager url, in helm chart we are doing this.
But for docker installation command, we don't have to have one more argument to set. So we need to derive this value from manager url in the start.sh for immutable delegates only

https://github.com/harness/delegate-helm-chart/blob/main/harness-delegate-ng/templates/configMap.yaml#L22

Tests:
How I tested: I manually override the start.sh in a running delegate pod . execute the start.sh and check config.yml output

set LOG_STREAM_URL to empty value
image

image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43967)

### CODE REVIEW

**Review by Vbhatia20 — DISMISSED** [review]

**Review by AnupamIO — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43967)* status: :shipit: complete! ✓

**Review by mdmilic — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43967)* status: Some of the checks are too old. 

___
*[`dockerization/delegate/immutable-scripts/start.sh` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/43967#-NOyb6_K6LheIgYvncgW:-NOyb6_L8vd05j3vKW-J:b-xi1v4f) ([raw file](https://github.com/harness/harness-core/blob/e77c27006aca7df1789bb593805ba776eac611f1/dockerization/delegate/immutable-scripts/start.sh#L55)):*
> ```Shell
> echo "verificationServiceUrl: $MANAGER_HOST_AND_PORT/verification/" >> config.yml
> echo "cvNextGenUrl: $MANAGER_HOST_AND_PORT/cv/api/" >> config.yml
> echo "logStreamingServiceBaseUrl: $MANAGER_HOST_AND_PORT/log-service/" >> config.yml
> ```

This might now always be correct. As opposed to other services, we get log streaming service URL from Manager config (no idea why). That means that it doesn't necessarily need to follow this pattern. Best double check with SMP team (when looking for edge cases I always go there :smile:) and/or owners of log streaming service if it's safe to do this
https://github.com/harness/harness-core/blob/develop/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L4201

**Comment by xingchi-jin** [comment]
@mdmilic  i will address your comments in this task altogether https://harness.atlassian.net/browse/PL-31606  
Thank you, these are good comments

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43967)* status: :shipit: complete! ✓

**Pull request merged**
