### PR TITLE
[fix]: [CCM-7169]: Business mapping save api call should return object created

### PR DESCRIPTION
**Pull request by sdsingh07**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31922)

### CODE REVIEW

**Comment by sdsingh07** [comment]
trigger messagecheck

**Review by Rohit-Kaliki — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31922)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[450-ce-views/src/main/java/io/harness/ccm/views/businessMapping/dao/BusinessMappingDao.java, line 34 at r1](https://reviewable.io/reviews/harness/harness-core/31922#-MzVFrAXC6ADpEPD5R8y:-MzVFrAY1jih2WydBlFq:b1ojwlt) ([raw file](https://github.com/harness/harness-core/blob/4ad2b7b4ef76a7fca403de9daa2a218bf59e7bd5/450-ce-views/src/main/java/io/harness/ccm/views/businessMapping/dao/BusinessMappingDao.java#L34)):*
> ```Java
>   public BusinessMapping save(BusinessMapping businessMapping) {
>     hPersistence.save(businessMapping);
>     return businessMapping;
> ```

UI will require UUID of the Business mapping for further applying other Business Logic, let's return the saved entity in the mongo which will have the UUID

**Comment by sdsingh07** [comment]
> https://github.com/harness/harness-core/pull/31922#pullrequestreview-927627917

After save operation, the UUID will be automatically populated in the businessMapping object.. Hence, UI will get the UUID for other business logic.

**Review by Rohit-Kaliki — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31922#-:-MznAysz9BUs1c5c78bq:bnfp4nl)* status: Some of the checks are too old.

**Review by sdsingh07 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31922)* status: Some of the checks are too old. 1. unresolved discussions. 

___
*[450-ce-views/src/main/java/io/harness/ccm/views/businessMapping/dao/BusinessMappingDao.java, line 34 at r1](https://reviewable.io/reviews/harness/harness-core/31922#-MzVFrAXC6ADpEPD5R8y:-MznGEkTBQniCFvhAT28:bmnm6ow) ([raw file](https://github.com/harness/harness-core/blob/4ad2b7b4ef76a7fca403de9daa2a218bf59e7bd5/450-ce-views/src/main/java/io/harness/ccm/views/businessMapping/dao/BusinessMappingDao.java#L34)):*
<details><summary><i>Previously, Rohit-Kaliki (K Rohit Reddy) wrote…</i></summary><blockquote>

UI will require UUID of the Business mapping for further applying other Business Logic, let's return the saved entity in the mongo which will have the UUID
</blockquote></details>

After save operation, the UUID will be automatically populated in the businessMapping object. Hence, UI will get the UUID for other business logic.

**Review by Rohit-Kaliki — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31922)* status: :shipit: complete! ✓

**Pull request merged**
