### PR TITLE
feat: [CDS-42673]: AzureInfra + AwsInfra: Connection type (host, PrivateIP, PublicIP)

### PR DESCRIPTION
**Pull request by filip5rovic**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37542)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37542)

**Comment by filip5rovic** [comment]
trigger feature-build

**Comment by filip5rovic** [comment]
trigger messagecheck

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 30 of 41 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37542)* status: Some of the checks are too old.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 29 of 41 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37542)* status: Some of the checks are too old. 1 change requests. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java` line 318 at r2](https://reviewable.io/reviews/harness/harness-core/37542#-NCMX3caBffdNVM3yoZm:-NCMX3cb5nPi_zJvgM1a:bbttkde) ([raw file](https://github.com/harness/harness-core/blob/2de095eb59c8046a86c5340f3c49ad67d5a7dc41/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java#L318)):*
> ```Java
> 
>   private String mapToAddress(AwsEC2Instance awsEC2Instance, InfrastructureOutcome infrastructureOutcome) {
>     if (!(infrastructureOutcome instanceof SshWinRmAwsInfrastructureOutcome)) {
> ```

Minor - Should we throw an exception here if ifrastrucutureOutcome is no instance of SshWinRmAwsInfrastructureOutcome? 
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AwsSshWinrmPerpetualTaskExecutorNg.java` line 93 at r2](https://reviewable.io/reviews/harness/harness-core/37542#-NCMbdwd6zJYpO2lRXJO:-NCMbdwd6zJYpO2lRXJP:bmjsm0) ([raw file](https://github.com/harness/harness-core/blob/2de095eb59c8046a86c5340f3c49ad67d5a7dc41/260-delegate/src/main/java/io/harness/perpetualtask/AwsSshWinrmPerpetualTaskExecutorNg.java#L93)):*
> ```Java
> 
>   private String mapToAddress(AwsEC2Instance awsEC2Instance, String hostConnectionType) {
>     if (EmptyPredicate.isEmpty(hostConnectionType)) {
> ```

Maybe here force task params to have hostConnectionType, it means adding NotNull annotation in task param on hostConnectionType field and the default value should be always set on UI.  Here, throw an exception if it's empty.
___
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureComputeClientImpl.java` line 668 at r2](https://reviewable.io/reviews/harness/harness-core/37542#-NCMcwtR6pa_2ffkypi0:-NCMcwtR6pa_2ffkypi1:b2dlwhu) ([raw file](https://github.com/harness/harness-core/blob/2de095eb59c8046a86c5340f3c49ad67d5a7dc41/960-api-services/src/main/java/io/harness/azure/impl/AzureComputeClientImpl.java#L668)):*
> ```Java
>     VirtualMachineDataBuilder builder = VirtualMachineData.builder().hostName(virtualMachine.name());
> 
>     if (AzureHostConnectionType.PUBLIC_IP.equals(hostConnectionType)
> ```

We should be consistent and have the same behavior like for AWS, it means if AzureHostConnectionType is PUBLIC_IP and virtualMachine.getPrimaryPublicIPAddress() is null set null as address value and we have to deal with null in InfrastructureStep. In short force customers to setup env properly,  not to create the bug for us if we return hostname but customer set publicIp on UI. Or, document this behavior. Or, if this is behavior in CG we are good :)

**Review by anilchowdhury-harness — APPROVED** [review]
> Reviewed 28 of 41 files at r1, 9 of 12 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37542)* status: :shipit: complete! ✓

**Comment by filip5rovic** [comment]
trigger codebasehash

**Review by filip5rovic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37542)* status: 1 change requests. 2. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java` line 318 at r2](https://reviewable.io/reviews/harness/harness-core/37542#-NCMX3caBffdNVM3yoZm:-NCUsvMq-085NCdAg-_p:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/2de095eb59c8046a86c5340f3c49ad67d5a7dc41/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java#L318)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - Should we throw an exception here if ifrastrucutureOutcome is no instance of SshWinRmAwsInfrastructureOutcome? 
</blockquote></details>

Done
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AwsSshWinrmPerpetualTaskExecutorNg.java` line 93 at r2](https://reviewable.io/reviews/harness/harness-core/37542#-NCMbdwd6zJYpO2lRXJO:-NCUsxDH8n-_qg6baAsf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2de095eb59c8046a86c5340f3c49ad67d5a7dc41/260-delegate/src/main/java/io/harness/perpetualtask/AwsSshWinrmPerpetualTaskExecutorNg.java#L93)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Maybe here force task params to have hostConnectionType, it means adding NotNull annotation in task param on hostConnectionType field and the default value should be always set on UI.  Here, throw an exception if it's empty.
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureComputeClientImpl.java` line 668 at r2](https://reviewable.io/reviews/harness/harness-core/37542#-NCMcwtR6pa_2ffkypi0:-NCUsxsy8NhTIzI6fcnP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2de095eb59c8046a86c5340f3c49ad67d5a7dc41/960-api-services/src/main/java/io/harness/azure/impl/AzureComputeClientImpl.java#L668)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We should be consistent and have the same behavior like for AWS, it means if AzureHostConnectionType is PUBLIC_IP and virtualMachine.getPrimaryPublicIPAddress() is null set null as address value and we have to deal with null in InfrastructureStep. In short force customers to setup env properly,  not to create the bug for us if we return hostname but customer set publicIp on UI. Or, document this behavior. Or, if this is behavior in CG we are good :) 
</blockquote></details>

Done.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 41 files at r1, 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37542)* status: 2. unresolved discussions.

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37542)* status: :shipit: complete! ✓

**Pull request merged**
