### PR TITLE
fix: [DEL-4231]: Enable delegateStatus filter in API explorer

### PR DESCRIPTION
**Pull request by AnupamIO**
## Describe your changes
JIRA: https://harness.atlassian.net/browse/DEL-4231

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34156)

### CODE REVIEW

**Comment by jennyjames21** [comment]
*[`380-cg-graphql/src/main/java/io/harness/app/datafetcher/delegate/DelegateListDataFetcher.java` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/34156#-N47z5A_4VEvxA0GIA93:-N47z5A_4VEvxA0GIA94:bdjoxx1) ([raw file](https://github.com/harness/harness-core/blob/40f19a9ff70c58343313187ad395233429795dc0/380-cg-graphql/src/main/java/io/harness/app/datafetcher/delegate/DelegateListDataFetcher.java#L77)):*
> ```Java
>         delegateField = delegateQuery.field(DelegateKeys.status);
>         QLDelegateStatus filterDelegateStatus = qlDelegateFilter.getDelegateStatus();
>         // utils.setEnumFilter(field,filterDelegateStatus);
> ```

you can remove commented code

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34156)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`380-cg-graphql/src/main/java/io/harness/app/datafetcher/delegate/DelegateListDataFetcher.java` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/34156#-N47z5A_4VEvxA0GIA93:-N48ZiwH1pv8b8cAdK25:bqpewpv) ([raw file](https://github.com/harness/harness-core/blob/40f19a9ff70c58343313187ad395233429795dc0/380-cg-graphql/src/main/java/io/harness/app/datafetcher/delegate/DelegateListDataFetcher.java#L77)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

you can remove commented code
</blockquote></details>

you mean instead of using StringFilter just uncomment enumFilter?

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34156)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`380-cg-graphql/src/main/java/io/harness/app/datafetcher/delegate/DelegateListDataFetcher.java` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/34156#-N47z5A_4VEvxA0GIA93:-N48aark29hxyZ3XNtHz:b-cei3p7) ([raw file](https://github.com/harness/harness-core/blob/40f19a9ff70c58343313187ad395233429795dc0/380-cg-graphql/src/main/java/io/harness/app/datafetcher/delegate/DelegateListDataFetcher.java#L77)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

whichever not in use with after your change ---   // utils.setEnumFilter(field,filterDelegateStatus);
</blockquote></details>

that is already removed: please refer: https://github.com/harness/harness-core/pull/34156/files

**Review by jennyjames21 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34156)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
:lgtm:

**Review by jennyjames21 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34156)* status: :shipit: complete! ✓

**Comment by AnupamIO** [comment]
trigger messagecheck

**Review by AnupamIO — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34156#-:-N48j3Ga2onSa2149USK:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
