### PR TITLE
feat: [CDS-46922]: get env refs using env group scope for execution

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
build scoped envRefs for environments part of env group

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42065)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 512 at r2](https://reviewable.io/reviews/harness/harness-core/42065#-NKSHPOREfSODhY8og0g:-NKSHPOREfSODhY8og0h:b-hi1m6a) ([raw file](https://github.com/harness/harness-core/blob/34415df5b467d653f25debda1e1d05c908991c7e/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L512)):*
> ```Java
>       return getEnvironmentsMap(environments, Scope.fromString(envGroupRefSplit[0]));
>     }
>   }
> ```

Can we extract this function out to a util so that it can be used at other places?



_Code quote:_
```Java
    String[] envGroupRefSplit = StringUtils.split(
        (String) environmentGroupYaml.getEnvGroupRef().fetchFinalValue(), ".", MAX_RESULT_THRESHOLD_FOR_SPLIT);
    if (envGroupRefSplit == null || envGroupRefSplit.length == 1) {
      return getEnvironmentsMap(environments, Scope.PROJECT);
    } else {
      return getEnvironmentsMap(environments, Scope.fromString(envGroupRefSplit[0]));
    }
  }
```

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42065)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42065)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 512 at r2](https://reviewable.io/reviews/harness/harness-core/42065#-NKSHPOREfSODhY8og0g:-NKSKiEnDjBdxgVsB--N:b-1t3zr8) ([raw file](https://github.com/harness/harness-core/blob/34415df5b467d653f25debda1e1d05c908991c7e/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L512)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we extract this function out to a util so that it can be used at other places?
</blockquote></details>

@sahilhindwani-harness can you please explain how this can be used at other places? I think its a specific use case.

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42065)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 512 at r2](https://reviewable.io/reviews/harness/harness-core/42065#-NKSHPOREfSODhY8og0g:-NKSVECx01UZO-mznUMi:b-iw0r95) ([raw file](https://github.com/harness/harness-core/blob/34415df5b467d653f25debda1e1d05c908991c7e/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L512)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

@sahilhindwani-harness can you please explain how this can be used at other places? I think its a specific use case. 
</blockquote></details>

Added util

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42065)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42065)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42065)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42065)* status: :shipit: complete! ✓

**Pull request merged**
