### PR TITLE
fix: [CDS-45074]: Adding new indexes and removing old unused indexes from …

### PR DESCRIPTION
**Pull request by Y0709**
…deployments table. Also increased chunk size to further optimize timescale db queries for deployments table. This migration is executed through q\executing queries in code as we cannot drop so many sql indexes through java code in one go 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40238)

### CODE REVIEW

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40238)* status: :shipit: complete! ✓

**Comment by Y0709** [comment]
Not to merge yet

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 7 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40238)* status: :shipit: complete! ✓

**Comment by Y0709** [comment]
trigger ti0, ti1, ti2,ti3,ti4

**Review by abhinavmittal-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40238)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/TimescaleDBDataMigrationList.java` line 49 at r5](https://reviewable.io/reviews/harness/harness-core/40238#-NHc-WhQ42OcfVqCDIOM:-NHc-WhQ42OcfVqCDION:bpuzkwd) ([raw file](https://github.com/harness/harness-core/blob/bf071048f3f062bc08922c773933d9a7b0bccdad/390-db-migration/src/main/java/io/harness/migrations/TimescaleDBDataMigrationList.java#L49)):*
> ```Java
>         .add(Pair.of(12, BaseTimeScaleDBDataMigration.class))
>         .add(Pair.of(13, AddNotificationSentStatusToAnomalies.class))
>         .add(Pair.of(14, AddOnDemandRollbackDetailsToDeployment.class))
> ```

the order is wrong

**Review by abhinavmittal-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40238#-:-NHc1JsY0KrzyEcgpA3a:bnfp4nl)* status: 1 file(s) to review.

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40238)* status: :shipit: complete! ✓

**Pull request merged**
