### PR TITLE
[feat]: [CDS-78125]: Final changes for supporting v0 steps/stages in v1 pipeline

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Final changes for supporting v0 steps/stages in v1 pipeline.
Using the previous PR's utils to propagate the parentInfo from parent to children and getting the nextId from both dependencies and sibling from yamlNode so that both versions works together.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52418)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52418)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/AbstractStagePlanCreator.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/52418#-NdVGmZd8WW5sQ11ta3b:-NdVGmZd8WW5sQ11ta3c:b-ki5ty) ([raw file](https://github.com/harness/harness-core/blob/5ab8204a575e90869ee90e83b6f188a05a758f9e/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/AbstractStagePlanCreator.java#L69)):*
> ```Java
>    */
>   protected List<AdviserObtainment> getAdviserObtainmentFromMetaData(YamlField stageField, Dependency dependency) {
>     return StrategyUtils.getAdviserObtainments(stageField, kryoSerializer, true, dependency);
> ```

its this used by v0?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorService.java` line 288 at r1](https://reviewable.io/reviews/harness/harness-core/52418#-NdVGvWhElCtpwv_RyhB:-NdVGvWhElCtpwv_RyhC:b-g4rncs) ([raw file](https://github.com/harness/harness-core/blob/5ab8204a575e90869ee90e83b6f188a05a758f9e/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorService.java#L288)):*
> ```Java
>             yamlVersion = dependency.getParentInfo().getDataMap().get(YAML_VERSION).getStringValue();
>           }
>         }
> ```

extract private method out of it

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52418)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/AbstractStagePlanCreator.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/52418#-NdVGmZd8WW5sQ11ta3b:-NdYcUMDD6c2usJEnSF_:b-qi0g5t) ([raw file](https://github.com/harness/harness-core/blob/5ab8204a575e90869ee90e83b6f188a05a758f9e/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/AbstractStagePlanCreator.java#L69)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

its this used by v0?
</blockquote></details>

Yes its used from by V0. So passing the dependency in the method. Now this will handle V0 stage even if its coming from V1 parent.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorService.java` line 288 at r1](https://reviewable.io/reviews/harness/harness-core/52418#-NdVGvWhElCtpwv_RyhB:-NdYdW_m3Gl78eGVFOif:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5ab8204a575e90869ee90e83b6f188a05a758f9e/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorService.java#L288)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

extract private method out of it
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52418)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger ut5 ut8 commonchecks

**Comment by brijeshdhakar** [comment]
trigger ut8

**Comment by brijeshdhakar** [comment]
trigger codebasehashcheck pmd

**Review by shalini-agr — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52418)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger review

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52418)* status: :shipit: complete! ✓

**Pull request merged**
