### PR TITLE
feat: [CDS-33539]: ship helm v3.8.0 binary

### PR DESCRIPTION
**Pull request by achyuth-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30735)

### CODE REVIEW

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 1 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30735)* status: 13 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/software/wings/delegatetasks/helm/HelmValuesFetchTask.java, line 125 at r2](https://reviewable.io/reviews/harness/harness-core/30735#-Mwj_Fcw-xQukMlabTbY:-Mwj_Fcw-xQukMlabTbZ:b-5ig2v6) ([raw file](https://github.com/harness/harness-core/blob/d8d4ac2a63a5513470b0d66116b8f0c99f4f48ee/260-delegate/src/main/java/software/wings/delegatetasks/helm/HelmValuesFetchTask.java#L125)):*
> ```Java
>     String helmPath = (helmVersion == HelmVersion.V3)
>         ? InstallUtils.getHelm3Path()
>         : (helmVersion == HelmVersion.V380 ? InstallUtils.getNewHelm3Path() : InstallUtils.getHelm2Path());
> ```

better to have switch case

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r1, 4 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30735)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java, line 756 at r2](https://reviewable.io/reviews/harness/harness-core/30735#-MwjpJlpC0vn7cTI2Od4:-MwjpJlpC0vn7cTI2Od5:bhiqlpo) ([raw file](https://github.com/harness/harness-core/blob/d8d4ac2a63a5513470b0d66116b8f0c99f4f48ee/400-rest/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java#L756)):*
> ```Java
>       return ensureHelmCliAndTillerInstalled(commandRequest);
>     }
>     return ensureHelm3Installed(commandRequest);
> ```

This "theoretically" changes existing behaviour for the case when version is null
___
*[960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java, line 526 at r2](https://reviewable.io/reviews/harness/harness-core/30735#-MwjuCq9EvxG1C9qZFpB:-MwjuCqBC4lb7zxmlx75:blzfr8s) ([raw file](https://github.com/harness/harness-core/blob/d8d4ac2a63a5513470b0d66116b8f0c99f4f48ee/960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java#L526)):*
> ```Java
>   @Override
>   public String getHelmPath(HelmVersion helmVersion) {
>     if (helmVersion == HelmVersion.V2) {
> ```

we need to return "helm" even if version == null

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30735)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/software/wings/delegatetasks/helm/HelmValuesFetchTask.java, line 125 at r2](https://reviewable.io/reviews/harness/harness-core/30735#-Mwj_Fcw-xQukMlabTbY:-Mwk8fhmB49XiYXHTvf3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d8d4ac2a63a5513470b0d66116b8f0c99f4f48ee/260-delegate/src/main/java/software/wings/delegatetasks/helm/HelmValuesFetchTask.java#L125)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

better to have switch case
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java, line 756 at r2](https://reviewable.io/reviews/harness/harness-core/30735#-MwjpJlpC0vn7cTI2Od4:-MwkAHX4AqknN0cMxiJz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d8d4ac2a63a5513470b0d66116b8f0c99f4f48ee/400-rest/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java#L756)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This "theoretically" changes existing behaviour for the case when version is null
</blockquote></details>

Done.
___
*[960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java, line 526 at r2](https://reviewable.io/reviews/harness/harness-core/30735#-MwjuCq9EvxG1C9qZFpB:-MwkEe3W98rNidk9IgHZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d8d4ac2a63a5513470b0d66116b8f0c99f4f48ee/960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java#L526)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we need to return "helm" even if version == null
</blockquote></details>

Done.

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30735)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[960-api-services/src/main/java/io/harness/delegate/configuration/InstallUtils.java, line 1225 at r3](https://reviewable.io/reviews/harness/harness-core/30735#-Mwz-9Y5AIJVT4-ST5Sb:-Mwz-9Y5AIJVT4-ST5Sc:bmysyk1) ([raw file](https://github.com/harness/harness-core/blob/584d7b5570dd919eb0939c5002ae5ddd2a172e62/960-api-services/src/main/java/io/harness/delegate/configuration/InstallUtils.java#L1225)):*
> ```Java
>     if (isNotEmpty(delegateConfiguration.getHelm3Path())) {
>       // TODO: what/how to change here for v3.8.0?
>       helmPaths.put(helm3Version, delegateConfiguration.getHelm3Path());
> ```

we should also set for  helm3VersionNew
helmPaths.put(helm3VersionNew, delegateConfiguration.getHelm3Path());

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30735)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[960-api-services/src/main/java/io/harness/delegate/configuration/InstallUtils.java, line 1225 at r3](https://reviewable.io/reviews/harness/harness-core/30735#-Mwz-9Y5AIJVT4-ST5Sb:-Mwzivc16JGcHBH2z1YU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/584d7b5570dd919eb0939c5002ae5ddd2a172e62/960-api-services/src/main/java/io/harness/delegate/configuration/InstallUtils.java#L1225)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should also set for  helm3VersionNew
helmPaths.put(helm3VersionNew, delegateConfiguration.getHelm3Path()); 
</blockquote></details>

Done.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 6 of 11 files at r1, 2 of 8 files at r2, 4 of 7 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30735)* status: 1 change requests. 1. unresolved discussions.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30735)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30735)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[on-prem/dockerless_pov_installer_generator/generate_installer.sh, line 138 at r5](https://reviewable.io/reviews/harness/harness-core/30735#-MxJ-9sdA1DGCuOMZgJa:-MxJ-9sdA1DGCuOMZgJb:b-jbgtri) ([raw file](https://github.com/harness/harness-core/blob/498b838806695e207b5166ca48184e49cb585852/on-prem/dockerless_pov_installer_generator/generate_installer.sh#L138)):*
> ```Shell
>     done
> 
>     for version in v2.13.1 v3.0.2 v3.1.2 v3.8.0; do
> ```

are we using 3.0.2 in our code ? If not, we can remove it

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30735)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[on-prem/dockerless_pov_installer_generator/generate_installer.sh, line 138 at r5](https://reviewable.io/reviews/harness/harness-core/30735#-MxJ-9sdA1DGCuOMZgJa:-MxJ3hVS0aNXt4s-qYon:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/498b838806695e207b5166ca48184e49cb585852/on-prem/dockerless_pov_installer_generator/generate_installer.sh#L138)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

are we using 3.0.2 in our code ? If not, we can remove it
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 3 of 11 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30735)* status: 1 change requests. 1. unresolved discussions.

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 5 of 11 files at r1, 2 of 8 files at r2, 4 of 7 files at r3, 3 of 11 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30735)* status: 1 change requests. 1. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30735)* status: :shipit: complete! ✓

**Pull request merged**
