### PR TITLE
[fix]: [CDS-40494]: fixing fetching environment id from pipeline

### PR DESCRIPTION
**Pull request by lasdox**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35754)

### CODE REVIEW

**Review by prabu-kr — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35754)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/pipeline/PipelineServiceHelper.java` line 169 at r1](https://reviewable.io/reviews/harness/harness-core/35754#-N7yvvTl9gazzCSokl7K:-N7yvvTl9gazzCSokl7L:b9oevm0) ([raw file](https://github.com/harness/harness-core/blob/c5a12bc6abea6160c52376fd739d5dc4c7edfde7/400-rest/src/main/java/software/wings/service/impl/pipeline/PipelineServiceHelper.java#L169)):*
> ```Java
>   public static String resolveEnvIdForPipelineStage(Map<String, Object> pipelineStageElementProperties,
>       Map<String, String> workflowVariables, List<Variable> pipelineVariables) {
>     String envId = workflowVariables.get("Environment");
> ```

This approach won't work. The name of the variable won't always be "Environment". It's whatever name you give for the workflow variable when you templatize in the workflow. To get the actual name of the variable to look for, search through the pipelineVariables and find the variable with obtainEntityType() == ENVIRONMENT and then use the 'value' of the variable as the key to look for in 'workflowVariables'.

**Review by prabu-kr — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35754)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/pipeline/PipelineServiceHelper.java` line 170 at r2](https://reviewable.io/reviews/harness/harness-core/35754#-N88V8-8ELhRxjDPROQR:-N88V8-8ELhRxjDPROQS:b-hofdro) ([raw file](https://github.com/harness/harness-core/blob/ba298f79e48ab3d7779dedccfa0bd9931b4b1a64/400-rest/src/main/java/software/wings/service/impl/pipeline/PipelineServiceHelper.java#L170)):*
> ```Java
>       Map<String, String> workflowVariables, List<Variable> pipelineVariables) {
>     String environmentVariable = pipelineVariables.stream()
>                                      .filter(var -> var.obtainEntityType().equals(EntityType.ENVIRONMENT))
> ```

Do EntityType.ENVIRONMENT.equals(var.obtainEntityType()). There can be non-entity type variables in pipeline too like text variables where obtainEntityType() will return null



_Code quote:_
```Java
EntityType.ENVIRONMENT
```

**Comment by lasdox** [comment]
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/35754)_ status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`400-rest/src/main/java/software/wings/service/impl/pipeline/PipelineServiceHelper.java` line 170 at r2](https://reviewable.io/reviews/harness/harness-core/35754#-N88V8-8ELhRxjDPROQR:-N88V8-8ELhRxjDPROQS:b-hofdro) ([raw file](https://github.com/harness/harness-core/blob/ba298f79e48ab3d7779dedccfa0bd9931b4b1a64/400-rest/src/main/java/software/wings/service/impl/pipeline/PipelineServiceHelper.java#L170)):_
> 
> > ```java
> >       Map<String, String> workflowVariables, List<Variable> pipelineVariables) {
> >     String environmentVariable = pipelineVariables.stream()
> >                                      .filter(var -> var.obtainEntityType().equals(EntityType.ENVIRONMENT))
> > ```
> 
> Do EntityType.ENVIRONMENT.equals(var.obtainEntityType()). There can be non-entity type variables in pipeline too like text variables where obtainEntityType() will return null
> 
> _Code quote:_
> 
> ```java
> EntityType.ENVIRONMENT
> ```

I dont think that changing the order of the equality would make any difference, but changed it, will work on unit test right now

**Review by prabu-kr — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35754)* status: :shipit: complete! ✓

**Pull request merged**
