### PR TITLE
feat: [CDS-67780]: Template-Service client code re-organisation

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Moved Template-Service-Client to commons

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47343)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by abhayganvir** [comment]
trigger messagecheck

**Comment by utkarshchoubey-harness** [comment]
trigger checkstylecodeformat

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger checkstylecodeformat

**Comment by utkarshchoubey-harness** [comment]
trigger pmd

**Comment by utkarshchoubey-harness** [comment]
trigger compile

**Comment by utkarshchoubey-harness** [comment]
trigger codebasehash

**Comment by utkarshchoubey-harness** [comment]
trigger checkstylecodeformat

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Review by shivamnegi94 — APPROVED** [review]

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47343)* status: 34 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`440-connector-nextgen/BUILD.bazel` line 52 at r5](https://reviewable.io/reviews/harness/harness-core/47343#-NV5KiBtDCnmvkl9QPKr:-NV87I261k28lzzSmI56:bro8lbp) ([raw file](https://github.com/harness/harness-core/blob/377155e00cf12f9f36d864fabb75cf4464b16ad2/440-connector-nextgen/BUILD.bazel#L52)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why is it needed here?
</blockquote></details>

Done, Because this file io.harness.connector.helper.CustomSecretManagerHelper is using template client
___
*[`platform-service/modules/resource-group-service/BUILD.bazel` line 47 at r5](https://reviewable.io/reviews/harness/harness-core/47343#-NV5KQcA5QdkHNl4usq3:-NV88nwmAp5CzxjyG7mi:b9z8i87) ([raw file](https://github.com/harness/harness-core/blob/377155e00cf12f9f36d864fabb75cf4464b16ad2/platform-service/modules/resource-group-service/BUILD.bazel#L47)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why does platform service need template-service client?
</blockquote></details>

Done, because client is used here io.harness.resourcegroup.resourceclient.template.TemplateResourceImpl
___
*[`scripts/jenkins/copyright-check.sh` line 10 at r5](https://reviewable.io/reviews/harness/harness-core/47343#-NV5KVgkBTGRF2kaSe9g:-NV88D5R7IEMfOJZnJuB:bssqsej) ([raw file](https://github.com/harness/harness-core/blob/377155e00cf12f9f36d864fabb75cf4464b16ad2/scripts/jenkins/copyright-check.sh#L10)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

Done, because have modified exclusion file, Copyright check was failing, Marc Suggested me to update this file as well in this pr
___
*[`srm-service/modules/cv-nextgen-service/service/BUILD.bazel` line 41 at r5](https://reviewable.io/reviews/harness/harness-core/47343#-NV5KXKgDZqk8qVbWOOR:-NV88AoH1MDiU154UgDG:b-oyn7fp) ([raw file](https://github.com/harness/harness-core/blob/377155e00cf12f9f36d864fabb75cf4464b16ad2/srm-service/modules/cv-nextgen-service/service/BUILD.bazel#L41)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why does srm need template-service client?
</blockquote></details>

Done, because client is used here io.harness.cvng.core.utils.template.TemplateFacade

**Review by archit-harness — APPROVED** [review]
> Reviewed 13 of 28 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 5 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47343)* status: 34 file(s) to review.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 20 of 28 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47343)* status: :shipit: complete! ✓

**Comment by utkarshchoubey-harness** [comment]
trigger feature-build

**Review by deepak-harness — APPROVED** [review]
> Reviewed 20 of 28 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47343)* status: :shipit: complete! ✓

**Review by reetika04 — APPROVED** [review]
> Reviewed 20 of 28 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47343)* status: :shipit: complete! ✓

**Review by ashishsanodia-harness — APPROVED** [review]
> Reviewed 20 of 28 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47343)* status: :shipit: complete! ✓

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Pull request merged**
