### PR TITLE
[feat]: [SRM-9972]: created NotificationRule entity, NotificationRuleDTO, NotificationRuleResource, NotificationRuleService

### PR DESCRIPTION
**Pull request by kapil-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32102)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger messagecheck

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32102)* status: 16 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleDTO.java, line 34 at r2](https://reviewable.io/reviews/harness/harness-core/32102#-N-M8boDBfX4GKcwFjFO:-N-M8boDBfX4GKcwFjFP:b-fpf2s3) ([raw file](https://github.com/harness/harness-core/blob/4e4b259bbcf07f794ef1917f7f717d0689258475/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleDTO.java#L34)):*
> ```Java
> 
>   boolean enabled;
>   @NotNull NotificationRuleType notificationRuleType;
> ```

this should be just type instead of notificationRuleType
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleResponse.java, line 23 at r2](https://reviewable.io/reviews/harness/harness-core/32102#-N-M8L6I1QXz-i247tBP:-N-M8L6I1QXz-i247tBQ:b-f5ow74) ([raw file](https://github.com/harness/harness-core/blob/4e4b259bbcf07f794ef1917f7f717d0689258475/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleResponse.java#L23)):*
> ```Java
> @Builder
> public class NotificationRuleResponse {
>   @NotNull @JsonProperty("notificationRule") private NotificationRuleDTO notificationRuleDTO;
> ```

We can just call the variable notificationRule instead of adding JsonProperty
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleSpec.java, line 16 at r2](https://reviewable.io/reviews/harness/harness-core/32102#-N-M8ifp0Y0UW8P8xJFB:-N-M8ifp0Y0UW8P8xJFC:bxpooxn) ([raw file](https://github.com/harness/harness-core/blob/4e4b259bbcf07f794ef1917f7f717d0689258475/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleSpec.java#L16)):*
> ```Java
> @SuperBuilder
> public abstract class NotificationRuleSpec {
>   public abstract NotificationRuleType getNotificationRuleType();
> ```

this should be called getType()
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleType.java, line 11 at r2](https://reviewable.io/reviews/harness/harness-core/32102#-N-M8mUe1WSZy_Ur9bEb:-N-M8mUe1WSZy_Ur9bEc:bma0cu8) ([raw file](https://github.com/harness/harness-core/blob/4e4b259bbcf07f794ef1917f7f717d0689258475/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleType.java#L11)):*
> ```Java
> 
> public enum NotificationRuleType {
>   MONITORED_SERVICE,
> ```

this should have a JsonProperty with Camel case.
Also we should first write resource level tests for this to make sure we are taking care of the convention and the yaml definition looks good.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/channels/CVNGEmailChannel.java, line 29 at r2](https://reviewable.io/reviews/harness/harness-core/32102#-N-M97cx0xeJJ-S7XtZS:-N-M97cx0xeJJ-S7XtZT:b-1k0b11) ([raw file](https://github.com/harness/harness-core/blob/4e4b259bbcf07f794ef1917f7f717d0689258475/300-cv-nextgen/src/main/java/io/harness/cvng/notification/channels/CVNGEmailChannel.java#L29)):*
> ```Java
> @JsonTypeName("Email")
> @JsonIgnoreProperties(ignoreUnknown = true)
> public class CVNGEmailChannel extends CVNGNotificationChannel {
> ```

We should find out the DTOs that are used by common notification and use them here instead of defining out own. If they are not part of the common code than we should figure out a way to share the definition.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32102)* status: 22 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleDTO.java, line 34 at r2](https://reviewable.io/reviews/harness/harness-core/32102#-N-M8boDBfX4GKcwFjFO:-N-Rirdc7Ekavi2OoOR6:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/4e4b259bbcf07f794ef1917f7f717d0689258475/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleDTO.java#L34)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

this should be just type instead of notificationRuleType
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleResponse.java, line 23 at r2](https://reviewable.io/reviews/harness/harness-core/32102#-N-M8L6I1QXz-i247tBP:-N-RiskZC0ST797L_Qaq:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/4e4b259bbcf07f794ef1917f7f717d0689258475/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleResponse.java#L23)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

We can just call the variable notificationRule instead of adding JsonProperty
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleSpec.java, line 16 at r2](https://reviewable.io/reviews/harness/harness-core/32102#-N-M8ifp0Y0UW8P8xJFB:-N-RitgB2rytf-TxM9Xy:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/4e4b259bbcf07f794ef1917f7f717d0689258475/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleSpec.java#L16)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

this should be called getType()
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleType.java, line 11 at r2](https://reviewable.io/reviews/harness/harness-core/32102#-N-M8mUe1WSZy_Ur9bEb:-N-Riv2hCzkS7VM9VFBt:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/4e4b259bbcf07f794ef1917f7f717d0689258475/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleType.java#L11)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

this should have a JsonProperty with Camel case.
Also we should first write resource level tests for this to make sure we are taking care of the convention and the yaml definition looks good.
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/channels/CVNGEmailChannel.java, line 29 at r2](https://reviewable.io/reviews/harness/harness-core/32102#-N-M97cx0xeJJ-S7XtZS:-N-RiwGV9FCnrmPpMwZh:b-ck6ssg) ([raw file](https://github.com/harness/harness-core/blob/4e4b259bbcf07f794ef1917f7f717d0689258475/300-cv-nextgen/src/main/java/io/harness/cvng/notification/channels/CVNGEmailChannel.java#L29)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

We should find out the DTOs that are used by common notification and use them here instead of defining out own. If they are not part of the common code than we should figure out a way to share the definition. 
</blockquote></details>

done, will be taken care of in next PR as discussed

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32102)* status: 17 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleDTO.java, line 36 at r3](https://reviewable.io/reviews/harness/harness-core/32102#-N-RhogO-vUDDGBg1ZZU:-N-RhogO-vUDDGBg1ZZV:bou45bv) ([raw file](https://github.com/harness/harness-core/blob/1cb38f45463aaf3f4dbe851ce314547f8228930b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleDTO.java#L36)):*
> ```Java
>   @NotNull NotificationRuleType type;
>   @NotNull NotificationRuleSpec spec;
>   @NotNull CVNGNotificationChannel channel;
> ```

instead of channel this should be notificationMethod
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleResponse.java, line 23 at r2](https://reviewable.io/reviews/harness/harness-core/32102#-N-M8L6I1QXz-i247tBP:-N-RhuflARSVTPORJjdO:b-bc5tc4) ([raw file](https://github.com/harness/harness-core/blob/4e4b259bbcf07f794ef1917f7f717d0689258475/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleResponse.java#L23)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

We can just call the variable notificationRule instead of adding JsonProperty
</blockquote></details>

the variable name should be notificationRule
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/NotificationRule.java, line 45 at r3](https://reviewable.io/reviews/harness/harness-core/32102#-N-RiC6PBusYIP2En6BH:-N-RiC6Q3QTFeLh1dvYH:b-t61w7e) ([raw file](https://github.com/harness/harness-core/blob/1cb38f45463aaf3f4dbe851ce314547f8228930b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/NotificationRule.java#L45)):*
> ```Java
> @FieldNameConstants(innerTypeName = "NotificationRuleKeys")
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @JsonIgnoreProperties(ignoreUnknown = true)
> ```

please review jackson related annotations from here. JsonIgnorePerperties is not needed.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/SLONotificationRule.java, line 28 at r3](https://reviewable.io/reviews/harness/harness-core/32102#-N-RiSFb83UgeXh3JnSG:-N-RiSFb83UgeXh3JnSH:bdh0lnc) ([raw file](https://github.com/harness/harness-core/blob/1cb38f45463aaf3f4dbe851ce314547f8228930b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/SLONotificationRule.java#L28)):*
> ```Java
> @EqualsAndHashCode(callSuper = true)
> public class SLONotificationRule extends NotificationRule {
>   SLONotificationRuleSpec sloSpec;
> ```

we should not save the spec directly . it should be transformed and this entity can have the spec properties directly. Please use transformer pattern for this.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/resources/NotificationRuleResource.java, line 41 at r3](https://reviewable.io/reviews/harness/harness-core/32102#-N-RijyH5wx4o689lZaX:-N-RijyH5wx4o689lZaY:b-wz1c3v) ([raw file](https://github.com/harness/harness-core/blob/1cb38f45463aaf3f4dbe851ce314547f8228930b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/resources/NotificationRuleResource.java#L41)):*
> ```Java
> import retrofit2.http.Body;
> 
> @Api("notification")
> ```

if the Resource is NotificationRule then url should also be notification-rule.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/resources/NotificationRuleResource.java, line 83 at r3](https://reviewable.io/reviews/harness/harness-core/32102#-N-Rj3cP2o7tvfiBkdfy:-N-Rj3cQ5f6NZUoCJHc_:b-ripre8) ([raw file](https://github.com/harness/harness-core/blob/1cb38f45463aaf3f4dbe851ce314547f8228930b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/resources/NotificationRuleResource.java#L83)):*
> ```Java
>   public RestResponse<Boolean> deleteUpdateNotificationRuleData(@BeanParam ProjectParams projectParams,
>       @ApiParam(required = true) @NotNull @PathParam("identifier") String identifier) {
>     return new RestResponse<>(notificationRuleService.delete(projectParams, identifier));
> ```

in delete we will have to make sure that the notificationRule is not referred anywhere. Please create a jira to track this.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/resources/NotificationRuleResource.java, line 89 at r3](https://reviewable.io/reviews/harness/harness-core/32102#-N-RjGZe8BpQDNOf-9FU:-N-RjGZe8BpQDNOf-9FV:b-51ftth) ([raw file](https://github.com/harness/harness-core/blob/1cb38f45463aaf3f4dbe851ce314547f8228930b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/resources/NotificationRuleResource.java#L89)):*
> ```Java
>   @Timed
>   @ExceptionMetered
>   @ApiOperation(value = "get all service level objectives ", nickname = "getnotificationRules")
> ```

please check nickname to- getNotificationRules
Also check the description.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32102)* status: 22 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleDTO.java, line 36 at r3](https://reviewable.io/reviews/harness/harness-core/32102#-N-RhogO-vUDDGBg1ZZU:-N-Tul7jC609UhLfX1DU:b-23h1ea) ([raw file](https://github.com/harness/harness-core/blob/1cb38f45463aaf3f4dbe851ce314547f8228930b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleDTO.java#L36)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

instead of channel this should be notificationMethod
</blockquote></details>

I have removed channel for time being, working on this.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleResponse.java, line 23 at r2](https://reviewable.io/reviews/harness/harness-core/32102#-N-M8L6I1QXz-i247tBP:-N-TuwN76IV_7hDFPgoF:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/4e4b259bbcf07f794ef1917f7f717d0689258475/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleResponse.java#L23)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

the variable name should be notificationRule
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/NotificationRule.java, line 45 at r3](https://reviewable.io/reviews/harness/harness-core/32102#-N-RiC6PBusYIP2En6BH:-N-TuxmiDu_8it4-rI3r:bdek3t1) ([raw file](https://github.com/harness/harness-core/blob/1cb38f45463aaf3f4dbe851ce314547f8228930b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/NotificationRule.java#L45)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

please review jackson related annotations from here. JsonIgnorePerperties is not needed.
</blockquote></details>

done, removed
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/SLONotificationRule.java, line 28 at r3](https://reviewable.io/reviews/harness/harness-core/32102#-N-RiSFb83UgeXh3JnSG:-N-Tv-YvD1Ml9yPAxDQK:bpgfyh3) ([raw file](https://github.com/harness/harness-core/blob/1cb38f45463aaf3f4dbe851ce314547f8228930b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/SLONotificationRule.java#L28)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

we should not save the spec directly . it should be transformed and this entity can have the spec properties directly. Please use transformer pattern for this.
</blockquote></details>

done, created a new transformer
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/resources/NotificationRuleResource.java, line 41 at r3](https://reviewable.io/reviews/harness/harness-core/32102#-N-RijyH5wx4o689lZaX:-N-Tv2p016LolPmwEpzf:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1cb38f45463aaf3f4dbe851ce314547f8228930b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/resources/NotificationRuleResource.java#L41)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

if the Resource is NotificationRule then url should also be notification-rule.
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/resources/NotificationRuleResource.java, line 83 at r3](https://reviewable.io/reviews/harness/harness-core/32102#-N-Rj3cP2o7tvfiBkdfy:-N-Tv3oK76CTO8J6nPaC:b-rouvzg) ([raw file](https://github.com/harness/harness-core/blob/1cb38f45463aaf3f4dbe851ce314547f8228930b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/resources/NotificationRuleResource.java#L83)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

in delete we will have to make sure that the notificationRule is not referred anywhere. Please create a jira to track this.
</blockquote></details>

I have added a TODO for this
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/resources/NotificationRuleResource.java, line 89 at r3](https://reviewable.io/reviews/harness/harness-core/32102#-N-RjGZe8BpQDNOf-9FU:-N-Tv6UVEe7tmSgjbopP:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1cb38f45463aaf3f4dbe851ce314547f8228930b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/resources/NotificationRuleResource.java#L89)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

please check nickname to- getNotificationRules
Also check the description. 
</blockquote></details>

done

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 21 files at r3, 19 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32102#-:-N-WU1u7CKy_-c9p4jba:bnfp4nl)* status: 1. unresolved discussions. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/transformer/NotificationRuleEntityAndDTOTransformer.java, line 18 at r4](https://reviewable.io/reviews/harness/harness-core/32102#-N-W4EKO9MoWtHyBx7rb:-N-W4EKPD2oFg4HkHjwX:b5c61dr) ([raw file](https://github.com/harness/harness-core/blob/58123186907a1135c8f06de43f896f846d5c9ba5/300-cv-nextgen/src/main/java/io/harness/cvng/notification/transformer/NotificationRuleEntityAndDTOTransformer.java#L18)):*
> ```Java
> import java.util.Map;
> 
> public class NotificationRuleEntityAndDTOTransformer {
> ```

why do we need this class? I think we can directly get the transformer using map. We can take care of this in the next PR also.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/notification/transformer/SLONotificationRuleSpecTransformer.java, line 16 at r4](https://reviewable.io/reviews/harness/harness-core/32102#-N-W4YpbAmztpvYUMYbL:-N-W4YpcBuE_bAFnJ94Z:b-loegfn) ([raw file](https://github.com/harness/harness-core/blob/58123186907a1135c8f06de43f896f846d5c9ba5/300-cv-nextgen/src/main/java/io/harness/cvng/notification/transformer/SLONotificationRuleSpecTransformer.java#L16)):*
> ```Java
> import io.harness.cvng.notification.entities.SLONotificationRule;
> 
> public class SLONotificationRuleSpecTransformer
> ```

please write a test for this. You  can do it after merging also.

**Review by kjoshi12345 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32102#-:-N-WUI2sADVZAEPzOCFo:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
