### PR TITLE
fix: [PL-26411]: Error handling for hashicorp vault

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35524)

### CODE REVIEW

**Comment by VikasMaddukuriHarness** [comment]
trigger messagecheck

**Review by shreyas-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35524)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by shreyas-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35524)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35524)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 170 at r2](https://reviewable.io/reviews/harness/harness-core/35524#-N7nyuqZ0MH641FnxCTc:-N7nyuqZ0MH641FnxCTd:b-ugoywb) ([raw file](https://github.com/harness/harness-core/blob/005a092d0f4d33386ccbeff308977e2d54e9aea5/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L170)):*
> ```Java
>       logAndThrowErrorIfRequestFailed(result, "V1Impl-readSecret");
>       VaultReadResponse response = result.body();
>       return response == null || response.getData() == null ? null : response.getData().get(pathAndKey.keyName);
> ```

in case response == null or response.getData() == null the log following: secret path, isSuccessful, response message, response code
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 250 at r2](https://reviewable.io/reviews/harness/harness-core/35524#-N7nyTZa9ZkfEDyM4KHl:-N7nyTZa9ZkfEDyM4KHm:b-avyh71) ([raw file](https://github.com/harness/harness-core/blob/005a092d0f4d33386ccbeff308977e2d54e9aea5/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L250)):*
> ```Java
>         message = response.message() + response.body();
>       }
>       log.error("Could not {} secret in the vault due to the following error {}", action, message);
> ```

log response.message() in both cases.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35524)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 251 at r2](https://reviewable.io/reviews/harness/harness-core/35524#-N7nzZWK0ZZ75BKLp5Ho:-N7nzZWK0ZZ75BKLp5Hp:b-yay7ak) ([raw file](https://github.com/harness/harness-core/blob/005a092d0f4d33386ccbeff308977e2d54e9aea5/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L251)):*
> ```Java
>       }
>       log.error("Could not {} secret in the vault due to the following error {}", action, message);
>       throw new HashiCorpVaultRuntimeException(message);
> ```

Message should have response.message as well. Currently in case response body is non null its not capturing the response.message.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35524)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 170 at r2](https://reviewable.io/reviews/harness/harness-core/35524#-N7o4mUV6np8toMt7dIn:-N7o4mUV6np8toMt7dIo:b-rj9gbw) ([raw file](https://github.com/harness/harness-core/blob/005a092d0f4d33386ccbeff308977e2d54e9aea5/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L170)):*
> ```Java
>       logAndThrowErrorIfRequestFailed(result, "V1Impl-readSecret");
>       VaultReadResponse response = result.body();
>       return response == null || response.getData() == null ? null : response.getData().get(pathAndKey.keyName);
> ```

in case response == null or response.getData() == null then log following: secret path, isSuccessful, message, code (message and code can be extracted from result object)

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35524)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 170 at r2](https://reviewable.io/reviews/harness/harness-core/35524#-N7o4mUV6np8toMt7dIn:-N7o6aSFE9E3k3Ks_F2O:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/005a092d0f4d33386ccbeff308977e2d54e9aea5/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L170)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

in case response == null or response.getData() == null then log following: secret path, isSuccessful, message, code (message and code can be extracted from result object)
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 250 at r2](https://reviewable.io/reviews/harness/harness-core/35524#-N7nyTZa9ZkfEDyM4KHl:-N7o6b7hBzSv95B8V7lP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/005a092d0f4d33386ccbeff308977e2d54e9aea5/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L250)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

log response.message() in both cases.
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 251 at r2](https://reviewable.io/reviews/harness/harness-core/35524#-N7nzZWK0ZZ75BKLp5Ho:-N7o6Zxr1FXOmA0qn35u:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/005a092d0f4d33386ccbeff308977e2d54e9aea5/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L251)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Message should have response.message as well. Currently in case response body is non null its not capturing the response.message.
</blockquote></details>

Done.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35524)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 250 at r2](https://reviewable.io/reviews/harness/harness-core/35524#-N7nyTZa9ZkfEDyM4KHl:-N7speKi6c7VqX7GV-mz:b-932z2e) ([raw file](https://github.com/harness/harness-core/blob/005a092d0f4d33386ccbeff308977e2d54e9aea5/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L250)):*
<details><summary><i>Previously, VikasMaddukuriHarness (VikasMaddukuriHarness) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We should avoid concatenation of response.message() in both if and else block and instead add it to log statement.
log.error("Could not {} secret in the vault due to the following error {} | {}", action, response.message, message);
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 170 at r3](https://reviewable.io/reviews/harness/harness-core/35524#-N7spBKDBaxSBZJLNiHp:-N7spBKDBaxSBZJLNiHq:bd3r36) ([raw file](https://github.com/harness/harness-core/blob/72c0c8386cd40aad30dd6793cd94abd6515c8e17/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L170)):*
> ```Java
>       logAndThrowErrorIfRequestFailed(result, "V1Impl-readSecret");
>       VaultReadResponse response = result.body();
>       if (result.isSuccessful() && (response == null || response.getData() == null)) {
> ```

Can we log irrespective of what is the value of result.isSuccessful()

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35524)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 250 at r2](https://reviewable.io/reviews/harness/harness-core/35524#-N7nyTZa9ZkfEDyM4KHl:-N7u6upm-3wM4EE1renF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/005a092d0f4d33386ccbeff308977e2d54e9aea5/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L250)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

We should avoid concatenation of response.message() in both if and else block and instead add it to log statement.
log.error("Could not {} secret in the vault due to the following error {} | {}", action, response.message, message);
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 170 at r3](https://reviewable.io/reviews/harness/harness-core/35524#-N7spBKDBaxSBZJLNiHp:-N7u7mYFA0-RQ0BFkgW3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72c0c8386cd40aad30dd6793cd94abd6515c8e17/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L170)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Can we log irrespective of what is the value of result.isSuccessful()
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35524)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by shreyas-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35524)* status: :shipit: complete! ✓

**Pull request merged**
