### PR TITLE
[feat]: [PIE-6132]: Adding strategy support in Yaml version V1

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39522)

### CODE REVIEW

**Review by hextechpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39522)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 169 at r1](https://reviewable.io/reviews/harness/harness-core/39522#-NFvTsnuALl4x7jaU8BL:-NFvTsnuALl4x7jaU8BM:bc2y2zn) ([raw file](https://github.com/harness/harness-core/blob/d459ce988c4575d83950e7f94e7b526665666b31/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L169)):*
> ```Java
>     Map<String, GraphLayoutNode> stageYamlFieldMap = new LinkedHashMap<>();
>     EdgeLayoutList edgeLayoutList;
>     String planNodeId = yamlField.getNode().getField(YAMLFieldNameConstants.STRATEGY).getNode().getUuid();
> ```

use getProperty here
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 179 at r1](https://reviewable.io/reviews/harness/harness-core/39522#-NFvU3hWCj4YIT1CCM7O:-NFvU3hWCj4YIT1CCM7P:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/d459ce988c4575d83950e7f94e7b526665666b31/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L179)):*
> ```Java
>     if (yamlField.getNode().getField(YAMLFieldNameConstants.STRATEGY).getNode().getField("matrix") != null) {
>       strategyType = StrategyType.MATRIX;
>     } else if (yamlField.getNode().getField(YAMLFieldNameConstants.STRATEGY).getNode().getField("parallelism")
> ```

ditto
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java` line 121 at r1](https://reviewable.io/reviews/harness/harness-core/39522#-NFvTDmO5GC6QxYMbnb7:-NFvTDmO5GC6QxYMbnb8:b-yloz6c) ([raw file](https://github.com/harness/harness-core/blob/d459ce988c4575d83950e7f94e7b526665666b31/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java#L121)):*
> ```Java
>     CustomStageSpecParams params = CustomStageSpecParams.builder().childNodeID(childrenNodeIds.get(0)).build();
>     String name;
>     if (config.getNode().getCurrJsonNode().get("name") != null
> ```

use config.getNodeName() all this logic is already present in this functions



_Code quote:_
```Java
config.getNode().getCurrJsonNode().get("name")
```

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39522)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 169 at r1](https://reviewable.io/reviews/harness/harness-core/39522#-NFvTsnuALl4x7jaU8BL:-NFwED9rBbNYJdqoOiND:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d459ce988c4575d83950e7f94e7b526665666b31/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L169)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

use getProperty here
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 179 at r1](https://reviewable.io/reviews/harness/harness-core/39522#-NFvU3hWCj4YIT1CCM7O:-NFwEDn70fwiOf213RrQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d459ce988c4575d83950e7f94e7b526665666b31/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L179)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java` line 121 at r1](https://reviewable.io/reviews/harness/harness-core/39522#-NFvTDmO5GC6QxYMbnb7:-NFwEEVe3EnXVFLlBJ1v:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d459ce988c4575d83950e7f94e7b526665666b31/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java#L121)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

use config.getNodeName() all this logic is already present in this functions
</blockquote></details>

Done.

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by hextechpal — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39522)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 180 at r3](https://reviewable.io/reviews/harness/harness-core/39522#-NGFjDdN2yPrHI6bDT47:-NGFjDdN2yPrHI6bDT48:b-t9f4bf) ([raw file](https://github.com/harness/harness-core/blob/93aac8d65438aa7ff9f86e179ebe353e3da090a6/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L180)):*
> ```Java
>     if (yamlField.getNode()
>             .getField(YAMLFieldNameConstants.STRATEGY)
>             .getNode()
> ```

nit: Can we have this node in a variable and then do getProperty on that variable?



_Code quote:_
```Java
    if (yamlField.getNode()
            .getField(YAMLFieldNameConstants.STRATEGY)
            .getNode()
```

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39522)* status: 1 change requests. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39522)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger ti4

**Pull request merged**
