### PR TITLE
feat: [DEL-5780]: API to fetch delegate list with filters

### PR DESCRIPTION
**Pull request by AnupamIO**
API to fetch delegate list with filters using api, exposed on ng manager.

Testing:
Screenshot 2023-04-28 at 4 28 09 PM

Above parameters are filters, api will return all delegates if no filter is provided.
```
FilterType: delegate
```
above filterType has to be provided in body. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47124)

### CODE REVIEW

**Review by mdmilic — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47124)* status: 0 of 1 approvals obtained. Waiting on team(s): del-team. 

___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java` line 595 at r1](https://reviewable.io/reviews/harness/harness-core/47124#-NU71X8V9WU1TTnIPBT4:-NU71X8V9WU1TTnIPBT5:bjf2cdf) ([raw file](https://github.com/harness/harness-core/blob/b158bcdd1a42de7ce73ba90380fc3b8ea52d5593/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L595)):*
> ```Java
>     }
> 
>     long upgraderLastUpdated = delegateGroup != null ? delegateGroup.getUpgraderLastUpdated() : 0;
> ```

What would be a use case of null group, is that a valid scenario?



_Code quote:_
```Java
delegateGroup != null 
```
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java` line 605 at r1](https://reviewable.io/reviews/harness/harness-core/47124#-NU7-KY94XXKlcom-HbD:-NU7-KY94XXKlcom-HbE:bv6439x) ([raw file](https://github.com/harness/harness-core/blob/b158bcdd1a42de7ce73ba90380fc3b8ea52d5593/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L605)):*
> ```Java
>     long lastHeartBeat = groupDelegates.stream().mapToLong(Delegate::getLastHeartBeat).max().orElse(0);
> 
>     AtomicInteger countOfDelegatesConnected = new AtomicInteger();
> ```

No need for atomic here. You could also count it after you've collected (e.g. like lastHeartbeat or delegateCreationTime)

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47124)* status: Some of the checks are too old. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java` line 595 at r1](https://reviewable.io/reviews/harness/harness-core/47124#-NU71X8V9WU1TTnIPBT4:-NUQVR9L706ZqYQx3ZG2:b-scxkzv) ([raw file](https://github.com/harness/harness-core/blob/b158bcdd1a42de7ce73ba90380fc3b8ea52d5593/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L595)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

What would be a use case of null group, is that a valid scenario?
</blockquote></details>

Only use case would be when delegateGroupId is not present in delegate object but I don't think that will happen, removing this condition.



_Code quote:_
```Java
  long upgraderLastUpdated = delegateGroup != null ? delegateGroup.getUpgraderLastUpdated() : 0;
```

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47124)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java` line 605 at r1](https://reviewable.io/reviews/harness/harness-core/47124#-NU7-KY94XXKlcom-HbD:-NUVkvZTDIh9D_I3eim2:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b158bcdd1a42de7ce73ba90380fc3b8ea52d5593/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L605)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

No need for atomic here. You could also count it after you've collected (e.g. like lastHeartbeat or delegateCreationTime)
</blockquote></details>

done

**Comment by AnupamIO** [comment]
trigger uts

**Comment by AnupamIO** [comment]
trigger uts

**Comment by AnupamIO** [comment]
trigger ut9

**Comment by AnupamIO** [comment]
trigger uts

**Review by mdmilic — APPROVED** [review]
> Reviewed 4 of 4 files at r3, 1 of 1 files at r4, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47124)* status: 1 file(s) to review.

**Pull request merged**
