### PR TITLE
feat: [CDS-36394]: publish template references to redis topic

### PR DESCRIPTION
**Pull request by inderschera**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32351)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32351)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java, line 180 at r1](https://reviewable.io/reviews/harness/harness-core/32351#-N059O2d9d8KhMtntrle:-N059O2d9d8KhMtntrlf:b-7g7xy7) ([raw file](https://github.com/harness/harness-core/blob/b378dd2f4bd0ff292c1f2b60f5ee2612b20a59de/840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java#L180)):*
> ```Java
>     List<EntitySetupUsageDTO> referredUsagesInTemplate = templateSetupUsageHelper.getReferencesOfTemplate(
>         templateIdentifierRef.getAccountIdentifier(), templateIdentifierRef.getOrgIdentifier(),
>         templateIdentifierRef.getProjectIdentifier(), templateIdentifierRef.getIdentifier(), versionLabel);
> ```

check with product whether its okay to check rbac for entities which are not in stable anymore 



_Code quote:_
```Java
    List<EntitySetupUsageDTO> referredUsagesInTemplate = templateSetupUsageHelper.getReferencesOfTemplate(

        templateIdentifierRef.getAccountIdentifier(), templateIdentifierRef.getOrgIdentifier(),
        templateIdentifierRef.getProjectIdentifier(), templateIdentifierRef.getIdentifier(), versionLabel);
```

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32351)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java, line 180 at r1](https://reviewable.io/reviews/harness/harness-core/32351#-N059O2d9d8KhMtntrle:-N0AQOCK5KJFYJzPwDK3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b378dd2f4bd0ff292c1f2b60f5ee2612b20a59de/840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java#L180)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

check with product whether its okay to check rbac for entities which are not in stable anymore 
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32351)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32351)* status: :shipit: complete! ✓

**Pull request merged**
