### PR TITLE
[feat]: [SRM-13141]: added new common HealthSourceSpec

### PR DESCRIPTION
**Pull request by n00bitax**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41548)

### CODE REVIEW

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41548)* status: 17 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/MonitoredServiceDataSourceType.java` line 31 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOV5g-5KIlQC3g84AP:-NJOV5g-5KIlQC3g84AQ:bn6kg1y) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/MonitoredServiceDataSourceType.java#L31)):*
> ```Java
>   @JsonProperty("CloudWatchMetrics") CLOUDWATCH_METRICS,
>   @JsonProperty("AwsPrometheus") AWS_PROMETHEUS,
>   @JsonProperty("NextGenHealthSource") NEXT_GEN_HEALTH_SOURCE;
> ```

We cannot make  this generic. This is how we get the type of HealthSource from the yaml.
___
*[`430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/MonitoredServiceDataSourceType.java` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOUeQm-sQYh2ax8oYu:-NJOUeQm-sQYh2ax8oYv:b6rj2t8) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/MonitoredServiceDataSourceType.java#L34)):*
> ```Java
>   public static final Map<DataSourceType, MonitoredServiceDataSourceType>
>       dataSourceTypeMonitoredServiceDataSourceTypeMap = new HashMap<>();
>   static {
> ```

nit: why do we have to change this?
If we are changing it isn't better top put it in the contructor of DataSourceType, so that we force them to add it if they add a new DataSourceType.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceParams.java` line 14 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOXgq958EzuOp4ZdMj:-NJOXgq958EzuOp4ZdMk:b-mc3cdj) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceParams.java#L14)):*
> ```Java
> @Data
> public class HealthSourceParams {
>   // TODO remove whats not required.
> ```

remove TODO.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java` line 52 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOYVeaEnufBtHeKN-e:-NJOYVeaEnufBtHeKN-f:b-dzf3zi) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java#L52)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> public class NextGenHealthSourceSpec extends MetricHealthSourceSpec {
>   DataSourceType dataSourceType;
> ```

We need to keep it in top level only. Lets not add type at spec level.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java` line 66 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOZEZ04NAfUqS68fsr:-NJOZEZ04NAfUqS68fss:bvsfzss) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java#L66)):*
> ```Java
>     String queryName;
>     String groupName;
>     CVMonitoringCategory category;
> ```

Lets not add CVMonitoringCategory to key.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java` line 133 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOZjJjAEp3Yo1J8tT6:-NJOZjJjAEp3Yo1J8tT7:b2redyd) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java#L133)):*
> ```Java
>           StringUtils.isNotBlank(query.getIdentifier()), "Query identifier does not match the expected pattern.");
>       if (uniqueQueryNames.contains(query.getName())) {
>         throw new InvalidRequestException(String.format("Duplicate query name present %s", query.getName()));
> ```

Use @UniqueIdentifierCheck for this.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java` line 144 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOZvRH7h7MLMluYjQa:-NJOZvRH7h7MLMluYjQb:b-1m6me8) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java#L144)):*
> ```Java
>         Preconditions.checkArgument(
>             StringUtils.isNotBlank(query.getGroupName()), "GroupName must be present for metrics");
>         Preconditions.checkArgument(!(Objects.nonNull(query.getContinuousVerification())
> ```

nit: we need to think about better approach to validate the fields as New HealthSources gets added to this structure.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java` line 157 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOaVDs-l_aKNMMalP3:-NJOaVDt4PyQN-bIpvSW:b-v7avet) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java#L157)):*
> ```Java
>   }
> 
>   private Map<Key, CVConfig> getCurrentCVConfigMap(String accountId, String orgIdentifier, String projectIdentifier,
> ```

Move this into a factory of transformers (For Logs and Metrics). 
Why do we need this special transformations for each HealthSourceType ? Lets have a generic transformation for all metric providers.  The code will get too dirty too soon, as we add more healthSources.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java` line 188 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOauw47gaDIB79N8nx:-NJOauw47gaDIB79N8ny:b-xzh7gs) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java#L188)):*
> ```Java
>                                                                 .monitoringSourceName(name)
>                                                                 .build();
>           sumologicMetricCVConfig.populateFromQueryDefinitions(metricDefinitionGroup, CVMonitoringCategory.ERRORS);
> ```

Why do we need this special transformations for each HealthSourceType ? Lets have a generic transformation for all. 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/monitoredService/SumologicMetricSourceSpecTransformer.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJObyc1-LdDqq_0rdDl:-NJObyc1-LdDqq_0rdDm:b6fl8q2) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/monitoredService/SumologicMetricSourceSpecTransformer.java#L27)):*
> ```Java
>   // TODO fix it.
>   @Override
>   public NextGenHealthSourceSpec transformToHealthSourceConfig(List<SumologicMetricCVConfig> cvConfigs) {
> ```

If we have generic HealthSourceSpec, why do we need specific CVConfig. Isn't it just extra effort for new onboarding?



_Code quote:_
```Java
SumologicMetricCVConfig
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryDefinition.java` line 20 at r5](https://reviewable.io/reviews/harness/harness-core/41548#-NJOY2Wt7YG8JAcIx-XZ:-NJOY2Wt7YG8JAcIx-X_:b-vqm47a) ([raw file](https://github.com/harness/harness-core/blob/178ce5fae80d4465793f69a2c7a9eafb0f7c8f3e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryDefinition.java#L20)):*
> ```Java
> @Data
> @Builder
> public class QueryDefinition {
> ```

implements WithIdentifier
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryDefinition.java` line 25 at r5](https://reviewable.io/reviews/harness/harness-core/41548#-NJO_JDVDfxJ55Toj_gd:-NJO_JDVDfxJ55Toj_ge:b-dabifr) ([raw file](https://github.com/harness/harness-core/blob/178ce5fae80d4465793f69a2c7a9eafb0f7c8f3e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryDefinition.java#L25)):*
> ```Java
>   String groupName;
>   QueryParams queryParams;
>   Boolean liveMonitoring;
> ```

Make it more specific, "liveMonitoringEnabled". And 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryDefinition.java` line 29 at r5](https://reviewable.io/reviews/harness/harness-core/41548#-NJOY8gZ7XhCE5tuVAE2:-NJOY8gZ7XhCE5tuVAE3:b-8ps83p) ([raw file](https://github.com/harness/harness-core/blob/178ce5fae80d4465793f69a2c7a9eafb0f7c8f3e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryDefinition.java#L29)):*
> ```Java
>   Boolean sli;
>   String query;
>   List<TimeSeriesMetricPackDTO.MetricThreshold> metricThresholds = new ArrayList<>();
> ```

Move MetricThreshold outside of TimeSeriesMetricPackDTO.

**Review by n00bitax — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41548)* status: 29 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java` line 66 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOZEZ04NAfUqS68fsr:-NJPbKKHDMCE36hvrEsL:b-7zkkbz) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java#L66)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Lets not add CVMonitoringCategory to key.
</blockquote></details>

as discussed it needs to be there for now.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java` line 133 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOZjJjAEp3Yo1J8tT6:-NJPbI46CEkhlVZDyfUA:bggxwwq) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java#L133)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Use @UniqueIdentifierCheck for this.
</blockquote></details>

added the check.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java` line 188 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOauw47gaDIB79N8nx:-NJPbC9S4rA9C3a8SUQq:b-j53k23) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java#L188)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Why do we need this special transformations for each HealthSourceType ? Lets have a generic transformation for all. 
</blockquote></details>

changed to 1 transformer for metric and log each
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryDefinition.java` line 20 at r5](https://reviewable.io/reviews/harness/harness-core/41548#-NJOY2Wt7YG8JAcIx-XZ:-NJPbcNR9kR3diEFPeem:b-n4fiqv) ([raw file](https://github.com/harness/harness-core/blob/178ce5fae80d4465793f69a2c7a9eafb0f7c8f3e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryDefinition.java#L20)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

implements WithIdentifier
</blockquote></details>

implements the withIdentifier noq
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryDefinition.java` line 25 at r5](https://reviewable.io/reviews/harness/harness-core/41548#-NJO_JDVDfxJ55Toj_gd:-NJPbRQY0S8vOyl1zA4g:b4gq0o6) ([raw file](https://github.com/harness/harness-core/blob/178ce5fae80d4465793f69a2c7a9eafb0f7c8f3e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryDefinition.java#L25)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Make it more specific, "liveMonitoringEnabled". And 
</blockquote></details>

suffixed all there fields with enabled.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/monitoredService/SumologicMetricSourceSpecTransformer.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJObyc1-LdDqq_0rdDl:-NJPb2PI36oW7d5Fuuqk:bfmtr2r) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/monitoredService/SumologicMetricSourceSpecTransformer.java#L27)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

If we have generic HealthSourceSpec, why do we need specific CVConfig. Isn't it just extra effort for new onboarding?
</blockquote></details>

made generic NextGenMetricCVConfig



_Code quote (from srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/monitoredService/NextGenMetricSourceSpecTransformer.java):_
```Java
NextGenMetricCVConfig
```

**Review by n00bitax — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41548)* status: 30 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceParams.java` line 14 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOXgq958EzuOp4ZdMj:-NJcLMH41wr-hoVesfnW:b-gsn9ur) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceParams.java#L14)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

remove TODO.
</blockquote></details>

there are 5 TODO will clean all of them in next PR.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java` line 157 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOaVDs-l_aKNMMalP3:-NJcJQ15DB0V09WyGpSN:bu9lhir) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java#L157)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Move this into a factory of transformers (For Logs and Metrics). 
Why do we need this special transformations for each HealthSourceType ? Lets have a generic transformation for all metric providers.  The code will get too dirty too soon, as we add more healthSources.
</blockquote></details>

Implemented Generic transformer for logs and metrics

**Review by n00bitax — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41548)* status: 30 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/MonitoredServiceDataSourceType.java` line 31 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOV5g-5KIlQC3g84AP:-NJcRLkRClhd0_dkVmO1:b-bzmlh2) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/MonitoredServiceDataSourceType.java#L31)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

We cannot make  this generic. This is how we get the type of HealthSource from the yaml.
</blockquote></details>

we cannot map multiple types to same class, https://github.com/FasterXML/jackson-databind/issues/312 will require us to write our own serde. vastly expands scope of PR moved to next one.
___
*[`430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/MonitoredServiceDataSourceType.java` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOUeQm-sQYh2ax8oYu:-NJcR_K53AgiXA5OgeAu:b-wi6jif) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/MonitoredServiceDataSourceType.java#L34)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

nit: why do we have to change this?
If we are changing it isn't better top put it in the contructor of DataSourceType, so that we force them to add it if they add a new DataSourceType.
</blockquote></details>

double {{}} is a bug level code smell, will requires changes in delegate common beans moved to next PR.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java` line 52 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOYVeaEnufBtHeKN-e:-NJcS7kSB-YzjdYTBcM4:b-rh5te9) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java#L52)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

We need to keep it in top level only. Lets not add type at spec level.
</blockquote></details>

we need to know the type, so maybe we will have to figure out a way to populate it.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java` line 144 at r4](https://reviewable.io/reviews/harness/harness-core/41548#-NJOZvRH7h7MLMluYjQa:-NJcRq3I3k8NnaxVXqfs:b38npvm) ([raw file](https://github.com/harness/harness-core/blob/91669a7210d13c9cabc42ac9b1ce2c5379775d25/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java#L144)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

nit: we need to think about better approach to validate the fields as New HealthSources gets added to this structure.
</blockquote></details>

will add a new validator class to keep this class compact.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryDefinition.java` line 29 at r5](https://reviewable.io/reviews/harness/harness-core/41548#-NJOY8gZ7XhCE5tuVAE2:-NJcSLizD0k5AavVz72H:bcb8wyx) ([raw file](https://github.com/harness/harness-core/blob/178ce5fae80d4465793f69a2c7a9eafb0f7c8f3e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryDefinition.java#L29)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Move MetricThreshold outside of TimeSeriesMetricPackDTO.
</blockquote></details>

touches a lot of existing classed , moved the refactoring to next PR>

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 3 of 18 files at r1, 3 of 11 files at r8, 4 of 19 files at r10, 3 of 13 files at r13, 1 of 2 files at r14, 4 of 7 files at r16, 5 of 7 files at r17, 2 of 6 files at r18, 1 of 2 files at r20, 1 of 2 files at r22, 1 of 1 files at r25, 3 of 3 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41548)* status: :shipit: complete! ✓

**Pull request merged**
