### PR TITLE
[feat]: [PL-29184]: Kryo Fix to use setReference=false

### PR DESCRIPTION
**Pull request by piyush-harness**
## Describe your changes

https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21210564281/Kryo+Serialisation+Final+Approach

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39202)

### CODE REVIEW

**Comment by piyush-harness** [comment]
trigger messagecheck

**Comment by piyush-harness** [comment]
trigger ti1

**Comment by piyush-harness** [comment]
trigger codeformat

**Comment by piyush-harness** [comment]
trigger ti0,ti1,ti2,ti3,ti3,ti4

**Comment by piyush-harness** [comment]
trigger ti0,ti1,ti2

**Comment by piyush-harness** [comment]
trigger ti3,ti4

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/app/DelegateQueueTask.java` line 176 at r5](https://reviewable.io/reviews/harness/harness-core/39202#-NFzl-QNADxpCCioNcPY:-NFzl-QNADxpCCioNcPZ:bfhqwr4) ([raw file](https://github.com/harness/harness-core/blob/8c5d76e2d9d3670f63402ddac2f609c5e22f4ff7/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L176)):*
> ```Java
>   }
> 
>   private void rebroadcastDelegateTaskUsingTaskData(DelegateTask delegateTask) {
> ```

why do we need these two methods? at this point the task is already deserailized.

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 324 at r5](https://reviewable.io/reviews/harness/harness-core/39202#-NFzlLXO6kLbSqdPTRZo:-NFzlLXO6kLbSqdPTRZp:b-pejcbq) ([raw file](https://github.com/harness/harness-core/blob/8c5d76e2d9d3670f63402ddac2f609c5e22f4ff7/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L324)):*
> ```Java
>   }
> 
>   private boolean canAssignDelegateScopesV2(Delegate delegate, DelegateTask task) {
> ```

why we need to duplicate these? isn't the task already deserialized here?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskBroadcastHelper.java` line 51 at r5](https://reviewable.io/reviews/harness/harness-core/39202#-NFzlTxY6Nr2ckRwvKFG:-NFzlTxY6Nr2ckRwvKFH:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/8c5d76e2d9d3670f63402ddac2f609c5e22f4ff7/400-rest/src/main/java/software/wings/service/impl/DelegateTaskBroadcastHelper.java#L51)):*
> ```Java
>   }
> 
>   public void broadcastNewDelegateTaskAsyncV2(DelegateTask task) {
> ```

same here

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 502 at r5](https://reviewable.io/reviews/harness/harness-core/39202#-NFzltpa-2P-F2I7skvH:-NFzltpa-2P-F2I7skvI:b-ojyaqk) ([raw file](https://github.com/harness/harness-core/blob/8c5d76e2d9d3670f63402ddac2f609c5e22f4ff7/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L502)):*
> ```Java
> 
>   @Override
>   public void scheduleSyncTaskV2(DelegateTask task) {
> ```

i don't think we need to duplicate each method. Just the one which does final processing we should replicate

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/metrics/impl/DelegateMetricsServiceImpl.java` line 82 at r5](https://reviewable.io/reviews/harness/harness-core/39202#-NFzm6biAGa9qaBtGnYc:-NFzm6biAGa9qaBtGnYd:b-ljwkrv) ([raw file](https://github.com/harness/harness-core/blob/8c5d76e2d9d3670f63402ddac2f609c5e22f4ff7/420-delegate-service/src/main/java/io/harness/metrics/impl/DelegateMetricsServiceImpl.java#L82)):*
> ```Java
>       metricService.incCounter(metricName);
>     }
>     if (task.getTaskDataV2() != null) {
> ```

instead of writing if else, just get the taskType based on null check and just call metricService.incCounter

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 10 of 21 files at r1, 4 of 10 files at r2, 18 of 23 files at r3, 4 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39202)* status: 38 file(s) to review. 0 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 324 at r5](https://reviewable.io/reviews/harness/harness-core/39202#-NFzlLXO6kLbSqdPTRZo:-NG-p9pb0s3afs-tDz3-:b-iuv79k) ([raw file](https://github.com/harness/harness-core/blob/8c5d76e2d9d3670f63402ddac2f609c5e22f4ff7/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L324)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why we need to duplicate these? isn't the task already deserialized here?
</blockquote></details>

Previous Method works on TaskData , To avoid complex if-else flows I have created new methods so that we can remove these methods easily once they are not being called from anywhere.

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskBroadcastHelper.java` line 51 at r5](https://reviewable.io/reviews/harness/harness-core/39202#-NFzlTxY6Nr2ckRwvKFG:-NG-rtu8DEFAZL677fV1:b-x15wa) ([raw file](https://github.com/harness/harness-core/blob/8c5d76e2d9d3670f63402ddac2f609c5e22f4ff7/400-rest/src/main/java/software/wings/service/impl/DelegateTaskBroadcastHelper.java#L51)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Same reason as above  to keep the new flow clean and avoid cognitive complexity

**Comment by piyush-harness** [comment]
trigger ti0

**Comment by piyush-harness** [comment]
trigger ti1,ti2

**Review by piyush-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39202)* status: 40 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 502 at r5](https://reviewable.io/reviews/harness/harness-core/39202#-NFzltpa-2P-F2I7skvH:-NG1CxVyC1zEPHjB0WXZ:bg3h4mp) ([raw file](https://github.com/harness/harness-core/blob/8c5d76e2d9d3670f63402ddac2f609c5e22f4ff7/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L502)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

i don't think we need to duplicate each method. Just the one which does final processing we should replicate 
</blockquote></details>

For clean implementation and refactoring, else we will be adding if else check everywhere to whether we process TaskData or TaskDatav2 and increase cognitive complexity. I have duplicated methods where we are using TaskData and replaced its usage with TaskDataV2 .
___
*[`420-delegate-service/src/main/java/io/harness/metrics/impl/DelegateMetricsServiceImpl.java` line 82 at r5](https://reviewable.io/reviews/harness/harness-core/39202#-NFzm6biAGa9qaBtGnYc:-NG1DVhp4SlX7_hW7nYu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8c5d76e2d9d3670f63402ddac2f609c5e22f4ff7/420-delegate-service/src/main/java/io/harness/metrics/impl/DelegateMetricsServiceImpl.java#L82)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

instead of writing if else, just get the taskType based on null check and just call metricService.incCounter
</blockquote></details>

Done.

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, 2 of 4 files at r7, 3 of 6 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39202)* status: 41 file(s) to review. 0 of 2 approvals obtained.

**Review by raghuAtWings — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39202#-:-NGKv7UMBDVkcBAjXywK:bnfp4nl)* status: 41 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
trigger codebasehashcheck

**Comment by piyush-harness** [comment]
trigger codebasehash

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 10 of 21 files at r1, 4 of 10 files at r2, 12 of 23 files at r3, 4 of 4 files at r4, 1 of 2 files at r6, 2 of 4 files at r7, 3 of 6 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39202)* status: :shipit: complete! ✓

**Pull request merged**
