### PR TITLE
[feat]: [CDC-38696]: FileStore client

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34675)

### CODE REVIEW

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 4 of 21 files at r1, 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34675)* status: :shipit: complete! ✓

**Comment by diptiman-adak** [comment]
@vladimir-peric I have just checked the bazel part. Please get the java code reviewed by someone

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 21 files at r1, 11 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34675)* status: :shipit: complete! ✓

___
*[`877-filestore/src/main/java/io/harness/filestore/resource/FileStoreResource.java` line 192 at r2](https://reviewable.io/reviews/harness/harness-core/34675#-N5Z69xf4BgJ_0tNu0PE:-N5Z69xf4BgJ_0tNu0PF:b-eky5en) ([raw file](https://github.com/harness/harness-core/blob/71f919766b3fadcf55b36126777f4f1502e62fcf/877-filestore/src/main/java/io/harness/filestore/resource/FileStoreResource.java#L192)):*
> ```Java
>       })
>   public Response
>   downloadFile(@Parameter(description = FILE_PARAM_MESSAGE) @PathParam(
> ```

Minor - usually we put item identifier after scope identifiers
___
*[`941-filestore-client/src/main/java/io/harness/filestoreclient/remote/FileStoreNgClient.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/34675#-N5Z8QQl1UBxa-LMw81d:-N5Z8QQl1UBxa-LMw81e:bo3y0j8) ([raw file](https://github.com/harness/harness-core/blob/71f919766b3fadcf55b36126777f4f1502e62fcf/941-filestore-client/src/main/java/io/harness/filestoreclient/remote/FileStoreNgClient.java#L22)):*
> ```Java
> 
> @OwnedBy(CDP)
> public interface FileStoreNgClient {
> ```

Just rename this to FileStoreClient. Why, because if we have FileStoreClient in 930-ng-core-clients and FileStoreNGClient in the new module with different names, it will be the same clients with different names but it is the same client. We can give the same name because 930-ng-core-clients and the new module will not be included together.

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34675#-:-N5ZnS-f1Hz0IVHRWQAl:bnfp4nl)* status: :shipit: complete! ✓

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 8 of 9 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34675)* status: :shipit: complete! ✓

**Pull request merged**
