### PR TITLE
[feat]: [CDS-74025]: Sleep the consumer poller-thread only when not enough entries to poll

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Sleep the consumer poller-thread only when not enough entries to poll. so when there is not much load on the system then we will sleep the thread so it does not make unnecessary calls to redis. and when there is high load on the system then poller will keep reading the events until there are enough events in the redis.

Testing: tested in a scale test that it improves the performance during the high load. and when the load is low it does sleep the thread. unit-test also tested this behaviour.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50685)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50685)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java` line 110 at r1](https://reviewable.io/reviews/harness/harness-core/50685#-N_cb3ha-ICeBO2nO8qi:-N_cb3ha-ICeBO2nO8qj:buz9h0o) ([raw file](https://github.com/harness/harness-core/blob/e67c54b03a5a03a19554ac7244b1de2da38630bb/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java#L110)):*
> ```Java
>       }
>     }
>     if (messages.size() < ((RedisAbstractConsumer) this.redisConsumer).getBatchSize()) {
> ```

nit we should change the consumer here to Redis consumer altogether and remove this cast, add a TODO for now. 

Also please verify if this is always true, there is a NOOP consumer which get init in case of dummyRedisUrl 
___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/50685#-N_c_fsyAVPCgcGht006:-N_c_fsyAVPCgcGht007:b-s8v3lc) ([raw file](https://github.com/harness/harness-core/blob/e67c54b03a5a03a19554ac7244b1de2da38630bb/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java#L112)):*
> ```Java
>     if (messages.size() < ((RedisAbstractConsumer) this.redisConsumer).getBatchSize()) {
>       // Adding thread sleep when the events read are less than the batch-size. This way when the load is high, consumer
>       // will query the events quickly. And in case of low load, thread will sleep for some time.
> ```

add a log here to debug at least in the first release

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50685)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java` line 110 at r1](https://reviewable.io/reviews/harness/harness-core/50685#-N_cb3ha-ICeBO2nO8qi:-N_ctmyQDmP7RYfg6rKV:b-jl8rtf) ([raw file](https://github.com/harness/harness-core/blob/e67c54b03a5a03a19554ac7244b1de2da38630bb/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java#L110)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

nit we should change the consumer here to Redis consumer altogether and remove this cast, add a TODO for now. 

Also please verify if this is always true, there is a NOOP consumer which get init in case of dummyRedisUrl 
</blockquote></details>

Have made the noop-redisConsumer to extend the abstractRedisConsumer for testing the sleep logic via ut. so its always true. 
___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/50685#-N_c_fsyAVPCgcGht006:-N_ceV7_E25CJljIGtJo:b-cyul7j) ([raw file](https://github.com/harness/harness-core/blob/e67c54b03a5a03a19554ac7244b1de2da38630bb/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java#L112)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

add a log here to debug at least in the first release
</blockquote></details>

Sure. will add logs when the sleep is not happening means when the load is high. If we add logs for case when there is less load then it would be too many logs. 5 logs per second per consumer.

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50685)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/50685#-N_c_fsyAVPCgcGht006:-N_cvNYk5A0I0DNJp3HA:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e67c54b03a5a03a19554ac7244b1de2da38630bb/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java#L112)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Sure. will add logs when the sleep is not happening means when the load is high. If we add logs for case when there is less load then it would be too many logs. 5 logs per second per consumer.
</blockquote></details>

Done

**Review by abhinav-harness — DISMISSED** [review]

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50685)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/50685#-N_c_fsyAVPCgcGht006:-NaGR1f5CBohrLaGFsgM:bntm8s) ([raw file](https://github.com/harness/harness-core/blob/e67c54b03a5a03a19554ac7244b1de2da38630bb/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java#L112)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Done
</blockquote></details>

@hextechpal should we make this log line as debug, as too many logs would be there?

**Review by hextechpal — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50685)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/50685#-N_c_fsyAVPCgcGht006:-NaHAuVGATVPEtNPRBLO:b-63le53) ([raw file](https://github.com/harness/harness-core/blob/e67c54b03a5a03a19554ac7244b1de2da38630bb/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java#L112)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@hextechpal should we make this log line as debug, as too many logs would be there?
</blockquote></details>

Ideally, a lot of logs will come when there is no load, we should make this sleep backoff too but for now, we can convert this to debug, but its as good as no log :)

**Comment by brijeshdhakar** [comment]
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/50685#-N_c_fsyAVPCgcGht006:-NaHHTbeDmHz0oMO6eRM:baij9bn) ([raw file](https://github.com/harness/harness-core/blob/e67c54b03a5a03a19554ac7244b1de2da38630bb/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java#L112)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

I put the log when there is high load because generally we don't have much load on system in PROD. So logs will not come. Logs will come only when we do perf test. I was planning to remove this log line in next release once we confirm that the change works fine.
So we should be good if we can remove this log line. Let me know what you think.
</blockquote></details>

And the log frequency will be once per batch. So i don't think its too much logs.

**Comment by brijeshdhakar** [comment]
trigger checkstylecodeformat

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50685)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]

**Pull request merged**
