### PR TITLE
feat: [CDS-41966]: adding migrations to elastic search sync

### PR DESCRIPTION
**Pull request by prabu-kr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36726)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36726)

**Review by abhinavmittal-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36726)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java` line 246 at r3](https://reviewable.io/reviews/harness/harness-core/36726#-NAOgdtpAcHMNb1NbfTn:-NAOgdtpAcHMNb1NbfTo:bjr010u) ([raw file](https://github.com/harness/harness-core/blob/1324c07d1010a97379142380ecda0ac9d4485733/400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java#L246)):*
> ```Java
>       if (workflowExecutionEntityIndexState == null) {
>         runDeploymentMigrations(accountIds);
>         TimeScaleEntityIndexState execution_entity = new TimeScaleEntityIndexState(
> ```

Handle the embold changes

class Demo {
    //Non-compliant code
    //ExecutorService is not closed anywhere
    public void process1() {
        ExecutorService executorService =  
                    Executors.newSingleThreadExecutor();
        executorService.execute(new Runnable() {
         @Override
         public void run() {
             try {
                 doTask();
                } catch (Exception e) {
                 logger.error("indexing failed", e);
             }
         }
        });
    }
            
    //Compliant code
    public  void process2() {
        ExecutorService executorService =  
                    Executors.newSingleThreadExecutor();
        executorService.execute(new Runnable() {
        @Override
        public void run() {
            try {
                doTask();
            } catch (Exception e) {
                 logger.error("indexing failed", e);
                }
            }
        });
        executorService.shutdown();      
    }      
    }
___
*[`400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java` line 271 at r3](https://reviewable.io/reviews/harness/harness-core/36726#-NAOghtl83HdCh0k20Kx:-NAOghtl83HdCh0k20Ky:bx7uzk1) ([raw file](https://github.com/harness/harness-core/blob/1324c07d1010a97379142380ecda0ac9d4485733/400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java#L271)):*
> ```Java
>   private void runDeploymentMigrations(List<String> accountIds) {
>     deploymentsMigrationHelper.setFailureDetailsForAccountIds(
>         accountIds, "EXECUTION_FAILURE_TIMESCALE MIGRATION: ", 500, EXECUTION_FAILURE_UPDATE_STATEMENT);
> ```

Make this to 100

**Comment by abhinavmittal-harness** [comment]
*[`400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java` line 250 at r3](https://reviewable.io/reviews/harness/harness-core/36726#-NAOhwM6Elrd_4n6mwia:-NAOhwM6Elrd_4n6mwib:b-tbyxzx) ([raw file](https://github.com/harness/harness-core/blob/1324c07d1010a97379142380ecda0ac9d4485733/400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java#L250)):*
> ```Java
>         wingsPersistence.save(execution_entity);
>       } else {
>         List<String> toMigrateAccountIds = workflowExecutionEntityIndexState.getToMigrateAccountIds() != null
> ```

Make this as if Empty or null

**Comment by abhinavmittal-harness** [comment]
*[`400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java` line 257 at r3](https://reviewable.io/reviews/harness/harness-core/36726#-NAOiAyR0_IMCxJA9ZcM:-NAOiAyR0_IMCxJA9ZcN:bcsezda) ([raw file](https://github.com/harness/harness-core/blob/1324c07d1010a97379142380ecda0ac9d4485733/400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java#L257)):*
> ```Java
>             ? workflowExecutionEntityIndexState.getAlreadyMigratedAccountIds()
>             : new LinkedList<>();
>         runDeploymentMigrations(toMigrateAccountIds);
> ```

you need to remove the already migrated accountIds from the existing list

**Review by abhinavmittal-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36726)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java` line 258 at r3](https://reviewable.io/reviews/harness/harness-core/36726#-NAOibeN0sNtWi1sn-_r:-NAOibeN0sNtWi1sn-_s:b-oxn0kq) ([raw file](https://github.com/harness/harness-core/blob/1324c07d1010a97379142380ecda0ac9d4485733/400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java#L258)):*
> ```Java
>             : new LinkedList<>();
>         runDeploymentMigrations(toMigrateAccountIds);
>         alreadyMigratedAccountIds.addAll(toMigrateAccountIds);
> ```

you need to remove the already migrated accountIds from the toMigrateAccountIds
___
*[`400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java` line 261 at r3](https://reviewable.io/reviews/harness/harness-core/36726#-NAOit2M4Z1RXioELVzY:-NAOit2M4Z1RXioELVzZ:b-joleqz) ([raw file](https://github.com/harness/harness-core/blob/1324c07d1010a97379142380ecda0ac9d4485733/400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java#L261)):*
> ```Java
>         TimeScaleEntityIndexState execution_entity =
>             new TimeScaleEntityIndexState(WorkflowExecution.class.getCanonicalName(), System.currentTimeMillis(),
>                 alreadyMigratedAccountIds, toMigrateAccountIds);
> ```

new ArrayList<>()

**Review by prabu-kr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36726)* status: 6 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java` line 246 at r3](https://reviewable.io/reviews/harness/harness-core/36726#-NAOgdtpAcHMNb1NbfTn:-NAwvZRbAuJatlO8kMKl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1324c07d1010a97379142380ecda0ac9d4485733/400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java#L246)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Handle the embold changes

class Demo {
    //Non-compliant code
    //ExecutorService is not closed anywhere
    public void process1() {
        ExecutorService executorService =  
                    Executors.newSingleThreadExecutor();
        executorService.execute(new Runnable() {
         @Override
         public void run() {
             try {
                 doTask();
                } catch (Exception e) {
                 logger.error("indexing failed", e);
             }
         }
        });
    }
            
    //Compliant code
    public  void process2() {
        ExecutorService executorService =  
                    Executors.newSingleThreadExecutor();
        executorService.execute(new Runnable() {
        @Override
        public void run() {
            try {
                doTask();
            } catch (Exception e) {
                 logger.error("indexing failed", e);
                }
            }
        });
        executorService.shutdown();      
    }      
    }
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java` line 250 at r3](https://reviewable.io/reviews/harness/harness-core/36726#-NAOhwM6Elrd_4n6mwia:-NAwv_AB3hQjSI3ziS5h:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1324c07d1010a97379142380ecda0ac9d4485733/400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java#L250)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Make this as if Empty or null
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java` line 258 at r3](https://reviewable.io/reviews/harness/harness-core/36726#-NAOibeN0sNtWi1sn-_r:-NAwv_yz7Lvv2uPDUkHb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1324c07d1010a97379142380ecda0ac9d4485733/400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java#L258)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

you need to remove the already migrated accountIds from the toMigrateAccountIds
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java` line 261 at r3](https://reviewable.io/reviews/harness/harness-core/36726#-NAOit2M4Z1RXioELVzY:-NAwvaM69B6AEl33_DpH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1324c07d1010a97379142380ecda0ac9d4485733/400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java#L261)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

new ArrayList<>()
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java` line 271 at r3](https://reviewable.io/reviews/harness/harness-core/36726#-NAOghtl83HdCh0k20Kx:-NAwvb5E58EUnXqw9cjy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1324c07d1010a97379142380ecda0ac9d4485733/400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java#L271)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Make this to 100
</blockquote></details>

Done.

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by abhinavmittal-harness** [comment]
*[`400-rest/src/main/java/io/harness/dashboard/DashboardSettingsServiceImpl.java` line 237 at r5](https://reviewable.io/reviews/harness/harness-core/36726#-NBpTHQaEO0w2ZDXdDvs:-NBpTHQaEO0w2ZDXdDvt:b7vzp4r) ([raw file](https://github.com/harness/harness-core/blob/d50b8adfc8e4a6432823946ecdc68becdab845e1/400-rest/src/main/java/io/harness/dashboard/DashboardSettingsServiceImpl.java#L237)):*
> ```Java
>       TimeScaleEntityIndexState updated_entity =
>           new TimeScaleEntityIndexState(WorkflowExecution.class.getCanonicalName(), System.currentTimeMillis(),
>               timeScaleEntityIndexState.getAlreadyMigratedAccountIds(), toMigrateAccountIds);
> ```

make alreadyMigratedAccoutnIds to new LinkedList or null

**Comment by abhinavmittal-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/dashboard/CustomDashboardResource.java` line 561 at r5](https://reviewable.io/reviews/harness/harness-core/36726#-NBpTQOv5pAP6ibJkvhm:-NBpTQOv5pAP6ibJkvhn:b-lpxrwq) ([raw file](https://github.com/harness/harness-core/blob/d50b8adfc8e4a6432823946ecdc68becdab845e1/400-rest/src/main/java/software/wings/resources/dashboard/CustomDashboardResource.java#L561)):*
> ```Java
>   @ExceptionMetered
>   @AuthRule(permissionType = LOGGED_IN)
>   public RestResponse addToToMigrateAccountIds(@QueryParam("accountIds") @NotEmpty List<String> accountIds) {
> ```

Does list work as query param

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36726)* status: 3 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained.

**Review by prabu-kr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36726)* status: 3 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/dashboard/DashboardSettingsServiceImpl.java` line 237 at r5](https://reviewable.io/reviews/harness/harness-core/36726#-NBpTHQaEO0w2ZDXdDvs:-NCdICYk-cfNamydEIdG:bmqcljq) ([raw file](https://github.com/harness/harness-core/blob/d50b8adfc8e4a6432823946ecdc68becdab845e1/400-rest/src/main/java/io/harness/dashboard/DashboardSettingsServiceImpl.java#L237)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

make alreadyMigratedAccoutnIds to new LinkedList or null
</blockquote></details>

This is the new api for copy templates. Over here we're reading the current state from db, just adding to ToMigrateAccountIds and then saving it back. Shouldn't we just save what we had in the db already instead of making it as null?
___
*[`400-rest/src/main/java/software/wings/resources/dashboard/CustomDashboardResource.java` line 561 at r5](https://reviewable.io/reviews/harness/harness-core/36726#-NBpTQOv5pAP6ibJkvhm:-NCdI07b2ZF5ejVJQ6KS:b-pt7fxo) ([raw file](https://github.com/harness/harness-core/blob/d50b8adfc8e4a6432823946ecdc68becdab845e1/400-rest/src/main/java/software/wings/resources/dashboard/CustomDashboardResource.java#L561)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Does list work as query param
</blockquote></details>

Have moved it to body instead

**Review by prabu-kr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36726)* status: 3 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/dashboard/DashboardSettingsServiceImpl.java` line 237 at r5](https://reviewable.io/reviews/harness/harness-core/36726#-NBpTHQaEO0w2ZDXdDvs:-NCdJ2fcEiALKIJoR6fM:b8iygwk) ([raw file](https://github.com/harness/harness-core/blob/d50b8adfc8e4a6432823946ecdc68becdab845e1/400-rest/src/main/java/io/harness/dashboard/DashboardSettingsServiceImpl.java#L237)):*
> copy template   Sorry I meant new api for adding accountIds to toMigrate in timeScaleIndexState

**Comment by prabu-kr** [comment]
trigger feature-build

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 1 of 4 files at r4, 1 of 2 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36726)* status: Some of the checks are too old. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained.

**Review by abhinavmittal-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36726)* status: Some of the checks are too old.

**Comment by prabu-kr** [comment]
trigger ft1

**Comment by prabu-kr** [comment]
trigger ft2

**Review by Abhishek-CDC — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36726)* status: Some of the checks are too old. 1 change requests. 

___
*[`400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java` line 256 at r7](https://reviewable.io/reviews/harness/harness-core/36726#-NFO3Zlr4snE9Zqpmjg0:-NFO3Zlr4snE9Zqpmjg1:b-2gxyy8) ([raw file](https://github.com/harness/harness-core/blob/d5fc3e5e12882c395267c7b2eee4cab5c2e21a7a/400-rest/src/main/java/software/wings/search/framework/ElasticsearchBulkSyncTask.java#L256)):*
> ```Java
>             ? workflowExecutionEntityIndexState.getAlreadyMigratedAccountIds()
>             : new LinkedList<>();
>         runDeploymentMigrations(toMigrateAccountIds, alreadyMigratedAccountIds);
> ```

we should remove accountIds that are present in alreadyMigratedAccountIds from toMigrateAccountIds. 
Example: when we have performed migration for all accountIds, toMigrateAccountIds will be empty and by this logic we will add all accountIds again and perform migration.

**Pull request closed without merging**
