### PR TITLE
[feat]: [PIE-5479]: Create and register dummy Rollback Stage node

### PR DESCRIPTION
**Pull request by namanvermah**
Create plan for rollback stage nodes (dummy for now) and register it as the next node for pipeline rollback advisor for all steps. Only handling sequential stages for now. 

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37839)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37839)

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37839)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37839)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37839)* status: :shipit: complete! ✓

**Pull request merged**
