### PR TITLE
fix: [CDC-16637]: move away from boolean filter in deploymentfreeze iterators

### PR DESCRIPTION
**Pull request by inderschera**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30317)

### CODE REVIEW

**Review by prabu-kr — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30317)* status: :shipit: complete! ✓

___
*[400-rest/src/main/java/software/wings/service/impl/compliance/DeploymentFreezeActivationHandler.java, line 86 at r1](https://reviewable.io/reviews/harness/harness-core/30317#-MuVa6V63bA9ijNpg-xP:-MuVa6V63bA9ijNpg-xQ:b-oprmn7) ([raw file](https://github.com/harness/harness-core/blob/249343695ea8ab8a48da6c537c78a2341bf506d0/400-rest/src/main/java/software/wings/service/impl/compliance/DeploymentFreezeActivationHandler.java#L86)):*
> ```Java
>                        .field(GovernanceConfigKeys.nextIterations)
>                        .not()
>                        .sizeEq(0))
> ```

Do we need 'not equal to emptyList' and 'not().sizeEq(0)' separately?

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30317)* status: 1. unresolved discussions. 

___
*[400-rest/src/main/java/software/wings/service/impl/compliance/DeploymentFreezeActivationHandler.java, line 86 at r1](https://reviewable.io/reviews/harness/harness-core/30317#-MuVa6V63bA9ijNpg-xP:-Muj-uWtCAIKOFiwAwNc:b7t9t8h) ([raw file](https://github.com/harness/harness-core/blob/249343695ea8ab8a48da6c537c78a2341bf506d0/400-rest/src/main/java/software/wings/service/impl/compliance/DeploymentFreezeActivationHandler.java#L86)):*
<details><summary><i>Previously, prabu-kr (Prabu Rajendran) wrote…</i></summary><blockquote>

Do we need 'not equal to emptyList' and 'not().sizeEq(0)' separately? 
</blockquote></details>

Yes @prabu-kr 
 Synced with Deepak - this is because Morphia is converting the empty list to null in our query.

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30317)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/compliance/DeploymentFreezeActivationHandler.java, line 86 at r1](https://reviewable.io/reviews/harness/harness-core/30317#-MuVa6V63bA9ijNpg-xP:-Muo7OCx-lWiAKyQkjLD:bq5jgt7) ([raw file](https://github.com/harness/harness-core/blob/95060cb05818ec29b07e5bd128cd8abddf8a6427/400-rest/src/main/java/software/wings/service/impl/compliance/DeploymentFreezeActivationHandler.java#L86)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Yes @prabu-kr 
 Synced with Deepak - this is because Morphia is converting the empty list to null in our query.
</blockquote></details>

I have removed != empty list check since there were 2 != null check coming in query.

**Review by poojaSinghal — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30317)* status: 1. unresolved discussions.

**Review by poojaSinghal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30317)* status: 1. unresolved discussions.

**Pull request merged**
