### PR TITLE
[fix]: [CVNG-4163]: added new flag for filtering of anomalous nodes

### PR DESCRIPTION
**Pull request by kapil-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30207)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger messagecheck

**Comment by kapil-harness** [comment]
@GET API: https://localhost:8181/cv/api/verify-step/OcIay0u2SnWPj3RzJZRArg/deployment-timeseries-data?routingId=kmpySmUISimoRrJL6NL73w&accountId=kmpySmUISimoRrJL6NL73w&anomalousMetricsOnly=true&anomalousNodesOnly=true&pageNumber=0&pageSize=10

Response:
{
    "metaData": {},
    "resource": {
        "pageResponse": {
            "totalPages": 1,
            "totalItems": 3,
            "pageItemCount": 3,
            "pageSize": 10,
            "content": [
                {
                    "transactionMetric": {
                        "transactionName": "/todolist/requestLogin",
                        "metricName": "Calls per Minute",
                        "score": 0.9004,
                        "risk": "UNHEALTHY"
                    },
                    "connectorName": "appd",
                    "dataSourceType": "APP_DYNAMICS",
                    "nodes": [
                        {
                            "hostName": "harness-deployment-canary-7445f86dbf-ml857",
                            "risk": "UNHEALTHY",
                            "score": 0.8004,
                            "controlData": [
                                22.53333333333333,
                                23.133333333333336,
                                23.066666666666666,
                                20.0
                            ],
                            "testData": [
                                190.66666666666666,
                                240.0,
                                210.33333333333334,
                                190.0
                            ],
                            "anomalous": true
                        }
                    ],
                    "nodeRiskCountDTO": {
                        "totalNodeCount": 1,
                        "anomalousNodeCount": 1,
                        "riskCounts": [
                            {
                                "risk": "UNHEALTHY",
                                "count": 1,
                                "displayName": "Unhealthy"
                            }
                        ]
                    }
                },
                {
                    "transactionMetric": {
                        "transactionName": "/todolist/exception",
                        "metricName": "Average Response Time (ms)",
                        "score": 0.8004,
                        "risk": "UNHEALTHY"
                    },
                    "connectorName": "appd",
                    "dataSourceType": "APP_DYNAMICS",
                    "nodes": [
                        {
                            "hostName": "harness-deployment-canary-7445f86dbf-ml857",
                            "risk": "UNHEALTHY",
                            "score": 0.9174,
                            "controlData": [
                                100.9333333333334,
                                78.1999999999999,
                                300.7999999999998,
                                200.0
                            ],
                            "testData": [
                                2105.3333333333335,
                                738.6666666666666,
                                2159.6666666666665,
                                764.0
                            ],
                            "anomalous": true
                        },
                        {
                            "hostName": "harness-deployment-canary-56b5cc7c5b-9rpq7",
                            "risk": "UNHEALTHY",
                            "score": 0.7004,
                            "controlData": [
                                150.9333333333334,
                                85.1999999999999,
                                307.7999999999998,
                                100.0
                            ],
                            "testData": [
                                456.6666666666667,
                                386.6666666666667,
                                466.6666666666667,
                                402.0
                            ],
                            "anomalous": true
                        }
                    ],
                    "nodeRiskCountDTO": {
                        "totalNodeCount": 2,
                        "anomalousNodeCount": 2,
                        "riskCounts": [
                            {
                                "risk": "UNHEALTHY",
                                "count": 2,
                                "displayName": "Unhealthy"
                            }
                        ]
                    }
                },
                {
                    "transactionMetric": {
                        "transactionName": "/todolist/requestLogin",
                        "metricName": "Average Response Time (ms)",
                        "score": 0.7004,
                        "risk": "UNHEALTHY"
                    },
                    "connectorName": "appd",
                    "dataSourceType": "APP_DYNAMICS",
                    "nodes": [
                        {
                            "hostName": "harness-deployment-canary-7445f86dbf-ml857",
                            "risk": "UNHEALTHY",
                            "score": 0.9004,
                            "controlData": [
                                0.8000000000000002,
                                0.7999999999999999,
                                0.8666666666666667,
                                1.0
                            ],
                            "testData": [
                                20.0,
                                23.666666666666668,
                                46.0,
                                100.0
                            ],
                            "anomalous": true
                        }
                    ],
                    "nodeRiskCountDTO": {
                        "totalNodeCount": 1,
                        "anomalousNodeCount": 1,
                        "riskCounts": [
                            {
                                "risk": "UNHEALTHY",
                                "count": 1,
                                "displayName": "Unhealthy"
                            }
                        ]
                    }
                }
            ],
            "pageIndex": 0,
            "empty": false
        },
        "deploymentTimeRange": {
            "startTime": "2022-01-20 17:26:00",
            "endTime": "2022-01-20 17:27:00"
        },
        "deploymentStartTime": 1642699560000,
        "deploymentEndTime": 1642699620000
    },
    "responseMessages": []
}

#################################################

@GET API: https://localhost:8181/cv/api/verify-step/OcIay0u2SnWPj3RzJZRArg/deployment-timeseries-data?routingId=kmpySmUISimoRrJL6NL73w&accountId=kmpySmUISimoRrJL6NL73w&anomalousMetricsOnly=false&anomalousNodesOnly=false&pageNumber=0&pageSize=10

Response:
{
    "metaData": {},
    "resource": {
        "pageResponse": {
            "totalPages": 1,
            "totalItems": 10,
            "pageItemCount": 10,
            "pageSize": 10,
            "content": [
                {
                    "transactionMetric": {
                        "transactionName": "/todolist/requestLogin",
                        "metricName": "Calls per Minute",
                        "score": 0.9004,
                        "risk": "UNHEALTHY"
                    },
                    "connectorName": "appd",
                    "dataSourceType": "APP_DYNAMICS",
                    "nodes": [
                        {
                            "hostName": "harness-deployment-canary-7445f86dbf-ml857",
                            "risk": "UNHEALTHY",
                            "score": 0.8004,
                            "controlData": [
                                22.53333333333333,
                                23.133333333333336,
                                23.066666666666666,
                                20.0
                            ],
                            "testData": [
                                190.66666666666666,
                                240.0,
                                210.33333333333334,
                                190.0
                            ],
                            "anomalous": true
                        },
                        {
                            "hostName": "harness-deployment-canary-56b5cc7c5b-9rpq7",
                            "risk": "HEALTHY",
                            "score": 0.5004,
                            "controlData": [
                                22.53333333333333,
                                23.133333333333336,
                                23.066666666666666,
                                1.0
                            ],
                            "testData": [
                                27.0,
                                28.666666666666668,
                                24.333333333333332,
                                25.0
                            ],
                            "anomalous": false
                        }
                    ],
                    "nodeRiskCountDTO": {
                        "totalNodeCount": 2,
                        "anomalousNodeCount": 1,
                        "riskCounts": [
                            {
                                "risk": "UNHEALTHY",
                                "count": 1,
                                "displayName": "Unhealthy"
                            },
                            {
                                "risk": "HEALTHY",
                                "count": 1,
                                "displayName": "Healthy"
                            }
                        ]
                    }
                },
                {
                    "transactionMetric": {
                        "transactionName": "/todolist/exception",
                        "metricName": "Average Response Time (ms)",
                        "score": 0.8004,
                        "risk": "UNHEALTHY"
                    },
                    "connectorName": "appd",
                    "dataSourceType": "APP_DYNAMICS",
                    "nodes": [
                        {
                            "hostName": "harness-deployment-canary-7445f86dbf-ml857",
                            "risk": "UNHEALTHY",
                            "score": 0.9174,
                            "controlData": [
                                100.9333333333334,
                                78.1999999999999,
                                300.7999999999998,
                                200.0
                            ],
                            "testData": [
                                2105.3333333333335,
                                738.6666666666666,
                                2159.6666666666665,
                                764.0
                            ],
                            "anomalous": true
                        },
                        {
                            "hostName": "harness-deployment-canary-56b5cc7c5b-9rpq7",
                            "risk": "UNHEALTHY",
                            "score": 0.7004,
                            "controlData": [
                                150.9333333333334,
                                85.1999999999999,
                                307.7999999999998,
                                100.0
                            ],
                            "testData": [
                                456.6666666666667,
                                386.6666666666667,
                                466.6666666666667,
                                402.0
                            ],
                            "anomalous": true
                        }
                    ],
                    "nodeRiskCountDTO": {
                        "totalNodeCount": 2,
                        "anomalousNodeCount": 2,
                        "riskCounts": [
                            {
                                "risk": "UNHEALTHY",
                                "count": 2,
                                "displayName": "Unhealthy"
                            }
                        ]
                    }
                },
                {
                    "transactionMetric": {
                        "transactionName": "/todolist/requestLogin",
                        "metricName": "Average Response Time (ms)",
                        "score": 0.7004,
                        "risk": "UNHEALTHY"
                    },
                    "connectorName": "appd",
                    "dataSourceType": "APP_DYNAMICS",
                    "nodes": [
                        {
                            "hostName": "harness-deployment-canary-7445f86dbf-ml857",
                            "risk": "UNHEALTHY",
                            "score": 0.9004,
                            "controlData": [
                                0.8000000000000002,
                                0.7999999999999999,
                                0.8666666666666667,
                                1.0
                            ],
                            "testData": [
                                20.0,
                                23.666666666666668,
                                46.0,
                                100.0
                            ],
                            "anomalous": true
                        },
                        {
                            "hostName": "harness-deployment-canary-56b5cc7c5b-9rpq7",
                            "risk": "HEALTHY",
                            "score": 0.5004,
                            "controlData": [
                                0.8000000000000002,
                                0.7999999999999999,
                                0.8666666666666667,
                                1.0
                            ],
                            "testData": [
                                0.6666666666666666,
                                0.6666666666666666,
                                0.6666666666666666,
                                1.0
                            ],
                            "anomalous": false
                        }
                    ],
                    "nodeRiskCountDTO": {
                        "totalNodeCount": 2,
                        "anomalousNodeCount": 1,
                        "riskCounts": [
                            {
                                "risk": "UNHEALTHY",
                                "count": 1,
                                "displayName": "Unhealthy"
                            },
                            {
                                "risk": "HEALTHY",
                                "count": 1,
                                "displayName": "Healthy"
                            }
                        ]
                    }
                },
                {
                    "transactionMetric": {
                        "transactionName": "/todolist/register",
                        "metricName": "Average Response Time (ms)",
                        "score": 0.5004,
                        "risk": "HEALTHY"
                    },
                    "connectorName": "appd",
                    "dataSourceType": "APP_DYNAMICS",
                    "nodes": [
                        {
                            "hostName": "harness-deployment-canary-7445f86dbf-ml857",
                            "risk": "HEALTHY",
                            "score": 0.5004,
                            "controlData": [
                                0.7999999999999999,
                                1.0,
                                0.8666666666666667,
                                1.0
                            ],
                            "testData": [
                                1.0,
                                0.6666666666666666,
                                1.0,
                                1.0
                            ],
                            "anomalous": false
                        },
                        {
                            "hostName": "harness-deployment-canary-56b5cc7c5b-9rpq7",
                            "risk": "HEALTHY",
                            "score": 0.5004,
                            "controlData": [
                                0.7999999999999999,
                                1.0,
                                0.8666666666666667,
                                1.0
                            ],
                            "testData": [
                                0.6666666666666666,
                                1.0,
                                1.0,
                                1.0
                            ],
                            "anomalous": false
                        }
                    ],
                    "nodeRiskCountDTO": {
                        "totalNodeCount": 2,
                        "anomalousNodeCount": 0,
                        "riskCounts": [
                            {
                                "risk": "HEALTHY",
                                "count": 2,
                                "displayName": "Healthy"
                            }
                        ]
                    }
                },
                {
                    "transactionMetric": {
                        "transactionName": "/todolist/inside",
                        "metricName": "Calls per Minute",
                        "score": 0.5004,
                        "risk": "HEALTHY"
                    },
                    "connectorName": "appd",
                    "dataSourceType": "APP_DYNAMICS",
                    "nodes": [
                        {
                            "hostName": "harness-deployment-canary-7445f86dbf-ml857",
                            "risk": "HEALTHY",
                            "score": 0.5894,
                            "controlData": [
                                126.66666666666667,
                                122.06666666666666,
                                130.26666666666668,
                                140.0
                            ],
                            "testData": [
                                99.66666666666667,
                                145.66666666666666,
                                112.33333333333333,
                                126.0
                            ],
                            "anomalous": false
                        },
                        {
                            "hostName": "harness-deployment-canary-56b5cc7c5b-9rpq7",
                            "risk": "HEALTHY",
                            "score": 0.5004,
                            "controlData": [
                                126.66666666666667,
                                122.06666666666666,
                                130.26666666666668,
                                140.0
                            ],
                            "testData": [
                                141.0,
                                150.66666666666666,
                                141.66666666666666,
                                145.0
                            ],
                            "anomalous": false
                        }
                    ],
                    "nodeRiskCountDTO": {
                        "totalNodeCount": 2,
                        "anomalousNodeCount": 0,
                        "riskCounts": [
                            {
                                "risk": "HEALTHY",
                                "count": 2,
                                "displayName": "Healthy"
                            }
                        ]
                    }
                },
                {
                    "transactionMetric": {
                        "transactionName": "/todolist/inside",
                        "metricName": "Average Response Time (ms)",
                        "score": 0.5004,
                        "risk": "HEALTHY"
                    },
                    "connectorName": "appd",
                    "dataSourceType": "APP_DYNAMICS",
                    "nodes": [
                        {
                            "hostName": "harness-deployment-canary-7445f86dbf-ml857",
                            "risk": "HEALTHY",
                            "score": 0.5004,
                            "controlData": [
                                0.0,
                                0.13333333333333333,
                                0.06666666666666667,
                                1.0
                            ],
                            "testData": [
                                0.3333333333333333,
                                0.0,
                                0.3333333333333333,
                                0.0
                            ],
                            "anomalous": false
                        },
                        {
                            "hostName": "harness-deployment-canary-56b5cc7c5b-9rpq7",
                            "risk": "HEALTHY",
                            "score": 0.5004,
                            "controlData": [
                                0.0,
                                0.13333333333333333,
                                0.06666666666666667,
                                1.0
                            ],
                            "testData": [
                                0.3333333333333333,
                                0.0,
                                0.0,
                                0.0
                            ],
                            "anomalous": false
                        }
                    ],
                    "nodeRiskCountDTO": {
                        "totalNodeCount": 2,
                        "anomalousNodeCount": 0,
                        "riskCounts": [
                            {
                                "risk": "HEALTHY",
                                "count": 2,
                                "displayName": "Healthy"
                            }
                        ]
                    }
                },
                {
                    "transactionMetric": {
                        "transactionName": "/todolist/register",
                        "metricName": "Calls per Minute",
                        "score": 0.5004,
                        "risk": "HEALTHY"
                    },
                    "connectorName": "appd",
                    "dataSourceType": "APP_DYNAMICS",
                    "nodes": [
                        {
                            "hostName": "harness-deployment-canary-7445f86dbf-ml857",
                            "risk": "HEALTHY",
                            "score": 0.5004,
                            "controlData": [
                                21.599999999999998,
                                22.400000000000002,
                                23.8,
                                25.0
                            ],
                            "testData": [
                                17.666666666666668,
                                27.0,
                                19.666666666666668,
                                24.0
                            ],
                            "anomalous": false
                        },
                        {
                            "hostName": "harness-deployment-canary-56b5cc7c5b-9rpq7",
                            "risk": "HEALTHY",
                            "score": 0.5004,
                            "controlData": [
                                21.599999999999998,
                                22.400000000000002,
                                23.8,
                                22.0
                            ],
                            "testData": [
                                23.0,
                                24.333333333333332,
                                24.333333333333332,
                                29.0
                            ],
                            "anomalous": false
                        }
                    ],
                    "nodeRiskCountDTO": {
                        "totalNodeCount": 2,
                        "anomalousNodeCount": 0,
                        "riskCounts": [
                            {
                                "risk": "HEALTHY",
                                "count": 2,
                                "displayName": "Healthy"
                            }
                        ]
                    }
                },
                {
                    "transactionMetric": {
                        "transactionName": "/todolist/exception",
                        "metricName": "Errors per Minute",
                        "score": 0.05000000000000001,
                        "risk": "HEALTHY"
                    },
                    "connectorName": "appd",
                    "dataSourceType": "APP_DYNAMICS",
                    "nodes": [
                        {
                            "hostName": "harness-deployment-canary-56b5cc7c5b-9rpq7",
                            "risk": "HEALTHY",
                            "score": 0.31999999999999995,
                            "controlData": [
                                38.86666666666667,
                                38.06666666666666,
                                37.86666666666667,
                                0.0
                            ],
                            "testData": [
                                41.333333333333336,
                                44.333333333333336,
                                41.666666666666664,
                                40.0
                            ],
                            "anomalous": false
                        },
                        {
                            "hostName": "harness-deployment-canary-7445f86dbf-ml857",
                            "risk": "HEALTHY",
                            "score": 0.20000000000000004,
                            "controlData": [
                                38.86666666666667,
                                38.06666666666666,
                                37.86666666666667,
                                0.0
                            ],
                            "testData": [
                                33.0,
                                45.0,
                                32.666666666666664,
                                38.0
                            ],
                            "anomalous": false
                        }
                    ],
                    "nodeRiskCountDTO": {
                        "totalNodeCount": 2,
                        "anomalousNodeCount": 0,
                        "riskCounts": [
                            {
                                "risk": "HEALTHY",
                                "count": 2,
                                "displayName": "Healthy"
                            }
                        ]
                    }
                },
                {
                    "transactionMetric": {
                        "transactionName": "/todolist/inside",
                        "metricName": "Errors per Minute",
                        "score": 0.05000000000000001,
                        "risk": "HEALTHY"
                    },
                    "connectorName": "appd",
                    "dataSourceType": "APP_DYNAMICS",
                    "nodes": [
                        {
                            "hostName": "harness-deployment-canary-56b5cc7c5b-9rpq7",
                            "risk": "HEALTHY",
                            "score": 0.403,
                            "controlData": [
                                38.666666666666664,
                                38.06666666666667,
                                38.2,
                                36.2
                            ],
                            "testData": [
                                41.666666666666664,
                                44.333333333333336,
                                41.333333333333336,
                                40.0
                            ],
                            "anomalous": false
                        },
                        {
                            "hostName": "harness-deployment-canary-7445f86dbf-ml857",
                            "risk": "HEALTHY",
                            "score": 0.20000000000000004,
                            "controlData": [
                                38.666666666666664,
                                38.06666666666667,
                                38.2,
                                0.0
                            ],
                            "testData": [
                                33.0,
                                44.666666666666664,
                                32.666666666666664,
                                38.0
                            ],
                            "anomalous": false
                        }
                    ],
                    "nodeRiskCountDTO": {
                        "totalNodeCount": 2,
                        "anomalousNodeCount": 0,
                        "riskCounts": [
                            {
                                "risk": "HEALTHY",
                                "count": 2,
                                "displayName": "Healthy"
                            }
                        ]
                    }
                },
                {
                    "transactionMetric": {
                        "transactionName": "/todolist/exception",
                        "metricName": "Calls per Minute",
                        "score": 0.0,
                        "risk": "HEALTHY"
                    },
                    "connectorName": "appd",
                    "dataSourceType": "APP_DYNAMICS",
                    "nodes": [
                        {
                            "hostName": "harness-deployment-canary-7445f86dbf-ml857",
                            "risk": "HEALTHY",
                            "score": 0.5004,
                            "controlData": [
                                38.86666666666667,
                                38.06666666666666,
                                37.86666666666667,
                                33.0
                            ],
                            "testData": [
                                33.0,
                                45.0,
                                32.666666666666664,
                                38.0
                            ],
                            "anomalous": false
                        },
                        {
                            "hostName": "harness-deployment-canary-56b5cc7c5b-9rpq7",
                            "risk": "HEALTHY",
                            "score": 0.5004,
                            "controlData": [
                                38.86666666666667,
                                38.06666666666666,
                                37.86666666666667,
                                36.0
                            ],
                            "testData": [
                                41.333333333333336,
                                44.333333333333336,
                                41.666666666666664,
                                40.0
                            ],
                            "anomalous": false
                        }
                    ],
                    "nodeRiskCountDTO": {
                        "totalNodeCount": 2,
                        "anomalousNodeCount": 0,
                        "riskCounts": [
                            {
                                "risk": "HEALTHY",
                                "count": 2,
                                "displayName": "Healthy"
                            }
                        ]
                    }
                }
            ],
            "pageIndex": 0,
            "empty": false
        },
        "deploymentTimeRange": {
            "startTime": "2022-01-20 17:26:00",
            "endTime": "2022-01-20 17:27:00"
        },
        "deploymentStartTime": 1642699560000,
        "deploymentEndTime": 1642699620000
    },
    "responseMessages": []
}

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30207)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/activity/resources/ActivityResource.java, line 100 at r2](https://reviewable.io/reviews/harness/harness-core/30207#-MuFM7b6-4CXebe86-Fb:-MuFM7b6-4CXebe86-Fc:bchajkz) ([raw file](https://github.com/harness/harness-core/blob/65172e20eae288202df53ca002444f63b48e3a42/300-cv-nextgen/src/main/java/io/harness/cvng/activity/resources/ActivityResource.java#L100)):*
> ```Java
>             .healthSourceIdentifiers(healthSourceIdentifiers)
>             .filter(filter)
>             .anomalousMetricsOnly(anomalousMetricsOnly)
> ```


can you check if if this is breaking change.



_Code quote:_
```Java
 .anomalousMetricsOnly(anomalousMetricsOnly)
```
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java, line 314 at r2](https://reviewable.io/reviews/harness/harness-core/30207#-MuFLtKfCcpyqRoVUVrr:-MuFLtKg5wCxiGZlC9uw:bmou60g) ([raw file](https://github.com/harness/harness-core/blob/65172e20eae288202df53ca002444f63b48e3a42/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java#L314)):*
> ```Java
> 
>   private boolean filterAnomalousNodes(DeploymentTimeSeriesAnalysisDTO.HostData hostData, boolean anomalousNodesOnly) {
>     if (!anomalousNodesOnly || (anomalousNodesOnly && hostData.isAnomalous())) {
> ```

please add test for both true and false case.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/params/filterParams/TimeSeriesAnalysisFilter.java, line 24 at r2](https://reviewable.io/reviews/harness/harness-core/30207#-MuFL6btBqFIPBWbcK1k:-MuFL6bvEqWGGwM-2Sn0:b2b3ovt) ([raw file](https://github.com/harness/harness-core/blob/65172e20eae288202df53ca002444f63b48e3a42/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/params/filterParams/TimeSeriesAnalysisFilter.java#L24)):*
> ```Java
> public class TimeSeriesAnalysisFilter extends AnalysisFilter {
>   @DefaultValue("false") @QueryParam("anomalousMetricsOnly") boolean anomalousMetricsOnly;
>   @DefaultValue("false") @QueryParam("anomalousNodesOnly") boolean anomalousNodesOnly;
> ```

Please move it to deployment specific filter



_Code quote:_
```Java
TimeSeriesAnalysisFilter
```

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30207)* status: 10 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/activity/resources/ActivityResource.java, line 100 at r2](https://reviewable.io/reviews/harness/harness-core/30207#-MuFM7b6-4CXebe86-Fb:-MuFQngIAXpFDBQUOrFB:bu6sp0w) ([raw file](https://github.com/harness/harness-core/blob/65172e20eae288202df53ca002444f63b48e3a42/300-cv-nextgen/src/main/java/io/harness/cvng/activity/resources/ActivityResource.java#L100)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

can you check if if this is breaking change.
</blockquote></details>

it is not a breaking change as we have renamed the variable associated to QueryParam and not the QueryParam itself. So the API contract remains the same.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java, line 314 at r2](https://reviewable.io/reviews/harness/harness-core/30207#-MuFLtKfCcpyqRoVUVrr:-MuF_Jfi3whasduueK_Z:b-7tfmjp) ([raw file](https://github.com/harness/harness-core/blob/65172e20eae288202df53ca002444f63b48e3a42/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java#L314)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

please add test for both true and false case.
</blockquote></details>

added
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/params/filterParams/TimeSeriesAnalysisFilter.java, line 24 at r2](https://reviewable.io/reviews/harness/harness-core/30207#-MuFL6btBqFIPBWbcK1k:-MuFSvww4s7RopVcVGKo:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/65172e20eae288202df53ca002444f63b48e3a42/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/params/filterParams/TimeSeriesAnalysisFilter.java#L24)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

Please move it to deployment specific filter
</blockquote></details>

done

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 9 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30207#-:-MuFfOIu2Kt_xPTJaYWG:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
