### PR TITLE
feat: [IDP-1003]: Generic dsl fetch layer + Auth interceptor

### PR DESCRIPTION
**Pull request by sathish-soundarapandian**
## Describe your changes
Generic dsl fetch layer + Auth interceptor

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52041)

### CODE REVIEW

**Comment by sathish-soundarapandian** [comment]
trigger commonchecks

**Comment by sathish-soundarapandian** [comment]
trigger mdc

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52041)* status: 36 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/client/DirectDslClient.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/52041#-NceoqDtB-6W_a-4bbrP:-NceoqDu8NCi1LWMUyWC:b-ai7lgo) ([raw file](https://github.com/harness/harness-core/blob/8a45d3049cd2c6755087067b1214a047842426b7/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/client/DirectDslClient.java#L71)):*
> ```Java
>   private Response executeRequest(OkHttpClient client, Request request) {
>     try {
>       okhttp3.Response response = client.newCall(request).execute();
> ```

It would be good to call close() on the response after we are done. Or maybe leverage the autoclose and put it in try itsef
```try(okhttp3.Response response = client.newCall(request).execute()) {```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/GithubIsBranchProtectionSetDsl.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/52041#-Nceqyso1QU5WGfdRmHG:-Nceqyso1QU5WGfdRmHH:b-v2y4uf) ([raw file](https://github.com/harness/harness-core/blob/8a45d3049cd2c6755087067b1214a047842426b7/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/GithubIsBranchProtectionSetDsl.java#L40)):*
> ```Java
>       Map<String, Set<String>> dataPointsAndInputValues, Map<String, String> replaceableHeaders,
>       Map<String, String> possibleReplaceableRequestBodyPairs) {
>     String apiUrl = ((HttpDataSourceLocationEntity) dataSourceLocationEntity).getApiRequestDetails().getUrl();
> ```

nit: we could typecast at the beginning instead of multiple times to improve readability.
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/GithubIsBranchProtectionSetDsl.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/52041#-NcetR522chwGZ7yhNQ7:-NcetR522chwGZ7yhNQ8:b5f77k0) ([raw file](https://github.com/harness/harness-core/blob/8a45d3049cd2c6755087067b1214a047842426b7/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/GithubIsBranchProtectionSetDsl.java#L61)):*
> ```Java
>       Map<String, Set<String>> dataPointsAndInputValues, String requestBody) {
>     if (dataPointsAndInputValues.containsKey(GITHUB_IS_BRANCH_PROTECTED)
>         && dataPointsAndInputValues.get(GITHUB_IS_BRANCH_PROTECTED) != null
> ```

nit: we could use StringUtils.isNotBlank() instead of these 3 lines
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/DataSourceProvider.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/52041#-NcetjTg5wJ7iIaIMEGT:-NcetjTg5wJ7iIaIMEGU:b3s5h21) ([raw file](https://github.com/harness/harness-core/blob/8a45d3049cd2c6755087067b1214a047842426b7/idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/DataSourceProvider.java#L37)):*
> ```Java
> 
>   public static final String REPO_SCM = "{REPO_SCM}";
>   protected static final String REPOSITORY_OWNER = "{REPOSITORY_OWNER}";
> ```

Could these go in GithubProvider as these are only used there?
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/GithubProvider.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/52041#-Nceutb-3QqxwNBIYz9I:-Nceutb-3QqxwNBIYz9J:bklc9tj) ([raw file](https://github.com/harness/harness-core/blob/8a45d3049cd2c6755087067b1214a047842426b7/idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/GithubProvider.java#L48)):*
> ```Java
>     Map<String, String> authHeaders = this.getAuthHeaders(accountIdentifier);
>     Map<String, String> replaceableHeaders = new HashMap<>();
>     replaceableHeaders.putAll(authHeaders);
> ```

nit: `Map<String, String> replaceableHeaders = new HashMap<>(authHeaders);` instead
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/GithubProvider.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/52041#-NcevM4X5DGLpwgYAq6D:-NcevM4X5DGLpwgYAq6E:bruz45f) ([raw file](https://github.com/harness/harness-core/blob/8a45d3049cd2c6755087067b1214a047842426b7/idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/GithubProvider.java#L52)):*
> ```Java
>     Map<String, String> possibleReplaceableRequestBodyPairs = new HashMap<>();
>     String catalogLocation = entity.getMetadata().getAnnotations().get("backstage.io/managed-by-location");
>     extractAndAddPossibleReplaceableRequestBodyPairs(catalogLocation, possibleReplaceableRequestBodyPairs);
> ```

nit: instead of sending the hashmap to this method, how about constructing one inside and returning? This method could be renamed appropriately
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/HarnessProvider.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/52041#-NcewSIHCJC-aF-CcCFf:-NcewSIHCJC-aF-CcCFg:b-yy7som) ([raw file](https://github.com/harness/harness-core/blob/8a45d3049cd2c6755087067b1214a047842426b7/idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/HarnessProvider.java#L43)):*
> ```Java
> 
>   private static final String X_SOURCE_PRINCIPAL = "X-Source-Principal";
>   private static final String ACCOUNT_IDENTIFIER = "ACCOUNT_IDENTIFIER";
> ```

This would be harness-account in the API I guess?
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/HarnessProvider.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/52041#-Ncex97O5Q_EmmoIR3G7:-Ncex97O5Q_EmmoIR3G8:b-io85y1) ([raw file](https://github.com/harness/harness-core/blob/8a45d3049cd2c6755087067b1214a047842426b7/idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/HarnessProvider.java#L60)):*
> ```Java
> 
>   @Override
>   public Map<String, String> getAuthHeaders(String accountIdentifier) {
> ```

IdpAuthInterceptor has similar code. Can we move the common out to a separate method?

**Comment by sathish-soundarapandian** [comment]
> It would be good to call close() on the response after we are done. Or maybe leverage the autoclose and put it in try itsef

Done

> nit: we could typecast at the beginning instead of multiple times to improve readability.

Done

> nit: we could use StringUtils.isNotBlank() instead of these 3 lines

Done. Used CollectionUtils

> Could these go in GithubProvider as these are only used there?

These can be re-used for other SCM

> nit: `Map<String, String> replaceableHeaders = new HashMap<>(authHeaders);` instead

Done

> nit: instead of sending the hashmap to this method, how about constructing one inside and returning? This method could be renamed appropriately

Done

> This would be harness-account in the API I guess?

Done

> IdpAuthInterceptor has similar code. Can we move the common out to a separate method?

Done

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52041)* status: 38 file(s) to review. 1 of 2 approvals obtained.

**Review by devesh-harness — DISMISSED** [review]

**Comment by sathish-soundarapandian** [comment]
trigger review

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Review by devesh-harness — APPROVED** [review]

**Comment by sathish-soundarapandian** [comment]
trigger ut7

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 23 of 23 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52041)* status: 39 file(s) to review.

**Comment by vikyathharekal** [comment]
trigger review

**Pull request merged**
