### PR TITLE
[feat]: [CDS-84518]: Fix StoreTypeCheck and Remove Duplicate Code in ScmErrorHandler.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:

Change: Removed some duplicate Code by adding a null check for the unwanted param.

Testing: Reproduced the case for which null gitMetadata is passed and verified the null check. Same UI handling observed as before the null check.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55382)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger uts

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55382)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/errorhandling/ScmErrorHandler.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/55382#-NjHxZrh94pl32Lu3f7d:-NjHxZri9I9WUn-SRUTq:bate3dq) ([raw file](https://github.com/harness/harness-core/blob/1f1f1df8a81c16f326f591dea36a8a925193231b/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/errorhandling/ScmErrorHandler.java#L75)):*
> ```Java
>   }
> 
>   private WingsException addMetadata(WingsException wingsException, ScmGitMetaData errorMetadata) {
> ```

lets create a overloaded method for this one without errorMetadata as argument and use it.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55382)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/errorhandling/ScmErrorHandler.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/55382#-NjHxZrh94pl32Lu3f7d:-NjIfLGzELY15W2KstPo:b-3wqyv9) ([raw file](https://github.com/harness/harness-core/blob/1f1f1df8a81c16f326f591dea36a8a925193231b/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/errorhandling/ScmErrorHandler.java#L75)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets create a overloaded method for this one without errorMetadata as argument and use it.
</blockquote></details>

If i create a new overloaded method, then either I have to reduplicate code using one without errorMetadata or Add null check in each case of existing method. Or we can add else condition here itself :  
else{  
wingsException.setMetadata(GitErrorMetadataDTO.builder()  
.build());  
}, need more clarity on this.

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/errorhandling/ScmErrorHandler.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/55382#-NjHxZrh94pl32Lu3f7d:-NjJd6VpCcwDgTiee8BT:bi8fhiv) ([raw file](https://github.com/harness/harness-core/blob/1f1f1df8a81c16f326f591dea36a8a925193231b/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/errorhandling/ScmErrorHandler.java#L75)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

If i create a new overloaded method, then either I have to reduplicate code using one without errorMetadata or Add null check in each case of existing method. Or we can add else condition here itself :  
else{  
wingsException.setMetadata(GitErrorMetadataDTO.builder()  
.build());  
}, need more clarity on this.
</blockquote></details>

What if simply you do:
private WingsException addMetadata(WingsException wingsException) {
return addMetadata(wingsException, null);
}

**Comment by senjucanon2** [comment]
trigger uts

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55382)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/errorhandling/ScmErrorHandler.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/55382#-NjHxZrh94pl32Lu3f7d:-NjRWAuEA9w17w2Rm0fH:b-cximbp) ([raw file](https://github.com/harness/harness-core/blob/1f1f1df8a81c16f326f591dea36a8a925193231b/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/errorhandling/ScmErrorHandler.java#L75)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

What if simply you do:
private WingsException addMetadata(WingsException wingsException) {
return addMetadata(wingsException, null);
}
</blockquote></details>

Overridded a parent function which is called by actual GitSyncHelper, now the flow is centrally handled .

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55382)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
