### PR TITLE
feat: [PL-23577]: Users deletion V2 behaviour.

### PR DESCRIPTION
**Pull request by boopesh007**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41864)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 2968 at r1](https://reviewable.io/reviews/harness/harness-core/41864#-NJp-ptkDPYgZG5f4pXb:-NJp-ptkDPYgZG5f4pXc:b-5x443o) ([raw file](https://github.com/harness/harness-core/blob/549b27f720b5923cbb86f47f59e08f918976f2da/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L2968)):*
> ```Java
>       log.warn("User is removed from all user groups in CG");
>       user.setUserGroups(new ArrayList<>());
>       log.error("User {} cannot be deleted in CG, since he is active on NG in account {}", user.getEmail(), accountId);
> ```

please use `it`, thanks



_Code quote:_
```Java
 he
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 2954 at r1](https://reviewable.io/reviews/harness/harness-core/41864#-NJp09Z5A1mQHvFzzpvH:-NJp09Z5A1mQHvFzzpvI:b-e6px1e) ([raw file](https://github.com/harness/harness-core/blob/549b27f720b5923cbb86f47f59e08f918976f2da/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L2954)):*
> ```Java
>     } else {
>       return true;
>     }
> ```

nit: can be converted directly to 1 line as `return !isEmpty(userGroups)` , thanks



_Code quote:_
```Java
    if (isEmpty(userGroups)) {
      return false;
    } else {
      return true;
    }
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 2941 at r1](https://reviewable.io/reviews/harness/harness-core/41864#-NJp1nXTAInsmgWqWPeS:-NJp1nXTAInsmgWqWPeT:b-9jhr6e) ([raw file](https://github.com/harness/harness-core/blob/549b27f720b5923cbb86f47f59e08f918976f2da/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L2941)):*
> ```Java
>       }
>       memberIds.forEach(userIdentifier -> userUserGroupMap.put(userIdentifier, userGroup));
>     });
> ```

This code seems repetitive, can we please extract it in separate method and use at both places, thanks



_Code quote:_
```Java
    PageRequest<UserGroup> req = aPageRequest()
                                     .withLimit(Long.toString(userGroupService.getCountOfUserGroups(accountId)))
                                     .addFilter(UserGroup.UserGroupKeys.accountId, EQ, accountId)
                                     .build();
    PageResponse<UserGroup> res = userGroupService.list(accountId, req, false, null, null);
    List<UserGroup> allUserGroupList = res.getResponse();
    if (isEmpty(allUserGroupList)) {
      return false;
    }

    Multimap<String, UserGroup> userUserGroupMap = HashMultimap.create();

    allUserGroupList.forEach(userGroup -> {
      List<String> memberIds = userGroup.getMemberIds();
      if (isEmpty(memberIds)) {
        return;
      }
      memberIds.forEach(userIdentifier -> userUserGroupMap.put(userIdentifier, userGroup));
    });
```

**Comment by abhayganvir** [comment]
trigger pocpermission

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 9 of 9 files at r1, 1 of 4 files at r2, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41864)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Pull request closed without merging**
