### PR TITLE
feat: [CDC-16236]: AppTelemetry for WF events

### PR DESCRIPTION
**Pull request by puthrayaharness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30697)

### CODE REVIEW

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 21 of 22 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30697)* status: :shipit: complete! ✓

**Comment by USB-05** [comment]
trigger ti0

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 18 of 22 files at r1, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30697)* status: :shipit: complete! ✓

**Comment by puthrayaharness** [comment]
trigger ti2 ti4

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30697)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 18 of 22 files at r1, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30697)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30697)* status: :shipit: complete! ✓

**Pull request merged**
