### PR TITLE
[feat]: [CDS-72193]: Integration of git settings: "applyGitXRepoAllowListFilter" for ImportFlow.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:

Context: Following the integration of the new setting "gitRepoAllowList" , this PR integrates that setting for ImportFlow. 

Changes: An internal flag "applyGitXRepoSetting" is introduced, only Import Flow send it true to getFIle Scm call as of now.
If this flag is set to true, setting would be applied to importFlow.

Impact: Import Flow for all gitProviders.

Testing: Both SSH and Https type Github, Gitlab connectors and their use-cases have been tested.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50018)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmGetFileByBranchRequestDTO.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/50018#-NZ_HrDE5vNwWitxFsZM:-NZ_HrDE5vNwWitxFsZN:b972s30) ([raw file](https://github.com/harness/harness-core/blob/650234f5ee41accb543fe37635a422f8c4422822/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmGetFileByBranchRequestDTO.java#L35)):*
> ```Java
>   // If ScmConnector is not null, then we use it instead of processing connectorRef
>   ScmConnector scmConnector;
>   boolean applyGitXRepoAllowListFilter;
> ```

Lets create a structure named "Settings" and put this field inside it as "applyRepoAllowlistSetting". This will help us to encapsulate such settings at a common place in future.

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java` line 58 at r3](https://reviewable.io/reviews/harness/harness-core/50018#-NZ_INKz8PHiC1C8sSZN:-NZ_INKz8PHiC1C8sSZO:b-4qnpvp) ([raw file](https://github.com/harness/harness-core/blob/650234f5ee41accb543fe37635a422f8c4422822/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java#L58)):*
> ```Java
> 
>   public GitAware fetchEntityFromRemote(GitAware entity, Scope scope, GitContextRequestParams gitContextRequestParams,
>       Map<String, String> contextMap, boolean applyGitXRepoAllowListFilter) {
> ```

can't it be added into "GitContextRequestParams" ?

**Comment by mohitg0795** [comment]
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 124 at r3](https://reviewable.io/reviews/harness/harness-core/50018#-NZ_IYh_1W93zpgMDGMX:-NZ_IYh_1W93zpgMDGMY:b-kvm3zk) ([raw file](https://github.com/harness/harness-core/blob/650234f5ee41accb543fe37635a422f8c4422822/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L124)):*
> ```proto
>   EntityType entityType = 10;
>   bool getOnlyFileContent = 11;
>   bool applyGitXRepoAllowListFilter = 12;
> ```

same  as above, better would be to put setting inside a structure to keep all settings at a common place

**Comment by mohitg0795** [comment]
*[`template-service/service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/50018#-NZ_JWgX-R6jLTv5L2on:-NZ_JWgX-R6jLTv5L2oo:b-dzefvv) ([raw file](https://github.com/harness/harness-core/blob/650234f5ee41accb543fe37635a422f8c4422822/template-service/service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L93)):*
> ```Java
>                                                           .repoName(gitEntityInfo.getRepoName())
>                                                           .build();
>     return gitAwareEntityHelper.fetchYAMLFromRemote(scope, gitContextRequestParams, Collections.emptyMap(), false);
> ```

why false here?

**Review by senjucanon2 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50018#-:-NZe92prCIqzDhf-mG66:bnfp4nl)* status: 19 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmGetFileByBranchRequestDTO.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/50018#-NZ_HrDE5vNwWitxFsZM:-NZe95-rEjASi9IMxrmI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/650234f5ee41accb543fe37635a422f8c4422822/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmGetFileByBranchRequestDTO.java#L35)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets create a structure named "Settings" and put this field inside it as "applyRepoAllowlistSetting". This will help us to encapsulate such settings at a common place in future.
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java` line 58 at r3](https://reviewable.io/reviews/harness/harness-core/50018#-NZ_INKz8PHiC1C8sSZN:-NZe96trE3AZMWLyhvCb:bss4xj7) ([raw file](https://github.com/harness/harness-core/blob/650234f5ee41accb543fe37635a422f8c4422822/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java#L58)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can't it be added into "GitContextRequestParams" ?
</blockquote></details>

Avoided adding in it this class, as it had context of request params, but our flag was internal, and hence created a new class for it.
___
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 124 at r3](https://reviewable.io/reviews/harness/harness-core/50018#-NZ_IYh_1W93zpgMDGMX:-NZe9Lyy77m_BjI44prO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/650234f5ee41accb543fe37635a422f8c4422822/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L124)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same  as above, better would be to put setting inside a structure to keep all settings at a common place
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/50018#-NZ_JWgX-R6jLTv5L2on:-NZe9N4g5ZtySM76dl-K:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/650234f5ee41accb543fe37635a422f8c4422822/template-service/service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L93)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why false here?
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 16 files at r1, 1 of 1 files at r3, 2 of 11 files at r4, 10 of 10 files at r5, 5 of 7 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50018)* status: 22 file(s) to review. 1 of 2 approvals obtained.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Review by adivishy1 — APPROVED** [review]
> Reviewed 2 of 16 files at r1, 1 of 1 files at r3, 7 of 11 files at r4, 10 of 10 files at r5, 4 of 7 files at r6, 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50018)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50018)* status: :shipit: complete! ✓

**Comment by senjucanon2** [comment]
trigger review

**Review by ankittiwari-harness — APPROVED** [review]

**Pull request merged**
