### PR TITLE
fix: [SPG-1023]: Optimize Perpetual Task Iterator Mongo query

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

This PR optimizes the Mongo query made by the PerpetualTask Iterator by doing the below -
1. While creating a perpetual task record initialize the `assignIteration` field that is used by the iterator to 0. This allows to get away with having the `{"assignIteration": {"$exists": false}}` clause in the query.
2. Use `MorphiaPersistenceRequiredProvider` instead of `MorphiaPersistenceProvider` so that the query does not contain `{"assignIteration": {"$exists": false}}`. This will allow Mongo to use the compoundIndexes for the collection effectively and should not load all the documents from disk to memory which is taking up a lot of time.
* The query generated by `MorphiaPersistenceRequiredProvider` is `{ query: {"state": "TASK_UNASSIGNED", "assignAfterMs": {"$lte": {"$numberLong": "1672789016916"}}, "assignIteration": {"$lt": {"$numberLong": "1672788996771"}}}  }`
* The query generated by `MorphiaPersistenceProvider` is `{ query: {"state": "TASK_UNASSIGNED", "assignAfterMs": {"$lte": {"$numberLong": "1672791251986"}}, "$or": [{"assignIteration": {"$lt": {"$numberLong": "1672791250648"}}}, {"assignIteration": {"$exists": false}}]}  }`

I tested this locally for the below scenarios -
1. The query is updated to no longer contain the exists is false clause.
2. To check if the newly created PerpetualTask record contains the `assignIteration` field initialized to currentTime.
3. The iterator picks up this record and processed it and then updates `assignIteration` field appropriately.   

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42196)

### CODE REVIEW

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java` line 158 at r1](https://reviewable.io/reviews/harness/harness-core/42196#-NKuFWRX-EvTtnw3YUI2:-NKuFWRX-EvTtnw3YUI3:b-fx3p70) ([raw file](https://github.com/harness/harness-core/blob/62ebda0b38582d8b14600f7d27fb9d1fd0a5bcab/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L158)):*
> ```Java
>                                        .delegateId("")
>                                        .state(PerpetualTaskState.TASK_UNASSIGNED)
>                                        .assignIteration(0)
> ```

it's fine to add the current time here instead of 0.

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42196)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java` line 158 at r1](https://reviewable.io/reviews/harness/harness-core/42196#-NKuFWRX-EvTtnw3YUI2:-NKy68KY3zx_bfY4AcqI:b-tq8am7) ([raw file](https://github.com/harness/harness-core/blob/62ebda0b38582d8b14600f7d27fb9d1fd0a5bcab/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L158)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

it's fine to add the current time here instead of 0.
</blockquote></details>

Done. Will update it.

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42196)* status: :shipit: complete! ✓

**Pull request merged**
