### PR TITLE
feat: [CDS-68176]: Added caseinsensitive sorting for Service, Envs

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
## Describe your changes
Add case insensitive sorting in LIST APIs for service and environment
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47300)

### CODE REVIEW

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47300)* status: 3 file(s) to review. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/47300#-NUZxdr0BgeHkjeO2IVB:-NUZxdr0BgeHkjeO2IVC:bc8u660) ([raw file](https://github.com/harness/harness-core/blob/e071513a0b6c21520c23bc0d6496cb50b6bdb8da/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L46)):*
> ```Java
>   @Override
>   public Page<Environment> findAll(Criteria criteria, Pageable pageable) {
>     Query query = new Query(criteria).with(pageable).collation(Collation.of(Locale.ENGLISH).strength(1));
> ```

nit, is it possible to add a UT using in-memory Mongo to test it out?

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/47300#-NUqq5dO-0e17R0dBEfV:-NUqq5dO-0e17R0dBEfW:bwxp9fm) ([raw file](https://github.com/harness/harness-core/blob/df2db93500eb545501a277e1c10bf9700dc94855/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L50)):*
> ```Java
>     return PageableExecutionUtils.getPage(
>         projects, pageable, () -> mongoTemplate.count(Query.of(query).limit(-1).skip(-1), Environment.class));
>   }
> ```

There is 1 more findAll method in this class
```io.harness.repositories.environment.custom.EnvironmentRepositoryCustomImpl#findAll(org.springframework.data.mongodb.core.query.Criteria)```
can we update there as well ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47300)* status: 5 file(s) to review. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/47300#-NUqymEM9aS1SWTXN_El:-NUqymEM9aS1SWTXN_Em:b-9t4a8l) ([raw file](https://github.com/harness/harness-core/blob/df2db93500eb545501a277e1c10bf9700dc94855/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L48)):*
> ```Java
> 
>   @Override
>   public Page<ServiceEntity> findAll(Criteria criteria, Pageable pageable) {
> ```

there is 1 another findAll method in this class

**Comment by sourabh-awashti** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
trigger ut0

**Comment by yogesh-chauhan** [comment]
trigger ut0

**Comment by yogesh-chauhan** [comment]
trigger ut0

**Comment by sourabh-awashti** [comment]
trigger messagecheck

**Comment by harshjain12** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
trigger ut0

**Comment by yogesh-chauhan** [comment]
trigger ut1, ut2, ut3, ut4

**Comment by yogesh-chauhan** [comment]
trigger ut5, ut6, ut7, ut8, ut9

**Comment by yogesh-chauhan** [comment]
trigger ut1, ut2, ut3, ut4

**Review by yogesh-chauhan — APPROVED** [review]

**Review by rohitk-h — APPROVED** [review]

**Review by rohitk-h — APPROVED** [review]

**Review by rohitk-h — APPROVED** [review]

**Review by abhinav-harness — APPROVED** [review]

**Comment by abhinav-harness** [comment]
trigger review

**Pull request merged**
