### PR TITLE
feat: [IDP-1691]: Gitlab & Bitbucket file parser data points

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56056)

### CODE REVIEW

**Review by vikyathharekal — CHANGES_REQUESTED** [review]
> Reviewed 15 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56056)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/scm/bitbucket/BitbucketFileContainsParser.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/56056#-NkKwAK219QV5VTCggs7:-NkKwAK219QV5VTCggs8:b-3sqaxk) ([raw file](https://github.com/harness/harness-core/blob/c8ca02fe00105edcee1413facda37a69502b4b3a/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/scm/bitbucket/BitbucketFileContainsParser.java#L16)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.IDP)
> public class BitbucketFileContainsParser extends BitbucketFileParser {
> ```

Can we re-use GithubFileContainsParser instead of duplicating this? 
Or have this code in SCMFileContainsParser and use it in everywhere?



_Code quote:_
```Java
BitbucketFileContainsParser
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/scm/bitbucket/BitbucketFileContentsParser.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/56056#-NkKwT1M4aRZXrd4Z-BR:-NkKwT1M4aRZXrd4Z-BS:b-96hwww) ([raw file](https://github.com/harness/harness-core/blob/c8ca02fe00105edcee1413facda37a69502b4b3a/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/scm/bitbucket/BitbucketFileContentsParser.java#L16)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.IDP)
> public class BitbucketFileContentsParser extends BitbucketFileParser {
> ```

Same comment as the prev one
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/scm/bitbucket/BitbucketFileParser.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/56056#-NkKwhvT6uVfTMhznrMB:-NkKwhvT6uVfTMhznrMC:b-fl2j5e) ([raw file](https://github.com/harness/harness-core/blob/c8ca02fe00105edcee1413facda37a69502b4b3a/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/scm/bitbucket/BitbucketFileParser.java#L32)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.IDP)
> public abstract class BitbucketFileParser implements DataPointParser {
> ```

Can we move common code to a common place? Most of the code here looks similar to Github one



_Code quote:_
```Java
BitbucketFileParser
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/scm/gitlab/GitlabContentsDsl.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/56056#-NkKxMhA8J51lpREA2sC:-NkKxMhA8J51lpREA2sD:b-u2zs7n) ([raw file](https://github.com/harness/harness-core/blob/c8ca02fe00105edcee1413facda37a69502b4b3a/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/scm/gitlab/GitlabContentsDsl.java#L24)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.IDP)
> public class GitlabContentsDsl extends GitlabBaseDsl {
> ```

Can we try to generalize this similar to ScmBaseDslLoop?



_Code quote:_
```Java
GitlabContentsDsl
```

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56056)* status: 22 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/scm/gitlab/GitlabContentsDsl.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/56056#-NkKxMhA8J51lpREA2sC:-NkLUn987kPpMi6i4jY8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c8ca02fe00105edcee1413facda37a69502b4b3a/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/scm/gitlab/GitlabContentsDsl.java#L24)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we try to generalize this similar to ScmBaseDslLoop?
</blockquote></details>

Done.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 9 of 9 files at r2, 5 of 5 files at r3, 2 of 8 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56056)* status: 24 file(s) to review. 1 of 2 approvals obtained.

**Comment by vigneswara-propelo** [comment]
trigger uts

**Review by devesh-harness — APPROVED** [review]

**Comment by vigneswara-propelo** [comment]
trigger review

**Pull request merged**
