### PR TITLE
fix: [PL-30421]: Fix thread contention on RedissonKryoCodec class

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Describe your changes
We are seeing high time thread contention in this class RedissonKryoCodec. This pr fixes this. Details are explained in jira ticket.
## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41606)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41606)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/41606#-NJJdu6z2K5ki2W40Isj:-NJJdu6z2K5ki2W40Isk:b7vjbuh) ([raw file](https://github.com/harness/harness-core/blob/3d23dc89ae59487c3fdcf917c61e1a8d89bfd29e/960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java#L43)):*
> ```Java
> 
>   private synchronized Kryo kryo() {
>     if (cachedKryo != null) {
> ```

This will lead to contention. Every thread will acquire lock.

We should remove synchronized keyword from the method. Read https://www.baeldung.com/java-singleton-double-checked-locking

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41606)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/41606#-NJJdu6z2K5ki2W40Isj:-NJJeRyT-u7aAQCp4oJe:b-cshc0s) ([raw file](https://github.com/harness/harness-core/blob/3d23dc89ae59487c3fdcf917c61e1a8d89bfd29e/960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java#L43)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This will lead to contention. Every thread will acquire lock.

We should remove synchronized keyword from the method. Read https://www.baeldung.com/java-singleton-double-checked-locking
</blockquote></details>

We need to follow double check idiom here

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41606)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java` line 71 at r3](https://reviewable.io/reviews/harness/harness-core/41606#-NJKXzhpDJRS0axBhMwm:-NJKXzhpDJRS0axBhMwn:brii9ei) ([raw file](https://github.com/harness/harness-core/blob/2cdef975ae51a31c9a93744fdf52beef9a5758d5/960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java#L71)):*
> ```Java
>   }
> 
>   private synchronized Set<Class<? extends KryoRegistrar>> getReflections() {
> ```

It should be getKryoRegistrars()
___
*[`960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java` line 71 at r3](https://reviewable.io/reviews/harness/harness-core/41606#-NJKYDy782crkhwUjkZN:-NJKYDy782crkhwUjkZO:bvom4jz) ([raw file](https://github.com/harness/harness-core/blob/2cdef975ae51a31c9a93744fdf52beef9a5758d5/960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java#L71)):*
> ```Java
>   }
> 
>   private synchronized Set<Class<? extends KryoRegistrar>> getReflections() {
> ```

Why is it synchronized?

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41606)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/41606#-NJJdu6z2K5ki2W40Isj:-NJOW1mO05jDQzxmmJPx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3d23dc89ae59487c3fdcf917c61e1a8d89bfd29e/960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java#L43)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We need to follow double check idiom here
</blockquote></details>

Done.
___
*[`960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java` line 71 at r3](https://reviewable.io/reviews/harness/harness-core/41606#-NJKXzhpDJRS0axBhMwm:-NJOW27f4Eg59BZZUfVo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2cdef975ae51a31c9a93744fdf52beef9a5758d5/960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java#L71)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

It should be getKryoRegistrars()
</blockquote></details>

Done.
___
*[`960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java` line 71 at r3](https://reviewable.io/reviews/harness/harness-core/41606#-NJKYDy782crkhwUjkZN:-NJOW2gu84h11UerEQ2C:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2cdef975ae51a31c9a93744fdf52beef9a5758d5/960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java#L71)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why is it synchronized?
</blockquote></details>

Done.

**Review by ankit-harness — APPROVED** [review]

**Review by ashishsanodia-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41606)* status: 3 file(s) to review. 3. unresolved discussions.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41606)* status: :shipit: complete! ✓

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41606#-:-NJOXU9h-aPdmbZwmOB-:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
