### PR TITLE
[feat]: [CDS-81658]: Added Contract changes v2/environmentInputYamlAndServiceOverrides Metadata API to unblock UI

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Have added a new API without functional support to unblock UI.

1. Why we made the change ?
To unblock UI for the selection-inputs of remote envs

2. What is the change ?
Have added a new API without functional support to unblock UI.

4. What will be the impact ?
Selection of Inputs for remote Envs.

Testing: Currently a Non-functional API.
 

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54308)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger messagecheck

**Review by hingerabhinav — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54308)* status: 7 file(s) to review. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentInputsetYamlAndServiceOverridesMetadataInput.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/54308#-Nh0jkrk5rbZ8vAlXk2G:-Nh0jkrk5rbZ8vAlXk2H:bmo64fb) ([raw file](https://github.com/harness/harness-core/blob/99a48ba8ea788e65b8741a90a0bf86aeedb99c3a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentInputsetYamlAndServiceOverridesMetadataInput.java#L32)):*
> ```Java
>   @NotNull List<String> serviceIdentifiers;
>   String envGroupIdentifier;
>   @Schema(hidden = true) @Size(max = 1000) List<EntityWithGitInfo> entityWithGitInfoList;
> ```

Let's create a separate Pojo for v2 API, this DTO has duplicate info for env ids.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger ut5, ut6, ut8

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/beans/EnvironmentInputSetYamlAndServiceOverridesMetadataInputV2.java` line 27 at r6](https://reviewable.io/reviews/harness/harness-core/54308#-Nh5HwzH-GS00h4nPU3T:-Nh5HwzH-GS00h4nPU3U:b-mn3rw8) ([raw file](https://github.com/harness/harness-core/blob/e80c8175e4d3a3be6535aaf02b0efaa7618d814b/120-ng-manager/src/main/java/io/harness/ng/core/beans/EnvironmentInputSetYamlAndServiceOverridesMetadataInputV2.java#L27)):*
> ```Java
> @Builder
> @FieldDefaults(level = AccessLevel.PRIVATE)
> public class EnvironmentInputSetYamlAndServiceOverridesMetadataInputV2 {
> ```

This class does not seem to have any inputSetYaml, is the name correct ?

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 882 at r6](https://reviewable.io/reviews/harness/harness-core/54308#-Nh5IBTIDArMiCQAStKn:-Nh5IBTIDArMiCQAStKo:bz22427) ([raw file](https://github.com/harness/harness-core/blob/e80c8175e4d3a3be6535aaf02b0efaa7618d814b/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L882)):*
> ```Java
> 
>   @POST
>   @Path("V2/env-service-override-metadata")
> ```

I think all our existing APIs are using camel case for path names, can we make it consistent ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 3 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54308)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by hingerabhinav — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54308)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/beans/EnvironmentInputSetYamlAndServiceOverridesMetadataInputV2.java` line 27 at r6](https://reviewable.io/reviews/harness/harness-core/54308#-Nh5HwzH-GS00h4nPU3T:-Nh5LOM-4vQTnEaZd-Vq:b-dnm6x1) ([raw file](https://github.com/harness/harness-core/blob/e80c8175e4d3a3be6535aaf02b0efaa7618d814b/120-ng-manager/src/main/java/io/harness/ng/core/beans/EnvironmentInputSetYamlAndServiceOverridesMetadataInputV2.java#L27)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This class does not seem to have any inputSetYaml, is the name correct ?
</blockquote></details>

EnvironmentAndServiceOverridesMetadataInput maybe. We used to use input set as a term for getting runtime input YAML but we should remove it now. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 882 at r6](https://reviewable.io/reviews/harness/harness-core/54308#-Nh5LTBM73GWM-ls9kiI:-Nh5LTBM73GWM-ls9kiJ:bxh14v9) ([raw file](https://github.com/harness/harness-core/blob/e80c8175e4d3a3be6535aaf02b0efaa7618d814b/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L882)):*
> ```Java
> 
>   @POST
>   @Path("V2/env-service-override-metadata")
> ```

let's make it v2 (small case)

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 882 at r6](https://reviewable.io/reviews/harness/harness-core/54308#-Nh5IBTIDArMiCQAStKn:-Nh5MqafDo0I8G9NVc1_:b6xm1zc) ([raw file](https://github.com/harness/harness-core/blob/e80c8175e4d3a3be6535aaf02b0efaa7618d814b/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L882)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I think all our existing APIs are using camel case for path names, can we make it consistent ?
</blockquote></details>

discussed offline https://harness.slack.com/archives/C02HZA70KBK/p1697644292405339

**Comment by senjucanon2** [comment]
trigger uts

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54308)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
