### PR TITLE
fix: [CDS-47647]: custom manifest

### PR DESCRIPTION
**Pull request by TarunUba1**
## Describe your changes
Adding support for Absolute path in Custom manifest.
## Testing
Normal case:-
Screenshot 2022-12-12 at 4 54 26 PM
Screenshot 2022-12-12 at 4 54 40 PM
New Case but file still in temporary directory:-
Screenshot 2022-12-13 at 2 07 45 AM
Screenshot 2022-12-13 at 2 08 19 AM

Case when in Absolute Path:-
Screenshot 2022-12-12 at 4 45 34 PM
Screenshot 2022-12-12 at 4 54 55 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41317)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41317)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java` line 205 at r1](https://reviewable.io/reviews/harness/harness-core/41317#-NIpmlfZDIj-cVxxnUd6:-NIpmlfZDIj-cVxxnUd7:b-vtn7pf) ([raw file](https://github.com/harness/harness-core/blob/a0b45ef96fce8f5b568d32211e76f9a1ebf2fcd3/930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java#L205)):*
> ```Java
> 
>         zipManifestFiles(pathToManifestFiles.toString(), destZippedManifestFile.toString());
>       } catch (FileNotFoundException e) {
> ```

Let's handle all exceptions here and add a warning log for catch block

**Review by vikyathharekal — CHANGES_REQUESTED** [review]
@tarunuba1 Could you describe the changes and add what you have tested in the PR description?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41317#-:-NJ3okZw1JxiAOfqqmdt:b-arm3i6)* status: Some of the checks are too old. 2 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java` line 200 at r1](https://reviewable.io/reviews/harness/harness-core/41317#-NJ3nnlx8E7Gw9LB47zF:-NJ3nnlx8E7Gw9LB47zG:b-jdjhpe) ([raw file](https://github.com/harness/harness-core/blob/a0b45ef96fce8f5b568d32211e76f9a1ebf2fcd3/930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java#L200)):*
> ```Java
>     Path destZippedManifestFile = Paths.get(destZippedManifestDirectory, "destZipManifestFile.zip");
>     Path pathToManifestFiles;
>     if (customManifestSource.getFilePaths().get(0).charAt(0) == '/') {
> ```

Could we use startsWith() instead?



_Code quote:_
```Java
.charAt(0) == '/'
```

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41317)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java` line 200 at r1](https://reviewable.io/reviews/harness/harness-core/41317#-NJ3nnlx8E7Gw9LB47zF:-NJ4_XlGBRj54QbrO6YB:bdbmiwq) ([raw file](https://github.com/harness/harness-core/blob/a0b45ef96fce8f5b568d32211e76f9a1ebf2fcd3/930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java#L200)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Could we use startsWith() instead?
</blockquote></details>

&lt;file name="/harness/930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java">
&lt;violation beginline="202" endline="202" begincolumn="9" endcolumn="66" rule="SimplifyStartsWith" ruleset="Performance" package.
It looks like this way is slower and in docs asking to do the same way i was doing
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java` line 205 at r1](https://reviewable.io/reviews/harness/harness-core/41317#-NIpmlfZDIj-cVxxnUd6:-NJ4_eOJEkzdeYv6bU0-:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a0b45ef96fce8f5b568d32211e76f9a1ebf2fcd3/930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java#L205)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's handle all exceptions here and add a warning log for catch block
</blockquote></details>

Done

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41317)* status: 3 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java` line 200 at r1](https://reviewable.io/reviews/harness/harness-core/41317#-NJ3nnlx8E7Gw9LB47zF:-NJ4eT-e1kzsZWU_r3ty:bl1ikyh) ([raw file](https://github.com/harness/harness-core/blob/a0b45ef96fce8f5b568d32211e76f9a1ebf2fcd3/930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java#L200)):*
<details><summary><i>Previously, TarunUba1 (Tarun Uba) wrote…</i></summary><blockquote>

&lt;file name="/harness/930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java">
&lt;violation beginline="202" endline="202" begincolumn="9" endcolumn="66" rule="SimplifyStartsWith" ruleset="Performance" package.
It looks like this way is slower and in docs asking to do the same way i was doing
</blockquote></details>

Did you find any analysis regarding this? Which docs are you referring to?

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41317)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java` line 200 at r1](https://reviewable.io/reviews/harness/harness-core/41317#-NJ3nnlx8E7Gw9LB47zF:-NJ4vL-n-hpZLwEvGoNA:b-ec5grl) ([raw file](https://github.com/harness/harness-core/blob/a0b45ef96fce8f5b568d32211e76f9a1ebf2fcd3/930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java#L200)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Did you find any analysis regarding this? Which docs are you referring to?
</blockquote></details>

https://pmd.sourceforge.io/pmd-6.23.0/pmd_rules_java_performance.html#simplifystartswith

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41317)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java` line 200 at r1](https://reviewable.io/reviews/harness/harness-core/41317#-NJ3nnlx8E7Gw9LB47zF:-NJ4vS8b2RgEsR74rz5S:byj8dfw) ([raw file](https://github.com/harness/harness-core/blob/a0b45ef96fce8f5b568d32211e76f9a1ebf2fcd3/930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java#L200)):*
<details><summary><i>Previously, TarunUba1 (Tarun Uba) wrote…</i></summary><blockquote>

https://pmd.sourceforge.io/pmd-6.23.0/pmd_rules_java_performance.html#simplifystartswith
</blockquote></details>

PMD case was failing due to this change

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41317)* status: 3 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java` line 200 at r1](https://reviewable.io/reviews/harness/harness-core/41317#-NJ3nnlx8E7Gw9LB47zF:-NJ5116WCikq1kzIFr-l:b-idos2) ([raw file](https://github.com/harness/harness-core/blob/a0b45ef96fce8f5b568d32211e76f9a1ebf2fcd3/930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java#L200)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

This has been deprecated in the latest version of PMD!
> https://pmd.github.io/latest/pmd_rules_java_performance.html#simplifystartswith
> This rule is deprecated for removal, as the optimization is insignificant.
</blockquote></details>

I am fine with any approach. This is just a nit.
If you go with chartAt(), would you have to check if the filePath is empty or not?

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41317)* status: 3 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java` line 206 at r3](https://reviewable.io/reviews/harness/harness-core/41317#-NJ52_yaDi8ZTuST2BN4:-NJ52_yaDi8ZTuST2BN5:b-9lcgx2) ([raw file](https://github.com/harness/harness-core/blob/5dbac6fec492ec8581c487af5da27317e5bbec84/930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java#L206)):*
> ```Java
>         zipManifestFiles(pathToManifestFiles.toString(), destZippedManifestFile.toString());
>       } catch (Exception e) {
>         logCallback.saveExecutionLog(
> ```

let's use log.warn, no need to communicate this to user

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41317)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java` line 200 at r1](https://reviewable.io/reviews/harness/harness-core/41317#-NJ3nnlx8E7Gw9LB47zF:-NJ5SrYn4GIcwIBiLRyq:b-x2d339) ([raw file](https://github.com/harness/harness-core/blob/a0b45ef96fce8f5b568d32211e76f9a1ebf2fcd3/930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java#L200)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

I am fine with any approach. This is just a nit.
If you go with chartAt(), would you have to check if the filePath is empty or not?
</blockquote></details>

Actually My PMD test was failing with showing me this link, why it was failing. Just to get the check pass i reverted my changes😅
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java` line 206 at r3](https://reviewable.io/reviews/harness/harness-core/41317#-NJ52_yaDi8ZTuST2BN4:-NJ5Ujdx2OWoCcqBFFIw:b-9jwh5o) ([raw file](https://github.com/harness/harness-core/blob/5dbac6fec492ec8581c487af5da27317e5bbec84/930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java#L206)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

let's use log.warn, no need to communicate this to user
</blockquote></details>

Oh, i did changes to save log in this step, it was getting skipped as stream was getting closed before the call tot his method. Should i revert those changes as well?

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41317)* status: :shipit: complete! ✓

**Pull request merged**
