### PR TITLE
feat: [CDS-41884]: add Custom Artifact support to CommandStep NG

### PR DESCRIPTION
**Pull request by vitsafronovici**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36830)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36830)

**Review by acasian-harness — CHANGES_REQUESTED** [review]
@vitsafronovici we need to check for winrm copy command handler also.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36830#-:-NAOtgKW54BDD3Ht-Rml:bequlen)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java` line 120 at r1](https://reviewable.io/reviews/harness/harness-core/36830#-NAOtNNf26ly-3L1tr1L:-NAOtNNf26ly-3L1tr1M:b-6c0cp3) ([raw file](https://github.com/harness/harness-core/blob/e8f96a12d085bbd820a2eae2272fe9ccc70651cc/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java#L120)):*
> ```Java
>       }
>       if (sshCommandTaskParameters.getArtifactDelegateConfig() instanceof CustomArtifactDelegateConfig) {
>         throw new SshCommandExecutionException(COPY_ARTIFACT_NOT_SUPPORTED_FOR_CUSTOM_ARTIFACT);
> ```

Let's throw the exception with hint and explanation

**Review by vitsafronovici — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36830#-:-NAPUbZ0CF90NZ2s-yGU:bb7f2mf)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36830)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java` line 120 at r1](https://reviewable.io/reviews/harness/harness-core/36830#-NAOtNNf26ly-3L1tr1L:-NAPUhRa8xd7HtuIFOZm:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e8f96a12d085bbd820a2eae2272fe9ccc70651cc/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java#L120)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

Let's throw the exception with hint and explanation
</blockquote></details>

done

**Review by acasian-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36830)* status: :shipit: complete! ✓

**Comment by vitsafronovici** [comment]
trigger ti4

**Comment by vitsafronovici** [comment]
trigger compile

**Comment by vitsafronovici** [comment]
trigger ti0

**Comment by vitsafronovici** [comment]
trigger ti1

**Comment by vitsafronovici** [comment]
trigger ti3

**Comment by vitsafronovici** [comment]
trigger ti4

**Comment by vitsafronovici** [comment]
trigger ft1

**Comment by vitsafronovici** [comment]
trigger ft2

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36830)* status: :shipit: complete! ✓

**Review by acasian-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36830)* status: :shipit: complete! ✓

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 2 of 3 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36830)* status: :shipit: complete! ✓

**Comment by vitsafronovici** [comment]
trigger codebasehash

**Pull request merged**
