### PR TITLE
fix: [CDS-35786]: correctly parsing jira issue api

### PR DESCRIPTION
**Pull request by lasdox**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32020)

### CODE REVIEW

**Comment by lasdox** [comment]
trigger messagecheck

**Comment by lasdox** [comment]
trigger messagecheck

**Comment by lasdox** [comment]
trigger messagecheck

**Comment by lasdox** [comment]
trigger messagecheck

**Comment by lasdox** [comment]
trigger messagecheck

**Comment by lasdox** [comment]
trigger authorcheck

**Review by prabu-kr — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32020)* status: :shipit: complete! ✓

**Comment by lasdox** [comment]
trigger authorcheck

**Review by prabu-kr — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32020)* status: :shipit: complete! ✓

**Pull request merged**
