### PR TITLE
feat: [CDS-39175]: Implement slot deployment step with container based artifacts

### PR DESCRIPTION
**Pull request by abosii-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34919)

### CODE REVIEW

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 17 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34919)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/beans/AzureSlotDeploymentPassThroughData.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/34919#-N67GWAa5ouMkpaYOb7t:-N67GWAa5ouMkpaYOb7u:byks9yr) ([raw file](https://github.com/harness/harness-core/blob/1a3f6832bd7eea3e3872cdba9e29b19e4a6c0d4f/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/beans/AzureSlotDeploymentPassThroughData.java#L31)):*
> ```Java
> @RecasterAlias("io.harness.cdng.azure.webapp.beans.AzureSlotDeploymentPassThroughData")
> public class AzureSlotDeploymentPassThroughData implements PassThroughData {
>   InfrastructureOutcome infrastructure;
> ```

Do we use InfrastructureOutcome from passThroughData ?

**Review by tmacari-harness — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34919)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by abosii-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34919)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/beans/AzureSlotDeploymentPassThroughData.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/34919#-N67GWAa5ouMkpaYOb7t:-N68636S0fVZ9n2BiP3G:b-n0x3xn) ([raw file](https://github.com/harness/harness-core/blob/1a3f6832bd7eea3e3872cdba9e29b19e4a6c0d4f/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/beans/AzureSlotDeploymentPassThroughData.java#L31)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Do we use InfrastructureOutcome from passThroughData ?
</blockquote></details>

using now

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 18 files at r1, 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34919)* status: :shipit: complete! ✓

**Comment by abosii-harness** [comment]
trigger messagecheck

**Pull request merged**
