### PR TITLE
[feat]: [cds-44553]: Iterator Freeze initial commit

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38550)

### CODE REVIEW

**Comment by puthrayaharness** [comment]
Closing this stale PR. Please feel free to reopen.

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 5 of 7 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38550)* status: :shipit: complete! ✓

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38550)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
*[`125-freeze/src/main/java/io/harness/freeze/helpers/FreezeTimeUtils.java` line 155 at r5](https://reviewable.io/reviews/harness/harness-core/38550#-NJlDdkd3ZSI547yFjQk:-NJlDdkd3ZSI547yFjQl:b8569zk) ([raw file](https://github.com/harness/harness-core/blob/96b3ab755743559e7d4af1ac82e3bdea8e705fd8/125-freeze/src/main/java/io/harness/freeze/helpers/FreezeTimeUtils.java#L155)):*
> ```Java
>         until = LocalDateTime.parse(freezeWindow.getRecurrence().getSpec().getUntil(), dtf);
>       }
>       Long lastWindowEndTimeEpoch = getEpochValueFromDateString(until, timeZone);
> ```

non maintainable, unreadable, please improve



_Code quote:_
```Java
    if (freezeWindow.getEndTime() == null) {
      FreezeDuration freezeDuration = FreezeDuration.fromString(freezeWindow.getDuration());
      Long endTime = getEpochValueFromDateString(firstWindowStartTime, timeZone) + freezeDuration.getTimeoutInMillis();
      firstWindowEndTime = Instant.ofEpochMilli(endTime).atZone(timeZone.toZoneId()).toLocalDateTime();
    } else {
      firstWindowEndTime = LocalDateTime.parse(freezeWindow.getEndTime(), dtf);
    }
    if (freezeWindow.getRecurrence() == null) {
      if (getCurrentTime() > getEpochValueFromDateString(firstWindowEndTime, timeZone)) {
        return new ArrayList<>();
      } else {
        if (getCurrentTime() < getEpochValueFromDateString(firstWindowStartTime, timeZone)) {
          return Collections.singletonList(getEpochValueFromDateString(firstWindowStartTime, timeZone));
        }
        return new ArrayList<>();
      }
    } else {
      LocalDateTime until;
      if (freezeWindow.getRecurrence().getSpec() == null) {
        until = getLocalDateTime(RecurrenceType.YEARLY, firstWindowEndTime, 5);
      } else {
        until = LocalDateTime.parse(freezeWindow.getRecurrence().getSpec().getUntil(), dtf);
      }
      Long lastWindowEndTimeEpoch = getEpochValueFromDateString(until, timeZone);
      if (getCurrentTime() > lastWindowEndTimeEpoch) {
        return new ArrayList<>();
      } else {
        return fetchUpcomingTimeWindow(firstWindowStartTime, firstWindowEndTime, lastWindowEndTimeEpoch,
            freezeWindow.getRecurrence().getRecurrenceType(), timeZone);
      }
    }
  }
```

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38550)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-freeze/src/main/java/io/harness/freeze/helpers/FreezeTimeUtils.java` line 155 at r5](https://reviewable.io/reviews/harness/harness-core/38550#-NJlDdkd3ZSI547yFjQk:-NJnw9xoDTEqJxnbozth:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/96b3ab755743559e7d4af1ac82e3bdea8e705fd8/125-freeze/src/main/java/io/harness/freeze/helpers/FreezeTimeUtils.java#L155)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

non maintainable, unreadable, please improve
</blockquote></details>

Done

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38550)* status: 1. unresolved discussions.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r2, 4 of 7 files at r3, 1 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38550)* status: :shipit: complete! ✓

**Pull request merged**
