### PR TITLE
feat: [DEL-3329]: Implement account level perpetual task rebalance

### PR DESCRIPTION
**Pull request by Xin-Harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30926)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
___
*[420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java, line 199 at r1](https://reviewable.io/reviews/harness/harness-core/30926#-MwbyQWb8VLdlTmEZzOT:-MwbyQWb8VLdlTmEZzOU:b-zgg71w) ([raw file](https://github.com/harness/harness-core/blob/75348dd2c9b54a002f447baa5a6b16f742b977eb/420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java#L199)):*
> ```Java
>                                            .filter(PerpetualTaskRecordKeys.state, PerpetualTaskState.TASK_TO_REBALANCE);
> 
>     return query.asList(new FindOptions().limit(50));
> ```

make 50 as constant.

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java, line 126 at r1](https://reviewable.io/reviews/harness/harness-core/30926#-Mwbynee9UUnRB03rjl_:-Mwbynee9UUnRB03rjla:b2467yp) ([raw file](https://github.com/harness/harness-core/blob/75348dd2c9b54a002f447baa5a6b16f742b977eb/400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java#L126)):*
> ```Java
>         MongoPersistenceIterator.<Account, MorphiaFilterExpander<Account>>builder()
>             .clazz(Account.class)
>             .fieldName(Account.AccountKeys.perpetualTaskAccountLevelIteration)
> ```

perpetualTaskAccountLevelIteration should be an actual Long field in the Account class. check for other account level iterators how they do it

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java, line 196 at r1](https://reviewable.io/reviews/harness/harness-core/30926#-Mwbz3de0tMVx9-6-Vxr:-Mwbz3de0tMVx9-6-Vxs:b-e5khds) ([raw file](https://github.com/harness/harness-core/blob/75348dd2c9b54a002f447baa5a6b16f742b977eb/400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java#L196)):*
> ```Java
>   public void rebalance(Account account) {
>     List<PerpetualTaskRecord> perpetualTaskRecordList =
>         perpetualTaskRecordDao.listBatchOfPerpetualTasksToRebalanceForAccount(account.getAppId());
> ```

why are you passing account.getAppId() ?

**Review by Xin-Harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30926)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java, line 196 at r1](https://reviewable.io/reviews/harness/harness-core/30926#-Mwbz3de0tMVx9-6-Vxr:-Mwc1KvFDC2qflP0vQlR:b-ntd6pv) ([raw file](https://github.com/harness/harness-core/blob/75348dd2c9b54a002f447baa5a6b16f742b977eb/400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java#L196)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why are you passing account.getAppId() ?
</blockquote></details>

We need to retrieve the perpetual tasks with Task_to_rebalance state for specific account.

**Review by Xin-Harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30926)* status: 4 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java, line 126 at r1](https://reviewable.io/reviews/harness/harness-core/30926#-Mwbynee9UUnRB03rjl_:-MwcXt0v8Q0WwuEX64SG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/75348dd2c9b54a002f447baa5a6b16f742b977eb/400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java#L126)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

perpetualTaskAccountLevelIteration should be an actual Long field in the Account class. check for other account level iterators how they do it
</blockquote></details>

Done.
___
*[420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java, line 199 at r1](https://reviewable.io/reviews/harness/harness-core/30926#-MwbyQWb8VLdlTmEZzOT:-MwcXuc14f6JyaA0lNFZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/75348dd2c9b54a002f447baa5a6b16f742b977eb/420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java#L199)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

make 50 as constant. 
</blockquote></details>

Done.

**Comment by Xin-Harness** [comment]
Test it in my local, I have created 1000 pt tasks with different id with only 1 delegate running. Every 1 minute the batch of 20 pt tasks get assigned.
As you can see at the 18:01 local time, there are 180 task has TASK_ASSIGNED status
Pasted Graphic 19
As you can see at the 18:02 local time, there are 200 task has TASK_ASSIGNED status

Pasted Graphic 20
As you can see at the 18:07 local time, there are 300 task has TASK_ASSIGNED status

Pasted Graphic 21

**Comment by Xin-Harness** [comment]
trigger ti3

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/beans/Account.java, line 848 at r2](https://reviewable.io/reviews/harness/harness-core/30926#-Mwi_ZhX2tociz1YmP5o:-Mwi_ZhYEqKqK6oRP0CZ:byquu61) ([raw file](https://github.com/harness/harness-core/blob/7cb34293ac8431cca8694baac64cd6caafa55828/400-rest/src/main/java/software/wings/beans/Account.java#L848)):*
> ```Java
>     public static final String name = "name";
>     public static final String licenseExpiryCheckIteration = "licenseExpiryCheckIteration";
>     public static final String perpetualTaskRebalanceIteration = "perpetualTaskRebalanceIteration";
> ```

Do we need this?

**Review by raghuAtWings — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30926)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Comment by Xin-Harness** [comment]
trigger tin1

**Comment by Xin-Harness** [comment]
trigger tin1

**Comment by Xin-Harness** [comment]
trigger ti1

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 5 files at r2, 3 of 3 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30926)* status: :shipit: complete! ✓

**Pull request merged**
