### PR TITLE
fix: [CDS-49109]: publishing delete event in case of envionment while deletion of project/org

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
When we delete  org/proj ,we should publish delete event for environments.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43359)

### CODE REVIEW

**Review by tchaurasiya — COMMENTED** [review]
Lets update junit.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43359#-:-NNF_YNE1dFeKTbv7v4h:b-sv32h8)* status: 3 file(s) to review. 0 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43359)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
is this change related to environment groups or environments ? 
are we just publishing delete events for environments in case of cascaded deletion ?

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 378 at r1](https://reviewable.io/reviews/harness/harness-core/43359#-NNew-u8AHjzCDxw-_mW:-NNew-u912OAMZ9EIktH:b-j4vqzv) ([raw file](https://github.com/harness/harness-core/blob/6c3e0fe5c51a401fd878d32a01aabde59cd3df34/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L378)):*
> ```Java
>         if (isEmpty(environments)) {
>           return true;
>         }
> ```

we can return before calling transaction template itself if environments are empty

**Review by vivekkarnatiharness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43359)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 378 at r1](https://reviewable.io/reviews/harness/harness-core/43359#-NNew-u8AHjzCDxw-_mW:-NNjN3yg8Lt5rKmv1bdJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6c3e0fe5c51a401fd878d32a01aabde59cd3df34/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L378)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we can return before calling transaction template itself if environments are empty
</blockquote></details>

Done.

**Comment by vivekkarnatiharness** [comment]
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this change related to environment groups or environments ? 
are we just publishing delete events for environments in case of cascaded deletion ? 
</blockquote></details>

Yes,for now we are just publishing event. Will add deletion of refereed entities, once Environment is onboarded with setup usages.

**Comment by vivekkarnatiharness** [comment]
trigger TIAll-tin0

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43359)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by vivekkarnatiharness** [comment]
trigger tiAll

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43359)* status: :shipit: complete! ✓

**Pull request merged**
