### PR TITLE
feat:[CDS-76094]: Making Serverless Package and Deploy Step Independent

### PR DESCRIPTION
**Pull request by piyush-bhuwalka**
## Describe your changes

Making Serverless Package and Deploy Step Independent

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51365)

### CODE REVIEW

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Review by PragyeshMishra01 — DISMISSED** [review]

**Review by RishabhGupta34 — DISMISSED** [review]

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaPackageV2StepInfo.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/51365#-NbPQ8ESCkhO75vTIdvS:-NbPQ8ESCkhO75vTIdvT:b-iigz4a) ([raw file](https://github.com/harness/harness-core/blob/548a9db42de5b3d1f39b1844d564dbbd44a904db/125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaPackageV2StepInfo.java#L44)):*
> ```Java
> import lombok.Getter;
> import lombok.NoArgsConstructor;
> import net.minidev.json.annotate.JsonIgnore;
> ```

is this the right jsonIgnore ? should you not use the one from Jackson ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51365)* status: Some of the checks are too old. 12 file(s) to review.

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Comment by piyush-bhuwalka** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaPackageV2StepInfo.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/51365#-NbPQ8ESCkhO75vTIdvS:-NbPSWjC2DIUWyBmW5sA:b-25mmu6) ([raw file](https://github.com/harness/harness-core/blob/548a9db42de5b3d1f39b1844d564dbbd44a904db/125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaPackageV2StepInfo.java#L44)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this the right jsonIgnore ? should you not use the one from Jackson ?
</blockquote></details>

Yes, have corrected the change in the next commit

**Comment by piyush-bhuwalka** [comment]
trigger ut3, ut7, ut8

**Comment by piyush-bhuwalka** [comment]
trigger messagecheck

**Comment by piyush-bhuwalka** [comment]
trigger checkstylecodeformat

**Comment by piyush-bhuwalka** [comment]
trigger pmd

**Comment by piyush-bhuwalka** [comment]
trigger codebasehash

**Comment by piyush-bhuwalka** [comment]
trigger commonchecks

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 7 of 7 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51365)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by RishabhGupta34 — APPROVED** [review]

**Comment by piyush-bhuwalka** [comment]
trigger review

**Pull request merged**
