### PR TITLE
feat: [PL-29553]: Alternate to ACLs to determine access

### PR DESCRIPTION
**Pull request by reetika04**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40991)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40991)* status: Some of the checks are too old. 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java` line 110 at r1](https://reviewable.io/reviews/harness/harness-core/40991#-NJjNrQzElCzfbJw2W7E:-NJjNrQzElCzfbJw2W7F:bg82b8d) ([raw file](https://github.com/harness/harness-core/blob/a19b75d7cbf634f6a3ac5b717d8b6885ed2d686e/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java#L110)):*
> ```Java
>         Aggregation.unwind("resourceGroupInfo"), Aggregation.unwind("roleInfo"));
>     AggregationResults<RoleAssignmentAggregateDBO> results =
>         mongoTemplate.aggregate(aggregation, RoleAssignmentDBO.class, RoleAssignmentAggregateDBO.class);
> ```

Should we filter disabled role assignments?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/40991#-NJjPSNB7IL8sTg6EHOX:-NJjPSNB7IL8sTg6EHOY:bod34v1) ([raw file](https://github.com/harness/harness-core/blob/a19b75d7cbf634f6a3ac5b717d8b6885ed2d686e/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java#L114)):*
> ```Java
>     List<String> acls = new ArrayList<>();
>     for (RoleAssignmentAggregateDBO result : results)
>       for (String permission : result.getRoleInfo().getPermissions()) {
> ```

Should we push role filer in the aggregate query itself?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java` line 133 at r1](https://reviewable.io/reviews/harness/harness-core/40991#-NJjNvdr6Yc_qfvKO8cX:-NJjNvdr6Yc_qfvKO8cY:bp5lo2i) ([raw file](https://github.com/harness/harness-core/blob/a19b75d7cbf634f6a3ac5b717d8b6885ed2d686e/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java#L133)):*
> ```Java
> 
>   @Override
>   public List<PermissionCheckResult> checkAccessUsingRoleAssignments(Principal principal,
> ```

We got to make sure indexes are in place and are used from code. Otherwise queries will be very inefficient and approach will not help.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java` line 144 at r1](https://reviewable.io/reviews/harness/harness-core/40991#-NJjOQQq65pm7mZmVWTH:-NJjOQQq65pm7mZmVWTI:boaqiho) ([raw file](https://github.com/harness/harness-core/blob/a19b75d7cbf634f6a3ac5b717d8b6885ed2d686e/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java#L144)):*
> ```Java
>                                   .is(PrincipalType.USER);
>       principals.add(userCriteria);
>       userGroupDao.list(principal.getPrincipalIdentifier())
> ```

We should fetch only user group identifier and scope

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40991)* status: 11 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java` line 110 at r1](https://reviewable.io/reviews/harness/harness-core/40991#-NJjNrQzElCzfbJw2W7E:-NJy8Iro8-aY3cAPq8og:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a19b75d7cbf634f6a3ac5b717d8b6885ed2d686e/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java#L110)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we filter disabled role assignments?
</blockquote></details>

Done.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/40991#-NJjPSNB7IL8sTg6EHOX:-NJy8Kzz3tE5Sw6ahD9t:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a19b75d7cbf634f6a3ac5b717d8b6885ed2d686e/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java#L114)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we push role filer in the aggregate query itself?
</blockquote></details>

Done.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java` line 133 at r1](https://reviewable.io/reviews/harness/harness-core/40991#-NJjNvdr6Yc_qfvKO8cX:-NJy8LPE4Nsn65Yu6i4U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a19b75d7cbf634f6a3ac5b717d8b6885ed2d686e/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java#L133)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We got to make sure indexes are in place and are used from code. Otherwise queries will be very inefficient and approach will not help.
</blockquote></details>

Done.

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40991)* status: 11 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java` line 144 at r1](https://reviewable.io/reviews/harness/harness-core/40991#-NJjOQQq65pm7mZmVWTH:-NJy8PWCB20Kxw6GWDTN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a19b75d7cbf634f6a3ac5b717d8b6885ed2d686e/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java#L144)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We should fetch only user group identifier and scope
</blockquote></details>

Done.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40991)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 537 at r2](https://reviewable.io/reviews/harness/harness-core/40991#-NJyPHOI7r-objlfzLM0:-NJyPHOI7r-objlfzLM1:b3hb91s) ([raw file](https://github.com/harness/harness-core/blob/70c2bd58578e8d4062792fe4db7d087fedad6185/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L537)):*
> ```Java
>       "Avoid loading unnecessary support accounts unnecessarily. Enabling it will reduce memory pressure",
>       HarnessTeam.PL),
>   SIMPLIFY_ACL_CHECK("Simplifying ACL check", HarnessTeam.PL),
> ```

Lets expand this a bit more and mention the kind of simplification
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java` line 144 at r1](https://reviewable.io/reviews/harness/harness-core/40991#-NJjOQQq65pm7mZmVWTH:-NJyQMyi2Ar7kh3s06y_:bt3gile) ([raw file](https://github.com/harness/harness-core/blob/a19b75d7cbf634f6a3ac5b717d8b6885ed2d686e/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java#L144)):*
<details><summary><i>Previously, reetika04 (Reetika) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see only userGroupIdentifier and scope being projected while listing user groups
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/RoleAssignmentDBO.java` line 144 at r2](https://reviewable.io/reviews/harness/harness-core/40991#-NJyP1W9DRPT3GdB3yfr:-NJyP1W9DRPT3GdB3yfs:b-h4952w) ([raw file](https://github.com/harness/harness-core/blob/70c2bd58578e8d4062792fe4db7d087fedad6185/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/RoleAssignmentDBO.java#L144)):*
> ```Java
>                  .field(RoleAssignmentDBOKeys.principalType)
>                  .build())
>         .add(CompoundMongoIndex.builder()
> ```

You don't need this index if we are creating userGroupPrincipalIndex

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40991)* status: 11 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 537 at r2](https://reviewable.io/reviews/harness/harness-core/40991#-NJyPHOI7r-objlfzLM0:-NJybY8CBTbZcE3bBCMT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/70c2bd58578e8d4062792fe4db7d087fedad6185/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L537)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Lets expand this a bit more and mention the kind of simplification
</blockquote></details>

Done.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/RoleAssignmentDBO.java` line 144 at r2](https://reviewable.io/reviews/harness/harness-core/40991#-NJyP1W9DRPT3GdB3yfr:-NJybZOI30C2dafDFYLY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/70c2bd58578e8d4062792fe4db7d087fedad6185/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/RoleAssignmentDBO.java#L144)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

You don't need this index if we are creating userGroupPrincipalIndex
</blockquote></details>

Done.

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40991#-:-NJyvMlX79ZzS3rNE86u:bnfp4nl)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40991)* status: Some of the checks are too old. 11 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java` line 87 at r3](https://reviewable.io/reviews/harness/harness-core/40991#-NKEZkpP52PfepcHul9v:-NKEZkpP52PfepcHul9w:bhtwvkn) ([raw file](https://github.com/harness/harness-core/blob/a003ca6f4ab8fec882972dd0d871e35209160d2d/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java#L87)):*
> ```Java
>   }
> 
>   private Set<ResourceSelector> getResourceSelectorsFromRoleAssignment(ResourceGroupDBO resourceGroup) {
> ```

Correct name getResourceSelectorsFromRoleAssignment

**Review by Jimit09Gandhi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40991)* status: Some of the checks are too old. 11 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40991)* status: Some of the checks are too old. 11 file(s) to review.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 3 of 6 files at r2, 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40991)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40991#-:-NKHJNHw2lt4qFXRElpG:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
