### PR TITLE
feat: [CDS-37171]: Added inline ConfigFile

### PR DESCRIPTION
**Pull request by ivan-83**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33227)

### CODE REVIEW

**Comment by ivan-83** [comment]
trigger messagecheck

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 20 of 42 files at r1, 32 of 42 files at r2, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33227)* status: 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFileStep.java` line 54 at r3](https://reviewable.io/reviews/harness/harness-core/33227#-N2jcGu25NDZi2ZMelGN:-N2jcGu3DWW4ZalCM21L:bi34rjy) ([raw file](https://github.com/harness/harness-core/blob/9f0a4dbac5add7eeb555013eae659cbea0ee08c1/125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFileStep.java#L54)):*
> ```Java
> @Singleton
> @Slf4j
> public class ConfigFileStep implements SyncExecutable<ConfigFileStepParameters> {
> ```

i think it should be `SyncExecutableWithRbac`
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFileStep.java` line 135 at r3](https://reviewable.io/reviews/harness/harness-core/33227#-N2jdEv9-AxybKqngwgX:-N2jdEv9-AxybKqngwgY:bh6vbau) ([raw file](https://github.com/harness/harness-core/blob/9f0a4dbac5add7eeb555013eae659cbea0ee08c1/125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFileStep.java#L135)):*
> ```Java
>     String fileIdentifierRef = harnessStoreConfig.getFileReference().getValue();
>     NGAccess ngAccess = AmbianceUtils.getNgAccess(ambiance);
>     IdentifierRefHelper.getIdentifierRef(fileIdentifierRef, ngAccess.getAccountIdentifier(),
> ```

not getting this validation, shall we load the file and check if it exists here?

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33227)* status: 12 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFileStep.java` line 54 at r3](https://reviewable.io/reviews/harness/harness-core/33227#-N2jcGu25NDZi2ZMelGN:-N2jxkGw3xPV4a-ENJqP:behjefi) ([raw file](https://github.com/harness/harness-core/blob/9f0a4dbac5add7eeb555013eae659cbea0ee08c1/125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFileStep.java#L54)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

i think it should be `SyncExecutableWithRbac`
</blockquote></details>

We are using SyncExecutable for ManifestStep and TaskExecutable for ArtifactStep, we implemented the same approach and for ConfigFileStep.However if we still need SyncExecutableWithRbac we can do that. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFileStep.java` line 135 at r3](https://reviewable.io/reviews/harness/harness-core/33227#-N2jdEv9-AxybKqngwgX:-N2jwQ8BAPppHiSpKyM_:b-kj4wcj) ([raw file](https://github.com/harness/harness-core/blob/9f0a4dbac5add7eeb555013eae659cbea0ee08c1/125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFileStep.java#L135)):*
> not getting this validation, shall we load the file and check if it exists here?
Right, this will be done as part of @vladimir-peric PR.

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33227)* status: :shipit: complete! ✓

**Comment by ivan-83** [comment]
trigger ti0

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33227)* status: 37 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/orchestration/NgStepRegistrar.java` line 114 at r5](https://reviewable.io/reviews/harness/harness-core/33227#-N2tnxx-8ewIpajywm0Y:-N2v8bEm4oEFEB5Vqmhz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9e9fe102f8f454c74122cecb81f2ee8ae611390d/125-cd-nextgen/src/main/java/io/harness/cdng/orchestration/NgStepRegistrar.java#L114)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can be renamed to Individual Config file step
</blockquote></details>

Done.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 33 of 34 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33227)* status: 1 change requests. 1. unresolved discussions.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 12 files at r4, 1 of 34 files at r5, 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33227)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33227)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/orchestration/NgStepRegistrar.java` line 114 at r5](https://reviewable.io/reviews/harness/harness-core/33227#-N2tnxx-8ewIpajywm0Y:-N2vNh-XEg8qIpdBK63K:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9e9fe102f8f454c74122cecb81f2ee8ae611390d/125-cd-nextgen/src/main/java/io/harness/cdng/orchestration/NgStepRegistrar.java#L114)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

done

**Pull request merged**
