### PR TITLE
[feat]: [CDS-84609]: CRUD operations for webhooks at org and project level

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added code to support CURD and list operations for webhooks at org and project level. Have tested out the CRUD and listing operations of webhooks and events. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55494)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55494)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/gitxwebhook/OrgGitXWebhooksApiImpl.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/55494#-NjRdrOPEIj2wwGDhGhq:-NjRdrOPEIj2wwGDhGhr:bvc6xrd) ([raw file](https://github.com/harness/harness-core/blob/25f295476f9891a8d4cfdd7049fd6e1b02183590/120-ng-manager/src/main/java/io/harness/ng/gitxwebhook/OrgGitXWebhooksApiImpl.java#L56)):*
> ```Java
>   GitXWebhookService gitXWebhookService;
>   GitXWebhookEventService gitXWebhookEventService;
>   private final int HTTP_201 = 201;
> ```

can't we use these constants from a common place?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55494)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/GitXEventsListRequestDTO.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/55494#-NjReBAJ4_c28KqwidLB:-NjReBAJ4_c28KqwidLC:b63im7f) ([raw file](https://github.com/harness/harness-core/blob/25f295476f9891a8d4cfdd7049fd6e1b02183590/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/GitXEventsListRequestDTO.java#L41)):*
> ```Java
>   String eventIdentifier;
>   List<String> eventStatus;
>   Scope scope;
> ```

can we keep the positioning of scope as the first param itself. it just helps to make it more intuitive to read code.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55494)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/loggers/GitXWebhookLogContext.java` line 81 at r2](https://reviewable.io/reviews/harness/harness-core/55494#-NjReKCJ9lqbI8sBHxuA:-NjReKCJ9lqbI8sBHxuB:bk1gc55) ([raw file](https://github.com/harness/harness-core/blob/25f295476f9891a8d4cfdd7049fd6e1b02183590/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/loggers/GitXWebhookLogContext.java#L81)):*
> ```Java
>     Map<String, String> logContextMap = new HashMap<>();
>     setContextIfNotNull(logContextMap, ACCOUNT_KEY, scope.getAccountIdentifier());
>     setContextIfNotNull(logContextMap, ORG_KEY, scope.getOrgIdentifier());
> ```

lets not put org and project if its null. I'm guessing if we set it then it would start coming as null in the logs.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55494)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/mapper/GitXWebhookMapper.java` line 149 at r2](https://reviewable.io/reviews/harness/harness-core/55494#-NjRfHqBBIYMMx5e5TuA:-NjRfHqBBIYMMx5e5TuB:be3jy5b) ([raw file](https://github.com/harness/harness-core/blob/25f295476f9891a8d4cfdd7049fd6e1b02183590/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/mapper/GitXWebhookMapper.java#L149)):*
> ```Java
>   public GitXEventsListRequestDTO buildEventsListGitXWebhookRequestDTO(String webhookIdentifier, Long eventStartTime,
>       Long eventEndTime, String repoName, String filePath, String eventIdentifier, List<String> eventStatus,
>       Scope scope) {
> ```

lets keep scope as first argument itself, we just replace account identifier with scope, thats it.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55494)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/beans/scope/Scope.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/55494#-NjRg9h98blcMKnExc_Z:-NjRg9h98blcMKnExc__:bo6p8ip) ([raw file](https://github.com/harness/harness-core/blob/25f295476f9891a8d4cfdd7049fd6e1b02183590/970-ng-commons/src/main/java/io/harness/beans/scope/Scope.java#L59)):*
> ```Java
>         .accountIdentifier(accountIdentifier)
>         .orgIdentifier(orgIdentifier)
>         .projectIdentifier(null)
> ```

I think you don't need to mention projectIdentifier itself

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55494)* status: 19 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/gitxwebhook/OrgGitXWebhooksApiImpl.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/55494#-NjRdrOPEIj2wwGDhGhq:-NjRk1hpCoycoCmymInV:bwfx9kj) ([raw file](https://github.com/harness/harness-core/blob/25f295476f9891a8d4cfdd7049fd6e1b02183590/120-ng-manager/src/main/java/io/harness/ng/gitxwebhook/OrgGitXWebhooksApiImpl.java#L56)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can't we use these constants from a common place?
</blockquote></details>

agreed, done
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/GitXEventsListRequestDTO.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/55494#-NjReBAJ4_c28KqwidLB:-NjRiCPe9-Ua0VDcrUV7:byh0y4d) ([raw file](https://github.com/harness/harness-core/blob/25f295476f9891a8d4cfdd7049fd6e1b02183590/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/GitXEventsListRequestDTO.java#L41)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we keep the positioning of scope as the first param itself. it just helps to make it more intuitive to read code.
</blockquote></details>

moved it
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/loggers/GitXWebhookLogContext.java` line 81 at r2](https://reviewable.io/reviews/harness/harness-core/55494#-NjReKCJ9lqbI8sBHxuA:-NjRiXjI2YINRFlm5d6b:bdm476z) ([raw file](https://github.com/harness/harness-core/blob/25f295476f9891a8d4cfdd7049fd6e1b02183590/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/loggers/GitXWebhookLogContext.java#L81)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets not put org and project if its null. I'm guessing if we set it then it would start coming as null in the logs.
</blockquote></details>

we are checking and adding the value if its not null
private static void setContextIfNotNull(Map<String, String> logContextMap, String key, String value) {  
  if (isNotEmpty(value)) {  
    logContextMap.putIfAbsent(key, value);  
  }  
}
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/mapper/GitXWebhookMapper.java` line 149 at r2](https://reviewable.io/reviews/harness/harness-core/55494#-NjRfHqBBIYMMx5e5TuA:-NjRjJTe22bKIY_jjR--:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/25f295476f9891a8d4cfdd7049fd6e1b02183590/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/mapper/GitXWebhookMapper.java#L149)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets keep scope as first argument itself, we just replace account identifier with scope, thats it.
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/beans/scope/Scope.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/55494#-NjRg9h98blcMKnExc_Z:-NjRjQG10kmYtQFgpcQS:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/25f295476f9891a8d4cfdd7049fd6e1b02183590/970-ng-commons/src/main/java/io/harness/beans/scope/Scope.java#L59)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think you don't need to mention projectIdentifier itself
</blockquote></details>

removed

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 8 of 19 files at r1, 1 of 1 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55494)* status: 19 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55494)* status: 19 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
