### PR TITLE
[fix]: [PL-15022]: added DOMAIN_WHITELIST exception in saml-login API

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
added DOMAIN_WHITELIST exception in saml-login API

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41843)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger smartchecks

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 514 at r3](https://reviewable.io/reviews/harness/harness-core/41843#-NJyCNwq1pHp4u9Ok0WY:-NJyCNwq1pHp4u9Ok0WZ:baxug6g) ([raw file](https://github.com/harness/harness-core/blob/284597cbb8b626fb90d721b2bbcf4588805ae004/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L514)):*
> ```Java
>         return Response.seeOther(redirectUrl).build();
>       } else if (e.getCode() == ErrorCode.DOMAIN_WHITELIST_FILTER_CHECK_FAILED) {
>         throw new WingsException(DOMAIN_WHITELIST_FILTER_CHECK_FAILED, USER);
> ```

minor: we should also log error and then throw



_Code quote:_
```Java
      } else if (e.getCode() == ErrorCode.DOMAIN_WHITELIST_FILTER_CHECK_FAILED) {
        throw new WingsException(DOMAIN_WHITELIST_FILTER_CHECK_FAILED, USER);
```

**Review by pbarapatre10 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41843)* status: 4 file(s) to review. 0 of 2 approvals obtained.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41843)* status: 4 file(s) to review. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/resources/response_messages.properties` line 209 at r3](https://reviewable.io/reviews/harness/harness-core/41843#-NJyCxgX9cu-4kZS6-67:-NJyIzxaEkms4Q8466fa:byaw7ds) ([raw file](https://github.com/harness/harness-core/blob/284597cbb8b626fb90d721b2bbcf4588805ae004/980-commons/src/main/resources/response_messages.properties#L209)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor: This message seems very generic & doesn't hint anything about Domain whitelist. Is it intended?
</blockquote></details>

this came directly from Kapil Digani, pls refer confirmation on the ticket https://harness.atlassian.net/browse/PL-15022?focusedCommentId=397100

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41843)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41843)* status: :shipit: complete! ✓

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41843)* status: :shipit: complete! ✓

**Pull request merged**
