### PR TITLE
[feat]: [CDS-67263]: Integrating create and update pipeline api with setup usage creation

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have integrated the create and update pipeline api with setup usage creation. Have tested out the following for gitX enabled project:
1. 	inline pipeline:
- create: should create setup usage 
- update: should update setup usage
2. 	remote pipeline:
- create: not create setup usage for any branch 
- update:	not update setup usage for any branch 
- import: not create setup usage for any branch 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48577)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48577)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java` line 218 at r1](https://reviewable.io/reviews/harness/harness-core/48577#-NWlL6C50byETthQRxiX:-NWlL6C50byETthQRxiY:b-8n8my8) ([raw file](https://github.com/harness/harness-core/blob/7fad750b79ef35a26017f29ce73bd812220f23d2/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java#L218)):*
> ```Java
>       GitEntityInfo gitEntityInfo = GitContextHelper.getGitEntityInfo();
>       if (gitEntityInfo != null) {
>         if (StoreType.INLINE.equals(gitEntityInfo.getStoreType())) {
> ```

why are we doing storeType comparison from context? It should be done from pipeline entity.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java` line 144 at r1](https://reviewable.io/reviews/harness/harness-core/48577#-NWlMvCd2ama5hzBApuj:-NWlMvCd2ama5hzBApuk:b-ef0bdn) ([raw file](https://github.com/harness/harness-core/blob/7fad750b79ef35a26017f29ce73bd812220f23d2/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java#L144)):*
> ```Java
>   }
> 
>   public void publishSetupUsageEvent(
> ```

I have a ques here: Is this method also called from background thread?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/48577#-NWvk_l3EtZbZ0-5honG:-NWvk_l3EtZbZ0-5honH:b7or4qy) ([raw file](https://github.com/harness/harness-core/blob/38aa10ab2aae38cc583fcbb355a9927f860de6f6/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java#L79)):*
> ```Java
>   @Inject private EntitySetupUsageClient entitySetupUsageClient;
>   @Inject private InternalReferredEntityExtractor internalReferredEntityExtractor;
>   @Inject private GitSyncSdkService gitSyncSdkService;
> ```

we don't need it anymore right?

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48577)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger uts

**Review by ankittiwari-harness — APPROVED** [review]

**Pull request merged**
