### PR TITLE
feat: [PIE-1842]: Improve error message for /pipeline/execute/interru…

### PR DESCRIPTION
**Pull request by prashantsharma04**
…pt/{planExecutionId}/{nodeExecutionId} api when nodeExecutionId is wrong

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30365)

### CODE REVIEW

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30365)* status: 1 file(s) to review. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java, line 534 at r1](https://reviewable.io/reviews/harness/harness-core/30365#-MuiqqEtCaf-mUiE2b_M:-MuiqqEtCaf-mUiE2b_N:b-7a9y2v) ([raw file](https://github.com/harness/harness-core/blob/8c7b30b787ce552f255953a5d4b8bcbfab237aa0/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L534)):*
> ```Java
>   }
> 
>   private void validatePathParameters(String planExecutionId, String nodeExecutionId) {
> ```

this check should be inside pmsExecutionService as someone can call the service directly as well.

@sahilhindwani-harness Is there some perf-optimization possible here? Are these DB queries really needed here?

**Comment by sahilhindwani-harness** [comment]
___
*[800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java, line 534 at r1](https://reviewable.io/reviews/harness/harness-core/30365#-MuiqqEtCaf-mUiE2b_M:-MuiueIkE7EaXL-IPk1u:b-alyccj) ([raw file](https://github.com/harness/harness-core/blob/8c7b30b787ce552f255953a5d4b8bcbfab237aa0/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L534)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

this check should be inside pmsExecutionService as someone can call the service directly as well.

@sahilhindwani-harness Is there some perf-optimization possible here? Are these DB queries really needed here?
</blockquote></details>

Yes @vaibhav-si , we can optimize this I believe. Rather than calling both planExecution and nodeExecution, we can call only nodeExecution (because if it exists then the planExecution should also exist). Also we should call mongoTemplate#exists rather than the get call since we only want to validate if it exists or not.

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30365)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java, line 534 at r1](https://reviewable.io/reviews/harness/harness-core/30365#-MuiqqEtCaf-mUiE2b_M:-MuiulnY-CuJfmpaGi6c:b-aae52m) ([raw file](https://github.com/harness/harness-core/blob/8c7b30b787ce552f255953a5d4b8bcbfab237aa0/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L534)):*
> this check should be inside pmsExecutionService as someone can call the service directly as well.
@vaibhav-si we already have a check while fetching planExecutionId or nodeExecutionId.

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30365)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java, line 534 at r1](https://reviewable.io/reviews/harness/harness-core/30365#-MuiqqEtCaf-mUiE2b_M:-Muj-8tA5qN7dJrIXQzm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8c7b30b787ce552f255953a5d4b8bcbfab237aa0/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L534)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

> this check should be inside pmsExecutionService as someone can call the service directly as well.
@vaibhav-si we already have a check while fetching planExecutionId or nodeExecutionId.
</blockquote></details>

Done.

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30365)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java, line 609 at r2](https://reviewable.io/reviews/harness/harness-core/30365#-MujWQGLCwZORidwXs9G:-MujWQGLCwZORidwXs9H:b-rojkqf) ([raw file](https://github.com/harness/harness-core/blob/c5660fc1e0bf82fe89ef9137b3ab8502167504c2/870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L609)):*
> ```Java
> 
>   @Override
>   public boolean ifExists(String nodeExecutionId) {
> ```

can we add a UT for this using in-memory DB?

**Comment by sahilhindwani-harness** [comment]
___
*[800-pipeline-service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java, line 292 at r3](https://reviewable.io/reviews/harness/harness-core/30365#-Mujbh9Q6KUUnpYEffBG:-Mujbh9Q6KUUnpYEffBH:b-lkdwfs) ([raw file](https://github.com/harness/harness-core/blob/9472231a8990b75b5c9362712031be1224ab8fbe/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L292)):*
> ```Java
>   public InterruptDTO registerInterrupt(
>       PlanExecutionInterruptType executionInterruptType, String planExecutionId, String nodeExecutionId) {
>     if (!nodeExecutionService.ifExists(nodeExecutionId)) {
> ```

There can be a chance that the interrupt is a plan level interrupt and no nodeExecutionId is there, could you please check that case too?

**Review by vaibhav-si — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30365)* status: 4 file(s) to review. 0 of 2 approvals obtained.

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30365)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java, line 292 at r3](https://reviewable.io/reviews/harness/harness-core/30365#-Mujbh9Q6KUUnpYEffBG:-MukWTSr71prgH19F0u7:b-ggcyiw) ([raw file](https://github.com/harness/harness-core/blob/9472231a8990b75b5c9362712031be1224ab8fbe/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L292)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

There can be a chance that the interrupt is a plan level interrupt and no nodeExecutionId is there, could you please check that case too?
</blockquote></details>

We already have a not null check for node execution id. This api won't get triggered if during plan formation we have the interrupt. @sahilhindwani-harness do think we can have any other case for this scenario

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30365)* status: 5 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java, line 609 at r2](https://reviewable.io/reviews/harness/harness-core/30365#-MujWQGLCwZORidwXs9G:-Muos6vj8cUusHFOp2rt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c5660fc1e0bf82fe89ef9137b3ab8502167504c2/870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L609)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

can we add a UT for this using in-memory DB?
</blockquote></details>

Done.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 2 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30365)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30365)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30365#-:-Mut8WCG5J58oUD7-Yzp:bnfp4nl)* status: 1 file(s) to review.

**Review by namanvermah — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30365)* status: :shipit: complete! ✓

**Review by namanvermah — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30365#-:-MutB1GJAp-L41wc-zk4:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
