### PR TITLE
fix: [DEL-5268]: if validation task is null then mark task as invalid

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
- If the validation task is null, then do not go ahead with the assignment process and mark the task as invalid state.
- WingsApplication.java : Remove non-delegate-related observers from the heartbeat observer register.
- DelegateObserver.java: Moved logic on PT reset task to OnReconnect() instead of onAdded() since onAdded already have CE related implementation.
- Fix NPE on fail task iterator
- Fix issue of not getting correct last recorded heartbeat

Test
- Sanity test on PT end-to-end flow
-Test observer flow with existing and new delegate added

## Checklist
- [ x] I've documented the changes in the PR description.
- [ x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39378)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1389 at r2](https://reviewable.io/reviews/harness/harness-core/39378#-NFbOfbE-d58m8JuNLMZ:-NFbOfbE-d58m8JuNLM_:b-mu3kxj) ([raw file](https://github.com/harness/harness-core/blob/e58e96f23276f95cb6a194d26dfbf7190ef0f6d0/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1389)):*
> ```Java
> 
>     KubernetesClusterHandler kubernetesClusterHandler = injector.getInstance(Key.get(KubernetesClusterHandler.class));
>     delegatePollingHeartbeatService.getSubject().register(kubernetesClusterHandler);
> ```

don't understand this change, can you please describe.

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java` line 389 at r2](https://reviewable.io/reviews/harness/harness-core/39378#-NFbPBOyB6ldNHv3n3Px:-NFbPBOyB6ldNHv3n3Py:boyg9v4) ([raw file](https://github.com/harness/harness-core/blob/f5eb65bf8378e364f31e7caa80d57d6aa3027485/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L389)):*
> ```Java
>   public void onReconnected(Delegate delegate) {
>     log.info("Delegate reconnected/added for account {} delegateId {}", delegate.getAccountId(), delegate.getUuid());
>     perpetualTaskRecordDao.updateTaskNonAssignableToAssignable(delegate.getAccountId());
> ```

wouldn't this get called when the same delegate disconnects for a few seconds and then reconnect?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39378)* status: 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java` line 389 at r2](https://reviewable.io/reviews/harness/harness-core/39378#-NFbPBOyB6ldNHv3n3Px:-NFefUt40tVzXL2cEdcn:bftkfuz) ([raw file](https://github.com/harness/harness-core/blob/f5eb65bf8378e364f31e7caa80d57d6aa3027485/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L389)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

wouldn't this get called when the same delegate disconnects for a few seconds and then reconnect? 
</blockquote></details>

no onReconnected event only when HB is more than 5 mins

**Comment by jennyjames21** [comment]
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1389 at r2](https://reviewable.io/reviews/harness/harness-core/39378#-NFbOfbE-d58m8JuNLMZ:-NFefc6k2CPEjNJ7t_Pz:bti2kq1) ([raw file](https://github.com/harness/harness-core/blob/e58e96f23276f95cb6a194d26dfbf7190ef0f6d0/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1389)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

don't understand this change, can you please describe. 
</blockquote></details>

XingChi recently added this, to make new class to use Delegate::Observer. We dont need kubernetesClusterHandler for this flow.

**Comment by jennyjames21** [comment]
trigger messagecheck

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39378)* status: :shipit: complete! ✓

**Pull request merged**
