### PR TITLE
feat: [CDS-46524]: Added support for config file built in variable

### PR DESCRIPTION
**Pull request by ivan-83**
## Describe your changes

Added support for configFile.getAsString and configFile.getAsBase64 buit-in methods

Examples
File from File Store
`<+configFile.getAsString("account:/folder1/yamlFile.yaml")>`  >> file account level
`<+configFile.getAsString("org:/folder1/yamlFile.yaml")>`   >> file org level
`<+configFile.getAsString("/folder1/yamlFile.yaml")>`  >> file project level

Secret File from Secret Manager
`<+configFile.getAsString("account.MySecretFile")>`  >> secret account level
`<+configFile.getAsString("org.MySecretFile")>`   >> secret org level
`<+configFile.getAsString("MySecretFile")> ` >> secret project level

The same and for getAsBase64 method.

Code changes include:

- `ConfigFileRemoteExpressionFunctor` is added because the existing `RemoteExpressionFunctor` only sends the first `getAsString` or `getAsBase64` argument to SDK functors.
- `ConfigFileFunctor` is added as a new SDK functor it will return the content for files but for secrets, it will only prepare the expression that will be evaluated by `NgSecretManagerFunctor`.
- `NgSecretManagerFunctor` will evaluate the Harness local secrets, and other types like KMS, GCP_KMS ... will be evaluated on the delegate.
- Secret masking works for `getAsBase64(secretIdentifier)` and `getAsString(secretIdentifier)`

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42823)

### CODE REVIEW

**Comment by ivan-83** [comment]
trigger messagecheck

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42823)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Comment by ivan-83** [comment]
trigger publish-delegate

**Comment by ivan-83** [comment]
trigger ft1

**Comment by ivan-83** [comment]
trigger publish-delegate

**Review by yogesh-chauhan — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 11 files at r1, 3 of 6 files at r2, 1 of 2 files at r3, 5 of 9 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42823)* status: Some of the checks are too old. 13 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42823)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, 3 of 6 files at r2, 1 of 2 files at r3, 4 of 9 files at r4, 4 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42823)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/expression/NgSecretManagerFunctor.java` line 281 at r6](https://reviewable.io/reviews/harness/harness-core/42823#-NN1eZAG3Kupan7FWdw1:-NN1eZAHEGwUKejJxU5n:b-gblult) ([raw file](https://github.com/harness/harness-core/blob/85e956cb82a1b04bf9d2ef82bcc90a5da9eb1fa0/400-rest/src/main/java/software/wings/expression/NgSecretManagerFunctor.java#L281)):*
> ```Java
>   }
> 
>   private Object obtainInternalBase64(String secretIdentifier, SecretVariableDTO.Type secretType) {
> ```

Feels like there is a lot of code duplication here. Can the old obtainInternal be reused with some flag for base64, or if that would produce too many branches, maybe have them separate like this but extract common code to separate methods and reuse in both obtainInternal & obtainInternalBase64
___
*[`980-commons/src/main/java/io/harness/utils/SecretUtils.java` line 40 at r6](https://reviewable.io/reviews/harness/harness-core/42823#-NN1fGSw51zBD5K7lSaI:-NN1fGSw51zBD5K7lSaJ:b-gr7lb2) ([raw file](https://github.com/harness/harness-core/blob/85e956cb82a1b04bf9d2ef82bcc90a5da9eb1fa0/980-commons/src/main/java/io/harness/utils/SecretUtils.java#L40)):*
> ```Java
> 
>   public static boolean isBase64SecretIdentifier(final String secretIdentifier) {
>     return secretIdentifier.startsWith(BASE_64_SECRET_IDENTIFIER_PREFIX);
> ```

This would compile regex pattern for each call which can be expensive especially since you invoke it from a loop. Compile regex pattern statically and use that instead.

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42823)* status: 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/expression/NgSecretManagerFunctor.java` line 281 at r6](https://reviewable.io/reviews/harness/harness-core/42823#-NN1eZAG3Kupan7FWdw1:-NN1lLvpDFq_D6cjynef:b-xk7oeb) ([raw file](https://github.com/harness/harness-core/blob/85e956cb82a1b04bf9d2ef82bcc90a5da9eb1fa0/400-rest/src/main/java/software/wings/expression/NgSecretManagerFunctor.java#L281)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Feels like there is a lot of code duplication here. Can the old obtainInternal be reused with some flag for base64, or if that would produce too many branches, maybe have them separate like this but extract common code to separate methods and reuse in both obtainInternal & obtainInternalBase64
</blockquote></details>

Yes, that's true, with the additional flag the obtainInternal method becomes more complex due to the fact that we have to modify each identifier before saving items in each map. We will have an additional 4 if/else due to need to update 4 maps. The method is so complex now without a flag.

If I start refactoring the base obtainInternal method the scope of testing will increase dramatically because in that case, we have to test <secret.getValue...> expressions for each swim line(AWS, K8S, Azure...), because of it I decided to pay the price of code duplication. 
___
*[`980-commons/src/main/java/io/harness/utils/SecretUtils.java` line 40 at r6](https://reviewable.io/reviews/harness/harness-core/42823#-NN1fGSw51zBD5K7lSaI:-NN1kXVQ6wVxKDWKuU72:beufij7) ([raw file](https://github.com/harness/harness-core/blob/85e956cb82a1b04bf9d2ef82bcc90a5da9eb1fa0/980-commons/src/main/java/io/harness/utils/SecretUtils.java#L40)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This would compile regex pattern for each call which can be expensive especially since you invoke it from a loop. Compile regex pattern statically and use that instead. 
</blockquote></details>

Hi @mdmilic 

Java startsWith doesn't support regular expressions it compares char by char at the position.

**Comment by ivan-83** [comment]
trigger ft1

**Review by mdmilic — APPROVED** [review]
Approve delegate owned changes

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42823#-:-NN2TCwZ1xKmUNkM4g6r:btbwd51)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, 3 of 6 files at r2, 1 of 2 files at r3, 3 of 9 files at r4, 3 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42823)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/expression/NgSecretManagerFunctor.java` line 342 at r6](https://reviewable.io/reviews/harness/harness-core/42823#-NN5FPze3nPe7rGnBvdh:-NN5FPzgCGHNxHrIEmJl:bv9wc2h) ([raw file](https://github.com/harness/harness-core/blob/85e956cb82a1b04bf9d2ef82bcc90a5da9eb1fa0/400-rest/src/main/java/software/wings/expression/NgSecretManagerFunctor.java#L342)):*
> ```Java
>       delegateMetricsService.recordDelegateMetricsPerAccount(accountId, SECRETS_CACHE_LOOKUPS);
>       EncryptedDataDetails cachedValue = secretsCache.get(String.valueOf(keyHash));
>       if (cachedValue != null) {
> ```

Should we keep all this logic in a single file? also please get approval from pl team for this file
___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/RemoteExpressionFunctor.java` line 78 at r6](https://reviewable.io/reviews/harness/harness-core/42823#-NN5Gcox-qm8RST1UA2-:-NN5Gcox-qm8RST1UA20:b-9nvtz6) ([raw file](https://github.com/harness/harness-core/blob/85e956cb82a1b04bf9d2ef82bcc90a5da9eb1fa0/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/RemoteExpressionFunctor.java#L78)):*
> ```Java
>   }
> 
>   public Object getAsString(String ref) {
> ```

can we revisit expressions format?

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42823)* status: 1 change requests. 1. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/expression/NgSecretManagerFunctor.java` line 342 at r6](https://reviewable.io/reviews/harness/harness-core/42823#-NN5FPze3nPe7rGnBvdh:-NN6kQoK2uN_gm1yFzSe:b-wfd026) ([raw file](https://github.com/harness/harness-core/blob/85e956cb82a1b04bf9d2ef82bcc90a5da9eb1fa0/400-rest/src/main/java/software/wings/expression/NgSecretManagerFunctor.java#L342)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Should we keep all this logic in a single file? also please get approval from pl team for this file
</blockquote></details>

@ankit-harness could you pls take a look at this file or someone from your team?

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42823)* status: 1 change requests. 2. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/expression/NgSecretManagerFunctor.java` line 342 at r6](https://reviewable.io/reviews/harness/harness-core/42823#-NN5FPze3nPe7rGnBvdh:-NN6yjmv3bYsl0TmQSAq:bb34908) ([raw file](https://github.com/harness/harness-core/blob/85e956cb82a1b04bf9d2ef82bcc90a5da9eb1fa0/400-rest/src/main/java/software/wings/expression/NgSecretManagerFunctor.java#L342)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

@ankit-harness could you pls take a look at this file or someone from your team? 
</blockquote></details>

@nishantsaini20  could you pls review this file?

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42823)* status: 1 change requests. 3. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/expression/NgSecretManagerFunctor.java` line 342 at r6](https://reviewable.io/reviews/harness/harness-core/42823#-NN5FPze3nPe7rGnBvdh:-NN7-dM6DKeCH5Uzrjac:bzcurx) ([raw file](https://github.com/harness/harness-core/blob/85e956cb82a1b04bf9d2ef82bcc90a5da9eb1fa0/400-rest/src/main/java/software/wings/expression/NgSecretManagerFunctor.java#L342)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

@nishantsaini20  could you pls review this file? 
</blockquote></details>

Hi @piyush-harness could you pls review this file?

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42823)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/RemoteExpressionFunctor.java` line 78 at r6](https://reviewable.io/reviews/harness/harness-core/42823#-NN5Gcox-qm8RST1UA2-:-NN8C-bl5BCUqZV-D6L-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/85e956cb82a1b04bf9d2ef82bcc90a5da9eb1fa0/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/RemoteExpressionFunctor.java#L78)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we revisit expressions format?
</blockquote></details>

Done.

**Review by mdmilic — APPROVED** [review]
> Reviewed 5 of 5 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42823)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 11 files at r1, 1 of 1 files at r6, 5 of 5 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42823)* status: :shipit: complete! ✓

**Pull request merged**
