### PR TITLE
feat: [DEL-2790]: Add per account immutable delegate overrides which auto expire

### PR DESCRIPTION
**Pull request by mdmilic**
I've extracted any version related operations to a new "Service" called DelegateVersionService. There are still some leftovers related to delegate.jar version in the DelegateServiceImpl which should be moved as well (I left it for after JDK11 upgrade to prevent potentially breaking it since we really need it soon)

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32063)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32063)* status: Some of the checks are too old. 20 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/io/harness/delegate/service/intfc/DelegateRingService.java, line 17 at r2](https://reviewable.io/reviews/harness/harness-core/32063#-N-NOO15DCLyM-idWswK:-N-NOO15DCLyM-idWswL:bx5vw50) ([raw file](https://github.com/harness/harness-core/blob/3075c21f73f90cb3a0293ffb1c1544b3df7adb0e/400-rest/src/main/java/io/harness/delegate/service/intfc/DelegateRingService.java#L17)):*
> ```Java
>   String getUpgraderImageTag(String accountId);
> 
>   List<String> getDelegateVersions(String accountId);
> ```

I and Raghu were discussion on this, we finalize on to keep delegateConfiguration in DelegateRing collection, so as to make it unique across accounts collection and delegateRing.
Also in future we can add/remove fields from delegateConfiguration without much changes. We can have fields like "jdk version" which will denote on which jre client has to run.


Similarly for watcher we can introduce watcherConfiguration.



_Code quote:_
```Java
  List<String> getDelegateVersions(String accountId);

  List<String> getWatcherVersions(String accountId);
```

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32063)* status: 20 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java, line 37 at r2](https://reviewable.io/reviews/harness/harness-core/32063#-MzueCRRlL5k58jMAZ7L-r2-37:-N-S__9M2U-IFXa0ipG3:b-8mka0n) ([raw file](https://github.com/harness/harness-core/blob/3075c21f73f90cb3a0293ffb1c1544b3df7adb0e/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java#L37)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

As are planning to have only one version of delegate in Delegate configuration.. And that's why we thought of converting List<String> to just String representing currently active delegate Version.
@raghuAtWings with delegateRing, shall we start following the practice of having one delegate version ?
</blockquote></details>

I agree it's good to have only one version and the list, but lets not block this PR on that. I'll create a ticket to do it next in a separate code change. The rings already had lists, I just exposed APIs to fetch them here. Also I created version overrides to match rings, but since jar overrides are not being used yet, it's not that important that they are lists
___
*[400-rest/src/main/java/io/harness/delegate/service/intfc/DelegateRingService.java, line 17 at r2](https://reviewable.io/reviews/harness/harness-core/32063#-N-NOO15DCLyM-idWswK:-N-SZ_yM6zBDWwdpFJi6:btlw8hp) ([raw file](https://github.com/harness/harness-core/blob/3075c21f73f90cb3a0293ffb1c1544b3df7adb0e/400-rest/src/main/java/io/harness/delegate/service/intfc/DelegateRingService.java#L17)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

I and Raghu were discussion on this, we finalize on to keep delegateConfiguration in DelegateRing collection, so as to make it unique across accounts collection and delegateRing.
Also in future we can add/remove fields from delegateConfiguration without much changes. We can have fields like "jdk version" which will denote on which jre client has to run.


Similarly for watcher we can introduce watcherConfiguration.
</blockquote></details>

I strongly disagree that we keep the entire delegateConfiguration in the Rings. DelegateConfiguration is bloated with a lot of unnecessary stuff, but also not going to be needed at all for immutable delegate (once properly migrated). We need to ditch the bad practices we used so far when designing our collections. Rings should remain being used for very specific purpose they are created for (to decide the version delegate is running and nothing else)

**Comment by raghuAtWings** [comment]
*[400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java, line 37 at r2](https://reviewable.io/reviews/harness/harness-core/32063#-MzueCRRlL5k58jMAZ7L-r2-37:-N-UaR1q5UK1XS2zNZiC:b-uloshh) ([raw file](https://github.com/harness/harness-core/blob/3075c21f73f90cb3a0293ffb1c1544b3df7adb0e/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java#L37)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I agree it's good to have only one version and the list, but lets not block this PR on that. I'll create a ticket to do it next in a separate code change. The rings already had lists, I just exposed APIs to fetch them here. Also I created version overrides to match rings, but since jar overrides are not being used yet, it's not that important that they are lists
</blockquote></details>

We can only use single version once we have watcher which just install a new delegate and kills the running one synchronously.

**Review by gaurav-jain1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32063)* status: 20 file(s) to review. 1. unresolved discussions. 

___
*[400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java, line 37 at r2](https://reviewable.io/reviews/harness/harness-core/32063#-MzueCRRlL5k58jMAZ7L-r2-37:-N-XIZvh6hGnnNNgyiHB:b-r511w) ([raw file](https://github.com/harness/harness-core/blob/3075c21f73f90cb3a0293ffb1c1544b3df7adb0e/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java#L37)):*
> ood to have only one version and the list, but lets not block this PR on that. I'll create a ticket to do it next in a separate code change. The rings already had lists, I j
yup, please create a JIRA both for watcher and delegate version.
___
*[400-rest/src/main/java/io/harness/delegate/service/intfc/DelegateRingService.java, line 17 at r2](https://reviewable.io/reviews/harness/harness-core/32063#-N-NOO15DCLyM-idWswK:-N-XIL3W8csd7c287Kro:br7wggj) ([raw file](https://github.com/harness/harness-core/blob/3075c21f73f90cb3a0293ffb1c1544b3df7adb0e/400-rest/src/main/java/io/harness/delegate/service/intfc/DelegateRingService.java#L17)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I strongly disagree that we keep the entire delegateConfiguration in the Rings. DelegateConfiguration is bloated with a lot of unnecessary stuff, but also not going to be needed at all for immutable delegate (once properly migrated). We need to ditch the bad practices we used so far when designing our collections. Rings should remain being used for very specific purpose they are created for (to decide the version delegate is running and nothing else)
</blockquote></details>

Hmm, just realised that we can control this via FeatureFlag like you did for jdk11 patch.

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32063)* status: 20 file(s) to review. 2. unresolved discussions. 

___
*[400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java, line 37 at r2](https://reviewable.io/reviews/harness/harness-core/32063#-MzueCRRlL5k58jMAZ7L-r2-37:-N-XYxpy55GHHuZtQ4fL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3075c21f73f90cb3a0293ffb1c1544b3df7adb0e/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java#L37)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

> ood to have only one version and the list, but lets not block this PR on that. I'll create a ticket to do it next in a separate code change. The rings already had lists, I j
yup, please create a JIRA both for watcher and delegate version.
</blockquote></details>

Done.
___
*[400-rest/src/main/java/io/harness/delegate/service/intfc/DelegateRingService.java, line 17 at r2](https://reviewable.io/reviews/harness/harness-core/32063#-N-NOO15DCLyM-idWswK:-N-XYxO7BsYZ28BYJbJg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3075c21f73f90cb3a0293ffb1c1544b3df7adb0e/400-rest/src/main/java/io/harness/delegate/service/intfc/DelegateRingService.java#L17)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Hmm, just realised that we can control this via FeatureFlag like you did for jdk11 patch. 
</blockquote></details>

Done.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 5 of 19 files at r1, 4 of 6 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32063)* status: :shipit: complete! ✓

**Pull request merged**
