### PR TITLE
feat: [CDS-38396]: runtime inputs APIs for env / infra / service overrides

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
1. Added APIs for getting runtime inputs yaml for these 3 entities: environment, infrastructure and service override
2. First get the appropriate yaml field, use RuntimeFormHelper to generate inputs yaml
3. Insert the resulting node to correct hierarchy and return its yaml
4. If no runtime inputs found, return null
5. Changed Service override config field to **variables**.
6. Fixed resources classpath for 127-cd-nextgen-entities 

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [X] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34086)

### CODE REVIEW

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34086)* status: 25 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java` line 194 at r1](https://reviewable.io/reviews/harness/harness-core/34086#-N40w_NW7NVi5p9l1uxn:-N40w_NW7NVi5p9l1uxo:b-8tolso) ([raw file](https://github.com/harness/harness-core/blob/ebea604f1bd99d039f7393cbe535a619464542b3/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java#L194)):*
> ```Java
>       }
>       try {
>         String serviceOverrideInputs = RuntimeInputFormHelper.createTemplateFromYaml(yaml);
> ```

we should not use template's function. You can either create one or change its name

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 24 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34086)* status: 1 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 303 at r1](https://reviewable.io/reviews/harness/harness-core/34086#-N475KWM3PlX-TXblArD:-N475KWM3PlX-TXblArE:b6z13b5) ([raw file](https://github.com/harness/harness-core/blob/ebea604f1bd99d039f7393cbe535a619464542b3/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L303)):*
> ```Java
>       String accountId, String orgIdentifier, String projectIdentifier, String envIdentifier) {
>     Map<String, Object> yamlInputs = new HashMap<>();
>     createEnvironmentInputsYamlInternal(accountId, orgIdentifier, projectIdentifier, envIdentifier, yamlInputs);
> ```

this method should return a new map instead of mutating its argument. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 259 at r1](https://reviewable.io/reviews/harness/harness-core/34086#-N475TgBEfKUYqJJKtJD:-N475TgBEfKUYqJJKtJE:b-1ma0oh) ([raw file](https://github.com/harness/harness-core/blob/ebea604f1bd99d039f7393cbe535a619464542b3/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L259)):*
> ```Java
>     Map<String, Object> yamlInputs = new HashMap<>();
>     createInfrastructureInputsYamlInternal(
>         accountId, orgIdentifier, projectIdentifier, environmentIdentifier, deployToAll, infraIdentifiers, yamlInputs);
> ```

this method should return a new map instead of mutating its argument

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34086)* status: 1 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/BUILD.bazel` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/34086#-N476_Ls5trODB4pS4yV:-N476_Ls5trODB4pS4yW:bs6xs4j) ([raw file](https://github.com/harness/harness-core/blob/ebea604f1bd99d039f7393cbe535a619464542b3/127-cd-nextgen-entities/BUILD.bazel#L37)):*
> ```Starlark
>     resources = ["//127-cd-nextgen-entities/src/test/resources:resource"],
>     visibility = ["//visibility:public"],
>     resources = ["//127-cd-nextgen-entities/src/test/resources:resource"],
> ```

this line is already added there in this target

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34086)* status: 6 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 303 at r1](https://reviewable.io/reviews/harness/harness-core/34086#-N475KWM3PlX-TXblArD:-N47HHh32oosWgMNXjkd:bszak5a) ([raw file](https://github.com/harness/harness-core/blob/ebea604f1bd99d039f7393cbe535a619464542b3/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L303)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this method should return a new map instead of mutating its argument. 
</blockquote></details>

Is it a bad practice to 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 259 at r1](https://reviewable.io/reviews/harness/harness-core/34086#-N475TgBEfKUYqJJKtJD:-N47Rvoz-GVnMKVxnmi1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ebea604f1bd99d039f7393cbe535a619464542b3/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L259)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this method should return a new map instead of mutating its argument
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java` line 194 at r1](https://reviewable.io/reviews/harness/harness-core/34086#-N40w_NW7NVi5p9l1uxn:-N47RzRm-qstHcOGVehJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ebea604f1bd99d039f7393cbe535a619464542b3/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java#L194)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

we should not use template's function. You can either create one or change its name
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/BUILD.bazel` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/34086#-N476_Ls5trODB4pS4yV:-N47S-PlEN_nOqQve1fQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ebea604f1bd99d039f7393cbe535a619464542b3/127-cd-nextgen-entities/BUILD.bazel#L37)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

this line is already added there in this target
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34086)* status: 1 change requests. 2. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34086)* status: 1 change requests. 2. unresolved discussions.

**Review by prashantsharma04 — COMMENTED** [review]
> Reviewed 15 of 25 files at r1, 6 of 6 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34086)* status: 1 change requests. 2. unresolved discussions.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34086#-:-N4AyLGa9-tRS6safzv0:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
