### PR TITLE
[feat]: [PIE-8807]: Added FF for AuditEvents

### PR DESCRIPTION
**Pull request by senjucanon2**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44826)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 647 at r1](https://reviewable.io/reviews/harness/harness-core/44826#-NPvqMwmEUoCAGd_NKA9:-NPvqMwmEUoCAGd_NKAA:b-ehdabn) ([raw file](https://github.com/harness/harness-core/blob/feb38fb41cb28779a6f765a09bb8a2c0e9fcfd96/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L647)):*
> ```Java
>   CHAOS_SRM_EVENT(
>       "Enables chaos events to be displayed as change source events in SRM monitored services.", HarnessTeam.CHAOS),
>   EXECUTION_AUDIT_EVENTS("Enables audits events for PipelineExecution", HarnessTeam.PIPELINE);
> ```

FF should start with team, here it should start with PIE

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44826)* status: 3 file(s) to review. 0 of 2 approvals obtained.

**Comment by senjucanon2** [comment]
trigger messagecheck

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44826)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 647 at r1](https://reviewable.io/reviews/harness/harness-core/44826#-NPvqMwmEUoCAGd_NKA9:-NPw-HW50bX1XYyXw67y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/feb38fb41cb28779a6f765a09bb8a2c0e9fcfd96/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L647)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

FF should start with team, here it should start with PIE
</blockquote></details>

Done.

**Comment by senjucanon2** [comment]
trigger ut2

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44826)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44826)* status: 1. unresolved discussions.

**Pull request merged**
