### PR TITLE
feat: [SRM-13445]: Updated Module Type CV to SRM

### PR DESCRIPTION
**Pull request by arpit-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42086)

### CODE REVIEW

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42086)* status: 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java` line 394 at r1](https://reviewable.io/reviews/harness/harness-core/42086#-NKUBbYg87xMw8TU9dGj:-NKUBbYg87xMw8TU9dGk:b-budfnj) ([raw file](https://github.com/harness/harness-core/blob/22501261c7625869834c6521289ae744b57b175e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java#L394)):*
> ```Java
>                                           .modulesSupported(Arrays.asList(ModuleType.CD, ModuleType.CI, ModuleType.CF,
>                                               ModuleType.CE, ModuleType.PMS, ModuleType.STO, ModuleType.TEMPLATESERVICE,
>                                               ModuleType.CV, ModuleType.SRM, ModuleType.CHAOS, ModuleType.GOVERNANCE))
> ```

Are we using CV anywhere? If not why did we not rename it to SRM?

**Review by arpit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42086)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java` line 394 at r1](https://reviewable.io/reviews/harness/harness-core/42086#-NKUBbYg87xMw8TU9dGj:-NKXg_Cq1bAK37ObLrnJ:b-rd8tz4) ([raw file](https://github.com/harness/harness-core/blob/22501261c7625869834c6521289ae744b57b175e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java#L394)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Are we using CV anywhere? If not why did we not rename it to SRM?
</blockquote></details>

Its used in licensing and there are many existing licenses with module type as CV. We can remove the CV type in next phase.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42086)* status: Some of the checks are too old. 1. unresolved discussions.

**Review by AbhijithHarness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42086)* status: Some of the checks are too old. 1. unresolved discussions. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java` line 394 at r1](https://reviewable.io/reviews/harness/harness-core/42086#-NKUBbYg87xMw8TU9dGj:-NKv438R4NSBek9WZy1t:bx997lj) ([raw file](https://github.com/harness/harness-core/blob/22501261c7625869834c6521289ae744b57b175e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java#L394)):*
> Its used in licensing and there are many existing licenses with module type as CV. We can remove the CV type in next phase.
nit: mark CV Enum as @Deprecated.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42086)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java` line 394 at r1](https://reviewable.io/reviews/harness/harness-core/42086#-NKUBbYg87xMw8TU9dGj:-NL-Ofp36j7WWcd0NqsV:b-dg3lnb) ([raw file](https://github.com/harness/harness-core/blob/22501261c7625869834c6521289ae744b57b175e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java#L394)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

> Its used in licensing and there are many existing licenses with module type as CV. We can remove the CV type in next phase.
nit: mark CV Enum as @Deprecated.
</blockquote></details>

Apart from this CVNGYamlSchemaServiceImpl, also make in this class for schema for cross functional steps
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/VerificationApplication.java` line 560 at r2](https://reviewable.io/reviews/harness/harness-core/42086#-NL-OJal1tp_b9RWbKsq:-NL-OJan54oTYwGvc6LX:bk1eusf) ([raw file](https://github.com/harness/harness-core/blob/0b4254c4c5b1b0a7e3b2fca876efa5e6f7f56007/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/VerificationApplication.java#L560)):*
> ```Java
>     return PmsSdkConfiguration.builder()
>         .deploymentMode(remote ? SdkDeployMode.REMOTE : SdkDeployMode.LOCAL)
>         .moduleType(ModuleType.SRM)
> ```

You need to change yamlSchemaClientConfig to add srm along with cv
Also please test in a pr env, if all services are old, and then you deploy new cv version, is pipeline save/update/excecute with cv step is working or not.

Also you need to add same entry in grpcClientConfigs in config.yaml for pipeline-service

Plus after this change we need to add overrides in pre-qa, qa and prod env


Just to be same on safe side check the same in cd service as well

cc: @deepak-harness

**Pull request closed without merging**
