### PR TITLE
fix: [CDS-25446]: consider instance expressions in template variables

### PR DESCRIPTION
**Pull request by inderschera**
We will now start picking up instance expressions from template variables.

Say, if we are deploying to 2 hosts - host1 and host2, and ${instance.hostName} is provided in template variables, we will have this execution view. For each host, we will have different execution of shell script.

Screenshot 2022-03-25 at 1 55 57 PM

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31544)

### CODE REVIEW

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31544)* status: :shipit: complete! ✓

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31544)* status: :shipit: complete! ✓

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31544)* status: :shipit: complete! ✓

**Review by poojaSinghal — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31544)* status: :shipit: complete! ✓

**Review by poojaSinghal — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31544)* status: :shipit: complete! ✓

**Pull request merged**
