### PR TITLE
feat: [IDP-180]: Bitbucket connector implementation

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44521)

### CODE REVIEW

**Comment by vigneswara-propelo** [comment]
trigger messagecheck

**Review by sandeepa-kv-jois — APPROVED** [review]

**Review by sandeepa-kv-jois — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44521)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44521)* status: :shipit: complete! ✓

___
*[`idp-service/service/src/main/java/io/harness/idp/gitintegration/implementation/BitbucketConnectorProcessor.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/44521#-NPRfryU37yM8p9PdRhD:-NPRfryU37yM8p9PdRhE:blxa5af) ([raw file](https://github.com/harness/harness-core/blob/30c5353c86384fe97f495e833729dab00248d70c/idp-service/service/src/main/java/io/harness/idp/gitintegration/implementation/BitbucketConnectorProcessor.java#L72)):*
> ```Java
>           "Password Secret not found for identifier : [%s], accountId: [%s]", connectorIdentifier, accountIdentifier));
>     }
>     tokenEnvironmentSecret.setDecryptedValue(pwdDecryptedSecretValue.getDecryptedValue());
> ```

nit: Can this code block go into a common util? All the ConnectorProcessors duplicate this part otherwise
Can take this up later as well. 



_Code quote:_
```Java
    EnvironmentSecret tokenEnvironmentSecret = new EnvironmentSecret();
    tokenEnvironmentSecret.secretIdentifier(pwdSecretIdentifier);
    tokenEnvironmentSecret.setEnvName(GitIntegrationConstants.BITBUCKET_TOKEN);
    DecryptedSecretValue pwdDecryptedSecretValue = ngSecretService.getDecryptedSecretValue(
        accountIdentifier, orgIdentifier, projectIdentifier, pwdSecretIdentifier);
    if (pwdDecryptedSecretValue == null) {
      throw new InvalidRequestException(String.format(
          "Password Secret not found for identifier : [%s], accountId: [%s]", connectorIdentifier, accountIdentifier));
    }
    tokenEnvironmentSecret.setDecryptedValue(pwdDecryptedSecretValue.getDecryptedValue());
```

**Review by deepharness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44521)* status: :shipit: complete! ✓

**Pull request merged**
