### PR TITLE
feat: [CDS-39321]: s3 changes

### PR DESCRIPTION
**Pull request by piyush-bhuwalka**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35044)

### CODE REVIEW

**Comment by piyush-bhuwalka** [comment]
trigger messagecheck

**Comment by piyush-bhuwalka** [comment]
trigger ft2

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by raghuAtWings** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/serverless/ServerlessTaskHelperBase.java` line 261 at r8](https://reviewable.io/reviews/harness/harness-core/35044#-N7EuPbyE-QK5zldHEsv:-N7EuPbyE-QK5zldHEsw:b-2qd69) ([raw file](https://github.com/harness/harness-core/blob/97ef3f31cc947c07399a88ccf406d5cf23965e61/930-delegate-tasks/src/main/java/io/harness/delegate/task/serverless/ServerlessTaskHelperBase.java#L261)):*
> ```Java
>     } else if (serverlessArtifactConfig instanceof ServerlessEcrArtifactConfig) {
>       logCallback.saveExecutionLog(color("Skipping downloading artifact step as it is not needed..", White, Bold));
>     } else if (serverlessArtifactConfig instanceof ServerlessS3ArtifactConfig) {
> ```

what happens with the older delegates where this class is not present? also have you tested this with older delegate version for all other fetchArtifact cases?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 1 of 10 files at r1, 3 of 8 files at r2, 1 of 8 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 2 of 4 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35044)* status: Some of the checks are too old. 0 of 1 approvals obtained.

**Comment by piyush-bhuwalka** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/serverless/ServerlessTaskHelperBase.java` line 261 at r8](https://reviewable.io/reviews/harness/harness-core/35044#-N7EuPbyE-QK5zldHEsv:-N7F32QVAFhTDGb2rURZ:b-cucqlm) ([raw file](https://github.com/harness/harness-core/blob/97ef3f31cc947c07399a88ccf406d5cf23965e61/930-delegate-tasks/src/main/java/io/harness/delegate/task/serverless/ServerlessTaskHelperBase.java#L261)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

what happens with the older delegates where this class is not present? also have you tested this with older delegate version for all other fetchArtifact cases?
</blockquote></details>

When the class is not present, this step would do nothing and the pipeline would fail eventually. Yes, I have tested other fetchArtifact cases with older delegate version

**Review by raghuAtWings — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35044)* status: Some of the checks are too old.

**Comment by alluvamsi-harness** [comment]
trigger codebasehash

**Review by alluvamsi-harness — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 3 of 8 files at r2, 1 of 8 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35044)* status: Some of the checks are too old.

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Review by sainath-b — APPROVED** [review]

**Review by sainath-b — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 3 of 8 files at r2, 1 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35044)* status: :shipit: complete! ✓

**Comment by piyush-bhuwalka** [comment]
trigger codebasehash

**Pull request merged**
