### PR TITLE
fix: [CDS-87033]: add executor service to delegate's local SCM server

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
## Describe your changes
Harness delegate's SCM server (which is run locally on every execution) creates `EpollEventLoopGroup`/`KQueueEventLoopGroup` for communication, which internally creates an executor with N threads for each instance of SCM server. This is creating a lot of `epollEventLoopGroup-%d-%d` threads on the delegate, ultimately affecting its performance. 
With this change, we are introducing a ExecutorService as a singleton in delegate and injecting it into the SCM server. 

Thread-pool configuration (with env var for overriding defaults):
- Core pool size: 1 (`SCM_SERVER_CORE_POOL_SIZE`)
- Max pool size: 10 (`SCM_SERVER_MAX_POOL_SIZE`)
- Idle time: 60 seconds (`SCM_SERVER_POOL_IDLE_TIME_SECONDS`)

| Before  | After (5 parallel k8s deployments) |
|--|--|
|  SCM Before | SCM After  |

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57062)

### CODE REVIEW

**Comment by abhinavsingh1196** [comment]
trigger uts

**Review by markoharness — APPROVED** [review]

**Review by GoelPratyush99 — APPROVED** [review]

**Review by abosii-harness — APPROVED** [review]

**Review by markoharness — APPROVED** [review]

**Comment by abhinavsingh1196** [comment]
Attached screenshots.

**Comment by abhinavsingh1196** [comment]
trigger uts,review,messagecheck

**Review by mdmilic — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57062)* status: 11 file(s) to review. Waiting on team(s): del-team. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/scm/ScmDelegateClientImpl.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/57062#-NmGEuxbAip1E_5iIV9t:-NmGEuxbAip1E_5iIV9u:b1ah33e) ([raw file](https://github.com/harness/harness-core/blob/22861c5345431b23f7774ac829b8ce668329c12d/930-delegate-tasks/src/main/java/io/harness/delegate/task/scm/ScmDelegateClientImpl.java#L42)):*
> ```Java
> @OwnedBy(DX)
> public class ScmDelegateClientImpl implements ScmDelegateClient {
>   @Inject @Named("scmServerExecutor") ExecutorService scmServerExecutor;
> ```

FYI  you should always avoid field level injection. You should use constructor level injection instead. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/scm/ScmLinuxManager.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/57062#-NmGF85i7Kk90WzQOgeB:-NmGF85j6tgU1RB4S8i5:b-gv14db) ([raw file](https://github.com/harness/harness-core/blob/22861c5345431b23f7774ac829b8ce668329c12d/930-delegate-tasks/src/main/java/io/harness/delegate/task/scm/ScmLinuxManager.java#L25)):*
> ```Java
> public class ScmLinuxManager extends ScmUnixManager {
>   ExecutorService scmServerExecutor;
>   EpollEventLoopGroup epollEventLoopGroup;
> ```

Make these private final. 



_Code quote:_
```Java
  ExecutorService scmServerExecutor;
  EpollEventLoopGroup epollEventLoopGroup;
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/scm/ScmMacOSManager.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/57062#-NmGFBnN1yktVYPKxipx:-NmGFBnN1yktVYPKxipy:bswhigk) ([raw file](https://github.com/harness/harness-core/blob/22861c5345431b23f7774ac829b8ce668329c12d/930-delegate-tasks/src/main/java/io/harness/delegate/task/scm/ScmMacOSManager.java#L26)):*
> ```Java
> public class ScmMacOSManager extends ScmUnixManager {
>   ExecutorService scmServerExecutor;
>   KQueueEventLoopGroup klg;
> ```

private final



_Code quote:_
```Java
  ExecutorService scmServerExecutor;
  KQueueEventLoopGroup klg;
```
___
*[`980-commons/src/main/java/io/harness/utils/system/BUILD.bazel` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/57062#-NmGFl8i7KZ7e3ISHRwM:-NmGFl8j857wZAYdjQJJ:b-nv2xq0) ([raw file](https://github.com/harness/harness-core/blob/22861c5345431b23f7774ac829b8ce668329c12d/980-commons/src/main/java/io/harness/utils/system/BUILD.bazel#L21)):*
> ```Starlark
>     deps = [
>         "//:lombok",
>         "//980-commons/src/main/java/io/harness/data/structure:module",
> ```

Let's not add this dep, it's way too big (I estimate over 30Mb for a null check). You should avoid using that EmptyPredicate anyway, it's useless implementation. Real good ones exist in common libraries we use everywhere. You should use StringUtils.lang3.isNotBlank instead.

**Comment by abhinavsingh1196** [comment]
trigger uts

**Review by mdmilic — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57062)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Comment by abhinavsingh1196** [comment]
trigger ut6,ut8

**Review by abosii-harness — APPROVED** [review]

**Comment by abhinavsingh1196** [comment]
trigger review

**Review by alebuh — APPROVED** [review]

**Comment by abhinavsingh1196** [comment]
trigger ut1

**Comment by abhinavsingh1196** [comment]
trigger ut5

**Review by markoharness — APPROVED** [review]

**Pull request merged**
