### PR TITLE
feat: [CDS-42264]: move artifact sources and primaryartifactref field insid…

### PR DESCRIPTION
**Pull request by inderschera**
…e primary

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36886)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36886)

**Comment by inderschera** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/PrimaryArtifact.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/36886#-NAek7k132zh5R5ZQR9E:-NAek7k132zh5R5ZQR9F:bma6zry) ([raw file](https://github.com/harness/harness-core/blob/cfe8e32e8522e77127746c0d62b69252aab8870e/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/PrimaryArtifact.java#L75)):*
> ```Java
>   // Use Builder as Constructor then only external property(visible) will be filled.
>   @Builder
>   @ConstructorProperties({"uuid", "sourceType", "spec", "primaryArtifactRef", "sources", "metadata"})
> ```

metadata is not an argument here in the constructor, is that expected but its mentioned in ```ConstructorProperties```

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36886)* status: 0 of 1 approvals obtained.

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36886)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/PrimaryArtifact.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/36886#-NAek7k132zh5R5ZQR9E:-NAheNvEAvG0HS-uG01k:b51sfpn) ([raw file](https://github.com/harness/harness-core/blob/cfe8e32e8522e77127746c0d62b69252aab8870e/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/PrimaryArtifact.java#L75)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

metadata is not an argument here in the constructor, is that expected but its mentioned in ```ConstructorProperties```
</blockquote></details>

Added it. Thanks

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36886)* status: :shipit: complete! ✓

**Pull request merged**
