### PR TITLE
fix: [CDS-49250]: Fix the log stream for Kubernetes and Native Helm.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
Fix the log stream for Kubernetes and Native Helm.

### Native Helm
1. Git (Helm Chart)
helm-git

2. Git (Helm Chart) + Harness
helm-git-harness

3. HTTP (Helm Chart) + Git
helm-http-git

4. HTTP (Helm Chart)
helm-http

5. HTTP (Helm Chart) + Harness
helm-http-harness

6. Harness (Helm Chart)
helm-harness

7. Custom (Helm Chart)
helm-custom

8. Custom (Helm Chart) + Harness
helm-harness-custom

9. Custom (Helm Chart) + Git
helm-custom-git

10. Git (Helm Chart) + Custom
helm-git-custom

11. HTTP (Helm Chart) + Custom + Git
helm-http-custom-git

### Kubernetes
1. Git (K8s)
Git

2. Git (K8s) + Harness
Harness-git-1
Harness-git-2

3. Http (K8s)
http

4. Http (K8s) + Git
http-git

5. Http (K8s) + Harness
harness-http

6. Custom (K8s)
custom

7. Custom (K8s) + Harness
harness-custom

8. Custom (K8s) + Git
custom-git

9. Harness (K8s)
harness

10. Git (K8s) + Custom
git-custom

11. Http (K8s) + Custom + Git
http-custom-git

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42182)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 2 of 7 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42182)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepPassThroughData.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/42182#-NL1AtrM7htNqhPdhaF-:-NL1AtrO7ae1retCz9bs:b-la844n) ([raw file](https://github.com/harness/harness-core/blob/32b87e3d245ad48b3943d48f2587409a7b3ed43d/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepPassThroughData.java#L93)):*
> ```Java
>   public void updateCloseFetchFilesStreamStatus(Set<String> manifestStoreTypeList) {
>     this.manifestStoreTypeVisited.addAll(manifestStoreTypeList);
>     if (ManifestStoreType.GitSubsetRepo.equals(manifestStoreTypeList)) {
> ```

In which scenario this condition will be true? You need to have a set of GIT, GITHUB, GITLAB, BITBUCKET, AZURE_REPO as input which doesn't sound reasonably 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepPassThroughData.java` line 100 at r3](https://reviewable.io/reviews/harness/harness-core/42182#-NL1BTrU0KE4_48k-8iH:-NL1BTrU0KE4_48k-8iI:b-ybljri) ([raw file](https://github.com/harness/harness-core/blob/32b87e3d245ad48b3943d48f2587409a7b3ed43d/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepPassThroughData.java#L100)):*
> ```Java
>       for (ManifestOutcome individualManifestOutcome : this.getManifestOutcomeList()) {
>         updatedCloseFetchFilesStreamStatus = updatedCloseFetchFilesStreamStatus
>             && this.manifestStoreTypeVisited.contains(individualManifestOutcome.getStore().getKind());
> ```

Why do we need to close log stream after we visited all manifest store types? I don't follow. For example, in case of K8s Manifest + Values Yaml with git store type you don't need to close log stream since fetch files log stream will be used further in K8s Task
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 1084 at r3](https://reviewable.io/reviews/harness/harness-core/42182#-NL1Bxm2187mpMXg7kAT:-NL1Bxm2187mpMXg7kAU:bm56yyj) ([raw file](https://github.com/harness/harness-core/blob/32b87e3d245ad48b3943d48f2587409a7b3ed43d/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L1084)):*
> ```Java
>         String msg = "Exception in processing HelmValuesFetchTask. " + exceptionMsg;
>         log.error(msg, ex);
>         logCallback.saveExecutionLog(msg, WARN);
> ```

Shouldn't this be kept as ERROR?

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42182)* status: 10 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepPassThroughData.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/42182#-NL1AtrM7htNqhPdhaF-:-NL9eP-BBvY-vWrFVrmE:bo96mfm) ([raw file](https://github.com/harness/harness-core/blob/32b87e3d245ad48b3943d48f2587409a7b3ed43d/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepPassThroughData.java#L93)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

In which scenario this condition will be true? You need to have a set of GIT, GITHUB, GITLAB, BITBUCKET, AZURE_REPO as input which doesn't sound reasonably 
</blockquote></details>

It will be true because we always check if the store type belongs to git subset and we pass the complete set. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepPassThroughData.java` line 100 at r3](https://reviewable.io/reviews/harness/harness-core/42182#-NL1BTrU0KE4_48k-8iH:-NL9eZzvDUCNKRmZgFQc:b-xafe22) ([raw file](https://github.com/harness/harness-core/blob/32b87e3d245ad48b3943d48f2587409a7b3ed43d/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepPassThroughData.java#L100)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why do we need to close log stream after we visited all manifest store types? I don't follow. For example, in case of K8s Manifest + Values Yaml with git store type you don't need to close log stream since fetch files log stream will be used further in K8s Task
</blockquote></details>

Close log stream is only for the Native Helm scenario where fetching manifest files are part of Prepare command unit. In k8s we close the stream while executing the k8stask
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 1084 at r3](https://reviewable.io/reviews/harness/harness-core/42182#-NL1Bxm2187mpMXg7kAT:-NL9eu27DS8xXZ0k1PZF:bx92l38) ([raw file](https://github.com/harness/harness-core/blob/32b87e3d245ad48b3943d48f2587409a7b3ed43d/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L1084)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Shouldn't this be kept as ERROR?
</blockquote></details>

For now we are logging it as warn and throwing the error. Later when we catch this error in HelmValuesFetchTaskNG.java then we log it as error and close the log the command unit.

**Review by achyuth-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42182)* status: 10 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42182)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepPassThroughData.java` line 90 at r4](https://reviewable.io/reviews/harness/harness-core/42182#-NLf48zw5lM_ttY5jKKE:-NLf48zx209bTVzTD_pS:bi5968o) ([raw file](https://github.com/harness/harness-core/blob/1a84ab5e8538af3086328f88a8b5a33d9a5f70ba/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepPassThroughData.java#L90)):*
> ```Java
>   }
> 
>   public void updateCloseFetchFilesStreamStatus(Set<String> manifestStoreTypeList) {
> ```

Let's add NativeHelm in name

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42182)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepPassThroughData.java` line 90 at r4](https://reviewable.io/reviews/harness/harness-core/42182#-NLf48zw5lM_ttY5jKKE:-NLfQHCC5EtEsFXz3Nga:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1a84ab5e8538af3086328f88a8b5a33d9a5f70ba/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepPassThroughData.java#L90)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's add NativeHelm in name
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42182)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by rafaelmart1ns — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 1 of 7 files at r2, 3 of 7 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42182)* status: :shipit: complete! ✓

**Pull request merged**
