### PR TITLE
[feat]: [PIE-6532]: Add API to initiate pipeline validation

### PR DESCRIPTION
**Pull request by namanvermah**
**Impact**: New API is internal, and no existing flows are touched. So, no impact.
**Testing**: Unit Tests Added. E2E testing done by hitting the new API to start the validation process, and then hitting the get result by uuid API added in the previous PR. The response came as expected.

Query Parameters in the new API are the same as that in Pipeline Get API.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40645)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> Reviewed 8 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40645)* status: 12 file(s) to review. 0 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40645)* status: 5 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 172 at r3](https://reviewable.io/reviews/harness/harness-core/40645#-NHwynbR88j2UwKNqCsm:-NHwynbR88j2UwKNqCsn:b-gv09yp) ([raw file](https://github.com/harness/harness-core/blob/75b800eac93b596456dfb152c92a74c38f65c7d4/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L172)):*
> ```Java
>   public Response startPipelineValidationEvent(String org, String project, String pipeline, String account,
>       String branch, String connectorRef, String repoName, Boolean loadFromCache, Boolean loadFromFallbackBranch) {
>     GitAwareContextHelper.populateGitDetails(
> ```

nit, I am not sure if this would work. 

This updates the current thread context. But you are spawning a new thread later.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40645)* status: 5 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 170 at r3](https://reviewable.io/reviews/harness/harness-core/40645#-NHwxdhG9swFrGIJFj4I:-NHx3SKf2LIP2iBqTLjk:bmf54j4) ([raw file](https://github.com/harness/harness-core/blob/75b800eac93b596456dfb152c92a74c38f65c7d4/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L170)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, any RBAC check needed?
</blockquote></details>

Added checks
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 172 at r3](https://reviewable.io/reviews/harness/harness-core/40645#-NHwynbR88j2UwKNqCsm:-NHx3TyJ0sJxFYHOFrn3:brv0061) ([raw file](https://github.com/harness/harness-core/blob/75b800eac93b596456dfb152c92a74c38f65c7d4/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L172)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, I am not sure if this would work. 

This updates the current thread context. But you are spawning a new thread later.
</blockquote></details>

The git details are needed to fetch the pipeline in this thread. Also, executor service picks the global context from the parent thread and spawns the new thread with that context so the git context will persist.

**Review by vaibhav-si — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40645)* status: 5 file(s) to review. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 172 at r3](https://reviewable.io/reviews/harness/harness-core/40645#-NHwynbR88j2UwKNqCsm:-NHx43fV-Jw9lixhm5e8:b40qft1) ([raw file](https://github.com/harness/harness-core/blob/75b800eac93b596456dfb152c92a74c38f65c7d4/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L172)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

The git details are needed to fetch the pipeline in this thread. Also, executor service picks the global context from the parent thread and spawns the new thread with that context so the git context will persist.
</blockquote></details>

Sounds god

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40645)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by ankittiwari-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/helper/PipelineAsyncValidationHelper.java` line 28 at r4](https://reviewable.io/reviews/harness/harness-core/40645#-NHx65gk7yFlfL1uFG_f:-NHx65gk7yFlfL1uFG_g:b-umlysz) ([raw file](https://github.com/harness/harness-core/blob/b9508bb861dc8824791ddfdfc455a005e3f415ef/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/helper/PipelineAsyncValidationHelper.java#L28)):*
> ```Java
>     String identifier = pipelineEntity.getIdentifier();
>     if (EmptyPredicate.isEmpty(branch)) {
>       return accountId + "/" + orgIdentifier + "/" + projectIdentifier + "/" + identifier;
> ```

nit: use string.format.

**Comment by ankittiwari-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service/PipelineAsyncValidationServiceImpl.java` line 57 at r4](https://reviewable.io/reviews/harness/harness-core/40645#-NHxBCEbAh-p0zrjeWTZ:-NHxBCEbAh-p0zrjeWT_:boyz289) ([raw file](https://github.com/harness/harness-core/blob/b9508bb861dc8824791ddfdfc455a005e3f415ef/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service/PipelineAsyncValidationServiceImpl.java#L57)):*
> ```Java
>         pipelineValidationEventRepository.save(pipelineValidationEvent);
> 
>     executorService.submit(PipelineAsyncValidationHandler.builder()
> ```

given we are not returning any response, we can use executorService.execute()

**Review by ankittiwari-harness — COMMENTED** [review]
> Reviewed 9 of 12 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40645)* status: 1 of 2 approvals obtained.

**Review by ankittiwari-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40645)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 12 files at r1, 1 of 1 files at r4, 4 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40645)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 4 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40645)* status: :shipit: complete! ✓

**Pull request merged**
