### PR TITLE
feat: [CDS-44154]: add entity refresh api on ng manager

### PR DESCRIPTION
**Pull request by inderschera**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38228)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 9 Issues 
* Code issue 8 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38228)

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 10 of 16 files at r1, 1 of 1 files at r2, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38228)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/EntityFetchHelper.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/38228#-NDIp8Jf4UXT2YFdyaLe:-NDIp8Jg3sIx7DJIQrHY:b-al2ged) ([raw file](https://github.com/harness/harness-core/blob/f998eca32e3c6979b52ad455329379dbbb1d3bc3/120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/EntityFetchHelper.java#L39)):*
> ```Java
>             serviceIdentifierRef.getProjectIdentifier(), serviceIdentifierRef.getIdentifier(), EntityType.SERVICE);
>     if (cacheMap.containsKey(uniqueServiceIdentifier)) {
>       return (ServiceEntity) cacheMap.get(uniqueServiceIdentifier);
> ```

what is our process of removing items from this cache ?

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38228)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/EntityFetchHelper.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/38228#-NDIp8Jf4UXT2YFdyaLe:-NDIwufi9RSktU2CVIM3:b-4u5wbz) ([raw file](https://github.com/harness/harness-core/blob/f998eca32e3c6979b52ad455329379dbbb1d3bc3/120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/EntityFetchHelper.java#L39)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

what is our process of removing items from this cache ?
</blockquote></details>

Why do we need to remove items from this map?
For each API call, this map would be newly populated to avoid multiple read from dbs for same services present in multiple different stages.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38228)* status: :shipit: complete! ✓

**Pull request merged**
