### PR TITLE
feat: [SPG-203] : exposing cluster api doc

### PR DESCRIPTION
**Pull request by RajBaviskar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37487)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37487)

**Comment by rohitk-h** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/gitops/resource/ClusterResource.java` line 306 at r1](https://reviewable.io/reviews/harness/harness-core/37487#-NBsfB1q2p5ujw8c1jhM:-NBsfB1q2p5ujw8c1jhN:b-9oijwa) ([raw file](https://github.com/harness/harness-core/blob/65817b060771ab73cb3be292375a17c6304ce289/120-ng-manager/src/main/java/io/harness/ng/gitops/resource/ClusterResource.java#L306)):*
> ```Java
>           {
>             @io.swagger.v3.oas.annotations.responses.ApiResponse(description = "Returns the list of cluster from Gitops Service")
>           })
> ```

This API should be hidden, gitops service has a list api for listing all clusters.

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37487)* status: 0 of 1 approvals obtained.

**Comment by RajBaviskar** [comment]
trigger messagecheck

**Comment by RajBaviskar** [comment]
> _[`120-ng-manager/src/main/java/io/harness/ng/gitops/resource/ClusterResource.java` line 306 at r1](https://reviewable.io/reviews/harness/harness-core/37487#-NBsfB1q2p5ujw8c1jhM:-NBsfB1q2p5ujw8c1jhN:b-9oijwa) ([raw file](https://github.com/harness/harness-core/blob/65817b060771ab73cb3be292375a17c6304ce289/120-ng-manager/src/main/java/io/harness/ng/gitops/resource/ClusterResource.java#L306)):_
> 
> > ```java
> >           {
> >             @io.swagger.v3.oas.annotations.responses.ApiResponse(description = "Returns the list of cluster from Gitops Service")
> >           })
> > ```
> 
> This API should be hidden, gitops service has a list api for listing all clusters.

reverted the changes to keep the API Hidden

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37487)* status: :shipit: complete! ✓

**Pull request closed without merging**
