### PR TITLE
feat: [IDP-171]: API: Bulk create/update environment secrets

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44029)

### CODE REVIEW

**Review by devesh-harness — DISMISSED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44029)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by sandeepa-kv-jois — DISMISSED** [review]

**Review by deepharness — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44029)* status: Some of the checks are too old. 

___
*[`idp-service/service/src/main/java/io/harness/idp/secret/mappers/EnvironmentSecretMapper.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/44029#-NOhHRUq8a6Ua2u5KEsE:-NOhHRUr2Hmc7lDjqdo8:belz7te) ([raw file](https://github.com/harness/harness-core/blob/17d8a88c739a98dd8fa2dbb48078602d8ba233ff/idp-service/service/src/main/java/io/harness/idp/secret/mappers/EnvironmentSecretMapper.java#L38)):*
> ```Java
>         .name(envSecret.getName())
>         .secretIdentifier(envSecret.getSecretIdentifier())
>         .accountIdentifier(accountIdentifier)
> ```

did we tried http://modelmapper.org/ anywhere . it will reduce the manual mapping of dto's ? its just a suggestion
___
*[`idp-service/service/src/main/java/io/harness/idp/secret/service/EnvironmentSecretServiceImpl.java` line 97 at r1](https://reviewable.io/reviews/harness/harness-core/44029#-NOhKChI8JmxYVoKzYGc:-NOhKChI8JmxYVoKzYGd:bdainnw) ([raw file](https://github.com/harness/harness-core/blob/17d8a88c739a98dd8fa2dbb48078602d8ba233ff/idp-service/service/src/main/java/io/harness/idp/secret/service/EnvironmentSecretServiceImpl.java#L97)):*
> ```Java
>       List<EnvironmentSecret> requestSecrets, String accountIdentifier) throws Exception {
>     boolean success = syncK8sSecret(requestSecrets, accountIdentifier);
>     if (success) {
> ```

Incase of sync failure what are we doing ?

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44029)* status: Some of the checks are too old. 1. unresolved discussions. 

___
*[`idp-service/service/src/main/java/io/harness/idp/secret/service/EnvironmentSecretServiceImpl.java` line 97 at r1](https://reviewable.io/reviews/harness/harness-core/44029#-NOhKChI8JmxYVoKzYGc:-NOhMBd113jN0gi0IvlV:b-8v8n8x) ([raw file](https://github.com/harness/harness-core/blob/17d8a88c739a98dd8fa2dbb48078602d8ba233ff/idp-service/service/src/main/java/io/harness/idp/secret/service/EnvironmentSecretServiceImpl.java#L97)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Incase of sync failure what are we doing ? 
</blockquote></details>

Actually, we should not even store it in DB. I was planning to handle retries and failure cases in https://harness.atlassian.net/browse/IDP-157

**Review by deepharness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44029)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by devesh-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44029)* status: :shipit: complete! ✓

**Pull request merged**
