### PR TITLE
[fix]: [CDS-59060]: install glibc-langpack-en

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Describe your changes
The initial issue is https://harness.atlassian.net/browse/CDS-59060, jGit was failing to fetch some tags with special characters. One of the fixes was to add LANG env variable to delegate. We found that this was not enough for immutable delegates as en_US.en_US.UTF-8 was not installed.
With microdnf install glibc-langpack-en we're installing en locales on delegate.
In order to test I run a delegate from that image and run a terraform step what would fetch a repo with has some tags with special characters (test passed) .

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47202)

### CODE REVIEW

**Comment by mdmilic** [comment]
Hey @tmacari-harness can you please add the description on what this fixes and how and testing done in the PR description section.

**Review by raghuAtWings — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47202)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`dockerization/delegate/Dockerfile` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/47202#-NUXOCi59sZCXvitjSvr:-NUXOCi59sZCXvitjSvs:b-p7xo4b) ([raw file](https://github.com/harness/harness-core/blob/b6a2d57a304ecf32c0216fb63354c8b0203aae6e/dockerization/delegate/Dockerfile#L22)):*
> ```Dockerfile
>     git \
>     shadow-utils \
>     glibc-langpack-en \
> ```

why not install 'locales` like we do for legacy delegate?

**Comment by tmacari-harness** [comment]
trigger uts

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47202)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`dockerization/delegate/Dockerfile` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/47202#-NUXOCi59sZCXvitjSvr:-NUal7eJ3X-XCwzBC2lZ:b-3351uf) ([raw file](https://github.com/harness/harness-core/blob/b6a2d57a304ecf32c0216fb63354c8b0203aae6e/dockerization/delegate/Dockerfile#L22)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why not install 'locales` like we do for legacy delegate?
</blockquote></details>

as we discussed atp-get is not available here and locales is not a valid package, we have to install them this way using microdnf

**Review by bharatgoelharness — CHANGES_REQUESTED** [review]
There are 2 new vul in this image
https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/ci/orgs/default/projects/IMImages/pipelines/publishimmutabledelegatetest/executions/utowlfsXQJCgKjJtrhfw5w/security?storeType=INLINE
cc @raghuAtWings

**Review by bharatgoelharness — APPROVED** [review]

**Review by raghuAtWings — APPROVED** [review]

**Comment by tmacari-harness** [comment]
trigger utAll

**Comment by tmacari-harness** [comment]
trigger messagecheck

**Comment by tmacari-harness** [comment]
trigger review

**Comment by tmacari-harness** [comment]
trigger uts

**Pull request merged**
