### PR TITLE
fix: [DEL-4202]: hard delete delegate entities on deleting owner

### PR DESCRIPTION
**Pull request by arpit3107**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34366)

### CODE REVIEW

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34366)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34366)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/io/harness/delegate/event/listener/OrganizationEntityCRUDEventListener.java` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/34366#-N4fG7pI-ctMv_6Gm6RK:-N4fG7pJBv4qSx294rNA:bcdshog) ([raw file](https://github.com/harness/harness-core/blob/0153433c401d92c2de58243673e2048225a992c3/400-rest/src/main/java/io/harness/delegate/event/listener/OrganizationEntityCRUDEventListener.java#L117)):*
> ```Java
>       delegateSetupService.deleteDelegateGroupsOnDeletingOwner(
>           organizationEntityChangeDTO.getAccountIdentifier(), owner);
>       delegateProfileService.deleteAllProfileOnDeletingOwner(organizationEntityChangeDTO.getAccountIdentifier(), owner);
> ```

What about DelegateScoped, DelegateConnections and DelegateConnectionResult, should we delegate them as well.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateProfileServiceImpl.java` line 409 at r1](https://reviewable.io/reviews/harness/harness-core/34366#-N4fFGaZ4FnyY4PFI70h:-N4fFGaZ4FnyY4PFI70i:bp4j5df) ([raw file](https://github.com/harness/harness-core/blob/0153433c401d92c2de58243673e2048225a992c3/400-rest/src/main/java/software/wings/service/impl/DelegateProfileServiceImpl.java#L409)):*
> ```Java
>                                        .filter(DelegateProfileKeys.ng, true)
>                                        .filter(DelegateProfileKeys.owner, owner);
> ```

Can we put a log.info here saying number of rows deleted for accountId and owner

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34366)* status: 1 change requests. 2. unresolved discussions. 

___
*[`400-rest/src/main/java/io/harness/delegate/event/listener/OrganizationEntityCRUDEventListener.java` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/34366#-N4fG7pI-ctMv_6Gm6RK:-N4fH14f1a9A0L9ZO9Qr:b-ac38r0) ([raw file](https://github.com/harness/harness-core/blob/0153433c401d92c2de58243673e2048225a992c3/400-rest/src/main/java/io/harness/delegate/event/listener/OrganizationEntityCRUDEventListener.java#L117)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

What about DelegateScoped, DelegateConnections and DelegateConnectionResult, should we delegate them as well.
</blockquote></details>

those will be autodeleted, if delegate is connected for 7 days. We dont need to explicitly delete those records.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateProfileServiceImpl.java` line 409 at r1](https://reviewable.io/reviews/harness/harness-core/34366#-N4fFGaZ4FnyY4PFI70h:-N4fHDmG5FF7L83MNDi3:bb7sa0c) ([raw file](https://github.com/harness/harness-core/blob/0153433c401d92c2de58243673e2048225a992c3/400-rest/src/main/java/software/wings/service/impl/DelegateProfileServiceImpl.java#L409)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Can we put a log.info here saying number of rows deleted for accountId and owner
</blockquote></details>

yes.

**Comment by arpit3107** [comment]
trigger messagecheck

**Comment by arpit3107** [comment]
trigger messagecheck

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34366)* status: Some of the checks are too old.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34366)* status: :shipit: complete! ✓

**Pull request merged**
