### PR TITLE
[feat]: [CDS-69592]: Async task for calculating pipeline references

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have added code for async task creation which calculates the entity references. Have tested out the following flows:
1. for gitX enabled project, get inline pipeline
2. for gitX enabled project, get remote pipeline from default branch and loaded from cache
3. for gitX enabled project, get remote pipeline from default branch and loaded from git
4. for gitX enabled project, get remote pipeline from non default branch
5. for gitX enabled project, creation and updation of inline pipeline
6. for gitX enabled project, creation and updation of remote pipeline

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48102)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`pipeline-service/config/config.yml` line 608 at r1](https://reviewable.io/reviews/harness/harness-core/48102#-NW-09zzEZE9l7_51s6k:-NW-09zzEZE9l7_51s6l:b-1ktzdx) ([raw file](https://github.com/harness/harness-core/blob/351b95d764095200a82c42c95f20e06c42fca96f/pipeline-service/config/config.yml#L608)):*
> ```YAML
> 
> pipelineReferenceExecutorServiceConfig:
>   corePoolSize: ${PIPELINE_REFERENCE_EXECUTOR_POOL_CORE_SIZE:-2}
> ```

why do we need min pool size to be 2? Can't it be 1?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferenceBackgroundHelper.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/48102#-NW-0MZr0ZtQxufd90yo:-NW-0MZs1uhunv7ygT8F:b-bga2cx) ([raw file](https://github.com/harness/harness-core/blob/351b95d764095200a82c42c95f20e06c42fca96f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferenceBackgroundHelper.java#L25)):*
> ```Java
> public class PipelineReferenceBackgroundHelper {
>   ExecutorService executor;
>   Injector injector;
> ```

must be private, right?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferenceBackgroundHelper.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/48102#-NW-0d7a0BZW54RZDLLZ:-NW-0d7a0BZW54RZDLL_:b-n61vrm) ([raw file](https://github.com/harness/harness-core/blob/351b95d764095200a82c42c95f20e06c42fca96f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferenceBackgroundHelper.java#L40)):*
> ```Java
>       executor.execute(pipelineReferencesRunnable);
>     } catch (RejectedExecutionException rejectedExecutionException) {
>       log.warn("Skipping background pipeline reference calculation as task queue is full : {}",
> ```

we need some identifiers here to identify for what pipeline did we skip it

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/48102#-NW-0zFUCfJL141C3E27:-NW-0zFUCfJL141C3E28:b-cfkf4t) ([raw file](https://github.com/harness/harness-core/blob/351b95d764095200a82c42c95f20e06c42fca96f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java#L35)):*
> ```Java
>         log.info(String.format("Calculating pipeline references in the background for pipelineIdentifier: %s",
>             pipelineEntity.getIdentifier()));
>         filterCreatorMergeService.getPipelineInfo(pipelineEntity);
> ```

can we add a comment here on why are we calling this method and not specifically calculating references.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/48102#-NW-1P_o-5ZfvJHv0DMl:-NW-1P_o-5ZfvJHv0DMm:b7d2gv4) ([raw file](https://github.com/harness/harness-core/blob/351b95d764095200a82c42c95f20e06c42fca96f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java#L37)):*
> ```Java
>         filterCreatorMergeService.getPipelineInfo(pipelineEntity);
>         log.info("Successfully calculated pipeline references and updated entitySetupUsage db.");
>       } catch (IOException e) {
> ```

how come IOexception comes here?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/48102#-NW-1TrK1dGBZuspJIqs:-NW-1TrK1dGBZuspJIqt:b-ti112t) ([raw file](https://github.com/harness/harness-core/blob/351b95d764095200a82c42c95f20e06c42fca96f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java#L29)):*
> ```Java
>     this.pipelineEntity = pipelineEntity;
>   }
>   @Override
> ```

blank line missing

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48102)* status: 5 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/config/config.yml` line 608 at r1](https://reviewable.io/reviews/harness/harness-core/48102#-NW-09zzEZE9l7_51s6k:-NW0lIhfDZgOrkHm3Yui:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/351b95d764095200a82c42c95f20e06c42fca96f/pipeline-service/config/config.yml#L608)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why do we need min pool size to be 2? Can't it be 1?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferenceBackgroundHelper.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/48102#-NW-0MZr0ZtQxufd90yo:-NW0lN0T2tfEtnAOvCD1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/351b95d764095200a82c42c95f20e06c42fca96f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferenceBackgroundHelper.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

must be private, right?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferenceBackgroundHelper.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/48102#-NW-0d7a0BZW54RZDLLZ:-NW0lbK99X6d3YSuR0DL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/351b95d764095200a82c42c95f20e06c42fca96f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferenceBackgroundHelper.java#L40)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we need some identifiers here to identify for what pipeline did we skip it
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/48102#-NW-1TrK1dGBZuspJIqs:-NW0lg5796lE_yj9wfBS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/351b95d764095200a82c42c95f20e06c42fca96f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

blank line missing
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/48102#-NW-0zFUCfJL141C3E27:-NW0n9Q1Ef98iU1wLWKg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/351b95d764095200a82c42c95f20e06c42fca96f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java#L35)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we add a comment here on why are we calling this method and not specifically calculating references.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/48102#-NW-1P_o-5ZfvJHv0DMl:-NW0n9qV11FpHEBlXFvM:b-3ld379) ([raw file](https://github.com/harness/harness-core/blob/351b95d764095200a82c42c95f20e06c42fca96f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java#L37)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

how come IOexception comes here?
</blockquote></details>

Ideally there is no IO happening here but in some of the method calls, an IO exception is being thrown, so as the caller we are handling it here.
We can work on the code refactor while we decouple the filter creation and reference calculations

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferenceBackgroundHelper.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/48102#-NW-0d7a0BZW54RZDLLZ:-NW1LZFj3A2P6ytVcbtw:b-ez0o8s) ([raw file](https://github.com/harness/harness-core/blob/351b95d764095200a82c42c95f20e06c42fca96f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferenceBackgroundHelper.java#L40)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

whats the change here?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/48102#-NW1LiUb1gw4YGiD_jx6:-NW1LiUb1gw4YGiD_jx7:b-obnddq) ([raw file](https://github.com/harness/harness-core/blob/f7bcd431a8c300e4f25de3ed28cd926a898952ca/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java#L40)):*
> ```Java
>         log.info("Successfully calculated pipeline references and updated entitySetupUsage db.");
>       } catch (IOException e) {
>         log.error("Faced an IO exception while calculating pipeline reference.");
> ```

missing identifiers in all error logs.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48102)* status: 5 file(s) to review. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferenceBackgroundHelper.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/48102#-NW-0d7a0BZW54RZDLLZ:-NW1O0cR9ZwvqMMtfUgZ:b-dl6rbx) ([raw file](https://github.com/harness/harness-core/blob/351b95d764095200a82c42c95f20e06c42fca96f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferenceBackgroundHelper.java#L40)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats the change here?
</blockquote></details>

the pipeline identifier is added, as part of the last commit it missed
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/48102#-NW1LiUb1gw4YGiD_jx6:-NW1NwCY5dEG8IFPpPw4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f7bcd431a8c300e4f25de3ed28cd926a898952ca/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java#L40)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

missing identifiers in all error logs.
</blockquote></details>

Done.

**Comment by adivishy1** [comment]
trigger uts

**Comment by adivishy1** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java` line 24 at r5](https://reviewable.io/reviews/harness/harness-core/48102#-NWCTMu5BZW2ad38o2HF:-NWCTMu5BZW2ad38o2HG:b-4oviii) ([raw file](https://github.com/harness/harness-core/blob/a168f2cd4d0362ba1ee823286340fe3bbd878ebd/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java#L24)):*
> ```Java
> public class PipelineReferencesRunnable implements Runnable {
>   @Inject FilterCreatorMergeService filterCreatorMergeService;
>   private PipelineEntity pipelineEntity;
> ```

As discussed, we need branch details as well for which setup usage is being published. Thus, instead of only pipeline entity, it should be an encapsulated struct containing pipeline entity, branch etc.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48102)* status: 6 file(s) to review. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java` line 24 at r5](https://reviewable.io/reviews/harness/harness-core/48102#-NWCTMu5BZW2ad38o2HF:-NWHnclx0QrXGQ3rF82w:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a168f2cd4d0362ba1ee823286340fe3bbd878ebd/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java#L24)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

As discussed, we need branch details as well for which setup usage is being published. Thus, instead of only pipeline entity, it should be an encapsulated struct containing pipeline entity, branch etc.
</blockquote></details>

Done.

**Comment by adivishy1** [comment]
trigger uts

**Comment by adivishy1** [comment]
trigger uts

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48102)* status: 18 file(s) to review. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/48102#-NW-1P_o-5ZfvJHv0DMl:-NWaQWGO7kmQc2xiznaO:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/351b95d764095200a82c42c95f20e06c42fca96f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java#L37)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Ideally there is no IO happening here but in some of the method calls, an IO exception is being thrown, so as the caller we are handling it here.
We can work on the code refactor while we decouple the filter creation and reference calculations
</blockquote></details>

Done

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferenceBackgroundHelper.java` line 26 at r10](https://reviewable.io/reviews/harness/harness-core/48102#-NWcOIRDEy9RVmfNOjig:-NWcOIRDEy9RVmfNOjih:b-nimqks) ([raw file](https://github.com/harness/harness-core/blob/185e17c6575e451075fe62e18ec5fad18eed5d30/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferenceBackgroundHelper.java#L26)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> @Slf4j
> public class PipelineReferenceBackgroundHelper {
> ```

can we rename everything to setup usage creation? Thats more intuitive i guess. This renaming should involve logs, classes, configs etc.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java` line 38 at r10](https://reviewable.io/reviews/harness/harness-core/48102#-NWcOss54aKOU38O1MFr:-NWcOss54aKOU38O1MFs:b-luspyz) ([raw file](https://github.com/harness/harness-core/blob/185e17c6575e451075fe62e18ec5fad18eed5d30/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java#L38)):*
> ```Java
>         //        The filter service is being called here as the references are calculated as part of filter creation
>         filterCreatorMergeService.getPipelineInfo(filterCreationParams);
>         log.info("Successfully calculated pipeline references and updated entitySetupUsage db.");
> ```

we don't need this log. We are already using ResponseTimeRecorder. Once this whole method is done with execution, it will print the log with time taken. For error, we already have error messages. So, if no error, that means the its success only.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/FilterCreationGitMetadata.java` line 19 at r10](https://reviewable.io/reviews/harness/harness-core/48102#-NWevTd78t-40nl5F2BY:-NWevTd78t-40nl5F2BZ:b657qdu) ([raw file](https://github.com/harness/harness-core/blob/185e17c6575e451075fe62e18ec5fad18eed5d30/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/FilterCreationGitMetadata.java#L19)):*
> ```Java
> @Builder
> @OwnedBy(HarnessTeam.PIPELINE)
> public class FilterCreationGitMetadata {
> ```

nit: why not use GitMetadata directly?

**Comment by sahilhindwani-harness** [comment]
Since we are using the same thread pool as that of the normal pipeline filter creator, can this background thread cause any issues over existing filter creation requests?
Like if the background thread utilises the pool for filter creation on sdk, our normal save might get hindered. Can we ensure that this is not happening?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 14 of 16 files at r7, 1 of 3 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48102)* status: 18 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48102)* status: 18 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/FilterCreationGitMetadata.java` line 19 at r10](https://reviewable.io/reviews/harness/harness-core/48102#-NWevTd78t-40nl5F2BY:-NWf3mu51rxGqaK1Mw_s:by2xjq9) ([raw file](https://github.com/harness/harness-core/blob/185e17c6575e451075fe62e18ec5fad18eed5d30/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/FilterCreationGitMetadata.java#L19)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: why not use GitMetadata directly?
</blockquote></details>

We are using gitMetadata to populate these fields but felt this is cleaner way of creating a new DTO which has only the required filed and not passing all the other git metadata
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferenceBackgroundHelper.java` line 26 at r10](https://reviewable.io/reviews/harness/harness-core/48102#-NWcOIRDEy9RVmfNOjig:-NWf0DJo0hboxhJCS_jU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/185e17c6575e451075fe62e18ec5fad18eed5d30/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferenceBackgroundHelper.java#L26)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we rename everything to setup usage creation? Thats more intuitive i guess. This renaming should involve logs, classes, configs etc.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java` line 38 at r10](https://reviewable.io/reviews/harness/harness-core/48102#-NWcOss54aKOU38O1MFr:-NWf0Ic35DUA38kqBRTi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/185e17c6575e451075fe62e18ec5fad18eed5d30/pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/PipelineReferencesRunnable.java#L38)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we don't need this log. We are already using ResponseTimeRecorder. Once this whole method is done with execution, it will print the log with time taken. For error, we already have error messages. So, if no error, that means the its success only.
</blockquote></details>

Done.

**Comment by adivishy1** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 8 of 16 files at r7, 1 of 3 files at r8, 3 of 3 files at r9, 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48102)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48102)* status: 6 file(s) to review.

**Comment by adivishy1** [comment]
trigger review

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 8 of 16 files at r7, 1 of 3 files at r8, 3 of 3 files at r9, 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48102)* status: :shipit: complete! ✓

**Pull request merged**
