### PR TITLE
[feat]: [CDS-33522]: updating code to enable repo and tags API for SPcert and…

### PR DESCRIPTION
**Pull request by markoharness**
… MSI users and credential generation for SPcert

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32898)

### CODE REVIEW

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32898)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java` line 285 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UVxE_D2QBBjqpm1mU:-N1UVxE_D2QBBjqpm1mV:brtdrwh) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java#L285)):*
> ```Java
> 
>         AzureAcrTokenTaskResponse accessTokenResponse =
>             (AzureAcrTokenTaskResponse) azureHelperService.executeSyncTask(ambiance, azureTaskParams, baseNGAccess,
> ```

Minor - we could try catch exception here and handle error msg
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/AzureHelperService.java` line 142 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UWEZaBdnG6B95WD88:-N1UWEZaBdnG6B95WD89:bq4vrtk) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/125-cd-nextgen/src/main/java/io/harness/cdng/azure/AzureHelperService.java#L142)):*
> ```Java
>     }
> 
>     LinkedHashMap<String, String> logStreamingAbstractions = new LinkedHashMap<>();
> ```

Pls create separate method for creation and filling log stream abstraction (logStreamingAbstractions)  
___
*[`960-api-services/src/main/java/io/harness/azure/client/AzureAuthorizationRestClient.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UZ7RuBwP_wRzDBLVc:-N1UZ7RuBwP_wRzDBLVd:b-v7gob2) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/io/harness/azure/client/AzureAuthorizationRestClient.java#L19)):*
> ```Java
> import retrofit2.http.Path;
> 
> public interface AzureAuthorizationRestClient {
> ```

Well done!
___
*[`960-api-services/src/main/java/io/harness/azure/client/AzureAuthorizationRestClient.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UZVLv2lfQu9nX6Pj4:-N1UZVLwDd852SWfJE7S:bksfic2) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/io/harness/azure/client/AzureAuthorizationRestClient.java#L24)):*
> ```Java
>   @POST("/{tenantId}/oauth2/v2.0/token")
>   Call<AzureIdentityAccessTokenResponse> servicePrincipalAccessToken(@Path(value = "tenantId") String tenantId,
>       @Field("grant_type") String grantType, @Field("client_id") String clientId, @Field("scope") String scope,
> ```

Minor - we could create constance for these field strings and reuse it.
___
*[`960-api-services/src/main/java/io/harness/azure/client/AzureContainerRegistryClient.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UZu4dARY-TEoVgmLC:-N1UZu4dARY-TEoVgmLD:b-ksipd0) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/io/harness/azure/client/AzureContainerRegistryClient.java#L75)):*
> ```Java
> 
>   /**
>    * Returns ACR refresh token
> ```

Minor - refresh >> access
___
*[`960-api-services/src/main/java/io/harness/azure/client/AzureContainerRegistryRestClient.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1U_9fOCz7ulGx01CqP:-N1U_9fOCz7ulGx01CqQ:b-45gc0o) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/io/harness/azure/client/AzureContainerRegistryRestClient.java#L38)):*
> ```Java
>   @POST("/oauth2/exchange")
>   @FormUrlEncoded
>   Call<AcrGetTokenResponse> getRefreshToken(@Field("grant_type") String grantType,
> ```

Minor - will create constants for all fields strings. 

The same question like above whether refresh and access token only referring to ACR or we can reuse it for other Azure services and rename to getServiceRefreshToken and getServiceAccessToken? 
___
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureAuthorizationClientImpl.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1U_vi344RbbUBbH85O:-N1U_vi344RbbUBbH85P:bg632tx) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/io/harness/azure/impl/AzureAuthorizationClientImpl.java#L114)):*
> ```Java
>         response =
>             azureAuthorizationRestClient
>                 .servicePrincipalAccessToken(azureConfig.getTenantId(), "client_credentials", azureConfig.getClientId(),
> ```

Minor - create constants for strings.
___
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureAuthorizationClientImpl.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UagRxB3mQ41T24nPT:-N1UagRxB3mQ41T24nPU:bcif2c) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/io/harness/azure/impl/AzureAuthorizationClientImpl.java#L124)):*
> ```Java
>                        .execute();
>       } else {
>         log.error("Retrieving ManagedIdentity access token is currently not supported via REST API");
> ```

I am not 100% sure but i think that we are logging error msg when catch NestedExceptionUtils.hintWithExplanationException. 
___
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureContainerRegistryClientImpl.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UfHpb1NuKJqMauRCc:-N1UfHpcBR3WkxvOxfD4:b-oxpohg) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/io/harness/azure/impl/AzureContainerRegistryClientImpl.java#L182)):*
> ```Java
>           getAzureRestClient(buildRepositoryHostUrl(registryUrl), AzureContainerRegistryRestClient.class);
>       Response<AcrGetTokenResponse> response =
>           acrRestClient.getRefreshToken("access_token", azureAccessToken, registryUrl).execute();
> ```

Create constance for access_token.
___
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureContainerRegistryClientImpl.java` line 206 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UfN7G7t3N5R_hoFO5:-N1UfN7G7t3N5R_hoFO6:b-r575ab) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/io/harness/azure/impl/AzureContainerRegistryClientImpl.java#L206)):*
> ```Java
>       String refreshToken = getAcrRefreshToken(registryUrl, azureAccessToken);
>       Response<AcrGetTokenResponse> response =
>           acrRestClient.getAccessToken("refresh_token", refreshToken, registryUrl, scope).execute();
> ```

Create constance for refresh_token.
___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UgbGq1QAvYZa6HqJ_:-N1UgbGq1QAvYZa6HqJa:b-puhowh) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L66)):*
> ```Java
>   }
> 
>   public String getCertificateThumbprintBase64Encoded(byte[] pem) {
> ```

Minor - Add uni tests in next PR for these  public utils methods. 
___
*[`960-api-services/src/main/java/software/wings/helpers/ext/azure/AcrGetTokenResponse.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UfbC8DUn-rjssy9-Y:-N1UfbC8DUn-rjssy9-Z:bj4715g) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/software/wings/helpers/ext/azure/AcrGetTokenResponse.java#L22)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> @OwnedBy(HarnessTeam.CDP)
> public class AcrGetTokenResponse {
> ```

Almost the same question, can we rename this from AcrGetTokenResponse to GetTokenResponse if we can reuse this response for other Azure non ACR resources? 
___
*[`960-api-services/src/main/java/software/wings/helpers/ext/azure/AcrGetTokenResponse.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UgKGz-H45KLoztHdv:-N1UgKH-9B6Cn4bdLdqR:b-oaqx69) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/software/wings/helpers/ext/azure/AcrGetTokenResponse.java#L23)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> public class AcrGetTokenResponse {
>   @JsonProperty("refresh_token") private String refreshToken;
> ```

Constants for refresh_token and access_token.
___
*[`960-api-services/src/main/java/software/wings/helpers/ext/azure/AzureIdentityAccessTokenResponse.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UgQcL6YqUy-7BPnqc:-N1UgQcL6YqUy-7BPnqd:b-uj2t2x) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/software/wings/helpers/ext/azure/AzureIdentityAccessTokenResponse.java#L23)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> public class AzureIdentityAccessTokenResponse {
>   @JsonProperty("token_type") private String tokenType;
> ```

Constants for strings.

**Comment by markoharness** [comment]
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java` line 285 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UVxE_D2QBBjqpm1mU:-N1Ukplj5FUaBQ_xBBZM:bkvptdf) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java#L285)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - we could try catch exception here and handle error msg
</blockquote></details>

We are not wrapping this kind of call for any of the helper services (acr, gcr, ecr...).
We can wrap it in try/catch but what would we do with the exception? Log the message? In case of exception this should already be handled by error framework.
I don't think there is need to wrap it with try/catch

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/client/AzureContainerRegistryRestClient.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1U_9fOCz7ulGx01CqP:-N1UpOPH1ohFFE3cBEOH:b-ca8g8z) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/io/harness/azure/client/AzureContainerRegistryRestClient.java#L38)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - will create constants for all fields strings. 

The same question like above whether refresh and access token only referring to ACR or we can reuse it for other Azure services and rename to getServiceRefreshToken and getServiceAccessToken? 
</blockquote></details>

These only refer to ACR

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/client/AzureContainerRegistryRestClient.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1U_9fOCz7ulGx01CqP:-N1Upn40C21wbrX7r2t3:b-g0nhxi) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/io/harness/azure/client/AzureContainerRegistryRestClient.java#L38)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

These only refer to ACR
</blockquote></details>

as per https://docs.microsoft.com/en-us/rest/api/containerregistry/refresh-tokens/get-from-exchange

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureAuthorizationClientImpl.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UagRxB3mQ41T24nPT:-N1UrCQc9fwLFuDli_xx:bel37p) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/io/harness/azure/impl/AzureAuthorizationClientImpl.java#L124)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I am not 100% sure but i think that we are logging error msg when catch NestedExceptionUtils.hintWithExplanationException. 
</blockquote></details>

You are right. Will remove the log line.

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UgbGq1QAvYZa6HqJ_:-N1UraE0CdSigKEWgvTt:b-uv9xs3) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L66)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - Add uni tests in next PR for these  public utils methods. 
</blockquote></details>

Yes. There will be a separate PR for unit tests only.

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/software/wings/helpers/ext/azure/AcrGetTokenResponse.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UfbC8DUn-rjssy9-Y:-N1Urh9b4nnp92s5jfA2:boldh6r) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/software/wings/helpers/ext/azure/AcrGetTokenResponse.java#L22)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Almost the same question, can we rename this from AcrGetTokenResponse to GetTokenResponse if we can reuse this response for other Azure non ACR resources? 
</blockquote></details>

It is only for ACR.

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/AzureHelperService.java` line 142 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UWEZaBdnG6B95WD88:-N1UsrCy0CrkxVl3QAfu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/125-cd-nextgen/src/main/java/io/harness/cdng/azure/AzureHelperService.java#L142)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Pls create separate method for creation and filling log stream abstraction (logStreamingAbstractions)  
</blockquote></details>

Done.

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/client/AzureAuthorizationRestClient.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UZ7RuBwP_wRzDBLVc:-N1Ussak0GyHCwl25WIl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/io/harness/azure/client/AzureAuthorizationRestClient.java#L19)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Well done!
</blockquote></details>

Done.

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureContainerRegistryClientImpl.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UfHpb1NuKJqMauRCc:-N1UsyUg0HjwmJrIkOov:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/io/harness/azure/impl/AzureContainerRegistryClientImpl.java#L182)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Create constance for access_token.
</blockquote></details>

Done.

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureContainerRegistryClientImpl.java` line 206 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UfN7G7t3N5R_hoFO5:-N1UszqK3BGfyZLZni6S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/io/harness/azure/impl/AzureContainerRegistryClientImpl.java#L206)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Create constance for refresh_token.
</blockquote></details>

Done.

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/software/wings/helpers/ext/azure/AcrGetTokenResponse.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UgKGz-H45KLoztHdv:-N1Ut0uo2Vz2PuNgVQpQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/software/wings/helpers/ext/azure/AcrGetTokenResponse.java#L23)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Constants for refresh_token and access_token.
</blockquote></details>

Done.

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/software/wings/helpers/ext/azure/AzureIdentityAccessTokenResponse.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/32898#-N1UgQcL6YqUy-7BPnqc:-N1Ut1lC6noDIw8b-PUI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3348d4251396dfc0c2a22914b6879938055cb3ce/960-api-services/src/main/java/software/wings/helpers/ext/azure/AzureIdentityAccessTokenResponse.java#L23)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Constants for strings. 
</blockquote></details>

Done.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32898)* status: :shipit: complete! ✓

**Pull request merged**
