### PR TITLE
[techDebt]: [DEL-4040]: Move DelegateConfigService and related classes to 930-delegate-tasks

### PR DESCRIPTION
**Pull request by raghuAtWings**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33008)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33008)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/ConfigFile.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/33008#-N1mW5FC7hNY5JX2OeJK:-N1mW5FC7hNY5JX2OeJL:boaltsg) ([raw file](https://github.com/harness/harness-core/blob/855d06d8bd898576539aa74857e5c0fe53db96bf/400-rest/src/main/java/software/wings/beans/ConfigFile.java#L220)):*
> ```Java
>   public ConfigFileDto toDto() {
>     Map<String, Integer> envVersionMap = new HashMap<>();
>     getEnvIdVersionMap().forEach((id, entityVersion) -> envVersionMap.put(id, entityVersion.getVersion()));
> ```

You can use stream & map collector to make it more readable and "immutable". E.g. 



_Code quote (i):_
```Java
    Map<String, Integer> envVersionMap = new HashMap<>();
    getEnvIdVersionMap().forEach((id, entityVersion) -> envVersionMap.put(id, entityVersion.getVersion()));
```



_Code snippet (ii):_
```Java
// Becomes something like this
Map<String, Integer> envVersionMap = getEnvIdVersionMap().entrySet().stream().collect(toMap(Entry::getKey, Entry::getValue::getVersion));
```
___
*[`400-rest/src/main/java/software/wings/resources/ServiceTemplateResource.java` line 185 at r1](https://reviewable.io/reviews/harness/harness-core/33008#-N1mYM5rBHcmnTrKV_H6:-N1mYM5s1MvyAfJ7PyUb:by52les) ([raw file](https://github.com/harness/harness-core/blob/855d06d8bd898576539aa74857e5c0fe53db96bf/400-rest/src/main/java/software/wings/resources/ServiceTemplateResource.java#L185)):*
> ```Java
>     List<ConfigFile> configFiles = serviceTemplateService.computedConfigFiles(appId, envId, templateId);
>     List<ConfigFileDto> fileDtos = new ArrayList<>();
>     configFiles.forEach(configFile -> fileDtos.add(configFile.toDto()));
> ```

prefer streams, allows you to make objects final (reference immutable)



_Code snippet:_
```Java
final List<ConfigFileDto> fileDtos = configFiles.stream().map(configFile -> configFile.toDto()).collect(toList())
```
___
*[`930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/33008#-N1mZ37w3IUtfVkvPPKQ:-N1mZ37w3IUtfVkvPPKR:b4qnq08) ([raw file](https://github.com/harness/harness-core/blob/855d06d8bd898576539aa74857e5c0fe53db96bf/930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java#L8)):*
> ```Java
> 
> @Data
> @Builder
> ```

If all the fields are mandatory (from the current usage it looks they are), you shouldn't have builder, makes it error prone. You should only have all args constructor.
To do that:
* remove builder
* Either make it `@Value` or keep `@Data` make all field `private final` <- these two are equivalent
___
*[`930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/33008#-N1mZU4h9rckxb0ZrjP9:-N1mZU4h9rckxb0ZrjPA:bof196p) ([raw file](https://github.com/harness/harness-core/blob/855d06d8bd898576539aa74857e5c0fe53db96bf/930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java#L21)):*
> ```Java
>     }
> 
>     return 1;
> ```

This seems very arbitrary. Probably best to throw exception instead.

**Review by mdmilic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33008)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/33008#-N1mZ37w3IUtfVkvPPKQ:-N1mZpD5EfSnYDmM6mik:b-bkcxvg) ([raw file](https://github.com/harness/harness-core/blob/855d06d8bd898576539aa74857e5c0fe53db96bf/930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java#L8)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

If all the fields are mandatory (from the current usage it looks they are), you shouldn't have builder, makes it error prone. You should only have all args constructor.
To do that:
* remove builder
* Either make it `@Value` or keep `@Data` make all field `private final` <- these two are equivalent
</blockquote></details>

just correction: 
"or keep `@Data` **AND** make all field private final"

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33008)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/33008#-N1m_KdG3646vqgQxYLl:-N1m_KdG3646vqgQxYLm:bvgdxz9) ([raw file](https://github.com/harness/harness-core/blob/855d06d8bd898576539aa74857e5c0fe53db96bf/930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java#L10)):*
> ```Java
> @Builder
> public class ConfigFileDto {
>   private String uuid;
> ```

Also, whatever you decide, all your fields should be private final (makes object more immutable). Either by using `@Value` or making it explicit

**Review by mdmilic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33008)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/33008#-N1mZU4h9rckxb0ZrjP9:-N1mqCOM2wrggdP-OgwK:b-cp69bk) ([raw file](https://github.com/harness/harness-core/blob/855d06d8bd898576539aa74857e5c0fe53db96bf/930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java#L21)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This seems very arbitrary. Probably best to throw exception instead. 
</blockquote></details>

OR make it a well named constant if the number actually makes sense

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33008)* status: :shipit: complete! ✓

**Review by johannesHarness — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33008)* status: :shipit: complete! ✓

**Review by johannesHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33008)* status: 1 change requests. 1. unresolved discussions. 

___
*[`930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/33008#-N1mZU4h9rckxb0ZrjP9:-N1zW7Sm2vUH5y_fjbX5:b5ajpi2) ([raw file](https://github.com/harness/harness-core/blob/855d06d8bd898576539aa74857e5c0fe53db96bf/930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java#L21)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

OR make it a well named constant if the number actually makes sense
</blockquote></details>

We should send over the defaultversion and return that, similar to the non-DTO class.

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/beans/ConfigFile.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/33008#-N1mW5FC7hNY5JX2OeJK:-N1ziQ11-hzks_4bFkeI:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/855d06d8bd898576539aa74857e5c0fe53db96bf/400-rest/src/main/java/software/wings/beans/ConfigFile.java#L220)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You can use stream & map collector to make it more readable and "immutable". E.g. 
</blockquote></details>

done

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/resources/ServiceTemplateResource.java` line 185 at r1](https://reviewable.io/reviews/harness/harness-core/33008#-N1mYM5rBHcmnTrKV_H6:-N1ziRhd1lhjQc715Qfx:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/855d06d8bd898576539aa74857e5c0fe53db96bf/400-rest/src/main/java/software/wings/resources/ServiceTemplateResource.java#L185)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

prefer streams, allows you to make objects final (reference immutable)
</blockquote></details>

done

**Comment by raghuAtWings** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/33008#-N1mZ37w3IUtfVkvPPKQ:-N1ziTL00N0mO5Ue-5H5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/855d06d8bd898576539aa74857e5c0fe53db96bf/930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java#L8)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

just correction: 
"or keep `@Data` **AND** make all field private final"
</blockquote></details>

Done.

**Comment by raghuAtWings** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/33008#-N1mZU4h9rckxb0ZrjP9:-N1ziVHMCNAomogCjWqE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/855d06d8bd898576539aa74857e5c0fe53db96bf/930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java#L21)):*
<details><summary><i>Previously, johannesHarness (Johannes Batzill) wrote…</i></summary><blockquote>

We should send over the defaultversion and return that, similar to the non-DTO class.
</blockquote></details>

Done.

**Comment by raghuAtWings** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/33008#-N1m_KdG3646vqgQxYLl:-N1ziXl09wuof9rZWkiQ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/855d06d8bd898576539aa74857e5c0fe53db96bf/930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java#L10)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Also, whatever you decide, all your fields should be private final (makes object more immutable). Either by using `@Value` or making it explicit
</blockquote></details>

done

**Review by johannesHarness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33008)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions.

**Review by johannesHarness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33008)* status: 1 change requests. 2. unresolved discussions.

**Review by puneetsar — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33008)* status: 1 change requests. 2. unresolved discussions.

**Pull request merged**
