### PR TITLE
[feat]: [CDS-82613]: traffic routing dtos optimization and cleanup

### PR DESCRIPTION
**Pull request by markoharness**
## Describe your changes

Reorganized classes around traffic routing steps (bg, canary, traffic routing) configuration.
Code tidy up regarding annotations and UTs.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56729)

### CODE REVIEW

**Comment by markoharness** [comment]
trigger uts

**Comment by alebuh** [comment]
A few more things can be done as part of this PR:
1. We can remove the values field from K8sTrafficRoutingMethodRuleSpec if we are going to support only one value for the method. 
2. With the current implementation even when we are configuring TrafficRouting for BG or Canary we need to specify the type (config or inherit). Is this expected or it will always be Config type for BG and Canary steps?

**Comment by markoharness** [comment]
trigger smartchecks

**Comment by markoharness** [comment]
trigger uts

**Comment by markoharness** [comment]
> A few more things can be done as part of this PR:
> 
> 1. We can remove the values field from K8sTrafficRoutingMethodRuleSpec if we are going to support only one value for the method.
> 2. With the current implementation even when we are configuring TrafficRouting for BG or Canary we need to specify the type (config or inherit). Is this expected or it will always be Config type for BG and Canary steps?


Removed the values field from K8sTrafficRoutingMethodRuleSpec.
Updated the design a bit which will not cause deserialisation issues.

**Comment by markoharness** [comment]
trigger messagecheck

**Review by alebuh — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56729)* status: 20 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/ConfigK8sTrafficRouting.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/56729#-Nlca2g68fxYi9M6s0Oe:-Nlca2g68fxYi9M6s0Of:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/1cfea7b5aa228d59b88a0ddf2149e56c1de3797b/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/ConfigK8sTrafficRouting.java#L21)):*
> ```Java
> import lombok.experimental.SuperBuilder;
> 
> @Value
> ```

same here
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/DefaultK8sTrafficRouting.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/56729#-Nlc_8N84PyhXzl_vNIA:-Nlc_8N84PyhXzl_vNIB:bgdjowx) ([raw file](https://github.com/harness/harness-core/blob/1cfea7b5aa228d59b88a0ddf2149e56c1de3797b/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/DefaultK8sTrafficRouting.java#L21)):*
> ```Java
> import lombok.experimental.SuperBuilder;
> 
> @Value
> ```

nit: do we need this annotation as there aren't any fields?

**Review by alebuh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56729)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/ConfigK8sTrafficRouting.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/56729#-Nlca2g68fxYi9M6s0Oe:-Nlcm3pHDQHUZTY-_hLE:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/1cfea7b5aa228d59b88a0ddf2149e56c1de3797b/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/ConfigK8sTrafficRouting.java#L21)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

same here
</blockquote></details>

removed

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/DefaultK8sTrafficRouting.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/56729#-Nlc_8N84PyhXzl_vNIA:-Nlcm5NA7iaHKfn59WoZ:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/1cfea7b5aa228d59b88a0ddf2149e56c1de3797b/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/DefaultK8sTrafficRouting.java#L21)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

nit: do we need this annotation as there aren't any fields?
</blockquote></details>

removed

**Comment by markoharness** [comment]
trigger uts

**Review by alebuh — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56729)* status: 20 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): k8s-team.

**Comment by markoharness** [comment]
trigger review

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sCanaryStepParameters.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/56729#-NlghdDxECpC7nFNAnRi:-Nlgn8t0-u2GO19jLveZ:b-yaaaj2) ([raw file](https://github.com/harness/harness-core/blob/03843de36f919025bd89812fdfece0cbf79d8184/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sCanaryStepParameters.java#L49)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

qq, We are adding the new command unit here, will it always be as third one?
</blockquote></details>

yes. it will be third one always

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/AbstractK8sTrafficRouting.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/56729#-NlghLZs0WfV1Z2RTnWL:-NlgnGp2-jrwXYmtwZ2m:by83v5z) ([raw file](https://github.com/harness/harness-core/blob/03843de36f919025bd89812fdfece0cbf79d8184/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/AbstractK8sTrafficRouting.java#L27)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor: If this is an interface we could rename AbstractK8sTrafficRouting.
</blockquote></details>

I will rethink about more appropriate name for this and include it in the next PR

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/K8sTrafficRoutingHelper.java` line 235 at r2](https://reviewable.io/reviews/harness/harness-core/56729#-NlgioTO2QbHvkpNAhw7:-NlgnRdJDr1xxKv0he93:b6p6t53) ([raw file](https://github.com/harness/harness-core/blob/03843de36f919025bd89812fdfece0cbf79d8184/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/K8sTrafficRoutingHelper.java#L235)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can we propagate matchType with value EXACT?  When is matchType null?
</blockquote></details>

matchType for now will always be null (as it is supposed to be part of step configuration yaml).
but there might be a default value annoation that we can use instead of null
i will check that and include it in next PR

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/K8sTrafficRoutingSchemaRuleSpec.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/56729#-NlgjToQ3aAKa9kDp_ZD:-NlgnnSW2lVS22hTYfZk:b-jn0vip) ([raw file](https://github.com/harness/harness-core/blob/f07f46db90feac1f7ece26c65eea8efa4ff4ea54/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting/K8sTrafficRoutingSchemaRuleSpec.java#L35)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can we force matchType to be EXACT when it's null, based on the above logic in the mapMatchType method?
</blockquote></details>

there might be a default value annotation that we can use so that it does not end up with null (in that case we could remove the null checking logic from mapMatchType)
i will check that and include it in next PR

**Pull request merged**
