### PR TITLE
feat: [PL-21045]: Fetching yaml from handler

### PR DESCRIPTION
**Pull request by Y0709**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35365)

### CODE REVIEW

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35365)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/handler/Yaml2HandlerFactory.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/35365#-N7PHIQJEPQuuxs74Opk:-N7PHIQK1v02awucN05W:boucwnu) ([raw file](https://github.com/harness/harness-core/blob/091417fff28583d6ae11405b4a51c4eacff13812/400-rest/src/main/java/software/wings/service/impl/yaml/handler/Yaml2HandlerFactory.java#L10)):*
> ```Java
> 
> @Singleton
> public class Yaml2HandlerFactory {
> ```

Why do we need a new factory ?

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35365)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 399 at r2](https://reviewable.io/reviews/harness/harness-core/35365#-N7PHjll3heNUm3XZ9ne:-N7PHjlm487vGk7Qa-1H:b-h21x7v) ([raw file](https://github.com/harness/harness-core/blob/091417fff28583d6ae11405b4a51c4eacff13812/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L399)):*
> ```Java
>       "Used to enable rollback workflow strategy on step failure", HarnessTeam.SPG),
>   COMPARE_YAML_IN_GIT_SYNC(
>       "Compare Yaml of two entities while git-sync (as of now only for application access)", HarnessTeam.SPG),
> ```

@abhinav-harness Rather than keeping spg as team, should we instead keep it as CD, PL etc ?

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35365)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35365)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 399 at r2](https://reviewable.io/reviews/harness/harness-core/35365#-N7PHjll3heNUm3XZ9ne:-N7PjYKQ1XJzGoGcpOJi:b8alyuk) ([raw file](https://github.com/harness/harness-core/blob/091417fff28583d6ae11405b4a51c4eacff13812/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L399)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

@abhinav-harness Rather than keeping spg as team, should we instead keep it as CD, PL etc ?
</blockquote></details>

yeah, anything works, but we have to GA it later so I mentioned team as SPG

**Review by DeepakPatankar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35365)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35365#-:-N7Uv1Cg3wni-uK22yGt:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
