### PR TITLE
fix: [PL-25688]: added hashet optimization in acl

### PR DESCRIPTION
**Pull request by naman-goenka**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34602)

### CODE REVIEW

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34602)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 316 at r1](https://reviewable.io/reviews/harness/harness-core/34602#-N5Dtgn22No-dgz8cZDt:-N5Dtgn22No-dgz8cZDu:b-rr2jg5) ([raw file](https://github.com/harness/harness-core/blob/002a0d44f36fb4c7fe98330d04fc66d6b8699fc9/120-ng-manager/config.yml#L316)):*
> ```YAML
> 
> accessControlClient:
>   enableAccessControl: true
> ```

Revert this config change.
___
*[`120-ng-manager/config.yml` line 333 at r1](https://reviewable.io/reviews/harness/harness-core/34602#-N5DtogoExZxOy7hqOFg:-N5DtogoExZxOy7hqOFh:b-rr2jg5) ([raw file](https://github.com/harness/harness-core/blob/002a0d44f36fb4c7fe98330d04fc66d6b8699fc9/120-ng-manager/config.yml#L333)):*
> ```YAML
>   accessControlServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
>   mockAccessControlService: false
> ```

Revert this config change.

**Review by Jimit09Gandhi — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34602)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34602)* status: 1 file(s) to review.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34602#-:-N5E1Mb8EOXYXEsKrmK9:bnfp4nl)* status: 1 file(s) to review.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34602)* status: 1 file(s) to review. 1 change requests. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/ACLDAOImpl.java` line 154 at r2](https://reviewable.io/reviews/harness/harness-core/34602#-N5E3De5462Ns8O3ssxO:-N5E3De5462Ns8O3ssxP:b-u7f9xx) ([raw file](https://github.com/harness/harness-core/blob/2481d96a70388585dd3023cee7f21aee2f1abeec/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/ACLDAOImpl.java#L154)):*
> ```Java
>     });
> 
>     List<ACL> aclsPresentInDB = aclRepository.getByAclQueryStringInAndEnabled(new ArrayList<>(aclQueryStrings), true);
> ```

Don't create an array list. Instead, change the first argument of getByAclQueryStringInAndEnabled method to take Collection instead of List

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34602#-:-N5EukWU3lQhD0exVfov:bnfp4nl)* status: 1 file(s) to review.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34602#-:-N5EzXBoBDKKJ54wMJ3P:bnfp4nl)* status: 1 file(s) to review.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34602#-:-N5EzklbCQAHLMlGlCSv:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
