### PR TITLE
fix: [DEL-4159]: Remove FF on connector selector and add more info to selection log

### PR DESCRIPTION
**Pull request by jennyjames21**
## Summary
1) remove FF OVERRIDE_CONNECTOR_SELECTOR, with this change connector selector will be overridden if there are selector at pipeline or stage or step level
For more reference on feature
 https://harness.atlassian.net/wiki/spaces/DEL/pages/21046854278/Delegate+Scoping+in+NG
2) Add more information to selector log
      a) Selectors displayed with origin or group by origin
      b) add capability url info to selection log 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34135)

### CODE REVIEW

**Comment by jennyjames21** [comment]
image

**Comment by jennyjames21** [comment]
image

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 5 of 12 files at r1, 22 of 22 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34135)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
image

**Comment by jennyjames21** [comment]
image

**Comment by jennyjames21** [comment]
image

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
image

**Comment by jennyjames21** [comment]
with older version delegate 
image
image

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34135)* status: Some of the checks are too old.

**Comment by jennyjames21** [comment]
:lgtm:

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 4 of 12 files at r1, 19 of 22 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34135)* status: Some of the checks are too old.

**Comment by jennyjames21** [comment]
trigger ti0

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34135)* status: :shipit: complete! ✓

**Pull request merged**
