### PR TITLE
feat: [CDS-77805]: support update for remote services

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes

1. use old service to create service to update
2. Use gitEntityInfo to distinguish bw INLINE and REMOTE services 
3. Calls git entity helper to update the method. Appropriate params like commitId, objectId need to be passed by UI. 
4. Mongo save is done using Retries separately. If git save fails, we don't save in mongo (since it is done first)

Tested
1. Remote service updates at the correct branch
2. Create new branch within the update flow 
3. Error handling for SCM failures 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52536)

### CODE REVIEW

**Comment by hingerabhinav** [comment]
trigger uts

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52536)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 334 at r1](https://reviewable.io/reviews/harness/harness-core/52536#-Ndjqp8C9s_N9mYIz3pK:-Ndjqp8C9s_N9mYIz3pL:b-pi7lnu) ([raw file](https://github.com/harness/harness-core/blob/c5eb742572a91d97ae6c1ae0722bfcad8de65ea4/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L334)):*
> ```Java
>   }
> 
>   private void populateScmDetailsIfRemoteService(ServiceEntity requestService, ServiceEntity oldService) {
> ```

why are we setting these values? Updates should happen only on required fields right?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52536)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/52536#-Ndjr-AL67TWbARKQyd0:-Ndjr-AL67TWbARKQyd1:bgz0330) ([raw file](https://github.com/harness/harness-core/blob/c5eb742572a91d97ae6c1ae0722bfcad8de65ea4/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L114)):*
> ```Java
> 
>       // inline entity
>       if (gitEntityInfo == null || StoreType.INLINE.equals(gitEntityInfo.getStoreType())
> ```

this check should be moved to some util, its pretty generic check

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52536)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/52536#-NdjrWvx2mpGvA3meAM_:-NdjrWvx2mpGvA3meAMa:b7mih7p) ([raw file](https://github.com/harness/harness-core/blob/c5eb742572a91d97ae6c1ae0722bfcad8de65ea4/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L136)):*
> ```Java
>     } catch (Exception e) {
>       log.error(String.format("Error while updating service [%s]", serviceEntity.getIdentifier()), e);
>       throw new InvalidRequestException(
> ```

why's this InvalidRequestException? It should be internalServerErrorException

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52536)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 337 at r1](https://reviewable.io/reviews/harness/harness-core/52536#-NdjrhJz6ooSNb7kUZ4B:-NdjrhJz6ooSNb7kUZ4C:bnm60jl) ([raw file](https://github.com/harness/harness-core/blob/c5eb742572a91d97ae6c1ae0722bfcad8de65ea4/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L337)):*
> ```Java
>     // these details remain unchanged in update flow
>     if (StoreType.REMOTE.equals(oldService.getStoreType())) {
>       requestService.setStoreType(StoreType.REMOTE);
> ```

Just confirming, if the "if" condition isn't true, then do we make sure that storeType already set is INLINE?

**Comment by hingerabhinav** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/52536)_ status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 334 at r1](https://reviewable.io/reviews/harness/harness-core/52536#-Ndjqp8C9s_N9mYIz3pK:-Ndjqp8C9s_N9mYIz3pL:b-pi7lnu) ([raw file](https://github.com/harness/harness-core/blob/c5eb742572a91d97ae6c1ae0722bfcad8de65ea4/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L334)):_
> 
> > ```java
> >   }
> > 
> >   private void populateScmDetailsIfRemoteService(ServiceEntity requestService, ServiceEntity oldService) {
> > ```
> 
> why are we setting these values? Updates should happen only on required fields right?

@mohitg0795 I am using this util io.harness.gitaware.helper.GitAwareEntityHelper#updateEntityOnGit which uses git details of the entity being updated to create an update request. 
We can use just the git request params but this ^^ also makes sure those details remain unchanged in the update flow. What do you think?

**Comment by hingerabhinav** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/52536)_ status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 337 at r1](https://reviewable.io/reviews/harness/harness-core/52536#-NdjrhJz6ooSNb7kUZ4B:-NdjrhJz6ooSNb7kUZ4C:bnm60jl) ([raw file](https://github.com/harness/harness-core/blob/c5eb742572a91d97ae6c1ae0722bfcad8de65ea4/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L337)):_
> 
> > ```java
> >     // these details remain unchanged in update flow
> >     if (StoreType.REMOTE.equals(oldService.getStoreType())) {
> >       requestService.setStoreType(StoreType.REMOTE);
> > ```
> 
> Just confirming, if the "if" condition isn't true, then do we make sure that storeType already set is INLINE?

No the old services being updated would not have storeType set

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52536)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 337 at r1](https://reviewable.io/reviews/harness/harness-core/52536#-NdjrhJz6ooSNb7kUZ4B:-NdnCo7K09YuKvv5m2zZ:b-2l5dr0) ([raw file](https://github.com/harness/harness-core/blob/c5eb742572a91d97ae6c1ae0722bfcad8de65ea4/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L337)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

No the old services being updated would not have storeType set 
</blockquote></details>

Then thats an issue right. It should be set as INLINE.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52536)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 334 at r1](https://reviewable.io/reviews/harness/harness-core/52536#-Ndjqp8C9s_N9mYIz3pK:-NdnDADjBwCIHQrdlmk8:b-r5q3w9) ([raw file](https://github.com/harness/harness-core/blob/c5eb742572a91d97ae6c1ae0722bfcad8de65ea4/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L334)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

@mohitg0795 I am using this util io.harness.gitaware.helper.GitAwareEntityHelper#updateEntityOnGit which uses git details of the entity being updated to create an update request. 
We can use just the git request params but this ^^ also makes sure those details remain unchanged in the update flow. What do you think? 

</blockquote></details>

This increases unnecessary dependency to keep on setting each field. All these things are not changeable in common flow eg: repo can't be changed in update flow atleast for other entities, not sure about services. To update repo or connector, we have separate metadata update api.

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52536)* status: 4 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 334 at r1](https://reviewable.io/reviews/harness/harness-core/52536#-Ndjqp8C9s_N9mYIz3pK:-NeC3NLz1709S3weZGgb:b-jfeksz) ([raw file](https://github.com/harness/harness-core/blob/c5eb742572a91d97ae6c1ae0722bfcad8de65ea4/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L334)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This increases unnecessary dependency to keep on setting each field. All these things are not changeable in common flow eg: repo can't be changed in update flow atleast for other entities, not sure about services. To update repo or connector, we have separate metadata update api.
</blockquote></details>

Done. We're now using the service retrieved and updating select fields only. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 337 at r1](https://reviewable.io/reviews/harness/harness-core/52536#-NdjrhJz6ooSNb7kUZ4B:-NeC3Whx2Y3PfPdkoTpQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c5eb742572a91d97ae6c1ae0722bfcad8de65ea4/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L337)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Then thats an issue right. It should be set as INLINE.
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/52536#-Ndjr-AL67TWbARKQyd0:-NeC3XqS1fugQJc41NwM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c5eb742572a91d97ae6c1ae0722bfcad8de65ea4/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L114)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this check should be moved to some util, its pretty generic check
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/52536#-NdjrWvx2mpGvA3meAM_:-NeC3Yss2xr1beZujTOF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c5eb742572a91d97ae6c1ae0722bfcad8de65ea4/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L136)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why's this InvalidRequestException? It should be internalServerErrorException
</blockquote></details>

Done.

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by hingerabhinav** [comment]
trigger ti2, ti4, ti6, ti7

**Comment by hingerabhinav** [comment]
trigger ut2, ut4, ut6, ut7

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> Dismissed @mohitg0795 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52536)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/52536#-Ndjr-AL67TWbARKQyd0:-NeCiw-LD3QPZYFK72gs:b-jm748c) ([raw file](https://github.com/harness/harness-core/blob/c5eb742572a91d97ae6c1ae0722bfcad8de65ea4/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L114)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There's already helper for this:
```public class GitAwareContextHelper {``` Please use this.

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52536)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/52536#-Ndjr-AL67TWbARKQyd0:-NeCq_hk4z1ucgbAalho:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c5eb742572a91d97ae6c1ae0722bfcad8de65ea4/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L114)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

There's already helper for this:
```public class GitAwareContextHelper {``` Please use this.
</blockquote></details>

Done

**Comment by hingerabhinav** [comment]
trigger uts

**Review by tchaurasiya — DISMISSED** [review]

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Comment by hingerabhinav** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52536)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by hingerabhinav** [comment]
trigger review

**Pull request merged**
