### PR TITLE
[feat]: [CDS-39653]: Added module icons to pipeline

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35949)

### CODE REVIEW

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35949)* status: :shipit: complete! ✓

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35949)

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35949)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 255 at r3](https://reviewable.io/reviews/harness/harness-core/35949#-N8hJZJFEOHBi4Mt7un8:-N8hJZJFEOHBi4Mt7un9:by8d0av) ([raw file](https://github.com/harness/harness-core/blob/0e3dcb686dfe52db4193ef71f019a6f7483159d5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L255)):*
> ```Java
>     // Add Template Module Info temporarily to Pipeline Entity
>     HashSet<String> templateModuleInfo = new HashSet<>();
>     for (TemplateReferenceSummary templateReferenceSummary : templateMergeResponseDTO.getTemplateReferenceSummaries()) {
> ```

Check if this can be null?



_Code quote:_
```Java
templateMergeResponseDTO.getTemplateReferenceSummaries()
```

**Review by archit-harness — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35949)* status: :shipit: complete! ✓

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35949)* status: 1 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 255 at r3](https://reviewable.io/reviews/harness/harness-core/35949#-N8hJZJFEOHBi4Mt7un8:-N8hj5K14W06iKw-AuNf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0e3dcb686dfe52db4193ef71f019a6f7483159d5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L255)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Check if this can be null?
</blockquote></details>

Done.

**Review by inderschera — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35949)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35949)* status: :shipit: complete! ✓

**Pull request merged**
