### PR TITLE
techdebt: [PIE-5202]: Abstract out common code of debezium consumer and add consumer for snapshotting

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42615)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger ti1, ti0, ti2, ti3, ti4

**Comment by shalini-agr** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 643 at r3](https://reviewable.io/reviews/harness/harness-core/42615#-NLtbXnr4AXoilvfrEXA:-NLtbXnr4AXoilvfrEXB:b-qwigsf) ([raw file](https://github.com/harness/harness-core/blob/a1ad8e687ab2175fccbcc2fa97c12b1279ac5947/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L643)):*
> ```Java
>     pipelineEventConsumerController.register(injector.getInstance(CreatePartialPlanRedisConsumer.class), 2);
>     pipelineEventConsumerController.register(injector.getInstance(PipelineExecutionSummaryCDRedisEventConsumer.class),
>         appConfig.getDebeziumConsumerConfigs().get(0).getNumberOfThreads());
> ```

Can we add a comment here to not use index but use identifier rather so that easier to understand.

**Comment by sahilhindwani-harness** [comment]
*[`debezium-service/config/config.yml` line 57 at r3](https://reviewable.io/reviews/harness/harness-core/42615#-NLtbkFJDAqDYcUozj5f:-NLtbkFJDAqDYcUozj5g:b-yiobe) ([raw file](https://github.com/harness/harness-core/blob/a1ad8e687ab2175fccbcc2fa97c12b1279ac5947/debezium-service/config/config.yml#L57)):*
> ```YAML
>     heartbeat.interval.ms: ${HEARTBEAT_INTERVAL_MS:-10000}
>     mongodb.connection.string: ${MONGODB_CONNECTION_STRING:-mongodb://localhost:27017}
>   - isEnabled: ${IS_ENABLED_SNAPSHOT:-true}
> ```

Should we come up with some naming convention for this till we starting using config management or something?
We have added snapshot in this but what about a new collection for which we need snapshot?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/config/config.yml` line 517 at r3](https://reviewable.io/reviews/harness/harness-core/42615#-NLtc7pL1ISVsN5m6wKK:-NLtc7pM8PAGwuKNqL3t:b-kjdh75) ([raw file](https://github.com/harness/harness-core/blob/a1ad8e687ab2175fccbcc2fa97c12b1279ac5947/pipeline-service/config/config.yml#L517)):*
> ```YAML
> lockNotifyResponseCleanup: ${LOCK_NOTIFY_RESPONSE_CLEANUP:-true}
> 
> eventsFrameworkSnapshot:
> ```

Should we call it snapshotDebeziumConsumerConfig?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 17 files at r1, 4 of 6 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42615)* status: 23 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42615)* status: 31 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 643 at r3](https://reviewable.io/reviews/harness/harness-core/42615#-NLtbXnr4AXoilvfrEXA:-NLu-PPw39XHyL9lRUT-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a1ad8e687ab2175fccbcc2fa97c12b1279ac5947/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L643)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we add a comment here to not use index but use identifier rather so that easier to understand.
</blockquote></details>

Done.
___
*[`pipeline-service/config/config.yml` line 517 at r3](https://reviewable.io/reviews/harness/harness-core/42615#-NLtc7pL1ISVsN5m6wKK:-NLu-SFi5tb1ByF8-BLI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a1ad8e687ab2175fccbcc2fa97c12b1279ac5947/pipeline-service/config/config.yml#L517)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should we call it snapshotDebeziumConsumerConfig?
</blockquote></details>

Done.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42615)* status: 41 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`debezium-service/config/config.yml` line 57 at r3](https://reviewable.io/reviews/harness/harness-core/42615#-NLtbkFJDAqDYcUozj5f:-NLu6gcZ-gMOaM8DIECN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a1ad8e687ab2175fccbcc2fa97c12b1279ac5947/debezium-service/config/config.yml#L57)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should we come up with some naming convention for this till we starting using config management or something?
We have added snapshot in this but what about a new collection for which we need snapshot?
</blockquote></details>

Done.

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 6 of 17 files at r1, 2 of 6 files at r2, 7 of 9 files at r3, 12 of 15 files at r4, 8 of 9 files at r5, 3 of 3 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42615)* status: 26 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 481 at r7](https://reviewable.io/reviews/harness/harness-core/42615#-NLxtHdcEgSJFX5zw59S:-NLxtHdcEgSJFX5zw59T:bw4zqrr) ([raw file](https://github.com/harness/harness-core/blob/eef828f808fbdd0c718e518beddf24b08692fa7e/120-ng-manager/config.yml#L481)):*
> ```YAML
> debeziumConsumersConfigs:
>   planExecutionsSummaryStreaming:
>     topicName: ${DEBEZIUM_CONSUMER_TOPIC_NAME:-DEBEZIUM_pmsMongo.pms-harness.planExecutionsSummary}
> ```

rename to topic
___
*[`120-ng-manager/config.yml` line 482 at r7](https://reviewable.io/reviews/harness/harness-core/42615#-NLxtJC88IP94qcfhqW4:-NLxtJC9Ee5vkDddsRxq:b-gg4j0f) ([raw file](https://github.com/harness/harness-core/blob/eef828f808fbdd0c718e518beddf24b08692fa7e/120-ng-manager/config.yml#L482)):*
> ```YAML
>   planExecutionsSummaryStreaming:
>     topicName: ${DEBEZIUM_CONSUMER_TOPIC_NAME:-DEBEZIUM_pmsMongo.pms-harness.planExecutionsSummary}
>     numberOfThreads: ${DEBEZIUM_CONSUMER_THREADS:-2}
> ```

rename to threads
___
*[`120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDChangeEventHandler.java` line 26 at r7](https://reviewable.io/reviews/harness/harness-core/42615#-NLxttluCR1mwBByYKPm:-NLxttluCR1mwBByYKPn:b-jppbfs) ([raw file](https://github.com/harness/harness-core/blob/eef828f808fbdd0c718e518beddf24b08692fa7e/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDChangeEventHandler.java#L26)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public class PipelineExecutionSummaryCDChangeEventHandler
>     extends io.harness.eventHandler.DebeziumAbstractRedisEventHandler {
> ```

add import statement
___
*[`958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java` line 109 at r7](https://reviewable.io/reviews/harness/harness-core/42615#-NLxue882O8BAkk7-eXT:-NLxue882O8BAkk7-eXU:b64aauz) ([raw file](https://github.com/harness/harness-core/blob/eef828f808fbdd0c718e518beddf24b08692fa7e/958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java#L109)):*
> ```Java
>     // debeziumChangeEvent.getKey() gives id of the Document which is unique
>     String eventKey = CACHE_PREFIX + debeziumChangeEvent.getKey();
>     String lockName = LOCK_PREFIX + eventKey;
> ```

why this lock is needed

**Comment by shalini-agr** [comment]
*[`958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java` line 109 at r7](https://reviewable.io/reviews/harness/harness-core/42615#-NLxue882O8BAkk7-eXT:-NLy4oAD8sZrODIy5xAr:bgj5r42) ([raw file](https://github.com/harness/harness-core/blob/eef828f808fbdd0c718e518beddf24b08692fa7e/958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java#L109)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

why this lock is needed
</blockquote></details>

if we run multiple threads of consumer, we need to make sure, only one of them processes the event

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42615)* status: 32 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 481 at r7](https://reviewable.io/reviews/harness/harness-core/42615#-NLxtHdcEgSJFX5zw59S:-NLy5rTk56yMJJQLwO5T:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eef828f808fbdd0c718e518beddf24b08692fa7e/120-ng-manager/config.yml#L481)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

rename to topic
</blockquote></details>

Done.
___
*[`120-ng-manager/config.yml` line 482 at r7](https://reviewable.io/reviews/harness/harness-core/42615#-NLxtJC88IP94qcfhqW4:-NLy5qzs8zs4_4TDh3Vz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eef828f808fbdd0c718e518beddf24b08692fa7e/120-ng-manager/config.yml#L482)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

rename to threads
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDChangeEventHandler.java` line 26 at r7](https://reviewable.io/reviews/harness/harness-core/42615#-NLxttluCR1mwBByYKPm:-NLy5_ZWAkeNi5m5my-R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eef828f808fbdd0c718e518beddf24b08692fa7e/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDChangeEventHandler.java#L26)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

add import statement
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java` line 109 at r7](https://reviewable.io/reviews/harness/harness-core/42615#-NLxue882O8BAkk7-eXT:-NLy5_O58NO-lT4YWANf:b-ue6gud) ([raw file](https://github.com/harness/harness-core/blob/eef828f808fbdd0c718e518beddf24b08692fa7e/958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java#L109)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Event if you run multiple threads they would just be a s multiple consumers in a consumer group 
</blockquote></details>

In-order to guarantee that one thread only processed the event with the given key, this lock is required.
Assume that we have got two event e1 and e2,  e2 occurred after e1. 

In e1, startTs is t1
In e2, startTs is t2; t2> t1

There are 2 pods of consumer running, pod p1 and p2
p1 consumed e1
p2 consumed e2

Because of some reason p1 became slow and p2 consumed e2 fast then we will run into some stale updates in timescale. This lock saves us from that.

How?
We have started storing timestamp in redis cache and have wrapped this code around lock. so now what will happen will be
In e1, startTs is t1
In e2, startTs is t2; t2> t1

There are 2 pods of consumer running, pod p1 and p2
p1 consumed e1
p2 consumed e2

Because of some reason p1 became slow and p2 consumed e2 fast then we will run into some stale updates in timescale. 

How this lock will help?
This lock saves us from that when combined with the redis timestamp which we store.

Let us take the same case now
Since p1 became slow and p2 consumed e2 first, because of this lock p1 will wait and the currentTimestamp inside cache will be updated to t2. Now P1 will resume and since t1<t2, it will be a no-op.


We are aware that this might cause some scale issues if we get the event from same planExecutionId. We can optimise this logic a little more by not waiting to acquire lock but rather only checking if lock can be acquired or not.. If yes, then proceed else don't ack the event and we will get a retry from redis in some time. Concept would be similar to GraphUpdateDispatcher.

**Review by hextechpal — APPROVED** [review]
> Reviewed 3 of 13 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42615)* status: 32 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java` line 109 at r7](https://reviewable.io/reviews/harness/harness-core/42615#-NLxue882O8BAkk7-eXT:-NLzOe6l7KiWnhvmBWaG:b-mtu1yd) ([raw file](https://github.com/harness/harness-core/blob/eef828f808fbdd0c718e518beddf24b08692fa7e/958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java#L109)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

In-order to guarantee that one thread only processed the event with the given key, this lock is required.
Assume that we have got two event e1 and e2,  e2 occurred after e1. 

In e1, startTs is t1
In e2, startTs is t2; t2> t1

There are 2 pods of consumer running, pod p1 and p2
p1 consumed e1
p2 consumed e2

Because of some reason p1 became slow and p2 consumed e2 fast then we will run into some stale updates in timescale. This lock saves us from that.

How?
We have started storing timestamp in redis cache and have wrapped this code around lock. so now what will happen will be
In e1, startTs is t1
In e2, startTs is t2; t2> t1

There are 2 pods of consumer running, pod p1 and p2
p1 consumed e1
p2 consumed e2

Because of some reason p1 became slow and p2 consumed e2 fast then we will run into some stale updates in timescale. 

How this lock will help?
This lock saves us from that when combined with the redis timestamp which we store.

Let us take the same case now
Since p1 became slow and p2 consumed e2 first, because of this lock p1 will wait and the currentTimestamp inside cache will be updated to t2. Now P1 will resume and since t1<t2, it will be a no-op.


We are aware that this might cause some scale issues if we get the event from same planExecutionId. We can optimise this logic a little more by not waiting to acquire lock but rather only checking if lock can be acquired or not.. If yes, then proceed else don't ack the event and we will get a retry from redis in some time. Concept would be similar to GraphUpdateDispatcher.

</blockquote></details>

So we are ensuring ordering and just dropping older events, this will not work when we want to make partial updates as we get complete document then probably it is ok to drop this event. This is ok for now but we need to do better here

@shalini-agr can you put this as a comment in our  codebase itself as welll

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42615)* status: 32 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java` line 109 at r7](https://reviewable.io/reviews/harness/harness-core/42615#-NLxue882O8BAkk7-eXT:-NLzfPAA2GTntRSzCfJi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eef828f808fbdd0c718e518beddf24b08692fa7e/958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java#L109)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

So we are ensuring ordering and just dropping older events, this will not work when we want to make partial updates as we get complete document then probably it is ok to drop this event. This is ok for now but we need to do better here

@shalini-agr can you put this as a comment in our  codebase itself as welll  
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java` line 109 at r7](https://reviewable.io/reviews/harness/harness-core/42615#-NLxue882O8BAkk7-eXT:-NM-60CQ8daQn6ixNOZ1:b-rqtcc8) ([raw file](https://github.com/harness/harness-core/blob/eef828f808fbdd0c718e518beddf24b08692fa7e/958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java#L109)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yes @hextechpal, we need to do better here if we start utilising partial updates. @shalini-agr , can you create a ticket and assign to me for handling it better?

**Comment by shalini-agr** [comment]
*[`958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java` line 109 at r7](https://reviewable.io/reviews/harness/harness-core/42615#-NLxue882O8BAkk7-eXT:-NM2FaBPAr9Ap517s3Th:berxwv0) ([raw file](https://github.com/harness/harness-core/blob/eef828f808fbdd0c718e518beddf24b08692fa7e/958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java#L109)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Yes @hextechpal, we need to do better here if we start utilising partial updates. @shalini-agr , can you create a ticket and assign to me for handling it better?
</blockquote></details>

Done: https://harness.atlassian.net/browse/PIE-7724

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 8 of 15 files at r4, 8 of 9 files at r5, 2 of 3 files at r6, 1 of 3 files at r7, 12 of 13 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42615)* status: 2 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42615)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42615)* status: :shipit: complete! ✓

**Pull request merged**
