### PR TITLE
fix: [CDS-42003]: Fixed illegal group reference on delegate issue

### PR DESCRIPTION
**Pull request by acasian-harness**
## Describe your changes

1. Fixed illegal group reference on delegate issue
2. Fixed null pointer on delegate when working dir doesn't exist
3. Removed validation if step is doesn't contain looping strategy
4. Allow command step to run on delegate without looping strategy
5. Remove exception if no hosts were fetched in infras
6. Added infra step logs as suggested in ticket

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36857)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* Code issue 3 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36857)

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 8 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36857#-:-NAa36jOC8mgjEqtAxo_:bnfp4nl)* status: :shipit: complete! ✓

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshExecutorFactoryContext.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/36857#-NAa0M46D-H596_UjHUo:-NAa0M46D-H596_UjHUp:bdr288f) ([raw file](https://github.com/harness/harness-core/blob/8abf08c446c49a717a747318058307171b5dc017/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshExecutorFactoryContext.java#L59)):*
> ```Java
>         try {
>           text = text.replaceAll("\\$" + key, value);
>         } catch (IllegalArgumentException exception) {
> ```

Minor - we could write msg to the error level with full stack trace log.error(msg, ex)

**Review by acasian-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36857)* status: 1. unresolved discussions. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshExecutorFactoryContext.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/36857#-NAa0M46D-H596_UjHUo:-NAcK0r0BJ-M6-B7FasJ:b-hmk2me) ([raw file](https://github.com/harness/harness-core/blob/8abf08c446c49a717a747318058307171b5dc017/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshExecutorFactoryContext.java#L59)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - we could write msg to the error level with full stack trace log.error(msg, ex)
</blockquote></details>

That's exactly the reason why it is not showing as error, since there is nothing we can fix and cluttering the logs with those errors will lead in task to clean up the error messages.

**Review by ivan-83 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36857)* status: :shipit: complete! ✓

**Pull request merged**
