### PR TITLE
fix: [CDS-79113]: Fix condition for comparing strategy metadata instead of…

### PR DESCRIPTION
**Pull request by Y0709**
… comparing the entire object

Context: We recently found a bug where post prod rollback was not getting triggered due to version mismatch of ng-manger and pipeline service. The reason for that is that in the newer release we added another field in strategy metadata which was not present in the older version so while comparing we are comparing the entire strategyMetadata object of the child with strategyMetdata in the strategyMetadataMap which is formed while execution. We have this check basically to filter the correct iteration that is being rolled back hence we dont need to compare the entire strategy metadata as fields can be added or removed there and we might observe this issue again. hence we have changed the condition to just use the current iteration and total iterations

Testing -- Tested multi svc/ env post prod rollback with different versions of ng-manager and pipeline svc as well as same versions.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52920)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 207 at r1](https://reviewable.io/reviews/harness/harness-core/52920#-NeIicea1w59bSB9EhkG:-NeIicea1w59bSB9EhkH:b-6zu9vw) ([raw file](https://github.com/harness/harness-core/blob/d4b62dfcf535fb1a5cb41e34bd7003932f1fd14d/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L207)):*
> ```Java
>   }
> 
>   private boolean checkIfChildStrategyMetaDataPresent(
> ```

We can pass only currentIteration in execution metadata
Since it is already planned for execution metadata cleanup, we can tackle during that time.

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52920)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 207 at r1](https://reviewable.io/reviews/harness/harness-core/52920#-NeIk33I1xi6nLjMRTTC:-NeNdqYq9I3sr9kw-c2D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d4b62dfcf535fb1a5cb41e34bd7003932f1fd14d/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L207)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can be better like childStrategyisPresentInParentMetadata
</blockquote></details>

Done.

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger ut3, ut4

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 215 at r2](https://reviewable.io/reviews/harness/harness-core/52920#-NeaTUhh3jTXPkcGZ2du:-NeaTUhh3jTXPkcGZ2dv:blw4bka) ([raw file](https://github.com/harness/harness-core/blob/833e689b9831f780ce61bd95d0fe36f86a0c4542/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L215)):*
> ```Java
>     Set<Integer> strategyIterationsToBeRolledBack = new HashSet<>();
>     for (StrategyMetadata strategyMetadata : strategyMetadataList) {
>       strategyIterationsToBeRolledBack.add(strategyMetadata.getCurrentIteration());
> ```

nit: we can use streams also for this

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52920)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52920)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52920)* status: :shipit: complete! ✓

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 220 at r3](https://reviewable.io/reviews/harness/harness-core/52920#-Neb0PjR5Zv3faGpQEZI:-Neb0PjR5Zv3faGpQEZJ:bdfusya) ([raw file](https://github.com/harness/harness-core/blob/215124a28a110d369ba781d7dc2fdbdcedbabd12/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L220)):*
> ```Java
>   }
> 
>   private boolean checkIfChildStrategyMetaDataPresentInPostExecutionRollbackStageStrategyMetadata(
> ```

nit: @sahilhindwani-harness do you think we can rename this to checkIfChildStrategyMetaDataPresentInRollbackStageStrategyMetadata

**Comment by Y0709** [comment]
trigger review

**Pull request closed without merging**
