### PR TITLE
[feat]: [PIE-4745]: Add invalid input sets list to merge API

### PR DESCRIPTION
**Pull request by namanvermah**
If the merge request has some invalid input sets, then the merge call will now give a list of the invalid references in the response. This will be used by UI to show a reconcile button in front of every invalid input set they selected.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36134)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36134)

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36134)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/inputset/InputSetErrorWrapperDTOPMS.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/36134#-N8wkALVE6mnCxneKkl1:-N8wkALX1W4w_BzrKy83:b-qehjm6) ([raw file](https://github.com/harness/harness-core/blob/a29345af4aece830d5e51b6f25dd8e1187681d7f/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/inputset/InputSetErrorWrapperDTOPMS.java#L34)):*
> ```Java
>   @Schema(description = InputSetSchemaConstants.INPUT_SET_UUID_TO_ERROR_YAML_MESSAGE)
>   Map<String, InputSetErrorResponseDTOPMS> uuidToErrorResponseMap;
>   @Schema(description = "List of Input Sets that caused the error") List<String> invalidInputSetReferences;
> ```

"that are invalid" ?



_Code quote:_
```Java
caused the error
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36134)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/inputset/InputSetErrorWrapperDTOPMS.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/36134#-N8wkALVE6mnCxneKkl1:-N8wkqo33VFlRUjttfrm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a29345af4aece830d5e51b6f25dd8e1187681d7f/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/inputset/InputSetErrorWrapperDTOPMS.java#L34)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

"that are invalid" ?
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36134)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36134)* status: :shipit: complete! ✓

**Pull request merged**
