### PR TITLE
feat: [CDS-81115]: remote service execution and linking

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
1. Set Source Principal in filter creation, Service step execution, variable creation
2. Use transient branch context to fetch service in above flows and reconciliation
3. fetch without cache when validating/refreshing inputs 
4. Add git branch to step parameters 
5. Use entity instead of YAML in filter json creator. 
6. Added new method to visitor factory to provide additional context. This context is used to set SetupMetadata which is used by Source Principal guard to set the correct principal wherever required. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53943)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/filters/FilterCreatorService.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/53943#-NgOVIDN3ffyHPjOUsAf:-NgOVIDN3ffyHPjOUsAg:bbi3r5t) ([raw file](https://github.com/harness/harness-core/blob/523df62c0a1ea6db219abca2cff70944b5cec171/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/filters/FilterCreatorService.java#L68)):*
> ```Java
>     // set source principal based on setupMetadata
>     SourcePrincipalContextBuilder.setSourcePrincipal(PmsSecurityContextGuardUtils.getPrincipal(
>         setupMetadata.getAccountId(), setupMetadata.getPrincipalInfo(), setupMetadata.getTriggeredInfo()));
> ```

lets get reviewed from pipeline team

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 8 of 12 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53943)* status: 12 file(s) to review. 0 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/filters/FilterCreatorService.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/53943#-NgOW0Kh6Pl83UdoLcRJ:-NgOW0Kh6Pl83UdoLcRK:b-69thod) ([raw file](https://github.com/harness/harness-core/blob/523df62c0a1ea6db219abca2cff70944b5cec171/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/filters/FilterCreatorService.java#L67)):*
> ```Java
> 
>     // set source principal based on setupMetadata
>     SourcePrincipalContextBuilder.setSourcePrincipal(PmsSecurityContextGuardUtils.getPrincipal(
> ```

we should use try-with-resources here and clear the thread context

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53943)* status: 13 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java` line 128 at r2](https://reviewable.io/reviews/harness/harness-core/53943#-NgOVCI573vXhVnrYhGX:-NgT9uKP-XeZAQCnGsZ_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/523df62c0a1ea6db219abca2cff70944b5cec171/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java#L128)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this need not be a parameter field and same below
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/filters/FilterCreatorService.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/53943#-NgOW0Kh6Pl83UdoLcRJ:-NgT9w425OSjzpEPZqg9:b-v1v8nb) ([raw file](https://github.com/harness/harness-core/blob/523df62c0a1ea6db219abca2cff70944b5cec171/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/filters/FilterCreatorService.java#L67)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should use try-with-resources here and clear the thread context
</blockquote></details>

Since we're passing the creating the principal from setup metadata, it is correct principal passed and is okay for now. Discussed with @archit-harness.

**Comment by hingerabhinav** [comment]
trigger uts

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53943)* status: 13 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/filters/FilterCreatorService.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/53943#-NgOW0Kh6Pl83UdoLcRJ:-NgTHvK0CZaVoQbATL0p:bpxmva1) ([raw file](https://github.com/harness/harness-core/blob/523df62c0a1ea6db219abca2cff70944b5cec171/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/filters/FilterCreatorService.java#L67)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

Since we're passing the creating the principal from setup metadata, it is correct principal passed and is okay for now. Discussed with @archit-harness.
</blockquote></details>

@hingerabhinav can we put this try with resources in the respective step, as i am not sure even with this right approach -> if existing step will get impacted

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53943)* status: 13 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/filters/FilterCreatorService.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/53943#-NgOW0Kh6Pl83UdoLcRJ:-NgTIRMz6ReFsUUKMIL5:bpg7prq) ([raw file](https://github.com/harness/harness-core/blob/523df62c0a1ea6db219abca2cff70944b5cec171/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/filters/FilterCreatorService.java#L67)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@hingerabhinav can we put this try with resources in the respective step, as i am not sure even with this right approach -> if existing step will get impacted
</blockquote></details>

Yes with user principal being set, some RBAC checks might get affected. So we will need to pass the setup metadata through each of the individual visitor.

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by hingerabhinav** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 5 files at r3, 2 of 2 files at r4, 4 of 7 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53943)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by hingerabhinav** [comment]
trigger ut5, ut6, ut8, ut9, messagecheck

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 2 of 7 files at r5, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53943)* status: Some of the checks are too old. 13 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53943)* status: Some of the checks are too old. 13 file(s) to review.

**Comment by hingerabhinav** [comment]
trigger review

**Pull request merged**
