### PR TITLE
[fix]: [CDS-68094]: Error message Improvement when secret is refererred inside a secret.

### PR DESCRIPTION
**Pull request by vtxorxwitty**
## Describe your changes
This PR contains changes regarding the error message improvement when a secret is referred inside a secret.

## Testing
Tested the changes locally.  
Scenarios tested - Tested when a secret is referred inside a secret.

## Steps to repro -> 
1. Create a stage template with a shell script:
shell script env vars:
FOO=<+stage.variables.github_token>

2. Create a stage variable:
github_token (secret) <+input>

3. Create a pipeline template that uses this stage template:

4. Create a pipeline variables:
github_token (secret) <+input>

5. Assign the value of stage variable inside the template as:
github_token <+pipeline,variables.github_token>

 
6. Create a pipeline from the pipeline template:

7. Assign the value of pipeline variable with actual secret:
github_token (secret) = actual secret

## Screenshot of the error message - 
Screenshot 2023-05-03 at 6 26 45 PM

## Impact - 
The changes will only affect the flow when a secret is being referred inside a secret.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47227)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/JexlRuntimeExceptionHandler.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/47227#-NUSL9PjAbecs_EwYEY1:-NUSL9PjAbecs_EwYEY2:bbdhgqo) ([raw file](https://github.com/harness/harness-core/blob/355da0617874440be716bb2123ea712085fd75be/980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/JexlRuntimeExceptionHandler.java#L49)):*
> ```Java
>     String message = ExceptionUtils.getMessage(ex);
> 
>     if (ex.getCause().getMessage().equals("Secret referencing inside a secret is not supported.")) {
> ```

The equals condition should be reversed. "CONSTANT.equals(variable)"

**Comment by mohitg0795** [comment]
*[`980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/JexlRuntimeExceptionHandler.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/47227#-NUSLKRG8rVT0aMY6MBO:-NUSLKRH-U7zg-N0aWtw:ba1ao78) ([raw file](https://github.com/harness/harness-core/blob/355da0617874440be716bb2123ea712085fd75be/980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/JexlRuntimeExceptionHandler.java#L49)):*
> ```Java
>     String message = ExceptionUtils.getMessage(ex);
> 
>     if (ex.getCause().getMessage().equals("Secret referencing inside a secret is not supported.")) {
> ```

This looks too much hardcoded logic, is it discussed and this is the only way to achieve something at the moment?

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47227)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/JexlRuntimeExceptionHandler.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/47227#-NUSL9PjAbecs_EwYEY1:-NUWWYJUEei2Q7gZcDqV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/355da0617874440be716bb2123ea712085fd75be/980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/JexlRuntimeExceptionHandler.java#L49)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The equals condition should be reversed. "CONSTANT.equals(variable)"
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/JexlRuntimeExceptionHandler.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/47227#-NUSLKRG8rVT0aMY6MBO:-NUWWYYiDmQ7Uta1l8Ad:b-et8og9) ([raw file](https://github.com/harness/harness-core/blob/355da0617874440be716bb2123ea712085fd75be/980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/JexlRuntimeExceptionHandler.java#L49)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This looks too much hardcoded logic, is it discussed and this is the only way to achieve something at the moment?
</blockquote></details>

Yes this is required when secret is referenced inside a secret. We don't support it in CG and expect a better error message in NG. Discussed these changes with @archit-harness

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47227)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by inderschera — APPROVED** [review]

**Comment by vtxorxwitty** [comment]
trigger review

**Pull request merged**
