### PR TITLE
[feat]: [SMP-663]: Add SMP license generator to license service

### PR DESCRIPTION
**Pull request by kapilgarg1996**
## Describe your changes

Document: https://harness.atlassian.net/wiki/spaces/ONPREM/pages/21165965967/SMP+Licensing

- This PR handles the generation of license using smp-license library.
- The generation API fetches the account and module licenses data from db which is already put there during onprem customer onboarding through admin tool.
- It also migrates the existing accounts with a new property added `smpAccount` which signifies if the account is an smp account

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37958)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 10 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 9 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37958)

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 2 of 13 files at r1, 13 of 13 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37958)* status: :shipit: complete! ✓

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37958)* status: :shipit: complete! ✓

**Comment by arya-harness** [comment]
trigger feature-build

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37958)* status: :shipit: complete! ✓

**Comment by kapilgarg1996** [comment]
trigger ti0

**Comment by kapilgarg1996** [comment]
trigger ti3

**Comment by kapilgarg1996** [comment]
trigger ti4

**Comment by kapilgarg1996** [comment]
trigger ti3

**Review by gunascode — APPROVED** [review]
> Reviewed 1 of 13 files at r1, 5 of 13 files at r2, 7 of 10 files at r4, 2 of 9 files at r5, 4 of 4 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37958)* status: :shipit: complete! ✓

**Pull request merged**
