### PR TITLE
fix: [PL-26599]: Make project and organization names case insensitive in API query

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes
Make project and organization entity names case insensitive when querying via API, conforming with UI behavior.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35552)

### CODE REVIEW

**Comment by vcalasansh** [comment]
trigger messagecheck

**Comment by vcalasansh** [comment]
trigger messagecheck

**Review by Fernando-Dourado — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35552)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 245 at r1](https://reviewable.io/reviews/harness/harness-core/35552#-N7SVR9PDh95oTs8mp5D:-N7SVR9PDh95oTs8mp5E:b-c9tup2) ([raw file](https://github.com/harness/harness-core/blob/9f83d100052b4af0861283d6301324f7b8a3beb0/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L245)):*
> ```Java
> 
>   @Override
>   public Optional<Organization> get(String accountIdentifier, String organizationIdentifier) {
> ```

Please, add one simple unit test to verify the use of the repository.

**Comment by abhinav-harness** [comment]
IMO we should be case sensitive in all the scenarios. 
| see the same behavior in project etc?

**Review by Fernando-Dourado — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35552)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by Fernando-Dourado — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35552)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by vcalasansh** [comment]
trigger messagecheck

**Review by Fernando-Dourado — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35552)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by Fernando-Dourado — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35552)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by lasdox — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35552)* status: :shipit: complete! ✓

**Pull request merged**
