### PR TITLE
fix:[PL-30195] Code guard to avoid NPE when accessing includedScope field

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- Code guard to avoid NPE when accessing included scope field

Screen Shot 2022-12-02 at 18 06 10

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41056)

### CODE REVIEW

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41056)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41056)* status: :shipit: complete! ✓

**Review by reetika04 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41056)* status: :shipit: complete! ✓

**Review by manish-manchanda — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41056)* status: :shipit: complete! ✓

**Pull request merged**
