### PR TITLE
feat: [PL-31584]: enhance the code to support limit in CG

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
enhance the code to support limit on the documents fetched by mongoDb in CG

tested the code by setting less limits and querying using UTs

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45840)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45840)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/impl/DashboardStatisticsServiceImplTest.java` line 523 at r1](https://reviewable.io/reviews/harness/harness-core/45840#-NRlA2Vn5lGaZB-0WkDc:-NRlA2Vn5lGaZB-0WkDd:byxqib7) ([raw file](https://github.com/harness/harness-core/blob/bbd34ab42cd8ba8f98451487148035e119c66777/400-rest/src/test/java/software/wings/service/impl/DashboardStatisticsServiceImplTest.java#L523)):*
> ```Java
>   @Owner(developers = ABHINAV)
>   @Category(UnitTests.class)
>   public void testUsageMetrics() {
> ```

Why did we remove this test?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45840)* status: 21 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/impl/DashboardStatisticsServiceImplTest.java` line 523 at r1](https://reviewable.io/reviews/harness/harness-core/45840#-NRlA2Vn5lGaZB-0WkDc:-NRla6dgAJfMbQpSCwLy:bwho5b6) ([raw file](https://github.com/harness/harness-core/blob/bbd34ab42cd8ba8f98451487148035e119c66777/400-rest/src/test/java/software/wings/service/impl/DashboardStatisticsServiceImplTest.java#L523)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why did we remove this test?
</blockquote></details>

It is for a method, that was not used anywhere and fetching lot of data, I have removed that method, so that no one will use that blindly as it is loading unlimited data.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45840#-:-NRlbohW4G_YRwTUTUPF:bnfp4nl)* status: 21 file(s) to review. 1 of 2 approvals obtained.

**Comment by bhavya181** [comment]
trigger ut1, ut3, ut6

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45840#-:-NSFLEo-A0ylrMyg_MRV:bnfp4nl)* status: Some of the checks are too old. 25 file(s) to review. 1 of 2 approvals obtained.

**Review by nikunj-badjatya — APPROVED** [review]
> Reviewed 14 of 21 files at r1, 1 of 1 files at r2, 7 of 7 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45840)* status: Some of the checks are too old.

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 2 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45840)* status: 3 file(s) to review.

**Pull request merged**
