### PR TITLE
feat: [IDP-287]: Dynamic creation of app-config based on git integrat…

### PR DESCRIPTION
**Pull request by devesh-harness**
…ion connector

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45471)

### CODE REVIEW

**Comment by devesh-harness** [comment]
trigger messagecheck

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45471)* status: 21 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/configmanager/ConfigType.java` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/45471#-NRBqeiAAcqNCqROuteN:-NRBqeiAAcqNCqROuteO:b-ip7qcw) ([raw file](https://github.com/harness/harness-core/blob/23820ba6b52df6d8b574206d4085a1fb9e4abf2a/idp-service/src/main/java/io/harness/idp/configmanager/ConfigType.java#L15)):*
> ```Java
> @OwnedBy(HarnessTeam.IDP)
> public enum ConfigType {
>   PLUGIN_CONFIG,
> ```

Just PLUGINS ?
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/beans/entity/AppConfigEntity.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/45471#-NRBqTPeAxSqhyW5eGJl:-NRBqTPfBPRzaHHVUyxE:b-49hjet) ([raw file](https://github.com/harness/harness-core/blob/23820ba6b52df6d8b574206d4085a1fb9e4abf2a/idp-service/src/main/java/io/harness/idp/configmanager/beans/entity/AppConfigEntity.java#L47)):*
> ```Java
>                  .field(AppConfigEntityKeys.accountIdentifier)
>                  .field(AppConfigEntityKeys.configId)
>                  //                 .field(AppConfigEntityKeys.configType)
> ```

Compound index will be on account + config_id right ? If so, please change the index name and this commented line
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/mappers/AppConfigMapper.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/45471#-NRBqimY1VvIfQ0K6Qc8:-NRBqimY1VvIfQ0K6Qc9:bbcpb7q) ([raw file](https://github.com/harness/harness-core/blob/23820ba6b52df6d8b574206d4085a1fb9e4abf2a/idp-service/src/main/java/io/harness/idp/configmanager/mappers/AppConfigMapper.java#L22)):*
> ```Java
>   public AppConfig toDTO(AppConfigEntity appConfigEntity) {
>     AppConfig appConfig = new AppConfig();
>     appConfig.setConfigId(appConfigEntity.getConfigId());
> ```

Are we not setting the configType in from and to DTO methods ?
___
*[`idp-service/src/main/java/io/harness/idp/onboarding/services/impl/OnboardingServiceImpl.java` line 647 at r2](https://reviewable.io/reviews/harness/harness-core/45471#-NRBrKpp0hu6HyJ_cTL5:-NRBrKpp0hu6HyJ_cTL6:b-i9exjp) ([raw file](https://github.com/harness/harness-core/blob/23820ba6b52df6d8b574206d4085a1fb9e4abf2a/idp-service/src/main/java/io/harness/idp/onboarding/services/impl/OnboardingServiceImpl.java#L647)):*
> ```Java
>   }
> 
>   private void createCatalogInfraConnectorSecretInBackstageK8S(
> ```

I suggest the following. Rename this function to "createCatalogInfraConnectorInBackstageK8S" and then call gitIntegrationService.createConnectorInBackstage() which will have internally two function calls -
1/ Secrets creation
2/ AppConfig stuff
___
*[`idp-service/src/main/resources/configs/integrations/bitbucket.yaml` line 0 at r2](https://reviewable.io/reviews/harness/harness-core/45471#-NRBr9heEwY8ru1I080b:-NRBr9heEwY8ru1I080c:b-udilp0) ([raw file](https://github.com/harness/harness-core/blob/23820ba6b52df6d8b574206d4085a1fb9e4abf2a/idp-service/src/main/resources/configs/integrations/bitbucket.yaml#L0)):*
Please add for bitbucket as well

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45471)* status: 21 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/45471#-NRBsykK2Ka9YchcFjI1:-NRBsykK2Ka9YchcFjI2:brz072k) ([raw file](https://github.com/harness/harness-core/blob/23820ba6b52df6d8b574206d4085a1fb9e4abf2a/idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java#L29)):*
> ```Java
> @Slf4j
> public class ConfigManagerUtils {
>   private static final String GITHUB_CONFIG_FILE = "configs/integrations/github.yaml";
> ```

If this is only in onboarding flow, then it is fine. If this is going to be extended for future use-cases where-in we store plugins config as yaml in the resources folder and read the file from classLoader, then we shouldn't invoke the classLoader and read the file each time. Instead it should be cached.

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45471)* status: 23 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/configmanager/ConfigType.java` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/45471#-NRBqeiAAcqNCqROuteN:-NRByVo-EYM0I0Dfr2_3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/23820ba6b52df6d8b574206d4085a1fb9e4abf2a/idp-service/src/main/java/io/harness/idp/configmanager/ConfigType.java#L15)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Just PLUGINS ?
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/beans/entity/AppConfigEntity.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/45471#-NRBqTPeAxSqhyW5eGJl:-NRByWd29GVbWCtW2Frn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/23820ba6b52df6d8b574206d4085a1fb9e4abf2a/idp-service/src/main/java/io/harness/idp/configmanager/beans/entity/AppConfigEntity.java#L47)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Compound index will be on account + config_id right ? If so, please change the index name and this commented line
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/mappers/AppConfigMapper.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/45471#-NRBqimY1VvIfQ0K6Qc8:-NRByXur8_VrlF01Oqrm:b-lwbssp) ([raw file](https://github.com/harness/harness-core/blob/23820ba6b52df6d8b574206d4085a1fb9e4abf2a/idp-service/src/main/java/io/harness/idp/configmanager/mappers/AppConfigMapper.java#L22)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Are we not setting the configType in from and to DTO methods ?
</blockquote></details>

no doing it on service layer in parametrised way because plugins config is set via API and integrations will be set from based on connectors in onboarding flow.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/45471#-NRBsykK2Ka9YchcFjI1:-NRBz4FTE34CF6G-m-PY:b-srb1xg) ([raw file](https://github.com/harness/harness-core/blob/23820ba6b52df6d8b574206d4085a1fb9e4abf2a/idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java#L29)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

If this is only in onboarding flow, then it is fine. If this is going to be extended for future use-cases where-in we store plugins config as yaml in the resources folder and read the file from classLoader, then we shouldn't invoke the classLoader and read the file each time. Instead it should be cached.
</blockquote></details>

This will be only in onboarding flow i think for now which will be one time process, it may get extended in update flow but there also it will be called less.Yes but will extend it if needed.
___
*[`idp-service/src/main/java/io/harness/idp/onboarding/services/impl/OnboardingServiceImpl.java` line 647 at r2](https://reviewable.io/reviews/harness/harness-core/45471#-NRBrKpp0hu6HyJ_cTL5:-NRCFiNvCjnUdHjuotcv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/23820ba6b52df6d8b574206d4085a1fb9e4abf2a/idp-service/src/main/java/io/harness/idp/onboarding/services/impl/OnboardingServiceImpl.java#L647)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

I suggest the following. Rename this function to "createCatalogInfraConnectorInBackstageK8S" and then call gitIntegrationService.createConnectorInBackstage() which will have internally two function calls -
1/ Secrets creation
2/ AppConfig stuff
</blockquote></details>

Done.
___
*[`idp-service/src/main/resources/configs/integrations/bitbucket.yaml` line  at r2](https://reviewable.io/reviews/harness/harness-core/45471#-NRBr9heEwY8ru1I080b:-NRCPW0v0wz-ykQOSSL3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/23820ba6b52df6d8b574206d4085a1fb9e4abf2a/idp-service/src/main/resources/configs/integrations/bitbucket.yaml#L)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Please add for bitbucket as well
</blockquote></details>

Done.

**Review by sathish-soundarapandian — APPROVED** [review]
> Reviewed 13 of 21 files at r1, 2 of 3 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45471)* status: 23 file(s) to review. 1 of 2 approvals obtained.

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 13 of 21 files at r1, 2 of 3 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45471)* status: 1 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/configmanager/ConfigType.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/45471#-NRCW_hI75m9Z5wTkIxd:-NRCW_hI75m9Z5wTkIxe:bq0czkz) ([raw file](https://github.com/harness/harness-core/blob/179905ec2a3d6a2c7230aa8a0b0ef9b2d8fad121/idp-service/src/main/java/io/harness/idp/configmanager/ConfigType.java#L15)):*
> ```Java
> @OwnedBy(HarnessTeam.IDP)
> public enum ConfigType {
>   PLUGINS,
> ```

nit: Should these be PLUGIN and INTEGRATION (singular)? As a record will represent 1 PLUGIN/INTEGRATION.



_Code quote:_
```Java
PLUGINS
```
___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java` line 127 at r3](https://reviewable.io/reviews/harness/harness-core/45471#-NRCgs0k0oL0k2Jlnt37:-NRCgs0k0oL0k2Jlnt38:bq8e426) ([raw file](https://github.com/harness/harness-core/blob/179905ec2a3d6a2c7230aa8a0b0ef9b2d8fad121/idp-service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java#L127)):*
> ```Java
>                                           .build();
>     try {
>       configManagerService.saveConfigUsingEntity(appConfigEntity);
> ```

Ideally service layer should accept dtos and deal with entities inside. Can we use the `saveConfigForAccount` method with dto?
___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/utils/GitIntegrationUtils.java` line 69 at r3](https://reviewable.io/reviews/harness/harness-core/45471#-NRCg-62708Urwy8qsJi:-NRCg-62708Urwy8qsJj:b-f5meu6) ([raw file](https://github.com/harness/harness-core/blob/179905ec2a3d6a2c7230aa8a0b0ef9b2d8fad121/idp-service/src/main/java/io/harness/idp/gitintegration/utils/GitIntegrationUtils.java#L69)):*
> ```Java
>     GithubConnectorDTO config = (GithubConnectorDTO) connectorInfoDTO.getConnectorConfig();
>     GithubApiAccessDTO apiAccess = config.getApiAccess();
>     if (apiAccess != null && apiAccess.getType().toString().equals(GitIntegrationConstants.GITHUB_APP_CONNECTOR_TYPE)) {
> ```

nit: we can return in one statement



_Code quote:_
```Java
if 
```

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45471)* status: 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java` line 127 at r3](https://reviewable.io/reviews/harness/harness-core/45471#-NRCgs0k0oL0k2Jlnt37:-NRCrZ4DCX01r324FZEy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/179905ec2a3d6a2c7230aa8a0b0ef9b2d8fad121/idp-service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java#L127)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Ideally service layer should accept dtos and deal with entities inside. Can we use the `saveConfigForAccount` method with dto?
</blockquote></details>

Done.

**Review by vikyathharekal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45471)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by sathish-soundarapandian — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45471)* status: :shipit: complete! ✓

**Pull request merged**
