### PR TITLE
[fix]: [PIE-4171]: Added Recaster Alias and Type Alias to required files

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes
Added Recaster Alias and Type Alias to required files

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34501)

### CODE REVIEW

**Comment by senjucanon2** [comment]
TI-bootstrap: trigger ti3

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34501)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`860-orchestration-steps/src/main/java/io/harness/steps/barriers/BarrierSpecParameters.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/34501#-N59RcZt4Xe7B61JNGz0:-N59RcZt4Xe7B61JNGz1:b-32hpj1) ([raw file](https://github.com/harness/harness-core/blob/624093097813a5098439f9f3bec0cb72ffb49585/860-orchestration-steps/src/main/java/io/harness/steps/barriers/BarrierSpecParameters.java#L24)):*
> ```Java
> @Builder
> @TypeAlias("barrierSpecParameters")
> @RecasterAlias("io.harness.steps.barriers.BarrierSpecParameters")
> ```

this class we should not change, as there already exists recaster alias for this



_Code quote:_
```Java
io.harness.steps.barriers.BarrierSpecParameters
```

**Comment by senjucanon2** [comment]
trigger ti2

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34501#-:-N59oF1_EKZROHMKPJB9:bnfp4nl)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34501)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`860-orchestration-steps/src/main/java/io/harness/steps/barriers/BarrierSpecParameters.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/34501#-N59RcZt4Xe7B61JNGz0:-N59rIxz1HH6RUdEaqMn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/624093097813a5098439f9f3bec0cb72ffb49585/860-orchestration-steps/src/main/java/io/harness/steps/barriers/BarrierSpecParameters.java#L24)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this class we should not change, as there already exists recaster alias for this
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34501)* status: :shipit: complete! ✓

**Pull request merged**
