### PR TITLE
fix: [CDS-81852]: Pipeline executions waiting for Jira approval are showing as running

### PR DESCRIPTION
**Pull request by ayushitiwari024**
## Describe your changes

**Issue:** Change in status update from `RUNNING` to `APPROVAL_WAITING` is taking longer than expected(i.e 1-2 minutes) as PlanNode and Graph is getting updated at the same time.

**Changes:** A call is done to update the status of the pipeline whenever there is a change in the status irrespective of the graph being updated.

**Testing:** Tested this case locally: https://harness.atlassian.net/browse/CDS-81852
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54341)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/OrchestrationLogPublisher.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/54341#-Nh58DlZAR1VHrfPOQpy:-Nh58DlZAR1VHrfPOQpz:b-5mi7c) ([raw file](https://github.com/harness/harness-core/blob/1240e73062ce5985d544b80ce25c586920e7d42a/pipeline-service/modules/orchestration/src/main/java/io/harness/event/OrchestrationLogPublisher.java#L53)):*
> ```Java
>   @Override
>   public void onPlanStatusUpdate(Ambiance ambiance) {
>     createAndHandleEventLog(ambiance.getPlanExecutionId(), AmbianceUtils.obtainCurrentRuntimeId(ambiance),
> ```

We can remove this function call as it is not required because we are doing the similar thing in new function

**Comment by ayushitiwari024** [comment]
trigger uts

**Review by ayushitiwari024 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54341)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/OrchestrationLogPublisher.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/54341#-Nh58DlZAR1VHrfPOQpy:-Nh5WOoh47dFcom7vB7H:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/1240e73062ce5985d544b80ce25c586920e7d42a/pipeline-service/modules/orchestration/src/main/java/io/harness/event/OrchestrationLogPublisher.java#L53)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We can remove this function call as it is not required because we are doing the similar thing in new function
</blockquote></details>

Done

**Comment by ayushitiwari024** [comment]
trigger messagecheck

**Comment by ayushitiwari024** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/OrchestrationLogPublisher.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/54341#-Nh58DlZAR1VHrfPOQpy:-Nh5gpubEsEyQsWEvA-7:bansuqs) ([raw file](https://github.com/harness/harness-core/blob/1240e73062ce5985d544b80ce25c586920e7d42a/pipeline-service/modules/orchestration/src/main/java/io/harness/event/OrchestrationLogPublisher.java#L53)):*
<details><summary><i>Previously, ayushitiwari024 wrote…</i></summary><blockquote>

Done
</blockquote></details>

Could you please add tests for the same?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54341)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54341)* status: 1 change requests. 1 of 2 approvals obtained.

**Comment by ayushitiwari024** [comment]
trigger ut7

**Comment by ayushitiwari024** [comment]
trigger ut7

**Review by ayushitiwari024 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54341)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/OrchestrationLogPublisher.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/54341#-Nh58DlZAR1VHrfPOQpy:-Nh6ZKdZ5rb9gfLXTnsT:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/1240e73062ce5985d544b80ce25c586920e7d42a/pipeline-service/modules/orchestration/src/main/java/io/harness/event/OrchestrationLogPublisher.java#L53)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Could you please add tests for the same?
</blockquote></details>

Done

**Review by sahilhindwani-harness — APPROVED** [review]

**Comment by ayushitiwari024** [comment]
trigger review

**Pull request merged**
