### PR TITLE
feat: [CDS-67967]: add retry execution info in planExecutionMetadata

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** Added retry execution info in planExecutionMetadata and in retry histories API response.

**Testing:** 
- RetryExecutionInfo null in the original execution
Screenshot 2023-05-04 at 2 42 19 PM

- RetryExecutionInfo correctly populated in case of retried execution.
Screenshot 2023-05-04 at 2 41 43 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47326)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/engine/executions/retry/RetryExecutionInfo.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/47326#-NU_wDYZBkQ69GM2IzRN:-NU_wDYZBkQ69GM2IzRO:bxzuxnv) ([raw file](https://github.com/harness/harness-core/blob/99cae1ee61c117d857a6568c759987c2e18743e4/pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/engine/executions/retry/RetryExecutionInfo.java#L22)):*
> ```Java
> public class RetryExecutionInfo {
>   List<String> retryStagesIdentifier;
>   List<String> identifierOfSkipStages;
> ```

just checking, looking at field 1, shouldn't the name of field 2 be "skipStagesIdentifiers" ?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 282 at r2](https://reviewable.io/reviews/harness/harness-core/47326#-NU_wVD6A8OT2xuyjmPC:-NU_wVD6A8OT2xuyjmPD:bqmkl4r) ([raw file](https://github.com/harness/harness-core/blob/99cae1ee61c117d857a6568c759987c2e18743e4/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L282)):*
> ```Java
>       planExecutionMetadataBuilder.expandedPipelineJson(expandedJson);
>       boolean isRetry = retryExecutionParameters.isRetry();
>       if (isRetry) {
> ```

it would be cleaner to use variable.isRetry() directly instead of putting it in a variable and then using it, given the fact that we aren't re-using it anywhere.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 283 at r2](https://reviewable.io/reviews/harness/harness-core/47326#-NU_wcUb4GvfpvCpQhOp:-NU_wcUb4GvfpvCpQhOq:b-fjlyss) ([raw file](https://github.com/harness/harness-core/blob/99cae1ee61c117d857a6568c759987c2e18743e4/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L283)):*
> ```Java
>       boolean isRetry = retryExecutionParameters.isRetry();
>       if (isRetry) {
>         planExecutionMetadataBuilder.retryExecutionInfo(buildRetryExecutionInfo(
> ```

I see the build method is just a builder itself. Any particular reason why we need to write a wrapper over builder itself?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 308 at r2](https://reviewable.io/reviews/harness/harness-core/47326#-NU_wlYa34xKZLma7Zab:-NU_wlYa34xKZLma7Zac:bhu1ifd) ([raw file](https://github.com/harness/harness-core/blob/99cae1ee61c117d857a6568c759987c2e18743e4/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L308)):*
> ```Java
>   }
> 
>   public io.harness.engine.executions.retry.RetryExecutionInfo buildRetryExecutionInfo(
> ```

this should be private?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47326)* status: 15 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 282 at r2](https://reviewable.io/reviews/harness/harness-core/47326#-NU_wVD6A8OT2xuyjmPC:-NU_yrpr1EhjW5lZomUm:b-i70h17) ([raw file](https://github.com/harness/harness-core/blob/99cae1ee61c117d857a6568c759987c2e18743e4/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L282)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

it would be cleaner to use variable.isRetry() directly instead of putting it in a variable and then using it, given the fact that we aren't re-using it anywhere.
</blockquote></details>

it's actually being used twice here.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 283 at r2](https://reviewable.io/reviews/harness/harness-core/47326#-NU_wcUb4GvfpvCpQhOp:-NU_yj7-BowNEQQhEoCZ:b-aoh8yh) ([raw file](https://github.com/harness/harness-core/blob/99cae1ee61c117d857a6568c759987c2e18743e4/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L283)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I see the build method is just a builder itself. Any particular reason why we need to write a wrapper over builder itself?
</blockquote></details>

we can remove this method and directly use builder where needed, done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 308 at r2](https://reviewable.io/reviews/harness/harness-core/47326#-NU_wlYa34xKZLma7Zab:-NU_z7bL2ByO6xcrI2gh:bwg588l) ([raw file](https://github.com/harness/harness-core/blob/99cae1ee61c117d857a6568c759987c2e18743e4/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L308)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this should be private?
</blockquote></details>

removed the method
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 454 at r2](https://reviewable.io/reviews/harness/harness-core/47326#-NU_x6pN9tg6wA74p4cc:-NU_zC3x9dp9ZVvwMftG:btlb34i) ([raw file](https://github.com/harness/harness-core/blob/99cae1ee61c117d857a6568c759987c2e18743e4/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L454)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we are directly reading from optional object without any check. Are we 101% sure that object will be sent in the response and it will never be empty? 
We can fetch it before using it and put appropriate check instead of directly using it.
</blockquote></details>

In this case, we are sure, because there always exists a planExecutionMetadata for a planExecutionId. 
But yes, in a very rare case of data being deleted from DB for whatever reason, we could get an NPE though the chances of getting into this situation are very rare, still I've added the NPE check here to be safe.
___
*[`pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/engine/executions/retry/RetryExecutionInfo.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/47326#-NU_wDYZBkQ69GM2IzRN:-NU_zl3b9YidNz1W0nKi:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/99cae1ee61c117d857a6568c759987c2e18743e4/pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/engine/executions/retry/RetryExecutionInfo.java#L22)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

just checking, looking at field 1, shouldn't the name of field 2 be "skipStagesIdentifiers" ?
</blockquote></details>

done

**Comment by shalini-agr** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 282 at r2](https://reviewable.io/reviews/harness/harness-core/47326#-NU_wVD6A8OT2xuyjmPC:-NUa3AAS7sUejWcbXIGq:b-sgq1es) ([raw file](https://github.com/harness/harness-core/blob/99cae1ee61c117d857a6568c759987c2e18743e4/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L282)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

it's actually being used twice here.
</blockquote></details>

This is a non-blocking comment thread, so no action is required. I would recommend using direct references instead of putting them in variables if there's no explicit need of it. 
Think about it that using argument.isRetry() even 4 times won't have any bad effect as its pretty convenient to read and use. Even the variable name is "isRetry", so its not even like we wanted to represent some logical meaning which wasn't explicit enough earlier. Putting in variable would make more sense when either using direct reference is complicated or verbose or we want to add some logical meaning to our code to improve better readability and understanding.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 468 at r3](https://reviewable.io/reviews/harness/harness-core/47326#-NUa3sRC-69HN1sv3pbr:-NUa3sRC-69HN1sv3pbs:b-2eg93) ([raw file](https://github.com/harness/harness-core/blob/21920d90d486965d3b415f34b2f7aa7227c2bbb3/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L468)):*
> ```Java
>           return RetryHistoryResponseDto.builder()
>               .executionInfos(executionInfos)
>               .latestExecutionId(latestRetryExecutionId)
> ```

is it fine to return response without executionInfoDTO? I think its a violation of contract. May be its better to throw an error in case executionInfoDTO isn't found.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47326)* status: 15 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 468 at r3](https://reviewable.io/reviews/harness/harness-core/47326#-NUa3sRC-69HN1sv3pbr:-NUa4CrP93h10n3RVUpt:b-8zwowj) ([raw file](https://github.com/harness/harness-core/blob/21920d90d486965d3b415f34b2f7aa7227c2bbb3/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L468)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

is it fine to return response without executionInfoDTO? I think its a violation of contract. May be its better to throw an error in case executionInfoDTO isn't found.
</blockquote></details>

yes, it is fine here, because in the case of original execution, it is expected to be null, if we don't set anything here, it gets set as null only.

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 5 of 8 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47326)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger commonchecks

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger messagecheck

**Comment by shalini-agr** [comment]
trigger checkstylecodeformat, pmd, codebasehash

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r2, 9 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47326)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 284 at r4](https://reviewable.io/reviews/harness/harness-core/47326#-NUaHbrF4IT1G0Q0tys6:-NUaHbrF4IT1G0Q0tys7:blqkoqg) ([raw file](https://github.com/harness/harness-core/blob/fff880919fbc0c020dfe7332f7a3921c3a0a61d6/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L284)):*
> ```Java
>       if (isRetry) {
>         planExecutionMetadataBuilder.retryExecutionInfo(
>             io.harness.execution.RetryExecutionInfo.builder()
> ```

do we need this fqn here?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 456 at r4](https://reviewable.io/reviews/harness/harness-core/47326#-NUaHgMxCrlDP-RZUNNn:-NUaHgMxCrlDP-RZUNNo:b-i2huwq) ([raw file](https://github.com/harness/harness-core/blob/fff880919fbc0c020dfe7332f7a3921c3a0a61d6/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L456)):*
> ```Java
>       String latestRetryExecutionId = executionInfos.get(0).getUuid();
>       Optional<PlanExecutionMetadata> planExecutionMetadataOptional =
>           planExecutionMetadataService.findByPlanExecutionId(currentPlanExecutionId);
> ```

use projections
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 473 at r4](https://reviewable.io/reviews/harness/harness-core/47326#-NUaHq3P0TjLBpI2E3g2:-NUaHq3P0TjLBpI2E3g3:b-1a13py) ([raw file](https://github.com/harness/harness-core/blob/fff880919fbc0c020dfe7332f7a3921c3a0a61d6/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L473)):*
> ```Java
>       } else {
>         throw new InvalidRequestException(
>             format("Execution with id [%s] is not present or deleted", currentPlanExecutionId));
> ```

PlanExecution
___
*[`pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/engine/executions/retry/RetryExecutionInfoDTO.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/47326#-NUaHPCqDWbdq44Cgtc_:-NUaHPCqDWbdq44Cgtca:b9wvia0) ([raw file](https://github.com/harness/harness-core/blob/fff880919fbc0c020dfe7332f7a3921c3a0a61d6/pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/engine/executions/retry/RetryExecutionInfoDTO.java#L19)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> @Value
> @Builder
> ```

add apiModelProperty

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47326)* status: 7 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 284 at r4](https://reviewable.io/reviews/harness/harness-core/47326#-NUaHbrF4IT1G0Q0tys6:-NUaJ8NTDSI5RTmawZ2D:bg7y40z) ([raw file](https://github.com/harness/harness-core/blob/fff880919fbc0c020dfe7332f7a3921c3a0a61d6/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L284)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

do we need this fqn here?
</blockquote></details>

yes, because we already have one more class with the same name in our project
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 456 at r4](https://reviewable.io/reviews/harness/harness-core/47326#-NUaHgMxCrlDP-RZUNNn:-NUaPEvR6cXyJuSHzUI3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fff880919fbc0c020dfe7332f7a3921c3a0a61d6/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L456)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use projections
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 473 at r4](https://reviewable.io/reviews/harness/harness-core/47326#-NUaHq3P0TjLBpI2E3g2:-NUaJy9O9rnkrJyifAYu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fff880919fbc0c020dfe7332f7a3921c3a0a61d6/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L473)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

PlanExecution
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/engine/executions/retry/RetryExecutionInfoDTO.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/47326#-NUaHPCqDWbdq44Cgtc_:-NUaJzgM35_gl27GI_cQ:b-tpm14d) ([raw file](https://github.com/harness/harness-core/blob/fff880919fbc0c020dfe7332f7a3921c3a0a61d6/pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/engine/executions/retry/RetryExecutionInfoDTO.java#L19)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add apiModelProperty
</blockquote></details>

added @Schema annotation

**Comment by shalini-agr** [comment]
trigger commonchecks

**Comment by shalini-agr** [comment]
trigger pmd, codebasehash, uts

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47326)* status: 7 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionMetadataRepositoryCustomImpl.java` line 42 at r5](https://reviewable.io/reviews/harness/harness-core/47326#-NUbyGsx36IBJRGg-r-W:-NUe7WcDBM1jeAcIxIql:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/994dad5af3a806eaf41dbf1c54da7c33fc29af27/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionMetadataRepositoryCustomImpl.java#L42)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Can we take the list of fields as parameter? And name the method something like getPlanExecutionMetadataWithFieldsIncluding? So that the same method can be used when we need  to project some other set of fields as well.
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 8 files at r2, 3 of 10 files at r3, 1 of 1 files at r4, 1 of 6 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47326)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47326)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/engine/executions/retry/RetryExecutionInfoDTO.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/47326#-NUaHPCqDWbdq44Cgtc_:-NUeFIyf83o7cXqYQ-As:b-fvvm9j) ([raw file](https://github.com/harness/harness-core/blob/fff880919fbc0c020dfe7332f7a3921c3a0a61d6/pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/engine/executions/retry/RetryExecutionInfoDTO.java#L19)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

added @Schema annotation
</blockquote></details>

we should not have DTO keyword for customer response

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47326)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/engine/executions/retry/RetryExecutionInfoDTO.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/47326#-NUaHPCqDWbdq44Cgtc_:-NUeIGlX8_-4ZqjNwYfX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fff880919fbc0c020dfe7332f7a3921c3a0a61d6/pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/engine/executions/retry/RetryExecutionInfoDTO.java#L19)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should not have DTO keyword for customer response
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47326)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47326)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
