### PR TITLE
fix: [DEL-5046]: Skip Delegate logging, when it is not acquiring tasks

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38745)

### CODE REVIEW

**Review by arpit3107 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38745)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1658 at r1](https://reviewable.io/reviews/harness/harness-core/38745#-NEo7vsuA4lG0CoRqmnZ:-NEo7vsuA4lG0CoRqmn_:b-8s59c4) ([raw file](https://github.com/harness/harness-core/blob/0f19d3026599fc3a3b54ee7c5edeaad37db5339a/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1658)):*
> ```Java
>       // Skip checking other cases if Delegate isn't acquiring tasks.
>       return true;
>     }
> ```

Why are you restarting delegate incase it is not acquiring tasks. 
Suppose delegate is freezed because of expired token then it will restart too frequently. 



_Code quote:_
```Java
    if (!acquireTasks.get()) {
      // Skip checking other cases if Delegate isn't acquiring tasks.
      return true;
    }
```

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38745)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1658 at r1](https://reviewable.io/reviews/harness/harness-core/38745#-NEo7vsuA4lG0CoRqmnZ:-NEo8rrP8sOqrXce6KGF:b-cce2sj) ([raw file](https://github.com/harness/harness-core/blob/0f19d3026599fc3a3b54ee7c5edeaad37db5339a/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1658)):*
> delegate is fr
acquireTasks will set to false only when watcher sends this signal during draining. Which means watcher will start new delegate process sometime soon, so there is no point evaluating below code.
In your case, when delegate is frozen we don't set acquire task to false. so we fallback below

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1658 at r1](https://reviewable.io/reviews/harness/harness-core/38745#-NEo7vsuA4lG0CoRqmnZ:-NEqNhYtAuZNw_ZAIgGU:bwdlasi) ([raw file](https://github.com/harness/harness-core/blob/0f19d3026599fc3a3b54ee7c5edeaad37db5339a/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1658)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

> delegate is fr
acquireTasks will set to false only when watcher sends this signal during draining. Which means watcher will start new delegate process sometime soon, so there is no point evaluating below code.
In your case, when delegate is frozen we don't set acquire task to false. so we fallback below
</blockquote></details>

we should add a log line in the if block

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38745)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1658 at r1](https://reviewable.io/reviews/harness/harness-core/38745#-NEo7vsuA4lG0CoRqmnZ:-NFMwbpT03PJMT0jJ11L:bfxoixe) ([raw file](https://github.com/harness/harness-core/blob/0f19d3026599fc3a3b54ee7c5edeaad37db5339a/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1658)):*
>  log line in th
That was the actual concern from customer. If we know that we are going to restart delegate process, then we shouldn't print logging like `Restarting delegate` every 10sec. 
We do print log on watcher side too, so probably we skipping logging here.

**Comment by gaurav-jain1** [comment]
trigger messagecheck

**Review by Vbhatia20 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38745)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions.

**Pull request merged**
