### PR TITLE
feat: [PL-29512]: Added Connector Audit for Force Delete

### PR DESCRIPTION
**Pull request by meenakshi-harness**
## Describe your changes
1. Integrated FORCE_DELETE audit action in Connector.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39940)

### CODE REVIEW

**Review by tiwaritejas — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39940)* status: Some of the checks are too old. 5 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39940)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39940)* status: :shipit: complete! ✓

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/events/ConnectorEventHandler.java` line 68 at r3](https://reviewable.io/reviews/harness/harness-core/39940#-NHX3biM2Ltq8bWVdB4-:-NHX3biODFqTaxEw1TSA:b-nwf23a) ([raw file](https://github.com/harness/harness-core/blob/d2bb6311639c35ccdcb4715e5d148131579c9034/440-connector-nextgen/src/main/java/io/harness/connector/events/ConnectorEventHandler.java#L68)):*
> ```Java
>   }
> 
>   private boolean handleConnectorForceDeleteEvent(OutboxEvent outboxEvent) throws IOException {
> ```

UT missing
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java` line 756 at r3](https://reviewable.io/reviews/harness/harness-core/39940#-NHX3ri_BIKEUtFbUhVA:-NHX3ri_BIKEUtFbUhVB:boj75qx) ([raw file](https://github.com/harness/harness-core/blob/d2bb6311639c35ccdcb4715e5d148131579c9034/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L756)):*
> ```Java
>     Supplier<OutboxEvent> supplier = null;
>     if (!gitSyncSdkService.isGitSyncEnabled(accountIdentifier, orgIdentifier, projectIdentifier)) {
>       if (forceDelete) {
> ```

UT covering this change

**Review by nishantsaini20 — APPROVED** [review]
Approving considering missing UTs will be added in another PR

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39940#-:-NHX4-lyAFB7n4Fqe2ay:bq3rrmb)* status: :shipit: complete! ✓

**Pull request merged**
