### PR TITLE
fix: [DEL-2223]: update delegate tags

### PR DESCRIPTION
**Pull request by arpit3107**
## Describe your changes
1. We should update delegate tags when delegate tries to Re-Register.
2. This should be true for both ecs and non-ecs delegates.
3. Also we should not save tags in delegateGroup for cg grouped delegates (ecs/immutable)

private void updateDelegateTagsAfterReRegistering(Delegate registeredDelegate, List<String> delegateTags) {
    Query<Delegate> delegateQuery = persistence.createQuery(Delegate.class)
                                        .filter(DelegateKeys.accountId, registeredDelegate.getAccountId())
                                        .filter(DelegateKeys.uuid, registeredDelegate.getUuid());
    persistence.update(
        delegateQuery, persistence.createUpdateOperations(Delegate.class).set(DelegateKeys.tags, delegateTags));
    registeredDelegate.setTags(delegateTags);
  }

This will be true for only while re-registering.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35465)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 987 at r1](https://reviewable.io/reviews/harness/harness-core/35465#-N7R9fFU21_qniEy0tqZ:-N7R9fFU21_qniEy0tq_:b-rxji3a) ([raw file](https://github.com/harness/harness-core/blob/55476e457854cf92e6031c28b5973871280eff65/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L987)):*
> ```Java
>     }
>     setUnset(updateOperations, DelegateKeys.heartbeatAsObject, delegate.isHeartbeatAsObject());
>     setUnset(updateOperations, DelegateKeys.tags, delegate.getTags());
> ```

can you explain how is this fixing the issue? also please add unit tests to make sure its not broken in future

**Review by raghuAtWings — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35465)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 987 at r1](https://reviewable.io/reviews/harness/harness-core/35465#-N7R9fFU21_qniEy0tqZ:-N7R9rN-7WAkbii6oUln:bn5eobm) ([raw file](https://github.com/harness/harness-core/blob/55476e457854cf92e6031c28b5973871280eff65/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L987)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

can you explain how is this fixing the issue? also please add unit tests to make sure its not broken in future
</blockquote></details>

also i don't see details on pr description and checklist, please add those

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35465)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 987 at r1](https://reviewable.io/reviews/harness/harness-core/35465#-N7R9fFU21_qniEy0tqZ:-N7z4e4_4P-SZRO23ZB6:b-upi6bt) ([raw file](https://github.com/harness/harness-core/blob/55476e457854cf92e6031c28b5973871280eff65/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L987)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

also i don't see details on pr description and checklist, please add those
</blockquote></details>

Arpit, you can describe in summary of your PR, and what change will happen as part of this.



_Code quote:_
```Java
tions(final Delegate delegate) {
```

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35465)

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35465)* status: 1 change requests. 1. unresolved discussions.

**Review by gaurav-jain1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35465)* status: 1 change requests. 1. unresolved discussions.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35465)* status: :shipit: complete! ✓

**Pull request merged**
