### PR TITLE
fix: [CDS-38467]: Ignoring the log-service errors for connection/save/close streams

### PR DESCRIPTION
**Pull request by archit-harness**
## Describe your changes
Ignoring the log-service errors for connection/save/close streams

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33962)

### CODE REVIEW

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33962)* status: :shipit: complete! ✓

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33962)* status: :shipit: complete! ✓

___
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientImpl.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/33962#-N3rja360qU3A_YJRMgr:-N3rja360qU3A_YJRMgs:bwva32w) ([raw file](https://github.com/harness/harness-core/blob/4f21f0a6d74e2aeed4b1d2b5e9da35d218493596/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientImpl.java#L64)):*
> ```Java
>           logStreamingClient.pushMessage(token, accountId, logKey, Collections.singletonList(logLine)));
>     } catch (Exception ex) {
>       log.error("Unable to push message to log stream for account {} and logKeySuffix {}", accountId, logKeySuffix, ex);
> ```

We should log the log line also I think so we don't lose on it

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33962)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientImpl.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/33962#-N3rja360qU3A_YJRMgr:-N3rlhLe93yuRMzl5o_h:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4f21f0a6d74e2aeed4b1d2b5e9da35d218493596/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientImpl.java#L64)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

We should log the log line also I think so we don't lose on it
</blockquote></details>

Done.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33962)* status: :shipit: complete! ✓

**Pull request merged**
