### PR TITLE
[fix]: [PL-24523]: ldap setting check

### PR DESCRIPTION
**Pull request by pbarapatre10**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32972)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Review by piyush-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32972)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by ujjawal-harness — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32972#-:-N1hPwHB4h77UgblfyU8:bnfp4nl)* status: 1 file(s) to review.

**Review by ujjawal-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32972#-:-N1hTd5R1Uf5oONX-KDI:bnfp4nl)* status: 2 file(s) to review.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32972)* status: :shipit: complete! ✓

**Review by shashank-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32972)* status: :shipit: complete! ✓

**Review by shashank-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32972)* status: 3 file(s) to review.

**Comment by pbarapatre10** [comment]
trigger ft2

**Review by shashank-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32972)* status: 4 file(s) to review.

**Comment by shashank-harness** [comment]
:lgtm:

**Review by shashank-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32972)* status: 4 file(s) to review.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32972)* status: 4 file(s) to review.

**Comment by shashank-harness** [comment]
:lgtm:

**Comment by shashank-harness** [comment]
:lgtm:

**Pull request merged**
