### PR TITLE
fix: [PL-22028]: fix ng clientSecret case

### PR DESCRIPTION
**Pull request by pbarapatre10**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30047)

### CODE REVIEW

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30047)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30047)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/SSOServiceImpl.java, line 523 at r3](https://reviewable.io/reviews/harness/harness-core/30047#-MtwgSpUDJ4I3Pj5xFOd:-MtwgSpUDJ4I3Pj5xFOe:bg1yr6j) ([raw file](https://github.com/harness/harness-core/blob/0383cdd95adab6e434e1df3520740b6110796e6f/400-rest/src/main/java/software/wings/service/impl/SSOServiceImpl.java#L523)):*
> ```Java
>   }
> 
>   private boolean deleteLdapSettings(String accountId, String targetAccountType) {
> ```

Why this was removed?

**Comment by piyush-harness** [comment]
___
*[400-rest/src/main/java/software/wings/resources/SSOResourceNG.java, line 172 at r3](https://reviewable.io/reviews/harness/harness-core/30047#-MtwgWiK3GV3V4UWlEed:-MtwgWiK3GV3V4UWlEee:bx1cwpj) ([raw file](https://github.com/harness/harness-core/blob/5467b2c276dd54caac03c464e423dee1cf2d0b6b/400-rest/src/main/java/software/wings/resources/SSOResourceNG.java#L172)):*
> ```Java
>   }
> 
>   private String getCGSecretManagerRefForClientSecret(
> ```

THis piece of code is not understandable , can we make this a bit more clear, Also can we have unit test cases around it?

**Comment by pbarapatre10** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/SSOServiceImpl.java, line 523 at r3](https://reviewable.io/reviews/harness/harness-core/30047#-MtwgSpUDJ4I3Pj5xFOd:-Mtwgy0r0N9WSm0k0_ng:b7wfct7) ([raw file](https://github.com/harness/harness-core/blob/0383cdd95adab6e434e1df3520740b6110796e6f/400-rest/src/main/java/software/wings/service/impl/SSOServiceImpl.java#L523)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why this was removed?
</blockquote></details>

This is dead code, so removed. Thanks

**Comment by piyush-harness** [comment]
___
*[400-rest/src/main/java/software/wings/resources/SSOResourceNG.java, line 172 at r3](https://reviewable.io/reviews/harness/harness-core/30047#-MtwgWiK3GV3V4UWlEed:-Mtwhr9T4TZkqXXl-4py:b1g3jc8) ([raw file](https://github.com/harness/harness-core/blob/5467b2c276dd54caac03c464e423dee1cf2d0b6b/400-rest/src/main/java/software/wings/resources/SSOResourceNG.java#L172)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

THis piece of code is not understandable , can we make this a bit more clear, Also can we have unit test cases around it?
</blockquote></details>

I meant break this down in multiple smaller methods for reusing checks and keep this method small , Reduce the Cognitive complexity so code is readable

**Comment by pbarapatre10** [comment]
___
*[400-rest/src/main/java/software/wings/resources/SSOResourceNG.java, line 172 at r3](https://reviewable.io/reviews/harness/harness-core/30047#-MtwgWiK3GV3V4UWlEed:-MtxVLnm2vGOAFgjyHRc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5467b2c276dd54caac03c464e423dee1cf2d0b6b/400-rest/src/main/java/software/wings/resources/SSOResourceNG.java#L172)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

I meant break this down in multiple smaller methods for reusing checks and keep this method small , Reduce the Cognitive complexity so code is readable 
</blockquote></details>

Done.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30047)* status: 6 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30047)* status: 6 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30047)* status: :shipit: complete! ✓

**Pull request merged**
