### PR TITLE
feat: [SRM-10615]: Slo service create update and delete audit events

### PR DESCRIPTION
**Pull request by naveen-harness**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34134)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 57 files at r1, 31 of 54 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34134)* status: 23 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImplTest.java` line 1139 at r2](https://reviewable.io/reviews/harness/harness-core/34134#-N4AeLue3MWrSYUrEHpG:-N4AeLuf6TyxmcN4TTFQ:b3dseum) ([raw file](https://github.com/harness/harness-core/blob/aba37112c1de4e3a86aef40061f841f4bb5f9fb9/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImplTest.java#L1139)):*
> ```Java
>   @Owner(developers = NAVEEN)
>   @Category(UnitTests.class)
>   public void testServiceLevelObjectiveCreateEvent() {
> ```

the test naming convention is testMethodName_desc, please rename all the test based on this convention. Please check monitoredService tests also.
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImplTest.java` line 1212 at r2](https://reviewable.io/reviews/harness/harness-core/34134#-N4AeoILAFs29Q8sAx99:-N4AeoILAFs29Q8sAx9A:b-ht30nu) ([raw file](https://github.com/harness/harness-core/blob/aba37112c1de4e3a86aef40061f841f4bb5f9fb9/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImplTest.java#L1212)):*
> ```Java
>   @Owner(developers = NAVEEN)
>   @Category(UnitTests.class)
>   public void testOutboxUpdateEventHandler() throws JsonProcessingException {
> ```

I think this test needs to be in ServiceLevelObjectiveUpdateEventTest file. Please check other tests also. 
The convention is that if you are testing method of some class it should have a separate file.

**Review by kjoshi12345 — DISMISSED** [review]
:lgtm:

> Reviewed 23 of 54 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34134#-:-N4CGoJR8qpVTFjixZYT:bnfp4nl)* status: :shipit: complete! ✓

**Comment by naveen-harness** [comment]
trigger ti0

**Comment by naveen-harness** [comment]
trigger ti1

**Comment by naveen-harness** [comment]
trigger ti3

**Comment by naveen-harness** [comment]
trigger ti4

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 4 of 5 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34134)* status: :shipit: complete! ✓

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34134#-:-N4QEzvh5fAZu23QhieX:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
