### PR TITLE
feat: [PL-38981]: changes to support migrating users from CG to NG multiple times

### PR DESCRIPTION
**Pull request by sahibaCCM**
## Describe your changes
Changes include adding a new API to sync the Users
-> Allow moving CG admin users to NG as admins
-> Allow moving all CG users to NG (logic remains same as how we migrate when we enable NG for an account.)

Tested for:
-> migrate CG to NG post deleting a few users
->  migrate CG to NG post adding user to CG only
-> using cleanup API and get all non admin users in  NG

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers

https://github.com/harness/harness-core/assets/112424209/b0a6f7b4-a094-4334-848c-4c55e902140c

<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48687)

### CODE REVIEW

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger messagecheck

**Comment by sahibaCCM** [comment]
trigger ut0

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger codeformat

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger uts

**Review by tiwaritejas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48687)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java` line 101 at r4](https://reviewable.io/reviews/harness/harness-core/48687#-NY-GhNgBMtqvFCOXz8l:-NY-GhNgBMtqvFCOXz8m:b-y3gqn6) ([raw file](https://github.com/harness/harness-core/blob/728fb4e551a6940cb71c56da7f0ebb387fc5c45b/120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java#L101)):*
> ```Java
>   }
>   private boolean processSyncNGWithCG(AccountEntityChangeDTO accountEntityChangeDTO) {
>     ngAccountSetupService.setupAccountForNG(accountEntityChangeDTO.getAccountId());
> ```

Looks like this use case can be achieved by re-running the "/nextgen-enabled" API again for the given account. 

Although, from the corresponding JIRA, I do see one catch in creating a new API- Cleanup of existing NG user data. The expected new API has to be used when a customer has messed up something in the CG->NG migration or the NG users data has become inconsistent for some reason.
So, we might need to handle the cleanup of the existing NG users first in the sync API before running the account setup service.
Example use case where data cleanup might be required-
A customer ran the cg->ng migration in the past and migrated unwanted and stale users as well. Now, they want to do a fresh NG setup with only the admin users this time. In the current implementation, I don't think this can be achieved as we are not handling any sort of cleanup of the already migrated users in the first migration. 
cc: @shashank-harness 
___
*[`400-rest/src/main/java/software/wings/resources/AdminAccountResource.java` line 137 at r4](https://reviewable.io/reviews/harness/harness-core/48687#-NY-FPB1DOd9fMm9AHl_:-NY-FPB1DOd9fMm9AHla:bif0qmg) ([raw file](https://github.com/harness/harness-core/blob/728fb4e551a6940cb71c56da7f0ebb387fc5c45b/400-rest/src/main/java/software/wings/resources/AdminAccountResource.java#L137)):*
> ```Java
>   public RestResponse<Boolean> syncNextgen(
>       @PathParam("accountId") String accountId, @QueryParam("adminOnly") @DefaultValue("false") boolean adminOnly) {
>     return new RestResponse<>(adminAccountService.syncNextgen(accountId, adminOnly));
> ```

I don't see "adminOnly" flag getting used further in the flow. 
Looks like the behaviour of only migratin the CG admins is being taken care by the FF- "PL_DO_NOT_MIGRATE_NON_ADMIN_CG_USERS_TO_NG" in the account setup service. So, in case we intend to keep using that flag, I don't see a use case of this query param here.

**Comment by sahibaCCM** [comment]
> > Reviewed 5 of 9 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/48687)_ status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java` line 101 at r4](https://reviewable.io/reviews/harness/harness-core/48687#-NY-GhNgBMtqvFCOXz8l:-NY-GhNgBMtqvFCOXz8m:b-y3gqn6) ([raw file](https://github.com/harness/harness-core/blob/728fb4e551a6940cb71c56da7f0ebb387fc5c45b/120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java#L101)):_
> 
> > ```java
> >   }
> >   private boolean processSyncNGWithCG(AccountEntityChangeDTO accountEntityChangeDTO) {
> >     ngAccountSetupService.setupAccountForNG(accountEntityChangeDTO.getAccountId());
> > ```
> 
> Looks like this use case can be achieved by re-running the "/nextgen-enabled" API again for the given account.
> 
> Although, from the corresponding JIRA, I do see one catch in creating a new API- Cleanup of existing NG user data. The expected new API has to be used when a customer has messed up something in the CG->NG migration or the NG users data has become inconsistent for some reason. So, we might need to handle the cleanup of the existing NG users first in the sync API before running the account setup service. Example use case where data cleanup might be required- A customer ran the cg->ng migration in the past and migrated unwanted and stale users as well. Now, they want to do a fresh NG setup with only the admin users this time. In the current implementation, I don't think this can be achieved as we are not handling any sort of cleanup of the already migrated users in the first migration. cc: @shashank-harness
> 
> _[`400-rest/src/main/java/software/wings/resources/AdminAccountResource.java` line 137 at r4](https://reviewable.io/reviews/harness/harness-core/48687#-NY-FPB1DOd9fMm9AHl_:-NY-FPB1DOd9fMm9AHla:bif0qmg) ([raw file](https://github.com/harness/harness-core/blob/728fb4e551a6940cb71c56da7f0ebb387fc5c45b/400-rest/src/main/java/software/wings/resources/AdminAccountResource.java#L137)):_
> 
> > ```java
> >   public RestResponse<Boolean> syncNextgen(
> >       @PathParam("accountId") String accountId, @QueryParam("adminOnly") @DefaultValue("false") boolean adminOnly) {
> >     return new RestResponse<>(adminAccountService.syncNextgen(accountId, adminOnly));
> > ```
> 
> I don't see "adminOnly" flag getting used further in the flow. Looks like the behaviour of only migratin the CG admins is being taken care by the FF- "PL_DO_NOT_MIGRATE_NON_ADMIN_CG_USERS_TO_NG" in the account setup service. So, in case we intend to keep using that flag, I don't see a use case of this query param here.

-> We had a discussion around achieving the behaviour using existing API but upon discussion we arrived on having a separate end point. And for cleanup we already are working on another API.
https://harness.slack.com/archives/C05C1UD2RHU/p1686650491718969

-> adminOnly bit I'll remove as we dont have to handle explicitly. Thanks

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger uts

**Review by shashank-harness — DISMISSED** [review]
Lgtm

**Comment by shashank-harness** [comment]
@sahibaCCM Please update testing done in PR description before merging.

**Comment by sahibaCCM** [comment]
trigger uts

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48687)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger uts

**Review by shashank-harness — APPROVED** [review]
lgtm

**Review by meenakshi-harness — APPROVED** [review]
Approving as this got 2 approvals already

**Pull request merged**
