### PR TITLE
fix: [DEL-4494]: use UserPrincipal instead of principal

### PR DESCRIPTION
**Pull request by arpit3107**
## Describe your changes

Principal is an abstract class and there is no field named userName in principal class object, hence UI is not sync with backend swagger.json. 
So, we should use UserPrincipal instead of principal.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35478)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/35478#-N7LTn7a2d5pvl9L9njo:-N7LhH5yAmXflpQj7sb2:b2bebum) ([raw file](https://github.com/harness/harness-core/blob/b50e0c0e7a5cb3602a3143e8349d266e376e3a4e/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L75)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

I guess no, Since Principal is an abstract class and UserPrincipal is extending it. We have unit tests that will catch any breaking change in future.
</blockquote></details>

If its servicePrincipal, then we won't be able to typeCast it right?

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35478)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/35478#-N7LTn7a2d5pvl9L9njo:-N7LvahH6Mj5RLcABbk_:br8ywqd) ([raw file](https://github.com/harness/harness-core/blob/b50e0c0e7a5cb3602a3143e8349d266e376e3a4e/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L75)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

If its servicePrincipal, then we won't be able to typeCast it right?
</blockquote></details>

I tested with ApiKeyPrincipal. This is able to cast it to UserPrincipal. Can we test out with servicePrincipal?
___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java` line 82 at r1](https://reviewable.io/reviews/harness/harness-core/35478#-N7LhQ495cpYhG0bBt22:-N7LvpgXEiKR7QowIQKP:boz5c96) ([raw file](https://github.com/harness/harness-core/blob/b50e0c0e7a5cb3602a3143e8349d266e376e3a4e/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java#L82)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Wouldn't it impact a lot of stuff? Directly changing type of field in an entity. It could also cause backward compatibility issues right?
</blockquote></details>

I dont think changing type will create issues, variables name and type in Principal and UserPrincipal are same. And the response is a JSON.

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/35478#-N7LTn7a2d5pvl9L9njo:-N7MCtU2DHUac291FKCz:b-h49tvg) ([raw file](https://github.com/harness/harness-core/blob/b50e0c0e7a5cb3602a3143e8349d266e376e3a4e/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L75)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

I tested with ApiKeyPrincipal. This is able to cast it to UserPrincipal. Can we test out with servicePrincipal?
</blockquote></details>

Yes, we can't trust it like this. If you know that it has to be "userPrincipal" only, then put a check and throw error in all other cases.

**Comment by mohitg0795** [comment]
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java` line 82 at r1](https://reviewable.io/reviews/harness/harness-core/35478#-N7LhQ495cpYhG0bBt22:-N7MD4Kl7gL0fER46x0I:b-vemoda) ([raw file](https://github.com/harness/harness-core/blob/b50e0c0e7a5cb3602a3143e8349d266e376e3a4e/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java#L82)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

I dont think changing type will create issues, variables name and type in Principal and UserPrincipal are same. And the response is a JSON.
</blockquote></details>

Principal is just an abstract class. If all createdByNgUser fields until now have been UserPrincipal, only then it will work. Otherwise, this is not a backward compatible change. You've basically converted an abstract class object into a definite implementation, getting my point?

**Comment by arpit3107** [comment]
Closing this pr and raised https://github.com/harness/harness-core/pull/35497 as suggested

**Pull request closed without merging**
