### PR TITLE
feat: [CDS-40862]: create pr script

### PR DESCRIPTION
**Pull request by GabeAboy**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37547)

### CODE REVIEW

**Comment by GabeAboy** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ShellScriptTaskNG.java` line 86 at r1](https://reviewable.io/reviews/harness/harness-core/37547#-NBxCE4oD_5WoDcCzzf3:-NBxCE4pCAsJWkoCcUwb:b-tivzji) ([raw file](https://github.com/harness/harness-core/blob/aef652e9a9a288a0fdc8475fdd4e6cee71eb4401/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ShellScriptTaskNG.java#L86)):*
> ```Java
>     } else {
>       try {
>         // TODO lets make a method similar to this GABRIEL
> ```

rm, I already referenced this

**Comment by GabeAboy** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ShellScriptTaskNG.java` line 139 at r1](https://reviewable.io/reviews/harness/harness-core/37547#-NBxCJGRE4p_IXBp7kn2:-NBxCJGRE4p_IXBp7kn3:b-ywnlnn) ([raw file](https://github.com/harness/harness-core/blob/aef652e9a9a288a0fdc8475fdd4e6cee71eb4401/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ShellScriptTaskNG.java#L139)):*
> ```Java
>   }
> 
>   public ShellExecutorConfig getShellExecutorConfig(ShellScriptTaskParametersNG taskParameters) {
> ```

revert if possible

**Comment by GabeAboy** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java` line 333 at r1](https://reviewable.io/reviews/harness/harness-core/37547#-NBxCNSxBGLY8c7HKQcA:-NBxCNSy57iBjXsYwr4z:b-owp9k) ([raw file](https://github.com/harness/harness-core/blob/aef652e9a9a288a0fdc8475fdd4e6cee71eb4401/960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java#L333)):*
> ```Java
>             format("Command completed with ExitCode (%d)", processResult.getExitValue()), INFO, commandExecutionStatus);
>       } else {
>         saveExecutionLog(format("Command completed with ExitCode (%d)", processResult.getExitValue()), INFO, commandExecutionStatus);
> ```

This is to update status of the log once finished. Otherwise the last log line will be running because of default value of saveExecutionLog

**Comment by GabeAboy** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/37547#-NBxCbch8vkv2Ophokty:-NBxCbch8vkv2Ophoktz:byp6rt5) ([raw file](https://github.com/harness/harness-core/blob/aef652e9a9a288a0fdc8475fdd4e6cee71eb4401/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L91)):*
> ```Java
> import java.io.IOException;
> import java.nio.file.NoSuchFileException;
> import java.util.*;
> ```

Revert

**Comment by GabeAboy** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 200 at r1](https://reviewable.io/reviews/harness/harness-core/37547#-NBxCfbO05pJCt8vSy8p:-NBxCfbO05pJCt8vSy8q:b6gy86v) ([raw file](https://github.com/harness/harness-core/blob/aef652e9a9a288a0fdc8475fdd4e6cee71eb4401/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L200)):*
> ```Java
>             .commandUnitName(COMMAND_UNIT)
>             .workingDirectory(COMMAND_PATH)
>             .environment(new HashMap<>())
> ```

environments always empty

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37547)

**Comment by GabeAboy** [comment]
*[`260-delegate/src/main/java/io/harness/logstreaming/LogStreamingTaskClient.java` line 171 at r1](https://reviewable.io/reviews/harness/harness-core/37547#-NBxCk2nDQDdvpT22ITX:-NBxCk2nDQDdvpT22ITY:b-9wv8ob) ([raw file](https://github.com/harness/harness-core/blob/aef652e9a9a288a0fdc8475fdd4e6cee71eb4401/260-delegate/src/main/java/io/harness/logstreaming/LogStreamingTaskClient.java#L171)):*
> ```Java
> 
>   @Override
>   public LogCallback obtainLogCallback(String commandName) {
> ```

appId and activityId are deprecated for logger, but this check requires them. Bypassing this if is necessary to get logCallBack in NGGitOpsTaskCommand

**Review by rohitk-h — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r2, 5 of 7 files at r3, 1 of 2 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37547)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRBaseStepInfo.java` line 51 at r5](https://reviewable.io/reviews/harness/harness-core/37547#-NCRifCo7lsfi6dXyo9f:-NCRifCo7lsfi6dXyo9g:b-e9nkcj) ([raw file](https://github.com/harness/harness-core/blob/10a84e44a14fd535f84bf0ab045506cf729bb61d/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRBaseStepInfo.java#L51)):*
> ```Java
> 
>   // TODO: Remove this field
>   ParameterField<Map<String, String>> stringMap;
> ```

We can remove this field as it is not being used.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStepUpdateConfigScriptWrapper.java` line 40 at r6](https://reviewable.io/reviews/harness/harness-core/37547#-NCRm7zO9MV4VfeSn9P3:-NCRm7zO9MV4VfeSn9P4:b-3i58fe) ([raw file](https://github.com/harness/harness-core/blob/e276aedc54d2c68292ad20e4bd989e8a2efdfc54/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStepUpdateConfigScriptWrapper.java#L40)):*
> ```Java
>   @NotNull
>   @JsonTypeInfo(use = NAME, property = "type", include = EXTERNAL_PROPERTY, visible = true)
>   CreatePRStepUpdateConfigScriptInlineSource spec;
> ```

This change is incorrect, `CreatePRStepUpdateConfigScriptBaseSource` was created to have Inline and Remote for now we only implemented Inline scripts. 
___
*[`960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java` line 333 at r1](https://reviewable.io/reviews/harness/harness-core/37547#-NBxCNSxBGLY8c7HKQcA:-NCRkgEs8yneEyBKTEXB:bsew3g3) ([raw file](https://github.com/harness/harness-core/blob/aef652e9a9a288a0fdc8475fdd4e6cee71eb4401/960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java#L333)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

This is to update status of the log once finished. Otherwise the last log line will be running because of default value of saveExecutionLog
</blockquote></details>

unable to understand the comment, this is a common executor why would only we require this change?

**Comment by GabeAboy** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java` line 333 at r1](https://reviewable.io/reviews/harness/harness-core/37547#-NBxCNSxBGLY8c7HKQcA:-NCRnWn01DW5KNZx7qRX:b-56vakd) ([raw file](https://github.com/harness/harness-core/blob/aef652e9a9a288a0fdc8475fdd4e6cee71eb4401/960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java#L333)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

unable to understand the comment, this is a common executor why would only we require this change?
</blockquote></details>

This change is to save the execution status. 
If we don't do this change here our Execution step will be in a running state

**Comment by rohitk-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java` line 333 at r1](https://reviewable.io/reviews/harness/harness-core/37547#-NBxCNSxBGLY8c7HKQcA:-NCRoazJA3muf8UocmuH:b5whoq7) ([raw file](https://github.com/harness/harness-core/blob/aef652e9a9a288a0fdc8475fdd4e6cee71eb4401/960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java#L333)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

This change is to save the execution status. 
If we don't do this change here our Execution step will be in a running state
</blockquote></details>

This is in the else block, can we not set `CloseLogStream` in the config? That piece is mean't to close the logs as I understand it.

**Comment by rohitk-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStepUpdateConfigScriptWrapper.java` line 40 at r6](https://reviewable.io/reviews/harness/harness-core/37547#-NCRm7zO9MV4VfeSn9P3:-NCTaaLD6S8-0yuQJLkg:b-s2g6uv) ([raw file](https://github.com/harness/harness-core/blob/e276aedc54d2c68292ad20e4bd989e8a2efdfc54/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStepUpdateConfigScriptWrapper.java#L40)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

This change is incorrect, `CreatePRStepUpdateConfigScriptBaseSource` was created to have Inline and Remote for now we only implemented Inline scripts. 
</blockquote></details>

ok to keep this as is as discussed offline

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37547)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Comment by rohitk-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java` line 341 at r8](https://reviewable.io/reviews/harness/harness-core/37547#-NCWlnVV3ALQdHb9Vb1_:-NCWlnVWEsM5q3GAWjzF:b-3707kl) ([raw file](https://github.com/harness/harness-core/blob/5ac3f0090e44436036f8a02abf3a60ca5a43c8c7/960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java#L341)):*
> ```Java
>       } else {
>         saveExecutionLog(
>             format("Command completed with ExitCode (%d)", processResult.getExitValue()), INFO, commandExecutionStatus);
> ```

can we set the closeLogStream in the config so that we will not need to modify this piece in scriptExecutor?

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 1 of 11 files at r1, 1 of 7 files at r3, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37547)* status: 1 change requests. 0 of 1 approvals obtained.

**Comment by GabeAboy** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java` line 333 at r1](https://reviewable.io/reviews/harness/harness-core/37547#-NBxCNSxBGLY8c7HKQcA:-NCWn1g_-sMKRWyIPLQA:b-6qh4wl) ([raw file](https://github.com/harness/harness-core/blob/aef652e9a9a288a0fdc8475fdd4e6cee71eb4401/960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java#L333)):*
>  closeLogStream in the config so that we will not 
We want to close the logs here for to modify the commandUnitsProgress. The stream stays open for the rest of the createPR/mergePR steps

**Review by rohitk-h — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37547)* status: :shipit: complete! ✓

**Review by rohitk-h — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37547)* status: 1 change requests. 0 of 1 approvals obtained.

**Comment by GabeAboy** [comment]
trigger feature-build

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37547)* status: 1 change requests. 0 of 1 approvals obtained.

**Comment by GabeAboy** [comment]
trigger feature-build

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37547)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37547#-:-ND1vrrG5_rH5z5Je58t:bnfp4nl)* status: :shipit: complete! ✓

**Pull request closed without merging**
