### PR TITLE
feat: [CDS-48893]: Added new API for listing nodes based on path

### PR DESCRIPTION
**Pull request by ivan-83**
## Describe your changes
Added the new endpoint to listing file store nodes (files/folders) on the path including first-level nodes and sub-nodes.
The new endpoint accepts identifiers based on scope, it takes accountIdentifier on account level,  
accountIdentifier, orgIdentifier on org level, accountIdentifier, orgIdentifier, projectIdentifier on project level.
The path is a required parameter and should be a full node path.

The API endpoint is hidden from the Swagger doc and intended for internal use. There is no requirement to make it open for the time being. 
The code is implemented based on recursion, the logic within the code searching for the nodes on each sub-path part but only listing nodes' metadata on the first level. It should not cause any performance issues. The file content is not included only nodes metadata.

GET >> https://fqdn/file-store/folder?accountIdentifier=<accountIdentifier>&path=<path>

The API request example on the local env,
https://localhost:7090/file-store/folder?accountIdentifier=kmpySmUISimoRrJL6NL73w&path=/folder4/file13

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42601)

### CODE REVIEW

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42601)* status: 8 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`877-filestore/src/main/java/io/harness/filestore/resource/FileStoreResource.java` line 338 at r1](https://reviewable.io/reviews/harness/harness-core/42601#-NLfAx8A7dN2Nh0PB5nO:-NLfRIFzDJRCuVvrUD0T:bu1fe5j) ([raw file](https://github.com/harness/harness-core/blob/a9dbf5a0daf966e56c329efe9312afa1f4d1a026/877-filestore/src/main/java/io/harness/filestore/resource/FileStoreResource.java#L338)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

why is this null?
</blockquote></details>

We are checking FILE_VIEW_PERMISSION on FILES(FS) level for users from the context. We don't have a request to check permissions for each file for the time being. It is also done for other resources. 
___
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java` line 510 at r1](https://reviewable.io/reviews/harness/harness-core/42601#-NLfBp7q4uQRISvKsoXe:-NLfTKcvBz0AB3i3rHiG:bwnymql) ([raw file](https://github.com/harness/harness-core/blob/a9dbf5a0daf966e56c329efe9312afa1f4d1a026/877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java#L510)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

we are updating the same list that we are iterating over, could lead to some issue that would be really hard to debug
</blockquote></details>

We are passing the list reference as a method param not iterating over the list. Before passing the list reference we modify it.  It happens in one thread context.

**Review by acasian-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42601)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/42601#-NLf9tX2CY7KqbsXrB-D:-NLtsiwMCrrG2BiF5pNU:bd0axuj) (no related file):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

@ivan-83 please provide the PR description about the change. Sample request/response.
</blockquote></details>

please udate the pr description

___

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42601)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42601)* status: :shipit: complete! ✓

**Review by bojanmicovic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42601)* status: :shipit: complete! ✓

**Pull request merged**
