### PR TITLE
[feat]: [PIE-4228]: Implement Input Set Import flow

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34608)

### CODE REVIEW

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34608#-:-N5F2r0a7rj3dZ06Ee84:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34608)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 494 at r1](https://reviewable.io/reviews/harness/harness-core/34608#-N5F8Y8d7CAOREIIBP8X:-N5F8Y8e0pLYWsPgKK4V:bhq14ry) ([raw file](https://github.com/harness/harness-core/blob/df22e788012669659c0ca0124db5d5cd2d6c1403/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L494)):*
> ```Java
>     invalidYamlException.setYaml(pipelineYaml);
>     return invalidYamlException;
>   }
> ```

All of these are helper methods, better to move into helper class



_Code quote:_
```Java
  String updateFieldsInImportedInputSet(String orgIdentifier, String projectIdentifier, String pipelineIdentifier,
      String inputSetIdentifier, InputSetImportRequestDTO inputSetImportRequest, String importedInputSet) {
    if (EmptyPredicate.isEmpty(importedInputSet)) {
      String errorMessage = format(
          "Empty YAML found on Git in branch [%s] for Input Set [%s] of Pipeline [%s] under Project[%s], Organization [%s].",
          GitAwareContextHelper.getBranchInRequest(), inputSetIdentifier, pipelineIdentifier, projectIdentifier,
          orgIdentifier);
      throw PMSPipelineServiceHelper.buildInvalidYamlException(errorMessage, importedInputSet);
    }
    YamlField inputSetYAMLField;
    try {
      inputSetYAMLField = YamlUtils.readTree(importedInputSet);
    } catch (IOException e) {
      String errorMessage = PipelineCRUDErrorResponse.errorMessageForNotAYAMLFile(
          GitAwareContextHelper.getBranchInRequest(), GitAwareContextHelper.getFilepathInRequest());
      throw buildInvalidYamlException(errorMessage, importedInputSet);
    }
    YamlField inputSetInnerField = inputSetYAMLField.getNode().getField(EntityYamlRootNames.INPUT_SET);
    boolean isOverlay = false;
    if (inputSetInnerField == null) {
      inputSetInnerField = inputSetYAMLField.getNode().getField(EntityYamlRootNames.OVERLAY_INPUT_SET);
      isOverlay = true;
      if (inputSetInnerField == null) {
        String errorMessage = format("File found on Git in branch [%s] for filepath [%s] is not an Input Set YAML.",
            GitAwareContextHelper.getBranchInRequest(), GitAwareContextHelper.getFilepathInRequest());
        throw buildInvalidYamlException(errorMessage, importedInputSet);
      }
    }
    return updateCommonFieldsInImportedInputSet(orgIdentifier, projectIdentifier, pipelineIdentifier,
        inputSetIdentifier, inputSetImportRequest, importedInputSet, inputSetYAMLField, isOverlay);
  }

  String updateCommonFieldsInImportedInputSet(String orgIdentifier, String projectIdentifier, String pipelineIdentifier,
      String inputSetIdentifier, InputSetImportRequestDTO inputSetImportRequest, String importedInputSet,
      YamlField inputSetField, boolean isOverlay) {
    YamlField inputSetInnerField;
    if (isOverlay) {
      inputSetInnerField = inputSetField.getNode().getField(EntityYamlRootNames.OVERLAY_INPUT_SET);
    } else {
      inputSetInnerField = inputSetField.getNode().getField(EntityYamlRootNames.INPUT_SET);
    }
    boolean hasMetadataChanged = false;

    String identifierFromGit = inputSetInnerField.getNode().getIdentifier();
    if (!inputSetIdentifier.equals(identifierFromGit)) {
      YamlUtils.setStringValueForField(YAMLFieldNameConstants.IDENTIFIER, inputSetIdentifier, inputSetInnerField);
      hasMetadataChanged = true;
    }

    String nameFromGit = inputSetInnerField.getNode().getName();
    if (!inputSetImportRequest.getInputSetName().equals(nameFromGit)) {
      YamlUtils.setStringValueForField(
          YAMLFieldNameConstants.NAME, inputSetImportRequest.getInputSetName(), inputSetInnerField);
      hasMetadataChanged = true;
    }

    String orgIdentifierFromGit = inputSetInnerField.getNode().getStringValue(YAMLFieldNameConstants.ORG_IDENTIFIER);
    if (!orgIdentifier.equals(orgIdentifierFromGit)) {
      YamlUtils.setStringValueForField(YAMLFieldNameConstants.ORG_IDENTIFIER, orgIdentifier, inputSetInnerField);
      hasMetadataChanged = true;
    }

    String projectIdentifierFromGit =
        inputSetInnerField.getNode().getStringValue(YAMLFieldNameConstants.PROJECT_IDENTIFIER);
    if (!projectIdentifier.equals(projectIdentifierFromGit)) {
      YamlUtils.setStringValueForField(
          YAMLFieldNameConstants.PROJECT_IDENTIFIER, projectIdentifier, inputSetInnerField);
      hasMetadataChanged = true;
    }

    String descriptionFromGit = inputSetInnerField.getNode().getStringValue(YAMLFieldNameConstants.DESCRIPTION);
    if (inputSetImportRequest.getInputSetDescription() != null
        && !inputSetImportRequest.getInputSetDescription().equals(descriptionFromGit)) {
      YamlUtils.setStringValueForField(
          YAMLFieldNameConstants.DESCRIPTION, inputSetImportRequest.getInputSetDescription(), inputSetInnerField);
      hasMetadataChanged = true;
    }
    if (isOverlay) {
      String pipelineIdentifierFromGit =
          inputSetInnerField.getNode().getStringValue(YAMLFieldNameConstants.PIPELINE_IDENTIFIER);
      if (!pipelineIdentifier.equals(pipelineIdentifierFromGit)) {
        YamlUtils.setStringValueForField(
            YAMLFieldNameConstants.PIPELINE_IDENTIFIER, pipelineIdentifier, inputSetInnerField);
        hasMetadataChanged = true;
      }
    } else {
      String pipelineIdentifierFromGit = inputSetInnerField.getNode()
                                             .getFieldOrThrow(YAMLFieldNameConstants.PIPELINE)
                                             .getNode()
                                             .getStringValue(YAMLFieldNameConstants.IDENTIFIER);
      if (!pipelineIdentifier.equals(pipelineIdentifierFromGit)) {
        YamlUtils.setStringValueForField(YAMLFieldNameConstants.PIPELINE_IDENTIFIER, pipelineIdentifier,
            inputSetInnerField.getNode().getField(YAMLFieldNameConstants.PIPELINE));
        hasMetadataChanged = true;
      }
    }

    if (hasMetadataChanged) {
      try {
        importedInputSet = YamlUtils.writeYamlString(inputSetField).replace("---\n", "");
      } catch (IOException e) {
        log.error("Unexpected error when trying to set description", e);
        throw new UnexpectedException("Unexpected error when trying to set Pipeline Metadata. Please try again.", e);
      }
    }
    return importedInputSet;
  }

  InvalidYamlException buildInvalidYamlException(String errorMessage, String pipelineYaml) {
    YamlSchemaErrorWrapperDTO errorWrapperDTO =
        YamlSchemaErrorWrapperDTO.builder()
            .schemaErrors(
                Collections.singletonList(YamlSchemaErrorDTO.builder().message(errorMessage).fqn("$.inputSet").build()))
            .build();
    InvalidYamlException invalidYamlException = new InvalidYamlException(errorMessage, errorWrapperDTO);
    invalidYamlException.setYaml(pipelineYaml);
    return invalidYamlException;
  }
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34608)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 494 at r1](https://reviewable.io/reviews/harness/harness-core/34608#-N5F8Y8d7CAOREIIBP8X:-N5FBtyk1DgeyEal7ceD:b-pwvny7) ([raw file](https://github.com/harness/harness-core/blob/df22e788012669659c0ca0124db5d5cd2d6c1403/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L494)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

All of these are helper methods, better to move into helper class
</blockquote></details>

will do in the refactor PR. Right now there is no helper class.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34608)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34608#-:-N5FPGx08ctLSdWwikQC:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34608)* status: :shipit: complete! ✓

___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 494 at r1](https://reviewable.io/reviews/harness/harness-core/34608#-N5F8Y8d7CAOREIIBP8X:-N5J4I6K-FNtCc9hSlpN:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/df22e788012669659c0ca0124db5d5cd2d6c1403/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L494)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

will do in the refactor PR. Right now there is no helper class.
</blockquote></details>

done

**Pull request merged**
