### PR TITLE
[feat]: [PL-24146]: Added List api

### PR DESCRIPTION
**Pull request by meenakshi-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32699)

### CODE REVIEW

**Comment by nishantsaini20** [comment]
trigger messagecheck

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32699)* status: 8 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/32699#-N1EfcWzAOizOSx5c2_n:-N1F7-Hi4jxHSIvC3qtm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3695c02da0d17a09fabde4150bb11f1057183524/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L94)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should we add mongo index for this?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/variable/services/impl/VariableServiceImplTest.java` line 265 at r2](https://reviewable.io/reviews/harness/harness-core/32699#-N1Ef6bIBD9ta0I8o-zS:-N1F712FCP1tMmwtsqp2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3695c02da0d17a09fabde4150bb11f1057183524/120-ng-manager/src/test/java/io/harness/ng/core/variable/services/impl/VariableServiceImplTest.java#L265)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Criteria can be captured and verified for various conditions which are part of getCriteriaForVariableList method
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 6 of 7 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32699)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32699)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 5 of 7 files at r2, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32699)* status: :shipit: complete! ✓

**Pull request merged**
