### PR TITLE
techdebt: [DEL-5679]: Add granular build files for 960-api-services folder

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes

Create granular build targets for 960-api-services.

I have wrapped all changes in the same PR, as the changes needed to fix cycles were very trivial. Here are a few notable changes:

1) maven-manifest.json updated this file, since we had quite a few dependencies since this was last updated

2) Moved import io.harness.pcf.cfcli.CfCliCommandResolver -> io.harness.pcf.cfcli.resolver.CfCliCommandResolver;

This is to resolve a cycle between io.harness.pcf.cfcli and io.harness.pcf.cfcli.client

3) Moved io.harness.aws.AwsCallTracker -> *o.harness.aws.util.AwsCallTracker

This is to resolve the cycle between software.wings.service.impl and io.harness.aws

4) Moved inner classes GcrImageTagResponse, DockerImageTagResponse and DockerRegistryToken to the outer class - so remove drop dependencies on nested folders.

## Checklist
- [X] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42458)

### CODE REVIEW

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 176 of 177 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42458)* status: :shipit: complete! ✓

**Review by Raghav-Murali — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42458)* status: :shipit: complete! ✓

___
*[`maven-manifest-override.txt` line 6 at r2](https://reviewable.io/reviews/harness/harness-core/42458#-NLTLlCD2fPgo-mod5eJ:-NLTLlCE4jBxhWRkfo6U:b5djnv5) ([raw file](https://github.com/harness/harness-core/blob/31abc26c7fc757e7f7ec5cac27b630d93b046ed3/maven-manifest-override.txt#L6)):*
> ```help
> com.google.inject.name,@maven//:com_google_inject_guice
> com.google.protobuf,@maven//:com_google_protobuf_protobuf_java
> com.mongodb,@maven//:org_mongodb_mongo_java_driver
> ```

Recently we moved to `@maven//:dev_morphia_morphia_core` from `org_morphia` should that also be updated here ? Since the Build cleaner is not able to resolve it and we have to manually add that.

**Review by gn-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42458)* status: 1. unresolved discussions. 

___
*[`maven-manifest-override.txt` line 6 at r2](https://reviewable.io/reviews/harness/harness-core/42458#-NLTLlCD2fPgo-mod5eJ:-NLU2KcX9XyGMekgC00g:b-abuql1) ([raw file](https://github.com/harness/harness-core/blob/31abc26c7fc757e7f7ec5cac27b630d93b046ed3/maven-manifest-override.txt#L6)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

Recently we moved to `@maven//:dev_morphia_morphia_core` from `org_morphia` should that also be updated here ? Since the Build cleaner is not able to resolve it and we have to manually add that.
</blockquote></details>

That change was reverted. Regardless, we needed an update to the maven-manifest.json file instead of this override file, which I did in this PR

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 176 of 177 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42458)* status: 1. unresolved discussions.

**Review by mdmilic — APPROVED** [review]
> Reviewed 176 of 177 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42458)* status: 1. unresolved discussions. 

___
*[`960-api-services/BUILD.bazel` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/42458#-NLWn0no7J95SP-7lTQW:-NLWn0no7J95SP-7lTQX:b-skxlar) ([raw file](https://github.com/harness/harness-core/blob/31abc26c7fc757e7f7ec5cac27b630d93b046ed3/960-api-services/BUILD.bazel#L13)):*
> ```Starlark
>     name = "module",
>     visibility = ["//visibility:public"],
>     exports = [
> ```

what's the use of exports vs deps (I'm assuming that you need one or the other to run the tests)

**Review by Raghav-Murali — APPROVED** [review]
> Reviewed 176 of 177 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42458)* status: 1. unresolved discussions.

**Review by mdmilic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42458)* status: 1. unresolved discussions.

**Review by Raghav-Murali — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42458)* status: :shipit: complete! ✓

**Pull request merged**
