### PR TITLE
fix: [PL-21808]: Full Sync should record error

### PR DESCRIPTION
**Pull request by abhinav-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30586)

Screenshot 2022-02-07 at 9 54 36 PM

### CODE REVIEW

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30586)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[200-functional-test/src/test/java/io/harness/functional/yaml/YamlFunctionalTestHelper.java, line 209 at r1](https://reviewable.io/reviews/harness/harness-core/30586#-MvK-Rrk5hH-CiWJDN0d:-MvK-Rrk5hH-CiWJDN0e:b-v4c26j) ([raw file](https://github.com/harness/harness-core/blob/899d544c67636614b4d4fd04aeafce787ae2583f/200-functional-test/src/test/java/io/harness/functional/yaml/YamlFunctionalTestHelper.java#L209)):*
> ```Java
>         yamlGitService.obtainApplicationYamlGitFileChanges(ACCOUNT_ID, oldApp).getGitFileChanges();
>     List<GitFileChange> newAppChanges =
>         yamlGitService.obtainApplicationYamlGitFileChanges(ACCOUNT_ID, newApp).getGitFileChanges();
> ```

null check if obtainApplicationYamlGitFileChanges(ACCOUNT_ID, newApp) returns null
___
*[400-rest/src/main/java/software/wings/beans/yaml/FullSyncChangeset.java, line 9 at r1](https://reviewable.io/reviews/harness/harness-core/30586#-MvK-ILS45Bj9x03IzbY:-MvK-ILS45Bj9x03IzbZ:b8y1vfl) ([raw file](https://github.com/harness/harness-core/blob/899d544c67636614b4d4fd04aeafce787ae2583f/400-rest/src/main/java/software/wings/beans/yaml/FullSyncChangeset.java#L9)):*
> ```Java
> @Value
> @Builder
> public class FullSyncChangeset {
> ```

This looks like a fullsyncrequest object, does it itself contains the yaml errors ?
___
*[400-rest/src/main/java/software/wings/beans/yaml/FullSyncChangeset.java, line 11 at r1](https://reviewable.io/reviews/harness/harness-core/30586#-MvK-gLO0x2tbaHPrHKx:-MvK-gLP5VoUZ27ipEtv:b-r5bwgc) ([raw file](https://github.com/harness/harness-core/blob/899d544c67636614b4d4fd04aeafce787ae2583f/400-rest/src/main/java/software/wings/beans/yaml/FullSyncChangeset.java#L11)):*
> ```Java
> public class FullSyncChangeset {
>   List<GitFileChange> gitFileChanges;
>   List<FullSyncError> yamlErrors;
> ```

 we have GitFileChange at this level and also in FullSyncErrors
___
*[400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java, line 368 at r1](https://reviewable.io/reviews/harness/harness-core/30586#-MvK1YjT35FG4u4Jw6w_:-MvK1YjT35FG4u4Jw6wa:b-92oo04) ([raw file](https://github.com/harness/harness-core/blob/899d544c67636614b4d4fd04aeafce787ae2583f/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L368)):*
> ```Java
> 
>   private void insertErrorDuringYamlCollection(String accountId, String appId, List<FullSyncError> yamlErrors) {
>     yamlErrors.forEach(yamlError -> {
> ```

null check for yamlErrors

emptyIfNull
___
*[400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java, line 369 at r1](https://reviewable.io/reviews/harness/harness-core/30586#-MvK1xvw9c78Nwm9S0wP:-MvK1xvx7ZNjemkcL0Mw:b-fmullq) ([raw file](https://github.com/harness/harness-core/blob/899d544c67636614b4d4fd04aeafce787ae2583f/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L369)):*
> ```Java
>   private void insertErrorDuringYamlCollection(String accountId, String appId, List<FullSyncError> yamlErrors) {
>     yamlErrors.forEach(yamlError -> {
>       gitSyncErrorService.upsertGitSyncErrors(yamlError.getGitFileChange(), yamlError.getError(), true, false);
> ```

Will this error be noted as harnessToGit error ?

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30586)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java, line 496 at r1](https://reviewable.io/reviews/harness/harness-core/30586#-MvK3ovv3QEs4l5GJLrK:-MvK3ovv3QEs4l5GJLrL:b-hiu62u) ([raw file](https://github.com/harness/harness-core/blob/899d544c67636614b4d4fd04aeafce787ae2583f/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L496)):*
> ```Java
> 
>     List<GitFileChange> gitFileChanges = new ArrayList<>();
>     return yamlDirectoryService.traverseDirectory(
> ```

In traverseDirectory we eventually use mulitple threads to add their gitFileChanges like different thread for cloud provider, source repo provider etc.

The arraylist is not a synchronised list, whether two parallel writes to the list can create an issue ?

**Comment by abhinav-harness** [comment]
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/harness/harness-core/30586#-MvK4Q7U0ZDdu7rYNYUm):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Full sync already records errors. Do we want to get all the errors at once so that we don't have to do full sync again ?
</blockquote></details>

Full sync records error and gracefully discards all of them at end :p: 
tagged you in that line

**Comment by abhinav-harness** [comment]
___
*[200-functional-test/src/test/java/io/harness/functional/yaml/YamlFunctionalTestHelper.java, line 209 at r1](https://reviewable.io/reviews/harness/harness-core/30586#-MvK-Rrk5hH-CiWJDN0d:-MvNSRAJDqA6IdkIHJjP:b97o58h) ([raw file](https://github.com/harness/harness-core/blob/899d544c67636614b4d4fd04aeafce787ae2583f/200-functional-test/src/test/java/io/harness/functional/yaml/YamlFunctionalTestHelper.java#L209)):*
> tionYamlGitFileChanges(A
its test so ignoring :P

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30586)* status: 9 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/beans/yaml/FullSyncChangeset.java, line 9 at r1](https://reviewable.io/reviews/harness/harness-core/30586#-MvK-ILS45Bj9x03IzbY:-MvNTIyC1K1udpZNOR2F:b-78c69h) ([raw file](https://github.com/harness/harness-core/blob/899d544c67636614b4d4fd04aeafce787ae2583f/400-rest/src/main/java/software/wings/beans/yaml/FullSyncChangeset.java#L9)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

This looks like a fullsyncrequest object, does it itself contains the yaml errors ?
</blockquote></details>

yes Full Sync error object contains yaml error. 
___
*[400-rest/src/main/java/software/wings/beans/yaml/FullSyncChangeset.java, line 11 at r1](https://reviewable.io/reviews/harness/harness-core/30586#-MvK-gLO0x2tbaHPrHKx:-MvNSfzN7BLQ8aqjRlsH:b-oxrgye) ([raw file](https://github.com/harness/harness-core/blob/899d544c67636614b4d4fd04aeafce787ae2583f/400-rest/src/main/java/software/wings/beans/yaml/FullSyncChangeset.java#L11)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

 we have GitFileChange at this level and also in FullSyncErrors
</blockquote></details>

yes, error gitfile change are in full sync error object along with failure msg
___
*[400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java, line 369 at r1](https://reviewable.io/reviews/harness/harness-core/30586#-MvK1xvw9c78Nwm9S0wP:-MvNTQhWEA8chE0jP4bm:b-hyp1r2) ([raw file](https://github.com/harness/harness-core/blob/899d544c67636614b4d4fd04aeafce787ae2583f/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L369)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Will this error be noted as harnessToGit error ?
</blockquote></details>

yes last false is g2h. 
___
*[400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java, line 496 at r1](https://reviewable.io/reviews/harness/harness-core/30586#-MvK3ovv3QEs4l5GJLrK:-MvNUtjZBwphE6HFmkLK:bvd63y7) ([raw file](https://github.com/harness/harness-core/blob/899d544c67636614b4d4fd04aeafce787ae2583f/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L496)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

In traverseDirectory we eventually use mulitple threads to add their gitFileChanges like different thread for cloud provider, source repo provider etc.

The arraylist is not a synchronised list, whether two parallel writes to the list can create an issue ?
</blockquote></details>

it has not created till now 
and I think they don't add to the same list.

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30586)* status: 9 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java, line 368 at r1](https://reviewable.io/reviews/harness/harness-core/30586#-MvK1YjT35FG4u4Jw6w_:-MvNWFLAAE3_Ts-l5v40:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/899d544c67636614b4d4fd04aeafce787ae2583f/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L368)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

null check for yamlErrors

emptyIfNull
</blockquote></details>

Done.



_Code quote:_
```Java
insertErrorDuringYamlCollection
```

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30586)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30586)* status: :shipit: complete! ✓

**Pull request merged**
