### PR TITLE
[feat]: [CDS-20010]: license framework for Current-Gen

### PR DESCRIPTION
**Pull request by tchaurasiya**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30043)

### CODE REVIEW

**Comment by tchaurasiya** [comment]
___
*[400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageService.java, line 13 at r1](https://reviewable.io/reviews/harness/harness-core/30043#-Mtg9gSrbXlrMr5Nd9s6-r1-13:-Mtpg_XFBTeYZKZRz4Ut:brn2ijl) ([raw file](https://github.com/harness/harness-core/blob/0b0961f3cae19e1301bac804ccfdf0b4f0bef681/400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageService.java#L13)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

do we really need this interface .?
</blockquote></details>

Keeping it for other module to be included. beside CD

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
Added a couple minor comments

> Reviewed 5 of 10 files at r1, 10 of 10 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30043#-:-Mu6VDjq0rXLoqAacw2x:b-ye60jp)* status: Some of the checks are too old. 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/io/harness/cdlicense/bean/CgServiceUsage.java, line 37 at r1](https://reviewable.io/reviews/harness/harness-core/30043#-Mtg9gSrbXlrMr5Nd9s4-r1-37:-Mu6RZsZ2W5L41xNiuu3:b-s7z8n4) ([raw file](https://github.com/harness/harness-core/blob/0b0961f3cae19e1301bac804ccfdf0b4f0bef681/400-rest/src/main/java/io/harness/cdlicense/bean/CgServiceUsage.java#L37)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We are using 2 different constructs here for marking fields' access levels, the `private` keyword, and the `@FieldDefaults` annotation. Lets stick to one and make it consistent across all our module.
___
*[400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageQueryHelper.java, line 48 at r1](https://reviewable.io/reviews/harness/harness-core/30043#-Mtg9gSrbXlrMr5Nd9s5-r1-48:-Mu6SBnI1V2cE9RC_Mde:bb6ywmx) ([raw file](https://github.com/harness/harness-core/blob/0b0961f3cae19e1301bac804ccfdf0b4f0bef681/400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageQueryHelper.java#L48)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

We also have different handling in catch block, where we have part of retry logic.
i will rethink if it can be extract.
</blockquote></details>

LGTM
___
*[400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageQueryHelper.java, line 119 at r4](https://reviewable.io/reviews/harness/harness-core/30043#-Mu6STEn833v6bbiagzX:-Mu6STEn833v6bbiagzY:bbtjim6) ([raw file](https://github.com/harness/harness-core/blob/a88584ea3b252ecd20fb66d9ea4f0626a06c4697/400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageQueryHelper.java#L119)):*
> ```Java
>   }
> 
>   private Map<String, CgServiceUsage> processResultSetToCreateServiceUsageMap(ResultSet resultSet) throws SQLException {
> ```

rename to something like `fetchServiceUsageDetails`. The method params and the return type also convey a context to what the method's functionality. Method's name need not be 'camel cased explanatory sentence'
___
*[400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageService.java, line 13 at r1](https://reviewable.io/reviews/harness/harness-core/30043#-Mtg9gSrbXlrMr5Nd9s6-r1-13:-Mu6T2cD9Cnjpz78xx5f:b-hj11v8) ([raw file](https://github.com/harness/harness-core/blob/0b0961f3cae19e1301bac804ccfdf0b4f0bef681/400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageService.java#L13)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Keeping it for other module to be included. beside CD
</blockquote></details>

makes sense. LGTM 
___
*[400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java, line 85 at r4](https://reviewable.io/reviews/harness/harness-core/30043#-Mu6TPs95mq3LwRxr32t:-Mu6TPs95mq3LwRxr32u:b-d4uzca) ([raw file](https://github.com/harness/harness-core/blob/a88584ea3b252ecd20fb66d9ea4f0626a06c4697/400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java#L85)):*
> ```Java
>       return 1L;
>     }
>     return (instanceCount + CG_LICENSE_INSTANCE_LIMIT - 1) / CG_LICENSE_INSTANCE_LIMIT;
> ```

use ternary operator to convert this to a one line method.



_Code quote:_
```Java
    if (instanceCount == 0) {
      return 1L;
    }
    return (instanceCount + CG_LICENSE_INSTANCE_LIMIT - 1) / CG_LICENSE_INSTANCE_LIMIT;
```
___
*[400-rest/src/test/java/io/harness/cdlicense/impl/CgCdLicenseUsageQueryHelperTest.java, line 88 at r4](https://reviewable.io/reviews/harness/harness-core/30043#-Mu6Tx4VDymLv2YBllV5:-Mu6Tx4VDymLv2YBllV6:b-e8512) ([raw file](https://github.com/harness/harness-core/blob/a88584ea3b252ecd20fb66d9ea4f0626a06c4697/400-rest/src/test/java/io/harness/cdlicense/impl/CgCdLicenseUsageQueryHelperTest.java#L88)):*
> ```Java
>   public void testFetchDistinctSvcIdException() throws SQLException {
>     when(preparedStatement.executeQuery()).thenThrow(new SQLException());
>     assertThatThrownBy(
> ```

check how many time DB was queried as well. Basically test if the retry logic is executed as expected as well.
___
*[400-rest/src/test/java/software/wings/service/AccountServiceTest.java, line 170 at r4](https://reviewable.io/reviews/harness/harness-core/30043#-Mu6Udxb0VhfnwHouJZW:-Mu6Udxb0VhfnwHouJZX:b9mtn3n) ([raw file](https://github.com/harness/harness-core/blob/a88584ea3b252ecd20fb66d9ea4f0626a06c4697/400-rest/src/test/java/software/wings/service/AccountServiceTest.java#L170)):*
> ```Java
>   @Mock private HarnessUserGroupService harnessUserGroupService;
>   @Mock private AccountPermissionUtils accountPermissionUtils;
>   @Mock private CgCdLicenseUsageService cgCdLicenseUsageService;
> ```

test that cgCdLicenseUsageService is called, and also the result is added to the `Account` model

**Review by tchaurasiya — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30043)* status: 16 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/io/harness/cdlicense/bean/CgServiceUsage.java, line 37 at r1](https://reviewable.io/reviews/harness/harness-core/30043#-Mtg9gSrbXlrMr5Nd9s4-r1-37:-Mu9nVKE5JJXUGnMxTZ4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b0961f3cae19e1301bac804ccfdf0b4f0bef681/400-rest/src/main/java/io/harness/cdlicense/bean/CgServiceUsage.java#L37)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

We are using 2 different constructs here for marking fields' access levels, the `private` keyword, and the `@FieldDefaults` annotation. Lets stick to one and make it consistent across all our module.
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
___
*[400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageQueryHelper.java, line 119 at r4](https://reviewable.io/reviews/harness/harness-core/30043#-Mu6STEn833v6bbiagzX:-Mu9nYFi5R75sTIe7A6l:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a88584ea3b252ecd20fb66d9ea4f0626a06c4697/400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageQueryHelper.java#L119)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

rename to something like `fetchServiceUsageDetails`. The method params and the return type also convey a context to what the method's functionality. Method's name need not be 'camel cased explanatory sentence'
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
___
*[400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java, line 85 at r4](https://reviewable.io/reviews/harness/harness-core/30043#-Mu6TPs95mq3LwRxr32t:-Mu9ncRM-NSrnW9Ji5SU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a88584ea3b252ecd20fb66d9ea4f0626a06c4697/400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java#L85)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

use ternary operator to convert this to a one line method.
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
___
*[400-rest/src/test/java/io/harness/cdlicense/impl/CgCdLicenseUsageQueryHelperTest.java, line 88 at r4](https://reviewable.io/reviews/harness/harness-core/30043#-Mu6Tx4VDymLv2YBllV5:-Mu9ngUi1-Kj3-2KDFcL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a88584ea3b252ecd20fb66d9ea4f0626a06c4697/400-rest/src/test/java/io/harness/cdlicense/impl/CgCdLicenseUsageQueryHelperTest.java#L88)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

check how many time DB was queried as well. Basically test if the retry logic is executed as expected as well.
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
___
*[400-rest/src/test/java/software/wings/service/AccountServiceTest.java, line 170 at r4](https://reviewable.io/reviews/harness/harness-core/30043#-Mu6Udxb0VhfnwHouJZW:-Mu9nlR5CEaxWQEU_b0J:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a88584ea3b252ecd20fb66d9ea4f0626a06c4697/400-rest/src/test/java/software/wings/service/AccountServiceTest.java#L170)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

test that cgCdLicenseUsageService is called, and also the result is added to the `Account` model
</blockquote></details>

Done.

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30043)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 10 files at r1, 3 of 10 files at r2, 1 of 5 files at r5, 3 of 14 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30043)* status: 13 file(s) to review. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 10 files at r2, 1 of 5 files at r5, 11 of 14 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30043)* status: 2 file(s) to review. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30043)* status: 2 file(s) to review. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java, line 39 at r7](https://reviewable.io/reviews/harness/harness-core/30043#-MwQ8K_v8XLuAMf8DaMq:-MwQ8K_wA2jYP4TX00DB:bswy9w) ([raw file](https://github.com/harness/harness-core/blob/e0c368cc6bbfbb53217625914f8b1155ef0efde1/400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java#L39)):*
> ```Java
>     Map<String, CgServiceUsage> percentileInstanceServicesUsageMap =
>         cgCdLicenseUsageQueryHelper.getPercentileInstanceForServices(
>             accountId, serviceIdsFromDeployments, 30, INSTANCE_COUNT_PERCENTILE_DISC);
> ```

is this 30 = 30 days ?

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30043)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30043)* status: :shipit: complete! ✓

**Pull request merged**
