### PR TITLE
[feat]: [CDS-80715]: upgrading jgit libs to 6.6.1.202309021850-r version

### PR DESCRIPTION
**Pull request by markoharness**
## Describe your changes
upgrading jgit libs from `5.13.0.202109080827-r ` to `6.6.1.202309021850-r` version

Several tests have been performed:

<google-sheets-html-origin><style type="text/css"></style>

ManifestFilesCommitID | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/cd/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProNativeK8snGRC8T1jj6/pipelines/NGPipeAutoNGPipeAutoguGrquF1Jkp9t60qdYPjNTmNz/deployments/yjx-rCfZTmaXmlRLJVTANg/pipeline?stage=6l7LnOm1SnqS5D08U5K8Xg&step=VCwYaDWcR_K4hr80-HAXig
-- | --
ManifestFilesCommitID (intentional error) | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/cd/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProNativeK8snGRC8T1jj6/pipelines/NGPipeAutoNGPipeAutoEzXdJQ84Ke2XxuhWvkBmrh5wL/deployments/pwM1qLEjSJSBeqVW5qNi1Q/pipeline
SingleManifestFileBranch | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/cd/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProNativeK8snGRC8T1jj6/pipelines/NGPipeAutoNGPipeAutonOGYjQtTNge8OVtgwuRIUPrlH/deployments/kEq9BubjTZ6XDGZtAE2VHA/pipeline?storeType=INLINE&stage=o7PfYDWSSzm1MniT_ru1tg&step=97rui7mESRSXb6oDLzW5qw
SingleManifestFileBranch (intentional error) | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/cd/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProNativeK8snGRC8T1jj6/pipelines/NGPipeAutoNGPipeAutonQzspJS9Ndv7ffQ7tlcgsY5fG/deployments/U9GCNZPIQQuZGSTOqHPkFg/pipeline?storeType=INLINE
MultipleManifestFiles (intentional error) | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/cd/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProNativeK8snGRC8T1jj6/pipelines/NGPipeAutoNGPipeAutoBpvhiYm5kdzoVvarek7a1aelQ/deployments/_sth1EtYSteZ6xOJN4oVww/pipeline?storeType=INLINE
  |  
k8sDeleteByManifest | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/cd/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProcbaypRFSgj/pipelines/NGPipeAutoNGPipeAutorGikWbwXQOfCDt0e7QSHVWqoO/pipeline-studio/?storeType=INLINE
k8sDeleteByRelease | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/cd/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProcbaypRFSgj/pipelines/NGPipeAutoNGPipeAutofbFNbR8KwwuPJmAW7BTMVXQAd/pipeline-studio/?storeType=INLINE
trydeletek8s | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/cd/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProcbaypRFSgj/pipelines/NGPipeAutoNGPipeAutoZQVBudE8sFOvAUZZHOZZvN925/pipeline-studio/?storeType=INLINE
tryrollbackk8s | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/cd/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProcbaypRFSgj/pipelines/NGPipeAutoNGPipeAutoqBfwy68ghUyHs71b9TMJcb5rb/pipeline-studio/?storeType=INLINE
scaleStep | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/cd/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProcbaypRFSgj/pipelines/NGPipeAutoNGPipeAutoaNBunIa09rZUmBEaN2DlEvoYv/pipeline-studio/?storeType=INLINE
  |  
K8s Rolling | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/cd/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoPro5peMYOIHaK/pipelines/NGPipeAutoNGPipeAutoUBfLEbKDL7EQggBdTvxomDOUz/pipeline-studio/?storeType=INLINE
tryapplyk8s | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/cd/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoPro5peMYOIHaK/pipelines/NGPipeAutoNGPipeAutoxdZpTHIpmOklPsuOqQVUP8t0x/pipeline-studio/?storeType=INLINE
bluegreen | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/cd/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoPro5peMYOIHaK/pipelines/NGPipeAutoNGPipeAutoYZArE2jMSd6F5BMbPav79zvye/pipeline-studio/?storeType=INLINE
canary | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/cd/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoPro5peMYOIHaK/pipelines/NGPipeAutoNGPipeAutoovpFreOtDR7WjJGnoQWsOrwVe/pipeline-studio/?storeType=INLINE
  |  
  |  
Deployment (using GitRepoHttpConnectorForAutomationTest via branch) | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/home/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProntdc9O8OoV/pipelines/NGPipeAutoNGPipeAutogNsRh6TZBE6fEJZFIMDCGY71W/executions/qE0xaCTASpO8wdzKBRo2dw/pipeline
Deployment (using GitRepoHttpConnectorForAutomationTest via commitId) | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/home/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProntdc9O8OoV/pipelines/NGPipeAutoNGPipeAutogNsRh6TZBE6fEJZFIMDCGY71W/executions/S3UY2QxTTwm99nNcw6Kt_Q/pipeline
Deployment (using GitRepoSSHConnectorForAutomationTest via branch) | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/home/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProntdc9O8OoV/pipelines/NGPipeAutoNGPipeAutogNsRh6TZBE6fEJZFIMDCGY71W/executions/NpUaVSpnQPOi8Vg_GYTr3g/pipeline
Deployment (using GitRepoSSHConnectorForAutomationTest via commitId) | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/home/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProntdc9O8OoV/pipelines/NGPipeAutoNGPipeAutogNsRh6TZBE6fEJZFIMDCGY71W/executions/89ebYB1jSvqoQSbds2XAEQ/pipeline
Deployment (using GitAccHttpConnectorForAutomationTest via branch) | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/home/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProntdc9O8OoV/pipelines/NGPipeAutoNGPipeAutogNsRh6TZBE6fEJZFIMDCGY71W/executions/KsFaeObNQZ-z5DlY_WbnJQ/pipeline
Deployment (using GitAccHttpConnectorForAutomationTest via commitId) | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/home/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProntdc9O8OoV/pipelines/NGPipeAutoNGPipeAutogNsRh6TZBE6fEJZFIMDCGY71W/executions/4gw20uaWTVeZO4AFZ9ZBwA/pipeline
Deployment (using GitAccSSHConnectorForAutomationTest via branch) | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/home/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProntdc9O8OoV/pipelines/NGPipeAutoNGPipeAutogNsRh6TZBE6fEJZFIMDCGY71W/executions/DnOTLZwfQwy-IIIW5ag3DA/pipeline
Deployment (using GitAccSSHConnectorForAutomationTest via commitId) | https://markol.pr2.harness.io/ng/account/t8patO3rT16Rf8khYUIh8w/home/orgs/Ng_Pipelines_K8s_Organisations/projects/NGPipeAutoDemoProntdc9O8OoV/pipelines/NGPipeAutoNGPipeAutogNsRh6TZBE6fEJZFIMDCGY71W/executions/XF2yOyuzT-ygpEU5Goh1xg/pipeline

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53652)

### CODE REVIEW

**Comment by markoharness** [comment]
trigger uts

**Comment by markoharness** [comment]
trigger uts

**Comment by markoharness** [comment]
trigger uts

**Comment by markoharness** [comment]
trigger uts

**Comment by markoharness** [comment]
trigger uts

**Review by acasian-harness — APPROVED** [review]

**Review by GoelPratyush99 — APPROVED** [review]

**Review by alebuh — APPROVED** [review]

**Comment by markoharness** [comment]
trigger uts

**Review by jyotiraval — DISMISSED** [review]

**Comment by markoharness** [comment]
trigger uts

**Review by alebuh — DISMISSED** [review]

**Review by GoelPratyush99 — APPROVED** [review]

**Review by abosii-harness — APPROVED** [review]

**Comment by markoharness** [comment]
trigger ut5,ut7,ut9

**Comment by markoharness** [comment]
trigger uts

**Review by pranay-harness — APPROVED** [review]

**Review by abosii-harness — APPROVED** [review]

**Review by acasian-harness — APPROVED** [review]

**Review by GoelPratyush99 — APPROVED** [review]

**Comment by markoharness** [comment]
trigger review

**Review by alebuh — APPROVED** [review]

**Comment by markoharness** [comment]
trigger uts

**Pull request merged**
