### PR TITLE
[feat]: [PL-26146]: Upgraded Platform Service & Access Control images to use UBI image

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35706)

### CODE REVIEW

**Comment by Jimit09Gandhi** [comment]
trigger messagecheck

**Comment by Jimit09Gandhi** [comment]
trigger messagecheck

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35706)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/build/build_dist.sh` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/35706#-N81zM-v5IYxFXzXHkkB:-N81zM-w0_Aukf5Cn8kG:bha8btg) ([raw file](https://github.com/harness/harness-core/blob/8f72ae53a15e3dd9ace20ea21a8252e72a6f01ec/access-control/build/build_dist.sh#L32)):*
> ```Shell
> cp ../../access-control/config/keystore.jks .
> cp ../../access-control/build/container/Dockerfile-accesscontrol-service-jenkins-k8-openjdk ./Dockerfile
> cp ../../access-control/build/container/Dockerfile-accesscontrol-service-jenkins-k8-gcr-openjdk ./Dockerfile-gcr
> ```

Can we delete this file if no longer needed : Dockerfile-accesscontrol-service-jenkins-k8-gcr-openjdk
___
*[`access-control/build/build_dist.sh` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/35706#-N81zV_i3TaJrsPGdn01:-N81zV_i3TaJrsPGdn02:b-h7xg5i) ([raw file](https://github.com/harness/harness-core/blob/483ad90661df647df5f4eb63ada9c0df22d08d3d/access-control/build/build_dist.sh#L34)):*
> ```Shell
> cp ../../dockerization/base-images/apm/inject-saas-apm-bins-into-dockerimage.sh .
> cp ../../access-control/build/container/Dockerfile-accesscontrol-service-jenkins-k8-openjdk ./Dockerfile
> cp ../../access-control/build/container/Dockerfile-accesscontrol-service-cie-jdk ./Dockerfile-cie-jdk
> ```

Its not clear to me why we have named file as :  Dockerfile-accesscontrol-service-cie-jdk.

What does cie means?



_Code quote:_
```Shell
Dockerfile-accesscontrol-service-cie-jdk
```

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35706)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/build/build_dist.sh` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/35706#-N81zM-v5IYxFXzXHkkB:-N82H_RI4q6m1o54Qju_:bpokudk) ([raw file](https://github.com/harness/harness-core/blob/8f72ae53a15e3dd9ace20ea21a8252e72a6f01ec/access-control/build/build_dist.sh#L32)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we delete this file if no longer needed : Dockerfile-accesscontrol-service-jenkins-k8-gcr-openjdk
</blockquote></details>

The idea is to cleanup once the change works successfully once through Prod deployment as per note by build team. 
https://harness.atlassian.net/wiki/spaces/ONPREM/pages/21088534606/Image+creation+Guidelines
___
*[`access-control/build/build_dist.sh` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/35706#-N81zV_i3TaJrsPGdn01:-N82H5smCoF-nmhM05w0:bq8ny5z) ([raw file](https://github.com/harness/harness-core/blob/483ad90661df647df5f4eb63ada9c0df22d08d3d/access-control/build/build_dist.sh#L34)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Its not clear to me why we have named file as :  Dockerfile-accesscontrol-service-cie-jdk.

What does cie means?
</blockquote></details>

The file name is as recommended by build team.
https://harness.atlassian.net/wiki/spaces/ONPREM/pages/21088534606/Image+creation+Guidelines

https://harness.io/blog/introducing-harness-ci-enterprise#:~:text=What%20Harness%20Did,module%20CI%20Enterprise%20(CIE).

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35706#-:-N83n_Dl1pdGlkE40KMQ:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35706#-:-N83ngbjB31Cy4F9xEw1:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
