### PR TITLE
[feat]: [PIE-7568]: Added ErrorCode "Resource_Not_Found" in response while making GET call for Pipelines via v1 APIs

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Here's the response:
Screenshot 2023-02-16 at 5 49 26 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44013)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger messagecheck

**Review by mankrit-singh — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44013)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 142 at r3](https://reviewable.io/reviews/harness/harness-core/44013#-NOPAWTJ-RsIPnWYjDZJ:-NOPAWTJ-RsIPnWYjDZK:b-vkai2m) ([raw file](https://github.com/harness/harness-core/blob/4cbd9d03ff902f9ad257dd5c17a8458ff550d0c4/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L142)):*
> ```Java
>         accountId, orgIdentifier, projectIdentifier, pipelineIdentifier, identifier, deleted, loadFromFallbackBranch);
>     if (optionalInputSetEntity.isEmpty()) {
>       throw new EntityNotFoundException(
> ```

isn't this a breaking change? I guess HTTP status code will change

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44013)* status: :shipit: complete! ✓

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44013)* status: 1. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 142 at r3](https://reviewable.io/reviews/harness/harness-core/44013#-NOPAWTJ-RsIPnWYjDZJ:-NOPBJh-E5m6xDFB2h6N:b-3hmlpm) ([raw file](https://github.com/harness/harness-core/blob/4cbd9d03ff902f9ad257dd5c17a8458ff550d0c4/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L142)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

isn't this a breaking change? I guess HTTP status code will change
</blockquote></details>

I have checked on local, UI has handled this ENTITY_NOT_FOUND same as INVALID_REQUEST. there's no change in behaviour on UI

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 142 at r3](https://reviewable.io/reviews/harness/harness-core/44013#-NOPAWTJ-RsIPnWYjDZJ:-NOPGtio6W1-0LOqQvIh:b2h06yp) ([raw file](https://github.com/harness/harness-core/blob/4cbd9d03ff902f9ad257dd5c17a8458ff550d0c4/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L142)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

I have checked on local, UI has handled this ENTITY_NOT_FOUND same as INVALID_REQUEST. there's no change in behaviour on UI
</blockquote></details>

UI is not the only consumer of the API. We have our APIs publicly exposed. We cannot make backward compatible changes.

**Pull request closed without merging**
