### PR TITLE
fix: [CDS-44524]: Fix expression rendering in createPR and updaterele…

### PR DESCRIPTION
**Pull request by rohitk-h**
…aserepostep

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38533)

### CODE REVIEW

**Review by henry-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38533)* status: 2 file(s) to review. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java` line 201 at r1](https://reviewable.io/reviews/harness/harness-core/38533#-NDoqTOt8PFWvj3NY8Yf:-NDopO-H5NvrrEe7qQDh:bj0kpee) ([raw file](https://github.com/harness/harness-core/blob/ae74d7679cd1f6e6f76e5598d8d5b8734b2c7b3c/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java#L201)):*
> ```Java
>           file = file.replaceAll("<\\+env.name>", cluster.getEnvName());
>         }
>         List<String> files = new ArrayList<>();
> ```

i'm assuming the list mutable? that is why `List<String> files = Collections.singletonList(file);` would not work

**Review by anshul-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38533)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java` line 201 at r1](https://reviewable.io/reviews/harness/harness-core/38533#-NDoqTOt8PFWvj3NY8Yf:-NDq3Dpz6fTxpCPx8k3V:btfnomy) ([raw file](https://github.com/harness/harness-core/blob/ae74d7679cd1f6e6f76e5598d8d5b8734b2c7b3c/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java#L201)):*
<details><summary><i>Previously, henry-harness (henry leong) wrote…</i></summary><blockquote>

i'm assuming the list mutable? that is why `List<String> files = Collections.singletonList(file);` would not work
</blockquote></details>

That is correct.

**Comment by rohitk-h** [comment]
trigger messagecheck

**Pull request merged**
