### PR TITLE
fix: [PIE-6825]: add strategyMetadata in newLevel in Retry

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes
**What is the issue?**
Expressions with strategy aren't getting resolved in case of retry

**What is the change?**
In retry, when new Level is added, adding strategyMetadata from currentLevel

**Impact**
No impact

**Testing**
Tested the changes in local and in PR env with and without strategy

ReleaseNotes summary needed? No

Is it new task type? No
Did you make changes to the code in a backward-compatible manner? No
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? No
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? No
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? No
if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? No
Did you remove an enum → No
Did you add an enum(That too at end of list) → No
FeatureFlag Added/Removed -> No
Verify Changes with affects any -> No

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41251)

### CODE REVIEW

**Review by sahilhindwani-harness — COMMENTED** [review]
Can we add a unit test for the same?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41251#-:-NIkY24G3fFdI0Jyz-1b:bxatg1w)* status: 1 file(s) to review. 0 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41251)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41251)* status: :shipit: complete! ✓

**Pull request merged**
