### PR TITLE
fix: [CDS-33804]: handle rollback skipping in K8s BG

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
If swap services step is not present in execution phase, rollback(swap services) is always being executed.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32123)

### CODE REVIEW

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32123)* status: 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/32123#-N-1r-2r4HRWmKeEwli-:-N-1r-2r4HRWmKeEwli0:beutiak) (no related file):*
@abhinavsingh1196 can we test this with retry failure strategy configured in the step? Set to 2-3 retries on failure.

---

**Comment by abhinavsingh1196** [comment]
*[a discussion](https://reviewable.io/reviews/harness/harness-core/32123#-N-1r-2r4HRWmKeEwli-:-N-1zy-V6TkprByVY8_W:b-gimu59) (no related file):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

@abhinavsingh1196 can we test this with retry failure strategy configured in the step? Set to 2-3 retries on failure.
</blockquote></details>

Tested BG Deploy stage with retry failure strategy (with rollback post-retry), both with and without Swap Services stage being present in the execution stage. Also tested Swap services stage failing during execution phase (with retry on failure). 

Screens:




---

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32123)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32123)* status: :shipit: complete! ✓

**Pull request merged**
