### PR TITLE
fix: [PL-31588]: Rate Limit based on QPM value from DB for external APIs

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

In `ExternalApiRateLimitingServiceImpl` we are rate limiting with a value of 60 QPS and 350 - 360 QPM. Whenever we exceed this rate we need to dump a log indicating for which `API Key` this rate limit is being exceeded to help with debugging.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45391)

### CODE REVIEW

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/ExternalApiRateLimitingServiceImpl.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/45391#-NR1Zz748GZWSF1K9Vhh:-NR1Zz748GZWSF1K9Vhi:b-jtilrx) ([raw file](https://github.com/harness/harness-core/blob/266207d2ab6e08832dafb4eb201f6c98192f7aa4/400-rest/src/main/java/software/wings/service/impl/ExternalApiRateLimitingServiceImpl.java#L43)):*
> ```Java
>             @Override
>             public RateLimiter load(String key) {
>               return RateLimiter.create(getMaxQPMPerManager() / 60);
> ```

This is correct implementation to protect against burst traffic.

**Review by gn-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45391)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/ExternalApiRateLimitingServiceImpl.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/45391#-NR1Zz748GZWSF1K9Vhh:-NR9_6tEDK45FTXtrmg2:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/266207d2ab6e08832dafb4eb201f6c98192f7aa4/400-rest/src/main/java/software/wings/service/impl/ExternalApiRateLimitingServiceImpl.java#L43)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

This is correct implementation to protect against burst traffic.
</blockquote></details>

done

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/security/AuthenticationFilter.java` line 371 at r2](https://reviewable.io/reviews/harness/harness-core/45391#-NR9_D3nB7j9SHnZJVuL:-NR9_D3nB7j9SHnZJVuM:b-6lxevq) ([raw file](https://github.com/harness/harness-core/blob/33eb0a5bbc968dfabc36f5c17663903751160d2d/400-rest/src/main/java/software/wings/security/AuthenticationFilter.java#L371)):*
> ```Java
>   private void ensureValidQPM(String key) {
>     if (rateLimitingService.rateLimitRequest(key)) {
>       log.warn("Rate Limit exceeded for key {}, QPM {} ", key, rateLimitingService.getMaxQPMPerManager());
> ```

Please log additional information , AccountId , Request Path etc

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/security/AuthenticationFilter.java` line 371 at r2](https://reviewable.io/reviews/harness/harness-core/45391#-NR9_D3nB7j9SHnZJVuL:-NR9lZmK-ypMIf4zc2w9:byoa2pf) ([raw file](https://github.com/harness/harness-core/blob/33eb0a5bbc968dfabc36f5c17663903751160d2d/400-rest/src/main/java/software/wings/security/AuthenticationFilter.java#L371)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Please log additional information , AccountId , Request Path etc
</blockquote></details>

I meant to say you can't print API key in logs that will be a security breach, You can print the Account ID and Request Path only

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45391)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/security/AuthenticationFilter.java` line 371 at r2](https://reviewable.io/reviews/harness/harness-core/45391#-NR9_D3nB7j9SHnZJVuL:-NRAHifBEr_FZGJ1WbQJ:b-4ca165) ([raw file](https://github.com/harness/harness-core/blob/33eb0a5bbc968dfabc36f5c17663903751160d2d/400-rest/src/main/java/software/wings/security/AuthenticationFilter.java#L371)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

I meant to say you can't print API key in logs that will be a security breach, You can print the Account ID and Request Path only 
</blockquote></details>

Okay got it. I will update it the logs.

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45391)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/security/AuthenticationFilter.java` line 371 at r2](https://reviewable.io/reviews/harness/harness-core/45391#-NR9_D3nB7j9SHnZJVuL:-NRAIH2wBhgTFPlRY6cC:b9ezjne) ([raw file](https://github.com/harness/harness-core/blob/33eb0a5bbc968dfabc36f5c17663903751160d2d/400-rest/src/main/java/software/wings/security/AuthenticationFilter.java#L371)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

Okay got it. I will update it the logs.
</blockquote></details>

The queryParams will print the Account and API Id. I wanted to see if the `X-Api-Key` is unique for each account or not that is why added that.

So I saw another API to generate the `X-Api-Key`, ideally that is what is being passed here and this key will be specific to an account right ?

**Review by gn-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45391)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by Raghav-Murali** [comment]
trigger messagecheck

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45391)* status: :shipit: complete! ✓

**Pull request merged**
