### PR TITLE
feat: [CDS-42505]: add agentId to gitopsClusters

### PR DESCRIPTION
**Pull request by GabeAboy**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38692)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/beans/ClusterRequest.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/38692#-NEEgvBY3uJTyW09HpmU:-NEEgvBY3uJTyW09HpmV:b-r83yg5) ([raw file](https://github.com/harness/harness-core/blob/b5adba8ea450b9e81615bed45360f64e61b97d03/127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/beans/ClusterRequest.java#L35)):*
> ```Java
>   @EntityIdentifier @Schema(description = "identifier of the cluster") String identifier;
>   @Schema(description = "organization identifier of the cluster") String orgIdentifier;
>   @Schema(description = "agent identifier of the cluster") String agentIdentifier;
> ```

Cluster Request should not contain agentID IMO
Gitops clusters have agentIDs ( on the gitops service side ) but ClusterRequest is generated by the Client (user) on the NG manager. Once a user selects a cluster to link to an environment, the cluster should be picked from it

**Comment by GabeAboy** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/beans/ClusterRequest.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/38692#-NEEgvBY3uJTyW09HpmU:-NEIIfTWAO-U73npS9gH:bmtkg5x) ([raw file](https://github.com/harness/harness-core/blob/b5adba8ea450b9e81615bed45360f64e61b97d03/127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/beans/ClusterRequest.java#L35)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Cluster Request should not contain agentID IMO
Gitops clusters have agentIDs ( on the gitops service side ) but ClusterRequest is generated by the Client (user) on the NG manager. Once a user selects a cluster to link to an environment, the cluster should be picked from it
</blockquote></details>

We need to save agent ID so that the records in collection gitopsCluster are unique. One customer can have multiple agents and across those agents have clusters with the same identifier. Therefore why we need agentID.

This ClusterRequest creates a reference of cluster to env one at a time. We also need it here



_Code quote:_
```Java
lusterReques
```

**Review by rohitk-h — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38692)* status: 1. unresolved discussions.

**Comment by rohitk-h** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/beans/ClusterRequest.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/38692#-NEEgvBY3uJTyW09HpmU:-NEIW2Sp8CJr2-TQC12P:b-tb1v11) ([raw file](https://github.com/harness/harness-core/blob/b5adba8ea450b9e81615bed45360f64e61b97d03/127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/beans/ClusterRequest.java#L35)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

We need to save agent ID so that the records in collection gitopsCluster are unique. One customer can have multiple agents and across those agents have clusters with the same identifier. Therefore why we need agentID.

This ClusterRequest creates a reference of cluster to env one at a time. We also need it here
</blockquote></details>

Account level agent and a project level agent can have same clusterIdentifier. Uniqueness of a cluster is not just a clusterIdentifier, it is a combination of agentIdentifier + clusterIdentifier. 
We have solved in connections using FQN that uses account/org/proj/clusterIdentifier and in agent case using scope. Can we use scope since we have it already in the request?

**Comment by rohitk-h** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/beans/ClusterRequest.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/38692#-NEEgvBY3uJTyW09HpmU:-NEIZTDKCIv8KS9CZ7Wz:b-ci29ei) ([raw file](https://github.com/harness/harness-core/blob/b5adba8ea450b9e81615bed45360f64e61b97d03/127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/beans/ClusterRequest.java#L35)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Account level agent and a project level agent can have same clusterIdentifier. Uniqueness of a cluster is not just a clusterIdentifier, it is a combination of agentIdentifier + clusterIdentifier. 
We have solved in connections using FQN that uses account/org/proj/clusterIdentifier and in agent case using scope. Can we use scope since we have it already in the request? 
</blockquote></details>

Thinking more, I realize that two different account level agents can have the same clusterIdentifier so the scope won't work and neither with FQN. Only agentIdentifier is the true unique property that can help differentiate. @yogesh-chauhan thoughts?

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/beans/ClusterRequest.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/38692#-NEEgvBY3uJTyW09HpmU:-NEg9u7hDKkl2m8FEXtX:b-q191n5) ([raw file](https://github.com/harness/harness-core/blob/b5adba8ea450b9e81615bed45360f64e61b97d03/127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/beans/ClusterRequest.java#L35)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Thinking more, I realize that two different account level agents can have the same clusterIdentifier so the scope won't work and neither with FQN. Only agentIdentifier is the true unique property that can help differentiate. @yogesh-chauhan thoughts?
</blockquote></details>

I think yes, in that case, we need to store agentId also but we should also validate the agentId sent in the request matches the one that is stored on the gitops service side

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38692)* status: Some of the checks are too old. 1. unresolved discussions. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/38692#-NEgAC_l0uPEtMuZKGF4:-NEgAC_l0uPEtMuZKGF5:b-lfwffi) (no related file):*
Also, if by agent identifier, mean something like
`org.myagent` or `account.myagent`, we should call it agentRef just to follow naming conventions

___

**Pull request merged**
