### PR TITLE
fix:[DEL-5597]: Add log with exception stack trace

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- Executes one-time retry when failing to create a git lock file.
- When this exception is thrown we got blind as original the exception is silenced.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41702)

### CODE REVIEW

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41702)* status: :shipit: complete! ✓

**Review by lasdox — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41702)* status: :shipit: complete! ✓

**Comment by Fernando-Dourado** [comment]
We already merged to the release branch and this help us to detect and confirm the customer issue. Now, we need to come up with the final solution.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41702)* status: :shipit: complete! ✓

**Review by lasdox — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41702)* status: :shipit: complete! ✓

**Pull request merged**
