### PR TITLE
Feat: [IDP-272]: IDP Bug Bash - Fixing issues found during IDP Bug Bash

### PR DESCRIPTION
**Pull request by sathish-soundarapandian**
## Describe your changes
1. Remove swagger stuff. We are following openAPI convention
2. Move catalogConnector stuff to gitintegration module
3. Proper exception handling in idp-service by registering existing exception mappers
4. onboarding access check API removed. UI will take care of it by leveraging ACL API
5. "/" addition in entityTargetPath if not present
6. Bug fix in choosing the secret details for git operations
7. Handling import for multiple accounts and conflict between similar named entities across org and project
8. Handle scenario wherein branch doesn't exist in the provided repo
9. Register each target individually and then register the all target in backstage

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45315)

### CODE REVIEW

**Comment by sathish-soundarapandian** [comment]
trigger ut6

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 21 of 23 files at r1, 9 of 10 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45315)* status: 0 of 1 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/processor/impl/GithubConnectorProcessor.java` line 94 at r3](https://reviewable.io/reviews/harness/harness-core/45315#-NQx8_se1iXEoPX0gvTv:-NQx8_se1iXEoPX0gvTw:bsdknux) ([raw file](https://github.com/harness/harness-core/blob/f28d29fc3e95a9a4a1354efe586c68dcdbb9cedc/idp-service/src/main/java/io/harness/idp/gitintegration/processor/impl/GithubConnectorProcessor.java#L94)):*
> ```Java
>         accountIdentifier, null, null, catalogConnectorInfo.getSourceConnector().getIdentifier());
>     String githubConnectorSecret =
>         connectorSecretsInfo.getSecond().get(GitIntegrationConstants.GITHUB_TOKEN).getDecryptedValue();
> ```

Is GITHUB_TOKEN enough in case of GitHub App as well?
___
*[`idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogComponentEntity.java` line 51 at r3](https://reviewable.io/reviews/harness/harness-core/45315#-NQx9SrR6rlxjrUPPI3-:-NQx9SrR6rlxjrUPPI30:bimn3kp) ([raw file](https://github.com/harness/harness-core/blob/f28d29fc3e95a9a4a1354efe586c68dcdbb9cedc/idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogComponentEntity.java#L51)):*
> ```Java
>     @JsonIgnore private String domain;
>     private String system;
>     @JsonIgnore private String harnessSystem;
> ```

What's the difference between system and harnessSystem?



_Code quote:_
```Java
harnessSystem
```

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45315)* status: 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/processor/impl/GithubConnectorProcessor.java` line 94 at r3](https://reviewable.io/reviews/harness/harness-core/45315#-NQx8_se1iXEoPX0gvTv:-NQxeSvQ-KtihI5_GQeQ:b-c6a14l) ([raw file](https://github.com/harness/harness-core/blob/f28d29fc3e95a9a4a1354efe586c68dcdbb9cedc/idp-service/src/main/java/io/harness/idp/gitintegration/processor/impl/GithubConnectorProcessor.java#L94)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Is GITHUB_TOKEN enough in case of GitHub App as well?
</blockquote></details>

Yes. This will be available in case of GitHub App as well and it is used only in the source push operation. The GitHub App related details and this token will be set in the backstage instance as secrets.
___
*[`idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogComponentEntity.java` line 51 at r3](https://reviewable.io/reviews/harness/harness-core/45315#-NQx9SrR6rlxjrUPPI3-:-NQxekYX8KvX-9qwRu7Q:b-nfmu5i) ([raw file](https://github.com/harness/harness-core/blob/f28d29fc3e95a9a4a1354efe586c68dcdbb9cedc/idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogComponentEntity.java#L51)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

What's the difference between system and harnessSystem?
</blockquote></details>

System is what backstage understands and harnessSystem is for our internal identification. It will be not written to DB / stored in backstage as anyways backstage doesn't understands what harnessSystem is.

**Review by vikyathharekal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45315)* status: :shipit: complete! ✓

**Pull request merged**
