### PR TITLE
feat: [PL-24963]: Improving the error message

### PR DESCRIPTION
**Pull request by Y0709**
Improving the error message by changing the exception mapper

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34664)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger messagecheck

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34664)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34664)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/graphql/GraphQLResource.java` line 135 at r2](https://reviewable.io/reviews/harness/harness-core/34664#-N5Q3WLA1aYzgfPetbYM:-N5Q3WLA1aYzgfPetbYN:buww4ag) ([raw file](https://github.com/harness/harness-core/blob/2dd58073f5fa69a89b5f6f9514b946d7fa9470cf/400-rest/src/main/java/software/wings/resources/graphql/GraphQLResource.java#L135)):*
> ```Java
>       @FormDataParam("file") InputStream uploadedInputStream, @Context HttpServletRequest httpServletRequest)
>       throws JsonProcessingException {
>     GraphQLQuery graphQLQuery = JsonUtils.asObjectWithExceptionType(query, GraphQLQuery.class);
> ```

asObjectWithExceptionHandling

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34664)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34664)* status: :shipit: complete! ✓

**Pull request merged**
