### PR TITLE
[feat]:[pie-7334]: move config contract for input sets

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added BE contract for moving input sets from either inline to remote or remote to inline

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42160)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/MoveConfigRequestDTO.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/42160#-NKrEMNDDZJ-kw5t2JOQ:-NKrEMNDDZJ-kw5t2JOR:b2ekrkp) ([raw file](https://github.com/harness/harness-core/blob/21bd7fb9b6038212b9c7d741feb0778cef38e1aa/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/MoveConfigRequestDTO.java#L66)):*
> ```Java
>   @Parameter(description = PipelineResourceConstants.INPUT_SET_ID_PARAM_MESSAGE)
>   @QueryParam(NGCommonEntityConstants.INPUT_SET_IDENTIFIER_KEY)
>   String inputSetIdentifier;
> ```

it shouldn't be used in same request dto as pipeline entity. This is wrong.

**Comment by mohitg0795** [comment]
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 545 at r2](https://reviewable.io/reviews/harness/harness-core/42160#-NKrEawd6WdvaJPYuRI9:-NKrEawd6WdvaJPYuRIA:bipw99q) ([raw file](https://github.com/harness/harness-core/blob/21bd7fb9b6038212b9c7d741feb0778cef38e1aa/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L545)):*
> ```Java
>           NGCommonEntityConstants.PROJECT_KEY) @ProjectIdentifier String projectIdentifier,
>       @Parameter(description = InputSetSchemaConstants.PIPELINE_ID_FOR_INPUT_SET_PARAM_MESSAGE) @NotNull @QueryParam(
>           NGCommonEntityConstants.PIPELINE_KEY) @ResourceIdentifier String pipelineIdentifier,
> ```

why does it need to be a query param? Its a POST request, it should be inside body, thats it

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42160)* status: 4 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/MoveConfigRequestDTO.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/42160#-NKrEMNDDZJ-kw5t2JOQ:-NKrHhD447qgy__B4tlZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21bd7fb9b6038212b9c7d741feb0778cef38e1aa/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/MoveConfigRequestDTO.java#L66)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

it shouldn't be used in same request dto as pipeline entity. This is wrong.
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 545 at r2](https://reviewable.io/reviews/harness/harness-core/42160#-NKrEawd6WdvaJPYuRI9:-NKrLwLWDjMS_LsfcKWH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21bd7fb9b6038212b9c7d741feb0778cef38e1aa/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L545)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why does it need to be a query param? Its a POST request, it should be inside body, thats it
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetMoveConfigRequestDTO.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/42160#-NKrM7TS0bUqULVljz9u:-NKrM7TS0bUqULVljz9v:b-vyv2lk) ([raw file](https://github.com/harness/harness-core/blob/bc91fc0e7e42b8072f74475c86def3c087eca043/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetMoveConfigRequestDTO.java#L32)):*
> ```Java
> @FieldNameConstants(innerTypeName = "InputSetMoveConfigRequestKeys")
> @Schema(name = "InputSetMoveConfigRequestDTO",
>     description = "Details to move input set from harness to git or git to harness")
> ```

why would description be "git to harness"

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42160)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetMoveConfigRequestDTO.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/42160#-NKrM7TS0bUqULVljz9u:-NKrPyu6EfS2AMVDEOOU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bc91fc0e7e42b8072f74475c86def3c087eca043/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetMoveConfigRequestDTO.java#L32)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why would description be "git to harness"
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42160)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42160)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 4 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42160)* status: :shipit: complete! ✓

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetMoveConfigRequestDTO.java` line 33 at r5](https://reviewable.io/reviews/harness/harness-core/42160#-NKv4lTu5Mkr4V_TcdW8:-NKv4lTv0OXLeSGuNriG:be135me) ([raw file](https://github.com/harness/harness-core/blob/4ce5190131af13f1834389207cb09e268f37f605/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetMoveConfigRequestDTO.java#L33)):*
> ```Java
> @Schema(name = "InputSetMoveConfigRequestDTO",
>     description = "Details to move input set from inline to remote or remote to inline")
> @OwnedBy(PL)
> ```

pipeline team

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42160)* status: :shipit: complete! ✓

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetMoveConfigRequestDTO.java` line 33 at r5](https://reviewable.io/reviews/harness/harness-core/42160#-NKv4lTu5Mkr4V_TcdW8:-NKv53T1DttLFnplXsf6:b6an6jr) ([raw file](https://github.com/harness/harness-core/blob/4ce5190131af13f1834389207cb09e268f37f605/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetMoveConfigRequestDTO.java#L33)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

pipeline team
</blockquote></details>

done, discussed offline

**Pull request merged**
