### PR TITLE
feat: [CDS-56648]: Resolve release placeholder in Kubernetes Tasks

### PR DESCRIPTION
**Pull request by abosii-harness**
## Describe your changes
We will provide different placeholders like $__HARNES_INTERNAL_RELEASE_REVISION and $__HARNES_INTERNAL_RELEASE_COLOR that we will later hide it behind native harness expression <+kubernetes.release.revision> and <+kubernetes.release.color> 

This PR handle these placeholders as part of the task. We will get the revision number and color (only if declarative rollback is enabled) from current release or latests release (in case of blue/green). Any placeholders found in values/params or kustomize patches will be replaced with these values. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45619)

### CODE REVIEW

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45619)* status: 24 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java` line 118 at r1](https://reviewable.io/reviews/harness/harness-core/45619#-NRZ8-L7A-qrloeSpmDW:-NRZ8-L7A-qrloeSpmDX:bo8qwu) ([raw file](https://github.com/harness/harness-core/blob/00f454b58a34b83317fdfeef12bc70c8d5cf0052/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java#L118)):*
> ```Java
> 
>     KubernetesReleaseDetails releaseDetails = null;
>     // For backward compatibility if delegate is released before ng-manager
> ```

this is not possible? 
if this boolean was primitive we could get rid of this null check?

**Review by abosii-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45619)* status: 24 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java` line 118 at r1](https://reviewable.io/reviews/harness/harness-core/45619#-NRZ8-L7A-qrloeSpmDW:-NRZQbun-nCWZXF-l_d2:b9ll2bx) ([raw file](https://github.com/harness/harness-core/blob/00f454b58a34b83317fdfeef12bc70c8d5cf0052/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java#L118)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

this is not possible? 
if this boolean was primitive we could get rid of this null check? 
</blockquote></details>

Theoretically not, but just to be sure
The idea behind reference boolean instead of primitive is just to be sure that manager is sending the value otherwise it may end up in wrong behavior

**Comment by abosii-harness** [comment]
trigger ut5

**Review by abhinavsingh1196 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45619)* status: 24 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45619)* status: 24 file(s) to review. 1 of 2 approvals obtained.

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 23 of 24 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45619)* status: :shipit: complete! ✓

**Comment by abosii-harness** [comment]
trigger messagecheck

**Pull request merged**
