### PR TITLE
feat: [PIE-5248]: Support for services filtering in pipeline list page

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37223)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37223)

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 266 at r1](https://reviewable.io/reviews/harness/harness-core/37223#-NBLNDZhAZZIXBN0lQyw:-NBLNDZhAZZIXBN0lQyx:b-dsufs6) ([raw file](https://github.com/harness/harness-core/blob/55fa11f3dafeaa4895f78ede0bb2bf29c14ae57e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L266)):*
> ```Java
> 
>   private void addFiltersForServices(FilterCreationContext filterCreationContext, CdFilterBuilder filterBuilder,
>       ServicesYaml service, ServiceDefinitionType deploymentType) {
> ```

nit: we should rename to "services"

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 224 at r1](https://reviewable.io/reviews/harness/harness-core/37223#-NBLSsQT4vtO123JAOV5:-NBLSsQU503EW363Z2Zd:b-f4wzb2) ([raw file](https://github.com/harness/harness-core/blob/55fa11f3dafeaa4895f78ede0bb2bf29c14ae57e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L224)):*
> ```Java
>                   filterCreationContext.getSetupMetadata().getOrgId(),
>                   filterCreationContext.getSetupMetadata().getProjectId(), entity.getIdentifier(),
>                   infraList.get(0).getIdentifier().getValue());
> ```

we need to update this as well, here we are currently taking only the 1st element

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 224 at r1](https://reviewable.io/reviews/harness/harness-core/37223#-NBLSsQT4vtO123JAOV5:-NBRIAiTDyQwY880m6Al:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/55fa11f3dafeaa4895f78ede0bb2bf29c14ae57e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L224)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we need to update this as well, here we are currently taking only the 1st element
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37223)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37223)* status: :shipit: complete! ✓

**Pull request merged**
