### PR TITLE
fix: [SRM-10594]: Better error message and response code in delegate time out

### PR DESCRIPTION
**Pull request by AbhijithHarness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34049)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34049)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/eraro/ErrorCode.java` line 129 at r1](https://reviewable.io/reviews/harness/harness-core/34049#-N3xxuAq6sCbyZeXP7-N:-N3xxuAr68VbAoIPUtha:b-1irsfy) ([raw file](https://github.com/harness/harness-core/blob/63d5da9daaf4b63ee0ab39b5be4dce2117d53f85/980-commons/src/main/java/io/harness/eraro/ErrorCode.java#L129)):*
> ```Java
>   UNEXPECTED,
> 
>   UNKNOWN_ERROR(INTERNAL_SERVER_ERROR),
> ```

I think UNKNOWN_ERROR is used in many places. Will this cause issue in other places?

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34049#-:-N40_T_o8nQ8-r1X3VR6:bnfp4nl)* status: :shipit: complete! ✓

**Comment by AbhijithHarness** [comment]
trigger ti0

**Comment by AbhijithHarness** [comment]
trigger ti2

**Comment by AbhijithHarness** [comment]
trigger ti4

**Comment by AbhijithHarness** [comment]
trigger ti0

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 9 of 10 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34049)* status: :shipit: complete! ✓

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 9 of 10 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34049)* status: :shipit: complete! ✓

**Pull request merged**
