### PR TITLE
feat: [PL-25694]: fix error in branch listing for ADO

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
Added connection url details for AzureRepo Connector.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34197)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/graphql/schema/type/cloudProvider/QLRancherCloudProvider.java` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/34197#-N4Te_ZHCvrC5nYVhLq8:-N4Te_ZIANQZjovonMyW:b2soagk) ([raw file](https://github.com/harness/harness-core/blob/3a5f2c8c5c8827e6b4f2fff180a5e6c64f89f155/400-rest/src/main/java/software/wings/graphql/schema/type/cloudProvider/QLRancherCloudProvider.java#L13)):*
> ```Java
> import io.harness.annotations.dev.TargetModule;
> import io.harness.ccm.health.CEHealthStatus;
> ```

Please remove this file from the PR.

**Comment by mohitg0795** [comment]
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/ScmConnector.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/34197#-N4Teo6uDqY3TjwXvsuf:-N4Teo6uDqY3TjwXvsug:bfnjg0g) ([raw file](https://github.com/harness/harness-core/blob/3a5f2c8c5c8827e6b4f2fff180a5e6c64f89f155/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/ScmConnector.java#L43)):*
> ```Java
>   @JsonIgnore void setGitConnectionUrl(String url);
> 
>   String getGitConnectionUrl();
> ```

Lets add some comments here, eg: It fetches already set git connection url etc. Just to add some explicit clarity.

**Comment by mohitg0795** [comment]
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java` line 123 at r2](https://reviewable.io/reviews/harness/harness-core/34197#-N4Tey-K4k7Sc5MyrH6x:-N4Tey-K4k7Sc5MyrH6y:b97vihg) ([raw file](https://github.com/harness/harness-core/blob/3a5f2c8c5c8827e6b4f2fff180a5e6c64f89f155/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L123)):*
> ```Java
>   @Override
>   public String getGitConnectionUrl(GitRepositoryDTO gitRepositoryDTO) {
>     final String azure_repo_name_separator = "/_git/";
> ```

Lets create a class level constant for it.

**Comment by mohitg0795** [comment]
*[`960-continuous-features/src/main/java/io/harness/cf/CfClientModule.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/34197#-N4Tf5tO4T-YqzmzmlWE:-N4Tf5tO4T-YqzmzmlWF:bnv0dag) ([raw file](https://github.com/harness/harness-core/blob/3a5f2c8c5c8827e6b4f2fff180a5e6c64f89f155/960-continuous-features/src/main/java/io/harness/cf/CfClientModule.java#L10)):*
> ```Java
> package io.harness.cf;
> 
> import static io.harness.data.structure.EmptyPredicate.isEmpty;
> ```

why is this file in the PR? Lets remove this if redundant.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34197)* status: 14 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/graphql/schema/type/cloudProvider/QLRancherCloudProvider.java` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/34197#-N4Te_ZHCvrC5nYVhLq8:-N4WAUVQECuJ_77JS7a7:bl0hnkf) ([raw file](https://github.com/harness/harness-core/blob/3a5f2c8c5c8827e6b4f2fff180a5e6c64f89f155/400-rest/src/main/java/software/wings/graphql/schema/type/cloudProvider/QLRancherCloudProvider.java#L13)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Please remove this file from the PR.
</blockquote></details>

Its due to clang-format
___
*[`940-feature-flag/src/main/java/io/harness/ff/CfMigrationService.java` line 4 at r2](https://reviewable.io/reviews/harness/harness-core/34197#-N4Tee5c2W_6jpUKtrqw:-N4WAX8xBWCMPJ2bP39-:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/3a5f2c8c5c8827e6b4f2fff180a5e6c64f89f155/940-feature-flag/src/main/java/io/harness/ff/CfMigrationService.java#L4)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why is this file in the PR. Lets remove this as well.
</blockquote></details>

same
___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/ScmConnector.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/34197#-N4Teo6uDqY3TjwXvsuf:-N4WAYGu5gPFGEnBL8KV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3a5f2c8c5c8827e6b4f2fff180a5e6c64f89f155/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/ScmConnector.java#L43)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets add some comments here, eg: It fetches already set git connection url etc. Just to add some explicit clarity.
</blockquote></details>

Done.
___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java` line 123 at r2](https://reviewable.io/reviews/harness/harness-core/34197#-N4Tey-K4k7Sc5MyrH6x:-N4WAYi88Z2RXZOKW9Au:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3a5f2c8c5c8827e6b4f2fff180a5e6c64f89f155/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L123)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets create a class level constant for it.
</blockquote></details>

Done.
___
*[`960-continuous-features/src/main/java/io/harness/cf/CfClientModule.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/34197#-N4Tf5tO4T-YqzmzmlWE:-N4WAZIM6Iku1wAKBa54:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/3a5f2c8c5c8827e6b4f2fff180a5e6c64f89f155/960-continuous-features/src/main/java/io/harness/cf/CfClientModule.java#L10)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is this file in the PR? Lets remove this if redundant.
</blockquote></details>

same as above

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 11 files at r1, 10 of 12 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34197#-:-N4WeEKZ0zNlZlOA6qft:bnfp4nl)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by abhinav-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34197)* status: 16 file(s) to review.

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 4 of 12 files at r2, 1 of 2 files at r3, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34197)* status: 9 file(s) to review. 1 change requests. 

___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java` line 135 at r4](https://reviewable.io/reviews/harness/harness-core/34197#-N4WpN9q99SYDZKVu_GK:-N4WpN9r498am1XYnocQ:bf6ye22) ([raw file](https://github.com/harness/harness-core/blob/b76f262d41c2498a2ccc2dc370719356eb3bb87c/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L135)):*
> ```Java
>     }
>     return FilePathUtils.addEndingSlashIfMissing(getUrl()) + gitRepositoryDTO.getProjectName()
>         + azure_repo_name_separator + gitRepositoryDTO.getName();
> ```

_git also comes in between right ?

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 11 files at r1, 5 of 12 files at r2, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34197)* status: 1 file(s) to review.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34197#-:-N4WrZG970NqSN_4dOws:bnfp4nl)* status: 1 file(s) to review.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34197#-:-N4WrpTRCjOFuwZg0nKq:bnfp4nl)* status: 1 file(s) to review.

**Review by bhavya181 — COMMENTED** [review]
> Reviewed 2 of 11 files at r1, 10 of 12 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34197)* status: 1 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34197)* status: 1 file(s) to review.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34197)* status: :shipit: complete! ✓

**Pull request merged**
