### PR TITLE
feat: [SRM-13076]: sending a list of monitoredServiceDetails in slo detail api

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40306)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40306)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/resources/ChangeEventResource.java` line 149 at r3](https://reviewable.io/reviews/harness/harness-core/40306#-NH7jzbq2XQB-JQlt1uh:-NH7jzbrDsE1hFzqJzqj:b-5gxjkw) ([raw file](https://github.com/harness/harness-core/blob/22cf28eb48044fd7201a9952fe3d3690f151c811/300-cv-nextgen/src/main/java/io/harness/cvng/core/resources/ChangeEventResource.java#L149)):*
> ```Java
>   public RestResponse<ChangeSummaryDTO>
>   getSummary(@NotNull @BeanParam ProjectParams projectParams,
>       @QueryParam("monitoredServiceIdentifiers") @NonNull List<String> monitoredServiceIdentifiers,
> ```

We are not suppose to remove the exiting filters. it will break the backward compatibility
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/ChangeEventService.java` line 50 at r3](https://reviewable.io/reviews/harness/harness-core/40306#-NH7k7btD00xfUU-aFnp:-NH7k7bu4GXJmzfii_i2:b-njb5wb) ([raw file](https://github.com/harness/harness-core/blob/22cf28eb48044fd7201a9952fe3d3690f151c811/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/ChangeEventService.java#L50)):*
> ```Java
>       List<ChangeSourceType> changeSourceTypes, Instant startTime, Instant endTime);
> 
>   ChangeSummaryDTO getChangeSummary(ProjectParams projectParams, List<String> monitoredServiceIdentifiers,
> ```

Add a new field monitoredServiceIdentifiers
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODashboardWidget.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/40306#-NH7kiZR31x4ispdenCx:-NH7kiZR31x4ispdenCy:bjwhbez) ([raw file](https://github.com/harness/harness-core/blob/22cf28eb48044fd7201a9952fe3d3690f151c811/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODashboardWidget.java#L72)):*
> ```Java
>   @Value
>   @Builder
>   public static class MonitoredServiceDetails {
> ```

use MonitoredServiceDetail
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 219 at r3](https://reviewable.io/reviews/harness/harness-core/40306#-NH7kMmLAMalyCv_yCWt:-NH7kMmLAMalyCv_yCWu:b79n1af) ([raw file](https://github.com/harness/harness-core/blob/22cf28eb48044fd7201a9952fe3d3690f151c811/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L219)):*
> ```Java
>           serviceLevelIndicator.getSliMissingDataType(), serviceLevelIndicator.getVersion(), filter);
> 
>       MonitoredServiceDetails msDetails =
> ```

use complete variable name monitoredServiceDetail

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40306)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODashboardWidget.java` line 74 at r5](https://reviewable.io/reviews/harness/harness-core/40306#-NHOQp3E0GS28J2pYmDi:-NHOQp3FEVCKdV4Hnho-:b-97dz9e) ([raw file](https://github.com/harness/harness-core/blob/51ac53d4245a98c7c9c124ab82ec0c1c3de6ae28/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODashboardWidget.java#L74)):*
> ```Java
>         .isCalculatingSLI(sloGraphData.isCalculatingSLI)
>         .errorBudgetRemaining(sloGraphData.getErrorBudgetRemaining())
>         .errorBudgetRemainingPercentage(sloGraphData.getErrorBudgetRemainingPercentage())
> ```

we still need to send monitoredServiceDetail right?



_Code quote:_
```Java
        .errorBudgetRemaining(sloGraphData.getErrorBudgetRemaining())
        .errorBudgetRemainingPercentage(sloGraphData.getErrorBudgetRemainingPercentage())
```

**Review by deepak-harness — APPROVED** [review]
> Reviewed 6 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40306)* status: :shipit: complete! ✓

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40306#-:-NHPEYI4-qC-eDDkz0sM:bnfp4nl)* status: :shipit: complete! ✓

**Review by Varsha-lalwani — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40306)* status: :shipit: complete! ✓

**Pull request merged**
