### PR TITLE
fix: [PL-32092]: Added migration to re-process roleassignment for loc…

### PR DESCRIPTION
**Pull request by meenakshi-harness**
1. This migration is to re-process all role-assignments of customer Localiza.
2. It also reprocess usergroup update in batch of 1000 users.
3. Tested locally by creating data and verifying before and after acls created.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45685)

### CODE REVIEW

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45685)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CreateACLsFromRoleAssignmentsMigration.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/45685#-NRYWKJo74n_TMmGiEnQ:-NRYWKJo74n_TMmGiEnR:b-w6akff) ([raw file](https://github.com/harness/harness-core/blob/bf255f531a142344711a99906d38b6f9906e4799/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CreateACLsFromRoleAssignmentsMigration.java#L68)):*
> ```Java
>   private long upsertACLs(RoleAssignmentDBO roleAssignment) {
>     aclRepository.deleteByRoleAssignmentId(roleAssignment.getId());
>     if (roleAssignment.getPrincipalType() == PrincipalType.USER_GROUP) {
> ```

We have skipped all role assignment for the account so we need to reprocess all the role assignments not just of User Group.

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45685)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CreateACLsFromRoleAssignmentsMigration.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/45685#-NRYWKJo74n_TMmGiEnQ:-NRbcKDOBdUO1f7M866z:b-2c1xxk) ([raw file](https://github.com/harness/harness-core/blob/bf255f531a142344711a99906d38b6f9906e4799/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CreateACLsFromRoleAssignmentsMigration.java#L68)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

We have skipped all role assignment for the account so we need to reprocess all the role assignments not just of User Group.
</blockquote></details>

else block will take care of them.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45685)* status: 3 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CreateACLsFromRoleAssignmentsMigration.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/45685#-NRfIe3JAaiifolBy0nL:-NRfIe3JAaiifolBy0nM:b2z31ky) ([raw file](https://github.com/harness/harness-core/blob/a0162906f2e0acc6f5a5ce8a46fd2fac15d7c1c8/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CreateACLsFromRoleAssignmentsMigration.java#L42)):*
> ```Java
> @Singleton
> @OwnedBy(HarnessTeam.PL)
> public class CreateACLsFromRoleAssignmentsMigration implements NGMigration {
> ```

Did we remove filter code for this account from change consumers?

Also, this migration was done earlier also. Is there a change from that or this is just a copy of that migration?
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CreateACLsFromRoleAssignmentsMigration.java` line 68 at r3](https://reviewable.io/reviews/harness/harness-core/45685#-NRfJyQH2WH5FBZhXHGI:-NRfJyQH2WH5FBZhXHGJ:behf6r3) ([raw file](https://github.com/harness/harness-core/blob/a0162906f2e0acc6f5a5ce8a46fd2fac15d7c1c8/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CreateACLsFromRoleAssignmentsMigration.java#L68)):*
> ```Java
>   }
> 
>   private long upsertACLs(RoleAssignmentDBO roleAssignment) {
> ```

Can we not just call RoleAssignmentChangeConsumerImpl.consumeCreateEvent()?

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45685)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CreateACLsFromRoleAssignmentsMigration.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/45685#-NRfIe3JAaiifolBy0nL:-NRgkp3Q9MlPiM4neiDj:blynqdm) ([raw file](https://github.com/harness/harness-core/blob/a0162906f2e0acc6f5a5ce8a46fd2fac15d7c1c8/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CreateACLsFromRoleAssignmentsMigration.java#L42)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Did we remove filter code for this account from change consumers?

Also, this migration was done earlier also. Is there a change from that or this is just a copy of that migration?
</blockquote></details>

1. We are removing that from 783xx ( the filter changes were hotfixed only in this version).
2. We have changed how we are processing user group roleassignments to tackle 24k user updates.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CreateACLsFromRoleAssignmentsMigration.java` line 68 at r3](https://reviewable.io/reviews/harness/harness-core/45685#-NRfJyQH2WH5FBZhXHGI:-NRglA871M-glOBBhSwp:bthi181) ([raw file](https://github.com/harness/harness-core/blob/a0162906f2e0acc6f5a5ce8a46fd2fac15d7c1c8/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CreateACLsFromRoleAssignmentsMigration.java#L68)):*
> . We have changed how we are processing user group roleassignments to tackle 24k user updates.

**Comment by meenakshi-harness** [comment]
Closing this as this needs to be merge in another release branch now https://github.com/harness/harness-core/pull/45774

**Pull request closed without merging**
