### PR TITLE
feat:[Pl-25315]: Introduced new Account Basic Role Assignment for new users, enabled through Feature Flag

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
Introduced new managed Role Assignment named Account Basic  for new users, enabled through Feature Flag.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33942)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 551 at r1](https://reviewable.io/reviews/harness/harness-core/33942#-N3oB0Ly0ZajlwBuOoJf:-N3oB0Ly0ZajlwBuOoJg:bf1z9ev) ([raw file](https://github.com/harness/harness-core/blob/64dbf610a64cb189c8755e7d35f2183139406071/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L551)):*
> ```Java
>       addUserToParentScope(userId, scope, source, true);
>     }
>     else
> ```

I guess formatter didn't run on this code, the code should be formatted better. Please check how if-else statement is written in method "getDefaultManagedRoleIdentifier" method.

**Comment by mohitg0795** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 547 at r1](https://reviewable.io/reviews/harness/harness-core/33942#-N3oBIRU-920TkRM8cnQ:-N3oBIRU-920TkRM8cnR:bflv80u) ([raw file](https://github.com/harness/harness-core/blob/64dbf610a64cb189c8755e7d35f2183139406071/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L547)):*
> ```Java
>       UserMembershipUpdateSource source) {
>     ensureUserMetadata(userId);
>     if (ngFeatureFlagHelperService.isEnabled(scope.getAccountIdentifier(), FeatureName.ACCOUNT_BASIC_ROLE)) {
> ```

what if this HTTP call fails and throws runtime exception? Is it fine that it goes to upper layers or should we have a default case handling or should we catch it here and do better handling?

**Comment by mohitg0795** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 674 at r1](https://reviewable.io/reviews/harness/harness-core/33942#-N3oBSg7EbcrN0pt81Da:-N3oBSg7EbcrN0pt81Db:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/64dbf610a64cb189c8755e7d35f2183139406071/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L674)):*
> ```Java
>         addUserToScopeInternal(userId, source, accountScope, ACCOUNT_BASIC);
>       }
>       else
> ```

same as above

**Comment by Jimit09Gandhi** [comment]
trigger messagecheck

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33942#-:-N3qgb5kC21cwSSVhTY7:bnfp4nl)* status: :shipit: complete! ✓

**Review by reetika04 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33942)* status: :shipit: complete! ✓

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33942)* status: :shipit: complete! ✓

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 558 at r2](https://reviewable.io/reviews/harness/harness-core/33942#-N3qqNNC7l49-aTQ4Zp_:-N3qpg0P9PKH9UaWXYox:b-capqg1) ([raw file](https://github.com/harness/harness-core/blob/38ec29d96936cbadd19ac0b02f8d2cf3d94cabc7/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L558)):*
> ```Java
>   }
> 
>   private String getDefaultManagedRoleIdentifier(Scope scope) {
> ```

This method is not required. We can take a boolean argument in getDefaultRoleIdentifier method
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 657 at r2](https://reviewable.io/reviews/harness/harness-core/33942#-N3qqha4EOtEleOsbAV7:-N3qp0Ei9nnFu59xs7j-:bpdrjma) ([raw file](https://github.com/harness/harness-core/blob/38ec29d96936cbadd19ac0b02f8d2cf3d94cabc7/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L657)):*
> ```Java
>   }
> 
>   private void addUserToParentScope(String userId, Scope scope, UserMembershipUpdateSource source, boolean accountBasicRoleFeatureFlag) {
> ```

Rename to isAccountBasicFeatureFlagEnabled



_Code quote:_
```Java
 ensureUserMetadata(userId);
```

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33942)* status: :shipit: complete! ✓

___
*[`123-ng-core-user/src/main/java/io/harness/utils/NGFeatureFlagHelperService.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/33942#-N3qrPhnA9-dioO4XH_g:-N3qrPhnA9-dioO4XH_h:b-q21imq) ([raw file](https://github.com/harness/harness-core/blob/38ec29d96936cbadd19ac0b02f8d2cf3d94cabc7/123-ng-core-user/src/main/java/io/harness/utils/NGFeatureFlagHelperService.java#L20)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.PL)
> public class NGFeatureFlagHelperService {
> ```

Why this new class? Can we not just use this?

RestClientUtils.getResponse(accountClient.isFeatureFlagEnabled(featureName.name(), accountId))



_Code quote:_
```Java
accountClient.isFeatureFlagEnabled
```

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33942)* status: 1 change requests. 1. unresolved discussions. 

___
*[`123-ng-core-user/src/main/java/io/harness/utils/NGFeatureFlagHelperService.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/33942#-N3qrPhnA9-dioO4XH_g:-N3sdp_Z0_HwOQElq8I-:bjgkr4) ([raw file](https://github.com/harness/harness-core/blob/38ec29d96936cbadd19ac0b02f8d2cf3d94cabc7/123-ng-core-user/src/main/java/io/harness/utils/NGFeatureFlagHelperService.java#L20)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this new class? Can we not just use this?

RestClientUtils.getResponse(accountClient.isFeatureFlagEnabled(featureName.name(), accountId))
</blockquote></details>

This call uses Retry policy, which will retry for defined no of times in case of failure.

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33942)* status: 3 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 547 at r1](https://reviewable.io/reviews/harness/harness-core/33942#-N3oBIRU-920TkRM8cnQ:-N3tZPpeAw-MY0tn7e4O:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/64dbf610a64cb189c8755e7d35f2183139406071/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L547)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if this HTTP call fails and throws runtime exception? Is it fine that it goes to upper layers or should we have a default case handling or should we catch it here and do better handling?
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 551 at r1](https://reviewable.io/reviews/harness/harness-core/33942#-N3oB0Ly0ZajlwBuOoJf:-N3tZPaJBl_K4mX_psQk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/64dbf610a64cb189c8755e7d35f2183139406071/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L551)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I guess formatter didn't run on this code, the code should be formatted better. Please check how if-else statement is written in method "getDefaultManagedRoleIdentifier" method.
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 674 at r1](https://reviewable.io/reviews/harness/harness-core/33942#-N3oBSg7EbcrN0pt81Da:-N3tZR_m6SnN2RxmjRKU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/64dbf610a64cb189c8755e7d35f2183139406071/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L674)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 558 at r2](https://reviewable.io/reviews/harness/harness-core/33942#-N3qqNNC7l49-aTQ4Zp_:-N3tZOHw1zZUPSBMKWoW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/38ec29d96936cbadd19ac0b02f8d2cf3d94cabc7/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L558)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This method is not required. We can take a boolean argument in getDefaultRoleIdentifier method
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 657 at r2](https://reviewable.io/reviews/harness/harness-core/33942#-N3qqha4EOtEleOsbAV7:-N3tZMRG71unlIHikOcX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/38ec29d96936cbadd19ac0b02f8d2cf3d94cabc7/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L657)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Rename to isAccountBasicFeatureFlagEnabled
</blockquote></details>

Done.

**Comment by Jimit09Gandhi** [comment]
trigger ti2

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33942#-:-N3thWHY6MqPJNjj0ueR:bnfp4nl)* status: 3. unresolved discussions.

**Review by Jimit09Gandhi — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33942)* status: 3. unresolved discussions.

**Review by reetika04 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33942)* status: 3. unresolved discussions.

**Review by reetika04 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33942#-:-N3tn8Jj8VvuxPwWFV4T:bnfp4nl)* status: 3. unresolved discussions.

**Review by reetika04 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33942)* status: 3. unresolved discussions.

**Review by naman-goenka — APPROVED** [review]

**Review by manish-manchanda — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33942)* status: 3. unresolved discussions.

**Comment by mohitg0795** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 547 at r1](https://reviewable.io/reviews/harness/harness-core/33942#-N3oBIRU-920TkRM8cnQ:-N3tsaGkDiUEQczAL6dl:b-z1y85z) ([raw file](https://github.com/harness/harness-core/blob/64dbf610a64cb189c8755e7d35f2183139406071/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L547)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Comment not acked, will check offline. Approving for now as its required for branch cut.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33942#-:-N3tsi8LCQKop4K_NTXD:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
