### PR TITLE
[feat]: [CDS-79241] Variables auto-suggestions for custom stage environment

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes
Added support for auto-suggestion variables for custom stage environment & infrastructure

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53115)

### CODE REVIEW

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger ut1

**Comment by lovish1999** [comment]
trigger ut7

**Comment by lovish1999** [comment]
trigger ut8

**Comment by lovish1999** [comment]
trigger ut9

**Review by tchaurasiya — DISMISSED** [review]

**Comment by lovish1999** [comment]
trigger ut9

**Comment by lovish1999** [comment]
trigger ut1

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/CustomStageVariableCreator.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/53115#-NevdViu0zFWgspblwaY:-NevdViu0zFWgspblwaZ:bacbcd7) ([raw file](https://github.com/harness/harness-core/blob/d31a5529b655797830706d862a085597c61a1df9/125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/CustomStageVariableCreator.java#L104)):*
> ```Java
>               .build());
>     }
>     return responseMap;
> ```

We should re-use 
```
LinkedHashMap<Object, Object\> finalMap \= new LinkedHashMap<>();  
LinkedHashMap<String, VariableCreationResponse\> variablesForChildrenNodes \= createVariablesForChildrenNodes(ctx, ctx.getCurrentField());  
finalMap.putAll(variablesForChildrenNodes);  
LinkedHashMap<String, VariableCreationResponse\> responseMap \=  
createVariablesForChildrenNodesPipelineV2Yaml(ctx, customStageNode);  
finalMap.putAll(responseMap);
```

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/StageVariableCreatorHelper.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/53115#-NevdgQu2csct6Esl0lG:-NevdgQu2csct6Esl0lH:b-4807sa) ([raw file](https://github.com/harness/harness-core/blob/d31a5529b655797830706d862a085597c61a1df9/125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/StageVariableCreatorHelper.java#L65)):*
> ```Java
> @CodePulse(module = ProductModule.CDS, unitCoverageRequired = true,
>     components = {HarnessModuleComponent.CDS_SERVICE_ENVIRONMENT, HarnessModuleComponent.CDS_PIPELINE})
> public class StageVariableCreatorHelper {
> ```

should be singleton

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53115)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by lovish1999** [comment]
trigger uts

**Review by tchaurasiya — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53115)* status: 6 file(s) to review.

**Comment by yogesh-chauhan** [comment]
trigger review

**Pull request merged**
