### PR TITLE
feat: [SRM-12420]: Added message parsing for DSL exceptions

### PR DESCRIPTION
**Pull request by arpit-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39036)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39036)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/cvng/CVNGDataCollectionDelegateServiceImpl.java` line 131 at r2](https://reviewable.io/reviews/harness/harness-core/39036#-NEu3nT--EvDP6fFXfmJ:-NEu3nT--EvDP6fFXfmK:b-azi2fw) ([raw file](https://github.com/harness/harness-core/blob/60a843d2aebde74d81d4a82d186c6aa9dd091e47/930-delegate-tasks/src/main/java/io/harness/cvng/CVNGDataCollectionDelegateServiceImpl.java#L131)):*
> ```Java
>         "io.harness.datacollection.exception.DataCollectionRuntimeException",
>         "io.harness.datacollection.exception.RateLimitExceededException"};
>     for (String exceptionMsg : dslExceptionMsgs) {
> ```

please return if length of messageParts is not 2.
Or even better just do replace exceptionMsg from message.

**Comment by arpit-harness** [comment]
trigger pmd

**Review by deepak-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39036)* status: :shipit: complete! ✓

**Comment by arpit-harness** [comment]
trigger buildnum

**Pull request merged**
