### PR TITLE
fix: [PL-26028]: fix error message

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
fix error message when scm svc is unable to instantiate inside delegates.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35647)

### CODE REVIEW

**Review by adivishy1 — APPROVED** [review]

**Comment by mohitg0795** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/scm/ScmDelegateClientImpl.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/35647#-N7tXDxwD6k4BGk_MU0j:-N7tXDxwD6k4BGk_MU0k:bcuo3eg) ([raw file](https://github.com/harness/harness-core/blob/da0a72450f7a6475bd5d9e8690ebf346fc3ab6ba/930-delegate-tasks/src/main/java/io/harness/delegate/task/scm/ScmDelegateClientImpl.java#L90)):*
> ```Java
>     } catch (Exception e) {
>       log.error(
>           "The delegate encountered internal error and was unable to perform the operation. Manager could not be created",
> ```

can we just make it "SCM Manager" to add more clarity in the log. Rest looks good.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35647)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by adivishy1 — APPROVED** [review]

**Review by adivishy1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35647)* status: 1 file(s) to review.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35647)* status: :shipit: complete! ✓

**Pull request merged**
