### PR TITLE
techdebt: [PIE-7242]: add callback to handle debezium errors

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41923)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger codebasehash

**Comment by sahilhindwani-harness** [comment]
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/41923#-NKNPQo4-5c_uuC1fw0f:-NKNPQo52XYGsboYRidd:b-9a3nuc) ([raw file](https://github.com/harness/harness-core/blob/f88caa460da6325613c0fd61a612cd8b1ceb1fe9/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java#L82)):*
> ```Java
>             debeziumEngine.close();
>             TimeUnit.SECONDS.sleep(10);
>           }
> ```

As discussed, move to different function and create DebeziumService and DebeziumServiceImpl to do any changes to debeziumEngine.



_Code quote:_
```Java
          if (debeziumEngine != null) {
            log.info("Closing Debezium engine for collection {}", changeConsumer.getCollection());
            debeziumEngine.close();
            TimeUnit.SECONDS.sleep(10);
          }
```

**Comment by sahilhindwani-harness** [comment]
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java` line 88 at r3](https://reviewable.io/reviews/harness/harness-core/41923#-NKNP_TT8g7j5LLM7KTU:-NKNP_TT8g7j5LLM7KTV:bjt60o3) ([raw file](https://github.com/harness/harness-core/blob/f88caa460da6325613c0fd61a612cd8b1ceb1fe9/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java#L88)):*
> ```Java
>           log.warn("Interrupted while waiting for debezium engine to close", e);
>         } catch (Exception e) {
>           log.error("Failed to close debezium engine due to unexpected exception", e);
> ```

Catch only exception and log the full stack trace.



_Code quote:_
```Java
        } catch (IOException e) {
          log.error("Failed to close debezium engine due to IO exception", e);
        } catch (InterruptedException e) {
          log.warn("Interrupted while waiting for debezium engine to close", e);
        } catch (Exception e) {
          log.error("Failed to close debezium engine due to unexpected exception", e);
```

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41923)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41923)* status: 10 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/41923#-NKNPQo4-5c_uuC1fw0f:-NKNzBGi6-t1k8CffZgX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f88caa460da6325613c0fd61a612cd8b1ceb1fe9/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java#L82)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

As discussed, move to different function and create DebeziumService and DebeziumServiceImpl to do any changes to debeziumEngine.
</blockquote></details>

Done.
___
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java` line 88 at r3](https://reviewable.io/reviews/harness/harness-core/41923#-NKNP_TT8g7j5LLM7KTU:-NKNz6bHCzjxrkTjvSCJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f88caa460da6325613c0fd61a612cd8b1ceb1fe9/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java#L88)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Catch only exception and log the full stack trace.
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41923)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 4 of 5 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41923)* status: :shipit: complete! ✓

**Pull request merged**
