### PR TITLE
fix: [PL-14710]:  Fix graph ql cryptic error

### PR DESCRIPTION
**Pull request by pbarapatre10**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30656)

### CODE REVIEW

**Review by nishantsaini20 — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30656)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/security/SecretManagerConfigServiceImpl.java, line 234 at r1](https://reviewable.io/reviews/harness/harness-core/30656#-MvY12SYD7xIR60xIA7d:-MvY12SZClG25XnIrRdP:bcp99g2) ([raw file](https://github.com/harness/harness-core/blob/3cb8a42c3c94777eb1b31bac49319beaae47ed04/400-rest/src/main/java/software/wings/service/impl/security/SecretManagerConfigServiceImpl.java#L234)):*
> ```Java
>     if (null == secretManagerConfig) {
>       String message = String.format("Secret manager with id %s for account %s can't be found.", kmsId, accountId);
>       log.warn(message);
> ```

Do we need to explicitly log it. Exception thrown in the next would also be getting logged.

**Comment by shashank-harness** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/security/SecretManagerConfigServiceImpl.java, line 234 at r1](https://reviewable.io/reviews/harness/harness-core/30656#-MvY12SYD7xIR60xIA7d:-MvY2cAD4ouvVlXWoJst:b-srxhbk) ([raw file](https://github.com/harness/harness-core/blob/3cb8a42c3c94777eb1b31bac49319beaae47ed04/400-rest/src/main/java/software/wings/service/impl/security/SecretManagerConfigServiceImpl.java#L234)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Do we need to explicitly log it. Exception thrown in the next would also be getting logged.
</blockquote></details>

@pbarapatre10 please respond to this

**Comment by pbarapatre10** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/security/SecretManagerConfigServiceImpl.java, line 234 at r1](https://reviewable.io/reviews/harness/harness-core/30656#-MvY12SYD7xIR60xIA7d:-MvY4hXW68zR7ism_gkG:b-y6x8ow) ([raw file](https://github.com/harness/harness-core/blob/3cb8a42c3c94777eb1b31bac49319beaae47ed04/400-rest/src/main/java/software/wings/service/impl/security/SecretManagerConfigServiceImpl.java#L234)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

@pbarapatre10 please respond to this
</blockquote></details>

Yes, we need to log it, as here we are just throwing the exception, & not printing trace else where. Thanks

**Comment by pbarapatre10** [comment]
trigger ti0

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30656)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/security/SecretManagerConfigServiceImpl.java, line 234 at r1](https://reviewable.io/reviews/harness/harness-core/30656#-MvY12SYD7xIR60xIA7d:-MvYg_0ICFzQl3nDdaWu:b7m1a9c) ([raw file](https://github.com/harness/harness-core/blob/3cb8a42c3c94777eb1b31bac49319beaae47ed04/400-rest/src/main/java/software/wings/service/impl/security/SecretManagerConfigServiceImpl.java#L234)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Yes, we need to log it, as here we are just throwing the exception, & not printing trace else where. Thanks
</blockquote></details>

This is removed so closing discussion.

**Pull request merged**
