### PR TITLE
feat: [CDP-17623]: Support terraform destroy -auto-approve in newer versions

### PR DESCRIPTION
**Pull request by abosii-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30268)

### CODE REVIEW

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30268)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by acasian-harness — DISMISSED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30268#-:-MuV6vQxA4N2n4aKq8Xq:bnfp4nl)* status: :shipit: complete! ✓

**Review by acasian-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30268#-:-MuuCA7VDhUZ0XxJ_lqq:bnfp4nl)* status: 1 of 2 approvals obtained.

**Review by tmacari-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30268)* status: :shipit: complete! ✓

**Pull request merged**
