### PR TITLE
feat: [CDS-48893]: HF-Added new API for listing nodes based on path

### PR DESCRIPTION
**Pull request by ivan-83**
## Describe your changes
Added the new endpoint to listing file store nodes (files/folders) on the path including first-level nodes and sub-nodes.
The new endpoint accepts identifiers based on scope, it takes accountIdentifier on account level,
accountIdentifier, orgIdentifier on org level, accountIdentifier, orgIdentifier, projectIdentifier on project level.
The path is a required parameter and should be a full node path.

The API endpoint is hidden from the Swagger doc and intended for internal use. There is no requirement to make it open for the time being.
The code is implemented based on recursion, the logic within the code searching for the nodes on each sub-path part but only listing nodes' metadata on the first level. It should not cause any performance issues. The file content is not included only nodes metadata.

GET >> https://fqdn/file-store/folder?accountIdentifier=<accountIndetifier>&path=<path>

The API request example on the local env,
https://localhost:7090/file-store/folder?accountIdentifier=kmpySmUISimoRrJL6NL73w&path=/folder4/file13

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42811)

### CODE REVIEW

**Comment by ivan-83** [comment]
trigger messagecheck

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42811)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by bojanmicovic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42811)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42811)* status: :shipit: complete! ✓

**Pull request merged**
