### PR TITLE
feat: [DEL-5767]: Adding delegate auth to DMS

### PR DESCRIPTION
**Pull request by AnupamIO**
Adding delegate auth to DMS. 

Testing:
- Tested DelegateAuth by creating a dummy resource.
- Authentication was done first by fetching token from db, then jwtCache was used.
- Checked that after expiry token is no longer valid and exception is thrown in auth.

Notes:
- DMS delegate auth doesn't contain accountKey based jwt decryption. No changes at manager delegate auth. 

- We will first verify if accountKey is getting used or not.
If used: We would need to find a way to access same, making rpc call isn't suited because it will add latency to entire delegate auth flow.
If not used: Will remove it from manager delegate auth flow as well.

- Refactored agent mtls code to 420-delegate, minor testing will be required for same to ensure it works fine.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43531)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 30 of 46 files at r1, 23 of 28 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43531)* status: 1 change requests. 0 of 1 approvals obtained. Waiting on team(s): del-team. 

___
*[`400-rest/src/main/java/io/harness/serializer/morphia/ManagerMorphiaRegistrar.java` line 870 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNq3TgF9sAanuuh3Jad:-NNq3TgF9sAanuuh3Jae:b-tbeo0g) ([raw file](https://github.com/harness/harness-core/blob/e3697641b8211ed8a86ff0052b82dd0c797be80b/400-rest/src/main/java/io/harness/serializer/morphia/ManagerMorphiaRegistrar.java#L870)):*
> ```Java
>     set.add(ARMInfrastructureProvisioner.class);
>     set.add(AccessRequest.class);
>     set.add(AgentMtlsEndpoint.class);
> ```

wouldn't this affect existing DB records? Or this mtls thing wasn't used at all
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java` line 77 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNq5sYU6tlu_eO1eOEf:-NNq5sYU6tlu_eO1eOEg:b-gt1hps) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java#L77)):*
> ```Java
>       protected void configure() {
>         bind(DelegateAuthService.class).to(DelegateAuthServiceImpl.class);
>         bind(DelegateMetricsService.class).to(DelegateMetricsServiceImpl.class);
> ```

this module list and bindings will just keep growing making this file unreadable. Create separate logical classes for all these bindings. E.g. AuthModule, you put authService, token and whatever is related to auth. Below you have mongo inline provider, again just create a class for it and put all DB bindings there. 
Note your DelegateServiceModule already uses some of these like MetricsModule, MongoModule etc.. Clean all these up and don't use anonymous classes 



_Code quote:_
```Java
    modules.add(new AbstractModule() {
      @Override
      protected void configure() {
        bind(DelegateAuthService.class).to(DelegateAuthServiceImpl.class);
        bind(DelegateMetricsService.class).to(DelegateMetricsServiceImpl.class);
        bind(DelegateTokenAuthenticator.class).to(DelegateServiceTokenAuthenticatorImpl.class);
      }
    });
```
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceAuthFilter.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNq5Sfi9uych7WwgLWT:-NNq5Sfj029L4Fg-1iub:b7y6eww) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceAuthFilter.java#L53)):*
> ```Java
>       validateDelegateAuth2Request(containerRequestContext);
>       return;
>     }
> ```

shouldn't this throw in case it's neither delgateAPI nor delegateAuth2API? I think if you dont throw means you accepted the auth which would be bad. 
The real implementation should be something like this



_Code snippet:_
```Java
if(delegateApi()) {
} else if (delegate2Api) {
} else {
  throw new WhateverException
}
```
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/configuration/BUILD.bazel` line 9 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNq6ao8-I2ny3y0NkNJ:-NNq6ao8-I2ny3y0NkNK:b2pkprm) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/419-delegate-service-app/src/main/java/io/harness/dms/configuration/BUILD.bazel#L9)):*
> ```Starlark
>     visibility = ["//visibility:public"],
>     deps = [
>         "//960-persistence:module",
> ```

this module is broken down, but not entirely. Is it possible to use package level targets. 



_Code quote:_
```Starlark
960-persistence:modul
```
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNqAJhoAXNYVXtrG0Qw:-NNqAJhoAXNYVXtrG0Qx:b-ogzcdz) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java#L26)):*
> ```Java
>   Duration HEARTBEAT_EXPIRY_TIME_FIVE_MINS = ofMinutes(5);
> 
>   String ACCOUNT_ID = "ACCOUNT_ID";
> ```

What is this used for
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateAuthServiceImpl.java` line 17 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNqBu0H8dgxKy2QD6fs:-NNqBu0H8dgxKy2QD6ft:bqwqhra) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/420-delegate-service/src/main/java/io/harness/service/impl/DelegateAuthServiceImpl.java#L17)):*
> ```Java
>       String agentMtlAuthority, boolean shouldSetTokenNameInGlobalContext) {
>     Base64.Decoder decoder = getUrlDecoder();
>     final String authHeader = new String(decoder.decode(tokenString.split("\\.")[0]));
> ```

Don't use split, that has terrible performance as it needs to compile regex pattern (in some cases), but also goes through entire input string and creates new object for every token.
Since you only care about the first token, I think your best bet would be substring. This doesn't go through entire input, no regex and only one output object (no garbage) 



_Code snippet:_
```Java
  tokenString.substring(0, tokenString.indexOf('.'));
```
___
*[`420-delegate-service/src/test/java/io/harness/service/DelegateAuthServiceTest.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNqDbANBs2tpXVUSVwI:-NNqDbANBs2tpXVUSVwJ:b-2fe9pt) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/420-delegate-service/src/test/java/io/harness/service/DelegateAuthServiceTest.java#L35)):*
> ```Java
>   @Category(UnitTests.class)
>   public void testValidateDelegateToken() {
>     initMocks(this);
> ```

Normally you don't need to init mocs manually. If you use `@RunWith(MockitoJunitRunner.class)` (or something like that), that does init mocs for you. There are (extremely rare) use cases where that doesn't work because the init order of some other libs, in that case you would add `@Before` method and do initMocs there (so they are inited before each test)
___
*[`420-delegate-service/src/test/java/io/harness/agent/utils/AgentMtlsVerifierTest.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNqDPg4D7FAyOSIU4eJ:-NNqDPg4D7FAyOSIU4eK:buonpk2) ([raw file](https://github.com/harness/harness-core/blob/e3697641b8211ed8a86ff0052b82dd0c797be80b/420-delegate-service/src/test/java/io/harness/agent/utils/AgentMtlsVerifierTest.java#L32)):*
> ```Java
> 
> @OwnedBy(DEL)
> public class AgentMtlsVerifierTest extends WingsBaseTest {
> ```

love this :heart_eyes:

**Review by xingchi-jin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43531)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java` line 77 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNq5sYU6tlu_eO1eOEf:-NNuBC6-5Qvx9g8roDQt:b32v57) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java#L77)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

this module list and bindings will just keep growing making this file unreadable. Create separate logical classes for all these bindings. E.g. AuthModule, you put authService, token and whatever is related to auth. Below you have mongo inline provider, again just create a class for it and put all DB bindings there. 
Note your DelegateServiceModule already uses some of these like MetricsModule, MongoModule etc.. Clean all these up and don't use anonymous classes 
</blockquote></details>

+1
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java` line 103 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNuBqGu9yla2e7T6350:-NNuBqGu9yla2e7T6351:b-c6ngey) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java#L103)):*
> ```Java
> 
>   private void registerResources(Environment environment, Injector injector) {
>     environment.jersey().register(injector.getInstance(DummyResource.class));
> ```

biz logics wise- what's the next step to migrate the resource, observers ? 
skeleton-sie - what's the next step to migrate health checks, exception handlers and converterFactories ? 
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceAuthFilter.java` line 77 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNuDq98E1N8ozeWS0ZL:-NNuDq98E1N8ozeWS0ZM:bz79ksm) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceAuthFilter.java#L77)):*
> ```Java
> 
>     String accountId = getRequestParamFromContext("accountId", pathParameters, queryParameters);
>     try (AccountLogContext ignore = new AccountLogContext(accountId, OVERRIDE_ERROR)) {
> ```

we can use DelegateLogContext
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceAuthFilter.java` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNuDfr27jhW0v7FhuVf:-NNuDfr27jhW0v7FhuVg:b-4kya80) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceAuthFilter.java#L98)):*
> ```Java
> 
>     String accountId = getRequestParamFromContext("accountId", pathParameters, queryParameters);
>     try (AccountLogContext ignore = new AccountLogContext(accountId, OVERRIDE_ERROR)) {
> ```

since it's now to delegate service, we can use DelegateLogContext 



_Code quote:_
```Java
ccountLogContext
```
___
*[`420-delegate-service/src/test/java/io/harness/agent/utils/AgentMtlsVerifierTest.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNqDPg4D7FAyOSIU4eJ:-NNuEDH71grl6Lir9ZMf:brtw9pe) ([raw file](https://github.com/harness/harness-core/blob/e3697641b8211ed8a86ff0052b82dd0c797be80b/420-delegate-service/src/test/java/io/harness/agent/utils/AgentMtlsVerifierTest.java#L32)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

love this :heart_eyes: 
</blockquote></details>

what is WingsBaseTest ? and how did you ( @mdmilic  ) type emoji in Reviewable ? 



_Code quote:_
```Java
WingsBaseTest 
```

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43531)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/test/java/io/harness/agent/utils/AgentMtlsVerifierTest.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNqDPg4D7FAyOSIU4eJ:-NNvCpKgCqMCM36EXGno:b-mzvxvw) ([raw file](https://github.com/harness/harness-core/blob/e3697641b8211ed8a86ff0052b82dd0c797be80b/420-delegate-service/src/test/java/io/harness/agent/utils/AgentMtlsVerifierTest.java#L32)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

what is WingsBaseTest ? and how did you ( @mdmilic  ) type emoji in Reviewable ? 
</blockquote></details>

WingsTestBase is present in 400-rest hence this test will fail with class not found :'(

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43531)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/test/java/io/harness/agent/utils/AgentMtlsVerifierTest.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNqDPg4D7FAyOSIU4eJ:-NNwHcCmEL-VkdYn8bU6:b-633b3h) ([raw file](https://github.com/harness/harness-core/blob/e3697641b8211ed8a86ff0052b82dd0c797be80b/420-delegate-service/src/test/java/io/harness/agent/utils/AgentMtlsVerifierTest.java#L32)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

WingsTestBase is present in 400-rest hence this test will fail with class not found :'(
</blockquote></details>

WingsBaseTest is the main culprit why our tests run 5h in total instead of 20min. It creates guice bindings for anything you might ever need in tests. Emojis are a trade secret :wink:

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43531)* status: Some of the checks are too old. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceAuthFilter.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNq5Sfi9uych7WwgLWT:-NO8U83N4CT-fFDannvt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceAuthFilter.java#L53)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

shouldn't this throw in case it's neither delgateAPI nor delegateAuth2API? I think if you dont throw means you accepted the auth which would be bad. 
The real implementation should be something like this
</blockquote></details>

Done.
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceAuthFilter.java` line 77 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNuDq98E1N8ozeWS0ZL:-NO8Vl_89LFOhH76YzMb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceAuthFilter.java#L77)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

we can use DelegateLogContext
</blockquote></details>

Done.
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceAuthFilter.java` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNuDfr27jhW0v7FhuVf:-NO8Vnky87Zm09zBITUj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceAuthFilter.java#L98)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

since it's now to delegate service, we can use DelegateLogContext 
</blockquote></details>

Done.
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNqAJhoAXNYVXtrG0Qw:-NO8Vw4Q-u-kylMvLXGb:b-xj28sj) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java#L26)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

What is this used for
</blockquote></details>

used in test cases. Ex: DelegateAuthServiceTest

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43531)* status: Some of the checks are too old. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java` line 77 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNq5sYU6tlu_eO1eOEf:-NO8qtaZ0ZpNrZbXsZsI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java#L77)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43531)* status: Some of the checks are too old. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/src/main/java/io/harness/dms/configuration/BUILD.bazel` line 9 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNq6ao8-I2ny3y0NkNJ:-NO8y1Tx7ZVT56aQD6Zb:b-hgtnth) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/419-delegate-service-app/src/main/java/io/harness/dms/configuration/BUILD.bazel#L9)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

this module is broken down, but not entirely. Is it possible to use package level targets. 
</blockquote></details>

I think it is not possible because 960 doesn't have package level target for cache and abstractMongoModule.
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateAuthServiceImpl.java` line 17 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNqBu0H8dgxKy2QD6fs:-NO8zDPQ5K8nTQDlZ8AP:b-afbuce) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/420-delegate-service/src/main/java/io/harness/service/impl/DelegateAuthServiceImpl.java#L17)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Don't use split, that has terrible performance as it needs to compile regex pattern (in some cases), but also goes through entire input string and creates new object for every token.
Since you only care about the first token, I think your best bet would be substring. This doesn't go through entire input, no regex and only one output object (no garbage) 
</blockquote></details>

well said, done.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43531)* status: Some of the checks are too old. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java` line 103 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNuBqGu9yla2e7T6350:-NO9ZdVp5DtelqkvAtL1:bd2u6bs) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java#L103)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

biz logics wise- what's the next step to migrate the resource, observers ? 
skeleton-sie - what's the next step to migrate health checks, exception handlers and converterFactories ? 
</blockquote></details>

- biz logic wise: we will migrate VersionInfoResource next to DMS. We will only move delegateAuth based apis because we don't have support for api-key authentication in dms.
- for health check and exception handlers, I'll include it with above resource change. 
___
*[`420-delegate-service/src/test/java/io/harness/service/DelegateAuthServiceTest.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNqDbANBs2tpXVUSVwI:-NO9LimKDClfpPDBkFXb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/420-delegate-service/src/test/java/io/harness/service/DelegateAuthServiceTest.java#L35)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Normally you don't need to init mocs manually. If you use `@RunWith(MockitoJunitRunner.class)` (or something like that), that does init mocs for you. There are (extremely rare) use cases where that doesn't work because the init order of some other libs, in that case you would add `@Before` method and do initMocs there (so they are inited before each test)
</blockquote></details>

Done.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43531)* status: 11 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/serializer/morphia/ManagerMorphiaRegistrar.java` line 870 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNq3TgF9sAanuuh3Jad:-NO9bV4SBchBlIm3Nb9P:br9aqse) ([raw file](https://github.com/harness/harness-core/blob/e3697641b8211ed8a86ff0052b82dd0c797be80b/400-rest/src/main/java/io/harness/serializer/morphia/ManagerMorphiaRegistrar.java#L870)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

wouldn't this affect existing DB records? Or this mtls thing wasn't used at all
</blockquote></details>

Added this AgentMtlsEndpoint.class to DelegateServiceMorphiaRegistrar, ManagerRegistrar adds this DelegateServiceMorphiaRegistrar as well. If you see any issue, please point.

**Review by mdmilic — APPROVED** [review]
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43531)* status: 3. unresolved discussions. 

___
*[`400-rest/src/main/java/io/harness/serializer/morphia/ManagerMorphiaRegistrar.java` line 870 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNq3TgF9sAanuuh3Jad:-NOA0a-xB-xcNGo6FMB5:b-2e1hi7) ([raw file](https://github.com/harness/harness-core/blob/e3697641b8211ed8a86ff0052b82dd0c797be80b/400-rest/src/main/java/io/harness/serializer/morphia/ManagerMorphiaRegistrar.java#L870)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

Added this AgentMtlsEndpoint.class to DelegateServiceMorphiaRegistrar, ManagerRegistrar adds this DelegateServiceMorphiaRegistrar as well. If you see any issue, please point.
</blockquote></details>

Nope that should be good
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/43531#-NNqAJhoAXNYVXtrG0Qw:-NOA0GYnAoZQyZGjrmOL:b-boj5co) ([raw file](https://github.com/harness/harness-core/blob/c16e591829f0d2543339e864dafbf81007a54730/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java#L26)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

used in test cases. Ex: DelegateAuthServiceTest
</blockquote></details>

resolving, but this is prod code, it should then probably be in some tests util class.

**Review by mdmilic — APPROVED** [review]
> Reviewed 22 of 24 files at r5, 2 of 2 files at r6, 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43531)* status: 3. unresolved discussions. 

___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/BUILD.bazel` line 56 at r8](https://reviewable.io/reviews/harness/harness-core/43531#-NOK3lfX-pWEZHgdXowC:-NOK3lfYEcFET5cAaePt:b-rglovw) ([raw file](https://github.com/harness/harness-core/blob/8fc8fc64114aebaa08d05451ccd084137de4827a/419-delegate-service-app/src/main/java/io/harness/dms/app/BUILD.bazel#L56)):*
> ```Starlark
>         "@maven//:javax_activation_activation",
>         "@maven//:javax_xml_bind_jaxb_api",
>         "//419-delegate-service-app/src/main/java/io/harness/dms/module",
> ```

This should probably be `//419-delegate-service-app/src/main/java/io/harness/dms/module:module`

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43531)* status: 3. unresolved discussions. 

___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/BUILD.bazel` line 56 at r8](https://reviewable.io/reviews/harness/harness-core/43531#-NOK3lfX-pWEZHgdXowC:-NOK5NcF6AMEfIGpZ5FU:boafu5k) ([raw file](https://github.com/harness/harness-core/blob/8fc8fc64114aebaa08d05451ccd084137de4827a/419-delegate-service-app/src/main/java/io/harness/dms/app/BUILD.bazel#L56)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This should probably be `//419-delegate-service-app/src/main/java/io/harness/dms/module:module`
</blockquote></details>

yes, it got changed by bazel buildifier, i checked this and DMS built fine.

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 19 of 46 files at r1, 12 of 28 files at r2, 3 of 7 files at r3, 2 of 11 files at r4, 22 of 24 files at r5, 2 of 2 files at r6, 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43531)* status: 1. unresolved discussions.

**Review by xingchi-jin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43531)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]

**Pull request merged**
