### PR TITLE
fix: [SRM-9971]: complete the analysis verificationJobInstance on verifica…

### PR DESCRIPTION
**Pull request by AbhijithHarness**
…tion job completion

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32048)

### CODE REVIEW

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32048)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java, line 285 at r1](https://reviewable.io/reviews/harness/harness-core/32048#-MzxbeXtCelOlc13S8gC:-MzxbeXtCelOlc13S8gD:b-bsgs2j) ([raw file](https://github.com/harness/harness-core/blob/6d19f561e45db5f39632e59d999c8125ed877435/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java#L285)):*
> ```Java
>       sliRecordService.delete(
>           serviceLevelIndicatorList.stream().map(ServiceLevelIndicator::getUuid).collect(Collectors.toList()));
>       orchestrationService.markCompleted(
> ```

I think we should do the deletion in a generic way. Similar to DeletedCVConfig or combine live monitoring and sli deletion in a single handler. 
This can happen in background.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java, line 723 at r1](https://reviewable.io/reviews/harness/harness-core/32048#-MzxcSFi2amCepgGL6R2:-MzxcSFi2amCepgGL6R3:b2mjvod) ([raw file](https://github.com/harness/harness-core/blob/6d19f561e45db5f39632e59d999c8125ed877435/300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java#L723)):*
> ```Java
>   }
> 
>   private void markAnalysisAsCompleted(String accountId, String verificationJobInstanceId) {
> ```

I think we have timeout also. We should make the status update common and add this logic in one place.
Is there a better way to enforce it?

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 9 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32048#-:-Mzy9CADCEfqqGeoyir3:bnfp4nl)* status: :shipit: complete! ✓

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java, line 233 at r3](https://reviewable.io/reviews/harness/harness-core/32048#-Mzy7pUp-ksnImz22oMt:-Mzy7pUp-ksnImz22oMu:b-6d9vl2) ([raw file](https://github.com/harness/harness-core/blob/5a504f4d031bf1d0dbd85b9c37f4560ac04a25b4/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java#L233)):*
> ```Java
>     }
>     if (analysisStateMachine == null) {
>       updateStatusOfOrchestrator(verificationTaskId, AnalysisStatus.WAITING);
> ```

nit: how hard is it to use a separate enum for AnalysisOrchestrator? Should we just do it in this PR?

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 8 files at r4, 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32048#-:-MzydaWK7GnXeF1SQMEH:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
