### PR TITLE
feat: [PIE-3853]: Implementation of strategy step in execution

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33551)

### CODE REVIEW

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33551)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33551)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/HarnessForConfigService.java` line 11 at r1](https://reviewable.io/reviews/harness/harness-core/33551#-N2ziHhs8LRpCkfdj73b:-N2ziHhs8LRpCkfdj73c:b-dkrm76) ([raw file](https://github.com/harness/harness-core/blob/6e8764de0355963e48e575923c6765510296838a/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/HarnessForConfigService.java#L11)):*
> ```Java
> import java.util.List;
> 
> public class HarnessForConfigService implements StrategyConfigService {
> ```

Can we rename it to HarnessForLoopConfigService?



_Code quote:_
```Java
HarnessForConfigService
```
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/MatrixConfigService.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/33551#-N2zirH03wi6UGJUClUx:-N2zirH03wi6UGJUClUy:bo6zxyv) ([raw file](https://github.com/harness/harness-core/blob/6e8764de0355963e48e575923c6765510296838a/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/MatrixConfigService.java#L49)):*
> ```Java
>   private void fetchCombinations(Map<String, String> currentCombination, Map<String, AxisConfig> axes,
>       List<Map<String, String>> combinations, List<ExcludeConfig> exclude, List<List<String>> matrixMetadata,
>       List<String> keys) {
> ```

Can this method tell what each field means?



_Code quote:_
```Java
  private void fetchCombinations(Map<String, String> currentCombination, Map<String, AxisConfig> axes,
      List<Map<String, String>> combinations, List<ExcludeConfig> exclude, List<List<String>> matrixMetadata,
      List<String> keys) {
```
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/MatrixConfigService.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/33551#-N2zjqTn6Mfhyt6rcblm:-N2zjqTn6Mfhyt6rcbln:b-dk02ty) ([raw file](https://github.com/harness/harness-core/blob/6e8764de0355963e48e575923c6765510296838a/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/MatrixConfigService.java#L66)):*
> ```Java
>       currentCombination.remove(key);
>     }
>     axes.put(key, axisValues);
> ```

I think it can be written more simply to denotate that you are calculating all possible combination with checking exclusions?

Just a suggestion would be


getAllCombinations(row = 0, finalCombinations,CurrentComb){
	
	if(row == axes.size() - 1){
		check if curremComb can be added to final Comb or not via exclude
	}


	for(col=0, col<axes.get(row).size(), col++){
		currentComb.add(axes.get(row, col));
		getAllCOmbinations(row+1, finalCombinations, CurrentComb);
	}


}

reason in current impl, we are adding lot of adding and removing keys, I think which can be avoided.

 



_Code quote:_
```Java
    if (axes.size() == 0) {
      if (!exclude.contains(ExcludeConfig.builder().exclude(currentCombination).build())) {
        combinations.add(new HashMap<>(currentCombination));
        matrixMetadata.add(keys);
      }
      return;
    }
    String key = axes.keySet().iterator().next();
    AxisConfig axisValues = axes.get(key);
    axes.remove(key);
    keys.add(key);
    for (String value : axisValues.getAxisValue().getValue()) {
      currentCombination.put(key, value);
      fetchCombinations(currentCombination, axes, combinations, exclude, matrixMetadata, keys);
      currentCombination.remove(key);
    }
    axes.put(key, axisValues);
```
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/StrategyStep.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/33551#-N2zie9w8MwWEtfZSsQX:-N2zie9w8MwWEtfZSsQY:b-51y6q3) ([raw file](https://github.com/harness/harness-core/blob/6e8764de0355963e48e575923c6765510296838a/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/StrategyStep.java#L43)):*
> ```Java
>     return ChildrenExecutableResponse.newBuilder()
>         .addChildren(
>             ChildrenExecutableResponse.Child.newBuilder().setChildNodeId(stepParameters.getChildNodeId()).build())
> ```

can we put this in switch case? if not then if else if?



_Code quote:_
```Java
    if (stepParameters.getStrategyConfig().getMatrixConfig() != null) {
      return ChildrenExecutableResponse.newBuilder()
          .addAllChildren(
              matrixConfigService.fetchChildren(stepParameters.getStrategyConfig(), stepParameters.getChildNodeId()))
          .build();
    }
    if (stepParameters.getStrategyConfig().getForConfig() != null) {
      return ChildrenExecutableResponse.newBuilder()
          .addAllChildren(harnessForConfigService.fetchChildren(
              stepParameters.getStrategyConfig(), stepParameters.getChildNodeId()))
          .build();
    }
    return ChildrenExecutableResponse.newBuilder()
        .addChildren(
            ChildrenExecutableResponse.Child.newBuilder().setChildNodeId(stepParameters.getChildNodeId()).build())
```

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/MatrixConfigService.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/33551#-N2zirH03wi6UGJUClUx:-N3-LjG41Z_gqltXwqhN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6e8764de0355963e48e575923c6765510296838a/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/MatrixConfigService.java#L49)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can this method tell what each field means?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/MatrixConfigService.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/33551#-N2zjqTn6Mfhyt6rcblm:-N3-Lkl2DUERByPqT4ni:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6e8764de0355963e48e575923c6765510296838a/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/MatrixConfigService.java#L66)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I think it can be written more simply to denotate that you are calculating all possible combination with checking exclusions?

Just a suggestion would be


getAllCombinations(row = 0, finalCombinations,CurrentComb){
	
	if(row == axes.size() - 1){
		check if curremComb can be added to final Comb or not via exclude
	}


	for(col=0, col<axes.get(row).size(), col++){
		currentComb.add(axes.get(row, col));
		getAllCOmbinations(row+1, finalCombinations, CurrentComb);
	}


}

reason in current impl, we are adding lot of adding and removing keys, I think which can be avoided.

 
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33551)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/MatrixConfigService.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/33551#-N3-UY4qA9DPYK5RPuSR:-N3-UY4qA9DPYK5RPuSS:b-4ynwoz) ([raw file](https://github.com/harness/harness-core/blob/972474f0b748f8b8c4d8d3eeaf30dabca1b2fa11/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/MatrixConfigService.java#L79)):*
> ```Java
>     AxisConfig axisValues = axes.get(key);
>     int i = 0;
>     for (String value : axisValues.getAxisValue().getValue()) {
> ```

why not make for with i index loop? just my opinion



_Code quote:_
```Java
for (String value : axisValues.getAxisValue().getValue())
```
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/MatrixConfigService.java` line 81 at r3](https://reviewable.io/reviews/harness/harness-core/33551#-N3-UdQE2xfZdxhVJneD:-N3-UdQE2xfZdxhVJneE:b7qftjn) ([raw file](https://github.com/harness/harness-core/blob/972474f0b748f8b8c4d8d3eeaf30dabca1b2fa11/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/MatrixConfigService.java#L81)):*
> ```Java
>     for (String value : axisValues.getAxisValue().getValue()) {
>       currentCombinationRef.put(key, value);
>       indexPath.add(i + "");
> ```

do you mean space or underscore



_Code quote:_
```Java
""
```
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/StrategyStep.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/33551#-N2zie9w8MwWEtfZSsQX:-N3-Uym63s-6CE0UCYJx:b-a3cval) ([raw file](https://github.com/harness/harness-core/blob/6e8764de0355963e48e575923c6765510296838a/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/StrategyStep.java#L43)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think it is else if only, are you suggesting to add else explicitly?
</blockquote></details>

yeah personal opionion only, but this is also okay
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/HarnessForConfigService.java` line 11 at r1](https://reviewable.io/reviews/harness/harness-core/33551#-N2ziHhs8LRpCkfdj73b:-N3-Se4N9J-Uk4OJbi4V:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6e8764de0355963e48e575923c6765510296838a/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/HarnessForConfigService.java#L11)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we rename it to HarnessForLoopConfigService?
</blockquote></details>

done

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33551)* status: 9 file(s) to review. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/MatrixConfigService.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/33551#-N3-UY4qA9DPYK5RPuSR:-N32oUYm3INeORZwULJB:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/972474f0b748f8b8c4d8d3eeaf30dabca1b2fa11/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/MatrixConfigService.java#L79)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why not make for with i index loop? just my opinion
</blockquote></details>

done
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/MatrixConfigService.java` line 81 at r3](https://reviewable.io/reviews/harness/harness-core/33551#-N3-UdQE2xfZdxhVJneD:-N32oTNI9PeunC2MAY72:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/972474f0b748f8b8c4d8d3eeaf30dabca1b2fa11/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/MatrixConfigService.java#L81)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

do you mean space or underscore
</blockquote></details>

done

**Review by arpit3107 — APPROVED** [review]
> Reviewed 5 of 10 files at r1, 4 of 6 files at r2, 1 of 1 files at r3, 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33551)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 6 files at r2, 1 of 1 files at r3, 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33551)* status: :shipit: complete! ✓

**Review by brijeshdhakar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33551)* status: :shipit: complete! ✓

**Pull request merged**
