### PR TITLE
feat: [CDS-77827]: add pipeline version in list pipeline api

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
add pipeline version in list pipeline api

Tests Done -
* Test both List API ( Open API & old pipeline list call with all possible values of 0,1, null )
For Old Pipelines where harnessVersion was not present we are setting this as 0 version

Sample Response :
```
{
    "status": "SUCCESS",
    "data": {
        "content": [
            {
                "name": "v1test",
                "identifier": "v1test",
                "tags": {},
                "version": 0,
                "numOfStages": 0,
                "createdAt": 1692956268747,
                "lastUpdatedAt": 1692956268747,
                "modules": [],
                "executionSummaryInfo": {
                    "numOfErrors": [],
                    "deployments": []
                },
                "recentExecutionsInfo": [],
                "filters": {},
                "stageNames": [],
                "entityValidityDetails": {
                    "valid": true,
                    "invalidYaml": null
                },
                "storeType": "INLINE",
                "isDraft": false,
                "yamlVersion": "1"
            },
            {
                "name": "test",
                "identifier": "test",
                "tags": {},
                "version": 0,
                "numOfStages": 0,
                "createdAt": 1692956237720,
                "lastUpdatedAt": 1692956237720,
                "modules": [],
                "executionSummaryInfo": {
                    "numOfErrors": [],
                    "deployments": []
                },
                "recentExecutionsInfo": [],
                "filters": {},
                "stageNames": [],
                "entityValidityDetails": {
                    "valid": true,
                    "invalidYaml": null
                },
                "storeType": "INLINE",
                "isDraft": false,
                "yamlVersion": "1"
            },
            {
                "name": "yrty",
                "identifier": "yrty",
                "tags": {},
                "version": 0,
                "numOfStages": 0,
                "createdAt": 1671538159938,
                "lastUpdatedAt": 1671538159938,
                "modules": [
                    "pms"
                ],
                "executionSummaryInfo": {
                    "numOfErrors": [],
                    "deployments": []
                },
                "recentExecutionsInfo": [],
                "filters": {
                    "pms": {}
                },
                "stageNames": [],
                "entityValidityDetails": {
                    "valid": true,
                    "invalidYaml": null
                },
                "storeType": "INLINE",
                "isDraft": false,
                "yamlVersion": "0"
            },
            {
                "name": "ytr",
                "identifier": "ytr",
                "tags": {},
                "version": 0,
                "numOfStages": 0,
                "createdAt": 1671526122870,
                "lastUpdatedAt": 1671526122870,
                "modules": [
                    "pms"
                ],
                "executionSummaryInfo": {
                    "numOfErrors": [],
                    "deployments": []
                },
                "recentExecutionsInfo": [],
                "filters": {
                    "pms": {}
                },
                "stageNames": [],
                "entityValidityDetails": {
                    "valid": true,
                    "invalidYaml": null
                },
                "storeType": "INLINE",
                "isDraft": false,
                "yamlVersion": "0"
            }
        ],
        "pageable": {
            "sort": {
                "sorted": true,
                "unsorted": false,
                "empty": false
            },
            "pageNumber": 0,
            "pageSize": 20,
            "offset": 0,
            "paged": true,
            "unpaged": false
        },
        "totalPages": 1,
        "totalElements": 4,
        "last": true,
        "numberOfElements": 4,
        "first": true,
        "sort": {
            "sorted": true,
            "unsorted": false,
            "empty": false
        },
        "size": 20,
        "number": 0,
        "empty": false
    },
    "metaData": null,
    "correlationId": "23ff35ad-3473-40d4-a17e-3d8748c37681"
}
``` 

Open Api Response 
```
[
    {
        "identifier": "v1test",
        "name": "v1test",
        "description": null,
        "tags": {},
        "created": 1692956268747,
        "updated": 1692956268747,
        "modules": [],
        "recent_execution_info": [],
        "store_type": "INLINE",
        "connector_ref": null,
        "valid": true,
        "git_details": null,
        "yaml_version": "1"
    },
    {
        "identifier": "test",
        "name": "test",
        "description": null,
        "tags": {},
        "created": 1692956237720,
        "updated": 1692956237720,
        "modules": [],
        "recent_execution_info": [],
        "store_type": "INLINE",
        "connector_ref": null,
        "valid": true,
        "git_details": null,
        "yaml_version": "1"
    },
    {
        "identifier": "yrty",
        "name": "yrty",
        "description": null,
        "tags": {},
        "created": 1671538159938,
        "updated": 1671538159938,
        "modules": [
            "pms"
        ],
        "recent_execution_info": [],
        "store_type": "INLINE",
        "connector_ref": null,
        "valid": true,
        "git_details": null,
        "yaml_version": "0"
    },
    {
        "identifier": "ytr",
        "name": "ytr",
        "description": null,
        "tags": {},
        "created": 1671526122870,
        "updated": 1671526122870,
        "modules": [
            "pms"
        ],
        "recent_execution_info": [],
        "store_type": "INLINE",
        "connector_ref": null,
        "valid": true,
        "git_details": null,
        "yaml_version": "0"
    }
]
``` 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52070)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by shalini-agr — APPROVED** [review]

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52070)* status: 6 file(s) to review.

**Review by mankrit-singh — APPROVED** [review]

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Review by mohitg0795 — APPROVED** [review]

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Pull request merged**
