### PR TITLE
fix: [CDS-37721]: added step level override for K8s Apply Step

### PR DESCRIPTION
**Pull request by achyuth-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33358)

### CODE REVIEW

**Review by GoelPratyush99 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33358)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java` line 398 at r2](https://reviewable.io/reviews/harness/harness-core/33358#-N2V4QUL5miy2H23gNbq:-N2V4QUL5miy2H23gNbr:b-sopjlg) ([raw file](https://github.com/harness/harness-core/blob/338dd9145fd15a2a30bc07779d4e4a1d640d947c/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L398)):*
> ```Java
>     List<String> valuesPaths = new ArrayList<>();
>     String folderPath = getParameterFieldValue(gitStoreConfig.getFolderPath());
>     valuesPaths.add(getValuesYamlGitFilePath(folderPath, VALUES_YAML_KEY));
> ```

Here. I had called populateGitFetchFilesConfigListWithValuesPaths twice as we always need to skip the exception if we are not able to fetch the default values.yaml file. In this case if we have values file defined in valuesPaths, we won't be able to ignore exception NoSuchFileFound for default values.yaml as valuesPaths.size() != 1. 



_Code quote:_
```Java
    valuesPaths.add(getValuesYamlGitFilePath(folderPath, VALUES_YAML_KEY));
    if (isNotEmpty(getParameterFieldValue(helmChartManifestOutcome.getValuesPaths()))) {
      valuesPaths.addAll(getParameterFieldValue(helmChartManifestOutcome.getValuesPaths()));
    }
    populateGitFetchFilesConfigListWithValuesPaths(gitFetchFilesConfigList, gitStoreConfig, manifestOutcome,
        connectorDTO, ambiance, identifier, valuesPaths.size() == 1, valuesPaths);
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 632 at r2](https://reviewable.io/reviews/harness/harness-core/33358#-N2V6sUe3167GdDzawmG:-N2V6sUe3167GdDzawmH:b-it8lqh) ([raw file](https://github.com/harness/harness-core/blob/338dd9145fd15a2a30bc07779d4e4a1d640d947c/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L632)):*
> ```Java
>     }
>     valuesPaths.add(0, getValuesYamlGitFilePath(folderPath, VALUES_YAML_KEY));
>     List<GitFetchFilesConfig> gitFetchFilesConfigList = new ArrayList<>();
> ```

Same here. We will throw exception NoSuchFileFound and fail our execution if we have values files defined in valuesPaths and we are unable to fetch the default values.yaml.



_Code quote:_
```Java
    if (ManifestType.K8Manifest.equals(k8sManifestOutcome.getType())) {
      K8sManifestOutcome manifestOutcome = (K8sManifestOutcome) k8sManifestOutcome;
      if (isNotEmpty(getParameterFieldValue(manifestOutcome.getValuesPaths()))) {
        valuesPaths.addAll(getParameterFieldValue(manifestOutcome.getValuesPaths()));
      }
      folderPath = getParameterFieldValue(gitStoreConfig.getPaths()).get(0);
    } else {
      HelmChartManifestOutcome manifestOutcome = (HelmChartManifestOutcome) k8sManifestOutcome;
      if (isNotEmpty(getParameterFieldValue(manifestOutcome.getValuesPaths()))) {
        valuesPaths.addAll(getParameterFieldValue(manifestOutcome.getValuesPaths()));
      }
      folderPath = getParameterFieldValue(gitStoreConfig.getFolderPath());
    }
    valuesPaths.add(0, getValuesYamlGitFilePath(folderPath, VALUES_YAML_KEY));
    List<GitFetchFilesConfig> gitFetchFilesConfigList = new ArrayList<>();
    populateGitFetchFilesConfigListWithValuesPaths(gitFetchFilesConfigList, gitStoreConfig, k8sManifestOutcome,
        connectorDTO, ambiance, identifier, valuesPaths.size() == 1, valuesPaths);
```

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33358)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java` line 398 at r2](https://reviewable.io/reviews/harness/harness-core/33358#-N2V4QUL5miy2H23gNbq:-N2VN56c5nvp_V0EA6Bj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/338dd9145fd15a2a30bc07779d4e4a1d640d947c/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L398)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Here. I had called populateGitFetchFilesConfigListWithValuesPaths twice as we always need to skip the exception if we are not able to fetch the default values.yaml file. In this case if we have values file defined in valuesPaths, we won't be able to ignore exception NoSuchFileFound for default values.yaml as valuesPaths.size() != 1. 
</blockquote></details>

Done.

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33358)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 632 at r2](https://reviewable.io/reviews/harness/harness-core/33358#-N2V6sUe3167GdDzawmG:-N2VN7ey9TsOyYNdKDFj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/338dd9145fd15a2a30bc07779d4e4a1d640d947c/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L632)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Same here. We will throw exception NoSuchFileFound and fail our execution if we have values files defined in valuesPaths and we are unable to fetch the default values.yaml.
</blockquote></details>

Done.

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33358)* status: :shipit: complete! ✓

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/GitFetchTaskNG.java` line 128 at r4](https://reviewable.io/reviews/harness/harness-core/33358#-N2VPaTD3V-v7n2I-Cwn:-N2VPaTD3V-v7n2I-Cwo:b-z6kk6a) ([raw file](https://github.com/harness/harness-core/blob/7142b2d7f252a45de1af21d84d1fad150a5bc552/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/GitFetchTaskNG.java#L128)):*
> ```Java
>         if (filesFromMultipleRepo.containsKey(gitFetchFilesConfig.getIdentifier())) {
>           FetchFilesResult fetchFilesResult = filesFromMultipleRepo.get(gitFetchFilesConfig.getIdentifier());
>           if (fetchFilesResult.getFiles() != null && gitFetchFilesResult.getFiles() != null) {
> ```

nit: Should use isNotEmpty() method instead of != null.

**Review by GoelPratyush99 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33358)* status: :shipit: complete! ✓

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/GitFetchTaskNG.java` line 128 at r4](https://reviewable.io/reviews/harness/harness-core/33358#-N2VPaTD3V-v7n2I-Cwn:-N2VQm7v9tThirbXclkh:bxzq6gs) ([raw file](https://github.com/harness/harness-core/blob/7142b2d7f252a45de1af21d84d1fad150a5bc552/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/GitFetchTaskNG.java#L128)):*
> nit: Should use isNotEmpty() method instead of != null.



_Code snippet:_
```Java
!isNull()
```

**Pull request merged**
