### PR TITLE
feat: [PL-22249]: change errorcode when full sync config not found

### PR DESCRIPTION
**Pull request by bhavya181**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30443)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
trigger compile

**Comment by USB-05** [comment]
trigger compile

**Comment by USB-05** [comment]
trigger ft1 ft2 ti3 ti4

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30443)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java, line 49 at r2](https://reviewable.io/reviews/harness/harness-core/30443#-MutnGWu1R_tbJllTHKr:-MutnGWu1R_tbJllTHKs:bbt5pyh) ([raw file](https://github.com/harness/harness-core/blob/a1d201de5b338c396ff1e22f8c9e409bb14ef6de/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java#L49)):*
> ```Java
>           accountIdentifier, orgIdentifier, projectIdentifier));
>       throw new InvalidRequestException(
>           String.format("A full sync config already exists for this account [%s], org [%s], project [%s]",
> ```

Lets use same error message at both places. Just use a variable to declare the error message, log it and return it as well.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java, line 81 at r2](https://reviewable.io/reviews/harness/harness-core/30443#-MutnTKi40otaUdSf65j:-MutnTKi40otaUdSf65k:b8pyh0a) ([raw file](https://github.com/harness/harness-core/blob/a1d201de5b338c396ff1e22f8c9e409bb14ef6de/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java#L81)):*
> ```Java
>     GitFullSyncConfig gitFullSyncConfig = gitFullSyncConfigRepository.update(criteria, update);
>     if (gitFullSyncConfig == null) {
>       throw new InvalidRequestException("No such configuration found, please check the scope.", WingsException.USER);
> ```

This should again be 404. And it should probably say "no configuration with given parameters found" or something similar.

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java, line 81 at r3](https://reviewable.io/reviews/harness/harness-core/30443#-MutpXUh40jDT4QZ-mHV:-MutpXUh40jDT4QZ-mHW:b-4d0b5u) ([raw file](https://github.com/harness/harness-core/blob/042bcb199fa942fbf95f51163cb083f2507ff823/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java#L81)):*
> ```Java
>     GitFullSyncConfig gitFullSyncConfig = gitFullSyncConfigRepository.update(criteria, update);
>     if (gitFullSyncConfig == null) {
>       throw new InvalidRequestException("No such configuration found, please check the scope.", WingsException.USER);
> ```

Can you check what happens if the fields-to-update have exactly same values as its in the input list? Then does it count it as an update or not.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30443)* status: 6 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java, line 49 at r2](https://reviewable.io/reviews/harness/harness-core/30443#-MutnGWu1R_tbJllTHKr:-Mutqezi9Do2knmXf5T0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a1d201de5b338c396ff1e22f8c9e409bb14ef6de/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java#L49)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets use same error message at both places. Just use a variable to declare the error message, log it and return it as well.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java, line 81 at r2](https://reviewable.io/reviews/harness/harness-core/30443#-MutnTKi40otaUdSf65j:-MutqbEg8RZ6Cn3t8rbW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a1d201de5b338c396ff1e22f8c9e409bb14ef6de/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java#L81)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This should again be 404. And it should probably say "no configuration with given parameters found" or something similar.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java, line 81 at r3](https://reviewable.io/reviews/harness/harness-core/30443#-MutpXUh40jDT4QZ-mHV:-Mutqc8P-leygeuB8dIM:b-b4xgar) ([raw file](https://github.com/harness/harness-core/blob/042bcb199fa942fbf95f51163cb083f2507ff823/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java#L81)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can you check what happens if the fields-to-update have exactly same values as its in the input list? Then does it count it as an update or not.
</blockquote></details>

it will count it as update.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30443)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java, line 81 at r3](https://reviewable.io/reviews/harness/harness-core/30443#-MutpXUh40jDT4QZ-mHV:-Mutqrde7fyl4CPOXPti:bqkxfwu) ([raw file](https://github.com/harness/harness-core/blob/042bcb199fa942fbf95f51163cb083f2507ff823/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java#L81)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

it will count it as update.
</blockquote></details>

Cool, can we add this as a UT itself

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30443)* status: 6 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java, line 81 at r3](https://reviewable.io/reviews/harness/harness-core/30443#-MutpXUh40jDT4QZ-mHV:-MutrzH8C-Cw6OoutuLj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/042bcb199fa942fbf95f51163cb083f2507ff823/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java#L81)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Cool, can we add this as a UT itself
</blockquote></details>

Done.

**Review by DeepakPatankar — DISMISSED** [review]
> Reviewed 3 of 6 files at r2, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30443)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30443)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 6 files at r2, 2 of 2 files at r4, 1 of 1 files at r5, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30443)* status: :shipit: complete! ✓

**Pull request merged**
