### PR TITLE
[fix]: [CI-4921]: Fix assume cross account role on ECR

### PR DESCRIPTION
**Pull request by shubham149**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35262)

### CODE REVIEW

**Comment by shubham149** [comment]
trigger messagecheck

**Review by raghavharness — DISMISSED** [review]
> Reviewed 3 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35262)* status: :shipit: complete! ✓

**Comment by shubham149** [comment]
Codebase hash approval PRs questions:
1. Is it new task type? (If yes, no need to answer 2 then)
 > No
2. Did you add a new class which is added in kryo serialization
> No
3. Did you make changes to the code in a backward-compatible manner?
> No
4. will the new version of the delegate receive old version task and process?
> Yes
5. If new version of the manager receives response for the old task will it be able to handle it successfully?
> Yes
6. Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager
> Yes
7. If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay
> Yes
8. if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay
> Yes
9. Did you remove an enum → this is not backward compatible yet (tracked by [DEL-3648: Move to name based kryo serializer for delegate/manager communicationIN PROGRESS](https://harness.atlassian.net/browse/DEL-3648) )
> No
10. Did you add an enum → make sure that the enum constant is added in the end of the already defined constants. If you don’t do this then you will have issues where wrong enum type will be deserialized in delegate side.
> Added enum at the end

**Review by raghavharness — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35262)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — APPROVED** [review]

**Comment by shubham149** [comment]
trigger codebasehash

**Comment by diptiman-adak** [comment]
trigger codebasehash

**Review by raghavharness — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35262)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 1 of 3 files at r2, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35262)* status: :shipit: complete! ✓

**Comment by shubham149** [comment]
trigger codebasehash

**Pull request merged**
