### PR TITLE
techdebt: [CDS-51701]: Created CD manager pms integration module

### PR DESCRIPTION
**Pull request by hextechpal**
## Describe your changes
In this pr I have created the cd-manager pms integration module. The idea is all the code integration pieces will move to this particular and then we can start moving the steps and start it as a different service while sharing these integration module with ng manager.

Eventually when all the steps have moved we can remove this integration module dependency from the ng-manager service.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42918)

### CODE REVIEW

**Comment by hextechpal** [comment]
trigger messagecheck

**Review by markoharness — APPROVED** [review]
> Reviewed 160 of 160 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42918)* status: 160 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 91 of 160 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42918)* status: 69 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 69 of 160 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42918)* status: 1 of 2 approvals obtained.

**Review by hextechpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42918)* status: 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`cd-manager/modules/pipeline/integration/core/BUILD.bazel` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/42918#-NMUQTkXEmrf7AdOJYZh:-NMXIwdZ5Fnu34CicxfA:boli0yw) ([raw file](https://github.com/harness/harness-core/blob/e61d352c66de6ccd00b96649cd460f87bc7d5d88/cd-manager/modules/pipeline/integration/core/BUILD.bazel#L14)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should this depend on the migrator ? I think it should be other way round ?
</blockquote></details>

This is not dependency rather visibility, only the modules defined in visibility array can use this, right now i am 100 migrator and subpackages, 125 and subpackages and cd-manager and subpackages

**Review by hextechpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42918)* status: 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`cd-manager/modules/pipeline/integration/core/BUILD.bazel` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/42918#-NMUQTkXEmrf7AdOJYZh:-NMXJLJSAssQohkqkn8k:bmi7fvm) ([raw file](https://github.com/harness/harness-core/blob/e61d352c66de6ccd00b96649cd460f87bc7d5d88/cd-manager/modules/pipeline/integration/core/BUILD.bazel#L14)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

This is not dependency rather visibility, only the modules defined in visibility array can use this, right now i am 100 migrator and subpackages, 125 and subpackages and cd-manager and subpackages
</blockquote></details>

125 visibility should cease to exist eventually

**Comment by hextechpal** [comment]
Closing this pr a lot of structure has changed in 125 rebasing is a pain i will create a fresh PR

**Pull request closed without merging**
