### PR TITLE
feat: [PL-27005]: enhance error message for SSO disabled PAT

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
Tested with -
list branch 
create file

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35743)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/ScmErrorExplanations.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/35743#-N80FeLS5gpgYw3UStp3:-N80FeLS5gpgYw3UStp4:b-2yiyu4) ([raw file](https://github.com/harness/harness-core/blob/05d20824b8b897f1e99219b6303494863d848d62/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/ScmErrorExplanations.java#L24)):*
> ```Java
>       + "2. The given branch<BRANCH> or repo<REPO> is invalid";
>   public static final String INVALID_CONNECTOR_CREDS =
>       "The credentials provided in the Github connector<CONNECTOR> are invalid or have expired or do not configured with SSO.";
> ```

grammatical correction: "are not configured"

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/35743#-N80FrZK7nKsRDAb2iCy:-N80FrZK7nKsRDAb2iCz:bggfe5u) ([raw file](https://github.com/harness/harness-core/blob/05d20824b8b897f1e99219b6303494863d848d62/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L67)):*
> ```Java
>   @Inject ExceptionManager exceptionManager;
>   private String errorFormat =
>       "Unexpected error occurred while performing %s git operation in Git Sync Service. Please contact Harness Support.";
> ```

lets avoid using "sync" anywhere from now onwards. Lets call it simply GIT service or git management service

Lets have a constant for it and use it everywhere in the logs. We can create a small logger method in this file and take string as argument and log it with the constant. Use the method to log everywhere then.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 211 at r2](https://reviewable.io/reviews/harness/harness-core/35743#-N80GOcHCCNuVp0D6un-:-N80GOcI2flM8sePQQoK:brj7wax) ([raw file](https://github.com/harness/harness-core/blob/05d20824b8b897f1e99219b6303494863d848d62/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L211)):*
> ```Java
>     try (GlobalContextManager.GlobalContextGuard guard = GlobalContextManager.ensureGlobalContextGuard();
>          MdcContextSetter ignore1 = new MdcContextSetter(contextMap)) {
>       log.info("Git Sync Service Grpc request received for getRepoUrl ops {}", request);
> ```

I see misses here, thanks for correcting them.

PS: these should've been caught in earlier reviews :-p

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35743)* status: 4 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/ScmErrorExplanations.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/35743#-N80FeLS5gpgYw3UStp3:-N83SleUABFvntaN__VO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/05d20824b8b897f1e99219b6303494863d848d62/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/ScmErrorExplanations.java#L24)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

grammatical correction: "are not configured"
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/35743#-N80FrZK7nKsRDAb2iCy:-N83Sji-E6oj3m-CP4E6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/05d20824b8b897f1e99219b6303494863d848d62/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L67)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets avoid using "sync" anywhere from now onwards. Lets call it simply GIT service or git management service

Lets have a constant for it and use it everywhere in the logs. We can create a small logger method in this file and take string as argument and log it with the constant. Use the method to log everywhere then.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35743)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by adivishy1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35743)* status: 4 file(s) to review.

**Review by adivishy1 — APPROVED** [review]

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35743)* status: 1 file(s) to review.

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35743)* status: :shipit: complete! ✓

**Review by ashishsanodia-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35743)* status: :shipit: complete! ✓

**Pull request merged**
