### PR TITLE
feat: [CDS-50173]: Adding anonymous authentication to OCI HelmRegistry.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
Added support for helm charts from public OCI HelmRegistry.
Screenshot 2023-01-18 at 11 35 36 AM

Connector Validation
Screenshot 2023-01-20 at 6 30 25 PM
Screenshot 2023-01-20 at 6 30 41 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42744)

### CODE REVIEW

**Comment by GoelPratyush99** [comment]
trigger messagecheck

**Comment by GoelPratyush99** [comment]
trigger ft1

**Comment by GoelPratyush99** [comment]
trigger ft2

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42744)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmValidationHandler.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/42744#-NM4lIi6Di09e_Y_6Xnp:-NM4lIi6Di09e_Y_6Xnq:b-rhw0yz) ([raw file](https://github.com/harness/harness-core/blob/ead0fd1012b27c248b3f5cb98bff36da623f8f01/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmValidationHandler.java#L59)):*
> ```Java
> 
>       decryptEncryptedDetails(helmValidationParams);
>       if (OciHelmAuthType.USER_PASSWORD.equals(helmValidationParams.getOciHelmConnectorDTO().getAuth().getAuthType())) {
> ```

Please check if we can add Socket or Http connection capability check instead for anonymous credentials

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42744)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmValidationHandler.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/42744#-NM4lIi6Di09e_Y_6Xnp:-NMEIg8XAflaKwjKxuPw:bb097zy) ([raw file](https://github.com/harness/harness-core/blob/ead0fd1012b27c248b3f5cb98bff36da623f8f01/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmValidationHandler.java#L59)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Please check if we can add Socket or Http connection capability check instead for anonymous credentials
</blockquote></details>

I have added validation for both anonymous and username password auth type

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42744)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by namantalaycha10 — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42744)* status: :shipit: complete! ✓

**Pull request merged**
