### PR TITLE
feat: [CDS-37899]: Create EnvironmentStepV2 and publish outcomes of environment

### PR DESCRIPTION
**Pull request by prashantsharma04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33378)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 7 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33378)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentHelper.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/33378#-N2W4cec-O6jbEZpU8Hj:-N2W4cedBEjK_VBssD5W:b-tqfjve) ([raw file](https://github.com/harness/harness-core/blob/b445d5f583a3815a5c3b3e09bc757f8e0dac9977/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentHelper.java#L20)):*
> ```Java
> @OwnedBy(HarnessTeam.CDC)
> @UtilityClass
> public class EnvironmentHelper {
> ```

should we have only helper as of now, entiti to pojo for step param and outcomes?



_Code quote:_
```Java
nvironmentHelper {
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentUtils.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/33378#-N2W4mA1AM1zu4EQrzgl:-N2W4mA1AM1zu4EQrzgm:b-f1v36x) ([raw file](https://github.com/harness/harness-core/blob/b445d5f583a3815a5c3b3e09bc757f8e0dac9977/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentUtils.java#L29)):*
> ```Java
> @OwnedBy(HarnessTeam.CDC)
> @UtilityClass
> public class EnvironmentUtils {
> ```

EnvironmentStepUtils



_Code quote:_
```Java
EnvironmentUtils
```
___
*[`800-pipeline-service/src/test/resources/recaster/alias/alias.txt` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/33378#-N2W50xM8u9zoqEDAIES:-N2W50xN3tqpwoWzNj3-:b-hlipon) ([raw file](https://github.com/harness/harness-core/blob/b445d5f583a3815a5c3b3e09bc757f8e0dac9977/800-pipeline-service/src/test/resources/recaster/alias/alias.txt#L111)):*
> ```help
> io.harness.steps.servicenow.ServiceNowTicketOutcome
> io.harness.steps.customstage.CustomStageNode
> io.harness.steps.environment.EnvironmentOutcomeV2
> ```

why its needed here?



_Code quote:_
```help
io.harness.steps.environment.EnvironmentOutcomeV
```
___
*[`860-orchestration-steps/src/test/resources/recaster/alias/alias.txt` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/33378#-N2W52VJAfCjKqcrlbLN:-N2W52VK2IEkM6JpYYYO:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/b445d5f583a3815a5c3b3e09bc757f8e0dac9977/860-orchestration-steps/src/test/resources/recaster/alias/alias.txt#L111)):*
> ```help
> io.harness.steps.servicenow.ServiceNowTicketOutcome
> io.harness.steps.customstage.CustomStageNode
> io.harness.steps.environment.EnvironmentOutcomeV2
> ```

same



_Code quote:_
```help
io.harness.steps.environment.EnvironmentOutcomeV2
```
___
*[`860-orchestration-visualization/src/test/resources/recaster/alias/alias.txt` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/33378#-N2W53Q1--vD0BElr7xO:-N2W53Q1--vD0BElr7xP:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/b445d5f583a3815a5c3b3e09bc757f8e0dac9977/860-orchestration-visualization/src/test/resources/recaster/alias/alias.txt#L47)):*
> ```help
> io.harness.steps.fork.ForkStepParameters
> io.harness.pms.expressions.ExecutionSummaryUpdateUtilsTest$TestStepParameters
> io.harness.steps.environment.EnvironmentOutcomeV2
> ```

same
___
*[`870-orchestration/src/test/resources/recaster/alias/alias.txt` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/33378#-N2W545KEjRbt29rPfab:-N2W545KEjRbt29rPfac:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/b445d5f583a3815a5c3b3e09bc757f8e0dac9977/870-orchestration/src/test/resources/recaster/alias/alias.txt#L46)):*
> ```help
> io.harness.steps.common.steps.stepgroup.StepGroupStepParameters
> io.harness.steps.fork.ForkStepParameters
> io.harness.steps.environment.EnvironmentOutcomeV2
> ```

same
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/environment/EnvironmentOutcomeV2.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/33378#-N2W566HDBom1_H_rDs-:-N2W566HDBom1_H_rDs0:b-sof97s) ([raw file](https://github.com/harness/harness-core/blob/b445d5f583a3815a5c3b3e09bc757f8e0dac9977/878-ng-common-utilities/src/main/java/io/harness/steps/environment/EnvironmentOutcomeV2.java#L28)):*
> ```Java
> @RecasterAlias("io.harness.steps.environment.EnvironmentOutcomeV2")
> @OwnedBy(CDC)
> public class EnvironmentOutcomeV2 implements Outcome, ExecutionSweepingOutput {
> ```

is this outcome needed at lower modules?



_Code quote:_
```Java
EnvironmentOutcomeV2
```

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33378)* status: 8 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentUtils.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/33378#-N2W4mA1AM1zu4EQrzgl:-N2W6E4z-W8eFE7PLlIA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b445d5f583a3815a5c3b3e09bc757f8e0dac9977/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentUtils.java#L29)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

EnvironmentStepUtils
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/environment/EnvironmentOutcomeV2.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/33378#-N2W566HDBom1_H_rDs-:-N2W5WLa3HHFfN0A23gh:b-90ka5q) ([raw file](https://github.com/harness/harness-core/blob/b445d5f583a3815a5c3b3e09bc757f8e0dac9977/878-ng-common-utilities/src/main/java/io/harness/steps/environment/EnvironmentOutcomeV2.java#L28)):*
> EnvironmentOutcomeV2
I have placed at the same location as V1 version of it

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33378)* status: 17 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`800-pipeline-service/src/test/resources/recaster/alias/alias.txt` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/33378#-N2W50xM8u9zoqEDAIES:-N2WW_5IAPSUvZ-0jYNh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b445d5f583a3815a5c3b3e09bc757f8e0dac9977/800-pipeline-service/src/test/resources/recaster/alias/alias.txt#L111)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why its needed here?
</blockquote></details>

Done.
___
*[`860-orchestration-steps/src/test/resources/recaster/alias/alias.txt` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/33378#-N2W52VJAfCjKqcrlbLN:-N2WW_nBDUV-HtQ221tk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b445d5f583a3815a5c3b3e09bc757f8e0dac9977/860-orchestration-steps/src/test/resources/recaster/alias/alias.txt#L111)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`860-orchestration-visualization/src/test/resources/recaster/alias/alias.txt` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/33378#-N2W53Q1--vD0BElr7xO:-N2WWa5g90nJ0S8qpYZr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b445d5f583a3815a5c3b3e09bc757f8e0dac9977/860-orchestration-visualization/src/test/resources/recaster/alias/alias.txt#L47)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`870-orchestration/src/test/resources/recaster/alias/alias.txt` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/33378#-N2W545KEjRbt29rPfab:-N2WWaff6TPqcIoRFOsz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b445d5f583a3815a5c3b3e09bc757f8e0dac9977/870-orchestration/src/test/resources/recaster/alias/alias.txt#L46)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentHelper.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/33378#-N2W4cec-O6jbEZpU8Hj:-N2WWVnB7gALdm_HOiuZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b445d5f583a3815a5c3b3e09bc757f8e0dac9977/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentHelper.java#L20)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should we have only helper as of now, entiti to pojo for step param and outcomes?
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33378)* status: :shipit: complete! ✓

**Pull request merged**
