### PR TITLE
feat: [CDS-85904]: Rollout deployment not working when pipeline is rerun

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Describe your changes

**Problem**: If a user is retrying from a matrix stage, the successful matrix stage are getting skipped. Ideally if the user is selecting the stage to be retried from, all nodes should run.

**Solution**: We do receive a variable runAllStages from UI. Default value is true. If the pipeline fails at a parallel group, user can specify if they wants to run only the failed stage (runAllStages = false) or all (runAllStages = true)

We will utilise this variable for matrix too. If user is using rerun from last stage then runAllStages value will be false (if selected stage is a matrix or a parallel group)

If they are selected rerun from specific stage, the UI will send the value as true.

**Testing**: Tested in local. Created a pipeline of three stages with second stage as matrix. Failed the third stage and retried from matrix. Before retrying from matrix, I did change the yaml. On retrying from matrix I checked the shell script input tab to check if new changes are coming or the old one. After my changes, I saw new step parameters. Before my changes, it was not reflecting the new yaml changes.

Screenshot 2023-12-14 at 4 27 26 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56780)

****

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger ut5

**Comment by prashantsharma04** [comment]
trigger ut7

**Comment by prashantsharma04** [comment]
trigger ut8

**Comment by prashantsharma04** [comment]
trigger ut9

**Comment by prashantsharma04** [comment]
trigger ut8

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 489 at r2](https://reviewable.io/reviews/harness/harness-core/56780#-Nlv9jrK6R82SmJD-ntB:-Nlv9jrL-WrzH_RwPeu0:bqkba0r) ([raw file](https://github.com/harness/harness-core/blob/49041b820e5ca0070561cc2a6680b457a6c0ec9f/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L489)):*
> ```Java
>     for (Node node : planNodes) {
>       if (stagesFqnToRetryWith.contains(node.getStageFqn()) && node.getStepCategory() == StepCategory.STRATEGY) {
>         if (runAllStages) {
> ```

nit: can be simplified by adding a && !runAllStages in the above if condition

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56780)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56780)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56780)* status: Some of the checks are too old.

**Comment by sahilhindwani-harness** [comment]
trigger review

**Pull request merged**
