### PR TITLE
feat: [CDS-46619]: modify delegate agent manager client's connection …

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
…pool for connection re-use

## Describe your changes
https://harness.atlassian.net/browse/CDS-46619

Delegate sends task progress via taskProgressExecutor thread, which is creating a lot of child threads (used for http connection) originating from the http client. 

The current configuration of the connection pool (used by the okhttp client) contains 0 maxIdleConnections, which prevents re-use of same thread for sending task progress.

Http.connectionPool -> `public static ConnectionPool connectionPool = new ConnectionPool(0, 5, TimeUnit.MINUTES);`

Before:
Screenshot 2022-11-15 at 1 18 53 PM

After:
Screenshot 2022-11-15 at 1 19 27 PM

JFR dumps attached on ticket.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40165)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40165)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClientFactory.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/40165#-NGuVHSH9DiLuaGsX5Or:-NGuVHSH9DiLuaGsX5Os:b88ex2d) ([raw file](https://github.com/harness/harness-core/blob/c1ca4375da27605cf7b2f510c2e6b3775ffca9f2/420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClientFactory.java#L58)):*
> ```Java
>   private final boolean trustAllCertificates;
>   private final OkHttpClient httpClient;
>   private final static ConnectionPool connectionPool = new ConnectionPool(16, 5, TimeUnit.MINUTES);
> ```

How we come up with 16 ? Keeping too much idle connection is not good for process health, how about if we bring this number lower 5 or something ?



_Code quote:_
```Java
16
```

**Comment by yogesh-chauhan** [comment]
*[`420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClientFactory.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/40165#-NGuVHSH9DiLuaGsX5Or:-NGupq5q6IS3tB01SuMo:b1u6wym) ([raw file](https://github.com/harness/harness-core/blob/c1ca4375da27605cf7b2f510c2e6b3775ffca9f2/420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClientFactory.java#L58)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

How we come up with 16 ? Keeping too much idle connection is not good for process health, how about if we bring this number lower 5 or something ?
</blockquote></details>

Earlier we had maxIdle as 0 which meant that new workers were being added as tasks came up and re-use was 0
Now, the behaviour will be that we keep max 16 idle threads ( each thread being max idle for 5 minutes ), post which they will be killed 
IMO,  16 is better than 5  because if the threads are idle they will be taken away but if there are tasks to be run, then a lower number means that more threads need to destroyed/created and re-use is lesser

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40165)* status: 1 change requests. 1. unresolved discussions.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40165)* status: :shipit: complete! ✓

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Pull request merged**
