### PR TITLE
fix: [CDS-71177]: fix branch support during resolution of template refs while creating/updating nested template

### PR DESCRIPTION
**Pull request by mohitg0795**
## Describe your changes
- There are multiple different flows where template ref parsing happens during template resolution
- In one such flow, branch paramteter wasn't correctly being passed and thus it was failing

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48809)

### CODE REVIEW

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
validate review

**Review by sribalij — CHANGES_REQUESTED** [review]
A few Junits?

**Review by mohitg0795 — COMMENTED** [review]
UTs are missing completely for these pieces and these are complicated pieces, will need time to write them. Currently, need to merge fix for a feature request into pre-qa so will request for approval for now. I've created a follow up ticket for UT planned in next sprint: https://harness.atlassian.net/browse/CDS-71220. Let me know if there are any concerns. Thanks.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48809#-:-NXBRwlWD1hfjfgvqdkr:b47lg3g)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`template-service/service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 179 at r1](https://reviewable.io/reviews/harness/harness-core/48809#-NXBfAQqBPm_CZc6MwP7:-NXBfAQqBPm_CZc6MwP8:bth03fe) ([raw file](https://github.com/harness/harness-core/blob/02fda0d1140a4b16f271136f4a7c76a86904e9a7/template-service/service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L179)):*
> ```Java
>           JsonNode versionLabelNode = (JsonNode) fqnToValueMap.get(FQN.builder().fqnList(fqnList).build());
>           String versionLabel = versionLabelNode == null ? null : versionLabelNode.asText();
>           fqnList.remove(fqnList.size() - 1);
> ```

nit: Can we add a comment as to why we are doing this?

**Comment by mohitg0795** [comment]
*[`template-service/service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 179 at r1](https://reviewable.io/reviews/harness/harness-core/48809#-NXBfAQqBPm_CZc6MwP7:-NXBgnZcDMrKO05S-OSh:b-lzxnu4) ([raw file](https://github.com/harness/harness-core/blob/02fda0d1140a4b16f271136f4a7c76a86904e9a7/template-service/service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L179)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: Can we add a comment as to why we are doing this?
</blockquote></details>

Its very complex piece that has been written. Took me good amount of time to understand and add my change over here. I will add a comment in my next PR.

**Pull request merged**
