### PR TITLE
feat: [PIE-7364]: Execution changes for policy as advanced options for the steps extended by AsyncExecutables

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42106)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 86 files at r2, 1 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42106)* status: 93 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/executable/CiAsyncExecutable.java` line 32 at r4](https://reviewable.io/reviews/harness/harness-core/42106#-NLKGi8l-nl9bcgbprOp:-NLKGi8l-nl9bcgbprOq:b63nuv7) ([raw file](https://github.com/harness/harness-core/blob/33db01e487d9f1584ac50fc61b838e8742f5b5a1/332-ci-manager/service/src/main/java/io/harness/ci/execution/executable/CiAsyncExecutable.java#L32)):*
> ```Java
>       Ambiance ambiance, StepElementParameters stepParameters, Map<String, ResponseData> responseDataMap);
> 
>   public StepResponse postValidate(Ambiance ambiance, StepElementParameters stepParameters, StepResponse stepResponse) {
> ```

postTaskValidate and comments 
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/executable/AsyncExecutableWithCapabilities.java` line 25 at r4](https://reviewable.io/reviews/harness/harness-core/42106#-NLKJGoQDDh93lV-lSH4:-NLKJGoR5lG6hWeGjth1:bsrz8b5) ([raw file](https://github.com/harness/harness-core/blob/33db01e487d9f1584ac50fc61b838e8742f5b5a1/878-ng-common-utilities/src/main/java/io/harness/steps/executable/AsyncExecutableWithCapabilities.java#L25)):*
> ```Java
> 
> @OwnedBy(PIPELINE)
> // Async Executable With Rollback and Post Validation
> ```

i think this should have rbac also default could be empty.
Only rollback we should not have anymore
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/executable/AsyncExecutableWithCapabilities.java` line 46 at r4](https://reviewable.io/reviews/harness/harness-core/42106#-NLKJUtn53BfDoGKH1un:-NLKJUtn53BfDoGKH1uo:b-gaizk) ([raw file](https://github.com/harness/harness-core/blob/33db01e487d9f1584ac50fc61b838e8742f5b5a1/878-ng-common-utilities/src/main/java/io/harness/steps/executable/AsyncExecutableWithCapabilities.java#L46)):*
> ```Java
>   // evaluating policies added in advanced section of the steps and updating status and failure info in the step
>   // response
>   public StepResponse postValidate(Ambiance ambiance, StepElementParameters stepParameters, StepResponse stepResponse) {
> ```

posttaskValidate
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/executables/PipelineAsyncExecutable.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/42106#-NLKJPjiBwAJc4BnXR2c:-NLKJPjiBwAJc4BnXR2d:b-v6d3oz) ([raw file](https://github.com/harness/harness-core/blob/33db01e487d9f1584ac50fc61b838e8742f5b5a1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/executables/PipelineAsyncExecutable.java#L24)):*
> ```Java
> 
> @OwnedBy(CDC)
> public abstract class PipelineAsyncExecutable extends AsyncExecutableWithCapabilities {
> ```

comments why this executable

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42106)* status: 93 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/executable/CiAsyncExecutable.java` line 32 at r4](https://reviewable.io/reviews/harness/harness-core/42106#-NLKGi8l-nl9bcgbprOp:-NLKL8G22G4CCldIn5F-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/33db01e487d9f1584ac50fc61b838e8742f5b5a1/332-ci-manager/service/src/main/java/io/harness/ci/execution/executable/CiAsyncExecutable.java#L32)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

postTaskValidate and comments 
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/executable/AsyncExecutableWithCapabilities.java` line 25 at r4](https://reviewable.io/reviews/harness/harness-core/42106#-NLKJGoQDDh93lV-lSH4:-NLKUyMSEntsOZuPpchN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/33db01e487d9f1584ac50fc61b838e8742f5b5a1/878-ng-common-utilities/src/main/java/io/harness/steps/executable/AsyncExecutableWithCapabilities.java#L25)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i think this should have rbac also default could be empty.
Only rollback we should not have anymore
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/executable/AsyncExecutableWithCapabilities.java` line 46 at r4](https://reviewable.io/reviews/harness/harness-core/42106#-NLKJUtn53BfDoGKH1un:-NLKL4Sp6m-iyyY4aVm-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/33db01e487d9f1584ac50fc61b838e8742f5b5a1/878-ng-common-utilities/src/main/java/io/harness/steps/executable/AsyncExecutableWithCapabilities.java#L46)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

posttaskValidate
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/executables/PipelineAsyncExecutable.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/42106#-NLKJPjiBwAJc4BnXR2c:-NLKNFW-B9EEGagRZZ5B:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/33db01e487d9f1584ac50fc61b838e8742f5b5a1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/executables/PipelineAsyncExecutable.java#L24)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

comments why this executable
</blockquote></details>

Done.

**Review by namanvermah — DISMISSED** [review]
> Reviewed 18 of 86 files at r2, 5 of 17 files at r3, 58 of 62 files at r4, 9 of 10 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42106)* status: 91 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 86 files at r2, 6 of 62 files at r4, 9 of 10 files at r5, 3 of 3 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42106)* status: 74 file(s) to review. 1 of 2 approvals obtained.

**Review by namanvermah — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42106)* status: 71 file(s) to review.

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42106)* status: 71 file(s) to review.

**Review by archit-harness — APPROVED** [review]
> Reviewed 14 of 86 files at r2, 5 of 17 files at r3, 52 of 62 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42106)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 18 of 86 files at r2, 5 of 17 files at r3, 58 of 62 files at r4, 9 of 10 files at r5, 3 of 3 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42106)* status: :shipit: complete! ✓

**Pull request merged**
