### PR TITLE
fix: [PIE-6098]: [Next-Gen] Custom Webhook trigger response

### PR DESCRIPTION
**Pull request by sribalij**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39717)

### CODE REVIEW

**Review by vcalasansh — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39717)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by sribalij** [comment]
trigger messagecheck

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39717)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39717)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/UrlHelper.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/39717#-NGKLqKPB5c3EyGbei26:-NGKLqKPB5c3EyGbei27:b-3rmrw9) ([raw file](https://github.com/harness/harness-core/blob/6688f97943beb9b0f348bd364c6b824892e6910b/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/UrlHelper.java#L35)):*
> ```Java
> 
>   public String buildApiExecutionUrl(String uuid, String accountIdentifier) {
>     return format("%sgateway/pipeline/api/webhook/triggerExecutionDetails/%s?accountIdentifier=%s",
> ```

Adding gateway is true for all prod1, prod2, prod3 and even in on-prem, and communit edition?



_Code quote:_
```Java
gateway/pipeline/api
```

**Review by sribalij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39717)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/UrlHelper.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/39717#-NGKLqKPB5c3EyGbei26:-NGTgaQi1ILGTvvAoqCS:bhxptj8) ([raw file](https://github.com/harness/harness-core/blob/6688f97943beb9b0f348bd364c6b824892e6910b/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/UrlHelper.java#L35)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Adding gateway is true for all prod1, prod2, prod3 and even in on-prem, and communit edition?
</blockquote></details>

Got confirmation from SRE team that this exists.

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39717)* status: :shipit: complete! ✓

**Pull request merged**
