### PR TITLE
feat: [CDS-37239]: Infra planCreator change in Environment PlanCreator V2

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33572)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33572)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 164 at r3](https://reviewable.io/reviews/harness/harness-core/33572#-N2zVFpoEOgM5t5ed0ou:-N2zVFpoEOgM5t5ed0ov:b1ni4gu) ([raw file](https://github.com/harness/harness-core/blob/bf7d9b0fa9d6b406d84c6f1b1c50dd40cd65ffbb/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L164)):*
> ```Java
>       String infraSectionUuid = "infraSection-" + UUIDGenerator.generateUuid();
>       String environmentUuid = "environment-" + UUIDGenerator.generateUuid();
> ```

serviceSpec can come from serviceField, and let serviceFunction add its dependencies itself



_Code quote:_
```Java
      String serviceSpecNodeId = "service-" + UUIDGenerator.generateUuid();
      String infraSectionUuid = "infraSection-" + UUIDGenerator.generateUuid();
      String environmentUuid = "environment-" + UUIDGenerator.generateUuid();
```

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 6 of 10 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33572)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 150 at r3](https://reviewable.io/reviews/harness/harness-core/33572#-N2zmaTE-b0j4mSLNDHL:-N2zmaTF64XSHLTIpMYQ:bsqp8ng) ([raw file](https://github.com/harness/harness-core/blob/bf7d9b0fa9d6b406d84c6f1b1c50dd40cd65ffbb/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L150)):*
> ```Java
> 
>   public YamlField addResourceConstraintDependency(
>       YamlNode rbacSiblingNode, LinkedHashMap<String, PlanCreationResponse> planCreationResponseMap) {
> ```

do you mean ```rcSiblingNode``` here ?

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33572)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 164 at r3](https://reviewable.io/reviews/harness/harness-core/33572#-N2zVFpoEOgM5t5ed0ou:-N2zqx89C6mF_8VswJNm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf7d9b0fa9d6b406d84c6f1b1c50dd40cd65ffbb/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L164)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

serviceSpec can come from serviceField, and let serviceFunction add its dependencies itself
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, 1 of 2 files at r3, 7 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33572)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorHelper.java` line 71 at r4](https://reviewable.io/reviews/harness/harness-core/33572#-N2zrbtbCQOZjTOk1gbG:-N2zrbtbCQOZjTOk1gbH:b-k82czm) ([raw file](https://github.com/harness/harness-core/blob/852e1097b0292808ab6f46386cad9cfd50edc093/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorHelper.java#L71)):*
> ```Java
>           YamlTypes.ENVIRONMENT_NODE_ID, ByteString.copyFrom(kryoSerializer.asDeflatedBytes(environmentUuid)));
>       serviceDependencyMap.put(
>           YamlTypes.NEXT_UUID, ByteString.copyFrom(kryoSerializer.asDeflatedBytes(infraSectionUuid)));
> ```

put this in else condition as if case is for v1, we should not change for v1, v1 env node uuid is above one only.



_Code quote:_
```Java
      serviceDependencyMap.put(
          YamlTypes.ENVIRONMENT_NODE_ID, ByteString.copyFrom(kryoSerializer.asDeflatedBytes(environmentUuid)));
      serviceDependencyMap.put(
          YamlTypes.NEXT_UUID, ByteString.copyFrom(kryoSerializer.asDeflatedBytes(infraSectionUuid)));
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorHelper.java` line 151 at r4](https://reviewable.io/reviews/harness/harness-core/33572#-N2zroIh8i0RTYDmo0ds:-N2zroIh8i0RTYDmo0dt:b-x0mhnj) ([raw file](https://github.com/harness/harness-core/blob/852e1097b0292808ab6f46386cad9cfd50edc093/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorHelper.java#L151)):*
> ```Java
>         YamlTypes.ENVIRONMENT_NODE_ID, ByteString.copyFrom(kryoSerializer.asDeflatedBytes(environmentUuid)));
>     return metadataDependency;
>   }
> ```

who needs this now?



_Code quote:_
```Java
  public static Map<String, ByteString> prepareMetadata(
      String serviceSpecNodeId, String infraSectionUuid, String environmentUuid, KryoSerializer kryoSerializer) {
    Map<String, ByteString> metadataDependency = new HashMap<>();
    metadataDependency.put(
        YamlTypes.SERVICE_SPEC_UUID, ByteString.copyFrom(kryoSerializer.asDeflatedBytes(serviceSpecNodeId)));
    metadataDependency.put(YamlTypes.NEXT_UUID, ByteString.copyFrom(kryoSerializer.asDeflatedBytes(infraSectionUuid)));
    metadataDependency.put(
        YamlTypes.ENVIRONMENT_NODE_ID, ByteString.copyFrom(kryoSerializer.asDeflatedBytes(environmentUuid)));
    return metadataDependency;
  }
```

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33572)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorHelper.java` line 71 at r4](https://reviewable.io/reviews/harness/harness-core/33572#-N2zrbtbCQOZjTOk1gbG:-N2zu8i78jCcmBbwTgaH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/852e1097b0292808ab6f46386cad9cfd50edc093/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorHelper.java#L71)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

put this in else condition as if case is for v1, we should not change for v1, v1 env node uuid is above one only.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorHelper.java` line 151 at r4](https://reviewable.io/reviews/harness/harness-core/33572#-N2zroIh8i0RTYDmo0ds:-N2zu4LsC5R91gp74h0x:b5n3azb) ([raw file](https://github.com/harness/harness-core/blob/852e1097b0292808ab6f46386cad9cfd50edc093/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorHelper.java#L151)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

who needs this now?
</blockquote></details>

deleted it

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33572)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorHelper.java` line 71 at r6](https://reviewable.io/reviews/harness/harness-core/33572#-N2zwkAWCLajYi5CmJw5:-N2zwkAWCLajYi5CmJw6:brzvw7n) ([raw file](https://github.com/harness/harness-core/blob/7d8cfb73c69a76f4fd27340a4c6eb74c1cab0fd4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorHelper.java#L71)):*
> ```Java
>     else {
>       serviceDependencyMap.put(
>           YamlTypes.ENVIRONMENT_NODE_ID, ByteString.copyFrom(kryoSerializer.asDeflatedBytes(environmentUuid)));
> ```

you have removed env node addition from v1, please test normal flows before merging your change



_Code quote:_
```Java
      serviceDependencyMap.put(
          YamlTypes.ENVIRONMENT_NODE_ID, ByteString.copyFrom(kryoSerializer.asDeflatedBytes(environmentUuid)));
```

**Comment by prashantsharma04** [comment]
trigger ti2

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33572)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorHelper.java` line 71 at r6](https://reviewable.io/reviews/harness/harness-core/33572#-N2zwkAWCLajYi5CmJw5:-N3-2LQK7TzvY5QZbbig:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d8cfb73c69a76f4fd27340a4c6eb74c1cab0fd4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorHelper.java#L71)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

you have removed env node addition from v1, please test normal flows before merging your change
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33572)* status: :shipit: complete! ✓

**Pull request merged**
