### PR TITLE
fix: [CDS-82037]: add missing null checks for syncing pipeline execution summary to timescale

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
There were null checks missing for adding author name, id, and avatar. Due to which the timescale sync for pipeline execution entities were failing for a customer, and some of the data was missing in timescale.
Added null checks for the same.

Tested locally:
1. Saving similar pipeline execution summary as customer had(with author object as below
`"author" : {
                    "__recast" : "io.harness.ci.pipeline.executions.beans.CIBuildAuthor"
                }, `
2. Saving pipeline execution summary with proper author info
3. Saving pipeline execution summary with only cd info
Tested^ with debezium enabled and disabled

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54756)

### CODE REVIEW

**Comment by RishabhGupta34** [comment]
trigger uts

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54756)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by Abhishek-CDC — APPROVED** [review]

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeDataHandler.java` line 194 at r1](https://reviewable.io/reviews/harness/harness-core/54756#-Ni3RE3v2bUKa0wq9Hu9:-Ni3RE3v2bUKa0wq9HuA:b42f7aq) ([raw file](https://github.com/harness/harness-core/blob/a60b6be281c33b8769cafa803fdb1884479b5ec6/110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeDataHandler.java#L194)):*
> ```Java
>       DBObject author = (DBObject) (ciExecutionInfo.get("author"));
>       if (author != null) {
>         if (author.get("id") != null) {
> ```

nit: Can we move all these to constants?

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54756)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54756)* status: 1. unresolved discussions. 

___
*[`110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeDataHandler.java` line 194 at r1](https://reviewable.io/reviews/harness/harness-core/54756#-Ni3RE3v2bUKa0wq9Hu9:-Ni3RydL10Qwe5sWteJC:bnjt4rc) ([raw file](https://github.com/harness/harness-core/blob/a60b6be281c33b8769cafa803fdb1884479b5ec6/110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeDataHandler.java#L194)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: Can we move all these to constants?
</blockquote></details>

same as below

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
> _[`110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeDataHandler.java` line 194 at r1](https://reviewable.io/reviews/harness/harness-core/54756#-Ni3RE3v2bUKa0wq9Hu9:-Ni3RE3v2bUKa0wq9HuA:b42f7aq) ([raw file](https://github.com/harness/harness-core/blob/a60b6be281c33b8769cafa803fdb1884479b5ec6/110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeDataHandler.java#L194)):_
> 
> > ```java
> >       DBObject author = (DBObject) (ciExecutionInfo.get("author"));
> >       if (author != null) {
> >         if (author.get("id") != null) {
> > ```
> 
> nit: Can we move all these to constants?

as this issue is with multiple files in cdc handlers, tracking it as part of https://harness.atlassian.net/browse/CDS-83180

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger uts

**Pull request merged**
