### PR TITLE
[feat]: [CDS-54854] EKS List Clusters API Implementation

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes
EKS List Clusters API Implementation

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44964)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44964)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java` line 397 at r1](https://reviewable.io/reviews/harness/harness-core/44964#-NQ9tG_K9nTzmoCmURaK:-NQ9tG_K9nTzmoCmURaL:bbaqshc) ([raw file](https://github.com/harness/harness-core/blob/320ca18544732b98a6192f0f0f65fbba843d3de6/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L397)):*
> ```Java
> 
>   @GET
>   @Path("eks-clusters")
> ```

Should be eks/clusters
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java` line 399 at r1](https://reviewable.io/reviews/harness/harness-core/44964#-NQ9tX2S9KXm3T95KBN6:-NQ9tX2S9KXm3T95KBN7:b-vkxuf2) ([raw file](https://github.com/harness/harness-core/blob/320ca18544732b98a6192f0f0f65fbba843d3de6/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L399)):*
> ```Java
>   @Path("eks-clusters")
>   @ApiOperation(value = "Get EKS clusters", nickname = "eks-clusters")
>   public ResponseDTO<List<String>> getEKSClusterNames(@QueryParam("awsConnectorRef") String awsConnectorRef,
> ```

We need to support expressions
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceServiceImpl.java` line 568 at r1](https://reviewable.io/reviews/harness/harness-core/44964#-NQ9th0R6s4fZChBGOvr:-NQ9th0R6s4fZChBGOvs:bzhqd0n) ([raw file](https://github.com/harness/harness-core/blob/320ca18544732b98a6192f0f0f65fbba843d3de6/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceServiceImpl.java#L568)):*
> ```Java
> 
>     DelegateResponseData responseData =
>         serviceHelper.getResponseData(access, awsTaskParams, TaskType.NG_AWS_TASK.name());
> ```

Let's have a new task type and task handler instead of reusing existing one
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsDelegateTask.java` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/44964#-NQ9tnFp6XvG1Lx2hvcj:-NQ9tnFp6XvG1Lx2hvck:b-fldzdu) ([raw file](https://github.com/harness/harness-core/blob/320ca18544732b98a6192f0f0f65fbba843d3de6/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsDelegateTask.java#L117)):*
> ```Java
>       case PUT_AUDIT_BATCH_TO_BUCKET:
>         return awsS3DelegateTaskHelper.putAuditBatchToBucket((AwsPutAuditBatchToBucketTaskParamsRequest) awsTaskParams);
>       case LIST_EKS_CLUSTERS:
> ```

We should have a new task type
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsEKSDelegateTaskHelper.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/44964#-NQ9ty3X3BxbTd3Let-h:-NQ9ty3X3BxbTd3Let-i:b-b885zx) ([raw file](https://github.com/harness/harness-core/blob/320ca18544732b98a6192f0f0f65fbba843d3de6/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsEKSDelegateTaskHelper.java#L64)):*
> ```Java
>       List<String> clusterList = new ArrayList<>();
>       String nextToken = null;
>       com.amazonaws.services.eks.model.ListClustersRequest listClustersRequest =
> ```

Can we import this?

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44964)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java` line 428 at r2](https://reviewable.io/reviews/harness/harness-core/44964#-NQUAC07AWBB28qIc6y-:-NQUAC07AWBB28qIc6y0:bb2ywyd) ([raw file](https://github.com/harness/harness-core/blob/e8bcb0f79ec8447cf5569ea8d8c22242febdee8b/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L428)):*
> ```Java
>   }
> 
>   @GET
> ```

Should be POST
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java` line 443 at r2](https://reviewable.io/reviews/harness/harness-core/44964#-NQUAHT399vmYhseBZSW:-NQUAHT399vmYhseBZSX:b-jr2t8n) ([raw file](https://github.com/harness/harness-core/blob/e8bcb0f79ec8447cf5569ea8d8c22242febdee8b/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L443)):*
> ```Java
>       @NotNull @QueryParam("fqnPath") String fqnPath,
>       @NotNull @QueryParam(NGCommonEntityConstants.PIPELINE_KEY) String pipelineIdentifier,
>       @QueryParam(NGCommonEntityConstants.SERVICE_KEY) String serviceRef,
> ```

Why do we need service ref here? 
___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 482 at r2](https://reviewable.io/reviews/harness/harness-core/44964#-NQUBL8o9Pak9VYFgd8R:-NQUBL8p-LndFm5Q6wKy:b-mfmary) ([raw file](https://github.com/harness/harness-core/blob/e8bcb0f79ec8447cf5569ea8d8c22242febdee8b/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L482)):*
> ```Java
>   TERRAFORM_CLOUD_CLEANUP_TASK_NG(TaskGroup.TERRAFORM_CLOUD, "Terraform Cloud Cleanup Task", true),
>   OCI_HELM_DOCKER_API_LIST_TAGS_TASK_NG(TaskGroup.HELM, "Task to query OCI Helm Docker API List Tags"),
>   AWS_EKS_LIST_CLUSTERS_TASK(TaskGroup.K8S_NG, "AWS EKS List Clusters Task");
> ```

This shouldn't be in K8s group

**Review by abhinavsingh1196 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r1, 9 of 13 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44964)* status: 7 file(s) to review. 2 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 872 at r3](https://reviewable.io/reviews/harness/harness-core/44964#-NQb9_NdANJ6p_Aiaq8D:-NQb9_NeDTDTU4kBE8WK:b-nf1uaz) ([raw file](https://github.com/harness/harness-core/blob/6dd8a8ae6d601c90a31822801a988561f0d41e7d/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L872)):*
> ```Java
>     if (connectorParameterField == null) {
>       return connectorRef;
>     } else if (!connectorParameterField.isExpression()) {
> ```

since each if/else-if block is returning, we don't need it. it can just be :
if (...) {
  return ;
}

if (...) {
  return;
}

... and so on
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 887 at r3](https://reviewable.io/reviews/harness/harness-core/44964#-NQbADfj3CtvRsP7B3Dy:-NQbADfj3CtvRsP7B3Dz:b-ppi80e) ([raw file](https://github.com/harness/harness-core/blob/6dd8a8ae6d601c90a31822801a988561f0d41e7d/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L887)):*
> ```Java
>             accountId, orgIdentifier, projectIdentifier, mergedCompleteYaml, gitEntityBasicInfo);
>       }
>       CDYamlExpressionEvaluator CDYamlExpressionEvaluator =
> ```

nit: should start with small case
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java` line 429 at r3](https://reviewable.io/reviews/harness/harness-core/44964#-NQbAeWh3OxyAJsNqhVr:-NQbAeWh3OxyAJsNqhVs:bxdb6zw) ([raw file](https://github.com/harness/harness-core/blob/6dd8a8ae6d601c90a31822801a988561f0d41e7d/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L429)):*
> ```Java
> 
>   @POST
>   @Path("v2/eks/clusters")
> ```

v2 suffix should probably be at the end `eks/clusters/v2`
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceServiceImpl.java` line 569 at r3](https://reviewable.io/reviews/harness/harness-core/44964#-NQbE8qv18IvpLWw3SGH:-NQbE8qv18IvpLWw3SGI:b-k8h2h9) ([raw file](https://github.com/harness/harness-core/blob/6dd8a8ae6d601c90a31822801a988561f0d41e7d/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceServiceImpl.java#L569)):*
> ```Java
>   }
> 
>   private List<String> getEKSClusterNamesTaskExecutionResponse(DelegateResponseData responseData) {
> ```

method name could be `getEksClusterNamesFromResponse`
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceServiceImpl.java` line 572 at r3](https://reviewable.io/reviews/harness/harness-core/44964#-NQbB71q9QhdmV-z9EOq:-NQbB71q9QhdmV-z9EOr:b-mfwc9a) ([raw file](https://github.com/harness/harness-core/blob/6dd8a8ae6d601c90a31822801a988561f0d41e7d/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceServiceImpl.java#L572)):*
> ```Java
>     if (responseData instanceof ErrorNotifyResponseData) {
>       ErrorNotifyResponseData errorNotifyResponseData = (ErrorNotifyResponseData) responseData;
>       throw new AwsEKSException("Failed to get AWS EKS clusters"
> ```

extract these as static final strings and use String.format() for constructing error message instead of concatenating.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsEKSDelegateTaskHelper.java` line 77 at r3](https://reviewable.io/reviews/harness/harness-core/44964#-NQbDP6C3lVXtGml_bQD:-NQbDP6C3lVXtGml_bQE:bmdo118) ([raw file](https://github.com/harness/harness-core/blob/6dd8a8ae6d601c90a31822801a988561f0d41e7d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsEKSDelegateTaskHelper.java#L77)):*
> ```Java
>     } catch (Exception e) {
>       Exception sanitizedException = ExceptionMessageSanitizer.sanitizeException(e);
>       log.error("Exception in getting AWS EKS clusters", sanitizedException);
> ```

message can be more specific, failed to list EKS clusters using ListClustersRequest for region `r1`

**Review by abhinavsingh1196 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44964)* status: 7 file(s) to review. 2 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsEKSDelegateTaskHelper.java` line 50 at r3](https://reviewable.io/reviews/harness/harness-core/44964#-NQbCaE0-C92YZ8ycd1t:-NQbCaE0-C92YZ8ycd1u:b4lh5ap) ([raw file](https://github.com/harness/harness-core/blob/6dd8a8ae6d601c90a31822801a988561f0d41e7d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsEKSDelegateTaskHelper.java#L50)):*
> ```Java
>     List<String> clusters = new ArrayList<>();
>     awsRegions.forEach(awsRegion -> {
>       List<String> eksClusters = listEKSClustersForGivenRegion(awsRegion, awsInternalConfig);
> ```

We should probably see if there is possibility for cluster names to be same across regions. If so, we can output cluster names as `region/cluster-name`
I believe this is the same format output by our GKE implementation too. Please confirm.
Region can be later used later during DescribeCluster SDK request also?

**Comment by lovish1999** [comment]
trigger ut2

**Comment by lovish1999** [comment]
trigger ut5

**Review by abosii-harness — COMMENTED** [review]
> Reviewed 5 of 7 files at r3, 5 of 7 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44964)* status: 2 file(s) to review. 2 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by abhinavsingh1196 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44964)* status: 2 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java` line 429 at r3](https://reviewable.io/reviews/harness/harness-core/44964#-NQbAeWh3OxyAJsNqhVr:-NQj4ffZ8x9Qo-h0iF8K:b-ddcj42) ([raw file](https://github.com/harness/harness-core/blob/6dd8a8ae6d601c90a31822801a988561f0d41e7d/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L429)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

v2 suffix should probably be at the end `eks/clusters/v2`
</blockquote></details>

@lovish1999 please change this too

**Review by lovish1999 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44964)* status: 5 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java` line 443 at r2](https://reviewable.io/reviews/harness/harness-core/44964#-NQUAHT399vmYhseBZSW:-NQjPkcB5lgdlUcpe4FK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e8bcb0f79ec8447cf5569ea8d8c22242febdee8b/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L443)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why do we need service ref here? 
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java` line 429 at r3](https://reviewable.io/reviews/harness/harness-core/44964#-NQbAeWh3OxyAJsNqhVr:-NQjPiQV0RQtGu8TA6DB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6dd8a8ae6d601c90a31822801a988561f0d41e7d/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L429)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

@lovish1999 please change this too
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 482 at r2](https://reviewable.io/reviews/harness/harness-core/44964#-NQUBL8o9Pak9VYFgd8R:-NQjPoQ52IIpB-PTJxgv:b-o56587) ([raw file](https://github.com/harness/harness-core/blob/e8bcb0f79ec8447cf5569ea8d8c22242febdee8b/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L482)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This shouldn't be in K8s group
</blockquote></details>

changed to aws

**Comment by lovish1999** [comment]
trigger ut2

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44964)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44964)* status: Waiting on team(s): del-team.

**Comment by lovish1999** [comment]
trigger compatibility

**Comment by lovish1999** [comment]
trigger compatibility_check

**Comment by abhinavsingh1196** [comment]
trigger codebasehash

**Comment by abhinavsingh1196** [comment]
@harness/del-team please review

**Review by abosii-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44964)* status: 3 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44964)* status: Waiting on team(s): del-team.

**Comment by raghuAtWings** [comment]
*[`930-delegate-tasks/BUILD.bazel` line 81 at r8](https://reviewable.io/reviews/harness/harness-core/44964#-NR4x_tCBsxt-wkrvLzx:-NR4x_tCBsxt-wkrvLzy:bou4y5g) ([raw file](https://github.com/harness/harness-core/blob/2458aec7bcef97f7dd6936ea4c9e96bdf65f279c/930-delegate-tasks/BUILD.bazel#L81)):*
> ```Starlark
>         "@maven//:com_amazonaws_aws_java_sdk_applicationautoscaling",
>         "@maven//:com_amazonaws_aws_java_sdk_cloudwatch",
>         "@maven//:com_amazonaws_aws_java_sdk_eks",
> ```

what version of sdk_eks we are brining in? did we check it for any vulunerability? 



_Code quote:_
```Starlark
com_amazonaws_aws_java_sdk_eks
```

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 2 of 10 files at r1, 4 of 13 files at r2, 3 of 7 files at r3, 2 of 7 files at r4, 1 of 2 files at r5, 4 of 5 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44964)* status: Waiting on team(s): del-team.

**Review by lovish1999 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44964)* status: 1. unresolved discussions. 

___
*[`930-delegate-tasks/BUILD.bazel` line 81 at r8](https://reviewable.io/reviews/harness/harness-core/44964#-NR4x_tCBsxt-wkrvLzx:-NR6tiF1ATcfJAp-wxNG:busnhrp) ([raw file](https://github.com/harness/harness-core/blob/2458aec7bcef97f7dd6936ea4c9e96bdf65f279c/930-delegate-tasks/BUILD.bazel#L81)):*
> com_amazonaws_aws_java_sdk_ek
Yes. It is safe. It  is already being used in some other areas of harness codebase.

**Pull request merged**
