### PR TITLE
[feat]: [CDS-73249]: Fix for handling existing flaw during creation of connectors.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Context: There is a flaw in the UI that user can only git provider URL in place of gitProvider account URL. And then give account username in repo separated by '/'. It is already known Ui fix for this is bigger effort.

Changes: Have made a small tentative fix for it.

Impact: list-user repo Api flow.

Testing: local tested.

Doc has been updated with details of this fix: https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21425979890/GitX+Repo+Allowlist+Setting

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49891)

### CODE REVIEW

**Review by adivishy1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49891)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1243 at r1](https://reviewable.io/reviews/harness/harness-core/49891#-NZ4aVYW4s5qQtGSP2oX:-NZ4aVYW4s5qQtGSP2oY:b-ikgdpk) ([raw file](https://github.com/harness/harness-core/blob/2c05a417ef72ba20b58004c9567c5d7a2ff6f44a/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1243)):*
> ```Java
>     }
> 
>     String repoToValidate = repo;
> ```

this is confusing assigning the variables again, can we use StringBuilder instead?
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1256 at r1](https://reviewable.io/reviews/harness/harness-core/49891#-NZ4_vTZDdXyFSM48t-r:-NZ4_vTZDdXyFSM48t-s:bzh0riu) ([raw file](https://github.com/harness/harness-core/blob/2c05a417ef72ba20b58004c9567c5d7a2ff6f44a/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1256)):*
> ```Java
>     String url = getRepoUrl(scope, connectorRef, repo);
>     List<String> segments = List.of(url.split("/"));
>     return segments.get(segments.size() - 2);
> ```

have you checked the repoUrl for all kinds of git providers and tested for both account and repo type connectors? just want to make sure we dont run into index out of bounds

**Comment by senjucanon2** [comment]
trigger uts

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49891)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1243 at r1](https://reviewable.io/reviews/harness/harness-core/49891#-NZ4aVYW4s5qQtGSP2oX:-NZ4xdY65BJh3T_RkdJb:bmgokzv) ([raw file](https://github.com/harness/harness-core/blob/2c05a417ef72ba20b58004c9567c5d7a2ff6f44a/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1243)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

this is confusing assigning the variables again, can we use StringBuilder instead?
</blockquote></details>

I tried using it but sonar rules suggested using this as a better way, BTW i have removed the verbosity a little to remove confusion
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1256 at r1](https://reviewable.io/reviews/harness/harness-core/49891#-NZ4_vTZDdXyFSM48t-r:-NZ4y3py9_kgf_0iL8_T:b-k8bif1) ([raw file](https://github.com/harness/harness-core/blob/2c05a417ef72ba20b58004c9567c5d7a2ff6f44a/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1256)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

have you checked the repoUrl for all kinds of git providers and tested for both account and repo type connectors? just want to make sure we dont run into index out of bounds
</blockquote></details>

Actually the segments are being generated from the fullRepoUrl and hence there will always be more than 2 segments and we require only the second last one.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1232 at r4](https://reviewable.io/reviews/harness/harness-core/49891#-NZ5HiHd22wQRG-S-j1n:-NZ5HiHd22wQRG-S-j1o:b-pxz7xs) ([raw file](https://github.com/harness/harness-core/blob/f1a2b528b16433e282b9a27ff1bd948855f97a22/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1232)):*
> ```Java
>   }
> 
>   private void validateRepo(Scope scope, String connectorRef, String repo) {
> ```

This complete method can move to gitRepoAllowListHelper I guess.

If any caller just has these params, the logic shall always remain the same to do validation for a repo, thus this shouldn't be in particular service but in a helper.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 114 at r4](https://reviewable.io/reviews/harness/harness-core/49891#-NZ5IDXiBc_QU022U1vP:-NZ5IDXiBc_QU022U1vQ:b-l3earb) ([raw file](https://github.com/harness/harness-core/blob/f1a2b528b16433e282b9a27ff1bd948855f97a22/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L114)):*
> ```Java
>   }
> 
>   public boolean containsInstancesOfReposWithNamespace(List<String> repoAllowlist) {
> ```

lets put explicit check for null or empty allowList

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49891)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 114 at r4](https://reviewable.io/reviews/harness/harness-core/49891#-NZ5IDXiBc_QU022U1vP:-NZ5WF05B4I2awT8Rarc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f1a2b528b16433e282b9a27ff1bd948855f97a22/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L114)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets put explicit check for null or empty allowList
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1232 at r4](https://reviewable.io/reviews/harness/harness-core/49891#-NZ5HiHd22wQRG-S-j1n:-NZ5WVf57MDE-zLFAitX:b-mdzzud) ([raw file](https://github.com/harness/harness-core/blob/f1a2b528b16433e282b9a27ff1bd948855f97a22/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1232)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This complete method can move to gitRepoAllowListHelper I guess.

If any caller just has these params, the logic shall always remain the same to do validation for a repo, thus this shouldn't be in particular service but in a helper.
</blockquote></details>

As discussed on call we have a method being called in this method which in turns call a d=service method that why it is in this method.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1253 at r4](https://reviewable.io/reviews/harness/harness-core/49891#-NZ5HyEj49gzqqSCqaif:-NZ5XQxQDrtH0BguieUD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f1a2b528b16433e282b9a27ff1bd948855f97a22/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1253)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Better method name would be : "getCompleteRepoName()" or something similar.
</blockquote></details>

Done.

**Comment by senjucanon2** [comment]
trigger review

**Comment by senjucanon2** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1253 at r4](https://reviewable.io/reviews/harness/harness-core/49891#-NZ5HyEj49gzqqSCqaif:-NZAQBZYCSqrhVh1uAmK:b-4zjq8o) ([raw file](https://github.com/harness/harness-core/blob/f1a2b528b16433e282b9a27ff1bd948855f97a22/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1253)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This shouldn't be here. Its pretty generic utility component. Should be inside GitRepoHelper

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49891)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1253 at r4](https://reviewable.io/reviews/harness/harness-core/49891#-NZ5HyEj49gzqqSCqaif:-NZASPS-8m6PXiZgB_cD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f1a2b528b16433e282b9a27ff1bd948855f97a22/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1253)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This shouldn't be here. Its pretty generic utility component. Should be inside GitRepoHelper
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 7 files at r6, 3 of 4 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49891)* status: 8 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by senjucanon2** [comment]
trigger uts

**Review by adivishy1 — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 2 of 7 files at r6, 3 of 4 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49891)* status: :shipit: complete! ✓

**Comment by senjucanon2** [comment]
trigger review

**Comment by senjucanon2** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49891)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by sourabh-awashti — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 7 files at r6, 2 of 4 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49891)* status: :shipit: complete! ✓

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
