### PR TITLE
feat: [DEL-4418]: Support to broadcast/assign/execute task on harness hosted delegate

### PR DESCRIPTION
**Pull request by jennyjames21**
…outing

## Describe your changes
Summary:
1) Adding support of global harness delegate to support harness hosted multi tenant delegates
2) Ability to route task to harness hosted delegate based on option provided to customer. 
3) if executeOnHarnessHostedDelegate flag is true then task processing, routing, broadcasting, assignment and execution will be on global harness delegate
4) For such scenarios we also stores customer accountId as secondary account Id.

## Checklist
- [ X] I've documented the changes in the PR description.
- [ X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35341)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
image

**Comment by jennyjames21** [comment]
image

**Comment by jennyjames21** [comment]
image

**Comment by jennyjames21** [comment]
image

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35341)

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 435 at r3](https://reviewable.io/reviews/harness/harness-core/35341#-N9DXf7d8dY_xstKYjYb:-N9DXf7d8dY_xstKYjYc:bkwgwe9) ([raw file](https://github.com/harness/harness-core/blob/38db68df6cba735fd49d8856e7fbf04732140680/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L435)):*
> ```Java
>     if (task.isExecuteOnHarnessHostedDelegates()) {
>       task.setSecondaryAccountId(task.getAccountId());
>       task.setAccountId(GLOBAL_DELEGATE_ACCOUNT_ID);
> ```

as discussed, lets not hardcode the account

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35341)* status: 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
trigger codeformat

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java` line 207 at r5](https://reviewable.io/reviews/harness/harness-core/35341#-N9IpRRmEgI9FIlQvlpF:-N9IpRRmEgI9FIlQvlpG:bbfdknu) ([raw file](https://github.com/harness/harness-core/blob/ef6c8ca47fd60ef84d915247cd548eb0e8cdc6c7/400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java#L207)):*
> ```Java
>       return null;
>     }
>     return createAccount(account, adminUserEmail);
> ```

where do we set the global flag to be true?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 439 at r5](https://reviewable.io/reviews/harness/harness-core/35341#-N9IpcOl75cHFF072QjJ:-N9IpcOl75cHFF072QjK:bl23u10) ([raw file](https://github.com/harness/harness-core/blob/ef6c8ca47fd60ef84d915247cd548eb0e8cdc6c7/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L439)):*
> ```Java
>         task.setAccountId(globalDelegateAccount);
>       }
>     }
> ```

there should be an else case here, if the executeOnHosted is true but there is no global account created, we should fail with right error message

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 2055 at r5](https://reviewable.io/reviews/harness/harness-core/35341#-N9IpnJA4zB4feUtvfbg:-N9IpnJA4zB4feUtvfbh:b-nhzk5d) ([raw file](https://github.com/harness/harness-core/blob/ef6c8ca47fd60ef84d915247cd548eb0e8cdc6c7/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L2055)):*
> ```Java
>   @Override
>   public Optional<Account> getGlobalDelegateAccount() {
>     Account account = wingsPersistence.createQuery(Account.class, excludeAuthorityCount)
> ```

we should also put this in cache since this will be queried a lot

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/software/wings/service/impl/DelegateTaskObserver.java` line 4 at r5](https://reviewable.io/reviews/harness/harness-core/35341#-N9IpxPB3UMaWPOJ0l9_:-N9IpxPB3UMaWPOJ0l9a:bqkv6pk) ([raw file](https://github.com/harness/harness-core/blob/ef6c8ca47fd60ef84d915247cd548eb0e8cdc6c7/420-delegate-service/src/main/java/software/wings/service/impl/DelegateTaskObserver.java#L4)):*
> ```Java
> 
> public interface DelegateTaskObserver {
>   void onTaskAssigned(String accountId, String taskId, String delegateId);
> ```

i don't follow how this works? what will the CI team needs to do for getting the event?

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java` line 207 at r5](https://reviewable.io/reviews/harness/harness-core/35341#-N9IpRRmEgI9FIlQvlpF:-N9IqA-6955MzD46m_aq:b-onqrik) ([raw file](https://github.com/harness/harness-core/blob/ef6c8ca47fd60ef84d915247cd548eb0e8cdc6c7/400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java#L207)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

where do we set the global flag to be true?
</blockquote></details>

on postman call Body Account 
 @POST
  @Path("/global")
  public RestResponse<Account> createGlobalDelegateAccount(
      @Body Account account, @QueryParam("adminUserEmail") String adminUserEmail) {
    return new RestResponse<>(adminAccountService.createAccount(account, adminUserEmail));
  }

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 2055 at r5](https://reviewable.io/reviews/harness/harness-core/35341#-N9IpnJA4zB4feUtvfbg:-N9IqUns24vZFb08oeb_:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/ef6c8ca47fd60ef84d915247cd548eb0e8cdc6c7/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L2055)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should also put this in cache since this will be queried a lot
</blockquote></details>

yes

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 435 at r3](https://reviewable.io/reviews/harness/harness-core/35341#-N9DXf7d8dY_xstKYjYb:-N9IqY--8TZq4tDypdcu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/38db68df6cba735fd49d8856e7fbf04732140680/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L435)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

as discussed, lets not hardcode the account
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 439 at r5](https://reviewable.io/reviews/harness/harness-core/35341#-N9IpcOl75cHFF072QjJ:-N9ItJXe1u1VYuRqd3Ku:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/ef6c8ca47fd60ef84d915247cd548eb0e8cdc6c7/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L439)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

there should be an else case here, if the executeOnHosted is true but there is no global account created, we should fail with right error message
</blockquote></details>

updated

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/software/wings/service/impl/DelegateTaskObserver.java` line 4 at r5](https://reviewable.io/reviews/harness/harness-core/35341#-N9IpxPB3UMaWPOJ0l9_:-N9ItLUO8UvafbGgXohE:b-moqcy7) ([raw file](https://github.com/harness/harness-core/blob/ef6c8ca47fd60ef84d915247cd548eb0e8cdc6c7/420-delegate-service/src/main/java/software/wings/service/impl/DelegateTaskObserver.java#L4)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

i don't follow how this works? what will the CI team needs to do for getting the event?
</blockquote></details>

yes they need to implement observer to perform action needed on their side

**Comment by jennyjames21** [comment]
trigger ti2

**Comment by jennyjames21** [comment]
trigger ti2

**Comment by jennyjames21** [comment]
trigger ti0

**Comment by jennyjames21** [comment]
trigger ti1

**Comment by jennyjames21** [comment]
trigger ti2

**Comment by jennyjames21** [comment]
trigger ti3

**Comment by jennyjames21** [comment]
trigger ti4

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java` line 207 at r5](https://reviewable.io/reviews/harness/harness-core/35341#-N9IpRRmEgI9FIlQvlpF:-N9XCLs-8cfvQDsbPHz6:b-bg2jk1) ([raw file](https://github.com/harness/harness-core/blob/ef6c8ca47fd60ef84d915247cd548eb0e8cdc6c7/400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java#L207)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

on postman call Body Account 
 @POST
  @Path("/global")
  public RestResponse<Account> createGlobalDelegateAccount(
      @Body Account account, @QueryParam("adminUserEmail") String adminUserEmail) {
    return new RestResponse<>(adminAccountService.createAccount(account, adminUserEmail));
  }
</blockquote></details>

why make the callers responsible to set the flag? why not set it in the method so callers only care about calling the right end point?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/beans/Account.java` line 776 at r8](https://reviewable.io/reviews/harness/harness-core/35341#-N9XCd9q8StdikbNZijY:-N9XCd9q8StdikbNZijZ:b-mchm1z) ([raw file](https://github.com/harness/harness-core/blob/6b1c5759049b59e2caedc7afe2856642b3ce503b/400-rest/src/main/java/software/wings/beans/Account.java#L776)):*
> ```Java
>     }
> 
>     public Builder withGlobalDelegateAccount(boolean globalDelegateAccount) {
> ```

do we need this?



_Code quote:_
```Java
withGlobalDelegateAccount
```

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 2055 at r5](https://reviewable.io/reviews/harness/harness-core/35341#-N9IpnJA4zB4feUtvfbg:-N9XCiPi2JC-jy6i6nzg:b-mqcd75) ([raw file](https://github.com/harness/harness-core/blob/ef6c8ca47fd60ef84d915247cd548eb0e8cdc6c7/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L2055)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

yes
</blockquote></details>

we shouldn't need this method now right?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/intfc/AccountService.java` line 262 at r8](https://reviewable.io/reviews/harness/harness-core/35341#-N9XCsvD63KaAyWjrDf_:-N9XCsvD63KaAyWjrDfa:byfox7n) ([raw file](https://github.com/harness/harness-core/blob/6b1c5759049b59e2caedc7afe2856642b3ce503b/400-rest/src/main/java/software/wings/service/intfc/AccountService.java#L262)):*
> ```Java
>   boolean isAccountActivelyUsed(String accountId);
> 
>   Optional<Account> getGlobalDelegateAccount();
> ```

do we need this now?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 6 of 10 files at r4, 1 of 3 files at r5, 8 of 8 files at r6, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35341)* status: 2. unresolved discussions. 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java` line 207 at r5](https://reviewable.io/reviews/harness/harness-core/35341#-N9IpRRmEgI9FIlQvlpF:-N9XWzTo3KRt5b8q_dWK:b-m4jnv0) ([raw file](https://github.com/harness/harness-core/blob/ef6c8ca47fd60ef84d915247cd548eb0e8cdc6c7/400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java#L207)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why make the callers responsible to set the flag? why not set it in the method so callers only care about calling the right end point?
</blockquote></details>

that's how other account API's follow, good to be consistent. And it's done by harness admins only and one time in each cluster

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 2055 at r5](https://reviewable.io/reviews/harness/harness-core/35341#-N9IpnJA4zB4feUtvfbg:-N9XXKP64wqTSq4sdul9:bcf5q1o) ([raw file](https://github.com/harness/harness-core/blob/ef6c8ca47fd60ef84d915247cd548eb0e8cdc6c7/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L2055)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we shouldn't need this method now right?
</blockquote></details>

yes, will remove

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/intfc/AccountService.java` line 262 at r8](https://reviewable.io/reviews/harness/harness-core/35341#-N9XCsvD63KaAyWjrDf_:-N9XXOc96nQsrgIUumrS:b32w12) ([raw file](https://github.com/harness/harness-core/blob/6b1c5759049b59e2caedc7afe2856642b3ce503b/400-rest/src/main/java/software/wings/service/intfc/AccountService.java#L262)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

do we need this now?
</blockquote></details>

No

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35341)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
trigger ti0

**Comment by jennyjames21** [comment]
trigger codebasehash

**Comment by jennyjames21** [comment]
trigger codebasehash

**Pull request merged**
