### PR TITLE
feat: [CVS-9179]: Added Debug API for Verify Step

### PR DESCRIPTION
**Pull request by arpit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31095)

### CODE REVIEW

**Comment by arpit-harness** [comment]
trigger messagecheck

**Comment by arpit-harness** [comment]
trigger ti2

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31095)* status: 10 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[120-ng-manager/config.yml, line 241 at r1](https://reviewable.io/reviews/harness/harness-core/31095#-MxDoBsX2R4OfVaqg679:-MxDoBsX2R4OfVaqg67A:b-z95pa4) ([raw file](https://github.com/harness/harness-core/blob/b2ce6a21fab31857edd8f96e8b09a16c62fa9dd8/120-ng-manager/config.yml#L241)):*
> 120-ng-manager/config.yml
Dont push config changes, Revert these
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java, line 240 at r1](https://reviewable.io/reviews/harness/harness-core/31095#-MxDopm-1PyMdGMU5y8v:-MxDopm-1PyMdGMU5y8w:b-tejd9g) ([raw file](https://github.com/harness/harness-core/blob/b2ce6a21fab31857edd8f96e8b09a16c62fa9dd8/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java#L240)):*
> ```Java
> 
>   @Override
>   public List<DataCollectionTask> getAllDataCollectionTasks(String accountId, String verificationTaskId) {
> ```

Write a test case for this

**Review by AbhijithHarness — DISMISSED** [review]
> Reviewed 8 of 10 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31095)* status: :shipit: complete! ✓

**Comment by arpit-harness** [comment]
trigger ti2

**Review by AbhijithHarness — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31095)* status: 0 of 1 approvals obtained.

**Review by AbhijithHarness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31095)* status: :shipit: complete! ✓

**Comment by arpit-harness** [comment]
trigger ti2

**Comment by arpit-harness** [comment]
trigger ti4

**Comment by arpit-harness** [comment]
trigger ti2

**Comment by arpit-harness** [comment]
trigger ti4

**Pull request merged**
