### PR TITLE
techdebt: [SPG-1027]: Move wait notify notifications to events framework

### PR DESCRIPTION
**Pull request by hextechpal**
## Describe your changes

Currently notify queue collection is maintained in mongo and we run periodic job over the records. In order to acquire the record we update it and hence it causes conflicts among the pods. 

This PR moved the notify queue records to redis making the collection and the records obsolete.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40517)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 18 files at r1, 2 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40517)* status: 15 file(s) to review. 0 of 1 approvals obtained. 

___
*[`953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/40517#-NHUtv2n23XAa7BpJGit:-NHUtv2n23XAa7BpJGiu:b-1pnt04) ([raw file](https://github.com/harness/harness-core/blob/e445c083aecf16aabd3e94bb29e56828d7f10980/953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java#L175)):*
> ```Java
> 
>   public static final String CG_NOTIFY_EVENT = "cg_notify_event";
>   public static final int CG_NOTIFY_EVENT_TOPIC_SIZE = 100000;
> ```

As we are adding new stream to existing redis, can we add and get approval from PL team for redis data estimation https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21202436122/Redis+Event+Framework+Usage

**Review by archit-harness — DISMISSED** [review]
> Reviewed 10 of 18 files at r1, 5 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40517)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 11 of 18 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40517)* status: :shipit: complete! ✓

**Review by hextechpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40517)* status: 13 file(s) to review. 0 of 1 approvals obtained. 

___
*[`953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/40517#-NHUtv2n23XAa7BpJGit:-NHXzLxH57kz5SihlOiI:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e445c083aecf16aabd3e94bb29e56828d7f10980/953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java#L175)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

As we are adding new stream to existing redis, can we add and get approval from PL team for redis data estimation https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21202436122/Redis+Event+Framework+Usage
</blockquote></details>

Done

**Review by archit-harness — APPROVED** [review]
> Reviewed 11 of 13 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40517)* status: :shipit: complete! ✓

**Review by manjunatha-etagi — APPROVED** [review]
> Reviewed 5 of 18 files at r1, 2 of 7 files at r2, 11 of 13 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40517)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 5 of 18 files at r1, 2 of 7 files at r2, 11 of 13 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40517)* status: :shipit: complete! ✓

**Pull request merged**
