### PR TITLE
feat: [SRM-11160]: Added SLO Disabling feature

### PR DESCRIPTION
**Pull request by arpit-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36006)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 12 Issues 
* Code issue 11 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36006)

**Comment by arpit-harness** [comment]
trigger ti2

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36006)* status: Some of the checks are too old. 21 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/EntityDisableTime.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/36006#-N9FQwzhBzbq4ts0vtmP:-N9FQwzhBzbq4ts0vtmQ:b-x5pjna) ([raw file](https://github.com/harness/harness-core/blob/9f77fbde6a835440a89b822adc51c17c1d26f944/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/EntityDisableTime.java#L42)):*
> ```Java
> @StoreIn(DbAliases.CVNG)
> public class EntityDisableTime
>     implements PersistentEntity, UuidAware, AccountAccess, UpdatedAtAware, CreatedAtAware, PersistentRegularIterable {
> ```

we don't need PersistentRegularIterable



_Code quote:_
```Java
PersistentRegularIterable
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/EntityDisableTime.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/36006#-N9FSYiMDQKSc-1MeJ66:-N9FSYiMDQKSc-1MeJ67:b5ksya) ([raw file](https://github.com/harness/harness-core/blob/9f77fbde6a835440a89b822adc51c17c1d26f944/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/EntityDisableTime.java#L44)):*
> ```Java
>     implements PersistentEntity, UuidAware, AccountAccess, UpdatedAtAware, CreatedAtAware, PersistentRegularIterable {
>   @Id private String uuid;
>   String entityUUID;
> ```

let's add the indexing on entityUuid and account id.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/EntityDisabledTimeServiceImpl.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/36006#-N9FSs-z0Dt1IM6VZYfF:-N9FSs-z0Dt1IM6VZYfG:bk38d71) ([raw file](https://github.com/harness/harness-core/blob/9f77fbde6a835440a89b822adc51c17c1d26f944/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/EntityDisabledTimeServiceImpl.java#L27)):*
> ```Java
>   @Override
>   public void save(EntityDisableTime entityDisableTime) {
>     hPersistence.save(EntityDisableTime.builder()
> ```

save the entityDisable time directly.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 1253 at r2](https://reviewable.io/reviews/harness/harness-core/36006#-N9FT1tSEwhrwO4ILzvo:-N9FT1tT1KSIZp7e4T3Y:b-xwer9m) ([raw file](https://github.com/harness/harness-core/blob/9f77fbde6a835440a89b822adc51c17c1d26f944/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L1253)):*
> ```Java
>     serviceLevelIndicatorService.setMonitoredServiceSLIsEnableFlag(
>         projectParams, monitoredService.getIdentifier(), enable);
>     if (enable && cvngMigrationService.getCVNGSchemaVersion() == 51) {
> ```

lets move to feature flag for this check would be cleaner

**Review by deepak-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36006)* status: Some of the checks are too old. 21 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImpl.java` line 263 at r2](https://reviewable.io/reviews/harness/harness-core/36006#-N9FW3nJ8b2wvthexnQi:-N9FW3nJ8b2wvthexnQj:b-qzzmmt) ([raw file](https://github.com/harness/harness-core/blob/9f77fbde6a835440a89b822adc51c17c1d26f944/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImpl.java#L263)):*
> ```Java
>       long y = disableTimes.get(currentRange).getEndTime();
> 
>       x = (long) (Math.ceil(x / 60000) * 60000);
> ```

nit: let's discuss, IF can be simplified.

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36006)* status: Some of the checks are too old. 23 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/EntityDisableTime.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/36006#-N9FSYiMDQKSc-1MeJ66:-NADQvOu0PriYbHZDgW9:bfybfm) ([raw file](https://github.com/harness/harness-core/blob/9f77fbde6a835440a89b822adc51c17c1d26f944/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/EntityDisableTime.java#L44)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

let's add the indexing on entityUuid and account id.
</blockquote></details>

Please add an index on entityUuid, startTime and endTime.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 14 of 21 files at r1, 2 of 2 files at r2, 5 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36006)* status: :shipit: complete! ✓

**Pull request merged**
