### PR TITLE
feat: [SRM-10573]: Save Template Identifier in MonitoredService

### PR DESCRIPTION
**Pull request by AbhijithHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33152)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33152)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/MonitoredServiceDTO.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/33152#-N25une50MWYRfGsO4sS:-N25une50MWYRfGsO4sT:b-wtxijp) ([raw file](https://github.com/harness/harness-core/blob/8001842939f2d1775d38b0a00bc11a8382babda7/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/MonitoredServiceDTO.java#L54)):*
> ```Java
>   @Valid Set<ServiceDependencyDTO> dependencies;
>   List<NotificationRuleRefDTO> notificationRuleRefs;
>   String templateIdentifier;
> ```

shouldn't we follow the same convention as pipeline 
something like
```
monitoredService:
  template:
    templateRef: "template",
    versionLabel: "v1"
```

**Review by AbhijithHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33152)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/MonitoredServiceDTO.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/33152#-N25une50MWYRfGsO4sS:-N262SXw4TgNKYoWuxAm:b-v96gz4) ([raw file](https://github.com/harness/harness-core/blob/8001842939f2d1775d38b0a00bc11a8382babda7/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/MonitoredServiceDTO.java#L54)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

shouldn't we follow the same convention as pipeline 
something like
```
monitoredService:
  template:
    templateRef: "template",
    versionLabel: "v1"
```

</blockquote></details>

I dont think there is a pipeline equivalent for this. Our yaml will still look the above, which template service will understand. This DTO is what we return back to UI.

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33152#-:-N29mjtN8UKBysdMcjPk:bnfp4nl)* status: :shipit: complete! ✓

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Pull request merged**
