### PR TITLE
[feat]: [PLG-2970]: added support for developerLicenses in ModuleLicense

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
Case 1:
API: CREATE License with both developerLicenses and workloads
{
    "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
    "moduleType": "CD",
    "edition": "ENTERPRISE",
    "licenseType": "TRIAL",
    "status": "ACTIVE",
    "startTime": "1699621448000",
    "expiryTime": "1731243848000",
    "workloads": "100",
    "cdLicenseType": "SERVICES",
    "selfService": false,
    "developerLicenses": "100"
}

Response:
{
    "metaData": null,
    "resource": null,
    "responseMessages": [
        {
            "code": "INVALID_FORMAT",
            "level": "ERROR",
            "message": "Invalid format of YAML payload: HTTP Error Status (400 - Invalid Format) received. Invalid request: Both numberOfDevelopers and workloads/serviceInstances cannot be part of the input!",
            "exception": null,
            "failureTypes": []
        }
    ]
}

Case 2: 
API: CREATE License with only workloads
{
    "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
    "moduleType": "CD",
    "edition": "ENTERPRISE",
    "licenseType": "TRIAL",
    "status": "ACTIVE",
    "startTime": "1699621448000",
    "expiryTime": "1731243848000",
    "workloads": "100",
    "cdLicenseType": "SERVICES",
    "selfService": false
}

Response: successfully created license with secondary entitlements
{
    "metaData": {},
    "resource": {
        "id": "654e2d9baf523f31beb2fc2f",
        "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
        "moduleType": "CD",
        "edition": "ENTERPRISE",
        "licenseType": "TRIAL",
        "status": "ACTIVE",
        "startTime": 1699621448000,
        "expiryTime": 1731243848000,
        "premiumSupport": false,
        "selfService": false,
        "createdAt": 1699622298876,
        "lastModifiedAt": 1699622298876,
        "cdLicenseType": "SERVICES",
        "workloads": 100
    },
    "responseMessages": []
}

Case 3:
API: CREATE License with only developerLicenses and cdLicenseType="SERVICES"
{
    "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
    "moduleType": "CD",
    "edition": "ENTERPRISE",
    "licenseType": "TRIAL",
    "status": "ACTIVE",
    "startTime": "1699621448000",
    "expiryTime": "1731243848000",
    "developerLicenses": "100",
    "cdLicenseType": "SERVICES",
    "selfService": false
}

Response: successfully created license from developerLicenses with cdLicenseType="SERVICES"
{
    "metaData": {},
    "resource": {
        "id": "654e304c672b7b415f921f60",
        "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
        "moduleType": "CD",
        "edition": "ENTERPRISE",
        "licenseType": "TRIAL",
        "status": "ACTIVE",
        "startTime": 1699621448000,
        "expiryTime": 1731243848000,
        "premiumSupport": false,
        "selfService": false,
        "createdAt": 1699622988498,
        "lastModifiedAt": 1699622988498,
        "developerLicenses": 100,
        "cdLicenseType": "SERVICES",
        "workloads": 100
    },
    "responseMessages": []
}

Case 4:
API: CREATE License with only developerLicenses and cdLicenseType="SERVICE_INSTANCES"
{
    "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
    "moduleType": "CD",
    "edition": "ENTERPRISE",
    "licenseType": "TRIAL",
    "status": "ACTIVE",
    "startTime": "1699621448000",
    "expiryTime": "1731243848000",
    "developerLicenses": "100",
    "cdLicenseType": "SERVICE_INSTANCES",
    "selfService": false
}

Response: successfully created license from developerLicenses with cdLicenseType="SERVICE_INSTANCES"
{
    "metaData": {},
    "resource": {
        "id": "654e3489672b7b415f921f64",
        "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
        "moduleType": "CD",
        "edition": "ENTERPRISE",
        "licenseType": "TRIAL",
        "status": "ACTIVE",
        "startTime": 1699621448000,
        "expiryTime": 1731243848000,
        "premiumSupport": false,
        "selfService": false,
        "createdAt": 1699624073474,
        "lastModifiedAt": 1699624073474,
        "developerLicenses": 100,
        "cdLicenseType": "SERVICE_INSTANCES",
        "serviceInstances": 100
    },
    "responseMessages": []
}

Case 5:
API: CREATE License with FF PLG_DEVELOPER_LICENSING=disbaled and developerLicenses!= null

Response: 
{
    "metaData": null,
    "resource": null,
    "responseMessages": [
        {
            "code": "INVALID_FORMAT",
            "level": "ERROR",
            "message": "Invalid format of YAML payload: HTTP Error Status (400 - Invalid Format) received. Invalid request: New Developer Licensing feature is not enabled for this account!",
            "exception": null,
            "failureTypes": []
        }
    ]
}

Case 6:
API: UPDATE License
{
    "id": "654e62873bcc9b12a8aac124",
    "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
    "moduleType": "CD",
    "edition": "ENTERPRISE",
    "licenseType": "TRIAL",
    "status": "ACTIVE",
    "startTime": "1699621448000",
    "expiryTime": "1731243848000",
    "developerLicenses": "200",
    "serviceInstances": "100",
    "cdLicenseType": "SERVICE_INSTANCES",
    "selfService": false
}

Response:
{
    "metaData": null,
    "resource": null,
    "responseMessages": [
        {
            "code": "INVALID_FORMAT",
            "level": "ERROR",
            "message": "Invalid format of YAML payload: HTTP Error Status (400 - Invalid Format) received. Invalid request: Both numberOfDevelopers and workloads/serviceInstances cannot be part of the input!",
            "exception": null,
            "failureTypes": []
        }
    ]
}

Case 7:
API: UPDATE License
{
    "id": "654e62873bcc9b12a8aac124",
    "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
    "moduleType": "CD",
    "edition": "ENTERPRISE",
    "licenseType": "TRIAL",
    "status": "ACTIVE",
    "startTime": "1699621448000",
    "expiryTime": "1731243848000",
    "developerLicenses": "200",
    "cdLicenseType": "SERVICE_INSTANCES",
    "selfService": false
}

Response: successfully updated license
{
    "metaData": {},
    "resource": {
        "id": "654e62873bcc9b12a8aac124",
        "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
        "moduleType": "CD",
        "edition": "ENTERPRISE",
        "licenseType": "TRIAL",
        "status": "ACTIVE",
        "startTime": 1699621448000,
        "expiryTime": 1731243848000,
        "premiumSupport": false,
        "selfService": false,
        "createdAt": 1699635847762,
        "lastModifiedAt": 1699636584251,
        "developerLicenses": 200,
        "cdLicenseType": "SERVICE_INSTANCES",
        "serviceInstances": 200
    },
    "responseMessages": []
}

Case 7: 
API: DELETE License

Response: successfully deleted license

Case 8: GET License 

Response: successfully returns the list of licenses for that accountId

Case 9:
API: CREATE FREE License https://localhost:8181/ng/api/licenses/free?accountIdentifier=kmpySmUISimoRrJL6NL73w&routingId=kmpySmUISimoRrJL6NL73w&moduleType=CD

Response:
{
    "status": "SUCCESS",
    "data": {
        "id": "6552abed8f85f845a746c68d",
        "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
        "moduleType": "CD",
        "edition": "FREE",
        "status": "ACTIVE",
        "startTime": 1699916745770,
        "expiryTime": 9223372036854775807,
        "premiumSupport": false,
        "selfService": false,
        "createdAt": 1699916781088,
        "lastModifiedAt": 1699916781088,
        "cdLicenseType": "SERVICES",
        "workloads": 5
    },
    "metaData": null,
    "correlationId": "d8f617ee-2844-4395-a42c-ca05b08e3bdb"
}

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55359)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger uts

**Comment by kapil-harness** [comment]
trigger checkstylecodeformat,messagecheck,codebasehash,pmd,commonchecks

**Review by mohitg0795 — APPROVED** [review]

**Comment by kapil-harness** [comment]
trigger review

**Review by kapilgarg1996 — APPROVED** [review]

**Comment by kapil-harness** [comment]
trigger review

**Pull request merged**
