### PR TITLE
fix: [CDS-47907]: added code to decrypt encrypted details

### PR DESCRIPTION
**Pull request by achyuth-harness**
## Describe your changes
Added decryption for HELM_FETCH_CHART_VERSIONS_TASK_NG task.

Before fix:
image

After fix:
image

Automation added: UT and API automation (https://github.com/wings-software/Automation/pull/3831)
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41208)

### CODE REVIEW

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Review by abosii-harness — APPROVED** [review]
Did we tested this with anonymous repo?

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41208#-:-NIpn7Z51sX81l02atdu:b-ls2b5t)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41208)* status: 2 file(s) to review. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmFetchChartVersionTaskNG.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/41208#-NIpwUQkDOFBIAJ1DkRu:-NIpwUQkDOFBIAJ1DkRv:b-wohhel) ([raw file](https://github.com/harness/harness-core/blob/880a2bc21c6422534f307bfbb63977d9bf13c96c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmFetchChartVersionTaskNG.java#L83)):*
> ```Java
>   }
> 
>   public String getDestinationDirectory(StoreDelegateConfig storeDelegateConfig) throws IOException {
> ```

nit: Wouldn't it be enough to make it package-private rather than public?



_Code quote:_
```Java
 public
```

**Review by achyuth-harness — COMMENTED** [review]
Yes:


> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41208#-:-NIpzX_aB0baEjTrTarL:b2cgdlm)* status: 2 file(s) to review.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41208)* status: :shipit: complete! ✓

**Pull request merged**
