### PR TITLE
feat: [CDS-56685]: NG Rancher connector connection test beans

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
## Describe your changes
This change contains the delegate task beans for Rancher connector, along with the actual connection test delegate task. 
Currently, the task is registered as unsupported. This feature will be behind a FF anyway, so these changes should be safe to merge.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48253)

### CODE REVIEW

**Comment by abhinavsingh1196** [comment]
trigger uts

**Review by abosii-harness — APPROVED** [review]

**Review by abosii-harness — APPROVED** [review]

**Comment by abhinavsingh1196** [comment]
trigger uts

**Review by GoelPratyush99 — APPROVED** [review]

**Review by TarunUba1 — APPROVED** [review]

**Review by TarunUba1 — APPROVED** [review]

**Comment by abhinavsingh1196** [comment]
trigger review

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 11 of 25 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48253)* status: 26 file(s) to review. 1 change requests. Waiting on team(s): del-team. 

___
*[`960-api-services/src/main/java/io/harness/rancher/BUILD.bazel` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/48253#-NWD1seK7ChQH-wwT6D4:-NWD1seK7ChQH-wwT6D5:bobcvop) ([raw file](https://github.com/harness/harness-core/blob/8d7db2f74ec2e1d27055c69720daf7de9201ee25/960-api-services/src/main/java/io/harness/rancher/BUILD.bazel#L16)):*
> ```Starlark
>         "//:lombok",
>         "//930-delegate-tasks/src/main/java/io/harness/http:module",
>         "//930-delegate-tasks/src/main/java/io/harness/http/beans:module",
> ```

960 module can only depend on the higher number modules, it can't depend on 954 and 930. This would cause cyclic dependency 
___
*[`960-api-services/src/main/java/io/harness/rancher/BUILD.bazel` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/48253#-NWD2EfL8-JKLQP8qCxF:-NWD2EfL8-JKLQP8qCxG:b-ul6cny) ([raw file](https://github.com/harness/harness-core/blob/8d7db2f74ec2e1d27055c69720daf7de9201ee25/960-api-services/src/main/java/io/harness/rancher/BUILD.bazel#L22)):*
> ```Starlark
>         "@maven//:com_google_inject_guice",
>         "@maven//:com_intellij_annotations",
>         "@maven//:org_apache_httpcomponents_httpcore",
> ```

it's generally wrong to use intellij annotations (they sometimes get imported by accident like intellijs @nonNull) , but also both that one and httpcore don't seem to be used.

**Review by abhinavsingh1196 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48253)* status: 26 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/rancher/BUILD.bazel` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/48253#-NWD1seK7ChQH-wwT6D4:-NWDBFAI9RrSGBX0Zy7j:blpw6mz) ([raw file](https://github.com/harness/harness-core/blob/8d7db2f74ec2e1d27055c69720daf7de9201ee25/960-api-services/src/main/java/io/harness/rancher/BUILD.bazel#L16)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

960 module can only depend on the higher number modules, it can't depend on 954 and 930. This would cause cyclic dependency 
</blockquote></details>

Nice catch :) 
Fixed it.
___
*[`960-api-services/src/main/java/io/harness/rancher/BUILD.bazel` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/48253#-NWD2EfL8-JKLQP8qCxF:-NWDBJv_AAtz2lWEI20d:b90g4u5) ([raw file](https://github.com/harness/harness-core/blob/8d7db2f74ec2e1d27055c69720daf7de9201ee25/960-api-services/src/main/java/io/harness/rancher/BUILD.bazel#L22)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

it's generally wrong to use intellij annotations (they sometimes get imported by accident like intellijs @nonNull) , but also both that one and httpcore don't seem to be used. 
</blockquote></details>

Removed these unused dependencies.

**Comment by abhinavsingh1196** [comment]
trigger uts

**Review by GoelPratyush99 — APPROVED** [review]

**Review by abosii-harness — APPROVED** [review]

**Pull request merged**
