### PR TITLE
[fix]: [CDS-79084]: Moving the planExecutionSummary status updates to graphGenerationService instead of doing via observer and some refactoring for pipeline chaining

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Moving the planExecutionSummary status updates to graphGenerationService instead of doing via observer and some refactoring for pipeline chaining.

Changes:

- Moved the planExecutionSummary status updates to graphGenerationService instead of doing via pipelineStatusUpdate observer. So that all the graph updates happen from the graphGenerationService only.
  -  This will save some DB calls as well because in graphGenerationService, all updates are happening in one operation and we added our updates in the same operations.
- Moved the notify for parent pipeline to PlanExecutionServiceImpl from the pipelineStatusUpdate observer.

Testing:

- Tested that the pipeline status is updating in the graph fine.
- Tested that the parent pipeline is being notified on completion of child pipeline.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52950)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/PlanExecutionStatusUpdateEventHandler.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/52950#-NeMyCG6BS4f7r20SDDj:-NeMyCG6BS4f7r20SDDk:b9cmtrq) ([raw file](https://github.com/harness/harness-core/blob/916c83e5dae42e9934bf0f612a88f18d33dba3e0/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/PlanExecutionStatusUpdateEventHandler.java#L39)):*
> ```Java
>     PlanExecution planExecution = planExecutionService.get(planExecutionId);
>     try {
>       updatePlanExecutionSummary(planExecution, summaryEntityUpdate);
> ```

Please add this in PmsExecutionSummaryService and call that in graphGEnerationService directly.
This class should not update the summary directly.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java` line 176 at r2](https://reviewable.io/reviews/harness/harness-core/52950#-NeMyMU018xuTbQ4gfou:-NeMyMU018xuTbQ4gfov:bfomsbk) ([raw file](https://github.com/harness/harness-core/blob/916c83e5dae42e9934bf0f612a88f18d33dba3e0/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L176)):*
> ```Java
>       switch (orchestrationEventType) {
>         case PLAN_EXECUTION_STATUS_UPDATE:
>           orchestrationGraph = planExecutionStatusUpdateEventHandler.handleEvent(
> ```

Please call pmsExecutionSummaryService here.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/PipelineStatusUpdateEventHandler.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/52950#-NeMyXVmB0oSSaLRqOoj:-NeMyXVmB0oSSaLRqOok:b-3zgzsb) ([raw file](https://github.com/harness/harness-core/blob/916c83e5dae42e9934bf0f612a88f18d33dba3e0/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/PipelineStatusUpdateEventHandler.java#L59)):*
> ```Java
> 
>   @Override
>   public void onPlanStatusUpdate(Ambiance ambiance) {
> ```

Can we remove this function altogether?

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 4 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52950)* status: 14 file(s) to review. 0 of 2 approvals obtained.

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52950)* status: 16 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/PlanExecutionStatusUpdateEventHandler.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/52950#-NeMyCG6BS4f7r20SDDj:-NeN8rtBEZyMsxVjyjPi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/916c83e5dae42e9934bf0f612a88f18d33dba3e0/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/PlanExecutionStatusUpdateEventHandler.java#L39)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Please add this in PmsExecutionSummaryService and call that in graphGEnerationService directly.
This class should not update the summary directly.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java` line 176 at r2](https://reviewable.io/reviews/harness/harness-core/52950#-NeMyMU018xuTbQ4gfou:-NeN8yqV0A-cEUTT0nY_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/916c83e5dae42e9934bf0f612a88f18d33dba3e0/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L176)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Please call pmsExecutionSummaryService here.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/PipelineStatusUpdateEventHandler.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/52950#-NeMyXVmB0oSSaLRqOoj:-NeN3QGmDiV7Pt-4cnE_:b-t6rfbq) ([raw file](https://github.com/harness/harness-core/blob/916c83e5dae42e9934bf0f612a88f18d33dba3e0/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/PipelineStatusUpdateEventHandler.java#L59)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we remove this function altogether?
</blockquote></details>

Its interface's method so need to override.

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 13 files at r1, 1 of 4 files at r3, 1 of 4 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52950)* status: 15 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/PlanExecutionStatusUpdateEventHandler.java` line 29 at r6](https://reviewable.io/reviews/harness/harness-core/52950#-Neaiaw57tLR3K7dZ_vz:-Neaiaw57tLR3K7dZ_w-:b-e7hgyc) ([raw file](https://github.com/harness/harness-core/blob/ceac118284499836bab61e17c168f0a6cf394798/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/PlanExecutionStatusUpdateEventHandler.java#L29)):*
> ```Java
>   @Inject private GraphGenerationService graphGenerationService;
> 
>   public OrchestrationGraph handleEvent(PlanExecution planExecution, OrchestrationGraph orchestrationGraph) {
> ```

why do you need complete planExecution and not just planExecutionId?
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryService.java` line 85 at r6](https://reviewable.io/reviews/harness/harness-core/52950#-NeaipWM7JB2UkNf_Vky:-NeaipWM7JB2UkNf_Vkz:bd2gvoz) ([raw file](https://github.com/harness/harness-core/blob/ceac118284499836bab61e17c168f0a6cf394798/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryService.java#L85)):*
> ```Java
>    * Uses - planExecutionId_unique idx
>    */
>   void updateStatus(PlanExecution planExecution, Update summaryEntityUpdate);
> ```

can we make return type as Update?
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java` line 176 at r2](https://reviewable.io/reviews/harness/harness-core/52950#-NeMyMU018xuTbQ4gfou:-NeaixhM3BRunsjKj8yW:b-qbncxa) ([raw file](https://github.com/harness/harness-core/blob/916c83e5dae42e9934bf0f612a88f18d33dba3e0/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L176)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@brijeshdhakar can we discuss this?

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52950)* status: 15 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/PlanExecutionStatusUpdateEventHandler.java` line 29 at r6](https://reviewable.io/reviews/harness/harness-core/52950#-Neaiaw57tLR3K7dZ_vz:-NebyxZs58azpnZixjMy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ceac118284499836bab61e17c168f0a6cf394798/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/PlanExecutionStatusUpdateEventHandler.java#L29)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do you need complete planExecution and not just planExecutionId?
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryService.java` line 85 at r6](https://reviewable.io/reviews/harness/harness-core/52950#-NeaipWM7JB2UkNf_Vky:-Nebyysm-4-MQINurKaV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ceac118284499836bab61e17c168f0a6cf394798/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryService.java#L85)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we make return type as Update?
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java` line 176 at r2](https://reviewable.io/reviews/harness/harness-core/52950#-NeMyMU018xuTbQ4gfou:-NebyzXT82doClX8-piF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/916c83e5dae42e9934bf0f612a88f18d33dba3e0/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L176)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@brijeshdhakar can we discuss this?
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 13 files at r1, 1 of 4 files at r4, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52950)* status: 13 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/PipelineStatusUpdateEventHandler.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/52950#-NeMyXVmB0oSSaLRqOoj:-Nec3j3F6Y3C8N0kVfbV:b-re1ufa) ([raw file](https://github.com/harness/harness-core/blob/916c83e5dae42e9934bf0f612a88f18d33dba3e0/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/PipelineStatusUpdateEventHandler.java#L59)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Its interface's method so need to override.
</blockquote></details>

we can remove the interface altogether

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 5 of 13 files at r1, 2 of 4 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52950)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger review

**Pull request merged**
