### PR TITLE
fix: [DEL-4796]: Add validation checks during Delegate register call

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Describe your changes
Few checks for ECS based delegate, during register call.
## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38255)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38255)

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2576 at r1](https://reviewable.io/reviews/harness/harness-core/38255#-NDZg4_N3_Wufd5UpQis:-NDZg4_N3_Wufd5UpQit:b2w2u0l) ([raw file](https://github.com/harness/harness-core/blob/2d577d00781d3013045195418aef6fc432157fae/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2576)):*
> ```Java
>     }
> 
>     if (!validateDelegateRegisterRequest(delegateParams)) {
> ```

i think the problem with this jira is that when we register the delegate, we don't consider whether the delegate is in cg or ng. 

1. if you have a delegate d1 in cg, a user can not create a delegate with the same name in ng
2. if you change the yaml and make ng to true in an existing yaml, it still thinks that the delegate is registered in cg and doesn't register a new delegate
3. we also do not consider whether delegate is in a different project/org so we have this limitation of the delegate name should be unique across account which is not user friendly

**Review by xingchi-jin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38255)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2581 at r1](https://reviewable.io/reviews/harness/harness-core/38255#-NDfxLDe4FM_d_P6HfCD:-NDfxLDe4FM_d_P6HfCE:b-ah7588) ([raw file](https://github.com/harness/harness-core/blob/2d577d00781d3013045195418aef6fc432157fae/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2581)):*
> ```Java
>     }
> 
>     if (isNotBlank(delegateParams.getDelegateGroupId())) {
> ```

this check can be removed
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 4505 at r1](https://reviewable.io/reviews/harness/harness-core/38255#-NDfxG6m9ZXYH0ZPCMZV:-NDfxG6m9ZXYH0ZPCMZW:b-fh3n7n) ([raw file](https://github.com/harness/harness-core/blob/2d577d00781d3013045195418aef6fc432157fae/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L4505)):*
> ```Java
>   }
> 
>   private boolean validateDelegateRegisterRequest(DelegateParams delegateParams) {
> ```

rename to isValidDelegateRegisterRequest

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38255)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2576 at r1](https://reviewable.io/reviews/harness/harness-core/38255#-NDZg4_N3_Wufd5UpQis:-NG126T151cHmxANyzZx:bscs97e) ([raw file](https://github.com/harness/harness-core/blob/2d577d00781d3013045195418aef6fc432157fae/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2576)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

i think the problem with this jira is that when we register the delegate, we don't consider whether the delegate is in cg or ng. 

1. if you have a delegate d1 in cg, a user can not create a delegate with the same name in ng
2. if you change the yaml and make ng to true in an existing yaml, it still thinks that the delegate is registered in cg and doesn't register a new delegate
3. we also do not consider whether delegate is in a different project/org so we have this limitation of the delegate name should be unique across account which is not user friendly 
</blockquote></details>

#1 is already fixed, one can have delegate with same name in cg and ng both.
for #2, if somebody used cg yaml and use it for creating ng delegate, it should fail here at this point, reason being it should have missing delegate Group Id.

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2576 at r1](https://reviewable.io/reviews/harness/harness-core/38255#-NDZg4_N3_Wufd5UpQis:-NGKhmAU4smXVWodL3J0:bbsigh6) ([raw file](https://github.com/harness/harness-core/blob/2d577d00781d3013045195418aef6fc432157fae/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2576)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

#1 is already fixed, one can have delegate with same name in cg and ng both.
for #2, if somebody used cg yaml and use it for creating ng delegate, it should fail here at this point, reason being it should have missing delegate Group Id.

</blockquote></details>

thats not true, we don't have delegate group id in the yaml

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38255)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained.

**Pull request closed without merging**
