### PR TITLE
feat: [PL-31961]: fix queries for userMetadata collection that are fetching unlimited records

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
fix queries for userMetadata collection that are fetching unlimited records, applied limits on userGroup API

- limit of 5k have been applied to UserGroup Apis
- use of stream instead of find() method

Tested the changes locally and added UTs as well

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44985)

### CODE REVIEW

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44985)* status: 10 file(s) to review. 1 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 430 at r2](https://reviewable.io/reviews/harness/harness-core/44985#-NQP_8bC0h-nRs2A4En3:-NQP_8bC0h-nRs2A4En4:b-5osufe) ([raw file](https://github.com/harness/harness-core/blob/47768b2cb908bde311a77050fcfde736470165cf/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L430)):*
> ```Java
>         get(scope.getAccountIdentifier(), scope.getOrgIdentifier(), scope.getProjectIdentifier(), userGroupIdentifier);
>     if (!userGroupOptional.isPresent()) {
>       return null;
> ```

Is null handled properly?



_Code quote:_
```Java
getUsersInUserGroup
```

**Comment by pbarapatre10** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 523 at r2](https://reviewable.io/reviews/harness/harness-core/44985#-NQPcN6-AvGNEmTZorsB:-NQPcN6-AvGNEmTZorsC:b-vpfy5d) ([raw file](https://github.com/harness/harness-core/blob/47768b2cb908bde311a77050fcfde736470165cf/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L523)):*
> ```Java
>   @Override
>   public CloseableIterator<UserMetadata> streamUserMetadata(List<String> userIds) {
>     return userMetadataRepository.stream(Criteria.where(UserMembershipKeys.userId).in(userIds));
> ```

minor: this should be `UserMetadataKeys.userId` , thanks



_Code quote:_
```Java
UserMembershipKeys.userId
```

**Comment by pbarapatre10** [comment]
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/dto/UserGroupRequestV2DTO.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/44985#-NQPd55v1eZznFaH7fyj:-NQPd55v1eZznFaH7fyk:b-x33zhy) ([raw file](https://github.com/harness/harness-core/blob/47768b2cb908bde311a77050fcfde736470165cf/960-ng-core-beans/src/main/java/io/harness/ng/core/dto/UserGroupRequestV2DTO.java#L50)):*
> ```Java
> 
>   @Schema(description = "Name of the UserGroup.") @NotNull @NGEntityName String name;
>   @Schema(description = "List of users emails in the UserGroup. Maximum users can be 1000.")
> ```

nit: update to 5000 here, thanks



_Code quote:_
```Java
1000.
```

**Review by pbarapatre10 — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 5 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44985)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44985)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 430 at r2](https://reviewable.io/reviews/harness/harness-core/44985#-NQP_8bC0h-nRs2A4En3:-NQPit8F2hpjHK6Ft-5J:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/47768b2cb908bde311a77050fcfde736470165cf/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L430)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Is null handled properly?
</blockquote></details>

yes
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 523 at r2](https://reviewable.io/reviews/harness/harness-core/44985#-NQPcN6-AvGNEmTZorsB:-NQPivUXAy9yMA_G6RBV:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/47768b2cb908bde311a77050fcfde736470165cf/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L523)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor: this should be `UserMetadataKeys.userId` , thanks
</blockquote></details>

done
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/dto/UserGroupRequestV2DTO.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/44985#-NQPd55v1eZznFaH7fyj:-NQPiwoY8TXI4SPT6geR:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/47768b2cb908bde311a77050fcfde736470165cf/960-ng-core-beans/src/main/java/io/harness/ng/core/dto/UserGroupRequestV2DTO.java#L50)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

nit: update to 5000 here, thanks
</blockquote></details>

done

**Review by pbarapatre10 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 9 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44985#-:-NQPj5pKEyF-aT_cNEJA:bnfp4nl)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by bhavya181** [comment]
trigger ut0

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 7 of 9 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44985)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by pbarapatre10 — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44985)* status: 1. unresolved discussions.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44985)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44985#-:-NQQTA0D8gZBuDzhpADB:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
