### PR TITLE
feat: [PL-27456]: Changes for increasing bazel version to 5.0.0

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes

* Upgrade bazel version to 5.0.0

Here are the main changes required:

1) resource_jars is not supported. We are primarily using those for proto targets, as long as those are listed in the deps, we should be good.
https://github.com/bazelbuild/bazel/issues/13221

There was another way to circumvent this issue, i.e. --noincompatible_disallow_resource_jars --experimental_builtins_injection_override=-java_library,-java_plugin ; but that only seems to work with the build command and not with the bazel query, which leads to failure during checkstyle

2) --experimental_no_product_name_out_symlink is deprecated and it defaults to true in 5.x.x - so we dont need to set it.
https://www.buildbuddy.io/blog/whats-new-in-bazel-5-0/
 
3) 'strict_java_deps' is replaced with experimental_strict_java_deps

4) 'javabase' and 'java_toolchain' are deprecated and we just need minimal information going forward for the new platform-based toolchain information.

https://github.com/bazelbuild/bazel/issues/7849

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37784)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_NA_** 
 


            
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37784)

**Review by archit-harness — APPROVED** [review]
> Reviewed 26 of 27 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37784)* status: 27 file(s) to review. 1 of 2 approvals obtained.

**Review by mdmilic — DISMISSED** [review]
@gn-harness You removed bunch of protos release_jars, but haven't added them to deps. Were they unused, or how does it work now?

> Reviewed 26 of 27 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37784#-:-NC_0ITLApy3308w3HLz:b-3av0sx)* status: :shipit: complete! ✓

**Review by gn-harness — COMMENTED** [review]
Most of them are already added to the deps, so those were duplicated. I think there was only one place, where I had to move instead of replace. 

I think these were redundant in the 4.x.x also (tried running by removing a few and it seems to still boot ng-manager). 

Overall idea of resource jars was to merge the contents of this jar with the parent one. As long as we have the proto jars coming via deps, we don't need this.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37784#-:-NC_s_jK5wLOtpFu-9Pl:bvbp4p7)* status: :shipit: complete! ✓

**Comment by diptiman-adak** [comment]
rebase

**Review by diptiman-adak — DISMISSED** [review]

**Review by puneetsar — DISMISSED** [review]
> Reviewed 26 of 27 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37784)* status: 1 of 2 approvals obtained.

**Review by mdmilic — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37784)* status: :shipit: complete! ✓

**Review by diptiman-adak — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37784)* status: :shipit: complete! ✓

**Review by naidu-harness — APPROVED** [review]
> Reviewed 26 of 27 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37784)* status: :shipit: complete! ✓

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37784#-:-NCxGZ_aAgq_Ua8ouS6_:bnfp4nl)* status: :shipit: complete! ✓

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37784#-:-NCxrF633K4_50-Zh5YC:bnfp4nl)* status: 1 of 2 approvals obtained.

**Review by diptiman-adak — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37784)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37784)* status: :shipit: complete! ✓

**Pull request merged**
