### PR TITLE
fix: [CDS-82222]: handle aborted terraform task

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Describe your changes
fix: [CDS-82222]: handle aborted terraform task
When abort event is received, delegate will do  Thread.currentThread().interrupt() 
During task execution the interrupted field of the thread can re reset of interrupted exception may not be handled properly.
A few places like that are:
1. io.harness.filesystem.FileIo#waitForDirectoryToBeAccessibleOutOfProcess
2. JGit library, Git.open() method is resetting threads interrupted field (this method is used un many places of delegate tasks code).

Once we cannot rely on current thread's interrupted field (as it can be change by any piece of code that is running in that thread) we added a new property to delegate task isAborted, that will be set true when the task is aborted.
During task execution we can check that field in order to know is task was aborted or not.

Tested on local env and also tested with an old delegate.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-82222]: https://harness.atlassian.net/browse/CDS-82222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54914)

### CODE REVIEW

**Comment by tmacari-harness** [comment]
trigger uts

**Comment by tmacari-harness** [comment]
trigger uts

**Comment by tmacari-harness** [comment]
trigger uts

**Review by mdmilic — CHANGES_REQUESTED** [review]
In general, I don't think this is a good approach to aborting your task. Delegate already interrupts the (main) task thread, so what you should do instead is to handle the thread interrupt in a better way. 
My understanding is that you have a code that handles the InterruptedException, so what you need to do is set the interrupted() flag when that exception is caught. Then your `handleAborted` would become something like below:
```Java
protected void handleAborted(AtomicBoolean isAborted) throws InterruptedException {
    if (Thread.currentThread().isInterrupted()) {
      throw new InterruptedException();
    }
  }
```
You should also make sure to interrupt all the child threads if you have any (eg if you are using some executor services, you can shut them down or interrupt their specific threads)

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54914#-:-NiKBUFQELreO9KvEgtP:b-31ehv7)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/test/resources/kryo-registrations.txt` line 2880 at r1](https://reviewable.io/reviews/harness/harness-core/54914#-NiK3ca61c_S25Hhk4hW:-NiK3ca61c_S25Hhk4hX:bb5m7m7) ([raw file](https://github.com/harness/harness-core/blob/025295dfef46826205310b8a6fe025114887a82f/260-delegate/src/test/resources/kryo-registrations.txt#L2880)):*
> ```help
> 20001001:io.harness.delegate.beans.connector.gcpconnector.GcpOidcDetailsDTO
> 20001002:io.harness.delegate.task.k8s.ReleaseMetadata
> 20001003:java.util.concurrent.atomic.AtomicBoolean
> ```

Why serializing AtomicBoolean, it looses it's atomicity this way, just use plain boolean if needed.

**Review by tmacari-harness — COMMENTED** [review]
Our delegate task is quite complex. We observed that we cannot rely on Thread.currentThread().isInterrupted() to abort the task at any time during execution.
Here are more details about it https://harness.slack.com/archives/CSL96M7UG/p1698321056946359.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54914#-:-NiKNpD91K__fG1SCFQX:bvhgt8y)* status: 16 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/test/resources/kryo-registrations.txt` line 2880 at r1](https://reviewable.io/reviews/harness/harness-core/54914#-NiK3ca61c_S25Hhk4hW:-NiKOeWuBjdJQTHjGBBX:bc22svo) ([raw file](https://github.com/harness/harness-core/blob/025295dfef46826205310b8a6fe025114887a82f/260-delegate/src/test/resources/kryo-registrations.txt#L2880)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Why serializing AtomicBoolean, it looses it's atomicity this way, just use plain boolean if needed.
</blockquote></details>

If I do not add it here I get ket kryo exception.

**Review by mdmilic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54914)* status: Some of the checks are too old. 16 file(s) to review. 1 of 2 approvals obtained. 

___
*[`260-delegate/src/test/resources/kryo-registrations.txt` line 2880 at r1](https://reviewable.io/reviews/harness/harness-core/54914#-NiK3ca61c_S25Hhk4hW:-Nienly3CZlwASwFDQz9:b-hbgmub) ([raw file](https://github.com/harness/harness-core/blob/025295dfef46826205310b8a6fe025114887a82f/260-delegate/src/test/resources/kryo-registrations.txt#L2880)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

If I do not add it here I get ket kryo exception.
</blockquote></details>

The AtomicBoolean is needed, but having it in side a kryo object that gets sent around is just a necessity, we don't actually transfer the AtomicBoolean over the wire, but use the same object inside the delegate as well.

**Review by mdmilic — APPROVED** [review]
After more discussions, this seems like the only viable approach which is bulletproof for notifying the task thread that it's being aborted. The issue with interrupt flag is that 3rd party deps might handle it incorrectly (like JGit) which could cause us to miss the signal if it would happen during a JGit operation (if it happens while executing other harness code, we could handle it properly). 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54914#-:-Nieo9vO85_pPepWeHg4:b-uba53v)* status: Some of the checks are too old. 16 file(s) to review. 1 of 2 approvals obtained.

**Review by vlica-harness — APPROVED** [review]

**Comment by tmacari-harness** [comment]
trigger review

**Pull request merged**
