### PR TITLE
feat: [CDS-34444]: add step level override for K8s Apply …

### PR DESCRIPTION
**Pull request by achyuth-harness**
…Step (NG)

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32652)

### CODE REVIEW

**Comment by achyuth-harness** [comment]
trigger ti2

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32652)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 367 at r2](https://reviewable.io/reviews/harness/harness-core/32652#-N1s61b8AZQvQD43_QFn:-N1s61b8AZQvQD43_QFo:b-t06qem) ([raw file](https://github.com/harness/harness-core/blob/dc23a0b99c344619a4e2362879600976e49aac57/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L367)):*
> ```Java
>             .collect(Collectors.toList());
> 
>     int i = 0;
> ```

nit: can use old way for (int i =0; i < manifestAttributesList.size(); i++)
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepPassThroughData.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/32652#-N1s2CFF78TNwIDokE0g:-N1s2CFGCpjRbl1nEDK1:b-jmm63w) ([raw file](https://github.com/harness/harness-core/blob/dc23a0b99c344619a4e2362879600976e49aac57/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepPassThroughData.java#L43)):*
> ```Java
>     }
>     List<ValuesManifestOutcome> valuesOutcomeList = new ArrayList<>();
>     for (ManifestOutcome manifestOutcome : manifestOutcomeList) {
> ```

to be safe here, maybe is worth to have a type check and add only if type is Value
___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentSteps/all.json` line 586 at r2](https://reviewable.io/reviews/harness/harness-core/32652#-N1s5RJlBBuP56HJpkFE:-N1s5RJm0eZkjhI8wRbz:b-59krhl) ([raw file](https://github.com/harness/harness-core/blob/dc23a0b99c344619a4e2362879600976e49aac57/125-cd-nextgen/src/test/resources/schema/DeploymentSteps/all.json#L586)):*
> ```JSON
>       "$schema": "http://json-schema.org/draft-07/schema#"
>     },
>     "HelmChartManifest": {
> ```

Why this is coming now?
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ManifestConfig.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/32652#-N1s5gHZ3edAYupF7ZLG:-N1s5gHZ3edAYupF7ZLH:beo4t82) ([raw file](https://github.com/harness/harness-core/blob/dc23a0b99c344619a4e2362879600976e49aac57/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ManifestConfig.java#L57)):*
> ```Java
>   @JsonProperty("spec")
>   @JsonTypeInfo(use = NAME, property = "type", include = EXTERNAL_PROPERTY, visible = true)
>   public ManifestAttributes spec;
> ```

It should be private (or package private)
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ManifestConfig.java` line 73 at r2](https://reviewable.io/reviews/harness/harness-core/32652#-N1s5k7g0r-WIpRabdcq:-N1s5k7g0r-WIpRabdcr:baxjtcg) ([raw file](https://github.com/harness/harness-core/blob/dc23a0b99c344619a4e2362879600976e49aac57/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ManifestConfig.java#L73)):*
> ```Java
>   }
> 
>   public ManifestAttributes getSpec() {
> ```

We have @Data annotation, why we need this method?

**Review by abosii-harness — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32652)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by abosii-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32652)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32652)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32652)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 6 of 18 files at r2, 2 of 3 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32652)* status: :shipit: complete! ✓

**Review by hextechpal — APPROVED** [review]
> Reviewed 6 of 18 files at r2, 2 of 3 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32652)* status: :shipit: complete! ✓

**Pull request merged**
