### PR TITLE
fix: [CDS-71721]: Fixing handle child response for identityStrategyInterna…

### PR DESCRIPTION
**Pull request by Y0709**
For stages with looping stategies we were not capturing the status of parent entities like stages correctly while copying the stage during rerun. After investigation we found that the response map of child responses in handle child response always has the response of that last step only due to which status of a stage is dependent on the last step of that stage while rerun. This behaviour is working fine for stages without lopping strategies where we are not using the response map of children but use original node status.
We have changed the code to use the same flow here. 
We have also fixed the flow to copy executions with failure strategy in it as we were not correctly copying the flow there
Tested retry with all failure strategies as well with parellelism

We will also be adding automation for this as part of this ticket https://harness.atlassian.net/browse/CDS-72014 . Automated case will include a pipeline with a stage with parallelism with multiple steps and a stage after that and we will retry from that stage and check if the stage with looping strategy is getting correctly copied or not

Adding a few scenarios here that are fixed in this pr
1) Here we can see that on rerun we are not copying the status for the stage correctly as we are just calculating the status of stage based on the status of last step.
[https://app.harness.io/ng/account/SNM_3IzhRa6SFPz6DIV7aA/cd/orgs/default/projects/testrohitgitops/pipelines/testparallelism/executions/AToFc1sURHiR-uY5Y86vuA/pipeline?storeType=INLINE](url)

2) Here we can see that the step after the step with failure strategy is not copied while retrying the execution. This is happening with multiple failure strategies
[https://app.harness.io/ng/account/SNM_3IzhRa6SFPz6DIV7aA/cd/orgs/default/projects/testrohitgitops/pipelines/testparallelismWithfailurestrategy1/executions/Ina7rAAJSI29FtDFdgoPRw/pipeline?storeType=INLINE&stage=xNPIGVFFSB-VqDwu3g4MpA&step=cXN134h_SdOvPPRCwe1W5g](url)

[https://app.harness.io/ng/account/SNM_3IzhRa6SFPz6DIV7aA/cd/orgs/default/projects/testrohitgitops/pipelines/testretrywithFailurestrategy2/executions/pK8HG7mMSse3I0FIAEY76w/pipeline?storeType=INLINE&stage=-O6nTlWvSQ2CjNi_qDMxtg&step=iYKCpIEqRJCPILT4L2gV4A](url)

[https://app.harness.io/ng/account/SNM_3IzhRa6SFPz6DIV7aA/cd/orgs/default/projects/testrohitgitops/pipelines/testretrywithFailurestrategy2/executions/cnk8AXS8SSCxXjgiqsohNg/pipeline?storeType=INLINE&stage=RHhrnjyTR2SSaqrRrChpMg](url)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49070)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49070)* status: 6 file(s) to review. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java` line 118 at r2](https://reviewable.io/reviews/harness/harness-core/49070#-NXsn08qBzfnv4MymC3W:-NXsn08rEDxUImY11ppH:bl4ln88) ([raw file](https://github.com/harness/harness-core/blob/331855e24d795f5a31527c4d41eac6d21929bc53/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java#L118)):*
> ```Java
>       // (retryListId) eg -> in strategy
>       NodeExecution nextNonRetriedNodeExecution =
>           nodeExecutionService.fetchNodeExecutionForPlanNodeAndRetriedId(nextNodeExecution.getPlanExecutionId(),
> ```

nit: use originalNodeExecution.getPlanExecutionId() so that its easier to understand. although nextNodeExecution also belong to original planExecution only.

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49070)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java` line 118 at r2](https://reviewable.io/reviews/harness/harness-core/49070#-NXsn08qBzfnv4MymC3W:-NXsytct5z76LhM7OK__:b-dgh0tr) ([raw file](https://github.com/harness/harness-core/blob/331855e24d795f5a31527c4d41eac6d21929bc53/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java#L118)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

nit: use originalNodeExecution.getPlanExecutionId() so that its easier to understand. although nextNodeExecution also belong to original planExecution only.
</blockquote></details>

We are using the next nodeExceution planExecutionId only since it belongs to original planExecution only and original node execution as we are getting does not have ambiance to get the plan ExecutionId

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49070)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49070)* status: :shipit: complete! ✓

**Comment by Y0709** [comment]
trigger review

**Comment by Y0709** [comment]
trigger messagecheck

**Pull request merged**
