### PR TITLE
fix: [CI-6612]: Add V1 Yaml checks for features that are behind FF

### PR DESCRIPTION
**Pull request by raghavharness**
## Describe your changes
Add V1 Yaml checks for features that are behind FF
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42222)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java` line 176 at r1](https://reviewable.io/reviews/harness/harness-core/42222#-NKwWZX6E5gtNBdS3-0_:-NKwWZX6E5gtNBdS3-0a:b6t9lul) ([raw file](https://github.com/harness/harness-core/blob/67d0760cd12ec4ce987549cfe1365e779a7b2f4c/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java#L176)):*
> ```Java
>         ? metadata.getHarnessVersion()
>         : PipelineVersion.V0;
>     boolean isExecutionInputEnabled = pipelineVersion.equals(PipelineVersion.V0)
> ```

always do a reverse check like : PipelineVersion.V0.equals(pipelineVersion) to avoid NPEs.

**Comment by raghavharness** [comment]
> _[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java` line 176 at r1](https://reviewable.io/reviews/harness/harness-core/42222#-NKwWZX6E5gtNBdS3-0_:-NKwWZX6E5gtNBdS3-0a:b6t9lul) ([raw file](https://github.com/harness/harness-core/blob/67d0760cd12ec4ce987549cfe1365e779a7b2f4c/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java#L176)):_
> 
> > ```java
> >         ? metadata.getHarnessVersion()
> >         : PipelineVersion.V0;
> >     boolean isExecutionInputEnabled = pipelineVersion.equals(PipelineVersion.V0)
> > ```
> 
> always do a reverse check like : PipelineVersion.V0.equals(pipelineVersion) to avoid NPEs.
Yeah makes sense, but I have already added a check in above line.

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42222)* status: 10 file(s) to review.

**Review by archit-harness — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42222)* status: :shipit: complete! ✓

**Pull request merged**
