### PR TITLE
fix: [PIE-4707]: added a config in debezium service

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36333)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36333)

**Comment by shalini-agr** [comment]
trigger ti0, ti2

**Comment by shalini-agr** [comment]
trigger ti0, ti2

**Comment by shalini-agr** [comment]
trigger ti0

**Comment by sahilhindwani-harness** [comment]
*[`959-debezium-beans/src/main/java/io/harness/debezium/DebeziumConfig.java` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/36333#-N9_BmFsDTAzfbYr1Vz9:-N9_BmFsDTAzfbYr1VzA:biedkmw) ([raw file](https://github.com/harness/harness-core/blob/1a0827cd2118d81d5ba93858029efc0fc5398171/959-debezium-beans/src/main/java/io/harness/debezium/DebeziumConfig.java#L112)):*
> ```Java
>   @JsonProperty("redisStreamSize") private int redisStreamSize;
>   @JsonProperty("snapshot.mode") private String snapshotMode;
>   @JsonProperty("transforms.unwrap.array.encoding") private String transformsUnwrapArrayEncoding;
> ```

Add a note explaining about this property and why we added it.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36333)* status: Some of the checks are too old. 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
*[`959-debezium-beans/src/main/java/io/harness/debezium/DebeziumConfig.java` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/36333#-N9_BmFsDTAzfbYr1Vz9:-N9_I7pr0A7XayBTYy_j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1a0827cd2118d81d5ba93858029efc0fc5398171/959-debezium-beans/src/main/java/io/harness/debezium/DebeziumConfig.java#L112)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Add a note explaining about this property and why we added it.
</blockquote></details>

Done.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 13 of 14 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36333)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36333)* status: :shipit: complete! ✓

**Pull request merged**
