### PR TITLE
[fix]: [CDS-78986]: fixing noOfTopKeys and topKey calculation for array-elements so that it will work on possible wrapper keys only

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Fixing the FqnMapGenerator and YamlMapGenerator logic to decide if an array element should be treated as wrapper object or normal object.

How are we deciding: We are checking the elements of the arrayNodes. And if the element has any field(let say field1) that has any UUID_KEY field(let say field2 examples: name/identifier) present then that field(field1) would be treated as the wrapper key. And the element would be treated as a wrapper object.

Example:
WrapperObject(step field is wrapper for the step object):
```
steps:
  - step:
      name: step1
      identifier: step1
  - step:
      name: step2
      identifier: step2

manifestes:
  - manifest:
      identifier: manifest1
      name: manifest1
      ...
  - manifest:
      identifier: manifest2
      name: manifest2
      ...
```

NormalObject:
```
variables:
  - name: var1
    value: val1
  - name: var2
    value: val2
```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53373)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53373)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/FQNHelper.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/53373#-NfHJwiW5SoLPGkjASAR:-NfHJwiW5SoLPGkjASAS:b-mchm1z) ([raw file](https://github.com/harness/harness-core/blob/47dbeafbaca72caefd096d5e197a5b7de8e40cb3/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/FQNHelper.java#L95)):*
> ```Java
>   //        return uuidKey;
>   //      }
>   //    }
> ```

do we need this?

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53373)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger gitleaks review

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53373)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger review

**Pull request merged**
