### PR TITLE
[feat]: [PIE-8772]: Integrating getFileContentOnly in run flow for template

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Integrating getFileContentOnly in run flow for template. Have tested out the following:

1. with FF on, remote pipeline with no run time inputs and templates
2. with FF on, remote pipeline with run time inputs and no templates
3. with FF on, remote pipeline with run time inputs and templates
4. with FF off, remote pipeline
5. with FF off, inline pipeline

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44921)

### CODE REVIEW

**Review by archit-harness — DISMISSED** [review]
> Reviewed 11 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44921)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeService.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/44921#-NQ6sOfh3FL042jBA3QD:-NQ6sOfh3FL042jBA3QE:bqpru1n) ([raw file](https://github.com/harness/harness-core/blob/c0b1491313ae98d8479b7950948f0388d5882d8a/840-template-service/src/main/java/io/harness/template/services/TemplateMergeService.java#L25)):*
> ```Java
>   TemplateMergeResponseDTO applyTemplatesToYamlV2(String accountId, String orgId, String projectId, String yaml,
>       boolean getMergedYamlWithTemplateField, boolean loadFromCache, boolean appendInputSetValidator,
>       boolean getOnlyFileContent);
> ```

@adivishy1 why have we integrated a new param in the method? We should go the same way as its done in pipeline service via context way.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44921)* status: 21 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeService.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/44921#-NQ6sOfh3FL042jBA3QD:-NQ96d149poi0d6n0YyU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0b1491313ae98d8479b7950948f0388d5882d8a/840-template-service/src/main/java/io/harness/template/services/TemplateMergeService.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@adivishy1 why have we integrated a new param in the method? We should go the same way as its done in pipeline service via context way.
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 775 at r5](https://reviewable.io/reviews/harness/harness-core/44921#-NQ9Ut466VLWM1ik1vnw:-NQ9Ut466VLWM1ik1vnx:bi62bqo) ([raw file](https://github.com/harness/harness-core/blob/250828a742533f90499171ed1c16080fc1a89876/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L775)):*
> ```Java
>     long start = System.currentTimeMillis();
>     log.info("Principal in the applyTemplate resource layer is {}", SourcePrincipalContextBuilder.getSourcePrincipal());
>     if (ngTemplateFeatureFlagHelperService.isFeatureFlagEnabled(accountId, PIE_GET_FILE_CONTENT_ONLY)
> ```

we don't need to use any flag in template service. We should simply set the context. If required context comes in the API request, it will be set otherwise ignored. The caller is the driver here.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44921)* status: 20 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 775 at r5](https://reviewable.io/reviews/harness/harness-core/44921#-NQ9Ut466VLWM1ik1vnw:-NQ9qRu3EaupUG8qKcRA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/250828a742533f90499171ed1c16080fc1a89876/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L775)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we don't need to use any flag in template service. We should simply set the context. If required context comes in the API request, it will be set otherwise ignored. The caller is the driver here.
</blockquote></details>

Done.

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/utils/TemplateUtils.java` line 174 at r9](https://reviewable.io/reviews/harness/harness-core/44921#-NQA4O2DBUUt40Fvag53:-NQA4O2DBUUt40Fvag54:b7b5evl) ([raw file](https://github.com/harness/harness-core/blob/d036062d425578a351dbfebbd5d4fb4a5e1fef02/840-template-service/src/main/java/io/harness/template/utils/TemplateUtils.java#L174)):*
> ```Java
>     if (user_flow != null) {
>       return user_flow.equals(USER_FLOW.EXECUTION);
>     }
> ```

nit: this can just be ```USER_FLOW.EXECUTION.equals(user_flow)```

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 6 of 11 files at r1, 1 of 9 files at r3, 1 of 6 files at r4, 2 of 11 files at r6, 10 of 11 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44921)* status: 12 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 6 of 11 files at r1, 1 of 9 files at r3, 1 of 6 files at r4, 2 of 11 files at r6, 10 of 11 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44921)* status: :shipit: complete! ✓

**Pull request merged**
