### PR TITLE
feat: [PL-32419]: Separate Kryo registrars for K8sNgTask and granular K8sNgApplication

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

This PR creates a separate Kryo registrar for K8sNgTask.

Tested it locally by running the K8sNgApplication in docker.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46570)

### CODE REVIEW

**Review by mdmilic — COMMENTED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46570)* status: 26 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/BUILD.bazel` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/46570#-NTYh4sG3PB5lTqWt2N2:-NTYh4sG3PB5lTqWt2N3:b5mf8ns) ([raw file](https://github.com/harness/harness-core/blob/4f73496e90b1434f186aad1978463b6ce5f6f756/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/BUILD.bazel#L43)):*
> ```Starlark
>         "@maven//:com_google_guava_guava",
>         "@maven//:com_google_inject_guice",
>         "@maven//:io_harness_cv_data_collection_dsl",
> ```

I don't recall what we said about this one, looks wrong, but is it same issue like ng_license_beans or it's valid to be here?
___
*[`delegate/src/main/java/io/harness/kryo/registrars/K8sNgTaskRegister.java` line 275 at r1](https://reviewable.io/reviews/harness/harness-core/46570#-NTYiKo30EWnf9vgPOyG:-NTYiKo30EWnf9vgPOyH:b-g4608x) ([raw file](https://github.com/harness/harness-core/blob/4f73496e90b1434f186aad1978463b6ce5f6f756/delegate/src/main/java/io/harness/kryo/registrars/K8sNgTaskRegister.java#L275)):*
> ```Java
> import java.util.LinkedHashSet;
> 
> public class K8sNgTaskRegister implements KryoRegistrar {
> ```

1. Are all of these actually needed for K8S tasks, looking at their names some might seem unrelated?
2. My understanding is that this registrar is only used for K8S dockerized task, but standard immutable delegate still uses old registrars from 930-delegate-tasks. 
If so I don't think that's a good idea because any change to K8S tasks would now have to reflect into two separate registrars. It would be best to create multiple registrars out of this one and register the same ones for older delegates and for K8S docker task APP. Some of the beans here also seem like common to all tasks, we already have one registrar for this here https://github.com/harness/harness-core/blob/develop/delegate/src/main/java/io/harness/taskapps/common/kryo/CommonTaskKryoRegistrar.java
Here's a (very simple) [example PR](https://github.com/harness/harness-core/pull/41827/files#diff-8444407cb8fbb659208a1d8506ea2338f288c3a446739372af7d62a25046a314) where I split secret registrars out of 930-delegate-tasks, but have only one set of registrars for all new and old usages.

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46570)* status: Some of the checks are too old. 26 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/BUILD.bazel` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/46570#-NTYh4sG3PB5lTqWt2N2:-NTp61583LNnhwemZhgb:b-bi3ir7) ([raw file](https://github.com/harness/harness-core/blob/4f73496e90b1434f186aad1978463b6ce5f6f756/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/BUILD.bazel#L43)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I don't recall what we said about this one, looks wrong, but is it same issue like ng_license_beans or it's valid to be here?
</blockquote></details>

The last resolution on this is that we have few Harness libraries published to maven and `io.harness.datacollection.exception.DataCollectionException` is one of the packages which need the maven dependency @maven//:io_harness_cv_data_collection_dsl.
___
*[`delegate/src/main/java/io/harness/kryo/registrars/K8sNgTaskRegister.java` line 275 at r1](https://reviewable.io/reviews/harness/harness-core/46570#-NTYiKo30EWnf9vgPOyG:-NTp6acWEjYMfbmYrzTM:b-vjoc1x) ([raw file](https://github.com/harness/harness-core/blob/4f73496e90b1434f186aad1978463b6ce5f6f756/delegate/src/main/java/io/harness/kryo/registrars/K8sNgTaskRegister.java#L275)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

1. Are all of these actually needed for K8S tasks, looking at their names some might seem unrelated?
2. My understanding is that this registrar is only used for K8S dockerized task, but standard immutable delegate still uses old registrars from 930-delegate-tasks. 
If so I don't think that's a good idea because any change to K8S tasks would now have to reflect into two separate registrars. It would be best to create multiple registrars out of this one and register the same ones for older delegates and for K8S docker task APP. Some of the beans here also seem like common to all tasks, we already have one registrar for this here https://github.com/harness/harness-core/blob/develop/delegate/src/main/java/io/harness/taskapps/common/kryo/CommonTaskKryoRegistrar.java
Here's a (very simple) [example PR](https://github.com/harness/harness-core/pull/41827/files#diff-8444407cb8fbb659208a1d8506ea2338f288c3a446739372af7d62a25046a314) where I split secret registrars out of 930-delegate-tasks, but have only one set of registrars for all new and old usages. 
</blockquote></details>

So the way I generated this file is that I just got all the non-primitives recursively from the `K8sTaskNG` class. There were ~450 non-primitives that I got for `K8sTaskNG` and out of them only ~250 were Kryo registered in `kryo-registrations.txt`, so I included all these ~250 here. It is not possible to just filter out what is needed manually for K8s NG Task as it encompasses a lot of flavors through overrides. 

Okay, so I will use the CommonTaskKryoRegistrar.java for the common ones. For the splitting this to multiple registrars can I raise in a separate PR after merging this so I can close this ticket and create a new one to follow-up on the split up ?

**Comment by Raghav-Murali** [comment]
trigger ut2, ut3, ut6

**Review by mdmilic — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46570#-:-NTuYxH72MURH738v8vp:bnfp4nl)* status: 26 file(s) to review. 1 of 2 approvals obtained. 

___
*[`delegate/src/main/java/io/harness/kryo/registrars/K8sNgTaskRegister.java` line 275 at r1](https://reviewable.io/reviews/harness/harness-core/46570#-NTYiKo30EWnf9vgPOyG:-NTuYlMI5EA4Hzdp9wUe:b-hfghm4) ([raw file](https://github.com/harness/harness-core/blob/4f73496e90b1434f186aad1978463b6ce5f6f756/delegate/src/main/java/io/harness/kryo/registrars/K8sNgTaskRegister.java#L275)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

So the way I generated this file is that I just got all the non-primitives recursively from the `K8sTaskNG` class. There were ~450 non-primitives that I got for `K8sTaskNG` and out of them only ~250 were Kryo registered in `kryo-registrations.txt`, so I included all these ~250 here. It is not possible to just filter out what is needed manually for K8s NG Task as it encompasses a lot of flavors through overrides. 

Okay, so I will use the CommonTaskKryoRegistrar.java for the common ones. For the splitting this to multiple registrars can I raise in a separate PR after merging this so I can close this ticket and create a new one to follow-up on the split up ?
</blockquote></details>

Sounds good

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Pull request merged**
