### PR TITLE
feat: [CDS-83538]: Remove usage of metadata field in dependency from V1 plan creators as they have all started using the new field nodeMetadata instead

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** We are using nodeMetadata field of dependency in V1 plan creators to pass metadata to children nodes. For backward compatibility, we were using both metadata and nodeMetadata, now that all v1 plan creators have started using nodeMetadata, we are removing the usages of metadata field.

**Testing:** V1 pipelines are executing successfully. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55045)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger pmd, checkstylecodeformat

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 14 files at r1, 4 of 4 files at r2, 4 of 4 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55045)* status: 20 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/DependencyMetadata.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/55045#-NicBglR9i69x2Yy_3Ay:-NicBglR9i69x2Yy_3Az:bv2vm2k) ([raw file](https://github.com/harness/harness-core/blob/e23b7fee45b3fa45cf183a2744c82132d670bd2c/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/DependencyMetadata.java#L22)):*
> ```Java
> @Builder
> @OwnedBy(HarnessTeam.PIPELINE)
> public class DependencyMetadata {
> ```

should we return directly this map instead of DependencyMetadata?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 156 at r3](https://reviewable.io/reviews/harness/harness-core/55045#-NicBn95Bj_LGYIQxezu:-NicBn95Bj_LGYIQxezv:b17cwbl) ([raw file](https://github.com/harness/harness-core/blob/47cbdf094c6544d1524675e2cbec88db75cab7fe/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L156)):*
> ```Java
>       }
>     }
>     return Optional.empty();
> ```

why we are returning empty?
___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/plan_creation_service.proto` line 191 at r4](https://reviewable.io/reviews/harness/harness-core/55045#-NicCKOJ-BkqGRqx9jNS:-NicCKOJ-BkqGRqx9jNT:b6ribfa) ([raw file](https://github.com/harness/harness-core/blob/053a20447cecbcec9c07285b64ceb37e86254d8c/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/plan_creation_service.proto#L191)):*
> ```proto
>   // used in place of metadata map in v1 -> metadata passed to immediate children
>   HarnessStruct nodeMetadata = 4;
>   // metadata passed to all the children and grandchildren until leaf
> ```

nit: can we add file path where we have added only reserved keys which will transfer and not all

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55045)* status: 20 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/DependencyMetadata.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/55045#-NicBglR9i69x2Yy_3Ay:-Nicf3XV4o5g9p_kEw6C:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e23b7fee45b3fa45cf183a2744c82132d670bd2c/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/DependencyMetadata.java#L22)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should we return directly this map instead of DependencyMetadata?
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 156 at r3](https://reviewable.io/reviews/harness/harness-core/55045#-NicBn95Bj_LGYIQxezu:-NicfEnNBueZu9e2OmYH:b-5dmky8) ([raw file](https://github.com/harness/harness-core/blob/47cbdf094c6544d1524675e2cbec88db75cab7fe/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L156)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are returning empty?
</blockquote></details>

if the key is not present in dependency then we are returning empty
___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/plan_creation_service.proto` line 191 at r4](https://reviewable.io/reviews/harness/harness-core/55045#-NicCKOJ-BkqGRqx9jNS:-NicZNrdACBVgy3Yq4lW:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/053a20447cecbcec9c07285b64ceb37e86254d8c/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/plan_creation_service.proto#L191)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: can we add file path where we have added only reserved keys which will transfer and not all
</blockquote></details>

done

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 14 files at r1, 1 of 2 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55045)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55045)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 14 files at r1, 2 of 4 files at r2, 4 of 4 files at r3, 1 of 2 files at r4, 8 of 11 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55045)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55045)* status: :shipit: complete! ✓

**Review by raghavharness — APPROVED** [review]

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
