### PR TITLE
feat: [PL-22630]: populate errorMsg to FullSyncEntity DB

### PR DESCRIPTION
**Pull request by bhavya181**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30705)

### CODE REVIEW

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30705)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30705)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/mappers/GitFullSyncEntityInfoMapper.java, line 58 at r1](https://reviewable.io/reviews/harness/harness-core/30705#-MvcKIDE7cNFAqgrWNni:-MvcKIDE7cNFAqgrWNnj:bagslxa) ([raw file](https://github.com/harness/harness-core/blob/65a1df9c2a6d3505275add61d70d0d11d8b2cad4/136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/mappers/GitFullSyncEntityInfoMapper.java#L58)):*
> ```Java
>   }
> 
>   private String getLatestErrorMsg(List<String> errorMessage) {
> ```

Are we storing all error msgs in the entity and not just the latest error msg?

I am asking because you have changed from list to singleton error msg above

**Review by vikas-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30705)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30705#-:-MvcnCBdEUzK_smpJyAF:bnfp4nl)* status: :shipit: complete! ✓

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30705#-:-MvcpJJe2ybZVvT6v48G:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30705)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by sunnykesh-harness — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30705)* status: :shipit: complete! ✓

**Pull request merged**
