### PR TITLE
fix: [CDS-54146]: support fqn paths for multi service/env pipelines

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
Added support to handle array of service and environment values in multi service pipelines. The YAML structure varies from usual arrays of objects which have identifier key to identify them uniquely.
These arrays have serviceRef and environmentRef to identify them. 
fqnPath supplied by UI would be : 
```pipeline.stages.dep.spec.services.values.nginx.serviceInputs.serviceDefinition.spec.artifacts.primary.sources.s1.spec.tag```

## Tested
1. v2 single service
2. v2 multi service : account level and project level service (via postman)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45178)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/evaluators/CDYamlExpressionFunctor.java` line 168 at r1](https://reviewable.io/reviews/harness/harness-core/45178#-NQjFoScAPK_-hQ1tV3X:-NQjFoScAPK_-hQ1tV3Y:bunxmp7) ([raw file](https://github.com/harness/harness-core/blob/5e5d8eb123dd0473adfb6e04804861d1e6dfe6ec/125-cd-nextgen/modules/common/core/src/main/java/io/harness/evaluators/CDYamlExpressionFunctor.java#L168)):*
> ```Java
>         fqnToValueMap.put(String.join(".", fqnList), valueFromObject);
>         contextMap.put(arrayElement.getStringValue(YAMLFieldNameConstants.ENVIRONMENT_REF), valueFromObject);
>         fqnList.remove(fqnList.size() - 1);
> ```

can this be extracted out as a method ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45178)* status: 3 file(s) to review. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45178)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by inderschera — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45178)* status: :shipit: complete! ✓

**Pull request merged**
