### PR TITLE
feat: [CDS-36049]: Adding wrapper APIs for license usage in CD

### PR DESCRIPTION
**Pull request by shubham-in10se**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32093)

### CODE REVIEW

**Comment by shubham-in10se** [comment]
trigger ti0

**Comment by shubham-in10se** [comment]
CodeBaseHash-codebasehashcheck

**Comment by shubham-in10se** [comment]
trigger codebasehash

**Comment by shubham-in10se** [comment]
trigger messagecheck

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 22 of 22 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32093)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
> Reviewed 22 of 22 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32093)* status: :shipit: complete! ✓

**Pull request merged**
