### PR TITLE
feat: [IDP-283]: Connector Screen APIs

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Describe your changes
1. Connector Screen APIs (Get All connectors info, Create/Update connector info)
2. Flattened CatalogConnector collection 
3. Removed usage of Infra & Source Connector from Service layers
4. Will create separate PR for removing Infra/Source connector usages from Request/Response as FE also needs to make changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45614)

### CODE REVIEW

**Review by devesh-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45614)* status: 22 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/processor/impl/BitbucketConnectorProcessor.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/45614#-NRWLAGo195RIhWQUl8H:-NRWLAGo195RIhWQUl8I:b-fwxxrs) ([raw file](https://github.com/harness/harness-core/blob/282a51079541a4e04fb8d8b610221efe6b8eeb8d/idp-service/src/main/java/io/harness/idp/gitintegration/processor/impl/BitbucketConnectorProcessor.java#L79)):*
> ```Java
>       String locationParentPath, String remoteFolder, List<String> filesToPush) {
>     Pair<ConnectorInfoDTO, Map<String, BackstageEnvVariable>> connectorSecretsInfo = getConnectorAndSecretsInfo(
>         accountIdentifier, null, null, catalogConnectorInfo.getInfraConnector().getIdentifier());
> ```

can we rename this to generic name for connector as we are having only single type of connector ?



_Code quote:_
```Java
getInfraConnector()
```

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45614)* status: 22 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/processor/impl/BitbucketConnectorProcessor.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/45614#-NRWLAGo195RIhWQUl8H:-NRWN9I2EtQmYxRzwbld:b-nhokw5) ([raw file](https://github.com/harness/harness-core/blob/282a51079541a4e04fb8d8b610221efe6b8eeb8d/idp-service/src/main/java/io/harness/idp/gitintegration/processor/impl/BitbucketConnectorProcessor.java#L79)):*
<details><summary><i>Previously, devesh-harness wrote…</i></summary><blockquote>

can we rename this to generic name for connector as we are having only single type of connector ?
</blockquote></details>

Will raise a separate PR for cleaning this as CatalogConnectorInfo model is used by FE

**Review by devesh-harness — APPROVED** [review]
> Reviewed 10 of 22 files at r1, 9 of 10 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45614)* status: 22 file(s) to review. 1 of 2 approvals obtained.

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 8 of 22 files at r1, 8 of 10 files at r2, 1 of 3 files at r4, 5 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45614)* status: 5 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/entities/CatalogConnector.java` line 57 at r5](https://reviewable.io/reviews/harness/harness-core/45614#-NRXPUjUEt4eiRqu_2wc:-NRXPUjUEt4eiRqu_2wd:bc16g9z) ([raw file](https://github.com/harness/harness-core/blob/941d0f893b0ca6287ba3e503505282fe6c7e10bb/idp-service/src/main/java/io/harness/idp/gitintegration/entities/CatalogConnector.java#L57)):*
> ```Java
> @HarnessEntity(exportable = true)
> @OwnedBy(HarnessTeam.IDP)
> public class CatalogConnector
> ```

nit: Could we add an Entity suffix? Since we have been following that convention



_Code quote:_
```Java
CatalogConnector
```
___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/mappers/CatalogConnectorMapper.java` line 23 at r5](https://reviewable.io/reviews/harness/harness-core/45614#-NRXQnGa0lxP5MuS6jTM:-NRXQnGa0lxP5MuS6jTN:bdkfbod) ([raw file](https://github.com/harness/harness-core/blob/5d78ffc5c32383961f88c8b2941fdbd065016324/idp-service/src/main/java/io/harness/idp/gitintegration/mappers/CatalogConnectorMapper.java#L23)):*
> ```Java
>     CatalogConnectorInfo catalogConnectorInfo = new CatalogConnectorInfo();
>     catalogConnectorInfo.setInfraConnector(catalogConnector.getInfraConnector());
>     catalogConnectorInfo.setSourceConnector(catalogConnector.getSourceConnector());
> ```

Do we still need to call it infra connector? Can we just call it connector?
___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/mappers/ConnectorDetailsMapper.java` line 35 at r5](https://reviewable.io/reviews/harness/harness-core/45614#-NRXRBKmEYj-luPREMXO:-NRXRBKmEYj-luPREMXP:b-wq6d4s) ([raw file](https://github.com/harness/harness-core/blob/941d0f893b0ca6287ba3e503505282fe6c7e10bb/idp-service/src/main/java/io/harness/idp/gitintegration/mappers/ConnectorDetailsMapper.java#L35)):*
> ```Java
>       ConnectorDetails connectorDetails, String accountIdentifier, String infraConnectorType) {
>     return CatalogConnector.builder()
>         .identifier(Constants.IDP_PREFIX + connectorDetails.getIdentifier())
> ```

Why is the prefix needed?



_Code quote:_
```Java
IDP_PREFIX
```
___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/resources/ConnectorInfoApiImpl.java` line 59 at r5](https://reviewable.io/reviews/harness/harness-core/45614#-NRXVlSu9AlLx3YPOFp4:-NRXVlSvBvF2uspsc659:bmdkb6a) ([raw file](https://github.com/harness/harness-core/blob/941d0f893b0ca6287ba3e503505282fe6c7e10bb/idp-service/src/main/java/io/harness/idp/gitintegration/resources/ConnectorInfoApiImpl.java#L59)):*
> ```Java
>       return Response.status(Response.Status.CREATED).entity(ConnectorDetailsMapper.toDTO(catalogConnector)).build();
>     } catch (Exception e) {
>       log.error(e.getMessage());
> ```

Can we log the whole exception stack trace? instead of just message

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45614)* status: 12 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/mappers/CatalogConnectorMapper.java` line 23 at r5](https://reviewable.io/reviews/harness/harness-core/45614#-NRXQnGa0lxP5MuS6jTM:-NRXX08lC1BJ6fkAZPI6:b-3hp8an) ([raw file](https://github.com/harness/harness-core/blob/5d78ffc5c32383961f88c8b2941fdbd065016324/idp-service/src/main/java/io/harness/idp/gitintegration/mappers/CatalogConnectorMapper.java#L23)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Do we still need to call it infra connector? Can we just call it connector?
</blockquote></details>

We will be flattening the CatalogConnectorInfo model too. 
Will raise a separate PR for cleaning this model as it is currently used by FE for sending the payload
___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/mappers/ConnectorDetailsMapper.java` line 35 at r5](https://reviewable.io/reviews/harness/harness-core/45614#-NRXRBKmEYj-luPREMXO:-NRXZzAAAzmKvcs13i74:b-cp2uvc) ([raw file](https://github.com/harness/harness-core/blob/941d0f893b0ca6287ba3e503505282fe6c7e10bb/idp-service/src/main/java/io/harness/idp/gitintegration/mappers/ConnectorDetailsMapper.java#L35)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Why is the prefix needed?
</blockquote></details>

It's added just for our internal reference to know particular connectorId is used in IDP. 
Before the identifier looked like infraConnectorIdentifier_sourceConnectorIdentifier. Now, as we have removed infra/source terms we have added this prefix (Based on @sathish-soundarapandian suggestion)
___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/resources/ConnectorInfoApiImpl.java` line 59 at r5](https://reviewable.io/reviews/harness/harness-core/45614#-NRXVlSu9AlLx3YPOFp4:-NRXZefn9WN_uO_txUxD:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/941d0f893b0ca6287ba3e503505282fe6c7e10bb/idp-service/src/main/java/io/harness/idp/gitintegration/resources/ConnectorInfoApiImpl.java#L59)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we log the whole exception stack trace? instead of just message
</blockquote></details>

done
___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/entities/CatalogConnector.java` line 57 at r5](https://reviewable.io/reviews/harness/harness-core/45614#-NRXPUjUEt4eiRqu_2wc:-NRXY1949p1Ps74F4znd:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/941d0f893b0ca6287ba3e503505282fe6c7e10bb/idp-service/src/main/java/io/harness/idp/gitintegration/entities/CatalogConnector.java#L57)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

nit: Could we add an Entity suffix? Since we have been following that convention
</blockquote></details>

done

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45614)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by devesh-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r5, 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45614)* status: :shipit: complete! ✓

**Pull request merged**
