### PR TITLE
[fix]: [PL-28017]: Throw Azure AuthenticationException instead of log…

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

This PR handles the AuthenticationException thrown by Azure vault in case of an invalid credentials. Previously, the exception was caught and logged. However, since the exception was not thrown the execution flow continues only to hit another exception further down the flow which gets displayed in the UI. Thus, the actual error caused by the invalid credentials never propagates back to the UI which in turn doesn't convey the actual issue to the end user.

The AuthenticationException need not be retried thus it's also handled only once.

[Test Scenario] - Create a new Azure secret manager connector and then update its credentials by changing to invalid client_id.
[Test Outcome] - Outcome: Azure doesn’t recognize the client_id and thus it throws a “AuthenticationException”.

[Prior Error Message on UI]-
Azure Key Vault Operation error: After 3 tries, encryption for secret harnessAzureVaultValidation failed.
Azure Key Vault Operation error: The Secret could not be saved in Azure Vault. accountId: wFHXHD0RRQWoO8tIZT5YVw, Secret name: harnessAzureVaultValidation, Vault name: QAAutomationKeyVault
Azure Key Vault Operation error: Status code 401, {"error":{"code":"Unauthorized","message":"AKV10000: Request is missing a Bearer or PoP token."}}

[New Error Message on UI with this fix]-
{"error_description":"AADSTS700016: Application with identifier '38fca8d7-4dda-41d5-b106-e5d8712b733b' was not found in the directory 'Harness Inc'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: 4d373837-105a-40e8-8068-7407d0fceb00\r\nCorrelation ID: d0e6c22c-5435-4c2e-9454-f069250f1fe9\r\nTimestamp: 2022-09-06 22:48:47Z","error":"unauthorized_client","error_uri":"https:\/\/[login.windows.net](https://localhost:8181/login.windows.net)\/error?code=700016"}
Failed to authenticate in azure cloud

As seen above the error code and message contained in the AuthenticationException provides sufficient details on what needs to be corrected.

## Checklist
- [ Yes ] I've documented the changes in the PR description - Check [PL-28017](https://harness.atlassian.net/browse/PL-28017) for sufficient summary.
- [ Yes ] I've tested this change either in PR or local environment - I have verified this change in the local test environment for secret manager update.
- [ Yes ] I've added unit tests to verify the changes - Added sufficient unit test that covers all possible scenarios for this change.
- [ N/A ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37239)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37239)

**Review by rickmarry — APPROVED** [review]
looks good

**Review by rickmarry — COMMENTED** [review]
> looks good
Normally, I would agree with PMD and it's assertion that catching an exception just to turn around and re-throw it is no good but in this case, it's not that simple.. here, you're calling out one particular exception and handling it in a different manner than the broader ones.  I don't see re-throwing in this case as a problem

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37239#-:-NBK8alkAMJIS77B1a2T:bbmbb1w)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by rickmarry — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37239)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37239)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`890-sm-core/src/test/java/io/harness/encryptors/AzureVaultEncryptorTest.java` line 139 at r2](https://reviewable.io/reviews/harness/harness-core/37239#-NBPNNIg-XYoDF9MAkby:-NBPNNIg-XYoDF9MAkbz:b-z22kto) ([raw file](https://github.com/harness/harness-core/blob/837df044d785f78dbd5b0415135de159c888abe6/890-sm-core/src/test/java/io/harness/encryptors/AzureVaultEncryptorTest.java#L139)):*
> ```Java
>             + " This can happen if the application has not been installed by the administrator"
>             + " of the tenant or consented to by any user in the tenant. You may have sent your"
>             + " authentication request to the wrong tenant."));
> ```

this is too verbose - just write something minimal and test its presence



_Code quote:_
```Java
            "'38fca8d7-4dda-41d5-b106-e5d8712b733b' was not found in the directory 'Harness Inc'."
            + " This can happen if the application has not been installed by the administrator"
            + " of the tenant or consented to by any user in the tenant. You may have sent your"
            + " authentication request to the wrong tenant."));
```
___
*[`890-sm-core/src/test/java/io/harness/encryptors/AzureVaultEncryptorTest.java` line 151 at r2](https://reviewable.io/reviews/harness/harness-core/37239#-NBPNJUZ1-O18l-s_Dcn:-NBPNJUZ1-O18l-s_Dco:bqeoxfm) ([raw file](https://github.com/harness/harness-core/blob/837df044d785f78dbd5b0415135de159c888abe6/890-sm-core/src/test/java/io/harness/encryptors/AzureVaultEncryptorTest.java#L151)):*
> ```Java
>     } catch (Exception ex) {
>       fail("Wrong exception thrown - AuthenticationException expected");
>     }
> ```

assertThrows does not work?



_Code quote:_
```Java
    try {
      azureVaultEncryptor.createSecret(azureVaultConfig.getAccountId(), name, plainText, azureVaultConfig);
    } catch (SecretManagementDelegateException ex) {
      String errorMsg = ex.getMessage();
      ErrorCode errorCode = ex.getCode();
      assertThat(errorCode).isEqualTo(AZURE_AUTHENTICATION_ERROR);
      assertThat(errorMsg).contains(
          "'38fca8d7-4dda-41d5-b106-e5d8712b733b' was not found in the directory 'Harness Inc'.");
    } catch (Exception ex) {
      fail("Wrong exception thrown - AuthenticationException expected");
    }
```
___
*[`890-sm-delegate/src/main/java/io/harness/helpers/ext/azure/KeyVaultADALAuthenticator.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/37239#-NBPMQ1UCjfACe7zDSmC:-NBPMQ1UCjfACe7zDSmD:b-1wia35) ([raw file](https://github.com/harness/harness-core/blob/837df044d785f78dbd5b0415135de159c888abe6/890-sm-delegate/src/main/java/io/harness/helpers/ext/azure/KeyVaultADALAuthenticator.java#L55)):*
> ```Java
>           Throwable ex = e.getCause();
>           if (ex instanceof AuthenticationException) {
>             throw(AuthenticationException) ex;
> ```

add a catch block like the other PR



_Code quote:_
```Java
          if (ex instanceof AuthenticationException) {
            throw(AuthenticationException) ex;
```

**Review by gn-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37239)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37239)* status: 4 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`890-sm-core/src/test/java/io/harness/encryptors/AzureVaultEncryptorTest.java` line 139 at r2](https://reviewable.io/reviews/harness/harness-core/37239#-NBPNNIg-XYoDF9MAkby:-NBTgJPeD7BaWfmQ_PbO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/837df044d785f78dbd5b0415135de159c888abe6/890-sm-core/src/test/java/io/harness/encryptors/AzureVaultEncryptorTest.java#L139)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

this is too verbose - just write something minimal and test its presence
</blockquote></details>

Done.
___
*[`890-sm-core/src/test/java/io/harness/encryptors/AzureVaultEncryptorTest.java` line 151 at r2](https://reviewable.io/reviews/harness/harness-core/37239#-NBPNJUZ1-O18l-s_Dcn:-NBThgDw8DWMAX9Srzld:bi6ic9c) ([raw file](https://github.com/harness/harness-core/blob/837df044d785f78dbd5b0415135de159c888abe6/890-sm-core/src/test/java/io/harness/encryptors/AzureVaultEncryptorTest.java#L151)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

assertThrows does not work?
</blockquote></details>

Will update the tests using assert.
___
*[`890-sm-delegate/src/main/java/io/harness/helpers/ext/azure/KeyVaultADALAuthenticator.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/37239#-NBPMQ1UCjfACe7zDSmC:-NBTs-3ICTUsN6r52gSp:b-2y3o5) ([raw file](https://github.com/harness/harness-core/blob/837df044d785f78dbd5b0415135de159c888abe6/890-sm-delegate/src/main/java/io/harness/helpers/ext/azure/KeyVaultADALAuthenticator.java#L55)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

add a catch block like the other PR
</blockquote></details>

Actually the AuthenticationException is nested within the cause of the ExecutionException that's caught here. So that's why catching the outer exception and then getting the actual AuthenticationException from within it.

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37239)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by rickmarry — APPROVED** [review]
Looks good! Nice job with all the unit tests!

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by gn-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37239)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37239)* status: :shipit: complete! ✓

**Pull request merged**
