### PR TITLE
feat: [CDS-2993]: k8s release history interface integration

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
## Describe your changes
Continuation of change https://github.com/harness/harness-core/pull/37222
Spec: https://harness.atlassian.net/wiki/spaces/CDP/pages/21075394834/Kubernetes+Declarative+Rollback

Includes changes for integrating the newly created release history interface with CG/NG K8s request handlers.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37776)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 49 Issues 
* Vulnerability 18 Vulnerabilities 
 * Code issue 22 Code issues 
* Anti-pattern 9 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37776)

**Comment by yogesh-chauhan** [comment]
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java` line 311 at r4](https://reviewable.io/reviews/harness/harness-core/37776#-ND1gVjWC_Q-sBHSm2Fo:-ND1gVjWC_Q-sBHSm2Fp:b-416s7y) ([raw file](https://github.com/harness/harness-core/blob/9714ef8e0e32bca8912df54b2cb9eefd8de52dc2/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java#L311)):*
> ```Java
> 
>       if (isNotTrue(k8sBlueGreenDeployTaskParameters.getSkipVersioningForAllK8sObjects())
>           && !k8sBlueGreenDeployTaskParameters.isUseDeclarativeRollback()) {
> ```

we need to document this that versioning will be disabled with this. Since this is a change in behaviour

**Comment by yogesh-chauhan** [comment]
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java` line 413 at r4](https://reviewable.io/reviews/harness/harness-core/37776#-ND1hrS3-UVUKdcbImXA:-ND1hrS3-UVUKdcbImXB:b2ukqmd) ([raw file](https://github.com/harness/harness-core/blob/9714ef8e0e32bca8912df54b2cb9eefd8de52dc2/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java#L413)):*
> ```Java
>           "\nCurrent release number is: " + k8sBlueGreenHandlerConfig.getCurrentRelease().getReleaseNumber());
> 
>       if (isNotTrue(k8sBlueGreenDeployTaskParameters.getSkipVersioningForAllK8sObjects())
> ```

should it not be OR instead of AND ?

**Comment by yogesh-chauhan** [comment]
*[`960-api-services/src/main/java/io/harness/k8s/releasehistory/K8SLegacyReleaseHistory.java` line 69 at r4](https://reviewable.io/reviews/harness/harness-core/37776#-ND2JEgj-QxCNeoZneQT:-ND2JEgj-QxCNeoZneQU:bmaxs3f) ([raw file](https://github.com/harness/harness-core/blob/9714ef8e0e32bca8912df54b2cb9eefd8de52dc2/960-api-services/src/main/java/io/harness/k8s/releasehistory/K8SLegacyReleaseHistory.java#L69)):*
> ```Java
>         .filter(release
>             -> currentReleaseNumber != release.getReleaseNumber() && release.getManagedWorkload() != null
>                 && release.getManagedWorkload().getName().endsWith(color))
> ```

can we have some first class field in Release object to tell about the color instead of inferring it from the workload name ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 8 of 58 files at r1, 3 of 16 files at r2, 21 of 36 files at r3, 8 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37776)* status: 16 file(s) to review. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java` line 243 at r4](https://reviewable.io/reviews/harness/harness-core/37776#-ND24s4_A4VJOAd94SMT:-ND24s4_A4VJOAd94SMU:b-4ca06d) ([raw file](https://github.com/harness/harness-core/blob/9714ef8e0e32bca8912df54b2cb9eefd8de52dc2/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java#L243)):*
> ```Java
>     //    releaseHistory.setReleaseStatus(Status.Failed);
>     //    k8sTaskHelperBase.saveReleaseHistoryInConfigMap(
>     //        canaryHandlerConfig.getKubernetesConfig(), releaseName, releaseHistory.getAsYaml());
> ```

do we need this method anymore ?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java` line 167 at r4](https://reviewable.io/reviews/harness/harness-core/37776#-ND256Xd13t_VW3Ofnd3:-ND256Xd13t_VW3Ofnd4:b6mgg6j) ([raw file](https://github.com/harness/harness-core/blob/9714ef8e0e32bca8912df54b2cb9eefd8de52dc2/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java#L167)):*
> ```Java
>     } else {
>       long steadyStateTimeoutInMillis = getTimeoutMillisFromMinutes(timeoutInMin);
>       List<KubernetesResourceId> managedResourceIds =
> ```

can managed workloads be empty/null ?

**Comment by abhinavsingh1196** [comment]
trigger feature-build

**Comment by abhinavsingh1196** [comment]
trigger feature-build

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 16 files at r2, 7 of 36 files at r3, 11 of 21 files at r5, 8 of 12 files at r6, 5 of 6 files at r7, 4 of 5 files at r8, 4 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37776)* status: 5 file(s) to review. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 36 files at r3, 1 of 21 files at r5, 1 of 12 files at r6, 1 of 6 files at r7, 1 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37776)* status: 0 of 1 approvals obtained.

**Comment by abhinavsingh1196** [comment]
*[`960-api-services/src/main/java/io/harness/k8s/releasehistory/K8SLegacyReleaseHistory.java` line 69 at r4](https://reviewable.io/reviews/harness/harness-core/37776#-ND2JEgj-QxCNeoZneQT:-NGptdPN-Rr2yOciv7bT:bjnpy6w) ([raw file](https://github.com/harness/harness-core/blob/9714ef8e0e32bca8912df54b2cb9eefd8de52dc2/960-api-services/src/main/java/io/harness/k8s/releasehistory/K8SLegacyReleaseHistory.java#L69)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we have some first class field in Release object to tell about the color instead of inferring it from the workload name ?
</blockquote></details>

will leave as is for old release history object, but will implement this for new release history (based on a label inside the release secret)

**Comment by abhinavsingh1196** [comment]
trigger feature-build

**Comment by abhinavsingh1196** [comment]
trigger feature-build

**Comment by abhinavsingh1196** [comment]
trigger feature-build

**Comment by abhinavsingh1196** [comment]
trigger feature-build

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 9 of 12 files at r10, 2 of 2 files at r11, 13 of 13 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37776)* status: Some of the checks are too old. 24 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 20 of 58 files at r1, 5 of 16 files at r2, 19 of 36 files at r3, 1 of 9 files at r4, 8 of 21 files at r5, 5 of 12 files at r6, 5 of 6 files at r7, 2 of 5 files at r9, 8 of 12 files at r10, 2 of 2 files at r11, 12 of 13 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37776)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by abhinavsingh1196** [comment]
trigger feature-build

**Comment by abhinavsingh1196** [comment]
trigger ti0 ti1 ti2 ti3 ti4 ft1 ft2 codebasehash checkstylecodeformat messagecheck pmd

**Comment by abhinavsingh1196** [comment]
trigger featurenamecheck

**Comment by abhinavsingh1196** [comment]
trigger featurenamecheck

**Comment by abhinavsingh1196** [comment]
trigger feature-build

**Comment by abhinavsingh1196** [comment]
trigger feature-build

**Review by abosii-harness — COMMENTED** [review]
> Reviewed 5 of 12 files at r10, 5 of 13 files at r13, 1 of 1 files at r16, 1 of 4 files at r17, 5 of 6 files at r18, 1 of 1 files at r19, 12 of 13 files at r20, 1 of 1 files at r21, 2 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37776)* status: 22 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseSecretHelper.java` line 57 at r22](https://reviewable.io/reviews/harness/harness-core/37776#-NIm85kA9ubpS9ltyPvI:-NIm85kB0qfIbGQMV5xW:b9dbcvw) ([raw file](https://github.com/harness/harness-core/blob/7d8ab8d2e05278d3263a588e2685882b2303d455/960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseSecretHelper.java#L57)):*
> ```Java
> 
>   public String generateName(@NotNull String releaseName, int releaseNumber) {
>     return String.join(RELEASE_NAME_DELIMITER, RELEASE_KEY, releaseName, String.valueOf(releaseNumber));
> ```

Will it make a bit of sense to add to RELEASE_KEY something like harness.release?

**Comment by abhinavsingh1196** [comment]
trigger feature-build

**Comment by abhinavsingh1196** [comment]
*[`960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseSecretHelper.java` line 57 at r22](https://reviewable.io/reviews/harness/harness-core/37776#-NIm85kA9ubpS9ltyPvI:-NIpobJs4hpnPcMqUvFN:b-aizovd) ([raw file](https://github.com/harness/harness-core/blob/7d8ab8d2e05278d3263a588e2685882b2303d455/960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseSecretHelper.java#L57)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Will it make a bit of sense to add to RELEASE_KEY something like harness.release?
</blockquote></details>

Done, changed the prefix from `release` to `harness.release`

**Comment by abhinavsingh1196** [comment]
trigger feature-build

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 4 files at r17, 4 of 6 files at r18, 10 of 13 files at r20, 1 of 1 files at r21, 1 of 2 files at r22, 3 of 4 files at r23, 1 of 3 files at r24, 1 of 5 files at r25, 2 of 4 files at r26, 8 of 8 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37776)* status: 15 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by abhinavsingh1196** [comment]
trigger feature-build

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 18 files at r28, 22 of 26 files at r29, 5 of 7 files at r30, 4 of 4 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37776)* status: 42 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 3 of 13 files at r13, 3 of 4 files at r23, 1 of 5 files at r25, 1 of 4 files at r26, 2 of 8 files at r27, 4 of 18 files at r28, 22 of 26 files at r29, 5 of 7 files at r30, 4 of 4 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37776)* status: :shipit: complete! ✓

**Pull request merged**
