### PR TITLE
[feat]: [CDS-43073]: Git sync new error handling

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38650)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/helpers/InputsValidator.java` line 229 at r2](https://reviewable.io/reviews/harness/harness-core/38650#-NE_ButA-Denh8eTa3je:-NE_ButA-Denh8eTa3jf:butfta2) ([raw file](https://github.com/harness/harness-core/blob/208a47ef17667b6b8b4ff64feccdeb5c52743a83/840-template-service/src/main/java/io/harness/template/helpers/InputsValidator.java#L229)):*
> ```Java
>     JsonNode templateNodeValue = templateNode.getCurrJsonNode();
>     // Template YAML corresponding to the TemplateRef and Version Label
>     TemplateRefreshServiceImpl.TemplateEntityGetResponse templateEntityGetResponse =
> ```

We should move out `TemplateEntityGetResponse` this to its own class.

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/TemplateRefreshServiceImpl.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/38650#-NE_Fuo57LWC3vCWArC5:-NE_Fuo6AsXxgi_yDmgr:b-oup75v) ([raw file](https://github.com/harness/harness-core/blob/208a47ef17667b6b8b4ff64feccdeb5c52743a83/840-template-service/src/main/java/io/harness/template/services/TemplateRefreshServiceImpl.java#L87)):*
> ```Java
>     TemplateEntity templateEntity = NGTemplateDtoMapper.toTemplateEntity(
>         accountId, orgId, projectId, templateIdentifier, versionLabel, refreshedYaml);
>     GitEntityInfo gitEntityInfo = GitAwareContextHelper.getGitRequestParamsInfo();
> ```

do we need to fetch from context now also ? I thought we can just pass on from the templateEntityGetResponse

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/template/service/PipelineRefreshServiceImpl.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/38650#-NE_GG5a0YfhpdOrLgPX:-NE_GG5a0YfhpdOrLgPY:b-pa937m) ([raw file](https://github.com/harness/harness-core/blob/208a47ef17667b6b8b4ff64feccdeb5c52743a83/pipeline-service/service/src/main/java/io/harness/pms/template/service/PipelineRefreshServiceImpl.java#L88)):*
> ```Java
> 
>     String pipelineYaml = pipelineEntity.getYaml();
>     if (Boolean.TRUE.equals(pipelineEntity.getTemplateReference())) {
> ```

I do not think this check is needed now. We need to call validate/refresh even if there is no template ref because we do reconciliation for services and environments also

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/template/service/PipelineRefreshServiceImpl.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/38650#-NE_GQ9K5hrGZ2zFyAb5:-NE_GQ9K5hrGZ2zFyAb6:b-pa937m) ([raw file](https://github.com/harness/harness-core/blob/208a47ef17667b6b8b4ff64feccdeb5c52743a83/pipeline-service/service/src/main/java/io/harness/pms/template/service/PipelineRefreshServiceImpl.java#L59)):*
> ```Java
>     PipelineEntity pipelineEntity = getPipelineEntity(accountId, orgId, projectId, pipelineIdentifier);
> 
>     if (Boolean.TRUE.equals(pipelineEntity.getTemplateReference())) {
> ```

I do not think this check is needed now. We need to call validate/refresh even if there is no template ref because we do reconciliation for services and environments also

**Comment by utkarshchoubey-harness** [comment]
trigger feature-build

**Comment by utkarshchoubey-harness** [comment]
trigger feature-build

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 3 of 19 files at r1, 3 of 14 files at r2, 7 of 10 files at r4, 1 of 2 files at r5, 5 of 6 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38650)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 82 at r7](https://reviewable.io/reviews/harness/harness-core/38650#-NGClF6U70cGP-yhv0Jw:-NGClF6U70cGP-yhv0Jx:b-gwdxb0) ([raw file](https://github.com/harness/harness-core/blob/fa2b3eaa4b4a8ee2a27bed120dd865183f19490f/840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L82)):*
> ```Java
> 
>   public TemplateResponseDTO writeTemplateResponseDto(TemplateEntityGetResponse templateEntityGetResponse) {
>     TemplateEntity templateEntity = templateEntityGetResponse.getTemplateEntity();
> ```

nit: remove duplicate code
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 291 at r7](https://reviewable.io/reviews/harness/harness-core/38650#-NGCnzKCDjEdGeSK13ww:-NGCnzKDDkWyyNdK-Ks3:bi4nlgu) ([raw file](https://github.com/harness/harness-core/blob/d61a950cce0713372dfe134683e4596225703d75/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L291)):*
> ```Java
>         FeatureRestrictionName.TEMPLATE_SERVICE, templateEntity.getAccountIdentifier());
> 
>     TemplateUtils.setupGitParentEntityDetails(templateEntity.getAccountIdentifier(), templateEntity.getOrgIdentifier(),
> ```

this should not be removed.



_Code quote:_
```Java
    TemplateUtils.setupGitParentEntityDetails(templateEntity.getAccountIdentifier(), templateEntity.getOrgIdentifier(),
        templateEntity.getProjectIdentifier());
```
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1110 at r7](https://reviewable.io/reviews/harness/harness-core/38650#-NGCoSKuBOFF68LUxlOr:-NGCoSKuBOFF68LUxlOs:b-v2fiee) ([raw file](https://github.com/harness/harness-core/blob/fa2b3eaa4b4a8ee2a27bed120dd865183f19490f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1110)):*
> ```Java
>       TemplateEntity templateEntity, String oldOrgIdentifier, String oldProjectIdentifier) {
>     TemplateUtils.setupGitParentEntityDetails(templateEntity.getAccountIdentifier(), oldOrgIdentifier,
>         oldProjectIdentifier, templateEntity.getRepo(), templateEntity.getConnectorRef());
> ```

nit: check if connectorRef or repo can change on template update. If yes, this could cause issues.
___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateRefreshServiceImpl.java` line 97 at r7](https://reviewable.io/reviews/harness/harness-core/38650#-NGCq6asAkheO_BDLAHI:-NGCq6asAkheO_BDLAHJ:b4ma07g) ([raw file](https://github.com/harness/harness-core/blob/fa2b3eaa4b4a8ee2a27bed120dd865183f19490f/840-template-service/src/main/java/io/harness/template/services/TemplateRefreshServiceImpl.java#L97)):*
> ```Java
>           gitEntityInfo.setFilePath(templateResponse.getGitDetails().getFilePath());
>         }
>       }
> ```

nit: shouldn't we call GitAwareContextHelper.updateGitEntityContext(gitEntityInfo); after this?
___
*[`840-template-service/src/main/java/io/harness/template/utils/TemplateUtils.java` line 48 at r7](https://reviewable.io/reviews/harness/harness-core/38650#-NGCot4985NxXl_3agal:-NGCot4985NxXl_3agam:brpveye) ([raw file](https://github.com/harness/harness-core/blob/fa2b3eaa4b4a8ee2a27bed120dd865183f19490f/840-template-service/src/main/java/io/harness/template/utils/TemplateUtils.java#L48)):*
> ```Java
>   }
> 
>   public void setupGitParentEntityDetails(String accountIdentifier, String orgIdentifier, String projectIdentifier,
> ```

nit: create separate overloaded method to set repo and connector.
If they are passed we need to set those.
this method should remain as it is.
___
*[`840-template-service/src/main/java/io/harness/template/utils/TemplateUtils.java` line 55 at r7](https://reviewable.io/reviews/harness/harness-core/38650#-NGCnN13Dtwws7s80KXG:-NGCnN13Dtwws7s80KXH:b-n2tnng) ([raw file](https://github.com/harness/harness-core/blob/fa2b3eaa4b4a8ee2a27bed120dd865183f19490f/840-template-service/src/main/java/io/harness/template/utils/TemplateUtils.java#L55)):*
> ```Java
>       if (EmptyPredicate.isNotEmpty(repoFromTemplate)) {
>         gitEntityInfo.setParentEntityRepoName(repoFromTemplate);
>       } else if (!GitAwareContextHelper.isNullOrDefault(gitEntityInfo.getRepoName())) {
> ```

nit: revist this. Might not cover all cases like if we want to explicitly set repoFromTemplate as null, it won't work.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/template/service/PipelineRefreshServiceImpl.java` line 99 at r7](https://reviewable.io/reviews/harness/harness-core/38650#-NGCr5XEEXorvyHo3scq:-NGCr5XEEXorvyHo3scr:b-bi42d) ([raw file](https://github.com/harness/harness-core/blob/fa2b3eaa4b4a8ee2a27bed120dd865183f19490f/pipeline-service/service/src/main/java/io/harness/pms/template/service/PipelineRefreshServiceImpl.java#L99)):*
> ```Java
>   @Override
>   public boolean recursivelyRefreshAllTemplateInputsInPipeline(String accountId, String orgId, String projectId,
>       String pipelineIdentifier, GitEntityUpdateInfoDTO gitEntityBasicInfo) {
> ```

nit: changes not required.

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38650)* status: :shipit: complete! ✓

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 3 of 19 files at r1, 3 of 14 files at r2, 7 of 10 files at r4, 1 of 2 files at r5, 5 of 6 files at r6, 2 of 4 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38650)* status: :shipit: complete! ✓

**Pull request merged**
