### PR TITLE
[feat]: [OPA-215]: add opa audit event data

### PR DESCRIPTION
**Pull request by dwarren-dev**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33031)

### CODE REVIEW

**Comment by dwarren-dev** [comment]
trigger ti0

**Comment by dwarren-dev** [comment]
trigger ti1

**Comment by dwarren-dev** [comment]
trigger ti2

**Comment by dwarren-dev** [comment]
trigger ti3

**Review by nishantsaini20 — DISMISSED** [review]
> Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33031)* status: Some of the checks are too old.

**Review by scottyw — APPROVED** [review]
Looks alright to me

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33031)* status: :shipit: complete! ✓

**Review by scottyw — APPROVED** [review]
+1

**Pull request merged**
