### PR TITLE
[feat]: [PIE-9144]: Plan transformation changes for Pipeline Rollback

### PR DESCRIPTION
**Pull request by namanvermah**
The new method in pipeline executor will be called by PipelineRollbackStageStep, which is yet to be added. Until it is added, this flow won't be touched, hence this is a noop change.
Also, PipelineRollbackStageHelper will be used to add other methods later on

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45519)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 115 at r2](https://reviewable.io/reviews/harness/harness-core/45519#-NRCjcID6xm-VJyXUhGz:-NRCjcID6xm-VJyXUhH-:b-weog29) ([raw file](https://github.com/harness/harness-core/blob/44c8e4f3b047aec2cecb82ddf80220adbcc7e2ba/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L115)):*
> ```Java
>   }
> 
>   String transformProcessedYamlForPipelineRollbackMode(String processedYaml, String originalPlanExecutionId) {
> ```

Can we add a comment as to what this function is doing ?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 261 at r2](https://reviewable.io/reviews/harness/harness-core/45519#-NRCjnyF6s_f3Qo82Hki:-NRCjnyF6s_f3Qo82Hkj:b-bcwosl) ([raw file](https://github.com/harness/harness-core/blob/44c8e4f3b047aec2cecb82ddf80220adbcc7e2ba/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L261)):*
> ```Java
>     // todo: remove the use of stage fqn here once fork and strategy are divided in sub categories of step and stage
>     String stageFqn = planNode.getStageFqn();
>     return Arrays.asList(StepCategory.FORK, StepCategory.STRATEGY).contains(stepCategory)
> ```

Lets add a comment as to why this is required?

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45519)* status: 4 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipelinerollback/PipelineRollbackStageHelper.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/45519#-NRDJIBt0FuK3ulr_D4l:-NRDJIBu7T8c2ctDjkdm:b-unom9p) ([raw file](https://github.com/harness/harness-core/blob/44c8e4f3b047aec2cecb82ddf80220adbcc7e2ba/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipelinerollback/PipelineRollbackStageHelper.java#L20)):*
> ```Java
> @Slf4j
> @OwnedBy(PIPELINE)
> public class PipelineRollbackStageHelper {
> ```

for constants have final class

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45519)* status: 5 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipelinerollback/PipelineRollbackStageHelper.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/45519#-NRDJIBt0FuK3ulr_D4l:-NRDPXrmBds8PzWiNTTH:bwm8z59) ([raw file](https://github.com/harness/harness-core/blob/44c8e4f3b047aec2cecb82ddf80220adbcc7e2ba/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipelinerollback/PipelineRollbackStageHelper.java#L20)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

for constants have final class
</blockquote></details>

this isn't a constants class, will add methods to this in the next PR
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 503 at r2](https://reviewable.io/reviews/harness/harness-core/45519#-NRCjTZr3IoSzE9oeWEI:-NRDPfTyEZJOSCJchniC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/44c8e4f3b047aec2cecb82ddf80220adbcc7e2ba/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L503)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we create a PipelineRollbackUtility and move this function there?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 115 at r2](https://reviewable.io/reviews/harness/harness-core/45519#-NRCjcID6xm-VJyXUhGz:-NRDPgUQCh_0Rs4Hs6AV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/44c8e4f3b047aec2cecb82ddf80220adbcc7e2ba/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L115)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we add a comment as to what this function is doing ?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 261 at r2](https://reviewable.io/reviews/harness/harness-core/45519#-NRCjnyF6s_f3Qo82Hki:-NRDPh9G3Zq4bFP7TAQ3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/44c8e4f3b047aec2cecb82ddf80220adbcc7e2ba/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L261)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Lets add a comment as to why this is required?
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45519)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Pull request merged**
