### PR TITLE
[feat]: [CDS-79050]: Set Identifier of principal as identifier of triggerByInfo in-case of null email.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Context: Email is used to set identifier of the UserPrincipal. It can be null at times.
Change: Whenever email is null, have used the identifier of triggeredByInfo for identifier of the UserPrincipal.
Testing: Locally, the same object on QA which were stuck were transferred to auditDb from outbox.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52751)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52751)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 281 at r1](https://reviewable.io/reviews/harness/harness-core/52751#-Ne81yUh04gvcDV4zrbW:-Ne81yUh04gvcDV4zrbX:b6be4f) ([raw file](https://github.com/harness/harness-core/blob/ad46738577f5d376ff440487d882fe1105b6dcdd/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L281)):*
> ```Java
>       return nodeExecutionEventData.getTriggeredBy().getExtraInfo().get("email");
>     }
>     return nodeExecutionEventData.getTriggeredBy().getIdentifier();
> ```

we should add empty check on identifier as well, if empty send system user just like in aborted

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52751)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 281 at r1](https://reviewable.io/reviews/harness/harness-core/52751#-Ne81yUh04gvcDV4zrbW:-Ne8B0MXCThOmxF9OgFq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ad46738577f5d376ff440487d882fe1105b6dcdd/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L281)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should add empty check on identifier as well, if empty send system user just like in aborted
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52751)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/52751#-Ne8QZTrAR50qoJ2uOR4:-Ne8QZTrAR50qoJ2uOR5:b-7xmjww) ([raw file](https://github.com/harness/harness-core/blob/0917351af752e66491c524a57b23c1b76387f94c/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L71)):*
> ```Java
> 
>   @Getter private final Subject<PipelineActionObserver> pipelineActionObserverSubject = new Subject<>();
>   private static final String SYSTEM_USER = "systemUser";
> ```

I think constants alrady exists in Abort flow. Can we reuse?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52751)* status: 1 change requests. 1 of 2 approvals obtained.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52751)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/52751#-Ne8QZTrAR50qoJ2uOR4:-Ne99K0l1JH3G5Uvx1jL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0917351af752e66491c524a57b23c1b76387f94c/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L71)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think constants alrady exists in Abort flow. Can we reuse?
</blockquote></details>

Done.

**Comment by senjucanon2** [comment]
trigger uts

**Review by rohitk-h — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52751)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52751)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52751)* status: :shipit: complete! ✓

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
