### PR TITLE
[feat]: [PIE-2360]: Add support for expansions based on local FQNs

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30052)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger ti0, ti1, ti2, ti3, ti4, ft1, ft2

**Comment by namanvermah** [comment]
Proto changes are not related to any delegate task, hence the hash change is backwards compatible.

**Comment by namanvermah** [comment]
trigger ti0, ti1, ti2, ti3, ti4, ft1, ft2

**Review by hextechpal — APPROVED** [review]
> Reviewed 12 of 18 files at r1, 3 of 4 files at r2, 4 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30052)* status: 6 file(s) to review.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 12 of 18 files at r1, 3 of 4 files at r2, 2 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30052)* status: 2 file(s) to review.

**Comment by namanvermah** [comment]
trigger ti0, ti3

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30052)* status: 2 file(s) to review.

**Pull request merged**
