### PR TITLE
fix: [PL-40592]: Iterator to cleanup invalid audits in CG

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
This PR adds an iterator which deletes the records in the "audits" collection (CG) satisfying the following conditions-
1. "accountId" is null.
2. The record is more than 3 months old.
Such records are invalid and do not have any real corresponding records in the "entityAuditRecords" collection. Hence, these can be safely removed.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51988)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger smartchecks

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger ut6

**Comment by tiwaritejas** [comment]
trigger uts

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51988)* status: Some of the checks are too old. 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 510 at r2](https://reviewable.io/reviews/harness/harness-core/51988#-NcvkZTD46GeBdJbxzXh:-NcvkZTD46GeBdJbxzXi:bdeyfx5) ([raw file](https://github.com/harness/harness-core/blob/a9193472ea3d81e25397978384177005e379ecf9/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L510)):*
> ```Java
>             return;
>           }
>           sleep(Duration.ofMillis(200));
> ```

I don't see a need of this.
___
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 518 at r2](https://reviewable.io/reviews/harness/harness-core/51988#-NcvkpD54CR0QhW4rafs:-NcvkpD54CR0QhW4raft:baqusnp) ([raw file](https://github.com/harness/harness-core/blob/a9193472ea3d81e25397978384177005e379ecf9/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L518)):*
> ```Java
>                                  .getQueryObject(),
>                            projection)
>                        .limit(batchSize);
> ```

Duplicate criteria.
___
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 527 at r2](https://reviewable.io/reviews/harness/harness-core/51988#-NcvluCVBhh1Md7RUBT9:-NcvluCVBhh1Md7RUBTA:blqob3w) ([raw file](https://github.com/harness/harness-core/blob/a9193472ea3d81e25397978384177005e379ecf9/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L527)):*
> ```Java
>       }
> 
>       log.info("Number of audits records processed: {}, deleted: {}", updated, deleted);
> ```

Place this at correct place. Looks like it will never get printed.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51988)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 510 at r2](https://reviewable.io/reviews/harness/harness-core/51988#-NcvkZTD46GeBdJbxzXh:-Ncvy_7a5MrYCkz9Ak_P:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a9193472ea3d81e25397978384177005e379ecf9/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L510)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

I don't see a need of this.
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 518 at r2](https://reviewable.io/reviews/harness/harness-core/51988#-NcvkpD54CR0QhW4rafs:-Ncvz2zhEL771MmqDq14:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a9193472ea3d81e25397978384177005e379ecf9/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L518)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Duplicate criteria.
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 527 at r2](https://reviewable.io/reviews/harness/harness-core/51988#-NcvluCVBhh1Md7RUBT9:-Ncvz9a148cqMpqIqvMf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a9193472ea3d81e25397978384177005e379ecf9/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L527)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Place this at correct place. Looks like it will never get printed.
</blockquote></details>

Done.

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger uts

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51988)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
