### PR TITLE
feat: [PL-27627]: user email update via SCIM NG

### PR DESCRIPTION
**Pull request by ujjawal-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37287)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* Code issue 3 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37287)

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 300 at r2](https://reviewable.io/reviews/harness/harness-core/37287#-NBRCPR2EEk8oIPraVWa:-NBRCPR2EEk8oIPraVWb:bo7fbhg) ([raw file](https://github.com/harness/harness-core/blob/5e9806c1c427986b06dd5463f3a1d535ef107bd8/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L300)):*
> ```Java
>     if (patchOperation.getValue(ScimMultiValuedObject.class) != null
>         && patchOperation.getValue(ScimMultiValuedObject.class).getDisplayName() != null) {
>       // @Todo: Check with Ujjawal why CG has patchOperation.getValue(String.class)
> ```

minor please remove this Todo if there are no more pending changes needed



_Code quote:_
```Java
// @Todo: Check with Ujjawal why CG has patchOperation.getValue(String.class)
```

**Review by pbarapatre10 — APPROVED** [review]
:lgtm:
please test with Okta & Azure both

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37287#-:-NBRCl077NYS3XOyCwXu:b-kmy07a)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by kapil-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37287#-:-NBRNJLA0iEl5QxynXU7:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37287)* status: :shipit: complete! ✓

**Pull request merged**
