### PR TITLE
feat: [PIE-5484]: Adding hsqs project to harness core repository with bazel configs

### PR DESCRIPTION
**Pull request by ankittiwari-harness**
[PIE-5484]: Adding hsqs project to harness core repository with bazel configs

## Describe your changes
Added the new hsqs - Harness Internal Queuing Service in the mono repo. Bazel configurations for the same are added too. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[PIE-5484]: https://harness.atlassian.net/browse/PIE-5484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37861)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 21 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 19 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37861)

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 28 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37861)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`queue-service/hsqs/store/types.go` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/37861#-NCsaZO-CsRf4Zu7Hj40:-NCsaZO-CsRf4Zu7Hj41:b78joow) ([raw file](https://github.com/harness/harness-core/blob/a1f4bbf0e26a655fcfbed0c6c4369e9c50bd1c97/queue-service/hsqs/store/types.go#L25)):*
> ```Go
> 	Topic        string                 `json:"topic"`
> 	SubTopic     string                 `json:"subTopic"`
> 	Payload      map[string]interface{} `json:"payload"`
> ```

why map?
___
*[`queue-service/hsqs/store/redis/redis-store.go` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/37861#-NCsb3HF-jaK-jXj3wUK:-NCsb3HF-jaK-jXj3wUL:b2r8bpf) ([raw file](https://github.com/harness/harness-core/blob/a1f4bbf0e26a655fcfbed0c6c4369e9c50bd1c97/queue-service/hsqs/store/redis/redis-store.go#L78)):*
> ```Go
> // Output:
> // Returns 1 if successfully enqueued
> var enqueueCmd = redis.NewScript(`
> ```

why raw lua scripts? go-redis provides api for this. I do not have a pref but just curious
___
*[`queue-service/hsqs/store/redis/redisconf.go` line 6 at r1](https://reviewable.io/reviews/harness/harness-core/37861#-NCsbo9p7ZahTc5qLoLN:-NCsbo9p7ZahTc5qLoLO:bal0tk6) ([raw file](https://github.com/harness/harness-core/blob/a1f4bbf0e26a655fcfbed0c6c4369e9c50bd1c97/queue-service/hsqs/store/redis/redisconf.go#L6)):*
> ```Go
> // https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.
> 
> package redis
> ```

is this shared across harness?

**Review by ankittiwari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37861)* status: 12 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`queue-service/hsqs/store/types.go` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/37861#-NCsaZO-CsRf4Zu7Hj40:-NCtYyiW5fdvJzgICbyq:b-7fif3q) ([raw file](https://github.com/harness/harness-core/blob/a1f4bbf0e26a655fcfbed0c6c4369e9c50bd1c97/queue-service/hsqs/store/types.go#L25)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

why map?
</blockquote></details>

Switched to []byte as discussed
___
*[`queue-service/hsqs/store/redis/redis-store.go` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/37861#-NCsb3HF-jaK-jXj3wUK:-NCtZ7Mn4G1HtUOfj-g5:b-8pmql9) ([raw file](https://github.com/harness/harness-core/blob/a1f4bbf0e26a655fcfbed0c6c4369e9c50bd1c97/queue-service/hsqs/store/redis/redis-store.go#L78)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

why raw lua scripts? go-redis provides api for this. I do not have a pref but just curious
</blockquote></details>

Will remove lua scripts with dequeue operations
___
*[`queue-service/hsqs/store/redis/redisconf.go` line 6 at r1](https://reviewable.io/reviews/harness/harness-core/37861#-NCsbo9p7ZahTc5qLoLN:-NCtZHBW6mls-wpeBrtv:b3g27nx) ([raw file](https://github.com/harness/harness-core/blob/a1f4bbf0e26a655fcfbed0c6c4369e9c50bd1c97/queue-service/hsqs/store/redis/redisconf.go#L6)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

is this shared across harness?
</blockquote></details>

Removed in rev

**Review by hextechpal — COMMENTED** [review]
> Reviewed 4 of 32 files at r1, 7 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37861)* status: 32 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37861)* status: 32 file(s) to review. 1 of 2 approvals obtained.

**Comment by ankittiwari-harness** [comment]
trigger messagecheck, trigger authorcheck, trigger ti2

**Review by naidu-harness — DISMISSED** [review]
:lgtm:

> Reviewed 24 of 32 files at r1, 7 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37861#-:-NCxPTMsCV96qJCUG6BB:bnfp4nl)* status: 1 file(s) to review.

**Comment by ankittiwari-harness** [comment]
trigger authorcheck

**Comment by ankittiwari-harness** [comment]
trigger authorcheck

**Comment by ankittiwari-harness** [comment]
trigger authorcheck

**Comment by ankittiwari-harness** [comment]
trigger featurenamecheck

**Review by hextechpal — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37861)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37861#-:-NCxxalC9AbWWD7wdCGj:bnfp4nl)* status: :shipit: complete! ✓

**Comment by naidu-harness** [comment]
trigger featurenamecheck

**Comment by ankittiwari-harness** [comment]
trigger featurenamecheck

**Comment by ankittiwari-harness** [comment]
trigger featurenamecheck

**Comment by ankittiwari-harness** [comment]
trigger featurenamecheck

**Pull request merged**
