### PR TITLE
[fix]: [PL-39780]: Improves log by adding entity identifier and scope

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51313)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51313)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/repositories/RoleAssignmentCustomRepositoryImpl.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/51313#-NauRdn9Aw0969maW4qP:-NauRdn9Aw0969maW4qQ:b-yq5zv) ([raw file](https://github.com/harness/harness-core/blob/c873d994242988f06075cceb95c5979c542e2e6a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/repositories/RoleAssignmentCustomRepositoryImpl.java#L64)):*
> ```Java
>   public long deleteMulti(Criteria criteria) {
>     Query query = new Query(criteria);
>     log.info("The current query for deleting multiple role assignment is: {}", query.toString());
> ```

Can we delete this log line?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/repositories/RoleAssignmentCustomRepositoryImpl.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/51313#-NauRp2PAlknP3CCGpdv:-NauRp2PAlknP3CCGpdw:bgequ1m) ([raw file](https://github.com/harness/harness-core/blob/c873d994242988f06075cceb95c5979c542e2e6a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/repositories/RoleAssignmentCustomRepositoryImpl.java#L65)):*
> ```Java
>     Query query = new Query(criteria);
>     log.info("The current query for deleting multiple role assignment is: {}", query.toString());
>     List<RoleAssignmentDBO> roleAssignmentDBOS = mongoTemplate.findAllAndRemove(query, RoleAssignmentDBO.class);
> ```

We should not do this. This will fetch all role assignments in memory. Let's not change anything here. We can capture deletion via RoleAssignmentChangeConsumer

**Comment by ashishsanodia-harness** [comment]
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/repositories/RoleAssignmentCustomRepositoryImpl.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/51313#-NauRdn9Aw0969maW4qP:-NauSc0bEA7sBluhXa9j:b-i3aum2) ([raw file](https://github.com/harness/harness-core/blob/c873d994242988f06075cceb95c5979c542e2e6a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/repositories/RoleAssignmentCustomRepositoryImpl.java#L64)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we delete this log line?
</blockquote></details>

this is the only place where we are logging role assignment identifiers in case of multi delete

**Comment by ashishsanodia-harness** [comment]
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/repositories/RoleAssignmentCustomRepositoryImpl.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/51313#-NauRp2PAlknP3CCGpdv:-NauT1MJ7zxpM9IMfbgx:bvfbn3y) ([raw file](https://github.com/harness/harness-core/blob/c873d994242988f06075cceb95c5979c542e2e6a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/repositories/RoleAssignmentCustomRepositoryImpl.java#L65)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We should not do this. This will fetch all role assignments in memory. Let's not change anything here. We can capture deletion via RoleAssignmentChangeConsumer
</blockquote></details>

In RoleAssignmentChangeConsumer for roleassignment delete event we just have mongo id not the identifier. This is the only place we can get both id and identifier in case of multi delete.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51313)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/repositories/RoleAssignmentCustomRepositoryImpl.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/51313#-NauRp2PAlknP3CCGpdv:-NauYn4f9JzRadFaMwXM:bj3zqpp) ([raw file](https://github.com/harness/harness-core/blob/c873d994242988f06075cceb95c5979c542e2e6a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/repositories/RoleAssignmentCustomRepositoryImpl.java#L65)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

In RoleAssignmentChangeConsumer for roleassignment delete event we just have mongo id not the identifier. This is the only place we can get both id and identifier in case of multi delete.
</blockquote></details>

But we can not do it. It will have impact on performance.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51313)* status: 6 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Pull request merged**
