### PR TITLE
[fix]: [PL-30879]: adding logs for flow where a User can be made disabled

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
Some 'Users' are getting 'disabled' and that is leading to those users not able to login to Harness. We were not able to determine which exact flow causes the User disabling. In this PR we are adding logs at places where 'User' is getting marked disabled. It would help to find the flow in the code where User is disabled.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42664)

### CODE REVIEW

**Review by tiwaritejas — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42664)* status: 3 file(s) to review. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 387 at r1](https://reviewable.io/reviews/harness/harness-core/42664#-NLuRKfK2GHSnxF2j-q3:-NLuRKfK2GHSnxF2j-q4:b6rg7jt) ([raw file](https://github.com/harness/harness-core/blob/495a88310abd0174730e19c5b5fa8c49c046e828/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L387)):*
> ```Java
>     UpdateOperations<User> updateOperation = wingsPersistence.createUpdateOperations(User.class);
>     updateOperation.set(UserKeys.disabled, disabled);
>     log.info("SCIM: Updating active state for user: {}, to: {}", userId, disabled);
> ```

Should this be consistent with other logs? We should log disabled instead of active, else it might create confusion while checking the logs.

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 387 at r1](https://reviewable.io/reviews/harness/harness-core/42664#-NLuRKfK2GHSnxF2j-q3:-NLy3pYZ3afx4p4H2Ndp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/495a88310abd0174730e19c5b5fa8c49c046e828/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L387)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

Should this be consistent with other logs? We should log disabled instead of active, else it might create confusion while checking the logs.
</blockquote></details>

Done.

**Review by tiwaritejas — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42664)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42664)* status: :shipit: complete! ✓

**Review by shashank-harness — COMMENTED** [review]
Please add logs in other paths too.
Including AccountServiceImpl.java:
public boolean disableAccount(String accountId, String migratedTo

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42664#-:-NLzV_-F8XYDpuD1V6SY:boesc3d)* status: :shipit: complete! ✓

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42664)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42664)* status: :shipit: complete! ✓

**Comment by pbarapatre10** [comment]
trigger ft1

**Comment by pbarapatre10** [comment]
trigger ft

**Comment by pbarapatre10** [comment]
trigger ft2

**Pull request merged**
