### PR TITLE
feat: [CDS-36022]: Added FileResource for RBAC  and FileEventHandler

### PR DESCRIPTION
**Pull request by ivan-83**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32373)

### CODE REVIEW

**Review by vladimir-peric — COMMENTED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32373)* status: 46 file(s) to review. 0 of 1 approvals obtained.

**Review by vladimir-peric — DISMISSED** [review]
> Reviewed 46 of 46 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32373)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 16 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32373)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/file/FileResourceImpl.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/32373#-N0kmd--CH0MAzLag6AU:-N0kmd--CH0MAzLag6AV:bjhq4xt) ([raw file](https://github.com/harness/harness-core/blob/97c47b886a16d4bfde4ca16aa09a67212717414f/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/file/FileResourceImpl.java#L68)):*
> ```Java
>         NGRestUtils
>             .getResponse(fileStoreClient.listFiles(scope.getAccountIdentifier(), scope.getOrgIdentifier(),
>                 scope.getProjectIdentifier(), resourceIds, 0, resourceIds.size()))
> ```

does this mean that we only fetch 1 page of items ? what happens if there are multiple pages ?

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32373)* status: 17 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/events/filestore/FileDeleteEvent.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/32373#-N0kdaEEETQWhh3c6z8P:-N0pwdm95lCcG1CMpJPF:b30jj0k) ([raw file](https://github.com/harness/harness-core/blob/97c47b886a16d4bfde4ca16aa09a67212717414f/120-ng-manager/src/main/java/io/harness/ng/core/events/filestore/FileDeleteEvent.java#L48)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

i can see `getResourrceScope()` and `getResource()` are dupplicated accross FileEvents, shall we move to upper class and extend it?
</blockquote></details>

Agree. It requires a little more work, we already implement framework interface Event we need to move file and accountId properties to abstract class.  
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/FileEventHandler.java` line 87 at r1](https://reviewable.io/reviews/harness/harness-core/32373#-N0ke1_N5AWG4GgWAnqX:-N0pvBde42FqjqqTZfRL:b9jo9tk) ([raw file](https://github.com/harness/harness-core/blob/97c47b886a16d4bfde4ca16aa09a67212717414f/120-ng-manager/src/main/java/io/harness/ng/core/outbox/FileEventHandler.java#L87)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

hiding the exception is a bad practice, it will increase the time for debugging an issue.
</blockquote></details>

Agree. Just logging exception if we throw exception it will affect publishing events on framework level. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/FileEventHandler.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/32373#-N0kenK8CEcourFzm_3o:-N0pv_HY2GhoVUCQ4bVM:b-idl1pe) ([raw file](https://github.com/harness/harness-core/blob/97c47b886a16d4bfde4ca16aa09a67212717414f/120-ng-manager/src/main/java/io/harness/ng/core/outbox/FileEventHandler.java#L119)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

how the FileDto yaml will look like? i the content is changed, i don't think it is going to be reflected in that diff, correct?
</blockquote></details>

Usually the file metadata are different. We are not keeping the file content as part of yaml. This is example for newFile
file:
    identifier: fileIndentifier
    name: filename
    fileUsage: MANIFEST_FILE
    type: FILE
    parentIdentifier: parentIdentifier
    description: Update description
    tags:
        - key: key1
          value: value1
        - key: key2
          value: value2
    mimeType: yaml
    createdBy: admin@harness.io


and for oldFile, here description is different and there is no tags
file:
    identifier: fileIndentifier
    name: filename
    fileUsage: MANIFEST_FILE
    type: FILE
    parentIdentifier: parentIdentifier
    description: Description
    mimeType: yaml
    createdBy: admin@harness.io
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/file/FileResourceImpl.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/32373#-N0kmd--CH0MAzLag6AU:-N0pw9TnC7BquV7cwJkd:bknvj5v) ([raw file](https://github.com/harness/harness-core/blob/97c47b886a16d4bfde4ca16aa09a67212717414f/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/file/FileResourceImpl.java#L68)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

does this mean that we only fetch 1 page of items ? what happens if there are multiple pages ?
</blockquote></details>

Done. We are requesting 20 identifiers per requests/pages in order to not reach maximum URL length (2,083 characters).

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 43 of 46 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32373)* status: Some of the checks are too old. 18 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 11 of 13 files at r3, 17 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32373)* status: Some of the checks are too old. 3. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32373)* status: Some of the checks are too old. 3. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 46 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32373)* status: Some of the checks are too old. 3. unresolved discussions.

**Review by reetika04 — APPROVED** [review]
> Reviewed 7 of 22 files at r1, 25 of 46 files at r2, 11 of 13 files at r3, 17 of 17 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32373)* status: 3. unresolved discussions.

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 17 of 17 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32373)* status: 3. unresolved discussions.

**Review by vladimir-peric — DISMISSED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32373)* status: 3. unresolved discussions.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 24 of 46 files at r2, 10 of 13 files at r3, 16 of 17 files at r4, 3 of 5 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32373)* status: :shipit: complete! ✓

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 1 of 2 files at r7, 1 of 2 files at r8, 2 of 5 files at r9, 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32373)* status: :shipit: complete! ✓

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r8, 2 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32373)* status: :shipit: complete! ✓

**Review by reetika04 — APPROVED** [review]
> Reviewed 1 of 2 files at r7, 1 of 2 files at r8, 2 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32373)* status: :shipit: complete! ✓

**Pull request merged**
