### PR TITLE
feat: [CDS-40867]: create pr file

### PR DESCRIPTION
**Pull request by GabeAboy**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36549)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36549)

**Comment by rohitk-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 211 at r3](https://reviewable.io/reviews/harness/harness-core/36549#-NAB9F4l4y0fUjLXDxwi:-NAB9F4l4y0fUjLXDxwj:b-ajq2y9) ([raw file](https://github.com/harness/harness-core/blob/19eb47c0f1c46c1184f97c26c1c269e5440648e7/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L211)):*
> ```Java
>       updateFiles(gitOpsTaskParams.getFilesToVariablesMap(), fetchFilesResult);
>       return fetchFilesResult;
>     } catch (Exception e) {
> ```

Can we specifically catch only the exception where files are not found and extract from the message the status code so that can be used here? 
Enhancing the exception itself to have the status code would be ok in my opinion

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36549)* status: 0 of 1 approvals obtained.

**Comment by rohitk-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 211 at r4](https://reviewable.io/reviews/harness/harness-core/36549#-NABRVlj851xt6lOzCTB:-NABRVlj851xt6lOzCTC:b24om3m) ([raw file](https://github.com/harness/harness-core/blob/e0d6c7d836188eb201cdc81722eaf637069dba95/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L211)):*
> ```Java
>       return fetchFilesResult;
>     } catch (Exception e) {
>       if(e.getCause().getMessage().contains("404")){
> ```

I still think we should only catch the specific exception here which is `NoSuchFileException` 



_Code quote (from 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/ScmFetchFilesHelperNG.java):_
```Java
        USER, new NoSuchFileException(fileContent.getPath(), null, String.valueOf(fileContent.getStatus())));
  }
```

**Review by GabeAboy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36549)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 211 at r3](https://reviewable.io/reviews/harness/harness-core/36549#-NAB9F4l4y0fUjLXDxwi:-NAB9zSF7DyQ0VD71bYF:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/19eb47c0f1c46c1184f97c26c1c269e5440648e7/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L211)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Can we specifically catch only the exception where files are not found and extract from the message the status code so that can be used here? 
Enhancing the exception itself to have the status code would be ok in my opinion
</blockquote></details>

done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 211 at r4](https://reviewable.io/reviews/harness/harness-core/36549#-NABRVlj851xt6lOzCTB:-NABcijP3ffnHAPCTa5U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e0d6c7d836188eb201cdc81722eaf637069dba95/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L211)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

I still think we should only catch the specific exception here which is `NoSuchFileException` 
</blockquote></details>

Done.

**Comment by rohitk-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 216 at r5](https://reviewable.io/reviews/harness/harness-core/36549#-NABoL6NEaYOuuzv3DsV:-NABoL6NEaYOuuzv3DsW:b-qp3nz3) ([raw file](https://github.com/harness/harness-core/blob/9381a6ca3e788792f8bcccdf1bbd17d97fc4ce4e/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L216)):*
> ```Java
>       if (e instanceof NoSuchFileException) {
>         this.logCallback.saveExecutionLog(
>             color(format("%nFetch Files task was not successful."), LogColor.White, LogWeight.Bold), ERROR);
> ```

We should update this message to say, files were not found. These executions logs are visible to the user.

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36549)* status: 0 of 1 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36549)* status: :shipit: complete! ✓

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36549)* status: :shipit: complete! ✓

**Pull request merged**
