### PR TITLE
feat: [PL-29332]: Index Optimisation in Build Cleaner

### PR DESCRIPTION
**Pull request by reetika04**
## Describe your changes
 Index Optimisation in Build Cleaner to only update the indexes of the file from the last updated time.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39262)

### CODE REVIEW

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39262)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/39262#-NFN-xEE2oxkG1xYCb43:-NFN-xEE2oxkG1xYCb44:b-o4l5c1) ([raw file](https://github.com/harness/harness-core/blob/4311729a5ca06a3bcfa98c55505f098cf393ff12/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L50)):*
> ```Java
> import org.slf4j.LoggerFactory;
> 
> public class BuildCleaner {
> ```

Thanks for the quick turnaround. Changes look good mostly, with minor comments.

Please add a PR description and some details on how it is tested.
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 129 at r1](https://reviewable.io/reviews/harness/harness-core/39262#-NFMvV_i6RJISqiN43Qq:-NFMvV_i6RJISqiN43Qr:b1ivfgt) ([raw file](https://github.com/harness/harness-core/blob/4311729a5ca06a3bcfa98c55505f098cf393ff12/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L129)):*
> ```Java
>    * Returns last modified date of the directory
>    */
>   @VisibleForTesting
> ```

nit: This tag is added when you want to tell why a function is not private and only exposed for testing. If you have not added unit tests, no need to add this and mark functions private.
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 144 at r1](https://reviewable.io/reviews/harness/harness-core/39262#-NFMvxQN5pt4pepXVcEW:-NFMvxQN5pt4pepXVcEX:b-1jtq6v) ([raw file](https://github.com/harness/harness-core/blob/4311729a5ca06a3bcfa98c55505f098cf393ff12/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L144)):*
> ```Java
>    */
>   @VisibleForTesting
>   public void updateLastRunTime() throws FileNotFoundException {
> ```

nit: private
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 145 at r1](https://reviewable.io/reviews/harness/harness-core/39262#-NFMwHSD7pUzgFMZZIYU:-NFMwHSD7pUzgFMZZIYV:b-i6g35) ([raw file](https://github.com/harness/harness-core/blob/4311729a5ca06a3bcfa98c55505f098cf393ff12/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L145)):*
> ```Java
>   @VisibleForTesting
>   public void updateLastRunTime() throws FileNotFoundException {
>     try (FileOutputStream fos = new FileOutputStream(workspace().resolve(BUILD_CLEANER_LAST_UPDATED).toString());
> ```

Instead of a new file, we can just use the file modified time / File.lastModified
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 174 at r1](https://reviewable.io/reviews/harness/harness-core/39262#-NFN-0uz3kCaHExKTBLd:-NFN-0uz3kCaHExKTBLe:bkas9br) ([raw file](https://github.com/harness/harness-core/blob/4311729a5ca06a3bcfa98c55505f098cf393ff12/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L174)):*
> ```Java
>   @VisibleForTesting
>   protected SymbolDependencyMap updateSymbolDependencies(SymbolDependencyMap harnessSymbolMap) throws IOException {
>     Date lastModified = Date.from(Instant.ofEpochSecond(getLastRunTime()));
> ```

nit: All the conversions to date are not necessary. If you have epochs, you can compare those directly.
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 175 at r1](https://reviewable.io/reviews/harness/harness-core/39262#-NFN-ecG5EGE1W6QrczZ:-NFN-ecG5EGE1W6Qrcz_:bku5jwr) ([raw file](https://github.com/harness/harness-core/blob/4311729a5ca06a3bcfa98c55505f098cf393ff12/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L175)):*
> ```Java
>   protected SymbolDependencyMap updateSymbolDependencies(SymbolDependencyMap harnessSymbolMap) throws IOException {
>     Date lastModified = Date.from(Instant.ofEpochSecond(getLastRunTime()));
>     Files.find(workspace(), Integer.MAX_VALUE, (filePath, fileAttr) -> fileAttr.isDirectory()).forEach(path -> {
> ```

this returns the top level folders or all folders?
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 177 at r1](https://reviewable.io/reviews/harness/harness-core/39262#-NFN-KJA52ie_Nxbv4PS:-NFN-KJA52ie_Nxbv4PT:b44q9pj) ([raw file](https://github.com/harness/harness-core/blob/4311729a5ca06a3bcfa98c55505f098cf393ff12/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L177)):*
> ```Java
>     Files.find(workspace(), Integer.MAX_VALUE, (filePath, fileAttr) -> fileAttr.isDirectory()).forEach(path -> {
>       File directory = new File(path.toString());
>       if (getLastModified(directory).after(lastModified)) {
> ```

nit: good practice to reduce nesting by returning early.

if (directoryLastModified < lastIndexTime) {
  return;
}

....

**Review by gn-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39262)* status: Some of the checks are too old. 3 file(s) to review. 1 of 2 approvals obtained.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39262)* status: Some of the checks are too old. 3 file(s) to review. 1 of 2 approvals obtained.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39262)* status: Some of the checks are too old. 3 file(s) to review. 1 of 2 approvals obtained.

**Review by Raghav-Murali — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39262)* status: Some of the checks are too old.

**Review by Raghav-Murali — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39262)* status: 1 of 2 approvals obtained.

**Pull request closed without merging**
