### PR TITLE
feat: [PL-22055]: integrate list API

### PR DESCRIPTION
**Pull request by bhavya181**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30092)

### CODE REVIEW

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java, line 224 at r2](https://reviewable.io/reviews/harness/harness-core/30092#-MuCcych0eCSxDIlgoYv:-MuCcych0eCSxDIlgoYw:b-vpw9ad) ([raw file](https://github.com/harness/harness-core/blob/c3d6796c5435548d853fd362f7d584fc713c19ce/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java#L224)):*
> ```Java
>       @RequestBody(description = "Details of Page including: size, index, sort") @BeanParam PageRequest pageRequest,
>       @Parameter(description = ACCOUNT_PARAM_MESSAGE) @NotBlank @QueryParam(
>           NGCommonEntityConstants.ACCOUNT_KEY) @io.harness.accesscontrol.AccountIdentifier String accountIdentifier,
> ```

AccountIdentifier should be marked as required=true.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30092)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java, line 89 at r2](https://reviewable.io/reviews/harness/harness-core/30092#-MuEzoWE6gz39ePT1iHw:-MuEzoWE6gz39ePT1iHx:bmtk8k8) ([raw file](https://github.com/harness/harness-core/blob/c3d6796c5435548d853fd362f7d584fc713c19ce/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java#L89)):*
> ```Java
>       createNewBranch(fullSyncEventRequest, yamlGitConfigDTO.getRepo());
>     } else {
>       gitBranchService.updateBranchSyncStatus(gitConfigScope.getAccountId(), yamlGitConfigDTO.getRepo(),
> ```

The branch won't be actually SYNCED here as it may have prev harness entities in git which won't be available at Harness, so need to check on it.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java, line 142 at r2](https://reviewable.io/reviews/harness/harness-core/30092#-MuF-JZ6315y_zJSpQ6i:-MuF-JZ6315y_zJSpQ6j:b-fjlom9) ([raw file](https://github.com/harness/harness-core/blob/c3d6796c5435548d853fd362f7d584fc713c19ce/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java#L142)):*
> ```Java
>             .retryCount(0)
>             .build();
>     gitFullSyncEntityService.updateStatus(entityScopeInfo.getAccountId(), orgIdentifier, projectIdentifier,
> ```

add comments or move it to a logical method separately.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30092)* status: 13 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java, line 224 at r2](https://reviewable.io/reviews/harness/harness-core/30092#-MuCcych0eCSxDIlgoYv:-MuFWMd176C6lHp2HSqa:byyo3sx) ([raw file](https://github.com/harness/harness-core/blob/c3d6796c5435548d853fd362f7d584fc713c19ce/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java#L224)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

AccountIdentifier should be marked as required=true.
</blockquote></details>

NotBalnk annotation is already aapplied.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java, line 89 at r2](https://reviewable.io/reviews/harness/harness-core/30092#-MuEzoWE6gz39ePT1iHw:-MuFWTdR4xNpXGa__PN7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c3d6796c5435548d853fd362f7d584fc713c19ce/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java#L89)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The branch won't be actually SYNCED here as it may have prev harness entities in git which won't be available at Harness, so need to check on it.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java, line 142 at r2](https://reviewable.io/reviews/harness/harness-core/30092#-MuF-JZ6315y_zJSpQ6i:-MuFWUR2CqyfvX8aSBVG:b-xtcypv) ([raw file](https://github.com/harness/harness-core/blob/c3d6796c5435548d853fd362f7d584fc713c19ce/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java#L142)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

add comments or move it to a logical method separately.
</blockquote></details>

moved to another method.

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 13 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30092#-:-MuGmxw41Nuh3QkM5g9g:bnfp4nl)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 8 of 13 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30092)* status: 1 file(s) to review.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30092)* status: 1 file(s) to review.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30092#-:-MuQ5aeHBK3W3s4DkwB9:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
