### PR TITLE
fix: [CDS-47824]: Download Artifact is not working for WinRM deployme…

### PR DESCRIPTION
**Pull request by bojanmicovic**
…nts on PRE_QA

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41122)

### CODE REVIEW

**Comment by bojanmicovic** [comment]
trigger smartchecks

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41122#-:-NIYQmHB4w5WaEtuFbWR:bnfp4nl)* status: 9 file(s) to review. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/AwsS3ArtifactDownloadHandler.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/41122#-NIYRJWN2Lyw6skJLlKg:-NIYRJWN2Lyw6skJLlKh:b-evh38u) ([raw file](https://github.com/harness/harness-core/blob/7c4e09382baefba26845cc39c8929d84c363b5d3/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/AwsS3ArtifactDownloadHandler.java#L75)):*
> ```Java
>   public String getPowerShellCommand(AwsS3ArtifactDelegateConfig s3ArtifactDelegateConfig, String destinationPath) {
>     AwsConnectionDetails connectionDetails = mapAwsConnectionDetails(s3ArtifactDelegateConfig, destinationPath);
>     return "$DESTINATION_PATH=[System.Environment]::ExpandEnvironmentVariables(\"" + connectionDetails.targetPath
> ```

Quick questions - Why do we need [System.Environment] env variable and ExpandEnvironmentVariables?  The customer inserted destination path will be preserved, right?

**Comment by vladimir-peric** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java` line 126 at r2](https://reviewable.io/reviews/harness/harness-core/41122#-NIamtZ5E7FCAb11Lfi6:-NIamtZ7CUp-rs5of4h0:byxtr7o) ([raw file](https://github.com/harness/harness-core/blob/07da1e7b147318d28289fbe4f3c09da1d7d868cb/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java#L126)):*
> ```Java
>   @Override
>   public CommandExecutionStatus executeCommandString(
>       String command, boolean winrmScriptCommandSplit, StringBuffer output, boolean displayCommand) {
> ```

Correct me if wrong, but looks like this output parameter is not used at all?

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java` line 126 at r2](https://reviewable.io/reviews/harness/harness-core/41122#-NIamtZ5E7FCAb11Lfi6:-NIapNO49YuCQudv-AVU:b-p2cv8l) ([raw file](https://github.com/harness/harness-core/blob/07da1e7b147318d28289fbe4f3c09da1d7d868cb/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java#L126)):*
<details><summary><i>Previously, vladimir-peric (Vladimir Peric) wrote…</i></summary><blockquote>

Correct me if wrong, but looks like this output parameter is not used at all?
</blockquote></details>

In this method it is not used, but there are two other implementations which uses this.

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/AwsS3ArtifactDownloadHandler.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/41122#-NIYRJWN2Lyw6skJLlKg:-NIapVjaDIFIvObcEfQH:bdhjun6) ([raw file](https://github.com/harness/harness-core/blob/7c4e09382baefba26845cc39c8929d84c363b5d3/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/AwsS3ArtifactDownloadHandler.java#L75)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Quick questions - Why do we need [System.Environment] env variable and ExpandEnvironmentVariables?  The customer inserted destination path will be preserved, right? 
</blockquote></details>

This was removed.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 11 of 15 files at r2, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41122)* status: 15 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/shell/AbstractScriptExecutor.java` line 98 at r4](https://reviewable.io/reviews/harness/harness-core/41122#-NIbQq_j2IMgATEe_HNA:-NIbQq_j2IMgATEe_HNB:b-j23twa) ([raw file](https://github.com/harness/harness-core/blob/6d45d674d46568d65794aa8c394c4fda2fe1df82/960-api-services/src/main/java/io/harness/shell/AbstractScriptExecutor.java#L98)):*
> ```Java
> 
>   @Override
>   public CommandExecutionStatus executeCommandString(
> ```

Everything looks good to me except this part where we are having param which is not used. 
___
*[`960-api-services/src/main/java/io/harness/shell/AbstractScriptExecutor.java` line 104 at r4](https://reviewable.io/reviews/harness/harness-core/41122#-NIbRCwU7g84rJzCay_H:-NIbRCwU7g84rJzCay_I:b-fa02a1) ([raw file](https://github.com/harness/harness-core/blob/6d45d674d46568d65794aa8c394c4fda2fe1df82/960-api-services/src/main/java/io/harness/shell/AbstractScriptExecutor.java#L104)):*
> ```Java
> 
>   @Override
>   public CommandExecutionStatus executeCommandString(
> ```

The same comment here.

**Pull request closed without merging**
