### PR TITLE
feat:[SSCA-612]: Added Filters on artifact listing

### PR DESCRIPTION
**Pull request by arpit-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54258)

### CODE REVIEW

**Review by mankrit-singh — APPROVED** [review]

**Comment by arpit-harness** [comment]
trigger uts

**Comment by arpit-harness** [comment]
trigger uts

**Comment by arpit-harness** [comment]
trigger ut1

**Comment by arpit-harness** [comment]
trigger ut4

**Comment by arpit-harness** [comment]
trigger ut9

**Review by deepharness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54258)* status: 11 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/repositories/EnforcementSummaryRepoCustom.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/54258#-Nh0W-S-1MYcOuI5M5sa:-Nh0W-S-1MYcOuI5M5sb:bxf2shz) ([raw file](https://github.com/harness/harness-core/blob/72c39c68fe25da86ec2fa7abb0836acb2c089cfb/ssca-manager/service/src/main/java/io/harness/repositories/EnforcementSummaryRepoCustom.java#L22)):*
> ```Java
> public interface EnforcementSummaryRepoCustom {
>   List<EnforcementSummaryEntity> findAll(Aggregation aggregation);
>   List<EnforcementSummaryEntity> findAll(Criteria criteria);
> ```

add accountId , all our repo should enforce that
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 228 at r2](https://reviewable.io/reviews/harness/harness-core/54258#-Nh1aAjR0aTUdlUGFhV0:-Nh1aAjR0aTUdlUGFhV1:b-k8dkmi) ([raw file](https://github.com/harness/harness-core/blob/7e393bbf60eaeaf246d54582d57750ceda305074/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L228)):*
> ```Java
>     criteria.andOperator(getDeploymentFilterCriteria(accountId, orgIdentifier, projectIdentifier, body));
> 
>     Page<ArtifactEntity> artifactEntities = artifactRepository.findAll(criteria, pageable);
> ```

findAll should take accountId , currently accountId is bloating in each criteria 
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 349 at r2](https://reviewable.io/reviews/harness/harness-core/54258#-Nh1avH-5cctTEVPfPWv:-Nh1avH-5cctTEVPfPWw:b7uyoj3) ([raw file](https://github.com/harness/harness-core/blob/7e393bbf60eaeaf246d54582d57750ceda305074/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L349)):*
> ```Java
> 
>   private Criteria getPolicyFilterCriteria(
>       String accountId, String orgIdentifier, String projectIdentifier, ArtifactListingRequestBody body) {
> ```

accountId is unused  
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 351 at r2](https://reviewable.io/reviews/harness/harness-core/54258#-Nh1_13z9f2Np4jzKC2t:-Nh1_13z9f2Np4jzKC2u:buxypyc) ([raw file](https://github.com/harness/harness-core/blob/7e393bbf60eaeaf246d54582d57750ceda305074/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L351)):*
> ```Java
>       String accountId, String orgIdentifier, String projectIdentifier, ArtifactListingRequestBody body) {
>     Criteria criteria = new Criteria();
>     if (Objects.nonNull(body) && Objects.nonNull(body.getPolicyViolation())) {
> ```

inverse the condition , it will make code more readable
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 373 at r2](https://reviewable.io/reviews/harness/harness-core/54258#-Nh1b-yA5Kx0z-bnAOh9:-Nh1b-yA5Kx0z-bnAOhA:b-ji6h01) ([raw file](https://github.com/harness/harness-core/blob/7e393bbf60eaeaf246d54582d57750ceda305074/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L373)):*
> ```Java
> 
>   private Criteria getDeploymentFilterCriteria(
>       String accountId, String orgIdentifier, String projectIdentifier, ArtifactListingRequestBody body) {
> ```

accountId is unused

**Review by arpit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54258)* status: 11 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/contracts/openapi/v1/openapi.yaml` line 329 at r3](https://reviewable.io/reviews/harness/harness-core/54258#gh-1363801083:-Nh3oQ-X5y0zpUdqwv2K:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/5a0353ff322aeb97efdf5a227cb94dfa39235d9e/ssca-manager/contracts/openapi/v1/openapi.yaml#L329)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

instead of componenCount, use updatedat
</blockquote></details>

Done
___
*[`ssca-manager/service/src/main/java/io/harness/repositories/EnforcementSummaryRepoCustom.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/54258#-Nh0W-S-1MYcOuI5M5sa:-Nh3oTSt9IjURcR7uDzc:b5sycjy) ([raw file](https://github.com/harness/harness-core/blob/72c39c68fe25da86ec2fa7abb0836acb2c089cfb/ssca-manager/service/src/main/java/io/harness/repositories/EnforcementSummaryRepoCustom.java#L22)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

add accountId , all our repo should enforce that
</blockquote></details>

EnforcementResultSummary doesn't have accountId.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 228 at r2](https://reviewable.io/reviews/harness/harness-core/54258#-Nh1aAjR0aTUdlUGFhV0:-Nh3oc8y6ts0B8zGj0S6:b5sycjy) ([raw file](https://github.com/harness/harness-core/blob/7e393bbf60eaeaf246d54582d57750ceda305074/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L228)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

findAll should take accountId , currently accountId is bloating in each criteria
</blockquote></details>

EnforcementResultSummary doesn't have accountId.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 349 at r2](https://reviewable.io/reviews/harness/harness-core/54258#-Nh1avH-5cctTEVPfPWv:-Nh3ofRY5ms8cqcEBhiS:b-rpgnzr) ([raw file](https://github.com/harness/harness-core/blob/7e393bbf60eaeaf246d54582d57750ceda305074/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L349)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

accountId is unused
</blockquote></details>

EnforcementResultSummary doesn't have accountId. Added in signature for future, also created a ticket for it.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 351 at r2](https://reviewable.io/reviews/harness/harness-core/54258#-Nh1_13z9f2Np4jzKC2t:-Nh3omlXDwrCnLOimcJb:bqvlnr8) ([raw file](https://github.com/harness/harness-core/blob/7e393bbf60eaeaf246d54582d57750ceda305074/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L351)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

inverse the condition , it will make code more readable
</blockquote></details>

Inverse how?
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 373 at r2](https://reviewable.io/reviews/harness/harness-core/54258#-Nh1b-yA5Kx0z-bnAOh9:-Nh3oy0VB0e63G9j3AMJ:b5sycjy) ([raw file](https://github.com/harness/harness-core/blob/7e393bbf60eaeaf246d54582d57750ceda305074/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L373)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

accountId is unused
</blockquote></details>

EnforcementResultSummary doesn't have accountId.

**Comment by arpit-harness** [comment]
trigger uts

**Comment by arpit-harness** [comment]
trigger uts

**Review by deepharness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54258)* status: 11 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 373 at r2](https://reviewable.io/reviews/harness/harness-core/54258#-Nh1b-yA5Kx0z-bnAOh9:-Nh5_NTI9tR7bsqLJ0V8:b-58szd9) ([raw file](https://github.com/harness/harness-core/blob/7e393bbf60eaeaf246d54582d57750ceda305074/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L373)):*
<details><summary><i>Previously, arpit-harness wrote…</i></summary><blockquote>

EnforcementResultSummary doesn't have accountId.
</blockquote></details>

can you remove that 
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 226 at r5](https://reviewable.io/reviews/harness/harness-core/54258#-Nh5_X94E3K9848hFhEo:-Nh5_X94E3K9848hFhEp:b-3e2pt3) ([raw file](https://github.com/harness/harness-core/blob/e8ade78c0bc6ff4469e2efc52ce585ef44714b92/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L226)):*
> ```Java
> 
>     criteria.andOperator(getPolicyFilterCriteria(accountId, orgIdentifier, projectIdentifier, body),
>         getDeploymentFilterCriteria(accountId, orgIdentifier, projectIdentifier, body));
> ```

you can remove the account Id from getDeploymentFilterCriteria as its a part of criteria

**Comment by arpit-harness** [comment]
trigger uts

**Review by mankrit-singh — APPROVED** [review]

**Review by deepharness — APPROVED** [review]
> Reviewed 6 of 12 files at r1, 2 of 3 files at r2, 2 of 3 files at r4, 6 of 7 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54258)* status: 3. unresolved discussions.

**Pull request merged**
