### PR TITLE
fix: [CVS-8998]: Not able to remove the Log indexes from the Health s…

### PR DESCRIPTION
**Pull request by slobodanpavic**
…ource of DD logs in edit flow

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30333)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30333)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/DatadogLogCVConfig.java, line 77 at r1](https://reviewable.io/reviews/harness/harness-core/30333#-MuajNJ_-3mGCyKio8MW:-MuajNJ_-3mGCyKio8MX:bq8gizl) ([raw file](https://github.com/harness/harness-core/blob/7a26ce48dd777a0f78b7dd90f7049d055cd7bd3e/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/DatadogLogCVConfig.java#L77)):*
> ```Java
>         UpdateOperations<DatadogLogCVConfig> updateOperations, DatadogLogCVConfig datadogLogCVConfig) {
>       setCommonOperations(updateOperations, datadogLogCVConfig);
>       if (datadogLogCVConfig.getIndexes() != null) {
> ```

why is this required? I think we should use unset to set it to null if we are unsetting index.

**Review by slobodanpavic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30333)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/DatadogLogCVConfig.java, line 77 at r1](https://reviewable.io/reviews/harness/harness-core/30333#-MuajNJ_-3mGCyKio8MW:-Muj5HyAD6nspHXGIl2Y:babbg55) ([raw file](https://github.com/harness/harness-core/blob/7a26ce48dd777a0f78b7dd90f7049d055cd7bd3e/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/DatadogLogCVConfig.java#L77)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

why is this required? I think we should use unset to set it to null if we are unsetting index. 
</blockquote></details>

Yes, you are right. The other solution could be to remove null check at all, and mark indexes field as NonNull.

**Comment by slobodanpavic** [comment]
trigger authorcheck

**Comment by slobodanpavic** [comment]
trigger blockpushmaster

**Pull request merged**
