### PR TITLE
feat: [CDS-80735]: Added settings config to Map

### PR DESCRIPTION
**Pull request by shivamnegi94**
## Describe your changes
Currently the changes for Stage timeout and Pipeline timeout was added in pipeline settings but they were not implemented.
As part of these changes we are adding timeout details to PlanContext
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54467)

### CODE REVIEW

**Comment by shivamnegi94** [comment]
trigger uts

**Comment by shivamnegi94** [comment]
trigger ut0

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54467)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 935 at r1](https://reviewable.io/reviews/harness/harness-core/54467#-NhPmUW3BW1OFlfcpAHP:-NhPmUW3BW1OFlfcpAHQ:b339uui) ([raw file](https://github.com/harness/harness-core/blob/dedbc0902bad97a29e7c51ed7321cb056cd104f5/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L935)):*
> ```Java
>   SRM_AUTO_DISCOVERY_ENABLE("The flag enables the auto discovery feature in SRM.", HarnessTeam.CV),
>   PIE_INPUTSET_RBAC_PERMISSIONS("Rbac Permissions for InputSets CRUD", PIPELINE),
>   CDS_DISABLE_TIMEOUT_CONFIG("Feature Flag to disable the timeout Configuration", HarnessTeam.CDC);
> ```

desc - max timeout configuration.
Also add MAX in FF name
___
*[`970-ng-commons/src/main/java/io/harness/constants/NGCommonEntityConstants.java` line 231 at r1](https://reviewable.io/reviews/harness/harness-core/54467#-NhPmvSM1IgzOw6v0LaI:-NhPmvSM1IgzOw6v0LaJ:bn61k59) ([raw file](https://github.com/harness/harness-core/blob/dedbc0902bad97a29e7c51ed7321cb056cd104f5/970-ng-commons/src/main/java/io/harness/constants/NGCommonEntityConstants.java#L231)):*
> ```Java
>   public static final String ACTIVITY_TYPES = "activityTypes";
>   public static final String SCOPE_FILTER = "scopeFilter";
>   public final String DEFAULT_TIMEOUT = "8w";
> ```

it should not be present here, try something in pms-commons
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/beans/PlanCreationContext.java` line 262 at r1](https://reviewable.io/reviews/harness/harness-core/54467#-NhPmfE37COkC80JXLWF:-NhPmfE37COkC80JXLWG:bs0cco5) ([raw file](https://github.com/harness/harness-core/blob/dedbc0902bad97a29e7c51ed7321cb056cd104f5/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/beans/PlanCreationContext.java#L262)):*
> ```Java
>   }
> 
>   public String getTimeoutDuration(String timeoutIdentifier) {
> ```

add comment that this will get value from settingsMap else return default value
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java` line 252 at r1](https://reviewable.io/reviews/harness/harness-core/54467#-NhPn61qCjNpP0nfgu5l:-NhPn61qCjNpP0nfgu5m:b-vtgmn4) ([raw file](https://github.com/harness/harness-core/blob/dedbc0902bad97a29e7c51ed7321cb056cd104f5/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java#L252)):*
> ```Java
>     Map<String, Boolean> featureFlagMap = new HashMap<>();
>     if (null != metadata && null != metadata.getFeatureFlagToValueMapMap()) {
>       featureFlagMap = metadata.getFeatureFlagToValueMapMap();
> ```

why we need to check executionMetadata?

**Review by shivamnegi94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54467)* status: 12 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 935 at r1](https://reviewable.io/reviews/harness/harness-core/54467#-NhPmUW3BW1OFlfcpAHP:-NhQDJCq8u5EF3qyGx3r:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dedbc0902bad97a29e7c51ed7321cb056cd104f5/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L935)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

desc - max timeout configuration.
Also add MAX in FF name
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/beans/PlanCreationContext.java` line 262 at r1](https://reviewable.io/reviews/harness/harness-core/54467#-NhPmfE37COkC80JXLWF:-NhQDHeL3Le22DxoiF_g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dedbc0902bad97a29e7c51ed7321cb056cd104f5/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/beans/PlanCreationContext.java#L262)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comment that this will get value from settingsMap else return default value
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java` line 252 at r1](https://reviewable.io/reviews/harness/harness-core/54467#-NhPn61qCjNpP0nfgu5l:-NhQAo4JE-1_RLSpUamW:bfbiay7) ([raw file](https://github.com/harness/harness-core/blob/dedbc0902bad97a29e7c51ed7321cb056cd104f5/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java#L252)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we need to check executionMetadata?
</blockquote></details>

I was thinking if it exist then we should add data to it.
___
*[`970-ng-commons/src/main/java/io/harness/constants/NGCommonEntityConstants.java` line 231 at r1](https://reviewable.io/reviews/harness/harness-core/54467#-NhPmvSM1IgzOw6v0LaI:-NhQDCVFEK4u1-54HJsB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dedbc0902bad97a29e7c51ed7321cb056cd104f5/970-ng-commons/src/main/java/io/harness/constants/NGCommonEntityConstants.java#L231)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

it should not be present here, try something in pms-commons
</blockquote></details>

Done.

**Comment by shivamnegi94** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54467)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 6 of 12 files at r1, 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54467)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/54467#-NhQMmHQ4NNK4vgeDnP6:-NhQMmHQ4NNK4vgeDnP7:b8au36b) ([raw file](https://github.com/harness/harness-core/blob/1582e33e4ef4c89cb495832f9c34b327eff3839c/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java#L89)):*
> ```Java
> public class PlanCreatorMergeService {
>   private static final int MAX_DEPTH = 10;
>   public final String DEFAULT_TIMEOUT = "8w";
> ```

nit: can we keep this `DEFAULT_TIMEOUT` at the common place so that other places can also use it? I see we have same variable with same value in another class `PlanCreationContext` as well.

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54467)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by shivamnegi94** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54467)* status: :shipit: complete! ✓

**Comment by shivamnegi94** [comment]
trigger review

**Comment by shivamnegi94** [comment]
trigger ut7, ut9

**Comment by shivamnegi94** [comment]
trigger uts

**Comment by shivamnegi94** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54467)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by shivamnegi94** [comment]
trigger ut1, ut2, ut5, ut6, ut7, ut8, ut9

**Comment by shivamnegi94** [comment]
trigger ut2, ut7, ut8, ut9

**Comment by shivamnegi94** [comment]
trigger ut2

**Comment by shivamnegi94** [comment]
trigger ut2

**Comment by shivamnegi94** [comment]
trigger messagecheck

**Comment by shivamnegi94** [comment]
trigger messagecheck

**Comment by shivamnegi94** [comment]
trigger commonchecks

**Comment by shivamnegi94** [comment]
trigger featurenamecheck

**Comment by shivamnegi94** [comment]
trigger checkstylecodeformat

**Comment by shivamnegi94** [comment]
trigger pmd, codebasehash

**Comment by shivamnegi94** [comment]
trigger review

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54467)* status: :shipit: complete! ✓

**Comment by shivamnegi94** [comment]
trigger commonchecks

**Comment by shivamnegi94** [comment]
trigger featurenamecheck

**Comment by shivamnegi94** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54467)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by shivamnegi94** [comment]
trigger ut6, ut8

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54467)* status: :shipit: complete! ✓

**Comment by shivamnegi94** [comment]
trigger review

**Comment by shivamnegi94** [comment]
trigger ut8

**Comment by shivamnegi94** [comment]
trigger uts

**Comment by shivamnegi94** [comment]
trigger ut2, ut5, ut7, ut8, ut9

**Comment by shivamnegi94** [comment]
trigger ut9

**Pull request merged**
