### PR TITLE
feat: [CDS-47035]: AutoScalingGroup Blue Green Deploy / Delegate Changes

### PR DESCRIPTION
**Pull request by vitsafronovici**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43024)

### CODE REVIEW

**Comment by arvind-choudhary-h** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/EcsAsgBaseInfrastructure.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/43024#-NMmojdT6O-0xDVQiOoF:-NMmojdT6O-0xDVQiOoG:b-pqtnw9) ([raw file](https://github.com/harness/harness-core/blob/193207e245d0e7cb87bf34cb9b3b6d8b1ab2324c/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/EcsAsgBaseInfrastructure.java#L15)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDP)
> public interface EcsAsgBaseInfrastructure {
> ```

should we name it as AwsBaseInfrastructure? It would be more clear as all infras have connector+region.

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenPrepareRollbackDataOutcome.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/43024#-NMmpYEg5TW0MYYeAIiH:-NMmpYEg5TW0MYYeAIiI:b-tn96yo) ([raw file](https://github.com/harness/harness-core/blob/193207e245d0e7cb87bf34cb9b3b6d8b1ab2324c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenPrepareRollbackDataOutcome.java#L30)):*
> ```Java
> @RecasterAlias("io.harness.cdng.aws.asg.AsgBlueGreenPrepareRollbackDataOutcome")
> public class AsgBlueGreenPrepareRollbackDataOutcome implements Outcome, ExecutionSweepingOutput {
>   Map<String, List<String>> prodAsgManifestsDataForRollback;
> ```

nit: AsgManifestData (manifests without s) -- for both prod and stage.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 29 files at r1, 3 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43024)* status: 31 file(s) to review. 0 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 20 of 29 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43024)* status: 25 file(s) to review.

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43024)* status: 25 file(s) to review. 1. unresolved discussions. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/EcsAsgBaseInfrastructure.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/43024#-NMmojdT6O-0xDVQiOoF:-NMnyo105tBfNAdJdCsX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/193207e245d0e7cb87bf34cb9b3b6d8b1ab2324c/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/EcsAsgBaseInfrastructure.java#L15)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

should we name it as AwsBaseInfrastructure? It would be more clear as all infras have connector+region.
</blockquote></details>

Done.

**Review by vitsafronovici — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43024#-:-NMnyvtG3EsTsSZDAzJi:bnfp4nl)* status: 25 file(s) to review. 1. unresolved discussions.

**Pull request merged**
