### PR TITLE
fix: [CDS-38470]: Remove old git sync for env groups

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34124)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
trigger ti0

**Comment by yogesh-chauhan** [comment]
trigger codeformat

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34124)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/BUILD.bazel` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/34124#-N46yy1y7A8F5WZqfekP:-N46yy1z3fIREYdm047F:b-owpflb) ([raw file](https://github.com/harness/harness-core/blob/f74eb32465c0bd0c695e5a83612d31d4fa83dbe6/125-cd-nextgen/BUILD.bazel#L63)):*
> ```Starlark
>         "//:lombok",
>         "//942-enforcement-sdk:module",
>         "//950-ng-core:tests",
> ```

why this is being added here? Also how is this currently working without this

**Review by prashantsharma04 — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34124)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34124)* status: :shipit: complete! ✓

**Pull request merged**
