### PR TITLE
fix: [DEL-3989]: Fetch Profile data from delegateProfileCache

### PR DESCRIPTION
**Pull request by AnupamIO**
JIRA: https://harness.atlassian.net/browse/DEL-3989

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32812)

### CODE REVIEW

**Comment by AnupamIO** [comment]
trigger messagecheck

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32812)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateProfileServiceImpl.java` line 177 at r1](https://reviewable.io/reviews/harness/harness-core/32812#-N1IODrS3xrbrQ7dw0qE:-N1IODrS3xrbrQ7dw0qF:b-vlys8z) ([raw file](https://github.com/harness/harness-core/blob/7af250d3bbd12a04567dc097061afb3f9f687f10/400-rest/src/main/java/software/wings/service/impl/DelegateProfileServiceImpl.java#L177)):*
> ```Java
>     // Update and invalidate cache
>     persistence.update(query, updateOperations);
>     delegateCache.invalidateDelegateProfileCache(delegateProfile.getAccountId(), delegateProfile.getUuid());
> ```

Wouldn't this will lead to stale entry in cache ?



_Code quote:_
```Java
delegateCache.invalidateDelegateProfileCache(delegateProfile.getAccountId(), delegateProfile.getUuid());
```

**Review by arpit3107 — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32812)* status: :shipit: complete! ✓

**Comment by AnupamIO** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/32812)_ status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`400-rest/src/main/java/software/wings/service/impl/DelegateProfileServiceImpl.java` line 177 at r1](https://reviewable.io/reviews/harness/harness-core/32812#-N1IODrS3xrbrQ7dw0qE:-N1IODrS3xrbrQ7dw0qF:b-vlys8z) ([raw file](https://github.com/harness/harness-core/blob/7af250d3bbd12a04567dc097061afb3f9f687f10/400-rest/src/main/java/software/wings/service/impl/DelegateProfileServiceImpl.java#L177)):_
> 
> > ```java
> >     // Update and invalidate cache
> >     persistence.update(query, updateOperations);
> >     delegateCache.invalidateDelegateProfileCache(delegateProfile.getAccountId(), delegateProfile.getUuid());
> > ```
> 
> Wouldn't this will lead to stale entry in cache ?
> 
> _Code quote:_
> 
> ```java
> delegateCache.invalidateDelegateProfileCache(delegateProfile.getAccountId(), delegateProfile.getUuid());
> ```



> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/32812)_ status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`400-rest/src/main/java/software/wings/service/impl/DelegateProfileServiceImpl.java` line 177 at r1](https://reviewable.io/reviews/harness/harness-core/32812#-N1IODrS3xrbrQ7dw0qE:-N1IODrS3xrbrQ7dw0qF:b-vlys8z) ([raw file](https://github.com/harness/harness-core/blob/7af250d3bbd12a04567dc097061afb3f9f687f10/400-rest/src/main/java/software/wings/service/impl/DelegateProfileServiceImpl.java#L177)):_
> 
> > ```java
> >     // Update and invalidate cache
> >     persistence.update(query, updateOperations);
> >     delegateCache.invalidateDelegateProfileCache(delegateProfile.getAccountId(), delegateProfile.getUuid());
> > ```
> 
> Wouldn't this will lead to stale entry in cache ?
> 
> _Code quote:_
> 
> ```java
> delegateCache.invalidateDelegateProfileCache(delegateProfile.getAccountId(), delegateProfile.getUuid());
> ```

as per discussion with Arpit we agreed to remove this as inconsistency is already there because this is local cache. However, we can't remove this invalidation as we are fetching again from cache just after updation: https://github.com/harness/harness-core/blob/develop/400-rest/src/main/java/software/wings/service/impl/DelegateProfileServiceImpl.java#L176-L179. Providing next rev for this.

**Comment by jennyjames21** [comment]
:lgtm:

**Review by jennyjames21 — DISMISSED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32812)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32812)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32812)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32812)* status: :shipit: complete! ✓

**Pull request merged**
