### PR TITLE
feat: [SRM-14350]: added feature flag for SLO annotations

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45515)

### CODE REVIEW

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45515)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 416 at r1](https://reviewable.io/reviews/harness/harness-core/45515#-NRCLUsd7kUBlQSJVNG3:-NRCLUsd7kUBlQSJVNG4:b-10kp8y) ([raw file](https://github.com/harness/harness-core/blob/591635d1052ebe614632b336e0644c6b13442bd6/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L416)):*
> ```Java
>   SRM_COMPOSITE_SLO("Flag to start creating composite SLOs", HarnessTeam.CV),
>   SRM_DOWNTIME("Flag to start creating downtime", HarnessTeam.CV),
>   SRM_ENABLE_SLO_ANNOTATIONS("Flag to start creating SLO annotations", HarnessTeam.CV),
> ```

let's follow what we have done for other feature, i.e rename it to SRM_SLO_ANNOTATIONS



_Code quote:_
```Java
SRM_ENABLE_SLO_ANNOTATIONS
```

**Comment by karansaraswat19** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 416 at r1](https://reviewable.io/reviews/harness/harness-core/45515#-NRCLUsd7kUBlQSJVNG3:-NRCOj5B6O73hS3UsBry:b8n2u8f) ([raw file](https://github.com/harness/harness-core/blob/591635d1052ebe614632b336e0644c6b13442bd6/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L416)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

let's follow what we have done for other feature, i.e rename it to SRM_SLO_ANNOTATIONS
</blockquote></details>

Deepak suggested this name in a thread

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45515#-:-NRDNyWCBWrdxy-oGv-Q:bnfp4nl)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45515)* status: :shipit: complete! ✓

**Pull request merged**
