### PR TITLE
[fix]: [DEL-5024]: Perpetual Task Enhancements

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
- Remove rebalance iterator and combine re-assigning functionality with  pt assignment iterator
- New delegate disconnect iterator to detect HB expiry and to fail regular and PT tasks on disconnect
- New state "PT_NON_ASSIGNABLE" to track PT's that are not assignable
- https://harness.atlassian.net/wiki/spaces/DEL/pages/21197226916/Perpetual+Task+Enhancements+Q3-22

Test case tested locally

1) Perpetual Task

-  Create new PT and successfully assigned to delegate
-  Create PT assignment fails on no eligible delegate, verify rite state
- Create PT assignment fails on validation, verify rite state
- Verify assign try count is set correctly on ever state change
- Verify assignAfterms set correctly on every state change
- Verify states set correctly on every state change
- verify unassigned reason set correctly on exceptions 
- Verify after 10 assign try count, state change to TASK_NON_ASSIGNABLE

2) Delegate Task
- verify already started task marked as failed on delegate disconnect more than 5 mins

3) Delegate disconnect verification
- Verify delegate disconnect iterator picking up delegate disconnect event
- Verify all delegate tasks assigned to delegate marked as failed 
- Verify all PT's marked as task unassigned state
- Verify delegate disconnection db entry marked as disconnected
- Verify delegate disconnect shows up in UI as soon as delegate disconnected

4) Delegate reconnect verification

- if delegate is reconnecting after 5 minutes, verify all TASK_UNASSIGNABLE pts marked ad TASK_UNASSINED
- Verify all pt's are getting assigned after reconnect

5) New delegate verification
-  when delegate gets added, verify all TASK_UNASSIGNABLE pts marked ad TASK_UNASSINED

6) PT context call fail
-  verify if context call fails, mark PT as Invalid state
- Verify PT running end to end

## Checklist
- [ x] I've documented the changes in the PR description.
- [ x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38546)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`270-delegate-service-app/delegate-service-config.yml` line 352 at r2](https://reviewable.io/reviews/harness/harness-core/38546#-NE2HEya1gUSJenDWCBG:-NE2HEyb-r1w1YEV9zbO:b-3tb2wn) ([raw file](https://github.com/harness/harness-core/blob/79147c0b97d91156be0b8b1c9470c67ec1535090/270-delegate-service-app/delegate-service-config.yml#L352)):*
> ```YAML
>     threadPoolSize: ${BLOCKING_CAPABILITY_PERMISSIONS_RECORD_ITERATOR_THREAD_COUNT:-5}
>   delegateDisconnectDetectorIteratorConfig:
>     threadPoolSize: ${DELEGATE_DISCONNECT_DETECTOR_CHECK_ITERATOR_THREAD_COUNT:-5}
> ```

do we need 5 threads?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/38546#-NE2Hy1z7HXB_l3q_s8L:-NE2Hy2-3T3fsSfcvpCq:b-vjwsfc) ([raw file](https://github.com/harness/harness-core/blob/79147c0b97d91156be0b8b1c9470c67ec1535090/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L64)):*
> ```Java
>             .fieldName(DelegateKeys.delegateDisconnectDetectorNextIteration)
>             .filterExpander(q
>                 -> q.field(DelegateKeys.status)
> ```

what does status mean? shouldn't we just rely on lastHeartBeat?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/38546#-NE2ISJt1YITokqOsAj3:-NE2ISJt1YITokqOsAj4:b-ku3mef) ([raw file](https://github.com/harness/harness-core/blob/79147c0b97d91156be0b8b1c9470c67ec1535090/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L91)):*
> ```Java
>                   delegate.getAccountId(), delegate.getUuid(), connection.getUuid()));
>       // trigger disconnect event which marks PT's as unassigned
>       delegateService.onDelegateDisconnected(delegate.getAccountId(), delegate.getUuid());
> ```

the PT logic and markTaskFailed should happen at one place. Right now this seems disconnected.

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/38546#-NE2If6L-E0lM_haRNcX:-NE2If6L-E0lM_haRNcY:bf3uash) ([raw file](https://github.com/harness/harness-core/blob/79147c0b97d91156be0b8b1c9470c67ec1535090/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L86)):*
> ```Java
>       delegateTaskServiceClassic.markAllTasksFailedForDelegate(delegate.getAccountId(), delegate.getUuid());
>       // delete delegateConnections
>       delegateConnectionDao.list(delegate.getAccountId(), delegate.getUuid())
> ```

why do we need to do this?

**Comment by jennyjames21** [comment]
*[`270-delegate-service-app/delegate-service-config.yml` line 352 at r2](https://reviewable.io/reviews/harness/harness-core/38546#-NE2HEya1gUSJenDWCBG:-NE2Kyds8Zmyvom_TX1M:bz9e8ic) ([raw file](https://github.com/harness/harness-core/blob/79147c0b97d91156be0b8b1c9470c67ec1535090/270-delegate-service-app/delegate-service-config.yml#L352)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

do we need 5 threads?
</blockquote></details>

i will reduce to 1

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 126 at r2](https://reviewable.io/reviews/harness/harness-core/38546#-NE2L3Pe2iuFxcLq2-qy:-NE2L3PgA75KMvL8cWTw:b-ftf4uv) ([raw file](https://github.com/harness/harness-core/blob/79147c0b97d91156be0b8b1c9470c67ec1535090/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L126)):*
> ```Java
>                 Delegate delegate = delegateCache.get(accountId, delegateId, true);
>                 delegateService.register(delegate);
>                 // delegateService.delegateDisconnected(accountId, delegateId, delegateConnectionId);
> ```

we should not do this, but what we do for PT on disconnected should not be called from here

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/38546#-NE2Hy1z7HXB_l3q_s8L:-NE2L1NE4YlpdrpHPcN7:btko6xm) ([raw file](https://github.com/harness/harness-core/blob/79147c0b97d91156be0b8b1c9470c67ec1535090/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L64)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

what does status mean? shouldn't we just rely on lastHeartBeat?
</blockquote></details>

status can be "Deleted" also since TTL takes while to clean up

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 78 at r2](https://reviewable.io/reviews/harness/harness-core/38546#-NE2IHVH2W4Tk2I-Tpui:-NE2LGGrCTusPB2dDJ-T:b-gwe3yp) ([raw file](https://github.com/harness/harness-core/blob/79147c0b97d91156be0b8b1c9470c67ec1535090/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L78)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need to do this?
</blockquote></details>

this will make sure, we dont run already executed ones. Im missing statement to update, will add that  

delegateService.updateLastExpiredEventHeartbeatTime(
          delegate.getLastHeartBeat(), delegate.getUuid(), delegate.getAccountId());

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java` line 255 at r2](https://reviewable.io/reviews/harness/harness-core/38546#-NE2LYj_AYNsqdqGH7qd:-NE2LYj_AYNsqdqGH7qe:b-z90dj7) ([raw file](https://github.com/harness/harness-core/blob/79147c0b97d91156be0b8b1c9470c67ec1535090/420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java#L255)):*
> ```Java
> 
>   public void markBatchOfPerpetualTasksWithNoHeartBeatToRebalanceForAccount(String accountId) {
>     long intervalValue = Long.valueOf(PerpetualTaskRecordKeys.intervalSeconds);
> ```

this is wrong and will throw an exception, PerpetualTaskRecordKeys.intervalSeconds is a string. also i think we don't need this anymore. there should be only one place where we do these updates, when the delegates disconnect because of no heartbeat for 8 mins then we mark things in different state

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/38546#-NE2If6L-E0lM_haRNcX:-NE2LiqV8sFk8Tjcb1e0:b-qogj93) ([raw file](https://github.com/harness/harness-core/blob/79147c0b97d91156be0b8b1c9470c67ec1535090/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L86)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need to do this?
</blockquote></details>

Right now ST which im removing make sure we delete all delegateConnections from DB, so we need to do the same in iterator to delete unused delegateConnections.

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 13 of 25 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38546)* status: 4. unresolved discussions. 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/38546#-NE2ISJt1YITokqOsAj3:-NE2MEys8mBlyRUW-88l:b-9sdrjn) ([raw file](https://github.com/harness/harness-core/blob/79147c0b97d91156be0b8b1c9470c67ec1535090/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L91)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

the PT logic and markTaskFailed should happen at one place. Right now this seems disconnected.
</blockquote></details>

We can combine both to use DelegateObserver::onDisconnected event(used by PT flow currently), which means make DelegateTask implements  DelegateObserver

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java` line 255 at r2](https://reviewable.io/reviews/harness/harness-core/38546#-NE2LYj_AYNsqdqGH7qd:-NE2ODMc7LlYR_k9dhjO:bbu5nn2) ([raw file](https://github.com/harness/harness-core/blob/79147c0b97d91156be0b8b1c9470c67ec1535090/420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java#L255)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this is wrong and will throw an exception, PerpetualTaskRecordKeys.intervalSeconds is a string. also i think we don't need this anymore. there should be only one place where we do these updates, when the delegates disconnect because of no heartbeat for 8 mins then we mark things in different state
</blockquote></details>

ignore this, some how it got added to my PR. I will remove this

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 126 at r2](https://reviewable.io/reviews/harness/harness-core/38546#-NE2L3Pe2iuFxcLq2-qy:-NE2ONez2R4Wez3hxD3p:b-5l4b3) ([raw file](https://github.com/harness/harness-core/blob/79147c0b97d91156be0b8b1c9470c67ec1535090/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L126)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should not do this, but what we do for PT on disconnected should not be called from here
</blockquote></details>

Can you elaborate? I'm removing this statement from the web socket disconnect event and relying on the iterator to mark PT to UN_ASSIGNED.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/38546#-NE2ISJt1YITokqOsAj3:-NE3rZ733pPHxcPee1af:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/79147c0b97d91156be0b8b1c9470c67ec1535090/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L91)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

We can combine both to use DelegateObserver::onDisconnected event(used by PT flow currently), which means make DelegateTask implements  DelegateObserver 
</blockquote></details>

updated

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/38546#-NE2If6L-E0lM_haRNcX:-NE3rbcv2iif3Xpl1ssc:bgykelb) ([raw file](https://github.com/harness/harness-core/blob/79147c0b97d91156be0b8b1c9470c67ec1535090/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L86)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Right now ST which im removing make sure we delete all delegateConnections from DB, so we need to do the same in iterator to delete unused delegateConnections. 
</blockquote></details>

Correction ST is not deleting current version delegate connection. Should we delete all delegateConnections is disconnect detected?

**Comment by raghuAtWings** [comment]
*[`270-delegate-service-app/delegate-service-config.yml` line 352 at r2](https://reviewable.io/reviews/harness/harness-core/38546#-NE2HEya1gUSJenDWCBG:-NE7WMow5NJX3Z55vV0g:b-g0ejvj) ([raw file](https://github.com/harness/harness-core/blob/79147c0b97d91156be0b8b1c9470c67ec1535090/270-delegate-service-app/delegate-service-config.yml#L352)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

i will reduce to 1
</blockquote></details>

it needs at least 2

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 126 at r6](https://reviewable.io/reviews/harness/harness-core/38546#-NEEXd7O27ad7xZqDwKr:-NEEXd7O27ad7xZqDwKs:byfsjt) ([raw file](https://github.com/harness/harness-core/blob/fc50010f38548635b37d4f2e57a80fc682bd99b3/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L126)):*
> ```Java
>                 Delegate delegate = delegateCache.get(accountId, delegateId, true);
>                 delegateService.register(delegate);
>                 delegateService.delegateDisconnected(accountId, delegateId, delegateConnectionId);
> ```

do we need to do this?

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 126 at r6](https://reviewable.io/reviews/harness/harness-core/38546#-NEEXd7O27ad7xZqDwKr:-NEEbGKf1gBahjGUsWMr:b-vgues7) ([raw file](https://github.com/harness/harness-core/blob/fc50010f38548635b37d4f2e57a80fc682bd99b3/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L126)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

do we need to do this?
</blockquote></details>

yes, UI call currently rely on the disconnected flag in DelegateDisconnection.  So if there are any WebSocket disconnect this will make sure to show it UI accordingly.
 Old logic has this along with rebalancing task.

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java` line 282 at r11](https://reviewable.io/reviews/harness/harness-core/38546#-NEgGhBT8Jk2Tbqb3Fn3:-NEgGhBT8Jk2Tbqb3Fn4:bqagi3b) ([raw file](https://github.com/harness/harness-core/blob/224193db4ff7a393dc2c414460bda32458498c0f/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L282)):*
> ```Java
>     } catch (Exception e) {
>       log.error("Error while fetching perpetual task context task params ", e);
>       markStateAndNonAssignedReason_OnAssignTryCount(
> ```

are we putting the reason on why the task was marked invalid?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 3 of 8 files at r3, 3 of 12 files at r5, 1 of 3 files at r6, 3 of 4 files at r7, 7 of 9 files at r8, 2 of 2 files at r9, 2 of 2 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38546)* status: 1. unresolved discussions. 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java` line 282 at r11](https://reviewable.io/reviews/harness/harness-core/38546#-NEgGhBT8Jk2Tbqb3Fn3:-NEnzyD2-ci5DZAicNJQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/224193db4ff7a393dc2c414460bda32458498c0f/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L282)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

are we putting the reason on why the task was marked invalid? 
</blockquote></details>

Done.

**Comment by raghuAtWings** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/UpdateRebalanceStateToTaskUnAssigned.java` line 25 at r12](https://reviewable.io/reviews/harness/harness-core/38546#-NEo27c--nvmtfqWvGsq:-NEo27c02V_e2pfQVodj:b-x1h9vx) ([raw file](https://github.com/harness/harness-core/blob/9d7b3e041c02da1142d23ba5aa6b204895b7850f/390-db-migration/src/main/java/io/harness/migrations/UpdateRebalanceStateToTaskUnAssigned.java#L25)):*
> ```Java
>                                  .fetch())) {
>       while (perpetualTasks.hasNext()) {
>         updateStateToTaskUnAssigned(perpetualTasks.next().getUuid());
> ```

we should not do one update a time. prepare a list of taskIds and then update in one shot

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java` line 283 at r12](https://reviewable.io/reviews/harness/harness-core/38546#-NEo2GUO5dUP3yF-raOB:-NEo2GUO5dUP3yF-raOC:b-97o0qp) ([raw file](https://github.com/harness/harness-core/blob/9d7b3e041c02da1142d23ba5aa6b204895b7850f/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L283)):*
> ```Java
>       log.error("Error while fetching perpetual task context task params ", e);
>       perpetualTaskRecordDao.updateInvalidStateWithExceptions(
>           perpetualTaskRecord, PerpetualTaskUnassignedReason.PT_TASK_FAILED, e.toString());
> ```

use ExceptionUtils.getMessage

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/resources/metrics/metricDefinitions/delegate_metrics.yaml` line 50 at r12](https://reviewable.io/reviews/harness/harness-core/38546#-NEo2SAS0upGpjEGv_Wv:-NEo2SATCX6m0dqr3SEx:b23kq5t) ([raw file](https://github.com/harness/harness-core/blob/9d7b3e041c02da1142d23ba5aa6b204895b7850f/400-rest/src/main/resources/metrics/metricDefinitions/delegate_metrics.yaml#L50)):*
> ```YAML
>     unit: count
>   - metricName: perpetual_tasks_paused_num
>     metricDefinition: Perpetual tasks paused
> ```

you should remove the rebalance one from here

**Comment by jennyjames21** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/UpdateRebalanceStateToTaskUnAssigned.java` line 25 at r12](https://reviewable.io/reviews/harness/harness-core/38546#-NEo27c--nvmtfqWvGsq:-NEo3mCR0Nk4bsck2UXQ:b-w3g61q) ([raw file](https://github.com/harness/harness-core/blob/9d7b3e041c02da1142d23ba5aa6b204895b7850f/390-db-migration/src/main/java/io/harness/migrations/UpdateRebalanceStateToTaskUnAssigned.java#L25)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should not do one update a time. prepare a list of taskIds and then update in one shot
</blockquote></details>

Around 11,000 task are currently in rebalance state. Will one shot create any issue? maybe batch of 50.

Another possibility is it might overload task assignment iterator for some time.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/resources/metrics/metricDefinitions/delegate_metrics.yaml` line 50 at r12](https://reviewable.io/reviews/harness/harness-core/38546#-NEo2SAS0upGpjEGv_Wv:-NEo7aWj0oOeJb_Okz4a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9d7b3e041c02da1142d23ba5aa6b204895b7850f/400-rest/src/main/resources/metrics/metricDefinitions/delegate_metrics.yaml#L50)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

you should remove the rebalance one from here
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java` line 283 at r12](https://reviewable.io/reviews/harness/harness-core/38546#-NEo2GUO5dUP3yF-raOB:-NEo7c-OCt09g_V28jYn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9d7b3e041c02da1142d23ba5aa6b204895b7850f/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L283)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

use ExceptionUtils.getMessage
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/UpdateRebalanceStateToTaskUnAssigned.java` line 25 at r12](https://reviewable.io/reviews/harness/harness-core/38546#-NEo27c--nvmtfqWvGsq:-NEq-7VM9VMWbx4ALkod:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9d7b3e041c02da1142d23ba5aa6b204895b7850f/390-db-migration/src/main/java/io/harness/migrations/UpdateRebalanceStateToTaskUnAssigned.java#L25)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Around 11,000 task are currently in rebalance state. Will one shot create any issue? maybe batch of 50.

Another possibility is it might overload task assignment iterator for some time. 
</blockquote></details>

done

**Comment by raghuAtWings** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/UpdateRebalanceStateToTaskUnAssigned.java` line 25 at r12](https://reviewable.io/reviews/harness/harness-core/38546#-NEo27c--nvmtfqWvGsq:-NEqHiL4ADqs1mSjfy3C:b-rpjuyb) ([raw file](https://github.com/harness/harness-core/blob/9d7b3e041c02da1142d23ba5aa6b204895b7850f/390-db-migration/src/main/java/io/harness/migrations/UpdateRebalanceStateToTaskUnAssigned.java#L25)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

done
</blockquote></details>

since state is indexed, we should be okay

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 5 of 8 files at r12, 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38546)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
trigger codebasehash

**Pull request merged**
