### PR TITLE
[techdebt]: [PIE-2679]: Add JSON expansion handlers to CI Manager

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30703)

### CODE REVIEW

**Review by naidu-harness — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30703#-:-MvbvtaUCbjG0tYA-OCh:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by namanvermah** [comment]
For pipeline governance, we need to expand certain fields like connectorRef . Each service needs to register certain handlers to support these expansions. CD service has been already onboarded, onboarding CI service now.
Example: https://harness.atlassian.net/wiki/spaces/CDNG/pages/2008711233/Sample+Expanded+Pipeline+Json

**Review by harshjain12 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30703#-:-Mvbwiyv56LVmK4_K5kd:bnfp4nl)* status: :shipit: complete! ✓

**Review by harshjain12 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30703#-:-Mvc-LLP32NSeT9c1SqO:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30703)* status: :shipit: complete! ✓

**Pull request merged**
