### PR TITLE
[fix]: [PL-22188]: Fix the issue of heartbeat of non default branch connector

### PR DESCRIPTION
**Pull request by DeepakPatankar**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30311)

### CODE REVIEW

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30311)* status: 5 file(s) to review. 0 of 2 approvals obtained. 

___
*[440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java, line 524 at r1](https://reviewable.io/reviews/harness/harness-core/30311#-MuVWEK46w9fFUa5r9Vg:-MuVWEK46w9fFUa5r9Vh:b-tmmji7) ([raw file](https://github.com/harness/harness-core/blob/c3f9413157b62a4e476aaa0e2d7a3af2e1fe0f60/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L524)):*
> ```Java
>     }
>     Connector connector = existingConnectorOptional.get();
>     connector.setHeartbeatPerpetualTaskId(null);
> ```

Why are we setting it as null. by default it will be null only, I think

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30311#-:-MuVkdW3CFe_8-DhhX7E:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30311)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java, line 524 at r1](https://reviewable.io/reviews/harness/harness-core/30311#-MuVWEK46w9fFUa5r9Vg:-MuVnNFp72wOU18OgGi-:b-j2gl4z) ([raw file](https://github.com/harness/harness-core/blob/c3f9413157b62a4e476aaa0e2d7a3af2e1fe0f60/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L524)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Why are we setting it as null. by default it will be null only, I think
</blockquote></details>

If the connector was already present in the project then heartbeatPerpetual task would already be present. Hence we need to remove it

**Review by bhavya181 — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30311)* status: :shipit: complete! ✓

**Pull request merged**
