### PR TITLE
feat: [IDP-282]: Add support for plain-text environment configs

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Describe your changes
1. Renaming EnvironmentSecret to BackstageEnvVariable everywhere.
2. BackstageEnvVariable will be abstract. BackstageEnvConfigVariable (plain text value case) and BackstageEnvSecretVariable (harness secret case) will build on this.
3. Same inheritance has been replicated in openapi using AllOf construct.
4. Using MapBinder to resolve Mapper for the above 2 types.
5. Refactored GitIntegrationUtils to return the secret identifier and moved decryption into separate method as  BackstageEnvVariable won't support decryptedValue for secret type.
6. Most of the other changes are moving around files and renaming classes.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45537)

### CODE REVIEW

**Comment by vikyathharekal** [comment]
trigger messagecheck

**Review by sandeepa-kv-jois — DISMISSED** [review]

**Review by vigneswara-propelo — COMMENTED** [review]
> Reviewed 17 of 41 files at r1, 2 of 5 files at r2, 4 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45537)* status: 42 file(s) to review. 1 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/envvariable/beans/entity/BackstageEnvConfigVariableEntity.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/45537#-NRHT1HP2EuN3T6YIl_W:-NRHT1HP2EuN3T6YIl_X:b-by1s06) ([raw file](https://github.com/harness/harness-core/blob/812340c5e9d4d795ff1342bc980a6b204da46d04/idp-service/src/main/java/io/harness/idp/envvariable/beans/entity/BackstageEnvConfigVariableEntity.java#L30)):*
> ```Java
> @StoreIn(DbAliases.IDP)
> @Entity(value = "environmentSecrets", noClassnameStored = true)
> @Document("environmentSecrets")
> ```

this should be backstageEnvVariable right?🤔



_Code quote:_
```Java
environmentSecrets
```
___
*[`idp-service/src/main/java/io/harness/idp/envvariable/beans/entity/BackstageEnvSecretVariableEntity.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/45537#-NRHTALh0CQt52xf3Ri9:-NRHTALh0CQt52xf3RiA:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/812340c5e9d4d795ff1342bc980a6b204da46d04/idp-service/src/main/java/io/harness/idp/envvariable/beans/entity/BackstageEnvSecretVariableEntity.java#L30)):*
> ```Java
> @StoreIn(DbAliases.IDP)
> @Entity(value = "environmentSecrets", noClassnameStored = true)
> @Document("environmentSecrets")
> ```

same here

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45537)* status: 42 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/envvariable/beans/entity/BackstageEnvConfigVariableEntity.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/45537#-NRHT1HP2EuN3T6YIl_W:-NRHuv7J6wzI8K2J-eKw:bdbjvwx) ([raw file](https://github.com/harness/harness-core/blob/812340c5e9d4d795ff1342bc980a6b204da46d04/idp-service/src/main/java/io/harness/idp/envvariable/beans/entity/BackstageEnvConfigVariableEntity.java#L30)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

this should be backstageEnvVariable right?🤔
</blockquote></details>

These are not needed actually. BackstageEnvVariableEntity will take care of it. Removing

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45537)* status: 42 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/envvariable/beans/entity/BackstageEnvConfigVariableEntity.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/45537#-NRHT1HP2EuN3T6YIl_W:-NRHw_8P-s7nU6OdohOi:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/812340c5e9d4d795ff1342bc980a6b204da46d04/idp-service/src/main/java/io/harness/idp/envvariable/beans/entity/BackstageEnvConfigVariableEntity.java#L30)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

These are not needed actually. BackstageEnvVariableEntity will take care of it. Removing
</blockquote></details>

Done

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45537)* status: 42 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/envvariable/beans/entity/BackstageEnvSecretVariableEntity.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/45537#-NRHTALh0CQt52xf3Ri9:-NRHwc2D5pzMRHFmrhjI:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/812340c5e9d4d795ff1342bc980a6b204da46d04/idp-service/src/main/java/io/harness/idp/envvariable/beans/entity/BackstageEnvSecretVariableEntity.java#L30)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Removed

**Review by vigneswara-propelo — DISMISSED** [review]
> Reviewed 12 of 41 files at r1, 1 of 5 files at r2, 4 of 10 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45537)* status: 42 file(s) to review. 1 of 2 approvals obtained.

**Comment by vikyathharekal** [comment]
trigger ut7

**Review by vigneswara-propelo — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45537)* status: 42 file(s) to review. 1 of 2 approvals obtained.

**Review by deepharness — APPROVED** [review]
> Reviewed 27 of 41 files at r1, 2 of 5 files at r2, 6 of 10 files at r3, 2 of 2 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45537)* status: :shipit: complete! ✓

**Pull request merged**
