### PR TITLE
feat: [PIE-5977]: Support for filtering of pipeline executions using …

### PR DESCRIPTION
**Pull request by devesh-harness**
…multiple pipeline instead of single pipeline

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39136)

### CODE REVIEW

**Review by sandeepa-kv-jois — COMMENTED** [review]
Few observations:
1) We need to check if the request has max 10 entries in the pipelineID list. If it has more than 10, we need to give an appropriate error message. This check is needed to avoid choking the DB.
2) Also, check max limit can be read from the config, so we don't need code change in the future if we need to increase this limit
3) Add a private API tag for this endpoint so that it won't be exported in OpenAPI spec for external usage
4) Add relevent unit tests

**Comment by devesh-harness** [comment]
trigger TIbootstrap2-ti2

**Comment by devesh-harness** [comment]
trigger MessageMetadata-message_metadata

**Comment by devesh-harness** [comment]
trigger checkstyle

**Comment by devesh-harness** [comment]
trigger CodeFormat

**Comment by devesh-harness** [comment]
trigger TIbootstrap2

**Comment by devesh-harness** [comment]
trigger codeformat

**Comment by devesh-harness** [comment]
trigger tibootstrap2

**Comment by devesh-harness** [comment]
trigger messagemetadata

**Comment by devesh-harness** [comment]
trigger messagemetadata

**Comment by devesh-harness** [comment]
trigger messagecheck

**Comment by devesh-harness** [comment]
trigger checkstyle

**Comment by devesh-harness** [comment]
trigger ti2

**Comment by devesh-harness** [comment]
trigger recency

**Comment by devesh-harness** [comment]
trigger ti2

**Comment by devesh-harness** [comment]
trigger ti2

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 5 files at r3, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39136)* status: Some of the checks are too old. 5 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 187 at r5](https://reviewable.io/reviews/harness/harness-core/39136#-NFhMFNv5CTWNaZ-NbpP:-NG07Qv7Eup081kfmFhP:b34bw28) ([raw file](https://github.com/harness/harness-core/blob/32e38f74842895bc2a3b1d3b357f9e214f8bb3cb/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L187)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Does it have to be a new API? Can we add the new field "pipelineIdentifiers" in the existing API?
</blockquote></details>

THis is for internal api and not exposed to customer, existing API addition will lead to breaking of api
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 193 at r5](https://reviewable.io/reviews/harness/harness-core/39136#-NFhMRc2E1gPRaRbwnG7:-NG07PFb7y_V3oV4_wBq:b32v57) ([raw file](https://github.com/harness/harness-core/blob/32e38f74842895bc2a3b1d3b357f9e214f8bb3cb/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L193)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

avoid code duplication. You can create a new method for the other fields and use it from both places
</blockquote></details>

+1

**Review by sandeepa-kv-jois — APPROVED** [review]

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39136)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by sandeepa-kv-jois — APPROVED** [review]

**Review by sarthakkasat — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39136)* status: :shipit: complete! ✓

**Pull request merged**
