### PR TITLE
feat: [DEL-3519]: apis for downloading ng delegates

### PR DESCRIPTION
**Pull request by arpit3107**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33162)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33162)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java` line 161 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MAmdAEBfqYK0ypoXp:-N2MAmdB6Yh3cVf4QtnV:b-1rjwlf) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java#L161)):*
> ```Java
>       @Query(NGCommonEntityConstants.ORG_KEY) String orgIdentifier,
>       @Query(NGCommonEntityConstants.PROJECT_KEY) String projectIdentifier,
>       @Body @NotNull DelegateSetupDetails delegateSetupDetails);
> ```

Let's try not use DelegateSetupDetails. The object is too complex and bloated and also serialized to yaml (not sure why). We need something much simpler.

**Review by mdmilic — CHANGES_REQUESTED** [review]
I would recommend making all the fields (I think they all are), local variables and method params final/immutable when possible. Then for those not possible figure out why not and try to find a way to make it possible. 

> Reviewed 6 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33162#-:-N2MXXuE7t0TF8zvwUmO:b-edvffp)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MX8y94GyNguStaauh:-N2MX8y94GyNguStaaui:b-jz0fo) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java#L53)):*
> ```Java
> @Produces("application/json")
> @Consumes({"application/json"})
> @OwnedBy(HarnessTeam.DEL)
> ```

What's the auth for this?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MWcVfCI2ux_NXTlnd:-N2MWcVfCI2ux_NXTlne:bga2038) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java#L93)):*
> ```Java
>       })
>   public Response
>   downloadDelegate(@Parameter(description = NGCommonEntityConstants.ACCOUNT_PARAM_MESSAGE) @QueryParam(
> ```

Who is the intended user for these APIs? Since different delegate types have some different parameters, maybe we should create a separate endpoint for each delegate type and have more meaningful input params e.g. downloadDockerDelegate etc...
___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateDownloadServiceImpl.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MVFZY6o1ug9xP-rD4:-N2MVFZY6o1ug9xP-rD5:bh12v0c) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateDownloadServiceImpl.java#L98)):*
> ```Java
>   }
> 
>   private void checkAndBuildProperDelegateSetupDetails(
> ```

Usually it's a bad sign if you have keywords like and/or/maybe etc.. in your method names, that means that they should be broken down to multiple methods 
___
*[`400-rest/src/main/java/io/harness/delegate/service/intfc/DelegateDownloadService.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MQq4H9oJCqtZ_w0Wr:-N2MQq4H9oJCqtZ_w0Ws:b6guejz) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/400-rest/src/main/java/io/harness/delegate/service/intfc/DelegateDownloadService.java#L17)):*
> ```Java
> 
> @OwnedBy(DEL)
> public interface DelegateDownloadService {
> ```

I know we usually create interfaces for "Service" classes, but they are mostly useless for us. Only causing you to write more Guice code and zero benefits. I started avoiding to put interfaces now, but I would say it's up to you right now what you like more. 
___
*[`400-rest/src/main/java/software/wings/service/intfc/DelegateService.java` line 225 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MQ-XQ-GkmA_UV0Dtu:-N2MQ-XQ-GkmA_UV0Dtv:b-xl2yvh) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/400-rest/src/main/java/software/wings/service/intfc/DelegateService.java#L225)):*
> ```Java
>       String accountId, String delegateTokenName, DelegateApproval action) throws InvalidRequestException;
> 
>   void checkUniquenessOfDelegateName(String accountId, String delegateName, boolean isNg);
> ```

You should probably rename it to something like `doesDelegateExist(...)` and return boolean. That way every caller can decide what to do if not unique. 



_Code quote (from 400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java):_
```Java
checkUniquenessOfDelegateName
```

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33162)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java` line 157 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MYOL52PeEl-Zi8FyL:-N2MYOL52PeEl-Zi8FyM:b-waaubt) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java#L157)):*
> ```Java
> 
>   @POST(DELEGATE_DOWNLOAD_API)
>   Call<RestResponse<DelegateDownloadResponse>> downloadDelegate(
> ```

Why do we need to go through this client, can't we just go to NG directly?

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33162)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2McD7P0WbFjSrfllZp:-N2McD7P0WbFjSrfllZq:b-e86nrl) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java#L100)):*
> ```Java
>           NGCommonEntityConstants.PROJECT_KEY) String projectIdentifier,
>       @RequestBody(required = true, description = "Parameters needed for downloading a specific delegate file")
>       DelegateSetupDetails delegateSetupDetails) {
> ```

what will be passed in this object ?



_Code quote:_
```Java
delegateSetupDetails
```
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java` line 110 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2McITz63xtylUe3zoh:-N2McITz63xtylUe3zoi:b-4pyfcp) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java#L110)):*
> ```Java
>     }
>     return Response.ok(delegateDownloadResponse.getDelegateFile())
>         .header(CONTENT_TRANSFER_ENCODING, BINARY)
> ```

Instead of text, can we directly return .yaml file ?



_Code quote:_
```Java
    return Response.ok(delegateDownloadResponse.getDelegateFile())
        .header(CONTENT_TRANSFER_ENCODING, BINARY)
        .type("text/plain; charset=UTF-8")
        .build();
```

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33162)* status: 4 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java` line 157 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MYOL52PeEl-Zi8FyL:-N2Q62nVAiU7XDAIwfPD:bgro21g) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java#L157)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Why do we need to go through this client, can't we just go to NG directly?
</blockquote></details>

No, all our delegate code lives on CG manager only, and we have decided to not move that to NG manager , even for NG use cases.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java` line 161 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MAmdAEBfqYK0ypoXp:-N2QLCqu-eCxzkuZ5Xtd:bedgeej) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java#L161)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Let's try not use DelegateSetupDetails. The object is too complex and bloated and also serialized to yaml (not sure why). We need something much simpler. 
</blockquote></details>

Yes, but you don't need to pass all those things in the request body. You can just pass delegateName and delegateType. Rest all will be handled as default internally.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MX8y94GyNguStaauh:-N2QLqsuB7wKlNPBTshI:b24562p) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java#L53)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

What's the auth for this?
</blockquote></details>

the usual bearer token or apiKey will work.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MWcVfCI2ux_NXTlnd:-N2QM50M4uF7Cj0tWNvS:b-qzofrd) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java#L93)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Who is the intended user for these APIs? Since different delegate types have some different parameters, maybe we should create a separate endpoint for each delegate type and have more meaningful input params e.g. downloadDockerDelegate etc...
</blockquote></details>

parameters will be same, its just that in body you have to pass delegateType as KUBERNETES or DOCKER.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2McD7P0WbFjSrfllZp:-N2QMI9i7N4tORDdHKuI:bh2ldil) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java#L100)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

what will be passed in this object ?
</blockquote></details>

You have to pass minimum of delegateName and delegateType (KUBERNETES/DOCKER). Otherwise you have option to pass tags,descruption,tokenName all those things.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java` line 110 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2McITz63xtylUe3zoh:-N2QMYiX6SD0X484Ecid:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java#L110)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Instead of text, can we directly return .yaml file ?
</blockquote></details>

ok
___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateDownloadServiceImpl.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MVFZY6o1ug9xP-rD4:-N2QMbKe3hwHigfEFKZ1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateDownloadServiceImpl.java#L98)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Usually it's a bad sign if you have keywords like and/or/maybe etc.. in your method names, that means that they should be broken down to multiple methods 
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/intfc/DelegateService.java` line 225 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MQ-XQ-GkmA_UV0Dtu:-N2QNFtPAl5wAS6-yt9H:b-x0re8k) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/400-rest/src/main/java/software/wings/service/intfc/DelegateService.java#L225)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You should probably rename it to something like `doesDelegateExist(...)` and return boolean. That way every caller can decide what to do if not unique. 
</blockquote></details>

actually this method itself will throw proper errors and caller doesnt need to bother about

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33162)* status: Some of the checks are too old. 4 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java` line 161 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MAmdAEBfqYK0ypoXp:-N2kP8v1DBLnZ_afPiQy:b-ojkl01) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java#L161)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

Yes, but you don't need to pass all those things in the request body. You can just pass delegateName and delegateType. Rest all will be handled as default internally.
</blockquote></details>

Having all this extra fields is confusing to customers, regardless if they are optional or not, they would need to be documented in the API and customers will have to know about them. It's better to have more minimal APIs with clearly defined fields. This objects has fields specific to CG, NG and various delegate types a lot of which doesn't apply to specific use cases. 
The additional problem with DelegateSetupDetails is that it's yaml. We need it to be json because it's used by customers.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MX8y94GyNguStaauh:-N2kOLSo2OvTRG2LmT49:b-lhajaq) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java#L53)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

the usual bearer token or apiKey will work.
</blockquote></details>

I'm not seeing the annotations, that's why I'm asking. For API Key you also need to specify the user permissions. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MWcVfCI2ux_NXTlnd:-N2kQIGN6mvU1EoUo0SQ:b-i14mn3) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java#L93)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

parameters will be same, its just that in body you have to pass delegateType as KUBERNETES or DOCKER.
</blockquote></details>

I meant that based on the delegate type, some fields from this massive object are used and others ignored, so if the requirements are different per delegate type it might make more sense to separate that to multiple APIs instead of bundling it into a single one. You should definitely not use DelegateSetupDetails, but I'm on the fence if you should have multiple APIs or one. 
Generally with API design you should follow single responsibility principle. This is a bit corner case, since the responsibility is downloading delegate, but also they are so different (and most customers will only use one type), that you could consider them different responsibilities (e.g. download k8s delegate, download docker delegate etc..). That's why I think you should consider having multiple endpoints and multiple request objects (one for each delegate type) each request object should have only fields specific to that delegate type. 
Caller use cases also need to be considered, you want to minimise the business logic needed for calling your API (e.g. if this, then do that, provide that info etc..).
@gaurav-jain1 what do you think is better?

**Review by mdmilic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33162)* status: Some of the checks are too old. 4 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MWcVfCI2ux_NXTlnd:-N2kwa0V6TOSgnXyHMPA:b-edcsrf) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java#L93)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I meant that based on the delegate type, some fields from this massive object are used and others ignored, so if the requirements are different per delegate type it might make more sense to separate that to multiple APIs instead of bundling it into a single one. You should definitely not use DelegateSetupDetails, but I'm on the fence if you should have multiple APIs or one. 
Generally with API design you should follow single responsibility principle. This is a bit corner case, since the responsibility is downloading delegate, but also they are so different (and most customers will only use one type), that you could consider them different responsibilities (e.g. download k8s delegate, download docker delegate etc..). That's why I think you should consider having multiple endpoints and multiple request objects (one for each delegate type) each request object should have only fields specific to that delegate type. 
Caller use cases also need to be considered, you want to minimise the business logic needed for calling your API (e.g. if this, then do that, provide that info etc..).
@gaurav-jain1 what do you think is better?
</blockquote></details>

Actually on the second thought I more think it should be a separate API for each delegate type. This way each endpoint can specify the content type it actually returns (e.g. yaml, binary for zip, probably text for shell script etc...)
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java` line 85 at r2](https://reviewable.io/reviews/harness/harness-core/33162#-N2kxUAf7Jacs6eX1Ccl:-N2kxUAf7Jacs6eX1Ccm:bs9juh7) ([raw file](https://github.com/harness/harness-core/blob/e4eee2078fed400667b29065d86bdf5e7b23796e/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java#L85)):*
> ```Java
>   }
> 
>   @POST
> ```

This should be HTTP get

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33162)* status: Some of the checks are too old. 4 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java` line 85 at r2](https://reviewable.io/reviews/harness/harness-core/33162#-N2kxUAf7Jacs6eX1Ccl:-N2kyf7r2MrBCaaUcHrp:byod3bp) ([raw file](https://github.com/harness/harness-core/blob/e4eee2078fed400667b29065d86bdf5e7b23796e/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java#L85)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This should be HTTP get
</blockquote></details>

Actually the request would probably end up being to large, so maybe for convenience we have to use POST

**Review by AnupamIO — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33162)* status: Some of the checks are too old. 4 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateDownloadServiceImpl.java` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/33162#-N2pBKQu8pCtxqoZK1wM:-N2pBKQu8pCtxqoZK1wN:b-iuulb8) ([raw file](https://github.com/harness/harness-core/blob/e4eee2078fed400667b29065d86bdf5e7b23796e/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateDownloadServiceImpl.java#L80)):*
> ```Java
>       File delegateFile = delegateService.generateKubernetesYaml(
>           accountId, delegateSetupDetails, managerHost, verificationServiceUrl, MediaType.TEXT_PLAIN_TYPE);
>       return new DelegateDownloadResponse(null, delegateFile);
> ```

please check, if sending File in response from cg-manager works in pr env. Most likely it will not work as File is created in cg-manager and while you send File to ng-manager, ng-manager will go to same location to search for file resulting in FileNotFoundException. It will work in local because both ng and cg manager are running on same machine.

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33162)* status: 7 file(s) to review. 3 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java` line 161 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MAmdAEBfqYK0ypoXp:-N3FYlrh7Mb_lUwZkuJb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java#L161)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Having all this extra fields is confusing to customers, regardless if they are optional or not, they would need to be documented in the API and customers will have to know about them. It's better to have more minimal APIs with clearly defined fields. This objects has fields specific to CG, NG and various delegate types a lot of which doesn't apply to specific use cases. 
The additional problem with DelegateSetupDetails is that it's yaml. We need it to be json because it's used by customers.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MX8y94GyNguStaauh:-N3FYrB4-JlIS13_Ma0S:b-sw39sj) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java#L53)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I'm not seeing the annotations, that's why I'm asking. For API Key you also need to specify the user permissions. 
</blockquote></details>

no, access control client inside the methods will take care of it.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/33162#-N2MWcVfCI2ux_NXTlnd:-N3FZ70TEl77ub0ENL9k:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/fd7cf1091ce16c469a5a0d23cb9270a6ea0ef510/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateDownloadResource.java#L93)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Actually on the second thought I more think it should be a separate API for each delegate type. This way each endpoint can specify the content type it actually returns (e.g. yaml, binary for zip, probably text for shell script etc...)
</blockquote></details>

Done
___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateDownloadServiceImpl.java` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/33162#-N2pBKQu8pCtxqoZK1wM:-N3FZFCMC90LPsgZMLM_:bhijpev) ([raw file](https://github.com/harness/harness-core/blob/e4eee2078fed400667b29065d86bdf5e7b23796e/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateDownloadServiceImpl.java#L80)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

please check, if sending File in response from cg-manager works in pr env. Most likely it will not work as File is created in cg-manager and while you send File to ng-manager, ng-manager will go to same location to search for file resulting in FileNotFoundException. It will work in local because both ng and cg manager are running on same machine.
</blockquote></details>

checking. Thanks!

**Review by AnupamIO — APPROVED** [review]
> Reviewed 2 of 11 files at r1, 3 of 7 files at r3, 2 of 5 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33162)* status: 2 change requests. 2. unresolved discussions.

**Review by mdmilic — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33162)* status: 1 change requests. 2. unresolved discussions.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 2 of 11 files at r1, 3 of 7 files at r3, 2 of 5 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33162)* status: :shipit: complete! ✓

**Pull request merged**
