### PR TITLE
fix: [FFM-3550]: Send correct number of target patch instructions to cf

### PR DESCRIPTION
**Pull request by conormurray95**
## Describe your changes
See ticket [here](https://harness.atlassian.net/browse/FFM-3550) for detailed description of the problem. 
When creating patch instruction rules to add targets to the feature flag system we were looping over all the account id's, and for each account id adding **all** accounts as a rule. This meant we were ending up with e.g. 88 patch rules each adding all 88 targets. See sample request data [here](https://jsonformatter.org/json-parser/b0c45b)
To resolve this we can just remove the loop and unnecessary code and create a single patch instruction to add the targets

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33774)

### CODE REVIEW

**Comment by conormurray95** [comment]
trigger ti1

**Comment by conormurray95** [comment]
trigger ti3

**Comment by conormurray95** [comment]
trigger ti1

**Comment by conormurray95** [comment]
trigger ti3

**Review by davejohnston — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33774)* status: :shipit: complete! ✓

**Pull request merged**
