### PR TITLE
feat:[del-5594]: add fetching installation command API

### PR DESCRIPTION
**Pull request by xingchi-jin**
## Describe your changes
Add an API to fetch installation commands for helm, terraform and docker

Screen Shot 2022-12-21 at 8 48 56 PM
Screen Shot 2022-12-21 at 8 49 05 PM
Screen Shot 2022-12-21 at 8 49 13 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41852)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/41852#-NKswjSGCxpNHNYYoNow:-NKswjSGCxpNHNYYoNox:bq8964x) ([raw file](https://github.com/harness/harness-core/blob/259324659223971a115f67c146a0e6c2205722ce/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java#L32)):*
> ```Java
> 
>   private static final String DOCKER_COMMAND = "docker run -d --name=docker-delegate --cpus=0.5 --memory=2g "
>       + "-e DELEGATE_NAME=docker-delegate "
> ```

every line should come in new line in the API response

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/41852#-NKswvj_3Iza2KGI-vwX:-NKswvj_3Iza2KGI-vwY:b-doh6j1) ([raw file](https://github.com/harness/harness-core/blob/259324659223971a115f67c146a0e6c2205722ce/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java#L43)):*
> ```Java
>       + "harness/harness-delegate-ng "
>       + "--set delegateName=helm-delegate "
>       + "--set accountId=${account_id} "
> ```

consider moving these in resource files

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java` line 802 at r3](https://reviewable.io/reviews/harness/harness-core/41852#-NKsx4oSAxyfwvWzkFYg:-NKsx4oSAxyfwvWzkFYh:b-nivoqn) ([raw file](https://github.com/harness/harness-core/blob/259324659223971a115f67c146a0e6c2205722ce/400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java#L802)):*
> ```Java
>   @Path("installation-command")
>   @Timed
>   //@AuthRule(permissionType = LOGGED_IN)
> ```

it can not be publicApi

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 8 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41852)* status: 0 of 1 approvals obtained.

**Review by xingchi-jin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41852)* status: 1 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/41852#-NKswjSGCxpNHNYYoNow:-NKsyba-17PU9AbLCUL1:b-z1i2kt) ([raw file](https://github.com/harness/harness-core/blob/259324659223971a115f67c146a0e6c2205722ce/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java#L32)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

every line should come in new line in the API response 
</blockquote></details>

I thought UI will anyway re-format the command. let me talk with Swaraj on what kind of string he wants. I will provide according to that. 
___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/41852#-NKswvj_3Iza2KGI-vwX:-NKt-BgM8VWvhlevWMgh:bpj9bsa) ([raw file](https://github.com/harness/harness-core/blob/259324659223971a115f67c146a0e6c2205722ce/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java#L43)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

consider moving these in resource files
</blockquote></details>

I have been thinking about this. The reason is, whenever we need to change a command, we will need a new manager( or DMS) release. There is no difference compare to putting it in resource file. Putting in file adds the complexity of file IO unnecessarily. So I don't see the need to do it and preferring sticking to the simple implementation.
Let me know for any thoughts.
___
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java` line 802 at r3](https://reviewable.io/reviews/harness/harness-core/41852#-NKsx4oSAxyfwvWzkFYg:-NKuElq1EDv6KfUQlsk4:b2ie42x) ([raw file](https://github.com/harness/harness-core/blob/259324659223971a115f67c146a0e6c2205722ce/400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java#L802)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

it can not be publicApi
</blockquote></details>

my bad, debug only.  fixed

**Review by AnupamIO — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 2 of 8 files at r2, 5 of 6 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41852)* status: 3. unresolved discussions. 

___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java` line 41 at r4](https://reviewable.io/reviews/harness/harness-core/41852#-NKvYnCI02OFUFh_swce:-NKvYnCI02OFUFh_swcf:bc1lqyw) ([raw file](https://github.com/harness/harness-core/blob/609444bf14f2d7237c73a4188e5bda2f0de5a0ed/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java#L41)):*
> ```Java
>   private static final String HELM_COMMAND =
>       "helm upgrade -i helm-delegate --namespace harness-delegate-ng --create-namespace "
>       + "harness/harness-delegate-ng "
> ```

minor: harness/harness-delegate-ng: this assumes that helm repo is saved with name harness. In current delegate install wizard we have added command to add repo as harness-ng. Repo name was changed because we changed the GCS bucket. Probably we can check and suggest same repo name everywhere: in install command, in UI, in docs.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41852)* status: :shipit: complete! ✓

**Comment by xingchi-jin** [comment]
trigger ti1

**Comment by xingchi-jin** [comment]
trigger ti3

**Comment by xingchi-jin** [comment]
trigger ti1

**Comment by xingchi-jin** [comment]
trigger ti1

**Comment by xingchi-jin** [comment]
trigger ti3

**Comment by xingchi-jin** [comment]
trigger codeformat

**Comment by xingchi-jin** [comment]
trigger ti0

**Comment by xingchi-jin** [comment]
trigger ti1

**Comment by xingchi-jin** [comment]
trigger checkstylecodeformat

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r7, 2 of 2 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41852)* status: :shipit: complete! ✓

**Review by AnupamIO — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r7, 2 of 2 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41852)* status: :shipit: complete! ✓

**Pull request merged**
