### PR TITLE
[feat]: [CDS-49001]: Added JenkinsParameterFieldType. Changes to migrator added

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41928)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/jenkins/jenkinsstep/JenkinsParameterField.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/41928#-NJvPsPACvV5byXDR_ki:-NJvPsPACvV5byXDR_kj:b-rltaqn) ([raw file](https://github.com/harness/harness-core/blob/519ebbf7b7125231da0ad0cc48bf8b167b78cedf/125-cd-nextgen/src/main/java/io/harness/cdng/jenkins/jenkinsstep/JenkinsParameterField.java#L44)):*
> ```Java
>   @ApiModelProperty(required = true, dataType = SwaggerConstants.JENKINS_PARAMETER_FIELD_TYPE_ENUM_CLASSPATH)
>   @YamlSchemaTypes(runtime)
>   ParameterField<JenkinsParameterFieldType> type;
> ```

existing JenkinsParameterField does not have this type field and we have marked this non null here. Will it not break existing setups ?

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/jenkins/jenkinsstep/JenkinsParameterField.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/41928#-NJvPsPACvV5byXDR_ki:-NJy2NiP8Ko-4VBSLg3c:b-mkmmjp) ([raw file](https://github.com/harness/harness-core/blob/519ebbf7b7125231da0ad0cc48bf8b167b78cedf/125-cd-nextgen/src/main/java/io/harness/cdng/jenkins/jenkinsstep/JenkinsParameterField.java#L44)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

existing JenkinsParameterField does not have this type field and we have marked this non null here. Will it not break existing setups ?
</blockquote></details>

Existing objects do have type field. It was just never added to the Spec. We can create without selecting type in UI. If it seems risky, we can remove NotNull for now.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41928)* status: 6 file(s) to review. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41928)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by manjunatha-etagi — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41928)* status: :shipit: complete! ✓

**Comment by arvind-choudhary-h** [comment]
trigger ft1

**Comment by arvind-choudhary-h** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41928)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
