### PR TITLE
fix: [DEL-3523]: Keep accountSecret and delegateToken in start up scripts for containerized delegates

### PR DESCRIPTION
**Pull request by gaurav-jain1**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31427)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31427)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[260-delegate/container/scripts/start.sh, line 217 at r1](https://reviewable.io/reviews/harness/harness-core/31427#-MyCa2isDOgTm-EO18_F:-MyCa2itCckKJJegMR1v:b-wxcz7z) ([raw file](https://github.com/harness/harness-core/blob/561dc64b72cb90c43e0f0d329ec38b8f83c4e6f1/260-delegate/container/scripts/start.sh#L217)):*
> ```Shell
>   echo "accountSecret: $ACCOUNT_SECRET" >> config-watcher.yml
> fi
> if ! `grep delegateToken config-watcher.yml > /dev/null`; then
> ```

I think you probably need to do a similar thing in delegate.sh and delegate.sh.ftl to write to config-delegate.yml
___
*[dockerization/delegate/scripts/start.sh, line 243 at r1](https://reviewable.io/reviews/harness/harness-core/31427#-MyCaAqg3ii3aJd9qpW5:-MyCaAqg3ii3aJd9qpW6:b-i8r9pk) ([raw file](https://github.com/harness/harness-core/blob/561dc64b72cb90c43e0f0d329ec38b8f83c4e6f1/dockerization/delegate/scripts/start.sh#L243)):*
> ```Shell
>   echo "accountId: $ACCOUNT_ID" > config-delegate.yml
>   if [ ! -e $ACCOUNT_SECRET ]; then
>     echo "delegateToken: $ACCOUNT_SECRET" >> config-delegate.yml
> ```

Was this intentional (to populate `delegateToken` variable and not `accountSecret`). I think it probably doesn't matter, but just from the consistency standpoint.

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31427)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[260-delegate/container/scripts/start.sh, line 217 at r1](https://reviewable.io/reviews/harness/harness-core/31427#-MyCa2isDOgTm-EO18_F:-MyH1oD33siCTL6fCf3W:be0n09m) ([raw file](https://github.com/harness/harness-core/blob/561dc64b72cb90c43e0f0d329ec38b8f83c4e6f1/260-delegate/container/scripts/start.sh#L217)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I think you probably need to do a similar thing in delegate.sh and delegate.sh.ftl to write to config-delegate.yml
</blockquote></details>

Not really, since watcher download new delegate.sh before starting delegate, so they'll be having changes anyway once we rename the variable in our yaml file. Delegate.sh will gets changed with this changeset:
https://github.com/harness/harness-core/pull/31003
___
*[dockerization/delegate/scripts/start.sh, line 243 at r1](https://reviewable.io/reviews/harness/harness-core/31427#-MyCaAqg3ii3aJd9qpW5:-MyH2DjJ7jGaTzUx9-Zu:b-nig2np) ([raw file](https://github.com/harness/harness-core/blob/561dc64b72cb90c43e0f0d329ec38b8f83c4e6f1/dockerization/delegate/scripts/start.sh#L243)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Was this intentional (to populate `delegateToken` variable and not `accountSecret`). I think it probably doesn't matter, but just from the consistency standpoint. 
</blockquote></details>

Actually doesn't matter, as these variables will be overwritten by delegate.sh anyway. I wanted to avoid 'accountSecret' keyword altogether, in order to avoid any panic with customers.

**Review by mdmilic — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31427#-:-MyHWAQX7dlQNWeWV9RZ:bnfp4nl)* status: :shipit: complete! ✓

**Review by bharatgoelharness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31427)* status: :shipit: complete! ✓

**Pull request merged**
