### PR TITLE
feat: [PIE-3591]: Matrix support for steps and bug fixes

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34363)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 166 at r5](https://reviewable.io/reviews/harness/harness-core/34363#-N4gUx4QC1_tR3IPxoW3:-N4gUx4QC1_tR3IPxoW4:b-ygd1n4) ([raw file](https://github.com/harness/harness-core/blob/576bddacadc4d10d8e0bf2c35e70c81d66743030/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L166)):*
> ```Java
>     planCreators.add(new CommandStepPlanCreator());
>     planCreators.add(new SpecNodePlanCreator());
>     planCreators.add(new StrategyConfigPlanCreator());
> ```

We need to add the strategy plan creator in cd because it will be used during plan creation of strategy node.

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 144 at r5](https://reviewable.io/reviews/harness/harness-core/34363#-N4gV6I-8xanhqwHcGYh:-N4gV6I-8xanhqwHcGYi:b-24tl13) ([raw file](https://github.com/harness/harness-core/blob/576bddacadc4d10d8e0bf2c35e70c81d66743030/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L144)):*
> ```Java
>     stageParameters.specConfig(getSpecParameters(specField.getNode().getUuid(), ctx, stageNode));
>     return PlanNode.builder()
>         .uuid(StageStrategyUtils.getSwappedPlanNodeId(ctx, stageNode))
> ```

We are making 3 changes in this class:
* Swapping the node of strategy and the stage node
* Adding strategy as a dependency if present

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSStepPlanCreatorV2.java` line 110 at r6](https://reviewable.io/reviews/harness/harness-core/34363#-N4gVMtJ39VLD6c3yKT2:-N4gVMtJ39VLD6c3yKT3:ba9tk7j) ([raw file](https://github.com/harness/harness-core/blob/2baa6492be738bfbafaacc77cc19461f8d66c4cf/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSStepPlanCreatorV2.java#L110)):*
> ```Java
> 
>     List<AdviserObtainment> adviserObtainmentFromMetaData = getAdviserObtainmentFromMetaData(ctx.getCurrentField());
>     Map<String, YamlField> dependenciesNodeMap = new HashMap<>();
> ```

We are making 3 changes over here:
* Swapping the nodeIds of the strategy and step node
* Removing nextstep adviser from here and adding it on strategy node if strategy field is present on step.
* Adding strategy as a dependency if step has strategy field

**Comment by sahilhindwani-harness** [comment]
*[`320-ci-execution/src/main/java/io/harness/ci/plan/creator/step/CIPMSStepPlanCreatorV2.java` line 101 at r6](https://reviewable.io/reviews/harness/harness-core/34363#-N4gVdy75M7-H4s9ZMaT:-N4gVdy86R-xcS-0MrIC:b2eeu7u) ([raw file](https://github.com/harness/harness-core/blob/2baa6492be738bfbafaacc77cc19461f8d66c4cf/320-ci-execution/src/main/java/io/harness/ci/plan/creator/step/CIPMSStepPlanCreatorV2.java#L101)):*
> ```Java
> 
>     List<AdviserObtainment> adviserObtainmentFromMetaData = getAdviserObtainmentFromMetaData(ctx.getCurrentField());
>     Map<String, YamlField> dependenciesNodeMap = new HashMap<>();
> ```

Same changes as CDPMSStepPlanCreatorV2

**Comment by sahilhindwani-harness** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/expressions/PMSExpressionEvaluator.java` line 74 at r6](https://reviewable.io/reviews/harness/harness-core/34363#-N4gVnZQ7cJpKoc5fJve:-N4gVnZR3ZIAuXkfTfrM:b5cyfk0) ([raw file](https://github.com/harness/harness-core/blob/2baa6492be738bfbafaacc77cc19461f8d66c4cf/800-pipeline-service/src/main/java/io/harness/pms/expressions/PMSExpressionEvaluator.java#L74)):*
> ```Java
>     addToContext("executionInput", new ExecutionInputExpressionFunctor(executionInputService, ambiance));
> 
>     addToContext("strategy", new StrategyFunctor(ambiance));
> ```

Only renaming of functor

**Comment by sahilhindwani-harness** [comment]
*[`860-orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/PMSStepPlanCreatorV2.java` line 97 at r6](https://reviewable.io/reviews/harness/harness-core/34363#-N4gVu5x4fMzmDrElI9u:-N4gVu5x4fMzmDrElI9v:b2eeu7u) ([raw file](https://github.com/harness/harness-core/blob/2baa6492be738bfbafaacc77cc19461f8d66c4cf/860-orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/PMSStepPlanCreatorV2.java#L97)):*
> ```Java
> 
>     List<AdviserObtainment> adviserObtainmentFromMetaData = getAdviserObtainmentFromMetaData(ctx.getCurrentField());
>     Map<String, YamlField> dependenciesNodeMap = new HashMap<>();
> ```

Same changes as CDPMSStepPlanCreatorV2

**Comment by sahilhindwani-harness** [comment]
*[`860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java` line 52 at r6](https://reviewable.io/reviews/harness/harness-core/34363#-N4gVydlDyL6R8ICMcao:-N4gVydlDyL6R8ICMcap:bmd2i6n) ([raw file](https://github.com/harness/harness-core/blob/2baa6492be738bfbafaacc77cc19461f8d66c4cf/860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java#L52)):*
> ```Java
>       update.set(PipelineExecutionSummaryEntity.PlanExecutionSummaryKeys.layoutNodeMap + "." + nodeExecution.getNodeId()
>               + ".moduleInfo.stepParameters",
>           nodeExecution.getResolvedStepParameters());
> ```

Recaster was not required.

**Comment by sahilhindwani-harness** [comment]
*[`860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 146 at r6](https://reviewable.io/reviews/harness/harness-core/34363#-N4gW8us9023yOEa1PVa:-N4gW8us9023yOEa1PVb:b6g381t) ([raw file](https://github.com/harness/harness-core/blob/2baa6492be738bfbafaacc77cc19461f8d66c4cf/860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L146)):*
> ```Java
> 
> 
>   private void modifyGraphLayoutNode(GraphLayoutNodeDTO graphLayoutNodeDTO, NodeExecution nodeExecution) {
> ```

This function modified the identifier and name of the dummy node we are copying.

**Comment by sahilhindwani-harness** [comment]
*[`870-orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyFunctor.java` line 42 at r6](https://reviewable.io/reviews/harness/harness-core/34363#-N4gWK5V7NFXhTPQttgk:-N4gWK5V7NFXhTPQttgl:b-98mqda) ([raw file](https://github.com/harness/harness-core/blob/2baa6492be738bfbafaacc77cc19461f8d66c4cf/870-orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyFunctor.java#L42)):*
> ```Java
>       strategyObjectMap.put("totalIteration", level.getStrategyMetadata().getTotalIterations());
>     }
>     strategyObjectMap.put(MATRIX, matrixValuesMap);
> ```

Now we are supporting more expressions like <+strategy.currentIteration> and <strategy.totalIteration>

**Comment by sahilhindwani-harness** [comment]
*[`870-orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 67 at r6](https://reviewable.io/reviews/harness/harness-core/34363#-N4gWVGf0bTR3fvgq1KB:-N4gWVGf0bTR3fvgq1KC:bcgthgj) ([raw file](https://github.com/harness/harness-core/blob/2baa6492be738bfbafaacc77cc19461f8d66c4cf/870-orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L67)):*
> ```Java
>       // If maxConcurrency is not defined then we will run all children in parallel therefore maxConcurrency should be
>       // number of children
>       if (maxConcurrency == 0) {
> ```

We are now saving the concurrentChildInstance in db first and then starting the children.
Why? because earlier there could be a case where the child finishes early and we don't have the concurrentChildInstance updated for DB.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 18 of 30 files at r1, 1 of 1 files at r5, 8 of 9 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34363)* status: 31 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java` line 595 at r6](https://reviewable.io/reviews/harness/harness-core/34363#-N4gVjAx1YZSC4yJSOjn:-N5-DfFx-aLl36NYALym:b868a9n) ([raw file](https://github.com/harness/harness-core/blob/2baa6492be738bfbafaacc77cc19461f8d66c4cf/800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java#L595)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: remove 1
</blockquote></details>

as mentioned remove 1 extra 
___
*[`860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 146 at r6](https://reviewable.io/reviews/harness/harness-core/34363#-N4gW8us9023yOEa1PVa:-N5-Dy1S3P0erTqefcUi:bbgjpb5) ([raw file](https://github.com/harness/harness-core/blob/2baa6492be738bfbafaacc77cc19461f8d66c4cf/860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L146)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

This function modified the identifier and name of the dummy node we are copying.
</blockquote></details>

can you please add the same description as comment
___
*[`870-orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 67 at r6](https://reviewable.io/reviews/harness/harness-core/34363#-N4gWVGf0bTR3fvgq1KB:-N5-HoO-D1nmH786S8mC:boaxyu1) ([raw file](https://github.com/harness/harness-core/blob/2baa6492be738bfbafaacc77cc19461f8d66c4cf/870-orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L67)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We are now saving the concurrentChildInstance in db first and then starting the children.
Why? because earlier there could be a case where the child finishes early and we don't have the concurrentChildInstance updated for DB.
</blockquote></details>

As discussed please add comment that we are doing nodeExecution first before starting as if started it could complete first before making nodeExecution changes thus race condition.
___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/AbstractStepPlanCreator.java` line 73 at r7](https://reviewable.io/reviews/harness/harness-core/34363#-N5-IXex2lUuTlh5LflB:-N5-IXex2lUuTlh5LflC:b94awdt) ([raw file](https://github.com/harness/harness-core/blob/bef181629bd3533002287dfa04ad573fd984e2b6/878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/AbstractStepPlanCreator.java#L73)):*
> ```Java
>                   .build())));
>     }
>   }
> ```

stage and step code is same, we should extract it out in a helper and use it



_Code quote:_
```Java
  protected void addStrategyFieldDependencyIfPresent(PlanCreationContext ctx, AbstractStepNode field,
      Map<String, YamlField> dependenciesNodeMap, Map<String, ByteString> metadataMap) {
    YamlField strategyField = ctx.getCurrentField().getNode().getField(YAMLFieldNameConstants.STRATEGY);
    if (strategyField != null) {
      dependenciesNodeMap.put(field.getUuid(), strategyField);
      // This is mandatory because it is the parent's responsibility to pass the nodeId and the childNodeId to the
      // strategy node
      metadataMap.put(StrategyConstants.STRATEGY_METADATA + strategyField.getNode().getUuid(),
          ByteString.copyFrom(kryoSerializer.asDeflatedBytes(
              StrategyMetadata.builder()
                  .strategyNodeId(field.getUuid())
                  .adviserObtainments(getAdviserObtainmentFromMetaDataForStrategy(ctx.getCurrentField()))
                  .childNodeId(strategyField.getNode().getUuid())
                  .strategyNodeIdentifier(field.getIdentifier())
                  .strategyNodeName(field.getName())
                  .build())));
    }
  }
```
___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/AbstractStepPlanCreator.java` line 77 at r7](https://reviewable.io/reviews/harness/harness-core/34363#-N5-IhxJ9_q5oupOv9hj:-N5-IhxJ9_q5oupOv9hk:b-o35phm) ([raw file](https://github.com/harness/harness-core/blob/bef181629bd3533002287dfa04ad573fd984e2b6/878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/AbstractStepPlanCreator.java#L77)):*
> ```Java
>   @Override public abstract PlanCreationResponse createPlanForField(PlanCreationContext ctx, T stepElement);
> 
>   private List<AdviserObtainment> getAdviserObtainmentFromMetaDataForStrategy(YamlField currentField) {
> ```

append For Step in method name, and put this in a helper, as don't want to fill this class with such details



_Code quote:_
```Java
getAdviserObtainmentFromMetaDataForStrategy
```
___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/AbstractStepPlanCreator.java` line 100 at r7](https://reviewable.io/reviews/harness/harness-core/34363#-N5-J5AF7bwitktSOVmq:-N5-J5AF7bwitktSOVmr:bhvo7em) ([raw file](https://github.com/harness/harness-core/blob/bef181629bd3533002287dfa04ad573fd984e2b6/878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/AbstractStepPlanCreator.java#L100)):*
> ```Java
>                       NextStepAdviserParameters.builder().nextNodeId(siblingField.getNode().getUuid()).build())))
>                   .build();
>         }
> ```

If strategy node here which is on step, then siblings should be step or stepgroup only right? why stage will be sibling here?



_Code quote:_
```Java
        if (parallelNodeInStage != null) {
          adviserObtainment =
              AdviserObtainment.newBuilder()
                  .setType(AdviserType.newBuilder().setType(OrchestrationAdviserTypes.NEXT_STEP.name()).build())
                  .setParameters(ByteString.copyFrom(kryoSerializer.asBytes(
                      NextStepAdviserParameters.builder().nextNodeId(siblingField.getNode().getUuid()).build())))
                  .build();
        } else {
          adviserObtainment =
              AdviserObtainment.newBuilder()
                  .setType(AdviserType.newBuilder().setType(OrchestrationAdviserTypes.NEXT_STAGE.name()).build())
                  .setParameters(ByteString.copyFrom(kryoSerializer.asBytes(
                      NextStepAdviserParameters.builder().nextNodeId(siblingField.getNode().getUuid()).build())))
                  .build();
        }
```
___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StrategyConfigPlanCreator.java` line 70 at r7](https://reviewable.io/reviews/harness/harness-core/34363#-N5-JOE03cQIHoC92_ha:-N5-JOE03cQIHoC92_hb:bahvbxb) ([raw file](https://github.com/harness/harness-core/blob/bef181629bd3533002287dfa04ad573fd984e2b6/878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StrategyConfigPlanCreator.java#L70)):*
> ```Java
>     }
>     StrategyType strategyType = StrategyType.FOR;
>     if (ctx.getCurrentField().getNode().getField("matrix") != null) {
> ```

use constants defined in lower module rather than hard coded string, same for parallelism



_Code quote:_
```Java
"matrix"
```

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StrategyConfigPlanCreator.java` line 70 at r7](https://reviewable.io/reviews/harness/harness-core/34363#-N5-JOE03cQIHoC92_ha:-N53eoGwBDDfn6o6cIIq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bef181629bd3533002287dfa04ad573fd984e2b6/878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StrategyConfigPlanCreator.java#L70)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use constants defined in lower module rather than hard coded string, same for parallelism
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/AbstractStepPlanCreator.java` line 73 at r7](https://reviewable.io/reviews/harness/harness-core/34363#-N5-IXex2lUuTlh5LflB:-N53ethjCGIbFPsOcOkm:bjjd7ou) ([raw file](https://github.com/harness/harness-core/blob/bef181629bd3533002287dfa04ad573fd984e2b6/878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/AbstractStepPlanCreator.java#L73)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

stage and step code is same, we should extract it out in a helper and use it
</blockquote></details>

Will refactor in upcoming PR.

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/AbstractStepPlanCreator.java` line 77 at r7](https://reviewable.io/reviews/harness/harness-core/34363#-N5-IhxJ9_q5oupOv9hj:-N53ew0z59-9QHtMp5jC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bef181629bd3533002287dfa04ad573fd984e2b6/878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/AbstractStepPlanCreator.java#L77)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

append For Step in method name, and put this in a helper, as don't want to fill this class with such details
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/AbstractStepPlanCreator.java` line 100 at r7](https://reviewable.io/reviews/harness/harness-core/34363#-N5-J5AF7bwitktSOVmq:-N53ex-f3eyu8wK_SAsl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bef181629bd3533002287dfa04ad573fd984e2b6/878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/AbstractStepPlanCreator.java#L100)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

If strategy node here which is on step, then siblings should be step or stepgroup only right? why stage will be sibling here?
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34363)* status: 31 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 146 at r6](https://reviewable.io/reviews/harness/harness-core/34363#-N4gW8us9023yOEa1PVa:-N53jX8X4ZTJJPA9Vngm:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2baa6492be738bfbafaacc77cc19461f8d66c4cf/860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L146)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you please add the same description as comment
</blockquote></details>

done
___
*[`870-orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 67 at r6](https://reviewable.io/reviews/harness/harness-core/34363#-N4gWVGf0bTR3fvgq1KB:-N53j_mO9RPQ03DkBlVZ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2baa6492be738bfbafaacc77cc19461f8d66c4cf/870-orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L67)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

As discussed please add comment that we are doing nodeExecution first before starting as if started it could complete first before making nodeExecution changes thus race condition.
</blockquote></details>

done
___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/AbstractStepPlanCreator.java` line 73 at r7](https://reviewable.io/reviews/harness/harness-core/34363#-N5-IXex2lUuTlh5LflB:-N53jd2j-MrK0CxXK1Yv:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bef181629bd3533002287dfa04ad573fd984e2b6/878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/AbstractStepPlanCreator.java#L73)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Will refactor in upcoming PR.
</blockquote></details>

done
___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StageStrategyUtils.java` line 165 at r8](https://reviewable.io/reviews/harness/harness-core/34363#-N53jof32RmPRFJEQPrZ:-N53jof32RmPRFJEQPr_:b-3np3uc) ([raw file](https://github.com/harness/harness-core/blob/786eb587ed555d4478df8b5aeb1ea99862571a55/878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StageStrategyUtils.java#L165)):*
> ```Java
>                                   NextStepAdviserParameters.builder().nextNodeId(siblingField.getNode().getUuid()).build())))
>                           .build();
>         adviserObtainments.add(adviserObtainment);
> ```

dont we need to check if parallel or matrix then no adviser is there?



_Code quote:_
```Java
      if (siblingField != null && siblingField.getNode().getUuid() != null) {
        AdviserObtainment adviserObtainment =
                  AdviserObtainment.newBuilder()
                          .setType(AdviserType.newBuilder().setType(OrchestrationAdviserTypes.NEXT_STEP.name()).build())
                          .setParameters(ByteString.copyFrom(kryoSerializer.asBytes(
                                  NextStepAdviserParameters.builder().nextNodeId(siblingField.getNode().getUuid()).build())))
                          .build();
        adviserObtainments.add(adviserObtainment);
```

**Review by archit-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34363)* status: 31 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34363)* status: 32 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 12 of 30 files at r1, 1 of 1 files at r5, 7 of 9 files at r6, 3 of 4 files at r7, 3 of 7 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34363)* status: :shipit: complete! ✓

**Pull request merged**
