### PR TITLE
feat: [PIE-8420]: Added support for fetching only file content in SCM java client

### PR DESCRIPTION
**Pull request by mohitg0795**
## Describe your changes
Exposing new endpoint in SCM java client to fetch only file content from GIT for given filepath and also to process batch file requests for the same.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44432)

### CODE REVIEW

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 1 of 7 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44432)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44432)* status: :shipit: complete! ✓

**Review by adivishy1 — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 1 of 7 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44432)* status: 1. unresolved discussions. 

___
*[`952-scm-java-client/src/main/java/io/harness/beans/response/GitFileContentBatchResponse.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/44432#-NPMfZNw9WkrYqWnTlzC:-NPMg1rX6uUZ5AkrqMtI:b-ac2i4g) ([raw file](https://github.com/harness/harness-core/blob/6209d9fd9bbe36abb7b8d0a0db8e8c81d1a385f4/952-scm-java-client/src/main/java/io/harness/beans/response/GitFileContentBatchResponse.java#L18)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: is it PL team?
</blockquote></details>

almost the same habit, by default in the head its still PL :joy:

**Review by sourabh-awashti — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 1 of 7 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44432)* status: :shipit: complete! ✓

**Pull request merged**
