### PR TITLE
feat: [PIE-8171]: use pipeline_execution_summary table of timescale to fetch health and executions of pipeline execution summary

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Issue:** Currently, for fetching pipeline health and execution info, we are querying data from cd and ci tables of timescale, but these tables don't collect info about the pipelines having only custom stages.

**Changes:** Now, we are using pipeline_execution_summary to query this data and this table contains info about the pipeline execution summary of every pipeline regardless of module-info. 

**Impact:** Now, in the pipeline health and execution page, data will be displayed for all the executions of the pipeline even if it doesn't belong to CI or CD modules.

**Testing:** Tested the behavior locally, I have this pipeline 'chaining' which only has a pipeline stage and its child pipeline only has a custom stage. And yet, on pipeline health and execution info, I can see correct information about the execution history of this pipeline.

Screenshot 2023-02-22 at 11 26 24 AM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44183)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44183)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java` line 175 at r3](https://reviewable.io/reviews/harness/harness-core/44183#-NP2MVOv0IFKEOccebol:-NP2MVOv0IFKEOccebom:b-g7j5x9) ([raw file](https://github.com/harness/harness-core/blob/94bbe0b9096c0b117dcbfb1769e96176a2fd01c5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java#L175)):*
> ```Java
>         }
>       } else {
>         List<Condition> conditions =
> ```

can we put if and else method blocks?

**Comment by shalini-agr** [comment]
trigger ti4

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44183)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java` line 175 at r3](https://reviewable.io/reviews/harness/harness-core/44183#-NP2MVOv0IFKEOccebol:-NP2rSkR3sUHCvKO9AmT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/94bbe0b9096c0b117dcbfb1769e96176a2fd01c5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java#L175)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we put if and else method blocks?
</blockquote></details>

Done.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 7 of 9 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44183)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 7 of 9 files at r3, 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44183)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 7 of 9 files at r3, 1 of 1 files at r4, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44183)* status: :shipit: complete! ✓

**Pull request merged**
