### PR TITLE
fix: [DEL-5872]: Expose more Delegate metrics 

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
- Add metrics to track task completed and task failed. Track delegate resource like memory and cpu goes above max threshold
- Ability to choose dynamic handling of request from manager to perform delegate task, enabled through FF 
- Ability to configure max threshold to show metrics and reject task. By default it's 90

Test
- Metrics verified for task completes, task failed, task rejected, resource above threshold, delegate connected/disconnected
- Test with configurable threshold value 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46718)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1930 at r3](https://reviewable.io/reviews/harness/harness-core/46718#-NU3E_1A8MCsYXgXULU9:-NU3E_1A8MCsYXgXULUA:bipwi6g) ([raw file](https://github.com/harness/harness-core/blob/69bf483127113d438b53e31fcd30859d26c7fa5c/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1930)):*
> ```Java
>     double loadAvg = ManagementFactory.getOperatingSystemMXBean().getSystemLoadAverage();
>     int cores = ManagementFactory.getOperatingSystemMXBean().getAvailableProcessors();
>     return (loadAvg / cores) * 100;
> ```

how did we verify that this is the right way of doing it?

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 759 at r3](https://reviewable.io/reviews/harness/harness-core/46718#-NU3EgAq6KOkMvuXdwmX:-NU3EgAr5DO9KS5SFPNT:b-qd8nhl) ([raw file](https://github.com/harness/harness-core/blob/69bf483127113d438b53e31fcd30859d26c7fa5c/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L759)):*
> ```Java
> 
>     if (getCPULoadAverage() > 90) {
>       log.warn("CPU Average load is above 90%");
> ```

we should log what was the usage instead just saying it was above 90%

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 761 at r3](https://reviewable.io/reviews/harness/harness-core/46718#-NU3ExmdCHEEAJQrMAfx:-NU3ExmdCHEEAJQrMAfy:b-18luek) ([raw file](https://github.com/harness/harness-core/blob/69bf483127113d438b53e31fcd30859d26c7fa5c/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L761)):*
> ```Java
>       log.warn("CPU Average load is above 90%");
>       rejectRequest.compareAndSet(false, true);
>       metricRegistry.recordGaugeInc(DELEGATE_USAGE_ABOVE_THRESHOLD, new String[] {DELEGATE_NAME});
> ```

we should not publish two metrics. instead just one, something like "RESOURCE_CONSUMPTION_ABOVE_THRESHOLD" which captures memory and cpu consumed more than 80%. Customers can autoscale based on it. Also we should take this value from environment variable so if someone wants to override, they can from delegate yaml. 

Also this entire tracking should only happen for immutable delegate

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46718)* status: 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 759 at r3](https://reviewable.io/reviews/harness/harness-core/46718#-NU3EgAq6KOkMvuXdwmX:-NU3QZBf6914quZOMGAU:b-n0ud77) ([raw file](https://github.com/harness/harness-core/blob/69bf483127113d438b53e31fcd30859d26c7fa5c/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L759)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should log what was the usage instead just saying it was above 90%
</blockquote></details>

updated, we also log the same as part of current performance

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 761 at r3](https://reviewable.io/reviews/harness/harness-core/46718#-NU3ExmdCHEEAJQrMAfx:-NU3QgU-B5cXWtGZSlJ_:bpfenem) ([raw file](https://github.com/harness/harness-core/blob/69bf483127113d438b53e31fcd30859d26c7fa5c/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L761)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should not publish two metrics. instead just one, something like "RESOURCE_CONSUMPTION_ABOVE_THRESHOLD" which captures memory and cpu consumed more than 80%. Customers can autoscale based on it. Also we should take this value from environment variable so if someone wants to override, they can from delegate yaml. 

Also this entire tracking should only happen for immutable delegate 
</blockquote></details>

consolidated to one metrics, RESOURCE_CONSUMPTION_ABOVE_THRESHOLD

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 761 at r3](https://reviewable.io/reviews/harness/harness-core/46718#-NU3ExmdCHEEAJQrMAfx:-NU3QlH_CFxIXd0wzSMj:b-rcjqkr) ([raw file](https://github.com/harness/harness-core/blob/69bf483127113d438b53e31fcd30859d26c7fa5c/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L761)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

consolidated to one metrics, RESOURCE_CONSUMPTION_ABOVE_THRESHOLD
</blockquote></details>

this is only for immutable delegate

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 761 at r3](https://reviewable.io/reviews/harness/harness-core/46718#-NU3ExmdCHEEAJQrMAfx:-NU3QrBw2c3kg9BIa6hh:b4r2402) ([raw file](https://github.com/harness/harness-core/blob/69bf483127113d438b53e31fcd30859d26c7fa5c/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L761)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

this is only for immutable delegate
</blockquote></details>

you want to track this as part of this ticket?
"we should take this value from environment variable so if someone wants to override, they can from delegate yaml."

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 761 at r3](https://reviewable.io/reviews/harness/harness-core/46718#-NU3ExmdCHEEAJQrMAfx:-NU8AK_y2fNxPxe6JDy0:b-bobasd) ([raw file](https://github.com/harness/harness-core/blob/69bf483127113d438b53e31fcd30859d26c7fa5c/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L761)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

you want to track this as part of this ticket?
"we should take this value from environment variable so if someone wants to override, they can from delegate yaml."
</blockquote></details>

yes, should be straight, just read the value from env variable

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46718)* status: 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
Above Resource CPU usage and during memory spike (io_harness_custom_metric_delegate_resource_consumption_above_threshold)
image

**Comment by jennyjames21** [comment]
Task Completed metrics 
image

**Comment by jennyjames21** [comment]
Task failed metrics 
image

**Comment by jennyjames21** [comment]
Delegate connected/disconnected
image

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 761 at r3](https://reviewable.io/reviews/harness/harness-core/46718#-NU3ExmdCHEEAJQrMAfx:-NUDYwA4BM4XpqHLFXTC:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/69bf483127113d438b53e31fcd30859d26c7fa5c/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L761)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

yes, should be straight, just read the value from env variable 
</blockquote></details>

done

**Review by jennyjames21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46718)* status: 11 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1930 at r3](https://reviewable.io/reviews/harness/harness-core/46718#-NU3E_1A8MCsYXgXULU9:-NUDYpQOAteDkIDdi2MY:b-oge3gc) ([raw file](https://github.com/harness/harness-core/blob/69bf483127113d438b53e31fcd30859d26c7fa5c/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1930)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

how did we verify that this is the right way of doing it?
</blockquote></details>

current performance display same as well

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 318 at r11](https://reviewable.io/reviews/harness/harness-core/46718#-NUKQP2MADfCPooJbWBl:-NUKQP2N0FOow-dYpVip:bd8d7u9) ([raw file](https://github.com/harness/harness-core/blob/c7cd90d93f8fac7021b1b9e149d54bdaf2658d92/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L318)):*
> ```Java
>       ? (Integer.parseInt(System.getenv().get("DELEGATE_RESOURCE_THRESHOLD")))
>       : 90;
>   private final boolean dynamicRequestHandling = isNotBlank(System.getenv().get("DYNAMIC_REQUEST_HANDLING"))
> ```

why do we need this?

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 317 at r11](https://reviewable.io/reviews/harness/harness-core/46718#-NUKQRhi6BwJg28yTfPh:-NUKQRhi6BwJg28yTfPi:bfljst) ([raw file](https://github.com/harness/harness-core/blob/c7cd90d93f8fac7021b1b9e149d54bdaf2658d92/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L317)):*
> ```Java
>   private final double RESOURCE_USAGE_THRESHOLD = isNotBlank(System.getenv().get("DELEGATE_RESOURCE_THRESHOLD"))
>       ? (Integer.parseInt(System.getenv().get("DELEGATE_RESOURCE_THRESHOLD")))
>       : 90;
> ```

define a constant and lets make it 80

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 760 at r11](https://reviewable.io/reviews/harness/harness-core/46718#-NUKQjac9vsQ_ij-v3TV:-NUKQjac9vsQ_ij-v3TW:b-zej8sq) ([raw file](https://github.com/harness/harness-core/blob/c7cd90d93f8fac7021b1b9e149d54bdaf2658d92/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L760)):*
> ```Java
>       return;
>     }
>     log.info("Process info CurrentProcessRSSMB {} ThresholdProcessMB {} currentPodRSSMB {} ThresholdPodMemoryMB {}",
> ```

don't make it info, that will be too many logs

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2093 at r11](https://reviewable.io/reviews/harness/harness-core/46718#-NUKR73f7kHkrnMy1jxO:-NUKR73f7kHkrnMy1jxP:b7rfbwx) ([raw file](https://github.com/harness/harness-core/blob/c7cd90d93f8fac7021b1b9e149d54bdaf2658d92/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2093)):*
> ```Java
>         log.info("Validation {} for task", validated ? "succeeded" : "failed");
>         if (!validated) {
>           metricRegistry.recordGaugeInc(TASK_FAILED, new String[] {DELEGATE_NAME, delegateTaskEvent.getTaskType()});
> ```

we shouldn't be reporting for validation errors

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2760 at r11](https://reviewable.io/reviews/harness/harness-core/46718#-NUKRCuWEERcKMnvSeey:-NUKRCuWEERcKMnvSeez:bx6w5ur) ([raw file](https://github.com/harness/harness-core/blob/c7cd90d93f8fac7021b1b9e149d54bdaf2658d92/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2760)):*
> ```Java
>         if (response != null && response.code() >= 200 && response.code() <= 299) {
>           log.debug("Task {} type {},  response sent to manager", taskId, taskResponse.getTaskTypeName());
>           metricRegistry.recordGaugeInc(TASK_COMPLETED, new String[] {DELEGATE_NAME, taskResponse.getTaskTypeName()});
> ```

this should be counter,

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2777 at r11](https://reviewable.io/reviews/harness/harness-core/46718#-NUKRFunADRky17Vbrkg:-NUKRFuoE1rR96iwEUnw:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/c7cd90d93f8fac7021b1b9e149d54bdaf2658d92/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2777)):*
> ```Java
>     } catch (IOException e) {
>       log.error("Unable to send response to manager", e);
>       metricRegistry.recordGaugeInc(TASK_FAILED, new String[] {DELEGATE_NAME, taskResponse.getTaskTypeName()});
> ```

same here

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2093 at r11](https://reviewable.io/reviews/harness/harness-core/46718#-NUKR73f7kHkrnMy1jxO:-NUKRIiE3W7xF_cjvBMy:b-bva3uq) ([raw file](https://github.com/harness/harness-core/blob/c7cd90d93f8fac7021b1b9e149d54bdaf2658d92/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2093)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we shouldn't be reporting for validation errors
</blockquote></details>

also this should be counter

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2802 at r11](https://reviewable.io/reviews/harness/harness-core/46718#-NUKRM0A-DETFw4jMRlI:-NUKRM0BAPlPiYSKp9cS:b-jni27d) ([raw file](https://github.com/harness/harness-core/blob/c7cd90d93f8fac7021b1b9e149d54bdaf2658d92/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2802)):*
> ```Java
>             .response(ErrorNotifyResponseData.builder().errorMessage(ExceptionUtils.getMessage(exception)).build())
>             .build();
>     metricRegistry.recordGaugeInc(TASK_FAILED, new String[] {DELEGATE_NAME, taskResponse.getTaskTypeName()});
> ```

counter

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, 1 of 2 files at r8, 8 of 8 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46718)* status: 2. unresolved discussions. 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 317 at r11](https://reviewable.io/reviews/harness/harness-core/46718#-NUKQRhi6BwJg28yTfPh:-NUKkMey-72wOFpnrYJD:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c7cd90d93f8fac7021b1b9e149d54bdaf2658d92/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L317)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

define a constant and lets make it 80
</blockquote></details>

done

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 318 at r11](https://reviewable.io/reviews/harness/harness-core/46718#-NUKQP2MADfCPooJbWBl:-NUKkOlQ4CZ6AU4sPYSb:b1y4kuf) ([raw file](https://github.com/harness/harness-core/blob/c7cd90d93f8fac7021b1b9e149d54bdaf2658d92/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L318)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need this?
</blockquote></details>

This is FF value coming from manager, since we are not enabling for all customers this is needed

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 760 at r11](https://reviewable.io/reviews/harness/harness-core/46718#-NUKQjac9vsQ_ij-v3TV:-NUKkfTO7He7WSnIk5Ej:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c7cd90d93f8fac7021b1b9e149d54bdaf2658d92/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L760)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

don't make it info, that will be too many logs
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2093 at r11](https://reviewable.io/reviews/harness/harness-core/46718#-NUKR73f7kHkrnMy1jxO:-NUKkiOcCGpf4HpJlEEf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c7cd90d93f8fac7021b1b9e149d54bdaf2658d92/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2093)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

also this should be counter
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2760 at r11](https://reviewable.io/reviews/harness/harness-core/46718#-NUKRCuWEERcKMnvSeey:-NUKkjrc0x-PVtAr6yku:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c7cd90d93f8fac7021b1b9e149d54bdaf2658d92/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2760)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this should be counter, 
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2777 at r11](https://reviewable.io/reviews/harness/harness-core/46718#-NUKRFunADRky17Vbrkg:-NUKklNl64kT4wIQopN0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c7cd90d93f8fac7021b1b9e149d54bdaf2658d92/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2777)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

**Review by jennyjames21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46718)* status: 2 file(s) to review. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2802 at r11](https://reviewable.io/reviews/harness/harness-core/46718#-NUKRM0A-DETFw4jMRlI:-NUKkmxZ1_wJVFzfuCMk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c7cd90d93f8fac7021b1b9e149d54bdaf2658d92/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2802)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

counter
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
trigger checkstylecodeformat

**Comment by jennyjames21** [comment]
trigger utAll

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46718)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
trigger messagecheck

**Pull request merged**
