### PR TITLE
fix: [CDS-41913]: return exception if nexus artifact url is null

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36450)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36450)

**Comment by RishabhGupta34** [comment]
trigger messagecheck

**Comment by RishabhGupta34** [comment]
trigger messagecheck

**Comment by arvind-choudhary-h** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/pcf/PcfSetupState.java` line 489 at r1](https://reviewable.io/reviews/harness/harness-core/36450#-N9fGsSmEFGDuM-p2NJ3:-N9fGsSmEFGDuM-p2NJ4:b-7o3nsr) ([raw file](https://github.com/harness/harness-core/blob/a6cd4baab5826c8a5f1731d1ab4094c491d600b7/400-rest/src/main/java/software/wings/sm/states/pcf/PcfSetupState.java#L489)):*
> ```Java
>         return artifactStreamAttributes.getMetadata().get(URL);
>       default:
>         return artifactStreamAttributes.getMetadata().get(URL);
> ```

why `default:` is changed?



_Code quote:_
```Java
default:
```

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36450)* status: 0 of 1 approvals obtained.

**Comment by RishabhGupta34** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/pcf/PcfSetupState.java` line 489 at r1](https://reviewable.io/reviews/harness/harness-core/36450#-N9fGsSmEFGDuM-p2NJ3:-N9fJ-jOAs9RsNpqfsPG:b652t9z) ([raw file](https://github.com/harness/harness-core/blob/a6cd4baab5826c8a5f1731d1ab4094c491d600b7/400-rest/src/main/java/software/wings/sm/states/pcf/PcfSetupState.java#L489)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

why `default:` is changed?
</blockquote></details>

Previously default was this only, but there was a Nexus issue in which due to empty URL the workflow was failing, I added error handling on empty URL to the default case, but it started breaking the docker based artifacts. So I separated out the NEXUS case from the default one, previous PR: https://github.com/harness/harness-core/pull/36156

**Comment by arvind-choudhary-h** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/pcf/PcfSetupState.java` line 489 at r1](https://reviewable.io/reviews/harness/harness-core/36450#-N9fGsSmEFGDuM-p2NJ3:-N9fUUhq1973ex7S19Lu:bwe2bmo) ([raw file](https://github.com/harness/harness-core/blob/a6cd4baab5826c8a5f1731d1ab4094c491d600b7/400-rest/src/main/java/software/wings/sm/states/pcf/PcfSetupState.java#L489)):*
<details><summary><i>Previously, RishabhGupta34 (Rishabh Gupta) wrote…</i></summary><blockquote>

Previously default was this only, but there was a Nexus issue in which due to empty URL the workflow was failing, I added error handling on empty URL to the default case, but it started breaking the docker based artifacts. So I separated out the NEXUS case from the default one, previous PR: https://github.com/harness/harness-core/pull/36156
</blockquote></details>

So, now Nexus one will still fail, right?
Shall we take out the docker one too?

**Comment by RishabhGupta34** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/pcf/PcfSetupState.java` line 489 at r1](https://reviewable.io/reviews/harness/harness-core/36450#-N9fGsSmEFGDuM-p2NJ3:-N9fVpt04TlNJ6TbA7qm:b2a91rp) ([raw file](https://github.com/harness/harness-core/blob/a6cd4baab5826c8a5f1731d1ab4094c491d600b7/400-rest/src/main/java/software/wings/sm/states/pcf/PcfSetupState.java#L489)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

So, now Nexus one will still fail, right?
Shall we take out the docker one too?
</blockquote></details>

Yes, nexus one will fail, because of the error handling in separate NEXUS case, but docker won't. I saw the docker execution doesn't contain URL, so docker would go to the default case and won't fail

**Review by arvind-choudhary-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36450)* status: :shipit: complete! ✓

**Pull request merged**
