### PR TITLE
fix: [CCM-9753]: Reduce ttl and don't save recommendations if there are no savings

### PR DESCRIPTION
**Pull request by trunapushpa**
## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39910)

### CODE REVIEW

**Comment by trunapushpa** [comment]
trigger codeformat

**Review by divyanshuchaubisa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39910)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`490-ce-commons/src/main/java/io/harness/ccm/commons/constants/RecommendationConstants.java` line 5 at r1](https://reviewable.io/reviews/harness/harness-core/39910#-NGV3CqN2whNnwLQvzvQ:-NGV3CqN2whNnwLQvzvR:b-fdemtz) ([raw file](https://github.com/harness/harness-core/blob/d694ed58b3a38fc6be101d141ac3bcba19c96cf4/490-ce-commons/src/main/java/io/harness/ccm/commons/constants/RecommendationConstants.java#L5)):*
> ```Java
> import java.time.Duration;
> 
> public interface RecommendationConstants {
> ```

Constant class should be defined as `final class with private constructor`. You can use lombok '@UtilityClass' annotation at top as well.
Reference: https://stackoverflow.com/questions/479565/how-do-you-define-a-class-of-constants-in-java
___
*[`490-ce-commons/src/main/java/io/harness/ccm/commons/constants/RecommendationConstants.java` line 7 at r1](https://reviewable.io/reviews/harness/harness-core/39910#-NGVC8Oh52eInNybhbGN:-NGVC8Oh52eInNybhbGO:bnobzam) ([raw file](https://github.com/harness/harness-core/blob/d694ed58b3a38fc6be101d141ac3bcba19c96cf4/490-ce-commons/src/main/java/io/harness/ccm/commons/constants/RecommendationConstants.java#L7)):*
> ```Java
> public interface RecommendationConstants {
>   Double SAVINGS_THRESHOLD = 0.0;
>   Duration RECOMMENDATION_TTL = Duration.ofDays(15);
> ```

Will the TTL value not vary from the types of recommendations we have? For e.g. we do not have homegrown solution to compute the ec2 recommendations and we are relying on aws api to get the same everyday. If any day we do not get the recommendation for the same ec2 instance, we should not show the recommendation. We are dealing with this using the common table ce_recommendation LASTPROCESSEDAT field.
In Ec2 recom case, we may avoid storing the recom data in mongo for 15 days and keep it short for 5 days ?
Also do we have the cleanup setup for timescale table 'ce_recommendation' ? There will be no use keeping the stale recommendations there too.
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/39910#-NGV4c6L3GswAUzb5xFp:-NGV4c6L3GswAUzb5xFq:bhfjco8) ([raw file](https://github.com/harness/harness-core/blob/d694ed58b3a38fc6be101d141ac3bcba19c96cf4/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L125)):*
> ```Java
>             }
>           }
>           List<AWSEC2Details> instances = extractEC2InstanceDetails(ec2RecommendationResponse);
> ```

If the savings are not more than threshold and we don't want to store the recommendation then no point of capturing the utilisation data as well in timescale. We can club the below calls as well in above if statement.

**Review by trunapushpa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39910)* status: 8 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`490-ce-commons/src/main/java/io/harness/ccm/commons/constants/RecommendationConstants.java` line 5 at r1](https://reviewable.io/reviews/harness/harness-core/39910#-NGV3CqN2whNnwLQvzvQ:-NGsSNe80fJp70KlMrqP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d694ed58b3a38fc6be101d141ac3bcba19c96cf4/490-ce-commons/src/main/java/io/harness/ccm/commons/constants/RecommendationConstants.java#L5)):*
<details><summary><i>Previously, divyanshuchaubisa (Divyanshu Chaubisa) wrote…</i></summary><blockquote>

Constant class should be defined as `final class with private constructor`. You can use lombok '@UtilityClass' annotation at top as well.
Reference: https://stackoverflow.com/questions/479565/how-do-you-define-a-class-of-constants-in-java
</blockquote></details>

Done.
___
*[`490-ce-commons/src/main/java/io/harness/ccm/commons/constants/RecommendationConstants.java` line 7 at r1](https://reviewable.io/reviews/harness/harness-core/39910#-NGVC8Oh52eInNybhbGN:-NGsSOX-9UYzl58cBCYs:b-j7l4c9) ([raw file](https://github.com/harness/harness-core/blob/d694ed58b3a38fc6be101d141ac3bcba19c96cf4/490-ce-commons/src/main/java/io/harness/ccm/commons/constants/RecommendationConstants.java#L7)):*
<details><summary><i>Previously, divyanshuchaubisa (Divyanshu Chaubisa) wrote…</i></summary><blockquote>

Will the TTL value not vary from the types of recommendations we have? For e.g. we do not have homegrown solution to compute the ec2 recommendations and we are relying on aws api to get the same everyday. If any day we do not get the recommendation for the same ec2 instance, we should not show the recommendation. We are dealing with this using the common table ce_recommendation LASTPROCESSEDAT field.
In Ec2 recom case, we may avoid storing the recom data in mongo for 15 days and keep it short for 5 days ?
Also do we have the cleanup setup for timescale table 'ce_recommendation' ? There will be no use keeping the stale recommendations there too.
</blockquote></details>

For now we can have it as 15 days. If we need different for each one, we can change later.
I am not sure about timescale. @nikunj-badjatya do you know of any cleanup setup for timescale?
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/39910#-NGV4c6L3GswAUzb5xFp:-NGsSq6294_D0ZydPghq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d694ed58b3a38fc6be101d141ac3bcba19c96cf4/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L125)):*
<details><summary><i>Previously, divyanshuchaubisa (Divyanshu Chaubisa) wrote…</i></summary><blockquote>

If the savings are not more than threshold and we don't want to store the recommendation then no point of capturing the utilisation data as well in timescale. We can club the below calls as well in above if statement.
</blockquote></details>

Done.

**Review by divyanshuchaubisa — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39910)* status: 3. unresolved discussions.

**Pull request closed without merging**
