### PR TITLE
fix: [PL-27860]: Updating the ppt whenever the secret is updated

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36981)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36981)

**Comment by VikasMaddukuriHarness** [comment]
trigger ti2

**Comment by VikasMaddukuriHarness** [comment]
trigger ti0, ti1, ti3

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36981)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 141 at r2](https://reviewable.io/reviews/harness/harness-core/36981#-NAwhu7o6YVQZD39b9a1:-NAwhu7o6YVQZD39b9a2:b-ogptmw) ([raw file](https://github.com/harness/harness-core/blob/edabc364a60cb8803b25d6697abc0bfe3cce0ead/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L141)):*
> ```Java
>       AccountClient accountClient, NGEncryptedDataService encryptedDataService, NGEncryptorService ngEncryptorService,
>       SecretCrudService secretCrudService, NGManagerEncryptorHelper ngManagerEncryptorHelper,
>       ConnectorService connectorService) {
> ```

No need to add connector service as dependency here. NGConnectorSecretManagerServiceImpl has ConnectorService as dependency.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 180 at r2](https://reviewable.io/reviews/harness/harness-core/36981#-NAwiAf96Fp1ps370tNl:-NAwiAf96Fp1ps370tNm:b-t58o2m) ([raw file](https://github.com/harness/harness-core/blob/edabc364a60cb8803b25d6697abc0bfe3cce0ead/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L180)):*
> ```Java
>           connectorService.getHeartbeatPerpetualTaskId(vaultConnector.getAccountIdentifier(),
>               vaultConnector.getOrgIdentifier(), vaultConnector.getProjectIdentifier(), vaultConnector.getIdentifier());
>       connectorService.resetHeartBeatTask(vaultConnector.getAccountIdentifier(), heartBeatPerpetualTaskId);
> ```

call it via NGConnectorSecretManagerService
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 254 at r2](https://reviewable.io/reviews/harness/harness-core/36981#-NAwiH9S3q9Z3YBklm4y:-NAwiH9S3q9Z3YBklm4z:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/edabc364a60cb8803b25d6697abc0bfe3cce0ead/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L254)):*
> ```Java
>     connectorRepository.save(vaultConnector, ChangeType.NONE);
>     String heartBeatPerpetualTaskId = connectorService.getHeartbeatPerpetualTaskId(vaultConnector.getAccountIdentifier(), vaultConnector.getOrgIdentifier(), vaultConnector.getProjectIdentifier(), vaultConnector.getIdentifier());
>     connectorService.resetHeartBeatTask(vaultConnector.getAccountIdentifier(), heartBeatPerpetualTaskId);
> ```

same here

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36981)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 141 at r2](https://reviewable.io/reviews/harness/harness-core/36981#-NAwhu7o6YVQZD39b9a1:-NBHQQ6V4YUKxyXu4L09:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/edabc364a60cb8803b25d6697abc0bfe3cce0ead/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L141)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

No need to add connector service as dependency here. NGConnectorSecretManagerServiceImpl has ConnectorService as dependency.
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 180 at r2](https://reviewable.io/reviews/harness/harness-core/36981#-NAwiAf96Fp1ps370tNl:-NBHQQeDDwbhvk6MXNNC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/edabc364a60cb8803b25d6697abc0bfe3cce0ead/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L180)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

call it via NGConnectorSecretManagerService
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 254 at r2](https://reviewable.io/reviews/harness/harness-core/36981#-NAwiH9S3q9Z3YBklm4y:-NBHQRDM3hc0GSyeFzF1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/edabc364a60cb8803b25d6697abc0bfe3cce0ead/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L254)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

**Comment by VikasMaddukuriHarness** [comment]
trigger messagecheck

**Review by gn-harness — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36981)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36981)* status: :shipit: complete! ✓

**Pull request merged**
