### PR TITLE
fix: [DEL-3902]: Move AwsEcrTask and related classes to 930-delegate-tasks

### PR DESCRIPTION
**Pull request by johannesHarness**
Move AwsEcrTask and related classes to 930-delegate-tasks.

---
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32496)

### CODE REVIEW

**Comment by johannesHarness** [comment]
trigger messagecheck

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32496)* status: :shipit: complete! ✓

**Comment by johannesHarness** [comment]
trigger codeformat

**Comment by johannesHarness** [comment]
trigger codebasehash

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32496)* status: :shipit: complete! ✓

**Pull request merged**
