### PR TITLE
feat: [PLG-2125]: Add support for ChaosEngineering version in release notes

### PR DESCRIPTION
**Pull request by neelam-harness**
Adding support for showing the version number of Chaos Manager in Release Notes.

Tested locally and verified the version updates correctly. cc: @Jonsy13 

Screenshot 2023-04-27 at 4 03 40 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47032)

### CODE REVIEW

**Comment by Jonsy13** [comment]
**Screenshot for response of version query of Chaos-Manager API -** 

Screenshot 2023-04-27 at 10 20 45 AM

**Review by Jonsy13 — DISMISSED** [review]

**Review by kapil-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47032)* status: 2 file(s) to review. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 101 at r1](https://reviewable.io/reviews/harness/harness-core/47032#-NU6Ze1R86jnuuZlJdPP:-NU6Ze1R86jnuuZlJdPQ:b-9819g4) ([raw file](https://github.com/harness/harness-core/blob/98ae91d621ec11a918280b0b5673767f75bcf2af/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L101)):*
> ```Java
>     } else if (ModuleType.CHAOS.name().equalsIgnoreCase(moduleName)) {
>       StringBuilder chaosMgrUrl = new StringBuilder();
>       chaosMgrUrl.append(nextGenConfiguration.getChaosServiceClientConfig().getBaseUrl());
> ```

nit: we can rename it to chaosManagerUrl, for more clarity
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/47032#-NU6ZSTO5QW_ezRiPTww:-NU6ZSTO5QW_ezRiPTwx:b9w2kt1) ([raw file](https://github.com/harness/harness-core/blob/98ae91d621ec11a918280b0b5673767f75bcf2af/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L102)):*
> ```Java
>       StringBuilder chaosMgrUrl = new StringBuilder();
>       chaosMgrUrl.append(nextGenConfiguration.getChaosServiceClientConfig().getBaseUrl());
>       chaosMgrUrl.append(CHAOS_MANAGER_API);
> ```

nit: you can do 2 append's in one line, e.g. 



_Code snippet:_
```Java
response.append(INDENTATION).append("name = \"").append(name).append("\",\n");
```

**Comment by neelam-harness** [comment]
trigger review

**Comment by neelam-harness** [comment]
trigger messagecheck

**Review by Xin-Harness — APPROVED** [review]

**Review by kapil-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47032)* status: 2 file(s) to review.

**Review by kapil-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47032)* status: 2 file(s) to review.

**Comment by neelam-harness** [comment]
trigger review

**Comment by neelam-harness** [comment]
trigger checkstylecodeformat

**Comment by neelam-harness** [comment]
trigger utAll

**Pull request merged**
