### PR TITLE
feat:[PL-42298]: Create Implicit ACLs in batches.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
Create Implicit ACLs in batches.
This is needed as when upsert ACLs beyond threshold it fails. We found threshold of 10k where it fails.
We will investigate root cause until then making ACL creation in batches configurable. 
For details refer:
https://harness.atlassian.net/browse/PL-41791
https://harness.atlassian.net/browse/PL-42146

Tests:
Created Implicit ACLs for Account Viewer role assignment creating ACLs in batches.

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54799)

### CODE REVIEW

**Comment by Jimit09Gandhi** [comment]
trigger uts

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54799)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java` line 138 at r3](https://reviewable.io/reviews/harness/harness-core/54799#-NjNE94c4PAw3K7PzGCY:-NjNE94d1Xz1kFPiMcJU:b-je0l6n) ([raw file](https://github.com/harness/harness-core/blob/62880a60a63a183b33a52ba0506a2955464afa80/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java#L138)):*
> ```Java
>   }
> 
>   private long createImplicitACLs(List<ACL> acls) {
> ```

import org.apache.commons.collections4.ListUtils;

// ...

private long createImplicitACLs(List<ACL> acls) {
    List<List<ACL>> listOfSublists = ListUtils.partition(acls, batchSizeForACLCreation);

    return listOfSublists.stream()
            .mapToLong(sublist -> aclRepository.insertAllIgnoringDuplicates(sublist))
            .sum();
}

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54799)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java` line 138 at r3](https://reviewable.io/reviews/harness/harness-core/54799#-NjNFVgx8_ozFc9U23xQ:-NjNFVgx8_ozFc9U23xR:b-7oq8ui) ([raw file](https://github.com/harness/harness-core/blob/62880a60a63a183b33a52ba0506a2955464afa80/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java#L138)):*
> ```Java
>   }
> 
>   private long createImplicitACLs(List<ACL> acls) {
> ```

import org.apache.commons.collections4.ListUtils;

// ...

private long createImplicitACLs(List<ACL> acls) {
    int batchSize = batchSizeForACLCreation;
    List<List<ACL>> listOfSublists = ListUtils.partition(acls, batchSize);

    return listOfSublists.stream()
            .mapToLong(sublist -> aclRepository.insertAllIgnoringDuplicates(sublist))
            .sum();
}

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54799)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java` line 138 at r3](https://reviewable.io/reviews/harness/harness-core/54799#-NjNE94c4PAw3K7PzGCY:-NjO6Yxt19XFVDF_yUP8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/62880a60a63a183b33a52ba0506a2955464afa80/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java#L138)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

import org.apache.commons.collections4.ListUtils;

// ...

private long createImplicitACLs(List<ACL> acls) {
    List<List<ACL>> listOfSublists = ListUtils.partition(acls, batchSizeForACLCreation);

    return listOfSublists.stream()
            .mapToLong(sublist -> aclRepository.insertAllIgnoringDuplicates(sublist))
            .sum();
}
</blockquote></details>

Done.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54799#-:-NjODaf-7KslgDvwKEXl:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
