### PR TITLE
[fix]: [PL-24227]: Add the repo provider in the connectivity error

### PR DESCRIPTION
**Pull request by DeepakPatankar**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31928)

### CODE REVIEW

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31928)* status: 8 file(s) to review. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/impl/GitSyncErrorServiceImpl.java, line 418 at r1](https://reviewable.io/reviews/harness/harness-core/31928#-MzYggFfExzKDJ_UDYOY:-MzYggFfExzKDJ_UDYOZ:bml5s8c) ([raw file](https://github.com/harness/harness-core/blob/911fae0df527b4c10c3bd3ba082128edc171d4e7/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/impl/GitSyncErrorServiceImpl.java#L418)):*
> ```Java
> 
>   @Override
>   public void saveConnectivityError(
> ```

Can we use the same method as we have repoUrl, we can get ConnectorType, this will reduce complexity to change the method everywhere and not missing on anything.

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31928)* status: 8 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/impl/GitSyncErrorServiceImpl.java, line 418 at r1](https://reviewable.io/reviews/harness/harness-core/31928#-MzYggFfExzKDJ_UDYOY:-MzZrFQp2FzxhF6KXQGS:bazqfiz) ([raw file](https://github.com/harness/harness-core/blob/911fae0df527b4c10c3bd3ba082128edc171d4e7/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/impl/GitSyncErrorServiceImpl.java#L418)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Can we use the same method as we have repoUrl, we can get ConnectorType, this will reduce complexity to change the method everywhere and not missing on anything. 
</blockquote></details>

I tried doing the changes. But it looks likk the current appraoch is more cleaner, compared to what it would be after suggestions. Hence lets keep it the way it is currently.

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 8 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31928#-:-Mzo8aElDIt8OxY6pzn6:bnfp4nl)* status: 11 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by bhavya181 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31928#-:-Mzt3JlAAEArnSRqFqyZ:bnfp4nl)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 6 of 8 files at r1, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31928)* status: 1 file(s) to review.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 6 of 8 files at r1, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31928)* status: :shipit: complete! ✓

**Pull request merged**
