### PR TITLE
feat: [PLG-1740]: Second subscription - CI

### PR DESCRIPTION
**Pull request by thomas-grasman**
Hotfix to pre-qa release 792xx

This change includes end to end changes including a migration which will allow customers to have up to two subscriptions to manage all of their module licenses. Paired with the required front end changes, customers will be able to purchase CI licenses using credit cards. If they purchase licenses for both CI and FF and select the same payment frequency, both modules will be tracked under the same subscriptoin.

Multiple module licenses will now be able to be tracked under a single module.

- subscriptionDetails no longer point to a single moduleLicense. moduleType was removed from subscriptionDetails.
- moduleLicense now requires a pointer to the subscription which is managing it.
- subscriptionDetails can now be looked up by the accountID and payment frequency.
- When subscription payments are received, we now cycle through all the modules listed under this subscription for creating/updating.
- When creating a new subscription to a module, we must check if another subscription already exists for the requested payment frequency. If it does, we add to that subscription rather than creating a new one.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46887)

### CODE REVIEW

**Review by kapil-harness — APPROVED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46887)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Comment by thomas-grasman** [comment]
trigger review

**Comment by thomas-grasman** [comment]
trigger review

**Comment by thomas-grasman** [comment]
trigger review

**Pull request merged**
