### PR TITLE
[feat]: [CCM-5352]: AWS Account tags support

### PR DESCRIPTION
**Pull request by nikunj-badjatya**
- A batch job (cron type) is written which will run (configurable) once a day in prod environment.
- Iterate through all CCM AWS connectors where BILLING feature is enabled.
- Fetch all account level tags by calling AWS api.
- Store this in BQ table (CloudProviderEntityTags) within the same dataset for each customer. Idea is that going forward we may have Azure and GCP tags as well. This table is partitioned on createdAt time. 
- The batch job will create the dataset and table if not existing.
- Here is how batch job execution looks like (see ticket)
- This batch job is also made configurable to be stopped entirely.
- Additionally, if a particular AWS Connector was for master account (management account), the job will try to fetch all member accounts and call list resource for tags api for each of them and store it in BQ in similar fashion.
- We want to do this periodically (once a day) because the tags can change at the source aws account and we should have updated tags with us.
- Cron is made configurable. 
- Tested on dev and screenshots are attached in the ticket for reference. 
- NOT TESTED - How does it behave when tags cross 1000s or more. 
- Secret in config is for dev
- Added autolog context for regular cron jobs - cronJobType and accountId. 

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30647)

### CODE REVIEW

**Comment by nikunj-badjatya** [comment]
- A batch job is written which will run (configurable) once a day in prod environment.

- Iterate through all CCM AWS connectors where BILLING feature is enabled. 
 
- Fetch all account level tags by calling AWS api.
 
- Store this in BQ table (CloudProviderEntityTags) within the same dataset for each customer.  Idea is that going forward we may have Azure and GCP tags as well. 
 
- The batch job will create the dataset and table if not existing. 
 
- Here is how batch job execution looks like.
  
- This batch job is also made configurable to be stopped entirely. 
 
- Additionally, if a particular AWS Connector was for master account (management account), the job will try to fetch all member accounts and call list resource for tags api for each of them and store it in BQ in similar fashion.
 
- We want to do this periodically (once a day) because the tags can change at the source aws account and we should have updated tags with us.

**Review by Rohit-Kaliki — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30647)* status: :shipit: complete! ✓

___
*[280-batch-processing/batch-processing-config.yml, line 121 at r1](https://reviewable.io/reviews/harness/harness-core/30647#-MvqUQmGBc-Hyt-hZo8Y:-MvqUQmGBc-Hyt-hZo8Z:b498hp6) ([raw file](https://github.com/harness/harness-core/blob/f3bf117a0601535896d135f58595cb59ab8da810/280-batch-processing/batch-processing-config.yml#L121)):*
> ```YAML
> 
> ngManagerServiceHttpClientConfig:
>   baseUrl: http://localhost:7457/
> ```

Do we need to change this value and the secret back for local testing?

**Comment by nikunj-badjatya** [comment]
> > Reviewed 19 of 19 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/30647)_ status: :shipit: complete! ✓
> 
> _[280-batch-processing/batch-processing-config.yml, line 121 at r1](https://reviewable.io/reviews/harness/harness-core/30647#-MvqUQmGBc-Hyt-hZo8Y:-MvqUQmGBc-Hyt-hZo8Z:b498hp6) ([raw file](https://github.com/harness/harness-core/blob/f3bf117a0601535896d135f58595cb59ab8da810/280-batch-processing/batch-processing-config.yml#L121)):_
> 
> > ```yaml
> > ngManagerServiceHttpClientConfig:
> >   baseUrl: http://localhost:7457/
> > ```
> 
> Do we need to change this value and the secret back for local testing?

yeah will change in next pr.

**Review by hitesharinga — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30647)* status: 1 change requests. 1. unresolved discussions. 

___
*[280-batch-processing/src/main/java/io/harness/batch/processing/pricing/gcp/bigquery/BQConst.java, line 51 at r1](https://reviewable.io/reviews/harness/harness-core/30647#-MvqeAPu20-acdOHGDDF:-MvqeAPv7LJGY5LZcsQb:btefodq) ([raw file](https://github.com/harness/harness-core/blob/336ea2d7e99c007b134618f2ca13ee4431bda987/280-batch-processing/src/main/java/io/harness/batch/processing/pricing/gcp/bigquery/BQConst.java#L51)):*
> ```Java
>       "SELECT count(*) AS count, cloudProvider FROM `%s` GROUP BY cloudProvider";
> 
>   public static final String CLOUD_PROVIDER_ENTITY_TAGS_INSERT =
> ```

@rohit-kaliki there might be a case where aws accountId is duplicate. 
@nikunj-badjatya  shall we delete entityId instead of cloud providerId.

**Review by nikunj-badjatya — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30647)* status: 1 change requests. 2. unresolved discussions. 

___
*[280-batch-processing/src/main/java/io/harness/batch/processing/pricing/gcp/bigquery/BQConst.java, line 51 at r1](https://reviewable.io/reviews/harness/harness-core/30647#-MvqeAPu20-acdOHGDDF:-Mvqk1_-49VjpsPVmJZe:b-ydy5ca) ([raw file](https://github.com/harness/harness-core/blob/336ea2d7e99c007b134618f2ca13ee4431bda987/280-batch-processing/src/main/java/io/harness/batch/processing/pricing/gcp/bigquery/BQConst.java#L51)):*
<details><summary><i>Previously, hitesharinga (Hitesh Aringa) wrote…</i></summary><blockquote>

@rohit-kaliki there might be a case where aws accountId is duplicate. 
@nikunj-badjatya  shall we delete entityId instead of cloud providerId. 
</blockquote></details>

We are deleting based on combination of cloudProviderId and entityId and entityName before inserting. 
Also, unified table will have one of - awsUsageAccountId, azureSubscriptionId or gcpBillingAccountId

**Review by hitesharinga — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30647)* status: 1. unresolved discussions.

**Review by hitesharinga — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30647)* status: 1. unresolved discussions.

**Pull request merged**
