### PR TITLE
feat: [CDS-47034]: ASG Blue Green Deploy / Manager Changes

### PR DESCRIPTION
**Pull request by vitsafronovici**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42711)

### CODE REVIEW

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 56 of 56 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42711)* status: 56 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenDeployStep.java` line 133 at r1](https://reviewable.io/reviews/harness/harness-core/42711#-NLzbyPe-BVJv5AOwupV:-NLzbyPe-BVJv5AOwupW:bh8yagw) ([raw file](https://github.com/harness/harness-core/blob/c6bff8933095c9fb00ce527befa6c2fac8753208/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenDeployStep.java#L133)):*
> ```Java
> 
>     return asgStepCommonHelper.queueAsgTask(stepElementParameters, asgBlueGreenDeployRequest, ambiance,
>         executionPassThroughData, true, AWS_ASG_BLUE_GREEN_DEPLOY_TASK_NG);
> ```

why is it a different task? shouldn't we use same task but having different commandName?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenDeployStep.java` line 269 at r1](https://reviewable.io/reviews/harness/harness-core/42711#-NLzcStM-sIqSQeexdUC:-NLzcStM-sIqSQeexdUD:b-b3tomw) ([raw file](https://github.com/harness/harness-core/blob/c6bff8933095c9fb00ce527befa6c2fac8753208/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenDeployStep.java#L269)):*
> ```Java
>                                                         .build();
> 
>       return executeAsgTask(ambiance, stepElementParameters, asgExecutionPassThroughData,
> ```

not sure if i got it right, are we executing the task once again for rollback? we are not having different rollback task?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgBlueGreenDeployTaskNG.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/42711#-NLzd6P2195nGpd88J1j:-NLzd6P2195nGpd88J1k:bkt5jnt) ([raw file](https://github.com/harness/harness-core/blob/c6bff8933095c9fb00ce527befa6c2fac8753208/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgBlueGreenDeployTaskNG.java#L48)):*
> ```Java
>   public AsgCommandResponse run(TaskParameters parameters) {
>     AsgCommandRequest asgCommandRequest = (AsgCommandRequest) parameters;
>     // TODO
> ```

what is this todo about?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgBlueGreenDeployTaskNG.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/42711#-NLzd9BGA1A5utYU7Ih_:-NLzd9BGA1A5utYU7Iha:bgz9xj8) ([raw file](https://github.com/harness/harness-core/blob/c6bff8933095c9fb00ce527befa6c2fac8753208/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgBlueGreenDeployTaskNG.java#L54)):*
> ```Java
>         .asgBlueGreenDeployResult(
>             AsgBlueGreenDeployResult.builder()
>                 .asgName("app__2")
> ```

why this is hardcoded?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgBlueGreenPrepareRollbackDataTaskNG.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/42711#-NLzdDl33EQzQdaBbcCK:-NLzdDl33EQzQdaBbcCL:b5mt9h2) ([raw file](https://github.com/harness/harness-core/blob/c6bff8933095c9fb00ce527befa6c2fac8753208/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgBlueGreenPrepareRollbackDataTaskNG.java#L51)):*
> ```Java
>         .asgBlueGreenPrepareRollbackDataResult(
>             AsgBlueGreenPrepareRollbackDataResult.builder()
>                 .asgLoadBalancerConfig(AsgLoadBalancerConfig.builder().loadBalancer("loadBalancer").build())
> ```

same, why is this hardcoded?

**Review by lovish1999 — DISMISSED** [review]
> Reviewed 56 of 56 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42711)* status: 1 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42711)* status: 1 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42711)* status: 1 of 2 approvals obtained.

**Review by lovish1999 — APPROVED** [review]

**Pull request merged**
