### PR TITLE
[fix]:[pl-27461]: fix updateStableTemplate version

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
fix updateStableTemplate version, have tested out the updateStableTemplate version when with and without passing the branch info. Have tested out the Inline templates in GitX project, no git management, works as expected. For old git sync, its failing, have raised a bug accordingly[https://harness.atlassian.net/browse/CDS-42127]

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36599)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36599)

**Comment by adivishy1** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
@adivishy1 can we test updateStableTemplate API for INLINE/Git-Sync and all other possible types of templates. Only then we should merge it.

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36599)* status: :shipit: complete! ✓

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36599)* status: :shipit: complete! ✓

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java` line 134 at r2](https://reviewable.io/reviews/harness/harness-core/36599#-NA8_Shs429Oj7nRQR8L:-NA8_Shs429Oj7nRQR8M:b-sdv572) ([raw file](https://github.com/harness/harness-core/blob/184050fe86d05d53808b07537e9de2c1b84f4eb1/840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java#L134)):*
> ```Java
>           if (versionLabelNode == null) {
>             Optional<TemplateEntity> templateEntity =
>                 templateServiceHelper.getTemplateOrThrowExceptionIfInvalid(templateIdentifierRef.getAccountIdentifier(),
> ```

Let's change this to getMetadataOrThrowExceptionIfInvalid() because template yaml is not required here.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36599)* status: 1 change requests. 1. unresolved discussions. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java` line 134 at r2](https://reviewable.io/reviews/harness/harness-core/36599#-NA8_Shs429Oj7nRQR8L:-NA8cXEc4BCGv36GNxSM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/184050fe86d05d53808b07537e9de2c1b84f4eb1/840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java#L134)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Let's change this to getMetadataOrThrowExceptionIfInvalid() because template yaml is not required here.
</blockquote></details>

Done.



_Code quote:_
```Java
getNestedTemplateReferences
```

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36599)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36599#-:-NA8dWHkCORUMnbNsVg5:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
