### PR TITLE
fix: [CDS-46403]: add null check for primary artifact spec

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes

This is to add error handling for null primary and sidecar artifact check.
This will remove dependency on how ui rendering yaml.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40185)

### CODE REVIEW

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40185)* status: :shipit: complete! ✓

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java` line 207 at r2](https://reviewable.io/reviews/harness/harness-core/40185#-NH425uaBE982giPMBcj:-NH425uaBE982giPMBck:b-bel7hu) ([raw file](https://github.com/harness/harness-core/blob/ed243ab6c9beb0944833accd2c240e20496d686f/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java#L207)):*
> ```Java
>   }
> 
>   private boolean isPrimaryArtifactPresentWithSpecAndSourceType(ArtifactListConfig artifacts) {
> ```

as discussed, lets create an enum 
```
enum ACTION {
    CREATE_DELEGATE_TASK,
    RUN_SYNC,
    SKIP;
  }
``` here
```

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java` line 181 at r3](https://reviewable.io/reviews/harness/harness-core/40185#-NH4JkCX6M6pAWCm_Iop:-NH4JkCX6M6pAWCm_Ioq:b-qr2zte) ([raw file](https://github.com/harness/harness-core/blob/08126dd7911330322cfcbe133581e18cfa605a66/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java#L181)):*
> ```Java
>       ACTION actionForPrimaryArtifact =
>           shouldCreateDelegateTask(artifacts.getPrimary().getSourceType(), artifacts.getPrimary().getSpec());
>       if (actionForPrimaryArtifact.equals(ACTION.CREATE_DELEGATE_TASK)) {
> ```

constants should be on the left side of equals

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40185)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40185)* status: :shipit: complete! ✓

**Pull request merged**
