### PR TITLE
feat: [IDP-1813]: Support for Scorecard delegate & k8s namespace

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56541)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56541)* status: 8 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/kubernetes/KubernetesProxyThroughDsl.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/56541#-Nl8KBHw6InBgQo-dh3B:-Nl8KBHw6InBgQo-dh3C:beacwi8) ([raw file](https://github.com/harness/harness-core/blob/dd6d221a2d467f281272a7b5c72eee47294904b3/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/kubernetes/KubernetesProxyThroughDsl.java#L52)):*
> ```Java
>   @Override
>   protected String getHost(Map<String, String> data) {
>     return data.get("{HOST}").replace(HTTPS_PREFIX, "");
> ```

For K8s, we make an internal call to another IDP Service API. So we should always go with direct client. We don't need delegate here. We can return null here.



_Code quote:_
```Java
return data.get("{HOST}").replace(HTTPS_PREFIX, "");
```

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56541)* status: 8 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/kubernetes/KubernetesProxyThroughDsl.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/56541#-Nl8KBHw6InBgQo-dh3B:-Nl8KYQ303HOCXM4ekf1:b-s934wt) ([raw file](https://github.com/harness/harness-core/blob/dd6d221a2d467f281272a7b5c72eee47294904b3/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/kubernetes/KubernetesProxyThroughDsl.java#L52)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

For K8s, we make an internal call to another IDP Service API. So we should always go with direct client. We don't need delegate here. We can return null here.
</blockquote></details>

Now that I think again - We should still be good as the host will be `https://(stress/qa/app/app3).harness.io`. And it will not be sent via delegate anyway.
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/kubernetes/KubernetesProxyThroughDsl.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/56541#-Nl8Kpxd0VOwA8Oe2TXI:-Nl8Kpxd0VOwA8Oe2TXJ:b514zy6) ([raw file](https://github.com/harness/harness-core/blob/dd6d221a2d467f281272a7b5c72eee47294904b3/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/kubernetes/KubernetesProxyThroughDsl.java#L52)):*
> ```Java
>   @Override
>   protected String getHost(Map<String, String> data) {
>     return data.get("{HOST}").replace(HTTPS_PREFIX, "");
> ```

nit: Not related to this PR. We can use the HOST constant in DataSourceProvider.



_Code quote:_
```Java
"{HOST}"
```

**Review by vikyathharekal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56541#-:-Nl8LJ9J7mjF-bgkYjOS:bnfp4nl)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by mankrit-singh — APPROVED** [review]

**Comment by vigneswara-propelo** [comment]
trigger uts

**Comment by vigneswara-propelo** [comment]
trigger review

**Comment by vigneswara-propelo** [comment]
trigger ut0

**Comment by sandeepa-kv-jois** [comment]
Unrelated tests are failing, going ahead with FM

**Pull request merged**
