### PR TITLE
techdebt: [PL-32390]: Additional logging to check empty UserPermissionInfo

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes

We have this issue where the cache is either getting corrupted or we have some application bug, where we are setting an empty UserPermissionInfo object. 

Adding some logging to debug it.

## Checklist
- [X] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47107)

### CODE REVIEW

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java` line 560 at r1](https://reviewable.io/reviews/harness/harness-core/47107#-NU8bVom-tX6Nf-kM8JO:-NU8bVom-tX6Nf-kM8JP:bnlktsn) ([raw file](https://github.com/harness/harness-core/blob/7b73e208b542ab98f06570fd5e7b4d2b4725860b/400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java#L560)):*
> ```Java
>         value = getUserPermissionInfoFromDB(accountId, user);
>         // Add a log message when UserPermissionInfo is empty. Context: PL-32390
>         if (value.getAppPermissionMap().isEmpty() && value.getAppPermissionMapInternal().isEmpty()
> ```

Add null checks and also Can we refactor this check into its own method instead of repeating.

**Review by gn-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47107)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java` line 560 at r1](https://reviewable.io/reviews/harness/harness-core/47107#-NU8bVom-tX6Nf-kM8JO:-NU8djbv8JWXw3m4RqPM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7b73e208b542ab98f06570fd5e7b4d2b4725860b/400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java#L560)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Add null checks and also Can we refactor this check into its own method instead of repeating.
</blockquote></details>

Done.



_Code quote:_
```Java
value.getAppPermissionMap()
```

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47107)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by gn-harness** [comment]
trigger utAll

**Comment by piyush-harness** [comment]
Force merging because there is some issue with Unit tests and this change only adds additional logging , along with Proper Null checks.

**Pull request merged**
