### PR TITLE
fix: [SRM-13979]: Adding index on verificationTaskId and analysisEndTime for LogAnalysisResult

### PR DESCRIPTION
**Pull request by dhruv-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44187)

### CODE REVIEW

**Review by n00bitax — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44187)* status: :shipit: complete! ✓

**Review by n00bitax — APPROVED** [review]

**Comment by dhruv-harness** [comment]
trigger ti0
trigger ti1
trigger ti2
trigger ti3
trigger ti4

**Comment by dhruv-harness** [comment]
trigger checkstylecodeformat

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 31 of 33 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44187)* status: :shipit: complete! ✓

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/entities/LogAnalysisResult.java` line 59 at r3](https://reviewable.io/reviews/harness/harness-core/44187#-NOxhJ4H7EJj3WQMfZCQ:-NOxhJ4H7EJj3WQMfZCR:b-ketxp3) ([raw file](https://github.com/harness/harness-core/blob/41b3ffbdd48751ba4b06f1763c329fe919bd84ab/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/entities/LogAnalysisResult.java#L59)):*
> ```Java
>                  .field(LogAnalysisResultKeys.analysisEndTime)
>                  .build())
>         .add(CompoundMongoIndex.builder()
> ```

nit: Good change. But now, I dont think the above index will be used much, and better removed. Also the below query can be optimised further: as the second one.



_Code snippet (i):_
```Java
hPersistence.createQuery(LogAnalysisResult.class, excludeAuthority)
        .filter(LogAnalysisResultKeys.verificationTaskId, verificationTaskId)
        .field(LogAnalysisResultKeys.analysisStartTime)
        .greaterThanOrEq(startTime)
        .field(LogAnalysisResultKeys.analysisEndTime)
        .lessThanOrEq(endTime)
        
```



_Code snippet (ii):_
```Java
hPersistence.createQuery(LogAnalysisResult.class, excludeAuthority)
        .filter(LogAnalysisResultKeys.verificationTaskId, verificationTaskId)
        .field(LogAnalysisResultKeys.analysisStartTime)
        .greaterThanOrEq(startTime)
        .field(LogAnalysisResultKeys.analysisEndTime)
        .greaterThanOrEq(startTime)
        .field(LogAnalysisResultKeys.analysisEndTime)
        .lessThanOrEq(endTime)
```

**Pull request merged**
