### PR TITLE
[fix]: [DEL-4198]: support ability to release delegate for an account till next release

### PR DESCRIPTION
**Pull request by raghuAtWings**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33750)

### CODE REVIEW

**Review by mdmilic — DISMISSED** [review]
It's missing the part where we actually remove the record "on new release". That should probably happen when we update the ring for the customer. E.g. if writing new version to ring3 - find all overrides for customers who are in ring3 which are validTillNextRelease and delete them. If this is a first step in the process and we plan implementing deletion later, then it looks good. 

> Reviewed 1 of 5 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33750#-:-N3uIOlE7Xa_75xYK5Xm:b-er7ioh)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminDelegateVersionService.java` line 62 at r4](https://reviewable.io/reviews/harness/harness-core/33750#-N3uFR-lAyPgHsvZ51T5:-N3uFR-lAyPgHsvZ51T6:b4b3ucl) ([raw file](https://github.com/harness/harness-core/blob/0ad1a7e632012c90adc5714c67cfc2632c970568/400-rest/src/main/java/io/harness/datahandler/services/AdminDelegateVersionService.java#L62)):*
> ```Java
>     if (validTillNextRelease) {
>       updateOperation.set(VersionOverrideKeys.validTillNextRelease, true);
>       log.info("Setting {} for accountID, will be valid till next release", overrideType);
> ```

Might be good to log the overrideValue as well
___
*[`970-watcher-beans/src/main/java/io/harness/delegate/beans/DelegateConfiguration.java` line 25 at r4](https://reviewable.io/reviews/harness/harness-core/33750#-N3uHUbGB7Y7nz0524Cj:-N3uHUbHD2jFYE6VtvFk:bmm4ex4) ([raw file](https://github.com/harness/harness-core/blob/0ad1a7e632012c90adc5714c67cfc2632c970568/970-watcher-beans/src/main/java/io/harness/delegate/beans/DelegateConfiguration.java#L25)):*
> ```Java
>   // Since we will always have one delegateversion for account adding validUntil for all of them at once.
>   private Long validUntil;
>   private boolean validTillNextRelease;
> ```

I think we don't need to have these two in the DelegateConfiguration, we are kinda duplicating the functionality of the VersionOverrides. In my opinion this versioning from the account collection should disappear soon as obsolete and we should only use rings + overrides (I think we are capable of doing that today as well, but we probably don't have enough confidence to turn it on for everyone - though we do use it in production successfully)



_Code quote:_
```Java
  private Long validUntil;
  private boolean validTillNextRelease;
```

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33750)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminDelegateVersionService.java` line 62 at r4](https://reviewable.io/reviews/harness/harness-core/33750#-N3uFR-lAyPgHsvZ51T5:-N3wVt1226iAjjhe918p:b-959hsp) ([raw file](https://github.com/harness/harness-core/blob/0ad1a7e632012c90adc5714c67cfc2632c970568/400-rest/src/main/java/io/harness/datahandler/services/AdminDelegateVersionService.java#L62)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Might be good to log the overrideValue as well
</blockquote></details>


done
___
*[`970-watcher-beans/src/main/java/io/harness/delegate/beans/DelegateConfiguration.java` line 25 at r4](https://reviewable.io/reviews/harness/harness-core/33750#-N3uHUbGB7Y7nz0524Cj:-N3wUkXy9eLJz0bIBrx7:b44mef4) ([raw file](https://github.com/harness/harness-core/blob/0ad1a7e632012c90adc5714c67cfc2632c970568/970-watcher-beans/src/main/java/io/harness/delegate/beans/DelegateConfiguration.java#L25)):*
> doing that today as well, but we probably don't have enough confidence to turn it on for everyone - though we do use it in production successfully)
Yeah, initially I skipped making changes over here, and than got a adhoc request to support without-ring version as well. The code-path will get deprecated when ring is enabled fully in prod, we can remove this logic later.

**Review by bharatgoelharness — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, 1 of 4 files at r5, 2 of 2 files at r6, 3 of 293 files at r7, 290 of 290 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33750)* status: 1. unresolved discussions.

**Review by raghuAtWings — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33750#-:-N416gpS5BOcBw2zlMxT:bnfp4nl)* status: :shipit: complete! ✓

**Review by arpit3107 — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, 1 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33750)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33750)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]

**Pull request merged**
