### PR TITLE
[feat]: [CCM-9935]: Fixing Backend APIs for Chewy's Budget

### PR DESCRIPTION
**Pull request by iamanmolm**
## Describe your changes
List of changes:
1. Rounding off the lastYear, actual & forecasted cost to two decimal places
2. Changing the response of LastYearMonthlyCost API to return ValueDataPoint DTO, which will have time and value. Now these keys will store time and cost as value.
3. Before this, we were throwing exception if budget monthly amount do not match the whole budget amount but now instead of throwing exception. We are setting the total budget amount equal to sum of all monthly budget amount at the backend.
4. In edit budget flow, we call budgetList graphQL to get the budget information which was stored in BudgetSummary DTO, so add  budgetBreakdown and budgetMonthlyAmount to the DTO. It will be used in budgetlist graphQL API.
5. Modifying both REST and GraphQL API that is {id}/costDetails and FetchBudgetsGridData respectively to add one more parameter breakdown in it(By default it will take value of YEARLY). Looking at the breakdown only we will be returning monthly wise or year wise data. This is so to support toggle button in budget details page as well.
6. Add a feature flag CCM_MONTHLY_BUDGET_BREAKDOWN("Use monthly breakdown feature in Yearly Period Budget", HarnessTeam.CE)

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40335)

### CODE REVIEW

**Review by svmav — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40335)* status: 10 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveResource.java` line 216 at r1](https://reviewable.io/reviews/harness/harness-core/40335#-NHUISaDBz1df5JedIXn:-NHUISaDBz1df5JedIXo:bpkfl7m) ([raw file](https://github.com/harness/harness-core/blob/632b8aa09f760eac44078534a339642ed5ad6d07/ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveResource.java#L216)):*
> ```Java
>             content = { @Content(mediaType = MediaType.APPLICATION_JSON) })
>       })
>   public ResponseDTO<LinkedHashMap<String, Double>>
> ```

It would be better if we have return type such as List<Object> where object has fields for timestamp and cost, that way the API is much more extensive and can be reused for other use cases as well, for example it will be very easily usable for charts and analytics. Right now, looks like the API caters to a very specific use case.
___
*[`ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveResource.java` line 240 at r1](https://reviewable.io/reviews/harness/harness-core/40335#-NHUHwAo55ay_-7cEcND:-NHUHwAo55ay_-7cEcNE:bjt1eqk) ([raw file](https://github.com/harness/harness-core/blob/632b8aa09f760eac44078534a339642ed5ad6d07/ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveResource.java#L240)):*
> ```Java
>       String months[] = BudgetUtils.getMonthsGivenStartTime(startTime);
>       response = new LinkedHashMap<>();
>       for (int i = 0; i < 12; i++) {
> ```

The Resource class should have minimal code logic. The code logic should be at the service layer. Can you move it to a relevant service class.

**Comment by iamanmolm** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/40335)_ status: 10 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveResource.java` line 216 at r1](https://reviewable.io/reviews/harness/harness-core/40335#-NHUISaDBz1df5JedIXn:-NHUISaDBz1df5JedIXo:bpkfl7m) ([raw file](https://github.com/harness/harness-core/blob/632b8aa09f760eac44078534a339642ed5ad6d07/ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveResource.java#L216)):_
> 
> > ```java
> >             content = { @Content(mediaType = MediaType.APPLICATION_JSON) })
> >       })
> >   public ResponseDTO<LinkedHashMap<String, Double>>
> > ```
> 
> It would be better if we have return type such as (List of Object) where object has fields for timestamp and cost, that way the API is much more extensive and can be reused for other use cases as well, for example it will be very easily usable for charts and analytics. Right now, looks like the API caters to a very specific use case.
> 
> _[`ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveResource.java` line 240 at r1](https://reviewable.io/reviews/harness/harness-core/40335#-NHUHwAo55ay_-7cEcND:-NHUHwAo55ay_-7cEcNE:bjt1eqk) ([raw file](https://github.com/harness/harness-core/blob/632b8aa09f760eac44078534a339642ed5ad6d07/ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveResource.java#L240)):_
> 
> > ```java
> >       String months[] = BudgetUtils.getMonthsGivenStartTime(startTime);
> >       response = new LinkedHashMap<>();
> >       for (int i = 0; i < 12; i++) {
> > ```
> 
> The Resource class should have minimal code logic. The code logic should be at the service layer. Can you move it to a relevant service class.

Fixed these.

**Review by iamanmolm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40335)* status: 14 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveResource.java` line 216 at r1](https://reviewable.io/reviews/harness/harness-core/40335#-NHUISaDBz1df5JedIXn:-NHhQjhB3OM384hTRt7v:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/632b8aa09f760eac44078534a339642ed5ad6d07/ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveResource.java#L216)):*
<details><summary><i>Previously, svmav (Shubhanshu Verma) wrote…</i></summary><blockquote>

It would be better if we have return type such as List<Object> where object has fields for timestamp and cost, that way the API is much more extensive and can be reused for other use cases as well, for example it will be very easily usable for charts and analytics. Right now, looks like the API caters to a very specific use case.
</blockquote></details>

Done.
___
*[`ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveResource.java` line 240 at r1](https://reviewable.io/reviews/harness/harness-core/40335#-NHUHwAo55ay_-7cEcND:-NHhQuy-B8hJ7jLWZgTg:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/632b8aa09f760eac44078534a339642ed5ad6d07/ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/perspectives/PerspectiveResource.java#L240)):*
<details><summary><i>Previously, iamanmolm (Anmol Maheshwari) wrote…</i></summary><blockquote>

Fixed these.
</blockquote></details>

Done

**Review by svmav — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40335)* status: 14 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`490-ce-commons/src/main/java/io/harness/ccm/budget/utils/BudgetUtils.java` line 458 at r2](https://reviewable.io/reviews/harness/harness-core/40335#-NHhowlj7ectmi5ULFiP:-NHhowlj7ectmi5ULFiQ:bl0h84j) ([raw file](https://github.com/harness/harness-core/blob/5b9dfaf59a4189bb300088fd3a9f735d097908a0/490-ce-commons/src/main/java/io/harness/ccm/budget/utils/BudgetUtils.java#L458)):*
> ```Java
>     c.setTimeZone(TimeZone.getTimeZone(DEFAULT_TIMEZONE));
>     c.setTimeInMillis(startOfMonth);
>     int i = 0;
> ```

Can you rename i

**Review by iamanmolm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40335)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`490-ce-commons/src/main/java/io/harness/ccm/budget/utils/BudgetUtils.java` line 458 at r2](https://reviewable.io/reviews/harness/harness-core/40335#-NHhowlj7ectmi5ULFiP:-NHhr6HZ-mhdBM9mrHcV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5b9dfaf59a4189bb300088fd3a9f735d097908a0/490-ce-commons/src/main/java/io/harness/ccm/budget/utils/BudgetUtils.java#L458)):*
<details><summary><i>Previously, svmav (Shubhanshu Verma) wrote…</i></summary><blockquote>

Can you rename i 
</blockquote></details>

Done.

**Review by svmav — APPROVED** [review]
> Reviewed 6 of 10 files at r1, 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40335)* status: :shipit: complete! ✓

**Pull request merged**
