### PR TITLE
feat: [CDS-71393]: Settings support for expression engine v2

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Describe your changes

Moved the FF for expression engine v2 under settings. This is required so that customer can enable/disable for a given project inorder to test this out.

Testing done:
- With settings as false, tried to fetch the json and was not able to fetch it.
- With settings as true, was able to fetch the json and parse it.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48892)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48892)* status: 7 file(s) to review. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/execution/expansion/PlanExpansionServiceImpl.java` line 147 at r2](https://reviewable.io/reviews/harness/harness-core/48892#-NXJFMyZEponkR2xk4Nj:-NXJFMy_2SVAPteKzqTv:b2qhh4) ([raw file](https://github.com/harness/harness-core/blob/6d46961591c9e6bf9730f0dba348da72141196f4/pipeline-service/modules/orchestration/src/main/java/io/harness/execution/expansion/PlanExpansionServiceImpl.java#L147)):*
> ```Java
> 
>   private boolean shouldUseExpandedJsonFunctor(Ambiance ambiance) {
>     return AmbianceUtils.shouldUseExpressionEngineV2(ambiance);
> ```

in ENgineExpressionEvaluator can you evaluateByCreatingExpression to include Script under it

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48892)* status: 7 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/execution/expansion/PlanExpansionServiceImpl.java` line 147 at r2](https://reviewable.io/reviews/harness/harness-core/48892#-NXJFMyZEponkR2xk4Nj:-NXJHZlN15O5ZaknYmjx:b-fnj79z) ([raw file](https://github.com/harness/harness-core/blob/6d46961591c9e6bf9730f0dba348da72141196f4/pipeline-service/modules/orchestration/src/main/java/io/harness/execution/expansion/PlanExpansionServiceImpl.java#L147)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

in ENgineExpressionEvaluator can you evaluateByCreatingExpression to include Script under it
</blockquote></details>

done discussed offline

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48892)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48892)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
Approved for settings yml

**Comment by sahilhindwani-harness** [comment]
trigger review

**Pull request merged**
