### PR TITLE
fix: [CI-9329]: Reverting the PR CI-9329 throw statement for not defining build properties.

### PR DESCRIPTION
**Pull request by sahithibanda01**
Reverts harness/harness-core#53907

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54537)

### CODE REVIEW

**Review by rajatharanganath — APPROVED** [review]

**Comment by sahithibanda01** [comment]
trigger messagecheck

**Comment by sahithibanda01** [comment]
trigger gitleaks

**Comment by sahithibanda01** [comment]
trigger gitleaks

**Comment by sahithibanda01** [comment]
trigger gitleaks

**Pull request merged**
