### PR TITLE
feat: [DEL-5504]: Separating delegate secret decryption

### PR DESCRIPTION
**Pull request by mdmilic**
## Describe your changes
Created multiple new modules to untangle delegate secret decryption and have it as a separate library. 
The only thing that is not separated out is custom secret decryption as it's too hard to get it out of 930-delegate-tasks. Old delegates still bring it in through 930-delegate-tasks and would have no issues. Bijou delegate doesn't have it.

Tested:
* Started CG manager and legacy and immutable delegates (to check that all guice bindings still work)
* Created CG Custom secret manager and added secrets to it
* Created NG GCP KMS Secret Manager 

I performed [Secrets automation run](https://app.harness.io/ng/#/account/vpCkHKsDSxK9_KYfjCTMKA/ci/orgs/QE_Team/projects/platformteam/pipelines/automationbyfeature/executions/cp9na5qJT_qGNGVql85WNA/tests) for this PR. Most of the tests succeed. I'm told the ones failed are because of bad test data, not the code and that it's ok to merge. Also, main thing to test here would be structural changes (e.g. does kryo 
& morphia still work for all secret managers), not behavioral as I didn't change any business logic. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41827)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`maven-manifest-override.txt` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/41827#-NLN2hjxAL4EySMURgxx:-NLN2hjxAL4EySMURgxy:b7v4ssc) ([raw file](https://github.com/harness/harness-core/blob/ebd11c654380799983b47dfe20d24aebce6d6601/maven-manifest-override.txt#L39)):*
> ```help
> org.w3c.dom,@maven//:xml_apis_xml_apis
> com.google.cloud.kms.v1.CryptoKeyName,@maven//:com_google_cloud_google_cloud_kms
> com.google.cloud.kms.v1.DecryptResponse,@maven//:com_google_cloud_google_cloud_kms
> ```

what does this change mean?

**Comment by raghuAtWings** [comment]
*[`890-sm-delegate/src/main/java/io/harness/secrets/noop/NoopSecretsDelegateCacheHelperService.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/41827#-NLN2zRDCUW78clGWVW0:-NLN2zRDCUW78clGWVW1:bd8d7u9) ([raw file](https://github.com/harness/harness-core/blob/ebd11c654380799983b47dfe20d24aebce6d6601/890-sm-delegate/src/main/java/io/harness/secrets/noop/NoopSecretsDelegateCacheHelperService.java#L14)):*
> ```Java
> import java.time.Duration;
> 
> public class NoopSecretsDelegateCacheHelperService implements SecretsDelegateCacheHelperService {
> ```

why do we need this?

**Comment by raghuAtWings** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/serializer/kryo/DelegateTasksKryoRegistrar.java` line 1008 at r2](https://reviewable.io/reviews/harness/harness-core/41827#-NLN39Lh3wrs61YGz9vO:-NLN39Lh3wrs61YGz9vP:b-jioljq) ([raw file](https://github.com/harness/harness-core/blob/85bcb13e1ad91b886edc02d4e84b7de6946c9e00/930-delegate-tasks/src/main/java/io/harness/serializer/kryo/DelegateTasksKryoRegistrar.java#L1008)):*
> ```Java
>     kryo.register(ManifestFile.class, 5539);
>     kryo.register(AWSPrometheusInfo.class, 90001);
>     kryo.register(CustomSecretNGManagerConfig.class, 40114);
> ```

where are these added for legacy delegates?

**Comment by raghuAtWings** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/security/encryption/secretsmanagerconfigs/CustomSecretsManagerConfig.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/41827#-NLN3H5P4JOpzodVfNk2:-NLN3H5P4JOpzodVfNk3:bbj3w2j) ([raw file](https://github.com/harness/harness-core/blob/ebd11c654380799983b47dfe20d24aebce6d6601/930-delegate-tasks/src/main/java/software/wings/security/encryption/secretsmanagerconfigs/CustomSecretsManagerConfig.java#L62)):*
> ```Java
> @FieldNameConstants(innerTypeName = "CustomSecretsManagerConfigKeys")
> public class CustomSecretsManagerConfig
>     extends SecretManagerConfig { // TODO: Marko - make sure this one still Kryo/Morphia (de)serializes
> ```

don't understand this todo

**Comment by raghuAtWings** [comment]
*[`931-delegate-decryption-service/src/java/io/harness/decryption/delegate/module/DelegateDecryptionModule.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/41827#-NLN4MlB74NehZLwCLCQ:-NLN4MlB74NehZLwCLCR:b6ui2dj) ([raw file](https://github.com/harness/harness-core/blob/ebd11c654380799983b47dfe20d24aebce6d6601/931-delegate-decryption-service/src/java/io/harness/decryption/delegate/module/DelegateDecryptionModule.java#L60)):*
> ```Java
>     bind(SecretsDelegateCacheHelperService.class).to(NoopSecretsDelegateCacheHelperService.class);
>     // Needed for configurable secret cache expiery
>     //    bind(DelegateConfigurationServiceProvider.class).to(DelegateConfigurationServiceProviderImpl.class);
> ```

do we need these commented lines?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 31 of 86 files at r1, 122 of 122 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41827)* status: 0 of 1 approvals obtained.

**Review by mdmilic — COMMENTED** [review]
> Reviewed 31 of 86 files at r1, 122 of 122 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41827)* status: 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`maven-manifest-override.txt` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/41827#-NLN2hjxAL4EySMURgxx:-NLQDhYAB9KZgMvRtQfp:b-nggm22) ([raw file](https://github.com/harness/harness-core/blob/ebd11c654380799983b47dfe20d24aebce6d6601/maven-manifest-override.txt#L39)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

what does this change mean?
</blockquote></details>

Sometimes we have a same package existing in multiple dependencies, so build cleaner doesn't know which dep to use (and it uses first one in the list). This is to instruct build cleaner which of the dependencies to use to resolve the particular import. 
In this case I don't even know where did BuildCleaner found the second dep as it wasn't in our workspace and it didn't actually work. 
___
*[`890-sm-delegate/src/main/java/io/harness/secrets/noop/NoopSecretsDelegateCacheHelperService.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/41827#-NLN2zRDCUW78clGWVW0:-NLQEiz2DCmp9xnFuV5o:b-ikgq6j) ([raw file](https://github.com/harness/harness-core/blob/ebd11c654380799983b47dfe20d24aebce6d6601/890-sm-delegate/src/main/java/io/harness/secrets/noop/NoopSecretsDelegateCacheHelperService.java#L14)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need this?
</blockquote></details>

Real cache helper service depends heavily on too many other services for the only purpose to fetch the delegate secret cache TTL from manager config. This is to remove this functionality for Bijou delegate so that I wouldn't need to break all those services. I also think we should get rid of this behavior for other delegates as well and simply use env variables/delegate config file like for everything else. This also adds time to delegate startup as it will try to contact manager, download a file, create properties cache etc... all while creating guice bindings (so during delegate init phase).
___
*[`930-delegate-tasks/src/main/java/software/wings/security/encryption/secretsmanagerconfigs/CustomSecretsManagerConfig.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/41827#-NLN3H5P4JOpzodVfNk2:-NLQG5vo16nFkZK839gl:b-h1itrt) ([raw file](https://github.com/harness/harness-core/blob/ebd11c654380799983b47dfe20d24aebce6d6601/930-delegate-tasks/src/main/java/software/wings/security/encryption/secretsmanagerconfigs/CustomSecretsManagerConfig.java#L62)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

don't understand this todo
</blockquote></details>

Custom Secret Manager is now registered in different registrars (old ones) than all the other secret managers (registered in new modules). This was just for me to make sure to run the tests that all the secret managers including this one can be (de)serialized with existing delegates. Will remove it
___
*[`931-delegate-decryption-service/src/java/io/harness/decryption/delegate/SecretsHandler.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/41827#-NLN4EwM-limZsA9-5lN:-NLQRixa46SOCRrFL-6K:b4rujle) ([raw file](https://github.com/harness/harness-core/blob/ebd11c654380799983b47dfe20d24aebce6d6601/931-delegate-decryption-service/src/java/io/harness/decryption/delegate/SecretsHandler.java#L35)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

is this a test record? why its in production code?
</blockquote></details>

This class is supposed to be an entry point for new secret manager module as a binary (when SM used standalone, not as part of existing delegates). I used it for manual testing to make sure everything is wired properly, all guice bindings are there etc.. java_binary target requires main class, so I will leave the empty class but remove the leftover testing code. 
At the end I didn't want to implement a Dockerfile in this PR as I wasn't sure yet how it should look like. That will be done in a separate PR
___
*[`931-delegate-decryption-service/src/java/io/harness/decryption/delegate/module/DelegateDecryptionModule.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/41827#-NLN4MlB74NehZLwCLCQ:-NLQSXV34CP9lCQG_4Y3:blpb1ax) ([raw file](https://github.com/harness/harness-core/blob/ebd11c654380799983b47dfe20d24aebce6d6601/931-delegate-decryption-service/src/java/io/harness/decryption/delegate/module/DelegateDecryptionModule.java#L60)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

do we need these commented lines?
</blockquote></details>

No, will remove. I used those as a reminder why these bindings exist, but eventually gave up on trying to decouple them from monolith and implemented NoopSecretsDelegateCacheHelperService.class for bijou delegate.

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41827)* status: 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/serializer/kryo/DelegateTasksKryoRegistrar.java` line 1008 at r2](https://reviewable.io/reviews/harness/harness-core/41827#-NLN39Lh3wrs61YGz9vO:-NLQTfdx2Unt2tBfJKKn:br9hf3r) ([raw file](https://github.com/harness/harness-core/blob/85bcb13e1ad91b886edc02d4e84b7de6946c9e00/930-delegate-tasks/src/main/java/io/harness/serializer/kryo/DelegateTasksKryoRegistrar.java#L1008)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

where are these added for legacy delegates?
</blockquote></details>

hey are in the SecretConfigKryoRegistrar.java (which lives in the new module along with the actual classes). Legacy delegates (and all other services that were using these) are now also importing this new KryoRegistrar e.g. for this particular one in 930-delegate-tasks/src/main/java/io/harness/serializer/DelegateTaskRegistrars.java

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41827)* status: 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/serializer/kryo/DelegateTasksKryoRegistrar.java` line 1008 at r2](https://reviewable.io/reviews/harness/harness-core/41827#-NLN39Lh3wrs61YGz9vO:-NLQU82QBnWbh7oZ2coM:bqgewhw) ([raw file](https://github.com/harness/harness-core/blob/85bcb13e1ad91b886edc02d4e84b7de6946c9e00/930-delegate-tasks/src/main/java/io/harness/serializer/kryo/DelegateTasksKryoRegistrar.java#L1008)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

hey are in the SecretConfigKryoRegistrar.java (which lives in the new module along with the actual classes). Legacy delegates (and all other services that were using these) are now also importing this new KryoRegistrar e.g. for this particular one in 930-delegate-tasks/src/main/java/io/harness/serializer/DelegateTaskRegistrars.java
</blockquote></details>

btw the same goes for morphia registrars

**Comment by mdmilic** [comment]
trigger feature-build

**Comment by mdmilic** [comment]
trigger smartchecks

**Comment by mdmilic** [comment]
trigger ft1, ft2

**Comment by mdmilic** [comment]
trigger ft1

**Comment by mdmilic** [comment]
trigger ft2

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 26 of 86 files at r1, 110 of 122 files at r2, 5 of 9 files at r3, 7 of 7 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41827#-:-NLwo2YU2NZLzhlWJNrt:bnfp4nl)* status: 6. unresolved discussions.

**Review by gn-harness — APPROVED** [review]
> Reviewed 26 of 86 files at r1, 110 of 122 files at r2, 5 of 9 files at r3, 7 of 7 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41827)* status: 6. unresolved discussions.

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 5 of 9 files at r3, 7 of 7 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41827)* status: :shipit: complete! ✓

**Review by gn-harness — APPROVED** [review]
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41827)* status: :shipit: complete! ✓

**Review by reetika04 — APPROVED** [review]
> Reviewed 23 of 86 files at r1, 107 of 122 files at r2, 5 of 9 files at r3, 7 of 7 files at r4, 5 of 7 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41827)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 23 of 86 files at r1, 107 of 122 files at r2, 5 of 9 files at r3, 7 of 7 files at r4, 5 of 7 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41827)* status: :shipit: complete! ✓

**Pull request merged**
