### PR TITLE
[techdebt]: [PIE-2728]: Common code extraction and tests for Retry methods

### PR DESCRIPTION
**Pull request by namanvermah**
Prereq for supporting retry of stage executions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30935)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger messagecheck

**Review by prashantsharma04 — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30935)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30935#-:-Mw_TwoSD1izUgOf7o34:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30935)* status: :shipit: complete! ✓

**Pull request merged**
