### PR TITLE
feat: [PL-24425]: Adding NotNull to Access Control DTOs

### PR DESCRIPTION
**Pull request by reetika04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32085)

### CODE REVIEW

**Comment by reetika04** [comment]
trigger messagecheck

**Review by karansiwach360 — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32085)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32085#-:-N-1mc_GEMux7bezhhgl:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by karansiwach360 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32085)* status: :shipit: complete! ✓

**Pull request merged**
