### PR TITLE
feat: [CDS-58931] upgrade helm from 3.8 to 3.12 for immutable delegate

### PR DESCRIPTION
**Pull request by alebuh**
## Describe your changes
Upgrade the helm version for immutable delegate from 3.8 to 3.12
As the immutable delegate will no longer have helm 3.1.2 or 3.8.0 binaries, we should return version 3.12.0 instead
This logic can be removed when we deprecate Helm V2 from the immutable delegate and end with only one version of Helm in it (this version will override all others when we export it to the env path). 

The binary is uploaded to the GCP bucket:
https://console.cloud.google.com/storage/browser/harness-prod-public/public/shared/tools/helm/release/v3.12.0?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=prod-setup-205416&prefix=&forceOnObjectsSortingFiltering=false

Test:
When FF HELM_VERSION_3_8_0 is disabled legacy delegate uses version v3.1.2
When FF HELM_VERSION_3_8_0 is enabled legacy delegate uses version v3.8.0
When FF HELM_VERSION_3_8_0 is disabled immutable delegate uses version v3.12.0
When FF HELM_VERSION_3_8_0 is enabled immutable delegate uses version v3.12.0

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50683)

### CODE REVIEW

**Comment by alebuh** [comment]
trigger publish-delegate

**Comment by alebuh** [comment]
trigger feature-build

**Comment by alebuh** [comment]
trigger uts

**Review by abosii-harness — APPROVED** [review]

**Review by bharatgoelharness — CHANGES_REQUESTED** [review]
why this is not updated ? harness-core/dockerization/delegate/scripts/client_tools.sh

**Comment by bharatgoelharness** [comment]
> why this is not updated ? harness-core/dockerization/delegate/scripts/client_tools.sh

ignore this

**Comment by alebuh** [comment]
trigger messagecheck, review

**Pull request merged**
