### PR TITLE
fix: [PIE-4661]: Donot allow execution for draft pipelines

### PR DESCRIPTION
**Pull request by smjt-h**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35907)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35907)

**Review by namanvermah — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35907#-:-N8Rw3YCBq3SAcpiwoWe:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35907)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/35907#-N8Rwns94bg85HYEv3EF:-N8Rwns94bg85HYEv3EG:b-w5rdiy) ([raw file](https://github.com/harness/harness-core/blob/13e1b739dfc38061dbc1aa02413d52656a4556eb/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java#L113)):*
> ```Java
>         executionHelper.fetchPipelineEntity(accountId, orgIdentifier, projectIdentifier, pipelineIdentifier);
>     if (pipelineEntity.getIsDraft() != null && pipelineEntity.getIsDraft()) {
>       throw new InvalidRequestException("Cannot execute a Draft Pipeline");
> ```

can you add pipeline and project identifier and other metadata



_Code quote:_
```Java
Cannot execute a Draft Pipeline
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35907)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/35907#-N8Rwns94bg85HYEv3EF:-N8TACFX3JyZv7_N7Axp:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/13e1b739dfc38061dbc1aa02413d52656a4556eb/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java#L113)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you add pipeline and project identifier and other metadata
</blockquote></details>

done

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35907)* status: :shipit: complete! ✓

**Pull request merged**
