### PR TITLE
[fix]: [PL-32038]: Fixing NullPointerException in user invite flow

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
Fixing NullPointerException in user invite flow. Role bindings is not required field in user request. If we do not pass role bindings in user request it is coming as null. As part of this change we are updating role binding getter to return empty list if it is null.

Tests:
- Api call with null reolebindings working fine
Screenshot 2023-05-05 at 7 02 36 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46930)

### CODE REVIEW

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46930)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/user/AddUsersDTO.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/46930#-NTwQtixEHfNef5Is_bD:-NTwQtixEHfNef5Is_bE:bsqocsb) ([raw file](https://github.com/harness/harness-core/blob/1718242dd276fdcb6715c0ad4eb510dff2aeda4d/960-ng-core-beans/src/main/java/io/harness/ng/core/user/AddUsersDTO.java#L35)):*
> ```Java
> public class AddUsersDTO {
>   @ApiModelProperty(required = true) @NotEmpty @Size(max = 100) List<String> emails;
>   @NotNull List<RoleBinding> roleBindings;
> ```

@ashishsanodia-harness   Can we not assign default empty array instead of making of adding NotNull?
Because role bindings is optional now.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/user/AddUsersDTO.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/46930#-NTwQtixEHfNef5Is_bD:-NUgAqtW2GmWrG2zyuIM:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/1718242dd276fdcb6715c0ad4eb510dff2aeda4d/960-ng-core-beans/src/main/java/io/harness/ng/core/user/AddUsersDTO.java#L35)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

@ashishsanodia-harness   Can we not assign default empty array instead of making of adding NotNull?
Because role bindings is optional now.
</blockquote></details>

Fixed

**Review by ankit-harness — APPROVED** [review]

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46930#-:-NUghBBS41YhVPztzEjJ:bnfp4nl)* status: 1 file(s) to review.

**Pull request merged**
