### PR TITLE
feat: [CDS-83009]: Add Spec Plan Creator v1

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** Introduce a SpecPlanCreator for v1 to create a plan node for spec inside pipeline, stages, and group to support the expressions like <+stage.spec.steps.step_id.name>

**Testing:** Tested that expressions starting with <+stages.spec...> and <+stages.stage_id.spec..> are working now in v1 yamls.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54827)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger uts

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54827)* status: 13 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PipelineServiceInfoDecorator.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/54827#-NiKGDLj2kdMCZNY-vaR:-NiKGDLj2kdMCZNY-vaS:bxqfjx2) ([raw file](https://github.com/harness/harness-core/blob/f3ff5c7d78b96b7f76cd62f5c1ca95bde8ac4ffc/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PipelineServiceInfoDecorator.java#L42)):*
> ```Java
>     planCreators.add(new ParallelPlanCreator());
>     planCreators.add(new ParallelPlanCreatorV1());
>     planCreators.add(new StepsPlanCreatorV1());
> ```

it is added here
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PipelineServiceInfoDecorator.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/54827#-NiKFDtV-K8QxSpFq-D5:-NiKG9kq-OuiXB97EnXh:b4tww36) ([raw file](https://github.com/harness/harness-core/blob/f006c54e7be076accb5b2579a02b8a29eaeaeb4d/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PipelineServiceInfoDecorator.java#L43)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

shouldnt both plan creator to be there
</blockquote></details>

StepsPlanCreator was added twice
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/group/GroupStepParametersV1.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/54827#-NiKFOKTCI1vM5lbG8TU:-NiKGHuK5u8PoXUzLffy:b-l59eol) ([raw file](https://github.com/harness/harness-core/blob/f3ff5c7d78b96b7f76cd62f5c1ca95bde8ac4ffc/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/group/GroupStepParametersV1.java#L35)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why to introduce spec? just add childNode directly, if it has spec then group.spec.steps.s1 will not work
</blockquote></details>

by adding spec only this expression is working

**Comment by brijeshdhakar** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/group/GroupStepParametersV1.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/54827#-NiKFOKTCI1vM5lbG8TU:-NiLAniNEVQqekwouBwF:b-blvpgp) ([raw file](https://github.com/harness/harness-core/blob/f3ff5c7d78b96b7f76cd62f5c1ca95bde8ac4ffc/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/group/GroupStepParametersV1.java#L35)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

by adding spec only this expression is working
</blockquote></details>

I think it should work without adding this GroupSpecParameters. @shalini-agr we can check this once why the expression is not resolving without this.

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 5 of 5 files at r2, 1 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54827)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54827)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/group/GroupStepParametersV1.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/54827#-NiKFOKTCI1vM5lbG8TU:-NiXsicD2aaqUhcJmcIv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3ff5c7d78b96b7f76cd62f5c1ca95bde8ac4ffc/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/group/GroupStepParametersV1.java#L35)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

I think it should work without adding this GroupSpecParameters. @shalini-agr we can check this once why the expression is not resolving without this.
</blockquote></details>

Done.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54827)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54827)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]

**Pull request merged**
