### PR TITLE
feat: [CDS-81131]: Remove resume event for async and async chain execution …

### PR DESCRIPTION
**Pull request by Y0709**
…modes

Context -- For Async and Async chain step, there is a race condition that is happening because of two sdk response events being fired. One is addExecutableResponse and other is resumeNodeExecution.
The race condition is as follows:
A step adds addExecutionResponse in sdkResponseEventQueue
The step finishes fast and at the same time emits the resumeNodeExecution event.
The resumeMetadata requires executableResponse to be a part of it and since the first step did not succeed, we might run into a potential NPE.

To avoid this ee would start storing the executableResponse too as part of our callback in AsyncExecutable and AsyncChainExecutable
In our AsyncResumeCallback, we will directly call the resume of the step rather than calling the event.

Testing -- 
Tested normal flow with async or async chain strategy type step
Tested with wait and approval steps which are async strategy type step
Tested using blue green deployment step which uses Async chain strategy steps

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54414)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54414)* status: 6 file(s) to review. 0 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger commonchecks

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54414)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/AsyncSdkResumeCallback.java` line 69 at r5](https://reviewable.io/reviews/harness/harness-core/54414#-NhaMvdxAV7j8DaI75hz:-NhaMvdxAV7j8DaI75i-:b-iqvi0v) ([raw file](https://github.com/harness/harness-core/blob/4a6ef6ac313711620a2882fb936d46eab1f5cb74/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/AsyncSdkResumeCallback.java#L69)):*
> ```Java
>         log.info("AsyncSdkResumeCallback notify is called for ambiance with nodeExecutionId {}",
>             AmbianceUtils.obtainCurrentRuntimeId(ambiance));
>         if (!AmbianceUtils.checkIfFeatureFlagEnabled(ambiance, "CDS_REMOVE_RESUME_EVENT_FOR_ASYNC_AND_ASYNCCHAIN_MODE")
> ```

use a constant



_Code quote:_
```Java
"CDS_REMOVE_RESUME_EVENT_FOR_ASYNC_AND_ASYNCCHAIN_MODE"
```
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/AsyncSdkResumeCallback.java` line 78 at r5](https://reviewable.io/reviews/harness/harness-core/54414#-NhaN-Wg64F6L4mpk7Yz:-NhaN-Wh30575m0DH9C4:bascg4t) ([raw file](https://github.com/harness/harness-core/blob/4a6ef6ac313711620a2882fb936d46eab1f5cb74/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/AsyncSdkResumeCallback.java#L78)):*
> ```Java
> 
>           NodeResumeEvent.Builder resumeEventBuilder =
>               NodeResumeEvent.newBuilder()
> ```

can we divide if condition as a method, and content inside if and else also as methods?

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54414)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/AsyncSdkResumeCallback.java` line 69 at r5](https://reviewable.io/reviews/harness/harness-core/54414#-NhaMvdxAV7j8DaI75hz:-NhaR0b3-6NXczxMUCEe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4a6ef6ac313711620a2882fb936d46eab1f5cb74/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/AsyncSdkResumeCallback.java#L69)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use a constant
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/AsyncSdkResumeCallback.java` line 78 at r5](https://reviewable.io/reviews/harness/harness-core/54414#-NhaN-Wg64F6L4mpk7Yz:-NhaR1846z_LgQ3UXiQk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4a6ef6ac313711620a2882fb936d46eab1f5cb74/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/AsyncSdkResumeCallback.java#L78)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we divide if condition as a method, and content inside if and else also as methods?
</blockquote></details>

Done.

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54414)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/AsyncSdkResumeCallback.java` line 85 at r7](https://reviewable.io/reviews/harness/harness-core/54414#-Nhav1t01AmDFywEHcoF:-Nhav1t01AmDFywEHcoG:b-mznx82) ([raw file](https://github.com/harness/harness-core/blob/cab2c9e6ca76d0d629695a7d8f21c7fa4625cae2/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/AsyncSdkResumeCallback.java#L85)):*
> ```Java
>     if (!AmbianceUtils.checkIfFeatureFlagEnabled(ambiance, CDS_REMOVE_RESUME_EVENT_FOR_ASYNC_AND_ASYNCCHAIN_MODE)
>         || executableResponseBytes == null || AmbianceUtils.obtainNodeType(ambiance) == null
>         || Objects.equals(AmbianceUtils.obtainNodeType(ambiance), "IDENTITY_PLAN_NODE")) {
> ```

we should abstact into another method



_Code quote:_
```Java
    if (!AmbianceUtils.checkIfFeatureFlagEnabled(ambiance, CDS_REMOVE_RESUME_EVENT_FOR_ASYNC_AND_ASYNCCHAIN_MODE)
        || executableResponseBytes == null || AmbianceUtils.obtainNodeType(ambiance) == null
        || Objects.equals(AmbianceUtils.obtainNodeType(ambiance), "IDENTITY_PLAN_NODE")) {
```

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/AsyncSdkResumeCallback.java` line 49 at r7](https://reviewable.io/reviews/harness/harness-core/54414#-Nhavp9w3AChMcXk4XVj:-Nhavp9w3AChMcXk4XVk:b-wkj2ke) ([raw file](https://github.com/harness/harness-core/blob/cab2c9e6ca76d0d629695a7d8f21c7fa4625cae2/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/AsyncSdkResumeCallback.java#L49)):*
> ```Java
>   byte[] ambianceBytes;
>   byte[] executableResponseBytes;
>   ExecutionMode mode;
> ```

nit: can we remove mode?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54414)* status: 1 file(s) to review. 2 change requests. 0 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54414)* status: 4 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/AsyncSdkResumeCallback.java` line 110 at r8](https://reviewable.io/reviews/harness/harness-core/54414#-NhbJpaW63SqW2YwB-1w:-NhbJpaW63SqW2YwB-1x:bpm7621) ([raw file](https://github.com/harness/harness-core/blob/ebb5b51751576ba8331b5d48b13173825ddf3b62/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/AsyncSdkResumeCallback.java#L110)):*
> ```Java
>     return !AmbianceUtils.checkIfFeatureFlagEnabled(ambiance, CDS_REMOVE_RESUME_EVENT_FOR_ASYNC_AND_ASYNCCHAIN_MODE)
>         || executableResponseBytes == null || AmbianceUtils.obtainNodeType(ambiance) == null
>         || Objects.equals(AmbianceUtils.obtainNodeType(ambiance), "IDENTITY_PLAN_NODE");
> ```

why for other conditions we should return true? and not continue? if earlier also they were true, we were sending event, shouldn't now that go via normal flow?



_Code quote:_
```Java
        || executableResponseBytes == null || AmbianceUtils.obtainNodeType(ambiance) == null
        || Objects.equals(AmbianceUtils.obtainNodeType(ambiance), "IDENTITY_PLAN_NODE");
```

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54414)* status: 5 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/AsyncSdkResumeCallback.java` line 110 at r8](https://reviewable.io/reviews/harness/harness-core/54414#-NhbJpaW63SqW2YwB-1w:-Nhfo72g-LKt0Dr7l-PG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ebb5b51751576ba8331b5d48b13173825ddf3b62/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/AsyncSdkResumeCallback.java#L110)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why for other conditions we should return true? and not continue? if earlier also they were true, we were sending event, shouldn't now that go via normal flow?
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54414)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54414)* status: :shipit: complete! ✓

**Comment by Y0709** [comment]
trigger review

**Pull request merged**
