### PR TITLE
feat: [CVS-4177]: prometheus basic auth

### PR DESCRIPTION
**Pull request by anjanBalgovind**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30537)

### CODE REVIEW

**Comment by anjanBalgovind** [comment]
trigger ft1

**Comment by anjanBalgovind** [comment]
trigger ti1

**Comment by anjanBalgovind** [comment]
trigger ti1

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 11 files at r1, 5 of 6 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30537#-:-MvX-qkvBfWn38YWWEjH:bnfp4nl)* status: :shipit: complete! ✓

___
*[400-rest/src/main/java/software/wings/service/impl/analysis/ContinuousVerificationServiceImpl.java, line 2037 at r3](https://reviewable.io/reviews/harness/harness-core/30537#-MvWrmXx-Ap_xMGycSxl:-MvWrmXx-Ap_xMGycSxm:b8l3q4j) ([raw file](https://github.com/harness/harness-core/blob/f5956ce39bbd1e48e7d285d14a5bf0c692feda1d/400-rest/src/main/java/software/wings/service/impl/analysis/ContinuousVerificationServiceImpl.java#L2037)):*
> ```Java
>             .serviceId(config.getServiceId())
>             .startTime(startTime)
>             .headers(prometheusConfig.generateHeaders())
> ```

can we add support for preprocessor function instead of have some specific contract based on this variable.
Something like
___
*[400-rest/src/test/java/software/wings/service/impl/analysis/APMDelegateServiceTest.java, line 146 at r3](https://reviewable.io/reviews/harness/harness-core/30537#-MvWoYP1-0rE4PKPiYNR:-MvWoYP1-0rE4PKPiYNS:b-g0mm2) ([raw file](https://github.com/harness/harness-core/blob/f5956ce39bbd1e48e7d285d14a5bf0c692feda1d/400-rest/src/test/java/software/wings/service/impl/analysis/APMDelegateServiceTest.java#L146)):*
> ```Java
> 
>   @Test
>   @Owner(developers = PRAVEEN)
> ```

nit: owner?

**Review by praveensugavanam — APPROVED** [review]
> Reviewed 4 of 11 files at r1, 5 of 6 files at r2, 2 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30537)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 5 of 11 files at r1, 5 of 6 files at r2, 4 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30537)* status: :shipit: complete! ✓

**Pull request merged**
