### PR TITLE
feat: [PL-22132]: Add custom field ldap

### PR DESCRIPTION
**Pull request by ujjawal-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30261)

### CODE REVIEW

**Comment by piyush-harness** [comment]
___
*[400-rest/src/main/java/software/wings/beans/sso/LdapUserSettings.java, line 36 at r1](https://reviewable.io/reviews/harness/harness-core/30261#-MuJxzWIAChXkz7vI_Aj:-MuJxzWIAChXkz7vI_Ak:b-9mclhy) ([raw file](https://github.com/harness/harness-core/blob/a48b8a73cf43a2e950ce457561c108d1a335f7cb/400-rest/src/main/java/software/wings/beans/sso/LdapUserSettings.java#L36)):*
> ```Java
>   @JsonProperty @NotBlank String searchFilter = LdapConstants.DEFAULT_USER_SEARCH_FILTER;
>   @JsonProperty @NotBlank String uidAttr = "uid";
>   @JsonProperty @NotBlank String samlAccountNameAttr = "samAccountName";
> ```

Fix the name

**Comment by piyush-harness** [comment]
___
*[400-rest/src/main/java/software/wings/helpers/ext/ldap/LdapUserConfig.java, line 21 at r1](https://reviewable.io/reviews/harness/harness-core/30261#-MuJy9w0-bqSvv-Pj70E:-MuJy9w0-bqSvv-Pj70F:btqkuzf) ([raw file](https://github.com/harness/harness-core/blob/a48b8a73cf43a2e950ce457561c108d1a335f7cb/400-rest/src/main/java/software/wings/helpers/ext/ldap/LdapUserConfig.java#L21)):*
> ```Java
>   String getUidAttr();
> 
>   String getSamlAccountNameAttr();
> ```

Fix name

**Comment by ujjawal-harness** [comment]
trigger messagecheck

**Comment by ujjawal-harness** [comment]
trigger buildnum

**Review by piyush-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30261)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
:lgtm:

**Review by avinashmadhwani02 — APPROVED** [review]

**Review by piyush-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30261)* status: 5 file(s) to review.

**Comment by piyush-harness** [comment]
:lgtm:

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30261)* status: :shipit: complete! ✓

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30261)* status: 3 file(s) to review.

**Review by piyush-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30261#-:-MuKbY1s4PXAlcyonEL1:bnfp4nl)* status: 3 file(s) to review.

**Comment by piyush-harness** [comment]
:lgtm:

**Pull request merged**
