### PR TITLE
fix: [CVS-9178]: passing metric identifier as metric name to LE

### PR DESCRIPTION
**Pull request by kanhaiyarat**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31182)

### CODE REVIEW

**Comment by kanhaiyarat** [comment]
Screenshot 2022-03-04 at 1 55 47 PM
Screenshot 2022-03-04 at 1 56 30 PM
Screenshot 2022-03-04 at 2 17 47 PM
Screenshot 2022-03-04 at 2 17 57 PM
Screenshot 2022-03-04 at 2 33 14 PM
Screenshot 2022-03-04 at 1 56 47 PM
Screenshot 2022-03-04 at 2 32 41 PM

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31182)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/beans/ServiceGuardTxnMetricAnalysisDataDTO.java, line 42 at r1](https://reviewable.io/reviews/harness/harness-core/31182#-MxJbvHnAcYlWgsw7Bf4:-MxJbvHo4c2fz5ZvBEp2:b-dgdg4u) ([raw file](https://github.com/harness/harness-core/blob/749193828d86009a3d8d5a8df464c1b07ea5a879/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/beans/ServiceGuardTxnMetricAnalysisDataDTO.java#L42)):*
> ```Java
>   @JsonIgnoreProperties(ignoreUnknown = true)
>   public static class MetricSumDTO {
>     private String metricName;
> ```

I think it is better to use @JsonProperity with metricName and keep the field name as identifier?
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/beans/TimeSeriesAnomaliesDTO.java, line 26 at r1](https://reviewable.io/reviews/harness/harness-core/31182#-MxJcIu56HliRR_ILdiO:-MxJcIu56HliRR_ILdiP:b-5h08c7) ([raw file](https://github.com/harness/harness-core/blob/749193828d86009a3d8d5a8df464c1b07ea5a879/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/beans/TimeSeriesAnomaliesDTO.java#L26)):*
> ```Java
> public class TimeSeriesAnomaliesDTO {
>   private String transactionName;
>   private String metricName;
> ```

same here.

**Comment by kanhaiyarat** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Review by kanhaiyarat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31182)* status: 13 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/beans/ServiceGuardTxnMetricAnalysisDataDTO.java, line 42 at r1](https://reviewable.io/reviews/harness/harness-core/31182#-MxJbvHnAcYlWgsw7Bf4:-MxYfXVR7cEI0bj1TwIC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/749193828d86009a3d8d5a8df464c1b07ea5a879/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/beans/ServiceGuardTxnMetricAnalysisDataDTO.java#L42)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

I think it is better to use @JsonProperity with metricName and keep the field name as identifier?
</blockquote></details>

Done.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/beans/TimeSeriesAnomaliesDTO.java, line 26 at r1](https://reviewable.io/reviews/harness/harness-core/31182#-MxJcIu56HliRR_ILdiO:-MxYfX2H7hUVkxZYrHPq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/749193828d86009a3d8d5a8df464c1b07ea5a879/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/beans/TimeSeriesAnomaliesDTO.java#L26)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

same here.
</blockquote></details>

Done.

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31182)* status: :shipit: complete! ✓

**Pull request merged**
