### PR TITLE
fix: [PLG-1821] : Add try-catch to unblock the subsequent migrations if the current request fails

### PR DESCRIPTION
**Pull request by neelam-harness**
## Describe your changes
\Add try-catch to unblock the subsequent migrations if the current request fails.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41713)

### CODE REVIEW

**Review by allenthom — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41713)* status: :shipit: complete! ✓

**Review by pranil-harness — APPROVED** [review]

**Review by hitesharinga — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41713)* status: :shipit: complete! ✓

**Comment by allenthom** [comment]
trigger messagecheck

**Comment by allenthom** [comment]
trigger messagecheck

**Comment by neelam-harness** [comment]
trigger checkstylecodeformat

**Comment by kapilgarg1996** [comment]
this migration should be part of NG migrations and should run in ng-manager because it uses NG data to modify account field.

**Review by pranil-harness — APPROVED** [review]

**Review by hitesharinga — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41713)* status: 1 file(s) to review.

**Review by allenthom — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41713)* status: 1 file(s) to review.

**Review by kapilgarg1996 — CHANGES_REQUESTED** [review]
shouldn't this migration be part of NG migrations and should run in ng-manager because it uses NG data to modify account field.

**Review by neelam-harness — COMMENTED** [review]
we are basically updating the CG database based on the data collected by NG database so i think we can perform the migration in CG even though the data is being collected by NG. I definitely agree with you though in terms of respective migrations should be handled accordingly in NG and CG.  
In the short term however, this erroneous state is blocking the subsequent migrations from progressing and hence adding the try-catch shall alleviate the issue. and we can plan better for the long term fix. 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41713#-:-NJgw1HM2dt4S7DOLY0Z:b-lpftyx)* status: :shipit: complete! ✓

**Pull request merged**
