### PR TITLE
[fix]: [PL-43966]: Adding internal api to return scope info based on unique ids

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
Adding internal api to return scope info based on unique ids

Tests:

- Scopeinfo client is returning expected response for this api call.
- Validated API response using curl
```
% curl -X GET 'http://localhost:7457/scope-info/multi?accountIdentifier=kmpySmUISimoRrJL6NL73w' \
--header 'Authorization: <token>' \
--header 'Content-Type: application/json' \
--data '[
    "ZJ5ufmGqTbSZYG57TKCCXw","kmpySmUISimoRrJL6NL73w", "IauG-cG2RQybrVziafX_uQ", "invalid-unique-id"
]'| jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   785  100   681  100   104  70635  10787 --:--:-- --:--:-- --:--:-- 87222
{
  "status": "SUCCESS",
  "data": {
    "invalid-unique-id": null,
    "ZJ5ufmGqTbSZYG57TKCCXw": {
      "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
      "orgIdentifier": "default",
      "projectIdentifier": "default_project",
      "scopeType": "PROJECT",
      "uniqueId": "ZJ5ufmGqTbSZYG57TKCCXw"
    },
    "kmpySmUISimoRrJL6NL73w": {
      "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
      "orgIdentifier": null,
      "projectIdentifier": null,
      "scopeType": "ACCOUNT",
      "uniqueId": "kmpySmUISimoRrJL6NL73w"
    },
    "IauG-cG2RQybrVziafX_uQ": {
      "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
      "orgIdentifier": "default",
      "projectIdentifier": null,
      "scopeType": "ORGANIZATION",
      "uniqueId": "IauG-cG2RQybrVziafX_uQ"
    }
  },
  "metaData": null,
  "correlationId": "bdeb8c2a-9c85-4e89-b48f-b13d19626e4d"
}
```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57414)

### CODE REVIEW

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 12 of 12 files at r1, 5 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57414)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57414)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 12 files at r1, 3 of 5 files at r2, 2 of 4 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57414)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 417 at r4](https://reviewable.io/reviews/harness/harness-core/57414#-NnsAOiGEfr1HicAf7Kz:-NnsAOiGEfr1HicAf7L-:b-mpkbyv) ([raw file](https://github.com/harness/harness-core/blob/efaad2488e7ae41464945559573a889ca2da9d01/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L417)):*
> ```Java
>               String.format("Organization with identifier [%s] does not exist in the specified scope", identifier));
>         }
>         scopeInfoCache.remove(
> ```

Can we move this to the top of this method
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoHelper.java` line 56 at r4](https://reviewable.io/reviews/harness/harness-core/57414#-NnsAdqa2QkI27YQQC44:-NnsAdqb2kIzbPxiksjS:b-6nn29r) ([raw file](https://github.com/harness/harness-core/blob/efaad2488e7ae41464945559573a889ca2da9d01/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoHelper.java#L56)):*
> ```Java
>   }
> 
>   String getScopeInfoUniqueIdCacheKey(final String accountIdentifier, final String uniqueId) {
> ```

Lets discuss this

**Review by pbarapatre10 — DISMISSED** [review]
LGTM

**Review by pbarapatre10 — DISMISSED** [review]

**Comment by ashishsanodia-harness** [comment]
PR merged in harness-code [https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/module/code/orgs/HarnessHCRInternalUAT/projects/Harness_Code/repos/harness-core/pulls/418](https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/module/code/orgs/HarnessHCRInternalUAT/projects/Harness_Code/repos/harness-core/pulls/418)

Closing this one

**Pull request closed without merging**
