### PR TITLE
[feat]: [PIE-9137]: Fetch commitId when update file is successful without commitId

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added code to fetch latest commitId of the file when update file is successful but commitId is not present
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45514)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 201 at r1](https://reviewable.io/reviews/harness/harness-core/45514#-NRCyOq838X-wBrFWMn6:-NRCyOq838X-wBrFWMn7:b5srq6m) ([raw file](https://github.com/harness/harness-core/blob/89bc505a48f48e57037c4f943d968744ac122344/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L201)):*
> ```Java
>       if (isNotEmpty(getLatestCommitOnFileResponse.getError())) {
>         return UpdateFileResponse.newBuilder()
>             .setStatus(Constants.SCM_INTERNAL_SERVER_ERROR_CODE)
> ```

can we check how do we handle it for other usages? I don't think it should be internal server error in this case.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45514)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 201 at r1](https://reviewable.io/reviews/harness/harness-core/45514#-NRCyOq838X-wBrFWMn6:-NRD9_wm7Clj3vql8zK2:b-8gmfh8) ([raw file](https://github.com/harness/harness-core/blob/89bc505a48f48e57037c4f943d968744ac122344/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L201)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we check how do we handle it for other usages? I don't think it should be internal server error in this case.
</blockquote></details>

we are doing similar handling for create, update and get, we have this comment
   // In case commit id is empty for any reason, we treat this as an error case even if file got created on git

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45514)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 201 at r1](https://reviewable.io/reviews/harness/harness-core/45514#-NRCyOq838X-wBrFWMn6:-NRHGhE73xP1pSWb0BHq:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/89bc505a48f48e57037c4f943d968744ac122344/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L201)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Yes, coz that was not expected. This is a genuine scenario where we got error from SCM service. So, this should be treated how we treat what happens if we got error in other SCM APIs.
</blockquote></details>

done

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 201 at r1](https://reviewable.io/reviews/harness/harness-core/45514#-NRCyOq838X-wBrFWMn6:-NRHHHxq9OxU_jIEIUKK:b-qkx2sp) ([raw file](https://github.com/harness/harness-core/blob/89bc505a48f48e57037c4f943d968744ac122344/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L201)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

done
</blockquote></details>

Handling is fine, but can we use it as a constant from some class rather than hardcoded string?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45514)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 201 at r1](https://reviewable.io/reviews/harness/harness-core/45514#-NRCyOq838X-wBrFWMn6:-NRHItCRC3870vNZoypu:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/89bc505a48f48e57037c4f943d968744ac122344/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L201)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Handling is fine, but can we use it as a constant from some class rather than hardcoded string?
</blockquote></details>

done



_Code quote:_
```Java
SCM_INTERNAL_SERVER_ERROR_CODE
```

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45514)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 201 at r1](https://reviewable.io/reviews/harness/harness-core/45514#-NRCyOq838X-wBrFWMn6:-NRHKGxh2_GSNPFN227r:b-e36n8y) ([raw file](https://github.com/harness/harness-core/blob/89bc505a48f48e57037c4f943d968744ac122344/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L201)):*
> SCM_INTERNAL_SERVER_ERROR_CODE
added this above line by mistake, pls ignore

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/constants/Constants.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/45514#-NRI69x5BrzuxFuy4dP9:-NRI69x5BrzuxFuy4dPA:bmn2ykd) ([raw file](https://github.com/harness/harness-core/blob/ba1aab8ee421d0d60ecfc49c7aff14fe734e3f98/952-scm-java-client/src/main/java/io/harness/constants/Constants.java#L37)):*
> ```Java
>   int SCM_BAD_RESPONSE_ERROR_CODE = 500;
>   int HTTP_SUCCESS_STATUS_CODE = 200;
>   int SCM_COMMIT_ID_NOT_FOUND = 400;
> ```

The HTTP code shouldn't be specific to a use-case. What if next time I have a use-case where I want to use 400, will we create another Constant?

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45514)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45514)* status: :shipit: complete! ✓

**Pull request merged**
