### PR TITLE
fix: [CDS-51140]: Iterator framework running without any sleeps fix

### PR DESCRIPTION
**Pull request by abhinavmittal-harness**
…ro so that it doesn't keep running without any breaks

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43673)

### CODE REVIEW

**Comment by abhinavmittal-harness** [comment]
trigger messagecheck

**Review by Raghav-Murali — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43673)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java` line 225 at r2](https://reviewable.io/reviews/harness/harness-core/43673#-NNuQt9j33q0bpRIY416:-NNuQt9j33q0bpRIY417:bu4hau3) ([raw file](https://github.com/harness/harness-core/blob/c09b4f71bc2c61ab35a7191a72a602bb93b0a898/960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java#L225)):*
> ```Java
>     Long nextIteration = next.obtainNextIteration(fieldName);
>     if (nextIteration == null) {
>       return maximumDelayForCheck == null ? targetInterval : maximumDelayForCheck;
> ```

As we discussed on call - this will be hit only for records that are being picked for the very first time whose nextIteration field is not yet set. There will be only fewer instances of those so I'm not sure if this alone will help in reducing the CPU usage. We should look into trying these iterators with the new Redis mode and see if it helps.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43673)* status: Some of the checks are too old. 2 file(s) to review.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43673)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by Y0709 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43673)* status: :shipit: complete! ✓

**Pull request merged**
