### PR TITLE
feat: [PIE-7782]: add support for using when condition as runtime input

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes
Add Support for using when conditions as runtime input in steps, stages, and step groups.
**Testing:** Tested manually locally by creating pipelines with when conditions as runtime input.

Recording of the new behavior:

https://user-images.githubusercontent.com/97503816/214310196-bc19b4b0-b3e6-4256-9309-80bb7008d8fc.mov

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42934)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/test/java/io/harness/cdng/creator/variables/HelmDeployStepVariableCreatorTest.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/42934#-NMnBY0HDdpbYaQtchre:-NMnBY0HDdpbYaQtchrf:b6svmtb) ([raw file](https://github.com/harness/harness-core/blob/65ee019a240127e693a78a1371e4c99b7b0c53bc/125-cd-nextgen/src/test/java/io/harness/cdng/creator/variables/HelmDeployStepVariableCreatorTest.java#L59)):*
> ```Java
>             "pipeline.stages.Deployment.spec.execution.steps.helmDeployment.timeout",
>             "pipeline.stages.Deployment.spec.execution.steps.helmDeployment.name",
>             "pipeline.stages.Deployment.spec.execution.steps.helmDeployment.when");
> ```

do we need to expose this as an expression ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 29 files at r1, 2 of 65 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42934)* status: 87 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): sto.

**Review by harshjain12 — APPROVED** [review]

**Review by harshjain12 — APPROVED** [review]
:lgtm:

> Reviewed 22 of 29 files at r1, 64 of 65 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42934#-:-NMqPL9A836zbvvhr89S:bnfp4nl)* status: 84 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Comment by shalini-agr** [comment]
trigger ft1, ft2

**Comment by shalini-agr** [comment]
*[`125-cd-nextgen/src/test/java/io/harness/cdng/creator/variables/HelmDeployStepVariableCreatorTest.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/42934#-NMnBY0HDdpbYaQtchre:-NN5llUC9wH6DfjrKco5:b-m2gndr) ([raw file](https://github.com/harness/harness-core/blob/65ee019a240127e693a78a1371e4c99b7b0c53bc/125-cd-nextgen/src/test/java/io/harness/cdng/creator/variables/HelmDeployStepVariableCreatorTest.java#L59)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need to expose this as an expression ?
</blockquote></details>

These are exposed right now as well, and even after this change we would want the same behavior, and as we have changed this to ParamterField, these changes are added now.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42934)* status: 87 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/creator/variables/HelmDeployStepVariableCreatorTest.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/42934#-NMnBY0HDdpbYaQtchre:-NNAw2324oDKdcKs9cNN:b-hv2qst) ([raw file](https://github.com/harness/harness-core/blob/65ee019a240127e693a78a1371e4c99b7b0c53bc/125-cd-nextgen/src/test/java/io/harness/cdng/creator/variables/HelmDeployStepVariableCreatorTest.java#L59)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

These are exposed right now as well, and even after this change we would want the same behavior, and as we have changed this to ParamterField, these changes are added now.
</blockquote></details>

We don't currently see when variable expression in this test because it is actually included in fqnExtraProperties which is not being asserted in this test. 
If we check 125-cd-nextgen/src/test/java/io/harness/cdng/jenkins/JenkinsBuildStepVariableCreatorTest.java , we can see that 'when' was present in extra properties earlier, it just moved to fqnProperties list because of the ParamterField change.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 12 of 29 files at r1, 51 of 65 files at r2, 1 of 1 files at r4, 23 of 23 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42934)* status: 24 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 11 of 29 files at r1, 51 of 65 files at r2, 18 of 23 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42934)* status: 7 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by archit-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42934)* status: Waiting on team(s): sto.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 17 of 21 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42934)* status: 22 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java` line 43 at r8](https://reviewable.io/reviews/harness/harness-core/42934#-NN_xUDR-50Bhkpcc766:-NN_xUDR-50Bhkpcc767:bayxi7f) ([raw file](https://github.com/harness/harness-core/blob/014225e19e11578efaa7d6641e92c6531df75d09/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java#L43)):*
> ```Java
>   // be null and handled accordingly
>   public String getRunConditionForStage(ParameterField<StageWhenCondition> stageWhenCondition) {
>     if (ParameterField.isNull(stageWhenCondition) || stageWhenCondition.getValue() == null) {
> ```

why this or condition would be required?



_Code quote:_
```Java
|| stageWhenCondition.getValue() == null
```
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java` line 56 at r8](https://reviewable.io/reviews/harness/harness-core/42934#-NN_xa1vAzSxLCuPcnSi:-NN_xa1vAzSxLCuPcnSj:bayxi7f) ([raw file](https://github.com/harness/harness-core/blob/014225e19e11578efaa7d6641e92c6531df75d09/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java#L56)):*
> ```Java
> 
>   public String getRunConditionForStep(ParameterField<StepWhenCondition> stepWhenCondition) {
>     if (ParameterField.isNull(stepWhenCondition) || stepWhenCondition.getValue() == null) {
> ```

why this or condition would be required?

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 21 files at r7, 1 of 1 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42934)* status: 24 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 20 of 21 files at r7, 1 of 1 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42934)* status: :shipit: complete! ✓

**Pull request merged**
