### PR TITLE
[feat]: [SEI-1683]: - Register SEI resources, permissions and scopes on harness …

### PR DESCRIPTION
**Pull request by ashish-levelops**
## Describe your changes
https://harness.atlassian.net/wiki/spaces/LEV/pages/21417754907/SEI+on+Harness+User+Experience#SEI-Resources
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52570)

### CODE REVIEW

**Comment by ashish-levelops** [comment]
trigger messagecheck

**Comment by ashish-levelops** [comment]
trigger checkstylecodeformat

**Comment by ashish-levelops** [comment]
trigger uts

**Comment by ashish-levelops** [comment]
trigger utall

**Comment by ashish-levelops** [comment]
trigger ut1

**Comment by praveensugavanam** [comment]
No Tests ?

**Review by praveensugavanam — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r3, 1 of 8 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52570)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEICollectionsResourceImpl.java` line 47 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-Ndn7iZ7BYOlAVfSfbw4:-Ndn7iZ7BYOlAVfSfbw5:b-6znv4l) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEICollectionsResourceImpl.java#L47)):*
> ```Java
> @Slf4j
> public class SEICollectionsResourceImpl implements Resource {
>   @Override
> ```

Can you add some tests for these ?

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 1084 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-NdnswNO-8lROjtk4TFa:-NdnswNO-8lROjtk4TFb:by3f8dx) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L1084)):*
> ```YAML
>         - core_role_delete
>         - core_usergroup_view
>         - core_usergroup_manage
> ```

below permissions are duplicate
        - core_usergroup_view
        - core_usergroup_manage

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 1079 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-Ndnt3kOEXXBmCgnQV81:-Ndnt3kOEXXBmCgnQV82:by3f8dx) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L1079)):*
> ```YAML
>         - core_project_delete
>         - core_usergroup_view
>         - core_usergroup_manage
> ```

below permissions are duplicate
        - core_usergroup_view
        - core_usergroup_manage

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52570)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEICollectionsResourceImpl.java` line 58 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-NdpCgYJ729368ok51po:-NdpCgYJ729368ok51pp:bu82ddm) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEICollectionsResourceImpl.java#L58)):*
> ```Java
> 
>   @Override
>   public Optional<String> getEventFrameworkEntityType() {
> ```

Can we rename COLLECTIONS to SEI_COLLECTIONS to keep it consistent and also will help to identify module?

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52570)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEICollectionsResourceImpl.java` line 85 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-NdpD4Sw7kzsR91c96VG:-NdpD4Sw7kzsR91c96VH:b-o75qb7) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEICollectionsResourceImpl.java#L85)):*
> ```Java
>   /* Ideally we should make SEI API call to validate resourceIds, but anyway these resources are sent by UI after
>    making SEI API call Though the resourceIds in the payload can be manipulated manually, but only Authorized user will
>    be able to do it, so for him, it does not make much sense, so returning true for all resource ids for now */
> ```

Didn't understand the comment. Lets discuss over call.
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEIConfigurationSettingsResourceImpl.java` line 80 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-NdpEBxs2gFL4HsNfDjY:-NdpEBxs2gFL4HsNfDjZ:bsgi9fx) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEIConfigurationSettingsResourceImpl.java#L80)):*
> ```Java
>   @Override
>   public List<Boolean> validate(List<String> resourceIds, Scope scope) {
>     return null;
> ```

If BY_RESOURCE_IDENTIFIER is supported then this should not be null.
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEIInsightsResourceImpl.java` line 85 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-NdpENk2Ch-kZ7TmUG3F:-NdpENk2Ch-kZ7TmUG3G:b-614b09) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEIInsightsResourceImpl.java#L85)):*
> ```Java
>   /* Ideally we should make SEI API call to validate resourceIds, but anyway these resources are sent by UI after
>    making SEI API call Though the resourceIds in the payload can be manipulated manually, but only Authorized user will
>    be able to do it, so for him, it does not make much sense, so returning true for all resource ids for now */
> ```

Lets discuss how is it different than other Harness entities.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52570)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1643 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-NdxnzK-DHmFr0Hkr25U:-NdxnzK-DHmFr0Hkr25V:b6374zf) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1643)):*
> ```YAML
>     includedInAllRoles: false
>     allowedScopeLevels:
>       - account
> ```

As discussed, collections and insights create should be allowed at all 3 scopes.

**Review by ashish-levelops — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52570)* status: 9 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1643 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-NdxnzK-DHmFr0Hkr25U:-NdyPBAHCq63DOWuGIJ0:bylf93c) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1643)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

As discussed, collections and insights create should be allowed at all 3 scopes.
</blockquote></details>

Updated scopes as discussed
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1648 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-NdoqroN1Sl1mU-DXAGX:-NdyPHK51ZOyM1p-vC8C:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1648)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

allowedScopeLevels is different for same entity across CRUD operations.  has account, org and project but sei_seicollections_delete is applicable only to account. Why is the difference? Can u please elaborate?
</blockquote></details>

Done.
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 1079 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-Ndnt3kOEXXBmCgnQV81:-NdyPQybBTMbH_Stu-oJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L1079)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

below permissions are duplicate
        - core_usergroup_view
        - core_usergroup_manage
</blockquote></details>

Done.
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 1084 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-NdnswNO-8lROjtk4TFa:-NdyPS-sCJGUMgMmwcnA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L1084)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

below permissions are duplicate
        - core_usergroup_view
        - core_usergroup_manage
</blockquote></details>

Done.
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEICollectionsResourceImpl.java` line 47 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-Ndn7iZ7BYOlAVfSfbw4:-NdyPTng53jI1szAiYzT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEICollectionsResourceImpl.java#L47)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

Can you add some tests for these ?
</blockquote></details>

Done.
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEICollectionsResourceImpl.java` line 58 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-NdpCgYJ729368ok51po:-NdyPUun6GVfhK46bXTI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEICollectionsResourceImpl.java#L58)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Can we rename COLLECTIONS to SEI_COLLECTIONS to keep it consistent and also will help to identify module?
</blockquote></details>

Done.
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEICollectionsResourceImpl.java` line 85 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-NdpD4Sw7kzsR91c96VG:-NdyPVhrBCSTPgzHB8Qa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEICollectionsResourceImpl.java#L85)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Didn't understand the comment. Lets discuss over call.
</blockquote></details>

Done.
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEIConfigurationSettingsResourceImpl.java` line 80 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-NdpEBxs2gFL4HsNfDjY:-NdyPX6Z0ex4fKIWCOQr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEIConfigurationSettingsResourceImpl.java#L80)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

If BY_RESOURCE_IDENTIFIER is supported then this should not be null.
</blockquote></details>

Done.
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEIInsightsResourceImpl.java` line 85 at r5](https://reviewable.io/reviews/harness/harness-core/52570#-NdpENk2Ch-kZ7TmUG3F:-NdyPYk0D3mB88LD5JAd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c54ba45ebb60a2c4f26ece7c3ad998a41972cb6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEIInsightsResourceImpl.java#L85)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Lets discuss how is it different than other Harness entities.
</blockquote></details>

Done.

**Comment by ashish-levelops** [comment]
trigger uts

**Comment by ashish-levelops** [comment]
Use /rebase

**Comment by ashish-levelops** [comment]
trigger CommonChecks

**Comment by ashish-levelops** [comment]
trigger commonchecks

**Comment by ashish-levelops** [comment]
trigger commonchecks

**Pull request closed without merging**
