### PR TITLE
feat: [CDS-53773]: Added deduplication of events and logging for prod

### PR DESCRIPTION
**Pull request by hextechpal**
## Describe your changes

Added cache to remove duplicate event processing
Added logs for debugging high cpu usage in prod related to redis producer

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44411)

### CODE REVIEW

**Comment by hextechpal** [comment]
trigger messagecheck

**Comment by hextechpal** [comment]
trigger messagecheck

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44411)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by inderschera — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44411)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/io/harness/queue/consumers/AbstractBaseConsumerCg.java` line 133 at r1](https://reviewable.io/reviews/harness/harness-core/44411#-NPLe9CnBkteVGSD1R3a:-NPLe9CnBkteVGSD1R3b:b-ifeqg6) ([raw file](https://github.com/harness/harness-core/blob/8464d078e33aa402fd77455304f65d832a5316f1/400-rest/src/main/java/io/harness/queue/consumers/AbstractBaseConsumerCg.java#L133)):*
> ```Java
>       if (isProcessed) {
>         log.warn(String.format("Duplicate redis notification received to consumer [%s] with messageId [%s]",
>             this.getClass().getSimpleName(), message.getId()));
> ```

Should we log count as well?

**Review by hextechpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44411)* status: 1. unresolved discussions. 

___
*[`400-rest/src/main/java/io/harness/queue/consumers/AbstractBaseConsumerCg.java` line 133 at r1](https://reviewable.io/reviews/harness/harness-core/44411#-NPLe9CnBkteVGSD1R3a:-NPLghLa2wJ5fCwnxOS4:ben3upn) ([raw file](https://github.com/harness/harness-core/blob/8464d078e33aa402fd77455304f65d832a5316f1/400-rest/src/main/java/io/harness/queue/consumers/AbstractBaseConsumerCg.java#L133)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Should we log count as well?
</blockquote></details>

almost exclusively its always one :smile:

**Pull request merged**
