### PR TITLE
feat: [PL-26355]: Add get repo url git sdk API logic

### PR DESCRIPTION
**Pull request by mohitg0795**
## Describe your changes

Test cases:
github - http
	- account level -- done
	- repo level -- done	

bitbucket - http
	- account level -- done
	- repo level -- done

bitbucket - ssh
	- repo level -- done

bitbucket on-prem - http
	- account level -- done
	- repo level -- done

bitbucket on-prem - ssh
	- repo level -- done

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35188)

### CODE REVIEW

**Review by adivishy1 — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35188)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
trigger messagecheck

**Review by bhavya181 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 7 of 14 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35188#-:-N6q3rr3-CVVy9Ct4cd4:bnfp4nl)* status: 8 file(s) to review. 0 of 2 approvals obtained.

**Review by adivishy1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35188)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 7 of 14 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35188)* status: 6 file(s) to review.

**Review by senjucanon2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 13 of 14 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35188#-:-N7L3846Egw-ZCkAXfzU:bnfp4nl)* status: Some of the checks are too old.

**Review by senjucanon2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35188#-:-N7LC_SlE8sP35vt6kXD:bnfp4nl)* status: 1 file(s) to review.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 12 of 14 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35188)* status: :shipit: complete! ✓

**Pull request merged**
