### PR TITLE
feat: [CDS-38445]: clean up templateMergeHelper

### PR DESCRIPTION
**Pull request by inderschera**
## Describe your changes
Changes:
Moved code out from TemplateMergeHelper to TemplateMergeServiceImpl
Added applyTemplatesV2 api

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34794)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34794)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/TemplateServiceModule.java` line 163 at r1](https://reviewable.io/reviews/harness/harness-core/34794#-N5necuc9_z2Cw1uRthS:-N5necuc9_z2Cw1uRthT:b-by3lml) ([raw file](https://github.com/harness/harness-core/blob/da87e18cdd71b19b8a8c5acc7ba77ca918969f11/840-template-service/src/main/java/io/harness/TemplateServiceModule.java#L163)):*
> ```Java
>     bind(NGTemplateService.class).to(NGTemplateServiceImpl.class);
>     bind(TemplateRefreshService.class).to(TemplateRefreshServiceImpl.class);
>     bind(TemplateMergeService.class).to(TemplateMergeServiceImpl.class);
> ```

Make it singleton

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34794)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/TemplateServiceModule.java` line 163 at r1](https://reviewable.io/reviews/harness/harness-core/34794#-N5necuc9_z2Cw1uRthS:-N5oIC9R3riwo7Jt0yAu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/da87e18cdd71b19b8a8c5acc7ba77ca918969f11/840-template-service/src/main/java/io/harness/TemplateServiceModule.java#L163)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Make it singleton
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34794)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34794)* status: :shipit: complete! ✓

**Review by utkarshchoubey-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 10 files at r1, 3 of 3 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34794#-:-N6CZOdg9mr8dYiJp_0W:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
