### PR TITLE
techdebt: [PIE-4947]: added UTs

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39995)

### CODE REVIEW

**Comment by AnshuH** [comment]
trigger TI

**Comment by ankittiwari-harness** [comment]
*[`pipeline-service/service/src/test/java/io/harness/NotificationTemplateRegistrarTest.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/39995#-NG_KqoF1FLcnww47WBD:-NG_KqoF1FLcnww47WBE:bx923r9) ([raw file](https://github.com/harness/harness-core/blob/e1e9275dbb339fe46a5df527018111b231250c20/pipeline-service/service/src/test/java/io/harness/NotificationTemplateRegistrarTest.java#L39)):*
> ```Java
>   @Owner(developers = SHALINI)
>   @Category(UnitTests.class)
>   public void testRun() {
> ```

nit: Make the Test Name more Verbose

**Review by ankittiwari-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39995#-:-NG_Kwo4AD9ldyMKQhB1:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
*[`pipeline-service/service/src/test/java/io/harness/NotificationTemplateRegistrarTest.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/39995#-NG_KqoF1FLcnww47WBD:-NG_LmN17jrij6tn_TXQ:b-7rl0jd) ([raw file](https://github.com/harness/harness-core/blob/e1e9275dbb339fe46a5df527018111b231250c20/pipeline-service/service/src/test/java/io/harness/NotificationTemplateRegistrarTest.java#L39)):*
<details><summary><i>Previously, ankittiwari-harness (Ankit Tiwari) wrote…</i></summary><blockquote>

nit: Make the Test Name more Verbose
</blockquote></details>

done.

**Comment by shalini-agr** [comment]
trigger messagecheck

**Comment by shalini-agr** [comment]
trigger messagecheck

**Review by ankittiwari-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39995#-:-NGolfGc9yCI0nq_nGkn:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39995)* status: Some of the checks are too old. 2 file(s) to review.

**Comment by shalini-agr** [comment]
trigger checkstylecodeformat

**Review by ankittiwari-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39995)* status: :shipit: complete! ✓

**Pull request merged**
