### PR TITLE
[feat]: [CDS-48177]: create table tags_info_ng

### PR DESCRIPTION
**Pull request by Abhishek-CDC**
## Describe your changes
Created table 'tags_info_ng' to store tag related information for different entities like service, pipeline etc.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42059)

### CODE REVIEW

**Comment by abhinavmittal-harness** [comment]
*[`950-ng-project-n-orgs/src/resources/timescale/create_tags_info_ng_table.sql` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/42059#-NKqOI1Y4qRCLmRZ7odi:-NKqOI1Z89gMYyEtF9Z1:bp6x61y) ([raw file](https://github.com/harness/harness-core/blob/e2709f62f8af76c95ae63e911e75d0b456f67ee7/950-ng-project-n-orgs/src/resources/timescale/create_tags_info_ng_table.sql#L15)):*
> ```TSQL
>     project_id text,
>     parent_type text NOT NULL,
>     parent_id text NOT NULL,
> ```

Let's add index on account_id
And one one compound one on account_id, projectId, orgId, and id

**Comment by abhinavmittal-harness** [comment]
*[`950-ng-project-n-orgs/src/resources/timescale/create_tags_info_ng_table.sql` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/42059#-NKqPGuf7IDbstyvYrnE:-NKqPGuf7IDbstyvYrnF:bcaom08) ([raw file](https://github.com/harness/harness-core/blob/e2709f62f8af76c95ae63e911e75d0b456f67ee7/950-ng-project-n-orgs/src/resources/timescale/create_tags_info_ng_table.sql#L17)):*
> ```TSQL
>     parent_id text NOT NULL,
>     tags text[],
>     PRIMARY KEY(id, parent_type));
> ```

Primary key should be combination of account_id, projectId, orgId, and id, parent_type I think

**Comment by abhinavmittal-harness** [comment]
*[`950-ng-project-n-orgs/src/resources/timescale/create_tags_info_ng_table.sql` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/42059#-NKqOI1Y4qRCLmRZ7odi:-NKr9ug0Ce8ojeafR_hi:b-fehy1i) ([raw file](https://github.com/harness/harness-core/blob/e2709f62f8af76c95ae63e911e75d0b456f67ee7/950-ng-project-n-orgs/src/resources/timescale/create_tags_info_ng_table.sql#L15)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Let's add index on account_id
And one one compound one on account_id, projectId, orgId, and id
</blockquote></details>

parentId

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42059)* status: Some of the checks are too old. 3 file(s) to review. 0 of 2 approvals obtained.

**Comment by Abhishek-CDC** [comment]
*[`950-ng-project-n-orgs/src/resources/timescale/create_tags_info_ng_table.sql` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/42059#-NKqPGuf7IDbstyvYrnE:-NKrCyKN6_JIa_PVUDnk:b-jcq6py) ([raw file](https://github.com/harness/harness-core/blob/e2709f62f8af76c95ae63e911e75d0b456f67ee7/950-ng-project-n-orgs/src/resources/timescale/create_tags_info_ng_table.sql#L17)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Primary key should be combination of account_id, projectId, orgId, and id, parent_type I think
</blockquote></details>

It is possible to have orgId/projectId null for some entities so we cannot make it primary key

**Comment by Abhishek-CDC** [comment]
*[`950-ng-project-n-orgs/src/resources/timescale/create_tags_info_ng_table.sql` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/42059#-NKqOI1Y4qRCLmRZ7odi:-NKrI4LRD35kXpw0Iizr:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e2709f62f8af76c95ae63e911e75d0b456f67ee7/950-ng-project-n-orgs/src/resources/timescale/create_tags_info_ng_table.sql#L15)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

parentId
</blockquote></details>

done

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42059)* status: 3 file(s) to review. 0 of 2 approvals obtained.

**Review by abhinavmittal-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42059#-:-NKvOdaU4DaaSayTD9KZ:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by Y0709 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42059)* status: :shipit: complete! ✓

**Pull request merged**
