### PR TITLE
[fix]: [PIE-3274]: Send update event for git synced projects

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31809)

### CODE REVIEW

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31809)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
We should add handling in PipelineOutboxHandler that isFromGit then don't audit

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31809#-:-MzFpLDO5-oZQ-9vtK56:bxztm7)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by namanvermah — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31809#-:-MzG1D3tBhaSlD9o8Pzw:bb6un1j)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31809)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
