### PR TITLE
feat: [PL-26995]: Added update and restore audit events for settings

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35687)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger ti3

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35687)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/SettingsServiceImplTest.java` line 168 at r2](https://reviewable.io/reviews/harness/harness-core/35687#-N7pBTJf61ISf7m9xE_E:-N7pBTJf61ISf7m9xE_F:b-b0smwz) ([raw file](https://github.com/harness/harness-core/blob/a173627a3c920f84b60b5d7cb93e42936850b8cb/120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/SettingsServiceImplTest.java#L168)):*
> ```Java
>         .thenAnswer(invocationOnMock
>             -> invocationOnMock.getArgument(0, TransactionCallback.class)
>                    .doInTransaction(new SimpleTransactionStatus()));
> ```

Verify if the methods inside transaction are called.
___
*[`120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/SettingsServiceImplTest.java` line 219 at r2](https://reviewable.io/reviews/harness/harness-core/35687#-N7pBIT4DWqqcFv6IUpR:-N7pBIT4DWqqcFv6IUpS:b-b0smwz) ([raw file](https://github.com/harness/harness-core/blob/a173627a3c920f84b60b5d7cb93e42936850b8cb/120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/SettingsServiceImplTest.java#L219)):*
> ```Java
>         .thenAnswer(invocationOnMock
>             -> invocationOnMock.getArgument(0, TransactionCallback.class)
>                    .doInTransaction(new SimpleTransactionStatus()));
> ```

Verify if the methods inside transaction are called.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/SettingEventHandler.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/35687#-N7pC9UQ8-V_q6H0OPkP:-N7pC9UQ8-V_q6H0OPkQ:b-fx3w31) ([raw file](https://github.com/harness/harness-core/blob/a173627a3c920f84b60b5d7cb93e42936850b8cb/120-ng-manager/src/main/java/io/harness/ng/core/outbox/SettingEventHandler.java#L24)):*
> ```Java
> import java.io.IOException;
> 
> public class SettingEventHandler implements OutboxEventHandler {
> ```

This class should be in ng-settings module.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35687)* status: 10 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/SettingsServiceImplTest.java` line 168 at r2](https://reviewable.io/reviews/harness/harness-core/35687#-N7pBTJf61ISf7m9xE_E:-N82KqMa6k_gSm5zuHN5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a173627a3c920f84b60b5d7cb93e42936850b8cb/120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/SettingsServiceImplTest.java#L168)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Verify if the methods inside transaction are called.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/SettingsServiceImplTest.java` line 219 at r2](https://reviewable.io/reviews/harness/harness-core/35687#-N7pBIT4DWqqcFv6IUpR:-N82Kr8U-g8gnf5c0cwP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a173627a3c920f84b60b5d7cb93e42936850b8cb/120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/SettingsServiceImplTest.java#L219)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Verify if the methods inside transaction are called.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/SettingEventHandler.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/35687#-N7pC9UQ8-V_q6H0OPkP:-N82KpTRAluDgixj2Z3j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a173627a3c920f84b60b5d7cb93e42936850b8cb/120-ng-manager/src/main/java/io/harness/ng/core/outbox/SettingEventHandler.java#L24)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This class should be in ng-settings module.
</blockquote></details>

Done.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35687)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/events/SettingEventHandler.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/35687#-N82LdKX87duPx-ikqxJ:-N82LdKX87duPx-ikqxK:bk3dyut) ([raw file](https://github.com/harness/harness-core/blob/e1e1671d91f384d7e839b16fb01ca47f2b2639a9/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/events/SettingEventHandler.java#L23)):*
> ```Java
> import java.io.IOException;
> 
> public class SettingEventHandler implements OutboxEventHandler {
> ```

Should it be in ngsettings.outbox package?

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35687)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/events/SettingEventHandler.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/35687#-N82LdKX87duPx-ikqxJ:-N83Dxjf3kb6ITSC7Vxn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e1e1671d91f384d7e839b16fb01ca47f2b2639a9/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/events/SettingEventHandler.java#L23)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should it be in ngsettings.outbox package?
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35687)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 2 of 5 files at r2, 4 of 7 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35687)* status: 1 file(s) to review.

**Review by nishantsaini20 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35687#-:-N87me6W0MIa2xCaeqJ4:bnfp4nl)* status: 1 file(s) to review.

**Pull request merged**
