### PR TITLE
fix: [CDS-59022]: Fixed query for fetching active instances of service.

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
Currently when we try to delete a service,we are fetching active instances of a service based on service identifier and account identifier.Which is incorrect as this query will give all the active instances which have same service identifier and account identifier.
Let's say we have a two services  with same identifier at project level and account level.When we try to fetch active instances for service at account level,it will return the active instances of project-level service as well.Which is incorrect,Have fixed this in this pr
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46405)

### CODE REVIEW

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/services/ServiceEntityManagementServiceImpl.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/46405#-NSyBs9ACRFm7X7dRFn_:-NSyBs9ACRFm7X7dRFna:b-ee3g9d) ([raw file](https://github.com/harness/harness-core/blob/84cb9840dca22820a6ff7538e181074ebe09b5ac/120-ng-manager/src/main/java/io/harness/ng/core/service/services/ServiceEntityManagementServiceImpl.java#L55)):*
> ```Java
>     }
> 
>     List<InstanceDTO> instanceInfoNGList = instanceService.getActiveInstancesByAccountOrgProjectAndService(
> ```

nit: can we make this method public and use it
getInstancesCreatedBefore()

getActiveInstancesByAccountOrgProjectAndService() - fetch all instances which are deleted after current timestamp.
And our deleteAll() --> method is not exception safe if instance is already deleted.

This might be not cause issue in almost all the time, but to be safe for any edge case lets use getInstancesCreatedBefore()

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46405)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by vivekkarnatiharness** [comment]
trigger messagecheck

**Comment by vivekkarnatiharness** [comment]
trigger messagecheck

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46405)* status: :shipit: complete! ✓

**Comment by vivekkarnatiharness** [comment]
trigger messagecheck

**Comment by vivekkarnatiharness** [comment]
trigger review

**Pull request merged**
