### PR TITLE
fix: [PL-40260]: Added limit for ng users

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Describe your changes
This will start blocking user addition based on the license. This will check when user is added via manual invite or via scim.
JIT type is not included in this.
The way it looks in case of scim is added as a SS below.
Screenshot 2023-07-25 at 4 56 34 PM
In case of LDAP, as LDAP itself is behind a featureRestricion, this is what we see when trying to sync an existing LDAP config 
Screenshot 2023-07-27 at 2 02 02 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50956)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/config.yml` line 472 at r1](https://reviewable.io/reviews/harness/harness-core/50956#-NaGj4ER0VCaBUQHJoza:-NaGj4ER0VCaBUQHJozb:bqglspx) ([raw file](https://github.com/harness/harness-core/blob/fa1313a7958efffaab28f3cbe983c95544dbe94b/120-ng-manager/config.yml#L472)):*
> ```YAML
> 
> enforcementClientConfiguration:
>   enforcementCheckEnabled: true
> ```

minor: IMO, we should keep it false by default and enable it environment by environment



_Code quote:_
```YAML
true
```

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 614 at r1](https://reviewable.io/reviews/harness/harness-core/50956#-NaGjObk7vlTrF3OnHwI:-NaGjObk7vlTrF3OnHwJ:b-l221i2) ([raw file](https://github.com/harness/harness-core/blob/fa1313a7958efffaab28f3cbe983c95544dbe94b/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L614)):*
> ```Java
>   private InviteOperationResponse newInvite(Invite invite, boolean[] scimLdapArray) {
>     //    checkUserLimit(invite.getAccountIdentifier(), invite.getEmail());
>     checkNgLimit(invite.getAccountIdentifier());
> ```

minor: remove commented code. 
One question here: User in CG & NG (same email) should be considered as one user and not separate, Are we doing the same thing inside? 



_Code quote:_
```Java
    //    checkUserLimit(invite.getAccountIdentifier(), invite.getEmail());
    checkNgLimit(invite.getAccountIdentifier());
```

**Review by pbarapatre10 — COMMENTED** [review]
Also, test with LDAP flow apart from SCIM/manual invite, thanks

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50956#-:-NaGkElCER90Sm_VPQhk:b-ic5ljq)* status: 9 file(s) to review. 0 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/remote/UsersRestrictionUsageImpl.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/50956#-NaGkPG0CB4jGtWjKTdx:-NaGkPG0CB4jGtWjKTdy:b66v2vo) ([raw file](https://github.com/harness/harness-core/blob/fa1313a7958efffaab28f3cbe983c95544dbe94b/123-ng-core-user/src/main/java/io/harness/ng/core/remote/UsersRestrictionUsageImpl.java#L26)):*
> ```Java
>   public long getCurrentValue(String accountIdentifier, StaticLimitRestrictionMetadataDTO restrictionMetadataDTO) {
>     return ngUserService.getNgUsersCount(Scope.builder().accountIdentifier(accountIdentifier).build());
>   }
> ```

minor: UT can be added for this, thanks



_Code quote:_
```Java
public class UsersRestrictionUsageImpl implements RestrictionUsageInterface<StaticLimitRestrictionMetadataDTO> {
  @Inject NgUserService ngUserService;

  @Override
  public long getCurrentValue(String accountIdentifier, StaticLimitRestrictionMetadataDTO restrictionMetadataDTO) {
    return ngUserService.getNgUsersCount(Scope.builder().accountIdentifier(accountIdentifier).build());
  }
```

**Review by VikasMaddukuriHarness — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50956#-:-NaLbPr-DLzlDR5hkBPR:bb7f2mf)* status: 10 file(s) to review. 0 of 2 approvals obtained.

**Comment by VikasMaddukuriHarness** [comment]
trigger uts

**Comment by VikasMaddukuriHarness** [comment]
trigger ut6

**Comment by VikasMaddukuriHarness** [comment]
trigger uts

**Review by shashank-harness — APPROVED** [review]
Lgtm

**Pull request merged**
