### PR TITLE
fix: [PIE-2811]: Increase runSequence irrespective of git branch and repo

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31725)

### CODE REVIEW

**Review by namanvermah — DISMISSED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31725#-:-MyzObAl6QD6xzAxWrHL:bnfp4nl)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31725)* status: 9 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineMetadataV2.java, line 37 at r1](https://reviewable.io/reviews/harness/harness-core/31725#-MyzWkED55QhKivMGnxj:-MyzWkED55QhKivMGnxk:bsnmofx) ([raw file](https://github.com/harness/harness-core/blob/aa55f0e162dbaf3611a93330503510a33a3e4e0b/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineMetadataV2.java#L37)):*
> ```Java
> @HarnessEntity(exportable = true)
> @StoreIn(DbAliases.PMS)
> public class PipelineMetadataV2 {
> ```

We are introducing more metadata, can we have comment what each metadata is containing and why



_Code quote:_
```Java
PipelineMetadataV2
```
___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineMetadataV2.java, line 41 at r1](https://reviewable.io/reviews/harness/harness-core/31725#-MyzW4Mo9e6p5Gym2ETJ:-MyzW4Mo9e6p5Gym2ETK:b3fra6o) ([raw file](https://github.com/harness/harness-core/blob/aa55f0e162dbaf3611a93330503510a33a3e4e0b/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineMetadataV2.java#L41)):*
> ```Java
>     return ImmutableList.<MongoIndex>builder()
>         .add(CompoundMongoIndex.builder()
>                  .name("account_org_project_pipeline_yaml_git_config_branch_idx")
> ```

this is word can be removed



_Code quote:_
```Java
yaml_git_config_branch
```

**Comment by sahilhindwani-harness** [comment]
___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineMetadataV2.java, line 37 at r1](https://reviewable.io/reviews/harness/harness-core/31725#-MyzWkED55QhKivMGnxj:-Mz-2KSM9VxkAol8L6tX:b-eiz20t) ([raw file](https://github.com/harness/harness-core/blob/aa55f0e162dbaf3611a93330503510a33a3e4e0b/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineMetadataV2.java#L37)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

We are introducing more metadata, can we have comment what each metadata is containing and why
</blockquote></details>

the other one will be removed. It won't get populated from now on. Will add a comment there.

**Comment by sahilhindwani-harness** [comment]
___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineMetadataV2.java, line 41 at r1](https://reviewable.io/reviews/harness/harness-core/31725#-MyzW4Mo9e6p5Gym2ETJ:-Mz-X2FH1f_VZZ_CEnu_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa55f0e162dbaf3611a93330503510a33a3e4e0b/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineMetadataV2.java#L41)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this is word can be removed
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 8 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31725)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by namanvermah — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31725)* status: :shipit: complete! ✓

**Pull request merged**
