### PR TITLE
feat: [CDS-40991]: feature flag to enable check state execution

### PR DESCRIPTION
**Pull request by rafaelmart1ns**
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36628)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36628)

**Review by lasdox — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36628)* status: :shipit: complete! ✓

**Comment by rafaelmart1ns** [comment]
trigger messagecheck

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36628)* status: 2 file(s) to review. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 422 at r2](https://reviewable.io/reviews/harness/harness-core/36628#-NA6-blX9Mpo1UcCKWF7:-NA6-blX9Mpo1UcCKWF8:b86dvld) ([raw file](https://github.com/harness/harness-core/blob/60d6181373a6b8d3e43161a85880f7e208433065/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L422)):*
> ```Java
>   TRIGGERS_REFACTOR("Enable NG Triggers UI refactoring", HarnessTeam.CDP),
> 
>   ENABLE_CHECK_STATE_EXECUTION_STARTING(
> ```

FYI, Maybe the name doesn't need to start with "enable" next time

**Review by rafaelmart1ns — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36628)* status: 2 file(s) to review. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 422 at r2](https://reviewable.io/reviews/harness/harness-core/36628#-NA6-blX9Mpo1UcCKWF7:-NA6EuCF-wvLetKMhz65:bxtjw0o) ([raw file](https://github.com/harness/harness-core/blob/60d6181373a6b8d3e43161a85880f7e208433065/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L422)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

FYI, Maybe the name doesn't need to start with "enable" next time
</blockquote></details>

next time I wont use "enable".

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36628)* status: :shipit: complete! ✓

**Pull request merged**
