### PR TITLE
feat: [CDS-47361]: Save environment group information to service_infra_info timescale table from GitopsExecutionSummary

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes

- Save environment type in GitOpsClusterOutcome
- Save environment type in GitOpsExecutionSummary in CDNGModuleInfoProvider for both stage and pipeline level info
- Save environment group information to timescale db "service_infra_info" table in case of gitops deployments

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41687)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeServiceInfraChangeDataHandlerNew.java` line 228 at r2](https://reviewable.io/reviews/harness/harness-core/41687#-NJPfjOx7crEouin976e:-NJPfjOx7crEouin976f:bg71mpw) ([raw file](https://github.com/harness/harness-core/blob/8d94fe21b55adeee8ade41c69195808d62e515a7/110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeServiceInfraChangeDataHandlerNew.java#L228)):*
> ```Java
> 
>             // env info
>             if (cdObject.get("infraExecutionSummary") != null) {
> ```

extracted this method out to a new method, no logic change here

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41687)* status: 15 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java` line 216 at r3](https://reviewable.io/reviews/harness/harness-core/41687#-NJd6lyzB0cfNpsqJD2c:-NJd6lyzB0cfNpsqJD2d:b-33jp83) ([raw file](https://github.com/harness/harness-core/blob/549b0b592ec84f19085dcde3a37c08df68d5327d/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java#L216)):*
> ```Java
>             .map(EnvironmentType::valueOf)
>             .collect(Collectors.toSet())
>             .forEach(cdPipelineModuleInfoBuilder::environmentType);
> ```

Add environment type to cdPipelineModuleInfo
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java` line 300 at r3](https://reviewable.io/reviews/harness/harness-core/41687#-NJd6r1z2GfPRghZ1lxR:-NJd6r1z2GfPRghZ1lxS:bt9v3ry) ([raw file](https://github.com/harness/harness-core/blob/549b0b592ec84f19085dcde3a37c08df68d5327d/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java#L300)):*
> ```Java
>                 data.getEnvGroupId(), data.getEnvGroupName(), data.getEnvId(), data.getEnvName(), data.getEnvType());
>           } else if (isNotEmpty(data.getEnvId())) {
>             gitOpsExecutionSummary.addSingleEnvironment(data.getEnvId(), data.getEnvName(), data.getEnvType());
> ```

Add environment type to gitOpsExecutionSummary
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/gitops/ClusterPlanCreatorUtils.java` line 94 at r3](https://reviewable.io/reviews/harness/harness-core/41687#-NJd6umO4PY-r-MuGT37:-NJd6umO4PY-r-MuGT38:b-9ecry8) ([raw file](https://github.com/harness/harness-core/blob/549b0b592ec84f19085dcde3a37c08df68d5327d/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/gitops/ClusterPlanCreatorUtils.java#L94)):*
> ```Java
>                                       .envRef(envRef)
>                                       .envName(envConfig.getName())
>                                       .envType(envConfig.getType().toString())
> ```

Add environment type to ClusterStepParameters

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 9 of 14 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41687)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 9 of 14 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41687)* status: :shipit: complete! ✓

**Pull request merged**
