### PR TITLE
feat: [PL-25079]: bump up scm veriosn in delegate

### PR DESCRIPTION
**Pull request by bhavya181**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33054)

### CODE REVIEW

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33054)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Comment by bhavya181** [comment]
trigger ti3

**Comment by bhavya181** [comment]
trigger messagecheck

**Comment by bhavya181** [comment]
trigger ti0

**Comment by bhavya181** [comment]
trigger ti2

**Comment by mdmilic** [comment]
@bhavya181, please make sure that new SCM library is downloadable for the new version (for both PROD & QA)

**Comment by bhavya181** [comment]
trigger ti1

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33054#-:-N1rSlRtBhSJk5oD-NSV:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
