### PR TITLE
[feat]:[PIE-5936]: Adding Base BenchMark Test for Enqueue and Dequeue operation

### PR DESCRIPTION
**Pull request by ankittiwari-harness**
[feat]:[PIE-5936]: Adding Base BenchMark Test for Enqueue and Dequeue operation

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[PIE-5936]: https://harness.atlassian.net/browse/PIE-5936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39067)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39067)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`queue-service/hsqs/store/redis/benchmark_redis_store_test.go` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/39067#-NEqcwp-EJb9eq6_lOR8:-NEqcwp-EJb9eq6_lOR9:b-4a7l6w) ([raw file](https://github.com/harness/harness-core/blob/03534200bd522b856e4e4552dd3aa3255f23c40b/queue-service/hsqs/store/redis/benchmark_redis_store_test.go#L45)):*
> ```Go
> 		if err := redisStore.Register(parent, store.RegisterTopicMetadata{Topic: topic}); err != nil {
> 			b.Errorf("could not register consumer group to queue %v", err.Error())
> 		}
> ```

stream registration should be first step



_Code quote:_
```Go
		if err := redisStore.Register(parent, store.RegisterTopicMetadata{Topic: topic}); err != nil {
			b.Errorf("could not register consumer group to queue %v", err.Error())
		}
```
___
*[`queue-service/hsqs/store/redis/benchmark_redis_store_test.go` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/39067#-NEqd4d70p64NwpZzzSj:-NEqd4d70p64NwpZzzSk:b-1k7lta) ([raw file](https://github.com/harness/harness-core/blob/03534200bd522b856e4e4552dd3aa3255f23c40b/queue-service/hsqs/store/redis/benchmark_redis_store_test.go#L53)):*
> ```Go
> }
> 
> func Test_BenchmarkDequeue(b *testing.T) {
> ```

how do we ensure this benchmark test with enqueued data?
___
*[`queue-service/hsqs/store/redis/benchmark_redis_store_test.go` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/39067#-NEqdNwN80v_n8WbPr9E:-NEqdNwN80v_n8WbPr9F:bezbcjz) ([raw file](https://github.com/harness/harness-core/blob/03534200bd522b856e4e4552dd3aa3255f23c40b/queue-service/hsqs/store/redis/benchmark_redis_store_test.go#L68)):*
> ```Go
> 			MaxWaitDuration: 10,
> 		}
> 		dequeResponse, err := redisStore.Dequeue(ctx, deqRequest)
> ```

Should we also add benchmark test for multiple consumers via go routines or in end to end tests?
___
*[`queue-service/hsqs/store/redis/redis_store.go` line 320 at r1](https://reviewable.io/reviews/harness/harness-core/39067#-NEqcDNj4RGb8Bx9Lnnd:-NEqcDNj4RGb8Bx9Lnne:bb7p05m) ([raw file](https://github.com/harness/harness-core/blob/03534200bd522b856e4e4552dd3aa3255f23c40b/queue-service/hsqs/store/redis/redis_store.go#L320)):*
> ```Go
> 		return &store.AckResponse{}, &store.AckErrorResponse{ErrorMessage: err.Error()}
> 	}
> 	//deleting the method from queue
> ```

task



_Code quote:_
```Go
method
```
___
*[`queue-service/hsqs/store/redis/redis_store.go` line 381 at r1](https://reviewable.io/reviews/harness/harness-core/39067#-NEqcM0GDMWwYeSe3Zoz:-NEqcM0GDMWwYeSe3Zp-:buqnygf) ([raw file](https://github.com/harness/harness-core/blob/03534200bd522b856e4e4552dd3aa3255f23c40b/queue-service/hsqs/store/redis/redis_store.go#L381)):*
> ```Go
> 	//nLogger := s.Logger.With().Str("AllQueuesTopicKey", allQueuesTopicKey).
> 	//	Str("ConsumerName", request.ConsumerName).
> 	//	Int("batchSize", request.BatchSize).Logger()
> ```

why we commented it out?



_Code quote:_
```Go
	//nLogger := s.Logger.With().Str("AllQueuesTopicKey", allQueuesTopicKey).
	//	Str("ConsumerName", request.ConsumerName).
	//	Int("batchSize", request.BatchSize).Logger()
```
___
*[`queue-service/hsqs/store/redis/redis_store.go` line 436 at r1](https://reviewable.io/reviews/harness/harness-core/39067#-NEqcSHcE5vR27SsRoxw:-NEqcSHcE5vR27SsRoxx:bhkyqrz) ([raw file](https://github.com/harness/harness-core/blob/03534200bd522b856e4e4552dd3aa3255f23c40b/queue-service/hsqs/store/redis/redis_store.go#L436)):*
> ```Go
> }
> 
> // Register method to get send
> ```

to set stream metadata 



_Code quote:_
```Go
to get send
```
___
*[`queue-service/hsqs/store/redis/redis_store.go` line 443 at r1](https://reviewable.io/reviews/harness/harness-core/39067#-NEqcZsb3t5QB_UHNjp8:-NEqcZsb3t5QB_UHNjp9:b-xa4b16) ([raw file](https://github.com/harness/harness-core/blob/03534200bd522b856e4e4552dd3aa3255f23c40b/queue-service/hsqs/store/redis/redis_store.go#L443)):*
> ```Go
> 		return err
> 	}
> ```

Please add a todo to add stream metadata with registration like stream size, retry count etc.

**Review by ankittiwari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39067)* status: 3 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`queue-service/hsqs/store/redis/benchmark_redis_store_test.go` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/39067#-NEqcwp-EJb9eq6_lOR8:-NEsiJPQDy33XMwbBnh2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/03534200bd522b856e4e4552dd3aa3255f23c40b/queue-service/hsqs/store/redis/benchmark_redis_store_test.go#L45)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

stream registration should be first step
</blockquote></details>

Done.
___
*[`queue-service/hsqs/store/redis/benchmark_redis_store_test.go` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/39067#-NEqd4d70p64NwpZzzSj:-NEsiLsVBn7ANogqZsD_:b-xt2317) ([raw file](https://github.com/harness/harness-core/blob/03534200bd522b856e4e4552dd3aa3255f23c40b/queue-service/hsqs/store/redis/benchmark_redis_store_test.go#L53)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

how do we ensure this benchmark test with enqueued data?
</blockquote></details>

the test requires running redis. Deq will run after enqueue operation, merged them in latest commit
___
*[`queue-service/hsqs/store/redis/benchmark_redis_store_test.go` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/39067#-NEqdNwN80v_n8WbPr9E:-NEsnNXpC0yzMJEw7yFW:b-ccusu8) ([raw file](https://github.com/harness/harness-core/blob/03534200bd522b856e4e4552dd3aa3255f23c40b/queue-service/hsqs/store/redis/benchmark_redis_store_test.go#L68)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Should we also add benchmark test for multiple consumers via go routines or in end to end tests?
</blockquote></details>

added in newer commit
___
*[`queue-service/hsqs/store/redis/redis_store.go` line 320 at r1](https://reviewable.io/reviews/harness/harness-core/39067#-NEqcDNj4RGb8Bx9Lnnd:-NEsncAODSZTMe9ied9w:b32vmt) ([raw file](https://github.com/harness/harness-core/blob/03534200bd522b856e4e4552dd3aa3255f23c40b/queue-service/hsqs/store/redis/redis_store.go#L320)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

task
</blockquote></details>

??
___
*[`queue-service/hsqs/store/redis/redis_store.go` line 381 at r1](https://reviewable.io/reviews/harness/harness-core/39067#-NEqcM0GDMWwYeSe3Zoz:-NEsnQfBE9Gf2VlJhEQ0:b-scns8b) ([raw file](https://github.com/harness/harness-core/blob/03534200bd522b856e4e4552dd3aa3255f23c40b/queue-service/hsqs/store/redis/redis_store.go#L381)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we commented it out?
</blockquote></details>

refactored the method to use topic only instead of deq request. Hence, no access to variables
___
*[`queue-service/hsqs/store/redis/redis_store.go` line 436 at r1](https://reviewable.io/reviews/harness/harness-core/39067#-NEqcSHcE5vR27SsRoxw:-NEsnZ0pDktQ0e2YV3xx:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/03534200bd522b856e4e4552dd3aa3255f23c40b/queue-service/hsqs/store/redis/redis_store.go#L436)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

to set stream metadata 
</blockquote></details>

done
___
*[`queue-service/hsqs/store/redis/redis_store.go` line 443 at r1](https://reviewable.io/reviews/harness/harness-core/39067#-NEqcZsb3t5QB_UHNjp8:-NEsnZWtB0OzokrGj8si:bfluihm) ([raw file](https://github.com/harness/harness-core/blob/03534200bd522b856e4e4552dd3aa3255f23c40b/queue-service/hsqs/store/redis/redis_store.go#L443)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Please add a todo to add stream metadata with registration like stream size, retry count etc.
</blockquote></details>

Added the todo

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39067)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`queue-service/hsqs/store/redis/redis_store.go` line 320 at r1](https://reviewable.io/reviews/harness/harness-core/39067#-NEqcDNj4RGb8Bx9Lnnd:-NFNj7Oe26pIO6nuJnkc:bn4tn22) ([raw file](https://github.com/harness/harness-core/blob/03534200bd522b856e4e4552dd3aa3255f23c40b/queue-service/hsqs/store/redis/redis_store.go#L320)):*
<details><summary><i>Previously, ankittiwari-harness (Ankit Tiwari) wrote…</i></summary><blockquote>

??
</blockquote></details>

I meant the comment could be updated

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39067)* status: 6 file(s) to review. 1 of 2 approvals obtained. 

___
*[`queue-service/hsqs/store/redis/benchmark_redis_store_test.go` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/39067#-NFO94Ci1XG5TlVbTypR:-NFO94Ci1XG5TlVbTypS:b-t2oex9) ([raw file](https://github.com/harness/harness-core/blob/f353d7ae174d14b3e68ac759a91abda9deba7ab4/queue-service/hsqs/store/redis/benchmark_redis_store_test.go#L25)):*
> ```Go
> )
> 
> var wg sync.WaitGroup
> ```

remove waitGroup
___
*[`queue-service/hsqs/store/redis/benchmark_redis_store_test.go` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/39067#-NFO90fm45kc1f5KDrXm:-NFO90fn-gI4yx4IyVB_:b22q5a5) ([raw file](https://github.com/harness/harness-core/blob/f353d7ae174d14b3e68ac759a91abda9deba7ab4/queue-service/hsqs/store/redis/benchmark_redis_store_test.go#L33)):*
> ```Go
> 	const queueCount = 100
> 	redisStore := NewRedisStore("localhost:6379")
> 	sema = make(chan struct{}, 10)
> ```

Remove sema



_Code quote:_
```Go
sema = make(chan struct{}, 10)
```

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39067)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39067)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`queue-service/hsqs/handler/end_to_end_handler_test.go` line 224 at r4](https://reviewable.io/reviews/harness/harness-core/39067#-NFSlZwcBKjiaenR32vL:-NFSlZwcBKjiaenR32vM:bvgvzzy) ([raw file](https://github.com/harness/harness-core/blob/56ce6928e2b03b95ebbbb9c07b8d2b0fb29c7a00/queue-service/hsqs/handler/end_to_end_handler_test.go#L224)):*
> ```Go
> 
> 	json.Unmarshal(data, &dequeResponses)
> 	// as only 5 messages are present in queue, it would return only 10 messages
> ```

is this comment correct? plus can we add description on each test what scenario we are testing



_Code quote:_
```Go
// as only 5 messages are present in queue, it would return only 10 messages
```
___
*[`queue-service/hsqs/store/redis/benchmark_redis_store_test.go` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/39067#-NFO94Ci1XG5TlVbTypR:-NFSlldv2mOElGoyLhFl:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f353d7ae174d14b3e68ac759a91abda9deba7ab4/queue-service/hsqs/store/redis/benchmark_redis_store_test.go#L25)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

remove waitGroup
</blockquote></details>

done
___
*[`queue-service/hsqs/store/redis/benchmark_redis_store_test.go` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/39067#-NFO90fm45kc1f5KDrXm:-NFSlmNd7Gr_Q5FcHzjU:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f353d7ae174d14b3e68ac759a91abda9deba7ab4/queue-service/hsqs/store/redis/benchmark_redis_store_test.go#L33)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Remove sema
</blockquote></details>

done

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39067)* status: 12 file(s) to review. 1 of 2 approvals obtained. 

___
*[`queue-service/hsqs/handler/end_to_end_handler_test.go` line 224 at r4](https://reviewable.io/reviews/harness/harness-core/39067#-NFSlZwcBKjiaenR32vL:-NFSrO_BCMttjhN1f28g:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/56ce6928e2b03b95ebbbb9c07b8d2b0fb29c7a00/queue-service/hsqs/handler/end_to_end_handler_test.go#L224)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

is this comment correct? plus can we add description on each test what scenario we are testing
</blockquote></details>

done

**Review by naidu-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 4 of 5 files at r3, 6 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39067)* status: 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39067)* status: :shipit: complete! ✓

**Pull request merged**
