### PR TITLE
[feat]: [PL-25915]: group name search in NG Ldap

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34442)

### CODE REVIEW

**Comment by piyush-harness** [comment]
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsService.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/34442#-N58uoYI6N-YSxPpqRqn:-N58uoYI6N-YSxPpqRqo:b-ost4hh) ([raw file](https://github.com/harness/harness-core/blob/1f85809c1fbe4fdec4f5f2ccfe4507b87aa7e68e/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsService.java#L27)):*
> ```Java
> import javax.validation.constraints.NotNull;
> import okhttp3.MultipartBody;
> import org.hibernate.validator.constraints.NotBlank;
> ```

Why is this hibernate validator import?

**Comment by piyush-harness** [comment]
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java` line 284 at r1](https://reviewable.io/reviews/harness/harness-core/34442#-N58vC6pCxFhhyOVFwG-:-N58vC6pCxFhhyOVFwG0:b-tastwo) ([raw file](https://github.com/harness/harness-core/blob/1f85809c1fbe4fdec4f5f2ccfe4507b87aa7e68e/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L284)):*
> ```Java
>   @Override
>   public Collection<LdapGroupResponse> searchLdapGroupsByName(
>       @NotBlank String accountIdentifier, @NotBlank String ldapId, @NotBlank String name) {
> ```

This should not be needed at impl as check is already defined in parent

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34442)* status: 20 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/ldap/search/NGLdapSearchService.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/34442#-N58vjkvEw6Qr64GU9jC:-N58vjkvEw6Qr64GU9jD:b2f6wx8) ([raw file](https://github.com/harness/harness-core/blob/1f85809c1fbe4fdec4f5f2ccfe4507b87aa7e68e/122-ng-authentication-settings/src/main/java/io/harness/ng/ldap/search/NGLdapSearchService.java#L68)):*
> ```Java
>             .executionTimeout(Duration.ofMillis(TaskData.DEFAULT_SYNC_CALL_TIMEOUT))
>             .accountId(settings.getAccountId())
>             .taskSetupAbstractions(buildAbstractions(settings.getAccountId(), null, null))
> ```

I think there's already a Utility class to build abstraction
___
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/ldap/search/NGLdapSearchService.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/34442#-N58vaJF-csYns3u2V23:-N58vaJF-csYns3u2V24:b9k7f26) ([raw file](https://github.com/harness/harness-core/blob/1f85809c1fbe4fdec4f5f2ccfe4507b87aa7e68e/122-ng-authentication-settings/src/main/java/io/harness/ng/ldap/search/NGLdapSearchService.java#L75)):*
> ```Java
> 
>     if (!(delegateResponseData instanceof LdapGroupSearchTaskResponse)) {
>       throw new SecretManagementException(SECRET_MANAGEMENT_ERROR, "Unknown Response from delegate", USER);
> ```

Why SECRET_MANAGEMENT_ERROR

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/34442)

**Pull request closed without merging**
