### PR TITLE
fix: [CDS-43600]: Executing the file which we create after decoding o…

### PR DESCRIPTION
**Pull request by bojanmicovic**
…n remote machine. Changing download artifact approach to go with old approach

## Describe your changes
The newest implementation is a process of executing customers script as it is written in Workflow. There are few steps for doing it:

1. Encode script
2. Transfer encoded script to a remote file
3. Create script which decodes and creates executable file (we store this filename in the code)
4. Execute the decoded script file from our code like before (powershell -f harness-executable.ps1)

We have separated Downloading the artifacts from executing the scripts, because earlier it was done in the same method.
This feature is under FFs DISABLE_WINRM_COMMAND_ENCODING and WINRM_SCRIPT_COMMAND_SPLIT.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41330)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java` line 166 at r2](https://reviewable.io/reviews/harness/harness-core/41330#-NIrcpb-ERNjE2MCGIaH:-NIrcpb-ERNjE2MCGIaI:b-xj3cf9) ([raw file](https://github.com/harness/harness-core/blob/14b170f64faa529b5bc585436742464ec2bf3873/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java#L166)):*
> ```Java
>       if (winrmScriptCommandSplit) {
>         String encodedScriptFilePath = getEncodedScriptFile(config.getWorkingDirectory(), config.getExecutionId());
>         exitCode = splitAndExecute(command, session, outputWriter, errorWriter, psScriptFile, encodedScriptFilePath);
> ```

nit: should we return early and remove the exit code variable altogether?

**Comment by sahilhindwani-harness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java` line 238 at r2](https://reviewable.io/reviews/harness/harness-core/41330#-NIrdZgi8AfCccImtAJZ:-NIrdZgi8AfCccImtAJ_:b-f1qwqc) ([raw file](https://github.com/harness/harness-core/blob/14b170f64faa529b5bc585436742464ec2bf3873/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java#L238)):*
> ```Java
> 
>   public static String executablePSFilePath(String workingDir, String suffix) {
>     return isEmpty(workingDir)
> ```

nit: we can use the above function here
return getEncodeScriptFile(..) + ".ps1"



_Code quote:_
```Java
        ? WINDOWS_TEMPFILE_LOCATION + HARNESS_EXECUTABLE_SCRIPT_FILENAME_PREFIX + randomAlphanumeric(10) + ".ps1"
```

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 17 of 18 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41330)* status: 19 file(s) to review. 0 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41330#-:-NIsdWnd54uq0sa_wol6:bnfp4nl)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java` line 166 at r2](https://reviewable.io/reviews/harness/harness-core/41330#-NIrcpb-ERNjE2MCGIaH:-NJ4c9VK77TcRN1p08o5:b-yeqbg4) ([raw file](https://github.com/harness/harness-core/blob/14b170f64faa529b5bc585436742464ec2bf3873/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java#L166)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: should we return early and remove the exit code variable altogether?
</blockquote></details>

As discussed, we will do in the follow up PR for this.

**Comment by sahilhindwani-harness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java` line 238 at r2](https://reviewable.io/reviews/harness/harness-core/41330#-NIrdZgi8AfCccImtAJZ:-NJ4cDcX3v8dWRQy2erq:b-9ukuur) ([raw file](https://github.com/harness/harness-core/blob/14b170f64faa529b5bc585436742464ec2bf3873/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java#L238)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: we can use the above function here
return getEncodeScriptFile(..) + ".ps1"
</blockquote></details>

As discussed, we will follow up this with next PR.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41330)* status: Some of the checks are too old. 19 file(s) to review.

**Comment by sahilhindwani-harness** [comment]
:lgtm:

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41330)* status: Some of the checks are too old. 19 file(s) to review.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41330)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41330#-:-NJ9rVdD2BVo_aPGzWJ6:bnfp4nl)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41330#-:-NJ9ykgb2HA_0HMjEezQ:bnfp4nl)* status: 19 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
:lgtm:
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41330#-:-NJB9pkE2HMh6gv5bNyS:bnfp4nl)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 13 of 18 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41330)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
