### PR TITLE
feat: [cds-48173]: moving rbac check from service step to individual steps

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
When we try to do rbac check for artifact connectors(passed as expression) inside service step,we are not able to get resolved variables in the service step itself,so for fixing it,we have moved all the rbac checks to their individual step.In this process we have moved rbac check to artifact step ,manifest step,config files,Azure Service Settings Step,Elastic group Service Settings Step .
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41603)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
We also need to handle io.harness.cdng.elastigroup.ElastigroupServiceSettingsStep

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java` line 180 at r2](https://reviewable.io/reviews/harness/harness-core/41603#-NJPAdwiENiWjCxiJkEF:-NJPAdwj16QOTxTPImwU:b-63cgq) ([raw file](https://github.com/harness/harness-core/blob/9c2f8d7fe35f06aef234226945d16f9afb81f2d8/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java#L180)):*
> ```Java
>     resolveExpressions(ambiance, artifacts);
> 
>     validateResources(ambiance, artifacts);
> ```

lets call this validateAccess(...)

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureServiceSettingsStep.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/41603#-NJPAo1MDF04-HYM9bg0:-NJPAo1MDF04-HYM9bg1:b-twked8) ([raw file](https://github.com/harness/harness-core/blob/9c2f8d7fe35f06aef234226945d16f9afb81f2d8/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureServiceSettingsStep.java#L91)):*
> ```Java
> 
>     expressionResolver.updateExpressions(ambiance, serviceSpec);
>     validateResources(ambiance, serviceSpec);
> ```

We should only check startupCommand/appSettings/connectionStrings

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 77 at r2](https://reviewable.io/reviews/harness/harness-core/41603#-NJPB1M4EP7O-lSk2_hY:-NJPB1M4EP7O-lSk2_hZ:bwsyzo0) ([raw file](https://github.com/harness/harness-core/blob/9c2f8d7fe35f06aef234226945d16f9afb81f2d8/125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L77)):*
> ```Java
>     cdExpressionResolver.updateExpressions(ambiance, configFiles);
> 
>     validateResources(ambiance, configFiles);
> ```

name change here..

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java` line 257 at r2](https://reviewable.io/reviews/harness/harness-core/41603#-NJPB7uo69Iy1Pjipz8L:-NJPB7uo69Iy1Pjipz8M:b-prsff8) ([raw file](https://github.com/harness/harness-core/blob/9c2f8d7fe35f06aef234226945d16f9afb81f2d8/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java#L257)):*
> ```Java
>           entityDetailProtoToRestMapper.createEntityDetailsDTO(new ArrayList<>(entityDetailsProto));
> 
>       pipelineRbacHelper.checkRuntimePermissions(ambiance, entityDetails, true);
> ```

can be moved outside of the loop

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/41603#-NJPBJM61H8waAOEn5tk:-NJPBJM70cqw1tlN3ZGQ:b-emarld) ([raw file](https://github.com/harness/harness-core/blob/9c2f8d7fe35f06aef234226945d16f9afb81f2d8/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java#L60)):*
> ```Java
>   @Inject EntityDetailProtoToRestMapper entityDetailProtoToRestMapper;
> 
>   void validateResources(Ambiance ambiance, NGServiceConfig serviceConfig) {
> ```

this should only accept variables and call this validateAccessForVariables(..)

**Comment by yogesh-chauhan** [comment]
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We also need to handle io.harness.cdng.elastigroup.ElastigroupServiceSettingsStep
</blockquote></details>

We should also call this from executEnvironmentPart(..)

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureServiceSettingsStep.java` line 115 at r4](https://reviewable.io/reviews/harness/harness-core/41603#-NJQSkLn72o9_53YhasJ:-NJQSkLn72o9_53YhasK:b-uaxeu) ([raw file](https://github.com/harness/harness-core/blob/b3811719833cccd2901149cbfef098180aaa67dd/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureServiceSettingsStep.java#L115)):*
> ```Java
>     checkForAccessOrThrow(ambiance, serviceSpec.getApplicationSettings());
>     checkForAccessOrThrow(ambiance, serviceSpec.getConnectionStrings());
>     checkForAccessOrThrow(ambiance, serviceSpec.getStartupCommand());
> ```

can we make just 1 call to pipelineRbacHelper instead of 3 here ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureServiceSettingsStep.java` line 208 at r5](https://reviewable.io/reviews/harness/harness-core/41603#-NJdk-0F0fclIwAjcG0M:-NJdk-0F0fclIwAjcG0N:b-l6mwxj) ([raw file](https://github.com/harness/harness-core/blob/0489ee678dae8081a0ecf6ae1bc5427a43e3a73b/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureServiceSettingsStep.java#L208)):*
> ```Java
>       pipeline : identifier : "pipwithmultiser" stages : -stage : identifier : "deploy" type : "Deployment" spec
>     : environment : environmentRef : "<+input>" environmentInputs : "<+input>" infrastructureDefinitions
>     : "<+input>" services : values : "<+input>"
> ```

remove

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 107 at r5](https://reviewable.io/reviews/harness/harness-core/41603#-NJdk38G61SAFf7ZNKoL:-NJdk38HBhUjhZBljaQw:b-kn4dca) ([raw file](https://github.com/harness/harness-core/blob/0489ee678dae8081a0ecf6ae1bc5427a43e3a73b/125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L107)):*
> ```Java
>     List<EntityDetail> entityDetails = new ArrayList<>();
> 
>     if (!EmptyPredicate.isEmpty(configFiles)) {
> ```

lets move this check to the first line 



_Code quote:_
```Java
P
```

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 113 at r5](https://reviewable.io/reviews/harness/harness-core/41603#-NJdk7i-2O-6sea9_k2A:-NJdk7i-2O-6sea9_k2B:b8giqd9) ([raw file](https://github.com/harness/harness-core/blob/0489ee678dae8081a0ecf6ae1bc5427a43e3a73b/125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L113)):*
> ```Java
>         List<EntityDetail> entityDetail =
>             entityDetailProtoToRestMapper.createEntityDetailsDTO(new ArrayList<>(entityDetailsProto));
>         if (!EmptyPredicate.isEmpty(entityDetail)) {
> ```

we should use isNotEmpty

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupServiceSettingsStep.java` line 117 at r5](https://reviewable.io/reviews/harness/harness-core/41603#-NJdkaDW2vll6ubFMeTF:-NJdkaDW2vll6ubFMeTG:bf3fckb) ([raw file](https://github.com/harness/harness-core/blob/0489ee678dae8081a0ecf6ae1bc5427a43e3a73b/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupServiceSettingsStep.java#L117)):*
> ```Java
>   private void checkForAccessOrThrow(Ambiance ambiance, StartupScriptConfiguration startupScriptConfiguration) {
>     Set<EntityDetailProtoDTO> entityDetailsProto =
>         entityReferenceExtractorUtils.extractReferredEntities(ambiance, startupScriptConfiguration);
> ```

lets use CollectionUtils.emptyIfNull(..)

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java` line 251 at r5](https://reviewable.io/reviews/harness/harness-core/41603#-NJdkpeS1Y_mLskuHciD:-NJdkpeS1Y_mLskuHciE:b-fcaowk) ([raw file](https://github.com/harness/harness-core/blob/0489ee678dae8081a0ecf6ae1bc5427a43e3a73b/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java#L251)):*
> ```Java
>   void checkForAccessOrThrow(Ambiance ambiance, List<ManifestAttributes> manifestAttributes) {
>     List<EntityDetail> entityDetails = new ArrayList<>();
>     if (!EmptyPredicate.isEmpty(manifestAttributes)) {
> ```

lets move to the first line

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java` line 254 at r5](https://reviewable.io/reviews/harness/harness-core/41603#-NJdksChDKMzMiQM9Wpp:-NJdksChDKMzMiQM9Wpq:biu4abx) ([raw file](https://github.com/harness/harness-core/blob/0489ee678dae8081a0ecf6ae1bc5427a43e3a73b/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java#L254)):*
> ```Java
>       for (ManifestAttributes manifestAttribute : manifestAttributes) {
>         Set<EntityDetailProtoDTO> entityDetailsProto =
>             entityReferenceExtractorUtils.extractReferredEntities(ambiance, manifestAttribute);
> ```

use emptyIfNull

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java` line 258 at r5](https://reviewable.io/reviews/harness/harness-core/41603#-NJdkvDx3ZTJ0AIyICKe:-NJdkvDx3ZTJ0AIyICKf:b-aztcjb) ([raw file](https://github.com/harness/harness-core/blob/0489ee678dae8081a0ecf6ae1bc5427a43e3a73b/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java#L258)):*
> ```Java
>         List<EntityDetail> entityDetail =
>             entityDetailProtoToRestMapper.createEntityDetailsDTO(new ArrayList<>(entityDetailsProto));
>         if (!EmptyPredicate.isEmpty(entityDetail)) {
> ```

isNotEmpty

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 7 files at r3, 1 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41603)* status: 11 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/artifact/steps/ArtifactsStepV2Test.java` line 172 at r5](https://reviewable.io/reviews/harness/harness-core/41603#-NJdlikLD2nr1fgNCEyj:-NJdlikLD2nr1fgNCEyk:bderiuc) ([raw file](https://github.com/harness/harness-core/blob/0489ee678dae8081a0ecf6ae1bc5427a43e3a73b/125-cd-nextgen/src/test/java/io/harness/cdng/artifact/steps/ArtifactsStepV2Test.java#L172)):*
> ```Java
>   private final Ambiance ambiance = buildAmbiance();
>   private final ArtifactTaskResponse successResponse = sampleArtifactTaskResponse();
>   private final ErrorNotifyResponseData errorNotifyResponse = sampleErrorNotifyResponse();
> ```

update these tests with verifying call to pipeline rbac helper

**Comment by vivekkarnatiharness** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureServiceSettingsStep.java` line 129 at r6](https://reviewable.io/reviews/harness/harness-core/41603#-NJfOqanD9nXJhCqWbE_:-NJfOqanD9nXJhCqWbEa:bvmvh39) ([raw file](https://github.com/harness/harness-core/blob/b9ea830d81962a7cf53dccbea35f9574d0dedb7a/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureServiceSettingsStep.java#L129)):*
> ```Java
>       return sourceSet;
>     }
>     if (EmptyPredicate.isEmpty(sourceSet)) {
> ```

this can be 
```
if sourceSet == null
```

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java` line 75 at r6](https://reviewable.io/reviews/harness/harness-core/41603#-NJfPIoj6_pXN5Osjl5T:-NJfPIoj6_pXN5Osjl5U:b-7t5wsf) ([raw file](https://github.com/harness/harness-core/blob/b9ea830d81962a7cf53dccbea35f9574d0dedb7a/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java#L75)):*
> ```Java
> 
>     List<EntityDetail> entityDetails = new ArrayList<>();
>     if (!EmptyPredicate.isEmpty(serviceVariables)) {
> ```

nit: we can use isNotEmpty and move this to the first line

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java` line 76 at r6](https://reviewable.io/reviews/harness/harness-core/41603#-NJfPLpv5yIm0P1TapRD:-NJfPLpv5yIm0P1TapRE:b1ylfc) ([raw file](https://github.com/harness/harness-core/blob/b9ea830d81962a7cf53dccbea35f9574d0dedb7a/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java#L76)):*
> ```Java
>     List<EntityDetail> entityDetails = new ArrayList<>();
>     if (!EmptyPredicate.isEmpty(serviceVariables)) {
>       for (NGVariable ngVariableChild : serviceVariables) {
> ```

nit: need not call this ngVariableChild, we can just call it ngVariable

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java` line 80 at r6](https://reviewable.io/reviews/harness/harness-core/41603#-NJfPRdy487B1IzK1nJ2:-NJfPRdy487B1IzK1nJ3:biu4abx) ([raw file](https://github.com/harness/harness-core/blob/b9ea830d81962a7cf53dccbea35f9574d0dedb7a/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java#L80)):*
> ```Java
>             entityReferenceExtractorUtils.extractReferredEntities(ambiance, ngVariableChild);
>         List<EntityDetail> entityDetail =
>             entityDetailProtoToRestMapper.createEntityDetailsDTO(new ArrayList<>(entityDetailsProto));
> ```

use emptyIfNull 



_Code quote:_
```Java
new ArrayList<>(entityDetailsProto)
```

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 11 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41603)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by vivekkarnatiharness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41603)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java` line 80 at r6](https://reviewable.io/reviews/harness/harness-core/41603#-NJfPRdy487B1IzK1nJ2:-NJiESspDpREefn36e6_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b9ea830d81962a7cf53dccbea35f9574d0dedb7a/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java#L80)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

use emptyIfNull 
</blockquote></details>

Done.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 13 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41603)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41603)* status: :shipit: complete! ✓

**Pull request merged**
