### PR TITLE
[feat]: [CDS-72530]: Fixed handling of newBranch case when base branch isn't provided for oldApiFLow.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Context: "isNewBranch" flag should be true when we move any file to git to a new branch and value should be used that passed by UI, but instead it was calculated by checking is base branch and target branch is null or not.

Changes: For "isNewBranch", used the value passed in the request rather than calculating. This fix is only for oldApis, new APIs should be fixed by introducing this flag and getting value from requests.

Impact: Move To Git flow.

Testing: Locally tested.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50003)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger messagecheck, uts

**Comment by adivishy1** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 964 at r1](https://reviewable.io/reviews/harness/harness-core/50003#-NZZHBd4Dt-Ux7-X8kws:-NZZHBd4Dt-Ux7-X8kwt:b7vk3cf) ([raw file](https://github.com/harness/harness-core/blob/442f9c5768ba72fa2510e7f5837d72275af0643c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L964)):*
> ```Java
>                                                  .filePath(moveConfigDTO.getFilePath())
>                                                  .commitMsg(moveConfigDTO.getCommitMessage())
>                                                  .isNewBranch(moveConfigDTO.isNewBranch())
> ```

Have you communicated the same to the UI dev to send bool?

**Review by adivishy1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50003)* status: Some of the checks are too old. 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 934 at r1](https://reviewable.io/reviews/harness/harness-core/50003#-NZZMCsK3-__tdLoIzD_:-NZZMCsK3-__tdLoIzDa:bkrmgj9) ([raw file](https://github.com/harness/harness-core/blob/442f9c5768ba72fa2510e7f5837d72275af0643c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L934)):*
> ```Java
>         accountIdentifier, orgIdentifier, projectIdentifier, pipelineIdentifier, false, null);
> 
>     Criteria metadataCriteria = pmsPipelineServiceHelper.getPipelineMetadataV2Criteria(
> ```

What is the different between metadataCriteria and metadataUpdate? 
Is criteria for fetching the pipelines and metadataUpdate for updating the metadata as part of this request?

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50003)* status: Some of the checks are too old. 1 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 934 at r1](https://reviewable.io/reviews/harness/harness-core/50003#-NZZMCsK3-__tdLoIzD_:-NZZPS5R3I5V17lt6qHk:b3uqq6h) ([raw file](https://github.com/harness/harness-core/blob/442f9c5768ba72fa2510e7f5837d72275af0643c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L934)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

What is the different between metadataCriteria and metadataUpdate? 
Is criteria for fetching the pipelines and metadataUpdate for updating the metadata as part of this request?
</blockquote></details>

During update operations(which called after the git flow for which this fix is made) we access 2 dbs collections one is PipelineEntity and the other is PipelineMetadataV2 db, and we 2 db operations hence we have used different helper methods to get their criteria.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 964 at r1](https://reviewable.io/reviews/harness/harness-core/50003#-NZZHBd4Dt-Ux7-X8kws:-NZZOwjPBbhx6OSy2aAC:bu5ncli) ([raw file](https://github.com/harness/harness-core/blob/442f9c5768ba72fa2510e7f5837d72275af0643c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L964)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Have you communicated the same to the UI dev to send bool?
</blockquote></details>

UI is already sending it.

**Review by adivishy1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50003)* status: Some of the checks are too old. 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50003)* status: Some of the checks are too old.

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
