### PR TITLE
feat: [CDS-47449]: Added support for Azure Repo.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
Azure Repo store added to Kubernetes and Native Helm swimlane. 

##Tested Cases

1. K8s manifest with and without values override (Azure Repo)
2. Helm with and without values override (Azure Repo)
3. Openshift with and without values override (Azure Repo)
4. Kustomize with and without values override (Azure Repo)

#Pipeline Yaml
```
pipeline:
  name: azureRepo K8s
  identifier: azureRepo_K8s
  projectIdentifier: CDS40577
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage
        identifier: stage
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: K8sRolling1
            serviceDefinition:
              spec:
                variables: []
                manifests:
                  - manifest:
                      identifier: manifest
                      type: K8sManifest
                      spec:
                        store:
                          type: AzureRepo
                          spec:
                            connectorRef: account.azure_pratyush_k8s
                            gitFetchType: Branch
                            paths:
                              - k8s/manifests/k8s/multipleFiles
                            branch: master
                        valuesPaths:
                          - k8s/manifests/k8s/multipleFiles/values.yaml
                        skipResourceVersioning: false
                  - manifest:
                      identifier: manifest2
                      type: Values
                      spec:
                        store:
                          type: AzureRepo
                          spec:
                            connectorRef: account.azure_pratyush_k8s
                            gitFetchType: Branch
                            paths:
                              - k8s/manifests/k8s/multipleFiles/overrideValues/values2.yaml
                            branch: master
                artifacts:
                  primary:
                    spec:
                      connectorRef: cdngdocker
                      imagePath: harness/todolist-sample
                      tag: latest
                    type: DockerRegistry
              type: Kubernetes
          infrastructure:
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: account.k8splayground
                namespace: default
                releaseName: release-<+INFRA_KEY>
            allowSimultaneousDeployments: false
            environmentRef: k8s
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        variables:
          - name: resourceNamePrefix
            type: String
            description: ""
            value: test
```

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40855)

### CODE REVIEW

**Review by achyuth-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40855)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 298 at r1](https://reviewable.io/reviews/harness/harness-core/40855#-NI7YWTo4QQJGdOiRIwG:-NI7YWTo4QQJGdOiRIwH:b-2zj69w) ([raw file](https://github.com/harness/harness-core/blob/24c426d7c285ba7e710052157d2221780d4d5f47/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L298)):*
> ```Java
>     AzureRepoConnectorDTO azureRepoConnectorDTO = (AzureRepoConnectorDTO) scmConnector;
>     SecretRefData tokenRef =
>         ((AzureRepoUsernameTokenDTO) ((AzureRepoHttpCredentialsDTO) azureRepoConnectorDTO.getAuthentication()
> ```

nit: can we avoid this double casting?

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40855)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 298 at r1](https://reviewable.io/reviews/harness/harness-core/40855#-NI7YWTo4QQJGdOiRIwG:-NI7b5ET4QkW-w5xZcqG:bs1q6wv) ([raw file](https://github.com/harness/harness-core/blob/24c426d7c285ba7e710052157d2221780d4d5f47/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L298)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

nit: can we avoid this double casting?
</blockquote></details>

No, I need this to get the tokenRef.

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40855)* status: 1 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/40855#-NICbvAo9TnZyeBV-soT:-NICbvAp4dcQeTsHvquV:bwmhkq9) (no related file):*
@goelpratyush99 can you pls share the manifest yaml sample in PR description. Also, are we handling capability checks for Azure Repo?

___

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40855)* status: 1. unresolved discussions. 1 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/40855#-NICbvAo9TnZyeBV-soT:-NICjDOZ-ENdzgzk8EsG:b-q8c77i) (no related file):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

@goelpratyush99 can you pls share the manifest yaml sample in PR description. Also, are we handling capability checks for Azure Repo?
</blockquote></details>

This is the manifest file https://github.com/wings-software/PipelinesNgAutomation/tree/master/k8s/manifests/k8s/multipleFiles same I have uploaded to azure repo https://dev.azure.com/goelpratyush/_git/kubernetesManifests?path=/k8s/manifests/k8s/multipleFiles. The capability check for azure repo is git so we don't require additional checks.

___

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40855)* status: :shipit: complete! ✓

**Pull request merged**
