### PR TITLE
feat: [CDS-58009]: delegate selector with expression list

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** Supporting the entire list of delegate selectors as an expression. 
In **TaskSelectorYaml.java**, we have added a logical handling for this case, to convert paramterField<List<TaskSelectorYaml>> to TaskSelector, for this case, we are always setting origin as default. 
In **StepUtils**, we have added handling for this field being an expression.

**Testing:** Tested locally for delegateSelectors being a fixed value, runtime input, en element of list as an expression, entire list being an expression.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47631)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> Reviewed 101 of 101 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47631)* status: 101 file(s) to review. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 438 at r1](https://reviewable.io/reviews/harness/harness-core/47631#-NV8DS9QC3rg-Y1JtUl3:-NV8DS9QC3rg-Y1JtUl4:b9ibhks) ([raw file](https://github.com/harness/harness-core/blob/c7c1ec803cecd8fed8aa90861cf401ab2180a1f5/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L438)):*
> ```Java
>         if (isDelegateSelectorsExpression(delegateSelectors)) {
>           setDelegateSelectors(delegateSelectors, withDelegateSelector);
>           return;
> ```

can we handle this in above hasDelegateSelectors and setOriginAndDelegateSelectors?
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/TaskSelectorYaml.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/47631#-NV8Dvg2-JDgDEVs4omh:-NV8Dvg2-JDgDEVs4omi:b-bzzx3b) ([raw file](https://github.com/harness/harness-core/blob/c7c1ec803cecd8fed8aa90861cf401ab2180a1f5/953-yaml-commons/src/main/java/io/harness/plancreator/steps/TaskSelectorYaml.java#L54)):*
> ```Java
>     }
> 
>     if (isNotEmpty(delegateSelectors.getValue()) && delegateSelectors.getValue().get(0) instanceof TaskSelectorYaml) {
> ```

why we need to check this?



_Code quote:_
```Java
delegateSelectors.getValue().get(0)
```

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47631)* status: 104 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 438 at r1](https://reviewable.io/reviews/harness/harness-core/47631#-NV8DS9QC3rg-Y1JtUl3:-NV8bZIE2QB7mv0v-v8Q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c7c1ec803cecd8fed8aa90861cf401ab2180a1f5/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L438)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we handle this in above hasDelegateSelectors and setOriginAndDelegateSelectors?
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/TaskSelectorYaml.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/47631#-NV8Dvg2-JDgDEVs4omh:-NVUdcDa8CstffzBAKBj:b4annpa) ([raw file](https://github.com/harness/harness-core/blob/c7c1ec803cecd8fed8aa90861cf401ab2180a1f5/953-yaml-commons/src/main/java/io/harness/plancreator/steps/TaskSelectorYaml.java#L54)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we need to check this?
</blockquote></details>

discussed offline 
Need this condition as we need to cast List<TaskSelectorYaml> to List<String> in case of entire list of delegateSelectors being an expression

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 6 files at r2, 1 of 3 files at r3, 2 of 3 files at r4, 3 of 3 files at r5, 5 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47631)* status: 110 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by r0610205 — APPROVED** [review]

**Review by jamie-harness — APPROVED** [review]

**Pull request merged**
