### PR TITLE
fix: [CDS-45805]: Do not remove keys from input set whose parent is an expressions in pipeline yaml

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
- fix: [CDS-45805]: WIP
- fix: [CDS-45805]: Basic impl with input sets save working
- fix: [CDS-45805]: Return using InputSetYamlHelper.setPipelineComponent method and fix tests
- feat: [CDS-0]: code format
- fix: [CDS-45805]: Use new strategy for normalizing FQNs wrt "pipeline"

## Describe your changes
Currently we have a logic for removing runtime inputs from input set yaml. This also removes fields whose key is identifier if there is no sibling 

Have made the change to check if a parent of that field in a runtime input/expression in the pipeline yaml, then we should retain it
Ex
pipeline yaml
```
infrastructureDefinition: <+input>
```

input set yaml
```
infrastructureDefinition: 
   identifier: infra
```

We should not remove this field with `identifier` key since its parent ( `infrastructureDefinition` ) is a runtime input in the pipeline yaml. This means that the input set provides a valid value for a field in the pipeline

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-45805]: https://harness.atlassian.net/browse/CDS-45805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-45805]: https://harness.atlassian.net/browse/CDS-45805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-45805]: https://harness.atlassian.net/browse/CDS-45805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-45805]: https://harness.atlassian.net/browse/CDS-45805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39670)

### CODE REVIEW

**Review by tchaurasiya — DISMISSED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39670)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
trigger ti1

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39670)* status: 2 file(s) to review.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 1 of 10 files at r4, 1 of 3 files at r5, 2 of 7 files at r6, 1 of 2 files at r7, 2 of 5 files at r8, 3 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39670)* status: :shipit: complete! ✓

**Pull request merged**
