### PR TITLE
feat: [CDS-58323]: migrated ambiance fields in Approval Instances

### PR DESCRIPTION
**Pull request by naman-goenka**
## Describe your changes
- Migration to add 5 ambiance fields required in db queries at first level in Approval Instances.
- For new instances, these fields will be auto-populated.
- Fields are not saved in nested object for db query performance. 
- **Specifics** : for each batch,  a bulk update is executed. Batch size: 500
- Testing - Local - Count: 129, Batch Size: 10
                - PR - Count: 654, Batch Size: 500

Screenshot 2023-04-03 at 3 01 01 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45985)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
@naman-goenka , why do we need this change? Can we have a quick sync around this?

**Comment by naman-goenka** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45985)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateAmbianceFieldsAtFirstLevelInApprovalInstancesMigration.java` line 73 at r3](https://reviewable.io/reviews/harness/harness-core/45985#-NSA59pwDGhKc3eGGmQY:-NSA59pwDGhKc3eGGmQZ:bqq3z44) ([raw file](https://github.com/harness/harness-core/blob/055036ff559e8ad98415e2af11f681179c0c0755/pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateAmbianceFieldsAtFirstLevelInApprovalInstancesMigration.java#L73)):*
> ```Java
>           Query query = new Query().with(Sort.by(Sort.Direction.ASC, ApprovalInstanceKeys.id)).with(pageable);
> 
>           approvalInstances = mongoTemplate.find(query, ApprovalInstance.class);
> ```

use iterator rather than using pagination
refer - https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21348420030/Limit+Data+in+Mongo+Queries#Best-Practices-To-Follow-To-Fetch-MongoDB-Data or nodeExecutionServiceImpl



_Code quote:_
```Java
mongoTemplate.find(query, ApprovalInstance.class)
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45985)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateAmbianceFieldsAtFirstLevelInApprovalInstancesMigration.java` line 63 at r4](https://reviewable.io/reviews/harness/harness-core/45985#-NSFKhk25otPNHhGiXMj:-NSFKhk25otPNHhGiXMk:b-dio65l) ([raw file](https://github.com/harness/harness-core/blob/c3c2ee776b3208f5c3d36ce4b861cece2c9ea683/pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateAmbianceFieldsAtFirstLevelInApprovalInstancesMigration.java#L63)):*
> ```Java
>       // only BATCH_SIZE records in memory at once
>       Query query = new Query();
>       query.cursorBatchSize(BATCH_SIZE);
> ```

we should use NO_LIMIT -> check doc as well
___
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateAmbianceFieldsAtFirstLevelInApprovalInstancesMigration.java` line 99 at r4](https://reviewable.io/reviews/harness/harness-core/45985#-NSFLk-R8hxvzBooSItV:-NSFLk-R8hxvzBooSItW:b8ojadz) ([raw file](https://github.com/harness/harness-core/blob/c3c2ee776b3208f5c3d36ce4b861cece2c9ea683/pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateAmbianceFieldsAtFirstLevelInApprovalInstancesMigration.java#L99)):*
> ```Java
>         log.error(String.format("%s Failed trying to fetch approval Instances or executing migration", DEBUG_LOG), e);
>       }
> ```

after loop if batch is not done, then update the approval (if approval instance list is nit empty)



_Code quote:_
```Java
approvalInstancesToBeUpdatedInCurrentBatch
```

**Comment by naman-goenka** [comment]
trigger ut7

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45985)* status: 5 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateAmbianceFieldsAtFirstLevelInApprovalInstancesMigration.java` line 63 at r4](https://reviewable.io/reviews/harness/harness-core/45985#-NSFKhk25otPNHhGiXMj:-NSFvtFqDnF4qtbVhGMf:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c3c2ee776b3208f5c3d36ce4b861cece2c9ea683/pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateAmbianceFieldsAtFirstLevelInApprovalInstancesMigration.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should use NO_LIMIT -> check doc as well
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateAmbianceFieldsAtFirstLevelInApprovalInstancesMigration.java` line 99 at r4](https://reviewable.io/reviews/harness/harness-core/45985#-NSFLk-R8hxvzBooSItV:-NSFvv_p-EAyxadYM4gV:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c3c2ee776b3208f5c3d36ce4b861cece2c9ea683/pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateAmbianceFieldsAtFirstLevelInApprovalInstancesMigration.java#L99)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

after loop if batch is not done, then update the approval (if approval instance list is nit empty)
</blockquote></details>

done

**Review by puthrayaharness — APPROVED** [review]

**Pull request merged**
