### PR TITLE
[feat]: [SRM-13434]: set deeplink URL for Service Health metric & CV

### PR DESCRIPTION
**Pull request by n00bitax**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42416)

### CODE REVIEW

**Comment by USB-05** [comment]
trigger gitleaks

**Comment by n00bitax** [comment]
trigger gitleaks

**Review by dhruv-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42416)* status: :shipit: complete! ✓

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42416)* status: :shipit: complete! ✓

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java` line 430 at r3](https://reviewable.io/reviews/harness/harness-core/42416#-NMbZxV6DyCNYiH-XA4M:-NMbZxV7E3U5VPiKfMeM:b249i60) ([raw file](https://github.com/harness/harness-core/blob/6aad80026bb33a5fecbc7c4240a5d38836d0ad56/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java#L430)):*
> ```Java
>     return metricsAnalyses;
>   }
>   public Map<String, Map<String, MetricsAnalysis>> getMapOfCvConfigIdAndFilteredMetrics(
> ```

Why this function needs to be public?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java` line 468 at r3](https://reviewable.io/reviews/harness/harness-core/42416#-NMbWDPI2cb7PSlhYDKH:-NMbWDPI2cb7PSlhYDKI:bfv12cj) ([raw file](https://github.com/harness/harness-core/blob/6aad80026bb33a5fecbc7c4240a5d38836d0ad56/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java#L468)):*
> ```Java
>   }
> 
>   private Optional<String> buildDeepLinkURL(MetricCVConfig metricCVConfig, AnalysisInfo metric) {
> ```

We should have the logic in MetricCVConfig only. Otherwise for each health Source type, we will have If else condition here. 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/VerifyStepMetricsAnalysisUtils.java` line 372 at r3](https://reviewable.io/reviews/harness/harness-core/42416#-NMbXVn5BN6j8v1ClV9d:-NMbXVn5BN6j8v1ClV9e:b-w5c91m) ([raw file](https://github.com/harness/harness-core/blob/6aad80026bb33a5fecbc7c4240a5d38836d0ad56/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/VerifyStepMetricsAnalysisUtils.java#L372)):*
> ```Java
>   }
> 
>   public static String setDeeplinkURLWithRange(DeploymentTimeSeriesAnalysis timeSeriesAnalysis, String deepLinkURL) {
> ```

This logic is specific to Prometheus and shouldn't be here. Have a function like : getDeeplinkUrl in CVConfig or metricAnalysisInfo that takes startTime, endTime, isHostLevel

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42416)* status: :shipit: complete! ✓

*[a discussion](https://reviewable.io/reviews/harness/harness-core/42416#-NMbfhRJ-ru3_61vlqiD:-NMbfhRJ-ru3_61vlqiE:b-w368dz) (no related file):*
Please add some test cases too.

___

**Review by AbhijithHarness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42416)* status: :shipit: complete! ✓

**Pull request merged**
