### PR TITLE
feat: [PL-31142]: Azure key vault managed identity

### PR DESCRIPTION
**Pull request by rijajoo**
## Describe your changes
Backend support for Azure Key Vault Managed Identity
Test cases: https://docs.google.com/spreadsheets/d/1gzoIF-cmDTsM7q9neVYIyTo-KYgYfp_iShCZanbJc7I/edit#gid=0

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45866)

### CODE REVIEW

**Comment by rijajoo** [comment]
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurekeyvaultconnector/AzureKeyVaultConnector.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/45866#-NRlDUKj5o7jkoUtp4bh:-NRlKxy75XNHGeZiU9eS:bkvexfv) ([raw file](https://github.com/harness/harness-core/blob/92c22e6b4c7566e04e8477f49017666c90a23b9e/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurekeyvaultconnector/AzureKeyVaultConnector.java#L48)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This should be false by default?
</blockquote></details>

We have used class "Boolean" and not primitive "boolean" because the mongo driver in CG does not translate null/ falsy values to false. The default for Boolean is null. And we have handled the null case everywhere.

**Comment by rijajoo** [comment]
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 378 at r1](https://reviewable.io/reviews/harness/harness-core/45866#-NRlE0AB78YmaCgHetG2:-NRlZle40cLHLFS4n6Mm:b-r06w74) ([raw file](https://github.com/harness/harness-core/blob/92c22e6b4c7566e04e8477f49017666c90a23b9e/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L378)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

When can an entry in the list be null?
</blockquote></details>

https://github.com/harness/harness-core/blob/bc621bb0939295ad685e634500cacfa48e79aa00/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L810
When the secretRefData is null, there's an entry added to the list as null.

**Comment by rijajoo** [comment]
trigger messagecheck

**Comment by rijajoo** [comment]
trigger ut6

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 8 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45866)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 8 of 15 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45866)* status: :shipit: complete! ✓

**Pull request merged**
