### PR TITLE
feat: [CDS-50307]: Skipping InstanceSyncPerpetualTaskMigrationJob for instance sync v2 and KUBERNETES_CLUSTER

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Describe your changes
For Instance sync v2 skipping the InstanceSyncPerpetualTaskMigrationJob for instance sync v2 and KUBERNETES_CLUSTER
We are doing this because we already going to add migration mechanism for instance sync v2 and if we don’t skip this then both migration job interferes each other
One more reason is when we enable this FF INSTANCE_SYNC_V2_CG we do not want the migration job to recreate the Perpetual task of instance sync v1

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42431)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42431)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/42431#-NLR-fpL-zT_b1VCt5jn:-NLR-fpM2RWIeIxbgzGK:bqec8lw) ([raw file](https://github.com/harness/harness-core/blob/7bbb4fefeae3429319e9ea24498da8994e243a30/400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java#L89)):*
> ```Java
>     Set<ContainerMetadata> containersMetadata = getContainerMetadataFromInstances(appId, infraMappingId);
> 
>     if (featureFlagService.isEnabled(INSTANCE_SYNC_V2_CG, infrastructureMapping.getAccountId())
> ```

please add a comment why we're adding this, as it is a bit confusing for someone who will try to use this method for whatever reason and find this

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42431)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/42431#-NLR-fpL-zT_b1VCt5jn:-NLU4H-J32cZiu10zbhw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7bbb4fefeae3429319e9ea24498da8994e243a30/400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java#L89)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

please add a comment why we're adding this, as it is a bit confusing for someone who will try to use this method for whatever reason and find this 
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/42431#-NLR-fpL-zT_b1VCt5jn:-NLUMWkg4_0NiW4if2kZ:bz5u7h4) ([raw file](https://github.com/harness/harness-core/blob/7bbb4fefeae3429319e9ea24498da8994e243a30/400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java#L89)):*
<details><summary><i>Previously, namantalaycha10 (Naman Talaycha) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can we add more verbose comment? Let's add the issue we were facing and why we disabled it.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42431)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42431)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/42431#-NLR-fpL-zT_b1VCt5jn:-NLUhrNoAyKeCJkorZDS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7bbb4fefeae3429319e9ea24498da8994e243a30/400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java#L89)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we add more verbose comment? Let's add the issue we were facing and why we disabled it.
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42431)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42431)* status: 2 file(s) to review.

**Review by abosii-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42431#-:-NLUvXin2-8szHoOIYNX:bnfp4nl)* status: 2 file(s) to review.

**Review by namantalaycha10 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42431)* status: 2 file(s) to review.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42431)* status: :shipit: complete! ✓

**Pull request merged**
