### PR TITLE
[feat]: [CDS-72587]: Integrated get batch file with default branch caching

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have added code to integrate get batch file flow for templates with default branch caching. Have tested out the get batch file for templates with git default branch caching FF enabled and its working as expected.
 
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49707)

### CODE REVIEW

**Comment by mohitg0795** [comment]
> ## Describe your changes
> Have added code to integrate get batch file flow for templates with default branch caching. Have tested out the get batch file for templates with git default branch caching FF enabled and its working as expected.
> 
> ## Checklist
> * [ ]  I've documented the changes in the PR description.
> * [ ]  I've tested this change either in PR or local environment.
> * [ ]  If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.
> 
> ## Comment Triggers
> Build triggers
> ## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)
> PR Check triggers
> ## PR check failures and solutions
> https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions
> 
> ## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)
> This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49707)

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/beans/request/GitFileRequestV2.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/49707#-NYr1MFQC3B0LYbxdWun:-NYr1MFR6Ego1kSli0zB:b-ojb51o) ([raw file](https://github.com/harness/harness-core/blob/b234a7b7043af41576fdd74e1ea245b26cc1b54e/952-scm-java-client/src/main/java/io/harness/beans/request/GitFileRequestV2.java#L30)):*
> ```Java
>   ScmConnector scmConnector;
>   boolean getOnlyFileContent;
>   String inputBranch;
> ```

I think we shouldn't touch original request dtos. With growing fields with similar names, it may become confusing with time to follow up.

Please see if we can have some workaround here instead of directly feeding in the new field here.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49707)* status: 9 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/beans/request/GitFileRequestV2.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/49707#-NYr1MFQC3B0LYbxdWun:-NYwF2gX9l-WZQ79QuHO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b234a7b7043af41576fdd74e1ea245b26cc1b54e/952-scm-java-client/src/main/java/io/harness/beans/request/GitFileRequestV2.java#L30)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we shouldn't touch original request dtos. With growing fields with similar names, it may become confusing with time to follow up.

Please see if we can have some workaround here instead of directly feeding in the new field here.
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitDefaultBranchCacheHelper.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/49707#-NZ18D_Q4qLf7jv4nBQA:-NZ18D_Q4qLf7jv4nBQB:buhgj8) ([raw file](https://github.com/harness/harness-core/blob/9f8d39cfafe3b3f9fa45034e743c454653eec0e2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitDefaultBranchCacheHelper.java#L79)):*
> ```Java
> 
>   public void cacheDefaultBranchResponse(String accountIdentifier, ScmConnector scmConnector, String repoName,
>       boolean isInputBranchEmpty, String resolvedBranch, String responseBranch) {
> ```

can we name it "isRequestBranchEmpty"? Also, whats the difference b/w resolvedBranch and responseBranch?

For DefaultBranchCacheHelper, there's no understanding of resolved branch and response branch. Always write methods as per their layers and not as per the callers.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 426 at r4](https://reviewable.io/reviews/harness/harness-core/49707#-NZ19fDh7Gc1cIsedo4E:-NZ19fDh7Gc1cIsedo4F:b-py8n1w) ([raw file](https://github.com/harness/harness-core/blob/9f8d39cfafe3b3f9fa45034e743c454653eec0e2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L426)):*
> ```Java
>                   scmGetFileByBranchRequestDTO.getConnectorRef(), scmGetFileByBranchRequestDTO.getRepoName());
> 
>           String resolvedBranch = gitDefaultBranchCacheHelper.setDefaultBranchIfInputBranchEmpty(
> ```

I think this method name should be "getDefaultBranch..." instead of "set...".

Also, do you think instead of "resolvedBranch", "workingBranch" could be a better name?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49707)* status: 12 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitDefaultBranchCacheHelper.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/49707#-NZ18D_Q4qLf7jv4nBQA:-NZ4XSJjCJVgAFrduzSa:b-fi187r) ([raw file](https://github.com/harness/harness-core/blob/9f8d39cfafe3b3f9fa45034e743c454653eec0e2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitDefaultBranchCacheHelper.java#L79)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we name it "isRequestBranchEmpty"? Also, whats the difference b/w resolvedBranch and responseBranch?

For DefaultBranchCacheHelper, there's no understanding of resolved branch and response branch. Always write methods as per their layers and not as per the callers.
</blockquote></details>

updated the variable name,
resolvedBranch -> whatever is the final branch we get from cache
responseBranch -> is the branch returned in the GitFileResponse 

done
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1104 at r4](https://reviewable.io/reviews/harness/harness-core/49707#-NZ18jJHD82fs9U1UDrV:-NZ4ZOx_DanQ3R_fHxx8:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9f8d39cfafe3b3f9fa45034e743c454653eec0e2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1104)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

nit: A simpler and cleaner change would've been to rename "request" argument to something else and parse out getGitFileRequestV2() output to variable name "request"
</blockquote></details>

done
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 426 at r4](https://reviewable.io/reviews/harness/harness-core/49707#-NZ19fDh7Gc1cIsedo4E:-NZ4Y99z4gU94NMxlI3m:bwfx9kj) ([raw file](https://github.com/harness/harness-core/blob/9f8d39cfafe3b3f9fa45034e743c454653eec0e2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L426)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think this method name should be "getDefaultBranch..." instead of "set...".

Also, do you think instead of "resolvedBranch", "workingBranch" could be a better name?
</blockquote></details>

agreed, done

**Pull request closed without merging**
