### PR TITLE
[feat]: [CDS-81261]: Added Batch Impl in Git-SDK for Gettting Files in Batches.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Changes: Implemented Batch Processing at SDK side (Grpc Requests will be sent in batches to GitSide for fetching remote Entities)

Testing:

- Reduced the batch size to One to see if different batches were formed and request were sent in Batches.

- Manually Added 64 GRPC calls to see if Template service timed out or not. 

- GetRemote Calls were made for straight 5 minutes but even then template service didn't timeout.

- If one of the template is not present we obtain the same response as the older one before this change.

Screenshot 2023-12-06 at 5 59 53 PM

Screenshot 2023-12-06 at 5 56 30 PM

Screenshot 2023-12-06 at 5 56 48 PM

Screenshot 2023-12-08 at 11 31 17 AM

Screenshot 2023-12-08 at 12 04 49 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56318)

### CODE REVIEW

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56318)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1062 at r1](https://reviewable.io/reviews/harness/harness-core/56318#-NkvFY8_44a98Iq-68NK:-NkvFY8_44a98Iq-68NL:b-2dym9k) ([raw file](https://github.com/harness/harness-core/blob/508e790f152b37e77228d33e9e39001327c173dd/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1062)):*
> ```Java
>   }
> 
>   private static List<Environment> getBatch(List<Environment> environmentEntities, int i) {
> ```

why are we changing in envs?

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56318)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 368 at r1](https://reviewable.io/reviews/harness/harness-core/56318#-NkwHsPE7wNNk5-b22q0:-NkwHsPE7wNNk5-b22q1:bf9ox1z) ([raw file](https://github.com/harness/harness-core/blob/0eb39aa0e63fee34968159ffdb32457cc996f2a4/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L368)):*
> ```Java
> 
>     // adding last batch when the last batch size is less than BATCH_SIZE.
>     if (itr > 0 && itr <= GET_FILE_REQUEST_BATCH_SIZE) {
> ```

why do we need the 2nd condition here? Only itr!=0 should be good enough i guess

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56318)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1062 at r1](https://reviewable.io/reviews/harness/harness-core/56318#-NkvFY8_44a98Iq-68NK:-Nkz6bAk4QoApttvRLVn:b-53t18k) ([raw file](https://github.com/harness/harness-core/blob/508e790f152b37e77228d33e9e39001327c173dd/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1062)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why are we changing in envs?
</blockquote></details>

Removed Unused Code.
___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 368 at r1](https://reviewable.io/reviews/harness/harness-core/56318#-NkwHsPE7wNNk5-b22q0:-Nkz6dyY2Eop_7IkmkQK:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/0eb39aa0e63fee34968159ffdb32457cc996f2a4/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L368)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why do we need the 2nd condition here? Only itr!=0 should be good enough i guess
</blockquote></details>

Done

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger messagecheck

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56318)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 314 at r5](https://reviewable.io/reviews/harness/harness-core/56318#-Nl4otaKBHfYlw-87Bfb:-Nl6poCcBD4GpZo2ggzv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/123f7b04182ad830ceb4c6851752df696db25324/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L314)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can't we simply use batch.getSize() ?
</blockquote></details>

Done.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger ut9

**Review by adivishy1 — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56318)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56318)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 307 at r7](https://reviewable.io/reviews/harness/harness-core/56318#-NlPztgI1mtaNOrOCR39:-NlPztgI1mtaNOrOCR3A:bu2ozhk) ([raw file](https://github.com/harness/harness-core/blob/3786da71f30709834f55635d663c9f9adcda9ab9/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L307)):*
> ```Java
> 
>   @VisibleForTesting
>   ScmGetBatchFilesResponse processGetFileRequestInBatches(
> ```

I think the method name should be : processGetBatchFilesRequestInBlocks() or something similar.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56318)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by senjucanon2** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56318)* status: <span>:shipit:</span> complete! ✓

**Comment by senjucanon2** [comment]
trigger review

**Review by yogesh-chauhan — APPROVED** [review]

**Pull request merged**
