### PR TITLE
[feat]: [CDS-42497]: Added templates for WinRm

### PR DESCRIPTION
**Pull request by ivan-83**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37096)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* Code issue 2 Code issues 
* Anti-pattern 2 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37096)

**Comment by ivan-83** [comment]
trigger messagecheck

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 62 of 62 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37096)* status: :shipit: complete! ✓

**Review by vladimir-peric — DISMISSED** [review]
> Reviewed 62 of 62 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37096)* status: :shipit: complete! ✓

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 39 of 39 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37096)* status: 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java` line 437 at r2](https://reviewable.io/reviews/harness/harness-core/37096#-NBNkS7JDkmAiGzGAuQG:-NBNkS7JDkmAiGzGAuQH:bg1rvtj) ([raw file](https://github.com/harness/harness-core/blob/5180d4eeebf14f37d410305b9a5b03a8fb40210f/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java#L437)):*
> ```Java
>         .name(stepCommandUnit.getName())
>         .script(isEmpty(envVariablesMap)
>                 ? getShellScript(ambiance, spec.getSource())
> ```

can we restrict this to powershell only.

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37096)* status: :shipit: complete! ✓

**Pull request merged**
