### PR TITLE
feat: [PLG-2994]: Add deletion credit api used by harness support user

### PR DESCRIPTION
**Pull request by Xin-Harness**
## Describe your changes
retrieve the current existing credit
Pasted Graphic 5
delete the credit given the credit id and customer account identifier
Pasted Graphic 6
credit get successfully deleted, no longer exist in get result
Pasted Graphic 7
delete the credit that already been delete in the db, raise error
Pasted Graphic 8

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54695)

### CODE REVIEW

**Comment by Xin-Harness** [comment]
trigger uts

**Review by neelam-harness — APPROVED** [review]

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54695)* status: 6 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 771 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkRUol8ITeCp0_33JB:-NhkRUom5GytYPpi5Ss5:b-o0ltr9) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/400-rest/src/main/java/software/wings/resources/AccountResource.java#L771)):*
> ```Java
> 
>   @DELETE
>   @Path("{accountId}/ng/credit/{creditId}")
> ```

creditId should be a query param because creditId belongs to clientAccountId which is part of the query param. Currently, it feels as if creditId belongs to accountId, which is obviously not the case.
___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 780 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkT2Nt5YbQFDCQOb0o:-NhkT2Nu32q01ggpGfvl:b-o9lqbi) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/400-rest/src/main/java/software/wings/resources/AccountResource.java#L780)):*
> ```Java
>     }
>     if (harnessUserGroupService.isHarnessSupportUser(existingUser.getUuid())) {
>       return new RestResponse<>(getResponse(adminCreditHttpClient.deleteAccountCredit(creditId)));
> ```

lest send clientAccountId in .deleteAccountCredit() so that a accountId check can be done in the service layer
___
*[`930-ng-license-manager/src/main/java/io/harness/credit/resource/AdminCreditResource.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkTCLb05MOTn5BFoRs:-NhkTCLcAIoasTHOGiO8:bn59vf3) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/930-ng-license-manager/src/main/java/io/harness/credit/resource/AdminCreditResource.java#L119)):*
> ```Java
>   @InternalApi
>   public ResponseDTO<Void>
>   deleteCredit(@PathParam("creditId") String creditId) {
> ```

accountId will also come as a pathparam
___
*[`930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkTSHpBu3WRWqf1EN8:-NhkTSHpBu3WRWqf1EN9:b-czwzpq) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java#L136)):*
> ```Java
> 
>   public void deleteCredit(String creditId) throws InvalidRequestException {
>     Optional<Credit> maybeCredit = creditRepository.findById(creditId);
> ```

lets do a accountId check, lets compare accountId in the args with accountId in the credit

**Comment by Xin-Harness** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/54695)_ status: 6 file(s) to review. 1 change requests. 1 of 2 approvals obtained.
> 
> _[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 771 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkRUol8ITeCp0_33JB:-NhkRUom5GytYPpi5Ss5:b-o0ltr9) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/400-rest/src/main/java/software/wings/resources/AccountResource.java#L771)):_
> 
> > ```java
> >   @DELETE
> >   @Path("{accountId}/ng/credit/{creditId}")
> > ```
> 
> creditId should be a query param because creditId belongs to clientAccountId which is part of the query param. Currently, it feels as if creditId belongs to accountId, which is obviously not the case.
> 
> _[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 780 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkT2Nt5YbQFDCQOb0o:-NhkT2Nu32q01ggpGfvl:b-o9lqbi) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/400-rest/src/main/java/software/wings/resources/AccountResource.java#L780)):_
> 
> > ```java
> >     }
> >     if (harnessUserGroupService.isHarnessSupportUser(existingUser.getUuid())) {
> >       return new RestResponse<>(getResponse(adminCreditHttpClient.deleteAccountCredit(creditId)));
> > ```
> 
> lest send clientAccountId in .deleteAccountCredit() so that a accountId check can be done in the service layer
> 
> _[`930-ng-license-manager/src/main/java/io/harness/credit/resource/AdminCreditResource.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkTCLb05MOTn5BFoRs:-NhkTCLcAIoasTHOGiO8:bn59vf3) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/930-ng-license-manager/src/main/java/io/harness/credit/resource/AdminCreditResource.java#L119)):_
> 
> > ```java
> >   @InternalApi
> >   public ResponseDTO<Void>
> >   deleteCredit(@PathParam("creditId") String creditId) {
> > ```
> 
> accountId will also come as a pathparam
> 
> _[`930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkTSHpBu3WRWqf1EN8:-NhkTSHpBu3WRWqf1EN9:b-czwzpq) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java#L136)):_
> 
> > ```java
> >   public void deleteCredit(String creditId) throws InvalidRequestException {
> >     Optional<Credit> maybeCredit = creditRepository.findById(creditId);
> > ```
> 
> lets do a accountId check, lets compare accountId in the args with accountId in the credit

**Review by Xin-Harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54695)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 771 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkRUol8ITeCp0_33JB:-NhlKm6xDSS4QGDGwKIr:bb7izuv) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/400-rest/src/main/java/software/wings/resources/AccountResource.java#L771)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

creditId should be a query param because creditId belongs to clientAccountId which is part of the query param. Currently, it feels as if creditId belongs to accountId, which is obviously not the case.
</blockquote></details>

Thanks for giving the suggestions, I will explain the reason why I have come up with this solution and didn't choose the way you have suggested which I also considered before. 

In our current system, the resource id that needs to be deleted are all passed as path parameter rather than query parameter, and the accountId is passed as query parameter. Take the below API as example: 

In our case since both  harness support accountid and client accountid.  As we all know harness support accountid goes in path parameter without doubt, in this case, client account parameter goes in query parameter. 



_Code snippet:_
```Java
  @DELETE
  @Path("{delegateId}/delegate-tags")
  @Timed
  @ExceptionMetered
  @AuthRule(permissionType = MANAGE_DELEGATES)
  @ApiKeyAuthorized(permissionType = MANAGE_DELEGATES)
  public RestResponse<DelegateDTO> deleteTags(
      @PathParam("delegateId") @NotEmpty String delegateId, @QueryParam("accountId") @NotEmpty String accountId) {
```
___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 780 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkT2Nt5YbQFDCQOb0o:-NhlN1Zk97WcsBrbIHg8:b-ecu0ms) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/400-rest/src/main/java/software/wings/resources/AccountResource.java#L780)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

lest send clientAccountId in .deleteAccountCredit() so that a accountId check can be done in the service layer
</blockquote></details>

Since the accountId existence check already done in the CG manager which manages account table, and there is no payload pass in the request body, so there is no need and won't be able to compare payload accountId with path parameter accountId. Give the below reason: 
1.It is because the good practice of DELETE API would not include body payload, so we would not include Credit as payload in the delete request,
2. credit UUID is the unique identifier of the resource we want to delete. 
3.  accountId check id done in CG manager which check if the client account exist in the current cluster. So we shouldn't check it repeatedly on Ng side.   The existing ng side account check for update API is used to verify payload info is same as path info, which doesn't apply to our case. 

Therefore we should not send clientAccountId in delete Account Credit().
___
*[`930-ng-license-manager/src/main/java/io/harness/credit/resource/AdminCreditResource.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkTCLb05MOTn5BFoRs:-NhlO92S-pHaiUyM2fU1:b-ze0eft) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/930-ng-license-manager/src/main/java/io/harness/credit/resource/AdminCreditResource.java#L119)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

accountId will also come as a pathparam
</blockquote></details>

Please check the above reply, it explains why it shouldn't come as path param.
___
*[`930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkTSHpBu3WRWqf1EN8:-NhlODW8EVJzSJxTFpLb:bdood13) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java#L136)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

lets do a accountId check, lets compare accountId in the args with accountId in the credit
</blockquote></details>

Same as above comments I provided, since we are not sending Credit as payload in delete method, so we don't need to verify the payload accountId is same as path accountId.

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54695)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 771 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkRUol8ITeCp0_33JB:-Nhlod5N-rtURf8vBitd:b-tm6b6i) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/400-rest/src/main/java/software/wings/resources/AccountResource.java#L771)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

Thanks for giving the suggestions, I will explain the reason why I have come up with this solution and didn't choose the way you have suggested which I also considered before. 

In our current system, the resource id that needs to be deleted are all passed as path parameter rather than query parameter, and the accountId is passed as query parameter. Take the below API as example: 

In our case since both  harness support accountid and client accountid.  As we all know harness support accountid goes in path parameter without doubt, in this case, client account parameter goes in query parameter.
</blockquote></details>

Credit resource does not exist in CG rather exists in NG, so creditId can be part of query param 
___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 780 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkT2Nt5YbQFDCQOb0o:-NhlorYa9Z-cfNbBG8jn:bxbse63) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/400-rest/src/main/java/software/wings/resources/AccountResource.java#L780)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

Since the accountId existence check already done in the CG manager which manages account table, and there is no payload pass in the request body, so there is no need and won't be able to compare payload accountId with path parameter accountId. Give the below reason: 
1.It is because the good practice of DELETE API would not include body payload, so we would not include Credit as payload in the delete request,
2. credit UUID is the unique identifier of the resource we want to delete. 
3.  accountId check id done in CG manager which check if the client account exist in the current cluster. So we shouldn't check it repeatedly on Ng side.   The existing ng side account check for update API is used to verify payload info is same as path info, which doesn't apply to our case. 

Therefore we should not send clientAccountId in delete Account Credit().
</blockquote></details>

We don't need any payload here.
Account existence check is to check whether clientAccountId is present or not in the same cluster.
What's the guarantee that creditId belongs to clientAccountId, which is a paramount check that we should have.

**Review by Xin-Harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54695)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 771 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkRUol8ITeCp0_33JB:-Nhm-thD8skbTgF03VQ4:b-1hninm) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/400-rest/src/main/java/software/wings/resources/AccountResource.java#L771)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

Credit resource does not exist in CG rather exists in NG, so creditId can be part of query param
</blockquote></details>

Also query parameter is used to limit the resource we want to filter, since it is the single source we want to reach out to, the it should goes to path parameter. Please check the link below for best practice. 

https://stackoverflow.com/questions/75494035/is-it-bad-practice-to-include-id-of-object-i-want-to-delete-in-url-query

here is what the best practice:

 In general, if you have a RESTful API, and you want to refer to a resource you use URL parameters as you want to identify that single resource.

So you would have something like

```javascript
DELETE /lectures/:lectureId
```

As it's a single resource of `lectures`.

However, you may want to delete multiple resources and in that case, it is a common practice to use query parameters

```javascript
DELETE lectures?id=LECTURE_1&id=LECTURE_2&id=LECTURE_3...
```
___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 780 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkT2Nt5YbQFDCQOb0o:-Nhm0ArfBBFUHfrjBafi:b62h9dy) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/400-rest/src/main/java/software/wings/resources/AccountResource.java#L780)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

We don't need any payload here.
Account existence check is to check whether clientAccountId is present or not in the same cluster.
What's the guarantee that creditId belongs to clientAccountId, which is a paramount check that we should have.
</blockquote></details>

That's a very valid point, the below line covers the case already.



_Code snippet:_
```Java
validateAccountExistence(clientAccountId);
```

**Review by kapil-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54695)* status: 6 file(s) to review. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 780 at r1](https://reviewable.io/reviews/harness/harness-core/54695#-NhkT2Nt5YbQFDCQOb0o:-NhmLOA1-5sf8sTrS0x9:b-4lvfby) ([raw file](https://github.com/harness/harness-core/blob/290f27d15b2de8f1fe3869b74cca24cde82f7dc1/400-rest/src/main/java/software/wings/resources/AccountResource.java#L780)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

That's a very valid point, the below line covers the case already.
</blockquote></details>

nit: clientAccountId should be the 1st args e.g. adminCreditHttpClient.deleteAccountCredit(clientAccountId , creditId))
___
*[`930-ng-license-manager/src/main/java/io/harness/credit/resource/AdminCreditResource.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/54695#-NhmM0IJ9eyaR4PV09-w:-NhmM0IJ9eyaR4PV09-x:by65fix) ([raw file](https://github.com/harness/harness-core/blob/d9e8f3d0f6b5a261395592972406ee6e3f38e585/930-ng-license-manager/src/main/java/io/harness/credit/resource/AdminCreditResource.java#L119)):*
> ```Java
>   @InternalApi
>   public ResponseDTO<Void>
>   deleteCredit(@PathParam("creditId") String creditId,
> ```

lets use fully qualified names and not short forms, lets rename it to creditIdentifier
take care of it in next PR

**Comment by Xin-Harness** [comment]
trigger uts

**Review by neelam-harness — APPROVED** [review]

**Comment by Xin-Harness** [comment]
trigger uts

**Comment by Xin-Harness** [comment]
trigger review

**Pull request merged**
