### PR TITLE
feat: [PIE-6837]: Update trigger Delete permission

### PR DESCRIPTION
**Pull request by sribalij**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41278)

### CODE REVIEW

**Review by vcalasansh — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41278)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41278)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java` line 191 at r3](https://reviewable.io/reviews/harness/harness-core/41278#-NJco8W53d2Su8g79OxN:-NJco8W53d2Su8g79OxO:b-g2gtlf) ([raw file](https://github.com/harness/harness-core/blob/2548391385f577585a651492dbf60c38eec7661f/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java#L191)):*
> ```Java
>   @Path("{triggerIdentifier}")
>   @ApiOperation(value = "Delete a trigger by identifier", nickname = "deleteTrigger")
>   @NGAccessControlCheck(resourceType = "PIPELINE", permission = PipelineRbacPermissions.PIPELINE_EXECUTE)
> ```

so anyone can delete the trigger? Should we check for Pipeline create and edit assuming there's no explicit permissions for triggers.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41278)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java` line 186 at r3](https://reviewable.io/reviews/harness/harness-core/41278#-NJcru1BDKNQjXe5x7mR:-NJcru1C53YnyFYE8aVj:b-u9pgt5) ([raw file](https://github.com/harness/harness-core/blob/cf94a976d5aea7e65052c6ad4029e5039bc1799d/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java#L186)):*
> ```Java
> 
>     accessControlClient.checkForAccessOrThrow(ResourceScope.of(accountIdentifier, orgIdentifier, projectIdentifier),
>         Resource.of("PIPELINE", targetIdentifier), PipelineRbacPermissions.PIPELINE_EXECUTE);
> ```

Why both pipeline delete and execute are required?

**Review by sribalij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41278)* status: Some of the checks are too old. 2 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java` line 191 at r3](https://reviewable.io/reviews/harness/harness-core/41278#-NJco8W53d2Su8g79OxN:-NJrpkgPCtD52SHYQ8Le:b-iutyfi) ([raw file](https://github.com/harness/harness-core/blob/2548391385f577585a651492dbf60c38eec7661f/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java#L191)):*
> Let me confirm with Product and get back. Earlier they had EXECUTE as well and did not want to remove that.
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java` line 186 at r3](https://reviewable.io/reviews/harness/harness-core/41278#-NJcru1BDKNQjXe5x7mR:-NJrpNth-gZLmmdRPRVH:b-m4fzye) ([raw file](https://github.com/harness/harness-core/blob/cf94a976d5aea7e65052c6ad4029e5039bc1799d/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java#L186)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why both pipeline delete and execute are required?
</blockquote></details>

Let me confirm with Product and get back. Earlier they had EXECUTE as well and did not want to remove that.

**Review by sribalij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41278)* status: 3 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java` line 191 at r3](https://reviewable.io/reviews/harness/harness-core/41278#-NJco8W53d2Su8g79OxN:-NJwYTUI5Q0IUn23JGuL:b-vm4zaa) ([raw file](https://github.com/harness/harness-core/blob/2548391385f577585a651492dbf60c38eec7661f/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java#L191)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

> Let me confirm with Product and get back. Earlier they had EXECUTE as well and did not want to remove that.
</blockquote></details>

Confirmed with Rohan and he mentioned just DELETE pipeline permission is enough. Added it in the ticket as well
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java` line 186 at r3](https://reviewable.io/reviews/harness/harness-core/41278#-NJcru1BDKNQjXe5x7mR:-NJwYlkp8_Wl61LZ62pp:bjlo8q4) ([raw file](https://github.com/harness/harness-core/blob/cf94a976d5aea7e65052c6ad4029e5039bc1799d/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java#L186)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Let me confirm with Product and get back. Earlier they had EXECUTE as well and did not want to remove that.
</blockquote></details>

Confirmed with Rohan and he mentioned just DELETE pipeline permission is enough. Added it in the ticket as well

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41278)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41278)* status: :shipit: complete! ✓

**Review by vaibhav-si — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41278)* status: 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41278)* status: :shipit: complete! ✓

**Pull request merged**
