### PR TITLE
[feat]: [PIE-9613]: Adding logs in PipelineStagePlanCreator

### PR DESCRIPTION
**Pull request by archit-harness**
## Describe your changes
Adding ManagedExecutorService to child threads in PlanCreatorService and logs in PipelineStagePlanCreator

Testing: locally and via unit tests

Impact: Added info logs, and AutoLog context to debug more in prod plus Added managedExecutorService, which will set parent thread context to children during planCreation, this was expected but was never being passed properly

Running manual tests and automation of git sync in qa should give confidence in this PR

Reason - 

```java

  @Test
  @Owner(developers = ARCHIT)
  @Category(UnitTests.class)
  public void testCreateInitialPlanCreationContext() throws ExecutionException, InterruptedException, TimeoutException {
    Executor executor = ThreadPool.create(ThreadPoolConfig.builder().maxPoolSize(1).corePoolSize(1).build(),
        new ThreadFactoryBuilder().setNameFormat("PlanCreatorInternalExecutorService-%d").build());

    CompletableFutures<String> completableFutures = new CompletableFutures<>(executor);

    GitEntityInfo aaaaa = GitEntityInfo.builder().repoName("aaaaa").build();
    try (PmsGitSyncBranchContextGuard ignore =
             new PmsGitSyncBranchContextGuard(GitSyncBranchContext.builder().gitBranchInfo(aaaaa).build(), true)) {
      List<Boolean> t = new ArrayList<>();
      t.add(true);
      t.add(false);

      t.forEach(key -> completableFutures.supplyAsync(() -> {
        try {
          return getCheck(key);
        } catch (Exception e) {
          throw new InvalidRequestException("Unable to parse the field in the path:" + key);
        }
      }));

      List<String> strings = completableFutures.allOf().get(5, TimeUnit.MINUTES);
      System.out.println(strings);
    }

  }

  private String getCheck(boolean f) {
    GitSyncBranchContext g = GitSyncBranchContext.builder()
                                 .gitBranchInfo(GitEntityInfo.builder().branch(f ? "archit" : "singla").build())
                                 .build();
    System.out.println(GitAwareContextHelper.getGitRequestParamsInfo());
    GitAwareContextHelper.updateGitEntityContext(g.getGitBranchInfo());
    GitEntityInfo gitRequestParamsInfo = GitAwareContextHelper.getGitRequestParamsInfo();
    System.out.println(gitRequestParamsInfo);
    return "";
  }
```

Points to note -

1. Executor Service created here is of only 1 thread
2. If branch is set into git context, another request on same thread (submitted via executor service), will already have the branch set as "archit", done by first flow. (if child is copying everything from parent, which is usually the case, not mentioned in above test)

Issue ->
First flow -> set one field
second flow -> set another field

second flow -> will have both fields set

3. Parent thread is having guard, having repo set -> is not passed to child threads, neither on first flow or second.

Just changing executorService to use ManagedExecutorService

```java
Executor executor =
        new ManagedExecutorService(ThreadPool.create(ThreadPoolConfig.builder().maxPoolSize(1).corePoolSize(1).build(),
            new ThreadFactoryBuilder().setNameFormat("PlanCreatorInternalExecutorService-%d").build()));
```

In above example,

1. Child threads will initially have parent context in both flows called in supplyAsync
2. When child thread updates the context, that is final context, which is expected

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46665)

### CODE REVIEW

**Review by mohitg0795 — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46665)* status: 4 file(s) to review. 0 of 2 approvals obtained.

**Review by prashantsharma04 — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46665)* status: 0 of 2 approvals obtained.

**Comment by archit-harness** [comment]
trigger messagecheck

**Comment by archit-harness** [comment]
trigger messagecheck

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46665)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]

**Pull request merged**
