### PR TITLE
[feat]: [CDS-69780]: Extending the StrategyNodeFunctor to include all strategy expressions for any level

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Extending the StrategyNodeFunctor to include all strategy expressions for any level.
So now strategy expressions can be pointed to specific strategy level(Or child of strategy) when we have multiple strategy levels.

Issue: When we have nested stepGroups and both stepGroups has the looping strategy. So if user want to refer the matrix/strategy expressions of the parent stepGroup from the child stepGroup. Its not possible currently.

Change: We have a StrategyNodeFunctor that takes the strategyNodeIdentifier as parameter and then it gives the specific strategyNode's data. Extending this to support the strategy expressions as well that are resolved from the strategyMetadata.

Impact: This impacts the `strategy.node.nodeIdentifier.identifierPostFix` type of expressions. Only the `strategy.node.nodeIdentifier.currentStartus` was available so far. Now we can use any strategy expressions with this format.

Please check the below examples for the specific strategy level expressions:

``` 
<+strategy.node.cs11.currentStatus>
 <+strategy.node.sg1.currentStatus>
 <+strategy.node.sg2.currentStatus>

<+strategy.node.cs11.identifierPostFix>
<+strategy.node.sg1.identifierPostFix>
<+strategy.node.sg2.identifierPostFix>

<+strategy.node.cs11.iterations>
<+strategy.node.sg1.iterations>
<+strategy.node.sg2.iterations>

<+strategy.node.cs11.iteration>
<+strategy.node.sg1.iteration>
<+strategy.node.sg2.iteration>


<+strategy.node.cs11.matrix>
<+strategy.node.sg1.matrix>
<+strategy.node.sg2.matrix>

<+strategy.node.cs11.matrix.key1>
<+strategy.node.sg1.matrix.key1>
<+strategy.node.sg2.matrix.key1>
```
The above expressions evaluates fine. Please check the below screenshot for the execution.
Screenshot 2023-06-30 at 3 15 06 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49972)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49972)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyNodeFunctor.java` line 87 at r1](https://reviewable.io/reviews/harness/harness-core/49972#-NZASYS_64EPY8ftLipX:-NZASYSa--73yfkEnkM1:b-vypdku) ([raw file](https://github.com/harness/harness-core/blob/1c7e1f4e983bb4becdf85ae4b153569f48f6c78b/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyNodeFunctor.java#L87)):*
> ```Java
>   }
> 
>   // Strategy expressions(Except currentStatus) are evaluated on the children of strategy node. So we are getting the
> ```

child* and not children
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyNodeFunctor.java` line 97 at r1](https://reviewable.io/reviews/harness/harness-core/49972#-NZASU0n2ZHvkeEJs4HG:-NZASU0o1XtOnLNQvpC6:bpxk7cj) ([raw file](https://github.com/harness/harness-core/blob/1c7e1f4e983bb4becdf85ae4b153569f48f6c78b/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyNodeFunctor.java#L97)):*
> ```Java
>         // getLevel(index+1).
>         if (level.getIdentifier().equals(identifier)) {
>           Level tempLevel = ambiance.getLevels(index + 1);
> ```

we should add check for index+1 item exists

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyNodeFunctor.java` line 97 at r1](https://reviewable.io/reviews/harness/harness-core/49972#-NZASU0n2ZHvkeEJs4HG:-NZASo92EPhgbuoybu9s:bvxbdub) ([raw file](https://github.com/harness/harness-core/blob/1c7e1f4e983bb4becdf85ae4b153569f48f6c78b/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyNodeFunctor.java#L97)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should add check for index+1 item exists
</blockquote></details>

I have started the loop index from (count-2) for this reason. So it will always exist.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49972)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyNodeFunctor.java` line 87 at r1](https://reviewable.io/reviews/harness/harness-core/49972#-NZASYS_64EPY8ftLipX:-NZAfGtz4wHZ2dad_ltD:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1c7e1f4e983bb4becdf85ae4b153569f48f6c78b/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyNodeFunctor.java#L87)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

child* and not children
</blockquote></details>

done

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49972)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger review

**Pull request merged**
