### PR TITLE
feat: [CDS-3956]: Fetching Artifact from Fetch Instances Script for Custom Deployment

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
JIRA - https://harness.atlassian.net/browse/CDS-3956

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34792)

### CODE REVIEW

**Comment by tchaurasiya** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java` line 200 at r1](https://reviewable.io/reviews/harness/harness-core/34792#-N5jPi9rDpUUBlVFUjcX:-N5jPi9rDpUUBlVFUjcY:b-tdet34) ([raw file](https://github.com/harness/harness-core/blob/85d5a35f8a060dc1a7dfe0c67e6e8dc10b517210/400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java#L200)):*
> ```Java
>     InstanceBuilder builder = buildInstanceBase(null, infraMapping, deploymentSummary);
> 
>     if (featureFlagService.isEnabled(
> ```

lets not override builder. affect
Rather lets write two different flow.

**Comment by tchaurasiya** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java` line 200 at r1](https://reviewable.io/reviews/harness/harness-core/34792#-N5jPi9rDpUUBlVFUjcX:-N5kUGmN3STyMPt-MBrm:bq6v0gs) ([raw file](https://github.com/harness/harness-core/blob/85d5a35f8a060dc1a7dfe0c67e6e8dc10b517210/400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java#L200)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

lets not override builder. affect
Rather lets write two different flow.
</blockquote></details>

Affecting readability**



_Code quote:_
```Java
 public static final String artifactBuildNum = "artifactBuildNum
```

**Comment by tchaurasiya** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java` line 205 at r1](https://reviewable.io/reviews/harness/harness-core/34792#-N5kUychCIRtwrEPkcpi:-N5kUyciAqyB23KCS2a7:b-8wr07j) ([raw file](https://github.com/harness/harness-core/blob/85d5a35f8a060dc1a7dfe0c67e6e8dc10b517210/400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java#L205)):*
> ```Java
>         ArtifactStream stream = CustomArtifactStream.builder().uuid(deploymentSummary.getArtifactStreamId()).build();
>         Artifact artifact = artifactService.getArtifactByBuildNumber(
>             stream, hostInstanceInfo.getProperties().get(artifactBuildNum).toString(), false);
> ```

wont this give NPE if  hostInstanceInfo.getProperties().get(artifactBuildNum) == null

**Comment by RishabhGupta34** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java` line 205 at r1](https://reviewable.io/reviews/harness/harness-core/34792#-N5kUychCIRtwrEPkcpi:-N5nDTZo8RVhKxc2ZnZq:b-421o1n) ([raw file](https://github.com/harness/harness-core/blob/85d5a35f8a060dc1a7dfe0c67e6e8dc10b517210/400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java#L205)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

wont this give NPE if  hostInstanceInfo.getProperties().get(artifactBuildNum) == null
</blockquote></details>

I have added that check here



_Code quote:_
```Java
if (!isNull(hostInstanceInfo.getProperties().get(artifactBuildNum))) {
```

**Comment by RishabhGupta34** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java` line 200 at r1](https://reviewable.io/reviews/harness/harness-core/34792#-N5jPi9rDpUUBlVFUjcX:-N5nE2qR6HNU_AJ5SfUk:bq60nje) ([raw file](https://github.com/harness/harness-core/blob/85d5a35f8a060dc1a7dfe0c67e6e8dc10b517210/400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java#L200)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Affecting readability**
</blockquote></details>

I added it like that, so that I don't have to replicate the code in this func.



_Code quote:_
```Java
    InstanceBuilder builder = buildInstanceBase(null, infraMapping, deploymentSummary);
```

**Comment by RishabhGupta34** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/34792#-N5kVqdhC6o1HtyZp3-B:-N5nE7yOA0ZPLVqjucMb:b-u3i7m0) ([raw file](https://github.com/harness/harness-core/blob/85d5a35f8a060dc1a7dfe0c67e6e8dc10b517210/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L66)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

nit: redundant space
</blockquote></details>

removed, thanks

**Review by anilchowdhury-harness — DISMISSED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34792#-:-N5sV5SBA6aOaG7bF216:bnfp4nl)* status: 2. unresolved discussions.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34792)* status: Some of the checks are too old. 1. unresolved discussions.

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34792)* status: Some of the checks are too old.

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34792)* status: Some of the checks are too old. 1 change requests. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java` line 201 at r2](https://reviewable.io/reviews/harness/harness-core/34792#-N66oKac3FxGobAr1bKy:-N66oKac3FxGobAr1bKz:b-oklo2r) ([raw file](https://github.com/harness/harness-core/blob/b243a45640ce16d4d4fc51ed828503ce2d4c7465/400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java#L201)):*
> ```Java
>     if (featureFlagService.isEnabled(
>             FeatureName.CUSTOM_DEPLOYMENT_ARTIFACT_FROM_FETCH_INSTANCE_SCRIPT, infraMapping.getAccountId())) {
>       if (!isNull(hostInstanceInfo.getProperties().get(artifactBuildNum))) {
> ```


we should check for properties being not null

```
 if (isNotEmpty(hostInstanceInfo.getProperties())
          && hostInstanceInfo.getProperties().get(artifactBuildNum) != null) {
```

Also since instance sync is a background process and checking for feature flag involves a REST call, we should try to avoid being so aggressive that we fetch it on every method invocation

Lets see how many perpetual tasks exist for custom deployments ( from DB ) to get an idea of the scale of this
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java` line 204 at r2](https://reviewable.io/reviews/harness/harness-core/34792#-N66tZ4M1O_BF6Uw8sye:-N66tZ4M1O_BF6Uw8syf:b-tyv1u2) ([raw file](https://github.com/harness/harness-core/blob/b243a45640ce16d4d4fc51ed828503ce2d4c7465/400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java#L204)):*
> ```Java
>         ArtifactStream stream = CustomArtifactStream.builder().uuid(deploymentSummary.getArtifactStreamId()).build();
>         artifact = artifactService.getArtifactByBuildNumber(
>             stream, hostInstanceInfo.getProperties().get(artifactBuildNum).toString(), false);
> ```

Can we add a new method to ArtifactService that just takes the
- accountId
- artifactStreamId
- artifactBuildNumber

I would have liked to refactor the existing method but there are many usages for that 
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java` line 826 at r2](https://reviewable.io/reviews/harness/harness-core/34792#-N66uZd51CJaw0Va1OLT:-N66uZd51CJaw0Va1OLU:bi2er2s) ([raw file](https://github.com/harness/harness-core/blob/b243a45640ce16d4d4fc51ed828503ce2d4c7465/400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java#L826)):*
> ```Java
>     List<CurrentActiveInstances> currentActiveInstances = getCurrentActiveInstances(accountId, appId, serviceId);
>     List<DeploymentHistory> deploymentHistoryList = getDeploymentHistory(accountId, appId, serviceId, pageRequest);
>     if (featureFlagService.isEnabled(ARTIFACT_FROM_DEPLOYMENT_HIST, accountId)) {
> ```

is this a related change ?
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/34792#-N66u5Eh-t1QLoa_ju_e:-N66u5Eh-t1QLoa_ju_f:b-hk9xi2) ([raw file](https://github.com/harness/harness-core/blob/b243a45640ce16d4d4fc51ed828503ce2d4c7465/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L67)):*
> ```Java
>   CUSTOM_DASHBOARD,
>   CUSTOM_DEPLOYMENT,
>   CUSTOM_DEPLOYMENT_ARTIFACT_FROM_FETCH_INSTANCE_SCRIPT,
> ```

better name would be

CUSTOM_DEPLOYMENT_ARTIFACT_FROM_INSTANCE_JSON

**Review by RishabhGupta34 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34792)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java` line 201 at r2](https://reviewable.io/reviews/harness/harness-core/34792#-N66oKac3FxGobAr1bKy:-N6qzrka5KOxPBMTnj2k:b499q7j) ([raw file](https://github.com/harness/harness-core/blob/b243a45640ce16d4d4fc51ed828503ce2d4c7465/400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java#L201)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>


we should check for properties being not null

```
 if (isNotEmpty(hostInstanceInfo.getProperties())
          && hostInstanceInfo.getProperties().get(artifactBuildNum) != null) {
```

Also since instance sync is a background process and checking for feature flag involves a REST call, we should try to avoid being so aggressive that we fetch it on every method invocation

Lets see how many perpetual tasks exist for custom deployments ( from DB ) to get an idea of the scale of this

</blockquote></details>

Changed
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java` line 204 at r2](https://reviewable.io/reviews/harness/harness-core/34792#-N66tZ4M1O_BF6Uw8sye:-N6qzu4F7SBsD_ISE1oQ:b-8b11j9) ([raw file](https://github.com/harness/harness-core/blob/b243a45640ce16d4d4fc51ed828503ce2d4c7465/400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java#L204)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Can we add a new method to ArtifactService that just takes the
- accountId
- artifactStreamId
- artifactBuildNumber

I would have liked to refactor the existing method but there are many usages for that 
</blockquote></details>

Added
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java` line 826 at r2](https://reviewable.io/reviews/harness/harness-core/34792#-N66uZd51CJaw0Va1OLT:-N6qzvDC9Gpyzk4xJzkg:b-tkjgs) ([raw file](https://github.com/harness/harness-core/blob/b243a45640ce16d4d4fc51ed828503ce2d4c7465/400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java#L826)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this a related change ?
</blockquote></details>

This is related to the multiple artifacts being shown, after discussing with Achyuth putting it behind FF, https://harness.atlassian.net/browse/CDS-2992
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/34792#-N66u5Eh-t1QLoa_ju_e:-N6r0Bqm60k7dIXQziyK:bb7oryy) ([raw file](https://github.com/harness/harness-core/blob/b243a45640ce16d4d4fc51ed828503ce2d4c7465/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L67)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

better name would be

CUSTOM_DEPLOYMENT_ARTIFACT_FROM_INSTANCE_JSON
</blockquote></details>

sure

**Comment by RishabhGupta34** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java` line 826 at r2](https://reviewable.io/reviews/harness/harness-core/34792#-N66uZd51CJaw0Va1OLT:-N6r9zX4905IwspDh0jC:bef84gh) ([raw file](https://github.com/harness/harness-core/blob/b243a45640ce16d4d4fc51ed828503ce2d4c7465/400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java#L826)):*
<details><summary><i>Previously, RishabhGupta34 (Rishabh Gupta) wrote…</i></summary><blockquote>

This is related to the multiple artifacts being shown, after discussing with Achyuth putting it behind FF, https://harness.atlassian.net/browse/CDS-2992
</blockquote></details>

Have removed this

**Comment by yogesh-chauhan** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/artifact/ArtifactServiceImpl.java` line 695 at r5](https://reviewable.io/reviews/harness/harness-core/34792#-N6w2huH6wlP4znVPV_K:-N6w2huH6wlP4znVPV_L:b-iff61p) ([raw file](https://github.com/harness/harness-core/blob/367636713830b261caf30f78ca5658720b83d395/400-rest/src/main/java/software/wings/service/impl/artifact/ArtifactServiceImpl.java#L695)):*
> ```Java
>     Query<Artifact> artifactQuery = wingsPersistence.createQuery(Artifact.class, excludeAuthority)
>                                         .filter(ArtifactKeys.accountId, accountId)
>                                         .filter(ArtifactKeys.artifactStreamId, artifactStreamId);
> ```

In another PR, lets explore if we should add a new DB index to handle this query

```
.add(CompoundMongoIndex.builder()
                 .name("accountId_artifactStream_buildNo")
                 .field(ArtifactKeys.accountId)
                 .field(ArtifactKeys.artifactStreamId)
                 .field(ArtifactKeys.metadata_buildNo)
                 .build())
```

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 6 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34792)* status: :shipit: complete! ✓

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 2 of 6 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34792)* status: 1. unresolved discussions.

**Review by PrasadRavella — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 2 of 6 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34792)* status: 1. unresolved discussions.

**Review by RishabhGupta34 — COMMENTED** [review]
👍🏻

> Reviewed 1 of 5 files at r2, 2 of 6 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34792#-:-N6xE3UP75mdt01HthhW:b-vocqrw)* status: :shipit: complete! ✓

**Pull request merged**
