### PR TITLE
feat: [PL-31067]: Pre-requisite setup to create delegate task in service

### PR DESCRIPTION
**Pull request by nishantsaini20**
## Describe your changes
This PR contains the following:
1. Installing guice module required to created delegate tasks in audit streaming service(springbatch application).
2. Add AWS S3 Publisher that creates AWS task for delegate to write audit events to S3 bucket.
3. build related changes.

Testing:
1. The complete flow of creating streaming destination to writing to s3 bucket in local env.
2. Updates UTs.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42910)

### CODE REVIEW

**Comment by nishantsaini20** [comment]
trigger messagecheck

**Review by ChrisHam8066 — CHANGES_REQUESTED** [review]
Are these tokens valid?

**Review by nishantsaini20 — COMMENTED** [review]
Which tokens?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42910#-:-NMZiPXN2itcYfla0_fa:bjuinkt)* status: 41 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by jyotiraval — APPROVED** [review]
The tokens being committed is just for local setup, on prod it will be replaced by token from secret manager. Thanks Nishant for helping understand.

**Review by pranay-harness — DISMISSED** [review]

**Comment by piyush-harness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java` line 145 at r5](https://reviewable.io/reviews/harness/harness-core/42910#-NMr1MfY6hELFl-clhTS:-NMr1MfY6hELFl-clhTT:ba5xfx7) ([raw file](https://github.com/harness/harness-core/blob/01504f3685341b26c774e65f93ccc5953fdef17f/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java#L145)):*
> ```Java
>           .putObjectResultResponse(putObjectResultResponse)
>           .build();
>     } catch (Exception ex) {
> ```

Why did we remove exception handling from here?

**Comment by piyush-harness** [comment]
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelperTest.java` line 649 at r5](https://reviewable.io/reviews/harness/harness-core/42910#-NMr1T2pCxlfvrB2T27J:-NMr1T2pCxlfvrB2T27K:b-iioz7s) ([raw file](https://github.com/harness/harness-core/blob/01504f3685341b26c774e65f93ccc5953fdef17f/930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelperTest.java#L649)):*
> ```Java
>     verify(awsApiHelperService, times(1)).putAuditBatchToBucket(any(), any(), any(), any());
> 
>     doThrow(new AmazonServiceException("Exception while writing to S3 bucket"))
> ```

Follow up on above comment of removing exception handling.

**Comment by piyush-harness** [comment]
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/publishers/impl/AwsS3StreamingPublisher.java` line 133 at r5](https://reviewable.io/reviews/harness/harness-core/42910#-NMr2YOP74VKntGSPM_E:-NMr2YOP74VKntGSPM_F:b-zcstjv) ([raw file](https://github.com/harness/harness-core/blob/f2ea6891a8e0a19b301b03e36742e905bd693bb5/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/publishers/impl/AwsS3StreamingPublisher.java#L133)):*
> ```Java
>     }
>     if (AWS_S3 == streamingDestination.getType()) {
>       AwsConnectorDTO connector =
> ```

We should check if connector's Connectivity type is via Harness Manager or Delegate , I think we built a framework around it for DelegateLess connectors check with @meenakshi-harness

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 33 of 41 files at r1, 3 of 5 files at r2, 6 of 8 files at r3, 9 of 11 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42910)* status: 53 file(s) to review. 2 change requests. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java` line 262 at r5](https://reviewable.io/reviews/harness/harness-core/42910#-NMr1evh9QIASz7Yw_C2:-NMr1evh9QIASz7Yw_C3:brb09mg) ([raw file](https://github.com/harness/harness-core/blob/f2ea6891a8e0a19b301b03e36742e905bd693bb5/960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java#L262)):*
> ```Java
>   private String getKey(AuditBatchDTO auditBatchDTO) {
>     List<OutgoingAuditMessage> outgoingMessages = auditBatchDTO.getOutgoingAuditMessages();
>     Long startTime = outgoingMessages.get(0).getAuditEventTime().toEpochMilli();
> ```

we should check size before accessing index.

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42910)* status: 53 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java` line 145 at r5](https://reviewable.io/reviews/harness/harness-core/42910#-NMr1MfY6hELFl-clhTS:-NMwTuZMBXskYZaBUqsy:b-iwda8k) ([raw file](https://github.com/harness/harness-core/blob/01504f3685341b26c774e65f93ccc5953fdef17f/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java#L145)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why did we remove exception handling from here?
</blockquote></details>

Added back
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelperTest.java` line 649 at r5](https://reviewable.io/reviews/harness/harness-core/42910#-NMr1T2pCxlfvrB2T27J:-NMwU-xJAUPUm4xHB0DB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/01504f3685341b26c774e65f93ccc5953fdef17f/930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelperTest.java#L649)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Follow up on above comment of removing exception handling.
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java` line 262 at r5](https://reviewable.io/reviews/harness/harness-core/42910#-NMr1evh9QIASz7Yw_C2:-NMwU1Pg31atNaBM0jRi:b-1shvk0) ([raw file](https://github.com/harness/harness-core/blob/f2ea6891a8e0a19b301b03e36742e905bd693bb5/960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java#L262)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

we should check size before accessing index.
</blockquote></details>

Delegate task will not be created when there is no outgoing message to be published. Also outgoingMessages field is annotated with NotEmpty as well.

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42910)* status: 53 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/publishers/impl/AwsS3StreamingPublisher.java` line 133 at r5](https://reviewable.io/reviews/harness/harness-core/42910#-NMr2YOP74VKntGSPM_E:-NN1OSM-BF8mvvKcwC2s:b-vydjrm) ([raw file](https://github.com/harness/harness-core/blob/f2ea6891a8e0a19b301b03e36742e905bd693bb5/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/publishers/impl/AwsS3StreamingPublisher.java#L133)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

We should check if connector's Connectivity type is via Harness Manager or Delegate , I think we built a framework around it for DelegateLess connectors check with @meenakshi-harness   
</blockquote></details>

Added a check that execute on delegate should be true.

**Review by reetika04 — APPROVED** [review]
> Reviewed 27 of 41 files at r1, 1 of 5 files at r2, 2 of 8 files at r3, 6 of 11 files at r4, 2 of 2 files at r5, 3 of 4 files at r6, 3 of 3 files at r7, 6 of 6 files at r8, 1 of 2 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42910)* status: 15 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by piyush-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r7, 4 of 6 files at r8, 1 of 2 files at r9, 1 of 2 files at r10, 2 of 2 files at r11, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42910)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 2 of 2 files at r11, 2 of 4 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42910)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42910)* status: :shipit: complete! ✓

**Review by jyotiraval — APPROVED** [review]
> Reviewed 27 of 41 files at r1, 1 of 5 files at r2, 2 of 8 files at r3, 6 of 11 files at r4, 2 of 2 files at r5, 3 of 3 files at r7, 4 of 6 files at r8, 1 of 2 files at r9, 1 of 2 files at r10, 2 of 2 files at r11, 2 of 4 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42910)* status: :shipit: complete! ✓

**Pull request merged**
