### PR TITLE
feat: [SRM-15053]: Handle Notifications for Deployment impact report

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Describe your changes

This PR contains:

1. Iterator for sending notifications for report when the step is completed.
2. Adding template for slack for deployment impact report.
3. Sending report in case of aborted and completion of step.
4. Generalizing the report methods so It can be used for any reports not just Firehydrant.
5. Fixing firehydrant report for the following things:  adding URL in all the headers, adding dynamic summary in the service health and slo, having error budget burned minutes instead of rate.
6. Moving some entities, DTO out of contracts/delegate module to SRM module as they are not needed outside SRM service.
7. Removed MSHealthReport from CustomChangeEvent as we needed RiskData in MSHealthReport for service health summary, and RiskData is of srm-service module, moved MSHealthReport to service module as well. Nevertheless there is no usage of MSHealthReport there, if needed in future we will store whatever we need from report instead of the whole entitty.
8. Adding pipelineName to the SRMAnalysisStepExecutionDetail entity as it's needed in the report which is fetched through pipelineServiceClient.
9. Adding UTS

PR env: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/default/projects/PREQA_NG_Pipelines/pipelines/PR_Harness_Env/deployments/1_8Suj0_SvaMkAEMY0xD9A/pipeline?connectorRef=account.PRenvHarnessYamlGithub&repoName=ng-pr-manifests&branch=main&storeType=REMOTE

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50666)

### CODE REVIEW

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepak-harness — CHANGES_REQUESTED** [review]
Also, we should modify the debug register API. so that we can test the notification end to end. 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50666#-:-N_m736CA6gG-oAElruc:bupkfuk)* status: 48 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/CVServiceModule.java` line 1025 at r2](https://reviewable.io/reviews/harness/harness-core/50666#-N_ly_1C36sdy6Yb-g87:-N_ly_1C36sdy6Yb-g88:by2wio6) ([raw file](https://github.com/harness/harness-core/blob/2c86a946768d40079e0f09e7956575f227f71532/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/CVServiceModule.java#L1025)):*
> ```Java
>     bind(EntityUnavailabilityStatusesService.class).to(EntityUnavailabilityStatusesServiceImpl.class);
>     bind(AnnotationService.class).to(AnnotationServiceImpl.class);
>     install(new PipelineRemoteClientModule(
> ```

nit: we should verify that in absense of the configuration we don't fail the startup of CVNG.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/services/impl/SRMAnalysisStepServiceImpl.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/50666#-N_lzPXH-kMzJ1PaUHCy:-N_lzPXH-kMzJ1PaUHCz:bxuw394) ([raw file](https://github.com/harness/harness-core/blob/2c86a946768d40079e0f09e7956575f227f71532/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/services/impl/SRMAnalysisStepServiceImpl.java#L84)):*
> ```Java
>   public String createSRMAnalysisStepExecution(Ambiance ambiance, String monitoredServiceIdentifier,
>       ServiceEnvironmentParams serviceEnvironmentParams, Duration duration) {
>     Object pmsExecutionSummary = NGRestUtils.getResponse(pipelineServiceClient.getExecutionDetailV2(
> ```

Lets put this in try catch block.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/utils/NotificationRuleCommonUtils.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/50666#-N_m5ioCADEN7BusuSRu:-N_m5ioCADEN7BusuSRv:b2rmz3x) ([raw file](https://github.com/harness/harness-core/blob/2c86a946768d40079e0f09e7956575f227f71532/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/utils/NotificationRuleCommonUtils.java#L89)):*
> ```Java
>   }
> 
>   public static String getSloPerformanceDetailsForReport(
> ```

are we fetching details here? we are passing details and constructing string for slack.

**Review by deepak-harness — DISMISSED** [review]
:lgtm:

> Reviewed 47 of 48 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50666#-:-N_mF9rn09R5wgqNItwr:bnfp4nl)* status: :shipit: complete! ✓

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepak-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50666)* status: :shipit: complete! ✓

**Comment by deepak-harness** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger ut5, ut7

**Pull request merged**
