### PR TITLE
feat: [SRM-10930]: Audit trail for resetting the error budget in slo.

### PR DESCRIPTION
**Pull request by naveen-harness**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34829)

### CODE REVIEW

**Comment by naveen-harness** [comment]
trigger compile

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34829)* status: 12 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 432 at r4](https://reviewable.io/reviews/harness/harness-core/34829#-N6I6f9N3e7UxdG1o-He:-N6I6f9N3e7UxdG1o-Hf:bll77oy) ([raw file](https://github.com/harness/harness-core/blob/b744e02801a1b5e45ca2c2fae0bcba1beb67eb4f/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L432)):*
> ```Java
>   @Override
>   public SLOErrorBudgetResetDTO resetErrorBudget(ProjectParams projectParams, SLOErrorBudgetResetDTO resetDTO) {
>     ServiceLevelObjective serviceLevelObjective = getEntity(projectParams, resetDTO.getServiceLevelObjectiveIdentifier());
> ```

We do not persist the error budget resets in the service level objective entity. There is a different entity for this  SLOErrorBudgetReset
Please check,

**Review by naveen-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34829)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 432 at r4](https://reviewable.io/reviews/harness/harness-core/34829#-N6I6f9N3e7UxdG1o-He:-N6NYdIf4X6b_Iu-pkQX:b4ph0zb) ([raw file](https://github.com/harness/harness-core/blob/b744e02801a1b5e45ca2c2fae0bcba1beb67eb4f/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L432)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

We do not persist the error budget resets in the service level objective entity. There is a different entity for this  SLOErrorBudgetReset
Please check,
</blockquote></details>

We need to keep it here only as discussed.

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34829)* status: 12 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/events/servicelevelobjective/ServiceLevelObjectiveErrorBudgetResetEvent.java` line 35 at r5](https://reviewable.io/reviews/harness/harness-core/34829#-N6NaUPW8aycv2PfYpxn:-N6NaUPX1AtVyZsLIsH8:b-knvnre) ([raw file](https://github.com/harness/harness-core/blob/db9c795768b81fca9f5d2c7aad026a415dd38378/300-cv-nextgen/src/main/java/io/harness/cvng/events/servicelevelobjective/ServiceLevelObjectiveErrorBudgetResetEvent.java#L35)):*
> ```Java
>     private String serviceLevelObjectiveIdentifier;
> 
>     private ServiceLevelObjectiveDTO newServiceLevelObjectiveDTO;
> ```

Can be removed.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/outbox/ServiceLevelObjectiveOutboxEventHandler.java` line 122 at r5](https://reviewable.io/reviews/harness/harness-core/34829#-N6NaXQy7PHq6oiU-FdC:-N6NaXQy7PHq6oiU-FdD:b-s3hmk9) ([raw file](https://github.com/harness/harness-core/blob/db9c795768b81fca9f5d2c7aad026a415dd38378/300-cv-nextgen/src/main/java/io/harness/cvng/outbox/ServiceLevelObjectiveOutboxEventHandler.java#L122)):*
> ```Java
>             .action(Action.ERROR_BUDGET_RESET)
>             .module(ModuleType.CV)
>             .oldYaml(getYamlString(sloErrorBudgetResetEvent.getOldServiceLevelObjectiveDTO()))
> ```

Not needed.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 440 at r5](https://reviewable.io/reviews/harness/harness-core/34829#-N6NbJym9uMELbvHtSnq:-N6NbJym9uMELbvHtSnr:b64k65t) ([raw file](https://github.com/harness/harness-core/blob/db9c795768b81fca9f5d2c7aad026a415dd38378/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L440)):*
> ```Java
>             .projectIdentifier(projectParams.getProjectIdentifier())
>             .build());
>     return sloErrorBudgetResetService.resetErrorBudget(projectParams, resetDTO);
> ```

Should move to SLOErrorBudgetResetServiceImpl.resetErrorBudget



_Code quote:_
```Java
sloErrorBudgetResetService.resetErrorBudget
```

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 8 files at r3, 6 of 6 files at r4, 2 of 6 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34829)* status: :shipit: complete! ✓

**Pull request merged**
