### PR TITLE
fix: [CDS-2997]: Modify service instance dashboard summary

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
Ticket: https://harness.atlassian.net/browse/CDS-2997

The 'last deployed at' timestamp and the workflow execution link for the service instances was referring to the last workflow execution, regardless of whether it passed or failed. 
Modified it to show the last successful workflow execution's link and timestamp.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33102)

### CODE REVIEW

**Comment by abhinavsingh1196** [comment]
*[`400-rest/src/main/java/software/wings/service/intfc/WorkflowExecutionService.java` line 331 at r2](https://reviewable.io/reviews/harness/harness-core/33102#-N1rbnz2-ZTwBAAQgh_z:-N1s0gQF43FJs3QwcdPc:bln5xsb) ([raw file](https://github.com/harness/harness-core/blob/49171cba10ec8e7cc4a098a771f6e49feb382852/400-rest/src/main/java/software/wings/service/intfc/WorkflowExecutionService.java#L331)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we use accountId, appId also ? or can we just use the above API 
```  
WorkflowExecution fetchWorkflowExecution(String appId, String workflowExecutionId, String... projectedFields);
```
</blockquote></details>

reused the existing API and removed this one, thanks

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33102)* status: Some of the checks are too old. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java` line 6160 at r3](https://reviewable.io/reviews/harness/harness-core/33102#-N2AdAWe5h1i_xzUzjek:-N2AdAWe5h1i_xzUzjel:b-f5na9d) ([raw file](https://github.com/harness/harness-core/blob/44c1866a5a6a2ca737733d15d9f6104fe318f9d3/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java#L6160)):*
> ```Java
>   @Override
>   public WorkflowExecution getLastSuccessfulWorkflowExecution(
>       String accountId, String appId, String uuid, String envId, String serviceId, String infraMappingId) {
> ```

rename the param `uuid` to `workflowId`
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java` line 936 at r3](https://reviewable.io/reviews/harness/harness-core/33102#-N2AeLqBCTBarHyLlDS3:-N2AeLqBCTBarHyLlDS4:bi07bvc) ([raw file](https://github.com/harness/harness-core/blob/44c1866a5a6a2ca737733d15d9f6104fe318f9d3/400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java#L936)):*
> ```Java
>       String lastWorkflowExecutionId = aggregationInfo.getArtifactInfo().getLastWorkflowExecutionId();
>       // To fetch last execution
>       WorkflowExecution lastWE = workflowExecutionService.fetchWorkflowExecution(appId, lastWorkflowExecutionId,
> ```

shouldn't this call be `getLastSuccessfulWorkflowExecution`, and everything else remains the same.
if all the workflow executions are `FAILED`, isn't it the same as not finding any workflow execution: `if (lastWE == null) {`

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33102)* status: Some of the checks are too old. 2 change requests. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33102)* status: Some of the checks are too old. 2 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java` line 963 at r3](https://reviewable.io/reviews/harness/harness-core/33102#-N2B3ajW7lSA6I2c4bGj:-N2B3ajX4OK6_cCBK5mX:b-2z392) ([raw file](https://github.com/harness/harness-core/blob/44c1866a5a6a2ca737733d15d9f6104fe318f9d3/400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java#L963)):*
> ```Java
>           workflowName = workflow.getName();
>           lastSuccessfulWE = workflowExecutionService.getLastSuccessfulWorkflowExecution(workflow.getAccountId(),
>               workflow.getAppId(), workflow.getUuid(), lastWE.getEnvId(), serviceId, infraMappingInfo.getId());
> ```

we should check if this works well when env is templatized in the workflow

**Comment by abhinavsingh1196** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java` line 963 at r3](https://reviewable.io/reviews/harness/harness-core/33102#-N2B3ajW7lSA6I2c4bGj:-N2BYPboAU9_crDhrztq:b-168yn9) ([raw file](https://github.com/harness/harness-core/blob/44c1866a5a6a2ca737733d15d9f6104fe318f9d3/400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java#L963)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should check if this works well when env is templatized in the workflow
</blockquote></details>

verified this with a templatized env and infradefs, LGTM

**Review by shubham-in10se — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33102)* status: 2 change requests. 0 of 1 approvals obtained.

**Comment by abhinavsingh1196** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java` line 936 at r3](https://reviewable.io/reviews/harness/harness-core/33102#-N2AeLqBCTBarHyLlDS3:-N2BYrCj4KeXLdilBS2r:b-hi2pi3) ([raw file](https://github.com/harness/harness-core/blob/44c1866a5a6a2ca737733d15d9f6104fe318f9d3/400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java#L936)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

shouldn't this call be `getLastSuccessfulWorkflowExecution`, and everything else remains the same.
if all the workflow executions are `FAILED`, isn't it the same as not finding any workflow execution: `if (lastWE == null) {`
</blockquote></details>

done, fetched some WE metadata needed for the query and used it further.

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 3 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33102)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33102)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33102)* status: :shipit: complete! ✓

**Pull request merged**
