### PR TITLE
[fix]: [PL-22503]: Remove the logic to not save the commit if the files processed are empty

### PR DESCRIPTION
**Pull request by DeepakPatankar**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30698)

### CODE REVIEW

**Comment by DeepakPatankar** [comment]
trigger messagecheck

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30698)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/impl/GitCommitServiceImpl.java, line 118 at r1](https://reviewable.io/reviews/harness/harness-core/30698#-Mvb9Qpg4YgCWvJyxp_D:-Mvb9Pa81bR-JLtg6t0y:b-3xrpv) ([raw file](https://github.com/harness/harness-core/blob/471592934005dd4fa0ae81c93dfaf6161728ffbc/136-git-sync-manager/src/main/java/io/harness/gitsync/core/impl/GitCommitServiceImpl.java#L118)):*
> ```Java
>                             .is(gitCommitDTO.getGitSyncDirection());
>     Update update = update(GitCommitKeys.status, gitCommitDTO.getStatus())
>                         .set(GitCommitKeys.fileProcessingSummary, gitCommitDTO.getFileProcessingSummary());
> ```

Make sure if FileProcessingSummary() is empty, then we are able to save the summary object in DB without any Null Pointer exception

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30698)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/impl/GitCommitServiceImpl.java, line 118 at r1](https://reviewable.io/reviews/harness/harness-core/30698#-Mvb9Qpg4YgCWvJyxp_D:-MvbAY5AAA-pdw73Ga8j:btsawyv) ([raw file](https://github.com/harness/harness-core/blob/471592934005dd4fa0ae81c93dfaf6161728ffbc/136-git-sync-manager/src/main/java/io/harness/gitsync/core/impl/GitCommitServiceImpl.java#L118)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Make sure if FileProcessingSummary() is empty, then we are able to save the summary object in DB without any Null Pointer exception
</blockquote></details>

Yeah, I tested this case when doing the local testing. I also verified that after this changes the subsequent h2g and g2h requests are working fine.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30698#-:-MvbYYFnE7ZzjKR2uD3Q:bnfp4nl)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by vikas-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30698)* status: 1 file(s) to review.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30698#-:-MvboDpWBI7JQ4B20M1A:bnfp4nl)* status: 1 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30698)* status: :shipit: complete! ✓

**Pull request merged**
