### PR TITLE
[feat]: [CCM-14734]: Add API for supported resources and Policy selection for AIDA tuning

### PR DESCRIPTION
**Pull request by iamanmolm**
## Describe your changes
1. Fixed name of policy within ce-nextgen/service/src/main/resources/governance/policies/AWS/ec2/ec2-old-instances-stop-age7Days.yml. It was inconsistent earlier.
2. Added `promptResources` API basically given the cloud provider it returns all the supported resources for prompting. And if no cloud provider is provided it returns AWS supported resources.
3. Added `promptRules` API returns description and ruleYaml and works like below:
    a. If supported cloudProvider is passed and supported resourceType is passed: It returns example rules only for that particular cloudProvider and resourceType.
    b. If supported cloudProvider is passed and non supported resourceType/ no resourceType is passed: It returns 11-12 examples rules for that cloudProvider.
    c. If non-supported or no cloudProvider is passed: It returns 11-12 examples rules for AWS as default cloudProvider.
4. Selected policies to be used for prompt engineering for different resources.
5. Added default policies for each cloud provider[For AWS I have used the data in prod which is hard coded on UI, when we select the cloud provider AWS in AIDA screen].
6. Also if some unknown or null resourceType is passed we will use those 11-12 examples for tuning the prompt accordingly.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54327)

### CODE REVIEW

**Comment by iamanmolm** [comment]
trigger messagecheck

**Comment by iamanmolm** [comment]
trigger uts

**Comment by iamanmolm** [comment]
trigger gitleaks

**Comment by iamanmolm** [comment]
trigger uts

**Comment by iamanmolm** [comment]
trigger ut7

**Comment by iamanmolm** [comment]
trigger uts

**Review by nikunj-badjatya — APPROVED** [review]

**Pull request merged**
