### PR TITLE
feat:[CDS-80158]: improving approval notif with cd metadata

### PR DESCRIPTION
**Pull request by naman-goenka**
## Describe your changes
- Improved harness approval notifications to have CD stage metadata.
- There are two kind of notifications: one when approval starts and one when approval is approved/rejected, both when configured to provide pipeline execution details require stages metadata.
- Added a stage metadata notification helper, which basically fetched and processes metadata for finished, running and upcoming stages. Currently only CD stages are handled, and handling for other stages like custom stages can be added later.
- Order of incoming stages is maintained while formatting
- Improvement irrespective of FF - use stage identifiers when names not present, and improves text format for headers like "Running Stages" in notification templates.
- Improvement with FF on only - if a Cd stage node is present we fetch info from plan creation for running and future stages ; from stage execution for completed stages. A fallback to stage name is added incase metadata is not fetched.
- [Tech/Product Spec](https://harness.atlassian.net/wiki/spaces/CDNG/pages/21520647005/Enhance+Approval+notifications+to+add+details+related+to+services+environment+artifacts+CG+Parity)
- [Testing notifications in various scenarios](https://harness.atlassian.net/wiki/spaces/CDNG/pages/21563637966/Improved+harness+approval+notifications)

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55321)

### CODE REVIEW

**Comment by naman-goenka** [comment]
trigger smartchecks

**Comment by naman-goenka** [comment]
trigger smartchecks

**Comment by naman-goenka** [comment]
trigger smartchecks, uts, commonchecks

**Comment by naman-goenka** [comment]
trigger uts

**Comment by naman-goenka** [comment]
trigger commonchecks

**Comment by naman-goenka** [comment]
trigger uts

**Review by abhinavmittal-harness — DISMISSED** [review]

**Comment by naman-goenka** [comment]
trigger commonchecks

**Comment by naman-goenka** [comment]
trigger uts

**Review by puthrayaharness — DISMISSED** [review]

**Comment by naman-goenka** [comment]
trigger gitleaks, pmd, compile

**Comment by naman-goenka** [comment]
trigger compile

**Comment by naman-goenka** [comment]
trigger compile

**Comment by naman-goenka** [comment]
trigger codebasehash

**Comment by naman-goenka** [comment]
trigger uts

**Comment by naman-goenka** [comment]
trigger codeformat, messagecheck, compile

**Comment by naman-goenka** [comment]
Will add codepulse annotation which is missing in two files in follow up PR

**Comment by naman-goenka** [comment]
trigger ut5, ut6, ut7, ut9

**Comment by naman-goenka** [comment]
trigger ut6

**Review by archit-harness — COMMENTED** [review]
> Reviewed 4 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55321)* status: 17 file(s) to review. 0 of 2 approvals obtained.

**Review by puthrayaharness — APPROVED** [review]

**Comment by naman-goenka** [comment]
trigger review

**Review by archit-harness — APPROVED** [review]
> Reviewed 12 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55321)* status: 17 file(s) to review.

**Comment by naman-goenka** [comment]
trigger review

**Pull request merged**
