### PR TITLE
feat: [cds-46270]: StepGroup Templates initial CRUD changes, Schema Validations and populating references

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Added Support for stepGroup Templates

Introduced the FF - CDS_STEPGROUP_TEMPLATE for the same

following operations are covered in this pr :-
* CRUD Stepgroup Templates 
* Schema Validations
* References 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40344)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger copyrightcheck

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateYamlConversionHelper.java` line 57 at r6](https://reviewable.io/reviews/harness/harness-core/40344#-NHf0B9i1YJYuq4zz6tS:-NHf0B9i1YJYuq4zz6tT:b-thco7y) ([raw file](https://github.com/harness/harness-core/blob/8096411e914737573de7d6a059e03a3a521779c1/840-template-service/src/main/java/io/harness/template/helpers/TemplateYamlConversionHelper.java#L57)):*
> ```Java
>     YamlNode rootFieldYamlNode = new YamlNode(rootJsonNode);
>     YamlField rootFieldYamlField = new YamlField(rootFieldYamlNode);
>     addAdditionalFieldsToYaml(templateEntityType, yamlConversionHandler, rootFieldYamlField);
> ```

lets just put a comment on why this special handling is needed

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 8 files at r2, 4 of 9 files at r3, 1 of 1 files at r4, 2 of 4 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40344)* status: :shipit: complete! ✓

**Comment by utkarshchoubey-harness** [comment]
trigger ti1

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40344)* status: :shipit: complete! ✓

**Pull request merged**
