### PR TITLE
[CDS-34999]: Template linking bean and inputs changes

### PR DESCRIPTION
**Pull request by prabu-kr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36943)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36943)

**Review by utkarshchoubey-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36943)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 153 at r2](https://reviewable.io/reviews/harness/harness-core/36943#-NBkJBJ92UbRP7Sjk6gV:-NBkJBJ92UbRP7Sjk6gW:bjhi5ys) ([raw file](https://github.com/harness/harness-core/blob/5b0b770bbfaf6dd4b349157faf0c6111d0d060df/840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L153)):*
> ```Java
>       List<Map<String, String>> templateVariablesMap = NGVariablesUtils.getSimplifiedVariablesList(variables);
>       templateVariables = JsonUtils.asTree(templateVariablesMap);
>       ((ObjectNode) templateSpec).set("templateVariables", templateVariables);
> ```

Can we use a constant everywhere where "templateVariables" is used
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/36943#-NBkJJkx4omdub_W_v22:-NBkJJkx4omdub_W_v23:b-r34p7z) ([raw file](https://github.com/harness/harness-core/blob/5b0b770bbfaf6dd4b349157faf0c6111d0d060df/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L51)):*
> ```Java
> import com.google.inject.Inject;
> import java.io.IOException;
> import java.util.*;
> ```

we can optimise the imports here, changing some config in intellij
___
*[`953-yaml-commons/src/main/java/io/harness/yaml/utils/NGVariablesUtils.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/36943#-NBkK-mq95B67O-gVKJg:-NBkK-mq95B67O-gVKJh:bfr0zzt) ([raw file](https://github.com/harness/harness-core/blob/5b0b770bbfaf6dd4b349157faf0c6111d0d060df/953-yaml-commons/src/main/java/io/harness/yaml/utils/NGVariablesUtils.java#L23)):*
> ```Java
> import io.harness.yaml.core.variables.SecretNGVariable;
> 
> import java.util.*;
> ```

same imports



_Code quote (from 953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java):_
```Java
createRuntimeInputForm
```

**Review by prabu-kr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36943)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/beans/yaml/NGTemplateInfoConfig.java` line 64 at r3](https://reviewable.io/reviews/harness/harness-core/36943#-NBkmGNBBuptSh4Jf1gw:-NBkmGNBBuptSh4Jf1gx:bsrjpum) ([raw file](https://github.com/harness/harness-core/blob/3de7e5b0f56d1008d9643813c9533102d9663b82/840-template-service/src/main/java/io/harness/template/beans/yaml/NGTemplateInfoConfig.java#L64)):*
> ```Java
>   String projectIdentifier;
> 
>   List<NGVariable> templateVariables;
> ```

Check with Meenaskhi for field name
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 151 at r3](https://reviewable.io/reviews/harness/harness-core/36943#-NBknD-z-rr4QvKHzD95:-NBknD-z-rr4QvKHzD96:b-r9f6o6) ([raw file](https://github.com/harness/harness-core/blob/3de7e5b0f56d1008d9643813c9533102d9663b82/840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L151)):*
> ```Java
>       templateSpec = templateConfig.getTemplateInfoConfig().getSpec();
>       List<NGVariable> variables = templateConfig.getTemplateInfoConfig().getTemplateVariables();
>       List<Map<String, String>> templateVariablesMap = NGVariablesUtils.getSimplifiedVariablesList(variables);
> ```

Don't need simplified variables list
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 160 at r3](https://reviewable.io/reviews/harness/harness-core/36943#-NBknHjT5DqkjUKzAO8E:-NBkmxcA8ymKDQ14cK6d:b-huobg3) ([raw file](https://github.com/harness/harness-core/blob/3de7e5b0f56d1008d9643813c9533102d9663b82/840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L160)):*
> ```Java
> 
>     // refreshed json node
>     JsonNode refreshedJsonNode = YamlRefreshHelper.refreshNodeFromSourceNode(templateInputs, templateSpec);
> ```

Refresh for both template variables and inputs separately
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 170 at r3](https://reviewable.io/reviews/harness/harness-core/36943#-NBknhZ48MYQYe5LK6d1:-NBknhZ48MYQYe5LK6d2:b-16xod0) ([raw file](https://github.com/harness/harness-core/blob/3de7e5b0f56d1008d9643813c9533102d9663b82/840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L170)):*
> ```Java
>       // Inserting the Updated Value of TemplateInputs corresponding to the TemplateInputs field
>       updatedValue.set(TEMPLATE_INPUTS, refreshedJsonNode);
>     }
> ```

Add similar checks for template variables here
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 183 at r3](https://reviewable.io/reviews/harness/harness-core/36943#-NBkjzUB1jrGKZSDfl6i:-NBkjzUB1jrGKZSDfl6j:bnwavo0) ([raw file](https://github.com/harness/harness-core/blob/3de7e5b0f56d1008d9643813c9533102d9663b82/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L183)):*
> ```Java
>       ObjectNode templateObjectNode =
>           (ObjectNode) YamlUtils.readTree(templateInputsYamlWithSpec).getNode().getCurrJsonNode();
>       JsonNode templateInputsYaml = templateObjectNode.retain(SPEC, "templateVariables");
> ```

Discuss with Yogesh if we can send templateInputs instead of SPEC. Or if we need to send separate strings for spec and template variables
___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/36943#-NBkphFb8DZJLUuUPOJw:-NBkphFb8DZJLUuUPOJx:byuchpu) ([raw file](https://github.com/harness/harness-core/blob/3de7e5b0f56d1008d9643813c9533102d9663b82/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java#L34)):*
> ```Java
> public class RuntimeInputFormHelper {
>   public String createTemplateFromYaml(String templateYaml) {
>     try {
> ```

No changes in this common framework. Either send template as a whole or call templateInputs and templateVariables separately with single root
___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java` line 84 at r3](https://reviewable.io/reviews/harness/harness-core/36943#-NBkqMDYCwNs-RtGhDIA:-NBkqMDYCwNs-RtGhDIB:b-w2q3xk) ([raw file](https://github.com/harness/harness-core/blob/3de7e5b0f56d1008d9643813c9533102d9663b82/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java#L84)):*
> ```Java
>     if (templateVariableSpec.getNodeType() != JsonNodeType.ARRAY) {
>       return null;
>     }
> ```

Not needed. Check using unit test with templateVariableYaml
___
*[`953-yaml-commons/src/main/java/io/harness/template/yaml/TemplateLinkConfig.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/36943#-NBkid5TAgl0JUrOU0E8:-NBkid5V9e7qJPqWCFEJ:b-hzhq03) ([raw file](https://github.com/harness/harness-core/blob/3de7e5b0f56d1008d9643813c9533102d9663b82/953-yaml-commons/src/main/java/io/harness/template/yaml/TemplateLinkConfig.java#L46)):*
> ```Java
>   @Pattern(regexp = NGRegexValidatorConstants.VERSION_LABEL_PATTERN) String versionLabel;
>   JsonNode templateInputs;
>   List<NGVariable> templateVariables;
> ```

convert to JsonNode

**Review by inderschera — DISMISSED** [review]
> Reviewed 4 of 12 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36943)* status: :shipit: complete! ✓

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 178 at r5](https://reviewable.io/reviews/harness/harness-core/36943#-NCKs8qk4AFgQn1495FE:-NCKs8ql6agVgHwdE0dw:bq79v8g) ([raw file](https://github.com/harness/harness-core/blob/77a8cb67054944c58d2f9ec74e633040754449c4/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L178)):*
> ```Java
>    * @return template inputs yaml
>    */
>   public String createTemplateInputsFromTemplate(String yaml, String accountId) {
> ```

nit: Let's optimise this method. I see it has become bulky.
We could directly create runtime input form of template yaml and then let's create an objectNode and set these values directly from runtime input form of complete yaml.

**Review by prabu-kr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36943)* status: 84 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 153 at r2](https://reviewable.io/reviews/harness/harness-core/36943#-NBkJBJ92UbRP7Sjk6gV:-NDBrjFwCSXQyFZJK1-T:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5b0b770bbfaf6dd4b349157faf0c6111d0d060df/840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L153)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Can we use a constant everywhere where "templateVariables" is used
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/36943#-NBkJJkx4omdub_W_v22:-NDBrmnUBioTu3iNp2xM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5b0b770bbfaf6dd4b349157faf0c6111d0d060df/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L51)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

we can optimise the imports here, changing some config in intellij
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 178 at r5](https://reviewable.io/reviews/harness/harness-core/36943#-NCKs8qk4AFgQn1495FE:-NDBrp7R9lOYpF2FV_Pp:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/77a8cb67054944c58d2f9ec74e633040754449c4/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L178)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: Let's optimise this method. I see it has become bulky.
We could directly create runtime input form of template yaml and then let's create an objectNode and set these values directly from runtime input form of complete yaml.
</blockquote></details>

Done
___
*[`953-yaml-commons/src/main/java/io/harness/yaml/utils/NGVariablesUtils.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/36943#-NBkK-mq95B67O-gVKJg:-NDBs-SMClkAEZZPvpKp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5b0b770bbfaf6dd4b349157faf0c6111d0d060df/953-yaml-commons/src/main/java/io/harness/yaml/utils/NGVariablesUtils.java#L23)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

same imports
</blockquote></details>

Done.

**Review by inderschera — DISMISSED** [review]
> Reviewed 20 of 40 files at r6, 4 of 6 files at r7, 61 of 61 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36943)* status: Some of the checks are too old. 1 change requests. 3. unresolved discussions. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 193 at r8](https://reviewable.io/reviews/harness/harness-core/36943#-NDRT8063gA-xQzUckJq:-NDRT8063gA-xQzUckJr:b-6cyx9w) ([raw file](https://github.com/harness/harness-core/blob/61388c71e2b9ff12706fe027b5c90b38cb87aae7/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L193)):*
> ```Java
>       JsonNode templateInputsYaml = templateJsonNode == null ? null : templateJsonNode.get(SPEC);
>       if (!featureFlagHelperService.isEnabled(accountId, FeatureName.NG_TEMPLATE_VARIABLES)) {
>         return YamlPipelineUtils.writeYamlString(templateInputsYaml);
> ```

when ff is not enabled, we will not send templateInputs as root field? 
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 197 at r8](https://reviewable.io/reviews/harness/harness-core/36943#-NDRTaWy-lhpWznZhD_w:-NDRTaWy-lhpWznZhD_x:b-em7bhz) ([raw file](https://github.com/harness/harness-core/blob/61388c71e2b9ff12706fe027b5c90b38cb87aae7/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L197)):*
> ```Java
>       JsonNode templateVariablesJson = templateJsonNode.get(YAMLFieldNameConstants.VARIABLES);
>       if (templateInputsYaml == null && templateVariablesJson == null) {
>         return templateInputsYamlWithSpec;
> ```

will this case happen? it would mean templateInputsYamlWithSpec is itself empty right?

**Review by utkarshchoubey-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 12 files at r4, 1 of 8 files at r5, 20 of 40 files at r6, 4 of 6 files at r7, 45 of 61 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36943#-:-NDWXXRg6MrwPQowxczc:bnfp4nl)* status: Some of the checks are too old. 1. unresolved discussions.

**Pull request closed without merging**
