### PR TITLE
[feat]: [CDS-34226]: Create NG CF Client and move all executions to use the new CF Client

### PR DESCRIPTION
**Pull request by nassergonzalez**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31069)

### CODE REVIEW

**Comment by nassergonzalez** [comment]
trigger messagecheck

**Comment by nassergonzalez** [comment]
trigger messagecheck

**Comment by nassergonzalez** [comment]
trigger messagecheck

**Comment by nassergonzalez** [comment]
trigger messagecheck

**Comment by nassergonzalez** [comment]
trigger messagecheck

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 9 of 12 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31069)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[260-delegate/src/test/java/software/wings/delegatetasks/CloudFormationCommandTaskHandlerTest.java, line 0 at r2](https://reviewable.io/reviews/harness/harness-core/31069#-Mx3FV2d76mxXpidISpr:-Mx3FV2d76mxXpidISps:b-7hp3v8) ([raw file](https://github.com/harness/harness-core/blob/70aa4aef6254fef6d9cca0db4b8516a5ddac8947/260-delegate/src/test/java/software/wings/delegatetasks/CloudFormationCommandTaskHandlerTest.java#L0)):*
Why did we remove it?

**Comment by nassergonzalez** [comment]
trigger ti0

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31069)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[260-delegate/src/test/java/software/wings/delegatetasks/CloudFormationCommandTaskHandlerTest.java, line  at r2](https://reviewable.io/reviews/harness/harness-core/31069#-Mx3FV2d76mxXpidISpr:-Mx3ogW68pon8NBJNClS:bp1wnny) ([raw file](https://github.com/harness/harness-core/blob/70aa4aef6254fef6d9cca0db4b8516a5ddac8947/260-delegate/src/test/java/software/wings/delegatetasks/CloudFormationCommandTaskHandlerTest.java#L)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Why did we remove it?
</blockquote></details>

This file and the one in the cloudformation-cloudformationtaskhandler package are the same, except this one that I deleted it seems that had less tests. This test seems to be like an old file not updated or used anymore)

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31069)* status: :shipit: complete! ✓

**Pull request merged**
