### PR TITLE
feat: [IDP-213]: Setup entity usage to prevent deletion of secrets in use

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Describe your changes
IDP Environment secrets refer to the Harness Secret stored in the built-in secret manager. 
Hence deleting a harness secret should be prevented if an IDP environment secret is referring to it.
Screenshot 2023-03-17 at 7 38 13 PM
Screenshot 2023-03-17 at 7 38 21 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45266)

### CODE REVIEW

**Comment by vikyathharekal** [comment]
trigger ut3, ut6, ut7

**Review by sandeepa-kv-jois — APPROVED** [review]

**Review by sandeepa-kv-jois — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45266)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Review by devesh-harness — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45266)* status: :shipit: complete! ✓

**Review by devesh-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45266)* status: :shipit: complete! ✓

**Review by deepharness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, 4 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45266)* status: Some of the checks are too old. 1 change requests. 

___
*[`idp-service/src/main/java/io/harness/idp/events/producers/SetupUsageProducer.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/45266#-NQzFsD52n7o4CA3nLoH:-NQzFsD52n7o4CA3nLoI:b-t8amxq) ([raw file](https://github.com/harness/harness-core/blob/99eb0f3e5477e3b8350c93625bd93867b2fc0212/idp-service/src/main/java/io/harness/idp/events/producers/SetupUsageProducer.java#L68)):*
> ```Java
>                                                            .setDeleteOldReferredByRecords(false)
>                                                            .build();
>       String messageId = eventProducer.send(
> ```

need to handle the exception , as it may break the loop
___
*[`idp-service/src/main/java/io/harness/idp/events/producers/SetupUsageProducer.java` line 93 at r2](https://reviewable.io/reviews/harness/harness-core/45266#-NQzG0qvCai5g07qwtdG:-NQzG0qvCai5g07qwtdH:b-t8amxq) ([raw file](https://github.com/harness/harness-core/blob/99eb0f3e5477e3b8350c93625bd93867b2fc0212/idp-service/src/main/java/io/harness/idp/events/producers/SetupUsageProducer.java#L93)):*
> ```Java
>                                                            .setDeleteOldReferredByRecords(true)
>                                                            .build();
>       String messageId = eventProducer.send(
> ```

need to handle the exception , as it may break the loop

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45266)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/events/producers/SetupUsageProducer.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/45266#-NQzFsD52n7o4CA3nLoH:-NQzxF638MZRgNIX37Fv:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/99eb0f3e5477e3b8350c93625bd93867b2fc0212/idp-service/src/main/java/io/harness/idp/events/producers/SetupUsageProducer.java#L68)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

need to handle the exception , as it may break the loop
</blockquote></details>

done
___
*[`idp-service/src/main/java/io/harness/idp/events/producers/SetupUsageProducer.java` line 93 at r2](https://reviewable.io/reviews/harness/harness-core/45266#-NQzG0qvCai5g07qwtdG:-NQzxGyE4280BtNNt9um:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/99eb0f3e5477e3b8350c93625bd93867b2fc0212/idp-service/src/main/java/io/harness/idp/events/producers/SetupUsageProducer.java#L93)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

need to handle the exception , as it may break the loop
</blockquote></details>

done

**Review by deepharness — DISMISSED** [review]
> Reviewed 2 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45266)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by vikyathharekal** [comment]
trigger ut5, ut7

**Review by deepharness — DISMISSED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45266)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by sandeepa-kv-jois — APPROVED** [review]

**Review by devesh-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45266)* status: :shipit: complete! ✓

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, 3 of 7 files at r2, 1 of 1 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45266)* status: :shipit: complete! ✓

___
*[`970-ng-commons/src/main/java/io/harness/EntityType.java` line 569 at r4](https://reviewable.io/reviews/harness/harness-core/45266#-NR2cVX0-R-4BRPSDzzC:-NR2cVX0-R-4BRPSDzzD:b-etac70) ([raw file](https://github.com/harness/harness-core/blob/40698215f28f4d347afe802588f086d4c1368b0e/970-ng-commons/src/main/java/io/harness/EntityType.java#L569)):*
> ```Java
>       ModuleType.STO, EntityTypeConstants.AWS_SECURITY_HUB, IdentifierRef.class, EntityYamlRootNames.AWS_SECURITY_HUB),
>   @JsonProperty(EntityTypeConstants.ENVIRONMENT_SECRET)
>   ENVIRONMENT_SECRET(ModuleType.IDP, EntityTypeConstants.ENVIRONMENT_SECRET, IdentifierRef.class);
> ```

Whats Environment Secret? Its not clear from the name

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45266)* status: 1 change requests. 1. unresolved discussions. 

___
*[`970-ng-commons/src/main/java/io/harness/EntityType.java` line 569 at r4](https://reviewable.io/reviews/harness/harness-core/45266#-NR2cVX0-R-4BRPSDzzC:-NR2ks749tby9c8_ud0-:b-dunh8l) ([raw file](https://github.com/harness/harness-core/blob/40698215f28f4d347afe802588f086d4c1368b0e/970-ng-commons/src/main/java/io/harness/EntityType.java#L569)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Whats Environment Secret? Its not clear from the name
</blockquote></details>

idp-ui (backstage) needs certain **environment** variables to be set, like the GITHUB_TOKEN, PAGERDUTY_TOKEN, etc.
Customers would use harness UI to store the values for these as harness **secrets**.
Environment Secret represents the mapping of the environment variable to the harness secret.
```
{
    "_id" : ObjectId("64147430e91b5f28bdb3a598"),
    "envName" : "GITHUB_TOKEN",
    "accountIdentifier" : "kmpySmUISimoRrJL6NL73w",
    "secretIdentifier" : "accountGithubToken",
    "createdAt" : NumberLong(1679062064825),
    "lastModifiedAt" : NumberLong(1679062064825),
    "isDeleted" : false,
    "deletedAt" : NumberLong(0),
    "_class" : "io.harness.idp.secret.beans.entity.EnvironmentSecretEntity"
}
```

Please refer https://harness.atlassian.net/wiki/spaces/IDP/pages/21275181267/Design+Document+IDP+Secrets+Management for more details

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45266)* status: :shipit: complete! ✓

___
*[`970-ng-commons/src/main/java/io/harness/EntityType.java` line 569 at r4](https://reviewable.io/reviews/harness/harness-core/45266#-NR2cVX0-R-4BRPSDzzC:-NR2thd13VOQoRQiBIWf:b-p7pbv3) ([raw file](https://github.com/harness/harness-core/blob/40698215f28f4d347afe802588f086d4c1368b0e/970-ng-commons/src/main/java/io/harness/EntityType.java#L569)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

idp-ui (backstage) needs certain **environment** variables to be set, like the GITHUB_TOKEN, PAGERDUTY_TOKEN, etc.
Customers would use harness UI to store the values for these as harness **secrets**.
Environment Secret represents the mapping of the environment variable to the harness secret.
```
{
    "_id" : ObjectId("64147430e91b5f28bdb3a598"),
    "envName" : "GITHUB_TOKEN",
    "accountIdentifier" : "kmpySmUISimoRrJL6NL73w",
    "secretIdentifier" : "accountGithubToken",
    "createdAt" : NumberLong(1679062064825),
    "lastModifiedAt" : NumberLong(1679062064825),
    "isDeleted" : false,
    "deletedAt" : NumberLong(0),
    "_class" : "io.harness.idp.secret.beans.entity.EnvironmentSecretEntity"
}
```

Please refer https://harness.atlassian.net/wiki/spaces/IDP/pages/21275181267/Design+Document+IDP+Secrets+Management for more details 
</blockquote></details>

I think EnvironmentSecret is not a right name. BackStageSecretEntity?

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45266)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/EntityType.java` line 569 at r4](https://reviewable.io/reviews/harness/harness-core/45266#-NR2cVX0-R-4BRPSDzzC:-NRXqM17BGTr13CKqgQO:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/40698215f28f4d347afe802588f086d4c1368b0e/970-ng-commons/src/main/java/io/harness/EntityType.java#L569)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

As discussed offline, we will be modifying the data model, keeping this PR on hold until that.
</blockquote></details>

Done

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 9 of 12 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45266#-:-NRbERosAdGF2uyoGJjX:bnfp4nl)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by vikyathharekal** [comment]
trigger ut3

**Review by deepharness — APPROVED** [review]
> Reviewed 9 of 12 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45266)* status: :shipit: complete! ✓

**Review by shashank-harness — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 9 of 12 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45266)* status: :shipit: complete! ✓

**Pull request merged**
