### PR TITLE
fix: [CDS-44477]: fixed Capability check for delegates maps all hosts…

### PR DESCRIPTION
**Pull request by vitsafronovici**
…, not only first host defined in infra def

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38575)

### CODE REVIEW

**Comment by vitsafronovici** [comment]
trigger ti0, ti1, ti2, ti3, ti4, ft1, ft2

**Review by acasian-harness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38575)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/SshHostConnectionCapabilityCheck.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/38575#-NE13Vf_1fJPuw9lYkkR:-NE13Vf_1fJPuw9lYkkS:b-jsp4zt) ([raw file](https://github.com/harness/harness-core/blob/00c783ef8c83c114220f87997afc80a682ee67fd/930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/SshHostConnectionCapabilityCheck.java#L63)):*
> ```Java
>             .orElseThrow(()
>                              -> new InvalidArgumentsException(
>                                  format("Not found hostName, host: %s, extracted port: %s", capability.getHost(), port),
> ```

Can we rephrase to `Failed to extract host name, host: %s, port: %s`
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/SshHostConnectionCapabilityCheck.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/38575#-NE132kE4xTJzcl1MVjv:-NE132kE4xTJzcl1MVjw:b-t7kuhf) ([raw file](https://github.com/harness/harness-core/blob/00c783ef8c83c114220f87997afc80a682ee67fd/930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/SshHostConnectionCapabilityCheck.java#L92)):*
> ```Java
>   Session connect(SshSessionConfig config) throws JSchException {
>     Session session = SshSessionFactory.getSSHSession(config);
>     session.disconnect();
> ```

nit: shouldn't we disconnect in finally? Also why are we returtning session, only for UT purpose?
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/38575#-NE13txc92HXz6-p6uCF:-NE13txc92HXz6-p6uCG:bsj45bw) ([raw file](https://github.com/harness/harness-core/blob/00c783ef8c83c114220f87997afc80a682ee67fd/930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java#L67)):*
> ```Java
>             .orElseThrow(()
>                              -> new InvalidArgumentsException(
>                                  format("Not found hostName, host: %s, extracted port: %s", capability.getHost(), port),
> ```

same, can we rephrase it
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/SshCommandTaskParameters.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/38575#-NE1LMoS9XSyK519JXHY:-NE1LMoS9XSyK519JXHZ:b-vqzdcs) ([raw file](https://github.com/harness/harness-core/blob/893778655b9a1a23e6442efbbf9d7ec067d165b6/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/SshCommandTaskParameters.java#L52)):*
> ```Java
>       capabilities.addAll(EncryptedDataDetailsCapabilityHelper.fetchExecutionCapabilitiesForEncryptedDataDetails(
>           pdcSshInfraDelegateConfig.getEncryptionDataDetails(), maskingEvaluator));
>     } else if (sshInfraDelegateConfig instanceof AzureSshInfraDelegateConfig) {
> ```

not getting here, why azure, aws related capabilities are removed?

**Review by acasian-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38575)* status: :shipit: complete! ✓

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 11 of 13 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38575)* status: :shipit: complete! ✓

**Comment by vitsafronovici** [comment]
trigger codebasehash

**Pull request merged**
