### PR TITLE
[fix]:[pie-7457]: Stop pipeline execution when storeTypes are different

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Stop the pipeline execution when the inline pipeline has been moved to remote and the input set has not been moved.

Impact -> Customer will not be able to execute the pipeline when the input set and pipeline are of different storeTypes.

Tests:
1. when both the entities are of same type.
2. when pipeline is remote and inputSet is inline. 

ReleaseNotes summary needed? No

Is it new task type? No
Did you make changes to the code in a backward-compatible manner? Yes
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? Yes
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? Yes
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No change
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? Yes
if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? Yes
Did you remove an enum → No
Did you add an enum(That too at end of list) → No
FeatureFlag Added/Removed -> No
Verify Changes with affects any -> No

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42274)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/42274#-NL0XH5dE20Box8XEFSh:-NL0XH5dE20Box8XEFSi:b9miu9c) ([raw file](https://github.com/harness/harness-core/blob/5612275a020e0c95f8a4a97f91a852bbc19d7199/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L63)):*
> ```Java
>   private final GitSyncSdkService gitSyncSdkService;
> 
>   public PipelineEntity getPipelineYaml(String accountId, String orgIdentifier, String projectIdentifier,
> ```

can we change names of the methods as well accordingly

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 230 at r1](https://reviewable.io/reviews/harness/harness-core/42274#-NL0XdGM-t7S3VqEhFD9:-NL0XdGM-t7S3VqEhFDA:bcy4ntg) ([raw file](https://github.com/harness/harness-core/blob/5612275a020e0c95f8a4a97f91a852bbc19d7199/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L230)):*
> ```Java
>       if (!pipelineEntity.getStoreType().equals(inputSet.getStoreType())) {
>         throw new InvalidRequestException(
>             String.format("The Pipeline %s and the InputSet %s are not of the same StoreType", pipelineIdentifier,
> ```

We should put a better error message.

eg: "Pipeline of storeType [] cannot be used with input-set of storeType [], please migrate to same storeType to use them"

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 230 at r1](https://reviewable.io/reviews/harness/harness-core/42274#-NL0XdGM-t7S3VqEhFD9:-NL0XvC55k7xC-daUwlK:bb5naii) ([raw file](https://github.com/harness/harness-core/blob/5612275a020e0c95f8a4a97f91a852bbc19d7199/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L230)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should put a better error message.

eg: "Pipeline of storeType [] cannot be used with input-set of storeType [], please migrate to same storeType to use them"
</blockquote></details>

We can also put a proper hint and explanation exceptions here for proper formatting on UI

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42274)* status: 3 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/42274#-NL0XH5dE20Box8XEFSh:-NL0Xej48lS3HI84zj9H:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5612275a020e0c95f8a4a97f91a852bbc19d7199/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L63)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we change names of the methods as well accordingly
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 230 at r1](https://reviewable.io/reviews/harness/harness-core/42274#-NL0XdGM-t7S3VqEhFD9:-NL0YKJd71aB19LXuF8q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5612275a020e0c95f8a4a97f91a852bbc19d7199/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L230)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We can also put a proper hint and explanation exceptions here for proper formatting on UI
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/42274#-NL0pWfH4xd7bwxY3ce7:-NL0pWfH4xd7bwxY3ce8:b-79lks) ([raw file](https://github.com/harness/harness-core/blob/ad8dd16bec3f815f2dfa2019574b6af07d7fefab/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L79)):*
> ```Java
>   }
> 
>   private PipelineEntity getPipelineYamlForOldGitSyncFlow(String accountId, String orgIdentifier,
> ```

we need to change method names for all wherever we have done changes.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 230 at r1](https://reviewable.io/reviews/harness/harness-core/42274#-NL0XdGM-t7S3VqEhFD9:-NL0pfCp3NtaOnO4Y3dD:b-nsscu9) ([raw file](https://github.com/harness/harness-core/blob/5612275a020e0c95f8a4a97f91a852bbc19d7199/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L230)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think we can put the hint and exception here itself as hard-coded string as its one off string and not re-usable. Or, please change the variable name for those strings as currently those are too generic.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42274)* status: 3 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 230 at r1](https://reviewable.io/reviews/harness/harness-core/42274#-NL0XdGM-t7S3VqEhFD9:-NL0q8az4UF6KsQrY3dk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5612275a020e0c95f8a4a97f91a852bbc19d7199/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L230)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we can put the hint and exception here itself as hard-coded string as its one off string and not re-usable. Or, please change the variable name for those strings as currently those are too generic.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/42274#-NL0pWfH4xd7bwxY3ce7:-NL0qPJh3Ej2By4yT5hE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ad8dd16bec3f815f2dfa2019574b6af07d7fefab/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L79)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we need to change method names for all wherever we have done changes.
</blockquote></details>

Done.



_Code quote:_
```Java
getPipelineYamlForOldGitSyncFlow
```

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42274)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42274)* status: :shipit: complete! ✓

**Pull request merged**
