### PR TITLE
feat: [PL-42154]: Process notification trigger request

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes

Summary:
- Process notification trigger request at notification service and mapper to notificationRequest
- Add entity-based event parameter to capture event/entity level data needed to send notification
- Add client-side API to get notification rule

Test
-Unit test for processing trigger requests for different channels and events
-End-to-end flow sending notification for one event type
-Sanity test

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55020)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55020)* status: 20 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/entities/eventmetadata/ConnectorNotificationEventParameters.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/55020#-NieTNL2-ZAdrt_rszhP:-NieTNL2-ZAdrt_rszhQ:b-pjmgkw) ([raw file](https://github.com/harness/harness-core/blob/1e4bedc5b16ed9e1f774f914d511e9e7fc20897b/platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/entities/eventmetadata/ConnectorNotificationEventParameters.java#L21)):*
> ```Java
>   List<ConnectorInfo> connectors;
> 
>   private class ConnectorInfo {
> ```

Why this private class is needed here? Also will it always, just hold the scope identifiers?
___
*[`platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/remote/resources/NotificationRuleResource.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/55020#-NieQHCw3JA467s5MDDk:-NieQHCw3JA467s5MDDl:b3i6al6) ([raw file](https://github.com/harness/harness-core/blob/1e4bedc5b16ed9e1f774f914d511e9e7fc20897b/platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/remote/resources/NotificationRuleResource.java#L36)):*
> ```Java
>       , @ApiResponse(code = 500, response = ErrorDTO.class, message = "Internal server error")
>     })
> public interface NotificationRuleResource {
> ```

Why this is not implemented using spec first approach?
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationEventConfig.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/55020#-NieQper67RTyFcaV_bn:-NieQper67RTyFcaV_bo:b-omslqk) ([raw file](https://github.com/harness/harness-core/blob/1e4bedc5b16ed9e1f774f914d511e9e7fc20897b/platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationEventConfig.java#L30)):*
> ```Java
>   NotificationEntity notificationEntity;
>   NotificationEvent notificationEvent;
>   NotificationEventParameters notificationEventParameters;
> ```

The interface NotificationEventParameters is annotated with @JsonTypeInfo and @JsonSubType. The external property used to infer the subtype is type. The type property is missing here and NotificationEventParameters notificationEventParameters; is even missing annotation.
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationRule.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/55020#-NieRdBI3HQGn8Wvlhfg:-NieRdBI3HQGn8Wvlhfh:b9x78k) ([raw file](https://github.com/harness/harness-core/blob/6039126ac441d2fa2f15ade34ecbce2ee4fa9a2d/platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationRule.java#L58)):*
> ```Java
>   String projectIdentifier;
> 
>   NotificationEntity notificationEntity;
> ```

I see this field is moved to NotificationEventConfig. Is this movement as per the proposed design?

**Comment by jennyjames21** [comment]
*[`platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/entities/eventmetadata/ConnectorNotificationEventParameters.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/55020#-NieTNL2-ZAdrt_rszhP:-NiflT934csNx5yw51t0:b-x7x7dz) ([raw file](https://github.com/harness/harness-core/blob/1e4bedc5b16ed9e1f774f914d511e9e7fc20897b/platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/entities/eventmetadata/ConnectorNotificationEventParameters.java#L21)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why this private class is needed here? Also will it always, just hold the scope identifiers?
</blockquote></details>

identifier is missing here. Correct me if im wrong connector look up need identifier + scope right

**Comment by jennyjames21** [comment]
*[`platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/entities/eventmetadata/ConnectorNotificationEventParameters.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/55020#-NieTNL2-ZAdrt_rszhP:-NigpbpC2sushNToJSDt:b-ovh4qa) ([raw file](https://github.com/harness/harness-core/blob/1e4bedc5b16ed9e1f774f914d511e9e7fc20897b/platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/entities/eventmetadata/ConnectorNotificationEventParameters.java#L21)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

identifier is missing here. Correct me if im wrong connector look up need identifier + scope right
</blockquote></details>

added identifier

**Comment by jennyjames21** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationEventConfig.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/55020#-NieQper67RTyFcaV_bn:-Nigpfaq0D32_TXF5XmQ:blif7mk) ([raw file](https://github.com/harness/harness-core/blob/1e4bedc5b16ed9e1f774f914d511e9e7fc20897b/platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationEventConfig.java#L30)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

The interface NotificationEventParameters is annotated with @JsonTypeInfo and @JsonSubType. The external property used to infer the subtype is type. The type property is missing here and NotificationEventParameters notificationEventParameters; is even missing annotation.
</blockquote></details>

updated, please check

**Comment by jennyjames21** [comment]
*[`platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/remote/resources/NotificationRuleResource.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/55020#-NieQHCw3JA467s5MDDk:-Nigpk9u6ycoyGDBMSm7:b-ire247) ([raw file](https://github.com/harness/harness-core/blob/1e4bedc5b16ed9e1f774f914d511e9e7fc20897b/platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/remote/resources/NotificationRuleResource.java#L36)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why this is not implemented using spec first approach?
</blockquote></details>

yes, removed for now

**Review by jennyjames21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55020)* status: 20 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationRule.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/55020#-NieRdBI3HQGn8Wvlhfg:-Nifm5RQ8P7s9z_AnSOf:b-wp7t78) ([raw file](https://github.com/harness/harness-core/blob/6039126ac441d2fa2f15ade34ecbce2ee4fa9a2d/platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationRule.java#L58)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

I see this field is moved to NotificationEventConfig. Is this movement as per the proposed design?
</blockquote></details>

yes restriction of one entity per rule is no more applicable

**Comment by jennyjames21** [comment]
trigger uts

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55020)* status: 20 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/entities/eventmetadata/ConnectorNotificationEventParameters.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/55020#-NieTNL2-ZAdrt_rszhP:-NihGg_UDiIWg8nOLome:b-s2wnq4) ([raw file](https://github.com/harness/harness-core/blob/1e4bedc5b16ed9e1f774f914d511e9e7fc20897b/platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/entities/eventmetadata/ConnectorNotificationEventParameters.java#L21)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

added identifier
</blockquote></details>

Yes you are correct, you need identifier + scope. But why do we need private class here?
Can we not make use of BaseNGAccess if the only fields required are identifier + scope?
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationEventConfig.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/55020#-NihDhgB9D2T0XBiMsH2:-NihDhgB9D2T0XBiMsH3:bhb60by) ([raw file](https://github.com/harness/harness-core/blob/09189b2ea8f8502fb644f1c609f133b4ddf9f5c6/platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationEventConfig.java#L34)):*
> ```Java
> @FieldNameConstants(innerTypeName = "NotificationEventConfigKeys")
> public class NotificationEventConfig {
>   @NotNull @JsonProperty("type") NotificationEntity notificationEntity;
> ```

Do we want to refer to this field as "type" in json? We can instead write property="notificationEntity" in JsonTypeInfo annotation on notificationEventParameters field below unless we really want to rename this field to type in json.

**Comment by jennyjames21** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationEventConfig.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/55020#-NihDhgB9D2T0XBiMsH2:-NihLOYeBDz_dCfXDJkA:b-v094fq) ([raw file](https://github.com/harness/harness-core/blob/09189b2ea8f8502fb644f1c609f133b4ddf9f5c6/platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationEventConfig.java#L34)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Do we want to refer to this field as "type" in json? We can instead write property="notificationEntity" in JsonTypeInfo annotation on notificationEventParameters field below unless we really want to rename this field to type in json.
</blockquote></details>

updated with property="notificationEntity"

**Comment by jennyjames21** [comment]
*[`platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/entities/eventmetadata/ConnectorNotificationEventParameters.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/55020#-NieTNL2-ZAdrt_rszhP:-NihLS5jBOldAFYgsgwu:bazj7b6) ([raw file](https://github.com/harness/harness-core/blob/1e4bedc5b16ed9e1f774f914d511e9e7fc20897b/platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/entities/eventmetadata/ConnectorNotificationEventParameters.java#L21)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Yes you are correct, you need identifier + scope. But why do we need private class here?
Can we not make use of BaseNGAccess if the only fields required are identifier + scope?
</blockquote></details>

removed private class and add BaseNGAccess instead

**Review by nishantsaini20 — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55020)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Review by AbhijithHarness — APPROVED** [review]

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55020)* status: 20 file(s) to review.

**Pull request merged**
