### PR TITLE
feat: [cds-48711]: adding repostory type field

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
Added repositorytype field to google artifact registry service outcome
image

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41823)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java` line 327 at r1](https://reviewable.io/reviews/harness/harness-core/41823#-NJjd9Y8B37Uwqpvv_2K:-NJjd9Y8B37Uwqpvv_2L:b-ib19wn) ([raw file](https://github.com/harness/harness-core/blob/a627fd409ae2339ce8fcf65b8ff0a4a951b4b6c2/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java#L327)):*
> ```Java
>         .image(getImageValue(garDelegateResponse))
>         .imagePullSecret(createImagePullSecret(ArtifactUtils.getArtifactKey(googleArtifactRegistryConfig)))
>         .repositoryType(googleArtifactRegistryConfig.getGoogleArtifactRegistryType().getValue())
> ```

is this always non null ?



_Code quote:_
```Java
googleArtifactRegistryConfig.getGoogleArtifactRegistryType()
```

**Comment by vivekkarnatiharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java` line 327 at r1](https://reviewable.io/reviews/harness/harness-core/41823#-NJjd9Y8B37Uwqpvv_2K:-NJjdZOv7iyVnY-4OmDY:baqm2we) ([raw file](https://github.com/harness/harness-core/blob/a627fd409ae2339ce8fcf65b8ff0a4a951b4b6c2/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java#L327)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this always non null ?
</blockquote></details>

 @JsonProperty("repositoryType")
  @NotNull
  @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH, allowableValues = "docker")
  ParameterField<String> googleArtifactRegistryType;
It is always notnull. ....

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41823)* status: :shipit: complete! ✓

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41823)* status: :shipit: complete! ✓

**Pull request merged**
