### PR TITLE
feat: [IDP-304]: Handeling env variables as secret for plugin configs.

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45975)

### CODE REVIEW

**Comment by devesh-harness** [comment]
trigger messagechec

**Comment by devesh-harness** [comment]
trigger messagecheck

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45975)* status: 30 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 1266 at r1](https://reviewable.io/reviews/harness/harness-core/45975#-NSA1hQZDulcv5x_rI1C:-NSA1hQZDulcv5x_rI1D:b7v8iuh) ([raw file](https://github.com/harness/harness-core/blob/0ba99d98aa2e73605b0c02cdcd5701c1b3503654/idp-service/contracts/openapi/v1/openapi.yaml#L1266)):*
> ```YAML
>       required:
>         - merged_config
>     AppConfigEnvVariables:
> ```

Can we use List<BackstageEnvSecretVariable> instead?
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/ReservedEnvVariables.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/45975#-NSA23wRA4o2sPy4pfRi:-NSA23wRA4o2sPy4pfRj:b1efogt) ([raw file](https://github.com/harness/harness-core/blob/0ba99d98aa2e73605b0c02cdcd5701c1b3503654/idp-service/src/main/java/io/harness/idp/configmanager/ReservedEnvVariables.java#L17)):*
> ```Java
>       new ArrayList<>(List.of(GitIntegrationConstants.GITHUB_TOKEN, GitIntegrationConstants.GITHUB_APP_ID,
>           GitIntegrationConstants.GITHUB_APP_PRIVATE_KEY_REF, GitIntegrationConstants.GITLAB_TOKEN,
>           GitIntegrationConstants.BITBUCKET_TOKEN, GitIntegrationConstants.AZURE_REPO_TOKEN));
> ```

Can we add BACKEND_SECRET to this list? cc: @sarthakkasat 
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/repositories/ConfigEnvVariablesRepositoryCustom.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/45975#-NSA3lk60K3qqU-bqNeF:-NSA3lk60K3qqU-bqNeG:b-yiuec9) ([raw file](https://github.com/harness/harness-core/blob/0ba99d98aa2e73605b0c02cdcd5701c1b3503654/idp-service/src/main/java/io/harness/idp/configmanager/repositories/ConfigEnvVariablesRepositoryCustom.java#L20)):*
> ```Java
> @OwnedBy(HarnessTeam.IDP)
> public interface ConfigEnvVariablesRepositoryCustom {
>   List<PluginConfigEnvVariablesEntity> getAllEnvVariablesForMultiplePluginIds(
> ```

as discussed - can we get just based on account id? since we don't store mappings of disabled plugins



_Code quote:_
```Java
getAllEnvVariablesForMultiplePluginIds
```
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigEnvVariablesServiceImpl.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/45975#-NSAAmjX0Fqjb4TsMJ0R:-NSAAmjX0Fqjb4TsMJ0S:bew606) ([raw file](https://github.com/harness/harness-core/blob/0ba99d98aa2e73605b0c02cdcd5701c1b3503654/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigEnvVariablesServiceImpl.java#L81)):*
> ```Java
>     List<PluginConfigEnvVariablesEntity> pluginsEnvVariablesEntity =
>         configEnvVariablesRepository.findAllByAccountIdentifierAndPluginId(accountIdentifier, appConfig.getConfigId());
>     configEnvVariablesRepository.deleteAllByPluginId(appConfig.getConfigId());
> ```

as discussed - we can try finding first and create new if we don't find exact match

**Comment by sarthakkasat** [comment]
*[`idp-service/src/main/java/io/harness/idp/configmanager/ReservedEnvVariables.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/45975#-NSA23wRA4o2sPy4pfRi:-NSC-r6b2w7Cz7hBecMI:b-biuc5) ([raw file](https://github.com/harness/harness-core/blob/0ba99d98aa2e73605b0c02cdcd5701c1b3503654/idp-service/src/main/java/io/harness/idp/configmanager/ReservedEnvVariables.java#L17)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we add BACKEND_SECRET to this list? cc: @sarthakkasat 
</blockquote></details>

Will add once my code changes are merged

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45975)* status: 36 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 1266 at r1](https://reviewable.io/reviews/harness/harness-core/45975#-NSA1hQZDulcv5x_rI1C:-NSC05bo8JzgwIg_DDw7:b6xqw0g) ([raw file](https://github.com/harness/harness-core/blob/0ba99d98aa2e73605b0c02cdcd5701c1b3503654/idp-service/contracts/openapi/v1/openapi.yaml#L1266)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we use List<BackstageEnvSecretVariable> instead?
</blockquote></details>

removed it it was not needed.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/ReservedEnvVariables.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/45975#-NSA23wRA4o2sPy4pfRi:-NSC0ElCDN2Udje3_oIT:b-7rl0jd) ([raw file](https://github.com/harness/harness-core/blob/0ba99d98aa2e73605b0c02cdcd5701c1b3503654/idp-service/src/main/java/io/harness/idp/configmanager/ReservedEnvVariables.java#L17)):*
<details><summary><i>Previously, sarthakkasat (Sarthak Kasat) wrote…</i></summary><blockquote>

Will add once my code changes are merged
</blockquote></details>

done.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/repositories/ConfigEnvVariablesRepositoryCustom.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/45975#-NSA3lk60K3qqU-bqNeF:-NSCOT6w8-DreVIHVRQj:b-apojcs) ([raw file](https://github.com/harness/harness-core/blob/0ba99d98aa2e73605b0c02cdcd5701c1b3503654/idp-service/src/main/java/io/harness/idp/configmanager/repositories/ConfigEnvVariablesRepositoryCustom.java#L20)):*
> getAllEnvVariablesForMultiplePluginIds
as discussed this approach is not correct.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigEnvVariablesServiceImpl.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/45975#-NSAAmjX0Fqjb4TsMJ0R:-NSCn5-7DWmG2XsWugu0:besqmzf) ([raw file](https://github.com/harness/harness-core/blob/0ba99d98aa2e73605b0c02cdcd5701c1b3503654/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigEnvVariablesServiceImpl.java#L81)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

as discussed - we can try finding first and create new if we don't find exact match
</blockquote></details>

not fixing will discuss.

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 12 of 30 files at r1, 14 of 20 files at r2, 2 of 5 files at r3, 3 of 7 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45975)* status: 24 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 14 of 20 files at r2, 2 of 5 files at r3, 3 of 7 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45975)* status: 36 file(s) to review. 2. unresolved discussions. 

___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java` line 139 at r5](https://reviewable.io/reviews/harness/harness-core/45975#-NSG7xzoA9x7AcgHbHQz:-NSG7xzoA9x7AcgHbHR-:b-fjv4of) ([raw file](https://github.com/harness/harness-core/blob/e48b6913fd302c6eba5cc033ffbe91dfc861f7b3/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java#L139)):*
> ```Java
>     Boolean createdNewConfig = false;
> 
>     if (isEnabled == true) {
> ```

nit: if (isEnabled)



_Code quote:_
```Java
if (isEnabled
```

**Pull request merged**
