### PR TITLE
[fix]: [CDS-69962]: Include skipped stages inside parallel blocks for PRB

### PR DESCRIPTION
**Pull request by namanvermah**
Changed how parallel stages are handled inside `transformProcessedYamlForPipelineRollbackMode`. Also extracted out a separate class for yaml transformation.
Before:
Screenshot 2023-05-23 at 11 37 40 AM

After:
Screenshot 2023-05-23 at 11 37 30 AM

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48211)

### CODE REVIEW

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48211)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by namanvermah** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48211)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
trigger review

**Pull request merged**
