### PR TITLE
feat: [SRM-12347]: Backdoor API to delete CVConfig immediately

### PR DESCRIPTION
**Pull request by praveensugavanam**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38697)

### CODE REVIEW

**Review by dhruv-harness — COMMENTED** [review]
Could you please share the reason why we need this API. 

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38697#-:-NE9tG2C-ZZFkIiaEKNv:b-6d3sqz)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/resources/CVConfigResource.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/38697#-NE9sLdw7fbpHRHEtCIt:-NE9sLdw7fbpHRHEtCIu:bwj82tx) ([raw file](https://github.com/harness/harness-core/blob/be4a53f5ec2b9f961b0d4703c4c7627828d21964/300-cv-nextgen/src/main/java/io/harness/cvng/core/resources/CVConfigResource.java#L58)):*
> ```Java
>   @ApiOperation(value = "Backdoor API to immediately delete CVConfig", nickname = "deleteCVConfig")
>   public RestResponse<Void> deleteCVConfig(@NotNull @BeanParam ProjectParams projectParams,
>       @ApiParam(required = true) @NotNull @PathParam("identifier") @ResourceIdentifier String cvConfigId) {
> ```

We should use @NotBlank unless we are accepting blank strings as valid inputs. 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVConfigServiceImpl.java` line 109 at r2](https://reviewable.io/reviews/harness/harness-core/38697#-NE9sriS8vObPAyUEpbG:-NE9sriS8vObPAyUEpbH:b-o1ynm5) ([raw file](https://github.com/harness/harness-core/blob/be4a53f5ec2b9f961b0d4703c4c7627828d21964/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVConfigServiceImpl.java#L109)):*
> ```Java
> 
>   @Override
>   public void deleteImmediately(@NotNull String cvConfigId) {
> ```

Since this impl is same as the delete impl with just the duration of the sidekick execution changed, cwe can make a private method which takes duration as a parameter and use it in both the delete variations.

**Review by praveensugavanam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38697)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/resources/CVConfigResource.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/38697#-NE9sLdw7fbpHRHEtCIt:-NECI6PK0m4_-anIpw4L:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/be4a53f5ec2b9f961b0d4703c4c7627828d21964/300-cv-nextgen/src/main/java/io/harness/cvng/core/resources/CVConfigResource.java#L58)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

We should use @NotBlank unless we are accepting blank strings as valid inputs. 
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVConfigServiceImpl.java` line 109 at r2](https://reviewable.io/reviews/harness/harness-core/38697#-NE9sriS8vObPAyUEpbG:-NECI85ECmSD_51PkSSf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/be4a53f5ec2b9f961b0d4703c4c7627828d21964/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVConfigServiceImpl.java#L109)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Since this impl is same as the delete impl with just the duration of the sidekick execution changed, cwe can make a private method which takes duration as a parameter and use it in both the delete variations.
</blockquote></details>

Done.

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38697)* status: 1 file(s) to review. 2. unresolved discussions.

**Comment by praveensugavanam** [comment]
trigger messagecheck

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38697)* status: 1 file(s) to review. 2. unresolved discussions.

**Pull request merged**
