### PR TITLE
techdebt: [PIE-2817]: Fix Graph Generation getting stuck

### PR DESCRIPTION
**Pull request by hextechpal**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30944)

### CODE REVIEW

**Review by naidu-harness — DISMISSED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30944)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by hextechpal** [comment]
trigger messagecheck

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 2 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30944)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30944)* status: :shipit: complete! ✓

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30944#-:-MwebznAAZQXQU7Pt_4K:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
