### PR TITLE
fix: [PL-23784]: fixing usergroup list call error related to page req…

### PR DESCRIPTION
**Pull request by naman-goenka**
…uest

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31502)

### CODE REVIEW

**Comment by naman-goenka** [comment]
trigger messagecheck

**Review by karansiwach360 — DISMISSED** [review]
> Reviewed 5 of 9 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31502)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by naman-goenka** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/31502)_ status: 10 file(s) to review. 0 of 2 approvals obtained.
> 
> _[400-rest/src/main/java/software/wings/resources/UserGroupResource.java, line 144 at r4](https://reviewable.io/reviews/harness/harness-core/31502#-MyrD5ca6uz8wbp7qyS7:-MyrD5ca6uz8wbp7qyS8:bvo6xz8) ([raw file](https://github.com/harness/harness-core/blob/18d0783ff10aec9fb177a4879a13955876ee8d37/400-rest/src/main/java/software/wings/resources/UserGroupResource.java#L144)):_
> 
> > ```java
> >   @AuthRule(permissionType = USER_PERMISSION_READ)
> >   @ExceptionMetered
> >   public RestResponse<Long> getCountOfUserGroups(@QueryParam("accountId") String accountId) {
> > ```
> 
> Is it needed on the UI and where?

Yes, its needed in UI. It's needed to remove stop gap solution ([1](https://github.com/wings-software/wingsui/blob/1c8d1a1346e141c419e0bc0e97fce7d682aad793/src/stores/AuthenticationSettingsStore.ts#L442) and [2](https://github.com/wings-software/wingsui/blob/1c8d1a1346e141c419e0bc0e97fce7d682aad793/src/stores/AuthenticationSettingsStore.ts#L197)) by calling this API in UserGroupService. Please refer to [this PR](https://github.com/wings-software/wingsui/pull/13211/files) for exact usage.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 5 of 9 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31502#-:-MyujbpuAeRhm8H-qC5F:bnfp4nl)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by karansiwach360 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31502)* status: Some of the checks are too old.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31502#-:-MzMiYtO5scwPJmr9FIa:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by karansiwach360 — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31502)* status: :shipit: complete! ✓

**Pull request merged**
