### PR TITLE
fix: [CDS-41949]: merge nonentity variables with parent

### PR DESCRIPTION
**Pull request by Y0709**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37259)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37259)

**Comment by Y0709** [comment]
trigger messagecheck

**Comment by Y0709** [comment]
trigger messagecheck

**Comment by Y0709** [comment]
trigger messagecheck

**Review by poojaSinghal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37259)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java` line 1222 at r1](https://reviewable.io/reviews/harness/harness-core/37259#-NBkfyg13zLgHtS4MPi4:-NBkfyg22XSVaz_M2UyX:b8e06xd) ([raw file](https://github.com/harness/harness-core/blob/d56fe42698664de258d40a9c1eb8fb67cf769aa4/400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java#L1222)):*
> ```Java
>             mergeRequired(existingVar, newVar);
>             mergeAllowedValuesAndList(existingVar, newVar);
>             if (checkRuntime(existingVar, isRuntime)) {
> ```

move the error message throw also inside the method. 
___
*[`400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java` line 1226 at r1](https://reviewable.io/reviews/harness/harness-core/37259#-NBkg1eN41xvCBnN2ujW:-NBkg1eN41xvCBnN2ujX:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/d56fe42698664de258d40a9c1eb8fb67cf769aa4/400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java#L1226)):*
> ```Java
>                   String.format("Variable %s is not marked as runtime in all pipeline stages", variable.getName()));
>             }
>             if (!checkFixed(existingVar, newVar.isFixed())) {
> ```

same

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37259)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java` line 1222 at r1](https://reviewable.io/reviews/harness/harness-core/37259#-NBkfyg13zLgHtS4MPi4:-NBmp4XW5TatMJMIM_zz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d56fe42698664de258d40a9c1eb8fb67cf769aa4/400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java#L1222)):*
<details><summary><i>Previously, poojaSinghal (Pooja Singhal) wrote…</i></summary><blockquote>

move the error message throw also inside the method. 
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java` line 1226 at r1](https://reviewable.io/reviews/harness/harness-core/37259#-NBkg1eN41xvCBnN2ujW:-NBmp4v44lbzMDjgeV5a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d56fe42698664de258d40a9c1eb8fb67cf769aa4/400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java#L1226)):*
<details><summary><i>Previously, poojaSinghal (Pooja Singhal) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37259)* status: :shipit: complete! ✓

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37259)* status: :shipit: complete! ✓

**Pull request merged**
