### PR TITLE
fix: [PL-27859]: Delegate should also give exception in response

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37427)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* Code issue 5 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37427)

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/test/resources/kryo-registrations.txt` line 1791 at r2](https://reviewable.io/reviews/harness/harness-core/37427#-NCOZZEV70nzjO9wu44Z:-NCOZZEV70nzjO9wu44_:bseh0qe) ([raw file](https://github.com/harness/harness-core/blob/7f681dc8a1751f726826163750064139f2210200/260-delegate/src/test/resources/kryo-registrations.txt#L1791)):*
> ```help
> 73986:io.harness.delegate.beans.DelegateSizeDetails
> 73987:io.harness.delegate.beans.DelegateSize
> 73988:io.harness.delegate.beans.NoInstalledDelegatesException
> ```

these exceptions are not thrown by delegates but by managers, they should not be registered for delegate manager communictaion

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 564 at r2](https://reviewable.io/reviews/harness/harness-core/37427#-NCO_5Nm0dAxwYSiEelE:-NCO_5Nm0dAxwYSiEelF:blwc8v7) ([raw file](https://github.com/harness/harness-core/blob/7f681dc8a1751f726826163750064139f2210200/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L564)):*
> ```Java
>     WingsException ex = null;
>     if (exception instanceof WingsException) {
>       ex = (WingsException) exception;
> ```

why do we need to check and typecast it?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37427)* status: 9 file(s) to review. 0 of 2 approvals obtained.

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37427)* status: 9 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/test/resources/kryo-registrations.txt` line 1791 at r2](https://reviewable.io/reviews/harness/harness-core/37427#-NCOZZEV70nzjO9wu44Z:-NCRO42NETQal8s31GTd:bnasv9a) ([raw file](https://github.com/harness/harness-core/blob/7f681dc8a1751f726826163750064139f2210200/260-delegate/src/test/resources/kryo-registrations.txt#L1791)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

these exceptions are not thrown by delegates but by managers, they should not be registered for delegate manager communictaion
</blockquote></details>

the test is failing - i dont have way out other than registering
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 564 at r2](https://reviewable.io/reviews/harness/harness-core/37427#-NCO_5Nm0dAxwYSiEelE:-NCROHaU--wuJGRGz2bB:b-q30yvg) ([raw file](https://github.com/harness/harness-core/blob/7f681dc8a1751f726826163750064139f2210200/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L564)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need to check and typecast it?
</blockquote></details>

errornotifyresponse build only takes wings exception

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/test/resources/kryo-registrations.txt` line 1791 at r2](https://reviewable.io/reviews/harness/harness-core/37427#-NCOZZEV70nzjO9wu44Z:-NCS5gAW58ifPM8OYveT:b21s0y2) ([raw file](https://github.com/harness/harness-core/blob/7f681dc8a1751f726826163750064139f2210200/260-delegate/src/test/resources/kryo-registrations.txt#L1791)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

the test is failing - i dont have way out other than registering
</blockquote></details>

don't register them in CommonsKryoRegsitrar
move these classes to where they are needed

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37427)* status: 10 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/test/resources/kryo-registrations.txt` line 1791 at r2](https://reviewable.io/reviews/harness/harness-core/37427#-NCOZZEV70nzjO9wu44Z:-NCSES8x3RgELo1D6sOZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7f681dc8a1751f726826163750064139f2210200/260-delegate/src/test/resources/kryo-registrations.txt#L1791)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

don't register them in CommonsKryoRegsitrar
move these classes to where they are needed
</blockquote></details>

Done.

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 2 of 4 files at r3, 6 of 7 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37427)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 2 of 4 files at r3, 6 of 7 files at r4, 2 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37427)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by abhinav-harness** [comment]
trigger codebasehash

**Review by Y0709 — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 6 of 7 files at r4, 1 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37427)* status: :shipit: complete! ✓

**Pull request merged**
