### PR TITLE
feat: [CDS-72892]: Use resource file to fetch static schema

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Describe your changes

Local Env:
schema will be fetched from local resource file
If user wants to make some changes in schema, he will make the changes in harness-schema in local itself, run the bundler and paste the final pipeline.json into resource file
Once done with its changes, he can raise a PR against harness-schema repo and merge changes to quality assurance. Next morning he/she test in preqa which will fetch schema from quality-assurance branch
Preqa Env:
Schema will be fetched from quality-assurance branch of harness-repo
Once develop tests his changes in preqa, either he/she can create a separate PR agains main branch of harness-repo (We can discuss if you want us to automate this if not let developer take care of main branch)
Reason for above for preqa env: We do not want user to run the bundler and merge changes to our harness-core. We want this to be done only during branch
For QA, during branch cut, schema will be fetched from latest commit of main branch of harness-schema and will be stored in our resource of pipeline-service
For all rest env -> schema will be read from resource file only
On clearing the sanity, the same jar is going to all env (stage/prod/on-prem)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49652)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger ut0

**Comment by prashantsharma04** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49652)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 208 at r2](https://reviewable.io/reviews/harness/harness-core/49652#-NYcHgpS5SDDmBgB0-NQ:-NYcHgpS5SDDmBgB0-NR:b-503w9y) ([raw file](https://github.com/harness/harness-core/blob/0fb89af88358f9ca3c940d5834301323fed3b70d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L208)):*
> ```Java
>         String staticYamlRepoUrl = calculateFileURL(EntityType.PIPELINES, "v0");
>         schema = schemaFetcher.fetchStaticYamlSchema(accountIdentifier, staticYamlRepoUrl);
>       }
> ```

even if FF is on we are getting schema twice
___
*[`pipeline-service/service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResourceImpl.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/49652#-NYcHsIFEG5tKszV089h:-NYcHsIFEG5tKszV089i:bcmjtam) ([raw file](https://github.com/harness/harness-core/blob/0fb89af88358f9ca3c940d5834301323fed3b70d/pipeline-service/service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResourceImpl.java#L75)):*
> ```Java
>     try {
>       if ("stress".equals(env)) {
>         String fileURL = pmsYamlSchemaServiceImpl.calculateFileURL(entityType, version);
> ```

why the code is duplicated and reused?

**Comment by prashantsharma04** [comment]
trigger uts

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49652)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 208 at r2](https://reviewable.io/reviews/harness/harness-core/49652#-NYcHgpS5SDDmBgB0-NQ:-NYmFAkfCl3nGpMo1XAh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0fb89af88358f9ca3c940d5834301323fed3b70d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L208)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

even if FF is on we are getting schema twice
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResourceImpl.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/49652#-NYcHsIFEG5tKszV089h:-NYmFC8g-jGGqYp-9JSc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0fb89af88358f9ca3c940d5834301323fed3b70d/pipeline-service/service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResourceImpl.java#L75)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why the code is duplicated and reused?
</blockquote></details>

Done.

**Review by naidu-harness — APPROVED** [review]

**Pull request merged**
