### PR TITLE
[feat]: [PIE-6871]: Add async validation option to old pipeline get API

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42869)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42869)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/42869#-NMDe7D8DF9t0NqMqkI6:-NMDe7D8DF9t0NqMqkI7:b2mcwsf) ([raw file](https://github.com/harness/harness-core/blob/8c63545601b5eae88a153f5cb9450ef906b48de5/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java#L44)):*
> ```Java
>   ValidateTemplateInputsResponseDTO validateTemplateInputsResponse;
>   CacheResponseMetadataDTO cacheResponse;
>   String validationUuid;
> ```

comment to explain what this field do
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 219 at r1](https://reviewable.io/reviews/harness/harness-core/42869#-NMDeK_F6gTBdCzW3EXg:-NMDeK_F6gTBdCzW3EXh:b-3e9662) ([raw file](https://github.com/harness/harness-core/blob/8c63545601b5eae88a153f5cb9450ef906b48de5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L219)):*
> ```Java
>         validationUUID = optionalEvent.get().getUuid();
>       } else {
>         PipelineValidationEvent newEvent =
> ```

can all of this logic be in service layer?



_Code quote:_
```Java
      pipelineEntity = pmsPipelineService.getPipeline(accountId, orgId, projectId, pipelineId, false, false,
          Boolean.TRUE.equals(loadFromFallbackBranch),
          PMSPipelineDtoMapper.parseLoadFromCacheHeaderParam(loadFromCache));
      if (pipelineEntity.isEmpty()) {
        throw new EntityNotFoundException(
            String.format("Pipeline with the given ID: %s does not exist or has been deleted.", pipelineId));
      }
      // if the branch in the request is null, then the branch from where the remote pipeline is taken from is set
      // inside the scm git metadata. Hence, the branch from there is the actual branch we need
      String branchFromScm = GitAwareContextHelper.getBranchInSCMGitMetadata();
      String fqn = PipelineAsyncValidationHelper.buildFQN(pipelineEntity.get(), branchFromScm);
      Optional<PipelineValidationEvent> optionalEvent =
          pipelineAsyncValidationService.getLatestEventByFQNAndAction(fqn, Action.CRUD);
      if (optionalEvent.isPresent()) {
        validationUUID = optionalEvent.get().getUuid();
      } else {
        PipelineValidationEvent newEvent =
            pipelineAsyncValidationService.startEvent(pipelineEntity.get(), branchFromScm, Action.CRUD);
        validationUUID = newEvent.getUuid();
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42869)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/42869#-NMDe7D8DF9t0NqMqkI6:-NMSasBZ-FFbia4mh7uZ:btt8tfc) ([raw file](https://github.com/harness/harness-core/blob/8c63545601b5eae88a153f5cb9450ef906b48de5/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java#L44)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

comment to explain what this field do
</blockquote></details>

this is still left
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 198 at r2](https://reviewable.io/reviews/harness/harness-core/42869#-NMSaxti2gDzb5X0OW_w:-NMSaxti2gDzb5X0OW_x:b-648hoz) ([raw file](https://github.com/harness/harness-core/blob/1c896e180825c28d82b35f24c89f1cde89e8ee81/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L198)):*
> ```Java
>     String validationUUID = null;
>     if (validateAsync) {
>       Pair<Optional<PipelineEntity>, String> pipelineEventPair = pmsPipelineService.getPipelineAndGetAsyncValidationId(
> ```

getPipelineAndAsyncValidationId , remove get duplicate keyword from method
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 130 at r2](https://reviewable.io/reviews/harness/harness-core/42869#-NMSb62c4dKKP3fVPjwk:-NMSb62c4dKKP3fVPjwl:b-23choo) ([raw file](https://github.com/harness/harness-core/blob/1c896e180825c28d82b35f24c89f1cde89e8ee81/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L130)):*
> ```Java
>     PipelineGetResponseBody pipelineGetResponseBody = new PipelineGetResponseBody();
>     // if validateAsync is true, then this ID wil be of the event started for the async validation process, which can be
>     // queried on using another API to get the result of the async validation. If validateAsync is false, then this ID
> ```

will it be null or empty string if false?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/42869#-NMSbDy05uB1-qK0YqBG:-NMSbDy05uB1-qK0YqBH:b-gyrq2i) ([raw file](https://github.com/harness/harness-core/blob/1c896e180825c28d82b35f24c89f1cde89e8ee81/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L89)):*
> ```Java
> 
>   Pair<Optional<PipelineEntity>, String> getPipelineAndGetAsyncValidationId(String accountId, String orgIdentifier,
>       String projectIdentifier, String identifier, boolean deleted, boolean getMetadataOnly,
> ```

where you are taking validateAsync flag true or false in this method?

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42869)* status: 8 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/42869#-NMDe7D8DF9t0NqMqkI6:-NMScTdTDl3dtMggj-6E:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/8c63545601b5eae88a153f5cb9450ef906b48de5/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java#L44)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this is still left
</blockquote></details>

Done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 219 at r1](https://reviewable.io/reviews/harness/harness-core/42869#-NMDeK_F6gTBdCzW3EXg:-NMScWTFAOgdWrbys1ow:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8c63545601b5eae88a153f5cb9450ef906b48de5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L219)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can all of this logic be in service layer?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 198 at r2](https://reviewable.io/reviews/harness/harness-core/42869#-NMSaxti2gDzb5X0OW_w:-NMScVcREaTB0YgQma1W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c896e180825c28d82b35f24c89f1cde89e8ee81/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L198)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

getPipelineAndAsyncValidationId , remove get duplicate keyword from method
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 130 at r2](https://reviewable.io/reviews/harness/harness-core/42869#-NMSb62c4dKKP3fVPjwk:-NMScXuL0BLacz3WgNAZ:b-em8jkp) ([raw file](https://github.com/harness/harness-core/blob/1c896e180825c28d82b35f24c89f1cde89e8ee81/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L130)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

will it be null or empty string if false?
</blockquote></details>

It will be null, added comment for the same
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/42869#-NMSbDy05uB1-qK0YqBG:-NMSc_GY0XVx_JfoHzJj:bpgc99k) ([raw file](https://github.com/harness/harness-core/blob/1c896e180825c28d82b35f24c89f1cde89e8ee81/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L89)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

where you are taking validateAsync flag true or false in this method?
</blockquote></details>

This is only called when async flag is true in API so need need for the flag in service layer

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42869)* status: 8 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/42869#-NMSbDy05uB1-qK0YqBG:-NMSckOO5Qq0R1eseQ7B:bmps4l6) ([raw file](https://github.com/harness/harness-core/blob/1c896e180825c28d82b35f24c89f1cde89e8ee81/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L89)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

This is only called when async flag is true in API so need need for the flag in service layer
</blockquote></details>

no need*

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/42869#-NMSbDy05uB1-qK0YqBG:-NMScWOGAaEukmFg070E:b-cijgy3) ([raw file](https://github.com/harness/harness-core/blob/1c896e180825c28d82b35f24c89f1cde89e8ee81/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L89)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

no need*
</blockquote></details>

Why is the method name so complicated? Can we make it something generic enough and do extra operation just based on some boolean argument like "doAsyncValidation" etc?
Also, lets make java class as return type instead of a Pair<>. Using pair adds constraint here and isn't scalable + doesn't also enforce any contract.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42869)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 198 at r2](https://reviewable.io/reviews/harness/harness-core/42869#-NMSaxti2gDzb5X0OW_w:-NMSdchx0hLYKzMjkSiW:bytxkv8) ([raw file](https://github.com/harness/harness-core/blob/1c896e180825c28d82b35f24c89f1cde89e8ee81/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L198)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

as @mohitg0795 shared, instead a new pojo could be introduced sending both fields as responses rather than pair
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 201 at r3](https://reviewable.io/reviews/harness/harness-core/42869#-NMSdqUe5z9FM4F6DXF2:-NMSdqUe5z9FM4F6DXF3:b5x3go5) ([raw file](https://github.com/harness/harness-core/blob/396d9ed13e2c9bdf7924192ad628a8388ecb74ad/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L201)):*
> ```Java
>     String validationUUID = null;
>     if (validateAsync) {
>       Pair<Optional<PipelineEntity>, String> pipelineEventPair = pmsPipelineService.getPipelineAndAsyncValidationId(
> ```

i think we should use - boolean validateAsync so that old APIs cant turn on or off based on the flag



_Code quote:_
```Java
boolean validateAsync
```

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 198 at r2](https://reviewable.io/reviews/harness/harness-core/42869#-NMSdtDwBTgESd-ybUea:-NMSdtDwBTgESd-ybUeb:b-tyohd2) ([raw file](https://github.com/harness/harness-core/blob/1c896e180825c28d82b35f24c89f1cde89e8ee81/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L198)):*
> ```Java
>     String validationUUID = null;
>     if (validateAsync) {
>       Pair<Optional<PipelineEntity>, String> pipelineEventPair = pmsPipelineService.getPipelineAndGetAsyncValidationId(
> ```

why is this if else in resource layer? Can't we have a service layer method which handles everything and returns proper response?

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42869)* status: 10 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 198 at r2](https://reviewable.io/reviews/harness/harness-core/42869#-NMSdtDwBTgESd-ybUea:-NMTTPEO5_CLeqoe9oYh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c896e180825c28d82b35f24c89f1cde89e8ee81/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L198)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is this if else in resource layer? Can't we have a service layer method which handles everything and returns proper response?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 201 at r3](https://reviewable.io/reviews/harness/harness-core/42869#-NMSdqUe5z9FM4F6DXF2:-NMTTOuz8h_frorYXk9E:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/396d9ed13e2c9bdf7924192ad628a8388ecb74ad/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L201)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i think we should use - boolean validateAsync so that old APIs cant turn on or off based on the flag
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/42869#-NMSbDy05uB1-qK0YqBG:-NMTTQ6K9QEV5Eph_xPE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c896e180825c28d82b35f24c89f1cde89e8ee81/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L89)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why is the method name so complicated? Can we make it something generic enough and do extra operation just based on some boolean argument like "doAsyncValidation" etc?
Also, lets make java class as return type instead of a Pair<>. Using pair adds constraint here and isn't scalable + doesn't also enforce any contract.
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 201 at r6](https://reviewable.io/reviews/harness/harness-core/42869#-NMT_eYUEUj6Aw7_2HAV:-NMT_eYUEUj6Aw7_2HAW:bomzm08) ([raw file](https://github.com/harness/harness-core/blob/c6cbd614cff6447066b437da099986a8dadcbb31/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L201)):*
> ```Java
>     String validationUUID;
>     try {
>       PipelineGetResult pipelineEventPair = pmsPipelineService.getAndValidatePipeline(accountId, orgId, projectId,
> ```

typo in name of the variable, missed to change after changing its type

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 134 at r6](https://reviewable.io/reviews/harness/harness-core/42869#-NMTek0nEhbiZXVQaKTn:-NMTek0nEhbiZXVQaKTo:bayuqqi) ([raw file](https://github.com/harness/harness-core/blob/c6cbd614cff6447066b437da099986a8dadcbb31/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L134)):*
> ```Java
>     String validationUUID;
>     try {
>       PipelineGetResult pipelineEventPair = pmsPipelineService.getAndValidatePipeline(account, org, project, pipeline,
> ```

variable name typo

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineGetResult.java` line 26 at r6](https://reviewable.io/reviews/harness/harness-core/42869#-NMTf5zfAIIw0zJyrtmW:-NMTf5zfAIIw0zJyrtmX:b-owyfzy) ([raw file](https://github.com/harness/harness-core/blob/c6cbd614cff6447066b437da099986a8dadcbb31/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineGetResult.java#L26)):*
> ```Java
>   // this ID wil be of the async validation event started for the async validation process, which can be
>   // queried on using another API to get the result of the async validation.
>   String asyncValidationUUID;
> ```

nit: Any specific reason to use UUID in the name? Just saying as it just goes different from our usual convention of using "id" as suffix for such things. If "id" is good enough, then I would suggest to keep on using it like "asynValidationId" just to keep things simple.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 92 at r6](https://reviewable.io/reviews/harness/harness-core/42869#-NMTfWLm5DlSufIOYV35:-NMTfeZBBgJsxi9kASxx:b-vawmy8) ([raw file](https://github.com/harness/harness-core/blob/c6cbd614cff6447066b437da099986a8dadcbb31/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L92)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This method name is not changed?
</blockquote></details>

I see that its used internally in getAndValidatePipeline method. Why is it public if its meant to be used internally?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 277 at r6](https://reviewable.io/reviews/harness/harness-core/42869#-NMTfpii4qLNR3vneIkh:-NMTfpii4qLNR3vneIki:bxzyy5y) ([raw file](https://github.com/harness/harness-core/blob/c6cbd614cff6447066b437da099986a8dadcbb31/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L277)):*
> ```Java
>     String validationUUID = null;
>     if (validateAsync) {
>       PipelineGetResult pipelineEventPair = getPipelineAndAsyncValidationId(
> ```

A better name could be "getAndValidatePipelineAsync", going on lines with our existing method "getAndValidatePipeline". Also, do we really need 2 methods? I think we should just mutate existing "getAndValidatePipeline" method to work according to new incoming argument. Issue with having 2 methods is that now if there's a common change, we are bringing in more branches of impact that it may bring in to + more refactoring scope in such case.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 378 at r6](https://reviewable.io/reviews/harness/harness-core/42869#-NMTgzSp0Fc08U3u8jw2:-NMTgzSp0Fc08U3u8jw3:by44qoj) ([raw file](https://github.com/harness/harness-core/blob/c6cbd614cff6447066b437da099986a8dadcbb31/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L378)):*
> ```Java
>     } else {
>       PipelineValidationEvent newEvent =
>           pipelineAsyncValidationService.startEvent(pipelineEntity.get(), branchFromScm, Action.CRUD);
> ```

If we fail to register event, then we fail the GET API as well?

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42869)* status: 10 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 201 at r6](https://reviewable.io/reviews/harness/harness-core/42869#-NMT_eYUEUj6Aw7_2HAV:-NMWwEA2CwYqA5iQIyj9:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c6cbd614cff6447066b437da099986a8dadcbb31/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L201)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

typo in name of the variable, missed to change after changing its type
</blockquote></details>

Done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 134 at r6](https://reviewable.io/reviews/harness/harness-core/42869#-NMTek0nEhbiZXVQaKTn:-NMWwFJn8mIT_RjFoZum:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c6cbd614cff6447066b437da099986a8dadcbb31/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L134)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

variable name typo
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineGetResult.java` line 26 at r6](https://reviewable.io/reviews/harness/harness-core/42869#-NMTf5zfAIIw0zJyrtmW:-NMWwFpX2y2tXzAnI8SU:b-blk7g2) ([raw file](https://github.com/harness/harness-core/blob/c6cbd614cff6447066b437da099986a8dadcbb31/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineGetResult.java#L26)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

nit: Any specific reason to use UUID in the name? Just saying as it just goes different from our usual convention of using "id" as suffix for such things. If "id" is good enough, then I would suggest to keep on using it like "asynValidationId" just to keep things simple.
</blockquote></details>

In general I've seen that if any entity has a UUID that a user can give (for eg pipelines input sets connectors etc) then we call it identifier or id, and otherwise if the UUID is given by harness (preflight events, this validation event) we call it just UUID
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 92 at r6](https://reviewable.io/reviews/harness/harness-core/42869#-NMTfWLm5DlSufIOYV35:-NMWwULa-UQxGZbhrhRM:b-eogckj) ([raw file](https://github.com/harness/harness-core/blob/c6cbd614cff6447066b437da099986a8dadcbb31/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L92)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I see that its used internally in getAndValidatePipeline method. Why is it public if its meant to be used internally?
</blockquote></details>

Made it internal. Idea is that this method will eventually be the one used cuz sync validation will go away, but yeah till then we can make this method private

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42869)* status: 10 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 277 at r6](https://reviewable.io/reviews/harness/harness-core/42869#-NMTfpii4qLNR3vneIkh:-NMWwynb-ilKhrDEPPyq:bapsmis) ([raw file](https://github.com/harness/harness-core/blob/c6cbd614cff6447066b437da099986a8dadcbb31/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L277)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

A better name could be "getAndValidatePipelineAsync", going on lines with our existing method "getAndValidatePipeline". Also, do we really need 2 methods? I think we should just mutate existing "getAndValidatePipeline" method to work according to new incoming argument. Issue with having 2 methods is that now if there's a common change, we are bringing in more branches of impact that it may bring in to + more refactoring scope in such case.
</blockquote></details>

The async word at the end is kinda ambiguous, like is the get async or the validation async or both? And anyway this method just gets the validation uuid, so putting this info in the method name makes sense to me
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 378 at r6](https://reviewable.io/reviews/harness/harness-core/42869#-NMTgzSp0Fc08U3u8jw2:-NMWx9VwCoohNswvTcik:b-rlckks) ([raw file](https://github.com/harness/harness-core/blob/c6cbd614cff6447066b437da099986a8dadcbb31/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L378)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

If we fail to register event, then we fail the GET API as well? 
</blockquote></details>

I think we should yes.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 6 files at r2, 2 of 6 files at r5, 1 of 1 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42869)* status: 10 file(s) to review. 6. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 201 at r3](https://reviewable.io/reviews/harness/harness-core/42869#-NMSdqUe5z9FM4F6DXF2:-NMSpeEk5MpkuPR1oTIy:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/396d9ed13e2c9bdf7924192ad628a8388ecb74ad/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L201)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

done

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 378 at r6](https://reviewable.io/reviews/harness/harness-core/42869#-NMTgzSp0Fc08U3u8jw2:-NMY7XlG0v7xMk_ODSjj:b-459ugv) ([raw file](https://github.com/harness/harness-core/blob/c6cbd614cff6447066b437da099986a8dadcbb31/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L378)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

I think we should yes. 
</blockquote></details>

I wonder something thats async should affect the response or not. Could you please confirm this once within the team and product if this is the final decision. Its critical thus just want to make it right in first go.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42869)* status: 10 file(s) to review. 6. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 378 at r6](https://reviewable.io/reviews/harness/harness-core/42869#-NMTgzSp0Fc08U3u8jw2:-NMYAtA00XSJQNSSiXAq:bpow3o3) ([raw file](https://github.com/harness/harness-core/blob/c6cbd614cff6447066b437da099986a8dadcbb31/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L378)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I wonder something thats async should affect the response or not. Could you please confirm this once within the team and product if this is the final decision. Its critical thus just want to make it right in first go.
</blockquote></details>

Product decision will be taken here: https://harness.slack.com/archives/C04AHCMNG7L/p1674553797513239

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 6 files at r2, 1 of 6 files at r3, 2 of 6 files at r5, 1 of 1 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42869)* status: :shipit: complete! ✓

**Pull request merged**
