### PR TITLE
[feat]: [CDS-43737]: azure sdk 890

### PR DESCRIPTION
**Pull request by markoharness**
## Describe your changes
Migrating leftover Azure code in from old Azure SDK libs to new SDK libs. 
Removing old azure libs.
Updating unit tests.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40682)

### CODE REVIEW

**Comment by markoharness** [comment]
trigger checkstylecodeformat, ft1, ft2, messagecheck, pmd, codebasehash, ti0, ti1, ti2, ti3, ti4

**Comment by markoharness** [comment]
trigger checkpermission

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 29 of 35 files at r1, 10 of 10 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40682)* status: 41 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`890-sm-core/src/test/java/resources/BUILD.bazel` line 2 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIGz4lu-mgs6z2JCyWC:-NIGz4lw4xNRX-r4SdpX:b-d20jzn) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/890-sm-core/src/test/java/resources/BUILD.bazel#L2)):*
> ```Starlark
> package(default_visibility = ["//visibility:public"])
> ```

Why do we need this file, because of mock-marker-inline, right?
___
*[`890-sm-delegate/src/main/java/io/harness/delegatetasks/NGAzureKeyVaultFetchEngineTask.java` line 89 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIH5nsVAFo8QDjcnaeD:-NIH5nsVAFo8QDjcnaeE:bejvl0m) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/890-sm-delegate/src/main/java/io/harness/delegatetasks/NGAzureKeyVaultFetchEngineTask.java#L89)):*
> ```Java
>     AzureResourceManager azureResourceManager;
>     List<Vault> vaultList = new ArrayList<>();
>     TokenCredential credentials =
> ```

Minor - get azureResourceManager including the token and authenticated logic should be moved in a separate method if the method doesn't require more arguments than 3. 
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 179 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIH56nm6CgK1gpNOlv_:-NIH56nm6CgK1gpNOlva:b8ickw4) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L179)):*
> ```Java
>     Response<KeyVaultSecret> response = azureVaultSecretsClient.setSecretWithResponse(keyVaultSecret, Context.NONE);
>     if (response.getStatusCode() < 200 || response.getStatusCode() >= 300) {
>       throw new Exception(
> ```

Can we use more specific exception here like AzureKeyVaultException or...?
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 222 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIH58ve6rEliD1LHrBV:-NIH58ve6rEliD1LHrBW:bc2dbyc) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L222)):*
> ```Java
>       // system as well as UI needs to be updated to support async reactive nature of this call.
>       SyncPoller<DeletedSecret, Void> syncPoller = keyVaultClient.beginDeleteSecret(existingRecord.getName());
>       syncPoller.setPollInterval(Duration.ofSeconds(1));
> ```

Is there a way that Azure takes from the response header when to make the next poll request? It could be overwhelming to poll on each second. 
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 323 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIH4ddd-ax84g1k4Y_p:-NIH4dde9ubb_LCw7Ezg:b8ickw4) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L323)):*
> ```Java
>           parsedSecretReference.getSecretName(), parsedSecretReference.getSecretVersion(), Context.NONE);
>       if (response.getStatusCode() < 200 || response.getStatusCode() >= 300) {
>         throw new Exception(
> ```

Can we use more specific exception here like AzureKeyVaultException or...?
___
*[`930-delegate-tasks/BUILD.bazel` line 54 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIGzhyx4KQWhycQX5Lr:-NIGzhyx4KQWhycQX5Ls:bqx7000) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/930-delegate-tasks/BUILD.bazel#L54)):*
> ```Starlark
>         "@maven//:com_amazonaws_aws_java_sdk_secretsmanager",
>         "@maven//:com_amazonaws_aws_java_sdk_servicediscovery",
>         "@maven//:com_azure_azure_security_keyvault_administration",
> ```

The question, we are getting vault SecretClient from com_azure_azure_security_keyvault_administration and that is the purpose of this module, right? 
What is the version of this module, is it aligned with the new SDK?  
___
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIH-nmu54bcT6nKIniq:-NIH-nmu54bcT6nKInir:b-scxja8) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L66)):*
> ```Java
>   }
> 
>   protected HttpPipeline getAzureHttpPipeline(
> ```

Where are we using this method?
___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 314 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIH0zXCCdJOy2myNcpY:-NIH0zXCCdJOy2myNcpZ:b-mo5s5o) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L314)):*
> ```Java
>   }
> 
>   public FixedDelayOptions getDelayOptions(int maxRetries, Duration delay) {
> ```

Minor - I think this should be getFixeDelayOptions instead of getDelayOptions and I guess that Azure supports more delay options. 
___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 318 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIH2W6iEzBuftJ8xl9M:-NIH2W6iEzBuftJ8xl9N:bftcnqn) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L318)):*
> ```Java
>   }
> 
>   public RetryOptions getRetryOptions(FixedDelayOptions delayOptions) {
> ```

Can we make this method more general to different options if not remove it and move new RetryOptions(delayOptions) to above method.

**Comment by markoharness** [comment]
*[`890-sm-core/src/test/java/resources/BUILD.bazel` line 2 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIGz4lu-mgs6z2JCyWC:-NIHEF5M49H-u_anPo6I:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/890-sm-core/src/test/java/resources/BUILD.bazel#L2)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Why do we need this file, because of mock-marker-inline, right?
</blockquote></details>

Yes

**Comment by markoharness** [comment]
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 222 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIH58ve6rEliD1LHrBV:-NIHEWgYBo7tc46obF5g:byrtr78) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L222)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Is there a way that Azure takes from the response header when to make the next poll request? It could be overwhelming to poll on each second. 
</blockquote></details>

Default polling interval is 1 second. So this line is redundant. I can remove it.

**Comment by markoharness** [comment]
*[`930-delegate-tasks/BUILD.bazel` line 54 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIGzhyx4KQWhycQX5Lr:-NIHEgEQCQZUOS2StesB:b2wzuzt) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/930-delegate-tasks/BUILD.bazel#L54)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The question, we are getting vault SecretClient from com_azure_azure_security_keyvault_administration and that is the purpose of this module, right? 
What is the version of this module, is it aligned with the new SDK?  
</blockquote></details>

No. We are getting KeyVaultError and KeyVaultErrorException models from com_azure_azure_security_keyvault_administration
version of this lib is 4.1.2 which is aligned with version 4.4.1 of  com_azure_azure_security_keyvault_keys and com_azure_azure_security_keyvault_secrets

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIH-nmu54bcT6nKIniq:-NIHFMpf68CPihaqO-nj:b5eyx6e) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L66)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Where are we using this method?
</blockquote></details>

In
io.harness.azure.impl.AzureAutoScaleSettingsClientImpl
io.harness.azure.impl.AzureComputeClientImpl
io.harness.azure.impl.AzureManagementClientImpl
io.harness.azure.impl.AzureWebClientImpl

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 314 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIH0zXCCdJOy2myNcpY:-NIHGGOj2sagH9Tvc78V:b-7s9zut) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L314)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - I think this should be getFixeDelayOptions instead of getDelayOptions and I guess that Azure supports more delay options. 
</blockquote></details>

I will rename it

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 318 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIH2W6iEzBuftJ8xl9M:-NIHGJSsA_-iTBdT33wJ:by0bly5) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L318)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can we make this method more general to different options if not remove it and move new RetryOptions(delayOptions) to above method.
</blockquote></details>

Not sure how to move it as it depends on the delayOptions object.
I could move the getDelayOptions/getFixedDelayOptions into getRetryOptions method?

**Comment by markoharness** [comment]
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 323 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIH4ddd-ax84g1k4Y_p:-NIHH_L13tdzFsJSPPKO:bwz90o3) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L323)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can we use more specific exception here like AzureKeyVaultException or...?
</blockquote></details>

I will change to AzureKeyVaultOperationException



_Code quote:_
```Java
        throw new Exception(
```

**Comment by markoharness** [comment]
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 179 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIH56nm6CgK1gpNOlv_:-NIHHc4YDUUHP3aG74Kb:bwxewxx) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L179)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can we use more specific exception here like AzureKeyVaultException or...?
</blockquote></details>

AzureKeyVaultOperationException

**Comment by markoharness** [comment]
*[`890-sm-delegate/src/main/java/io/harness/delegatetasks/NGAzureKeyVaultFetchEngineTask.java` line 89 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIH5nsVAFo8QDjcnaeD:-NIHIzBD5rPZcL0oy6bj:b-uarwc0) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/890-sm-delegate/src/main/java/io/harness/delegatetasks/NGAzureKeyVaultFetchEngineTask.java#L89)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - get azureResourceManager including the token and authenticated logic should be moved in a separate method if the method doesn't require more arguments than 3. 
</blockquote></details>

TokenCredentials is already in a separate method.
I will move the authenticated logic into separate method.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40682#-:-NIHcVsD3M8HYXZTy0VF:bnfp4nl)* status: 41 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 311 at r1](https://reviewable.io/reviews/harness/harness-core/40682#-NIHbVPV-ifqR3ELsaf9:-NIHbVPV-ifqR3ELsafA:b-zej1ky) ([raw file](https://github.com/harness/harness-core/blob/d3efda9fd31e0198aba467affbae743125567384/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L311)):*
> ```Java
> 
>   public FixedDelayOptions getDefaultDelayOptions() {
>     return getDelayOptions(0, Duration.ofSeconds(1));
> ```

I think FixedDelay retry strategy doesn't help a lot, if Azure natively supports exponential backoff or jitter it will be nice, if not let's go with the current solution.
___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 318 at r3](https://reviewable.io/reviews/harness/harness-core/40682#-NIH2W6iEzBuftJ8xl9M:-NIHc9gE29aaA-mwALOy:b8hht60) ([raw file](https://github.com/harness/harness-core/blob/50757eab47ffdf95a1c458244f09265491222e43/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L318)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

Not sure how to move it as it depends on the delayOptions object.
I could move the getDelayOptions/getFixedDelayOptions into getRetryOptions method?
</blockquote></details>

I mean here we have to support more retry options, more retry strategies.

**Review by mdmilic — APPROVED** [review]
Approve delegate CODEOWNED chagnes

> Reviewed 5 of 35 files at r1, 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40682#-:-NIHkygE-I6ZdbhUWdSv:bgh2ojq)* status: 35 file(s) to review. Waiting on team(s): sto.

**Review by williamwissemann — APPROVED** [review]
> Reviewed 27 of 35 files at r1, 8 of 10 files at r2, 2 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40682)* status: Waiting on team(s): sto.

**Review by jsentongo — APPROVED** [review]

**Pull request merged**
