### PR TITLE
feat: [CHAOS-941]: Adding Chaos Admin as a Managed Role

### PR DESCRIPTION
**Pull request by S-ayanide**
## Describe your changes

Adding Chaos Admin with all chaos roles as well as Environment and Environment Groups roles
Permissions given:
```
        - chaos_chaoshub_view
        - chaos_chaoshub_edit
        - chaos_chaoshub_delete
        - chaos_chaosinfrastructure_view
        - chaos_chaosinfrastructure_edit
        - chaos_chaosinfrastructure_delete
        - chaos_chaosexperiment_view
        - chaos_chaosexperiment_edit
        - chaos_chaosexperiment_delete
        - chaos_chaosgameday_view
        - chaos_chaosgameday_edit
        - chaos_chaosgameday_delete
        - core_environment_view
        - core_environment_edit
        - core_environment_delete
        - core_environment_access
        - core_environmentgroup_view
        - core_environmentgroup_edit
        - core_environmentgroup_delete
        - core_environmentgroup_access
```

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41780)

### CODE REVIEW

**Review by imrajdas — CHANGES_REQUESTED** [review]

**Review by imrajdas — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41780)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by imrajdas — APPROVED** [review]

**Review by reetika04 — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41780)* status: Some of the checks are too old.

**Review by imrajdas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41780)* status: Some of the checks are too old.

**Review by S-ayanide — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41780)* status: Some of the checks are too old.

**Review by imrajdas — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41780#-:-NLVIKW57LZJw5c3SLjU:bnfp4nl)* status: Some of the checks are too old.

**Review by imrajdas — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41780)* status: :shipit: complete! ✓

**Review by reetika04 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41780)* status: :shipit: complete! ✓

**Pull request merged**
