### PR TITLE
[fix]: [PL-28549]: added 2FA QR code for NG user invite email template

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
added 2FA QR code for NG user invite email template

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38604)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger messagecheck

**Comment by kapil-harness** [comment]
trigger messagecheck

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38604#-:-NE4-_DFCzs_ymdkhKa0:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by rijajoo — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38604)* status: 1 file(s) to review.

**Comment by kapil-harness** [comment]
trigger messagecheck

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38604)* status: 1 file(s) to review. 1 change requests. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/38604#-NE4bhDV025o_fVAL0G4:-NE4bhDV025o_fVAL0G5:b-jy5pze) (no related file):*
Increment the build no.

___

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38604)* status: :shipit: complete! ✓

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38604)* status: 1 change requests. 1. unresolved discussions. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/38604#-NE4bhDV025o_fVAL0G4:-NE4d3PP-VW7Ijzvn8Qm:b-896fix) (no related file):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Increment the build no.
</blockquote></details>

Done.

___

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38604#-:-NE4hsiV5JJsRG1p1oLW:bnfp4nl)* status: 1 file(s) to review.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38604)* status: :shipit: complete! ✓

**Pull request merged**
