### PR TITLE
feat: [PIE-7565]: Update the NodeStatus in Async Executable by the step

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Updating async node execution status
Changes in this PR:

1. Providing **capability for async steps to give sdk the status** if one have to change status of their node.

**Usecase**: In free plan, if one wants to show a different status other than queue as pipeline is actually not started, the step can send the status QUEUED_LICENSE_LIMIT_REACHED, which will get update to the node as well as status of pipeline

**Testing**: made some mock wait step, which was sending some status and checked the correct status which was getting updated as step along with whole pipeline

2. While waiting for Async call, if a **step wants to concurrent update some status**, it can do it using progress data. We have created a new Progress Data as AsyncProgressData which contains status.

Handler response will check for async request and will update the node status similar to that of passed in AsyncProgressData

**Testing**: did testing on wait step. Created an api to hit progress call using correlation id of wait step

3. Earlier **wait step and approval step, were changing the status of whole pipeline from their end** on completion. That logic have been shifted to PlanNodeExecutionStrategy.resumeNodeExecution

**Testing**: ran multiple of pipelines which consists of wait steps/stages and approval in parallels and in serial. Did manual approve along with automatic approval in case of wait step and failure in case of approval stage

Screenshot 2023-01-27 at 5 27 31 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42817)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42817)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java` line 200 at r3](https://reviewable.io/reviews/harness/harness-core/42817#-NMSRuCb68uuqlkkoFM_:-NMSRuCb68uuqlkkoFMa:b-606fjv) ([raw file](https://github.com/harness/harness-core/blob/b6697e3078a2e8ce0346cfa4617b19a167caacfd/884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java#L200)):*
> ```Java
>         return EnumSet.of(EXPIRED, FAILED, INTERVENTION_WAITING, RUNNING, APPROVAL_REJECTED, QUEUED);
>       case QUEUED_LICENSE_LIMIT_REACHED:
>         return EnumSet.of(QUEUED);
> ```

i think both queued and Async waiting can be moved to limit reached queued isn't?
___
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java` line 283 at r3](https://reviewable.io/reviews/harness/harness-core/42817#-NMSRvPU2QLyfTyB9vzG:-NMSRvPU2QLyfTyB9vzH:biwvk0h) ([raw file](https://github.com/harness/harness-core/blob/b6697e3078a2e8ce0346cfa4617b19a167caacfd/884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java#L283)):*
> ```Java
>       return PAUSED;
>     } else if (statuses.stream().anyMatch(status -> status == QUEUED_LICENSE_LIMIT_REACHED)) {
>       return QUEUED;
> ```

final status is QUEUED_LICENSE_LIMIT_REACHED only
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/SdkNodeExecutionServiceImpl.java` line 69 at r3](https://reviewable.io/reviews/harness/harness-core/42817#-NMSS06r4HFvs84_Vr8-:-NMSS06r4HFvs84_Vr80:b-ejisdq) ([raw file](https://github.com/harness/harness-core/blob/b6697e3078a2e8ce0346cfa4617b19a167caacfd/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/SdkNodeExecutionServiceImpl.java#L69)):*
> ```Java
> 
>     SdkResponseEventProto sdkResponseEvent = SdkResponseEventProto.newBuilder()
>                                                  .setStatus(executableResponse.getStatus())
> ```

you can add comment here that we will if customer sends custom status, you should also check status if not null/empty
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/AddExecutableResponseRequestProcessor.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/42817#-NMSTM9M9M2AdSzTCBAW:-NMSTM9M9M2AdSzTCBAX:bn9qszw) ([raw file](https://github.com/harness/harness-core/blob/b6697e3078a2e8ce0346cfa4617b19a167caacfd/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/AddExecutableResponseRequestProcessor.java#L34)):*
> ```Java
>     AddExecutableResponseRequest request = event.getAddExecutableResponseRequest();
>     if(event.getStatus()!=null) {
>       nodeExecutionService.updateStatusWithOps(SdkResponseEventUtils.getNodeExecutionId(event), event.getStatus(),
> ```

can you add comment that as overrideStatus is empty, it will take from nodeAllowedStatuses, thus transition to QueuedLimit Reached status will be not having race condition as mongo is acting as central service to handle it, even if async task resume fast and is processed first, thus status update will fail
___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/execution/executable_response.proto` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/42817#-NMSTxYN1ZE8tLE8fE4Z:-NMSTxYN1ZE8tLE8fE4_:b-dsgdc0) ([raw file](https://github.com/harness/harness-core/blob/b6697e3078a2e8ce0346cfa4617b19a167caacfd/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/execution/executable_response.proto#L26)):*
> ```protobuf
>     SkipTaskExecutableResponse skipTask = 8;
>   }
>   Status status=9;
> ```

can you add comment here what this status means
___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/execution/events/sdk_response_event.proto` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/42817#-NMSU41v9KHcpgypYGmQ:-NMSU41v9KHcpgypYGmR:bvhwe8m) ([raw file](https://github.com/harness/harness-core/blob/b6697e3078a2e8ce0346cfa4617b19a167caacfd/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/execution/events/sdk_response_event.proto#L40)):*
> ```protobuf
>   }
>   io.harness.pms.contracts.ambiance.Ambiance ambiance = 18;
>  Status status = 19;
> ```

why its needed t both places?

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r5, 17 of 21 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42817)* status: 32 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java` line 200 at r3](https://reviewable.io/reviews/harness/harness-core/42817#-NMSRuCb68uuqlkkoFM_:-NN0eKvT-yf9UDVK-7in:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b6697e3078a2e8ce0346cfa4617b19a167caacfd/884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java#L200)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i think both queued and Async waiting can be moved to limit reached queued isn't?
</blockquote></details>

done
___
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java` line 283 at r3](https://reviewable.io/reviews/harness/harness-core/42817#-NMSRvPU2QLyfTyB9vzG:-NN0eM5LBZ7Tt50h0pBM:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b6697e3078a2e8ce0346cfa4617b19a167caacfd/884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java#L283)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

final status is QUEUED_LICENSE_LIMIT_REACHED only
</blockquote></details>

done
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/SdkNodeExecutionServiceImpl.java` line 69 at r3](https://reviewable.io/reviews/harness/harness-core/42817#-NMSS06r4HFvs84_Vr8-:-NN0h5Q730BJc7ECbCi3:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b6697e3078a2e8ce0346cfa4617b19a167caacfd/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/SdkNodeExecutionServiceImpl.java#L69)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

you can add comment here that we will if customer sends custom status, you should also check status if not null/empty
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/statusupdate/QueuedLicenseLimitReachedStatusUpdate.java` line 32 at r7](https://reviewable.io/reviews/harness/harness-core/42817#-NN0hPchBkLGnH-x1LIS:-NN0hPckD8FaHZb7gaxt:b-ij8q08) ([raw file](https://github.com/harness/harness-core/blob/bc4ae284f8113a7598215a58a887eeb84471f3b6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/statusupdate/QueuedLicenseLimitReachedStatusUpdate.java#L32)):*
> ```Java
>       planExecutionService.updateStatus(nodeStatusUpdateInfo.getNodeExecution().getAmbiance().getStageExecutionId(),
>           Status.QUEUED_LICENSE_LIMIT_REACHED);
>     }
> ```

what we are trying to achieve
i think this should be deleted



_Code quote:_
```Java
    // update stage status of queued step
    if (nodeStatusUpdateInfo.getNodeExecution().getAmbiance().getStageExecutionId() != null) {
      planExecutionService.updateStatus(nodeStatusUpdateInfo.getNodeExecution().getAmbiance().getStageExecutionId(),
          Status.QUEUED_LICENSE_LIMIT_REACHED);
    }
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java` line 219 at r7](https://reviewable.io/reviews/harness/harness-core/42817#-NN0lzldEgoL35rhxKZy:-NN0lzle7emgYYxj3oqZ:b-ag6tfh) ([raw file](https://github.com/harness/harness-core/blob/bc4ae284f8113a7598215a58a887eeb84471f3b6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java#L219)):*
> ```Java
>         nodeExecution = Preconditions.checkNotNull(
>             nodeExecutionService.updateStatusWithOps(nodeExecutionId, RUNNING, null, EnumSet.noneOf(Status.class)));
>         Status planStatus =
> ```

comments to add
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/HandleProgressRequestProcessor.java` line 44 at r7](https://reviewable.io/reviews/harness/harness-core/42817#-NN0mQf3B0A64YpH2EIH:-NN0mQf46sNTeYckF5_y:b-3pwonm) ([raw file](https://github.com/harness/harness-core/blob/bc4ae284f8113a7598215a58a887eeb84471f3b6/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/HandleProgressRequestProcessor.java#L44)):*
> ```Java
>       NodeExecution nodeExecution = nodeExecutionService.updateStatusWithOps(
>           SdkResponseEventUtils.getNodeExecutionId(event), progressRequest.getStatus(),
>           ops -> setUnset(ops, NodeExecutionKeys.progressData, progressDoc), EnumSet.noneOf(Status.class));
> ```

comments to add why we are doing
___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/execution/executable_response.proto` line 38 at r7](https://reviewable.io/reviews/harness/harness-core/42817#-NN0mbssBv326pxRkgVw:-NN0mbssBv326pxRkgVx:baf1rkd) ([raw file](https://github.com/harness/harness-core/blob/bc4ae284f8113a7598215a58a887eeb84471f3b6/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/execution/executable_response.proto#L38)):*
> ```protobuf
>   repeated string units = 3;
>   int32 timeout = 5;
>   Status status = 9;
> ```

dd what this status is going to be used for
___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/execution/events/sdk_response_event.proto` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/42817#-NMSU41v9KHcpgypYGmQ:-NN0k4GY0ChEHGb8uJB7:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b6697e3078a2e8ce0346cfa4617b19a167caacfd/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/execution/events/sdk_response_event.proto#L40)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why its needed t both places?
</blockquote></details>

done

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42817)* status: 32 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/statusupdate/QueuedLicenseLimitReachedStatusUpdate.java` line 32 at r7](https://reviewable.io/reviews/harness/harness-core/42817#-NN0hPchBkLGnH-x1LIS:-NN0q-z17VoAShCMPvcQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bc4ae284f8113a7598215a58a887eeb84471f3b6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/statusupdate/QueuedLicenseLimitReachedStatusUpdate.java#L32)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what we are trying to achieve
i think this should be deleted
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java` line 219 at r7](https://reviewable.io/reviews/harness/harness-core/42817#-NN0lzldEgoL35rhxKZy:-NN0q1t6C39d7_nif7-N:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bc4ae284f8113a7598215a58a887eeb84471f3b6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java#L219)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

comments to add
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/AddExecutableResponseRequestProcessor.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/42817#-NMSTM9M9M2AdSzTCBAW:-NN0q4hA4E3JMiGSFx-P:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b6697e3078a2e8ce0346cfa4617b19a167caacfd/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/AddExecutableResponseRequestProcessor.java#L34)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you add comment that as overrideStatus is empty, it will take from nodeAllowedStatuses, thus transition to QueuedLimit Reached status will be not having race condition as mongo is acting as central service to handle it, even if async task resume fast and is processed first, thus status update will fail
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 21 files at r6, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42817)* status: 32 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/HandleProgressRequestProcessor.java` line 44 at r7](https://reviewable.io/reviews/harness/harness-core/42817#-NN0mQf3B0A64YpH2EIH:-NN1lKHp2DXZReUR9OiI:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bc4ae284f8113a7598215a58a887eeb84471f3b6/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/HandleProgressRequestProcessor.java#L44)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

comments to add why we are doing
</blockquote></details>

done
___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/execution/executable_response.proto` line 38 at r7](https://reviewable.io/reviews/harness/harness-core/42817#-NN0mbssBv326pxRkgVw:-NN1lLDHDjal8RXlBd6u:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bc4ae284f8113a7598215a58a887eeb84471f3b6/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/execution/executable_response.proto#L38)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dd what this status is going to be used for
</blockquote></details>

done

**Review by hextechpal — APPROVED** [review]
> Reviewed 7 of 13 files at r5, 19 of 21 files at r6, 1 of 1 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42817)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42817)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 7 of 13 files at r5, 19 of 21 files at r6, 1 of 1 files at r7, 4 of 5 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42817)* status: :shipit: complete! ✓

**Pull request merged**
