### PR TITLE
[feat]: [CDS-46820]: populate yaml for envV2 when used in envV1 supported pipelines

### PR DESCRIPTION
**Pull request by tchaurasiya**
…rted pipelines

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40374)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfraStepUtils.java` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/40374#-NHAA0Qb0GAFzw5LCDC7:-NHAA0Qb0GAFzw5LCDC8:b-whekuk) ([raw file](https://github.com/harness/harness-core/blob/12f3336402f8648a1543be709d1bb514cf43566f/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfraStepUtils.java#L116)):*
> ```Java
>     YamlNode yamlNode = yamlField.getNode();
>     if (yamlNode != null && yamlNode.isObject()) {
>       ObjectNode objectNode = (ObjectNode) yamlNode.getCurrJsonNode().get("environment");
> ```

we should also check if yamlNode.getcurrentJsonNode().get("environment") is an object node to avoid class cast

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfraStepUtils.java` line 121 at r2](https://reviewable.io/reviews/harness/harness-core/40374#-NHAB0YuC4K0NQ33ENKz:-NHAB0YuC4K0NQ33ENL-:b-yrni94) ([raw file](https://github.com/harness/harness-core/blob/12f3336402f8648a1543be709d1bb514cf43566f/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfraStepUtils.java#L121)):*
> ```Java
>         objectNode.replace(EnvironmentKeys.type, JsonPipelineUtils.asTree(environmentYaml.getType()));
>         objectNode.replace(EnvironmentKeys.tags, JsonPipelineUtils.asTree(environmentYaml.getTags()));
>         objectNode.replace(EnvironmentKeys.description, JsonPipelineUtils.asTree(environmentYaml.getDescription()));
> ```

Lets use  objectNode.put(String, String) instead of replace

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40374)* status: 3 file(s) to review. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40374)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/executable/SyncExecutableWithRbac.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/40374#-NHAB8TW1n0X5SkYSL5x:-NHAB8TW1n0X5SkYSL5y:b3rq0uo) ([raw file](https://github.com/harness/harness-core/blob/12f3336402f8648a1543be709d1bb514cf43566f/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/executable/SyncExecutableWithRbac.java#L40)):*
> ```Java
> 
>   StepResponse executeSyncAfterRbac(
>       Ambiance ambiance, T stepParameters, StepInputPackage inputPackage, PassThroughData passThroughData) throws IOException;
> ```

Lets not make this change

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfraStepUtils.java` line 121 at r2](https://reviewable.io/reviews/harness/harness-core/40374#-NHAB0YuC4K0NQ33ENKz:-NHDKv2L3Xf5rwf0YG9w:b-ttraf6) ([raw file](https://github.com/harness/harness-core/blob/12f3336402f8648a1543be709d1bb514cf43566f/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfraStepUtils.java#L121)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets use  objectNode.put(String, String) instead of replace
</blockquote></details>



Both seems to have same impl.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfraStepUtils.java` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/40374#-NHAA0Qb0GAFzw5LCDC7:-NHDL1Yo4n_p67K8xf4_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/12f3336402f8648a1543be709d1bb514cf43566f/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfraStepUtils.java#L116)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should also check if yamlNode.getcurrentJsonNode().get("environment") is an object node to avoid class cast
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/executable/SyncExecutableWithRbac.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/40374#-NHAB8TW1n0X5SkYSL5x:-NHDLPnkEgPPf7lX3or7:b-dfi3bi) ([raw file](https://github.com/harness/harness-core/blob/12f3336402f8648a1543be709d1bb514cf43566f/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/executable/SyncExecutableWithRbac.java#L40)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets not make this change
</blockquote></details>

This is due to our internal method YamlUtils.writeYamlString() has IoException, 
So i think handling it right there by just logging warning should be good right?

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40374)* status: :shipit: complete! ✓

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/executable/SyncExecutableWithRbac.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/40374#-NHAB8TW1n0X5SkYSL5x:-NHFJAtb8DmZVAxp9LLU:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/12f3336402f8648a1543be709d1bb514cf43566f/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/executable/SyncExecutableWithRbac.java#L40)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

This is due to our internal method YamlUtils.writeYamlString() has IoException, 
So i think handling it right there by just logging warning should be good right?
</blockquote></details>

Yes

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Pull request merged**
