### PR TITLE
[feat]: [PIE-7095]: Adding support for execution delete on pipeline delete

### PR DESCRIPTION
**Pull request by archit-harness**
## Describe your changes
Adding support for execution delete on pipeline delete

Impact: Added deletion of entities on pipeline and account Deletion on processing entity delete event

Testing: Deleting and checking error logs in PR env

ReleaseNotes summary needed? No

Is it new task type? No
Did you make changes to the code in a backward-compatible manner? Yes
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? Yes
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? Yes
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No change
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? Yes
if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? Yes
Did you remove an enum → No
Did you add an enum(That too at end of list) → No
FeatureFlag Added/Removed -> No
Verify Changes with affects any -> No

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42271)

### CODE REVIEW

**Comment by archit-harness** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/42271#-NLUFxxtA9zkJgTLua67:-NLUFxxtA9zkJgTLua68:b-hlb9od) ([raw file](https://github.com/harness/harness-core/blob/004ed926e58aa39b27a589467f85ea3d7180f4f4/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L93)):*
> ```Java
>   }
> 
>   private boolean processAccountEntityChangeEvent(EntityChangeDTO entityChangeDTO, String action) {
> ```

nit: could you please rename this to PipelineEntityChangeEvent?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 173 at r3](https://reviewable.io/reviews/harness/harness-core/42271#-NLUGhPP53foAmRrD9eI:-NLUGhPQAIwYm3C5wjrT:b2htpaq) ([raw file](https://github.com/harness/harness-core/blob/004ed926e58aa39b27a589467f85ea3d7180f4f4/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L173)):*
> ```Java
>   private void deletePipelineExecutionsDetailsInternal(Set<String> planExecutionsToDelete) {
>     // Deletes the barrierInstances
>     barrierService.deleteAllForGivenPlanExecutionId(planExecutionsToDelete);
> ```

Are we are not deleting planExecutions, planExecutionMetadata and graph?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 26 of 30 files at r1, 25 of 27 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42271)* status: 54 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42271)* status: 54 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/42271#-NLUFxxtA9zkJgTLua67:-NLUH7w0D19X-MxnYxXj:b-jpybi0) ([raw file](https://github.com/harness/harness-core/blob/004ed926e58aa39b27a589467f85ea3d7180f4f4/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L93)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: could you please rename this to PipelineEntityChangeEvent?
</blockquote></details>

yes, can i do in next pr as all tests passed
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 173 at r3](https://reviewable.io/reviews/harness/harness-core/42271#-NLUGhPP53foAmRrD9eI:-NLUHAZW01xm1H6Q6Wm-:b-yjd0jn) ([raw file](https://github.com/harness/harness-core/blob/004ed926e58aa39b27a589467f85ea3d7180f4f4/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L173)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Are we are not deleting planExecutions, planExecutionMetadata and graph?
</blockquote></details>

it will 2nd PR, wanted to keep Prs small

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 26 of 30 files at r1, 25 of 27 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42271)* status: 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42271)* status: :shipit: complete! ✓

**Pull request merged**
