### PR TITLE
fix: [PL-38283]: increase wait time brfore removing old pod during upgrade

### PR DESCRIPTION
**Pull request by xingchi-jin**
## Describe your changes
Set minimum number of seconds for which a newly created Pod should be ready without any of its containers crashing, for it to be considered available.
This is set for improving stability during upgrade. It will tell kubernetes to wait at least this amount of seconds before removing the old pod after the new one becomes ready.

Test:
1. It doesn't affect the delegate startup installation time

image

2. It waited for > 2 min before it kill the old one 
image
From the above photo, you can see a new delegate has come up and running fine. But k8s not treat it as ready because of this setting . so k8s is not killing the old pod
image
This photo shows, the new pod has been running for 2 min, but the old one is still not be killed. The old was eventually killed when the new one has been running for 2 m 42 s 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47039)

### CODE REVIEW

**Review by AnupamIO — DISMISSED** [review]

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47039)* status: 7 file(s) to review. 

___
*[`400-rest/src/main/resources/delegatetemplates/harness-delegate-immutable.yaml.ftl` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/47039#-NU0syqN06iYWgZSAN8-:-NU0syqN06iYWgZSAN80:b-f3qofd) ([raw file](https://github.com/harness/harness-core/blob/86b0e569270c03c54ec70fa09a1e7dbb73583791/400-rest/src/main/resources/delegatetemplates/harness-delegate-immutable.yaml.ftl#L46)):*
> ```FreeMarker
> spec:
>   replicas: 1
>   minReadySeconds: 120
> ```

approved but one question: If let's say someone installs a new delegate then this means that for first 120s delegate will not receive/execute any request since it is not considered ready by k8 ?

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47039)* status: 7 file(s) to review. 

___
*[`400-rest/src/main/resources/delegatetemplates/harness-delegate-immutable.yaml.ftl` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/47039#-NU0uf_C5zX1t4WxlxE1:-NU0uf_C5zX1t4WxlxE2:b-nbhpts) ([raw file](https://github.com/harness/harness-core/blob/86b0e569270c03c54ec70fa09a1e7dbb73583791/400-rest/src/main/resources/delegatetemplates/harness-delegate-immutable.yaml.ftl#L47)):*
> ```FreeMarker
>   replicas: 1
>   minReadySeconds: 120
>   selector:
> ```

for above comment, trying to understand if user will have to wait for 2mins to execute any task, if he's installed first delegate in account.

**Review by mdmilic — DISMISSED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47039)* status: 1. unresolved discussions. 

___
*[`400-rest/src/main/resources/delegatetemplates/harness-delegate-immutable.yaml.ftl` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/47039#-NU0syqN06iYWgZSAN8-:-NU1GUQQ6J-5iV4UzCXl:b-lalbie) ([raw file](https://github.com/harness/harness-core/blob/86b0e569270c03c54ec70fa09a1e7dbb73583791/400-rest/src/main/resources/delegatetemplates/harness-delegate-immutable.yaml.ftl#L46)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

approved but one question: If let's say someone installs a new delegate then this means that for first 120s delegate will not receive/execute any request since it is not considered ready by k8 ?
</blockquote></details>

no, the pod will not serve any inbound traffic, but delegate only has outbound traffic which would work. Delegate would work normally apart from potentially delaying prometheus metrics by 2min (which is inbound traffic but not over internet)

**Review by xingchi-jin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47039)* status: 2. unresolved discussions. 

___
*[`400-rest/src/main/resources/delegatetemplates/harness-delegate-immutable.yaml.ftl` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/47039#-NU0syqN06iYWgZSAN8-:-NU2c6Zc91w6k98kxqzS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/86b0e569270c03c54ec70fa09a1e7dbb73583791/400-rest/src/main/resources/delegatetemplates/harness-delegate-immutable.yaml.ftl#L46)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

no, the pod will not serve any inbound traffic, but delegate only has outbound traffic which would work. Delegate would work normally apart from potentially delaying prometheus metrics by 2min (which is inbound traffic but not over internet)
</blockquote></details>

Done.
___
*[`400-rest/src/main/resources/delegatetemplates/harness-delegate-immutable.yaml.ftl` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/47039#-NU0uf_C5zX1t4WxlxE1:-NU2c74S7eST4IbGRCol:btztt8j) ([raw file](https://github.com/harness/harness-core/blob/86b0e569270c03c54ec70fa09a1e7dbb73583791/400-rest/src/main/resources/delegatetemplates/harness-delegate-immutable.yaml.ftl#L47)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

for above comment, trying to understand if user will have to wait for 2mins to execute any task, if he's installed first delegate in account.
</blockquote></details>

no, when starting a new deployment, it didn't even wait 2 min before the delegate pods show ready in k8s. Our logs indicates delegate was already installing tools and register and received capability tasks

**Review by AnupamIO — APPROVED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47039)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47039)* status: :shipit: complete! ✓

**Comment by xingchi-jin** [comment]
trigger ut2

**Comment by xingchi-jin** [comment]
trigger messagecheck

**Pull request merged**
