### PR TITLE
feat: [CDS-36149]: add private IP for Azure SSH

### PR DESCRIPTION
**Pull request by alebuh**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37994)

### CODE REVIEW

**Comment by alebuh** [comment]
trigger feature-build

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37994)

**Review by alebuh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37994)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): sto. 

___
*[`400-rest/src/main/java/software/wings/helpers/ext/azure/AzureHelperService.java` line 255 at r1](https://reviewable.io/reviews/harness/harness-core/37994#-NE6_nzjD9jEi_pfuUJM:-NEAk7JpCKGumYgEUfZC:b-w6l9jj) ([raw file](https://github.com/harness/harness-core/blob/12ff0804376e189b7754613529ba8096e94686fd/400-rest/src/main/java/software/wings/helpers/ext/azure/AzureHelperService.java#L255)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - it is a better solution to have privateIp on Host, calculation host string should be done on up level. I guess we will have drop-down with privateIp and publicDNS on UI  and, if set private IP as public DNS it doesn't make sense from host/instance perspective. Also, this host data is used for instance sync logic.  
</blockquote></details>

discussed this. will leave it as it is, as that is the way it's implemented for aws
___
*[`400-rest/src/main/java/software/wings/helpers/ext/azure/AzureHelperService.java` line 409 at r1](https://reviewable.io/reviews/harness/harness-core/37994#-NE6aCnR-aIzS0FvTkaT:-NEAkN-p3l82O-49N_tk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/12ff0804376e189b7754613529ba8096e94686fd/400-rest/src/main/java/software/wings/helpers/ext/azure/AzureHelperService.java#L409)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I think the default should be VM hostname instead of null.
</blockquote></details>

Done.

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37994#-:-NECL9rL4zkOHcz0Xbh6:bnfp4nl)* status: Waiting on team(s): sto.

**Review by alebuh — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37994)* status: Waiting on team(s): sto.

**Review by markoharness — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37994)* status: Waiting on team(s): sto.

**Pull request merged**
