### PR TITLE
fix: [CDS-53254]: Add Service Environment Infra schema validation in steps

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
If we are not able to convert a service or environment yaml to its respective Java POJO ( for eg. NGServiceConfig for service yaml ), currently, we show a generic error message like "unable to read service yaml" because we do not want to surface Jackson exceptions to the end user

Now, once this mapping fails, we do schema validation on the yaml and this allows for better user friendly error messages 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-53254]: https://harness.atlassian.net/browse/CDS-53254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-53254]: https://harness.atlassian.net/browse/CDS-53254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-53254]: https://harness.atlassian.net/browse/CDS-53254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-53254]: https://harness.atlassian.net/browse/CDS-53254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-53254]: https://harness.atlassian.net/browse/CDS-53254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-53254]: https://harness.atlassian.net/browse/CDS-53254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-53254]: https://harness.atlassian.net/browse/CDS-53254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-53254]: https://harness.atlassian.net/browse/CDS-53254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47288)

### CODE REVIEW

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47288)* status: 21 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java` line 400 at r2](https://reviewable.io/reviews/harness/harness-core/47288#-NUZvuyF0YJw9y1DRhgH:-NUZvuyG8gGtW8qQYr2p:b-8f85gp) ([raw file](https://github.com/harness/harness-core/blob/29d4ae234c5a369f46f50f23cd173e269cede725/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java#L400)):*
> ```Java
>       return InfrastructureEntityConfigMapper.toInfrastructureConfig(infrastructureEntity);
>     } catch (Exception ex) {
>       infrastructureYamlSchemaHelper.validateSchema(
> ```

Schema validation happens only if mapping fails..

Shouldn't it happen always?

**Review by archit-harness — DISMISSED** [review]

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java` line 400 at r2](https://reviewable.io/reviews/harness/harness-core/47288#-NUZvuyF0YJw9y1DRhgH:-NU_fmjAAotQgdvX-v7u:b-kew9d2) ([raw file](https://github.com/harness/harness-core/blob/29d4ae234c5a369f46f50f23cd173e269cede725/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java#L400)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Schema validation happens only if mapping fails..

Shouldn't it happen always?
</blockquote></details>

Earlier it was planned yo remove schema validation on every execution as it affect the performance.
I think thats why only doing for failed mapping  case.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java` line 400 at r2](https://reviewable.io/reviews/harness/harness-core/47288#-NUZvuyF0YJw9y1DRhgH:-NU_hdgU5v31sk16cJ_S:b-pirkh9) ([raw file](https://github.com/harness/harness-core/blob/29d4ae234c5a369f46f50f23cd173e269cede725/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java#L400)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Earlier it was planned yo remove schema validation on every execution as it affect the performance.
I think thats why only doing for failed mapping  case.
</blockquote></details>

I want to do this change in a safe manner

After this change goes, it will tell us when the schema validation fails even when mapping the yaml to the object passes
Because if we add schema validation in the direct flow, it might break some setups ( which might be wrong already but working )
Based on the logs, we will take a call

**Review by tchaurasiya — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47288)* status: 21 file(s) to review. 1. unresolved discussions.

**Comment by yogesh-chauhan** [comment]
trigger checkstylecodeformat

**Comment by yogesh-chauhan** [comment]
trigger uts

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 20 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47288)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java` line 400 at r2](https://reviewable.io/reviews/harness/harness-core/47288#-NUZvuyF0YJw9y1DRhgH:-NUa9m8eDUi_a94-vrBs:brxp9sq) ([raw file](https://github.com/harness/harness-core/blob/29d4ae234c5a369f46f50f23cd173e269cede725/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java#L400)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I want to do this change in a safe manner

After this change goes, it will tell us when the schema validation fails even when mapping the yaml to the object passes
Because if we add schema validation in the direct flow, it might break some setups ( which might be wrong already but working )
Based on the logs, we will take a call


</blockquote></details>

Sounds good.

**Comment by yogesh-chauhan** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
trigger uts

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47288)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47288)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47288)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
trigger review

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47288)* status: 1. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java` line 400 at r2](https://reviewable.io/reviews/harness/harness-core/47288#-NUZvuyF0YJw9y1DRhgH:-NUemS6y7kxeimAepV3z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/29d4ae234c5a369f46f50f23cd173e269cede725/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java#L400)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Sounds good.
</blockquote></details>

Done.

**Pull request merged**
