### PR TITLE
[feat]: [PL-29867]: Logic to add settings, service principal clients to NG auth filter modules. And add new external OAuth JWT token flow with validation using public keys

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
As part of requirement by JPMC, we need to support access to Harness SCIM API endpoints through an externally issued OAuth JWT token in NG. Currently the invocation of SCIM API is possible only through `sat` or `pat` Tokens. 

The externally issued OAuth token needs to be validated in two parts: 

1.  Authenticity of the Token is correct , i.e. it is generated by an Issuer which it claims to be - We achieve this by verifying signature of the JWT token using the Public keys of the Issuer. The public key of the Issuer will be configured under 'Account settings' in NG.
2.  Validate the claims in the JWT token to be matching with those configured under 'Account settings' in NG, and as well Mapped correctly to a Harness 'Service Account'. This is achieved through matching the required claims in payload segment of JWT token as well checking the Service account details in Harness. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40981)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
trigger checkstylecodeformat

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 34 files at r1, 2 of 29 files at r2, 1 of 31 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40981)* status: 35 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`965-api-key-filter/src/main/java/io/harness/security/NextGenAuthenticationFilter.java` line 116 at r5](https://reviewable.io/reviews/harness/harness-core/40981#-NIM3ek9EJWfZl5f3twy:-NIM3ekA1nd1KbU4jeCN:be77a2t) ([raw file](https://github.com/harness/harness-core/blob/285c51d2d423bdd4047e94c23366b582f3489389/965-api-key-filter/src/main/java/io/harness/security/NextGenAuthenticationFilter.java#L116)):*
> ```Java
>         tokenId = splitToken[2];
>       } else if (splitToken.length == 3) {
>         boolean isJwtTokenType = JWTTokenFlowAuthFilterUtils.isJWTTokenType(splitToken, accountIdentifier);
> ```

Do not change existing code, Create a new validate API key method and call it if token is of JWTToken
___
*[`965-api-key-filter/src/main/java/io/harness/security/NextGenAuthenticationFilter.java` line 266 at r5](https://reviewable.io/reviews/harness/harness-core/40981#-NIMI7xH-YAVUmtxbRMs:-NIMI7xI93dl-nR2bCfa:bix6zj7) ([raw file](https://github.com/harness/harness-core/blob/285c51d2d423bdd4047e94c23366b582f3489389/965-api-key-filter/src/main/java/io/harness/security/NextGenAuthenticationFilter.java#L266)):*
> ```Java
>   }
> 
>   private void handleSCIMJwtTokenFlow(String accountIdentifier, String jwtToken) {
> ```

Very complex method please break into multiple
___
*[`965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java` line 110 at r5](https://reviewable.io/reviews/harness/harness-core/40981#-NIMIPmZ7krvDrXl5x7O:-NIMIPmZ7krvDrXl5x7P:b-sq0cgd) ([raw file](https://github.com/harness/harness-core/blob/285c51d2d423bdd4047e94c23366b582f3489389/965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java#L110)):*
> ```Java
>     }
> 
>     JwtConsumer jwtConsumer = new JwtConsumerBuilder()
> ```

This. can be singleton
___
*[`965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java` line 121 at r5](https://reviewable.io/reviews/harness/harness-core/40981#-NIMIXei8b8BALie0Chw:-NIMIXei8b8BALie0Chx:b-6qwv7l) ([raw file](https://github.com/harness/harness-core/blob/285c51d2d423bdd4047e94c23366b582f3489389/965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java#L121)):*
> ```Java
> 
>       // validate expiry
>       if (jwtTokenClaims.getExpirationTime() != null
> ```

use jwtVerifier

**Comment by pbarapatre10** [comment]
*[`965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java` line 110 at r5](https://reviewable.io/reviews/harness/harness-core/40981#-NIMIPmZ7krvDrXl5x7O:-NIMfbh96SaaY9k7_GFs:biif4yk) ([raw file](https://github.com/harness/harness-core/blob/285c51d2d423bdd4047e94c23366b582f3489389/965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java#L110)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

This. can be singleton
</blockquote></details>

It is used within this method only. And the class is a `@UtilityClass`. We are also re-initializing it again below after few lines, so I think the current code is fine. Thanks

**Comment by pbarapatre10** [comment]
*[`965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java` line 121 at r5](https://reviewable.io/reviews/harness/harness-core/40981#-NIMIXei8b8BALie0Chw:-NIMifAeCxodmr2mflw_:b-44dzxn) ([raw file](https://github.com/harness/harness-core/blob/285c51d2d423bdd4047e94c23366b582f3489389/965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java#L121)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

use jwtVerifier
</blockquote></details>

jwtVerifier requires information about Algorithm and few more info to use. ref: https://github.com/harness/harness-core/blob/77a00a78b1bef79bcbd9d4189f182055cd94053d/400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java#L862 
Validating with public keys we have to use the current one, thanks

**Comment by piyush-harness** [comment]
*[`965-api-key-filter/src/main/java/io/harness/security/NextGenAuthenticationFilter.java` line 116 at r5](https://reviewable.io/reviews/harness/harness-core/40981#-NIM3ek9EJWfZl5f3twy:-NIN2XL1ET04YnfwulKN:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/285c51d2d423bdd4047e94c23366b582f3489389/965-api-key-filter/src/main/java/io/harness/security/NextGenAuthenticationFilter.java#L116)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Do not change existing code, Create a new validate API key method and call it if token is of JWTToken
</blockquote></details>

Done

**Review by piyush-harness — APPROVED** [review]
Approved for demo next, Unit tests and code cleanup has to be done in the next PR.
:lgtm:

> Reviewed 2 of 29 files at r2, 27 of 31 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40981#-:-NIN7jig27mX4M4jnnU_:b-91rspv)* status: 35 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Review by manish-manchanda — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40981)* status: 35 file(s) to review. 1 change requests. 1 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingIdentifiers.java` line 16 at r6](https://reviewable.io/reviews/harness/harness-core/40981#-NIN3G6983YyljEvlQSY:-NIN3G6983YyljEvlQSZ:b-jolvdk) ([raw file](https://github.com/harness/harness-core/blob/97f03ac54edfa51515768b65b3287d198fc5f10a/120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingIdentifiers.java#L16)):*
> ```Java
>   public static String SCIM_JWT_TOKEN_CONFIGURATION_KEY_IDENTIFIER = "scim_jwt_token_key_field";
>   public static String SCIM_JWT_TOKEN_CONFIGURATION_VALUE_IDENTIFIER = "scim_jwt_token_value_field";
>   public static String SCIM_JWT_TOKEN_CONFIGURATION_PUBLIC_KEY_IDENTIFIER = "scim_jwt_token_jwks_keys_url";
> ```

If this for key URL then lets change the variable name to highlight the same
___
*[`965-api-key-filter/src/main/java/io/harness/security/NextGenAuthenticationFilter.java` line 260 at r6](https://reviewable.io/reviews/harness/harness-core/40981#-NINBIXjBrrXNfbcMD-X:-NINBIXjBrrXNfbcMD-Y:b-4di3vx) ([raw file](https://github.com/harness/harness-core/blob/97f03ac54edfa51515768b65b3287d198fc5f10a/965-api-key-filter/src/main/java/io/harness/security/NextGenAuthenticationFilter.java#L260)):*
> ```Java
> 
>     String publicKeysJsonString =
>         JWTTokenFlowAuthFilterUtils.getPublicKeysJsonStringFromUrl(accountIdentifier, settingsStringValues[2]);
> ```

Using like this settingsStringValues[2] is error prone, if you are not moving this Map (as per another comment) lets consider taking in variable 
___
*[`965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java` line 159 at r6](https://reviewable.io/reviews/harness/harness-core/40981#-NINAg9eCZCmeA7s9ViZ:-NINAg9eCZCmeA7s9Vi_:bbw0s2v) ([raw file](https://github.com/harness/harness-core/blob/97f03ac54edfa51515768b65b3287d198fc5f10a/965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java#L159)):*
> ```Java
>   public boolean isJWTTokenType(String[] splitToken, String accountIdentifier) {
>     if (splitToken.length == 3) {
>       if (!("pat".equalsIgnoreCase(splitToken[0]) || "sat".equalsIgnoreCase(splitToken[0]))) {
> ```

Are there no constants for "pat" etc we can use ?
Please pull splitToken[0] to variable for readability 
String tokenType = header.getString("typ"); -> Is this a type of "type" or its "typ" only ?
___
*[`965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java` line 236 at r6](https://reviewable.io/reviews/harness/harness-core/40981#-NIN9rg_CCp2MG1-ddQb:-NIN9rg_CCp2MG1-ddQc:b-c4y4i6) ([raw file](https://github.com/harness/harness-core/blob/97f03ac54edfa51515768b65b3287d198fc5f10a/965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java#L236)):*
> ```Java
>   public String[] getSettingsStringValuesArrayFromListDTO(
>       List<SettingResponseDTO> settingsResponse, final String accountIdentifier) {
>     String[] settingStringVals = new String[4];
> ```

Instead of String Array can we use 
Map<String, String> settingMap = new HashMap<>();

for (SettingResponseDTO settingResponseDto : settingsResponse) {
      if (settingResponseDto != null && settingResponseDto.getSetting() != null) {
        settingMap.put(settingResponseDto.getSetting().getIdentifier(), settingResponseDto.getSetting().getValue());
        }
      }

But then you'll need to validate for pre-sense for those 4 keys later, see what is more readable and maintainable

**Comment by shashank-harness** [comment]
*[`965-api-key-filter/src/main/java/io/harness/security/NextGenAuthenticationFilter.java` line 260 at r6](https://reviewable.io/reviews/harness/harness-core/40981#-NINBIXjBrrXNfbcMD-X:-NINEEPI5cO_-NRjDBtj:bvplgag) ([raw file](https://github.com/harness/harness-core/blob/97f03ac54edfa51515768b65b3287d198fc5f10a/965-api-key-filter/src/main/java/io/harness/security/NextGenAuthenticationFilter.java#L260)):*
<details><summary><i>Previously, manish-manchanda wrote…</i></summary><blockquote>

Using like this settingsStringValues[2] is error prone, if you are not moving this Map (as per another comment) lets consider taking in variable 
</blockquote></details>

Agree. @pbarapatre10 Lets fix this in next PR along with UTs

**Comment by shashank-harness** [comment]
*[`965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java` line 82 at r6](https://reviewable.io/reviews/harness/harness-core/40981#-NINHdT-6aigtIyKFgDM:-NINHdT-6aigtIyKFgDN:blcbkep) ([raw file](https://github.com/harness/harness-core/blob/97f03ac54edfa51515768b65b3287d198fc5f10a/965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java#L82)):*
> ```Java
>   public void validateJwtTokenAndMatchClaimKeyValue(
>       String jwtToken, String toMatchClaimKey, String toMatchClaimValue, String publicKeys, String accountIdentifier) {
>     final int clockSkewAllowedInSeconds = 30; // 30 seconds is the allowed clockSkew in flow
> ```

@pbarapatre10 Can we make this configurable or is it something fixed?
In case its configurable, lets do that in next PR. This one is only for Demo so it's okay.

**Comment by shashank-harness** [comment]
*[`965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java` line 163 at r6](https://reviewable.io/reviews/harness/harness-core/40981#-NINI5Z8DajY6l0kr5Qq:-NINI5Z8DajY6l0kr5Qr:bhty6hr) ([raw file](https://github.com/harness/harness-core/blob/97f03ac54edfa51515768b65b3287d198fc5f10a/965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java#L163)):*
> ```Java
>           JSONObject header =
>               new JSONObject(new String(Base64.getUrlDecoder().decode(splitToken[0]), StandardCharsets.UTF_8));
>           String tokenType = header.getString("typ");
> ```

is this a typo? -> "typ"

**Comment by shashank-harness** [comment]
*[`965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java` line 82 at r6](https://reviewable.io/reviews/harness/harness-core/40981#-NINIFOAA-8v81Wczur4:-NINIFOAA-8v81Wczur5:blcbkep) ([raw file](https://github.com/harness/harness-core/blob/97f03ac54edfa51515768b65b3287d198fc5f10a/965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java#L82)):*
> ```Java
>   public void validateJwtTokenAndMatchClaimKeyValue(
>       String jwtToken, String toMatchClaimKey, String toMatchClaimValue, String publicKeys, String accountIdentifier) {
>     final int clockSkewAllowedInSeconds = 30; // 30 seconds is the allowed clockSkew in flow
> ```

@pbarapatre10 Can we make this configurable or is it something fixed?
In case its configurable, lets do that in next PR. This one is only for Demo so it's okay.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 2 of 34 files at r1, 2 of 29 files at r2, 28 of 31 files at r4, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40981)* status: 1 change requests. Waiting on team(s): sto.

**Review by manish-manchanda — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40981)* status: 1 change requests. Waiting on team(s): sto. 

___
*[`965-api-key-filter/src/main/java/io/harness/security/NextGenAuthenticationFilter.java` line 133 at r6](https://reviewable.io/reviews/harness/harness-core/40981#-NINIuO18WgPkR50yXSt:-NINIuO18WgPkR50yXSu:b-3l6as9) ([raw file](https://github.com/harness/harness-core/blob/97f03ac54edfa51515768b65b3287d198fc5f10a/965-api-key-filter/src/main/java/io/harness/security/NextGenAuthenticationFilter.java#L133)):*
> ```Java
>   private void validateApiKeyForJwt(String accountIdentifier, String apiKey, boolean isScimCall) {
>     if (isScimCall) {
>       handleSCIMJwtTokenFlow(accountIdentifier, apiKey);
> ```

In this method validateApiKeyForJwt() you have 2 behaviours one to validate and 2nd to set the Principal in context so might consider renaming method to show the same

**Review by manish-manchanda — APPROVED** [review]
:lgtm:

> Reviewed 2 of 34 files at r1, 2 of 29 files at r2, 28 of 31 files at r4, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40981#-:-NINKf7m2rczSRkMrCFm:bnfp4nl)* status: Waiting on team(s): sto.

**Pull request merged**
