### PR TITLE
fix: [CDS-72677]: Fix for re-run of trigger executions with empty inputs

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes
This PR fixes re-runs of executions fired by triggers with empty inputs. 

Previously, the `runtimeInputYaml` was passed to planExecution creation as "pipeline: {}\n", which causes issues with re-running these executions via Harness UI. This PR sets the `runtimeInputYaml` to "" (empty string) if the underlying pipeline doesn't expect any inputs, thus fixing the issue.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49558)

### CODE REVIEW

**Comment by vcalasansh** [comment]
trigger messagecheck

**Comment by vcalasansh** [comment]
trigger uts

**Comment by vcalasansh** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49558)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java` line 825 at r1](https://reviewable.io/reviews/harness/harness-core/49558#-NYWdlVE2m64HOo5Bp_a:-NYWdlVE2m64HOo5Bp_b:b-hytzsp) ([raw file](https://github.com/harness/harness-core/blob/5b66307f50d526f90316b9e47454c7d04e7c3fb3/pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java#L825)):*
> ```Java
>     // Triggers for pipelines with no inputs have "pipeline: {}\n" as their `inputYaml`.
>     // To avoid issues with pipeline re-runs, we need to set the inputYaml to "" in this case.
>     String templateYaml = InputSetTemplateHelper.createTemplateFromPipeline(pipelineYaml);
> ```

Here we are calling uncesary template call again, should we validate if runtime input yaml is empty then send ""?

**Review by vcalasansh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49558)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java` line 825 at r1](https://reviewable.io/reviews/harness/harness-core/49558#-NYWdlVE2m64HOo5Bp_a:-NYXlv7r3trY0a1JpykS:bstms1w) ([raw file](https://github.com/harness/harness-core/blob/5b66307f50d526f90316b9e47454c7d04e7c3fb3/pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java#L825)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Here we are calling uncesary template call again, should we validate if runtime input yaml is empty then send ""?
</blockquote></details>

Thanks for the comment! So, here I thought it was a good idea to check whether the pipeline itself has no inputs, because that's the underlying cause which makes API throw error on re-run. If we check the trigger inputs instead, the issue will still happen if trigger has inputs but pipeline has none. For example, suppose you create a trigger for a pipeline which has input variable `var1`, then you go and remove this input from pipeline so now it has no inputs. The trigger will still work - the value provided for `var1` will just be ignored when creating the execution - but the re-run will fail with the same error we are getting today.

Also, note that this is not an inter-service call, `InputSetTemplateHelper.createTemplateFromPipeline` just does some yaml parsing.

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49558)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by Y0709 — APPROVED** [review]

**Comment by vcalasansh** [comment]
trigger uts

**Pull request merged**
