### PR TITLE
[feat]: [PL-22141]: API to update Harness built in global gcp kms secret manager

### PR DESCRIPTION
**Pull request by nishantsaini20**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30358)

### CODE REVIEW

**Comment by shashank-harness** [comment]
___
*[120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java, line 137 at r1](https://reviewable.io/reviews/harness/harness-core/30358#-Mujn_W3CgMTJwrEVslt:-Mujn_W3CgMTJwrEVslu:bn82eum) ([raw file](https://github.com/harness/harness-core/blob/b82eb55d3efae79c1254fe7c04ae88eba29a6ed8/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L137)):*
> ```Java
> 
>   @Override
>   public Optional<ConnectorResponseDTO> getGlobalKmsConnector() {
> ```

if getconnector does the job then this will not be required

**Comment by shashank-harness** [comment]
___
*[120-ng-manager/src/main/java/io/harness/ng/core/globalkms/impl/GlobalKmsServiceImpl.java, line 66 at r1](https://reviewable.io/reviews/harness/harness-core/30358#-MujoMmBB-eDKUJORBIe:-MujoMmBB-eDKUJORBIf:bx5klne) ([raw file](https://github.com/harness/harness-core/blob/b82eb55d3efae79c1254fe7c04ae88eba29a6ed8/120-ng-manager/src/main/java/io/harness/ng/core/globalkms/impl/GlobalKmsServiceImpl.java#L66)):*
> ```Java
>     GcpKmsConnectorDTO existingConnectorConfig =
>         (GcpKmsConnectorDTO) existingConnector.get().getConnector().getConnectorConfig();
>     connectorConfig.setHarnessManaged(existingConnectorConfig.isHarnessManaged());
> ```

as discussed, update existingConnectorConfig in db as it required less number of changes and eliminates any error



_Code quote:_
```Java
existingConnectorConfig
```

**Comment by shashank-harness** [comment]
___
*[440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepository.java, line 60 at r1](https://reviewable.io/reviews/harness/harness-core/30358#-MujpT1MAVY5YF7IcKwo:-MujpT1MAVY5YF7IcKwp:bvkix2p) ([raw file](https://github.com/harness/harness-core/blob/b82eb55d3efae79c1254fe7c04ae88eba29a6ed8/440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepository.java#L60)):*
> ```Java
>   Optional<Connector> findOne(Criteria criteria, String repo, String branch);
> 
>   Optional<Connector> findOne(Criteria criteria);
> ```

Not required

**Comment by shashank-harness** [comment]
___
*[440-connector-nextgen/src/main/java/io/harness/connector/services/ConnectorCrudService.java, line 40 at r1](https://reviewable.io/reviews/harness/harness-core/30358#-MujpVqY-PJ_oWgS70LL:-MujpVqY-PJ_oWgS70LM:bvkix2p) ([raw file](https://github.com/harness/harness-core/blob/b82eb55d3efae79c1254fe7c04ae88eba29a6ed8/440-connector-nextgen/src/main/java/io/harness/connector/services/ConnectorCrudService.java#L40)):*
> ```Java
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, String connectorIdentifier);
> 
>   Optional<ConnectorResponseDTO> getGlobalKmsConnector();
> ```

Not required

**Comment by shashank-harness** [comment]
___
*[440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java, line 146 at r1](https://reviewable.io/reviews/harness/harness-core/30358#-MujpYae3Q7NwhdJ4urj:-MujpYae3Q7NwhdJ4urk:bvkix2p) ([raw file](https://github.com/harness/harness-core/blob/b82eb55d3efae79c1254fe7c04ae88eba29a6ed8/440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java#L146)):*
> ```Java
> 
>   @Override
>   public Optional<Connector> findOne(Criteria criteria) {
> ```

Not required

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30358)* status: 23 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/globalkms/impl/GlobalKmsServiceImpl.java, line 66 at r1](https://reviewable.io/reviews/harness/harness-core/30358#-MujoMmBB-eDKUJORBIe:-MusbFTo6knaVJeLViMU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b82eb55d3efae79c1254fe7c04ae88eba29a6ed8/120-ng-manager/src/main/java/io/harness/ng/core/globalkms/impl/GlobalKmsServiceImpl.java#L66)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

as discussed, update existingConnectorConfig in db as it required less number of changes and eliminates any error
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java, line 137 at r1](https://reviewable.io/reviews/harness/harness-core/30358#-Mujn_W3CgMTJwrEVslt:-MusbJpaBE1LQv60J_uU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b82eb55d3efae79c1254fe7c04ae88eba29a6ed8/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L137)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

if getconnector does the job then this will not be required
</blockquote></details>

Done.
___
*[440-connector-nextgen/src/main/java/io/harness/connector/services/ConnectorCrudService.java, line 40 at r1](https://reviewable.io/reviews/harness/harness-core/30358#-MujpVqY-PJ_oWgS70LL:-MusbLqc9wNdqjPdlH12:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b82eb55d3efae79c1254fe7c04ae88eba29a6ed8/440-connector-nextgen/src/main/java/io/harness/connector/services/ConnectorCrudService.java#L40)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Not required
</blockquote></details>

Done.
___
*[440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepository.java, line 60 at r1](https://reviewable.io/reviews/harness/harness-core/30358#-MujpT1MAVY5YF7IcKwo:-MusbNVl7xvzt_Tm7yzx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b82eb55d3efae79c1254fe7c04ae88eba29a6ed8/440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepository.java#L60)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Not required
</blockquote></details>

Done.
___
*[440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java, line 146 at r1](https://reviewable.io/reviews/harness/harness-core/30358#-MujpYae3Q7NwhdJ4urj:-MusbPCv3c0VeFpEycc5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b82eb55d3efae79c1254fe7c04ae88eba29a6ed8/440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java#L146)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Not required
</blockquote></details>

Done.

**Comment by shashank-harness** [comment]
___
*[120-ng-manager/src/main/java/io/harness/ng/core/globalkms/impl/GlobalKmsServiceImpl.java, line 63 at r3](https://reviewable.io/reviews/harness/harness-core/30358#-Mv2Il1i83qIxPggQsN0:-Mv2Il1i83qIxPggQsN1:b-fljh0n) ([raw file](https://github.com/harness/harness-core/blob/f5db0f2d93a3499194b833a58ad656c2f26f5f3f/120-ng-manager/src/main/java/io/harness/ng/core/globalkms/impl/GlobalKmsServiceImpl.java#L63)):*
> ```Java
>     existingConnectorConfig.setProjectId(connectorConfig.getProjectId());
>     existingConnectorConfig.setRegion(connectorConfig.getRegion());
>     existingSecret.setSpec(secret.getSpec());
> ```

We can add a validation step as discussed



_Code quote:_
```Java
SecretCrudService
```

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30358)* status: 19 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/globalkms/impl/GlobalKmsServiceImpl.java, line 63 at r3](https://reviewable.io/reviews/harness/harness-core/30358#-Mv2Il1i83qIxPggQsN0:-Mv9kXsp-DTEoM0raRn2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f5db0f2d93a3499194b833a58ad656c2f26f5f3f/120-ng-manager/src/main/java/io/harness/ng/core/globalkms/impl/GlobalKmsServiceImpl.java#L63)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

We can add a validation step as discussed
</blockquote></details>

Done.

**Review by shashank-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30358)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
___
*[120-ng-manager/src/main/java/io/harness/ng/core/globalkms/impl/GlobalKmsServiceImpl.java, line 42 at r4](https://reviewable.io/reviews/harness/harness-core/30358#-MvIfVVL0pF_V8UFXtnq:-MvIfVVL0pF_V8UFXtnr:b-cyb887) ([raw file](https://github.com/harness/harness-core/blob/e7287c996c90381521e163b78e85fbbebaf009a7/120-ng-manager/src/main/java/io/harness/ng/core/globalkms/impl/GlobalKmsServiceImpl.java#L42)):*
> ```Java
> import javax.ws.rs.NotFoundException;
> 
> public class GlobalKmsServiceImpl implements GlobalKmsService {
> ```

Shall we name this NgGlobalKmsService?

**Review by piyush-harness — APPROVED** [review]
> Reviewed 4 of 23 files at r1, 6 of 9 files at r2, 11 of 13 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30358)* status: 19 file(s) to review.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30358)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
:lgtm:

**Review by shashank-harness — APPROVED** [review]
> Reviewed 3 of 23 files at r1, 8 of 13 files at r3, 2 of 4 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30358)* status: :shipit: complete! ✓

**Pull request merged**
