### PR TITLE
feat: [CDS-39387]: Purge serverless instance stats

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Describe your changes
Purge serverless instance stats
Purge stats for deleted accounts as well

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35205)

### CODE REVIEW

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35205)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/scheduler/InstancesPurgeJob.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/35205#-N6skSC16Y0ubF55IQVD:-N6skSC16Y0ubF55IQVE:b3ilvh) ([raw file](https://github.com/harness/harness-core/blob/e500d30ad4ac34ec84665a43d34de844dde3673d/400-rest/src/main/java/software/wings/scheduler/InstancesPurgeJob.java#L103)):*
> ```Java
>     Stopwatch sw = Stopwatch.createStarted();
> 
>     boolean purged = serverlessInstanceStatService.purgeUpTo(getStartingInstantOfRetentionOfInstanceStats());
> ```

this method name is too long. 



_Code quote:_
```Java
getStartingInstantOfRetentionOfInstanceStats()
```
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/stats/InstanceStatServiceImpl.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/35205#-N6skmhM7xQMcx1m0Wrl:-N6skmhM7xQMcx1m0Wrm:b-4btwpe) ([raw file](https://github.com/harness/harness-core/blob/e500d30ad4ac34ec84665a43d34de844dde3673d/400-rest/src/main/java/software/wings/service/impl/instance/stats/InstanceStatServiceImpl.java#L96)):*
> ```Java
>     log.info("Purging instance stats for deleted accounts if present");
>     Query<InstanceStatsSnapshot> query = persistence.createQuery(InstanceStatsSnapshot.class)
>                                              .field(InstanceStatsSnapshotKeys.timestamp)
> ```

should we make this a batch call.?



_Code quote:_
```Java
    Query<InstanceStatsSnapshot> query = persistence.createQuery(InstanceStatsSnapshot.class)
                                             .field(InstanceStatsSnapshotKeys.timestamp)
                                             .lessThan(timestamp);
```
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/stats/ServerlessInstanceStatServiceImpl.java` line 152 at r1](https://reviewable.io/reviews/harness/harness-core/35205#-N6slDiBEZtbOdINXp1m:-N6slDiBEZtbOdINXp1n:bj8bld6) ([raw file](https://github.com/harness/harness-core/blob/e500d30ad4ac34ec84665a43d34de844dde3673d/400-rest/src/main/java/software/wings/service/impl/instance/stats/ServerlessInstanceStatServiceImpl.java#L152)):*
> ```Java
>     log.info("Purging serverless instance stats for deleted accounts if present");
>     Query<ServerlessInstanceStats> query = persistence.createQuery(ServerlessInstanceStats.class)
>                                                .field(ServerlessInstanceStatsKeys.timestamp)
> ```

same as above.



_Code quote:_
```Java
    Query<ServerlessInstanceStats> query = persistence.createQuery(ServerlessInstanceStats.class)
                                               .field(ServerlessInstanceStatsKeys.timestamp)
                                               .lessThan(timestamp);
```

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35205)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/scheduler/InstancesPurgeJob.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/35205#-N6skSC16Y0ubF55IQVD:-N7GzIGO-AXFHfPxYh9l:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e500d30ad4ac34ec84665a43d34de844dde3673d/400-rest/src/main/java/software/wings/scheduler/InstancesPurgeJob.java#L103)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

this method name is too long. 
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/stats/InstanceStatServiceImpl.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/35205#-N6skmhM7xQMcx1m0Wrl:-N7GyOqp1I8sohA_4y3k:bv8os7c) ([raw file](https://github.com/harness/harness-core/blob/e500d30ad4ac34ec84665a43d34de844dde3673d/400-rest/src/main/java/software/wings/service/impl/instance/stats/InstanceStatServiceImpl.java#L96)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

should we make this a batch call.?
</blockquote></details>

I couldn't find a straightforward way to do it in the delete call itself. 
If batching is absolutely needed, one option is - could fetch all the documents, then collect the IDs (say 1000 at a time) and pass them to delete.

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35205)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/stats/ServerlessInstanceStatServiceImpl.java` line 152 at r1](https://reviewable.io/reviews/harness/harness-core/35205#-N6slDiBEZtbOdINXp1m:-N7H4MH5D-VKa7LOiKJE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e500d30ad4ac34ec84665a43d34de844dde3673d/400-rest/src/main/java/software/wings/service/impl/instance/stats/ServerlessInstanceStatServiceImpl.java#L152)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

Done.

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35205)* status: :shipit: complete! ✓

**Pull request merged**
