### PR TITLE
[feat]: [CDS-36326]: Added detailedExitCode for TF Plan

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33478)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33478)* status: 12 file(s) to review. 0 of 1 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 13 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33478)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 11 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33478#-:-N2z-IH46u7dfjkNqSW0:bnfp4nl)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 11 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33478)* status: :shipit: complete! ✓

**Review by arpit3107 — APPROVED** [review]
> Reviewed 11 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33478)* status: :shipit: complete! ✓

**Pull request merged**
