### PR TITLE
[fix]: [SRM-9928]: adding support for fromStage in SLO policy expansion

### PR DESCRIPTION
**Pull request by deepak-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32114)

### CODE REVIEW

**Comment by deepak-harness** [comment]
trigger ti1

**Comment by deepak-harness** [comment]
trigger ti4

**Comment by deepak-harness** [comment]
trigger checkstyle

**Comment by deepak-harness** [comment]
trigger codebasehash

**Comment by deepak-harness** [comment]
trigger ft2

**Comment by deepak-harness** [comment]
trigger ti0

**Comment by deepak-harness** [comment]
trigger ti1

**Comment by deepak-harness** [comment]
trigger ti2

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32114)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/governance/services/SLOPolicyExpansionHandler.java, line 114 at r1](https://reviewable.io/reviews/harness/harness-core/32114#-N-2FStS962QE5CRImnh:-N-2FStdCYYKOPgCDRfD:b-h1vyxa) ([raw file](https://github.com/harness/harness-core/blob/14f719f00efd005774091db553a9b480f33c979c/300-cv-nextgen/src/main/java/io/harness/cvng/governance/services/SLOPolicyExpansionHandler.java#L114)):*
> ```Java
>             CVNGStepUtils.findStageByIdentifier(propagateFromPipeline, useFromStageIdentifier);
>         return CVNGStepUtils.getServiceRefNode(propagateFromStage).asText();
>       } catch (IOException e) {
> ```

I don't think we should ignore this right? Is not having service or state is a valid state?
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/governance/services/SLOPolicyExpansionHandler.java, line 119 at r1](https://reviewable.io/reviews/harness/harness-core/32114#-N-2Fd-a0CD93lZ0vIvO:-N-2Fd-a0CD93lZ0vIvP:bcsnos0) ([raw file](https://github.com/harness/harness-core/blob/14f719f00efd005774091db553a9b480f33c979c/300-cv-nextgen/src/main/java/io/harness/cvng/governance/services/SLOPolicyExpansionHandler.java#L119)):*
> ```Java
>       }
>     }
>     return null;
> ```

if we don't ignore the exception then we don't need to return null right?

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32114)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/governance/services/SLOPolicyExpansionHandler.java, line 111 at r2](https://reviewable.io/reviews/harness/harness-core/32114#-N-2xmUBC05kRs7c-xJF:-N-2xmUBC05kRs7c-xJG:bt0klcc) ([raw file](https://github.com/harness/harness-core/blob/d4d5a603f027519f1f4b5401f7c469a9b98b4ee8/300-cv-nextgen/src/main/java/io/harness/cvng/governance/services/SLOPolicyExpansionHandler.java#L111)):*
> ```Java
>         log.error("Neither service or fromStage provided. FieldValue: " + fieldValue
>             + " yaml: " + metadata.getYaml().toStringUtf8());
>         throw new IllegalStateException("Neither service or fromStage provided");
> ```

can we pass e also. Otherwise we will miss the stacktrace.

**Pull request merged**
