### PR TITLE
techdebt: [CDS-14583]: Exception msg sanitization of all swimlane

### PR DESCRIPTION
**Pull request by namantalaycha10**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30712)

### CODE REVIEW

**Comment by namantalaycha10** [comment]
changes are incomplete

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 7 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30712)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java, line 223 at r2](https://reviewable.io/reviews/harness/harness-core/30712#-MvtrDLuAjA7Jxlfm-r0:-MvtrDLuAjA7Jxlfm-r1:bx3x4i6) ([raw file](https://github.com/harness/harness-core/blob/13c991662cea4e7cf9a1c91eb5f5218390c237e3/400-rest/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L223)):*
> ```Java
>       gitClient.ensureRepoLocallyClonedAndUpdated(gitOperationContext);
>     } catch (RuntimeException ex) {
>       Exception sanitizeException = ExceptionMessageSanitizer.sanitizeException(ex);
> ```

nit: sanitizedException
___
*[400-rest/src/main/java/software/wings/sm/states/ElasticLoadBalancerState.java, line 81 at r2](https://reviewable.io/reviews/harness/harness-core/30712#-Mvu0nJH4_ah0zimV2ZQ:-Mvu0nJJDwyV54j1lBFE:b-4wo7gf) ([raw file](https://github.com/harness/harness-core/blob/13c991662cea4e7cf9a1c91eb5f5218390c237e3/400-rest/src/main/java/software/wings/sm/states/ElasticLoadBalancerState.java#L81)):*
> ```Java
>           secretManager.getEncryptionDetails(awsConfig, context.getAppId(), context.getWorkflowExecutionId()));
>       ExceptionMessageSanitizer.storeAllSecretsForSanitizing(awsConfig,
>           secretManager.getEncryptionDetails(awsConfig, context.getAppId(), context.getWorkflowExecutionId()));
> ```

we don't need to call this method twice



_Code quote:_
```Java
 secretManager.getEncryptionDetails(awsConfig, context.getAppId(), context.getWorkflowExecutionId())
```
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java, line 584 at r2](https://reviewable.io/reviews/harness/harness-core/30712#-Mvu1Ddl2rkMHazfIaOs:-Mvu1Ddl2rkMHazfIaOt:b-2rcqsc) ([raw file](https://github.com/harness/harness-core/blob/13c991662cea4e7cf9a1c91eb5f5218390c237e3/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L584)):*
> ```Java
>       Exception sanitizeException = ExceptionMessageSanitizer.sanitizeException(ex);
>       log.error(
>           String.format("Exception in copying files to provisioner specific directory", sanitizeException.getMessage()),
> ```

there are no string formatters in the given string

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 18 of 20 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30712)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Pull request closed without merging**
