### PR TITLE
[fix]:[SRM-13261]: Don't show calculating for first 10 minutes of creation of SLI

### PR DESCRIPTION
**Pull request by deepak-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41071)

### CODE REVIEW

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41071)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceImpl.java` line 280 at r2](https://reviewable.io/reviews/harness/harness-core/41071#-NJFOkvV7mlN0V_nAbcQ:-NJFOkvV7mlN0V_nAbcR:bsfdk1p) ([raw file](https://github.com/harness/harness-core/blob/c1f549e6aa6fd2979cdb7fa34378bbaa0baedd95/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceImpl.java#L280)):*
> ```Java
>       errorBudgetRemaining = totalErrorBudgetMinutes - sliValue.getBadCount();
>     } else if (Instant.ofEpochMilli(serviceLevelIndicator.getCreatedAt())
>                    .isBefore(clock.instant().minus(Duration.ofMinutes(10)))) {
> ```

It should be
clock.instant(). isBefore(Instant.ofEpochMilli(serviceLevelIndicator.getCreatedAt().plus(Duration.ofMinutes(10))
or
Instant.ofEpochMilli(serviceLevelIndicator.getCreatedAt()).isAfter(clock.instant().minus(Duration.ofMinutes(10)))) 
I think first is more readable.

Also we can have test for this.



_Code quote:_
```Java
    } else if (Instant.ofEpochMilli(serviceLevelIndicator.getCreatedAt())
                   .isBefore(clock.instant().minus(Duration.ofMinutes(10)))) {
```

**Review by deepak-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41071)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceImpl.java` line 280 at r2](https://reviewable.io/reviews/harness/harness-core/41071#-NJFOkvV7mlN0V_nAbcQ:-NJIviTSAxepRsicF7xP:b-xii2j3) ([raw file](https://github.com/harness/harness-core/blob/c1f549e6aa6fd2979cdb7fa34378bbaa0baedd95/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceImpl.java#L280)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

It should be
clock.instant(). isBefore(Instant.ofEpochMilli(serviceLevelIndicator.getCreatedAt().plus(Duration.ofMinutes(10))
or
Instant.ofEpochMilli(serviceLevelIndicator.getCreatedAt()).isAfter(clock.instant().minus(Duration.ofMinutes(10)))) 
I think first is more readable.

Also we can have test for this.

</blockquote></details>

We don't want to show the calculating message until SLI was created within 10 minutes from now. 
Added a test case as well. if SLI if before 15 minutes then iscalculating is true else false.

**Review by AbhijithHarness — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41071)* status: 1 change requests. 1. unresolved discussions.

**Review by Varsha-lalwani — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41071#-:-NJJ5rNQ0f5odRJS_7GN:bnfp4nl)* status: :shipit: complete! ✓

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41071)* status: :shipit: complete! ✓

**Pull request merged**
