### PR TITLE
[feat]: [PIE-3910]: Add storeType and connectorRef to execution details

### PR DESCRIPTION
**Pull request by namanvermah**
This PR follows the standard procedure of adding new fields to execution summary API:
1. add the fields to execution metadata or plan execution metadata in `ExecutionHelper` (former in this case)
2. add them to summary entity when it is created in `ExecutionSummaryCreateEventHandler`
3. add these fields to `PipelineExecutionSummaryDTO` in `PipelineExecutionSummaryDtoMapper`

`storeType` and `connectorRef` are needed in the summary response so that UI doesn't have to make a separate call to get pipeline entity to display this info. This info is also needed for the "save as input set" button in rerun/retry pipeline modals.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33663)

### CODE REVIEW

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33663)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33663)* status: 13 file(s) to review.

**Comment by namanvermah** [comment]
The Proto file changed is not used for any delegate task, hence this change is backwards compatible.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33663)* status: :shipit: complete! ✓

**Pull request merged**
