### PR TITLE
feat: [CDS-82451]: Add listener for new topic for artifact collection

### PR DESCRIPTION
**Pull request by Y0709**
We decided to move artifact collection to a new topic **artifact_collection**,  We have created a new listener for that topic in this pr. We are only adding a listener in this pr so that in case there is a system rollback due to some incident we do not accumulate wait instances of this new topic as there will be no listener to this topic in previous release , Hence we are only indroducing a new stream and its listener in this pr and not creating wait instances on that stream. We will make changes for it in next release.

Testing -- 

Tested the new listener by temporarily creating wait instances on that stream and checking whether we are able to listen those events or not

Screenshot 2023-12-04 at 4 27 55 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56270)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger ut4, ut5

**Review by archit-harness — DISMISSED** [review]
> Reviewed 5 of 6 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56270)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56270)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/queue/consumers/ArtifactCollectionEventConsumerCg.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktMDpmAUdY7TUNeGZN:-NktMDpmAUdY7TUNeGZO:b3klnfu) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/400-rest/src/main/java/io/harness/queue/consumers/ArtifactCollectionEventConsumerCg.java#L22)):*
> ```Java
> import javax.cache.Cache;
> 
> public class ArtifactCollectionEventConsumerCg extends AbstractBaseConsumerCg {
> ```

not needed this is for redis which we do not use in CG
___
*[`400-rest/src/main/java/io/harness/queue/consumers/listeners/ArtifactCollectionEventMessageListenerCg.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktM6pE543ozeFo9DRu:-NktM6pE543ozeFo9DRv:b3klnfu) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/400-rest/src/main/java/io/harness/queue/consumers/listeners/ArtifactCollectionEventMessageListenerCg.java#L10)):*
> ```Java
> package io.harness.queue.consumers.listeners;
> 
> public class ArtifactCollectionEventMessageListenerCg extends AbstractMessageListenerCg {}
> ```

not needed this is for redis which we do not use in CG
___
*[`400-rest/src/main/java/io/harness/queue/publishers/CgArtifactCollectionEventPublisher.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktMHYG2RgvM6nufiLa:-NktMHYG2RgvM6nufiLb:b3klnfu) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/400-rest/src/main/java/io/harness/queue/publishers/CgArtifactCollectionEventPublisher.java#L20)):*
> ```Java
> 
> @Slf4j
> public class CgArtifactCollectionEventPublisher extends RedisNotifyQueuePublisher {
> ```

not needed this is for redis which we do not use in CG
___
*[`400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktMMN41RApc0Ly_vTy:-NktMMN41RApc0Ly_vTz:bpp6stj) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java#L60)):*
> ```Java
>       bind(Producer.class).annotatedWith(Names.named(CG_NOTIFY_EVENT)).toInstance(NoOpProducer.of(CG_NOTIFY_EVENT));
>       bind(Producer.class).annotatedWith(Names.named(CG_GENERAL_EVENT)).toInstance(NoOpProducer.of(CG_GENERAL_EVENT));
>       bind(Producer.class)
> ```

not needed
___
*[`400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktMNN9Dfc1Z3dCoELe:-NktMNN9Dfc1Z3dCoELf:bpp6stj) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java#L69)):*
> ```Java
>       bind(Consumer.class)
>           .annotatedWith(Names.named(CG_GENERAL_EVENT))
>           .toInstance(
> ```

not needed
___
*[`400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktMOxNDeBY3bQLRdUm:-NktMOxNDeBY3bQLRdUn:bpp6stj) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java#L88)):*
> ```Java
>           .toInstance(RedisProducer.of(CG_GENERAL_EVENT, redissonClient, CG_GENERAL_EVENT_TOPIC_SIZE,
>               MANAGER.getServiceId(), redisConfig.getEnvNamespace()));
>       bind(Producer.class)
> ```

not needed
___
*[`400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java` line 102 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktMPz9Ewsiqx4JbuNC:-NktMPz9Ewsiqx4JbuND:bpp6stj) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java#L102)):*
> ```Java
>               CG_GENERAL_EVENT_MAX_PROCESSING_TIME, CG_GENERAL_EVENT_BATCH_SIZE, redisConfig.getEnvNamespace()));
>       bind(Consumer.class)
>           .annotatedWith(Names.named(CG_ARTIFACT_COLLECTION_EVENT))
> ```

not needed
___
*[`400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java` line 114 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktMRCm6vzKBjqvJmqf:-NktMRCm6vzKBjqvJmqg:bpp6stj) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java#L114)):*
> ```Java
>       bind(MessageListener.class).annotatedWith(Names.named(CG_NOTIFY_EVENT)).to(NotifyEventMessageListenerCg.class);
>       bind(MessageListener.class).annotatedWith(Names.named(CG_GENERAL_EVENT)).to(GeneralEventMessageListenerCg.class);
>       bind(MessageListener.class)
> ```

not needed
___
*[`953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java` line 261 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktMV95-YWiIqv7oJd9:-NktMV95-YWiIqv7oJdA:bpp6stj) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java#L261)):*
> ```Java
>   public static final int CG_ARTIFACT_COLLECTION_EVENT_TOPIC_SIZE = 100000;
>   public static final int CG_ARTIFACT_COLLECTION_EVENT_BATCH_SIZE = 50;
>   public static final Duration CG_ARTIFACT_COLLECTION_EVENT_MAX_PROCESSING_TIME = Duration.ofMinutes(10);
> ```

not needed

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56270)* status: 6 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/queue/consumers/ArtifactCollectionEventConsumerCg.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktMDpmAUdY7TUNeGZN:-Nku-9ylEUCYufvI04iT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/400-rest/src/main/java/io/harness/queue/consumers/ArtifactCollectionEventConsumerCg.java#L22)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

not needed this is for redis which we do not use in CG
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/io/harness/queue/consumers/listeners/ArtifactCollectionEventMessageListenerCg.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktM6pE543ozeFo9DRu:-Nku-AJWEKK09defLRT4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/400-rest/src/main/java/io/harness/queue/consumers/listeners/ArtifactCollectionEventMessageListenerCg.java#L10)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

not needed this is for redis which we do not use in CG
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/io/harness/queue/publishers/CgArtifactCollectionEventPublisher.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktMHYG2RgvM6nufiLa:-Nku-Ak-76UBuV-py1bX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/400-rest/src/main/java/io/harness/queue/publishers/CgArtifactCollectionEventPublisher.java#L20)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

not needed this is for redis which we do not use in CG
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktMMN41RApc0Ly_vTy:-Nku-BzpDzJn2eI4ShFJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java#L60)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktMNN9Dfc1Z3dCoELe:-Nku-CWI8Y0F_D_94R6z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java#L69)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktMOxNDeBY3bQLRdUm:-Nku-CpKAhEe00gi-6nN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java#L88)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java` line 102 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktMPz9Ewsiqx4JbuNC:-Nku-D6iErcwK1gb_h-X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java#L102)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java` line 114 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktMRCm6vzKBjqvJmqf:-Nku-DfqEOxoTqcbIrf3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/400-rest/src/main/java/software/wings/app/ManagerEventsFrameworkModule.java#L114)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.
___
*[`953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java` line 261 at r2](https://reviewable.io/reviews/harness/harness-core/56270#-NktMV95-YWiIqv7oJd9:-Nku-E4d6PUNAgYyB1Y5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f73a2b7cca8e52ece867f9c35676234dfb65737b/953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java#L261)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56270)* status: 6 file(s) to review. 1 change requests. 9. unresolved discussions. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger ut5, ut6

**Comment by Y0709** [comment]
trigger uts

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56270)* status: 1 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1251 at r3](https://reviewable.io/reviews/harness/harness-core/56270#-Nl1dvQO8odO4myUXTtN:-Nl1i7FB-UUPoF9Atfy0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7fa149f24d4bbe7303bf19caa602abdb12a2acfb/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1251)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

this is not needed please delete, infact can you completely remove this flag redisNotifyEvent and related code
</blockquote></details>

Done.

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger ut4, ut5, ut6, ut7, ut8, ut9

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56270)* status: 3 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger ut5

**Comment by Y0709** [comment]
trigger ut5

**Pull request merged**
