### PR TITLE
feat: [DEL-3938]: change to debug logs

### PR DESCRIPTION
**Pull request by arpit3107**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32861)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32861)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1569 at r1](https://reviewable.io/reviews/harness/harness-core/32861#-N1OVP2lAzIf9UF9M66f:-N1OVP2lAzIf9UF9M66g:bwch4gi) ([raw file](https://github.com/harness/harness-core/blob/90ff912de9992b2e3b08a07780ee7e7bce27a0f4/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1569)):*
> ```Java
>     healthMonitorExecutor.scheduleAtFixedRate(() -> {
>       try {
>         log.debug("Starting local heartbeat.");
> ```

You can mark debug for manager heartbeat too.



_Code quote:_
```Java
g.debu
```

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32861)* status: :shipit: complete! ✓

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32861)* status: 1 change requests. 1. unresolved discussions. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1569 at r1](https://reviewable.io/reviews/harness/harness-core/32861#-N1OVP2lAzIf9UF9M66f:-N1PFH7F2ED38-63xxPA:b1zmayi) ([raw file](https://github.com/harness/harness-core/blob/90ff912de9992b2e3b08a07780ee7e7bce27a0f4/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1569)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

You can mark debug for manager heartbeat too.
</blockquote></details>

That costs much less, since that will appear once per min. Will be raising another pr later to handle low cost logs.

**Review by gaurav-jain1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32861)* status: 1 change requests. 1. unresolved discussions.

**Review by gaurav-jain1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32861)* status: :shipit: complete! ✓

**Pull request merged**
