### PR TITLE
feat: [PL-25422]: fix error messages in case of internal server error

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
Generic error message in case of internal server errors.
Fixed issue where error message was not clear when delegates are down.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33594)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/ScmExceptionUtils.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/33594#-N30szPqB-v5E5-Az7Qf:-N30szPqB-v5E5-Az7Qg:b-nned6u) ([raw file](https://github.com/harness/harness-core/blob/dffde7c0b8ab71c8c3c7e2ead3408b516ea7806b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/ScmExceptionUtils.java#L61)):*
> ```Java
>       return responseMessageList.get(responseMessageList.size() - 1).getMessage();
>     }
>     return "";
> ```

Should we put some reasonable default error message if by any chance this case becomes valid? That would be good instead of having empty string.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketCreateFileScmApiErrorHandler.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/33594#-N30t7ci4DCz9JgJ9vAh:-N30t7ci4DCz9JgJ9vAi:b16v4pu) ([raw file](https://github.com/harness/harness-core/blob/dffde7c0b8ab71c8c3c7e2ead3408b516ea7806b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketCreateFileScmApiErrorHandler.java#L42)):*
> ```Java
>             new ScmBadRequestException(errorMessage));
>       default:
>         log.error(String.format("Error while creating bitbucket file: [%s: %s]", statusCode, errorMessage));
> ```

Thanks for putting these logs. Wasn't required but surely good to have.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/33594#-N30tJ8I1-zTAuCi9oe0:-N30tJ8J0U04LyCfxEEw:bswndua) ([raw file](https://github.com/harness/harness-core/blob/dffde7c0b8ab71c8c3c7e2ead3408b516ea7806b/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L117)):*
> ```Java
>         log.info("Git Sync Service getFile ops response : {}", getFileResponse);
>       } catch (Exception ex) {
>         final String errorMessage = String.format(errorFormat, "get file");
> ```

lets use our enum operationType over here instead of hard-coded string. to add more consistency.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 121 at r1](https://reviewable.io/reviews/harness/harness-core/33594#-N30tSgoBy5qCIBkW8Dw:-N30tSgoBy5qCIBkW8Dx:b5ubzdm) ([raw file](https://github.com/harness/harness-core/blob/dffde7c0b8ab71c8c3c7e2ead3408b516ea7806b/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L121)):*
> ```Java
>         getFileResponse = GetFileResponse.newBuilder()
>                               .setStatusCode(HTTP_500)
>                               .setError(ErrorDetails.newBuilder().setErrorMessage(errorMessage).build())
> ```

we have to get away with this error message right? That was the plan so that there's no internal information shown on the UI. eg: If lets say its an NPE, then it will go to UI in this case.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 121 at r1](https://reviewable.io/reviews/harness/harness-core/33594#-N30tSgoBy5qCIBkW8Dw:-N30ur5cDlEHYopWtYlE:b-niu31a) ([raw file](https://github.com/harness/harness-core/blob/dffde7c0b8ab71c8c3c7e2ead3408b516ea7806b/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L121)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we have to get away with this error message right? That was the plan so that there's no internal information shown on the UI. eg: If lets say its an NPE, then it will go to UI in this case.
</blockquote></details>

I see its hardcoded string. Comment resolved. Thanks.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/33594#-N30v-EGE58AY__uhy7c:-N30v-EGE58AY__uhy7d:b-aiay3l) ([raw file](https://github.com/harness/harness-core/blob/dffde7c0b8ab71c8c3c7e2ead3408b516ea7806b/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L64)):*
> ```Java
>   @Inject EntityDetailProtoToRestMapper entityDetailProtoToRestMapper;
>   @Inject ExceptionManager exceptionManager;
>   private String errorFormat = "Unexpected error occurred while %s git operation. Please contact Harness Support.";
> ```

while "performing" % operation

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33594)* status: 18 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/ScmExceptionUtils.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/33594#-N32v7MKDH5GvTInE8gl:-N32v7MKDH5GvTInE8gm:b-br7vcj) ([raw file](https://github.com/harness/harness-core/blob/dffde7c0b8ab71c8c3c7e2ead3408b516ea7806b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/ScmExceptionUtils.java#L56)):*
> ```Java
>   }
> 
>   public static String getMessage(WingsException ex) {
> ```

The above method takes throwable, shouldn't this also take throwable ?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33594)* status: 18 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/ScmExceptionUtils.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/33594#-N32v7MKDH5GvTInE8gl:-N33VA7a3l8SnkRAOYGT:b-9gqh70) ([raw file](https://github.com/harness/harness-core/blob/dffde7c0b8ab71c8c3c7e2ead3408b516ea7806b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/ScmExceptionUtils.java#L56)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

The above method takes throwable, shouldn't this also take throwable ?
</blockquote></details>

This getMessage is specifically written for WingsException, for other exceptions it won't work, above is a different case.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/ScmExceptionUtils.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/33594#-N30szPqB-v5E5-Az7Qf:-N33Xvqp2lpfUES0D4o3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dffde7c0b8ab71c8c3c7e2ead3408b516ea7806b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/ScmExceptionUtils.java#L61)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Should we put some reasonable default error message if by any chance this case becomes valid? That would be good instead of having empty string.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/33594#-N30v-EGE58AY__uhy7c:-N33VP1y3pcheLT5LW6l:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dffde7c0b8ab71c8c3c7e2ead3408b516ea7806b/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L64)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

while "performing" % operation
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/33594#-N30tJ8I1-zTAuCi9oe0:-N33VPpu9uBHKVepzimy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dffde7c0b8ab71c8c3c7e2ead3408b516ea7806b/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L117)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets use our enum operationType over here instead of hard-coded string. to add more consistency.
</blockquote></details>

Done.

**Comment by bhavya181** [comment]
trigger ti1, ti3

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 16 of 18 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33594#-:-N342ew93Dax8Xdd7XO6:bnfp4nl)* status: 19 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 16 of 18 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33594)* status: :shipit: complete! ✓

**Pull request merged**
