### PR TITLE
fix: [DEL-4963]: Separate Redis instance for delegate-related operation

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
- Separate Redis instance for delegate-related operations and introduce separate Redis Config for delegate service.
- Distributed caching approach using Redisson Client RMap data structure
- Local Redis cache support using RLocalCachedMap
https://harness.atlassian.net/wiki/spaces/DEL/pages/21255423025/Dedicated+Redis+Instance+for+Delegate+Service

Test Performed
Sanity Test with disable flag to use Redis cache
         1) Delegate Installation - CG and NG
         2) K8 end to end flow - CG
         3) NG Pipeline execution

Delegate Cache 
- If flag enabled, Verify cache is present in Redis and value in hash
- Verify Delegate Cache fetch from Redis cache on read and refresh on every 1 minute
- Verify any update on Delegate entity reflects on UI/Redis cache
- Verify delete delegate updates the cache and remove from cache (pending)
- Verify task execution flow with delegate entity fetched from Redis

Delegate Group Cache
- Verify delegate groups cache are getting added to the Redis cache and value in hash
- Verify UI all delegates are displayed under the delegate group
- End to End Task execution with NG pipeline
- Verify list of selectors are displaying correctly in NG   

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44249)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger ut1

**Review by puthrayaharness — DISMISSED** [review]

**Comment by raghuAtWings** [comment]
*[`400-rest/src/test/resources/manager-kryo-registrations.txt` line 840 at r3](https://reviewable.io/reviews/harness/harness-core/44249#-NOziR4V6HdY3s5bLcgT:-NOziR4X807dKM44jzs8:b-fa9uq3) ([raw file](https://github.com/harness/harness-core/blob/2961dae1a19c5af4e0e09eea4f1d74ede21a5d80/400-rest/src/test/resources/manager-kryo-registrations.txt#L840)):*
> ```help
> 5700:io.harness.waiter.StringNotifyProgressData
> 5701:software.wings.service.impl.aws.model.embed.AwsLambdaDetails
> 5808:io.harness.delegate.beans.DelegateCapacity
> ```

why do we need to add this? do we even use capacity anymore?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 15 of 20 files at r1, 7 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44249)* status: 0 of 1 approvals obtained. Waiting on team(s): del-team.

**Comment by jennyjames21** [comment]
*[`400-rest/src/test/resources/manager-kryo-registrations.txt` line 840 at r3](https://reviewable.io/reviews/harness/harness-core/44249#-NOziR4V6HdY3s5bLcgT:-NOzidcMBNsDZdfynQO3:b3zwkf) ([raw file](https://github.com/harness/harness-core/blob/2961dae1a19c5af4e0e09eea4f1d74ede21a5d80/400-rest/src/test/resources/manager-kryo-registrations.txt#L840)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need to add this? do we even use capacity anymore?
</blockquote></details>

yes we do use capacity for CI flow, and we are serializing delegate entity using kyro for redis, this is the first time we are serializing  delegate entity

**Review by raghuAtWings — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44249)* status: :shipit: complete! ✓

**Pull request merged**
