### PR TITLE
fix: [CDS-46903]: Propagate no eligible delegate message to UI

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Describe your changes
1. Adding separate error code (`NO_ELIGIBLE_DELEGATES`) for No eligible delegate exception
2. Adding the message as a param and propagating this to the UI.

## Testing
1. No delegate in the account

2. Delegate selectors not matching the delegate

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40536)

### CODE REVIEW

**Review by acasian-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40536)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40536)* status: :shipit: complete! ✓

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/NoEligibleDelegatesInAccountException.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/40536#-NHeIavN1MaM9Z2Wgh4R:-NHeIavN1MaM9Z2Wgh4S:bgc1qj3) ([raw file](https://github.com/harness/harness-core/blob/3a2077eee5045cae77c8a55de28385a83e96cf7f/950-delegate-tasks-beans/src/main/java/io/harness/delegate/NoEligibleDelegatesInAccountException.java#L18)):*
> ```Java
>   public NoEligibleDelegatesInAccountException(String message) {
>     super(message, NO_ELIGIBLE_DELEGATES);
>     super.param(MESSAGE_ARG, message);
> ```

why we need this if we already passing message in constructor call above ?



_Code quote:_
```Java
super.param(MESSAGE_ARG, message
```

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40536)* status: 1 change requests. 1. unresolved discussions. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/NoEligibleDelegatesInAccountException.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/40536#-NHeIavN1MaM9Z2Wgh4R:-NHeK2y0BeLS8kApN-JJ:b-auh7wi) ([raw file](https://github.com/harness/harness-core/blob/3a2077eee5045cae77c8a55de28385a83e96cf7f/950-delegate-tasks-beans/src/main/java/io/harness/delegate/NoEligibleDelegatesInAccountException.java#L18)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

why we need this if we already passing message in constructor call above ?
</blockquote></details>

We use MessageManager.prepareMessage() to parse `NO_ELIGIBLE_DELEGATES=${message}` 
We need a message in the param for this. Please refer https://github.com/harness/harness-core/blob/develop/980-commons/src/main/java/io/harness/eraro/MessageManager.java#L50

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40536)* status: :shipit: complete! ✓

**Pull request merged**
