### PR TITLE
fix: [CDS-77579]: fixed create pipeline v1 spec API for V1 version

### PR DESCRIPTION
**Pull request by mohitg0795**
## Describe your changes
- For V1 spec APIs, pipeline creation handling was missing for V1 version.
- Fixed the missing pieces, now creation of pipelines working for both V1 and V0 version.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51887)

### CODE REVIEW

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51887)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 210 at r1](https://reviewable.io/reviews/harness/harness-core/51887#-NcQuTOLCWteqcUnIuit:-NcQuTOLCWteqcUnIuiu:bidtasa) ([raw file](https://github.com/harness/harness-core/blob/0ee16ffd1b2a292be19782f5a1d794f3c43a8cfa/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L210)):*
> ```Java
>       }
>       BasicPipeline basicPipeline = null;
>       if (pipelineVersion != null && !pipelineVersion.equals(PipelineVersion.V0)) {
> ```

pipelineVersion will always come right. should we have the condition in form of equals instead of not-equal? And give error if version does not match to v0 or v1? Because if user give any random value(v2/v3) in version then also the current code will handle for v1.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 210 at r1](https://reviewable.io/reviews/harness/harness-core/51887#-NcQuTOLCWteqcUnIuit:-NcQvotyB4iDqN4tm8Qt:b-reiob9) ([raw file](https://github.com/harness/harness-core/blob/0ee16ffd1b2a292be19782f5a1d794f3c43a8cfa/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L210)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

pipelineVersion will always come right. should we have the condition in form of equals instead of not-equal? And give error if version does not match to v0 or v1? Because if user give any random value(v2/v3) in version then also the current code will handle for v1.
</blockquote></details>

I copy pasted it from current handling itself done somewhere else in the code. But yes, we can try and handle it correctly. Will fix it.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51887)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51887)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger uts

**Pull request closed without merging**
