### PR TITLE
Fix: [SRM-12643]: Modify methods using serviceLevelObjectiveRef to use identifier instead of uuid

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
…e identifier instead of uuid

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39406)

### CODE REVIEW

**Comment by Varsha-lalwani** [comment]
trigger ft2, ti1, ti2, ti3, ti4

**Comment by Varsha-lalwani** [comment]
trigger ti1, ti2, ti3, ti4

**Review by karansaraswat19 — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39406)* status: :shipit: complete! ✓

**Review by deepak-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39406)* status: Some of the checks are too old. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/CompositeSLOMetricAnalysisStateExecutor.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/39406#-NGG50-4A2KWOd5w4g8V:-NGG50-4A2KWOd5w4g8W:bxvjn6c) ([raw file](https://github.com/harness/harness-core/blob/0025828838f58f866159e86fd0ac10b498b794ac/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/CompositeSLOMetricAnalysisStateExecutor.java#L61)):*
> ```Java
>     for (ServiceLevelObjectivesDetail objectivesDetail :
>         compositeServiceLevelObjective.getServiceLevelObjectivesDetails()) {
>       ProjectParams projectParams = ProjectParams.builder()
> ```

nit: see if we can make it a bulk DB call.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39406)* status: :shipit: complete! ✓

**Pull request merged**
