### PR TITLE
[fix]: [CDS-42182]: Add Infra Setup Usage when linked to pipeline

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
When we link infrastructure to a pipeline stage, this PR adds support to add usage for the same
Have tested this with single environment, multi environment, env/infra as expression/runtime inputs

Also verified account/org level environments

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-46496]: https://harness.atlassian.net/browse/CDS-46496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-42182]: https://harness.atlassian.net/browse/CDS-42182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-42182]: https://harness.atlassian.net/browse/CDS-42182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-42182]: https://harness.atlassian.net/browse/CDS-42182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43243)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentYamlV2VisitorHelper.java` line 77 at r2](https://reviewable.io/reviews/harness/harness-core/43243#-NNFx-sU1yQS2-eSfNId:-NNFx-sU1yQS2-eSfNIe:bmyalfm) ([raw file](https://github.com/harness/harness-core/blob/f1aa2d8aaaee072b09e8b3a36a90b6fe534df290/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentYamlV2VisitorHelper.java#L77)):*
> ```Java
>               .setType(EntityTypeProtoEnum.ENVIRONMENT)
>               .build();
>       contextMap.put(ENV_REF, environmentYamlV2.getEnvironmentRef().getExpressionValue());
> ```

This is to pass the environment ref down to the infrastructureYamlVisitor

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43243)* status: 12 file(s) to review. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/helper/InfraStructureDefinitionVisitorHelper.java` line 85 at r2](https://reviewable.io/reviews/harness/harness-core/43243#-NNG-rUe1UEo3jqQxbBp:-NNG-rUe1UEo3jqQxbBq:b55kqza) ([raw file](https://github.com/harness/harness-core/blob/f1aa2d8aaaee072b09e8b3a36a90b6fe534df290/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/helper/InfraStructureDefinitionVisitorHelper.java#L85)):*
> ```Java
>   }
> 
>   private EntityDetailProtoDTO getEntityDetailProtoDTO(String accountIdentifier, String orgIdentifier,
> ```

nit: would envIdentifierRef be enough for providing account, org, project info

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/helper/InfraStructureDefinitionVisitorHelper.java` line 85 at r2](https://reviewable.io/reviews/harness/harness-core/43243#-NNG-rUe1UEo3jqQxbBp:-NNGTY8YDuzGvwAhU7wg:b-6qj55g) ([raw file](https://github.com/harness/harness-core/blob/f1aa2d8aaaee072b09e8b3a36a90b6fe534df290/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/helper/InfraStructureDefinitionVisitorHelper.java#L85)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

nit: would envIdentifierRef be enough for providing account, org, project info
</blockquote></details>

We are passing account/org/project separately

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43243)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
trigger pmd

**Comment by yogesh-chauhan** [comment]
trigger codebasehash

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43243)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 6 of 12 files at r1, 2 of 2 files at r2, 1 of 2 files at r3, 1 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43243)* status: :shipit: complete! ✓

**Review by RajBaviskar — APPROVED** [review]
> Reviewed 6 of 12 files at r1, 2 of 2 files at r2, 1 of 2 files at r3, 1 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43243)* status: :shipit: complete! ✓

**Review by RajBaviskar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43243#-:-NNIaGPw5Mfcts2p4mGQ:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
