### PR TITLE
fix:[CDS-72250]: fixing file reference in azure and k8s apply step

### PR DESCRIPTION
**Pull request by sourabh-awashti**
## Describe your changes
File references was not being shown for file store when files are getting referenced in these steps
Implemented with file ref for these steps to extract file reference and added support for handling file reference in json creator.

Tests Done:
Adding files in these steps and getting reference in file store
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49939)

### CODE REVIEW

**Review by nassergonzalez — DISMISSED** [review]

**Comment by sourabh-awashti** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/azure/core/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfo.java` line 118 at r1](https://reviewable.io/reviews/harness/harness-core/49939#-NZa8EmqE8qnoKIn8AP_:-NZa8EmqE8qnoKIn8APa:bswj2fe) ([raw file](https://github.com/harness/harness-core/blob/c8ca290acbf59d27d323f56a7e471fbdca68da19/125-cd-nextgen/modules/azure/core/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfo.java#L118)):*
> ```Java
>     Map<String, ParameterField<List<String>>> fileRefMap = new HashMap<>();
> 
>     if (createStepConfiguration.getTemplate().getStore().getSpec() instanceof HarnessStore) {
> ```

just check if this can lead to NPE or not

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49939)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by sourabh-awashti** [comment]
trigger uts

**Comment by sourabh-awashti** [comment]
*[`125-cd-nextgen/modules/azure/core/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfo.java` line 118 at r1](https://reviewable.io/reviews/harness/harness-core/49939#-NZa8EmqE8qnoKIn8AP_:-NZaBWpbEgHmswgfw9J3:bxp96dt) ([raw file](https://github.com/harness/harness-core/blob/c8ca290acbf59d27d323f56a7e471fbdca68da19/125-cd-nextgen/modules/azure/core/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfo.java#L118)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

just check if this can lead to NPE or not
</blockquote></details>

I checked, all fields are marked with not null annotations so no need to add null check

**Review by nassergonzalez — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49939)* status: 6 file(s) to review.

**Comment by yogesh-chauhan** [comment]
trigger review

**Pull request merged**
