### PR TITLE
feat: [CDS-76982]: create StepElementParametersV1 and StepBaseParameters and use in Executables.

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Issue:** Currently, we have a class StepElementParameters which implements the interface StepParameters and that is being used by all the steps as their stepParametersClass. Now that we are implementing the v1 version of yaml, we need to create the v1 version of all the steps and use StepElementParametersV1 in them.

**Changes:** To avoid creating a new implementation for each step whenever a new YAML is planned, we have created an intermediate interface **StepBaseParameters** which extends StepParameters and will be implemented by StepElementParameters and StepElementParametersV1. 

In StepBaseParameters, we have added abstract get methods for the fields like name, timeout, etc. And in the steps, we will now set this StepBaseParameters as the stepParametersClass so that we will able to use the same steps for both versions.

In this PR, we have made this change for steps implementing TaskExecutable. Later, we can do it for other executables as well in incremental PRs.

PR can be reviewed in this flow:
StepBaseParameters - intermediate interface extending StepParameters and implemented by StepBaseParameters and StepElementParametersV1
StepElementParametersV1 - step parameters for v1 yaml.
TaskExecutableWithCapabilities and its two implementations (CDTaskExecutable and PipelineTaskExecutable) - Use StepBaseParameters instead of StepBaseParameters
In CD and Pipeline steps - Use StepBaseParameters instead of StepBaseParameters

**Impact:** All the steps in pipeline service and ng manager implementing TaskExecutable.

**Testing:**
- Tested that the Http step and Shell script step are running as expected for both V1 and V0 yamls. Also, ran other pipeline steps which have changes in this PR. 
- For testing, if the changes are backward compatible, Started a pipeline execution with pipeline service on develop branch then while it was running, reran the pipeline service on the feature branch, this did not affect the running execution. Also tested the same with the CD step and restarted the ng manager on the feature branch.
 
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51612)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51612)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/v1/StepElementParametersV1.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/51612#-NbYvr9v3w49qNmtTSY0:-NbYvr9v3w49qNmtTSY1:bqhvstp) ([raw file](https://github.com/harness/harness-core/blob/b8eafc885d85e3cc1afcad7e61087f14a3071288/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/v1/StepElementParametersV1.java#L41)):*
> ```Java
>   String description;
>   ParameterField<String> timeout;
>   List<FailureStrategyConfig> failureStrategies;
> ```

add failurestartegy yet to be implemented
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/v1/StepElementParametersV1.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/51612#-NbYvpDUCK2Fk4hGHU91:-NbYvpDUCK2Fk4hGHU92:b-tdntan) ([raw file](https://github.com/harness/harness-core/blob/b8eafc885d85e3cc1afcad7e61087f14a3071288/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/v1/StepElementParametersV1.java#L43)):*
> ```Java
>   List<FailureStrategyConfig> failureStrategies;
> 
>   ParameterField<String> skipCondition;
> ```

remove skip condition

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51612)* status: 16 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/v1/StepElementParametersV1.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/51612#-NbYvr9v3w49qNmtTSY0:-NbZ2FKYCl_YfVuekV8D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b8eafc885d85e3cc1afcad7e61087f14a3071288/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/v1/StepElementParametersV1.java#L41)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add failurestartegy yet to be implemented
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/v1/StepElementParametersV1.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/51612#-NbYvpDUCK2Fk4hGHU91:-NbZ2FZvDDhIxbjtkMul:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b8eafc885d85e3cc1afcad7e61087f14a3071288/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/v1/StepElementParametersV1.java#L43)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

remove skip condition
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 15 files at r2, 1 of 2 files at r3, 9 of 10 files at r4, 67 of 67 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51612)* status: 79 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]

**Review by harshjain12 — APPROVED** [review]

**Review by puthrayaharness — DISMISSED** [review]

**Review by archit-harness — APPROVED** [review]

**Comment by shalini-agr** [comment]
trigger uts

**Review by harshjain12 — APPROVED** [review]

**Review by puthrayaharness — APPROVED** [review]

**Comment by shalini-agr** [comment]
trigger review

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
