### PR TITLE
fix: [CDS-59253]: aws sam deploy step container adoption

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46632)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`879-pipeline-ci-commons/BUILD.bazel` line 13 at r4](https://reviewable.io/reviews/harness/harness-core/46632#-NTTYS8584f_AGSAz5Ii:-NTTYS8606HycHYPgitW:b-y1gkrk) ([raw file](https://github.com/harness/harness-core/blob/ba9ac0225ec5e60a90966af405eda589f5e1bd5c/879-pipeline-ci-commons/BUILD.bazel#L13)):*
> ```Starlark
>     name = "module",
>     srcs = glob(["src/main/java/**/*.java"]),
>     visibility = ["//visibility:public"],
> ```

why this change?

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 45 files at r1, 9 of 11 files at r2, 52 of 53 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46632)* status: 66 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 2 of 45 files at r1, 9 of 11 files at r2, 52 of 53 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46632)* status: Waiting on team(s): sto.

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46632)* status: Waiting on team(s): sto.

**Comment by abhinav-harness** [comment]
trigger ut5

**Review by rohitk-h — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46632)* status: 4 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46632)* status: Some of the checks are too old. Waiting on team(s): sto.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46632)* status: Waiting on team(s): sto.

**Review by rohitk-h — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46632)* status: Waiting on team(s): sto.

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46632)* status: 1 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46632)* status: 2 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46632)* status: 2 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46632)* status: Waiting on team(s): sto.

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 45 files at r1, 4 of 11 files at r2, 46 of 53 files at r3, 1 of 3 files at r4, 3 of 4 files at r5, 9 of 10 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46632)* status: Waiting on team(s): sto.

**Comment by harshjain12** [comment]
I am not onboarded with any of the pipeline service changes. Approving ci side of changes.

**Review by harshjain12 — APPROVED** [review]

**Review by hextechpal — APPROVED** [review]
> Reviewed 2 of 45 files at r1, 4 of 11 files at r2, 46 of 53 files at r3, 1 of 3 files at r4, 3 of 4 files at r5, 9 of 10 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46632)* status: Waiting on team(s): sto.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 45 files at r1, 4 of 11 files at r2, 46 of 53 files at r3, 1 of 3 files at r4, 3 of 4 files at r5, 9 of 10 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46632)* status: Waiting on team(s): sto.

**Pull request merged**
