### PR TITLE
[fix]: [CDS-41232]: Fixed timescale migrations

### PR DESCRIPTION
**Pull request by prabu-kr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36066)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 20 Issues 
* Vulnerability 3 Vulnerabilities 
 * Code issue 15 Code issues 
* Anti-pattern 2 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36066)

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Review by prabu-kr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36066)* status: 21 file(s) to review. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/TimescaleDBDataMigrationList.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9BfQs6Et__Cc6yCsJW:-N9BfQs6Et__Cc6yCsJX:b-qmo3t0) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/TimescaleDBDataMigrationList.java#L43)):*
> ```Java
>         .add(Pair.of(8, PodInfoPartialIndexForSyncQuery.class))
>         .add(Pair.of(9, AddParentPipelineDataToDeployment.class))
>         .add(Pair.of(10, AddWorkflowExecutionFailureDetails.class))
> ```

Change the order. Add noop if version has changed
___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddParentPipelineDataToDeployment.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9BjyFr-RaXSbhJbjvy:-N9BjyFr-RaXSbhJbjvz:b-7hzfs2) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddParentPipelineDataToDeployment.java#L55)):*
> ```Java
> 
>   private static final String update_statement =
>       "UPDATE DEPLOYMENT SET PARENT_PIPELINE_ID=?, WORKFLOWS=?, CAUSE=? WHERE EXECUTIONID=?";
> ```

Change name to CreatedByType
___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddParentPipelineDataToDeployment.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9BjVu66aVYwD_x1WNg:-N9BjVu66aVYwD_x1WNh:b54xk37) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddParentPipelineDataToDeployment.java#L72)):*
> ```Java
>           featureFlagService.getAccountIds(FeatureName.TIME_SCALE_CG_SYNC).stream().collect(Collectors.toList());
>       Map<String, Set<String>> accountIdToAppIdMap = new HashMap<>();
>       for (String accountId : accountIds) {
> ```

Move migration for accountIds logic to 400
___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddParentPipelineDataToDeployment.java` line 110 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9Bka7PCfS8XN9qScYH:-N9Bka7PCfS8XN9qScYI:b-10v00i) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddParentPipelineDataToDeployment.java#L110)):*
> ```Java
>         new BasicDBObject("accountId", accountId)
>             .append("appId", appId)
>             .append(WorkflowExecutionKeys.pipelineSummary, new BasicDBObject("$exists", Boolean.TRUE));
> ```

Remove the extra filter
___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddParentPipelineDataToDeployment.java` line 159 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9BoUou5P8YoGOKpofn:-N9BoUou5P8YoGOKpofo:b-g5hfdr) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddParentPipelineDataToDeployment.java#L159)):*
> ```Java
>                             .sort(new BasicDBObject().append(WorkflowExecutionKeys.createdAt, -1))
>                             .skip(updated)
>                             .limit(1000);
> ```

Create a new connection for every 1000 records
___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddWorkflowExecutionFailureDetails.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9Bq-h83PW5dqa9E-i1:-N9Bq-h83PW5dqa9E-i2:bb7nssp) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddWorkflowExecutionFailureDetails.java#L125)):*
> ```Java
>     DBCursor dataRecords = collection.find(objectsToBeUpdated, projection)
>                                .sort(new BasicDBObject().append(WorkflowExecutionKeys.createdAt, -1))
>                                .limit(1000);
> ```

redu
___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddWorkflowExecutionFailureDetails.java` line 138 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9BqBZ88rAaEQalZS6P:-N9BqBZ88rAaEQalZS6Q:bfgh8o6) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddWorkflowExecutionFailureDetails.java#L138)):*
> ```Java
>         updated++;
> 
>         if (updated != 0 && updated % 1000 == 0) {
> ```

Change 1000 to 500



_Code quote:_
```Java
    try (Connection connection = timeScaleDBService.getDBConnection();
         PreparedStatement updateStatement = connection.prepareStatement(update_statement)) {
```
___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddWorkflowExecutionFailureDetails.java` line 141 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9BqES7-nu-hTZWaji0:-N9BqES7-nu-hTZWaji1:b-nyt7f4) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddWorkflowExecutionFailureDetails.java#L141)):*
> ```Java
>           List<WorkflowExecution> workflowExecutionsWithFailureDetails =
>               workflowExecutionService.getWorkflowExecutionsWithFailureDetails(appId, workflowExecutions);
>           for (WorkflowExecution workflowExecution : workflowExecutionsWithFailureDetails) {
> ```

Start a connection here
___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/SyncWorkflowExecutionDataFromMongo.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9BuJut3QknlFb4wLKn:-N9BuJut3QknlFb4wLKo:bvyvdgf) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/SyncWorkflowExecutionDataFromMongo.java#L30)):*
> ```Java
>   private String debugLine = "MISSING_DEPLOYMENT_TIMESCALE MIGRATION: ";
>   private final long START_TS = 1659571200000L;
>   private final long END_TS = 1659916800000L;
> ```

validate this in timescale
___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/SyncWorkflowExecutionDataFromMongo.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9Bwipi-2BtLUI7qtIf:-N9Bwipi-2BtLUI7qtIg:bc5arfo) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/SyncWorkflowExecutionDataFromMongo.java#L61)):*
> ```Java
>   private void bulkPerformReconciliation(String accountId) {
>     log.info(debugLine + "Migrating all workflowExecutions for account " + accountId);
>     deploymentReconService.performReconciliation(accountId, START_TS, END_TS);
> ```

Convert the migration to an api and run it in a background thread. Ignore the deploymentreconInstance logic
___
*[`400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java` line 71 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9ByxhO09qNGqpuOp6-:-N9ByxhO09qNGqpuOp60:b-cmu86w) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java#L71)):*
> ```Java
>       "DELETE FROM DEPLOYMENT_STAGE WHERE EXECUTIONID=?";
>   private static final String insert_statement_migration_parent_table =
>       "INSERT INTO DEPLOYMENT_PARENT (EXECUTIONID,STARTTIME,ENDTIME,ACCOUNTID,APPID,TRIGGERED_BY,TRIGGER_ID,STATUS,SERVICES,CLOUDPROVIDERS,ENVIRONMENTS,PIPELINE,DURATION,ARTIFACTS,ENVTYPES,PARENT_EXECUTION,FAILURE_DETAILS,FAILED_STEP_NAMES,FAILED_STEP_TYPES,STAGENAME,ROLLBACK_DURATION, INSTANCES_DEPLOYED, TAGS,PARENT_PIPELINE_ID,WORKFLOWS,CAUSE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
> ```

Add missing ? and test this in local for other 2 tables. Update field name cause. Remove workflows in stage
___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceHelper.java` line 646 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9BsDFL1zPMxhw0YQTg:-N9BsDFL1zPMxhw0YQTh:b94fa84) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceHelper.java#L646)):*
> ```Java
>       StringJoiner failureMessage = new StringJoiner(", ");
>       StringJoiner failedStepNames = new StringJoiner(", ");
>       StringJoiner failedStepTypes = new StringJoiner(", ");
> ```

do a try catch here and log
___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceHelper.java` line 672 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9BsmfBEVHB1s-oqGkH:-N9BsmfBEVHB1s-oqGkI:bsa6k7r) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceHelper.java#L672)):*
> ```Java
>   }
> 
>   public static String getCause(WorkflowExecution workflowExecution) {
> ```

reuse it in migration

**Review by prabu-kr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36066)* status: 22 file(s) to review. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddParentPipelineDataToDeployment.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9BjyFr-RaXSbhJbjvy:-N9IBe4p5U8FOEPTzRHb:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddParentPipelineDataToDeployment.java#L55)):*
<details><summary><i>Previously, prabu-kr (Prabu Rajendran) wrote…</i></summary><blockquote>

Change name to CreatedByType
</blockquote></details>

Done
___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddParentPipelineDataToDeployment.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9BjVu66aVYwD_x1WNg:-N9IBfdb3-F66i2KZN5c:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddParentPipelineDataToDeployment.java#L72)):*
<details><summary><i>Previously, prabu-kr (Prabu Rajendran) wrote…</i></summary><blockquote>

Move migration for accountIds logic to 400
</blockquote></details>

Done
___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddParentPipelineDataToDeployment.java` line 110 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9Bka7PCfS8XN9qScYH:-N9IBjqE0QrYQU4ZlPfj:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddParentPipelineDataToDeployment.java#L110)):*
<details><summary><i>Previously, prabu-kr (Prabu Rajendran) wrote…</i></summary><blockquote>

Remove the extra filter
</blockquote></details>

Done
___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddParentPipelineDataToDeployment.java` line 159 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9BoUou5P8YoGOKpofn:-N9IBloQEE73nRCq1MN1:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddParentPipelineDataToDeployment.java#L159)):*
<details><summary><i>Previously, prabu-kr (Prabu Rajendran) wrote…</i></summary><blockquote>

Create a new connection for every 1000 records
</blockquote></details>

Done
___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddWorkflowExecutionFailureDetails.java` line 138 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9BqBZ88rAaEQalZS6P:-N9IBqOO5j5p3SH9avOv:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddWorkflowExecutionFailureDetails.java#L138)):*
<details><summary><i>Previously, prabu-kr (Prabu Rajendran) wrote…</i></summary><blockquote>

Change 1000 to 500
</blockquote></details>

Done
___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddWorkflowExecutionFailureDetails.java` line 141 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9BqES7-nu-hTZWaji0:-N9IBr4h5jw3HRXKNN4n:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddWorkflowExecutionFailureDetails.java#L141)):*
<details><summary><i>Previously, prabu-kr (Prabu Rajendran) wrote…</i></summary><blockquote>

Start a connection here
</blockquote></details>

Done
___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/SyncWorkflowExecutionDataFromMongo.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9BuJut3QknlFb4wLKn:-N9IBtMd-dIT91A1uwYN:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/SyncWorkflowExecutionDataFromMongo.java#L30)):*
<details><summary><i>Previously, prabu-kr (Prabu Rajendran) wrote…</i></summary><blockquote>

validate this in timescale
</blockquote></details>

Done
___
*[`390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/SyncWorkflowExecutionDataFromMongo.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9Bwipi-2BtLUI7qtIf:-N9IBuDaCUOv2yz_C8Hi:b-e2bn7n) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/SyncWorkflowExecutionDataFromMongo.java#L61)):*
<details><summary><i>Previously, prabu-kr (Prabu Rajendran) wrote…</i></summary><blockquote>

Convert the migration to an api and run it in a background thread. Ignore the deploymentreconInstance logic
</blockquote></details>

Using the script instead
___
*[`400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java` line 71 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9ByxhO09qNGqpuOp6-:-N9IBzm36hWxwfPB3Mxu:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java#L71)):*
<details><summary><i>Previously, prabu-kr (Prabu Rajendran) wrote…</i></summary><blockquote>

Add missing ? and test this in local for other 2 tables. Update field name cause. Remove workflows in stage
</blockquote></details>

Done
___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceHelper.java` line 646 at r3](https://reviewable.io/reviews/harness/harness-core/36066#-N9BsDFL1zPMxhw0YQTg:-N9IBYYA2Qvvhzn0nEqo:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c1b6231b69c48397d11c11b43741c0d65056ce01/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceHelper.java#L646)):*
<details><summary><i>Previously, prabu-kr (Prabu Rajendran) wrote…</i></summary><blockquote>

do a try catch here and log
</blockquote></details>

Done

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 10 of 20 files at r3, 6 of 11 files at r4, 3 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36066)* status: :shipit: complete! ✓

**Comment by prabu-kr** [comment]
trigger ti3

**Comment by prabu-kr** [comment]
trigger ti4

**Comment by prabu-kr** [comment]
trigger messagecheck

**Comment by prabu-kr** [comment]
trigger ft1

**Comment by prabu-kr** [comment]
trigger ti1

**Comment by prabu-kr** [comment]
trigger ti4

**Comment by prabu-kr** [comment]
trigger ti4

**Comment by prabu-kr** [comment]
trigger ti4

**Comment by prabu-kr** [comment]
trigger ti3

**Comment by prabu-kr** [comment]
trigger ft1

**Comment by prabu-kr** [comment]
trigger ti1

**Comment by prabu-kr** [comment]
trigger ti0

**Comment by prabu-kr** [comment]
trigger ti2

**Pull request merged**
