### PR TITLE
fix: [CODE-1186]: changes for the gitx

### PR DESCRIPTION
**Pull request by deepak-harness**
## Describe your changes

1. Remove any null check on connector ref(Since connector ref can be empty/null)
2. Added file path for the harness code
3. Added a new param isHarnessCodeRepo in the GitInfoDetails dto which is the DTO for accepting GitX param in the API to differentiate between the create entity request between remote entity third party connector or harness connector. GitSettingHelper uses this param to set the connectorRef to empty if this param is set. If the param is not set the flow remains the same.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56782)

### CODE REVIEW

**Comment by deepak-harness** [comment]
trigger uts

**Comment by deepak-harness** [comment]
trigger uts

**Comment by deepak-harness** [comment]
trigger ut5, ut6, ut7, ut9

**Comment by deepak-harness** [comment]
trigger uts

**Comment by deepak-harness** [comment]
trigger ut7

**Comment by mohitg0795** [comment]
Sorry, by mistake, clicked on "close PR". Have opened it back @deepak-harness .

**Review by hextechpal — CHANGES_REQUESTED** [review]
As we are changin g public-facing APIs we should make changes in our open-api spec as well

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56782#-:-NlhVjtT0HEqNAThDLAR:biemiz8)* status: 14 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by deepak-harness — COMMENTED** [review]
Changes are in pipeline v2 and inputset apis which are not part of the open api spec. so no changes required there.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56782#-:-Nli2oFADeK2cKbYOHww:bqgfwr0)* status: 14 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56782)* status: 14 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoHelper.java` line 64 at r3](https://reviewable.io/reviews/harness/harness-core/56782#-NliaPql9ynYFw8rL07-:-NliaPql9ynYFw8rL070:b6c7d3) ([raw file](https://github.com/harness/harness-core/blob/a31f7d12f2928df3fb847252eb572c1ffb6d37ca/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoHelper.java#L64)):*
> ```Java
>   }
> 
>   private String getCompleteHTTPUrlForHarness(ScmConnector scmConnector) {
> ```

I think this was commented before as well. This logic should be centrally handled just like we do for other GIT providers. Please can you make it exactly how its being done for other GIT providers.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56782)* status: 14 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java` line 73 at r3](https://reviewable.io/reviews/harness/harness-core/56782#-NliacRz06aXHFuC3YqD:-NliacS-DBS0j7JGnxOx:b-ffashv) ([raw file](https://github.com/harness/harness-core/blob/a31f7d12f2928df3fb847252eb572c1ffb6d37ca/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java#L73)):*
> ```Java
>         && GitAwareContextHelper.isNullOrDefault(gitEntityInfo.getConnectorRef())) {
>       String defaultConnectorForGitX = getDefaultConnectorForGitX(accountIdentifier, orgIdentifier, projectIdentifier);
>       if (TRUE.equals(gitEntityInfo.getIsHarnessCodeRepo())) {
> ```

Lets move this complete if block handling to GitAwareContextHelper for easier re-use later on as well. 

We can have some method like : "setHarnessCodeConnectorRef"

**Comment by deepak-harness** [comment]
trigger uts

**Comment by hitesharinga** [comment]
trigger ut6

**Pull request merged**
