### PR TITLE
[feat]:[CDS-35502] Add yaml snippet for CF

### PR DESCRIPTION
**Pull request by nassergonzalez**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32011)

### CODE REVIEW

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32011)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/resources/provisionerStrategyYaml/cloudformation.yaml, line 13 at r1](https://reviewable.io/reviews/harness/harness-core/32011#-Mzp3haZC5VBNx-U0Ghc:-Mzp3haZC5VBNx-U0Ghd:b-112fv7) ([raw file](https://github.com/harness/harness-core/blob/26612f5ff9ef5fa14a0d195a1ab7b0516b6d553d/125-cd-nextgen/src/main/resources/provisionerStrategyYaml/cloudformation.yaml#L13)):*
> ```YAML
>               connectorRef:
>               region:
>               roleArn:
> ```

Optional fields should not be here. If they remain unpopulated that's gonna be an invalid YAML
___
*[125-cd-nextgen/src/main/resources/provisionerStrategyYaml/cloudformation.yaml, line 14 at r1](https://reviewable.io/reviews/harness/harness-core/32011#-Mzp308lBiP1vwRIqKVg:-Mzp308lBiP1vwRIqKVh:b-pmj4zq) ([raw file](https://github.com/harness/harness-core/blob/26612f5ff9ef5fa14a0d195a1ab7b0516b6d553d/125-cd-nextgen/src/main/resources/provisionerStrategyYaml/cloudformation.yaml#L14)):*
> ```YAML
>               region:
>               roleArn:
>               templateFile:
> ```

I don't think we need an empty templateFile element 
___
*[125-cd-nextgen/src/main/resources/provisionerStrategyYaml/cloudformation.yaml, line 18 at r1](https://reviewable.io/reviews/harness/harness-core/32011#-Mzp39QS4-ptODCXpndB:-Mzp39QS4-ptODCXpndC:blbygj8) ([raw file](https://github.com/harness/harness-core/blob/26612f5ff9ef5fa14a0d195a1ab7b0516b6d553d/125-cd-nextgen/src/main/resources/provisionerStrategyYaml/cloudformation.yaml#L18)):*
> ```YAML
>                 spec:
>                   templateUrl:
>               parameters:
> ```

The same here, We don't need an empty parameters element.
___
*[125-cd-nextgen/src/main/resources/provisionerStrategyYaml/cloudformation.yaml, line 28 at r1](https://reviewable.io/reviews/harness/harness-core/32011#-Mzp3Imz32F4v1qcjYEU:-Mzp3Imz32F4v1qcjYEV:b-7c7iqw) ([raw file](https://github.com/harness/harness-core/blob/26612f5ff9ef5fa14a0d195a1ab7b0516b6d553d/125-cd-nextgen/src/main/resources/provisionerStrategyYaml/cloudformation.yaml#L28)):*
> ```YAML
>                       paths:
>               stackName:
>               parameterOverrides:
> ```

the same here.
___
*[125-cd-nextgen/src/main/resources/provisionerStrategyYaml/cloudformation.yaml, line 32 at r1](https://reviewable.io/reviews/harness/harness-core/32011#-Mzp4i9FD7PVD6jDd1AK:-Mzp4i9FD7PVD6jDd1AL:b-z2ptob) ([raw file](https://github.com/harness/harness-core/blob/26612f5ff9ef5fa14a0d195a1ab7b0516b6d553d/125-cd-nextgen/src/main/resources/provisionerStrategyYaml/cloudformation.yaml#L32)):*
> ```YAML
>                   value:
>                   type:
>               skipOnStakStatuses:
> ```

Optional
___
*[125-cd-nextgen/src/main/resources/provisionerStrategyYaml/cloudformation.yaml, line 35 at r1](https://reviewable.io/reviews/harness/harness-core/32011#-Mzp4PWQE_e51lbN2hKp:-Mzp4PWQE_e51lbN2hKq:bxxghm5) ([raw file](https://github.com/harness/harness-core/blob/26612f5ff9ef5fa14a0d195a1ab7b0516b6d553d/125-cd-nextgen/src/main/resources/provisionerStrategyYaml/cloudformation.yaml#L35)):*
> ```YAML
>               capabilities:
>               tags:
>     - step:
> ```

We don't need an approval step here

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32011)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/resources/provisionerStrategyYaml/cloudformation.yaml, line 44 at r3](https://reviewable.io/reviews/harness/harness-core/32011#-MzyVImB7ozTAvYIZg8y:-MzyVImB7ozTAvYIZg8z:br145al) ([raw file](https://github.com/harness/harness-core/blob/fb7b601a421ba7c48416aa057c24d70815378304/125-cd-nextgen/src/main/resources/provisionerStrategyYaml/cloudformation.yaml#L44)):*
> ```YAML
>         spec:
>           configuration:
>             type: Inline
> ```

Let's have inherited delete step.

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32011)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/resources/provisionerStrategyYaml/cloudformation.yaml, line 44 at r3](https://reviewable.io/reviews/harness/harness-core/32011#-MzyVImB7ozTAvYIZg8y:-MzynTd7EE_qm49lz1-c:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fb7b601a421ba7c48416aa057c24d70815378304/125-cd-nextgen/src/main/resources/provisionerStrategyYaml/cloudformation.yaml#L44)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Let's have inherited delete step.
</blockquote></details>

Done.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32011)* status: :shipit: complete! ✓

**Comment by nassergonzalez** [comment]
trigger ti0

**Pull request merged**
