### PR TITLE
fix: [CDS-79324]: Fetch ServiceLicenseUsage in batches to avoid timeout

### PR DESCRIPTION
**Pull request by mani5h-harness**
## Describe your changes
Fetch ServiceLicenseUsage in batches to avoid timeout

The query to fetch distinct services in last 30 days for license usage is timing out sometimes. 
I have divided the query into two query, to fetch the services in 15 day intervals.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53512)

### CODE REVIEW

**Comment by mani5h-harness** [comment]
trigger messagecheck

**Comment by mani5h-harness** [comment]
trigger uts

**Comment by mani5h-harness** [comment]
trigger uts

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53512)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java` line 359 at r1](https://reviewable.io/reviews/harness/harness-core/53512#-NfS4bEa3gbFNf4lW6OL:-NfS4bEbBT1RC3LnV1hb:be6rz02) ([raw file](https://github.com/harness/harness-core/blob/5367f4fec01c05d12ce0ffbcaaff974e1d3e551c/125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java#L359)):*
> ```Java
>     // splitting the data retrieval into 15-day intervals within the last 30 days.
> 
>     int sizeBatch1 = (int) Math.ceil(TIME_PERIOD_IN_DAYS * 1.0 / 2);
> ```

sizeBatch1 and sizeBatch2 have the same value, we can use constant. 
Pls simplify this, like having two variables 30 days back and 15 days back by using Instant class, and using it directly in queries.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java` line 368 at r1](https://reviewable.io/reviews/harness/harness-core/53512#-NfSBeNu4y137vrim4MV:-NfSBeNvAsOHCOiNWhfK:b-hg9ek3) ([raw file](https://github.com/harness/harness-core/blob/5367f4fec01c05d12ce0ffbcaaff974e1d3e551c/125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java#L368)):*
> ```Java
>     long startIntervalBatch2 = getEpochMilliNDaysAgo(endIntervalBatch2, sizeBatch2);
> 
>     Set<ServiceInfraInfo> activeServiceSet = new HashSet<>();
> ```

Does ServiceInfraInfo implement equal() and hashCode()?
Also, ask @harness-david can we add the new index on the service_infra_info table.

**Comment by mani5h-harness** [comment]
trigger messagecheck

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53512)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java` line 368 at r1](https://reviewable.io/reviews/harness/harness-core/53512#-NfSBeNu4y137vrim4MV:-NfVER5Z-0WDsAbTUw8b:b-ucuy9r) ([raw file](https://github.com/harness/harness-core/blob/5367f4fec01c05d12ce0ffbcaaff974e1d3e551c/125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java#L368)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Does ServiceInfraInfo implement equal() and hashCode()?
Also, ask @harness-david can we add the new index on the service_infra_info table.
</blockquote></details>

Can we do smt like this, 

long thirtyDaysBack     = getEpochMilliNDaysAgo(timestamp, TIME_PERIOD_30_DAYS);
logg fifteenDaysBack    = getEpochMilliNDaysAgo(timestamp, TIME_PERIOD_15_DAYS);

timeScaleDAL.getDistinctServiceWithExecutionInTimeRange(
        accountIdentifier, thirthyDaysBack, fifteenDaysBack)   //thirthyDaysBack inclusive, fifteenDaysBack exlusive

timeScaleDAL.getDistinctServiceWithExecutionInTimeRange(
        accountIdentifier, fifteenDaysBack, timstamp)             // fifteenDaysBack inclusive, timstamp exclusive

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53512)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java` line 368 at r1](https://reviewable.io/reviews/harness/harness-core/53512#-NfSBeNu4y137vrim4MV:-NfVOV5l779439jLdPCc:b-h3hr88) ([raw file](https://github.com/harness/harness-core/blob/5367f4fec01c05d12ce0ffbcaaff974e1d3e551c/125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java#L368)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can we do smt like this, 

long thirtyDaysBack     = getEpochMilliNDaysAgo(timestamp, TIME_PERIOD_30_DAYS);
logg fifteenDaysBack    = getEpochMilliNDaysAgo(timestamp, TIME_PERIOD_15_DAYS);

timeScaleDAL.getDistinctServiceWithExecutionInTimeRange(
        accountIdentifier, thirthyDaysBack, fifteenDaysBack)   //thirthyDaysBack inclusive, fifteenDaysBack exlusive

timeScaleDAL.getDistinctServiceWithExecutionInTimeRange(
        accountIdentifier, fifteenDaysBack, timstamp)             // fifteenDaysBack inclusive, timstamp exclusive
</blockquote></details>

And do this logic only on timeout DB exception.

**Comment by mani5h-harness** [comment]
> > Reviewed 1 of 2 files at r1, 1 of 3 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/53512)_ status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java` line 368 at r1](https://reviewable.io/reviews/harness/harness-core/53512#-NfSBeNu4y137vrim4MV:-NfVER5Z-0WDsAbTUw8b:b-ucuy9r) ([raw file](https://github.com/harness/harness-core/blob/5367f4fec01c05d12ce0ffbcaaff974e1d3e551c/125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java#L368)):_
> 
> Previously, ivan-83 (Ivan Mijailovic) wrote…
> Can we do smt like this,
> 
> long thirtyDaysBack = getEpochMilliNDaysAgo(timestamp, TIME_PERIOD_30_DAYS); logg fifteenDaysBack = getEpochMilliNDaysAgo(timestamp, TIME_PERIOD_15_DAYS);
> 
> timeScaleDAL.getDistinctServiceWithExecutionInTimeRange( accountIdentifier, thirthyDaysBack, fifteenDaysBack) //thirthyDaysBack inclusive, fifteenDaysBack exlusive
> 
> timeScaleDAL.getDistinctServiceWithExecutionInTimeRange( accountIdentifier, fifteenDaysBack, timstamp) // fifteenDaysBack inclusive, timstamp exclusive

updated the PR, with the feedback
the starttime and endtime, both are inclusive. So I am using fifteenDaysBack+1 in first query

Only fetching in batches on DataAccessException now, which is the exception we get on "read time out"

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53512)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java` line 368 at r1](https://reviewable.io/reviews/harness/harness-core/53512#-NfSBeNu4y137vrim4MV:-NfV_ucO2d2wuesGGXAt:br7g9jb) ([raw file](https://github.com/harness/harness-core/blob/5367f4fec01c05d12ce0ffbcaaff974e1d3e551c/125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java#L368)):*
<details><summary><i>Previously, mani5h-harness wrote…</i></summary><blockquote>

updated the PR, with the feedback
the starttime and endtime, both are inclusive. So I am using fifteenDaysBack+1 in first query

Only fetching in batches on DataAccessException now, which is the exception we get on "read time out"

</blockquote></details>

Nice! pls check the cause of org.jooq.exception.DataAccessException and check for timeout and re-fetching the services in that case.
And, move this logic to a separate method. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java` line 369 at r3](https://reviewable.io/reviews/harness/harness-core/53512#-NfVae4A38Goav2Xf4cn:-NfVae4B27zBdiZsIHiz:b-4nmt5q) ([raw file](https://github.com/harness/harness-core/blob/cc73ed92a2765128bd1bb0c9dbffede0956be432/125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java#L369)):*
> ```Java
>       Set<ServiceInfraInfo> activeServiceSet = new HashSet<>();
>       activeServiceSet.addAll(
>           timeScaleDAL.getDistinctServiceWithExecutionInTimeRange(accountIdentifier, fifteenDaysBack + 1, timestamp));
> ```

put a comment in code why +1.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
LGTM with minor comment for logs.

> Reviewed 1 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53512#-:-NfWcdZY0MKycQUHpYyK:bbwt58p)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java` line 381 at r4](https://reviewable.io/reviews/harness/harness-core/53512#-NfWbXkn5_gpEKcJPXT4:-NfWbXkoDtpBtS2gvbI0:b-2gfr11) ([raw file](https://github.com/harness/harness-core/blob/7e7de66440b9c28b01801262de259cf5aa16767e/125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java#L381)):*
> ```Java
>     try {
>       return timeScaleDAL.getDistinctServiceWithExecutionInTimeRange(accountIdentifier, timestamp, thirtyDaysBack);
>     } catch (Exception e) {
> ```

Add log.error(), we need to know the cause of the exception and for which accountId.

**Comment by mani5h-harness** [comment]
> LGTM with minor comment for logs.
> 
> > Reviewed 1 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/53512#-:-NfWcdZY0MKycQUHpYyK:bbwt58p)_ status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.
> 
> _[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java` line 381 at r4](https://reviewable.io/reviews/harness/harness-core/53512#-NfWbXkn5_gpEKcJPXT4:-NfWbXkoDtpBtS2gvbI0:b-2gfr11) ([raw file](https://github.com/harness/harness-core/blob/7e7de66440b9c28b01801262de259cf5aa16767e/125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java#L381)):_
> 
> > ```java
> >     try {
> >       return timeScaleDAL.getDistinctServiceWithExecutionInTimeRange(accountIdentifier, timestamp, thirtyDaysBack);
> >     } catch (Exception e) {
> > ```
> 
> Add log.error(), we need to know the cause of the exception and for which accountId.

Logs are present in getDistinctServiceWithExecutionInTimeRange when we fetch the data from DB
getDistinctServiceWithExecutionInTimeRange logs and rethrows, so logging again won't be helpful

**Review by ivan-83 — DISMISSED** [review]

**Review by piyush-bhuwalka — DISMISSED** [review]

**Comment by mani5h-harness** [comment]
trigger uts

**Comment by mani5h-harness** [comment]
trigger messagecheck

**Comment by mani5h-harness** [comment]
trigger uts

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53512#-:-NfogQJy4CwJ-K48kq20:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by mani5h-harness** [comment]
trigger review

**Pull request merged**
