### PR TITLE
[fix]: [CDS-7642]: Adding command flag disable statefiles in chartmuseum com…

### PR DESCRIPTION
**Pull request by namantalaycha10**
…mand

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30598)

### CODE REVIEW

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30598)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 294 at r2](https://reviewable.io/reviews/harness/harness-core/30598#-Mw8D2QP7xWi_6v4rIm2:-Mw8D2QQBdu_zT1jfTBs:bw47for) ([raw file](https://github.com/harness/harness-core/blob/ace513a559ae6964f66fd12a11b22848f8af91e2/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L294)):*
> ```Java
>     String tempDir = "";
>     if (useLatestChartMuseumVersion) {
>       tempDir = Paths.get(RESOURCE_DIR_BASE, repoName, "cache").toAbsolutePath().normalize().toString();
> ```

we have same logic at different places which creates the directory to use as repo cache. This is a code smell and can cause issues in future. Lets try to unify the code

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30598)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r2, 2 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30598)* status: Some of the checks are too old. 1 change requests. 

___
*[960-api-services/src/main/java/io/harness/chartmuseum/ChartMuseumClientHelper.java, line 80 at r3](https://reviewable.io/reviews/harness/harness-core/30598#-MwyYcrO1m0HezhmLR8G:-MwyYcrO1m0HezhmLR8H:b-2r89pf) ([raw file](https://github.com/harness/harness-core/blob/db44d249bc8e1a491e463ec80e99da3b7b107690/960-api-services/src/main/java/io/harness/chartmuseum/ChartMuseumClientHelper.java#L80)):*
> ```Java
>       evaluatedTemplate = AMAZON_S3_COMMAND_TEMPLATE.replace("${BUCKET_NAME}", bucket)
>                               .replace("${FOLDER_PATH}", basePath == null ? "" : basePath)
>                               .replace("${REGION}", region);
> ```

how about 
template = ""
```
  if (useLatestChartMuseumVersion) {
      template = AMAZON_S3_COMMAND_TEMPLATE_LATEST_CM_BIN
    } else {
      template = AMAZON_S3_COMMAND_TEMPLATE
}
evaluatedTemplate = template.replace("${BUCKET_NAME}", bucket)
                              .replace("${FOLDER_PATH}", basePath == null ? "" : basePath)
                              .replace("${REGION}", region);
```
___
*[960-api-services/src/main/java/io/harness/chartmuseum/ChartMuseumClientHelper.java, line 104 at r3](https://reviewable.io/reviews/harness/harness-core/30598#-MwyZXFMAQMBwweD_HV2:-MwyZXFMAQMBwweD_HV3:b-ju9os8) ([raw file](https://github.com/harness/harness-core/blob/db44d249bc8e1a491e463ec80e99da3b7b107690/960-api-services/src/main/java/io/harness/chartmuseum/ChartMuseumClientHelper.java#L104)):*
> ```Java
>       evaluatedTemplate = GCS_COMMAND_TEMPLATE.replace("${BUCKET_NAME}", bucket)
>                               .replace("${FOLDER_PATH}", basePath == null ? "" : basePath);
>     }
> ```

ditto as above ^

**Pull request closed without merging**
