### PR TITLE
feat: [CDS-3904]: GCP 1.19 Authentication

### PR DESCRIPTION
**Pull request by BogdanAtHarness**
Add dynamic token supplier to KubernetesConfig. Persist GCP service account key JSON in the root of the working directory when running GCP >= 1.19 deployments. Append GOOGLE_APPLICATION_CREDENTIALS env var pointing to the GCP service account key JSON when running kubectl commands against GCP version >= 1.19. Add GCP access token caching. Create an authentication interceptor for K8s ApiClient that uses a new caching token supplier. Add unit tests & supporting classes.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32298)

### CODE REVIEW

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 18 of 42 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32298)* status: 24 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/app/WingsModule.java, line 1035 at r1](https://reviewable.io/reviews/harness/harness-core/32298#-N077kWN2UtYA9VbuIcc:-N077kWN2UtYA9VbuIcd:bffv69p) ([raw file](https://github.com/harness/harness-core/blob/7440022079f6662a2799adde62fe78bcfe612a55/400-rest/src/main/java/software/wings/app/WingsModule.java#L1035)):*
> ```Java
>     bind(GkeClusterService.class).to(GkeClusterServiceImpl.class);
>     try {
>       bind(new TypeLiteral<DataStore<StoredCredential>>() {
> ```

dont't we need stored credentials only on delegate ?

**Review by BogdanAtHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32298)* status: 24 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/app/WingsModule.java, line 1035 at r1](https://reviewable.io/reviews/harness/harness-core/32298#-N077kWN2UtYA9VbuIcc:-N07Dj016i62SVRbq6KE:btonzde) ([raw file](https://github.com/harness/harness-core/blob/7440022079f6662a2799adde62fe78bcfe612a55/400-rest/src/main/java/software/wings/app/WingsModule.java#L1035)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

dont't we need stored credentials only on delegate ?
</blockquote></details>

We do, but since we're binding GkeClusterHelper on Manager as well, we need this here as a direct dependency. I don't think this will be ever called from Manager

**Review by BogdanAtHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32298)* status: 24 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/app/WingsModule.java, line 1035 at r1](https://reviewable.io/reviews/harness/harness-core/32298#-N077kWN2UtYA9VbuIcc:-N07DyveDpTjUrxc_py_:b-m2rroq) ([raw file](https://github.com/harness/harness-core/blob/7440022079f6662a2799adde62fe78bcfe612a55/400-rest/src/main/java/software/wings/app/WingsModule.java#L1035)):*
<details><summary><i>Previously, BogdanAtHarness (Bogdan Azaric) wrote…</i></summary><blockquote>

We do, but since we're binding GkeClusterHelper on Manager as well, we need this here as a direct dependency. I don't think this will be ever called from Manager
</blockquote></details>

GkeClusterService has a dependency to GkeClusterHelper which in turn needs DataStore<StoredCredential>

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 5 of 42 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32298)* status: 18 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/gcp/helpers/GkeClusterHelper.java, line 221 at r2](https://reviewable.io/reviews/harness/harness-core/32298#-N0AiITP0948smm64nxU:-N0AiITP0948smm64nxV:b-2q0bbr) ([raw file](https://github.com/harness/harness-core/blob/0f4b39026ef0506bb870e46436c37e889eb373d4/930-delegate-tasks/src/main/java/io/harness/delegate/task/gcp/helpers/GkeClusterHelper.java#L221)):*
> ```Java
>       kubernetesConfigBuilder.clientKey(masterAuth.getClientKey().toCharArray());
>     }
>     if (cluster.getCurrentMasterVersion().compareTo("1.19") >= 0) {
> ```

if this is a string comparison, will it work if `cluster.getCurrentMasterVersion()` is lets say 1.20 ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 16 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32298)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[960-api-services/src/main/java/io/harness/k8s/model/GcpAccessTokenSupplier.java, line 73 at r2](https://reviewable.io/reviews/harness/harness-core/32298#-N0AjhdZCXvKbjio1G1L:-N0AjhdZCXvKbjio1G1M:bdbcrzy) ([raw file](https://github.com/harness/harness-core/blob/0f4b39026ef0506bb870e46436c37e889eb373d4/960-api-services/src/main/java/io/harness/k8s/model/GcpAccessTokenSupplier.java#L73)):*
> ```Java
>         .setTokenServerEncodedUrl(googleCredential.getTokenServerEncodedUrl())
>         .setServiceAccountProjectId(googleCredential.getServiceAccountProjectId())
>         .addRefreshListener(new DataStoreCredentialRefreshListener(googleCredential.getServiceAccountId(), cache))
> ```

what is the job of the refresh listener here ? I see that we are ourselves checking for expiry.
Does this update the cache ?

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 2 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32298)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by BogdanAtHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32298)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/gcp/helpers/GkeClusterHelper.java, line 221 at r2](https://reviewable.io/reviews/harness/harness-core/32298#-N0AiITP0948smm64nxU:-N0Am6ol7vkPJb5v16My:b-asalyg) ([raw file](https://github.com/harness/harness-core/blob/0f4b39026ef0506bb870e46436c37e889eb373d4/930-delegate-tasks/src/main/java/io/harness/delegate/task/gcp/helpers/GkeClusterHelper.java#L221)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

if this is a string comparison, will it work if `cluster.getCurrentMasterVersion()` is lets say 1.20 ? 
</blockquote></details>

Yes, it goes char by char. But actually, if the version is 1.9 it will not work. I will fix this, good call.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 41 of 42 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32298)* status: 1 change requests. 1. unresolved discussions.

**Review by BogdanAtHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32298)* status: 1 change requests. 1. unresolved discussions. 

___
*[960-api-services/src/main/java/io/harness/k8s/model/GcpAccessTokenSupplier.java, line 73 at r2](https://reviewable.io/reviews/harness/harness-core/32298#-N0AjhdZCXvKbjio1G1L:-N0Azril44SQWtGooxuV:bl14a3i) ([raw file](https://github.com/harness/harness-core/blob/0f4b39026ef0506bb870e46436c37e889eb373d4/960-api-services/src/main/java/io/harness/k8s/model/GcpAccessTokenSupplier.java#L73)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

what is the job of the refresh listener here ? I see that we are ourselves checking for expiry.
Does this update the cache ?
</blockquote></details>

Yes, it updates the cache

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32298)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32298)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32298)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
> Reviewed 35 of 42 files at r1, 3 of 3 files at r2, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32298)* status: :shipit: complete! ✓

**Pull request merged**
