### PR TITLE
feat: [CDS-53753]: Sync step creation

### PR DESCRIPTION
**Pull request by meenaravichandran1**
## Describe your changes
This PR has all the structs for a new step and has POJOs relevant to the sync step. Have stripped out the business logic from this PR to keep it simple for review.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44359)

### CODE REVIEW

**Comment by meenaravichandran1** [comment]
trigger messagecheck

**Review by anshul-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 29 files at r1, 25 of 25 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44359)* status: 29 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steptype/NGStepType.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/44359#-NP8y6zm9hVbV_vwzZCT:-NP8y6zm9hVbV_vwzZCU:b-77annp) ([raw file](https://github.com/harness/harness-core/blob/71df4d8e69ead11db0e8b6b9aaf6233e161b65a0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steptype/NGStepType.java#L40)):*
> ```Java
>   @JsonProperty(StepSpecTypeConstants.GITOPS_SYNC)
>   GITOPS_SYNC(
>       "Gitops Sync", Arrays.asList(ServiceDefinitionType.KUBERNETES), "Kubernetes", StepSpecTypeConstants.GITOPS_SYNC),
> ```

nit: Can we capitalize "o" in Gitops?



_Code quote:_
```Java
 "Gitops Sync"
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 648 at r2](https://reviewable.io/reviews/harness/harness-core/44359#-NP8yMWK8PbqRrj7phTj:-NP8yMWK8PbqRrj7phTk:b-vvt5iz) ([raw file](https://github.com/harness/harness-core/blob/71df4d8e69ead11db0e8b6b9aaf6233e161b65a0/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L648)):*
> ```Java
>             .setName("GitOps Sync")
>             .setType(StepSpecTypeConstants.GITOPS_SYNC)
>             .setFeatureFlag(FeatureName.NG_GITOPS.name())
> ```

Put this step behind a new feature flag. If we reuse the existing feature flag, then it will get enabled for everyone who already has NG-GITOPS ff



_Code quote:_
```Java
setFeatureFlag(FeatureName.NG_GITOPS.name()
```

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44359)* status: 29 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steptype/NGStepType.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/44359#-NP8y6zm9hVbV_vwzZCT:-NPAwb2M-6b0_cZtyFTC:b-8p159b) ([raw file](https://github.com/harness/harness-core/blob/71df4d8e69ead11db0e8b6b9aaf6233e161b65a0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steptype/NGStepType.java#L40)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

nit: Can we capitalize "o" in Gitops?
</blockquote></details>

ah, looks like I missed it in this place. Can I add it to the follow-up PR?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 648 at r2](https://reviewable.io/reviews/harness/harness-core/44359#-NP8yMWK8PbqRrj7phTj:-NPAwmYQ8O_NFmdmQn8l:bzarldk) ([raw file](https://github.com/harness/harness-core/blob/71df4d8e69ead11db0e8b6b9aaf6233e161b65a0/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L648)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Put this step behind a new feature flag. If we reuse the existing feature flag, then it will get enabled for everyone who already has NG-GITOPS ff
</blockquote></details>

makes sense, will make the change. Can I add it to the follow-up PR?

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44359)* status: 31 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 648 at r2](https://reviewable.io/reviews/harness/harness-core/44359#-NP8yMWK8PbqRrj7phTj:-NPB3aUb41TDFI6wBD2x:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/71df4d8e69ead11db0e8b6b9aaf6233e161b65a0/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L648)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

makes sense, will make the change. Can I add it to the follow-up PR?
</blockquote></details>

Done

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44359)* status: 31 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steptype/NGStepType.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/44359#-NP8y6zm9hVbV_vwzZCT:-NPB3rd45clIecETHeUx:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/71df4d8e69ead11db0e8b6b9aaf6233e161b65a0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steptype/NGStepType.java#L40)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

ah, looks like I missed it in this place. Can I add it to the follow-up PR?
</blockquote></details>

Done

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44359)* status: 31 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncBaseStepInfo.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/44359#-NPCfWNI7CX2YgE1R3UZ:-NPCfWNJ71mbp6zdgSSE:b-t1mcsp) ([raw file](https://github.com/harness/harness-core/blob/88ed884605b9d83ed754b6a2ed14df341521bfd1/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncBaseStepInfo.java#L48)):*
> ```Java
>   @ApiModelProperty(dataType = SwaggerConstants.GITOPS_AGENT_DETAILS_LIST_CLASSPATH)
>   @YamlSchemaTypes(value = {runtime})
>   public ParameterField<List<AgentApplicationTargets>> applicationsList;
> ```

ParameterField is needed only when you want to support something as runtime input. Generally, we do this for terminal/leaf fields. Full objects are rarely allowed to be runtime inputs unless a special use case. Also, UI won't be showing options to make these objects runtime, they also show runtime inputs options for terminal/leaf fields only.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44359)* status: 31 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncRetryStrategy.java` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/44359#-NPCglvtEWXn1D20CoOY:-NPCglvtEWXn1D20CoOZ:b-1y2ckk) ([raw file](https://github.com/harness/harness-core/blob/88ed884605b9d83ed754b6a2ed14df341521bfd1/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncRetryStrategy.java#L40)):*
> ```Java
>   @YamlSchemaTypes(value = {runtime})
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH)
>   public ParameterField<String> maxRetryBackoffDuration;
> ```

nit, since this is already inside retrystrategy, does every field in this class needs to have "retry" keyword?

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 4 of 29 files at r1, 22 of 25 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44359)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44359)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncBaseStepInfo.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/44359#-NPCfWNI7CX2YgE1R3UZ:-NPDt2mDCyeYEdVRZzky:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/88ed884605b9d83ed754b6a2ed14df341521bfd1/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncBaseStepInfo.java#L48)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

ParameterField is needed only when you want to support something as runtime input. Generally, we do this for terminal/leaf fields. Full objects are rarely allowed to be runtime inputs unless a special use case. Also, UI won't be showing options to make these objects runtime, they also show runtime inputs options for terminal/leaf fields only.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncRetryStrategy.java` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/44359#-NPCglvtEWXn1D20CoOY:-NPDsqnnBpWvXEDKUZuG:b-moqx80) ([raw file](https://github.com/harness/harness-core/blob/88ed884605b9d83ed754b6a2ed14df341521bfd1/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncRetryStrategy.java#L40)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, since this is already inside retrystrategy, does every field in this class needs to have "retry" keyword?
</blockquote></details>

for some of them, it is good to have to improve readability. Will check this for the other fields

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44359)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by anshul-harness — DISMISSED** [review]
> Reviewed 4 of 5 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44359)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 4 of 29 files at r1, 19 of 25 files at r2, 4 of 5 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44359)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 17 of 18 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44359)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Comment by meenaravichandran1** [comment]
trigger ut1

**Comment by meenaravichandran1** [comment]
trigger pmd

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 17 of 18 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44359)* status: :shipit: complete! ✓

**Review by anshul-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44359)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]

**Pull request merged**
