### PR TITLE
fix: [PL-23876]: Throwing exception when the user is externally managed.

### PR DESCRIPTION
**Pull request by boopesh007**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32200)

### CODE REVIEW

**Comment by boopesh007** [comment]
trigger messagecheck

**Comment by boopesh007** [comment]
trigger checkstyle

**Comment by mohitg0795** [comment]
*[123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java, line 556 at r2](https://reviewable.io/reviews/harness/harness-core/32200#-N-arjHo9ezxHAK0U5Bw:-N-arjHo9ezxHAK0U5Bx:b-um2az8) ([raw file](https://github.com/harness/harness-core/blob/1d46787de70339d7447f95a40f7bf7c20951e9de/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L556)):*
> ```Java
>     if (isUserExternallyManaged(userId)) {
>       log.error("User is externally managed, cannot delete user - userId: {}", userId);
>       throw new InvalidRequestException("User is externally managed, cannot delete user");
> ```

This is a change in contract. Just make sure that no UI should break. Also, if any customer is using this API, it will break for them, so need to check that as well.

Also, what does "externally managed" means here? Will our customers be able to interpret this error?

**Comment by boopesh007** [comment]
*[123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java, line 556 at r2](https://reviewable.io/reviews/harness/harness-core/32200#-N-arjHo9ezxHAK0U5Bw:-N-atJAQ9d_4eg2Bzl4v:b-f612qt) ([raw file](https://github.com/harness/harness-core/blob/1d46787de70339d7447f95a40f7bf7c20951e9de/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L556)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This is a change in contract. Just make sure that no UI should break. Also, if any customer is using this API, it will break for them, so need to check that as well.

Also, what does "externally managed" means here? Will our customers be able to interpret this error?
</blockquote></details>

I have tested the changes, there was no breakage in UI. If any customer is using this API to delete an externally managed user then they will get this exception. Externally managed means the user is managed through 3rd party ID Providers such as OKTA, Onelogin, etc. The case is Delete button itself will not be enabled for such externally managed users, so it's unlikely customers can trigger this API through UI. When they try to delete such users through API then they will get this error.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32200)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java, line 556 at r2](https://reviewable.io/reviews/harness/harness-core/32200#-N-arjHo9ezxHAK0U5Bw:-N-blv1s6oOP0GGXVibi:b2iwpmn) ([raw file](https://github.com/harness/harness-core/blob/1d46787de70339d7447f95a40f7bf7c20951e9de/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L556)):*
<details><summary><i>Previously, boopesh007 (Boopesh Shanmugam) wrote…</i></summary><blockquote>

I have tested the changes, there was no breakage in UI. If any customer is using this API to delete an externally managed user then they will get this exception. Externally managed means the user is managed through 3rd party ID Providers such as OKTA, Onelogin, etc. The case is Delete button itself will not be enabled for such externally managed users, so it's unlikely customers can trigger this API through UI. When they try to delete such users through API then they will get this error. 
</blockquote></details>

Ok, point to note is that its an API contract change. For any customers who are using this API, the behaviour will change for this particular use-case. So, that should be kept in mind. Approving it for now assuming developer is aware of the side-effects of the change.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32200#-:-N-bmMYQ8iNoPq8knMuR:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
