### PR TITLE
[fix]: [PL-41063]: Adds support to read json secret from hashicorp vault with jsonpath

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
Adds support to read json secret using jsonpath in Reference type secret

Tests:
- Verified Reference type secret creation with jsonpath working fine, Able to read json secret value using jsonpath.
- Tested for below secret manager
  - Hashicorp Vault
  - Azure key vault
  - GCP secret manager
  - AWS secret manager

- For secret with name `test-secret` and value
```
{
  "key1": "value1",
  "key2": {
    "key21": "value21",
    "key22": "value22"
  },
  "key3": {
    "key31": {
      "key311": "value311"
    }
  }
}
```
-  Getting below outputs for respective jsonpath
      - test-secret (without any # key)
         ```
          {
            "key1": "value1",
            "key2": {
              "key21": "value21",
              "key22": "value22"
            },
            "key3": {
              "key31": {
                "key311": "value311"
              }
            }
          }
          ```
      - test-secret#key1
         ```
          "value1"
          ```
      - test-secret#key2
         ```
          {
            "key21": "value21",
            "key22": "value22"
          }
          ```
      - test-secret#key3
         ```
         {
            "key31": {
              "key311": "value311"
           }
         }
         ```
      - test-secret#key3.key31
         ```
         {
            "key311": "value311"
         }
         ```
      - test-secret#key3.key31.key311
        ```
          "value311"
        ```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52490)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger ut7

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger ut7

**Comment by piyush-harness** [comment]
*[`931-secret-providers/src/java/io/harness/helpers/GlobalSecretManagerUtils.java` line 34 at r5](https://reviewable.io/reviews/harness/harness-core/52490#-Ne9TO-ABJxAF5W8TCLN:-Ne9TO-ABJxAF5W8TCLO:bd1z1k8) ([raw file](https://github.com/harness/harness-core/blob/fa0da20311919ff52ee2560c3979018a1b0f4c2a/931-secret-providers/src/java/io/harness/helpers/GlobalSecretManagerUtils.java#L34)):*
> ```Java
> 
>   public static String getValueByJsonPath(DocumentContext context, String key) throws JsonProcessingException {
>     ObjectMapper mapper = new ObjectMapper();
> ```

Can we reuse ObjectMapper or better use ObjectReader from it.

**Review by piyush-harness — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 8 files at r2, 4 of 6 files at r3, 1 of 1 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52490)* status: 14 file(s) to review. 0 of 2 approvals obtained.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
*[`931-secret-providers/src/java/io/harness/helpers/GlobalSecretManagerUtils.java` line 34 at r5](https://reviewable.io/reviews/harness/harness-core/52490#-Ne9TO-ABJxAF5W8TCLN:-NeEjAr74CI2XqHwRmv-:bv93g9j) ([raw file](https://github.com/harness/harness-core/blob/fa0da20311919ff52ee2560c3979018a1b0f4c2a/931-secret-providers/src/java/io/harness/helpers/GlobalSecretManagerUtils.java#L34)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Can we reuse ObjectMapper or better use ObjectReader from it.
</blockquote></details>

Moved objectmapper to class level variable

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger ut4, ut6

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger ut0, ut2, ut3, ut9

**Comment by ashishsanodia-harness** [comment]
trigger ut0

**Comment by ashishsanodia-harness** [comment]
trigger gitleaks

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 8 files at r2, 3 of 6 files at r3, 5 of 5 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52490)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 392 at r7](https://reviewable.io/reviews/harness/harness-core/52490#-NeM-v3z-ZrEXcGL66Ie:-NeM-v3z-ZrEXcGL66If:b-d3b3ks) ([raw file](https://github.com/harness/harness-core/blob/246a8b51f991650958a4b1d5f4f1f79de90e3820/931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L392)):*
> ```Java
>             AZURE_KEY_VAULT_OPERATION_ERROR, USER_SRE);
>       }
>       return getValueByJsonPath(parse(response.getValue().getValue()), parsedSecretReference.getKey()).toCharArray();
> ```

Can getValueByJsonPath return null? If yes then this can throw NPE.
___
*[`931-encryption-service/src/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java` line 192 at r7](https://reviewable.io/reviews/harness/harness-core/52490#-NeM0K9Z546TyBHUSgRk:-NeM0K9Z546TyBHUSgRl:b-t72drx) ([raw file](https://github.com/harness/harness-core/blob/246a8b51f991650958a4b1d5f4f1f79de90e3820/931-encryption-service/src/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java#L192)):*
> ```Java
>         AccessSecretVersionResponse response = gcpSecretsManagerClient.accessSecretVersion(secretVersionName);
>         String payload = response.getPayload().getData().toStringUtf8();
>         return getValueByJsonPath(parse(payload), key).toCharArray();
> ```

Same here, can cause NPE
___
*[`931-secret-providers/src/java/io/harness/helpers/GlobalSecretManagerUtils.java` line 40 at r7](https://reviewable.io/reviews/harness/harness-core/52490#-NeLzq_K25sDsd_q3S75:-NeLzq_L2ThjwYBgJlTb:b-u8ld01) ([raw file](https://github.com/harness/harness-core/blob/246a8b51f991650958a4b1d5f4f1f79de90e3820/931-secret-providers/src/java/io/harness/helpers/GlobalSecretManagerUtils.java#L40)):*
> ```Java
>     }
> 
>     return mapper.writeValueAsString(value);
> ```

What will this return if value is null?

**Comment by ashishsanodia-harness** [comment]
*[`931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 392 at r7](https://reviewable.io/reviews/harness/harness-core/52490#-NeM-v3z-ZrEXcGL66Ie:-NeMUDig4UTrpJd7pfS1:b-tkafoj) ([raw file](https://github.com/harness/harness-core/blob/246a8b51f991650958a4b1d5f4f1f79de90e3820/931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L392)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Can getValueByJsonPath return null? If yes then this can throw NPE.
</blockquote></details>

As discussed it won't return null but throw PathNotFoundException if json path is invalid, This is covered in unit test

**Comment by ashishsanodia-harness** [comment]
*[`931-encryption-service/src/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java` line 192 at r7](https://reviewable.io/reviews/harness/harness-core/52490#-NeM0K9Z546TyBHUSgRk:-NeMUkL5ECMOARPyATFP:b-tkafoj) ([raw file](https://github.com/harness/harness-core/blob/246a8b51f991650958a4b1d5f4f1f79de90e3820/931-encryption-service/src/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java#L192)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Same here, can cause NPE
</blockquote></details>

As discussed it won't return null but throw PathNotFoundException if json path is invalid, This is covered in unit test

**Comment by ashishsanodia-harness** [comment]
*[`931-secret-providers/src/java/io/harness/helpers/GlobalSecretManagerUtils.java` line 40 at r7](https://reviewable.io/reviews/harness/harness-core/52490#-NeLzq_K25sDsd_q3S75:-NeMUomV3ZnAYz17wsPw:b-w1qf1n) ([raw file](https://github.com/harness/harness-core/blob/246a8b51f991650958a4b1d5f4f1f79de90e3820/931-secret-providers/src/java/io/harness/helpers/GlobalSecretManagerUtils.java#L40)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

What will this return if value is null?
</blockquote></details>

context.read will throw PathNotFoundException if json path is invalid, This is covered in unit test. so value being passed to objectmapper won't be null.

**Review by nishantsaini20 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52490)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Pull request merged**
