### PR TITLE
[fix]: [CDS-46496]: Minimize quotes for converting objects to yaml in TemplateYamlUtils and CDYamlUtils

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
This change is behind FF `CDS_ENTITY_REFRESH_DO_NOT_QUOTE_STRINGS` 

## Describe your changes
Whenever we convert an object for eg. Map to yaml using yaml utils, it ends up adding double quotes to each string value by default. For eg. 

if the take this yaml
```
key: value
````

then converting this to a map and converting that map to yaml, changes it to as follows
```
key: "value"
```

This is not clean and causes confusions when these changes get pushed to Git. For eg. when a user reconciles a template, the diff shown on the UI does not match what is shown on Git side because every line ends up showing a change as below
image

However, after this change, the diffs are shown correctly as below
image

We achieve this by using the "MINIMIZE QUOTES" feature of Jackson Yaml Generator. Ref: https://www.javadoc.io/doc/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml/2.7.5/com/fasterxml/jackson/dataformat/yaml/YAMLGenerator.Feature.html#MINIMIZE_QUOTES. It quotes strings only when its multi line

This also fixes the issue where a multi line string used to be converted to a single line string with \n as below
image

This also indents arrays to be in line with what our UI also does
```
steps:
  - step:
```
as opposed to earlier
```
steps:
- step:
```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-46496]: https://harness.atlassian.net/browse/CDS-46496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-46496]: https://harness.atlassian.net/browse/CDS-46496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-46496]: https://harness.atlassian.net/browse/CDS-46496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43109)

### CODE REVIEW

**Review by hingerabhinav — DISMISSED** [review]
> Reviewed 6 of 7 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43109)* status: 21 file(s) to review. 1 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43109)* status: :shipit: complete! ✓

**Review by inderschera — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 3 of 15 files at r2, 28 of 31 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43109)* status: 31 file(s) to review. 1 of 2 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 31 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43109)* status: 30 file(s) to review. 1 of 2 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 2 of 31 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43109)* status: 28 file(s) to review. 1 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 25 of 31 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43109)* status: :shipit: complete! ✓

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 3 of 15 files at r2, 28 of 31 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43109)* status: :shipit: complete! ✓

**Pull request merged**
