### PR TITLE
[feat]: [CDP-20484]: Modify the data model

### PR DESCRIPTION
**Pull request by nassergonzalez**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30401)

### CODE REVIEW

**Comment by nassergonzalez** [comment]
trigger compile

**Comment by nassergonzalez** [comment]
trigger compile

**Review by tmacari-harness — COMMENTED** [review]
> Reviewed 10 of 14 files at r1, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30401)* status: 14 file(s) to review. 0 of 2 approvals obtained.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30401)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 10 of 14 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30401)* status: :shipit: complete! ✓

**Pull request merged**
