### PR TITLE
[feat]:[PL-29393]: adding additional metadata field in secret file sp…

### PR DESCRIPTION
**Pull request by shreyas-harness**
…ec dto

## Describe your changes
Adding additional metadata field in file spec dto
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39308)

### CODE REVIEW

**Comment by shreyas-harness** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 192 at r3](https://reviewable.io/reviews/harness/harness-core/39308#-NFSV_3N3lg9h-HFuaeB:-NFSV_3O1D9FGvm1hVot:blhslyv) ([raw file](https://github.com/harness/harness-core/blob/0358df86eebd85922eb61eb51948f82c5b5b27a4/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L192)):*
> ```Java
>         validateAdditionalMetadataInSecretFileSpecDTOForGcpSecretManager(secret);
>         return;
>       default:
> ```

is it expected that any other secret managers will be calling this method? If no, then we can add some info/warning log in default block to check who called it unexpectedly.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 205 at r3](https://reviewable.io/reviews/harness/harness-core/39308#-NFSWYceCtkoz4jHVD91:-NFSWYceCtkoz4jHVD92:b-eqks38) ([raw file](https://github.com/harness/harness-core/blob/0358df86eebd85922eb61eb51948f82c5b5b27a4/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L205)):*
> ```Java
>     Map<String, Object> values = secret.getAdditionalMetadata().getValues();
>     if (isEmpty(values)) {
>       throw new InvalidRequestException("Additional metadata must have values map");
> ```

As this method is very specific to GCP Secret Manager, we should have corresponding details mentioned in error statements as well so that we are clear eg: "additional metadata must have values map ** for gcp secret manager **". Same goes for further error statements as well.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 190 at r3](https://reviewable.io/reviews/harness/harness-core/39308#-NFSWv8l0DNbyTj4K4-6:-NFSWv8l0DNbyTj4K4-7:bew5g0t) ([raw file](https://github.com/harness/harness-core/blob/0358df86eebd85922eb61eb51948f82c5b5b27a4/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L190)):*
> ```Java
>     switch (secretManager.getEncryptionType()) {
>       case GCP_SECRETS_MANAGER:
>         validateAdditionalMetadataInSecretFileSpecDTOForGcpSecretManager(secret);
> ```

I would suggest you to create separate handler classes for it. Later on if further secret manager start to have these kind of validations, and if you keep on adding those methods in this class itself, it is going to become messy

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39308)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39308)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39308)* status: :shipit: complete! ✓

**Review by meenakshi-harness — APPROVED** [review]
Please update PR description with the testing done for this change.

**Comment by shreyas-harness** [comment]
> Please update PR description with the testing done for this change.

Done

**Pull request merged**
