### PR TITLE
feat: [PIE-9506]: set user name and email in uscm save flow

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Issue:** Currently we use the user's harness email and username as author info for git commits.

**Changes:** Save users' git email and username while saving their SCM in their profile. And use these credentials as author info while doing git commits.

**Impact:** The user's git username and email will be used as author info when the user's credentials will be used from their harness profile for git commits.

**Testing:** Tested git create and update after adding SCM in a user profile. The correct author was passed to git.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46227)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger ut9

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 117 at r2](https://reviewable.io/reviews/harness/harness-core/46227#-NTXhK7v3gmdZmy5hvzf:-NTXhK7v3gmdZmy5hvzg:bwhheor) ([raw file](https://github.com/harness/harness-core/blob/ac956d0c697aa9a736c7e059d2a3f81bfbbbc065/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L117)):*
> ```Java
>     if (isFailureResponse(userDetailsResponse.getStatusCode())) {
>       log.error("Error in getting user details from SCM: {}", userDetailsResponse);
>       scmErrorHandler.processAndThrowException(userDetailsResponse.getStatusCode(),
> ```

we cannot use scmErrorHandler on consumer clients which use git-service.



_Code quote:_
```Java
ScmErrorHandler
```

**Comment by shalini-agr** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 117 at r2](https://reviewable.io/reviews/harness/harness-core/46227#-NTXhK7v3gmdZmy5hvzf:-NTXm1SC2CC5oFqcEOb9:b-tqd3vd) ([raw file](https://github.com/harness/harness-core/blob/ac956d0c697aa9a736c7e059d2a3f81bfbbbc065/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L117)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we cannot use scmErrorHandler on consumer clients which use git-service.
</blockquote></details>

I see for other methods, we have written a method in SCMGitSyncHelper and we are calling that method from other places, should we also do something like that?

**Comment by shalini-agr** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 117 at r2](https://reviewable.io/reviews/harness/harness-core/46227#-NTXhK7v3gmdZmy5hvzf:-NTXuPJ_9yquqtCkzwWo:bk7e7sh) ([raw file](https://github.com/harness/harness-core/blob/ac956d0c697aa9a736c7e059d2a3f81bfbbbc065/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L117)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

I see for other methods, we have written a method in SCMGitSyncHelper and we are calling that method from other places, should we also do something like that?
</blockquote></details>

have created a utility class SCMErrorHandler in consumer service.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 38 files at r1, 40 of 41 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46227)* status: 43 file(s) to review. 1 of 2 approvals obtained.

**Review by senjucanon2 — COMMENTED** [review]
> Reviewed 1 of 38 files at r1, 10 of 41 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46227)* status: 30 file(s) to review. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/AbstractScmClientFacilitatorServiceImpl.java` line 208 at r4](https://reviewable.io/reviews/harness/harness-core/46227#-NTYsksxEisTuEbxFm4b:-NTYsksxEisTuEbxFm4c:b-vnp686) ([raw file](https://github.com/harness/harness-core/blob/5ad41f6c83271ff8fa24e169f90a00031ef7317f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/AbstractScmClientFacilitatorServiceImpl.java#L208)):*
> ```Java
>   GitFileDetails getGitFileDetails(
>       UpdateGitFileRequestDTO updateGitFileRequestDTO, Optional<UserDetailsResponseDTO> userDTO) {
>     final EmbeddedUser currentUser = ScmUserHelper.getCurrentUser();
> ```

Please check once if "ScmUserHelper.getCurrentUser()" handles null case

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46227)* status: 30 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/AbstractScmClientFacilitatorServiceImpl.java` line 208 at r4](https://reviewable.io/reviews/harness/harness-core/46227#-NTYsksxEisTuEbxFm4b:-NTYtX-jAzVzhQxhLNRn:b-1kauv5) ([raw file](https://github.com/harness/harness-core/blob/5ad41f6c83271ff8fa24e169f90a00031ef7317f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/AbstractScmClientFacilitatorServiceImpl.java#L208)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Please check once if "ScmUserHelper.getCurrentUser()" handles null case
</blockquote></details>

it does. This method returns user details from principal, if principal can't be found, default values are returned.
all this logic was already there.

**Review by senjucanon2 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46227)* status: 30 file(s) to review.

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
