### PR TITLE
[fix]: [PL-28560]: Added Enum for sorting in new Resource Group APIs

### PR DESCRIPTION
**Pull request by mankrit-singh**
## Describe your changes
Added Enum for sorting in new Resource Group APIsAdded Enum for sorting in new Resource Group APIs

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38117)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38117)

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38117)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v3/mapper/ResourceGroupApiUtils.java` line 279 at r1](https://reviewable.io/reviews/harness/harness-core/38117#-ND7Gl3KBxfECItpQThg:-ND7Gl3KBxfECItpQThh:b-k0dp62) ([raw file](https://github.com/harness/harness-core/blob/d8664387742d9adb710d86cd72bfe5c9bd7b4e8e/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v3/mapper/ResourceGroupApiUtils.java#L279)):*
> ```Java
>     }
>     if (order == null || (!order.equalsIgnoreCase("asc") && !order.equalsIgnoreCase("desc"))) {
>       throw new InvalidRequestException("Order of sorting unidentified or null.");
> ```

Mention supported values in the error message
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v3/mapper/ResourceGroupApiUtils.java` line 282 at r1](https://reviewable.io/reviews/harness/harness-core/38117#-ND7Gb_Z4lu6ic7w0RP7:-ND7Gb_Z4lu6ic7w0RP8:b6hxw14) ([raw file](https://github.com/harness/harness-core/blob/d8664387742d9adb710d86cd72bfe5c9bd7b4e8e/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v3/mapper/ResourceGroupApiUtils.java#L282)):*
> ```Java
>     }
>     if (field == null) {
>       throw new InvalidRequestException("Field provided for sorting is null, while order is not.");
> ```

nit, we can also ignore if no field is provided
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v3/mapper/ResourceGroupApiUtils.java` line 297 at r1](https://reviewable.io/reviews/harness/harness-core/38117#-ND7GqdAA-2jmi2RrRp7:-ND7GqdAA-2jmi2RrRp8:b-kcjt7h) ([raw file](https://github.com/harness/harness-core/blob/d8664387742d9adb710d86cd72bfe5c9bd7b4e8e/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v3/mapper/ResourceGroupApiUtils.java#L297)):*
> ```Java
>         break;
>       default:
>         throw new InvalidRequestException("Field provided for sorting unidentified.");
> ```

nit, mention supported fields in error message.

**Comment by mankrit-singh** [comment]
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v3/mapper/ResourceGroupApiUtils.java` line 279 at r1](https://reviewable.io/reviews/harness/harness-core/38117#-ND7Gl3KBxfECItpQThg:-ND7JI8PAD_4TznILGqb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d8664387742d9adb710d86cd72bfe5c9bd7b4e8e/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v3/mapper/ResourceGroupApiUtils.java#L279)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Mention supported values in the error message
</blockquote></details>

Done.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38117)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by TarunUba1 — APPROVED** [review]

**Review by reetika04 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38117)* status: :shipit: complete! ✓

**Pull request merged**
