### PR TITLE
feat: [CDS-85944]: support envs to move inline to remote

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
added a new API in Env Resource v2 to allow moving envs from inline to remote. Added UT for the same. 

Tested moving Inline environments of pre prod and prod types. Opening the env on UI. 
image

image

image

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56303)

### CODE REVIEW

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 1203 at r2](https://reviewable.io/reviews/harness/harness-core/56303#-Nl2D8SA--5Klzgk-ah1:-Nl2D8SA--5Klzgk-ah2:b5px3wi) ([raw file](https://github.com/harness/harness-core/blob/9456d736dd4362900ddac9f4d035fb63ad5deb16/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L1203)):*
> ```Java
>       {
>         @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "default",
>             description = "Fetches Environment YAML from Harness DB and creates a remote entity")
> ```

Description need not be this specific. We can just say "moved environment from inline to remote" or something similar

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentMoveConfigOperationDTO.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/56303#-Nl2DIEE6_IXOPcPTRrT:-Nl2DIEE6_IXOPcPTRrU:bx24kd7) ([raw file](https://github.com/harness/harness-core/blob/9456d736dd4362900ddac9f4d035fb63ad5deb16/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentMoveConfigOperationDTO.java#L29)):*
> ```Java
>   String commitMessage;
>   boolean isNewBranch;
>   MoveConfigOperationType moveConfigOperationType;
> ```

If we expose to open API, it wil be good to put NotNull annotations on field. Also, can this be @Value instead of @Data ? Fields should be immutable

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentMoveConfigRequestDTO.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/56303#-Nl2Df_w7kUuD_zlS7D4:-Nl2Df_w7kUuD_zlS7D5:bnxle0a) ([raw file](https://github.com/harness/harness-core/blob/9456d736dd4362900ddac9f4d035fb63ad5deb16/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentMoveConfigRequestDTO.java#L59)):*
> ```Java
>   @Parameter(description = GitSyncApiConstants.MOVE_CONFIG_PARAM_MESSAGE)
>   @QueryParam(GitSyncApiConstants.MOVE_CONFIG_KEY)
>   MoveConfigOperationType moveConfigOperationType;
> ```

If we expose to open API, it wil be good to put NotNull annotations on field. Also, can this be [@value](https://github.com/value) instead of [@DaTa](https://github.com/DaTa) ? Fields should be immutable

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentMoveConfigRequestDTO.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/56303#-Nl2DnUV2koUWNSFFkqZ:-Nl2DnUV2koUWNSFFkq_:b-7s0k3e) ([raw file](https://github.com/harness/harness-core/blob/9456d736dd4362900ddac9f4d035fb63ad5deb16/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentMoveConfigRequestDTO.java#L46)):*
> ```Java
>   @QueryParam(GitSyncApiConstants.FILE_PATH_KEY)
>   String filePath;
>   @Parameter(description = GitSyncApiConstants.FILEPATH_PARAM_MESSAGE)
> ```

typo here ?



_Code quote:_
```Java
@Parameter(description = GitSyncApiConstants.FILEPATH_PARAM_MESSAGE)
```

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentMoveConfigRequestDTO.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/56303#-Nl2DrABCWFg6oel_mHS:-Nl2DrABCWFg6oel_mHT:b-o4r8pl) ([raw file](https://github.com/harness/harness-core/blob/9456d736dd4362900ddac9f4d035fb63ad5deb16/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentMoveConfigRequestDTO.java#L49)):*
> ```Java
>   @QueryParam(GitSyncApiConstants.COMMIT_MSG_KEY)
>   String commitMsg;
>   @Parameter(description = "Checks the new branch")
> ```

this is not clear



_Code quote:_
```Java
"Checks the new branch")
```

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentMoveConfigResponse.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/56303#-Nl2DwZp-v9WpsEDgvxU:-Nl2DwZp-v9WpsEDgvxV:b6v3vxr) ([raw file](https://github.com/harness/harness-core/blob/9456d736dd4362900ddac9f4d035fb63ad5deb16/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentMoveConfigResponse.java#L30)):*
> ```Java
> @OwnedBy(CDC)
> public class EnvironmentMoveConfigResponse {
>   @Schema(description = "Contains the environmentIdentifier of the successfully moved config.", hidden = true)
> ```

should we say "environment" instead of "config" ? also, do we need to hide it ?



_Code quote:_
```Java
config.
```

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1139 at r2](https://reviewable.io/reviews/harness/harness-core/56303#-Nl2EBNO0MSfwVD6K7zf:-Nl2EBNO0MSfwVD6K7zg:b-a5etxh) ([raw file](https://github.com/harness/harness-core/blob/9456d736dd4362900ddac9f4d035fb63ad5deb16/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1139)):*
> ```Java
>   }
> 
>   private void validateMoveConfigRequest(EnvironmentMoveConfigOperationDTO moveConfigOperationDTO) {
> ```

We can use Javax validation for this ?

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1122 at r2](https://reviewable.io/reviews/harness/harness-core/56303#-Nl2EIGzB6Z6eqVtX7_X:-Nl2EIGzB6Z6eqVtX7_Y:b-8iytys) ([raw file](https://github.com/harness/harness-core/blob/9456d736dd4362900ddac9f4d035fb63ad5deb16/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1122)):*
> ```Java
> 
>     Optional<Environment> environment =
>         getMetadata(accountIdentifier, orgIdentifier, projectIdentifier, environmentIdentifier, false);
> ```


better to return if environment is not present. Then continue with regular code. This will avoid nesting 
```
if (environment not present) {
   // throw
}

// move
```

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 12 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56303)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56303)* status: 9 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 1205 at r2](https://reviewable.io/reviews/harness/harness-core/56303#-Nl2YtKgAHaenqZp35hv:-Nl2YtKgAHaenqZp35hw:b-p4fbi9) ([raw file](https://github.com/harness/harness-core/blob/9456d736dd4362900ddac9f4d035fb63ad5deb16/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L1205)):*
> ```Java
>             description = "Fetches Environment YAML from Harness DB and creates a remote entity")
>       })
>   @Hidden
> ```

If its Hidden, then we shouldn't even be adding any swagger annotations. Why is it hidden?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56303)* status: 9 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1125 at r2](https://reviewable.io/reviews/harness/harness-core/56303#-Nl2ZpQ_3TUrlCLJNz0o:-Nl2ZpQ_3TUrlCLJNz0p:b-jngvmk) ([raw file](https://github.com/harness/harness-core/blob/9456d736dd4362900ddac9f4d035fb63ad5deb16/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1125)):*
> ```Java
> 
>     if (environment.isPresent()) {
>       if (StoreType.REMOTE.equals(environment.get().getStoreType())) {
> ```

it also needs a check on the operationType, whether its inline to remote or remote to inline. Only for inline to remote this condition should satisfy.

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56303)* status: 9 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1157 at r2](https://reviewable.io/reviews/harness/harness-core/56303#-Nl2_3duCETPYBlSSMsy:-Nl2_3duCETPYBlSSMsz:bohcnb7) ([raw file](https://github.com/harness/harness-core/blob/9456d736dd4362900ddac9f4d035fb63ad5deb16/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1157)):*
> ```Java
>   }
> 
>   private void throwInvalidRequestForEmptyField(String fieldName) {
> ```

looks like a good generic utility, can be moved to some utility / helper class so that it can be used more going forward.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56303)* status: 9 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 320 at r2](https://reviewable.io/reviews/harness/harness-core/56303#-Nl2a0pg6F7eDsRGL9hv:-Nl2a0pg6F7eDsRGL9hw:b-citrlb) ([raw file](https://github.com/harness/harness-core/blob/9456d736dd4362900ddac9f4d035fb63ad5deb16/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L320)):*
> ```Java
>     } else {
>       throw new UnsupportedOperationException(String.format(
>           "Move operation:[%s] not supported for environments", moveConfigOperationDTO.getMoveConfigOperationType()));
> ```

make sure that our api docs mention only INLINE TO REMOTE in the enum, otherwise you will start failing for other valid enum values as well mentioned in the doc.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56303)* status: 9 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 319 at r2](https://reviewable.io/reviews/harness/harness-core/56303#-Nl2aAID4cERkVOJhMXs:-Nl2aAID4cERkVOJhMXt:bbsqxq8) ([raw file](https://github.com/harness/harness-core/blob/9456d736dd4362900ddac9f4d035fb63ad5deb16/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L319)):*
> ```Java
>       return moveToRemote(criteria, environmentToUpdate);
>     } else {
>       throw new UnsupportedOperationException(String.format(
> ```

This check should be in service layer itself, not in repository layer.

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56303)* status: 9 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 475 at r2](https://reviewable.io/reviews/harness/harness-core/56303#-Nl2a_iI4-j7dmNC4MXz:-Nl2a_iI4-j7dmNC4MY-:b-mvhpl0) ([raw file](https://github.com/harness/harness-core/blob/9456d736dd4362900ddac9f4d035fb63ad5deb16/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L475)):*
> ```Java
>         gitAwareEntityHelper.getRepoUrl(serviceEntity.getAccountIdentifier(), serviceEntity.getOrgIdentifier(),
>             serviceEntity.getProjectIdentifier()));
>     update.set(ServiceEntityKeys.fallBackBranch, serviceEntity.getFallBackBranch());
> ```

Actually the earlier check looks correct to me. We have only 1 branch during whole operation and that becomes the fallback branch automatically.

**Comment by hingerabhinav** [comment]
Closing this as we've moved to harness code.

**Pull request closed without merging**
