### PR TITLE
fix: [CDS-37205]: Bitbucket optimized Git fetch file(enabling scm for butbucket as well)

### PR DESCRIPTION
**Pull request by TarunUba1**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35827)

### CODE REVIEW

**Comment by TarunUba1** [comment]
1. Implemented Scm connection optimised fetch file for Bitbucket connection in both CG and NG
2. No new classes were added for the commit

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35827)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 271 at r2](https://reviewable.io/reviews/harness/harness-core/35827#-N8Nu0nTD0szZ3Mz5hzB:-N8Nu0nTD0szZ3Mz5hzC:bdgz1kw) ([raw file](https://github.com/harness/harness-core/blob/628cd99f95a9a23ca8e5b8399f2bac46a2c6660b/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L271)):*
> ```Java
>         && isBitbucketUsernameTokenAuth((BitbucketConnectorDTO) scmConnector)) {
>       BitbucketConnectorDTO bitbucketConnectorDTO = (BitbucketConnectorDTO) scmConnector;
>       SecretRefData tokenRef =
> ```

let assign `BitbucketUsernamePasswordDTO` to a variable, instead of doing so many object casting on the fly, repetatively.



_Code quote:_
```Java
      SecretRefData tokenRef =
          ((BitbucketUsernamePasswordDTO) ((BitbucketHttpCredentialsDTO) bitbucketConnectorDTO.getAuthentication()
                                               .getCredentials())
                  .getHttpCredentialsSpec())
              .getPasswordRef();
      String usernameRef =
          ((BitbucketUsernamePasswordDTO) ((BitbucketHttpCredentialsDTO) bitbucketConnectorDTO.getAuthentication()
                                               .getCredentials())
                  .getHttpCredentialsSpec())
              .getUsername();
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 279 at r2](https://reviewable.io/reviews/harness/harness-core/35827#-N8NuMX83SHm_Uyvl0Iq:-N8NuMX83SHm_Uyvl0Ir:b-63v55t) ([raw file](https://github.com/harness/harness-core/blob/628cd99f95a9a23ca8e5b8399f2bac46a2c6660b/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L279)):*
> ```Java
>           ((BitbucketUsernamePasswordDTO) ((BitbucketHttpCredentialsDTO) bitbucketConnectorDTO.getAuthentication()
>                                                .getCredentials())
>                   .getHttpCredentialsSpec())
> ```

extract this to different method.



_Code quote:_
```Java
      BitbucketConnectorDTO bitbucketConnectorDTO = (BitbucketConnectorDTO) scmConnector;
      SecretRefData tokenRef =
          ((BitbucketUsernamePasswordDTO) ((BitbucketHttpCredentialsDTO) bitbucketConnectorDTO.getAuthentication()
                                               .getCredentials())
                  .getHttpCredentialsSpec())
              .getPasswordRef();
      String usernameRef =
          ((BitbucketUsernamePasswordDTO) ((BitbucketHttpCredentialsDTO) bitbucketConnectorDTO.getAuthentication()
                                               .getCredentials())
                  .getHttpCredentialsSpec())
              .getUsername();

      BitbucketApiAccessDTO apiAccessDTO =
          BitbucketApiAccessDTO.builder()
              .type(USERNAME_AND_TOKEN)
              .spec(BitbucketUsernameTokenApiAccessDTO.builder()
                        .tokenRef(tokenRef)
                        .usernameRef(SecretRefData.builder().decryptedValue(usernameRef.toCharArray()).build())
                        .build())
              .build();
      bitbucketConnectorDTO.setApiAccess(apiAccessDTO);
```

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35827)

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35827)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 271 at r2](https://reviewable.io/reviews/harness/harness-core/35827#-N8Nu0nTD0szZ3Mz5hzB:-N8WlnKm3xZikrZGFjem:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/628cd99f95a9a23ca8e5b8399f2bac46a2c6660b/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L271)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

let assign `BitbucketUsernamePasswordDTO` to a variable, instead of doing so many object casting on the fly, repetatively.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 279 at r2](https://reviewable.io/reviews/harness/harness-core/35827#-N8NuMX83SHm_Uyvl0Iq:-N8WlmjFAkc05WEWEwJj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/628cd99f95a9a23ca8e5b8399f2bac46a2c6660b/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L279)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

extract this to different method.
</blockquote></details>

Done.

**Comment by TarunUba1** [comment]
trigger messagecheck

**Comment by TarunUba1** [comment]
trigger messagecheck

**Comment by TarunUba1** [comment]
old-Pr-raised new PR and merged

**Pull request closed without merging**
