### PR TITLE
[feat]: [CDS-38570]: Added hard delete for templates

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34116)

### CODE REVIEW

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34116)* status: 1 change requests. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/34116#-N4BNYtT3yvlgd8LO2wE:-N4BNYtT3yvlgd8LO2wF:b-lravr0) (no related file):*
Do add manager client baseurl config override to all environments. Reference ticket: https://harness.atlassian.net/browse/CDS-37249

___
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 414 at r3](https://reviewable.io/reviews/harness/harness-core/34116#-N4BO9cY0P7filcdyTGw:-N4BO9cY0P7filcdyTGx:b-zb3nh9) ([raw file](https://github.com/harness/harness-core/blob/afd3a8c58f577251568982cd72f6e393a741cb57/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L414)):*
> ```Java
>           templateIdentifier, versionLabel, projectIdentifier, orgIdentifier));
>     }
>     TemplateEntity withDeleted = templateToDelete.withLastUpdatedTemplate(false).withDeleted(true);
> ```

We shouldn't do this for templates to hard delete.



_Code snippet:_
```Java
TemplateEntity withDeleted = templateToDelete.withLastUpdatedTemplate(false).withDeleted(true);
```

**Review by inderschera — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34116)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34116)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 414 at r3](https://reviewable.io/reviews/harness/harness-core/34116#-N4BO9cY0P7filcdyTGw:-N4QTXHL3KxeWybprmIa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/afd3a8c58f577251568982cd72f6e393a741cb57/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L414)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

We shouldn't do this for templates to hard delete.
</blockquote></details>

Done.

**Review by inderschera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34116)* status: :shipit: complete! ✓

**Pull request merged**
