### PR TITLE
[fix]: [PL-24474]: Improve debugging experience for SAML

### PR DESCRIPTION
**Pull request by boopesh007**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35634)

### CODE REVIEW

**Comment by boopesh007** [comment]
trigger messagecheck

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fRu0x0sKRQVLKiJj2:-N7fRu0x0sKRQVLKiJj3:b7sg03x) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L175)):*
> ```Java
>       userGroupService.update(userGroupDTO);
>     }
>     log.info("NGSCCIM: Member userIds provided by the SCIM Provider are {}, for account {}",
> ```

NGSCIM?



_Code quote:_
```Java
NGSCCIM
```

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 207 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fTbQ50xlWRBSYJHHO:-N7fTbQ50xlWRBSYJHHP:bi6ivlw) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L207)):*
> ```Java
> 
>   private String processReplaceOperationOnGroup(String groupId, String accountId, PatchOperation patchOperation) {
>     log.info("NGSCIM: Patch Operation Path is {}", patchOperation.getPath());
> ```

add accountId

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 215 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fTdDM-IQWrWf1zmLp:-N7fTdDM-IQWrWf1zmLq:bi6ivlw) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L215)):*
> ```Java
>     } else {
>       try {
>         log.info("NGSCIM: Patch Operation Value is {}", patchOperation.getValue(String.class));
> ```

add accountId

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 215 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fTttt7BvbRXTtuN_n:-N7fTttt7BvbRXTtuN_o:bvtpy32) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L215)):*
> ```Java
>     } else {
>       try {
>         log.info("NGSCIM: Patch Operation Value is {}", patchOperation.getValue(String.class));
> ```

delete this

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 207 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fUbx_EXB2cBvhc3FO:-N7fUbx_EXB2cBvhc3FP:bvtpy32) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L207)):*
> ```Java
> 
>   private String processReplaceOperationOnGroup(String groupId, String accountId, PatchOperation patchOperation) {
>     log.info("NGSCIM: Patch Operation Path is {}", patchOperation.getPath());
> ```

delete this

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 228 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fUzMdBxB1yYS8FbEk:-N7fUzMdBxB1yYS8FbEl:bvtpy32) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L228)):*
> ```Java
>     try {
>       if (patchOperation.getValue(ScimMultiValuedObject.class) != null) {
>         log.info("NGSCIM: Display name for the patch operation is {}",
> ```

delete this



_Code quote:_
```Java
processOktaReplaceOperationOnGroup
```

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 243 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fV2cyCvYtcdvuBo3F:-N7fV2cyCvYtcdvuBo3G:bixlu09) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L243)):*
> ```Java
>     String operation = isNotEmpty(patchRequest.getOperations()) ? patchRequest.getOperations().toString() : null;
>     String schemas = isNotEmpty(patchRequest.getSchemas()) ? patchRequest.getSchemas().toString() : null;
>     log.info("NGSCIM: Patch Request Logging\nOperations {}\n, Schemas {}\n,External Id {}\n, Meta {}", operation,
> ```

add accountId here and also in ScimGroupServiceImpl

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 315 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fVVqE3AkxwTOmhGpO:-N7fVVqE3AkxwTOmhGpP:b-97bkil) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L315)):*
> ```Java
>   private void updateNewMemberIds(Set<String> userIdsFromOperation, Set<String> newMemberIds, String accountId) {
>     log.info("NGSCIM: User Ids received from SCIM provider are {}, for accountId {}",
>         String.join(",", userIdsFromOperation), accountId);
> ```

String.join not needed.
print Set directly

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fW_gLBu43hawjpFpz:-N7fW_gLBu43hawjpFq-:b15lyx) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java#L51)):*
> ```Java
>           .build();
>     } catch (Exception ex) {
>       log.info("NGSCIM: Failed to create the group, for accountId {}, Exception is", accountIdentifier, ex);
> ```

log.error



_Code quote:_
```Java
Failed to create the group,
```

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fWkZv0WsV141dtvC7:-N7fWkZv0WsV141dtvC8:b-7qz7q5) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java#L66)):*
> ```Java
>           .build();
>     } catch (Exception ex) {
>       log.info("NGSCIM: Failed to fetch the groups with id: {}, for accountId {}, Exception is", groupIdentifier,
> ```

error

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fWmQC6v-kK0-rsTw1:-N7fWmQC6v-kK0-rsTw2:b-7qz7q5) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java#L51)):*
> ```Java
>           .build();
>     } catch (Exception ex) {
>       log.info("NGSCIM: Failed to create the group, for accountId {}, Exception is", accountIdentifier, ex);
> ```

error

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/ScimGroupResource.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fWsDJ2owLv8OqpTwC:-N7fWsDJ2owLv8OqpTwD:b-7qz7q5) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/resources/ScimGroupResource.java#L50)):*
> ```Java
>       return Response.status(Status.CREATED).entity(scimGroupService.createGroup(groupQuery, accountId)).build();
>     } catch (Exception ex) {
>       log.info("SCIM: Failed to create the group {}, for accountId {}", groupQuery.getDisplayName(), accountId, ex);
> ```

error

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/ScimGroupResource.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fWt93EgKXL_FLT8PH:-N7fWt93EgKXL_FLT8PI:b-7qz7q5) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/resources/ScimGroupResource.java#L62)):*
> ```Java
>       return Response.status(Response.Status.OK).entity(scimGroupService.getGroup(groupId, accountId)).build();
>     } catch (Exception ex) {
>       log.info("SCIM: Failed to fetch the groups with id: {}, for accountId {}", groupId, accountId, ex);
> ```

error

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/ScimGroupResource.java` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fWub35i-Z3V3Bnjxp:-N7fWub35i-Z3V3Bnjxq:b-7qz7q5) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/resources/ScimGroupResource.java#L112)):*
> ```Java
>       return scimGroupService.updateGroup(groupId, accountId, groupQuery);
>     } catch (Exception ex) {
>       log.info("SCIM: Failed to update the group with id: {}, accountId {} ", groupId, accountId, ex);
> ```

error

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java` line 101 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fWyqe8qi7yztpMOtY:-N7fWyqe8qi7yztpMOtZ:b-81qe1m) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java#L101)):*
> ```Java
>     searchGroupResponse.itemsPerPage(count);
>     searchGroupResponse.totalResults(groupList.size());
>     log.info("NGSCIM: Search Group Response is {}, for accountId {}",
> ```

SCIM?

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java` line 170 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fXF21C1TTKb4LXjNp:-N7fXF21C1TTKb4LXjNq:b-rtagwg) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java#L170)):*
> ```Java
> 
>   private String processReplaceOperationOnGroup(String groupId, String accountId, PatchOperation patchOperation) {
>     log.info("SCIM: Replace operation received on path {}, for accountId {}", patchOperation.getPath(), accountId);
> ```

delete



_Code quote:_
```Java
searchGroupResponse.getResources()
```

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java` line 179 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fXKUzBIY3TBf2R4zC:-N7fXKUzBIY3TBf2R4zD:b-rtagwg) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java#L179)):*
> ```Java
>       try {
>         log.info(
>             "SCIM: Patch operation value is {}, for accountId {}", patchOperation.getValue(String.class), accountId);
> ```

delete

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java` line 192 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fXNEw3cC-_wzOSAnc:-N7fXNEw3cC-_wzOSAnd:b-rtagwg) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java#L192)):*
> ```Java
>     try {
>       if (patchOperation.getValue(ScimMultiValuedObject.class) != null) {
>         log.info("SCIM: Display name from the patch operation is {}, for accountId {}",
> ```

delete

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java` line 267 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fXQ959AwRYv8B1PkC:-N7fXQ959AwRYv8B1PkD:b-6pvzfn) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java#L267)):*
> ```Java
> 
>   private void updateNewMemberIds(Set<String> userIdsFromOperation, Set<String> newMemberIds, String accountId) {
>     log.info("NGSCIM: User Ids received from SCIM provider are {}, for accountId {}",
> ```

SCIM instead of NGSCIM.

Also, String.join not required

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java` line 664 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fZ-_479sI4MxUAk0e:-N7fZ-_479sI4MxUAk0f:b-oxsvp3) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java#L664)):*
> ```Java
>       userGroups.add(groupIdValues.getString(i));
>     }
>     log.info("SAML: User groups fetched are {}, for accountId {}", userGroups);
> ```

missing accountId

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/security/saml/SamlUserGroupSync.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fZ4JB0qYfQcaf0a3l:-N7fZ4JB0qYfQcaf0a3m:b-8pnvnb) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/security/saml/SamlUserGroupSync.java#L37)):*
> ```Java
>   public void syncUserGroup(
>       final SamlUserAuthorization samlUserAuthorization, final String accountId, final String ssoId) {
>     log.info("SAML: Syncing saml user groups for user: {}", samlUserAuthorization.getEmail());
> ```

accountId missing

**Review by shashank-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35634)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by boopesh007** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fRu0x0sKRQVLKiJj2:-N7lxD7S3WC6yAtoRxvB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L175)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

NGSCIM?
</blockquote></details>

Done.



_Code quote:_
```Java
"NGSCIM: Patch Operation Path is
```

**Comment by boopesh007** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 207 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fUbx_EXB2cBvhc3FO:-N7lxnl80w790EM-J0Jm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L207)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

delete this
</blockquote></details>

Done.

**Comment by boopesh007** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 215 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fTttt7BvbRXTtuN_n:-N7lxyIdDgZU7X0jEe7V:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L215)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

delete this
</blockquote></details>

Done.

**Comment by boopesh007** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 228 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fUzMdBxB1yYS8FbEk:-N7ly8CH1xFwoCiXDHJu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L228)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

delete this
</blockquote></details>

Done.



_Code quote:_
```Java
NGSCIM: Display name for the patch operation
```

**Comment by boopesh007** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 243 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fV2cyCvYtcdvuBo3F:-N7lyR8W50VcOJCqLi1u:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L243)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

add accountId here and also in ScimGroupServiceImpl
</blockquote></details>

Done.



_Code quote:_
```Java
NGSCIM: Patch Request Logging\nO
```

**Comment by boopesh007** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 315 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fVVqE3AkxwTOmhGpO:-N7lyb6qAgcpX64et0Le:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L315)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

String.join not needed.
print Set directly
</blockquote></details>

Done.



_Code quote:_
```Java
NGSCIM: User Ids received from SCIM provider
```

**Comment by boopesh007** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fWmQC6v-kK0-rsTw1:-N7lyol86KYSGibvTD_s:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java#L51)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

error
</blockquote></details>

Done.

**Comment by boopesh007** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fWkZv0WsV141dtvC7:-N7lyvu3-sa8f12zf-UM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java#L66)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

error
</blockquote></details>

Done.



_Code quote:_
```Java
NGSCIM: Failed to fetch the groups with id
```

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/resources/ScimGroupResource.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fWsDJ2owLv8OqpTwC:-N7lzEUXB2yLiijHpKw_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/resources/ScimGroupResource.java#L50)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

error
</blockquote></details>

Done.



_Code quote:_
```Java
SCIM: Failed to create the group
```

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/resources/ScimGroupResource.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fWt93EgKXL_FLT8PH:-N7lzLiiC-y7oDqQB2wE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/resources/ScimGroupResource.java#L62)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

error
</blockquote></details>

Done.



_Code quote:_
```Java
SCIM: Failed to fetch the groups with i
```

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/resources/ScimGroupResource.java` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fWub35i-Z3V3Bnjxp:-N7lzTKd0snDxve58Yrq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/resources/ScimGroupResource.java#L112)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

error
</blockquote></details>

Done.



_Code quote:_
```Java
SCIM: Failed to update the group with id
```

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java` line 101 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fWyqe8qi7yztpMOtY:-N7lzcU7AYOlzGh1jGck:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java#L101)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

SCIM?
</blockquote></details>

Done.



_Code quote:_
```Java
NGSCIM: Search Group Response is
```

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java` line 170 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fXF21C1TTKb4LXjNp:-N7lzmmS7lDAiliu_9Sc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java#L170)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.



_Code quote:_
```Java
SCIM: Replace operation received on path
```

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java` line 179 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fXKUzBIY3TBf2R4zC:-N7lzwsvDhcVasmKZYg8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java#L179)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.



_Code quote:_
```Java
"SCIM: Patch operation value is
```

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java` line 192 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fXNEw3cC-_wzOSAnc:-N7m-9os0G8ugxbJo4o8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java#L192)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.



_Code quote:_
```Java
SCIM: Display name from the patch operation is
```

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java` line 267 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fXQ959AwRYv8B1PkC:-N7m-KxQ5xgfPyeGcNrN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java#L267)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

SCIM instead of NGSCIM.

Also, String.join not required
</blockquote></details>

Done.



_Code quote:_
```Java
NGSCIM: User Ids received from SCIM provider 
```

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java` line 664 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fZ-_479sI4MxUAk0e:-N7m-Wvr3wT9RSPXVgMS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java#L664)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

missing accountId
</blockquote></details>

Done.



_Code quote:_
```Java
SAML: User groups fetched are
```

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/security/saml/SamlUserGroupSync.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/35634#-N7fZ4JB0qYfQcaf0a3l:-N7m06CZE2y7Z1yZCPCQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f373d537655b480f028e5f808c31ba5d54153f04/400-rest/src/main/java/software/wings/security/saml/SamlUserGroupSync.java#L37)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

accountId missing
</blockquote></details>

Done.



_Code quote:_
```Java
SAML: Syncing saml user groups for user
```

**Review by shashank-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35634#-:-N7yRVaM5XkMn0UqC1JP:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35634)* status: :shipit: complete! ✓

**Pull request merged**
