### PR TITLE
fix:[CDS-58979] Pump the build number

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- It fixes a problem to apply filter for all artifact source not only for gcs when the FF SPG_ALLOW_FILTER_BY_PATHS_GCS enabled.
Its impacting the deployment re-run page and the artifactory history list.

image

image

- Fix Google Cloud Build and secret usage on workflow context

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46394)

### CODE REVIEW

**Comment by Fernando-Dourado** [comment]
trigger messagecheck

**Review by raghuAtWings — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46394)* status: 11 file(s) to review. 0 of 2 approvals obtained. 

___
*[`957-cg-beans/src/main/java/software/wings/helpers/ext/gcb/models/GcbBuildDetails.java` line 57 at r7](https://reviewable.io/reviews/harness/harness-core/46394#-NSw2NHK9ZF6t_5VhUIi:-NSw2NHK9ZF6t_5VhUIj:b-xkamrn) ([raw file](https://github.com/harness/harness-core/blob/e94be72387b7cbd512570c9cb790a5be20db2edf/957-cg-beans/src/main/java/software/wings/helpers/ext/gcb/models/GcbBuildDetails.java#L57)):*
> ```Java
>   private Map<String, String> substitutions;
>   private List<String> tags;
>   private List<Map<String, Object>> secrets;
> ```

Why object?

**Comment by rafaelmart1ns** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/46394)_ status: 11 file(s) to review. 0 of 2 approvals obtained.
> 
> _[`957-cg-beans/src/main/java/software/wings/helpers/ext/gcb/models/GcbBuildDetails.java` line 57 at r7](https://reviewable.io/reviews/harness/harness-core/46394#-NSw2NHK9ZF6t_5VhUIi:-NSw2NHK9ZF6t_5VhUIj:b-xkamrn) ([raw file](https://github.com/harness/harness-core/blob/e94be72387b7cbd512570c9cb790a5be20db2edf/957-cg-beans/src/main/java/software/wings/helpers/ext/gcb/models/GcbBuildDetails.java#L57)):_
> 
> > ```java
> >   private Map<String, String> substitutions;
> >   private List<String> tags;
> >   private List<Map<String, Object>> secrets;
> > ```
> 
> Why object?

this can be string or a hashmap

**Comment by rafaelmart1ns** [comment]
> Why object?

this can be string or a hashmap

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46394)* status: 11 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sribalij — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46394)* status: 1. unresolved discussions.

**Pull request merged**
