### PR TITLE
feat: [PL-23707]: Adding logs and retry to webhook registration

### PR DESCRIPTION
**Pull request by mohitg0795**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31447)

### CODE REVIEW

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31447)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31447)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 653 at r1](https://reviewable.io/reviews/harness/harness-core/31447#-MyCLc7_38dUMWB-R4u-:-MyCLc7_38dUMWB-R4u0:bj2em39) ([raw file](https://github.com/harness/harness-core/blob/e9949ee8b3e22ce94512eaec471af334d17dcb0b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L653)):*
> ```Java
>         .handle(Exception.class)
>         .withMaxAttempts(2)
>         .onFailedAttempt(event -> log.info(failedAttemptMessage, event.getAttemptCount(), event.getLastFailure()))
> ```

Can we add some text here like

The attempt no {} failed with the error {},

Otherwise with this existing format how we will search for this log ?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 654 at r1](https://reviewable.io/reviews/harness/harness-core/31447#-MyCLnd50jtLm0exMOTY:-MyCLnd50jtLm0exMOTZ:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/e9949ee8b3e22ce94512eaec471af334d17dcb0b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L654)):*
> ```Java
>         .withMaxAttempts(2)
>         .onFailedAttempt(event -> log.info(failedAttemptMessage, event.getAttemptCount(), event.getLastFailure()))
>         .onFailure(event -> log.error(failureMessage, event.getAttemptCount(), event.getFailure()));
> ```

same

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31447)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 653 at r1](https://reviewable.io/reviews/harness/harness-core/31447#-MyCLc7_38dUMWB-R4u-:-MyCSCg409L1cCuO2vhp:b-geemie) ([raw file](https://github.com/harness/harness-core/blob/e9949ee8b3e22ce94512eaec471af334d17dcb0b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L653)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Can we add some text here like

The attempt no {} failed with the error {},

Otherwise with this existing format how we will search for this log ?
</blockquote></details>

The message is passed as argument, it has all these things.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 654 at r1](https://reviewable.io/reviews/harness/harness-core/31447#-MyCLnd50jtLm0exMOTY:-MyCSG20-_uCt_0j9SES:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/e9949ee8b3e22ce94512eaec471af334d17dcb0b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L654)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

same
</blockquote></details>

same

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31447)* status: :shipit: complete! ✓

**Pull request merged**
