### PR TITLE
[feat]: [CDS-50733]: proxy added in download artifact

### PR DESCRIPTION
**Pull request by vladimir-peric**
We added support for using proxy settings on the target host Windows machine.  
There are two environment variables that need to be set on the target Windows host.

- `HTTP_PROXY` set with the proxy address.
- `HARNESS_ENV_PROXY` set to true.

When those conditions are met there will be a `Using the HTTP_PROXY environment variable` console log message on the `Download Artifact` step during pipeline/stage execution. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44969)

### CODE REVIEW

**Review by acasian-harness — DISMISSED** [review]

**Review by vitsafronovici — APPROVED** [review]
not very readable, maybe it would be better to put these Strings in resources as templates and then replace the variables

**Review by acasian-harness — COMMENTED** [review]
@ivan-83 please describe the changes

**Review by ivan-83 — COMMENTED** [review]
I agree, In terms of readability, I've updated the script java file to present the whole executable scripts. Now sonar qube will complain but we can ignore it. Placing executable scripts in resource files or keeping them in the Java file, I think it's not so critical here.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44969#-:-NSpS3fk24rriLlFdlEY:b-krs57a)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44969#-:-NSpV7qwAcYPwRw6B4EC:bnfp4nl)* status: 9 file(s) to review.

**Review by vitsafronovici — APPROVED** [review]

**Comment by ivan-83** [comment]
trigger review

**Pull request merged**
