### PR TITLE
[fix]: [PL-28565]: Makes retryInterval, timeout and connectionPoolSize properties configurable for redisson

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
…rties configurable for redisson

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38052)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38052)

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38052)* status: 24 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`960-persistence/src/main/java/io/harness/redis/RedissonClientFactory.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/38052#-ND26hDo32Q-X_kzqnqd:-ND26hDo32Q-X_kzqnqe:btbbzia) ([raw file](https://github.com/harness/harness-core/blob/1da677da4341ade3836405924ac9b955f6026731/960-persistence/src/main/java/io/harness/redis/RedissonClientFactory.java#L106)):*
> ```Java
>       }
>       config.setNettyThreads(redisConfig.getNettyThreads());
>       config.setUseScriptCache(redisConfig.isUseScriptCache());
> ```

We will need to set these new redis configuration properties here also.

**Comment by ashishsanodia-harness** [comment]
*[`960-persistence/src/main/java/io/harness/redis/RedissonClientFactory.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/38052#-ND26hDo32Q-X_kzqnqd:-ND29WO35ipAV7dNXXdN:b-b03nyu) ([raw file](https://github.com/harness/harness-core/blob/1da677da4341ade3836405924ac9b955f6026731/960-persistence/src/main/java/io/harness/redis/RedissonClientFactory.java#L106)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We will need to set these new redis configuration properties here also. 
</blockquote></details>

All these properties retryInterval, retryAttempts, connectionPoolsize and timeout are at SingleServerConfig level. Not at top level like nettythread, useScriptCache

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38052#-:-ND2DuT_3OLQDbGa66A1:bnfp4nl)* status: 24 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 24 files at r1, 22 of 23 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38052#-:-ND2EF3iAXu1ExcOVf3H:bnfp4nl)* status: 24 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38052#-:-ND2HvnJDGbNVc52HrZ7:bnfp4nl)* status: 24 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Pull request merged**
