### PR TITLE
[feat]: [PL-22424]: usage restriction check for new app

### PR DESCRIPTION
**Pull request by karansiwach360**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30920)

### CODE REVIEW

**Comment by karansiwach360** [comment]
trigger messagecheck

**Review by gupta-utkarsh — CHANGES_REQUESTED** [review]
> Reviewed 11 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30920)* status: 32 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/UsageRestrictionsServiceImpl.java, line 361 at r1](https://reviewable.io/reviews/harness/harness-core/30920#-MweKCa47nCC_HvGUJRt:-MweKCa47nCC_HvGUJRu:bkox2n2) ([raw file](https://github.com/harness/harness-core/blob/dadd5da72eb75418f275038837c22ad5dd0312ee/400-rest/src/main/java/software/wings/service/impl/UsageRestrictionsServiceImpl.java#L361)):*
> ```Java
>   }
> 
>   private boolean hasUsageRestrictionsForNewApp(Set<AppEnvRestriction> appEnvRestrictions) {
> ```

What if user does not have any AppEnvRestrictions? The user would still be able to list connectors here.

**Review by karansiwach360 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30920)* status: 32 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/UsageRestrictionsServiceImpl.java, line 361 at r1](https://reviewable.io/reviews/harness/harness-core/30920#-MweKCa47nCC_HvGUJRt:-MweXCjw1Nrb4yy7ndrm:b-odzv7j) ([raw file](https://github.com/harness/harness-core/blob/dadd5da72eb75418f275038837c22ad5dd0312ee/400-rest/src/main/java/software/wings/service/impl/UsageRestrictionsServiceImpl.java#L361)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

What if user does not have any AppEnvRestrictions? The user would still be able to list connectors here.
</blockquote></details>

We are returning false then

**Review by gupta-utkarsh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30920)* status: 32 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/UsageRestrictionsServiceImpl.java, line 361 at r1](https://reviewable.io/reviews/harness/harness-core/30920#-MweKCa47nCC_HvGUJRt:-Mwea-fSCi8M6eHgOtI_:b-f9m6ri) ([raw file](https://github.com/harness/harness-core/blob/dadd5da72eb75418f275038837c22ad5dd0312ee/400-rest/src/main/java/software/wings/service/impl/UsageRestrictionsServiceImpl.java#L361)):*
<details><summary><i>Previously, karansiwach360 (Karan Siwach) wrote…</i></summary><blockquote>

We are returning false then
</blockquote></details>

Where? I do not see handling for that case.

**Review by karansiwach360 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30920)* status: 32 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/UsageRestrictionsServiceImpl.java, line 361 at r1](https://reviewable.io/reviews/harness/harness-core/30920#-MweKCa47nCC_HvGUJRt:-MwelvFr4uKiAZ9bjyH1:b-7rrjyp) ([raw file](https://github.com/harness/harness-core/blob/dadd5da72eb75418f275038837c22ad5dd0312ee/400-rest/src/main/java/software/wings/service/impl/UsageRestrictionsServiceImpl.java#L361)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

Where? I do not see handling for that case.
</blockquote></details>

this only :/   
if (isEmpty(appEnvRestrictions)) {
      return false;
   }



_Code quote:_
```Java
    if (isEmpty(appEnvRestrictions)) {
      return false;
    }
```

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 19 of 32 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30920#-:-MwwkvNN9Dn1NBESwwpZ:bnfp4nl)* status: 32 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 30 of 32 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30920)* status: :shipit: complete! ✓

**Pull request merged**
