### PR TITLE
fix:[CDS-53549]: Using the step timeout as the delegate task timeout

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- The timeout value set in the step has not been used to determine the delegate task timeout causing to workflow execution abort when the build step takes more than 10 minutes to complete.

## Comment Triggers
<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46914)

### CODE REVIEW

**Comment by Fernando-Dourado** [comment]
trigger ut0, checkstylecodeformat

**Comment by Fernando-Dourado** [comment]
trigger codebasehash

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46914)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by boopesh007 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46914)* status: :shipit: complete! ✓

**Comment by boopesh007** [comment]
trigger codebasehash

**Review by boopesh007 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46914#-:-NTrpON69cdeYJFpf4sj:bnfp4nl)* status: :shipit: complete! ✓

**Comment by boopesh007** [comment]
trigger codebasehash

**Review by boopesh007 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46914#-:-NTrr3CZ7iMrB5vPZa_C:bnfp4nl)* status: :shipit: complete! ✓

**Review by boopesh007 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46914#-:-NTrr5Ec-r3sWpT9Is34:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
