### PR TITLE
fix: [PL-41845]: Short term fix to allow project admin role binding c…

### PR DESCRIPTION
**Pull request by meenakshi-harness**
1. Removed validation to check if SA exist in given scope but added recursive validation from child to parent scope for SA
2. This is done to allow creating child scope role bindings for parent scope SA as a short term hack.
3. This role binding will be shown only in roleassignment get API with following filter. Currently not supported in UI

`{
    "scopeFilters": [
        {
            "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
            "filter": "INCLUDING_CHILD_SCOPES"
        }
    ],
    "principalFilter": {
        "identifier": "test1",
        "type": "SERVICE_ACCOUNT"
    }
}`

Testing:
1. Create Project with Account scope SA, SA should get project admin permission.
2. Create Project with SA of different account - Should fail.
3. Create Project level entity with SA at account scope (given this SA doesn't have project admin permission) - Creation should fail.

Audit trail with parent scope info
Screenshot 2023-10-31 at 10 57 19 AM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)

### CODE REVIEW

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDaoImpl.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/54419#-Nhkn0PW1GIkSCfxJ1oh:-Nhkn0PW1GIkSCfxJ1oi:b-twy6jd) ([raw file](https://github.com/harness/harness-core/blob/9e666810d8292a443484575ffa92d45f565f9a6b/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDaoImpl.java#L74)):*
> ```Java
>   public List<ServiceAccountDBO> getAllInAccount(String identifier, String accountIdentifier) {
>     Pattern startsWithScope = Pattern.compile("^".concat("/ACCOUNT/" + accountIdentifier));
>     Criteria criteria = Criteria.where(RoleAssignmentDBOKeys.identifier)
> ```

It should ServiceAccountDBOKeys.identifier.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDaoImpl.java` line 76 at r3](https://reviewable.io/reviews/harness/harness-core/54419#-Nhkn5lKEjJ-ljbW4Sb5:-Nhkn5lKEjJ-ljbW4Sb6:b-oj6h1t) ([raw file](https://github.com/harness/harness-core/blob/9e666810d8292a443484575ffa92d45f565f9a6b/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDaoImpl.java#L76)):*
> ```Java
>     Criteria criteria = Criteria.where(RoleAssignmentDBOKeys.identifier)
>                             .is(identifier)
>                             .and(RoleAssignmentDBOKeys.scopeIdentifier)
> ```

It should ServiceAccountDBOKeys.scopeIdentifier.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/ServiceAccountValidator.java` line 58 at r3](https://reviewable.io/reviews/harness/harness-core/54419#-NhkobAT6I9Tz1deZh2m:-NhkobAT6I9Tz1deZh2n:byx5k1i) ([raw file](https://github.com/harness/harness-core/blob/9e666810d8292a443484575ffa92d45f565f9a6b/access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/ServiceAccountValidator.java#L58)):*
> ```Java
>       return ValidationResult.builder().valid(true).build();
>     }
>     return ValidationResult.builder().valid(false).build();
> ```

Lets have error message in case of validation failure .
.errorMessage(String.format(
            "service account not found with the given identifier %s in the account %s", identifier, accountId))

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/ServiceAccountValidator.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/54419#-NhkopV20a6DaUaHkqLA:-NhkopV20a6DaUaHkqLB:b-wktwu0) ([raw file](https://github.com/harness/harness-core/blob/9e666810d8292a443484575ffa92d45f565f9a6b/access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/ServiceAccountValidator.java#L48)):*
> ```Java
>     // Removing validation temporarily, this will be fixed as part of hierarchical SA
>     String identifier = principal.getPrincipalIdentifier();
>     String[] scopeIdentifierSplit = scopeIdentifier.split("/");
> ```

Instead of constructing accountId this way, lets convert to ScopeDTO and use that.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java` line 199 at r3](https://reviewable.io/reviews/harness/harness-core/54419#-NhkpUfo9hX3euATlZen:-NhkpUfo9hX3euATlZeo:b-dltwjx) ([raw file](https://github.com/harness/harness-core/blob/9e666810d8292a443484575ffa92d45f565f9a6b/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java#L199)):*
> ```Java
> 
>     if (SERVICE_ACCOUNT.equals(roleAssignment.getPrincipalType())) {
>       principalScopeLevel = scope.getLevel().toString();
> ```

In case of Project creation, in create call for Project Admin what is scope? Is it project or account?

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 9 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDaoImpl.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/54419#-Nhkn0PW1GIkSCfxJ1oh:-NhlVaDM1L87FQkAdRU5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9e666810d8292a443484575ffa92d45f565f9a6b/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDaoImpl.java#L74)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

It should ServiceAccountDBOKeys.identifier.
</blockquote></details>

Done.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDaoImpl.java` line 76 at r3](https://reviewable.io/reviews/harness/harness-core/54419#-Nhkn5lKEjJ-ljbW4Sb5:-NhlVb9j62uafpQOnl1w:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9e666810d8292a443484575ffa92d45f565f9a6b/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDaoImpl.java#L76)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

It should ServiceAccountDBOKeys.scopeIdentifier.
</blockquote></details>

Done.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/ServiceAccountValidator.java` line 58 at r3](https://reviewable.io/reviews/harness/harness-core/54419#-NhkobAT6I9Tz1deZh2m:-NhlVena4AtKWy7qYVBq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9e666810d8292a443484575ffa92d45f565f9a6b/access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/ServiceAccountValidator.java#L58)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Lets have error message in case of validation failure .
.errorMessage(String.format(
            "service account not found with the given identifier %s in the account %s", identifier, accountId))
</blockquote></details>

Done.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java` line 199 at r3](https://reviewable.io/reviews/harness/harness-core/54419#-NhkpUfo9hX3euATlZen:-NhlVfTZ9siNq1KsEVgL:buf6r90) ([raw file](https://github.com/harness/harness-core/blob/9e666810d8292a443484575ffa92d45f565f9a6b/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java#L199)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

In case of Project creation, in create call for Project Admin what is scope? Is it project or account?
</blockquote></details>

project

**Comment by meenakshi-harness** [comment]
trigger uts

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 9 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/ServiceAccountValidator.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/54419#-NhkopV20a6DaUaHkqLA:-NhlXKBQEKoQf36Q0yRc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9e666810d8292a443484575ffa92d45f565f9a6b/access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/ServiceAccountValidator.java#L48)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Instead of constructing accountId this way, lets convert to ScopeDTO and use that.
</blockquote></details>

Done.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDao.java` line 33 at r5](https://reviewable.io/reviews/harness/harness-core/54419#-Nhm4WlcCBjFhQfJ2jgL:-Nhm4WlcCBjFhQfJ2jgM:bein6cl) ([raw file](https://github.com/harness/harness-core/blob/6d61b164af63bb082775a78a0f3afa142946de81/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDao.java#L33)):*
> ```Java
>   Optional<ServiceAccount> delete(@NotEmpty String identifier, @NotEmpty String scopeIdentifier);
> 
>   List<ServiceAccountDBO> getAllInAccount(String identifier, String scopeIdentifier);
> ```

Change scopeIdentifier to accoundIdentifier in all methods.

**Comment by meenakshi-harness** [comment]
trigger uts

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 9 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/ServiceAccountService.java` line 33 at r6](https://reviewable.io/reviews/harness/harness-core/54419#-NhooqcRDpdSOR78uIew:-NhooqcRDpdSOR78uIex:b-rokuhf) ([raw file](https://github.com/harness/harness-core/blob/007d2ad049052b8134d8de2aed24e00a28e82d16/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/ServiceAccountService.java#L33)):*
> ```Java
>   Optional<ServiceAccount> deleteIfPresent(@NotEmpty String identifier, @NotEmpty String scopeIdentifier);
> 
>   List<ServiceAccountDBO> getAllInAccount(@NotEmpty String identifier, @NotEmpty String accountIdentifier);
> ```

Other methods in this service return ServiceAccount. Can we be consistent?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDao.java` line 33 at r5](https://reviewable.io/reviews/harness/harness-core/54419#-Nhm4WlcCBjFhQfJ2jgL:-Nhop2-kBjxVejCYldqG:bb76mu4) ([raw file](https://github.com/harness/harness-core/blob/6d61b164af63bb082775a78a0f3afa142946de81/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDao.java#L33)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Change scopeIdentifier to accoundIdentifier in all methods.
</blockquote></details>

Why?

**Comment by meenakshi-harness** [comment]
trigger uts

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 9 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/ServiceAccountService.java` line 33 at r6](https://reviewable.io/reviews/harness/harness-core/54419#-NhooqcRDpdSOR78uIew:-NhyxR1R2TejV6X6P6Cb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/007d2ad049052b8134d8de2aed24e00a28e82d16/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/ServiceAccountService.java#L33)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Other methods in this service return ServiceAccount. Can we be consistent?
</blockquote></details>

Done.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDao.java` line 33 at r5](https://reviewable.io/reviews/harness/harness-core/54419#-Nhm4WlcCBjFhQfJ2jgL:-NhyxRqc1ihG1eIdbv80:b93r8q9) ([raw file](https://github.com/harness/harness-core/blob/6d61b164af63bb082775a78a0f3afa142946de81/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDao.java#L33)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

We are fetching all service accounts in a given account, hence accountId is needed not scope identifier

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 9 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/ServiceAccountValidator.java` line 46 at r10](https://reviewable.io/reviews/harness/harness-core/54419#-Ni3fJyO5-CqKZCEve2j:-Ni3fJyO5-CqKZCEve2k:b-epdxun) ([raw file](https://github.com/harness/harness-core/blob/e9db0b57bf601daa9fc3438f7909b0e2bd1453eb/access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/ServiceAccountValidator.java#L46)):*
> ```Java
>     Scope scope = scopeService.buildScopeFromScopeIdentifier(scopeIdentifier);
>     String identifier = principal.getPrincipalIdentifier();
>     Scope parentScope = scope;
> ```

rename parentScope to currentScope.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java` line 224 at r10](https://reviewable.io/reviews/harness/harness-core/54419#-Ni3d6te2BIQmCocdE4I:-Ni3d6te2BIQmCocdE4J:b-epdxun) ([raw file](https://github.com/harness/harness-core/blob/e9db0b57bf601daa9fc3438f7909b0e2bd1453eb/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java#L224)):*
> ```Java
>   private String getServiceAccountScopeLevel(@NotNull String serviceAccountIdentifier, @NotNull Scope scope) {
>     Scope parentScope = scope;
>     while (parentScope != null) {
> ```

rename parentScope to currentScope.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 9 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java` line 225 at r10](https://reviewable.io/reviews/harness/harness-core/54419#-Ni3faqm32vKzuCu-FgS:-Ni3faqm32vKzuCu-FgT:b-bx27yl) ([raw file](https://github.com/harness/harness-core/blob/8b4be4c0a775721577483c346f660789a81915b1/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java#L225)):*
> ```Java
> 
>   private String getServiceAccountScopeLevel(@NotNull String serviceAccountIdentifier, @NotNull Scope scope) {
>     harnessServiceAccountService.sync(serviceAccountIdentifier, scope);
> ```

Shouldn't we sync and then get?

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 9 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountCustomRepositoryImpl.java` line 38 at r10](https://reviewable.io/reviews/harness/harness-core/54419#-Ni3gG028xFak9nnsXfs:-Ni3gG028xFak9nnsXft:brqt31d) ([raw file](https://github.com/harness/harness-core/blob/e9db0b57bf601daa9fc3438f7909b0e2bd1453eb/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountCustomRepositoryImpl.java#L38)):*
> ```Java
>   @Override
>   public List<ServiceAccountDBO> find(Criteria criteria) {
>     Query query = new Query(criteria);
> ```

I dont see usage for this method.

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 9 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountCustomRepositoryImpl.java` line 38 at r10](https://reviewable.io/reviews/harness/harness-core/54419#-Ni3gG028xFak9nnsXfs:-Ni3k0pM0HOqerTtOzZT:b-x9wtof) ([raw file](https://github.com/harness/harness-core/blob/e9db0b57bf601daa9fc3438f7909b0e2bd1453eb/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountCustomRepositoryImpl.java#L38)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

I dont see usage for this method.
</blockquote></details>

This is very generic method hence not removed
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/ServiceAccountValidator.java` line 46 at r10](https://reviewable.io/reviews/harness/harness-core/54419#-Ni3fJyO5-CqKZCEve2j:-Ni3k5mK9En6HW_vdPv-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e9db0b57bf601daa9fc3438f7909b0e2bd1453eb/access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/ServiceAccountValidator.java#L46)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

rename parentScope to currentScope.
</blockquote></details>

Done.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java` line 224 at r10](https://reviewable.io/reviews/harness/harness-core/54419#-Ni3d6te2BIQmCocdE4I:-Ni3k7kl3FKhoKTz-Mcc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e9db0b57bf601daa9fc3438f7909b0e2bd1453eb/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java#L224)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

rename parentScope to currentScope.
</blockquote></details>

Done.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java` line 225 at r10](https://reviewable.io/reviews/harness/harness-core/54419#-Ni3faqm32vKzuCu-FgS:-Ni3k6Nx82NU1RA1VmMZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8b4be4c0a775721577483c346f660789a81915b1/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java#L225)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Shouldn't we sync and then get?
</blockquote></details>

Done.

**Review by ankit-harness — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 2 of 7 files at r2, 3 of 6 files at r9, 1 of 1 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 9 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained.

**Comment by meenakshi-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountCustomRepositoryImpl.java` line 38 at r10](https://reviewable.io/reviews/harness/harness-core/54419#-Ni3gG028xFak9nnsXfs:-Ni3yia3BEJVpZqKmoih:b-uhzf3k) ([raw file](https://github.com/harness/harness-core/blob/e9db0b57bf601daa9fc3438f7909b0e2bd1453eb/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountCustomRepositoryImpl.java#L38)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

This is very generic method hence not removed
</blockquote></details>

@meenakshi-harness we can add when we need it. 
https://www.techtarget.com/whatis/definition/You-arent-gonna-need-it#:~:text=YAGNI%20principle%20(%22You%20Aren',desired%20increased%20frequency%20of%20releases.

**Comment by meenakshi-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 3 of 6 files at r9, 1 of 1 files at r10, 2 of 2 files at r11, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger ut7, ut8, ut9

**Comment by meenakshi-harness** [comment]
trigger ut9, ut8

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Review by ankit-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54419)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
