### PR TITLE
fix: [CDS-47776]: Cluster details mismatch in Service instances

### PR DESCRIPTION
**Pull request by meenaravichandran1**
## Describe your changes
Cluster details are not uniquely returned for Active service instances popover. This fix adds a filter for infra/cluster id, pipeline id along with service id, build id, env id.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41049)

### CODE REVIEW

**Comment by meenaravichandran1** [comment]
trigger messagecheck

**Comment by Abhishek-CDC** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java` line 283 at r1](https://reviewable.io/reviews/harness/harness-core/41049#-NIKrlr71ytkmeVxIonQ:-NIKrlr71ytkmeVxIonR:b-odvmzt) ([raw file](https://github.com/harness/harness-core/blob/78f5db741e95dfc1249e6e45c1b172c27e033a92/120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java#L283)):*
> ```Java
>       @QueryParam(NGCommonEntityConstants.INFRA_IDENTIFIER) String infraId,
>       @QueryParam(NGCommonEntityConstants.CLUSTER_IDENTIFIER) String clusterId,
>       @NotNull @QueryParam(NGCommonEntityConstants.PIPELINE_EXECUTION_ID) String pipelineExecutionId) {
> ```

lets make pipelineExecutionId optional since same API is used by old dashboard

**Comment by Abhishek-CDC** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java` line 283 at r1](https://reviewable.io/reviews/harness/harness-core/41049#-NIKs2ikC6MTznYFS2du:-NIKs2ikC6MTznYFS2dv:b-sh1kci) ([raw file](https://github.com/harness/harness-core/blob/78f5db741e95dfc1249e6e45c1b172c27e033a92/120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java#L283)):*
> ```Java
>       @QueryParam(NGCommonEntityConstants.INFRA_IDENTIFIER) String infraId,
>       @QueryParam(NGCommonEntityConstants.CLUSTER_IDENTIFIER) String clusterId,
>       @NotNull @QueryParam(NGCommonEntityConstants.PIPELINE_EXECUTION_ID) String pipelineExecutionId) {
> ```

lets also try adding 'lastDeployedAt' time that we get for pipelineExecution in response for 'getActiveServiceInstances' API as a filter since we can have multiple entries for same pipeline execution if instances are deployed at different time.

**Review by Abhishek-CDC — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41049)* status: 13 file(s) to review. 0 of 2 approvals obtained.

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41049)* status: 13 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java` line 283 at r1](https://reviewable.io/reviews/harness/harness-core/41049#-NIKrlr71ytkmeVxIonQ:-NIN554RC87in5Hnsc4g:b-8lt9cd) ([raw file](https://github.com/harness/harness-core/blob/78f5db741e95dfc1249e6e45c1b172c27e033a92/120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java#L283)):*
<details><summary><i>Previously, Abhishek-CDC (Abhishek) wrote…</i></summary><blockquote>

lets make pipelineExecutionId optional since same API is used by old dashboard
</blockquote></details>

will address this
___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java` line 283 at r1](https://reviewable.io/reviews/harness/harness-core/41049#-NIKs2ikC6MTznYFS2du:-NIN5BPm9nn4GOoYJXvI:b-jvkshk) ([raw file](https://github.com/harness/harness-core/blob/78f5db741e95dfc1249e6e45c1b172c27e033a92/120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java#L283)):*
<details><summary><i>Previously, Abhishek-CDC (Abhishek) wrote…</i></summary><blockquote>

lets also try adding 'lastDeployedAt' time that we get for pipelineExecution in response for 'getActiveServiceInstances' API as a filter since we can have multiple entries for same pipeline execution if instances are deployed at different time.
</blockquote></details>

pipelineExecutionId is unique for every pipeline execution, right?

Is there any use case where they won't be unique?

**Review by rohitk-h — DISMISSED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41049)* status: 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41049)* status: 14 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java` line 283 at r1](https://reviewable.io/reviews/harness/harness-core/41049#-NIKs2ikC6MTznYFS2du:-NIXen4kD1d-Sa2Zlnk3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/78f5db741e95dfc1249e6e45c1b172c27e033a92/120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java#L283)):*
<details><summary><i>Previously, Abhishek-CDC (Abhishek) wrote…</i></summary><blockquote>

pipelineExecutionId will be unique for each execution but it is possible to have instances deployed at different times within same pipeline execution
</blockquote></details>

Done.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41049)* status: 14 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by Abhishek-CDC — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41049)* status: 14 file(s) to review. 2. unresolved discussions.

**Review by Abhishek-CDC — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41049)* status: 14 file(s) to review.

**Review by Abhishek-CDC — APPROVED** [review]
> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41049)* status: :shipit: complete! ✓

**Pull request merged**
