### PR TITLE
[fix]: [SRM-11696]: Fixing bug for the less than for fail fast use case.

### PR DESCRIPTION
**Pull request by deepak-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36869)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36869)

**Comment by deepak-harness** [comment]
trigger messagecheck

**Comment by deepak-harness** [comment]
trigger messagecheck

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36869)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/TimeSeriesMetricPackDTO.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/36869#-NAcs28fAwBNLlWk84RV:-NAcs28fAwBNLlWk84RW:b-c82pr7) ([raw file](https://github.com/harness/harness-core/blob/aed564a0673283015b41e808a300755c1f1f4bf5/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/TimeSeriesMetricPackDTO.java#L106)):*
> ```Java
>                 .value(criteria.getType().getRatio(criteria.getSpec().lessThan))
>                 .build();
>         if (MetricThresholdActionType.IGNORE.equals(type)) {
> ```

This will never be executed now

**Review by deepak-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36869)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/TimeSeriesMetricPackDTO.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/36869#-NAcs28fAwBNLlWk84RV:-NActJPY4cFRY-old1HF:b-6b6sn0) ([raw file](https://github.com/harness/harness-core/blob/aed564a0673283015b41e808a300755c1f1f4bf5/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/TimeSeriesMetricPackDTO.java#L106)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

This will never be executed now
</blockquote></details>

It will be executed when the criteria is less than and action is IGNORE.
Earlier it was not getting executed in case of action as fail fast since I forgot to remove the check in if clause.

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36869)* status: :shipit: complete! ✓

**Pull request merged**
