### PR TITLE
fix: [CDS-81154]: Add Execution Mode as a filter option in Executions List page

### PR DESCRIPTION
**Pull request by ayushitiwari024**
## Describe your changes

**Issue:** Customers have asked for options to view the Rollback executions, Child Executions, Retries, etc. on the Executions list page. Other than Rollback executions, the others are not even displayed by default.

**Changes:** Added ExecutionModeFilter flag with 3 values(rollback, all, default). Corresponding to all the values criteria is set and the pipelines are filtered.

**Testing:** Tested this case locally: https://harness.atlassian.net/browse/CDS-81154

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54450)

### CODE REVIEW

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54450)* status: 3 file(s) to review. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionModeFilter.java` line 11 at r1](https://reviewable.io/reviews/harness/harness-core/54450#-NhPuYzg4k1N8iqjKor3:-NhPuYzg4k1N8iqjKor4:b-yspfpg) ([raw file](https://github.com/harness/harness-core/blob/1674fa8d674d5d08e2039b510e90770926b5b1c9/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionModeFilter.java#L11)):*
> ```Java
> 
> /**
>  * ROLLBACK: Displays all the Post prod rollback execution
> ```

Mention rollback executions instead of Post-prod-rollback executions. Because we will show the pipeline rollback executions as well in this mode.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 184 at r1](https://reviewable.io/reviews/harness/harness-core/54450#-NhPvF5HEfm74jBiJXYK:-NhPvF5HEfm74jBiJXYL:bzdqkiw) ([raw file](https://github.com/harness/harness-core/blob/1674fa8d674d5d08e2039b510e90770926b5b1c9/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L184)):*
> ```Java
>           filterCriteria, filterProperties, EmptyPredicate.isNotEmpty(pipelineIdentifier));
>     } else {
>       populatePipelineFilterANDOperator(filterCriteria,
> ```

nit: Can you add a comment that if filterIdentifier and filterCriteria both are null then we need default behaviour. So instead of duplicating the logic here, we are calling the same flow with filterCriteria with default executionMode value?

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54450)* status: 4 file(s) to review. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/test/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImplTest.java` line 291 at r3](https://reviewable.io/reviews/harness/harness-core/54450#-Nh_K1VA3kjg8yKpK35V:-Nh_K1VA3kjg8yKpK35W:b7n057n) ([raw file](https://github.com/harness/harness-core/blob/786b30b9b7349776d0fec630707151493ff970ef/pipeline-service/service/src/test/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImplTest.java#L291)):*
> ```Java
>     Document inChildList = form.getCriteriaObject();
>     assertThat(inChildList.size()).isEqualTo(1);
>     assertThat(inChildList.toString()).isEqualTo("Document{{isLatestExecution=Document{{$ne=false}}}}");
> ```

We will show non-latest executions as well when the ExecutionModeFilter.ALL is used? Then this {isLatestExecution=Document{{$ne=false}}} condition should not come.

**Review by ayushitiwari024 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54450)* status: 4 file(s) to review. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionModeFilter.java` line 11 at r1](https://reviewable.io/reviews/harness/harness-core/54450#-NhPuYzg4k1N8iqjKor3:-Nh_an-J56MHCGoFFcVZ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/1674fa8d674d5d08e2039b510e90770926b5b1c9/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionModeFilter.java#L11)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Mention rollback executions instead of Post-prod-rollback executions. Because we will show the pipeline rollback executions as well in this mode.
</blockquote></details>

Done

**Comment by ayushitiwari024** [comment]
trigger smartchecks

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54450)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by ayushitiwari024** [comment]
trigger gitleaks

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger gitleaks

**Comment by ayushitiwari024** [comment]
trigger gitleaks

**Comment by ayushitiwari024** [comment]
trigger gitleaks

**Comment by ayushitiwari024** [comment]
trigger uts

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54450)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54450)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54450)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 451 at r5](https://reviewable.io/reviews/harness/harness-core/54450#-NhbWJeB5zdyZdJJLDEu:-NhbWJeB5zdyZdJJLDEv:b9au0q1) ([raw file](https://github.com/harness/harness-core/blob/bfe0426caf03d02ec79eb7d3cdb0a57ffb382da1/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L451)):*
> ```Java
>     } else if (ExecutionModeFilter.DEFAULT == pipelineFilter.getExecutionModeFilter()) {
>       criteria.and(PlanExecutionSummaryKeys.executionMode).ne(ExecutionMode.PIPELINE_ROLLBACK);
>       if (!isPipelineIdentifierPresent) {
> ```

@sahilhindwani-harness can you check this, i think we can simplify it?
@ayushitiwari024 lets connect once tomorrow on this?

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54450)* status: :shipit: complete! ✓

**Comment by ayushitiwari024** [comment]
trigger review

**Review by ayushitiwari024 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54450)* status: :shipit: complete! ✓

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 451 at r5](https://reviewable.io/reviews/harness/harness-core/54450#-NhbWJeB5zdyZdJJLDEu:-NhjSqJuCH0mWtoksS8g:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/bfe0426caf03d02ec79eb7d3cdb0a57ffb382da1/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L451)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@sahilhindwani-harness can you check this, i think we can simplify it?
@ayushitiwari024 lets connect once tomorrow on this?
</blockquote></details>

Done

**Comment by ayushitiwari024** [comment]
trigger uts

**Comment by ayushitiwari024** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 3 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54450)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 3 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54450)* status: :shipit: complete! ✓

**Comment by ayushitiwari024** [comment]
trigger review

**Pull request merged**
