### PR TITLE
[fix]: [PIE-6474]: Make reconcile work if type is changed for variables

### PR DESCRIPTION
**Pull request by namanvermah**
When the variable type is changed for a variable that is marked as runtime input, then the reconcile option will suggest to remove that variable from the input set altogether.
Testing: added unit tests. E2E testing video attached.
https://user-images.githubusercontent.com/68542540/205595056-73571efc-2e27-494c-98ff-01971a4de181.mov

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41086)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger messagecheck

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41086)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41086)* status: :shipit: complete! ✓

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/InputSetErrorsHelper.java` line 165 at r1](https://reviewable.io/reviews/harness/harness-core/41086#-NIWxuGI6RjGKnmd-GK0:-NIWxuGJDKb5DCgOQ9s6:b-opdays) ([raw file](https://github.com/harness/harness-core/blob/555aeb585698eabdf765589bae62197b3c017499/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/InputSetErrorsHelper.java#L165)):*
> ```Java
>       if (inputSetFQNs.contains(key)) {
>         Object templateValue = templateConfig.getFqnToValueMap().get(key);
>         Object value = inputSetConfig.getFqnToValueMap().get(key);
> ```

nit: rename to better name for verbosity.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41086)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41086#-:-NIX5TNl33tjB9aBWep7:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41086)* status: :shipit: complete! ✓

**Pull request merged**
