### PR TITLE
feat: [CDS-76206]: add infra selectors in shell script step

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
add infra selectors in shell script step

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51292)

### CODE REVIEW

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by sarthakkasat** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskParametersNG.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/51292#-NcN7Hgo0E9aY-30mKeU:-NcN7Hgo0E9aY-30mKeV:bz8hq3x) ([raw file](https://github.com/harness/harness-core/blob/8018ac65fa3c553895db9db40d816ff3d462ba25/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskParametersNG.java#L64)):*
> ```Java
>     List<ExecutionCapability> capabilities = new ArrayList<>();
>     if ((script.contains(K8sConstants.HARNESS_KUBE_CONFIG_PATH) || BooleanUtils.isTrue(includeInfraSelectors))
>         && k8sInfraDelegateConfig != null) {
> ```

I think we discussed that this condition can be simplified to check only k8sInfraDelegateConfig, right ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51292)* status: Some of the checks are too old. 8 file(s) to review. 1 of 2 approvals obtained.

**Review by sarthakkasat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51292)* status: Some of the checks are too old. 8 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskParametersNG.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/51292#-NcN7Hgo0E9aY-30mKeU:-NcQRwlw8kCpwPkuZRY9:b-3g84ik) ([raw file](https://github.com/harness/harness-core/blob/8018ac65fa3c553895db9db40d816ff3d462ba25/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskParametersNG.java#L64)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I think we discussed that this condition can be simplified to check only k8sInfraDelegateConfig, right ?
</blockquote></details>

Made the changes in separate PR --> https://github.com/harness/harness-core/pull/51653

**Pull request closed without merging**
