### PR TITLE
feat: [PLG-1954]: Add cxng local dev license

### PR DESCRIPTION
**Pull request by Xin-Harness**
## Describe your changes
After run ng-manager in local, cd, ci, ce, cf,srm license get generated for local dev to have module visibility based on module license.
image
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44239)

### CODE REVIEW

**Review by neelam-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44239)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalAdminCFLicenseMigration.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/44239#-NPVHkcNBoo0W8y2SLeV:-NPVHkcO1jkYMjMNMz3-:b77hx8) ([raw file](https://github.com/harness/harness-core/blob/a0b399898f220bbefe54473001ef7ee788694678/930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalAdminCFLicenseMigration.java#L26)):*
> ```Java
> public class LocalAdminCFLicenseMigration implements NGMigration {
>   @Inject MongoTemplate mongoTemplate;
>   private String ADMIN_ACCOUNT_IDENTIFIER = "kmpySmUISimoRrJL6NL73w";
> ```

nit: let's make this field also as `final` if the account is not going to change ?
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalAdminCILicenseMigration.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/44239#-NPVLYaj4hqiP5qYxBFX:-NPVLYaj4hqiP5qYxBFY:b4qnz0f) ([raw file](https://github.com/harness/harness-core/blob/a0b399898f220bbefe54473001ef7ee788694678/930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalAdminCILicenseMigration.java#L2)):*
> ```Java
> /*
>  * Copyright 2021 Harness Inc. All rights reserved.
> ```

nit: change `2021` to `2023`
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalAdminSRMLicenseMigration.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/44239#-NPVMd7G4ZralN-aGP5E:-NPVMd7G4ZralN-aGP5F:bi6ddd5) ([raw file](https://github.com/harness/harness-core/blob/a0b399898f220bbefe54473001ef7ee788694678/930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalAdminSRMLicenseMigration.java#L26)):*
> ```Java
> public class LocalAdminSRMLicenseMigration implements NGMigration {
>   @Inject MongoTemplate mongoTemplate;
>   private String ADMIN_ACCOUNT_IDENTIFIER = "kmpySmUISimoRrJL6NL73w";
> ```

same nit: let's make it final in all places if not going to change

**Review by thomas-grasman — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44239)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by neelam-harness — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44239#-:-NPYkEyB2BJFS0VQzYvL:bnfp4nl)* status: 4 file(s) to review.

**Review by neelam-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44239)* status: :shipit: complete! ✓

**Pull request merged**
