### PR TITLE
fix: [CDS-44213]: OPA Pipeline expansion for "environment"

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
- feat: [CDS-41366]: WIP
- feat: [CDS-44213]: Pipeline expansion for "environment"
- [x] Handle Static Environment and Infrastructure
- [x] Handle Infrastructure Inputs
- [x] Expand connectorRef within the infrastructure spec

Source Yaml for environment:
```
environment:
    environmentRef: my_environment
    deployToAll: false
    infrastructureDefinitions:
    - identifier: my_infra
```

Expanded Yaml: ( strategy = PARALLEL )
```
infrastructure:
        environment:
              id: my_environment
              name: dev_environment
              tags: []
              deleted: false
        environmentRef: my_environment
        allowSimultaneousDeployments: false
        infrastructureDefinition:
        type: ECS
        spec:
            connectorRef: aws-connector
            cluster: us-east-1-cluster
            region: us-east-1
```
Documented the yamls here: https://harness.atlassian.net/wiki/pages/viewpage.action?pageId=21199781935&pageVersion=7
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38422)

[CDS-41366]: https://harness.atlassian.net/browse/CDS-41366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-44213]: https://harness.atlassian.net/browse/CDS-44213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 8 Issues 
* Code issue 8 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38422)

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by namanvermah — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 11 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38422#-:-NDmCr3GDTcb6L31KF0h:bnfp4nl)* status: :shipit: complete! ✓

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 6 of 11 files at r1, 9 of 12 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38422)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
io.harness.cvng.servicelevelobjective.services.impl.ServiceLevelObjectiveServiceImplTest is failing here

**Comment by yogesh-chauhan** [comment]
io.harness.cvng.core.jobs.EntityCRUDStreamConsumerTest is also failing

**Pull request merged**
