### PR TITLE
fix: [PL-40576]: Fix the Fetch Secret Time Limit for Azure Vault.

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

This PR handles retry time limit with incremental backoff for Interrupted exception for Azure vault. Interrupted exception signifies that the client was not able to connect to Azure vault and fetch the secret within the given time limit. This has been occurring a lot of times (150k times / week) in customer environments which indicates that in certain cases the existing time limit is not sufficient. Thus, this PR handles this scenario with incremental back-off.

Tested it locally to fetch the secret.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55685)

### CODE REVIEW

**Comment by Raghav-Murali** [comment]
trigger uts

**Review by xingchi-jin — DISMISSED** [review]

**Comment by Raghav-Murali** [comment]
trigger messagecheck

**Comment by Raghav-Murali** [comment]
trigger messagecheck

**Comment by Raghav-Murali** [comment]
trigger uts

**Comment by sahibaHarness** [comment]
trigger uts

**Review by sahibaHarness — DISMISSED** [review]

**Comment by Raghav-Murali** [comment]
trigger uts

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55685)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 317 at r1](https://reviewable.io/reviews/harness/harness-core/55685#-NjlFY5L51LAx3q4Qv9e:-NjlXBZG9DtJyMW1Zp1L:b-ea2e1m) ([raw file](https://github.com/harness/harness-core/blob/19bb9ef2ec796577726b360ee0306fbd18365cb4/931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L317)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Instead of passing fetchAttempt as parameter, we can use exception block below to print interrupted exception based on the value of failed attempt.
</blockquote></details>

Thanks for the inputs! I have addressed it accordingly.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55685)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 407 at r3](https://reviewable.io/reviews/harness/harness-core/55685#-NjlYwgJ6ghOqRlh0waj:-NjlYwgJ6ghOqRlh0wak:bbc5fa7) ([raw file](https://github.com/harness/harness-core/blob/803a8bb83f6588d37398885e310803e9d5df17bb/931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L407)):*
> ```Java
>       // as it can flood the log stream.
>       if (ex instanceof InterruptedException) {
>         throw new SecretManagementDelegateException(AZURE_KEY_VAULT_INTERRUPT_ERROR, message, USER);
> ```

Looks good. Lets add UT for this.

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55685)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 407 at r3](https://reviewable.io/reviews/harness/harness-core/55685#-NjlYwgJ6ghOqRlh0waj:-NjnE1GyD4tA2DF32rmA:b-qn8u06) ([raw file](https://github.com/harness/harness-core/blob/803a8bb83f6588d37398885e310803e9d5df17bb/931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L407)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Looks good. Lets add UT for this.
</blockquote></details>

Have added it and tested locally.

**Comment by Raghav-Murali** [comment]
trigger uts

**Review by sahibaHarness — APPROVED** [review]

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55685)* status: 3 file(s) to review.

**Pull request merged**
