### PR TITLE
[fix]: [CDS-81634]: fix for NPE if target host not provided for shell script

### PR DESCRIPTION
**Pull request by rchaudharyy**
## Describe your changes
Executing shell script  by default on delegate if target host is not provided

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54546)

### CODE REVIEW

**Comment by rchaudharyy** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java` line 337 at r1](https://reviewable.io/reviews/harness/harness-core/54546#-NhaC48lBzQIGw267WnR:-NhaC48lBzQIGw267WnS:b-u5dslw) ([raw file](https://github.com/harness/harness-core/blob/bcdc418338e44bd67223c6c014d15f822df5ae03/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java#L337)):*
> ```Java
>   }
>   private void updateShellScriptStepOnDelegateParameterField(
>       @Nonnull ShellScriptStepParameters shellScriptStepParameters) {
> ```

Not Null is not needed in private methods. if step parameters were null, it would fail way earlier. Also, framework ensures, null step params are not possible

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java` line 343 at r1](https://reviewable.io/reviews/harness/harness-core/54546#-NhaCSX41BYhYLibZa1m:-NhaCSX41BYhYLibZa1n:bai9ai3) ([raw file](https://github.com/harness/harness-core/blob/bcdc418338e44bd67223c6c014d15f822df5ae03/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java#L343)):*
> ```Java
>       } else {
>         shellScriptStepParameters.setOnDelegate(ParameterField.createValueField(false));
>       }
> ```

can you also elaborate beahviour in following cases
- onDelegate is an expression which could not be resolved eg. <+soeme_random_expression>
- onDelegate is lets say "" or some junk string

**Comment by rchaudharyy** [comment]
> _[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java` line 337 at r1](https://reviewable.io/reviews/harness/harness-core/54546#-NhaC48lBzQIGw267WnR:-NhaC48lBzQIGw267WnS:b-u5dslw) ([raw file](https://github.com/harness/harness-core/blob/bcdc418338e44bd67223c6c014d15f822df5ae03/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java#L337)):_
> 
> > ```java
> >   }
> >   private void updateShellScriptStepOnDelegateParameterField(
> >       @Nonnull ShellScriptStepParameters shellScriptStepParameters) {
> > ```
> 
> Not Null is not needed in private methods. if step parameters were null, it would fail way earlier. Also, framework ensures, null step params are not possible

ok

**Comment by rchaudharyy** [comment]
> _[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java` line 343 at r1](https://reviewable.io/reviews/harness/harness-core/54546#-NhaCSX41BYhYLibZa1m:-NhaCSX41BYhYLibZa1n:bai9ai3) ([raw file](https://github.com/harness/harness-core/blob/bcdc418338e44bd67223c6c014d15f822df5ae03/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java#L343)):_
> 
> > ```java
> >       } else {
> >         shellScriptStepParameters.setOnDelegate(ParameterField.createValueField(false));
> >       }
> > ```
> 
> can you also elaborate beahviour in following cases
> 
> * onDelegate is an expression which could not be resolved eg. <+soeme_random_expression>
> * onDelegate is lets say "" or some junk string

In both scenarios onDelegate value will be coming as null and it will be handled in the first condition only i.e to run it on delegate itself.

In other scenarios, if onDelegate value is an expression and it is getting resolved to string value in that case we will be throwing InvalidRequestException.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54546)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java` line 335 at r1](https://reviewable.io/reviews/harness/harness-core/54546#-NhaC0GUCM9VOlZbEw0H:-NhaC0GUCM9VOlZbEw0I:b-6jg0b9) ([raw file](https://github.com/harness/harness-core/blob/bcdc418338e44bd67223c6c014d15f822df5ae03/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java#L335)):*
> ```Java
>                                 accountIdentifier, orgIdentifier, projectIdentifier))
>                             .getValue());
>   }
> ```

nit: new line for readability

**Comment by rchaudharyy** [comment]
trigger uts

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by rchaudharyy** [comment]
trigger review

**Pull request merged**
