### PR TITLE
fix: [PL-20635]: UserGroup can be deleted even when referenced in a pipeline

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)

### CODE REVIEW

**Review by gupta-utkarsh — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: 7 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java, line 657 at r2](https://reviewable.io/reviews/harness/harness-core/30292#-MvNWbiwEY9B2PDiI4ni:-MvNWbiwEY9B2PDiI4nj:b-upek7q) ([raw file](https://github.com/harness/harness-core/blob/b0aa161dc7891ab00ed1effe779cbaebf1ecc85a/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L657)):*
> ```Java
> 
>   public void updateUserGroupParents(Set<String> previousUserGroups, Set<String> currentUserGroups, String accountId,
>       String pipelineId, String appId) {
> ```

Where is the code which prevents deletion of user group if it is being used in a pipeline?

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: 9 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java, line 662 at r1](https://reviewable.io/reviews/harness/harness-core/30292#-Muz42Eq4IGVHmFr10WD:-MvNwIwR8a6hPRdzz1Md:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5083b103157af4b9eb2305970f400c3433c02eab/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L662)):*
<details><summary><i>Previously, karansiwach360 (Karan Siwach) wrote…</i></summary><blockquote>

Null check for userGroup
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java, line 657 at r2](https://reviewable.io/reviews/harness/harness-core/30292#-MvNWbiwEY9B2PDiI4ni:-MvNwDfg5iD-BK2dgVlX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b0aa161dc7891ab00ed1effe779cbaebf1ecc85a/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L657)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

Where is the code which prevents deletion of user group if it is being used in a pipeline?
</blockquote></details>

Done.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: 11 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/beans/security/UserGroup.java, line 235 at r1](https://reviewable.io/reviews/harness/harness-core/30292#-Muz2ou61IBcMJetA0WW:-MvTE6R_9N12BFk7BBWy:b-wxez1r) ([raw file](https://github.com/harness/harness-core/blob/5083b103157af4b9eb2305970f400c3433c02eab/400-rest/src/main/java/software/wings/beans/security/UserGroup.java#L235)):*
<details><summary><i>Previously, karansiwach360 (Karan Siwach) wrote…</i></summary><blockquote>

Null check on parents field
</blockquote></details>

In this case parents cannot be null at all because we are initializing a hashmap and just adding and removing stuff. I think no need to do null check for parents here.
___
*[400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java, line 2083 at r1](https://reviewable.io/reviews/harness/harness-core/30292#-Muz6i8L9GDE7k3LJucC:-MvTES8TENGy2X-B2x-C:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5083b103157af4b9eb2305970f400c3433c02eab/400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java#L2083)):*
<details><summary><i>Previously, karansiwach360 (Karan Siwach) wrote…</i></summary><blockquote>

Why is this needed if we have USER_GROUPS.equals(name)?
</blockquote></details>

Done.

**Review by karansiwach360 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: 11 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/beans/security/UserGroup.java, line 235 at r1](https://reviewable.io/reviews/harness/harness-core/30292#-Muz2ou61IBcMJetA0WW:-MvTyi03-PdbRIuh7XRI:b-f312pi) ([raw file](https://github.com/harness/harness-core/blob/5083b103157af4b9eb2305970f400c3433c02eab/400-rest/src/main/java/software/wings/beans/security/UserGroup.java#L235)):*
<details><summary><i>Previously, karansiwach360 (Karan Siwach) wrote…</i></summary><blockquote>

But for existing entries in DB, will it not be null?
</blockquote></details>

Just validate it once, you might need to handle it in constructor otherwise.

**Review by gupta-utkarsh — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: 11 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/beans/security/UserGroup.java, line 235 at r1](https://reviewable.io/reviews/harness/harness-core/30292#-Muz2ou61IBcMJetA0WW:-MvUDJNy8NQJwAA7XHXS:b-2ih1hz) ([raw file](https://github.com/harness/harness-core/blob/5083b103157af4b9eb2305970f400c3433c02eab/400-rest/src/main/java/software/wings/beans/security/UserGroup.java#L235)):*
<details><summary><i>Previously, karansiwach360 (Karan Siwach) wrote…</i></summary><blockquote>

Just validate it once, you might need to handle it in constructor otherwise.
</blockquote></details>

+1 please validate this that when we fetch from DB the new HashSet<>() is respected.
___
*[400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java, line 257 at r5](https://reviewable.io/reviews/harness/harness-core/30292#-MvUDfDW61j3PmakDaGX:-MvUDfDW61j3PmakDaGY:bobjhcx) ([raw file](https://github.com/harness/harness-core/blob/81924526af8637e6a0d709c7709b7cedbf600f7c/400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java#L257)):*
> ```Java
>     validatePipeline(pipeline, keywords);
> 
>     Set<String> previousUserGroups = getUserGroups(savedPipeline);
> ```

Please get the changes in this file reviewed by CDC team as well.
___
*[400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java, line 656 at r5](https://reviewable.io/reviews/harness/harness-core/30292#-MvUEEOG97w5KE77Q4BB:-MvUEEOG97w5KE77Q4BC:bfi7s1k) ([raw file](https://github.com/harness/harness-core/blob/81924526af8637e6a0d709c7709b7cedbf600f7c/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L656)):*
> ```Java
>   }
> 
>   public void updateUserGroupParents(Set<String> previousUserGroups, Set<String> currentUserGroups, String accountId,
> ```

This service contract is incorrect there, the logic to do this should be in pipeline service. User Group service should only expose these contracts.
addParents(String accountId, String userGroupId, Set<UserGroupEntityReference> parentsToAdd)
removeParents(String accountId, String userGroupId, Set<UserGroupEntityReference> parentsToRemove)
___
*[400-rest/src/test/java/software/wings/service/PipelineServiceTest.java, line 1713 at r5](https://reviewable.io/reviews/harness/harness-core/30292#-MvUDrkb3dKMtdL8_med:-MvUDrkb3dKMtdL8_mee:b32vmt) ([raw file](https://github.com/harness/harness-core/blob/81924526af8637e6a0d709c7709b7cedbf600f7c/400-rest/src/test/java/software/wings/service/PipelineServiceTest.java#L1713)):*
> ```Java
>   @Owner(developers = VIKAS_M)
>   @Category(UnitTests.class)
>   public void test_savePipelineCallsUpdateUserGroupMethod() {}
> ```

??

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: 11 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/beans/security/UserGroup.java, line 235 at r1](https://reviewable.io/reviews/harness/harness-core/30292#-Muz2ou61IBcMJetA0WW:-MvUefO5-DI-nLT1b4I-:b-grpzl6) ([raw file](https://github.com/harness/harness-core/blob/5083b103157af4b9eb2305970f400c3433c02eab/400-rest/src/main/java/software/wings/beans/security/UserGroup.java#L235)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

+1 please validate this that when we fetch from DB the new HashSet<>() is respected.
</blockquote></details>

Validated. new HashSet<> is somehow being used for the existing entries in the dB
___
*[400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java, line 2083 at r1](https://reviewable.io/reviews/harness/harness-core/30292#-Muz6i8L9GDE7k3LJucC:-MvUHGhj6ZjHD04wBVU_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5083b103157af4b9eb2305970f400c3433c02eab/400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java#L2083)):*
<details><summary><i>Previously, karansiwach360 (Karan Siwach) wrote…</i></summary><blockquote>

Why is !shouldBeIgnored needed, it is still there?
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java, line 656 at r5](https://reviewable.io/reviews/harness/harness-core/30292#-MvUEEOG97w5KE77Q4BB:-MvUexaFCFM6wqEroh2V:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/81924526af8637e6a0d709c7709b7cedbf600f7c/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L656)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

This service contract is incorrect there, the logic to do this should be in pipeline service. User Group service should only expose these contracts.
addParents(String accountId, String userGroupId, Set<UserGroupEntityReference> parentsToAdd)
removeParents(String accountId, String userGroupId, Set<UserGroupEntityReference> parentsToRemove)
</blockquote></details>

Done.
___
*[400-rest/src/test/java/software/wings/service/PipelineServiceTest.java, line 1713 at r5](https://reviewable.io/reviews/harness/harness-core/30292#-MvUDrkb3dKMtdL8_med:-MvUIeAvAWq-mcqPAIEm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/81924526af8637e6a0d709c7709b7cedbf600f7c/400-rest/src/test/java/software/wings/service/PipelineServiceTest.java#L1713)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

??
</blockquote></details>

Done.

**Review by gupta-utkarsh — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 3 files at r4, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: 11 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/test/java/software/wings/service/impl/UserGroupServiceImplTest.java, line 1356 at r6](https://reviewable.io/reviews/harness/harness-core/30292#-MvXwmJSEG1j2RUidU3v:-MvXwmJSEG1j2RUidU3w:bo9qnty) ([raw file](https://github.com/harness/harness-core/blob/0617027f7e7ea830118051891ca1e739bfd1fff4/400-rest/src/test/java/software/wings/service/impl/UserGroupServiceImplTest.java#L1356)):*
> ```Java
>   //  @Owner(developers = VIKAS_M)
>   //  @Category(UnitTests.class)
>   //  public void test_updateUserGroupParents() {
> ```

Why is this test commented?

**Review by karansiwach360 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292#-:-MvXxoBM0wH76sIkVFec:bnfp4nl)* status: 11 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[400-rest/src/test/java/software/wings/service/impl/UserGroupServiceImplTest.java, line 1356 at r6](https://reviewable.io/reviews/harness/harness-core/30292#-MvXwmJSEG1j2RUidU3v:-MvY3pui5p4tHjEI5oKK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0617027f7e7ea830118051891ca1e739bfd1fff4/400-rest/src/test/java/software/wings/service/impl/UserGroupServiceImplTest.java#L1356)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

Why is this test commented?
</blockquote></details>

Done.

**Review by gupta-utkarsh — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292#-:-MvYdJNT1xgqtyBk6NAk:bnfp4nl)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: 11 file(s) to review. 1 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/30292#-MvYu2B75mpby855f_QF:-MvYu2B75mpby855f_QG:b-a45spk) (no related file):*
Since we have approval steps and notification strategies in workflows as well which refer to user groups, we should probably have ticket to add them as well in usergroup parents.

---
___
*[400-rest/src/main/java/software/wings/beans/UserGroupEntityReference.java, line 16 at r7](https://reviewable.io/reviews/harness/harness-core/30292#-MvYpRWN0eJ2YCO8Sbq-:-MvYpRWN0eJ2YCO8Sbq0:b57g44k) ([raw file](https://github.com/harness/harness-core/blob/ad040e1afe5859db47926d87cc4480f7032a1ea4/400-rest/src/main/java/software/wings/beans/UserGroupEntityReference.java#L16)):*
> ```Java
>   private String id;
>   private String appId;
>   private String accountId;
> ```

nit: accountId is redundant here. It will always be same as userGroup accountId.
___
*[400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java, line 662 at r7](https://reviewable.io/reviews/harness/harness-core/30292#-MvYssSR0tBrZ_reUL7P:-MvYssSR0tBrZ_reUL7Q:berljbu) ([raw file](https://github.com/harness/harness-core/blob/ad040e1afe5859db47926d87cc4480f7032a1ea4/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L662)):*
> ```Java
>     }
>     userGroup.addParent(UserGroupEntityReference.builder()
>                             .entityType("PIPELINE")
> ```

It's better to have entityType in method declaration itself, in case if we want to use it in future for other entities.
___
*[400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java, line 678 at r7](https://reviewable.io/reviews/harness/harness-core/30292#-MvYt45-E1pdHklPla5M:-MvYt45-E1pdHklPla5N:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/ad040e1afe5859db47926d87cc4480f7032a1ea4/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L678)):*
> ```Java
>     }
>     userGroup.removeParent(UserGroupEntityReference.builder()
>                                .entityType("PIPELINE")
> ```

same here

**Review by inderschera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: Some of the checks are too old. 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[390-db-migration/src/main/java/io/harness/migrations/all/AddPipelinesReferenceToUserGroups.java, line 30 at r8](https://reviewable.io/reviews/harness/harness-core/30292#-Mw5YYlJ0BQUSZ0C-Qtk:-Mw5YYlJ0BQUSZ0C-Qtl:b23q7qg) ([raw file](https://github.com/harness/harness-core/blob/329657ac736fc22e211539c1699d1e66ef4bb5cc/390-db-migration/src/main/java/io/harness/migrations/all/AddPipelinesReferenceToUserGroups.java#L30)):*
> ```Java
>   public void migrate() {
>     log.info("Starting to add pipelines reference in userGroups.");
>     try (HIterator<Account> accounts = new HIterator<>(wingsPersistence.createQuery(Account.class).fetch())) {
> ```

In past migrations, I have seen issues on holding iterators for too long. They might get disconnected if we hold them for too long. I would suggest to get all accounts in a list and then do migration using that list.
___
*[390-db-migration/src/main/java/io/harness/migrations/all/AddPipelinesReferenceToUserGroups.java, line 58 at r8](https://reviewable.io/reviews/harness/harness-core/30292#-Mw5bwzo750x0tuWQVES:-Mw5bwzo750x0tuWQVET:bysie4f) ([raw file](https://github.com/harness/harness-core/blob/329657ac736fc22e211539c1699d1e66ef4bb5cc/390-db-migration/src/main/java/io/harness/migrations/all/AddPipelinesReferenceToUserGroups.java#L58)):*
> ```Java
> 
>     for (String id : parentsToRemove) {
>       userGroupService.removeParentsReference(id, pipeline.getAccountId(), pipeline.getAppId(), pipeline.getUuid());
> ```

Instead of updating usergroups per pipeline, it's better to first get all parents of a user group and at after iterating all pipelines for account, do one single update to update parents in usergroup.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: 11 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[390-db-migration/src/main/java/io/harness/migrations/all/AddPipelinesReferenceToUserGroups.java, line 30 at r8](https://reviewable.io/reviews/harness/harness-core/30292#-Mw5YYlJ0BQUSZ0C-Qtk:-Mw6EbCT-1PrqU_tjHS1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/329657ac736fc22e211539c1699d1e66ef4bb5cc/390-db-migration/src/main/java/io/harness/migrations/all/AddPipelinesReferenceToUserGroups.java#L30)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

In past migrations, I have seen issues on holding iterators for too long. They might get disconnected if we hold them for too long. I would suggest to get all accounts in a list and then do migration using that list.
</blockquote></details>

Done.
___
*[390-db-migration/src/main/java/io/harness/migrations/all/AddPipelinesReferenceToUserGroups.java, line 58 at r8](https://reviewable.io/reviews/harness/harness-core/30292#-Mw5bwzo750x0tuWQVES:-Mw6Ebs58qfyEKvg_V8e:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/329657ac736fc22e211539c1699d1e66ef4bb5cc/390-db-migration/src/main/java/io/harness/migrations/all/AddPipelinesReferenceToUserGroups.java#L58)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Instead of updating usergroups per pipeline, it's better to first get all parents of a user group and at after iterating all pipelines for account, do one single update to update parents in usergroup.
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java, line 257 at r5](https://reviewable.io/reviews/harness/harness-core/30292#-MvUDfDW61j3PmakDaGX:-Mw6Ef1_3bIAfUF7PxXV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/81924526af8637e6a0d709c7709b7cedbf600f7c/400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java#L257)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

Please get the changes in this file reviewed by CDC team as well.
</blockquote></details>

Done.

**Review by inderschera — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, 1 of 2 files at r3, 1 of 3 files at r4, 2 of 6 files at r6, 2 of 2 files at r7, 1 of 2 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained.

**Review by inderschera — DISMISSED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: Some of the checks are too old. 4 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by inderschera — DISMISSED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 1 of 2 files at r3, 1 of 3 files at r4, 2 of 6 files at r6, 2 of 2 files at r7, 1 of 2 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: 4 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 1 of 2 files at r3, 1 of 3 files at r4, 2 of 6 files at r6, 1 of 2 files at r7, 1 of 2 files at r9, 1 of 1 files at r10, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: 1. unresolved discussions.

**Review by gupta-utkarsh — COMMENTED** [review]
> Reviewed 1 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30292)* status: :shipit: complete! ✓

**Pull request merged**
