### PR TITLE
fix: [OIP-762]: Refactoring the logic to get the control data start timestamp

### PR DESCRIPTION
**Pull request by dhruv-harness**
## Describe your changes
Refactoring the logic to get control data start timestamp in the overview API response so that it is agnostic of the verification result and only depends on the configuration & host detection. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51553)

### CODE REVIEW

**Comment by dhruv-harness** [comment]
trigger messagecheck

**Comment by n00bitax** [comment]
some queries: why are writing business logic in a file called VerifyStepResourceImpl ?
and why do have 2 resources CVNGStepResource & VerifyStepResource ?

**Comment by n00bitax** [comment]
looks like we have lot of weird code :
`public abstract class CanaryBlueGreenAdditionalInfo extends AdditionalInfo {
  Set<HostSummaryInfo> primary;
  Set<HostSummaryInfo> canary;

  private String primaryInstancesLabel;
  private String canaryInstancesLabel;`
in the base class we already have things like canary and Labels and then we have a specific class for BlueGreen BlueGreenAdditionalInfo

**Comment by dhruv-harness** [comment]
> some queries: why are writing business logic in a file called VerifyStepResourceImpl ? and why do have 2 resources CVNGStepResource & VerifyStepResource ?

The VerifyStepResource interface defines the API interface and the VerifyStepResourceImpl class provides the implementation. Unlike other resource classes, which act as the API interfaces, this class is responsible for the business implementation. 
PS- From Jan 2023 forward, all APIs were supposed to follow this pattern.

We have a separate class because the previous class was providing obsolete APIs which we were deprecating, to ensure the API paths are cleaner and overall code is more readable, we kept the classes separate.

**Comment by dhruv-harness** [comment]
>looks like we have lot of weird code :
>
>```
>public abstract class CanaryBlueGreenAdditionalInfo extends AdditionalInfo {
>  Set<HostSummaryInfo> primary;
>  Set<HostSummaryInfo> canary;
>
>  private String primaryInstancesLabel;
>  private String canaryInstancesLabel;
>```
>in the base class we already have things like canary and canaryInstancesLabel and then we have a specific class for BlueGreen called BlueGreenAdditionalInfo, so blue-green has these fields even tho we created a specific class just for bluegreen

The BlueGreenAdditionalInfo class defines the values for these labels, which is before and after. The Canary child class will define the values as primary and canary. The field names could have been control and test instead in the base class.

**Comment by n00bitax** [comment]
My opinion is we should rename it to control and test also the class name itself looks wrong CanaryBlueGreenAdditionalInfo, rather call it something like HostBasedVerification as it covers rolling too?

**Comment by dhruv-harness** [comment]
> I wasn't pointing to having VerifyStepResource interface define the API interface and the VerifyStepResourceImpl but rather why the logic isn't in the respective service classes but in the ResourceImpl . Isn't that the standard we follow?

Usually yes, but in this case the resource impl class would be almost useless and we would have to create a new service class to do the same thing.

**Comment by dhruv-harness** [comment]
> My opinion is we should rename it to control and test also the class name itself looks wrong CanaryBlueGreenAdditionalInfo, rather call it something like HostBasedVerification as it covers rolling too?

here blue green covers rolling also, but yeah I agree with you, we can clean some of this in upcoming PRs

**Pull request merged**
