### PR TITLE
[fix]: [PL-28358]: Add DB query improvement to fetch only matching accountId, userGroupId from userInvites collection for updation while unlinking SSO group

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
Currently when in an account there are large number of user invites pending, during SSO UserGroup unlink we fetch all those user invites. Most of them doesn't have userGroup references or invites were not made through user group. In this fix we are only considering those userInvites which are pending and also has reference to the userGroup. On unlink we remove the userGroup reference which is de-linked from userInvites. 
I have tested this in local, however I don't have the performance comparison, where in large number of user invites can be pending (more than 2K). We can have the testing in PreQA with help from QA sanity once it is available in PreQA

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46981)

### CODE REVIEW

**Review by ankit-harness — DISMISSED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46981)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 2495 at r2](https://reviewable.io/reviews/harness/harness-core/46981#-NTwZeziBgQ0c70oc2o7:-NTwZeziBgQ0c70oc2o8:b983doj) ([raw file](https://github.com/harness/harness-core/blob/a003139b894fa6cd067956ff16f03c3cf7d780ab/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L2495)):*
> ```Java
>   public List<UserInvite> getInvitesFromAccountIdAndUserGroupId(String accountId, String userGroupId) {
>     Query<UserInvite> userInviteQuery = wingsPersistence.createQuery(UserInvite.class)
>                                             .filter(UserInvite.ACCOUNT_ID_KEY2, accountId)
> ```

Can we use ACCOUNT_ID_KEY



_Code quote:_
```Java
ACCOUNT_ID_KEY2
```

**Review by pbarapatre10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46981)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 2495 at r2](https://reviewable.io/reviews/harness/harness-core/46981#-NTwZeziBgQ0c70oc2o7:-NTwjvFR6hrWTWkrdD8r:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a003139b894fa6cd067956ff16f03c3cf7d780ab/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L2495)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we use ACCOUNT_ID_KEY
</blockquote></details>

Done.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46981)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46981#-:-NTx1q5jDB0V4gifhgKB:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Pull request merged**
