### PR TITLE
feat: [PL-24987]: scim username identifier change

### PR DESCRIPTION
**Pull request by ujjawal-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32853)

### CODE REVIEW

**Comment by piyush-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 357 at r1](https://reviewable.io/reviews/harness/harness-core/32853#-N1NhT1TAjc_EPSHKGoH:-N1NhT1TAjc_EPSHKGoI:b-cv1rv2) ([raw file](https://github.com/harness/harness-core/blob/5ca117c6c02997df153a778cfaaef33cfba73c8d/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L357)):*
> ```Java
>     log.info("NGSCIM: Creating group in account {} where name {} with call: {}", accountId, groupQuery.getDisplayName(),
>         groupQuery);
>     String userGroupIdentifier = isNotEmpty(groupQuery.getDisplayName())
> ```

This condition is wrong, Identifier will be set to Empty which is not correct, Also we need to make this change in Search as well

**Comment by ujjawal-harness** [comment]
trigger ti4

**Comment by ujjawal-harness** [comment]
trigger messagecheck

**Comment by ujjawal-harness** [comment]
trigger ti0

**Review by piyush-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32853)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — DISMISSED** [review]
please add unit test, in a follow up PR

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32853#-:-N1da4bm8uXHmJuNfyyL:b19p1vk)* status: :shipit: complete! ✓

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32853)* status: :shipit: complete! ✓

**Review by piyush-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32853)* status: :shipit: complete! ✓

**Pull request merged**
