### PR TITLE
feat: [PL-23110]: added user id in audits

### PR DESCRIPTION
**Pull request by ujjawal-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31121)

### CODE REVIEW

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31121)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/security/ThreadLocalUserProvider.java, line 23 at r1](https://reviewable.io/reviews/harness/harness-core/31121#-MxJiwIt2KgAk6yuvas-:-MxJiwIt2KgAk6yuvas0:b8kwuxy) ([raw file](https://github.com/harness/harness-core/blob/25c40296fb9e29bc062cb682cb02a49083e72cf5/400-rest/src/main/java/software/wings/security/ThreadLocalUserProvider.java#L23)):*
> ```Java
> public class ThreadLocalUserProvider implements UserProvider {
>   public static EmbeddedUser populateEmbeddedUser(User user) {
>     EmbeddedUser embeddedUser = EmbeddedUser.builder()
> ```

Why not use passed User object ?

**Review by piyush-harness — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31121)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31121)* status: :shipit: complete! ✓

**Review by bojanmicovic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31121)* status: :shipit: complete! ✓

**Pull request merged**
