### PR TITLE
fix: [CDS-70516]: Fixing reconcilliation flow for remote input sets from BE

### PR DESCRIPTION
**Pull request by Y0709**
We decided to always send pipeline branch and input set branch when available from UI
Fix made - take input set branch from git context when the repo is same. Also added a check when the repo is same and branch is diff we are throwing an exception. Also added check to ignore input set branch when repo is different for input set and pipeline 
With setting disabled - Diff repo cases not possible

1) Same repo same branch -- Works( in case call made from input set listing page it works only when input set on default branch)
2) Same repo diff branch --  Fails and show the expected new error for invalid configuration

With setting enabled -- 

1) Same repo same branch -- reconcillation works ( in case call made from input set listing page it works only when input set on default branch)
2) Same repo diff branch -- reconcillation fails same as above
3) Diff repo input set default -- reconcillation works 
4) Diff repo input set non default -- reconcillation fails

Also Tested with inline input sets
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48990)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48990)* status: Some of the checks are too old. 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java` line 382 at r3](https://reviewable.io/reviews/harness/harness-core/48990#-NYHeO7rBfeJohDAFnIj:-NYHeO7rBfeJohDAFnIk:b-4sxug3) ([raw file](https://github.com/harness/harness-core/blob/cc548ce4d828b05564db6374a9c33373dba9031f/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java#L382)):*
> ```Java
>     boolean isDifferentRepoForPipelineAndInputSetsAccountSettingEnabled =
>         inputSetsApiUtils.isDifferentRepoForPipelineAndInputSetsAccountSettingEnabled(accountId);
>     if (isDifferentRepoForPipelineAndInputSetsAccountSettingEnabled && EmptyPredicate.isEmpty(pipelineBranch)) {
> ```

this check should be on service level

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/InputSetValidationHelper.java` line 201 at r3](https://reviewable.io/reviews/harness/harness-core/48990#-NYHf18dEx85GgocwoFf:-NYHf18dEx85GgocwoFg:b-rzmezo) ([raw file](https://github.com/harness/harness-core/blob/cc548ce4d828b05564db6374a9c33373dba9031f/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/InputSetValidationHelper.java#L201)):*
> ```Java
>         }
>       } else {
>         throw new InvalidRequestException("Input Set branch not provided");
> ```

why is this an invalid case? Input set branch can be empty, empty means it should come from default branch.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/InputSetValidationHelper.java` line 206 at r3](https://reviewable.io/reviews/harness/harness-core/48990#-NYHfd7f4su5firhvGB7:-NYHfd7f4su5firhvGB8:b-hk6raj) ([raw file](https://github.com/harness/harness-core/blob/cc548ce4d828b05564db6374a9c33373dba9031f/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/InputSetValidationHelper.java#L206)):*
> ```Java
>       if (!inputSetBranch.equals(pipelineBranch)) {
>         throw new InvalidRequestException(
>             "Reconciliation is not allowed as the configuration is not supported. Pipeline and InputSet must be present on the same branch when they are in the same repository");
> ```

"as the configuration is not supported" is not understandable. We can keep it simple "Reconciliation is not allowed for given input-set. Pipeline and input-set ..... same repository"

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/InputSetValidationHelper.java` line 209 at r3](https://reviewable.io/reviews/harness/harness-core/48990#-NYHg3_j5_95_zmdDGq1:-NYHg3_j5_95_zmdDGq2:b2aztx9) ([raw file](https://github.com/harness/harness-core/blob/cc548ce4d828b05564db6374a9c33373dba9031f/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/InputSetValidationHelper.java#L209)):*
> ```Java
>       }
>     } else {
>       if (!isDifferentRepoForPipelineAndInputSetsAccountSettingEnabled) {
> ```

This if gets called even if pipeline repo is null or input set repo is null. We should fix it. It should only be called if both repo are not null and not-matching.

**Comment by Y0709** [comment]
trigger uts

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by Y0709** [comment]
trigger review

**Comment by Y0709** [comment]
trigger messagecheck

**Pull request merged**
