### PR TITLE
feat: [SRM-11328]: Modified Search on Monitored Service list view and graph view

### PR DESCRIPTION
**Pull request by arpit-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36098)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* Code issue 4 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36098)

**Review by dhruv-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36098)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 850 at r1](https://reviewable.io/reviews/harness/harness-core/36098#-N8vqMgu5ZG4suwcTEuX:-N8vqMgu5ZG4suwcTEuY:b-tz05a1) ([raw file](https://github.com/harness/harness-core/blob/ef0779189fd3b6611c1f1fed713da6a6b264fb41/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L850)):*
> ```Java
>   private List<MonitoredService> filterMonitoredService(
>       List<MonitoredService> monitoredServices, Map<String, String> serviceIdNameMap, String filter) {
>     if (filter != null) {
> ```

If filter is null, we are returning the same argument as monitoredServices, but I see we are passing a single monitored service in this method. Is this method being overloaded?
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 854 at r1](https://reviewable.io/reviews/harness/harness-core/36098#-N8vrBGF-f7PDAKgo-qU:-N8vrBGG57MF5kq9sEkQ:bep53dw) ([raw file](https://github.com/harness/harness-core/blob/ef0779189fd3b6611c1f1fed713da6a6b264fb41/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L854)):*
> ```Java
>                               .filter(monitoredService
>                                   -> isEmpty(filter)
>                                       || serviceIdNameMap.get(monitoredService.getServiceIdentifier())
> ```

It will throw NPE if the serviceIdNameMap is null. and we are passing null for it
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 982 at r1](https://reviewable.io/reviews/harness/harness-core/36098#-N8vru4l8FHDzGX3IZwB:-N8vru4l8FHDzGX3IZwC:b-1owo1m) ([raw file](https://github.com/harness/harness-core/blob/ef0779189fd3b6611c1f1fed713da6a6b264fb41/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L982)):*
> ```Java
>         nextGenService.getServiceIdNameMap(projectParams, new ArrayList<>(serviceIdentifiers));
>     monitoredServices = filterMonitoredService(monitoredServices, serviceIdNameMap, filter);
>     return filterMonitoredService(monitoredServices, serviceIdNameMap, filter);
> ```

We are calling the filterMonitoredService method on its own result?

**Review by arpit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36098)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 850 at r1](https://reviewable.io/reviews/harness/harness-core/36098#-N8vqMgu5ZG4suwcTEuX:-N8wY07B4HCcNx5GqZyB:bgnbltv) ([raw file](https://github.com/harness/harness-core/blob/ef0779189fd3b6611c1f1fed713da6a6b264fb41/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L850)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

If filter is null, we are returning the same argument as monitoredServices, but I see we are passing a single monitored service in this method. Is this method being overloaded?
</blockquote></details>

Will remove the redundant null check for filter.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 854 at r1](https://reviewable.io/reviews/harness/harness-core/36098#-N8vrBGF-f7PDAKgo-qU:-N8wYigc-rFP8WyfMai5:b-p3osvu) ([raw file](https://github.com/harness/harness-core/blob/ef0779189fd3b6611c1f1fed713da6a6b264fb41/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L854)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

It will throw NPE if the serviceIdNameMap is null. and we are passing null for it
</blockquote></details>

The serviceIdNameMap will never be null Except in the case when the monitoredService is null too.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 982 at r1](https://reviewable.io/reviews/harness/harness-core/36098#-N8vru4l8FHDzGX3IZwB:-N8wZ1Du4ORFnj3PjVT0:b-1mda08) ([raw file](https://github.com/harness/harness-core/blob/ef0779189fd3b6611c1f1fed713da6a6b264fb41/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L982)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

We are calling the filterMonitoredService method on its own result?
</blockquote></details>

Removed redundant call.

**Review by dhruv-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36098)* status: 3. unresolved discussions.

**Pull request merged**
