### PR TITLE
[feat]: [CDS-84826]: Exports POJO and plan-creation framework changes

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

We want to introduce the exports in the YAML so that users can define their exports at any step/stage level(Via template as well) and use those exports in subsequent steps.

What is the change: Adding POJO for the exports and populating the exports in the planNode if provided in the YAML. 

Impact: Since we are just populating one field in the planNode and have the null check while setting in the proto. So there should not be any impact on existing flows.

Testing: Tested the pipelines with having exports in steps/stages and without exports. 

- There is no issue when the exports are not present in the step/stage.
- When the exports are provided in YAML, these are being saved in the planNode as json string. And we can use them during the execution in subsequent PRs.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55614)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55614)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorService.java` line 303 at r1](https://reviewable.io/reviews/harness/harness-core/55614#-NjfMgG_8EBYyBZo8K1v:-NjfMgG_8EBYyBZo8K1w:b3ivxfz) ([raw file](https://github.com/harness/harness-core/blob/7ed1a17826da1222bb75a97d2126602cbbbd7c6e/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorService.java#L303)):*
> ```Java
>               planForField, serviceName, field, currentNodeServiceAffinity);
>           PlanCreatorServiceHelper.decorateResponseWithParentInfo(dependency, planForField);
>           PlanCreatorServiceHelper.decorateNodeWithExports(planForField, field);
> ```

Can we introduce getExports as abstract method in plan creator, so framework is not deserialising this and maybe provide this helper which planCreators are impl
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 234 at r1](https://reviewable.io/reviews/harness/harness-core/55614#-NjfMXXR6rJHUy7v4TTA:-NjfMXXR6rJHUy7v4TTB:bhnb885) ([raw file](https://github.com/harness/harness-core/blob/7ed1a17826da1222bb75a97d2126602cbbbd7c6e/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L234)):*
> ```Java
>     if (exportsNode == null || planForField.getPlanNode() == null) {
>       return;
>     }
> ```

can we move this condition first, so we are not doing get without planNode available even



_Code quote:_
```Java
    if (exportsNode == null || planForField.getPlanNode() == null) {
      return;
    }
```

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55614)* status: 1 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorService.java` line 303 at r1](https://reviewable.io/reviews/harness/harness-core/55614#-NjfMgG_8EBYyBZo8K1v:-NjfXkOE4hUPGAg37MQE:bdk7ku9) ([raw file](https://github.com/harness/harness-core/blob/7ed1a17826da1222bb75a97d2126602cbbbd7c6e/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorService.java#L303)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we introduce getExports as abstract method in plan creator, so framework is not deserialising this and maybe provide this helper which planCreators are impl
</blockquote></details>

Why is this needed?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 234 at r1](https://reviewable.io/reviews/harness/harness-core/55614#-NjfMXXR6rJHUy7v4TTA:-NjfY9vf79f2UgiccXp_:bw7wmzd) ([raw file](https://github.com/harness/harness-core/blob/7ed1a17826da1222bb75a97d2126602cbbbd7c6e/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L234)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we move this condition first, so we are not doing get without planNode available even
</blockquote></details>

Why this is needed?
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/PlanNode.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/55614#-NjfYIePDpkGKkjAF_rt:-NjfYIePDpkGKkjAF_ru:b-8edeoq) ([raw file](https://github.com/harness/harness-core/blob/7ed1a17826da1222bb75a97d2126602cbbbd7c6e/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/PlanNode.java#L69)):*
> ```Java
>   @Singular List<TimeoutObtainment> timeoutObtainments;
>   // Json format string for the exports map.
>   String exports;
> ```

why not actual object why json?
___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/plan_node_proto.proto` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/55614#-NjfYOTJ-HVTm6atyyyJ:-NjfYOTJ-HVTm6atyyyK:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/7ed1a17826da1222bb75a97d2126602cbbbd7c6e/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/plan_node_proto.proto#L42)):*
> ```proto
>   map<string, io.harness.pms.contracts.advisers.AdvisorObtainmentList> adviserObtainmentsForExecutionMode = 21;
>   repeated string stepInputsKeyExclude = 22;
>   string exports = 23;
> ```

ditto

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/PlanNode.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/55614#-NjfYIePDpkGKkjAF_rt:-Njf_V6tEM_TRcqqILn2:bwkj0ra) ([raw file](https://github.com/harness/harness-core/blob/7ed1a17826da1222bb75a97d2126602cbbbd7c6e/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/PlanNode.java#L69)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

why not actual object why json?
</blockquote></details>

This object will be created in plan-creator-service then it needs to be sent to pipeline-service via grpc response. But JAVA POJO can not be sent via grpc so sending as json-string. And can not create exact object in proto because the value is of type object(It can be string/number/list or complex object as well but proto does not support genetic data-type)

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/plan_node_proto.proto` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/55614#-NjfYOTJ-HVTm6atyyyJ:-NjfanuG-_geNGoXp-hK:b-eehdr3) ([raw file](https://github.com/harness/harness-core/blob/7ed1a17826da1222bb75a97d2126602cbbbd7c6e/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/plan_node_proto.proto#L42)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

We will need either map or jsonString during the execution(for publishing the outcomes) so not deserialising into the map of objects.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55614)* status: 1 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 234 at r1](https://reviewable.io/reviews/harness/harness-core/55614#-NjfMXXR6rJHUy7v4TTA:-NjfbfYa6q7IuHz7q5wL:bzhzfd4) ([raw file](https://github.com/harness/harness-core/blob/7ed1a17826da1222bb75a97d2126602cbbbd7c6e/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L234)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Why this is needed?
</blockquote></details>

yeah this will be removed and moved to individual creators

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55614)* status: 6 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 459 at r3](https://reviewable.io/reviews/harness/harness-core/55614#-NjkxFo73SeZ73QbdeUW:-NjkxFo73SeZ73QbdeUX:b-ssalqq) ([raw file](https://github.com/harness/harness-core/blob/cae05f64daf1033883cb53cd71fdb44bdb217dc6/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L459)):*
> ```Java
>         Set<FailureType> failureTypes, NGFailureActionTypeV1 actionType, String nextNodeUuid);
>   }
>   public Map<String, Object> getExportsFromYamlField(YamlField field, String yamlVersion) {
> ```

if we have http stepNode contains exports, it would work out of the box right? without reading yaml field

**Comment by brijeshdhakar** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 459 at r3](https://reviewable.io/reviews/harness/harness-core/55614#-NjkxFo73SeZ73QbdeUW:-Njl2Hrz2uqo71ZOSxrU:bhkqzku) ([raw file](https://github.com/harness/harness-core/blob/cae05f64daf1033883cb53cd71fdb44bdb217dc6/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L459)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

if we have http stepNode contains exports, it would work out of the box right? without reading yaml field
</blockquote></details>

Archit we want to get the value field and not the wrapper(Having desc and value field) so we will need to map once.

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55614)* status: 2 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 459 at r3](https://reviewable.io/reviews/harness/harness-core/55614#-NjkxFo73SeZ73QbdeUW:-NjlbveX4iMGbtIrgE2i:b-64umr) ([raw file](https://github.com/harness/harness-core/blob/cae05f64daf1033883cb53cd71fdb44bdb217dc6/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L459)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Archit we want to get the value field and not the wrapper(Having desc and value field) so we will need to map once.
</blockquote></details>

Let's not create this method here. We should precisely define the definition of exports and the plan creator should parse the field and supply it. For starter, we only have this for step group and stage so let's put these there
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/PlanNode.java` line 50 at r3](https://reviewable.io/reviews/harness/harness-core/55614#-NjlbHtx8TSfvy3y3IJU:-NjlbHtx8TSfvy3y3IJV:b-ac2zrx) ([raw file](https://github.com/harness/harness-core/blob/cae05f64daf1033883cb53cd71fdb44bdb217dc6/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/PlanNode.java#L50)):*
> ```Java
>   @NonFinal @lombok.Setter String executionInputTemplate;
>   @Singular List<RefObject> refObjects;
>   Map<String, Object> exports;
> ```

why object?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PartialPlanCreator.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/55614#-Njlb_HfBtraaacZuXPD:-Njlb_HfBtraaacZuXPE:b-g03uye) ([raw file](https://github.com/harness/harness-core/blob/cae05f64daf1033883cb53cd71fdb44bdb217dc6/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PartialPlanCreator.java#L24)):*
> ```Java
>   Map<String, Set<String>> getSupportedTypes();
> 
>   default void setExportsInNode(PlanCreationResponse response, YamlField yamlField, String yamlVersion) {
> ```

This doesn't belong here. getExports method should be in plan creators and it should return the definition that you define and not what is in the yaml

**Comment by brijeshdhakar** [comment]
Closing this PR as i have create another pr(https://github.com/harness/harness-core/pull/55799) for contracts. And will implement make the changes in plan-creators to populate the exports field.

**Pull request closed without merging**
