### PR TITLE
feat: [FFM-3458]: Increase Java SDK metrics buffer size

### PR DESCRIPTION
**Pull request by bmjen**
## Describe your changes

Due to the high number of evaluations we are seeing a lot of metrics post requests from the Java SDK.

The buffer is currently 1024, but given we have around 250 flags who’s identifiers are around 6Kb we are constantly flushing.

We need to:
 - Make the buffer size on platform configurable
 - Increase the default buffer size
 - Update the Java SDK to address the Exception occurred: ConcurrentModificationExceptio error
 
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33562)

### CODE REVIEW

**Review by davejohnston — APPROVED** [review]
LGTM

**Review by davejohnston — DISMISSED** [review]
> Reviewed 21 of 21 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33562)* status: :shipit: complete! ✓

**Review by enver-bisevac — APPROVED** [review]

**Comment by bmjen** [comment]
trigger messagecheck

**Review by enver-bisevac — APPROVED** [review]

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 20 of 21 files at r1, 1 of 3 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33562)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
trigger ti0

**Pull request merged**
