### PR TITLE
[fix]: [CDS-85828]: Fixed the setup references when the entity is moved from inline to remote

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have added to handle the setup references when the entity is moved from inline to remote by deleting the references and populating the references only if the entity is created on a default branch. Have tested out the following for both pipelines and templates:
1. Setup references when the entity has been moved inline to remote on non default branch -> the references are deleted and no new references are computed
2. Setup references when the entity has been moved inline to remote on default branch -> the references are deleted and new references are computed 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56327)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger messagecheck

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56327)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 1143 at r2](https://reviewable.io/reviews/harness/harness-core/56327#-NktqiHd2CYAw2LwKtZu:-NktqiHd2CYAw2LwKtZv:b-j2i5rx) ([raw file](https://github.com/harness/harness-core/blob/ff0d2b5105c4a9051184e13438d2b7b53b4d9e2d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L1143)):*
> ```Java
> 
>   private void computeSetupReferences(PipelineEntity pipelineEntity, MoveConfigOperationDTO moveConfigDTO) {
>     if (INLINE_TO_REMOTE.equals(moveConfigDTO.getMoveConfigOperationType())) {
> ```

We need to handle same for template service as well, right?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56327)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 1142 at r2](https://reviewable.io/reviews/harness/harness-core/56327#-Nktqb2E-1pGjdDmx9wB:-Nkxu61XCvO8Fk8rrSKl:bd3znth) ([raw file](https://github.com/harness/harness-core/blob/ff0d2b5105c4a9051184e13438d2b7b53b4d9e2d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L1142)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if this method throws an exception? It will error out the import request itself, right?
</blockquote></details>

have handled this
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 1143 at r2](https://reviewable.io/reviews/harness/harness-core/56327#-NktqiHd2CYAw2LwKtZu:-Nkxu8tI9-ttS9iX-7AO:b1dy4il) ([raw file](https://github.com/harness/harness-core/blob/ff0d2b5105c4a9051184e13438d2b7b53b4d9e2d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L1143)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We need to handle same for template service as well, right?
</blockquote></details>

added for templates

**Comment by adivishy1** [comment]
trigger uts

**Comment by adivishy1** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56327)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger uts

**Comment by adivishy1** [comment]
trigger review

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56327)* status: :shipit: complete! ✓

**Pull request merged**
