### PR TITLE
feat: [PL-27264]: Support protos dependencies in build cleaner

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes

Support adding dependency on proto targets too. 

Also made updating existing build files as the default option. Also added an option "overwriteExistingBuildFiles" to overwrite the build files.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37272)

### CODE REVIEW

**Comment by gn-harness** [comment]
trigger messagecheck

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37272)

**Review by piyush-harness — APPROVED** [review]
> Reviewed 8 of 17 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37272)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Review by gn-harness — COMMENTED** [review]
+1; Just harder to get review with different timezones, so succumbed to the timeline pressure :)

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37272#-:-NBT2AgeEVdpdlgJxutn:bll4b3g)* status: 18 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BUILD.bazel` line 9 at r4](https://reviewable.io/reviews/harness/harness-core/37272#-NBSWyjA0-vf2LnSOVcw:-NBSuW4m-Ilv_RPUw4iB:b-vkh2gs) ([raw file](https://github.com/harness/harness-core/blob/42dbc08f29efbee716173c494c8d0fc61c14e38d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BUILD.bazel#L9)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I would say you probably need 'proto' module here as well. Not sure why it wasn't generated. 
</blockquote></details>

Because it was not auto-generated after a point :)  Re-ran the tool and updated! Also working on a tool to keep running build-cleaner in the background
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/proto/ProtoBuildMapper.java` line 56 at r4](https://reviewable.io/reviews/harness/harness-core/37272#-NBSXrJH9Zu9RAaIf6m6:-NBSwgNo5vwcvHZCQFW9:btbllc2) ([raw file](https://github.com/harness/harness-core/blob/42dbc08f29efbee716173c494c8d0fc61c14e38d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/proto/ProtoBuildMapper.java#L56)):*
> Paths.get(workspace, srcs).toString();
Done
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/proto/ProtoBuildMapper.java` line 69 at r4](https://reviewable.io/reviews/harness/harness-core/37272#-NBSZAN_-lxotMyc88Dn:-NBSx85jDhsHCgad1r0b:b4el7of) ([raw file](https://github.com/harness/harness-core/blob/42dbc08f29efbee716173c494c8d0fc61c14e38d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/proto/ProtoBuildMapper.java#L69)):*
> IllegalStateException
Done
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/proto/ProtoFile.java` line 21 at r4](https://reviewable.io/reviews/harness/harness-core/37272#-NBSape79j4r1oV4VG7n:-NBT2824A6EY-qCgHVXM:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/42dbc08f29efbee716173c494c8d0fc61c14e38d/tools/build-cleaner/src/main/java/io/harness/buildcleaner/proto/ProtoFile.java#L21)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Make all these ''final' to make the object immutable. It's nice that it uses immutable lists so it will be fully immutable, not just reference immutable. If some of the fields are optional you can also give them a default value for the builder with '@Default' lombok annotation. Also if some of the fields are mandatory (like 'packageName') you should create your own 'builder(...)' method (lombok then skips doing this for you). Something like [here](https://stackoverflow.com/a/30867286), but having hidden builder is actually wrong (because it's not really hidden), just call constructor on its place instead. 
</blockquote></details>

Done

**Pull request merged**
