### PR TITLE
[feat]: [SRM-10567]: Notification Cool Off Logic for SLO & Monitored Service + UTs

### PR DESCRIPTION
**Pull request by kapil-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33061)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33061)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleRef.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/33061#-N1qFJFQ149NjcaXplCE:-N1qFJFQ149NjcaXplCF:b2kjsbv) ([raw file](https://github.com/harness/harness-core/blob/8226d6ccba505ad14ec1acce19606d2816b6848b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleRef.java#L19)):*
> ```Java
>   @NotNull String notificationRuleRef;
>   @NotNull boolean enabled;
>   @NotNull long lastSuccessFulNotificationTime;
> ```

Also it has a typo. We can also make it Instant
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleRef.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/33061#-N1qFfZB71nozBkelUm7:-N1qFfZB71nozBkelUm8:bbv7zdj) ([raw file](https://github.com/harness/harness-core/blob/8226d6ccba505ad14ec1acce19606d2816b6848b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleRef.java#L21)):*
> ```Java
>   @NotNull long lastSuccessFulNotificationTime;
> 
>   public boolean isEligible(long currentInstant, long coolOffDuration) {
> ```

instead of long use Instant and Duration
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/utils/NotificationRuleCommonUtils.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/33061#-N1qG0SA4GIoDNbCSbn1:-N1qG0SA4GIoDNbCSbn2:b2trnnx) ([raw file](https://github.com/harness/harness-core/blob/8226d6ccba505ad14ec1acce19606d2816b6848b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/utils/NotificationRuleCommonUtils.java#L46)):*
> ```Java
>       NotificationRuleType notificationRuleType, CVNGNotificationChannelType notificationChannelType) {
>     return String.format("cvng_%s_%s", notificationRuleType.getIdentifier().toLowerCase(),
>         notificationChannelType.getIdentifier().toLowerCase());
> ```

let's call it templateSuffixIdentifier for communicating the intent
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/33061#-N1qGb46CJU4LgrMSPSD:-N1qGb46CJU4LgrMSPSE:b65ambn) ([raw file](https://github.com/harness/harness-core/blob/8226d6ccba505ad14ec1acce19606d2816b6848b/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L103)):*
> ```Java
>   @Inject private NotificationClient notificationClient;
> 
>   public static final long COOL_OFF_DURATION_IN_MILLIS = 3600000;
> ```

use Duration of this constant.
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/ServiceLevelObjectiveServiceImplTest.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/33061#-N1qGyZ8AkY-Fv0U9Amg:-N1qGyZ8AkY-Fv0U9Amh:b-oow7mm) ([raw file](https://github.com/harness/harness-core/blob/8226d6ccba505ad14ec1acce19606d2816b6848b/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/ServiceLevelObjectiveServiceImplTest.java#L115)):*
> ```Java
>   @Inject HPersistence hPersistence;
>   @Inject NotificationRuleService notificationRuleService;
>   @Mock private NotificationClient notificationClient;
> ```

is it possible to write fake for NotificationClient? Similar to io.harness.cvng.client.FakeNextGenService

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33061)* status: 7 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleRef.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/33061#-N1qFJFQ149NjcaXplCE:-N1rVhCX-WWFdUydPfVz:b-xr08b3) ([raw file](https://github.com/harness/harness-core/blob/8226d6ccba505ad14ec1acce19606d2816b6848b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleRef.java#L19)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

Also it has a typo. We can also make it Instant
</blockquote></details>

converted it to an Instant
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleRef.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/33061#-N1qFfZB71nozBkelUm7:-N1rW67R7Ui0Gxw135_8:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8226d6ccba505ad14ec1acce19606d2816b6848b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleRef.java#L21)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

instead of long use Instant and Duration
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/utils/NotificationRuleCommonUtils.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/33061#-N1qG0SA4GIoDNbCSbn1:-N1rW7zL3pQItzWh0ewG:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8226d6ccba505ad14ec1acce19606d2816b6848b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/utils/NotificationRuleCommonUtils.java#L46)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

let's call it templateSuffixIdentifier for communicating the intent
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/33061#-N1qGb46CJU4LgrMSPSD:-N1rW9MO6wG5T3-M_ysI:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8226d6ccba505ad14ec1acce19606d2816b6848b/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L103)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

use Duration of this constant.
</blockquote></details>

done
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/ServiceLevelObjectiveServiceImplTest.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/33061#-N1qGyZ8AkY-Fv0U9Amg:-N1rWAuaEOE7aGA6F6jF:byncq5q) ([raw file](https://github.com/harness/harness-core/blob/8226d6ccba505ad14ec1acce19606d2816b6848b/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/ServiceLevelObjectiveServiceImplTest.java#L115)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

is it possible to write fake for NotificationClient? Similar to io.harness.cvng.client.FakeNextGenService
</blockquote></details>

yes we can, but what will be the benefit of doing this. 
I can see even after having io.harness.cvng.client.FakeNextGenService we still Mock the NextGenService in our UTs, which we are already doing for NotificationClient.

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33061)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleRef.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/33061#-N1qFJFQ149NjcaXplCE:-N1sARUcDkL5PasC6s0y:bqbkkkh) ([raw file](https://github.com/harness/harness-core/blob/8226d6ccba505ad14ec1acce19606d2816b6848b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleRef.java#L19)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

converted it to an Instant
</blockquote></details>

lastSuccessFullNotificationSent

please rename. full has one l missing.



_Code quote:_
```Java
lastSuccessFulNotificationSendInstant
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/33061#-N1qGb46CJU4LgrMSPSD:-N1sAr9kDKRYlKwGd13O:b-3muq6h) ([raw file](https://github.com/harness/harness-core/blob/8226d6ccba505ad14ec1acce19606d2816b6848b/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L103)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

done
</blockquote></details>

public static final Duration COOL_OFF_DURATION = Duration.ofHours(1)
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/ServiceLevelObjectiveServiceImplTest.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/33061#-N1qGyZ8AkY-Fv0U9Amg:-N1sB24lAiDd010eFFZp:b-iccbfw) ([raw file](https://github.com/harness/harness-core/blob/8226d6ccba505ad14ec1acce19606d2816b6848b/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/ServiceLevelObjectiveServiceImplTest.java#L115)):*
>  even after having io.harness.cvng.clie
We don't. You might be looking at the old code before we created FakeNextGenService. 
The idea is to have a default implementation for the cases where you don't worry about the interactions with NotificationClient. You can still Mock it for your tests if you want. That's the testing approach we are moving towards.
You can ignore this comment for now. We can discuss this in the next arch board.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33061)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleRef.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/33061#-N1qFJFQ149NjcaXplCE:-N1s_VG4CZuGqA6IV2pO:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8226d6ccba505ad14ec1acce19606d2816b6848b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleRef.java#L19)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

lastSuccessFullNotificationSent

please rename. full has one l missing.
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/33061#-N1qGb46CJU4LgrMSPSD:-N1s_XJKCzkQGmkG6s2i:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8226d6ccba505ad14ec1acce19606d2816b6848b/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L103)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

public static final Duration COOL_OFF_DURATION = Duration.ofHours(1)
</blockquote></details>

done
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/ServiceLevelObjectiveServiceImplTest.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/33061#-N1qGyZ8AkY-Fv0U9Amg:-N1s_Z2-EJQpDo-p_ONd:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8226d6ccba505ad14ec1acce19606d2816b6848b/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/ServiceLevelObjectiveServiceImplTest.java#L115)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

>  even after having io.harness.cvng.clie
We don't. You might be looking at the old code before we created FakeNextGenService. 
The idea is to have a default implementation for the cases where you don't worry about the interactions with NotificationClient. You can still Mock it for your tests if you want. That's the testing approach we are moving towards.
You can ignore this comment for now. We can discuss this in the next arch board.
</blockquote></details>

done

**Comment by kapil-harness** [comment]
trigger ti3

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3, 24 of 24 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33061)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/monitoredService/MonitoredServiceService.java` line 108 at r4](https://reviewable.io/reviews/harness/harness-core/33061#-N1w9Yhz8APS9Y0ikKlL:-N1w9Yhz8APS9Y0ikKlM:bnwe5de) ([raw file](https://github.com/harness/harness-core/blob/89088fd81b83c31beed585a685856eff3c7b3e4c/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/monitoredService/MonitoredServiceService.java#L108)):*
> ```Java
>       ProjectParams projectParams, String monitoredServiceIdentifier, Long startTime, Long endTime);
> 
>   List<NotificationRule> getNotificationRulesByMonitoredServiceEntity(MonitoredService monitoredService);
> ```

This can be just getNotificationRules. Also NotificationRule are part of MonitoredService right so why do we need this method in the service?
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/client/FakeNotificationClient.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/33061#-N1wAf4jAjV5HpVnTkuL:-N1wAf4jAjV5HpVnTkuM:bder4lm) ([raw file](https://github.com/harness/harness-core/blob/89088fd81b83c31beed585a685856eff3c7b3e4c/300-cv-nextgen/src/test/java/io/harness/cvng/client/FakeNotificationClient.java#L29)):*
> ```Java
>   @Override
>   public List<NotificationResult> sendBulkNotificationAsync(List<NotificationChannel> notificationChannels) {
>     return null;
> ```

Please don't return null. Either we should return something valid or throw exception.
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java` line 181 at r4](https://reviewable.io/reviews/harness/harness-core/33061#-N1wAv7I6wcH_gZ8JFJK:-N1wAv7I6wcH_gZ8JFJL:b7tww0y) ([raw file](https://github.com/harness/harness-core/blob/89088fd81b83c31beed585a685856eff3c7b3e4c/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java#L181)):*
> ```Java
>   @Mock SetupUsageEventService setupUsageEventService;
>   @Mock ChangeSourceService changeSourceServiceMock;
>   @Mock FakeNotificationClient notificationClient;
> ```

This should be overridden in the Module. Using it like this is not useful. 
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java` line 249 at r4](https://reviewable.io/reviews/harness/harness-core/33061#-N1wB3TQD3ErGMRkhxvC:-N1wB3TQD3ErGMRkhxvD:b-vddfhs) ([raw file](https://github.com/harness/harness-core/blob/89088fd81b83c31beed585a685856eff3c7b3e4c/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java#L249)):*
> ```Java
>     FieldUtils.writeField(monitoredServiceService, "heatMapService", heatMapService, true);
>     FieldUtils.writeField(notificationRuleService, "clock", clock, true);
>     FieldUtils.writeField(monitoredServiceService, "notificationRuleService", notificationRuleService, true);
> ```

Why are we mocking this?
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImplTest.java` line 384 at r4](https://reviewable.io/reviews/harness/harness-core/33061#-N1wBOaEBCwMTqj_Pz0n:-N1wBOaEBCwMTqj_Pz0o:bg0bzys) ([raw file](https://github.com/harness/harness-core/blob/89088fd81b83c31beed585a685856eff3c7b3e4c/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImplTest.java#L384)):*
> ```Java
>     createData(startTime, sliStates);
>     double errorBudgetBurnRate = sliRecordService.getErrorBudgetBurnRate(sliId, Duration.ofMinutes(10).toMillis(), 120);
>     assertThat(errorBudgetBurnRate).isEqualTo(3.3333333333333335);
> ```

double should be compared with a offset because of precision issues.
something like:
```
assertThat(errorBudgetBurndown.get(i).getValue()).isCloseTo(expectedBurndown.get(i), offset(0.01));
```

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33061)* status: 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/monitoredService/MonitoredServiceService.java` line 108 at r4](https://reviewable.io/reviews/harness/harness-core/33061#-N1w9Yhz8APS9Y0ikKlL:-N1wwFeRDW0OZPp3HVGZ:b-970isi) ([raw file](https://github.com/harness/harness-core/blob/89088fd81b83c31beed585a685856eff3c7b3e4c/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/monitoredService/MonitoredServiceService.java#L108)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

This can be just getNotificationRules. Also NotificationRule are part of MonitoredService right so why do we need this method in the service?
</blockquote></details>

yes, changed it to getNotificationRules and made it public in its package.
We need this method because MonitoredService only has metadata for a NotificationRule, however in order to trigger notifications we need whole NotificationRule entity object.
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/client/FakeNotificationClient.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/33061#-N1wAf4jAjV5HpVnTkuL:-N1wwmBGDm1tVjaO214A:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/89088fd81b83c31beed585a685856eff3c7b3e4c/300-cv-nextgen/src/test/java/io/harness/cvng/client/FakeNotificationClient.java#L29)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

Please don't return null. Either we should return something valid or throw exception.
</blockquote></details>

done
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java` line 181 at r4](https://reviewable.io/reviews/harness/harness-core/33061#-N1wAv7I6wcH_gZ8JFJK:-N1wwn8i2-0COkzsUC7Q:b-a0dvzf) ([raw file](https://github.com/harness/harness-core/blob/89088fd81b83c31beed585a685856eff3c7b3e4c/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java#L181)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

This should be overridden in the Module. Using it like this is not useful. 
</blockquote></details>

it is overridden in the module, pls check io.harness.rule.CvNextGenRule
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java` line 249 at r4](https://reviewable.io/reviews/harness/harness-core/33061#-N1wB3TQD3ErGMRkhxvC:-N1wwuvaDRe6uDMcFnVg:b-vbbvjz) ([raw file](https://github.com/harness/harness-core/blob/89088fd81b83c31beed585a685856eff3c7b3e4c/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java#L249)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

Why are we mocking this?
</blockquote></details>

This was done in order to synchronise the clock.instant() in both monitoredServiceService & notificationRuleService.
If we don't do this then both monitoredServiceService & notificationRuleService work on different clock.instant() and hence our purpose is not served.
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImplTest.java` line 384 at r4](https://reviewable.io/reviews/harness/harness-core/33061#-N1wBOaEBCwMTqj_Pz0n:-N1wxOPW7n7ANZVt2LVq:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/89088fd81b83c31beed585a685856eff3c7b3e4c/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImplTest.java#L384)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

double should be compared with a offset because of precision issues.
something like:
```
assertThat(errorBudgetBurndown.get(i).getValue()).isCloseTo(expectedBurndown.get(i), offset(0.01));
```
</blockquote></details>

done

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 3 of 8 files at r5, 2 of 2 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33061)* status: :shipit: complete! ✓

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33061#-:-N2-obTA9RWCIz_3v_AZ:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
