### PR TITLE
fix: [PIE-3619]: Better error handling if delegate task could not be qued …

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
…from pipeline-service

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32821)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32821)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`870-orchestration/src/main/java/io/harness/event/handlers/QueueTaskRequestProcessor.java` line 109 at r2](https://reviewable.io/reviews/harness/harness-core/32821#-N1JCd0v3iMY6fEcDaSq:-N1JCd0w2Gy_iKbbwVxA:bpn5mhb) ([raw file](https://github.com/harness/harness-core/blob/982817f60a62ab770d2dd9a126308b3ff0d3bc9e/870-orchestration/src/main/java/io/harness/event/handlers/QueueTaskRequestProcessor.java#L109)):*
> ```Java
>       log.error("Error while queuing delegate task for node execution {}", nodeExecutionId, ex);
>       orchestrationEngine.handleError(
>           ambiance, new QueueTaskException("Unable to queue delegate task: " + ex.getMessage()));
> ```

Can you add unit test to check for this exception as part of more test coverage



_Code quote:_
```Java
ambiance, new QueueTaskException("Unable to queue delegate task: " + ex.getMessage()))
```
___
*[`980-commons/src/main/java/io/harness/eraro/ErrorCode.java` line 606 at r2](https://reviewable.io/reviews/harness/harness-core/32821#-N1JCHp83T6ermnYAtzb:-N1JCHp83T6ermnYAtzc:bbhq5ix) ([raw file](https://github.com/harness/harness-core/blob/982817f60a62ab770d2dd9a126308b3ff0d3bc9e/980-commons/src/main/java/io/harness/eraro/ErrorCode.java#L606)):*
> ```Java
>   DATA_PROCESSING_ERROR,
>   INVALID_AZURE_AKS_REQUEST,
>   SERVERLESS_EXECUTION_ERROR,
> ```

why this is needed?



_Code quote:_
```Java
SERVERLESS_EXECUTION_ERROR,
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32821)* status: 6 file(s) to review. 1 of 2 approvals obtained. 

___
*[`870-orchestration/src/main/java/io/harness/event/handlers/QueueTaskRequestProcessor.java` line 109 at r2](https://reviewable.io/reviews/harness/harness-core/32821#-N1JCd0v3iMY6fEcDaSq:-N1Mmktv6pJfCqq1i8ru:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/982817f60a62ab770d2dd9a126308b3ff0d3bc9e/870-orchestration/src/main/java/io/harness/event/handlers/QueueTaskRequestProcessor.java#L109)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can you add unit test to check for this exception as part of more test coverage
</blockquote></details>

done
___
*[`980-commons/src/main/java/io/harness/eraro/ErrorCode.java` line 606 at r2](https://reviewable.io/reviews/harness/harness-core/32821#-N1JCHp83T6ermnYAtzb:-N1Mmm9BA7zyEn6CaWVM:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/982817f60a62ab770d2dd9a126308b3ff0d3bc9e/980-commons/src/main/java/io/harness/eraro/ErrorCode.java#L606)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this is needed?
</blockquote></details>

done

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32821)* status: :shipit: complete! ✓

**Pull request closed without merging**
