### PR TITLE
[techdebt]: [CCM-8680]: Optimized perspectiveTimeSeriesStats GraphQL query

### PR DESCRIPTION
**Pull request by sdsingh07**
## Describe your changes
1. Getting top 12 entries using grid api call.
2. Getting the data for each day for those top 12 entries by adding those entries in the IN expression.
3. If user selects includeOthers, then getting the combined cost data for each day and later subtracting it from the day's data of the top 12 entries to get the Others value.
4. If user selected includeUnallocatedCost, then getting combined unallocatedcost data for each day.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36840)

### CODE REVIEW

**Comment by sdsingh07** [comment]
trigger compile, ti0, ti1, ti2, ti3, ti4

**Comment by sdsingh07** [comment]
trigger ti3

**Comment by sdsingh07** [comment]
trigger featurenamecheck

**Review by hitesharinga — APPROVED** [review]
> Reviewed 6 of 13 files at r1, 1 of 3 files at r2, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36840)* status: :shipit: complete! ✓

**Pull request merged**
