### PR TITLE
fix: [DEL-6187]: Error message missing delegate name

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
- Delegate name is coming as null on fail delegate task error message

Test
- Local sanity
## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45796)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger messagecheck

**Review by raghuAtWings — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45796)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 2010 at r1](https://reviewable.io/reviews/harness/harness-core/45796#-NRfggXv9oSbU1uOaTkK:-NRfggXwC8CeMfIh6b2A:b-r0hmq5) ([raw file](https://github.com/harness/harness-core/blob/0100a18f5c1bebd0eca8b6613ec75a4d87c76c7d/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L2010)):*
> ```Java
>         delegateTasks.stream().map(DelegateTask::getUuid).collect(Collectors.toList()));
>     Delegate delegate = delegateCache.get(accountId, delegateId, false);
>     final String delegateName = isNotEmpty(delegate.getHostName()) ? delegate.getHostName() : delegate.getUuid();
> ```

shouldn't we say delegate.getName() for null case? also in what cases hostname can be empty?

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 2010 at r1](https://reviewable.io/reviews/harness/harness-core/45796#-NRfggXv9oSbU1uOaTkK:-NRfgxH-3APabTuCju9W:b-wlh8fp) ([raw file](https://github.com/harness/harness-core/blob/0100a18f5c1bebd0eca8b6613ec75a4d87c76c7d/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L2010)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

shouldn't we say delegate.getName() for null case? also in what cases hostname can be empty?
</blockquote></details>

We use host name across to identify delegate and host name is always in delegate but delegate name can be empty i think. 
But in this case if we don't find the delegate in cache, it may come as null for name and host name. But delegate id will not be null

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 2010 at r1](https://reviewable.io/reviews/harness/harness-core/45796#-NRfggXv9oSbU1uOaTkK:-NRfmCID8loLlqERrp8M:bp8peax) ([raw file](https://github.com/harness/harness-core/blob/0100a18f5c1bebd0eca8b6613ec75a4d87c76c7d/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L2010)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

We use host name across to identify delegate and host name is always in delegate but delegate name can be empty i think. 
But in this case if we don't find the delegate in cache, it may come as null for name and host name. But delegate id will not be null
</blockquote></details>

if we don't find delegate in cache then we will have NPE

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 2010 at r1](https://reviewable.io/reviews/harness/harness-core/45796#-NRfggXv9oSbU1uOaTkK:-NRfp88Z5no0x_EQocwb:b-jm1ya9) ([raw file](https://github.com/harness/harness-core/blob/0100a18f5c1bebd0eca8b6613ec75a4d87c76c7d/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L2010)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

if we don't find delegate in cache then we will have NPE
</blockquote></details>

yes, we know for sure delegateid will not be null as it's passed as param versus picking from cache.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45796)* status: :shipit: complete! ✓

**Pull request merged**
