### PR TITLE
fix:[CDS-46702]: Deployment freeze issues

### PR DESCRIPTION
**Pull request by abhinavmittal-harness**
## Describe your changes

Will add description in a while

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40963)

### CODE REVIEW

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40963)* status: 7 file(s) to review. 0 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`125-freeze/src/main/java/io/harness/freeze/helpers/FreezeTimeUtils.java` line 188 at r1](https://reviewable.io/reviews/harness/harness-core/40963#-NIMFewsEFd_n4xaKRTl:-NIMFewsEFd_n4xaKRTm:b-7s0k3e) ([raw file](https://github.com/harness/harness-core/blob/22d3829950a580ca2b18281585d76f7766f83404/125-freeze/src/main/java/io/harness/freeze/helpers/FreezeTimeUtils.java#L188)):*
> ```Java
>         FreezeTimeUtils.getEpochValueFromDateString(firstWindowStartTime, timeZone) - getCurrentTime();
>     if (timeDifferenceFromStartTime > MAX_FREEZE_START_TIME) {
>       throw new InvalidRequestException("Freeze window start time should be at less than 5 years");
> ```

typo here ?



_Suggestion:_
```Java
at less than 5 years
```

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40963)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40963)* status: 9 file(s) to review. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40963)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by Abhishek-CDC — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40963)* status: :shipit: complete! ✓

**Pull request merged**
