### PR TITLE
fix: [PL-26618]: Removing HARD_DELETE_ENTITES ff

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Describe your changes
Removed the FF - HARD_DELETE_ENTITIES

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37689)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37689)

**Comment by VikasMaddukuriHarness** [comment]
trigger messagecheck

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37689)* status: 16 file(s) to review. 0 of 2 approvals obtained.

**Review by hingerabhinav — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 3 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37689)* status: 16 file(s) to review. 0 of 2 approvals obtained.

**Review by sribalij — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37689)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 374 at r2](https://reviewable.io/reviews/harness/harness-core/37689#-NCVyNif2pWOhXoL6prn:-NCVyNif2pWOhXoL6pro:b75mrem) ([raw file](https://github.com/harness/harness-core/blob/39d414b8bdfd976786fc2f7a6b5d54cfed829efb/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L374)):*
> ```Java
>       log.info("NGTrigger {} hard delete successful", identifier);
>     } else {
>       UpdateResult deleteResult = ngTriggerRepository.delete(criteria);
> ```

Can we also make sure to remove it from NGTriggerRepositoryCustom#delete if there are no more references for that

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37689)* status: 18 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 374 at r2](https://reviewable.io/reviews/harness/harness-core/37689#-NCVyNif2pWOhXoL6prn:-NCW-RJ-87z6pdgm4kT1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/39d414b8bdfd976786fc2f7a6b5d54cfed829efb/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L374)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Can we also make sure to remove it from NGTriggerRepositoryCustom#delete if there are no more references for that
</blockquote></details>

Done.

**Review by sribalij — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 3 of 10 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37689)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 10 of 10 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37689)* status: :shipit: complete! ✓

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 10 of 10 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37689)* status: :shipit: complete! ✓

**Pull request merged**
