### PR TITLE
[feat]: [CDS-35532]: Add getIAMRoles endpoint for NG

### PR DESCRIPTION
**Pull request by nassergonzalez**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31805)

### CODE REVIEW

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31805)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java, line 75 at r1](https://reviewable.io/reviews/harness/harness-core/31805#-MzK3mFd9fdkewTaeBRj:-MzK3mFd9fdkewTaeBRk:b-ca507a) ([raw file](https://github.com/harness/harness-core/blob/9143e4cc95c75207b18ccbf5c29f4e0646d5fc4a/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java#L75)):*
> ```Java
>     return response.getRoles();
>   }
>   @VisibleForTesting
> ```

let's have an empty line between methods
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java, line 76 at r1](https://reviewable.io/reviews/harness/harness-core/31805#-MzK4MWIEjI5RCXzP1oI:-MzK4MWIEjI5RCXzP1oJ:bwcklqy) ([raw file](https://github.com/harness/harness-core/blob/9143e4cc95c75207b18ccbf5c29f4e0646d5fc4a/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java#L76)):*
> ```Java
>   }
>   @VisibleForTesting
>   private AwsIAMRolesResponse executeSyncTask(
> ```

If we want to make it visible for testing and test it it should be protected
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java, line 77 at r1](https://reviewable.io/reviews/harness/harness-core/31805#-MzK4VAL0cH_TAY7dnwY:-MzK4VAL0cH_TAY7dnwZ:boa1mxe) ([raw file](https://github.com/harness/harness-core/blob/9143e4cc95c75207b18ccbf5c29f4e0646d5fc4a/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java#L77)):*
> ```Java
>   @VisibleForTesting
>   private AwsIAMRolesResponse executeSyncTask(
>       AwsTaskParams awsTaskParams, BaseNGAccess baseNGAccess, String ifFailedMessage) {
> ```

We call that method only to get AwsIAMRolesResponse so we don't need pass Error message as a parameter because it will be always the same.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java, line 83 at r1](https://reviewable.io/reviews/harness/harness-core/31805#-MzK5PkM2jjHjmXfAVON:-MzK5PkM2jjHjmXfAVOO:bi3dkt2) ([raw file](https://github.com/harness/harness-core/blob/9143e4cc95c75207b18ccbf5c29f4e0646d5fc4a/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java#L83)):*
> ```Java
>   }
> 
>   private AwsIAMRolesResponse getTaskExecutionResponse(DelegateResponseData responseData, String ifFailedMessage) {
> ```

the same here
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsIAMDelegateTaskHelper.java, line 49 at r1](https://reviewable.io/reviews/harness/harness-core/31805#-MzK6xKD680Eos18Cx-j:-MzK6xKD680Eos18Cx-k:by6d3fw) ([raw file](https://github.com/harness/harness-core/blob/9143e4cc95c75207b18ccbf5c29f4e0646d5fc4a/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsIAMDelegateTaskHelper.java#L49)):*
> ```Java
>       return AwsIAMRolesResponse.builder().roles(roles).commandExecutionStatus(SUCCESS).build();
>     } catch (Exception e) {
>       return AwsIAMRolesResponse.builder().commandExecutionStatus(CommandExecutionStatus.FAILURE).roles(null).build();
> ```

we don't need explicitly set roles as null.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsTaskType.java, line 13 at r1](https://reviewable.io/reviews/harness/harness-core/31805#-MzK7ecl8WJCnUArEn6v:-MzK7ecl8WJCnUArEn6w:b49otal) ([raw file](https://github.com/harness/harness-core/blob/9143e4cc95c75207b18ccbf5c29f4e0646d5fc4a/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsTaskType.java#L13)):*
> ```Java
> import io.harness.annotations.dev.OwnedBy;
> 
> @OwnedBy(HarnessTeam.CDP) public enum AwsTaskType { VALIDATE, LIST_S3_BUCKETS, LIST_IAM_ROLES, LIST_IAM_INSTANCE_ROLES }
> ```

Why do we need LIST_IAM_INSTANCE_ROLES ?
___
*[960-api-services/src/test/java/io/harness/aws/AwsClientTest.java, line 81 at r1](https://reviewable.io/reviews/harness/harness-core/31805#-MzK87Ng8Xhlw2ZXxdKy:-MzK87Ng8Xhlw2ZXxdKz:bsnfgkc) ([raw file](https://github.com/harness/harness-core/blob/9143e4cc95c75207b18ccbf5c29f4e0646d5fc4a/960-api-services/src/test/java/io/harness/aws/AwsClientTest.java#L81)):*
> ```Java
>     verify(awsApiHelperService, times(1)).handleAmazonServiceException(any());
>   }
>   @Test
> ```

lets add an empty line between methods.
___
*[980-commons/src/main/java/io/harness/exception/AwsIAMRolesException.java, line 30 at r1](https://reviewable.io/reviews/harness/harness-core/31805#-MzK9TIt4mcfMmrzFhi5:-MzK9TIt4mcfMmrzFhi6:b-n0tlk5) ([raw file](https://github.com/harness/harness-core/blob/9143e4cc95c75207b18ccbf5c29f4e0646d5fc4a/980-commons/src/main/java/io/harness/exception/AwsIAMRolesException.java#L30)):*
> ```Java
>   @SuppressWarnings("squid:CallToDeprecatedMethod")
>   public AwsIAMRolesException(String message, Throwable cause) {
>     super(message, cause, BUCKET_SERVER_ERROR, Level.ERROR, null, null);
> ```

why BUCKET_SERVER_ERROR?



_Code quote:_
```Java
BUCKET_SERVER_ERROR
```

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31805)* status: 5 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java, line 75 at r1](https://reviewable.io/reviews/harness/harness-core/31805#-MzK3mFd9fdkewTaeBRj:-MzKIC1e0uuLfazInlzc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9143e4cc95c75207b18ccbf5c29f4e0646d5fc4a/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java#L75)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's have an empty line between methods
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java, line 76 at r1](https://reviewable.io/reviews/harness/harness-core/31805#-MzK4MWIEjI5RCXzP1oI:-MzKIHTL8zIxUMK60OoX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9143e4cc95c75207b18ccbf5c29f4e0646d5fc4a/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java#L76)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

If we want to make it visible for testing and test it it should be protected
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java, line 77 at r1](https://reviewable.io/reviews/harness/harness-core/31805#-MzK4VAL0cH_TAY7dnwY:-MzKIdCVBQZD5rvtb2m4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9143e4cc95c75207b18ccbf5c29f4e0646d5fc4a/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java#L77)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

We call that method only to get AwsIAMRolesResponse so we don't need pass Error message as a parameter because it will be always the same.
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java, line 83 at r1](https://reviewable.io/reviews/harness/harness-core/31805#-MzK5PkM2jjHjmXfAVON:-MzKIdgc59eAwXImAORD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9143e4cc95c75207b18ccbf5c29f4e0646d5fc4a/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java#L83)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

the same here
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsIAMDelegateTaskHelper.java, line 49 at r1](https://reviewable.io/reviews/harness/harness-core/31805#-MzK6xKD680Eos18Cx-j:-MzKIqa18odSUY0zda12:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9143e4cc95c75207b18ccbf5c29f4e0646d5fc4a/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsIAMDelegateTaskHelper.java#L49)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

we don't need explicitly set roles as null.
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsTaskType.java, line 13 at r1](https://reviewable.io/reviews/harness/harness-core/31805#-MzK7ecl8WJCnUArEn6v:-MzKIs90EYcasknxUi1D:b8z5z0h) ([raw file](https://github.com/harness/harness-core/blob/9143e4cc95c75207b18ccbf5c29f4e0646d5fc4a/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsTaskType.java#L13)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Why do we need LIST_IAM_INSTANCE_ROLES ?
</blockquote></details>

I was planning to move also that logic as a bonus if we get free time but I will remove it and just create a ticket if we have time
___
*[960-api-services/src/test/java/io/harness/aws/AwsClientTest.java, line 81 at r1](https://reviewable.io/reviews/harness/harness-core/31805#-MzK87Ng8Xhlw2ZXxdKy:-MzKJAt_AkLy5pwve-KV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9143e4cc95c75207b18ccbf5c29f4e0646d5fc4a/960-api-services/src/test/java/io/harness/aws/AwsClientTest.java#L81)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

lets add an empty line between methods.
</blockquote></details>

Done.
___
*[980-commons/src/main/java/io/harness/exception/AwsIAMRolesException.java, line 30 at r1](https://reviewable.io/reviews/harness/harness-core/31805#-MzK9TIt4mcfMmrzFhi5:-MzKJKOi5I1OME-GO84K:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9143e4cc95c75207b18ccbf5c29f4e0646d5fc4a/980-commons/src/main/java/io/harness/exception/AwsIAMRolesException.java#L30)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

why BUCKET_SERVER_ERROR?
</blockquote></details>

Done.

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31805)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java, line 57 at r2](https://reviewable.io/reviews/harness/harness-core/31805#-MzOovPl3KCkbPFR09KE:-MzOovPl3KCkbPFR09KF:bovxuve) ([raw file](https://github.com/harness/harness-core/blob/2fdb9c038876bc3d50cb55e7febf0f381df0d9b2/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L57)):*
> ```Java
>   @GET
>   @Path("regions")
>   @ApiOperation(value = "Get all the AWS regions defined in the application", nickname = "RegionsForAwsHelper")
> ```

Let's change "ForAwsHelper" to "ForAws" in all nicknames

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31805)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java, line 57 at r2](https://reviewable.io/reviews/harness/harness-core/31805#-MzOovPl3KCkbPFR09KE:-Mz_cBsH59aRjGmrwxs0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fdb9c038876bc3d50cb55e7febf0f381df0d9b2/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L57)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Let's change "ForAwsHelper" to "ForAws" in all nicknames
</blockquote></details>

Done.

**Review by tmacari-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31805#-:-MznFO_m6WPPGugMVExK:bnfp4nl)* status: :shipit: complete! ✓

**Comment by nassergonzalez** [comment]
trigger ti0

**Pull request merged**
