### PR TITLE
[feat]: [PIE-9193]: Invoke IdentityStrategyInternalStep only if Strategy is Identity

### PR DESCRIPTION
**Pull request by namanvermah**
When an Identity Step is being run, its children are made identity nodes on the fly if that Identity Step is a descendant of some strategy. This should only happen if the Strategy itself is identity.

This fixes the issue where pipeline rollback was not working for stages with strategy.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46426)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger messagecheck

**Comment by namanvermah** [comment]
trigger messagecheck

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46426)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46426)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
trigger review

**Pull request merged**
