### PR TITLE
feat: [CDS-71743]: Revert Hotfix: Adding a new field in release history to track the bg environment

### PR DESCRIPTION
**Pull request by GoelPratyush99**
Reverts harness/harness-core#48782

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48981)

### CODE REVIEW

**Comment by GoelPratyush99** [comment]
trigger uts

**Review by acasian-harness — APPROVED** [review]

**Review by abosii-harness — CHANGES_REQUESTED** [review]
We need the changes for Yaml as well with this release, otherwise we will not be able to ever release this feature

**Comment by acasian-harness** [comment]
trigger uts

**Comment by GoelPratyush99** [comment]
trigger messagecheck

**Comment by GoelPratyush99** [comment]
trigger uts

**Review by abosii-harness — APPROVED** [review]

**Comment by GoelPratyush99** [comment]
trigger review

**Pull request merged**
