### PR TITLE
[feat]: [PIE-3309]: capture pipeline serice api erorrs and send to se…

### PR DESCRIPTION
**Pull request by brijeshdhakar**
…gment

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31914)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java, line 858 at r1](https://reviewable.io/reviews/harness/harness-core/31914#-MzUggo3CkRdukO4FRvQ:-MzUggo3CkRdukO4FRvR:bc5h9rw) ([raw file](https://github.com/harness/harness-core/blob/618ccffece2cd160764417e3d91c8bfd6b3f6056/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L858)):*
> ```Java
>   private void registerAPIErrorsTelemetrySenderFilter(Environment environment, Injector injector) {
>     TelemetryReporter telemetryReporter = injector.getInstance(TelemetryReporter.class);
>     environment.jersey().register(new APIErrorsTelemetrySenderFilter(telemetryReporter, "NG Manager"));
> ```

nit use NG_MANAGER.getServiceId

**Comment by sahilhindwani-harness** [comment]
*[800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java, line 574 at r1](https://reviewable.io/reviews/harness/harness-core/31914#-MzUgqPJD_-rPBH1ju4_:-MzUgqPKBtZby5rW6oHo:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/618ccffece2cd160764417e3d91c8bfd6b3f6056/800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java#L574)):*
> ```Java
>   private void registerAPIErrorsTelemetrySenderFilter(Environment environment, Injector injector) {
>     TelemetryReporter telemetryReporter = injector.getInstance(TelemetryReporter.class);
>     environment.jersey().register(new APIErrorsTelemetrySenderFilter(telemetryReporter, "Pipeline service"));
> ```

same as above

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31914)* status: 3 file(s) to review. 0 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
*[800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java, line 574 at r1](https://reviewable.io/reviews/harness/harness-core/31914#-MzUgqPJD_-rPBH1ju4_:-MzUl5TzBE6kt2VjZIvS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/618ccffece2cd160764417e3d91c8bfd6b3f6056/800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java#L574)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by rijajoo — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31914#-:-MzUpuu37O3W4-c1YqJ-:bnfp4nl)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31914)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31914)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31914)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
