### PR TITLE
[feat]: [CDS-80678]: Added the reload from git option for sync enabled entities

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added code to reload from git option for bi directional sync enabled entities for pipelines. Have tested out the following:
1. remote pipeline: 
	1.1 sync enabled:
		a. get pipline: use cache -> working
		b. run pipeline: use cache -> working
		c. reload from git: use git -> working

	1.2 sync disabled:
		a. get pipline: use cache -> working
		b. run pipeline: use git -> working
		c. reload from git: use git -> working

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53678)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger messagecheck

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53678)* status: Some of the checks are too old. 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmGetFileByBranchRequestDTO.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/53678#-NgL-qpvCFAiTy0qLKPB:-NgL-qpvCFAiTy0qLKPC:b-pntur5) ([raw file](https://github.com/harness/harness-core/blob/a9c872f7545353893a035be2291161046860abd2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmGetFileByBranchRequestDTO.java#L40)):*
> ```Java
>   ScmConnector scmConnector;
>   GitXSettingsParams gitXSettingsParams;
>   boolean forceRefresh;
> ```

shouldn't it be "forceFetchFromGIT" ? or "forceGITFetch"

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53678)* status: Some of the checks are too old. 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/gitx/USER_FLOW.java` line 12 at r2](https://reviewable.io/reviews/harness/harness-core/53678#-NgL0Krd3YVDsXm8MKc6:-NgL0Krd3YVDsXm8MKc7:bf4jbo) ([raw file](https://github.com/harness/harness-core/blob/a9c872f7545353893a035be2291161046860abd2/970-ng-commons/src/main/java/io/harness/gitx/USER_FLOW.java#L12)):*
> ```Java
> import io.harness.annotations.dev.OwnedBy;
> 
> @OwnedBy(HarnessTeam.PIPELINE) public enum USER_FLOW { EXECUTION, GET_FILE }
> ```

now this is not required right?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53678)* status: Some of the checks are too old. 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 348 at r2](https://reviewable.io/reviews/harness/harness-core/53678#-NgL0NNI8HKD3zJK1ssf:-NgL0NNI8HKD3zJK1ssg:b-h2w6kx) ([raw file](https://github.com/harness/harness-core/blob/a9c872f7545353893a035be2291161046860abd2/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L348)):*
> ```Java
>       boolean loadFromCache, boolean validateAsync) {
>     Optional<PipelineEntity> pipelineEntity;
>     ThreadOperationContextHelper.setUserFlow(USER_FLOW.GET_FILE);
> ```

why's this required?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53678)* status: Some of the checks are too old. 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 121 at r2](https://reviewable.io/reviews/harness/harness-core/53678#-NgL0TPl9rXHvGL-9jv9:-NgL0TPl9rXHvGL-9jvA:bl2i8f0) ([raw file](https://github.com/harness/harness-core/blob/a9c872f7545353893a035be2291161046860abd2/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L121)):*
> ```Java
>                     .getOnlyFileContent(PipelineGitXHelper.isExecutionFlow())
>                     .yamlVersion(yamlVersion)
>                     .forceRefresh(PipelineGitXHelper.isGetFileFlow())
> ```

No, we shouldn't handle anything like this. The new param should be set the same way as we handle the cache params until now.

**Pull request closed without merging**
