### PR TITLE
feat: [CDS-69758]: Add oneOfFields for environmentYamlV2

### PR DESCRIPTION
**Pull request by abhinavmittal-harness**
## Describe your changes
Sample yaml:
Screenshot 2023-06-19 at 10 51 25 AM

image

Screenshot 2023-06-19 at 10 51 14 AM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49354)

### CODE REVIEW

**Comment by abhinavmittal-harness** [comment]
trigger uts

**Comment by abhinavmittal-harness** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/49354#-NYH2M9j-8gBOCvVBvUd:-NYH2M9j-8gBOCvVBvUe:b2dk8wz) ([raw file](https://github.com/harness/harness-core/blob/51107d9d8feead4c08d3331e99fa62a788368ae0/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java#L52)):*
> ```Java
> @OwnedBy(CDC)
> @RecasterAlias("io.harness.cdng.environment.yaml.EnvironmentYamlV2")
> @OneOfField(fields = {"infrastructureDefinition", "infrastructureDefinitions"})
> ```

can you check if this adds strict schema validation on the environment yaml. Basically we want to see if I add an extra random field in the environment yaml, does the schema still remain valid ?

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49354)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinavmittal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49354)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/49354#-NYH2M9j-8gBOCvVBvUd:-NYH4ehuAWP9knQ7HX7w:bd5h51p) ([raw file](https://github.com/harness/harness-core/blob/51107d9d8feead4c08d3331e99fa62a788368ae0/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java#L52)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can you check if this adds strict schema validation on the environment yaml. Basically we want to see if I add an extra random field in the environment yaml, does the schema still remain valid ?
</blockquote></details>

No it doesn't
If we add some random field it will allow saving and the schema would be considered valid

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49354)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49354)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49354)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49354)* status: :shipit: complete! ✓

**Comment by abhinavmittal-harness** [comment]
trigger review

**Pull request merged**
