### PR TITLE
feat: [CODE-552]: triggers for gitness pt2

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Describe your changes
In this PR I have added more changes for upserting triggers for harness scm. Also, a unit test is added for the same.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49594)

### CODE REVIEW

**Comment by abhinav-harness** [comment]
trigger uts

**Comment by abhinav-harness** [comment]
trigger uts

**Review by vcalasansh — DISMISSED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49594)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`950-ng-core/src/main/java/io/harness/ng/webhook/UpsertWebhookRequestDTO.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/49594#-NYiqW4NDHJiSGuk5EuM:-NYiqW4NDHJiSGuk5EuN:b-ce2xeb) ([raw file](https://github.com/harness/harness-core/blob/db283e8ab9e0d267db2f663e125ce27921409eee/950-ng-core/src/main/java/io/harness/ng/webhook/UpsertWebhookRequestDTO.java#L37)):*
> ```Java
>   String orgIdentifier;
>   String projectIdentifier;
>   String connectorIdentifierRef;
> ```

Is connectorIdentifierRef any different from our usual "connectorRef" convention that is used until now?

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/beans/HookEventType.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/49594#-NYiqj3YAWqLGobONZ5N:-NYiqj3YAWqLGobONZ5O:b-l3kti3) ([raw file](https://github.com/harness/harness-core/blob/db283e8ab9e0d267db2f663e125ce27921409eee/952-scm-java-client/src/main/java/io/harness/beans/HookEventType.java#L43)):*
> ```Java
>           AzureWebhookEvent.AZURE_PULL_REQUEST_ISSUE_COMMENT),
>       // todo(abhinav): add issue comments when it arrives.
>       Arrays.asList(HarnessWebhookEvent.HARNESS_PULLREQ_CREATED, HarnessWebhookEvent.HARNESS_PULLREQ_REOPENED,
> ```

nit: HARNESS_PULL_REQUEST_* sounds better. We don't get much by not writing "UEST". Either we can use PULL_REQUEST complete or more common shorthand notation "PR".

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/webhook/WebhookAction.java` line 146 at r1](https://reviewable.io/reviews/harness/harness-core/49594#-NYir8BR-mjx1lE8iys4:-NYir8BR-mjx1lE8iys5:b-23w2lq) ([raw file](https://github.com/harness/harness-core/blob/db283e8ab9e0d267db2f663e125ce27921409eee/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/webhook/WebhookAction.java#L146)):*
> ```Java
>         return EnumSet.of(CREATED, EDITED, DELETED);
>       default:
>         throw new InvalidRequestException("Event " + event.name() + " not a github event");
> ```

Shouldn't the message say "Harness SCM even"?

**Comment by abhinav-harness** [comment]
*[`950-ng-core/src/main/java/io/harness/ng/webhook/UpsertWebhookRequestDTO.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/49594#-NYiqW4NDHJiSGuk5EuM:-NYscdLs1Affo6hj87dR:b-1imd51) ([raw file](https://github.com/harness/harness-core/blob/db283e8ab9e0d267db2f663e125ce27921409eee/950-ng-core/src/main/java/io/harness/ng/webhook/UpsertWebhookRequestDTO.java#L37)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Is connectorIdentifierRef any different from our usual "connectorRef" convention that is used until now?
</blockquote></details>

Changing it is not straightforward now since its exposed in apis

**Comment by abhinav-harness** [comment]
*[`952-scm-java-client/src/main/java/io/harness/beans/HookEventType.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/49594#-NYiqj3YAWqLGobONZ5N:-NYscuHI06zItoAuDh5m:b-iagobx) ([raw file](https://github.com/harness/harness-core/blob/db283e8ab9e0d267db2f663e125ce27921409eee/952-scm-java-client/src/main/java/io/harness/beans/HookEventType.java#L43)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

nit: HARNESS_PULL_REQUEST_* sounds better. We don't get much by not writing "UEST". Either we can use PULL_REQUEST complete or more common shorthand notation "PR".
</blockquote></details>

Its coming from scm svc, hard to change now

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49594)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
trigger uts

**Review by vcalasansh — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49594)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
trigger uts

**Comment by abhinav-harness** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Review by vcalasansh — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49594)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
failing test reported here https://harness.slack.com/archives/C01JMN5P7EX/p1687857219158309

**Pull request merged**
