### PR TITLE
feat: [DEL-3256]: show list of delegates when a token is being revoked

### PR DESCRIPTION
**Pull request by arpit3107**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30838)

### CODE REVIEW

**Comment by abhinav-harness** [comment]
___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 552 at r1](https://reviewable.io/reviews/harness/harness-core/30838#-Mw5ttyDClOb6a86eSgI:-Mw5ttyDClOb6a86eSgJ:b-cm6shl) ([raw file](https://github.com/harness/harness-core/blob/f8fc0f8c5b748171e39fd9b18adc565cae35a39d/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L552)):*
> ```Java
> 
>       if (isNotEmpty(delegateTokenName)) {
>         log.info("Registering Delegate with Token: {}", delegateTokenName);
> ```

why this change, is this a revert?

**Comment by abhinav-harness** [comment]
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 102 at r1](https://reviewable.io/reviews/harness/harness-core/30838#-Mw5uClz5aU_looxrFVD:-Mw5uClz5aU_looxrFVE:b-g009ho) ([raw file](https://github.com/harness/harness-core/blob/ad480dd51e449637e2b2d9e80387d773fa8fd7b2/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L102)):*
> ```Java
>     try {
>       JWTClaimsSet jwtClaimsSet = encryptedJWT.getJWTClaimsSet();
>       if (System.currentTimeMillis() > jwtClaimsSet.getExpirationTime().getTime()) {
> ```

null check

**Comment by abhinav-harness** [comment]
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 144 at r1](https://reviewable.io/reviews/harness/harness-core/30838#-Mw5uW1T0ZC4GZ74lPne:-Mw5uW1T0ZC4GZ74lPnf:bz62vge) ([raw file](https://github.com/harness/harness-core/blob/f8fc0f8c5b748171e39fd9b18adc565cae35a39d/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L144)):*
> ```Java
>                                            .equal(accountId)
>                                            .field(DelegateNgTokenKeys.status)
>                                            .equal(status);
> ```

why remove?

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30838)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateParams.java, line 57 at r1](https://reviewable.io/reviews/harness/harness-core/30838#-Mw5wNBm9XlxJf2mvchF:-Mw5wNBm9XlxJf2mvchG:b20p9xw) ([raw file](https://github.com/harness/harness-core/blob/f8fc0f8c5b748171e39fd9b18adc565cae35a39d/920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateParams.java#L57)):*
> ```Java
> 
>   String delegateTokenName;
> }
> ```

wont it cause issue in CG?



_Code quote:_
```Java
kenName;
```

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30838)* status: 5 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 552 at r1](https://reviewable.io/reviews/harness/harness-core/30838#-Mw5ttyDClOb6a86eSgI:-Mw6LPri3OgzVJFi3W3j:b94lywg) ([raw file](https://github.com/harness/harness-core/blob/f8fc0f8c5b748171e39fd9b18adc565cae35a39d/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L552)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

why this change, is this a revert?
</blockquote></details>

This is never used, i.e. Vlad forgot to add the token name in the yaml and hence is not present at delegate agent side.
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 102 at r1](https://reviewable.io/reviews/harness/harness-core/30838#-Mw5uClz5aU_looxrFVD:-Mw6Lc7b2PWIeO3lRcLj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ad480dd51e449637e2b2d9e80387d773fa8fd7b2/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L102)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

null check
</blockquote></details>

Done.
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 144 at r1](https://reviewable.io/reviews/harness/harness-core/30838#-Mw5uW1T0ZC4GZ74lPne:-Mw6LerB0T5dPYyirEpm:bqd8lkx) ([raw file](https://github.com/harness/harness-core/blob/f8fc0f8c5b748171e39fd9b18adc565cae35a39d/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L144)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

why remove?
</blockquote></details>

We are not using DelegateNgToken collection anymore. I had removed all these things as part of caching ticket, but that ticket cant be merged now.
___
*[920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateParams.java, line 57 at r1](https://reviewable.io/reviews/harness/harness-core/30838#-Mw5wNBm9XlxJf2mvchF:-Mw6LoF175zMpJ_SERPk:b-ar33ug) ([raw file](https://github.com/harness/harness-core/blob/f8fc0f8c5b748171e39fd9b18adc565cae35a39d/920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateParams.java#L57)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

wont it cause issue in CG?
</blockquote></details>

No, Vlad added it for NG, but is of no use.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 5 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30838)* status: :shipit: complete! ✓

**Pull request merged**
