### PR TITLE
techdebt: [PIE-4561]: introduce batching in redis consumer

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35717)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger ti0

**Comment by sahilhindwani-harness** [comment]
*[`120-ng-manager/config.yml` line 463 at r2](https://reviewable.io/reviews/harness/harness-core/35717#-N7z2XARAw9qxz_nGtor:-N7z2XARAw9qxz_nGtos:b-e422jr) ([raw file](https://github.com/harness/harness-core/blob/f3ce7c23d8812020221d5ff4bff1e20cf78df770/120-ng-manager/config.yml#L463)):*
> ```YAML
> debeziumConsumerConfigs:
>   - topicName: ${TOPIC_NAME:-DEBEZIUM_pmsMongo.pms-harness.planExecutionsSummary}
>     numberOfThreads: ${THREADS:-2}
> ```

nit: name can be more verbose so that people are aware of what they are overridding

**Comment by sahilhindwani-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/eventsframework/EventsFrameworkModule.java` line 249 at r2](https://reviewable.io/reviews/harness/harness-core/35717#-N7z2x6C1joVAzU7cHUO:-N7z2x6C1joVAzU7cHUP:b-1pnv1d) ([raw file](https://github.com/harness/harness-core/blob/f3ce7c23d8812020221d5ff4bff1e20cf78df770/120-ng-manager/src/main/java/io/harness/ng/eventsframework/EventsFrameworkModule.java#L249)):*
> ```Java
>   @Provides
>   @Singleton
>   @Named("pmsEventsCache")
> ```

nit: rename to something different as pmsEventsCache is already there.

**Comment by sahilhindwani-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java` line 144 at r2](https://reviewable.io/reviews/harness/harness-core/35717#-N7z43elD0DoTcZLje4z:-N7z43elD0DoTcZLje5-:b-sb3mwb) ([raw file](https://github.com/harness/harness-core/blob/f3ce7c23d8812020221d5ff4bff1e20cf78df770/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java#L144)):*
> ```Java
>   }
> 
>   private AcquiredLock<?> acquireLock(int maxRetries, String lockName) throws InterruptedException {
> ```

Use RetryPolicy for retrying

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35717)* status: 18 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java` line 144 at r2](https://reviewable.io/reviews/harness/harness-core/35717#-N7z43elD0DoTcZLje4z:-N7zQoTy46xu1AHsQLCp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3ce7c23d8812020221d5ff4bff1e20cf78df770/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java#L144)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Use RetryPolicy for retrying
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8MmKsnB832sW_CC9NW:-N8MmDUgCF353dsBkERN:b6tng1j) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java#L125)):*
> ```Java
>       }
>       log.info("Acquired lock for planExecutionId: {}", eventKey);
>       Long timestamp1 = eventsCache.get(eventKey);
> ```

nit: can we rename it to lastProcessedTimeStamp?

**Comment by sahilhindwani-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java` line 116 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8MmWxO7mAbdU49328s:-N8MmWxO7mAbdU49328t:bi4n7n3) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java#L116)):*
> ```Java
>     String eventKey = CACHE_PREFIX + debeziumChangeEvent.getKey();
>     String lockName = LOCK_PREFIX + eventKey;
>     Long timestamp = debeziumChangeEvent.getTimestamp();
> ```

nit: Should we rename it to currentTimestamp?

**Comment by sahilhindwani-harness** [comment]
*[`951-debezium-service/config.yml` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8Mmmn_5Uifhqr1grh7:-N8Mmmn_5Uifhqr1grh8:b-5fitkc) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/951-debezium-service/config.yml#L48)):*
> ```YAML
>     connect.max.attempts: ${CONNECT_MAX_ATTEMPTS:-3}
>     snapshot.fetch.size: ${SNAPSHOT_FETCH_SIZE:-2000}
>     timeout: ${TIMEOUT:-60}
> ```

nit: can we rename it to a more verbose name?

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 10 of 16 files at r2, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35717)* status: 18 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java` line 114 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8MmUcS5Yk4Kmj1Fq4F:-N8MmUcS5Yk4Kmj1Fq4G:b-3nkgtg) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java#L114)):*
> ```Java
>   private boolean handleMessage(Message message) {
>     DebeziumChangeEvent debeziumChangeEvent = Objects.requireNonNull(buildEventFromMessage(message));
>     String eventKey = CACHE_PREFIX + debeziumChangeEvent.getKey();
> ```

what do you mean by event key? is this executionId? If yes just add a comment mentioning its planExecutionid



_Code quote:_
```Java
debeziumChangeEvent.getKey()
```
___
*[`120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java` line 116 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8MmWxO7mAbdU49328s:-N8MmfO2E8tSLI02rG4A:b32v57) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java#L116)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: Should we rename it to currentTimestamp?
</blockquote></details>

+1
___
*[`120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8MmKsnB832sW_CC9NW:-N8MmrilEtY_9C4ZwNMw:b32v57) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java#L125)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: can we rename it to lastProcessedTimeStamp?
</blockquote></details>

+1
___
*[`120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java` line 134 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8MnHN4C2QiwGzzxag5:-N8MnHN4C2QiwGzzxag6:b-3igmfn) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java#L134)):*
> ```Java
>           return eventHandler.handleEvent(debeziumChangeEvent);
>         } else {
>           log.info("Ignoring event {} with planExecutionID {} as it was already updated", message.getId(), eventKey);
> ```

i dont think info we should do, else it will be too many events logging. it will clog it.
maybe we can put it as debug if needed



_Code quote:_
```Java
log.info
```
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/SecretManagementModuleTest.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8MndRR0jlhr5d9vwvA:-N8MndRS3vPAazULPF_u:bp6f86v) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/120-ng-manager/src/test/java/io/harness/ng/core/SecretManagementModuleTest.java#L79)):*
> ```Java
> public class SecretManagementModuleTest extends CategoryTest {
>   private SecretManagementModule secretManagementModule;
>   private CacheModule cacheModule;
> ```

why we needed to add this in your PR?
___
*[`951-debezium-service/config.yml` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8Mmmn_5Uifhqr1grh7:-N8Mnhch3K7AbN07K0Yl:b-d322zu) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/951-debezium-service/config.yml#L48)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: can we rename it to a more verbose name?
</blockquote></details>

timeout of what?
___
*[`952-debezium-engine/src/main/java/io/harness/debezium/EventsFrameworkChangeConsumer.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8MnnGO-f_uJqwr20xO:-N8MnnGO-f_uJqwr20xP:b-2d6t07) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/952-debezium-engine/src/main/java/io/harness/debezium/EventsFrameworkChangeConsumer.java#L35)):*
> ```Java
>     this.collectionName = collectionName;
>     this.producerFactory = producerFactory;
>     this.timeout = timeout;
> ```

doesnt seem like a timeout, but sleepTimePeriod for processing debezium events
___
*[`952-debezium-engine/src/main/java/io/harness/debezium/EventsFrameworkChangeConsumer.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8Mnt1YBpg5ph7dGiob:-N8Mnt1YBpg5ph7dGioc:b1473mu) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/952-debezium-engine/src/main/java/io/harness/debezium/EventsFrameworkChangeConsumer.java#L61)):*
> ```Java
>         log.error("Exception Occurred while marking record as committed", e);
>       }
>       if (cnt >= 1000) {
> ```

This count can also be config, default value can be 1000

**Comment by sahilhindwani-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java` line 134 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8MnIuD4KCStq_Fa_7u:-N8MnIuD4KCStq_Fa_7v:b-hu43yz) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java#L134)):*
> ```Java
>           return eventHandler.handleEvent(debeziumChangeEvent);
>         } else {
>           log.info("Ignoring event {} with planExecutionID {} as it was already updated", message.getId(), eventKey);
> ```

Can we add a comment either on the file or here of the approach?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35717)* status: 19 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java` line 114 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8MmUcS5Yk4Kmj1Fq4F:-N8MtDIm2OREyWGnUv4S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java#L114)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what do you mean by event key? is this executionId? If yes just add a comment mentioning its planExecutionid
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java` line 134 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8MnHN4C2QiwGzzxag5:-N8MtFJgC_qqGPT32Ypl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java#L134)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i dont think info we should do, else it will be too many events logging. it will clog it.
maybe we can put it as debug if needed
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java` line 134 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8MnIuD4KCStq_Fa_7u:-N8Mtmmk2BaS0eMso9fQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java#L134)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we add a comment either on the file or here of the approach?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/SecretManagementModuleTest.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8MndRR0jlhr5d9vwvA:-N8MuIqv3RAos1pz_sGt:b-1fil3u) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/120-ng-manager/src/test/java/io/harness/ng/core/SecretManagementModuleTest.java#L79)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we needed to add this in your PR?
</blockquote></details>

Because we needed harnessCacheManager for using Redis cache for storing timestamps, since it was already not used in 120-ng-manager, we needed to add this.
___
*[`952-debezium-engine/src/main/java/io/harness/debezium/EventsFrameworkChangeConsumer.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8MnnGO-f_uJqwr20xO:-N8Mva3c14Jayx5Ay3lk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/952-debezium-engine/src/main/java/io/harness/debezium/EventsFrameworkChangeConsumer.java#L35)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

doesnt seem like a timeout, but sleepTimePeriod for processing debezium events
</blockquote></details>

Done.
___
*[`952-debezium-engine/src/main/java/io/harness/debezium/EventsFrameworkChangeConsumer.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/35717#-N8Mnt1YBpg5ph7dGiob:-N8N7L9N9BKfHVAgEpvG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6ef7a28ffb5b0a06ae19397d288a42d345cbef51/952-debezium-engine/src/main/java/io/harness/debezium/EventsFrameworkChangeConsumer.java#L61)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

This count can also be config, default value can be 1000
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35717)* status: 19 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 5 of 16 files at r2, 4 of 5 files at r3, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35717)* status: :shipit: complete! ✓

**Pull request merged**
