### PR TITLE
fix: [PL-39054]: Revert "fix: [DEL-6278]: Add a check in delegate startup so that legacy delegate image is not used for immutable delegate installation"

### PR DESCRIPTION
**Pull request by xingchi-jin**
Reverts harness/harness-core#47381

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48434)

### CODE REVIEW

**Comment by xingchi-jin** [comment]
trigger uts

**Comment by xingchi-jin** [comment]
trigger messagecheck

**Comment by xingchi-jin** [comment]
trigger messagecheck

**Comment by xingchi-jin** [comment]
trigger messagecheck

**Review by AnupamIO — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48434)* status: Some of the checks are too old. 1 file(s) to review. 1 of 2 approvals obtained.

**Review by bharatgoelharness — APPROVED** [review]

**Pull request merged**
