### PR TITLE
fix: [CDS-73241]: Variable path suggestion are not correct

### PR DESCRIPTION
**Pull request by prashantsharma04**
Screenshot 2023-07-04 at 12 28 52 PM
## Describe your changes

Problem: Variables suggestion are coming wrong for output tab

Solution: In variable api, we do send the yaml. In yaml, all leaf node values are replaced with uuid. For Pipeline stage it was not getting reflected, because its a stage and outputs node comes under spec and not directly under stage.

We have created a new variable creator whose dependency is added from PipelineStageVariableCreator. 
In new variable creator, we are updating the yaml field with value as uuid and making a yaml update call

Testing in local.
Screenshot 2023-06-29 at 11 02 11 AM
Screenshot 2023-06-29 at 11 03 21 AM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49874)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/AbstractStageVariableCreator.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/49874#-NZ1zS0hBx5eE1BpZ80w:-NZ1zS0i1ogJVwmARPZd:bd46veo) ([raw file](https://github.com/harness/harness-core/blob/4d35583238f82c70d613c89191a535b0057d358d/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/AbstractStageVariableCreator.java#L102)):*
> ```Java
>           throw new InvalidRequestException(
>               "Variable with name \"" + variableName + "\" added without any value. Fqn: " + fqn);
>         }
> ```

Will this affect any other stage variables?

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49874)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49874)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/AbstractStageVariableCreator.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/49874#-NZ50l4m2FoDRBXwQbTP:-NZ50l4nB82ZQW2QYjdI:bbw34lj) ([raw file](https://github.com/harness/harness-core/blob/4db0a6af20d559b5fe75653ead97214a12eee1a2/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/AbstractStageVariableCreator.java#L87)):*
> ```Java
>   }
> 
>   protected void addVariablesForOutputVariables(
> ```

move to pipeline stage creator

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49874)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by prashantsharma04** [comment]
trigger review

**Comment by prashantsharma04** [comment]
trigger uts

**Review by prashantsharma04 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49874)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/AbstractStageVariableCreator.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/49874#-NZ50l4m2FoDRBXwQbTP:-NZ58vFmDIU7vCvlRBIy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4db0a6af20d559b5fe75653ead97214a12eee1a2/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/AbstractStageVariableCreator.java#L87)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

move to pipeline stage creator
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49874)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49874)* status: :shipit: complete! ✓

**Comment by prashantsharma04** [comment]
trigger review

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49874)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49874)* status: :shipit: complete! ✓

**Comment by prashantsharma04** [comment]
trigger trigger review

**Pull request merged**
