### PR TITLE
feat: [CDS-71302]: Added beans for Step execution entity for saving step execution details

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
Added beans for Step execution entity, which is required to save the step execution details to mongo for syncing the data to timescale. 
This PR contains only beans, so it shouldn't break anything.
Tech spec: https://harness.atlassian.net/l/cp/e43RLjm7

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49301)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49301)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/step/HarnessApprovalStepExecutionDetails.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/49301#-NYRPBlX3SSwLLO0eq04:-NYRPBlY8-16jNh5e_9T:b-35zsis) ([raw file](https://github.com/harness/harness-core/blob/56c309f3f0638d766bcbbd29c2d6e4ca6d003a4b/pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/step/HarnessApprovalStepExecutionDetails.java#L31)):*
> ```Java
> @TypeAlias("HarnessApprovalStepExecutionDetails")
> @RecasterAlias("io.harness.execution.step.HarnessApprovalStepExecutionDetails")
> public class HarnessApprovalStepExecutionDetails implements StepExecutionDetails {
> ```

Why these beans are required in contracts folder? are these shared with any other module?
___
*[`pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/step/StepExecutionEntity.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/49301#-NYRPSMy1YI1-qBce1yz:-NYRPSMzC14_As_qe5cF:bemprg4) ([raw file](https://github.com/harness/harness-core/blob/56c309f3f0638d766bcbbd29c2d6e4ca6d003a4b/pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/step/StepExecutionEntity.java#L52)):*
> ```Java
> @HarnessEntity(exportable = true)
> @OwnedBy(HarnessTeam.CDP)
> public class StepExecutionEntity implements PersistentEntity, UuidAware {
> ```

why this in contracts?

**Review by abhinavmittal-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49301)* status: 8 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/step/HarnessApprovalStepExecutionDetails.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/49301#-NYReCDq2snrW78x3J7C:-NYReCDq2snrW78x3J7D:balllfw) ([raw file](https://github.com/harness/harness-core/blob/56c309f3f0638d766bcbbd29c2d6e4ca6d003a4b/pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/step/HarnessApprovalStepExecutionDetails.java#L48)):*
> ```Java
>   public static class EmbeddedUser {
>     private String name;
>     private String email;
> ```

Can we reuse embedded user class that already exists. I believe it does
___
*[`pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/step/StepExecutionDetails.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/49301#-NYRemEm9Hyfo3TI6uom:-NYRemEm9Hyfo3TI6uon:b3cuecb) ([raw file](https://github.com/harness/harness-core/blob/56c309f3f0638d766bcbbd29c2d6e4ca6d003a4b/pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/step/StepExecutionDetails.java#L27)):*
> ```Java
>       @JsonSubTypes.Type(value = JiraCreateStepExecutionDetails.class, name = "JiraCreate"),
>       @JsonSubTypes.Type(value = JiraUpdateStepExecutionDetails.class, name = "JiraUpdate")
> })
> ```

can we do json sub typing based on type instead of name

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/step/HarnessApprovalStepExecutionDetails.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/49301#-NYRPBlX3SSwLLO0eq04:-NYXBXbd5yIvUWejFoBM:bn72t01) ([raw file](https://github.com/harness/harness-core/blob/56c309f3f0638d766bcbbd29c2d6e4ca6d003a4b/pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/step/HarnessApprovalStepExecutionDetails.java#L31)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why these beans are required in contracts folder? are these shared with any other module?
</blockquote></details>

moved to src

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/step/HarnessApprovalStepExecutionDetails.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/49301#-NYReCDq2snrW78x3J7C:-NYXBZbh5cVuNUl46XZN:b-1hinr9) ([raw file](https://github.com/harness/harness-core/blob/56c309f3f0638d766bcbbd29c2d6e4ca6d003a4b/pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/step/HarnessApprovalStepExecutionDetails.java#L48)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Can we reuse embedded user class that already exists. I believe it does
</blockquote></details>

reused that one
I added a new, as Approval step was converting to another dto, which was only for the approval step

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/step/StepExecutionDetails.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/49301#-NYRemEm9Hyfo3TI6uom:-NYXFoFzC1kFZfl5UTNl:b-6l7y9f) ([raw file](https://github.com/harness/harness-core/blob/56c309f3f0638d766bcbbd29c2d6e4ca6d003a4b/pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/step/StepExecutionDetails.java#L27)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

can we do json sub typing based on type instead of name
</blockquote></details>

Already implemented, we use TypeAlias, so that even if package name changes the type alias can remain same.

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger uts

**Review by abhinavmittal-harness — DISMISSED** [review]
> Reviewed 18 of 18 files at r4, 2 of 2 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49301)* status: 24 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 16 of 18 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49301)* status: 7 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/test/resources/recaster/alias/alias.txt` line 71 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYbzTzi3GaCJ0umxNWk:-NYbzTzi3GaCJ0umxNWl:bnd2euc) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration/src/test/resources/recaster/alias/alias.txt#L71)):*
> ```help
> io.harness.execution.step.JiraUpdateStepExecutionDetails
> io.harness.execution.step.JiraApprovalStepExecutionDetails
> io.harness.execution.step.CustomApprovalStepExecutionDetails
> ```

not required, as these are used only for step parameters
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/JiraUpdateStepExecutionDetails.java` line 29 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYbzltK7gLyeSlB3JhG:-NYbzltK7gLyeSlB3JhH:btltd10) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/JiraUpdateStepExecutionDetails.java#L29)):*
> ```Java
> @JsonTypeName("JiraUpdate")
> @TypeAlias("JiraUpdateStepExecutionDetails")
> @RecasterAlias("io.harness.execution.step.JiraUpdateStepExecutionDetails")
> ```

put inside step/jira package and same for others
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntity.java` line 54 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYc-A2O3MnLvMdK7btV:-NYc-A2O3MnLvMdK7btW:b-9jo15e) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntity.java#L54)):*
> ```Java
> public class StepExecutionEntity implements PersistentEntity, UuidAware {
>   @org.springframework.data.annotation.Id @Id String uuid;
>   @CreatedDate private long createdAt;
> ```

dont use long but instead Use Long, this is good for handling null or making or removing fields in future
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntity.java` line 80 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYbzut-1fHH7_4KHfqO:-NYbzut-1fHH7_4KHfqP:b3x9yct) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntity.java#L80)):*
> ```Java
>     return ImmutableList.<MongoIndex>builder()
>         .add(SortCompoundMongoIndex.builder()
>                  .name("sorted_step_execution_info_idx")
> ```

sorted keyword is not required



_Code quote:_
```Java
sorted_
```
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntityUpdateDTO.java` line 18 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYc-71R-73q5WEV_IHg:-NYc-71R-73q5WEV_IHh:b-ege5qw) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntityUpdateDTO.java#L18)):*
> ```Java
> @Data
> @Builder
> public class StepExecutionEntityUpdateDTO {
> ```

owned by?

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration/src/test/resources/recaster/alias/alias.txt` line 71 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYbzTzi3GaCJ0umxNWk:-NYcKDKTArX3xwH-QcnY:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration/src/test/resources/recaster/alias/alias.txt#L71)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

not required, as these are used only for step parameters
</blockquote></details>

done

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/JiraUpdateStepExecutionDetails.java` line 29 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYbzltK7gLyeSlB3JhG:-NYcKF2EDMHUtxzzUBf-:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/JiraUpdateStepExecutionDetails.java#L29)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

put inside step/jira package and same for others
</blockquote></details>

done

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntityUpdateDTO.java` line 18 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYc-71R-73q5WEV_IHg:-NYcKFsb3O8PdUaVHveh:b-7tfmjp) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntityUpdateDTO.java#L18)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

owned by?
</blockquote></details>

added

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntity.java` line 80 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYbzut-1fHH7_4KHfqO:-NYcKHI8BWCij_xgwq7V:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntity.java#L80)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

sorted keyword is not required
</blockquote></details>

removed

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntity.java` line 54 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYc-A2O3MnLvMdK7btV:-NYcKIJm3INuDNsc_kmG:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntity.java#L54)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dont use long but instead Use Long, this is good for handling null or making or removing fields in future
</blockquote></details>

done

**Comment by RishabhGupta34** [comment]
trigger uts

**Review by anilchowdhury-harness — APPROVED** [review]

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 9 of 18 files at r4, 1 of 2 files at r5, 9 of 13 files at r7, 4 of 5 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49301)* status: Some of the checks are too old. 14 file(s) to review. 1 change requests. 5. unresolved discussions.

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntity.java` line 80 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYbzut-1fHH7_4KHfqO:-NYwbyXyCZ4EFzHPnlpC:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntity.java#L80)):*
<details><summary><i>Previously, RishabhGupta34 (Rishabh Gupta) wrote…</i></summary><blockquote>

removed
</blockquote></details>

done

**Review by RishabhGupta34 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49301)* status: 14 file(s) to review. 1 change requests. 5. unresolved discussions. 

___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntityUpdateDTO.java` line 18 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYc-71R-73q5WEV_IHg:-NYwc0jL3lMOqSRkSB5U:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntityUpdateDTO.java#L18)):*
<details><summary><i>Previously, RishabhGupta34 (Rishabh Gupta) wrote…</i></summary><blockquote>

added
</blockquote></details>

done

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/step/StepExecutionEntity.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/49301#-NYRPSMy1YI1-qBce1yz:-NYwc5u85VdQfC7mpYhu:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/56c309f3f0638d766bcbbd29c2d6e4ca6d003a4b/pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/step/StepExecutionEntity.java#L52)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this in contracts?
</blockquote></details>

done

**Comment by RishabhGupta34** [comment]
> > Reviewed 16 of 18 files at r4, 1 of 2 files at r5, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/49301)_ status: 7 file(s) to review. 1 change requests. 1 of 2 approvals obtained.
> 
> _[`pipeline-service/modules/orchestration/src/test/resources/recaster/alias/alias.txt` line 71 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYbzTzi3GaCJ0umxNWk:-NYbzTzi3GaCJ0umxNWl:bnd2euc) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration/src/test/resources/recaster/alias/alias.txt#L71)):_
> 
> > ```
> > io.harness.execution.step.JiraUpdateStepExecutionDetails
> > io.harness.execution.step.JiraApprovalStepExecutionDetails
> > io.harness.execution.step.CustomApprovalStepExecutionDetails
> > ```
> 
> not required, as these are used only for step parameters
> 
> _[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/JiraUpdateStepExecutionDetails.java` line 29 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYbzltK7gLyeSlB3JhG:-NYbzltK7gLyeSlB3JhH:btltd10) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/JiraUpdateStepExecutionDetails.java#L29)):_
> 
> > ```java
> > @JsonTypeName("JiraUpdate")
> > @TypeAlias("JiraUpdateStepExecutionDetails")
> > @RecasterAlias("io.harness.execution.step.JiraUpdateStepExecutionDetails")
> > ```
> 
> put inside step/jira package and same for others
> 
> _[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntity.java` line 54 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYc-A2O3MnLvMdK7btV:-NYc-A2O3MnLvMdK7btW:b-9jo15e) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntity.java#L54)):_
> 
> > ```java
> > public class StepExecutionEntity implements PersistentEntity, UuidAware {
> >   @org.springframework.data.annotation.Id @Id String uuid;
> >   @CreatedDate private long createdAt;
> > ```
> 
> dont use long but instead Use Long, this is good for handling null or making or removing fields in future
> 
> _[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntity.java` line 80 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYbzut-1fHH7_4KHfqO:-NYbzut-1fHH7_4KHfqP:b3x9yct) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntity.java#L80)):_
> 
> > ```java
> >     return ImmutableList.<MongoIndex>builder()
> >         .add(SortCompoundMongoIndex.builder()
> >                  .name("sorted_step_execution_info_idx")
> > ```
> 
> sorted keyword is not required
> 
> _Code quote:_
> 
> ```java
> sorted_
> ```
> 
> _[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntityUpdateDTO.java` line 18 at r6](https://reviewable.io/reviews/harness/harness-core/49301#-NYc-71R-73q5WEV_IHg:-NYc-71R-73q5WEV_IHh:b-ege5qw) ([raw file](https://github.com/harness/harness-core/blob/bd83f6a82f9156abd8c373e8c50cbea6b6858aed/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/step/StepExecutionEntityUpdateDTO.java#L18)):_
> 
> > ```java
> > @Data
> > @Builder
> > public class StepExecutionEntityUpdateDTO {
> > ```
> 
> owned by?

done

**Pull request merged**
