### PR TITLE
fix: [PL-37908]: Expose delegate metric when delegate is busy

### PR DESCRIPTION
**Pull request by raghuAtWings**
## Describe your changes
Fix the metric types and recording the metrics. 

**Tests done**
Tested this in PR env and tested all metrics showing up correctly in prometheus

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47437)

### CODE REVIEW

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 747 at r1](https://reviewable.io/reviews/harness/harness-core/47437#-NUgmK0_E2OzwvAo7eU-:-NUgmK0_E2OzwvAo7eU0:b-1o0wrc) ([raw file](https://github.com/harness/harness-core/blob/9efa2248e392075f914c0fd8ea62b88bec9056bb/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L747)):*
> ```Java
>           RESOURCE_CONSUMPTION_ABOVE_THRESHOLD.getMetricName(), new String[] {DELEGATE_NAME}, 1.0);
>       metricRegistry.registerCounterMetric(
>           TASK_REJECTED.getMetricName(), new String[] {DELEGATE_NAME}, "Total number of task rejected");
> ```

should this be  metricRegistry.recordCounterInc?

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2431 at r1](https://reviewable.io/reviews/harness/harness-core/47437#-NUgmetN8nCiRHPGFscE:-NUgmetN8nCiRHPGFscF:b-yid7g) ([raw file](https://github.com/harness/harness-core/blob/9efa2248e392075f914c0fd8ea62b88bec9056bb/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2431)):*
> ```Java
>       metricRegistry.recordCounterInc(
>           TASK_TIMEOUT.getMetricName(), new String[] {DELEGATE_NAME, taskData.getTaskType()});
>       Optional.ofNullable(currentlyExecutingFutures.get(taskId).getTaskFuture())
> ```

should TASK_TIME be gauge as it's goes up and down

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2431 at r1](https://reviewable.io/reviews/harness/harness-core/47437#-NUgmetN8nCiRHPGFscE:-NUgoH_-7m9dHUA4YaRN:bvhpxb) ([raw file](https://github.com/harness/harness-core/blob/9efa2248e392075f914c0fd8ea62b88bec9056bb/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2431)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

should TASK_TIME be gauge as it's goes up and down
</blockquote></details>

no, users would need to plot how many tasks are timing out within a time perioid

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47437)* status: 8 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by jennyjames21 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47437)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by raghuAtWings** [comment]
trigger uts

**Pull request merged**
