### PR TITLE
feat: [PL-26646]: cg git sync polling

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35483)

### CODE REVIEW

**Comment by abhinav-harness** [comment]
trigger feature-build

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35483)

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35483)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlChangeSetServiceImpl.java` line 556 at r3](https://reviewable.io/reviews/harness/harness-core/35483#-N8hM7nU4PMNsl_HV8n6:-N8hM7nU4PMNsl_HV8n7:b-uj6wej) ([raw file](https://github.com/harness/harness-core/blob/d4e2ed9633a82a1576eac1f7fb1b1637759bb705/400-rest/src/main/java/software/wings/service/impl/yaml/YamlChangeSetServiceImpl.java#L556)):*
> ```Java
>                                       .accountId(accountId)
>                                       .fullSync(false)
>                                       .gitToHarness(true)
> ```

add queuedOn ?

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35483)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlChangeSetServiceImpl.java` line 556 at r3](https://reviewable.io/reviews/harness/harness-core/35483#-N8hM7nU4PMNsl_HV8n6:-N8hMuiXAVLOwnMVICRj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d4e2ed9633a82a1576eac1f7fb1b1637759bb705/400-rest/src/main/java/software/wings/service/impl/yaml/YamlChangeSetServiceImpl.java#L556)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

add queuedOn ?
</blockquote></details>

Done.

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 3 of 8 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35483)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35483)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by aman-harness — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 3 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35483)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
trigger codebasehash

**Pull request merged**
