### PR TITLE
fix: [PL-30748]: Add index for InstanceServiceImpl.getActiveInstances…

### PR DESCRIPTION
**Pull request by rijajoo**
…ByAccountOrgProjectAndService query

## Describe your changes

Criteria criteria = Criteria.where(InstanceKeys.accountIdentifier)
                              .is(accountIdentifier)
                              .and(InstanceKeys.orgIdentifier)
                              .is(orgIdentifier)
                              .and(InstanceKeys.projectIdentifier)
                              .is(projectIdentifier)
                              .and(InstanceKeys.serviceIdentifier)
                              .is(serviceIdentifier)
                              .and(InstanceKeys.isDeleted)
                              .is(false);

Added index to optimise this query.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42292)

### CODE REVIEW

**Comment by rijajoo** [comment]
trigger messagecheck

**Comment by rijajoo** [comment]
trigger ti0

**Review by ankit-harness — APPROVED** [review]

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42292#-:-NL5u0R19Sl7lVIy0hjH:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42292)* status: :shipit: complete! ✓

**Review by VikasMaddukuriHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42292)* status: Some of the checks are too old. 1 change requests. 1 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/42292#-NLKCvlP48J3CLu-GB7f:-NLKCvlP48J3CLu-GB7g:bnirw2k) (no related file):*
I don't think we need to add this new index. There is already an index whose prefix is the same index that is being added. That index is "accountId_organizationId_projectId_serviceId_envId_isDeleted_createdAt_deletedAt_idx". 

___

**Review by VikasMaddukuriHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42292)* status: Some of the checks are too old. 1 change requests. 1 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/42292#-NLKCvlP48J3CLu-GB7f:-NLKELWUDVMC8OQjpT5l:b-9lzogb) (no related file):*
<details><summary><i>Previously, VikasMaddukuriHarness (VikasMaddukuriHarness) wrote…</i></summary><blockquote>

I don't think we need to add this new index. There is already an index whose prefix is the same index that is being added. That index is "accountId_organizationId_projectId_serviceId_envId_isDeleted_createdAt_deletedAt_idx". 
</blockquote></details>

Please ignore the above index. The existing index which has a prefix is this accountId_organizationId_projectId_serviceId_isDeleted_createdAt_deletedAt_idx

___

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42292)* status: Some of the checks are too old. 1 change requests.

**Pull request closed without merging**
