### PR TITLE
feat: [CDS-76036]: Remove time_bucket_gapfill for timescale migration 

### PR DESCRIPTION
**Pull request by mani5h-harness**
## Describe your changes
This PR adds replacement for time_bucket_gapfill for InstanctStatsDataFetcher and updates the related tests

This solves the following tickets
https://harness.atlassian.net/browse/CDS-76032 - Replace time_bucket_gapfill functionality (AbstractStatsDataFetcher.java#L218)
https://harness.atlassian.net/browse/CDS-76036 - Replace time_bucket_gapfill functionality (AbstractDataFetcherTestBase.java#L155 to L165)

Changes - 
-- Added harness_time_bucket_list sql function and used it in left join in place of time_bucket_gapfill

Note - As per the discussion on the tickets, this seems to be dead code. I tried removing the tests and InstanceStatsDataFetcher altogether but a lot of tests were failing with missing implementation for InstanceStats annotation.

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52787)

### CODE REVIEW

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52787#-:-Ne98Ewz6Ft_8TwtnU5e:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by mani5h-harness** [comment]
trigger pmd

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52787#-:-NeDr9Jg9u0goOjoHR2X:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by harness-david — APPROVED** [review]
Changes look good.  I thought this code was not even used so I did not look closely when I created the harness_time_bucket_list function... it would have been easier if the first 2 parameters were timestamptz.  In any event, the changes should work with the function.

**Comment by mani5h-harness** [comment]
trigger pmd

**Comment by mani5h-harness** [comment]
trigger uts

**Comment by mani5h-harness** [comment]
trigger recency

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52787#-:-NeoN3Na7v5EWzwrJfXW:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by RishabhGupta34 — APPROVED** [review]

**Comment by mani5h-harness** [comment]
trigger review

**Comment by mani5h-harness** [comment]
trigger uts

**Comment by mani5h-harness** [comment]
trigger ut1 ut7 ut8 ut9

**Pull request merged**
