### PR TITLE
[feat]:[CDS-42597]: Add new exceptions and handlers to use the new error fra…

### PR DESCRIPTION
**Pull request by nassergonzalez**
…mework

## Describe your changes
Add new error handling for ARM. The new exceptions, with messages and hints can be found here:
https://harness.atlassian.net/wiki/spaces/PD/pages/21184675904/Azure+ARM+BP+-+Error+Handling

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37720)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 11 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 9 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37720)

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 17 of 19 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37720)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java` line 98 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCUGIikB-WJmvq-CU-R:-NCUGIikB-WJmvq-CU-S:benhvbr) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java#L98)):*
> ```Java
>           context.getDeploymentName(), e.getMessage());
>       logCallback.saveExecutionLog(message, ERROR, FAILURE);
>       throw new AzureARMTaskException(message, EnumSet.of(FailureType.TIMEOUT_ERROR));
> ```

nit: while I know that this use case is unlikely because of pipeline timeout strategy, but would be great to throw a runtime exception this case as well and add hint and explanation later 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCUG8CP59XKJBJLhIZ1:-NCUG8CP59XKJBJLhIZ2:b-qrgnt0) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java#L99)):*
> ```Java
>       logCallback.saveExecutionLog(message, ERROR, FAILURE);
>       throw new AzureARMTaskException(message, EnumSet.of(FailureType.TIMEOUT_ERROR));
>     } catch (AzureARMResourceGroupScopeException | AzureARMSubscriptionScopeException | AzureARMManagementScopeException
> ```

I believe these are all your Arm related exceptions. In this case, you can catch only AzureARMRuntimeException, all other exception are subtype of this one
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMDeploymentService.java` line 218 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCUQgzv6QrcTIO87EFr:-NCUQgzv6QrcTIO87EFs:b-ga3vcs) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMDeploymentService.java#L218)):*
> ```Java
>       return performSteadyStateCheckManagementGroupScope(context);
>     } catch (Exception ex) {
>       if (ex.getMessage().contains("does not have authorization")) {
> ```

This may result in potential NPE if message is null. Is not very common for an exception to have a null message, but it is a potential issue. Either null check should be added, either a better logic to be added here with handling particular exception that can have in message does not have authorization
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMDeploymentService.java` line 274 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURN4h3X_kLC5ts19j:-NCURN4h3X_kLC5ts19k:bvibf1a) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMDeploymentService.java#L274)):*
> ```Java
>     } catch (Exception ex) {
>       if (ex.getMessage().contains("does not have authorization")) {
>         throw new AzureARMTenantScopeException(ERROR_INVALID_TENANT_CREDENTIALS);
> ```

same here: This may result in potential NPE if message is null. Is not very common for an exception to have a null message, but it is a potential issue. Either null check should be added, either a better logic to be added here with handling particular exception that can have in message does not have authorization
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/exception/AzureARMRuntimeExceptionHandler.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURTPU2sF2cYYMH6oj:-NCURTPU2sF2cYYMH6ok:b-y63cjn) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/exception/AzureARMRuntimeExceptionHandler.java#L31)):*
> ```Java
> import java.util.Set;
> 
> public class AzureARMRuntimeExceptionHandler implements ExceptionHandler {
> ```

please add owner 
___
*[`980-commons/src/main/java/io/harness/exception/ngexception/AzureARMTaskException.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURkWu3L8y4LGzTuwK:-NCURkWu3L8y4LGzTuwL:bs9amxn) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/980-commons/src/main/java/io/harness/exception/ngexception/AzureARMTaskException.java#L18)):*
> ```Java
> import java.util.EnumSet;
> 
> public class AzureARMTaskException extends WingsException {
> ```

please add owner tean
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMDeploymentException.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURvCS6sD9Kk3g_H-u:-NCURvCS6sD9Kk3g_H-v:bs9amxm) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMDeploymentException.java#L10)):*
> ```Java
> package io.harness.exception.runtime.azure;
> 
> public class AzureARMDeploymentException extends AzureARMRuntimeException {
> ```

please add owner team
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMManagementScopeException.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURo1S6I4anLah3iZW:-NCURo1S6I4anLah3iZX:bs9amxm) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMManagementScopeException.java#L10)):*
> ```Java
> package io.harness.exception.runtime.azure;
> 
> public class AzureARMManagementScopeException extends AzureARMRuntimeException {
> ```

please add owner team
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMResourceGroupScopeException.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURpMT2UzMiZKvkUnF:-NCURpMT2UzMiZKvkUnG:bs9amxm) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMResourceGroupScopeException.java#L10)):*
> ```Java
> package io.harness.exception.runtime.azure;
> 
> public class AzureARMResourceGroupScopeException extends AzureARMRuntimeException {
> ```

please add owner team
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMRuntimeException.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURqtgC4-VBdekgKzJ:-NCURqtgC4-VBdekgKzK:bs9amxm) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMRuntimeException.java#L10)):*
> ```Java
> package io.harness.exception.runtime.azure;
> 
> public class AzureARMRuntimeException extends RuntimeException {
> ```

please add owner team
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMSubscriptionScopeException.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURrjQ15E_CDXTzGQV:-NCURrjQ15E_CDXTzGQW:bs9amxm) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMSubscriptionScopeException.java#L10)):*
> ```Java
> package io.harness.exception.runtime.azure;
> 
> public class AzureARMSubscriptionScopeException extends AzureARMRuntimeException {
> ```

please add owner team
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMTenantScopeException.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURsQLDs8drtlWYwRC:-NCURsQLDs8drtlWYwRD:bs9amxm) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMTenantScopeException.java#L10)):*
> ```Java
> package io.harness.exception.runtime.azure;
> 
> public class AzureARMTenantScopeException extends AzureARMRuntimeException {
> ```

please add owner team
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMValidationException.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURt89-FpLmCIlfTMC:-NCURt89-FpLmCIlfTMD:bs9amxm) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMValidationException.java#L10)):*
> ```Java
> package io.harness.exception.runtime.azure;
> 
> public class AzureARMValidationException extends AzureARMRuntimeException {
> ```

please add owner team

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 17 of 19 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37720)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMDeploymentService.java` line 273 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCZ1d3gAmEgIpDPMYAL:-NCZ1d3gAmEgIpDPMYAM:b-aob7no) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMDeploymentService.java#L273)):*
> ```Java
>       return performSteadyStateCheckTenantScope(context);
>     } catch (Exception ex) {
>       if (ex.getMessage().contains("does not have authorization")) {
> ```

We can extract "does not have authorization" into a constant once we use it in multiple places.

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37720)* status: 4 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCUG8CP59XKJBJLhIZ1:-NCZm9Ts-XAkl3VBevH7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java#L99)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I believe these are all your Arm related exceptions. In this case, you can catch only AzureARMRuntimeException, all other exception are subtype of this one
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMDeploymentService.java` line 218 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCUQgzv6QrcTIO87EFr:-NCZoADI4vzpnyRwrC3b:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMDeploymentService.java#L218)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This may result in potential NPE if message is null. Is not very common for an exception to have a null message, but it is a potential issue. Either null check should be added, either a better logic to be added here with handling particular exception that can have in message does not have authorization
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMDeploymentService.java` line 273 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCZ1d3gAmEgIpDPMYAL:-NCZpWnI-nuT-6LOgMj6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMDeploymentService.java#L273)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

We can extract "does not have authorization" into a constant once we use it in multiple places.
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMDeploymentService.java` line 274 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURN4h3X_kLC5ts19j:-NCZpp-g7KORr02fAeXD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMDeploymentService.java#L274)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

same here: This may result in potential NPE if message is null. Is not very common for an exception to have a null message, but it is a potential issue. Either null check should be added, either a better logic to be added here with handling particular exception that can have in message does not have authorization
</blockquote></details>

Done.

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 2 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37720)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions.

**Comment by nassergonzalez** [comment]
trigger ti1

**Review by abosii-harness — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37720)* status: :shipit: complete! ✓

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37720)* status: 1 change requests. 9. unresolved discussions. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/exception/AzureARMRuntimeExceptionHandler.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURTPU2sF2cYYMH6oj:-NC_YWtq9KI0THeixS72:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/exception/AzureARMRuntimeExceptionHandler.java#L31)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

please add owner 
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/exception/ngexception/AzureARMTaskException.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURkWu3L8y4LGzTuwK:-NC_Y_jn43ojIJB5nM0R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/980-commons/src/main/java/io/harness/exception/ngexception/AzureARMTaskException.java#L18)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

please add owner tean
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMDeploymentException.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURvCS6sD9Kk3g_H-u:-NC_YdH59EY93nLCNQY3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMDeploymentException.java#L10)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

please add owner team
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMManagementScopeException.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURo1S6I4anLah3iZW:-NC_YnM80YaNsLbWMOHu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMManagementScopeException.java#L10)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

please add owner team
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMResourceGroupScopeException.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURpMT2UzMiZKvkUnF:-NC_Ynt1D0A7F2n3e6xd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMResourceGroupScopeException.java#L10)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

please add owner team
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMRuntimeException.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURqtgC4-VBdekgKzJ:-NC_YoSJ19ejcDyEr-ms:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMRuntimeException.java#L10)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

please add owner team
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMSubscriptionScopeException.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURrjQ15E_CDXTzGQV:-NC_Yp-U9g21wYhytgxr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMSubscriptionScopeException.java#L10)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

please add owner team
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMTenantScopeException.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURsQLDs8drtlWYwRC:-NC_YpSO4WaOBLTA0ph3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMTenantScopeException.java#L10)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

please add owner team
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMValidationException.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/37720#-NCURt89-FpLmCIlfTMC:-NC_YpqP3y1jV9G4nCKR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26a01755a7c567acdb338ce67e0e087cb5879b37/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureARMValidationException.java#L10)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

please add owner team
</blockquote></details>

Done.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37720)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37720#-:-NCdBimP3s3GqkNnz2M8:bnfp4nl)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
> Reviewed 4 of 19 files at r1, 5 of 6 files at r2, 1 of 1 files at r4, 9 of 9 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37720)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37720#-:-NCeInEW7iLtQU9QHM1W:bnfp4nl)* status: :shipit: complete! ✓

**Comment by nassergonzalez** [comment]
trigger codebasehash

**Pull request merged**
