### PR TITLE
fix: [PL-30077]: Redundant subsequence index cleanup in CDP

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40761)

### CODE REVIEW

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40761)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/infrastructure/CloudFormationRollbackConfig.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/40761#-NI2EfLgCTWmpj5czOQZ:-NI2EfLgCTWmpj5czOQ_:b-st8g67) ([raw file](https://github.com/harness/harness-core/blob/8c4ce0eaa29b83b5994a45e34313048f3b6cfc1a/400-rest/src/main/java/software/wings/beans/infrastructure/CloudFormationRollbackConfig.java#L49)):*
> ```Java
>   @Id @NotNull(groups = {Update.class}) @SchemaIgnore private String uuid;
>   @FdIndex private String accountId;
>   @FdIndex @NotNull @SchemaIgnore protected String appId;
> ```

Why do we remove  @FdIndex only for that field?

**Review by abhinavmittal-harness — DISMISSED** [review]
> Reviewed 8 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40761)* status: 9 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40761)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/infrastructure/CloudFormationRollbackConfig.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/40761#-NI2EfLgCTWmpj5czOQZ:-NIDO2G1Be2W_Q6bX7zB:b-a4q1gj) ([raw file](https://github.com/harness/harness-core/blob/8c4ce0eaa29b83b5994a45e34313048f3b6cfc1a/400-rest/src/main/java/software/wings/beans/infrastructure/CloudFormationRollbackConfig.java#L49)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Why do we remove  @FdIndex only for that field?
</blockquote></details>

We have other compound indexes which has appId field. So removed index on that filed. For accountId and createdAt, there are no other compound indexes which are covering this. Let me know if this answers your question.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40761)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/infrastructure/CloudFormationRollbackConfig.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/40761#-NI2EfLgCTWmpj5czOQZ:-NIDQ2Oo4KDuefwRVi47:bzafjh) ([raw file](https://github.com/harness/harness-core/blob/8c4ce0eaa29b83b5994a45e34313048f3b6cfc1a/400-rest/src/main/java/software/wings/beans/infrastructure/CloudFormationRollbackConfig.java#L49)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

createdAt and entityId are also are part of  byAppAndEntityAndAwsConfig byAppAndEntityAndAwsConfigAndCustomStackNameAndRegion and byAppAndEntityAndCustomStackNameAndRegion indexes. Or I missed something?
</blockquote></details>

The way indexes work is if we have 2 indexes, if one of the index is a prefix of other, then the former is redundant is it will be covered in later one. 
We have index for createdAt but in other compound indexes, we do not have createdAt as the prefix. So createdAt field will not be covered in those indexes.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40761)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40761)* status: :shipit: complete! ✓

**Pull request merged**
