### PR TITLE
fix: [CDS-34238]: Fix helm repository already exists when connector is updated

### PR DESCRIPTION
**Pull request by abosii-harness**
Draft solution for `Error: repository name (reponame) already exists, please specify a different name`. The idea is to try again helm repo add with flag --force-update, which based on helm code will skip validation on existing repo. 
Other solutions will be to execute helm repo remove then helm repo add again.

Cons about this solution:
- Older version of helm v3 doesn't support --force-update option (I think it was introduced in v3.3.x), on other hand this error will not be thrown if --no-update option is not provided

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31034)

### CODE REVIEW

**Review by achyuth-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31034)* status: :shipit: complete! ✓

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31034)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31034)* status: :shipit: complete! ✓

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Pull request merged**
