### PR TITLE
fix: [PL-21772]: Added account identifier in Query params to fix

### PR DESCRIPTION
**Pull request by boopesh007**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31456)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31456)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java, line 552 at r1](https://reviewable.io/reviews/harness/harness-core/31456#-MyBlChR3nGs1rtX3aK2:-MyBlChR3nGs1rtX3aK3:b-5ueoih) ([raw file](https://github.com/harness/harness-core/blob/844128442af0ae311d4ed4afd86c528840555a52/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java#L552)):*
> ```Java
>                                NGCommonEntityConstants.CONNECTOR_TYPE) ConnectorType connectorType,
>       @Parameter(description = ACCOUNT_PARAM_MESSAGE, required = true) @NotBlank @QueryParam(
>           NGCommonEntityConstants.ACCOUNT_KEY) String accountIdentifier) {
> ```

can we put accountIdentifier as first param? The reason is that the same order is shown in swagger docs and it would be better if we try to follow a convention where accountIdentifier is shown as one of the main params for us and then the corresponding required API param follow

**Review by boopesh007 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31456)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java, line 552 at r1](https://reviewable.io/reviews/harness/harness-core/31456#-MyBlChR3nGs1rtX3aK2:-MyBo-6R3AR-gN-cHRB7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/844128442af0ae311d4ed4afd86c528840555a52/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java#L552)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we put accountIdentifier as first param? The reason is that the same order is shown in swagger docs and it would be better if we try to follow a convention where accountIdentifier is shown as one of the main params for us and then the corresponding required API param follow
</blockquote></details>

Done.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31456)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31456)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31456#-:-MyBpSsI8IC08u-yX1Ck:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31456)* status: :shipit: complete! ✓

**Pull request merged**
