### PR TITLE
[fix]: [PL-22153]: Fix the issue where the status of a full sync job/ full sync file was not correctly updated

### PR DESCRIPTION
**Pull request by DeepakPatankar**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30299)

### CODE REVIEW

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30299)* status: :shipit: complete! ✓

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30299)* status: 1 change requests. 1. unresolved discussions. 

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/harness/harness-core/30299#-MuR7gl29edyvtByZxaD):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

where are we fixing full sync job status
</blockquote></details>

The logic for that was already present. There was a issue where I was not setting the value of file path when sending the response from the sdk.

In our git sync side we required file path at one place and it failed. Since program failed in between it didn't set the value of the full sync job.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30299)* status: :shipit: complete! ✓

**Comment by DeepakPatankar** [comment]
trigger messagecheck

**Comment by DeepakPatankar** [comment]
trigger messagecheck

**Comment by DeepakPatankar** [comment]
trigger messagecheck

**Pull request merged**
