### PR TITLE
[feat]: [PIE-8127]: Added code to make input-set independent of repo

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added code to make remote input sets independent of pipeline repo and branch. Test suite covers the CRUD flows and execute flows either via api or curls.

1. creation: store the created branch 
2. list api: no change
3. overlay IS creation: store the created branch
4. get: load from default if not fallBackBranch, creation of new index
5. update: no changes
6. run: no changes
7. merge api: infer the parent scope in the merge api

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43745)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/beans/entity/InputSetEntity.java` line 146 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOGZ8VN-HZvX9Qo_6iq:-NOGZ8VN-HZvX9Qo_6ir:b-2mf1lk) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/beans/entity/InputSetEntity.java#L146)):*
> ```Java
>   @Setter @NonFinal String connectorRef;
>   @Wither @Setter @NonFinal String repoURL;
>   @Wither @Setter @NonFinal String fallBackBranch;
> ```

Whats the corresponding field in pipeline or template? I didn't see any such field over there.



_Code quote:_
```Java
String fallBackBranch;
```

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 212 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOGZSGH42cC7H8UFjMd:-NOGZSGH42cC7H8UFjMe:b-gn5wg0) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L212)):*
> ```Java
>       String pipelineRepoID, List<String> stageIdentifiers, String lastYamlToMerge) {
>     Set<String> inputSetVersions = new HashSet<>();
>     PipelineExceptionsHelper.setupGitParentEntityDetails(accountId, orgIdentifier, projectIdentifier, null, null);
> ```

Why is pipelines "exceptions" helper having method to setup git parent entity details?



_Code quote:_
```Java
PipelineExceptionsHelper
```

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 202 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOGZxncCpdXr4bDh8zF:-NOGZxncCpdXr4bDh8zG:bovsp72) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L202)):*
> ```Java
>     try {
>       savedEntity = fetchRemoteEntity(accountIdentifier, orgIdentifier, projectIdentifier, savedEntity, branch);
>     } catch (WingsException ex) {
> ```

log exception

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 217 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOG_AK-AddpDVc3D13a:-NOG_AK-AddpDVc3D13b:b2hwtpi) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L217)):*
> ```Java
>   }
> 
>   private boolean shouldRetryWithFallBackBranch(
> ```

this can come from common source I believe

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 218 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOG_DwK1740iUHrwzxH:-NOG_DwK1740iUHrwzxI:b8qh2ec) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L218)):*
> ```Java
> 
>   private boolean shouldRetryWithFallBackBranch(
>       ScmException scmException, String branchTried, String templateFallBackBranch) {
> ```

why's terminology "template"fallbackBranch used here?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/utils/PipelineExceptionsHelper.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOG_TN44xh-zeZuYT-M:-NOG_TN44xh-zeZuYT-N:bhr8kz9) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/utils/PipelineExceptionsHelper.java#L49)):*
> ```Java
> 
>   public void setupGitParentEntityDetails(String accountIdentifier, String orgIdentifier, String projectIdentifier,
>       String repoFromTemplate, String connectorFromTemplate) {
> ```

whats "repoFromTEMPLATE" and "connectorFromTEMPLATE"?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/utils/PipelineExceptionsHelper.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOG_anc8IY9AwnxGef_:-NOG_and1Z2SuEf98v50:b-roh2lo) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/utils/PipelineExceptionsHelper.java#L59)):*
> ```Java
>       }
> 
>       // Set Parent's ConnectorRef
> ```

These seem redundant comments. It doesn't help to enhance any logic/code interpretation IMO. Can we check and improve them if required, otherwise we can remove them at all.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43745)* status: 21 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOGYv2F8dyQQx3xy66x:-NOIAvBMBCezqwkU7LzD:bpzdyfc) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L91)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we would need to update these APIs also right?
</blockquote></details>

we dont need to change anything in this, have informed UI to populate the GetEntityFindInfo object accordingly 
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/beans/entity/InputSetEntity.java` line 146 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOGZ8VN-HZvX9Qo_6iq:-NOIAXmm0pE2JeGx9QwW:bnw2gxd) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/beans/entity/InputSetEntity.java#L146)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Whats the corresponding field in pipeline or template? I didn't see any such field over there.
</blockquote></details>

in case of pipeline, we are storing this in the pipelineMetadataV2, its just called the branch, whereas in case of templates, as we are storing it in the same template collection, its fallBackBranch
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 202 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOGZxncCpdXr4bDh8zF:-NOIC1Kh5N9AuGwijBYZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L202)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

log exception
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 218 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOG_DwK1740iUHrwzxH:-NOIC2KpB-Xx75yLBS7o:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L218)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why's terminology "template"fallbackBranch used here?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/utils/PipelineExceptionsHelper.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOG_TN44xh-zeZuYT-M:-NOII2oE5qElW5jTYsyg:bs9o4z7) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/utils/PipelineExceptionsHelper.java#L49)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats "repoFromTEMPLATE" and "connectorFromTEMPLATE"?
</blockquote></details>

Done.
Was added as part of testing and was not removed

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43745)* status: 26 file(s) to review. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 212 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOGZSGH42cC7H8UFjMd:-NOIIIU75dbAs008lcHA:b5yf2rd) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L212)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why is pipelines "exceptions" helper having method to setup git parent entity details?
</blockquote></details>

agreed, created a new helper and added this logic there
Done
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 217 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOG_AK-AddpDVc3D13a:-NOIMDvY65Gzan6e2xyg:b-xxjliv) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L217)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this can come from common source I believe
</blockquote></details>

Done.
Moved this to helpers and changed the pipeline service to use this from helper



_Code quote:_
```Java
shouldRetryWithFallBackBranch
```
___
*[`pipeline-service/service/src/main/java/io/harness/utils/PipelineExceptionsHelper.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOG_anc8IY9AwnxGef_:-NOIMyE69yhKa7SgAyqi:b-7rl0jd) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/utils/PipelineExceptionsHelper.java#L59)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

These seem redundant comments. It doesn't help to enhance any logic/code interpretation IMO. Can we check and improve them if required, otherwise we can remove them at all.
</blockquote></details>

done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 16 of 20 files at r1, 2 of 2 files at r2, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43745)* status: 26 file(s) to review. 8. unresolved discussions. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOGYv2F8dyQQx3xy66x:-NOIu0e9D6h1sZEot3V1:btzjee0) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L91)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

we dont need to change anything in this, have informed UI to populate the GetEntityFindInfo object accordingly 
</blockquote></details>

As discussed, we need to add required params here as well for the new open api spec

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/utils/PipelineGitXHelper.java` line 58 at r4](https://reviewable.io/reviews/harness/harness-core/43745#-NOIvXKl1pPM0yilPgCn:-NOIvXKl1pPM0yilPgCo:bt6dji3) ([raw file](https://github.com/harness/harness-core/blob/01bbc4bf58c44d6cf6d4cc6f1b0440edff814f4d/pipeline-service/service/src/main/java/io/harness/utils/PipelineGitXHelper.java#L58)):*
> ```Java
>       ScmException scmException, String branchTried, String entityFallBackBranch) {
>     return scmException != null && SCM_BAD_REQUEST.equals(scmException.getCode())
>         && (isNotEmpty(entityFallBackBranch) && !branchTried.equals(entityFallBackBranch));
> ```

the equals condition can be reversed for better handling

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43745)* status: 26 file(s) to review. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/43745#-NOGYv2F8dyQQx3xy66x:-NOIyWW6E2cSMdrydSIH:b-rxtpku) ([raw file](https://github.com/harness/harness-core/blob/1dc20482b6303cae4f47d2f31dcf66f48081c2f7/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L91)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

As discussed, we need to add required params here as well for the new open api spec
</blockquote></details>

https://harness.atlassian.net/browse/PIE-8351 created a ticket for the same
___
*[`pipeline-service/service/src/main/java/io/harness/utils/PipelineGitXHelper.java` line 58 at r4](https://reviewable.io/reviews/harness/harness-core/43745#-NOIvXKl1pPM0yilPgCn:-NOIyYyO2tiSbBP0hLWA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/01bbc4bf58c44d6cf6d4cc6f1b0440edff814f4d/pipeline-service/service/src/main/java/io/harness/utils/PipelineGitXHelper.java#L58)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

the equals condition can be reversed for better handling
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 16 of 20 files at r1, 2 of 2 files at r2, 8 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43745)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43745)* status: :shipit: complete! ✓

**Pull request merged**
