### PR TITLE
techdebt : [SPG-107]: fix jdk11 build on linux - add javax_javaee_api to 400-rest

### PR DESCRIPTION
**Pull request by shivagowda**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33416)

### CODE REVIEW

**Comment by shivagowda** [comment]
trigger ti0JDK11, ti1JDK11, ti2JDK11, ti3JDK11, ti4JDK11

**Comment by shivagowda** [comment]
trigger ti0JDK11, ti1JDK11, ti2JDK11, ti3JDK11, ti4JDK11

**Comment by diptiman-adak** [comment]
trigger ti1JDK11

**Comment by diptiman-adak** [comment]
trigger ti1JDK11

**Comment by diptiman-adak** [comment]
trigger ti1JDK11

**Comment by diptiman-adak** [comment]
trigger ti1JDK11

**Comment by diptiman-adak** [comment]
trigger ti1JDK11

**Comment by diptiman-adak** [comment]
trigger ti1JDK11

**Comment by diptiman-adak** [comment]
trigger ti1JDK11

**Comment by rijajoo** [comment]
trigger ti1JDK11

**Comment by diptiman-adak** [comment]
trigger ti1JDK11

**Comment by shivagowda** [comment]
trigger ti1JDK11

**Comment by shivagowda** [comment]
trigger ti0JDK11, ti1JDK11, ti2JDK11, ti3JDK11, ti4JDK11

**Comment by shivagowda** [comment]
trigger ti0JDK11, ti1JDK11, ti2JDK11, ti3JDK11, ti4JDK11

**Pull request merged**
