### PR TITLE
[fix]: [PL-27472]: Reverts "Added KryoWrapper"

### PR DESCRIPTION
**Pull request by pbarapatre10**
Reverts harness/harness-core#36443

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38733)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Comment by pbarapatre10** [comment]
trigger ti3

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38733#-:-NEDMeAz32aaa8-3YqJD:bnfp4nl)* status: 17 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 16 of 16 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38733)* status: Waiting on team(s): sto.

**Pull request merged**
