### PR TITLE
feat: [CVS-9175]: Move AppdDataCollectionTask

### PR DESCRIPTION
**Pull request by AbhijithHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30957)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
___
*[230-model-test/src/main/java/io/harness/testframework/restutils/ConnectorUtils.java, line 20 at r1](https://reviewable.io/reviews/harness/harness-core/30957#-MwhlpL4EMeAnHK3465b:-MwhlpL4EMeAnHK3465c:b-ht3xv6) ([raw file](https://github.com/harness/harness-core/blob/1322587d895945c0ed99a421c6e8d64914ee5f72/230-model-test/src/main/java/io/harness/testframework/restutils/ConnectorUtils.java#L20)):*
> ```Java
> import io.harness.shell.AuthenticationScheme;
> 
> import software.wings.delegatetasks.cv.beans.appd.AppDynamicsConfig;
> ```

to avoid these many file changes because of package, i would recommend that when you move the class keep the same package name. this way we can catch things in review

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionBaselineServiceImpl.java, line 194 at r2](https://reviewable.io/reviews/harness/harness-core/30957#-Mwz9Du5Df1_FrN1sjTs:-Mwz9Du5Df1_FrN1sjTt:bqebhii) ([raw file](https://github.com/harness/harness-core/blob/2db4d0dc245fae905d661bb6836bf0882d782614/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionBaselineServiceImpl.java#L194)):*
> ```Java
>   }
> 
>   private <T extends Base> void updateTtl(String workflowExecutionId, String appId, Class<T> recordClass) {
> ```

why this change?

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/analysis/ContinuousVerificationServiceImpl.java, line 109 at r2](https://reviewable.io/reviews/harness/harness-core/30957#-Mwz9Key1qffbXz0oB49:-Mwz9KezAp9YNlpZxoGS:b-hyr2to) ([raw file](https://github.com/harness/harness-core/blob/82a23bb2b72d0c2ad9526c0028c9de707d6ae6dc/400-rest/src/main/java/software/wings/service/impl/analysis/ContinuousVerificationServiceImpl.java#L109)):*
> ```Java
> import software.wings.delegatetasks.DelegateStateType;
> import software.wings.delegatetasks.cv.DataCollectionException;
> import software.wings.delegatetasks.cv.beans.CustomLogResponseMapper;
> ```

you should keep the same package name for this to avoid changes.

**Comment by raghuAtWings** [comment]
___
*[430-cv-nextgen-commons/src/main/java/io/harness/serializer/kryo/CvNextGenCommonsBeansKryoRegistrar.java, line 124 at r2](https://reviewable.io/reviews/harness/harness-core/30957#-MwzA2eI1V0sz4Zq5_Hg:-MwzA2eI1V0sz4Zq5_Hh:b-sf30b4) ([raw file](https://github.com/harness/harness-core/blob/2db4d0dc245fae905d661bb6836bf0882d782614/430-cv-nextgen-commons/src/main/java/io/harness/serializer/kryo/CvNextGenCommonsBeansKryoRegistrar.java#L124)):*
> ```Java
>     kryo.register(SplunkValidationResponse.SampleLog.class, 9018);
>     kryo.register(DataCollectionConnectorBundle.class, 9019);
>     kryo.register(AppDynamicsApplication.class, 9020);
> ```

please ensure to not change the number associated with the class

**Comment by raghuAtWings** [comment]
___
*[930-delegate-tasks/src/main/java/software/wings/delegatetasks/DelegateStateType.java, line 7 at r2](https://reviewable.io/reviews/harness/harness-core/30957#-MwzAK0x4eYwm7aE0Uez:-MwzAK0x4eYwm7aE0Uf-:b2jossl) ([raw file](https://github.com/harness/harness-core/blob/82a23bb2b72d0c2ad9526c0028c9de707d6ae6dc/930-delegate-tasks/src/main/java/software/wings/delegatetasks/DelegateStateType.java#L7)):*
> ```Java
> 
> 
> public enum DelegateStateType {
> ```

we should add a test to ensure that this is in sync with StateType

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 30 of 280 files at r1, 252 of 253 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30957)* status: 0 of 1 approvals obtained.

**Comment by AbhijithHarness** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/analysis/ContinuousVerificationServiceImpl.java, line 109 at r2](https://reviewable.io/reviews/harness/harness-core/30957#-Mwz9Key1qffbXz0oB49:-Mx40keW7BQudfCzWfI0:b7zlhny) ([raw file](https://github.com/harness/harness-core/blob/82a23bb2b72d0c2ad9526c0028c9de707d6ae6dc/400-rest/src/main/java/software/wings/service/impl/analysis/ContinuousVerificationServiceImpl.java#L109)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

you should keep the same package name for this to avoid changes.
</blockquote></details>

This is a new class.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 42 of 42 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30957)* status: :shipit: complete! ✓

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Comment by AbhijithHarness** [comment]
Screenshot 2022-03-04 at 12 53 30 PM
Screenshot 2022-03-04 at 10 00 56 AM
png">
Screenshot 2022-03-04 at 1 21 45 PM

Screenshot 2022-03-04 at 1 58 21 PM
ps://user-images.githubusercontent.com/86918452/156749948-80d4e6d4-e72b-44d8-b447-d01cc418f849.png">

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 21 of 280 files at r1, 85 of 253 files at r2, 38 of 42 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30957)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[270-verification/src/test/java/io/harness/service/TimeSeriesAnalysisServiceImplTest.java, line 349 at r5](https://reviewable.io/reviews/harness/harness-core/30957#-MxJyx1R0hiM0NYwwF7d:-MxJyx1R0hiM0NYwwF7e:b-thvudd) ([raw file](https://github.com/harness/harness-core/blob/5a2ea5045c7f55e77931cbc0cd946450cddb149d/270-verification/src/test/java/io/harness/service/TimeSeriesAnalysisServiceImplTest.java#L349)):*
> ```Java
>                                                   .name("key")
>                                                   .stateExecutionId(stateExecutionId)
>                                                   // check why appId is null .appId(appId)
> ```

do you have to check this before merging?
___
*[310-ci-manager/src/test/resources/indexes.txt, line 77 at r5](https://reviewable.io/reviews/harness/harness-core/30957#-MxJzHuH3PZSby-z86jm:-MxJzHuH3PZSby-z86jn:b-s2eape) ([raw file](https://github.com/harness/harness-core/blob/5a2ea5045c7f55e77931cbc0cd946450cddb149d/310-ci-manager/src/test/resources/indexes.txt#L77)):*
> ```help
> kmsTransitionEvent2 {"name": "earliestGet_1", "background": true, "expireAfterSeconds": 86400} {"earliestGet": 1}
> kmsTransitionEvent2 {"name": "next4", "background": true} {"topic": 1, "earliestGet": 1}
> newRelicMetricRecords {"name": "accountId_1", "background": true} {"accountId": 1}
> ```

why these new indexes? Indexes in these collections might be risky 
___
*[930-delegate-tasks/src/main/java/software/wings/delegatetasks/DelegateStateType.java, line 13 at r5](https://reviewable.io/reviews/harness/harness-core/30957#-MxK1yFt-V6XWAKyWH94:-MxK1yFt-V6XWAKyWH95:b-kyd3jg) ([raw file](https://github.com/harness/harness-core/blob/5a2ea5045c7f55e77931cbc0cd946450cddb149d/930-delegate-tasks/src/main/java/software/wings/delegatetasks/DelegateStateType.java#L13)):*
> ```Java
> import static com.google.common.base.CaseFormat.UPPER_UNDERSCORE;
> 
> public enum DelegateStateType {
> ```

will introducing this cause kryo serialisation failures if delegate is released independently?
___
*[970-ng-commons/src/main/java/io/harness/serializer/kryo/NGCommonsKryoRegistrar.java, line 92 at r5](https://reviewable.io/reviews/harness/harness-core/30957#-MxK0kkn7P5zxbZvgwCT:-MxK0kkoAFb0AOSP3dnC:bncrjhh) ([raw file](https://github.com/harness/harness-core/blob/5a2ea5045c7f55e77931cbc0cd946450cddb149d/970-ng-commons/src/main/java/io/harness/serializer/kryo/NGCommonsKryoRegistrar.java#L92)):*
> ```Java
>     kryo.register(SchemaCacheKey.class, 970009);
> 
>     kryo.register(AppDynamicsApplication.class, 9020);
> ```

Are we making sure that the numbers are not changing once we move these?

**Review by AbhijithHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30957)* status: 1 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[270-verification/src/test/java/io/harness/service/TimeSeriesAnalysisServiceImplTest.java, line 349 at r5](https://reviewable.io/reviews/harness/harness-core/30957#-MxJyx1R0hiM0NYwwF7d:-MxK3WOYBC9ObrOBK7op:b-scb53z) ([raw file](https://github.com/harness/harness-core/blob/5a2ea5045c7f55e77931cbc0cd946450cddb149d/270-verification/src/test/java/io/harness/service/TimeSeriesAnalysisServiceImplTest.java#L349)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

do you have to check this before merging?
</blockquote></details>

Had checked it, it was because of equals change appId was supposed to be null, forgot to remove it. Removed it.
___
*[310-ci-manager/src/test/resources/indexes.txt, line 77 at r5](https://reviewable.io/reviews/harness/harness-core/30957#-MxJzHuH3PZSby-z86jm:-MxK3jb-6nxjMxq8pEIJ:b-uc292k) ([raw file](https://github.com/harness/harness-core/blob/5a2ea5045c7f55e77931cbc0cd946450cddb149d/310-ci-manager/src/test/resources/indexes.txt#L77)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

why these new indexes? Indexes in these collections might be risky 
</blockquote></details>

Since we moved it to delegateTasks, all morphia registers extending it will have this collection too. It is dirty, but are there any risks?
___
*[400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionBaselineServiceImpl.java, line 194 at r2](https://reviewable.io/reviews/harness/harness-core/30957#-Mwz9Du5Df1_FrN1sjTs:-MxK44c_9uFGRJ1AG83q:by43kuw) ([raw file](https://github.com/harness/harness-core/blob/2db4d0dc245fae905d661bb6836bf0882d782614/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionBaselineServiceImpl.java#L194)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why this change?
</blockquote></details>

changed back
___
*[430-cv-nextgen-commons/src/main/java/io/harness/serializer/kryo/CvNextGenCommonsBeansKryoRegistrar.java, line 124 at r2](https://reviewable.io/reviews/harness/harness-core/30957#-MwzA2eI1V0sz4Zq5_Hg:-MxK46qG2Thw_-GEFi2A:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/2db4d0dc245fae905d661bb6836bf0882d782614/430-cv-nextgen-commons/src/main/java/io/harness/serializer/kryo/CvNextGenCommonsBeansKryoRegistrar.java#L124)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

please ensure to not change the number associated with the class
</blockquote></details>

updated
___
*[930-delegate-tasks/src/main/java/software/wings/delegatetasks/DelegateStateType.java, line 7 at r2](https://reviewable.io/reviews/harness/harness-core/30957#-MwzAK0x4eYwm7aE0Uez:-MxK48j6CLp_Y7MYRuEy:b-7tfmjp) ([raw file](https://github.com/harness/harness-core/blob/82a23bb2b72d0c2ad9526c0028c9de707d6ae6dc/930-delegate-tasks/src/main/java/software/wings/delegatetasks/DelegateStateType.java#L7)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should add a test to ensure that this is in sync with StateType 
</blockquote></details>

added
___
*[930-delegate-tasks/src/main/java/software/wings/delegatetasks/DelegateStateType.java, line 13 at r5](https://reviewable.io/reviews/harness/harness-core/30957#-MxK1yFt-V6XWAKyWH94:-MxK49iV2fXuH3BObDtJ:b-uyqcrk) ([raw file](https://github.com/harness/harness-core/blob/5a2ea5045c7f55e77931cbc0cd946450cddb149d/930-delegate-tasks/src/main/java/software/wings/delegatetasks/DelegateStateType.java#L13)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

will introducing this cause kryo serialisation failures if delegate is released independently?
</blockquote></details>

Yes, it should be causing kyro issue. Will discuss release plan with Raghu too.
___
*[970-ng-commons/src/main/java/io/harness/serializer/kryo/NGCommonsKryoRegistrar.java, line 92 at r5](https://reviewable.io/reviews/harness/harness-core/30957#-MxK0kkn7P5zxbZvgwCT:-MxK4h4m-4itC-xgzdh5:b-4jsn3q) ([raw file](https://github.com/harness/harness-core/blob/5a2ea5045c7f55e77931cbc0cd946450cddb149d/970-ng-commons/src/main/java/io/harness/serializer/kryo/NGCommonsKryoRegistrar.java#L92)):*
> Are we making sure that the numbers are not changing once we move these?
it is same

**Comment by raghuAtWings** [comment]
___
*[310-ci-manager/src/test/resources/indexes.txt, line 77 at r5](https://reviewable.io/reviews/harness/harness-core/30957#-MxJzHuH3PZSby-z86jm:-MxLu5o7BVz36bs8Orti:b-woku6c) ([raw file](https://github.com/harness/harness-core/blob/5a2ea5045c7f55e77931cbc0cd946450cddb149d/310-ci-manager/src/test/resources/indexes.txt#L77)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Since we moved it to delegateTasks, all morphia registers extending it will have this collection too. It is dirty, but are there any risks?
</blockquote></details>

the indexes are created based on the modules a service is dependent on. This is not ideal but we can't wait for this to change for this effort

**Comment by raghuAtWings** [comment]
___
*[930-delegate-tasks/src/main/java/software/wings/delegatetasks/DelegateStateType.java, line 13 at r5](https://reviewable.io/reviews/harness/harness-core/30957#-MxK1yFt-V6XWAKyWH94:-MxLuM3G3-hP-8QZDZnZ:boig8g) ([raw file](https://github.com/harness/harness-core/blob/5a2ea5045c7f55e77931cbc0cd946450cddb149d/930-delegate-tasks/src/main/java/software/wings/delegatetasks/DelegateStateType.java#L13)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Yes, it should be causing kyro issue. Will discuss release plan with Raghu too.
</blockquote></details>

we will release both mgr and delegate at the same time

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30957)* status: 1 change requests. 4. unresolved discussions.

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 1 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30957)* status: :shipit: complete! ✓

**Pull request merged**
