### PR TITLE
techDebt: [DEL-5415]: Move SecretManagerRuntimeParameters out of 930

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary: 
Move SecretManagerRuntimeParameters out of 930-delegate-task
Add corresponding dto class for delegate task usuages 

Test
- Encrypted secret value read in shell script
- End to end k8 deployment

## Checklist
- [ x] I've documented the changes in the PR description.
- [x ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40977)

### CODE REVIEW

**Comment by jennyjames21** [comment]
Same version - secret print
image
K8 deployment
image

**Comment by jennyjames21** [comment]
Older version of delegate : Secret key value read
image
K8 end to end depoyment
image

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40977)* status: :shipit: complete! ✓

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40977)* status: :shipit: complete! ✓

___
*[`890-sm-core/src/main/java/software/wings/beans/SecretManagerRuntimeParameters.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/40977#-NId1MwuBYVnw5Oq3ldp:-NId1MwuBYVnw5Oq3ldq:b-omzfko) ([raw file](https://github.com/harness/harness-core/blob/d4c0f9eab63a1b03220f3d896cd7dd446112182e/890-sm-core/src/main/java/software/wings/beans/SecretManagerRuntimeParameters.java#L67)):*
> ```Java
>         .runtimeParameters(runtimeParameters)
>         .build();
>   }
> ```

Is this really needed? We dont seem to be serializing this over the wire and sending a bunch of strings in runtimeParameters



_Code quote:_
```Java
  public software.wings.beans.dto.SecretManagerRuntimeParameters toDto() {
    return software.wings.beans.dto.SecretManagerRuntimeParameters.builder()
        .accountId(accountId)
        .uuid(uuid)
        .secretManagerId(secretManagerId)
        .executionId(executionId)
        .runtimeParameters(runtimeParameters)
        .build();
  }
```

**Comment by jennyjames21** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/40977)_ status: :shipit: complete! ✓
> 
> _[`890-sm-core/src/main/java/software/wings/beans/SecretManagerRuntimeParameters.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/40977#-NId1MwuBYVnw5Oq3ldp:-NId1MwuBYVnw5Oq3ldq:b-omzfko) ([raw file](https://github.com/harness/harness-core/blob/d4c0f9eab63a1b03220f3d896cd7dd446112182e/890-sm-core/src/main/java/software/wings/beans/SecretManagerRuntimeParameters.java#L67)):_
> 
> > ```java
> >         .runtimeParameters(runtimeParameters)
> >         .build();
> >   }
> > ```
> 
> Is this really needed? We dont seem to be serializing this over the wire and sending a bunch of strings in runtimeParameters
> 
> _Code quote:_
> 
> ```java
>   public software.wings.beans.dto.SecretManagerRuntimeParameters toDto() {
>     return software.wings.beans.dto.SecretManagerRuntimeParameters.builder()
>         .accountId(accountId)
>         .uuid(uuid)
>         .secretManagerId(secretManagerId)
>         .executionId(executionId)
>         .runtimeParameters(runtimeParameters)
>         .build();
>   }
> ```

In SecretManagerImpl

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40977)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by gn-harness — DISMISSED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40977)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40977)* status: :shipit: complete! ✓

**Pull request merged**
