### PR TITLE
feat: [SPG-164]: Remove org.simpleframework.simple-xml dependecy

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes
This PR removes the org.simpleframework.simple-xml dependency. 

For this I had to switch from `com.squareup.retrofit2:converter-simplexml` to `com.squareup.retrofit2:converter-jaxb`, as recommended here: https://github.com/square/retrofit/tree/master/retrofit-converters/simplexml

Regarding the @Transient annotations, I verified that they seem to have no effect at all (the fields marked with @Transient are being store in our DB), so I'm just removing these annotations.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38086)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_NA_** 
 


            
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38086)

**Comment by vcalasansh** [comment]
trigger messagecheck

**Comment by vcalasansh** [comment]
trigger ti2

**Comment by arvind-choudhary-h** [comment]
*[`400-rest/src/main/java/software/wings/beans/AuthToken.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/38086#-NEAW6lpBjH8w3sQMFJE:-NEAW6lpBjH8w3sQMFJF:b-fw700z) ([raw file](https://github.com/harness/harness-core/blob/bd230f85bc073fb67a46b82399cb4b7547518785/400-rest/src/main/java/software/wings/beans/AuthToken.java#L38)):*
> ```Java
> @HarnessEntity(exportable = true)
> public class AuthToken extends Base implements AccountAccess {
>   @XmlTransient private User user;
> ```

can replace with `import org.mongodb.morphia.annotations.Transient;`

**Comment by arvind-choudhary-h** [comment]
*[`400-rest/src/main/java/software/wings/sm/StateExecutionInstance.java` line 180 at r1](https://reviewable.io/reviews/harness/harness-core/38086#-NEAWAKyENjjM9I-X0yg:-NEAWAKyENjjM9I-X0yh:b-o1s74f) ([raw file](https://github.com/harness/harness-core/blob/bd230f85bc073fb67a46b82399cb4b7547518785/400-rest/src/main/java/software/wings/sm/StateExecutionInstance.java#L180)):*
> ```Java
>   private boolean hasInspection;
> 
>   @XmlTransient private String workflowId;
> ```

as mentioned by @yogesh-chauhan

**Comment by arvind-choudhary-h** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/pcf/PcfRollbackState.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/38086#-NEAWCXH9GUTSGWEb3nj:-NEAWCXH9GUTSGWEb3nk:b-o1s74f) ([raw file](https://github.com/harness/harness-core/blob/bd230f85bc073fb67a46b82399cb4b7547518785/400-rest/src/main/java/software/wings/sm/states/pcf/PcfRollbackState.java#L46)):*
> ```Java
> @OwnedBy(CDP)
> public class PcfRollbackState extends PcfDeployState {
>   @Inject @XmlTransient private SweepingOutputService sweepingOutputService;
> ```

as mentioned by @yogesh-chauhan

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38086)* status: 0 of 1 approvals obtained.

**Review by vcalasansh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38086)* status: 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/AuthToken.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/38086#-NEAW6lpBjH8w3sQMFJE:-NEGqRY52kQN3jPOXiYr:bwo0932) ([raw file](https://github.com/harness/harness-core/blob/bd230f85bc073fb67a46b82399cb4b7547518785/400-rest/src/main/java/software/wings/beans/AuthToken.java#L38)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

can replace with `import org.mongodb.morphia.annotations.Transient;`
</blockquote></details>

Thank you for the comments! Would it not be better to remove this @Transient annotation? I'm afraid that replacing it with `import org.mongodb.morphia.annotations.Transient;` would remove the field we are currently storing from DB docs, as explained in Morphia's documentation here: https://morphia.dev/morphia/2.1/annotations.html
___
*[`400-rest/src/main/java/software/wings/sm/StateExecutionInstance.java` line 180 at r1](https://reviewable.io/reviews/harness/harness-core/38086#-NEAWAKyENjjM9I-X0yg:-NEGqmmd4yXw-c5k7d6t:b-ksfkzk) ([raw file](https://github.com/harness/harness-core/blob/bd230f85bc073fb67a46b82399cb4b7547518785/400-rest/src/main/java/software/wings/sm/StateExecutionInstance.java#L180)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

as mentioned by @yogesh-chauhan 
</blockquote></details>

Thank you! Could you please check my previous comment?
___
*[`400-rest/src/main/java/software/wings/sm/states/pcf/PcfRollbackState.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/38086#-NEAWCXH9GUTSGWEb3nj:-NEGqsnDCBLvrrGFKuZu:b-ksfkzk) ([raw file](https://github.com/harness/harness-core/blob/bd230f85bc073fb67a46b82399cb4b7547518785/400-rest/src/main/java/software/wings/sm/states/pcf/PcfRollbackState.java#L46)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

as mentioned by @yogesh-chauhan 
</blockquote></details>

Thank you! Could you please check my previous comment?

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 14 of 17 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38086)* status: 3. unresolved discussions.

**Review by shashank-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38086)* status: Some of the checks are too old. 2 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/AuthToken.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/38086#-NEAW6lpBjH8w3sQMFJE:-NEZlmH11JB1l25aGKy1:bsjgk3) ([raw file](https://github.com/harness/harness-core/blob/bd230f85bc073fb67a46b82399cb4b7547518785/400-rest/src/main/java/software/wings/beans/AuthToken.java#L38)):*
<details><summary><i>Previously, vcalasansh (Vinícius Calasans) wrote…</i></summary><blockquote>

Thank you for the comments! Would it not be better to remove this @Transient annotation? I'm afraid that replacing it with `import org.mongodb.morphia.annotations.Transient;` would remove the field we are currently storing from DB docs, as explained in Morphia's documentation here: https://morphia.dev/morphia/2.1/annotations.html
</blockquote></details>

We do not store this field as of now in DB.
You can add 
"import org.mongodb.morphia.annotations.Transient" to User user.

We need to test login works or not to provide sign off.
If you have a PR env please share that so we can test login.

**Review by vcalasansh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38086)* status: 4 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/AuthToken.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/38086#-NEAW6lpBjH8w3sQMFJE:-NEkMuXh0ZkhrqLr7itO:b-rcj6u7) ([raw file](https://github.com/harness/harness-core/blob/bd230f85bc073fb67a46b82399cb4b7547518785/400-rest/src/main/java/software/wings/beans/AuthToken.java#L38)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

We do not store this field as of now in DB.
You can add 
"import org.mongodb.morphia.annotations.Transient" to User user.

We need to test login works or not to provide sign off.
If you have a PR env please share that so we can test login. 
</blockquote></details>

Thank you for reviewing! I updated the PR with your suggestion and also created a PR env for it here: https://spg.pr.harness.io/spg-164/ . Could you please take a look again?

**Review by shashank-harness — DISMISSED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38086)* status: 3 file(s) to review. 3. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38086)* status: 3. unresolved discussions.

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38086)* status: :shipit: complete! ✓

**Review by lasdox — APPROVED** [review]
> Reviewed 11 of 17 files at r1, 1 of 3 files at r2, 2 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38086)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 11 of 17 files at r1, 1 of 3 files at r2, 2 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38086)* status: :shipit: complete! ✓

**Pull request merged**
