### PR TITLE
feat: [SRM-11388]: Added persistence logic for monitored service during template verify step

### PR DESCRIPTION
**Pull request by arpit-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36816)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Vulnerability 1 Vulnerabilities 
 
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36816)

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36816)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/cdng/services/impl/TemplateVerifyStepMonitoredServiceResolutionServiceImpl.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/36816#-NANaGzN3Fm9UDbusMUO:-NANaGzN3Fm9UDbusMUP:bolu7do) ([raw file](https://github.com/harness/harness-core/blob/b1515fb94256b9c0bf187997af68f151f66a29fe/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/services/impl/TemplateVerifyStepMonitoredServiceResolutionServiceImpl.java#L125)):*
> ```Java
>         && CollectionUtils.isNotEmpty(monitoredServiceDTO.getSources().getHealthSources())) {
>       persistTemplateMonitoredService(serviceEnvironmentParams, monitoredServiceDTO);
>       populateCvConfigAndHealSourceData(serviceEnvironmentParams, monitoredServiceDTO.getSources().getHealthSources(),
> ```

getResolvedCVConfigInfo() shouldnt persist monitoredService. No one will expect it when going through the code. Move the persistence to CVNGStep only. 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/cdng/services/impl/TemplateVerifyStepMonitoredServiceResolutionServiceImpl.java` line 147 at r1](https://reviewable.io/reviews/harness/harness-core/36816#-NANZiR_6DE52wa3U8p6:-NANZiR_6DE52wa3U8p7:b-9zrbls) ([raw file](https://github.com/harness/harness-core/blob/b1515fb94256b9c0bf187997af68f151f66a29fe/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/services/impl/TemplateVerifyStepMonitoredServiceResolutionServiceImpl.java#L147)):*
> ```Java
>       }
>     } catch (Exception e) {
>       log.error(e.getMessage() + " Failed to persist monitored service");
> ```

make it 
`log.error("Failed to persist monitored service: " + monitoredServiceIdentifier, e)`. This should automatically print stacktrace.

**Comment by arpit-harness** [comment]
trigger compile

**Comment by arpit-harness** [comment]
trigger checkstyle

**Comment by arpit-harness** [comment]
trigger checkstyle

**Comment by arpit-harness** [comment]
tigger ti0, ti3, ti4

**Comment by arpit-harness** [comment]
trigger ti0, ti3

**Comment by arpit-harness** [comment]
trigger messagecheck

**Comment by arpit-harness** [comment]
trigger featurename

**Comment by arpit-harness** [comment]
trigger featurenamecheck

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36816)* status: :shipit: complete! ✓

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36816)* status: :shipit: complete! ✓

**Pull request merged**
