### PR TITLE
feat: [CDS-34768]: do not followRedirect for http step FF

### PR DESCRIPTION
**Pull request by hingerabhinav**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31844)

### CODE REVIEW

**Review by prabu-kr — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31844)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
I dont think this will solve issue while test connection

**Comment by hingerabhinav** [comment]
@abhinav-harness Yes this is for http step only

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31844)* status: Some of the checks are too old.

**Pull request closed without merging**
