### PR TITLE
[fix]: [CDS-69594]: Use list of node execution IDs in identity node for Pipeline Rollback

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48035)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/48035#-NVmIY6m73hmatqapy3N:-NVmIY6m73hmatqapy3O:b-3n4job) ([raw file](https://github.com/harness/harness-core/blob/abb2e3a03d2f36fdb80affc85ef6b347a9d55a4d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java#L42)):*
> ```Java
>   NodeExecution get(String nodeExecutionId);
> 
>   List<NodeExecution> get(List<String> nodeExecutionIds);
> ```

use iterator and projections here.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48035)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/48035#-NVmIY6m73hmatqapy3N:-NW1Djx822kkyUKsYrAf:b-hcw03m) ([raw file](https://github.com/harness/harness-core/blob/abb2e3a03d2f36fdb80affc85ef6b347a9d55a4d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java#L42)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

use iterator and projections here.
</blockquote></details>

use iterator, but not projections because almost all fields of node execution are used

**Comment by namanvermah** [comment]
trigger uts

**Comment by namanvermah** [comment]
trigger uts

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48035)* status: 6 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by namanvermah** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48035)* status: 7 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48035)* status: 4 file(s) to review.

**Comment by namanvermah** [comment]
trigger reviw

**Comment by namanvermah** [comment]
trigger review

**Pull request merged**
