### PR TITLE
feat: [DEL-6024]: api to override delegate image

### PR DESCRIPTION
**Pull request by AnupamIO**
Exposing an API to override delegate image tag.

testing:
Tested in local, values are getting populated in db. 

Screenshot 2023-03-05 at 9 17 24 PM

Screenshot 2023-03-05 at 9 28 07 PM

Note: API will work with NG API key only, this api cannot be used from CG.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44719)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44719)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/VersionOverrideResource.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/44719#-NPqzuTW4WJ_MRDgjdhJ:-NPqzuTW4WJ_MRDgjdhK:bvlhwd3) ([raw file](https://github.com/harness/harness-core/blob/8fdac5d476ef56d3c1e021b60b44a5fc538386da/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/VersionOverrideResource.java#L30)):*
> ```Java
> @Slf4j
> @Produces("application/json")
> @NextGenManagerAuth
> ```

What is this auth type? We should check who should be allowed to invoke this API. I think we would probably need `ApiKeyAuthorized` (e.g. to call it from command line with appropriate API key) and some kind of admin user permissions. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/VersionOverrideResource.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/44719#-NPr-L3wAtF6BdDDTnfG:-NPr-L3wAtF6BdDDTnfH:b-bctx4g) ([raw file](https://github.com/harness/harness-core/blob/8fdac5d476ef56d3c1e021b60b44a5fc538386da/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/VersionOverrideResource.java#L47)):*
> ```Java
>     CGRestUtils.getResponse(delegateNgManagerCgManagerClient.overrideDelegateImage(
>         accountId, delegateTag, validTillNextRelease, validForDays));
>     return new RestResponse<>();
> ```

Maybe would be good to give some kind of feedback to the user I think this would return null true/false which is not much understandable. Check what other similar APIs do. 
___
*[`400-rest/src/main/java/io/harness/delegate/resources/DelegateVersionOverrideInternalResource.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/44719#-NPqtQdW6BSMHn6kR0_2:-NPqtQdW6BSMHn6kR0_3:brgms1x) ([raw file](https://github.com/harness/harness-core/blob/8fdac5d476ef56d3c1e021b60b44a5fc538386da/400-rest/src/main/java/io/harness/delegate/resources/DelegateVersionOverrideInternalResource.java#L57)):*
> ```Java
>   @ExceptionMetered
>   @InternalApi
>   public RestResponse<Void> downloadDockerDelegate(@Context HttpServletRequest request,
> ```

Change the name

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44719)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/VersionOverrideResource.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/44719#-NPqzuTW4WJ_MRDgjdhJ:-NQB8jgH9eLAS5AxMOD-:b6r3kuf) ([raw file](https://github.com/harness/harness-core/blob/8fdac5d476ef56d3c1e021b60b44a5fc538386da/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/VersionOverrideResource.java#L30)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

What is this auth type? We should check who should be allowed to invoke this API. I think we would probably need `ApiKeyAuthorized` (e.g. to call it from command line with appropriate API key) and some kind of admin user permissions. 
</blockquote></details>

@NextGenManagerAuth will cover api-key auth but I think we won't be able to identify user doing curl to update image. Anyone with access to api-key can hit the url, i feel.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44719)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/resources/DelegateVersionOverrideInternalResource.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/44719#-NPqtQdW6BSMHn6kR0_2:-NQOmwbjDhQcoCoeeBud:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8fdac5d476ef56d3c1e021b60b44a5fc538386da/400-rest/src/main/java/io/harness/delegate/resources/DelegateVersionOverrideInternalResource.java#L57)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Change the name
</blockquote></details>

Done.

**Review by mdmilic — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44719)* status: :shipit: complete! ✓

**Pull request merged**
