### PR TITLE
[feat]: [CDS-84606]: Webhook event processing to support org and project level webhooks

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added code to process the webhook events at org and project level. Have tested out the following:
1. For project level webhook, receiving and processing an event of project level entity 
2. For project level webhook, receiving and processing an event of org level entity
3. For org level webhook, receiving and processing an event of project level entity

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55643)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/GitXCacheUpdateHelperRequestDTO.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-Njgm9ByDE6b5Xs8NFQj:-Njgm9ByDE6b5Xs8NFQk:b-i66dvn) ([raw file](https://github.com/harness/harness-core/blob/bc5e95cb319ff0e832900b69776aff8d2e24b84d/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/GitXCacheUpdateHelperRequestDTO.java#L33)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public class GitXCacheUpdateHelperRequestDTO {
>   String accountIdentifier;
> ```

Will this break any existing client?
What if client is passing accountIdentifier?

**Comment by sahilhindwani-harness** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 86 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-NjgmU_60VCEtQkx1_Yr:-NjgmU_60VCEtQkx1_Ys:b45sxld) ([raw file](https://github.com/harness/harness-core/blob/bc5e95cb319ff0e832900b69776aff8d2e24b84d/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L86)):*
> ```Java
>                  .unique(true)
>                  .field(GitXWebhookEventKeys.accountIdentifier)
>                  .field(GitXWebhookEventKeys.orgIdentifier)
> ```

What is our end goal over here?
Unique eventIdentifier across account?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55643)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-Njgno2-EVcG5HNWrILO:-Njgno2-EVcG5HNWrILP:b-puswu0) ([raw file](https://github.com/harness/harness-core/blob/730c71e4541aae54673e86a944aec8f4dc9b0b2c/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L91)):*
> ```Java
>         if (isEmpty(processingFilePathResponseDTO.getProcessingFilePaths())) {
>           log.info(String.format(
>               "The webhook event %s will be SKIPPED as the webhook is disabled or the folder paths don't match.",
> ```

lets change the error message here as well accordingly

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55643)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 133 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-NjgoYlW2DOQjQuL8Ot6:-NjgoYlXB5RHQNwWVWUE:bqojvgc) ([raw file](https://github.com/harness/harness-core/blob/730c71e4541aae54673e86a944aec8f4dc9b0b2c/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L133)):*
> ```Java
>   }
> 
>   private ProcessingFilePathResponseDTO getMatchingFiles(
> ```

nit: getFilesToProcess method name?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55643)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 137 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-Njgod4REaaIwRnfxL9e:-Njgod4REaaIwRnfxL9f:b-qxeusq) ([raw file](https://github.com/harness/harness-core/blob/730c71e4541aae54673e86a944aec8f4dc9b0b2c/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L137)):*
> ```Java
>     ProcessingFilePathResponseDTO processingFilePathResponseDTO = null;
>     for (GitXWebhook gitXWebhook : gitXWebhookList) {
>       ScmConnector scmConnector = getScmConnector(gitXWebhook);
> ```

we should have a try catch on overall thing. May be we get error while fetching scm connector itself, then also we should try to fetch the next scm connector

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55643)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 142 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-NjgolpaAVBTIToT2BmB:-NjgolpaAVBTIToT2BmC:b-c00rfk) ([raw file](https://github.com/harness/harness-core/blob/730c71e4541aae54673e86a944aec8f4dc9b0b2c/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L142)):*
> ```Java
>         modifiedFilePaths = parsePayloadAndGetModifiedFilePaths(gitXWebhook, gitXWebhookEvent, scmConnector);
>       } catch (Exception exception) {
>         log.info(String.format(
> ```

.error()

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55643)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 147 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-Njgot4O7kBeYcUhXsZc:-Njgot4O7kBeYcUhXsZd:b-gvzgge) ([raw file](https://github.com/harness/harness-core/blob/730c71e4541aae54673e86a944aec8f4dc9b0b2c/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L147)):*
> ```Java
>       }
>       log.info(String.format("Successfully fetched the file paths with GitXWebhook %s", gitXWebhook.getIdentifier()));
>       List<String> processingFilePaths = getMatchingFilePaths(modifiedFilePaths, gitXWebhook);
> ```

can't we move this complete logic in the try block itself? instead of using "continue"

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55643)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 143 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-Njgoy9y4RyE7fJSDA21:-Njgoy9y4RyE7fJSDA22:bwkauhp) ([raw file](https://github.com/harness/harness-core/blob/730c71e4541aae54673e86a944aec8f4dc9b0b2c/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L143)):*
> ```Java
>       } catch (Exception exception) {
>         log.info(String.format(
>             "Failed to fetch the modifiedFilePaths data from gitXWebhook identifier %s", gitXWebhook.getIdentifier()));
> ```

also lets mention that we will try with next scm connector now

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55643)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 206 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-NjgpYpg1VPgQdjNgP7i:-NjgpYpg1VPgQdjNgP7j:btq1f71) ([raw file](https://github.com/harness/harness-core/blob/730c71e4541aae54673e86a944aec8f4dc9b0b2c/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L206)):*
> ```Java
>   }
> 
>   public ScmConnector getScmConnector(GitXWebhook gitXWebhook) {
> ```

why is this public?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55643)* status: 14 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/GitXCacheUpdateHelperRequestDTO.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-Njgm9ByDE6b5Xs8NFQj:-Njgok0K68hYJhIHHycm:b72f5t2) ([raw file](https://github.com/harness/harness-core/blob/bc5e95cb319ff0e832900b69776aff8d2e24b84d/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/GitXCacheUpdateHelperRequestDTO.java#L33)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Will this break any existing client?
What if client is passing accountIdentifier?
</blockquote></details>

this is an internal DTO, for the existing clients passing just accountId is handled
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 86 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-NjgmU_60VCEtQkx1_Yr:-NjgovX80oXPDKxCFNGX:bmykpzx) ([raw file](https://github.com/harness/harness-core/blob/bc5e95cb319ff0e832900b69776aff8d2e24b84d/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L86)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

What is our end goal over here?
Unique eventIdentifier across account?
</blockquote></details>

webhook event cant be tied to a scope, hence removed the org and project
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-Njgno2-EVcG5HNWrILO:-NjgsWssDjVCoEDgplAC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/730c71e4541aae54673e86a944aec8f4dc9b0b2c/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L91)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets change the error message here as well accordingly
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 133 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-NjgoYlW2DOQjQuL8Ot6:-NjgpJFhDjeNFL6z8eDx:b-n9tkhd) ([raw file](https://github.com/harness/harness-core/blob/730c71e4541aae54673e86a944aec8f4dc9b0b2c/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L133)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

nit: getFilesToProcess method name?
</blockquote></details>

changed
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 137 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-Njgod4REaaIwRnfxL9e:-NjgsL4h2mgJZPjqChim:bhg904r) ([raw file](https://github.com/harness/harness-core/blob/730c71e4541aae54673e86a944aec8f4dc9b0b2c/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L137)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should have a try catch on overall thing. May be we get error while fetching scm connector itself, then also we should try to fetch the next scm connector
</blockquote></details>

changed it accordingly
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 142 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-NjgolpaAVBTIToT2BmB:-NjgreRW1eUfE4Judsoe:b-fvx5ps) ([raw file](https://github.com/harness/harness-core/blob/730c71e4541aae54673e86a944aec8f4dc9b0b2c/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L142)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

.error()
</blockquote></details>

not really an error right? we anyways have the backup, thats why made it info but changing it to error
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 143 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-Njgoy9y4RyE7fJSDA21:-Njgs0eO9Pi2nTjNMArB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/730c71e4541aae54673e86a944aec8f4dc9b0b2c/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L143)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

also lets mention that we will try with next scm connector now
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 147 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-Njgot4O7kBeYcUhXsZc:-NjgsBfSCxJsKE26FHZq:b-n9tkhd) ([raw file](https://github.com/harness/harness-core/blob/730c71e4541aae54673e86a944aec8f4dc9b0b2c/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L147)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can't we move this complete logic in the try block itself? instead of using "continue"
</blockquote></details>

changed
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 206 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-NjgpYpg1VPgQdjNgP7i:-NjgrtTE-nVQxB8wUF5M:b-jexn67) ([raw file](https://github.com/harness/harness-core/blob/730c71e4541aae54673e86a944aec8f4dc9b0b2c/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L206)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is this public?
</blockquote></details>

changed to private

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 142 at r1](https://reviewable.io/reviews/harness/harness-core/55643#-NjgolpaAVBTIToT2BmB:-NjiRAJS8D6Rta-nNioL:b8vj57b) ([raw file](https://github.com/harness/harness-core/blob/730c71e4541aae54673e86a944aec8f4dc9b0b2c/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L142)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

not really an error right? we anyways have the backup, thats why made it info but changing it to error
</blockquote></details>

It should be error coz otherwise we won't be able to track it. Yes, we have fallbacks but in itself its an error only.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55643)* status: 14 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 149 at r4](https://reviewable.io/reviews/harness/harness-core/55643#-NjiRMxd2J-GrFWwlTUz:-NjiRMxd2J-GrFWwlTV-:brc049k) ([raw file](https://github.com/harness/harness-core/blob/d1be4601ca17e0d7cdd26e2438e4cfcb1d515ddc/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L149)):*
> ```Java
>             .build();
>       } catch (Exception exception) {
>         log.error(String.format(
> ```

why are we not logging the exception here?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55643)* status: 14 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java` line 149 at r4](https://reviewable.io/reviews/harness/harness-core/55643#-NjiRMxd2J-GrFWwlTUz:-NjkGM0_E9MTtGgRkPmv:b-697c4k) ([raw file](https://github.com/harness/harness-core/blob/d1be4601ca17e0d7cdd26e2438e4cfcb1d515ddc/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java#L149)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why are we not logging the exception here?
</blockquote></details>

added it,

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55643)* status: 14 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by sandeshsalunkhegh — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger uts, review

**Pull request merged**
