### PR TITLE
feat: [PL-30215]: added the missing view permissions

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
Harness Support User had the following permissions missing:
core_variable_view
core_setting_view
Added the above two necessary permissions in this PR
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41092)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Comment by tiwaritejas** [comment]
trigger messagecheck, ft2

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Comment by tiwaritejas** [comment]
trigger ft2

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Comment by tiwaritejas** [comment]
trigger messagecheck, ft2

**Review by reetika04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41092)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/41092#-NIXX8VRBBlf4MxKok1U:-NIXX8VSEcBYysrd8-oB:b9cgpnb) ([raw file](https://github.com/harness/harness-core/blob/d372befcdf2edd760427d81e2c44a8eec0d3e99a/access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml#L55)):*
> ```YAML
>       - ccm_loadBalancer_view
>       - ccm_folder_view
>       - core_variable_view
> ```

Update the version.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41092)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/41092#-NIXX8VRBBlf4MxKok1U:-NIXXsnV9h4E0ZvIpDbr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d372befcdf2edd760427d81e2c44a8eec0d3e99a/access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml#L55)):*
<details><summary><i>Previously, reetika04 (Reetika) wrote…</i></summary><blockquote>

Update the version.
</blockquote></details>

Done.

**Review by reetika04 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41092)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41092)* status: :shipit: complete! ✓

**Pull request merged**
