### PR TITLE
feat: [Pl-25475]: Support of secrets for UserGroup notifications

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Backend code changes to support secrets for userGroups

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34314)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger ft1

**Comment by adivishy1** [comment]
trigger ft2

**Comment by sahilhindwani-harness** [comment]
*[`platform-service/modules/notification-service/BUILD.bazel` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/34314#-N4bOmN33DjeqlcgDlot:-N4bOmN49Aw2XV_APsFH:bivxn42) ([raw file](https://github.com/harness/harness-core/blob/0429d9ecff19db89dac6b277c17bf6429e83c4cf/platform-service/modules/notification-service/BUILD.bazel#L19)):*
> ```Starlark
>     deps = [
>         "//:lombok",
>         "//870-orchestration:module",
> ```

why do we need this dependency?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34314)* status: 1 change requests. 0 of 1 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`platform-service/modules/notification-service/BUILD.bazel` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/34314#-N4bOmN33DjeqlcgDlot:-N4bQP_Y1U5nwssB9FRr:b-6vp9q4) ([raw file](https://github.com/harness/harness-core/blob/0429d9ecff19db89dac6b277c17bf6429e83c4cf/platform-service/modules/notification-service/BUILD.bazel#L19)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

why do we need this dependency?
</blockquote></details>

We should not depend on 870-orchestration. Please remove this dependency.

**Comment by adivishy1** [comment]
trigger checkstyle

**Comment by adivishy1** [comment]
> > Reviewed 9 of 9 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/34314)_ status: 1 change requests. 0 of 1 approvals obtained.

Review changes have been incorporated

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34314)* status: :shipit: complete! ✓

**Pull request merged**
