### PR TITLE
[feat]: [PL-28848]: Removing User assigned viewer role assignments across all scopes.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes

- Removing User assigned viewer role assignments across all scopes.
- This will help to customers manage role assignments using Default User Groups instead of individual user.
- We had introduced Default User Groups at all scopes with AccountViewer(Role) - All Account Level resources(Resource Group) role binding as deletable and there are customers who have removed the role binding from Default User Group.
- Also for accounts having ACCOUNT_BASIC_ROLE_ONLY FF ON, we had not assigned AccountViewer - All Account Level resources role binding to Account Scope user group.
- So for both of this scenarios we wont be removing Account Viewer role binding from the users.
- To avoid having one time  bloating up OpLog and direct load on Access Control service for processing delete events I have added delay in migration. For Prod-2 having max no of role assignments ~85k of all clusters it will add delay of roughly ~33 mins.
In Prod-2, removing viewer role assignments is processed by Access Control Debezium Change Consumers in roughly ~30 ms, it will roughly take ~1 hour to process all change events.

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42066)

### CODE REVIEW

**Review by ankit-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42066)* status: :shipit: complete! ✓

**Comment by Jimit09Gandhi** [comment]
trigger ti1

**Review by reetika04 — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42066)* status: :shipit: complete! ✓

**Comment by Jimit09Gandhi** [comment]
trigger messagecheck

**Pull request merged**
