### PR TITLE
[feat]: [CDS-76106]: Removed limit of 1000 branches to unblock customer.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes
Issue: list-branches is a hidden API which is called when we view execution history of remote pipeline. As earlier we didn't involve pagination and set a max limit of 1000 for unique branches in response. Now the customer has more than 1000 branches for a single pipeline and hence list-branches api is sending 500 Https code in response.

We don’t have this behaviour documented as of now. It was presumed earlier that customer would not be having a pipeline in more than 1000 branches.

Change: Removed limit of 1000 unique branches.

Testing: A hardcoded branch list of size more than 1000 branches was made and returned to UI. It was handled  by UI.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51404)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger uts

**Comment by mohitg0795** [comment]
```Now the customer has more than 1000 branches for a single pipeline and hence list-branches api is sending 500 in response.```

If limit is 1000, then why does it send 500 in the response?

**Comment by senjucanon2** [comment]
trigger uts

**Review by hextechpal — DISMISSED** [review]

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51404)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryReadHelper.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/51404#-NbIlqtfBOiNDfZ1Q4gI:-NbIlqtfBOiNDfZ1Q4gJ:b-puzr2s) ([raw file](https://github.com/harness/harness-core/blob/b4dd7587fee9031da8e4708d2aa1664a829073cf/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryReadHelper.java#L53)):*
> ```Java
>     validatePipelineExecutionSummaryStreamQuery(query);
>     return secondaryMongoTemplate.stream(query, PipelineExecutionSummaryEntity.class);
>   }
> ```

this method kinda already exists - fetchExecutionSummaryEntityFromSecondary, use that send your query only
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustom.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/51404#-NbIluJ64waCoRsdwVgR:-NbIluJ64waCoRsdwVgS:bpp6stj) ([raw file](https://github.com/harness/harness-core/blob/b4dd7587fee9031da8e4708d2aa1664a829073cf/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustom.java#L43)):*
> ```Java
>   String fetchRootRetryExecutionId(String planExecutionId);
> 
>   CloseableIterator<PipelineExecutionSummaryEntity> findListOfUniqueBranches(Criteria criteria);
> ```

not needed
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 192 at r3](https://reviewable.io/reviews/harness/harness-core/51404#-NbIlwdG5CYR7zMUEtnN:-NbIlwdG5CYR7zMUEtnO:bjvg8f1) ([raw file](https://github.com/harness/harness-core/blob/b4dd7587fee9031da8e4708d2aa1664a829073cf/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L192)):*
> ```Java
>   public CloseableIterator<PipelineExecutionSummaryEntity> findListOfUniqueBranches(Criteria criteria) {
>     Query query = new Query(criteria);
>     query.fields().include(PipelineExecutionSummaryEntity.PlanExecutionSummaryKeys.entityGitDetailsBranch);
> ```

make it - PlanExecutionSummaryKeys.entityGitDetailsBranch



_Code quote:_
```Java
PipelineExecutionSummaryEntity.PlanExecutionSummaryKeys
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 271 at r3](https://reviewable.io/reviews/harness/harness-core/51404#-NbIm1rY96oT4q-swobZ:-NbIm1rY96oT4q-swob_:b-1i3se) ([raw file](https://github.com/harness/harness-core/blob/b4dd7587fee9031da8e4708d2aa1664a829073cf/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L271)):*
> ```Java
> 
>   @Override
>   public PMSPipelineListBranchesResponse getListOfBranches(Criteria criteria) {
> ```

add UT for this

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51404)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryReadHelper.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/51404#-NbIlqtfBOiNDfZ1Q4gI:-NbJ5dM_-8NKKaHMXY5K:b9youi5) ([raw file](https://github.com/harness/harness-core/blob/b4dd7587fee9031da8e4708d2aa1664a829073cf/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryReadHelper.java#L53)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this method kinda already exists - fetchExecutionSummaryEntityFromSecondary, use that send your query only
</blockquote></details>

Used the already existing method.
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustom.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/51404#-NbIluJ64waCoRsdwVgR:-NbJ5gyTEfYtQxpWRdns:bss4a2b) ([raw file](https://github.com/harness/harness-core/blob/b4dd7587fee9031da8e4708d2aa1664a829073cf/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustom.java#L43)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Removed.
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 192 at r3](https://reviewable.io/reviews/harness/harness-core/51404#-NbIlwdG5CYR7zMUEtnN:-NbJ5u3TEOk0j5nRciMf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b4dd7587fee9031da8e4708d2aa1664a829073cf/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L192)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

make it - PlanExecutionSummaryKeys.entityGitDetailsBranch
</blockquote></details>

Done.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51404)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 271 at r3](https://reviewable.io/reviews/harness/harness-core/51404#-NbIm1rY96oT4q-swobZ:-NbJTwpv0kvetKb7GvDE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b4dd7587fee9031da8e4708d2aa1664a829073cf/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L271)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add UT for this
</blockquote></details>

Done.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r4, 2 of 4 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51404)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
