### PR TITLE
fix: [DEL-4674]: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 15017"

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
Reverts harness/harness-core#36477

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36493)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36493)

**Comment by VikasMaddukuriHarness** [comment]
trigger messagecheck

**Comment by VikasMaddukuriHarness** [comment]
trigger MessageMetadata-message_metadata

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 114 of 114 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36493)* status: :shipit: complete! ✓

**Comment by VikasMaddukuriHarness** [comment]
trigger codebasehash

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 114 of 114 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36493)* status: :shipit: complete! ✓

**Pull request merged**
