### PR TITLE
feat: [CDS-78066]: improve coverage pipeline-service : IdentityNodeExecutionStrategyHelper.java

### PR DESCRIPTION
**Pull request by ayushitiwari024**
## Describe your changes

92%- coverage

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56703)

### CODE REVIEW

**Comment by ayushitiwari024** [comment]
trigger smartchecks

**Comment by ayushitiwari024** [comment]
trigger uts

**Comment by rohitk-h** [comment]
@ayushitiwari024 can you please update the improvement in coverage numbers

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56703)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/execution/strategy/identity/IdentityNodeExecutionStrategyHelperTest.java` line 209 at r2](https://reviewable.io/reviews/harness/harness-core/56703#-Nm4ZZ6X6GfKNyfRPrl8:-Nm4ZZ6X6GfKNyfRPrl9:bsdl3cn) ([raw file](https://github.com/harness/harness-core/blob/b096062daf3d43acd54474907f6ea19c763fa51d/pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/execution/strategy/identity/IdentityNodeExecutionStrategyHelperTest.java#L209)):*
> ```Java
>         OrchestrationTestHelper.createCloseableIterator(nodeExecutionList.iterator());
>     NodeExecution result = identityNodeExecutionStrategyHelper.getCorrectNodeExecution(executionsIterator, currLevels);
>     assertThat(result.getAmbiance().getLevelsCount()).isEqualTo(2);
> ```

Can we assert the contents inside ambiance as well?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/execution/strategy/identity/IdentityNodeExecutionStrategyHelperTest.java` line 274 at r2](https://reviewable.io/reviews/harness/harness-core/56703#-Nm4ZhxWEqA4krLWsX5A:-Nm4ZhxWEqA4krLWsX5B:bpbi0d3) ([raw file](https://github.com/harness/harness-core/blob/b096062daf3d43acd54474907f6ea19c763fa51d/pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/execution/strategy/identity/IdentityNodeExecutionStrategyHelperTest.java#L274)):*
> ```Java
>         identityNodeExecutionStrategyHelper.createNodeExecution(ambiance, node, notifyId, parentId, previousId);
> 
>     assertThat(actual.getNodeId()).isEqualTo(originalExecution.getNodeId());
> ```

Can we assert for few more fields?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56703)* status: 1 change requests. 1 of 2 approvals obtained.

**Review by ayushitiwari024 — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56703#-:-NmAbstF-6p08rBf_BHg:bb6un1j)* status: 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/execution/strategy/identity/IdentityNodeExecutionStrategyHelperTest.java` line 209 at r2](https://reviewable.io/reviews/harness/harness-core/56703#-Nm4ZZ6X6GfKNyfRPrl8:-NmAdNOl7FpFXgL-bRlv:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/b096062daf3d43acd54474907f6ea19c763fa51d/pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/execution/strategy/identity/IdentityNodeExecutionStrategyHelperTest.java#L209)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we assert the contents inside ambiance as well?
</blockquote></details>

Done
___
*[`pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/execution/strategy/identity/IdentityNodeExecutionStrategyHelperTest.java` line 274 at r2](https://reviewable.io/reviews/harness/harness-core/56703#-Nm4ZhxWEqA4krLWsX5A:-NmAbuIg4m7jqzc2nvZH:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/b096062daf3d43acd54474907f6ea19c763fa51d/pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/execution/strategy/identity/IdentityNodeExecutionStrategyHelperTest.java#L274)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we assert for few more fields?
</blockquote></details>

Done

**Review by sandeshsalunkhegh — APPROVED** [review]

**Comment by ayushitiwari024** [comment]
trigger messagecheck

**Comment by ayushitiwari024** [comment]
trigger uts

**Comment by ayushitiwari024** [comment]
trigger ut4

**Comment by ayushitiwari024** [comment]
trigger ut4

**Comment by ayushitiwari024** [comment]
trigger ut4

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56703)* status: Some of the checks are too old. 1 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by sandeshsalunkhegh — APPROVED** [review]
LGTM

**Comment by sandeshsalunkhegh** [comment]
trigger review

**Pull request merged**
