### PR TITLE
feat: [PL-24919]: Added error handling for list branch API

### PR DESCRIPTION
**Pull request by bhavya181**
Added Error Handling of list Branch V2 API

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32815)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListBranchesScmApiErrorHandler.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/32815#-N1ImZAb2iPPHpm0pmkk:-N1ImZAb2iPPHpm0pmkl:bfk80ln) ([raw file](https://github.com/harness/harness-core/blob/fc2e3120aad1660a40ddbd92e952a7c99bbbae8f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListBranchesScmApiErrorHandler.java#L23)):*
> ```Java
>             SCMExceptionExplanations.LIST_BRANCH_WITH_INVALID_CRED, new ScmUnauthorizedException(errorMessage));
>       case 404:
>         throw NestedExceptionUtils.hintWithExplanationException(SCMExceptionHints.BITBUCKET_REPO_NOT_FOUND,
> ```

can we make it generic only? We don't need to mention bitbucket or github in the error message. We can simply mention the issue and may be that can be generically used across all places as well if it matches.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubListBranchesScmApiErrorHandler.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/32815#-N1ImoIm0INNMgq6zjXX:-N1ImoIm0INNMgq6zjXY:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/fc2e3120aad1660a40ddbd92e952a7c99bbbae8f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubListBranchesScmApiErrorHandler.java#L23)):*
> ```Java
>             SCMExceptionExplanations.LIST_BRANCH_WITH_INVALID_CRED, new ScmUnauthorizedException(errorMessage));
>       case 404:
>         throw NestedExceptionUtils.hintWithExplanationException(SCMExceptionHints.GITHUB_REPO_NOT_FOUND,
> ```

same

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32815)* status: 26 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListBranchesScmApiErrorHandler.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/32815#-N1ImZAb2iPPHpm0pmkk:-N1J0RyX-SsqzoDFeEpo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fc2e3120aad1660a40ddbd92e952a7c99bbbae8f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListBranchesScmApiErrorHandler.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we make it generic only? We don't need to mention bitbucket or github in the error message. We can simply mention the issue and may be that can be generically used across all places as well if it matches.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubListBranchesScmApiErrorHandler.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/32815#-N1ImoIm0INNMgq6zjXX:-N1J0Si77O7XEVZk7m7D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fc2e3120aad1660a40ddbd92e952a7c99bbbae8f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubListBranchesScmApiErrorHandler.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 16 of 23 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32815#-:-N1J21Y0DHy_2jheAhgV:bnfp4nl)* status: 26 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListBranchesScmApiErrorHandler.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/32815#-N1J2Ah74xwTg_-6uld3:-N1J2Ah81bFLgogIB6ax:be2e6v5) ([raw file](https://github.com/harness/harness-core/blob/f07c1be78b52abc755974db098080780b1bb433c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListBranchesScmApiErrorHandler.java#L34)):*
> ```Java
>             SCMExceptionExplanations.LIST_BRANCH_WHEN_REPO_NOT_EXIST, new ScmResourceNotFoundException(errorMessage));
>       default:
>         log.error(String.format("Error while listing bitbucket branches: [%s: %s]", statusCode, errorMessage));
> ```

Bitbucket is mentioned
___
*[`952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/32815#-N1J2NLW9aN7qHVKooFv:-N1J2NLW9aN7qHVKooFw:b1ynd14) ([raw file](https://github.com/harness/harness-core/blob/f07c1be78b52abc755974db098080780b1bb433c/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java#L21)):*
> ```Java
>   public static final String LIST_REPO_WITH_INVALID_CRED =
>       "We couldn't list repositories as the credentials provided in connector are invalid or have expired.";
>   public static final String LIST_BRANCH_WITH_INVALID_CRED =
> ```

Don't use the word "We". 

Just say Couldn't list branches. Credentials provided in connector are invalid or have expired.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32815)* status: 28 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListBranchesScmApiErrorHandler.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/32815#-N1J2Ah74xwTg_-6uld3:-N1JAy7D3HmlhwlyLkcZ:b-3rqwvl) ([raw file](https://github.com/harness/harness-core/blob/f07c1be78b52abc755974db098080780b1bb433c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListBranchesScmApiErrorHandler.java#L34)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Bitbucket is mentioned
</blockquote></details>

Are you asking to remove bitbucket? so, we will be showing provider type in every error, just for making errorMessage generic, I have put %s to take input of ProviderType for each message, this way it will become generic also and we can provide repoProvider also
___
*[`952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/32815#-N1J2NLW9aN7qHVKooFv:-N1JAsuY1ILhbKZjRmxQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f07c1be78b52abc755974db098080780b1bb433c/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java#L21)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Don't use the word "We". 

Just say Couldn't list branches. Credentials provided in connector are invalid or have expired.
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListBranchesScmApiErrorHandler.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/32815#-N1J2Ah74xwTg_-6uld3:-N1JBm6PEBOOIqlnTM7e:b-pve70c) ([raw file](https://github.com/harness/harness-core/blob/f07c1be78b52abc755974db098080780b1bb433c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListBranchesScmApiErrorHandler.java#L34)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Are you asking to remove bitbucket? so, we will be showing provider type in every error, just for making errorMessage generic, I have put %s to take input of ProviderType for each message, this way it will become generic also and we can provide repoProvider also
</blockquote></details>

@ankit-harness this is a log only, so should be fine. I think you misunderstood it here.

But @bhavya181 as mentioned above, we can make it generic and there's no need to put bitbucket/github or anything. It just adds unnecessary liability across error handling to put in repo provider everywhere otherwise it would break consistency.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListBranchesScmApiErrorHandler.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/32815#-N1J2Ah74xwTg_-6uld3:-N1NeGB42ObYdqTWmOH9:b-82kidk) ([raw file](https://github.com/harness/harness-core/blob/f07c1be78b52abc755974db098080780b1bb433c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListBranchesScmApiErrorHandler.java#L34)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@ankit-harness this is a log only, so should be fine. I think you misunderstood it here.

But @bhavya181 as mentioned above, we can make it generic and there's no need to put bitbucket/github or anything. It just adds unnecessary liability across error handling to put in repo provider everywhere otherwise it would break consistency.
</blockquote></details>

As discussed, we will be moving errors to individual repo provider package itself for easy management. This will be taken up as separate PR.

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> Reviewed 15 of 23 files at r1, 10 of 10 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32815#-:-N1Ne_XHC445j-r_Garw:bnfp4nl)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32815#-:-N1O20f16c5-qG6TCKEQ:bnfp4nl)* status: 20 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListBranchesScmApiErrorHandler.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/32815#-N1J2Ah74xwTg_-6uld3:-N1O22Js3Gh4iWsFFU88:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f07c1be78b52abc755974db098080780b1bb433c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListBranchesScmApiErrorHandler.java#L34)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

done

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 17 of 18 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32815#-:-N1O9YZw5S4wFrDD5CTG:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32815#-:-N1OQ3QW5OZQFAhGMjZi:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
