### PR TITLE
feat: [DEL-5855]: Add abort task support for queued task and update hqsclient

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:

- Updated with queue service authentication change by directly using new HQSClientService class.
- Removed factory class and updated the config
- Functionality to Abort queued task 

Test
- Queueing/Dequeuing with queue service verification in PR env
- Regular PR sanity with FF disabled
- Abort queued task verification
- Unit test

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45387)

### CODE REVIEW

**Comment by xingchi-jin** [comment]
can you add description and tests ?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 2081 at r5](https://reviewable.io/reviews/harness/harness-core/45387#-NRsrMRe3YX73NMPFn9y:-NRsrMRg-vBIdQcJ-76H:b-9z3jf6) ([raw file](https://github.com/harness/harness-core/blob/1c0830b52cf2c78b238039a3f8baf96b188b8015/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L2081)):*
> ```Java
>         persistence.save(delegateTask, delegateTaskMigrationHelper.isMigrationEnabledForTask(delegateTask.getUuid()));
>     // no need to broadcast if list is empty, empty for the case when task is queued in queue service
>     if (isEmpty(delegateTask.getBroadcastToDelegateIds())) {
> ```

i thought we will not save the task when its queued. why this change then?



_Code quote:_
```Java
delegateCache.addToAbortedTaskList(accountId, Sets.newHashSet(delegateTaskId));
```

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 10 of 15 files at r1, 3 of 4 files at r2, 1 of 3 files at r3, 2 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45387)* status: 0 of 1 approvals obtained. Waiting on team(s): del-team.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 2081 at r5](https://reviewable.io/reviews/harness/harness-core/45387#-NRsrMRe3YX73NMPFn9y:-NRssg_Q3UsCP62o0wkw:b-1qyj4t) ([raw file](https://github.com/harness/harness-core/blob/1c0830b52cf2c78b238039a3f8baf96b188b8015/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L2081)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

i thought we will not save the task when its queued. why this change then?
</blockquote></details>

Because our broadcasting(first attempt) currently doesn't stop if the delegate task is not saved or doesn't depend on value from DB, goes on the same thread

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45387)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
Sanity
image
image

**Comment by jennyjames21** [comment]
trigger ut0

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 10 of 15 files at r1, 3 of 4 files at r2, 1 of 3 files at r3, 2 of 4 files at r4, 2 of 3 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45387)* status: :shipit: complete! ✓

**Comment by arvind-choudhary-h** [comment]
Reviewed migrator side of code.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45387)* status: :shipit: complete! ✓

**Pull request merged**
