### PR TITLE
[feat]: [PL-20218]: Add the support to filter user group by application name

### PR DESCRIPTION
**Pull request by DeepakPatankar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34406)

### CODE REVIEW

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34406)* status: 23 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 282 at r1](https://reviewable.io/reviews/harness/harness-core/34406#-N59dzW78uaozPgWewHB:-N59dzW78uaozPgWewHC:b-93k26o) ([raw file](https://github.com/harness/harness-core/blob/624dba85409775c9b02847a95bba77f659ff3290/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L282)):*
> ```Java
>     SearchFilter applicationSearchFilter = SearchFilter.builder()
>                                                .fieldName(Application.ApplicationKeys.name)
>                                                .op(Operator.CONTAINS)
> ```

Starts with
___
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 290 at r1](https://reviewable.io/reviews/harness/harness-core/34406#-N59eBDP2pKGpVGhTxu5:-N59eBDP2pKGpVGhTxu6:bubacdg) ([raw file](https://github.com/harness/harness-core/blob/624dba85409775c9b02847a95bba77f659ff3290/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L290)):*
> ```Java
>             .addFilter(applicationSearchFilter)
>             .build();
>     PageResponse<Application> applicationList = appService.list(applicationPageRequest);
> ```

app can be more than 1000 
___
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 308 at r1](https://reviewable.io/reviews/harness/harness-core/34406#-N59g5vL5Hhm_gYR156q:-N59g5vL5Hhm_gYR156r:b-vxoc79) ([raw file](https://github.com/harness/harness-core/blob/624dba85409775c9b02847a95bba77f659ff3290/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L308)):*
> ```Java
>                                                               .fieldValues(new Object[] {AppFilter.FilterType.SELECTED})
>                                                               .fieldName(UserGroupKeys.appIds)
>                                                               .op(Operator.IN)
> ```

unindexed query

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34406)* status: 23 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 282 at r1](https://reviewable.io/reviews/harness/harness-core/34406#-N59dzW78uaozPgWewHB:-N5Ac0_cETWksAArh3HX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/624dba85409775c9b02847a95bba77f659ff3290/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L282)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

Starts with
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 290 at r1](https://reviewable.io/reviews/harness/harness-core/34406#-N59eBDP2pKGpVGhTxu5:-N5Ac4pzAbILrpNfBCsr:bvl80ro) ([raw file](https://github.com/harness/harness-core/blob/624dba85409775c9b02847a95bba77f659ff3290/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L290)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

app can be more than 1000 
</blockquote></details>

The user is trying to search the application with the searchTerm. If the searchTerm is not good and we have 1000 applications, then the user will try again with a better searchTerm

Adding more than 1000 applications in our IN query might not be a good solution
___
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 308 at r1](https://reviewable.io/reviews/harness/harness-core/34406#-N59g5vL5Hhm_gYR156q:-N5Ad0jq6Rbc6OY_Pq2P:bpb5d5j) ([raw file](https://github.com/harness/harness-core/blob/624dba85409775c9b02847a95bba77f659ff3290/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L308)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

unindexed query
</blockquote></details>

Is it a good idea to add the index just for this use case ?

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34406)* status: 23 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 308 at r1](https://reviewable.io/reviews/harness/harness-core/34406#-N59g5vL5Hhm_gYR156q:-N5EX24NBvYRZlwHqnRF:bu3d90t) ([raw file](https://github.com/harness/harness-core/blob/624dba85409775c9b02847a95bba77f659ff3290/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L308)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Is it a good idea to add the index just for this use case ?
</blockquote></details>

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34406)* status: 23 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 290 at r1](https://reviewable.io/reviews/harness/harness-core/34406#-N59eBDP2pKGpVGhTxu5:-N5Erq3iBgXTUXPQd3o-:bgl8v86) ([raw file](https://github.com/harness/harness-core/blob/624dba85409775c9b02847a95bba77f659ff3290/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L290)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

The user is trying to search the application with the searchTerm. If the searchTerm is not good and we have 1000 applications, then the user will try again with a better searchTerm

Adding more than 1000 applications in our IN query might not be a good solution
</blockquote></details>

can we limit to even lesser?
___
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 308 at r1](https://reviewable.io/reviews/harness/harness-core/34406#-N59g5vL5Hhm_gYR156q:-N5EyKyCAIE4fbL2IecD:bg4tqz2) ([raw file](https://github.com/harness/harness-core/blob/624dba85409775c9b02847a95bba77f659ff3290/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L308)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>


</blockquote></details>

yes we should imo

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34406)* status: 23 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 290 at r1](https://reviewable.io/reviews/harness/harness-core/34406#-N59eBDP2pKGpVGhTxu5:-N5FaLBoEANrXoGUa6eL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/624dba85409775c9b02847a95bba77f659ff3290/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L290)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

can we limit to even lesser?
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 308 at r1](https://reviewable.io/reviews/harness/harness-core/34406#-N59g5vL5Hhm_gYR156q:-N5Fau9cC2k2ZbCYueUu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/624dba85409775c9b02847a95bba77f659ff3290/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L308)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

yes we should imo 
</blockquote></details>

Done.

**Review by ujjawal-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34406#-:-N5JRpgk-Okow3YFlrwv:bnfp4nl)* status: 25 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 5 of 23 files at r1, 4 of 6 files at r3, 6 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34406)* status: 25 file(s) to review. 1 of 2 approvals obtained.

**Review by Y0709 — APPROVED** [review]
> Reviewed 14 of 23 files at r1, 4 of 6 files at r3, 6 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34406)* status: :shipit: complete! ✓

**Pull request merged**
