### PR TITLE
[fix]: [cds-41432]: Fixed setting lastUpdatedAt flag after deleting t…

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
…emplates

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38196)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38196)

**Comment by bharatgoelharness** [comment]
trigger publish-delegate

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38196)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 469 at r1](https://reviewable.io/reviews/harness/harness-core/38196#-NDRKXut4yKFa_j0mAF3:-NDRKXut4yKFa_j0mAF4:bdu7q93) ([raw file](https://github.com/harness/harness-core/blob/835b4cdadad940e6ab2b1363f46cfe4ca9657c9c/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L469)):*
> ```Java
>   }
> 
>   private boolean deleteMultipleTemplatesHelper(String accountId, String orgIdentifier, String projectIdentifier,
> ```

let's add UT as well for this. You can use the same example given in ticket and verify with that.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38196)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 469 at r1](https://reviewable.io/reviews/harness/harness-core/38196#-NDRKXut4yKFa_j0mAF3:-NDRtEnx03w3RL_yTGQu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/835b4cdadad940e6ab2b1363f46cfe4ca9657c9c/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L469)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

let's add UT as well for this. You can use the same example given in ticket and verify with that.
</blockquote></details>

Done.

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38196)* status: :shipit: complete! ✓

**Review by inderschera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38196)* status: :shipit: complete! ✓

___
*[`840-template-service/src/test/java/io/harness/template/services/NGTemplateServiceImplTest.java` line 428 at r2](https://reviewable.io/reviews/harness/harness-core/38196#-NDWY3J6DZJEFAdV4ean:-NDWY3J6DZJEFAdV4eao:b4phzam) ([raw file](https://github.com/harness/harness-core/blob/d3af47d611230ca43cf1d61b78694883fbb99e55/840-template-service/src/test/java/io/harness/template/services/NGTemplateServiceImplTest.java#L428)):*
> ```Java
>     try {
>       when(request.execute()).thenReturn(Response.success(ResponseDTO.newResponse(false)));
>     } catch (IOException ex) {
> ```

nit: you can throw exception in method signature if required.

**Pull request merged**
