### PR TITLE
[feat]: [CDS-67805]: Compute reference entities in create and update flows

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Area of Code changes:
As part of this ticket, we have added code to update the reference entity for the default branches[based on the default branch cache] in the create and update flows.

Testing:
1. Remote pipeline creation [both default and non default branches]
2. Remote pipeline updation [both default and non default branches]
3. Remote pipeline fetch [both default and non default branches]
4. Inline pipeline creation 
5. Inline pipeline updation
6. Inline pipeline fetch

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51550)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitDefaultBranchCacheHelper.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/51550#-NbxgvVs5xPPck3B5fTP:-NbxgvVs5xPPck3B5fTQ:b-zgmjvi) ([raw file](https://github.com/harness/harness-core/blob/f4f4796ed12e039a8f5d1a24cf839d71cecb7bd5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitDefaultBranchCacheHelper.java#L107)):*
> ```Java
> 
>   public boolean isGitDefaultBranch(
>       String accountIdentifier, ScmConnector scmConnector, String repoName, String branch) {
> ```

what does "branch" represent here? Which branch is it?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 1058 at r1](https://reviewable.io/reviews/harness/harness-core/51550#-NbxhLET92UK-mkyLDz0:-NbxhLET92UK-mkyLDz1:bfyop7m) ([raw file](https://github.com/harness/harness-core/blob/f4f4796ed12e039a8f5d1a24cf839d71cecb7bd5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L1058)):*
> ```Java
> 
>   private void computeReferencesIfApplicable(PipelineEntity pipelineEntity) {
>     if (PipelineGitXHelper.shouldPublishSetupUsages(pipelineEntity.getStoreType())) {
> ```

aren't we publishing references for all INLINE cases by default?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51550)* status: Some of the checks are too old. 6 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitDefaultBranchCacheHelper.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/51550#-NbxgvVs5xPPck3B5fTP:-NbxrWpl3WAS8H8n6aAH:b4micq8) ([raw file](https://github.com/harness/harness-core/blob/f4f4796ed12e039a8f5d1a24cf839d71cecb7bd5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitDefaultBranchCacheHelper.java#L107)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what does "branch" represent here? Which branch is it?
</blockquote></details>

changed it to requestBranch
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 1058 at r1](https://reviewable.io/reviews/harness/harness-core/51550#-NbxhLET92UK-mkyLDz0:-NbxrcPq9693QxBIwI1Q:bux02je) ([raw file](https://github.com/harness/harness-core/blob/f4f4796ed12e039a8f5d1a24cf839d71cecb7bd5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L1058)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

aren't we publishing references for all INLINE cases by default?
</blockquote></details>

yes for inline cases, we are not creating an async task, its happens when are calling the updatePipelineInfo flow
just to keep it the setup usages same for remote, have added it here similar to the get flow

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 1058 at r1](https://reviewable.io/reviews/harness/harness-core/51550#-NbxhLET92UK-mkyLDz0:-Nby0SPF6CclTxG5ogtZ:b-85tabr) ([raw file](https://github.com/harness/harness-core/blob/f4f4796ed12e039a8f5d1a24cf839d71cecb7bd5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L1058)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

yes for inline cases, we are not creating an async task, its happens when are calling the updatePipelineInfo flow
just to keep it the setup usages same for remote, have added it here similar to the get flow
</blockquote></details>

My concern here is that it appears that we don't do setup usage creation at all for INLINE cases. Not sure if thats right assessment or not. Will DM for more details.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51550)* status: 6 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 1058 at r1](https://reviewable.io/reviews/harness/harness-core/51550#-NbxhLET92UK-mkyLDz0:-Nby9SXO4-_J2UKvYTxb:b-2g8zp3) ([raw file](https://github.com/harness/harness-core/blob/f4f4796ed12e039a8f5d1a24cf839d71cecb7bd5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L1058)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

My concern here is that it appears that we don't do setup usage creation at all for INLINE cases. Not sure if thats right assessment or not. Will DM for more details.
</blockquote></details>

As discussed offline, we are updating the for inline and remote pipeline but from this point of code, we are updating only for remote, hence changed the name for better clarity

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51550)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
