### PR TITLE
feat: [CDS-44756]: Remove dependency between NG Manager and Pipeline

### PR DESCRIPTION
**Pull request by ivan-83**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38740)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38740)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/test/resources/recaster/alias/alias.txt` line 531 at r1](https://reviewable.io/reviews/harness/harness-core/38740#-NEElb0KB2Kcu2a52wXW:-NEElb0KB2Kcu2a52wXX:b-x6vpxx) ([raw file](https://github.com/harness/harness-core/blob/3866af195125089330bf3b63d5f1ed80f2d18e38/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L531)):*
> ```help
> io.harness.cdng.ssh.output.HostsOutput
> io.harness.cdng.ssh.output.SshInfraDelegateConfigOutput
> io.harness.cdng.ssh.output.WinRmInfraDelegateConfigOutput
> ```

dont need it
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/output/HostsOutput.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/38740#-NEElNuL5deg7ZH7DFgF:-NEElNuL5deg7ZH7DFgG:bni43z8) ([raw file](https://github.com/harness/harness-core/blob/3866af195125089330bf3b63d5f1ed80f2d18e38/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/output/HostsOutput.java#L23)):*
> ```Java
> @Builder
> @OwnedBy(CDP)
> @RecasterAlias("io.harness.cdng.ssh.output.HostsOutput")
> ```

we cant change recaster alias for existing output/outcome, this was introduced so any file movement doesn't affect existing output / outcome to be mapped



_Code quote:_
```Java
cdng.ssh.output.HostsOutpu
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/output/SshInfraDelegateConfigOutput.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/38740#-NEElXq31rFyvR_G0rEC:-NEElXq31rFyvR_G0rED:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/3866af195125089330bf3b63d5f1ed80f2d18e38/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/output/SshInfraDelegateConfigOutput.java#L23)):*
> ```Java
> @Builder
> @OwnedBy(CDP)
> @RecasterAlias("io.harness.cdng.ssh.output.SshInfraDelegateConfigOutput")
> ```

same as above
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/output/WinRmInfraDelegateConfigOutput.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/38740#-NEElZ4r62HUEXYFeksz:-NEElZ4r62HUEXYFekt-:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/3866af195125089330bf3b63d5f1ed80f2d18e38/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/output/WinRmInfraDelegateConfigOutput.java#L23)):*
> ```Java
> @Builder
> @OwnedBy(CDP)
> @RecasterAlias("io.harness.cdng.ssh.output.WinRmInfraDelegateConfigOutput")
> ```

same as above

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38740)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/test/resources/recaster/alias/alias.txt` line 531 at r1](https://reviewable.io/reviews/harness/harness-core/38740#-NEElb0KB2Kcu2a52wXW:-NEGWltEB4FgtA_ycV_B:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3866af195125089330bf3b63d5f1ed80f2d18e38/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L531)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dont need it
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/output/HostsOutput.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/38740#-NEElNuL5deg7ZH7DFgF:-NEGWiEP3SPunhNhEEuU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3866af195125089330bf3b63d5f1ed80f2d18e38/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/output/HostsOutput.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we cant change recaster alias for existing output/outcome, this was introduced so any file movement doesn't affect existing output / outcome to be mapped
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/output/SshInfraDelegateConfigOutput.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/38740#-NEElXq31rFyvR_G0rEC:-NEGWjQi1YkuX-R4wVuH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3866af195125089330bf3b63d5f1ed80f2d18e38/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/output/SshInfraDelegateConfigOutput.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/output/WinRmInfraDelegateConfigOutput.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/38740#-NEElZ4r62HUEXYFeksz:-NEGWk-r1SDWTkwngBw3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3866af195125089330bf3b63d5f1ed80f2d18e38/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/output/WinRmInfraDelegateConfigOutput.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 9 of 15 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38740)* status: 1 change requests. 4. unresolved discussions.

**Comment by ivan-83** [comment]
trigger checkstyle

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 6 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38740)* status: :shipit: complete! ✓

**Pull request merged**
