### PR TITLE
[fix]: [PL-25247]: Upgrades swagger v3 dependencies to fix inconsistent open…

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
…api generation issue.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33651)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger ti1

**Comment by ashishsanodia-harness** [comment]
trigger ti1

**Comment by ashishsanodia-harness** [comment]
trigger ti1

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33651)* status: 14 file(s) to review. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/yaml/CustomPropertyUtils.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/33651#-N3KSVge-3lAKzMX7cMP:-N3KSVge-3lAKzMX7cMQ:b-4s2ve4) ([raw file](https://github.com/harness/harness-core/blob/ef4f63242debaf3465340b9ce369ef70a2a8e78c/400-rest/src/main/java/software/wings/yaml/CustomPropertyUtils.java#L24)):*
> ```Java
> import org.yaml.snakeyaml.introspector.BeanAccess;
> import org.yaml.snakeyaml.introspector.Property;
> import org.yaml.snakeyaml.introspector.PropertyUtils;
> ```

are these classes the same and just moved from older package to newer package ?

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 11 of 14 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33651)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/33651)

**Pull request closed without merging**
