### PR TITLE
feat: [CDS-47361]: Add environment group information to CDNGModuleInfoProvider

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
- feat: [CDS-47361]: Add environment group information to CDNGModuleInfoProvider

## Describe your changes
Add environment group ref and name to CDNG Module Stage Info and environment group ref to CDNG Pipeline Module Info 
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-47875]: https://harness.atlassian.net/browse/CDS-47875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-47361]: https://harness.atlassian.net/browse/CDS-47361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41248)

### CODE REVIEW

**Review by rohitk-h — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41248)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41248)* status: :shipit: complete! ✓

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java` line 193 at r1](https://reviewable.io/reviews/harness/harness-core/41248#-NIu-E6_CS3_Z7VH4VJ_:-NIu-E6aCgl6UGUzIiC3:b-sd824n) ([raw file](https://github.com/harness/harness-core/blob/b2e6ba761081d30f320f6c57f62b3aa9243d19db/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java#L193)):*
> ```Java
>             .infrastructureIdentifier(infrastructureOutcome.getInfraIdentifier())
>             .infrastructureName(infrastructureOutcome.getInfraName());
>         if (EmptyPredicate.isNotEmpty(infrastructureOutcome.getEnvironment().getEnvGroupRef())) {
> ```

just to ask, is infrastructure.getEnvironment() is always non null?
Seeing this assumption every instance in class.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41248)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41248)* status: 1. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java` line 193 at r1](https://reviewable.io/reviews/harness/harness-core/41248#-NIu-E6_CS3_Z7VH4VJ_:-NIwGKovAoVkCL1mqmAE:bfarv8j) ([raw file](https://github.com/harness/harness-core/blob/b2e6ba761081d30f320f6c57f62b3aa9243d19db/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java#L193)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

just to ask, is infrastructure.getEnvironment() is always non null?
Seeing this assumption every instance in class.
</blockquote></details>

Yes, right now this assumption is valid. InfrastructureOutcome without environment does not make much sense 
However, I feel the class should have been annotated with @NotNull

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41248)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41248)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
