### PR TITLE
[fix]: [CCM-7516]: Cost categories filter on unallocated costs shown as user input

### PR DESCRIPTION
**Pull request by sdsingh07**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32855)

### CODE REVIEW

**Review by svmav — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32855)* status: :shipit: complete! ✓

___
*[`450-ce-views/src/main/java/io/harness/ccm/views/service/impl/ViewsBillingServiceImpl.java` line 1295 at r1](https://reviewable.io/reviews/harness/harness-core/32855#-N1NkQV329NXJnLQS6VK:-N1NkQV329NXJnLQS6VL:bk0g072) ([raw file](https://github.com/harness/harness-core/blob/a2aa69a7dbec3c8da8fea4ffd945304ab5024193/450-ce-views/src/main/java/io/harness/ccm/views/service/impl/ViewsBillingServiceImpl.java#L1295)):*
> ```Java
>       return value.toString();
>     }
>     return null;
> ```

Make sure that this change doesn't have any side effects

**Review by sdsingh07 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32855)* status: 1. unresolved discussions. 

___
*[`450-ce-views/src/main/java/io/harness/ccm/views/service/impl/ViewsBillingServiceImpl.java` line 1295 at r1](https://reviewable.io/reviews/harness/harness-core/32855#-N1NkQV329NXJnLQS6VK:-N1NktR68r6MOWrVoG26:b-x1rg2e) ([raw file](https://github.com/harness/harness-core/blob/a2aa69a7dbec3c8da8fea4ffd945304ab5024193/450-ce-views/src/main/java/io/harness/ccm/views/service/impl/ViewsBillingServiceImpl.java#L1295)):*
<details><summary><i>Previously, svmav (Shubhanshu Verma) wrote…</i></summary><blockquote>

Make sure that this change doesn't have any side effects
</blockquote></details>

This function we are using only at one place and null value is handled there.
Earlier, we are returning `Others` and including string value in the result, only if the value is not `Others`.
But now in case of BM, the unallocated cost label may has `Others` value and we do not want to omit it.

**Review by Rohit-Kaliki — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32855#-:-N1bEF402y2I4At2epRF:bnfp4nl)* status: 1. unresolved discussions.

**Review by svmav — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32855)* status: Some of the checks are too old.

**Pull request merged**
