### PR TITLE
fix: [CDS-36687]: Fixing license calculation for CD NG

### PR DESCRIPTION
**Pull request by shubham-in10se**
## Checklist
- [-] I've documented the changes in the PR description.
- [-] I've tested this change either in PR or local environment.
- [-] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33566)

### CODE REVIEW

**Review by abosii-harness — APPROVED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33566)* status: :shipit: complete! ✓

**Comment by shubham-in10se** [comment]
trigger messagecheck

**Comment by shubham-in10se** [comment]
The change is regarding changing the calculation logic for CD License Usage for NG. It involves some code refactoring/movement to lower modules.

For the approval of PRs we would like people to provide us answer to the following questions:

Is it new task type? (If yes, no need to answer 2 then)
No

Did you add a new class which is added in kryo serialization
N/A

if yes then do not use that class in any of the delegate task payload till it makes to delegate release
N/A

Did you make changes to the code in a backward-compatible manner?
Yes

will the new version of the delegate receive old version task and process?
N/A

If new version of the manager receives response for the old task will it be able to handle it successfully?
N/A

Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager
N/A

If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay
N/A

if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay
N/A

Did you remove an enum → this is not backward compatible yet (tracked by [DEL-3648: Move to name based kryo serializer for delegate/manager communicationIN PROGRESS](https://harness.atlassian.net/browse/DEL-3648) )
No enum was removed or added

Did you add an enum → make sure that the enum constant is added in the end of the already defined constants. If you don’t do this then you will have issues where wrong enum type will be deserialized in delegate side.
No enum was removed or added

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33566)* status: :shipit: complete! ✓

**Pull request merged**
