### PR TITLE
[fix]: [PL-29157]: Upgrade protobuf-java / protobuf-javalite to 3.21.7 for all impacted images

### PR DESCRIPTION
**Pull request by raghuAtWings**
## Describe your changes
Upgrading the following libraries 
1. "com.google.api.grpc:proto-google-cloud-secretmanager-v1:1.2.8" -> 2.5.0
2.     "io.grpc:grpc-protobuf-lite:1.48.0" -> 1.50.1
3.     "io.grpc:grpc-protobuf:1.48.0" -> 1.50.1
4.     "io.grpc:grpc-services:1.48.0" -> 1.50.1
5.     "io.grpc:grpc-stub:1.48.0" -> 1.50.1

Tests done
1. end to end k8 deployment in cg
2. end to end shell script deployment in ng
3. secrets creation/deletion from cg and ng

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39312)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
trigger ti0

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39312)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by jennyjames21 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39312)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by jennyjames21 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39312#-:-NFkOGM52xYJmchYc1Zz:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by raghuAtWings** [comment]
trigger ti0

**Comment by raghuAtWings** [comment]
trigger ti1

**Comment by raghuAtWings** [comment]
trigger ti2

**Comment by raghuAtWings** [comment]
trigger ti3

**Comment by raghuAtWings** [comment]
trigger ti4

**Comment by raghuAtWings** [comment]
trigger ti0

**Comment by raghuAtWings** [comment]
trigger ti1

**Comment by raghuAtWings** [comment]
trigger ti2

**Comment by raghuAtWings** [comment]
trigger ti3

**Comment by raghuAtWings** [comment]
trigger ti4

**Pull request merged**
