### PR TITLE
[feat]: [CDS-80901]: Add custom stage as referring entity for the environment it uses

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes

This PR contains two major changes: 

1. Add custom stage as referring entity for the environment and infrastructure it uses (via the getChildrenToWalk Method)
2. Fix empty log issues for manifest and config files steps when run as children of custom stage environment step

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53794)

### CODE REVIEW

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger uts

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53794)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 113 at r2](https://reviewable.io/reviews/harness/harness-core/53794#-Ng2wUnB8w7ow51G_JSJ:-Ng2wUnB8w7ow51G_JSK:bcukfql) ([raw file](https://github.com/harness/harness-core/blob/970a519e2c9545d9d38f00483f4a9b7ebb28f908/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L113)):*
> ```Java
> 
>       final NGLogCallback environmentStepLogCallback =
>           serviceStepsHelper.getServiceLogCallback(ambiance, true, ENVIRONMENT_STEP_COMMAND_UNIT);
> ```

It would be nice if we could have separate methods for the CustumStage environment instead of getServiceLogCallback.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 117 at r2](https://reviewable.io/reviews/harness/harness-core/53794#-Ng2wN24AR_-dZoBGdsj:-Ng2wN24AR_-dZoBGdsk:b555432) ([raw file](https://github.com/harness/harness-core/blob/970a519e2c9545d9d38f00483f4a9b7ebb28f908/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L117)):*
> ```Java
>           serviceStepsHelper.getServiceLogCallback(ambiance, true, OVERRIDES_COMMAND_UNIT);
> 
>       environmentStepLogCallback.saveExecutionLog("abcd");
> ```

Pls, remove this line.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 210 at r2](https://reviewable.io/reviews/harness/harness-core/53794#-Ng2wqgW-9O5tXBLpkIH:-Ng2wqgX35w4NlAhTSkP:bf26u1) ([raw file](https://github.com/harness/harness-core/blob/970a519e2c9545d9d38f00483f4a9b7ebb28f908/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L210)):*
> ```Java
> 
>     final NGLogCallback logCallback =
>         serviceStepsHelper.getServiceLogCallback(ambiance, false, ENVIRONMENT_STEP_COMMAND_UNIT);
> ```

The same as above.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java` line 414 at r2](https://reviewable.io/reviews/harness/harness-core/53794#-Ng2zFz62mE9RWvsm3HP:-Ng2zFz62mE9RWvsm3HQ:b-3erw6h) ([raw file](https://github.com/harness/harness-core/blob/970a519e2c9545d9d38f00483f4a9b7ebb28f908/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java#L414)):*
> ```Java
>       @NonNull Map<String, List<ManifestConfigWrapper>> finalSvcManifestsMap) {
>     List<ManifestConfigWrapper> manifests = new ArrayList<>();
>     if (isEmpty(finalSvcManifestsMap)) {
> ```

Before your changes, if finalScvManifestMap is empty we were calling the overrideHelmRepoConnectorIfHelmChartExists method, pls check that we are backward compatible. 
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/constants/ServiceStepConstants.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/53794#-Ng2xfk424O4h9mKtOf-:-Ng2xfk424O4h9mKtOf0:bv6iza6) ([raw file](https://github.com/harness/harness-core/blob/970a519e2c9545d9d38f00483f4a9b7ebb28f908/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/constants/ServiceStepConstants.java#L50)):*
> ```Java
>   public static final String SERVICE_STEP_COMMAND_UNIT = "Service Step";
>   public static final String OVERRIDES_COMMAND_UNIT = "Service Overrides";
>   public static final String ENVIRONMENT_STEP_COMMAND_UNIT = "Environment Step";
> ```

This shouldn't be part of ServiceStepConstants. Move this to Custom stage constants. 
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/53794#-Ng2ztHm8DL3qae6BsT1:-Ng2ztHn7IUJBMV2rCWs:bjwlz5x) ([raw file](https://github.com/harness/harness-core/blob/970a519e2c9545d9d38f00483f4a9b7ebb28f908/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java#L87)):*
> ```Java
>   @Inject private SdkGraphVisualizationDataService sdkGraphVisualizationDataService;
> 
>   StepType customStageEnvStep = StepType.newBuilder()
> ```

This shouldn't be part of ServiceStepHelper. Pls, create the new class CustomStage helper or CustomStageEnviromentHelper ....
and move methods related to the custom stage there including getLogCallbackForManifestOrConfigFilesStep
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/53794#-Ng3-ZFY2Mpq0dkdz_7n:-Ng3-ZFY2Mpq0dkdz_7o:b9sxuew) ([raw file](https://github.com/harness/harness-core/blob/970a519e2c9545d9d38f00483f4a9b7ebb28f908/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java#L175)):*
> ```Java
>       Level level = levels.get(i);
>       if (customStageEnvStep.equals(level.getStepType())) {
>         commandUnit = ENVIRONMENT_STEP_COMMAND_UNIT;
> ```

How is this working, can we get ride of the service step in the custom stage env step?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 113 at r2](https://reviewable.io/reviews/harness/harness-core/53794#-Ng2wUnB8w7ow51G_JSJ:-Ng3XQ1k7WrHrpNvZ-yU:b2ngthx) ([raw file](https://github.com/harness/harness-core/blob/970a519e2c9545d9d38f00483f4a9b7ebb28f908/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L113)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

It would be nice if we could have separate methods for the CustumStage environment instead of getServiceLogCallback.
</blockquote></details>

+1

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java` line 168 at r2](https://reviewable.io/reviews/harness/harness-core/53794#-Ng3XWhf4ma7z2q5z6HT:-Ng3XWhf4ma7z2q5z6HU:b-43ku5l) ([raw file](https://github.com/harness/harness-core/blob/970a519e2c9545d9d38f00483f4a9b7ebb28f908/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java#L168)):*
> ```Java
>   public AsyncExecutableResponse executeAsync(Ambiance ambiance, EmptyStepParameters stepParameters,
>       StepInputPackage inputPackage, PassThroughData passThroughData) {
>     final NGLogCallback logCallback = serviceStepsHelper.getLogCallbackForManifestOrConfigFilesStep(ambiance, false);
> ```

the naming of the method is not good. Either we should
- create different methods for manifest and config files
- create 1 method which accepts some argument

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/constants/ServiceStepConstants.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/53794#-Ng2xfk424O4h9mKtOf-:-Ng3Xlhp7qH9vnt0h1Tc:b32v57) ([raw file](https://github.com/harness/harness-core/blob/970a519e2c9545d9d38f00483f4a9b7ebb28f908/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/constants/ServiceStepConstants.java#L50)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

This shouldn't be part of ServiceStepConstants. Move this to Custom stage constants.
</blockquote></details>

+1

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53794)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Comment by lovish1999** [comment]
trigger uts

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53794)* status: 14 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 8 of 14 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53794)* status: 14 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
Overall LGTM with minor comments.

> Reviewed 10 of 14 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53794#-:-NgKU-CM2aoBZbqm5MIA:btabond)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 296 at r4](https://reviewable.io/reviews/harness/harness-core/53794#-NgKTYap5V40q2cWN6qP:-NgKTYap5V40q2cWN6qQ:b-f2y2s) ([raw file](https://github.com/harness/harness-core/blob/5510ab0b185ec875e9ec873eae1ad01cd40a2c40/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L296)):*
> ```Java
>   }
> 
>   public NGLogCallback getLogCallback(Ambiance ambiance, boolean shouldOpenStream, String commandUnit) {
> ```

We can move this method to NGLogCallbackUtility class. 
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/utilities/NGLogCallbackUtility.java` line 36 at r4](https://reviewable.io/reviews/harness/harness-core/53794#-NgJXyT91lDOVBqjFkGQ:-NgKSvsc3sMuFp6jhcTR:b-lii1id) ([raw file](https://github.com/harness/harness-core/blob/5510ab0b185ec875e9ec873eae1ad01cd40a2c40/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/utilities/NGLogCallbackUtility.java#L36)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This should not be called NGLogCallbackUtility
Its specific to Service And Environments
Can we create separate classes on methods for service and environment ?
</blockquote></details>

Agree, rename the class or public getLogCallback method to be specific to service and envs.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/CustomStageFilterCreator.java` line 53 at r4](https://reviewable.io/reviews/harness/harness-core/53794#-NgKSSK00Hf7-wmUaXI6:-NgKSSK00Hf7-wmUaXI7:byjprj2) ([raw file](https://github.com/harness/harness-core/blob/5510ab0b185ec875e9ec873eae1ad01cd40a2c40/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/CustomStageFilterCreator.java#L53)):*
> ```Java
>       final ParameterField<String> environmentRef = env.getEnvironmentRef();
>       if (ParameterField.isNull(environmentRef)
>           || EmptyPredicate.isEmpty(environmentRef.fetchFinalValue().toString())) {
> ```

can environmentRef.fetchFinalValue() be null?



_Code quote:_
```Java
environmentRef.fetchFinalValue()
```

**Review by lovish1999 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53794)* status: 1 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 296 at r4](https://reviewable.io/reviews/harness/harness-core/53794#-NgKTYap5V40q2cWN6qP:-NgN8JpgClEbxjdIZmTk:b-rnlexb) ([raw file](https://github.com/harness/harness-core/blob/5510ab0b185ec875e9ec873eae1ad01cd40a2c40/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L296)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We can move this method to NGLogCallbackUtility class.
</blockquote></details>

It is only specific to custom stage env. step. 
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java` line 168 at r2](https://reviewable.io/reviews/harness/harness-core/53794#-Ng3XWhf4ma7z2q5z6HT:-NgN8NEn2wcnS01ys-Um:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/970a519e2c9545d9d38f00483f4a9b7ebb28f908/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java#L168)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

the naming of the method is not good. Either we should
- create different methods for manifest and config files
- create 1 method which accepts some argument
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java` line 414 at r2](https://reviewable.io/reviews/harness/harness-core/53794#-Ng2zFz62mE9RWvsm3HP:-NgN8Pia80_ydUQcKj-U:b-as56sm) ([raw file](https://github.com/harness/harness-core/blob/970a519e2c9545d9d38f00483f4a9b7ebb28f908/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java#L414)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Before your changes, if finalScvManifestMap is empty we were calling the overrideHelmRepoConnectorIfHelmChartExists method, pls check that we are backward compatible.
</blockquote></details>

yes, it is backward compatible as we handle empty values there are also similarly. But still for clarity, if made the changes. 
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/53794#-Ng2ztHm8DL3qae6BsT1:-NgN8Z2cCoPwGg8h-4rL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/970a519e2c9545d9d38f00483f4a9b7ebb28f908/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java#L87)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

This shouldn't be part of ServiceStepHelper. Pls, create the new class CustomStage helper or CustomStageEnviromentHelper ....
and move methods related to the custom stage there including getLogCallbackForManifestOrConfigFilesStep
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/53794#-Ng3-ZFY2Mpq0dkdz_7n:-NgN8ZzM1BkXs9OIqhKr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/970a519e2c9545d9d38f00483f4a9b7ebb28f908/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java#L175)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

How is this working, can we get ride of the service step in the custom stage env step?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/utilities/NGLogCallbackUtility.java` line 36 at r4](https://reviewable.io/reviews/harness/harness-core/53794#-NgJXyT91lDOVBqjFkGQ:-NgN8adKAwXzXKZgA-r0:b-ki7w33) ([raw file](https://github.com/harness/harness-core/blob/5510ab0b185ec875e9ec873eae1ad01cd40a2c40/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/utilities/NGLogCallbackUtility.java#L36)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Agree, rename the class or public getLogCallback method to be specific to service and envs.
</blockquote></details>

Okay, renaming can be done in separate upcoming PR as all UTs have already run. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/CustomStageFilterCreator.java` line 53 at r4](https://reviewable.io/reviews/harness/harness-core/53794#-NgKSSK00Hf7-wmUaXI6:-NgN8j5i2Ly1D78QeDLZ:bfr98mt) ([raw file](https://github.com/harness/harness-core/blob/5510ab0b185ec875e9ec873eae1ad01cd40a2c40/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/CustomStageFilterCreator.java#L53)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

can environmentRef.fetchFinalValue() be null?
</blockquote></details>

No. Because ParameterField.isNull should handle those cases. But still for safety, I can keep a check on it in upcoming PR.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53794)* status: 2. unresolved discussions.

**Comment by lovish1999** [comment]
trigger review

**Pull request merged**
