### PR TITLE
[feat]: [PL-32216] : Multiple SAML setting 'update', 'delete', 'test' support in NG

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes

Adding support for cases when multiple SAML providers will be configured when FF `PL_ENABLE_MULTIPLE_IDP_SUPPORT` is ON.
In that scenario user would be able to do:

1. Update/Delete/Test a single SAML provider setting 
2. Create more that 1 SAML provider setting in account
3. Ability to enable/disable authentication enable via a single SAML setting 

Test Scenarios:

Without FF:
All things working as they are currently. (a) Able to create SAML settings, update, delete SAML setting with just accountId. 
(b) Setting account auth mechanism to SAML & deleting SAML falls back to USER_PASSWORD

With FF enabled:
a) Update, Delete on account API is blocked with appropriate error to user
b) Update, delete on SAML ssoId tested
c) Updating authenticationEnabled for individual SAML setting tested
d) Setting account level auth-mechanism and deleting SAML doesn't reset to USER_PASSWORD if there are still more SAML setting with authentication enabled. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47321)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger checkstylecodeformat

**Comment by pbarapatre10** [comment]
trigger pmd

**Comment by pbarapatre10** [comment]
trigger codebasehash

**Comment by pbarapatre10** [comment]
trigger checkstylecodeformat

**Comment by pbarapatre10** [comment]
trigger checkstylecodeformat

**Comment by pbarapatre10** [comment]
trigger pmd

**Comment by pbarapatre10** [comment]
trigger codebasehash

**Comment by pbarapatre10** [comment]
trigger ss

**Comment by shashank-harness** [comment]
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java` line 117 at r4](https://reviewable.io/reviews/harness/harness-core/47321#-NUbHC-54h86f1I2Uv3W:-NUbHC-54h86f1I2Uv3X:b-lzezx3) ([raw file](https://github.com/harness/harness-core/blob/5252212d0bc92c40251cd4f7f938f9d6c2e4763f/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L117)):*
> ```Java
>             SamlSettings samlSettings = (SamlSettings) ssoSetting;
>             if (samlSettings.isAuthenticationEnabled()) {
>               count++;
> ```

minor optimization:
if the purpose of this counter is to know whether there is any SAML setting with auth enabled, then why not break the loop once we find one instead of going through all of the settings.

**Comment by pbarapatre10** [comment]
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java` line 117 at r4](https://reviewable.io/reviews/harness/harness-core/47321#-NUbHC-54h86f1I2Uv3W:-NUcJvOi38hgLxjpSefz:b-dtkdsq) ([raw file](https://github.com/harness/harness-core/blob/5252212d0bc92c40251cd4f7f938f9d6c2e4763f/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L117)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

minor optimization:
if the purpose of this counter is to know whether there is any SAML setting with auth enabled, then why not break the loop once we find one instead of going through all of the settings.
</blockquote></details>

Done, thanks

**Comment by pbarapatre10** [comment]
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java` line 109 at r4](https://reviewable.io/reviews/harness/harness-core/47321#-NUbEXqu9XJcw5qja07a:-NUcJxVm48ikN_kcjpZ3:b-896fja) ([raw file](https://github.com/harness/harness-core/blob/5252212d0bc92c40251cd4f7f938f9d6c2e4763f/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L109)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

minor comment:
if we put this condition first, we can avoid unnecessary calls to featureflag service:

</blockquote></details>

Done!

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by piyush-harness** [comment]
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsService.java` line 45 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe07HYCZmMmecaGxWe:-NUe07HYCZmMmecaGxWf:b-k3xjj1) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsService.java#L45)):*
> ```Java
>       String samlProviderType, String clientId, String clientSecret);
>   // this overloading is for case when updating a SAML setting among list of settings in account {samlSSOId}
>   SSOConfig updateSAMLMetadata(@NotNull String accountId, String samlSSOId, MultipartBody.Part inputStream,
> ```

This is too may arguments for a method, Can we instead pass a DTO?

**Comment by piyush-harness** [comment]
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java` line 113 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe0uIZ2X8rwqBRApMF:-NUe0uIZ2X8rwqBRApMG:b-9xxqud) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L113)):*
> ```Java
>       if (null != ssoConfig) {
>         int count = 0;
>         for (SSOSettings ssoSetting : ssoConfig.getSsoSettings()) {
> ```

This is too much verbose code, It can be done in a single line using Java Streams and Filter

**Comment by piyush-harness** [comment]
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java` line 278 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe15HG65yuB4L0jSjm:-NUe15HG65yuB4L0jSjn:bnjkwjn) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L278)):*
> ```Java
>       String entityIdentifier, String samlProviderType, String clientId, String clientSecret) {
>     // when FF is enabled, avoid using this API, which can result in discrepancy of SAML setting update
>     if (ngFeatureFlagHelperService.isEnabled(accountId, PL_ENABLE_MULTIPLE_IDP_SUPPORT)) {
> ```

Instead of repeating the same code , Can we write the check and exception thrown in one place and resuse it?

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/beans/sso/SamlSettings.java` line 53 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe1pyCDLuBUnraFsij:-NUe1pyCDLuBUnraFsik:brb9bqv) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/400-rest/src/main/java/software/wings/beans/sso/SamlSettings.java#L53)):*
> ```Java
>   @SchemaIgnore private String encryptedClientSecret;
>   private String friendlySamlName;
>   private boolean configuredFromNG;
> ```

Are we going to write migration for existing entries for this field?

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/SSOResourceNG.java` line 194 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe24kGCoKzUhj0RV2Z:-NUe24kGCoKzUhj0RV2_:bq0bic2) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/400-rest/src/main/java/software/wings/resources/SSOResourceNG.java#L194)):*
> ```Java
>   @Path("saml-idp-metadata-upload-sso-id")
>   @Timed
>   @AuthRule(permissionType = LOGGED_IN)
> ```

Why AuthRule LOGGED_IN is needed here if its an internal API?

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 19 files at r1, 1 of 1 files at r2, 3 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47321)* status: 23 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java` line 320 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe1Jp81gLmb3uCne8C:-NUe1Jp81gLmb3uCne8D:blwrj5y) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L320)):*
> ```Java
>   public SSOConfig deleteSAMLMetadata(@NotNull @AccountIdentifier String accountIdentifier) {
>     // when FF is enabled, avoid using this API, which can result in discrepancy of SAML setting update
>     if (ngFeatureFlagHelperService.isEnabled(accountIdentifier, PL_ENABLE_MULTIPLE_IDP_SUPPORT)) {
> ```

Same code repeat?

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/beans/sso/SamlSettings.java` line 53 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe1pyCDLuBUnraFsij:-NUeOdOgDvTsC2dvpnKU:b-jmrf50) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/400-rest/src/main/java/software/wings/beans/sso/SamlSettings.java#L53)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Are we going to write migration for existing entries for this field?
</blockquote></details>

Yes, we are going to write migration for this, thanks

**Comment by pbarapatre10** [comment]
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsService.java` line 45 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe07HYCZmMmecaGxWe:-NUeOlZhDe1Gd-YYxe6a:bf7jf65) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsService.java#L45)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

This is too may arguments for a method, Can we instead pass a DTO?
</blockquote></details>

Agreed!
We'll handle this in separate PR, because the impact of this change is quite big, since similar arguments are passed down to CG side as well. Thanks

**Comment by pbarapatre10** [comment]
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java` line 113 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe0uIZ2X8rwqBRApMF:-NUeOko622OX5XnPGsL5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L113)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

This is too much verbose code, It can be done in a single line using Java Streams and Filter
</blockquote></details>

Done.

**Comment by pbarapatre10** [comment]
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java` line 278 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe15HG65yuB4L0jSjm:-NUeOjwv7vxUwziByT_L:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L278)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Instead of repeating the same code , Can we write the check and exception thrown in one place and resuse it?
</blockquote></details>

Done.

**Comment by pbarapatre10** [comment]
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java` line 320 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe1Jp81gLmb3uCne8C:-NUeOjM68RoIstCSY0Zj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L320)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Same code repeat?
</blockquote></details>

Done.

**Comment by pbarapatre10** [comment]
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java` line 488 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe1TAl2VR5nwmHh2aW:-NUeOikX2bZ4g_PdLgmp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L488)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Removed the verbosity in code
</blockquote></details>

Done.

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/resources/SSOResourceNG.java` line 194 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe24kGCoKzUhj0RV2Z:-NUePqmg57LnbsCsfFe1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/400-rest/src/main/java/software/wings/resources/SSOResourceNG.java#L194)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why AuthRule LOGGED_IN is needed here if its an internal API?
</blockquote></details>

Done.

**Comment by pbarapatre10** [comment]
trigger uts

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 18 of 19 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 9 of 11 files at r5, 4 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47321)* status: 16 file(s) to review. 1 change requests. 8. unresolved discussions. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 8 of 19 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 6 of 11 files at r5, 4 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47321)* status: 1 change requests. 8. unresolved discussions.

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/SSOResourceNG.java` line 194 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe24kGCoKzUhj0RV2Z:-NUgjan9E0NY9i28Axwe:b4onzuq) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/400-rest/src/main/java/software/wings/resources/SSOResourceNG.java#L194)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did we confirm its not gonna break anything before removing?

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/security/saml/SamlClientService.java` line 100 at r7](https://reviewable.io/reviews/harness/harness-core/47321#-NUgjuaJ6jm3yQIi9yj-:-NUgjuaK3GKvk6l7tr09:ba9s8hz) ([raw file](https://github.com/harness/harness-core/blob/7934b7bb0f01962b98d58e9dd37648d1d4e6aafd/400-rest/src/main/java/software/wings/security/saml/SamlClientService.java#L100)):*
> ```Java
> 
>   public SamlClient getSamlClientFromAccountAndSamlId(Account account, String samlUuid) throws SamlException {
>     List<SamlSettings> samlSettings = ssoSettingService.getSamlSettingsListByAccountId(account.getUuid());
> ```

Why load all in memory ? Can we not query only one?

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/beans/sso/SamlSettings.java` line 53 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe1pyCDLuBUnraFsij:-NUgoX990FFuy-TXWAnB:bau27w5) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/400-rest/src/main/java/software/wings/beans/sso/SamlSettings.java#L53)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Yes, we are going to write migration for this, thanks
</blockquote></details>

Primitive boolean can break existing SAML Settings load, Have we tested that?

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/resources/SSOResourceNG.java` line 194 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe24kGCoKzUhj0RV2Z:-NUhiCnj3ZKOJwRfeDIL:b-xlrgjq) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/400-rest/src/main/java/software/wings/resources/SSOResourceNG.java#L194)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Did we confirm its not gonna break anything before removing?
</blockquote></details>

Yes, confirmed that it doesn't break anything.

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/saml/SamlClientService.java` line 100 at r7](https://reviewable.io/reviews/harness/harness-core/47321#-NUgjuaJ6jm3yQIi9yj-:-NUhi_icEbJOzhbd0jwf:b82w7i4) ([raw file](https://github.com/harness/harness-core/blob/7934b7bb0f01962b98d58e9dd37648d1d4e6aafd/400-rest/src/main/java/software/wings/security/saml/SamlClientService.java#L100)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why load all in memory ? Can we not query only one?
</blockquote></details>

Yes, we can. Will fix this in subsequent PR. Thanks

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/beans/sso/SamlSettings.java` line 53 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe1pyCDLuBUnraFsij:-NUhigXHDNnPFARK6nCe:b-1bfzgm) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/400-rest/src/main/java/software/wings/beans/sso/SamlSettings.java#L53)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Primitive boolean can break existing SAML Settings load, Have we tested that?
</blockquote></details>

It is not breaking any existing flow as for existing settings configured since it can be updated from CG also, the value should be false (default) for `configuredFromNG`. CG API will only list SAML which has this attribute value as false. Thanks

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/beans/sso/SamlSettings.java` line 53 at r6](https://reviewable.io/reviews/harness/harness-core/47321#-NUe1pyCDLuBUnraFsij:-NUhm7gVEQ7C0vV3OOtj:b-89rjml) ([raw file](https://github.com/harness/harness-core/blob/83792218a6f27a926a76f071c5dbe91e9f8360df/400-rest/src/main/java/software/wings/beans/sso/SamlSettings.java#L53)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

It is not breaking any existing flow as for existing settings configured since it can be updated from CG also, the value should be false (default) for `configuredFromNG`. CG API will only list SAML which has this attribute value as false. Thanks
</blockquote></details>

DONE

**Review by piyush-harness — APPROVED** [review]
> Reviewed 4 of 19 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, 4 of 11 files at r5, 4 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47321)* status: 1. unresolved discussions.

**Pull request merged**
