### PR TITLE
fix:[CDS-68038]: Push unoptimized query on workflowExecution collection behind FF

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- Add an FF to disable the query.
- Segment event for CG is not mission critical, we can control which account enables it.
- It will be a negative FF, where the default is we never execute this code block.

## Additional Information.
The collection `workflowExecution` doesn't have an index using `accountId` and `createdBy.email` to speed up the execution. We should avoid adding more indexes to the collection to resolve corner cases, our focus is to add new indexes only to achieve a higher audience.

Our options are:

1. Add a new index to keep 100% of the current rule.
1. Changing the query to use sort DESC increases the performance by 97%, but slightly changes the existing rule. From 21560 totalKeysExamined using ASC to 591 using DESC.
1. Add a FF to disable the query. Segment event for CG is not mission critical, we can control which account enables it. 

For now, we are going with option 3 focused on prod stability.

## Comment Triggers
<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47913)

### CODE REVIEW

**Comment by Fernando-Dourado** [comment]
trigger messagecheck

**Review by lasdox — APPROVED** [review]

**Review by vaibhav-si — COMMENTED** [review]
This FF in long run means we wil no longer this particular Segment event.
Have we checked the consumer of this event if this is fine?

Also, there's no way to optimize the query itself?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47913#-:-NVcFJOb4X6IukW5DXSQ:bu56wxc)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — COMMENTED** [review]
"wil no longer this particular Segment event." -> "wil no longer send this particular Segment event."

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47913#-:-NVcFvRxAQcIpuLNEHhC:bswfhis)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47913)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/event/handler/impl/EventPublishHelper.java` line 850 at r1](https://reviewable.io/reviews/harness/harness-core/47913#-NVcGeFP3I4RQ_gLwWrw:-NVcGeFP3I4RQ_gLwWrx:b-za00yn) ([raw file](https://github.com/harness/harness-core/blob/b24b566d9d7b11c8127c7d3bb9fdf61b18f0d45c/400-rest/src/main/java/io/harness/event/handler/impl/EventPublishHelper.java#L850)):*
> ```Java
>           aPageRequest()
>               .addFilter("accountId", Operator.EQ, accountId)
>               .addFilter("createdBy.email", Operator.EQ, userEmail)
> ```

Why do we even need to filter by user email if all we want to know is whether it's the first deployment in the account or not?

**Review by Fernando-Dourado — COMMENTED** [review]
The query optimization was evaluated as mentioned in additional details from PR description.

* Changing the query to use sort DESC increases the performance by 97%, but slightly changes the existing rule. From 21560 totalKeysExamined using ASC to 591 using DESC.

We don't have many options.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47913#-:-NVeTTl_5_Rvk6RIoxj2:ba9u59t)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/event/handler/impl/EventPublishHelper.java` line 850 at r1](https://reviewable.io/reviews/harness/harness-core/47913#-NVcGeFP3I4RQ_gLwWrw:-NVeTzps6XL8JnDio3t4:b9jhv5s) ([raw file](https://github.com/harness/harness-core/blob/b24b566d9d7b11c8127c7d3bb9fdf61b18f0d45c/400-rest/src/main/java/io/harness/event/handler/impl/EventPublishHelper.java#L850)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Why do we even need to filter by user email if all we want to know is whether it's the first deployment in the account or not?
</blockquote></details>

This piece of code identifies if is the first deployment of that user, the published event has the account and user e-mail information. The other events published by this class use only account.

**Comment by Fernando-Dourado** [comment]
trigger uts

**Comment by Fernando-Dourado** [comment]
trigger codeformat

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47913)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by puthrayaharness — APPROVED** [review]

**Comment by Fernando-Dourado** [comment]
trigger review

**Pull request merged**
