### PR TITLE
[feat]: [PL-27888]: add NG delegate tasks for LDAP auth test

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
For NG LDAP we want to remove dependency for CG delegate. In this PR we are removing the dependency for CG delegate task for testing authentication with LDAP. The changes create a new NG delegate task and checks for test-authentication scenario. 

- Is it new task type? YES

- Did you add a new class which is added in kryo serialization - YES

    - if yes then do not use that class in any of the delegate task payload till it makes to delegate release - YES
 
- Did you make changes to the code in a backward-compatible manner? - YES

    - will the new version of the delegate receive old version task and process? - YES
    - If new version of the manager receives response for the old task will it be able to handle it successfully? - YES

- Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager - YES

    - If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay - YES
    - if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay - YES

- Did you add an enum ? - YES to the end `NG_LDAP_TEST_AUTHENTICATION` 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37025)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37025)

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Review by ujjawal-harness — APPROVED** [review]
:lgtm:

> Reviewed 18 of 23 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37025#-:-NAwhpEi2-MD-ywA-eqv:bnfp4nl)* status: 23 file(s) to review. 1 of 2 approvals obtained.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37025)* status: 23 file(s) to review. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ldap/src/test/java/io/harness/ldap/service/impl/NGLdapServiceImplTest.java` line 382 at r3](https://reviewable.io/reviews/harness/harness-core/37025#-NAwkg2X4aVnPJYxfE08:-NAwkg2YEr5rVjN1Nrk0:b-3nungy) ([raw file](https://github.com/harness/harness-core/blob/bec45d0137177b149cc661321bf346f6b5f94ad7/120-ng-manager/modules/ldap/src/test/java/io/harness/ldap/service/impl/NGLdapServiceImplTest.java#L382)):*
> ```Java
>   @Category(UnitTests.class)
>   public void testLDAPAuthentication() throws IOException {
>     // Arrange
> ```

nit: remove the comment
___
*[`120-ng-manager/modules/ldap/src/test/java/io/harness/ldap/service/impl/NGLdapServiceImplTest.java` line 412 at r3](https://reviewable.io/reviews/harness/harness-core/37025#-NAwl2V87ULVmHOYSq4M:-NAwl2V87ULVmHOYSq4N:b-3nungy) ([raw file](https://github.com/harness/harness-core/blob/bec45d0137177b149cc661321bf346f6b5f94ad7/120-ng-manager/modules/ldap/src/test/java/io/harness/ldap/service/impl/NGLdapServiceImplTest.java#L412)):*
> ```Java
>         .thenReturn(NGLdapTestAuthenticationTaskResponse.builder().ldapAuthenticationResponse(ldapResponse).build());
> 
>     // Act
> ```

nit: remove the comment
___
*[`120-ng-manager/modules/ldap/src/test/java/io/harness/ldap/service/impl/NGLdapServiceImplTest.java` line 415 at r3](https://reviewable.io/reviews/harness/harness-core/37025#-NAwl5HaBHdlg7JjfP8w:-NAwl5HaBHdlg7JjfP8x:b-3nungy) ([raw file](https://github.com/harness/harness-core/blob/bec45d0137177b149cc661321bf346f6b5f94ad7/120-ng-manager/modules/ldap/src/test/java/io/harness/ldap/service/impl/NGLdapServiceImplTest.java#L415)):*
> ```Java
>     LdapResponse resultResponse = ngLdapService.testLDAPLogin(ACCOUNT_ID, ORG_ID, PROJECT_ID, userName, testPassword);
> 
>     // Assert
> ```

nit: remove the comment

**Review by kapil-harness — APPROVED** [review]
> Reviewed 18 of 23 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37025)* status: :shipit: complete! ✓

**Comment by piyush-harness** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 206 at r3](https://reviewable.io/reviews/harness/harness-core/37025#-NAwqfaABtjGz6qfBuHM:-NAwqfaB03r-uCuOv97j:b2g4o20) ([raw file](https://github.com/harness/harness-core/blob/bec45d0137177b149cc661321bf346f6b5f94ad7/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L206)):*
> ```Java
>             .build();
> 
>     DelegateResponseData delegateResponseData = getDelegateResponseData(
> ```

Capture Failure and propagate above

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 18 of 23 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37025)* status: :shipit: complete! ✓

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 206 at r3](https://reviewable.io/reviews/harness/harness-core/37025#-NAwqfaABtjGz6qfBuHM:-NAx21554FLa4SjQ2AmM:b5edbkt) ([raw file](https://github.com/harness/harness-core/blob/bec45d0137177b149cc661321bf346f6b5f94ad7/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L206)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Capture Failure and propagate above
</blockquote></details>

@piyush-harness its handled in method `getDelegateResponseData` 
   `validateDelegateTaskResponse(delegateResponseData);`

**Review by piyush-harness — APPROVED** [review]
> Reviewed 18 of 23 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37025)* status: :shipit: complete! ✓

**Comment by pbarapatre10** [comment]
trigger codebasehash

**Pull request merged**
