### PR TITLE
fix: [CDS-43493]: changes to ignore helm release hist failure and ret…

### PR DESCRIPTION
**Pull request by achyuth-harness**
…ry install/upgrade

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37773)

### CODE REVIEW

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r1, 4 of 7 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37773)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 4203 at r3](https://reviewable.io/reviews/harness/harness-core/37773#-NCZSQaC0NGijh-eMLTB:-NCZSQaC0NGijh-eMLTC:b-zar4zx) ([raw file](https://github.com/harness/harness-core/blob/d9e041e77b370bc25d716cab9e6da8e56acb8991/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L4203)):*
> ```JSON
>                 },
>                 {
>                   "type": "string"
> ```

why do we need a String type as well here. ..?



_Code quote:_
```JSON
                {
                  "type": "string"
                }
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 258 at r3](https://reviewable.io/reviews/harness/harness-core/37773#-NCZqZQUBCPzfmvwCjhS:-NCZqZQUBCPzfmvwCjhT:beyr78c) ([raw file](https://github.com/harness/harness-core/blob/d9e041e77b370bc25d716cab9e6da8e56acb8991/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L258)):*
> ```Java
> 
>   public void processHelmReleaseHistOutput(ReleaseInfo releaseInfo, boolean ignoreHelmHistFailure) {
>     String msg = "Release History command passed but there is an issue with latest release, details: \n"
> ```

let's also mention here that we are deliberately skipping this and proceeding with a fresh install.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/HelmTaskHelperBaseTest.java` line 150 at r3](https://reviewable.io/reviews/harness/harness-core/37773#-NCZqzzO12I1tbdG95G_:-NCZqzzO12I1tbdG95Ga:bg6df6u) ([raw file](https://github.com/harness/harness-core/blob/d9e041e77b370bc25d716cab9e6da8e56acb8991/930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/HelmTaskHelperBaseTest.java#L150)):*
> ```Java
>         .isInstanceOf(HelmClientException.class)
>         .hasMessageContaining("immutable after creation");
>   }
> ```

add a test case for when this flag is true.

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37773)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 4203 at r3](https://reviewable.io/reviews/harness/harness-core/37773#-NCZSQaC0NGijh-eMLTB:-NCZssMh9VMueKY56648:b-iypmbn) ([raw file](https://github.com/harness/harness-core/blob/d9e041e77b370bc25d716cab9e6da8e56acb8991/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L4203)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

why do we need a String type as well here. ..?
</blockquote></details>

Discussed offline
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 258 at r3](https://reviewable.io/reviews/harness/harness-core/37773#-NCZqZQUBCPzfmvwCjhS:-NCZtG7A3YH4yqxl3wLv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9e041e77b370bc25d716cab9e6da8e56acb8991/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L258)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

let's also mention here that we are deliberately skipping this and proceeding with a fresh install.
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/HelmTaskHelperBaseTest.java` line 150 at r3](https://reviewable.io/reviews/harness/harness-core/37773#-NCZqzzO12I1tbdG95G_:-NCZtns34sSZSg34LUkw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9e041e77b370bc25d716cab9e6da8e56acb8991/930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/HelmTaskHelperBaseTest.java#L150)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

add a test case for when this flag is true.
</blockquote></details>

Done.

**Review by shubham-in10se — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37773)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Pull request merged**
