### PR TITLE
techdebt: [PIE-2782]: Added debezium module to capture mongoDB change events

### PR DESCRIPTION
**Pull request by shalini-agr**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30946)

### CODE REVIEW

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 10 of 17 files at r1, 5 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30946)* status: 17 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java, line 276 at r2](https://reviewable.io/reviews/harness/harness-core/30946#-Mwe_r6U3gUme1rIdy3C:-Mwe_r6U3gUme1rIdy3D:b-9cj3nk) ([raw file](https://github.com/harness/harness-core/blob/e31cd11ffd9ac1fd4eee2c4a8eb212762426bb16/800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java#L276)):*
> ```Java
>   @Override
>   public void run(PipelineServiceConfiguration appConfig, Environment environment) {
>     if (appConfig.getDebeziumConfig().isEnabled()) {
> ```

Let's put this if block somewhere below in this method, not at the start. 
___
*[800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java, line 278 at r2](https://reviewable.io/reviews/harness/harness-core/30946#-Mwea0Od1XF_agDWV2cJ:-Mwea0Od1XF_agDWV2cK:b-tam189) ([raw file](https://github.com/harness/harness-core/blob/e31cd11ffd9ac1fd4eee2c4a8eb212762426bb16/800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java#L278)):*
> ```Java
>     if (appConfig.getDebeziumConfig().isEnabled()) {
>       DebeziumConfiguration debeziumConfiguration = new DebeziumConfiguration();
>       ExecutorService debeziumExecutorService = Executors.newSingleThreadExecutor(
> ```

put all these 4 lines in a method named something like 'startDebeziumEngine'.
___
*[800-pipeline-service/src/main/java/io/harness/debezium/DebeziumChangeConsumer.java, line 34 at r2](https://reviewable.io/reviews/harness/harness-core/30946#-MweabJD9kCIaPi7hXfe:-MweabJD9kCIaPi7hXff:bfe9i31) ([raw file](https://github.com/harness/harness-core/blob/e31cd11ffd9ac1fd4eee2c4a8eb212762426bb16/800-pipeline-service/src/main/java/io/harness/debezium/DebeziumChangeConsumer.java#L34)):*
> ```Java
>         log.error(
>             String.format(
>                 "Exception caught when trying to process event: [%s]. Retrying this event with exponential backoff now...",
> ```

we are not doing any exponential back now currently, let's remove this.

Also, put a todo here. I think we can evaluate how we wanna handle failures here.
___
*[958-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java, line 24 at r1](https://reviewable.io/reviews/harness/harness-core/30946#-MweT4Ho4eF-dklCXrbu:-MweT4Ho4eF-dklCXrbv:b3xf0xv) ([raw file](https://github.com/harness/harness-core/blob/9bccaf229e181fe32130faa40dd77a309e565504/958-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java#L24)):*
> ```Java
> public class DebeziumController implements Runnable {
>   protected final ExecutorService executorService =
>       Executors.newSingleThreadExecutor(new ThreadFactoryBuilder().setNameFormat("debezium-controller-class").build());
> ```

thread name should be `debezium-engine` here I think



_Code quote:_
```Java
i
```

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30946)* status: 17 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java, line 276 at r2](https://reviewable.io/reviews/harness/harness-core/30946#-Mwe_r6U3gUme1rIdy3C:-MwemMip8VYfY7II4xca:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e31cd11ffd9ac1fd4eee2c4a8eb212762426bb16/800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java#L276)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Let's put this if block somewhere below in this method, not at the start. 
</blockquote></details>

Done.
___
*[800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java, line 278 at r2](https://reviewable.io/reviews/harness/harness-core/30946#-Mwea0Od1XF_agDWV2cJ:-MwemSmI21u5MpdrDKXZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e31cd11ffd9ac1fd4eee2c4a8eb212762426bb16/800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java#L278)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

put all these 4 lines in a method named something like 'startDebeziumEngine'.
</blockquote></details>

Done.
___
*[800-pipeline-service/src/main/java/io/harness/debezium/DebeziumChangeConsumer.java, line 34 at r2](https://reviewable.io/reviews/harness/harness-core/30946#-MweabJD9kCIaPi7hXfe:-MwemY8Y31kPCpV4_DnS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e31cd11ffd9ac1fd4eee2c4a8eb212762426bb16/800-pipeline-service/src/main/java/io/harness/debezium/DebeziumChangeConsumer.java#L34)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

we are not doing any exponential back now currently, let's remove this.

Also, put a todo here. I think we can evaluate how we wanna handle failures here.
</blockquote></details>

Done.
___
*[958-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java, line 24 at r1](https://reviewable.io/reviews/harness/harness-core/30946#-MweT4Ho4eF-dklCXrbu:-MwemZ_z120XRhRyLsjm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9bccaf229e181fe32130faa40dd77a309e565504/958-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java#L24)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

thread name should be `debezium-engine` here I think
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger ti0

**Comment by shalini-agr** [comment]
trigger ti4

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 7 of 17 files at r1, 4 of 7 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30946)* status: 7 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java, line 275 at r4](https://reviewable.io/reviews/harness/harness-core/30946#-MwfcntW1JQXhPc2xA47:-MwfcntW1JQXhPc2xA48:bmy6o3p) ([raw file](https://github.com/harness/harness-core/blob/de9e2059b01eae33b1f98124e7ff07eaa0abbc0b/800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java#L275)):*
> ```Java
>   }
> 
>   public static void startDebeziumEngine(DebeziumConfig debeziumConfig) {
> ```

This belongs to debezium module
___
*[800-pipeline-service/src/main/java/io/harness/debezium/DebeziumChangeConsumer.java, line 18 at r4](https://reviewable.io/reviews/harness/harness-core/30946#-Mwfd-3q6IfzbwQ1gs2s:-Mwfd-3q6IfzbwQ1gs2t:b-89a4l7) ([raw file](https://github.com/harness/harness-core/blob/de9e2059b01eae33b1f98124e7ff07eaa0abbc0b/800-pipeline-service/src/main/java/io/harness/debezium/DebeziumChangeConsumer.java#L18)):*
> ```Java
> @Singleton
> @Slf4j
> public class DebeziumChangeConsumer implements DebeziumEngine.ChangeConsumer<ChangeEvent<String, String>> {
> ```

Ditto
___
*[800-pipeline-service/src/main/java/io/harness/debezium/DebeziumConfig.java, line 16 at r4](https://reviewable.io/reviews/harness/harness-core/30946#-Mwfd1oeCz6rZjfKeVaD:-Mwfd1oeCz6rZjfKeVaE:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/de9e2059b01eae33b1f98124e7ff07eaa0abbc0b/800-pipeline-service/src/main/java/io/harness/debezium/DebeziumConfig.java#L16)):*
> ```Java
> @Data
> @Builder
> public class DebeziumConfig {
> ```

ditto
___
*[800-pipeline-service/src/main/java/io/harness/debezium/DebeziumConfiguration.java, line 17 at r4](https://reviewable.io/reviews/harness/harness-core/30946#-Mwfd3Uz9LaXQbf7cnPc:-Mwfd3Uz9LaXQbf7cnPd:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/de9e2059b01eae33b1f98124e7ff07eaa0abbc0b/800-pipeline-service/src/main/java/io/harness/debezium/DebeziumConfiguration.java#L17)):*
> ```Java
> 
> @Slf4j
> public class DebeziumConfiguration {
> ```

ditto
___
*[800-pipeline-service/src/main/java/io/harness/debezium/PipelineExecutionSummaryConsumer.java, line 12 at r4](https://reviewable.io/reviews/harness/harness-core/30946#-MwfdjYVCWuj9zU-dDfj:-MwfdjYVCWuj9zU-dDfk:bikx17a) ([raw file](https://github.com/harness/harness-core/blob/de9e2059b01eae33b1f98124e7ff07eaa0abbc0b/800-pipeline-service/src/main/java/io/harness/debezium/PipelineExecutionSummaryConsumer.java#L12)):*
> ```Java
> import io.harness.pms.plan.execution.beans.PipelineExecutionSummaryEntity;
> 
> public class PipelineExecutionSummaryConsumer implements ChangeConsumer<PipelineExecutionSummaryEntity> {
> ```

make this singleton
___
*[958-debezium-engine/src/main/java/io/debezium/embedded/EmbeddedEngineChangeEvent.java, line 56 at r4](https://reviewable.io/reviews/harness/harness-core/30946#-MwfdLu6A7Fw03V2P2Jp:-MwfdLu6A7Fw03V2P2Jq:b-jkf4tq) ([raw file](https://github.com/harness/harness-core/blob/de9e2059b01eae33b1f98124e7ff07eaa0abbc0b/958-debezium-engine/src/main/java/io/debezium/embedded/EmbeddedEngineChangeEvent.java#L56)):*
> ```Java
> 
>   @Override
>   public String toString() {
> ```

Use lombok

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30946)* status: 12 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java, line 275 at r4](https://reviewable.io/reviews/harness/harness-core/30946#-MwfcntW1JQXhPc2xA47:-Mwk85XXBrqfzSxzxVE0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/de9e2059b01eae33b1f98124e7ff07eaa0abbc0b/800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java#L275)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

This belongs to debezium module
</blockquote></details>

Done.
___
*[958-debezium-engine/src/main/java/io/debezium/embedded/EmbeddedEngineChangeEvent.java, line 56 at r4](https://reviewable.io/reviews/harness/harness-core/30946#-MwfdLu6A7Fw03V2P2Jp:-Mwk89FZBsbSp8rXHrgc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/de9e2059b01eae33b1f98124e7ff07eaa0abbc0b/958-debezium-engine/src/main/java/io/debezium/embedded/EmbeddedEngineChangeEvent.java#L56)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Use lombok
</blockquote></details>

Done.
___
*[800-pipeline-service/src/main/java/io/harness/debezium/DebeziumChangeConsumer.java, line 18 at r4](https://reviewable.io/reviews/harness/harness-core/30946#-Mwfd-3q6IfzbwQ1gs2s:-Mwk8Cya0WfpECmaeruq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/de9e2059b01eae33b1f98124e7ff07eaa0abbc0b/800-pipeline-service/src/main/java/io/harness/debezium/DebeziumChangeConsumer.java#L18)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[800-pipeline-service/src/main/java/io/harness/debezium/DebeziumConfig.java, line 16 at r4](https://reviewable.io/reviews/harness/harness-core/30946#-Mwfd1oeCz6rZjfKeVaD:-Mwk8EoJ725U7yb8up8a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/de9e2059b01eae33b1f98124e7ff07eaa0abbc0b/800-pipeline-service/src/main/java/io/harness/debezium/DebeziumConfig.java#L16)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[800-pipeline-service/src/main/java/io/harness/debezium/DebeziumConfiguration.java, line 17 at r4](https://reviewable.io/reviews/harness/harness-core/30946#-Mwfd3Uz9LaXQbf7cnPc:-Mwk8Hrz8XkBDkrros_6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/de9e2059b01eae33b1f98124e7ff07eaa0abbc0b/800-pipeline-service/src/main/java/io/harness/debezium/DebeziumConfiguration.java#L17)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[800-pipeline-service/src/main/java/io/harness/debezium/PipelineExecutionSummaryConsumer.java, line 12 at r4](https://reviewable.io/reviews/harness/harness-core/30946#-MwfdjYVCWuj9zU-dDfj:-Mwk87gIBQYqdCp6O08S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/de9e2059b01eae33b1f98124e7ff07eaa0abbc0b/800-pipeline-service/src/main/java/io/harness/debezium/PipelineExecutionSummaryConsumer.java#L12)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

make this singleton
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger checkstyle

**Comment by shalini-agr** [comment]
trigger compile, ti0, ti1, ti2, ti3, ti4, ft1, ft2

**Comment by shalini-agr** [comment]
trigger ti1

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30946)* status: 13 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[958-debezium-engine/src/main/java/io/harness/debezium/DebeziumEngineStarter.java, line 20 at r7](https://reviewable.io/reviews/harness/harness-core/30946#-MwylVwm-aqt2kxSf2vr:-MwylVwm-aqt2kxSf2vs:b-4xid8) ([raw file](https://github.com/harness/harness-core/blob/62ab475703b47cbd35d811837514b3f45353844d/958-debezium-engine/src/main/java/io/harness/debezium/DebeziumEngineStarter.java#L20)):*
> ```Java
> 
> @Slf4j
> public class DebeziumEngineStarter {
> ```

We could have formed a new class for starter and kept the original configuration class as it is.

**Review by hextechpal — COMMENTED** [review]
> Reviewed 8 of 10 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30946)* status: 12 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by hextechpal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30946#-:-MwypWw4-x51F4Z8nSax:bnfp4nl)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30946)* status: 20 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[958-debezium-engine/src/main/java/io/harness/debezium/DebeziumEngineStarter.java, line 20 at r7](https://reviewable.io/reviews/harness/harness-core/30946#-MwylVwm-aqt2kxSf2vr:-Mwz9Cx7CzrXAkESaMib:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/62ab475703b47cbd35d811837514b3f45353844d/958-debezium-engine/src/main/java/io/harness/debezium/DebeziumEngineStarter.java#L20)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

We could have formed a new class for starter and kept the original configuration class as it is.
</blockquote></details>

Done.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30946)* status: 20 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java, line 320 at r9](https://reviewable.io/reviews/harness/harness-core/30946#-Mwzv1yO-KOiBR3jlH7V:-Mwzv1yO-KOiBR3jlH7W:b-9h3lsr) ([raw file](https://github.com/harness/harness-core/blob/030eaaf58b1acd784688b23c17d6d153e48b1f6e/800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java#L320)):*
> ```Java
>       });
>     }
>     if (appConfig.getDebeziumConfig().isEnabled()) {
> ```

check for debezium config being null

**Review by vaibhav-si — COMMENTED** [review]
> Reviewed 6 of 10 files at r5, 1 of 1 files at r6, 1 of 2 files at r7, 2 of 9 files at r8, 7 of 7 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30946)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30946#-:-MwzyfMO9KXqEchj0oCH:bnfp4nl)* status: 12 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30946)* status: 12 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java, line 320 at r9](https://reviewable.io/reviews/harness/harness-core/30946#-Mwzv1yO-KOiBR3jlH7V:-MwzypgQ5piyjCzKOdSh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/030eaaf58b1acd784688b23c17d6d153e48b1f6e/800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java#L320)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

check for debezium config being null
</blockquote></details>

Done.

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30946)* status: 12 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30946#-:-Mx-8SR99RPq82RJcplc:bnfp4nl)* status: 12 file(s) to review. 1. unresolved discussions.

**Review by hextechpal — APPROVED** [review]
> Reviewed 2 of 9 files at r8, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30946)* status: 9 file(s) to review.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 4 of 17 files at r1, 2 of 7 files at r2, 7 of 10 files at r5, 1 of 1 files at r6, 1 of 2 files at r7, 2 of 9 files at r8, 7 of 7 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30946)* status: :shipit: complete! ✓

**Pull request merged**
