### PR TITLE
feat: [CDS-50962]: Support for the CommitId used for fetching manifests as a Built-In variable

### PR DESCRIPTION
**Pull request by TarunUba1**
## Describe your changes

Created a sweeping output with value :- ${k8sGitFetchInfo.Service.commitId}

## Testing
Tested to print variable in sheel script
Screenshot 2023-01-12 at 7 37 21 PM

Screenshot 2023-01-12 at 7 37 16 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42565)

### CODE REVIEW

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42565)* status: 16 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/api/k8s/K8sGitFetchInfo.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/42565#-NLeukjX8wy9pwEkl-B5:-NM2WpcH9tnjyV_jzSb6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bcc6876699fa3acd6341ceed44835889bf8fbe0a/400-rest/src/main/java/software/wings/api/k8s/K8sGitFetchInfo.java#L26)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we look into transforming this to something like ${k8sGitFetchInfo.service.commitId}, you should be able to achieve this by transforming your code into something like:
class K8sGitInfo {
  private String commitId;
}

K8sGitFetchInfo extends HashMap<String, K8sGitInfo> implements SweepingOutput {

}

${k8sGitFetchInfo.service.commitId}

And then, when you populate K8sGitFetchInfo, you could use something like:

k8sGitFetchInfo.put(K8sValuesLocation.Service.toLowercase(), K8sGitInfo.builder().commitId(...).build())

That should work, but let me know if you hit any issues
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java` line 1015 at r2](https://reviewable.io/reviews/harness/harness-core/42565#-NLevukg8ZbU9KXj8AzH:-NM2WtIJ9XvLk2F0XR31:bx1cv7j) ([raw file](https://github.com/harness/harness-core/blob/bcc6876699fa3acd6341ceed44835889bf8fbe0a/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L1015)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Not clear why do you need here to go over all values in  gitFetchFilesConfigMap, if you need only the K8sValuesLocation.Service one. The second issue, is that you just override it since your serviceId is always the same, so basically you end up in storing only the last entry in the map. In scenario where you have a values.yaml override with a different branch than your manifest, it may end up showing the commit id of the values.yaml not manifest (pure random)
</blockquote></details>

Service manifest commit is stores under Service and value override that is specified seperately is stored in ServiceOverride, will not be overwritten, tested.
___
*[`400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java` line 1019 at r2](https://reviewable.io/reviews/harness/harness-core/42565#-NLewNjL6ZAIVWm4W8ER:-NM2X5awDCUHHVXvn3Jg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bcc6876699fa3acd6341ceed44835889bf8fbe0a/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L1019)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This is not a good expression, ideally customer shouldn't don't have to know what is the serviceId
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42565)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/ScmFetchFilesHelper.java` line 80 at r3](https://reviewable.io/reviews/harness/harness-core/42565#-NM4mWftABPViKsNBxWC:-NM4mWftABPViKsNBxWD:b-3gdbmb) ([raw file](https://github.com/harness/harness-core/blob/676aa7d02ef15fcc9e9165b2ed27ad218e61ed42/930-delegate-tasks/src/main/java/software/wings/delegatetasks/ScmFetchFilesHelper.java#L80)):*
> ```Java
>   public GitFetchFilesResult fetchFilesFromRepoWithScm(
>       GitFileConfig gitFileConfig, GitConfig gitConfig, List<String> filePathList) {
>     return fetchFilesFromRepoWithScm("__default", gitFileConfig, gitConfig, filePathList);
> ```

Let's have this __default as constant with a proper naming, like DEFAULT_FETCH_IDENTIFIER
___
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/GitMetadataContext.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/42565#-NM4mgF9BT0mUgb_7WK9:-NM4mgF9BT0mUgb_7WKA:bmtti8p) ([raw file](https://github.com/harness/harness-core/blob/676aa7d02ef15fcc9e9165b2ed27ad218e61ed42/930-delegate-tasks/src/main/java/software/wings/service/impl/GitMetadataContext.java#L15)):*
> ```Java
> import java.util.Map;
> 
> public class GitMetadataContext {
> ```

Please add @Owner annotation to class 
And let's rename it to GitFetchMetadataContext
___
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/GitServiceImpl.java` line 163 at r3](https://reviewable.io/reviews/harness/harness-core/42565#-NM4mrPg8GpATKm7qs2m:-NM4mrPg8GpATKm7qs2n:b2gltva) ([raw file](https://github.com/harness/harness-core/blob/676aa7d02ef15fcc9e9165b2ed27ad218e61ed42/930-delegate-tasks/src/main/java/software/wings/service/impl/GitServiceImpl.java#L163)):*
> ```Java
>       List<String> filePaths, boolean useBranch, boolean shouldExportCommitSha, LogCallback logCallback) {
>     return fetchFilesByPath(
>         "__default", gitConfig, connectorId, commitId, branch, filePaths, useBranch, shouldExportCommitSha, null);
> ```

Same here, let's have this as constant
___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/yaml/GitFetchFilesRequest.java` line 59 at r3](https://reviewable.io/reviews/harness/harness-core/42565#-NM4nC5p-VUvCyOtwFgu:-NM4nC5p-VUvCyOtwFgv:b-9gkte) ([raw file](https://github.com/harness/harness-core/blob/676aa7d02ef15fcc9e9165b2ed27ad218e61ed42/950-delegate-tasks-beans/src/main/java/software/wings/beans/yaml/GitFetchFilesRequest.java#L59)):*
> ```Java
>     this.fileExtensions = fileExtensions;
>     this.recursive = recursive;
>   }
> ```

add space after

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42565)* status: 16 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/ScmFetchFilesHelper.java` line 80 at r3](https://reviewable.io/reviews/harness/harness-core/42565#-NM4mWftABPViKsNBxWC:-NM7PnK0Bayh18awX4Qv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/676aa7d02ef15fcc9e9165b2ed27ad218e61ed42/930-delegate-tasks/src/main/java/software/wings/delegatetasks/ScmFetchFilesHelper.java#L80)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's have this __default as constant with a proper naming, like DEFAULT_FETCH_IDENTIFIER
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/GitServiceImpl.java` line 163 at r3](https://reviewable.io/reviews/harness/harness-core/42565#-NM4mrPg8GpATKm7qs2m:-NM7Pqk-2IpegOcXxd8C:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/676aa7d02ef15fcc9e9165b2ed27ad218e61ed42/930-delegate-tasks/src/main/java/software/wings/service/impl/GitServiceImpl.java#L163)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Same here, let's have this as constant
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/yaml/GitFetchFilesRequest.java` line 59 at r3](https://reviewable.io/reviews/harness/harness-core/42565#-NM4nC5p-VUvCyOtwFgu:-NM7Prvn5BM2qZ3iaD7W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/676aa7d02ef15fcc9e9165b2ed27ad218e61ed42/950-delegate-tasks-beans/src/main/java/software/wings/beans/yaml/GitFetchFilesRequest.java#L59)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

add space after
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/GitMetadataContext.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/42565#-NM4mgF9BT0mUgb_7WK9:-NM7PopMEHMP7UXtgiea:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/676aa7d02ef15fcc9e9165b2ed27ad218e61ed42/930-delegate-tasks/src/main/java/software/wings/service/impl/GitMetadataContext.java#L15)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Please add @Owner annotation to class 
And let's rename it to GitFetchMetadataContext
</blockquote></details>

Done.

**Comment by TarunUba1** [comment]
trigger messagecheck

**Comment by TarunUba1** [comment]
trigger checkstylecodeformat

**Comment by TarunUba1** [comment]
trigger ti3

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42565)* status: 17 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/GitFetchFilesTask.java` line 106 at r10](https://reviewable.io/reviews/harness/harness-core/42565#-NMDvsh2EWgDEjeCWGMI:-NMRmGcYAh3xUNQB-KJh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6c579db8c4a27e4111bb10654239206243dfaad/930-delegate-tasks/src/main/java/software/wings/delegatetasks/GitFetchFilesTask.java#L106)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Wrap this into try block try (GitFetchMetadataContext fetchMetadataContext = new GitFetchMetadataContext()) {
  ..
}
otherwise the close method will never be called
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/GitFetchFilesTask.java` line 173 at r10](https://reviewable.io/reviews/harness/harness-core/42565#-NMDw1Vv4B55IzCnCxCO:-NMRmHuZ83yC3aUt4MUa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6c579db8c4a27e4111bb10654239206243dfaad/930-delegate-tasks/src/main/java/software/wings/delegatetasks/GitFetchFilesTask.java#L173)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

You did great previously on creating new HashMap, that would ensure that no further changes in map are made 
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/gitFetchMetadata/GitFetchMetadataContext.java` line 12 at r10](https://reviewable.io/reviews/harness/harness-core/42565#-NMDvfvL91j-I4r7QHUO:-NMRmE3U0candOC0nySA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6c579db8c4a27e4111bb10654239206243dfaad/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/gitFetchMetadata/GitFetchMetadataContext.java#L12)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Please add owner to class
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/gitFetchMetadata/GitFetchMetadataLocalThread.java` line 8 at r10](https://reviewable.io/reviews/harness/harness-core/42565#-NMDwge-D58-AbtZ6dnt:-NMRmFWBBJPK20s0GiCS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6c579db8c4a27e4111bb10654239206243dfaad/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/gitFetchMetadata/GitFetchMetadataLocalThread.java#L8)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

let's rename this package to metadata or context, it's more readable to keep simple names for package, as this can be confused with classes or methods 
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42565)* status: 18 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/GitFetchFilesTask.java` line 176 at r12](https://reviewable.io/reviews/harness/harness-core/42565#-NMSTjmw8aCaxg8-xZnZ:-NMSTjmx-YtU4xeX246t:btnxxjd) ([raw file](https://github.com/harness/harness-core/blob/34f978068fe7f6343a47b0f7f7c5b0f96aed47e3/930-delegate-tasks/src/main/java/software/wings/delegatetasks/GitFetchFilesTask.java#L176)):*
> ```Java
>           .gitCommandStatus(GitCommandStatus.SUCCESS)
>           .build();
>     } catch (Exception ex) {
> ```

no need for this catch block, you should be able to use try with resource without catch block
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/metaData/GitFetchMetadataLocalThread.java` line 8 at r12](https://reviewable.io/reviews/harness/harness-core/42565#-NMSTMurCNjqcaOcKWe9:-NMSTMut6PpFlmVEJObo:bob47ie) ([raw file](https://github.com/harness/harness-core/blob/34f978068fe7f6343a47b0f7f7c5b0f96aed47e3/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/metaData/GitFetchMetadataLocalThread.java#L8)):*
> ```Java
>  */
> 
> package io.harness.delegate.task.git.metaData;
> ```

metadata all lowercase

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42565)* status: 18 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/GitFetchFilesTask.java` line 176 at r12](https://reviewable.io/reviews/harness/harness-core/42565#-NMSTjmw8aCaxg8-xZnZ:-NMS_aZTAmJcbt-zFvZ6:b5p6afv) ([raw file](https://github.com/harness/harness-core/blob/34f978068fe7f6343a47b0f7f7c5b0f96aed47e3/930-delegate-tasks/src/main/java/software/wings/delegatetasks/GitFetchFilesTask.java#L176)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

no need for this catch block, you should be able to use try with resource without catch block
</blockquote></details>

Need the catch block to catch exceptions thrown by GitFetchMetadataContext.

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42565)* status: 17 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/metaData/GitFetchMetadataLocalThread.java` line 8 at r12](https://reviewable.io/reviews/harness/harness-core/42565#-NMSTMurCNjqcaOcKWe9:-NMSdRH45x7f6UsFExTS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/34f978068fe7f6343a47b0f7f7c5b0f96aed47e3/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/metaData/GitFetchMetadataLocalThread.java#L8)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

metadata all lowercase
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42565)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by namantalaycha10 — APPROVED** [review]
> Reviewed 4 of 16 files at r3, 6 of 13 files at r4, 1 of 2 files at r8, 2 of 2 files at r12, 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42565)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/api/k8s/K8sGitFetchInfo.java` line 31 at r13](https://reviewable.io/reviews/harness/harness-core/42565#-NMTq8KaEgEJ8-ytFywR:-NMTq8KbD9x1NgotuoJ_:bbqbj4o) ([raw file](https://github.com/harness/harness-core/blob/f6e6ee83208348640ef7c46613222a64acbe6b61/400-rest/src/main/java/software/wings/api/k8s/K8sGitFetchInfo.java#L31)):*
> ```Java
>   @Override
>   public String getType() {
>     return "K8sGitFetchInfo";
> ```

nit: should be a constant variable instead of hardcoded one

**Pull request merged**
