### PR TITLE
[fix]: [PIE-8949]: Fixing Inconsistent processing of response messages for steps and rollback

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Fixing Inconsistent processing of response messages for steps and rollback.
Issue: When we generate the stepResponse from multiple child responseMap. The final message will depend on the the order in which they the responses are iterated from map.
Fix: Passing the nodeExecutionTs in the StepResponseNotifyData while ending the execution. So setting the message from the latest child response fixed the issue.

Backward compatibility: The change is backward compatible as we are checking the field for null before using. So if its not present in the response form a service. it will not break anything.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45288)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/SdkCoreStepUtils.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/45288#-NQiv1Vb7hK0iehuyIte:-NQiv1Vb7hK0iehuyItf:bcy73om) ([raw file](https://github.com/harness/harness-core/blob/179188c114ffbb9ec0c0b9678774b85ecb667224/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/SdkCoreStepUtils.java#L42)):*
> ```Java
>           failureInfoBuilder.addAllFailureData(responseNotifyData.getFailureInfo().getFailureDataList());
>           failureInfoBuilder.addAllFailureTypes(responseNotifyData.getFailureInfo().getFailureTypesList());
>           // Put the errorMessage only if it's not set yet. Or responseNotifyData is the most recent failure.
> ```

The comment does't go along whats implemented. What are we doing for "put error message only if its not set yet"?

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45288)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/SdkCoreStepUtils.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/45288#-NQj2iOG3COBbx4QeypI:-NQj2iOG3COBbx4QeypJ:bqumhjj) ([raw file](https://github.com/harness/harness-core/blob/179188c114ffbb9ec0c0b9678774b85ecb667224/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/SdkCoreStepUtils.java#L38)):*
> ```Java
>       childStatuses.add(executionStatus);
>       nodeExecutionId = responseNotifyData.getNodeUuid();
>       if (StatusUtils.brokeStatuses().contains(executionStatus)) {
> ```

@brijeshdhakar i think only error message is not the issue, list of failureInfoData also needs to be sorted with endTs, so you wont need to handle it diffferently
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/pms/execution/utils/NodeProjectionUtils.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/45288#-NQj2wszEhKZa8geHKZT:-NQj2wszEhKZa8geHKZU:blsy4dt) ([raw file](https://github.com/harness/harness-core/blob/179188c114ffbb9ec0c0b9678774b85ecb667224/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/pms/execution/utils/NodeProjectionUtils.java#L92)):*
> ```Java
>       NodeExecutionKeys.failureInfo, NodeExecutionKeys.oldRetry, NodeExecutionKeys.endTs);
> 
>   public static final Set<String> fieldsForExecutionStrategy =
> ```

which one is using this?

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45288)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/SdkCoreStepUtils.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/45288#-NQj2iOG3COBbx4QeypI:-NQj9i49CljK2pVVrSrz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/179188c114ffbb9ec0c0b9678774b85ecb667224/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/SdkCoreStepUtils.java#L38)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@brijeshdhakar i think only error message is not the issue, list of failureInfoData also needs to be sorted with endTs, so you wont need to handle it diffferently
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/SdkCoreStepUtils.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/45288#-NQiv1Vb7hK0iehuyIte:-NQj90D93gaL1X2DIVZ7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/179188c114ffbb9ec0c0b9678774b85ecb667224/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/SdkCoreStepUtils.java#L42)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The comment does't go along whats implemented. What are we doing for "put error message only if its not set yet"?
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/pms/execution/utils/NodeProjectionUtils.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/45288#-NQj2wszEhKZa8geHKZT:-NQj9WDe599zlV5oMXDl:b-ojtpmn) ([raw file](https://github.com/harness/harness-core/blob/179188c114ffbb9ec0c0b9678774b85ecb667224/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/pms/execution/utils/NodeProjectionUtils.java#L92)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

which one is using this?
</blockquote></details>

Its used by nodeResumeHelper. we send the stepResponseNotifyData from here for the all children nodeExecution.



_Code quote:_
```Java
fieldsForResponseNotifyData
```

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by archit-harness — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45288)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45288)* status: 7 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45288)* status: :shipit: complete! ✓

**Pull request merged**
