### PR TITLE
[feat]: [PL-23131]: Adds OpenApi generator dropwizard command

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32514)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 26 of 26 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32514)* status: 27 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 281 at r2](https://reviewable.io/reviews/harness/harness-core/32514#-N0nnGkKD5QWxQYkP0Wh:-N0nnGkKD5QWxQYkP0Wi:bohv1s2) ([raw file](https://github.com/harness/harness-core/blob/ca6bb781661e2ae9db5d7d72d29ae069b96d4d61/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L281)):*
> ```Java
>     bootstrap.addCommand(new InspectCommand<>(this));
>     bootstrap.addCommand(new ScanClasspathMetadataCommand());
>     bootstrap.addCommand(new OpenApiGenerationCommand(getOasConfig(getLocalConfiguration())));
> ```

Lets rename this command to GenerateOpenApiSpecCommand
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 295 at r2](https://reviewable.io/reviews/harness/harness-core/32514#-N0nnAqS3OaPcSNWdKyX:-N0nnAqTCiLR38NQFuVZ:bye1hu8) ([raw file](https://github.com/harness/harness-core/blob/ca6bb781661e2ae9db5d7d72d29ae069b96d4d61/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L295)):*
> ```Java
>   }
> 
>   private NextGenConfiguration getLocalConfiguration() {
> ```

Put this method in NextGenConfiguration class itself.
___
*[`290-dashboard-service/src/main/java/io/harness/DashboardServiceConfig.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/32514#-N0nnwd66SOrxfEBY7Ut:-N0nnwd95Ro-Clwwj3ol:b-xlxxk0) ([raw file](https://github.com/harness/harness-core/blob/ca6bb781661e2ae9db5d7d72d29ae069b96d4d61/290-dashboard-service/src/main/java/io/harness/DashboardServiceConfig.java#L30)):*
> ```Java
> 
> @Getter
> @Setter
> ```

We should not need Setter here once we move getLocalConfiguration method here

**Comment by ashishsanodia-harness** [comment]
trigger authorcheck

**Comment by ashishsanodia-harness** [comment]
> > Reviewed 1 of 3 files at r1, 26 of 26 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/32514)_ status: 27 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 281 at r2](https://reviewable.io/reviews/harness/harness-core/32514#-N0nnGkKD5QWxQYkP0Wh:-N0nnGkKD5QWxQYkP0Wi:bohv1s2) ([raw file](https://github.com/harness/harness-core/blob/ca6bb781661e2ae9db5d7d72d29ae069b96d4d61/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L281)):_
> 
> > ```java
> >     bootstrap.addCommand(new InspectCommand<>(this));
> >     bootstrap.addCommand(new ScanClasspathMetadataCommand());
> >     bootstrap.addCommand(new OpenApiGenerationCommand(getOasConfig(getLocalConfiguration())));
> > ```
> 
> Lets rename this command to GenerateOpenApiSpecCommand
>> Done
> 
> _[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 295 at r2](https://reviewable.io/reviews/harness/harness-core/32514#-N0nnAqS3OaPcSNWdKyX:-N0nnAqTCiLR38NQFuVZ:bye1hu8) ([raw file](https://github.com/harness/harness-core/blob/ca6bb781661e2ae9db5d7d72d29ae069b96d4d61/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L295)):_
> 
> > ```java
> >   }
> > 
> >   private NextGenConfiguration getLocalConfiguration() {
> > ```
> 
> Put this method in NextGenConfiguration class itself.
>> Done
> 
> _[`290-dashboard-service/src/main/java/io/harness/DashboardServiceConfig.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/32514#-N0nnwd66SOrxfEBY7Ut:-N0nnwd95Ro-Clwwj3ol:b-xlxxk0) ([raw file](https://github.com/harness/harness-core/blob/ca6bb781661e2ae9db5d7d72d29ae069b96d4d61/290-dashboard-service/src/main/java/io/harness/DashboardServiceConfig.java#L30)):_
> 
> > ```java
> > @Getter
> > @Setter
> > ```
> 
> We should not need Setter here once we move getLocalConfiguration method here
>> Done

**Review by ankit-harness — COMMENTED** [review]
> Reviewed 4 of 5 files at r3, 29 of 29 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32514)* status: 33 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 281 at r2](https://reviewable.io/reviews/harness/harness-core/32514#-N0nnGkKD5QWxQYkP0Wh:-N13fUCUCVcODWEpd3Gp:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ca6bb781661e2ae9db5d7d72d29ae069b96d4d61/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L281)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Lets rename this command to GenerateOpenApiSpecCommand
</blockquote></details>

Done

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 295 at r2](https://reviewable.io/reviews/harness/harness-core/32514#-N0nnAqS3OaPcSNWdKyX:-N13gADq726AyzVbVoQj:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ca6bb781661e2ae9db5d7d72d29ae069b96d4d61/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L295)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Put this method in NextGenConfiguration class itself.
</blockquote></details>

Done

**Comment by ashishsanodia-harness** [comment]
*[`290-dashboard-service/src/main/java/io/harness/DashboardServiceConfig.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/32514#-N0nnwd66SOrxfEBY7Ut:-N13gFw-7o2SaBgCcCsT:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ca6bb781661e2ae9db5d7d72d29ae069b96d4d61/290-dashboard-service/src/main/java/io/harness/DashboardServiceConfig.java#L30)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We should not need Setter here once we move getLocalConfiguration method here
</blockquote></details>

Done

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32514#-:-N13lqY66V7Y64YEmaa7:bnfp4nl)* status: 33 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 4 of 5 files at r3, 29 of 29 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32514)* status: Some of the checks are too old.

**Pull request merged**
