### PR TITLE
fix: [CDS-39673]: fix having template response and node info only in template update call

### PR DESCRIPTION
**Pull request by inderschera**
## Describe your changes
TemplateResponse and nodeInfo were being populated in root errorNodeSummary on template save, which is incorrect because template haven't been saved yet.
Changed it to only happen for template update.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36419)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36419)

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36419)* status: :shipit: complete! ✓

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36419)* status: :shipit: complete! ✓

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 250 at r2](https://reviewable.io/reviews/harness/harness-core/36419#-N9eOQ1x3RY-8xeURMCB:-N9eOQ1yEMpKZL86UENo:b-hlwds5) ([raw file](https://github.com/harness/harness-core/blob/f91bab9fa5d6978ca00f471ecf0f124872db11e8/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L250)):*
> ```Java
>     } catch (NGTemplateResolveExceptionV2 ex) {
>       ValidateTemplateInputsResponseDTO validateTemplateInputsResponse = ex.getValidateTemplateInputsResponseDTO();
>       validateTemplateInputsResponse.getErrorNodeSummary().setTemplateResponse(
> ```

NIT: This Error node Summary will never be null?

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36419)* status: :shipit: complete! ✓

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 250 at r2](https://reviewable.io/reviews/harness/harness-core/36419#-N9eOQ1x3RY-8xeURMCB:-N9ecIErCHXZ-upBzWqA:b-zd18fi) ([raw file](https://github.com/harness/harness-core/blob/f91bab9fa5d6978ca00f471ecf0f124872db11e8/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L250)):*
<details><summary><i>Previously, poojaSinghal (Pooja Singhal) wrote…</i></summary><blockquote>

NIT: This Error node Summary will never be null? 
</blockquote></details>

yes, won't be null. Have a UT as well for same. If something changes, UT would fail.

**Pull request merged**
