### PR TITLE
feat: [DEL-3155]: remove use_cdn phase3

### PR DESCRIPTION
**Pull request by abhinav-harness**
This reverts commit f81a216f05685d10bd24e2320ade9024f178071f.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31058)

### CODE REVIEW

**Comment by abhinav-harness** [comment]
@gaurav-jain1 I have done it in multiple phase - USE_CDN flag is not used anywhere in start.sh and delegate.sh now. 
Since we have released new image it can now be removed. 


On second question - we have a flag which determines if its a saas delegate or on prem through which we can figure out - the flag is DEPLOY_MODE

**Comment by gaurav-jain1** [comment]
After this change,  useCdn in 'delegateconfiguration.java' will be set to false. When are we planning to deprecate that code ?

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31058)* status: 2 file(s) to review.

**Comment by abhinav-harness** [comment]
Tested on pr env

**Review by arpit3107 — APPROVED** [review]
> Reviewed 13 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31058)* status: :shipit: complete! ✓

**Pull request merged**
