### PR TITLE
fix: [CDS-49492]: fix Inline Backend Config usage when FF TERRAFORM_R…

### PR DESCRIPTION
**Pull request by akhilpandey1**
When TERRAFORM_REMOTE_BACKEND_CONFIG was enabled, it did not allow the local/inline backend config to be used, even though it could have been defined inline, this PR fixes it, by using the correct key to store it in fileMetaData and retrieve it during Destroy step execution

image
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42261)

### CODE REVIEW

**Comment by akhilpandey1** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1567 at r1](https://reviewable.io/reviews/harness/harness-core/42261#-NL-wJb1MarOZqWNwDrY-r1-1567:-NL5lLdN2SJmf01_gKdo:b4t1e3p) ([raw file](https://github.com/harness/harness-core/blob/3b97ae4ff10f684ed24c5deb2c270136a39d89ba/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1567)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

I saw here was added ! negation for LOCAL_STORE_TYPE
is this done because it’s remote backend config and is not LOCAL_STORE_TYPE?
not sure why exactly it was added.
</blockquote></details>

This is done, because earlier the code was incorrect to extract local backend configs form key BACKEND_CONFIG_KEY as it was storing it in BACKEND_CONFIGS_KEY on line 652 in this class, thus we should be going into the else block here

**Review by vlica-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42261)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by alebuh — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42261)* status: Some of the checks are too old. 1. unresolved discussions.

**Review by alebuh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42261)* status: Some of the checks are too old. 1. unresolved discussions.

**Review by vlica-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42261)* status: 1 file(s) to review.

**Review by vlica-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42261#-:-NLQ0IaQ3r6SnGHklUMJ:bnfp4nl)* status: 1 file(s) to review.

**Review by akhilpandey1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42261)* status: 1 file(s) to review.

**Review by vlica-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42261#-:-NLQ5Rrk-IEBbadSPZ2-:bnfp4nl)* status: 1 file(s) to review.

**Pull request closed without merging**
