### PR TITLE
fix: [CDS-81036]: Fix query to create rollback yaml to consider skipp…

### PR DESCRIPTION
**Pull request by Y0709**
…ed stages as well while post prod rollback

Until now we did not consider skipped stages as executed stage while post prod rollback as per the query. We have removed that to consider skipped stages to be part of yaml as well while post prod rollabck. 
Also fixed slack notification issue
We have also added a 30 day check to throw exception is post prod rollback is tried on an execution older than 30 days

Testing --
Tested post prod rollback for a stage using service from another skipped stage 
Tested slack notification . Stage name is coming correctly

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53903)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53903)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53903)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 909 at r1](https://reviewable.io/reviews/harness/harness-core/53903#-NgJ0TGjEMVbR9hCITPp:-NgJ0TGjEMVbR9hCITPq:b-z55i01) ([raw file](https://github.com/harness/harness-core/blob/973c6fa4ee8f96e95a61774ba83a22d272204369/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L909)):*
> ```Java
>       String planExecutionId, Set<String> fieldsToBeIncluded) {
>     Query query = query(where(NodeExecutionKeys.planExecutionId).is(planExecutionId))
>                       .addCriteria(where(NodeExecutionKeys.status).ne(Status.SKIPPED))
> ```

nit: can we ask cd team to add automation for the same? @sahilhindwani-harness 
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 322 at r1](https://reviewable.io/reviews/harness/harness-core/53903#-NgJ0_gM4RC1fFSZMsCC:-NgJ0_gM4RC1fFSZMsCD:bzlxim) ([raw file](https://github.com/harness/harness-core/blob/48f013a442a5e21ed128fa64436c2366be2da485/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L322)):*
> ```Java
>         }
>       }
>       stepName = nodeExecution.getName();
> ```

can we rename stepName to nodeName
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 345 at r1](https://reviewable.io/reviews/harness/harness-core/53903#-NgJ0cPS0eatkJeAoIR0:-NgJ0cPS0eatkJeAoIR1:b-geu7k8) ([raw file](https://github.com/harness/harness-core/blob/48f013a442a5e21ed128fa64436c2366be2da485/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L345)):*
> ```Java
>     templateData.put("PIPELINE", pipelineId);
>     templateData.put("PIPELINE_STEP", nodeIdentifier);
>     templateData.put("PIPELINE_STEP_NAME", stepName);
> ```

add comment here -> this env variable is for all nodes
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java` line 211 at r1](https://reviewable.io/reviews/harness/harness-core/53903#-NgJ0vp7-rAsJZZc7Owu:-NgJ0vp7-rAsJZZc7Owv:b79121u) ([raw file](https://github.com/harness/harness-core/blob/48f013a442a5e21ed128fa64436c2366be2da485/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java#L211)):*
> ```Java
>     String executionId = generateUuid();
>     ExecutionTriggerInfo triggerInfo = executionHelper.buildTriggerInfo(null);
>     PlanExecution originalPlanExecution = planExecutionService.get(originalExecutionId);
> ```

can we use projections here
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 268 at r1](https://reviewable.io/reviews/harness/harness-core/53903#-NgJ1-8JE2y6GtuuVOJG:-NgJ1-8JE2y6GtuuVOJH:bhzex4t) ([raw file](https://github.com/harness/harness-core/blob/48f013a442a5e21ed128fa64436c2366be2da485/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L268)):*
> ```Java
>   }
> 
>   public void checkAndThrowExceptionIfExecutionOlderThanOneMonthForPostProdRollback(
> ```

why post prod? isnt this true for pipeline rollback as well?

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53903)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 322 at r1](https://reviewable.io/reviews/harness/harness-core/53903#-NgJ0_gM4RC1fFSZMsCC:-NgJADCG8KgWUMGi2PK4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/48f013a442a5e21ed128fa64436c2366be2da485/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L322)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we rename stepName to nodeName
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 345 at r1](https://reviewable.io/reviews/harness/harness-core/53903#-NgJ0cPS0eatkJeAoIR0:-NgJAEH49kqXxb79H2Bh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/48f013a442a5e21ed128fa64436c2366be2da485/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L345)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comment here -> this env variable is for all nodes
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java` line 211 at r1](https://reviewable.io/reviews/harness/harness-core/53903#-NgJ0vp7-rAsJZZc7Owu:-NgJAFjXCDG9JlCe_Dbf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/48f013a442a5e21ed128fa64436c2366be2da485/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java#L211)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we use projections here
</blockquote></details>

Done.

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53903)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger ut7, ut8, ut9

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53903)* status: :shipit: complete! ✓

**Comment by Y0709** [comment]
trigger messagecheck, review

**Comment by Y0709** [comment]
trigger messagecheck

**Pull request merged**
