### PR TITLE
[feat]: [PL-31462]: Handle delete user from SCIM if user added to NG SCIM and manually invited to CG

### PR DESCRIPTION
**Pull request by shashank-harness**
## Describe your changes
Fixing bug found in QA Bugbash - https://docs.google.com/spreadsheets/d/1WtMKBmJ8iu9JquFp-djVfRidhR5OQHeLiFlIYQzjWqc/edit#gid=286076765

**Use case:**
- A user invited manually to CG and then added via SCIM in NG
- Now delete user from NG SCIM via SCIM provider.
- User should not show up in NG UI. IT should be visible in CG UI only.
- Due to bug user was still showing in NG UI.

**Testing:**
- Replicated exact steps mentioned above in local and NG deletion was as expected.
- Repeated same steps by adding/deleting the user directly via SCIM and via SCIM groups too.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48464)

### CODE REVIEW

**Review by diptiman-adak — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48464)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 223 at r1](https://reviewable.io/reviews/harness/harness-core/48464#-NWaoxma1anme8yCJBE0:-NWaoxma1anme8yCJBE1:b-e1czuy) ([raw file](https://github.com/harness/harness-core/blob/8c1dcfc875894425b5174593d7d95330009e7242/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L223)):*
> ```Java
>     log.info("NGSCIM: deleting for accountId {} the user {}", accountId, userId);
>     ngUserService.removeUserFromScope(userId, Scope.builder().accountIdentifier(accountId).build(),
>         UserMembershipUpdateSource.USER, NGRemoveUserFilter.ACCOUNT_LAST_ADMIN_CHECK);
> ```

Test comment

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48464)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
trigger uts

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48464)* status: :shipit: complete! ✓

**Comment by shashank-harness** [comment]
trigger messagecheck

**Pull request merged**
