### PR TITLE
fix: [CDS-41001]: Merging the variables for context elements

### PR DESCRIPTION
**Pull request by Y0709**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37176)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37176)

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37176)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/resume/ResumeStateUtils.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/37176#-NBTXOvV3YArOKQKucRy:-NBTXOvV3YArOKQKucRz:bume653) ([raw file](https://github.com/harness/harness-core/blob/c7f78cebb708e1b11073be0bf9f0ab6d63e7faa8/400-rest/src/main/java/software/wings/sm/resume/ResumeStateUtils.java#L90)):*
> ```Java
>               FeatureName.MERGE_RUNTIME_VARIABLES_IN_RESUME, stateExecutionInstance.getAccountId())) {
>         WorkflowStandardParams workflowStandardParams =
>             (WorkflowStandardParams) stateExecutionInstance.getContextElements()
> ```

null check here after get context element. (surrounded by EmptyifNull )
___
*[`400-rest/src/main/java/software/wings/sm/resume/ResumeStateUtils.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/37176#-NBTXd5tEmqMB5qaMmp6:-NBTXd5tEmqMB5qaMmp7:bwav65y) ([raw file](https://github.com/harness/harness-core/blob/c7f78cebb708e1b11073be0bf9f0ab6d63e7faa8/400-rest/src/main/java/software/wings/sm/resume/ResumeStateUtils.java#L107)):*
> ```Java
>   void mergeWorkflowElementVariables(ExecutionContext context, WorkflowStandardParams oldParams) {
>     WorkflowStandardParams currParams = context.getContextElement(ContextElementType.STANDARD);
>     oldParams.getWorkflowElement().getVariables().forEach((key, value) -> {
> ```

empty if null check here

**Review by hingerabhinav — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37176)* status: 3 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 439 at r3](https://reviewable.io/reviews/harness/harness-core/37176#-NBVSo3k3IKs2AZHK3jR:-NBVSo3k3IKs2AZHK3jS:b-q6s4w9) ([raw file](https://github.com/harness/harness-core/blob/8fb08e0db9d9ea83f9103e188c7e196219806329/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L439)):*
> ```Java
>       "merge context elements workflow variables while resuming pipeline from a stage", HarnessTeam.SPG),
>   NG_ARTIFACT_SOURCES("Flag to support multi artifact sources for service V2", HarnessTeam.CDC),
>   UPDATE_EMAILS_VIA_SCIM("Will enable updating emails in Harness via SCIM", HarnessTeam.PL);
> ```

since we're persisting these enums, better to add this at the end

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37176)* status: 3 file(s) to review. 3 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/resume/ResumeStateUtils.java` line 106 at r4](https://reviewable.io/reviews/harness/harness-core/37176#-NBW5Sqw6CD1GU-FZxQw:-NBW5Sqw6CD1GU-FZxQx:bd7fqx0) ([raw file](https://github.com/harness/harness-core/blob/2d6f8e2cee438750155bf7af457cc742ff607210/400-rest/src/main/java/software/wings/sm/resume/ResumeStateUtils.java#L106)):*
> ```Java
>   @VisibleForTesting
>   void mergeWorkflowElementVariables(ExecutionContext context, WorkflowStandardParams oldParams) {
>     WorkflowStandardParams currParams = context.getContextElement(ContextElementType.STANDARD);
> ```

Does updating stateExecutionInstance in context, eventually gets updated in database for follow up stateExecutionInstance to get this data? Could you point where we are doing that?

In software.wings.sm.StateMachineExecutor#updateStateExecutionData(software.wings.sm.StateExecutionInstance, software.wings.sm.StateExecutionData, io.harness.beans.ExecutionStatus, java.lang.String, java.util.Collection<io.harness.beans.ExecutionStatus>, java.util.List<software.wings.sm.ContextElement>, java.util.List<software.wings.sm.ContextElement>, java.lang.String),
I see we update contextElements only if contextElements are returned in execution response. So, fix would not work right?

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37176)* status: 3 file(s) to review. 3 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/resume/ResumeStateUtils.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/37176#-NBTXOvV3YArOKQKucRy:-NBWghiZ0GIBB3YrejKb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c7f78cebb708e1b11073be0bf9f0ab6d63e7faa8/400-rest/src/main/java/software/wings/sm/resume/ResumeStateUtils.java#L90)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

null check here after get context element. (surrounded by EmptyifNull )
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/sm/resume/ResumeStateUtils.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/37176#-NBTXd5tEmqMB5qaMmp6:-NBWh1IyBrx0IWukN2L_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c7f78cebb708e1b11073be0bf9f0ab6d63e7faa8/400-rest/src/main/java/software/wings/sm/resume/ResumeStateUtils.java#L107)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

empty if null check here
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/sm/resume/ResumeStateUtils.java` line 106 at r4](https://reviewable.io/reviews/harness/harness-core/37176#-NBW5Sqw6CD1GU-FZxQw:-NBWgjezBzWwbplGnZ35:b8kntmj) ([raw file](https://github.com/harness/harness-core/blob/2d6f8e2cee438750155bf7af457cc742ff607210/400-rest/src/main/java/software/wings/sm/resume/ResumeStateUtils.java#L106)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Does updating stateExecutionInstance in context, eventually gets updated in database for follow up stateExecutionInstance to get this data? Could you point where we are doing that?

In software.wings.sm.StateMachineExecutor#updateStateExecutionData(software.wings.sm.StateExecutionInstance, software.wings.sm.StateExecutionData, io.harness.beans.ExecutionStatus, java.lang.String, java.util.Collection<io.harness.beans.ExecutionStatus>, java.util.List<software.wings.sm.ContextElement>, java.util.List<software.wings.sm.ContextElement>, java.lang.String),
I see we update contextElements only if contextElements are returned in execution response. So, fix would not work right?
</blockquote></details>

The stateExecutionInstance of nextState is getting updated as we are updating the context and for resume the will always next state
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 439 at r3](https://reviewable.io/reviews/harness/harness-core/37176#-NBVSo3k3IKs2AZHK3jR:-NBWh2Qa8njDUx-eY8Li:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8fb08e0db9d9ea83f9103e188c7e196219806329/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L439)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

since we're persisting these enums, better to add this at the end
</blockquote></details>

Done.

**Review by inderschera — DISMISSED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37176)* status: 2 change requests. 3. unresolved discussions.

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37176)* status: 1 change requests. 2. unresolved discussions.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37176)* status: :shipit: complete! ✓

**Pull request merged**
