### PR TITLE
feat: [CDS-41347]: Update go-template to v0.4.1

### PR DESCRIPTION
**Pull request by akhilpandey1**
Updated go-template from 0.4.0 to 0.4.1, as previous version was based on 1.16.4 go-lang version which had open critical CVEs, updated the build with go-lang version 1.17.9 which has fixed these

Updated all the places 0.4 version was used to 0.4.1

Did not keep 0.4 anymore in the codebase as it has security vulnerabilities so we'll be deprecating it but backward compatibility should be maintained as we're not deleting it from GCS/CDN

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36147)

### CODE REVIEW

**Comment by akhilpandey1** [comment]
trigger feature-build

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36147)

**Comment by akhilpandey1** [comment]
trigger feature-build

**Comment by akhilpandey1** [comment]
trigger feature-build

**Comment by akhilpandey1** [comment]
trigger feature-build

**Comment by akhilpandey1** [comment]
trigger feature-build

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36147)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36147)* status: :shipit: complete! ✓

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36147)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36147)* status: :shipit: complete! ✓

**Comment by akhilpandey1** [comment]
trigger feature-build

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36147)* status: :shipit: complete! ✓

___
*[`960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/36147#-N976uu49CvyBjBBCgfy:-N976uu56lsRZrnz01AS:b-rtflgd) ([raw file](https://github.com/harness/harness-core/blob/2afcac65bdfbebf9756a112f5c5f2b07ebfdca51/960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java#L50)):*
> ```Java
>   @Override
>   public String getGoTemplateClientPath() {
>     return getToolPath(GO_TEMPLATE, GoTemplateVersion.V0_4_1);
> ```

Hey @akhilpandey1  this is not backwards compatible change for legacy delegates, so we can’t take it in this form (it’s OK for immutable where image tag and delegate version are coupled, but not for legacy as image tag and delegate.jar are released separately). 
This means that if you have a new delegate image, but older delegate version, goTemplate path will fail (it will look for old go-template binary) and vice versa for old image but new delegate version would fail as well. 
What you should do for now is add extra logic when you ask for the goTemplate path. Ask first for new version, if that fails, fallback to old version. This also means keeping the both versions in the enum. 
We should look into how to make these upgrades backwards compatible for the future if possible.

**Comment by mdmilic** [comment]
I don't know why reviewable says it's approved since I added a blocking comment, but please don't merge before fixing this.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36147)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36147)* status: 1 change requests. Waiting on team(s): sto.

**Review by mdmilic — DISMISSED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36147)* status: Waiting on team(s): sto.

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36147)* status: Waiting on team(s): sto.

**Comment by akhilpandey1** [comment]
trigger messagecheck

**Comment by akhilpandey1** [comment]
trigger messagecheck

**Comment by akhilpandey1** [comment]
trigger messagecheck

**Comment by akhilpandey1** [comment]
*[`960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/36147#-N976uu49CvyBjBBCgfy:-N9IHoux3wCR2msheBmG:b-fiknaj) ([raw file](https://github.com/harness/harness-core/blob/2afcac65bdfbebf9756a112f5c5f2b07ebfdca51/960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java#L50)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Hey @akhilpandey1  this is not backwards compatible change for legacy delegates, so we can’t take it in this form (it’s OK for immutable where image tag and delegate version are coupled, but not for legacy as image tag and delegate.jar are released separately). 
This means that if you have a new delegate image, but older delegate version, goTemplate path will fail (it will look for old go-template binary) and vice versa for old image but new delegate version would fail as well. 
What you should do for now is add extra logic when you ask for the goTemplate path. Ask first for new version, if that fails, fallback to old version. This also means keeping the both versions in the enum. 
We should look into how to make these upgrades backwards compatible for the future if possible. 
</blockquote></details>

This is fixed now, as we'll return older one when 4.0.1 not available

**Pull request merged**
