### PR TITLE
feat: [SRM-12406]: SLO consumption breakdown table view

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40249)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40249)* status: 6 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLOHealthListView.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/40249#-NH2oZrO4S-LEN8res3j:-NH2oZrPBLvnAKa6bDZV:b-bloq5p) ([raw file](https://github.com/harness/harness-core/blob/d0d11c4b6d201923b2bf355ee60e49c789647a20/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLOHealthListView.java#L25)):*
> ```Java
>   @NotNull String sloIdentifier;
>   @NotNull String name;
>   String orgIdentifier;
> ```

Lets make these changes with account level compatibility changes
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 793 at r2](https://reviewable.io/reviews/harness/harness-core/40249#-NH2ouVn5d9HBdeOGJ1j:-NH2ouVn5d9HBdeOGJ1k:bnszp27) ([raw file](https://github.com/harness/harness-core/blob/d0d11c4b6d201923b2bf355ee60e49c789647a20/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L793)):*
> ```Java
> 
>   private List<AbstractServiceLevelObjective> getSLOsAssociatedWithCompositeSLO(
>       List<ServiceLevelObjectivesDetail> serviceLevelObjectivesDetailList,
> ```

Should have a valudation that the identifier is from compsote SLO only

**Review by karansaraswat19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40249)* status: 6 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 793 at r2](https://reviewable.io/reviews/harness/harness-core/40249#-NH2ouVn5d9HBdeOGJ1j:-NH2qmLb989pv1gQSK_0:b-kgz4lb) ([raw file](https://github.com/harness/harness-core/blob/d0d11c4b6d201923b2bf355ee60e49c789647a20/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L793)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Should have a valudation that the identifier is from compsote SLO only
</blockquote></details>

this function is being called in getResponse which is being called in getSLOForListView where composite slo validation is being done

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40249#-:-NH31AtbAii8vtxGpo2k:bnfp4nl)* status: 1 change requests. 1. unresolved discussions.

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40249)* status: 1 change requests. 1. unresolved discussions. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODashboardWidget.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/40249#-NH3ZMR96mSBYzoSay_Q:-NH3ZMR96mSBYzoSay_R:bvojvo5) ([raw file](https://github.com/harness/harness-core/blob/d0d11c4b6d201923b2bf355ee60e49c789647a20/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODashboardWidget.java#L87)):*
> ```Java
>     boolean isRecalculatingSLI;
>     boolean isCalculatingSLI;
>     int errorBudgetBurned;
> ```

@JsonIgnore
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLOHealthListView.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/40249#-NH3NScN7pgXr2-6OwsZ:-NH3NScN7pgXr2-6Ows_:be0pyut) ([raw file](https://github.com/harness/harness-core/blob/d0d11c4b6d201923b2bf355ee60e49c789647a20/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLOHealthListView.java#L45)):*
> ```Java
>   @NotNull SLOTargetType sloTargetType;
>   ServiceLevelIndicatorType sliType;
>   String sliIdentifier;
> ```

if this is purely for internal use we can add @Jsonignore

**Review by deepak-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40249)* status: :shipit: complete! ✓

**Pull request merged**
