### PR TITLE
feat: [PL-31870]: Changed token list api to return all tokens 

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
changes in list token api-
 1. currently it has apikeyId and parentId as mandatory fields, we will make them optional fields
-  if someone passes only parentId - it will list all the tokens of that user for that scope based on apikey type(PAT or SAT)
- if someone passes only apikeyId - we will throw error that parentId is also required.
- if both fields are not passed - it will list all the tokens for that scope based on apikey type(PAT or SAT)
2. we will add one optional boolean field to list only active tokens

These are the permission checks - 
apikeyId and parentId both present - 
 - for PAT - check if user has USER Management permission or if its loggedIn user
 - for SAT - check if user has SA Management permission

apikeyId and parentId both are not present - 
 - for PAT - check if user has USER Management permission
 - for SAT - check if user has SA Management permission

if only parentId is present - 
 - for PAT - check if user has USER Management permission or if its loggedIn user
 - for SAT - check if user has SA Management permission

if only apikeyId is present - 
	throw error that we require parentId
	
Tests - 
1. list all users PATs with core_user_management permission 
2. list all users PATs without core_user_management permission - throwing Access Denied exception
3. list own PATs with/without core_user_management permission
4. list another user's PAT with core_user_management permission
5. list another user's PAT without core_user_management permission - throwing unauthorized exception
6. list all SATs with core_service_account_management permission
7. list all SATs without core_service_account_management permission - throwing Access denied exception
8. list one SA's SATs with core_service_account_management permission

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48650)

### CODE REVIEW

**Comment by Jimit09Gandhi** [comment]
trigger messagecheck

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48650)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java` line 242 at r1](https://reviewable.io/reviews/harness/harness-core/48650#-NWr1nIRBQ5ioJJTv5HQ:-NWr1nIRBQ5ioJJTv5HR:bqcrau) ([raw file](https://github.com/harness/harness-core/blob/05b37eac09853947f97793d16973e1c9caac89ad/120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java#L242)):*
> ```Java
>       @QueryParam("includeOnlyActiveTokens") boolean includeOnlyActiveTokens) {
>     if (isNotEmpty(apiKeyIdentifier) && isEmpty(parentIdentifier)) {
>       throw new InvalidRequestException("Need to pass parentId along with apikeyId to list the tokens.");
> ```

Change to "Need to pass parentIdentifier along with apiKeyIdentifier to list the tokens."

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48650)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java` line 361 at r1](https://reviewable.io/reviews/harness/harness-core/48650#-NWr9iHb29n8VQkOvyWg:-NWr9iHb29n8VQkOvyWh:bjqpoep) ([raw file](https://github.com/harness/harness-core/blob/05b37eac09853947f97793d16973e1c9caac89ad/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L361)):*
> ```Java
> 
>     if (filterDTO.isIncludeOnlyActiveTokens()) {
>       criteria.and(TokenKeys.validFrom).lte(Instant.now());
> ```

Is it possible to create tokens which can be activated with future date?

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48650)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java` line 427 at r1](https://reviewable.io/reviews/harness/harness-core/48650#-NWrB1K48YwCBiUu8I3S:-NWrB1K48YwCBiUu8I3T:bech33d) ([raw file](https://github.com/harness/harness-core/blob/05b37eac09853947f97793d16973e1c9caac89ad/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L427)):*
> ```Java
>     accessControlClient.checkForAccessOrThrow(ResourceScope.of(filterDTO.getAccountIdentifier(),
>                                                   filterDTO.getOrgIdentifier(), filterDTO.getProjectIdentifier()),
>         Resource.of(PlatformResourceTypes.USER, filterDTO.getParentIdentifier()), MANAGE_USER_PERMISSION);
> ```

Passing parentIdentifier for MANAGE_USER_PERMISSION wont be valid and will always return false.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48650)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java` line 405 at r1](https://reviewable.io/reviews/harness/harness-core/48650#-NWrF4xJEew-TwV3Y5GM:-NWrF4xJEew-TwV3Y5GN:b7e2hgh) ([raw file](https://github.com/harness/harness-core/blob/05b37eac09853947f97793d16973e1c9caac89ad/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L405)):*
> ```Java
>     switch (filterDTO.getApiKeyType()) {
>       case USER:
>         try {
> ```

Add Unit Tests to cover all cases.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48650)* status: 5 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java` line 361 at r1](https://reviewable.io/reviews/harness/harness-core/48650#-NWr9iHb29n8VQkOvyWg:-NXyFUS5EOzRKqZaxXe6:b-kz1dkm) ([raw file](https://github.com/harness/harness-core/blob/05b37eac09853947f97793d16973e1c9caac89ad/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L361)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Is it possible to create tokens which can be activated with future date?
</blockquote></details>

yes, we can pass validFrom as query parameter in create token api
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java` line 405 at r1](https://reviewable.io/reviews/harness/harness-core/48650#-NWrF4xJEew-TwV3Y5GM:-NXyF_CZ--qLOXv8fcN3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/05b37eac09853947f97793d16973e1c9caac89ad/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L405)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Add Unit Tests to cover all cases.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java` line 427 at r1](https://reviewable.io/reviews/harness/harness-core/48650#-NWrB1K48YwCBiUu8I3S:-NXyFaKJ-mpiw1EVSU6_:bze5tcw) ([raw file](https://github.com/harness/harness-core/blob/05b37eac09853947f97793d16973e1c9caac89ad/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L427)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Passing parentIdentifier for MANAGE_USER_PERMISSION wont be valid and will always return false.
</blockquote></details>

I have checked its working fine, for admin its returing true
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java` line 242 at r1](https://reviewable.io/reviews/harness/harness-core/48650#-NWr1nIRBQ5ioJJTv5HQ:-NXyFhYQEOJI5bBZAHIn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/05b37eac09853947f97793d16973e1c9caac89ad/120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java#L242)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Change to "Need to pass parentIdentifier along with apiKeyIdentifier to list the tokens."
</blockquote></details>

Done.

**Comment by bhavya181** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48650)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java` line 470 at r8](https://reviewable.io/reviews/harness/harness-core/48650#-NYOBvHK06CdsM3q15vt:-NYOBvHK06CdsM3q15vu:b-24hey2) ([raw file](https://github.com/harness/harness-core/blob/9652dca45d1361ba4a12058c7d8917144a71cd54/120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java#L470)):*
> ```Java
>     SourcePrincipalContextBuilder.setSourcePrincipal(principal);
>     tokenService.validateTokenListPermissions(tokenFilterDTO);
>     verify(accessControlClient, times(1)).checkForAccessOrThrow(any(), any(), any());
> ```

There is nothing we are asserting or checking in this test. We need to mock access check and say User Managment is allowed and then validate action.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48650)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java` line 483 at r8](https://reviewable.io/reviews/harness/harness-core/48650#-NYOCBrzBnUqZJaZvsZT:-NYOCBrzBnUqZJaZvsZU:bj8bld6) ([raw file](https://github.com/harness/harness-core/blob/9652dca45d1361ba4a12058c7d8917144a71cd54/120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java#L483)):*
> ```Java
>     SourcePrincipalContextBuilder.setSourcePrincipal(principal);
>     tokenService.validateTokenListPermissions(tokenFilterDTO);
>     verify(accessControlClient, times(1)).checkForAccessOrThrow(any(), any(), any());
> ```

same as above.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48650)* status: 6 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java` line 457 at r8](https://reviewable.io/reviews/harness/harness-core/48650#-NYOBQvAAf9D7AlqIq2h:-NYS53fF1hoD3qnhFs7t:b-w7y1zr) ([raw file](https://github.com/harness/harness-core/blob/9652dca45d1361ba4a12058c7d8917144a71cd54/120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java#L457)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

There is nothing we are asserting or checking in this test.
</blockquote></details>

this is checking whole flow of loggedInUserCheck
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java` line 470 at r8](https://reviewable.io/reviews/harness/harness-core/48650#-NYOBvHK06CdsM3q15vt:-NYS5S0qCpIE-XpX5vqB:b4nq1zf) ([raw file](https://github.com/harness/harness-core/blob/9652dca45d1361ba4a12058c7d8917144a71cd54/120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java#L470)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

There is nothing we are asserting or checking in this test. We need to mock access check and say User Managment is allowed and then validate action.
</blockquote></details>

this method just calls accessControlCheck, if we mock and sends result, what will this test check?
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java` line 483 at r8](https://reviewable.io/reviews/harness/harness-core/48650#-NYOCBrzBnUqZJaZvsZT:-NYS7m8d3SVpUWoWHO-H:b4nq1zf) ([raw file](https://github.com/harness/harness-core/blob/9652dca45d1361ba4a12058c7d8917144a71cd54/120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java#L483)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

this method just calls accessControlCheck, if we mock and sends result, what will this test check?

**Comment by bhavya181** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48650)* status: Some of the checks are too old. 6 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java` line 470 at r8](https://reviewable.io/reviews/harness/harness-core/48650#-NYOBvHK06CdsM3q15vt:-NYqh21WBkLH8407z0a7:b-b2b0no) ([raw file](https://github.com/harness/harness-core/blob/9652dca45d1361ba4a12058c7d8917144a71cd54/120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java#L470)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

this method just calls accessControlCheck, if we mock and sends result, what will this test check?
</blockquote></details>

Test says User has permission but checking for user doesnt have permission.
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java` line 483 at r8](https://reviewable.io/reviews/harness/harness-core/48650#-NYOCBrzBnUqZJaZvsZT:-NYqfkcQ8_7K_1BCKwPi:b-kmxif0) ([raw file](https://github.com/harness/harness-core/blob/9652dca45d1361ba4a12058c7d8917144a71cd54/120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java#L483)):*
> this method just calls accessControlCheck, if we mock and sends result, what will this test check?

Test says User has permission but checking for user doesnt have permission.
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java` line 471 at r9](https://reviewable.io/reviews/harness/harness-core/48650#-NYqgaHM4Pb2AMHtWMxC:-NYqgaHM4Pb2AMHtWMxD:b48uhgd) ([raw file](https://github.com/harness/harness-core/blob/bb0998fb8058bd34068e2d444ed3f8b33885762d/120-ng-manager/src/test/java/io/harness/ng/core/api/impl/TokenServiceImplTest.java#L471)):*
> ```Java
>     // when parentId is different
>     tokenFilterDTO.setParentIdentifier("test");
>     when(ngUserService.getUserById(anyString())).thenReturn(userInfo);
> ```

Split this into multiple UTs. A single UT should focus on one test case.

**Comment by bhavya181** [comment]
trigger uts

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48650)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java` line 427 at r1](https://reviewable.io/reviews/harness/harness-core/48650#-NWrB1K48YwCBiUu8I3S:-NYrN957BAQzdzjzo24y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/05b37eac09853947f97793d16973e1c9caac89ad/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L427)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

We shouldn't check Manager User per user as Manage User permission is across scope so pass null for resourceIdentifier. 
</blockquote></details>

Done.

**Comment by bhavya181** [comment]
trigger uts

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 4 files at r3, 1 of 2 files at r6, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48650)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by bhavya181** [comment]
trigger uts

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48650)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
