### PR TITLE
fix: [CDS-58532]: Identifier based RBAC for Templates LIST Page

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
Filter templates based on RBAC for LIST API
Currently, the list API checks if the user has permission to view templates at that scope. It does not check for RBAC on individual template objects. This PR adds that support

For eg. If a user has access to view just 1 template out of 10 in a project, they are expected to see just 1 template on the list page

This change only applies to template list call and not to templates list metadata call

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46013)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 545 at r2](https://reviewable.io/reviews/harness/harness-core/46013#-NSFkL_H8aFSkkDdI-2B:-NSFkL_H8aFSkkDdI-2C:by3p2d) ([raw file](https://github.com/harness/harness-core/blob/56743c9092a0687a488e667737e22cace9788af7/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L545)):*
> ```Java
>       @QueryParam("getDistinctFromBranches") boolean getDistinctFromBranches) {
>     accessControlClient.checkForAccessOrThrow(ResourceScope.of(accountIdentifier, orgIdentifier, projectIdentifier),
>         Resource.of(TEMPLATE, null), PermissionTypes.TEMPLATE_VIEW_PERMISSION);
> ```

I think this should not be removed

**Review by utkarshchoubey-harness — DISMISSED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46013)* status: Some of the checks are too old. 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1503 at r3](https://reviewable.io/reviews/harness/harness-core/46013#-NTNNYAY3p_WfwlET3Ji:-NTNNYAY3p_WfwlET3Jj:bglbo8r) ([raw file](https://github.com/harness/harness-core/blob/41fbfce2c2db330f480841ea4496a9d5ef861386/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1503)):*
> ```Java
>         return Page.empty();
>       }
> ```

nit: lets not add a new line between each statement

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/TemplateRbacHelper.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/46013#-NTNNcSN95WFkaZuIicV:-NTNNcSN95WFkaZuIicW:bnddwh0) ([raw file](https://github.com/harness/harness-core/blob/41fbfce2c2db330f480841ea4496a9d5ef861386/840-template-service/src/main/java/io/harness/template/services/TemplateRbacHelper.java#L30)):*
> ```Java
> import java.util.function.Function;
> import java.util.stream.Collectors;
> ```

can be a Singleton

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46013)* status: :shipit: complete! ✓

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46013)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46013#-:-NTO67ZQBBQX1rjlUNfI:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46013)* status: :shipit: complete! ✓

**Comment by vivekkarnatiharness** [comment]
trigger review

**Pull request merged**
