### PR TITLE
[feat]:[pl-26997]: Integrate LIST Template Flow with GitX

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Integrate LIST Template Flow with GitX
The following flows have been tested out:
1. GitX with Inline 
2. GitX with Remote 
3. Old GitSync
4. Non git enabled project

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35760)

### CODE REVIEW

**Review by inderschera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35760)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateService.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/35760#-N84AvDRASs81fty64yF:-N84AvDU8BNy0VLtM-CP:bu0lr98) ([raw file](https://github.com/harness/harness-core/blob/da090bcfb0107d12ad5222332fd3bd8242544156/840-template-service/src/main/java/io/harness/template/services/NGTemplateService.java#L43)):*
> ```Java
>       Set<String> templateVersions, String comments);
> 
>   Page<TemplateEntity> list(Criteria criteria, Pageable pageable, String accountId, String orgIdentifier,
> ```

Should we just rename this method to listTemplateMetadata? Essentially it's doing the same thing as newly created method.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87iq-w6MYoz87vJjF3:-N87iq-w6MYoz87vJjF4:beh2xze) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java#L71)):*
> ```Java
> 
>   Page<TemplateEntity> findAllMetadata(
>       Criteria criteria, Pageable pageable, String accountIdentifier, String orgIdentifier, String projectIdentifier);
> ```

Lets always keep the scope arguments as the first arguments and all other arguments follow them.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 345 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87izYB9CzgueKDxgM6:-N87izYCBMZPGUm4s-2n:b3owfai) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L345)):*
> ```Java
> 
>   @Override
>   public Page<TemplateEntity> findAllMetadata(
> ```

I think we can simpy call it findAll() method itself. Its understood going forward that it will only fetch data from Db and yaml won't be a part of it.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 345 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87izYB9CzgueKDxgM6:-N87j6Hj7ipoSQVATAB0:b3se720) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L345)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we can simpy call it findAll() method itself. Its understood going forward that it will only fetch data from Db and yaml won't be a part of it. 
</blockquote></details>

Also, for INLINE templates, yaml is a part and method name suggests otherwise.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 114 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87mfxg3miDxppol1nM:-N87mfxg3miDxppol1nN:b-8fzhsy) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L114)):*
> ```Java
>         .gitDetails(getEntityGitDetails(templateEntity))
>         .lastUpdatedAt(templateEntity.getLastUpdatedAt())
>         .entityValidityDetails(templateEntity.isEntityInvalid()
> ```

not required with new gitx, so lets remove it



_Code quote:_
```Java
        .entityValidityDetails(templateEntity.isEntityInvalid()
                ? EntityValidityDetails.builder().valid(false).invalidYaml(templateEntity.getYaml()).build()
                : EntityValidityDetails.builder().valid(true).build())
```

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 444 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87mkgd4FDAVUbpnJ6X:-N87mkgd4FDAVUbpnJ6Y:bpydlst) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L444)):*
> ```Java
> 
>   @POST
>   @Path("/listMetadata")
> ```

it should be "list-meta-data"

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 444 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87mkgd4FDAVUbpnJ6X:-N87n3t96bWApCu6oTTx:b2zah7k) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L444)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

it should be "list-meta-data"
</blockquote></details>

add @Hidden to hide it from customers api spec

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 457 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87nXOz3JmERnJGAqbg:-N87nXOz3JmERnJGAqbh:bvebkco) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L457)):*
> ```Java
>                            NGCommonEntityConstants.ACCOUNT_KEY) @AccountIdentifier String accountId,
>       @Parameter(description = NGCommonEntityConstants.ORG_PARAM_MESSAGE) @QueryParam(
>           NGCommonEntityConstants.ORG_KEY) @OrgIdentifier String orgId,
> ```

orgIdentifier

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 459 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87nZY7BVvoCaSHyG8E:-N87nZY7BVvoCaSHyG8F:b-o4ud37) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L459)):*
> ```Java
>           NGCommonEntityConstants.ORG_KEY) @OrgIdentifier String orgId,
>       @Parameter(description = NGCommonEntityConstants.PROJECT_PARAM_MESSAGE) @QueryParam(
>           NGCommonEntityConstants.PROJECT_KEY) @ProjectIdentifier String projectId,
> ```

projectIdentifier

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 455 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87n_f212ohifDwkdNl:-N87n_f212ohifDwkdNm:bbt4mhe) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L455)):*
> ```Java
>   public ResponseDTO<Page<TemplateMetadataSummaryResponseDTO>>
>   listTemplateMetadata(@Parameter(description = NGCommonEntityConstants.ACCOUNT_PARAM_MESSAGE) @NotNull @QueryParam(
>                            NGCommonEntityConstants.ACCOUNT_KEY) @AccountIdentifier String accountId,
> ```

accountIdentifer

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 482 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87ngQ74x-K60m3qjlK:-N87ngQ74x-K60m3qjlL:b-2ksx5s) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L482)):*
> ```Java
>         Resource.of(TEMPLATE, null), PermissionTypes.TEMPLATE_VIEW_PERMISSION);
>     log.info(String.format("Get List of templates in project: %s, org: %s, account: %s", projectId, orgId, accountId));
>     Criteria criteria = templateServiceHelper.formCriteria(accountId, orgId, projectId, filterIdentifier,
> ```

as discussed, we will move criteria from here.

**Comment by mohitg0795** [comment]
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateMetadataSummaryResponseDTO.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87nvAACKypyxxAxfoT:-N87nvAACKypyxxAxfoU:b-qs95cx) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateMetadataSummaryResponseDTO.java#L29)):*
> ```Java
> @OwnedBy(CDC)
> public class TemplateMetadataSummaryResponseDTO {
>   @NotEmpty String accountId;
> ```

annotation not required. also "accountIdentifier"

**Comment by mohitg0795** [comment]
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateMetadataSummaryResponseDTO.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87o5rhAXjj4KZ-LbfO:-N87o5rhAXjj4KZ-LbfP:b-6w5ehp) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateMetadataSummaryResponseDTO.java#L40)):*
> ```Java
> 
>   String versionLabel;
>   boolean isStableTemplate;
> ```

Boolean

**Comment by mohitg0795** [comment]
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateMetadataSummaryResponseDTO.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87oAbLBAfMf43CcykP:-N87oAbLBAfMf43CcykQ:b-ki8jgq) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateMetadataSummaryResponseDTO.java#L46)):*
> ```Java
> 
>   Scope templateScope;
>   Long version;
> ```

Everything should be either Long or long.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35760)* status: 9 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87iq-w6MYoz87vJjF3:-N87xagvA5qxAqvyl9CS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java#L71)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets always keep the scope arguments as the first arguments and all other arguments follow them.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 345 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87izYB9CzgueKDxgM6:-N87xZOFEBK4OTlgyjmx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L345)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Also, for INLINE templates, yaml is a part and method name suggests otherwise.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 114 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87mfxg3miDxppol1nM:-N87s1sH192MOVIrR1HK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L114)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

not required with new gitx, so lets remove it
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 455 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87n_f212ohifDwkdNl:-N87wkIg9dL3NlN0rqel:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L455)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

accountIdentifer
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 457 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87nXOz3JmERnJGAqbg:-N87wkgx9bIbRw8XRYZp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L457)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

orgIdentifier
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 459 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87nZY7BVvoCaSHyG8E:-N87wl2NDgp5jQ8zzGEu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L459)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

projectIdentifier
</blockquote></details>

Done.
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateMetadataSummaryResponseDTO.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87nvAACKypyxxAxfoT:-N87sicF7mVjdpSOcsBx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateMetadataSummaryResponseDTO.java#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

annotation not required. also "accountIdentifier"
</blockquote></details>

Done.
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateMetadataSummaryResponseDTO.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87o5rhAXjj4KZ-LbfO:-N87s3DlAmCIkXLO2Yvq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateMetadataSummaryResponseDTO.java#L40)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Boolean
</blockquote></details>

Done.
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateMetadataSummaryResponseDTO.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87oAbLBAfMf43CcykP:-N87s2ixCw0yfRiHhHN7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateMetadataSummaryResponseDTO.java#L46)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Everything should be either Long or long.
</blockquote></details>

Done.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35760)* status: 9 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87iq-w6MYoz87vJjF3:-N893G8w8ZzSvs5FdodV:bn844h3) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java#L71)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There is no need of writing findAllV2, if it has different arguments, then findAll will be good

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35760)* status: 12 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87iq-w6MYoz87vJjF3:-N8MXN4e7f44_ErF0yyj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java#L71)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

There is no need of writing findAllV2, if it has different arguments, then findAll will be good
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 444 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87mkgd4FDAVUbpnJ6X:-N88FBne3aNJ74WqYACB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L444)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

add @Hidden to hide it from customers api spec
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 482 at r2](https://reviewable.io/reviews/harness/harness-core/35760#-N87ngQ74x-K60m3qjlK:-N8Mn6v2E6E4digULBUl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2573ac680c02f00c2ae54bee8b15e81558937a20/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L482)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

as discussed, we will move criteria from here.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateService.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/35760#-N84AvDRASs81fty64yF:-N88HA1hC4Md0bc8anNI:b-1y5z9j) ([raw file](https://github.com/harness/harness-core/blob/da090bcfb0107d12ad5222332fd3bd8242544156/840-template-service/src/main/java/io/harness/template/services/NGTemplateService.java#L43)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Should we just rename this method to listTemplateMetadata? Essentially it's doing the same thing as newly created method.
</blockquote></details>

I feel, we should keep it as it as cause we are fetching the yaml from git

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 490 at r5](https://reviewable.io/reviews/harness/harness-core/35760#-N8NBR868iXLup-CRHMY:-N8NBR868iXLup-CRHMZ:b-wnyhx4) ([raw file](https://github.com/harness/harness-core/blob/89a001800e360d2a373f5871c2be94fccfabbd2b/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L490)):*
> ```Java
>     PageParamsDTO pageParamsDTO = NGTemplateDtoMapper.preparePageParamsDTO(page, size, sort);
> 
>     Criteria criteria = templateServiceHelper.formCriteria(accountIdentifier, orgIdentifier, projectIdentifier,
> ```

criteria not removed?

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* Code issue 5 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35760)

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 6 of 11 files at r4, 1 of 3 files at r5, 3 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35760)* status: 1 change requests. 1. unresolved discussions.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 6 of 11 files at r4, 1 of 3 files at r5, 3 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35760)* status: 1 change requests. 1. unresolved discussions.

**Review by bhavya181 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35760)* status: 1 change requests. 1. unresolved discussions.

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r4, 1 of 3 files at r5, 3 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35760)* status: :shipit: complete! ✓

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 441 at r7](https://reviewable.io/reviews/harness/harness-core/35760#-N8XNyV217dFSvDOi5AT:-N8XNyV217dFSvDOi5AU:b-byyi3l) ([raw file](https://github.com/harness/harness-core/blob/d3f2e52c379a0638b0aae6006359eb0b4453504b/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L441)):*
> ```Java
> 
>     Page<TemplateSummaryResponseDTO> templateSummaryResponseDTOS =
>         templateService.list(criteria, pageRequest, accountId, orgId, projectId, getDistinctFromBranches)
> ```

Let's call listTemplateMetadata from here as well. For older git experience, anyhow we should get the correct yaml
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateService.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/35760#-N84AvDRASs81fty64yF:-N8XNnCR2-9hSEPX-Q2B:bdiguac) ([raw file](https://github.com/harness/harness-core/blob/da090bcfb0107d12ad5222332fd3bd8242544156/840-template-service/src/main/java/io/harness/template/services/NGTemplateService.java#L43)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

I feel, we should keep it as it as cause we are fetching the yaml from git
</blockquote></details>

As discussed, let's remove this since this create confusion that list call will return everything with yaml for newer git experience as well.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateService.java` line 48 at r7](https://reviewable.io/reviews/harness/harness-core/35760#-N8XOS0k3edZVjhSUCv0:-N8XOS0l9nKYet2btLjh:bka0xkk) ([raw file](https://github.com/harness/harness-core/blob/d3f2e52c379a0638b0aae6006359eb0b4453504b/840-template-service/src/main/java/io/harness/template/services/NGTemplateService.java#L48)):*
> ```Java
>       String projectIdentifier, Boolean getDistinctFromBranches);
> 
>   Page<TemplateEntity> listTemplateMetadata(String accountIdentifier, String orgIdentifier, String projectIdentifier,
> ```

This api should handle for both older and newer git experience.

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35760)* status: :shipit: complete! ✓

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 399 at r7](https://reviewable.io/reviews/harness/harness-core/35760#-N8XP-YjDMXlbYRbOie-:-N8XP-YjDMXlbYRbOie0:bp9cr9d) ([raw file](https://github.com/harness/harness-core/blob/d3f2e52c379a0638b0aae6006359eb0b4453504b/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L399)):*
> ```Java
>   // will return non deleted templates only
>   public ResponseDTO<Page<TemplateSummaryResponseDTO>>
>   listTemplates(@Parameter(description = NGCommonEntityConstants.ACCOUNT_PARAM_MESSAGE) @NotNull @QueryParam(
> ```

This list api is also used internally by other microservices. Let's deprecate that and change those to newer API in next PR.

**Review by inderschera — APPROVED** [review]
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35760)* status: :shipit: complete! ✓

**Review by bhavya181 — APPROVED** [review]
> Reviewed 5 of 6 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35760)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 5 of 6 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35760)* status: :shipit: complete! ✓

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35760)* status: :shipit: complete! ✓

**Pull request merged**
