### PR TITLE
feat: [CDS-69493]: use ci execution resource image overrides for container step initialise

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
- feat: [CDS-69493]: Fetch CI Execution Image for container step
- feat: [CDS-69493]: Add clients/ci to BUILD.bazel
- fix: [CDS-69493]: Fix bug with API endpoint being incorrect

## Describe your changes
In the container initialise step, fetch customer's execution config from CI manager. If some config exists, use lite-engine and add-on image tag from that config, otherwise use the default config
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-69493]: https://harness.atlassian.net/browse/CDS-69493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-69493]: https://harness.atlassian.net/browse/CDS-69493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-69493]: https://harness.atlassian.net/browse/CDS-69493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48143)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStepInitHelper.java` line 212 at r1](https://reviewable.io/reviews/harness/harness-core/48143#-NW0dPB49N_7_dBtLyX6:-NW0dPB5EEoj2dUy5our:b-ekty0z) ([raw file](https://github.com/harness/harness-core/blob/55e5dc266e501408045906f144277eca5172bfce/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStepInitHelper.java#L212)):*
> ```Java
> 
>     CIK8ContainerParams setupAddOnContainerParams = getSetupAddOnContainerParams(
>         infrastructure, volumeToMountPath, os, ngAccess, harnessInternalImageConnector, StageInfraDetails.Type.K8);
> ```

I am passing infra type as k8s here since the flow looks like for k8s, @sahilhindwani-harness do we have flows for docker or any other flow for container step ?

**Comment by yogesh-chauhan** [comment]
trigger checkstylecodeformat

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStepInitHelper.java` line 212 at r1](https://reviewable.io/reviews/harness/harness-core/48143#-NW0dPB49N_7_dBtLyX6:-NW254n8DQZMpx4dzAB5:b-v5wakh) ([raw file](https://github.com/harness/harness-core/blob/55e5dc266e501408045906f144277eca5172bfce/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStepInitHelper.java#L212)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I am passing infra type as k8s here since the flow looks like for k8s, @sahilhindwani-harness do we have flows for docker or any other flow for container step ?
</blockquote></details>

Can we derive it from Infrastructure?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerParamsProvider.java` line 106 at r2](https://reviewable.io/reviews/harness/harness-core/48143#-NW25D9XCGM6P1WLWB__:-NW25D9XCGM6P1WLWB_a:bn63saw) ([raw file](https://github.com/harness/harness-core/blob/a9efb2c5f114f6e3c05bd79b118c530a8f07dabf/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerParamsProvider.java#L106)):*
> ```Java
>     try {
>       final Response<ResponseDTO<CIExecutionImages>> response =
>           ciServiceResourceClient.getCustomersExecutionConfig(infraType, true, accountIdentifier).execute();
> ```

Should we add a retry mechanism here?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerParamsProvider.java` line 123 at r2](https://reviewable.io/reviews/harness/harness-core/48143#-NW25XgR6cdSiJvmrcXN:-NW25XgR6cdSiJvmrcXO:bmoe7mj) ([raw file](https://github.com/harness/harness-core/blob/a9efb2c5f114f6e3c05bd79b118c530a8f07dabf/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerParamsProvider.java#L123)):*
> ```Java
>     } catch (IOException e) {
>       log.error(FAILED_TO_FETCH_CI_EXECUTION_CONFIG_MSG, e);
>       throw new InvalidRequestException(FAILED_TO_FETCH_CI_EXECUTION_CONFIG_MSG);
> ```

Should we not throw exception but rather log the error and fallback to default.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerParamsProvider.java` line 229 at r2](https://reviewable.io/reviews/harness/harness-core/48143#-NW25xUPBAWhRgdvIe-V:-NW25xUPBAWhRgdvIe-W:bqwszne) ([raw file](https://github.com/harness/harness-core/blob/a9efb2c5f114f6e3c05bd79b118c530a8f07dabf/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerParamsProvider.java#L229)):*
> ```Java
>   }
> 
>   private Optional<String> fetchOverridenLiteEngineImage(Ambiance ambiance, StageInfraDetails.Type infraType) {
> ```

Can we merge this and below to one request?

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48143)* status: 5 file(s) to review. 0 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerParamsProvider.java` line 229 at r2](https://reviewable.io/reviews/harness/harness-core/48143#-NW25xUPBAWhRgdvIe-V:-NW2e4Mp7ExJUm_Yd6Qz:bea2ux0) ([raw file](https://github.com/harness/harness-core/blob/a9efb2c5f114f6e3c05bd79b118c530a8f07dabf/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerParamsProvider.java#L229)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we merge this and below to one request?
</blockquote></details>

Moved to container init step helper

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerParamsProvider.java` line 123 at r2](https://reviewable.io/reviews/harness/harness-core/48143#-NW25XgR6cdSiJvmrcXN:-NW2G_MiC_nCtqHIkoJl:bfmsgt5) ([raw file](https://github.com/harness/harness-core/blob/a9efb2c5f114f6e3c05bd79b118c530a8f07dabf/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerParamsProvider.java#L123)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should we not throw exception but rather log the error and fallback to default.
</blockquote></details>

Discussed offline, we will just add re-try

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48143)* status: 6 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerParamsProvider.java` line 106 at r2](https://reviewable.io/reviews/harness/harness-core/48143#-NW25D9XCGM6P1WLWB__:-NW2gxIE2TMUiUVJGKBF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a9efb2c5f114f6e3c05bd79b118c530a8f07dabf/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerParamsProvider.java#L106)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should we add a retry mechanism here?
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48143)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 4 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48143)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
trigger review

**Pull request merged**
