### PR TITLE
feat: [CDS-57826]: Add kubernetes release functor

### PR DESCRIPTION
**Pull request by abosii-harness**
## Describe your changes
Adding `<+kubernetes.release.revision>` and `<+kubernetes.release.stageColor>` expressions. Value will be resolved to the proper placeholder.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46090)

### CODE REVIEW

**Comment by abosii-harness** [comment]
trigger feature-build

**Comment by abosii-harness** [comment]
trigger publish-delegate

**Review by GoelPratyush99 — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46090)* status: 3 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): k8s-team.

**Review by markoharness — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46090)* status: 4 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): k8s-team.

**Review by abhinavsingh1196 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46090)* status: 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 758 at r3](https://reviewable.io/reviews/harness/harness-core/46090#-NSPcVRA02_nE3o4ik6s:-NSPcVRB6ciV3Du2LLhW:bogl3vv) ([raw file](https://github.com/harness/harness-core/blob/50f070fcbaa1b2f3f4412ac996225ada8b752e22/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L758)):*
> ```Java
>     sdkFunctorMap.put(CONFIG_FILE_FUNCTOR, ConfigFileFunctor.class);
>     sdkFunctorMap.put(FILE_STORE_FUNCTOR, FileStoreFunctor.class);
>     sdkFunctorMap.put(FUNCTOR_NAME, KubernetesReleaseFunctor.class);
> ```

Can we name this KUBERNETES_RELEASE_FUNCTOR, this name is generic?

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46090)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by markoharness — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46090)* status: 4 file(s) to review.

**Comment by abosii-harness** [comment]
trigger messagecheck

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46090)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by lovish1999 — APPROVED** [review]
> Reviewed 2 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46090)* status: :shipit: complete! ✓

**Review by TarunUba1 — APPROVED** [review]
> Reviewed 2 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46090)* status: :shipit: complete! ✓

**Comment by abosii-harness** [comment]
trigger review

**Review by markoharness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46090)* status: :shipit: complete! ✓

**Pull request merged**
