### PR TITLE
techdebt: [DEL-4567]: Extract spring persistence layer in a module

### PR DESCRIPTION
**Pull request by hextechpal**
## Describe your changes

Have decoupled spring data module from persistence module. So that all the current gen stuff keep depending on morphia while the nextgen can depend on new spring data module.

Have also decoupled spring from morphia all together by removing the use of advanced datastore in config

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36182)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 19 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 12 Code issues 
* Anti-pattern 5 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36182)

**Comment by xingchi-jin** [comment]
trigger publish-delegate

**Review by xingchi-jin — APPROVED** [review]
have fixed checkstyle and a ti2 test, and  some sanity test has been done

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 34 of 195 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36182)* status: 178 file(s) to review. 1 change requests. Waiting on team(s): sto. 

___
*[`959-timeout-engine/src/main/java/io/harness/serializer/TimeoutEngineRegistrars.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/36182#-N955Hzr9VIUDFdX8UUB:-N955Hzs2bQYnumebK6d:b-rqq4uf) ([raw file](https://github.com/harness/harness-core/blob/8be0c5c34a6a24faafa93f32ea81e886ece3b36a/959-timeout-engine/src/main/java/io/harness/serializer/TimeoutEngineRegistrars.java#L35)):*
> ```Java
>           .add(TimeoutEngineMorphiaRegistrar.class)
>           .add(NgPersistenceMorphiaRegistrar.class)
>           .build();
> ```

shouldnt these registrars be added to each module where ng-persistence module is added in bazel, as direct register instead of indirect?



_Code quote:_
```Java
public class TimeoutEngineRegistrars {
  public static final ImmutableSet<Class<? extends KryoRegistrar>> kryoRegistrars =
      ImmutableSet.<Class<? extends KryoRegistrar>>builder()
          .add(TimeoutEngineKryoRegistrar.class)
          .add(NgPersistenceKryoRegistrar.class)
          .addAll(PersistenceRegistrars.kryoRegistrars)
          .build();

  public static final ImmutableSet<Class<? extends MorphiaRegistrar>> morphiaRegistrars =
      ImmutableSet.<Class<? extends MorphiaRegistrar>>builder()
          .addAll(PersistenceRegistrars.morphiaRegistrars)
          .add(TimeoutEngineMorphiaRegistrar.class)
          .add(NgPersistenceMorphiaRegistrar.class)
          .build();
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/waiter/PmsNotifyEventListener.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/36182#-N955U1d6S8ijpoGZEYx:-N955U1d6S8ijpoGZEYy:b6rd1r7) ([raw file](https://github.com/harness/harness-core/blob/8be0c5c34a6a24faafa93f32ea81e886ece3b36a/pipeline-service/modules/orchestration/src/main/java/io/harness/waiter/PmsNotifyEventListener.java#L43)):*
> ```Java
>   private static QueueConsumer<NotifyEvent> getNgQueueConsumer(
>       Injector injector, VersionInfoManager versionInfoManager, PublisherConfiguration config) {
>     return NgQueueFactory.createNgQueueConsumer(injector, NotifyEvent.class, ofSeconds(10),
> ```

Shouldnt we add ng-persistence module as direct dependency in bazel for this module?

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36182)* status: 178 file(s) to review. Waiting on team(s): sto. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/waiter/PmsNotifyEventListener.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/36182#-N955U1d6S8ijpoGZEYx:-N957Fd74zOXkDfR59_3:b-r03iba) ([raw file](https://github.com/harness/harness-core/blob/8be0c5c34a6a24faafa93f32ea81e886ece3b36a/pipeline-service/modules/orchestration/src/main/java/io/harness/waiter/PmsNotifyEventListener.java#L43)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Shouldnt we add ng-persistence module as direct dependency in bazel for this module?
</blockquote></details>

Discussed offline, will be taken care in next pr

**Comment by xingchi-jin** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/36182)_ status: 178 file(s) to review. Waiting on team(s): sto.
> 
> _[`pipeline-service/modules/orchestration/src/main/java/io/harness/waiter/PmsNotifyEventListener.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/36182#-N955U1d6S8ijpoGZEYx:-N957Fd74zOXkDfR59_3:b-r03iba) ([raw file](https://github.com/harness/harness-core/blob/8be0c5c34a6a24faafa93f32ea81e886ece3b36a/pipeline-service/modules/orchestration/src/main/java/io/harness/waiter/PmsNotifyEventListener.java#L43)):_
> 
> Previously, archit-harness (Archit Singla) wrote…
> Discussed offline, will be taken care in next pr

@archit-harness  If add in next PR, do we also need this addition in 762xx branch https://github.com/harness/harness-core/pull/36236

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 16 of 203 files at r1, 162 of 195 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36182)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 16 of 203 files at r1, 194 of 195 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36182)* status: :shipit: complete! ✓

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 16 of 203 files at r1, 194 of 195 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36182#-:-N95KKwO91hzyFZWDwSU:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
