### PR TITLE
[feat]: [PIE-7451]: Adding pipeline settings and limits based on Customer plan

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Adding pipeline settings and limits based on the customer plan to restrict the pipeline-actions.
Added the below settings and feature-restrictions: 

1. pipeline_timeout
2. stage_timeout
3. step_timeout
4. concurrent_pipeline_executions

And added the below feature-restrictions
1.  maximum_concurrent_steps_in_pipeline_execution
2. pipeline_execution_data_retention

Did not add setting for :`Hard limit Failure`, because in doc its mentioned that it will not be pipeline-setting. https://harness.atlassian.net/wiki/spaces/PIPE/pages/21220884906/Pipeline+settings+limits#:~:text=Hard%20Limit%20%2C%20it%20will%20not%20be%20a%20pipeline

Scope: Added new settings. 
Testing: Verified in DB that the new entries are created on ng-manager start.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42367)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42367)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 134 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPCOU8BSIwMwur-SJM:-NLPCOU8BSIwMwur-SJN:b-yvf4mo) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L134)):*
> ```YAML
>         editable: true
>       ENTERPRISE:
>         defaultValue: NO_LIMIT
> ```

having this string, will we read this in validator and ignore it? @tiwaritejas if we don't want any default value what should we do?
___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 136 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPCU2UAAW5V4RTeOs5:-NLPCU2UAAW5V4RTeOs6:bp3dd43) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L136)):*
> ```YAML
>         defaultValue: NO_LIMIT
>         editable: true
>   - identifier: concurrent_pipeline_executions
> ```

concurrent active pipeline executions
___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 148 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPCXCv0iB-c0cVz2tU:-NLPCXCv0iB-c0cVz2tV:b-sxdek4) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L148)):*
> ```YAML
>         editable: false
>       TEAM:
>         defaultValue: 200
> ```

currently make it 500 only, as we need to clear previous values
___
*[`925-enforcement-service/src/main/resources/features/pipeline-features.yml` line 104 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPClmq5-5WgmBpmukw:-NLPClmq5-5WgmBpmukx:blaa5ly) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/925-enforcement-service/src/main/resources/features/pipeline-features.yml#L104)):*
> ```YAML
>         limit: 10000
>         clientName: pipelineService
>   - name: MAX_CONCURRENT_STEPS_IN_PIPELINE_EXECUTION
> ```

MAX_TOTAL_STEPS? reason concurrent feelds confusing to people when maxCOncurreny in strategy is also there
___
*[`925-enforcement-service/src/main/resources/features/pipeline-features.yml` line 109 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPDJ6n3-K5PDwkQyYi:-NLPDJ6n3-K5PDwkQyYj:b32vac) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/925-enforcement-service/src/main/resources/features/pipeline-features.yml#L109)):*
> ```YAML
>       FREE:
>         restrictionType: STATIC_LIMIT
>         limit: 5
> ```

10
___
*[`925-enforcement-service/src/main/resources/features/pipeline-features.yml` line 113 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPDJfyESP5gFIR7ApL:-NLPDJfyESP5gFIR7ApM:b2ngysu) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/925-enforcement-service/src/main/resources/features/pipeline-features.yml#L113)):*
> ```YAML
>       TEAM:
>         restrictionType: STATIC_LIMIT
>         limit: 20
> ```

256
___
*[`925-enforcement-service/src/main/resources/features/pipeline-features.yml` line 118 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPDKLu6CR5C9DhNqSx:-NLPDKLw7iXwFfe0UMny:b2ngysu) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/925-enforcement-service/src/main/resources/features/pipeline-features.yml#L118)):*
> ```YAML
>         restrictionType: STATIC_LIMIT
>         limit: 50
>         clientName: pipelineService
> ```

256
___
*[`925-enforcement-service/src/main/resources/features/pipeline-features.yml` line 181 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPDAo164zeRoLigjbF:-NLPDAo164zeRoLigjbG:b-runln5) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/925-enforcement-service/src/main/resources/features/pipeline-features.yml#L181)):*
> ```YAML
>     description: The restriction on max concurrent pipeline executions
>     restrictions:
>       ENTERPRISE:
> ```

what about free and team?

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42367)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/enforcement/MaxStepTimeoutRestrictionUsageImpl.java` line 15 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPDUVIBg924UQXV6dl:-NLPDUVJBJh7LpEkboI6:b-454db9) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/pipeline-service/service/src/main/java/io/harness/enforcement/MaxStepTimeoutRestrictionUsageImpl.java#L15)):*
> ```Java
> import io.harness.enforcement.client.usage.RestrictionUsageInterface;
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> ```

for all this can we have default method in abstract class which everyone has extend?



_Code quote:_
```Java
MaxStepTimeoutRestrictionUsageImpl
```

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42367)* status: 11 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 134 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPCOU8BSIwMwur-SJM:-NLQAbt53KCmOtrGt5PL:bvzmpax) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L134)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

having this string, will we read this in validator and ignore it? @tiwaritejas if we don't want any default value what should we do?
</blockquote></details>

The default value is that there is no limit on step limit. We can use the NO_LIMIT during our implementation and will not set any timeout for step based on setting.
___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 136 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPCU2UAAW5V4RTeOs5:-NLQBcwOAWT9lx-typBz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L136)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

concurrent active pipeline executions
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 148 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPCXCv0iB-c0cVz2tU:-NLQCAVj7a6hM4tkN0Ne:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L148)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

currently make it 500 only, as we need to clear previous values
</blockquote></details>

Done.
___
*[`925-enforcement-service/src/main/resources/features/pipeline-features.yml` line 181 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPDAo164zeRoLigjbF:-NLQE6IT1lBkj5p-QfnD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/925-enforcement-service/src/main/resources/features/pipeline-features.yml#L181)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what about free and team?
</blockquote></details>

Done.

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42367)* status: 11 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`925-enforcement-service/src/main/resources/features/pipeline-features.yml` line 104 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPClmq5-5WgmBpmukw:-NLR_XRVBTjsjYTzyeRG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/925-enforcement-service/src/main/resources/features/pipeline-features.yml#L104)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

MAX_TOTAL_STEPS? reason concurrent feelds confusing to people when maxCOncurreny in strategy is also there
</blockquote></details>

Done.
___
*[`925-enforcement-service/src/main/resources/features/pipeline-features.yml` line 109 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPDJ6n3-K5PDwkQyYi:-NLR_Xu6B2SYAs1CLFIx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/925-enforcement-service/src/main/resources/features/pipeline-features.yml#L109)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

10
</blockquote></details>

Done.
___
*[`925-enforcement-service/src/main/resources/features/pipeline-features.yml` line 113 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPDJfyESP5gFIR7ApL:-NLR_YRP1-18Rlj_jtOD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/925-enforcement-service/src/main/resources/features/pipeline-features.yml#L113)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

256
</blockquote></details>

Done.
___
*[`925-enforcement-service/src/main/resources/features/pipeline-features.yml` line 118 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPDKLu6CR5C9DhNqSx:-NLR_Z1N82JJHNI_j0nm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/925-enforcement-service/src/main/resources/features/pipeline-features.yml#L118)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

256
</blockquote></details>

Done.

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42367)* status: 11 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/enforcement/MaxStepTimeoutRestrictionUsageImpl.java` line 15 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPDUVIBg924UQXV6dl:-NLRaUu5Bl22sOWmY8bm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/pipeline-service/service/src/main/java/io/harness/enforcement/MaxStepTimeoutRestrictionUsageImpl.java#L15)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

for all this can we have default method in abstract class which everyone has extend?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/enforcement/MaxStaticValueRestrictionUsageImpl.java` line 19 at r8](https://reviewable.io/reviews/harness/harness-core/42367#-NLUJM9E7jfP7En015Jx:-NLUJM9E7jfP7En015Jy:b-xiiml5) ([raw file](https://github.com/harness/harness-core/blob/525ec8dea883b5147cb8ebd357b94e8320f81ac4/pipeline-service/service/src/main/java/io/harness/enforcement/MaxStaticValueRestrictionUsageImpl.java#L19)):*
> ```Java
>     implements RestrictionUsageInterface<StaticLimitRestrictionMetadataDTO> {
>   @Override
>   public long getCurrentValue(String accountIdentifier, StaticLimitRestrictionMetadataDTO restrictionMetadataDTO) {
> ```

Can we add a comment why we are returning 0?

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 4 files at r5, 2 of 3 files at r7, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42367)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 134 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPCOU8BSIwMwur-SJM:-NLUKTxo0b17ck01jju8:bjecd5k) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L134)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

The default value is that there is no limit on step limit. We can use the NO_LIMIT during our implementation and will not set any timeout for step based on setting.
</blockquote></details>

where we are using it?
___
*[`925-enforcement-service/src/main/resources/features/pipeline-features.yml` line 181 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPDAo164zeRoLigjbF:-NLUKeg8CBdJj_SQ8ClQ:b41w4x0) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/925-enforcement-service/src/main/resources/features/pipeline-features.yml#L181)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

both are 500 max value

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 1 of 4 files at r5, 2 of 3 files at r7, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42367)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
*[`925-enforcement-service/src/main/resources/features/pipeline-features.yml` line 181 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPDAo164zeRoLigjbF:-NLWum6m-oGrr_5IKzQ4:b-74rxiu) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/925-enforcement-service/src/main/resources/features/pipeline-features.yml#L181)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

both are 500 max value
</blockquote></details>

In doc, I see the values 2, 1000 and 5000 for Free, Team and Enterprise

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42367)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`925-enforcement-service/src/main/resources/features/pipeline-features.yml` line 181 at r4](https://reviewable.io/reviews/harness/harness-core/42367#-NLPDAo164zeRoLigjbF:-NLZ6hot2CbMFSKKS7IU:b-wv079h) ([raw file](https://github.com/harness/harness-core/blob/31e9cb862177f0fd7bd387b66c9f67ef5bb7c239/925-enforcement-service/src/main/resources/features/pipeline-features.yml#L181)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

In doc, I see the values 2, 1000 and 5000 for Free, Team and Enterprise
</blockquote></details>

yeah changed in doc to 500 and 1k respectively

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42367)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger ti1

**Review by sahilhindwani-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42367#-:-NLZtBulAs3SfR4jNXM1:bnfp4nl)* status: :shipit: complete! ✓

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 1 of 4 files at r5, 1 of 3 files at r7, 7 of 7 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42367)* status: :shipit: complete! ✓

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 1 of 4 files at r5, 1 of 3 files at r7, 7 of 7 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42367)* status: :shipit: complete! ✓

**Pull request merged**
