### PR TITLE
techdebt: [PIE-4195]: Improve code coverage for 800-pipeline-service

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35368)

### CODE REVIEW

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35368)* status: Some of the checks are too old. 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/EndNodeExecutionHelper.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/35368#-N7JzjAr1TtPEk5KR-Q8:-N7JzjAr1TtPEk5KR-Q9:bc4w902) ([raw file](https://github.com/harness/harness-core/blob/786cf927364a911cac423b358f1979da9e824278/800-pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/EndNodeExecutionHelper.java#L51)):*
> ```Java
>   }
> 
>   private NodeExecution processStepResponseWithNoAdvisers(Ambiance ambiance, StepResponseProto stepResponse) {
> ```

we can add VisibleForTesting annotation

**Comment by shalini-agr** [comment]
*[`800-pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/EndNodeExecutionHelper.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/35368#-N7JzjAr1TtPEk5KR-Q8:-N7K6QakCm9p2kQUlZqE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/786cf927364a911cac423b358f1979da9e824278/800-pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/EndNodeExecutionHelper.java#L51)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

we can add VisibleForTesting annotation
</blockquote></details>

Done.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35368#-:-N7ZK43g3VT3zWbKFmQb:bnfp4nl)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35368)* status: 1 change requests. 1. unresolved discussions.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35368)* status: :shipit: complete! ✓

**Pull request merged**
