### PR TITLE
feat: [PL-39825]: revert - Added support for project and organization

### PR DESCRIPTION
**Pull request by meenakshi-harness**
Reverts harness/harness-core#52935

We are reverting from develop as well, as UI fixes might take some time

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53700)

### CODE REVIEW

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53700)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by meenakshi-harness** [comment]
trigger ut9

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Comment by meenakshi-harness** [comment]
trigger gitleaks

**Pull request merged**
