### PR TITLE
[feat]: [CDS-74327]: added trigger identifier in ng trigger event history base dto

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
## Describe your changes
Return NgEventHistoryDto instead of NgEventHistoryBaseDto for api to fetch eventhistory by eventcorrelationId
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50803)

### CODE REVIEW

**Comment by rathodmeetsatish** [comment]
trigger smartchecks

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerEventHistoryResource.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/50803#-N_mHoUX7NyHgOKWgoiw:-N_mHoUX7NyHgOKWgoix:b6mx5aw) ([raw file](https://github.com/harness/harness-core/blob/d6fe93770b54feb4408d9a45d30cc73e2d08f819/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerEventHistoryResource.java#L107)):*
> ```Java
>         ApiResponse(responseCode = "default", description = "Returns the Trigger catalogue response")
>       })
>   ResponseDTO<Page<NGTriggerEventHistoryDTO>>
> ```

isn't this a backward incompatible change?

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/NGTriggerEventHistoryMapper.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/50803#-N_mHvf4E3OJ2Sx1LyyV:-N_mHvf4E3OJ2Sx1LyyW:bsyfddv) ([raw file](https://github.com/harness/harness-core/blob/d6fe93770b54feb4408d9a45d30cc73e2d08f819/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/NGTriggerEventHistoryMapper.java#L35)):*
> ```Java
>     NGTriggerEventHistoryDTO ngTriggerEventHistoryDTO = toTriggerEventHistoryDto(triggerEventHistory);
>     ngTriggerEventHistoryDTO.setType(triggerEntity.getType());
>     if (ngTriggerEventHistoryDTO.getType().equals(NGTriggerType.ARTIFACT)) {
> ```

we should do reverse comparisons in case of hardcoded strings. Here, it shall run into NPE if .getType() is Null.

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50803)* status: 8 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerEventHistoryResource.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/50803#-N_mHoUX7NyHgOKWgoiw:-N_mKl39BJJne2O33aaH:b-h9copd) ([raw file](https://github.com/harness/harness-core/blob/d6fe93770b54feb4408d9a45d30cc73e2d08f819/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerEventHistoryResource.java#L107)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

isn't this a backward incompatible change?
</blockquote></details>

yes ui is the only consumer of this new api they have been informed about this change
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/NGTriggerEventHistoryMapper.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/50803#-N_mHvf4E3OJ2Sx1LyyV:-N_mKumI9o_Z7EWFRUfR:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/d6fe93770b54feb4408d9a45d30cc73e2d08f819/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/NGTriggerEventHistoryMapper.java#L35)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should do reverse comparisons in case of hardcoded strings. Here, it shall run into NPE if .getType() is Null.
</blockquote></details>

done

**Comment by rathodmeetsatish** [comment]
trigger uts

**Review by sribalij — APPROVED** [review]

**Comment by rathodmeetsatish** [comment]
trigger uts

**Comment by rathodmeetsatish** [comment]
trigger uts

**Comment by rathodmeetsatish** [comment]
trigger uts

**Review by vcalasansh — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 1 of 1 files at r3, 2 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50803)* status: 8 file(s) to review.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 1 of 1 files at r3, 2 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50803)* status: :shipit: complete! ✓

**Comment by rathodmeetsatish** [comment]
trigger uts

**Pull request merged**
