### PR TITLE
[feat]: [PIE-2843]: Optimise expansion handler calls in JSONExpansionService

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31461)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
___
*[800-pipeline-service/src/main/java/io/harness/pms/governance/ExpansionRequestBatchHelper.java, line 90 at r1](https://reviewable.io/reviews/harness/harness-core/31461#-Myq_3OZ0gJvtCbZYH5x:-Myq_3O_0PMr0FBB0v3d:b6qjd8r) ([raw file](https://github.com/harness/harness-core/blob/83f58dc711092dcf242502a1a255b02ce3cf5a37/800-pipeline-service/src/main/java/io/harness/pms/governance/ExpansionRequestBatchHelper.java#L90)):*
> ```Java
>       Set<ExpansionRequest> expansionRequests, String key, ExpansionRequestMetadata expansionRequestMetadata) {
>     // separate all requests by value so that each value's requests are mapped to one common request
>     Map<JsonNode, Set<ExpansionRequest>> requestsPerValue = new HashMap<>();
> ```

nit: can we simplify this using java streams groupingBy logic?

**Comment by sahilhindwani-harness** [comment]
___
*[800-pipeline-service/src/main/java/io/harness/pms/governance/ExpansionRequestBatchHelper.java, line 59 at r1](https://reviewable.io/reviews/harness/harness-core/31461#-Myq_s249IkDoUdi88UZ:-Myq_s25642I7nZeWZxu:buv62zv) ([raw file](https://github.com/harness/harness-core/blob/83f58dc711092dcf242502a1a255b02ce3cf5a37/800-pipeline-service/src/main/java/io/harness/pms/governance/ExpansionRequestBatchHelper.java#L59)):*
> 
Can we use groupingBy logic here too?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31461)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31461)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/governance/ExpansionRequestBatchHelper.java, line 59 at r1](https://reviewable.io/reviews/harness/harness-core/31461#-Myq_s249IkDoUdi88UZ:-MyuGl2j20clETiz0oo5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83f58dc711092dcf242502a1a255b02ce3cf5a37/800-pipeline-service/src/main/java/io/harness/pms/governance/ExpansionRequestBatchHelper.java#L59)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

> 
Can we use groupingBy logic here too?
</blockquote></details>

Done.

**Pull request closed without merging**
