### PR TITLE
feat: [PL-32248]: Support sorting on secrets listing.

### PR DESCRIPTION
**Pull request by boopesh007**
## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45986)

### CODE REVIEW

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45986)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45986)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/core/remote/SecretApiImplTest.java` line 303 at r2](https://reviewable.io/reviews/harness/harness-core/45986#-NSAANFVDG--x-3GVoCQ:-NSAANFWC-TZxQc-0LI4:b-i5i9xx) ([raw file](https://github.com/harness/harness-core/blob/8e5fdc4883946fba39d5bd1a90456b432214a487/120-ng-manager/src/test/java/io/harness/ng/core/remote/SecretApiImplTest.java#L303)):*
> ```Java
> 
>     Response response = accountSecretApi.getAccountScopedSecrets(
>         identifiers, types, false, null, page, limit, account, "modified", Sort.Direction.DESC.toString());
> ```

Why do we maintain a map for these fields in this way?
Like "updated" is mapped to "lastUpdatedAt" and "modified" is mapped to "lastModifiedAt". Why not keep the sort field the same as the field name in the entity to be sorted?

**Comment by boopesh007** [comment]
*[`120-ng-manager/src/test/java/io/harness/ng/core/remote/SecretApiImplTest.java` line 303 at r2](https://reviewable.io/reviews/harness/harness-core/45986#-NSAANFVDG--x-3GVoCQ:-NSADtY435PbCGNi1mzV:b-3do78d) ([raw file](https://github.com/harness/harness-core/blob/8e5fdc4883946fba39d5bd1a90456b432214a487/120-ng-manager/src/test/java/io/harness/ng/core/remote/SecretApiImplTest.java#L303)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

Why do we maintain a map for these fields in this way?
Like "updated" is mapped to "lastUpdatedAt" and "modified" is mapped to "lastModifiedAt". Why not keep the sort field the same as the field name in the entity to be sorted?
</blockquote></details>

It's already present this way in the ApiUtils, it should be a change across callers and as well as in ApiUtils.

**Comment by mankrit-singh** [comment]
*[`120-ng-manager/src/test/java/io/harness/ng/core/remote/SecretApiImplTest.java` line 303 at r2](https://reviewable.io/reviews/harness/harness-core/45986#-NSAANFVDG--x-3GVoCQ:-NSEs6zKCasxIG9ZnXOG:b90vk8p) ([raw file](https://github.com/harness/harness-core/blob/8e5fdc4883946fba39d5bd1a90456b432214a487/120-ng-manager/src/test/java/io/harness/ng/core/remote/SecretApiImplTest.java#L303)):*
<details><summary><i>Previously, boopesh007 (Boopesh Shanmugam) wrote…</i></summary><blockquote>

It's already present this way in the ApiUtils, it should be a change across callers and as well as in ApiUtils.
</blockquote></details>

according to the new set of API standards, we're using "created", "updated" etc.

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45986)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45986)* status: :shipit: complete! ✓

**Pull request merged**
