### PR TITLE
feat: [CDS-53751]: Sync step implementation - all changes prior to polling

### PR DESCRIPTION
**Pull request by meenaravichandran1**
## Describe your changes
Sync step - all changes prior to polling. I'll add some logs and null checks, change strings to constants, and refine strings as I continue to test.
(Some text comments are present for my reference. I'll remove them later after testing E2E)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44794)

### CODE REVIEW

**Comment by meenaravichandran1** [comment]
trigger messagecheck

**Review by vaibhav-si — COMMENTED** [review]
can we carve out the step param changes and merge them separately?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44794#-:-NPvVOHh4iJpfs7OG4b5:b-261ldn)* status: 17 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncOptionsEnum.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/44794#-NPvS0kXESI0PXMS_pL2:-NPvS0kXESI0PXMS_pL3:b-ln6zfg) ([raw file](https://github.com/harness/harness-core/blob/a5bfe0a31f9fe8f1f4d251439d13f6af4bb92cc5/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncOptionsEnum.java#L10)):*
> ```Java
> package io.harness.cdng.gitops.syncstep;
> 
> public enum SyncOptionsEnum {
> ```

nit, just call it SyncOptions
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncResources.java` line 13 at r3](https://reviewable.io/reviews/harness/harness-core/44794#-NPvS80W0xUR-rMlv1Gx:-NPvS80W0xUR-rMlv1Gy:b18i84z) ([raw file](https://github.com/harness/harness-core/blob/a5bfe0a31f9fe8f1f4d251439d13f6af4bb92cc5/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncResources.java#L13)):*
> ```Java
> import com.fasterxml.jackson.annotation.JsonValue;
> 
> public enum SyncResources {
> ```

do we need this? We have `applyOutofSyncOnly` policy already in Sync Policies. cc @anshul-harness 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 92 at r3](https://reviewable.io/reviews/harness/harness-core/44794#-NPvSS6iET4J1UzocoEF:-NPvSS6jDHpag5pi9Yjl:bc0ligf) ([raw file](https://github.com/harness/harness-core/blob/a5bfe0a31f9fe8f1f4d251439d13f6af4bb92cc5/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L92)):*
> ```Java
>     String accountId = AmbianceUtils.getAccountId(ambiance);
>     if (!cdFeatureFlagHelper.isEnabled(accountId, FeatureName.GITOPS_SYNC_STEP)) {
>       throw new InvalidRequestException("Operation not supported.", USER);
> ```

Can we give better error msg here: like Feature Flag "GITOPS_SYNC_STEP" not enabled

**Review by meenaravichandran1 — COMMENTED** [review]
I've pushed all the changes in a single commit. Is there anything that I can do now?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44794#-:-NPwI__N8curd9YRFgfv:b-1536i3)* status: 17 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncOptionsEnum.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/44794#-NPvS0kXESI0PXMS_pL2:-NPwIVL22YiieL_imnKO:b-m2k5pr) ([raw file](https://github.com/harness/harness-core/blob/a5bfe0a31f9fe8f1f4d251439d13f6af4bb92cc5/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncOptionsEnum.java#L10)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, just call it SyncOptions
</blockquote></details>

there is another class names SyncOptions
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncResources.java` line 13 at r3](https://reviewable.io/reviews/harness/harness-core/44794#-NPvS80W0xUR-rMlv1Gx:-NPwIFfNDAt1NT8ZBUaV:b-vs36fw) ([raw file](https://github.com/harness/harness-core/blob/a5bfe0a31f9fe8f1f4d251439d13f6af4bb92cc5/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncResources.java#L13)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

do we need this? We have `applyOutofSyncOnly` policy already in Sync Policies. cc @anshul-harness 
</blockquote></details>

the initial discussion was to have the sync step as same as Sync in Apps page, that's the reason it's there in two places. I'll check once again.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 92 at r3](https://reviewable.io/reviews/harness/harness-core/44794#-NPvSS6iET4J1UzocoEF:-NPwI0bX-akaIHOLKapT:b-dvvyv1) ([raw file](https://github.com/harness/harness-core/blob/a5bfe0a31f9fe8f1f4d251439d13f6af4bb92cc5/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L92)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Can we give better error msg here: like Feature Flag "GITOPS_SYNC_STEP" not enabled
</blockquote></details>

Since this is a user-facing error message, I do not want to reveal the internals here. I will name it Sync Operation not supported.

**Review by vaibhav-si — COMMENTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44794)* status: 17 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 92 at r3](https://reviewable.io/reviews/harness/harness-core/44794#-NPvSS6iET4J1UzocoEF:-NQ-kwhMAx2_b2_SiLke:bym7hs9) ([raw file](https://github.com/harness/harness-core/blob/a5bfe0a31f9fe8f1f4d251439d13f6af4bb92cc5/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L92)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

Since this is a user-facing error message, I do not want to reveal the internals here. I will name it Sync Operation not supported.
</blockquote></details>

The error message should be self-serviceable. Even our support team should be able to understand it and provide the corrective action. So, I personally feel it's okay to mention the FF.

**Review by vaibhav-si — COMMENTED** [review]
Create a new branch from this branch. It would have all your changes. In original branch, remove the sync step implemetation.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44794#-:-NQ-lVur3eL2K6mYo-Iz:b-pjl3mn)* status: 17 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44794)* status: 17 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 120 at r4](https://reviewable.io/reviews/harness/harness-core/44794#-NQ1QxEtDYpjDLoe95vN:-NQ1QxEv9S9QAM3-vRgb:bfu1tpb) ([raw file](https://github.com/harness/harness-core/blob/50faa9c519c140e8edb4cd50e5203b7538f02d54/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L120)):*
> ```Java
>     // sync policy - manual - call sync
>     if (!applicationsToBeManuallySynced.isEmpty()) {
>       syncAllApplications(applicationsToBeManuallySynced, accountId, orgId, projectId, syncStepParameters);
> ```

nit, can be renamed to triggerSyncApps
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 141 at r4](https://reviewable.io/reviews/harness/harness-core/44794#-NQ1R7KB9b-KQb3DXJkS:-NQ1R7KB9b-KQb3DXJkT:bdfu10j) ([raw file](https://github.com/harness/harness-core/blob/50faa9c519c140e8edb4cd50e5203b7538f02d54/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L141)):*
> ```Java
>       try {
>         final Response<ApplicationResource> response =
>             Failsafe.with(getRetryPolicy("Retrying to sync application...", FAILED_TO_SYNC_APPLICATION))
> ```

can we have a client helper which deals with the boiler plate code for making an API request with retries and errors etc. and just returns the final response?

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 5 of 16 files at r1, 4 of 6 files at r2, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44794)* status: 17 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44794#-:-NQ1Sq0N7MfyWk6YSHPk:bnfp4nl)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44794)* status: 17 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 92 at r3](https://reviewable.io/reviews/harness/harness-core/44794#-NPvSS6iET4J1UzocoEF:-NQ1z1WC-s5Z3BtDl_xT:b-6wihg4) ([raw file](https://github.com/harness/harness-core/blob/a5bfe0a31f9fe8f1f4d251439d13f6af4bb92cc5/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L92)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

The error message should be self-serviceable. Even our support team should be able to understand it and provide the corrective action. So, I personally feel it's okay to mention the FF.
</blockquote></details>

makes sense. Will make the change in the next PR.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 120 at r4](https://reviewable.io/reviews/harness/harness-core/44794#-NQ1QxEtDYpjDLoe95vN:-NQ1zAOeAUpKHIA_hsp2:b2nhysk) ([raw file](https://github.com/harness/harness-core/blob/50faa9c519c140e8edb4cd50e5203b7538f02d54/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L120)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, can be renamed to triggerSyncApps
</blockquote></details>

ack
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 141 at r4](https://reviewable.io/reviews/harness/harness-core/44794#-NQ1R7KB9b-KQb3DXJkS:-NQ1zDbC0g2HXwfnaTi8:b2nhysk) ([raw file](https://github.com/harness/harness-core/blob/50faa9c519c140e8edb4cd50e5203b7538f02d54/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L141)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

can we have a client helper which deals with the boiler plate code for making an API request with retries and errors etc. and just returns the final response?
</blockquote></details>

ack

**Comment by meenaravichandran1** [comment]
trigger feature-build

**Review by anshul-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 16 files at r1, 4 of 6 files at r2, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44794)* status: 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncOptionsEnum.java` line 13 at r4](https://reviewable.io/reviews/harness/harness-core/44794#-NQCUbmK6O4Plb9i0Edq:-NQCUbmK6O4Plb9i0Edr:br6ybpd) ([raw file](https://github.com/harness/harness-core/blob/50faa9c519c140e8edb4cd50e5203b7538f02d54/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncOptionsEnum.java#L13)):*
> ```Java
>   VALIDATE("Validate"),
>   CREATE_NAMESPACE("CreateNamespace"),
>   PRUNE_LAST("pruneLast"),
> ```

Capitalize P



_Code quote:_
```Java
("pr
```

**Review by anshul-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44794)* status: 3. unresolved discussions.

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44794)* status: 4. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncOptionsEnum.java` line 13 at r4](https://reviewable.io/reviews/harness/harness-core/44794#-NQCUbmK6O4Plb9i0Edq:-NQCYW8S-niukbjFvMP8:bin22w8) ([raw file](https://github.com/harness/harness-core/blob/50faa9c519c140e8edb4cd50e5203b7538f02d54/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncOptionsEnum.java#L13)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Capitalize P
</blockquote></details>

Validated this in our Gitops and Argo too. They pass this parameter alone with small p. Hence followed the same.

**Review by anshul-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44794)* status: 3. unresolved discussions.

**Review by vaibhav-si — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44794)* status: Some of the checks are too old.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44794)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by anshul-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44794)* status: :shipit: complete! ✓

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 6 of 16 files at r1, 4 of 6 files at r2, 4 of 7 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44794)* status: :shipit: complete! ✓

**Pull request merged**
