### PR TITLE
feat: [PL-24918]: error handling for list repo API

### PR DESCRIPTION
**Pull request by bhavya181**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32720)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/32720#-N14H6YK82A6QkX7s64K:-N14H6YL1lF0YO9Xiex8:b-eekhqa) ([raw file](https://github.com/harness/harness-core/blob/43d2d05994601e17d16154a502c6293ec9a3a7f4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L60)):*
> ```Java
>         scmConnector);
> 
>     ScmApiErrorHandlingHelper.processAndThrowError(
> ```

This is not right. processAndThrowError should be called only if response is of error type.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/32720#-N14H6YK82A6QkX7s64K:-N14J2gY5P81o-LDgvEK:b-ziex6o) ([raw file](https://github.com/harness/harness-core/blob/43d2d05994601e17d16154a502c6293ec9a3a7f4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L60)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This is not right. processAndThrowError should be called only if response is of error type.
</blockquote></details>

This helper first checks for status code, if it less than 300, it will return without calling any handler

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720#-:-N1CikwW6Ol9dVeCdOwi:bnfp4nl)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720)* status: 10 file(s) to review. 2 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 604 at r1](https://reviewable.io/reviews/harness/harness-core/32720#-N1CkxjJB2dRds2uAE56:-N1CkxjJB2dRds2uAE57:b-zhk933) ([raw file](https://github.com/harness/harness-core/blob/43d2d05994601e17d16154a502c6293ec9a3a7f4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L604)):*
> ```Java
>   @Override
>   public GetUserReposResponse listUserRepos(String accountIdentifier, String orgIdentifier, String projectIdentifier,
>       ScmConnector scmConnector, PageRequestDTO pageRequest) {
> ```

Why did we change it to a param ?

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720)* status: 10 file(s) to review. 2 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/32720#-N14H6YK82A6QkX7s64K:-N1Cl3HFA-aZG6Fkr42h:bqwdlz2) ([raw file](https://github.com/harness/harness-core/blob/43d2d05994601e17d16154a502c6293ec9a3a7f4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L60)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

This helper first checks for status code, if it less than 300, it will return without calling any handler
</blockquote></details>

The error handler should only be called if there is an error. You can use a util method that doesn't do anything when the response is successful, else it throws an exception.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720)* status: 10 file(s) to review. 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 604 at r1](https://reviewable.io/reviews/harness/harness-core/32720#-N1CkxjJB2dRds2uAE56:-N1Cl88r1E8TYuclvOb3:b-adeyiw) ([raw file](https://github.com/harness/harness-core/blob/43d2d05994601e17d16154a502c6293ec9a3a7f4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L604)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Why did we change it to a param ?
</blockquote></details>

Because every layer is using scmConnector after this and for that they are making db call again and again, scmOrchestrator, ScmClientFaclitator, that's passing it as param, so we don't query it again and again

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720)* status: 10 file(s) to review. 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmOrchestratorServiceImpl.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/32720#-N1ClQ2DD0foA_d3C2gI:-N1ClQ2DD0foA_d3C2gJ:bikc5lc) ([raw file](https://github.com/harness/harness-core/blob/43d2d05994601e17d16154a502c6293ec9a3a7f4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmOrchestratorServiceImpl.java#L98)):*
> ```Java
> 
>   @Override
>   public <R> R processScmRequestUsingGivenConnector(
> ```

nit: processScmRequestsUsingConnector would have been sufficient

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720)* status: 10 file(s) to review. 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/32720#-N14H6YK82A6QkX7s64K:-N14MPkD7TLew6GdOnuq:bwwieab) ([raw file](https://github.com/harness/harness-core/blob/43d2d05994601e17d16154a502c6293ec9a3a7f4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L60)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

The error handler should only be called if there is an error. You can use a util method that doesn't do anything when the response is successful, else it throws an exception.
</blockquote></details>

That's what that helper method is doing

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720)* status: 9 file(s) to review. 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListRepoScmApiErrorHandler.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/32720#-N1ClbTE5E3sLw6JyzoM:-N1ClbTE5E3sLw6JyzoN:bkaozin) ([raw file](https://github.com/harness/harness-core/blob/43d2d05994601e17d16154a502c6293ec9a3a7f4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListRepoScmApiErrorHandler.java#L28)):*
> ```Java
>             SCMExceptionExplanations.LIST_REPO_WITH_INVALID_CRED, new ScmUnauthorizedException(errorMessage));
>       default:
>         log.error(String.format("Error while listing bitbucket repos: [%s]" + errorMessage, statusCode));
> ```

For log.error, please use the below format

 log.error("Error while listing bitbucket repos: [{}]  {}, errorMessage, statusCode);

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720)* status: 12 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmOrchestratorServiceImpl.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/32720#-N1ClQ2DD0foA_d3C2gI:-N1D2qBT0kLX9ejNoprc:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/43d2d05994601e17d16154a502c6293ec9a3a7f4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmOrchestratorServiceImpl.java#L98)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

nit: processScmRequestsUsingConnector would have been sufficient
</blockquote></details>

done
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListRepoScmApiErrorHandler.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/32720#-N1ClbTE5E3sLw6JyzoM:-N1D2rwjB43iZ_B2BDuj:b6agbid) ([raw file](https://github.com/harness/harness-core/blob/43d2d05994601e17d16154a502c6293ec9a3a7f4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListRepoScmApiErrorHandler.java#L28)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

For log.error, please use the below format

 log.error("Error while listing bitbucket repos: [{}]  {}, errorMessage, statusCode);
</blockquote></details>

Done.

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720)* status: 12 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/32720#-N14H6YK82A6QkX7s64K:-N1CmEks388T6H4JSr1a:bz20iwx) ([raw file](https://github.com/harness/harness-core/blob/43d2d05994601e17d16154a502c6293ec9a3a7f4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L60)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

That's what that helper method is doing
</blockquote></details>

Then we call call the helper as ScmAPIResponseHandler.processExcectionInFailureCase

**Review by DeepakPatankar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/32720#-N14H6YK82A6QkX7s64K:-N1D8RqMEgnouIj6kMC-:bmc7ze2) ([raw file](https://github.com/harness/harness-core/blob/43d2d05994601e17d16154a502c6293ec9a3a7f4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L60)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Then we call call the helper as ScmAPIResponseHandler.processExcectionInFailureCase
</blockquote></details>

If naming is a concern, then we can name it like : "handler.handleIfError"
I've done same in git sdk.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720)* status: 12 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/32720#-N14H6YK82A6QkX7s64K:-N1D7eqaALYjt4vSebvr:bwbln68) ([raw file](https://github.com/harness/harness-core/blob/43d2d05994601e17d16154a502c6293ec9a3a7f4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L60)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

If naming is a concern, then we can name it like : "handler.handleIfError"
I've done same in git sdk.
</blockquote></details>

if (response.hasError()) {
   ScmApiErrorHandlingHelper.processAndThrowError(ScmApis.LIST_REPOSITORIES, scmConnector.getConnectorType(), response.getStatus(), response.getError());
}

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/32720#-N14H6YK82A6QkX7s64K:-N1D9ngy4o9NkEWujjZx:b-4wzrbv) ([raw file](https://github.com/harness/harness-core/blob/43d2d05994601e17d16154a502c6293ec9a3a7f4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L60)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

if (response.hasError()) {
   ScmApiErrorHandlingHelper.processAndThrowError(ScmApis.LIST_REPOSITORIES, scmConnector.getConnectorType(), response.getStatus(), response.getError());
}
</blockquote></details>

Yes, I was thinking that this must be the concern. I have a counter question here:
- So, do you think that it has to be done this way only? Making it explicit that we are calling error handler in case if its error?
- Or we can use helper method as suggested above that mentions: "handleIfError" and that does this implicit check for us? If naming is corrected, then I think helper method should be fine

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/32720#-N14H6YK82A6QkX7s64K:-N1DouSI7gOFJ886t1Oy:b-7fgrbt) ([raw file](https://github.com/harness/harness-core/blob/43d2d05994601e17d16154a502c6293ec9a3a7f4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L60)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Yes, I was thinking that this must be the concern. I have a counter question here:
- So, do you think that it has to be done this way only? Making it explicit that we are calling error handler in case if its error?
- Or we can use helper method as suggested above that mentions: "handleIfError" and that does this implicit check for us? If naming is corrected, then I think helper method should be fine
</blockquote></details>

I think second option is better as in response, we check just by status code, that if status code is greater than 300, we will call this handler and then we have to put this condition every time we use it, so keeping it inside will be better and we can change its name. 
what's say @ankit-harness

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/32720#-N14H6YK82A6QkX7s64K:-N1E8xeVAL98IM4CALVY:b-9my7vp) ([raw file](https://github.com/harness/harness-core/blob/43d2d05994601e17d16154a502c6293ec9a3a7f4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L60)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

I think second option is better as in response, we check just by status code, that if status code is greater than 300, we will call this handler and then we have to put this condition every time we use it, so keeping it inside will be better and we can change its name. 
what's say @ankit-harness 
</blockquote></details>

Done the changes

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 11 of 12 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720#-:-N1E9dny2S9QwbalhIo4:bnfp4nl)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 11 of 12 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32720#-:-N1EALLZ7xIh7PJvtFes:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
