### PR TITLE
fix: [PL-29378]: check for reference in git sync for cg git connector

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Describe your changes
In CG we can delete a git connector even if it is referenced for git sync
adding this to not allow it to be deleted

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39135)

### CODE REVIEW

**Comment by abhinav-harness** [comment]
trigger checkstyle

**Comment by abhinav-harness** [comment]
trigger checkstyle

**Comment by abhinav-harness** [comment]
trigger ft1

**Review by Fernando-Dourado — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39135)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java` line 1575 at r2](https://reviewable.io/reviews/harness/harness-core/39135#-NGsIyaI1h_lL_6p1lMv:-NGsIyaI1h_lL_6p1lMw:b-dw2scm) ([raw file](https://github.com/harness/harness-core/blob/e4769df30b838036071e7a1f9d8465dfeebe5d84/400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java#L1575)):*
> ```Java
>       if (SettingVariableTypes.GIT.name().equals(connectorSetting.getValue().getType())) {
>         List<YamlGitConfig> yamlGitConfigByConnector =
>             yamlGitService.getYamlGitConfigByConnector(connectorSetting.getAccountId(), connectorSetting.getUuid());
> ```

Please, add unit test to cover the scenarios

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39135)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java` line 1575 at r2](https://reviewable.io/reviews/harness/harness-core/39135#-NGsIyaI1h_lL_6p1lMv:-NGsWUHf8tnBJ_dib7r1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e4769df30b838036071e7a1f9d8465dfeebe5d84/400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java#L1575)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

Please, add unit test to cover the scenarios
</blockquote></details>

Done.

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Review by Fernando-Dourado — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39135)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/impl/SettingsServiceImplTest.java` line 574 at r3](https://reviewable.io/reviews/harness/harness-core/39135#-NH-h1cF4VnDQAhPCueL:-NH-h1cG1OwKcZ79BgmP:b-m392so) ([raw file](https://github.com/harness/harness-core/blob/9a9021ca29e540dd77fe8d1e3e9ad2b5dc8a1538/400-rest/src/test/java/software/wings/service/impl/SettingsServiceImplTest.java#L574)):*
> ```Java
>         aSettingAttribute().withCategory(SettingCategory.CONNECTOR).withValue(gitconfig).build();
>     assertThatExceptionOfType(InvalidRequestException.class)
>         .isThrownBy(() -> settingsService.ensureSettingAttributeSafeToDelete(accountSetting));
> ```

Next time, you could add a message assertion too.

**Review by Fernando-Dourado — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39135)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by franciscojuniorharness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39135)* status: :shipit: complete! ✓

**Pull request merged**
