### PR TITLE
fix: [CDS-64684]: passing regex for build number manual curl

### PR DESCRIPTION
**Pull request by rafaelmart1ns**
## Describe your changes
Modifies curl generation for when the webhook is last collected by removing schema artifacts from the payload.

Motivation: 
when you use the last collected with regex or with a predefined build the webhook ignores the artifacts passed by the payload.
With this, it causes a wrong understanding that the customer would be able to use a new regex in this payload. So the goal was to remove this and update the documentation so I don't get the wrong idea.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47527)

### CODE REVIEW

**Comment by rafaelmart1ns** [comment]
trigger messagecheck

**Comment by rafaelmart1ns** [comment]
trigger uts

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47527)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 35 at r4](https://reviewable.io/reviews/harness/harness-core/47527#-NVSiI1W-9y1RAB4dV-l:-NVSiI1W-9y1RAB4dV-m:bfqorzd) ([raw file](https://github.com/harness/harness-core/blob/24a08313b5fa5e87ea16ae12919af1d9c8c855dc/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L35)):*
> ```Java
>   SPG_ALLOW_GET_BUILD_SYNC("Allow get builds sync from gcs", HarnessTeam.SPG),
>   SPG_ALLOW_FILTER_BY_PATHS_GCS("Enables filtering by path on database GCS-type stream artifacts.", HarnessTeam.SPG),
>   SPG_GENERATE_CURL_WITHOUT_ARTIFACT("", HarnessTeam.SPG),
> ```

nit, every FF must have a description

**Review by lasdox — DISMISSED** [review]

**Comment by rafaelmart1ns** [comment]
trigger uts

**Review by Fernando-Dourado — APPROVED** [review]

**Comment by rafaelmart1ns** [comment]
trigger checkstylecodeformat

**Comment by rafaelmart1ns** [comment]
trigger uts

**Review by lasdox — APPROVED** [review]

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47527)* status: 5 file(s) to review.

**Comment by rafaelmart1ns** [comment]
trigger review

**Pull request merged**
