### PR TITLE
feat: [DEL-5293]: immutable docker delegate

### PR DESCRIPTION
**Pull request by AnupamIO**
Testing:
1- Downloaded docker-compose from qa for cg and ng docker delegate, modified it according to changes done in ftl file and applied the yaml. Delegate came up and executed basic shell script task. (checked with both legacy and immutable images)
2- Tested at pr env by bringing up delegates (cg: legacy/imm ng: legacy/imm). Executed basic shell task on ng immutable docker delegate which executed fine.

Note: 
Auto-upgrade is kept as OFF for docker delegates both legacy and immutable.
Didn't remove the -detach flag from cg docker .sh file.

Build Number: 7003202-000

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39643)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/resources/delegatetemplates/harness-ng-delegate-docker-compose.yaml.ftl` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/39643#-NG2qSQN3A-Al0v_ug0B:-NG2qSQO8lghmy9PlpZk:bv3vy3t) ([raw file](https://github.com/harness/harness-core/blob/cfeae225cc243012652c2bf92f1cf266e9877677/400-rest/src/main/resources/delegatetemplates/harness-ng-delegate-docker-compose.yaml.ftl#L25)):*
> ```FreeMarker
>       </#if>
> <#else>
>       - CLIENT_TOOLS_DOWNLOAD_DISABLED=true
> ```

do we need this? depending on the image this should be automatically set.

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39643)* status: 0 of 1 approvals obtained.

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39643)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39643)* status: :shipit: complete! ✓

**Comment by AnupamIO** [comment]
featurenamecheck

**Comment by AnupamIO** [comment]
trigger featurenamecheck

**Pull request merged**
