### PR TITLE
feat: [IDP-1620]: Fix stats response

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Describe your changes
Changing response from array to object
Also, tested the generated model against this response

/v1/scorecards/{scorecard-id}/stats
`{
  "name": "string",
  "stats": [
    {
      "name": "string",
      "owner": "string",
      "system": "string",
      "kind": "string",
      "type": "string",
      "score": 0
    }
  ]
}`

/v1/checks/{check-id}/stats
`{
  "name": "string",
  "stats": [
    {
      "name": "string",
      "owner": "string",
      "system": "string",
      "kind": "string",
      "type": "string",
      "status": "string"
    }
  ]
}`

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55290)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 4327 at r1](https://reviewable.io/reviews/harness/harness-core/55290#-NishNWd5WMcKtF2K0PC:-NishNWd5WMcKtF2K0PD:bnisqnf) ([raw file](https://github.com/harness/harness-core/blob/272540a2118c70f63f2869781166ba5c1d0a8bc1/idp-service/contracts/openapi/v1/openapi.yaml#L4327)):*
> ```YAML
>             type: array
>             items:
>               $ref: '#/components/schemas/ScorecardStatsResponse'
> ```

why this is still using array?

**Comment by ashishsanodia-harness** [comment]
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 4322 at r1](https://reviewable.io/reviews/harness/harness-core/55290#-NishYLdEA9GJu4GsPO8:-NishYLdEA9GJu4GsPO9:b-q8zt1f) ([raw file](https://github.com/harness/harness-core/blob/272540a2118c70f63f2869781166ba5c1d0a8bc1/idp-service/contracts/openapi/v1/openapi.yaml#L4322)):*
> ```YAML
>         application/json:
>           schema:
>             $ref: '#/components/schemas/ScorecardStatsResponse'
> ```

Did you verify generated model for this? Please update PR description

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55290)* status: 1 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 4322 at r1](https://reviewable.io/reviews/harness/harness-core/55290#-NishYLdEA9GJu4GsPO8:-Nisk9GT4KLCL-q65xA0:b-hujfd) ([raw file](https://github.com/harness/harness-core/blob/272540a2118c70f63f2869781166ba5c1d0a8bc1/idp-service/contracts/openapi/v1/openapi.yaml#L4322)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

Did you verify generated model for this? Please update PR description
</blockquote></details>

updated. Please check once
___
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 4327 at r1](https://reviewable.io/reviews/harness/harness-core/55290#-NishNWd5WMcKtF2K0PC:-Nisk50M1Zi9GQh0TlcM:bvizjko) ([raw file](https://github.com/harness/harness-core/blob/272540a2118c70f63f2869781166ba5c1d0a8bc1/idp-service/contracts/openapi/v1/openapi.yaml#L4327)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

why this is still using array?
</blockquote></details>

missed to change for yaml response

**Review by vikyathharekal — APPROVED** [review]

**Review by sandeepa-kv-jois — APPROVED** [review]

**Comment by vigneswara-propelo** [comment]
trigger review

**Review by mankrit-singh — APPROVED** [review]

**Pull request merged**
