### PR TITLE
[fix]: [CDS-80771]: List InputSets for Project

### PR DESCRIPTION
**Pull request by vtxorxwitty**
## Describe your changes
Tested the API locally. It lists all the InputSets present in the project.
Screenshot 2023-10-12 at 7 19 00 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54106)

### CODE REVIEW

**Comment by vtxorxwitty** [comment]
trigger uts

**Comment by vtxorxwitty** [comment]
trigger checkstylecodeformat

**Comment by vtxorxwitty** [comment]
trigger uts

**Review by utkarshchoubey-harness — DISMISSED** [review]

**Comment by vtxorxwitty** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 670 at r3](https://reviewable.io/reviews/harness/harness-core/54106#-NgwO6my2CGkSA1gwu4r:-NgwO6my2CGkSA1gwu4s:bwpeie9) ([raw file](https://github.com/harness/harness-core/blob/ca276243e5a3dcdf5532e6cd63ba9c291739926c/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L670)):*
> ```Java
>       @BeanParam GitMetadataUpdateRequestInfoDTO gitMetadataUpdateRequestInfo);
> 
>   @GET
> ```

Add hidden annotation

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 693 at r3](https://reviewable.io/reviews/harness/harness-core/54106#-NgwOJ3jCwHQ3iS-phV2:-NgwOJ3jCwHQ3iS-phV3:b-yjk8y3) ([raw file](https://github.com/harness/harness-core/blob/ca276243e5a3dcdf5532e6cd63ba9c291739926c/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L693)):*
> ```Java
>           description = PipelineResourceConstants.PROJECT_PARAM_MESSAGE) @ProjectIdentifier String projectIdentifier,
>       @Parameter(description = InputSetSchemaConstants.INPUT_SET_TYPE_MESSAGE) @QueryParam(
>           "inputSetType") @DefaultValue("ALL") InputSetListTypePMS inputSetListType,
> ```

why this field is required?

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54106)* status: 7 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 670 at r3](https://reviewable.io/reviews/harness/harness-core/54106#-NgwO6my2CGkSA1gwu4r:-NgwRj_u-IFk71DwfOrl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ca276243e5a3dcdf5532e6cd63ba9c291739926c/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L670)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Add hidden annotation
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 693 at r3](https://reviewable.io/reviews/harness/harness-core/54106#-NgwOJ3jCwHQ3iS-phV2:-NgwRkcS2oB0m5qisNY5:b-wtzm55) ([raw file](https://github.com/harness/harness-core/blob/ca276243e5a3dcdf5532e6cd63ba9c291739926c/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L693)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

why this field is required?
</blockquote></details>

Just kept it as it was a part of the listInputSets API. But we don't need it here so better to remove the unnecessary parameters.

**Comment by vtxorxwitty** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 695 at r3](https://reviewable.io/reviews/harness/harness-core/54106#-NgwONPv7RXy8do5xOMy:-NgwONPv7RXy8do5xOMz:bhobiky) ([raw file](https://github.com/harness/harness-core/blob/ca276243e5a3dcdf5532e6cd63ba9c291739926c/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L695)):*
> ```Java
>           "inputSetType") @DefaultValue("ALL") InputSetListTypePMS inputSetListType,
>       @QueryParam(NGResourceFilterConstants.SEARCH_TERM_KEY) @Parameter(
>           description = PipelineResourceConstants.INPUT_SET_SEARCH_TERM_PARAM_MESSAGE) String searchTerm,
> ```

Do we really need this?
Let's keep this api simple

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/inputset/InputSetSchemaConstants.java` line 41 at r3](https://reviewable.io/reviews/harness/harness-core/54106#-NgwWi65BaeIa4LbCOfw:-NgwWi65BaeIa4LbCOfx:bu10mwi) ([raw file](https://github.com/harness/harness-core/blob/ca276243e5a3dcdf5532e6cd63ba9c291739926c/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/inputset/InputSetSchemaConstants.java#L41)):*
> ```Java
>   public static final String INPUT_SET_COUNT_MESSAGE =
>       "Tells whether there are any Input Sets for this Pipeline or not.";
>   public static final String INPUT_SET_ID_WITH_PIPELINE_ID = "Pipeline Identifier for the entity.";
> ```

Nit: I think description is incorrect

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/mappers/PMSInputSetFilterHelper.java` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/54106#-NgwWrN_-Omt8gG50RXW:-NgwWrN_-Omt8gG50RXX:b4f06a5) ([raw file](https://github.com/harness/harness-core/blob/ca276243e5a3dcdf5532e6cd63ba9c291739926c/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/mappers/PMSInputSetFilterHelper.java#L85)):*
> ```Java
>   }
> 
>   public Criteria listInputSetsForProjectCriteria(String accountId, String orgIdentifier, String projectIdentifier,
> ```

nit: Lets simplify this by removing search term and deleted from params.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54106)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Comment by vtxorxwitty** [comment]
trigger uts

**Comment by vtxorxwitty** [comment]
trigger ut9

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 695 at r3](https://reviewable.io/reviews/harness/harness-core/54106#-NgwONPv7RXy8do5xOMy:-NgxczghDevAZcsgtFxE:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ca276243e5a3dcdf5532e6cd63ba9c291739926c/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L695)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Do we really need this?
Let's keep this api simple
</blockquote></details>

done

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/inputset/InputSetSchemaConstants.java` line 41 at r3](https://reviewable.io/reviews/harness/harness-core/54106#-NgwWi65BaeIa4LbCOfw:-Ngxd1gCAlBK2xjYTUoY:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ca276243e5a3dcdf5532e6cd63ba9c291739926c/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/inputset/InputSetSchemaConstants.java#L41)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Nit: I think description is incorrect
</blockquote></details>

done

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/mappers/PMSInputSetFilterHelper.java` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/54106#-NgwWrN_-Omt8gG50RXW:-Ngxd2h-8lCFtvXTxhZS:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ca276243e5a3dcdf5532e6cd63ba9c291739926c/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/mappers/PMSInputSetFilterHelper.java#L85)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: Lets simplify this by removing search term and deleted from params.
</blockquote></details>

done

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54106)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by vtxorxwitty** [comment]
trigger review

**Pull request merged**
