### PR TITLE
feat: [CDS-38981]: adding NG azure webApp traffic-shift and swap-slot step

### PR DESCRIPTION
**Pull request by vlica-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34615)

### CODE REVIEW

**Review by nassergonzalez — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34615)* status: :shipit: complete! ✓

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, 4 of 7 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34615)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/common/NgAzureLogCallbackProvider.java` line 36 at r4](https://reviewable.io/reviews/harness/harness-core/34615#-N5d6yHH7MMacV-mqikU:-N5d6yHH7MMacV-mqikV:b-op2vlj) ([raw file](https://github.com/harness/harness-core/blob/ba1913e3d93cb96a97c98b073d5f534d2daa5c52/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/common/NgAzureLogCallbackProvider.java#L36)):*
> ```Java
>   }
> 
>   private boolean shouldOpenStream(String commandUnitName) {
> ```

@abosii-harness is that correct behavior?

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 3 of 7 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34615)* status: 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java` line 71 at r4](https://reviewable.io/reviews/harness/harness-core/34615#-N5dJarr3DPr3hDyvhJ2:-N5dJarr3DPr3hDyvhJ3:b-zfke4f) ([raw file](https://github.com/harness/harness-core/blob/6249dfd16d3434cae88db0b9d70be57cc89f2c88/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java#L71)):*
> ```Java
>   @Override
>   public void validateResources(Ambiance ambiance, StepElementParameters stepParameters) {
>     List<EntityDetail> entityDetailList = new ArrayList<>();
> ```

This actually can be omitted, InfrastructureStep should already check runtime access
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java` line 138 at r4](https://reviewable.io/reviews/harness/harness-core/34615#-N5dLZGJ-M5xfzdcGaPW:-N5dLZGJ-M5xfzdcGaPX:b-ska5hh) ([raw file](https://github.com/harness/harness-core/blob/6249dfd16d3434cae88db0b9d70be57cc89f2c88/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java#L138)):*
> ```Java
> 
>   @Override
>   public StepResponse handleTaskResultWithSecurityContext(Ambiance ambiance, StepElementParameters stepParameters,
> ```

We should save something in sweeping output (it can be empty object), we will require it later for rollback
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java` line 148 at r4](https://reviewable.io/reviews/harness/harness-core/34615#-N5dL1ruAsnPvNaeOswE:-N5dL1ruAsnPvNaeOswF:b-ngd299) ([raw file](https://github.com/harness/harness-core/blob/6249dfd16d3434cae88db0b9d70be57cc89f2c88/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java#L148)):*
> ```Java
>       throw ex;
>     }
>     List<UnitProgress> unitProgresses = response.getCommandUnitsProgress().getUnitProgresses() == null
> ```

Any reasons why we have to take care if unitProgresses is null?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppTrafficShiftStep.java` line 150 at r4](https://reviewable.io/reviews/harness/harness-core/34615#-N5dKWD7126F3eUeI6Kw:-N5dKWD7126F3eUeI6Kx:b-ngd299) ([raw file](https://github.com/harness/harness-core/blob/6249dfd16d3434cae88db0b9d70be57cc89f2c88/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppTrafficShiftStep.java#L150)):*
> ```Java
>       throw ex;
>     }
>     List<UnitProgress> unitProgresses = response.getCommandUnitsProgress().getUnitProgresses() == null
> ```

Any reasons why we have to take care if unitProgresses is null?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppTrafficShiftStep.java` line 165 at r4](https://reviewable.io/reviews/harness/harness-core/34615#-N5dK1Ba56i5ZYFQY-1P:-N5dK1Ba56i5ZYFQY-1Q:b9olq98) ([raw file](https://github.com/harness/harness-core/blob/6249dfd16d3434cae88db0b9d70be57cc89f2c88/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppTrafficShiftStep.java#L165)):*
> ```Java
>   private double parseTrafficPercentage(String trafficPercentage) {
>     try {
>       return Double.parseDouble(trafficPercentage);
> ```

What if trafficPercentage is in integer format?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppTrafficShiftStep.java` line 167 at r4](https://reviewable.io/reviews/harness/harness-core/34615#-N5dK6kjCEgr6lul3Umn:-N5dK6kjCEgr6lul3Umo:b-9z3yk1) ([raw file](https://github.com/harness/harness-core/blob/6249dfd16d3434cae88db0b9d70be57cc89f2c88/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppTrafficShiftStep.java#L167)):*
> ```Java
>       return Double.parseDouble(trafficPercentage);
>     } catch (NumberFormatException ex) {
>       throw new InvalidArgumentsException("Failed to parse traffic percentage");
> ```

nit: We can give a better error here by providing step identifier and step type in error message
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppTrafficShiftStepInfo.java` line 57 at r4](https://reviewable.io/reviews/harness/harness-core/34615#-N5dKF8z-9j26E0yKRQH:-N5dKF8z-9j26E0yKRQI:b4cpzkd) ([raw file](https://github.com/harness/harness-core/blob/6249dfd16d3434cae88db0b9d70be57cc89f2c88/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppTrafficShiftStepInfo.java#L57)):*
> ```Java
> 
>   @NotNull
>   @YamlSchemaTypes(value = {SupportedPossibleFieldTypes.string, SupportedPossibleFieldTypes.number})
> ```

nit: SupportedPossibleFieldTypes can be statically imported
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/common/NgAzureLogCallbackProvider.java` line 36 at r4](https://reviewable.io/reviews/harness/harness-core/34615#-N5d6yHH7MMacV-mqikU:-N5dKsSr4waGzQSMVpTs:b-uhe0o6) ([raw file](https://github.com/harness/harness-core/blob/ba1913e3d93cb96a97c98b073d5f534d2daa5c52/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/common/NgAzureLogCallbackProvider.java#L36)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

@abosii-harness is that correct behavior? 
</blockquote></details>

yes, I've messed up here initially

**Review by abosii-harness — APPROVED** [review]
> Reviewed 5 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34615)* status: 1 change requests. 1. unresolved discussions.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 5 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34615)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34615)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java` line 69 at r6](https://reviewable.io/reviews/harness/harness-core/34615#-N5jDDDkBTofUZew-8oc:-N5jDDDkBTofUZew-8od:bv8j90k) ([raw file](https://github.com/harness/harness-core/blob/75def7367ce7b9f9286460f383460b7ec6247cf3/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java#L69)):*
> ```Java
>   @Override
>   public void validateResources(Ambiance ambiance, StepElementParameters stepParameters) {
>     // Azure Connector is validated in InfrastructureStep
> ```

can we validate that target slot is not null or empty ?

**Review by abosii-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34615)* status: 1 change requests. 1. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java` line 69 at r6](https://reviewable.io/reviews/harness/harness-core/34615#-N5jDDDkBTofUZew-8oc:-N5jDnNiAIdE9cH2m-Hr:bwsn3x2) ([raw file](https://github.com/harness/harness-core/blob/75def7367ce7b9f9286460f383460b7ec6247cf3/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java#L69)):*
<details><summary><i>Previously, anilchowdhury-harness (Anil Chowdhury) wrote…</i></summary><blockquote>

can we validate that target slot is not null or empty ?
</blockquote></details>

This kind of validation should be done in plan creator, validateResources is called for RBAC

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 8 files at r1, 1 of 7 files at r2, 1 of 4 files at r3, 1 of 1 files at r4, 3 of 6 files at r5, 2 of 2 files at r6, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34615#-:-N5k0FQt2ycRq3cEHUJI:bnfp4nl)* status: :shipit: complete! ✓

**Comment by vlica-harness** [comment]
trigger codeformat

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r9, 3 of 3 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34615#-:-N5nZWUK5hbqVJl2mlAe:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
