### PR TITLE
feat: [CDS-58423]: plugin provider for container step v2

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45923)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/plugin_info_service.proto` line 12 at r2](https://reviewable.io/reviews/harness/harness-core/45923#-NS4uuBU1fcJE-T21U9O:-NS4uuBU1fcJE-T21U9P:b9mfteu) ([raw file](https://github.com/harness/harness-core/blob/376c791872a2848696c2d1d0abd84eb436df1344/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/plugin_info_service.proto#L12)):*
> ```protobuf
> option java_multiple_files = true;
> 
> import "io/harness/pms/contracts/plan/plan_creation_service.proto";
> ```

nit: Why do we need this?

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 10 of 10 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45923)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45923)* status: 1. unresolved discussions.

**Comment by abhinav-harness** [comment]
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/plugin_info_service.proto` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/45923#-NSA5aJYEOevpA7L2-N-:-NSCkPaw1tXjE1cmei15:b-f6co27) ([raw file](https://github.com/harness/harness-core/blob/f9d7bd80c2d0999feea6ba07267847d146a32f05/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/plugin_info_service.proto#L34)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

we should remove these two fields
</blockquote></details>

this is needed for later mapping

**Review by rohitk-h — APPROVED** [review]
> Reviewed 10 of 10 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45923)* status: 1. unresolved discussions.

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Review by hextechpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45923)* status: :shipit: complete! ✓

___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/plugin_info_service.proto` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/45923#-NSA5aJYEOevpA7L2-N-:-NSEhlJy4o-qvyk4bFlZ:b-pou38q) ([raw file](https://github.com/harness/harness-core/blob/f9d7bd80c2d0999feea6ba07267847d146a32f05/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/plugin_info_service.proto#L34)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

this is needed for later mapping
</blockquote></details>

but why this you have as part of request only

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45923)* status: :shipit: complete! ✓

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45923)* status: 1 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/plugin_info_service.proto` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/45923#-NSA5aJYEOevpA7L2-N-:-NSCkVWL-6v12D69uTvm:bhn2u7a) ([raw file](https://github.com/harness/harness-core/blob/f9d7bd80c2d0999feea6ba07267847d146a32f05/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/plugin_info_service.proto#L34)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

but why this you have as part of request only
</blockquote></details>

this is response

**Review by hextechpal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45923)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]

**Pull request merged**
