### PR TITLE
feat: [PL-28882]: environment api implementation 

### PR DESCRIPTION
**Pull request by TarunUba1**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38865)

### CODE REVIEW

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38865)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/ProjectEnvironmentsApiImpl.java` line 170 at r1](https://reviewable.io/reviews/harness/harness-core/38865#-NEdboMLE4OfC5Kg4XqN:-NEdboMLE4OfC5Kg4XqO:b-d6od7w) ([raw file](https://github.com/harness/harness-core/blob/f73e7e27326c04ee1ea7239f675aa42e2a172701/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/ProjectEnvironmentsApiImpl.java#L170)):*
> ```Java
>     if (isAccessList) {
>       accessControlClient.checkForAccessOrThrow(ResourceScope.of(account, org, project), Resource.of(PROJECT, project),
>           VIEW_PROJECT_PERMISSION, "Unauthorized to list environments");
> ```

will the error message also show the missing permission?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/ProjectEnvironmentsApiImpl.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/38865#-NEdcM-e3oW7jkuOsUKB:-NEdcM-e3oW7jkuOsUKC:bp9jo8s) ([raw file](https://github.com/harness/harness-core/blob/f73e7e27326c04ee1ea7239f675aa42e2a172701/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/ProjectEnvironmentsApiImpl.java#L182)):*
> ```Java
>                                                       .collect(Collectors.toList());
> 
>       List<PermissionCheckDTO> permissionCheckDTOS =
> ```

Sorting is applicable in "access" flow?

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38865)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/ProjectEnvironmentsApiImpl.java` line 170 at r1](https://reviewable.io/reviews/harness/harness-core/38865#-NEdboMLE4OfC5Kg4XqN:-NEg6gyVEEN4-t1HjP7p:b-ctnsn7) ([raw file](https://github.com/harness/harness-core/blob/f73e7e27326c04ee1ea7239f675aa42e2a172701/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/ProjectEnvironmentsApiImpl.java#L170)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

will the error message also show the missing permission?
</blockquote></details>

Underlying functions looks like will return error with missing Permission but haven't tested it
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/ProjectEnvironmentsApiImpl.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/38865#-NEdcM-e3oW7jkuOsUKB:-NEg6w1W4F3UkdbieMs-:b-iatkzh) ([raw file](https://github.com/harness/harness-core/blob/f73e7e27326c04ee1ea7239f675aa42e2a172701/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/ProjectEnvironmentsApiImpl.java#L182)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Sorting is applicable in "access" flow?
</blockquote></details>

Sorting and searching as part of previous functions were not a part of result for accessList fetch

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38865)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/ProjectEnvironmentsApiImpl.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/38865#-NEdcM-e3oW7jkuOsUKB:-NEg7OlEC01j8j2RGGNY:bwaw1cw) ([raw file](https://github.com/harness/harness-core/blob/f73e7e27326c04ee1ea7239f675aa42e2a172701/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/ProjectEnvironmentsApiImpl.java#L182)):*
<details><summary><i>Previously, TarunUba1 (Tarun Uba) wrote…</i></summary><blockquote>

Sorting and searching as part of previous functions were not a part of result for accessList fetch
</blockquote></details>

Sorting and searching were not part of previous access list functions and same have been followed currently. Whats your take

**Comment by TarunUba1** [comment]
trigger ti0

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 139 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFcbhFME6K1heAIJBRe:-NFcbhFPAQ_CDUWV_J63:b1zs1mm) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L139)):*
> ```Java
>   }
> 
>   private void validate(NGEnvironmentConfig ngEnvironmentConfig) {
> ```

can we  reuse code from already existing mapper?
io.harness.ng.core.environment.mappers.EnvironmentMapper#validateEnvGlobalOverrides

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFccIhwBpxxkPggTkt8:-NFccIhwBpxxkPggTkt9:b-bsktcr) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L148)):*
> can we  reuse code from already existing mapper?

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 139 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFcbhFME6K1heAIJBRe:-NFcdrZ14jSFS7NkcWhL:b-xyeqmw) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L139)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

can we  reuse code from already existing mapper?
io.harness.ng.core.environment.mappers.EnvironmentMapper#validateEnvGlobalOverrides

</blockquote></details>

ignore this comment.

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 258 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFceRR91_ZY8lcwuMfO:-NFceRR91_ZY8lcwuMfP:b-bsktcr) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L258)):*
> can we  reuse code from already existing mapper?

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFces7t00NYt1XDSc2C:-NFces7t00NYt1XDSc2D:b-kb7r8o) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L104)):*
> ```Java
>     return environment;
>   }
>   public NGEnvironmentConfig toNGEnvironmentConfig(EnvironmentRequest dto, String org, String project) {
> ```

Can be static.

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFcey2M3Cw-EOVubs_U:-NFcey2M3Cw-EOVubs_V:b-kb7r8o) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L125)):*
> ```Java
>   }
> 
>   public Environment toNGEnvironmentEntity(String accountId, EnvironmentRequest dto, String org, String project) {
> ```

Can be static.

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 221 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFcfeuX5aiPtihyeHQL:-NFcfeuX5aiPtihyeHQM:b-bsktcr) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L221)):*
> can we  reuse code from already existing mapper?

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 234 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFcfgCo4t4eRIHTXvR-:-NFcfgCo4t4eRIHTXvR0:b4ldi71) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L234)):*
> ```Java
>   }
> 
>   public void checkDuplicateConfigFilesIdentifiersWithIn(List<ConfigFileWrapper> configFiles) {
> ```

can we reuse code from already existing mapper?

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 248 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFcfkYcDCzc6sRMfIKL:-NFcfkYcDCzc6sRMfIKM:b4ldi71) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L248)):*
> ```Java
> 
>   @NotNull
>   private Set<String> getDuplicateIdentifiers(Stream<String> identifierStream) {
> ```

can we reuse code from already existing mapper?

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 221 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFcfoBy1eGu__JPXu64:-NFcfoBy1eGu__JPXu65:b3kxh5c) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L221)):*
> ```Java
>   }
> 
>   public void checkDuplicateManifestIdentifiersWithIn(List<ManifestConfigWrapper> manifests) {
> ```

also make them static, if not already

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38865)* status: Some of the checks are too old. 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFchPVR-u0UoDxtLSfJ:-NFchPVR-u0UoDxtLSfK:bt0eawo) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L100)):*
> ```Java
>     Set<ConstraintViolation<Environment>> violations = validator.validate(environment);
>     if (!violations.isEmpty()) {
>       throw new JerseyViolationException(violations, null);
> ```

Good practice to adopt JerseyViolationException at apiResource level classes, where we send them back unhandled.👌
Else can expose unwanted info.

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtilsTest.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFcjTZr38snwswUNosZ:-NFcjTZr38snwswUNos_:b3nqpz1) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtilsTest.java#L104)):*
> ```Java
> 
>     yamlServiceOverride = ServiceOverridesMapper.toYaml(ngServiceOverrideConfig);
>     environmentRequest = new EnvironmentRequest();
> ```

nit: we can extract all this setter code to small methods.
Would shrink setUp() method body.

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtilsTest.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFck-uJ-kXwgYkW9Y0B:-NFck-uJ-kXwgYkW9Y0C:b38xw1f) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtilsTest.java#L52)):*
> ```Java
> import org.junit.experimental.categories.Category;
> 
> public class EnvironmentsResourceApiUtilsTest extends CategoryTest {
> ```

Lets add test for remaming methods too.
as io.harness.ng.core.environment.resources.EnvironmentsResourceApiUtils#mapSort

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38865)* status: 7 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFchPVR-u0UoDxtLSfJ:-NFeTjSVEMLaWBiPtWHr:b-zcjvte) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L100)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Good practice to adopt JerseyViolationException at apiResource level classes, where we send them back unhandled.👌
Else can expose unwanted info.
</blockquote></details>

Thanks
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFces7t00NYt1XDSc2C:-NFeDH_12Rm3labplBQi:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L104)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Can be static.
</blockquote></details>

done
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFcey2M3Cw-EOVubs_U:-NFeDM0_41ai36XjmhKV:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L125)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Can be static.
</blockquote></details>

done
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFccIhwBpxxkPggTkt8:-NFeGT4CCRdu2qLvsOAe:bntdy6h) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L148)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

> can we  reuse code from already existing mapper?
</blockquote></details>

private method currently
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 221 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFcfeuX5aiPtihyeHQL:-NFeDVh89NL6qZUpEC-c:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L221)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

> can we  reuse code from already existing mapper?
</blockquote></details>

done
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 221 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFcfoBy1eGu__JPXu64:-NFeE1jkAmBHof8tGhb0:b-mc3o25) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L221)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

also make them static, if not already
</blockquote></details>

they are static currently
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 234 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFcfgCo4t4eRIHTXvR-:-NFeE3oJ8jigDumUdeUb:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L234)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

can we reuse code from already existing mapper?
</blockquote></details>

done
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 248 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFcfkYcDCzc6sRMfIKL:-NFdao3Z3xSWR55bEzXY:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L248)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

can we reuse code from already existing mapper?
</blockquote></details>

done
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 258 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFceRR91_ZY8lcwuMfO:-NFeGWKDEo8k83cqFX8s:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L258)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

> can we  reuse code from already existing mapper?
</blockquote></details>

done
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtilsTest.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFck-uJ-kXwgYkW9Y0B:-NFeGXdJ2DBOLynkUIu8:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtilsTest.java#L52)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Lets add test for remaming methods too.
as io.harness.ng.core.environment.resources.EnvironmentsResourceApiUtils#mapSort
</blockquote></details>

done
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtilsTest.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFcjTZr38snwswUNosZ:-NFeU2NZ1bPRksUVqUxy:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtilsTest.java#L104)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

nit: we can extract all this setter code to small methods.
Would shrink setUp() method body.
</blockquote></details>

done

**Comment by TarunUba1** [comment]
trigger ft2

**Comment by TarunUba1** [comment]
trigger ft2

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 3 files at r2, 4 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38865)* status: 6 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 2 approvals obtained.

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/38865#-NFccIhwBpxxkPggTkt8:-NFqs6vf4EFhQLmNVDnj:b-lv9e8x) ([raw file](https://github.com/harness/harness-core/blob/295792d7bf1a78b9f2f8094c6c37bd293ebcf54a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentsResourceApiUtils.java#L148)):*
<details><summary><i>Previously, TarunUba1 (Tarun Uba) wrote…</i></summary><blockquote>

private method currently
</blockquote></details>

Lets make it public.

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38865)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by TarunUba1** [comment]
trigger ti0

**Comment by TarunUba1** [comment]
trigger ti1

**Comment by TarunUba1** [comment]
trigger ti2

**Comment by TarunUba1** [comment]
trigger ti3

**Comment by TarunUba1** [comment]
trigger ti4

**Comment by TarunUba1** [comment]
trigger ti0

**Comment by TarunUba1** [comment]
trigger ti1 ti2 ti3 ti4

**Comment by TarunUba1** [comment]
Workflow was changed Regarding APis , Closing it now

**Pull request closed without merging**
