### PR TITLE
feat: [CDS-36790]: Refactor chartmuseum client and add support for 0.13+ version

### PR DESCRIPTION
**Pull request by abosii-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32992)

### CODE REVIEW

**Review by mdmilic — COMMENTED** [review]
> Reviewed 7 of 60 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32992)* status: 53 file(s) to review. 0 of 1 approvals obtained.

**Review by mdmilic — DISMISSED** [review]
> Reviewed 1 of 60 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32992)* status: 52 file(s) to review.

**Comment by mdmilic** [comment]
approving delegate module related changes

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 49 of 60 files at r1, 6 of 11 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32992)* status: :shipit: complete! ✓

___
*[`970-api-services-beans/src/main/java/io/harness/chartmuseum/ChartMuseumConstants.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/32992#-N1t0Z5q9IelQTQ9UPwv:-N1t0Z5r2D1gqVqzFoiv:b-4qcq3n) ([raw file](https://github.com/harness/harness-core/blob/bbc857cdf5322da880971eba46df3240272cf051/970-api-services-beans/src/main/java/io/harness/chartmuseum/ChartMuseumConstants.java#L53)):*
> ```Java
>       " --port=${PORT} --storage=google --storage-google-bucket=${BUCKET_NAME} --storage-google-prefix=${FOLDER_PATH}";
> 
>   public final String DISABLE_STATEFILES = "--disable-statefiles --index-limit 100";
> ```

isn't 100 too high a limit ? Is is possible to test cpu spike with 100 being reached ?

**Review by abosii-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32992)* status: 22 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`970-api-services-beans/src/main/java/io/harness/chartmuseum/ChartMuseumConstants.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/32992#-N1t0Z5q9IelQTQ9UPwv:-N2At7h08lrVrQNltVoH:b1v2osh) ([raw file](https://github.com/harness/harness-core/blob/bbc857cdf5322da880971eba46df3240272cf051/970-api-services-beans/src/main/java/io/harness/chartmuseum/ChartMuseumConstants.java#L53)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

isn't 100 too high a limit ? Is is possible to test cpu spike with 100 being reached ?
</blockquote></details>

There is a small difference between index limit 100 and index limit 10, there is even a higher spike with index limit 10 first few seconds 
index-limit 100


index-limit 10


I've set it to 100 for few reasons:
 * Without any index limit, if repo has a high number of repo it will fail with to many open files
 * With small index limit (10) time to init repo is too big and doesn't fit in our timeout  
 * I've tested different combinations and this looks optimal for big repos

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 22 of 22 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32992)* status: 1. unresolved discussions.

**Review by yogesh-chauhan — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32992)* status: :shipit: complete! ✓

**Review by shubham-in10se — DISMISSED** [review]
> Reviewed 2 of 60 files at r1, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32992)* status: :shipit: complete! ✓

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/chartmuseum/ChartmuseumCgClientFactory.java` line 41 at r5](https://reviewable.io/reviews/harness/harness-core/32992#-N2C4Edt8Nni_Bbel-OF:-N2CEdUj9MqwzqnB8C_w:b-hpfr5q) ([raw file](https://github.com/harness/harness-core/blob/23f4b83de229af61107f6f560e628862d245e4e9/930-delegate-tasks/src/main/java/io/harness/delegate/chartmuseum/ChartmuseumCgClientFactory.java#L41)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

There is no need to split this in 2 different methods, I don't see any logic just some casting. It will actually reduce readability (at least for me, let me know if you fell differently) 
</blockquote></details>

it is fine for now, but if we ever decide to add any more cases, this will require refactoring.

**Comment by abosii-harness** [comment]
trigger messagecheck

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32992)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> Reviewed 32 of 60 files at r1, 5 of 11 files at r2, 4 of 5 files at r3, 9 of 22 files at r4, 1 of 2 files at r5, 6 of 9 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32992)* status: :shipit: complete! ✓

**Pull request merged**
