### PR TITLE
feat: [CDS-36984]: Export terraform plan as human readable output

### PR DESCRIPTION
**Pull request by akhilpandey1**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36833)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 12 Issues 
* Code issue 11 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36833)

**Comment by akhilpandey1** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/36833#-NAP3uvtD93c-aoHEHS7:-NAP3uvtD93c-aoHEHS8:b-4eqxj2) ([raw file](https://github.com/harness/harness-core/blob/abc257463a902ae16b3c74c7dbc149dde725ac67/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L74)):*
> ```Java
> import io.harness.filesystem.FileIo;
> import io.harness.git.model.GitRepositoryType;
> import io.harness.logging.*;
> ```

do not use * imports

**Comment by yogesh-chauhan** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 395 at r2](https://reviewable.io/reviews/harness/harness-core/36833#-NAP4a7P-1bv3TjMs8SZ:-NAP4a7P-1bv3TjMs8S_:bymns3j) ([raw file](https://github.com/harness/harness-core/blob/abc257463a902ae16b3c74c7dbc149dde725ac67/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L395)):*
> ```Java
>         String message =
>             "Terraform Humanreadable plan not found in Delegate sent Execution Data, delegate seems to be on a older version not supporting human readable plan for Terraform";
>         log.error(message);
> ```

we shoud log the exception as well 
```log.error(message, e ) ```
also lets catch all exceptions here just to be safe

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/beans/delegation/TerraformProvisionParameters.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/36833#-NAPDMNU11E82NnWImut:-NAPDMNU11E82NnWImuu:b68w3x1) ([raw file](https://github.com/harness/harness-core/blob/abc257463a902ae16b3c74c7dbc149dde725ac67/930-delegate-tasks/src/main/java/software/wings/beans/delegation/TerraformProvisionParameters.java#L47)):*
> ```Java
> import lombok.Builder;
> import lombok.Getter;
> import lombok.Setter;
> ```

I don't see these annotation being used in this class?

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 963 at r2](https://reviewable.io/reviews/harness/harness-core/36833#-NAPDqQu3E_Zsq5riP0C:-NAPDqQu3E_Zsq5riP0D:b-cwf5k4) ([raw file](https://github.com/harness/harness-core/blob/abc257463a902ae16b3c74c7dbc149dde725ac67/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L963)):*
> ```Java
>         executeShellCommand(humanReadableCommand, scriptDirectory, parameters, envVars, planHumanReadableOutputStream);
>     if (code == 0) {
>       if (parameters.isExportPlanToHumanReadableOutput()) {
> ```

You can combine these two if statements into single one
if (code == 0 && parameters.isExport...)

**Comment by markoharness** [comment]
*[`970-api-services-beans/src/main/java/io/harness/logging/PlanHumanReadableOutputStream.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/36833#-NAPEGbeDq9AxA6wEc-R:-NAPEGbeDq9AxA6wEc-S:b2ghtle) ([raw file](https://github.com/harness/harness-core/blob/abc257463a902ae16b3c74c7dbc149dde725ac67/970-api-services-beans/src/main/java/io/harness/logging/PlanHumanReadableOutputStream.java#L30)):*
> ```Java
>     // Add a new line after the string so it looks better as a plan in the end
>     s = s + "\n";
>     humanReadablePlan.append(s);
> ```

You don't need to reassign 's' variable
you can define "\n" as static variable of the class
and then just call humanReadablePlan.append(s + NEW_LINE)

**Review by markoharness — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36833)* status: 4 file(s) to review. 0 of 1 approvals obtained.

**Comment by akhilpandey1** [comment]
*[`970-api-services-beans/src/main/java/io/harness/logging/PlanHumanReadableOutputStream.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/36833#-NAPEGbeDq9AxA6wEc-R:-NASwysU1-a0Yd2HqgUH:b-n79qj4) ([raw file](https://github.com/harness/harness-core/blob/abc257463a902ae16b3c74c7dbc149dde725ac67/970-api-services-beans/src/main/java/io/harness/logging/PlanHumanReadableOutputStream.java#L30)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

You don't need to reassign 's' variable
you can define "\n" as static variable of the class
and then just call humanReadablePlan.append(s + NEW_LINE)
</blockquote></details>

Done, humanReadablePlan.append(s + NEW_LINE) caused the PMD failure due to inefficient buffering, so added as  humanReadablePlan.append(s).append(NEW_LINE);

**Comment by akhilpandey1** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/beans/delegation/TerraformProvisionParameters.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/36833#-NAPDMNU11E82NnWImut:-NAT9Cyv6b0-XI9X_HRl:b-nie876) ([raw file](https://github.com/harness/harness-core/blob/abc257463a902ae16b3c74c7dbc149dde725ac67/930-delegate-tasks/src/main/java/software/wings/beans/delegation/TerraformProvisionParameters.java#L47)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

I don't see these annotation being used in this class?
</blockquote></details>

Thanks, removed them

**Comment by akhilpandey1** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/36833#-NAP3uvtD93c-aoHEHS7:-NAT9Jn5-2HTzyoLpwFB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/abc257463a902ae16b3c74c7dbc149dde725ac67/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L74)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do not use * imports
</blockquote></details>

Done.

**Comment by akhilpandey1** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 963 at r2](https://reviewable.io/reviews/harness/harness-core/36833#-NAPDqQu3E_Zsq5riP0C:-NAT9LRI6Mdc4UtUbLcC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/abc257463a902ae16b3c74c7dbc149dde725ac67/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L963)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

You can combine these two if statements into single one
if (code == 0 && parameters.isExport...)
</blockquote></details>

Done.

**Comment by akhilpandey1** [comment]
trigger ti0

**Comment by akhilpandey1** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 395 at r2](https://reviewable.io/reviews/harness/harness-core/36833#-NAP4a7P-1bv3TjMs8SZ:-NAVLKNV66Crgeh_eLuZ:b-oejllh) ([raw file](https://github.com/harness/harness-core/blob/abc257463a902ae16b3c74c7dbc149dde725ac67/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L395)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we shoud log the exception as well 
```log.error(message, e ) ```
also lets catch all exceptions here just to be safe
</blockquote></details>

Done, catching all exceptions now and logging them as well

**Review by markoharness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36833)* status: 2. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 2 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36833)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36833)* status: 0 of 1 approvals obtained.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36833)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36833)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by yogesh-chauhan** [comment]
trigger codebasehash

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36833)* status: :shipit: complete! ✓

**Pull request merged**
