### PR TITLE
fix: [PL-27285]: Added try catch block to the delete flow in rename call

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36085)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36085)

**Comment by VikasMaddukuriHarness** [comment]
trigger messagecheck

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36085)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by VikasMaddukuriHarness** [comment]
trigger codebasehash

**Review by aman-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36085#-:-N8hcVqm7W0YXg8n3zxo:bnfp4nl)* status: 1 file(s) to review.

**Comment by VikasMaddukuriHarness** [comment]
trigger codebasehash

**Comment by piyush-harness** [comment]
*[`890-sm-core/src/main/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java` line 173 at r2](https://reviewable.io/reviews/harness/harness-core/36085#-N8he8hHBFPd6VQG0SC3:-N8he8hHBFPd6VQG0SC4:bul4e2y) ([raw file](https://github.com/harness/harness-core/blob/df1392ff187eba9590eaa1393a795537666a32b6/890-sm-core/src/main/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java#L173)):*
> ```Java
>               deleteSecret(accountId, existingRecord, vaultConfig);
>             } catch (Exception e) {
>               log.error("Delete secret failed in rename secret call with the following error {}", e.getMessage());
> ```

Why are we not throwing back this error to UI

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36085)* status: 1 file(s) to review. 1. unresolved discussions. 

___
*[`890-sm-core/src/main/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java` line 173 at r2](https://reviewable.io/reviews/harness/harness-core/36085#-N8he8hHBFPd6VQG0SC3:-N8hlR3j9Lv2X7cisU9W:b-58c1rf) ([raw file](https://github.com/harness/harness-core/blob/df1392ff187eba9590eaa1393a795537666a32b6/890-sm-core/src/main/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java#L173)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why are we not throwing back this error to UI
</blockquote></details>

In the case of rename of secret, we need delete permissions. But apparently this is not the correct way. So we are now ignoring that delete call and updating in harness dB. In vault side, the old record will still be present. 
We will update the docs mentioning the same. If you provide delete permissions, then only the record in vault will be deleted otherwise, we will still have the old entry lying in vault side

**Pull request merged**
