### PR TITLE
fix:[CDS-57705] Populate adoptDelegateDecryption from an FF

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- When a service variable value is a secret expression and that expression uses nested variables, we are unable to render it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45571)

### CODE REVIEW

**Review by puthrayaharness — APPROVED** [review]

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45571)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by Fernando-Dourado** [comment]
trigger featurenamecheck

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45571)* status: :shipit: complete! ✓

**Comment by Fernando-Dourado** [comment]
trigger featurenamecheck

**Comment by Fernando-Dourado** [comment]
trigger featurenamecheck

**Comment by Fernando-Dourado** [comment]
trigger featurenamecheck

**Comment by Fernando-Dourado** [comment]
PR checks are broken with these changes.

**Pull request closed without merging**
