### PR TITLE
feat: [IDP-181]: AzureRepo connector implementation

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44843)

### CODE REVIEW

**Review by devesh-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44843)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/GitIntegrationUtil.java` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/44843#-NPz_ao73EDm_c_5crWH:-NPz_ao73EDm_c_5crWI:b-c2hyzf) ([raw file](https://github.com/harness/harness-core/blob/f3a2dc11a5f30361c19d7a9ebe7b7cc05ea09dfd/idp-service/src/main/java/io/harness/idp/gitintegration/GitIntegrationUtil.java#L19)):*
> ```Java
> 
> @Singleton
> public class GitIntegrationUtil {
> ```

Lets use UtilityClass annotation and do static import instead of injecting it.

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44843)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/GitIntegrationUtil.java` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/44843#-NPz_ao73EDm_c_5crWH:-NPziP6b9jsNvI3p3R7f:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f3a2dc11a5f30361c19d7a9ebe7b7cc05ea09dfd/idp-service/src/main/java/io/harness/idp/gitintegration/GitIntegrationUtil.java#L19)):*
<details><summary><i>Previously, devesh-harness wrote…</i></summary><blockquote>

Lets use UtilityClass annotation and do static import instead of injecting it.
</blockquote></details>

done

**Review by devesh-harness — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44843)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by devesh-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44843)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by deepharness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44843)* status: 8 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/GitIntegrationUtil.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/44843#-NQ-dmta8b4uHOVSgyy9:-NQ-dmta8b4uHOVSgyyA:b1wgpkp) ([raw file](https://github.com/harness/harness-core/blob/bcaa0e65a976e38d2f296ed07f765089875bc610/idp-service/src/main/java/io/harness/idp/gitintegration/GitIntegrationUtil.java#L18)):*
> ```Java
> @UtilityClass
> public class GitIntegrationUtil {
>   public EnvironmentSecret getEnvironmentSecret(SecretManagerClientService ngSecretService, String accountIdentifier,
> ```

Should it be a static method ? if not you can inject SecretManagerClientService , it will reduce 1 parameter.

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44843)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/GitIntegrationUtil.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/44843#-NQ-dmta8b4uHOVSgyy9:-NQ-ihtO7iBMoBXxWZkd:bc45l7r) ([raw file](https://github.com/harness/harness-core/blob/bcaa0e65a976e38d2f296ed07f765089875bc610/idp-service/src/main/java/io/harness/idp/gitintegration/GitIntegrationUtil.java#L18)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Should it be a static method ? if not you can inject SecretManagerClientService , it will reduce 1 parameter.
</blockquote></details>

In UtilityClass, we wont be able to Inject right? thats why i passed it as parameter

**Review by deepharness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44843)* status: 8 file(s) to review. 

___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/GitIntegrationUtil.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/44843#-NQ-dmta8b4uHOVSgyy9:-NQ-jxI-7F5oLAEd7XuH:baf84af) ([raw file](https://github.com/harness/harness-core/blob/bcaa0e65a976e38d2f296ed07f765089875bc610/idp-service/src/main/java/io/harness/idp/gitintegration/GitIntegrationUtil.java#L18)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

In UtilityClass, we wont be able to Inject right? thats why i passed it as parameter
</blockquote></details>

you can add a dto later in case no. of parameters are more than 5.

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44843)* status: 8 file(s) to review. 

___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/GitIntegrationUtil.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/44843#-NQ-dmta8b4uHOVSgyy9:-NQ-rNP5DsFVFCEPzl_6:bb7oryy) ([raw file](https://github.com/harness/harness-core/blob/bcaa0e65a976e38d2f296ed07f765089875bc610/idp-service/src/main/java/io/harness/idp/gitintegration/GitIntegrationUtil.java#L18)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

you can add a dto later in case no. of parameters are more than 5.
</blockquote></details>

sure

**Review by vigneswara-propelo — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44843#-:-NQ-rizg6Y6WHZvLxq9n:bnfp4nl)* status: 8 file(s) to review.

**Review by vigneswara-propelo — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44843)* status: 8 file(s) to review.

**Review by devesh-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44843)* status: 8 file(s) to review.

**Review by devesh-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44843#-:-NQ-zeqIBz38du6KENt3:bnfp4nl)* status: 8 file(s) to review.

**Review by devesh-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44843)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by deepharness — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44843)* status: 1 file(s) to review.

**Review by sandeepa-kv-jois — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 6 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44843)* status: :shipit: complete! ✓

**Pull request merged**
