### PR TITLE
fix: [PL-23599]: Usage scope of git connector is ignored when using G…

### PR DESCRIPTION
**Pull request by abhinav-harness**
…raphql API for enabling git sync

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31375)

### CODE REVIEW

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31375)* status: 3 file(s) to review. 1 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java, line 1069 at r2](https://reviewable.io/reviews/harness/harness-core/31375#-My3tepCDhmEAe0R5lHJ:-My3tepCDhmEAe0R5lHK:b-4nt9wd) ([raw file](https://github.com/harness/harness-core/blob/84f089619ea45fce57de9179cc8ac1a4201a5e7f/400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java#L1069)):*
> ```Java
>   @Override
>   public SettingAttribute getWithRbac(String id) {
>     final SettingAttribute settingAttribute = getById(id);
> ```

do we need to check for this being null ?

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31375)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java, line 1068 at r2](https://reviewable.io/reviews/harness/harness-core/31375#-My5lMtB2nRT5miP_WQY:-My5lMtB2nRT5miP_WQZ:b-7v9v9h) ([raw file](https://github.com/harness/harness-core/blob/84f089619ea45fce57de9179cc8ac1a4201a5e7f/400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java#L1068)):*
> ```Java
> 
>   @Override
>   public SettingAttribute getWithRbac(String id) {
> ```

The get call of SettingAttribute should be following the rbac. Can we directly use the get method ?

**Comment by abhinav-harness** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java, line 1069 at r2](https://reviewable.io/reviews/harness/harness-core/31375#-My3tepCDhmEAe0R5lHJ:-My61jga5Uyi-jYYqWvA:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/84f089619ea45fce57de9179cc8ac1a4201a5e7f/400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java#L1069)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need to check for this being null ? 
</blockquote></details>

done

**Comment by abhinav-harness** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java, line 1068 at r2](https://reviewable.io/reviews/harness/harness-core/31375#-My5lMtB2nRT5miP_WQY:-My61kYC7dh5OOvLnXuX:b-ig7hra) ([raw file](https://github.com/harness/harness-core/blob/84f089619ea45fce57de9179cc8ac1a4201a5e7f/400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java#L1068)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

The get call of SettingAttribute should be following the rbac. Can we directly use the get method ?
</blockquote></details>

no, it doesnt

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31375)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31375)* status: :shipit: complete! ✓

___
*[400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java, line 1068 at r2](https://reviewable.io/reviews/harness/harness-core/31375#-My5lMtB2nRT5miP_WQY:-My6JoHc7TvRTGsK4yGZ:b-cp1axp) ([raw file](https://github.com/harness/harness-core/blob/84f089619ea45fce57de9179cc8ac1a4201a5e7f/400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java#L1068)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

no, it doesnt
</blockquote></details>

But then anybody who is using get of settingAttributes, can get the settingAttribute. 

In cg, they didn't had any rbac ?

Also in cg rbac is on the persistence layer right ? So maybe the get method is internally taking care of rbac ?

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31375)* status: :shipit: complete! ✓

___
*[400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java, line 1068 at r2](https://reviewable.io/reviews/harness/harness-core/31375#-My5lMtB2nRT5miP_WQY:-My6mHSDBD_hBIKMw4m0:b-fwe) ([raw file](https://github.com/harness/harness-core/blob/84f089619ea45fce57de9179cc8ac1a4201a5e7f/400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java#L1068)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

But then anybody who is using get of settingAttributes, can get the settingAttribute. 

In cg, they didn't had any rbac ?

Also in cg rbac is on the persistence layer right ? So maybe the get method is internally taking care of rbac ?
</blockquote></details>

yeah, i tried using other get - rbac was applied but it was with appid and we don't have appid in settingattributes 
(earlier we used to have). idk how others are working till now.

**Review by DeepakPatankar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31375)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
trigger ft2

**Pull request merged**
