### PR TITLE
feat: [PLG-2327]: Added endpoint to check for a valid credit card

### PR DESCRIPTION
**Pull request by thomas-grasman**
## Describe your changes
Added an API endpoint for validating a credit card's expiration date. 

By the time credit cards are saved into our database, they're already validated by Stripe and then by us to check for duplicates. This endpoint just checks to see if any cards are still valid.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48437)

### CODE REVIEW

**Comment by thomas-grasman** [comment]
trigger uts

**Comment by thomas-grasman** [comment]
trigger messagecheck

**Comment by thomas-grasman** [comment]
trigger uts

**Comment by thomas-grasman** [comment]
trigger ut3

**Review by neelam-harness — CHANGES_REQUESTED** [review]
looks good overall. Thanks

**Comment by thomas-grasman** [comment]
trigger uts

**Comment by thomas-grasman** [comment]
trigger uts

**Review by Xin-Harness — APPROVED** [review]

**Review by neelam-harness — APPROVED** [review]

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48437)* status: 5 file(s) to review. 1 change requests. 

___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/resource/CreditCardResource.java` line 78 at r2](https://reviewable.io/reviews/harness/harness-core/48437#-NXObRSN6nNZx9ygRnXQ:-NXObRSN6nNZx9ygRnXR:bx4y2vd) ([raw file](https://github.com/harness/harness-core/blob/e149d47c715560728688afd0d5df231770b30d9c/930-ng-license-manager/src/main/java/io/harness/subscription/resource/CreditCardResource.java#L78)):*
> ```Java
>       @Valid @RequestBody(description = "Non-sensitive credit card information") @NotNull CreditCardDTO creditCardDTO) {
>     return ResponseDTO.newResponse(creditCardService.saveCreditCard(creditCardDTO));
>   }
> ```

new line should be added
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/CreditCardServiceImpl.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/48437#-NXOas5cAUT6I5WiDXpr:-NXOas5cAUT6I5WiDXps:b-jgnjqa) ([raw file](https://github.com/harness/harness-core/blob/e149d47c715560728688afd0d5df231770b30d9c/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/CreditCardServiceImpl.java#L84)):*
> ```Java
>   }
> 
>   private boolean hasUnexpiredCard(List<CardDTO> creditCards) {
> ```

it should be renamed to hasAtleastOneUnexpiredCard()

**Comment by thomas-grasman** [comment]
trigger uts

**Review by thomas-grasman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48437)* status: 5 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/resource/CreditCardResource.java` line 78 at r2](https://reviewable.io/reviews/harness/harness-core/48437#-NXObRSN6nNZx9ygRnXQ:-NXQjqsL6ecCPNbO7Lhs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e149d47c715560728688afd0d5df231770b30d9c/930-ng-license-manager/src/main/java/io/harness/subscription/resource/CreditCardResource.java#L78)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

new line should be added
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/CreditCardServiceImpl.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/48437#gh-1213427282:-NXQjrXD2WzAlMcagB_4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e2ac508efa9e976d5a5c6d08a82d12e8c376b705/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/CreditCardServiceImpl.java#L63)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

let's log the error ?

log.error("Customer with accountIdentifier = {} doesn't exist.", accountIdentifier)
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/CreditCardServiceImpl.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/48437#gh-1213435442:-NXQjroc3HLWkB882NtD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e2ac508efa9e976d5a5c6d08a82d12e8c376b705/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/CreditCardServiceImpl.java#L71)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

let's put this conditions in helper methods with explanatory names to make it more readable, easier to fix the individual pieces if any issues arise. for ex: 
`!creditCards.isEmpty() && hasUnExpiredCard(...)`
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/CreditCardServiceImpl.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/48437#-NXOas5cAUT6I5WiDXpr:-NXQjsRL48wiiggaRCMw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e149d47c715560728688afd0d5df231770b30d9c/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/CreditCardServiceImpl.java#L84)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

it should be renamed to hasAtleastOneUnexpiredCard()
</blockquote></details>

Done.

**Review by Xin-Harness — APPROVED** [review]

**Review by kapil-harness — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48437)* status: 5 file(s) to review. 2. unresolved discussions. 

___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/CreditCardService.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/48437#-NXRQKAC40P7peYpDrl_:-NXRQKAD-MvmOoyKNzkw:byceo8k) ([raw file](https://github.com/harness/harness-core/blob/7fac5b8b539670111121c4a5e56b21ade7ae9a5e/930-ng-license-manager/src/main/java/io/harness/subscription/services/CreditCardService.java#L15)):*
> ```Java
> public interface CreditCardService {
>   CreditCardResponse saveCreditCard(CreditCardDTO creditCardDTO);
>   boolean hasValidCard(String accountIdentifier);
> ```

nit: newline should be added, pls take care of it in your next PR

**Comment by thomas-grasman** [comment]
trigger review

**Pull request merged**
