### PR TITLE
[feat]: [CDS-41388]: Add Rollback scafolding

### PR DESCRIPTION
**Pull request by nassergonzalez**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36655)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 21 Issues 
* Vulnerability 3 Vulnerabilities 
 * Code issue 18 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36655)

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 23 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36655)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/AzureARMRollbackResourceStepPlanCreator.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/36655#-NADW7_E5wr5ssIZeLNy:-NADW7_E5wr5ssIZeLNz:b-qw0d4v) ([raw file](https://github.com/harness/harness-core/blob/7f920033a260dfe29aafd0e449be8d87872e78c4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/AzureARMRollbackResourceStepPlanCreator.java#L18)):*
> ```Java
> import java.util.Set;
> 
> public class AzureARMRollbackResourceStepPlanCreator extends CDPMSStepPlanCreatorV2<AzureARMRollbackStepNode> {
> ```

@OwnedBy



_Code quote:_
```Java
extends CDPMSStepPlanCreatorV2
```
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureBlueprintTaskNGResponse.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/36655#-NADYtp16XhQ_MxCCvGe:-NADYtp16XhQ_MxCCvGf:b-pen7c9) ([raw file](https://github.com/harness/harness-core/blob/7f920033a260dfe29aafd0e449be8d87872e78c4/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureBlueprintTaskNGResponse.java#L21)):*
> ```Java
> @Data
> @EqualsAndHashCode(callSuper = true)
> public class AzureBlueprintTaskNGResponse extends AzureTaskNGResponse {
> ```

OwnedBy

**Review by vlica-harness — APPROVED** [review]
> Reviewed 20 of 25 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36655)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36655)* status: :shipit: complete! ✓

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 20 of 25 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36655)* status: :shipit: complete! ✓

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 20 of 25 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36655)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36655)* status: :shipit: complete! ✓

**Pull request merged**
