### PR TITLE
feat: [SRM-12014]: API for getting verification job instance

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Describe your changes
endpoint: "/cv/api/verify-step/verification-job-instance/{verifyStepExecutionId}"

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37482)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Vulnerability 1 Vulnerabilities 
 
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37482)

**Review by arpit-harness — APPROVED** [review]
:lgtm: suggestion: @deepak-harness should we make a method in CVNGStepTaskService and use that in the resource instead of directly using verificationJobInstanceService. Currently it looks out of place.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37482#-:-NBvPSk15lnBZwMe0HAT:bsizrgx)* status: 1 file(s) to review.

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37482)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/cdng/resources/CVNGStepResource.java` line 226 at r3](https://reviewable.io/reviews/harness/harness-core/37482#-NBw43K66y0V6Y9pombz:-NBw43K66y0V6Y9pomc-:bjae1pa) ([raw file](https://github.com/harness/harness-core/blob/40b20d30c9bb44b6290838e2927cc93d38198bed/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/resources/CVNGStepResource.java#L226)):*
> ```Java
>   @ExceptionMetered
>   @ApiOperation(value = "get verification job instance", nickname = "getVerificationJobInstance", hidden = true)
>   public RestResponse<VerificationJobInstance> getVerificationJobInstance(
> ```

Lets move the API to new resource primarily for automation.  That way it will be easier to mange the APIs for automation, also authentication can be clubbed if required in future.

**Review by deepak-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37482)* status: 4 file(s) to review. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/cdng/services/api/CVNGStepTaskService.java` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/37482#-NC0CfKaDeaJPgqHacpQ:-NC0CfKaDeaJPgqHacpR:brs3y5h) ([raw file](https://github.com/harness/harness-core/blob/90d120b32880c319ab5f0b36dc3ed074ddf5f028/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/services/api/CVNGStepTaskService.java#L34)):*
> ```Java
>   void notifyCVNGStep(CVNGStepTask entity);
>   CVNGStepTask getByCallBackId(String callBackId);
>   VerificationJobInstance getByVerificationJobInstanceId(String verificationJobInstanceId);
> ```

nit: we can directly inject the verificationJobInstanceService in the AutomationResource.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37482)* status: :shipit: complete! ✓

**Pull request merged**
