### PR TITLE
fix: [CDS-48194]: Add support for page size for list files

### PR DESCRIPTION
**Pull request by abosii-harness**
## Describe your changes
Does look like for listening files for stash (bitbucket server) provider it does require page size, otherwise it will result in not properly handling the page.

Adding this as common for every provider in case if this would be an issue and for other providers and only if requested page size is >0, otherwise will use the previous behavior. Will handle on delegate to set page size only for bitbucket server. 

### Without Page Size
Page **#1**
Screenshot 2022-12-09 at 11 51 25
Page **#2**
Screenshot 2022-12-09 at 11 52 00
Page **#3**
Screenshot 2022-12-09 at 11 52 34

###  With page size
Page **#1**
Screenshot 2022-12-09 at 11 54 59
Page **#2**
Screenshot 2022-12-09 at 11 56 06
Page **#3**
Screenshot 2022-12-09 at 11 57 04
Page **#4**
Screenshot 2022-12-09 at 11 58 18

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41371)

### CODE REVIEW

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41371)* status: Some of the checks are too old. 2 file(s) to review. 1 of 2 approvals obtained.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41371)* status: Some of the checks are too old.

**Comment by abosii-harness** [comment]
trigger ft1

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41371#-:-NJANDdG-6dnd6BQhTkO:bnfp4nl)* status: 1 of 2 approvals obtained.

**Review by vikyathharekal — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41371#-:-NJAUXfB4k8Akgyg74aS:bg7igkv)* status: :shipit: complete! ✓

**Pull request merged**
