### PR TITLE
feat: [IDP-197]: IDP Service Auth Integration

### PR DESCRIPTION
**Pull request by sathish-soundarapandian**
## Describe your changes
IDP Service Auth Integration

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44222)

### CODE REVIEW

**Review by sandeepa-kv-jois — APPROVED** [review]

**Review by sandeepa-kv-jois — DISMISSED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44222)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by devesh-harness — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44222)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by deepharness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44222)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`idp-service/config/config.yml` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/44222#-NOwjOXA5VMlm510EGqh:-NOwjOXA5VMlm510EGqi:bpsyiuq) ([raw file](https://github.com/harness/harness-core/blob/ec90d33247a0694e4cc0681af1774fff39568eda/idp-service/config/config.yml#L71)):*
> ```YAML
> 
> ngManagerServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
> idpServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
> ```

Why we are keeping secrets in config file . Can these be set during deployment using helm  
___
*[`idp-service/modules/contracts/src/main/java/io/harness/idp/annotations/IdpServiceAuth.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/44222#-NOwkoQ-2dU4zpwGnBna:-NOwkoQ-2dU4zpwGnBnb:b-l6jr1v) ([raw file](https://github.com/harness/harness-core/blob/ec90d33247a0694e4cc0681af1774fff39568eda/idp-service/modules/contracts/src/main/java/io/harness/idp/annotations/IdpServiceAuth.java#L24)):*
> ```Java
> @Retention(RetentionPolicy.RUNTIME)
> @Target({ElementType.METHOD, ElementType.TYPE})
> public @interface IdpServiceAuth {}
> ```

why are we using markup interface , if possible use annotation as interface without any method doesn't make much sense 
___
*[`idp-service/modules/contracts/src/main/java/io/harness/idp/annotations/IdpServiceAuthIfHasApiKey.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/44222#-NOwkGcB5wtn1V32ADyM:-NOwkGcB5wtn1V32ADyN:b-u3jduc) ([raw file](https://github.com/harness/harness-core/blob/ec90d33247a0694e4cc0681af1774fff39568eda/idp-service/modules/contracts/src/main/java/io/harness/idp/annotations/IdpServiceAuthIfHasApiKey.java#L26)):*
> ```Java
> @Retention(RetentionPolicy.RUNTIME)
> @Target({ElementType.METHOD})
> public @interface IdpServiceAuthIfHasApiKey {}
> ```

naming is not correct . does "IdpServiceAuthIfHasApiKey" has anything to do with IdpServiceAuth . Also why are we using markup interface , if possible use annotation as interface without any method doesn't make much sense 



_Code quote:_
```Java
IdpServiceAuthIfHasApiKey
```

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44222)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/config/config.yml` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/44222#-NOwjOXA5VMlm510EGqh:-NOwoqoT6s21P_LzQtsC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ec90d33247a0694e4cc0681af1774fff39568eda/idp-service/config/config.yml#L71)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Why we are keeping secrets in config file . Can these be set during deployment using helm  
</blockquote></details>

Done.
___
*[`idp-service/modules/contracts/src/main/java/io/harness/idp/annotations/IdpServiceAuth.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/44222#-NOwkoQ-2dU4zpwGnBna:-NOwowfh8EHw5a-PjC5T:bqb056u) ([raw file](https://github.com/harness/harness-core/blob/ec90d33247a0694e4cc0681af1774fff39568eda/idp-service/modules/contracts/src/main/java/io/harness/idp/annotations/IdpServiceAuth.java#L24)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

why are we using markup interface , if possible use annotation as interface without any method doesn't make much sense 
</blockquote></details>

Have used the same convention that we have in other modules. Ex. "PipelineServiceAuth", "PipelineServiceAuthIfHasApiKey".
Actually it is annotation only. Have used as "@interface". marker interface (public interface) though it is just plain interface without any methods.
___
*[`idp-service/modules/contracts/src/main/java/io/harness/idp/annotations/IdpServiceAuthIfHasApiKey.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/44222#-NOwkGcB5wtn1V32ADyM:-NOwpkxI1FFW6ckJWcsn:b-2d60jg) ([raw file](https://github.com/harness/harness-core/blob/ec90d33247a0694e4cc0681af1774fff39568eda/idp-service/modules/contracts/src/main/java/io/harness/idp/annotations/IdpServiceAuthIfHasApiKey.java#L26)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

naming is not correct . does "IdpServiceAuthIfHasApiKey" has anything to do with IdpServiceAuth . Also why are we using markup interface , if possible use annotation as interface without any method doesn't make much sense 
</blockquote></details>

This annotation is used for APIs in idp-service which can be authenticated using X-API-KEY in request headers.
Have used the same convention that we have in other modules. Ex. "PipelineServiceAuth", "PipelineServiceAuthIfHasApiKey".
Actually it is annotation only. Have used as "@interface". marker interface (public interface) though it is just plain interface without any methods.

**Review by deepharness — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44222)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by devesh-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44222)* status: :shipit: complete! ✓

**Pull request merged**
