### PR TITLE
[fix]: [PL-22135]: Fixed remove from context

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
Fixed remove from context

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30304)

### CODE REVIEW

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30304)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by ashishsanodia-harness — APPROVED** [review]

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30304)* status: 1 file(s) to review. 

___
*[953-events-api/src/main/java/io/harness/eventsframework/impl/redis/monitoring/context/RedisEventMetricContext.java, line 29 at r1](https://reviewable.io/reviews/harness/harness-core/30304#-MuUcx1a4EMeWXfNniL8:-MuUcx1a4EMeWXfNniL9:bchybeu) ([raw file](https://github.com/harness/harness-core/blob/71ab4b14c8127eb38834ac78d53eccccd842626f/953-events-api/src/main/java/io/harness/eventsframework/impl/redis/monitoring/context/RedisEventMetricContext.java#L29)):*
> ```Java
> @Slf4j
> public class RedisEventMetricContext implements AutoCloseable {
>   Map<String, String> map = new HashMap<>();
> ```

I think some better name should be given to the map. eg: ContextKeysMap or something.
___
*[953-events-api/src/main/java/io/harness/eventsframework/impl/redis/monitoring/context/RedisEventMetricContext.java, line 40 at r1](https://reviewable.io/reviews/harness/harness-core/30304#-MuUduAp3uh1Qg-eogxF:-MuUduAp3uh1Qg-eogxG:b-cqt0t9) ([raw file](https://github.com/harness/harness-core/blob/71ab4b14c8127eb38834ac78d53eccccd842626f/953-events-api/src/main/java/io/harness/eventsframework/impl/redis/monitoring/context/RedisEventMetricContext.java#L40)):*
> ```Java
>   private void removeFromContext() {
>     for (Map.Entry<String, String> entry : map.entrySet()) {
>       ThreadContext.remove(entry.getValue());
> ```

We could just simply do: ThreadContext.removeAll(map.keySet()); No need of a loop here actually.
___
*[953-events-api/src/main/java/io/harness/eventsframework/impl/redis/monitoring/context/RedisEventMetricContext.java, line 49 at r1](https://reviewable.io/reviews/harness/harness-core/30304#-MuUd2d90vtOqpeYWRp3:-MuUd2d90vtOqpeYWRp4:bk6t1i6) ([raw file](https://github.com/harness/harness-core/blob/71ab4b14c8127eb38834ac78d53eccccd842626f/953-events-api/src/main/java/io/harness/eventsframework/impl/redis/monitoring/context/RedisEventMetricContext.java#L49)):*
> ```Java
>   }
> 
>   private void updateThreadAndMap(String key, String value) {
> ```

probably a better name could be : updateThreadContext(). It doesn't need to talk that it updates some map as well. Thats internal for the class to know.

**Comment by rathodmeetsatish** [comment]
trigger messagecheck

**Review by mohitg0795 — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30304#-:-MuVF8992RxzT2smntP1:bnfp4nl)* status: 1 file(s) to review.

**Comment by rathodmeetsatish** [comment]
trigger messagecheck

**Comment by rathodmeetsatish** [comment]
trigger messagecheck

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30304)* status: 1 file(s) to review.

**Review by abhinav-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30304)* status: 1 file(s) to review.

**Review by abhinav-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30304#-:-MuVIU9l3XuAjLXMcQjX:bnfp4nl)* status: 1 file(s) to review.

**Review by abhinav-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30304#-:-MuVIgfKCwZzp8nPVvQ2:bnfp4nl)* status: 1 file(s) to review.

**Review by abhinav-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30304#-:-MuVInRTB71H0xjAgwpr:bnfp4nl)* status: 1 file(s) to review.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30304)* status: :shipit: complete! ✓

**Pull request merged**
