### PR TITLE
feat: [DEL-2573]: Selection log improvements

### PR DESCRIPTION
**Pull request by jennyjames21**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30929)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java, line 853 at r1](https://reviewable.io/reviews/harness/harness-core/30929#-MwbeH323GoX4ca9q2jL:-MwbeH323GoX4ca9q2jM:b9qukzk) ([raw file](https://github.com/harness/harness-core/blob/61cdd56c1c3c8b3afced9ffa72b4c06f0d925429/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L853)):*
> ```Java
>                                 .map(Delegate::getUuid)
>                                 .collect(Collectors.toList());
>       if (task.isSelectionLogsTrackingEnabled()) {
> ```

use FF instead

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30929)* status: 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
image

**Comment by jennyjames21** [comment]
image

**Comment by jennyjames21** [comment]
image

**Comment by jennyjames21** [comment]
trigger checkstyle

**Comment by jennyjames21** [comment]
trigger ti1

**Comment by jennyjames21** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java, line 853 at r1](https://reviewable.io/reviews/harness/harness-core/30929#-MwbeH323GoX4ca9q2jL:-Mwe56-35Em4nRq0UG98:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/61cdd56c1c3c8b3afced9ffa72b4c06f0d925429/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L853)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

use FF instead 
</blockquote></details>

Done.

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java, line 982 at r4](https://reviewable.io/reviews/harness/harness-core/30929#-MwhwXI-2_EF9zVc0GQj:-MwhwXI0DLR-DCI5qL2J:bqebhii) ([raw file](https://github.com/harness/harness-core/blob/39614f391dde709cb760b152b740b2239353416f/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L982)):*
> ```Java
>         boolean isTaskNg =
>             !isEmpty(task.getSetupAbstractions()) && Boolean.parseBoolean(task.getSetupAbstractions().get(NG));
>         accountDelegates = accountDelegates.stream().filter(delegate -> delegate.isNg() == isTaskNg).collect(toList());
> ```

why this change?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 4 of 8 files at r2, 3 of 7 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30929)* status: 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java, line 982 at r4](https://reviewable.io/reviews/harness/harness-core/30929#-MwhwXI-2_EF9zVc0GQj:-MwhxGS-0kgCLje-41q0:bz5dbtq) ([raw file](https://github.com/harness/harness-core/blob/39614f391dde709cb760b152b740b2239353416f/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L982)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why this change?
</blockquote></details>

Before we were filtering account delegates based on isTaskNg flag in batch  (comparing delegate.isNG with task.isNg) . Since we removed batch, had to fetch the info directly from task. 
Without this we will send all active delegates instead of only NG delegates or CG delegates.

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 3 of 8 files at r2, 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30929)* status: 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by raghuAtWings — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30929)* status: :shipit: complete! ✓

**Pull request merged**
