### PR TITLE
[fix]: [PLG-2086]: migration to update value of isCrossGenerationAccessEnabled for all the accounts

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
migration to update value of isCrossGenerationAccessEnabled for all the accounts using below logic:
1. if non-CD account then isCrossGenerationAccessEnabled=false
2. else if CD account
     a. defaultExperience=NG then isCrossGenerationAccessEnabled=true
     b. defaultExperience=CG then
           i. if FF PL_HIDE_LAUNCH_NEXTGEN is enabled then isCrossGenerationAccessEnabled=false
           ii. if FF PL_HIDE_LAUNCH_NEXTGEN is disabled then isCrossGenerationAccessEnabled=true 

Test scenarios -> https://harness.atlassian.net/wiki/spaces/GTM/pages/21350842480/New+CG+NG+transition+feature+testing+scenarios
     
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45487)

### CODE REVIEW

**Review by thomas-grasman — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45487)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/45487#-NR9VRPhE1p9Iv7LBlT7:-NR9VRPhE1p9Iv7LBlT8:b-udc09n) ([raw file](https://github.com/harness/harness-core/blob/bcdc709383ea5b80c60bfa9b03dc3f050b29c1a1/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L80)):*
> ```Java
> 
>             wingsPersistence.update(account, updateOperations);
>             accountsLeftForMigration.remove(account.getUuid());
> ```

we shouldn't insert and remove from a list to track the failure accounts. Simply, if we add accounts in catch block, then we get list of accounts for which migration failed.

**Comment by mohitg0795** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/45487#-NR9Va1iClOB2NrG6gJp:-NR9Va1iClOB2NrG6gJq:b-pcbrk0) ([raw file](https://github.com/harness/harness-core/blob/bcdc709383ea5b80c60bfa9b03dc3f050b29c1a1/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L83)):*
> ```Java
>             log.info("isCrossGenerationAccessEnabled field is successfully added into account: {}", account.getUuid());
>           } catch (Exception e) {
>             log.error("Error while updating isCrossGenerationAccessEnabled field for account: {}",
> ```

whats the recovery mechanism for accounts for which migration failed?

**Comment by mohitg0795** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/45487#-NR9VfgC-Q7PXsv0XV3F:-NR9VfgC-Q7PXsv0XV3G:bthpjxa) ([raw file](https://github.com/harness/harness-core/blob/bcdc709383ea5b80c60bfa9b03dc3f050b29c1a1/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L98)):*
> ```Java
>   private boolean isCdModuleLicenseNotPresent(String accountIdentifier) {
>     AccountLicenseDTO accountLicenseDTO =
>         NGRestUtils.getResponse(ngLicenseHttpClient.getAccountLicensesDTO(accountIdentifier));
> ```

can we log the response for each request

**Comment by mohitg0795** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/45487#-NR9Vilp0T9iellnJwm3:-NR9Vilp0T9iellnJwm4:b-tk03xq) ([raw file](https://github.com/harness/harness-core/blob/bcdc709383ea5b80c60bfa9b03dc3f050b29c1a1/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L78)):*
> ```Java
>               }
>             }
> ```

lets log update statement for each account

**Comment by mohitg0795** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/45487#-NR9VmCWDGAES6UeX9m7:-NR9VmCWDGAES6UeX9m8:bhlm7zl) ([raw file](https://github.com/harness/harness-core/blob/bcdc709383ea5b80c60bfa9b03dc3f050b29c1a1/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L58)):*
> ```Java
>           Account account = null;
>           try {
>             account = records.next();
> ```

you can create a try block with AccountLogContext which will ensure that account id is present in all logs by default.

**Review by neelam-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45487)* status: 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/45487#-NR9xNTlDTOmU7skI6nz:-NR9xNTlDTOmU7skI6o-:bkt5zk4) ([raw file](https://github.com/harness/harness-core/blob/bcdc709383ea5b80c60bfa9b03dc3f050b29c1a1/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L72)):*
> ```Java
> 
>                 if (isFfEnabled) {
>                   updateOperations.set(AccountKeys.isCrossGenerationAccessEnabled, Boolean.FALSE);
> ```

we can simplify this code block by something like this:



_Code snippet:_
```Java
boolean crossGenAccessValue = accountService.isFeatureFlagEnabled(FeatureName.PL_HIDE_LAUNCH_NEXTGEN.name(), account.getUuid()) 
                              ? Boolean.FALSE
                              : Boolean.TRUE;
updateOperations.set(AccountKeys.isCrossGenerationAccessEnabled, crossGenAccessValue);
```
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/45487#-NR9Vilp0T9iellnJwm3:-NR9sv-i-Oalobb9lctO:b32v57) ([raw file](https://github.com/harness/harness-core/blob/bcdc709383ea5b80c60bfa9b03dc3f050b29c1a1/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L78)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets log update statement for each account 
</blockquote></details>

+1
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/45487#-NR9VRPhE1p9Iv7LBlT7:-NR9y0RW9fQwTwxFQ46b:b-ul8jrf) ([raw file](https://github.com/harness/harness-core/blob/bcdc709383ea5b80c60bfa9b03dc3f050b29c1a1/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L80)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we shouldn't insert and remove from a list to track the failure accounts. Simply, if we add accounts in catch block, then we get list of accounts for which migration failed.
</blockquote></details>

Good idea
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/45487#-NR9Va1iClOB2NrG6gJp:-NR9yGWD0DKXDI-wA9l3:b2rb20j) ([raw file](https://github.com/harness/harness-core/blob/bcdc709383ea5b80c60bfa9b03dc3f050b29c1a1/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L83)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

if that happens then we may need to do either of the below:
1. re-run the same migration again
2. update the value via mongo update query via OPS ticket
</blockquote></details>

Please add the link to the test wiki as well for reference.

**Review by neelam-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45487)* status: 1 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/45487#-NR9yb1G5xh1fVmZiU71:-NR9yb1G5xh1fVmZiU72:bf4cvnt) ([raw file](https://github.com/harness/harness-core/blob/bcdc709383ea5b80c60bfa9b03dc3f050b29c1a1/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L62)):*
> ```Java
>             UpdateOperations<Account> updateOperations = wingsPersistence.createUpdateOperations(Account.class);
> 
>             if (isCdModuleLicenseNotPresent(account.getUuid())) {
> ```

Let's rename this method to `isModuleTypeCd(account)`

**Comment by kapil-harness** [comment]
**Local testing results:**

Total accounts=5

**Before migration runs:**

BAC4567890123456789012 -> non-CD account -> not having isCrossGen
1234567890123456789012 -> non-CD account -> having isCrossGen
__GLOBAL_ACCOUNT_ID__  -> non-CD account -> having isCrossGen
kmpySmUISimoRrJL6NL73w -> CD account 	 -> having isCrossGen 		-> defaultExp=CG and PL_HIDE=true
PQRySmUISimoRrJL6NL73w -> CD account     -> not having isCrossGen 	-> defaultExp=NG and PL_HIDE=true


**After migration runs:**

BAC4567890123456789012 -> adds isCrossGen=false
1234567890123456789012 -> updates isCrossGen=false
__GLOBAL_ACCOUNT_ID__  -> updates isCrossGen=false
kmpySmUISimoRrJL6NL73w -> updates isCrossGen=false
PQRySmUISimoRrJL6NL73w -> adds isCrossGen=true

Screenshot 2023-03-22 at 8 54 28 PM

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45487)* status: 1 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/45487#-NR9yb1G5xh1fVmZiU71:-NRA0oE86G6wwHpKyU1S:b-3yudos) ([raw file](https://github.com/harness/harness-core/blob/bcdc709383ea5b80c60bfa9b03dc3f050b29c1a1/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L62)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

Let's rename this method to `isModuleTypeCd(account)`
</blockquote></details>

how about isAccountNonCd()
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/45487#-NR9xNTlDTOmU7skI6nz:-NRA0t2z3gdcNMB4mi3q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bcdc709383ea5b80c60bfa9b03dc3f050b29c1a1/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L72)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

we can simplify this code block by something like this:
</blockquote></details>

Done.
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/45487#-NR9Vilp0T9iellnJwm3:-NRA0tcIBtNedrqxJFmN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bcdc709383ea5b80c60bfa9b03dc3f050b29c1a1/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L78)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/45487#-NR9VRPhE1p9Iv7LBlT7:-NRA0uLu41ZZdaCAku3t:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bcdc709383ea5b80c60bfa9b03dc3f050b29c1a1/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L80)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

Good idea
</blockquote></details>

Done.
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/45487#-NR9Va1iClOB2NrG6gJp:-NRA0vBA9Hn3YqmtYW2t:b-7v5bb2) ([raw file](https://github.com/harness/harness-core/blob/bcdc709383ea5b80c60bfa9b03dc3f050b29c1a1/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L83)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

Please add the link to the test wiki as well for reference. 
</blockquote></details>

attached in PR description

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45487)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by kapil-harness** [comment]
trigger messagecheck

**Review by thomas-grasman — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45487)* status: :shipit: complete! ✓

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45487)* status: 1 change requests. 1. unresolved discussions. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 105 at r3](https://reviewable.io/reviews/harness/harness-core/45487#-NRA3Zix9xpjJRyVnuTB:-NRA5wgD7Kx1wPvdEQPc:b-r2r9s2) ([raw file](https://github.com/harness/harness-core/blob/443abc28aee0d7a1226369ce9d19977a7734bd0a/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L105)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

I don't think it's a good idea to emit the whole `accountLicenseDTO` for 13K+ accounts as an info log. This will impact the performance and also it's emitting the customer information in the logs that might be sensitive information. Perhaps consider emitting only the fields that you're interested for the troubleshooting purposes. 
</blockquote></details>

AccountLicenseDTO has 4 values in it i.e. accountID, allModuleLicenses, createdAt and updatedAt.
Amongst these only allModuleLicenses is the chunky one but that will also have max 10-12 values if subscribed for all the modules.
We want these data points to debug better in case of non-CD accounts if some wrong value is added for a customer.
Its not a sensitive info as all the terms are harness internal terms, does not make sense to anyone like accountId, license, etc.

**Review by thomas-grasman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45487)* status: 1 change requests. 1. unresolved discussions.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45487)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45487)* status: 1 change requests. 1. unresolved discussions.

**Review by neelam-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45487#-:-NRAEi950A1H639co_1M:bnfp4nl)* status: :shipit: complete! ✓

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 105 at r3](https://reviewable.io/reviews/harness/harness-core/45487#-NRA4_3XEAado5QZ_7Yr:-NRA4_3XEAado5QZ_7Ys:b-khx4g0) ([raw file](https://github.com/harness/harness-core/blob/443abc28aee0d7a1226369ce9d19977a7734bd0a/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L105)):*
> I don't think it's a good idea to emit the whole accountLicenseDTO for 13K+ accounts as an info log. This will impact the performance and also it's emitting the customer information in the logs that might be sensitive information. Perhaps consider emitting only the fields that you're interested for the troublesho
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java` line 105 at r3](https://reviewable.io/reviews/harness/harness-core/45487#-NRA3Zix9xpjJRyVnuTB:-NRAEaDK7DYiQvTTOxCs:bacn737) ([raw file](https://github.com/harness/harness-core/blob/443abc28aee0d7a1226369ce9d19977a7734bd0a/390-db-migration/src/main/java/io/harness/migrations/all/UpdateIsCrossGenerationAccessEnabledForAllAccountsMigration.java#L105)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

removed the AccountLicenseDTO and added a more lean log
</blockquote></details>

Thanks Kapil.

**Pull request merged**
