### PR TITLE
[feat]: [CDS-83334]: Invalidate git file cache after the webhook is created or updated

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added code to invalidate the git file cache when the webhook is created or updated. Have tested out the same locally, its working as expected.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54981)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54981)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 360 at r1](https://reviewable.io/reviews/harness/harness-core/54981#-NifXMCg8MPDWBgp9IBD:-NifXMCg8MPDWBgp9IBE:b-p71e9s) ([raw file](https://github.com/harness/harness-core/blob/6bd24c6286a0d896dedf0516e28a99512ab572cc/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L360)):*
> ```Java
> 
>   private void clearCache(
>       String accountIdentifier, String repoName, String webhookIdentifier, String webhookOperation) {
> ```

we can't be taking params just for logging purpose. Please remove redundant params.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54981)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/54981#-NifXRxU8N5keCqsRbTW:-NifXRxU8N5keCqsRbTX:b-jfhm69) ([raw file](https://github.com/harness/harness-core/blob/6bd24c6286a0d896dedf0516e28a99512ab572cc/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L104)):*
> ```Java
>               String.format("Error while saving webhook [%s] in DB", gitXWebhook.getIdentifier()));
>         }
>         clearCache(
> ```

what if this call fails? We don't want to block creation operation coz we couldn't clear cache.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54981)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/54981#-NifXRxU8N5keCqsRbTW:-NifXdgl3cP7i3NHy1ot:bo1jqv9) ([raw file](https://github.com/harness/harness-core/blob/6bd24c6286a0d896dedf0516e28a99512ab572cc/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L104)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if this call fails? We don't want to block creation operation coz we couldn't clear cache.
</blockquote></details>

or I would suggest to do this operation first and then create webhook. In that case we can make it blocking operation.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54981)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/54981#-NifXodS0J-GPvyoSG3V:-NifXodS0J-GPvyoSG3W:ba9n5dd) ([raw file](https://github.com/harness/harness-core/blob/6bd24c6286a0d896dedf0516e28a99512ab572cc/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L96)):*
> ```Java
>         log.info(String.format("Creating Webhook with identifier %s in account %s",
>             createGitXWebhookRequestDTO.getWebhookIdentifier(), createGitXWebhookRequestDTO.getAccountIdentifier()));
>         registerWebhookOnGit(gitXWebhook.getAccountIdentifier(), gitXWebhook.getRepoName(),
> ```

On side note, I've qq here: What happens if we register webhook again for an already registered repo?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54981)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 193 at r1](https://reviewable.io/reviews/harness/harness-core/54981#-NifXunP6agXaoFJW2dv:-NifXunP6agXaoFJW2dw:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/6bd24c6286a0d896dedf0516e28a99512ab572cc/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L193)):*
> ```Java
>               "Error while updating webhook [%s] in DB", updateGitXWebhookCriteriaDTO.getWebhookIdentifier()));
>         }
>         clearCache(updatedGitXWebhook.getAccountIdentifier(), updatedGitXWebhook.getRepoName(),
> ```

same as above

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54981)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImplTest.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/54981#-NifXy2D4LW9ztDuS98f:-NifXy2D4LW9ztDuS98g:benzwc4) ([raw file](https://github.com/harness/harness-core/blob/6bd24c6286a0d896dedf0516e28a99512ab572cc/136-git-sync-manager/src/test/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImplTest.java#L67)):*
> ```Java
>   @Mock GitSyncConnectorService gitSyncConnectorService;
>   @Mock WebhookEventService webhookEventService;
>   @Mock GitFileCacheService gitFileCacheService;
> ```

redundant changes?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54981)* status: 2 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/54981#-NifXodS0J-GPvyoSG3V:-NihmDm6EtCjW9VSScoP:b-8pkdly) ([raw file](https://github.com/harness/harness-core/blob/4a71dd2a6f394a53a0651df71a2b7313fcf17115/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L96)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

On side note, I've qq here: What happens if we register webhook again for an already registered repo?
</blockquote></details>

We throw an error stating that webhook is already present for this repo 
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/54981#-NifXRxU8N5keCqsRbTW:-NiigCMf0CNEVdfN90DU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4a71dd2a6f394a53a0651df71a2b7313fcf17115/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L104)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

or I would suggest to do this operation first and then create webhook. In that case we can make it blocking operation.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 193 at r1](https://reviewable.io/reviews/harness/harness-core/54981#-NifXunP6agXaoFJW2dv:-NiigCaDCY-gElwUnjJU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4a71dd2a6f394a53a0651df71a2b7313fcf17115/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L193)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 360 at r1](https://reviewable.io/reviews/harness/harness-core/54981#-NifXMCg8MPDWBgp9IBD:-NiigDGR-b6k4DNIyRgX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4a71dd2a6f394a53a0651df71a2b7313fcf17115/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L360)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we can't be taking params just for logging purpose. Please remove redundant params.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImplTest.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/54981#-NifXy2D4LW9ztDuS98f:-Nii-5I93LciHeKh6mxM:bwwm8qt) ([raw file](https://github.com/harness/harness-core/blob/4a71dd2a6f394a53a0651df71a2b7313fcf17115/136-git-sync-manager/src/test/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImplTest.java#L67)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

redundant changes?
</blockquote></details>

no we need this for the uts, if not the we try to invoke the gitFileCacheService

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54981)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 361 at r2](https://reviewable.io/reviews/harness/harness-core/54981#-Nin1YBc1Ij0HAH3rx1A:-Nin1YBc1Ij0HAH3rx1B:b-ox0hut) ([raw file](https://github.com/harness/harness-core/blob/74805c0cb6fe01addffd1582de6113abcdc3c3d9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L361)):*
> ```Java
>           GitFileCacheKey.builder().accountIdentifier(accountIdentifier).repoName(repoName).build();
>       GitFileCacheDeleteResult gitFileCacheDeleteResult = gitFileCacheService.invalidateCache(cacheKey);
>       log.info("Invalidated cache for key: {} , result: {}", cacheKey, gitFileCacheDeleteResult);
> ```

I think lets move this line into the invalideCache method itself so that it gets logged for all cases. We may need this for future reference also when we try to fix our reload-from-git thing.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54981)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 362 at r2](https://reviewable.io/reviews/harness/harness-core/54981#-Nin1m2jCnEkAcSMpYgJ:-Nin1m2jCnEkAcSMpYgK:b-xb4ph7) ([raw file](https://github.com/harness/harness-core/blob/74805c0cb6fe01addffd1582de6113abcdc3c3d9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L362)):*
> ```Java
>       GitFileCacheDeleteResult gitFileCacheDeleteResult = gitFileCacheService.invalidateCache(cacheKey);
>       log.info("Invalidated cache for key: {} , result: {}", cacheKey, gitFileCacheDeleteResult);
>     } catch (Exception ex) {
> ```

logging the exception?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54981)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 365 at r2](https://reviewable.io/reviews/harness/harness-core/54981#-Nin1qW49z3unEqntNSg:-Nin1qW49z3unEqntNSh:b-5u6ycb) ([raw file](https://github.com/harness/harness-core/blob/74805c0cb6fe01addffd1582de6113abcdc3c3d9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L365)):*
> ```Java
>       throw new InternalServerErrorException(
>           String.format(
>               "Error occurred while clearing the cache in repo [%s] account [%s]", repoName, accountIdentifier),
> ```

may be we can be more clear here : Error occurred while clearing cached files for given repo []. Account is already known so that can be removed from the error message of the exception atleast.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54981)* status: 2 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 361 at r2](https://reviewable.io/reviews/harness/harness-core/54981#-Nin1YBc1Ij0HAH3rx1A:-Nin5LLxEHM8kglBz9lP:b-hbad1u) ([raw file](https://github.com/harness/harness-core/blob/74805c0cb6fe01addffd1582de6113abcdc3c3d9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L361)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think lets move this line into the invalideCache method itself so that it gets logged for all cases. We may need this for future reference also when we try to fix our reload-from-git thing.
</blockquote></details>

yes, moved it
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 362 at r2](https://reviewable.io/reviews/harness/harness-core/54981#-Nin1m2jCnEkAcSMpYgJ:-Nin4Wj4AKOI4TlA23oA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/74805c0cb6fe01addffd1582de6113abcdc3c3d9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L362)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

logging the exception?
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 365 at r2](https://reviewable.io/reviews/harness/harness-core/54981#-Nin1qW49z3unEqntNSg:-Nin4fqSCuaU7A1w8H8_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/74805c0cb6fe01addffd1582de6113abcdc3c3d9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L365)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

may be we can be more clear here : Error occurred while clearing cached files for given repo []. Account is already known so that can be removed from the error message of the exception atleast.
</blockquote></details>

Done.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54981)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 361 at r3](https://reviewable.io/reviews/harness/harness-core/54981#-Nin6ll1708chR5mO5BR:-Nin6ll1708chR5mO5BS:bqsffmw) ([raw file](https://github.com/harness/harness-core/blob/3853b780897b806a8f9503f233c4e6b7d93a7943/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L361)):*
> ```Java
>       gitFileCacheService.invalidateCache(cacheKey);
>     } catch (Exception ex) {
>       log.error("Exception occurred while clearing the cache for repo {}", repoName, ex);
> ```

I think we would need account identifier here. We should simply log the cache key.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54981)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 365 at r2](https://reviewable.io/reviews/harness/harness-core/54981#-Nin1qW49z3unEqntNSg:-Nin6qCG4ru7p3HlWhZj:b-6rngnt) ([raw file](https://github.com/harness/harness-core/blob/74805c0cb6fe01addffd1582de6113abcdc3c3d9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L365)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No one would understand "clearing the cache in". We should state that error in clearing cached files so that it also makes sense to everyone as a use-case.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54981)* status: 4 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/54981#-NifXodS0J-GPvyoSG3V:-Nin6pqu5IQu_6S7BS-A:b2nhp9o) ([raw file](https://github.com/harness/harness-core/blob/4a71dd2a6f394a53a0651df71a2b7313fcf17115/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L96)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

We throw an error stating that webhook is already present for this repo
</blockquote></details>

The
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 365 at r2](https://reviewable.io/reviews/harness/harness-core/54981#-Nin1qW49z3unEqntNSg:-NinylqSEAc_UbHYNhd4:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/74805c0cb6fe01addffd1582de6113abcdc3c3d9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L365)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

No one would understand "clearing the cache in". We should state that error in clearing cached files so that it also makes sense to everyone as a use-case.
</blockquote></details>

done
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 361 at r3](https://reviewable.io/reviews/harness/harness-core/54981#-Nin6ll1708chR5mO5BR:-NincqKI5lHDFXOxi504:b-l8a0dv) ([raw file](https://github.com/harness/harness-core/blob/3853b780897b806a8f9503f233c4e6b7d93a7943/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L361)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we would need account identifier here. We should simply log the cache key.
</blockquote></details>

added the cache key

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54981)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
