### PR TITLE
[feat]:[CDS-33522]: acr integration to ng

### PR DESCRIPTION
**Pull request by alebuh**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31775)

### CODE REVIEW

**Comment by markoharness** [comment]
trigger ti2

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 32 files at r7, 2 of 133 files at r9, 9 of 36 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31775)* status: 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java` line 257 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0oee7H7xxAAmRCrAh-:-N0oee7H7xxAAmRCrAh0:b-vjh8pb) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java#L257)):*
> ```Java
>             ((AzureClientSecretKeyDTO) config.getAuthDTO().getCredentials()).getSecretKey().toSecretRefStringValue(),
>             ambiance));
>       } else {
> ```

Minor - Maybe check firstly for SP with certificate and throw exception. 
___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java` line 262 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0oey7nEM8phsLPYNCn:-N0oey7nEM8phsLPYNCo:bd5b7gl) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java#L262)):*
> ```Java
>       }
>     } else {
>       log.info("For Azure MSI there should not be necessary to provide credentials");
> ```

Minor - Try to make log message more specific. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java` line 156 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0oG_7N2OefIbWreNyu:-N0okNDR3Fj2aHOBzhnN:bqog7zb) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java#L156)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: instead of checking for acrArtifactConfig.getTagRegex() we should use ParameterField.isNull(acrArtifactConfig.getTagRegex()). As well there is no point of having empty string, it can be null instead. I feel that if value is null then we can have 2 different behaviors, null and empty string
</blockquote></details>

Agree.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java` line 159 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0ojxXWEyxXQtbyxqyk:-N0ojxXX0NqlF7xB1169:bjtup1e) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java#L159)):*
> ```Java
>     String tag = acrArtifactConfig.getTag() != null ? acrArtifactConfig.getTag().getValue() : "";
>     if (EmptyPredicate.isEmpty(tag) && EmptyPredicate.isEmpty(tagRegex)) {
>       tagRegex = "\\*";
> ```

Make constant of this \\*
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java` line 246 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0ogPUr4dpUA4-YqxLm:-N0ogPUr4dpUA4-YqxLn:b-w3oqfa) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java#L246)):*
> ```Java
>         .image(getImageValue(acrArtifactDelegateResponse))
>         .connectorRef(acrArtifactConfig.getConnectorRef().getValue())
>         .tag(useDelegateResponse ? acrArtifactDelegateResponse.getTag()
> ```

Minor - separate method getTag(...)
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java` line 252 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0og2qjERP8zMDQH51y:-N0og2qk8acmaFQTGlHr:bodb8z8) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java#L252)):*
> ```Java
>         .type(ArtifactSourceType.ACR.getDisplayName())
>         .primaryArtifact(acrArtifactConfig.isPrimaryArtifact())
>         .imagePullSecret(IMAGE_PULL_SECRET + ArtifactUtils.getArtifactKey(acrArtifactConfig) + ">")
> ```

What is the purpose of ">" can we separate this to constant and use String.format to build string snippet or even more separate this to new method? 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/acr/service/AcrResourceServiceImpl.java` line 100 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0ohJtiAzyITp5_owO0:-N0ohJtiAzyITp5_owO1:b-cwtffe) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/acr/service/AcrResourceServiceImpl.java#L100)):*
> ```Java
>     AzureRepositoriesResponse repositoriesResponse = (AzureRepositoriesResponse) azureHelperService.executeSyncTask(
>         azureTaskParamsTaskParams, baseNGAccess, "Azure list repositories task failure due to error");
>     return AcrRepositoriesDTO.builder()
> ```

Can we return the list of repositories, do we need to have wrapper data structure? 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/acr/service/AcrResourceServiceImpl.java` line 101 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0oh3fE2pczIxRsooeH:-N0oh3fE2pczIxRsooeI:bb00sq2) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/acr/service/AcrResourceServiceImpl.java#L101)):*
> ```Java
>         azureTaskParamsTaskParams, baseNGAccess, "Azure list repositories task failure due to error");
>     return AcrRepositoriesDTO.builder()
>         .repositories(repositoriesResponse.getRepositories()
> ```

Minor - separate method getRepositories(...)
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java` line 161 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0ohkC-7PgiApek6pBc:-N0ohkC-7PgiApek6pBd:bzc8bmr) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java#L161)):*
> ```Java
>         connectorDTO = getConnector(acrArtifactConfig.getConnectorRef().getValue(), ambiance);
>         if (!(connectorDTO.getConnectorConfig() instanceof AzureConnectorDTO)) {
>           throw new InvalidConnectorTypeException("provided Connector " + acrArtifactConfig.getConnectorRef().getValue()
> ```

Minor - use Sting.format(...)
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java` line 174 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0oHcXYC-DaFLj68NcK:-N0oi8w30pkUuUvjHT4t:bqog7zb) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java#L174)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: This and manual logic can be simplified by providing getAuthDTO() and getCredentials as part of common interface AzureCredentialSpecDTO and create common interface AuzureAuthDTO, so there will not need to check on type or casting part, only null check required
</blockquote></details>

Agree.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/azure/AcrArtifactTaskHandler.java` line 36 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0onaQA5WgVjsQUVMfq:-N0onaQA5WgVjsQUVMfr:b-fwjyp8) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/azure/AcrArtifactTaskHandler.java#L36)):*
> ```Java
> public class AcrArtifactTaskHandler extends DelegateArtifactTaskHandler<AcrArtifactDelegateRequest> {
>   private final SecretDecryptionService secretDecryptionService;
>   private final AzureNgHelper azureNgHelper;
> ```

If we call this class AzureNGHelper we are going  to put all stuff related to Azure delegate in this class. It should be more specific class.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/azure/AcrArtifactTaskHelper.java` line 30 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0ooMyu01X4C1O6AFLk:-N0ooMyu01X4C1O6AFLl:bp0soet) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/azure/AcrArtifactTaskHelper.java#L30)):*
> ```Java
> @Singleton
> public class AcrArtifactTaskHelper {
>   private final AcrArtifactTaskHandler acrArtifactTaskHandler;
> ```

Task helper calls task handler ???
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureNgHelper.java` line 98 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0or-ug3QbheNGHOxjp:-N0or-ug3QbheNGHOxjq:b-m02oi4) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureNgHelper.java#L98)):*
> ```Java
>   }
> 
>   public AzureSubscriptionsResponse listSubscriptions(
> ```

In the following package we have added task handler for all sync tasks which comes from manger and need to be executed as operations on Azure cloud. 
930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/resource/taskhandler/

Your class servers as helper for all asyn task. Please move this class to the following package and call something like this AzureAsynTaskHelper or more meaningful.
930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/resource

Methods should accept AzureConfig in order to be reusable by other deployment handlers like AzureVMSS, WebApp .. because we are planing to add support for all of these deployments on NG. Also i am not sure can we reuse AzureSubscriptionResponse as output of methods or it should be DTO which will be propagated to handlers and transform to Response in handler. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureNgHelper.java` line 264 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0oylo90v510QcT0Zsf:-N0oyloA9gAnUODjVDW_:b64eist) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureNgHelper.java#L264)):*
> ```Java
>   }
> 
>   public List<BuildDetailsInternal> getBuilds(
> ```

Please, More meaningful name instead of getBuilds
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureNgHelper.java` line 277 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0oyuIu-_gBUxazyH1V:-N0oyuIu-_gBUxazyH1W:bmxczp1) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureNgHelper.java#L277)):*
> ```Java
> 
>   // temp implementation until jackson library is upgraded
>   public List<BuildDetailsInternal> getBuilds(
> ```

The same as above
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureNgHelper.java` line 308 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0oz4Y-DMgVgf84Ufa2:-N0oz4Y-DMgVgf84Ufa3:brvdoeh) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureNgHelper.java#L308)):*
> ```Java
>               .buildUrl(imageUrl + ":" + tag)
>               .metadata(metadata)
>               .uiDisplayName("Tag# " + tag)
> ```

Constant
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureTask.java` line 30 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0ozpuJ7EM_xURXruFQ:-N0ozpuJ7EM_xURXruFR:b3tjs1h) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureTask.java#L30)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDP)
> public class AzureTask extends AbstractDelegateRunnableTask {
> ```

This task is part of io.harness.delegate.task.azure package should we move this to 930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure where are place all other Azure stuff? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureTask.java` line 56 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0p-Ne_DVE6Eyzq1IAL:-N0p-Ne_DVE6Eyzq1IAM:byd2ttx) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureTask.java#L56)):*
> ```Java
>                 azureTaskParams.getEncryptionDetails(), azureTaskParams.getAzureConnector()))
>             .build();
>       case LIST_SUBSCRIPTIONS:
> ```

We have already introduced  the concept of operations for all sync tasks.

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/acr/service/AcrResourceServiceImpl.java` line 100 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0ohJtiAzyITp5_owO0:-N0p9-iw-ztU8Nw2VcFI:b-sihv3c) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/acr/service/AcrResourceServiceImpl.java#L100)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can we return the list of repositories, do we need to have wrapper data structure? 
</blockquote></details>

We are trying to be consistent and to have possibilities to expand the response object in the future, hence the wrapper object.

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/azure/AcrArtifactTaskHandler.java` line 36 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0onaQA5WgVjsQUVMfq:-N0pCOxU3zUvKwHJlFRI:b-tvzsce) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/azure/AcrArtifactTaskHandler.java#L36)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

If we call this class AzureNGHelper we are going  to put all stuff related to Azure delegate in this class. It should be more specific class.
</blockquote></details>

Any suggestion?

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/azure/AcrArtifactTaskHelper.java` line 30 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0ooMyu01X4C1O6AFLk:-N0pCgvtA-8emKC1xBB4:bgu2mfd) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/azure/AcrArtifactTaskHelper.java#L30)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Task helper calls task handler ???
</blockquote></details>

What is the issue here? Any potential problem with this?
This how it was done in other cases and there was no issue with it.

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/client/AzureContainerRegistryRestClient.java` line 27 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0oggW8Dpkh5D3IWV91:-N0pIxUj-dIhwpoz_ViP:bfrzw8p) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/960-api-services/src/main/java/io/harness/azure/client/AzureContainerRegistryRestClient.java#L27)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

any reasons why we need underscore before _catalog here?
</blockquote></details>

That is docker spec rest API.

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java` line 155 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0oGFsjDIvlaBy9nJHJ:-N0pYEAs1X7BsewqmqCa:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java#L155)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: typo, should be acr
</blockquote></details>

Done

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java` line 156 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0oG_7N2OefIbWreNyu:-N0pYIca1phh9ouvsc_g:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java#L156)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Agree.
</blockquote></details>

Done

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java` line 159 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0ojxXWEyxXQtbyxqyk:-N0pYKPuB4e_5FrzGY_L:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java#L159)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Make constant of this \\*
</blockquote></details>

Done

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java` line 252 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0og2qjERP8zMDQH51y:-N0pYOch0wtfvIYvQtgz:bujg4fg) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java#L252)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

What is the purpose of ">" can we separate this to constant and use String.format to build string snippet or even more separate this to new method? 
</blockquote></details>

Extracted it to constant. And created (extracted it) a method which uses it.

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/acr/service/AcrResourceServiceImpl.java` line 101 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0oh3fE2pczIxRsooeH:-N0pY_oD50wC8VxWS0gz:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/acr/service/AcrResourceServiceImpl.java#L101)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - separate method getRepositories(...)
</blockquote></details>

Done

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java` line 161 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0ohkC-7PgiApek6pBc:-N0pYc3e53Imzc6VES1_:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java#L161)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - use Sting.format(...)
</blockquote></details>

Done

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/azure/AcrArtifactTaskHandler.java` line 36 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0onaQA5WgVjsQUVMfq:-N0pYmRF2DyOAQPJEyrv:bxjzti2) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/azure/AcrArtifactTaskHandler.java#L36)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

Any suggestion?
</blockquote></details>

Renamed it AzureAsyncTaskHelper and moved it to more appropriate package.

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureNgHelper.java` line 98 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0or-ug3QbheNGHOxjp:-N0pZ09l6O3ilHqBsFMJ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureNgHelper.java#L98)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

In the following package we have added task handler for all sync tasks which comes from manger and need to be executed as operations on Azure cloud. 
930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/resource/taskhandler/

Your class servers as helper for all asyn task. Please move this class to the following package and call something like this AzureAsynTaskHelper or more meaningful.
930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/resource

Methods should accept AzureConfig in order to be reusable by other deployment handlers like AzureVMSS, WebApp .. because we are planing to add support for all of these deployments on NG. Also i am not sure can we reuse AzureSubscriptionResponse as output of methods or it should be DTO which will be propagated to handlers and transform to Response in handler. 
</blockquote></details>

Done

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureNgHelper.java` line 233 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0ocnRD5ZSl7W2fwjcu:-N0pZvH_AHi8e0bVzm4e:b8m32cm) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureNgHelper.java#L233)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: I would like to avoid using InvalidRequestException and will be better manage all errors using hint, explanation, exception. This applies to other methods as well. Even that I'm seeing in some places this is applied, so not clear what is logic here.. 
</blockquote></details>

removed regular exceptions and replaced then with hint-explanation exceptions

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureNgHelper.java` line 277 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0oyuIu-_gBUxazyH1V:-N0p_3mL0qGvx9yAqtZ0:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureNgHelper.java#L277)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The same as above
</blockquote></details>

Done

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureNgHelper.java` line 308 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0oz4Y-DMgVgf84Ufa2:-N0p_5H-E3Wxx39cE5sD:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureNgHelper.java#L308)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Constant
</blockquote></details>

Done

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureTask.java` line 30 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0ozpuJ7EM_xURXruFQ:-N0p_9uW6FQWke_-T2_1:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/AzureTask.java#L30)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

This task is part of io.harness.delegate.task.azure package should we move this to 930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure where are place all other Azure stuff? 
</blockquote></details>

Done

**Comment by markoharness** [comment]
*[`970-api-services-beans/src/main/java/io/harness/azure/model/kube/AzureKubeConfig.java` line 18 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0ohDwj4QY0FheejsPy:-N0p_OUhBo04dyOkx8o3:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/970-api-services-beans/src/main/java/io/harness/azure/model/kube/AzureKubeConfig.java#L18)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: missing owner
</blockquote></details>

Done

**Comment by markoharness** [comment]
*[`970-api-services-beans/src/main/java/io/harness/azure/model/kube/ClusterConfig.java` line 18 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0ohFrHBiq0h4E2YnUw:-N0p_QYx8R39IdYrTfB1:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/970-api-services-beans/src/main/java/io/harness/azure/model/kube/ClusterConfig.java#L18)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: missing owner
</blockquote></details>

Done

**Comment by markoharness** [comment]
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java` line 257 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0oee7H7xxAAmRCrAh-:-N0p_XPZ8Z2RNUeSNQaR:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java#L257)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - Maybe check firstly for SP with certificate and throw exception. 
</blockquote></details>

Done

**Comment by markoharness** [comment]
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java` line 262 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0oey7nEM8phsLPYNCn:-N0p_YlZ0gAye2bYNPE_:bassbyv) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java#L262)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - Try to make log message more specific. 
</blockquote></details>

removed the log message

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 2547 at r15](https://reviewable.io/reviews/harness/harness-core/31775#-N0o_AtwAE1Q2_4q7sgG:-N0p_kDK4jfpb8352f_a:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e85eb06455a3ba559352a1ae050c51494cbdb57f/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L2547)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I don't think metadata should be part of schema. Need to add  @Getter(onMethod_ = { @ApiModelProperty(hidden = true) }) @ApiModelProperty(hidden = true) in K8sAzureInfrastructure
</blockquote></details>

Done

**Review by markoharness — APPROVED** [review]
> Reviewed 10 of 20 files at r16, 10 of 10 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31775)* status: 2 change requests. 15. unresolved discussions.

**Review by ivan-83 — COMMENTED** [review]
> Reviewed 1 of 79 files at r19, 1 of 15 files at r22, 3 of 78 files at r26, 20 of 38 files at r27, 7 of 16 files at r29, 30 of 36 files at r31, 24 of 27 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31775)* status: 2 change requests. 15. unresolved discussions. 0 of 1 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31775#-:-N0q5Dfv5Wd2so1xdXIi:bnfp4nl)* status: 1 change requests. 5. unresolved discussions.

**Review by markoharness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31775)* status: 1 change requests. 5. unresolved discussions.

**Pull request merged**
