### PR TITLE
[fix]: [PL-28943]: updating error message for entity identifier

### PR DESCRIPTION
**Pull request by shreyas-harness**
## Describe your changes
Updating error message for entity identifier
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38710)

### CODE REVIEW

**Comment by shreyas-harness** [comment]
trigger messagecheck

**Comment by shreyas-harness** [comment]
trigger messagecheck

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38710)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38710)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/test/java/io/harness/data/validator/EntityIdentifierValidatorTest.java` line 142 at r2](https://reviewable.io/reviews/harness/harness-core/38710#-NEEmq_M0CRcoU2b9ShC:-NEEmq_M0CRcoU2b9ShD:b-geysz0) ([raw file](https://github.com/harness/harness-core/blob/1fa01669a80f4cbf4fc1ced0b80db5d1042777d0/980-commons/src/test/java/io/harness/data/validator/EntityIdentifierValidatorTest.java#L142)):*
> ```Java
>     assertEquals(
>         1, validator.validate(EntityIdentifierValidatorTestStructure.builder().identifier("$abc").build()).size());
>     assertEquals("can be 64 characters long and can only contain alphanumeric, underscore and $ characters,"
> ```

Assign to variable so that it is more readable.
___
*[`980-commons/src/test/java/io/harness/data/validator/EntityIdentifierValidatorTest.java` line 144 at r2](https://reviewable.io/reviews/harness/harness-core/38710#-NEEnJMr1VStYBX7mVB_:-NEEnJMr1VStYBX7mVBa:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/1fa01669a80f4cbf4fc1ced0b80db5d1042777d0/980-commons/src/test/java/io/harness/data/validator/EntityIdentifierValidatorTest.java#L144)):*
> ```Java
>     assertEquals("can be 64 characters long and can only contain alphanumeric, underscore and $ characters,"
>             + " and not start with a number or $",
>         validator.validate(EntityIdentifierValidatorTestStructure.builder().identifier("$abc").build())
> ```

same here

**Review by shreyas-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38710)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/test/java/io/harness/data/validator/EntityIdentifierValidatorTest.java` line 142 at r2](https://reviewable.io/reviews/harness/harness-core/38710#-NEEmq_M0CRcoU2b9ShC:-NEF9KUm-NqTDRRSqD11:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fa01669a80f4cbf4fc1ced0b80db5d1042777d0/980-commons/src/test/java/io/harness/data/validator/EntityIdentifierValidatorTest.java#L142)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Assign to variable so that it is more readable.
</blockquote></details>

Done.
___
*[`980-commons/src/test/java/io/harness/data/validator/EntityIdentifierValidatorTest.java` line 144 at r2](https://reviewable.io/reviews/harness/harness-core/38710#-NEEnJMr1VStYBX7mVB_:-NEF9Kka6RUUK2pLuTPa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fa01669a80f4cbf4fc1ced0b80db5d1042777d0/980-commons/src/test/java/io/harness/data/validator/EntityIdentifierValidatorTest.java#L144)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38710)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38710)* status: :shipit: complete! ✓

**Pull request merged**
