### PR TITLE
feat: [DEL-4242]: Add connectivity status for delegate selector

### PR DESCRIPTION
**Pull request by AnupamIO**
JIRA: https://harness.atlassian.net/browse/DEL-4242

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34704)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34704)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResourceV3.java` line 470 at r1](https://reviewable.io/reviews/harness/harness-core/34704#-N5dWRZg6zgM0R5um7cm:-N5dWRZg6zgM0R5um7cn:b-k60n76) ([raw file](https://github.com/harness/harness-core/blob/5bda3cb595c6231e1771563e463c7b0347ef6ebe/400-rest/src/main/java/software/wings/resources/DelegateSetupResourceV3.java#L470)):*
> ```Java
>         ApiResponse(responseCode = "default", description = "A set of selectors (delegate implicit selectors + tags).")
>       })
>   public RestResponse<List<DelegateSelector>>
> ```

This change is not backwards compatible it will break the UI unless both UI and manager are deployed simultaneously. Better to create a new API and leave the old one as is, removing it after the UI deployment. 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 559 at r1](https://reviewable.io/reviews/harness/harness-core/34704#-N5dXOKuBUTEZs4BmCn2:-N5dXOKuBUTEZs4BmCn3:b-kfsmq9) ([raw file](https://github.com/harness/harness-core/blob/5bda3cb595c6231e1771563e463c7b0347ef6ebe/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L559)):*
> ```Java
>     delegateGroups.forEach(group -> {
>       List<Delegate> delegateList = delegateCache.getDelegatesForGroup(accountId, group.getUuid());
>       boolean isConnected;
> ```

This is too complex. Needs to be taken out into multiple methods. Try to 



_Code quote:_
```Java
    delegateGroups.forEach(group -> {
      List<Delegate> delegateList = delegateCache.getDelegatesForGroup(accountId, group.getUuid());
      boolean isConnected;
      if (isNotEmpty(delegateList)) {
        isConnected = delegateList.stream().anyMatch(this::checkHeartBeatExpiration);
      } else {
        log.warn("unable to get delegate list for group from cache");
        isConnected = false;
      }
      delegateSetupService.retrieveDelegateGroupImplicitSelectors(group).keySet().forEach(
          implicitSelector -> addDelegateSelector(implicitSelector, delegateSelectorMap, isConnected));
      if (isNotEmpty(group.getTags())) {
        group.getTags().forEach(tag -> addDelegateSelector(tag, delegateSelectorMap, isConnected));
      }
    });
```
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 576 at r1](https://reviewable.io/reviews/harness/harness-core/34704#-N5dWtpT3TsV5-aP1RtQ:-N5dWtpT3TsV5-aP1RtR:b-bnzewx) ([raw file](https://github.com/harness/harness-core/blob/5bda3cb595c6231e1771563e463c7b0347ef6ebe/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L576)):*
> ```Java
>         .sorted((s1, s2) -> {
>           if ((s1.isConnected() && s2.isConnected()) || (!s1.isConnected() && !s2.isConnected())) {
>             return s1.getDelegateSelectorName().compareTo(s2.getDelegateSelectorName());
> ```

Create a custom comparator class



_Code quote:_
```Java
          if ((s1.isConnected() && s2.isConnected()) || (!s1.isConnected() && !s2.isConnected())) {
            return s1.getDelegateSelectorName().compareTo(s2.getDelegateSelectorName());
          } else if (s1.isConnected()) {
            return -1;
          } else {
            return 1;
          }
```
___
*[`400-rest/src/test/java/software/wings/service/delegate/DelegateServiceTest.java` line 3041 at r1](https://reviewable.io/reviews/harness/harness-core/34704#-N5dVSIZBQu9DebrXbAl:-N5dVSIZBQu9DebrXbAm:b-527gsf) ([raw file](https://github.com/harness/harness-core/blob/5bda3cb595c6231e1771563e463c7b0347ef6ebe/400-rest/src/test/java/software/wings/service/delegate/DelegateServiceTest.java#L3041)):*
> ```Java
>     final List<DelegateSelector> delegateSelectors =
>         delegateService.getAllDelegateSelectorsUpTheHierarchy(accountId, null, null);
>     assertThat(delegateSelectors.size()).isEqualTo(3);
> ```

You should create appropriate expectation objects (e.g. `new DelegateSelector("acctgrpconnected", true)`) and use `assertThat().containsExactly()` this assertion verifies both order and size. 



_Code quote:_
```Java
    assertThat(delegateSelectors.size()).isEqualTo(3);
    // check the order of delegateSelectors.
    assertThat(delegateSelectors.get(0).getDelegateSelectorName()).isEqualTo("acctgrpconnected");
    assertThat(delegateSelectors.get(1).getDelegateSelectorName()).isEqualTo("acctgrppartiallyconnected");
    assertThat(delegateSelectors.get(2).getDelegateSelectorName()).isEqualTo("acctgrpdisconnected");

    // check connection status of all selectors.
    assertThat(delegateSelectors.get(0).isConnected()).isEqualTo(true);
    assertThat(delegateSelectors.get(1).isConnected()).isEqualTo(true);
    assertThat(delegateSelectors.get(2).isConnected()).isEqualTo(false);
```
___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateSelector.java` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/34704#-N5dU7nH3z99wbOzbSwv:-N5dU7nH3z99wbOzbSww:bkztiay) ([raw file](https://github.com/harness/harness-core/blob/5bda3cb595c6231e1771563e463c7b0347ef6ebe/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateSelector.java#L10)):*
> ```Java
> 
> @Data
> @Builder
> ```

Don't use builder, class is small enough and all fields are mandatory. Make all fields `final` instead to make the class immutable
___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateSelector.java` line 13 at r1](https://reviewable.io/reviews/harness/harness-core/34704#-N5dTyVx6ms17hdI1kQl:-N5dTyVx6ms17hdI1kQm:b-fmnxzr) ([raw file](https://github.com/harness/harness-core/blob/5bda3cb595c6231e1771563e463c7b0347ef6ebe/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateSelector.java#L13)):*
> ```Java
> @OwnedBy(HarnessTeam.DEL)
> public class DelegateSelector {
>   private String delegateSelectorName;
> ```

You can just call it `name` as it's already in the DelegateSelector class

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34704)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 559 at r1](https://reviewable.io/reviews/harness/harness-core/34704#-N5dXOKuBUTEZs4BmCn2:-N5dwcOi-si0MN3LrRXB:b-y7fcov) ([raw file](https://github.com/harness/harness-core/blob/5bda3cb595c6231e1771563e463c7b0347ef6ebe/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L559)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This is too complex. Needs to be taken out into multiple methods. Try to 
</blockquote></details>

Try also rethinking the logic. Do we need to Query the DB for groups and then go through all the groups to get delegates? That seems pointless. You could probably get all delegates straight away (from cache for accountId/owner) each delegate has group info if that info is needed later on. If you go this route try testing in CG+NG

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java` line 369 at r1](https://reviewable.io/reviews/harness/harness-core/34704#-N5qAPtC-tfsfOL2LOs2:-N5qAPtC-tfsfOL2LOs3:b-9jpejm) ([raw file](https://github.com/harness/harness-core/blob/5bda3cb595c6231e1771563e463c7b0347ef6ebe/400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java#L369)):*
> ```Java
>   @ExceptionMetered
>   @AuthRule(permissionType = LOGGED_IN)
>   public RestResponse<List<DelegateSelector>> delegateSelectorsUpTheHierarchy(@Context HttpServletRequest request,
> ```

lets not change existing APIs, create a new API and have UI use it and then remove this one

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34704)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 559 at r1](https://reviewable.io/reviews/harness/harness-core/34704#-N5dXOKuBUTEZs4BmCn2:-N67HraLEwaA3V6YrqR3:b-kt6l82) ([raw file](https://github.com/harness/harness-core/blob/5bda3cb595c6231e1771563e463c7b0347ef6ebe/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L559)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Try also rethinking the logic. Do we need to Query the DB for groups and then go through all the groups to get delegates? That seems pointless. You could probably get all delegates straight away (from cache for accountId/owner) each delegate has group info if that info is needed later on. If you go this route try testing in CG+NG
</blockquote></details>

All delegates for a accountId is not available in cache. So we would need at least one db call. Either we need to fetch all delegateGroups or all delegates from db.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34704)* status: Some of the checks are too old. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateSelector.java` line 13 at r1](https://reviewable.io/reviews/harness/harness-core/34704#-N5dTyVx6ms17hdI1kQl:-N67JRU-6ecZttxD5TRG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5bda3cb595c6231e1771563e463c7b0347ef6ebe/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateSelector.java#L13)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You can just call it `name` as it's already in the DelegateSelector class
</blockquote></details>

Done.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34704)* status: Some of the checks are too old. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 559 at r1](https://reviewable.io/reviews/harness/harness-core/34704#-N5dXOKuBUTEZs4BmCn2:-N67N9hV9Ii91aPUTND3:b-dkr6nj) ([raw file](https://github.com/harness/harness-core/blob/5bda3cb595c6231e1771563e463c7b0347ef6ebe/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L559)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

Querying DelegateGroup is inevitable because we need tags also.
</blockquote></details>

Simplified.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34704)* status: Some of the checks are too old. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 576 at r1](https://reviewable.io/reviews/harness/harness-core/34704#-N5dWtpT3TsV5-aP1RtQ:-N67SF9C3BMF4HTM7cWz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5bda3cb595c6231e1771563e463c7b0347ef6ebe/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L576)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Create a custom comparator class
</blockquote></details>

Done.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34704)* status: Some of the checks are too old. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/delegate/DelegateServiceTest.java` line 3041 at r1](https://reviewable.io/reviews/harness/harness-core/34704#-N5dVSIZBQu9DebrXbAl:-N69RIsHDuT5o7_rHPHk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5bda3cb595c6231e1771563e463c7b0347ef6ebe/400-rest/src/test/java/software/wings/service/delegate/DelegateServiceTest.java#L3041)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You should create appropriate expectation objects (e.g. `new DelegateSelector("acctgrpconnected", true)`) and use `assertThat().containsExactly()` this assertion verifies both order and size. 
</blockquote></details>

Done.
___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateSelector.java` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/34704#-N5dU7nH3z99wbOzbSwv:-N69R_3p5d6YEw1rF2El:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5bda3cb595c6231e1771563e463c7b0347ef6ebe/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateSelector.java#L10)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Don't use builder, class is small enough and all fields are mandatory. Make all fields `final` instead to make the class immutable
</blockquote></details>

Done.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34704)* status: 7 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java` line 369 at r1](https://reviewable.io/reviews/harness/harness-core/34704#-N5qAPtC-tfsfOL2LOs2:-N69uFzuDYGCNGQDLC7g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5bda3cb595c6231e1771563e463c7b0347ef6ebe/400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java#L369)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

lets not change existing APIs, create a new API and have UI use it and then remove this one
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResourceV3.java` line 470 at r1](https://reviewable.io/reviews/harness/harness-core/34704#-N5dWRZg6zgM0R5um7cm:-N69uFCnExQSjmKC4JFE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5bda3cb595c6231e1771563e463c7b0347ef6ebe/400-rest/src/main/java/software/wings/resources/DelegateSetupResourceV3.java#L470)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This change is not backwards compatible it will break the UI unless both UI and manager are deployed simultaneously. Better to create a new API and leave the old one as is, removing it after the UI deployment. 
</blockquote></details>

Done.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34704)* status: 1 change requests. 5. unresolved discussions.

**Pull request merged**
