### PR TITLE
fix: [PL-31496]: Add groups in user responses in ng SCIM

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Describe your changes
As per SCIM 2.0 standards, we will have to return back groups node which gives all the groups the user is part of for any CRUD response of user resource. This is needed for JPMC primarily to verify the userGroups in their side for a given user. We are adding this in response and this is behind a FF.

Screen-shots: 
image

image

Testing:
1. Added UT's
2. Verified create and update ScimUser call with and without FF and validated the response. Verified this in local.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44808)

### CODE REVIEW

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44808)* status: 7 file(s) to review. 0 of 2 approvals obtained.

**Review by tiwaritejas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44808)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/repositories/ng/core/custom/UserGroupRepositoryCustomImpl.java` line 58 at r5](https://reviewable.io/reviews/harness/harness-core/44808#-NQ9gdGX9HFVE5Or1EIb:-NQ9gdGX9HFVE5Or1EIc:bgarnua) ([raw file](https://github.com/harness/harness-core/blob/8c5e025f9fe82c22bdfc2e4edae60f542f47eb67/123-ng-core-user/src/main/java/io/harness/repositories/ng/core/custom/UserGroupRepositoryCustomImpl.java#L58)):*
> ```Java
>   public List<UserGroup> findAll(Criteria criteria) {
>     Query query = new Query(criteria);
>     query.limit(500);
> ```

@pbarapatre10 What if number of user groups is more than 500? I see a single call made from NGScimUserServiceImpl to fetch the user groups, it will return the first 500 only, right? I don't see any method to fetch user groups in batches.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44808)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by tiwaritejas — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44808)* status: :shipit: complete! ✓

**Review by tiwaritejas — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44808)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44808)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
