### PR TITLE
feat: [PIE-8955]: Add background cache handling for git-file-batch API call

### PR DESCRIPTION
**Pull request by mohitg0795**
## Describe your changes
Following changes are done as part of this PR:
- Refactored gitx cache background thread executor service to run only fixed num of allowed tasks and reject others
- Update cache in background for files used in execution flow on best effort basis

Test cases:
- Tested execution of pipelines with nested templates
- Files getting updated in background thread both for single file and batch files as expected.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45381)

### CODE REVIEW

**Review by adivishy1 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45381)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 379 at r3](https://reviewable.io/reviews/harness/harness-core/45381#-NR1DrGh7IvCkKcfdbB8:-NR1DrGh7IvCkKcfdbB9:bqizucr) ([raw file](https://github.com/harness/harness-core/blob/d837ec9da674102508a91d7ffa8d77379672e359/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L379)):*
> ```Java
>     //    if (!isBatchGetFileTaskSupportedByDelegates(scmGetBatchFilesByBranchRequestDTO.getAccountIdentifier())) {
>     //      return processGetBatchFileTaskUsingSingleGetFileAPI(scmGetBatchFilesByBranchRequestDTO);
>     //    }
> ```

can we clean up the comments?

**Review by adivishy1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45381)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 379 at r3](https://reviewable.io/reviews/harness/harness-core/45381#-NR1DrGh7IvCkKcfdbB8:-NR4lrXbCAdCp5IZ4gEX:baaae28) ([raw file](https://github.com/harness/harness-core/blob/d837ec9da674102508a91d7ffa8d77379672e359/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L379)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

can we clean up the comments?
</blockquote></details>

done, reverted.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 10 files at r1, 1 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45381)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45381)* status: :shipit: complete! ✓

**Pull request merged**
