### PR TITLE
[feat]: [CDS-59517]: refactoring for overrides v2

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes

This is partial pr for api + service layer for override 2.0
In this pr we are refactoring existing classes to be used further

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47059)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/EnvGlobalOverrideValidator.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/47059#-NU55lSi0knhr2diEcqy:-NU55lSi0knhr2diEcqz:b-2vchxm) ([raw file](https://github.com/harness/harness-core/blob/efc943bee4b4cf1364ebf0fd00cdf80b93b791d1/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/EnvGlobalOverrideValidator.java#L14)):*
> ```Java
> import org.jetbrains.annotations.NotNull;
> 
> public class EnvGlobalOverrideValidator implements ServiceOverrideTypeBasedValidator {
> ```

should be a singleton ?

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans/NGServiceOverridesEntity.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/47059#-NU55tyZ91H1IlArcwTG:-NU55tyZ91H1IlArcwTH:b7paztm) ([raw file](https://github.com/harness/harness-core/blob/efc943bee4b4cf1364ebf0fd00cdf80b93b791d1/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans/NGServiceOverridesEntity.java#L67)):*
> ```Java
>                  .field(NGServiceOverridesEntityKeys.orgIdentifier)
>                  .field(NGServiceOverridesEntityKeys.projectIdentifier)
>                  .field(NGServiceOverridesEntityKeys.identifier)
> ```

what happens for already saved service overrides where identifier is not set ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 19 of 26 files at r1, 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47059)* status: 28 file(s) to review. 0 of 2 approvals obtained.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47059)* status: 28 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/EnvGlobalOverrideValidator.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/47059#-NU55lSi0knhr2diEcqy:-NU56RDA1AKo9KbTWfqb:b9vmmlp) ([raw file](https://github.com/harness/harness-core/blob/efc943bee4b4cf1364ebf0fd00cdf80b93b791d1/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/EnvGlobalOverrideValidator.java#L14)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should be a singleton ?
</blockquote></details>

Is this a service or utility?
I am guessing all the methods can be static here.

If not, if it is a service, make is Singleton as Yogesh mentioned

**Review by tchaurasiya — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47059)* status: 28 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans/NGServiceOverridesEntity.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/47059#-NU55tyZ91H1IlArcwTG:-NU5Glot54oSgh4p8WhC:b685l15) ([raw file](https://github.com/harness/harness-core/blob/efc943bee4b4cf1364ebf0fd00cdf80b93b791d1/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans/NGServiceOverridesEntity.java#L67)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

what happens for already saved service overrides where identifier is not set ?
</blockquote></details>

Yeah this was for local testing, pushed by mistake.
If identifier null it will fail, as this index wont be unique.
We will first rollout migration for identifier + add for any new entity created in db
CC: @vaibhav-si

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 26 files at r1, 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47059)* status: Some of the checks are too old. 28 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideTypeBasedValidator.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/47059#-NUQi1mQBT_KbGvDW6Sz:-NUQi1mQBT_KbGvDW6T-:b-zb5e0b) ([raw file](https://github.com/harness/harness-core/blob/efc943bee4b4cf1364ebf0fd00cdf80b93b791d1/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideTypeBasedValidator.java#L20)):*
> ```Java
>     void validateRequest(@NonNull ServiceOverrideRequestDTOV2 requestDTOV2);
> 
>     String generateServiceOverrideIdentifier(NGServiceOverridesEntity serviceOverridesEntity);
> ```

this is also NotNull right ?

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/EnvGlobalOverrideValidator.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/47059#-NU55lSi0knhr2diEcqy:-NUVRmn48VcnOp6h5sgQ:b-dgieoo) ([raw file](https://github.com/harness/harness-core/blob/efc943bee4b4cf1364ebf0fd00cdf80b93b791d1/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/EnvGlobalOverrideValidator.java#L14)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Is this a service or utility?
I am guessing all the methods can be static here.

If not, if it is a service, make is Singleton as Yogesh mentioned


</blockquote></details>

Yes marked the interface as singleton.
this will be used as service (not static)

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideTypeBasedValidator.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/47059#-NUQi1mQBT_KbGvDW6Sz:-NUVU1qPDkEWgtCZW1-E:b-lm3ne8) ([raw file](https://github.com/harness/harness-core/blob/efc943bee4b4cf1364ebf0fd00cdf80b93b791d1/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideTypeBasedValidator.java#L20)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this is also NotNull right ?
</blockquote></details>

marked!

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 6 of 7 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47059)* status: 28 file(s) to review. 1 of 2 approvals obtained.

**Review by mankrit-singh — APPROVED** [review]

**Comment by tchaurasiya** [comment]
trigger utAll

**Comment by tchaurasiya** [comment]
trigger ut0

**Comment by tchaurasiya** [comment]
trigger utAll

**Comment by tchaurasiya** [comment]
trigger ut1, ut2, ut3, ut4, ut5

**Comment by tchaurasiya** [comment]
trigger review

**Pull request merged**
