### PR TITLE
[feat]: [PIE-7259]: Add special handling for fields inside service and env for runtime inputs

### PR DESCRIPTION
**Pull request by namanvermah**
Any field that is under "service", "environment", "template", "services", "environments", "environmentGroup" in runtime input yaml will not be ignored and merged into the pipeline yaml for execution

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42118)

### CODE REVIEW

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 25 files at r1, 21 of 22 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42118)* status: 25 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42118)* status: 25 file(s) to review.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 25 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42118)* status: 21 file(s) to review.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 3 of 25 files at r1, 21 of 22 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42118)* status: :shipit: complete! ✓

**Pull request merged**
