### PR TITLE
feat: [CDS-37901]: Gitops Cluster Step & outcome

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes

Create a Gitops Cluster step that would consume the environment/environmentgroup/gitops clusters selected in the pipeline and produce an outcome which contains data about the clusters.  To do this, we first find all the cluster refs, then we call gitops service to fetch the clusters with those identifiers. 
The Gitops Outcome will also have resolved variables going forward but this PR does not contain those changes

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33585)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
trigger ti1, ti3

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 12 files at r1, 3 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33585)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersOutcome.java` line 62 at r3](https://reviewable.io/reviews/harness/harness-core/33585#-N3cIbeNDGV4wTdXNmkX:-N3cIbeO4wgubsXDzvbJ:b-3ze847) ([raw file](https://github.com/harness/harness-core/blob/136331b054fac28437f2d1bcb1dfdd22a4e8c871/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersOutcome.java#L62)):*
> ```Java
>     String key;
>     Object value;
>   }
> ```

Can be removed and converted to map in variables field in ClusterData



_Code quote:_
```Java
  @Data
  @Builder
  private static class Variable {
    String key;
    Object value;
  }
```

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33585)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersOutcome.java` line 62 at r3](https://reviewable.io/reviews/harness/harness-core/33585#-N3cIbeNDGV4wTdXNmkX:-N3cQ17MAEjTpWcrnnCH:bfgxrya) ([raw file](https://github.com/harness/harness-core/blob/136331b054fac28437f2d1bcb1dfdd22a4e8c871/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersOutcome.java#L62)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can be removed and converted to map in variables field in ClusterData
</blockquote></details>

makes sense. Done

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33585)* status: :shipit: complete! ✓

**Pull request merged**
