### PR TITLE
feat: [PL-24602]: Update version for access control is security release branch

### PR DESCRIPTION
**Pull request by gupta-utkarsh**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32229)

### CODE REVIEW

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32229#-:-N-X9CWT8Fs0R-eEBlAO:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
*[access-control/build.properties, line 3 at r1](https://reviewable.io/reviews/harness/harness-core/32229#-N-XHjnG0hrUjmbo6vfp:-N-XHjnG0hrUjmbo6vfq:bxj9cvh) ([raw file](https://github.com/harness/harness-core/blob/f5c59e699ff73839d601d53e4c54fb49385ebddc/access-control/build.properties#L3)):*
> ```INI
> build.majorVersion=1
> build.minorVersion=0
> build.number=74610
> ```

Can we make this version 74663 same as other services.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32229)* status: 1 file(s) to review.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32229#-:-N-XUWIQ3j431YeP31bQ:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
