### PR TITLE
[fix]: [DEL-4958]: Remove versioning from cg manager

### PR DESCRIPTION
**Pull request by raghuAtWings**
## Describe your changes
Currently we still have versioned grpc code which is no longer used. Removing this to clean up

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37892)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37892)

**Comment by raghuAtWings** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/37892#-NCvIOP2Aql8EqCCY2gI:-NCvIOP2Aql8EqCCY2gJ:br0qkjh) ([raw file](https://github.com/harness/harness-core/blob/8a3691f90e5c939d5d94b99307969fe4665953e4/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L128)):*
> ```Java
>   public String createTask(String perpetualTaskType, String accountId, PerpetualTaskClientContext clientContext,
>       PerpetualTaskSchedule schedule, boolean allowDuplicate, String taskDescription) {
>     if (mainConfiguration.isDisableDelegateMgmtInManager()) {
> ```

Are you removing from config file and replace_config also?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/37892#-NCvIOP2Aql8EqCCY2gI:-NCvJ5r-451Rp1GeTwG6:b-g1q0yn) ([raw file](https://github.com/harness/harness-core/blob/8a3691f90e5c939d5d94b99307969fe4665953e4/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L128)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Are you removing from config file and replace_config also?
</blockquote></details>

no, i don't think we should club these two.

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37892)* status: 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by jennyjames21 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37892)* status: :shipit: complete! ✓

**Pull request merged**
