### PR TITLE
feat: [PIE-6245]: Reduce size of plan node

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39878)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39878)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/GraphStatusUpdateHelper.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/39878#-NGRRH6UA1PSSXBUqND8:-NGRRH6UA1PSSXBUqND9:b-qqg6i7) ([raw file](https://github.com/harness/harness-core/blob/280dbf5a4b449495e48a00b4f872e54c8252eca7/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/GraphStatusUpdateHelper.java#L136)):*
> ```Java
>             .progressData(nodeExecution.getPmsProgressData());
>     if (prevValue.getStepParameters() != null) {
>       prevValueBuilder.stepParameters(nodeExecution.getResolvedParams());
> ```

Can we add the same check in StepDetailsUpdateEventHandler in line 61

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/GraphStatusUpdateHelper.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/39878#-NGRRH6UA1PSSXBUqND8:-NGRkzJ_-tGVvc4eSasQ:b-yprcs) ([raw file](https://github.com/harness/harness-core/blob/280dbf5a4b449495e48a00b4f872e54c8252eca7/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/GraphStatusUpdateHelper.java#L136)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we add the same check in StepDetailsUpdateEventHandler in line 61
</blockquote></details>

StepDetailsUpdateEventHandler won't be called if there is no stepInputs

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39878)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39878)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39878)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/sdk/core/steps/io/PipelineViewObject.java` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/39878#-NG_27bz7LuO0___vs0g:-NG_27bz7LuO0___vs0h:bxf8rm6) ([raw file](https://github.com/harness/harness-core/blob/49bce8df8a7a1207cbd2e1a1fd709524d8fb0448/953-yaml-commons/src/main/java/io/harness/pms/sdk/core/steps/io/PipelineViewObject.java#L13)):*
> ```Java
>   String DEFAULT = "default";
>   default String toViewJson() {
>     return DEFAULT;
> ```

why not null?

**Comment by sahilhindwani-harness** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/sdk/core/steps/io/PipelineViewObject.java` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/39878#-NG_27bz7LuO0___vs0g:-NG_2h9yEFg-X8Mpge_c:b-hi12vy) ([raw file](https://github.com/harness/harness-core/blob/49bce8df8a7a1207cbd2e1a1fd709524d8fb0448/953-yaml-commons/src/main/java/io/harness/pms/sdk/core/steps/io/PipelineViewObject.java#L13)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

why not null?
</blockquote></details>

In the current implementation, user can override with null to hide all the fields. Therefore did not use null as few places this behaviour is used.

**Review by hextechpal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39878)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
trigger codeformat

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
trigger codeformat

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39878)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39878)* status: :shipit: complete! ✓

**Pull request merged**
