### PR TITLE
fix: [DEL-6222]: Rerun migration for few missed records

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
- Rerun migration to encrypt token for records created though NG Migration
- Records created through NG migration or new project/org created (default token created with project or org creation) not creating encryptedTokenRecord, so adding set encrypted value for new ones and migrating existing missed records.

Test
-Unit/ Local testing

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46077)

### CODE REVIEW

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46077)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46077)* status: :shipit: complete! ✓

**Review by xingchi-jin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46077)* status: :shipit: complete! ✓

___
*[`390-db-migration/src/main/java/io/harness/migrations/MigrationBackgroundList.java` line 428 at r2](https://reviewable.io/reviews/harness/harness-core/46077#-NSRahSp4kgGrTiGVBst:-NSRahSp4kgGrTiGVBsu:b13st65) ([raw file](https://github.com/harness/harness-core/blob/038ad095e108e5ed8f2a345c4662371f5cb521d5/390-db-migration/src/main/java/io/harness/migrations/MigrationBackgroundList.java#L428)):*
> ```Java
>         .add(Pair.of(247, BackFillingKeywordsOnWorkflowExecutionCollection.class))
>         .add(Pair.of(248, UpdateK8sWatchInvalidStatePerpetualTaskMigration.class))
>         .add(Pair.of(249, EncryptDelegateTokenMigration.class))
> ```

is it ok to have dup class in the list, 245 and 249 ? (non-blocking comment)

**Comment by jennyjames21** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/MigrationBackgroundList.java` line 428 at r2](https://reviewable.io/reviews/harness/harness-core/46077#-NSRahSp4kgGrTiGVBst:-NSRbgEY5AVJ0kxciLp3:b-ko6smy) ([raw file](https://github.com/harness/harness-core/blob/038ad095e108e5ed8f2a345c4662371f5cb521d5/390-db-migration/src/main/java/io/harness/migrations/MigrationBackgroundList.java#L428)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

is it ok to have dup class in the list, 245 and 249 ? (non-blocking comment)
</blockquote></details>

i think so, because schema only has last executed number so that it will run anything after that.
i tested deploying new PR and sanity looks fine. 
New projects created with default token with encrypted record

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46077)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
trigger review

**Pull request merged**
