### PR TITLE
fix: [SRM-15167]: Enhancements and fixes on deployment step

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Describe your changes

This address review comments for https://github.com/harness/harness-core/pull/50666
This fixes:
1. Deleting MS is failing summary page as activities are deleted
2. If a monitored service notification has 2 notification and 1 got sent within the last hour then deployment report notification doesn't get sent, this fixes that
3. Change event api register for automation
4. demo feedback

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50926)

### CODE REVIEW

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepak-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50926)* status: 17 file(s) to review. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/services/impl/SRMAnalysisStepServiceImpl.java` line 151 at r3](https://reviewable.io/reviews/harness/harness-core/50926#-NaKUZIo0a3nRDAe4BRo:-NaKUZIo0a3nRDAe4BRp:bozmoy4) ([raw file](https://github.com/harness/harness-core/blob/c0924fe3162a5220204cb9e8261be230da40d6f2/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/services/impl/SRMAnalysisStepServiceImpl.java#L151)):*
> ```Java
>       handleReportNotification(stepExecutionDetail);
>     } catch (Exception exception) {
>       log.error("Sending deployment analysis report failed", exception);
> ```

nit: we can probably add either the monitored service id or the SRM step analysis ID
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/ChangeEventServiceImpl.java` line 150 at r3](https://reviewable.io/reviews/harness/harness-core/50926#-NaKUo7JCs78KbXcWkO6:-NaKUo7JCs78KbXcWkO7:b-3gp27n) ([raw file](https://github.com/harness/harness-core/blob/c0924fe3162a5220204cb9e8261be230da40d6f2/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/ChangeEventServiceImpl.java#L150)):*
> ```Java
>     if (changeEventDTO.getMetadata().getType().equals(ChangeSourceType.SRM_STEP_ANALYSIS)) {
>       HarnessSRMAnalysisEventMetadata metadata = (HarnessSRMAnalysisEventMetadata) changeEventDTO.getMetadata();
>       Ambiance ambiance =
> ```

nit: Makes sense to move this move to populate meta data. This is unnecessary bloat the register method which is used for all other activities(making reading code harder).

**Pull request merged**
