### PR TITLE
feat: [PL-25672]: Integrated fileUrl in git sdk

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
Integrated fileUrl in git sdk, so that pipeline and input get calls will able to get the fileUrl.
## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33908)

### CODE REVIEW

**Comment by bhavya181** [comment]
trigger ft1

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33908#-:-N3sWFNu-jK_Ppk7Q6vF:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by bhavya181** [comment]
trigger ti0, ti4

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 8 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33908#-:-N4Bocp10gPVm6gx6EOS:bnfp4nl)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, 7 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33908#-:-N4BsZYI7fW1RWuyp9MW:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33908#-:-N4QrHX385Y-gPV435wE:bnfp4nl)* status: :shipit: complete! ✓

**Review by kapil-harness — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, 7 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33908)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, 7 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33908)* status: :shipit: complete! ✓

**Pull request merged**
