### PR TITLE
fix: [PIE-9232]: Remove deps on expression engine while resolving output…

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
… and outcomes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45657)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
Add UTs

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45657#-:-NRXTb4Q2BbUzk_t_JYo:b-qzg4r4)* status: 5 file(s) to review. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ExpandedJsonFunctorUtils.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/45657#-NRXPrsr0MyyAnTtngiG:-NRXPrsr0MyyAnTtngiH:bbdq7wi) ([raw file](https://github.com/harness/harness-core/blob/d3b7759da0a8e8e12509495c41c858cd86d5bb0f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ExpandedJsonFunctorUtils.java#L76)):*
> ```Java
>   }
> 
>   public String generateFullyQualifiedName(Ambiance ambiance, String expression) {
> ```

i think we should add note, this expression cannot contain nested expression, plus we should add a check as well in future no one uses this method for nested expressions
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ExpandedJsonFunctorUtils.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/45657#-NRXSD4V3Xbs0SmeK0yJ:-NRXSD4V3Xbs0SmeK0yK:b-arnzmh) ([raw file](https://github.com/harness/harness-core/blob/d3b7759da0a8e8e12509495c41c858cd86d5bb0f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ExpandedJsonFunctorUtils.java#L95)):*
> ```Java
>           break;
>         }
>         if (!level.getSkipExpressionChain() || level.getStepType().getStepCategory() == StepCategory.STRATEGY) {
> ```

add comments for special handling of strategy



_Code quote:_
```Java
getFullyQualifiedExpressionBasedOnGroup
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsOutcomeServiceImpl.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/45657#-NRXPMsx7JI0C7-Lfeqb:-NRXPMsx7JI0C7-Lfeqc:b-75jv9s) ([raw file](https://github.com/harness/harness-core/blob/d3b7759da0a8e8e12509495c41c858cd86d5bb0f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsOutcomeServiceImpl.java#L89)):*
> ```Java
>       Object value = evaluator.evaluateExpression(EngineExpressionEvaluator.createExpression(refObject.getName()));
>       if (value != null) {
>         // Add a log line
> ```

add log line to check on edge cases
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsOutcomeServiceImpl.java` line 211 at r2](https://reviewable.io/reviews/harness/harness-core/45657#-NRXSiG_0tb_P9jDQRWK:-NRXSiG_0tb_P9jDQRWL:byhml6b) ([raw file](https://github.com/harness/harness-core/blob/d3b7759da0a8e8e12509495c41c858cd86d5bb0f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsOutcomeServiceImpl.java#L211)):*
> ```Java
>                       .addCriteria(where(OutcomeInstanceKeys.name).is(name))
>                       .addCriteria(where(OutcomeInstanceKeys.fullyQualifiedName).is(fullyQualifiedName))
>                       .with(Sort.by(Sort.Direction.DESC, OutcomeInstanceKeys.createdAt));
> ```

is index updated?

Add why desc sort is required due to planNode executed multiple times



_Code quote:_
```Java
with(Sort.by(Sort.Direction.DESC, OutcomeInstanceKeys.createdAt));
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsSweepingOutputServiceImpl.java` line 199 at r2](https://reviewable.io/reviews/harness/harness-core/45657#-NRXTQ-l1HijeWPqHcry:-NRXTQ-l1HijeWPqHcrz:b5fnt0n) ([raw file](https://github.com/harness/harness-core/blob/d3b7759da0a8e8e12509495c41c858cd86d5bb0f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsSweepingOutputServiceImpl.java#L199)):*
> ```Java
>                       .addCriteria(where(ExecutionSweepingOutputKeys.fullyQualifiedName).is(fullyQualifiedName));
>     List<ExecutionSweepingOutputInstance> instances = mongoTemplate.find(query, ExecutionSweepingOutputInstance.class);
>     // Multiple instances might be returned if the same name was saved at different levels/specificity.
> ```

why here and outcome instance has different logic, both places it should be same to check for highest levelIdx and even in those last createdAt



_Code quote:_
```Java
ExecutionSweepingOutputInstance
```

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsSweepingOutputServiceImpl.java` line 199 at r2](https://reviewable.io/reviews/harness/harness-core/45657#-NRXTQ-l1HijeWPqHcry:-NRagCm38_4aP6npZydF:bzb74h3) ([raw file](https://github.com/harness/harness-core/blob/d3b7759da0a8e8e12509495c41c858cd86d5bb0f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsSweepingOutputServiceImpl.java#L199)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why here and outcome instance has different logic, both places it should be same to check for highest levelIdx and even in those last createdAt
</blockquote></details>

I think it is the same query as levelIdx but since we were already using it here therefore kept the same.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsOutcomeServiceImpl.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/45657#-NRXPMsx7JI0C7-Lfeqb:-NRanKwxEI_QzPY-CD0T:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d3b7759da0a8e8e12509495c41c858cd86d5bb0f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsOutcomeServiceImpl.java#L89)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add log line to check on edge cases
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ExpandedJsonFunctorUtils.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/45657#-NRXPrsr0MyyAnTtngiG:-NRanQwG2PS16ZpPsgcG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d3b7759da0a8e8e12509495c41c858cd86d5bb0f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ExpandedJsonFunctorUtils.java#L76)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i think we should add note, this expression cannot contain nested expression, plus we should add a check as well in future no one uses this method for nested expressions
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ExpandedJsonFunctorUtils.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/45657#-NRXSD4V3Xbs0SmeK0yJ:-NRaoEu19J_5yOP6lkH8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d3b7759da0a8e8e12509495c41c858cd86d5bb0f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ExpandedJsonFunctorUtils.java#L95)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comments for special handling of strategy
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsOutcomeServiceImpl.java` line 211 at r2](https://reviewable.io/reviews/harness/harness-core/45657#-NRXSiG_0tb_P9jDQRWK:-NRaoHeI26m1C2E-MUNJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d3b7759da0a8e8e12509495c41c858cd86d5bb0f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsOutcomeServiceImpl.java#L211)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

is index updated?

Add why desc sort is required due to planNode executed multiple times
</blockquote></details>

Done.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 2 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45657)* status: 6 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsOutcomeServiceImpl.java` line 213 at r2](https://reviewable.io/reviews/harness/harness-core/45657#-NRaseJw-saeZ_SYfqzp:-NRaseJw-saeZ_SYfqzq:bhl9rg2) ([raw file](https://github.com/harness/harness-core/blob/d3b7759da0a8e8e12509495c41c858cd86d5bb0f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsOutcomeServiceImpl.java#L213)):*
> ```Java
>                       .with(Sort.by(Sort.Direction.DESC, OutcomeInstanceKeys.createdAt));
> 
>     List<OutcomeInstance> instances = mongoTemplate.find(query, OutcomeInstance.class);
> ```

limit of 1
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsSweepingOutputServiceImpl.java` line 199 at r2](https://reviewable.io/reviews/harness/harness-core/45657#-NRXTQ-l1HijeWPqHcry:-NRash7GAyBO_LxnKroz:bai7ehv) ([raw file](https://github.com/harness/harness-core/blob/d3b7759da0a8e8e12509495c41c858cd86d5bb0f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsSweepingOutputServiceImpl.java#L199)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think it is the same query as levelIdx but since we were already using it here therefore kept the same. 
</blockquote></details>

discussed offline, it will be same as outcome.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsSweepingOutputServiceImpl.java` line 217 at r5](https://reviewable.io/reviews/harness/harness-core/45657#-NRaskgY-u_mJb82JA-m:-NRaskgY-u_mJb82JA-n:b-l8g5tb) ([raw file](https://github.com/harness/harness-core/blob/98cc2d2a51efaa3d968a6f7ebe2012d4a425b805/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsSweepingOutputServiceImpl.java#L217)):*
> ```Java
>         ? null
>         : instances.stream()
>               .max(Comparator.comparing(ExecutionSweepingOutputInstance::getLevelRuntimeIdIdx))
> ```

add limit of 1
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/data/OutcomeInstance.java` line 84 at r5](https://reviewable.io/reviews/harness/harness-core/45657#-NRas-S91y9AFuksiywM:-NRas-S91y9AFuksiywN:b81on6i) ([raw file](https://github.com/harness/harness-core/blob/98cc2d2a51efaa3d968a6f7ebe2012d4a425b805/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/data/OutcomeInstance.java#L84)):*
> ```Java
>                  .field(OutcomeInstanceKeys.planExecutionId)
>                  .field(OutcomeInstanceKeys.fullyQualifiedName)
>                  .build())
> ```

createdAt sort index

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsOutcomeServiceImpl.java` line 213 at r2](https://reviewable.io/reviews/harness/harness-core/45657#-NRaseJw-saeZ_SYfqzp:-NRbJvSIEIodI-Fri-7o:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d3b7759da0a8e8e12509495c41c858cd86d5bb0f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsOutcomeServiceImpl.java#L213)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

limit of 1
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsSweepingOutputServiceImpl.java` line 199 at r2](https://reviewable.io/reviews/harness/harness-core/45657#-NRXTQ-l1HijeWPqHcry:-NRbJwDXANT6wZOqJtBZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d3b7759da0a8e8e12509495c41c858cd86d5bb0f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsSweepingOutputServiceImpl.java#L199)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

discussed offline, it will be same as outcome.
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45657)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
