### PR TITLE
feat: [PIE-3443]: Add filter identifier and filter properties in envi…

### PR DESCRIPTION
**Pull request by prashantsharma04**
…ronment group list api call

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32170)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32170)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java, line 225 at r1](https://reviewable.io/reviews/harness/harness-core/32170#-N-NP-OL3NNRv_Jh6PPs:-N-NP-OL3NNRv_Jh6PPt:b-596p35) ([raw file](https://github.com/harness/harness-core/blob/38453ff2a5e66eaead567830d3677c0d7df9f5de/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L225)):*
> ```Java
>       @Parameter(description = "The word to be searched and included in the list response") @QueryParam(
>           NGResourceFilterConstants.SEARCH_TERM_KEY) String searchTerm,
>       @QueryParam(NGResourceFilterConstants.FILTER_KEY) String filterIdentifier, FilterPropertiesDTO filterProperties,
> ```

@RequestBody please add description here

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32170)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java, line 225 at r1](https://reviewable.io/reviews/harness/harness-core/32170#-N-NP-OL3NNRv_Jh6PPs:-N-NTjly4qqgXOzOjxrZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/38453ff2a5e66eaead567830d3677c0d7df9f5de/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L225)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@RequestBody please add description here
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32170)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32170#-:-N-X_gUa1HyVT-avOz47:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
