### PR TITLE
[fix]: [DEL-4800]: Delegate websocket connection issue after hotfix

### PR DESCRIPTION
**Pull request by raghuAtWings**
## Describe your changes

After the deployment of websocket reconnection optimizations we saw that some delegates disconnect and reconnect frequently. We saw socket close event in the delegate logs. This did not affect any deployment but we want to find the reason. 

1. reducing the heartbeat from delegates to manager to 50 seconds. We are doing this since the idle time for the LB in ancestry is one min. We are suspecting that the websocket might be closed because of that. 
2. adding logs to see the reason for disconnection

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37357)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_NA_** 
 


            
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37357)

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/37357#-NBZEBg8DWdCNMe-XO8_:-NBZEBg95jfB09vtSl5l:bkibcof) ([raw file](https://github.com/harness/harness-core/blob/b1b84f6c16573c92ec03527e8c8821c6dcb58c36/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L124)):*
> ```Java
>                    AutoLogContext ignore3 = new WebsocketLogContext(event.getResource().uuid(), OVERRIDE_ERROR)) {
>                 log.info("delegate socket disconnected {}", event);
>                 Delegate delegate = delegateCache.get(accountId, delegateId, true);
> ```

you want to print the object here ? pretty print?

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37357)* status: 0 of 1 approvals obtained.

**Review by jennyjames21 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37357)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
trigger messagecheck

**Pull request merged**
