### PR TITLE
feat: [CDS-37192]: Exclude the number of reference by entities for fo…

### PR DESCRIPTION
**Pull request by bojanmicovic**
…lder from backend error message.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33341)

### CODE REVIEW

**Comment by bojanmicovic** [comment]
trigger messagecheck

**Review by acasian-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33341)* status: Some of the checks are too old.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 4 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33341)* status: 10 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileReferenceServiceImpl.java` line 115 at r2](https://reviewable.io/reviews/harness/harness-core/33341#-N3ep31u1kYWjaHm0zYV:-N3ep31u1kYWjaHm0zYW:bbgckz6) ([raw file](https://github.com/harness/harness-core/blob/063f74ce023faede09d2cd7aec958e80d614d1a8/877-filestore/src/main/java/io/harness/filestore/service/impl/FileReferenceServiceImpl.java#L115)):*
> ```Java
> 
>   private List<String> getFolderChildrenFQNs(NGFile fileOrFolder) {
>     GraphLookupOperation graphLookupOperation = Aggregation.graphLookup("ngFiles")
> ```

I think grapLookupOperation will do sub queries based on identifier and parent identifier not taking into consideration scope (account, org, project). 

It means we are going to find the file identifier on specific scope in matchOperation, if the file with the same identifier exists on another scope lookup will take into account and files/folder from another scope. Pls correct me if i am wrong. What i suggest let's add support for path on folder and file level and get all children where  "fileOrFolder" path matching sub folders/files path by regex on specific scope. When you get the result exclude the match for searching fileOrFolder 'path' .

Or, try to add scope criteria to graphLookupOperation. Let's discuss.  The solution with patch could be easer. 
___
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java` line 221 at r2](https://reviewable.io/reviews/harness/harness-core/33341#-N3eiHEhAY_GCv6c63ko:-N3eiHEhAY_GCv6c63kp:b97al8p) ([raw file](https://github.com/harness/harness-core/blob/063f74ce023faede09d2cd7aec958e80d614d1a8/877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java#L221)):*
> ```Java
>   public FolderNodeDTO listFolderNodes(@NotNull String accountIdentifier, String orgIdentifier,
>       String projectIdentifier, @NotNull FolderNodeDTO folderNodeDTO) {
>     fetchFileOrThrow(accountIdentifier, orgIdentifier, projectIdentifier, folderNodeDTO.getIdentifier());
> ```

Pls remove this fetchFileOrThrow. We agreed with UI team to return empty list not throw error.



_Code quote:_
```Java
fetchFileOrThrow(accountIdentifier, orgIdentifier, projectIdentifier, folderNodeDTO.getIdentifier())
```

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/33341)

**Pull request closed without merging**
