### PR TITLE
fix: [PLG-1374]: added referer to start trial

### PR DESCRIPTION
**Pull request by devinder-harness**
## Describe your changes
This PR adds `refererURL` field to track event which helps us with tracking the user signup traffic
Click https://harness.atlassian.net/browse/PLG-1374 to know more
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37240)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37240)

**Comment by yogesh-chauhan** [comment]
*[`920-ng-signup/src/main/java/io/harness/signup/services/SignupService.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/37240#-NBLHpvu4aUSSxHhhbPc:-NBLHpvu4aUSSxHhhbPd:b-th60lt) ([raw file](https://github.com/harness/harness-core/blob/a52cebf39285c385568bf7f9af9e4d795d62f687/920-ng-signup/src/main/java/io/harness/signup/services/SignupService.java#L21)):*
> ```Java
> @OwnedBy(GTM)
> public interface SignupService {
>   UserInfo signup(SignupDTO dto, String captchaToken, String referer) throws WingsException;
> ```

Since referer can be null, we have 2 options
- create an overloaded method that just takes (dto, captchtoken ) along with the above method
- use @Nullable annotation to let people know that this field is okay to be null

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37240)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Comment by devinder-harness** [comment]
> _[`920-ng-signup/src/main/java/io/harness/signup/services/SignupService.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/37240#-NBLHpvu4aUSSxHhhbPc:-NBLHpvu4aUSSxHhhbPd:b-th60lt) ([raw file](https://github.com/harness/harness-core/blob/a52cebf39285c385568bf7f9af9e4d795d62f687/920-ng-signup/src/main/java/io/harness/signup/services/SignupService.java#L21)):_
> 
> > ```java
> > @OwnedBy(GTM)
> > public interface SignupService {
> >   UserInfo signup(SignupDTO dto, String captchaToken, String referer) throws WingsException;
> > ```
> 
> Since referer can be null, we have 2 options
> 
> * create an overloaded method that just takes (dto, captchtoken ) along with the above method
> * use @nullable annotation to let people know that this field is okay to be null

added @nullable

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37240)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Comment by devinder-harness** [comment]
trigger ti1

**Review by bhavya-sinha — DISMISSED** [review]

**Review by pranil-harness — APPROVED** [review]
> Reviewed 9 of 11 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37240)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by pranil-harness — APPROVED** [review]

**Review by hekimoglu010 — APPROVED** [review]
> Reviewed 9 of 11 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37240)* status: :shipit: complete! ✓

**Review by thomas-grasman — APPROVED** [review]

**Pull request merged**
