### PR TITLE
feat: [PL-26239]: changes for listing github app repos

### PR DESCRIPTION
**Pull request by bhavya181**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36052)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36052)

**Comment by bhavya181** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`product/ci/scm/git/git.go` line 705 at r4](https://reviewable.io/reviews/harness/harness-core/36052#-NAsHzOM0bQRr6ASxrNy:-NAsHzOM0bQRr6ASxrNz:b-t8a09r) ([raw file](https://github.com/harness/harness-core/blob/36fec9a167e9b7964a71cb837edeb9eebf472f53/product/ci/scm/git/git.go#L705)):*
> ```Go
> // Repos returns the full repository list, traversing and
> // combining paginated responses if necessary.
> func Repos(ctx context.Context, client *scm.Client, log *zap.SugaredLogger, isGithubApp bool) ([]*scm.Repository, error) {
> ```

We shouldn't pass isGithubApp as a separate parameter here. What if such things come in future for all other providers as well, then it will just pollute the argument list. 
Lets create some metadata request and just add a field for isGithubApp.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36052)* status: 7 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`product/ci/scm/git/git.go` line 705 at r4](https://reviewable.io/reviews/harness/harness-core/36052#-NAsHzOM0bQRr6ASxrNy:-NAyOwDJ76TVLfDZbpwH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/36fec9a167e9b7964a71cb837edeb9eebf472f53/product/ci/scm/git/git.go#L705)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We shouldn't pass isGithubApp as a separate parameter here. What if such things come in future for all other providers as well, then it will just pollute the argument list. 
Lets create some metadata request and just add a field for isGithubApp.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 7 files at r2, 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36052)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 7 files at r2, 1 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36052)* status: 3 file(s) to review.

**Review by rijajoo — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r2, 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36052#-:-NAyadnu6DYk9vAqlCNH:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
