### PR TITLE
[feat]: [PIE-3778]: Introducing default value in runtime input

### PR DESCRIPTION
**Pull request by brijeshdhakar**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33279)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger ti2

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33279)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/33279#-N2LqtoV9i1uxyD-oQJq:-N2LqtoV9i1uxyD-oQJr:bv4tey9) ([raw file](https://github.com/harness/harness-core/blob/cf7ed7ad816c8e492745dadef3344a73f04ec7dc/970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java#L55)):*
> ```Java
>   public static <T> ParameterField<T> createExpressionField(
>       boolean isExpression, String expressionValue, InputSetValidator inputSetValidator, boolean isTypeString) {
>     return new ParameterField<>(null, isExpression, expressionValue, inputSetValidator, isTypeString);
> ```

use constructor with default value as null



_Code quote:_
```Java
return new ParameterField<>(null, isExpression, expressionValue, inputSetValidator, isTypeString);
```
___
*[`970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/33279#-N2Lo6Ap02mTABR2PlDJ:-N2Lo6Ap02mTABR2PlDK:b-qdblnb) ([raw file](https://github.com/harness/harness-core/blob/cf7ed7ad816c8e492745dadef3344a73f04ec7dc/970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java#L61)):*
> ```Java
>       T defaultValue, InputSetValidator inputSetValidator, boolean isTypeString) {
>     if (expressionValue.equals("<+input>")) {
>       return new ParameterField<>(null, defaultValue, false, null, inputSetValidator, isTypeString);
> ```

why its not an expression if runtime input?



_Code quote:_
```Java
false,
```
___
*[`970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/33279#-N2LqBE2E4TpYMnbhK2X:-N2LqBE2E4TpYMnbhK2Y:bu49dx) ([raw file](https://github.com/harness/harness-core/blob/cf7ed7ad816c8e492745dadef3344a73f04ec7dc/970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java#L63)):*
> ```Java
>       return new ParameterField<>(null, defaultValue, false, null, inputSetValidator, isTypeString);
>     }
>     return new ParameterField<>(null, defaultValue, isExpression, expressionValue, inputSetValidator, isTypeString);
> ```

default value should also be null



_Code quote:_
```Java
null, defaultValue
```
___
*[`970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java` line 187 at r2](https://reviewable.io/reviews/harness/harness-core/33279#-N2LsVvXDR4uDAfUWyjC:-N2LsVvXDR4uDAfUWyjD:b-o4flgr) ([raw file](https://github.com/harness/harness-core/blob/cf7ed7ad816c8e492745dadef3344a73f04ec7dc/970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java#L187)):*
> ```Java
>             defaultValueString = defaultValue;
>           }
>         }
> ```

this should be better handled.



_Code quote:_
```Java
      defaultValueString = matcher.group(1);
      List<Pattern> patterns = new ArrayList<>();
      patterns.add(Pattern.compile("\\.default\\((.*?)\\).allowedValues\\(.*?\\)$"));
      patterns.add(Pattern.compile("\\.default\\((.*?)\\).executionInput\\(.*?\\)$"));
      for (Pattern pattern : patterns) {
        Matcher m = pattern.matcher(text);
        if (m.find()) {
          String defaultValue = m.group(1);
          if (defaultValueString == null || defaultValueString.length() < defaultValue.length()) {
            defaultValueString = defaultValue;
          }
        }
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33279)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java` line 187 at r2](https://reviewable.io/reviews/harness/harness-core/33279#-N2LsVvXDR4uDAfUWyjC:-N2Lt05OAS0H7zRQeZ0l:b-i6yv4m) ([raw file](https://github.com/harness/harness-core/blob/cf7ed7ad816c8e492745dadef3344a73f04ec7dc/970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java#L187)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this should be better handled.
</blockquote></details>

Add unit test

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33279)* status: 2 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/33279#-N2LqtoV9i1uxyD-oQJq:-N2Mp69eA_NQKLarUB3x:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cf7ed7ad816c8e492745dadef3344a73f04ec7dc/970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java#L55)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use constructor with default value as null
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/33279#-N2Lo6Ap02mTABR2PlDJ:-N2MpXUA0mxGI_jAxdnI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cf7ed7ad816c8e492745dadef3344a73f04ec7dc/970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java#L61)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why its not an expression if runtime input?
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/33279#-N2LqBE2E4TpYMnbhK2X:-N2MpNtuEMlgNtbPvOxc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cf7ed7ad816c8e492745dadef3344a73f04ec7dc/970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

default value should also be null
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java` line 187 at r2](https://reviewable.io/reviews/harness/harness-core/33279#-N2LsVvXDR4uDAfUWyjC:-N2MpCQQ6x4fPwufbaxD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cf7ed7ad816c8e492745dadef3344a73f04ec7dc/970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java#L187)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Add unit test
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33279)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/33279#-N2LqBE2E4TpYMnbhK2X:-N2Pi54o1J_XsPsmu3WW:b-weqljt) ([raw file](https://github.com/harness/harness-core/blob/cf7ed7ad816c8e492745dadef3344a73f04ec7dc/970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java#L63)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

how it is done?
___
*[`970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/33279#-N2MqwZ_7-B5M9F1mjTD:-N2Pj2Rm5UujAQh8yk1L:b-f34lpn) ([raw file](https://github.com/harness/harness-core/blob/cf7ed7ad816c8e492745dadef3344a73f04ec7dc/970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java#L95)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

@archit-harness we are sending isExpression=false if defaultValue is not null. This is with <+input> only because when user does not give value for <+input> while starting pipeline then we need to use default value and not try to evaluate <+input> expression(evaluating <+input> will fail anyways)
</blockquote></details>

This we should discuss more on it.
___
*[`970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java` line 193 at r3](https://reviewable.io/reviews/harness/harness-core/33279#-N2PipqqB-k44-9XAYwX:-N2PipqqB-k44-9XAYwY:b8v5zei) ([raw file](https://github.com/harness/harness-core/blob/f2faa8ff83a2f16ad6de6e1c65f2f5ad31fbdd34/970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java#L193)):*
> ```Java
>           if (defaultValueString == null || defaultValue.length() < defaultValueString.length()) {
>             defaultValueString = defaultValue;
>           }
> ```

where is <+input>.default("abc") is handled?



_Code quote:_
```Java
        Matcher m = pattern.matcher(text);
        if (m.find()) {
          String defaultValue = m.group(1);
          // Take the smallest match as default value. <+input>.default("abc").executionInput() can match to "abc" and
          // "abc").executionInput(). We need to take the "abc"
          if (defaultValueString == null || defaultValue.length() < defaultValueString.length()) {
            defaultValueString = defaultValue;
          }
```
___
*[`970-ng-commons/src/test/java/io/serializer/jackson/ParameterFieldDeserializerTest.java` line 138 at r3](https://reviewable.io/reviews/harness/harness-core/33279#-N2PiTnQ6A6t-74xP-qr:-N2PiTnQ6A6t-74xP-qs:b-1eycky) ([raw file](https://github.com/harness/harness-core/blob/f2faa8ff83a2f16ad6de6e1c65f2f5ad31fbdd34/970-ng-commons/src/test/java/io/serializer/jackson/ParameterFieldDeserializerTest.java#L138)):*
> ```Java
>     }
>     // testing .executionInput() patterns after .default construct
>     text = "<+input>.default(\"value\").allowedValues(\"random\").executionInput()";
> ```

can we have a unit test where default is after allowed value or executionInput as well



_Code quote:_
```Java
default(\"value\").all
```

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33279)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/33279#-N2MqwZ_7-B5M9F1mjTD:-N2Pkh-t2rwjlnq2x4Er:b75pynb) ([raw file](https://github.com/harness/harness-core/blob/cf7ed7ad816c8e492745dadef3344a73f04ec7dc/970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java#L95)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

This we should discuss more on it.
</blockquote></details>

Ok. For now we can merge this in feature branch. And we can discuss this more when we add executionInput. ExecutionInput might bring some more unknowns so it would be better to think when all cases would be there.
___
*[`970-ng-commons/src/test/java/io/serializer/jackson/ParameterFieldDeserializerTest.java` line 138 at r3](https://reviewable.io/reviews/harness/harness-core/33279#-N2PiTnQ6A6t-74xP-qr:-N2PkQkRAKT2W7Q5tZwq:b3ttq85) ([raw file](https://github.com/harness/harness-core/blob/f2faa8ff83a2f16ad6de6e1c65f2f5ad31fbdd34/970-ng-commons/src/test/java/io/serializer/jackson/ParameterFieldDeserializerTest.java#L138)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we have a unit test where default is after allowed value or executionInput as well
</blockquote></details>

We have a case just below this assert. When default if after allowedValues()
`<+input>.allowedValues(\"random\").default(\"value\").executionInput()"`



_Code quote:_
```Java
<+input>.allowedValues(\"random\").default(\"value\").executionInput()"
```

**Pull request closed without merging**
