### PR TITLE
fix: [PL-30838]: Added enforcement for service accounts

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Describe your changes
Service Accounts Groups are limited to 100 for free users
Tested whether the check locally by trying to service accounts beyond limit
## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42904)

### CODE REVIEW

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42904)* status: 8 file(s) to review. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 123 at r3](https://reviewable.io/reviews/harness/harness-core/42904#-NMPPukf3fcuxSxas2ho:-NMPPukf3fcuxSxas2hp:b-urdqfn) ([raw file](https://github.com/harness/harness-core/blob/d4e38788cb0604024975b89b419fce8b6f34e8d9/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L123)):*
> ```Java
> import io.harness.ng.core.migration.UserGroupMigrationProvider;
> import io.harness.ng.core.remote.UserGroupRestrictionUsageImpl;
> import io.harness.ng.core.remote.licenserestriction.*;
> ```

we dont use all (*) imports.

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42904#-:-NMPSRiDA3bcQPCa2SFy:bnfp4nl)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by VikasMaddukuriHarness** [comment]
trigger ti0,ti1

**Review by reetika04 — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42904)* status: :shipit: complete! ✓

**Pull request merged**
