### PR TITLE
feat: [PL-22018]: integrated scm service with go scm compare commits API change

### PR DESCRIPTION
**Pull request by mohitg0795**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30069)

### CODE REVIEW

**Comment by USB-05** [comment]
trigger ti0 ti1 ti2 ti3 ti4 ft1 ft2

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 3 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30069)* status: 4 file(s) to review.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30069)* status: 1 file(s) to review.

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30069)* status: 3 file(s) to review.

**Review by kapil-harness — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30069)* status: 1 file(s) to review.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30069)* status: 1 file(s) to review.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30069)* status: :shipit: complete! ✓

**Pull request merged**
