### PR TITLE
[feat]: [PIE-9454]: Onboarded DefaultStoreType for Pipeline, InputSets and Templates.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Change: Have Onboarded defaultStoreType as GitX settings. Whenever user doesn't pass StoreType as parameter than we will set the storeType as the default mentioned in settings.
Testing: Local: have tested cases like sending store type as null, empty and garbage values for INLINE/REMOTE for pipeline,inputSets and templates create flows have been tested.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46597)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java` line 109 at r3](https://reviewable.io/reviews/harness/harness-core/46597#-NTQ2BtIDZ3U9aINbc9x:-NTQ2BtIDZ3U9aINbc9y:bildu7d) ([raw file](https://github.com/harness/harness-core/blob/ff4ce027a6ceae03b1d55bd611bf218417f308bd/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java#L109)):*
> ```Java
> 
>   public boolean isNullOrDefault(String val) {
>     // Also returns true if val is empty
> ```

whats the requirement of this comment? Also, as a habit, always do DEFAULT.equals(val).

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 170 at r3](https://reviewable.io/reviews/harness/harness-core/46597#-NTQ3vt2Ag9QNqNQoFih:-NTQ3vt2Ag9QNqNQoFii:b-urhc7p) ([raw file](https://github.com/harness/harness-core/blob/ff4ce027a6ceae03b1d55bd611bf218417f308bd/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L170)):*
> ```Java
>     assureThatTheProjectAndOrgExists(
>         templateEntity.getAccountId(), templateEntity.getOrgIdentifier(), templateEntity.getProjectIdentifier());
>     gitXSettingsHelper.applyGitXSettingsIfApplicable(
> ```

We shouldn't move the grouping method to gitx helper. There can be multiple such groupings, so then if everyone starts to create different groupings and put it into the helper, it doesn't make sense.
This grouping method should simply be private method in this file itself.

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/46597#-NTQ6ceEDdjzFrvRUGun:-NTQ6ceEDdjzFrvRUGuo:b-ez79lu) ([raw file](https://github.com/harness/harness-core/blob/ff4ce027a6ceae03b1d55bd611bf218417f308bd/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java#L79)):*
> ```Java
>       StoreType defaultStoreTypeForEntities;
> 
>       if (isGitExperienceEnforcedInSettings(accountIdentifier, orgIdentifier, projIdentifier)) {
> ```

can't we have something like if gitx is enforced, then automatically default storeType for entities returns REMOTE from the settings service itself? Fetching 2 settings and putting all logic on our end seems bit over.

**Comment by mohitg0795** [comment]
*[`953-git-sync-commons/src/main/java/io/harness/gitsync/interceptor/GitSyncConstants.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/46597#-NTQ6zd7CK4L3Gx6wwjq:-NTQ6zd7CK4L3Gx6wwjr:b-aa7h6p) ([raw file](https://github.com/harness/harness-core/blob/ff4ce027a6ceae03b1d55bd611bf218417f308bd/953-git-sync-commons/src/main/java/io/harness/gitsync/interceptor/GitSyncConstants.java#L27)):*
> ```Java
>   public static final String DEFAULT_CONNECTOR_FOR_GIT_EXPERIENCE = "default_connector_for_git_experience";
>   public static final String DEFAULT_STORE_TYPE_FOR_ENTITIES = "default_store_type_for_entities";
>   public static final String COULD_NOT_FETCH_SETTING = "Could not fetch setting: %s";
> ```

Good job on thinking to templatize the error message. But lets not put it in this file. This is for particular constants eg: some field constants etc. Logging constants are very specific to different classes and can be defined in the same class itself.

**Review by shalini-agr — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46597)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46597)* status: 6 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 170 at r3](https://reviewable.io/reviews/harness/harness-core/46597#-NTQ3vt2Ag9QNqNQoFih:-NTUaES-3HI2zL46tbzE:b-6g66ul) ([raw file](https://github.com/harness/harness-core/blob/ff4ce027a6ceae03b1d55bd611bf218417f308bd/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L170)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We shouldn't move the grouping method to gitx helper. There can be multiple such groupings, so then if everyone starts to create different groupings and put it into the helper, it doesn't make sense.
This grouping method should simply be private method in this file itself. 
</blockquote></details>

That will lead to 3 copies of this method in Pipeline, InputSet and Template -ServiceImpl 
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java` line 109 at r3](https://reviewable.io/reviews/harness/harness-core/46597#-NTQ2BtIDZ3U9aINbc9x:-NTUaQzKDyyYAZGFRUP4:b85u7p0) ([raw file](https://github.com/harness/harness-core/blob/ff4ce027a6ceae03b1d55bd611bf218417f308bd/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java#L109)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats the requirement of this comment? Also, as a habit, always do DEFAULT.equals(val).
</blockquote></details>

This was a previously written method i just have added comment to highlight that it returns true for 3 cases null, default and Empty rather than 2 null or Default as the method name suggests.
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/46597#-NTQ6CQ-5_JfiLW3tzMn:-NTUb-3X-Uy-xU2HjNp8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff4ce027a6ceae03b1d55bd611bf218417f308bd/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java#L74)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please use complete names : projectIdentifier
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/46597#-NTQ6ceEDdjzFrvRUGun:-NTUb2gG57gURql_ZvAN:b-rx4x1q) ([raw file](https://github.com/harness/harness-core/blob/ff4ce027a6ceae03b1d55bd611bf218417f308bd/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java#L79)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can't we have something like if gitx is enforced, then automatically default storeType for entities returns REMOTE from the settings service itself? Fetching 2 settings and putting all logic on our end seems bit over.
</blockquote></details>

It would have been helpful but settingsFramework code does not support this, Will confirm with @tiwaritejas once on this.
___
*[`953-git-sync-commons/src/main/java/io/harness/gitsync/interceptor/GitSyncConstants.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/46597#-NTQ6zd7CK4L3Gx6wwjq:-NTUbb1Z7CSFnUOYAkAo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff4ce027a6ceae03b1d55bd611bf218417f308bd/953-git-sync-commons/src/main/java/io/harness/gitsync/interceptor/GitSyncConstants.java#L27)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Good job on thinking to templatize the error message. But lets not put it in this file. This is for particular constants eg: some field constants etc. Logging constants are very specific to different classes and can be defined in the same class itself.
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 170 at r3](https://reviewable.io/reviews/harness/harness-core/46597#-NTQ3vt2Ag9QNqNQoFih:-NTUd0X0CcaHM8b4j7h2:b-74rxe) ([raw file](https://github.com/harness/harness-core/blob/ff4ce027a6ceae03b1d55bd611bf218417f308bd/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L170)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

That will lead to 3 copies of this method in Pipeline, InputSet and Template -ServiceImpl 
</blockquote></details>

Doesn't matter. If it leads to 30 copies, its fine. Can you explain me how does that make sense to just have it at 1 place? Can you address the concerns that I raised in my last comment?

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java` line 109 at r3](https://reviewable.io/reviews/harness/harness-core/46597#-NTQ2BtIDZ3U9aINbc9x:-NTUdEcsCphZVh0xAVM5:b-tjinie) ([raw file](https://github.com/harness/harness-core/blob/ff4ce027a6ceae03b1d55bd611bf218417f308bd/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java#L109)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

This was a previously written method i just have added comment to highlight that it returns true for 3 cases null, default and Empty rather than 2 null or Default as the method name suggests.
</blockquote></details>

I think whoever reads the method should be easily able to understand it. Wdyt? We should only add comments to explain something thats difficult to infer on a direct view.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46597)* status: 6 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java` line 109 at r3](https://reviewable.io/reviews/harness/harness-core/46597#-NTQ2BtIDZ3U9aINbc9x:-NTXLGK9A-VetSUL6r8r:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff4ce027a6ceae03b1d55bd611bf218417f308bd/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java#L109)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think whoever reads the method should be easily able to understand it. Wdyt? We should only add comments to explain something thats difficult to infer on a direct view.
</blockquote></details>

Done.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46597)* status: 6 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 170 at r3](https://reviewable.io/reviews/harness/harness-core/46597#-NTQ3vt2Ag9QNqNQoFih:-NTXZa7z12n6ZW9M4bSm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff4ce027a6ceae03b1d55bd611bf218417f308bd/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L170)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Doesn't matter. If it leads to 30 copies, its fine. Can you explain me how does that make sense to just have it at 1 place? Can you address the concerns that I raised in my last comment?
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46597)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by shalini-agr — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46597)* status: :shipit: complete! ✓

**Comment by senjucanon2** [comment]
trigger review

**Review by utkarshchoubey-harness — APPROVED** [review]

**Pull request merged**
