### PR TITLE
[feat]: [CDS-36899]: instance sync serverless aws lambda

### PR DESCRIPTION
**Pull request by PragyeshMishra01**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32704)

### CODE REVIEW

**Comment by sainath-b** [comment]
trigger feature-build

**Comment by sainath-b** [comment]
trigger feature-build

**Comment by sainath-b** [comment]
trigger feature-build

**Comment by sainath-b** [comment]
trigger feature-build

**Comment by sainath-b** [comment]
trigger feature-build

**Comment by sainath-b** [comment]
trigger messagecheck

**Comment by sainath-b** [comment]
trigger checkstyle

**Review by arpit3107 — APPROVED** [review]
> Reviewed 13 of 25 files at r1, 18 of 30 files at r2, 5 of 7 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32704)* status: :shipit: complete! ✓

**Comment by sainath-b** [comment]
trigger checkstyle

**Comment by sainath-b** [comment]
trigger feature-build

**Comment by sainath-b** [comment]
trigger pmd

**Comment by sainath-b** [comment]
trigger ti0

**Comment by sainath-b** [comment]
trigger ti1

**Comment by sainath-b** [comment]
trigger ti2

**Comment by sainath-b** [comment]
trigger ti3

**Comment by sainath-b** [comment]
trigger ti4

**Comment by sainath-b** [comment]
trigger FunctionalTest1

**Comment by sainath-b** [comment]
trigger ft1

**Comment by sainath-b** [comment]
trigger ft2

**Review by achyuth-harness — APPROVED** [review]
:lgtm:

> Reviewed 13 of 25 files at r1, 18 of 30 files at r2, 5 of 7 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32704#-:-N2Lyz845q1483j5VHVM:bnfp4nl)* status: :shipit: complete! ✓

**Comment by sainath-b** [comment]
trigger ti0

**Comment by sainath-b** [comment]
trigger ti1

**Comment by sainath-b** [comment]
trigger ti2

**Comment by sainath-b** [comment]
trigger ti3

**Comment by sainath-b** [comment]
trigger ti4

**Pull request merged**
