### PR TITLE
techdebt: [CDS-74001]: Throw error in ParameterDocumentFieldMapper if the type of resolved expression value doesn't match the expected type of field.

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Issue:** Currently, we don't have handling for class cast exceptions in one place with a helpful error message with field name and value.

**Changes:** Generally, we get class cast exceptions when a field is an expression and its resolved value is of a different type than the expected field type. And, this will be first caught in ParameterDocumentFieldMapper. So, there, we have added handling to throw an exception in case of an error in the class cast. And, then in Recaster and ComplexFieldRecaster classes, we are building the path of the field by saving in exception and appending during the recursion.

**Impact:** A generic error will be thrown for all class cast issues with paramterField type. The error contains expected and actual types of fields, the actual value of the field obtained, and the field path.

**Testing:**
Earlier we were throwing these error logs from ParamterDocumentFieldMapper whenever there was a difference in actual and expected types of a field. `Expected value of type: %s, got: %s`. We checked all such logs in prod and noted down for what fields we are getting this error. We saw these: integer, double, list, secret, imagePullPolicy, boolean. Tested all these field types locally.

Examples of updated error message:

Screenshot 2023-07-14 at 5 11 17 PM
Screenshot 2023-07-14 at 4 08 27 PM
Screenshot 2023-07-14 at 4 09 37 PM
Screenshot 2023-07-14 at 4 14 47 PM
Screenshot 2023-07-14 at 4 15 58 PM
Screenshot 2023-07-14 at 4 17 34 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50422)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger ut4, ut5, ut6

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50422)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`979-recaster/src/test/java/io/harness/exceptions/CastedFieldExceptionTest.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/50422#-N_ICOmt8qdi48rnquYo:-N_ICOmu6jmMMTIbsWB8:b-75ywm7) ([raw file](https://github.com/harness/harness-core/blob/9217120e6efafee8d4fb9d25f62970b4b957a226/979-recaster/src/test/java/io/harness/exceptions/CastedFieldExceptionTest.java#L27)):*
> ```Java
>   public void testCastedFieldExceptionConstructor() {
>     String message = "CastedFieldException";
>     io.harness.exception.CastedFieldException castedFieldException = new CastedFieldException(message);
> ```

why is this needed?
___
*[`980-commons/src/main/java/io/harness/exception/ParameterFieldCastException.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/50422#-N_ICm2mDQbKb_1HKAYo:-N_ICm2n1XMHqsNv5wXO:blhvnma) ([raw file](https://github.com/harness/harness-core/blob/9217120e6efafee8d4fb9d25f62970b4b957a226/980-commons/src/main/java/io/harness/exception/ParameterFieldCastException.java#L17)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> public class ParameterFieldCastException extends WingsException {
> ```

we should move to 970-ng as ParamterField exists there

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50422)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`979-recaster/src/main/java/io/harness/core/Recaster.java` line 144 at r2](https://reviewable.io/reviews/harness/harness-core/50422#-N_Ia1pEC-NYz-2A0dFN:-N_Ia1pEC-NYz-2A0dFO:b6y1bl4) ([raw file](https://github.com/harness/harness-core/blob/9217120e6efafee8d4fb9d25f62970b4b957a226/979-recaster/src/main/java/io/harness/core/Recaster.java#L144)):*
> ```Java
>                                                               : ((CastedFieldException) e).getFieldName();
>             List<String> messageListSplitBySpace =
>                 Arrays.stream(e.getMessage().split(" ")).collect(Collectors.toList());
> ```

discussed offline to correct
___
*[`980-commons/src/main/java/io/harness/exception/ParameterFieldCastException.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/50422#-N_ICm2mDQbKb_1HKAYo:-N_IbBjj3N8mP-5BgAxn:bysziek) ([raw file](https://github.com/harness/harness-core/blob/9217120e6efafee8d4fb9d25f62970b4b957a226/980-commons/src/main/java/io/harness/exception/ParameterFieldCastException.java#L17)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should move to 970-ng as ParamterField exists there
</blockquote></details>

add comments to explain this better

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger ut5, ut7, ut8

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50422)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`979-recaster/src/main/java/io/harness/fieldrecaster/ComplexFieldRecaster.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/50422#-N_XUOazBN5RcuIkTmIC:-N_XUOazBN5RcuIkTmID:bri00lp) ([raw file](https://github.com/harness/harness-core/blob/52a2ed0c8b6d0c78648e94f51e01073ceef33735/979-recaster/src/main/java/io/harness/fieldrecaster/ComplexFieldRecaster.java#L65)):*
> ```Java
>       } else if (e instanceof CastedFieldException) {
>         // We are building path of field by appending the field name from the caught exception
>         throw new RecasterException(format(((CastedFieldException) e).getMessageWithoutFieldPath(),
> ```

extract them as variables for readabilty



_Code quote:_
```Java
(CastedFieldException) e
```

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50422)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`979-recaster/src/main/java/io/harness/fieldrecaster/ComplexFieldRecaster.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/50422#-N_XUOazBN5RcuIkTmIC:-N_XYDtR0kGF4ifFv8Y4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/52a2ed0c8b6d0c78648e94f51e01073ceef33735/979-recaster/src/main/java/io/harness/fieldrecaster/ComplexFieldRecaster.java#L65)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

extract them as variables for readabilty
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger ut5, ut6, ut7, ut8, ut9

**Review by archit-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50422)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldMapper.java` line 107 at r4](https://reviewable.io/reviews/harness/harness-core/50422#-N_YJYIb0Lu2fhePBIAE:-N_YJYIb0Lu2fhePBIAF:blosy0) ([raw file](https://github.com/harness/harness-core/blob/2a039947771fc1f2eaf535e3df5c005bf1d44b77/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldMapper.java#L107)):*
> ```Java
>       log.error(String.format("Expected value of type: %s, got: %s with value %s", cls.getSimpleName(),
>           parameterFieldValueWrapper.getValue().getClass().getSimpleName(), parameterFieldValueWrapper.getValue()));
>       throw new ParameterFieldCastException(
> ```

Since this is in yaml-commons, what will happen if the sdk has this change and pipeline-service does not?

**Comment by sahilhindwani-harness** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldMapper.java` line 108 at r4](https://reviewable.io/reviews/harness/harness-core/50422#-N_YJf2pBwY6M_2nr1fL:-N_YJf2pBwY6M_2nr1fM:b-gw3m4h) ([raw file](https://github.com/harness/harness-core/blob/2a039947771fc1f2eaf535e3df5c005bf1d44b77/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldMapper.java#L108)):*
> ```Java
>           parameterFieldValueWrapper.getValue().getClass().getSimpleName(), parameterFieldValueWrapper.getValue()));
>       throw new ParameterFieldCastException(
>           String.format("The field should be of type [%s] but got: [%s] with value [%s]", cls.getSimpleName(),
> ```

nit: Could you please create a constants file and move this over there?

**Comment by sahilhindwani-harness** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldProcessor.java` line 124 at r4](https://reviewable.io/reviews/harness/harness-core/50422#-N_YJvJxBaRpe1i3Ggez:-N_YJvJxBaRpe1i3Ggf-:b-irwh0b) ([raw file](https://github.com/harness/harness-core/blob/2a039947771fc1f2eaf535e3df5c005bf1d44b77/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldProcessor.java#L124)):*
> ```Java
>           if (finalValue.getClass().equals(String.class)) {
>             finalValue = Double.valueOf((String) finalValue);
>           } else if (finalValue.getClass().equals(Integer.class)) {
> ```

Maybe check instance [Number.class|https://docs.oracle.com/javase/8/docs/api/java/lang/Number.html] here?

**Comment by sahilhindwani-harness** [comment]
*[`979-recaster/src/main/java/io/harness/core/Recaster.java` line 147 at r4](https://reviewable.io/reviews/harness/harness-core/50422#-N_YKKbe3kfe4U_05tJI:-N_YKKbe3kfe4U_05tJJ:b-6ocvot) ([raw file](https://github.com/harness/harness-core/blob/2a039947771fc1f2eaf535e3df5c005bf1d44b77/979-recaster/src/main/java/io/harness/core/Recaster.java#L147)):*
> ```Java
>                                                recasterMap.getIdentifier(), entity.getClass(), cf.getField().getName()),
>                 e);
>           }
> ```

Should we move this handling to a separate function for readability?

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 2 of 9 files at r1, 1 of 5 files at r2, 6 of 9 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50422)* status: 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldProcessor.java` line 124 at r4](https://reviewable.io/reviews/harness/harness-core/50422#-N_YJvJxBaRpe1i3Ggez:-N_Z2Ka60K569-Tu7lF2:b-ocgt0q) ([raw file](https://github.com/harness/harness-core/blob/2a039947771fc1f2eaf535e3df5c005bf1d44b77/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterDocumentFieldProcessor.java#L124)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We can use isAssignableFrom?
</blockquote></details>

Discussed offline, this is not required. Was thinking of simplifying the if condition but seems like this won't simplify the code.

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger ut3

**Comment by shalini-agr** [comment]
trigger ut3

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50422)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50422)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
