### PR TITLE
feat: [PL-30085]: delegate disconnect alert helper

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Describe your changes
On delegate disconnection we shoot an alert based on alert notification sent by client. Those are currently pull based which means we run a quartz job to check if delegate is disconnected. 
But we have a iterator running which checks if delegate is disconnected which can help us raise an alert directly. Hence registering the observer to check delegate disconnection.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42704)

### CODE REVIEW

**Review by arpit3107 — CHANGES_REQUESTED** [review]
You mentioned about using iterator DelegateDisconnectDetectorIterator, but you are still relying on quartz job for checking alerts. Also with iterators,  make sure to create alerts within acceptable time. There have been support jiras in past asking for a low time gap.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42704#-:-NLyqRQf5WdlNZp-S50E:bba7xoa)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/intfc/DelegateService.java` line 256 at r1](https://reviewable.io/reviews/harness/harness-core/42704#-NLyslSD61HnJuq7R6C3:-NLyslSE-7tSll2vvacf:bjwr4vr) ([raw file](https://github.com/harness/harness-core/blob/e82a53dd1160ca0e17d33b279e440b14bec86df7/400-rest/src/main/java/software/wings/service/intfc/DelegateService.java#L256)):*
> ```Java
>   List<DelegateDTO> listDelegatesHavingTags(String accountId, DelegateTags tags);
> 
>   Delegate getDelegateById(String accountId, String delegateId);
> ```

Use DelegateCache class.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 4460 at r1](https://reviewable.io/reviews/harness/harness-core/42704#-NM-k9L70KA6TiuTzseN:-NM-k9L70KA6TiuTzseO:blucxq4) ([raw file](https://github.com/harness/harness-core/blob/e82a53dd1160ca0e17d33b279e440b14bec86df7/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L4460)):*
> ```Java
>         .get();
>   }
> ```

this already exists i believe or get it from cache

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 4460 at r1](https://reviewable.io/reviews/harness/harness-core/42704#-NM-k9L70KA6TiuTzseN:-NM-l7Tm6S_PUKoI89YV:b-mkl9st) ([raw file](https://github.com/harness/harness-core/blob/e82a53dd1160ca0e17d33b279e440b14bec86df7/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L4460)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

this already exists i believe or get it from cache
</blockquote></details>

delegatesFromGroupCache for delegate group which is in CG as well

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42704)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by abhinav-harness — COMMENTED** [review]
Yes keeping quartz in system for now in case something goes wrong. It can be removed later if we think this one is safe enough. Aim currently is to give alert early.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42704#-:-NM0US851ZVFTus2koQJ:b-oh0wfh)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42704)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 4460 at r1](https://reviewable.io/reviews/harness/harness-core/42704#-NM-k9L70KA6TiuTzseN:-NM1J-931ODM-i0_jYRU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e82a53dd1160ca0e17d33b279e440b14bec86df7/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L4460)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

delegatesFromGroupCache for delegate group which is in CG as well
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/intfc/DelegateService.java` line 256 at r1](https://reviewable.io/reviews/harness/harness-core/42704#-NLyslSD61HnJuq7R6C3:-NM1J-rtAry99IBfBNs9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e82a53dd1160ca0e17d33b279e440b14bec86df7/400-rest/src/main/java/software/wings/service/intfc/DelegateService.java#L256)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

Use DelegateCache class.
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
So relying on both will double alerts?

**Comment by abhinav-harness** [comment]
@jennyjames21 alert fmwk handles alert dedup internally. if you see quartz job are also scheduled and can run anytime but they only alert once for each delegate as alert fmwk internally handles it

**Review by arpit3107 — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42704)* status: :shipit: complete! ✓

**Pull request merged**
