### PR TITLE
[feat]: [PIE-3794]: Pipeline Get Update and Delete for simplified git experience

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33622)

### CODE REVIEW

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33622#-:-N345d3g5NClBfN-U_34:bnfp4nl)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33622)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 415 at r2](https://reviewable.io/reviews/harness/harness-core/33622#-N34MjnDDS-nUhHGUxwS:-N34MjnDDS-nUhHGUxwT:b6wlzuj) ([raw file](https://github.com/harness/harness-core/blob/a71b4cf1de3949fa3e32d87cbedf7d841919620b/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L415)):*
> ```Java
>       } catch (IOException e) {
>         throw new UnexpectedException("Unexpected error when trying to set description");
>       }
> ```

set new yaml into response and not return



_Code quote:_
```Java
      try {
        return YamlUtils.writeYamlString(pipelineYamlField).replace("---\n", "");
      } catch (IOException e) {
        throw new UnexpectedException("Unexpected error when trying to set description");
      }
```
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 494 at r2](https://reviewable.io/reviews/harness/harness-core/33622#-N34Mxny8sMAA3tqRZuA:-N34Mxny8sMAA3tqRZuB:bqz8i7b) ([raw file](https://github.com/harness/harness-core/blob/a71b4cf1de3949fa3e32d87cbedf7d841919620b/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L494)):*
> ```Java
>         pmsPipelineRepository.findAll(criteria, pageRequest, accountId, orgId, projectId, false);
>     for (PipelineEntity pipelineEntity : pipelineEntities) {
>       pmsPipelineRepository.deleteForOldGitSync(pipelineEntity.withDeleted(true));
> ```

check for both old and new flow and inline



_Code quote:_
```Java
pmsPipelineRepository.deleteForOldGitSync
```
___
*[`800-pipeline-service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 188 at r2](https://reviewable.io/reviews/harness/harness-core/33622#-N34P7EF2K28u4GOB8Pm:-N34P7EF2K28u4GOB8Pn:bhvpih9) ([raw file](https://github.com/harness/harness-core/blob/a71b4cf1de3949fa3e32d87cbedf7d841919620b/800-pipeline-service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L188)):*
> ```Java
>   @Override
>   public Optional<PipelineEntity> findForOldGitSync(String accountId, String orgIdentifier, String projectIdentifier,
>       String pipelineIdentifier, boolean notDeleted, boolean getMetadataOnly) {
> ```

 can be removed getMetadataOnly flag



_Code quote:_
```Java
, boolean getMetadataOnly
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33622)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 415 at r2](https://reviewable.io/reviews/harness/harness-core/33622#-N34MjnDDS-nUhHGUxwS:-N34SvkqBHf8LafcYZLe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a71b4cf1de3949fa3e32d87cbedf7d841919620b/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L415)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

set new yaml into response and not return
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 494 at r2](https://reviewable.io/reviews/harness/harness-core/33622#-N34Mxny8sMAA3tqRZuA:-N34SxpJ1EHNScrHyHv_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a71b4cf1de3949fa3e32d87cbedf7d841919620b/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L494)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

check for both old and new flow and inline
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 188 at r2](https://reviewable.io/reviews/harness/harness-core/33622#-N34P7EF2K28u4GOB8Pm:-N34SzBM6ZUnCGz5rQUP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a71b4cf1de3949fa3e32d87cbedf7d841919620b/800-pipeline-service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L188)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

 can be removed getMetadataOnly flag
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33622)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33622)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33622#-:-N34XqMs5LmsgWdS3WWF:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
