### PR TITLE
[feat]: [CDS-51650]: moving around

### PR DESCRIPTION
**Pull request by RajBaviskar**
## Describe your changes
* Fix base url resolution
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42901)

### CODE REVIEW

**Comment by RajBaviskar** [comment]
trigger ti0

**Comment by RajBaviskar** [comment]
trigger ti1

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42901)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 888 at r1](https://reviewable.io/reviews/harness/harness-core/42901#-NMlY0KM0-2NDzTseoVO:-NMlY0KM0-2NDzTseoVP:b-j28j8r) ([raw file](https://github.com/harness/harness-core/blob/720aebe82741316aa4f9117cd12bc36b196d170d/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L888)):*
> ```Java
> 
>     injector.getInstance(Key.get(ScheduledExecutorService.class, Names.named("taskPollExecutor")))
>         .scheduleWithFixedDelay(injector.getInstance(ModuleVersionsMaintenanceTask.class), 0, 1, TimeUnit.MINUTES);
> ```

too aggressive

**Review by RajBaviskar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42901)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 888 at r1](https://reviewable.io/reviews/harness/harness-core/42901#-NMlY0KM0-2NDzTseoVO:-NMpHm3I0L_YBnYIpl9E:b-5dfjer) ([raw file](https://github.com/harness/harness-core/blob/720aebe82741316aa4f9117cd12bc36b196d170d/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L888)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

too aggressive
</blockquote></details>

removed.

**Review by sribalij — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42901)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42901)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/42901#-NMpfzmpAwC6_kz3L_VX:-NMpfzmpAwC6_kz3L_VY:bya4qzu) ([raw file](https://github.com/harness/harness-core/blob/7b6b242bad75f4f8fab985f92120c7218931c989/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L82)):*
> ```Java
>         String currentVersion = "";
>         try {
>           String BaseUrl = nextGenConfiguration.getNgManagerClientConfig().getBaseUrl() + "version";
> ```

add check for slash



_Code quote:_
```Java
"version";
```
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/42901#-NMpg5fd3IrlwC0wC6FT:-NMpg5fd3IrlwC0wC6FU:b-4t5eg2) ([raw file](https://github.com/harness/harness-core/blob/7b6b242bad75f4f8fab985f92120c7218931c989/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L82)):*
> ```Java
>         String currentVersion = "";
>         try {
>           String BaseUrl = nextGenConfiguration.getNgManagerClientConfig().getBaseUrl() + "version";
> ```

variable name sjhould start with small case
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 117 at r3](https://reviewable.io/reviews/harness/harness-core/42901#-NMpgJj2-YGDsCWec-er:-NMpgJj2-YGDsCWec-es:bcpz6wu) ([raw file](https://github.com/harness/harness-core/blob/7b6b242bad75f4f8fab985f92120c7218931c989/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L117)):*
> ```Java
>     String[] dateTimeFormat = dateTime.toString().split(" ");
>     if (dateTimeFormat.length >= 5) {
>       module.setLastModifiedAt(dateTimeFormat[1] + " " + dateTimeFormat[2] + " " + dateTimeFormat[5]);
> ```

check library for formatting



_Code quote:_
```Java
    String[] dateTimeFormat = dateTime.toString().split(" ");
    if (dateTimeFormat.length >= 5) {
      module.setLastModifiedAt(dateTimeFormat[1] + " " + dateTimeFormat[2] + " " + dateTimeFormat[5]);
    }
```

**Review by RajBaviskar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42901)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/42901#-NMpfzmpAwC6_kz3L_VX:-NMpmpBf-betymzX-WoO:b-t9490x) ([raw file](https://github.com/harness/harness-core/blob/7b6b242bad75f4f8fab985f92120c7218931c989/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L82)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

add check for slash
</blockquote></details>

added
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/42901#-NMpg5fd3IrlwC0wC6FT:-NMpmqMB6LhbvjQR6qn9:b-n9tkhd) ([raw file](https://github.com/harness/harness-core/blob/7b6b242bad75f4f8fab985f92120c7218931c989/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L82)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

variable name sjhould start with small case
</blockquote></details>

changed
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 117 at r3](https://reviewable.io/reviews/harness/harness-core/42901#-NMpgJj2-YGDsCWec-er:-NMpmrLYBmHWCzDO8_R_:b-697a4g) ([raw file](https://github.com/harness/harness-core/blob/7b6b242bad75f4f8fab985f92120c7218931c989/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L117)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

check library for formatting
</blockquote></details>

added lib

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42901)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42901)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by sribalij — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42901)* status: :shipit: complete! ✓

**Review by sribalij — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42901)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42901#-:-NMpw-923e75wEKulpCX:bnfp4nl)* status: :shipit: complete! ✓

**Comment by RajBaviskar** [comment]
trigger ti2

**Comment by RajBaviskar** [comment]
trigger tin0

**Pull request merged**
