### PR TITLE
feat: [PL-29019]: Added log sanitisation to mask JWT

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
Added regex-based log sanitisation for JWT
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39829)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39829)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/LogSanitizer.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/39829#-NGQgUeu2cy9ktLErwhP:-NGQgUeu2cy9ktLErwhQ:bog6hgs) ([raw file](https://github.com/harness/harness-core/blob/79afac024f9fe97d30798f94e172679dfbcce4ce/930-delegate-tasks/src/main/java/software/wings/delegatetasks/LogSanitizer.java#L30)):*
> ```Java
> public abstract class LogSanitizer {
>   public static Set<String> calculateSecretLines(Set<String> secrets) {
>     if (secrets == null || secrets.isEmpty()) {
> ```

Can be replaced by isEmpty(secrets)
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/LogSanitizer.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/39829#-NGQf27AB6T6x2znlD3z:-NGQf27AB6T6x2znlD4-:b-prjxym) ([raw file](https://github.com/harness/harness-core/blob/79afac024f9fe97d30798f94e172679dfbcce4ce/930-delegate-tasks/src/main/java/software/wings/delegatetasks/LogSanitizer.java#L68)):*
> ```Java
> 
>     // JWT sanitization
>     String jwtRegex = "[\\w-]*\\.[\\w-]*\\.[\\w-]*";
> ```

Define it as a constant in some common constant class.
___
*[`950-log-client/src/main/java/io/harness/logstreaming/LogStreamingSanitizer.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/39829#-NGQfVDfD1WlK17vfnsw:-NGQfVDfD1WlK17vfnsx:brhumzt) ([raw file](https://github.com/harness/harness-core/blob/79afac024f9fe97d30798f94e172679dfbcce4ce/950-log-client/src/main/java/io/harness/logstreaming/LogStreamingSanitizer.java#L22)):*
> ```Java
> public class LogStreamingSanitizer {
>   private final Set<String> secrets;
>   private final String jwtRegex = "[\\w-]*\\.[\\w-]*\\.[\\w-]*";
> ```

Same here.
___
*[`950-log-client/src/test/java/io/harness/logstreaming/LogStreamingSanitizerTest.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/39829#-NGQfgZh-oQTcfjZQVw0:-NGQfgZh-oQTcfjZQVw1:bpgj70h) ([raw file](https://github.com/harness/harness-core/blob/79afac024f9fe97d30798f94e172679dfbcce4ce/950-log-client/src/test/java/io/harness/logstreaming/LogStreamingSanitizerTest.java#L62)):*
> ```Java
>   @Category(UnitTests.class)
>   public void shouldMaskJwt() {
>     String message = "JWT: a1c.x2z.123 \n JWT2: 123.123.123 JWT3: abc.abc.abc";
> ```

Add test where string should not be masked.
e.g. abc.xyz, abc.efg.pqr.xyz

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39829)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/LogSanitizer.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/39829#-NGQf27AB6T6x2znlD3z:-NGQj3eG2LZ7U0dhfcQx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/79afac024f9fe97d30798f94e172679dfbcce4ce/930-delegate-tasks/src/main/java/software/wings/delegatetasks/LogSanitizer.java#L68)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Define it as a constant in some common constant class.
</blockquote></details>

Done.
___
*[`950-log-client/src/main/java/io/harness/logstreaming/LogStreamingSanitizer.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/39829#-NGQfVDfD1WlK17vfnsw:-NGQj4hR401JRXi3vUL5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/79afac024f9fe97d30798f94e172679dfbcce4ce/950-log-client/src/main/java/io/harness/logstreaming/LogStreamingSanitizer.java#L22)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[`950-log-client/src/test/java/io/harness/logstreaming/LogStreamingSanitizerTest.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/39829#-NGQfgZh-oQTcfjZQVw0:-NH9PsIH7HWi6p_S3PrV:b-s1984t) ([raw file](https://github.com/harness/harness-core/blob/79afac024f9fe97d30798f94e172679dfbcce4ce/950-log-client/src/test/java/io/harness/logstreaming/LogStreamingSanitizerTest.java#L62)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Add test where string should not be masked.
e.g. abc.xyz, abc.efg.pqr.xyz
</blockquote></details>

Added these and more cases in UT. However, after the previous discussions on this, we have concluded that [xyz.xyz.xyz.xyz] should be masked as [********.xyz]

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39829)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/NGCommonEntityConstants.java` line 160 at r2](https://reviewable.io/reviews/harness/harness-core/39829#-NHNozP83sP79frIieY_:-NHNozP83sP79frIieYa:byiunrm) ([raw file](https://github.com/harness/harness-core/blob/11758c9492114febfd71c491e1b17be23c8ee648/970-ng-commons/src/main/java/io/harness/NGCommonEntityConstants.java#L160)):*
> ```Java
>   public static final String HARNESS_IMAGE = "harnessImage";
>   public static final String METHOD_NAME = "methodName";
>   public static final String JWT_REGEX = "[\\w-]*\\.[\\w-]*\\.[\\w-]*";
> ```

Move it to NGConstants.

**Comment by tiwaritejas** [comment]
trigger ft2

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39829)* status: 8 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39829)* status: 4 file(s) to review.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39829)* status: :shipit: complete! ✓

**Pull request merged**
