### PR TITLE
feat: [CDS-77357]: set nodeMetadata in dependency v1 plan creators

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** Set the newly added field nodeMetata in the dependency in v1 plan creators. In this field, we can directly add string value without kryoserializing it. 

**Impact:** This change won't impact any existing flows as we are setting a value and not consuming anything from this new field.

**Testing:** Ran Http Step and shell script step locally with v1 yaml.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52020)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 3 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52020)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`310-iacm-manager/app/src/main/java/io/harness/iacm/plan/creator/stage/IACMStagePMSPlanCreatorV1.java` line 364 at r3](https://reviewable.io/reviews/harness/harness-core/52020#-NcgCgEmCU_7hjbEjE3M:-NcgCgEmCU_7hjbEjE3N:b-4jweks) ([raw file](https://github.com/harness/harness-core/blob/52ab278331a37991c0207638e9c3da146755cd87/310-iacm-manager/app/src/main/java/io/harness/iacm/plan/creator/stage/IACMStagePMSPlanCreatorV1.java#L364)):*
> ```Java
>         HarnessValue.newBuilder().setBytesValue(ByteString.copyFrom(kryoSerializer.asBytes(infrastructure))).build());
>     nodeMetadataMap.put("workspaceId", HarnessValue.newBuilder().setStringValue(workspaceId).build());
>     metadataMap.put("codebase", ByteString.copyFrom(kryoSerializer.asBytes(codeBase)));
> ```

shouldnt all metadatMap put be together and same for other map? clear to read
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/stage/V3/IntegrationStagePMSPlanCreatorV3.java` line 235 at r3](https://reviewable.io/reviews/harness/harness-core/52020#-NcgE2XrE2PMCC5Q-v9_:-NcgE2XrE2PMCC5Q-v9a:b6plwth) ([raw file](https://github.com/harness/harness-core/blob/52ab278331a37991c0207638e9c3da146755cd87/332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/stage/V3/IntegrationStagePMSPlanCreatorV3.java#L235)):*
> ```Java
>     Map<String, HarnessValue> nodeMetadataMap = new HashMap<>();
>     Map<String, ByteString> metadataMap = new HashMap<>();
>     metadataMap.put("stageNode", ByteString.copyFrom(kryoSerializer.asBytes(stageNode)));
> ```

why we are doing 2 times kryo serialise for same object? we can create and add to both metadataMap and nodeMetadataMap and same at all other places



_Code quote:_
```Java
ByteString.copyFrom(kryoSerializer.asBytes(stageNode)
```
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/steps/CIStepsPlanCreator.java` line 103 at r3](https://reviewable.io/reviews/harness/harness-core/52020#-NcgEGYJ0GzHvd2zaQEW:-NcgEGYJ0GzHvd2zaQEX:bj3xuia) ([raw file](https://github.com/harness/harness-core/blob/52ab278331a37991c0207638e9c3da146755cd87/332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/steps/CIStepsPlanCreator.java#L103)):*
> ```Java
>                               .putAllMetadata(ctx.getDependency().getMetadataMap())
>                               .putMetadata(
>                                   "nextId", ByteString.copyFrom(kryoSerializer.asBytes(steps.get(i + 1).getUuid())))
> ```

Check to add to some planCreator constants or YamlFieldNameConstants, here also you can optimise steps.get(i + 1).getUuid() to one variable and use in both metadataMap and node one
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtilsV1.java` line 101 at r3](https://reviewable.io/reviews/harness/harness-core/52020#-NcgBWXG67hzE22t7qul:-NcgBWXG67hzE22t7qum:b-n4zyyc) ([raw file](https://github.com/harness/harness-core/blob/52ab278331a37991c0207638e9c3da146755cd87/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtilsV1.java#L101)):*
> ```Java
>   }
> 
>   public DependencyMetadata addStrategyFieldDependencyIfPresent(KryoSerializer kryoSerializer, PlanCreationContext ctx,
> ```

can we rename to make it get?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtilsV1.java` line 107 at r3](https://reviewable.io/reviews/harness/harness-core/52020#-NcgBZ3KCWAi5amgatg8:-NcgBZ3KCWAi5amgatg9:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/52ab278331a37991c0207638e9c3da146755cd87/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtilsV1.java#L107)):*
> ```Java
>   }
> 
>   public DependencyMetadata addStrategyFieldDependencyIfPresent(KryoSerializer kryoSerializer, PlanCreationContext ctx,
> ```

same as above
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtilsV1.java` line 127 at r3](https://reviewable.io/reviews/harness/harness-core/52020#-NcgBf2c1s8737_0E26x:-NcgBf2c1s8737_0E26y:bo3mts7) ([raw file](https://github.com/harness/harness-core/blob/52ab278331a37991c0207638e9c3da146755cd87/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtilsV1.java#L127)):*
> ```Java
>                   .shouldProceedIfFailed(shouldProceedIfFailed)
>                   .build())));
>       nodeMetadataMap.put(StrategyConstants.STRATEGY_METADATA + strategyField.getNode().getUuid(),
> ```

add comments at all places that its same as metadataMap but new impl

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52020)* status: 23 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`310-iacm-manager/app/src/main/java/io/harness/iacm/plan/creator/stage/IACMStagePMSPlanCreatorV1.java` line 364 at r3](https://reviewable.io/reviews/harness/harness-core/52020#-NcgCgEmCU_7hjbEjE3M:-NcgJhCQ1rp3KxMlf3hN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/52ab278331a37991c0207638e9c3da146755cd87/310-iacm-manager/app/src/main/java/io/harness/iacm/plan/creator/stage/IACMStagePMSPlanCreatorV1.java#L364)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

shouldnt all metadatMap put be together and same for other map? clear to read
</blockquote></details>

Done.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/stage/V3/IntegrationStagePMSPlanCreatorV3.java` line 235 at r3](https://reviewable.io/reviews/harness/harness-core/52020#-NcgE2XrE2PMCC5Q-v9_:-NcgJdpoDnBi3DMyhw9Y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/52ab278331a37991c0207638e9c3da146755cd87/332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/stage/V3/IntegrationStagePMSPlanCreatorV3.java#L235)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are doing 2 times kryo serialise for same object? we can create and add to both metadataMap and nodeMetadataMap and same at all other places
</blockquote></details>

Done.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/steps/CIStepsPlanCreator.java` line 103 at r3](https://reviewable.io/reviews/harness/harness-core/52020#-NcgEGYJ0GzHvd2zaQEW:-NcgN_Kq9cvV1cTTV8jB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/52ab278331a37991c0207638e9c3da146755cd87/332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/steps/CIStepsPlanCreator.java#L103)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Check to add to some planCreator constants or YamlFieldNameConstants, here also you can optimise steps.get(i + 1).getUuid() to one variable and use in both metadataMap and node one
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtilsV1.java` line 101 at r3](https://reviewable.io/reviews/harness/harness-core/52020#-NcgBWXG67hzE22t7qul:-NcgIvdTClH0HxVpMNUX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/52ab278331a37991c0207638e9c3da146755cd87/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtilsV1.java#L101)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we rename to make it get?
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtilsV1.java` line 107 at r3](https://reviewable.io/reviews/harness/harness-core/52020#-NcgBZ3KCWAi5amgatg8:-NcgIw5R4LAmrRrtyLwr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/52ab278331a37991c0207638e9c3da146755cd87/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtilsV1.java#L107)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtilsV1.java` line 127 at r3](https://reviewable.io/reviews/harness/harness-core/52020#-NcgBf2c1s8737_0E26x:-NcgOsuJ4ouJ-iczAzrG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/52ab278331a37991c0207638e9c3da146755cd87/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtilsV1.java#L127)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comments at all places that its same as metadataMap but new impl
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 19 of 22 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52020)* status: 23 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52020)* status: 23 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — APPROVED** [review]
> Reviewed 19 of 22 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52020)* status: :shipit: complete! ✓

**Review by smjt-h — APPROVED** [review]
> Reviewed 19 of 22 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52020)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]

**Review by raghavharness — APPROVED** [review]

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
