### PR TITLE
[feat]: [CDS-79701]: Filter events based on filepath and repo for a given entity

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Filter events based on filepath and repo for a given entity when the bi directional sync is enabled. Have tested this out locally, working as expected.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53430)

### CODE REVIEW

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53430)* status: 9 file(s) to review. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/53430#-NfLsS0R-GP0uXQb3v-u:-NfLsS0R-GP0uXQb3v-v:b-idw3gx) ([raw file](https://github.com/harness/harness-core/blob/0875100b4ac6a749c8939eb8f02b40f4db10eddd/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L69)):*
> ```Java
>   String branch;
>   Author author;
>   List<String> modifiedFilePaths;
> ```

lets call it "processedFilePaths" ?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53430)* status: 9 file(s) to review. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/53430#-NfLsS0R-GP0uXQb3v-u:-NfP6pGe4ezduMJFUdAm:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/0875100b4ac6a749c8939eb8f02b40f4db10eddd/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L69)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets call it "processedFilePaths" ?
</blockquote></details>

done

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53430)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/GitXEventUpdateRequestDTO.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/53430#-NfPST_I2bRkNY5v0oSj:-NfPST_I2bRkNY5v0oSk:boy1rlx) ([raw file](https://github.com/harness/harness-core/blob/4adfe702e557ef95c703efdc4a3cfd8fa79050e2/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/GitXEventUpdateRequestDTO.java#L33)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public class GitXEventUpdateRequestDTO {
>   List<String> modifiedFilePaths;
> ```

same here : processedFilePaths

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53430)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/53430#-NfPUHzR5qhf1vpZny_6:-NfPUHzR5qhf1vpZny_7:b2nil1s) ([raw file](https://github.com/harness/harness-core/blob/4adfe702e557ef95c703efdc4a3cfd8fa79050e2/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java#L86)):*
> ```Java
>         getScmConnector(gitXWebhook.getAccountIdentifier(), gitXWebhook.getConnectorRef(), gitXWebhook.getRepoName());
>     List<String> modifiedFilePaths = parsePayloadAndGetModifiedFilePaths(gitXWebhook, gitXWebhookEvent, scmConnector);
>     List<String> matchingFilePaths = getMatchingFilePaths(modifiedFilePaths, gitXWebhook);
> ```

we should be storing matchingFilePaths instead of modifiedFilePaths in the DB

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53430)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/GitXEventUpdateRequestDTO.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/53430#-NfPST_I2bRkNY5v0oSj:-NfPdWj6D11bg3zyPsGY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4adfe702e557ef95c703efdc4a3cfd8fa79050e2/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/GitXEventUpdateRequestDTO.java#L33)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same here : processedFilePaths
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/53430#-NfPUHzR5qhf1vpZny_6:-NfPdnX-DHZwiLZw9j_2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4adfe702e557ef95c703efdc4a3cfd8fa79050e2/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java#L86)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should be storing matchingFilePaths instead of modifiedFilePaths in the DB
</blockquote></details>

Done.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53430)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/53430#-NfUaFUj7FCoW0iiFiMn:-NfUaFUj7FCoW0iiFiMo:b-kb3qa0) ([raw file](https://github.com/harness/harness-core/blob/af6f8ccdd3eb51757a0c0abdeeec1c1628797a25/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L98)):*
> ```Java
>           return listEventsForGivenRepoAndFilePath(gitXEventsListRequestDTO);
>         }
>         Criteria criteria = buildEventsListCriteria(gitXEventsListRequestDTO);
> ```

criteria should be the final criteria required here, no further enhancement should be done in consequent methods

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53430)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 112 at r3](https://reviewable.io/reviews/harness/harness-core/53430#-NfUc-IFBTeDTldxYYj1:-NfUc-IG2F1jhdimJBB8:b-7t6ywl) ([raw file](https://github.com/harness/harness-core/blob/af6f8ccdd3eb51757a0c0abdeeec1c1628797a25/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L112)):*
> ```Java
>   }
> 
>   private GitXEventsListResponseDTO listEventsForGivenRepoAndFilePath(
> ```

no need of separate method for givenFilePathAndRepo, this logic should be integrated in original flow itself directly

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53430)* status: 11 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/53430#-NfUaFUj7FCoW0iiFiMn:-NfUgLeQ56WSi0YC-gHL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af6f8ccdd3eb51757a0c0abdeeec1c1628797a25/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L98)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

criteria should be the final criteria required here, no further enhancement should be done in consequent methods
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 112 at r3](https://reviewable.io/reviews/harness/harness-core/53430#-NfUc-IFBTeDTldxYYj1:-NfUgGoV15KDsvHSJvsq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af6f8ccdd3eb51757a0c0abdeeec1c1628797a25/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L112)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

no need of separate method for givenFilePathAndRepo, this logic should be integrated in original flow itself directly
</blockquote></details>

Done.

**Comment by adivishy1** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53430)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger uts

**Review by utkarshchoubey-harness — APPROVED** [review]

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 5 of 9 files at r1, 1 of 2 files at r2, 4 of 5 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53430)* status: 11 file(s) to review.

**Comment by adivishy1** [comment]
trigger uts

**Review by utkarshchoubey-harness — APPROVED** [review]

**Review by mohitg0795 — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger uts

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
