### PR TITLE
[fix]: [PIE-4660]: Fix NPE. Adding stageSchema one only when its namespace is present in shcmea

### PR DESCRIPTION
**Pull request by brijeshdhakar**
…present in shcmea

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35891)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35891)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/PmsYamlSchemaHelper.java` line 248 at r1](https://reviewable.io/reviews/harness/harness-core/35891#-N8Nosy3BCowYy0IWFeP:-N8Nosy3BCowYy0IWFeQ:bw08j63) ([raw file](https://github.com/harness/harness-core/blob/af5f606796ae91f3ba36e41910a86a64ea322287/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/PmsYamlSchemaHelper.java#L248)):*
> ```Java
>               .filter(o
>                   -> EmptyPredicate.isEmpty(o.getYamlSchemaMetadata().getNamespace())
>                       || pipelineDefinitions.get(o.getYamlSchemaMetadata().getNamespace()) != null)
> ```

is this condition correct?



_Code quote:_
```Java
              .filter(o
                  -> EmptyPredicate.isEmpty(o.getYamlSchemaMetadata().getNamespace())
                      || pipelineDefinitions.get(o.getYamlSchemaMetadata().getNamespace()) != null)
```

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/PmsYamlSchemaHelper.java` line 248 at r1](https://reviewable.io/reviews/harness/harness-core/35891#-N8Nosy3BCowYy0IWFeP:-N8NpSll7xeTLiFgDW_q:b-yaz7yu) ([raw file](https://github.com/harness/harness-core/blob/af5f606796ae91f3ba36e41910a86a64ea322287/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/PmsYamlSchemaHelper.java#L248)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

is this condition correct?
</blockquote></details>

Yes archit, Here we are filtering the schemaDetails. We will include the stage schema in stageElementWrapperCOnfig oneOf only if its namespace is present in pipeline definitions. And Empty check is for pipeline service's namespace/definitions.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35891)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35891)* status: :shipit: complete! ✓

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/PmsYamlSchemaHelper.java` line 248 at r1](https://reviewable.io/reviews/harness/harness-core/35891#-N8Nosy3BCowYy0IWFeP:-N8NqNNa-dSMF6gv0KLD:b-gem18g) ([raw file](https://github.com/harness/harness-core/blob/af5f606796ae91f3ba36e41910a86a64ea322287/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/PmsYamlSchemaHelper.java#L248)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Yes archit, Here we are filtering the schemaDetails. We will include the stage schema in stageElementWrapperCOnfig oneOf only if its namespace is present in pipeline definitions. And Empty check is for pipeline service's namespace/definitions.
</blockquote></details>

Please add a comment for the same may be in develop

**Pull request merged**
