### PR TITLE
fix: [DEL-4605]: Fix in watcher version check

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Describe your changes
Watcher while fetching version from manager, doesn't separate out the major version. Hence end up in mismatch of version even though same. Which result in watcher in crash loop of upgrading same vesion

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36133)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36133)

**Review by mdmilic — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36133)* status: :shipit: complete! ✓

___
*[`build.properties` line 3 at r1](https://reviewable.io/reviews/harness/harness-core/36133#-N8wz_ld4AUa44ZulkuC:-N8wz_ld4AUa44ZulkuD:b-kiakut) ([raw file](https://github.com/harness/harness-core/blob/981e199a4874df006f615f3a7fcc99bcab8b59e5/build.properties#L3)):*
> ```INI
> build.majorVersion=1
> build.minorVersion=0
> build.number=76127
> ```

You skipped a version number, not sure if important.

**Review by Vbhatia20 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36133)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36133)* status: :shipit: complete! ✓

___
*[`build.properties` line 3 at r1](https://reviewable.io/reviews/harness/harness-core/36133#-N8wz_ld4AUa44ZulkuC:-N90JTK962syEaFoeblV:b-alpo85) ([raw file](https://github.com/harness/harness-core/blob/981e199a4874df006f615f3a7fcc99bcab8b59e5/build.properties#L3)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You skipped a version number, not sure if important.
</blockquote></details>

I had another patch coming before this, but nvm updated it correctly

**Pull request merged**
