### PR TITLE
feat: [PIE-9240]: Add support for OAuth in Bitbucket

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

Add support for OAuth in Bitbucket.

Testing: Tested locally that I'm able to add bitbucket OAuth SCM in user profile and same is being used in git commits.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46680)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger ut1, ut2, ut6

**Comment by shalini-agr** [comment]
trigger ut0, ut6, ut9, ut2, ut3, ut4

**Comment by mohitg0795** [comment]
*[`product/ci/scm/proto/scm_service.proto` line 260 at r5](https://reviewable.io/reviews/harness/harness-core/46680#-NTw_JEH0LPTUsMUdllI:-NTw_JEH0LPTUsMUdllJ:b82qw77) ([raw file](https://github.com/harness/harness-core/blob/207c7f42648d840bbfd70d1e8ae1a10e5c85efed/product/ci/scm/proto/scm_service.proto#L260)):*
> ```protobuf
>   string app_password = 2;
>   string oauth_token = 3;
>   bool use_oauth = 4;
> ```

lets use some kind of enum here. use_oauth is a hard binding for oauth. What if new mechanism comes up?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46680)* status: 36 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`product/ci/scm/proto/scm_service.proto` line 260 at r5](https://reviewable.io/reviews/harness/harness-core/46680#-NTw_JEH0LPTUsMUdllI:-NTwoWxc9ZWUv4y61teq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/207c7f42648d840bbfd70d1e8ae1a10e5c85efed/product/ci/scm/proto/scm_service.proto#L260)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets use some kind of enum here. use_oauth is a hard binding for oauth. What if new mechanism comes up?
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 8 of 19 files at r1, 13 of 24 files at r2, 3 of 4 files at r3, 7 of 8 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46680)* status: 36 file(s) to review. 1 of 2 approvals obtained.

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 8 of 19 files at r1, 13 of 24 files at r2, 3 of 4 files at r3, 7 of 8 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46680)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Comment by shalini-agr** [comment]
trigger ut9

**Comment by shalini-agr** [comment]
trigger ut2

**Comment by shalini-agr** [comment]
trigger ut2, ut9

**Pull request merged**
