### PR TITLE
[fix]: [PL-22205]: The git sync setting api should throw the correct error when a setting already exists

### PR DESCRIPTION
**Pull request by DeepakPatankar**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30877)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30877)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncSettingsServiceImpl.java, line 55 at r1](https://reviewable.io/reviews/harness/harness-core/30877#-MwQIBGHCT6v6sB1Yxx6:-MwQIBGHCT6v6sB1Yxx7:b-igwo3s) ([raw file](https://github.com/harness/harness-core/blob/95d376360a00f3832b8bc23d87e731a2b8c6e3c9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncSettingsServiceImpl.java#L55)):*
> ```Java
>     } catch (DuplicateKeyException ex) {
>       throw new io.harness.exception.InvalidRequestException(
>           "A git sync settings already exists in the project " + request.getProjectIdentifier());
> ```

Should we add accountid, orgid as well in the error message? Scope would be incomplete without them I suppose.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitSyncSettingsMapper.java, line 26 at r1](https://reviewable.io/reviews/harness/harness-core/30877#-MwQHu2lBYRCz9Vz1ISJ:-MwQHu2m4m13_BGU_336:b-9ghch) ([raw file](https://github.com/harness/harness-core/blob/95d376360a00f3832b8bc23d87e731a2b8c6e3c9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitSyncSettingsMapper.java#L26)):*
> ```Java
>   public GitSyncSettingsDTO getDTOFromGitSyncSettings(GitSyncSettings gitSyncSettings) {
>     if (gitSyncSettings == null) {
>       return null;
> ```

Instead of returning null, we should simply throw exception if null is not expected. Returning null has higher chances to further mess up the system.

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30877)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncSettingsServiceImpl.java, line 55 at r1](https://reviewable.io/reviews/harness/harness-core/30877#-MwQIBGHCT6v6sB1Yxx6:-MwQKcNF9FNKzsN11TRU:b-knokmt) ([raw file](https://github.com/harness/harness-core/blob/95d376360a00f3832b8bc23d87e731a2b8c6e3c9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncSettingsServiceImpl.java#L55)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Should we add accountid, orgid as well in the error message? Scope would be incomplete without them I suppose.
</blockquote></details>

agreed, atleast org should be added.

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30877)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncSettingsServiceImpl.java, line 55 at r1](https://reviewable.io/reviews/harness/harness-core/30877#-MwQIBGHCT6v6sB1Yxx6:-MwQa8fo5k38S2ZBvxqt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/95d376360a00f3832b8bc23d87e731a2b8c6e3c9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncSettingsServiceImpl.java#L55)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

agreed, atleast org should be added. 
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitSyncSettingsMapper.java, line 26 at r1](https://reviewable.io/reviews/harness/harness-core/30877#-MwQHu2lBYRCz9Vz1ISJ:-MwQa9dH8md77EFnTuJf:bwmquo4) ([raw file](https://github.com/harness/harness-core/blob/95d376360a00f3832b8bc23d87e731a2b8c6e3c9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitSyncSettingsMapper.java#L26)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Instead of returning null, we should simply throw exception if null is not expected. Returning null has higher chances to further mess up the system.
</blockquote></details>

I think the null values suites here more than throwing an exception. If the gitSyncSettings is null, then the mapper will try to convert it into the DTO which should also be null.

**Comment by DeepakPatankar** [comment]
trigger messagecheck

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30877#-:-Mw_I_Xg-NVGLmwGCmA4:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30877)* status: :shipit: complete! ✓

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30877)* status: :shipit: complete! ✓

**Pull request merged**
