### PR TITLE
fix: [DEL-5939]: ECS delegate, Mark disconnected flag as false when HB updates

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
For ECS flow unset or mark the 'disconnected' field in the delegate as false

Test Performed
- Local testing

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43662)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger messagecheck

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43662)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. Waiting on team(s): del-team. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/beans/Delegate.java` line 194 at r1](https://reviewable.io/reviews/harness/harness-core/43662#-NNjtpkv3Q8Ke0JT8GyG:-NNjtpkv3Q8Ke0JT8GyH:b-2ay0de) ([raw file](https://github.com/harness/harness-core/blob/412a88e5f61ffc5778ea2c434a6d8a22d567634a/420-delegate-service/src/main/java/io/harness/delegate/beans/Delegate.java#L194)):*
> ```Java
>         .polllingModeEnabled(delegateParams.isPollingModeEnabled())
>         .ng(delegateParams.isNg())
>         .disconnected(false)
> ```

Is this need to be done only for ECS delegate or for all ?



_Code quote:_
```Java
false)
```

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/delegate/beans/Delegate.java` line 194 at r1](https://reviewable.io/reviews/harness/harness-core/43662#-NNjtpkv3Q8Ke0JT8GyG:-NNju2kh0fgKCp0G1aZN:bwr6bsg) ([raw file](https://github.com/harness/harness-core/blob/412a88e5f61ffc5778ea2c434a6d8a22d567634a/420-delegate-service/src/main/java/io/harness/delegate/beans/Delegate.java#L194)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Is this need to be done only for ECS delegate or for all ?
</blockquote></details>

we already rest of the flow to DelegateHeartBeatDoa. So this currently used only for ECS

**Review by gaurav-jain1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43662)* status: 2 file(s) to review.

**Pull request merged**
