### PR TITLE
fix: [CDS-81901]: Fix generate hash method if using oc resources

### PR DESCRIPTION
**Pull request by abosii-harness**
## Describe your changes
Customer is using Route resource from the openshift, based on our logic when customer is using this kind of resource we will automatically switch to openshift cli. Using openshift cli make their manifest to work properly. Adding the same logic for create during hash generation.

**Non-related changes:**
- [x] Added a new method that wraps static method for better mocking
- [x] Integrate the create command with kubectl version framework instead of the hard coded one to support openshift client 

### Test case
Used this manifest:
```kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: openshift-route-test
  labels:
    app.kubernetes.io/name: openshift-route-test
  annotations:
    haproxy.router.openshift.io/balance: 'roundrobin'
    haproxy.router.openshift.io/disable_cookies: 'true'
spec:
  host: openshift.route.test
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: openshift-route-test
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: openshift-route-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openshift-route-test
    subresource: scale
  maxReplicas: 1
  minReplicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-route-test
  labels:
    app.kubernetes.io/name: openshift-route-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: openshift-route-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openshift-route-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: openshift-route-test
spec:
  selector:
    app.kubernetes.io/name: openshift-route-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
```
**Before fix:**
Screenshot 2023-10-17 at 17 29 15

**After fix:**
Screenshot 2023-10-17 at 18 25 54

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54264)

### CODE REVIEW

**Comment by abosii-harness** [comment]
trigger uts

**Review by GoelPratyush99 — APPROVED** [review]

**Review by abhinavsingh1196 — APPROVED** [review]

**Review by alebuh — APPROVED** [review]

**Comment by abosii-harness** [comment]
trigger messagecheck, review

**Comment by abosii-harness** [comment]
trigger messagecheck

**Comment by abosii-harness** [comment]
trigger messagecheck

**Pull request merged**
