### PR TITLE
fix: [PL-28759]: refactord filters to use single and operator

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
Refactored the filters service to use a single $and operator. The following error message was showing prior to the changes in the PR-
_Due to limitations of the com.mongodb.BasicDBObject, you can't add a second '$and' expression specified._
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39579)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39579)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/39579#-NGLbcoh7PtB7o5ZyTNl:-NGLbcoh7PtB7o5ZyTNm:bx9c677) ([raw file](https://github.com/harness/harness-core/blob/2c02ac93983cf3daf29fd9dd4bc901a14f11d874/440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java#L70)):*
> ```Java
>   public static final String CREDENTIAL_TYPE_KEY = "credentialType";
>   public static final String INHERIT_FROM_DELEGATE_STRING = "INHERIT_FROM_DELEGATE";
>   private final List<Criteria> criteriaListToAnd = new ArrayList<>();
> ```

Should not be a class variable.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39579)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/39579#-NGLbcoh7PtB7o5ZyTNl:-NGPzA_77r8XFvoJD5gd:bnn1lw8) ([raw file](https://github.com/harness/harness-core/blob/2c02ac93983cf3daf29fd9dd4bc901a14f11d874/440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java#L70)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should not be a class variable.
</blockquote></details>

Refactored the code.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39579)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39579)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/39579#-NGQig_g3YvpCusMw2B8:-NGQig_g3YvpCusMw2B9:be0yerx) ([raw file](https://github.com/harness/harness-core/blob/ceba17b29610efbd13d62bb8e244602bb3d3f887/440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java#L72)):*
> ```Java
> 
>   @Override
>   public Criteria createCriteriaFromConnectorListQueryParams(String accountIdentifier, String orgIdentifier,
> ```

UT for the change?

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39579)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/39579#-NGQig_g3YvpCusMw2B8:-NGRCi5d316gxwe9LUjx:b-tivjom) ([raw file](https://github.com/harness/harness-core/blob/ceba17b29610efbd13d62bb8e244602bb3d3f887/440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java#L72)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

UT for the change?
</blockquote></details>

There is not functionality change here. The test cases for list present in ConnectorListWithFiltersTest.java should cover this change too.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39579)* status: :shipit: complete! ✓

**Pull request merged**
