### PR TITLE
[fix]: [PL-32740] : Delegate Selectors support in LDAP

### PR DESCRIPTION
**Pull request by shashank-harness**
## Describe your changes
On analysing CFD - https://harness.atlassian.net/browse/PL-32740, we found that Ldap sync is failing for CITI because few delegate tasks go to one delegate which can query their LDAP servers correctly and few go to the ones, which eventually time out.
With this HF we want to implement two things:
- If 1 out of n groups throw exception, consume it and move forward without breaking whole LDAP sync. 
- Implement Delegate selectors for LDAP. We will use this to debug CITI's case by asking them to configure LDAP ONLY with relevant delegate.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50041)

### CODE REVIEW

**Comment by shashank-harness** [comment]
trigger uts

**Comment by shashank-harness** [comment]
trigger uts

**Comment by shashank-harness** [comment]
trigger uts

**Comment by shashank-harness** [comment]
trigger uts

**Review by bhavya181 — APPROVED** [review]

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 125 at r4](https://reviewable.io/reviews/harness/harness-core/50041#-NZQl1s877jkSSWAj8kz:-NZQl1s877jkSSWAj8l-:b2swlmc) ([raw file](https://github.com/harness/harness-core/blob/d0c4255d0e517a221f3f5054c5a32e372a798139/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L125)):*
> ```Java
> 
>     DelegateResponseData delegateResponseData = getDelegateResponseData(accountIdentifier, orgIdentifier,
>         projectIdentifier, parameters, NG_LDAP_TEST_USER_SETTINGS, parameters.getLdapSettings());
> ```

minor: we are already sending `parameters` to the method which contains the ldapSettings, so LdapSettings can be extracted from within the method itself I think



_Code quote:_
```Java
, parameters.getLdapSettings()
```

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 301 at r4](https://reviewable.io/reviews/harness/harness-core/50041#-NZQlJzq8pibr1cS-D1I:-NZQlJzq8pibr1cS-D1J:baf3tt7) ([raw file](https://github.com/harness/harness-core/blob/d0c4255d0e517a221f3f5054c5a32e372a798139/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L301)):*
> ```Java
>           }
>         } catch (Exception e) {
>           log.error("NGLDAP: Sync error for user group {} and accountId {}", userGroup.getName(), accountIdentifier, e);
> ```

minor: can we log org identifier, proj identifier as well, since a group name can be same across scopes, so it might create confusion while debugging, thanks



_Code quote:_
```Java
userGroup.getName()
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/beans/sso/LdapSettings.java` line 167 at r4](https://reviewable.io/reviews/harness/harness-core/50041#-NZQmlQ48KJpTVhp0ino:-NZQmlQ48KJpTVhp0inp:b-m7fso8) ([raw file](https://github.com/harness/harness-core/blob/d0c4255d0e517a221f3f5054c5a32e372a798139/400-rest/src/main/java/software/wings/beans/sso/LdapSettings.java#L167)):*
> ```Java
>                                     .selectors(connectionSettings.getDelegateSelectors())
>                                     .selectorOrigin(TASK_SELECTORS)
>                                     .build());
> ```

executionCapabilities is an immutable list, and we cannot add further to it, please correct by making 'executionCapabilities' non-immutable, thanks



_Code quote:_
```Java
      executionCapabilities.add(SelectorCapability.builder()
                                    .selectors(connectionSettings.getDelegateSelectors())
                                    .selectorOrigin(TASK_SELECTORS)
                                    .build());
```

**Comment by shashank-harness** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 125 at r4](https://reviewable.io/reviews/harness/harness-core/50041#-NZQl1s877jkSSWAj8kz:-NZQqIIo6eWxM5jySxT1:b-77lju1) ([raw file](https://github.com/harness/harness-core/blob/d0c4255d0e517a221f3f5054c5a32e372a798139/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L125)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor: we are already sending `parameters` to the method which contains the ldapSettings, so LdapSettings can be extracted from within the method itself I think
</blockquote></details>

these parameters can be of different types so typecasting is not possible

**Review by nataraja2018 — APPROVED** [review]

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/beans/sso/LdapSettings.java` line 167 at r4](https://reviewable.io/reviews/harness/harness-core/50041#-NZQmlQ48KJpTVhp0ino:-NZQrvsKAwwyIuxNx-u-:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/d0c4255d0e517a221f3f5054c5a32e372a798139/400-rest/src/main/java/software/wings/beans/sso/LdapSettings.java#L167)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

executionCapabilities is an immutable list, and we cannot add further to it, please correct by making 'executionCapabilities' non-immutable, thanks
</blockquote></details>

Done

**Comment by shashank-harness** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 92 at r4](https://reviewable.io/reviews/harness/harness-core/50041#-NZQk7RW1kl2Zha96q3Q:-NZQs2aZ21-_xD_Fospw:biw3nsu) ([raw file](https://github.com/harness/harness-core/blob/d0c4255d0e517a221f3f5054c5a32e372a798139/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L92)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

nit: is 5 minutes not too high since it is for a single group sync? thanks
</blockquote></details>

it is. Its only for CITI debugging.

**Pull request merged**
