### PR TITLE
feat: [CDS-85020]: Propagate metric info map for new metrics

### PR DESCRIPTION
**Pull request by Y0709**
In this pr we are just propagating info for new metrics from consumer to handler and this just contain method signature changes due to propagation of new metric info map

Testing - tested basic flows by running a few pipelines

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55931)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger ut8

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 15 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55931)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractMessageListener.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/55931#-Nk-hhbNAPSXBv8GX1lH:-Nk-hhbNAPSXBv8GX1lI:b-386wvm) ([raw file](https://github.com/harness/harness-core/blob/e57642fbe417bd3a190a73b1d833eb675af97071/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractMessageListener.java#L55)):*
> ```Java
>       T entity = extractEntity(message.getMessage().getData());
>       Map<String, Object> metricInfo = new HashMap<>();
>       metricInfo.put("threadPickTs", System.currentTimeMillis());
> ```

discussed offline to change impl

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55931)* status: 19 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractMessageListener.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/55931#-Nk-hhbNAPSXBv8GX1lH:-NkHXgeS51EfSC9CCvHo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e57642fbe417bd3a190a73b1d833eb675af97071/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractMessageListener.java#L55)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

discussed offline to change impl
</blockquote></details>

Done.

**Comment by Y0709** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java` line 168 at r2](https://reviewable.io/reviews/harness/harness-core/55931#-NkItMHi2wJQWYilWNeR:-NkItMHi2wJQWYilWNeS:b-iorcel) ([raw file](https://github.com/harness/harness-core/blob/7c832da2ea0e4f614a39e83b2973ffd71844cbe0/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java#L168)):*
> ```Java
>           metricInfo.put(PmsEventMonitoringConstants.STREAM_NAME, redisConsumer.getTopicName());
>           metricInfo.put(PmsEventMonitoringConstants.EVENT_PROCESS_START_TS, System.currentTimeMillis());
>           metricInfo.put(PmsEventMonitoringConstants.EVENT_RECEIVE_TS, readTs);
> ```

nit: Can we move this to a separate function?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 19 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55931)* status: 18 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 16 of 18 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55931)* status: 2 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractMessageListener.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/55931#-NkPBiIS0sJzfZGaP3gR:-NkPBiIS0sJzfZGaP3gS:bt9cgfb) ([raw file](https://github.com/harness/harness-core/blob/ec8183ed544f87531ce757866099b6b7788126b5/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractMessageListener.java#L55)):*
> ```Java
>       Long issueTimestamp = ProtoUtils.timestampToUnixMillis(message.getTimestamp());
>       metricInfo.put(PmsEventMonitoringConstants.EVENT_SEND_TS, issueTimestamp);
>       processMessage(entity, message.getMessage().getMetadataMap(), issueTimestamp, metricInfo);
> ```

issueTimestamp is already being sent, so we should remove from there right? and send only metricInfo?

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55931)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractMessageListener.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/55931#-NkPBiIS0sJzfZGaP3gR:-NkQ9dX51A_bNoiOeJ75:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ec8183ed544f87531ce757866099b6b7788126b5/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractMessageListener.java#L55)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

issueTimestamp is already being sent, so we should remove from there right? and send only metricInfo?
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55931)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger mdc

**Comment by Y0709** [comment]
trigger mdc

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55931)* status: :shipit: complete! ✓

**Comment by Y0709** [comment]
trigger review, mdc

**Pull request merged**
