### PR TITLE
feat: [PL-27456]: Added build files for 980-commons with no cycles present

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes

Added granular targets for 980-commons. Could not add BUILD files for each sub-folder as there are a lot of cycles that need to be resolved on case by case basis.

Other than the BUILD files, also had to change:
1) tools/bazel/duplicated.bzl - this was required as we assumed *Test* folder name in the output, which needed a change as we already had a folder with that name
2) NullSafeImmutableMap - change helped to automatically import deps.

====
Hashcheck failed, so answering requested questions:

1) Is it new task type? (If yes, no need to answer 2 then)
No

2) Did you add a new class which is added in kryo serialization
No

3) if yes then do not use that class in any of the delegate task payload till it makes to delegate release
NA

4) Did you make changes to the code in a backward-compatible manner?
NA

5) will the new version of the delegate receive old version task and process?
NA

6) If new version of the manager receives response for the old task will it be able to handle it successfully?
Yes

7) Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager
No

8) If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay
Yes

9) If the newer version of ng service creates the task parameter and calls older cg manager, will it be okay
Yes

10) Did you remove an enum → this is not backward compatible yet (tracked by [DEL-3648: Move to name based kryo serializer for delegate/manager communicationIN PROGRESS](https://harness.atlassian.net/browse/DEL-3648) )
No

11) Did you add an enum → make sure that the enum constant is added in the end of the already defined constants. If you don’t do this then you will have issues where wrong enum type will be deserialized in delegate side.
No

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [X] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36688)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36688)

**Comment by gn-harness** [comment]
trigger ti0, ti1, ti2, ti3, ti4, ft1, ft2

**Comment by gn-harness** [comment]
trigger ti0, ti1, ti2, ti3, ti4, ft1, ft2

**Comment by gn-harness** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Comment by gn-harness** [comment]
trigger ti1, ti4

**Comment by gn-harness** [comment]
trigger feature-build

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36688)* status: 35 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/swagger/BUILD.bazel` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/36688#-NAy-g6V5Yi-1bwRQqXK:-NAy-g6V5Yi-1bwRQqXL:b-ri24b7) ([raw file](https://github.com/harness/harness-core/blob/f805086071a1c8d9f193aacd057ed77a92c0de02/980-commons/src/main/java/io/harness/swagger/BUILD.bazel#L14)):*
> ```Starlark
>         "@maven//:io_swagger_swagger_jaxrs",
>         "@maven//:io_swagger_swagger_models",
>         "@maven//:org_reflections_reflections",
> ```

The types of changes we are making are going to affect the classpath heavily, so any reflection that we are using might get broken (because it might fail to find some classes on the classpath and those are never explicit deps, so will not appear in the dep section). AFAIK we do reflections only through `org_reflections_reflections` or `HarnessReflections` which also lives in 980-commons
Can you please go into the reflection logic of this particular package and see if something would get broken? Do we have proper tests to make sure it doesn't? 
Note that for tests we still use one big fat jar, so classpath would be different to what it is during runtime (which is wrong). Is it hard to break tests into package level targets in parallel (or maybe at least those ones that are dealing with reflection)?

One (unrelated) example of the thing that I encountered recently that will surely get broken is MatricsPublishers 
970-ng-commons/src/main/java/io/harness/metrics/jobs/RecordMetricsJob.java
This finds all the classes of certain type on the classpath and does something with them. However those metrics publishers will never be on any classpath unless we manually add the Dep.

**Review by gn-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36688)* status: 35 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/swagger/BUILD.bazel` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/36688#-NAy-g6V5Yi-1bwRQqXK:-NBPfpLP-9FphNBm2eHk:b3wcl19) ([raw file](https://github.com/harness/harness-core/blob/674b9233de407e33c81fd40dcfb64aa1a071a698/980-commons/src/main/java/io/harness/swagger/BUILD.bazel#L14)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

The types of changes we are making are going to affect the classpath heavily, so any reflection that we are using might get broken (because it might fail to find some classes on the classpath and those are never explicit deps, so will not appear in the dep section). AFAIK we do reflections only through `org_reflections_reflections` or `HarnessReflections` which also lives in 980-commons
Can you please go into the reflection logic of this particular package and see if something would get broken? Do we have proper tests to make sure it doesn't? 
Note that for tests we still use one big fat jar, so classpath would be different to what it is during runtime (which is wrong). Is it hard to break tests into package level targets in parallel (or maybe at least those ones that are dealing with reflection)?

One (unrelated) example of the thing that I encountered recently that will surely get broken is MatricsPublishers 
970-ng-commons/src/main/java/io/harness/metrics/jobs/RecordMetricsJob.java
This finds all the classes of certain type on the classpath and does something with them. However those metrics publishers will never be on any classpath unless we manually add the Dep.
</blockquote></details>

Thanks for the good suggestion and the offline discussion.

I read through the code and its call sites. This looks like a safe change - as the class under consideration is just a utility. It has dependency on reflection because swagger needs some utilities to read metadata about classes. It also does not seem to have auto-magic like RecordMetricsJob.java - we are explicitly passing in Java classes under consideration.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36688)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by mdmilic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36688)* status: :shipit: complete! ✓

**Review by diptiman-adak — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36688)* status: :shipit: complete! ✓

**Pull request merged**
