### PR TITLE
fix: [CDS-67993]: Notifications are not working for matrix stages

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Issue:** Notifications are not working for matrix stages

**Changes:** Currently, we are comparing the stages identifier of node execution with the one mentioned in notification rules. In the case of stages with strategy, their identifier in node execution will have _ and index appended at the end which is why they didn't match with the stage identifier, and a notification couldn't be sent. Now, in this PR, we have changed this by comparing the identifier of the strategy level of the stage which will be the actual identifier, it matches with the stage identifier in notification rules and hence notification gets sent.

**Testing:** Tested locally that notifications are correctly sent for stages with a looping strategy.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47561)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger uts, messagecheck

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47561)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 316 at r3](https://reviewable.io/reviews/harness/harness-core/47561#-NV45dGpEExNnPsvqYu3:-NV45dGqDOx0PhpOm4v5:bdx0sr5) ([raw file](https://github.com/harness/harness-core/blob/68b18f6bc640a3baf473aefe7bc91bd73dc74ee2/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L316)):*
> ```Java
>   }
> 
>   private String getStageIdentifier(NodeExecution nodeExecution) {
> ```

Can you add a unit-test for this?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47561)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 316 at r3](https://reviewable.io/reviews/harness/harness-core/47561#-NV45dGpEExNnPsvqYu3:-NV4RwUVDGAIjaxGdmCA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/68b18f6bc640a3baf473aefe7bc91bd73dc74ee2/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L316)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Can you add a unit-test for this?
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47561)* status: 2 file(s) to review.

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
