### PR TITLE
feat: [PL-25115] Adding traceHeader to access control and platform service

### PR DESCRIPTION
**Pull request by kshitij-harness**
## Describe your changes
Registering TraceFiler which adds Opentelemetry Trace ID to response headers.
Changes tested in PR Env

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38139)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38139)

**Comment by rijajoo** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/AccessControlConfiguration.java` line 118 at r2](https://reviewable.io/reviews/harness/harness-core/38139#-NDBhZZz0PDj8LuFGhRp:-NDBhZZz0PDj8LuFGhRq:b-kuva8s) ([raw file](https://github.com/harness/harness-core/blob/27031f4e2fe14ec94871910d76c4ee695492ea22/access-control/service/src/main/java/io/harness/accesscontrol/AccessControlConfiguration.java#L118)):*
> ```Java
>   @JsonProperty("basePathPrefix") private String basePathPrefix = "";
>   @JsonProperty("segmentConfiguration") private SegmentConfiguration segmentConfiguration;
>   @JsonProperty(value = "enableOpentelemetry") private Boolean enableOpentelemetry;
> ```

Let's keep it primitive boolean so it is not nullable.

**Comment by rijajoo** [comment]
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/ResourceGroupServiceConfig.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/38139#-NDBhmwWEhAW-j4p8wxb:-NDBhmwWEhAW-j4p8wxc:bc0quqm) ([raw file](https://github.com/harness/harness-core/blob/27031f4e2fe14ec94871910d76c4ee695492ea22/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/ResourceGroupServiceConfig.java#L45)):*
> ```Java
>   @JsonProperty("hostname") String hostname;
>   @JsonProperty("basePathPrefix") String basePathPrefix;
>   @JsonProperty(value = "enableOpentelemetry") private Boolean enableOpentelemetry;
> ```

Same here. You can check all the instances.

**Comment by kshitij-harness** [comment]
> _[`access-control/service/src/main/java/io/harness/accesscontrol/AccessControlConfiguration.java` line 118 at r2](https://reviewable.io/reviews/harness/harness-core/38139#-NDBhZZz0PDj8LuFGhRp:-NDBhZZz0PDj8LuFGhRq:b-kuva8s) ([raw file](https://github.com/harness/harness-core/blob/27031f4e2fe14ec94871910d76c4ee695492ea22/access-control/service/src/main/java/io/harness/accesscontrol/AccessControlConfiguration.java#L118)):_
> 
> > ```java
> >   @JsonProperty("basePathPrefix") private String basePathPrefix = "";
> >   @JsonProperty("segmentConfiguration") private SegmentConfiguration segmentConfiguration;
> >   @JsonProperty(value = "enableOpentelemetry") private Boolean enableOpentelemetry;
> > ```
> 
> Let's keep it primitive boolean so it is not nullable.

Since it is optional parameter, I've kept it boxed boolean. Null value would be treated same as false.

**Review by rijajoo — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38139#-:-NDBzP-K8PVa_ncXjwM2:bnfp4nl)* status: 13 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by rijajoo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38139)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38139)* status: :shipit: complete! ✓

**Pull request merged**
