### PR TITLE
fix: [DEL-4328]: add delegate log streaming dispatcher and use it as …

### PR DESCRIPTION
**Pull request by arpit3107**
…singleton.

Aim was to reduce the thread size for logStreamingClient that dispatches execution logs to logStreamingService.
There is a scheduled service which will run every 1 sec and dispatch the logs saved in cache. So, I will be using two caches, one primary cache where threads will be writing cache, and then we will be dispatching logs from secondary cache.
In next iteration we will dispatch from primary cache while threads will be writing in secondary cache. 
this will reduce the locking time for threads.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36769)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 10 Issues 
* Vulnerability 4 Vulnerabilities 
 * Code issue 6 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36769)

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAeQ6z25w7XlwnbRuz8:-NAeQ6z25w7XlwnbRuz9:brpzw6e) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L44)):*
> ```Java
>   private final AtomicBoolean isWritingInPrimaryLogCache = new AtomicBoolean(true);
> 
>   private final Map<String, List<LogLine>> primaryLogCache = new HashMap<>();
> ```

why do we need these two as class variable? why not just create a new and use the reference of the old one drain?

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAeQbL1DEc22xOdYpkW:-NAeQbL25O9zhtisLfqS:bghv6da) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L70)):*
> ```Java
>     @Override
>     protected Scheduler scheduler() {
>       return Scheduler.newFixedRateSchedule(0, 1, TimeUnit.SECONDS);
> ```

do we need every second?

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAeQugMDQqFhvYZ8ub8:-NAeQugMDQqFhvYZ8ub9:be2zfyv) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L112)):*
> ```Java
>   }
> 
>   private boolean dispatchAllLogsFromPrimaryCacheBeforeClosingStream(
> ```

in the previous mechanism, the calling thread was waiting till all the logs are sent, are we doing the same here?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36769)* status: 0 of 1 approvals obtained.

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36769)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java` line 936 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAshZIa7_dlXMNaZXAO:-NAshZIdAOz7VrmMjT91:brcb7f) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L936)):*
> ```Java
>   @Named("logStreamingExecutor")
>   public ThreadPoolExecutor logStreamingExecutor() {
>     return ThreadPool.create(10, 40, 500, TimeUnit.MILLISECONDS,
> ```

Millis is too less for thread idle wait time, keep it 7 or 10 seconds.



_Code quote:_
```Java
TimeUnit.MILLISECONDS,
```
___
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAsizRp-i6ECSC5BdY-:-NAsizRp-i6ECSC5BdY0:bd1j9fm) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L42)):*
> ```Java
>   private final AtomicReference<DelegateLogStreamingDispatcherService> svcHolder = new AtomicReference<>();
> 
>   private final AtomicBoolean isWritingInPrimaryLogCache = new AtomicBoolean(true);
> ```

We don't need this boolean, you can maintain a reference to map, which will be protected by readWriteLock, 
During write, you'll just call the write to this reference, caller doesn't need to take care which map this will going to write.



_Code quote:_
```Java
 private final AtomicBoolean isWritingInPrimaryLogCache = new AtomicBoolean(true);
```
___
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAsjeGxDtA4qj9bsQWr:-NAsjeGxDtA4qj9bsQWs:b-8qq4fj) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L97)):*
> ```Java
>     for (Iterator<Map.Entry<String, List<LogLine>>> iterator = logCache.entrySet().iterator(); iterator.hasNext();) {
>       Map.Entry<String, List<LogLine>> next = iterator.next();
>       // Question? are we able to send logs before removing from iterator
> ```

This is something you need to figure out Arpit. Please do not post such comments, instead figure out yourself



_Code quote:_
```Java
// Question? are we able to send logs before removing from iterator
```
___
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 117 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAskHRf9EwqSDZ-feoc:-NAskHRf9EwqSDZ-feod:bawgoau) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L117)):*
> ```Java
>       return false;
>     }
>     logStreamingExecutor.submit(() -> sendLogsOverHttp(logKey, primaryLogCache.get(logKey)));
> ```

This can result in NPE, consider you are dispatching logs for a particular logkey, and at the same time you switched the map reference and dispatching logs for entire map. Now both these threads can potentially work on same logkey



_Code quote:_
```Java
primaryLogCache.get(logKey))
```
___
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAsk59zEVouIzy33alM:-NAsk59zEVouIzy33alN:birixg8) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L125)):*
> ```Java
>     try {
>       readWriteLock.readLock().lock();
>       if (isWritingInPrimaryLogCache.get()) {
> ```

This code is too complex, instead maintain a reference and write logline to that reference, like I suggested before.



_Code quote:_
```Java
      readWriteLock.readLock().lock();
      if (isWritingInPrimaryLogCache.get()) {
        if (!primaryLogCache.containsKey(logKey)) {
          primaryLogCache.put(logKey, new ArrayList<>());
        }
        primaryLogCache.get(logKey).add(logLine);
      } else {
        if (!secondaryLogCache.containsKey(logKey)) {
          secondaryLogCache.put(logKey, new ArrayList<>());
        }
        secondaryLogCache.get(logKey).add(logLine);
      }
```
___
*[`260-delegate/src/main/java/io/harness/logstreaming/LogStreamingTaskClient.java` line 106 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAsiaPu9Enfpvapgy9D:-NAsiaPu9Enfpvapgy9E:brq7vax) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/LogStreamingTaskClient.java#L106)):*
> ```Java
> 
>   @Override
>   public void dispatchLogs() {
> ```

why we need this method here ? we can dispatch directly from delegateLogStreamingDispatcher



_Code quote:_
```Java
  public void dispatchLogs() {
    delegateLogStreamingDispatcher.swapMapsAndDispatchLogs();












  }
```

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36769)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2158 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAskuoQ0QAGijjaONh6:-NAskuoQ0QAGijjaONh7:b-xhj1pc) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2158)):*
> ```Java
> 
>     if (delegateLogStreamingDispatcher == null) {
>       delegateLogStreamingDispatcher = new DelegateLogStreamingDispatcher(
> ```

why we need to do all this dispatcher business here ?
you can make this dispatcher as singleton which will get initialise by very first object of  LogStreamingTaskClient



_Code quote:_
```Java
    if (delegateLogStreamingDispatcher == null) {
      delegateLogStreamingDispatcher = new DelegateLogStreamingDispatcher(
          delegateTaskPackage.getAccountId(), logStreamingClient, logStreamingExecutor);
    }

    if (!delegateTaskPackage.getLogStreamingToken().equals(logStreamingToken)) {
      logStreamingToken = delegateTaskPackage.getLogStreamingToken();
      delegateLogStreamingDispatcher.setToken(logStreamingToken);
    }

    delegateLogStreamingDispatcher.start();
```

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36769)* status: 4 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java` line 936 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAshZIa7_dlXMNaZXAO:-NBNF0dh5DyJ_YCuHfAM:b-k22q20) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L936)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Millis is too less for thread idle wait time, keep it 7 or 10 seconds.
</blockquote></details>

2 seconds should be good. Since we are keeping less number of threads
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2158 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAskuoQ0QAGijjaONh6:-NBNFAeYA1ocbE21iR2m:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2158)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

why we need to do all this dispatcher business here ?
you can make this dispatcher as singleton which will get initialise by very first object of  LogStreamingTaskClient
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAsizRp-i6ECSC5BdY-:-NBNFFft4bl0i8d8CFj9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L42)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

We don't need this boolean, you can maintain a reference to map, which will be protected by readWriteLock, 
During write, you'll just call the write to this reference, caller doesn't need to take care which map this will going to write.
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAeQ6z25w7XlwnbRuz8:-NBNFH_l-q_cHP7m-Rer:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L44)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need these two as class variable? why not just create a new and use the reference of the old one drain?
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAeQf-HAvHggM5e6gg8:-NBNFKRp3P9f4IsqSLZ4:b-e20tdc) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L59)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we need to find the answer of this? what does this do?
</blockquote></details>

not needed in this case
___
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAeQbL1DEc22xOdYpkW:-NBNFOrL3pNVUUzAEyWG:b-1q2j1l) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L70)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

do we need every second?
</blockquote></details>

2 seconds should be good. It will wake up and checks whether the cache is empty, and then sleep again.
___
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAsjeGxDtA4qj9bsQWr:-NBNFbPq022GQsel8qpQ:b-emxauj) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L97)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

This is something you need to figure out Arpit. Please do not post such comments, instead figure out yourself
</blockquote></details>

This was for me only to figure out in pr env. :) 
___
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAeQugMDQqFhvYZ8ub8:-NBNFk8g9gqKM9VLWFHK:byaewuj) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L112)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

in the previous mechanism, the calling thread was waiting till all the logs are sent, are we doing the same here?
</blockquote></details>

yes, now also calling thread will wait for 100ms if there are some logs to be dispatched.
___
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 117 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAskHRf9EwqSDZ-feoc:-NBNFxcfA6CVbBI-ZiC2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L117)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

This can result in NPE, consider you are dispatching logs for a particular logkey, and at the same time you switched the map reference and dispatching logs for entire map. Now both these threads can potentially work on same logkey
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAsk59zEVouIzy33alM:-NBNFyij2zmVDe_q6uFw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L125)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

This code is too complex, instead maintain a reference and write logline to that reference, like I suggested before.
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/logstreaming/LogStreamingTaskClient.java` line 106 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAsiaPu9Enfpvapgy9D:-NBNG77dACK8-2g_d-49:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/LogStreamingTaskClient.java#L106)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

why we need this method here ? we can dispatch directly from delegateLogStreamingDispatcher
</blockquote></details>

Done.

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java` line 936 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAshZIa7_dlXMNaZXAO:-NBNfICBDaalTnrgpaVL:b-acu10i) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L936)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

2 seconds should be good. Since we are keeping less number of threads
</blockquote></details>

why do we need minimum of 10 threads and max of 40? i think min should be 1 and max should be 5

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 590 at r5](https://reviewable.io/reviews/harness/harness-core/36769#-NBNfWhW0gahI0sDXiiy:-NBNfWhW0gahI0sDXiiz:b65swjx) ([raw file](https://github.com/harness/harness-core/blob/3d8c9c0f425ded665fe5919be1538501ccd7d551/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L590)):*
> ```Java
>       DelegateStackdriverLogAppender.setDelegateId(delegateId);
>       delegateLogStreamingDispatcher.setAccountId(accountId);
>       delegateLogStreamingDispatcher.start();
> ```

you should pass whatever is needed to be set in the start method and not expose setter

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 60 at r5](https://reviewable.io/reviews/harness/harness-core/36769#-NBNfoPq10r7RiLQzrcE:-NBNfoPq10r7RiLQzrcF:bftjgga) ([raw file](https://github.com/harness/harness-core/blob/3d8c9c0f425ded665fe5919be1538501ccd7d551/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L60)):*
> ```Java
> 
>   public void swapMapsAndDispatchLogs() {
>     if (logCache.isEmpty() || token == null) {
> ```

can the token ever be null? if not then thats an error

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 77 at r5](https://reviewable.io/reviews/harness/harness-core/36769#-NBNg35MAMQjlBbVjET3:-NBNg35MAMQjlBbVjET4:b-ycr22g) ([raw file](https://github.com/harness/harness-core/blob/3d8c9c0f425ded665fe5919be1538501ccd7d551/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L77)):*
> ```Java
>     for (Iterator<Map.Entry<String, List<LogLine>>> iterator = logCache.entrySet().iterator(); iterator.hasNext();) {
>       Map.Entry<String, List<LogLine>> next = iterator.next();
>       logStreamingExecutor.submit(() -> sendLogsOverHttp(next.getKey(), next.getValue()));
> ```

you don't need to do iterator and remove operation, this map will anyways be garbage collected once this method is done, just do forEach for the entry set.

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 44 at r5](https://reviewable.io/reviews/harness/harness-core/36769#-NBNgV9DASOph46LP6BX:-NBNgV9DASOph46LP6BY:b-ufplzq) ([raw file](https://github.com/harness/harness-core/blob/3d8c9c0f425ded665fe5919be1538501ccd7d551/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L44)):*
> ```Java
>   private Map<String, List<LogLine>> logCache = new HashMap<>();
>   ReadWriteLock readWriteLockForMap = new ReentrantReadWriteLock();
>   ReadWriteLock readWriteLockForToken = new ReentrantReadWriteLock();
> ```

do we need lock for token?

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAeQugMDQqFhvYZ8ub8:-NBNggmt9YTP-sONX5vq:bpucoju) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L112)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

yes, now also calling thread will wait for 100ms if there are some logs to be dispatched.
</blockquote></details>

i don't see that logic, there has to be a while loop to make sure the logs are dispatched. the sleep has to be in the while loop

**Review by mdmilic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36769)* status: 1 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/logstreaming/LogStreamingTaskClient.java` line 61 at r5](https://reviewable.io/reviews/harness/harness-core/36769#-NBNh0DE-T1XUb9IDeo4:-NBNh0DE-T1XUb9IDeo5:b-9f7cbr) ([raw file](https://github.com/harness/harness-core/blob/e104a895e7e4ef7036bfa5bb9daed5aaba190948/260-delegate/src/main/java/io/harness/logstreaming/LogStreamingTaskClient.java#L61)):*
> ```Java
> public class LogStreamingTaskClient implements ILogStreamingTaskClient {
>   private final DelegateLogService logService;
>   private final LogStreamingClient logStreamingClient;
> ```

You should remove logStreamingClient from the taskClient and instead forward all the call to dispatcher.

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/logstreaming/LogStreamingTaskClient.java` line 104 at r5](https://reviewable.io/reviews/harness/harness-core/36769#-NBNhIfm0VvV2j7hE0W1:-NBNhIfm0VvV2j7hE0W2:bigzi1g) ([raw file](https://github.com/harness/harness-core/blob/3d8c9c0f425ded665fe5919be1538501ccd7d551/260-delegate/src/main/java/io/harness/logstreaming/LogStreamingTaskClient.java#L104)):*
> ```Java
> 
>   @Override
>   public void dispatchLogs() {
> ```

this is not right. there should not be any logic to dispatch logs in the client.

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36769)* status: 1 file(s) to review. 2 change requests. 11. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAeQugMDQqFhvYZ8ub8:-NBNlYmUCKiaJMczOunM:b-790qb0) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L112)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

i don't see that logic, there has to be a while loop to make sure the logs are dispatched. the sleep has to be in the while loop
</blockquote></details>

Why do we need to wait for that? Isn't the point to offload it to a separate thread?

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36769)* status: 1 file(s) to review. 2 change requests. 11. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/36769#-NAeQugMDQqFhvYZ8ub8:-NBNlxsP2qczInhf0_oj:b-svmbjs) ([raw file](https://github.com/harness/harness-core/blob/4c4234606eb235f4dd19a89772783ef942b30ab8/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L112)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Why do we need to wait for that? Isn't the point to offload it to a separate thread?
</blockquote></details>

If we run this every 1s and sleep for 100ms waiting for the call to finish, we will spend 10% of time just sleeping

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36769)* status: 5 file(s) to review. 2 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 590 at r5](https://reviewable.io/reviews/harness/harness-core/36769#-NBNfWhW0gahI0sDXiiy:-NBSuxzJARBYYyuaI5CN:b32v57) ([raw file](https://github.com/harness/harness-core/blob/3d8c9c0f425ded665fe5919be1538501ccd7d551/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L590)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

you should pass whatever is needed to be set in the start method and not expose setter
</blockquote></details>

+1
___
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 80 at r6](https://reviewable.io/reviews/harness/harness-core/36769#-NBSvrTW9beRhuXYk4iQ:-NBSvrTW9beRhuXYk4iR:b-w1xw2j) ([raw file](https://github.com/harness/harness-core/blob/34d7d09a7bddc4e41fdf3cc2c8d04b30f578734f/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L80)):*
> ```Java
>       readWriteLockForMap.readLock().lock();
>       if (!logCache.containsKey(logKey)) {
>         logCache.put(logKey, new ArrayList<>());
> ```

Can 2 different threads for same logkey perform put operation together ?



_Code quote:_
```Java
logCache.put(logKey,
```
___
*[`260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java` line 92 at r6](https://reviewable.io/reviews/harness/harness-core/36769#-NBSwAQD8kQpZ9CHtv-C:-NBSwAQD8kQpZ9CHtv-D:b2t2x7z) ([raw file](https://github.com/harness/harness-core/blob/34d7d09a7bddc4e41fdf3cc2c8d04b30f578734f/260-delegate/src/main/java/io/harness/logstreaming/DelegateLogStreamingDispatcher.java#L92)):*
> ```Java
>     try {
>       readWriteLockForMap.readLock().lock();
>       if (!logCache.containsKey(logKey)) {
> ```

We don't need to swap here, just set the bool here. Scheduled dispatch call will happen after few seconds anyway.



_Code quote:_
```Java
      readWriteLockForMap.readLock().lock();
      if (!logCache.containsKey(logKey)) {
        logCache.put(logKey, new ArrayList<>());
      }
```

**Pull request closed without merging**
