### PR TITLE
feat: [CDS-38083]: azure list Web App names & deployment slots endpoints implementation

### PR DESCRIPTION
**Pull request by vlica-harness**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33706)

### CODE REVIEW

**Comment by vlica-harness** [comment]
trigger ti0

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33706)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/33706#-N3Nv87R5msX47P0v7v7:-N3Nv87S4FQRtFFHHO5D:b-quskkc) ([raw file](https://github.com/harness/harness-core/blob/a5c72134f77e56056204d0bef6954911ceb21892/120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java#L74)):*
> ```Java
>   @Path("subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/azure-app-services")
>   @ApiOperation(value = "Gets azure app services by subscription and resourceGroup", nickname = "getAzureAppServices")
>   public ResponseDTO<AzureWebAppNamesDTO> getAppServiceNames(
> ```

I think API endpoint name and response doesn't actually reflect each other. azure-app-services suggests that response should contain a list of azure web app services, when the actually response contains a list of azure web app names. My suggestions will be one of:
* Update response so it will contain a list of AzureWebApp with field name, so it can be updated with other details in future if it does required
* Update endpoint path itself so it would mention that response contains only name

I like more first point, but both will work for me equally good
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/33706#-N3NslEfCKeoOUF7X0tg:-N3NslEfCKeoOUF7X0th:b4ewtm0) ([raw file](https://github.com/harness/harness-core/blob/a5c72134f77e56056204d0bef6954911ceb21892/120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java#L88)):*
> ```Java
>   @GET
>   @Path("subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/azure-app-services/{webAppName}/slots")
>   @ApiOperation(value = "Gets azure webApp deployment slots", nickname = "getAzureAppServices")
> ```

This nickname should be unique, otherwise can create some issues on FE
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/AzureHelperService.java` line 180 at r1](https://reviewable.io/reviews/harness/harness-core/33706#-N3NwDdY64sMEFbVTO9_:-N3NwDdY64sMEFbVTO9a:b-tpgpa2) ([raw file](https://github.com/harness/harness-core/blob/a5c72134f77e56056204d0bef6954911ceb21892/125-cd-nextgen/src/main/java/io/harness/cdng/azure/AzureHelperService.java#L180)):*
> ```Java
> 
>   public DelegateResponseData executeSyncTask(ExecutionCapabilityDemander params, BaseNGAccess ngAccess,
>       String ifFailedMessage, Integer... customTaskTimeoutInSec) {
> ```

I'm confused why this need to be an args array. If you want to pass an optional timeout parameter without need to update it everywhere just override executeSyncTask method. So you'll have 2 methods:
* executeSyncTask([prev args]) -> executeSyncTask([prev args], Optional.empty())
* executeSyncTask([prev args], Optional<Integer> timeout)
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos/AzureWebAppNameDTO.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/33706#-N3NuaGY6lcp8kxgbgck:-N3NuaGY6lcp8kxgbgcl:bqp8mlu) ([raw file](https://github.com/harness/harness-core/blob/a5c72134f77e56056204d0bef6954911ceb21892/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos/AzureWebAppNameDTO.java#L21)):*
> ```Java
> @OwnedBy(CDP)
> @Schema(name = "AzureWebAppNameResponse", description = "Azure response for Web App name")
> public class AzureWebAppNameDTO {
> ```

Is this used anywhere or it was intended to be used with AzureWebAppNamesDTO? 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java` line 156 at r1](https://reviewable.io/reviews/harness/harness-core/33706#-N3Nwwu26nw3AY9lexR0:-N3Nwwu26nw3AY9lexR1:b-68azsk) ([raw file](https://github.com/harness/harness-core/blob/a5c72134f77e56056204d0bef6954911ceb21892/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java#L156)):*
> ```Java
> 
>     AzureWebAppNamesResponse azureWebAppNamesResponse = (AzureWebAppNamesResponse) azureHelperService.executeSyncTask(
>         azureTaskParamsTaskParams, baseNGAccess, "Azure list Web App names task failure due to error", 60);
> ```

nit: timeout should be a constant
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/azureconnector/AzureTaskType.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/33706#-N3Ny9Y-CynVzaC3Bd1m:-N3Ny9Y15BN3N6tNS5F9:bp6jbpn) ([raw file](https://github.com/harness/harness-core/blob/a5c72134f77e56056204d0bef6954911ceb21892/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/azureconnector/AzureTaskType.java#L21)):*
> ```Java
>   LIST_RESOURCE_GROUPS,
>   LIST_CLUSTERS,
>   LIST_WEBAPP_NAMES,
> ```

Let's add them at the end of enum, there is some issues with kryo when you mess up with order and I feel that this is used in kryo ser/der

**Comment by vlica-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/33706#-N3NslEfCKeoOUF7X0tg:-N3O9RzW6TLMKmzMf3H1:bc8flwk) ([raw file](https://github.com/harness/harness-core/blob/a5c72134f77e56056204d0bef6954911ceb21892/120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java#L88)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This nickname should be unique, otherwise can create some issues on FE
</blockquote></details>

Thanks, done

**Comment by vlica-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/AzureHelperService.java` line 180 at r1](https://reviewable.io/reviews/harness/harness-core/33706#-N3NwDdY64sMEFbVTO9_:-N3O9YQ43lK9O3XVkSC_:b-tfxy97) ([raw file](https://github.com/harness/harness-core/blob/a5c72134f77e56056204d0bef6954911ceb21892/125-cd-nextgen/src/main/java/io/harness/cdng/azure/AzureHelperService.java#L180)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I'm confused why this need to be an args array. If you want to pass an optional timeout parameter without need to update it everywhere just override executeSyncTask method. So you'll have 2 methods:
* executeSyncTask([prev args]) -> executeSyncTask([prev args], Optional.empty())
* executeSyncTask([prev args], Optional<Integer> timeout)
</blockquote></details>

yeah, the idea was to pass a parameter and not to update it everywhere where method is used. 
I thought there will be too many methods executeSyncTask, but makes sense. Updated.

**Comment by vlica-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java` line 156 at r1](https://reviewable.io/reviews/harness/harness-core/33706#-N3Nwwu26nw3AY9lexR0:-N3OA0zp6DNMYrMCv9ls:b-y01cq2) ([raw file](https://github.com/harness/harness-core/blob/a5c72134f77e56056204d0bef6954911ceb21892/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java#L156)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: timeout should be a constant
</blockquote></details>

Thanks, done.

**Comment by vlica-harness** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/azureconnector/AzureTaskType.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/33706#-N3Ny9Y-CynVzaC3Bd1m:-N3OA8xpAw2eFXkNokPy:b-2itqi) ([raw file](https://github.com/harness/harness-core/blob/a5c72134f77e56056204d0bef6954911ceb21892/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/azureconnector/AzureTaskType.java#L21)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's add them at the end of enum, there is some issues with kryo when you mess up with order and I feel that this is used in kryo ser/der
</blockquote></details>

Makes sense, done.

**Comment by vlica-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos/AzureWebAppNameDTO.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/33706#-N3NuaGY6lcp8kxgbgck:-N3ODyAq1oKxU0OMRcIP:bmod9i4) ([raw file](https://github.com/harness/harness-core/blob/a5c72134f77e56056204d0bef6954911ceb21892/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos/AzureWebAppNameDTO.java#L21)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Is this used anywhere or it was intended to be used with AzureWebAppNamesDTO? 
</blockquote></details>

not used anymore, removed

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33706)* status: :shipit: complete! ✓

**Review by nassergonzalez — DISMISSED** [review]
> Reviewed 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33706)* status: :shipit: complete! ✓

**Review by vlica-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33706)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java` line 79 at r2](https://reviewable.io/reviews/harness/harness-core/33706#-N3OIX3f8oENg4cD-Fkl:-N3PR73f3fCqNbYhhcQh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6e93f3857fb75ea2bcf2ff0c54fda7b9dcb80aec/120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java#L79)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Can we annotate PathParams with @NotNull?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/33706#-N3OIjOOABXkVwg8BBWd:-N3PR7kO6-ODMVj3Y8U1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6e93f3857fb75ea2bcf2ff0c54fda7b9dcb80aec/120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java#L94)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/azure/response/AzureDeploymentSlotResponse.java` line 1 at r2](https://reviewable.io/reviews/harness/harness-core/33706#-N3PDSXs1vYIzaLeSeMM:-N3PR95N0_vF250ti5_3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6e93f3857fb75ea2bcf2ff0c54fda7b9dcb80aec/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/azure/response/AzureDeploymentSlotResponse.java#L1)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Please add copyright to all new files
</blockquote></details>

Done.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 22 files at r1, 1 of 5 files at r2, 1 of 2 files at r4, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33706)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, 7 of 8 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33706)* status: :shipit: complete! ✓

**Review by nassergonzalez — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33706)* status: :shipit: complete! ✓

**Review by nassergonzalez — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33706)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 10 of 22 files at r1, 3 of 5 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, 7 of 8 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33706)* status: :shipit: complete! ✓

**Pull request merged**
