### PR TITLE
fix: [PL-32770]: add capability specific error message

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes

Summary:
Add capability specific error message in selection log when validation failed for all eligible delegates

Test:
Local test

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48377)

### CODE REVIEW

**Comment by jennyjames21** [comment]
image

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48377)* status: 36 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorHelper.java` line 183 at r4](https://reviewable.io/reviews/harness/harness-core/48377#-NWn7gz547INp35qujYI:-NWn7gz547INp35qujYJ:bubebjo) ([raw file](https://github.com/harness/harness-core/blob/f8ac94b25fafb466db784c2ddae29414e5bd73ec/400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorHelper.java#L183)):*
> ```Java
>         if (taskWaitIds.containsKey(taskId)) {
>           String errorMessage = delegateTasks.containsKey(taskId)
>               ? assignDelegateService.getActiveDelegateAssignmentErrorMessage(EXPIRED, delegateTasks.get(taskId))
> ```

Why are we not upgrading this method? It will help unify the error messages right?

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorHelper.java` line 183 at r4](https://reviewable.io/reviews/harness/harness-core/48377#-NWn7gz547INp35qujYI:-NWnfFNn6OLR00DWovUa:b-dpc5l0) ([raw file](https://github.com/harness/harness-core/blob/f8ac94b25fafb466db784c2ddae29414e5bd73ec/400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorHelper.java#L183)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Why are we not upgrading this method? It will help unify the error messages right?
</blockquote></details>


1) Text is longer to display as error message versus selection log has more space to display
2) I thought we will add it to the selection log first. IMO we should only rely only on selection log once we enabled selection log for all task types. We can enable selection log for all task types once we switched from mongo to GCP (planning to enable this soon)

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 4 of 33 files at r2, 29 of 30 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48377)* status: 36 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48377)* status: 36 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorHelper.java` line 183 at r4](https://reviewable.io/reviews/harness/harness-core/48377#-NWn7gz547INp35qujYI:-NXRPI6nECAGWPUo77rA:b-e9pota) ([raw file](https://github.com/harness/harness-core/blob/198572a9a7f2887f9c9fb2fc3bb62243829ad4df/400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorHelper.java#L183)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>


1) Text is longer to display as error message versus selection log has more space to display
2) I thought we will add it to the selection log first. IMO we should only rely only on selection log once we enabled selection log for all task types. We can enable selection log for all task types once we switched from mongo to GCP (planning to enable this soon)
</blockquote></details>

As discussed offline, the selection log is not available on each view. Even the view from the ticket is not a selection log. Can you please leave a TODO comment to integrate the same log here too?
___
*[`400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorHelper.java` line 266 at r4](https://reviewable.io/reviews/harness/harness-core/48377#-NXRNfqhDRLtHVgx1F7S:-NXRNfqhDRLtHVgx1F7T:bm67mv2) ([raw file](https://github.com/harness/harness-core/blob/198572a9a7f2887f9c9fb2fc3bb62243829ad4df/400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorHelper.java#L266)):*
> ```Java
>           String capabilityErrors = String.format("%s : [%s]", capability.getCapabilityValidationError(),
>               getHostNamesFromDelegateIds(delegateTask.getAccountId(), delegateTask.getEligibleToExecuteDelegateIds()));
>           delegateSelectionLogsService.logTaskValidationFailed(delegateTask, capabilityErrors);
> ```

Is the following snippet not enough? 

* isNotEmpty(delegateTask.getExecutionCapabilities()) -- not required as we are going to iterate an empty list and do nothing
* delegateTask.getStatus().equals(QUEUED) -- What do we need to check this? How can we enter this function for non-queued task?
* Also it is a good practice to un-nest the code, just makes it more readable



_Code snippet:_
```Java
if (!delegateTask.getValidationCompleteDelegateIds().containsAll(
            delegateTask.getEligibleToExecuteDelegateIds())) {
  return;
}

delegateTask.getExecutionCapabilities().forEach(capability -> {
  if (isEmpty(capability.getCapabilityToString())) {
    return;
  }
  String capabilityErrors = String.format("%s : [%s]", capability.getCapabilityValidationError(),
      getHostNamesFromDelegateIds(delegateTask.getAccountId(), delegateTask.getEligibleToExecuteDelegateIds()));
  delegateSelectionLogsService.logTaskValidationFailed(delegateTask, capabilityErrors);
});
```

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorHelper.java` line 266 at r4](https://reviewable.io/reviews/harness/harness-core/48377#-NXRNfqhDRLtHVgx1F7S:-NXRRZv68jd8IPhurfxJ:b80n3ii) ([raw file](https://github.com/harness/harness-core/blob/198572a9a7f2887f9c9fb2fc3bb62243829ad4df/400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorHelper.java#L266)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Is the following snippet not enough? 

* isNotEmpty(delegateTask.getExecutionCapabilities()) -- not required as we are going to iterate an empty list and do nothing
* delegateTask.getStatus().equals(QUEUED) -- What do we need to check this? How can we enter this function for non-queued task?
* Also it is a good practice to un-nest the code, just makes it more readable
</blockquote></details>

1) delegateTask.getExecutionCapabilities() can be null for task that doesn't need validation 
2) QUEUED status not needed, i will remove
3)  Not all code reviewers follow that, some people enforce removing unnecessary lines of code . So it's hard for me to write code per reviewers' choice.  


But not to offend anybody i will make this change which sounds good suggestion to me :).  Waiting for a day when AI does the code review. 

if (!delegateTask.getValidationCompleteDelegateIds().containsAll(
            delegateTask.getEligibleToExecuteDelegateIds())) {
  return;
}

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48377)* status: 37 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorHelper.java` line 266 at r4](https://reviewable.io/reviews/harness/harness-core/48377#-NXRNfqhDRLtHVgx1F7S:-NXRYILP3S4eyrFt5luj:b6vrqmv) ([raw file](https://github.com/harness/harness-core/blob/198572a9a7f2887f9c9fb2fc3bb62243829ad4df/400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorHelper.java#L266)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

my bad QEUEUD status is needed here. When the task is expired(task status: started) but validation is completed for all (success for at least one delegate) we shouldn't be logging validation failure
</blockquote></details>

Cool, thanks!

This un-nesting is actually an industry-wide standard: https://testing.googleblog.com/2017/06/code-health-reduce-nesting-reduce.html . We will also publish these guidelines internally for developers.

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger ut1

**Pull request merged**
