### PR TITLE
feat: [CDS-81832]: Add support for V1 static schema for templates for V1 schema parser

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Add support for V1 static schema for templates for V1 schema parser

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54186)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger ut5, ut6, ut7, ut8, ut9

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/release/release-branch.sh` line 247 at r1](https://reviewable.io/reviews/harness/harness-core/54186#-NgwIbve9LxwyxjZmRGr:-NgwIbve9LxwyxjZmRGs:bzaymto) ([raw file](https://github.com/harness/harness-core/blob/cd6c65306fb62a2799183653148fbbe25bbb0b43/pipeline-service/release/release-branch.sh#L247)):*
> ```Shell
>     # Updating static-schema for V1 pipeline in branch cut branch
>     PIPELINE_V1_JSON="pipeline-service/service/src/main/resources/static-schema/v1/pipeline.json"
>     perform_curl_with_retry "https://raw.githubusercontent.com/harness/harness-schema/${head_static_commit}/v1/pipeline.json" ${PIPELINE_V1_JSON}
> ```

why doing same thing again? Same is being done above in this file

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54186)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/release/release-branch.sh` line 247 at r1](https://reviewable.io/reviews/harness/harness-core/54186#-NgwIbve9LxwyxjZmRGr:-NgwLFcB26iF1zjTBher:b-j8iglw) ([raw file](https://github.com/harness/harness-core/blob/cd6c65306fb62a2799183653148fbbe25bbb0b43/pipeline-service/release/release-branch.sh#L247)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

why doing same thing again? Same is being done above in this file
</blockquote></details>

@brijeshdhakar First we are updating latest schema to develop then we are doing it for release branch, hence it is done twice

**Review by shalini-agr — APPROVED** [review]

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54186)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/utils/TemplateSchemaFetcher.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/54186#-Ngx9w6UC3TlaSZaNb_w:-Ngx9w6UC3TlaSZaNb_x:bfe3lcl) ([raw file](https://github.com/harness/harness-core/blob/cd6c65306fb62a2799183653148fbbe25bbb0b43/template-service/service/src/main/java/io/harness/template/utils/TemplateSchemaFetcher.java#L68)):*
> ```Java
>         templateStaticSchemaJsonNode else directly return templateStaticSchemaJsonNode
>       */
>       if (version.equals(TEMPLATE_VO)) {
> ```

can you use switch case for it

**Review by utkarshchoubey-harness — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54186)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/release/release-branch.sh` line 247 at r1](https://reviewable.io/reviews/harness/harness-core/54186#-NgwIbve9LxwyxjZmRGr:-NgxE6KGEJIYFpL__z_q:b-896fjb) ([raw file](https://github.com/harness/harness-core/blob/cd6c65306fb62a2799183653148fbbe25bbb0b43/pipeline-service/release/release-branch.sh#L247)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

@brijeshdhakar First we are updating latest schema to develop then we are doing it for release branch, hence it is done twice
</blockquote></details>

Done 
___
*[`template-service/service/src/main/java/io/harness/template/utils/TemplateSchemaFetcher.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/54186#-Ngx9w6UC3TlaSZaNb_w:-NgxE61S1IYMtv1rcIq4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cd6c65306fb62a2799183653148fbbe25bbb0b43/template-service/service/src/main/java/io/harness/template/utils/TemplateSchemaFetcher.java#L68)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you use switch case for it
</blockquote></details>

Done.

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54186)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/release/release-branch.sh` line 247 at r1](https://reviewable.io/reviews/harness/harness-core/54186#-NgwIbve9LxwyxjZmRGr:-Nh0D53m2esOALGQGMYW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cd6c65306fb62a2799183653148fbbe25bbb0b43/pipeline-service/release/release-branch.sh#L247)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Why doing the curl again? We already have the file from the previous curl? Also storing at the same location.
</blockquote></details>

Done.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54186)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54186)* status: :shipit: complete! ✓

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Pull request merged**
