### PR TITLE
techdebt: [PL-22201]: Access control code reorganization

### PR DESCRIPTION
**Pull request by gupta-utkarsh**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31376)

### CODE REVIEW

**Comment by gupta-utkarsh** [comment]
trigger messagecheck

**Comment by gupta-utkarsh** [comment]
trigger codeformat

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 218 of 218 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31376#-:-MxqKAru1jcmU4KkYIT3:bnfp4nl)* status: 218 file(s) to review. 1 of 2 approvals obtained.

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 218 of 218 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31376)* status: :shipit: complete! ✓

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31376#-:-MxqbO-0EK9MdB1hVJ88:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
