### PR TITLE
fix: [CDS-69727]: Set pipeline git info for resolving templates

### PR DESCRIPTION
**Pull request by rohitk-h**
## Describe your changes
- When a trigger is created it validates the pipeline inputs, the templates pipeline refers to and the input sets. If validation fails the trigger will save but will not be enabled. The same validation is done when enabling a disabled trigger.
- In this case the templates which was in remote repo were failing to resolve results in failed trigger validation. 
- Fix here is setting the pipeline connector and repo information before resolving the remote templates. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48264)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48264)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 486 at r1](https://reviewable.io/reviews/harness/harness-core/48264#-NWAvIGR0bD_wqmwKXSO:-NWAvIGR0bD_wqmwKXSP:b-xawik6) ([raw file](https://github.com/harness/harness-core/blob/44b879eaa9a91cbd892b9ada0c449409674df376/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L486)):*
> ```Java
>     // `default`. It's only being called from NGTriggers hence we are intentionally passing the pipeline connector info
>     // and pipeline repo. It needs to be removed once we deprecate old git sync.
>     PipelineGitXHelper.setupGitParentEntityDetails(
> ```

why we are setting in api level, before making template resolve call, we have set there


refer 

private TemplateMergeResponseDTO resolveTemplateRefsInPipeline(String accountId, String orgId, String projectId,
      String yaml, boolean checkForTemplateAccess, boolean getMergedTemplateWithTemplateReferences,
      String loadFromCache, boolean appendInputSetValidator) {

**Review by rohitk-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48264)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 486 at r1](https://reviewable.io/reviews/harness/harness-core/48264#-NWAvIGR0bD_wqmwKXSO:-NWB7WlY97qX1pZBGhj9:b-wyfpb5) ([raw file](https://github.com/harness/harness-core/blob/44b879eaa9a91cbd892b9ada0c449409674df376/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L486)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are setting in api level, before making template resolve call, we have set there


refer 

private TemplateMergeResponseDTO resolveTemplateRefsInPipeline(String accountId, String orgId, String projectId,
      String yaml, boolean checkForTemplateAccess, boolean getMergedTemplateWithTemplateReferences,
      String loadFromCache, boolean appendInputSetValidator) {

</blockquote></details>

Line: io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java:99
```GitEntityInfo gitEntityInfo = GitContextHelper.getGitEntityInfo();``` returns null due to condition here: io/harness/gitsync/helpers/GitContextHelper.java:40 

hence we must set this before this line. Discussed with @mohitg0795 and added in the api level.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 486 at r1](https://reviewable.io/reviews/harness/harness-core/48264#-NWAvIGR0bD_wqmwKXSO:-NWBGKuiA28zPwUDdEN9:bw90rn7) ([raw file](https://github.com/harness/harness-core/blob/44b879eaa9a91cbd892b9ada0c449409674df376/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L486)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Line: io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java:99
```GitEntityInfo gitEntityInfo = GitContextHelper.getGitEntityInfo();``` returns null due to condition here: io/harness/gitsync/helpers/GitContextHelper.java:40 

hence we must set this before this line. Discussed with @mohitg0795 and added in the api level. 

</blockquote></details>

We don't need this comment here @rohitk-h . This change isn't specific to triggers. This change makes the API correct in its behaviour on its own, doesn't depend on the clients.

@archit-harness can you pin point where are we setting these values? Here, the issue is we have written logics in resource layer thus we need to set it over there.

**Review by archit-harness — APPROVED** [review]

**Review by rohitk-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48264)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 486 at r1](https://reviewable.io/reviews/harness/harness-core/48264#-NWAvIGR0bD_wqmwKXSO:-NWDRCFE5OOAZEjIY1Vi:b-dlnt20) ([raw file](https://github.com/harness/harness-core/blob/44b879eaa9a91cbd892b9ada0c449409674df376/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L486)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We don't need this comment here @rohitk-h . This change isn't specific to triggers. This change makes the API correct in its behaviour on its own, doesn't depend on the clients.

@archit-harness can you pin point where are we setting these values? Here, the issue is we have written logics in resource layer thus we need to set it over there.
</blockquote></details>

Updated.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48264)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by rohitk-h** [comment]
trigger uts

**Review by sribalij — APPROVED** [review]

**Comment by rohitk-h** [comment]
trigger ut5

**Comment by rohitk-h** [comment]
trigger review

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48264)* status: :shipit: complete! ✓

**Pull request merged**
