### PR TITLE
feat: [CDP-19581]: error handling FW for native helm

### PR DESCRIPTION
**Pull request by achyuth-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/29986)

### CODE REVIEW

**Comment by achyuth-harness** [comment]
trigger ft1

**Comment by achyuth-harness** [comment]
trigger pmd

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 23 of 26 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29986)* status: 29 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmDeployOutcome.java, line 35 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-MtlvauO5gLGD3fZkMHU:-MtlvauO5gLGD3fZkMHV:b4a5z2u) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmDeployOutcome.java#L35)):*
> ```Java
>   int newReleaseVersion;
>   List<ContainerInfo> containerInfoList;
>   boolean isInstallUpgrade;
> ```

nit: naming is a bit confusing
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java, line 232 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-MtlwDLJ8rX9hOvGnUUu:-MtlwDLJ8rX9hOvGnUUv:b-ni15g5) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L232)):*
> ```Java
>       logCallback = markDoneAndStartNew(commandRequest, logCallback, WrapUp);
> 
>       if (checkIfReleasePurgingNeeded(commandRequest)) {
> ```

This should always be part of finally block, don't see the reason why it was moved away
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java, line 380 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-MtlwXuG7YMBiw0R-nNr:-MtlwXuG7YMBiw0R-nNs:b-aoavv5) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L380)):*
> ```Java
>             .workingDirectory(workingDir)
>             .kubeconfigPath(kubeconfigPath)
>             .isErrorFrameworkEnabled(true)
> ```

Why do we need this field? doStatusCheckForAllResources is already supporting isErrorFrameworkEnabled flag
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java, line 489 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-MtlxCmHCmMCM2BmDvqb:-MtlxCmHCmMCM2BmDvqc:b-griaf2) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L489)):*
> ```Java
>       log.error(TIMED_OUT_IN_STEADY_STATE, e);
>       logCallback.saveExecutionLog(TIMED_OUT_IN_STEADY_STATE, LogLevel.ERROR);
>       return new HelmCommandResponseNG(CommandExecutionStatus.FAILURE, ExceptionUtils.getMessage(e));
> ```

Would it make sense to throw e instead returning response since the current flow rely on error framework now?
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java, line 494 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-MtlwuhjCpGoMIClMKh_:-Mtlwuhl0YKQxr9PmKba:b-7au21w) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L494)):*
> ```Java
>       log.error("Helm rollback failed: " + msg, e);
>       throw e;
>       //      return new HelmCommandResponseNG(
> ```

Let's remove this
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNG.java, line 83 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-Mtm3e_W8xt3SjKVV_wC:-Mtm3e_W8xt3SjKVV_wD:b-wrpugj) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNG.java#L83)):*
> ```Java
>           .build();
>     } catch (Exception e) {
>       // TODO: IMPORTANT! Verify if this doesn't adversely affect K8s steps
> ```

are we good here?
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, line 1433 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-Mtm3mwnDGUpvJQWXPIz:-Mtm3mwo4e62C0GR2u4r:b3lfhaq) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L1433)):*
> ```Java
>       boolean denoteOverallSuccess) throws Exception {
>     return doStatusCheckForAllResources(client, resourceIds, k8sDelegateTaskParams, namespace, executionLogCallback,
>         denoteOverallSuccess, k8sDelegateTaskParams.isErrorFrameworkEnabled());
> ```

I don't see why we do need to complicate this logic
___
*[960-api-services/src/main/java/io/harness/helm/HelmClient.java, line 33 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-Mtm42PO-b4Ix1VgYd5B:-Mtm42PO-b4Ix1VgYd5C:b-oz6bgg) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/960-api-services/src/main/java/io/harness/helm/HelmClient.java#L33)):*
> ```Java
>    *
>    * @param helmCommandData the command request
>    * @param isErrorFrameworkEnabled
> ```

nit: we can add some more details why this param is needed since we're commeting usage 
___
*[960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java, line 554 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-Mtm4wWR3_J2GbSwP8fH:-Mtm4wWR3_J2GbSwP8fI:bixxd2z) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java#L554)):*
> ```Java
>   static class ErrorActivityOutputStream extends LogOutputStream {
>     @NonNull private final LogCallback logCallback;
>     @Getter private String input;
> ```

nit: name actually should be output
___
*[970-api-services-beans/src/main/java/io/harness/k8s/model/K8sDelegateTaskParams.java, line 24 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-Mtm50RT9NgMUzNHGbcv:-Mtm50RT9NgMUzNHGbcw:b-fi7h2o) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/970-api-services-beans/src/main/java/io/harness/k8s/model/K8sDelegateTaskParams.java#L24)):*
> ```Java
>   String kustomizeBinaryPath;
>   boolean useVarSupportForKustomize;
>   boolean isErrorFrameworkEnabled;
> ```

Let's re review if we do actually need this

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29986)* status: 29 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmDeployOutcome.java, line 35 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-MtlvauO5gLGD3fZkMHU:-MtmGiug0Z5NM7LlafFJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmDeployOutcome.java#L35)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: naming is a bit confusing
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java, line 232 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-MtlwDLJ8rX9hOvGnUUu:-MtmQgI70zc3PZZZt5Vk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L232)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This should always be part of finally block, don't see the reason why it was moved away
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java, line 380 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-MtlwXuG7YMBiw0R-nNr:-MtmQhDg69XrLLg-JzZf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L380)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why do we need this field? doStatusCheckForAllResources is already supporting isErrorFrameworkEnabled flag
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java, line 489 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-MtlxCmHCmMCM2BmDvqb:-MtmImhE3PUUFQBIgLhU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L489)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Would it make sense to throw e instead returning response since the current flow rely on error framework now?
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java, line 494 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-MtlwuhjCpGoMIClMKh_:-MtmIlozCQNPkiMn2R2E:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L494)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's remove this
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNG.java, line 83 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-Mtm3e_W8xt3SjKVV_wC:-MtmInuM23kox8e-PKIc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNG.java#L83)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

are we good here?
</blockquote></details>

Done.
___
*[960-api-services/src/main/java/io/harness/helm/HelmClient.java, line 33 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-Mtm42PO-b4Ix1VgYd5B:-MtmJIW9A-YOHYFWwFQw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/960-api-services/src/main/java/io/harness/helm/HelmClient.java#L33)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: we can add some more details why this param is needed since we're commeting usage 
</blockquote></details>

Done.
___
*[960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java, line 554 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-Mtm4wWR3_J2GbSwP8fH:-MtmKM793pL2_tK8voEE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java#L554)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: name actually should be output
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, line 1433 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-Mtm3mwnDGUpvJQWXPIz:-MtmQe2jE7t6FIVGO_WM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L1433)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I don't see why we do need to complicate this logic
</blockquote></details>

Done.
___
*[970-api-services-beans/src/main/java/io/harness/k8s/model/K8sDelegateTaskParams.java, line 24 at r4](https://reviewable.io/reviews/harness/harness-core/29986#-Mtm50RT9NgMUzNHGbcv:-MtmQew34Al9jj6FMroF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d87500708234eac68b5b801eeb56cf900aba4f8c/970-api-services-beans/src/main/java/io/harness/k8s/model/K8sDelegateTaskParams.java#L24)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's re review if we do actually need this 
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29986)* status: 29 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java, line 313 at r5](https://reviewable.io/reviews/harness/harness-core/29986#-MtmmHx3DC2Ya0F2nZq8:-MtmmHx3DC2Ya0F2nZq9:bj4ufr3) ([raw file](https://github.com/harness/harness-core/blob/c44df32eefee8a63a2048364b990b714008eba5b/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L313)):*
> ```Java
>       String msg = "Helm delete failed: " + exceptionMessage;
>       log.error(msg, e);
>       logCallback.saveExecutionLog(msg, LogLevel.ERROR);
> ```

I don't expect any executions logs active at this time. Let's remove this line. log.error should be enough for us to debug if someone hit any issues

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29986)* status: 29 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java, line 313 at r5](https://reviewable.io/reviews/harness/harness-core/29986#-MtmmHx3DC2Ya0F2nZq8:-MtmqrOL7RniA1JkD8_M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c44df32eefee8a63a2048364b990b714008eba5b/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L313)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I don't expect any executions logs active at this time. Let's remove this line. log.error should be enough for us to debug if someone hit any issues
</blockquote></details>

Done.

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29986)* status: 18 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java, line 173 at r6](https://reviewable.io/reviews/harness/harness-core/29986#-MtpHW9A74x2uaehz3MI:-MtpjxYl5x_XOF9qA3XS:bb7sa0c) ([raw file](https://github.com/harness/harness-core/blob/21839d1554481b8cd97e60b617ce60be75514d61/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L173)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this intentional or a part of error handling ?
</blockquote></details>

yes, part of error handling
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmExceptionConstants.java, line 37 at r6](https://reviewable.io/reviews/harness/harness-core/29986#-MtpI7WwEA47-E7skl3G:-MtpsqTy8RjPHn0jCeFl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1f30947bd024a07823b32ec9bcaa525468cc1c22/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmExceptionConstants.java#L37)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I am not able to understand what this means ? Do we need to elaborate ?
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmExceptionConstants.java, line 41 at r6](https://reviewable.io/reviews/harness/harness-core/29986#-MtpIG2y-AocTMTnSE14:-MtpmyiV0G_Ie_MmqDZW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1f30947bd024a07823b32ec9bcaa525468cc1c22/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmExceptionConstants.java#L41)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

These are user facing messages. cmd should probable be command or something similar
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmExceptionConstants.java, line 77 at r6](https://reviewable.io/reviews/harness/harness-core/29986#-MtpIUKE5Ga7f16TRhlA:-Mtpn78CBdPLUCdwKXAo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1f30947bd024a07823b32ec9bcaa525468cc1c22/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmExceptionConstants.java#L77)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

pls -> please
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 592 at r6](https://reviewable.io/reviews/harness/harness-core/29986#-MtpIurnE9d4ljcivCYW:-Mtpk2b91Jro3L9gMaZu:b-8cxrw0) ([raw file](https://github.com/harness/harness-core/blob/1f30947bd024a07823b32ec9bcaa525468cc1c22/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L592)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we want to fail in this case now ?
</blockquote></details>

Yes, discussed this pt with @abosii-harness, (as it could potentially cause adverse effects in Kubernetes). now instead of continuing execution with failed response, we fail in fetch files stage. this is useful as it helps in catching errors like invalid chart/repo name, incorrect/invalid chart path, connector creds etc.

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29986)* status: 18 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java, line 173 at r6](https://reviewable.io/reviews/harness/harness-core/29986#-MtpHW9A74x2uaehz3MI:-MtptNUU-tvjlrRz34k7:bq0n3g5) ([raw file](https://github.com/harness/harness-core/blob/21839d1554481b8cd97e60b617ce60be75514d61/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L173)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

yes.
</blockquote></details>

Its a part of error handling

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 20 files at r1, 6 of 26 files at r2, 4 of 11 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29986)* status: 6 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 592 at r6](https://reviewable.io/reviews/harness/harness-core/29986#-MtpIurnE9d4ljcivCYW:-MtsfOvb0nvd1YwV0LZO:brhveze) ([raw file](https://github.com/harness/harness-core/blob/1f30947bd024a07823b32ec9bcaa525468cc1c22/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L592)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

Yes, discussed this pt with @abosii-harness, (as it could potentially cause adverse effects in Kubernetes). now instead of continuing execution with failed response, we fail in fetch files stage. this is useful as it helps in catching errors like invalid chart/repo name, incorrect/invalid chart path, connector creds etc.
</blockquote></details>

and this only affects NG ?
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNG.java, line 85 at r6](https://reviewable.io/reviews/harness/harness-core/29986#-MtpjcUNAgIvJHm6btmF:-MtpjcUR-qGm9wIVrVsW:bf44828) ([raw file](https://github.com/harness/harness-core/blob/1f30947bd024a07823b32ec9bcaa525468cc1c22/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNG.java#L85)):*
> ```Java
>       String exceptionMsg = e.getMessage() == null ? ExceptionUtils.getMessage(e) : e.getMessage();
>       String msg = "HelmValuesFetchTaskNG execution failed with exception " + exceptionMsg;
>       log.error(msg, e);
> ```

we should not log and throw together. If we throw the exception with the original exception, the caller should log it. 
This is an advice, you can read more about it. Not blocking the PR

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29986)* status: 6 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 592 at r6](https://reviewable.io/reviews/harness/harness-core/29986#-MtpIurnE9d4ljcivCYW:-MtsuiPzDWe6lm70pjFU:btdohsf) ([raw file](https://github.com/harness/harness-core/blob/1f30947bd024a07823b32ec9bcaa525468cc1c22/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L592)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

and this only affects NG ?
</blockquote></details>

Yes. the only usage of this method 'fetchValuesYamlFromChart' is in this class (HelmValuesFetchTaskNG)

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29986)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java, line 530 at r8](https://reviewable.io/reviews/harness/harness-core/29986#-MtwBz-K8GI00xuJM3Hi:-MtwBz-K8GI00xuJM3Hj:bvxknxf) ([raw file](https://github.com/harness/harness-core/blob/9e74038744786acf542eca4aa4c0c3a3ce0363bc/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L530)):*
> ```Java
> 
>             if (isHelm3(cliResponse.getOutput())) {
>               throw new InvalidRequestException("Error: Trying to perform a helm V2 deployment with helm V3");
> ```

nit: Can we use here hint and explanation logic? throw ExceptionsUtils.hintWithExplanation and add some more details like the location of used helm binary, ex: helmClient.getHelmPath(helmCommandRequest.getHelmVersion)

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29986)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java, line 530 at r8](https://reviewable.io/reviews/harness/harness-core/29986#-MtwBz-K8GI00xuJM3Hi:-MtwXPgZ1eFvaHlifgcQ:b3fodoo) ([raw file](https://github.com/harness/harness-core/blob/9e74038744786acf542eca4aa4c0c3a3ce0363bc/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L530)):*
> helmClient.getHelmPath(helmCommandRequest.getHelmVersion)
Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29986)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 20 files at r1, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29986)* status: 2 file(s) to review. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 592 at r6](https://reviewable.io/reviews/harness/harness-core/29986#-MtpIurnE9d4ljcivCYW:-MtxoMRVBP2524WLRL3S:b-i0hu2c) ([raw file](https://github.com/harness/harness-core/blob/1f30947bd024a07823b32ec9bcaa525468cc1c22/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L592)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

Yes. the only usage of this method 'fetchValuesYamlFromChart' is in this class (HelmValuesFetchTaskNG)
</blockquote></details>

So earlier we were letting this task run. Now, we fail. There can be workflows which were passing earlier and will now start to fail. Lets think through this if its going to impact CG.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29986)* status: :shipit: complete! ✓

**Pull request merged**
