### PR TITLE
feat: [PL-21243]: API to disable Git Exp

### PR DESCRIPTION
**Pull request by bhavya181**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/29988)

### CODE REVIEW

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29988)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 397 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlW0EjDTOWJJxEVI04:-MtlW0EjDTOWJJxEVI05:b-adff79) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L397)):*
> ```Java
>                             accountIdentifier, orgIdentifier, projectIdentifier)
>         > 0;
>     gitSyncSettingsService.delete(accountIdentifier, orgIdentifier, projectIdentifier);
> ```

1. What happens when someone disables and then reenables the git sync? 
2. Will everything work correctly? 
3. What all changes does he/she will have to do to make the git sync work again ?
4. If in the disabled state the git and harness has diverged, then how can we ensure that both git and harness are at the same state ?

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29988)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 551 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlX028EKYk04oop4ou:-MtlX028EKYk04oop4ov:bx8nywt) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L551)):*
> ```Java
> 
>   private void deleteExistingSetupUsages(List<YamlGitConfigDTO> yamlGitConfigDTOS) {
>     for (YamlGitConfigDTO gitSyncConfigDTO : yamlGitConfigDTOS) {
> ```

NPE if yamlGitConfigDTOs is null

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29988)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 586 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlY0m41_izmbZkseI7:-MtlY0m59QUTr8j2VAWu:bx8nywt) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L586)):*
> ```Java
> 
>   private void deleteBranches(List<YamlGitConfigDTO> yamlGitConfigDTOS) {
>     for (YamlGitConfigDTO gitSyncConfigDTO : yamlGitConfigDTOS) {
> ```

NPE if yamlGitConfigDTOs is null
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 587 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlYJgk6I_pyQAtj8bR:-MtlYJgk6I_pyQAtj8bS:baiu9vl) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L587)):*
> ```Java
>   private void deleteBranches(List<YamlGitConfigDTO> yamlGitConfigDTOS) {
>     for (YamlGitConfigDTO gitSyncConfigDTO : yamlGitConfigDTOS) {
>       List<YamlGitConfigDTO> yamlGitConfigDTOList =
> ```

Why are we getting the list of yamlgitconfig dtos again ?

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29988)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java, line 114 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlYT9aBw4BfwI8Enoh:-MtlYT9aBw4BfwI8Enoi:b-u1774u) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java#L114)):*
> ```Java
>   @ApiOperation(value = "Disable git experience", nickname = "disableGitSync")
>   public boolean putGitExperience(
>       @Parameter(description = PROJECT_PARAM_MESSAGE) @QueryParam("projectId") String projectIdentifier,
> ```

Query param should be projectIdentifier
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java, line 115 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlYWm69Q8QS9LphI8p:-MtlYWm69Q8QS9LphI8q:bvebkco) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java#L115)):*
> ```Java
>   public boolean putGitExperience(
>       @Parameter(description = PROJECT_PARAM_MESSAGE) @QueryParam("projectId") String projectIdentifier,
>       @Parameter(description = ORG_PARAM_MESSAGE) @QueryParam("organizationId") String orgIdentifier,
> ```

orgIdentifier
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java, line 116 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlYYeP6a25SnvJ5MDq:-MtlYYeP6a25SnvJ5MDr:baxf5u9) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java#L116)):*
> ```Java
>       @Parameter(description = PROJECT_PARAM_MESSAGE) @QueryParam("projectId") String projectIdentifier,
>       @Parameter(description = ORG_PARAM_MESSAGE) @QueryParam("organizationId") String orgIdentifier,
>       @Parameter(description = ACCOUNT_PARAM_MESSAGE) @QueryParam("accountId") @NotEmpty String accountId) {
> ```

accountIdentifier

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29988)* status: 9 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitBranchServiceImpl.java, line 137 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlbW19-e39-9e98A0T:-MtlbW19-e39-9e98A0U:b-2tzqg0) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitBranchServiceImpl.java#L137)):*
> ```Java
>       GitBranch gitBranch = get(accountId, GitUtils.convertToUrlWithGit(repoUrl), branchName);
>       if (gitBranch == null) {
>         gitBranch = GitBranch.builder()
> ```

can we convert this into upsert query?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitBranchServiceImpl.java, line 223 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlbccW-fJgnUyI9eZ8:-MtlbccW-fJgnUyI9eZ9:bnpzf8x) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitBranchServiceImpl.java#L223)):*
> ```Java
> 
>   @Override
>   public DeleteResult deleteAll(String repoUrl, String accountIdentifier) {
> ```

Please use a consistent arguments order from highest to lowest in priority. Its not consistent right now but going forward we can make it for all newly added methods.
eg: here accountIdentifier should come before repoUrl.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncSettingsServiceImpl.java, line 71 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlcA1bAk9I4uAFjtDV:-MtlcA1bAk9I4uAFjtDW:b-jcfrek) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncSettingsServiceImpl.java#L71)):*
> ```Java
>   @Override
>   public void delete(String accountIdentifier, String orgIdentifier, String projectIdentifier) {
>     gitSyncSettingsRepository.deleteByAccountIdentifierAndOrgIdentifierAndProjectIdentifier(
> ```

Can we just check if it deletes all occurrences? Can be easily tested via manual test.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 571 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlcabcAHv2YQT-dlMq:-MtlcabcAHv2YQT-dlMr:b-yb5jdo) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L571)):*
> ```Java
>         setupUsageEventProducer.send(
>             Message.newBuilder()
>                 .putAllMetadata(ImmutableMap.of("accountId", gitSyncConfigDTO.getAccountIdentifier(),
> ```

Please use static constant for account Id here. Check with @rathodmeetsatish on it.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 577 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlcYkvAHsERQKB02RD:-MtlcYkvAHsERQKB02RE:b-6pznwj) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L577)):*
> ```Java
>                 .build());
>       } catch (Exception ex) {
>         log.error(
> ```

exception is not added to the log
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java, line 116 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlYYeP6a25SnvJ5MDq:-Mtlcmb7-lJAvnnNW6OR:bwgjl9p) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java#L116)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

accountIdentifier
</blockquote></details>

Lets maintain the order as well please.
___
*[136-git-sync-manager/src/main/java/io/harness/repositories/repositories/yamlGitConfig/YamlGitConfigRepository.java, line 45 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlcwqZBUknpMlMJf0a:-MtlcwqZBUknpMlMJf0b:b-yj2vtz) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/repositories/repositories/yamlGitConfig/YamlGitConfigRepository.java#L45)):*
> ```Java
>       String accountId, String organizationIdentifier, String projectIdentifier, String repo);
> 
>   Long deleteByAccountIdAndOrgIdentifierAndProjectIdentifier(
> ```

Here return type is Long but in GitSyncSettingsRepository, its void for same delete method. Please can we verify it once and get more clarity on it.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29988)* status: 9 file(s) to review. 2 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitBranchServiceImpl.java, line 137 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlbW19-e39-9e98A0T:-MtmUvqnDRCaWWua-9fh:b-z4wnbz) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitBranchServiceImpl.java#L137)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we convert this into upsert query?
</blockquote></details>

No, upsert does not create collection in db with the _class field, which can throw error.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitBranchServiceImpl.java, line 223 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlbccW-fJgnUyI9eZ8:-MtmV9NsBzqkz9LbHITO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitBranchServiceImpl.java#L223)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Please use a consistent arguments order from highest to lowest in priority. Its not consistent right now but going forward we can make it for all newly added methods.
eg: here accountIdentifier should come before repoUrl.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncSettingsServiceImpl.java, line 71 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlcA1bAk9I4uAFjtDV:-MtmVCPwAd-06r5NPZMb:b-8pzzpu) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncSettingsServiceImpl.java#L71)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can we just check if it deletes all occurrences? Can be easily tested via manual test.
</blockquote></details>

Yes, it has been tested.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 397 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlW0EjDTOWJJxEVI04:-MtmVGoBBEI-THe5gW2z:b-uly6bo) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L397)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

1. What happens when someone disables and then reenables the git sync? 
2. Will everything work correctly? 
3. What all changes does he/she will have to do to make the git sync work again ?
4. If in the disabled state the git and harness has diverged, then how can we ensure that both git and harness are at the same state ?


</blockquote></details>

1. Nothing will change, the normal git-sync enable flow will work.
2. Yes
3. No, change is required.
4. By Full-Sync, whenever he enables git-sync again.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 551 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlX028EKYk04oop4ou:-MtmVhKx7gAOSiROz1A8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L551)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

NPE if yamlGitConfigDTOs is null
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 571 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlcabcAHv2YQT-dlMq:-MtmVi124meh5RhBmTe8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L571)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Please use static constant for account Id here. Check with @rathodmeetsatish on it.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 577 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlcYkvAHsERQKB02RD:-MtmVimX2kckI7mm9oC5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L577)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

exception is not added to the log
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 586 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlY0m41_izmbZkseI7:-MtmVjXI4CRGXplEVZ6y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L586)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

NPE if yamlGitConfigDTOs is null
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 587 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlYJgk6I_pyQAtj8bR:-MtmVk7JAfwUzS9_sOeU:bnco6q1) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L587)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Why are we getting the list of yamlgitconfig dtos again ?
</blockquote></details>

Earlier list is of all repos, synced in a paticular project, while this list is for checking whether this repo is synced in diff projects or not, 
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java, line 114 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlYT9aBw4BfwI8Enoh:-MtmVzxq1AjsBd2bapEs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java#L114)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Query param should be projectIdentifier
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java, line 115 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlYWm69Q8QS9LphI8p:-MtmW-K088CdGoFJ4rDx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java#L115)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

orgIdentifier
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java, line 116 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlYYeP6a25SnvJ5MDq:-MtmW-iI3hU3AfVa-kbJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java#L116)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets maintain the order as well please.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/repositories/repositories/yamlGitConfig/YamlGitConfigRepository.java, line 45 at r1](https://reviewable.io/reviews/harness/harness-core/29988#-MtlcwqZBUknpMlMJf0a:-MtmW4_P-gBPJdyFbd4d:b-peujyk) ([raw file](https://github.com/harness/harness-core/blob/ed81534134b184f44e2c4b1b0e92772514469ec5/136-git-sync-manager/src/main/java/io/harness/repositories/repositories/yamlGitConfig/YamlGitConfigRepository.java#L45)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Here return type is Long but in GitSyncSettingsRepository, its void for same delete method. Please can we verify it once and get more clarity on it.
</blockquote></details>

Both works for it.

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29988)* status: 9 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 594 at r2](https://reviewable.io/reviews/harness/harness-core/29988#-MtmZReV-UMswvYND3Mp:-MtmZReV-UMswvYND3Mq:b375qos) ([raw file](https://github.com/harness/harness-core/blob/7179bb823056743dc392e0f8a161227ea7faf402/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L594)):*
> ```Java
>       List<YamlGitConfigDTO> yamlGitConfigDTOList =
>           getByAccountAndRepo(gitSyncConfigDTO.getAccountIdentifier(), gitSyncConfigDTO.getRepo());
>       if (yamlGitConfigDTOList.size() == 0) {
> ```

shouldn't this be !=0

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29988)* status: 9 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 594 at r2](https://reviewable.io/reviews/harness/harness-core/29988#-MtmZReV-UMswvYND3Mp:-MtmZv054hbNCxu9H4Aq:bv44mq4) ([raw file](https://github.com/harness/harness-core/blob/7179bb823056743dc392e0f8a161227ea7faf402/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L594)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

shouldn't this be !=0
</blockquote></details>

so, for this proj, we have already delete this yamlGitConfig, if no more yamlGitConfigs are prsent withe this repoUrl, we should delete its branches.

**Review by DeepakPatankar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29988#-:-Mtn0x3W-YXrr-9Zjepx:bnfp4nl)* status: 9 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 9 files at r1, 2 of 4 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29988#-:-Mts2Ltw-2W1r9DeYJIN:bnfp4nl)* status: 2 file(s) to review.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29988#-:-Mts2uB55AYw-VDLJgwr:bnfp4nl)* status: 2 file(s) to review.

**Pull request merged**
