### PR TITLE
feat: [SRM-12075]: Verify step enhacements backend changes.

### PR DESCRIPTION
**Pull request by naveen-harness**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38076)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* Code issue 7 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38076)

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38076)* status: 91 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/LearningEngineTask.java` line 114 at r2](https://reviewable.io/reviews/harness/harness-core/38076#-NDb6m8F19GHtIbLBR_J:-NDb6m8F19GHtIbLBR_K:bswu8dp) ([raw file](https://github.com/harness/harness-core/blob/d11d2897e09b5b9f45c5ff78196749c47fec1b68/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/LearningEngineTask.java#L114)):*
> ```Java
>     TIME_SERIES_CANARY,
>     CANARY,
>     IMPROVISED_CANARY,
> ```

Lets not name it IMPROVISED_CANARY -> BEFORE_AFTER_DEPLOYMENT_METRIC
CANARY -> CANARY_METRIC
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/38076#-NDb7OBk09tI1wxoTtyk:-NDb7OBk09tI1wxoTtyl:b-idgqt2) ([raw file](https://github.com/harness/harness-core/blob/d11d2897e09b5b9f45c5ff78196749c47fec1b68/300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java#L15)):*
> ```Java
>   public static final String CVNG_LICENSE_ENFORCEMENT = "CVNG_LICENSE_ENFORCEMENT";
> 
>   public static final String HOST_SAMPLING = "HOST_SAMPLING";
> ```

SRM_HOST_SAMPLING_ENABLE.
Also needs it in : https://github.com/harness/harness-core/blob/b789a301de44fc1a94643366f6ccc29366948908/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/beans/AnalysisState.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/38076#-NDb83-67sccoce1EuwK:-NDb83-67sccoce1EuwL:b-5yp2uz) ([raw file](https://github.com/harness/harness-core/blob/d11d2897e09b5b9f45c5ff78196749c47fec1b68/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/beans/AnalysisState.java#L37)):*
> ```Java
>     SERVICE_GUARD_TREND_ANALYSIS,
>     SLI_METRIC_ANALYSIS,
>     CANARY_ANALYSIS_STATE,
> ```

Single state might be enough. Deployment_metric_analysis
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/entities/HostSamplingState.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/38076#-NDb8XbMD5FjXK_1bzSL:-NDb8XbMD5FjXK_1bzSM:b-wmf2xh) ([raw file](https://github.com/harness/harness-core/blob/d11d2897e09b5b9f45c5ff78196749c47fec1b68/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/entities/HostSamplingState.java#L25)):*
> ```Java
>     protected Set<String> controlHosts;
>     protected Set<String> testHosts;
>     protected VerificationJobInstance verificationJobInstance;
> ```

Dont put verificationJobInstance as part of state
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/HostSamplingStateExecutor.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/38076#-NDb97YE3tk2eFYhiPmq:-NDb97YE3tk2eFYhiPmr:b-gpvsmw) ([raw file](https://github.com/harness/harness-core/blob/d11d2897e09b5b9f45c5ff78196749c47fec1b68/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/HostSamplingStateExecutor.java#L54)):*
> ```Java
>     Set<String> preDeploymentHosts = new HashSet<>();
>     Set<String> postDeploymentHosts = new HashSet<>();
>     for (TimeSeriesRecordDTO timeSeriesRecordDTO : preDeploymentTimeSeriesRecords) {
> ```

nit : use streams
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/HostSamplingStateExecutor.java` line 143 at r2](https://reviewable.io/reviews/harness/harness-core/38076#-NDbAenm7qzQfQibNh6Y:-NDbAenm7qzQfQibNh6Z:b130j1e) ([raw file](https://github.com/harness/harness-core/blob/d11d2897e09b5b9f45c5ff78196749c47fec1b68/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/HostSamplingStateExecutor.java#L143)):*
> ```Java
>   @Override
>   public AnalysisStatus getExecutionStatus(HostSamplingState analysisState) {
>     if (!analysisState.getControlHosts().isEmpty() && !analysisState.getTestHosts().isEmpty()) {
> ```

Or should be fine

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38076)* status: 104 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/CVServiceModule.java` line 1066 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtm5ZAAV8HQ2B6_Lwo:-NEtm5ZAAV8HQ2B6_Lwp:b-1e2u0g) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/CVServiceModule.java#L1066)):*
> ```Java
>         .to(HostSamplingStateExecutor.class)
>         .in(Scopes.SINGLETON);
>     stateTypeAnalysisStateExecutorMap.addBinding(StateType.CANARY_ANALYSIS_STATE)
> ```

Namining: DEPLOYMENT_TIME_SERIES_ANALYSIS_STATE
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/TimeSeriesCanaryLearningEngineTask_v2.java` line 17 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtma6T2KwfjGcZOv4x:-NEtma6T2KwfjGcZOv4y:bi7yazb) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/TimeSeriesCanaryLearningEngineTask_v2.java#L17)):*
> ```Java
> @EqualsAndHashCode(callSuper = true)
> public class TimeSeriesCanaryLearningEngineTask_v2 extends LearningEngineTask {
>   private String preDeploymentDataUrl;
> ```

controlDataUrl and testDataUrl
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/analysis/resources/TimeSeriesAnalysisResource.java` line 59 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtmrKuB8QhADUJDkW8:-NEtmrKuB8QhADUJDkW9:b-9n4nwu) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/resources/TimeSeriesAnalysisResource.java#L59)):*
> ```Java
>   getTimeSeriesRecords(@QueryParam("verificationTaskId") @NotNull String verificationTaskId,
>       @QueryParam("startTime") @NotNull Long startTime, @QueryParam("endTime") @NotNull Long endTime,
>       @QueryParam("controlHosts") String controlHosts, @QueryParam("testHosts") String testHosts) {
> ```

commaSeperatedControlHosts (Java variable)
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/api/TimeSeriesAnalysisService.java` line 40 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtnZifA1OfKM5DG3b7:-NEtnZifA1OfKM5DG3b8:b2596um) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/api/TimeSeriesAnalysisService.java#L40)):*
> ```Java
>   Map<String, Map<String, List<TimeSeriesAnomaliesDTO>>> getLongTermAnomalies(String verificationTaskId);
>   List<TimeSeriesMetricDefinition> getMetricTemplate(String cvConfigId);
>   List<TimeSeriesRecordDTO> getTimeSeriesRecordDTOs(String verificationTaskId, Instant startTime, Instant endTime);
> ```

@Deprecated
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/api/TimeSeriesAnalysisService.java` line 41 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtnVla6P0fB7MoxczL:-NEtnVla6P0fB7MoxczM:blc26y3) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/api/TimeSeriesAnalysisService.java#L41)):*
> ```Java
>   List<TimeSeriesMetricDefinition> getMetricTemplate(String cvConfigId);
>   List<TimeSeriesRecordDTO> getTimeSeriesRecordDTOs(String verificationTaskId, Instant startTime, Instant endTime);
>   List<TimeSeriesRecordDTO> getDeploymentMetricTimeSeriesRecordDTOs(
> ```

rename the variables
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/TimeSeriesAnalysisServiceImpl.java` line 383 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtoEDo9i4ZItN0NZDo:-NEtoEDo9i4ZItN0NZDp:bcyp00s) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/TimeSeriesAnalysisServiceImpl.java#L383)):*
> ```Java
>     uriBuilder.setPath(SERVICE_BASE_URL + "/" + TIMESERIES_ANALYSIS_RESOURCE + "/time-series-data");
>     uriBuilder.addParameter("verificationTaskId", input.getVerificationTaskId());
>     uriBuilder.addParameter("startTime", Long.toString(preDeploymentTimeRange.get().getStartTime().toEpochMilli()));
> ```

CARNARY -> controlData should be after deployment. 



_Code quote:_
```Java
CanaryBlueGreenVerificationJob
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/TimeSeriesRecordServiceImpl.java` line 529 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtpwuy9xRC1BoDXa9p:-NEtpwuy9xRC1BoDXa9q:b-avxjst) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/TimeSeriesRecordServiceImpl.java#L529)):*
> ```Java
>   @Override
>   public List<TimeSeriesRecordDTO> getDeploymentMetricTimeSeriesRecordDTOs(
>       String verificationTaskId, Instant startTime, Instant endTime, Set<String> controlHosts, Set<String> testHosts) {
> ```

Just need Set<String> hosts
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/TimeSeriesRecordServiceImpl.java` line 530 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtqBVgDyo8sfRK5UKb:-NEtqBVgDyo8sfRK5UKc:b-acvtzb) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/TimeSeriesRecordServiceImpl.java#L530)):*
> ```Java
>   public List<TimeSeriesRecordDTO> getDeploymentMetricTimeSeriesRecordDTOs(
>       String verificationTaskId, Instant startTime, Instant endTime, Set<String> controlHosts, Set<String> testHosts) {
>     List<TimeSeriesRecord> timeSeriesRecords = getTimeSeriesRecords(verificationTaskId, startTime, endTime);
> ```

Add this query to mongo only. 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/beans/AnalysisInput.java` line 27 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtr3QfCCmYyjHWW-kX:-NEtr3QfCCmYyjHWW-kY:b-hecy3i) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/beans/AnalysisInput.java#L27)):*
> ```Java
>   private Instant endTime;
>   private String verificationTaskId;
>   private String verificationJobInstanceId;
> ```

Just put a comment // Details for Deployment Analysis
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/HostSamplingStateExecutor.java` line 145 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtsc-L1atlSmCh-J3s:-NEtsc-M-PqfrxbDw0IT:b-r3u014) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/HostSamplingStateExecutor.java#L145)):*
> ```Java
>             /*
>               For example:
>               Pre deployment hosts are n1, n2
> ```

update example



_Code quote:_
```Java
    if (analysisState.getStatus() == AnalysisStatus.SUCCESS) {
      return AnalysisStatus.SUCCESS;
    }
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/AnalysisStateMachineServiceImpl.java` line 387 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtt16_22KsrcZt5BDi:-NEtt16_22KsrcZt5BDj:b-g11s03) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/AnalysisStateMachineServiceImpl.java#L387)):*
> ```Java
>           stateMachine.setCurrentState(testTimeSeriesAnalysisState);
>         } else {
>           CanaryTimeSeriesAnalysisState canaryTimeSeriesAnalysisState = CanaryTimeSeriesAnalysisState.builder().build();
> ```

If else: 
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/TimeSeriesAnalysisServiceImplTest.java` line 209 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEttQ7r3wCm1l52I4He:-NEttQ7r3wCm1l52I4Hf:but95qq) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/TimeSeriesAnalysisServiceImplTest.java#L209)):*
> ```Java
> 
>   @Test
>   @Owner(developers = PRAVEEN)
> ```

Update owners

**Review by naveen-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38076)* status: 104 file(s) to review. 1 change requests. 16. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/CVServiceModule.java` line 1066 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtm5ZAAV8HQ2B6_Lwo:-NF08hLHAdb2A1xOH8bI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/CVServiceModule.java#L1066)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Namining: DEPLOYMENT_TIME_SERIES_ANALYSIS_STATE
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/LearningEngineTask.java` line 114 at r2](https://reviewable.io/reviews/harness/harness-core/38076#-NDb6m8F19GHtIbLBR_J:-NF08ifJ7XMBs_ZEC_oK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d11d2897e09b5b9f45c5ff78196749c47fec1b68/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/LearningEngineTask.java#L114)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Lets not name it IMPROVISED_CANARY -> BEFORE_AFTER_DEPLOYMENT_METRIC
CANARY -> CANARY_METRIC
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/TimeSeriesCanaryLearningEngineTask_v2.java` line 17 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtma6T2KwfjGcZOv4x:-NF08jHl-7SIOzI8PfRR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/TimeSeriesCanaryLearningEngineTask_v2.java#L17)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

controlDataUrl and testDataUrl
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/analysis/resources/TimeSeriesAnalysisResource.java` line 59 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtmrKuB8QhADUJDkW8:-NF08k1w3da3-6O5qRTE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/resources/TimeSeriesAnalysisResource.java#L59)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

commaSeperatedControlHosts (Java variable)
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/api/TimeSeriesAnalysisService.java` line 41 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtnVla6P0fB7MoxczL:-NF08kuH46r9HIdKs6uf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/api/TimeSeriesAnalysisService.java#L41)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

rename the variables
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/TimeSeriesAnalysisServiceImpl.java` line 383 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtoEDo9i4ZItN0NZDo:-NF08m3MC4ye34mPZdBd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/TimeSeriesAnalysisServiceImpl.java#L383)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

CARNARY -> controlData should be after deployment. 
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/TimeSeriesRecordServiceImpl.java` line 529 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtpwuy9xRC1BoDXa9p:-NF08o3U2dnfQrGKfv8n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/TimeSeriesRecordServiceImpl.java#L529)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Just need Set<String> hosts
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/TimeSeriesRecordServiceImpl.java` line 530 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtqBVgDyo8sfRK5UKb:-NF08oJm8_y4p67af6QF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/TimeSeriesRecordServiceImpl.java#L530)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Add this query to mongo only. 
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/38076#-NDb7OBk09tI1wxoTtyk:-NF08p9HEhUwLOqOLX6i:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d11d2897e09b5b9f45c5ff78196749c47fec1b68/300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java#L15)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

SRM_HOST_SAMPLING_ENABLE.
Also needs it in : https://github.com/harness/harness-core/blob/b789a301de44fc1a94643366f6ccc29366948908/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/beans/AnalysisInput.java` line 27 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtr3QfCCmYyjHWW-kX:-NF08q0cA-mq6X91HGQr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/beans/AnalysisInput.java#L27)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Just put a comment // Details for Deployment Analysis
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/beans/AnalysisState.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/38076#-NDb83-67sccoce1EuwK:-NF08qpZ74F28LHhmpk-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d11d2897e09b5b9f45c5ff78196749c47fec1b68/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/beans/AnalysisState.java#L37)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Single state might be enough. Deployment_metric_analysis
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/entities/HostSamplingState.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/38076#-NDb8XbMD5FjXK_1bzSL:-NF08sICDyNcmoHr3hd9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d11d2897e09b5b9f45c5ff78196749c47fec1b68/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/entities/HostSamplingState.java#L25)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Dont put verificationJobInstance as part of state
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/HostSamplingStateExecutor.java` line 143 at r2](https://reviewable.io/reviews/harness/harness-core/38076#-NDbAenm7qzQfQibNh6Y:-NF08v292ziFZcd2XUNV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d11d2897e09b5b9f45c5ff78196749c47fec1b68/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/HostSamplingStateExecutor.java#L143)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Or should be fine
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/HostSamplingStateExecutor.java` line 145 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtsc-L1atlSmCh-J3s:-NF08wXj0p4MvpnFTWkh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/HostSamplingStateExecutor.java#L145)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

update example
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/AnalysisStateMachineServiceImpl.java` line 387 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtt16_22KsrcZt5BDi:-NF08xsM02Up8xploG4P:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/AnalysisStateMachineServiceImpl.java#L387)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

If else: 
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/TimeSeriesAnalysisServiceImplTest.java` line 209 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEttQ7r3wCm1l52I4He:-NF09-YBA1XHITkXLH1X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/TimeSeriesAnalysisServiceImplTest.java#L209)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Update owners
</blockquote></details>

Done.

**Comment by naveen-harness** [comment]
trigger messagecheck

**Comment by naveen-harness** [comment]
trigger messagecheck

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 3 of 11 files at r3, 16 of 18 files at r4, 58 of 62 files at r5, 1 of 2 files at r6, 5 of 22 files at r7, 6 of 15 files at r8, 14 of 14 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38076)* status: :shipit: complete! ✓

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/TimeSeriesCanaryLearningEngineTask_v2.java` line 17 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtma6T2KwfjGcZOv4x:-NFCSii864RskVxW0Sfa:b-51cfx7) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/TimeSeriesCanaryLearningEngineTask_v2.java#L17)):*
<details><summary><i>Previously, naveen-harness (Naveen Shukla) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: we dont need preDeployment and postDeployment Data URLs if we are changing it from the start only\\

**Review by AbhijithHarness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38076)* status: :shipit: complete! ✓

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/TimeSeriesCanaryLearningEngineTask_v2.java` line 17 at r7](https://reviewable.io/reviews/harness/harness-core/38076#-NEtma6T2KwfjGcZOv4x:-NFCdbcwDwySRvDHLHgy:bjus68m) ([raw file](https://github.com/harness/harness-core/blob/82345fde91ca316d16127b282d789600a985d32a/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/TimeSeriesCanaryLearningEngineTask_v2.java#L17)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

nit: we dont need preDeployment and postDeployment Data URLs if we are changing it from the start only\\
</blockquote></details>

nit: atleast use @Deprecated

**Pull request closed without merging**
