### PR TITLE
feat: [SRM-13159]: Refactoring SLO V2 APIs. API signature changes, Swagger changes, Request changes

### PR DESCRIPTION
**Pull request by sathish-soundarapandian**
## Describe your changes
Refactoring SLO V2 APIs. API signature changes, Swagger changes, Request changes

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41225)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41225)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java` line 268 at r2](https://reviewable.io/reviews/harness/harness-core/41225#-NIgkevGEFoLHZz4x-se:-NIgkevGEFoLHZz4x-sf:b-eyvfl7) ([raw file](https://github.com/harness/harness-core/blob/901a5830b51456ab16d293b00597c8a0be3bf3c5/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java#L268)):*
> ```Java
>       responses = { @io.swagger.v3.oas.annotations.responses.ApiResponse(description = "Gets the SLO's data") })
>   @NGAccessControlCheck(resourceType = SLO, permission = VIEW_PERMISSION)
>   public RestResponse<ServiceLevelObjectiveV2Response>
> ```

Lets add the widget/list api too with /status-list rest end point

**Comment by sathish-soundarapandian** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/41225)_ status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java` line 268 at r2](https://reviewable.io/reviews/harness/harness-core/41225#-NIgkevGEFoLHZz4x-se:-NIgkevGEFoLHZz4x-sf:b-eyvfl7) ([raw file](https://github.com/harness/harness-core/blob/901a5830b51456ab16d293b00597c8a0be3bf3c5/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java#L268)):_
> 
> > ```java
> >       responses = { @io.swagger.v3.oas.annotations.responses.ApiResponse(description = "Gets the SLO's data") })
> >   @NGAccessControlCheck(resourceType = SLO, permission = VIEW_PERMISSION)
> >   public RestResponse<ServiceLevelObjectiveV2Response>
> > ```
> 
> Lets add the widget/list api too with /status-list rest end point

Done

**Comment by sathish-soundarapandian** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/41225)_ status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/core/services/CVNextGenConstants.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/41225#-NIgeq6K1RoPbrx8WGOJ:-NIgeq6K1RoPbrx8WGOK:b-9jnbgb) ([raw file](https://github.com/harness/harness-core/blob/901a5830b51456ab16d293b00597c8a0be3bf3c5/948-cv-nextgen-beans/src/main/java/io/harness/cvng/core/services/CVNextGenConstants.java#L48)):_
> 
> > ```java
> >   String PROJECT_PATH = "account/{" + ACCOUNT_IDENTIFIER_KEY + "}/org/{" + ORG_IDENTIFIER_KEY + "}/project/{"
> >       + PROJECT_IDENTIFIER_KEY + "}";
> >   String PROJECT_PATH_WITH_RESOURCE_IDENTIFIER = PROJECT_PATH + "/identifier/{" + RESOURCE_IDENTIFIER_KEY + "}";
> > ```
> 
> ACCOUNT_PATH ACCOUNT_PATH_WITH_RESOURCE_IDENTIFIER ORG_PATH ORG_PATH_WITH_RESOURCE_IDENTIFIER
> 
> _[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/HealthSourceSpec.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/41225#-NIgfZNd1WcLCmWzJbHs:-NIgfZNd1WcLCmWzJbHt:b-ec2rav) ([raw file](https://github.com/harness/harness-core/blob/901a5830b51456ab16d293b00597c8a0be3bf3c5/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/HealthSourceSpec.java#L51)):_
> 
> > ```java
> >       @JsonSubTypes.Type(value = AwsPrometheusHealthSourceSpec.class, name = "AwsPrometheus")
> > })
> > @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = DATA_SOURCE_TYPE, include = JsonTypeInfo.As.EXTERNAL_PROPERTY)
> > ```
> 
> SLOTargetDTO CalenderSpec ServiceLevelIndicatorSpec ChangeSourceDTO MetricThresholdSpec
> 
> _[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/41225#-NIggobNAe7txVqyKsMQ:-NIggobO57avqyKlvccd:b-xdr84z) ([raw file](https://github.com/harness/harness-core/blob/901a5830b51456ab16d293b00597c8a0be3bf3c5/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java#L87)):_
> 
> > ```java
> > //    })
> > @OwnedBy(HarnessTeam.CV)
> > public class ServiceLevelObjectiveV2Resource {
> > ```
> 
> pathParam ServiceLevelObjectiveV2Resource

Done

**Review by deepak-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41225)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java` line 87 at r3](https://reviewable.io/reviews/harness/harness-core/41225#-NIpDRTm31bpn8hrfHfr:-NIpDRTm31bpn8hrfHfs:bdb4a09) ([raw file](https://github.com/harness/harness-core/blob/54dee6e9950cf3ea734829490551d8d9be3c1ef2/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java#L87)):*
> ```Java
>           @Content(mediaType = NGCommonEntityConstants.APPLICATION_YAML_MEDIA_TYPE,
>               schema = @Schema(implementation = ErrorDTO.class))
>     })*/
> ```

we should uncomment it.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java` line 102 at r3](https://reviewable.io/reviews/harness/harness-core/41225#-NIpFGEDD7TbClYObEV4:-NIpFGEDD7TbClYObEV5:b-6cob18) ([raw file](https://github.com/harness/harness-core/blob/54dee6e9950cf3ea734829490551d8d9be3c1ef2/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java#L102)):*
> ```Java
>   @Timed
>   @ExceptionMetered
>   @Path(PROJECT_PATH + "/composite-slo/onboarding-graph")
> ```

move the PROJECT_PATH to the class level
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java` line 278 at r3](https://reviewable.io/reviews/harness/harness-core/41225#-NIpF_sE8gIN6lTj8pv6:-NIpF_sE8gIN6lTj8pv7:bufq436) ([raw file](https://github.com/harness/harness-core/blob/54dee6e9950cf3ea734829490551d8d9be3c1ef2/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java#L278)):*
> ```Java
>   }
> 
>   private static void foolProofCheck(
> ```

rename to validations

**Comment by sathish-soundarapandian** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/41225)_ status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java` line 87 at r3](https://reviewable.io/reviews/harness/harness-core/41225#-NIpDRTm31bpn8hrfHfr:-NIpDRTm31bpn8hrfHfs:bdb4a09) ([raw file](https://github.com/harness/harness-core/blob/54dee6e9950cf3ea734829490551d8d9be3c1ef2/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java#L87)):_
> 
> > ```java
> >           @Content(mediaType = NGCommonEntityConstants.APPLICATION_YAML_MEDIA_TYPE,
> >               schema = @Schema(implementation = ErrorDTO.class))
> >     })*/
> > ```
> 
> we should uncomment it.
> 
> _[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java` line 102 at r3](https://reviewable.io/reviews/harness/harness-core/41225#-NIpFGEDD7TbClYObEV4:-NIpFGEDD7TbClYObEV5:b-6cob18) ([raw file](https://github.com/harness/harness-core/blob/54dee6e9950cf3ea734829490551d8d9be3c1ef2/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java#L102)):_
> 
> > ```java
> >   @Timed
> >   @ExceptionMetered
> >   @Path(PROJECT_PATH + "/composite-slo/onboarding-graph")
> > ```
> 
> move the PROJECT_PATH to the class level
> 
> _[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java` line 278 at r3](https://reviewable.io/reviews/harness/harness-core/41225#-NIpF_sE8gIN6lTj8pv6:-NIpF_sE8gIN6lTj8pv7:bufq436) ([raw file](https://github.com/harness/harness-core/blob/54dee6e9950cf3ea734829490551d8d9be3c1ef2/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java#L278)):_
> 
> > ```java
> >   }
> > 
> >   private static void foolProofCheck(
> > ```
> 
> rename to validations

Done

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 5 of 7 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41225)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/core/services/CVNextGenConstants.java` line 51 at r5](https://reviewable.io/reviews/harness/harness-core/41225#-NJ3qKNU9KLpvUu4akHf:-NJ3qKNU9KLpvUu4akHg:b-yf5a9a) ([raw file](https://github.com/harness/harness-core/blob/39d594c67425828e00b36baccce036a6add46af0/948-cv-nextgen-beans/src/main/java/io/harness/cvng/core/services/CVNextGenConstants.java#L51)):*
> ```Java
>   String ACCOUNT_PATH = "account/{" + ACCOUNT_IDENTIFIER_KEY + "}";
>   String ACCOUNT_PATH_WITH_RESOURCE_IDENTIFIER =
>       ACCOUNT_PATH + SLASH_DELIMITER + RESOURCE_IDENTIFIER_KEY_PATH + "{" + RESOURCE_IDENTIFIER_KEY + "}";
> ```

nit: We are using /, {, } and SLASH_DELIMITER. We should either use constants for all of these or use the characters themselves.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java` line 119 at r5](https://reviewable.io/reviews/harness/harness-core/41225#-NJ3rUQt8REVsbHWI9ji:-NJ3rUQt8REVsbHWI9jj:bulak4m) ([raw file](https://github.com/harness/harness-core/blob/39d594c67425828e00b36baccce036a6add46af0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java#L119)):*
> ```Java
>   @NGAccessControlClientCheck
>   public RestResponse<TimeGraphResponse>
>   getOnboardingGraphNg(@PathParam(CVNextGenConstants.ACCOUNT_IDENTIFIER_KEY) @ApiParam(
> ```

Can we define a wrapper for the path params as these will be commonly used across multiple APIs, like we have ProjectParams.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 5 of 7 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41225)* status: :shipit: complete! ✓

**Comment by sathish-soundarapandian** [comment]
> > Reviewed 2 of 2 files at r1, 5 of 7 files at r3, 2 of 2 files at r5, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/41225)_ status: 1. unresolved discussions. 0 of 1 approvals obtained.
> 
> _[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/core/services/CVNextGenConstants.java` line 51 at r5](https://reviewable.io/reviews/harness/harness-core/41225#-NJ3qKNU9KLpvUu4akHf:-NJ3qKNU9KLpvUu4akHg:b-yf5a9a) ([raw file](https://github.com/harness/harness-core/blob/39d594c67425828e00b36baccce036a6add46af0/948-cv-nextgen-beans/src/main/java/io/harness/cvng/core/services/CVNextGenConstants.java#L51)):_
> 
> > ```java
> >   String ACCOUNT_PATH = "account/{" + ACCOUNT_IDENTIFIER_KEY + "}";
> >   String ACCOUNT_PATH_WITH_RESOURCE_IDENTIFIER =
> >       ACCOUNT_PATH + SLASH_DELIMITER + RESOURCE_IDENTIFIER_KEY_PATH + "{" + RESOURCE_IDENTIFIER_KEY + "}";
> > ```
> 
> nit: We are using /, {, } and SLASH_DELIMITER. We should either use constants for all of these or use the characters themselves.
> 
> _[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java` line 119 at r5](https://reviewable.io/reviews/harness/harness-core/41225#-NJ3rUQt8REVsbHWI9ji:-NJ3rUQt8REVsbHWI9jj:bulak4m) ([raw file](https://github.com/harness/harness-core/blob/39d594c67425828e00b36baccce036a6add46af0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java#L119)):_
> 
> > ```java
> >   @NGAccessControlClientCheck
> >   public RestResponse<TimeGraphResponse>
> >   getOnboardingGraphNg(@PathParam(CVNextGenConstants.ACCOUNT_IDENTIFIER_KEY) @ApiParam(
> > ```
> 
> Can we define a wrapper for the path params as these will be commonly used across multiple APIs, like we have ProjectParams.

Done

**Review by dhruv-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41225)* status: :shipit: complete! ✓

**Comment by sathish-soundarapandian** [comment]
trigger ti1, ti3, checkstylecodeformat

**Comment by sathish-soundarapandian** [comment]
trigger ti3, checkstylecodeformat

**Comment by sathish-soundarapandian** [comment]
trigger ti1

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41225)* status: :shipit: complete! ✓

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java` line 63 at r6](https://reviewable.io/reviews/harness/harness-core/41225#-NJ8t3lhE4K1c3zRW9o7:-NJ8t3lhE4K1c3zRW9o8:bkiw59x) ([raw file](https://github.com/harness/harness-core/blob/0ffeaea346a206d6740d7c05727fb97417d77a7d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java#L63)):*
> ```Java
> 
> @Api(SLO_NG_PATH)
> @Path(SLO_NG_PATH)
> ```

Since this is a project path, have we planned to create new resource for account scoped? If yes then, why not in the same PR?



_Code quote:_
```Java
@Api(SLO_NG_PATH)
@Path(SLO_NG_PATH)
```

**Comment by sathish-soundarapandian** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/41225)_ status: :shipit: complete! ✓
> 
> _[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java` line 63 at r6](https://reviewable.io/reviews/harness/harness-core/41225#-NJ8t3lhE4K1c3zRW9o7:-NJ8t3lhE4K1c3zRW9o8:bkiw59x) ([raw file](https://github.com/harness/harness-core/blob/0ffeaea346a206d6740d7c05727fb97417d77a7d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveNgResource.java#L63)):_
> 
> > ```java
> > @Api(SLO_NG_PATH)
> > @Path(SLO_NG_PATH)
> > ```
> 
> Since this is a project path, have we planned to create new resource for account scoped? If yes then, why not in the same PR?
> 
> _Code quote:_
> 
> ```java
> @Api(SLO_NG_PATH)
> @Path(SLO_NG_PATH)
> ```

Done

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 5 of 7 files at r3, 2 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41225#-:-NJ9DMLIBN8LyKuM-65M:bnfp4nl)* status: 1. unresolved discussions.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41225)* status: 1. unresolved discussions.

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41225#-:-NJ9nTj5D9QJ4169niiX:bnfp4nl)* status: 1. unresolved discussions.

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41225#-:-NJ9tu_y9pQZRoCHHcBV:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
