### PR TITLE
[feat]: [PIE-3974]: Execution input with default and allowedValules

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

Recently we added support for executionInputs in pipeline for normal inputs. This pr extends the executionInputs with allowedValues validator. And adds new constructs support of providing default for execution inputs.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33981)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger feature-build

**Comment by brijeshdhakar** [comment]
trigger ti3 ti1

**Comment by brijeshdhakar** [comment]
trigger feature-build

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 16 files at r1, 1 of 1 files at r2, 4 of 8 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33981)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 125 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wSTFO7xbtShEJQzpe:-N3wSTFO7xbtShEJQzpf:b-gkw6tb) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L125)):*
> ```Java
>     }
>     ExecutionInputInstance executionInputInstance = executionInputService.getExecutionInputInstance(nodeExecutionId);
>     // TODO(BRIJESH): Write mapper to convert entity to DTO.
> ```

todo can be deleted



_Code quote:_
```Java
// TODO(BRIJESH): Write mapper to convert entity to DTO
```
___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 119 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wUfZYEnvbUVyemqjK:-N3wUfZYEnvbUVyemqjL:b276h91) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L119)):*
> ```Java
>         return appendedValidator;
>       }
>       ParameterField<?> inputSetParameterField = YamlUtils.read(inputSetValueText, ParameterField.class);
> ```

dont deserialise yourself, use RuntimeInputValuesValidator#getInputSetParameterField as it handles empty string and in future if any edge case, if your input value is empty above deserialisation fails if directly converting to parameterField.



_Code quote:_
```Java
ParameterField<?> inputSetParameterField = YamlUtils.read(inputSetValueText, ParameterField.class);
```
___
*[`970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java` line 58 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wcrXCA4u-Q40VHWqr:-N3wcrXCA4u-Q40VHWqs:b-bfcidt) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java#L58)):*
> ```Java
>   }
> 
>   public static <T> ParameterField<T> createExpressionFieldWithDefault(boolean isExpression, String expressionValue,
> ```

createFieldWithDefaultValue



_Code quote:_
```Java
createExpressionFieldWithDefault
```
___
*[`970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java` line 63 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wcuL5-XVLaWuAGwDv:-N3wcuL5-XVLaWuAGwDw:b-bfcidt) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java#L63)):*
> ```Java
>   }
> 
>   public static <T> ParameterField<T> createExpressionFieldWithDefault(boolean isExpression, boolean isExecutionInput,
> ```

createFieldWithDefaultValue



_Code quote:_
```Java
createExpressionFieldWithDefault
```
___
*[`970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java` line 93 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wczLb-efBxLylTG_i:-N3wczLb-efBxLylTG_j:b-y4alt8) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java#L93)):*
> ```Java
>       String defaultValue = NGRuntimeInputUtils.extractParameters(text, "default");
>       boolean isExecutionInput = NGExpressionUtils.matchesExecutionInputPattern(text);
>       return ParameterField.createExpressionFieldWithDefault(defaultValue == null, isExecutionInput,
> ```

add comment that if default value then keep flag off as people would treat them as final value., this would be useful for default value only in runtime input, for execution input default value would come always from expression resolution.



_Code quote:_
```Java
defaultValue == null
```
___
*[`970-ng-commons/src/test/java/io/serializer/jackson/ParameterFieldDeserializerTest.java` line 35 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wVHdY4TgWymTyGgKA:-N3wVHdY4TgWymTyGgKB:b-g6hpge) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/test/java/io/serializer/jackson/ParameterFieldDeserializerTest.java#L35)):*
> ```Java
> public class ParameterFieldDeserializerTest extends CategoryTest implements MultilineStringMixin {
>   private ObjectMapper objectMapper;
>   @InjectMocks ParameterFieldDeserializer parameterFieldDeserializer;
> ```

where you are using deserialiser here?



_Code quote:_
```Java
@InjectMocks ParameterFieldDeserializer parameterFieldDeserializer;
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33981)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3whqWg7478Y988rdy2:-N3whqWg7478Y988rdy3:b-u9csq4) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java#L59)):*
> ```Java
> 
>   private String createExecutionInputFormInternal(
>       YamlConfig yamlConfig, boolean shouldUpdateCurrentField, boolean shouldReplaceWithDefaultValue) {
> ```

does this flag means that if value is not given then replace with default value? is this only for runtime inputs? if yes then why do we need to make expression flag false if runtime input and value not given?



_Code quote:_
```Java
shouldReplaceWithDefaultValue
```
___
*[`970-ng-commons/src/main/java/io/harness/utils/NGRuntimeInputUtils.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wiVPV0IDjWqn7LbFp:-N3wiVPV0IDjWqn7LbFq:bxkga3d) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/main/java/io/harness/utils/NGRuntimeInputUtils.java#L23)):*
> ```Java
>   public String extractParameters(String text, String validatorTypeString) {
>     String defaultValueString = null;
>     // Checking the pattern when field ends with .default(*)
> ```

should be textValue and not default as its generic or only create it for default



_Code quote:_
```Java
default
```
___
*[`970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java` line 30 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wjSzQCgtX7qOTrOU0:-N3wjSzQCgtX7qOTrOU1:b-7epam5) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java#L30)):*
> ```Java
>     String defaultString = "default";
>     assertEquals("\"value\"", NGRuntimeInputUtils.extractParameters(text, defaultString));
>     text = "<+input>.default(\"value\").executionInput()";
> ```

test for first executionInput then default?



_Code quote:_
```Java
default(\"value\").executionInput()
```
___
*[`970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java` line 38 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wjOKnDT5NGIY1gvzp:-N3wjOKnDT5NGIY1gvzq:b-ve9jpo) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java#L38)):*
> ```Java
>       assertEquals("\"value\"", NGRuntimeInputUtils.extractParameters(text, defaultString));
>     }
> ```

can you add test for reverse as well that is first validator then default?



_Code quote:_
```Java
    for (InputSetValidatorType validatorType : InputSetValidatorType.values()) {
      text = "<+input>.default(\"value\")." + validatorType.getYamlName() + "(\"random\")";
      assertEquals("\"value\"", NGRuntimeInputUtils.extractParameters(text, defaultString));
    }
```
___
*[`970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java` line 45 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wj-4mBkvhmdJkA5sm:-N3wj-4mBkvhmdJkA5sn:buntun2) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java#L45)):*
> ```Java
>         "\"random\"", NGRuntimeInputUtils.extractParameters(text, InputSetValidatorType.ALLOWED_VALUES.getYamlName()));
> 
>     text = "<+input>.allowedValues(\"random\").default(\"value\").executionInput()";
> ```

can you add one more test, allowedValues then executionInput then default?



_Code quote:_
```Java
text = "<+input>.allowedValues(\"random\").default(\"value\").executionInput()";
```
___
*[`970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java` line 51 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wjafuEK-kDSGDUEg_:-N3wjafuEK-kDSGDUEga:b-31ee2) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java#L51)):*
> ```Java
> 
>     // testing default and allowedValues after executionInput()
>     text = "<+input>.executionInput().default(\"value\").allowedValues(\"random\")";
> ```

executionInput then validator then default



_Code quote:_
```Java
executionInput().default(\"value\").allowedValues(\"random\")"
```
___
*[`970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java` line 57 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wjDFA80oJGSpZCZa2:-N3wjDFA80oJGSpZCZa3:b-i8hay1) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java#L57)):*
> ```Java
> 
>     // Testing allowedValue with regex inputset validator pattern.
>     text = "<+input>.allowedValues(\"value\")." + InputSetValidatorType.REGEX.getYamlName() + "(\"random\")";
> ```

both allowed Values and regex should not be allowed



_Code quote:_
```Java
allowedValues(\"value\")." + InputSetValidatorType.REGEX.getYamlName() +
```

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33981)* status: 19 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 125 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wSTFO7xbtShEJQzpe:-N3xGkxVAhCEySnlD7he:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L125)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

todo can be deleted
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 119 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wUfZYEnvbUVyemqjK:-N3xnSZm13HE7OLB83QG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L119)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dont deserialise yourself, use RuntimeInputValuesValidator#getInputSetParameterField as it handles empty string and in future if any edge case, if your input value is empty above deserialisation fails if directly converting to parameterField.
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3whqWg7478Y988rdy2:-N3xpgPl2AgVJw4JU8uW:bbn7bbm) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java#L59)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

does this flag means that if value is not given then replace with default value? is this only for runtime inputs? if yes then why do we need to make expression flag false if runtime input and value not given?
</blockquote></details>

This is when we are creating the template for execution input. In execution input we want to provide template with pre-filled default values. But in normal Runtime inputs, we give the complete expression in template.



_Code quote:_
```Java
createExecutionInputFormInternal
```
___
*[`970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java` line 58 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wcrXCA4u-Q40VHWqr:-N3xqL7A7L9rgg3evSbp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java#L58)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

createFieldWithDefaultValue
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java` line 63 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wcuL5-XVLaWuAGwDv:-N3xqLnh29KoybkFT9Sv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/main/java/io/harness/pms/yaml/ParameterField.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

createFieldWithDefaultValue
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/utils/NGRuntimeInputUtils.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wiVPV0IDjWqn7LbFp:-N3xI4LO2-cMdYifdBZd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/main/java/io/harness/utils/NGRuntimeInputUtils.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should be textValue and not default as its generic or only create it for default
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java` line 93 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wczLb-efBxLylTG_i:-N3xnPKcAP7dDfm7vNko:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java#L93)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comment that if default value then keep flag off as people would treat them as final value., this would be useful for default value only in runtime input, for execution input default value would come always from expression resolution.
</blockquote></details>

Done.
___
*[`970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java` line 30 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wjSzQCgtX7qOTrOU0:-N3xlb9E7G7wIfH6NSPy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java#L30)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

test for first executionInput then default?
</blockquote></details>

Done.
___
*[`970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java` line 38 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wjOKnDT5NGIY1gvzp:-N3xJjgz1s-QC775yg-D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java#L38)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you add test for reverse as well that is first validator then default?
</blockquote></details>

Done.
___
*[`970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java` line 45 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wj-4mBkvhmdJkA5sm:-N3xm47Y4YUWDTlKpgJB:b-btv871) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java#L45)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you add one more test, allowedValues then executionInput then default?
</blockquote></details>

Done. Added all the combinations of all three.
___
*[`970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java` line 51 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wjafuEK-kDSGDUEg_:-N3xm9E48HZpwTWsOpsF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java#L51)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

executionInput then validator then default
</blockquote></details>

Done.
___
*[`970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java` line 57 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wjDFA80oJGSpZCZa2:-N3xIrW985Ps93oyX1yR:b-hr1gep) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/test/java/io/harness/utils/NGRuntimeInputUtilsTest.java#L57)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

both allowed Values and regex should not be allowed
</blockquote></details>

The purpose of this method is only to extract value inside a validator pattern. I think this should not be aware of the logic that allowedValue and Regex should not come together. This logic must be inside the validator only.
___
*[`970-ng-commons/src/test/java/io/serializer/jackson/ParameterFieldDeserializerTest.java` line 35 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3wVHdY4TgWymTyGgKA:-N3xnR6BEitBVzIC54Lq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/970-ng-commons/src/test/java/io/serializer/jackson/ParameterFieldDeserializerTest.java#L35)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

where you are using deserialiser here?
</blockquote></details>

Done.

**Comment by brijeshdhakar** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3whqWg7478Y988rdy2:-N3xqu2CDz39k0fPrkql:brhafbu) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java#L59)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

This is when we are creating the template for execution input. In execution input we want to provide template with pre-filled default values. But in normal Runtime inputs, we give the complete expression in template.
</blockquote></details>

And we are using the same code flow. So added this flag in method for using the same common method for both.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 2 of 16 files at r1, 1 of 8 files at r3, 7 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33981)* status: 20 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 7 of 16 files at r1, 1 of 8 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33981)* status: 17 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33981)* status: 16 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3whqWg7478Y988rdy2:-N40pfy46DzHEpHRYkoT:b-o70tj6) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java#L59)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

And we are using the same code flow. So added this flag in method for using the same common method for both.
</blockquote></details>

Discussed offline, needs to check with UI, for executionInput, we should not return only default value.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33981)* status: 15 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/33981#-N3whqWg7478Y988rdy2:-N41OPaN7zUolQo3kJv9:b-nfbr1) ([raw file](https://github.com/harness/harness-core/blob/3da76e27e1c3005e269307c28d6bac00fc1babbd/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java#L59)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Discussed offline, needs to check with UI, for executionInput, we should not return only default value.
</blockquote></details>

Done. Removed this code as. We will not be field with default value in execution input template. We will send the complete expression like normal Runtime input template.

**Comment by brijeshdhakar** [comment]
Codebase hash changes:
No changes in kryo registrars and protos. Not sure why the codebase hash changed in this PR.

All the changes in this pr are completely in pipeline service.
This will not affect delegate communication.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33981)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 16 files at r1, 1 of 1 files at r2, 3 of 8 files at r3, 6 of 8 files at r5, 1 of 1 files at r6, 5 of 9 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33981)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33981)* status: 4 file(s) to review.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33981#-:-N41dpBJC04qAOKNspNJ:bnfp4nl)* status: 2 file(s) to review.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33981#-:-N41dxCB4QZ1YFeTDaQa:bnfp4nl)* status: 2 file(s) to review.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33981#-:-N41eGJFBqvCGbDQ51Lx:bnfp4nl)* status: 2 file(s) to review.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 2 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33981)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33981)* status: :shipit: complete! ✓

**Pull request merged**
