### PR TITLE
[feat]: [PIE-9619]: Remove PRB executions from Executions list view and recent executions

### PR DESCRIPTION
**Pull request by namanvermah**
Other Changes:
1. Remove execution graph from parent if rollback graph has execution graph
2. Add a comment in pipeline executor

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46430)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46430)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/46430#-NTDP8G65E8jEPqfkOLW:-NTDP8G65E8jEPqfkOLX:bss8bss) ([raw file](https://github.com/harness/harness-core/blob/e74cc3962b77b89f75ee7d53e5e0e0fb2ea666c9/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L148)):*
> ```Java
> 
>     criteria.and(PlanExecutionSummaryKeys.isLatestExecution).ne(!isLatest);
>     criteria.and(PlanExecutionSummaryKeys.executionMode).ne(ExecutionMode.PIPELINE_ROLLBACK);
> ```

this query will be costly for all executions page

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46430)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/46430#-NTDP8G65E8jEPqfkOLW:-NTDf8VLC83U46ZTlG9s:b-z4wqc3) ([raw file](https://github.com/harness/harness-core/blob/e74cc3962b77b89f75ee7d53e5e0e0fb2ea666c9/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L148)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this query will be costly for all executions page
</blockquote></details>

Removed for now, will test this query on QA first and see the performance metrics, and then go about merging

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46430)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46430)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
trigger review

**Pull request merged**
