### PR TITLE
techdebt: [PL-24694]: Separate Feature Build for Platform Service

### PR DESCRIPTION
**Pull request by ankit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32356)

### CODE REVIEW

**Comment by ankit-harness** [comment]
trigger messagecheck

**Comment by ankit-harness** [comment]
trigger messagecheck

**Review by gupta-utkarsh — APPROVED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32356)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32356#-:-N09dT1V3ShrTWqDxi2f:bnfp4nl)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32356)* status: :shipit: complete! ✓

**Pull request merged**
