### PR TITLE
fix: [PL-43414]: Add notification management permission to Account Admin

### PR DESCRIPTION
**Pull request by namanharness**
## Describe your changes

adding Notification management role to account admin 
file reference: platform-service/modules/notification-service/src/main/java/io/harness/notification/utils/NotificationManagementServicePermission.java

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56481)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56481)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 735 at r1](https://reviewable.io/reviews/harness/harness-core/56481#-Nl45qIJ6H9bJPQ0Vvkp:-Nl45qIJ6H9bJPQ0Vvkq:bs159dj) ([raw file](https://github.com/harness/harness-core/blob/d6349e8c4847b82e207e9bcaa0d813de154a9412/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L735)):*
> ```YAML
>         - iac_workspace_view
>         - core_notification_management_view
>         - core_notification_management_edit
> ```

This permissions are not added to permissions.yml.

Please follow permissions lifecycle.
https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21060812887/Permissions+Management

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/56481)_ status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1883 at r3](https://reviewable.io/reviews/harness/harness-core/56481#-Nl6vMt2E6Fu93GvDrcX:-Nl6vMt2E6Fu93GvDrcY:bupgxdo) ([raw file](https://github.com/harness/harness-core/blob/007a4fdc2a1a656fbd4ed6f2bd69346fea00c965/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1883)):_
> 
> > ```yaml
> >       - organization
> >       - project
> >   - identifier: core_notification_management_view
> > ```
> 
> I think we should have just core_notification_view, core_notification_edit and core_notification_delete

You mean remove management?

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56481)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by jennyjames21** [comment]
trigger uts

**Review by ashishsanodia-harness — COMMENTED** [review]
@namanharness   This change requires version increment for both permissions.yml and managed-roles.yml
cc: @Jimit09Gandhi 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56481#-:-Nl754xD4PU4fAjS4Nzh:bvpkbas)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by jennyjames21** [comment]
yes, naman already added that file when jimit reviewed. i did force push, so adding version back

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger ut3

**Pull request closed without merging**
