### PR TITLE
feat: [CDS-39569]: CG - Make it possible to specify App/Env/Services exceptions for deployment freeze windows 

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes

This PR implements the possibility of specifying exceptions for deployment freeze windows.

In the same way that the user can pass `appSelections` filters in CG's `compliance-config` API payloads, this PR makes it possible to send a `excludeAppSelections` field that contains specifies which Apps, Envs or Services will be excluded from deployment freezes. 

Parsing of the new `excludeAppSelections` field only happens when the new feature flag `SPG_NEW_DEPLOYMENT_FREEZE_EXCLUSIONS` is enabled, which in turn depends on `NEW_DEPLOYMENT_FREEZE` feature flag being enabled.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36150)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* Code issue 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36150)

**Comment by vcalasansh** [comment]
trigger ti0

**Comment by vcalasansh** [comment]
trigger ti3

**Comment by vcalasansh** [comment]
trigger ti3

**Comment by vcalasansh** [comment]
trigger ti4

**Comment by vcalasansh** [comment]
trigger ti0

**Review by Fernando-Dourado — COMMENTED** [review]
> Reviewed 10 of 22 files at r1, 2 of 3 files at r2, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36150)* status: 10 file(s) to review. 0 of 1 approvals obtained.

**Review by Fernando-Dourado — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36150)* status: 10 file(s) to review.

**Review by Fernando-Dourado — APPROVED** [review]
:lgtm:

> Reviewed 8 of 22 files at r1, 1 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36150#-:-NDEp5g09Yq7PyAUZy6D:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
