### PR TITLE
feat: [CDS-49235]: ASG Git subset manifest content support

### PR DESCRIPTION
**Pull request by vitsafronovici**
## Describe your changes
Added support for fetching Git subset manifests files. Fetching is done in async way by chaining delegate tasks until all manifests are fetched .
Affected swimlanes: ASG 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41971)

### CODE REVIEW

**Review by lovish1999 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41971)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java` line 229 at r1](https://reviewable.io/reviews/harness/harness-core/41971#-NKqtUHm88vk2bwhHeiK:-NKqtUHm88vk2bwhHeiL:b-o4gjtm) ([raw file](https://github.com/harness/harness-core/blob/7ae9e2448fc010a1b80a5ffe763667c12b991596/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java#L229)):*
> ```Java
>                                    .stream()
>                                    .filter(f -> isNotEmpty(f.getFiles()))
>                                    .map(f -> f.getFiles().get(0).getFileContent())
> ```

This can have multiple Files, right? (For ex: in scaling policies)

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41971)* status: 1 of 2 approvals obtained.

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java` line 219 at r1](https://reviewable.io/reviews/harness/harness-core/41971#-NKqvK-OB6qT0-oPHg2M:-NKqvK-OB6qT0-oPHg2N:b43pbkl) ([raw file](https://github.com/harness/harness-core/blob/7ae9e2448fc010a1b80a5ffe763667c12b991596/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java#L219)):*
> ```Java
>             .build();
> 
>     DelegateResponseData delegateResponseData = this.delegateGrpcClientWrapper.executeSyncTask(delegateTaskRequest);
> ```

Can we check if we can execute the Async task here? We can maintain state at each manifestOutcome level.

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41971)* status: 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java` line 229 at r1](https://reviewable.io/reviews/harness/harness-core/41971#-NKqtUHm88vk2bwhHeiK:-NKqv9Mh40GH8seLKYFy:b-dlvlsi) ([raw file](https://github.com/harness/harness-core/blob/7ae9e2448fc010a1b80a5ffe763667c12b991596/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java#L229)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

This can have multiple Files, right? (For ex: in scaling policies)
</blockquote></details>

as discussed we always fetch one content from one ManifestOutcome, one by one

**Review by acasian-harness — CHANGES_REQUESTED** [review]
@vitsafronovici can you add proper pr description, not clear what this is change is about. 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41971#-:-NKr0Ozj-_B0fOqeoj3l:b-xy5hz0)* status: 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 863 at r1](https://reviewable.io/reviews/harness/harness-core/41971#-NKr-_GHCKxOncBuAM5M:-NKr-_GHCKxOncBuAM5N:bzcuesq) ([raw file](https://github.com/harness/harness-core/blob/7ae9e2448fc010a1b80a5ffe763667c12b991596/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L863)):*
> ```Java
>     if (isNotEmpty(scopedFilePathList)) {
>       logCallback.saveExecutionLog(
>           color(format("Fetching %s files with identifier: %s", manifestType, manifestIdentifier), LogColor.White,
> ```

this is common code between all swimlanes who are using the local file store. Why this log change is needed?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java` line 219 at r1](https://reviewable.io/reviews/harness/harness-core/41971#-NKqvK-OB6qT0-oPHg2M:-NKr0Gt80CmnkZa9XrIu:b-yzq28z) ([raw file](https://github.com/harness/harness-core/blob/7ae9e2448fc010a1b80a5ffe763667c12b991596/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java#L219)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

Can we check if we can execute the Async task here? We can maintain state at each manifestOutcome level.
</blockquote></details>

This should be done in task chain fashion, async way, like we do for all the swimlanes.

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41971)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java` line 219 at r1](https://reviewable.io/reviews/harness/harness-core/41971#-NKqvK-OB6qT0-oPHg2M:-NKxs57J2jlE54i7HP-E:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ae9e2448fc010a1b80a5ffe763667c12b991596/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java#L219)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

This should be done in task chain fashion, async way, like we do for all the swimlanes.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 863 at r1](https://reviewable.io/reviews/harness/harness-core/41971#-NKr-_GHCKxOncBuAM5M:-NKxs6H-8NiOUm-7whK3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ae9e2448fc010a1b80a5ffe763667c12b991596/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L863)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

this is common code between all swimlanes who are using the local file store. Why this log change is needed?
</blockquote></details>

Done.

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41971)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java` line 439 at r3](https://reviewable.io/reviews/harness/harness-core/41971#-NL05uQICG3MOGYXvHZf:-NL05uQICG3MOGYXvHZg:bcfve5s) ([raw file](https://github.com/harness/harness-core/blob/a447576edf8255e5634b2dbfcf5a251fa891abe7/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java#L439)):*
> ```Java
>                                   .build();
> 
>     String taskName = TaskType.GIT_FETCH_NEXT_GEN_TASK.getDisplayName();
> ```

imho we should use `name()` here, `getDisplayName` is used by UI to display user friendly task name. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java` line 515 at r3](https://reviewable.io/reviews/harness/harness-core/41971#-NL06R86-O_AvVAebEWA:-NL06R86-O_AvVAebEWB:brhciwl) ([raw file](https://github.com/harness/harness-core/blob/a447576edf8255e5634b2dbfcf5a251fa891abe7/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java#L515)):*
> ```Java
>   }
> 
>   public void info(LogCallback logCallback, String msg, Object... params) {
> ```

imho instead of using those logging utilities in helpers, we could have a log wrapper doing this

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java` line 500 at r4](https://reviewable.io/reviews/harness/harness-core/41971#-NL17G4j9LorJ0QX8zW0:-NL17G4qEmhWoiSNzY2o:b-4f76e2) ([raw file](https://github.com/harness/harness-core/blob/a0c55d96f74135640a6137baf11de1a832e7d20c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java#L500)):*
> ```Java
>       logger.info(logCallback, "Fetching %s manifest files with identifier `%s` from Git", manifestType, identifier);
>       return queueFetchGitTask(asgExecutionPassThroughData, ambiance, stepElementParameters);
>     }
> ```

We can move all these lines in the above `if (delegateResponseData != null)` block



_Code quote:_
```Java
    gitFetchFilesConfig = asgManifestFetchData.getNextGitFetchFilesConfig();

    if (gitFetchFilesConfig != null) {
      identifier = gitFetchFilesConfig.getIdentifier();
      manifestType = gitFetchFilesConfig.getManifestType();
      logger.info(logCallback, "Fetching %s manifest files with identifier `%s` from Git", manifestType, identifier);
      return queueFetchGitTask(asgExecutionPassThroughData, ambiance, stepElementParameters);
    }
```

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 3 of 6 files at r2, 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41971)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41971)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41971)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41971)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java` line 439 at r3](https://reviewable.io/reviews/harness/harness-core/41971#-NL05uQICG3MOGYXvHZf:-NL1EJT53n1B3fZtuPRI:b-ccrdgy) ([raw file](https://github.com/harness/harness-core/blob/a447576edf8255e5634b2dbfcf5a251fa891abe7/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java#L439)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

imho we should use `name()` here, `getDisplayName` is used by UI to display user friendly task name. 
</blockquote></details>

will ook ugly for UI
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java` line 515 at r3](https://reviewable.io/reviews/harness/harness-core/41971#-NL06R86-O_AvVAebEWA:-NL1Ejln8CPPerQcijfo:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/a447576edf8255e5634b2dbfcf5a251fa891abe7/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java#L515)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

imho instead of using those logging utilities in helpers, we could have a log wrapper doing this
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java` line 500 at r4](https://reviewable.io/reviews/harness/harness-core/41971#-NL17G4j9LorJ0QX8zW0:-NL1EQdTEqWq4Jk9lIKz:b-l315oz) ([raw file](https://github.com/harness/harness-core/blob/a0c55d96f74135640a6137baf11de1a832e7d20c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java#L500)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

We can move all these lines in the above `if (delegateResponseData != null)` block
</blockquote></details>

It will not work, as this method is also used when we don't have response from GitfetchTask delegate and we need to initiate one

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java` line 500 at r4](https://reviewable.io/reviews/harness/harness-core/41971#-NL17G4j9LorJ0QX8zW0:-NL4hA2qC30qkVGBuB15:bobtspl) ([raw file](https://github.com/harness/harness-core/blob/a0c55d96f74135640a6137baf11de1a832e7d20c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java#L500)):*
<details><summary><i>Previously, vitsafronovici (Vitalie Safronovici) wrote…</i></summary><blockquote>

It will not work, as this method is also used when we don't have response from GitfetchTask delegate and we need to initiate one
</blockquote></details>

Yeah but we already have gitFetchFilesConfig in the start of this method. But it only nit. Marking it resolved.

**Review by arvind-choudhary-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41971)* status: 2 file(s) to review.

**Review by lovish1999 — APPROVED** [review]
> Reviewed 3 of 6 files at r2, 3 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41971)* status: :shipit: complete! ✓

**Pull request merged**
