### PR TITLE
[feat]: [PL-21667]: Adding pagination support for Accounts fetch and added unit test cases.

### PR DESCRIPTION
**Pull request by boopesh007**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34779)

### CODE REVIEW

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 147 at r1](https://reviewable.io/reviews/harness/harness-core/34779#-N5eCPUj9IQx1d4e2qwZ:-N5eCPUj9IQx1d4e2qw_:bl5r4rs) ([raw file](https://github.com/harness/harness-core/blob/ac2602faf213ba9a415dbfffdaddb895acba3ead/400-rest/src/main/java/software/wings/resources/UserResource.java#L147)):*
> ```Java
> import org.hibernate.validator.constraints.NotBlank;
> import org.hibernate.validator.constraints.NotEmpty;
> import org.jvnet.hk2.annotations.Optional;
> ```

By mistake? It should be java's Optional

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 535 at r1](https://reviewable.io/reviews/harness/harness-core/34779#-N5eCaif0cvQOqvdPkai:-N5eCaigD1mBK5nHPuTr:b-brwgxx) ([raw file](https://github.com/harness/harness-core/blob/ac2602faf213ba9a415dbfffdaddb895acba3ead/400-rest/src/main/java/software/wings/resources/UserResource.java#L535)):*
> ```Java
>    */
>   @GET
>   @Path("user-accounts/{userId}")
> ```

change name to 



_Code snippet:_
```Java
"accounts/{userId}"
```

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 535 at r1](https://reviewable.io/reviews/harness/harness-core/34779#-N5eCaif0cvQOqvdPkai:-N5eQY5K6Lhy8LfOI-DE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac2602faf213ba9a415dbfffdaddb895acba3ead/400-rest/src/main/java/software/wings/resources/UserResource.java#L535)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

change name to 
</blockquote></details>

Done.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34779)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34779)* status: :shipit: complete! ✓

**Pull request merged**
