### PR TITLE
[fix]: [CDS-72523]: Expression support for nodeNames in Matrix

### PR DESCRIPTION
**Pull request by vtxorxwitty**
## Describe your changes
Changes to support expressions for the nodeName field in matrix definition. 

## Testing
Tested the changes for the following use cases: 
1. When nodeName is given and the boolean flag for matrix naming is enabled.
Screenshot 2023-08-25 at 7 25 45 PM

2. When nodeName is not given and the boolean flag for matrix naming is enabled.
Screenshot 2023-08-25 at 7 25 56 PM

3. When nodeName is given and the boolean flag for matrix naming is disabled.
Screenshot 2023-08-25 at 7 26 35 PM

4. When nodeName is not given and the boolean flag for matrix naming is disabled.
Screenshot 2023-08-25 at 7 27 08 PM

5. When the nodeName fails to resolve.
Screenshot 2023-08-25 at 7 49 52 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51672)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java` line 341 at r2](https://reviewable.io/reviews/harness/harness-core/51672#-NcMlLtA4_2Td7zjcYoQ:-NcMlLtA4_2Td7zjcYoR:b7l7zxq) ([raw file](https://github.com/harness/harness-core/blob/c8a4282469d05b8b695e1cb9f8f550ab7ed64e9b/884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java#L341)):*
> ```Java
>     String nodeName = level.getStrategyMetadata().getMatrixMetadata().getNodeName();
> 
>     if (EmptyPredicate.isEmpty(nodeName)) {
> ```

can we create a function that takes in nodeName and useMatrixFieldName and returns the identifier
That way, we will be able to reduce the if at two places.

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/51672#-NcMlcp_0DOETgofARNy:-NcMlcp_0DOETgofARNz:b-9vkt2l) ([raw file](https://github.com/harness/harness-core/blob/c8a4282469d05b8b695e1cb9f8f550ab7ed64e9b/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L87)):*
> ```Java
>         // If nodeName field is not given, we define the node names with the <key,value> pairs provided by the users.
>         variableName = entries.stream().map(t -> t.getValue().replace(".", "")).collect(Collectors.joining("_"));
>       }
> ```

Create a new function and add the logic over there.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/execution/executable_response.proto` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/51672#-NcMlikQA3efsbx7mVRy:-NcMlikQA3efsbx7mVRz:b-1f8n90) ([raw file](https://github.com/harness/harness-core/blob/c8a4282469d05b8b695e1cb9f8f550ab7ed64e9b/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/execution/executable_response.proto#L89)):*
> ```proto
>   string subType = 3;
>   repeated string matrixKeysToSkipInName = 4;
>   string nodeName = 5;
> ```

Keep only one. Either resolvedNodeName or nodeName.

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51672)* status: 6 file(s) to review. 0 of 2 approvals obtained.

**Comment by vtxorxwitty** [comment]
trigger uts

**Comment by vtxorxwitty** [comment]
trigger messagecheck

**Comment by vtxorxwitty** [comment]
trigger uts

**Comment by vtxorxwitty** [comment]
trigger ut7

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 103 at r6](https://reviewable.io/reviews/harness/harness-core/51672#-NcYMkJb6lJe5DOscfCk:-NcYMkJb6lJe5DOscfCl:b-3g03oc) ([raw file](https://github.com/harness/harness-core/blob/a6914d3a1d69fc4575f3342d53b5664b732c4b40/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L103)):*
> ```Java
>                                                       .addAllMatrixCombination(matrixMetadata.get(currentIteration))
>                                                       .putAllMatrixValues(combination)
>                                                       .setNodeName(isNodeNameSet ? variableName : "")
> ```

Add a comment here as to why we are doing this.

**Comment by vtxorxwitty** [comment]
trigger uts

**Comment by vtxorxwitty** [comment]
trigger ut0

**Comment by vtxorxwitty** [comment]
trigger ut1

**Comment by vtxorxwitty** [comment]
trigger ut2

**Comment by vtxorxwitty** [comment]
trigger ut3

**Comment by vtxorxwitty** [comment]
trigger ut4

**Comment by vtxorxwitty** [comment]
trigger ut1

**Comment by vtxorxwitty** [comment]
trigger ut2

**Comment by vtxorxwitty** [comment]
trigger ut2

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51672)* status: 6 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java` line 341 at r2](https://reviewable.io/reviews/harness/harness-core/51672#-NcMlLtA4_2Td7zjcYoQ:-NcbOR6h9HiH1BlKWG_j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c8a4282469d05b8b695e1cb9f8f550ab7ed64e9b/884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java#L341)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

can we create a function that takes in nodeName and useMatrixFieldName and returns the identifier
That way, we will be able to reduce the if at two places.
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/51672#-NcMlcp_0DOETgofARNy:-NcbOSbe2YUKaRjNNIdn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c8a4282469d05b8b695e1cb9f8f550ab7ed64e9b/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L87)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Create a new function and add the logic over there.
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 103 at r6](https://reviewable.io/reviews/harness/harness-core/51672#-NcYMkJb6lJe5DOscfCk:-NcbOTHxCKw5fuLI1dX9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a6914d3a1d69fc4575f3342d53b5664b732c4b40/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L103)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Add a comment here as to why we are doing this.
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 118 at r6](https://reviewable.io/reviews/harness/harness-core/51672#-NcYMrVN2ANmSRmp-fIi:-NcbOU-y46sDd9epZmci:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a6914d3a1d69fc4575f3342d53b5664b732c4b40/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L118)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

There is no need to convert to json node, you can String itself to the evaluator.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/execution/executable_response.proto` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/51672#-NcMlikQA3efsbx7mVRy:-NcbOUkN7RHqL-Thtevj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c8a4282469d05b8b695e1cb9f8f550ab7ed64e9b/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/execution/executable_response.proto#L89)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Keep only one. Either resolvedNodeName or nodeName.
</blockquote></details>

Done.

**Comment by vtxorxwitty** [comment]
trigger ut4

**Comment by vtxorxwitty** [comment]
trigger ut1

**Comment by vtxorxwitty** [comment]
trigger uts

**Review by sahilhindwani-harness — COMMENTED** [review]
As discussed, Please add UT for these

> Reviewed 1 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51672#-:-NcfY1rr6nO8PEm5Gwck:bjeq3sm)* status: 6 file(s) to review. 0 of 2 approvals obtained.

**Comment by vtxorxwitty** [comment]
trigger uts

**Comment by vtxorxwitty** [comment]
trigger uts

**Review by naidu-harness — CHANGES_REQUESTED** [review]
please improve the new code coverage to 90

**Comment by vtxorxwitty** [comment]
trigger uts

**Comment by vtxorxwitty** [comment]
trigger uts

**Comment by vtxorxwitty** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r9, 2 of 3 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51672)* status: 10 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 4 files at r2, 1 of 3 files at r5, 1 of 1 files at r6, 1 of 3 files at r9, 1 of 3 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51672)* status: 2 file(s) to review. 2 change requests. 1 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java` line 363 at r13](https://reviewable.io/reviews/harness/harness-core/51672#-NcgyIRI04ysjw4W-4Ty:-NcgyIRI04ysjw4W-4Tz:b-6ftgr) ([raw file](https://github.com/harness/harness-core/blob/d43bf59b0d0c2156ad323b677e32f60840cdbaba/884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java#L363)):*
> ```Java
>                             .map(t -> t.getValue().replace(".", ""))
>                             .collect(Collectors.joining("_"));
>     } else {
> ```

what is this else condition doing? adding indexes? can you add comment, why earlier it was not there and we need now?
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/strategy/MatrixConfig.java` line 84 at r13](https://reviewable.io/reviews/harness/harness-core/51672#-Ncgz2GMDKYlmay2D6P7:-Ncgz2GMDKYlmay2D6P8:b-9xwmdv) ([raw file](https://github.com/harness/harness-core/blob/d43bf59b0d0c2156ad323b677e32f60840cdbaba/953-yaml-commons/src/main/java/io/harness/plancreator/strategy/MatrixConfig.java#L84)):*
> ```Java
>   @YamlSchemaTypes(value = {expression})
>   @SkipAutoEvaluation
>   ParameterField<String> nodeName;
> ```

first raise pr for schema
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 74 at r13](https://reviewable.io/reviews/harness/harness-core/51672#-Ncgzo1N8zNU6T8rDZRB:-Ncgzo1N8zNU6T8rDZRC:bnnumkx) ([raw file](https://github.com/harness/harness-core/blob/d43bf59b0d0c2156ad323b677e32f60840cdbaba/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L74)):*
> ```Java
>       Set<Map.Entry<String, String>> entries = combination.entrySet();
> 
>       EngineExpressionEvaluator evaluator =
> ```

why we are creating evaluator here, can we move this to resolveNodeName?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 119 at r13](https://reviewable.io/reviews/harness/harness-core/51672#-NcgzYARDluSRO5D3ohM:-NcgzYARDluSRO5D3ohN:b-qyrght) ([raw file](https://github.com/harness/harness-core/blob/d43bf59b0d0c2156ad323b677e32f60840cdbaba/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L119)):*
> ```Java
>     if (EmptyPredicate.isNotEmpty(nodeName)) {
>       // If nodeName field is given, using it to name the nodes.
>       return (String) evaluator.resolve(nodeName, ExpressionMode.THROW_EXCEPTION_IF_UNRESOLVED);
> ```

This we got product approval that if expression doesn't resolve we will throw exception? also did we test scenario what is happening, can you add sshot and automation for this

**Comment by archit-harness** [comment]
in 2nd case why uuid is getting attached?

in 3rd case and 1st case -> both are s1_a, not sure what nodeName you are using, thus use different value and share sshot again

**Review by vtxorxwitty — COMMENTED** [review]
The first and the third case will give same result as we are giving nodename. It will be the priority irrespective of whether the boolean setting is enabled or disabled. 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51672#-:-Nch0xLsD6qWPBc3Qpow:bddhmcp)* status: 2 file(s) to review. 2 change requests. 1 of 2 approvals obtained.

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51672)* status: 2 file(s) to review. 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java` line 363 at r13](https://reviewable.io/reviews/harness/harness-core/51672#-NcgyIRI04ysjw4W-4Ty:-Nch42fl4mIyC-NPgMa7:b-xegw7s) ([raw file](https://github.com/harness/harness-core/blob/d43bf59b0d0c2156ad323b677e32f60840cdbaba/884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java#L363)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what is this else condition doing? adding indexes? can you add comment, why earlier it was not there and we need now?
</blockquote></details>

This else condition is adding indexes when both nodename is not given and the boolean setting is disabled. In that case all the child nodenames will have indices appended. 

It was present from before. This part of the code we have not changed anything. Just bifurcated based on the if conditions.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 119 at r13](https://reviewable.io/reviews/harness/harness-core/51672#-NcgzYARDluSRO5D3ohM:-Nch4n930OhCdnpvVqFz:b2m1bq3) ([raw file](https://github.com/harness/harness-core/blob/d43bf59b0d0c2156ad323b677e32f60840cdbaba/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L119)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

This we got product approval that if expression doesn't resolve we will throw exception? also did we test scenario what is happening, can you add sshot and automation for this
</blockquote></details>

Yes I have tested the scenario. And attached the screenshot in the PR description.

**Comment by vtxorxwitty** [comment]
trigger uts

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51672)* status: 3 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/strategy/MatrixConfig.java` line 84 at r13](https://reviewable.io/reviews/harness/harness-core/51672#-Ncgz2GMDKYlmay2D6P7:-NchCmbF0iJs79KMHr1p:b-tlnucg) ([raw file](https://github.com/harness/harness-core/blob/d43bf59b0d0c2156ad323b677e32f60840cdbaba/953-yaml-commons/src/main/java/io/harness/plancreator/strategy/MatrixConfig.java#L84)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

first raise pr for schema
</blockquote></details>

Raised a separate PR for the config changes.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 74 at r13](https://reviewable.io/reviews/harness/harness-core/51672#-Ncgzo1N8zNU6T8rDZRB:-NchCrmlCnipcxvnuzMl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d43bf59b0d0c2156ad323b677e32f60840cdbaba/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L74)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are creating evaluator here, can we move this to resolveNodeName?
</blockquote></details>

Done.

**Comment by vtxorxwitty** [comment]
trigger uts

**Comment by vtxorxwitty** [comment]
trigger ut7

**Comment by vtxorxwitty** [comment]
trigger ut1

**Comment by vtxorxwitty** [comment]
trigger ut9

**Comment by vtxorxwitty** [comment]
trigger ut1

**Comment by vtxorxwitty** [comment]
trigger ut7

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51672)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by vtxorxwitty** [comment]
trigger ut1

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51672)* status: :shipit: complete! ✓

**Review by naidu-harness — APPROVED** [review]

**Pull request merged**
