### PR TITLE
[feat]: [PIE-8938]: Always revalidate when reloading from git

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45108)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45108)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 411 at r1](https://reviewable.io/reviews/harness/harness-core/45108#-NQUaJNHDulPrl9S4m3j:-NQUaJNHDulPrl9S4m3k:b-v0o1u7) ([raw file](https://github.com/harness/harness-core/blob/178492648e6ab0fc02822acae84122d46bdfee7c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L411)):*
> ```Java
>     String branchFromScm = GitAwareContextHelper.getBranchInSCMGitMetadata();
>     String fqn = PipelineAsyncValidationHelper.buildFQN(pipelineEntity, branchFromScm);
>     String validationUUID;
> ```

can you add comment why we are doing validation if not from cache?



_Code quote:_
```Java
      PipelineValidationEvent newEvent =
          pipelineAsyncValidationService.startEvent(pipelineEntity, branchFromScm, Action.CRUD, loadFromCache);
      validationUUID = newEvent.getUuid();
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45108)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 411 at r1](https://reviewable.io/reviews/harness/harness-core/45108#-NQUaJNHDulPrl9S4m3j:-NQUhCvh23MyVBc0HBXY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/178492648e6ab0fc02822acae84122d46bdfee7c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L411)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you add comment why we are doing validation if not from cache?
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45108)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 412 at r2](https://reviewable.io/reviews/harness/harness-core/45108#-NQYiU7r8YqHqUkmBPN1:-NQYiU7r8YqHqUkmBPN2:b-lage2q) ([raw file](https://github.com/harness/harness-core/blob/bbf72045ddb5371b66ec910cc63c7e6a713c2748/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L412)):*
> ```Java
>     String fqn = PipelineAsyncValidationHelper.buildFQN(pipelineEntity, branchFromScm);
>     String validationUUID;
>     if (!loadFromCache && pipelineEntity.getStoreType() == StoreType.REMOTE) {
> ```

I think rather than relating it to user and all, we should simply say in comments that whenever its going to be loaded from GIT, we want to create a fresh validation event, which is pretty logical in itself.
Also, creating a logical method to put this if condition into would be helpful for easy readability.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45108)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 412 at r2](https://reviewable.io/reviews/harness/harness-core/45108#-NQYiU7r8YqHqUkmBPN1:-NQYzLkg6vgwfN4vBEVW:bg24mc4) ([raw file](https://github.com/harness/harness-core/blob/bbf72045ddb5371b66ec910cc63c7e6a713c2748/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L412)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think rather than relating it to user and all, we should simply say in comments that whenever its going to be loaded from GIT, we want to create a fresh validation event, which is pretty logical in itself.
Also, creating a logical method to put this if condition into would be helpful for easy readability.
</blockquote></details>

Added a separate method to get validation uuid. And imo there's no harm in a more descriptive comment

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 412 at r2](https://reviewable.io/reviews/harness/harness-core/45108#-NQYiU7r8YqHqUkmBPN1:-NQZ-Srx2a6flwo3jsjp:bvmy84u) ([raw file](https://github.com/harness/harness-core/blob/bbf72045ddb5371b66ec910cc63c7e6a713c2748/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L412)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Added a separate method to get validation uuid. And imo there's no harm in a more descriptive comment
</blockquote></details>

We should try and think from API perspective rather than consumer perspective. Here the comment is pretty focussed on UI integration, thus pointed it out. And I personally don't agree with too elaborate comments every-time as it degrades code readability.
Anyways, earlier one was not a blocker comment, just a suggestion. We are good over here.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45108)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45108)* status: :shipit: complete! ✓

**Pull request merged**
