### PR TITLE
fix: [CDS-53968]: provided proper exception for invalid credentials f…

### PR DESCRIPTION
**Pull request by vitsafronovici**
## Describe your changes
Changed the error message to be more descriptive.
Before:
image

After:
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45236)

### CODE REVIEW

**Comment by vitsafronovici** [comment]
trigger ut0

**Review by acasian-harness — APPROVED** [review]
@vitsafronovici let's update PR description in github with examples or screenshots with before/after

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45236#-:-NQeob9s9IXSVhMVEBEo:bxhusq8)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by vitsafronovici** [comment]
trigger ut1, ut2, ut3, ut4, ut5, ut6, ut7, ut8, ut9

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45236)* status: 1 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshWinRmExceptionHandler.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/45236#-NQewctW8jWiTKXNuYUz:-NQf7k5N0CQDjVMxiVEF:b-7sxfwr) ([raw file](https://github.com/harness/harness-core/blob/da3f8bb007d18739c57ea2c453aa92b94e7cb50d/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshWinRmExceptionHandler.java#L33)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Maybe having Boolean as a method param and using null for handling common ssh and winrm exceptions
</blockquote></details>

common logic will be inside handle() method
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshWinRmExceptionHandler.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/45236#-NQexWpo0N_gJhpA-OPq:-NQf7uRI0Nc6Pi1Nw3yX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/da3f8bb007d18739c57ea2c453aa92b94e7cb50d/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshWinRmExceptionHandler.java#L47)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

"SSH" private constant 
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshWinRmExceptionHandler.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/45236#-NQexb7TAi6-8zdagCU-:-NQf7vyD8urkOuiQcEoz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/da3f8bb007d18739c57ea2c453aa92b94e7cb50d/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshWinRmExceptionHandler.java#L62)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

"invalid credentials" private constant
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshWinRmExceptionHandler.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/45236#-NQexiVY3uV-S-OipUj4:-NQf7wWt24CZat--6k2M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/da3f8bb007d18739c57ea2c453aa92b94e7cb50d/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshWinRmExceptionHandler.java#L65)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

"WinRm" private constant
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshWinRmExceptionHandler.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/45236#-NQexN_e3wRfscSNB015:-NQf7xS01fjOhP64En7j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/da3f8bb007d18739c57ea2c453aa92b94e7cb50d/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshWinRmExceptionHandler.java#L76)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

getDefaultException and wrapToTaskNGDataException are the same methods, use one of them. 
</blockquote></details>

Done.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45236#-:-NQf8WDk4yIVwKdEAD12:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by vitsafronovici** [comment]
trigger messagecheck

**Pull request merged**
