### PR TITLE
feat: [DEL-3254]: Reduce broadcast interval after one try

### PR DESCRIPTION
**Pull request by jennyjames21**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30398)

### CODE REVIEW

**Comment by jennyjames21** [comment]
___
*[400-rest/src/main/java/software/wings/app/DelegateQueueTask.java, line 287 at r1](https://reviewable.io/reviews/harness/harness-core/30398#-Mul8bNG1FZR2CZ5JsjR:-Mul8bNG1FZR2CZ5JsjS:bu4ln29) ([raw file](https://github.com/harness/harness-core/blob/96d81999e59197d645d85b48bc2c0025c69f8d8e/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L287)):*
> ```Java
>           broadcastToDelegates.add(delegateId);
>           eligibleDelegatesList.addLast(delegateId);
>         }
> ```

AlreadyTriedDelegates is an exciting field which was not used before, im using that to track already tried delegates and resetting

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/app/DelegateQueueTask.java, line 97 at r2](https://reviewable.io/reviews/harness/harness-core/30398#-Mum2R7l5P1G6DnJuPet:-Mum2R7l5P1G6DnJuPeu:bm92kx5) ([raw file](https://github.com/harness/harness-core/blob/c38732927a02879a328c935cc47631b0c7c98ccf/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L97)):*
> ```Java
> 
>   // async tasks{5sec, 30 Sec, 1 Min, 2 Min, 4 Min, 8 Min,
>   private List<Integer> asyncIntervals = Arrays.asList(5, 30, 60, 120, 240, 480, 900);
> ```

i don't think we need two different intervals. also i think 120 seconds is enough

**Comment by jennyjames21** [comment]
image
image
https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22qa-setup%22%0Aresource.labels.location%3D%22us-central1-c%22%0Aresource.labels.cluster_name%3D%22pr-private%22%0Aresource.labels.namespace_name%3D%22del-task-interval-2%22%0Alabels.k8s-pod%2Fapp%3D%22dms%22%0A%22XTF24n26SgqWvLXxjgzC4g%22;cursorTimestamp=2022-02-01T23:18:57.309092663Z?project=qa-setup

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/app/DelegateQueueTask.java, line 288 at r3](https://reviewable.io/reviews/harness/harness-core/30398#-Mut60fjDlKASfjIbQ73:-Mut60fjDlKASfjIbQ74:byhs42u) ([raw file](https://github.com/harness/harness-core/blob/a78eac5064f8c9f197ea3f3d13f3e09a2fc17527/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L288)):*
> ```Java
>         }
>         long nextInterval = TimeUnit.SECONDS.toMillis(5);
>         AtomicInteger broadcastRoundCount = new AtomicInteger(delegateTask.getBroadcastRound());
> ```

why do we need atomic integer?

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/app/DelegateQueueTask.java, line 294 at r3](https://reviewable.io/reviews/harness/harness-core/30398#-Mut6D65DC9e490i0_rC:-Mut6D65DC9e490i0_rD:b8bi8mt) ([raw file](https://github.com/harness/harness-core/blob/a78eac5064f8c9f197ea3f3d13f3e09a2fc17527/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L294)):*
> ```Java
>         // if all delegates got one round of rebroadcast, then increase broadcast interval & broadcastRound
>         if (alreadyTriedDelegates.containsAll(delegateTask.getEligibleToExecuteDelegateIds())) {
>           alreadyTriedDelegates = Sets.newHashSet();
> ```

use clear instead of creating new set

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/app/DelegateQueueTask.java, line 256 at r3](https://reviewable.io/reviews/harness/harness-core/30398#-Mut6VVs8QNnush5j6Wi:-Mut6VVs8QNnush5j6Wj:bnj1by0) ([raw file](https://github.com/harness/harness-core/blob/a78eac5064f8c9f197ea3f3d13f3e09a2fc17527/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L256)):*
> ```Java
>                                                    .field(DelegateTaskKeys.expiry)
>                                                    .greaterThan(now)
>                                                    .field(DelegateTaskKeys.broadcastRound)
> ```

this change doesn't make the delegate task to fail if all 3 rounds of broadcasting is done. it will remain in the queue and get expired. We should fail the task in case the rounds are exceeded.

**Comment by jennyjames21** [comment]
___
*[400-rest/src/main/java/software/wings/app/DelegateQueueTask.java, line 256 at r3](https://reviewable.io/reviews/harness/harness-core/30398#-Mut6VVs8QNnush5j6Wi:-MuvGJPZ7a6vVg6rLrPQ:b-itzna4) ([raw file](https://github.com/harness/harness-core/blob/a78eac5064f8c9f197ea3f3d13f3e09a2fc17527/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L256)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this change doesn't make the delegate task to fail if all 3 rounds of broadcasting is done. it will remain in the queue and get expired. We should fail the task in case the rounds are exceeded. 
</blockquote></details>

currently we mark long run task queued state as failed or if the task is expired  as failed thru scheduleTask. 
I was thinking to add that change as as part when we introduce assignmentTimeout that way it's clear to user why failed.
We cannot fully rely on broadcastRound to fail either as it need some time to receive task event, validate and acquire rite?

**Comment by jennyjames21** [comment]
___
*[400-rest/src/main/java/software/wings/app/DelegateQueueTask.java, line 294 at r3](https://reviewable.io/reviews/harness/harness-core/30398#-Mut6D65DC9e490i0_rC:-MuvI89iBsSbn1MrAAbI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a78eac5064f8c9f197ea3f3d13f3e09a2fc17527/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L294)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

use clear instead of creating new set
</blockquote></details>

Done.

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/app/DelegateQueueTask.java, line 288 at r3](https://reviewable.io/reviews/harness/harness-core/30398#-Mut60fjDlKASfjIbQ73:-MuwBKfM9Eqrdvx6t7zo:bg257mv) ([raw file](https://github.com/harness/harness-core/blob/a78eac5064f8c9f197ea3f3d13f3e09a2fc17527/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L288)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

only for sake readability on increment operation
</blockquote></details>

lets use int, atomic makes you feel like there is some concurrency concern :)

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30398)* status: 0 of 1 approvals obtained.

**Review by jennyjames21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30398)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/app/DelegateQueueTask.java, line 288 at r3](https://reviewable.io/reviews/harness/harness-core/30398#-Mut60fjDlKASfjIbQ73:-MuwH-NoBefxxR4PwqK6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a78eac5064f8c9f197ea3f3d13f3e09a2fc17527/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L288)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

lets use int, atomic makes you feel like there is some concurrency concern :)
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
trigger messagecheck

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30398)* status: :shipit: complete! ✓

**Pull request merged**
