### PR TITLE
fix: [CDS-36189]: changed capability check for HttpHelmRepoConfig

### PR DESCRIPTION
**Pull request by achyuth-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32234)

### CODE REVIEW

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32234)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/beans/settings/helm/HttpHelmRepoConfig.java, line 97 at r1](https://reviewable.io/reviews/harness/harness-core/32234#-N-Xpd7nBedEFjlEnNbU:-N-Xpd7nBedEFjlEnNbV:b-s0q3uy) ([raw file](https://github.com/harness/harness-core/blob/c55471aa1524b6566364862f13167d3cdbae3476/400-rest/src/main/java/software/wings/beans/settings/helm/HttpHelmRepoConfig.java#L97)):*
> ```Java
>       ref: https://harness.atlassian.net/browse/CDS-36189
>      */
>     URI url;
> ```

any reasons why this should be outside the try catch block?
___
*[400-rest/src/main/java/software/wings/beans/settings/helm/HttpHelmRepoConfig.java, line 102 at r1](https://reviewable.io/reviews/harness/harness-core/32234#-N-Xpgyu9WDSQMnb1eSx:-N-Xpgyu9WDSQMnb1eSy:b-cu9xpy) ([raw file](https://github.com/harness/harness-core/blob/c55471aa1524b6566364862f13167d3cdbae3476/400-rest/src/main/java/software/wings/beans/settings/helm/HttpHelmRepoConfig.java#L102)):*
> ```Java
>       int port = url.getPort();
>       if (port <= -1) {
>         port = url.getScheme().equals("https") ? 443 : 80;
> ```

Let's have a null check here, since you're parsing through URI in this case scheme is not mandatory, we can default this to 443 in this case

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32234)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32234)* status: :shipit: complete! ✓

**Pull request merged**
