### PR TITLE
fix: [CDS-81161]: Use ScheduledExecutorService to close all prefix log streams

### PR DESCRIPTION
**Pull request by sarthakkasat**
## Describe your changes
Currently as a fallback to close log streams we call the method delayToCloseAllPrefix logStreams, we are adding a delay to call this method as the 2 close log stream methods called in very short amount of time might lead to loss of log data.
Edge case is mentioned here:
`https://harness.atlassian.net/browse/CDS-81161?focusedCommentId=584579`

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54197)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 649 at r1](https://reviewable.io/reviews/harness/harness-core/54197#-Ngx28Zn6u4_eGf-Z1C9:-Ngx28ZoB1B_D-rrQo-b:b28upzi) ([raw file](https://github.com/harness/harness-core/blob/5c9ce7a8c7ad922f397aba3a5656f55f829084e9/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L649)):*
> ```Java
>   @Singleton
>   @Named("logStreamingClientThreadPool")
>   public ScheduledExecutorService logStreamingClientThreadPool() {
> ```

I think we should change the name from logStreamingClientThreadPool to logStreamingClientScheduledExecutor to avoid confusion

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 649 at r1](https://reviewable.io/reviews/harness/harness-core/54197#-Ngx28Zn6u4_eGf-Z1C9:-Ngx2FeM89svqcX120S8:b-6p9qzf) ([raw file](https://github.com/harness/harness-core/blob/5c9ce7a8c7ad922f397aba3a5656f55f829084e9/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L649)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I think we should change the name from logStreamingClientThreadPool to logStreamingClientScheduledExecutor to avoid confusion
</blockquote></details>

Also change the @Named("..")

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 655 at r1](https://reviewable.io/reviews/harness/harness-core/54197#-Ngx2RP0Aw2pGUVmL0NX:-Ngx2RP0Aw2pGUVmL0NY:b-ozytx) ([raw file](https://github.com/harness/harness-core/blob/5c9ce7a8c7ad922f397aba3a5656f55f829084e9/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L655)):*
> ```Java
>         : ThreadPoolConfig.builder().corePoolSize(1).maxPoolSize(50).idleTime(30).timeUnit(TimeUnit.SECONDS).build();
>     return new ScheduledThreadPoolExecutor(threadPoolConfig.getCorePoolSize(),
>         new ThreadFactoryBuilder().setNameFormat("log-client-pool-%d").setPriority(Thread.MAX_PRIORITY).build());
> ```

lets leave the default value for priority i.e NORM_PRIORITY

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 653 at r1](https://reviewable.io/reviews/harness/harness-core/54197#-Ngx2raGDupgalwRT9kA:-Ngx2raGDupgalwRT9kB:b-n6hcid) ([raw file](https://github.com/harness/harness-core/blob/5c9ce7a8c7ad922f397aba3a5656f55f829084e9/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L653)):*
> ```Java
>             && appConfig.getLogStreamingServiceConfig().getThreadPoolConfig() != null
>         ? appConfig.getLogStreamingServiceConfig().getThreadPoolConfig()
>         : ThreadPoolConfig.builder().corePoolSize(1).maxPoolSize(50).idleTime(30).timeUnit(TimeUnit.SECONDS).build();
> ```

core pool size 1 will not work
Lets keep at 10

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54197)* status: 5 file(s) to review. 0 of 2 approvals obtained.

**Review by sarthakkasat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54197)* status: 5 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 649 at r1](https://reviewable.io/reviews/harness/harness-core/54197#-Ngx28Zn6u4_eGf-Z1C9:-Ngx4J-s3k7cr0CXH1CZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5c9ce7a8c7ad922f397aba3a5656f55f829084e9/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L649)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Also change the @Named("..")
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 653 at r1](https://reviewable.io/reviews/harness/harness-core/54197#-Ngx2raGDupgalwRT9kA:-Ngx4ReV0CObV8V49l21:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5c9ce7a8c7ad922f397aba3a5656f55f829084e9/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L653)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

core pool size 1 will not work
Lets keep at 10
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 655 at r1](https://reviewable.io/reviews/harness/harness-core/54197#-Ngx2RP0Aw2pGUVmL0NX:-Ngx4QQO-Pg_zYWhnWIr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5c9ce7a8c7ad922f397aba3a5656f55f829084e9/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L655)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets leave the default value for priority i.e NORM_PRIORITY
</blockquote></details>

Done.

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
we need to update config.yml for NG Manager and Pipeline Service as well

**Review by sarthakkasat — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54197#-:-NgxQeto7zf49kkx1Ysf:bb6un1j)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/config.yml` line 338 at r7](https://reviewable.io/reviews/harness/harness-core/54197#-NhAs8raAcxqfLOGwSr7:-NhAs8raAcxqfLOGwSr8:b-jxr7u3) ([raw file](https://github.com/harness/harness-core/blob/a834bd5852fe1605304a2137925dafcf66c90792/120-ng-manager/config.yml#L338)):*
> ```YAML
>   threadPoolConfig:
>     corePoolSize: ${LOG_STREAMING_CLIENT_POOL_CORE_SIZE:-10}
>   delayToClosePrefixLogStreamInSeconds: 5
> ```

can we use environment variable here like corePoolSize ?

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2, 1 of 6 files at r5, 5 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54197)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/config/config.yml` line 267 at r7](https://reviewable.io/reviews/harness/harness-core/54197#-NhAs3wm3sNVP7emIUnp:-NhAs3wm3sNVP7emIUnq:b-jxr7u3) ([raw file](https://github.com/harness/harness-core/blob/a834bd5852fe1605304a2137925dafcf66c90792/pipeline-service/config/config.yml#L267)):*
> ```YAML
>   threadPoolConfig:
>     corePoolSize: ${LOG_STREAMING_CLIENT_POOL_CORE_SIZE:-10}
>   delayToClosePrefixLogStreamInSeconds: 5
> ```

can we use environment variable here like corePoolSize ?

**Comment by sarthakkasat** [comment]
trigger uts

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54197)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by sourabh-awashti — APPROVED** [review]

**Comment by sarthakkasat** [comment]
trigger uts

**Comment by sarthakkasat** [comment]
trigger uts

**Comment by sarthakkasat** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54197)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
trigger ut1

**Review by sourabh-awashti — APPROVED** [review]
LGTM

**Comment by sarthakkasat** [comment]
trigger review

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 6 files at r7, 4 of 4 files at r8, 4 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54197)* status: :shipit: complete! ✓

**Pull request merged**
