### PR TITLE
[feat]: [PIE-7218]: Integrating pipelineService to Audit Service

### PR DESCRIPTION
**Pull request by senjucanon2**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42948)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java` line 171 at r3](https://reviewable.io/reviews/harness/harness-core/42948#-NNC3kis7oIcNMQXocvC:-NNC3kis7oIcNMQXocvD:b-dop2nb) ([raw file](https://github.com/harness/harness-core/blob/2cf78913277b31d01792bd5e4993006cba39947d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java#L171)):*
> ```Java
> 
>     try {
>       transactionHelper.performTransaction(() -> fireInformAndSendAuditOnStart(ambiance, planExecutionMetadata));
> ```

How does transaction work here? Once outbox event is sent, will we be able to revert it in case some issue happens during "fireInform" call?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineExecutionOutboxEventHandler.java` line 78 at r3](https://reviewable.io/reviews/harness/harness-core/42948#-NNC4GmS-yqrUsOcnOCA:-NNC4GmS-yqrUsOcnOCB:b-m2cn07) ([raw file](https://github.com/harness/harness-core/blob/2cf78913277b31d01792bd5e4993006cba39947d/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineExecutionOutboxEventHandler.java#L78)):*
> ```Java
>           return handlePipelineEndEvent(outboxEvent);
>         default:
>           return false;
> ```

we should log here what was the event type that wasn't registered

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineExecutionOutboxEventHandler.java` line 81 at r3](https://reviewable.io/reviews/harness/harness-core/42948#-NNC4JmG4sAP4l6DBhv-:-NNC4JmG4sAP4l6DBhv0:b-525v0j) ([raw file](https://github.com/harness/harness-core/blob/2cf78913277b31d01792bd5e4993006cba39947d/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineExecutionOutboxEventHandler.java#L81)):*
> ```Java
>       }
>     } catch (IOException ex) {
>       return false;
> ```

we should log exception here

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineExecutionOutboxEventHandler.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/42948#-NNC4Y5xAxAz4e-PYCT_:-NNC4Y5xAxAz4e-PYCTa:b9xof2b) ([raw file](https://github.com/harness/harness-core/blob/2cf78913277b31d01792bd5e4993006cba39947d/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineExecutionOutboxEventHandler.java#L55)):*
> ```Java
>                                 .build();
>     return auditClientService.publishAudit(auditEntry, globalContext);
>   }
> ```

leave a blank line here

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineExecutionOutboxEventHandler.java` line 58 at r3](https://reviewable.io/reviews/harness/harness-core/42948#-NNC4gA00d0knx2NPHkq:-NNC4gA00d0knx2NPHkr:biy85d5) ([raw file](https://github.com/harness/harness-core/blob/2cf78913277b31d01792bd5e4993006cba39947d/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineExecutionOutboxEventHandler.java#L58)):*
> ```Java
>   private boolean handlePipelineEndEvent(OutboxEvent outboxEvent) throws JsonProcessingException {
>     GlobalContext globalContext = outboxEvent.getGlobalContext();
>     AuditEntry auditEntry = AuditEntry.builder()
> ```

do you think we can modularize creation of auditEntry? Its taking everything from outbox event only so we can simplify it as a method itself instead of duplicating the code

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/events/PipelineEndEvent.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/42948#-NNGqWNl2TZ7PdVch1vi:-NNGqWNl2TZ7PdVch1vj:bued8q) ([raw file](https://github.com/harness/harness-core/blob/2cf78913277b31d01792bd5e4993006cba39947d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/events/PipelineEndEvent.java#L35)):*
> ```Java
> @Builder
> @NoArgsConstructor
> @JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)
> ```

Add comments explaining the use of this event class.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/events/PipelineEndEvent.java` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/42948#-NNGqgT7BHZqrGpN8G-X:-NNGqgT7BHZqrGpN8G-Y:brptdxf) ([raw file](https://github.com/harness/harness-core/blob/2cf78913277b31d01792bd5e4993006cba39947d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/events/PipelineEndEvent.java#L36)):*
> ```Java
> @NoArgsConstructor
> @JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)
> public class PipelineEndEvent implements Event {
> ```

please add Audit in the name and move to different package.  io.harness.audit.events
Do we really need this class in orchestration? Can we move it in some other module?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/events/PipelineStartEvent.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/42948#-NNGrP4T2FN6irXogSRp:-NNGrP4T2FN6irXogSRq:b-j79tnw) ([raw file](https://github.com/harness/harness-core/blob/2cf78913277b31d01792bd5e4993006cba39947d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/events/PipelineStartEvent.java#L35)):*
> ```Java
> @NoArgsConstructor
> @JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)
> public class PipelineStartEvent implements Event {
> ```

same as PipelineEndEvent.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java` line 171 at r3](https://reviewable.io/reviews/harness/harness-core/42948#-NNGrV099R-juPpnuojM:-NNGrV0AAQH8G05KFaok:bu0itb7) ([raw file](https://github.com/harness/harness-core/blob/2cf78913277b31d01792bd5e4993006cba39947d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java#L171)):*
> ```Java
> 
>     try {
>       transactionHelper.performTransaction(() -> fireInformAndSendAuditOnStart(ambiance, planExecutionMetadata));
> ```

As discussed, we should add audits via observer and not directly call in PlanExecutionStrategy. 
One issue if we do via observer could be that the planExecution is saved but the outbox is not but this maybe a rare case. Having a dependency of audits on orchestration will cause tight coupling between engine and audits.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java` line 181 at r3](https://reviewable.io/reviews/harness/harness-core/42948#-NNGs2LrBiWPMKBqs9HD:-NNGs2LrBiWPMKBqs9HE:b-u16de3) ([raw file](https://github.com/harness/harness-core/blob/2cf78913277b31d01792bd5e4993006cba39947d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java#L181)):*
> ```Java
>   }
> 
>   private OutboxEvent fireInformAndSendAuditOnStart(Ambiance ambiance, PlanExecutionMetadata planExecutionMetadata) {
> ```

Move this to observer.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java` line 218 at r3](https://reviewable.io/reviews/harness/harness-core/42948#-NNGs5d33ITk1fMAyKik:-NNGs5d33ITk1fMAyKil:b-ikslab) ([raw file](https://github.com/harness/harness-core/blob/2cf78913277b31d01792bd5e4993006cba39947d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java#L218)):*
> ```Java
>   }
> 
>   private OutboxEvent fireInformAndSendAuditOnEnd(Ambiance ambiance) {
> ```

Same as pipeline start

**Comment by sahilhindwani-harness** [comment]
*[`platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/Action.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/42948#-NNGsXwC8UdJhCA-W8cG:-NNGsXwC8UdJhCA-W8cH:b-29wbf8) ([raw file](https://github.com/harness/harness-core/blob/2cf78913277b31d01792bd5e4993006cba39947d/platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/Action.java#L39)):*
> ```Java
>   // SLO Event
>   ERROR_BUDGET_RESET,
>   START,
> ```

PIPELINE_EXECUTION_START
PIPELINE_EXECUTION_END

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 12 files at r2, 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42948)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Pull request closed without merging**
