### PR TITLE
[feat]: [PIE-9212]: Updated scm list repos for gitlab

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Updated scm list repos for gitlab to show repos with subgroup format in the response. Have tested out the same with multiple subgroups and no subgroups.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45727)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 777 at r3](https://reviewable.io/reviews/harness/harness-core/45727#-NRbSb6k1nWDlG1l7PGH:-NRbSb6k1nWDlG1l7PGI:b-enbzyx) ([raw file](https://github.com/harness/harness-core/blob/e6954850bb67a7af5d3bb92adf928c5877eb0917/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L777)):*
> ```Java
> 
>   @VisibleForTesting
>   protected String buildRepoForGitlab(String namespace, String repoName) {
> ```

is there any better class where we can move to?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 748 at r3](https://reviewable.io/reviews/harness/harness-core/45727#-NRbUcEB4YeejyOq9m5m:-NRbUcEB4YeejyOq9m5n:b-w1souy) ([raw file](https://github.com/harness/harness-core/blob/e6954850bb67a7af5d3bb92adf928c5877eb0917/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L748)):*
> ```Java
>       return Collections.singletonList(GitRepositoryResponseDTO.builder().name(gitRepository.getName()).build());
>     } else if (isNotEmpty(gitRepository.getOrg()) && isNamespaceNotEmpty(response)) {
>       return prepareListRepoResponseWithNamespace(scmConnector, response, gitRepository);
> ```

please test out all branch listing for all git providers as its a common change that may affect others as well.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45727)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 748 at r3](https://reviewable.io/reviews/harness/harness-core/45727#-NRbUcEB4YeejyOq9m5m:-NRbUuQ89LsHnLtYuVPG:b-89vtwl) ([raw file](https://github.com/harness/harness-core/blob/e6954850bb67a7af5d3bb92adf928c5877eb0917/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L748)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please test out all branch listing for all git providers as its a common change that may affect others as well.
</blockquote></details>

yes, I have tested it our for github, BB and ado, while testing out BB on prem due to vpn or not i am not sure, it was timing out, the code hadnt reached this part though
Also, as we are explicitly checking for gitlab connector for newly introduced code, we are good 
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 777 at r3](https://reviewable.io/reviews/harness/harness-core/45727#-NRbSb6k1nWDlG1l7PGH:-NRbYKu44j0AOjMlmLjp:bkcxp76) ([raw file](https://github.com/harness/harness-core/blob/e6954850bb67a7af5d3bb92adf928c5877eb0917/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L777)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

is there any better class where we can move to?
</blockquote></details>

Thought we can move it to a util class but saw in the same class there were other two or three such helper methods, so creating just for this method wouldnt make much sense i feel. If we create such an utility class, we can probably move all such helper methods

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45727)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 777 at r3](https://reviewable.io/reviews/harness/harness-core/45727#-NRbSb6k1nWDlG1l7PGH:-NRbrpo69TbInuqv-4Ir:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6954850bb67a7af5d3bb92adf928c5877eb0917/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L777)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I agree with you but lets start from here itself. Next time we have another use-case and someone will give same logic and this code will get messier with time.

There must be already some UTIL that we can just use for such things. Check on places where we contruct repo urls.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45727)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45727)* status: :shipit: complete! ✓

**Pull request merged**
