### PR TITLE
feat: [PL-28369]: Added threshold timeout to mongo operations

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
Added default threshold of 15min for all mongo operations and made it configurable 
Added these configs for ng-manager and cg-manager for now
 These are the operations which have been added here -
 
 **stream**  - working ✅
 **count** - working ✅
 **mapReduce** - working ✅
 **executeQuery** - working ✅
 **find** - working ✅
 **findOne** - working ✅
 **findAllAndRemove** - working ✅
 **findAll** - all usages has been diverted to use find method with empty query ✅
 **findDistinct** - not work (spring mongo does not consider maxTimeMs for this operation)
 **findAndModify** - not work (spring mongo does not consider maxTimeMs for this operation)
 **findAndReplace** - not work (spring mongo does not consider maxTimeMs for this operation)
 **findAndRemove** - not work (spring mongo does not consider maxTimeMs for this operation)
 **aggregate** - not possible (need to add MaxTimeMS in aggregateOptions which is supported in spring 2.3.0, currently we are at 2.2.0)
 **aggregateStream** - not possible (need to add MaxTimeMS in aggregateOptions which is supported in spring 2.3.0, currently we are at 2.2.0)

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37923)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* Code issue 5 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37923)

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37923)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/37923#-NCxmSQF2az9J-52Y4-c:-NCxmSQF2az9J-52Y4-d:baumcxi) ([raw file](https://github.com/harness/harness-core/blob/942d54cc6cc9087fb1b3a8b77063f3517d34571d/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L47)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.PL)
> public class HMongoTemplate extends MongoTemplate implements HealthMonitor {
> ```

We can add traceQuery everywhere too. Also I dont see exists() method overidden

Have we remove usages of findAll method and blocked it?

Pls add methods here for aggregate and aggregateStream but they will not have maxtimems specified but put a comment that when spring is upgraded, this can be done for these 2 methods
___
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/37923#-NCxkJ212z0vlMgM59GE:-NCxkJ212z0vlMgM59GF:b-w7ei5r) ([raw file](https://github.com/harness/harness-core/blob/942d54cc6cc9087fb1b3a8b77063f3517d34571d/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L49)):*
> ```Java
> public class HMongoTemplate extends MongoTemplate implements HealthMonitor {
>   private static final int RETRIES = 3;
>   private static final int MAX_TIME_IN_MILLIS_FOR_MONGO_OPERATIONS = 1;
> ```

We will make it configurable.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37923)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/37923#-NCxmSQF2az9J-52Y4-c:-NCxpCFf7yn3Jo9-YebW:bp3jbx9) ([raw file](https://github.com/harness/harness-core/blob/942d54cc6cc9087fb1b3a8b77063f3517d34571d/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L47)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We can add traceQuery everywhere too. Also I dont see exists() method overidden

Have we remove usages of findAll method and blocked it?

Pls add methods here for aggregate and aggregateStream but they will not have maxtimems specified but put a comment that when spring is upgraded, this can be done for these 2 methods
</blockquote></details>

Remove all usage of -
new MongoTemplate

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 36 of 36 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37923)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/37923#-ND1Anbv6ffEGq1u8Q_Y:-ND1Anbv6ffEGq1u8Q_Z:bz1k6h) ([raw file](https://github.com/harness/harness-core/blob/b9c7fe801c2489c5ed95efae1f5a76fb11ba3867/120-ng-manager/config.yml#L98)):*
> ```YAML
>   aliasDBName: ng-harness
>   traceMode: DISABLED
>   maxProcessingTime: 900000
> ```

maxOperationTimeInMillis

I don't see corresponding change in replace_configs.sh
___
*[`360-cg-manager/config.yml` line 304 at r3](https://reviewable.io/reviews/harness/harness-core/37923#-ND1B640ErGooWixveTG:-ND1B640ErGooWixveTH:b-i0rvu1) ([raw file](https://github.com/harness/harness-core/blob/b9c7fe801c2489c5ed95efae1f5a76fb11ba3867/360-cg-manager/config.yml#L304)):*
> ```YAML
>     mongoTagValue: none
>   aliasDBName: harness
>   maxProcessingTime: 900000
> ```

maxOperationTimeInMillis.

I don't see corresponding change in replace_configs.sh
___
*[`935-analyser-service/src/main/java/io/harness/serviceinfo/ServiceInfoServiceImpl.java` line 88 at r3](https://reviewable.io/reviews/harness/harness-core/37923#-ND1BPQD6Tm5awAaiTk0:-ND1BPQD6Tm5awAaiTk1:b-jy2twb) ([raw file](https://github.com/harness/harness-core/blob/b9c7fe801c2489c5ed95efae1f5a76fb11ba3867/935-analyser-service/src/main/java/io/harness/serviceinfo/ServiceInfoServiceImpl.java#L88)):*
> ```Java
> 
>   @Override
>   public List<ServiceInfo> getAllServices() {
> ```

Can we add findAll method in HMongoTemplate and let it throw UnsupportedOperationException and mention the alternative
___
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/37923#-NCxmSQF2az9J-52Y4-c:-ND1C0hr6M_7hWNcktcB:b-eyg42p) ([raw file](https://github.com/harness/harness-core/blob/942d54cc6cc9087fb1b3a8b77063f3517d34571d/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L47)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

tracequery - added
findAll method -changed, still need to block it
added method for aggregate and aggregateStream
need to check for Mongo
</blockquote></details>

Can we check for new MongoTemplate and include it in this PR
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoConfig.java` line 111 at r3](https://reviewable.io/reviews/harness/harness-core/37923#-ND1CBgm4_Du-aQbfvKr:-ND1CBgm4_Du-aQbfvKs:b-40inog) ([raw file](https://github.com/harness/harness-core/blob/b9c7fe801c2489c5ed95efae1f5a76fb11ba3867/960-persistence/src/main/java/io/harness/mongo/MongoConfig.java#L111)):*
> ```Java
>   private AnalyticNodeMongoConfig analyticNodeConfig = AnalyticNodeMongoConfig.builder().build();
> 
>   @JsonProperty(defaultValue = "900000") @Default @NotEmpty private int maxProcessingTime = 900000;
> ```

maxOperationTimeinMillis

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37923)* status: 40 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/37923#-ND1Anbv6ffEGq1u8Q_Y:-ND2E8eC2oBIxyXzkQJl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b9c7fe801c2489c5ed95efae1f5a76fb11ba3867/120-ng-manager/config.yml#L98)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

maxOperationTimeInMillis

I don't see corresponding change in replace_configs.sh
</blockquote></details>

Done.
___
*[`360-cg-manager/config.yml` line 304 at r3](https://reviewable.io/reviews/harness/harness-core/37923#-ND1B640ErGooWixveTG:-ND2EAEmDxrVpzwybDBW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b9c7fe801c2489c5ed95efae1f5a76fb11ba3867/360-cg-manager/config.yml#L304)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

maxOperationTimeInMillis.

I don't see corresponding change in replace_configs.sh
</blockquote></details>

Done.
___
*[`935-analyser-service/src/main/java/io/harness/serviceinfo/ServiceInfoServiceImpl.java` line 88 at r3](https://reviewable.io/reviews/harness/harness-core/37923#-ND1BPQD6Tm5awAaiTk0:-ND2EBZtCvBepKrpfb7o:b-k1mdwo) ([raw file](https://github.com/harness/harness-core/blob/b9c7fe801c2489c5ed95efae1f5a76fb11ba3867/935-analyser-service/src/main/java/io/harness/serviceinfo/ServiceInfoServiceImpl.java#L88)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we add findAll method in HMongoTemplate and let it throw UnsupportedOperationException and mention the alternative
</blockquote></details>

IMO instead of throwing exception, we can call find method from here directly
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoConfig.java` line 111 at r3](https://reviewable.io/reviews/harness/harness-core/37923#-ND1CBgm4_Du-aQbfvKr:-ND2EO4kEBuxmlsHZ4el:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b9c7fe801c2489c5ed95efae1f5a76fb11ba3867/960-persistence/src/main/java/io/harness/mongo/MongoConfig.java#L111)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

maxOperationTimeinMillis
</blockquote></details>

Done.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37923)* status: 40 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/37923#-NCxmSQF2az9J-52Y4-c:-ND2FMIO8PszH1wPSTTw:bfhofe7) ([raw file](https://github.com/harness/harness-core/blob/942d54cc6cc9087fb1b3a8b77063f3517d34571d/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L47)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we check for new MongoTemplate and include it in this PR
</blockquote></details>

There are no use cases for new MongoTemplate

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37923)* status: 40 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`935-analyser-service/src/main/java/io/harness/serviceinfo/ServiceInfoServiceImpl.java` line 88 at r3](https://reviewable.io/reviews/harness/harness-core/37923#-ND1BPQD6Tm5awAaiTk0:-ND2Gi-Q9svuxEzjkbYa:b9146l5) ([raw file](https://github.com/harness/harness-core/blob/b9c7fe801c2489c5ed95efae1f5a76fb11ba3867/935-analyser-service/src/main/java/io/harness/serviceinfo/ServiceInfoServiceImpl.java#L88)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

IMO instead of throwing exception, we can call find method from here directly
</blockquote></details>

Lets do that

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37923)* status: 40 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`935-analyser-service/src/main/java/io/harness/serviceinfo/ServiceInfoServiceImpl.java` line 88 at r3](https://reviewable.io/reviews/harness/harness-core/37923#-ND1BPQD6Tm5awAaiTk0:-ND2Grj81Sd-3KyuU44j:b-yl8dbo) ([raw file](https://github.com/harness/harness-core/blob/b9c7fe801c2489c5ed95efae1f5a76fb11ba3867/935-analyser-service/src/main/java/io/harness/serviceinfo/ServiceInfoServiceImpl.java#L88)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Lets do that
</blockquote></details>

that is already done

**Review by ankit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37923)* status: 40 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37923#-:-ND2HUwlDRkniWU9fO7O:bnfp4nl)* status: 40 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 94 at r4](https://reviewable.io/reviews/harness/harness-core/37923#-ND2IgTz0GzytrZZSzpB:-ND2IgTz0GzytrZZSzpC:be97j75) ([raw file](https://github.com/harness/harness-core/blob/52be919085d7976fd81b735e7b6e028f8a5c1123/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L94)):*
> ```Java
>       return super.findAndModify(query, update, options, entityClass, collectionName);
>     } catch (UncategorizedMongoDbException ex) {
>       log.error("query {} exceeded max time limit.", query);
> ```

can we also mention the max time limit here? As its configurable, so good to have it in the logs.

**Comment by mohitg0795** [comment]
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 94 at r4](https://reviewable.io/reviews/harness/harness-core/37923#-ND2IgTz0GzytrZZSzpB:-ND2InlNDryfxiPSrFts:bxxiwo2) ([raw file](https://github.com/harness/harness-core/blob/52be919085d7976fd81b735e7b6e028f8a5c1123/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L94)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we also mention the max time limit here? As its configurable, so good to have it in the logs.
</blockquote></details>

Or when we log the query, its already being logged? If yes, then its fine.

**Comment by mohitg0795** [comment]
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 139 at r4](https://reviewable.io/reviews/harness/harness-core/37923#-ND2IvVm5k7nleOknO6B:-ND2IvVm5k7nleOknO6C:b2la087) ([raw file](https://github.com/harness/harness-core/blob/52be919085d7976fd81b735e7b6e028f8a5c1123/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L139)):*
> ```Java
>       return super.findOne(query, entityClass, collectionName);
>     } catch (UncategorizedMongoDbException ex) {
>       log.error("query {} exceeded max time limit.", query);
> ```

can we carve out it as a constant as its being used across the file?

**Comment by bhavya181** [comment]
trigger ti0

**Review by rijajoo — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r2, 27 of 36 files at r3, 1 of 6 files at r4, 34 of 36 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37923#-:-NDDdwES-rAFNHZXdICE:bnfp4nl)* status: 39 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by rijajoo — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37923)* status: 39 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Pull request merged**
