### PR TITLE
[feat]: [PIE-4390]: Adding mode in Expression engine to return original expression if unresolved in renderExpression

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Currently, we have two options when an expression is unresolved, either throw an exception or return null as expression value. 
But in some cases we want to return the original expression if it is not resolved. 
Adding support of expressionMode, so callers can provide an expression mode and according to the expressionMode, the expression engine will return the null value or original expression or throw exception.
This PR adds the mode and integrates it with renderExpression flow to return the expression according to the mode.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35851)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r1, 7 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35851)* status: 17 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/expression/EngineExpressionEvaluator.java` line 291 at r2](https://reviewable.io/reviews/harness/harness-core/35851#-N8NdMHS1EnF1TKkHjCk:-N8NdMHS1EnF1TKkHjCl:b-m6ejrw) ([raw file](https://github.com/harness/harness-core/blob/4559450989a56ea067e4805d3bc06d227f273596/980-commons/src/main/java/io/harness/expression/EngineExpressionEvaluator.java#L291)):*
> ```Java
>     } else {
>       return PartialEvaluateResult.createCompleteResult(
>           renderExpressionInternal(expression, ctx, depth, expressionMode));
> ```

Where we are handling exception being thrown and keeping same expression?
___
*[`980-commons/src/main/java/io/harness/text/StringReplacer.java` line 98 at r2](https://reviewable.io/reviews/harness/harness-core/35851#-N8NPAOB2Btr8IWVQ5Nx:-N8NPAOB2Btr8IWVQ5Ny:bb7d4mw) ([raw file](https://github.com/harness/harness-core/blob/4559450989a56ea067e4805d3bc06d227f273596/980-commons/src/main/java/io/harness/text/StringReplacer.java#L98)):*
> ```Java
>         String expressionValue = expressionResolver.resolve(expression);
> 
>         // If ExpressionMode is ExpressionMode.RETURN_ORIGINAL_EXPRESSION_IF_UNRESOLVED nd expression is resolved to
> ```

and*
___
*[`980-commons/src/main/java/io/harness/text/StringReplacer.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/35851#-N8Nd29u7sZIvMv2h39l:-N8Nd29u7sZIvMv2h39m:b-1scath) ([raw file](https://github.com/harness/harness-core/blob/4559450989a56ea067e4805d3bc06d227f273596/980-commons/src/main/java/io/harness/text/StringReplacer.java#L104)):*
> ```Java
>           expressionValue = expression;
>         } else {
>           buf.replace(expressionStartPos, expressionEndPos, expressionValue);
> ```

this should be irrespective of any mode right?



_Code quote:_
```Java
buf.replace(expressionStartPos, expressionEndPos, expressionValue);
```

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Comment by brijeshdhakar** [comment]
*[`980-commons/src/main/java/io/harness/expression/EngineExpressionEvaluator.java` line 291 at r2](https://reviewable.io/reviews/harness/harness-core/35851#-N8NdMHS1EnF1TKkHjCk:-N8PI7825XdF8mx_yhkP:b-r183us) ([raw file](https://github.com/harness/harness-core/blob/4559450989a56ea067e4805d3bc06d227f273596/980-commons/src/main/java/io/harness/expression/EngineExpressionEvaluator.java#L291)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Where we are handling exception being thrown and keeping same expression?
</blockquote></details>

In renderExpressionInternal method(), We are throwing the exception.
    if (expressionMode == ExpressionMode.THROW_EXCEPTION_IF_UNRESOLVED
        && EmptyPredicate.isNotEmpty(resolver.getUnresolvedExpressions())) {
      throw new UnresolvedExpressionsException(new ArrayList<>(resolver.getUnresolvedExpressions()));
    }

And in StringReplacer, where we replace the expression with its evaluated value, we are checking for the expression mode and evaluated value, if the value is null then we will not replace and keep the expression as it is.

**Comment by brijeshdhakar** [comment]
*[`980-commons/src/main/java/io/harness/text/StringReplacer.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/35851#-N8Nd29u7sZIvMv2h39l:-N8PImbWClF679UUtMX3:bo4q3yc) ([raw file](https://github.com/harness/harness-core/blob/4559450989a56ea067e4805d3bc06d227f273596/980-commons/src/main/java/io/harness/text/StringReplacer.java#L104)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this should be irrespective of any mode right?
</blockquote></details>

If the mode RETURBN_NULL_IF_NOT_RESOLVED or , THROW_EXCEPTION_IF_NOT_RESOLVED then we will replace the expression with null value(if expression value does not resolve to any value), This is what happens till now.
But now we are adding the support to keep the expression intact, so if the mode is RETURN_ORIGINAL_EXPRESSION_IF_UNRESOLVED and value is null, then we will not replace the expression with null string.

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35851)

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 9 of 13 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35851)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r1, 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35851)* status: Some of the checks are too old. 1 change requests. 1 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/text/StringReplacer.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/35851#-N8Nd29u7sZIvMv2h39l:-N8T5GXr8F3-RjthCtcD:bgcgm1) ([raw file](https://github.com/harness/harness-core/blob/4559450989a56ea067e4805d3bc06d227f273596/980-commons/src/main/java/io/harness/text/StringReplacer.java#L104)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

If the mode RETURBN_NULL_IF_NOT_RESOLVED or , THROW_EXCEPTION_IF_NOT_RESOLVED then we will replace the expression with null value(if expression value does not resolve to any value), This is what happens till now.
But now we are adding the support to keep the expression intact, so if the mode is RETURN_ORIGINAL_EXPRESSION_IF_UNRESOLVED and value is null, then we will not replace the expression with null string.
</blockquote></details>

We should not make changes in StringReplacer, we should handle this in ExpressionResolver implementations

**Comment by brijeshdhakar** [comment]
*[`980-commons/src/main/java/io/harness/text/StringReplacer.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/35851#-N8Nd29u7sZIvMv2h39l:-N8e9mWQCO2cWarRmuHs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4559450989a56ea067e4805d3bc06d227f273596/980-commons/src/main/java/io/harness/text/StringReplacer.java#L104)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

We should not make changes in StringReplacer, we should handle this in ExpressionResolver implementations
</blockquote></details>

Done.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35851)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35851)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`980-commons/src/test/java/io/harness/text/StringReplacerTest.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/35851#-N8gMBZXBA9Uzt6d8n68:-N8gMBZXBA9Uzt6d8n69:b-a9ac28) ([raw file](https://github.com/harness/harness-core/blob/79b207d1036bd2bcf48c63201d031a19d58161cd/980-commons/src/test/java/io/harness/text/StringReplacerTest.java#L65)):*
> ```Java
>   @Owner(developers = BRIJESH)
>   @Category(UnitTests.class)
>   public void testStringReplacerWithExpressionModes() {
> ```

Move the test to AmbianceExpressionEvaluatorTest using AmbianceExpressionEvaluator



_Code quote:_
```Java
  @Test
  @Owner(developers = BRIJESH)
  @Category(UnitTests.class)
  public void testStringReplacerWithExpressionModes() {
```

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35851)* status: 2 change requests. 1 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/expression/ExpressionMode.java` line 8 at r3](https://reviewable.io/reviews/harness/harness-core/35851#-N8gex762LGZI0hJfZKh:-N8gex762LGZI0hJfZKi:b49v3h3) ([raw file](https://github.com/harness/harness-core/blob/79b207d1036bd2bcf48c63201d031a19d58161cd/980-commons/src/main/java/io/harness/expression/ExpressionMode.java#L8)):*
> ```Java
>                              // resolved.
>   RETURN_ORIGINAL_EXPRESSION_IF_UNRESOLVED // Expression engine should return original expression itself as expression
>                                            // value if that expression is not resolved.
> ```

You can use /* comment */ instead of adding comment for each enum as clean code practise 
___
*[`980-commons/src/test/java/io/harness/text/DummyExpressionResolver.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/35851#-N8gfCnJDMXiESTXexl2:-N8gfCnJDMXiESTXexl3:b63xz6x) ([raw file](https://github.com/harness/harness-core/blob/79b207d1036bd2bcf48c63201d031a19d58161cd/980-commons/src/test/java/io/harness/text/DummyExpressionResolver.java#L27)):*
> ```Java
>   public String resolveInternal(String expression) {
>     if (expression.equals(notToResolveExpression)) {
>       return "null";
> ```

can we use constant here?

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35851)* status: 5 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/expression/ExpressionMode.java` line 8 at r3](https://reviewable.io/reviews/harness/harness-core/35851#-N8gex762LGZI0hJfZKh:-N8hU8JLBwEaI8b9ffUp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/79b207d1036bd2bcf48c63201d031a19d58161cd/980-commons/src/main/java/io/harness/expression/ExpressionMode.java#L8)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

You can use /* comment */ instead of adding comment for each enum as clean code practise 
</blockquote></details>

Done.
___
*[`980-commons/src/test/java/io/harness/text/DummyExpressionResolver.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/35851#-N8gfCnJDMXiESTXexl2:-N8hU9AD58dL0ZRNNaJG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/79b207d1036bd2bcf48c63201d031a19d58161cd/980-commons/src/test/java/io/harness/text/DummyExpressionResolver.java#L27)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

can we use constant here?
</blockquote></details>

Done.
___
*[`980-commons/src/test/java/io/harness/text/StringReplacerTest.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/35851#-N8gMBZXBA9Uzt6d8n68:-N8hUCwmDUmSQ882SI_t:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/79b207d1036bd2bcf48c63201d031a19d58161cd/980-commons/src/test/java/io/harness/text/StringReplacerTest.java#L65)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Move the test to AmbianceExpressionEvaluatorTest using AmbianceExpressionEvaluator
</blockquote></details>

Done.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35851)* status: 5 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35851)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35851)* status: Some of the checks are too old. 1 change requests.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 5 of 13 files at r1, 6 of 8 files at r2, 4 of 6 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35851)* status: Some of the checks are too old.

**Pull request merged**
