### PR TITLE
feat: [PIE-9166]: create DTOs for userSourceCodeManagers

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45721)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/AzureRepoSCMDTO.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/45721#-NRbjALC1Yflw5HNVyiA:-NRbjALD8Fv1XvAlkty8:bh2bp5o) ([raw file](https://github.com/harness/harness-core/blob/5200fb658f37fa315af6f53a65656573ea15dfe9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/AzureRepoSCMDTO.java#L35)):*
> ```Java
> @EqualsAndHashCode(callSuper = true)
> public class AzureRepoSCMDTO extends UserSourceCodeManagerDTO {
>   @JsonProperty("apiAccess") AzureRepoApiAccessDTO apiAccess;
> ```

why's json property required?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java` line 76 at r3](https://reviewable.io/reviews/harness/harness-core/45721#-NRbjQw4Dkp_bkwvrgK6:-NRbjQw4Dkp_bkwvrgK7:b-7eybv7) ([raw file](https://github.com/harness/harness-core/blob/5200fb658f37fa315af6f53a65656573ea15dfe9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java#L76)):*
> ```Java
>       , @Content(mediaType = APPLICATION_YAML_MEDIA_TYPE, schema = @Schema(implementation = ErrorDTO.class))
>     })
> public class UserSourceCodeManagerResource {
> ```

all the APIs will be hidden from swagger, so we should use @hidden

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45721)* status: 22 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java` line 76 at r3](https://reviewable.io/reviews/harness/harness-core/45721#-NRbjQw4Dkp_bkwvrgK6:-NRc2PZ-9tD8imKrMkCd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5200fb658f37fa315af6f53a65656573ea15dfe9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java#L76)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

all the APIs will be hidden from swagger, so we should use @hidden
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/AzureRepoSCMDTO.java` line 30 at r7](https://reviewable.io/reviews/harness/harness-core/45721#-NRgboWf09LOWnt24Ukp:-NRgboWf09LOWnt24Ukq:b9mk3to) ([raw file](https://github.com/harness/harness-core/blob/997ce5a478d40c6edae9d1fe59796612627c2d32/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/AzureRepoSCMDTO.java#L30)):*
> ```Java
> @Data
> @SuperBuilder
> @Schema(name = "AzureRepoSCM", description = "This Contains details of the AzureRepo User Source Code Manager")
> ```

these annotations should be removed.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/AzureRepoSCMDTO.java` line 23 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgc9A8D12mqNLvwky7:-NRgc9A8D12mqNLvwky8:bp328im) ([raw file](https://github.com/harness/harness-core/blob/2500c6afa7fb33395448a75b248e509ede91a4a6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/AzureRepoSCMDTO.java#L23)):*
> ```Java
> @SuperBuilder
> public class AzureRepoSCMDTO extends UserSourceCodeManagerDTO {
>   AzureRepoApiAccessDTO apiAccess;
> ```

I think there's some annotation to make all fields private by default. Please check that and use it here or else we can declare it private explicitly.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GithubSCMDTO.java` line 24 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgce7f4HLTwEmd-5SR:-NRgce7f4HLTwEmd-5SS:b8vksar) ([raw file](https://github.com/harness/harness-core/blob/2500c6afa7fb33395448a75b248e509ede91a4a6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GithubSCMDTO.java#L24)):*
> ```Java
> public class GithubSCMDTO extends UserSourceCodeManagerDTO {
>   GithubApiAccessDTO apiAccess;
>   @Override
> ```

blank line missing.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GithubSCMDTO.java` line 23 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgcfl4ArtdLvOdgcxM:-NRgcfl4ArtdLvOdgcxN:b-whdxy4) ([raw file](https://github.com/harness/harness-core/blob/2500c6afa7fb33395448a75b248e509ede91a4a6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GithubSCMDTO.java#L23)):*
> ```Java
> @SuperBuilder
> public class GithubSCMDTO extends UserSourceCodeManagerDTO {
>   GithubApiAccessDTO apiAccess;
> ```

similar comments like mentioned above for other same classes

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GithubSCMRequestDTO.java` line 24 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgclbx8kPbB1IZOwvF:-NRgclbx8kPbB1IZOwvG:b-kv95v8) ([raw file](https://github.com/harness/harness-core/blob/2500c6afa7fb33395448a75b248e509ede91a4a6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GithubSCMRequestDTO.java#L24)):*
> ```Java
> public class GithubSCMRequestDTO extends UserSourceCodeManagerRequestDTO {
>   @JsonProperty("apiAccess") GithubApiAccessDTO apiAccess;
>   @Override
> ```

blank line missing. Please check in other places as well.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GithubSCMResponseDTO.java` line 28 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgcuHi465X1D0AW6r6:-NRgcuHi465X1D0AW6r7:bbkm5mg) ([raw file](https://github.com/harness/harness-core/blob/2500c6afa7fb33395448a75b248e509ede91a4a6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GithubSCMResponseDTO.java#L28)):*
> ```Java
>   }
> 
>   public GithubApiAccessDTO getApiAccess() {
> ```

why's this getter declared explicitly and no lombok annotation used for it?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/UserSourceCodeManagerRequestDTO.java` line 23 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgeTYL5kFQwRenMNh5:-NRgeTYL5kFQwRenMNh6:b-2cg36f) ([raw file](https://github.com/harness/harness-core/blob/2500c6afa7fb33395448a75b248e509ede91a4a6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/UserSourceCodeManagerRequestDTO.java#L23)):*
> ```Java
> @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", include = JsonTypeInfo.As.EXISTING_PROPERTY)
> public abstract class UserSourceCodeManagerRequestDTO {
>   @Schema(description = NGCommonEntityConstants.ACCOUNT_PARAM_MESSAGE) @FdIndex String accountIdentifier;
> ```

why's FdIndex used here?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/UserSourceCodeManagerRequestDTO.java` line 23 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgeXjh0edzkgETOWWf:-NRgeXjh0edzkgETOWWg:b-36vjrh) ([raw file](https://github.com/harness/harness-core/blob/2500c6afa7fb33395448a75b248e509ede91a4a6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/UserSourceCodeManagerRequestDTO.java#L23)):*
> ```Java
> @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", include = JsonTypeInfo.As.EXISTING_PROPERTY)
> public abstract class UserSourceCodeManagerRequestDTO {
>   @Schema(description = NGCommonEntityConstants.ACCOUNT_PARAM_MESSAGE) @FdIndex String accountIdentifier;
> ```

we don't need to add any schema annotations as we are anyways hiding the APIs from swagger.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/UserSourceCodeManagerRequestDTO.java` line 19 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgecNr8Dk0lQ3bD2od:-NRgecNr8Dk0lQ3bD2oe:b-1rkm79) ([raw file](https://github.com/harness/harness-core/blob/2500c6afa7fb33395448a75b248e509ede91a4a6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/UserSourceCodeManagerRequestDTO.java#L19)):*
> ```Java
> import lombok.Data;
> 
> @Data
> ```

why's data required here? I think only Getters should be required for request dtos.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/mappers/AzureRepoSCMMapper.java` line 17 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRggXiF0DS9BxUE6cWe:-NRggXiF0DS9BxUE6cWf:b-ucal41) ([raw file](https://github.com/harness/harness-core/blob/2500c6afa7fb33395448a75b248e509ede91a4a6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/mappers/AzureRepoSCMMapper.java#L17)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public class AzureRepoSCMMapper extends UserSourceCodeManagerMapper<AzureRepoSCMDTO, AzureRepoSCM> {
>   AzureRepoSCM toEntityInternal(AzureRepoSCMDTO sourceCodeManagerDTO) {
> ```

what does "internal" means here.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/mappers/AzureRepoSCMResponseMapper.java` line 18 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgggMU8DdUtktPWvSF:-NRgggMU8DdUtktPWvSG:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/2500c6afa7fb33395448a75b248e509ede91a4a6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/mappers/AzureRepoSCMResponseMapper.java#L18)):*
> ```Java
> public class AzureRepoSCMResponseMapper
>     extends UserSourceCodeManagerResponseMapper<AzureRepoSCMResponseDTO, AzureRepoSCMDTO> {
>   @Override
> ```

same

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45721)* status: 38 file(s) to review. 15. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/AzureRepoSCMDTO.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/45721#-NRbjALC1Yflw5HNVyiA:-NRgkG9G6v7nWLJytSYR:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/5200fb658f37fa315af6f53a65656573ea15dfe9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/AzureRepoSCMDTO.java#L35)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why's json property required?
</blockquote></details>

removed
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/AzureRepoSCMDTO.java` line 23 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgc9A8D12mqNLvwky7:-NRgkQa-5yGb1tDpn5nn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/28e737d2743e2c8305a4bc968dd0c2231792be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/AzureRepoSCMDTO.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think there's some annotation to make all fields private by default. Please check that and use it here or else we can declare it private explicitly.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GithubSCMDTO.java` line 23 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgcfl4ArtdLvOdgcxM:-NRgkF-S0lRwQwPgMeb0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/28e737d2743e2c8305a4bc968dd0c2231792be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GithubSCMDTO.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

similar comments like mentioned above for other same classes
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GithubSCMDTO.java` line 24 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgce7f4HLTwEmd-5SR:-NRgmTPo6xxfvlNMD50Q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/28e737d2743e2c8305a4bc968dd0c2231792be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GithubSCMDTO.java#L24)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

blank line missing.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GithubSCMRequestDTO.java` line 24 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgclbx8kPbB1IZOwvF:-NRgmToV2LDEsGvRGvUR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/28e737d2743e2c8305a4bc968dd0c2231792be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GithubSCMRequestDTO.java#L24)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

blank line missing. Please check in other places as well.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GithubSCMResponseDTO.java` line 28 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgcuHi465X1D0AW6r6:-NRgkTo2BFVUvg98fLi7:bs33eh1) ([raw file](https://github.com/harness/harness-core/blob/28e737d2743e2c8305a4bc968dd0c2231792be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GithubSCMResponseDTO.java#L28)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why's this getter declared explicitly and no lombok annotation used for it?
</blockquote></details>

i guess i clicked on intellij suggestion and it added it here, reverted now
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/UserSourceCodeManagerRequestDTO.java` line 19 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgecNr8Dk0lQ3bD2od:-NRgky0w4DUvm0McgizC:br35ac1) ([raw file](https://github.com/harness/harness-core/blob/28e737d2743e2c8305a4bc968dd0c2231792be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/UserSourceCodeManagerRequestDTO.java#L19)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why's data required here? I think only Getters should be required for request dtos.
</blockquote></details>

replaced with @Value for getters
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/UserSourceCodeManagerRequestDTO.java` line 23 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgeXjh0edzkgETOWWf:-NRgl1hfCQNVyWSsr7tD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/28e737d2743e2c8305a4bc968dd0c2231792be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/UserSourceCodeManagerRequestDTO.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we don't need to add any schema annotations as we are anyways hiding the APIs from swagger.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/UserSourceCodeManagerRequestDTO.java` line 23 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgeTYL5kFQwRenMNh5:-NRgmaC13Qf4zv28GD4a:b3vupqj) ([raw file](https://github.com/harness/harness-core/blob/28e737d2743e2c8305a4bc968dd0c2231792be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/UserSourceCodeManagerRequestDTO.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why's FdIndex used here?
</blockquote></details>

it's not, just need on entity level class, removed from here
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/UserSourceCodeManagerResponseDTO.java` line 22 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgekHaBw8UDwyehuOK:-NRglVCXCL7sozlBAJ1c:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/28e737d2743e2c8305a4bc968dd0c2231792be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/UserSourceCodeManagerResponseDTO.java#L22)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/mappers/AzureRepoApiAccessMapper.java` line 24 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgf-4E1taCAy1MXNSX:-NRgnzs_7SAVUDLOSQD6:b8x16a7) ([raw file](https://github.com/harness/harness-core/blob/28e737d2743e2c8305a4bc968dd0c2231792be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/mappers/AzureRepoApiAccessMapper.java#L24)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

do you think the method naming can be improved here and simplified? It looks more like a helper class method rather than a mapper class method.
</blockquote></details>

Actually, this is still a mapper for apiAccessType, renamed method names to `toDTO` and `toApiAccess` for making this simpler
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/mappers/AzureRepoSCMMapper.java` line 17 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRggXiF0DS9BxUE6cWe:-NRgmgy-A8fOczi8aWeq:b-dd42hs) ([raw file](https://github.com/harness/harness-core/blob/28e737d2743e2c8305a4bc968dd0c2231792be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/mappers/AzureRepoSCMMapper.java#L17)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what does "internal" means here.
</blockquote></details>

we are using this abstract method inside a public method in parent class, since input and output parameters are same, we could not name this `toEntity` as well, so, as it is used internally in` toEntity`, I named it t`oEntityInternal`.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/mappers/AzureRepoSCMRequestMapper.java` line 18 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRggeH881c8n0MNEYRf:-NRgn20L2B2QC3iJdz3X:b-hzzxef) ([raw file](https://github.com/harness/harness-core/blob/28e737d2743e2c8305a4bc968dd0c2231792be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/mappers/AzureRepoSCMRequestMapper.java#L18)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think override won't come here.
</blockquote></details>

it would be because we are overriding this method that is declared abstract in the parent class.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/mappers/AzureRepoSCMResponseMapper.java` line 18 at r8](https://reviewable.io/reviews/harness/harness-core/45721#-NRgggMU8DdUtktPWvSF:-NRgnGXkD13iW6-beQd2:b-9mhvz5) ([raw file](https://github.com/harness/harness-core/blob/28e737d2743e2c8305a4bc968dd0c2231792be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/mappers/AzureRepoSCMResponseMapper.java#L18)):*
> it would be because we are overriding this method that is declared abstract in the parent class.

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 1 of 10 files at r2, 1 of 3 files at r3, 3 of 14 files at r4, 12 of 23 files at r6, 5 of 5 files at r7, 13 of 16 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45721)* status: 38 file(s) to review. 16. unresolved discussions. 1 of 2 approvals obtained.

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 16 of 16 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45721)* status: 38 file(s) to review. 16. unresolved discussions. 1 of 2 approvals obtained.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 1 of 10 files at r2, 1 of 3 files at r3, 2 of 14 files at r4, 4 of 23 files at r6, 4 of 5 files at r7, 10 of 16 files at r9, 16 of 16 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45721)* status: 16. unresolved discussions.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 10 files at r2, 1 of 3 files at r3, 2 of 14 files at r4, 4 of 23 files at r6, 4 of 5 files at r7, 10 of 16 files at r9, 16 of 16 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45721)* status: :shipit: complete! ✓

**Pull request merged**
