### PR TITLE
feat: [PL-30938]: added logs for debugging support accounts issue

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
support accounts are not loading for some Harness User Group users, added the logs to debug the issue.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42662)

### CODE REVIEW

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42662)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/IdentityServiceResource.java` line 163 at r1](https://reviewable.io/reviews/harness/harness-core/42662#-NLvMY479HQ1XRPQisy0:-NLvMY48AgN_cf1BkeCa:bwyqeer) ([raw file](https://github.com/harness/harness-core/blob/a6d4e04df69e2b9a2786d2dc39718cbd707512cd/400-rest/src/main/java/software/wings/resources/IdentityServiceResource.java#L163)):*
> ```Java
>       throw new WingsException(USER_DOES_NOT_EXIST, USER);
>     } else {
>       log.info("Trying to get user {} details", user);
> ```

This can print sensitive information like password as well because we are passing whole user object.

Lets print only relevant info like email
___
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 546 at r1](https://reviewable.io/reviews/harness/harness-core/42662#-NLvMgiX49VyE3CSrhz9:-NLvMgiX49VyE3CSrhzA:bbxgkzp) ([raw file](https://github.com/harness/harness-core/blob/a6d4e04df69e2b9a2786d2dc39718cbd707512cd/400-rest/src/main/java/software/wings/resources/UserResource.java#L546)):*
> ```Java
>     logContext.put("contextKey", String.valueOf(UUID.randomUUID()));
>     try (AutoLogContext ignore1 = new AutoLogContext(logContext, OVERRIDE_ERROR)) {
>       log.info("Loading support accounts for users/user endpoint for user {}", user);
> ```

Same comment as above
___
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 751 at r1](https://reviewable.io/reviews/harness/harness-core/42662#-NLvMplk-Bah4WUuJ7zI:-NLvMplk-Bah4WUuJ7zJ:b-imnqg9) ([raw file](https://github.com/harness/harness-core/blob/a6d4e04df69e2b9a2786d2dc39718cbd707512cd/400-rest/src/main/java/software/wings/resources/UserResource.java#L751)):*
> ```Java
> 
>     validateCaptchaToken(captchaToken);
>     log.info("Trying to login to account {} having request {}", accountId, loginBody);
> ```

Would it print any sensitive information? 
___
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 302 at r1](https://reviewable.io/reviews/harness/harness-core/42662#-NLvMt_A-VomOMu4YKen:-NLvMt_A-VomOMu4YKeo:bbxgkzp) ([raw file](https://github.com/harness/harness-core/blob/a6d4e04df69e2b9a2786d2dc39718cbd707512cd/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L302)):*
> ```Java
>       }
>     }
>     log.info("Login successful for user {}", user);
> ```

Same comment as above

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42662)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/IdentityServiceResource.java` line 163 at r1](https://reviewable.io/reviews/harness/harness-core/42662#-NLvMY479HQ1XRPQisy0:-NLvTj8WEfEI2jl8mHkb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a6d4e04df69e2b9a2786d2dc39718cbd707512cd/400-rest/src/main/java/software/wings/resources/IdentityServiceResource.java#L163)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This can print sensitive information like password as well because we are passing whole user object.

Lets print only relevant info like email
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 546 at r1](https://reviewable.io/reviews/harness/harness-core/42662#-NLvMgiX49VyE3CSrhz9:-NLvTjeN4eaq7IUDDN-4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a6d4e04df69e2b9a2786d2dc39718cbd707512cd/400-rest/src/main/java/software/wings/resources/UserResource.java#L546)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Same comment as above
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 751 at r1](https://reviewable.io/reviews/harness/harness-core/42662#-NLvMplk-Bah4WUuJ7zI:-NLvTkBLEJAiIOcbsHY8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a6d4e04df69e2b9a2786d2dc39718cbd707512cd/400-rest/src/main/java/software/wings/resources/UserResource.java#L751)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Would it print any sensitive information? 
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 302 at r1](https://reviewable.io/reviews/harness/harness-core/42662#-NLvMt_A-VomOMu4YKen:-NLvTlS70FLrEJtRusE_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a6d4e04df69e2b9a2786d2dc39718cbd707512cd/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L302)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Same comment as above
</blockquote></details>

Done.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42662)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 838 at r2](https://reviewable.io/reviews/harness/harness-core/42662#-NLwp4z2AqX2NQYvkk1-:-NLwp4z2AqX2NQYvkk10:b-snc1qi) ([raw file](https://github.com/harness/harness-core/blob/9bf9749146ee902f8fa13a277e10ec6b1b70b19a/400-rest/src/main/java/software/wings/resources/UserResource.java#L838)):*
> ```Java
>   @ExceptionMetered
>   public RestResponse<User> redirectlogin(SsoRedirectRequest request) {
>     log.info("SSO login {}", request);
> ```

This will print jwtToken

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42662)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 838 at r2](https://reviewable.io/reviews/harness/harness-core/42662#-NLwp4z2AqX2NQYvkk1-:-NLywULF5yEb4XeBlksS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9bf9749146ee902f8fa13a277e10ec6b1b70b19a/400-rest/src/main/java/software/wings/resources/UserResource.java#L838)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This will print jwtToken
</blockquote></details>

Done.

**Pull request closed without merging**
