### PR TITLE
fix: [DEL-6278]: Add a check in delegate startup so that legacy delegate image is not used for immutable delegate installation

### PR DESCRIPTION
**Pull request by raghuAtWings**
## Describe your changes
Adding a check in delegate startup so that legacy delegate image is not used for immutable delegate installation

**Tests done**
1. ran cg kubernetes delegates with delegate:latest and delegate:YY.MM.XXXX tags
2. ran ng kubernetes delegates with delegate:latest and delegate:YY.MM.XXXX tags 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47381)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
trigger messagecheck

**Comment by raghuAtWings** [comment]
trigger uts

**Review by xingchi-jin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47381)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 477 at r1](https://reviewable.io/reviews/harness/harness-core/47381#-NUdVJ5O1s_FPOsp36ce:-NUdVJ5O1s_FPOsp36cf:b-lccbdy) ([raw file](https://github.com/harness/harness-core/blob/92323439803a9daa91888ba61b624ae5f825bdf2/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L477)):*
> ```Java
>    */
>   @SuppressWarnings("PMD")
>   private void checkForImmutableAndStatefulset() {
> ```

rename to.  checkForMismatchBetweenImageAndK8sResourceType

add comment below, since the method is not very straightforward. 

1.  Use "isImmutableDelegate" to determine whether it's an immutable image or legacy image
2. Use  Integer.parseInt(HOST_NAME.substring(index + 1))  to determine whether it's statefulset or deployment. If NumberFormatException happens, it's statefulset. 
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 497 at r1](https://reviewable.io/reviews/harness/harness-core/47381#-NUdWLycA0j-pcH1K3cS:-NUdWLyd5uNM-WuhWQCG:b-2l6kuv) ([raw file](https://github.com/harness/harness-core/blob/92323439803a9daa91888ba61b624ae5f825bdf2/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L497)):*
> ```Java
>     } catch (NumberFormatException e) {
>       log.info("{} is not from a stateful set, checking whether its using immutable image", HOST_NAME);
>       if (getVersion().startsWith("1.0")) {
> ```

why not use "isImmutableDelegate" flag to determine whether it's legacy image or immutable image ?

**Review by xingchi-jin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47381)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 497 at r1](https://reviewable.io/reviews/harness/harness-core/47381#-NUdWLycA0j-pcH1K3cS:-NUdWamN228FySo165Xz:b2cxuc8) ([raw file](https://github.com/harness/harness-core/blob/92323439803a9daa91888ba61b624ae5f825bdf2/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L497)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

why not use "isImmutableDelegate" flag to determine whether it's legacy image or immutable image ? 
</blockquote></details>

this flag is hardcoded for immutable and legacy. it's not loaded from env

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47381)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
trigger utAll

**Comment by raghuAtWings** [comment]
trigger uts

**Pull request merged**
