### PR TITLE
[feat]: [CVS-6133]: adding resource layer test cases for SLO

### PR DESCRIPTION
**Pull request by deepak-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30987)

### CODE REVIEW

**Comment by deepak-harness** [comment]
trigger messagecheck

**Comment by deepak-harness** [comment]
trigger ti0

**Comment by deepak-harness** [comment]
trigger ti1

**Comment by deepak-harness** [comment]
trigger ti2

**Comment by deepak-harness** [comment]
trigger ti3

**Comment by deepak-harness** [comment]
trigger ti4

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30987#-:-MwizLT7BLrDWE8pdvan:bnfp4nl)* status: :shipit: complete! ✓

___
*[300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveResourceTest.java, line 100 at r1](https://reviewable.io/reviews/harness/harness-core/30987#-Mwiz11_49OHJLSo4Xto:-Mwiz11a2ib2q3RUufns:b3yxw9w) ([raw file](https://github.com/harness/harness-core/blob/a04ea4838094cb123ef8474a7f085db84b6ecc7c/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveResourceTest.java#L100)):*
> ```Java
>     invalidResourceDataList.add(
>         InvalidResourceData.builder().property("identifier").replacementValue("").expectedResponseCode(400).build());
>     invalidResourceDataList.add(InvalidResourceData.builder()
> ```

nit: should we also optionally  check for error message. We can have contains instead of equals.

**Pull request merged**
