### PR TITLE
[feat]: [GIT-488]: Gitops service client in ResourceGroupService

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/29839)

### CODE REVIEW

**Comment by abhinav-harness** [comment]
lgtm

**Review by gupta-utkarsh — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 6 of 14 files at r2, 11 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29839)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[830-resource-group/src/main/java/io/harness/resourcegroup/resourceclient/gitops/ApplicationResourceImpl.java, line 80 at r3](https://reviewable.io/reviews/harness/harness-core/29839#-Muj2Ydy6GuR9F0VsMWt:-Muj2Ydy6GuR9F0VsMWu:bn216s9) ([raw file](https://github.com/harness/harness-core/blob/4a71582f811cf40efbc3838f8683f747c2662430/830-resource-group/src/main/java/io/harness/resourcegroup/resourceclient/gitops/ApplicationResourceImpl.java#L80)):*
> ```Java
>   @Override
>   public Map<ScopeLevel, EnumSet<ValidatorType>> getSelectorKind() {
>     return ImmutableMap.of(ScopeLevel.ACCOUNT, EnumSet.of(BY_RESOURCE_TYPE_INCLUDING_CHILD_SCOPES),
> ```

By Resource_TYPE_INCLUDING_CHILD_SCOPES would remain for both Account and Organization. This essentially helps to give access on project level entities from account level. Same for other resources.
___
*[925-access-control-service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml, line 713 at r3](https://reviewable.io/reviews/harness/harness-core/29839#-Muj30GuCIReL9bcYyfX:-Muj30GuCIReL9bcYyfY:b-6uxbfe) ([raw file](https://github.com/harness/harness-core/blob/4a71582f811cf40efbc3838f8683f747c2662430/925-access-control-service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L713)):*
> ```YAML
>     includeInAllRoles: false
>     allowedScopeLevels:
>       - account
> ```

This will remain. Now permissions can be given at account level for a project level resource.

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29839)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[830-resource-group/src/main/java/io/harness/resourcegroup/resourceclient/gitops/ApplicationResourceImpl.java, line 80 at r3](https://reviewable.io/reviews/harness/harness-core/29839#-Muj2Ydy6GuR9F0VsMWt:-Muj5DY62SSp367p-kBy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4a71582f811cf40efbc3838f8683f747c2662430/830-resource-group/src/main/java/io/harness/resourcegroup/resourceclient/gitops/ApplicationResourceImpl.java#L80)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

By Resource_TYPE_INCLUDING_CHILD_SCOPES would remain for both Account and Organization. This essentially helps to give access on project level entities from account level. Same for other resources.
</blockquote></details>

Done.
___
*[925-access-control-service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml, line 713 at r3](https://reviewable.io/reviews/harness/harness-core/29839#-Muj30GuCIReL9bcYyfX:-Muj5EtwC4PKw0DK1PBy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4a71582f811cf40efbc3838f8683f747c2662430/925-access-control-service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L713)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

This will remain. Now permissions can be given at account level for a project level resource.
</blockquote></details>

Done.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29839#-:-Muj759d5KjdAe_GxxT2:bnfp4nl)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
Q. Is it new task type? 
A. No

**Comment by abhinav-harness** [comment]
discussed on slack - nothing related to del tasks, apptoving

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 14 of 14 files at r2, 5 of 16 files at r3, 3 of 7 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29839)* status: :shipit: complete! ✓

**Pull request merged**
