### PR TITLE
[feat]:[pl-29191]: BE api for list repo

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
BE api contract for listing repositories of all templates in a given scope

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39094)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 875 at r2](https://reviewable.io/reviews/harness/harness-core/39094#-NEtKIOi8HJ_mWWnnKJA:-NEtKIOi8HJ_mWWnnKJB:b4rrb12) ([raw file](https://github.com/harness/harness-core/blob/b1318d94aa7dd961eec96a06cc5af2e4684c0e9e/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L875)):*
> ```Java
>   }
> 
>   @POST
> ```

why is this POST?

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 894 at r2](https://reviewable.io/reviews/harness/harness-core/39094#-NEtLQGsCJBQlYvT7lsd:-NEtLQGsCJBQlYvT7lse:b-xb5yw4) ([raw file](https://github.com/harness/harness-core/blob/b1318d94aa7dd961eec96a06cc5af2e4684c0e9e/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L894)):*
> ```Java
>           NGCommonEntityConstants.PROJECT_KEY) @ProjectIdentifier String projectIdentifier,
>       @Parameter(description = "Specify true if all accessible Templates are to be included") @QueryParam(
>           INCLUDE_ALL_TEMPLATES_ACCESSIBLE) boolean includeAllTemplatesAccessibleAtScope) {
> ```

what does this field do?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39094)* status: 1 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 875 at r2](https://reviewable.io/reviews/harness/harness-core/39094#-NEtKIOi8HJ_mWWnnKJA:-NEtLv3o6JArKERjxzna:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b1318d94aa7dd961eec96a06cc5af2e4684c0e9e/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L875)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is this POST?
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 894 at r2](https://reviewable.io/reviews/harness/harness-core/39094#-NEtLQGsCJBQlYvT7lsd:-NEtLvTt1xfSC1iQ5MMr:bh89tuk) ([raw file](https://github.com/harness/harness-core/blob/b1318d94aa7dd961eec96a06cc5af2e4684c0e9e/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L894)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what does this field do?
</blockquote></details>

while list/list-metadata is called with includeAllTemplatesAccessibleAtScope as true, even thought we might be at account level and we have passed the org info, we will go ahead and fetch all the templates at both account and org level, in such a case, for repos as well, we would have to do a similar thing so have all the repos

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39094)* status: :shipit: complete! ✓

**Review by inderschera — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39094)* status: :shipit: complete! ✓

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 895 at r3](https://reviewable.io/reviews/harness/harness-core/39094#-NEtaCsMBtiVcWz-MA94:-NEtaCsMBtiVcWz-MA95:b3lr91k) ([raw file](https://github.com/harness/harness-core/blob/7f48a41cf8af2fb402960e7438e243ffe9e0314e/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L895)):*
> ```Java
>       @Parameter(description = "Specify true if all accessible Templates are to be included") @QueryParam(
>           INCLUDE_ALL_TEMPLATES_ACCESSIBLE) boolean includeAllTemplatesAccessibleAtScope) {
>     accessControlClient.checkForAccessOrThrow(ResourceScope.of(accountIdentifier, orgIdentifier, projectIdentifier),
> ```

I don't think we need to check template view access here.

**Review by inderschera — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39094)* status: 1 file(s) to review. 0 of 1 approvals obtained.

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39094)* status: :shipit: complete! ✓

**Pull request merged**
