### PR TITLE
[fix]: [PIE-7997]: Remove cyclic dependency between ValidateAndMergeHelper and PMSExecutionServiceImpl

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43459)

### CODE REVIEW

**Review by ankittiwari-harness — DISMISSED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43459)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — DISMISSED** [review]
:lgtm:

> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43459#-:-NNKsipiCNlMS8ilKqpY:bnfp4nl)* status: :shipit: complete! ✓

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 627 at r2](https://reviewable.io/reviews/harness/harness-core/43459#-NNKt8Uv0wyqUInr26CV:-NNKt8Uv0wyqUInr26CW:b5wyixj) ([raw file](https://github.com/harness/harness-core/blob/97e0406d3b0c230b98c7ab949fc9619202eb8cf6/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L627)):*
> ```Java
>       List<String> stageIdentifiers) {
>     String pipelineYaml = validateAndMergeHelper
>                               .getPipelineEntity(accountId, orgIdentifier, projectIdentifier, pipelineIdentifier,
> ```

why are we getting PipelineEntity from validateAndMergeHelper? Why not from PmsPipelineService?

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43459)* status: :shipit: complete! ✓

**Review by ankittiwari-harness — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43459#-:-NNKzGtZCb7M-7kkze6y:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43459)* status: 2 file(s) to review.

**Review by ankittiwari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43459)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43459)* status: :shipit: complete! ✓

**Pull request merged**
