### PR TITLE
feat: [CDS-39117]: add instance sync for azure Web Apps NG

### PR DESCRIPTION
**Pull request by vlica-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35043)

### CODE REVIEW

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35043)* status: :shipit: complete! ✓

**Review by vlica-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35043)* status: :shipit: complete! ✓

___
*[`126-instance/src/main/java/io/harness/dtos/instanceinfo/AzureWebAppInstanceInfoDTO.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/35043#-N6J24Ez2g-DmYuPqFcs:-N6JB5PA6NK7zUJhRWv_:b-3ewc6y) ([raw file](https://github.com/harness/harness-core/blob/d47b32e37116d63917db14452d699189380068ea/126-instance/src/main/java/io/harness/dtos/instanceinfo/AzureWebAppInstanceInfoDTO.java#L32)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

There should be a unique instance key per instance, in this case there will be only one instance key per app. Consider adding instanceIp / instanceId to instance key
</blockquote></details>

yeah, good catch, added instanceId.

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 34 of 34 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35043)* status: :shipit: complete! ✓

___
*[`126-instance/src/main/java/io/harness/dtos/deploymentinfo/AzureWebAppDeploymentInfoDTO.java` line 1 at r2](https://reviewable.io/reviews/harness/harness-core/35043#-N6MI7mK8hiYe19H9UhY:-N6MI7mK8hiYe19H9UhZ:bexhix4) ([raw file](https://github.com/harness/harness-core/blob/8c19278bebf3cde15dc3acc09c2a6ef18993e898/126-instance/src/main/java/io/harness/dtos/deploymentinfo/AzureWebAppDeploymentInfoDTO.java#L1)):*
> ```Java
> package io.harness.dtos.deploymentinfo;
> ```

let's add Copyright to new files



_Code quote (from 126-instance/src/main/java/io/harness/dtos/instanceinfo/InstanceInfoDTO.java):_
```Java
Copyright
```
___
*[`126-instance/src/main/java/io/harness/service/instancesynchandlerfactory/InstanceSyncHandlerFactoryServiceImpl.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/35043#-N6MHrlV2RV-grfCwlBK:-N6MHrlV2RV-grfCwlBL:b-noecgd) ([raw file](https://github.com/harness/harness-core/blob/8c19278bebf3cde15dc3acc09c2a6ef18993e898/126-instance/src/main/java/io/harness/service/instancesynchandlerfactory/InstanceSyncHandlerFactoryServiceImpl.java#L31)):*
> ```Java
>   private final NativeHelmInstanceSyncHandler nativeHelmInstanceSyncHandler;
>   private final ServerlessAwsLambdaInstanceSyncHandler serverlessAwsLambdaInstanceSyncHandler;
>   private final AzureWebAppInstanceSyncHandler azureWebAppInstanceSyncHandler;
> ```

let's keep the empty line

**Review by abosii-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35043)* status: :shipit: complete! ✓

**Review by vlica-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35043)* status: 16 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/dtos/deploymentinfo/AzureWebAppDeploymentInfoDTO.java` line 1 at r2](https://reviewable.io/reviews/harness/harness-core/35043#-N6MI7mK8hiYe19H9UhY:-N6MW9Xc6zXzmwMRtYF2:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8c19278bebf3cde15dc3acc09c2a6ef18993e898/126-instance/src/main/java/io/harness/dtos/deploymentinfo/AzureWebAppDeploymentInfoDTO.java#L1)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's add Copyright to new files
</blockquote></details>

done
___
*[`126-instance/src/main/java/io/harness/service/instancesynchandlerfactory/InstanceSyncHandlerFactoryServiceImpl.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/35043#-N6MHrlV2RV-grfCwlBK:-N6MWBcmDstvd6Skg1FT:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8c19278bebf3cde15dc3acc09c2a6ef18993e898/126-instance/src/main/java/io/harness/service/instancesynchandlerfactory/InstanceSyncHandlerFactoryServiceImpl.java#L31)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's keep the empty line
</blockquote></details>

done

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35043)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35043#-:-N6MZ-675h7QFcXVmMGD:bnfp4nl)* status: :shipit: complete! ✓

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35043)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35043)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
Well done!

> Reviewed 18 of 34 files at r1, 16 of 16 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35043#-:-N6N0WHU1u7yQgDLKY6D:b-v7gob2)* status: :shipit: complete! ✓

___
*[`126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/azure/AzureWebAppInstanceSyncPerpetualTaskHandler.java` line 142 at r4](https://reviewable.io/reviews/harness/harness-core/35043#-N6Mxo7i-mgCdl31PRZb:-N6Mxo7i-mgCdl31PRZc:b-ymtih4) ([raw file](https://github.com/harness/harness-core/blob/588caa1dbdd02e62b1586cb070841390de38a51a/126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/azure/AzureWebAppInstanceSyncPerpetualTaskHandler.java#L142)):*
> ```Java
>             baseNGAccess.getAccountIdentifier(), baseNGAccess.getOrgIdentifier(), baseNGAccess.getProjectIdentifier());
> 
>     AzureConnectorDTO connectorDTO = azureHelperService.getConnector(identifierRef);
> ```

Minor -  if we supply only identifier here, azureHelperService.getConnector(identifierRef) how is it working for connectors on the account and org level?

**Comment by vlica-harness** [comment]
*[`126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/azure/AzureWebAppInstanceSyncPerpetualTaskHandler.java` line 142 at r4](https://reviewable.io/reviews/harness/harness-core/35043#-N6Mxo7i-mgCdl31PRZb:-N6N_3nv0v8b10xNkzl1:b-o8mz5q) ([raw file](https://github.com/harness/harness-core/blob/588caa1dbdd02e62b1586cb070841390de38a51a/126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/azure/AzureWebAppInstanceSyncPerpetualTaskHandler.java#L142)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor -  if we supply only identifier here, azureHelperService.getConnector(identifierRef) how is it working for connectors on the account and org level?  
</blockquote></details>

well, the identifier I supply here rely on accountId, orgId, projectId + connectorRef. Then the connector is retrieved based on identifier...

**Review by ivan-83 — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35043)* status: :shipit: complete! ✓

___
*[`126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/azure/AzureWebAppInstanceSyncPerpetualTaskHandler.java` line 142 at r4](https://reviewable.io/reviews/harness/harness-core/35043#-N6Mxo7i-mgCdl31PRZb:-N6NcVAW6uKXJweRa0NI:b-x463d8) ([raw file](https://github.com/harness/harness-core/blob/588caa1dbdd02e62b1586cb070841390de38a51a/126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/azure/AzureWebAppInstanceSyncPerpetualTaskHandler.java#L142)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

well, the identifier I supply here rely on accountId, orgId, projectId + connectorRef. Then the connector is retrieved based on identifier...
</blockquote></details>

Sure, my mistake, I see you are sending the whole  identifierRef object.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 2 of 4 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35043)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r7, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35043)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35043)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35043)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 16 of 34 files at r1, 16 of 16 files at r3, 2 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35043#-:-N6ReyA05GBCkUl8NE7J:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
