### PR TITLE
[fix]: [PL-24964]: Null check for service variable type

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
Null check for service variable type

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34930)

### CODE REVIEW

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34930)* status: Some of the checks are too old. 1 file(s) to review. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/handler/service/ServiceYamlHandler.java` line 328 at r2](https://reviewable.io/reviews/harness/harness-core/34930#-N68vPp90pc70RcAN4Lf:-N68vPpDAjbrt3SVAJos:b-8ce79a) ([raw file](https://github.com/harness/harness-core/blob/d96243d5f759466cbc59f939801bcf8f49c30eca/400-rest/src/main/java/software/wings/service/impl/yaml/handler/service/ServiceYamlHandler.java#L328)):*
> ```Java
> 
>         if (serviceVariable.getType() == null) {
>           configVarsToUpdate.add(configVar);
> ```

Why are we allowing config var to update without type?
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/handler/service/ServiceYamlHandler.java` line 412 at r2](https://reviewable.io/reviews/harness/harness-core/34930#-N68v_uW3KGC6VVpsuXJ:-N68v_uW3KGC6VVpsuXK:b-ew7nez) ([raw file](https://github.com/harness/harness-core/blob/d96243d5f759466cbc59f939801bcf8f49c30eca/400-rest/src/main/java/software/wings/service/impl/yaml/handler/service/ServiceYamlHandler.java#L412)):*
> ```Java
>       if (serviceVariable.getType() == null) {
>         try {
>           serviceVariable.setType(ServiceVariableType.valueOf(configVar.getValueType()));
> ```

This could be null as well since we allowed config var to be added without type.



_Code quote:_
```Java
configVar.getValueType()
```

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34930)* status: Some of the checks are too old. 1 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/handler/service/ServiceYamlHandler.java` line 328 at r2](https://reviewable.io/reviews/harness/harness-core/34930#-N68vPp90pc70RcAN4Lf:-N69-a-A9z1qisf2I35J:bejpftd) ([raw file](https://github.com/harness/harness-core/blob/d96243d5f759466cbc59f939801bcf8f49c30eca/400-rest/src/main/java/software/wings/service/impl/yaml/handler/service/ServiceYamlHandler.java#L328)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Why are we allowing config var to update without type?
</blockquote></details>

the service variable type is saved as null whenever it is anything other than TEXT,ENCRYPTED_TEXT,ARTIFACT so by doing this we are trying to let them update the service variable type
And to solve the problem of service variable being saved as null i have have fixed it by not allowing the creation of service if the type is incorrect.Method name validateConfigVariableType(yaml);
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/handler/service/ServiceYamlHandler.java` line 412 at r2](https://reviewable.io/reviews/harness/harness-core/34930#-N68v_uW3KGC6VVpsuXJ:-N690bSKE-yFTtyZuzE5:bbr3n66) ([raw file](https://github.com/harness/harness-core/blob/d96243d5f759466cbc59f939801bcf8f49c30eca/400-rest/src/main/java/software/wings/service/impl/yaml/handler/service/ServiceYamlHandler.java#L412)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

This could be null as well since we allowed config var to be added without type.
</blockquote></details>

thats why i have added try catch so if configVar.getValueType() is anything other than 3 enum values we will throw exception

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34930)* status: Some of the checks are too old. 1 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/handler/service/ServiceYamlHandler.java` line 328 at r2](https://reviewable.io/reviews/harness/harness-core/34930#-N68vPp90pc70RcAN4Lf:-N692AEb3nD3btifbi20:bahm72y) ([raw file](https://github.com/harness/harness-core/blob/d96243d5f759466cbc59f939801bcf8f49c30eca/400-rest/src/main/java/software/wings/service/impl/yaml/handler/service/ServiceYamlHandler.java#L328)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

the service variable type is saved as null whenever it is anything other than TEXT,ENCRYPTED_TEXT,ARTIFACT so by doing this we are trying to let them update the service variable type
And to solve the problem of service variable being saved as null i have have fixed it by not allowing the creation of service if the type is incorrect.Method name validateConfigVariableType(yaml);
</blockquote></details>

validateConfigVariableType this was added in an earlier pr

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34930)* status: Some of the checks are too old. 1 file(s) to review. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/handler/service/ServiceYamlHandler.java` line 412 at r2](https://reviewable.io/reviews/harness/harness-core/34930#-N68v_uW3KGC6VVpsuXJ:-N6CDHNH2Y4kHIjt0INN:b-z9i9hx) ([raw file](https://github.com/harness/harness-core/blob/d96243d5f759466cbc59f939801bcf8f49c30eca/400-rest/src/main/java/software/wings/service/impl/yaml/handler/service/ServiceYamlHandler.java#L412)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

thats why i have added try catch so if configVar.getValueType() is anything other than 3 enum values we will throw exception
</blockquote></details>

nit: error message needs to be corrected.



_Code quote:_
```Java
Invalid service variable name %s", configVar.getValueType()
```

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34930)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
