### PR TITLE
[fix]: [CDS-36266]: Refresh API - NG Templates 

### PR DESCRIPTION
**Pull request by vtxorxwitty**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31883)

### CODE REVIEW

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31883)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java` line 521 at r2](https://reviewable.io/reviews/harness/harness-core/31883#-N0_hwQH6lwxcl2mXmN8:-N0den6v-NUf-14HTEcK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d3bda22a6f6b26818ac2ee3a2bf17638e6ec4705/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java#L521)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

get finalNode from yamlConfig.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java` line 556 at r2](https://reviewable.io/reviews/harness/harness-core/31883#-N0_jV529DbbLPkAdL2W:-N0dernO5Dg16SGGlU2H:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d3bda22a6f6b26818ac2ee3a2bf17638e6ec4705/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java#L556)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Add proper error message.
</blockquote></details>

Done.

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31883)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java` line 496 at r2](https://reviewable.io/reviews/harness/harness-core/31883#-N0_i3syEkvjCMy_Amg-:-N0eU1_h8YuaVkvQEJi8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d3bda22a6f6b26818ac2ee3a2bf17638e6ec4705/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java#L496)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

What if templateInputs are null. This might throw NPE. 
</blockquote></details>

Done.

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31883)* status: 4 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java` line 542 at r2](https://reviewable.io/reviews/harness/harness-core/31883#-N0_jLdu6Jmd95oW5qx3:-N0eovujC09JfUO-V5aI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d3bda22a6f6b26818ac2ee3a2bf17638e6ec4705/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java#L542)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Handle the case when templateSpecYaml is empty. In this case, templateInputs should not be present at all.
</blockquote></details>

Done.

**Review by inderschera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31883)* status: 4 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java` line 417 at r4](https://reviewable.io/reviews/harness/harness-core/31883#-N0fD-8z-XgAC3rDhmGj:-N0fD-8z-XgAC3rDhmGk:b-u6lwxt) ([raw file](https://github.com/harness/harness-core/blob/a19705eca93ebf971fd805c6f48b459de40444fb/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java#L417)):*
> ```Java
>   }
> 
>   public String refreshTemplates(String accountId, String orgId, String projectId, String yaml) {
> ```

Please add unit tests for this method. Should cover atleast these cases:
1. Template has extra runtime inputs than linked template inputs
2. Template has less runtime inputs than linked template inputs.
3. Template has runtime inputs but linked templateInputs in null.
4. Template does not have runtime input but linked templateInputs is not null.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java` line 519 at r4](https://reviewable.io/reviews/harness/harness-core/31883#-N0fCsnyCKd-dJHK7suk:-N0fCsnyCKd-dJHK7sul:b-qqz9ou) ([raw file](https://github.com/harness/harness-core/blob/a19705eca93ebf971fd805c6f48b459de40444fb/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java#L519)):*
> ```Java
>     if (yamlConfig == null) {
>       // CASE -> When Template does not contain any runtime inputs
>       updatedValue.remove(TEMPLATE_INPUTS);
> ```

what if TEMPLATE_INPUTS are already not present in updatedValue?
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java` line 548 at r4](https://reviewable.io/reviews/harness/harness-core/31883#-N0fCdEd7GbyuMg94iNB:-N0fCdEd7GbyuMg94iNC:b-i67o5x) ([raw file](https://github.com/harness/harness-core/blob/a19705eca93ebf971fd805c6f48b459de40444fb/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java#L548)):*
> ```Java
>     // LinkedTemplateYAML with Template Inputs
>     Map<String, JsonNode> dummyTemplateInputsMap = new LinkedHashMap<>();
>     dummyTemplateInputsMap.put(DUMMY_NODE, templateInputs);
> ```

here templateInputs can be null. What happens when you convert it to yaml?

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31883)* status: 11 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java` line 417 at r4](https://reviewable.io/reviews/harness/harness-core/31883#-N0fD-8z-XgAC3rDhmGj:-N0jZCMT7_v40usXt0C4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a19705eca93ebf971fd805c6f48b459de40444fb/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java#L417)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Please add unit tests for this method. Should cover atleast these cases:
1. Template has extra runtime inputs than linked template inputs
2. Template has less runtime inputs than linked template inputs.
3. Template has runtime inputs but linked templateInputs in null.
4. Template does not have runtime input but linked templateInputs is not null.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java` line 519 at r4](https://reviewable.io/reviews/harness/harness-core/31883#-N0fCsnyCKd-dJHK7suk:-N0jZDvg6WHxL0Qc3exO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a19705eca93ebf971fd805c6f48b459de40444fb/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java#L519)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

what if TEMPLATE_INPUTS are already not present in updatedValue?
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java` line 548 at r4](https://reviewable.io/reviews/harness/harness-core/31883#-N0fCdEd7GbyuMg94iNB:-N0jZEu-2OTe5IaXEDfQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a19705eca93ebf971fd805c6f48b459de40444fb/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java#L548)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

here templateInputs can be null. What happens when you convert it to yaml?
</blockquote></details>

Done.

**Review by inderschera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31883)* status: 17 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java` line 225 at r7](https://reviewable.io/reviews/harness/harness-core/31883#-N0knt2U4UY_RPlxmAHd:-N0knt2U4UY_RPlxmAHe:bf78fyq) ([raw file](https://github.com/harness/harness-core/blob/8dae560baa857d83587c7b57c93dc9f04c1d8da6/840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java#L225)):*
> ```Java
>   }
> 
>   private String convertToYaml(Object object) {
> ```

same here. duplicate code. please move.
___
*[`840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java` line 230 at r7](https://reviewable.io/reviews/harness/harness-core/31883#-N0knatwAVbliW8Sa_Q6:-N0knatwAVbliW8Sa_Q7:bcegkny) ([raw file](https://github.com/harness/harness-core/blob/8dae560baa857d83587c7b57c93dc9f04c1d8da6/840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java#L230)):*
> ```Java
> 
>   private TemplateEntity getLinkedTemplateEntity(
>       String accountId, String orgId, String projectId, JsonNode yaml, Map<String, TemplateEntity> templateCacheMap) {
> ```

This is duplicate code. Move this to common class, maybe add TemplateMergeServiceHelper class.
___
*[`840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java` line 261 at r7](https://reviewable.io/reviews/harness/harness-core/31883#-N0knoGR1Uz9AjrkXW_7:-N0knoGR1Uz9AjrkXW_8:b-zbhvj6) ([raw file](https://github.com/harness/harness-core/blob/8dae560baa857d83587c7b57c93dc9f04c1d8da6/840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java#L261)):*
> ```Java
>   }
> 
>   private boolean isTemplatePresent(String fieldName, JsonNode templateValue) {
> ```

This is also duplicate. Move this.

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31883)* status: 18 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java` line 225 at r7](https://reviewable.io/reviews/harness/harness-core/31883#-N0knt2U4UY_RPlxmAHd:-N12ea2P8z_FrmelXDhB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8dae560baa857d83587c7b57c93dc9f04c1d8da6/840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java#L225)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

same here. duplicate code. please move.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java` line 230 at r7](https://reviewable.io/reviews/harness/harness-core/31883#-N0knatwAVbliW8Sa_Q6:-N12eaMAA_FLNWA_u-lT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8dae560baa857d83587c7b57c93dc9f04c1d8da6/840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java#L230)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

This is duplicate code. Move this to common class, maybe add TemplateMergeServiceHelper class.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java` line 261 at r7](https://reviewable.io/reviews/harness/harness-core/31883#-N0knoGR1Uz9AjrkXW_7:-N12ebHb5FrcGz-t3naN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8dae560baa857d83587c7b57c93dc9f04c1d8da6/840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java#L261)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

This is also duplicate. Move this.
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 9 files at r7, 2 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31883)* status: 15 file(s) to review. 1 change requests. 3. unresolved discussions. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 38 at r8](https://reviewable.io/reviews/harness/harness-core/31883#-N1D9r1c6cGchUowYsIy:-N1D9r1c6cGchUowYsIz:bdlavqw) ([raw file](https://github.com/harness/harness-core/blob/b7e99c2282a8366e3910db2eb3326b1fe660b4fb/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L38)):*
> ```Java
> @AllArgsConstructor(onConstructor = @__({ @Inject }))
> @Slf4j
> public class TemplateMergeServiceHelper {
> ```

Add comments what this class will be responsible for and explain a small comment for each method



_Code quote:_
```Java
TemplateMergeServiceHelper
```
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 43 at r8](https://reviewable.io/reviews/harness/harness-core/31883#-N1DA9vt6EXt2kR2aDio:-N1DA9vt6EXt2kR2aDip:bv6dpkh) ([raw file](https://github.com/harness/harness-core/blob/b7e99c2282a8366e3910db2eb3326b1fe660b4fb/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L43)):*
> ```Java
>   public String convertToYaml(Object object) {
>     return YamlUtils.write(object).replace("---\n", "");
>   }
> ```

use YamlPipelineUtils.getYamlString thus remove method directly



_Code quote:_
```Java
  public String convertToYaml(Object object) {
    return YamlUtils.write(object).replace("---\n", "");
  }
```
___
*[`840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java` line 44 at r8](https://reviewable.io/reviews/harness/harness-core/31883#-N1DAPmC8AIY1EOoi3PA:-N1DAPmC8AIY1EOoi3PB:b-sd8j4o) ([raw file](https://github.com/harness/harness-core/blob/b7e99c2282a8366e3910db2eb3326b1fe660b4fb/840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java#L44)):*
> ```Java
> @Slf4j
> @OwnedBy(CDC)
> public class RefreshTemplateInputs {
> ```

Add comments explaining class usage and aim



_Code quote:_
```Java
RefreshTemplateInputs 
```
___
*[`840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java` line 74 at r8](https://reviewable.io/reviews/harness/harness-core/31883#-N1DAWPW-qwvaIQFSzVH:-N1DAWPW-qwvaIQFSzVI:b2t1i3w) ([raw file](https://github.com/harness/harness-core/blob/b7e99c2282a8366e3910db2eb3326b1fe660b4fb/840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java#L74)):*
> ```Java
>   }
> 
>   private Map<String, Object> getResMap(String accountId, String orgId, String projectId, YamlNode yamlNode,
> ```

can be a better method name explaining what input it takes and output.

CorrelationContext -> can explore to cache at global level per correlationId, and clear entry for that correlationId 
___
*[`840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java` line 126 at r8](https://reviewable.io/reviews/harness/harness-core/31883#-N1DBgX5BAbGBx4Bw9sA:-N1DBgX5BAbGBx4Bw9sB:b-6x794p) ([raw file](https://github.com/harness/harness-core/blob/b7e99c2282a8366e3910db2eb3326b1fe660b4fb/840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java#L126)):*
> ```Java
> 
>   private JsonNode getUpdatedTemplateValue(
>       String accountId, String orgId, String projectId, JsonNode value, Map<String, TemplateEntity> templateCacheMap) {
> ```

what is this value, thus properName



_Code quote:_
```Java
value
```
___
*[`840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java` line 187 at r8](https://reviewable.io/reviews/harness/harness-core/31883#-N1DFSCD4e9KONc3Ejmd:-N1DFSCD4e9KONc3Ejme:bgjzjjp) ([raw file](https://github.com/harness/harness-core/blob/b7e99c2282a8366e3910db2eb3326b1fe660b4fb/840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java#L187)):*
> ```Java
>     Map<FQN, Object> templateSpecMap = getUpdatedTemplateInputsFqnMap(dummyTemplateInputsYaml, templateSpecYaml);
> 
>     JsonNode node = null;
> ```

rename this field but this can be optimised to get from original config



_Code quote:_
```Java
node
```
___
*[`840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java` line 198 at r8](https://reviewable.io/reviews/harness/harness-core/31883#-N1DD1Fw6r-d8sZdWGUi:-N1DD1Fw6r-d8sZdWGUj:bvm6hks) ([raw file](https://github.com/harness/harness-core/blob/b7e99c2282a8366e3910db2eb3326b1fe660b4fb/840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java#L198)):*
> ```Java
>   }
> 
>   private Map<FQN, Object> getUpdatedTemplateInputsFqnMap(String originalYaml, String templateSpecYaml) {
> ```

inputsYaml -> rename field



_Code quote:_
```Java
riginalYaml
```
___
*[`840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java` line 208 at r8](https://reviewable.io/reviews/harness/harness-core/31883#-N1DEnm3COqFuebps33r:-N1DEnm3COqFuebps33s:b-iqwy7o) ([raw file](https://github.com/harness/harness-core/blob/b7e99c2282a8366e3910db2eb3326b1fe660b4fb/840-template-service/src/main/java/io/harness/template/refresh/RefreshTemplateInputs.java#L208)):*
> ```Java
> 
>     // Iterating all the Runtime Inputs in the TemplateSpec FQN-Map and replacing the values with those in the
>     // TemplateInputs FQN-Map
> ```

can explain better which values map you are replacing and with what



_Code quote:_
```Java
TemplateInputs FQN-Map
```

**Review by archit-harness — COMMENTED** [review]
Can move the generic method which takes 2 yaml as inputs and refresh them so that input set can also use it

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31883#-:-N1DG7Vc3ClfqRv31F9s:by3whb2)* status: 15 file(s) to review. 1 change requests. 3. unresolved discussions.

**Review by inderschera — COMMENTED** [review]
> Reviewed 2 of 4 files at r2, 6 of 7 files at r5, 4 of 9 files at r7, 4 of 6 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31883)* status: 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained.

**Review by inderschera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31883)* status: :shipit: complete! ✓

**Pull request merged**
