### PR TITLE
[fix]: [PL-24531]: Add the support for listBranches with default in the scm api

### PR DESCRIPTION
**Pull request by DeepakPatankar**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32634)

### CODE REVIEW

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32634)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 253 at r1](https://reviewable.io/reviews/harness/harness-core/32634#-N0o6PA8962mBBVODM7v:-N0o6PA8962mBBVODM7w:bgju1wq) ([raw file](https://github.com/harness/harness-core/blob/16391f535c081d56729c068e8dabd1ad7be4ac7e/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L253)):*
> ```Java
>             .setSlug(slug)
>             .setProvider(provider)
>             .setPagination(PageRequest.newBuilder().setPage(pageNumber).build())
> ```

pagination will be taken as input, please provide pageRequest in parameter
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 257 at r1](https://reviewable.io/reviews/harness/harness-core/32634#-N0o6XR7BrR0zoEwjBa9:-N0o6XR8BuVpC9purSEN:byt3sm6) ([raw file](https://github.com/harness/harness-core/blob/16391f535c081d56729c068e8dabd1ad7be4ac7e/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L257)):*
> ```Java
>     ListBranchesWithDefaultResponse branchListResponse =
>         ScmGrpcClientUtils.retryAndProcessException(scmBlockingStub::listBranchesWithDefault, listBranchesRequest);
>     ScmResponseStatusUtils.checkScmResponseStatusAndThrowException(
> ```

Don't check for error from here, just send the response we are getting from scm directly, error check will be put on different layer.

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32634)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 253 at r1](https://reviewable.io/reviews/harness/harness-core/32634#-N0o6PA8962mBBVODM7v:-N0oiAX_4kfbSfuXa6Ww:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16391f535c081d56729c068e8dabd1ad7be4ac7e/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L253)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

pagination will be taken as input, please provide pageRequest in parameter
</blockquote></details>

Done.
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 257 at r1](https://reviewable.io/reviews/harness/harness-core/32634#-N0o6XR7BrR0zoEwjBa9:-N0oirmBAoOhzZBZMn3M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16391f535c081d56729c068e8dabd1ad7be4ac7e/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L257)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Don't check for error from here, just send the response we are getting from scm directly, error check will be put on different layer.
</blockquote></details>

Done.

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32634)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 253 at r1](https://reviewable.io/reviews/harness/harness-core/32634#-N0o6PA8962mBBVODM7v:-N0p6Qgm3UHnQ8L2mL4_:bwywmfd) ([raw file](https://github.com/harness/harness-core/blob/16391f535c081d56729c068e8dabd1ad7be4ac7e/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L253)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I saw that GitHubAPi takes Page Number and we are passing page Index here, so, page number should be page index +1

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32634)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 253 at r1](https://reviewable.io/reviews/harness/harness-core/32634#-N0o6PA8962mBBVODM7v:-N0p7cusBaMyD68XYpOU:b-mlaihb) ([raw file](https://github.com/harness/harness-core/blob/16391f535c081d56729c068e8dabd1ad7be4ac7e/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L253)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

I saw that GitHubAPi takes Page Number and we are passing page Index here, so, page number should be page index +1 
</blockquote></details>

I remeber scm takes pageNumber always. So lets not use page index in our DTO and lets call it page number.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32634)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 253 at r1](https://reviewable.io/reviews/harness/harness-core/32634#-N0o6PA8962mBBVODM7v:-N0pB1pY6YwoFWUQV7Ww:b-4y9hk9) ([raw file](https://github.com/harness/harness-core/blob/16391f535c081d56729c068e8dabd1ad7be4ac7e/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L253)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

I remeber scm takes pageNumber always. So lets not use page index in our DTO and lets call it page number.
</blockquote></details>

ya, but this dto is common to harness, anyone can use it, so it should have pageIndex as our APIs use pageIndex only, for scm apis we require branch number, so, maybe we can just change it here

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32634)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 253 at r1](https://reviewable.io/reviews/harness/harness-core/32634#-N0o6PA8962mBBVODM7v:-N0pNqFa3njpm-8f7wMy:bf0itz4) ([raw file](https://github.com/harness/harness-core/blob/16391f535c081d56729c068e8dabd1ad7be4ac7e/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L253)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

ya, but this dto is common to harness, anyone can use it, so it should have pageIndex as our APIs use pageIndex only, for scm apis we require branch number, so, maybe we can just change it here 
</blockquote></details>

that's the issue I was pointing in other review comment. We should not be using the rest API, page request to here. I will check and revert back

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32634)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 253 at r1](https://reviewable.io/reviews/harness/harness-core/32634#-N0o6PA8962mBBVODM7v:-N0pWV3sDtpQSuWH19P9:b-hsa4ww) ([raw file](https://github.com/harness/harness-core/blob/16391f535c081d56729c068e8dabd1ad7be4ac7e/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L253)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

that's the issue I was pointing in other review comment. We should not be using the rest API, page request to here. I will check and revert back
</blockquote></details>

No this is not PageRequest of rest api, it's a different dto

**Review by bhavya181 — DISMISSED** [review]
:lgtm:

> Reviewed 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32634#-:-N0powpC0-5VOBqqQUp5:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32634#-:-N100aRg3l75_fnl9ire:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 4 of 6 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32634)* status: :shipit: complete! ✓

**Pull request merged**
