### PR TITLE
[feat]: [CDS-37148]:  Implementation of AWS Cloudformation Deploy api for Change sets

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32993)

### CODE REVIEW

**Comment by arvind-choudhary-h** [comment]
trigger messagecheck

**Comment by arvind-choudhary-h** [comment]
trigger ti1

**Review by nassergonzalez — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r1, 1 of 4 files at r2, 1 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32993)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/CloudformationBaseHelper.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1mP1fiEh4_hOKbxdoX:-N1mP1fj-3BQo22c3_D9:bs1yrsz) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/CloudformationBaseHelper.java#L24)):*
> ```Java
>   Optional<Stack> getIfStackExists(String customStackName, String suffix, AwsInternalConfig awsConfig, String region);
> 
>   DeployStackRequest mapToDeployStackRequest(UpdateStackRequest updateStackRequest);
> ```

Nit: This is more like a mutation, or transformation. When I read the name of the function I though that there was some kind of map between several items but the function is just mutating the UpdateStackRequest to a DeployStackRequest. Could a change in the name make this more cleaner? Like mutateUpdateToDeployRequest or something like that?
(Or just a comment in the interface explaining that)
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/cloudformation/cloudformationtaskhandler/CloudFormationCreateStackHandler.java` line 134 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1mPaVK5t57wPjtlctX:-N1mPaVK5t57wPjtlctY:bypjcqt) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/930-delegate-tasks/src/main/java/software/wings/delegatetasks/cloudformation/cloudformationtaskhandler/CloudFormationCreateStackHandler.java#L134)):*
> ```Java
> 
>   /**
>    * Make sure to update {@link
> ```

Is this a comment that needs to go to the branch? Can we take that action now instead of leaving the comment? (I don't have context about this comment so idk if this is a new task to be done after the merge of this task or something that was forgotten)
___
*[`960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java` line 217 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1mZMa62L4eazrQBLi2:-N1mZMa8A4QMixrrdisc:b-9p0yfa) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L217)):*
> ```Java
> 
>   @Override
>   public DeployStackResult deployStack(String region, DeployStackRequest deployStackRequest,
> ```

Is this change in the client implementation suppose to replace the updateStack call? If so, shall we remove the updateStack call? It also seems that is going to replace the createStack implementation. Should that also be removed?.
___
*[`960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java` line 228 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1mc9Y-EC995GnVqOgW:-N1mc9Y-EC995GnVqOgX:bjln6wq) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L228)):*
> ```Java
>     DeployStackResult result;
> 
>     if (Objects.equals(describeChangeSetResult.getStatus(), "FAILED")) {
> ```

There is a ChangeSetStatus enumeration that could be used instead of a hardcoded string
___
*[`960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java` line 230 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1mcXkl9RONSnoXR3ga:-N1mcXkl9RONSnoXR3gb:b-4zl1w2) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L230)):*
> ```Java
>     if (Objects.equals(describeChangeSetResult.getStatus(), "FAILED")) {
>       deleteChangeSet(region, deployStackRequest, awsConfig, changeSetName, logCallback);
>       if (null != describeChangeSetResult.getStatusReason()
> ```

Instead of having hardcoded strings, could we use getChanges method in the DescribeChangeSetResult to find if the change set doesn't contain changes? Example
Changeset status failed and getChanges empty == No updates are to be performed
___
*[`960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java` line 248 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1md_mM1JEqoVkalpR7:-N1md_mM1JEqoVkalpR8:b-x9b369) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L248)):*
> ```Java
>                      .build();
>       }
>     } else if (Objects.equals(describeChangeSetResult.getStatus(), "CREATE_COMPLETE")) {
> ```

Same thing, use of enumerations
___
*[`960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java` line 356 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1merMoCELFmNOjrnkg:-N1merMoCELFmNOjrnkh:bq4177m) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L356)):*
> ```Java
> 
>   private boolean changeSetCreated(DescribeChangeSetResult describeChangeSet) {
>     List<String> endStatus = Arrays.asList("CREATE_COMPLETE", "FAILED", "DELETE_COMPLETE", "DELETE_FAILED");
> ```

There is already an enum for this ChangeSetStatus

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1, 3 of 4 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32993)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java` line 274 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1muhYK40PHhfl8T9l4:-N1muhYK40PHhfl8T9l5:bojzkzq) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L274)):*
> ```Java
> 
>   private DescribeChangeSetResult describeChangeSet(String region, DeployStackRequest deployStackRequest,
>       AwsInternalConfig awsConfig, String changeSetName, LogCallback logCallback) {
> ```

logCallback not used
___
*[`960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java` line 356 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1myCcF5JbeZ0Zo29nV:-N1myCcG-ZzcEXqlfb4X:blue80b) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L356)):*
> ```Java
> 
>   private boolean changeSetCreated(DescribeChangeSetResult describeChangeSet) {
>     List<String> endStatus = Arrays.asList("CREATE_COMPLETE", "FAILED", "DELETE_COMPLETE", "DELETE_FAILED");
> ```

we can have endStatus as a constant.
___
*[`970-api-services-beans/src/main/java/io/harness/aws/cf/Parameter.java` line 1 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1n07w63awZKYr_c99G:-N1n07w8BnA-fyqrP_er:besukbs) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/970-api-services-beans/src/main/java/io/harness/aws/cf/Parameter.java#L1)):*
> ```Java
> package io.harness.aws.cf;
> ```

Parameters in UpdateStackRequest and CreateChangeSetRequest are of the same type.
Does it make sense to have those intermediate objects and convert from SDK Parametres to our Parameters and then back to SDK Parametres?
The same for tags.

**Comment by arvind-choudhary-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/CloudformationBaseHelper.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1mP1fiEh4_hOKbxdoX:-N1o7j5s0nxUdMPtAe_-:bikov46) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/CloudformationBaseHelper.java#L24)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

Nit: This is more like a mutation, or transformation. When I read the name of the function I though that there was some kind of map between several items but the function is just mutating the UpdateStackRequest to a DeployStackRequest. Could a change in the name make this more cleaner? Like mutateUpdateToDeployRequest or something like that?
(Or just a comment in the interface explaining that)
</blockquote></details>

Sure, I have updated.

**Comment by arvind-choudhary-h** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/cloudformation/cloudformationtaskhandler/CloudFormationCreateStackHandler.java` line 134 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1mPaVK5t57wPjtlctX:-N1o7mtOEpwO1RgazDy5:bqvfe6a) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/930-delegate-tasks/src/main/java/software/wings/delegatetasks/cloudformation/cloudformationtaskhandler/CloudFormationCreateStackHandler.java#L134)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

Is this a comment that needs to go to the branch? Can we take that action now instead of leaving the comment? (I don't have context about this comment so idk if this is a new task to be done after the merge of this task or something that was forgotten)
</blockquote></details>

Removed it, no need as of now.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java` line 228 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1mc9Y-EC995GnVqOgW:-N1o8DZ0Az53G3rfFW9Q:b-kyctki) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L228)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

There is a ChangeSetStatus enumeration that could be used instead of a hardcoded string
</blockquote></details>

Missed that, updated.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java` line 274 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1muhYK40PHhfl8T9l4:-N1o8Kzg8liOu4hR7WYh:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L274)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

logCallback not used
</blockquote></details>

removed

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java` line 356 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1merMoCELFmNOjrnkg:-N1o8MEG0S21SC5VsKqI:b-kyctki) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L356)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

There is already an enum for this ChangeSetStatus
</blockquote></details>

Missed that, updated.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java` line 356 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1myCcF5JbeZ0Zo29nV:-N1o8OCrBOn3GmdyNu99:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L356)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

we can have endStatus as a constant.
</blockquote></details>

Done.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java` line 230 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1mcXkl9RONSnoXR3ga:-N1o8Q8hCBuFJANfDcBP:b-dk294d) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L230)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

Instead of having hardcoded strings, could we use getChanges method in the DescribeChangeSetResult to find if the change set doesn't contain changes? Example
Changeset status failed and getChanges empty == No updates are to be performed
</blockquote></details>

The logic is ported directly from AWS CLI implementation. link: https://github.com/aws/aws-cli/blob/develop/awscli/customizations/cloudformation/deployer.py#L171

**Comment by arvind-choudhary-h** [comment]
*[`970-api-services-beans/src/main/java/io/harness/aws/cf/Parameter.java` line 1 at r4](https://reviewable.io/reviews/harness/harness-core/32993#-N1n07w63awZKYr_c99G:-N1o8tyh3wFp2vsEJi4G:b-roswsr) ([raw file](https://github.com/harness/harness-core/blob/25a7817df1f24ef4ce0158f67dfad5613907554c/970-api-services-beans/src/main/java/io/harness/aws/cf/Parameter.java#L1)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Parameters in UpdateStackRequest and CreateChangeSetRequest are of the same type.
Does it make sense to have those intermediate objects and convert from SDK Parametres to our Parameters and then back to SDK Parametres?
The same for tags.
</blockquote></details>

Makes complete sense. I also started with AWS SDK models but "@maven//:com_amazonaws_aws_java_sdk_cloudformation", was not available in BAZEL.build and I assumed this is intentional. Removed Parameter and Tag.

For the DeployStack objects, they should be used for 2 reasons according to me:
1. We tried to implement deploy https://docs.aws.amazon.com/cli/latest/reference/deploy/index.html
2. We submit 3 types of requests - CREATE / DESCRIBE / EXECUTE. So, different request and response made sense.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 10 of 10 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32993)* status: 1 change requests. 7. unresolved discussions.

**Review by nassergonzalez — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32993)* status: :shipit: complete! ✓

**Pull request merged**
