### PR TITLE
feat:[CDS-79584]: Add appropriate validation is render expression apis

### PR DESCRIPTION
**Pull request by Aninditaa-ch**
## Describe your changes
The expression was coming from a method in EngineGrpcExpressionService, a check was added to ensure that it is not null. Additionally, the test cases for these if conditions was added in the test file for the same.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55277)

### CODE REVIEW

**Comment by Aninditaa-ch** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver/expressions/EngineGrpcExpressionService.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/55277#-NisS-0892AYSR4DzZ5g:-NisS-0892AYSR4DzZ5h:bgsnmks) ([raw file](https://github.com/harness/harness-core/blob/cee104892745177e69d0b32adf3f63a7d28cd213/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver/expressions/EngineGrpcExpressionService.java#L69)):*
> ```Java
>                 .setExpressionMode(mode)
>                 .build());
>     if (isEmpty(expression)) {
> ```

I think this should come before the above line. Same for all.

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver/expressions/EngineGrpcExpressionService.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/55277#-NisS3lr3jNrILLx9hvj:-NisS3lr3jNrILLx9hvk:b-z3mrht) ([raw file](https://github.com/harness/harness-core/blob/cee104892745177e69d0b32adf3f63a7d28cd213/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver/expressions/EngineGrpcExpressionService.java#L83)):*
> ```Java
> 
>     if (isEmpty(expression)) {
>       throw new InvalidRequestException("The expression cannot be empty.");
> ```

Please write a test case for the same.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55277)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by Aninditaa-ch** [comment]
trigger uts

**Review by Aninditaa-ch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55277)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver/expressions/EngineGrpcExpressionService.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/55277#-NisS-0892AYSR4DzZ5g:-NjMbyKu9ekMRWJs1pHh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cee104892745177e69d0b32adf3f63a7d28cd213/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver/expressions/EngineGrpcExpressionService.java#L69)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think this should come before the above line. Same for all.
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver/expressions/EngineGrpcExpressionService.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/55277#-NisS3lr3jNrILLx9hvj:-NjMbyyk7oS7OdNN14TA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cee104892745177e69d0b32adf3f63a7d28cd213/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver/expressions/EngineGrpcExpressionService.java#L83)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Please write a test case for the same.
</blockquote></details>

Done.

**Comment by Aninditaa-ch** [comment]
trigger messagecheck

**Comment by Aninditaa-ch** [comment]
trigger ut3

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver/expressions/EngineGrpcExpressionService.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/55277#-NjkHktB22xqhi7gOlhF:-NjkHktB22xqhi7gOlhG:b28gj37) ([raw file](https://github.com/harness/harness-core/blob/a1b60a44e5128ebde24462977a16506cab456928/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver/expressions/EngineGrpcExpressionService.java#L43)):*
> ```Java
>   @Override
>   public String renderExpression(Ambiance ambiance, String expression, boolean skipUnresolvedExpressionsCheck) {
>     if (isEmpty(expression)) {
> ```

Rather than empty, can we check for null value only?
I think empty should be supported.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55277)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Comment by Aninditaa-ch** [comment]
trigger uts

**Comment by Aninditaa-ch** [comment]
trigger uts

**Comment by Aninditaa-ch** [comment]
trigger uts

**Comment by Aninditaa-ch** [comment]
trigger recency

**Comment by Aninditaa-ch** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver/expressions/EngineGrpcExpressionService.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/55277#-NjkHktB22xqhi7gOlhF:-NlMIouAEne30wldFxL6:b3pmxim) ([raw file](https://github.com/harness/harness-core/blob/a1b60a44e5128ebde24462977a16506cab456928/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver/expressions/EngineGrpcExpressionService.java#L43)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Rather than empty, can we check for null value only?
I think empty should be supported.
</blockquote></details>

@Aninditaa-ch , what are we throwing currently if expression is null or empty in this. Could you please check this locally?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55277)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by Aninditaa-ch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55277)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver/expressions/EngineGrpcExpressionService.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/55277#-NjkHktB22xqhi7gOlhF:-Nm4qruF2w3mAZyf0s6K:b-x9pwik) ([raw file](https://github.com/harness/harness-core/blob/a1b60a44e5128ebde24462977a16506cab456928/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver/expressions/EngineGrpcExpressionService.java#L43)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

@Aninditaa-ch , what are we throwing currently if expression is null or empty in this. Could you please check this locally?
</blockquote></details>

We are currently throwing NullPointerError in this case. Updated the expression to exclude the same.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55277)* status: Some of the checks are too old. 2 file(s) to review.

**Comment by shalini-agr** [comment]
trigger uts

**Comment by Aninditaa-ch** [comment]
trigger review

**Comment by shalini-agr** [comment]
trigger ut7, ut8, ut9

**Pull request merged**
