### PR TITLE
fix: [DEL-4555]: Fix version check in start.sh

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Describe your changes
This change set contains following fixes:
1) Version check in start.sh
2) Check for existence of config-delegate.yml before removing it in delegate.sh
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35855)

### CODE REVIEW

**Review by bharatgoelharness — DISMISSED** [review]

**Review by arpit3107 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35855)* status: :shipit: complete! ✓

**Comment by gaurav-jain1** [comment]
trigger ti3

**Comment by gaurav-jain1** [comment]
trigger ti3

**Comment by gaurav-jain1** [comment]
trigger ti3

**Comment by gaurav-jain1** [comment]
Screenshot 2022-08-01 at 12 21 24 PM
Marking `testGetDeploymentActiveFailedRunningInfo` test as flaky as it was passing locally.

**Comment by gaurav-jain1** [comment]
trigger ti3

**Review by bharatgoelharness — DISMISSED** [review]

**Comment by gaurav-jain1** [comment]
trigger ti0

**Comment by gaurav-jain1** [comment]
trigger ti2

**Review by bharatgoelharness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35855)* status: :shipit: complete! ✓

**Comment by gaurav-jain1** [comment]
trigger ti0

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35855)* status: :shipit: complete! ✓

**Comment by gaurav-jain1** [comment]
trigger ti0

**Comment by gaurav-jain1** [comment]
trigger ti0

**Pull request merged**
