### PR TITLE
[fix]: [CDS-81143]: Revert changes to avoid unexpected behaviour for merge inputset for pipeline

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
## Describe your changes
Revert the null check change made while calling yaml config and made the changes such that it affects only 1 api and doesn't cause unexpected behaviour for others

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55207)

### CODE REVIEW

**Comment by rathodmeetsatish** [comment]
trigger uts

**Review by vcalasansh — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55207)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by vcalasansh — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55207)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by sribalij — APPROVED** [review]

**Review by karansaraswat19 — DISMISSED** [review]

**Comment by rathodmeetsatish** [comment]
trigger review

**Review by sahibaHarness — APPROVED** [review]

**Comment by sahilhindwani-harness** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 106 at r4](https://reviewable.io/reviews/harness/harness-core/55207#-Nj78LSF3hMZSzIb5hiE:-Nj78LSGCrYBiGgbXWbJ:bvr6hld) ([raw file](https://github.com/harness/harness-core/blob/bb62cd6fba139794ae855fe1b9cc786605325f4a/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L106)):*
> ```Java
>       String inputSetPipelineCompYaml, boolean appendInputSetValidator, boolean isAtExecutionTime) {
>     YamlConfig originalYamlConfig = new YamlConfig(originalYaml);
>     YamlConfig inputSetConfig = new YamlConfig(inputSetPipelineCompYaml);
> ```

Please add UT for the same.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55207)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests.

**Comment by rathodmeetsatish** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55207)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by karansaraswat19 — APPROVED** [review]

**Comment by rathodmeetsatish** [comment]
trigger review

**Pull request merged**
