### PR TITLE
[techdebt]: [PIE-3973]: Remove validation methods from ValidateAndMergeHelper

### PR DESCRIPTION
**Pull request by namanvermah**
Removed all remaining usages of input set validation methods from `ValidateAndMergeHelper`, and removed those methods from that class as well. It only has merge related methods remaining now, which I'll pick up in the next PR.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34897)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34897)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 484 at r1](https://reviewable.io/reviews/harness/harness-core/34897#-N5sWXrJDLMIDtwt20Bd:-N5sWXrKAR4ODedwv0fY:b1egyb5) ([raw file](https://github.com/harness/harness-core/blob/e31de5095dfabc2d846e1064ba35a7c3e4a3fe3f/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L484)):*
> ```Java
> 
>     String pipelineBranch = gitEntityBasicInfo == null ? null : gitEntityBasicInfo.getBranch();
>     String pipelineRepoID = gitEntityBasicInfo == null ? null : gitEntityBasicInfo.getYamlGitConfigId();
> ```

I think we should create a helper passing git info to it it should return different values, like branch/repo, just like we have AmbianceUtils, rather than doing it by caller



_Code quote:_
```Java
    String pipelineBranch = gitEntityBasicInfo == null ? null : gitEntityBasicInfo.getBranch();
    String pipelineRepoID = gitEntityBasicInfo == null ? null : gitEntityBasicInfo.getYamlGitConfigId();
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34897)* status: 9 file(s) to review. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 484 at r1](https://reviewable.io/reviews/harness/harness-core/34897#-N5sWXrJDLMIDtwt20Bd:-N66gfUtBtKT1xVfZFsV:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e31de5095dfabc2d846e1064ba35a7c3e4a3fe3f/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L484)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I think we should create a helper passing git info to it it should return different values, like branch/repo, just like we have AmbianceUtils, rather than doing it by caller
</blockquote></details>

done

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34897)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34897)* status: :shipit: complete! ✓

**Pull request merged**
