### PR TITLE
feat: [CI-4564]: setting licence enforcement on provision

### PR DESCRIPTION
**Pull request by HenAmar**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33518)

### CODE REVIEW

**Review by aman-harness — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33518)* status: :shipit: complete! ✓

**Comment by HenAmar** [comment]
trigger messagecheck

**Comment by HenAmar** [comment]
trigger messagecheck

**Review by aman-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33518)* status: :shipit: complete! ✓

**Pull request merged**
