### PR TITLE
[feat]: [CDS-84603]: Updated GitXwebhook Db and added new mongo indexes for supporting webhooks at org and project

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Updated GitXWebhook and GitXWebhookEvent DBs along with adding new mongo indexes for supporting webhooks at org and project level.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55468)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhook.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/55468#-NjLrXDR-g_mIaQv0UbY:-NjLrXDR-g_mIaQv0UbZ:b-9iggei) ([raw file](https://github.com/harness/harness-core/blob/32864b41b9e2bd0c7e4208e8ff217b0398156d05/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhook.java#L89)):*
> ```Java
>                  .build())
>         .add(CompoundMongoIndex.builder()
>                  .name("accountIdentifier_orgIdentifier_identifier_unique_idx")
> ```

If this is unique then why do we need accountIdentifier_orgIdentifier_projectIdentifier?
Why cant we query based on this?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55468)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by adivishy1** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhook.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/55468#-NjLrXDR-g_mIaQv0UbY:-NjMflKyBygIOgM_rGdx:b-brp4xh) ([raw file](https://github.com/harness/harness-core/blob/32864b41b9e2bd0c7e4208e8ff217b0398156d05/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhook.java#L89)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

If this is unique then why do we need accountIdentifier_orgIdentifier_projectIdentifier?
Why cant we query based on this?
</blockquote></details>

Agreed, thanks for clarifying the same, have removed the extra indexes

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55468)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhook.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/55468#-NjLrXDR-g_mIaQv0UbY:-NjMiv8x0Ng_oAXxEZX0:b7e4upt) ([raw file](https://github.com/harness/harness-core/blob/32864b41b9e2bd0c7e4208e8ff217b0398156d05/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhook.java#L89)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Agreed, thanks for clarifying the same, have removed the extra indexes
</blockquote></details>

please validate the collections are not big, else these needs to be created before hand

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55468)* status: :shipit: complete! ✓

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
