### PR TITLE
fix:[CDS-45448]: Code guard to avoid the NPE

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
The stack trace root cause is related to missing the YAML validator class in some elements of `software.wings.sm.StepType`. When an element without the validator class is used it throws the NPE and all those lines are added to the log.

I’m adding a code guard to avoid the NPE, as it is not clear if all elements should have a reference to a validator class.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40565)

### CODE REVIEW

**Comment by Fernando-Dourado** [comment]
trigger checkstylecodeformat

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40565)* status: :shipit: complete! ✓

**Review by lasdox — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40565)* status: :shipit: complete! ✓

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40565)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/handler/workflow/StepYamlBuilderFactory.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/40565#-NHeR1FF78taGBBAuNOt:-NHeR1FF78taGBBAuNOu:b516wj1) ([raw file](https://github.com/harness/harness-core/blob/af82918e7ecb0e7260c6394eb0feca450929c155/400-rest/src/main/java/software/wings/service/impl/yaml/handler/workflow/StepYamlBuilderFactory.java#L33)):*
> ```Java
>         validator = injector.getInstance(stepType.getYamlValidatorClass());
>       } else {
>         log.warn("Can not get step yaml builder for step type {} as the YAML validator class is null", stepType);
> ```

let's change the log level to debug here because validator class being null should be expected for few steps.

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40565)* status: :shipit: complete! ✓

**Pull request merged**
