### PR TITLE
feat: [SRM-10049]: yaml template api for monitoredService

### PR DESCRIPTION
**Pull request by AbhijithHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32754)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32754)* status: 15 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/cv-nextgen-config.yml` line 58 at r3](https://reviewable.io/reviews/harness/harness-core/32754#-N1Haw2U53P_QSb4CosB:-N1Haw2VDsNLWXRSEN35:bpui8vd) ([raw file](https://github.com/harness/harness-core/blob/38875c0383d4c40d91a9f28a197af8ee773dd77b/300-cv-nextgen/cv-nextgen-config.yml#L58)):*
> ```YAML
>   readTimeOutSeconds: 15
> 
> templateServiceClientConfig:
> ```

will startup fail if we can not connect to template service?
Also I think we need to add overrides for these and plan out the changes in all the envs.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/CVServiceModule.java` line 383 at r2](https://reviewable.io/reviews/harness/harness-core/32754#-N1HUCsAC0bk47IHItLV:-N1HUCsAC0bk47IHItLW:b-78nmep) ([raw file](https://github.com/harness/harness-core/blob/d87bdc95d23b569269559af46a8d11aad7fca709/300-cv-nextgen/src/main/java/io/harness/cvng/CVServiceModule.java#L383)):*
> ```Java
>                 .build()));
>     install(PrimaryVersionManagerModule.getInstance());
>     install(new TemplateResourceClientModule(verificationConfiguration.getTemplateServiceClientConfig(),
> ```

I think we can install it outside of the module. That way we can have a fake implementation of this module in the testing setup.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/resources/MonitoredServiceResource.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/32754#-N1HUi5616QUcEsL3YuH:-N1HUi5616QUcEsL3YuI:bwf62ri) ([raw file](https://github.com/harness/harness-core/blob/d87bdc95d23b569269559af46a8d11aad7fca709/300-cv-nextgen/src/main/java/io/harness/cvng/core/resources/MonitoredServiceResource.java#L95)):*
> ```Java
>   @Timed
>   @ExceptionMetered
>   @ApiOperation(value = "saves monitored service from template", nickname = "Edit Configurations...")
> ```

I think nickname is not correct. This name is used by UI in the generated client

**Review by AbhijithHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32754)* status: 16 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/cv-nextgen-config.yml` line 58 at r3](https://reviewable.io/reviews/harness/harness-core/32754#-N1Haw2U53P_QSb4CosB:-N1MaKzj027uFFhZSPzS:bkz8zb4) ([raw file](https://github.com/harness/harness-core/blob/38875c0383d4c40d91a9f28a197af8ee773dd77b/300-cv-nextgen/cv-nextgen-config.yml#L58)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

will startup fail if we can not connect to template service?
Also I think we need to add overrides for these and plan out the changes in all the envs.
</blockquote></details>

it will startup, only those APIs depending on this will fail.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/CVServiceModule.java` line 383 at r2](https://reviewable.io/reviews/harness/harness-core/32754#-N1HUCsAC0bk47IHItLV:-N1MaRW-8Zu2g8rNeCQI:bolew6v) ([raw file](https://github.com/harness/harness-core/blob/d87bdc95d23b569269559af46a8d11aad7fca709/300-cv-nextgen/src/main/java/io/harness/cvng/CVServiceModule.java#L383)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

I think we can install it outside of the module. That way we can have a fake implementation of this module in the testing setup.
</blockquote></details>

We can still override even if we define in this module, as we have overridden clock, right?
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/resources/MonitoredServiceResource.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/32754#-N1HUi5616QUcEsL3YuH:-N1Mav-d18IQWSxq9Hvw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d87bdc95d23b569269559af46a8d11aad7fca709/300-cv-nextgen/src/main/java/io/harness/cvng/core/resources/MonitoredServiceResource.java#L95)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

I think nickname is not correct. This name is used by UI in the generated client 
</blockquote></details>

Done.

**Review by kjoshi12345 — DISMISSED** [review]
:lgtm:

> Reviewed 7 of 15 files at r1, 5 of 5 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32754#-:-N1MsHZ6DaYdpPCGn4dB:bnfp4nl)* status: :shipit: complete! ✓

___
*[`300-cv-nextgen/container/scripts/replace_configs.sh` line 175 at r4](https://reviewable.io/reviews/harness/harness-core/32754#-N1MriVz6DfCDg7YnhqU:-N1MriVz6DfCDg7YnhqV:b-opap7c) ([raw file](https://github.com/harness/harness-core/blob/357b1955899d26e0f2f611395154779fb51352e2/300-cv-nextgen/container/scripts/replace_configs.sh#L175)):*
> ```Shell
> replace_key_value accessControlClientConfig.accessControlServiceSecret "$ACCESS_CONTROL_SECRET"
> 
> replace_key_value templateServiceClientConfig.baseUrl "$TEMPLATE_SERVICE_ENDPOINT"
> ```

We need a variable for templateServiceSecret also right?

**Review by deepak-harness — APPROVED** [review]
> Reviewed 5 of 15 files at r1, 1 of 5 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32754)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32754)* status: :shipit: complete! ✓

**Review by AbhijithHarness — COMMENTED** [review]
> Reviewed 5 of 15 files at r1, 1 of 5 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32754)* status: 1 file(s) to review.

**Comment by AbhijithHarness** [comment]
*[`300-cv-nextgen/container/scripts/replace_configs.sh` line 175 at r4](https://reviewable.io/reviews/harness/harness-core/32754#-N1MriVz6DfCDg7YnhqU:-N1O8fvd4Hzk-ltL-ad1:b9tbw2k) ([raw file](https://github.com/harness/harness-core/blob/357b1955899d26e0f2f611395154779fb51352e2/300-cv-nextgen/container/scripts/replace_configs.sh#L175)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

We need a variable for templateServiceSecret also right?
</blockquote></details>

will add in next PR

**Comment by AbhijithHarness** [comment]
trigger pmd

**Pull request merged**
