### PR TITLE
[fix]: [PL-23131]: fixing default values in config and making Open api spec …

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
…generation test inherit from  CategoryTest

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32777)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32777)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/test/java/io/harness/ng/GenerateOpenApiSpecCommandTest.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/32777#-N1ENTNY5byZxwwu1pTo:-N1ETcUEDOZJEYe8LGzh:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/865beb7be0070306e5ef668c88ebcfc952648590/120-ng-manager/src/test/java/io/harness/ng/GenerateOpenApiSpecCommandTest.java#L37)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Avoid CategoryTest if not needed (everywhere). This just adds time to execution of the tests and it seems not necessary in this case. 
</blockquote></details>

Fixed

**Comment by ashishsanodia-harness** [comment]
*[`340-ce-nextgen/src/test/java/io/harness/ccm/GenerateOpenApiSpecCommandTest.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/32777#-N1ENfg5Al0_eSjklkL3:-N1ETgCG61AOoUyDo0dE:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/865beb7be0070306e5ef668c88ebcfc952648590/340-ce-nextgen/src/test/java/io/harness/ccm/GenerateOpenApiSpecCommandTest.java#L37)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

same
</blockquote></details>

Fixed

**Comment by ashishsanodia-harness** [comment]
trigger authorcheck

**Review by jamie-harness — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32777)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32777#-:-N1FnX-o2ZGxIXfutY3N:bnfp4nl)* status: 10 file(s) to review.

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32777)* status: 6 file(s) to review.

**Review by jennyjames21 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32777)* status: 6 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32777)* status: 6 file(s) to review.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32777)* status: 6 file(s) to review.

**Review by puneetsar — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32777)* status: 6 file(s) to review.

**Pull request merged**
