### PR TITLE
feat: [PL-43003]: Add log integration for init task

### PR DESCRIPTION
**Pull request by AnupamIO**
Add log integration for init task.

Details:
There are few of things missing as part of this PR.
- logs aren't getting streamed using UI, we are able to tail log using curl directly.
- /stream call from UI is sometimes not getting started timely, it starts after task execution is done on step container and closing of stream. We need to check why such delay in stream call is happening. Till then we can avoid closing stream from code for testing purposes. This won't impact anything because this is not in production.
- If events are not streaming correctly, we can stop closing event watcher for local testing, it will automatically close after timeout. 

Testing:

Screenshot 2023-11-24 at 8 10 37 PM

Blob api output on UI:
Screenshot 2023-11-27 at 7 57 06 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55994)

### CODE REVIEW

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55994)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/BUILD.bazel` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG-MCc8uEMFsGQDjL8:-NkG-MCc8uEMFsGQDjL9:b-g0awjp) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/BUILD.bazel#L22)):*
> ```Starlark
>         "//260-delegate/src/main/java/io/harness/delegate/service/secret:module",
>         "//260-delegate/src/main/java/io/harness/delegate/service/tasklogging:module",
>          "//260-delegate/src/main/java/io/harness/logstreaming:module",
> ```

Minor: formatting
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG0EqXE1VrbjSM_he4:-NkG0EqXE1VrbjSM_he5:b26qjvx) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L124)):*
> ```Java
> 
>       logStreamingTaskClient = getLogStreamingTaskClient(loggingToken, logKey);
>       logStreamingTaskClient.openStream(null);
> ```

Should we supply logKey to openStream()?
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 141 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG0VtO50YSNMx-Vk-f:-NkG0VtO50YSNMx-Vk-g:b-mq6xim) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L141)):*
> ```Java
> 
>       streamLogLine(
>           logStreamingTaskClient, LogLevel.INFO, format("Starting job to create pod on %s namespace", namespace));
> ```

Missing pod name in the log message.
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 164 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG1IIzAr6d4EE3gfdm:-NkG1IIzAr6d4EE3gfdn:byzaysd) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L164)):*
> ```Java
> 
>       streamLogLine(logStreamingTaskClient, LogLevel.INFO,
>           format("Done creating the task pod %s for %s!!", pod.getMetadata().getName(), infraId));
> ```

The msg could be: Pod %s is in running status on %s namespace.
Can we have info messages related to created containers on pod? 
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 165 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG109X2W3xiABG_X04:-NkG109X2W3xiABG_X05:bxfky8l) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L165)):*
> ```Java
>       streamLogLine(logStreamingTaskClient, LogLevel.INFO,
>           format("Done creating the task pod %s for %s!!", pod.getMetadata().getName(), infraId));
>       //  sleep(ofSeconds(5));
> ```

Remove the comment.
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 169 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG1ZHJ-cOCqCYssZdJ:-NkG1ZHJ-cOCqCYssZdK:bxfky8l) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L169)):*
> ```Java
>       if (watch != null) {
>         k8EventHandler.stopEventWatch(watch);
>         // sleep(ofMinutes(1));
> ```

Remove the comment.
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG1cZE0sd0anWkOcxb:-NkG1cZE0sd0anWkOcxc:bqdejcc) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L182)):*
> ```Java
>     } finally {
>       if (logStreamingTaskClient != null) {
>         logStreamingTaskClient.closeStream(null);
> ```

I think we need also logKey here. Based on the logKey, the log service will move(snapshot) logs from the stream(Redis) to the blob store and delete existing streams.
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 328 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG2H6K6yn6FP2LeWya:-NkG2H6K6yn6FP2LeWyb:bo8md6k) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L328)):*
> ```Java
>         // client need to send logKey for init task as well, this logKey will be used to create and push logs to stream
>         // from delegate runner.
>         .baseLogKey(logKey)
> ```

Do we need logKey here or pass it while opening a stream? I think we need logPrefix as the base key and log key pass to openStream method.
It means when the logKey is null, logPrefix will serve for open/stream/blob/close the logs.  
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 333 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG2TTvBOWHfx6gc3zZ:-NkG2TTvBOWHfx6gc3z_:bp02wcg) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L333)):*
> ```Java
>   }
> 
>   private void streamLogLine(ILogStreamingTaskClient logStreamingTaskClient, LogLevel logLevel, String message) {
> ```

The methods getLogStreamingTaskClient and streamLogLine should be moved to some helper/common logs class.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/K8EventHandler.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG5lcQ37pOQxpXTiBk:-NkG5lcQ37pOQxpXTiBl:b-c7zca) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/K8EventHandler.java#L91)):*
> ```Java
>       CoreV1Api coreV1ApiInput) throws ApiException {
>     ApiClient apiClient =
>         coreV1ApiInput != null ? coreV1ApiInput.getApiClient() : apiClientFactory.getClient(kubernetesConfig);
> ```

When oreV1ApiInput is null?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/K8EventHandler.java` line 110 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG5QqY8Sc24N7_ZnqQ:-NkG5QqY8Sc24N7_ZnqR:bde5imu) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/K8EventHandler.java#L110)):*
> ```Java
>       }
>     } catch (Exception ex) {
>       log.info("Exception is ", ex);
> ```

Can we log this on an error or warn level and having a meaningful msg instead of "Exception is"

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55994)* status: 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/BUILD.bazel` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkGI3DLBtm1QnInWyHw:-NkGI3DLBtm1QnInWyHx:bovbvkx) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/BUILD.bazel#L23)):*
> ```Starlark
>         "//260-delegate/src/main/java/io/harness/delegate/service/tasklogging:module",
>          "//260-delegate/src/main/java/io/harness/logstreaming:module",
>         "//930-delegate-tasks:module",
> ```

We should try to avoid this (direct) dep. Though I could see that it still creeps in through the logging client. 
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkGEaj5BAXWvUgb3h2q:-NkGEaj5BAXWvUgb3h2r:b-ni8iym) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L93)):*
> ```Java
>   private final LogStreamingClient logStreamingClient;
>   private final DelegateLogService delegateLogService;
>   private final K8EventHandler k8EventHandler;
> ```

I think I understand now why I left the logging implementation for later when doing init. 
`K8EventHandler` forces you to bring in the entire 930-delegate-task dep (we are trying to remove that dep from K8S Runner. Right now it wouldn't make a difference to the final size of the .jar because both K8SRunner and 930-delegate-tasks get imported in the immutable delegate (260-delegate), but still not the right thing to do. 
Another problem with this class is that it requires a separate K8S API client (not the one used by the runner to create pods). This client has problems of it's own (which is why I haven't ported it to Bijou project). 

I suggest you create a knock off of this class. Put it in the runner code and inject the runner API client. 
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 333 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG2TTvBOWHfx6gc3zZ:-NkGIm2CExJuf_ovzglC:bz2e6ka) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L333)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The methods getLogStreamingTaskClient and streamLogLine should be moved to some helper/common logs class.
</blockquote></details>

Create a separate class which extends the ILogStreamingTaskClient. getLog... method can be your factory method for that class, streamLogLine (or better just call it `log`) can be your logging method. No need to reimplement each of them in different classes (e.g. in eventHandler), just provide instance to this class. 

Note: I would rather do composition instead of inheritance for this new class (i.e. ILogStreamingTaskClient is a field, not implemented interface), but that can only work if you re-implement the k8EventHandler (which I also suggest you do anyway). 
___
*[`920-delegate-service-beans/src/main/proto/io/harness/delegate/log_config.proto` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkGHf3i6Vef0O7lPzvj:-NkGHf3i6Vef0O7lPzvk:b-b0529y) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/920-delegate-service-beans/src/main/proto/io/harness/delegate/log_config.proto#L16)):*
> ```proto
>   string log_prefix = 1;
>   // This log key is used for streaming init Task logs
>   string log_key = 2;
> ```

Not sure I understand why do you need a separate log_key? Why not using log_prefix?
What is the value we expect in the log_key?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/K8EventHandler.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG5lcQ37pOQxpXTiBk:-NkGKOAtEgNJaE0XJO8I:b-ffrmkf) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/K8EventHandler.java#L91)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

When oreV1ApiInput is null?
</blockquote></details>

Lets not use this class. This is just a hack.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55994)* status: 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 141 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG0VtO50YSNMx-Vk-f:-NkGKBzcCkv_I8au77g6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L141)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Missing pod name in the log message.
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 165 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG109X2W3xiABG_X04:-NkGKy7E6xc57dDCv_IW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L165)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Remove the comment.
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 169 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG1ZHJ-cOCqCYssZdJ:-NkGKxwy5opjP3mORkio:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L169)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Remove the comment.
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG1cZE0sd0anWkOcxb:-NkGL4xJ4VxRWJva7se6:bgr1zq5) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L182)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I think we need also logKey here. Based on the logKey, the log service will move(snapshot) logs from the stream(Redis) to the blob store and delete existing streams.
</blockquote></details>

not needed, same reason as above. Here we supply logKeySuffix

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55994)* status: 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 328 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG2H6K6yn6FP2LeWya:-NkGeEtV5AptC9lRGsPv:b-emefv4) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L328)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Do we need logKey here or pass it while opening a stream? I think we need logPrefix as the base key and log key pass to openStream method.
It means when the logKey is null, logPrefix will serve for open/stream/blob/close the logs.
</blockquote></details>

removed logKey from init, we will use existing logPrefix
___
*[`920-delegate-service-beans/src/main/proto/io/harness/delegate/log_config.proto` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkGHf3i6Vef0O7lPzvj:-NkGeQG648mh5MtRdBCN:b-4r9wah) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/920-delegate-service-beans/src/main/proto/io/harness/delegate/log_config.proto#L16)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Not sure I understand why do you need a separate log_key? Why not using log_prefix?
What is the value we expect in the log_key?
</blockquote></details>

thats a fair point, we can use log_prefix only. sorry for mixup.

**Review by xingchi-jin — APPROVED** [review]

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55994)* status: 8 file(s) to review. 2 change requests. 10. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkGEaj5BAXWvUgb3h2q:-NkJiZ_t5kQdyKADNbYP:bvkxxrk) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L93)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I think I understand now why I left the logging implementation for later when doing init. 
`K8EventHandler` forces you to bring in the entire 930-delegate-task dep (we are trying to remove that dep from K8S Runner. Right now it wouldn't make a difference to the final size of the .jar because both K8SRunner and 930-delegate-tasks get imported in the immutable delegate (260-delegate), but still not the right thing to do. 
Another problem with this class is that it requires a separate K8S API client (not the one used by the runner to create pods). This client has problems of it's own (which is why I haven't ported it to Bijou project). 

I suggest you create a knock off of this class. Put it in the runner code and inject the runner API client.
</blockquote></details>

created similar class and injected api client.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55994)* status: 8 file(s) to review. 2 change requests. 11. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 124 at r2](https://reviewable.io/reviews/harness/harness-core/55994#gh-1406562088:-NkJitSJ0Ag65h2EJhkU:b-6xrcoe) ([raw file](https://github.com/harness/harness-core/blob/7b9533a8235f06f65ab2bc68816a066a43f044b8/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L124)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

why this is null ? 
</blockquote></details>

this is to supply if we have any log suffix, passing null because we dont have any suffix for log stream. same as current flow https://github.com/harness/harness-core/blob/develop/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2477

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55994)* status: 8 file(s) to review. 2 change requests. 12. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 333 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG2TTvBOWHfx6gc3zZ:-NkKieuE-Oo8-YNDcXQR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L333)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Create a separate class which extends the ILogStreamingTaskClient. getLog... method can be your factory method for that class, streamLogLine (or better just call it `log`) can be your logging method. No need to reimplement each of them in different classes (e.g. in eventHandler), just provide instance to this class. 

Note: I would rather do composition instead of inheritance for this new class (i.e. ILogStreamingTaskClient is a field, not implemented interface), but that can only work if you re-implement the k8EventHandler (which I also suggest you do anyway).
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/K8EventHandler.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG5lcQ37pOQxpXTiBk:-NkJjDwfED31iGqcu23z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/K8EventHandler.java#L91)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Lets not use this class. This is just a hack.
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/K8EventHandler.java` line 110 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG5QqY8Sc24N7_ZnqQ:-NkKkGhG1B3S719jG25Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/K8EventHandler.java#L110)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can we log this on an error or warn level and having a meaningful msg instead of "Exception is"
</blockquote></details>

Done.

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55994#-:-NkKljid1SCylUosPLyi:bnfp4nl)* status: 8 file(s) to review. 1 change requests. 4. unresolved discussions.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55994)* status: 8 file(s) to review. 1 change requests. 5. unresolved discussions. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/BUILD.bazel` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkGI3DLBtm1QnInWyHw:-NkKnlff2UH9mkTQSMSC:bxoluje) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/BUILD.bazel#L23)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

We should try to avoid this (direct) dep. Though I could see that it still creeps in through the logging client.
</blockquote></details>

I would say let's merge this to unblock Ivan, meanwhile i'll figure out to break down dependencies to smaller build files and use that bazel module in bijou.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55994)* status: 8 file(s) to review. 1 change requests. 5. unresolved discussions. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 333 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkG2TTvBOWHfx6gc3zZ:-NkKpdbqBVNjDy2W8daM:b-ylxddf) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L333)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

just a note, we don't want instance to be static. We want each task to have different instance of logStreamingTaskClient.

**Comment by AnupamIO** [comment]
trigger uts

**Review by mdmilic — APPROVED** [review]
> Reviewed 6 of 8 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55994)* status: 9 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/BUILD.bazel` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/55994#-NkGI3DLBtm1QnInWyHw:-NkLCAcqAsoFhB69fsFS:btytqdx) ([raw file](https://github.com/harness/harness-core/blob/f3e20725bda908bad7abaa6ebf738cf498f3d974/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/BUILD.bazel#L23)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

I would say let's merge this to unblock Ivan, meanwhile i'll figure out to break down dependencies to smaller build files and use that bazel module in bijou.
</blockquote></details>

Sure, just re-run the build cleaner (if that's what you were using), I think you won't need 930-delegate-tasks after removing K8EventHandler. 
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 158 at r3](https://reviewable.io/reviews/harness/harness-core/55994#-NkLF0EW8vtpOXdRQIIs:-NkLF0EW8vtpOXdRQIIt:beiwlh5) ([raw file](https://github.com/harness/harness-core/blob/bd2ada50ec266af3e12695d931b5bc1875136842/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L158)):*
> ```Java
>           k8EventHandler.startAsyncPodEventWatch(namespace, pod.getMetadata().getName(), logStreamingTaskClient);
> 
>       coreApi.createNamespacedPod(namespace, pod, null, null, DELEGATE_FIELD_MANAGER, "Warn");
> ```

You are first starting a watch for a pod, then creating a pod. Would this work, or do you need to do it the other way around?

Also, I think createPod API doesn't wait for the pod to become ready, just finishes when the Pod is created (but still unscheduled). CI Waits for the Pod status to become ready before finishing the init and stopping the watch.
Maybe this would be enough for @ivan-83 for right now, but he wouldn't get the full Pod startup logs I think. I think that's OK and we can work on waiting for pod to be Ready separately.



_Code quote:_
```Java
      Watch<CoreV1Event> watch =
          k8EventHandler.startAsyncPodEventWatch(namespace, pod.getMetadata().getName(), logStreamingTaskClient);

      coreApi.createNamespacedPod(namespace, pod, null, null, DELEGATE_FIELD_MANAGER, "Warn");
```

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55994)* status: 9 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 158 at r3](https://reviewable.io/reviews/harness/harness-core/55994#-NkLF0EW8vtpOXdRQIIs:-NkLISPt0l6il8n175gr:b-1fjzps) ([raw file](https://github.com/harness/harness-core/blob/bd2ada50ec266af3e12695d931b5bc1875136842/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L158)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You are first starting a watch for a pod, then creating a pod. Would this work, or do you need to do it the other way around?

Also, I think createPod API doesn't wait for the pod to become ready, just finishes when the Pod is created (but still unscheduled). CI Waits for the Pod status to become ready before finishing the init and stopping the watch.
Maybe this would be enough for @ivan-83 for right now, but he wouldn't get the full Pod startup logs I think. I think that's OK and we can work on waiting for pod to be Ready separately.
</blockquote></details>

1- You are first starting a watch for a pod, then creating a pod. Would this work, or do you need to do it the other way around?
Yes, this way it works. I also tried other way around and we were not getting any logs.

2- Yes, that's true that's why in some cases, i had to avoid closing event watcher or else it will not stream all logs. Will check this separately, synced with Ivan regarding this yesterday, he can avoid closing watcher (it will eventually close after timeout) for local testing. Will raise a jira and fix this.

**Comment by AnupamIO** [comment]
trigger ut9

**Comment by AnupamIO** [comment]
trigger messagecheck

**Review by ankittiwari-harness — APPROVED** [review]
added codeowner approval

**Pull request merged**
