### PR TITLE
fix: [CDS-70686]: add serializer for object node and array node

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Issue:** When there's an object node or array node with a text node of value "12e34" serialized into yaml string, we need to add a custom serializer for our custom trigger for the text node to be used. 

**Testing:** Validated locally by creating pipeline, stage, and step templates with variables with value "12e34".

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48564)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48564)* status: 5 file(s) to review. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/serializer/jackson/EdgeCaseRegexArraySerializer.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/48564#-NWl7XUs9CiRms4BjWFz:-NWl7XUs9CiRms4BjWG-:bbwq6fv) ([raw file](https://github.com/harness/harness-core/blob/dc92c943857750274a3576ac84efef22477d8c89/970-ng-commons/src/main/java/io/serializer/jackson/EdgeCaseRegexArraySerializer.java#L20)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> public class EdgeCaseRegexArraySerializer extends StdSerializer<ArrayNode> {
> ```

You can only override serialiser for textNode inside array default serialiser


public class CustomArraySerializers extends StdArraySerializers {
    public static class CustomTextNodeSerializer extends JsonSerializer<TextNode> {
        @Override
        public void serialize(TextNode textNode, JsonGenerator jsonGenerator, SerializerProvider serializerProvider) throws IOException {
            jsonGenerator.writeString(textNode.textValue().toUpperCase()); // Custom serialization logic
        }
    }
}
___
*[`970-ng-commons/src/main/java/io/serializer/jackson/EdgeCaseRegexObjectSerializer.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/48564#-NWl7viW1plJz65tRbTl:-NWl7viW1plJz65tRbTm:bzbgc6t) ([raw file](https://github.com/harness/harness-core/blob/dc92c943857750274a3576ac84efef22477d8c89/970-ng-commons/src/main/java/io/serializer/jackson/EdgeCaseRegexObjectSerializer.java#L29)):*
> ```Java
>     gen.writeStartObject();
>     value.fields().forEachRemaining(entry -> {
>       String key = entry.getKey();
> ```

For Object this could be simplfied as


public static class CustomObjectNodeSerializer extends StdSerializer<ObjectNode> {
        public CustomObjectNodeSerializer() {
            super(ObjectNode.class);
        }

        @Override
        public void serialize(ObjectNode objectNode, JsonGenerator jsonGenerator, SerializerProvider serializerProvider) throws IOException {
            DefaultSerializerProvider.Impl provider = (DefaultSerializerProvider.Impl) serializerProvider;
            JsonSerializer<Object> textNodeSerializer = provider.findValueSerializer(TextNode.class);
            
            jsonGenerator.writeStartObject();
            for (String fieldName : objectNode.fieldNames()) {
                jsonGenerator.writeFieldName(fieldName);
                if (objectNode.get(fieldName) instanceof TextNode) {
                    textNodeSerializer.serialize(objectNode.get(fieldName), jsonGenerator, serializerProvider);
                } else {
                    serializerProvider.defaultSerializeValue(objectNode.get(fieldName), jsonGenerator);
                }
            }
            jsonGenerator.writeEndObject();
        }
    }
___
*[`template-service/service/src/test/java/io/harness/template/yaml/TemplateYamlUtilsTest.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/48564#-NWl5Dzu9UyaV2diiQra:-NWl5Dzu9UyaV2diiQrb:bgt9f77) ([raw file](https://github.com/harness/harness-core/blob/dc92c943857750274a3576ac84efef22477d8c89/template-service/service/src/test/java/io/harness/template/yaml/TemplateYamlUtilsTest.java#L34)):*
> ```Java
>     Map map = new LinkedHashMap<String, Object>();
>     JsonNode jsonNode = JsonUtils.readTree(
>         "{\"stages\":[{\"stage\":{\"name\":\"cs\",\"identifier\":\"cs\",\"description\":\"\",\"type\":\"Custom\",\"spec\":{\"execution\":{\"steps\":[{\"step\":{\"type\":\"ShellScript\",\"name\":\"ShellScript_1\",\"identifier\":\"ShellScript_1\",\"spec\":{\"shell\":\"Bash\",\"onDelegate\":true,\"source\":{\"type\":\"Inline\",\"spec\":{\"script\":\"echo <+pipeline.variables.var1>\"}},\"environmentVariables\":[],\"outputVariables\":[]},\"timeout\":\"10m\"}}],\"rollbackSteps\":[]},\"serviceDependencies\":[]},\"tags\":{}}}],\"variables\":[{\"name\":\"var1\",\"type\":\"String\",\"description\":\"\",\"value\":\"+1234\"},{\"name\":\"var2\",\"type\":\"String\",\"description\":\"\",\"value\":\"23e45\"},{\"name\":\"var3\",\"type\":\"String\",\"description\":\"\",\"value\":\"abcd\"},{\"name\":\"var4\",\"type\":\"String\",\"description\":\"\",\"value\":\"2145\"}]}");
> ```

can you put this into some file content? and same for response?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48564)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/test/java/io/harness/template/yaml/TemplateYamlUtilsTest.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/48564#-NWl5Dzu9UyaV2diiQra:-NWlP1hv9QWJg-5cREYd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dc92c943857750274a3576ac84efef22477d8c89/template-service/service/src/test/java/io/harness/template/yaml/TemplateYamlUtilsTest.java#L34)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you put this into some file content? and same for response?
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48564)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Review by utkarshchoubey-harness — APPROVED** [review]
LGTM

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
