### PR TITLE
[feat]: [CDS-40882]: Refactor Artifactory repositoryDetails endpoint

### PR DESCRIPTION
**Pull request by nassergonzalez**
## Describe your changes
Change the repositoryDetails endpoint to work with the new refactoring that is happening around the Services. 
The new endpoint will keep the previous behaviour if the serviceRef is not sent, or it will retrieve the service data given an serviceRef and a fqnPath, and from there, the connectorId

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35786)

### CODE REVIEW

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35786)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35786)* status: :shipit: complete! ✓

**Review by hingerabhinav — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35786)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java` line 194 at r1](https://reviewable.io/reviews/harness/harness-core/35786#-N82ksbFCrSyJxjaGpT0:-N82ksbFCrSyJxjaGpT1:b-3ur2gr) ([raw file](https://github.com/harness/harness-core/blob/3cf0e4bd4716d01be68a84652c3b72f03084490f/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java#L194)):*
> ```Java
>       ArtifactoryRegistryArtifactConfig artifactoryRegistryArtifactConfig =
>           (ArtifactoryRegistryArtifactConfig) artifactSpecFromService;
> ```

Should we also get repo type from artifact spec if its not present in payload?

**Comment by nassergonzalez** [comment]
trigger messagecheck

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35786)* status: 1. unresolved discussions. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java` line 194 at r1](https://reviewable.io/reviews/harness/harness-core/35786#-N82ksbFCrSyJxjaGpT0:-N82rp8dAsc-rNb-hY6K:bord4sj) ([raw file](https://github.com/harness/harness-core/blob/3cf0e4bd4716d01be68a84652c3b72f03084490f/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java#L194)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

Should we also get repo type from artifact spec if its not present in payload? 
</blockquote></details>

From what I gathered, the UI will always send the type of artifact type. I could not see that field in the service definition and the default value is any

**Review by tmacari-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35786)* status: 1. unresolved discussions.

**Review by hingerabhinav — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35786)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java` line 194 at r1](https://reviewable.io/reviews/harness/harness-core/35786#-N82ksbFCrSyJxjaGpT0:-N83DbGp6xhTHR1CDbqo:bkr8e4e) ([raw file](https://github.com/harness/harness-core/blob/ae2056277c84c0e8b43eb656f22359145e1c98bd/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java#L194)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

From what I gathered, the UI will always send the type of artifact type. I could not see that field in the service definition and the default value is any
</blockquote></details>

Ok got it

**Pull request merged**
