### PR TITLE
fix: [CI-0]: Add Rutvij Mehta to authorsList.txt

### PR DESCRIPTION
**Pull request by rutvijmehta-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32339)

### CODE REVIEW

**Review by hemanthmantri — APPROVED** [review]
LGTM

**Review by hemanthmantri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32339#-:-N02_zSF0koFYdtoUn1E:bnfp4nl)* status: 1 file(s) to review.

**Review by hemanthmantri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32339#-:-N02a1yPEO4wjhaCsfdJ:bnfp4nl)* status: 1 file(s) to review.

**Comment by rutvijmehta-harness** [comment]
trigger messagecheck

**Review by rutvijmehta-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32339)* status: 1 file(s) to review.

**Review by hemanthmantri — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32339#-:-N02xUIu-0LXERaw-iTf:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
