### PR TITLE
fix: [PL-29704]: Cleanup env folder first in case of svc rename

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40046)

### CODE REVIEW

**Review by srinivaswings — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40046)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by srinivaswings — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40046)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by Y0709 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40046)* status: 1 file(s) to review. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 484 at r3](https://reviewable.io/reviews/harness/harness-core/40046#-NGjuPj-7avLNvsO0JjX:-NGjuPj-7avLNvsO0JjY:b-rch9f6) ([raw file](https://github.com/harness/harness-core/blob/41057d4e6e2b47ff61b0218f55e230ff8c6e26b8/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L484)):*
> ```Java
>   SPG_DELETE_ENVIRONMENTS_ON_SERVICE_RENAME_GIT_SYNC(
>       "On service rename delete stale folders inside environments folders.", HarnessTeam.SPG),
>   GITOPS_API_PARAMS_MERGE_PR("Show API parameters in Merge PR step", HarnessTeam.GITOPS),
> ```

I think ff GITOPS_API_PARAMS_MERGE_PR is added twice here

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40046)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 484 at r3](https://reviewable.io/reviews/harness/harness-core/40046#-NGjuPj-7avLNvsO0JjX:-NGk--_wDH1FRy9Qz1az:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/41057d4e6e2b47ff61b0218f55e230ff8c6e26b8/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L484)):*
<details><summary><i>Previously, Y0709 (Yuvraj Singhal) wrote…</i></summary><blockquote>

I think ff GITOPS_API_PARAMS_MERGE_PR is added twice here 
</blockquote></details>

Done.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40046)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by Y0709 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40046)* status: 1. unresolved discussions.

**Review by Y0709 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40046)* status: :shipit: complete! ✓

**Pull request merged**
