### PR TITLE
[fix]: [SRM-13949]: Changing the implementation for verificationTask cleanup for improved DB performance

### PR DESCRIPTION
**Pull request by dhruv-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45034)

### CODE REVIEW

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/45034#-NQOy6Cc41JPmxCtA2id:-NQOy6Cc41JPmxCtA2ie:b2d55l3) ([raw file](https://github.com/harness/harness-core/blob/cd86bce4366d3ec3cc1dff174d03e82bcc9e50f7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java#L125)):*
> ```Java
>       while (mongoCursor.hasNext()) {
>         numberOfRecordsDeleted++;
>         hPersistence.delete(mongoCursor.next());
> ```

It's deleting one at a time, correct me If I am wrong. I think you can do what we did in DeleteActivitiesNotAssociatedWithMonitoredServices



_Code quote:_
```Java
 hPersistence.delete(mongoCursor.next());
```

**Review by dhruv-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/45034#-NQOy6Cc41JPmxCtA2id:-NQPtEW5C8mzLbEeg8cn:b377i2c) ([raw file](https://github.com/harness/harness-core/blob/cd86bce4366d3ec3cc1dff174d03e82bcc9e50f7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java#L125)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

It's deleting one at a time, correct me If I am wrong. I think you can do what we did in DeleteActivitiesNotAssociatedWithMonitoredServices
</blockquote></details>

changed to use the $in operator in the delete query

**Review by n00bitax — APPROVED** [review]

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034)* status: 1 file(s) to review. 1 change requests. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutorTest.java` line 326 at r2](https://reviewable.io/reviews/harness/harness-core/45034#-NQTx2_GCwGQuQeLzGOF:-NQTx2_GCwGQuQeLzGOG:bfbgrhb) ([raw file](https://github.com/harness/harness-core/blob/96cd8486146f84c9397cdf820914a342c67dbdeb/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutorTest.java#L326)):*
> ```Java
>     Query<LogAnalysisResult> query = hPersistence.createQuery(LogAnalysisResult.class)
>                                          .filter(LogAnalysisResultKeys.verificationTaskId, verificationTaskId);
>     assertThat(query.count()).isEqualTo(numberOfRecords);
> ```

Can you also assist on that the number of times delete is called by mocking Hpersistence, so that we know it is deleted in 10 times



_Code quote:_
```Java
assertThat(query.count()).isEqualTo(numberOfRecords);
```

**Review by naveen-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034)* status: 1 file(s) to review. 2 change requests. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java` line 133 at r2](https://reviewable.io/reviews/harness/harness-core/45034#-NQU9E4yAAPoAs6pGueY:-NQU9E4yAAPoAs6pGueZ:blazz0m) ([raw file](https://github.com/harness/harness-core/blob/96cd8486146f84c9397cdf820914a342c67dbdeb/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java#L133)):*
> ```Java
>       Query<? extends PersistentEntity> queryToFindRecordsToBeDeleted =
>           hPersistence.createQuery(entity).field(UuidAware.UUID_KEY).in(recordIdsTobeDeleted);
>       hPersistence.delete(queryToFindRecordsToBeDeleted);
> ```

Can we use `findAndDelete` instead, and update the numberOfRecordsDeleted based on the returned documents ?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java` line 134 at r2](https://reviewable.io/reviews/harness/harness-core/45034#-NQU8Mj233FTNAanxPjV:-NQU8Mj233FTNAanxPjW:bdtv4on) ([raw file](https://github.com/harness/harness-core/blob/96cd8486146f84c9397cdf820914a342c67dbdeb/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java#L134)):*
> ```Java
>           hPersistence.createQuery(entity).field(UuidAware.UUID_KEY).in(recordIdsTobeDeleted);
>       hPersistence.delete(queryToFindRecordsToBeDeleted);
>       log.info("Deleted {} records of entity {} for the verificationTaskId {}", numberOfRecordsDeleted,
> ```

Looks like `verificationTaskId` is passed in this function just for the sake of the log, you can add the log in the `cleanUpDataForSingleEntity` instead 
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutorTest.java` line 319 at r2](https://reviewable.io/reviews/harness/harness-core/45034#-NQUABWz94x5SRsOD6Jf:-NQUABWz94x5SRsOD6Jg:b-mljdoc) ([raw file](https://github.com/harness/harness-core/blob/96cd8486146f84c9397cdf820914a342c67dbdeb/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutorTest.java#L319)):*
> ```Java
>   @Category(UnitTests.class)
>   public void testExecute_cleanupLogAnalysisResultRecords() {
>     int numberOfRecords = new Random().nextInt(999) + 1;
> ```

You should add test cases for other entities as well, it can be randomized as well. 
Also add testcases for those entities which are not supposed to be deleted

**Review by dhruv-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034)* status: 1 file(s) to review. 2 change requests. 4. unresolved discussions. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java` line 133 at r2](https://reviewable.io/reviews/harness/harness-core/45034#-NQU9E4yAAPoAs6pGueY:-NQUGNTT5nvtSmv-1Ahm:b-lvedi) ([raw file](https://github.com/harness/harness-core/blob/96cd8486146f84c9397cdf820914a342c67dbdeb/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java#L133)):*
<details><summary><i>Previously, naveen-harness (Naveen Shukla) wrote…</i></summary><blockquote>

Can we use `findAndDelete` instead, and update the numberOfRecordsDeleted based on the returned documents ?
</blockquote></details>

Are there are performance improvements we can get in using findAndDelete, as it will only delete 1 record at a time, we will have to iterate.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java` line 134 at r2](https://reviewable.io/reviews/harness/harness-core/45034#-NQU8Mj233FTNAanxPjV:-NQUGM6L9r_IThte7MHK:b32w0x) ([raw file](https://github.com/harness/harness-core/blob/96cd8486146f84c9397cdf820914a342c67dbdeb/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java#L134)):*
<details><summary><i>Previously, naveen-harness (Naveen Shukla) wrote…</i></summary><blockquote>

Looks like `verificationTaskId` is passed in this function just for the sake of the log, you can add the log in the `cleanUpDataForSingleEntity` instead 
</blockquote></details>

OK
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutorTest.java` line 319 at r2](https://reviewable.io/reviews/harness/harness-core/45034#-NQUABWz94x5SRsOD6Jf:-NQUGcek4Y9mgqxEBu_P:b41jn4l) ([raw file](https://github.com/harness/harness-core/blob/96cd8486146f84c9397cdf820914a342c67dbdeb/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutorTest.java#L319)):*
<details><summary><i>Previously, naveen-harness (Naveen Shukla) wrote…</i></summary><blockquote>

You should add test cases for other entities as well, it can be randomized as well. 
Also add testcases for those entities which are not supposed to be deleted
</blockquote></details>

I thought about adding test cases for other entities. There are already UTs which ensure any entity with a verificationTaskId is part of the list which is used to delete them. We can test the other entities to be deleted either by separate UTs or by traversing the same list and creating records for all the entities. This cant be randomised since we need to explicitly create the instances which will be stored in the db before being deleted. 
But what would be the objective of the test. We have already verified that 
1. entities to be deleted are part of the list
2. a single entity from the list is getting deleted without mentioning which entity.

For the entities which are not to be deleted, added a similar test
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutorTest.java` line 326 at r2](https://reviewable.io/reviews/harness/harness-core/45034#-NQTx2_GCwGQuQeLzGOF:-NQULtGW77bd5-sd-oBA:b-ahyfbh) ([raw file](https://github.com/harness/harness-core/blob/96cd8486146f84c9397cdf820914a342c67dbdeb/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutorTest.java#L326)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

Can you also assist on that the number of times delete is called by mocking Hpersistence, so that we know it is deleted in 10 times
</blockquote></details>

I dont think we should assert on that since its an implementation detail, not a functionality. In future if a more powerful API is there to delete the records in bulk, we can switch to that but the functionality will still remain the same, ie deleting all the records with this id

**Review by naveen-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034)* status: 2 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java` line 133 at r2](https://reviewable.io/reviews/harness/harness-core/45034#-NQU9E4yAAPoAs6pGueY:-NQUO-ZJ-p9u5p1S8TOA:b-mwtmsd) ([raw file](https://github.com/harness/harness-core/blob/96cd8486146f84c9397cdf820914a342c67dbdeb/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java#L133)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Are there are performance improvements we can get in using findAndDelete, as it will only delete 1 record at a time, we will have to iterate.
</blockquote></details>

Not sure about performance improvement, you've set the value of numberOfRecordsDeleted before deleting the actual entity which doesn't seem like a good practice, it might cause a bug if actual delete entity fails, numberOfRecordsDeleted should come from db itself in my opinion.



_Code quote:_
```Java
numberOfRecordsDeleted
```

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034)* status: 2 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutorTest.java` line 326 at r2](https://reviewable.io/reviews/harness/harness-core/45034#-NQTx2_GCwGQuQeLzGOF:-NQUOrL7DkQe0e4Bh410:b-bfnx10) ([raw file](https://github.com/harness/harness-core/blob/96cd8486146f84c9397cdf820914a342c67dbdeb/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutorTest.java#L326)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

I dont think we should assert on that since its an implementation detail, not a functionality. In future if a more powerful API is there to delete the records in bulk, we can switch to that but the functionality will still remain the same, ie deleting all the records with this id
</blockquote></details>

We can assert that it's called less than or equal to 10 times if that's the case.

**Review by dhruv-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034)* status: 2 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutorTest.java` line 326 at r2](https://reviewable.io/reviews/harness/harness-core/45034#-NQTx2_GCwGQuQeLzGOF:-NQURCTC-dqEeiQlfyjU:b-f8kude) ([raw file](https://github.com/harness/harness-core/blob/96cd8486146f84c9397cdf820914a342c67dbdeb/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutorTest.java#L326)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

We can assert that it's called less than or equal to 10 times if that's the case. 
</blockquote></details>

The underlying issue is the same. We want to test the functionality, not the implementation.

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034)* status: 2 change requests. 2. unresolved discussions.

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034)* status: 3 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java` line 133 at r2](https://reviewable.io/reviews/harness/harness-core/45034#-NQU9E4yAAPoAs6pGueY:-NQUS30o6HsV0-NrEz-_:b-wiop12) ([raw file](https://github.com/harness/harness-core/blob/96cd8486146f84c9397cdf820914a342c67dbdeb/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java#L133)):*
<details><summary><i>Previously, naveen-harness (Naveen Shukla) wrote…</i></summary><blockquote>

Not sure about performance improvement, you've set the value of numberOfRecordsDeleted before deleting the actual entity which doesn't seem like a good practice, it might cause a bug if actual delete entity fails, numberOfRecordsDeleted should come from db itself in my opinion.
</blockquote></details>

We shouldnt do one by one delete. It will put more pressure on. the server. Use hPersistence.getDatastore(entity).delete(). to get write result back and get the count. of deleted, and continue to delete till it deleted count is < RECORDS_TO_BE_DELETED_IN_SINGLE_BATCH.

**Review by naveen-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034)* status: 2 change requests. 2. unresolved discussions.

**Review by dhruv-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034)* status: 2 change requests. 2. unresolved discussions. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java` line 133 at r2](https://reviewable.io/reviews/harness/harness-core/45034#-NQU9E4yAAPoAs6pGueY:-NQUw_XY9SbpCadlqqQ6:b-e4tt0e) ([raw file](https://github.com/harness/harness-core/blob/96cd8486146f84c9397cdf820914a342c67dbdeb/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java#L133)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

We shouldnt do one by one delete. It will put more pressure on. the server. Use hPersistence.getDatastore(entity).delete(). to get write result back and get the count. of deleted, and continue to delete till it deleted count is < RECORDS_TO_BE_DELETED_IN_SINGLE_BATCH.
</blockquote></details>

As discussed offline, we are not deleting 1 by 1. Also there is no way to delete a limited number of records without reading them first.

the numberOfRecords deleted is not being used to actually delete the records, it is being used for logging. If the delete fails, I think the entire block should fail and the log statement will also not be logged. To actually delete the records, we are relying solely on the db query to fetch the next n number of records. If somehow the delete fails in the db but doesnt throw any exception, we will have a double log entry but the subsequent iterations will still delete the records.

Added projection to reduce the amount of data we are reading before deleting.
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutorTest.java` line 326 at r2](https://reviewable.io/reviews/harness/harness-core/45034#-NQTx2_GCwGQuQeLzGOF:-NQUx8Jh58eW3GKAs-g9:b3rpjgm) ([raw file](https://github.com/harness/harness-core/blob/96cd8486146f84c9397cdf820914a342c67dbdeb/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutorTest.java#L326)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

The underlying issue is the same. We want to test the functionality, not the implementation.
</blockquote></details>

Had a discussion in the team. Adding these assertions since we are enforcing db implementation.

**Review by naveen-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034#-:-NQV3fVmAVxKWSqZFIaQ:bnfp4nl)* status: 2 file(s) to review. 2 change requests. 1. unresolved discussions.

**Review by naveen-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034#-:-NQYTgI79a2vX6KQNJ5K:bnfp4nl)* status: 2 file(s) to review. 2 change requests. 1. unresolved discussions.

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034)* status: 1 change requests. 1. unresolved discussions.

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034#-:-NQcneq98KI4Tai8ogfX:bnfp4nl)* status: 1. unresolved discussions.

**Review by Varsha-lalwani — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45034)* status: :shipit: complete! ✓

**Pull request merged**
