### PR TITLE
fix: [DEL-4787]: added logging for deleteDirectoryMethod and fix manifestCollection for helm v2

### PR DESCRIPTION
**Pull request by achyuth-harness**
## Describe your changes

We have made the fix in above pr to not delete anything if the cache directory is empty, which is the case for helm v2. We have also ensured that we don't add repo flags for helm v2 as it is not supported

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37172)

### CODE REVIEW

**Review by prabu-kr — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37172)* status: :shipit: complete! ✓

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37172)

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37172)* status: :shipit: complete! ✓

___
*[`980-commons/src/main/java/io/harness/filesystem/FileIo.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/37172#-NBGUUps2_5Ea3FI7siA:-NBGUUpt4CpI-QRhyz2b:bdlnwbg) ([raw file](https://github.com/harness/harness-core/blob/1eb0ed97f9cb0561c65b56cfb4171da86310611a/980-commons/src/main/java/io/harness/filesystem/FileIo.java#L119)):*
> ```Java
>     }
> 
>     log.info("Deleting directory at path: " + directoryPath);
> ```

Let's put log at deleteQuietlyWithErrorLog as well.

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37172)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 

___
*[`980-commons/src/main/java/io/harness/filesystem/FileIo.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/37172#-NBGUUps2_5Ea3FI7siA:-NBGVRgPBAMkXA7wAYwh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1eb0ed97f9cb0561c65b56cfb4171da86310611a/980-commons/src/main/java/io/harness/filesystem/FileIo.java#L119)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Let's put log at deleteQuietlyWithErrorLog as well.
</blockquote></details>

Done.

**Review by prabu-kr — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37172)* status: 1 change requests. 1. unresolved discussions.

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37172)* status: 1 change requests. 1. unresolved discussions. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java` line 648 at r2](https://reviewable.io/reviews/harness/harness-core/37172#-NBGZ18q5vjJVLcUhpxu:-NBGZ18q5vjJVLcUhpxv:b7uezrp) ([raw file](https://github.com/harness/harness-core/blob/a8462822f0714c4495b9489e2dc2b789018798c0/930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L648)):*
> ```Java
>   private void deleteQuietlyWithErrorLog(String tempDir) {
>     try {
>       log.info("Deleting directory at path(deleteQuietlyWithErrorLog) " + tempDir);
> ```

you can dump stack trace here.



_Code quote:_
```Java
);
```

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37172)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java` line 648 at r2](https://reviewable.io/reviews/harness/harness-core/37172#-NBGZ18q5vjJVLcUhpxu:-NBHX0xc-05s9JhbrISz:b-lpqz2u) ([raw file](https://github.com/harness/harness-core/blob/a8462822f0714c4495b9489e2dc2b789018798c0/930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L648)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

you can dump stack trace here.
</blockquote></details>

Done. (As part of another PR to test out)

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37172)* status: 4 file(s) to review. 1 change requests. 

___
*[`980-commons/src/main/java/io/harness/filesystem/FileIo.java` line 115 at r4](https://reviewable.io/reviews/harness/harness-core/37172#-NBHX_jJ73Wcjz5qzK_P:-NBHX_jJ73Wcjz5qzK_Q:bxjh8cc) ([raw file](https://github.com/harness/harness-core/blob/1703921264e1a873a60506ba5306c392077749d4/980-commons/src/main/java/io/harness/filesystem/FileIo.java#L115)):*
> ```Java
> 
>   public static void deleteDirectoryAndItsContentIfExists(final String directoryPath) throws IOException {
>     if (!Files.exists(Paths.get(directoryPath)) || isEmpty(directoryPath)) {
> ```

Flip the condition
 isEmpty(directoryPath) || !Files.exists(Paths.get(directoryPath))



_Code quote:_
```Java
!Files.exists(Paths.get(directoryPath)) || isEmpty(directoryPath)
```

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37172)* status: 4 file(s) to review. 1 change requests. 

___
*[`980-commons/src/main/java/io/harness/filesystem/FileIo.java` line 115 at r4](https://reviewable.io/reviews/harness/harness-core/37172#-NBHX_jJ73Wcjz5qzK_P:-NBHYxqq-RASGYpWmvRp:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/1703921264e1a873a60506ba5306c392077749d4/980-commons/src/main/java/io/harness/filesystem/FileIo.java#L115)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Flip the condition
 isEmpty(directoryPath) || !Files.exists(Paths.get(directoryPath))
</blockquote></details>

Done

**Review by prabu-kr — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37172)* status: :shipit: complete! ✓

**Review by prabu-kr — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37172)* status: :shipit: complete! ✓

**Comment by prabu-kr** [comment]
trigger codebasehashcheck

**Comment by prabu-kr** [comment]
trigger codebasehash

**Review by Vbhatia20 — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 3 files at r4, 1 of 1 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37172)* status: :shipit: complete! ✓

**Pull request merged**
