### PR TITLE
[feat]: [PL-21856]: community edition user deletion

### PR DESCRIPTION
**Pull request by karansiwach360**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30678)

### CODE REVIEW

**Comment by karansiwach360** [comment]
trigger messagecheck

**Comment by karansiwach360** [comment]
trigger messagecheck

**Comment by karansiwach360** [comment]
trigger messagecheck

**Review by reetika04 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30678#-:-Mw0cyQf4Ds8BwNCHVor:bnfp4nl)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 5 of 8 files at r2, 1 of 2 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30678)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 5 of 8 files at r2, 1 of 2 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30678)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/NGAggregateModule.java, line 43 at r4](https://reviewable.io/reviews/harness/harness-core/30678#-Mw5T07_29p2KHR352yp:-Mw5T07_29p2KHR352yq:b-dg56yc) ([raw file](https://github.com/harness/harness-core/blob/d7ce7065c8c8eb7a07037145cb91756e998ae472/120-ng-manager/src/main/java/io/harness/ng/core/NGAggregateModule.java#L43)):*
> ```Java
>         .toInstance(new ManagedExecutorService(Executors.newFixedThreadPool(poolSize)));
>     bind(ExecutorService.class)
>         .annotatedWith(Names.named(THREAD_POOL_NAME))
> ```

Which  is this thread pool that we have removed?

**Review by karansiwach360 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30678)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/NGAggregateModule.java, line 43 at r4](https://reviewable.io/reviews/harness/harness-core/30678#-Mw5T07_29p2KHR352yp:-Mw6a_ytEvvqZ0oUi-UD:b-l728k5) ([raw file](https://github.com/harness/harness-core/blob/d7ce7065c8c8eb7a07037145cb91756e998ae472/120-ng-manager/src/main/java/io/harness/ng/core/NGAggregateModule.java#L43)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

Which  is this thread pool that we have removed?
</blockquote></details>

NgUserServiceImpl. getLastAdminScopes used it, but it does not have any usage now

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30678#-:-MwQBfeq7O7i-HAahmkE:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
