### PR TITLE
feat: [DEL-4377]: Immutable Delegate image expiration

### PR DESCRIPTION
**Pull request by AnupamIO**
https://harness.atlassian.net/browse/DEL-4377

Test cases added to JIRA

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36962)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36962)

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 865 at r2](https://reviewable.io/reviews/harness/harness-core/36962#-NAyyfox8Jg9mgujmprh:-NAyyfox8Jg9mgujmpri:bovir9j) ([raw file](https://github.com/harness/harness-core/blob/e10b755eec0e80585d615d1d19cbbe7c640f16fd/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L865)):*
> ```Java
>               .groupName(entry.getKey())
>               .upgraderLastUpdated(delegateGroupMap.getOrDefault(entry.getKey(), 0L))
>               .immutable(entry.getValue().get(0).isImmutable())
> ```

don't like this get(0). why do we need to do this?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2730 at r2](https://reviewable.io/reviews/harness/harness-core/36962#-NAyyxzTCxAsINDc293C:-NAyyxzTCxAsINDc293D:bd7bv0y) ([raw file](https://github.com/harness/harness-core/blob/e10b755eec0e80585d615d1d19cbbe7c640f16fd/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2730)):*
> ```Java
>       calendar.setTime(sdf.parse(version));
>     } catch (ParseException e) {
>       log.error("Unable to parse version {} for delegateId {}", version, delegateId);
> ```

we should log the exception as well.

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36962)* status: 0 of 1 approvals obtained.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36962)* status: 3 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 865 at r2](https://reviewable.io/reviews/harness/harness-core/36962#-NAyyfox8Jg9mgujmprh:-NB92zgW7TGB48qRXVsD:bsq574t) ([raw file](https://github.com/harness/harness-core/blob/e10b755eec0e80585d615d1d19cbbe7c640f16fd/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L865)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

don't like this get(0). why do we need to do this?
</blockquote></details>

This is a field at DelegateScalingGroup level which will help UI to check type of delegate (mutable/immutable). Immutable field is currently part of delegate collection hence we would need to fetch using get(). 
Another point can be why not to have immutable field as part of delegateGroup collection: I think that's not a good way because for cg mutable delegate we will not have delegateGroup entry.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2730 at r2](https://reviewable.io/reviews/harness/harness-core/36962#-NAyyxzTCxAsINDc293C:-NB92y7T49smRwBztsTu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e10b755eec0e80585d615d1d19cbbe7c640f16fd/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2730)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should log the exception as well. 
</blockquote></details>

Done.

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36962)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 865 at r2](https://reviewable.io/reviews/harness/harness-core/36962#-NAyyfox8Jg9mgujmprh:-NBBJ95IBsGIrr-kvUAQ:b-fzim7s) ([raw file](https://github.com/harness/harness-core/blob/e10b755eec0e80585d615d1d19cbbe7c640f16fd/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L865)):*
> ch will help UI to check type of delegate (mutable/immutable). I
For better code readability, you can declare a boolean flag before this statement:
final boolean isImmutable = IsNotEmpty(delegateList) ?  delegateList.get(0).IsImmutable() : false;
// use the boolean flag later.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1008 at r3](https://reviewable.io/reviews/harness/harness-core/36962#-NBBJiD8-GyG1cVd2Xuk:-NBBJiD8-GyG1cVd2Xul:b6v37pw) ([raw file](https://github.com/harness/harness-core/blob/0cfbb45d4bda363c6b593b0513e6c6cfb90fa985/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1008)):*
> ```Java
>     if (delegate.isImmutable()) {
>       setUnset(updateOperations, DelegateKeys.expirationTime,
>           setDelegateExpirationTime(delegate.getVersion(), delegate.getUuid()));
> ```

How if we set -1 for other delegates ? So later if we want to bring this functionality for mutable delegate too, we can use this with a valid value.



_Code quote:_
```Java
      setUnset(updateOperations, DelegateKeys.expirationTime,
          setDelegateExpirationTime(delegate.getVersion(), delegate.getUuid()));
```

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36962)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 865 at r2](https://reviewable.io/reviews/harness/harness-core/36962#-NAyyfox8Jg9mgujmprh:-NBCtqwV38HPeglJB7pT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e10b755eec0e80585d615d1d19cbbe7c640f16fd/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L865)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

> ch will help UI to check type of delegate (mutable/immutable). I
For better code readability, you can declare a boolean flag before this statement:
final boolean isImmutable = IsNotEmpty(delegateList) ?  delegateList.get(0).IsImmutable() : false;
// use the boolean flag later.
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1008 at r3](https://reviewable.io/reviews/harness/harness-core/36962#-NBBJiD8-GyG1cVd2Xuk:-NBCtvSm7k6dYWVxj9if:bp4oyzw) ([raw file](https://github.com/harness/harness-core/blob/0cfbb45d4bda363c6b593b0513e6c6cfb90fa985/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1008)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

How if we set -1 for other delegates ? So later if we want to bring this functionality for mutable delegate too, we can use this with a valid value.
</blockquote></details>

If we need that later on simple if/else here will do.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36962)* status: 2. unresolved discussions.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36962)* status: :shipit: complete! ✓

**Pull request merged**
