### PR TITLE
feat: [CDS-81004]: Fix CG Socket timeout issue in fetching service in…

### PR DESCRIPTION
**Pull request by mani5h-harness**
…stance license usage

## Describe your changes

**Issue** - We fetch p95 count of service instances to find license usage in CG. To find p95, we have to get all service instance rows for the account and sort them. Due to the volume of data, the query takes 40 seconds for some accounts. 
The timeout is set to 30 seconds resulting in queries timing out. 

**Approaches considered** - 
1. We tried adding an index consisting of accountid, reportedat. Since the issue is the sheer volume of data that needs to be sorted, fetching the data isn't the bottleneck, and this did not optimize the query.
2. Update the `socketTimeout` property on the run before executing the query. After any config update, the Data source needs to be restarted, so this can actually cause more problems.
3. Updating socketTimeout to 60 seconds in config.yml . This is the simplest solution, but this will increase load on DB as this increases the timeout for all queries. 
4. Create a separate `TimescaleDBService` for license usage calculation use case. This creates a separate `Datasource` with its own configuration, without affecting the other queries. This PR implements this approach. 

This PR implements the 4th approach.

**Testing notes** - Random data was generated in local database's instance_stats table. Then a query was selected which was taking 40-50 seconds on average. Then that query was executed by hardcoding it. 
Verified that the query passes and the result is correct.
Verified that only one instance of LicenseUsageTimeScaleDBService is created in multiple injections.
Also verified that the same query fails with timeout when `licenseUsageTimescaleSocketTimeout` is set to 30

**QA validation notes** - This query doesn't fail in QA, so it won't be possible to test this in QA.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54434)

### CODE REVIEW

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54434)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/app/WingsModule.java` line 1506 at r1](https://reviewable.io/reviews/harness/harness-core/54434#-NhCDOBP7OiU5dVqHr9Y:-NhCDOBP7OiU5dVqHr9Z:b-hqobat) ([raw file](https://github.com/harness/harness-core/blob/05b23dff61ac5e70240b600b6654cd774057c773/400-rest/src/main/java/software/wings/app/WingsModule.java#L1506)):*
> ```Java
>           public TimeScaleDBConfig get() {
>             return timeScaleDBConfig.toBuilder()
>                 .socketTimeout(configuration.getLicenseUsageTimescaleSocketTimeout())
> ```

What if configuration.getLicenseUsageTimescaleSocketTimeout() is not provided? 
What if timeScaleDBConfig is null?
toBuilder() will keep other already set properties?

**Comment by mani5h-harness** [comment]
*[`400-rest/src/main/java/software/wings/app/WingsModule.java` line 1506 at r1](https://reviewable.io/reviews/harness/harness-core/54434#-NhCDOBP7OiU5dVqHr9Y:-NhCWuIIAuUmie_oPv7z:byyhqiu) ([raw file](https://github.com/harness/harness-core/blob/05b23dff61ac5e70240b600b6654cd774057c773/400-rest/src/main/java/software/wings/app/WingsModule.java#L1506)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

What if configuration.getLicenseUsageTimescaleSocketTimeout() is not provided? 
What if timeScaleDBConfig is null?
toBuilder() will keep other already set properties?
</blockquote></details>

If licenseUsageTimescaleSocketTimeout is not provided, its value will be 0. which would mean timing out due to socket timeout is disabled. 
Should we have a default value here?

timeScaleDBConfig should not be null as we bind it above on 1493. If config.getTimeScaleDBConfig is null, then we create a new TimeScaleConfigDB above

Yes, toBuilder creates a shallow copy of the object.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54434)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/app/WingsModule.java` line 1506 at r1](https://reviewable.io/reviews/harness/harness-core/54434#-NhCDOBP7OiU5dVqHr9Y:-NhCw9_W74onHCTX97-M:btmqzup) ([raw file](https://github.com/harness/harness-core/blob/05b23dff61ac5e70240b600b6654cd774057c773/400-rest/src/main/java/software/wings/app/WingsModule.java#L1506)):*
<details><summary><i>Previously, mani5h-harness wrote…</i></summary><blockquote>

If licenseUsageTimescaleSocketTimeout is not provided, its value will be 0. which would mean timing out due to socket timeout is disabled. 
Should we have a default value here?

timeScaleDBConfig should not be null as we bind it above on 1493. If config.getTimeScaleDBConfig is null, then we create a new TimeScaleConfigDB above

Yes, toBuilder creates a shallow copy of the object.
</blockquote></details>

Should we have a default value here? >> Yes, we should have the default value set to 60 seconds.

**Comment by mani5h-harness** [comment]
trigger uts, commonchecks

**Comment by mani5h-harness** [comment]
*[`400-rest/src/main/java/software/wings/app/WingsModule.java` line 1506 at r1](https://reviewable.io/reviews/harness/harness-core/54434#-NhCDOBP7OiU5dVqHr9Y:-NhD8x5B0lEjXFyB6MYM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/05b23dff61ac5e70240b600b6654cd774057c773/400-rest/src/main/java/software/wings/app/WingsModule.java#L1506)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Should we have a default value here? >> Yes, we should have the default value set to 60 seconds.
</blockquote></details>

Done.

**Comment by mani5h-harness** [comment]
trigger messagecheck

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54434)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/app/WingsModule.java` line 1508 at r2](https://reviewable.io/reviews/harness/harness-core/54434#-NhDBRIu9maUjc2oN23q:-NhDBRIu9maUjc2oN23r:b-sdaaft) ([raw file](https://github.com/harness/harness-core/blob/fabdb54665d0ed627789316c9d52661a2a383cf1/400-rest/src/main/java/software/wings/app/WingsModule.java#L1508)):*
> ```Java
>                 .socketTimeout(configuration.getLicenseUsageTimescaleSocketTimeout() != 0
>                         ? configuration.getLicenseUsageTimescaleSocketTimeout()
>                         : 60)
> ```

60 should be constant.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54434#-:-NhDLlP98PI_VFGtHER1:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by mani5h-harness** [comment]
trigger uts

**Comment by mani5h-harness** [comment]
trigger ut7

**Review by piyush-bhuwalka — APPROVED** [review]

**Comment by mani5h-harness** [comment]
trigger uts

**Comment by mani5h-harness** [comment]
trigger ut2

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54434#-:-NhRWnZADPPE-fC4suc0:bnfp4nl)* status: 5 file(s) to review.

**Comment by mani5h-harness** [comment]
trigger review

**Pull request merged**
