### PR TITLE
feat: [PL-39825]: revert - Added support for project and organization

### PR DESCRIPTION
**Pull request by meenakshi-harness**
Reverts harness/harness-core#53700
1. Added Project and ORG and resource in resource group
2. Remove validation that org and project can be added as scope at same scope

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54103)

### CODE REVIEW

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by Jimit09Gandhi** [comment]
trigger uts

**Review by ankit-harness — APPROVED** [review]

**Pull request merged**
