### PR TITLE
feat: [CDS-79278]: Add SecretRuntimeUsageEventProducer

### PR DESCRIPTION
**Pull request by mani5h-harness**
## Describe your changes
Add SecretRuntimeUsageService which is to be called from all the swimlanes to publish their runtime usage of secrets to redis.

The swimlanes will need to provide the following info for secret runtime usage. 
- secretId, projectId, orgId, accountId either through SecretDTOV2 or secretIdentifierRef.
- referredByEntity
- entitiyUsageDetailProto 

EntitiyUsageDetail has usageType (a static string from 970-ng-commons : EventUsageTypes), and usageData (an abstract class which can be extended to provide additional runtime usage data)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53100)

### CODE REVIEW

**Review by abosii-harness — COMMENTED** [review]
Are we going to have some service or anything that will ease the life? This producer is too raw and will end up in a lot of boilerplate if everyone are going to use it directly

**Comment by mani5h-harness** [comment]
> Are we going to have some service or anything that will ease the life? This producer is too raw and will end up in a lot of boilerplate if everyone are going to use it directly

Created a service SecretRuntimeUsageService. Although the referredByEntity, entitiyUsageDetailProto and secretInfo is the minimum that the swimlanes will need to provide

**Review by ivan-83 — COMMENTED** [review]
LGTM with minor comments. 

> Reviewed 1 of 3 files at r1, 4 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53100#-:-Neu5LHs8RjWAg4TN4DQ:bt1utpg)* status: 7 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/secretusage/SecretRuntimeUsageService.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/53100#-Neu4AYL7nkxiPLYx_ba:-Neu4AYM0da7ZAA6KVYc:buzhqko) ([raw file](https://github.com/harness/harness-core/blob/744f66515db0b86605ef05000db1527ea0911b04/125-cd-nextgen/src/main/java/io/harness/cdng/secretusage/SecretRuntimeUsageService.java#L39)):*
> ```Java
>    */
>   void produceRuntimeUsageForSecretEvent(String accountIdentifier, SecretDTOV2 secretDTOV2,
>       EntityDetailProtoDTO referredByEntity, EntityUsageDetailProto usageDetail);
> ```

@tiwaritejas why do we need both structures, io.harness.ng.core.entityusageactivity.EntityUsageDetail and EntityUsageDetailProto. 
I think should we only expose EntityUsageDetail and do mapping to proto. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/secretusage/SecretRuntimeUsageServiceImpl.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/53100#-Neu0tFDCaj7KeQhCfco:-Neu0tFG2ZY9KGaslIAU:bt10wew) ([raw file](https://github.com/harness/harness-core/blob/744f66515db0b86605ef05000db1527ea0911b04/125-cd-nextgen/src/main/java/io/harness/cdng/secretusage/SecretRuntimeUsageServiceImpl.java#L33)):*
> ```Java
> 
>   @Override
>   public void produceRuntimeUsageForSecretEvent(
> ```

Minor: produceRuntimeUsageForSecretEvent >> publishSecretRuntimeUsageEvent or createSecretRuntimeUsage
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/secretusage/SecretRuntimeUsageServiceImpl.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/53100#-Neu12_KATFi0x2Z3-12:-Neu12_KATFi0x2Z3-13:bt10wew) ([raw file](https://github.com/harness/harness-core/blob/744f66515db0b86605ef05000db1527ea0911b04/125-cd-nextgen/src/main/java/io/harness/cdng/secretusage/SecretRuntimeUsageServiceImpl.java#L43)):*
> ```Java
> 
>   @Override
>   public void produceRuntimeUsageForSecretEvent(String accountIdentifier, SecretDTOV2 secretDTOV2,
> ```

Minor: produceRuntimeUsageForSecretEvent >> publishSecretRuntimeUsageEvent or createSecretRuntimeUsage

**Review by ivan-83 — APPROVED** [review]

**Review by piyush-bhuwalka — APPROVED** [review]

**Comment by mani5h-harness** [comment]
trigger review

**Comment by mani5h-harness** [comment]
trigger ut3 ut6

**Review by abosii-harness — DISMISSED** [review]

**Comment by mani5h-harness** [comment]
trigger uts

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53100#-:-Nex_-ffCyK9ga0EpN5p:bnfp4nl)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by mani5h-harness** [comment]
trigger uts

**Comment by mani5h-harness** [comment]
trigger uts

**Review by piyush-bhuwalka — DISMISSED** [review]

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/events/SecretRuntimeUsageEventProducer.java` line 26 at r6](https://reviewable.io/reviews/harness/harness-core/53100#-Nf9ueIXAiXZhSQM4Yzi:-Nf9ueIXAiXZhSQM4Yzj:b-l2yy5j) ([raw file](https://github.com/harness/harness-core/blob/ec76591c4f1abe27424902b3dc81cc008845a5e2/125-cd-nextgen/src/main/java/io/harness/cdng/events/SecretRuntimeUsageEventProducer.java#L26)):*
> ```Java
> @OwnedBy(CDP)
> @Slf4j
> public class SecretRuntimeUsageEventProducer {
> ```

Can we move all of these to a common package? Maybe ng-common-utlities.
We might need to duplicate the same for pipeline-service, having this in ng-common-utilities would reduce the duplication

**Comment by mani5h-harness** [comment]
> _[`125-cd-nextgen/src/main/java/io/harness/cdng/events/SecretRuntimeUsageEventProducer.java` line 26 at r6](https://reviewable.io/reviews/harness/harness-core/53100#-Nf9ueIXAiXZhSQM4Yzi:-Nf9ueIXAiXZhSQM4Yzj:b-l2yy5j) ([raw file](https://github.com/harness/harness-core/blob/ec76591c4f1abe27424902b3dc81cc008845a5e2/125-cd-nextgen/src/main/java/io/harness/cdng/events/SecretRuntimeUsageEventProducer.java#L26)):_
> 
> > ```java
> > @OwnedBy(CDP)
> > @Slf4j
> > public class SecretRuntimeUsageEventProducer {
> > ```
> 
> Can we move all of these to a common package? Maybe ng-common-utlities. We might need to duplicate the same for pipeline-service, having this in ng-common-utilities would reduce the duplication

Moved to ng-common-utilities

**Comment by mani5h-harness** [comment]
trigger recency

**Comment by mani5h-harness** [comment]
trigger uts

**Comment by mani5h-harness** [comment]
trigger uts

**Comment by mani5h-harness** [comment]
trigger uts

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 6 of 7 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53100)* status: 9 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by mani5h-harness** [comment]
trigger uts

**Comment by mani5h-harness** [comment]
trigger ut5

**Comment by mani5h-harness** [comment]
trigger ut5

**Review by piyush-bhuwalka — APPROVED** [review]

**Comment by mani5h-harness** [comment]
trigger review

**Pull request merged**
