### PR TITLE
[feat]:[CDS-71092]: adding templates ref by pipeline telemetry

### PR DESCRIPTION
**Pull request by RajBaviskar**
## Describe your changes

- adding templates ref by pipeline telemetry

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49853)

### CODE REVIEW

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by RajBaviskar** [comment]
trigger messagecheck

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 94 at r4](https://reviewable.io/reviews/harness/harness-core/49853#-NZ4n2gf7QZx9vLLuocb:-NZ4n2ggBF9uEijEoYEv:bl6zprp) ([raw file](https://github.com/harness/harness-core/blob/c01cbeb407d892a2d671f32574533594b3832019/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L94)):*
> ```Java
> 
>   private final TelemetryReporter telemetryReporter;
>   private final ExecutorService executorService;
> ```

How are we injecting this?
This should be named in my opinion.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49853)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by RajBaviskar** [comment]
trigger uts

**Review by archit-harness — COMMENTED** [review]
> Reviewed 7 of 10 files at r1, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49853)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 94 at r4](https://reviewable.io/reviews/harness/harness-core/49853#-NZ4n2gf7QZx9vLLuocb:-NZ4vVw0DlsJHRd821cZ:b32v57) ([raw file](https://github.com/harness/harness-core/blob/c01cbeb407d892a2d671f32574533594b3832019/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L94)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

How are we injecting this?
This should be named in my opinion.
</blockquote></details>

+1

**Review by RajBaviskar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49853)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 94 at r4](https://reviewable.io/reviews/harness/harness-core/49853#-NZ4n2gf7QZx9vLLuocb:-NZ560YMDZ4RobhIe_Gb:b9k5jvv) ([raw file](https://github.com/harness/harness-core/blob/c01cbeb407d892a2d671f32574533594b3832019/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L94)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

changed.

**Review by RajBaviskar — COMMENTED** [review]
> Reviewed 7 of 10 files at r1, 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49853)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49853)* status: 1 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 94 at r5](https://reviewable.io/reviews/harness/harness-core/49853#-NZ596E02jeRbNEs0ZtE:-NZ596E02jeRbNEs0ZtF:b-5tt6cr) ([raw file](https://github.com/harness/harness-core/blob/d0a62ba8e0539053b8895f62965e01ce5e1d3ffd/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L94)):*
> ```Java
> 
>   @Inject private final TelemetryReporter telemetryReporter;
>   @Inject private final ExecutorService executorService;
> ```

What i meant is using @Named, inject is not required as we have - @AllArgsConstructor(access = AccessLevel.PUBLIC, onConstructor = @__({ @Inject }))

**Comment by RajBaviskar** [comment]
trigger uts

**Review by RajBaviskar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49853)* status: 1 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 94 at r5](https://reviewable.io/reviews/harness/harness-core/49853#-NZ596E02jeRbNEs0ZtE:-NZ5FJKMBLikHIyyKTpW:bgjsyrb) ([raw file](https://github.com/harness/harness-core/blob/d0a62ba8e0539053b8895f62965e01ce5e1d3ffd/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L94)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

What i meant is using @Named, inject is not required as we have - @AllArgsConstructor(access = AccessLevel.PUBLIC, onConstructor = @__({ @Inject }))
</blockquote></details>

added.

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by RajBaviskar** [comment]
trigger ut0

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by RajBaviskar** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 7 files at r8, 1 of 2 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49853)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 92 at r13](https://reviewable.io/reviews/harness/harness-core/49853#-NZj3Jo2-X3PxK6EedPL:-NZj3Jo2-X3PxK6EedPM:bz032j4) ([raw file](https://github.com/harness/harness-core/blob/8cf64aa6c36604ca386c69c6a1693e822344086a/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L92)):*
> ```Java
> 
>   private final TelemetryReporter telemetryReporter;
>   private final Executor executor;
> ```

nit: Please change it to executorService.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49853)* status: 8 file(s) to review.

**Comment by RajBaviskar** [comment]
trigger review

**Review by RajBaviskar — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49853)* status: 8 file(s) to review.

**Review by utkarshchoubey-harness — APPROVED** [review]

**Pull request merged**
