### PR TITLE
feat: [PIE-3384]: Add search term in the criteria in env group list call

### PR DESCRIPTION
**Pull request by prashantsharma04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32081)

### CODE REVIEW

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32081#-:-MzxvHzxA6B6FLO4zVU3:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by shivamnegi94 — APPROVED** [review]

**Review by shivamnegi94 — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32081)* status: 2 file(s) to review.

**Comment by prashantsharma04** [comment]
trigger license/cla, license, cla

**Comment by prashantsharma04** [comment]
trigger license/cla

**Comment by prashantsharma04** [comment]
trigger license

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32081)* status: 2 file(s) to review.

**Review by brijeshdhakar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32081)* status: 2 file(s) to review.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32081)* status: :shipit: complete! ✓

**Pull request merged**
