### PR TITLE
fix: [CDS-86561]: adds validation for branch name, relevant error message for remote entity update and create

### PR DESCRIPTION
**Pull request by sandeshsalunkhegh**
fix: [CDS-86561]: adds validation for branch name, relevant error message for remote pipeline creation

Issue: branch names with special characters cause certain issues while fetching yaml of the pipeline created for that pipeline.

Changes: validation for branch name added for the remote pipeline creation API.

Testing: Done on local, and added unit tests for the same. Attached screen recording.

https://github.com/harness/harness-core/assets/22246973/346bf3bf-e172-4d47-8340-affb29050c87

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-86561]: https://harness.atlassian.net/browse/CDS-86561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56631)

### CODE REVIEW

**Review by adivishy1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56631)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 171 at r3](https://reviewable.io/reviews/harness/harness-core/56631#-NlafM6h36hMEcQUbMzU:-NlafM6h36hMEcQUbMzV:b8olt1k) ([raw file](https://github.com/harness/harness-core/blob/925ab42c3c2fb3268706a58cfb471f3efe196543/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L171)):*
> ```Java
>   private final AccountClient accountClient;
>   private static final String INVALID_BRANCH_NAME_FORMAT_STRING =
>       "The Branch Name [%s] is Invalid for this pipeline. Please check guidelines for creating branches at respective Git SCM application.";
> ```

we cant be sure that its a pipeline, it can be any remote entity
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 652 at r3](https://reviewable.io/reviews/harness/harness-core/56631#-Nlafi1ME_O4_F8FWfAd:-Nlafi1ME_O4_F8FWfAe:bq0stn8) ([raw file](https://github.com/harness/harness-core/blob/925ab42c3c2fb3268706a58cfb471f3efe196543/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L652)):*
> ```Java
>   }
> 
>   private void validateParameters(String branchName, String filePath) {
> ```

we can probably change the method name to something like validateInputFileParameters or better

**Review by sandeshsalunkhegh — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56631)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 171 at r3](https://reviewable.io/reviews/harness/harness-core/56631#-NlafM6h36hMEcQUbMzU:-NlgNA2CCN5-FP7lN1kt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/925ab42c3c2fb3268706a58cfb471f3efe196543/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L171)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

we cant be sure that its a pipeline, it can be any remote entity
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 652 at r3](https://reviewable.io/reviews/harness/harness-core/56631#-Nlafi1ME_O4_F8FWfAd:-NlgNB4x97_10IzD44wt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/925ab42c3c2fb3268706a58cfb471f3efe196543/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L652)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

we can probably change the method name to something like validateInputFileParameters or better
</blockquote></details>

Done.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56631)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56631)* status: <span>:shipit:</span> complete! ✓

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by sandeshsalunkhegh** [comment]
trigger ut0, ut5, ut7

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 171 at r4](https://reviewable.io/reviews/harness/harness-core/56631#-NljjqfSDX7TaFwvgbjh:-NljjqfSDX7TaFwvgbji:b-erjo8h) ([raw file](https://github.com/harness/harness-core/blob/5e859d0fad712ba0ba07a2435862201015127467/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L171)):*
> ```Java
>   private final AccountClient accountClient;
>   private static final String INVALID_BRANCH_NAME_FORMAT_STRING =
>       "The Branch Name [%s] is Invalid. Please check guidelines for creating branches at respective Git SCM application.";
> ```

This message doesn't look user friendly at all. What guidelines should I check as a user?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 473 at r4](https://reviewable.io/reviews/harness/harness-core/56631#-Nljjv_d4kSeCDwzBYOE:-Nljjv_d4kSeCDwzBYOF:bmt5dkd) ([raw file](https://github.com/harness/harness-core/blob/5e859d0fad712ba0ba07a2435862201015127467/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L473)):*
> ```Java
>     try {
>       Scope scope = ScopeIdentifierMapper.getScopeFromScopeIdentifiers(createFileRequest.getScopeIdentifiers());
>       validateRemoteInputParameters(createFileRequest.getBranchName(), createFileRequest.getFilePath());
> ```

we cannot have any validations in this layer alone. This should be done centrally.

**Pull request merged**
