### PR TITLE
[feat]: [CDS-56494]: migration to add service override v2 related fields

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes
1. migration to add identifier+type for overrides v2
2. Updated upsert flow to add identifier+type in upsert call

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47457)

### CODE REVIEW

**Comment by tchaurasiya** [comment]
trigger uts

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/background/AddServiceOverrideV2RelatedFieldsMigration.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/47457#-NUuto-15WS-bjtEq7dF:-NUuto-15WS-bjtEq7dG:b-lx5fx8) ([raw file](https://github.com/harness/harness-core/blob/8f66a54d2078c98825869f4984b8db5fbec69496/120-ng-manager/src/main/java/io/harness/ng/core/migration/background/AddServiceOverrideV2RelatedFieldsMigration.java#L66)):*
> ```Java
>                       + "Migration failed for override with environmentRef: [%s], serviceRef: [%s], projectId: [%s], orgId: [%s]",
>                   overridesEntity.getEnvironmentRef(), overridesEntity.getServiceRef(),
>                   overridesEntity.getProjectIdentifier(), overridesEntity.getOrgIdentifier()));
> ```

We should log the exception

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java` line 383 at r3](https://reviewable.io/reviews/harness/harness-core/47457#-NUuub8x7W7MHWvsh09M:-NUuub8x7W7MHWvsh09N:bs8o6ti) ([raw file](https://github.com/harness/harness-core/blob/8f66a54d2078c98825869f4984b8db5fbec69496/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java#L383)):*
> ```Java
>     update.set(NGServiceOverridesEntityKeys.lastModifiedAt, System.currentTimeMillis());
>     // for service override v2
>     update.set(NGServiceOverridesEntityKeys.identifier, identifier);
> ```

if identifier is set by the user, will we still override it ?

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/background/AddServiceOverrideV2RelatedFieldsMigration.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/47457#-NUuto-15WS-bjtEq7dF:-NUv1qv40X3YcwNi1dKH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8f66a54d2078c98825869f4984b8db5fbec69496/120-ng-manager/src/main/java/io/harness/ng/core/migration/background/AddServiceOverrideV2RelatedFieldsMigration.java#L66)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We should log the exception
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java` line 383 at r3](https://reviewable.io/reviews/harness/harness-core/47457#-NUuub8x7W7MHWvsh09M:-NUv201M8M3pEuBvC0EY:brxlzej) ([raw file](https://github.com/harness/harness-core/blob/8f66a54d2078c98825869f4984b8db5fbec69496/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java#L383)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

if identifier is set by the user, will we still override it ?
</blockquote></details>

Marked it as @deprecated, only getting used in V1. (no case of override will be possible)

**Comment by tchaurasiya** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47457)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by tchaurasiya** [comment]
trigger review

**Pull request merged**
