### PR TITLE
feat: [PL-39275]: SEND METRICS TO SEGMENT platform changes

### PR DESCRIPTION
**Pull request by sahibaHarness**
## Describe your changes

Send metrics to segment[Amplitude] & Prometheus to monitor Active projects on accounts. This has to be done to monitor stickiness of feature
Pasted Graphic 8
Pasted Graphic 6
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53500)

### CODE REVIEW

**Comment by sahibaHarness** [comment]
trigger uts

**Comment by sahibaHarness** [comment]
trigger uts

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53500)* status: Some of the checks are too old. 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java` line 381 at r1](https://reviewable.io/reviews/harness/harness-core/53500#-NfrJ_BV5u2i9PoCojPQ:-NfrJ_BV5u2i9PoCojPR:b-5vf82r) ([raw file](https://github.com/harness/harness-core/blob/fa8cfa08a3295cc4d5a3d6572cb63890175ab162/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java#L381)):*
> ```Java
>              new ResponseTimeRecorder("Successfully Published metrics to Segment & Prometheus")) {
>       for (String accountIdentifier : accountIds) {
>         int projectCount = projectCounts.containsKey(accountIdentifier) ? projectCounts.get(accountIdentifier) : 0;
> ```

getOrDefault() method can be used
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java` line 382 at r1](https://reviewable.io/reviews/harness/harness-core/53500#-NfrJeMo4FUxBrz1VFUV:-NfrJeMo4FUxBrz1VFUW:b-5vf82r) ([raw file](https://github.com/harness/harness-core/blob/fa8cfa08a3295cc4d5a3d6572cb63890175ab162/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java#L382)):*
> ```Java
>       for (String accountIdentifier : accountIds) {
>         int projectCount = projectCounts.containsKey(accountIdentifier) ? projectCounts.get(accountIdentifier) : 0;
>         int uniqueProjectCount = uniqueProjectCountPerAccountId.containsKey(accountIdenifier)
> ```

getOrDefault() method can be used
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java` line 391 at r1](https://reviewable.io/reviews/harness/harness-core/53500#-NfrJgvu0ccp46UsQ7zA:-NfrJgvu0ccp46UsQ7zB:bpyo5m1) ([raw file](https://github.com/harness/harness-core/blob/fa8cfa08a3295cc4d5a3d6572cb63890175ab162/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java#L391)):*
> ```Java
>   }
> 
>   private void sendSegmentMetricsForActiveProject(String accountIdentifier, int totalProjects, int activeProjects) {
> ```

can be renamed to sendSegmentEventsForActiveProjects()
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java` line 396 at r1](https://reviewable.io/reviews/harness/harness-core/53500#-NfrJzQCCHiTo851UGGU:-NfrJzQD1TJbJM0ubVyO:b-j6p0lm) ([raw file](https://github.com/harness/harness-core/blob/fa8cfa08a3295cc4d5a3d6572cb63890175ab162/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java#L396)):*
> ```Java
>     identifyEventProperties.put("totalProjects", totalProjects);
>     identifyEventProperties.put("activeProjects", activeProjects);
>     float activeProjectPercentage = totalProjects != 0 ? ((activeProjects / totalProjects) * 100) : 0;
> ```

extract this % calc logic in a separate method.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/DistinctProjectsPerAccount.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/53500#-NfrKqGY3BQpUt9Y8EDn:-NfrKqGY3BQpUt9Y8EDo:b-quuiuv) ([raw file](https://github.com/harness/harness-core/blob/fa8cfa08a3295cc4d5a3d6572cb63890175ab162/platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/DistinctProjectsPerAccount.java#L29)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @FieldNameConstants(innerTypeName = "DistinctProjectsPerAccountKeys")
> ```

remove this newline
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/remote/AuditResourceImpl.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/53500#-NfrLIZ-39w3QOvcPkx0:-NfrLIZ0DaTh3hUDeTDr:b-jaihys) ([raw file](https://github.com/harness/harness-core/blob/fa8cfa08a3295cc4d5a3d6572cb63890175ab162/platform-service/modules/audit-service/src/main/java/io/harness/audit/remote/AuditResourceImpl.java#L83)):*
> ```Java
>   @InternalApi
>   public ResponseDTO<Void> publishMetrics(ActiveProjectMetricsDTO activeProjectMetricsDTO) {
>     auditService.computeMetricsForActiveProject(activeProjectMetricsDTO.getAccountIds(),
> ```

why can't you send the whole DTO i.e. ActiveProjectMetricsDTO to auditService

**Comment by sahibaHarness** [comment]
trigger uts

**Review by sahibaHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53500)* status: 15 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java` line 396 at r1](https://reviewable.io/reviews/harness/harness-core/53500#-NfrJzQCCHiTo851UGGU:-NfzMpaI-dKqYjBLbV-j:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/fa8cfa08a3295cc4d5a3d6572cb63890175ab162/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java#L396)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

better name would be getActiveProjectPercentage()
</blockquote></details>

done
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/remote/AuditResourceImpl.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/53500#-NfrLIZ-39w3QOvcPkx0:-NfzMYYXA1IgNKrFBWdX:b-vod3p6) ([raw file](https://github.com/harness/harness-core/blob/fa8cfa08a3295cc4d5a3d6572cb63890175ab162/platform-service/modules/audit-service/src/main/java/io/harness/audit/remote/AuditResourceImpl.java#L83)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

this comment is not addressed
</blockquote></details>

have to call computeMetricsForUniqueLogins as well from same function. Have changed the name of DTO as well to AccountMetricsDTO

**Comment by sahibaHarness** [comment]
trigger uts

**Comment by sahibaHarness** [comment]
trigger uts

**Comment by sahibaHarness** [comment]
trigger uts

**Comment by sahibaHarness** [comment]
trigger ut2,ut7

**Review by kapil-harness — APPROVED** [review]
> Reviewed 6 of 14 files at r1, 6 of 9 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53500)* status: Some of the checks are too old. 15 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 14 files at r1, 6 of 9 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53500)* status: Some of the checks are too old. 1 change requests. 1 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/remote/AuditResource.java` line 102 at r4](https://reviewable.io/reviews/harness/harness-core/53500#-NgMzSkn7NHNa7TOv5en:-NgMzSkn7NHNa7TOv5eo:b-kxb5h7) ([raw file](https://github.com/harness/harness-core/blob/6685168c3c7bab32a76b987e598616caf8ddebf1/platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/remote/AuditResource.java#L102)):*
> ```Java
>   @Path("/publish-metrics")
>   @Hidden
>   @ApiOperation(
> ```

Any new api created should follow spec first approach rather than using openapi annotations. Also should we not have a separate  resource layer for metric related endpoints? e.g. /audit-metric
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/DistinctProjectsPerAccount.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/53500#-NgN1Q_500MjBzdYTHot:-NgN1Q_500MjBzdYTHou:bklf0k6) ([raw file](https://github.com/harness/harness-core/blob/6685168c3c7bab32a76b987e598616caf8ddebf1/platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/DistinctProjectsPerAccount.java#L24)):*
> ```Java
> @OwnedBy(PL)
> @Data
> @Builder
> ```

Do we need both Data and Builder annotation? Would Builder and Getter annotation be sufficient?
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/UniqueLoginsPerAccount.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/53500#-NgN1lG_-Evzeb57K0AL:-NgN1lG_-Evzeb57K0AM:bhhqwuv) ([raw file](https://github.com/harness/harness-core/blob/6685168c3c7bab32a76b987e598616caf8ddebf1/platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/UniqueLoginsPerAccount.java#L24)):*
> ```Java
> @OwnedBy(PL)
> @Data
> @Builder
> ```

Same here, Do we need both Data and Builder annotation?
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/beans/ProjectAuditMetricContext.java` line 17 at r4](https://reviewable.io/reviews/harness/harness-core/53500#-NgN28WN4PjDIXitIo1W:-NgN28WN4PjDIXitIo1X:b-p3oc5b) ([raw file](https://github.com/harness/harness-core/blob/6685168c3c7bab32a76b987e598616caf8ddebf1/platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/beans/ProjectAuditMetricContext.java#L17)):*
> ```Java
> 
> @Data
> @Builder
> ```

Same here. There is a constructor to populate values. Is builder and data required?
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/AuditRepositoryCustomImpl.java` line 112 at r4](https://reviewable.io/reviews/harness/harness-core/53500#-NgN4WrT14oijfEE9GgV:-NgN4WrT14oijfEE9GgW:b-b9lbb7) ([raw file](https://github.com/harness/harness-core/blob/6685168c3c7bab32a76b987e598616caf8ddebf1/platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/AuditRepositoryCustomImpl.java#L112)):*
> ```Java
>     Map<String, Integer> result = new HashMap<>();
> 
>     aggregate(newAggregation(matchStage, groupBy, projectionStage), DistinctProjectsPerAccount.class)
> ```

What is the query performance for this? This looks expensive query.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/AuditRepositoryCustomImpl.java` line 126 at r4](https://reviewable.io/reviews/harness/harness-core/53500#-NgN4x-zCH_hinr-5-K2:-NgN4x-zCH_hinr-5-K3:bke1v6z) ([raw file](https://github.com/harness/harness-core/blob/6685168c3c7bab32a76b987e598616caf8ddebf1/platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/AuditRepositoryCustomImpl.java#L126)):*
> ```Java
> 
>     criteriaList.add(Criteria.where(AuditEventKeys.ACCOUNT_IDENTIFIER_KEY).in(accountIds));
>     criteriaList.add(Criteria.where(AuditEventKeys.action).is(Action.LOGIN));
> ```

Login have other action too i.e. LOGIN2FA, This should also be included
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/AuditRepositoryCustomImpl.java` line 144 at r4](https://reviewable.io/reviews/harness/harness-core/53500#-NgN4sPT1zJN9ftUOt3c:-NgN4sPT1zJN9ftUOt3d:b-r0bilg) ([raw file](https://github.com/harness/harness-core/blob/6685168c3c7bab32a76b987e598616caf8ddebf1/platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/AuditRepositoryCustomImpl.java#L144)):*
> ```Java
>     Map<String, Integer> result = new HashMap<>();
> 
>     aggregate(newAggregation(matchStage, groupBy, projectionStage), UniqueLoginsPerAccount.class)
> ```

Same here. Have we evaluated the query performance?

**Pull request closed without merging**
