### PR TITLE
[feat]: [PL-29626]: Implement Parallel Implementation of user Group s…

### PR DESCRIPTION
**Pull request by shashank-harness**
Implement User Group Sync behind FF PL_LDAP_PARALLEL_GROUP_SYNC in CG LDAP.
This is already hotfixed and tested by customer ZKB as part of this PR https://github.com/harness/harness-core/pull/39184

Signed-off-by: Shashank Singh <shashank.singh@harness.io>

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39884)

### CODE REVIEW

**Comment by shashank-harness** [comment]
trigger ti1

**Comment by shashank-harness** [comment]
trigger tin1

**Review by piyush-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39884)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
:lgtm:

**Review by piyush-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39884)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
trigger ti4

**Comment by shashank-harness** [comment]
trigger ti4

**Comment by AnshuH** [comment]
trigger ti4

**Comment by AnshuH** [comment]
trigger ti4

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39884)* status: :shipit: complete! ✓

**Pull request merged**
