### PR TITLE
feat: [DEL-3664]: Add Management API for mTLS Delegates

### PR DESCRIPTION
**Pull request by johannesHarness**
Add Management API for delegate mTLS functionality - for more details on the mTLS delegate design please refer to the [mTLS Delegate - Design Document](https://harness.atlassian.net/wiki/spaces/~203497205/pages/21043576978/mTLS+Delegate+-+Design+Document)

While we'll expose the API for both CG & NG, there is only one endpoint per account across both (they share the same).
In other words, enabling it in CG will enable it in NG and vice-versa (This was confirmed with Raghu, Pranay and Puneet)

For more details

---
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32274)

### CODE REVIEW

**Comment by jennyjames21** [comment]
*[120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateMtlsEndpointNgResource.java, line 108 at r1](https://reviewable.io/reviews/harness/harness-core/32274#-N-yfBYL9_tmYF3MKkps:-N-yfBYL9_tmYF3MKkpt:b-f9lrv3) ([raw file](https://github.com/harness/harness-core/blob/9640d719715002fa830e2a192052e06449d14c17/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateMtlsEndpointNgResource.java#L108)):*
> ```Java
>   @Timed
>   @ExceptionMetered
>   @NGAccessControlCheck(resourceType = ResourceTypes.ACCOUNT, permission = EDIT_ACCOUNT_PERMISSION)
> ```

EDIT_ACCOUNT_PERMISSION give access to more than harness support users, whoever with permission to edit account.  if that's ok

**Comment by jennyjames21** [comment]
*[120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateMtlsEndpointNgResource.java, line 127 at r1](https://reviewable.io/reviews/harness/harness-core/32274#-N-ygz487eNFzFumq3xe:-N-ygz487eNFzFumq3xf:b-m4tlri) ([raw file](https://github.com/harness/harness-core/blob/9640d719715002fa830e2a192052e06449d14c17/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateMtlsEndpointNgResource.java#L127)):*
> ```Java
>       @NotNull DelegateMtlsEndpointRequest endpointRequest) {
>     try (AutoLogContext ignore1 = new AccountLogContext(accountIdentifier, OVERRIDE_ERROR)) {
>       this.ensureOperationIsExecutedByHarnessSupport();
> ```

i see you have check, so do we need to add permission as NGAccessControlCheck

**Comment by jennyjames21** [comment]
*[270-delegate-service-app/delegate-service-config.yml, line 56 at r1](https://reviewable.io/reviews/harness/harness-core/32274#-N-yhT2w6R1UVQgOPvbW:-N-yhT2w6R1UVQgOPvbX:b-yi6hs7) ([raw file](https://github.com/harness/harness-core/blob/9640d719715002fa830e2a192052e06449d14c17/270-delegate-service-app/delegate-service-config.yml#L56)):*
> ```YAML
> deploymentClusterName: ""
> delegateMtlsSubdomain: "delegate.local.harness.io"
> ```

you can ignore this module(270) as it's was created for DMS

**Comment by jennyjames21** [comment]
*[270-delegate-service-app/container/scripts/replace_configs.sh, line 509 at r1](https://reviewable.io/reviews/harness/harness-core/32274#-N-yhavfBKNFn-xrh9CD:-N-yhavfBKNFn-xrh9CE:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/9640d719715002fa830e2a192052e06449d14c17/270-delegate-service-app/container/scripts/replace_configs.sh#L509)):*
> ```Shell
> if [[ "" != "$DELEGATE_MTLS_SUBDOMAIN" ]]; then
>   yq write -i $CONFIG_FILE delegateMtlsSubdomain "$DELEGATE_MTLS_SUBDOMAIN"
> fi
> ```

same here

**Comment by jennyjames21** [comment]
*[400-rest/src/main/java/io/harness/delegate/resources/DelegateMtlsEndpointResource.java, line 1 at r1](https://reviewable.io/reviews/harness/harness-core/32274#-N-yiFUH0TxiiPEXNOGP:-N-yiFUH0TxiiPEXNOGQ:bgkefub) ([raw file](https://github.com/harness/harness-core/blob/9640d719715002fa830e2a192052e06449d14c17/400-rest/src/main/java/io/harness/delegate/resources/DelegateMtlsEndpointResource.java#L1)):*
> ```Java
> /*
> ```

Should this be under 420-delegate-service

**Comment by jennyjames21** [comment]
*[420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateMtlsEndpointInternalNgResource.java, line 51 at r1](https://reviewable.io/reviews/harness/harness-core/32274#-N-yjjAe-NlMX3xYtVu0:-N-yjjAe-NlMX3xYtVu1:bg9dfdc) ([raw file](https://github.com/harness/harness-core/blob/9640d719715002fa830e2a192052e06449d14c17/420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateMtlsEndpointInternalNgResource.java#L51)):*
> ```Java
> @Produces("application/json")
> @Consumes("application/json")
> @Scope(DELEGATE)
> ```

Not sure this connotation is ever checked or used

**Comment by jennyjames21** [comment]
*[420-delegate-service/src/main/java/io/harness/service/DelegateServiceModule.java, line 48 at r1](https://reviewable.io/reviews/harness/harness-core/32274#-N-ykOeX8gydB0s7L6dq:-N-ykOeX8gydB0s7L6dr:by52q4e) ([raw file](https://github.com/harness/harness-core/blob/9640d719715002fa830e2a192052e06449d14c17/420-delegate-service/src/main/java/io/harness/service/DelegateServiceModule.java#L48)):*
> ```Java
> 
>   public DelegateServiceModule() {
>     this("");
> ```

why empty string?

**Comment by jennyjames21** [comment]
*[420-delegate-service/src/main/java/io/harness/service/impl/DelegateMtlsEndpointServiceImpl.java, line 107 at r1](https://reviewable.io/reviews/harness/harness-core/32274#-N-ylm1T4V0psybke2F7:-N-ylm1T4V0psybke2F8:b-x0uz4a) ([raw file](https://github.com/harness/harness-core/blob/9640d719715002fa830e2a192052e06449d14c17/420-delegate-service/src/main/java/io/harness/service/impl/DelegateMtlsEndpointServiceImpl.java#L107)):*
> ```Java
>     options.upsert(false);
>     options.returnNew(true);
> ```

you can also use that in one line persistence.findAndModify(query, updateOperations, HPersistence.returnNewOptions)

**Review by jennyjames21 — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32274)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by johannesHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32274)* status: 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateMtlsEndpointNgResource.java, line 108 at r1](https://reviewable.io/reviews/harness/harness-core/32274#-N-yfBYL9_tmYF3MKkps:-N-ynlv87EEifs3GHigc:b-c2mcir) ([raw file](https://github.com/harness/harness-core/blob/9640d719715002fa830e2a192052e06449d14c17/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateMtlsEndpointNgResource.java#L108)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

EDIT_ACCOUNT_PERMISSION give access to more than harness support users, whoever with permission to edit account.  if that's ok
</blockquote></details>

As discussed, I'll commented the permission part out and only rely on harness support group check.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateMtlsEndpointNgResource.java, line 127 at r1](https://reviewable.io/reviews/harness/harness-core/32274#-N-ygz487eNFzFumq3xe:-N-yo5WS2uQ_CbsW8_jk:b-c2mcir) ([raw file](https://github.com/harness/harness-core/blob/9640d719715002fa830e2a192052e06449d14c17/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateMtlsEndpointNgResource.java#L127)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

i see you have check, so do we need to add permission as NGAccessControlCheck
</blockquote></details>

As discussed, I'll commented the permission part out and only rely on harness support group check.
___
*[270-delegate-service-app/delegate-service-config.yml, line 56 at r1](https://reviewable.io/reviews/harness/harness-core/32274#-N-yhT2w6R1UVQgOPvbW:-N-yo78dA7d9Apziuo3L:b-z26p95) ([raw file](https://github.com/harness/harness-core/blob/9640d719715002fa830e2a192052e06449d14c17/270-delegate-service-app/delegate-service-config.yml#L56)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

you can ignore this module(270) as it's was created for DMS
</blockquote></details>

I wanted to have it here for consistency sake, so once the DMS work gets continued it doesn't cause any unnecessary problems.
___
*[400-rest/src/main/java/io/harness/delegate/resources/DelegateMtlsEndpointResource.java, line 1 at r1](https://reviewable.io/reviews/harness/harness-core/32274#-N-yiFUH0TxiiPEXNOGP:-N-yoI6m3j6Icb6Uxlj_:b-lw6aii) ([raw file](https://github.com/harness/harness-core/blob/9640d719715002fa830e2a192052e06449d14c17/400-rest/src/main/java/io/harness/delegate/resources/DelegateMtlsEndpointResource.java#L1)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Should this be under 420-delegate-service
</blockquote></details>

Optimally, yes. However, due to its dependencies on the  harness support user check I can't move it there.
Since the effort of moving everything delegate related in manager to 420, I didn't try to solve that problem as of now too avoid unnecessary work.
___
*[420-delegate-service/src/main/java/io/harness/service/DelegateServiceModule.java, line 48 at r1](https://reviewable.io/reviews/harness/harness-core/32274#-N-ykOeX8gydB0s7L6dq:-N-yo_mT9T_BDekzT0Bp:b-22yc3v) ([raw file](https://github.com/harness/harness-core/blob/9640d719715002fa830e2a192052e06449d14c17/420-delegate-service/src/main/java/io/harness/service/DelegateServiceModule.java#L48)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

why empty string?
</blockquote></details>

I can also have it as null, they are treated similary later on.
___
*[420-delegate-service/src/main/java/io/harness/service/impl/DelegateMtlsEndpointServiceImpl.java, line 107 at r1](https://reviewable.io/reviews/harness/harness-core/32274#-N-ylm1T4V0psybke2F7:-N-yq1LyCRcYM8AsrVQw:bjtt6jm) ([raw file](https://github.com/harness/harness-core/blob/9640d719715002fa830e2a192052e06449d14c17/420-delegate-service/src/main/java/io/harness/service/impl/DelegateMtlsEndpointServiceImpl.java#L107)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

you can also use that in one line persistence.findAndModify(query, updateOperations, HPersistence.returnNewOptions)
</blockquote></details>

oh nice!

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32274)* status: :shipit: complete! ✓

**Comment by johannesHarness** [comment]
trigger ti1

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 5 of 7 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32274)* status: :shipit: complete! ✓

**Pull request merged**
