### PR TITLE
techdebt: [DEL-5722]: move ThirdPartyApiCallLog and CVActivityLog out of delegate

### PR DESCRIPTION
**Pull request by raghuAtWings**
## Describe your changes
In an effort to remove mongo dependency in delegate we are doing the following

1. Moved ThirdPartyApiCallLog and  CVActivityLog to 400-rest
2. created a dtos with same names  in 930-delegate-tasks

**Tests done**
1. created service guard in PR env and verified that the api logs are showing up with these changes
2. same test above with the delegate version 1.0.78306 (current prod version) and verified that the api call logs are showing up

Screen Shot 2023-02-15 at 3 38 20 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42408)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
trigger ti0

**Comment by raghuAtWings** [comment]
trigger ti4

**Review by mdmilic — DISMISSED** [review]
> Reviewed 61 of 96 files at r1, 38 of 39 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42408)* status: Some of the checks are too old. Waiting on team(s): del-team. 

___
*[`930-delegate-tasks/src/main/java/software/wings/beans/dto/ThirdPartyApiCallLog.java` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/42408#-NP-Kwov-UzsSYfzf-uD:-NP-Kwov-UzsSYfzf-uE:bl8wqji) ([raw file](https://github.com/harness/harness-core/blob/d3682679bf0f2563c66103472c87c489a0ae0128/930-delegate-tasks/src/main/java/software/wings/beans/dto/ThirdPartyApiCallLog.java#L36)):*
> ```Java
>  */
> @Data
> @Builder
> ```

Does it really need all of these?



_Code quote:_
```Java
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
```

**Comment by raghuAtWings** [comment]
trigger ti3

**Comment by AnshuH** [comment]
trigger ut3 ut5

**Review by AnupamIO — APPROVED** [review]
> Reviewed 60 of 96 files at r1, 35 of 39 files at r2, 1 of 1 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42408)* status: :shipit: complete! ✓

**Pull request merged**
