### PR TITLE
fix: [DEL-5804]: Move DelegateSelectionRecords to google data store

### PR DESCRIPTION
**Pull request by raghuAtWings**
## Describe your changes
DelegateSelectionRecords creates a huge volume which forces us to use expensive mongodb instances. Since this data is just mostly storage and rarely read we want to move it to google data store for cheaper storage. 

**Tests done**
1. end to end k8 deployment in cg
2. end to end shell scrip deployment in ng

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42735)

### CODE REVIEW

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java` line 120 at r2](https://reviewable.io/reviews/harness/harness-core/42735#-NMfHisU0JaOzOJSrAdj:-NMfHisU0JaOzOJSrAdk:b-xdjfud) ([raw file](https://github.com/harness/harness-core/blob/4c9aa8a33045c7860296834282e7d7c2cc816d6f/400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java#L120)):*
> ```Java
> 
>   @Override
>   public synchronized void save(DelegateSelectionLog selectionLog) {
> ```

you adding FF for fetching the selection log, not for saving?

This method calls frequently 4+ per task(we removed batch saving) so synchronization can slow down overall

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java` line 333 at r2](https://reviewable.io/reviews/harness/harness-core/42735#-NMfKBry3I5sAlHGgYZI:-NMfKBry3I5sAlHGgYZJ:bhosp1a) ([raw file](https://github.com/harness/harness-core/blob/4c9aa8a33045c7860296834282e7d7c2cc816d6f/400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java#L333)):*
> ```Java
>     if (delegateSelectionLog == null) {
>       return Optional.empty();
>     }
> ```

So delegateSelectionLogTaskMetadata collection will remain in DB?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java` line 120 at r2](https://reviewable.io/reviews/harness/harness-core/42735#-NMfHisU0JaOzOJSrAdj:-NMfK-uO1gWNyQx7TZFH:btkm07z) ([raw file](https://github.com/harness/harness-core/blob/4c9aa8a33045c7860296834282e7d7c2cc816d6f/400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java#L120)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

you adding FF for fetching the selection log, not for saving?

This method calls frequently 4+ per task(we removed batch saving) so synchronization can slow down overall   
</blockquote></details>

The idea is to start saving at both places so that when we toggle the data is present at both places. Once this flag is GA'd we will stop writing to mongo. 
Also this call just adds in the cache so its fast.

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java` line 333 at r2](https://reviewable.io/reviews/harness/harness-core/42735#-NMfKBry3I5sAlHGgYZI:-NMfKTzV97uqWY6_B1OR:b-96vfak) ([raw file](https://github.com/harness/harness-core/blob/4c9aa8a33045c7860296834282e7d7c2cc816d6f/400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java#L333)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

So delegateSelectionLogTaskMetadata collection will remain in DB?
</blockquote></details>

good point, Do you know why we need this collection?

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java` line 333 at r2](https://reviewable.io/reviews/harness/harness-core/42735#-NMfKBry3I5sAlHGgYZI:-NMfKsVVAVAqeHodaK8t:bbpdqgb) ([raw file](https://github.com/harness/harness-core/blob/4c9aa8a33045c7860296834282e7d7c2cc816d6f/400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java#L333)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

good point, Do you know why we need this collection?
</blockquote></details>

SetUpAbstractions data in CG mostly

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java` line 333 at r2](https://reviewable.io/reviews/harness/harness-core/42735#-NMfKBry3I5sAlHGgYZI:-NMfL9Vb3ui_AgeX10CG:bb2jqr3) ([raw file](https://github.com/harness/harness-core/blob/4c9aa8a33045c7860296834282e7d7c2cc816d6f/400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java#L333)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

SetUpAbstractions data in CG mostly 


</blockquote></details>

Also this is one per task not per selectionLogRecord

**Comment by jennyjames21** [comment]
*[`400-rest/src/test/java/software/wings/service/impl/DelegateSelectionLogsServiceImplTest.java` line 437 at r2](https://reviewable.io/reviews/harness/harness-core/42735#-NMfLmeQ2ZSyIA-lDnSa:-NMfLmeQ2ZSyIA-lDnSb:b77gby5) ([raw file](https://github.com/harness/harness-core/blob/4c9aa8a33045c7860296834282e7d7c2cc816d6f/400-rest/src/test/java/software/wings/service/impl/DelegateSelectionLogsServiceImplTest.java#L437)):*
> ```Java
>   private List<DelegateSelectionLogParams> fetchSelectionLogs(String accountId, String taskId) {
>     List<DelegateSelectionLogParams> delegateSelectionLogParams = new ArrayList<>();
>     for (int i = 0; i < 10; i++) {
> ```

why 10?

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/selection/log/DelegateSelectionLog.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/42735#-NMfNZ4d06rvmLUQQoGo:-NMfNZ4d06rvmLUQQoGp:b-lljwme) ([raw file](https://github.com/harness/harness-core/blob/8c54320f1af4e027fe220adabb99cab0ab5e356a/420-delegate-service/src/main/java/io/harness/selection/log/DelegateSelectionLog.java#L52)):*
> ```Java
>                  .field(DelegateSelectionLogKeys.taskId)
>                  .field(DelegateSelectionLogKeys.message)
>                  .field(DelegateSelectionLogKeys.groupId)
> ```

Do we need to make this change anymore since you are moving away from mongo?
Also it's the last field in the list, may not make any difference, thinking the cost of removing and add new index

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42735)* status: 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/selection/log/DelegateSelectionLogTaskMetadata.java` line 49 at r4](https://reviewable.io/reviews/harness/harness-core/42735#-NN8wOa41tmcKU9kB2lL:-NN8wOa41tmcKU9kB2lM:b95peoz) ([raw file](https://github.com/harness/harness-core/blob/051cec393e900301b69054d787a4a19c71ae69fe/420-delegate-service/src/main/java/io/harness/selection/log/DelegateSelectionLogTaskMetadata.java#L49)):*
> ```Java
> 
>   @Builder.Default @FdTtlIndex private Date validUntil = Date.from(OffsetDateTime.now().plusMonths(1).toInstant());
> }
> ```

Do you want to delete this in this PR?

**Comment by jennyjames21** [comment]
*[`400-rest/src/test/java/software/wings/service/impl/DelegateSelectionLogsServiceImplTest.java` line 437 at r2](https://reviewable.io/reviews/harness/harness-core/42735#-NMfLmeQ2ZSyIA-lDnSa:-NN8wyMd1fyIXPctKnje:beay9mr) ([raw file](https://github.com/harness/harness-core/blob/4c9aa8a33045c7860296834282e7d7c2cc816d6f/400-rest/src/test/java/software/wings/service/impl/DelegateSelectionLogsServiceImplTest.java#L437)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

why 10? 
</blockquote></details>

can you move the limit to constant?

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 7 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42735)* status: 0 of 1 approvals obtained.

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java` line 333 at r2](https://reviewable.io/reviews/harness/harness-core/42735#-NMfKBry3I5sAlHGgYZI:-NN94A1t7xSxcpaeuGc5:b-oicv7z) ([raw file](https://github.com/harness/harness-core/blob/4c9aa8a33045c7860296834282e7d7c2cc816d6f/400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java#L333)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Also this is one per task not per selectionLogRecord
</blockquote></details>

removed now

**Comment by raghuAtWings** [comment]
*[`400-rest/src/test/java/software/wings/service/impl/DelegateSelectionLogsServiceImplTest.java` line 437 at r2](https://reviewable.io/reviews/harness/harness-core/42735#-NMfLmeQ2ZSyIA-lDnSa:-NN94BWH4OL1AToSI5p2:bswriv6) ([raw file](https://github.com/harness/harness-core/blob/4c9aa8a33045c7860296834282e7d7c2cc816d6f/400-rest/src/test/java/software/wings/service/impl/DelegateSelectionLogsServiceImplTest.java#L437)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

can you move the limit to constant?
</blockquote></details>

this is for test

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/selection/log/DelegateSelectionLog.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/42735#-NMfNZ4d06rvmLUQQoGo:-NN94JgU2d23pKYRaiJF:bypsxzw) ([raw file](https://github.com/harness/harness-core/blob/8c54320f1af4e027fe220adabb99cab0ab5e356a/420-delegate-service/src/main/java/io/harness/selection/log/DelegateSelectionLog.java#L52)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Do we need to make this change anymore since you are moving away from mongo?
Also it's the last field in the list, may not make any difference, thinking the cost of removing and add new index
</blockquote></details>

yes we should for better coding practice. The OPS team will create the new index and delete the old one. The index name is changed

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/selection/log/DelegateSelectionLogTaskMetadata.java` line 49 at r4](https://reviewable.io/reviews/harness/harness-core/42735#-NN8wOa41tmcKU9kB2lL:-NN94Ubn3aaMNeyNxD7t:bsnzcsd) ([raw file](https://github.com/harness/harness-core/blob/051cec393e900301b69054d787a4a19c71ae69fe/420-delegate-service/src/main/java/io/harness/selection/log/DelegateSelectionLogTaskMetadata.java#L49)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Do you want to delete this in this PR?
</blockquote></details>

yes. tested this for both cg and ng

**Review by xingchi-jin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42735)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java` line 295 at r4](https://reviewable.io/reviews/harness/harness-core/42735#-NNJfEP-A0rZL4T0NmCw:-NNJfEP-A0rZL4T0NmCx:bp28678) ([raw file](https://github.com/harness/harness-core/blob/f0a958832f51ecdebff22a3bbaea8aea88403fd9/400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java#L295)):*
> ```Java
>                       .addFilter(DelegateSelectionLogKeys.accountId, SearchFilter.Operator.EQ, accountId)
>                       .addFilter(DelegateSelectionLogKeys.taskId, SearchFilter.Operator.EQ, taskId)
>                       .addFilter(DelegateSelectionLogKeys.conclusion, SearchFilter.Operator.EQ, ASSIGNED)
> ```

should here be ASSIGNED or SELECTED ? 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java` line 394 at r4](https://reviewable.io/reviews/harness/harness-core/42735#-NNJfSTxAz9tmza1v6q4:-NNJfSTxAz9tmza1v6q5:buc3kym) ([raw file](https://github.com/harness/harness-core/blob/f0a958832f51ecdebff22a3bbaea8aea88403fd9/400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java#L394)):*
> ```Java
>   }
> 
>   void purgeSelectionLogs() {
> ```

private
___
*[`400-rest/src/main/resources/google/data-store-index.yaml` line 198 at r4](https://reviewable.io/reviews/harness/harness-core/42735#-NNJgkOzA5pjJUe5Ch9T:-NNJgkOzA5pjJUe5Ch9U:b-mi15gu) ([raw file](https://github.com/harness/harness-core/blob/f0a958832f51ecdebff22a3bbaea8aea88403fd9/400-rest/src/main/resources/google/data-store-index.yaml#L198)):*
> ```YAML
> - kind: delegateSelectionLogRecords
>   properties:
>     - name: accountId
> ```

why other fields are not present here ?
like message, conclusion ..etc

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java` line 394 at r4](https://reviewable.io/reviews/harness/harness-core/42735#-NNJfSTxAz9tmza1v6q4:-NNgy0Gk4eyDHpNYOlaH:b-uvhxti) ([raw file](https://github.com/harness/harness-core/blob/f0a958832f51ecdebff22a3bbaea8aea88403fd9/400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java#L394)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

private
</blockquote></details>

its used in a test so package protected

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/resources/google/data-store-index.yaml` line 198 at r4](https://reviewable.io/reviews/harness/harness-core/42735#-NNJgkOzA5pjJUe5Ch9T:-NNgy3k6EeYmbcWGdC7X:bu6yyks) ([raw file](https://github.com/harness/harness-core/blob/f0a958832f51ecdebff22a3bbaea8aea88403fd9/400-rest/src/main/resources/google/data-store-index.yaml#L198)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

why other fields are not present here ?
like message, conclusion ..etc 

</blockquote></details>

we don't want to create index on each field, only on what is needed

**Comment by raghuAtWings** [comment]
trigger ti0

**Review by xingchi-jin — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42735)* status: 4 file(s) to review. 1. unresolved discussions. Waiting on team(s): del-team.

**Review by jennyjames21 — DISMISSED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42735)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42735)* status: :shipit: complete! ✓

**Pull request merged**
