### PR TITLE
fix: [CDS-53208]: update instance dashboard details

### PR DESCRIPTION
**Pull request by achyuth-harness**
## Describe your changes
For helm chart deployments of a sub-chart, we have updated the instance dashboard details to include both parent chart name and sub-chart name

How it looks:
image

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44293)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44293)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 1095 at r1](https://reviewable.io/reviews/harness/harness-core/44293#-NPWlwI94Ht_aKbmXrGf:-NPWlwI94Ht_aKbmXrGg:b2f0l2t) ([raw file](https://github.com/harness/harness-core/blob/257fb91c7c171eb17c73e14a08c41e1225021050/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L1095)):*
> ```Java
>     }
> 
>     helmChartInfo.setSubChart(isNotEmpty(helmChartManifestDelegateConfig.getSubChartName()));
> ```

What about K8s Deployments?
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmChartInfo.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/44293#-NPWlt507RcxwNHbVcIv:-NPWlt507RcxwNHbVcIw:b-c7vjt9) ([raw file](https://github.com/harness/harness-core/blob/257fb91c7c171eb17c73e14a08c41e1225021050/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmChartInfo.java#L24)):*
> ```Java
>   private String version;
>   private String repoUrl;
>   private boolean isSubChart;
> ```

Should we use instead subchart name?

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44293)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmChartInfo.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/44293#-NPWlt507RcxwNHbVcIv:-NPa27rn4DNKIggeF0x8:b-lmj7jn) ([raw file](https://github.com/harness/harness-core/blob/257fb91c7c171eb17c73e14a08c41e1225021050/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmChartInfo.java#L24)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Should we use instead subchart name?
</blockquote></details>

We will show that it is a sub-chart (in UI) when we hover over the chart details if this field is set to true.

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44293)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 1589 at r4](https://reviewable.io/reviews/harness/harness-core/44293#-NPqKPdZ5Ih3gFrpuqoI:-NPqKPdZ5Ih3gFrpuqoJ:bply99v) ([raw file](https://github.com/harness/harness-core/blob/afbcf0aecbb7810f9e07c490be2b8f8686be8093/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L1589)):*
> ```Java
>     }
> 
>     log.error("Chart name not found");
> ```

should be warn if it doesn't fail

**Review by GoelPratyush99 — DISMISSED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44293)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44293)* status: :shipit: complete! ✓

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44293)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by GoelPratyush99 — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44293)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44293)* status: 1 of 2 approvals obtained.

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44293)* status: :shipit: complete! ✓

**Pull request merged**
