### PR TITLE
techdebt: [SRM-14826]: Record duration for orchestration and state ma…

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
…chine

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48475)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48475)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/metrics/CVNGMetricsUtils.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/48475#-NWbl23p4vTZV9_O4JTZ:-NWbl23p4vTZV9_O4JT_:bto6n3s) ([raw file](https://github.com/harness/harness-core/blob/b2eccde497b0364fc2e1e2239db4c9af934b7095/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/metrics/CVNGMetricsUtils.java#L37)):*
> ```Java
> 
>   String STATE_MACHINE_EXECUTION_TIME = "state_machine_execution_time";
> ```

this needs to be registered in resource.metric.metricdefinition.

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger ut1

**Comment by Varsha-lalwani** [comment]
trigger commonchecks

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48475)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/resources/metrics/metricDefinitions/analysis_orchestrator_metrics` line 8 at r3](https://reviewable.io/reviews/harness/harness-core/48475#-NWjj3NxA-Ot2sqQeoWl:-NWjj3NxA-Ot2sqQeoWm:b2txj66) ([raw file](https://github.com/harness/harness-core/blob/76ade9659280c31ed5120aa44e1980585f9d7996/srm-service/modules/cv-nextgen-service/service/src/main/resources/metrics/metricDefinitions/analysis_orchestrator_metrics#L8)):*
> ```
>     metricDefinition: Time taken to finish the orchestration.
>     type: Duration
>     distribution: [ 0m, 1ms, 15s, 30s, 1m, 2m, 4m, 8m, 16m, 32m ]
> ```

is it taking 32m to complete orchesteraton? I think 0 to 30s should be fine

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48475)* status: :shipit: complete! ✓

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepak-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48475)* status: :shipit: complete! ✓

**Pull request merged**
