### PR TITLE
feat: [CDS-45542]:  clean secret encrypted terraform plan from vault

### PR DESCRIPTION
**Pull request by vlica-harness**
## Describe your changes
Before these changes, terraform plan was stored as a secret in VAULT. Sometimes these entries in the VAULT were never used, as only PLAN step could be executed. Now, we have created a new task to clean the secrets from VAULT when the pipeline ends. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39774)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39774)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 874 at r1](https://reviewable.io/reviews/harness/harness-core/39774#-NGRG1Vf7kEtgGx4X-FR:-NGRG1Vf7kEtgGx4X-FS:b-2xprl8) ([raw file](https://github.com/harness/harness-core/blob/f65f7dbe6974221de5d92dbb71fe1feee125f680/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L874)):*
> ```Java
> 
>   private void runCleanupTerraformSecretTask(Ambiance ambiance, EncryptionConfig encryptionConfig,
>       List<EncryptedRecordData> encryptedRecordData, String cleanupSecretUuid) {
> ```

nit: it would be better to call it ecnryptedRecordDataList
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/cleanup/TerraformSecretCleanupTaskParameters.java` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/39774#-NGRLySjArPeM-ZRBCRY:-NGRLySk2lko2DvPLptg:begelmw) ([raw file](https://github.com/harness/harness-core/blob/f65f7dbe6974221de5d92dbb71fe1feee125f680/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/cleanup/TerraformSecretCleanupTaskParameters.java#L1)):*
> ```Java
> /*
> ```

nit: better to move these to delegate-tasks-beans module
___
*[`980-commons/src/main/java/io/harness/eraro/ErrorCode.java` line 658 at r1](https://reviewable.io/reviews/harness/harness-core/39774#-NGRM9e47jp1ETvs_8WV:-NGRM9e5-tQzfRmHyUgB:b-cwqii) ([raw file](https://github.com/harness/harness-core/blob/f65f7dbe6974221de5d92dbb71fe1feee125f680/980-commons/src/main/java/io/harness/eraro/ErrorCode.java#L658)):*
> ```Java
>   MONGO_EXECUTION_TIMEOUT_EXCEPTION,
>   DELEGATE_NOT_REGISTERED(NOT_FOUND),
>   TERRAFORM_VAULT_SECRET_CLEANUP_FAILURE;
> ```

you need to add this to 980-commons/src/main/resources/response_messages.properties
___
*[`980-commons/src/main/java/io/harness/exception/TerraformSecretCleanupFailureException.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/39774#-NGRMVK64-qr_1w_vEQR:-NGRMVK64-qr_1w_vEQS:bmpjj6w) ([raw file](https://github.com/harness/harness-core/blob/f65f7dbe6974221de5d92dbb71fe1feee125f680/980-commons/src/main/java/io/harness/exception/TerraformSecretCleanupFailureException.java#L2)):*
> ```Java
> /*
>  * Copyright 2021 Harness Inc. All rights reserved.
> ```

nit: should be 2022

**Review by vlica-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39774)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 874 at r1](https://reviewable.io/reviews/harness/harness-core/39774#-NGRG1Vf7kEtgGx4X-FR:-NGRjtcz1T3LrIIlEqiA:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f65f7dbe6974221de5d92dbb71fe1feee125f680/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L874)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: it would be better to call it ecnryptedRecordDataList
</blockquote></details>

done
___
*[`980-commons/src/main/java/io/harness/eraro/ErrorCode.java` line 658 at r1](https://reviewable.io/reviews/harness/harness-core/39774#-NGRM9e47jp1ETvs_8WV:-NGRjyP98g_GQnnxG3-_:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f65f7dbe6974221de5d92dbb71fe1feee125f680/980-commons/src/main/java/io/harness/eraro/ErrorCode.java#L658)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

you need to add this to 980-commons/src/main/resources/response_messages.properties
</blockquote></details>

done
___
*[`980-commons/src/main/java/io/harness/exception/TerraformSecretCleanupFailureException.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/39774#-NGRMVK64-qr_1w_vEQR:-NGRjzNGCv4-BgSwDvUY:bhzvn4t) ([raw file](https://github.com/harness/harness-core/blob/f65f7dbe6974221de5d92dbb71fe1feee125f680/980-commons/src/main/java/io/harness/exception/TerraformSecretCleanupFailureException.java#L2)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: should be 2022
</blockquote></details>

)) done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/cleanup/TerraformSecretCleanupTaskParameters.java` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/39774#-NGRLySjArPeM-ZRBCRY:-NGRjxASCIfIl30qREVk:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f65f7dbe6974221de5d92dbb71fe1feee125f680/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/cleanup/TerraformSecretCleanupTaskParameters.java#L1)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: better to move these to delegate-tasks-beans module
</blockquote></details>

done

**Review by abosii-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39774)* status: :shipit: complete! ✓

**Comment by vlica-harness** [comment]
trigger feature-build

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39774)* status: :shipit: complete! ✓

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 17 files at r1, 5 of 7 files at r2, 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39774)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 1053 at r3](https://reviewable.io/reviews/harness/harness-core/39774#-NGWmPjg3FP_jYEDw0ND:-NGWmPjg3FP_jYEDw0NE:b1irkk7) ([raw file](https://github.com/harness/harness-core/blob/367332e2149c7a7fc8b28dd3da80301f5e8cbf40/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L1053)):*
> ```Java
>     return fileInfo;
>   }
>   public void cleanupAllTerraformPlanExecutionDetails(TFPlanExecutionDetailsKey tfPlanExecutionDetailsKey) {
> ```

please add empty line
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 1082 at r3](https://reviewable.io/reviews/harness/harness-core/39774#-NGWmy4u1PFv9rIsB5i6:-NGWmy4u1PFv9rIsB5i7:b-ng2zio) ([raw file](https://github.com/harness/harness-core/blob/367332e2149c7a7fc8b28dd3da80301f5e8cbf40/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L1082)):*
> ```Java
>             .taskType(TaskType.TERRAFORM_SECRET_CLEANUP_TASK_NG.name())
>             .executionTimeout(Duration.ofMinutes(10))
>             .taskSetupAbstraction("ng", "true")
> ```

lets use io.harness.cdng.common.beans.SetupAbstractionKeys constants
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 1084 at r3](https://reviewable.io/reviews/harness/harness-core/39774#-NGWn7kB4IohD9Z2UuVV:-NGWn7kB4IohD9Z2UuVW:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/367332e2149c7a7fc8b28dd3da80301f5e8cbf40/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L1084)):*
> ```Java
>             .taskSetupAbstraction("ng", "true")
>             .logStreamingAbstractions(
>                 new LinkedHashMap<>(ImmutableMap.of("accountId", AmbianceUtils.getAccountId(ambiance))))
> ```

same here

**Review by namantalaycha10 — APPROVED** [review]
> Reviewed 2 of 17 files at r1, 2 of 7 files at r2, 3 of 6 files at r3, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39774)* status: :shipit: complete! ✓

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39774)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39774)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 1086 at r4](https://reviewable.io/reviews/harness/harness-core/39774#-NGqpmrCESZZioPZ6w1r:-NGqpmrCESZZioPZ6w1s:blmooqr) ([raw file](https://github.com/harness/harness-core/blob/6bb298809672fb26aaf35635a87b5c918d49d463/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L1086)):*
> ```Java
>             .taskSetupAbstraction(SetupAbstractionKeys.ng, "true")
>             .logStreamingAbstractions(new LinkedHashMap<>(
>                 ImmutableMap.of(SetupAbstractionKeys.accountId, AmbianceUtils.getAccountId(ambiance))))
> ```

are you sure about these changes? If there is any logic that would update this map before serializing it will result in not supported operation. I'm not aware if this map is mutated after, just checking

**Review by vlica-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39774)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 1086 at r4](https://reviewable.io/reviews/harness/harness-core/39774#-NGqpmrCESZZioPZ6w1r:-NGr8tsL61YVL2ez4NX1:b-2g83hn) ([raw file](https://github.com/harness/harness-core/blob/6bb298809672fb26aaf35635a87b5c918d49d463/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L1086)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

are you sure about these changes? If there is any logic that would update this map before serializing it will result in not supported operation. I'm not aware if this map is mutated after, just checking
</blockquote></details>

did change it

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39774)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39774)* status: :shipit: complete! ✓

**Review by namantalaycha10 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39774)* status: :shipit: complete! ✓

**Review by alebuh — APPROVED** [review]
> Reviewed 2 of 17 files at r1, 2 of 7 files at r2, 3 of 6 files at r3, 11 of 12 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39774)* status: :shipit: complete! ✓

**Pull request merged**
