### PR TITLE
feat: [IE-228]: Dockerfile standardization for ACL service

### PR DESCRIPTION
**Pull request by rijajoo**
## Describe your changes
Build:- https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/ci/orgs/default/projects/FEATUREBUILDS/pipelines/Build_Docker_Standardized_Services/executions/7pMYm7c8S4ymw-fn0c_Klg/pipeline?storeType=INLINE
Deployment-https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/default/projects/DevSpaces/pipelines/Deploy_Services/executions/-sUHy-p7Qe-Zx3rqQ8MZNQ/pipeline?connectorRef=harnessplinfra&branch=master&repoName=harness-pl-infra&storeType=REMOTE&stage=4_HKQEB2RW2tPBHKIUKjRQ
Image Size:- Old: 864MB, New: 858MB
Image Efficiency:- 98%

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51062)

### CODE REVIEW

**Review by krishi0408 — COMMENTED** [review]
they are having JDK_17 change, i think this was not working. We need to ask vishal

**Comment by Vbhatia20** [comment]
trigger uts

**Review by Vbhatia20 — APPROVED** [review]

**Comment by krishi0408** [comment]
trigger ut8

**Comment by Vbhatia20** [comment]
trigger ut7

**Comment by Vbhatia20** [comment]
trigger ut8

**Comment by rijajoo** [comment]
trigger ut7

**Comment by rijajoo** [comment]
trigger ut8

**Comment by rijajoo** [comment]
trigger uts

**Comment by rijajoo** [comment]
trigger ut7

**Comment by rijajoo** [comment]
trigger ut0

**Comment by rijajoo** [comment]
trigger ut0

**Comment by rijajoo** [comment]
trigger ut7

**Comment by rijajoo** [comment]
trigger ut0

**Review by Vbhatia20 — DISMISSED** [review]

**Comment by rijajoo** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
*[`access-control/build/container/Dockerfile-accesscontrol-service-cie-jdk-multistage` line 47 at r6](https://reviewable.io/reviews/harness/harness-core/51062#-NbyMkEY5TtwE8aWMCtO:-NbyMkEY5TtwE8aWMCtP:bwhxv60) ([raw file](https://github.com/harness/harness-core/blob/e19fe6d3e518ffb0b63f0d822c26cf6210d5df13/access-control/build/container/Dockerfile-accesscontrol-service-cie-jdk-multistage#L47)):*
> ```
> USER root
> RUN set -x \
> && microdnf remove tar unzip gzip
> ```

Last time this failed for me with jdk 17 image

**Comment by rijajoo** [comment]
trigger uts

**Comment by rijajoo** [comment]
trigger uts

**Review by Vbhatia20 — APPROVED** [review]

**Review by ashishsanodia-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 1 of 2 files at r3, 2 of 2 files at r4, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51062#-:-Nbz8stc-uCUkv3BHhKZ:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
