### PR TITLE
fix: [PL-28329]: api key entry proper caching

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Describe your changes
The issue we had was stale usergroup object while computing permission for api key. 
When we were getting api key we were setting usergroup object depending on a flag details which can be either of true of false. 
On true we were getting the whole usergroup object and saving it whereas when it was false we were saving only some fields of that object. 
Later while computing permissions we were using the usergroup object to get api key permissions which can lead to wrong permissions if api key cache has apikey value without usergroup details. 

We are changing it to always have complete usergroup object in api key cache.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37677)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* Code issue 6 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37677)

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37677)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 261 at r1](https://reviewable.io/reviews/harness/harness-core/37677#-NCNHbhk0bFwJVC7jKkW:-NCNHbhk0bFwJVC7jKkX:b-hfpv1m) ([raw file](https://github.com/harness/harness-core/blob/fa5ad039be34f910748905480473c1a7bfe30614/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L261)):*
> ```Java
>   }
> 
>   private ApiKeyEntry buildApiKeyEntry(String uuid, ApiKeyEntry entry, boolean details) {
> ```

remove?



_Code quote:_
```Java
boolean details
```
___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 378 at r1](https://reviewable.io/reviews/harness/harness-core/37677#-NCNJPDgCM1UXNG9yTQt:-NCNJPDgCM1UXNG9yTQu:bxh0zuu) ([raw file](https://github.com/harness/harness-core/blob/fa5ad039be34f910748905480473c1a7bfe30614/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L378)):*
> ```Java
>         apiKeyPermissionInfo = apiKeyPermissionInfoCache.get(getKeyForAPIKeyCache(accountId, apiKey));
>         if (apiKeyPermissionInfo == null) {
>           updateApiKeyCacheIfUserGroupIsUnset(apiKeyEntry, accountId, apiKey);
> ```

why only if user group is unset -- please document too.



_Code quote:_
```Java
 up
```

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37677)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 351 at r1](https://reviewable.io/reviews/harness/harness-core/37677#-NCNJdej8CbPO2CqcDMA:-NCNJdej8CbPO2CqcDMB:bikp38o) ([raw file](https://github.com/harness/harness-core/blob/fa5ad039be34f910748905480473c1a7bfe30614/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L351)):*
> ```Java
>       }
>       if (!details && apiKeyEntry != null) {
>         // this block of code is written to make changes less risky as apiKeyEntry always need to have all the details.
> ```

Probably document with javadoc what details argument is supposed to do, i.e ApiKeyEntry to include/exclude UserGroupDetail.

Then here, add a comment that you are just filtering out additional details from the ApiKeyEntry based on the argument passed,



_Code quote:_
```Java
this block of code is written to make changes less risky as apiKeyEntry always need to have all the details.
```

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37677)* status: 1 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 350 at r1](https://reviewable.io/reviews/harness/harness-core/37677#-NCNt2MTCgCFtQ83Ofsa:-NCNt2MTCgCFtQ83Ofsb:b-j43z2f) ([raw file](https://github.com/harness/harness-core/blob/fa5ad039be34f910748905480473c1a7bfe30614/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L350)):*
> ```Java
>         }
>       }
>       if (!details && apiKeyEntry != null) {
> ```

Why is this required?. It should be safe to return whole ApiKeyEntry, right?
___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 378 at r1](https://reviewable.io/reviews/harness/harness-core/37677#-NCNtcKz7ovqKVt-SZ14:-NCNtcKz7ovqKVt-SZ15:b-p0lj1d) ([raw file](https://github.com/harness/harness-core/blob/fa5ad039be34f910748905480473c1a7bfe30614/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L378)):*
> ```Java
>         apiKeyPermissionInfo = apiKeyPermissionInfoCache.get(getKeyForAPIKeyCache(accountId, apiKey));
>         if (apiKeyPermissionInfo == null) {
>           updateApiKeyCacheIfUserGroupIsUnset(apiKeyEntry, accountId, apiKey);
> ```

Why are we updating cache in get() method here? Is this temporary code fix current cache entries? Should we flush entire cache instead and then let it rebuild

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37677)* status: 1 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 261 at r1](https://reviewable.io/reviews/harness/harness-core/37677#-NCNHbhk0bFwJVC7jKkW:-NCOIzBGExcqmHgtzDTE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fa5ad039be34f910748905480473c1a7bfe30614/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L261)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

remove?
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 351 at r1](https://reviewable.io/reviews/harness/harness-core/37677#-NCNJdej8CbPO2CqcDMA:-NCOJ0KtBdEq6pRq8e8x:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fa5ad039be34f910748905480473c1a7bfe30614/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L351)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Probably document with javadoc what details argument is supposed to do, i.e ApiKeyEntry to include/exclude UserGroupDetail.

Then here, add a comment that you are just filtering out additional details from the ApiKeyEntry based on the argument passed,
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 378 at r1](https://reviewable.io/reviews/harness/harness-core/37677#-NCNtcKz7ovqKVt-SZ14:-NCOJ1Cr-e1CjF5ALTRk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fa5ad039be34f910748905480473c1a7bfe30614/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L378)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why are we updating cache in get() method here? Is this temporary code fix current cache entries? Should we flush entire cache instead and then let it rebuild
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 378 at r1](https://reviewable.io/reviews/harness/harness-core/37677#-NCNJPDgCM1UXNG9yTQt:-NCOJ1WQ-WrxDKA86MzS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fa5ad039be34f910748905480473c1a7bfe30614/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L378)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

why only if user group is unset -- please document too.
</blockquote></details>

Done.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37677#-:-NCOK0JtBSVcEUHYQWSH:bnfp4nl)* status: 1 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37677#-:-NCOK2yS-DiFtEgTnJqw:bnfp4nl)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37677#-:-NCOK6gIAg9yB2fbx1zs:bnfp4nl)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37677)* status: 1 file(s) to review.

**Review by gn-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37677)* status: :shipit: complete! ✓

**Review by Y0709 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37677)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37677#-:-NCOkJEF62fquSMI3FTg:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
