### PR TITLE
fix: [PL-22381]: Delete SSO setting in NG

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
…t the ID of the SSO setting.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31199)

### CODE REVIEW

**Comment by piyush-harness** [comment]
___
*[123-ng-core-user/src/main/java/io/harness/ng/authenticationsettings/remote/AuthSettingsManagerClient.java, line 95 at r1](https://reviewable.io/reviews/harness/harness-core/31199#-MxY7LCv7Pnwo2Vjl9Fz:-MxY7LCv7Pnwo2Vjl9G-:b-jvu1wl) ([raw file](https://github.com/harness/harness-core/blob/3dd46e751f2554585d6cb1c23095d5e3d95c1357/123-ng-core-user/src/main/java/io/harness/ng/authenticationsettings/remote/AuthSettingsManagerClient.java#L95)):*
> ```Java
>   Call<RestResponse<SSOConfig>> deleteSAMLMetadata(@Query("accountId") String accountIdentifier);
> 
>   @GET(API_PREFIX + "sso/get-oauth-settings-id")
> ```

API name is not correct it should SAML settings

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31199)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/resources/SSOResourceNG.java, line 124 at r1](https://reviewable.io/reviews/harness/harness-core/31199#-MxY7RLMBO2tHQkv0RkG:-MxY7RLMBO2tHQkv0RkH:bswuufw) ([raw file](https://github.com/harness/harness-core/blob/3dd46e751f2554585d6cb1c23095d5e3d95c1357/400-rest/src/main/java/software/wings/resources/SSOResourceNG.java#L124)):*
> ```Java
>   @Timed
>   @ExceptionMetered
>   public RestResponse<String> getOauthSettingId(@QueryParam("accountId") String accountId) {
> ```

Here also change the name

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31199)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[123-ng-core-user/src/main/java/io/harness/ng/authenticationsettings/remote/AuthSettingsManagerClient.java, line 95 at r1](https://reviewable.io/reviews/harness/harness-core/31199#-MxY7LCv7Pnwo2Vjl9Fz:-MxYBhkN3GXh7OEOsYHK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3dd46e751f2554585d6cb1c23095d5e3d95c1357/123-ng-core-user/src/main/java/io/harness/ng/authenticationsettings/remote/AuthSettingsManagerClient.java#L95)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

API name is not correct it should SAML settings
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/resources/SSOResourceNG.java, line 124 at r1](https://reviewable.io/reviews/harness/harness-core/31199#-MxY7RLMBO2tHQkv0RkG:-MxYBiYO0Stkxn-Ud3Uq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3dd46e751f2554585d6cb1c23095d5e3d95c1357/400-rest/src/main/java/software/wings/resources/SSOResourceNG.java#L124)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Here also change the name
</blockquote></details>

Done.

**Comment by shashank-harness** [comment]
___
*[122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java, line 64 at r2](https://reviewable.io/reviews/harness/harness-core/31199#-MxnxbsO9k8X0U1lvkPJ:-MxnxbsO9k8X0U1lvkPK:b-5ee9u4) ([raw file](https://github.com/harness/harness-core/blob/04677c2d24445b0a8879290db84044472ef2bf74/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L64)):*
> ```Java
>   private final AuthSettingsManagerClient managerClient;
>   private final EnforcementClientService enforcementClientService;
>   @Inject UserGroupService userGroupService;
> ```

private final UserGroupService userGroupService



_Code quote:_
```Java
AuthenticationSettingsServiceImpl 
```

**Comment by shashank-harness** [comment]
___
*[122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java, line 248 at r2](https://reviewable.io/reviews/harness/harness-core/31199#-Mxny6ou4Nm_U3Yixuh2:-Mxny6ov8oaxzPz8dZMk:b-3kfjsu) ([raw file](https://github.com/harness/harness-core/blob/04677c2d24445b0a8879290db84044472ef2bf74/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L248)):*
> ```Java
>       throw new InvalidRequestException("No Saml Metadata found for this account");
>     }
>     if (!userGroupService.getUserGroupsBySsoId(accountIdentifier, ssoId).isEmpty()) {
> ```

use isNotEmpty

**Comment by shashank-harness** [comment]
___
*[122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java, line 244 at r2](https://reviewable.io/reviews/harness/harness-core/31199#-MxnyfQK1Pq0cAUMqB0p:-MxnyfQK1Pq0cAUMqB0q:b-a4ahy9) ([raw file](https://github.com/harness/harness-core/blob/04677c2d24445b0a8879290db84044472ef2bf74/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L244)):*
> ```Java
>   @Override
>   public SSOConfig deleteSAMLMetadata(@NotNull @AccountIdentifier String accountIdentifier) {
>     String ssoId = getResponse(managerClient.getSAMLMetadataId(accountIdentifier));
> ```

do the timeout testing as discussed

**Comment by shashank-harness** [comment]
___
*[400-rest/src/main/java/software/wings/resources/SSOResourceNG.java, line 124 at r1](https://reviewable.io/reviews/harness/harness-core/31199#-MxY7RLMBO2tHQkv0RkG:-MxnzkqI1iFJAaA9E6vV:b-gs8b5q) ([raw file](https://github.com/harness/harness-core/blob/3dd46e751f2554585d6cb1c23095d5e3d95c1357/400-rest/src/main/java/software/wings/resources/SSOResourceNG.java#L124)):*
<details><summary><i>Previously, VikasMaddukuriHarness (VikasMaddukuriHarness) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

change method name also

**Comment by shashank-harness** [comment]
___
*[400-rest/src/main/java/software/wings/resources/SSOResourceNG.java, line 122 at r2](https://reviewable.io/reviews/harness/harness-core/31199#-Mxo0H7QDJCbSOUZZQlq:-Mxo0H7R5rK-bCuz4p-V:bsrpkyo) ([raw file](https://github.com/harness/harness-core/blob/04677c2d24445b0a8879290db84044472ef2bf74/400-rest/src/main/java/software/wings/resources/SSOResourceNG.java#L122)):*
> ```Java
>   @ExceptionMetered
>   public RestResponse<String> getOauthSettingId(@QueryParam("accountId") String accountId) {
>     SamlSettings samlSettings = ssoService.getSamlSettings(accountId);
> ```

this method should return SamlSettings instead of an id.

**Comment by shashank-harness** [comment]
___
*[400-rest/src/main/java/software/wings/resources/SSOResourceNG.java, line 123 at r2](https://reviewable.io/reviews/harness/harness-core/31199#-Mxo0NtlCdRKHtm-b4vW:-Mxo0NtlCdRKHtm-b4vX:b7wy16k) ([raw file](https://github.com/harness/harness-core/blob/04677c2d24445b0a8879290db84044472ef2bf74/400-rest/src/main/java/software/wings/resources/SSOResourceNG.java#L123)):*
> ```Java
>   public RestResponse<String> getOauthSettingId(@QueryParam("accountId") String accountId) {
>     SamlSettings samlSettings = ssoService.getSamlSettings(accountId);
>     if (samlSettings == null) {
> ```

remove any logic from Resource file method

**Review by shashank-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31199)* status: 6 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31199)* status: 6 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java, line 64 at r2](https://reviewable.io/reviews/harness/harness-core/31199#-MxnxbsO9k8X0U1lvkPJ:-MxriXqg0Ydze3CmamcK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/04677c2d24445b0a8879290db84044472ef2bf74/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L64)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

private final UserGroupService userGroupService
</blockquote></details>

Done.
___
*[122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java, line 244 at r2](https://reviewable.io/reviews/harness/harness-core/31199#-MxnyfQK1Pq0cAUMqB0p:-MxriZIpCucpwmkcc7th:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/04677c2d24445b0a8879290db84044472ef2bf74/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L244)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

do the timeout testing as discussed
</blockquote></details>

Done.
___
*[122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java, line 248 at r2](https://reviewable.io/reviews/harness/harness-core/31199#-Mxny6ou4Nm_U3Yixuh2:-MxriZol9dMro1Inlirt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/04677c2d24445b0a8879290db84044472ef2bf74/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/impl/AuthenticationSettingsServiceImpl.java#L248)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

use isNotEmpty
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/resources/SSOResourceNG.java, line 124 at r1](https://reviewable.io/reviews/harness/harness-core/31199#-MxY7RLMBO2tHQkv0RkG:-Mxri_bpA1ILBOFF52VY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3dd46e751f2554585d6cb1c23095d5e3d95c1357/400-rest/src/main/java/software/wings/resources/SSOResourceNG.java#L124)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

change method name also
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/resources/SSOResourceNG.java, line 122 at r2](https://reviewable.io/reviews/harness/harness-core/31199#-Mxo0H7QDJCbSOUZZQlq:-MxriaFh2Ne3v9_g1ZGY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/04677c2d24445b0a8879290db84044472ef2bf74/400-rest/src/main/java/software/wings/resources/SSOResourceNG.java#L122)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

this method should return SamlSettings instead of an id.
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/resources/SSOResourceNG.java, line 123 at r2](https://reviewable.io/reviews/harness/harness-core/31199#-Mxo0NtlCdRKHtm-b4vW:-MxriamA238mGLpyXs2c:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/04677c2d24445b0a8879290db84044472ef2bf74/400-rest/src/main/java/software/wings/resources/SSOResourceNG.java#L123)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

remove any logic from Resource file method
</blockquote></details>

Done.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31199)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 2 of 6 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31199)* status: :shipit: complete! ✓

**Comment by piyush-harness** [comment]
:lgtm:

**Pull request merged**
