### PR TITLE
fix: [CDS-46083]: Service dashboard is not displaying instances in th…

### PR DESCRIPTION
**Pull request by meenaravichandran1**
…e instances section

## Description
Service dashboard was not displaying the instance details. This change is populate the details from backend.

## Testing steps
Tested locally and it worked. Will test in a PR environment and update.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40197)

### CODE REVIEW

**Review by rohitk-h — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40197)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java` line 219 at r2](https://reviewable.io/reviews/harness/harness-core/40197#-NGwY-slCJyAu-uQim9V:-NGwY-slCJyAu-uQim9W:bvdhov4) ([raw file](https://github.com/harness/harness-core/blob/a9a483182d5c232587f5872b098368988979cfa6/126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java#L219)):*
> ```Java
>                             .is(serviceId)
>                             .and(InstanceKeysAdditional.instanceInfoClusterIdentifier)
>                             .exists(false)
> ```

Suggestion: Instead of filtering non gitops instances here can we add a check as to not call this function for gitops flows? This seems like a generic function so idea is to not modify to exclude non-gitops flow.
___
*[`126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java` line 259 at r2](https://reviewable.io/reviews/harness/harness-core/40197#-NGwYUzhCzo8C1M-iFq7:-NGwYUzhCzo8C1M-iFq8:b-wjgrr) ([raw file](https://github.com/harness/harness-core/blob/a9a483182d5c232587f5872b098368988979cfa6/126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java#L259)):*
> ```Java
>             .as(InstanceSyncConstants.COUNT);
>     return mongoTemplate.aggregate(
>         newAggregation(matchStage, groupClusterEnvId), "instanceNG", ActiveServiceInstanceInfo.class);
> ```

Should this be `Instance.class` Ref: io.harness.entities.Instance

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40197)* status: :shipit: complete! ✓

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40197)* status: 2. unresolved discussions. 

___
*[`126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java` line 219 at r2](https://reviewable.io/reviews/harness/harness-core/40197#-NGwY-slCJyAu-uQim9V:-NGw_QCt0rwjW0A98d7X:bz96oyt) ([raw file](https://github.com/harness/harness-core/blob/a9a483182d5c232587f5872b098368988979cfa6/126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java#L219)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Suggestion: Instead of filtering non gitops instances here can we add a check as to not call this function for gitops flows? This seems like a generic function so idea is to not modify to exclude non-gitops flow.
</blockquote></details>

Will change this
___
*[`126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java` line 259 at r2](https://reviewable.io/reviews/harness/harness-core/40197#-NGwYUzhCzo8C1M-iFq7:-NGwZh1TAY5PXS45IE4G:b-ya4gdj) ([raw file](https://github.com/harness/harness-core/blob/a9a483182d5c232587f5872b098368988979cfa6/126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java#L259)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Should this be `Instance.class` Ref: io.harness.entities.Instance
</blockquote></details>

when using Instance.class got an error because InstanceInfo is abstract and doesn't have details like, clusterid, agentid, appid, etc. that are part of GitopsInstanceInfo class

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40197)* status: 2. unresolved discussions. 

___
*[`126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java` line 219 at r2](https://reviewable.io/reviews/harness/harness-core/40197#-NGwY-slCJyAu-uQim9V:-NGw_iH17-fcw9IswwI8:b-q0w90f) ([raw file](https://github.com/harness/harness-core/blob/a9a483182d5c232587f5872b098368988979cfa6/126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java#L219)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

Will change this
</blockquote></details>

I'm about to send out one more PR today for one other attribute to be reflected in the UI (for another bug). Since the UI can start working on it in parallel, can I add this change to that PR?

**Comment by rohitk-h** [comment]
*[`126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java` line 219 at r2](https://reviewable.io/reviews/harness/harness-core/40197#-NGwY-slCJyAu-uQim9V:-NGwaToI7Z9wBHJYOT9f:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/a9a483182d5c232587f5872b098368988979cfa6/126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java#L219)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

I'm about to send out one more PR today for one other attribute to be reflected in the UI (for another bug). Since the UI can start working on it in parallel, can I add this change to that PR?
</blockquote></details>

yes

**Comment by rohitk-h** [comment]
*[`126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java` line 259 at r2](https://reviewable.io/reviews/harness/harness-core/40197#-NGwYUzhCzo8C1M-iFq7:-NGwaYoa3xKkob8rwzO5:b7eov4d) ([raw file](https://github.com/harness/harness-core/blob/a9a483182d5c232587f5872b098368988979cfa6/126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java#L259)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

when using Instance.class got an error because InstanceInfo is abstract and doesn't have details like, clusterid, agentid, appid, etc. that are part of GitopsInstanceInfo class
</blockquote></details>

ok, let's make it a constance then.

**Pull request merged**
