### PR TITLE
fix: [CDP-20314]: Helm chart values files are not download during dep…

### PR DESCRIPTION
**Pull request by achyuth-harness**
…loyment with harness

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30282)

### CODE REVIEW

**Review by abosii-harness — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30282)* status: 9 file(s) to review. 1 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/HelmChartConfigHelperService.java, line 134 at r1](https://reviewable.io/reviews/harness/harness-core/30282#-MuPtujs2tF1uEAYrLeS:-MuPtujs2tF1uEAYrLeT:b-bq9yjd) ([raw file](https://github.com/harness/harness-core/blob/d692d545c5735b77a76371d89e4d94c917f44872/400-rest/src/main/java/software/wings/service/impl/HelmChartConfigHelperService.java#L134)):*
> ```Java
> 
>     helmChartConfigParamsBuilder.useRepoFlags(
>         featureFlagService.isEnabled(FeatureName.USE_HELM_REPO_FLAGS, context.getAccountId())
> ```

nit: we can reduce an unnecessary call flag check if we will flip the condition in case of Helm v2
___
*[400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java, line 1045 at r1](https://reviewable.io/reviews/harness/harness-core/30282#-MuPu7kP2hbZVvob9Cwh:-MuPu7kP2hbZVvob9Cwi:b-bq9yjd) ([raw file](https://github.com/harness/harness-core/blob/d692d545c5735b77a76371d89e4d94c917f44872/400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java#L1045)):*
> ```Java
>                 featureFlagService.isEnabled(USE_LATEST_CHARTMUSEUM_VERSION, context.getAccountId()));
>             helmChartConfigTaskParams.setUseRepoFlags(
>                 featureFlagService.isEnabled(USE_HELM_REPO_FLAGS, context.getAccountId())
> ```

nit: we can reduce an unnecessary call flag check if we will flip the condition in case of Helm v2
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 734 at r1](https://reviewable.io/reviews/harness/harness-core/30282#-MuPuBmYCSmCMsyRdTeP:-MuPuBmYCSmCMsyRdTeQ:b-vxewyl) ([raw file](https://github.com/harness/harness-core/blob/d692d545c5735b77a76371d89e4d94c917f44872/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L734)):*
> ```Java
> 
>   public void updateRepo(String repoName, String workingDirectory, HelmVersion helmVersion, long timeoutInMillis,
>       boolean useRepoFlag, String tempDir) {
> ```

nit: the var name can be repoDir, is a bit confusing this temp

**Review by abosii-harness — APPROVED** [review]
> Reviewed 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30282)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30282)* status: 11 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 173 at r5](https://reviewable.io/reviews/harness/harness-core/30282#-Mudi_h6BktJucaBSoxF:-Mudi_h6BktJucaBSoxG:b-2adm4b) ([raw file](https://github.com/harness/harness-core/blob/3b7b3314a3db981ff11057ddf975239eda109c01/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L173)):*
> ```Java
>       return;
>     }
>     String dir = Paths.get(RESOURCE_DIR_BASE, "cache").toAbsolutePath().normalize().toString();
> ```

Is this ```dir```  same for all repos?
If yes, it does not help because then its the same as existing functionality
Directories need to unique

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30282)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 173 at r5](https://reviewable.io/reviews/harness/harness-core/30282#-Mudi_h6BktJucaBSoxF:-Mue6ttUAQ3MwZpYtrM0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3b7b3314a3db981ff11057ddf975239eda109c01/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L173)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Is this ```dir```  same for all repos?
If yes, it does not help because then its the same as existing functionality
Directories need to unique 
</blockquote></details>

Done.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 9 files at r1, 2 of 5 files at r2, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30282)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30282)* status: 11 file(s) to review.

**Review by namantalaycha10 — APPROVED** [review]

**Review by namantalaycha10 — DISMISSED** [review]
> Reviewed 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30282)* status: :shipit: complete! ✓

**Comment by achyuth-harness** [comment]
This PR does NOT have a new task type.
cc: @abhinav-harness

**Review by abhinav-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30282)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30282)* status: :shipit: complete! ✓

**Review by abhinav-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30282#-:-Mufa99vEuxLBUAu-1s2:bnfp4nl)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30282)* status: :shipit: complete! ✓

**Pull request closed without merging**
