### PR TITLE
feat: [IDP-176]: Configure GKE logging. Replace ng-manager secret

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44136)

### CODE REVIEW

**Review by deepharness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44136)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/app/IdpConfiguration.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/44136#-NOwi_ywApcLUYPpyNwa:-NOwi_ywApcLUYPpyNwb:bn94kio) ([raw file](https://github.com/harness/harness-core/blob/c21c1b37f9110295f920e0739c95af10f9becac0/idp-service/service/src/main/java/io/harness/idp/app/IdpConfiguration.java#L72)):*
> ```Java
>   public void setServerFactory(ServerFactory factory) {
>     DefaultServerFactory defaultServerFactory = (DefaultServerFactory) factory;
>     ((DefaultServerFactory) getServerFactory())
> ```

use a variable for ((DefaultServerFactory) getServerFactory()), its called many times 



_Code quote:_
```Java
((DefaultServerFactory) getServerFactory())
```
___
*[`idp-service/service/src/main/java/io/harness/idp/app/IdpConfiguration.java` line 81 at r2](https://reviewable.io/reviews/harness/harness-core/44136#-NOwixGOEvNxQPxXp9zm:-NOwixGOEvNxQPxXp9zn:btb4x1s) ([raw file](https://github.com/harness/harness-core/blob/c21c1b37f9110295f920e0739c95af10f9becac0/idp-service/service/src/main/java/io/harness/idp/app/IdpConfiguration.java#L81)):*
> ```Java
>   private ConnectorFactory getDefaultApplicationConnectorFactory() {
>     final HttpConnectorFactory factory = new HttpConnectorFactory();
>     factory.setPort(12003);
> ```

take it from config , its already defined there
___
*[`idp-service/service/src/main/java/io/harness/idp/app/IdpConfiguration.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/44136#-NOwirCo0wr2sXeu9c9C:-NOwirCo0wr2sXeu9c9D:btb4x1s) ([raw file](https://github.com/harness/harness-core/blob/c21c1b37f9110295f920e0739c95af10f9becac0/idp-service/service/src/main/java/io/harness/idp/app/IdpConfiguration.java#L87)):*
> ```Java
>   private ConnectorFactory getDefaultAdminConnectorFactory() {
>     final HttpConnectorFactory factory = new HttpConnectorFactory();
>     factory.setPort(12004);
> ```

take it from config , its already defined there
___
*[`idp-service/service/src/main/java/io/harness/idp/app/IdpConfiguration.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/44136#-NOwj6499Yoy44oBVWo5:-NOwj6499Yoy44oBVWo6:b-1f5wzq) ([raw file](https://github.com/harness/harness-core/blob/c21c1b37f9110295f920e0739c95af10f9becac0/idp-service/service/src/main/java/io/harness/idp/app/IdpConfiguration.java#L94)):*
> ```Java
>     LogbackAccessRequestLogFactory logbackAccessRequestLogFactory = new LogbackAccessRequestLogFactory();
>     FileAppenderFactory<IAccessEvent> fileAppenderFactory = new FileAppenderFactory<>();
>     fileAppenderFactory.setArchive(true);
> ```

can we take it form config?
___
*[`idp-service/service/src/main/java/io/harness/idp/app/IdpConfiguration.java` line 98 at r2](https://reviewable.io/reviews/harness/harness-core/44136#-NOwjBmi7-EqWPYVvc1j:-NOwjBmi7-EqWPYVvc1k:b-1f5wzq) ([raw file](https://github.com/harness/harness-core/blob/c21c1b37f9110295f920e0739c95af10f9becac0/idp-service/service/src/main/java/io/harness/idp/app/IdpConfiguration.java#L98)):*
> ```Java
>     fileAppenderFactory.setThreshold(Level.ALL.toString());
>     fileAppenderFactory.setArchivedLogFilenamePattern("access.%d.log.gz");
>     fileAppenderFactory.setArchivedFileCount(14);
> ```

can we take it form config?

**Review by deepharness — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44136)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by deepharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44136)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by sathish-soundarapandian — APPROVED** [review]
> Reviewed 3 of 3 files at r5, 4 of 5 files at r6, 9 of 10 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44136)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by deepharness — APPROVED** [review]
> Reviewed 3 of 3 files at r5, 4 of 5 files at r6, 9 of 10 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44136)* status: :shipit: complete! ✓

**Pull request merged**
