### PR TITLE
feat: [CDS-54668]: Improved Connector Scope error handling

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Earlier error message was - "OrgIdentifier cannot be empty for ORG scope"

Now it should look like :- "The project level connector cannot be used at account level. Ref: [vgh]"

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44805)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java` line 179 at r2](https://reviewable.io/reviews/harness/harness-core/44805#-NPvX-V45QsT8VAx8c48:-NPvX-V45QsT8VAx8c49:b-4axy2x) ([raw file](https://github.com/harness/harness-core/blob/07003cc368a54866dd97905d725441c6cb808e0c/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L179)):*
> ```Java
>   YamlGitConfigClient yamlGitConfigClient;
>   EntitySetupUsageService entitySetupUsageService;
>   private final String connector = "connector";
> ```

please use capital letter variables for constants.

**Comment by mohitg0795** [comment]
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java` line 192 at r2](https://reviewable.io/reviews/harness/harness-core/44805#-NPvXJzo1sjm7kVj0tmU:-NPvXJzo1sjm7kVj0tmV:bxhtkti) ([raw file](https://github.com/harness/harness-core/blob/07003cc368a54866dd97905d725441c6cb808e0c/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L192)):*
> ```Java
>   public Optional<ConnectorResponseDTO> getByRef(
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, String connectorRef) {
>     IdentifierRef identifierRef = IdentifierRefHelper.getIdentifierRefOrThrowException(
> ```

I'm not sure if this could be a backward incompatible change or so. Please get it approved by PL Team as they are the owners of it I guess.

**Review by inderschera — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44805)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java` line 179 at r2](https://reviewable.io/reviews/harness/harness-core/44805#-NPvYFFABnRFPr0OnIAT:-NPvYFFABnRFPr0OnIAU:b-8d1lzi) ([raw file](https://github.com/harness/harness-core/blob/07003cc368a54866dd97905d725441c6cb808e0c/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L179)):*
> ```Java
>   YamlGitConfigClient yamlGitConfigClient;
>   EntitySetupUsageService entitySetupUsageService;
>   private final String connector = "connector";
> ```

make it static as well
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java` line 192 at r2](https://reviewable.io/reviews/harness/harness-core/44805#-NPvXJzo1sjm7kVj0tmU:-NPvYKo236yWHj6E9yCy:bg1bt9) ([raw file](https://github.com/harness/harness-core/blob/07003cc368a54866dd97905d725441c6cb808e0c/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L192)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I'm not sure if this could be a backward incompatible change or so. Please get it approved by PL Team as they are the owners of it I guess.
</blockquote></details>

It's backward compatible. We are just improving error message here.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44805)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java` line 192 at r1](https://reviewable.io/reviews/harness/harness-core/44805#-NPvQUx7-qX485igmMc-:-NPvYoEfAXTVfjxDZjsu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b41128ddb1c5f8bcaf02fe2baaf0854ae7c8c32f/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L192)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

dont hard code the value like this
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java` line 179 at r2](https://reviewable.io/reviews/harness/harness-core/44805#-NPvX-V45QsT8VAx8c48:-NPvYmXH-hTZZBYsLDDW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/07003cc368a54866dd97905d725441c6cb808e0c/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L179)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please use capital letter variables for constants.
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java` line 192 at r2](https://reviewable.io/reviews/harness/harness-core/44805#-NPvXJzo1sjm7kVj0tmU:-NPvYnmq2y29PForwDmx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/07003cc368a54866dd97905d725441c6cb808e0c/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L192)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

It's backward compatible. We are just improving error message here.
</blockquote></details>

Done.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44805)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java` line 192 at r2](https://reviewable.io/reviews/harness/harness-core/44805#-NPvXJzo1sjm7kVj0tmU:-NPvYuic0mHviuJT1AXv:bctl3pn) ([raw file](https://github.com/harness/harness-core/blob/07003cc368a54866dd97905d725441c6cb808e0c/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L192)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

yes @mohitg0795 it is backward compatible

**Review by utkarshchoubey-harness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44805#-:-NPvZ-5J1vqhRfSldFck:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44805)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44805)* status: :shipit: complete! ✓

**Review by vivekkarnatiharness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44805)* status: :shipit: complete! ✓

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44805)* status: :shipit: complete! ✓

**Pull request merged**
