### PR TITLE
fix: [PL-43038]: Corrected query to fetch CG only users

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
After introduction of accountLevelMap, the CG/NG filter was getting applied after the DB call. It had the following 2 issues-
1. It resulted into consistency between total count of users being returned vs total user records being fetched in CG.
2. It broke pagination on CG users list page.
Since, accountLevelMap is now GA'ed across all prod clusters, this PR adds it to the mongo query, so that both the above issues are addressed.

Testing-
1. On CG users page, the total count of users, should match the actual number of users returned in the list response.
2. Pagination should work properly.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55846)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger uts

**Review by sahibaHarness — APPROVED** [review]
LGTM

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Comment by pbarapatre10** [comment]
Adding comment from slack here for reference: 

The changes seem correct as earlier even when in API the requested limit was ‘50’, not 50 users were returned as they were getting filtered from the result list. However there are few observations :
- In [next few lines](https://github.com/harness/harness-core/blob/df76977ce6eff8d4149774497f67f7a80fdeb33c/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L4357) we are again filtering the queried results, which becomes redundant after this change
- The query is using ‘userAccountLevelDataMap’ nested fields, and this query won’t use the index any more (earlier the index would be getting used), so the first load of CG ‘Access Management’ --> ‘Users’ will be slow, and subsequent users list loading will be slow as well.

**Pull request merged**
