### PR TITLE
feat: [PIE-2910]: Creating infra collection in ng-harness

### PR DESCRIPTION
**Pull request by prashantsharma04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31148)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by namanvermah — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31148)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[950-ng-core/src/main/java/io/harness/ng/core/infraStructureDefinition/beans/InfraStructureDefinitionEntity.java, line 40 at r1](https://reviewable.io/reviews/harness/harness-core/31148#-MxDbJC15dfsYOqaUnRs:-MxDbJC15dfsYOqaUnRt:b30pfb2) ([raw file](https://github.com/harness/harness-core/blob/11768f90d56e4922bfa7236d1e347c5296284509/950-ng-core/src/main/java/io/harness/ng/core/infraStructureDefinition/beans/InfraStructureDefinitionEntity.java#L40)):*
> ```Java
>     return ImmutableList.<MongoIndex>builder()
>         .add(CompoundMongoIndex.builder()
>                  .name("unique_accountId_organizationIdentifier_projectIdentifier_infraIdentifier")
> ```

should have env id

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31148)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[950-ng-core/src/main/java/io/harness/ng/core/infraStructureDefinition/beans/InfraStructureDefinitionEntity.java, line 40 at r1](https://reviewable.io/reviews/harness/harness-core/31148#-MxDbJC15dfsYOqaUnRs:-MxDfZyJAndtH2T8kRev:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/11768f90d56e4922bfa7236d1e347c5296284509/950-ng-core/src/main/java/io/harness/ng/core/infraStructureDefinition/beans/InfraStructureDefinitionEntity.java#L40)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

should have env id
</blockquote></details>

Done.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31148#-:-MxDs5jPEJgenw93Nj6n:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request closed without merging**
