### PR TITLE
fix: [CDS-46390]: Added hints and explanation.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40100)

### CODE REVIEW

**Review by namantalaycha10 — APPROVED** [review]

**Review by namantalaycha10 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40100)* status: :shipit: complete! ✓

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40100)* status: 1. unresolved discussions. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/k8s/kustomize/KustomizeTaskHelperTest.java` line 196 at r1](https://reviewable.io/reviews/harness/harness-core/40100#-NGq2kmQDG_T_DnHfzzO-r1-196:-NGrFRKd9CLYJOU0si2n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c6c332efbee095e2355442cfcb8920141e9a3cbb/930-delegate-tasks/src/test/java/io/harness/delegate/k8s/kustomize/KustomizeTaskHelperTest.java#L196)):*
<details><summary><i>Previously, namantalaycha10 (Naman Talaycha) wrote…</i></summary><blockquote>

shouldn't in test also it should be  Kustomize Base Path
</blockquote></details>

Done.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40100)* status: 1. unresolved discussions.

**Review by GoelPratyush99 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40100)* status: 1. unresolved discussions.

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40100)* status: 1. unresolved discussions. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/k8s/kustomize/KustomizeTaskHelperTest.java` line 196 at r1](https://reviewable.io/reviews/harness/harness-core/40100#-NGq2kmQDG_T_DnHfzzO-r1-196:-NGtmlrJ5CFGiFTU6Jmo:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c6c332efbee095e2355442cfcb8920141e9a3cbb/930-delegate-tasks/src/test/java/io/harness/delegate/k8s/kustomize/KustomizeTaskHelperTest.java#L196)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done

**Review by GoelPratyush99 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40100#-:-NGtn6yY3gsI22RdB1wf:bnfp4nl)* status: 1. unresolved discussions.

**Review by namantalaycha10 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40100)* status: :shipit: complete! ✓

**Pull request merged**
