### PR TITLE
[fix]: [CDS-38398]: UpdateCorruptedEmptyClusterNameInstanceStatsMigration

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33782)

### CODE REVIEW

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33782)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/33782#-N3YRunC89aggY-TmGt0:-N3YRunD5_4DKpvQJxzv:bsa8qal) ([raw file](https://github.com/harness/harness-core/blob/7daaf143e46d8b1b4b4f619703259a06423f04e5/390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java#L97)):*
> ```Java
>             instanceStatService.aggregate(accountId, Instant.ofEpochMilli(FROM), Instant.ofEpochMilli(UNTIL));
>         for (InstanceStatsSnapshot statsSnapshot : instanceStats) {
>           List<Instance> instances = getInstances(accountId, statsSnapshot.getTimestamp());
> ```

the accountId used here should be coming from `statsSnapshot`
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/33782#-N3YU77T938w1gOHpqtU:-N3YU77T938w1gOHpqtV:b46xo2g) ([raw file](https://github.com/harness/harness-core/blob/7daaf143e46d8b1b4b4f619703259a06423f04e5/390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java#L104)):*
> ```Java
>               DEBUG_LINE, format("published instance event for %s", statsSnapshot.getTimestamp().toString())));
>           if (successful) {
>             usageMetricsEventPublisher.publishInstanceTimeSeries(
> ```

there is a possibility of a race condition here.
Publish the usageMetricsEvent after we've updated the data in InstanceStats mongo collection.



_Code quote:_
```Java
          if (successful) {
            usageMetricsEventPublisher.publishInstanceTimeSeries(
                accountId, statsSnapshot.getTimestamp().toEpochMilli(), instances);
          }
```
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/33782#-N3YTRpW8ZRxMoqx2Sqt:-N3YTRpW8ZRxMoqx2Squ:bqan4j9) ([raw file](https://github.com/harness/harness-core/blob/7daaf143e46d8b1b4b4f619703259a06423f04e5/390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java#L122)):*
> ```Java
>             if (updated >= INSTANCE_STATS_BATCH_SIZE) {
>               log.info(
>                   "Updated {} instance stats four account id {}: {}", updated, accountId, bulkWriteOperation.execute());
> ```

have this in a separate statement.
Avoid writing code logic as part of log statements. One tends to overlook log statements while reading through the code



_Code quote:_
```Java
bulkWriteOperation.execute()
```
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java` line 180 at r2](https://reviewable.io/reviews/harness/harness-core/33782#-N3YQwiiC9_yBmdLzxyA:-N3YQwiiC9_yBmdLzxyB:b-xl0hgn) ([raw file](https://github.com/harness/harness-core/blob/7daaf143e46d8b1b4b4f619703259a06423f04e5/390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java#L180)):*
> ```Java
>     try {
>       Query<Instance> containerFetchInstancesQuery = mongoPersistence.createQuery(Instance.class, excludeAuthority)
>                                                          .filter("accountId", accountId)
> ```

This has become a recurring logic being used many times, during migration/calculation of 'active instances' for a given point in time. Let us extract this method in a lower module  so it can be use everywhere.



_Code quote:_
```Java
      Query<Instance> containerFetchInstancesQuery = mongoPersistence.createQuery(Instance.class, excludeAuthority)
                                                         .filter("accountId", accountId)
                                                         .field("createdAt")
                                                         .lessThanOrEq(toTime.toEpochMilli());
      containerFetchInstancesQuery.and(
          containerFetchInstancesQuery.or(containerFetchInstancesQuery.criteria("isDeleted").equal(false),
              containerFetchInstancesQuery.criteria("deletedAt").greaterThanOrEq(toTime.toEpochMilli())));
```

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33782)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java` line 213 at r2](https://reviewable.io/reviews/harness/harness-core/33782#-N3YUvFI3uiw2d2xodks:-N3YUvFI3uiw2d2xodkt:bl0igp8) ([raw file](https://github.com/harness/harness-core/blob/7daaf143e46d8b1b4b4f619703259a06423f04e5/390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java#L213)):*
> ```Java
> 
>   private BasicDBList getAggregateCountDBList(List<AggregateCount> aggregateCounts) {
>     BasicDBList basicDBList = new BasicDBList();
> ```

rename. 
Always try to have a meaningful variable name.

**Comment by tchaurasiya** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/33782#-N3YU77T938w1gOHpqtU:-N3Z5Ao6DMkYT8fvqk9o:bvzrjcy) ([raw file](https://github.com/harness/harness-core/blob/7daaf143e46d8b1b4b4f619703259a06423f04e5/390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java#L104)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

there is a possibility of a race condition here.
Publish the usageMetricsEvent after we've updated the data in InstanceStats mongo collection.
</blockquote></details>

As discussed offline, in this method no interaction with mongo will happen.

**Comment by tchaurasiya** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/33782#-N3YTRpW8ZRxMoqx2Sqt:-N3Z6nl3D-CmEhrsnCAy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7daaf143e46d8b1b4b4f619703259a06423f04e5/390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java#L122)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

have this in a separate statement.
Avoid writing code logic as part of log statements. One tends to overlook log statements while reading through the code
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java` line 213 at r2](https://reviewable.io/reviews/harness/harness-core/33782#-N3YUvFI3uiw2d2xodks:-N3Z81eWEgCMS0sF36If:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7daaf143e46d8b1b4b4f619703259a06423f04e5/390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java#L213)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

rename. 
Always try to have a meaningful variable name.
</blockquote></details>

Done.

**Review by tchaurasiya — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33782)* status: 1 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/33782#-N3YRunC89aggY-TmGt0:-N3YslF48TNoCCq0Brc2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7daaf143e46d8b1b4b4f619703259a06423f04e5/390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java#L97)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

the accountId used here should be coming from `statsSnapshot`
</blockquote></details>

Done.



_Code quote:_
```Java
e> instances = getInstances(accountId, stats
```

**Comment by tchaurasiya** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java` line 180 at r2](https://reviewable.io/reviews/harness/harness-core/33782#-N3YQwiiC9_yBmdLzxyA:-N3Z99y80Tav4-rTgQX1:b8uhi7z) ([raw file](https://github.com/harness/harness-core/blob/7daaf143e46d8b1b4b4f619703259a06423f04e5/390-db-migration/src/main/java/io/harness/migrations/all/UpdateCorruptedEmptyClusterNameInstanceStatsMigration.java#L180)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

This has become a recurring logic being used many times, during migration/calculation of 'active instances' for a given point in time. Let us extract this method in a lower module  so it can be use everywhere.
</blockquote></details>

Need to hotfix it today, Marking it as todo for now.
(Just Don't wanna pull any unexpected kryo or dependency issue)

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33782)* status: :shipit: complete! ✓

**Review by namantalaycha10 — APPROVED** [review]
> Reviewed 1 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33782)* status: :shipit: complete! ✓

**Pull request merged**
