### PR TITLE
feat: [DEL-3521]: apis for delegate approval/rejection

### PR DESCRIPTION
**Pull request by arpit3107**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32520)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32520)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java` line 512 at r1](https://reviewable.io/reviews/harness/harness-core/32520#-N0eVWSX7J9jfAlp0cJj:-N0eVWSX7J9jfAlp0cJk:b-i7t178) ([raw file](https://github.com/harness/harness-core/blob/3e4c53fe4c79d45cb895780724a35612fdc30079/400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java#L512)):*
> ```Java
>   @AuthRule(permissionType = MANAGE_DELEGATES)
>   @ApiKeyAuthorized(permissionType = MANAGE_DELEGATES)
>   public RestResponse<Void> updateApprovalStatusUsingProfile(
> ```

Should we return Delegate object instead of void?



_Code quote:_
```Java
Void
```
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 991 at r1](https://reviewable.io/reviews/harness/harness-core/32520#-N0eVfdN-QWXIbtYcHBS:-N0eVfdN-QWXIbtYcHBT:b-s49epb) ([raw file](https://github.com/harness/harness-core/blob/3e4c53fe4c79d45cb895780724a35612fdc30079/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L991)):*
> ```Java
>       if (DelegateInstanceStatus.WAITING_FOR_APPROVAL.equals(currentDelegate.getStatus())) {
>         updateApprovalStatePerDelegate(currentDelegate, action);
>       }
> ```

What if status is not WAITING_FOR_APPROVAL ? we should return appropriate error message.
Here and same for above

**Comment by gaurav-jain1** [comment]
I only see APIs for approval, is rejection api coming as separate PR ?

**Review by arpit3107 — COMMENTED** [review]
No, in the body of request you can pass whether you want to approve or reject the delegates associated with a particular profile/token.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32520#-:-N0eYkdg8hgF6Z2-6Lcq:b-amg5b8)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java` line 512 at r1](https://reviewable.io/reviews/harness/harness-core/32520#-N0eVWSX7J9jfAlp0cJj:-N0eZ0-48zXY-dzYjX5i:bftac8g) ([raw file](https://github.com/harness/harness-core/blob/3e4c53fe4c79d45cb895780724a35612fdc30079/400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java#L512)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Should we return Delegate object instead of void?
</blockquote></details>

Multiple delegates can be attached to a particular profile/token. So, we cant send any particular response apart from success/failure. Also, if few delegates out of these delegates are already approved then those delegates should be again approved/rejected. These apis will work only for those delegates that are in WAITING_FOR_APPROVAL state.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 991 at r1](https://reviewable.io/reviews/harness/harness-core/32520#-N0eVfdN-QWXIbtYcHBS:-N0eZVtECPmQgbupxydq:b-7ax2lz) ([raw file](https://github.com/harness/harness-core/blob/3e4c53fe4c79d45cb895780724a35612fdc30079/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L991)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

What if status is not WAITING_FOR_APPROVAL ? we should return appropriate error message.
Here and same for above
</blockquote></details>

This shouldn't be an error. If some are WAITING_FOR_APPROVAL then approve/reject them and leave the rest as it is.

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32520)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java` line 512 at r1](https://reviewable.io/reviews/harness/harness-core/32520#-N0eVWSX7J9jfAlp0cJj:-N0edO-H-_Sh-2rmeCsY:b-f3y28p) ([raw file](https://github.com/harness/harness-core/blob/3e4c53fe4c79d45cb895780724a35612fdc30079/400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java#L512)):*
> NG_FOR_APPROVAL state.
But we should send some response, atleast delegateId(s) whose status got changed or something

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32520)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 965 at r2](https://reviewable.io/reviews/harness/harness-core/32520#-N0nvHNc19LBQVXyNIbu:-N0nvHNc19LBQVXyNIbv:b-sof288) ([raw file](https://github.com/harness/harness-core/blob/adf036b9e5d29b3d92b0460e67c8618d27a69ab0/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L965)):*
> ```Java
> 
>     if (currentDelegates.isEmpty()) {
>       throw new InvalidRequestException(format(
> ```

Instead of throwing exception we can say "0 delegate updated"



_Code quote:_
```Java
   throw new InvalidRequestException(format(
```
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 968 at r2](https://reviewable.io/reviews/harness/harness-core/32520#-N0nvTHzCJDxk2wqDRUh:-N0nvTI-AGEh5EEyT-ck:b-d8h7x9) ([raw file](https://github.com/harness/harness-core/blob/adf036b9e5d29b3d92b0460e67c8618d27a69ab0/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L968)):*
> ```Java
>           "Unable to fetch any delegate with accountId %s and delegateProfileId %s ", accountId, delegateProfileId));
>     }
>     List<String> idsOfUpdatedDelegates = new ArrayList<>();
> ```

Consider renaming to updateDelegates



_Code quote:_
```Java
dsOfUpdatedDelegates 
```
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 976 at r2](https://reviewable.io/reviews/harness/harness-core/32520#-N0nvsx-0sp7p_c5BTgy:-N0nvsx-0sp7p_c5BTgz:b-hmpmcx) ([raw file](https://github.com/harness/harness-core/blob/adf036b9e5d29b3d92b0460e67c8618d27a69ab0/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L976)):*
> ```Java
>     }
>     return new DelegateApprovalResponse(
>         isNotEmpty(idsOfUpdatedDelegates) ? DELEGATES_UPDATED_RESPONSE : NO_DELEGATES_UPDATED_RESPONSE,
> ```

No need to pass string argument here, you can construct it in DelegateApprovalResponse() ctor itself.



_Code quote:_
```Java
isNotEmpty(idsOfUpdatedDelegates) ? DELEGATES_UPDATED_RESPONSE : NO_DELEGATES_UPDATED_RESPONSE,
```
___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateApprovalResponse.java` line 12 at r2](https://reviewable.io/reviews/harness/harness-core/32520#-N0nvfsfC8jGDPPzhuyi:-N0nvfsfC8jGDPPzhuyj:bq90g7y) ([raw file](https://github.com/harness/harness-core/blob/adf036b9e5d29b3d92b0460e67c8618d27a69ab0/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateApprovalResponse.java#L12)):*
> ```Java
> @OwnedBy(HarnessTeam.DEL)
> public class DelegateApprovalResponse {
>   private final String responseMessage;
> ```

IMO in message we can number of delegates got update.
in case of error just say "0 delegate(s) updated"



_Code quote:_
```Java
String responseMessage;
```

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32520)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1029 at r2](https://reviewable.io/reviews/harness/harness-core/32520#-N0nwIh04Bh-wx0aXWY5:-N0nwIh04Bh-wx0aXWY6:bvo4lu4) ([raw file](https://github.com/harness/harness-core/blob/adf036b9e5d29b3d92b0460e67c8618d27a69ab0/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1029)):*
> ```Java
> 
>   @Override
>   public DelegateApprovalResponse rejectDelegatesUsingToken(String accountId, String delegateTokenName)
> ```

here, internally you can club this with approve method and pass action (approve/reject)



_Code quote:_
```Java
rejectDelegatesUsingToken
```

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32520)* status: 5 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java` line 512 at r1](https://reviewable.io/reviews/harness/harness-core/32520#-N0eVWSX7J9jfAlp0cJj:-N0o1gASCcjOmn1GymTd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3e4c53fe4c79d45cb895780724a35612fdc30079/400-rest/src/main/java/software/wings/resources/DelegateSetupResource.java#L512)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

> NG_FOR_APPROVAL state.
But we should send some response, atleast delegateId(s) whose status got changed or something
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 965 at r2](https://reviewable.io/reviews/harness/harness-core/32520#-N0nvHNc19LBQVXyNIbu:-N0o1iB-91fsNAJnDjUe:bhyy5pn) ([raw file](https://github.com/harness/harness-core/blob/adf036b9e5d29b3d92b0460e67c8618d27a69ab0/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L965)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Instead of throwing exception we can say "0 delegate updated"
</blockquote></details>

No, that would mislead in case user is sending wrong delegateProfileId. 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 968 at r2](https://reviewable.io/reviews/harness/harness-core/32520#-N0nvTHzCJDxk2wqDRUh:-N0o1tp81tu6egPbfUvg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/adf036b9e5d29b3d92b0460e67c8618d27a69ab0/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L968)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Consider renaming to updateDelegates
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 976 at r2](https://reviewable.io/reviews/harness/harness-core/32520#-N0nvsx-0sp7p_c5BTgy:-N0o1zaW52nbga372dBy:b-7sj4zz) ([raw file](https://github.com/harness/harness-core/blob/adf036b9e5d29b3d92b0460e67c8618d27a69ab0/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L976)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

No need to pass string argument here, you can construct it in DelegateApprovalResponse() ctor itself.
</blockquote></details>

Yes, so I am using constructor only.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1029 at r2](https://reviewable.io/reviews/harness/harness-core/32520#-N0nwIh04Bh-wx0aXWY5:-N0o22l46UyRje2c6Xap:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/adf036b9e5d29b3d92b0460e67c8618d27a69ab0/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1029)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

here, internally you can club this with approve method and pass action (approve/reject)
</blockquote></details>

Done.
___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateApprovalResponse.java` line 12 at r2](https://reviewable.io/reviews/harness/harness-core/32520#-N0nvfsfC8jGDPPzhuyi:-N0o2ACF8QJwMJz_0YHW:b-qcpk3k) ([raw file](https://github.com/harness/harness-core/blob/adf036b9e5d29b3d92b0460e67c8618d27a69ab0/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateApprovalResponse.java#L12)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

IMO in message we can number of delegates got update.
in case of error just say "0 delegate(s) updated"
</blockquote></details>

Error will mislead that he is passing correct set of values but all delegates are in approved/rejected state.

**Review by gaurav-jain1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32520)* status: 5 file(s) to review. 6. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 965 at r2](https://reviewable.io/reviews/harness/harness-core/32520#-N0nvHNc19LBQVXyNIbu:-N0oUYB93Ht_FzWVmKq9:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/adf036b9e5d29b3d92b0460e67c8618d27a69ab0/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L965)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

No, that would mislead in case user is sending wrong delegateProfileId. 
</blockquote></details>

ok

**Comment by arpit3107** [comment]
trigger messagecheck

**Comment by arpit3107** [comment]
trigger messagecheck

**Pull request merged**
