### PR TITLE
feat: [PL-30779]: Environment Group Outbox Event Handler

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
Add outbox event handler for environment group CRUD operations. Outbox events were already saved in the database were not being processed because of the missing handler
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42350)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42350)* status: 7 file(s) to review. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/core/outbox/EnvironmentGroupOutboxEventHandlerTest.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/42350#-NLH2A-b-xIUWbr8uuKH:-NLH2A-b-xIUWbr8uuKI:b-gr1ae1) ([raw file](https://github.com/harness/harness-core/blob/3cdbeb82155a100ae2d8cc96daf2a03965199eb1/120-ng-manager/src/test/java/io/harness/ng/core/outbox/EnvironmentGroupOutboxEventHandlerTest.java#L56)):*
> ```Java
> import org.mockito.MockitoAnnotations;
> 
> public class EnvironmentGroupOutboxEventHandlerTest extends CategoryTest {
> ```

nit: should we even publish outbox event for envGroup if we are not seeing any usage for this crud event to be utilised by others? as I think its currently used only by cd service and no async operation is needed? when needed in future then we can add? why waste resources?

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42350)* status: 7 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/core/outbox/EnvironmentGroupOutboxEventHandlerTest.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/42350#-NLH2A-b-xIUWbr8uuKH:-NLJlTuG1U0FyAOle1c8:b-9mus57) ([raw file](https://github.com/harness/harness-core/blob/3cdbeb82155a100ae2d8cc96daf2a03965199eb1/120-ng-manager/src/test/java/io/harness/ng/core/outbox/EnvironmentGroupOutboxEventHandlerTest.java#L56)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: should we even publish outbox event for envGroup if we are not seeing any usage for this crud event to be utilised by others? as I think its currently used only by cd service and no async operation is needed? when needed in future then we can add? why waste resources?
</blockquote></details>

Yes, outbox event is used for audit trails.

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42350)* status: 7 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/core/outbox/EnvironmentGroupOutboxEventHandlerTest.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/42350#-NLH2A-b-xIUWbr8uuKH:-NLJlcaS-v-8ZpBvI57N:b5pwbgi) ([raw file](https://github.com/harness/harness-core/blob/3cdbeb82155a100ae2d8cc96daf2a03965199eb1/120-ng-manager/src/test/java/io/harness/ng/core/outbox/EnvironmentGroupOutboxEventHandlerTest.java#L56)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Yes, outbox event is used for audit trails.
</blockquote></details>

its processed by platform service

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42350)* status: 7 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42350)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42350)* status: :shipit: complete! ✓

**Pull request merged**
