### PR TITLE
[feat]: [PIE-6086]: Add node execution id to graph for parallel blocks

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39419)

### CODE REVIEW

**Comment by AnshuH** [comment]
trigger ti1 ti3 ti4

**Comment by tusharharness** [comment]
trigger sonar

**Comment by tusharharness** [comment]
trigger sonar

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OrchestrationUtils.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/39419#-NFqbSmL1bn0yLWVahSX:-NFqbSmL1bn0yLWVahSY:b-vses1d) ([raw file](https://github.com/harness/harness-core/blob/f964522812a751bb5582e41fb5383bb02b6947e1/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OrchestrationUtils.java#L63)):*
> ```Java
>     StepType currentStepType = Objects.requireNonNull(AmbianceUtils.getCurrentStepType(nodeExecution.getAmbiance()));
>     return currentStepType.getStepCategory() == StepCategory.STAGE
>         || currentStepType.getStepCategory() == StepCategory.FORK;
> ```

This can take parallel at step level too, can we have this for stage level only by checking if parent is stages?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39419)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39419)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OrchestrationUtils.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/39419#-NFqbSmL1bn0yLWVahSX:-NFtcGRw7j3ygYFOdD5y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f964522812a751bb5582e41fb5383bb02b6947e1/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OrchestrationUtils.java#L63)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

This can take parallel at step level too, can we have this for stage level only by checking if parent is stages?
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39419)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by namanvermah** [comment]
trigger ft1

**Comment by namanvermah** [comment]
trigger ft1

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39419)* status: :shipit: complete! ✓

**Pull request merged**
