### PR TITLE
[fix]: [PL-32206]: In Access control service, fixed migration for populating name and email which is sourced from CG Db.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
In Access control service, fixed UserInfo Migration for populating name and email which is sourced from CG Db.
The migration was failing as UserClientModule was not imported in Access Control and so Guice was not able to provide the instance.

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45688)

### CODE REVIEW

**Review by ankit-harness — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45688)* status: 5 file(s) to review. 1 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserInfoMigration.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/45688#-NRbD52v9W633s_FFDte:-NRbD52wBTfq4GPny7Hz:b-otabxv) ([raw file](https://github.com/harness/harness-core/blob/25bb64a83c643d52650d55e5bd2be0f8d84eebee/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserInfoMigration.java#L30)):*
> ```Java
> @Singleton
> @OwnedBy(HarnessTeam.PL)
> public class UserInfoMigration implements NGMigration {
> ```

We will need to register this migration

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45688)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserInfoMigration.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/45688#-NRbD52v9W633s_FFDte:-NRbT-CHEd0ejgwFxKLZ:bkh2rc5) ([raw file](https://github.com/harness/harness-core/blob/25bb64a83c643d52650d55e5bd2be0f8d84eebee/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserInfoMigration.java#L30)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We will need to register this migration
</blockquote></details>

It was already registered in AccessControlMongoBackgroundMigrationDetails.

**Comment by Jimit09Gandhi** [comment]
trigger messagecheck

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45688)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by Jimit09Gandhi** [comment]
trigger ut0

**Comment by Jimit09Gandhi** [comment]
trigger ut2

**Comment by Jimit09Gandhi** [comment]
trigger ut4

**Comment by Jimit09Gandhi** [comment]
trigger ut7

**Comment by Jimit09Gandhi** [comment]
trigger ut8

**Comment by Jimit09Gandhi** [comment]
trigger ut7

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45688)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`access-control/config/config.yml` line 277 at r2](https://reviewable.io/reviews/harness/harness-core/45688#-NRgSmcJ95Z8qa7EHbAY:-NRgSmcJ95Z8qa7EHbAZ:b-jvgj9c) ([raw file](https://github.com/harness/harness-core/blob/adcaa487983a72731d7a2d1ebdd48793c11e88f3/access-control/config/config.yml#L277)):*
> ```YAML
>   syncFeaturesToCF: false
> 
> cgUserClientConfig:
> ```

Let's not add it. Can we reuse account config. User and Account both reside in CG manager.

Our configs will explode this way. We need to cleanup access control configs.



_Code quote:_
```YAML
featureFlagClientConfiguration
```

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45688)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/config/config.yml` line 277 at r2](https://reviewable.io/reviews/harness/harness-core/45688#-NRgSmcJ95Z8qa7EHbAY:-NRg_scqClVv36nkW6nb:bifsv5w) ([raw file](https://github.com/harness/harness-core/blob/adcaa487983a72731d7a2d1ebdd48793c11e88f3/access-control/config/config.yml#L277)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Let's not add it. Can we reuse account config. User and Account both reside in CG manager.

Our configs will explode this way. We need to cleanup access control configs.
</blockquote></details>

sure @Ankit Singhal I felt the same. we should have only other service base urls. Using account Client for now.
Created https://harness.atlassian.net/browse/PL-32281 for cleanup.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45688#-:-NRl8_ljEZd9g5PXK9bR:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45688)* status: :shipit: complete! ✓

**Pull request merged**
