### PR TITLE
fix: [CDS-80869]: support runtime inputs for stackNames, change outpu…

### PR DESCRIPTION
**Pull request by tmacari-harness**
fix: [CDS-80869]: support runtime inputs for stackNames, change outputs logic

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-80869]: https://harness.atlassian.net/browse/CDS-80869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53846)

### CODE REVIEW

**Comment by tmacari-harness** [comment]
trigger uts

**Comment by tmacari-harness** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53846)* status: 15 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/awscdk/AwsCdkDeployStep.java` line 156 at r2](https://reviewable.io/reviews/harness/harness-core/53846#-Ng44KEoCvBVdvxqLGGq:-Ng4FhvS1QhqyKdM6pS4:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a2a4e90c70d33c8175b054dcbd52a1b97f8e6ccf/125-cd-nextgen/src/main/java/io/harness/cdng/provision/awscdk/AwsCdkDeployStep.java#L156)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor: cdkOutput could be constant.
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/awscdk/AwsCdkSynthStep.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/53846#-Ng46LUuElrlKBUvbpyH:-Ng4Bq7a6GrN1ZyKNGC8:b-uds9ec) ([raw file](https://github.com/harness/harness-core/blob/a2a4e90c70d33c8175b054dcbd52a1b97f8e6ccf/125-cd-nextgen/src/main/java/io/harness/cdng/provision/awscdk/AwsCdkSynthStep.java#L91)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

we want to have only the stack name in step output, not entire file name
</blockquote></details>

extracted to AwsCdkHelper, when there wii be other steps using it.. it could be extracted to a more common class.

**Comment by tmacari-harness** [comment]
trigger uts

**Comment by tmacari-harness** [comment]
trigger uts

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53846#-:-Ng4SQf57XUDNQUuJvC9:bnfp4nl)* status: 15 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/awscdk/AwsCdkHelper.java` line 168 at r2](https://reviewable.io/reviews/harness/harness-core/53846#-Ng45tQ0BhhWTl0Snqh8:-Ng4RxVnDga-GQHNTJrf:b-smtlin) ([raw file](https://github.com/harness/harness-core/blob/a2a4e90c70d33c8175b054dcbd52a1b97f8e6ccf/125-cd-nextgen/src/main/java/io/harness/cdng/provision/awscdk/AwsCdkHelper.java#L168)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

For terraform we do the same
</blockquote></details>

In that case, you should log the exception.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 9 of 14 files at r1, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53846)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/awscdk/AwsCdkDeployStepInfo.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/53846#-NgHztQ87Ur1QByXvheZ:-NgHztQ87Ur1QByXvhe_:b-qont7r) ([raw file](https://github.com/harness/harness-core/blob/2a3ed771297b1e836ff01ecc4cd5bd2843666cad/125-cd-nextgen/src/main/java/io/harness/cdng/provision/awscdk/AwsCdkDeployStepInfo.java#L59)):*
> ```Java
>   // For Visitor Framework Impl
>   @Getter(onMethod_ = { @ApiModelProperty(hidden = true) }) @ApiModelProperty(hidden = true) String metadata;
>   @YamlSchemaTypes({runtime})
> ```

just checking if this supports expression as well ?

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53846)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/awscdk/AwsCdkDeployStepInfo.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/53846#-NgHztQ87Ur1QByXvheZ:-NgI-edqExqwmGCXmbjB:b-qeugku) ([raw file](https://github.com/harness/harness-core/blob/2a3ed771297b1e836ff01ecc4cd5bd2843666cad/125-cd-nextgen/src/main/java/io/harness/cdng/provision/awscdk/AwsCdkDeployStepInfo.java#L59)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

just checking if this supports expression as well ?
</blockquote></details>

each array element can be expression but not the entire list

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 9 of 14 files at r1, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53846)* status: :shipit: complete! ✓

**Comment by tmacari-harness** [comment]
trigger review

**Pull request merged**
