### PR TITLE
feat: [CDS-41698]: Command Step: Handle Service Variables and Service…

### PR DESCRIPTION
**Pull request by bojanmicovic**
… overrides as command step variables

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36573)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36573)

**Comment by bojanmicovic** [comment]
trigger messagecheck

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36573)* status: 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/utils/CommandStepUtils.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/36573#-NA4_Hnm6ZpB8qqmY8KA:-NA4_Hnm6ZpB8qqmY8KB:b-i4f3o5) ([raw file](https://github.com/harness/harness-core/blob/0015ee702b319bde4ccf358c0b2a355a978eecf3/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/utils/CommandStepUtils.java#L43)):*
> ```Java
>   public static final String HARNESS_BACKUP_PATH = "HARNESS_BACKUP_PATH";
>   public static final String HARNESS_RUNTIME_PATH = "HARNESS_RUNTIME_PATH";
>   public static final String HARNESS_STAGING_PATH = "HARNESS_STAGING_PATH";
> ```

those constants can be removed also

**Comment by bojanmicovic** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/utils/CommandStepUtils.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/36573#-NA4_Hnm6ZpB8qqmY8KA:-NA4b6L12ROPG4Otx8Yt:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/0015ee702b319bde4ccf358c0b2a355a978eecf3/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/utils/CommandStepUtils.java#L43)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

those constants can be removed also
</blockquote></details>

Done

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36573)* status: :shipit: complete! ✓

**Pull request merged**
