### PR TITLE
feat: [DEL-3998]: send same jwt for 25 mins

### PR DESCRIPTION
**Pull request by arpit3107**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33376)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33376)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 134 at r1](https://reviewable.io/reviews/harness/harness-core/33376#-N2VWG9P97yrWsKeoMMU:-N2VWG9P97yrWsKeoMMV:b-bmgmvm) ([raw file](https://github.com/harness/harness-core/blob/a51a3d7d388ba55f64d6192f138e4ed44b572854/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L134)):*
> ```Java
>       if (System.currentTimeMillis() > jwtClaimsSet.getExpirationTime().getTime()) {
>         log.error(
>             "Arpit: Delegate {} is using EXPIRED delegate token. DelegateId: {}", jwtClaimsSet.getIssuer(), delegateId);
> ```

git reset --hard on this file



_Code quote:_
```Java
Arpit:
```
___
*[`980-commons/src/main/java/io/harness/security/TokenGenerator.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/33376#-N2VXVAhC-N2V-UbG0nY:-N2VXVAhC-N2V-UbG0nZ:b-tbti2f) ([raw file](https://github.com/harness/harness-core/blob/a51a3d7d388ba55f64d6192f138e4ed44b572854/980-commons/src/main/java/io/harness/security/TokenGenerator.java#L44)):*
> ```Java
>   private static final TemporalAmount EXP_DURATION = Duration.ofMinutes(30);
>   private long expiryTimeOfLastJWT;
>   private String lastEncryptedJWT;
> ```

These variables need to be protected via read write lock, since multiple threads can access it.



_Code quote:_
```Java
  private long expiryTimeOfLastJWT;
  private String lastEncryptedJWT;
```
___
*[`980-commons/src/main/java/io/harness/security/TokenGenerator.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/33376#-N2VXFjQ8LCbDP59Z-kU:-N2VXFjQ8LCbDP59Z-kV:b-a2iif7) ([raw file](https://github.com/harness/harness-core/blob/a51a3d7d388ba55f64d6192f138e4ed44b572854/980-commons/src/main/java/io/harness/security/TokenGenerator.java#L60)):*
> ```Java
> 
>   public String getToken(String audience, String issuer) {
>     // keep sending the last EncryptedJWT for next 25 mins
> ```

Please also specify why we are sending for 25min. as we wanted to keep some buffer so that when request reach to manager, jwt remains valid.



_Code quote:_
```Java
keep sending the last EncryptedJWT for next 25 mins
```
___
*[`980-commons/src/main/java/io/harness/security/TokenGenerator.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/33376#-N2VXDrI34Gvt6Ps198E:-N2VXDrI34Gvt6Ps198F:bd6tg) ([raw file](https://github.com/harness/harness-core/blob/a51a3d7d388ba55f64d6192f138e4ed44b572854/980-commons/src/main/java/io/harness/security/TokenGenerator.java#L62)):*
> ```Java
>     // keep sending the last EncryptedJWT for next 25 mins
>     if (lastEncryptedJWT != null && expiryTimeOfLastJWT > System.currentTimeMillis() + TimeUnit.MINUTES.toMillis(5)) {
>       log.info("Arpit: Sending last JWT {}", lastEncryptedJWT);
> ```

log.debug



_Code quote:_
```Java
log.info(
```

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33376)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/security/TokenGenerator.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/33376#-N2VXn_dBAvZRgfLpYaN:-N2VXn_dBAvZRgfLpYaO:bz0urzn) ([raw file](https://github.com/harness/harness-core/blob/a51a3d7d388ba55f64d6192f138e4ed44b572854/980-commons/src/main/java/io/harness/security/TokenGenerator.java#L42)):*
> ```Java
> @Singleton
> public class TokenGenerator {
>   private static final TemporalAmount EXP_DURATION = Duration.ofMinutes(30);
> ```

consider having const variable, EXPIRY_FOR_CACHED_JWT = 25s



_Code quote:_
```Java
 EXP_DURATION
```

**Review by mdmilic — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33376)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/security/TokenGenerator.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/33376#-N2VXVAhC-N2V-UbG0nY:-N2WVo-0DOvgU08g13NA:b-kp9h0x) ([raw file](https://github.com/harness/harness-core/blob/a51a3d7d388ba55f64d6192f138e4ed44b572854/980-commons/src/main/java/io/harness/security/TokenGenerator.java#L44)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

These variables need to be protected via read write lock, since multiple threads can access it.
</blockquote></details>

Hey @gaurav-jain1 I think it would be ok to avoid the locking if possible, since if another thread picks up old JWT token, that's still a valid token that will be accepted by manager, but also chances for it to happen are minimal, so we should be good.

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33376)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/security/TokenGenerator.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/33376#-N2VXVAhC-N2V-UbG0nY:-N2XD2lmCh1s3t7ZOIkj:b-uopgk8) ([raw file](https://github.com/harness/harness-core/blob/a51a3d7d388ba55f64d6192f138e4ed44b572854/980-commons/src/main/java/io/harness/security/TokenGenerator.java#L44)):*
> will be accepted by manage
Consider this at scale, for example if each delegate create 4 JWT ( 2 for delegate and 2 for watcher), and if there are 2k delegates out there, than on manager cache will increase by 4x ie we need to cache 8k tokens.

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33376)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/security/TokenGenerator.java` line 103 at r3](https://reviewable.io/reviews/harness/harness-core/33376#-N2XTeDH7_r2Yj5huGAN:-N2XTeDJ0Klfy_DuB6e0:b-k8x53y) ([raw file](https://github.com/harness/harness-core/blob/a97e0951040c7193f422ccc0e7e972ec842adb36/980-commons/src/main/java/io/harness/security/TokenGenerator.java#L103)):*
> ```Java
> 
>       log.info("Arpit: Sending new JWT {}", lastEncryptedJWT);
>       log.info("Arpit: Exception", new Exception());
> ```

remove these loggings



_Code quote:_
```Java
      log.info("Arpit: Sending new JWT {}", lastEncryptedJWT);
      log.info("Arpit: Exception", new Exception());
```

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33376)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/security/TokenGenerator.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/33376#-N2VXVAhC-N2V-UbG0nY:-N2_Jv9q5rPiOmvNIj03:b-q19o45) ([raw file](https://github.com/harness/harness-core/blob/a51a3d7d388ba55f64d6192f138e4ed44b572854/980-commons/src/main/java/io/harness/security/TokenGenerator.java#L44)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

> will be accepted by manage
Consider this at scale, for example if each delegate create 4 JWT ( 2 for delegate and 2 for watcher), and if there are 2k delegates out there, than on manager cache will increase by 4x ie we need to cache 8k tokens.
</blockquote></details>

I know, but my understanding is that this is not easily reproducible, so it's not fair to say it would be 4x. Also, you need to store one set of tokens anyway so worst case would be 2x. Worst case would happen if it's always reproducible and then I would agree that we should sync it, but there's only very narrow timeframe for duplicate to happen. With watchers rate of requests I would say almost never with delegates very rarely. I would guestimate it probably to single digit % if not less which is not terrible increase and I think we abuse locks so would like to avoid it if possible.

**Review by gaurav-jain1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33376)* status: 2 file(s) to review. 1. unresolved discussions. 

___
*[`980-commons/src/main/java/io/harness/security/TokenGenerator.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/33376#-N2VXVAhC-N2V-UbG0nY:-N2bgeKL4kt4uw3Ovur9:b-5peeln) ([raw file](https://github.com/harness/harness-core/blob/a51a3d7d388ba55f64d6192f138e4ed44b572854/980-commons/src/main/java/io/harness/security/TokenGenerator.java#L44)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I know, but my understanding is that this is not easily reproducible, so it's not fair to say it would be 4x. Also, you need to store one set of tokens anyway so worst case would be 2x. Worst case would happen if it's always reproducible and then I would agree that we should sync it, but there's only very narrow timeframe for duplicate to happen. With watchers rate of requests I would say almost never with delegates very rarely. I would guestimate it probably to single digit % if not less which is not terrible increase and I think we abuse locks so would like to avoid it if possible.
</blockquote></details>

Even if its a rare possibility, I would choose to prefer burn Delegate resource instead of manager. Also this lock will come into play once in 25min, which is reasonable. 
Moreover we are dealing with 2 variables here: Expiry time and cached jwt, things can go wrong if more than one thread work on them together.

**Review by gaurav-jain1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33376)* status: 2 file(s) to review. 1. unresolved discussions.

**Comment by dgarg-harness** [comment]
trigger messagecheck

**Comment by arpit3107** [comment]
trigger ti3

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33376)* status: 1. unresolved discussions.

**Review by gaurav-jain1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33376)* status: :shipit: complete! ✓

___
*[`980-commons/src/main/java/io/harness/security/TokenGenerator.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/33376#-N2VXVAhC-N2V-UbG0nY:-N2jASvQ7f7xKF6TpEg4:bkx3zbo) ([raw file](https://github.com/harness/harness-core/blob/a51a3d7d388ba55f64d6192f138e4ed44b572854/980-commons/src/main/java/io/harness/security/TokenGenerator.java#L44)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Even if its a rare possibility, I would choose to prefer burn Delegate resource instead of manager. Also this lock will come into play once in 25min, which is reasonable. 
Moreover we are dealing with 2 variables here: Expiry time and cached jwt, things can go wrong if more than one thread work on them together.
</blockquote></details>

Let's do this for now, we can change later if we seen side-effects.

**Comment by arpit3107** [comment]
trigger compile

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33376)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33376)* status: :shipit: complete! ✓

**Pull request merged**
