### PR TITLE
techdebt: [PIE-2978]: Store offsets in redis and stream changes into redis streams

### PR DESCRIPTION
**Pull request by shalini-agr**
…hangeConsumer

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31262)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger messagecheck

**Comment by shalini-agr** [comment]
trigger messagecheck

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31262)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[958-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java, line 43 at r1](https://reviewable.io/reviews/harness/harness-core/31262#-MxdNDfN2gHg2Dg0eSPX:-MxdNDfN2gHg2Dg0eSPY:b-e1zw4s) ([raw file](https://github.com/harness/harness-core/blob/74b9c560a6f5d310e7482298f137710a72a377e3/958-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java#L43)):*
> ```Java
> 
>   protected DebeziumEngine<ChangeEvent<String, String>> getEngine(Properties props) {
>     return DebeziumEngine.create(Json.class).using(props).notifying(new RedisStreamChangeConsumer(redisAdress)).build();
> ```

We should make this configurable based on the passed props 



_Code quote:_
```Java
new RedisStreamChangeConsumer(redisAdress
```

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31262)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[958-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java, line 43 at r1](https://reviewable.io/reviews/harness/harness-core/31262#-MxdNDfN2gHg2Dg0eSPX:-MxdQDsNDDS_uEIjazsL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/74b9c560a6f5d310e7482298f137710a72a377e3/958-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java#L43)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

We should make this configurable based on the passed props 
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger ti2

**Review by hextechpal — APPROVED** [review]
> Reviewed 4 of 8 files at r3, 17 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31262)* status: 22 file(s) to review. 1 of 2 approvals obtained. 

___
*[958-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java, line 43 at r1](https://reviewable.io/reviews/harness/harness-core/31262#-MxdNDfN2gHg2Dg0eSPX:-Mxhn5dZ0mofUqukLFTb:b-bg7m69) ([raw file](https://github.com/harness/harness-core/blob/74b9c560a6f5d310e7482298f137710a72a377e3/958-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java#L43)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant here what sort of consumer we need to create. We will take this up later though. Right now approving it

**Comment by shalini-agr** [comment]
trigger ti0, ti4

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 1 of 8 files at r3, 4 of 17 files at r4, 31 of 32 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31262)* status: 33 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
___
*[952-debezium-engine/src/main/java/io/harness/debezium/RedisStreamChangeConsumer.java, line 104 at r7](https://reviewable.io/reviews/harness/harness-core/31262#-MxnnVSl8hPYSk0Sst7D:-MxnnVSnCn9VWzNV-agb:b-h0k9ak) ([raw file](https://github.com/harness/harness-core/blob/36ea716012edfd3a0d39d077a9693a67f1660e6d/952-debezium-engine/src/main/java/io/harness/debezium/RedisStreamChangeConsumer.java#L104)):*
> ```Java
>                     .build();
>             Message message = Message.newBuilder().setData(debeziumChangeEvent.toByteString()).build();
>             RedisProducer.of(destination, redisson, 10000, "debezium", "").send(message);
> ```

Should we replace this with one redisProducer which we could create in the constructor rather than creating new every time?

**Comment by sahilhindwani-harness** [comment]
___
*[952-debezium-engine/src/main/java/io/harness/debezium/RedisStreamChangeConsumer.java, line 109 at r7](https://reviewable.io/reviews/harness/harness-core/31262#-Mxno9tsCwjY-mdnRlfR:-Mxno9tsCwjY-mdnRlfS:bb3ypb3) ([raw file](https://github.com/harness/harness-core/blob/36ea716012edfd3a0d39d077a9693a67f1660e6d/952-debezium-engine/src/main/java/io/harness/debezium/RedisStreamChangeConsumer.java#L109)):*
> ```Java
>           for (ChangeEvent<String, String> record : batch) {
>             try {
>               committer.markProcessed(record);
> ```

Should we mark them as processed in the above loop as soon as we sent an event?

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 1 of 10 files at r1, 1 of 8 files at r3, 5 of 17 files at r4, 31 of 32 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31262)* status: 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
___
*[952-debezium-engine/src/main/java/io/harness/debezium/RedisStreamChangeConsumer.java, line 109 at r7](https://reviewable.io/reviews/harness/harness-core/31262#-Mxno9tsCwjY-mdnRlfR:-MxoIHRK0uNkFjPvFqyr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/36ea716012edfd3a0d39d077a9693a67f1660e6d/952-debezium-engine/src/main/java/io/harness/debezium/RedisStreamChangeConsumer.java#L109)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should we mark them as processed in the above loop as soon as we sent an event?
</blockquote></details>

Done.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31262)* status: 20 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[952-debezium-engine/src/main/java/io/harness/debezium/RedisStreamChangeConsumer.java, line 104 at r7](https://reviewable.io/reviews/harness/harness-core/31262#-MxnnVSl8hPYSk0Sst7D:-Mxs0PWp7JJYJIuT3YQu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/36ea716012edfd3a0d39d077a9693a67f1660e6d/952-debezium-engine/src/main/java/io/harness/debezium/RedisStreamChangeConsumer.java#L104)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should we replace this with one redisProducer which we could create in the constructor rather than creating new every time?
</blockquote></details>

Done.
___
*[958-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java, line 43 at r1](https://reviewable.io/reviews/harness/harness-core/31262#-MxdNDfN2gHg2Dg0eSPX:-Mxs0Odb3iU2Gl6tV7pM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/74b9c560a6f5d310e7482298f137710a72a377e3/958-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java#L43)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

I meant here what sort of consumer we need to create. We will take this up later though. Right now approving it
</blockquote></details>

Done.

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 18 of 32 files at r6, 3 of 5 files at r8, 1 of 1 files at r9, 13 of 13 files at r10, 3 of 3 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31262)* status: 23 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[project/main_maven_install.json, line 4 at r10](https://reviewable.io/reviews/harness/harness-core/31262#-MxsPUBNDvVaylEt-TYX:-MxsPUBNDvVaylEt-TYY:boe0188) ([raw file](https://github.com/harness/harness-core/blob/d24c4e1bc5accd0eef61a1500bd11a323a85c3d2/project/main_maven_install.json#L4)):*
> ```JSON
>     "dependency_tree": {
>         "__AUTOGENERATED_FILE_DO_NOT_MODIFY_THIS_FILE_MANUALLY": "THERE_IS_NO_DATA_ONLY_ZUUL",
>         "__INPUT_ARTIFACTS_HASH": 1179043483,
> ```

why has this file changes i did not see we added any libraries?
___
*[952-debezium-engine/src/main/java/io/harness/debezium/DebeziumConfiguration.java, line 85 at r12](https://reviewable.io/reviews/harness/harness-core/31262#-MxsObcM-Yj83C87_qFl:-MxsObcM-Yj83C87_qFm:b-176pqq) ([raw file](https://github.com/harness/harness-core/blob/f1d324aa4b234b9b81b07ef21f755b45d41f2470/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumConfiguration.java#L85)):*
> ```Java
>   }
> 
>   public static RedissonClient getRedissonClient(DebeziumConfig debeziumConfig) {
> ```

this should not be done here
___
*[952-debezium-engine/src/main/java/io/harness/debezium/DebeziumConfiguration.java, line 91 at r12](https://reviewable.io/reviews/harness/harness-core/31262#-MxsOgwX314H5Yn61RmY:-MxsOgwX314H5Yn61RmZ:bdkx4tk) ([raw file](https://github.com/harness/harness-core/blob/f1d324aa4b234b9b81b07ef21f755b45d41f2470/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumConfiguration.java#L91)):*
> ```Java
>   }
> 
>   public static Map<String, RedisProducer> getDestinationToProducerMap(DebeziumConfig debeziumConfig) {
> ```

ditto. Move this logic where we create the engine
___
*[952-debezium-engine/src/main/java/io/harness/debezium/RedisStreamChangeConsumer.java, line 34 at r12](https://reviewable.io/reviews/harness/harness-core/31262#-MxsP7uW3xr2MUmdD0pF:-MxsP7uW3xr2MUmdD0pG:b-hsic1k) ([raw file](https://github.com/harness/harness-core/blob/f1d324aa4b234b9b81b07ef21f755b45d41f2470/952-debezium-engine/src/main/java/io/harness/debezium/RedisStreamChangeConsumer.java#L34)):*
> ```Java
>   String nullKey = "default";
>   String nullValue = "default";
>   Map<String, RedisProducer> destinationToProducerMap;
> ```

this map should be created in this class

**Comment by shalini-agr** [comment]
___
*[project/main_maven_install.json, line 4 at r10](https://reviewable.io/reviews/harness/harness-core/31262#-MxsPUBNDvVaylEt-TYX:-Mxs_5VE73-RSfFunq5h:b-gpsog7) ([raw file](https://github.com/harness/harness-core/blob/d24c4e1bc5accd0eef61a1500bd11a323a85c3d2/project/main_maven_install.json#L4)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

why has this file changes i did not see we added any libraries?
</blockquote></details>

There were some changes earlier because I had added "jedis" dependency, although now, all the changes have been reverted..

**Comment by shalini-agr** [comment]
___
*[952-debezium-engine/src/main/java/io/harness/debezium/RedisStreamChangeConsumer.java, line 34 at r12](https://reviewable.io/reviews/harness/harness-core/31262#-MxsP7uW3xr2MUmdD0pF:-MxshEer9dyf8avicAYr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f1d324aa4b234b9b81b07ef21f755b45d41f2470/952-debezium-engine/src/main/java/io/harness/debezium/RedisStreamChangeConsumer.java#L34)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

this map should be created in this class
</blockquote></details>

Done.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 1 of 8 files at r3, 1 of 17 files at r4, 18 of 32 files at r6, 3 of 5 files at r8, 1 of 1 files at r9, 7 of 13 files at r10, 3 of 3 files at r13, 3 of 3 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31262)* status: 14 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[952-debezium-engine/src/main/java/io/harness/debezium/DebeziumEngineStarter.java, line 19 at r15](https://reviewable.io/reviews/harness/harness-core/31262#-My76_P29aiLtYPR3LdG:-My76_P29aiLtYPR3LdH:bxffquj) ([raw file](https://github.com/harness/harness-core/blob/525489c59d3c04695e4b6d80a433c2cea1341638/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumEngineStarter.java#L19)):*
> ```Java
> @Slf4j
> public class DebeziumEngineStarter {
>   public static void startDebeziumEngine(
> ```

nit, here we are starting/executing/submitting debezium contoller threads. Lets name it similialy
___
*[952-debezium-engine/src/main/java/io/harness/debezium/RedisStreamChangeConsumer.java, line 73 at r15](https://reviewable.io/reviews/harness/harness-core/31262#-My7BzWR0D5_CecN6PyR:-My7BzWS-XE6WI2VnnVt:b-utlpv1) ([raw file](https://github.com/harness/harness-core/blob/525489c59d3c04695e4b6d80a433c2cea1341638/952-debezium-engine/src/main/java/io/harness/debezium/RedisStreamChangeConsumer.java#L73)):*
> ```Java
>   public void handleBatch(List<ChangeEvent<String, String>> records,
>       RecordCommitter<ChangeEvent<String, String>> committer) throws InterruptedException {
>     DelayStrategy delayStrategy = DelayStrategy.exponential(initialRetryDelay, maxRetryDelay);
> ```

nit, not sure how this delay strategy works, we can add when we do performance analysis and find some real use case
___
*[958-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java, line 22 at r15](https://reviewable.io/reviews/harness/harness-core/31262#-My76PIk-O1hAzM5Q-ao:-My76PIk-O1hAzM5Q-ap:bqpxyf5) ([raw file](https://github.com/harness/harness-core/blob/0606af4289db88cd203ca078db0d9da771c62464/958-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java#L22)):*
> ```Java
> @Singleton
> @Slf4j
> public class DebeziumController implements Runnable {
> ```

nit, add a comment mentioning that controller class is managing the lifecycle of debezeium engine threads
___
*[959-debezium-beans/src/main/java/io/harness/debezium/RedisOffsetBackingStore.java, line 29 at r15](https://reviewable.io/reviews/harness/harness-core/31262#-My78_mq8kFjl44Jn_k-:-My78_mr6Ch7mcJ6pBFa:b-3zgr2z) ([raw file](https://github.com/harness/harness-core/blob/525489c59d3c04695e4b6d80a433c2cea1341638/959-debezium-beans/src/main/java/io/harness/debezium/RedisOffsetBackingStore.java#L29)):*
> ```Java
>   public RedisOffsetBackingStore() {}
> 
>   public void connect() {
> ```

nit, redis cilent creation could have been done in a separate class

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31262)* status: 8 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 

___
*[952-debezium-engine/src/main/java/io/harness/debezium/DebeziumConfiguration.java, line 85 at r12](https://reviewable.io/reviews/harness/harness-core/31262#-MxsObcM-Yj83C87_qFl:-My7DPGU51uvoyCIMA2W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f1d324aa4b234b9b81b07ef21f755b45d41f2470/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumConfiguration.java#L85)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

this should not be done here
</blockquote></details>

Done.
___
*[952-debezium-engine/src/main/java/io/harness/debezium/DebeziumConfiguration.java, line 91 at r12](https://reviewable.io/reviews/harness/harness-core/31262#-MxsOgwX314H5Yn61RmY:-My7DP_nCRHpUI05N_0t:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f1d324aa4b234b9b81b07ef21f755b45d41f2470/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumConfiguration.java#L91)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

ditto. Move this logic where we create the engine
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 5 files at r8, 1 of 1 files at r9, 7 of 13 files at r10, 3 of 3 files at r13, 3 of 3 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31262)* status: 1 change requests. 6. unresolved discussions.

**Review by hextechpal — APPROVED** [review]
> Reviewed 3 of 3 files at r13, 3 of 3 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31262)* status: 2. unresolved discussions.

**Pull request merged**
