### PR TITLE
[feat]: [CDS-41050]: Instance Sync for PDC SSH deployments

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35811)

### CODE REVIEW

**Review by acasian-harness — APPROVED** [review]
> Reviewed 9 of 55 files at r1, 56 of 56 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35811)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35811#-:-N8O6hMN7q6znVSWMf3a:bnfp4nl)* status: 59 file(s) to review.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 57 files at r3, 58 of 58 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35811)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/CommandStep.java` line 68 at r4](https://reviewable.io/reviews/harness/harness-core/35811#-N8P2lmzD0OuVGn2YiMX:-N8P2lmzD0OuVGn2YiMY:b650zv6) ([raw file](https://github.com/harness/harness-core/blob/50a6b5c52289067e657ebfbe0e998b3da2fb0cd4/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/CommandStep.java#L68)):*
> ```Java
>   @Inject private KryoSerializer kryoSerializer;
>   @Inject private StepHelper stepHelper;
>   @Inject private CDStepHelper cdStepHelper;
> ```

nit: SshCommandStepHelper extends cdStepHelper so no need to inject.

**Comment by arvind-choudhary-h** [comment]
trigger codebasehash

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 5 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35811)

**Review by sahilhindwani-harness — APPROVED** [review]

**Pull request merged**
