### PR TITLE
feat: [CDS-75211]: Added StrategyNode Individual Schema for V0 Static Schema Parser

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Added StrategyNode Individual Schema for V0 Static Schema Parser

 Schema for StrategyNode 
 
```
{
   "title":"StrategyConfig",
   "type":"object",
   "properties":{
      "matrix":{
         "oneOf":[
            {
               "$ref":"#/definitions/pipeline/common/ParameterFieldMatrixConfigInterface"
            },
            {
               "type":"string",
               "pattern":"^<\\+input>((\\.)((executionInput\\(\\))|(allowedValues|default|regex)\\(.+?\\)))*$",
               "minLength":1
            }
         ]
      },
      "parallelism":{
         "oneOf":[
            {
               "type":"integer",
               "format":"int32",
               "minimum":0
            },
            {
               "type":"string",
               "pattern":"(<\\+.+>.*)",
               "minLength":1
            }
         ]
      },
      "repeat":{
         "$ref":"#/definitions/pipeline/common/HarnessForConfig"
      },
      "description":{
         "desc":"This is the description for StrategyConfig"
      }
   },
   "$schema":"http://json-schema.org/draft-07/schema#",
   "allOf":[
      {
         "oneOf":[
            {
               "required":[
                  "repeat"
               ]
            },
            {
               "required":[
                  "parallelism"
               ]
            },
            {
               "required":[
                  "matrix"
               ]
            }
         ]
      }
   ],
   "definitions":{
      "pipeline":{
         "common":{
            "ParameterFieldMatrixConfigInterface":{
               "title":"ParameterFieldMatrixConfigInterface",
               "type":"object",
               "properties":{
                  "defaultValue":{
                     "$ref":"#/definitions/pipeline/common/MatrixConfigInterface"
                  },
                  "executionInput":{
                     "type":"boolean"
                  },
                  "expression":{
                     "type":"boolean"
                  },
                  "expressionValue":{
                     "type":"string"
                  },
                  "inputSetValidator":{
                     "$ref":"#/definitions/pipeline/common/InputSetValidator"
                  },
                  "jsonResponseField":{
                     "type":"boolean"
                  },
                  "responseField":{
                     "type":"string"
                  },
                  "typeString":{
                     "type":"boolean"
                  },
                  "value":{
                     "$ref":"#/definitions/pipeline/common/MatrixConfigInterface"
                  },
                  "description":{
                     "desc":"This is the description for ParameterFieldMatrixConfigInterface"
                  }
               },
               "$schema":"http://json-schema.org/draft-07/schema#"
            },
            "MatrixConfigInterface":{
               "title":"MatrixConfigInterface",
               "type":"object",
               "$schema":"http://json-schema.org/draft-07/schema#",
               "properties":{
                  "description":{
                     "desc":"This is the description for MatrixConfigInterface"
                  }
               }
            },
            "InputSetValidator":{
               "title":"InputSetValidator",
               "type":"object",
               "properties":{
                  "parameters":{
                     "type":"string"
                  },
                  "validatorType":{
                     "type":"string",
                     "enum":[
                        "ALLOWED_VALUES",
                        "REGEX"
                     ]
                  },
                  "description":{
                     "desc":"This is the description for InputSetValidator"
                  }
               },
               "$schema":"http://json-schema.org/draft-07/schema#"
            },
            "HarnessForConfig":{
               "title":"HarnessForConfig",
               "type":"object",
               "properties":{
                  "end":{
                     "oneOf":[
                        {
                           "type":"integer",
                           "format":"int32",
                           "minimum":0
                        },
                        {
                           "type":"string",
                           "pattern":"(<\\+.+>.*)",
                           "minLength":1
                        }
                     ]
                  },
                  "items":{
                     "oneOf":[
                        {
                           "type":"array",
                           "items":{
                              "type":"string"
                           }
                        },
                        {
                           "type":"string",
                           "pattern":"(<\\+.+>.*)",
                           "minLength":1
                        }
                     ]
                  },
                  "maxConcurrency":{
                     "oneOf":[
                        {
                           "type":"integer",
                           "format":"int32",
                           "minimum":0
                        },
                        {
                           "type":"string",
                           "pattern":"(<\\+.+>.*)",
                           "minLength":1
                        }
                     ]
                  },
                  "partitionSize":{
                     "oneOf":[
                        {
                           "type":"integer",
                           "format":"int32",
                           "minimum":0
                        },
                        {
                           "type":"string",
                           "pattern":"(<\\+.+>.*)",
                           "minLength":1
                        }
                     ]
                  },
                  "start":{
                     "oneOf":[
                        {
                           "type":"integer",
                           "format":"int32",
                           "minimum":0
                        },
                        {
                           "type":"string",
                           "pattern":"(<\\+.+>.*)",
                           "minLength":1
                        }
                     ]
                  },
                  "times":{
                     "oneOf":[
                        {
                           "type":"integer",
                           "format":"int32",
                           "minimum":0
                        },
                        {
                           "type":"string",
                           "pattern":"(<\\+.+>.*)",
                           "minLength":1
                        }
                     ]
                  },
                  "unit":{
                     "type":"string",
                     "enum":[
                        "Percentage",
                        "Count"
                     ]
                  },
                  "description":{
                     "desc":"This is the description for HarnessForConfig"
                  }
               },
               "$schema":"http://json-schema.org/draft-07/schema#",
               "allOf":[
                  {
                     "oneOf":[
                        {
                           "required":[
                              "times"
                           ]
                        },
                        {
                           "required":[
                              "items"
                           ]
                        }
                     ]
                  }
               ]
            }
         }
      }
   }
}
``` 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51837)

### CODE REVIEW

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51837)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/PipelineSchemaParserV0.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/51837#-NcMOOJU3uOH2zSH9Vnd:-NcMOOJU3uOH2zSH9Vne:b5rllun) ([raw file](https://github.com/harness/harness-core/blob/ab2ef67a80d51fa5f90158db1a546a04405f18c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/PipelineSchemaParserV0.java#L126)):*
> ```Java
>       String[] fqnComponents = currentFqn.split("/");
>       if (fqnComponents.length >= 5) {
>         String stageName = fqnComponents[4];
> ```

stageName is not needed for strategy. Strategy schema will be same across the stages so we don't need to pass stage name.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51837)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51837)* status: :shipit: complete! ✓

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by AnshuH** [comment]
trigger messagecheck

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Pull request merged**
