### PR TITLE
feat: [CDS-72112]: Unit test to validate on-prem pipeline.json compared with harness-schema json

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49289)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49289)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResourceImpl.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/49289#-NXyxk6x2mBRcUNeU9Eo:-NXyxk6x2mBRcUNeU9Ep:b2xx4g) ([raw file](https://github.com/harness/harness-core/blob/297dade855d4a15042f1a8f6b8447fd45af2beb8/pipeline-service/service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResourceImpl.java#L89)):*
> ```Java
>   private ResponseDTO<JsonNode> getStaticYamlSchemaFromResource(String accountIdentifier, String projectIdentifier,
>       String orgIdentifier, String identifier, EntityType entityType, Scope scope) {
>     String filePath = "static-schema/";
> ```

file constants
___
*[`pipeline-service/service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResourceImpl.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/49289#-NXyxlKx9_uKn0ijje96:-NXyxlKx9_uKn0ijje97:b2xx4g) ([raw file](https://github.com/harness/harness-core/blob/297dade855d4a15042f1a8f6b8447fd45af2beb8/pipeline-service/service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResourceImpl.java#L91)):*
> ```Java
>     String filePath = "static-schema/";
>     if (entityType == PIPELINES) {
>       filePath = filePath + "pipeline.json";
> ```

file constants
___
*[`pipeline-service/service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResourceImpl.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/49289#-NXyz2Ct0H6S7NrwzXLo:-NXyz2Ct0H6S7NrwzXLp:b-bg93u3) ([raw file](https://github.com/harness/harness-core/blob/297dade855d4a15042f1a8f6b8447fd45af2beb8/pipeline-service/service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResourceImpl.java#L91)):*
> ```Java
>     String filePath = "static-schema/";
>     if (entityType == PIPELINES) {
>       filePath = filePath + "pipeline.json";
> ```

use switch cases
___
*[`pipeline-service/service/src/test/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImplTest.java` line 239 at r2](https://reviewable.io/reviews/harness/harness-core/49289#-NXyzLrj8HCuS5BaZl-D:-NXyzLrj8HCuS5BaZl-E:btu1a6c) ([raw file](https://github.com/harness/harness-core/blob/297dade855d4a15042f1a8f6b8447fd45af2beb8/pipeline-service/service/src/test/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImplTest.java#L239)):*
> ```Java
> 
>     String errorMessageForPipeline =
>         "Copy Pipeline.json and paste it under static-schema/pipeline.json from https://github.com/harness/harness-schema/blob/quality-assurance/v0/pipeline.json";
> ```

main branch
___
*[`pipeline-service/service/src/test/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImplTest.java` line 265 at r2](https://reviewable.io/reviews/harness/harness-core/49289#-NXyzR7Q2j3O-P9xmih7:-NXyzR7Q2j3O-P9xmih8:bvun87z) ([raw file](https://github.com/harness/harness-core/blob/297dade855d4a15042f1a8f6b8447fd45af2beb8/pipeline-service/service/src/test/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImplTest.java#L265)):*
> ```Java
>     assertEquals(jsonNode, repoJson);
> 
>     String errorMessageForPipeline =
> ```

errorMessageForTemplate

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49289)* status: 8 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResourceImpl.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/49289#-NXyxk6x2mBRcUNeU9Eo:-NY1nodQE-BXFLBJb6PR:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/297dade855d4a15042f1a8f6b8447fd45af2beb8/pipeline-service/service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResourceImpl.java#L89)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

file constants
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResourceImpl.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/49289#-NXyxlKx9_uKn0ijje96:-NY1np0E9L1UAAG4HA3j:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/297dade855d4a15042f1a8f6b8447fd45af2beb8/pipeline-service/service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResourceImpl.java#L91)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

file constants
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResourceImpl.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/49289#-NXyz2Ct0H6S7NrwzXLo:-NY1npT3-_8fbCo1v405:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/297dade855d4a15042f1a8f6b8447fd45af2beb8/pipeline-service/service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResourceImpl.java#L91)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use switch cases
</blockquote></details>

done
___
*[`pipeline-service/service/src/test/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImplTest.java` line 239 at r2](https://reviewable.io/reviews/harness/harness-core/49289#-NXyzLrj8HCuS5BaZl-D:-NY1nqPQ5khlXzDjrwzV:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/297dade855d4a15042f1a8f6b8447fd45af2beb8/pipeline-service/service/src/test/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImplTest.java#L239)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

main branch
</blockquote></details>

done
___
*[`pipeline-service/service/src/test/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImplTest.java` line 265 at r2](https://reviewable.io/reviews/harness/harness-core/49289#-NXyzR7Q2j3O-P9xmih7:-NY1nqql9rGj9inCD80W:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/297dade855d4a15042f1a8f6b8447fd45af2beb8/pipeline-service/service/src/test/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImplTest.java#L265)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

errorMessageForTemplate
</blockquote></details>

done

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49289)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 2 of 5 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49289)* status: :shipit: complete! ✓

**Comment by prashantsharma04** [comment]
trigger reviewCheck

**Comment by prashantsharma04** [comment]
trigger review

**Pull request merged**
