### PR TITLE
feat: [SSCA-1065]: Add logic for updating artifact and environments for tracker

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Describe your changes

This only updates the artifacts and environments in the tracker. 
Counts, latestArtifactWIthfix and auto closing will be in the separate PR.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56681)

### CODE REVIEW

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepharness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56681)* status: 14 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/repositories/ArtifactRepositoryCustom.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/56681#-NlWKhLq3uyx4iuZqJ7v:-NlWKhLq3uyx4iuZqJ7w:b5ju6jm) ([raw file](https://github.com/harness/harness-core/blob/7b5f1a39554781b2752d2e47255f89ef6e06a24d/ssca-manager/service/src/main/java/io/harness/repositories/ArtifactRepositoryCustom.java#L30)):*
> ```Java
> 
>   List<ArtifactEntity> findAll(Aggregation aggregation);
>   List<String> findDistinctArtifactIds(Criteria criteria);
> ```

Can we add account , org & project in the method signature? This will help in enforcing the constrain. Also we can guard these must haves
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/jobs/RemediationTrackerUpdateArtifactsIteratorHandler.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/56681#-NlWJiQf4TH197nUFHN4:-NlWJiQf4TH197nUFHN5:b-qn6wlo) ([raw file](https://github.com/harness/harness-core/blob/7b5f1a39554781b2752d2e47255f89ef6e06a24d/ssca-manager/service/src/main/java/io/harness/ssca/jobs/RemediationTrackerUpdateArtifactsIteratorHandler.java#L53)):*
> ```Java
>             .fieldName(RemediationTrackerEntityKeys.nextIteration)
>             .acceptableNoAlertDelay(ofMinutes(5))
>             .targetInterval(ofMinutes(30))
> ```

We can take it from configurations.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 666 at r1](https://reviewable.io/reviews/harness/harness-core/56681#-NlWOQLY8h-ATaQlrhXU:-NlWOQLY8h-ATaQlrhXV:bkusp0) ([raw file](https://github.com/harness/harness-core/blob/7b5f1a39554781b2752d2e47255f89ef6e06a24d/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L666)):*
> ```Java
> 
>   @Override
>   public List<String> getOrchestrationIds(
> ```

Why we need this here ? we can always call normalisedSbomComponentService
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 137 at r1](https://reviewable.io/reviews/harness/harness-core/56681#-NlWUvk80GD1FpZLiyxN:-NlWUvk80GD1FpZLiyxO:buqel2i) ([raw file](https://github.com/harness/harness-core/blob/7b5f1a39554781b2752d2e47255f89ef6e06a24d/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L137)):*
> ```Java
>         : new HashSet<>();
>     Set<String> artifactIdsMatchingTrackerFilter =
>         artifactService.getDistinctArtifactIds(remediationTracker.getAccountId(), remediationTracker.getOrgIdentifier(),
> ```

Why we are making 2 calls one for orchestrationId 2nd for artifactId? we can get it in once call
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 164 at r1](https://reviewable.io/reviews/harness/harness-core/56681#-NlWVmlcEcEvt-yZedgU:-NlWVmlcEcEvt-yZedgV:b1rn9gb) ([raw file](https://github.com/harness/harness-core/blob/7b5f1a39554781b2752d2e47255f89ef6e06a24d/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L164)):*
> ```Java
>   }
> 
>   public List<ArtifactInfo> getArtifactInfo(List<ArtifactEntity> patchedArtifactEntities,
> ```

Why public ? make it private

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56681)* status: 14 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/repositories/ArtifactRepositoryCustom.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/56681#-NlWKhLq3uyx4iuZqJ7v:-NlXRYgV3McuzwJglJyf:b-14ujed) ([raw file](https://github.com/harness/harness-core/blob/7b5f1a39554781b2752d2e47255f89ef6e06a24d/ssca-manager/service/src/main/java/io/harness/repositories/ArtifactRepositoryCustom.java#L30)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Can we add account , org & project in the method signature? This will help in enforcing the constrain. Also we can guard these must haves
</blockquote></details>

Criteria has all that constraints. We shouldn't have that enforcement in repo layer.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/jobs/RemediationTrackerUpdateArtifactsIteratorHandler.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/56681#-NlWJiQf4TH197nUFHN4:-NlXRhGp4Cavf_wSJvp6:b-ntcmwk) ([raw file](https://github.com/harness/harness-core/blob/7b5f1a39554781b2752d2e47255f89ef6e06a24d/ssca-manager/service/src/main/java/io/harness/ssca/jobs/RemediationTrackerUpdateArtifactsIteratorHandler.java#L53)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

We can take it from configurations.
</blockquote></details>

yes, will do that separately
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 666 at r1](https://reviewable.io/reviews/harness/harness-core/56681#-NlWOQLY8h-ATaQlrhXU:-NlXSTH72IGObiUxOwrG:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/7b5f1a39554781b2752d2e47255f89ef6e06a24d/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L666)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Why we need this here ? we can always call normalisedSbomComponentService
</blockquote></details>

done
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 137 at r1](https://reviewable.io/reviews/harness/harness-core/56681#-NlWUvk80GD1FpZLiyxN:-NlXSeTm6AOVJSmO1ztV:bypghen) ([raw file](https://github.com/harness/harness-core/blob/7b5f1a39554781b2752d2e47255f89ef6e06a24d/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L137)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Why we are making 2 calls one for orchestrationId 2nd for artifactId? we can get it in once call
</blockquote></details>

Both queries are running in different collection
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 164 at r1](https://reviewable.io/reviews/harness/harness-core/56681#-NlWVmlcEcEvt-yZedgU:-NlXTBFs7z7X-NfhbSIt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7b5f1a39554781b2752d2e47255f89ef6e06a24d/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L164)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Why public ? make it private
</blockquote></details>

Done.

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepharness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56681)* status: 16 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/repositories/ArtifactRepositoryCustom.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/56681#-NlWKhLq3uyx4iuZqJ7v:-NlXjNgpDCp9oDcuZw9-:bkdnyzy) ([raw file](https://github.com/harness/harness-core/blob/7b5f1a39554781b2752d2e47255f89ef6e06a24d/ssca-manager/service/src/main/java/io/harness/repositories/ArtifactRepositoryCustom.java#L30)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

Criteria has all that constraints. We shouldn't have that enforcement in repo layer.
</blockquote></details>

where we are enforcing them ?
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 137 at r1](https://reviewable.io/reviews/harness/harness-core/56681#-NlWUvk80GD1FpZLiyxN:-NlXkahY0KYrPr-hUc0m:bywcqb0) ([raw file](https://github.com/harness/harness-core/blob/7b5f1a39554781b2752d2e47255f89ef6e06a24d/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L137)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

Both queries are running in different collection
</blockquote></details>

I mean we have both artifactid & orchestrationid in sbomComponent

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56681)* status: 16 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/repositories/ArtifactRepositoryCustom.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/56681#-NlWKhLq3uyx4iuZqJ7v:-NlXqdtLDWcnDK5iqtL5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7b5f1a39554781b2752d2e47255f89ef6e06a24d/ssca-manager/service/src/main/java/io/harness/repositories/ArtifactRepositoryCustom.java#L30)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

where we are enforcing them ?
</blockquote></details>

Done.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 137 at r1](https://reviewable.io/reviews/harness/harness-core/56681#-NlWUvk80GD1FpZLiyxN:-NlXsi6NERtbXqsEitFx:bspbmsh) ([raw file](https://github.com/harness/harness-core/blob/7b5f1a39554781b2752d2e47255f89ef6e06a24d/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L137)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

I mean we have both artifactid & orchestrationid in sbomComponent
</blockquote></details>

Will do that in next PR

**Review by deepharness — APPROVED** [review]
> Reviewed 11 of 17 files at r1, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56681)* status: <span>:shipit:</span> complete! ✓

**Pull request merged**
