### PR TITLE
[feat]: [CDS-42772]: fetch resource group template before deployment

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37583)

### CODE REVIEW

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37583)* status: 34 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java` line 109 at r1](https://reviewable.io/reviews/harness/harness-core/37583#-NC0CZWD0H2a4uaMA-rf:-NC0JwERDm0J5JLlktrx:b9q0y1v) ([raw file](https://github.com/harness/harness-core/blob/8df501886966d5c9ebb2e65f3253d95a71b37c39/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java#L109)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

Should we skip the task or throw an exception
</blockquote></details>

If there is no AzureARMConfig or ScopeType is other than ResourceGroup we should skip
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java` line 213 at r1](https://reviewable.io/reviews/harness/harness-core/37583#-NC0DvwnERkiZa8o6p7P:-NC0LIUD2YHv6_Y7wIqF:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/8df501886966d5c9ebb2e65f3253d95a71b37c39/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java#L213)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

nit. This object is used only in the next line. Does not makes more sense to just get the second object (AzureCreateARMResourceStepConfigurationParameters) directly instead of allocating this temp object?
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepConfiguration.java` line 82 at r1](https://reviewable.io/reviews/harness/harness-core/37583#-NC0EhC8BJNu7f2Y3iMe:-NC0XN2gE8Xf7UJ3e3G7:b-8b11j9) ([raw file](https://github.com/harness/harness-core/blob/8df501886966d5c9ebb2e65f3253d95a71b37c39/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepConfiguration.java#L82)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

I could not find the unittests for this changes
</blockquote></details>

Added

**Review by nassergonzalez — CHANGES_REQUESTED** [review]
> Reviewed 30 of 33 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37583)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java` line 168 at r1](https://reviewable.io/reviews/harness/harness-core/37583#-NC0k2z_2Y6K-DD0sKTV:-NC0k2z_2Y6K-DD0sKTW:byolayi) ([raw file](https://github.com/harness/harness-core/blob/8df501886966d5c9ebb2e65f3253d95a71b37c39/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java#L168)):*
> ```Java
>           "The only scope allowed to do rollback is ResourceGroup. %s is not supported", azureARMConfig.getScopeType());
>     }
>     return null;
> ```

Are the scenarios where the azureARMConfig object doesn't have a RG or SubsID relevant? They were before but they have been deleted now

**Review by nassergonzalez — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37583)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 1 of 33 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37583)* status: Some of the checks are too old.

**Review by anilchowdhury-harness — DISMISSED** [review]
:lgtm:

> Reviewed 30 of 33 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37583#-:-NCLfuylBFyJNTkQGlrY:bnfp4nl)* status: Some of the checks are too old.

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37583#-:-NCPE_pN9f0cvegZAp54:bnfp4nl)* status: :shipit: complete! ✓

**Review by nassergonzalez — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37583)* status: :shipit: complete! ✓

**Pull request merged**
