### PR TITLE
feat: [PIE-5219]: Added POJOs and plan creator classes for wait step

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37283)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37283)

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37283)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 438 at r4](https://reviewable.io/reviews/harness/harness-core/37283#-NBRjU4r2zpe-qD5cust:-NBRjU4r2zpe-qD5cusu:b-exgp4q) ([raw file](https://github.com/harness/harness-core/blob/9470d227b87f8ce998d52c5ed8c29b62befac065/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L438)):*
> ```Java
>   NG_ARTIFACT_SOURCES("Flag to support multi artifact sources for service V2", HarnessTeam.CDC),
>   UPDATE_EMAILS_VIA_SCIM("Will enable updating emails in Harness via SCIM", HarnessTeam.PL),
>   WAIT_STEP;
> ```

Add description and Team info for adding FF.

**Comment by shalini-agr** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 438 at r4](https://reviewable.io/reviews/harness/harness-core/37283#-NBRjU4r2zpe-qD5cust:-NBRlr5Y4e3SnRhrdot6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9470d227b87f8ce998d52c5ed8c29b62befac065/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L438)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Add description and Team info for adding FF.
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStepInfo.java` line 41 at r5](https://reviewable.io/reviews/harness/harness-core/37283#-NBS0Yq0ARHxqmKJjHnx:-NBS0Yq0ARHxqmKJjHny:b-ivhxjh) ([raw file](https://github.com/harness/harness-core/blob/94932c4b5d24c33cfde4d0a6668d5b79005809c0/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStepInfo.java#L41)):*
> ```Java
> @RecasterAlias("io.harness.steps.wait.WaitStepInfo")
> public class WaitStepInfo implements PMSStepInfo, Visitable {
>   String duration;
> ```

I think this should be Timeout object  rather than any string. What if user gives incorrect value which we cannot parse?

```  @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH)
  @Pattern(regexp = NGRegexValidatorConstants.TIMEOUT_PATTERN)
  @VariableExpression(skipInnerObjectTraversal = true)
  ParameterField<Timeout> duration;```
```

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStepNode.java` line 38 at r5](https://reviewable.io/reviews/harness/harness-core/37283#-NBS0ynr1F0M098u9v6t:-NBS0ynr1F0M098u9v6u:bzczd19) ([raw file](https://github.com/harness/harness-core/blob/94932c4b5d24c33cfde4d0a6668d5b79005809c0/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStepNode.java#L38)):*
> ```Java
> @OwnedBy(PIPELINE)
> @RecasterAlias("io.harness.steps.wait.WaitStepNode")
> public class WaitStepNode extends PmsAbstractStepNode {
> ```

I think we will need to move timeout field out of AbstractStepNode as it is not required for this step. Let us take that as a different PR.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStepParameters.java` line 30 at r5](https://reviewable.io/reviews/harness/harness-core/37283#-NBS1DEJ1UnMjdll5U1Q:-NBS1DEJ1UnMjdll5U1R:b-mxaf69) ([raw file](https://github.com/harness/harness-core/blob/94932c4b5d24c33cfde4d0a6668d5b79005809c0/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStepParameters.java#L30)):*
> ```Java
> @RecasterAlias("io.harness.steps.wait.WaitStepParameters")
> public class WaitStepParameters implements SpecParameters {
>   String duration;
> ```

Same change for Timeout

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37283)* status: 1 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStepNode.java` line 38 at r5](https://reviewable.io/reviews/harness/harness-core/37283#-NBS0ynr1F0M098u9v6t:-NBS1ba3E1PWrkRtrRBT:bkfy73w) ([raw file](https://github.com/harness/harness-core/blob/94932c4b5d24c33cfde4d0a6668d5b79005809c0/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStepNode.java#L38)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think we will need to move timeout field out of AbstractStepNode as it is not required for this step. Let us take that as a different PR.
</blockquote></details>

Yes sahil, timout field we will handle in later PR.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37283)* status: 5 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStepInfo.java` line 41 at r5](https://reviewable.io/reviews/harness/harness-core/37283#-NBS0Yq0ARHxqmKJjHnx:-NBSOr_g8t4z6qpaiWGt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/94932c4b5d24c33cfde4d0a6668d5b79005809c0/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStepInfo.java#L41)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think this should be Timeout object  rather than any string. What if user gives incorrect value which we cannot parse?

```  @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH)
  @Pattern(regexp = NGRegexValidatorConstants.TIMEOUT_PATTERN)
  @VariableExpression(skipInnerObjectTraversal = true)
  ParameterField<Timeout> duration;```
```

</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStepParameters.java` line 30 at r5](https://reviewable.io/reviews/harness/harness-core/37283#-NBS1DEJ1UnMjdll5U1Q:-NBSOup73etboyeTAHI-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/94932c4b5d24c33cfde4d0a6668d5b79005809c0/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStepParameters.java#L30)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Same change for Timeout
</blockquote></details>

Done.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37283)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37283)* status: :shipit: complete! ✓

**Pull request merged**
