### PR TITLE
fix:[CDS-47400]: Added new index using appId and createdAt to avoid sorting in memory

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
* Added new index using appId and createdAt to avoid sorting in memory

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45069)

### CODE REVIEW

**Comment by Fernando-Dourado** [comment]
trigger messagecheck

**Review by lasdox — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45069)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45069)* status: :shipit: complete! ✓

**Review by lasdox — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45069)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
