### PR TITLE
feat:[PL-42139]: RBAC on audit trail

### PR DESCRIPTION
**Pull request by kapilgarg1996**
## Describe your changes

- Customer can now edit Audit View permission in a Role
- By default Audit view permission is enabled for managed roles.
- Feature flags required : ACCOUNT_BASIC_ROLE, PL_REMOVE_USER_VIEWER_ROLE_ASSIGNMENTS, PL_ENABLE_BASIC_ROLE_FOR_PROJECTS_ORGS

Process for a customer
- Customer need to create a role with Audit permission disabled.
- Customer has to change the role binding of "All Organisation Users" (All Account Users) user group to the new role 
- This way all users will be denied Audit View Permission 
- If customer wants to enable Audit View for a user, they can assign default "Account Viewer" (Organisation Viewer) role to the user (or user group)

### Admin User
**Account Audit Trail**
Screenshot 2023-12-07 at 4 45 20 PM
**Organisation Audit Trail**
Screenshot 2023-12-07 at 4 44 51 PM

### User with no audit view permission at account level
**Account Audit Trail**
Screenshot 2023-12-07 at 4 45 09 PM
**Organisation Audit Trail**
Screenshot 2023-12-07 at 4 45 00 PM

### User with no audit view permission at account level and org level
**Organisation Audit Trail**
Screenshot 2023-12-07 at 4 52 37 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56485)

### CODE REVIEW

**Review by Jimit09Gandhi — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56485)* status: Some of the checks are too old. 4 file(s) to review. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditPermissionValidator.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/56485#-Nlg0UgD6rXcAAF-bNwa:-Nlg0UgD6rXcAAF-bNwb:b-7hz7ri) ([raw file](https://github.com/harness/harness-core/blob/f20d4887c2522b7d0d9e43665d409d868bde920a/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditPermissionValidator.java#L47)):*
> ```Java
> 
>     if (!hasAccess) {
>       throw new AccessDeniedException(getAccessDeniedExceptionMessage(accountIdentifier,
> ```

Lets use accessControlClient.checkForAccessOrThrow. See if we can use AccessDeniedException message created by the accessControlClient.

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56485)* status: Some of the checks are too old. 4 file(s) to review. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 340 at r1](https://reviewable.io/reviews/harness/harness-core/56485#-Nlg1eu73wV7EStY5DtY:-Nlg1eu73wV7EStY5DtZ:b-vyrtgi) ([raw file](https://github.com/harness/harness-core/blob/a364d7b546dc0145ecba85cd89873a6a36186695/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L340)):*
> ```YAML
>       - account
>       - organization
>       - project
> ```

As this allowedScopeLevel is removed from project, verify PermissionsManagementJob has cleared the Audit view permission from Project level roles which had this permission.

**Comment by kapilgarg1996** [comment]
trigger uts

**Comment by kapilgarg1996** [comment]
trigger all

**Comment by kapilgarg1996** [comment]
trigger ut6, smartchecks,gitleaks

**Comment by kapilgarg1996** [comment]
trigger smartchecks

**Comment by kapilgarg1996** [comment]
trigger ut6

**Comment by kapilgarg1996** [comment]
trigger messagecheck

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56485)* status: Some of the checks are too old. 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditPermissionValidator.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/56485#-Nnit0Dc9xQzhtNWzz9N:-Nnit0Dc9xQzhtNWzz9O:busma98) ([raw file](https://github.com/harness/harness-core/blob/238005d94fabfa12d2a025eb40fc0209b6e71493/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditPermissionValidator.java#L62)):*
> ```Java
>     if (isEmpty(accountIdentifier) || isEmpty(orgIdentifier)) {
>       return false;
>     }
> ```

Is there any flow where accountIdentifie and orgIdentifier would be empty ?
Consider this case, with existing behavior if orgIdentifier is empty then this would return false but now we will directly perform access check and if orgIdentifier is empty this would mean access check would be performed for account scope if user has permission then it pass. Although the changes done seem correct just want to understand if it break for any existing customer.

**Comment by kapilgarg1996** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/56485)_ status: Some of the checks are too old. 4 file(s) to review. 0 of 2 approvals obtained.
> 
> _[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 340 at r1](https://reviewable.io/reviews/harness/harness-core/56485#-Nlg1eu73wV7EStY5DtY:-Nlg1eu73wV7EStY5DtZ:b-vyrtgi) ([raw file](https://github.com/harness/harness-core/blob/a364d7b546dc0145ecba85cd89873a6a36186695/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L340)):_
> 
> > ```yaml
> >       - account
> >       - organization
> >       - project
> > ```
> 
> As this allowedScopeLevel is removed from project, verify PermissionsManagementJob has cleared the Audit view permission from Project level roles which had this permission.

Yes, I verified in the database. PFB the result

Before
```
{ "_id" : ObjectId("659c0f9eaef5e9598b1cb46b"), "identifier" : "_project_viewer", "name" : "Project Viewer", "allowedScopeLevels" : [ "project" ], "permissions" : [ "core_serviceaccount_view", "core_template_view", "core_governancePolicy_view", "gitops_application_view", "sto_exemption_view", "core_resourcegroup_view", "ff_environment_view", "chaos_chaosexperiment_view", "core_pipeline_view", "core_serviceaccount_list", "chi_slo_view", "core_user_view", "sto_issue_view", "chaos_chaosinfrastructure_view", "chi_downtime_view", "core_role_view", "cet_criticalevent_view", "core_audit_view", "core_delegateconfiguration_view", "gitops_cluster_view", "chaos_chaoshub_view", "chaos_chaosgameday_view", "core_secret_view", "sto_scan_view", "core_service_view", "iac_workspace_view", "ff_targetgroup_view", "sto_ticket_view", "chaos_chaossecuritygovernance_view", "chi_monitoredservice_view", "core_setting_view", "sto_testtarget_view", "core_environment_view", "servicediscovery_networkmap_view", "core_usergroup_view", "core_environmentgroup_view", "core_connector_view", "core_governancePolicySets_view", "ff_target_view", "cet_agents_view", "gitops_agent_view", "cet_token_view", "code_repo_view", "ff_featureflag_view", "gitops_repository_view", "core_file_view", "core_delegate_view", "ff_environment_apiKeyView", "gitops_cert_view", "core_project_view", "gitops_gpgkey_view", "core_variable_view" ], "managed" : true, "isPublic" : false, "internal" : false, "description" : "View a project", "createdAt" : NumberLong("1704726430590"), "lastModifiedAt" : NumberLong("1704726430590"), "version" : NumberLong(0), "_class" : "roles" }
```
After
```
rs0:PRIMARY> db.roles.find({"identifier": "_project_viewer"})
{ "_id" : ObjectId("659c0f9eaef5e9598b1cb46b"), "identifier" : "_project_viewer", "name" : "Project Viewer", "allowedScopeLevels" : [ "project" ], "permissions" : [ "core_serviceaccount_view", "core_template_view", "core_governancePolicy_view", "gitops_application_view", "sto_exemption_view", "core_resourcegroup_view", "ff_environment_view", "chaos_chaosexperiment_view", "core_pipeline_view", "core_serviceaccount_list", "chi_slo_view", "core_user_view", "sto_issue_view", "chaos_chaosinfrastructure_view", "chi_downtime_view", "core_role_view", "cet_criticalevent_view", "ssca_remediationtracker_view", "core_delegateconfiguration_view", "gitops_cluster_view", "chaos_chaoshub_view", "chaos_chaosgameday_view", "core_secret_view", "sto_scan_view", "core_service_view", "iac_workspace_view", "ff_targetgroup_view", "sto_ticket_view", "chaos_chaossecuritygovernance_view", "chi_monitoredservice_view", "core_setting_view", "sto_testtarget_view", "core_environment_view", "servicediscovery_networkmap_view", "core_usergroup_view", "core_environmentgroup_view", "core_connector_view", "core_governancePolicySets_view", "ff_target_view", "cet_agents_view", "gitops_agent_view", "cet_token_view", "code_repo_view", "ff_featureflag_view", "gitops_repository_view", "core_file_view", "core_delegate_view", "ff_environment_apiKeyView", "gitops_cert_view", "core_project_view", "gitops_gpgkey_view", "core_inputset_view", "core_variable_view", "ssca_enforcementexemption_view", "core_gitxWebhooks_view" ], "managed" : true, "isPublic" : false, "internal" : false, "description" : "View a project", "createdAt" : NumberLong("1704726430590"), "lastModifiedAt" : NumberLong("1704728149243"), "version" : NumberLong(2), "_class" : "roles" }
```

**Comment by kapilgarg1996** [comment]
trigger messagecheck

**Comment by kapilgarg1996** [comment]
trigger uts

**Comment by kapilgarg1996** [comment]
trigger ut4,ut5

**Review by Jimit09Gandhi — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56485)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by Jimit09Gandhi — APPROVED** [review]

**Pull request merged**
