### PR TITLE
fix: [PL-39676]: Revert Upgrade io.netty:netty* libraries to 4.1.94.final to fix a medium level vulnerability

### PR DESCRIPTION
**Pull request by smjt-h**
Reverts harness/harness-core#49920

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50497)

### CODE REVIEW

**Comment by smjt-h** [comment]
trigger uts

**Comment by smjt-h** [comment]
trigger messagecheck

**Comment by smjt-h** [comment]
trigger uts

**Comment by smjt-h** [comment]
trigger uts

**Review by raghuAtWings — APPROVED** [review]

**Pull request merged**
