### PR TITLE
[fix]: [PIE-5082]: Discotinue and terminate the children node executions in interrupt monitor along with parents

### PR DESCRIPTION
**Pull request by brijeshdhakar**
Currently in interrupt monitor’s  forceTerminate, we find the parent node executions from all nodeExecutions and terminate them. But there is a case when a node is not leaf and and its children not started so far, So that node will not come in parents list.
And that nodeExecution will not be terminated.
Recently we saw this in pre-qa when CI stage was started but CI did not consume the nodeStart from redis. So its children were not started. And then someone aborted the pipeline.
So there were 3 node executions: Pipelines, stages and stage. All were in running state.
Pipeline and stages were parents(Pipeline stage of stages and stages parent of stage) but stage was not parent of any.
And interrupt monitor terminated the pipeline and stages nodeExecutions but Stage node remained in Running stage.
Above PR will solve this issue and it will abort the children NodeExecutions as well if they are in running.
Note: This flow is called only during force terminate of an execution.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37124)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37124)

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37124)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java` line 218 at r3](https://reviewable.io/reviews/harness/harness-core/37124#-NBVS3ht59Up04Yk-lES:-NBVS3ht59Up04Yk-lET:bay7k3j) ([raw file](https://github.com/harness/harness-core/blob/ea52a4ac2bc40ddc98a1af0d140e581cea382e65/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java#L218)):*
> ```Java
>       if (discontinuingNode == null) {
>         // TODO: Think more cases can this happen if yes what we can do to improve
>         log.error("Unable to unblock stuck execution InterruptId :{} NodeExecutionId: {}", interrupt.getUuid(),
> ```

nit: will you be adding alert for this log line?



_Code quote:_
```Java
log.error("Unable to unblock stuck execution InterruptId :{} NodeExecutionId: {}", interrupt.getUuid(),
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java` line 231 at r3](https://reviewable.io/reviews/harness/harness-core/37124#-NBVSWpi4G7H4yBXW_Ox:-NBVSWpi4G7H4yBXW_Oy:b-vk3yzj) ([raw file](https://github.com/harness/harness-core/blob/ea52a4ac2bc40ddc98a1af0d140e581cea382e65/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java#L231)):*
> ```Java
>     } else {
>       log.info("Only plan Status was not correct. Updated plan status to {}", planExecution.getStatus());
>     }
> ```

Can we carve this into new function as its used multiple places just to avoid duplicate code and if anything new be added its common everywhere



_Code quote:_
```Java
    Status status = planExecutionService.calculateStatus(interrupt.getPlanExecutionId());
    PlanExecution planExecution =
        planExecutionService.updateStatusForceful(interrupt.getPlanExecutionId(), status, null, true);
    if (planExecution == null) {
      log.error("Failed to update PlanExecution {} with Status {}", interrupt.getPlanExecutionId(), status);
    } else {
      log.info("Only plan Status was not correct. Updated plan status to {}", planExecution.getStatus());
    }
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37124)* status: 3 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java` line 218 at r3](https://reviewable.io/reviews/harness/harness-core/37124#-NBVS3ht59Up04Yk-lES:-NBWkEN3DBvINaT_AQQq:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ea52a4ac2bc40ddc98a1af0d140e581cea382e65/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java#L218)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: will you be adding alert for this log line?
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java` line 231 at r3](https://reviewable.io/reviews/harness/harness-core/37124#-NBVSWpi4G7H4yBXW_Ox:-NBWkGKF-pLYQtIhfDW8:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ea52a4ac2bc40ddc98a1af0d140e581cea382e65/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java#L231)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we carve this into new function as its used multiple places just to avoid duplicate code and if anything new be added its common everywhere
</blockquote></details>

done

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37124)* status: :shipit: complete! ✓

**Pull request merged**
