### PR TITLE
[fix]: [SRM-9875]: adding extra dimension of data source to verification_job…

### PR DESCRIPTION
**Pull request by deepak-harness**
…_instance_extra_time metric

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31815)

### CODE REVIEW

**Comment by deepak-harness** [comment]
trigger messagecheck

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31815)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/metrics/beans/VerificationTaskMetricContext.java, line 20 at r2](https://reviewable.io/reviews/harness/harness-core/31815#-MzKduP360Uqqx6E-h7F:-MzKduP450QlySOKedlb:b-4lwtq2) ([raw file](https://github.com/harness/harness-core/blob/d10b6d929ab0a8cd373838174f4b448a9e835b86/300-cv-nextgen/src/main/java/io/harness/cvng/metrics/beans/VerificationTaskMetricContext.java#L20)):*
> ```Java
>   public VerificationTaskMetricContext(VerificationTask verificationTask) {
>     put("accountId", verificationTask.getAccountId());
>     if (Objects.nonNull(verificationTask.getTags()) && verificationTask.getTags().containsKey(TAG_DATA_SOURCE)) {
> ```

we should add all tags instead of condition like this. As the final tags are only added based on the group so having extra data does not matter. 
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/entities/VerificationJobInstance.java, line 213 at r2](https://reviewable.io/reviews/harness/harness-core/31815#-MzKeLIw9gtya6rvEC34:-MzKeLIx24O09Fkw9Fgt:b-ibvqrs) ([raw file](https://github.com/harness/harness-core/blob/d10b6d929ab0a8cd373838174f4b448a9e835b86/300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/entities/VerificationJobInstance.java#L213)):*
> ```Java
>       return getEndTime().equals(verificationJobInstance.getEndTime()) && isFinalState();
>     }
>     public Duration getTimeTakenToFinish() {
> ```

this should be based on current time and the endTime of verification job instance + data collection delay right?
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java, line 274 at r2](https://reviewable.io/reviews/harness/harness-core/31815#-MzKef6jDqtd857iPJUx:-MzKef6jDqtd857iPJUy:b2j2vox) ([raw file](https://github.com/harness/harness-core/blob/d10b6d929ab0a8cd373838174f4b448a9e835b86/300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java#L274)):*
> ```Java
>   }
> 
>   private void recordMetric(ProgressLog progressLog) {}
> ```

is this used?
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java, line 366 at r2](https://reviewable.io/reviews/harness/harness-core/31815#-MzKejggD-QurTazvT5Q:-MzKejggD-QurTazvT5R:b-qiekwk) ([raw file](https://github.com/harness/harness-core/blob/d10b6d929ab0a8cd373838174f4b448a9e835b86/300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java#L366)):*
> ```Java
>       orchestrationService.markCompleted(verificationTaskIds);
>     }
>     if (lastProgressLog.isLastProgressLog(verificationJobInstance)) {
> ```

I think it is better to should do in in the caller.

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31815)* status: 4 file(s) to review. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/entities/VerificationJobInstance.java, line 213 at r2](https://reviewable.io/reviews/harness/harness-core/31815#-MzKeLIw9gtya6rvEC34:-MzLWygvBQ4t80bN22Tw:b49zz3z) ([raw file](https://github.com/harness/harness-core/blob/d10b6d929ab0a8cd373838174f4b448a9e835b86/300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/entities/VerificationJobInstance.java#L213)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

this should be based on current time and the endTime of verification job instance + data collection delay right?
</blockquote></details>

this is not used anymore right?

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31815)* status: :shipit: complete! ✓

**Pull request merged**
