### PR TITLE
[feat]:[PIE-6082]: Java client for queue Service Initial Setup

### PR DESCRIPTION
**Pull request by ankittiwari-harness**
## Describe your changes
Initial Setup for Java Client of Queue Service i.e hsqs used for interacting with multiple hsqs rest API's 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39500)

### CODE REVIEW

**Comment by ankittiwari-harness** [comment]
trigger compile

**Review by naidu-harness — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39500)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39500#-:-NFrwdlB1-BjH-Eq1QAy:bnfp4nl)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39500)* status: 8 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/AckRequest.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZ3qc2WLZnQ7XROJk:-NFtZ3qdBzAyvvPYxRJu:bkcd6mr) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/AckRequest.java#L26)):*
> ```Java
>   String subTopic;
> 
>   String topic;
> ```

can we add comments from our go here, so that someone using also knows about it. PLus we should add @Owner



_Code quote:_
```Java
  String consumerName;

  String itemID;

  String subTopic;

  String topic;
```
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/AckResponse.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZ7vO9ji3XOh6Jxhi:-NFtZ7vO9ji3XOh6Jxhj:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/AckResponse.java#L20)):*
> ```Java
> @Builder
> public class AckResponse {
>   String itemID;
> ```

same as above
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/DequeueItemMetadata.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZ9G5DYSnwo2-BfCM:-NFtZ9G5DYSnwo2-BfCN:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/DequeueItemMetadata.java#L21)):*
> ```Java
> @Builder
> public class DequeueItemMetadata {
>   Integer currentRetryCount;
> ```

same as above
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/DequeueItemMetadata.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZ9fb0wOaM_WokngD:-NFtZ9fb0wOaM_WokngE:bfv9v2e) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/DequeueItemMetadata.java#L23)):*
> ```Java
>   Integer currentRetryCount;
> 
>   BigDecimal maxProcessingTime;
> ```

shouldnt this be long?
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/DequeueRequest.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZBDOD454aVtPvsAc:-NFtZBDP8qqi8K1EJvO-:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/DequeueRequest.java#L22)):*
> ```Java
>   Integer batchSize;
> 
>   String consumerName;
> ```

same as above
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/DequeueResponse.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZBuW1Nqd0Qtzbh3m:-NFtZBuW1Nqd0Qtzbh3n:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/DequeueResponse.java#L27)):*
> ```Java
>   List<Integer> payload;
> 
>   String queueKey;
> ```

same as above
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/EnqueueRequest.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZDB258gNip0QJSd5:-NFtZDB258gNip0QJSd6:brx2xok) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/EnqueueRequest.java#L21)):*
> ```Java
>   byte[] payload;
> 
>   String producerName;
> ```

same as above
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/EnqueueResponse.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZImJCG1h5LeBGxSO:-NFtZImK9A8PDxR5tYnS:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/EnqueueResponse.java#L19)):*
> ```Java
> @Value
> @Builder
> public class EnqueueResponse {
> ```

same as above
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/UnAckRequest.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZJHC4OK2DJZjIWFn:-NFtZJHC4OK2DJZjIWFo:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/UnAckRequest.java#L20)):*
> ```Java
> @Builder
> public class UnAckRequest {
>   String itemID;
> ```

same as above
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/UnAckResponse.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZJu81240ObBJ8vul:-NFtZJu81240ObBJ8vum:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/UnAckResponse.java#L21)):*
> ```Java
> public class UnAckResponse {
>   String itemID;
> ```

same as above

**Review by ankittiwari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39500)* status: 33 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/AckRequest.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZ3qc2WLZnQ7XROJk:-NFwK7t58WnxSBdT4mZg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/AckRequest.java#L26)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we add comments from our go here, so that someone using also knows about it. PLus we should add @Owner
</blockquote></details>

Done.
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/AckResponse.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZ7vO9ji3XOh6Jxhi:-NFwK8mM185QFiwS1c60:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/AckResponse.java#L20)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/DequeueItemMetadata.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZ9G5DYSnwo2-BfCM:-NFwKACnBsifF3AQIJco:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/DequeueItemMetadata.java#L21)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/DequeueItemMetadata.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZ9fb0wOaM_WokngD:-NFwKApy3E3Z64XMuUvr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/DequeueItemMetadata.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

shouldnt this be long?
</blockquote></details>

Done.
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/DequeueRequest.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZBDOD454aVtPvsAc:-NFwKEYw0BvTFDQ7gODO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/DequeueRequest.java#L22)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/DequeueResponse.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZBuW1Nqd0Qtzbh3m:-NFwKK4rC3c4R0y_XrpN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/DequeueResponse.java#L27)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/EnqueueRequest.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZDB258gNip0QJSd5:-NFwKL6XAtsA2hrlaG6S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/EnqueueRequest.java#L21)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/EnqueueResponse.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZImJCG1h5LeBGxSO:-NFwKLkK8u4d3tkerk0-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/EnqueueResponse.java#L19)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/UnAckRequest.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZJHC4OK2DJZjIWFn:-NFwKME34gykN9i4lxx8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/UnAckRequest.java#L20)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/UnAckResponse.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/39500#-NFtZJu81240ObBJ8vul:-NFwKMjp3fzaOc5y8gyX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cfa0d55876adb2fc270e5039d28ee0b81d4b8420/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/UnAckResponse.java#L21)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 33 of 33 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39500)* status: 33 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39500)* status: 33 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 17 of 33 files at r2, 2 of 2 files at r3, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39500)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 18 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39500)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
