### PR TITLE
fix: [PL-43064]: Make the sorting feild timestamp for all the queries and orderType by default is DESC

### PR DESCRIPTION
**Pull request by sahibaHarness**
## Describe your changes

Make the incorrect sort order be handled gracefully and fall back to default sorting if incorrect.
Added test for the same.
 
Tested for:
-> Sort order field being null
-> Sort order field being anything other than timestamp 
-> Sort order type being null
-> Multiple sort orders
-> Happy scenario where Sort order type being ASC with timestamp
-> Happy scenario where Sort order type being DESC with timestamp

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55986)

### CODE REVIEW

**Comment by sahibaHarness** [comment]
trigger uts

**Comment by sahibaHarness** [comment]
trigger uts

**Comment by sahibaHarness** [comment]
trigger uts

**Comment by sahibaHarness** [comment]
trigger messagecheck

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55986)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/test/java/io/harness/audit/remote/AuditResourceTest.java` line 126 at r3](https://reviewable.io/reviews/harness/harness-core/55986#-NkFUvdjDS6LCGN-CAxS:-NkFUvdjDS6LCGN-CAxT:brlf5sw) ([raw file](https://github.com/harness/harness-core/blob/bac1b8ebd670972755bf8b801efb774bd1a6793f/platform-service/modules/audit-service/src/test/java/io/harness/audit/remote/AuditResourceTest.java#L126)):*
> ```Java
>     ResourceScopeDTO scopeDTO = ResourceScopeDTO.builder().accountIdentifier(accountIdentifier).build();
>     doNothing().when(auditPermissionValidator).validate(accountIdentifier, scopeDTO);
>     when(auditService.list(eq(accountIdentifier), any(), eq(null))).thenReturn(getPage(emptyList(), 0));
> ```

capture pagerequest argument and assert the sort order is defaulting to correct values of field and type.

**Review by nishantsaini20 — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55986)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55986)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahibaHarness** [comment]
trigger uts

**Comment by sahibaHarness** [comment]
trigger uts

**Comment by sahibaHarness** [comment]
trigger uts

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55986)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/remote/AuditResourceImpl.java` line 72 at r6](https://reviewable.io/reviews/harness/harness-core/55986#-NkOksU5-3b2HUXngKme:-NkOksU65Lye6BXC4NIf:b-5zowck) ([raw file](https://github.com/harness/harness-core/blob/f3824548919c3ef2aa7462986572c92274d1222d/platform-service/modules/audit-service/src/main/java/io/harness/audit/remote/AuditResourceImpl.java#L72)):*
> ```Java
>     if (isEmpty(pageRequest.getSortOrders()) || pageRequest.getSortOrders().size() > 1
>         || !AuditEventKeys.timestamp.equals(pageRequest.getSortOrders().get(0).getFieldName())) {
>       if (pageRequest.getSortOrders() != null
> ```

- Use isNotEmpty(pageRequest.getSortOrders())
- Extract to a private method that logs based on what pageRequest.getSortOrders() has. Also log for condition where size is > 1

**Comment by sahibaHarness** [comment]
trigger uts

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55986)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/remote/AuditResourceImpl.java` line 85 at r7](https://reviewable.io/reviews/harness/harness-core/55986#-NkP0N4U1gbOlKQp730M:-NkP0N4U1gbOlKQp730N:bq2sdq5) ([raw file](https://github.com/harness/harness-core/blob/f7cb244a7f33e033941934d2687cfd2a6b086958/platform-service/modules/audit-service/src/main/java/io/harness/audit/remote/AuditResourceImpl.java#L85)):*
> ```Java
> 
>   private void logForInvalidSortOrder(PageRequest pageRequest, String accountIdentifier) {
>     if (pageRequest.getSortOrders().size() > 1) {
> ```

Check for is not empty as well. getSortOrders() can return null resulting NPE

**Comment by sahibaHarness** [comment]
trigger uts

**Comment by sahibaHarness** [comment]
> > Reviewed 1 of 1 files at r7, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/55986)_ status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`platform-service/modules/audit-service/src/main/java/io/harness/audit/remote/AuditResourceImpl.java` line 85 at r7](https://reviewable.io/reviews/harness/harness-core/55986#-NkP0N4U1gbOlKQp730M:-NkP0N4U1gbOlKQp730N:bq2sdq5) ([raw file](https://github.com/harness/harness-core/blob/f7cb244a7f33e033941934d2687cfd2a6b086958/platform-service/modules/audit-service/src/main/java/io/harness/audit/remote/AuditResourceImpl.java#L85)):_
> 
> > ```java
> >   private void logForInvalidSortOrder(PageRequest pageRequest, String accountIdentifier) {
> >     if (pageRequest.getSortOrders().size() > 1) {
> > ```
> 
> Check for is not empty as well. getSortOrders() can return null resulting NPE

The API request will give sort order size as zero when not passed. Added the null check
image

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55986)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
