### PR TITLE
feat: [SRM-11288]: Added support for new pipeline yaml in SLO expansion policy

### PR DESCRIPTION
**Pull request by arpit-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35894)

### CODE REVIEW

**Comment by arpit-harness** [comment]
trigger messagecheck

**Comment by arpit-harness** [comment]
trigger messagecheck

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Vulnerability 1 Vulnerabilities 
 
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35894)

**Review by praveensugavanam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35894)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/cdng/services/impl/CVNGStepUtils.java` line 94 at r1](https://reviewable.io/reviews/harness/harness-core/35894#-N8UV_tNCTgBZdJLdbAq:-N8UV_tNCTgBZdJLdbAr:b-k1v8) ([raw file](https://github.com/harness/harness-core/blob/f11751c1dc7c34b1a0654031cf6ede89126c2efc/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/services/impl/CVNGStepUtils.java#L94)):*
> ```Java
>     }
>   }
> ```

Before merging this, Can we get on a call quickly to understand why we need this change ?
Based on the diff, it looks like service ref can be optional in a pipeline now ? That could have other consequences for us, no ?

**Review by deepak-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35894)* status: Some of the checks are too old. 4 file(s) to review. 1 change requests.

**Review by arpit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35894)* status: Some of the checks are too old. 4 file(s) to review. 1. unresolved discussions. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/cdng/services/impl/CVNGStepUtils.java` line 94 at r1](https://reviewable.io/reviews/harness/harness-core/35894#-N8UV_tNCTgBZdJLdbAq:-N9-pJ3x2umgA7VKkq3U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f11751c1dc7c34b1a0654031cf6ede89126c2efc/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/services/impl/CVNGStepUtils.java#L94)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

Before merging this, Can we get on a call quickly to understand why we need this change ?
Based on the diff, it looks like service ref can be optional in a pipeline now ? That could have other consequences for us, no ?
</blockquote></details>

Done.

**Comment by sunilgupta-harness** [comment]
reviewable is not getting updated so force merging it

**Pull request merged**
