### PR TITLE
feat: [CDS-79546]: Changes to avoid write conflicts while planExecuti…

### PR DESCRIPTION
**Pull request by Y0709**
…onSummaryUpdate

Context:  Currently we are updating the planExecutionSummary collection via 2 flows one via graph and one via prpc client when other modules  send data to be updated in planExecution summary. This sometimes results in write conflicts in mongo. These write conflicts may also arise when 2 parallel stages of different modules are running in parallel ad both send grpc calls to update and since the updates are not sequential this also leads to write conflicts. To avoid these issues we have shifted the code to update planExecutionSummary completely via graph and when other modules send calls to update info we will update that info to a new collection **graphUpdateInfo** for both stage and pipeline level info and publish an orchestration log to update planExecutionSummary via graph
Before Changes response

Screenshot 2023-10-04 at 2 31 46 PM

After changes response

Screenshot 2023-10-04 at 2 35 32 PM

Testing done - 
Created a pipeline with cd and custom stages both seperately and combined . Checked moduleInfo is updated in both layout node map and outside layout node map

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53697)

### CODE REVIEW

**Review by hextechpal — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53697)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger commonchecks

**Comment by Y0709** [comment]
trigger gitleaks

**Comment by Y0709** [comment]
trigger smartchecks

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger ut0

**Comment by Y0709** [comment]
trigger ut0, ut1, ut2, ut3, ut4, ut5, ut6, ut7, ut8, ut9

**Comment by Y0709** [comment]
trigger ut1

**Comment by Y0709** [comment]
trigger ut2

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53697)* status: 9 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/GraphUpdateInfo.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/53697#-NftpXTM7kz1paJkcJdg:-NftpXTM7kz1paJkcJdh:b4g0655) ([raw file](https://github.com/harness/harness-core/blob/353b9088c906d65acf13ee74d6201253a9850c75/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/GraphUpdateInfo.java#L47)):*
> ```Java
> @Document("graphUpdateInfo")
> @TypeAlias("graphUpdateInfo")
> public class GraphUpdateInfo implements PersistentEntity, UuidAware {
> ```

Why we cant use NodeExecutionInfo to store this?

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53697)* status: 9 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/sdk/service/execution/PmsExecutionGrpcService.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/53697#-Nftq_oS6aXl3ciOQFZA:-Nftq_oT3g_VUY9ek8Ws:b-2pfjt5) ([raw file](https://github.com/harness/harness-core/blob/353b9088c906d65acf13ee74d6201253a9850c75/pipeline-service/service/src/main/java/io/harness/pms/sdk/service/execution/PmsExecutionGrpcService.java#L113)):*
> ```Java
>   }
> 
>   private void updateGraphUpdateInfo(String moduleName, String planExecutionId, LinkedHashMap<String, Object> infoDoc) {
> ```

why is this required?

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53697)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/GraphUpdateInfo.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/53697#-NftpXTM7kz1paJkcJdg:-Nftt2Zp6jnZnMgvgZ0p:bu5svp3) ([raw file](https://github.com/harness/harness-core/blob/353b9088c906d65acf13ee74d6201253a9850c75/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/GraphUpdateInfo.java#L47)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why we cant use NodeExecutionInfo to store this?
</blockquote></details>

We are not using node execution info because here we have to store pipeline level info which is stored outside layout node map as module info as well as stage node level info 
___
*[`pipeline-service/service/src/main/java/io/harness/pms/sdk/service/execution/PmsExecutionGrpcService.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/53697#-Nftq_oS6aXl3ciOQFZA:-NfttWXu8IUk5qmH39yx:b-in1c46) ([raw file](https://github.com/harness/harness-core/blob/353b9088c906d65acf13ee74d6201253a9850c75/pipeline-service/service/src/main/java/io/harness/pms/sdk/service/execution/PmsExecutionGrpcService.java#L113)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why is this required?
</blockquote></details>

Just to avoid small duplication of code

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger pmd

**Comment by Y0709** [comment]
trigger codebasehash

**Comment by sahilhindwani-harness** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 930 at r3](https://reviewable.io/reviews/harness/harness-core/53697#-NgHfx9o-a3dXiFh4_qU:-NgHfx9o-a3dXiFh4_qV:b-cdo2lv) ([raw file](https://github.com/harness/harness-core/blob/f471fb9b09f52c92f541e5105dd6e152dd8ca5de/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L930)):*
> ```Java
>       HarnessTeam.CDP),
>   CDS_INFRA_GITX("Onboard Infrastructure entity to GitX", HarnessTeam.CDC),
>   PMS_MERGE_PIPELINE_EXECUTION_SUMMARY_UPDATE_FLOW(
> ```

ni: Use PIE

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 7 of 11 files at r1, 7 of 9 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53697)* status: 10 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r1, 5 of 9 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53697)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/GraphUpdateInfo.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/53697#-NgHwTWfBUJddmVfeoez:-NgHwTWfBUJddmVfeof-:bwzhn2x) ([raw file](https://github.com/harness/harness-core/blob/f471fb9b09f52c92f541e5105dd6e152dd8ca5de/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/GraphUpdateInfo.java#L55)):*
> ```Java
>   String stageUuid;
>   StepCategory stepCategory;
>   Map<String, LinkedHashMap<String, Object>> moduleInfo;
> ```

can we make it generic, store data needed by moduleInfo as an object.
So this entity becomes generic to act as update for graph, like when stepDetails needs to be updated.
Also file ticket to move stepDetails to this collection as graph update 
cc: @sahilhindwani-harness 



_Code quote:_
```Java
  String stageUuid;
  StepCategory stepCategory;
  Map<String, LinkedHashMap<String, Object>> moduleInfo;
```
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/PlanExecutionModuleInfoUpdateEventHandler.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/53697#-NgHy7c_88jBM7BugqQ2:-NgHy7ca0T-gCbTFOAwN:b9drc9q) ([raw file](https://github.com/harness/harness-core/blob/f471fb9b09f52c92f541e5105dd6e152dd8ca5de/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/PlanExecutionModuleInfoUpdateEventHandler.java#L33)):*
> ```Java
>   private static final String STAGE_MODULE_INFO_UPDATE_KEY = "layoutNodeMap.%s.moduleInfo.%s.%s";
> 
>   public void handlePipelineInfoUpdate(String planExecutionId, Update update) {
> ```

isnt below method almost same except params to be different?
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/GraphUpdateInfoRepositoryCustomImpl.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/53697#-NgHyBqW8lcMrZVfKhOC:-NgHyBqW8lcMrZVfKhOD:b-1ldvbo) ([raw file](https://github.com/harness/harness-core/blob/f471fb9b09f52c92f541e5105dd6e152dd8ca5de/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/GraphUpdateInfoRepositoryCustomImpl.java#L28)):*
> ```Java
> @AllArgsConstructor(access = AccessLevel.PRIVATE, onConstructor = @__({ @Inject }))
> @Slf4j
> @OwnedBy(PIPELINE)
> ```

add codepulse annotations
___
*[`pipeline-service/service/src/main/java/io/harness/pms/sdk/service/execution/PmsExecutionGrpcService.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/53697#-NgHydDeCRHiMNSsJLsS:-NgHydDeCRHiMNSsJLsT:b-t5a2nt) ([raw file](https://github.com/harness/harness-core/blob/f471fb9b09f52c92f541e5105dd6e152dd8ca5de/pipeline-service/service/src/main/java/io/harness/pms/sdk/service/execution/PmsExecutionGrpcService.java#L125)):*
> ```Java
> 
>   @VisibleForTesting
>   void updateStageModuleInfo(ExecutionSummaryUpdateRequest request) {
> ```

isnt this almost same as pipeline update?

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53697)* status: 8 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 930 at r3](https://reviewable.io/reviews/harness/harness-core/53697#-NgHfx9o-a3dXiFh4_qU:-NgTGpfg6996BpneA6ny:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f471fb9b09f52c92f541e5105dd6e152dd8ca5de/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L930)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

ni: Use PIE
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/GraphUpdateInfo.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/53697#-NgHwTWfBUJddmVfeoez:-NgTGxN3B_lB7ASbzvWK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f471fb9b09f52c92f541e5105dd6e152dd8ca5de/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/GraphUpdateInfo.java#L55)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we make it generic, store data needed by moduleInfo as an object.
So this entity becomes generic to act as update for graph, like when stepDetails needs to be updated.
Also file ticket to move stepDetails to this collection as graph update 
cc: @sahilhindwani-harness
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/GraphUpdateInfoRepositoryCustomImpl.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/53697#-NgHyBqW8lcMrZVfKhOC:-NgTGz8v6k6ehawJNtfw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f471fb9b09f52c92f541e5105dd6e152dd8ca5de/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/GraphUpdateInfoRepositoryCustomImpl.java#L28)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add codepulse annotations
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53697)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 930 at r3](https://reviewable.io/reviews/harness/harness-core/53697#-NgHfx9o-a3dXiFh4_qU:-NgTSGyY9CzOxXyE4nIL:b-j6pw4i) ([raw file](https://github.com/harness/harness-core/blob/f471fb9b09f52c92f541e5105dd6e152dd8ca5de/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L930)):*
<details><summary><i>Previously, Y0709 (Yuvraj Singhal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We should now use CDS one, there is no PIE
___
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/GraphUpdateInfo.java` line 55 at r6](https://reviewable.io/reviews/harness/harness-core/53697#-NgTSOU96tT8D6dVw1mo:-NgTSOU96tT8D6dVw1mp:b-tjfisq) ([raw file](https://github.com/harness/harness-core/blob/c4baf12a7ffb9e83c3b9f5ff2bd4943362526c67/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/GraphUpdateInfo.java#L55)):*
> ```Java
>   String planExecutionId;
>   String nodeExecutionId;
>   StepCategory stepCategory;
> ```

where is this stepCategory used?
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/PlanExecutionModuleInfoUpdateEventHandler.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/53697#-NgHy7c_88jBM7BugqQ2:-NgTcdbFClQ6MtEZWsEc:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f471fb9b09f52c92f541e5105dd6e152dd8ca5de/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/PlanExecutionModuleInfoUpdateEventHandler.java#L33)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

isnt below method almost same except params to be different?
</blockquote></details>

done

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53697)* status: 11 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 930 at r3](https://reviewable.io/reviews/harness/harness-core/53697#-NgHfx9o-a3dXiFh4_qU:-NgTjhkg19Ph3qUhdo-Y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f471fb9b09f52c92f541e5105dd6e152dd8ca5de/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L930)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

We should now use CDS one, there is no PIE
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/GraphUpdateInfo.java` line 55 at r6](https://reviewable.io/reviews/harness/harness-core/53697#-NgTSOU96tT8D6dVw1mo:-NgTjgWL7ypJX5K6MrtP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4baf12a7ffb9e83c3b9f5ff2bd4943362526c67/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/GraphUpdateInfo.java#L55)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

where is this stepCategory used?
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 7 of 9 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53697)* status: 11 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 7 files at r5, 6 of 9 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53697)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53697)* status: :shipit: complete! ✓

**Comment by Y0709** [comment]
trigger review

**Pull request merged**
