### PR TITLE
feat: [PLG-2148]: Create credit api implementation

### PR DESCRIPTION
**Pull request by Xin-Harness**
## Describe your changes
Test the unhappy path with invalid json input
image
Test happy path with valid json input
image

image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46350)

### CODE REVIEW

**Review by neelam-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46350)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/credit/services/CreditService.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/46350#-NTGI2s6-qucnRW4sqYN:-NTGI2s77tEubvqVGWeB:b-i4oo2b) ([raw file](https://github.com/harness/harness-core/blob/a734329f4efd0ef2167bfa572b523ace27991192/930-ng-license-manager/src/main/java/io/harness/credit/services/CreditService.java#L20)):*
> ```Java
>   List<CreditDTO> getCredits(String accountIdentifier);
> 
>   CreditDTO purchaseCredits(String accountIdentifier, CreditDTO creditDTO);
> ```

let's rename this to `purchaseCredit` (singular) since this method is only purchasing a single credit and not bulk credits ?

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46350)* status: 3 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/46350#-NTIRC3v3bdB5Qc7bnjc:-NTIRC3v3bdB5Qc7bnjd:bt42zpt) ([raw file](https://github.com/harness/harness-core/blob/a734329f4efd0ef2167bfa572b523ace27991192/930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java#L48)):*
> ```Java
>   @Override
>   public CreditDTO purchaseCredits(String accountIdentifier, CreditDTO creditDTO) {
>     Credit buildCredits = CICredit.builder().build();
> ```

we should use CICreditObjectMapper for this.

**Review by kapil-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46350#-:-NTJxbgCEZIv3DfeK5mn:bnfp4nl)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by neelam-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46350)* status: :shipit: complete! ✓

**Comment by neelam-harness** [comment]
trigger review

**Pull request merged**
