### PR TITLE
fix:[CDS-52541]: Silence the mapping exception behind FF.

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
We are unable to RCA a corner case during map operation. The method throws the error `Converter org.modelmapper.internal.converter.CollectionConverter@354aaffe failed to convert com.mongodb.BasicDBList to java.util.List`. We choose to iterate the source and try to map each element to the same target, using this strategy when the issue comes again we will have more details.

Enable the FF `SPG_STATE_MACHINE_MAPPING_EXCEPTION_IGNORE` to silence the exception and keep the execution.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43521)

### CODE REVIEW

**Comment by Fernando-Dourado** [comment]
trigger messagecheck

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43521)* status: Some of the checks are too old. 3 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43521)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43521)* status: 3 file(s) to review. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java` line 2793 at r2](https://reviewable.io/reviews/harness/harness-core/43521#-NNfz91F726M9OZTgStZ:-NNfz91F726M9OZTgSt_:b-94meog) ([raw file](https://github.com/harness/harness-core/blob/19ad56132bb63b575c993943f0517ce1f677a5e2/400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java#L2793)):*
> ```Java
> 
>       // ITERATE THE SOURCE ELEMENTS AND MAP TO THE SAME TARGET
>       mapEntries(source, target, accountId);
> ```

Won't it be safer to call this method when the feature flag is enabled? Rather than proactively going in and checking for the feature flag later on exception?

**Review by lasdox — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43521)* status: :shipit: complete! ✓

**Pull request merged**
