### PR TITLE
fix: [PL-22160]: Changed error code for duplicate yaml git config

### PR DESCRIPTION
**Pull request by bhavya181**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30748)

### CODE REVIEW

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30748)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30748)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 279 at r1](https://reviewable.io/reviews/harness/harness-core/30748#-Mvvvl4j5NFa1YpqPBSs:-Mvvvl4j5NFa1YpqPBSt:b7lycwo) ([raw file](https://github.com/harness/harness-core/blob/6cc58eef881f427882f6772290eeaba0b57a30a9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L279)):*
> ```Java
>       sendEventForConnectorSetupUsageChange(gitSyncConfigDTO);
>     } catch (DuplicateKeyException ex) {
>       log.error("A git sync config with this identifier or repo %s and branch %s already exists",
> ```

Our unique index is on the repo. So can you please change this line to 

A git sync config with this identifier or repo %s already exists"

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30748)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 279 at r1](https://reviewable.io/reviews/harness/harness-core/30748#-Mvvvl4j5NFa1YpqPBSs:-MvxEIjW5S6bo4KtyEEb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6cc58eef881f427882f6772290eeaba0b57a30a9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L279)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Our unique index is on the repo. So can you please change this line to 

A git sync config with this identifier or repo %s already exists"
</blockquote></details>

Done.
___
*[980-commons/src/main/java/io/harness/exception/DuplicateEntityException.java, line 23 at r1](https://reviewable.io/reviews/harness/harness-core/30748#-MvsppCkrJxE_u1Q7QP9-r1-23:-MvxEKGU6aiAiw6bVgD4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6cc58eef881f427882f6772290eeaba0b57a30a9/980-commons/src/main/java/io/harness/exception/DuplicateEntityException.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

error code issue : RESOURCE_NOT_FOUND_EXCEPTION
</blockquote></details>

Done.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30748)* status: 3 file(s) to review. 2. unresolved discussions.

**Review by DeepakPatankar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30748#-:-Mw2QuLz9pF1udYlptlp:bnfp4nl)* status: 1. unresolved discussions.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30748)* status: 1. unresolved discussions.

**Review by rathodmeetsatish — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30748)* status: 1. unresolved discussions.

**Review by rathodmeetsatish — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30748#-:-Mw2Rjjk6gN9sHfpD7dc:bnfp4nl)* status: 1. unresolved discussions.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30748#-:-Mw5S9AB6ZDz0BlGSoLA:bnfp4nl)* status: :shipit: complete! ✓

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30748)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30748)* status: :shipit: complete! ✓

**Pull request merged**
