### PR TITLE
feat: [PL-26990]: Ability to know the status of Email Notifications

### PR DESCRIPTION
**Pull request by rijajoo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38291)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 14 Issues 
* Code issue 13 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38291)

**Comment by piyush-harness** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 646 at r2](https://reviewable.io/reviews/harness/harness-core/38291#-NDWsiKhEuPkydMvi63Z:-NDWsiKhEuPkydMvi63_:b-kfl3g0) ([raw file](https://github.com/harness/harness-core/blob/7b7df0ce03effc32e8c73987d8ca6e16fa7c942b/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L646)):*
> ```Java
>   @GET
>   @Hidden
>   @Path("is-email-in-account")
> ```

Change path

**Comment by piyush-harness** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java` line 137 at r2](https://reviewable.io/reviews/harness/harness-core/38291#-NDWtZGp0cpD5ZaJ2UdX:-NDWtZGp0cpD5ZaJ2UdY:b-989sn6) ([raw file](https://github.com/harness/harness-core/blob/7b7df0ce03effc32e8c73987d8ca6e16fa7c942b/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java#L137)):*
> ```Java
>           DEFAULT_ERROR_CODE, USER);
>     }
>     NotificationTaskResponse response = sendInSync(Collections.singletonList(email), Collections.emptyList(),
> ```

Why this is passed as empty

**Comment by piyush-harness** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java` line 146 at r2](https://reviewable.io/reviews/harness/harness-core/38291#-NDWtmTg1oPrJbPGXYY1:-NDWtmTh4yqBybrU9Mm3:bk8rp8d) ([raw file](https://github.com/harness/harness-core/blob/7b7df0ce03effc32e8c73987d8ca6e16fa7c942b/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java#L146)):*
> ```Java
>   }
> 
>   public NotificationTaskResponse sendEmail(EmailDTO emailDTO) {
> ```

Break this method

**Comment by piyush-harness** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java` line 146 at r2](https://reviewable.io/reviews/harness/harness-core/38291#-NDWtmTg1oPrJbPGXYY1:-NDaOy16D4x0A7uChQg-:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/7b7df0ce03effc32e8c73987d8ca6e16fa7c942b/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java#L146)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Break this method
</blockquote></details>

ok

**Review by piyush-harness — DISMISSED** [review]
> Reviewed 10 of 17 files at r1, 3 of 6 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38291)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
:lgtm:

**Review by rathodmeetsatish — DISMISSED** [review]
> Reviewed 10 of 17 files at r1, 3 of 6 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38291)* status: :shipit: complete! ✓

**Comment by piyush-harness** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java` line 139 at r4](https://reviewable.io/reviews/harness/harness-core/38291#-NDgsxCu6Jn2FtNqjQbA:-NDgsxCu6Jn2FtNqjQbB:beuytla) ([raw file](https://github.com/harness/harness-core/blob/9e15701b5306b2dc8a599f2511a5a40e7bc04d2c/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java#L139)):*
> ```Java
>     NotificationTaskResponse response = sendInSync(Collections.singletonList(email), Collections.emptyList(),
>         DEFAULT_SUBJECT_BODY, DEFAULT_SUBJECT_BODY, email, notificationSettingDTO.getAccountId());
>     if (response.getProcessingResponse().getResult().isEmpty()
> ```

Check for Null on getProcessingResponse

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38291)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java` line 166 at r4](https://reviewable.io/reviews/harness/harness-core/38291#-NDgublS9vQR2RzKWust:-NDgublS9vQR2RzKWusu:b9gmrxr) ([raw file](https://github.com/harness/harness-core/blob/9e15701b5306b2dc8a599f2511a5a40e7bc04d2c/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java#L166)):*
> ```Java
>       throw new NotificationException("Failed to send email. Check SMTP configuration", DEFAULT_ERROR_CODE, USER);
>     }
>     if (!errorMessage.equals("")) {
> ```

Check StringUtils.isNotEmpty
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java` line 175 at r4](https://reviewable.io/reviews/harness/harness-core/38291#-NDguW1M-tqJg4WzXb2M:-NDguW1M-tqJg4WzXb2N:b9gmrxr) ([raw file](https://github.com/harness/harness-core/blob/9e15701b5306b2dc8a599f2511a5a40e7bc04d2c/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java#L175)):*
> ```Java
>     if (emails.isEmpty() && ccEmails.isEmpty()) {
>       String emptyEmailMessage = "No email id encountered for " + emailDTO.getNotificationId() + ".";
>       if (!errorMessage.equals("")) {
> ```

Check StringUtils.isNotEmpty
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java` line 195 at r4](https://reviewable.io/reviews/harness/harness-core/38291#-NDguihT9THpSEodweEn:-NDguihT9THpSEodweEo:bb73xfv) ([raw file](https://github.com/harness/harness-core/blob/9e15701b5306b2dc8a599f2511a5a40e7bc04d2c/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java#L195)):*
> ```Java
>     if (!notPresentEmails.isEmpty()) {
>       emails.removeAll(notPresentEmails);
>       if (!errorMessage.equals("")) {
> ```

Same
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java` line 198 at r4](https://reviewable.io/reviews/harness/harness-core/38291#-NDgv7GD-Msqr3OqaTDI:-NDgv7GE2-UVpvHGF4MY:b3ujo14) ([raw file](https://github.com/harness/harness-core/blob/9e15701b5306b2dc8a599f2511a5a40e7bc04d2c/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java#L198)):*
> ```Java
>         errorMessage += " ";
>       }
>       errorMessage +=
> ```

Use String.concat , Its more performant

**Review by rathodmeetsatish — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38291)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by rathodmeetsatish — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38291)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38291)* status: :shipit: complete! ✓

**Comment by piyush-harness** [comment]
:lgtm:

**Comment by rijajoo** [comment]
trigger codebasehash

**Pull request merged**
