### PR TITLE
feat: [CDS-55795]: Elastigroup setup step

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45145)

### CODE REVIEW

**Comment by arvind-choudhary-h** [comment]
*[`100-migrator/src/main/java/io/harness/ngmigration/service/step/elastigroup/ElastigroupSetupStepMapperImpl.java` line 159 at r1](https://reviewable.io/reviews/harness/harness-core/45145#-NQXbZ14EP4rAhzDXgUi:-NQXbZ14EP4rAhzDXgUj:b56ds2s) ([raw file](https://github.com/harness/harness-core/blob/c17361901f2efb1a70f0c191a7a27f2482195a81/100-migrator/src/main/java/io/harness/ngmigration/service/step/elastigroup/ElastigroupSetupStepMapperImpl.java#L159)):*
> ```Java
>     SpotInstServiceSetup state1 = (SpotInstServiceSetup) getState(stepYaml1);
>     SpotInstServiceSetup state2 = (SpotInstServiceSetup) getState(stepYaml2);
>     return CompareUtils.compareObjects(state1.getCurrentRunningCount(), state2.getCurrentRunningCount())
> ```

we'll need to check for the case where currentRunning is selected. At that time, instance counts doesn't matter.

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45145)* status: 1 file(s) to review. 0 of 2 approvals obtained.

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45145)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`100-migrator/src/main/java/io/harness/ngmigration/service/step/elastigroup/ElastigroupSetupStepMapperImpl.java` line 159 at r1](https://reviewable.io/reviews/harness/harness-core/45145#-NQXbZ14EP4rAhzDXgUi:-NQXbqB1A6ROfExGKkK0:bn1l5tn) ([raw file](https://github.com/harness/harness-core/blob/c17361901f2efb1a70f0c191a7a27f2482195a81/100-migrator/src/main/java/io/harness/ngmigration/service/step/elastigroup/ElastigroupSetupStepMapperImpl.java#L159)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

we'll need to check for the case where currentRunning is selected. At that time, instance counts doesn't matter.
</blockquote></details>

wont instance count be null or zero in that case?

**Comment by arvind-choudhary-h** [comment]
*[`100-migrator/src/main/java/io/harness/ngmigration/service/step/elastigroup/ElastigroupSetupStepMapperImpl.java` line 159 at r1](https://reviewable.io/reviews/harness/harness-core/45145#-NQXbZ14EP4rAhzDXgUi:-NQYd0H92L9ajFqJlPMY:b-igdyxm) ([raw file](https://github.com/harness/harness-core/blob/c17361901f2efb1a70f0c191a7a27f2482195a81/100-migrator/src/main/java/io/harness/ngmigration/service/step/elastigroup/ElastigroupSetupStepMapperImpl.java#L159)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

wont instance count be null or zero in that case?
</blockquote></details>

Not sure if we update in every PUT call of that step if we change. Anyways, we'll need to add this check: `useCurrentRunningCount` 



_Code quote:_
```Java
SpotInstServiceSetup
```

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45145)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45145)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`100-migrator/src/main/java/io/harness/ngmigration/service/step/elastigroup/ElastigroupSetupStepMapperImpl.java` line 159 at r1](https://reviewable.io/reviews/harness/harness-core/45145#-NQXbZ14EP4rAhzDXgUi:-NQbUtrp7_LaoGyxOE0x:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c17361901f2efb1a70f0c191a7a27f2482195a81/100-migrator/src/main/java/io/harness/ngmigration/service/step/elastigroup/ElastigroupSetupStepMapperImpl.java#L159)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

Not sure if we update in every PUT call of that step if we change. Anyways, we'll need to add this check: `useCurrentRunningCount` 
</blockquote></details>

Done.

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45145)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45145)* status: :shipit: complete! ✓

**Pull request merged**
