### PR TITLE
feat: [IDP-1031]: Iterator for score computation for scorecards

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52149)

### CODE REVIEW

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52149)* status: 9 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/namespace/beans/entity/NamespaceEntity.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/52149#-NcxQjQi4QqgGhgX6fYh:-NcxQjQi4QqgGhgX6fYi:bs3ln1k) ([raw file](https://github.com/harness/harness-core/blob/c128779deb2d7b923f832a45fe1f6be653f1747e/idp-service/src/main/java/io/harness/idp/namespace/beans/entity/NamespaceEntity.java#L42)):*
> ```Java
>   @CreatedDate Long createdAt;
>   @LastModifiedDate Long lastModifiedAt;
>   @FdIndex Long nextIteration;
> ```

We can use primitive long type itself here
___
*[`idp-service/src/main/java/io/harness/idp/namespace/beans/entity/NamespaceEntity.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/52149#-NcxQq216VE2siJIxNmI:-NcxQq216VE2siJIxNmJ:byfn343) ([raw file](https://github.com/harness/harness-core/blob/c128779deb2d7b923f832a45fe1f6be653f1747e/idp-service/src/main/java/io/harness/idp/namespace/beans/entity/NamespaceEntity.java#L42)):*
> ```Java
>   @CreatedDate Long createdAt;
>   @LastModifiedDate Long lastModifiedAt;
>   @FdIndex Long nextIteration;
> ```

What will be the behaviour for new accounts being provisioned ? We should be setting system current ms in that flow as well
___
*[`idp-service/src/main/java/io/harness/idp/namespace/beans/entity/NamespaceEntity.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/52149#-NcxQlq8EwkzHQkl-4DN:-NcxQlq8EwkzHQkl-4DO:bs3ln1k) ([raw file](https://github.com/harness/harness-core/blob/c128779deb2d7b923f832a45fe1f6be653f1747e/idp-service/src/main/java/io/harness/idp/namespace/beans/entity/NamespaceEntity.java#L52)):*
> ```Java
> 
>   @Override
>   public Long obtainNextIteration(String fieldName) {
> ```

We can use primitive long type itself here
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scores/iteratorhandler/ScoreComputationHandler.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/52149#-NcxRIfLAO-U2ghTl9tS:-NcxRIfLAO-U2ghTl9tT:b-c95ccv) ([raw file](https://github.com/harness/harness-core/blob/c128779deb2d7b923f832a45fe1f6be653f1747e/idp-service/src/main/java/io/harness/idp/scorecard/scores/iteratorhandler/ScoreComputationHandler.java#L39)):*
> ```Java
>   @Override
>   public void handle(NamespaceEntity namespaceEntity) {
>     scoreService.computeScores(
> ```

log info can be added before the start to understand how long score computation takes for an account

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52149)* status: 10 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/app/IdpApplication.java` line 194 at r2](https://reviewable.io/reviews/harness/harness-core/52149#-NczWODX4E1QcWuFAzxf:-NczWODX4E1QcWuFAzxg:b-vuc1gr) ([raw file](https://github.com/harness/harness-core/blob/43af60f099e714997fea5d42cc23659cd41d886f/idp-service/src/main/java/io/harness/idp/app/IdpApplication.java#L194)):*
> ```Java
>     environment.jersey().register(RequestLoggingFilter.class);
> 
>     harnessMetricRegistry = injector.getInstance(HarnessMetricRegistry.class);
> ```

where is this instance getting used? :thinking: 



_Code quote:_
```Java
harnessMetricRegistry
```
___
*[`idp-service/src/main/java/io/harness/idp/migration/NameSpaceEntityNextIterationMigration.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/52149#-NczXCJMA9oE2bQshWBg:-NczXCJMA9oE2bQshWBh:b-z5dz5r) ([raw file](https://github.com/harness/harness-core/blob/43af60f099e714997fea5d42cc23659cd41d886f/idp-service/src/main/java/io/harness/idp/migration/NameSpaceEntityNextIterationMigration.java#L33)):*
> ```Java
> 
>     BasicDBObject basicDBObject = new BasicDBObject();
>     BasicDBObject updateOps = new BasicDBObject(NamespaceEntity.NamespaceKeys.nextIteration, currentTimeInMillis);
> ```

if we are setting the current timestamp, then would the score computation run only after 12 hours?
What if we set -1, will one computation happen immediately?



_Code quote:_
```Java
currentTimeInMillis
```

**Comment by devesh-harness** [comment]
trigger uts, messagecheck

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52149)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Comment by devesh-harness** [comment]
trigger ut0, ut1, ut2, ut3

**Comment by devesh-harness** [comment]
trigger ut4

**Comment by devesh-harness** [comment]
trigger uts

**Review by sathish-soundarapandian — APPROVED** [review]

**Comment by devesh-harness** [comment]
trigger review

**Pull request merged**
