### PR TITLE
feat: [CDS-35556]: approvals,jira,snow steps variable creator changes

### PR DESCRIPTION
**Pull request by hingerabhinav**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32547)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 18 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32547)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`860-orchestration-steps/src/main/java/io/harness/steps/approval/step/beans/Condition.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/32547#-N0iVD6Z4MuC8HBKfcUK:-N0iVD6Z4MuC8HBKfcUL:btwmw1k) ([raw file](https://github.com/harness/harness-core/blob/81dcdcad23c2394df78f9ebf172297fcba033c57/860-orchestration-steps/src/main/java/io/harness/steps/approval/step/beans/Condition.java#L30)):*
> ```Java
>   @NotNull @VariableExpression(policy = REGULAR_WITH_CUSTOM_FIELD) String key;
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH)
>   @VariableExpression(skipVariableExpression = true)
> ```

if you are skipping value, then how list of condition variables are coming in expression?



_Code quote:_
```Java
@VariableExpression(skipVariableExpression = true)
```
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/jira/JiraUpdateStepVariableCreator.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/32547#-N0iWmUeDypu_M8Khk-B:-N0iWmUeDypu_M8Khk-C:balijz5) ([raw file](https://github.com/harness/harness-core/blob/81dcdcad23c2394df78f9ebf172297fcba033c57/860-orchestration-steps/src/main/java/io/harness/steps/jira/JiraUpdateStepVariableCreator.java#L42)):*
> ```Java
>   public YamlExtraProperties getStepExtraProperties(String fqnPrefix, String localNamePrefix, JiraUpdateStepNode config) {
>     return super.getStepExtraProperties(fqnPrefix, localNamePrefix, config);
>   }
> ```

no need to override



_Code quote:_
```Java
  @Override
  public YamlExtraProperties getStepExtraProperties(String fqnPrefix, String localNamePrefix, JiraUpdateStepNode config) {
    return super.getStepExtraProperties(fqnPrefix, localNamePrefix, config);
  }
```
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/jira/JiraUpdateStepVariableCreator.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/32547#-N0iWrDs5OC78njh-MA2:-N0iWrDs5OC78njh-MA3:b-hp96b4) ([raw file](https://github.com/harness/harness-core/blob/81dcdcad23c2394df78f9ebf172297fcba033c57/860-orchestration-steps/src/main/java/io/harness/steps/jira/JiraUpdateStepVariableCreator.java#L72)):*
> ```Java
>     });
>   }
> ```

this was added to support in v1 API is it?



_Code quote:_
```Java
  @Override
  protected void addVariablesInComplexObject(Map<String, YamlProperties> yamlPropertiesMap,
                                             Map<String, YamlOutputProperties> yamlOutputPropertiesMap, YamlNode yamlNode) {
    List<String> complexFields = new ArrayList<>();
    complexFields.add("fields");

    List<YamlField> fields = yamlNode.fields();
    fields.forEach(field -> {
      if (!field.getName().equals(YAMLFieldNameConstants.UUID) && !complexFields.contains(field.getName())) {
        addFieldToPropertiesMapUnderStep(field, yamlPropertiesMap);
      }
    });

    YamlField yamlField = yamlNode.getField("fields");
    if (VariableCreatorHelper.isNotYamlFieldEmpty(yamlField)) {
      addVariablesForFields(yamlField, yamlPropertiesMap);
    }
  }

  private void addVariablesForFields(YamlField yamlField, Map<String, YamlProperties> yamlPropertiesMap) {
    List<YamlNode> yamlNodes = yamlField.getNode().asArray();
    yamlNodes.forEach(yamlNode -> {
      YamlField uuidNode = yamlNode.getField(YAMLFieldNameConstants.UUID);
      if (uuidNode != null) {
        addFieldToPropertiesMapUnderStep(uuidNode, yamlPropertiesMap);
      }
    });
  }
```
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/jira/beans/JiraField.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/32547#-N0iVVJX9n_igr89FFJB:-N0iVVJX9n_igr89FFJC:b-gnnoqj) ([raw file](https://github.com/harness/harness-core/blob/81dcdcad23c2394df78f9ebf172297fcba033c57/860-orchestration-steps/src/main/java/io/harness/steps/jira/beans/JiraField.java#L31)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> public class JiraField {
>   @NotEmpty @VariableExpression(policy = REGULAR_WITH_CUSTOM_FIELD) String name;
> ```

it should be other way round, name should be skipped and value should be regular with custom field



_Code quote:_
```Java
@VariableExpression(policy = REGULAR_WITH_CUSTOM_FIELD)
```
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/servicenow/ServiceNowCreateStepVariableCreator.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/32547#-N0iVc3iAkF3Kkbuy1QO:-N0iVc3iAkF3Kkbuy1QP:b-jevkgb) ([raw file](https://github.com/harness/harness-core/blob/81dcdcad23c2394df78f9ebf172297fcba033c57/860-orchestration-steps/src/main/java/io/harness/steps/servicenow/ServiceNowCreateStepVariableCreator.java#L34)):*
> ```Java
>     return super.getStepExtraProperties(fqnPrefix, localNamePrefix, config);
>   }
> ```

no need to override if nothing extra you are adding



_Code quote:_
```Java
  @Override
  public YamlExtraProperties getStepExtraProperties(
      String fqnPrefix, String localNamePrefix, ServiceNowCreateStepNode config) {
    return super.getStepExtraProperties(fqnPrefix, localNamePrefix, config);
  }
```
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/servicenow/ServiceNowUpdateStepVariableCreator.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/32547#-N0iVfgK-R_rzOx4aJHU:-N0iVfgK-R_rzOx4aJHV:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/81dcdcad23c2394df78f9ebf172297fcba033c57/860-orchestration-steps/src/main/java/io/harness/steps/servicenow/ServiceNowUpdateStepVariableCreator.java#L33)):*
> ```Java
>       String fqnPrefix, String localNamePrefix, ServiceNowUpdateStepNode config) {
>     return super.getStepExtraProperties(fqnPrefix, localNamePrefix, config);
>   }
> ```

same as above



_Code quote:_
```Java
  @Override
  public YamlExtraProperties getStepExtraProperties(
      String fqnPrefix, String localNamePrefix, ServiceNowUpdateStepNode config) {
    return super.getStepExtraProperties(fqnPrefix, localNamePrefix, config);
  }
```
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/servicenow/beans/ServiceNowField.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/32547#-N0iVi7O-pk0Kek4A-da:-N0iVi7O-pk0Kek4A-db:bf5zjc7) ([raw file](https://github.com/harness/harness-core/blob/81dcdcad23c2394df78f9ebf172297fcba033c57/860-orchestration-steps/src/main/java/io/harness/steps/servicenow/beans/ServiceNowField.java#L31)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> public class ServiceNowField {
>   @NotEmpty @VariableExpression(policy = REGULAR_WITH_CUSTOM_FIELD) String name;
> ```

same as earlier



_Code quote:_
```Java
@VariableExpression(policy = REGULAR_WITH_CUSTOM_FIELD)
```

**Review by archit-harness — DISMISSED** [review]
> Reviewed 3 of 25 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32547)* status: :shipit: complete! ✓

___
*[`860-orchestration-steps/src/main/java/io/harness/steps/jira/JiraUpdateStepVariableCreator.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/32547#-N0iWmUeDypu_M8Khk-B:-N0nw7SXBFn5il1Ckonq:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/81dcdcad23c2394df78f9ebf172297fcba033c57/860-orchestration-steps/src/main/java/io/harness/steps/jira/JiraUpdateStepVariableCreator.java#L42)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

no need to override
</blockquote></details>

done
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/jira/JiraUpdateStepVariableCreator.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/32547#-N0iWrDs5OC78njh-MA2:-N0nwCXcAZeSU5t0yZvn:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/81dcdcad23c2394df78f9ebf172297fcba033c57/860-orchestration-steps/src/main/java/io/harness/steps/jira/JiraUpdateStepVariableCreator.java#L72)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this was added to support in v1 API is it?
</blockquote></details>

done
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/jira/beans/JiraField.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/32547#-N0iVVJX9n_igr89FFJB:-N0nwMfz05_1N1iGOEhn:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/81dcdcad23c2394df78f9ebf172297fcba033c57/860-orchestration-steps/src/main/java/io/harness/steps/jira/beans/JiraField.java#L31)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

it should be other way round, name should be skipped and value should be regular with custom field
</blockquote></details>

done
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/servicenow/ServiceNowCreateStepVariableCreator.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/32547#-N0iVc3iAkF3Kkbuy1QO:-N0nweur5qbU246srsul:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/81dcdcad23c2394df78f9ebf172297fcba033c57/860-orchestration-steps/src/main/java/io/harness/steps/servicenow/ServiceNowCreateStepVariableCreator.java#L34)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

no need to override if nothing extra you are adding
</blockquote></details>

done
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/servicenow/ServiceNowUpdateStepVariableCreator.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/32547#-N0iVfgK-R_rzOx4aJHU:-N0nwk5vC1JkakuvyE6O:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/81dcdcad23c2394df78f9ebf172297fcba033c57/860-orchestration-steps/src/main/java/io/harness/steps/servicenow/ServiceNowUpdateStepVariableCreator.java#L33)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

done
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/servicenow/beans/ServiceNowField.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/32547#-N0iVi7O-pk0Kek4A-da:-N0nwlcJ6eGHRm-GrDKW:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/81dcdcad23c2394df78f9ebf172297fcba033c57/860-orchestration-steps/src/main/java/io/harness/steps/servicenow/beans/ServiceNowField.java#L31)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as earlier
</blockquote></details>

done
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/approval/step/beans/Condition.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/32547#-N0iVD6Z4MuC8HBKfcUK:-N0nwxvh5B5W30nwZDCq:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/81dcdcad23c2394df78f9ebf172297fcba033c57/860-orchestration-steps/src/main/java/io/harness/steps/approval/step/beans/Condition.java#L30)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

if you are skipping value, then how list of condition variables are coming in expression?
</blockquote></details>

done

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32547)* status: :shipit: complete! ✓

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 18 of 25 files at r1, 11 of 13 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32547)* status: :shipit: complete! ✓

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 18 of 25 files at r1, 11 of 13 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32547)* status: :shipit: complete! ✓

**Pull request merged**
