### PR TITLE
[feat]: [PIE-6045]: Add account settings for Pipeline to limit the concurrent executing pipelines, max parallel stages and max parallel steps

### PR DESCRIPTION
**Pull request by brijeshdhakar**
…ncurrent executing pipelines, max parallel stages and max parallel steps

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39320)

### CODE REVIEW

**Review by archit-harness — DISMISSED** [review]
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39320)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39320)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 356 at r3](https://reviewable.io/reviews/harness/harness-core/39320#-NFTEy4OBAKV6G7PGr29:-NFTEy4OBAKV6G7PGr2A:bljm6ye) ([raw file](https://github.com/harness/harness-core/blob/cc198d264bd18e0c14e3a7ada7d4b5fc18257528/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L356)):*
> ```Java
>   private void customValidation(String accountIdentifier, SettingDTO oldSettingDTO, SettingDTO newSettingDTO) {
>     SettingValidator settingValidator = settingValidatorMap.get(oldSettingDTO.getIdentifier());
>     if (settingValidator == null) {
> ```

This "null" check should be removed. Say, if a setting is a part of some group, and there is a validator for that group, and also there is some specific validator for the setting too. In that case, the group validation will be skipped.

**Review by tiwaritejas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39320)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 356 at r3](https://reviewable.io/reviews/harness/harness-core/39320#-NFTEy4OBAKV6G7PGr29:-NFTG4CQ-6AtbWLunCVj:b-moaxm1) ([raw file](https://github.com/harness/harness-core/blob/cc198d264bd18e0c14e3a7ada7d4b5fc18257528/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L356)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

This "null" check should be removed. Say, if a setting is a part of some group, and there is a validator for that group, and also there is some specific validator for the setting too. In that case, the group validation will be skipped.
</blockquote></details>

Both, the setting level as well as group level validations should be carried out independently.

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39320)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 356 at r3](https://reviewable.io/reviews/harness/harness-core/39320#-NFTEy4OBAKV6G7PGr29:-NFTKnSM3jYnOjxfa9eQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cc198d264bd18e0c14e3a7ada7d4b5fc18257528/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L356)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

Both, the setting level as well as group level validations should be carried out independently.
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39320)* status: Some of the checks are too old. 14 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 475 at r5](https://reviewable.io/reviews/harness/harness-core/39320#-NGGnd8O2JhYD2YB2n3F:-NGGnd8O2JhYD2YB2n3G:ba107fd) ([raw file](https://github.com/harness/harness-core/blob/22dc61f20ce4e38471fcbd5a3fd2277e84ae75b8/120-ng-manager/config.yml#L475)):*
> ```YAML
> enableOpentelemetry: false
> 
> maxConcurrentExecutionsConfig:
> ```

Lets wait on these changes, i dont think we should make changes in ng manager like this

**Comment by abhayganvir** [comment]
trigger igp

**Comment by brijeshdhakar** [comment]
Closing this PR. Since Settings framework is going to support the plan based values for a setting. Will reopen or create new PR based on the required changes.

**Pull request closed without merging**
