### PR TITLE
feat: [SSCA-1062]: Add implementation for Listing API of remediation

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57007)

### CODE REVIEW

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepharness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57007)* status: 15 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/mapper/RemediationTrackerMapper.java` line 238 at r1](https://reviewable.io/reviews/harness/harness-core/57007#-NmCIGtL0tLKigc3Qa5K:-NmCIGtL0tLKigc3Qa5L:b-t1rupk) ([raw file](https://github.com/harness/harness-core/blob/90697ee323a9f6e688008d9c827d819d18643f5a/ssca-manager/service/src/main/java/io/harness/ssca/mapper/RemediationTrackerMapper.java#L238)):*
> ```Java
>   }
> 
>   private String formatTimeDuration(long milliSeconds) {
> ```

Why don't you try a humanizer like this one https://github.com/mfornos/humanize?tab=readme-ov-file#datetime-1
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 359 at r1](https://reviewable.io/reviews/harness/harness-core/57007#-NmAaRU05-WTo_fxEL1v:-NmAaRU05-WTo_fxEL1w:bdbixij) ([raw file](https://github.com/harness/harness-core/blob/90697ee323a9f6e688008d9c827d819d18643f5a/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L359)):*
> ```Java
>   }
> 
>   private Criteria getComponentNameFilterCriteria(
> ```

we can keep getFilterCriteria as one method , pass field name . Also check if this is already a part of any existing query builder, if not move it to MongoQueryBuilder
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 374 at r1](https://reviewable.io/reviews/harness/harness-core/57007#-NmCK3Ky2PtShp5IofWv:-NmCK3Ky2PtShp5IofWw:b7w19q8) ([raw file](https://github.com/harness/harness-core/blob/90697ee323a9f6e688008d9c827d819d18643f5a/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L374)):*
> ```Java
>   }
> 
>   private Criteria getCveFilterCriteria(String fieldName, RemediationListingRequestBodyCveFilter filter) {
> ```

keep getFilterCriteria as one method
___
*[`ssca-manager/service/src/test/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImplTest.java` line 402 at r1](https://reviewable.io/reviews/harness/harness-core/57007#-NmCKq-98HjUeAcGfYCY:-NmCKq-98HjUeAcGfYCZ:bxoq46i) ([raw file](https://github.com/harness/harness-core/blob/90697ee323a9f6e688008d9c827d819d18643f5a/ssca-manager/service/src/test/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImplTest.java#L402)):*
> ```Java
>   @Owner(developers = VARSHA_LALWANI)
>   @Category(UnitTests.class)
>   public void listRemediations() {
> ```

I couldn't understand the test flow . Can you write in comment or method name whats the intent ?
Also don't club mutiple UT , this makes it difficult to refactor later. If you are following AAA pattern , make sure your Act & assert follows a sequence

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57007)* status: Some of the checks are too old. 15 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/mapper/RemediationTrackerMapper.java` line 238 at r1](https://reviewable.io/reviews/harness/harness-core/57007#-NmCIGtL0tLKigc3Qa5K:-NmVwAdyBXCrKhuutU3B:b-oeutgi) ([raw file](https://github.com/harness/harness-core/blob/90697ee323a9f6e688008d9c827d819d18643f5a/ssca-manager/service/src/main/java/io/harness/ssca/mapper/RemediationTrackerMapper.java#L238)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Why don't you try a humanizer like this one https://github.com/mfornos/humanize?tab=readme-ov-file#datetime-1
</blockquote></details>

This is not actively maintained and not widely used. I can't find any for java.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 359 at r1](https://reviewable.io/reviews/harness/harness-core/57007#-NmAaRU05-WTo_fxEL1v:-NmVwIuL7sKILECq74qS:b-c2d38q) ([raw file](https://github.com/harness/harness-core/blob/90697ee323a9f6e688008d9c827d819d18643f5a/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L359)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

we can keep getFilterCriteria as one method , pass field name . Also check if this is already a part of any existing query builder, if not move it to MongoQueryBuilder
</blockquote></details>

As I have used separate filter names in the request, doesn't make sense to combine both, as the value comes from different objects.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 374 at r1](https://reviewable.io/reviews/harness/harness-core/57007#-NmCK3Ky2PtShp5IofWv:-NmVwYdq5-lrubqjZPE9:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/90697ee323a9f6e688008d9c827d819d18643f5a/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L374)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

keep getFilterCriteria as one method
</blockquote></details>

same

**Review by deepharness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57007)* status: Some of the checks are too old. 13 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 359 at r1](https://reviewable.io/reviews/harness/harness-core/57007#-NmAaRU05-WTo_fxEL1v:-NmZcMup0NUU-HXzXDA-:bicjw8z) ([raw file](https://github.com/harness/harness-core/blob/90697ee323a9f6e688008d9c827d819d18643f5a/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L359)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

As I have used separate filter names in the request, doesn't make sense to combine both, as the value comes from different objects.
</blockquote></details>

What the intent of getComponentNameFilterCriteria or getCveFilterCriteria ? Are they creating any specific query also at service layer why you want to keep all the query builder inside your service it violated SRP. You should pass the filed names not the whole filter .

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepharness — APPROVED** [review]
> Reviewed 7 of 15 files at r1, 3 of 6 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57007)* status: 1. unresolved discussions.

**Pull request merged**
