### PR TITLE
fix: [PL-32106]: CG SCIM audit trails not handled in legacy. Adding enhancement to handle audit trails now for CG SCIM UserGroup user addition/removal or userGroup updates

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
Currently the audit trails for UserGroup updates in CG SCIM are not captured. This is a missed functionality which is now added as an enhancement to cater to Customer requirement. 

Testing Done:
- Tested in PR environment: All UserGroups updates are now showing up in audit trails
Screenshot 2023-03-23 at 10 59 35 PM

Screenshot 2023-03-23 at 10 59 49 PM

Screenshot 2023-03-23 at 11 00 01 PM
- Unit tests added

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45572)

### CODE REVIEW

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45572)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java` line 181 at r1](https://reviewable.io/reviews/harness/harness-core/45572#-NRHypst1vbeS4r-FMzu:-NRHypst1vbeS4r-FMzv:b-egqucy) ([raw file](https://github.com/harness/harness-core/blob/c83119a9a1f8ed3023e9607cc1bcc2d57077aad2/400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java#L181)):*
> ```Java
>         auditServiceHelper.reportForAuditingUsingAccountId(userGroup.getAccountId(), null, user, Event.Type.REMOVE);
>       });
>     }
> ```

Can we put the entire logic of audit to a separate method.
Helps with readibility.

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java` line 296 at r1](https://reviewable.io/reviews/harness/harness-core/45572#-NRHz4L00RtugG590pVU:-NRHz4L00RtugG590pVV:b9wvmrk) ([raw file](https://github.com/harness/harness-core/blob/c83119a9a1f8ed3023e9607cc1bcc2d57077aad2/400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java#L296)):*
> ```Java
>       wingsPersistence.update(existingGroup, updateOperations);
>       UserGroup updatedUserGroup = userGroupService.get(accountId, groupId);
> ```

similarly here.
I think in both PUT and PATCH there are lots of code common.

We can have one separate method for audit and pass only relevant info to it.



_Code quote:_
```Java
SCIM: 
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java` line 181 at r1](https://reviewable.io/reviews/harness/harness-core/45572#-NRHypst1vbeS4r-FMzu:-NRI2HpY77srSYc_q5Pk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c83119a9a1f8ed3023e9607cc1bcc2d57077aad2/400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java#L181)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Can we put the entire logic of audit to a separate method.
Helps with readibility.
</blockquote></details>

Done.

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java` line 296 at r1](https://reviewable.io/reviews/harness/harness-core/45572#-NRHz4L00RtugG590pVU:-NRI2Iu_Ab7IT6EKKLkl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c83119a9a1f8ed3023e9607cc1bcc2d57077aad2/400-rest/src/main/java/software/wings/scim/ScimGroupServiceImpl.java#L296)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

similarly here.
I think in both PUT and PATCH there are lots of code common.

We can have one separate method for audit and pass only relevant info to it.
</blockquote></details>

Done.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45572)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Pull request merged**
