### PR TITLE
fix: [PL-22567]: GraphQL returns config for customSecretManager

### PR DESCRIPTION
**Pull request by mitishapandey**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34654)

### CODE REVIEW

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34654)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`380-cg-graphql/src/main/java/software/wings/graphql/datafetcher/secretmanager/CustomSecretManagerDataFetcher.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/34654#-N5JqK0y9traKZ3C-N_L:-N5JqK0y9traKZ3C-N_M:bdw11wy) ([raw file](https://github.com/harness/harness-core/blob/be1e294f4031e259792d0cec0f424960fbcbbdfb/380-cg-graphql/src/main/java/software/wings/graphql/datafetcher/secretmanager/CustomSecretManagerDataFetcher.java#L55)):*
> ```Java
>     SecretManagerConfig secretManagerConfig = customSecretsManagerService.getSecretsManager(accountId, uuid);
> 
> //    final QLSecretManagerBuilder builder = QLSecretManager.builder();
> ```

Remove this commented lines
___
*[`380-cg-graphql/src/main/java/software/wings/graphql/datafetcher/secretmanager/CustomSecretManagerDataFetcher.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/34654#-N5JqLVeD3W42nmez15n:-N5JqLVeD3W42nmez15o:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/be1e294f4031e259792d0cec0f424960fbcbbdfb/380-cg-graphql/src/main/java/software/wings/graphql/datafetcher/secretmanager/CustomSecretManagerDataFetcher.java#L87)):*
> ```Java
>     SecretManagerConfig secretManagerConfig = customSecretsManagerService.getSecretsManager(accountId, secretManagerId);
> 
> //    final QLSecretManagerBuilder builder = QLSecretManager.builder();
> ```

same
___
*[`400-rest/src/main/java/software/wings/graphql/datafetcher/secretManager/SecretManagerController.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/34654#-N5JqRsmBqFVG_AZGst9:-N5JqRsmBqFVG_AZGstA:b82kgwr) ([raw file](https://github.com/harness/harness-core/blob/be1e294f4031e259792d0cec0f424960fbcbbdfb/400-rest/src/main/java/software/wings/graphql/datafetcher/secretManager/SecretManagerController.java#L45)):*
> ```Java
>     CustomSecretsManagerConfig customSecretsManagerConfig = (CustomSecretsManagerConfig) secretManager;
>     QLCustomSecretManagerConfig build = QLCustomSecretManagerConfig.builder()
>             .templateId(customSecretsManagerConfig.getTemplateId())
> ```

Can you check once that we have populated all the fields

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34654)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/graphql/datafetcher/secretManager/SecretManagerController.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/34654#-N5JqbeV7FVn2FgpJlBT:-N5JqbeV7FVn2FgpJlBU:b-n0ov5x) ([raw file](https://github.com/harness/harness-core/blob/be1e294f4031e259792d0cec0f424960fbcbbdfb/400-rest/src/main/java/software/wings/graphql/datafetcher/secretManager/SecretManagerController.java#L70)):*
> ```Java
> 
>   public QLSecretManager convertToQLSecretManager(SecretManagerConfig secretManager) {
>     QLSecretManagerBuilder builder1 = QLSecretManager.builder();
> ```

name it builder1

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34654)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/graphql/datafetcher/secretManager/SecretManagerDataFetcher.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/34654#-N5Jqo-r63Z60Ktz3cFr:-N5Jqo-r63Z60Ktz3cFs:b-u9p8mw) ([raw file](https://github.com/harness/harness-core/blob/be1e294f4031e259792d0cec0f424960fbcbbdfb/400-rest/src/main/java/software/wings/graphql/datafetcher/secretManager/SecretManagerDataFetcher.java#L55)):*
> ```Java
>     }
> 
>     //convertToQLSecretManager function called with secretManagerController obj
> ```

remove comment

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34654)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/graphql/schema/type/secretManagers/QLCustomSecretManagerConfig.java` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/34654#-N5JqsEu8uzJlD9mB6Gh:-N5JqsEu8uzJlD9mB6Gi:b-vfv9o5) ([raw file](https://github.com/harness/harness-core/blob/be1e294f4031e259792d0cec0f424960fbcbbdfb/400-rest/src/main/java/software/wings/graphql/schema/type/secretManagers/QLCustomSecretManagerConfig.java#L19)):*
> ```Java
> @Builder
> public class QLCustomSecretManagerConfig implements QLSecretManagerConfig{
> //    templateId: String
> ```

Remove comments

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34654)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 9 of 10 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34654)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34654)* status: :shipit: complete! ✓

**Pull request merged**
