### PR TITLE
[feat]: [CDS-16130]: integrate artifactory with terraform

### PR DESCRIPTION
**Pull request by tmacari-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)

### CODE REVIEW

**Comment by tmacari-harness** [comment]
All files from "**960-api-services/src/test/resources/**" are wiremock resources.
All new logic from **960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java** is just migrated from **400-rest/src/main/java/software/wings/helpers/ext/artifactory/ArtifactoryServiceImpl.java**

**Comment by tmacari-harness** [comment]
trigger FunctionalTest1-Functional_tests

**Comment by tmacari-harness** [comment]
trigger TIbootstrap4-tin4

**Comment by tmacari-harness** [comment]
trigger Recency-recencycheck

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 9 of 25 files at r1, 80 of 83 files at r2, 6 of 18 files at r4, 6 of 17 files at r6, 30 of 30 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)* status: 131 file(s) to review. 1 change requests. 0 of 1 approvals obtained.  (waiting on @satyamshanker)

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/mappers/ArtifactoryResourceMapper.java, line 1 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXhU1j3wKuoamIhASV:-MvXhU1j3wKuoamIhASW:btabx9b) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/mappers/ArtifactoryResourceMapper.java#L1)):*
> ```Java
> package io.harness.cdng.artifact.resources.artifactory.mappers;
> ```

copyright and owned by missing
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceService.java, line 1 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXhWe-7BQsBTZxpEjA:-MvXhWe-7BQsBTZxpEjB:baof1b6) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceService.java#L1)):*
> ```Java
> package io.harness.cdng.artifact.resources.artifactory.service;
> ```

copyright
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java, line 1 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXhYvu5yuYfLYfr4_l:-MvXhYvu5yuYfLYfr4_m:b-dk8tp4) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java#L1)):*
> ```Java
> package io.harness.cdng.artifact.resources.artifactory.service;
> ```

copyright missing
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/manifest/yaml/ArtifactoryStorageConfigDTO.java, line 1 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXhfTEBmXcAUfYqsop:-MvXhfTEBmXcAUfYqsoq:b-dk8tp4) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/yaml/ArtifactoryStorageConfigDTO.java#L1)):*
> ```Java
> package io.harness.cdng.manifest.yaml;
> ```

copyright missing
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/manifest/yaml/FileStorageConfigDTO.java, line 1 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXhkIQ0QLQRUAnWvjL:-MvXhkIQ0QLQRUAnWvjM:b-dk8tp4) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/yaml/FileStorageConfigDTO.java#L1)):*
> ```Java
> package io.harness.cdng.manifest.yaml;
> ```

copyright missing
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/manifest/yaml/FileStorageStoreConfig.java, line 1 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXhl_v5ZukydQrBauc:-MvXhl_v5ZukydQrBaud:b-dqawtp) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/yaml/FileStorageStoreConfig.java#L1)):*
> ```Java
> package io.harness.cdng.manifest.yaml;
> ```

copyright missing and owned by
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformRemoteVarFileConfig.java, line 10 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXi1kQEfgUA8Cn8-Gh:-MvXi1kQEfgUA8Cn8-Gi:b-dk8tp4) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformRemoteVarFileConfig.java#L10)):*
> ```Java
> package io.harness.cdng.provision.terraform;
> 
> import io.harness.annotations.dev.HarnessTeam;
> ```

copyright missing
___
*[960-api-services/src/main/java/io/harness/artifactory/ArtifactoryNgService.java, line 1 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXjozk-j27wec0fMbD:-MvXjozk-j27wec0fMbE:b-dqawtp) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/960-api-services/src/main/java/io/harness/artifactory/ArtifactoryNgService.java#L1)):*
> ```Java
> package io.harness.artifactory;
> ```

copyright missing and owned by
___
*[960-api-services/src/main/java/io/harness/artifactory/ArtifactoryNgServiceImpl.java, line 1 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXjr284h0DHITkBkan:-MvXjr284h0DHITkBkao:b-dqawtp) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/960-api-services/src/main/java/io/harness/artifactory/ArtifactoryNgServiceImpl.java#L1)):*
> ```Java
> package io.harness.artifactory;
> ```

copyright missing and owned by

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)* status: 131 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 1 approvals obtained.  (waiting on @satyamshanker)

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/mappers/ArtifactoryResourceMapper.java, line 1 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXhU1j3wKuoamIhASV:-MvXvsEO78tNeblFIVN4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/mappers/ArtifactoryResourceMapper.java#L1)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

copyright and owned by missing
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceService.java, line 1 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXhWe-7BQsBTZxpEjA:-MvXvtxp3BD21NdNIA6r:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceService.java#L1)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

copyright
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java, line 1 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXhYvu5yuYfLYfr4_l:-MvXvvJC6eqzVV-opxL_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java#L1)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

copyright missing
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/manifest/yaml/ArtifactoryStorageConfigDTO.java, line 1 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXhfTEBmXcAUfYqsop:-MvXvwB43MU6If8j8qF7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/yaml/ArtifactoryStorageConfigDTO.java#L1)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

copyright missing
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/manifest/yaml/FileStorageConfigDTO.java, line 1 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXhkIQ0QLQRUAnWvjL:-MvXvxtP3QphArh6vZU-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/yaml/FileStorageConfigDTO.java#L1)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

copyright missing
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/manifest/yaml/FileStorageStoreConfig.java, line 1 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXhl_v5ZukydQrBauc:-MvXvz4W8bznW5FNPDfM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/yaml/FileStorageStoreConfig.java#L1)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

copyright missing and owned by
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformRemoteVarFileConfig.java, line 10 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXi1kQEfgUA8Cn8-Gh:-MvXw-1B3OMS8hiBdRfG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformRemoteVarFileConfig.java#L10)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

copyright missing
</blockquote></details>

Done.
___
*[960-api-services/src/main/java/io/harness/artifactory/ArtifactoryNgService.java, line 1 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXjozk-j27wec0fMbD:-MvXw05D-2Y5dkfTup_-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/960-api-services/src/main/java/io/harness/artifactory/ArtifactoryNgService.java#L1)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

copyright missing and owned by
</blockquote></details>

Done.
___
*[960-api-services/src/main/java/io/harness/artifactory/ArtifactoryNgServiceImpl.java, line 1 at r10](https://reviewable.io/reviews/harness/harness-core/30587#-MvXjr284h0DHITkBkan:-MvXw1Yg0aRMyu1khzrS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50d54edea4a2db359c382ff7762a171d706aaf50/960-api-services/src/main/java/io/harness/artifactory/ArtifactoryNgServiceImpl.java#L1)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

copyright missing and owned by
</blockquote></details>

Done.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 2 of 8 files at r11, 1 of 1 files at r12, 8 of 8 files at r13, 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)* status: 131 file(s) to review. 0 of 1 approvals obtained.  (waiting on @satyamshanker)

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 59 of 83 files at r2, 1 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)* status: Some of the checks are too old. 131 file(s) to review. 0 of 1 approvals obtained.  (waiting on @satyamshanker)

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 4 of 25 files at r1, 9 of 83 files at r2, 1 of 18 files at r4, 2 of 17 files at r6, 18 of 30 files at r10, 5 of 8 files at r13.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)* status: Some of the checks are too old. 131 file(s) to review. 1 change requests. 0 of 1 approvals obtained.  (waiting on @satyamshanker)

___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java, line 143 at r14](https://reviewable.io/reviews/harness/harness-core/30587#-MvuPbwI5juUsAAz9G4l:-MvuPbwI5juUsAAz9G4m:b-3l2cmq) ([raw file](https://github.com/harness/harness-core/blob/0818d9e1bf4c99c23ceff37838d8e9d60d34d39e/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java#L143)):*
> ```Java
> 
>   @GET
>   @Path("getRepositoriesDetails")
> ```

the path of the API need not need contain the verb. we can just call it `RepositoriesDetails`
Ref: https://cloud.google.com/blog/products/api-management/restful-api-design-nouns-are-good-verbs-are-bad
___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java, line 159 at r14](https://reviewable.io/reviews/harness/harness-core/30587#-MvuPMCzBPqNF6yRvjjW:-MvuPMCzBPqNF6yRvjjX:bbqu240) ([raw file](https://github.com/harness/harness-core/blob/0818d9e1bf4c99c23ceff37838d8e9d60d34d39e/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java#L159)):*
> ```Java
> 
>   @GET
>   @Path("getArtifactBuildsDetails")
> ```

the path of the API need not need to contain the verb. we can just call it `artifactBuildsDetails`
Ref: https://cloud.google.com/blog/products/api-management/restful-api-design-nouns-are-good-verbs-are-bad
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceService.java, line 21 at r14](https://reviewable.io/reviews/harness/harness-core/30587#-MvuRA7W5MYc9vB-MTvn:-MvuRA7W5MYc9vB-MTvo:b-gslt4t) ([raw file](https://github.com/harness/harness-core/blob/0818d9e1bf4c99c23ceff37838d8e9d60d34d39e/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceService.java#L21)):*
> ```Java
> public interface ArtifactoryResourceService {
>   ArtifactoryRepoDetailsDTO getRepositories(
>       String repositoryType, IdentifierRef connectorRef, String orgIdentifier, String projectIdentifier);
> ```

lets use @notnull @notempty annotations to these arguments to avoid confusion in the future

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 4 of 25 files at r1, 3 of 83 files at r2, 1 of 18 files at r4, 1 of 17 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)* status: Some of the checks are too old. 131 file(s) to review. 1 change requests. 0 of 1 approvals obtained.  (waiting on @satyamshanker)

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)* status: 131 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained.  (waiting on @satyamshanker)

___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java, line 143 at r14](https://reviewable.io/reviews/harness/harness-core/30587#-MvuPbwI5juUsAAz9G4l:-MvwRidgALfhaaS4zhcF:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/0818d9e1bf4c99c23ceff37838d8e9d60d34d39e/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java#L143)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

the path of the API need not need contain the verb. we can just call it `RepositoriesDetails`
Ref: https://cloud.google.com/blog/products/api-management/restful-api-design-nouns-are-good-verbs-are-bad
</blockquote></details>

Done
___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java, line 159 at r14](https://reviewable.io/reviews/harness/harness-core/30587#-MvuPMCzBPqNF6yRvjjW:-MvwRkGc5ABDc8k0kwfF:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/0818d9e1bf4c99c23ceff37838d8e9d60d34d39e/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java#L159)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

the path of the API need not need to contain the verb. we can just call it `artifactBuildsDetails`
Ref: https://cloud.google.com/blog/products/api-management/restful-api-design-nouns-are-good-verbs-are-bad
</blockquote></details>

Done
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceService.java, line 21 at r14](https://reviewable.io/reviews/harness/harness-core/30587#-MvuRA7W5MYc9vB-MTvn:-MvwRoCM8fwRWVo5I9ub:b-c3c1rb) ([raw file](https://github.com/harness/harness-core/blob/0818d9e1bf4c99c23ceff37838d8e9d60d34d39e/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceService.java#L21)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets use @notnull @notempty annotations to these arguments to avoid confusion in the future
</blockquote></details>

Added @NonNull

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 124 files at r15, 36 of 83 files at r16, 2 of 18 files at r18, 2 of 17 files at r20, 31 of 44 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)* status: 131 file(s) to review. 1 change requests. 0 of 1 approvals obtained.  (waiting on @satyamshanker)

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 25 files at r1, 1 of 124 files at r15, 38 of 83 files at r16, 13 of 44 files at r24.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)* status: 131 file(s) to review. 1 change requests. 0 of 1 approvals obtained.  (waiting on @satyamshanker)

___
*[960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java, line 210 at r24](https://reviewable.io/reviews/harness/harness-core/30587#-Mw3bE5K8AZ35TY_pe1s:-Mw3bE5K8AZ35TY_pe1t:b-mxwsn1) ([raw file](https://github.com/harness/harness-core/blob/de9e5d1b6450e77f03c20fda96d86b420ae868b1/960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java#L210)):*
> ```Java
>     ArtifactoryRequest repositoryRequest =
>         new ArtifactoryRequestImpl().apiUrl("api/repositories/").method(GET).responseType(JSON);
>     String errorOccurredWhileRetrievingRepositories = "Error occurred while retrieving repositories";
> ```

this can be extracted out as a private final string
___
*[960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java, line 242 at r24](https://reviewable.io/reviews/harness/harness-core/30587#-Mw3bsUg2fHQEXtfmVfu:-Mw3bsUg2fHQEXtfmVfv:b-7wwpay) ([raw file](https://github.com/harness/harness-core/blob/de9e5d1b6450e77f03c20fda96d86b420ae868b1/960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java#L242)):*
> ```Java
>     } catch (SocketTimeoutException e) {
>       log.error(errorOccurredWhileRetrievingRepositories, e);
>       return repositories;
> ```

does this mean that we return a partial set of repositories?

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)* status: 131 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained.  (waiting on @satyamshanker)

___
*[960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java, line 210 at r24](https://reviewable.io/reviews/harness/harness-core/30587#-Mw3bE5K8AZ35TY_pe1s:-Mw4Qvvu-OJrzvq7OKjJ:b-qwc4te) ([raw file](https://github.com/harness/harness-core/blob/de9e5d1b6450e77f03c20fda96d86b420ae868b1/960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java#L210)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this can be extracted out as a private final string
</blockquote></details>

I can do that.
___
*[960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java, line 242 at r24](https://reviewable.io/reviews/harness/harness-core/30587#-Mw3bsUg2fHQEXtfmVfu:-Mw4R2m0CcCEZ8jEdCbg:b-hse52g) ([raw file](https://github.com/harness/harness-core/blob/de9e5d1b6450e77f03c20fda96d86b420ae868b1/960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java#L242)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

does this mean that we return a partial set of repositories?
</blockquote></details>

All the logic from that class vas migrated / extracted from software.wings.helpers.ext.artifactory.ArtifactoryServiceImpl and it is already used in CG.

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)* status: 131 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained.  (waiting on @satyamshanker)

___
*[960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java, line 210 at r24](https://reviewable.io/reviews/harness/harness-core/30587#-Mw3bE5K8AZ35TY_pe1s:-Mw5U5Cr1JL4YS923Xby:b-7rl0kd) ([raw file](https://github.com/harness/harness-core/blob/de9e5d1b6450e77f03c20fda96d86b420ae868b1/960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java#L210)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

I can do that.
</blockquote></details>

done

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)* status: 131 file(s) to review. 0 of 1 approvals obtained.  (waiting on @satyamshanker)

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 2 of 124 files at r15, 74 of 83 files at r16, 2 of 18 files at r18, 2 of 17 files at r20, 40 of 44 files at r24, 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)* status: 131 file(s) to review. 0 of 1 approvals obtained.  (waiting on @satyamshanker)

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 74 of 83 files at r27, 2 of 18 files at r29, 2 of 17 files at r31, 44 of 44 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r36, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 7 of 25 files at r1, 2 of 124 files at r15, 74 of 83 files at r27, 2 of 18 files at r29, 2 of 17 files at r31, 41 of 44 files at r35, 2 of 2 files at r36, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30587)* status: :shipit: complete! ✓

**Pull request merged**
