### PR TITLE
feat: [CDS-36262]: Calculating and populating the rollback duration to timeScaleDB

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
Using `service_infra_info`  table to store rollback duration of each stage. I have written and tested the migration to a column in this table.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39534)

### CODE REVIEW

**Review by shalini-agr — DISMISSED** [review]
> Reviewed 2 of 6 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39534)* status: :shipit: complete! ✓

**Review by naidu-harness — CHANGES_REQUESTED** [review]

**Comment by naidu-harness** [comment]
sample CI PR for reference: https://github.com/harness/harness-core/pull/37545

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39534)* status: :shipit: complete! ✓

___
*[`110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeServiceInfraChangeDataHandlerNew.java` line 267 at r2](https://reviewable.io/reviews/harness/harness-core/39534#-NG0NYp2AdMQgTnc7Yjb:-NG0NYp2AdMQgTnc7Yjc:bxq0jj5) ([raw file](https://github.com/harness/harness-core/blob/c3fbd1033ea6f1079eaa6156973703bddbdd8774/110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeServiceInfraChangeDataHandlerNew.java#L267)):*
> ```Java
>           // rollback_duration
>           if (cdObject.get("rollbackDuration") != null) {
>             columnValueMapping.put("rollback_duration", String.valueOf(cdObject.get("rollbackDuration").toString()));
> ```

nit: Do we need both String.valueOf() and toString()?



_Code quote:_
```Java
String.valueOf(cdObject.get("rollbackDuration").toString()
```

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39534)* status: 1 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/PipelineCoreTimeScaleMigrationDetails.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/39534#-NFwlnT7KV43vmgwftTS-r2-45:-NG0WWtR3E5yrcyp1naw:b32v57) ([raw file](https://github.com/harness/harness-core/blob/c3fbd1033ea6f1079eaa6156973703bddbdd8774/pipeline-service/service/src/main/java/io/harness/pms/migration/PipelineCoreTimeScaleMigrationDetails.java#L45)):*
<details><summary><i>Previously, naidu-harness (Sanyasi Naidu Annepu) wrote…</i></summary><blockquote>

There should be zero dependency on pipeline service
</blockquote></details>

+1

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39534)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeServiceInfraChangeDataHandlerNew.java` line 267 at r2](https://reviewable.io/reviews/harness/harness-core/39534#-NG0NYp2AdMQgTnc7Yjb:-NG0aNTT94ZFOSPp_yGo:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c3fbd1033ea6f1079eaa6156973703bddbdd8774/110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeServiceInfraChangeDataHandlerNew.java#L267)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

nit: Do we need both String.valueOf() and toString()?
</blockquote></details>

Done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/PipelineCoreTimeScaleMigrationDetails.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/39534#-NFwlnT7KV43vmgwftTS-r2-45:-NG0aPJwC2fplhzQBvYn:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c3fbd1033ea6f1079eaa6156973703bddbdd8774/pipeline-service/service/src/main/java/io/harness/pms/migration/PipelineCoreTimeScaleMigrationDetails.java#L45)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done

**Review by naidu-harness — APPROVED** [review]

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39534)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/service/src/main/resources/timescale/create_change_data_capture_tables_timescale.sql` line 101 at r3](https://reviewable.io/reviews/harness/harness-core/39534#-NG0b3Pq605otlWmZRED:-NG0b3Pq605otlWmZREE:bwhauqh) ([raw file](https://github.com/harness/harness-core/blob/af785c3bab899edff14b7233eabe5c4829e3715d/pipeline-service/service/src/main/resources/timescale/create_change_data_capture_tables_timescale.sql#L101)):*
> ```TSQL
>      executionId text  NULL,
>      artifact_image text  NULL,
>      rollback_duration bigint NULL);
> ```

Is this needed?

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39534)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/resources/timescale/create_change_data_capture_tables_timescale.sql` line 101 at r3](https://reviewable.io/reviews/harness/harness-core/39534#-NG0b3Pq605otlWmZRED:-NG0cccxCa662q3SNZcB:bscggad) ([raw file](https://github.com/harness/harness-core/blob/af785c3bab899edff14b7233eabe5c4829e3715d/pipeline-service/service/src/main/resources/timescale/create_change_data_capture_tables_timescale.sql#L101)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Is this needed?
</blockquote></details>

No not necessary. Just wanted to save addition migration query in case the table is getting created again. I have removed it

**Review by shalini-agr — APPROVED** [review]
> Reviewed 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39534)* status: 1 change requests. 2. unresolved discussions.

**Review by GoelPratyush99 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39534#-:-NG0uZKyEtT3LR8GNULc:bnfp4nl)* status: 1 change requests. 2. unresolved discussions.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 5 of 10 files at r2, 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39534)* status: 1. unresolved discussions.

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 1 of 10 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39534#-:-NG0zFtVC-zX6Ib7vQU5:bnfp4nl)* status: :shipit: complete! ✓

**Review by vikyathharekal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39534)* status: :shipit: complete! ✓

**Pull request merged**
