### PR TITLE
[fix]: [DEL-4655]: remove spring data mongodb dependencies

### PR DESCRIPTION
**Pull request by raghuAtWings**
## Describe your changes
Removing the following dependencies from 260-delegate
420-delegate-service
890-sm-core
910-delegate-service-driver
950-ng-project-n-orgs
955-filters-sdk
958-migration-sdk
959-ng-persistence
clients/notification
platform-service/modules/notification-service/contract

Since many delegate tasks and related classes were part of 890-sm-core, I created 890-sm-delegate and moved delegate related classes there.  

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36743)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 131 Issues 
* Vulnerability 35 Vulnerabilities 
 * Code issue 92 Code issues 
* Anti-pattern 4 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36743)

**Review by mdmilic — CHANGES_REQUESTED** [review]
This change has quite a bit of files changed and I'm guessing most of them are module rename. 
Generally you should do these things in separate PRs or at least a separate commit that we can diff against, because it's really hard knowing what to look for otherwise. 
Can you please update PR description with what exactly are you changing and what the reviewer should keep an eye at (e.g. what files/modules, what are just renames etc...)

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36743#-:-NAGbsIW7BqTw8ch_AZE:b-sivpr0)* status: 125 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 122 of 125 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36743)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
trigger codebasehash

**Comment by raghuAtWings** [comment]
trigger compile

**Comment by raghuAtWings** [comment]
trigger ti0

**Comment by raghuAtWings** [comment]
trigger ti1

**Comment by raghuAtWings** [comment]
trigger ti2

**Comment by raghuAtWings** [comment]
trigger ti3

**Comment by raghuAtWings** [comment]
trigger ti4

**Review by mdmilic — DISMISSED** [review]
> Reviewed 117 of 125 files at r1, 12 of 12 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36743)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
trigger ti0

**Comment by raghuAtWings** [comment]
trigger ti1

**Comment by raghuAtWings** [comment]
trigger ti2

**Comment by raghuAtWings** [comment]
trigger ti3

**Comment by raghuAtWings** [comment]
trigger ti4

**Comment by raghuAtWings** [comment]
trigger ti4

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 6 of 6 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36743)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
trigger codebasehash

**Review by praveensugavanam — APPROVED** [review]
> Reviewed 113 of 125 files at r1, 12 of 12 files at r2, 1 of 6 files at r3, 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36743)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 113 of 125 files at r1, 12 of 12 files at r2, 6 of 6 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36743)* status: :shipit: complete! ✓

**Pull request merged**
