### PR TITLE
feat: [SRM-15052] Update API for health score to be used for srm analysis step activity as well

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Describe your changes

Currently we only have endTime and duration in the API and frontend sends by default 4 hours duration, for analysis step we need longer duration. startTime would be analysis startTime - 2hours, and endTime would be activityEndTime. This period may not exactly fit in our default bucket for durations, so we are handling this in the BE

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50401)

### CODE REVIEW

**Comment by Varsha-lalwani** [comment]
trigger uts_JDK11

**Review by naveen-harness — DISMISSED** [review]

**Comment by Varsha-lalwani** [comment]
trigger messagecheck

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50401)* status: 5 file(s) to review. 1 change requests. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/DurationDTO.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/50401#-N_CgE_B9yB-I9nh3eMv:-N_CgE_B9yB-I9nh3eMw:b6q6lau) ([raw file](https://github.com/harness/harness-core/blob/16a042c3b0c8ac5453012f8e1b5ef989688b9a2a/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/DurationDTO.java#L28)):*
> ```Java
>   }
> 
>   public static DurationDTO findClosestGreaterDurationDTO(Duration targetDuration) {
> ```

We should add testcases for this. will help in verifying edgecases.
Similar to roundTo nearest 5 minute boundary.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/MonitoredServiceResource.java` line 245 at r1](https://reviewable.io/reviews/harness/harness-core/50401#-N_CgYs8DonYZeiUtEL_:-N_CgYs8DonYZeiUtELa:bqfh4kn) ([raw file](https://github.com/harness/harness-core/blob/16a042c3b0c8ac5453012f8e1b5ef989688b9a2a/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/MonitoredServiceResource.java#L245)):*
> ```Java
>   }
> 
>   private Instant validateDurationAndGetStartTime(DurationDTO durationDTO, Long startTime, Long endTime) {
> ```

We should have a validation utils rather than polluting the resource file.

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50401)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/DurationDTO.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/50401#-N_CgE_B9yB-I9nh3eMv:-N_EDEtKC0SQa6zCNZK5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16a042c3b0c8ac5453012f8e1b5ef989688b9a2a/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/DurationDTO.java#L28)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

We should add testcases for this. will help in verifying edgecases.
Similar to roundTo nearest 5 minute boundary.
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/MonitoredServiceResource.java` line 245 at r1](https://reviewable.io/reviews/harness/harness-core/50401#-N_CgYs8DonYZeiUtEL_:-N_EDGLC5JpwQbC7DZUC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16a042c3b0c8ac5453012f8e1b5ef989688b9a2a/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/MonitoredServiceResource.java#L245)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

We should have a validation utils rather than polluting the resource file. 
</blockquote></details>

Done.

**Comment by Varsha-lalwani** [comment]
trigger uts_JDK11

**Review by deepak-harness — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50401)* status: :shipit: complete! ✓

**Pull request merged**
