### PR TITLE
[fix]: [CDS-34795]: API change for Resolving Templates in Pipeline Yaml

### PR DESCRIPTION
**Pull request by vtxorxwitty**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31369)

### CODE REVIEW

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31369)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java, line 32 at r2](https://reviewable.io/reviews/harness/harness-core/31369#-MyBSCD38-hXxWoKAMja:-MyBSCD44WB73flZfZnz:b-bev7u0) ([raw file](https://github.com/harness/harness-core/blob/23f4532fbae359239ee2d51acdc12ae327d000fd/890-pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java#L32)):*
> ```Java
> public class PMSPipelineResponseDTO {
>   private String yamlPipeline;
>   private String resolvedTemplatesPipelineYaml;
> ```

Add schema annotation on this field stating the description of this field. It has been pending for other fields in this object but we should add for new fields.

**Review by vaibhav-si — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31369)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31369)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java, line 32 at r2](https://reviewable.io/reviews/harness/harness-core/31369#-MyBSCD38-hXxWoKAMja:-MyGJOYeE-JDlCLTyc5i:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/23f4532fbae359239ee2d51acdc12ae327d000fd/890-pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java#L32)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Add schema annotation on this field stating the description of this field. It has been pending for other fields in this object but we should add for new fields.
</blockquote></details>

Done.

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31369)* status: :shipit: complete! ✓

**Pull request merged**
