### PR TITLE
feat:[CDS-84744]: Reversing the events for delete stack step

### PR DESCRIPTION
**Pull request by piyush-bhuwalka**
## Describe your changes

Reversing the events for delete stack step. The stack events for delete stack step were appearing in wrong order . We have fixed the events. No unit tests can be added for this, as these are log order changes

 

https://github.com/harness/harness-core/assets/100153994/52cfa463-3317-46ab-966f-613d35afdc38

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55628)

### CODE REVIEW

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Comment by piyush-bhuwalka** [comment]
trigger messagecheck

**Review by PragyeshMishra01 — APPROVED** [review]

**Comment by piyush-bhuwalka** [comment]
trigger messagecheck

**Review by nassergonzalez — APPROVED** [review]

**Review by ivan-83 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55628)* status: 1 file(s) to review. 

___
*[`960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java` line 497 at r1](https://reviewable.io/reviews/harness/harness-core/55628#-NjgCtFj5D9WcT-Bijbm:-NjgCtFj5D9WcT-Bijbn:b-oq2kh5) ([raw file](https://github.com/harness/harness-core/blob/e6c75906e2331f6bf4f96c995141ff0d2d8f4ca6/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L497)):*
> ```Java
>             new DescribeStackEventsRequest().withStackName(describeStacksRequest.getStackName()), awsConfig,
>             lastStackEventsTs);
>         Collections.reverse(stackEvents);
> ```

@piyush-bhuwalka Are we reversing stack events because of printing stack events on the UI console in reverse order?

**Comment by piyush-bhuwalka** [comment]
*[`960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java` line 497 at r1](https://reviewable.io/reviews/harness/harness-core/55628#-NjgCtFj5D9WcT-Bijbm:-NjgKF9TA1YtIHzqihoQ:bfhkyy) ([raw file](https://github.com/harness/harness-core/blob/e6c75906e2331f6bf4f96c995141ff0d2d8f4ca6/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L497)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

@piyush-bhuwalka Are we reversing stack events because of printing stack events on the UI console in reverse order?
</blockquote></details>

Yes @ivan-83 , the stack events are received in reverse order to us in the BE. So to print it in the correct order, we reverse it

**Review by ivan-83 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55628)* status: 1 file(s) to review.

**Comment by piyush-bhuwalka** [comment]
trigger review

**Pull request merged**
