### PR TITLE
fix: [PL-38777]: Fix for issue on fetching API-keys is throwing error

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary
- Issue: On API key listing page on the switch account, the list api key throws 500
-  Fix: load support user on user context while fetching parent identifiers

Test:
-Local

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48998)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
tigger uts

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 373 at r2](https://reviewable.io/reviews/harness/harness-core/48998#-NXXS_o74exLHvzLhFgZ:-NXXS_o74exLHvzLhFg_:byvnkpt) ([raw file](https://github.com/harness/harness-core/blob/746a9153b9f53451c4c6fcae70d09b1b747c8eb2/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L373)):*
> ```Java
>   @GET
>   @Path("/support-users/{userId}")
>   public RestResponse<Optional<UserInfo>> getUserg(@PathParam("userId") String userId,
> ```

Why do we need new method? Can we not use the above one?

**Comment by piyush-harness** [comment]
*[`930-ng-core-clients/src/main/java/io/harness/user/remote/UserClient.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/48998#-NXXTHVKBhjecdyMxCTn:-NXXTHVKBhjecdyMxCTo:bwwxen6) ([raw file](https://github.com/harness/harness-core/blob/746a9153b9f53451c4c6fcae70d09b1b747c8eb2/930-ng-core-clients/src/main/java/io/harness/user/remote/UserClient.java#L125)):*
> ```Java
>   @GET(USERS_API + "/{userId}") Call<RestResponse<Optional<UserInfo>>> getUserById(@Path("userId") String userId);
> 
>   @GET(USERS_API_INCLUDE_SUPPORT_USER + "/{userId}")
> ```

I don't think we need another API you can call the same API with loadSupportAccount=true

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/intfc/UserService.java` line 237 at r2](https://reviewable.io/reviews/harness/harness-core/48998#-NXXTsqX7g6tJ8i48SW5:-NXXTsqX7g6tJ8i48SW6:b-bd4pn8) ([raw file](https://github.com/harness/harness-core/blob/746a9153b9f53451c4c6fcae70d09b1b747c8eb2/400-rest/src/main/java/software/wings/service/intfc/UserService.java#L237)):*
> ```Java
> 
>   /**
>    * Gets the user and loads the user groups for the given account.
> ```

nit: Gets the user by ID and optionally load supportAccounts

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48998)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3412 at r2](https://reviewable.io/reviews/harness/harness-core/48998#-NXXTX2b5lQlemr8masH:-NXXTX2b5lQlemr8masI:b-z6hyie) ([raw file](https://github.com/harness/harness-core/blob/746a9153b9f53451c4c6fcae70d09b1b747c8eb2/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3412)):*
> ```Java
>     }
>     loadUserGroups(accountId, user);
>     loadSupportAccounts(user);
> ```

Why do we need to load here?

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
Verified support users getting loaded as part of get user call from api list page 
image

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 373 at r2](https://reviewable.io/reviews/harness/harness-core/48998#-NXXS_o74exLHvzLhFgZ:-NXgEeNC2hT3vKa1Qzer:bnk3y2l) ([raw file](https://github.com/harness/harness-core/blob/746a9153b9f53451c4c6fcae70d09b1b747c8eb2/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L373)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why do we need new method? Can we not use the above one?
</blockquote></details>

In general, to avoid refactoring multiple places.
 Removed now, using getUserById(). refactored getUserByid() usage for NG manager files. 
For CG side side, found a way to load support accounts without refactoring

**Comment by jennyjames21** [comment]
*[`930-ng-core-clients/src/main/java/io/harness/user/remote/UserClient.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/48998#-NXXTHVKBhjecdyMxCTn:-NXgFEDdEfLNQdYpZysf:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/746a9153b9f53451c4c6fcae70d09b1b747c8eb2/930-ng-core-clients/src/main/java/io/harness/user/remote/UserClient.java#L125)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

I don't think we need another API you can call the same API with loadSupportAccount=true
</blockquote></details>

updated

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3412 at r2](https://reviewable.io/reviews/harness/harness-core/48998#-NXXTX2b5lQlemr8masH:-NXgFFiO3IJYbilfo2YG:b-vwajzw) ([raw file](https://github.com/harness/harness-core/blob/746a9153b9f53451c4c6fcae70d09b1b747c8eb2/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3412)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why do we need to load here?
</blockquote></details>

removed, by mistake

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/intfc/UserService.java` line 237 at r2](https://reviewable.io/reviews/harness/harness-core/48998#-NXXTsqX7g6tJ8i48SW5:-NXgFI_LEGkA0biNISEv:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/746a9153b9f53451c4c6fcae70d09b1b747c8eb2/400-rest/src/main/java/software/wings/service/intfc/UserService.java#L237)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

nit: Gets the user by ID and optionally load supportAccounts
</blockquote></details>

done

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 363 at r6](https://reviewable.io/reviews/harness/harness-core/48998#-NXkOrXQ7Q3a5Qd9_C1b:-NXkOrXQ7Q3a5Qd9_C1c:b-3u3l6v) ([raw file](https://github.com/harness/harness-core/blob/976be03eedad25d437463c80b408a669650f3bcd/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L363)):*
> ```Java
>       @QueryParam("includeSupportAccounts") @DefaultValue("false") boolean includeSupportAccounts) {
>     try {
>       User user = userService.get(userId);
> ```

Can we call userService,get(userId,includeSupportAccount) directly?

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48998)* status: 21 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3294 at r1](https://reviewable.io/reviews/harness/harness-core/48998#-NXkObU9BnNK6xt1VVFA:-NXkObUABw0u9fpf1uej:b-fwa67q) ([raw file](https://github.com/harness/harness-core/blob/0d3b91206cea487c6ec63e27f465e8cd8bb42d60/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3294)):*
> ```Java
> 
>   @Override
>   public User get(String userId, boolean includeSupportAccounts) {
> ```

Why remove this method? Its rightly abstracting supportAccountLoad using boolean.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3294 at r1](https://reviewable.io/reviews/harness/harness-core/48998#-NXkObU9BnNK6xt1VVFA:-NXkPLk2603dQjreLbo9:b-ti9w8m) ([raw file](https://github.com/harness/harness-core/blob/0d3b91206cea487c6ec63e27f465e8cd8bb42d60/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3294)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why remove this method? Its rightly abstracting supportAccountLoad using boolean.
</blockquote></details>

i introduced that on the previous iteration.  diff with latest

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 363 at r6](https://reviewable.io/reviews/harness/harness-core/48998#-NXkOrXQ7Q3a5Qd9_C1b:-NXkPrIXEc65PS_xcsPz:b-l0gquv) ([raw file](https://github.com/harness/harness-core/blob/976be03eedad25d437463c80b408a669650f3bcd/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L363)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Can we call userService,get(userId,includeSupportAccount) directly?
</blockquote></details>

i removed that method (introduced by me on prev iteration) --   userService,get(userId,includeSupportAccount)

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r7, 1 of 1 files at r8, 6 of 6 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48998)* status: 23 file(s) to review. 1 of 2 approvals obtained.

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger messagecheck

**Review by sribalij — APPROVED** [review]

**Review by ashishsanodia-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48998)* status: 22 file(s) to review.

**Review by ashishsanodia-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48998#-:-NXnLzwMBVVLqBt1h69t:bnfp4nl)* status: 22 file(s) to review.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 9 of 15 files at r3, 1 of 1 files at r5, 4 of 4 files at r6, 1 of 3 files at r7, 1 of 1 files at r8, 6 of 6 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48998)* status: :shipit: complete! ✓

**Pull request merged**
