### PR TITLE
[feat]: [CDS-46394]: azure web app overrieds fix

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Describe your changes
Service overrides for Application Settings and Connection Strings are now applied, both from Environment overrides level and Environment Service overrides.
webapp_overrides

webapp_overrides_logs

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41677)

### CODE REVIEW

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41677)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java` line 247 at r3](https://reviewable.io/reviews/harness/harness-core/41677#-NJov1zA5qL4DzDMZp51:-NJov1zA5qL4DzDMZp52:b-5cg8lg) ([raw file](https://github.com/harness/harness-core/blob/0269ad7c7843240ada8b8662bb88303372ce5b34/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java#L247)):*
> ```Java
>         ambiance, RefObjectUtils.getOutcomeRefObject(ServiceStepV3.SERVICE_CONNECTION_STRINGS_SWEEPING_OUTPUT));
>     if (!resolveOptional.isFound()) {
>       log.info("Could not find connectionStringsSweepingOutput for the stage.");
> ```

If we are going to log msg here we need more info like account id ...  I suggest using only resolveOptional.isFound() in fetchWebAppConfig(Ambiance ambiance) method
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java` line 257 at r3](https://reviewable.io/reviews/harness/harness-core/41677#-NJp1enp-2MuxnmgFvH9:-NJp1ent16qzjocPEBcK:bstge6t) ([raw file](https://github.com/harness/harness-core/blob/0269ad7c7843240ada8b8662bb88303372ce5b34/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java#L257)):*
> ```Java
>         ambiance, RefObjectUtils.getOutcomeRefObject(ServiceStepV3.SERVICE_APP_SETTINGS_SWEEPING_OUTPUT));
>     if (!resolveOptional.isFound()) {
>       log.info("Could not find appSettingsSweepingOutput for the stage.");
> ```

the same as above
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 253 at r3](https://reviewable.io/reviews/harness/harness-core/41677#-NJp5ScW20ffBB_viPQp:-NJp5ScXBIfNoImjlfzN:b-jtf62v) ([raw file](https://github.com/harness/harness-core/blob/0269ad7c7843240ada8b8662bb88303372ce5b34/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L253)):*
> ```Java
>     }
>     List<ConnectionStringsConfiguration> finalConnectionStrings;
>     if (serviceOverrideConfig == null && ngEnvironmentConfig == null) {
> ```

I would rather go with 2 public methods for env and service overrides for aa settings and conn string and 2 public methods for service configs the having this different then null logic. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 256 at r3](https://reviewable.io/reviews/harness/harness-core/41677#-NJp67Np72ACKW_y5rFT:-NJp67Np72ACKW_y5rFU:bs9g889) ([raw file](https://github.com/harness/harness-core/blob/0269ad7c7843240ada8b8662bb88303372ce5b34/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L256)):*
> ```Java
>       final List<ConnectionStringsConfiguration> svcConnectionStrings =
>           getSvcConnectionStrings(serviceV2Config.getNgServiceV2InfoConfig());
>       finalConnectionStrings = svcConnectionStrings;
> ```

^^^ not needed
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 271 at r3](https://reviewable.io/reviews/harness/harness-core/41677#-NJp6NrzDyCnS-dd5VOM:-NJp6NrzDyCnS-dd5VON:b-urmd6e) ([raw file](https://github.com/harness/harness-core/blob/0269ad7c7843240ada8b8662bb88303372ce5b34/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L271)):*
> ```Java
>               .build();
>       sweepingOutputService.consume(
>           ambiance, configFilesSweepingOutputName, connectionStringsSweepingOutput, StepCategory.STAGE.name());
> ```

when connectionStringsSweepingOutput is null do we still need to save it?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 283 at r3](https://reviewable.io/reviews/harness/harness-core/41677#-NJp76fPEg87KcSc5HsE:-NJp76fQ9PYCo6YRMGeu:bstge6t) ([raw file](https://github.com/harness/harness-core/blob/0269ad7c7843240ada8b8662bb88303372ce5b34/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L283)):*
> ```Java
>     }
>     List<ApplicationSettingsConfiguration> finalAppSettings;
>     if (serviceOverrideConfig == null && ngEnvironmentConfig == null) {
> ```

the same as above
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 303 at r3](https://reviewable.io/reviews/harness/harness-core/41677#-NJp7RsrCAbHwAVjG_DI:-NJp7RsrCAbHwAVjG_DJ:b-vmeq3x) ([raw file](https://github.com/harness/harness-core/blob/0269ad7c7843240ada8b8662bb88303372ce5b34/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L303)):*
> ```Java
> 
>   @VisibleForTesting
>   public static List<ConnectionStringsConfiguration> prepareFinalConnectionStrings(
> ```

this method should be called from ServiceStepV3#getNGEnvironmentConfig directly just rename it
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 320 at r3](https://reviewable.io/reviews/harness/harness-core/41677#-NJp7EJh-eQIH8SKLB7V:-NJp7EJiAMw5R8w2mmyU:b-vmeq3x) ([raw file](https://github.com/harness/harness-core/blob/0269ad7c7843240ada8b8662bb88303372ce5b34/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L320)):*
> ```Java
> 
>   @VisibleForTesting
>   public static List<ApplicationSettingsConfiguration> prepareFinalAppSettings(NGServiceV2InfoConfig serviceV2Config,
> ```

this method should be called from ServiceStepV3#getNGEnvironmentConfig directly just rename it



_Code quote (from 125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java):_
```Java
getNGEnvironmentConfig
```

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41677)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 253 at r3](https://reviewable.io/reviews/harness/harness-core/41677#-NJp5ScW20ffBB_viPQp:-NJp8BcyEpVaryQXd3_P:b5msm9a) ([raw file](https://github.com/harness/harness-core/blob/0269ad7c7843240ada8b8662bb88303372ce5b34/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L253)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I would rather go with 2 public methods for env and service overrides for aa settings and conn string and 2 public methods for service configs the having this different then null logic. 
</blockquote></details>

I would rather go with 2 public methods for env and service overrides for app settings and conn string and 2 public methods for service configs than having null logic check.

**Review by acasian-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41677)* status: 5 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/41677#-NJt7-YL98vJ9faaehA4:-NJt7-YM63I3oO6aXIjy:bklek7k) (no related file):*
@vladimir-peric please describe the changes and attach screenshots with before/after behaviour.

___
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 352 at r3](https://reviewable.io/reviews/harness/harness-core/41677#-NJt8cO21wkWfQBSjqYM:-NJt8cO21wkWfQBSjqYN:b-5q4qxb) ([raw file](https://github.com/harness/harness-core/blob/0269ad7c7843240ada8b8662bb88303372ce5b34/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L352)):*
> ```Java
> 
>   private static List<ConnectionStringsConfiguration> getSvcConnectionStrings(NGServiceV2InfoConfig serviceV2Config) {
>     if (AzureWebAppServiceSpec.class.isAssignableFrom(
> ```

what is this check for?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 354 at r3](https://reviewable.io/reviews/harness/harness-core/41677#-NJt8iKQ1dYQbIBRYpxx:-NJt8iKQ1dYQbIBRYpxy:b-scbcd1) ([raw file](https://github.com/harness/harness-core/blob/0269ad7c7843240ada8b8662bb88303372ce5b34/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L354)):*
> ```Java
>     if (AzureWebAppServiceSpec.class.isAssignableFrom(
>             serviceV2Config.getServiceDefinition().getServiceSpec().getClass())
>         && ((AzureWebAppServiceSpec) serviceV2Config.getServiceDefinition().getServiceSpec()).getConnectionStrings()
> ```

if it's not a webapp spec, isn't it going to throw class cast exception?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 363 at r3](https://reviewable.io/reviews/harness/harness-core/41677#-NJt8v_81_S_MkPuZ64I:-NJt8v_81_S_MkPuZ64J:b610ksj) ([raw file](https://github.com/harness/harness-core/blob/0269ad7c7843240ada8b8662bb88303372ce5b34/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L363)):*
> ```Java
> 
>   private static List<ApplicationSettingsConfiguration> getSvcAppSettings(NGServiceV2InfoConfig serviceV2Config) {
>     if (AzureWebAppServiceSpec.class.isAssignableFrom(
> ```

imho, this is helper for all service types, we should safely check the type of service definition. Also make it extensible for other service types.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41677)* status: 8 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by tchaurasiya — DISMISSED** [review]
> Reviewed 1 of 4 files at r1, 1 of 4 files at r2, 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41677)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41677)* status: 1 file(s) to review.

**Review by markoharness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41677)* status: 1 file(s) to review.

**Comment by vladimir-peric** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 352 at r3](https://reviewable.io/reviews/harness/harness-core/41677#-NJt8cO21wkWfQBSjqYM:-NKI_xwsAbZyDoHTN3Fn:bpl1x59) ([raw file](https://github.com/harness/harness-core/blob/0269ad7c7843240ada8b8662bb88303372ce5b34/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L352)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

what is this check for?
</blockquote></details>

The logic is a bit enhanced here now, so only in case spec if of type WebAppSpec connection strings and app settings are retrieved.

**Comment by vladimir-peric** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 354 at r3](https://reviewable.io/reviews/harness/harness-core/41677#-NJt8iKQ1dYQbIBRYpxx:-NKIaRbW4UIa69U1u3o-:bzavout) ([raw file](https://github.com/harness/harness-core/blob/0269ad7c7843240ada8b8662bb88303372ce5b34/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L354)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

if it's not a webapp spec, isn't it going to throw class cast exception?
</blockquote></details>

With this logic we are safe from that.

**Comment by vladimir-peric** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 363 at r3](https://reviewable.io/reviews/harness/harness-core/41677#-NJt8v_81_S_MkPuZ64I:-NKIae-e5AQG3DHKsyms:bijvq6h) ([raw file](https://github.com/harness/harness-core/blob/0269ad7c7843240ada8b8662bb88303372ce5b34/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L363)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

imho, this is helper for all service types, we should safely check the type of service definition. Also make it extensible for other service types.
</blockquote></details>

We are checking if the spec is of type WebAppSpec now, which makes this applicable to any service definition with such spec.

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41677#-:-NKIcx0cCXMnjLstoX1d:bnfp4nl)* status: 3. unresolved discussions.

**Comment by vladimir-peric** [comment]
trigger ti3

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41677)* status: 2 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41677#-:-NKIyLDQ2X7qEZoeASL_:bnfp4nl)* status: 2 file(s) to review. 3. unresolved discussions.

**Review by acasian-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41677#-:-NKJMjaQDZks22kfYrDF:bnfp4nl)* status: 1. unresolved discussions.

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41677)* status: :shipit: complete! ✓

**Pull request merged**
