### PR TITLE
fix: [DEL-3789]: Print delegate configuration in delegate logs

### PR DESCRIPTION
**Pull request by gaurav-jain1**
Changes to print delegateConfiguration (without secrets) in delegate logs.
This will be helpful in debugging issues in customer environment, where we don't have access to config-delegate.yml

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32236)

### CODE REVIEW

**Review by mdmilic — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32236)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[960-api-services/src/main/java/io/harness/delegate/configuration/DelegateConfiguration.java, line 79 at r1](https://reviewable.io/reviews/harness/harness-core/32236#-N-YMxgx-bdkFWzTgNjU:-N-YMxgyBbQUhwvIS93-:b-3gkde0) ([raw file](https://github.com/harness/harness-core/blob/f2e96a81249be0ee7988dbf542a68017b2a2ad01/960-api-services/src/main/java/io/harness/delegate/configuration/DelegateConfiguration.java#L79)):*
> ```Java
>   }
> 
>   public String getDelegateConfigAsString() {
> ```

You can do this much better/easier with Lombok @ToString 
https://projectlombok.org/features/ToString
From experience it's better to use includes then excludes, so combination of 
@ToString(onlyExplicitlyIncluded = true) and @ToString.Include on fields you want to include will do the trick. This will also fix our toString(), so that no one can mistakenly print secrets.

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32236)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[960-api-services/src/main/java/io/harness/delegate/configuration/DelegateConfiguration.java, line 79 at r1](https://reviewable.io/reviews/harness/harness-core/32236#-N-YMxgx-bdkFWzTgNjU:-N-crRI49JnWNyJi0jJT:bislohj) ([raw file](https://github.com/harness/harness-core/blob/f2e96a81249be0ee7988dbf542a68017b2a2ad01/960-api-services/src/main/java/io/harness/delegate/configuration/DelegateConfiguration.java#L79)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You can do this much better/easier with Lombok @ToString 
https://projectlombok.org/features/ToString
From experience it's better to use includes then excludes, so combination of 
@ToString(onlyExplicitlyIncluded = true) and @ToString.Include on fields you want to include will do the trick. This will also fix our toString(), so that no one can mistakenly print secrets. 
</blockquote></details>

Sure, will use this

**Review by mdmilic — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32236)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32236#-:-N-xGlhV07z8eLTB5wWo:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
