### PR TITLE
[fix]: [PIE-2334]: Fix the setup usage issue in the full sync flow for pipelines

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30191)

### CODE REVIEW

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30191)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30191)* status: :shipit: complete! ✓

**Review by DeepakPatankar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30191)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30191)* status: 2 file(s) to review.

**Comment by sahilhindwani-harness** [comment]
___
*[800-pipeline-service/src/main/java/io/harness/pms/filter/creation/FilterCreatorMergeService.java, line 88 at r2](https://reviewable.io/reviews/harness/harness-core/30191#-MuAher_CFGuGEBR0phY:-MuAher_CFGuGEBR0phZ:bs8j94x) ([raw file](https://github.com/harness/harness-core/blob/e19ae11655ff1e6d0aeaae70c132a92ef9c18b7f/800-pipeline-service/src/main/java/io/harness/pms/filter/creation/FilterCreatorMergeService.java#L88)):*
> ```Java
>         obtainFiltersRecursively(services, dependencies, filters, setupMetadataBuilder.build());
>     validateFilterCreationBlobResponse(response);
>     deleteExistingSetupUsages(pipelineEntity);
> ```

why are we deleting here? we fire an event wherein we delete this already in publishSetupUsageEvent I believe.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30191)* status: 3 file(s) to review. 1. unresolved discussions. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/filter/creation/FilterCreatorMergeService.java, line 88 at r2](https://reviewable.io/reviews/harness/harness-core/30191#-MuAher_CFGuGEBR0phY:-MuAkR1a2oLUCHmtYkd2:b-4jocpr) ([raw file](https://github.com/harness/harness-core/blob/e19ae11655ff1e6d0aeaae70c132a92ef9c18b7f/800-pipeline-service/src/main/java/io/harness/pms/filter/creation/FilterCreatorMergeService.java#L88)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

why are we deleting here? we fire an event wherein we delete this already in publishSetupUsageEvent I believe.
</blockquote></details>

Added check for FS

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30191)* status: 3 file(s) to review. 1. unresolved discussions.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30191)* status: 1. unresolved discussions.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30191)* status: :shipit: complete! ✓

**Pull request merged**
