### PR TITLE
fix: [DEL-4667]: Reduce call frequency on getting delegate version from manager

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
Reducing frequency of delegate/configuration call from watcher from 30 seconds to 15 mins
Side effect of this there will be delay of 15 mins to kickstart delegate restart

## Checklist
- [ X] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36542)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36542)

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36542)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
image

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36542)* status: Some of the checks are too old.

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36542)* status: Some of the checks are too old. 1 change requests. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 993 at r3](https://reviewable.io/reviews/harness/harness-core/36542#-NAocT0L9D2xIDgly5UD:-NAocT0L9D2xIDgly5UE:b-estcik) ([raw file](https://github.com/harness/harness-core/blob/08ae01aea3770c2dd80e77bef2ed2b6a41715e3d/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L993)):*
> ```Java
>       throw new InvalidRequestException("Deleted AccountId: " + accountId);
>     }
>     log.info("Getting delegate configuration from Delegate ring for account {}", accountId);
> ```

There will be too many logs, we can make it back to debug.

**Pull request closed without merging**
