### PR TITLE
fix: [CVS-9293]: New Relic custom metric bug fixes

### PR DESCRIPTION
**Pull request by AbhijithHarness**
Unit tests will be added, in the same ticker

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
Screenshot 2022-03-10 at 4 48 43 PM
Screenshot 2022-03-10 at 4 49 21 PM
Screenshot 2022-03-10 at 4 49 59 PM

- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31355)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31355)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/NewRelicDataCollectionInfoMapper.java, line 54 at r1](https://reviewable.io/reviews/harness/harness-core/31355#-Mxnudh_2K5rtg534WP-:-Mxnudh_2K5rtg534WP0:buceypu) ([raw file](https://github.com/harness/harness-core/blob/686a4aa900a0a76a8cc55d17970933bce7c2b50b/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/NewRelicDataCollectionInfoMapper.java#L54)):*
> ```Java
>   public NewRelicDataCollectionInfo toDataCollectionInfo(
>       List<NewRelicCVConfig> cvConfigs, ServiceLevelIndicator serviceLevelIndicator) {
>     cvConfigs =
> ```

@abhijithharness let's move this logic out and add an abstract method in MetricCVConfig with a method which returns whether the CVConfig can be used for SLI or not.
We have seen enough bugs with these kind of issues.

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Comment by AbhijithHarness** [comment]
trigger ft2

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 8 files at r1, 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31355#-:-MxrkJVQ5Q-AL8tXiet6:bnfp4nl)* status: :shipit: complete! ✓

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 7 of 8 files at r1, 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31355#-:-Mxs1lpjEsWV7VUjlc89:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
