### PR TITLE
feat: [DEL-3558]: delegate tags crud apis

### PR DESCRIPTION
**Pull request by arpit3107**
…and cg manager

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31969)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31969)* status: 25 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java, line 35 at r1](https://reviewable.io/reviews/harness/harness-core/31969#-Mzmvo7EC5t7xkpASkyj:-Mzmvo7EC5t7xkpASkyk:b-baeycj) ([raw file](https://github.com/harness/harness-core/blob/14bb5ea106599fa1ed8d66901af9f88d7d968773/120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java#L35)):*
> ```Java
>   String DELEGATE_GROUP_TAGS_API = "delegate-group-tags-internal";
> 
>   //------------------------Delegate Token Related-------------------------------------
> ```

Delegate Token 



_Code quote:_
```Java
Delegate Token Related
```
___
*[120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java, line 65 at r1](https://reviewable.io/reviews/harness/harness-core/31969#-MzmvyNt2foiy_0svDVE:-MzmvyNuDzsYOfcozCrF:bf82y6o) ([raw file](https://github.com/harness/harness-core/blob/14bb5ea106599fa1ed8d66901af9f88d7d968773/120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java#L65)):*
> ```Java
>       @Query("delegateTokenName") String delegateTokenName);
> 
>   //------------------------Delegate Group Tags Related, Old Apis-----------------------------------
> ```

Delegate Group Tags



_Code quote:_
```Java
Delegate Group Tags
```
___
*[120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java, line 74 at r1](https://reviewable.io/reviews/harness/harness-core/31969#-Mzmw0VbE2yrvnn0POLj:-Mzmw0VbE2yrvnn0POLk:b-l2qyuq) ([raw file](https://github.com/harness/harness-core/blob/14bb5ea106599fa1ed8d66901af9f88d7d968773/120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java#L74)):*
> ```Java
>       @Query(NGCommonEntityConstants.PROJECT_KEY) String projectIdentifier, @Body @NotNull DelegateGroupTags tags);
> 
>   //------------------------Delegate Group Tags Related, New Apis-----------------------------------
> ```

Remove this,  no need to mention old and new apis separately



_Code quote:_
```Java
  //------------------------Delegate Group Tags Related, New Apis-----------------------------------
```
___
*[120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java, line 76 at r1](https://reviewable.io/reviews/harness/harness-core/31969#-MzmwCBJ0-h5KpWb6awK:-MzmwCBJ0-h5KpWb6awL:b-4fxwsv) ([raw file](https://github.com/harness/harness-core/blob/14bb5ea106599fa1ed8d66901af9f88d7d968773/120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java#L76)):*
> ```Java
>   //------------------------Delegate Group Tags Related, New Apis-----------------------------------
> 
>   @GET(DELEGATE_GROUP_TAGS_API + "/list")
> ```

I don't think its a good practice to append verb in api name. Method type itself should be good enough saying about functionality of API. Consider remove verbs here and for below apis



_Code quote:_
```Java
/list
```
___
*[120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateGroupTagsResource.java, line 83 at r1](https://reviewable.io/reviews/harness/harness-core/31969#-MzmwfJ97HBGPFQk_3JZ:-MzmwfJABd11JrwCbj-C:bfrklpb) ([raw file](https://github.com/harness/harness-core/blob/14bb5ea106599fa1ed8d66901af9f88d7d968773/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateGroupTagsResource.java#L83)):*
> ```Java
>   @ApiOperation(value = "List tags attached with Delegate group", nickname = "listTagsForDelegateGroup")
>   @Timed
>   @Path("{groupIdentifier}/list")
> ```

Please remove verbs from api path... ditto below



_Code quote:_
```Java
list
```
___
*[420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateSetupResourceV2.java, line 220 at r1](https://reviewable.io/reviews/harness/harness-core/31969#-MzmzKjN1WpoWr0_9XPu:-MzmzKjN1WpoWr0_9XPv:b-fcg7gm) ([raw file](https://github.com/harness/harness-core/blob/14bb5ea106599fa1ed8d66901af9f88d7d968773/420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateSetupResourceV2.java#L220)):*
> ```Java
>   @Path("/tags")
>   @Timed
>   @InternalApi
> ```

Let's move this to new file "DelegateGroupTagsInternalResource.java" as well



_Code quote:_
```Java
  @PUT
  @Path("/tags")
  @Timed
  @InternalApi
  @ExceptionMetered
  @Operation(operationId = "updateTagsForDelegateGroup", summary = "Updates tags for the Delegate Group.",
      responses =
      {
        @io.swagger.v3.oas.annotations.responses.
        ApiResponse(responseCode = "default", description = "Delegate Group details for updated group.")
      })
  public RestResponse<DelegateGroup>
  updateTagsForDelegateGroup(@Parameter(description = "Delegate Group Name") @QueryParam(
                                 NGCommonEntityConstants.IDENTIFIER_KEY) @NotEmpty String groupName,
      @Parameter(description = NGCommonEntityConstants.ACCOUNT_PARAM_MESSAGE) @QueryParam(
          NGCommonEntityConstants.ACCOUNT_KEY) @NotEmpty String accountId,
      @Parameter(description = NGCommonEntityConstants.ORG_PARAM_MESSAGE) @QueryParam(
          NGCommonEntityConstants.ORG_KEY) String orgId,
      @Parameter(description = NGCommonEntityConstants.PROJECT_PARAM_MESSAGE) @QueryParam(
          NGCommonEntityConstants.PROJECT_KEY) String projectId,
      @RequestBody(required = true, description = "List of tags") DelegateGroupTags tags) {
    try (AutoLogContext ignore1 = new AccountLogContext(accountId, OVERRIDE_ERROR)) {
      return new RestResponse<>(
          delegateSetupService.updateDelegateGroupTags_old(accountId, orgId, projectId, groupName, tags.getTags()));
    }
  }
```
___
*[420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java, line 580 at r1](https://reviewable.io/reviews/harness/harness-core/31969#-Mzn0n7d2FTv-S0lRbZ3:-Mzn0n7d2FTv-S0lRbZ4:b-2ad1g6) ([raw file](https://github.com/harness/harness-core/blob/14bb5ea106599fa1ed8d66901af9f88d7d968773/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L580)):*
> ```Java
>       String accountId, String orgId, String projectId, String delegateGroupName, Set<String> tags) {
>     DelegateEntityOwner owner = DelegateEntityOwnerHelper.buildOwner(orgId, projectId);
> ```

Can you put a log.warn here, so that we can know if anybody is using this api or not. and we can deprecate it accordingly.. Also file a ticket to remove this.
___
*[420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java, line 655 at r1](https://reviewable.io/reviews/harness/harness-core/31969#-Mzn0QSBBzFBBNPTQgC1:-Mzn0QSBBzFBBNPTQgC2:blgykr3) ([raw file](https://github.com/harness/harness-core/blob/14bb5ea106599fa1ed8d66901af9f88d7d968773/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L655)):*
> ```Java
> 
>       final UpdateOperations<DelegateGroup> updateOperations = persistence.createUpdateOperations(DelegateGroup.class);
>       setUnset(updateOperations, DelegateGroupKeys.tags, delegateGroupTags.getTags());
> ```

I think you can have common code for update and addition, only this operation will change to setUnsetOnInsert instead.

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31969)* status: 25 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java, line 35 at r1](https://reviewable.io/reviews/harness/harness-core/31969#-Mzmvo7EC5t7xkpASkyj:-MznaUVbByos7Ci5aQKw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14bb5ea106599fa1ed8d66901af9f88d7d968773/120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java#L35)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Delegate Token 
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java, line 65 at r1](https://reviewable.io/reviews/harness/harness-core/31969#-MzmvyNt2foiy_0svDVE:-MznaV7A1fld6QnKPIfm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14bb5ea106599fa1ed8d66901af9f88d7d968773/120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java#L65)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Delegate Group Tags
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java, line 74 at r1](https://reviewable.io/reviews/harness/harness-core/31969#-Mzmw0VbE2yrvnn0POLj:-MznaVuy-Mij5EFxjGNP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14bb5ea106599fa1ed8d66901af9f88d7d968773/120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java#L74)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Remove this,  no need to mention old and new apis separately
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java, line 76 at r1](https://reviewable.io/reviews/harness/harness-core/31969#-MzmwCBJ0-h5KpWb6awK:-Mznacxm5lnE7i2rcduF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14bb5ea106599fa1ed8d66901af9f88d7d968773/120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java#L76)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

I don't think its a good practice to append verb in api name. Method type itself should be good enough saying about functionality of API. Consider remove verbs here and for below apis
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateGroupTagsResource.java, line 83 at r1](https://reviewable.io/reviews/harness/harness-core/31969#-MzmwfJ97HBGPFQk_3JZ:-MznadZa7piPaO9h3X5Q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14bb5ea106599fa1ed8d66901af9f88d7d968773/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateGroupTagsResource.java#L83)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Please remove verbs from api path... ditto below
</blockquote></details>

Done.
___
*[420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateSetupResourceV2.java, line 220 at r1](https://reviewable.io/reviews/harness/harness-core/31969#-MzmzKjN1WpoWr0_9XPu:-MznafDJ4x2aOQ2XPZZG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14bb5ea106599fa1ed8d66901af9f88d7d968773/420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateSetupResourceV2.java#L220)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Let's move this to new file "DelegateGroupTagsInternalResource.java" as well
</blockquote></details>

Done.
___
*[420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java, line 580 at r1](https://reviewable.io/reviews/harness/harness-core/31969#-Mzn0n7d2FTv-S0lRbZ3:-MznafuJ9voZgRmA0uXK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14bb5ea106599fa1ed8d66901af9f88d7d968773/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L580)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Can you put a log.warn here, so that we can know if anybody is using this api or not. and we can deprecate it accordingly.. Also file a ticket to remove this.
</blockquote></details>

Done.
___
*[420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java, line 655 at r1](https://reviewable.io/reviews/harness/harness-core/31969#-Mzn0QSBBzFBBNPTQgC1:-MznbI466Qc6fk2dyRJE:buz0yqo) ([raw file](https://github.com/harness/harness-core/blob/14bb5ea106599fa1ed8d66901af9f88d7d968773/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L655)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

I think you can have common code for update and addition, only this operation will change to setUnsetOnInsert instead.
</blockquote></details>

No, that will not fulfill our purpose.

**Review by gaurav-jain1 — COMMENTED** [review]
> Reviewed 16 of 26 files at r1, 6 of 9 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31969)* status: 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained.

**Review by gaurav-jain1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31969)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 16 of 26 files at r1, 6 of 9 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31969#-:-MztElSC14A26MuFSCRr:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
