### PR TITLE
feat:[CDS-50099]: remove FF: GITOPS_FETCH_LINKED_APPS and its usages

### PR DESCRIPTION
**Pull request by vaibhav-si**
## Describe your changes

Verified that we are able to see the Step in UI after the change.

Screenshot 2023-02-16 at 4 51 25 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44048)

### CODE REVIEW

**Review by mankrit-singh — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44048)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineConfigurationHelper.java` line 71 at r3](https://reviewable.io/reviews/harness/harness-core/44048#-NOQ8Rjl1Pddgwrg8IjX:-NOQ8Rjl1Pddgwrg8IjY:b-r0jlzn) ([raw file](https://github.com/harness/harness-core/blob/3ddaeaf8711868faaaa248f15f77c2c47c0e241b/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineConfigurationHelper.java#L71)):*
> ```Java
>         || executionStrategyType == ExecutionStrategyType.GITOPS) {
>       if (executionStrategyType == ExecutionStrategyType.GITOPS
>           && featureFlagHelper.isEnabled(accountId, FeatureName.GITOPS_FETCH_LINKED_APPS)) {
> ```

is this removal correct ? if FF is removed then the AND condition should only simplify right ? Instead of removal

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44048)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44048)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineConfigurationHelper.java` line 71 at r3](https://reviewable.io/reviews/harness/harness-core/44048#-NOQ8Rjl1Pddgwrg8IjX:-NOQA2yG8H_ZXreZNFmq:b60os79) ([raw file](https://github.com/harness/harness-core/blob/3ddaeaf8711868faaaa248f15f77c2c47c0e241b/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineConfigurationHelper.java#L71)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this removal correct ? if FF is removed then the AND condition should only simplify right ? Instead of removal 
</blockquote></details>

What you mention is right. This is what I did in the first commit.

But I also realized we don't need 2 files for Git now (with FF and without FF). There is only yaml file now "kubernetes-gitops.yaml". Hence, the removal.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44048)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by anshul-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44048)* status: :shipit: complete! ✓

**Pull request merged**
