### PR TITLE
fix: [CDS-86891]: Split getActiveServiceInstanceCountBreakdown Aggregate query into 2 separate queries

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
This is the current DB query made in the particular method
```
db.getCollection('instanceNG').explain('executionStats').aggregate([
    {
        $match: {
            'serviceIdentifier': 'hierarchy_service_v3', 
             $or: [
                {'accountIdentifier':'NYVU0wI4R0ijpWK5Gyl5pQ', 'orgIdentifier':'ClickUp', 'projectIdentifier': 'clickupbackend', 'isDeleted': false, 'createdAt': {$lte: 1699920000000}}, 
                {'accountIdentifier':'NYVU0wI4R0ijpWK5Gyl5pQ', 'orgIdentifier':'ClickUp', 'projectIdentifier': 'clickupbackend', 'isDeleted': true, 'createdAt': {$lte: 1699920000000}, 'deletedAt': {$gte: 1699920000000}}
             ]
         }
    }, 
    {
        $group: {
            '_id': {'serviceIdentifier':'$serviceIdentifier', 'envType': '$envType'}, 
            'count': {$sum: 1}
        }
    }, 
    {
        $project: {'serviceIdentifier':'$_id.serviceIdentifier', 'envType': '$_id.envType', 'count':'$count'}
    }
])
```
We want to split this query up into 2 parts so that both of them can use the right index ( accountIdentifier, orgIdentifier, projectIdentifier, serviceIdentifier, isDeleted, createdAt, deletedAt }

To do this, we have created 2 new queries. Pseduo code is as follow
```
// For non-deleted instances
const nonDeletedResult = db.getCollection('instanceNG').aggregate([
    {
        $match: {
            'serviceIdentifier': 'hierarchy_service_v3',
            'accountIdentifier': 'acc',
            'orgIdentifier': 'org',
            'projectIdentifier': 'foo',
            'isDeleted': false,
            'createdAt': { $lte: 1699920000000 }
        }
    },
    {
        $group: {
            '_id': { 'serviceIdentifier': '$serviceIdentifier', 'envType': '$envType' },
            'count': { $sum: 1 }
        }
    },
    {
        $project: { 'serviceIdentifier': '$_id.serviceIdentifier', 'envType': '$_id.envType', 'count': '$count' }
    }
]);

// For deleted instances
const deletedResult = db.getCollection('instanceNG').aggregate([
    {
        $match: {
            'serviceIdentifier': 'hierarchy_service_v3',
            'accountIdentifier': 'acc',
            'orgIdentifier': 'org',
            'projectIdentifier': 'foo',
            'isDeleted': true,
            'createdAt': { $lte: 1699920000000 },
            'deletedAt': { $gte: 1699920000000 }
        }
    },
    {
        $group: {
            '_id': { 'serviceIdentifier': '$serviceIdentifier', 'envType': '$envType' },
            'count': { $sum: 1 }
        }
    },
    {
        $project: { 'serviceIdentifier': '$_id.serviceIdentifier', 'envType': '$_id.envType', 'count': '$count' }
    }
]);

// Combine results
const combinedResult = [
    ...nonDeletedResult.toArray(),
    ...deletedResult.toArray()
];
```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56844)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56844)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by Y0709 — APPROVED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56844)* status: <span>:shipit:</span> complete! ✓

**Comment by yogesh-chauhan** [comment]
trigger review

**Pull request merged**
