### PR TITLE
feat: [CDS-36906]: Env CRUD with Infra

### PR DESCRIPTION
**Pull request by prashantsharma04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32820)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32820)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/32820#-N1JA7zR0XtWD0veuo9M:-N1JA7zR0XtWD0veuo9N:btin2a2) ([raw file](https://github.com/harness/harness-core/blob/f17f889c45801451f3ccad5d38b455d8ca1d843f/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java#L81)):*
> ```Java
>   // of infraStructure
>   //  @Getter(onMethod_ = { @ApiModelProperty(hidden = true) })
>   //  @ApiModelProperty(hidden = true)
> ```

in develop branch these need to be hidden



_Code quote:_
```Java
  //  @Getter(onMethod_ = { @ApiModelProperty(hidden = true) })
  //  @ApiModelProperty(hidden = true)
```
___
*[`127-cd-nextgen-beans/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/32820#-N1JAMXIAgU6tR-_5uye:-N1JAMXIAgU6tR-_5uyf:b-h38egv) ([raw file](https://github.com/harness/harness-core/blob/f17f889c45801451f3ccad5d38b455d8ca1d843f/127-cd-nextgen-beans/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java#L34)):*
> ```Java
> @Builder
> @SimpleVisitorHelper(helperClass = EnvironmentYamlV2VisitorHelper.class)
> @TypeAlias("environmentYaml")
> ```

this already exists



_Code quote:_
```Java
@TypeAlias("environmentYaml")
```
___
*[`127-cd-nextgen-beans/src/main/java/io/harness/cdng/infra/yaml/InfraStructureDefinition.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/32820#-N1JAIjGDT_hjIbjMEov:-N1JAIjGDT_hjIbjMEow:b1yhndz) ([raw file](https://github.com/harness/harness-core/blob/f17f889c45801451f3ccad5d38b455d8ca1d843f/127-cd-nextgen-beans/src/main/java/io/harness/cdng/infra/yaml/InfraStructureDefinition.java#L32)):*
> ```Java
> @Builder
> @SimpleVisitorHelper(helperClass = InfraStructureDefinitionVisitorHelper.class)
> @TypeAlias("environmentYaml")
> ```

this should be changed



_Code quote:_
```Java
TypeAlias("environmentYaml")
```

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32820)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/32820#-N1JA7zR0XtWD0veuo9M:-N1JMpu120zrTp0-pZt4:b495ikz) ([raw file](https://github.com/harness/harness-core/blob/f17f889c45801451f3ccad5d38b455d8ca1d843f/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java#L81)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

in develop branch these need to be hidden
</blockquote></details>

Will be adding this for develop branch
___
*[`127-cd-nextgen-beans/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/32820#-N1JAMXIAgU6tR-_5uye:-N1JMuMX5pDtw_lh6l4S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f17f889c45801451f3ccad5d38b455d8ca1d843f/127-cd-nextgen-beans/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java#L34)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this already exists
</blockquote></details>

Done.
___
*[`127-cd-nextgen-beans/src/main/java/io/harness/cdng/infra/yaml/InfraStructureDefinition.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/32820#-N1JAIjGDT_hjIbjMEov:-N1JMvHU04FtY23dSHcV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f17f889c45801451f3ccad5d38b455d8ca1d843f/127-cd-nextgen-beans/src/main/java/io/harness/cdng/infra/yaml/InfraStructureDefinition.java#L32)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this should be changed
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32820)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/32820#-N1JNUe095t2oZd5X8oT:-N1Mfn0dAnTm-gwFia2Y:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9276b543fa09a522e7df6c146844c3e06547437c/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java#L50)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this should not come , for develop its going to be hidden and for feat branch it will be in oneOf Set
</blockquote></details>

done

**Review by hextechpal — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32820)* status: :shipit: complete! ✓

**Pull request merged**
