### PR TITLE
feat: [SPG-947]: optimise wf execution query with cdpagecandidate

### PR DESCRIPTION
**Pull request by inderschera**
## Describe your changes

We need to change query to use the best index, but since the query plan cache is already populated with using a bad index, for short term we need to provide hint.

ExecutionStats without hint and query changes:
find({ appId: "-4mC6pnWSmiHDj8Irp7JBg", workflowId: "7kxsIlE8Q-qO0FQ3NLs_zA", cdPageCandidate: true})

duration: 59 seconds
"executionStats" : {
        "executionSuccess" : true,
        "nReturned" : 106365.0,
        "executionTimeMillis" : 49677.0,
        "totalKeysExamined" : 106365.0,
        "totalDocsExamined" : 106365.0
}

ExecutionStats with hint and query changes:
.find({accountId: "vrst0PgwRnOIeii0a2inKg", workflowId: "7kxsIlE8Q-qO0FQ3NLs_zA", cdPageCandidate: true}).hint("accountId_cdPageCandidate_workflowId_createdAt")

duration: 9 seconds
"executionStats" : {
        "executionSuccess" : true,
        "nReturned" : 106361.0,
        "executionTimeMillis" : 9501.0,
        "totalKeysExamined" : 106361.0,
        "totalDocsExamined" : 106361.0
}

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40114)

### CODE REVIEW

**Review by lasdox — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40114)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40114)* status: :shipit: complete! ✓

**Comment by lasdox** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/40114)_ status: :shipit: complete! ✓
> 
> _[`400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java` line 224 at r1](https://reviewable.io/reviews/harness/harness-core/40114#-NGsD6p_-DpIu3NIfpZc:-NGsD6pa-Mu_a6Bv8Pyp:b-u691yr) ([raw file](https://github.com/harness/harness-core/blob/0aa4102d6fe1697c4097c8989093d7cfcd167c54/400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java#L224)):_
> 
> > ```java
> >                 .build();
> >         innerPageRequest.setOptions(Collections.singletonList(Option.SKIPCOUNT));
> >         try {
> > ```
> 
> Why these are not under feature flag. finding across accounts might be not a good idea

We will not find across accounts, only across workflowId.
The higher cardinality node here is workflowId, we are only changing to accountId so we can use existing index

**Review by srinivaswings — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40114)* status: 1 change requests. 1. unresolved discussions.

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40114)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java` line 224 at r1](https://reviewable.io/reviews/harness/harness-core/40114#-NGsD6p_-DpIu3NIfpZc:-NHP-i1T5Le0LmOdoshw:bob8v08) ([raw file](https://github.com/harness/harness-core/blob/0aa4102d6fe1697c4097c8989093d7cfcd167c54/400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java#L224)):*
<details><summary><i>Previously, lasdox (Lucas Sales) wrote…</i></summary><blockquote>

We will not find across accounts, only across workflowId.
The higher cardinality node here is workflowId, we are only changing to accountId so we can use existing index

</blockquote></details>

@srinivaswings only reason to add accountId here is for query to use better index. Only workflowId filter should also suffice here but it doesn't use good index. Hence, the filter.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40114)* status: 1 change requests. 1. unresolved discussions.

**Comment by inderschera** [comment]
trigger smartchecks

**Comment by abhayganvir** [comment]
trigger copyrightcheck

**Comment by abhayganvir** [comment]
trigger copyrightcheck

**Review by srinivaswings — APPROVED** [review]

**Pull request merged**
