### PR TITLE
fix: [PIE-8515]: Unable to save pipeline with chained pipeline stage

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Describe your changes

1. User not able to save child pipeline when child pipeline is on default branch which is a non-main branch
2. Currently if a user have added a child pipeline, on updating the same pipeline to different branch is not supported.

Will be testing this PR build in preqa with this test plan - https://docs.google.com/spreadsheets/d/1Khl4jLY9fgthR9S3Xs95wfLQJTYHdXL3hxqtDqT55KE/edit#gid=0

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44283)

### CODE REVIEW

**Review by adivishy1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 9 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44283)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/gitsync/sdk/EntityGitDetails.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/44283#-NP1AQsG4YtwWgmJj-Xu:-NP1AQsG4YtwWgmJj-Xv:b-i8a1y7) ([raw file](https://github.com/harness/harness-core/blob/b90f0a6a8d14d97f863335ca3626625092b14753/970-ng-commons/src/main/java/io/harness/gitsync/sdk/EntityGitDetails.java#L37)):*
> ```Java
>   @Schema(description = "File Url of the entity") String fileUrl;
>   @Schema(description = "Repo url of the entity") String repoUrl;
>   @Schema(description = "Repo url of the entity") String parentEntityConnectorRef;
> ```

lets fix the description

**Review by adivishy1 — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 2 of 4 files at r4, 2 of 3 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44283)* status: 14 file(s) to review. 1 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/gitsync/sdk/EntityGitDetails.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/44283#-NP1AQsG4YtwWgmJj-Xu:-NPG8OvA3k4P863fDLKI:bb6ywmx) ([raw file](https://github.com/harness/harness-core/blob/b90f0a6a8d14d97f863335ca3626625092b14753/970-ng-commons/src/main/java/io/harness/gitsync/sdk/EntityGitDetails.java#L37)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

lets fix the description 
</blockquote></details>

LGTM

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r2, 1 of 5 files at r3, 2 of 4 files at r4, 1 of 3 files at r5, 2 of 4 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44283)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 340 at r7](https://reviewable.io/reviews/harness/harness-core/44283#-NPLZwXCAPoLcxLGv9q1:-NPLZwXD7Dxw_zYDv2xC:bk0j6ob) ([raw file](https://github.com/harness/harness-core/blob/54869501ec4dc415fdf612d9b683a3b77c066e8e/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L340)):*
> ```Java
>       } else {
>         // TODO: currently we are setting up the same in PipelineStageFilterCreator. Check if can call this only once
>         PipelineGitXHelper.setupGitParentEntityDetails(accountId, orgIdentifier, projectIdentifier, null, null);
> ```

this is not required during execution?

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44283)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 340 at r7](https://reviewable.io/reviews/harness/harness-core/44283#-NPLZwXCAPoLcxLGv9q1:-NPLeUx-2X_MzDSxbjsj:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/54869501ec4dc415fdf612d9b683a3b77c066e8e/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L340)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this is not required during execution?
</blockquote></details>

done

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44283)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44283)* status: :shipit: complete! ✓

**Pull request merged**
