### PR TITLE
[feat]: [PIE-2445]: Adding steps as plan creator for under execution …

### PR DESCRIPTION
**Pull request by prashantsharma04**
…- CDStepsPlanCreator

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30196)

### CODE REVIEW

**Review by hextechpal — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30196)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30196)* status: :shipit: complete! ✓

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30196)* status: :shipit: complete! ✓

___
*[882-pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/beans/PlanCreationContext.java, line 99 at r1](https://reviewable.io/reviews/harness/harness-core/30196#-MuQU_tH73ivhF8MpVf-:-MuQU_tH73ivhF8MpVf0:b-rwplya) ([raw file](https://github.com/harness/harness-core/blob/ba5278866ba9942bcd9ec5fe22cb5dfc5bd6389b/882-pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/beans/PlanCreationContext.java#L99)):*
> ```Java
>   }
> 
>   public List<YamlField> getStepYamlFieldsFromStepsAsCurrentYamlField() {
> ```

nit, this can be done generically for a YamlField I think. Not particularly limited to PlanCreationContext. PlanCreatorUtils might be a better place for this. There are similar functions there.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30196)* status: :shipit: complete! ✓

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/StepsPlanCreator.java, line 48 at r1](https://reviewable.io/reviews/harness/harness-core/30196#-MuQWe2wB5GB6bBNmHZH:-MuQWe2wB5GB6bBNmHZI:b-kvptj2) ([raw file](https://github.com/harness/harness-core/blob/ba5278866ba9942bcd9ec5fe22cb5dfc5bd6389b/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/StepsPlanCreator.java#L48)):*
> ```Java
>     for (YamlField stepYamlField : stepYamlFields) {
>       Map<String, YamlField> stepYamlFieldMap = new HashMap<>();
>       stepYamlFieldMap.put(stepYamlField.getNode().getUuid(), stepYamlField);
> ```

nit, is it necessary to create these single entry maps? I see them in many places. Can DepedencyUtils build dependencies from a single yamlField?

**Pull request merged**
