### PR TITLE
[feat]:  [CDS-36657]: Add support for v2 Variable creator

### PR DESCRIPTION
**Pull request by nassergonzalez**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32468)

### CODE REVIEW

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 33 of 34 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32468)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 234 at r1](https://reviewable.io/reviews/harness/harness-core/32468#-N0_aJS_3_DzRLNj8EsZ:-N0_aJS_3_DzRLNj8Es_:bwd24it) ([raw file](https://github.com/harness/harness-core/blob/06ba67345cdf027afac29801e99566faa97640b8/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L234)):*
> ```Java
>         pipelineTemplateHelper.resolveTemplateRefsInPipeline(pipelineEntity).getMergedPipelineYaml();
>     VariableMergeServiceResponse variablesResponse =
>         pmsPipelineService.createVariablesResponse(resolveTemplateRefsInPipeline, true);
> ```

is that something we should change in our  PR?

**Review by tmacari-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32468#-:-N0a6hHs2n2V6VtM5NdS:bnfp4nl)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32468)* status: :shipit: complete! ✓

**Comment by nassergonzalez** [comment]
trigger authorcheck

**Pull request merged**
