### PR TITLE
feat: [PIE-9763]: added API to update filepath and repo name for remote templates

### PR DESCRIPTION
**Pull request by mohitg0795**
## Describe your changes
Tested following cases:
- Happy flow updating repo and filepath for given template id and version
- Updating a template that doesn't exist throws an exception

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46710)

### CODE REVIEW

**Review by utkarshchoubey-harness — APPROVED** [review]

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46710)* status: 9 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/beans/UpdateGitDetailsParams.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/46710#-NTXEn9D2FwnB52uNbC3:-NTXEn9D2FwnB52uNbC4:b-661s1r) ([raw file](https://github.com/harness/harness-core/blob/08cd40df7a1738ef79335318f6748fb812cdaecc/840-template-service/src/main/java/io/harness/template/beans/UpdateGitDetailsParams.java#L15)):*
> ```Java
> @Value
> @Builder
> public class UpdateGitDetailsParams {
> ```

owner annotation
___
*[`840-template-service/src/main/java/io/harness/template/beans/TemplateUpdateGitMetadataResponse.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/46710#-NTXEusxExGc-8XcLmIA:-NTXEusxExGc-8XcLmIB:bisssrk) ([raw file](https://github.com/harness/harness-core/blob/08cd40df7a1738ef79335318f6748fb812cdaecc/840-template-service/src/main/java/io/harness/template/beans/TemplateUpdateGitMetadataResponse.java#L31)):*
> ```Java
> public class TemplateUpdateGitMetadataResponse {
>   Boolean status;
> }
> ```

@schema annotation is missing for field

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/beans/TemplateUpdateGitMetadataResponse.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/46710#-NTXEusxExGc-8XcLmIA:-NTXFOKbCtunjjRwWZU9:b-twl605) ([raw file](https://github.com/harness/harness-core/blob/08cd40df7a1738ef79335318f6748fb812cdaecc/840-template-service/src/main/java/io/harness/template/beans/TemplateUpdateGitMetadataResponse.java#L31)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@schema annotation is missing for field
</blockquote></details>

These aren't required as we don't expose anything for Swagger 2.0 or 3.0 now. I will still add it just to maintain consistency for now.

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46710)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/beans/UpdateGitDetailsParams.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/46710#-NTXEn9D2FwnB52uNbC3:-NTXG72j5fH0i-xJqNvb:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/08cd40df7a1738ef79335318f6748fb812cdaecc/840-template-service/src/main/java/io/harness/template/beans/UpdateGitDetailsParams.java#L15)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

owner annotation
</blockquote></details>

done
___
*[`840-template-service/src/main/java/io/harness/template/beans/TemplateUpdateGitMetadataResponse.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/46710#-NTXEusxExGc-8XcLmIA:-NTXG6Qb9BT_jwpvcVcW:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/08cd40df7a1738ef79335318f6748fb812cdaecc/840-template-service/src/main/java/io/harness/template/beans/TemplateUpdateGitMetadataResponse.java#L31)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

These aren't required as we don't expose anything for Swagger 2.0 or 3.0 now. I will still add it just to maintain consistency for now.
</blockquote></details>

done

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46710)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 3 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46710)* status: :shipit: complete! ✓

**Pull request merged**
