### PR TITLE
fix: [PL-23109]: user group sanitization

### PR DESCRIPTION
**Pull request by karansiwach360**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31977)

### CODE REVIEW

**Comment by karansiwach360** [comment]
trigger messagecheck

**Comment by karansiwach360** [comment]
trigger messagecheck

**Comment by karansiwach360** [comment]
trigger ti2

**Review by ujjawal-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 11 files at r1, 10 of 12 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31977#-:-N-1a4rbAWC4WP8-jOEM:bnfp4nl)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 4 of 11 files at r1, 4 of 12 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31977)* status: 7 file(s) to review.

**Review by reetika04 — APPROVED** [review]
> Reviewed 6 of 12 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31977)* status: :shipit: complete! ✓

**Pull request merged**
