### PR TITLE
[fix]: [CDS-77649]: Handling that the Stage abort interrupts only that stage instead of all stages

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Issue: 

- In `checkInterruptsPreInvocation` before starting a node, we were fetching all the AbortAll/ExpireAll interrupts and if any present then we are not allowing that node to restart without checking if the active interrupt applies on that node. So even if we abort one stage, it would have aborted all the parallel stages.(Same goes for the Expire)
- If we abort the stage then Pipeline abort was not allowed. Getting the error `Execution has already ABORT_ALL interrupt`. Because we were not checking if the ABORT_ALL interrupt is present on stage or on plan.

Fix:  

- Checking the the active interrupt applies on the concerned node. If it does then deny the node start else allow it.
- Fixed the method that check if an ABORT_ALL interrupt already present. Now we will check if a planLevel ABORT_ALL interrupt present or not. And check the stage level interrupt while triggering stage level interrupts.

Testing:

- Tested that if we do the stage abort, then only that stage is being aborted. While the other parallel stages are executing fine.
- Tested that if we abort the pipeline, then all the parallel stages are aborted
- Tested that we are able to abort the pipeline even if we have aborted a stage before it.
- Tested that we are not able to abort the pipeline we have already triggered the pipeline abort before it.
- Tested that when we have parallel stages running. We are able to abort any stage exactly once. And can not trigger the abort multiple times on the same stage.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52009)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52009)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/52009#-NcadLC_70miaTCcaHkD:-NcadLC_70miaTCcaHkE:b-gh4zxu) ([raw file](https://github.com/harness/harness-core/blob/cacd4b7454c63cc51b5fcfc1e35156cd969b4cde/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L108)):*
> ```Java
>           // Checking if any plan level AbortAll interrupt present.
>           return true;
>         } else if (presentInterrupt.getNodeExecutionId().equals(interrupt.getNodeExecutionId())) {
> ```

what if this is null? null equals will fail



_Code quote:_
```Java
presentInterrupt.getNodeExecutionId()
```

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52009)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/52009#-NcadLC_70miaTCcaHkD:-NcagggGCoXp5JDgKtnh:b-tz6jny) ([raw file](https://github.com/harness/harness-core/blob/cacd4b7454c63cc51b5fcfc1e35156cd969b4cde/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L108)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what if this is null? null equals will fail
</blockquote></details>

It can not be empty. I its empty then the execution will go into the if block. If its nonEmpty then only it will come to else-if condition.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52009)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptServiceImpl.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/52009#-Ncaov090G5-ogumb6PJ:-Ncaov090G5-ogumb6PK:b-3u1hed) ([raw file](https://github.com/harness/harness-core/blob/cacd4b7454c63cc51b5fcfc1e35156cd969b4cde/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptServiceImpl.java#L93)):*
> ```Java
> 
>     Optional<Interrupt> optionalInterrupt =
>         InterruptUtils.obtainOptionalInterruptFromActiveInterrupts(interrupts, ambiance);
> ```

Discussed offline, we can pass list of nodeExecutionIds from here rather than bringing stage concept in interrupts.

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52009)* status: 8 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptServiceImpl.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/52009#-Ncaov090G5-ogumb6PJ:-NcbJGUMAPnnhnArRin4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cacd4b7454c63cc51b5fcfc1e35156cd969b4cde/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptServiceImpl.java#L93)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Discussed offline, we can pass list of nodeExecutionIds from here rather than bringing stage concept in interrupts.
</blockquote></details>

Done.

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 1 of 5 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52009)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by naidu-harness** [comment]
@brijeshdhakar Newly added code coverage is less than 80. Please add more tests before merging the PR

**Review by naidu-harness — CHANGES_REQUESTED** [review]
Improve the New code coverage

**Review by archit-harness — DISMISSED** [review]
> Reviewed 7 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52009)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger ut0 ut1 ut2 ut3 ut4

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52009)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52009)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by naidu-harness — APPROVED** [review]

**Pull request merged**
