### PR TITLE
feat: [PL-39557]: Added service class and client method for resource group for enabling public access

### PR DESCRIPTION
**Pull request by meenakshi-harness**
## Describe your changes
1. Added harnessManaged field in Resource group create/upodate API. This will be hidden field.
2. Added service classes for enable public access.
3. Added enable public access api impl and UTs.

Testing:
1. Enable public access only on onboarded resource type.
2. Default resource group in a given scope will be created with `_public_resource`.
3. Roleassignment with ALL_USER and ALL_AUTHENTICATION_USER is created which generates respective ACLs. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52212)

### CODE REVIEW

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52212)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/52212#-Nd6StRm6OABW4DAXCxW:-Nd6StRm6OABW4DAXCxX:b-n177hw) ([raw file](https://github.com/harness/harness-core/blob/f9cc29b58ddfd66e5e44ba828426758d56b82e97/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java#L113)):*
> ```Java
>       throw new InvalidRequestException("Unable to update public resource group", USER);
>     }
>     for (PublicAccessRoleAssignmentMapping publicAccessRoleAssignmentMapping : publicAccessRoleAssignmentMappings) {
> ```

Shouldn't this be filteredMappings? We need to create role assignment only for publicAccessRoleAssignmentMapping for given resourceType and role mapping?

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52212)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/52212#-Nd6StRm6OABW4DAXCxW:-Nd6VFLa2izCMhK6OPIq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9cc29b58ddfd66e5e44ba828426758d56b82e97/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java#L113)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Shouldn't this be filteredMappings? We need to create role assignment only for publicAccessRoleAssignmentMapping for given resourceType and role mapping?
</blockquote></details>

Done.

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52212)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java` line 144 at r3](https://reviewable.io/reviews/harness/harness-core/52212#-Nd6iyMV0Gd7610N_vP4:-Nd6iyMW5nFNVm7hF6tb:bcnhppt) ([raw file](https://github.com/harness/harness-core/blob/20c5485604517ba34299d3d1ed7debca7cfcc8d2/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java#L144)):*
> ```Java
>   }
> 
>   private ResourceGroupResponse updatePublicResourceGroup(ResourceGroupResponse existingResourceGroup,
> ```

Add UT for update.

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52212)* status: 13 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java` line 144 at r3](https://reviewable.io/reviews/harness/harness-core/52212#-Nd6iyMV0Gd7610N_vP4:-Nd6q4yzAK8Dqm5u1lQr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/20c5485604517ba34299d3d1ed7debca7cfcc8d2/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java#L144)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Add UT for update.
</blockquote></details>

Done.

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger ut5

**Review by mankrit-singh — APPROVED** [review]

**Review by ankit-harness — COMMENTED** [review]
> Reviewed 4 of 13 files at r1, 1 of 3 files at r2, 2 of 4 files at r4, 4 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52212)* status: 3 file(s) to review. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessService.java` line 16 at r6](https://reviewable.io/reviews/harness/harness-core/52212#-NdEzRiQ-wgTmL-PGZF1:-NdEzRiQ-wgTmL-PGZF2:b-r8rnqa) ([raw file](https://github.com/harness/harness-core/blob/223c95a1cba4a0bbc037758b42378fd3518d4cf2/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessService.java#L16)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PL)
> public interface PublicAccessService {
> ```

Shouldn't this file be in access control core?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessUtils.java` line 38 at r6](https://reviewable.io/reviews/harness/harness-core/52212#-NdEyafKCddkXVvzm1m6:-NdEyafL6QVnq19Oc2pL:bjl6we1) ([raw file](https://github.com/harness/harness-core/blob/223c95a1cba4a0bbc037758b42378fd3518d4cf2/access-control/libs/core/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessUtils.java#L38)):*
> ```Java
>   }
> 
>   public List<PublicAccessRoleAssignmentMapping> getPublicAccessRoleAssignmentMapping() {
> ```

This method should not be here (in access-control core). This should be in the place where you need this mapping.

**Pull request merged**
