### PR TITLE
feat: [del-5634]: API exposing token value

### PR DESCRIPTION
**Pull request by xingchi-jin**
## Describe your changes
Add an option to get tokens api to allow fetching token value given a token name.
 Tested with success
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42129)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateTokenNgResource.java` line 141 at r3](https://reviewable.io/reviews/harness/harness-core/42129#-NKsx_RXCfmImFEvFV1Q:-NKsx_RXCfmImFEvFV1R:b-dkzt5m) ([raw file](https://github.com/harness/harness-core/blob/9dee6e6ffa1584c1947696592734a63de84dff45/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateTokenNgResource.java#L141)):*
> ```Java
>       })
>   public RestResponse<List<DelegateTokenDetails>>
>   getDelegateTokens(@Parameter(description = "Name of Delegate Token (ACTIVE or REVOKED).") @QueryParam(
> ```

what kind of access control we have on this API? in my opinion not everyone should be able to copy a token. Only admin users should be able to call this api

**Review by AnupamIO — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42129)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateTokenNgResource.java` line 141 at r3](https://reviewable.io/reviews/harness/harness-core/42129#-NKsx_RXCfmImFEvFV1Q:-NKvgleA0W-f_iaaf0d2:b-q5wvqo) ([raw file](https://github.com/harness/harness-core/blob/9dee6e6ffa1584c1947696592734a63de84dff45/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateTokenNgResource.java#L141)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

what kind of access control we have on this API? in my opinion not everyone should be able to copy a token. Only admin users should be able to call this api
</blockquote></details>

+1, it is currently using DELEGATE_VIEW_PERMISSION. probably we can use DELEGATE_CONFIG_EDIT_PERMISSION or similar in access control.

**Review by xingchi-jin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42129)* status: Some of the checks are too old. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateTokenNgResource.java` line 141 at r3](https://reviewable.io/reviews/harness/harness-core/42129#-NKsx_RXCfmImFEvFV1Q:-NL3Ldgu7g-Ova_-ykAx:bigcbt6) ([raw file](https://github.com/harness/harness-core/blob/9dee6e6ffa1584c1947696592734a63de84dff45/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateTokenNgResource.java#L141)):*
> DELEGATE_CONFIG_EDIT_PERMISSION
I had a discussion with Prateek about this. Compare to today when generating k8s yamls where the token be revealed. We should use the same permission as creating a delegate.
For that probably I will use the 'core_delegate_edit'

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42129)* status: Some of the checks are too old.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42129)* status: Some of the checks are too old.

**Review by xingchi-jin — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42129)* status: Some of the checks are too old.

**Comment by xingchi-jin** [comment]
Test Result regarding permission
Step 1. I login as a viewer use (in my PR ENV)
Screen Shot 2023-01-10 at 5 23 03 PM

Step 2.
When I call ng token API to fetch token value, access denied
image

@raghuAtWings

**Pull request merged**
