### PR TITLE
fix: [CDS-41036]: NG - Throw InvalidArgumentsException when useFromStage chain is detected

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes
Whenever attempting to execute a pipeline that has service configuration chained with `useFromStage` (see example below), pipeline-service was throwing a null pointer exception during plan execution creation.

By `useFromStage` chaining, we mean cases similar to the following:  A deployment pipeline with 3 deploy stages. Stage1 has service configs defined, Stage2 has `useFromStage: Stage1` and Stage3 has `useFromStage: Stage2` - The fact that Stage3 is referencing Stage2 for its service configurations, which in turn is referencing Stage1 represents the `useFromStage` chaining, which is currently unsupported in pipeline-service.

This PR makes Harness App throw an `InvalidArgumentsException` with comprehensible message whenever this case is detected. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41129)

### CODE REVIEW

**Comment by vcalasansh** [comment]
trigger messagecheck

**Comment by vcalasansh** [comment]
trigger smartchecks

**Review by sribalij — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41129)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java` line 330 at r1](https://reviewable.io/reviews/harness/harness-core/41129#-NIg3XiF0uSa1ktpffZR:-NIg3XiF0uSa1ktpffZS:b-vk5m0r) ([raw file](https://github.com/harness/harness-core/blob/a24059008a96125ae380e9a23bf9ed65e1263107/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java#L330)):*
> ```Java
>         if (useFromStage(deploymentStage.getService())) {
>           throw new InvalidArgumentsException(
>               "Invalid identifier given in useFromStage. Cannot reference a stage which also has useFromStage parameter");
> ```

Does this also log the stage identifier in case a pipeline has multiple stages ?

**Review by vcalasansh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41129)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java` line 330 at r1](https://reviewable.io/reviews/harness/harness-core/41129#-NIg3XiF0uSa1ktpffZR:-NIgbkoTCutjIrLkUBGi:brraqjy) ([raw file](https://github.com/harness/harness-core/blob/a24059008a96125ae380e9a23bf9ed65e1263107/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java#L330)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Does this also log the stage identifier in case a pipeline has multiple stages ?
</blockquote></details>

Yes it does, this is an example error message, where the problematic stage's name is `deploy3`: "Error creating Plan: Could not create plan for node [pipeline.stages.deploy3]: Invalid argument(s): Invalid identifier given in useFromStage. Cannot reference a stage which also has useFromStage parameter". Thank you!

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41129)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by sribalij — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41129)* status: :shipit: complete! ✓

**Pull request merged**
