### PR TITLE
[fix]: [CDS-42815]: Fixing Gar primary artifact pipeline execution info

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
Gar Bugs fixing

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37192)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37192)

**Comment by vivekkarnatiharness** [comment]
trigger messagecheck

**Review by vtxorxwitty — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37192#-:-NBHP9sN-2P1Udk2mxqW:bnfp4nl)* status: 1 file(s) to review.

**Review by vtxorxwitty — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37192)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java` line 174 at r1](https://reviewable.io/reviews/harness/harness-core/37192#-NBLlJF4Dt4kIvZpUYL3:-NBLlJF4Dt4kIvZpUYL4:b-b6hah3) ([raw file](https://github.com/harness/harness-core/blob/5770be2207159f37630b8524fed66001368a7216/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java#L174)):*
> ```Java
>       case GOOGLE_ARTIFACT_REGISTRY:
>         GoogleArtifactRegistryConfig googleArtifactRegistryConfig = (GoogleArtifactRegistryConfig) artifactConfig;
>         String version = googleArtifactRegistryConfig.getVersion().getValue() != null
> ```

Please add unit test case for the above scenario in ArtifactUtilsTest class. 



_Code quote:_
```Java
        GoogleArtifactRegistryConfig googleArtifactRegistryConfig = (GoogleArtifactRegistryConfig) artifactConfig;
```

**Review by shivamnegi94 — APPROVED** [review]

**Review by shivamnegi94 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37192)* status: :shipit: complete! ✓

**Comment by vivekkarnatiharness** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java` line 174 at r1](https://reviewable.io/reviews/harness/harness-core/37192#-NBLlJF4Dt4kIvZpUYL3:-NBMifGN0upBIBbVMw6Q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5770be2207159f37630b8524fed66001368a7216/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java#L174)):*
<details><summary><i>Previously, vtxorxwitty (Ved Tambat) wrote…</i></summary><blockquote>

Please add unit test case for the above scenario in ArtifactUtilsTest class. 
</blockquote></details>

Done.

**Review by vivekkarnatiharness — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37192)* status: 1. unresolved discussions.

**Comment by vivekkarnatiharness** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java` line 174 at r1](https://reviewable.io/reviews/harness/harness-core/37192#-NBLlJF4Dt4kIvZpUYL3:-NBMjRLVDzMQQDGScvPw:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/5770be2207159f37630b8524fed66001368a7216/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java#L174)):*
<details><summary><i>Previously, vivekkarnatiharness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

done

**Review by naman-goenka — APPROVED** [review]

**Review by vtxorxwitty — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37192#-:-NBMtPCI9arTAliOcSCo:bnfp4nl)* status: 1. unresolved discussions.

**Pull request merged**
