### PR TITLE
fix: [CDS-49797]: fixing the empty string runtime input for valuesPaths.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
When deserialising empty strings to objects, jackson fails with Mapping Exception. Jackson suggests that we should set a coercion config for that specific data type to map empty string to null

https://cowtowncoder.medium.com/jackson-2-12-most-wanted-4-5-cbc91c00bcd2

This PR only adds coercion config for ArrayList. We face this problem when UI might send "" as input value for optional fields and this breaks plan creation. Further if user deletes the runtime optional field then we were getting Cast exception in K8s step helper and Native helm step helper. If the user deletes the optional runtime input field then we do not get Mapping Exception and the string "<+input>" is passed to the valuesPaths in manifest outcome.

PR: [https://cd.pr.harness.io/cds-49797-2/ng/#/account/kmpySmUISimoRrJL6NL73w/cd/orgs/default/projects/defaultproject/pipelines/HelmChart/pipeline-studio/?storeType=INLINE](https://cd.pr.harness.io/cds-49797-2/ng/#/account/kmpySmUISimoRrJL6NL73w/cd/orgs/default/projects/defaultproject/pipelines/HelmChart/pipeline-studio/?storeType=INLINE)

Automation: [https://github.com/wings-software/Automation/pull/4134](https://github.com/wings-software/Automation/pull/4134)

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42418)

### CODE REVIEW

**Comment by GoelPratyush99** [comment]
MessageMetadata: trigger messagecheck

**Comment by GoelPratyush99** [comment]
trigger messagecheck

**Review by achyuth-harness — DISMISSED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42418)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42418)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/42418#-NLexrSR39P1oKzX5eDK:-NLexrSR39P1oKzX5eDL:b-de0umz) ([raw file](https://github.com/harness/harness-core/blob/a3864d3e80b4aa35c3bb52e5049b6a9aadb7c60e/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L71)):*
> ```Java
>     // map empty string to null instead of failing with Mapping Exception
>     mapper.coercionConfigFor(LinkedHashMap.class).setCoercion(CoercionInputShape.EmptyString, CoercionAction.AsNull);
>     mapper.coercionConfigFor(ArrayList.class).setCoercion(CoercionInputShape.EmptyString, CoercionAction.AsNull);
> ```

Please confirm if we can have asEmpty instead of null

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42418)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/42418#-NLexrSR39P1oKzX5eDK:-NLfQNB21J38avEUKI-t:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a3864d3e80b4aa35c3bb52e5049b6a9aadb7c60e/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L71)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Please confirm if we can have asEmpty instead of null
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42418)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
