### PR TITLE
[feat]: [PIE-9705]: Rollback Stage status should depend on rollback steps

### PR DESCRIPTION
**Pull request by namanvermah**
Create a separate step for combined rollback that publishes the output. For rollback mode execution, in deploy stage, use this output to determine the state of the stage

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46637)

### CODE REVIEW

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46637)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46637)* status: 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46637)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46637)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
trigger review

**Pull request merged**
