### PR TITLE
fix: [DEL-4963]: Separate Redis instance for delegate-related operati…

### PR DESCRIPTION
**Pull request by jennyjames21**
Summary:

Separate Redis instance for delegate-related operations and introduce separate Redis Config for delegate service.
Distributed caching approach using Redisson Client RMap data structure
Local Redis cache support using RLocalCachedMap
https://harness.atlassian.net/wiki/spaces/DEL/pages/21255423025/Dedicated+Redis+Instance+for+Delegate+Service
Test Performed
Sanity Test with disable flag to use Redis cache
1) Delegate Installation - CG and NG
2) K8 end to end flow - CG
3) NG Pipeline execution

Delegate Cache

If flag enabled, Verify cache is present in Redis and value in hash
Verify Delegate Cache fetch from Redis cache on read and refresh on every 1 minute
Verify any update on Delegate entity reflects on UI/Redis cache
Verify delete delegate updates the cache and remove from cache (pending)
Verify task execution flow with delegate entity fetched from Redis
Delegate Group Cache

Verify delegate groups cache are getting added to the Redis cache and value in hash
Verify UI all delegates are displayed under the delegate group
End to End Task execution with NG pipeline
Verify list of selectors are displaying correctly in NG

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44492)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger ut3

**Comment by raghuAtWings** [comment]
*[`100-migrator/config.yml` line 703 at r1](https://reviewable.io/reviews/harness/harness-core/44492#-NPOokbP-4F8CYhs4qD8:-NPOokbQ48eXDcndFmer:b-6wx487) ([raw file](https://github.com/harness/harness-core/blob/9beff9aae805094aaa88d52ef9a2ef561e86c4ec/100-migrator/config.yml#L703)):*
> ```YAML
>     enableQueueAndDequeue: false
> 
> redisDelegateConfig:
> ```

why do we need this for migrator?

**Comment by raghuAtWings** [comment]
*[`160-model-gen-tool/config-datagen.yml` line 314 at r1](https://reviewable.io/reviews/harness/harness-core/44492#-NPOooVS4_S4qdpLr-bl:-NPOooVS4_S4qdpLr-bm:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/9beff9aae805094aaa88d52ef9a2ef561e86c4ec/160-model-gen-tool/config-datagen.yml#L314)):*
> ```YAML
>     durationUnit: MINUTES
> 
> redisDelegateConfig:
> ```

same here

**Comment by raghuAtWings** [comment]
*[`360-cg-manager/container/scripts/replace_configs.sh` line 772 at r1](https://reviewable.io/reviews/harness/harness-core/44492#-NPOp2yD5FqUAoHYoLok:-NPOp2yD5FqUAoHYoLol:bqzy87f) ([raw file](https://github.com/harness/harness-core/blob/3d11b4650f611eef76889eb3d153db24ff40dc9c/360-cg-manager/container/scripts/replace_configs.sh#L772)):*
> ```Shell
> 
> if [[ "" != "$ATMOSPHERE_REDIS_URL" ]]; then
>   export ATMOSPHERE_REDIS_URL; yq -i '.redisAtmosphereConfig.redisUrl=env(ATMOSPHERE_REDIS_URL)' $CONFIG_FILE
> ```

why changing this?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44492)* status: 0 of 1 approvals obtained. Waiting on team(s): del-team.

**Comment by jennyjames21** [comment]
*[`100-migrator/config.yml` line 703 at r1](https://reviewable.io/reviews/harness/harness-core/44492#-NPOokbP-4F8CYhs4qD8:-NPP6LRw2F91FJfQLgb9:b-a9e4wu) ([raw file](https://github.com/harness/harness-core/blob/9beff9aae805094aaa88d52ef9a2ef561e86c4ec/100-migrator/config.yml#L703)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need this for migrator?
</blockquote></details>

It uses delegate cache i believe, test failed hence added

**Comment by jennyjames21** [comment]
*[`160-model-gen-tool/config-datagen.yml` line 314 at r1](https://reviewable.io/reviews/harness/harness-core/44492#-NPOooVS4_S4qdpLr-bl:-NPP6_6S0IYyC_wrH0_Z:bstjyoj) ([raw file](https://github.com/harness/harness-core/blob/9beff9aae805094aaa88d52ef9a2ef561e86c4ec/160-model-gen-tool/config-datagen.yml#L314)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

same here
</blockquote></details>

datagen uses mainconfiguration to start, hence added. App start up failed here too.

**Comment by jennyjames21** [comment]
*[`360-cg-manager/container/scripts/replace_configs.sh` line 772 at r1](https://reviewable.io/reviews/harness/harness-core/44492#-NPOp2yD5FqUAoHYoLok:-NPP792ADIHWkktxKAgX:b-sb49bf) ([raw file](https://github.com/harness/harness-core/blob/3d11b4650f611eef76889eb3d153db24ff40dc9c/360-cg-manager/container/scripts/replace_configs.sh#L772)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why changing this?
</blockquote></details>

we added this a while back in preparation to move the atmosphere redis url to new service. Atmosphere url (for broadcasting) eventually will move to new redis,  once stabilized

**Review by raghuAtWings — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44492)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by puthrayaharness — APPROVED** [review]

**Review by raghuAtWings — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44492)* status: 1 change requests. 1. unresolved discussions.

**Pull request merged**
