### PR TITLE
[feat]: [CDS-47649]: azure web app rollback artifact details fix

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Describe your changes
Generating Rollback Artifact details threw an error for Azure Web App. This is now resolved.

Before:
Screenshot 2022-12-01 at 16 49 44

After: 
No issue is seen.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41007)

### CODE REVIEW

**Review by markoharness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41007)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41007)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java` line 147 at r1](https://reviewable.io/reviews/harness/harness-core/41007#-NIHcnjg117yBjJs6G7h:-NIHcnjhEawCyAXpzWEl:bx8ra1v) ([raw file](https://github.com/harness/harness-core/blob/4028464800d80065f6a110b92009b20cb616f349/125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java#L147)):*
> ```Java
>     }
> 
>     if (InfrastructureKind.AZURE_WEB_APP.equals(infrastructureKind)) {
> ```

You can remove this if because you are doing the next check in next if and this is enough  >> executionDetails.get() instanceof DefaultExecutionDetails

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41007#-:-NIHnOL749ImZZQ01FNL:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by markoharness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41007)* status: 1 file(s) to review.

**Comment by vladimir-peric** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java` line 147 at r1](https://reviewable.io/reviews/harness/harness-core/41007#-NIHcnjg117yBjJs6G7h:-NII086S-rg8ojOUyzPD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4028464800d80065f6a110b92009b20cb616f349/125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java#L147)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

You can remove this if because you are doing the next check in next if and this is enough  >> executionDetails.get() instanceof DefaultExecutionDetails
</blockquote></details>

Done.

**Review by ivan-83 — APPROVED** [review]
:lgtm:
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41007#-:-NII0FeN7BiXrpSt5zeJ:b-qcfkkb)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41007)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41007)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41007#-:-NII1JF43MlHj_fDMyMj:bnfp4nl)* status: 1 file(s) to review.

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41007)* status: :shipit: complete! ✓

**Pull request merged**
