### PR TITLE
fix: [CDS-79020]: Support deletion of files with symlinks

### PR DESCRIPTION
**Pull request by sarthakkasat**
## Describe your changes
While deleting the FileUtils.deleteQuitely() method checks if the parent is present for symlink file and then deletes that file, if the parent file is missing deletion would be unsuccessful, with this change we will use the FileIo.deleteDirectoryAndItsContentIfExists() method to do the deletion. While visiting the files this method does not check if parent is present, it goes through all the files and deletes them

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53222)

### CODE REVIEW

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53222)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerragruntProvisionTask.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/53222#-Nf1jXMc5dmCURMrihUp:-Nf1jXMc5dmCURMrihUq:b-hi0od2) ([raw file](https://github.com/harness/harness-core/blob/3ac58c3a40378549d88b40508628e51a481cb8a2/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerragruntProvisionTask.java#L215)):*
> ```Java
>         log.error("Exception in copying files to provisioner specific directory", sanitizedException);
>         try {
>           FileIo.deleteDirectoryAndItsContentIfExists(baseDir);
> ```

this is CG code, so lets not make changes here
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/terraform/task/TerraformProvisionTask.java` line 257 at r1](https://reviewable.io/reviews/harness/harness-core/53222#-Nf1jZQvCMYtAM4nU1sL:-Nf1jZQvCMYtAM4nU1sM:b-hi0od2) ([raw file](https://github.com/harness/harness-core/blob/3ac58c3a40378549d88b40508628e51a481cb8a2/930-delegate-tasks/src/main/java/software/wings/delegatetasks/terraform/task/TerraformProvisionTask.java#L257)):*
> ```Java
>         log.error("Exception in downloading and copying files to provisioner specific directory", sanitizedException);
>         try {
>           FileIo.deleteDirectoryAndItsContentIfExists(baseDir);
> ```

this is CG code, so lets not make changes here

**Review by sarthakkasat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53222)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerragruntProvisionTask.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/53222#-Nf1jXMc5dmCURMrihUp:-Nf9now-8bV4cq6mqqKf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3ac58c3a40378549d88b40508628e51a481cb8a2/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerragruntProvisionTask.java#L215)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this is CG code, so lets not make changes here
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/terraform/task/TerraformProvisionTask.java` line 257 at r1](https://reviewable.io/reviews/harness/harness-core/53222#-Nf1jZQvCMYtAM4nU1sL:-Nf9np_o2LGRMmAr3Grc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3ac58c3a40378549d88b40508628e51a481cb8a2/930-delegate-tasks/src/main/java/software/wings/delegatetasks/terraform/task/TerraformProvisionTask.java#L257)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this is CG code, so lets not make changes here
</blockquote></details>

Done.

**Review by sourabh-awashti — DISMISSED** [review]
LGTM

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53222)* status: 5 file(s) to review.

**Comment by sarthakkasat** [comment]
trigger uts

**Comment by sarthakkasat** [comment]
trigger pmd, trigger checkstylecodeformat, trigger codebasehash, trigger messagecheck

**Comment by sarthakkasat** [comment]
trigger pmd, trigger checkstylecodeformat, trigger codebasehash, trigger messagecheck

**Comment by sarthakkasat** [comment]
trigger uts

**Comment by sarthakkasat** [comment]
trigger, ut0, ut1, ut2, ut7, ut9

**Comment by sarthakkasat** [comment]
trigger uts

**Comment by sarthakkasat** [comment]
trigger uts

**Review by sourabh-awashti — APPROVED** [review]

**Comment by yogesh-chauhan** [comment]
trigger review

**Pull request merged**
