### PR TITLE
feat: [OPA-78]: Create OPAPOLICY entity type and register with GitSync

### PR DESCRIPTION
**Pull request by scottyw**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30329)

### CODE REVIEW

**Review by dwarren-dev — DISMISSED** [review]

**Comment by scottyw** [comment]
trigger authorcheck

**Comment by scottyw** [comment]
Hey delegate folks, I updated the delegate hash as indicated in the checks but I am unclear if the change is actually safe. It would be great to get some confirmation before going any fuether. Thanks!

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30329)* status: :shipit: complete! ✓

**Review by bojanmicovic — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30329#-:-MuqEb2C72EeTCROJo-W:bnfp4nl)* status: :shipit: complete! ✓

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 5 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30329)* status: :shipit: complete! ✓

___
*[970-ng-commons/src/main/java/io/harness/EntityType.java, line 125 at r1](https://reviewable.io/reviews/harness/harness-core/30329#-MuqH2Ce4yNjXWUa5VWx:-MuqH2Ce4yNjXWUa5VWy:be97lj6) ([raw file](https://github.com/harness/harness-core/blob/f92dd9f32688071d871089b050c1794081a92616/970-ng-commons/src/main/java/io/harness/EntityType.java#L125)):*
> ```Java
>       EntityYamlRootNames.SERVICENOW_APPROVAL),
>   @JsonProperty(EntityTypeConstants.OPAPOLICIES)
>   OPAPOLICIES(ModuleType.CORE, EntityTypeConstants.OPAPOLICIES, IdentifierRef.class, EntityYamlRootNames.OPAPOLICY);
> ```

ModuleType will be CORE ?

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 7 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30329)* status: :shipit: complete! ✓

**Review by scottyw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30329)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[970-ng-commons/src/main/java/io/harness/EntityType.java, line 125 at r1](https://reviewable.io/reviews/harness/harness-core/30329#-MuqH2Ce4yNjXWUa5VWx:-Muu071oC9oBJyZGpgLQ:b-ds31rs) ([raw file](https://github.com/harness/harness-core/blob/f92dd9f32688071d871089b050c1794081a92616/970-ng-commons/src/main/java/io/harness/EntityType.java#L125)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

ModuleType will be CORE ?
</blockquote></details>

I'm not sure. Do you think it should be something different? Governance is not a module itself, it's more of a platform feature that can be used by CD, CI, FF and so on.

**Comment by scottyw** [comment]
Rebased just now to fix the merge conflict on delegate hash.

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30329)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[970-ng-commons/src/main/java/io/harness/EntityType.java, line 125 at r1](https://reviewable.io/reviews/harness/harness-core/30329#-MuqH2Ce4yNjXWUa5VWx:-MuvHpEjEOUcAbhL0DK5:bsys4cw) ([raw file](https://github.com/harness/harness-core/blob/f92dd9f32688071d871089b050c1794081a92616/970-ng-commons/src/main/java/io/harness/EntityType.java#L125)):*
<details><summary><i>Previously, scottyw (Scott Walker) wrote…</i></summary><blockquote>

I'm not sure. Do you think it should be something different? Governance is not a module itself, it's more of a platform feature that can be used by CD, CI, FF and so on.
</blockquote></details>

Core will work for that case I think

**Review by DeepakPatankar — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30329)* status: :shipit: complete! ✓

**Comment by scottyw** [comment]
Thanks reviewers, I'll rebase to resolve the conflict and merge.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 9 of 12 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30329)* status: :shipit: complete! ✓

**Pull request merged**
