### PR TITLE
feat: [PL-23661]: Changes to support email null for LDAP sync

### PR DESCRIPTION
**Pull request by ujjawal-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31385)

### CODE REVIEW

**Comment by piyush-harness** [comment]
___
*[400-rest/src/test/java/software/wings/scheduler/LdapGroupSyncJobHelperTest.java, line 224 at r1](https://reviewable.io/reviews/harness/harness-core/31385#-MxrxVrA7z9fyKrR9xh-:-MxrxVrA7z9fyKrR9xh0:b4p6nav) ([raw file](https://github.com/harness/harness-core/blob/f48b647ce34de50aded1fa331602b7fd3c5f466e/400-rest/src/test/java/software/wings/scheduler/LdapGroupSyncJobHelperTest.java#L224)):*
> ```Java
>     }
>     assertThat(exceptionThrown).isEqualTo(false);
>     verify(userService).inviteUser(any(), eq(false), eq(true));
> ```

What are we verifying here?

**Comment by piyush-harness** [comment]
___
*[400-rest/src/test/java/software/wings/scheduler/LdapGroupSyncJobHelperTest.java, line 244 at r1](https://reviewable.io/reviews/harness/harness-core/31385#-Mxrxk6n74nOBFDhlWX_:-Mxrxk6n74nOBFDhlWXa:b-c5ssxk) ([raw file](https://github.com/harness/harness-core/blob/f48b647ce34de50aded1fa331602b7fd3c5f466e/400-rest/src/test/java/software/wings/scheduler/LdapGroupSyncJobHelperTest.java#L244)):*
> ```Java
>     Map<LdapUserResponse, Set<UserGroup>> addedGroupMembers = new HashMap<>();
>     LdapUserResponse ldapUserResponse =
>         LdapUserResponse.builder().name("ldap").email(null).userId("userId").dn("dn").build();
> ```

We should verify that if a Group Response has one member email set to null, He is dropped and others are synced successfully.

**Comment by piyush-harness** [comment]
___
*[400-rest/src/test/java/software/wings/scheduler/LdapGroupSyncJobHelperTest.java, line 349 at r1](https://reviewable.io/reviews/harness/harness-core/31385#-MxryHud5Mm9zMPWbcQA:-MxryHud5Mm9zMPWbcQB:b-2rdvck) ([raw file](https://github.com/harness/harness-core/blob/f48b647ce34de50aded1fa331602b7fd3c5f466e/400-rest/src/test/java/software/wings/scheduler/LdapGroupSyncJobHelperTest.java#L349)):*
> ```Java
>     assertThat(exceptionThrown).isEqualTo(false);
>     verify(userService, times(0)).inviteUser(any(), eq(false), eq(true));
>     verify(userService, times(2)).addUserToUserGroups(any(), any(), any(), eq(true), eq(true));
> ```

Where are we verifying if correct members are being added to groups?

**Review by piyush-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31385)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31385)* status: :shipit: complete! ✓

**Pull request merged**
