### PR TITLE
[feat]: [PIE-9145]: Used Settings for AuditEvents instead of FF

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Issue: Instead of an FF, we are using default settings for enabling audits
Change: Have added a new setting: enable auditevents at Account level. Also have rename Node Execution to Pipeline Execution events.
Testing: Local.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45527)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger ut5

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/45527#-NRJ0t6X5SSpq6dye-X0:-NRJ0t6X5SSpq6dye-X1:bvl4yhg) ([raw file](https://github.com/harness/harness-core/blob/7205d5f71550e2645f4cff89c5065e850db295fd/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L81)):*
> ```Java
>   private void sendOutboxEvents(NodeOutboxInfo nodeOutboxInfo) {
>     Ambiance ambiance = nodeOutboxInfo.getNodeExecution().getAmbiance();
>     String enableNodeAudit = "false";
> ```

please can we use constant here.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/45527#-NRJ1ECY9OrjsQqAcPuB:-NRJ1ECY9OrjsQqAcPuC:bwlmvl8) ([raw file](https://github.com/harness/harness-core/blob/7205d5f71550e2645f4cff89c5065e850db295fd/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L81)):*
> ```Java
>   private void sendOutboxEvents(NodeOutboxInfo nodeOutboxInfo) {
>     Ambiance ambiance = nodeOutboxInfo.getNodeExecution().getAmbiance();
>     String enableNodeAudit = "false";
> ```

why are we setting value to it if we are anyways going to fetch it via REST API?

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45527)* status: 11 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 84 at r3](https://reviewable.io/reviews/harness/harness-core/45527#-NRILKwC7P6KjsAHcRn3:-NRJ3AJ39RFAzCYW3uex:b-ytok09) ([raw file](https://github.com/harness/harness-core/blob/f83403dfd784b4093297a207da385dd017f2e838/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L84)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Vivek, did we do complete change? I see that you've caught exception but didn't return false.
</blockquote></details>

i have already intialised my enableAudit Varaible to false;
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 43 at r4](https://reviewable.io/reviews/harness/harness-core/45527#-NRJ0jKL-4FRnGMI1Z2K:-NRJ32Tv0KyXUGeodgdw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7205d5f71550e2645f4cff89c5065e850db295fd/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L43)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

if we are adding this decorator, then why do we need @inject in all fields?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/45527#-NRJ0t6X5SSpq6dye-X0:-NRJ335k-_jpemsHmNZe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7205d5f71550e2645f4cff89c5065e850db295fd/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L81)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please can we use constant here. 
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/45527#-NRJ1ECY9OrjsQqAcPuB:-NRJ33ydDewtJspTZEpm:boe26cn) ([raw file](https://github.com/harness/harness-core/blob/7205d5f71550e2645f4cff89c5065e850db295fd/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L81)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why are we setting value to it if we are anyways going to fetch it via REST API?
</blockquote></details>

It does not returns false value instead throws exception.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 90 at r4](https://reviewable.io/reviews/harness/harness-core/45527#-NRJ0vjv6uvtOx5Tzla7:-NRJ3IC_3wzXkzPO5VoB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7205d5f71550e2645f4cff89c5065e850db295fd/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L90)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this should be log.error
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 4 of 6 files at r2, 4 of 4 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45527)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by senjucanon2** [comment]
trigger ut0, ut7

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45527)* status: :shipit: complete! ✓

**Review by shalini-agr — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 4 of 6 files at r2, 4 of 4 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45527)* status: Some of the checks are too old.

**Comment by senjucanon2** [comment]
trigger ut0, ut2, ut4

**Pull request merged**
