### PR TITLE
feat: [CDS-85055]: Create common plan creator for v1 steps

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** Create common plan creator for v1 steps

**Testing:** Ran v1 pipeline with http and shell script step locally.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55822)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger smartchecks

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger ut9

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/v1/PmsStepPlanCreatorV3.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/55822#-Njrt5aVEQjSoakNZD7k:-Njrt5aVEQjSoakNZD7l:b-saptkg) ([raw file](https://github.com/harness/harness-core/blob/1967976bbd5f7dc3c33c389de1d93e7298e8200e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/v1/PmsStepPlanCreatorV3.java#L49)):*
> ```Java
> 
> @CodePulse(module = ProductModule.CDS, unitCoverageRequired = true, components = {HarnessModuleComponent.CDS_PIPELINE})
> public abstract class PmsStepPlanCreatorV3<T extends PmsAbstractStepNodeV1> implements PartialPlanCreator<T> {
> ```

I think V3 will create confusion like if a plan-creator belongs to V1 YAML or not. We can follow the convention to have V1 suffix for all plan-creator for V1 yamlVersion.
Lets name it  PmsStepPlanCreatorV1? And we can remove the V2 suffix from the  PmsStepPlanCreatorV2 and delete the  PmsStepPlanCreator? @archit-harness what do you think?

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreator.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/55822#-NjruNiR4Fo5CjKOmL28:-NjruNiR4Fo5CjKOmL29:b-8vw9m2) ([raw file](https://github.com/harness/harness-core/blob/1967976bbd5f7dc3c33c389de1d93e7298e8200e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreator.java#L43)):*
> ```Java
> 
>   @Override
>   public Set<String> getSupportedYamlVersions() {
> ```

This override is un-necessary. We can remove this.

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/v1/HttpStepNodeV1.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/55822#-Njrvy3uDeAnTVeeze4u:-Njrvy3uDeAnTVeeze4v:byrvtw) ([raw file](https://github.com/harness/harness-core/blob/1967976bbd5f7dc3c33c389de1d93e7298e8200e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/v1/HttpStepNodeV1.java#L76)):*
> ```Java
> 
>   @Override
>   public StepSpecType getStepSpecType() {
> ```

Lets use getSpec instead of getStepSpecType.  We can define abstract method getSpec in the abstractStepNodeV1 and  add @Value annotations on the individual stepNodes so getSpec will become automatically available.

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepNodeV1.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/55822#-Njrwyc96b37o7y2mb9V:-Njrwyc96b37o7y2mb9W:b-twducy) ([raw file](https://github.com/harness/harness-core/blob/1967976bbd5f7dc3c33c389de1d93e7298e8200e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepNodeV1.java#L73)):*
> ```Java
> 
>   @Override
>   public StepSpecType getStepSpecType() {
> ```

Same as http we wouldn't need this method.

**Comment by brijeshdhakar** [comment]
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/v1/AbstractStepNodeV1.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/55822#-Njrx23V5-2I64I8Q3Vf:-Njrx23V5-2I64I8Q3Vg:b-bg7b27) ([raw file](https://github.com/harness/harness-core/blob/1967976bbd5f7dc3c33c389de1d93e7298e8200e/953-yaml-commons/src/main/java/io/harness/plancreator/steps/v1/AbstractStepNodeV1.java#L47)):*
> ```Java
>   ParameterField<StrategyConfigV1> strategy;
>   PolicyConfig enforce;
>   @JsonIgnore public abstract StepSpecType getStepSpecType();
> ```

As commented in HttpStepNodeV1, lets define getSpec instead of getStepSpecType. Then we don't need to override it will automatically be overridden by getter method.

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepPlanCreator.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/55822#-NjryCz4ELivhqoUQhq2:-NjryCz4ELivhqoUQhq3:b-vn33bt) ([raw file](https://github.com/harness/harness-core/blob/1967976bbd5f7dc3c33c389de1d93e7298e8200e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepPlanCreator.java#L47)):*
> ```Java
>   @Override
>   public Set<String> getSupportedYamlVersions() {
>     return super.getSupportedYamlVersions();
> ```

Same, no need to override.

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55822)* status: 8 file(s) to review. 0 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/v1/PmsAbstractStepNodeV1.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/55822#-Njrxr830zhb4XHoLIFO:-Njueh1KE9xsaC20P41t:b3yjkrm) ([raw file](https://github.com/harness/harness-core/blob/1967976bbd5f7dc3c33c389de1d93e7298e8200e/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/v1/PmsAbstractStepNodeV1.java#L30)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

This can be moved to AbstractStepNodeV1 right. Nothing specific to PmsStepNodes.
</blockquote></details>

AbstractStepNodeV1 is in 953-yaml-commons, and this module doesn't depend on pms-sdk so PlanCreationContext can't be used there

**Review by archit-harness — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55822)* status: 6 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/v1/PmsStepPlanCreatorV3.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/55822#-Njrt5aVEQjSoakNZD7k:-NjujYdNDtN2cju7mRyb:bg885o6) ([raw file](https://github.com/harness/harness-core/blob/1967976bbd5f7dc3c33c389de1d93e7298e8200e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/v1/PmsStepPlanCreatorV3.java#L49)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

I think V3 will create confusion like if a plan-creator belongs to V1 YAML or not. We can follow the convention to have V1 suffix for all plan-creator for V1 yamlVersion.
Lets name it  PmsStepPlanCreatorV1? And we can remove the V2 suffix from the  PmsStepPlanCreatorV2 and delete the  PmsStepPlanCreator? @archit-harness what do you think?
</blockquote></details>

yeah lets follow that

**Comment by shalini-agr** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreator.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/55822#-NjruNiR4Fo5CjKOmL28:-NjuelYu6E32ISp7O0eP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1967976bbd5f7dc3c33c389de1d93e7298e8200e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreator.java#L43)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

This override is un-necessary. We can remove this.
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/v1/PmsStepPlanCreatorV3.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/55822#-Njrt5aVEQjSoakNZD7k:-NjutAGI4BAkTur09d66:b-h5u32j) ([raw file](https://github.com/harness/harness-core/blob/1967976bbd5f7dc3c33c389de1d93e7298e8200e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/v1/PmsStepPlanCreatorV3.java#L49)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

yeah lets follow that
</blockquote></details>

removed v3 suffix from here

**Comment by shalini-agr** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/v1/HttpStepNodeV1.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/55822#-Njrvy3uDeAnTVeeze4u:-NjueoQjCS27hCWYw6rx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1967976bbd5f7dc3c33c389de1d93e7298e8200e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/v1/HttpStepNodeV1.java#L76)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Lets use getSpec instead of getStepSpecType.  We can define abstract method getSpec in the abstractStepNodeV1 and  add @Value annotations on the individual stepNodes so getSpec will become automatically available.
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepNodeV1.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/55822#-Njrwyc96b37o7y2mb9V:-Njuep9383E1K7L8T2t0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1967976bbd5f7dc3c33c389de1d93e7298e8200e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepNodeV1.java#L73)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Same as http we wouldn't need this method.
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepPlanCreator.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/55822#-NjryCz4ELivhqoUQhq2:-NjuepkmE8rWYKyjz5tG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1967976bbd5f7dc3c33c389de1d93e7298e8200e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepPlanCreator.java#L47)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Same, no need to override.
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/v1/AbstractStepNodeV1.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/55822#-Njrx23V5-2I64I8Q3Vf:-Njuebs34xomNSIeS2ge:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1967976bbd5f7dc3c33c389de1d93e7298e8200e/953-yaml-commons/src/main/java/io/harness/plancreator/steps/v1/AbstractStepNodeV1.java#L47)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

As commented in HttpStepNodeV1, lets define getSpec instead of getStepSpecType. Then we don't need to override it will automatically be overridden by getter method.
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55822)* status: 6 file(s) to review. 7. unresolved discussions. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55822)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
