### PR TITLE
feat: [PL-24897]: added method to list branch

### PR DESCRIPTION
**Pull request by bhavya181**
This has integration of listBranches scm client methods with API

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32709)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmManagerFacilitatorServiceImpl.java` line 288 at r1](https://reviewable.io/reviews/harness/harness-core/32709#-N13JHAhBD6lE18Z4HCd:-N13JHAj6XWBD9AyTWGy:bwaevhx) ([raw file](https://github.com/harness/harness-core/blob/fa22428fe8111d488ac1054ea8e6375f0a02d37c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmManagerFacilitatorServiceImpl.java#L288)):*
> ```Java
>   @Override
>   public ListBranchesWithDefaultResponse listBranches(String accountIdentifier, String orgIdentifier,
>       String projectIdentifier, String connectorRef, String repoUrl, PageRequestDTO pageRequest) {
> ```

this isn't repoUrl, right? It must be just the repo name.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 324 at r1](https://reviewable.io/reviews/harness/harness-core/32709#-N13JQO77VRnHH2K75kI:-N13JQO77VRnHH2K75kJ:bhngtx3) ([raw file](https://github.com/harness/harness-core/blob/fa22428fe8111d488ac1054ea8e6375f0a02d37c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L324)):*
> ```Java
>           NGCommonEntityConstants.PROJECT_KEY) @ProjectIdentifier String projectIdentifier,
>       @Parameter(description = GitSyncApiConstants.REPO_URL_PARAM_MESSAGE) @NotBlank @QueryParam(
>           NGCommonEntityConstants.REPO_URL) String repoUrl,
> ```

This should be repoName, we don't need repoUrl

**Comment by mohitg0795** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/scm/GitRefType.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/32709#-N13JYsED1ZZZghf5Ecw:-N13JYsED1ZZZghf5Ecx:bv64kp1) ([raw file](https://github.com/harness/harness-core/blob/fa22428fe8111d488ac1054ea8e6375f0a02d37c/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/scm/GitRefType.java#L24)):*
> ```Java
>   CREATE_NEW_BRANCH,
>   REPOSITORY,
>   BRANCH_WITH_DEFAULT
> ```

can be better eg: BRANCH_LIST_WITH_DEFAULT_BRANCH

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32709)* status: 13 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmManagerFacilitatorServiceImpl.java` line 288 at r1](https://reviewable.io/reviews/harness/harness-core/32709#-N13JHAhBD6lE18Z4HCd:-N13U5iQ5XeElpiY4z97:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fa22428fe8111d488ac1054ea8e6375f0a02d37c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmManagerFacilitatorServiceImpl.java#L288)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this isn't repoUrl, right? It must be just the repo name.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 324 at r1](https://reviewable.io/reviews/harness/harness-core/32709#-N13JQO77VRnHH2K75kI:-N13U9SY4vvusFPUV69g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fa22428fe8111d488ac1054ea8e6375f0a02d37c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L324)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This should be repoName, we don't need repoUrl
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/scm/GitRefType.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/32709#-N13JYsED1ZZZghf5Ecw:-N13U8EJ2l7UEb4TzKy2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fa22428fe8111d488ac1054ea8e6375f0a02d37c/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/scm/GitRefType.java#L24)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can be better eg: BRANCH_LIST_WITH_DEFAULT_BRANCH
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32709#-:-N13XDHJ2TcSPJ2W9u3N:bnfp4nl)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32709#-:-N1CtjoH-yeJVuqN3jde:bnfp4nl)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 11 of 12 files at r2, 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32709)* status: :shipit: complete! ✓

**Pull request merged**
