### PR TITLE
feat: [CDS-47420]: Adding consumers and processors on pipeline executions

### PR DESCRIPTION
**Pull request by boopesh007**
## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40883)

### CODE REVIEW

**Review by shalini-agr — APPROVED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40883)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40883)* status: 17 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/overviewLandingPage/PipelineExecutionSummaryChangeEventHandler.java` line 96 at r2](https://reviewable.io/reviews/harness/harness-core/40883#-NIC9PLZCiqKCGWlFxW8:-NIC9PLZCiqKCGWlFxW9:b-i2rafh) ([raw file](https://github.com/harness/harness-core/blob/5cbc5054c9fdd9bf09e0516443af165fa4e47334/pipeline-service/service/src/main/java/io/harness/pms/event/overviewLandingPage/PipelineExecutionSummaryChangeEventHandler.java#L96)):*
> ```Java
>       }
>     }
>     if (node.get(PipelineExecutionSummaryKeys.moduleInfo).get("ci") != null) {
> ```

Please handle case for cd also. What if pipeline is of type cd, how we will store author info in that condition?

**Review by shalini-agr — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, 7 of 7 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40883)* status: 18 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by prashantsharma04 — COMMENTED** [review]
> Reviewed 8 of 17 files at r1, 1 of 2 files at r2, 3 of 7 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40883)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40883)* status: 4 file(s) to review.

**Review by shalini-agr — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40883)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40883)* status: 4 file(s) to review.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40883#-:-NIXWV4V1Bz_8uYwAh93:bnfp4nl)* status: 4 file(s) to review.

**Pull request merged**
