### PR TITLE
fix:[CDS-47343]: Do not dispatch to slack when url is empty or null

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- Added a code guard to don't dispatch slack integration when the URL is empty or null.
- Saving on logging storage costs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40680)

### CODE REVIEW

**Comment by Fernando-Dourado** [comment]
trigger codebasehash

**Comment by Fernando-Dourado** [comment]
trigger smartcheck

**Review by lasdox — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40680)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by vcalasansh — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40680)* status: :shipit: complete! ✓

**Pull request merged**
