### PR TITLE
feat: [PIE-5813]: Endpoint to validate trigger yaml with pipeline

### PR DESCRIPTION
**Pull request by sribalij**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38871)

### CODE REVIEW

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38871)* status: 6 file(s) to review. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java` line 230 at r2](https://reviewable.io/reviews/harness/harness-core/38871#-NEdXKkl078OMSyKc8TT:-NEdXKkm-xLEpNLFfhcO:bjea3r4) ([raw file](https://github.com/harness/harness-core/blob/2e1e7f6969f0f60b3512616b486dd6172d850476/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java#L230)):*
> ```Java
>       }
>     } catch (Exception exception) {
>       throw new InvalidRequestException("Failed while validating trigger yaml: " + exception.getMessage());
> ```

nit, add exceptiion as parameter so that it gets logged with stacktrace

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38871)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by abhinav-harness** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java` line 230 at r2](https://reviewable.io/reviews/harness/harness-core/38871#-NEdabc_2OsXrTw88uv7:-NEdabc_2OsXrTw88uv8:b-t77xc3) ([raw file](https://github.com/harness/harness-core/blob/2e1e7f6969f0f60b3512616b486dd6172d850476/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java#L230)):*
> ```Java
>       }
>     } catch (Exception exception) {
>       throw new InvalidRequestException("Failed while validating trigger yaml: " + exception.getMessage());
> ```

agreed

**Review by sribalij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38871)* status: 6 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java` line 230 at r2](https://reviewable.io/reviews/harness/harness-core/38871#-NEdXKkl078OMSyKc8TT:-NEdaqiD5pzAV_24WB3S:b3mghvc) ([raw file](https://github.com/harness/harness-core/blob/2e1e7f6969f0f60b3512616b486dd6172d850476/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java#L230)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, add exceptiion as parameter so that it gets logged with stacktrace
</blockquote></details>

Yup. Makes sense

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38871)* status: 1. unresolved discussions.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38871)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38871)* status: 1. unresolved discussions.

**Pull request merged**
