### PR TITLE
feat: [PL-31794]: Fixed createdAt field retention in Project flow

### PR DESCRIPTION
**Pull request by meenakshi-harness**
## Describe your changes
1. We got a CFD where project sort order was random when sorted on createdAt field.
2. We noticed some of the Projects which were updated has `createdAt` as null, that is why sort order was not applicable.
3. There was a bug in update flow of project api where createdAt field was not retained while saving updated project and was set as null. This was causing sort behaviour to fail.
4. Did the code change to always set createdAt field from existing records
5. Added UTs and tested create, update and list api with sorting.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44690)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44690)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 411 at r2](https://reviewable.io/reviews/harness/harness-core/44690#-NPbYnRlBKnp0EodSq_n:-NPbYnRlBKnp0EodSq_o:b-71qdry) ([raw file](https://github.com/harness/harness-core/blob/881f7cd43f21de467af5be42a66b9fc6b78ff77c/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L411)):*
> ```Java
>       project.setId(existingProject.getId());
>       project.setCreatedAt(existingProject.getCreatedAt() == null ? existingProject.getLastModifiedAt()
>                                                                   : existingProject.getCreatedAt());
> ```

Why this should be required? Why using @CreatedDate annotation isn't sufficient?

**Comment by meenakshi-harness** [comment]
trigger ut0

**Comment by meenakshi-harness** [comment]
trigger JavaUnitTests7

**Comment by meenakshi-harness** [comment]
trigger ut7

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44690)* status: :shipit: complete! ✓

**Pull request merged**
