### PR TITLE
feat: [CDS-59186]: container step abstraction

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46553)

### CODE REVIEW

**Comment by abhinav-harness** [comment]
trigger ut5

**Comment by sahilhindwani-harness** [comment]
*[`879-pipeline-ci-commons/src/main/java/io/harness/pms/sdk/core/plugin/AbstractContainerStepV2.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/46553#-NTRrPqI9nl2CRI6LGgC:-NTRrPqI9nl2CRI6LGgD:b-x78ku4) ([raw file](https://github.com/harness/harness-core/blob/d2cf2979f681bb8b1f2f673ef9f79e4dba896084/879-pipeline-ci-commons/src/main/java/io/harness/pms/sdk/core/plugin/AbstractContainerStepV2.java#L55)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> @Slf4j
> public abstract class AbstractContainerStepV2 implements AsyncExecutableWithRbac<StepElementParameters> {
> ```

@abhinav-harness , can we add comments on abstract function as to what we are expecting the implementors to provide?

**Comment by sahilhindwani-harness** [comment]
*[`879-pipeline-ci-commons/src/main/java/io/harness/pms/sdk/core/plugin/AbstractContainerStepV2.java` line 161 at r2](https://reviewable.io/reviews/harness/harness-core/46553#-NTRr_Xv0OzvzcljmNF8:-NTRr_Xv0OzvzcljmNF9:b-oajmr7) ([raw file](https://github.com/harness/harness-core/blob/d2cf2979f681bb8b1f2f673ef9f79e4dba896084/879-pipeline-ci-commons/src/main/java/io/harness/pms/sdk/core/plugin/AbstractContainerStepV2.java#L161)):*
> ```Java
>     String delegateSvcEndpoint = DELEGATE_SVC_ENDPOINT;
>     if (executionServiceConfig != null) {
>       isLocal = executionServiceConfig.isLocal();
> ```

Could you please create a ticket to make this executionServiceConfig flow from pipeline-service rather than hardcoding it in every service?

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, 42 of 42 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46553)* status: 44 file(s) to review. 0 of 2 approvals obtained.

**Comment by abhinav-harness** [comment]
followup has the change for executionservice config.

**Comment by abhinav-harness** [comment]
Will write documentation in followup for abstract class

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46553)* status: 44 file(s) to review. 1 of 2 approvals obtained.

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Review by Y0709 — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 42 of 42 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46553)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
trigger review

**Comment by abhinav-harness** [comment]
trigger review

**Review by harshjain12 — APPROVED** [review]

**Pull request merged**
