### PR TITLE
feat: [IDP-172]: Github implementation or backstage git integration

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43994)

### CODE REVIEW

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43994)* status: 9 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/service/BUILD.bazel` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOep5t6H-n39yHk9X6:-NOOep5t6H-n39yHk9X7:b-21p6ma) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/BUILD.bazel#L39)):*
> ```Starlark
>         "//idp-service/contracts:module",
>         "//idp-service/service/src/main/java/io/harness/idp/config:module",
>         "//idp-service/service/src/main/java/io/harness/idp/gitIntigration:module",
> ```

nit: Please rename to 'gitIntegration' (spell check)
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/ConnectorTypes.java` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOf9Kq-xFst-DwSshz:-NOOf9Kq-xFst-DwSsi-:b-x1bmiu) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/ConnectorTypes.java#L10)):*
> ```Java
> package io.harness.idp.gitIntigration;
> 
> public enum ConnectorTypes { GITHUB }
> ```

Rather than maintaining our own connector types for IDP software catalog, it is better to use already existing ConnectorType bean (io.harness.delegate.beans.connector.ConnectorType). Reason being - at the end, we are going to use the connectors available / created over there. 

We can add a method called getIdpCatalogConnectorTypes in that bean class (io.harness.delegate.beans.connector.ConnectorType) which returns the available connector types for IDP software catalog.
___
*[`idp-service/service/src/main/java/io/harness/idp/secret/beans/dto/EnvironmentSecretDTO.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOg4xMDg2-qLwVfNWj:-NOOg4xMDg2-qLwVfNWk:b18o885) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/secret/beans/dto/EnvironmentSecretDTO.java#L23)):*
> ```Java
> @JsonInclude(JsonInclude.Include.NON_NULL)
> @OwnedBy(HarnessTeam.IDP)
> public class EnvironmentSecretDTO {
> ```

I suggest we can create this as static class inside 'EnvironmentSecretValueDTO' class

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43994)* status: 9 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/ConnectorTypes.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOJtg_u3nyeumRlLOuP:-NOJtg_u3nyeumRlLOuQ:b-pe8s43) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/ConnectorTypes.java#L8)):*
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html#:~:text=Package%20names%20are%20written%20in%20all%20lower%20case%20to%20avoid%20conflict%20with%20the%20names%20of%20classes%20or%20interfaces.

> Package names are written in all lower case to avoid conflict with the names of classes or interfaces.



_Code quote:_
```Java
gitIntigration
```
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/ConnectorTypes.java` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOf9Kq-xFst-DwSshz:-NOOk4FIDu4jovozNw70:b32v57) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/ConnectorTypes.java#L10)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Rather than maintaining our own connector types for IDP software catalog, it is better to use already existing ConnectorType bean (io.harness.delegate.beans.connector.ConnectorType). Reason being - at the end, we are going to use the connectors available / created over there. 

We can add a method called getIdpCatalogConnectorTypes in that bean class (io.harness.delegate.beans.connector.ConnectorType) which returns the available connector types for IDP software catalog.
</blockquote></details>

+1
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/baseClass/ConnectorSecrets.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOkL_S0esmF6ryhYQw:-NOOkL_S0esmF6ryhYQx:bub4kcb) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/baseClass/ConnectorSecrets.java#L14)):*
> ```Java
> import java.util.List;
> 
> public interface ConnectorSecrets {
> ```

Could this be ConnectorProcessor?
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/factory/ConnectorSecretsFactory.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOgDMw-35rUM_P9aLB:-NOOgDMw-35rUM_P9aLC:bgy8x20) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/factory/ConnectorSecretsFactory.java#L22)):*
> ```Java
>   @Inject private ConnectorResourceClient connectorResourceClient;
> 
>   public ConnectorSecrets getConnectorFactory(ConnectorTypes connectorTypes) {
> ```

We could name this as getConnectorProcessor()?
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/factory/ConnectorSecretsFactory.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOJv6rZAK6RU7MNpSCe:-NOJv6rZAK6RU7MNpSCf:bgbrjlh) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/factory/ConnectorSecretsFactory.java#L27)):*
> ```Java
>     }
> 
>     switch (connectorTypes) {
> ```

Can we add a default case and throw an unsupported exception?



_Code quote:_
```Java
switch
```
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/factory/ConnectorSecretsFactory.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOkc-1152BDthAUPtt:-NOOkc-1152BDthAUPtu:b57xtih) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/factory/ConnectorSecretsFactory.java#L29)):*
> ```Java
>     switch (connectorTypes) {
>       case GITHUB:
>         return new GithubConnector(connectorResourceClient);
> ```

Can we @inject instead?
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/implementation/GithubConnector.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOllvF2T3FeERoGvKv:-NOOllvF2T3FeERoGvKw:bllgble) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/implementation/GithubConnector.java#L26)):*
> ```Java
> import java.util.Optional;
> 
> public class GithubConnector implements ConnectorSecrets {
> ```

GithubConnectorProcessor?
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/implementation/GithubConnector.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOmmAc3heXWQzvZrYB:-NOOmmAc3heXWQzvZrYC:b-xd9xu5) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/implementation/GithubConnector.java#L27)):*
> ```Java
> 
> public class GithubConnector implements ConnectorSecrets {
>   private ConnectorResourceClient connectorResourceClient;
> ```

How about injecting this in an abstract class (which either implements this interface OR has an abstract method)
Could you evaluate which would be a better code design?



_Code quote:_
```Java
connectorResourceClient
```
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/implementation/GithubConnector.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOoK7qB4KPUlgNTLcY:-NOOoK7qB4KPUlgNTLcZ:b-m0d59l) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/implementation/GithubConnector.java#L47)):*
> ```Java
> 
>           EnvironmentSecretDTO appIdEnvironmentSecretDTO =
>               EnvironmentSecretDTO.builder().envName("GITHUB_APP_APPLICATION_ID").build();
> ```

Could we define these env names in a separate constants file? So that all envs will be in one place



_Code quote:_
```Java
GITHUB_APP_APPLICATION_ID
```
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/implementation/GithubConnector.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOorwR9sGZ3k1r9Dm5:-NOOorwR9sGZ3k1r9Dm6:b-snzlun) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/implementation/GithubConnector.java#L71)):*
> ```Java
>           EnvironmentSecretDTO tokenEnvironmentSecretDTO = EnvironmentSecretDTO.builder()
>                                                                .secretIdentifier(spec.getTokenRef().getIdentifier())
>                                                                .envName("GITHUB_TOKENS")
> ```

GITHUB_TOKEN ?



_Code quote:_
```Java
GITHUB_TOKENS
```

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43994)* status: 11 file(s) to review. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/service/BUILD.bazel` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOep5t6H-n39yHk9X6:-NOOxyJs4BFx5Hmnk7_z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/BUILD.bazel#L39)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

nit: Please rename to 'gitIntegration' (spell check)
</blockquote></details>

Done.
___
*[`idp-service/service/src/main/java/io/harness/idp/secret/beans/dto/EnvironmentSecretDTO.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOg4xMDg2-qLwVfNWj:-NOQDpxR6z0sPDx79yfc:bl40g27) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/secret/beans/dto/EnvironmentSecretDTO.java#L23)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

I suggest we can create this as static class inside 'EnvironmentSecretValueDTO' class
</blockquote></details>

EnvironmentSecretDTO is having generic on which we can use independently also thats why this is separate.
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/ConnectorTypes.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOJtg_u3nyeumRlLOuP:-NOOy0j-4JFtu0rszd6B:b-7rl0jd) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/ConnectorTypes.java#L8)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html#:~:text=Package%20names%20are%20written%20in%20all%20lower%20case%20to%20avoid%20conflict%20with%20the%20names%20of%20classes%20or%20interfaces.

> Package names are written in all lower case to avoid conflict with the names of classes or interfaces.

</blockquote></details>

done.
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/ConnectorTypes.java` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOf9Kq-xFst-DwSshz:-NOOy4NZ6f03rrjGaamr:b-r1yh0r) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/ConnectorTypes.java#L10)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

+1
</blockquote></details>

done , directly used it.....because creating based on module is not good i think so not added the method...... i saw one method was implemented but it was based on type.
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/factory/ConnectorSecretsFactory.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOgDMw-35rUM_P9aLB:-NOOyUNJ1XpX43MKi65B:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/factory/ConnectorSecretsFactory.java#L22)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

We could name this as getConnectorProcessor()?
</blockquote></details>

done
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/factory/ConnectorSecretsFactory.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOJv6rZAK6RU7MNpSCe:-NOQD_Oe5eWWDDoglGBM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/factory/ConnectorSecretsFactory.java#L27)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we add a default case and throw an unsupported exception?
</blockquote></details>

Done.
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/factory/ConnectorSecretsFactory.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOkc-1152BDthAUPtt:-NOQDaXlDk4IljbdzjE2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/factory/ConnectorSecretsFactory.java#L29)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we @inject instead?
</blockquote></details>

Done.
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/baseClass/ConnectorSecrets.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOkL_S0esmF6ryhYQw:-NOOyIKa6RnUixIKsqyf:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/baseClass/ConnectorSecrets.java#L14)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Could this be ConnectorProcessor?
</blockquote></details>

Done
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/implementation/GithubConnector.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOllvF2T3FeERoGvKv:-NOOycS1ETyME9bjMemK:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/implementation/GithubConnector.java#L26)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

GithubConnectorProcessor?
</blockquote></details>

done
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/implementation/GithubConnector.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOmmAc3heXWQzvZrYB:-NOQDmYn7_n5dIi6QSx6:b-ledog9) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/implementation/GithubConnector.java#L27)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

How about injecting this in an abstract class (which either implements this interface OR has an abstract method)
Could you evaluate which would be a better code design?
</blockquote></details>

creating a abstract class with abstract method will be good because if we are using interface which have method to implement we anyway not overriding it in abstract class but will override it in different implementations of connectors and there while overriding we need ConnectorResourceClient to be injected for the implementation…..keeping them separate for this implementation in abstract class and interface is not helping much as we are not planning to use interface for other implementation without ConnectorResourceClient
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/implementation/GithubConnector.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOoK7qB4KPUlgNTLcY:-NOQ6u0vB0adKeiqmMV0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/implementation/GithubConnector.java#L47)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Could we define these env names in a separate constants file? So that all envs will be in one place
</blockquote></details>

Done.
___
*[`idp-service/service/src/main/java/io/harness/idp/gitIntigration/implementation/GithubConnector.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/43994#-NOOorwR9sGZ3k1r9Dm5:-NOQ6stn820CFsSKF_B1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/820df9c3ddb3bc8824cd8ee0b66f8d342c54fa8c/idp-service/service/src/main/java/io/harness/idp/gitIntigration/implementation/GithubConnector.java#L71)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

GITHUB_TOKEN ?
</blockquote></details>

Done.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 4 of 9 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43994)* status: Some of the checks are too old. 9 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/gitintegration/EnvironmentVariablesNames.java` line 11 at r3](https://reviewable.io/reviews/harness/harness-core/43994#-NOgzVdY0X2ipGqs61RO:-NOgzVdY0X2ipGqs61RP:bauompw) ([raw file](https://github.com/harness/harness-core/blob/ebbc35e7ebb4c497545b6cc75831180ee89e05c1/idp-service/service/src/main/java/io/harness/idp/gitintegration/EnvironmentVariablesNames.java#L11)):*
> ```Java
> 
> public class EnvironmentVariablesNames {
>   public static final String githubToken = "GITHUB_TOKEN";
> ```

nit: we usually follow Snake Case (All Caps) for constants. So this variable could be GITHUB_TOKEN.

**Review by sathish-soundarapandian — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 4 of 9 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43994)* status: Some of the checks are too old. 2. unresolved discussions.

**Review by deepharness — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 4 of 9 files at r2, 3 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43994)* status: 2 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43994)* status: 2. unresolved discussions. 

___
*[`idp-service/service/src/main/java/io/harness/idp/gitintegration/implementation/GithubConnectorProcessor.java` line 35 at r4](https://reviewable.io/reviews/harness/harness-core/43994#-NOjKI689XYq5kYU06dI:-NOjKI689XYq5kYU06dJ:bmkex5g) ([raw file](https://github.com/harness/harness-core/blob/ffd2b8d458ae51bdb71c61717d404927c45cbf85/idp-service/service/src/main/java/io/harness/idp/gitintegration/implementation/GithubConnectorProcessor.java#L35)):*
> ```Java
>     List<EnvironmentSecretValueDTO> resultList = new ArrayList<>();
> 
>     if (!connectorDTO.isPresent()) {
> ```

nit: we could use isEmpty()

**Review by vikyathharekal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43994)* status: 2. unresolved discussions.

**Pull request merged**
