### PR TITLE
feat: [CDS-7467]: Prune support in NG

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)

### CODE REVIEW

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStepParameters.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/34256#-N4zezHpAmk7tgCyDL8D:-N4zezHqA4pEJ57up76e:b3b6mp8) ([raw file](https://github.com/harness/harness-core/blob/6c2ed76a46f648409ca3590442f2924e56797ea4/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStepParameters.java#L65)):*
> ```Java
>   @Override
>   @JsonIgnore
>   public List<String> getCommandUnits(boolean isPruningEnabled) {
> ```

do we have decided to add another command unit for prune?

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStepParameters.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/34256#-N4zfJ8C7PPJEctBR4Nn:-N4zfJ8C7PPJEctBR4No:b4054ai) ([raw file](https://github.com/harness/harness-core/blob/6c2ed76a46f648409ca3590442f2924e56797ea4/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStepParameters.java#L65)):*
> ```Java
>   @Override
>   @JsonIgnore
>   public List<String> getCommandUnits(boolean isPruningEnabled) {
> ```

if we have decided to add another command unit for prune, lets complete this logic.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGSwapServicesStepParameters.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/34256#-N4zfflT41eltDs0nQP0:-N4zfflU3DoIvSEJuKJS:b-afi826) ([raw file](https://github.com/harness/harness-core/blob/6c2ed76a46f648409ca3590442f2924e56797ea4/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGSwapServicesStepParameters.java#L55)):*
> if we have decided to add another command unit for prune, lets complete this logic.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 20 files at r1, 4 of 21 files at r2, 2 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: Some of the checks are too old. 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 2 of 20 files at r1, 1 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: Some of the checks are too old. 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 2 of 20 files at r1, 1 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: Some of the checks are too old. 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 3 of 20 files at r1, 1 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: Some of the checks are too old. 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 3 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: Some of the checks are too old. 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: Some of the checks are too old. 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 2 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: Some of the checks are too old. 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 20 files at r1, 2 of 21 files at r2, 6 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained.

**Comment by tchaurasiya** [comment]
*[a discussion](https://reviewable.io/reviews/harness/harness-core/34256#-N4zrN5M25eyIdVgCPJi:-N4zrN5N2B7G0uEUq250:b-l76l36) (no related file):*
@namantalaycha10 looks good, but let's also test backward compatibility on delegate on this pr.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained.

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: 24 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingRollbackStepParameters.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/34256#-N4guWNm-a8c_mZm1mYf:-N5-1nytCCWp4aTNvKje:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d1c6b193df6dd639f5f0582b5876014ce62ce344/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingRollbackStepParameters.java#L44)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

why do we have `RecreatePrunedResource` command here. It would only come into picture when we have pruning enabled .. right ..?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRequestHandler.java` line 204 at r2](https://reviewable.io/reviews/harness/harness-core/34256#-N4gvhYK63lhR6_onmfg:-N5-2AvcESZtDW3n5maY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d1c6b193df6dd639f5f0582b5876014ce62ce344/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRequestHandler.java#L204)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

make this at WARN level
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackRequestHandler.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/34256#-N4gwZkj0PicGjIAsK_0:-N5-8Zt8AXC2U484cP6R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d1c6b193df6dd639f5f0582b5876014ce62ce344/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackRequestHandler.java#L87)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

refactor this to move to a different method.
</blockquote></details>

Done.

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: 24 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackRequestHandler.java` line 93 at r2](https://reviewable.io/reviews/harness/harness-core/34256#-N4gwNNbCG_KZBLSd_mc:-N500YI28NQWzt5r4hL1:b-tc4hed) ([raw file](https://github.com/harness/harness-core/blob/d1c6b193df6dd639f5f0582b5876014ce62ce344/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackRequestHandler.java#L93)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

should we not mark this as FAILED ..?
</blockquote></details>

We wanted to treat pruning as an additional functionality( not as the main deployment).
So anything failing with pruning, we does not stop the deployment
this is same what happening in CG , just confirmed with @tchaurasiya

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: 24 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/34256#-N4zrN5M25eyIdVgCPJi:-N500ngdAPIR0NAAqaUw:b2nhysk) (no related file):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

@namantalaycha10 looks good, but let's also test backward compatibility on delegate on this pr.
</blockquote></details>

ack

___

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 22 of 24 files at r4, 5 of 19 files at r6, 18 of 18 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained.

**Review by tchaurasiya — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: 1 change requests. 4. unresolved discussions.

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r3, 22 of 24 files at r4, 4 of 19 files at r6, 18 of 18 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingRollbackStep.java` line 119 at r9](https://reviewable.io/reviews/harness/harness-core/34256#-N55L6rg48Qg3EXCETdK:-N55L6rh3IWgoAFFUChh:bj1hkwu) ([raw file](https://github.com/harness/harness-core/blob/470795f1a9f2cfd39c9f1a20c1e6df43fb5c6f65/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingRollbackStep.java#L119)):*
> ```Java
>       K8sRollingOutcome k8sRollingOutcome = (K8sRollingOutcome) k8sRollingOptionalOutput.getOutput();
>       if (k8sStepHelper.isPruningEnabled(accountId)) {
>         prunedResources =
> ```

define the variable near to its first usage.
Also in this case, since `prunedResources` list is only used at one place, we can simplify this further.



_Code quote:_
```Java
      if (k8sStepHelper.isPruningEnabled(accountId)) {
        prunedResources =
            k8sRollingOutcome.getPrunedResourceIds() == null ? emptyList() : k8sRollingOutcome.getPrunedResourceIds();
      }
      rollbackRequestBuilder.releaseName(k8sRollingOutcome.getReleaseName())
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingStep.java` line 197 at r9](https://reviewable.io/reviews/harness/harness-core/34256#-N55LSHu79ITgbAeCR-Q:-N55LSHu79ITgbAeCR-R:b-o3u6ja) ([raw file](https://github.com/harness/harness-core/blob/470795f1a9f2cfd39c9f1a20c1e6df43fb5c6f65/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingStep.java#L197)):*
> ```Java
>             .prunedResourceIds(k8sStepHelper.isPruningEnabled(AmbianceUtils.getAccountId(ambiance))
>                     ? k8sTaskResponse.getPrunedResourceIds()
>                     : Collections.emptyList())
> ```

extract this to a helper function. I see this code snippet used at multiple places.



_Code quote:_
```Java
            .prunedResourceIds(k8sStepHelper.isPruningEnabled(AmbianceUtils.getAccountId(ambiance))
                    ? k8sTaskResponse.getPrunedResourceIds()
                    : Collections.emptyList())
```

**Comment by jennyjames21** [comment]
Is the change tested with older version of delegate?

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: 57 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingRollbackStep.java` line 119 at r9](https://reviewable.io/reviews/harness/harness-core/34256#-N55L6rg48Qg3EXCETdK:-N5DxCje3u3cw_m4iE0R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/470795f1a9f2cfd39c9f1a20c1e6df43fb5c6f65/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingRollbackStep.java#L119)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

define the variable near to its first usage.
Also in this case, since `prunedResources` list is only used at one place, we can simplify this further.
</blockquote></details>

Done.

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: 57 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingRollbackStep.java` line 182 at r2](https://reviewable.io/reviews/harness/harness-core/34256#-N4guHpt-N4l-Utc9f8c:-N5DxF8RB3aHnZYToGAy:b-7g8q73) ([raw file](https://github.com/harness/harness-core/blob/d1c6b193df6dd639f5f0582b5876014ce62ce344/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingRollbackStep.java#L182)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

should we have a different name for this outcome.?
</blockquote></details>

checked Outcome name will be different

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: 57 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingStep.java` line 197 at r9](https://reviewable.io/reviews/harness/harness-core/34256#-N55LSHu79ITgbAeCR-Q:-N5DyBLmCIQcQ5urcwTG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/470795f1a9f2cfd39c9f1a20c1e6df43fb5c6f65/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingStep.java#L197)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

extract this to a helper function. I see this code snippet used at multiple places.
</blockquote></details>

Done.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 5 of 5 files at r10, 50 of 52 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256)* status: 1 change requests. 3. unresolved discussions.

**Comment by namantalaycha10** [comment]
trigger ti2

**Review by jennyjames21 — APPROVED** [review]
:lgtm:

> Reviewed 9 of 20 files at r1, 12 of 21 files at r2, 5 of 11 files at r3, 22 of 24 files at r4, 2 of 19 files at r6, 18 of 18 files at r8, 5 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34256#-:-N5E6J2BE9JOu7v5hJ5I:bnfp4nl)* status: 1 change requests. 3. unresolved discussions.

**Pull request merged**
