### PR TITLE
techdebt: [PIE-0]: made redis topic name a config variable for ng manager

### PR DESCRIPTION
**Pull request by shalini-agr**
…ager

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34967)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34967)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 447 at r2](https://reviewable.io/reviews/harness/harness-core/34967#-N6CFm7T258P7LX1hBDo:-N6CFm7T258P7LX1hBDp:b-ua997a) ([raw file](https://github.com/harness/harness-core/blob/df160504c8e8864806a0d45f8501b315ac1f9126/120-ng-manager/config.yml#L447)):*
> ```YAML
> 
> debeziumConsumerConfigs:
>   - topicName: ${TOPIC_NAME:-DEBEZIUM_pmsMongo.pms-harness.planExecutionsSummary}
> ```

what happens if you add another topic?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34967)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 447 at r2](https://reviewable.io/reviews/harness/harness-core/34967#-N6CFm7T258P7LX1hBDo:-N6CIUcsE8bOXPaYREZb:b-akefc2) ([raw file](https://github.com/harness/harness-core/blob/df160504c8e8864806a0d45f8501b315ac1f9126/120-ng-manager/config.yml#L447)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

what happens if you add another topic?
</blockquote></details>

Nothing without code change actually, we can use that topic name when adding a new Redis consumer for that topic.

**Review by hextechpal — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34967)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34967)* status: 1 change requests. 1. unresolved discussions.

**Pull request merged**
