### PR TITLE
feat: [CDS-78912]: support metadata only GET for Service entities

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
Everytime we don't need to make git calls to fetch service entity, sometimes just metadata calls (mongo) are enough. Eg. Delete flow. 
Introduces a new method to just fetch metadata and made the change for delete flow for now. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52836)

### CODE REVIEW

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/52836#-NeMEbAK2nHWy5oFaR6x:-NeMEbAL-0kOJzEvm3jr:bdpl9ak) ([raw file](https://github.com/harness/harness-core/blob/ddc39dd9931e00bdee55736dad531507bc7a720a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java#L48)):*
> ```Java
>       String serviceIdentifier, boolean deleted, boolean includeMetadataOnly);
> 
>   Optional<ServiceEntity> get(String accountId, String orgIdentifier, String projectIdentifier,
> ```

just from reading the signature of these 2 get methods, does it mean that the first method will be used for fetching where we do not need the yaml of the service ?

**Comment by hingerabhinav** [comment]
> _[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/52836#-NeMEbAK2nHWy5oFaR6x:-NeMEbAL-0kOJzEvm3jr:bdpl9ak) ([raw file](https://github.com/harness/harness-core/blob/ddc39dd9931e00bdee55736dad531507bc7a720a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java#L48)):_
> 
> > ```java
> >       String serviceIdentifier, boolean deleted, boolean includeMetadataOnly);
> > 
> >   Optional<ServiceEntity> get(String accountId, String orgIdentifier, String projectIdentifier,
> > ```
> 
> just from reading the signature of these 2 get methods, does it mean that the first method will be used for fetching where we do not need the yaml of the service ?

@yogesh-chauhan upon checking further the params governing fetching from git (cache and fallback) and includeMetadataOnly (get from mongo) does not make sense to be used together. I would expose 2 methods to achieve these 2 use cases. Existing default method's behavior would be to get from git (since callers would be depending on YAML).

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by hingerabhinav** [comment]
trigger ut7, ut8

**Comment by hingerabhinav** [comment]
trigger uts

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 3 of 8 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52836)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/52836#-NeO7iEw3Up_n9V-kUav:-NeO7iEx2SIOrTRhUbrV:b-go64lf) ([raw file](https://github.com/harness/harness-core/blob/d05968dfddcef0aee3b381759d3d1aca022102d7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java#L46)):*
> ```Java
>    *         no matching entity is found.
>    */
>   Optional<ServiceEntity> getMetadataOnly(
> ```

"getMetadata" itself can be the name of the interface

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52836)* status: 8 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/52836#-NeO7p4Z-eRJRmUvABxy:-NeO7p4Z-eRJRmUvABxz:biarvkp) ([raw file](https://github.com/harness/harness-core/blob/d05968dfddcef0aee3b381759d3d1aca022102d7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java#L47)):*
> ```Java
>    */
>   Optional<ServiceEntity> getMetadataOnly(
>       String accountId, String orgIdentifier, String projectIdentifier, String serviceIdentifier, boolean deleted);
> ```

should be "accountIdentifier"

**Comment by mohitg0795** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 263 at r3](https://reviewable.io/reviews/harness/harness-core/52836#-NeO7vixAm2neS2nPR9P:-NeO7vixAm2neS2nPR9Q:b-p11etq) ([raw file](https://github.com/harness/harness-core/blob/d05968dfddcef0aee3b381759d3d1aca022102d7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L263)):*
> ```Java
>   private Optional<ServiceEntity> get(String accountId, String orgIdentifier, String projectIdentifier,
>       String serviceRef, boolean deleted, boolean loadFromCache, boolean loadFromFallbackBranch,
>       boolean includeMetadataOnly) {
> ```

better argument name could be "getMetadataOnly"

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52836)* status: Some of the checks are too old. 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/52836#-NeO7p4Z-eRJRmUvABxy:-NekykfF00bYCHqHpAys:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d05968dfddcef0aee3b381759d3d1aca022102d7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java#L47)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

should be "accountIdentifier"
</blockquote></details>

Done.

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52836)* status: Some of the checks are too old. 8 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52836)* status: Some of the checks are too old. 8 file(s) to review.

**Comment by hingerabhinav** [comment]
trigger review

**Pull request merged**
