### PR TITLE
feat: [CDS-39278]: remove NG_NATIVE_HELM FF

### PR DESCRIPTION
**Pull request by achyuth-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34772)

### CODE REVIEW

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34772)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34772)* status: :shipit: complete! ✓

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 266 at r1](https://reviewable.io/reviews/harness/harness-core/34772#-N5ejUkC-qyoO5RMF4JZ:-N5ejUkD9KXu9J1Q8fPZ:bwsfw31) ([raw file](https://github.com/harness/harness-core/blob/ebb15ee1dc82d9d2697519f18febd41e0af358cd/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L266)):*
> ```Java
>   OPTIMIZED_TF_PLAN,
>   SELF_SERVICE_ENABLED,
>   NG_NATIVE_HELM,
> ```

lets check on UI also

**Review by GoelPratyush99 — APPROVED** [review]

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34772)* status: 1. unresolved discussions. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 266 at r1](https://reviewable.io/reviews/harness/harness-core/34772#-N5ejUkC-qyoO5RMF4JZ:-N5i5rxF2H0X4gpzf6R8:b-9jfh3f) ([raw file](https://github.com/harness/harness-core/blob/ebb15ee1dc82d9d2697519f18febd41e0af358cd/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L266)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets check on UI also
</blockquote></details>

Confirmed with @bhavya-sinha, its been removed

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34772)* status: :shipit: complete! ✓

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Pull request merged**
