### PR TITLE
fix: [CDS-70550]: Fix Container Step V2 Pod Clean Up Logic and make resources field optional in Container Step Group Infra

### PR DESCRIPTION
**Pull request by sainath-b**
## Describe your changes
Issues to be fixed as a part of this bug.
1. Fix Container Step V2 Pod Clean Up Logic

2. Make resources field optional in Container Step Group Infra

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48444)

### CODE REVIEW

**Comment by sainath-b** [comment]
trigger uts

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48444)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by sainath-b** [comment]
trigger uts

**Comment by sainath-b** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48444)* status: 11 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/PodCleanupUpdateEventHandler.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/48444#-NWfClsS1vBc5gaG-gWk:-NWfClsS1vBc5gaG-gWl:b-24s1dc) ([raw file](https://github.com/harness/harness-core/blob/a6b0f79cac1c297a7affa61f9f6848ac31e5dd07/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/PodCleanupUpdateEventHandler.java#L24)):*
> ```Java
> @Singleton
> @OwnedBy(HarnessTeam.PIPELINE)
> public class PodCleanupUpdateEventHandler implements NodeStatusUpdateObserver {
> ```

Please make this AsyncInformObserver

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48444)* status: 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by rohitk-h — DISMISSED** [review]
> Reviewed 4 of 5 files at r1, 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48444)* status: Waiting on team(s): sto.

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 4 of 5 files at r1, 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48444)* status: Waiting on team(s): sto.

**Comment by sainath-b** [comment]
trigger uts

**Comment by sainath-b** [comment]
trigger uts

**Comment by sainath-b** [comment]
trigger uts

**Comment by sainath-b** [comment]
trigger codeformat

**Comment by sainath-b** [comment]
trigger messagecheck

**Comment by sainath-b** [comment]
trigger pmd

**Review by sainath-b — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 6 files at r2, 1 of 5 files at r4, 9 of 9 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48444)* status: 11 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/PodCleanupUpdateEventHandler.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/48444#-NWfClsS1vBc5gaG-gWk:-NWtUT7R14ZyjbhBJfAh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a6b0f79cac1c297a7affa61f9f6848ac31e5dd07/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/PodCleanupUpdateEventHandler.java#L24)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Please make this AsyncInformObserver
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r4, 9 of 9 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48444)* status: Some of the checks are too old. 11 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 5 files at r4, 9 of 9 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48444)* status: Some of the checks are too old. Waiting on team(s): sto.

**Comment by sainath-b** [comment]
trigger review

**Review by abhinav-harness — APPROVED** [review]

**Review by harshjain12 — APPROVED** [review]

**Pull request merged**
