### PR TITLE
[feat]: [PLG-1639]: added migration for all the accounts

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
added migration for all the accounts

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44854)

### CODE REVIEW

**Review by Xin-Harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44854)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/ForAllAccountsAddIsCrossGenerationAccessEnabledMigration.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/44854#-NPxkV5D43rnvltuTbQC:-NPxkV5D43rnvltuTbQD:b-gi12k3) ([raw file](https://github.com/harness/harness-core/blob/4ea6e900ece1bdfda35918890c3e21ba44232576/390-db-migration/src/main/java/io/harness/migrations/all/ForAllAccountsAddIsCrossGenerationAccessEnabledMigration.java#L23)):*
> ```Java
> import dev.morphia.query.UpdateOperations;
> import lombok.extern.slf4j.Slf4j;
> ```

One minor comment, need to add plg as owner

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44854)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/ForAllAccountsAddIsCrossGenerationAccessEnabledMigration.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/44854#-NPxkV5D43rnvltuTbQC:-NPxo7jzDBYOdnrbCpf1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4ea6e900ece1bdfda35918890c3e21ba44232576/390-db-migration/src/main/java/io/harness/migrations/all/ForAllAccountsAddIsCrossGenerationAccessEnabledMigration.java#L23)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

One minor comment, need to add plg as owner
</blockquote></details>

Done.

**Review by neelam-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44854#-:-NPxoGTt0_iGxOxUhtbo:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/ForAllAccountsAddIsCrossGenerationAccessEnabledMigration.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/44854#-NPxkV5D43rnvltuTbQC:-NPxo9712IbJi3Le7br8:b32v57) ([raw file](https://github.com/harness/harness-core/blob/4ea6e900ece1bdfda35918890c3e21ba44232576/390-db-migration/src/main/java/io/harness/migrations/all/ForAllAccountsAddIsCrossGenerationAccessEnabledMigration.java#L23)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

One minor comment, need to add plg as owner
</blockquote></details>

+1

**Review by neelam-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44854)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by thomas-grasman — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44854)* status: 1 change requests. 1. unresolved discussions.

**Review by thomas-grasman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44854)* status: 1 change requests. 1. unresolved discussions.

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44854)* status: :shipit: complete! ✓

**Pull request merged**
