### PR TITLE
Techdebt: [SRM-13114]: Refactoring create state machine

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40435)

### CODE REVIEW

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40435)* status: 10 file(s) to review. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/StateMachineFactory.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/40435#-NHSkWkh5yZYqYNDsjRl:-NHSkWkh5yZYqYNDsjRm:b-g1wpeg) ([raw file](https://github.com/harness/harness-core/blob/877cb1cbca19ffeda7e02016c3375a6b29f3e008/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/StateMachineFactory.java#L14)):*
> ```Java
> 
> public abstract class StateMachineFactory {
>   public abstract AnalysisStateMachine createStateMachine(AnalysisInput inputForAnalysis);
> ```

Why is this abstract? Since our factory is only going to be used for AnalysisStateMachine, we can have a single concrete impl for it, which will be responsible for providing the instances of the stateMachine depending on the analysisInput.

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40435)* status: 10 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/StateMachineFactory.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/40435#-NHSkWkh5yZYqYNDsjRl:-NHSobRp2FPfV_gMAtiC:bc2a4me) ([raw file](https://github.com/harness/harness-core/blob/877cb1cbca19ffeda7e02016c3375a6b29f3e008/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/StateMachineFactory.java#L14)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Why is this abstract? Since our factory is only going to be used for AnalysisStateMachine, we can have a single concrete impl for it, which will be responsible for providing the instances of the stateMachine depending on the analysisInput. 
</blockquote></details>

that would have if-else statements and if any new type is added, we would need to change in the existing method

**Review by dhruv-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40435)* status: 10 file(s) to review. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/StateMachineFactory.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/40435#-NHSkWkh5yZYqYNDsjRl:-NHSpiTt8ecxPFmPhZQj:b-ogw2dv) ([raw file](https://github.com/harness/harness-core/blob/877cb1cbca19ffeda7e02016c3375a6b29f3e008/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/StateMachineFactory.java#L14)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

that would have if-else statements and if any new type is added, we would need to change in the existing method
</blockquote></details>

When using Factory pattern, that is the way to go. We should refactor the class name if we do not intend to use it as a factory.

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40435)* status: 10 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/StateMachineFactory.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/40435#-NHSkWkh5yZYqYNDsjRl:-NHSqz_qC7EiO9QiqUBu:bm3z65d) ([raw file](https://github.com/harness/harness-core/blob/877cb1cbca19ffeda7e02016c3375a6b29f3e008/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/StateMachineFactory.java#L14)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

When using Factory pattern, that is the way to go. We should refactor the class name if we do not intend to use it as a factory.  
</blockquote></details>

AFAIK this is what abstract factory pattern is.

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40435)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/StateMachineFactory.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/40435#-NHSkWkh5yZYqYNDsjRl:-NHY8K5QAAfLWTIQL7ae:b3o5kl2) ([raw file](https://github.com/harness/harness-core/blob/877cb1cbca19ffeda7e02016c3375a6b29f3e008/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/StateMachineFactory.java#L14)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Abstract factory pattern is an extension to factory pattern where you use a factory provider to get the factory for a particular type which further will be used to give you the instance of the desired class. 
Lets discuss
</blockquote></details>

We can rename it to StateMachineService 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/CompositeSLOAnalysisStateMachine.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/40435#-NHY8oNV6QXtdNjEbTw3:-NHY8oNV6QXtdNjEbTw4:b-v137yz) ([raw file](https://github.com/harness/harness-core/blob/877cb1cbca19ffeda7e02016c3375a6b29f3e008/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/CompositeSLOAnalysisStateMachine.java#L32)):*
> ```Java
>   @Override
>   public AnalysisStateMachine createStateMachine(AnalysisInput inputForAnalysis) {
>     AnalysisStateMachine stateMachine = AnalysisStateMachine.builder()
> ```

Can move the instantiation, setting firstState, adding execution logs to a different method

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 10 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40435)* status: 1. unresolved discussions.

**Review by dhruv-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40435)* status: :shipit: complete! ✓

**Pull request merged**
