### PR TITLE
feat: [CDS-40277]: remove FF IGNORE_PCF_CONNECTION_CACHE

### PR DESCRIPTION
**Pull request by alebuh**
## Describe your changes
Removing this FF as it's not used by any customer and was added just as a safe point if something goes wrong with caching or some customer does not want to use it.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38274)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38274)

**Comment by alebuh** [comment]
trigger messagecheck

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 32 of 39 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38274)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/pcf/CfCommandRequest.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/38274#-NEAATNT5rona3YE7Fvi:-NEAATNU6UV9nJQzLZQd:b-7k69yi) ([raw file](https://github.com/harness/harness-core/blob/c1d48fd1c076fa333f32be4afd0aa4ca21f86703/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/pcf/CfCommandRequest.java#L38)):*
> ```Java
>   private boolean useAppAutoscalar;
>   private boolean limitPcfThreads;
>   private boolean ignorePcfConnectionContextCache;
> ```

is that backward compatible?
___
*[`960-api-services/src/main/java/io/harness/pcf/cfsdk/CloudFoundryOperationsWrapper.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/38274#-NEAC4AUBfQBMfMicQvN:-NEAC4AUBfQBMfMicQvO:bxfb74v) ([raw file](https://github.com/harness/harness-core/blob/c1d48fd1c076fa333f32be4afd0aa4ca21f86703/960-api-services/src/main/java/io/harness/pcf/cfsdk/CloudFoundryOperationsWrapper.java#L30)):*
> ```Java
>   @Override
>   public void close() {
>     if (ignorePcfConnectionContextCache && connectionContext != null) {
> ```

why do we remove this?

**Review by alebuh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38274)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/pcf/CfCommandRequest.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/38274#-NEAATNT5rona3YE7Fvi:-NEAKJTB2j4dn6QXVwPf:bjbo7xx) ([raw file](https://github.com/harness/harness-core/blob/c1d48fd1c076fa333f32be4afd0aa4ca21f86703/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/pcf/CfCommandRequest.java#L38)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

is that backward compatible?
</blockquote></details>

My assumption is that it is because it's a boolean. I suppose that when the delegate receives this request it won't process this field, and by default, it will be false. Do you know maybe what is the best way to test this if we are not sure?
___
*[`960-api-services/src/main/java/io/harness/pcf/cfsdk/CloudFoundryOperationsWrapper.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/38274#-NEAC4AUBfQBMfMicQvN:-NEALbqK2JDfazCegQJz:b-wzk4l8) ([raw file](https://github.com/harness/harness-core/blob/c1d48fd1c076fa333f32be4afd0aa4ca21f86703/960-api-services/src/main/java/io/harness/pcf/cfsdk/CloudFoundryOperationsWrapper.java#L30)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

why do we remove this?
</blockquote></details>

As ignorePcfConnectionContextCache was false for all customers, this part of the code was never called. I could leave the empty close() method but didn't see the point in it

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38274)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/pcf/CfCommandRequest.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/38274#-NEAATNT5rona3YE7Fvi:-NEASPTw9L68bxmTGDDk:bnpz61s) ([raw file](https://github.com/harness/harness-core/blob/c1d48fd1c076fa333f32be4afd0aa4ca21f86703/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/pcf/CfCommandRequest.java#L38)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

My assumption is that it is because it's a boolean. I suppose that when the delegate receives this request it won't process this field, and by default, it will be false. Do you know maybe what is the best way to test this if we are not sure?
</blockquote></details>

could you please test with an older delegate version?

**Comment by alebuh** [comment]
trigger feature-build

**Comment by alebuh** [comment]
trigger feature-build

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38274)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/pcf/cfsdk/CloudFoundryOperationsWrapper.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/38274#-NEAC4AUBfQBMfMicQvN:-NEeeA2HBPybeeojyaXh:bv9lg5o) ([raw file](https://github.com/harness/harness-core/blob/c1d48fd1c076fa333f32be4afd0aa4ca21f86703/960-api-services/src/main/java/io/harness/pcf/cfsdk/CloudFoundryOperationsWrapper.java#L30)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

As ignorePcfConnectionContextCache was false for all customers, this part of the code was never called. I could leave the empty close() method but didn't see the point in it
</blockquote></details>

my concern is that after adding check for ignorePcfConnectionContextCache condition was  "if (connectionContext != null)"

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38274)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/pcf/cfsdk/CloudFoundryOperationsWrapper.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/38274#-NEAC4AUBfQBMfMicQvN:-NEeekrh93ZVLCy713eN:b-1ahzb4) ([raw file](https://github.com/harness/harness-core/blob/c1d48fd1c076fa333f32be4afd0aa4ca21f86703/960-api-services/src/main/java/io/harness/pcf/cfsdk/CloudFoundryOperationsWrapper.java#L30)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

my concern is that after adding check for ignorePcfConnectionContextCache condition was  "if (connectionContext != null)"
</blockquote></details>

*before adding check for ignorePcfConnectionContextCache

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 2 of 39 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38274)* status: :shipit: complete! ✓

**Comment by alebuh** [comment]
@ivan-83 @anilchowdhury-harness could you please review this as well?
@tmacari-harness gave approval with concern so he advised that you guys take a look as well.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 35 of 39 files at r1, 2 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38274)* status: :shipit: complete! ✓

___
*[`960-api-services/src/main/java/io/harness/pcf/cfsdk/CloudFoundryOperationsWrapper.java` line 30 at r4](https://reviewable.io/reviews/harness/harness-core/38274#-NEr5hCpDuHPDMSZKKU3:-NEr5hCpDuHPDMSZKKU4:bgkwovi) ([raw file](https://github.com/harness/harness-core/blob/967d68fd41eeeee6ba39d52bbe857000af02a4e6/960-api-services/src/main/java/io/harness/pcf/cfsdk/CloudFoundryOperationsWrapper.java#L30)):*
> ```Java
>   @Override
>   public void close() {
>     if (ignorePcfConnectionContextCache && connectionContext != null) {
> ```

@alebuh what was the default value for ignorePcfConnectionContextCache true or false? 
___
*[`960-api-services/src/main/java/io/harness/pcf/cfsdk/ConnectionContextProvider.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/38274#-NEr66850tetFftMgpsf:-NEr66850tetFftMgpsg:b-fwocyk) ([raw file](https://github.com/harness/harness-core/blob/967d68fd41eeeee6ba39d52bbe857000af02a4e6/960-api-services/src/main/java/io/harness/pcf/cfsdk/ConnectionContextProvider.java#L79)):*
> ```Java
>   public ConnectionContext getConnectionContext(CfRequestConfig pcfRequestConfig) throws PivotalClientApiException {
>     try {
>       if (pcfRequestConfig.isIgnorePcfConnectionContextCache()) {
> ```

The same question as above?

**Review by alebuh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38274)* status: 1 change requests. 2. unresolved discussions. 

___
*[`960-api-services/src/main/java/io/harness/pcf/cfsdk/CloudFoundryOperationsWrapper.java` line 30 at r4](https://reviewable.io/reviews/harness/harness-core/38274#-NEr5hCpDuHPDMSZKKU3:-NEtIJTF4cKp5J7bs7j_:b-r7ennv) ([raw file](https://github.com/harness/harness-core/blob/967d68fd41eeeee6ba39d52bbe857000af02a4e6/960-api-services/src/main/java/io/harness/pcf/cfsdk/CloudFoundryOperationsWrapper.java#L30)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

@alebuh what was the default value for ignorePcfConnectionContextCache true or false? 
</blockquote></details>

It was false. This FF was never activated for any customer, it was placed there just as a safe point. As it was never enabled, it was always false.
___
*[`960-api-services/src/main/java/io/harness/pcf/cfsdk/ConnectionContextProvider.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/38274#-NEr66850tetFftMgpsf:-NEtIiBE33mFvXbHdcV9:bocdjnd) ([raw file](https://github.com/harness/harness-core/blob/967d68fd41eeeee6ba39d52bbe857000af02a4e6/960-api-services/src/main/java/io/harness/pcf/cfsdk/ConnectionContextProvider.java#L79)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The same question as above? 
</blockquote></details>

It was always false

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38274#-:-NEtQu4aEnQadr-VxLPr:bnfp4nl)* status: :shipit: complete! ✓

**Comment by alebuh** [comment]
trigger codebasehash

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 36 of 39 files at r1, 2 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38274)* status: Some of the checks are too old.

**Pull request merged**
