### PR TITLE
fix: [CDS-85928]: Execution is stuck on waiting

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Describe your changes

Issue: Using matrix at stage level and matrix at step group level, roll back steps are not triggered.

Reason: The uuid being used in RollbackExecutableUtility was fetching uuid was fetching uuid from last strategy level. For rollback steps, we need stage level uuid, hence it was not working.

Image after the fix.
Screenshot 2023-12-08 at 12 12 33 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56529)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java` line 95 at r1](https://reviewable.io/reviews/harness/harness-core/56529#-Nl7Cji7-vUtG5AouV8K:-Nl7Cji87j3o5l0W6ecY:bdx4g7p) ([raw file](https://github.com/harness/harness-core/blob/3524993d6b49f4f13559015b5885c4e8ba4f983c/884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java#L95)):*
> ```Java
>   }
> 
>   public String getStrategySetupIdAmbiance(Ambiance ambiance) {
> ```

Can we rename this? something like getFirstStrategySetupIdFromAmbiance or getStageStrategySetupIdFromAmbiance?

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`884-pms-commons/src/test/java/io/harness/pms/execution/utils/AmbianceUtilsTest.java` line 342 at r2](https://reviewable.io/reviews/harness/harness-core/56529#-Nl7L30I9yDYK3UrM7i4:-Nl7L30I9yDYK3UrM7i5:bed7kcy) ([raw file](https://github.com/harness/harness-core/blob/4169e1e8837664166b9f916b8175cf97a31574ab/884-pms-commons/src/test/java/io/harness/pms/execution/utils/AmbianceUtilsTest.java#L342)):*
> ```Java
>   public void testGetStrategySetupIdAmbiance() {
>     Ambiance ambiance = buildAmbianceUsingStrategyMetadata();
>     String strategySetupId = AmbianceUtils.getFirstLevelStrategySetupIdAmbiance(ambiance);
> ```

Please add testcase for this issue.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56529)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by prashantsharma04** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56529)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by prashantsharma04** [comment]
trigger ut7

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56529)* status: <span>:shipit:</span> complete! ✓

**Comment by prashantsharma04** [comment]
trigger review

**Pull request merged**
