### PR TITLE
fix: [PL-24091]: change the upsert query for GitFileLocation

### PR DESCRIPTION
**Pull request by bhavya181**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31770)

### CODE REVIEW

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31770)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 223 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz0vQ8s6WGsiZTxz0YC:-Mz0vQ8tAOz9KZ_lB9bq:b73npy6) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L223)):*
> ```Java
>       String folderPath, String filePath, String commitId, String branchName) {
>     String completeFilePath = GitSyncFilePathUtils.createFilePath(folderPath, filePath);
>     String completeFilePathWithoutStartingSlash = completeFilePath.substring(1);
> ```

add null check for completefilePath
___
*[136-git-sync-manager/src/main/java/io/harness/repositories/gitFileLocation/GitFileLocationRepositoryCustomImpl.java, line 136 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz0vjVh33dY_sOAVslj:-Mz0vjVh33dY_sOAVslk:b-a1kpbc) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/repositories/gitFileLocation/GitFileLocationRepositoryCustomImpl.java#L136)):*
> ```Java
>   @Override
>   public GitFileLocation find(Criteria criteria) {
>     return mongoTemplate.findOne(query(criteria), GitFileLocation.class);
> ```

Is there a chance that we may have multiple records in DB for this criteria ?

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 223 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz0vQ8s6WGsiZTxz0YC:-Mz1FGpM7f048fzUzPOz:b4cptml) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L223)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

add null check for completefilePath
</blockquote></details>

It can't be null.



_Code quote:_
```Java
GitSyncFilePathUtils
```

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 223 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1FL7T3tf4ZJsH4hO7:-Mz1FL7UDlCxSxgVodFt:blaux1y) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L223)):*
> ```Java
>       String folderPath, String filePath, String commitId, String branchName) {
>     String completeFilePath = GitSyncFilePathUtils.createFilePath(folderPath, filePath);
>     String completeFilePathWithoutStartingSlash = completeFilePath.substring(1);
> ```

Please create generic utility method for such things.

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31770)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 264 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1HPjd1q3OU9ylca0F:-Mz1HPjd1q3OU9ylca0G:b-tsjjv2) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L264)):*
> ```Java
>     gitFileLocationRepository.save(fileLocation);
>     if (gitFileLocation != null) {
>       log.info("Updated Git Entity having repo [{}], branch [{}] and completeFilePath [{}]", yamlGitConfig.getRepo(),
> ```

we can simply log complete entity right?

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/repositories/gitFileLocation/GitFileLocationRepositoryCustomImpl.java, line 135 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1HZjm6gwnv2W1BIK_:-Mz1HZjm6gwnv2W1BIKa:b-cjfzrl) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/repositories/gitFileLocation/GitFileLocationRepositoryCustomImpl.java#L135)):*
> ```Java
> 
>   @Override
>   public GitFileLocation find(Criteria criteria) {
> ```

If inside its findOne(), then main method call name also should be findOne()

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 223 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1FL7T3tf4ZJsH4hO7:-Mz1MetKEndIzXCcNHW8:b-evz0sr) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L223)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

name should be something like "getFilePathWithoutStartingSlash"

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 264 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1HPjd1q3OU9ylca0F:-Mz1Mkzx-ce6E9mHADys:b-q566rv) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L264)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

post pushInfo already log complete entity details.
</blockquote></details>

Its fine, lets not rely on somewhere else to log the entity. We can log it here as well.

**Comment by mohitg0795** [comment]
___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 77 at r2](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1NW3O55aVMJwuzxoQ:-Mz1NW3PAibCmOj1SXxu:b8nt111) ([raw file](https://github.com/harness/harness-core/blob/e83c88596fabc5c3bd47f10d1ec4ab3ff8c12d93/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L77)):*
> ```Java
>   public static String giveFilePathWithoutSlash(String path) {
>     if (isEmpty(path)) {
>       throw new InvalidRequestException("CompleteFilePath cannot be null");
> ```

Input is only path, not completeFilePath.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31770)* status: 7 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 223 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1FL7T3tf4ZJsH4hO7:-Mz1PGwnC_Ra-GbX7azP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L223)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

name should be something like "getFilePathWithoutStartingSlash"
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 264 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1HPjd1q3OU9ylca0F:-Mz1PHjJ1oZe14B5TJrm:b-x6bswy) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L264)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Its fine, lets not rely on somewhere else to log the entity. We can log it here as well.
</blockquote></details>

there is no point of logging unnecessary fields, this entity has lot of fields, what's the point of showing them.
___
*[136-git-sync-manager/src/main/java/io/harness/repositories/gitFileLocation/GitFileLocationRepositoryCustomImpl.java, line 136 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz0vjVh33dY_sOAVslj:-Mz1PW00523nUuqh5HOK:b-yvb49s) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/repositories/gitFileLocation/GitFileLocationRepositoryCustomImpl.java#L136)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think lets be a little cautious here. Lets put a try catch over this call and throw a wings exception with proper message if there are 2 entities existing.
@bhavya181 way to reproduce would be to put 2 entities in DB with same path, or path with and without forward slash and see what exception are we getting here. We shouldn't let the issue like last time happen where the query logic went into UI.
</blockquote></details>

It uses findOne, if duplicateEntries would present , it will return one entry, you can check findOne method of mongo
___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 77 at r2](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1NW3O55aVMJwuzxoQ:-Mz1Pjmp9u1LTi3ABGLp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e83c88596fabc5c3bd47f10d1ec4ab3ff8c12d93/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L77)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Input is only path, not completeFilePath.
</blockquote></details>

Done.
___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 79 at r2](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1N_lG2f7kWAZb_eup:-Mz1PkdV6wcUqvN_3clR:b-drbct) ([raw file](https://github.com/harness/harness-core/blob/e83c88596fabc5c3bd47f10d1ec4ab3ff8c12d93/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L79)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

logic is wrongly written. Its a generic method thats taking a path. So you should check if its starting with slash or not and return accordingly.
Also, make it generic in the sense that if it has multiple forward slashes, then it should remove all.
</blockquote></details>

I will take multiple forward slash remove on another pr.

**Comment by mohitg0795** [comment]
___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 77 at r2](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1NW3O55aVMJwuzxoQ:-Mz1RAFAEbBB2n6f7pgc:b1srdt) ([raw file](https://github.com/harness/harness-core/blob/e83c88596fabc5c3bd47f10d1ec4ab3ff8c12d93/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L77)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can we correct the error message here. It should be "file path cannot be empty", not null. Sorry to point this out, but we should start being a little particular about such small things as well.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31770)* status: 7 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 264 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1HPjd1q3OU9ylca0F:-Mz1SofrAMBwc7wlPubO:bd57i9r) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L264)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can you point me where its logging the entity? Also, if you're logging something elsewhere in a particular flow, doesn't mean it will be logged in all flows that use this particular method, correct? So, thats why its always best to log things at the right place necessarily. If you want to log things at other layers as well, its a call that you make as use-case owner but that shouldn't override the necessary logs.
</blockquote></details>

This save method is call only once from PostPushInfo, there we are logging whole entity, for now, I have added all unique fields in log.
___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 77 at r2](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1NW3O55aVMJwuzxoQ:-Mz1ShW76j-cnOpNRuIe:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e83c88596fabc5c3bd47f10d1ec4ab3ff8c12d93/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L77)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can we correct the error message here. It should be "file path cannot be empty", not null. Sorry to point this out, but we should start being a little particular about such small things as well.
</blockquote></details>

done
___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 75 at r3](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1SA6t9leNGjLmTcaP:-Mz1SiwS2Xm2BFu9Us1q:bxrla4l) ([raw file](https://github.com/harness/harness-core/blob/ca5732f863a389777b8df35dc217058705243626/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L75)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please add UT for this method as well
</blockquote></details>

yes, I will add it in another pr

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 264 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1HPjd1q3OU9ylca0F:-Mz1UlDiCuWm7zXeaLZe:buju7ap) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L264)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

This save method is call only once from PostPushInfo, there we are logging whole entity, for now, I have added all unique fields in log.
</blockquote></details>

Ok, Probably, you're not getting the point here. We can go ahead with it now, not a concern.

**Comment by mohitg0795** [comment]
___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 75 at r3](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1SA6t9leNGjLmTcaP:-Mz1V-Kh1oIYmteilzjN:b-fo6o4k) ([raw file](https://github.com/harness/harness-core/blob/ca5732f863a389777b8df35dc217058705243626/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L75)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

yes, I will add it in another pr
</blockquote></details>

can you create the JIRA for it and share it here.

**Comment by mohitg0795** [comment]
___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 77 at r2](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1NW3O55aVMJwuzxoQ:-Mz1V4Th39BPYtsV63z8:b-wy9vhb) ([raw file](https://github.com/harness/harness-core/blob/e83c88596fabc5c3bd47f10d1ec4ab3ff8c12d93/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L77)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

done
</blockquote></details>

I don't see changes here? Did we update the message to "file path cannot be empty"?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31770)* status: 7 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 77 at r2](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1NW3O55aVMJwuzxoQ:-Mz1VjZC2NGFkXzRjVak:blc2uw8) ([raw file](https://github.com/harness/harness-core/blob/e83c88596fabc5c3bd47f10d1ec4ab3ff8c12d93/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L77)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I don't see changes here? Did we update the message to "file path cannot be empty"?
</blockquote></details>

yes, it's updated
___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 75 at r3](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1SA6t9leNGjLmTcaP:-Mz1VcJp8el_SMzau5Vw:bsruups) ([raw file](https://github.com/harness/harness-core/blob/ca5732f863a389777b8df35dc217058705243626/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L75)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can you create the JIRA for it and share it here.
</blockquote></details>

I will create a one more pr under same ticket

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 224 at r5](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1Vrit30Fcfr9EkHkx:-Mz1VriuEdlZPspw2AZx:beukwm8) ([raw file](https://github.com/harness/harness-core/blob/89a2842170c58db526c3968c647367134f8581b9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L224)):*
> ```Java
>     String completeFilePath = GitSyncFilePathUtils.createFilePath(folderPath, filePath);
>     Optional<GitFileLocation> gitFileLocation =
>         gitFileLocationRepository.findByAccountIdAndCompleteGitPathAndRepoAndBranch(
> ```

Lets add complete scope here in fetch query as mentioned by Akash.

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 230 at r5](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1Vxb37RuotAZrQ0_p:-Mz1Vxb37RuotAZrQ0_q:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/89a2842170c58db526c3968c647367134f8581b9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L230)):*
> ```Java
>       String completeFilePathWithoutStartingSlash =
>           GitSyncFilePathUtils.getFilePathWithoutStartingSlash(completeFilePath);
>       gitFileLocation = gitFileLocationRepository.findByAccountIdAndCompleteGitPathAndRepoAndBranch(
> ```

same

**Comment by mohitg0795** [comment]
___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 75 at r3](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1SA6t9leNGjLmTcaP:-Mz1WBfSCDbcF2o0fOY1:ba4t37x) ([raw file](https://github.com/harness/harness-core/blob/ca5732f863a389777b8df35dc217058705243626/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L75)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

I will create a one more pr under same ticket
</blockquote></details>

We shouldn't create PRs under same ticket. Please create a separate JIRA for it if it will be taken up separately.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31770)* status: 7 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 75 at r3](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1SA6t9leNGjLmTcaP:-Mz1Ym2M4yRSNMi3Aq_7:blyd2be) ([raw file](https://github.com/harness/harness-core/blob/ca5732f863a389777b8df35dc217058705243626/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L75)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We shouldn't create PRs under same ticket. Please create a separate JIRA for it if it will be taken up separately.
</blockquote></details>

https://harness.atlassian.net/browse/PL-24095

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31770)* status: 7 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 224 at r5](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1Vrit30Fcfr9EkHkx:-Mz1ar_G6owDiMR2Jg2D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/89a2842170c58db526c3968c647367134f8581b9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L224)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets add complete scope here in fetch query as mentioned by Akash.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 230 at r5](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1Vxb37RuotAZrQ0_p:-Mz1apIO9NDb-p0g3hr5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/89a2842170c58db526c3968c647367134f8581b9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L230)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r1, 2 of 4 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31770#-:-Mz1b94C24690oUiAo6X:bnfp4nl)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 223 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz0vQ8s6WGsiZTxz0YC:-Mz1bWoP1V0n6yZouHWo:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L223)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

done

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/repositories/gitFileLocation/GitFileLocationRepositoryCustomImpl.java, line 136 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz0vjVh33dY_sOAVslj:-Mz1bYmpET0m1qyGr-G6:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/repositories/gitFileLocation/GitFileLocationRepositoryCustomImpl.java#L136)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

It uses findOne, if duplicateEntries would present , it will return one entry, you can check findOne method of mongo
</blockquote></details>

done

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31770#-:-Mz1ba5bDFRPwukyT5RF:bnfp4nl)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31770)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 223 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz0vQ8s6WGsiZTxz0YC:-Mz1cSgcDqf1ui-mITg5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L223)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

done
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/repositories/gitFileLocation/GitFileLocationRepositoryCustomImpl.java, line 136 at r1](https://reviewable.io/reviews/harness/harness-core/31770#-Mz0vjVh33dY_sOAVslj:-Mz1cV3ICzO6ZrW0jcE0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f8f64c910bdcc5ee8192e0b2e5e1b92f169b4378/136-git-sync-manager/src/main/java/io/harness/repositories/gitFileLocation/GitFileLocationRepositoryCustomImpl.java#L136)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

done
</blockquote></details>

Done.

**Review by abhinav-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31770)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 231 at r7](https://reviewable.io/reviews/harness/harness-core/31770#-Mz1hnjr6PqzH9OCUYRJ:-Mz1hnjr6PqzH9OCUYRK:b-pb9bf2) ([raw file](https://github.com/harness/harness-core/blob/e7bcac736291ca42cbf8653f6234995756fedf42/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L231)):*
> ```Java
>           GitSyncFilePathUtils.getFilePathWithoutStartingSlash(completeFilePath);
>       gitFileLocation =
>           gitFileLocationRepository.findByAccountIdAndOrganizationIdAndProjectIdAndCompleteGitPathAndRepoAndBranch(
> ```

index?

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 2 of 4 files at r2, 1 of 2 files at r4, 1 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31770)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31770#-:-Mz1idV02smZ7wcCrpQp:bnfp4nl)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31770#-:-Mz1irpe40fV1suvvWjx:bnfp4nl)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31770#-:-Mz1j90bCZsyf_HOHuCv:bnfp4nl)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 1 of 2 files at r4, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31770)* status: :shipit: complete! ✓

**Pull request merged**
