### PR TITLE
feat: [DEL-5873]: generate java module size report

### PR DESCRIPTION
**Pull request by mdmilic**
## Describe your changes
There is a new bazel rule called [brannock](https://en.wikipedia.org/wiki/Brannock_Device) (alternative name was [nonius](https://en.wikipedia.org/wiki/Nonius_(device))) that generates the size report of any list of deps. There are two reports generated
* `size_report.txt` - report of all “leaf deps” - sorted, no dupes report of all transitive deps and their sizes
* `size_report.txt.deps`  - report of direct deps and their total sizes

### How it works:
The rule defines an [aspect](https://bazel.build/extending/aspects) on the deps attribute (meaning the aspect implementation gets executed for every transitive dep once). It also defines mandatory output file which will contain report.

1. Aspect will (for each dep), generate a one line file containing the size of the dep in bytes and the target
2. The list of all those files will be propagated using `OutputGroupInfo` provider which defines a new output_group "size"
3. The rule will take the list of the size files, enhance and concatenate them generating final reports

### How to run 
Rule can be used standalone, but if flag REPORT_SIZE is enabled & if build.bazel file uses harness custom java_binary or java_library (`load("//:tools/bazel/harness.bzl", "java_library")` instead of `load("rules_java//java:defs.bzl", "java_library")`) there will be automatic target created named the same as existing java_library/java_binary suffixed with sizer.
NOTE: When invoking brannock rules, you need to request the output_group named "size"
 
```bazel build //931-vault-beans/src/java/io/harness/helpers/vault:module_sizer --output_groups=size```

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43169)

### CODE REVIEW

**Comment by mdmilic** [comment]
trigger smartchecks

**Review by gn-harness — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43169)* status: Some of the checks are too old.

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43169)* status: :shipit: complete! ✓

**Pull request merged**
