### PR TITLE
feat: [CI-3315]: onboard CI Steps to new Yaml Schema

### PR DESCRIPTION
**Pull request by harshjain12**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/29993)

### CODE REVIEW

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 19 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29993)* status: Some of the checks are too old. 18 file(s) to review. 0 of 1 approvals obtained.

**Comment by brijeshdhakar** [comment]
___
*[330-ci-beans/src/main/java/io/harness/beans/steps/nodes/BuildAndPushDockerNode.java, line 35 at r1](https://reviewable.io/reviews/harness/harness-core/29993#-MtvcO49ADX6APQL59WD:-MtvcO49ADX6APQL59WE:begf2ac) ([raw file](https://github.com/harness/harness-core/blob/c204546d81997d91c46fe61e8bc0b7f0dcee4727/330-ci-beans/src/main/java/io/harness/beans/steps/nodes/BuildAndPushDockerNode.java#L35)):*
> ```Java
>   @JsonProperty("type")
>   @NotNull
>   BuildAndPushDockerNode.StepType type = BuildAndPushDockerNode.StepType.BuildAndPushDockerRegistry;
> ```

We can remove this extra `BuildAndPushDockerNode.` before StepType. The enum is in the same class so it can access without it.
Same for other step node classes.

**Comment by brijeshdhakar** [comment]
___
*[330-ci-beans/src/main/java/io/harness/beans/steps/nodes/GCSUploadNode.java, line 28 at r1](https://reviewable.io/reviews/harness/harness-core/29993#-MtvdIT2247a4_25yN-P:-MtvdIT2247a4_25yN-Q:b60ow0r) ([raw file](https://github.com/harness/harness-core/blob/c204546d81997d91c46fe61e8bc0b7f0dcee4727/330-ci-beans/src/main/java/io/harness/beans/steps/nodes/GCSUploadNode.java#L28)):*
> ```Java
> @NoArgsConstructor
> @EqualsAndHashCode(callSuper = true)
> @JsonTypeName("GCSUpload")
> ```

Can we use the constants here instead of the string? like: CIStepInfoType.UPLOAD_GCS
The same change in all step node classes.

**Comment by brijeshdhakar** [comment]
___
*[970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/entity_type.proto, line 55 at r1](https://reviewable.io/reviews/harness/harness-core/29993#-Mtvsse86t4RBXShGgLh:-Mtvsse86t4RBXShGgLi:b-aw8br1) ([raw file](https://github.com/harness/harness-core/blob/c204546d81997d91c46fe61e8bc0b7f0dcee4727/970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/entity_type.proto#L55)):*
> ```protobuf
>   BUILD_AND_PUSH_ECR = 40;
>   BUILD_AND_PUSH_DOCKER_REGISTRY = 41;
>   SERVICENOW_APPROVAL = 42;
> ```

Why this ServiceNow_approval?

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 1 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29993)* status: Some of the checks are too old. 17 file(s) to review. 0 of 1 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 12 of 37 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29993)* status: :shipit: complete! ✓

**Comment by harshjain12** [comment]
FM PR because test is failing because of some issue in develop branch

**Pull request merged**
