### PR TITLE
fix: [PL-39507]: Modified 2FA to not clear authMech and TOTP

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49813)

### CODE REVIEW

**Review by pbarapatre10 — APPROVED** [review]
Please add PR description. Also ensure it doesn't break the flow of sending 2FA email notification/QR code with/without FFs `AUTO_ACCEPT_SAML_ACCOUNT_INVITES` and `PL_NO_EMAIL_FOR_SAML_ACCOUNT_INVITES` 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49813#-:-NZPNVIDCoUizsHfVo_F:bctbavc)* status: Some of the checks are too old. 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 2726 at r1](https://reviewable.io/reviews/harness/harness-core/49813#-NZPOoh33wvvI4Gk-r8_:-NZPOoh33wvvI4Gk-r8a:bli65vw) ([raw file](https://github.com/harness/harness-core/blob/55a1874047cf9a623aa5bcf8a7cf2eeae197782b/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L2726)):*
> ```Java
>     TwoFactorAuthenticationSettings twoFactorAuthenticationSettings =
>         totpAuthHandler.createTwoFactorAuthenticationSettings(user, account);
>     //    twoFactorAuthenticationSettings.setTwoFactorAuthenticationEnabled(true);
> ```

nit: please remove commented code, thanks



_Code quote:_
```Java
//    twoFactorAuthenticationSettings.setTwoFactorAuthenticationEnabled(true);
```

**Comment by VikasMaddukuriHarness** [comment]
trigger uts

**Comment by VikasMaddukuriHarness** [comment]
trigger ut8

**Comment by VikasMaddukuriHarness** [comment]
trigger uts

**Comment by VikasMaddukuriHarness** [comment]
trigger ut0

**Review by pbarapatre10 — APPROVED** [review]
Please update the PR description and also testing status with/without the SAML flags, thanks

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49813#-:-NZaD7k40d8ovrmav0Do:b-wws7yy)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
