### PR TITLE
techdebt: [PL-29835] Fix the cycles in persistence mongo index folder

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

This PR fixes the below cycles in 960-persistence module -

[Cycle - 1]

.-> //960-persistence/src/main/java/io/harness/mongo/index:module
|   //960-persistence/src/main/java/io/harness/mongo:module
|   //960-persistence/src/main/java/io/harness/queue:module
`-- //960-persistence/src/main/java/io/harness/mongo/index:module 

[Cycle - 2]

.-> //960-persistence/src/main/java/io/harness/mongo/index:module 
|   //960-persistence/src/main/java/io/harness/persistence:module 
|   //960-persistence/src/main/java/io/harness/mongo:module 
|   //960-persistence/src/main/java/io/harness/queue:module 
`-- //960-persistence/src/main/java/io/harness/mongo/index:module 

Tested this PR locally for below scenario -
1. End to End K8s Cloud provider connector validation.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42025)

### CODE REVIEW

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 55 of 55 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42025)* status: 55 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by gn-harness — APPROVED** [review]
> Reviewed 55 of 55 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42025)* status: Waiting on team(s): sto.

**Comment by Raghav-Murali** [comment]
trigger ft1, feature-build

**Review by gn-harness — APPROVED** [review]
> Reviewed 36 of 36 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42025)* status: 36 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by archit-harness — APPROVED** [review]
> Reviewed 19 of 55 files at r1, 36 of 36 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42025)* status: Waiting on team(s): sto.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 19 of 55 files at r1, 36 of 36 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42025#-:-NL-BopU18xxRXCioiyx:bnfp4nl)* status: Waiting on team(s): sto.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 19 of 55 files at r1, 36 of 36 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42025)* status: Waiting on team(s): sto.

**Review by inderschera — APPROVED** [review]
> Reviewed 19 of 55 files at r1, 36 of 36 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42025)* status: Waiting on team(s): sto.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 19 of 55 files at r1, 36 of 36 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42025)* status: Waiting on team(s): sto.

**Review by puthrayaharness — APPROVED** [review]

**Pull request merged**
