### PR TITLE
feat: [PL-29722]: Feature flag for enabling collapse and expand side nav

### PR DESCRIPTION
**Pull request by avinashmadhwani02**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42925)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42925)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 589 at r2](https://reviewable.io/reviews/harness/harness-core/42925#-NMXDza1DxBXdGbQv1Be:-NMXDza1DxBXdGbQv1Bf:b-g3fcjn) ([raw file](https://github.com/harness/harness-core/blob/b795d2934846f201582e6e53901c6d3498769277/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L589)):*
> ```Java
>   PL_USER_DELETION_V2("Modularising user deletion flows separately for CG and NG ", HarnessTeam.PL),
>   DISABLE_INSTANCE_STATS_JOB_CG("Disable Instance Stats Job from CG", HarnessTeam.CDP),
>   ENABLE_SIDENAV_COLLAPSE("FF for enabling collapse and expand of side nav", HarnessTeam.PL),
> ```

Follow the guideline for name a FF: https://harness.atlassian.net/wiki/spaces/SPG/pages/21183823964/Feature+Flag+Guidelines

**Review by pbarapatre10 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42925#-:-NMXHbne5x52XU91my-G:bnfp4nl)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by nishantsaini20 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42925)* status: 1 change requests. 1 of 2 approvals obtained.

**Review by avinashmadhwani02 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42925)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 589 at r2](https://reviewable.io/reviews/harness/harness-core/42925#-NMXDza1DxBXdGbQv1Be:-NMXRNP91BNPO4uEllXa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b795d2934846f201582e6e53901c6d3498769277/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L589)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Follow the guideline for name a FF: https://harness.atlassian.net/wiki/spaces/SPG/pages/21183823964/Feature+Flag+Guidelines
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42925)* status: :shipit: complete! ✓

**Pull request merged**
