### PR TITLE
[feat]: [CVS-9415]: added logs for SLO

### PR DESCRIPTION
**Pull request by kapil-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31374)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger messagecheck

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31374)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/cvnglogs/ApiCallLogRecord.java, line 129 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-Mxrxnxu7eVueCWSOp3T:-MxrxnxwERnui8cTIPvg:bwxo8om) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/cvnglogs/ApiCallLogRecord.java#L129)):*
> ```Java
>   public boolean isErrorLog() {
>     for (ApiCallLogField response : responses) {
>       if (isNumeric(response.getValue())) {
> ```

you should look for the name instead of doing isNumeric. 
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/CVNGLogService.java, line 34 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-Mxry8pNEPfiG-dCZmmL:-Mxry8pO5Srhpf-oKtc0:bstcpku) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/CVNGLogService.java#L34)):*
> ```Java
>       List<String> healthSourceIdentifiers, boolean errorLogsOnly, PageParams pageParams);
>   PageResponse<CVNGLogDTO> getCVNGLogs(String accountId, List<String> verificationTaskIds, CVNGLogType logType,
>       Instant startTime, Instant endTime, boolean errorLogsOnly, PageParams pageParams);
> ```

please create a filter params for this. This same api should be used for live monitoring, SLI and eventually we should refactor verify step to also use this api.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java, line 175 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-MxryYLaEU8gSebw55dm:-MxryYLaEU8gSebw55dn:bbidp2d) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java#L175)):*
> ```Java
>   public PageResponse<CVNGLogDTO> getCVNGLogs(String accountId, List<String> verificationTaskIds, CVNGLogType logType,
>       Instant startTime, Instant endTime, boolean errorLogsOnly, PageParams pageParams) {
>     List<CVNGLog> cvngLogs = getCVNGLogs(accountId, verificationTaskIds, logType, startTime, endTime);
> ```

we should have a validation on duration (Difference between startTime and endTime) so that we are not querying large ranges. We can keep that to 1 day for now. 
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java, line 198 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-MxryzHg6Xgex4LdJ7pg:-MxryzHg6Xgex4LdJ7ph:b-4m0q76) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java#L198)):*
> ```Java
>         .field(CVNGLogKeys.traceableId)
>         .in(verificationTaskIds)
>         .field(CVNGLogKeys.startTime)
> ```

what if time range is in between the time ranges for CVNGLog? I think we should include the the half matching time also.
        .field(CVNGLogKeys.startTime)
        .greaterThanOrEq(startTime)
        .field(CVNGLogKeys.startTime)
        .lessThanOrEq(endTime)
        .asList();

Please write proper tests covering the time range cases.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveResource.java, line 181 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-Mxs0O8iBfk1NSykotzR:-Mxs0O8j-NvpSD3PZVIh:b-18ovqv) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveResource.java#L181)):*
> ```Java
>       @ApiParam(required = true) @NotNull @QueryParam("startTime") long startTime,
>       @ApiParam(required = true) @NotNull @QueryParam("endTime") long endTime,
>       @QueryParam("errorLogsOnly") @ApiParam(defaultValue = "false") boolean errorLogsOnly,
> ```

please write a object with BeanParams
You can follow same pattern as io.harness.cvng.core.beans.params.filterParams.AnalysisFilter
We will have to create a common class and subclasses for all 3 usecases.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java, line 257 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-Mxs0skV8-FHaMwmKMQs:-Mxs0skWDkqZDT025LOW:b-wux2gz) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L257)):*
> ```Java
>       Instant startTime, Instant endTime, boolean errorLogsOnly, PageParams pageParams) {
>     ServiceLevelObjective serviceLevelObjective = getEntity(projectParams, identifier);
>     if (Objects.isNull(serviceLevelObjective)) {
> ```

we should throw error in this case. Not empty response. Because if slo identifier does not exist the api should fail with not found exception. Please make sure we are returning 400 in this case.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java, line 266 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-Mxs1C7v8b7BoVXvyeuC:-Mxs1C7v8b7BoVXvyeuD:b-s40q0r) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L266)):*
> ```Java
> 
>     serviceLevelIndicatorEntities.forEach(serviceLevelIndicatorEntity
>         -> verificationTaskIds.add(verificationTaskService.getSLIVerificationTaskId(
> ```

please write a bulk api in verificationTaskService to get the list (verificationTaskService.getSLIVerificationTaskIds)
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/ServiceLevelObjectiveServiceImplTest.java, line 762 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-Mxs1XRt5AM5H6pAMAJR:-Mxs1XRt5AM5H6pAMAJS:b-uoih8m) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/ServiceLevelObjectiveServiceImplTest.java#L762)):*
> ```Java
>     PageResponse<CVNGLogDTO> cvngLogDTOResponse =
>         serviceLevelObjectiveService.getCVNGLogs(projectParams, sloDTO.getIdentifier(), CVNGLogType.API_CALL_LOG,
>             Instant.now(), Instant.now(), false, PageParams.builder().page(0).size(10).build());
> ```

we should always use clock instead of Instant.now()
The idea is that the test should have fixed input and fixed out so that there is no chance of having a flaky test. Also this is a convention that we follow across the codebase.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31374)* status: 12 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/cvnglogs/ApiCallLogRecord.java, line 129 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-Mxrxnxu7eVueCWSOp3T:-MxuK8iPENexzgSKjkMz:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/cvnglogs/ApiCallLogRecord.java#L129)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

you should look for the name instead of doing isNumeric. 
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/CVNGLogService.java, line 34 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-Mxry8pNEPfiG-dCZmmL:-MxuKAAW3UqLCfeXeXG_:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/CVNGLogService.java#L34)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

please create a filter params for this. This same api should be used for live monitoring, SLI and eventually we should refactor verify step to also use this api.
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java, line 175 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-MxryYLaEU8gSebw55dm:-MxuKBXY7Hqva2H-vlcz:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java#L175)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

we should have a validation on duration (Difference between startTime and endTime) so that we are not querying large ranges. We can keep that to 1 day for now. 
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java, line 198 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-MxryzHg6Xgex4LdJ7pg:-MxuKCe88zDXI39G35GA:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java#L198)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

what if time range is in between the time ranges for CVNGLog? I think we should include the the half matching time also.
        .field(CVNGLogKeys.startTime)
        .greaterThanOrEq(startTime)
        .field(CVNGLogKeys.startTime)
        .lessThanOrEq(endTime)
        .asList();

Please write proper tests covering the time range cases.

</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveResource.java, line 181 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-Mxs0O8iBfk1NSykotzR:-MxuKE72DlU_I52dnYmP:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveResource.java#L181)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

please write a object with BeanParams
You can follow same pattern as io.harness.cvng.core.beans.params.filterParams.AnalysisFilter
We will have to create a common class and subclasses for all 3 usecases.
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java, line 257 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-Mxs0skV8-FHaMwmKMQs:-MxuKFcpCUMWjnja2z0u:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L257)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

we should throw error in this case. Not empty response. Because if slo identifier does not exist the api should fail with not found exception. Please make sure we are returning 400 in this case.
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java, line 266 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-Mxs1C7v8b7BoVXvyeuC:-MxuKGLIC87LAldfLIQC:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L266)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

please write a bulk api in verificationTaskService to get the list (verificationTaskService.getSLIVerificationTaskIds)
</blockquote></details>

done
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/ServiceLevelObjectiveServiceImplTest.java, line 762 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-Mxs1XRt5AM5H6pAMAJR:-MxuKHxF03o-nECObFf6:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/ServiceLevelObjectiveServiceImplTest.java#L762)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

we should always use clock instead of Instant.now()
The idea is that the test should have fixed input and fixed out so that there is no chance of having a flaky test. Also this is a convention that we follow across the codebase.
</blockquote></details>

done

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31374#-:-MxwJ2Bn957zjfuiG8il:bnfp4nl)* status: 2. unresolved discussions. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java, line 257 at r2](https://reviewable.io/reviews/harness/harness-core/31374#-Mxs0skV8-FHaMwmKMQs:-MxwIdPF1yR7e34WThp7:bxjqq0l) ([raw file](https://github.com/harness/harness-core/blob/8c04236cb72c1e3e2fefdad6e344023db08338be/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L257)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

done
</blockquote></details>

nit: please write a resource layer test for this. You can do this along with other resource layer tests.

**Review by kjoshi12345 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31374)* status: :shipit: complete! ✓

**Pull request merged**
