### PR TITLE
feat: [PIE-3591]: Schema change for matrix

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34101)

### CODE REVIEW

**Review by naidu-harness — DISMISSED** [review]
:lgtm:

> Reviewed 14 of 20 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34101#-:-N4BWqiU35hf-THhuQN7:bnfp4nl)* status: 24 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 14 of 20 files at r1, 8 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34101)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`870-orchestration/src/main/java/io/harness/concurrency/MaxConcurrentChildCallback.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/34101#-N4C2ImG1DhHmQ4hGz43:-N4C2ImG1DhHmQ4hGz44:b4pl2jh) ([raw file](https://github.com/harness/harness-core/blob/fd05deeaf15b036cdca27515283c81d88d4a5e71/870-orchestration/src/main/java/io/harness/concurrency/MaxConcurrentChildCallback.java#L82)):*
> ```Java
>                                                                 .maxConcurrency(maxConcurrency)
>                                                                 .build();
>     waitNotifyEngine.waitForAllOn(publisherName, maxConcurrentChildCallback, nodeExecution.getUuid());
> ```

is it because we are adding in create initiate mode?



_Code quote:_
```Java
    MaxConcurrentChildCallback maxConcurrentChildCallback = MaxConcurrentChildCallback.builder()
                                                                .parentNodeExecutionId(parentNodeExecutionId)
                                                                .ambiance(ambiance)
                                                                .maxConcurrency(maxConcurrency)
                                                                .build();
    waitNotifyEngine.waitForAllOn(publisherName, maxConcurrentChildCallback, nodeExecution.getUuid());
```
___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/stages/GenericStagePlanCreator.java` line 136 at r2](https://reviewable.io/reviews/harness/harness-core/34101#-N4C1poZAeqxLZ9qN0vS:-N4C1poZAeqxLZ9qN0vT:b4flusb) ([raw file](https://github.com/harness/harness-core/blob/99c54cec886371088fad25cc253cf1f9af066e11/878-ng-common-utilities/src/main/java/io/harness/plancreator/stages/GenericStagePlanCreator.java#L136)):*
> ```Java
>                                 .build())
>               .build());
>     }
> ```

add your stage strategy changes to AbstractStagePlanCreator this as well, because there is an ongoing effort to go away from stagelementConfig and StepElementConfig, so we don't want to put data here, for now, you should add this change in both plan creator.



_Code quote:_
```Java
  /**
   * Adds a strategy node as a dependency of the stage if present.
   * Please note that strategy uses uuid of the stage node because the stage is using the uuid of strategy field as we
   * want to wrap stage around strategy.
   *
   * @param ctx
   * @param field
   * @param dependenciesNodeMap
   * @param metadataMap
   */
  protected void addStrategyFieldDependencyIfPresent(PlanCreationContext ctx, StageElementConfig field,
      LinkedHashMap<String, PlanCreationResponse> planCreationResponseMap, Map<String, ByteString> metadataMap) {
    YamlField strategyField = ctx.getCurrentField().getNode().getField(YAMLFieldNameConstants.STRATEGY);
    if (strategyField != null) {
      // This is mandatory because it is the parent's responsibility to pass the nodeId and the childNodeId to the
      // strategy node
      metadataMap.put(StrategyConstants.STRATEGY_METADATA + strategyField.getNode().getUuid(),
          ByteString.copyFrom(
              kryoSerializer.asDeflatedBytes(StrategyMetadata.builder()
                                                 .strategyNodeId(field.getUuid())
                                                 .adviserObtainments(StageStrategyUtils.getAdviserObtainments(
                                                     ctx.getCurrentField(), kryoSerializer, false))
                                                 .childNodeId(strategyField.getNode().getUuid())
                                                 .build())));
      planCreationResponseMap.put(field.getUuid(),
          PlanCreationResponse.builder()
              .dependencies(DependenciesUtils.toDependenciesProto(ImmutableMap.of(field.getUuid(), strategyField))
                                .toBuilder()
                                .putDependencyMetadata(
                                    field.getUuid(), Dependency.newBuilder().putAllMetadata(metadataMap).build())
                                .build())
              .build());
    }
```

**Comment by sahilhindwani-harness** [comment]
*[`870-orchestration/src/main/java/io/harness/concurrency/MaxConcurrentChildCallback.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/34101#-N4C2ImG1DhHmQ4hGz43:-N4CRqIM9lM3yAlCH_5A:bb77ueg) ([raw file](https://github.com/harness/harness-core/blob/fd05deeaf15b036cdca27515283c81d88d4a5e71/870-orchestration/src/main/java/io/harness/concurrency/MaxConcurrentChildCallback.java#L82)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

is it because we are adding in create initiate mode?
</blockquote></details>

Yes

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/stages/GenericStagePlanCreator.java` line 136 at r2](https://reviewable.io/reviews/harness/harness-core/34101#-N4C1poZAeqxLZ9qN0vS:-N4CRscvBcSQEN10LkiS:b-gdye1x) ([raw file](https://github.com/harness/harness-core/blob/99c54cec886371088fad25cc253cf1f9af066e11/878-ng-common-utilities/src/main/java/io/harness/plancreator/stages/GenericStagePlanCreator.java#L136)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add your stage strategy changes to AbstractStagePlanCreator this as well, because there is an ongoing effort to go away from stagelementConfig and StepElementConfig, so we don't want to put data here, for now, you should add this change in both plan creator.
</blockquote></details>

The changes were already added there but since Ci uses this, we added here too.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 10 files at r2, 10 of 10 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34101)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 10 of 20 files at r1, 5 of 10 files at r2, 5 of 10 files at r3, 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34101)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 6 of 20 files at r1, 3 of 10 files at r2, 5 of 10 files at r3, 2 of 5 files at r4, 1 of 1 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34101)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 10 files at r2, 2 of 10 files at r3, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34101)* status: :shipit: complete! ✓

**Pull request merged**
