### PR TITLE
feat: [PL-29878]: added API to get paginated list of user's accounts

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
added API to get paginated list of user's accounts

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41366)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41366)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 552 at r2](https://reviewable.io/reviews/harness/harness-core/41366#-NIqU9m5A_EeaeAUspwX:-NIqU9m5A_EeaeAUspwY:bbwm5bk) ([raw file](https://github.com/harness/harness-core/blob/16a2a200151f2e91c971c57be771997802b204f5/400-rest/src/main/java/software/wings/resources/UserResource.java#L552)):*
> ```Java
>   @ExceptionMetered
>   @AuthRule(permissionType = LOGGED_IN)
>   public RestResponse<io.harness.ng.beans.PageResponse<Account>> getUserAccounts(
> ```

Can we reuse this API instead of a new API?
___
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 572 at r2](https://reviewable.io/reviews/harness/harness-core/41366#-NIqUYR53yXF5RGOQnuy:-NIqUYR53yXF5RGOQnuz:b-d3je51) ([raw file](https://github.com/harness/harness-core/blob/16a2a200151f2e91c971c57be771997802b204f5/400-rest/src/main/java/software/wings/resources/UserResource.java#L572)):*
> ```Java
>     List<Account> accounts =
>         userService.getUserAccounts(UserThreadLocal.get().getUuid(), pageIndex, pageSize, searchTerm);
>     long totalUserAccounts = userService.getTotalUserAccounts(UserThreadLocal.get().getUuid(), searchTerm);
> ```

Do we need to return totalAccounts in case of infinite scrolling?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41366)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 552 at r2](https://reviewable.io/reviews/harness/harness-core/41366#-NIqU9m5A_EeaeAUspwX:-NIr4pE-1IzctciY_uWq:bswp8l3) ([raw file](https://github.com/harness/harness-core/blob/16a2a200151f2e91c971c57be771997802b204f5/400-rest/src/main/java/software/wings/resources/UserResource.java#L552)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we reuse this API instead of a new API?
</blockquote></details>

this is not used anywhere, removed it
___
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 572 at r2](https://reviewable.io/reviews/harness/harness-core/41366#-NIqUYR53yXF5RGOQnuy:-NIr4wXq4HNMHBhl6jY4:b-1ss587) ([raw file](https://github.com/harness/harness-core/blob/16a2a200151f2e91c971c57be771997802b204f5/400-rest/src/main/java/software/wings/resources/UserResource.java#L572)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Do we need to return totalAccounts in case of infinite scrolling?
</blockquote></details>

whatever be the UI, Api should give correct response right?

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41366)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 572 at r2](https://reviewable.io/reviews/harness/harness-core/41366#-NIqUYR53yXF5RGOQnuy:-NJ4T2i79nIGLTTok9Tf:bcds06n) ([raw file](https://github.com/harness/harness-core/blob/16a2a200151f2e91c971c57be771997802b204f5/400-rest/src/main/java/software/wings/resources/UserResource.java#L572)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

whatever be the UI, Api should give correct response right?
</blockquote></details>

Not necessarily. We can chuck it it's costly. API contract can very well be "totalPages will be available on best effort basis".
In this case, I think its an unnecessary overhead
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 544 at r3](https://reviewable.io/reviews/harness/harness-core/41366#-NJ4TVhZ3MT5enoF2Xv0:-NJ4TVhZ3MT5enoF2Xv1:b-lkj0dy) ([raw file](https://github.com/harness/harness-core/blob/93cd9005237f6d40ca3af3e46ea292f1d67a592d/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L544)):*
> ```Java
> 
>   @Override
>   public long getTotalUserAccounts(String userId, String searchTerm) {
> ```

We can remove this method.

**Review by pbarapatre10 — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 7 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41366#-:-NJF1_cjDfDhRyv2EJo6:bnfp4nl)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41366)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 572 at r2](https://reviewable.io/reviews/harness/harness-core/41366#-NIqUYR53yXF5RGOQnuy:-NJJn3FL03F-PcWc5kbr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16a2a200151f2e91c971c57be771997802b204f5/400-rest/src/main/java/software/wings/resources/UserResource.java#L572)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Not necessarily. We can chuck it it's costly. API contract can very well be "totalPages will be available on best effort basis".
In this case, I think its an unnecessary overhead
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 544 at r3](https://reviewable.io/reviews/harness/harness-core/41366#-NJ4TVhZ3MT5enoF2Xv0:-NJJn4I0DqovWz3peUkW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/93cd9005237f6d40ca3af3e46ea292f1d67a592d/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L544)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We can remove this method.
</blockquote></details>

Done.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41366#-:-NJKSu1_BYKCEvQSPn49:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
