### PR TITLE
feat: [CDS-45551]: adding terragrunt plan step

### PR DESCRIPTION
**Pull request by vlica-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41249)

### CODE REVIEW

**Comment by vlica-harness** [comment]
trigger smartchecks

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41249)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntStepHelper.java` line 331 at r3](https://reviewable.io/reviews/harness/harness-core/41249#-NIqM2el7bXOvsqo4iw8:-NIqM2el7bXOvsqo4iw9:bd02ud7) ([raw file](https://github.com/harness/harness-core/blob/34cd95211bb6bb6a8d0abc95e5eb2d4484e0f52d/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntStepHelper.java#L331)):*
> ```Java
>   }
> 
>   public List<StoreDelegateConfig> toTerragruntVarFileInfo(
> ```

It returns a list of StoreDelegateConfigs, we can give it a more better name

**Review by vlica-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41249)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntStepHelper.java` line 331 at r3](https://reviewable.io/reviews/harness/harness-core/41249#-NIqM2el7bXOvsqo4iw8:-NIqtnCYBLccdW1tyc7l:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/34cd95211bb6bb6a8d0abc95e5eb2d4484e0f52d/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntStepHelper.java#L331)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

It returns a list of StoreDelegateConfigs, we can give it a more better name 
</blockquote></details>

done

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41249)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by alebuh — APPROVED** [review]
> Reviewed 4 of 8 files at r2, 1 of 2 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41249)* status: :shipit: complete! ✓

**Pull request merged**
