### PR TITLE
feat: [CDS-85485]: Divide sdk response events among multiple redis st…

### PR DESCRIPTION
**Pull request by Y0709**
…reams

As per issues found in load test on prod [https://harness.atlassian.net/browse/CDS-86430](https://harness.atlassian.net/browse/CDS-86430) we have decided to reduce the no events in pipeline_sdk_response stream and decided to move a few events to new streams. More details for the same are in this ticket [https://harness.atlassian.net/browse/CDS-85485](https://harness.atlassian.net/browse/CDS-85485) . We have 2 new redis streams with same specs as the original stream 

1) pipeline_sdk_spawn - for SPAWN_CHILD and SPAWN_CHILDREN events
2) pipeline_sdk_step_response - for HANDLE_STEP_RESPONSE and QUEUE_TASK events

For testing 
Tested via a cd execution that has all 4 events sent from ng manager to pipeline svc and all events are processed properly without any issues

Please not that this change is behind a FF and we will push events in new stream only after enabling the FF

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56969)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger commonchecks

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceConsumersConfig.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/56969#-Nm4d4FQ5-mSmjBizsVX:-Nm4d4FQ5-mSmjBizsVY:blerimf) ([raw file](https://github.com/harness/harness-core/blob/16a40deeb1abebd8fc1048d3c283cf5275e59604/pipeline-service/service/src/main/java/io/harness/PipelineServiceConsumersConfig.java#L43)):*
> ```Java
>   PipelineServiceConsumerConfig triggerExecutionEvent;
>   PipelineServiceConsumerConfig asyncFilterCreationEvent;
>   PipelineServiceConsumerConfig sdkResponseSpawn;
> ```

nit: can we rename this better?

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/SdkResponseSpawnEventPublisher.java` line 12 at r1](https://reviewable.io/reviews/harness/harness-core/56969#-Nm4fsA15MkP6NwsfxTB:-Nm4fsA15MkP6NwsfxTC:b-55m7lo) ([raw file](https://github.com/harness/harness-core/blob/16a40deeb1abebd8fc1048d3c283cf5275e59604/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/SdkResponseSpawnEventPublisher.java#L12)):*
> ```Java
> import io.harness.pms.contracts.execution.events.SdkResponseEventProto;
> 
> public interface SdkResponseSpawnEventPublisher {
> ```

Can we create one SdkResponseEventPublisher and create functions for different streams?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56969)* status: 26 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 21 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56969)* status: 5 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/RedisSdkResponseSpawnEventPublisher.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/56969#-Nm4fz9X55OmLECRPNDB:-Nm4fz9X55OmLECRPNDC:b-tm8ogp) ([raw file](https://github.com/harness/harness-core/blob/16a40deeb1abebd8fc1048d3c283cf5275e59604/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/RedisSdkResponseSpawnEventPublisher.java#L25)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> public class RedisSdkResponseSpawnEventPublisher implements SdkResponseSpawnEventPublisher {
> ```

can we create one abstract impl as almost all code is same across different streams thus producer is different
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/RedisSdkStepResponseEventPublisher.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/56969#-Nm4g4Uq2zR-rRPDzI1K:-Nm4g4Uq2zR-rRPDzI1L:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/16a40deeb1abebd8fc1048d3c283cf5275e59604/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/RedisSdkStepResponseEventPublisher.java#L26)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public class RedisSdkStepResponseEventPublisher implements SdkStepResponseEventPublisher {
>   private Producer eventProducer;
> ```

same as above
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/SdkResponseSpawnEventPublisher.java` line 12 at r1](https://reviewable.io/reviews/harness/harness-core/56969#-Nm4fsA15MkP6NwsfxTB:-Nm4gA4v4gbjlOxJ2CbV:b32v57) ([raw file](https://github.com/harness/harness-core/blob/16a40deeb1abebd8fc1048d3c283cf5275e59604/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/SdkResponseSpawnEventPublisher.java#L12)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we create one SdkResponseEventPublisher and create functions for different streams?
</blockquote></details>

+1
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/SdkStepResponseEventPublisher.java` line 12 at r1](https://reviewable.io/reviews/harness/harness-core/56969#-Nm4gGVY65gbZcMndKb8:-Nm4gGVY65gbZcMndKb9:bku9t6o) ([raw file](https://github.com/harness/harness-core/blob/16a40deeb1abebd8fc1048d3c283cf5275e59604/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/SdkStepResponseEventPublisher.java#L12)):*
> ```Java
> import io.harness.pms.contracts.execution.events.SdkResponseEventProto;
> 
> public interface SdkStepResponseEventPublisher {
> ```

dont we have this interface already?
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/execution/consumers/SdkStepResponseEventRedisConsumer.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/56969#-Nm4gXZ95yOL8kiRPN5F:-Nm4gXZ95yOL8kiRPN5G:b-3i8pu9) ([raw file](https://github.com/harness/harness-core/blob/16a40deeb1abebd8fc1048d3c283cf5275e59604/pipeline-service/modules/orchestration/src/main/java/io/harness/execution/consumers/SdkStepResponseEventRedisConsumer.java#L8)):*
> ```Java
>  */
> 
> package io.harness.execution.consumers;
> ```

can you move all consumer of sdk response under a folder of sdk_response and same for above

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56969)* status: 21 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/RedisSdkResponseSpawnEventPublisher.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/56969#-Nm4fz9X55OmLECRPNDB:-Nm5Dx9W0TMajRGkCSWC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16a40deeb1abebd8fc1048d3c283cf5275e59604/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/RedisSdkResponseSpawnEventPublisher.java#L25)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we create one abstract impl as almost all code is same across different streams thus producer is different
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/RedisSdkStepResponseEventPublisher.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/56969#-Nm4g4Uq2zR-rRPDzI1K:-Nm5DxWJ5aqXJh7AUB0i:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16a40deeb1abebd8fc1048d3c283cf5275e59604/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/RedisSdkStepResponseEventPublisher.java#L26)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/SdkResponseSpawnEventPublisher.java` line 12 at r1](https://reviewable.io/reviews/harness/harness-core/56969#-Nm4fsA15MkP6NwsfxTB:-Nm5DxzrDWlGFrX7d4Ce:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16a40deeb1abebd8fc1048d3c283cf5275e59604/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/SdkResponseSpawnEventPublisher.java#L12)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/SdkStepResponseEventPublisher.java` line 12 at r1](https://reviewable.io/reviews/harness/harness-core/56969#-Nm4gGVY65gbZcMndKb8:-Nm5Dzb41wx1lgsRo3Sp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16a40deeb1abebd8fc1048d3c283cf5275e59604/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/SdkStepResponseEventPublisher.java#L12)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dont we have this interface already?
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/execution/consumers/SdkStepResponseEventRedisConsumer.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/56969#-Nm4gXZ95yOL8kiRPN5F:-Nm5DreyDG7TI5nyJmdf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16a40deeb1abebd8fc1048d3c283cf5275e59604/pipeline-service/modules/orchestration/src/main/java/io/harness/execution/consumers/SdkStepResponseEventRedisConsumer.java#L8)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you move all consumer of sdk response under a folder of sdk_response and same for above
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56969)* status: 21 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/RedisSdkResponseEventPublisher.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/56969#-Nm5F1lM9E9Ds7mq1_jE:-Nm5F1lM9E9Ds7mq1_jF:b-81yq1p) ([raw file](https://github.com/harness/harness-core/blob/d5f3c6b9bed365756056101210d8160d1c9f5393/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/RedisSdkResponseEventPublisher.java#L43)):*
> ```Java
> 
>   @Override
>   public void publishEvent(SdkResponseEventProto event) {
> ```

can you have only one method, and based on types use different producer

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56969)* status: 22 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/RedisSdkResponseEventPublisher.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/56969#-Nm5F1lM9E9Ds7mq1_jE:-Nm7d9ndBJRJ7fDoCSjG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d5f3c6b9bed365756056101210d8160d1c9f5393/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/response/publishers/RedisSdkResponseEventPublisher.java#L43)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you have only one method, and based on types use different producer
</blockquote></details>

Done.

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger ut4

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 10 files at r2, 11 of 11 files at r3, 1 of 1 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56969)* status: 22 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 5 of 10 files at r2, 11 of 11 files at r3, 1 of 1 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56969)* status: <span>:shipit:</span> complete! ✓

**Comment by Y0709** [comment]
trigger review

**Pull request merged**
