### PR TITLE
fix:[CDS-46223]: added schema validation for duplicate stepTemplateRefs

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
Added schema validation to prevent duplicate stepTemplateRefs in Deployment template in NG
Tests performed:
- Tried adding duplicate steps in a deployment template to see if it fails
- Added Junit for the same

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40277)

### CODE REVIEW

**Comment by RishabhGupta34** [comment]
trigger messagecheck

**Review by anilchowdhury-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40277)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/customDeployment/helper/CustomDeploymentYamlHelper.java` line 365 at r2](https://reviewable.io/reviews/harness/harness-core/40277#-NH49GU-3lI7d36ZqqZX:-NH49GU-3lI7d36ZqqZY:b-jo15wg) ([raw file](https://github.com/harness/harness-core/blob/8483364a4e0cc3da1914c47b90558cdee2ca383a/120-ng-manager/src/main/java/io/harness/ng/core/customDeployment/helper/CustomDeploymentYamlHelper.java#L365)):*
> ```Java
>     if (YamlUtils.checkIfNodeIsArrayWithPrimitiveTypes(yamlNode.getCurrJsonNode())) {
>       if (!path.empty() && path.lastElement().equals(STEP_TEMPLATE_REFS)) {
>         Map<String, Boolean> checkForDuplicateSteps = new HashMap<>();
> ```

Lets use Set to identify duplicate node

**Comment by RishabhGupta34** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/customDeployment/helper/CustomDeploymentYamlHelper.java` line 365 at r2](https://reviewable.io/reviews/harness/harness-core/40277#-NH49GU-3lI7d36ZqqZX:-NH4Td2W8Gc269kVja4o:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8483364a4e0cc3da1914c47b90558cdee2ca383a/120-ng-manager/src/main/java/io/harness/ng/core/customDeployment/helper/CustomDeploymentYamlHelper.java#L365)):*
<details><summary><i>Previously, anilchowdhury-harness (Anil Chowdhury) wrote…</i></summary><blockquote>

Lets use Set to identify duplicate node
</blockquote></details>

Done.

**Review by anilchowdhury-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40277)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/customDeployment/helper/CustomDeploymentYamlHelper.java` line 370 at r3](https://reviewable.io/reviews/harness/harness-core/40277#-NH4VmRb3e4i3DvK1hKb:-NH4VmRb3e4i3DvK1hKc:bb9zrx) ([raw file](https://github.com/harness/harness-core/blob/1e620287936237ae22ebc8d647cdbdd5595fd635/120-ng-manager/src/main/java/io/harness/ng/core/customDeployment/helper/CustomDeploymentYamlHelper.java#L370)):*
> ```Java
>         for (YamlNode arrayElement : yamlNode.asArray()) {
>           if (checkForDuplicateSteps.contains(arrayElement.asText())) {
>             throw new InvalidRequestException("Duplicate stepTemplateRefs linked with the template");
> ```

Can we also print the name of the duplicate step in this error message. This way it will be easier for user to identify which step to remove if there are many steps linked in it

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40277#-:-NH89k307yW5ftfwG0nC:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
