### PR TITLE
fix: [PL-23642]: add accountIdentifier to isDomainPrefixAvailable in delegate-mtls resources

### PR DESCRIPTION
**Pull request by johannesHarness**
Based on our internal openAPI specifications every operation has to run in a context of an account.
This PR is adding the accountId/accountIdentifier parameter to the isDomainPrefixAvailable method of all delegate-mtls related resources.

The delegate-mtls API isn't used by customers yet, the feature is still in development.
Therefore, this API change won't break customers or requires portal changes.

OAS:
https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/1928757422/Open+Api+Spec+3+onboarding

## Testing
- Executed REST API locally against both CG and NG manager and verified API call works with accountId, and fails without accountId.
- Verified that both swagger and openapi.json contain the new parameter.

---
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32658)

### CODE REVIEW

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32658)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32658)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by Vbhatia20 — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32658)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32658)* status: :shipit: complete! ✓

**Pull request merged**
