### PR TITLE
feat: [CDS-48517]: Delegate changes: K8s & Native Helm (CG - Direct Kubernetes Cluster) Instance sync V2 implementation New Approach

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Describe your changes
Delegate Side changes for K8s & Native Helm (CG - Direct Kubernetes Cluster) Instance sync V2 implementation

## Checklist
- No documentation require
- I've tested this change either in PR or local environment.
- All these changes are behind FF so Backward compatible

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41479)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java` line 96 at r2](https://reviewable.io/reviews/harness/harness-core/41479#-NJjWgz35V8h_xmbheyN:-NJjWgz35V8h_xmbheyO:b-ppntao) ([raw file](https://github.com/harness/harness-core/blob/80ff4f0b93e4d71c998268e012abd94f5527c8ab/260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java#L96)):*
> ```Java
>                   : ((K8sInstanceSyncResponse) ((K8sTaskExecutionResponse) taskResponseData).getK8sTaskResponse())
>                         .getK8sPodInfoList()
>                         .size())
> ```

Extract into a different function



_Code quote:_
```Java
          .setInstanceCount(instanceSyncTaskDetails.getIsHelm()
                  ? ((ContainerSyncResponse) taskResponseData).getContainerInfoList().size()
                  : ((K8sInstanceSyncResponse) ((K8sTaskExecutionResponse) taskResponseData).getK8sTaskResponse())
                        .getK8sPodInfoList()
                        .size())
```

**Comment by sahilhindwani-harness** [comment]
*[`260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/41479#-NJjWmGT7h8SWJ0HA_bD:-NJjWmGT7h8SWJ0HA_bE:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/80ff4f0b93e4d71c998268e012abd94f5527c8ab/260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java#L99)):*
> ```Java
>           .setExecutionStatus(instanceSyncTaskDetails.getIsHelm()
>                   ? ((ContainerSyncResponse) taskResponseData).getCommandExecutionStatus().name()
>                   : ((K8sTaskExecutionResponse) taskResponseData).getCommandExecutionStatus().name())
> ```

same as above



_Code quote:_
```Java
          .setExecutionStatus(instanceSyncTaskDetails.getIsHelm()
                  ? ((ContainerSyncResponse) taskResponseData).getCommandExecutionStatus().name()
                  : ((K8sTaskExecutionResponse) taskResponseData).getCommandExecutionStatus().name())
```

**Comment by sahilhindwani-harness** [comment]
*[`260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java` line 174 at r2](https://reviewable.io/reviews/harness/harness-core/41479#-NJjWt8d865IXMYOP59v:-NJjWt8d865IXMYOP59w:b-dbo3y5) ([raw file](https://github.com/harness/harness-core/blob/80ff4f0b93e4d71c998268e012abd94f5527c8ab/260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java#L174)):*
> ```Java
>     List<ContainerInfo> result = new ArrayList<>();
>     try {
>       if (k8sInstanceSyncTaskDetails.getIsHelm()) {
> ```

nit: Add comments as to what we are doing here and also split the functions as we discussed on call.

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Comment by namantalaycha10** [comment]
trigger checkstylecodeformat

**Comment by namantalaycha10** [comment]
trigger ti1

**Comment by sahilhindwani-harness** [comment]
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 225 at r5](https://reviewable.io/reviews/harness/harness-core/41479#-NJyXx8E7RLKdhmMbsmy:-NJyXx8E7RLKdhmMbsmz:b7xs67d) ([raw file](https://github.com/harness/harness-core/blob/a6a5fd3d6560e50cca21cd088e6728b63cc4c1de/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L225)):*
> ```Java
>                   .parallelStream()
>                   .map(instance -> kryoSerializer.asObject(instance.toByteArray()))
>                   .collect(Collectors.toList()));
> ```

nit: delete if will not be used in future.

**Comment by sahilhindwani-harness** [comment]
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 246 at r5](https://reviewable.io/reviews/harness/harness-core/41479#-NJyXzy32lbd_wG3Bis9:-NJyXzy32lbd_wG3BisA:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/a6a5fd3d6560e50cca21cd088e6728b63cc4c1de/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L246)):*
> ```Java
>       }
> 
>       /*      instancesPerTask.get(instanceSyncData.getTaskDetailsId())
> ```

same as above

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41479)* status: 9 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java` line 96 at r2](https://reviewable.io/reviews/harness/harness-core/41479#-NJjWgz35V8h_xmbheyN:-NJym_I_EEu6pMr1kSJq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/80ff4f0b93e4d71c998268e012abd94f5527c8ab/260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java#L96)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Extract into a different function
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/41479#-NJjWmGT7h8SWJ0HA_bD:-NJyma2K63WeHIRb6AbE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/80ff4f0b93e4d71c998268e012abd94f5527c8ab/260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java#L99)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 225 at r5](https://reviewable.io/reviews/harness/harness-core/41479#-NJyXx8E7RLKdhmMbsmy:-NJymfTIDaMWSFlj9lZZ:bmsu2i8) ([raw file](https://github.com/harness/harness-core/blob/a6a5fd3d6560e50cca21cd088e6728b63cc4c1de/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L225)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: delete if will not be used in future.
</blockquote></details>

this I will delete in manager changes
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 246 at r5](https://reviewable.io/reviews/harness/harness-core/41479#-NJyXzy32lbd_wG3Bis9:-NJymjlr0SoqsGgeVdxB:b3xqbp8) ([raw file](https://github.com/harness/harness-core/blob/a6a5fd3d6560e50cca21cd088e6728b63cc4c1de/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L246)):*
> this I will delete in manager changes

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 5 of 7 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41479)* status: Some of the checks are too old. 9 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 1 of 5 files at r2, 5 of 7 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41479)* status: Some of the checks are too old.

**Comment by namantalaycha10** [comment]
trigger ft2

**Comment by namantalaycha10** [comment]
trigger ft1

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41479)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by mdmilic — APPROVED** [review]
@namantalaycha10 being behind a FF doesn't mean it's backwards compatible. It means it's compatible while the FF is off. It needs to be compatible even when you turn on the FF or even if you remove the FF in a few months. Delegate lifecycle is different than manager and customers can run old version of delegate for months. 
Since the API is proto in this case, you need to make sure that your delegate/manager can handle null values for all the fields you added and the ones you removed. For removed field, even currently existing delegate must be able to handle nulls. Manager must be able to handle old response type from older delegates that are running older version of this task.

> Reviewed 1 of 5 files at r2, 5 of 7 files at r3, 1 of 2 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41479#-:-NKP-imd7RhVpTCG3f2Q:bovfzj2)* status: :shipit: complete! ✓

**Pull request merged**
