### PR TITLE
[techdebt]: [PIE-4376]: Reduce the number of deserialisations during input set merge

### PR DESCRIPTION
**Pull request by namanvermah**
Expose methods that return YamlConfig instead of String, so that the repeated serialisations and deserialisations are avoided in `ExecutionHelper`. 
Tested this manually on a pipeline with 12 approval stages, the time taken goes down to about 20-22ms from 36-38ms.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35292)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35292)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 249 at r1](https://reviewable.io/reviews/harness/harness-core/35292#-N6qKXEE6-rLGiuv5Y0d:-N6qKXEE6-rLGiuv5Y0e:b-mwmjgl) ([raw file](https://github.com/harness/harness-core/blob/03ca6133b67161586bdfdd46c7bb8ff3f8734b37/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L249)):*
> ```Java
>       YamlConfig runtimeInputYamlConfig = new YamlConfig(mergedRuntimeInputYaml);
>       YamlConfig templateYamlConfig =
>           RuntimeInputFormHelper.createRuntimeInputFormYamlConfig(pipelineEntityYamlConfig, true);
> ```

why do we need this now?



_Code quote:_
```Java
      YamlConfig templateYamlConfig =
          RuntimeInputFormHelper.createRuntimeInputFormYamlConfig(pipelineEntityYamlConfig, true);
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35292)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 249 at r1](https://reviewable.io/reviews/harness/harness-core/35292#-N6qKXEE6-rLGiuv5Y0d:-N6qX4y7Bys3E8hqlepL:bre0fw5) ([raw file](https://github.com/harness/harness-core/blob/03ca6133b67161586bdfdd46c7bb8ff3f8734b37/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L249)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do we need this now?
</blockquote></details>

Was needed for input set validation. Moved this line into the validation helper itself

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35292)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35292)* status: :shipit: complete! ✓

**Pull request merged**
