### PR TITLE
fix: [DEL-4575]: upgrading org.apache.cxf_cxf-core to 3.4.7

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Describe your changes
Upgrading org.apache.cxf_cxf-core package 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35941)

### CODE REVIEW

**Review by xingchi-jin — APPROVED** [review]

**Comment by jennyjames21** [comment]
*[`120-ng-manager/src/test/resources/mongo/indexes.txt` line 699 at r4](https://reviewable.io/reviews/harness/harness-core/35941#-N8X2f5JE_xI8MvdTE9K:-N8X2f5JE_xI8MvdTE9L:b-1qwfb0) ([raw file](https://github.com/harness/harness-core/blob/9932020d862b303b155a2748daf1d7f744e9e761/120-ng-manager/src/test/resources/mongo/indexes.txt#L699)):*
> ```help
> rollbackData {"name": "key", "background": true} {"key": 1}
> rollbackData {"name": "key_stageStatus_createdAt", "background": true} {"key": 1, "stageStatus": 1, "createdAt": -1}
> rollbackData {"name": "stageExecutionId", "background": true} {"stageExecutionId": 1}
> ```

why index change?

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35941)* status: 0 of 1 approvals obtained.

**Comment by raghuAtWings** [comment]
*[`120-ng-manager/src/test/resources/mongo/indexes.txt` line 699 at r4](https://reviewable.io/reviews/harness/harness-core/35941#-N8X2f5JE_xI8MvdTE9K:-N8X5613EjadfNEJtvOt:b-ftglw9) ([raw file](https://github.com/harness/harness-core/blob/9932020d862b303b155a2748daf1d7f744e9e761/120-ng-manager/src/test/resources/mongo/indexes.txt#L699)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

why index change?
</blockquote></details>

the test was failing, its not related to the PR.

**Review by jennyjames21 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35941)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35941)* status: :shipit: complete! ✓

**Pull request merged**
