### PR TITLE
feat: [IDP-1273]: Licensing - Enforcement changes

### PR DESCRIPTION
**Pull request by sathish-soundarapandian**
## Describe your changes
Licensing - Enforcement changes

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56870)

### CODE REVIEW

**Review by Xin-Harness — CHANGES_REQUESTED** [review]
> Reviewed 17 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56870)* status: 18 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/chart/templates/config.yaml` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/56870#-Nm1ouH32_2yyhUJ5-bi:-Nm1ouH45rSDDIfVehg5:bev8tua) ([raw file](https://github.com/harness/harness-core/blob/e20a37fc3561522ea04e6697a269244fe7116c27/120-ng-manager/chart/templates/config.yaml#L76)):*
> ```YAML
>   CI_MANAGER_SERVICE_CLIENT_BASEURL: http://ci-manager:7090/
>   CVNG_SERVICE_CLIENT_BASEURL: http://cv-nextgen:6060/cv/api/
>   IDP_SERVICE_BASE_URL: http://idp-service:12003/
> ```

It is recommended to rename it to IDP_SERVICE_CLIENT_BASE_URL since it helps understand it connect to IDP service client rather than server itself.
___
*[`943-enforcement-beans/src/main/java/io/harness/enforcement/constants/FeatureRestrictionName.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/56870#-Nm2dETgBYZnuKBQwH0l:-Nm2dETgBYZnuKBQwH0m:b-kcxsmu) ([raw file](https://github.com/harness/harness-core/blob/e20a37fc3561522ea04e6697a269244fe7116c27/943-enforcement-beans/src/main/java/io/harness/enforcement/constants/FeatureRestrictionName.java#L115)):*
> ```Java
>   SEI_MAX_NUMBER_OF_CONTRIBUTORS("SEI_MAX_NUMBER_OF_CONTRIBUTORS"),
> 
>   // IDP Features
> ```

nit: the feature name would explain the purpose of the code and we don't need to have the comment

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56870)* status: 18 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/chart/templates/config.yaml` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/56870#-Nm1ouH32_2yyhUJ5-bi:-Nm45aK_3IMZTAdBqd9Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e20a37fc3561522ea04e6697a269244fe7116c27/120-ng-manager/chart/templates/config.yaml#L76)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

It is recommended to rename it to IDP_SERVICE_CLIENT_BASE_URL since it helps understand it connect to IDP service client rather than server itself.
</blockquote></details>

Done.
___
*[`943-enforcement-beans/src/main/java/io/harness/enforcement/constants/FeatureRestrictionName.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/56870#-Nm2dETgBYZnuKBQwH0l:-Nm45btL57W54dLoGM04:b9qes6o) ([raw file](https://github.com/harness/harness-core/blob/e20a37fc3561522ea04e6697a269244fe7116c27/943-enforcement-beans/src/main/java/io/harness/enforcement/constants/FeatureRestrictionName.java#L115)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

nit: the feature name would explain the purpose of the code and we don't need to have the comment
</blockquote></details>

Yes. The feature name will explain the purpose of the code. It's just that we are grouping module specific features with that comment.
If we had a constrain stating that feature names should start with module prefix, that would be the ideal way. But as if now, it is not being followed.

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56870)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 11 of 18 files at r1, 3 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56870)* status: 4 file(s) to review.

**Comment by sathish-soundarapandian** [comment]
trigger review

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Review by sandeepa-kv-jois — APPROVED** [review]

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Review by arya-harness — APPROVED** [review]

**Comment by sathish-soundarapandian** [comment]
trigger ut6, ut5

**Review by jyotiraval — APPROVED** [review]

**Pull request merged**
