### PR TITLE
techdebt: [PIE-6096]: added configs in debezium service

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39537)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39537)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`debezium-service/config/config.yml` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/39537#-NFwRljT4dW0hVAXC-Xi:-NFwRljUCVDNp2kNCEdZ:b7m2nk2) ([raw file](https://github.com/harness/harness-core/blob/08b41bd5f9cc4f7da9a81a8c119b0858ba3c31d0/debezium-service/config/config.yml#L56)):*
> ```YAML
>     max.batch.size: ${MAX_BATCH_SIZE:-1000}
>     max.queue.size.in.bytes: ${MAX_QUEUE_SIZE_IN_BYTES:-1000000000}
>     poll.interval.ms: ${POLL_INTERVAL_MS:-5000}
> ```

we can make it to 3000

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39537)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`debezium-service/config/config.yml` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/39537#-NFwRljT4dW0hVAXC-Xi:-NFweSTD0YUstu5n1AXC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/08b41bd5f9cc4f7da9a81a8c119b0858ba3c31d0/debezium-service/config/config.yml#L56)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we can make it to 3000
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger messagecheck

**Comment by shalini-agr** [comment]
trigger compile ti0 ti1 ti2 ft2

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39537)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39537)* status: :shipit: complete! ✓

**Pull request merged**
