### PR TITLE
feat: [PL-22367]: fixed scim user creation flow

### PR DESCRIPTION
**Pull request by ujjawal-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30505)

### CODE REVIEW

**Comment by ujjawal-harness** [comment]
trigger messagecheck

**Comment by piyush-harness** [comment]
___
*[120-ng-manager/src/test/java/io/harness/ng/scim/NGScimUserServiceImplTest.java, line 54 at r3](https://reviewable.io/reviews/harness/harness-core/30505#-MuzgFJoBOWeVWqq5Uc5:-MuzgFJoBOWeVWqq5Uc6:b4168ha) ([raw file](https://github.com/harness/harness-core/blob/71b37dad11e60b93a0c629f2ac8922c578eb9d80/120-ng-manager/src/test/java/io/harness/ng/scim/NGScimUserServiceImplTest.java#L54)):*
> ```Java
>   @Owner(developers = UJJAWAL)
>   @Category(UnitTests.class)
>   public void testCreateUser() {
> ```

Name these tests properly , something like testScim_IfUserIsNotPartOfAccountAlready_ItShouldAddToAccount() etc

**Review by piyush-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30505)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
:lgtm:

**Review by piyush-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30505)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30505)* status: :shipit: complete! ✓

**Pull request merged**
