### PR TITLE
techdebt: [CDS-79518]: Make cache threadsafe for pipeline service events

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Describe your changes

Rather than doing 2 operations for adding a value in redis cache during event consumption, we are doing one now.

What issues those 2 were causing?
- This was not atomic and thus had a chance of inconsitency

How we are solving this?
We have used putIfAbsent method that returns a boolean of whether the put was succesful or not.
This is the documentation for the same:
 https://www.javadoc.io/doc/javax.cache/cache-api/1.0.0/javax/cache/Cache.html#putIfAbsent(K,%20V)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52969)

### CODE REVIEW

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52969)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java` line 141 at r1](https://reviewable.io/reviews/harness/harness-core/52969#-NeR1hYz9CwD2uakGkAZ:-NeR1hYz9CwD2uakGkA_:bprgks5) ([raw file](https://github.com/harness/harness-core/blob/38bd59ecd0aa23969d6f5f511a6ea906e2208e4d/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java#L141)):*
> ```Java
>     AtomicBoolean success = new AtomicBoolean(true);
>     if (messageListener.isProcessable(message) && !isAlreadyProcessed(message)) {
>       log.info("Read message with message id {} from redis", message.getId());
> ```

Can you shift this log to the top as well?, just where we start iterating on messages



_Code quote:_
```Java
log.info("Read message with message id {} from redis", message.getId());
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52969)* status: 1. unresolved discussions. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java` line 141 at r1](https://reviewable.io/reviews/harness/harness-core/52969#-NeR1hYz9CwD2uakGkAZ:-NeRArKt4M56dD3E2zQL:b32v57) ([raw file](https://github.com/harness/harness-core/blob/38bd59ecd0aa23969d6f5f511a6ea906e2208e4d/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java#L141)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Can you shift this log to the top as well?, just where we start iterating on messages
</blockquote></details>

+1

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52969)* status: 1. unresolved discussions. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java` line 141 at r1](https://reviewable.io/reviews/harness/harness-core/52969#-NeR1hYz9CwD2uakGkAZ:-NeRQg504ZboA-K5-Qz-:b-qhgmb2) ([raw file](https://github.com/harness/harness-core/blob/38bd59ecd0aa23969d6f5f511a6ea906e2208e4d/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java#L141)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Also FYI, we can add maybe comment details here that putIfAbsent is atomic -> via taking lock inside and putting value in a map, as its a cache, if we see slowness in our load test -> we should move to Rset add which is truly atomic without taking lock

**Review by hextechpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52969)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java` line 141 at r1](https://reviewable.io/reviews/harness/harness-core/52969#-NeR1hYz9CwD2uakGkAZ:-NeR_yZC0x7ReRe2sALP:b148nhl) ([raw file](https://github.com/harness/harness-core/blob/38bd59ecd0aa23969d6f5f511a6ea906e2208e4d/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java#L141)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Also FYI, we can add maybe comment details here that putIfAbsent is atomic -> via taking lock inside and putting value in a map, as its a cache, if we see slowness in our load test -> we should move to Rset add which is truly atomic without taking lock
</blockquote></details>

@sahilhindwani-harness maybe we should replace this with RSet with an iterator for expiry

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Review by hextechpal — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52969)* status: :shipit: complete! ✓

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger ut3

**Comment by sahilhindwani-harness** [comment]
trigger ut7

**Comment by sahilhindwani-harness** [comment]
trigger ut3

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52969)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
