### PR TITLE
[feat]: [PL-42030]: Propagate scopeInfo as request context in internal HTTP requests

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
For each api call Scope info filter resolves scope info based on request parameters. Scope info resolution happens multiple times.
 
To reduce scope info resolution calls we can reuse if it is already resolved. 
This PR adds support to put already resolved scope info into `MDC` context. This MDC scope info can be subsequently used by http client to send same information as http headers. Once Scope info filter receives this scope info in headers it will reuse the same instead of resolving it again.

Tests:
Added logs in scope filter to verify if scope info present in http request it will not resolve but use the same one.

Logs where it is using existing scope info

> {"severity":"INFO","timestamp_millis":"1701679924181","logger":"io.harness.security.ScopeInfoFilter","harness":{"scopeInfo_uniqueId":"EgAPBxGfSYKdiOGPOG931A","scopeInfo_account":"EgAPBxGfSYKdiOGPOG931A","scopeInfo_scopeType":"ACCOUNT","X-requestId":"1edd4652-4f29-45de-989a-097f990463e8"},"thread":"dw-436 - GET /settings/disable_harness_built_in_secret_manager?accountIdentifier=EgAPBxGfSYKdiOGPOG931A&repoIdentifier=__default__&branch=__default__&getDefaultFromOtherRepo=false","message":"SCOPE_INFO_FILTER: setting existing context in MDC: ScopeInfo(accountIdentifier=EgAPBxGfSYKdiOGPOG931A, orgIdentifier=null, projectIdentifier=null, scopeType=ACCOUNT, uniqueId=EgAPBxGfSYKdiOGPOG931A)","timestamp":"2023-12-04 08:52:04.181 +0000"}
> {"severity":"INFO","timestamp_millis":"1701679924212","logger":"io.harness.security.ScopeInfoFilter","harness":{"scopeInfo_uniqueId":"EgAPBxGfSYKdiOGPOG931A","scopeInfo_account":"EgAPBxGfSYKdiOGPOG931A","scopeInfo_scopeType":"ACCOUNT","X-requestId":"1edd4652-4f29-45de-989a-097f990463e8"},"thread":"dw-175 - GET /git-sync?accountIdentifier=EgAPBxGfSYKdiOGPOG931A&repoIdentifier=__default__&branch=__default__&getDefaultFromOtherRepo=false","message":"SCOPE_INFO_FILTER: setting existing context in MDC: ScopeInfo(accountIdentifier=EgAPBxGfSYKdiOGPOG931A, orgIdentifier=null, projectIdentifier=null, scopeType=ACCOUNT, uniqueId=EgAPBxGfSYKdiOGPOG931A)","timestamp":"2023-12-04 08:52:04.212 +0000"}

Logs where it is resolving new scope info if there is no existing one in request context

> {"severity":"INFO","timestamp_millis":"1701679930290","logger":"io.harness.security.ScopeInfoFilter","harness":{"scopeInfo_uniqueId":"EgAPBxGfSYKdiOGPOG931A","scopeInfo_account":"EgAPBxGfSYKdiOGPOG931A","scopeInfo_scopeType":"ACCOUNT","X-requestId":"3ee58c7b-7364-4b33-99af-36f933964908"},"thread":"dw-417 - GET /user/usermembership?userId=U0VtVGKwSia95aYnWj8BTQ&accountIdentifier=EgAPBxGfSYKdiOGPOG931A","message":"SCOPE_INFO_FILTER: setting new context in MDC: ScopeInfo(accountIdentifier=EgAPBxGfSYKdiOGPOG931A, orgIdentifier=null, projectIdentifier=null, scopeType=ACCOUNT, uniqueId=EgAPBxGfSYKdiOGPOG931A) existing was: ScopeInfo(accountIdentifier=null, orgIdentifier=null, projectIdentifier=null, scopeType=null, uniqueId=null)","timestamp":"2023-12-04 08:52:10.290 +0000"}
> {"severity":"INFO","timestamp_millis":"1701679930313","logger":"io.harness.security.ScopeInfoFilter","harness":{"scopeInfo_uniqueId":"EgAPBxGfSYKdiOGPOG931A","scopeInfo_account":"EgAPBxGfSYKdiOGPOG931A","scopeInfo_scopeType":"ACCOUNT","X-requestId":"696e035a-066a-4936-aa19-42b5a3ad5ab0"},"thread":"dw-436 - POST /user/aggregate?accountId=EgAPBxGfSYKdiOGPOG931A&accountIdentifier=EgAPBxGfSYKdiOGPOG931A&pageIndex=0&pageSize=1000&searchTerm=pl_auto_user_dx9jw7%40harnessiopublic.testinator.com","message":"SCOPE_INFO_FILTER: setting new context in MDC: ScopeInfo(accountIdentifier=EgAPBxGfSYKdiOGPOG931A, orgIdentifier=null, projectIdentifier=null, scopeType=ACCOUNT, uniqueId=EgAPBxGfSYKdiOGPOG931A) existing was: ScopeInfo(accountIdentifier=null, orgIdentifier=null, projectIdentifier=null, scopeType=null, uniqueId=null)","timestamp":"2023-12-04 08:52:10.313 +0000"}

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56263)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56263)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/56263#-Nl1IDXD8DNOsz6y4-Vq:-Nl1IDXD8DNOsz6y4-Vr:btcbysq) ([raw file](https://github.com/harness/harness-core/blob/0aa5dcdf8ee83e4ca78f3f73513d6c9bd7393e0d/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L76)):*
> ```Java
>       existingScopeInfoBuilder.scopeType(ScopeLevel.valueOf(existingScopeType));
>       existingScopeInfoBuilder.uniqueId(existingUniqueId);
>     }
> ```

existingScopeInfoBuilder.build() should be called here itself
___
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/56263#-Nl1I2feAd5bSF0x5Oe_:-Nl1I2feAd5bSF0x5Oea:b-bmhn14) ([raw file](https://github.com/harness/harness-core/blob/0aa5dcdf8ee83e4ca78f3f73513d6c9bd7393e0d/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L91)):*
> ```Java
>       String projectIdentifier = getProjectIdentifierFrom(requestContext).orElse(null);
> 
>       ScopeInfo existingScopeInfo = existingScopeInfoBuilder.build();
> ```

.build() method should be called above itself
___
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 172 at r1](https://reviewable.io/reviews/harness/harness-core/56263#-Nl1I_CV90XS04epAGwA:-Nl1I_CV90XS04epAGwB:b-s3wkk6) ([raw file](https://github.com/harness/harness-core/blob/0aa5dcdf8ee83e4ca78f3f73513d6c9bd7393e0d/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L172)):*
> ```Java
> 
>   @Override
>   public void filter(ContainerRequestContext containerRequestContext, ContainerResponseContext containerResponseContext)
> ```

Whats the difference between this and the other filter method?
___
*[`970-ng-commons/src/main/java/io/harness/beans/scope/BUILD.bazel` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/56263#-Nl1Jtyv3ujoPlcJRtVt:-Nl1Jtyv3ujoPlcJRtVu:bdk7ku9) ([raw file](https://github.com/harness/harness-core/blob/0aa5dcdf8ee83e4ca78f3f73513d6c9bd7393e0d/970-ng-commons/src/main/java/io/harness/beans/scope/BUILD.bazel#L26)):*
> ```Starlark
>         "//980-commons/src/main/java/io/harness/exception:module",
>         "//999-annotations/src/main/java/io/harness/annotations/dev:module",
>         "@maven//:com_squareup_okhttp3_okhttp",
> ```

Why is this needed?
___
*[`970-ng-commons/src/main/java/io/harness/beans/scope/ScopeInfoContext.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/56263#-Nl1JXdNAFW6qFzOPa0l:-Nl1JXdNAFW6qFzOPa0m:bnvetaq) ([raw file](https://github.com/harness/harness-core/blob/0aa5dcdf8ee83e4ca78f3f73513d6c9bd7393e0d/970-ng-commons/src/main/java/io/harness/beans/scope/ScopeInfoContext.java#L27)):*
> ```Java
> @UtilityClass
> public class ScopeInfoContext {
>   public static final String SCOPE_INFO_ACCOUNT_CONTEXT_PROPERTY = "scopeInfo_account";
> ```

HTTP header names are typically case-insensitive, and they are often expressed in kebab-case (hyphen-separated words, all lowercase) or sometimes in camelCase. Underscore-separated words is not a common convention for HTTP headers.

Maybe we can do

public static final String SCOPE_INFO_ACCOUNT_CONTEXT_PROPERTY = "scopeinfo-account";
public static final String SCOPE_INFO_ORG_CONTEXT_PROPERTY = "scopeinfo-org";
public static final String SCOPE_INFO_PROJECT_CONTEXT_PROPERTY = "scopeinfo-project";
public static final String SCOPE_INFO_SCOPE_TYPE_CONTEXT_PROPERTY = "scopeinfo-scopetype";
public static final String SCOPE_INFO_UNIQUE_ID_CONTEXT_PROPERTY = "scopeinfo-uniqueid";

**Comment by ashishsanodia-harness** [comment]
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/56263#-Nl1IDXD8DNOsz6y4-Vq:-Nl1q0TlCNeG6rdpf-fX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/371c2fd248b15f377ecdab23d155de5fdd2d8741/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L76)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

existingScopeInfoBuilder.build() should be called here itself
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/56263#-Nl1I2feAd5bSF0x5Oe_:-Nl1q31YAc1EqkVwxoQF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/371c2fd248b15f377ecdab23d155de5fdd2d8741/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L91)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

.build() method should be called above itself
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
*[`970-ng-commons/src/main/java/io/harness/beans/scope/BUILD.bazel` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/56263#-Nl1Jtyv3ujoPlcJRtVt:-Nl1qYbm39QurzMce-tY:b-k0xxyk) ([raw file](https://github.com/harness/harness-core/blob/371c2fd248b15f377ecdab23d155de5fdd2d8741/970-ng-commons/src/main/java/io/harness/beans/scope/BUILD.bazel#L26)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

ScopeinfoContext needs below okhttp3 classes, Interceptor is being used to put MDC info in request headers
import okhttp3.Interceptor;  
import okhttp3.Request;

**Comment by ashishsanodia-harness** [comment]
*[`970-ng-commons/src/main/java/io/harness/beans/scope/ScopeInfoContext.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/56263#-Nl1JXdNAFW6qFzOPa0l:-Nl1r-goACf-0QSbDQcN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/371c2fd248b15f377ecdab23d155de5fdd2d8741/970-ng-commons/src/main/java/io/harness/beans/scope/ScopeInfoContext.java#L27)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

HTTP header names are typically case-insensitive, and they are often expressed in kebab-case (hyphen-separated words, all lowercase) or sometimes in camelCase. Underscore-separated words is not a common convention for HTTP headers.

Maybe we can do

public static final String SCOPE_INFO_ACCOUNT_CONTEXT_PROPERTY = "scopeinfo-account";
public static final String SCOPE_INFO_ORG_CONTEXT_PROPERTY = "scopeinfo-org";
public static final String SCOPE_INFO_PROJECT_CONTEXT_PROPERTY = "scopeinfo-project";
public static final String SCOPE_INFO_SCOPE_TYPE_CONTEXT_PROPERTY = "scopeinfo-scopetype";
public static final String SCOPE_INFO_UNIQUE_ID_CONTEXT_PROPERTY = "scopeinfo-uniqueid";
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger ut5, ut6, ut8

**Pull request merged**
