### PR TITLE
feat: [CDS-78955]: Refractoring for Schema Parser, Moving parsers to individual services and removing factory

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Refractoring for Abstract Schema Parser 
Moved PipelineSchemaParserV0 to Pipeline Service 
Moved TemplateSchemaParserV0 to Template Service
Removed the JsonNode schema Paramater's from the Individual Parser ( They will internally fetch it on their init () )
Removed the AbstractSchemaParserFactory
Created SchemaFetcher Util class for template srv

Dependency for parser and schemaFetcher -
PipelineSchemaParserV0 ( Injects schema fetcher to fetch Schema ) and PMSYamlSchemaServiceImpl ( Injects PipelineSchemaParserV0 to fetch individual schemas, currently all logic was in SchemaFetcher )

Similarly created schemaFetcher for template srv as well as else there will be cyclic dependency as parser will need schemaFetcher to fetch schema, And others schema logics for template srv are in NGTemplateSchemaServiceImpl which will use Parser to fetch individual Schema

Tests Done - 
* Individual Schema API for Pipelines ( tested pipeline v0,v1 , Trigger v0, individual schema for stepgroup and strategy)
* Static schema API for template service 
* Tested template create flow fetching correct schema

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52628)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52628)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 538 at r1](https://reviewable.io/reviews/harness/harness-core/52628#-NdoXiTP5KFgMni0v1Sg:-NdoXiTP5KFgMni0v1Sh:bhpvfku) ([raw file](https://github.com/harness/harness-core/blob/977ffa6fbab2ac0ef36a496dd46a838d4c0089c5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L538)):*
> ```Java
> 
>   private ObjectNode getIndividualSchema(String nodeGroup, String nodeType, String nodeGroupDifferentiator) {
>     pipelineSchemaParserV0.getInstance();
> ```

what is this instance doing here?



_Code quote:_
```Java
pipelineSchemaParserV0.getInstance();
```

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52628)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 538 at r1](https://reviewable.io/reviews/harness/harness-core/52628#-NdoXiTP5KFgMni0v1Sg:-Ne22KYpExVoRbTteXLL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/977ffa6fbab2ac0ef36a496dd46a838d4c0089c5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L538)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what is this instance doing here?
</blockquote></details>

Done.

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52628)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/AbstractStaticSchemaParser.java` line 56 at r4](https://reviewable.io/reviews/harness/harness-core/52628#-Ne2ADY834wPv5prux1A:-Ne2ADY834wPv5prux1B:b7sjhkp) ([raw file](https://github.com/harness/harness-core/blob/b564dd353ad6b0af90b0981c899af817c9f66999/953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/AbstractStaticSchemaParser.java#L56)):*
> ```Java
>       String currentFqn, String childNodeRefValue, ObjectNode objectNode);
> 
>   public AbstractStaticSchemaParser initializeParserIfNotAlreadyInitialzed() {
> ```

why to rename?

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52628)* status: 14 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/AbstractStaticSchemaParser.java` line 56 at r4](https://reviewable.io/reviews/harness/harness-core/52628#-Ne2ADY834wPv5prux1A:-Ne2F0XM3tYxP3fAhylH:b8c68fp) ([raw file](https://github.com/harness/harness-core/blob/b564dd353ad6b0af90b0981c899af817c9f66999/953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/AbstractStaticSchemaParser.java#L56)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why to rename?
</blockquote></details>

Done
Purpose of that function is to initialise the parser, confirmed with brijesh, he mentioned to rename it

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 6 of 14 files at r1, 7 of 8 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52628)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/AbstractStaticSchemaParser.java` line 56 at r4](https://reviewable.io/reviews/harness/harness-core/52628#-Ne2ADY834wPv5prux1A:-Ne2lpsU74QzM-Jo2y89:b1rp4uj) ([raw file](https://github.com/harness/harness-core/blob/b564dd353ad6b0af90b0981c899af817c9f66999/953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/AbstractStaticSchemaParser.java#L56)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done
Purpose of that function is to initialise the parser, confirmed with brijesh, he mentioned to rename it
</blockquote></details>

This method does the initialisation of the parser so renaming.
@utkarshchoubey-harness  can you make it void method? We are not doing anything of the returned value.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52628)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/AbstractStaticSchemaParser.java` line 56 at r4](https://reviewable.io/reviews/harness/harness-core/52628#-Ne2ADY834wPv5prux1A:-Ne2zD2SEeKk_C6vhGPK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b564dd353ad6b0af90b0981c899af817c9f66999/953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/AbstractStaticSchemaParser.java#L56)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

This method does the initialisation of the parser so renaming.
@utkarshchoubey-harness  can you make it void method? We are not doing anything of the returned value.
</blockquote></details>

Done.

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52628)* status: 11 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r3, 1 of 1 files at r5, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52628)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/AbstractStaticSchemaParser.java` line 56 at r4](https://reviewable.io/reviews/harness/harness-core/52628#-Ne2ADY834wPv5prux1A:-Ne3DMdhEQ0ifD_3Brzz:b-tyx2oz) ([raw file](https://github.com/harness/harness-core/blob/b564dd353ad6b0af90b0981c899af817c9f66999/953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/AbstractStaticSchemaParser.java#L56)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@utkarshchoubey-harness @brijeshdhakar i think we should name it getInstace, it will have logic to intialise or not inside it

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52628)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Pull request merged**
