### PR TITLE
fix: [DEL-4150]: Fix entry in bazel_script.sh

### PR DESCRIPTION
**Pull request by johannesHarness**
Fix entry in bazel_script.sh
---
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33525)

### CODE REVIEW

**Comment by johannesHarness** [comment]
trigger ti1

**Comment by johannesHarness** [comment]
trigger ti2

**Comment by johannesHarness** [comment]
trigger ti3

**Comment by johannesHarness** [comment]
trigger ti4

**Review by devkimittal — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33525)* status: :shipit: complete! ✓

**Comment by johannesHarness** [comment]
trigger ti1

**Comment by johannesHarness** [comment]
trigger ti2

**Pull request merged**
