### PR TITLE
feat: [CDS-46204]: Serverless S3 Backend Changes

### PR DESCRIPTION
**Pull request by alluvamsi-harness**
## Describe your changes
Added backend changes to support Serverless NG S3 Manifest Store
Test Plan: https://docs.google.com/spreadsheets/d/1IZ6URhH2bnJ59n2DDe503Cd4zvuKiSMAkWkNm8x2hQc/edit#gid=0
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40904)

### CODE REVIEW

**Comment by alluvamsi-harness** [comment]
trigger messagecheck

**Comment by alluvamsi-harness** [comment]
trigger feature-build

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java` line 181 at r2](https://reviewable.io/reviews/harness/harness-core/40904#-NIAvq_P-E3TODcylHqZ:-NIAvq_P-E3TODcylHq_:b-bflwqi) ([raw file](https://github.com/harness/harness-core/blob/9cd8d86bf37402f2fbd92db03f8ea9b97e80bb1b/125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java#L181)):*
> ```Java
>     kryo.register(ServerlessStepExceptionPassThroughData.class, 12580);
>     kryo.register(ServerlessGitFetchFailurePassThroughData.class, 12581);
>     kryo.register(ServerlessFetchFileOutcome.class, 12582);
> ```

please check if this is backward compatible, IMO should be but lets verify

**Comment by alluvamsi-harness** [comment]
trigger feature-build

**Review by PragyeshMishra01 — APPROVED** [review]

**Review by arpit3107 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40904)* status: 35 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 413 at r5](https://reviewable.io/reviews/harness/harness-core/40904#-NII3oQ2CAxav-gXh5yp:-NII3oQ2CAxav-gXh5yq:bshwlbw) ([raw file](https://github.com/harness/harness-core/blob/08b243651681a45f5f7715c0457b63946af0ced0/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L413)):*
> ```Java
>   CF_COMMAND_TASK_NG(TaskGroup.TAS, "Command task for tanzu application service"),
>   ECS_S3_FETCH_TASK_NG(TaskGroup.ECS, "ECS S3 Fetch Task"),
>   SERVERLESS_S3_FETCH_TASK_NG(TaskGroup.SERVERLESS_NG, "Serverless S3 Fetch File Task");
> ```

You have added a new taskType. So how you will be using it with delegate keeping backward compatibility in mind. Since delegate will always be few versions behind manager.

**Review by mdmilic — APPROVED** [review]
Approve delegate CODEOWNER changes

> Reviewed 7 of 28 files at r1, 2 of 15 files at r3, 4 of 12 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40904#-:-NII6zIe9DMsTkflLNma:bo6b12e)* status: 35 file(s) to review. 1 change requests. 2. unresolved discussions. 

___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 413 at r5](https://reviewable.io/reviews/harness/harness-core/40904#-NII3oQ2CAxav-gXh5yp:-NII75AS63VsbZk8Nwd5:b-l2b69d) ([raw file](https://github.com/harness/harness-core/blob/08b243651681a45f5f7715c0457b63946af0ced0/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L413)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

You have added a new taskType. So how you will be using it with delegate keeping backward compatibility in mind. Since delegate will always be few versions behind manager.
</blockquote></details>

@arpit3107 old delegates will not have this task type, hence will not accept tasks of this type. Adding new taskType is fine (not breaking change), the problem will come if they later decide that they need to add new parameters to TaskParams or TaskResponse which is a breaking change and not allowed.

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 16 of 28 files at r1, 6 of 15 files at r3, 11 of 12 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40904#-:-NIIHd1g5mepN6owIOZB:bnfp4nl)* status: 21 file(s) to review. 1 change requests. 2. unresolved discussions.

**Review by sainath-b — APPROVED** [review]

**Review by sainath-b — APPROVED** [review]
> Reviewed 16 of 28 files at r1, 6 of 15 files at r3, 11 of 12 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40904)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions.

**Review by sainath-b — APPROVED** [review]

**Review by sainath-b — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40904)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions.

**Pull request merged**
