### PR TITLE
feat: [PL-41852]: Notification client API to process notification trigger request

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary: 
- Notification client-side changes to process notification trigger request and process using mongo queue

Test
- Unit test
- Local test 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53996)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
*[`platform-service/modules/notification-service/src/test/java/io/harness/notification/eventbackbone/MongoMessageConsumerTest.java` line 133 at r2](https://reviewable.io/reviews/harness/harness-core/53996#-Nh1Dfk_0wog75xSUMF5:-Nh1Dfk_0wog75xSUMF6:b-rnctyp) ([raw file](https://github.com/harness/harness-core/blob/670f9fc6c4e1850afc913d5717d8f9525ddd43c5/platform-service/modules/notification-service/src/test/java/io/harness/notification/eventbackbone/MongoMessageConsumerTest.java#L133)):*
> ```Java
>         MongoNotificationRequest.builder().bytes(notificationTriggerRequest.toByteArray()).build();
>     assertThatThrownBy(() -> mongoMessageConsumer.onMessage(mongoNotificationRequest))
>         .isInstanceOf(NullPointerException.class);
> ```

why null pointer exception?

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
*[`platform-service/modules/notification-service/src/test/java/io/harness/notification/eventbackbone/MongoMessageConsumerTest.java` line 133 at r2](https://reviewable.io/reviews/harness/harness-core/53996#-Nh1Dfk_0wog75xSUMF5:-Nh3gKuK751tA8pOE1Ro:b-671mmn) ([raw file](https://github.com/harness/harness-core/blob/670f9fc6c4e1850afc913d5717d8f9525ddd43c5/platform-service/modules/notification-service/src/test/java/io/harness/notification/eventbackbone/MongoMessageConsumerTest.java#L133)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

why null pointer exception?
</blockquote></details>

Thats was wrong, it was supposed to throw invalidProtoException. Since there is a catch inside method, removing this statement of assert throw

**Comment by jennyjames21** [comment]
*[`platform-service/modules/notification-service/src/test/java/io/harness/notification/eventbackbone/MongoMessageConsumerTest.java` line 133 at r2](https://reviewable.io/reviews/harness/harness-core/53996#-Nh1Dfk_0wog75xSUMF5:-Nh3ghqa4PL50WHFZz3l:b-lsbr4s) ([raw file](https://github.com/harness/harness-core/blob/670f9fc6c4e1850afc913d5717d8f9525ddd43c5/platform-service/modules/notification-service/src/test/java/io/harness/notification/eventbackbone/MongoMessageConsumerTest.java#L133)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Thats was wrong, it was supposed to throw invalidProtoException. Since there is a catch inside method, removing this statement of assert throw
</blockquote></details>

unit test updated

**Comment by jennyjames21** [comment]
trigger uts

**Review by ashishsanodia-harness — APPROVED** [review]
:lgtm:

> Reviewed 10 of 12 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53996#-:-Nh6e1pH2t-F6awPRkXr:bnfp4nl)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by Varsha-lalwani — APPROVED** [review]
approved for SRM

**Pull request merged**
