### PR TITLE
fix: [SRM-12747]: SLOHealthListView class changes

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39684)

### CODE REVIEW

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39684)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 327 at r1](https://reviewable.io/reviews/harness/harness-core/39684#-NGGW_4A1cebxkW-MEXr:-NGGW_4B8t-VwucTRmSQ:b19tvz2) ([raw file](https://github.com/harness/harness-core/blob/836fc4ad2ddebfae4e347bbeec739205e79f6f72/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L327)):*
> ```Java
>         .sloTargetPercentage(serviceLevelObjective.getSloTargetPercentage())
>         .userJourneys(userJourneys)
>         .userJourneyName(userJourneys.get(0).getName())
> ```

This will work for now since we earlier allowed only 1 user journey, but what do we want to show in the future since we are allowing more than one user journeys, shouldn't we show them all?



_Code quote:_
```Java
 .userJourneyName(userJourneys.get(0).getName())
```

**Review by karansaraswat19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39684)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 327 at r1](https://reviewable.io/reviews/harness/harness-core/39684#-NGGW_4A1cebxkW-MEXr:-NGGhPTv9hGq9u_DoGaK:b-uk1eo1) ([raw file](https://github.com/harness/harness-core/blob/836fc4ad2ddebfae4e347bbeec739205e79f6f72/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L327)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

This will work for now since we earlier allowed only 1 user journey, but what do we want to show in the future since we are allowing more than one user journeys, shouldn't we show them all?
</blockquote></details>

We will be keeping this just to make it backwards compatible because rn the frontend expects a string not an array.

**Review by Varsha-lalwani — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39684)* status: 1. unresolved discussions.

**Comment by karansaraswat19** [comment]
trigger messagecheck

**Review by Varsha-lalwani — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39684)* status: :shipit: complete! ✓

**Pull request merged**
