### PR TITLE
feat: [DEL-5026]: deprecate PT heartbeat and save task failure

### PR DESCRIPTION
**Pull request by arpit3107**
## Describe your changes
As part of https://harness.atlassian.net/wiki/spaces/DEL/pages/21197226916/Perpetual+Task+Enhancements+Q3-22, we wanted to deprecate PT heartbeat as this is no where used except for debugging purpose (we have other ways for debugging) and its calls used to cost a high ART and load.

So, we are deprecating PT heartbeat and should save task failure reason if PT execution failed for some reason. This should be backward compatible as immutable will be running a lot behind manager.

Scenarios tested:
1. This is backward compatible change, as i am only adding a new api, and leaving old one as it is.
2. Modified a PT execution task so that it will throw exception and that exception message is being saved in db. 
3. 
Screenshot 2022-10-28 at 1 01 02 PM

Screenshot 2022-10-28 at 12 42 21 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39291)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskLifecycleManager.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSBdls3hAYVj4cWxfx:-NFSBdlt5vBCf0I0HOfR:bqb647z) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskLifecycleManager.java#L84)):*
> ```Java
> 
>       // question? some tasks are internally failing on this runOnce and putting failure reason in the
>       // PerpetualTaskResponse.responseMessage, but they are setting responseCode as 200 only, as if nothing failed.
> ```

they should return 500

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskLifecycleManager.java` line 103 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSBpvD7mTKJ0N6zfv5:-NFSBpvD7mTKJ0N6zfv6:b-8f53fi) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskLifecycleManager.java#L103)):*
> ```Java
>       decrementTaskCounter();
>     }
>     perpetualTaskServiceAgentClient.recordPerpetualTaskFailure(taskId, accountId, perpetualTaskResponse);
> ```

aren't you still making a call to manager on each execution?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java` line 350 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSBzsdE4VCalyJUVnn:-NFSBzsdE4VCalyJUVno:b-mss626) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L350)):*
> ```Java
>     int responseCode = perpetualTaskResponse.getResponseCode();
>     if (responseCode == SC_OK) {
>       log.warn("Trying to record perpetual task failure even though task was successful.");
> ```

either rename this method to say recordTaskFailureIfNecessary or don't call it when its not supposed to. This warning log is meaning less.

**Comment by raghuAtWings** [comment]
*[`420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSCPLp0iJyUSUoNzpq:-NFSCPLp0iJyUSUoNzpr:byd4q2v) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java#L72)):*
> ```Java
>       }
>       // Question?? should we throw exception and fail incase accountId is not there
>       if (isEmpty(accountId)) {
> ```

is it possible to have accountId as null? if not then remove this

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/perpetualtask/grpc/PerpetualTaskServiceGrpc.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSCdJEC2n-Pwb6Ez2i:-NFSCdJFAiyCrmFWR1gk:b-gm7kaf) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/420-delegate-service/src/main/java/io/harness/perpetualtask/grpc/PerpetualTaskServiceGrpc.java#L67)):*
> ```Java
>   // Question? why is this still in place, when delegate has moved to rest calls
>   @Override
>   public void heartbeat(HeartbeatRequest request, StreamObserver<HeartbeatResponse> responseObserver) {
> ```

older immutable delegates may still call it. We should remove it after all the old immutable delegates in the prod db.

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java` line 292 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSCudN6qbwJAyxTUI0:-NFSCudN6qbwJAyxTUI1:b-c06fl2) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java#L292)):*
> ```Java
>   }
> 
>   public boolean saveTaskFailureExceptionAndCount(String taskId, String exceptionMsg, long failedExecutionCount) {
> ```

why boolean return?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 3 of 10 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39291)* status: 0 of 1 approvals obtained.

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39291)* status: 9 file(s) to review. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskLifecycleManager.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSBdls3hAYVj4cWxfx:-NFSmlzu-PbJM4o3HBYl:b-jtg73s) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskLifecycleManager.java#L84)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

they should return 500
</blockquote></details>

yes, so how we can make sure of this from other teams.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskLifecycleManager.java` line 103 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSBpvD7mTKJ0N6zfv5:-NFSmr3NAhb_ECfdw1th:b-g4l9dk) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskLifecycleManager.java#L103)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

aren't you still making a call to manager on each execution?
</blockquote></details>

Done, btw earlier the check was inside this method. So the method was calling only in case of failure.
___
*[`400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java` line 350 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSBzsdE4VCalyJUVnn:-NFSn2FW6FeBGU4FehFN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L350)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

either rename this method to say recordTaskFailureIfNecessary or don't call it when its not supposed to. This warning log is meaning less.
</blockquote></details>

Done.
___
*[`420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSCPLp0iJyUSUoNzpq:-NFSn3Pc0fcd5H6If77c:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java#L72)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

is it possible to have accountId as null? if not then remove this
</blockquote></details>

Done.
___
*[`420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java` line 292 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSCudN6qbwJAyxTUI0:-NFSn4YY3_4EOmvkBTXc:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java#L292)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why boolean return?
</blockquote></details>

done
___
*[`420-delegate-service/src/main/java/io/harness/perpetualtask/grpc/PerpetualTaskServiceGrpc.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSCdJEC2n-Pwb6Ez2i:-NFSnAgF7ZA5riNAo9Ix:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/420-delegate-service/src/main/java/io/harness/perpetualtask/grpc/PerpetualTaskServiceGrpc.java#L67)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

older immutable delegates may still call it. We should remove it after all the old immutable delegates in the prod db. 
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSCPLp0iJyUSUoNzpq:-NFU65ip9kzLebKgFmbl:b-64c6t9) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java#L72)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

REST call needs accountId for authentication purpose

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskLifecycleManager.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSBdls3hAYVj4cWxfx:-NFUCAO3DnFHez2IAXpU:b-h88l4d) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskLifecycleManager.java#L84)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

yes, so how we can make sure of this from other teams.
</blockquote></details>

i think we need to do that exercise of going through every PT task type. I will create ticket to track that

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskLifecycleManager.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSBdls3hAYVj4cWxfx:-NFUCPCj-uuXlT7U-Rhi:bqm9jd7) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskLifecycleManager.java#L84)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

i think we need to do that exercise of going through every PT task type. I will create ticket to track that
</blockquote></details>

One bad task can cause a lot of damage, not just to affect the customer delegate, but also to the manager. 

Last prod1 incident, the customer have 6k PT assigned and the HB delay was more than 10 mins multiple times due to resource exhaustion.

**Comment by arpit3107** [comment]
reopening pr to run tests failed due to build issues

**Review by jennyjames21 — APPROVED** [review]
Looks good

> Reviewed 2 of 9 files at r2, 7 of 9 files at r3, 3 of 3 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39291#-:-NFU7qY3DP3ck4TV6QOQ:bsrfkwe)* status: 6. unresolved discussions. 

___
*[`420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSCPLp0iJyUSUoNzpq:-NFy6-sO1tacJIkWWNzR:b-wecv84) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java#L72)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

REST call needs accountId for authentication purpose
</blockquote></details>

Did you test after removing

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskLifecycleManager.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/39291#-NFSBdls3hAYVj4cWxfx:-NFyHFjvBjSapV1lISyp:b-moqbso) ([raw file](https://github.com/harness/harness-core/blob/9d22603e97bb47df32caed5fd2c41e729fa5e102/260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskLifecycleManager.java#L84)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

One bad task can cause a lot of damage, not just to affect the customer delegate, but also to the manager. 

Last prod1 incident, the customer have 6k PT assigned and the HB delay was more than 10 mins multiple times due to resource exhaustion.


</blockquote></details>

we don't need to make sure for other teams. if the task is failing consistently we need to set the response code to 500 and let our framework back it off and stop it. We just need to make sure that the reason is updated and teams can debug why the task was backed off.

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 6 of 9 files at r3, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39291)* status: 1. unresolved discussions.

**Review by jennyjames21 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39291)* status: :shipit: complete! ✓

**Pull request merged**
