### PR TITLE
[feat]: [CDS-36063]:  Add unittest for the PR-31866

### PR DESCRIPTION
**Pull request by nassergonzalez**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32228)

### CODE REVIEW

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32228)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java, line 345 at r1](https://reviewable.io/reviews/harness/harness-core/32228#-N-XQswv8lckTK2JqkuW:-N-XQsww6HHjpdHV8ko4:bqcujcf) ([raw file](https://github.com/harness/harness-core/blob/a79b80102aed2b0ebc240e561bb0ade7865485e9/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java#L345)):*
> ```Java
>     boolean hasS3Files = false;
>     boolean hasGitFiles = false;
>     if (isNotEmpty(stepConfiguration.getParametersFilesSpecs())) {
> ```

it may not have parameters files but still have tags or template on git.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java, line 421 at r1](https://reviewable.io/reviews/harness/harness-core/32228#-N-XS33Y-hcMG7lsJpef:-N-XS33Y-hcMG7lsJpeg:bcrf0fd) ([raw file](https://github.com/harness/harness-core/blob/a79b80102aed2b0ebc240e561bb0ade7865485e9/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java#L421)):*
> ```Java
>     CloudformationCreateStackStepConfiguration stepConfiguration =
>         cloudformationCreateStackStepParameters.getConfiguration();
>     List<StackStatus> stackStatus = new ArrayList<>();
> ```

Let's call it stackStatuses. 
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java, line 465 at r1](https://reviewable.io/reviews/harness/harness-core/32228#-N-XSe30DGYDDURXY9p_:-N-XSe30DGYDDURXY9pa:b-lv4slk) ([raw file](https://github.com/harness/harness-core/blob/a79b80102aed2b0ebc240e561bb0ade7865485e9/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java#L465)):*
> ```Java
>       AwsS3FetchFilesResponse responseData) {
>     Set<String> identifiers = cloudFormationCreateStackPassThroughData.getParametersFilesContent().keySet();
>     Map<String, List<S3FileDetailResponse>> s3Files = responseData.getS3filesDetails();
> ```

we don't need a new variable here.
"identifier" is more meaningful than "s"
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java, line 483 at r1](https://reviewable.io/reviews/harness/harness-core/32228#-N-XT9GC5T3iOzOAgp8J:-N-XT9GC5T3iOzOAgp8K:bqj4tsg) ([raw file](https://github.com/harness/harness-core/blob/a79b80102aed2b0ebc240e561bb0ade7865485e9/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java#L483)):*
> ```Java
> 
>     CloudformationTemplateFileSpec cloudformationTemplateFileSpec = stepConfiguration.getTemplateFile().getSpec();
>     if (s3Files.get(TEMPLATE_FILE_IDENTIFIER) != null) {
> ```

we will never download template from s3.   If ```isNotEmpty(cloudFormationCreateStackPassThroughData.getTemplateBody())``` that means it was downloaded previously from git and we have to take it from cloudFormationCreateStackPassThroughData.
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/CDStepHelperTest.java, line 119 at r1](https://reviewable.io/reviews/harness/harness-core/32228#-N-XV3u81g4XGxyxfYYJ:-N-XV3u81g4XGxyxfYYK:b-kgpoxp) ([raw file](https://github.com/harness/harness-core/blob/a79b80102aed2b0ebc240e561bb0ade7865485e9/125-cd-nextgen/src/test/java/io/harness/cdng/CDStepHelperTest.java#L119)):*
> ```Java
>   public void setup() {
>     initMocks(this);
>   }
> ```

add empty line.
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStepInfoTest.java, line 36 at r1](https://reviewable.io/reviews/harness/harness-core/32228#-N-XVgOB85c1OHDgaTXt:-N-XVgOC1Gn7FqEYWci0:b-t7zs86) ([raw file](https://github.com/harness/harness-core/blob/a79b80102aed2b0ebc240e561bb0ade7865485e9/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStepInfoTest.java#L36)):*
> ```Java
>   @Owner(developers = NGONZALEZ)
>   @Category(UnitTests.class)
>   public void testValidateParamsWithNoSpecParameters() {
> ```

maybe that should be split in 2 tests, one which throws exception and one passing validation.
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStepTest.java, line 130 at r1](https://reviewable.io/reviews/harness/harness-core/32228#-N-XWHyY2BssUvxu2Nw8:-N-XWHyZ71BjyfiNIcAF:bvqc7g7) ([raw file](https://github.com/harness/harness-core/blob/a79b80102aed2b0ebc240e561bb0ade7865485e9/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStepTest.java#L130)):*
> ```Java
>     assertThat(entityDetails.get(1).getEntityRef().getIdentifier()).isEqualTo("test-connector");
>     assertThat(entityDetails.get(1).getEntityRef().getAccountIdentifier()).isEqualTo("test-account");
>   }
> ```

Please add empty line
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStepTest.java, line 167 at r1](https://reviewable.io/reviews/harness/harness-core/32228#-N-XWPD5BrMPFEi2PkFG:-N-XWPD5BrMPFEi2PkFH:bt006ng) ([raw file](https://github.com/harness/harness-core/blob/a79b80102aed2b0ebc240e561bb0ade7865485e9/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStepTest.java#L167)):*
> ```Java
>     assertThat(entityDetails.get(2).getEntityRef().getIdentifier()).isEqualTo("test-connector");
>     assertThat(entityDetails.get(2).getEntityRef().getAccountIdentifier()).isEqualTo("test-account");
>   }
> ```

empty line

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32228)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java, line 394 at r2](https://reviewable.io/reviews/harness/harness-core/32228#-N-XhM-E1RE4a9VLzL1b:-N-XhM-E1RE4a9VLzL1c:b-8vthq0) ([raw file](https://github.com/harness/harness-core/blob/a5332abdc083fa0595aed8a78765df33cb85bf5b/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java#L394)):*
> ```Java
> 
>   @NotNull
>   protected List<GitFetchFilesConfig> getParametersGitFetchFileConfigs(
> ```

Why did we make it protected?
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java, line 154 at r2](https://reviewable.io/reviews/harness/harness-core/32228#-N-XgaLMAeCPIZjUgdCc:-N-XgaLMAeCPIZjUgdCd:b-4sss1q) ([raw file](https://github.com/harness/harness-core/blob/a5332abdc083fa0595aed8a78765df33cb85bf5b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java#L154)):*
> ```Java
>   public void testStartChainLinkWithGit() {
>     StepElementParameters stepElementParameters = createStepParametersWithGit(false);
>     ConnectorInfoDTO connectorInfoDTO =
> ```

Would be more intuitive if we call them AwsConnectorDTO and GitConnectorDTO



_Code quote:_
```Java
 public void testStartChainLinkWithGit() {
```
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java, line 176 at r2](https://reviewable.io/reviews/harness/harness-core/32228#-N-XiEay5T30GYwfFmAw:-N-XiEay5T30GYwfFmAx:b-obzh0c) ([raw file](https://github.com/harness/harness-core/blob/a5332abdc083fa0595aed8a78765df33cb85bf5b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java#L176)):*
> ```Java
> 
>     PowerMockito.verifyStatic(StepUtils.class, times(1));
>     StepUtils.prepareCDTaskRequest(any(), taskDataArgumentCaptor.capture(), any(), any(), any(), any(), any());
> ```

Why do we need this ? we do nothing with the response.
If it it not required lets remove from other tests also.
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java, line 178 at r2](https://reviewable.io/reviews/harness/harness-core/32228#-N-Xhtn89nwnvlIVhCYC:-N-Xhtn89nwnvlIVhCYD:bxqis5u) ([raw file](https://github.com/harness/harness-core/blob/a5332abdc083fa0595aed8a78765df33cb85bf5b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java#L178)):*
> ```Java
>     StepUtils.prepareCDTaskRequest(any(), taskDataArgumentCaptor.capture(), any(), any(), any(), any(), any());
>     assertThat(taskDataArgumentCaptor.getValue()).isNotNull();
>     assertThat(taskDataArgumentCaptor.getValue().getParameters()).isNotNull();
> ```

Let's add some assertion of task parameters which in this case are an instance of GitFetchRequest.
let's do the same in other tests
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java, line 183 at r2](https://reviewable.io/reviews/harness/harness-core/32228#-N-XdGfIEleySt13zCfr:-N-XdGfIEleySt13zCfs:buquskm) ([raw file](https://github.com/harness/harness-core/blob/a5332abdc083fa0595aed8a78765df33cb85bf5b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java#L183)):*
> ```Java
>     assertThat(response.getPassThroughData()).isNotNull();
> 
>     StepElementParameters stepElementParametersWithTags = createStepParametersWithGit(true);
> ```

Let's try to test one scenario in one test and give it a meaningful name.
The same for tests below

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32228)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java, line 394 at r2](https://reviewable.io/reviews/harness/harness-core/32228#-N-XhM-E1RE4a9VLzL1b:-N-bSiBa06hHf2ymHR0J:b-7s6njt) ([raw file](https://github.com/harness/harness-core/blob/a5332abdc083fa0595aed8a78765df33cb85bf5b/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java#L394)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

To be able to access to it from the tests. I remember that I once used the @VisibleForTesting tag and you suggested to change the method to protected
</blockquote></details>

But we didn't add any test for it
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStepInfoTest.java, line 38 at r3](https://reviewable.io/reviews/harness/harness-core/32228#-N-bVQV10h9rpl_662tJ:-N-bVQV10h9rpl_662tK:bkymjw3) ([raw file](https://github.com/harness/harness-core/blob/99fbcdc9b2711a9637b48516fde12a4240e6e31c/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStepInfoTest.java#L38)):*
> ```Java
>   public void testValidateParamsWithNoSpecParameters() {
>     CloudformationCreateStackStepInfo cloudformationCreateStackStepInfo = new CloudformationCreateStackStepInfo();
>     Assertions.assertThatThrownBy(cloudformationCreateStackStepInfo::validateSpecParameters)
> ```

here we check that exception is thrown
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStepInfoTest.java, line 45 at r3](https://reviewable.io/reviews/harness/harness-core/32228#-N-bVTj40jJhfCFmqIyO:-N-bVTj40jJhfCFmqIyP:b-mbek4n) ([raw file](https://github.com/harness/harness-core/blob/99fbcdc9b2711a9637b48516fde12a4240e6e31c/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStepInfoTest.java#L45)):*
> ```Java
>             .connectorRef(ParameterField.createValueField("connectorRef"))
>             .build());
>     cloudformationCreateStackStepInfo.validateSpecParameters();
> ```

here that is pass
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java, line 178 at r2](https://reviewable.io/reviews/harness/harness-core/32228#-N-Xhtn89nwnvlIVhCYC:-N-bZ46Y2pzP1Yyeq_jY:b-i3hz2a) ([raw file](https://github.com/harness/harness-core/blob/a5332abdc083fa0595aed8a78765df33cb85bf5b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java#L178)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

I may be wrong here but parameters is going to be instance of object no? Unless you want to test that from object i can cast it to GitFetchRequest and check that (I'm actually going with that and perform the check in the cast and if that is not what you were looking for, we can change it later)
</blockquote></details>

yes, we know that it should be an instance of GitFetchRequest but would be good to check if it has the correct fields.
The same is applicable for other tests
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java, line 187 at r3](https://reviewable.io/reviews/harness/harness-core/32228#-N-b_0Xd2TjHxTW7kD9B:-N-bZ1tB5lZFGX9Xfp2i:b1irkk7) ([raw file](https://github.com/harness/harness-core/blob/99fbcdc9b2711a9637b48516fde12a4240e6e31c/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java#L187)):*
> ```Java
>     assertThat(response.getTaskRequest()).isNotNull();
>     assertThat(response.getPassThroughData()).isNotNull();
>   }
> ```

please add empty line

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32228)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java, line 394 at r2](https://reviewable.io/reviews/harness/harness-core/32228#-N-XhM-E1RE4a9VLzL1b:-N0-xAaW31PX7mdHQdrS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5332abdc083fa0595aed8a78765df33cb85bf5b/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java#L394)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

But we didn't add any test for it
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStepInfoTest.java, line 36 at r1](https://reviewable.io/reviews/harness/harness-core/32228#-N-XVgOB85c1OHDgaTXt:-N00-VkbCDWmdqrCtXiR:b-q8ilnv) ([raw file](https://github.com/harness/harness-core/blob/a79b80102aed2b0ebc240e561bb0ade7865485e9/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStepInfoTest.java#L36)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

I don't understand, This test doesn't throws exceptions :S
</blockquote></details>

gotcha
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStepInfoTest.java, line 38 at r3](https://reviewable.io/reviews/harness/harness-core/32228#-N-bVQV10h9rpl_662tJ:-N00-_zl63szh9XDSgY9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/99fbcdc9b2711a9637b48516fde12a4240e6e31c/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStepInfoTest.java#L38)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

here we check that exception is thrown
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStepInfoTest.java, line 45 at r3](https://reviewable.io/reviews/harness/harness-core/32228#-N-bVTj40jJhfCFmqIyO:-N00-hN93wFhIY58npup:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/99fbcdc9b2711a9637b48516fde12a4240e6e31c/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStepInfoTest.java#L45)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

here that is pass
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java, line 178 at r2](https://reviewable.io/reviews/harness/harness-core/32228#-N-Xhtn89nwnvlIVhCYC:-N008v_A4QzBNTsrduIV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5332abdc083fa0595aed8a78765df33cb85bf5b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java#L178)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

yes, we know that it should be an instance of GitFetchRequest but would be good to check if it has the correct fields.
The same is applicable for other tests
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java, line 187 at r3](https://reviewable.io/reviews/harness/harness-core/32228#-N-b_0Xd2TjHxTW7kD9B:-N0093yp374u3E-7MtVm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/99fbcdc9b2711a9637b48516fde12a4240e6e31c/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java#L187)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

please add empty line
</blockquote></details>

Done.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32228)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32228)* status: :shipit: complete! ✓

**Pull request merged**
