### PR TITLE
fix: [CDS-68144]: pass context correctly from user SCM service to git service

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Issue:** Context was getting lost when grpc call was made from ng manager to git sync service

**Changes:** Added principal in the object of grpc request and setting context in git sync service

**Testing:** Tested locally and in PR env that context was correctly set in git sync service.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47075)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger ut6, ut7, ut8, ut9, ut0, ut3, messagecheck

**Comment by shalini-agr** [comment]
trigger messgecheck

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47075)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger ut2

**Comment by shalini-agr** [comment]
trigger ut0, ut5, ut6

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 191 at r4](https://reviewable.io/reviews/harness/harness-core/47075#-NU5a72b1RItvsdk1wSy:-NU5a72b1RItvsdk1wSz:bwpbdcy) ([raw file](https://github.com/harness/harness-core/blob/b2ba536eaeccc8efffc75d8ff0dbce900b01db61/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L191)):*
> ```Java
>          MdcContextSetter ignore1 = new MdcContextSetter(contextMap)) {
>       setPrincipal(request.getAccountIdentifier(), request.getPrincipal());
>       log.info(String.format("%s Grpc request received for getUserDetails ops %s", GIT_SERVICE, request));
> ```

put this logline before setting principal. We don't want to miss out on logging request in any case such that where setting principal may cause some issue.

**Comment by mohitg0795** [comment]
*[`980-commons/src/main/java/io/harness/security/PrincipalProtoMapper.java` line 67 at r4](https://reviewable.io/reviews/harness/harness-core/47075#-NU5abpd-T_NyRkJ9-LX:-NU5abpd-T_NyRkJ9-LY:b2qrpvb) ([raw file](https://github.com/harness/harness-core/blob/b2ba536eaeccc8efffc75d8ff0dbce900b01db61/980-commons/src/main/java/io/harness/security/PrincipalProtoMapper.java#L67)):*
> ```Java
>           .build();
>     }
>     log.error("The principal DTO request is {}", principalDto);
> ```

- This logline should be improved. It doesn't mention anything about the error, looks pretty generic.
- Can we just confirm once if it logs out principalDTO correctly? Sometime it just logs class name or other redundant identifiers without logging the actual required data.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47075)* status: 6 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 191 at r4](https://reviewable.io/reviews/harness/harness-core/47075#-NU5a72b1RItvsdk1wSy:-NU5lKrfB37sH1McbK2F:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b2ba536eaeccc8efffc75d8ff0dbce900b01db61/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L191)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

put this logline before setting principal. We don't want to miss out on logging request in any case such that where setting principal may cause some issue.
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/security/PrincipalProtoMapper.java` line 67 at r4](https://reviewable.io/reviews/harness/harness-core/47075#-NU5abpd-T_NyRkJ9-LX:-NU5oI144dt9F_5oEiFi:b-u9gnp3) ([raw file](https://github.com/harness/harness-core/blob/b2ba536eaeccc8efffc75d8ff0dbce900b01db61/980-commons/src/main/java/io/harness/security/PrincipalProtoMapper.java#L67)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

- This logline should be improved. It doesn't mention anything about the error, looks pretty generic.
- Can we just confirm once if it logs out principalDTO correctly? Sometime it just logs class name or other redundant identifiers without logging the actual required data.
</blockquote></details>

it logs the class name only

**Comment by mohitg0795** [comment]
*[`980-commons/src/main/java/io/harness/security/PrincipalProtoMapper.java` line 67 at r4](https://reviewable.io/reviews/harness/harness-core/47075#-NU5abpd-T_NyRkJ9-LX:-NU66zTxElIqJzXtIId4:b-nmknjg) ([raw file](https://github.com/harness/harness-core/blob/b2ba536eaeccc8efffc75d8ff0dbce900b01db61/980-commons/src/main/java/io/harness/security/PrincipalProtoMapper.java#L67)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

it logs the class name only
</blockquote></details>

Yes, so we need to fix it. No point of this log then.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47075)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/security/PrincipalProtoMapper.java` line 67 at r4](https://reviewable.io/reviews/harness/harness-core/47075#-NU5abpd-T_NyRkJ9-LX:-NU69Jj30engJONDBHRD:b-aq2hl2) ([raw file](https://github.com/harness/harness-core/blob/b2ba536eaeccc8efffc75d8ff0dbce900b01db61/980-commons/src/main/java/io/harness/security/PrincipalProtoMapper.java#L67)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Yes, so we need to fix it. No point of this log then.
</blockquote></details>

logging only principal type

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47075)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]
io.harness.security.* 

Update the import to classnames instead of * in next PR

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
