### PR TITLE
feat: [PL-31752]: Enhance the HTTP error handling for NGRestUtils

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

This PR enhances the HTTP Error handling for NGRestUtils. It processes the HTTP error status code received then sets the appropriate error code for the InvalidRequest exception and provides a corresponding error message.

Created a separate PR (https://github.com/harness/harness-core/pull/46032) to push the error codes before this PR is pushed.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45390)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45390)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java` line 210 at r1](https://reviewable.io/reviews/harness/harness-core/45390#-NR1hsZS2pip1cNjgf7v:-NR1hsZS2pip1cNjgf7w:b6t3lbw) ([raw file](https://github.com/harness/harness-core/blob/9fd45f0940a235a08dfc585caa902e2d9215bd9f/970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java#L210)):*
> ```Java
>     switch (code) {
>       case HTTP_STATUS_400:
>         errorCode = ErrorCode.INVALID_FORMAT;
> ```

Shall we remove HTTP_ prefix from error codes for consistency? 
___
*[`970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java` line 244 at r1](https://reviewable.io/reviews/harness/harness-core/45390#-NR1i5KRAKzWI7VtWDaR:-NR1i5KRAKzWI7VtWDaS:busb14n) ([raw file](https://github.com/harness/harness-core/blob/9fd45f0940a235a08dfc585caa902e2d9215bd9f/970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java#L244)):*
> ```Java
>         if (code >= 400 && code < 500) {
>           errorCode = ErrorCode.HTTP_CLIENT_ERROR_RESPONSE;
>           errorMessage = "HTTP Error Status (4xx - Client Error Response) received.";
> ```

Shall we put the code in the msg here for completeness?
___
*[`970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java` line 247 at r1](https://reviewable.io/reviews/harness/harness-core/45390#-NR1i9PF-wMdxFG81MzD:-NR1i9PF-wMdxFG81MzE:busb14n) ([raw file](https://github.com/harness/harness-core/blob/9fd45f0940a235a08dfc585caa902e2d9215bd9f/970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java#L247)):*
> ```Java
>         } else if (code >= 500) {
>           errorCode = ErrorCode.HTTP_SERVER_ERROR_RESPONSE;
>           errorMessage = "HTTP Error Status (5xx - Server Error Response) received.";
> ```

Shall we put the code in the msg here for completeness?
___
*[`980-commons/src/main/java/io/harness/eraro/ErrorCode.java` line 670 at r1](https://reviewable.io/reviews/harness/harness-core/45390#-NR1idrG-xPuQvl1hUff:-NR1idrG-xPuQvl1hUfg:b2oyzqv) ([raw file](https://github.com/harness/harness-core/blob/9fd45f0940a235a08dfc585caa902e2d9215bd9f/980-commons/src/main/java/io/harness/eraro/ErrorCode.java#L670)):*
> ```Java
>   SCM_FORBIDDEN,
> 
>   HTTP_CLIENT_ERROR_RESPONSE,
> ```

I think first we have may to introduce just error codes and once that is released, make changes to NGRestUtils. Reason - Services are independently deployed. So some services will have this new class and some not. So InvalidRequestException de-serialization may fail on those services

**Comment by mohitg0795** [comment]
*[`970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/45390#-NR4n6o92S77JzmU2eMZ:-NR4n6o92S77JzmU2eM_:b-u4lrf0) ([raw file](https://github.com/harness/harness-core/blob/9fd45f0940a235a08dfc585caa902e2d9215bd9f/970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java#L40)):*
> ```Java
> public class NGRestUtils {
>   private static final int MAX_ATTEMPTS = 3;
>   private static final int HTTP_STATUS_400 = 400;
> ```

Can we check if this is available from some standard lib or we can move this to a separate ENUM that everyone else can also use wherever they need to refer HTTP status codes?

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45390)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/45390#-NR4n6o92S77JzmU2eMZ:-NS85N0c4ppidaSCvcbT:b85hu8h) ([raw file](https://github.com/harness/harness-core/blob/9fd45f0940a235a08dfc585caa902e2d9215bd9f/970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java#L40)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can we check if this is available from some standard lib or we can move this to a separate ENUM that everyone else can also use wherever they need to refer HTTP status codes?
</blockquote></details>

Yes, there is apache commons library for this. I will update it.
___
*[`970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java` line 120 at r1](https://reviewable.io/reviews/harness/harness-core/45390#-NR4nwY9DNtFjnxYxBui:-NS87jF23uornIPtmW8Y:b-onmvc0) ([raw file](https://github.com/harness/harness-core/blob/9fd45f0940a235a08dfc585caa902e2d9215bd9f/970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java#L120)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we should avoid passing null for metadata here. We can create another method which just takes 2 required arguments and internally we can call the original method with empty metadata object to keep it simple and clean.
eg: buildErrorResponse(httpStatus, errorMessage) {
             return buildErrorResponse(Metadata.builder.build(), httpStatus, errorMessage);
       }
</blockquote></details>

Actually Metadata here is an interface and thus we need define all its methods. Actually in the existing WingsException we already do have a constructor that sets null for Metadata. So passing null from here should be fine.
___
*[`970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java` line 210 at r1](https://reviewable.io/reviews/harness/harness-core/45390#-NR1hsZS2pip1cNjgf7v:-NS88GGE0LWOZenRGWDC:b-tddxf) ([raw file](https://github.com/harness/harness-core/blob/9fd45f0940a235a08dfc585caa902e2d9215bd9f/970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java#L210)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Shall we remove HTTP_ prefix from error codes for consistency? 
</blockquote></details>

Done, replaced the custom defined constants for Apache lib constants which doesn't have this prefix.
___
*[`970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java` line 213 at r1](https://reviewable.io/reviews/harness/harness-core/45390#-NR4p6x29bz1vmBpGQ1a:-NS891MRBP5-r0Ixzq7s:b-s3li85) ([raw file](https://github.com/harness/harness-core/blob/9fd45f0940a235a08dfc585caa902e2d9215bd9f/970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java#L213)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

don't you think this complete switch block can move to a separate helper method thats focussed on this mapping. That mapping can be used at different places as well.
We can just call the helper here and fetch error code and error message.
</blockquote></details>

I thought of having this method itself as the helper method that can be used at other places. If we move the switch block then the whole function has to be moved because in the switch block we are filling the 2 local vars declared.
___
*[`970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java` line 244 at r1](https://reviewable.io/reviews/harness/harness-core/45390#-NR1i5KRAKzWI7VtWDaR:-NS89xn83NrDHI4ZCm_D:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9fd45f0940a235a08dfc585caa902e2d9215bd9f/970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java#L244)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Shall we put the code in the msg here for completeness?
</blockquote></details>

Done
___
*[`970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java` line 247 at r1](https://reviewable.io/reviews/harness/harness-core/45390#-NR1i9PF-wMdxFG81MzD:-NS89ycHBuCDkcAIuinF:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9fd45f0940a235a08dfc585caa902e2d9215bd9f/970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java#L247)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Shall we put the code in the msg here for completeness?
</blockquote></details>

Done
___
*[`980-commons/src/main/java/io/harness/eraro/ErrorCode.java` line 670 at r1](https://reviewable.io/reviews/harness/harness-core/45390#-NR1idrG-xPuQvl1hUff:-NS8A3i9E9Wt7wVI5fCD:bdw8ven) ([raw file](https://github.com/harness/harness-core/blob/9fd45f0940a235a08dfc585caa902e2d9215bd9f/980-commons/src/main/java/io/harness/eraro/ErrorCode.java#L670)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I think first we have may to introduce just error codes and once that is released, make changes to NGRestUtils. Reason - Services are independently deployed. So some services will have this new class and some not. So InvalidRequestException de-serialization may fail on those services 
</blockquote></details>

Ah I see, thanks for letting me know about it. I will raise a separate PR for Error codes and merge it before this one.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45390#-:-NTRdl6p-IGgHXBLqHDz:bnfp4nl)* status: Some of the checks are too old. 3 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained.

**Comment by Raghav-Murali** [comment]
trigger uts

**Comment by Raghav-Murali** [comment]
trigger utAll

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45390)* status: 3 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45390#-:-NV3GRTc7kLDno8QbAzB:bnfp4nl)* status: 3 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45390)* status: :shipit: complete! ✓

**Pull request merged**
