### PR TITLE
feat: [PIE-4674]: Support of objects in matrix

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36029)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 10 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 8 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36029)

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, 12 of 13 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36029)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/strategy/MatrixConfig.java` line 57 at r3](https://reviewable.io/reviews/harness/harness-core/36029#-N8gMpym1vPQVWSBRYlX:-N8gMpym1vPQVWSBRYlY:bqjix7l) ([raw file](https://github.com/harness/harness-core/blob/48f61fcf48ae30551c8c7c4e33e980b51adbacbd/953-yaml-commons/src/main/java/io/harness/plancreator/strategy/MatrixConfig.java#L57)):*
> ```Java
>   String uuid;
> 
>   // This stores normal primitive key/value pair defined as axis in matrix
> ```

nit: it stored both primitive and complex value right?



_Code quote:_
```Java
primitive
```
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 295 at r3](https://reviewable.io/reviews/harness/harness-core/36029#-N8gN2g54NPZ9FYKfMGO:-N8gN2g54NPZ9FYKfMGP:b-kgqijz) ([raw file](https://github.com/harness/harness-core/blob/48f61fcf48ae30551c8c7c4e33e980b51adbacbd/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L295)):*
> ```Java
>         for (Map.Entry<String, String> entry : matrixMapLocal.entrySet()) {
>           try {
>             objectMap.put(entry.getKey(), JsonUtils.asMap(entry.getValue()));
> ```

nit: can you add comment that you are trying to convert json back to map, if failed then it means its a string thus handled exception



_Code quote:_
```Java
JsonUtils.asMap
```
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigService.java` line 107 at r3](https://reviewable.io/reviews/harness/harness-core/36029#-N8gNGEC8Re1vVAdr4tg:-N8gNGEC8Re1vVAdr4th:b-n3a4l1) ([raw file](https://github.com/harness/harness-core/blob/48f61fcf48ae30551c8c7c4e33e980b51adbacbd/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigService.java#L107)):*
> ```Java
>    *
>    * @param currentCombinationRef - Reference variable to store the current combination
>    * @param primitiveAxes - The axes defined in the yaml
> ```

now primitiveAxes name could be generic
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigService.java` line 108 at r3](https://reviewable.io/reviews/harness/harness-core/36029#-N8gNEPX6on5QBdDTFGY:-N8gNEPX6on5QBdDTFGZ:b-gnui5b) ([raw file](https://github.com/harness/harness-core/blob/48f61fcf48ae30551c8c7c4e33e980b51adbacbd/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigService.java#L108)):*
> ```Java
>    * @param currentCombinationRef - Reference variable to store the current combination
>    * @param primitiveAxes - The axes defined in the yaml
>    * @param complexAxes - The axes defined in the yaml
> ```

there is no complexAxes now



_Code quote:_
```Java
@param complexAxes - The axes defined in the yaml
```
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigService.java` line 138 at r3](https://reviewable.io/reviews/harness/harness-core/36029#-N8gNLz95_FuW1dr51Hl:-N8gNLz95_FuW1dr51Hm:b-1u3nn4) ([raw file](https://github.com/harness/harness-core/blob/48f61fcf48ae30551c8c7c4e33e980b51adbacbd/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigService.java#L138)):*
> ```Java
>      * 1. If a key is present in primitiveAxes then we will treat value for this key as primitive
>      * 2. If a key is present in complexAxes then we will treat value for this key as complex
>      * 3.If a key is present in expressionAxes then it can be either the string or the object that is stored as value
> ```

These comments could change, right?



_Code quote:_
```Java
     * 1. If a key is present in primitiveAxes then we will treat value for this key as primitive
     * 2. If a key is present in complexAxes then we will treat value for this key as complex
     * 3.If a key is present in expressionAxes then it can be either the string or the object that is stored as value
```
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigService.java` line 171 at r3](https://reviewable.io/reviews/harness/harness-core/36029#-N8gNZqO1bP3yfdhufFU:-N8gNZqO1bP3yfdhufFV:b-4ip6oz) ([raw file](https://github.com/harness/harness-core/blob/48f61fcf48ae30551c8c7c4e33e980b51adbacbd/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigService.java#L171)):*
> ```Java
>   }
> 
>   private void handlePrimitive(String key, Map<String, String> currentCombinationRef,
> ```

primitive word can be remove now places



_Code quote:_
```Java
handlePrimitive
```

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 2 of 9 files at r1, 12 of 13 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36029)* status: 1 change requests. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigService.java` line 107 at r3](https://reviewable.io/reviews/harness/harness-core/36029#-N8gNGEC8Re1vVAdr4tg:-N8h1dfR84sXZzdJTIQ5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/48f61fcf48ae30551c8c7c4e33e980b51adbacbd/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigService.java#L107)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

now primitiveAxes name could be generic
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigService.java` line 108 at r3](https://reviewable.io/reviews/harness/harness-core/36029#-N8gNEPX6on5QBdDTFGY:-N8h1ehS173P4Grn5dT5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/48f61fcf48ae30551c8c7c4e33e980b51adbacbd/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigService.java#L108)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

there is no complexAxes now
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigService.java` line 138 at r3](https://reviewable.io/reviews/harness/harness-core/36029#-N8gNLz95_FuW1dr51Hl:-N8h1feU7nqG70ljRsha:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/48f61fcf48ae30551c8c7c4e33e980b51adbacbd/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigService.java#L138)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

These comments could change, right?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigService.java` line 171 at r3](https://reviewable.io/reviews/harness/harness-core/36029#-N8gNZqO1bP3yfdhufFU:-N8h1gRQDi2JuaYCUq5F:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/48f61fcf48ae30551c8c7c4e33e980b51adbacbd/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigService.java#L171)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

primitive word can be remove now places
</blockquote></details>

Done.

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36029)* status: 3 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36029)* status: :shipit: complete! ✓

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36029)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36029)* status: :shipit: complete! ✓

**Pull request merged**
