### PR TITLE
fix: [CI-7002]: Remove variable response from CIStageVariableCreator

### PR DESCRIPTION
**Pull request by smjt-h**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43890)

### CODE REVIEW

**Comment by smjt-h** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43890)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`332-ci-manager/service/src/test/java/io/harness/ci/creator/variables/CIStageVariableCreatorTest.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/43890#-NODllAO1gHcGQ-bA3Fi:-NODllAO1gHcGQ-bA3Fj:br005c4) ([raw file](https://github.com/harness/harness-core/blob/d2d82ebf147f90bba5a31c0f860b01e238281e58/332-ci-manager/service/src/test/java/io/harness/ci/creator/variables/CIStageVariableCreatorTest.java#L76)):*
> ```Java
>                                .getNode()
>                                .getField("stages")
>                                .getNode()
> ```

can we check fqn value for variables as well?
___
*[`332-ci-manager/service/src/test/java/io/harness/ci/creator/variables/CIStageVariableCreatorTest.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/43890#-NODlkKEBUKtnN_SmmOh:-NODlkKEBUKtnN_SmmOi:b6p6ns2) ([raw file](https://github.com/harness/harness-core/blob/d2d82ebf147f90bba5a31c0f860b01e238281e58/332-ci-manager/service/src/test/java/io/harness/ci/creator/variables/CIStageVariableCreatorTest.java#L96)):*
> ```Java
>     //    }
> 
>     //    mYRt58hVTump7YOMGYGSxA
> ```

remove it



_Code quote:_
```Java
    //    for (Map.Entry<String, VariableCreationResponse> entry : responseMap.entrySet()) {
    //      String key = entry.getKey();
    //      VariableCreationResponse value = entry.getValue();
    //      assertThat(responseMap).isNotNull();
    //
    //      // now work with key and value...
    //    }

    //    mYRt58hVTump7YOMGYGSxA
```

**Comment by smjt-h** [comment]
> > Reviewed 1 of 2 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/43890)_ status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`332-ci-manager/service/src/test/java/io/harness/ci/creator/variables/CIStageVariableCreatorTest.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/43890#-NODllAO1gHcGQ-bA3Fi:-NODllAO1gHcGQ-bA3Fj:br005c4) ([raw file](https://github.com/harness/harness-core/blob/d2d82ebf147f90bba5a31c0f860b01e238281e58/332-ci-manager/service/src/test/java/io/harness/ci/creator/variables/CIStageVariableCreatorTest.java#L76)):_
> 
> > ```java
> >                                .getNode()
> >                                .getField("stages")
> >                                .getNode()
> > ```
> 
> can we check fqn value for variables as well?
> 
> _[`332-ci-manager/service/src/test/java/io/harness/ci/creator/variables/CIStageVariableCreatorTest.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/43890#-NODlkKEBUKtnN_SmmOh:-NODlkKEBUKtnN_SmmOi:b6p6ns2) ([raw file](https://github.com/harness/harness-core/blob/d2d82ebf147f90bba5a31c0f860b01e238281e58/332-ci-manager/service/src/test/java/io/harness/ci/creator/variables/CIStageVariableCreatorTest.java#L96)):_
> 
> > ```java
> >     //    }
> > 
> >     //    mYRt58hVTump7YOMGYGSxA
> > ```
> 
> remove it
> 
> _Code quote:_
> 
> ```java
>     //    for (Map.Entry<String, VariableCreationResponse> entry : responseMap.entrySet()) {
>     //      String key = entry.getKey();
>     //      VariableCreationResponse value = entry.getValue();
>     //      assertThat(responseMap).isNotNull();
>     //
>     //      // now work with key and value...
>     //    }
> 
>     //    mYRt58hVTump7YOMGYGSxA
> ```

uuid for Variables is not there in the object

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43890)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. Waiting on team(s): sto. 

___
*[`332-ci-manager/service/src/test/java/io/harness/ci/creator/variables/CIStageVariableCreatorTest.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/43890#-NODlkKEBUKtnN_SmmOh:-NODunIr84I8jBVmv-nD:b-r53n) ([raw file](https://github.com/harness/harness-core/blob/d2d82ebf147f90bba5a31c0f860b01e238281e58/332-ci-manager/service/src/test/java/io/harness/ci/creator/variables/CIStageVariableCreatorTest.java#L96)):*
<details><summary><i>Previously, smjt-h (Soumyajit Das) wrote…</i></summary><blockquote>

done
</blockquote></details>

please refer - ShellScriptStepVariableCreatorTest to add test for it

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43890)* status: Some of the checks are too old. Waiting on team(s): sto. 

___
*[`332-ci-manager/service/src/test/java/io/harness/ci/creator/variables/CIStageVariableCreatorTest.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/43890#-NODllAO1gHcGQ-bA3Fi:-NOhug25EXmsflbDJuPY:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/d2d82ebf147f90bba5a31c0f860b01e238281e58/332-ci-manager/service/src/test/java/io/harness/ci/creator/variables/CIStageVariableCreatorTest.java#L76)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we check fqn value for variables as well?
</blockquote></details>

done
___
*[`332-ci-manager/service/src/test/java/io/harness/ci/creator/variables/CIStageVariableCreatorTest.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/43890#-NODlkKEBUKtnN_SmmOh:-NOhufOm5t4Cq5aF34h6:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/d2d82ebf147f90bba5a31c0f860b01e238281e58/332-ci-manager/service/src/test/java/io/harness/ci/creator/variables/CIStageVariableCreatorTest.java#L96)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

please refer - ShellScriptStepVariableCreatorTest to add test for it
</blockquote></details>

done

**Pull request merged**
