### PR TITLE
fix: [DEL-3978]: Introducing watcher auth

### PR DESCRIPTION
**Pull request by gaurav-jain1**
Summary: As part of fetch watcher version per account from manager, we need to introduce new
auth which can easily be generated by various mechanism. As part of this changeset, introducing HMAC based
256bit encrypted auth filter, used by scripts (or watcher) for communicating with Manager.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32813)

### CODE REVIEW

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32813)* status: :shipit: complete! ✓

**Comment by gaurav-jain1** [comment]
trigger compile

**Comment by gaurav-jain1** [comment]
trigger codebasehash

**Review by arpit3107 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32813)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 156 at r3](https://reviewable.io/reviews/harness/harness-core/32813#-N1qvsc-3bMxTRZxlHCc:-N1qvsc0BTmd9kAFPcT1:b67ysmq) ([raw file](https://github.com/harness/harness-core/blob/f4ac96071e1629103fd12f21070e7ac61d597aa4/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L156)):*
> ```Java
>     try {
>       Algorithm algorithm = Algorithm.HMAC256(accountKey);
>       JWTVerifier verifier = JWT.require(algorithm).withSubject(accountId).build();
> ```

Why are you always verifying it with accountKey. Watcher can also use delegate token in-place of accountKey.

And with delegateToken, i think you can now implement it to always iterate on db and look for active tokens only.



_Code quote:_
```Java
      Algorithm algorithm = Algorithm.HMAC256(accountKey);
      JWTVerifier verifier = JWT.require(algorithm).withSubject(accountId).build();
      verifier.verify(tokenString);
```
___
*[`400-rest/src/main/java/software/wings/security/AuthenticationFilter.java` line 418 at r3](https://reviewable.io/reviews/harness/harness-core/32813#-N1qvFLN2OrVbiiOkS4_:-N1qvFLN2OrVbiiOkS4a:bq4q3s8) ([raw file](https://github.com/harness/harness-core/blob/f4ac96071e1629103fd12f21070e7ac61d597aa4/400-rest/src/main/java/software/wings/security/AuthenticationFilter.java#L418)):*
> ```Java
>       if (authHeader != null && authHeader.contains("Delegate")) {
>         authService.validateDelegateToken(
>             accountId, substringAfter(containerRequestContext.getHeaderString(HttpHeaders.AUTHORIZATION), "Watcher "));
> ```

instead of this  "Watcher  ", it should be "Delegate " since you will be sending delegateToken in name of delegate only. Even though only watcher will be sending this. 



_Code quote:_
```Java
accountId, substringAfter(containerRequestContext.getHeaderString(HttpHeaders.AUTHORIZATION), "Watcher "));
```
___
*[`400-rest/src/main/java/software/wings/security/AuthRuleFilter.java` line 704 at r3](https://reviewable.io/reviews/harness/harness-core/32813#-N1qwZG58dnrFInShPon:-N1qwZG58dnrFInShPoo:b-wenj9c) ([raw file](https://github.com/harness/harness-core/blob/f4ac96071e1629103fd12f21070e7ac61d597aa4/400-rest/src/main/java/software/wings/security/AuthRuleFilter.java#L704)):*
> ```Java
>     return resourceMethod.getAnnotation(DelegateAuth.class) != null
>         || resourceClass.getAnnotation(DelegateAuth.class) != null
>         || resourceMethod.getAnnotation(io.harness.security.annotations.DelegateAuth2.class) != null
> ```

instead create a new method isDelegateAuthV2() , just like you did in other class. And currently make sure, that only specific watcher apis are annotated with DelegateAuthV2.

later, I will apply this to all delegate apis also.



_Code quote:_
```Java
        || resourceMethod.getAnnotation(io.harness.security.annotations.DelegateAuth2.class) != null
        || resourceClass.getAnnotation(io.harness.security.annotations.DelegateAuth2.class) != null;
```

**Review by arpit3107 — COMMENTED** [review]
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32813)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by arpit3107 — APPROVED** [review]
> Reviewed 2 of 8 files at r2, 5 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32813)* status: :shipit: complete! ✓

**Comment by gaurav-jain1** [comment]
trigger codeformat

**Pull request merged**
