### PR TITLE
feat: [PL-27980]: add whitelist cache removal api

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37234)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37234)

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37234)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/WhitelistResource.java` line 212 at r2](https://reviewable.io/reviews/harness/harness-core/37234#-NBJWkuv8bM_GtFNXHJV:-NBJWkuv8bM_GtFNXHJW:b-d00m1r) ([raw file](https://github.com/harness/harness-core/blob/1d0aec8bf44b97fe5dca29da7fa3a99540f06726/400-rest/src/main/java/software/wings/resources/WhitelistResource.java#L212)):*
> ```Java
>     }
>     if (harnessUserGroupService.isHarnessSupportUser(existingUser.getUuid())) {
>       whitelistService.evictWhitelistConfigCache(accountId);
> ```

return early if not a support user; reduces indentation.
 
````
if (!harnessUserGroupService.isHarnessSupportUser(existingUser.getUuid())) {
     return RestResponse.Builder.aRestResponse()
          .withResponseMessages(
              Lists.newArrayList(ResponseMessage.builder().message("User not allowed to reset cache").build()))
          .build();      
}

whitelistService.evictWhitelistConfigCache(accountId);
log.info("Reset cache successful for account id {}", accountId);
return new RestResponse<>(Boolean.TRUE);
````



_Code quote:_
```Java
    if (harnessUserGroupService.isHarnessSupportUser(existingUser.getUuid())) {
      whitelistService.evictWhitelistConfigCache(accountId);
      log.info("Reset cache successful for account id {}", accountId);
      return new RestResponse<>(Boolean.TRUE);
    } else {
      return RestResponse.Builder.aRestResponse()
          .withResponseMessages(
              Lists.newArrayList(ResponseMessage.builder().message("User not allowed to reset cache").build()))
          .build();
    }
```

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37234)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/WhitelistResource.java` line 212 at r2](https://reviewable.io/reviews/harness/harness-core/37234#-NBJWkuv8bM_GtFNXHJV:-NBJ_NXmCjHhEfQoQ4oA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1d0aec8bf44b97fe5dca29da7fa3a99540f06726/400-rest/src/main/java/software/wings/resources/WhitelistResource.java#L212)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

return early if not a support user; reduces indentation.
 
````
if (!harnessUserGroupService.isHarnessSupportUser(existingUser.getUuid())) {
     return RestResponse.Builder.aRestResponse()
          .withResponseMessages(
              Lists.newArrayList(ResponseMessage.builder().message("User not allowed to reset cache").build()))
          .build();      
}

whitelistService.evictWhitelistConfigCache(accountId);
log.info("Reset cache successful for account id {}", accountId);
return new RestResponse<>(Boolean.TRUE);
````
</blockquote></details>

Done.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37234)* status: 4 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/WhitelistResource.java` line 64 at r3](https://reviewable.io/reviews/harness/harness-core/37234#-NBJbz_p1yCM3sZmAEqy:-NBJbz_p1yCM3sZmAEqz:b-hag9zb) ([raw file](https://github.com/harness/harness-core/blob/680dc452a2c8215aaddecbd9af77678fd0e5f9c1/400-rest/src/main/java/software/wings/resources/WhitelistResource.java#L64)):*
> ```Java
> public class WhitelistResource {
>   private WhitelistService whitelistService;
>   private HarnessUserGroupService harnessUserGroupService;
> ```

These two can be marked final



_Code quote:_
```Java
  private WhitelistService whitelistService;
  private HarnessUserGroupService harnessUserGroupService;
```

**Review by lasdox — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37234)* status: 4 file(s) to review. 1. unresolved discussions.

**Review by gn-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37234)* status: 4 file(s) to review.

**Review by gn-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37234)* status: :shipit: complete! ✓

**Pull request merged**
