### PR TITLE
feat: [CI-6813]: git status to stage

### PR DESCRIPTION
**Pull request by devkimittal**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42996)

### CODE REVIEW

**Comment by devkimittal** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/GitBuildStatusUtility.java` line 234 at r1](https://reviewable.io/reviews/harness/harness-core/42996#-NMZEsgf0lfL5orvsRvd:-NMZEsgf0lfL5orvsRve:b-bbazm) ([raw file](https://github.com/harness/harness-core/blob/000d7b4b44fe5d651094919545f3b9154c976e33/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/GitBuildStatusUtility.java#L234)):*
> ```Java
>     GitSCMType gitSCMType = retrieveSCMType(gitConnector);
> 
>     String stageSetupId = AmbianceUtils.getSetupIdForGivenCategory(ambiance, StepCategory.STAGE);
> ```

Why we are using stageSetupId here? Not have much context so could you please explain the reason?

**Comment by devkimittal** [comment]
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/GitBuildStatusUtility.java` line 234 at r1](https://reviewable.io/reviews/harness/harness-core/42996#-NMZEsgf0lfL5orvsRvd:-NMZFPr83qwu5ZkZ-fq_:b-4752pu) ([raw file](https://github.com/harness/harness-core/blob/000d7b4b44fe5d651094919545f3b9154c976e33/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/GitBuildStatusUtility.java#L234)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Why we are using stageSetupId here? Not have much context so could you please explain the reason?
</blockquote></details>

The link that we send back in status to scm, is redirecting us to pipeline instead of stage. There is a customer ask to https://harness.atlassian.net/browse/CI-6709 have it redirect to the specific stage. stageSetupid is the value that needs to be appended in the url.

**Comment by devkimittal** [comment]
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/GitBuildStatusUtility.java` line 234 at r1](https://reviewable.io/reviews/harness/harness-core/42996#-NMZEsgf0lfL5orvsRvd:-NMZGLEc-JAVlUcOt8JJ:b-8fpjd8) ([raw file](https://github.com/harness/harness-core/blob/000d7b4b44fe5d651094919545f3b9154c976e33/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/GitBuildStatusUtility.java#L234)):*
<details><summary><i>Previously, devkimittal (Dev Mittal) wrote…</i></summary><blockquote>

The link that we send back in status to scm, is redirecting us to pipeline instead of stage. There is a customer ask to https://harness.atlassian.net/browse/CI-6709 have it redirect to the specific stage. stageSetupid is the value that needs to be appended in the url.
</blockquote></details>

example pr using this setup https://bitbucket.org/devmittalciv16/ci_3446/pull-requests/23 
you can see setup id is used in url in ui

**Review by aman-harness — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42996#-:-NMcFxy53eaooJs-L2Vx:bnfp4nl)* status: 1. unresolved discussions.

**Comment by sahilhindwani-harness** [comment]
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/GitBuildStatusUtility.java` line 234 at r1](https://reviewable.io/reviews/harness/harness-core/42996#-NMZEsgf0lfL5orvsRvd:-NMcHhhM2rGAKosXB3mL:bepv5iz) ([raw file](https://github.com/harness/harness-core/blob/000d7b4b44fe5d651094919545f3b9154c976e33/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/GitBuildStatusUtility.java#L234)):*
<details><summary><i>Previously, devkimittal (Dev Mittal) wrote…</i></summary><blockquote>

example pr using this setup https://bitbucket.org/devmittalciv16/ci_3446/pull-requests/23 
you can see setup id is used in url in ui
</blockquote></details>

I think we will need executionId as well in the url. Could you please try with matrix once if the url generated is working?

**Comment by devkimittal** [comment]
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/GitBuildStatusUtility.java` line 234 at r1](https://reviewable.io/reviews/harness/harness-core/42996#-NMZEsgf0lfL5orvsRvd:-NMck5qCC45OcbFgEM45:bvjwbw6) ([raw file](https://github.com/harness/harness-core/blob/000d7b4b44fe5d651094919545f3b9154c976e33/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/GitBuildStatusUtility.java#L234)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think we will need executionId as well in the url. Could you please try with matrix once if the url generated is working?
</blockquote></details>

You are right, we need exec id as well in case of strategy on stage. will make the change, thanks.

**Pull request merged**
