### PR TITLE
techdebt: [PIE-3064]: Reduce number of orchestration_event emitted

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31418)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31418)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[870-orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java, line 84 at r1](https://reviewable.io/reviews/harness/harness-core/31418#-MyLNVlD7nKRXewoP1YZ:-MyLNVlD7nKRXewoP1Y_:b6qu8jr) ([raw file](https://github.com/harness/harness-core/blob/c9cdc36017809080197c99ea1376dc354b314a99/870-orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java#L84)):*
> ```Java
>           OrchestrationEvent.newBuilder()
>               .setAmbiance(ambiance)
>               .setEventType(OrchestrationEventType.ORCHESTRATION_START)
> ```

are we deleting this event all together?
If yes then we can delete even the proto type?



_Code quote:_
```Java
OrchestrationEventType.ORCHESTRATION_START
```

**Comment by sahilhindwani-harness** [comment]
___
*[870-orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java, line 84 at r1](https://reviewable.io/reviews/harness/harness-core/31418#-MyLNVlD7nKRXewoP1YZ:-MyLRPEC1XisSLd85eXr:b-ew1bw9) ([raw file](https://github.com/harness/harness-core/blob/c9cdc36017809080197c99ea1376dc354b314a99/870-orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java#L84)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

are we deleting this event all together?
If yes then we can delete even the proto type?
</blockquote></details>

We have removed it for now, but we might require it in the future therefore kept it as is in proto. We need to keep OrchestrationStart and OrchestrationEnd as they might be required in future.

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31418)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31418#-:-MyLVIUJ2DSU0r-kyqil:bnfp4nl)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31418)* status: :shipit: complete! ✓

**Pull request merged**
