### PR TITLE
DO_NOT_MERGE: [PL-29289]: Create separate module for 980-commons/exception

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes

NOTE: https://harness.atlassian.net/browse/PL-29380 was logged related to a recent change where we moved a class from package A to B. Kryo does not seem to like it

Create granular 980-commons/exception module. This required breaking a bunch of cycles, which led to files being moved around to folder leading to changes throughout the codebase. 

Other than the file moves in 980-commons, rest of the changes are trivial.

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39188)

### CODE REVIEW

**Review by mdmilic — APPROVED** [review]
> Reviewed 1986 of 1986 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39188)* status: 1986 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1908 of 1986 files at r1, 78 of 78 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39188)* status: 78 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by hitesharinga — APPROVED** [review]
> Reviewed 1908 of 1986 files at r1, 78 of 78 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39188)* status: Waiting on team(s): sto.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1908 of 1986 files at r1, 78 of 78 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39188)* status: Waiting on team(s): sto.

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 78 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39188)* status: Waiting on team(s): sto.

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39188)* status: Waiting on team(s): sto.

**Review by reetika04 — APPROVED** [review]
> Reviewed 1908 of 1986 files at r1, 78 of 78 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39188)* status: Waiting on team(s): sto.

**Review by r0610205 — APPROVED** [review]

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1908 of 1986 files at r1, 78 of 78 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39188)* status: :shipit: complete! ✓

**Comment by gn-harness** [comment]
trigger codebasehash

**Pull request closed without merging**
