### PR TITLE
fix: [CDS-40838]: handle cluster duplicate key err

### PR DESCRIPTION
**Pull request by GabeAboy**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36914)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36914)

**Review by rohitk-h — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36914)* status: :shipit: complete! ✓

**Comment by GabeAboy** [comment]
trigger pmd

**Comment by GabeAboy** [comment]
trigger pmd

**Comment by GabeAboy** [comment]
trigger ft1

**Comment by GabeAboy** [comment]
trigger ft2

**Comment by GabeAboy** [comment]
trigger ti4

**Comment by GabeAboy** [comment]
trigger ti3

**Comment by GabeAboy** [comment]
trigger ti2

**Comment by GabeAboy** [comment]
trigger ti4

**Comment by GabeAboy** [comment]
trigger compile

**Comment by GabeAboy** [comment]
trigger buildnum

**Comment by GabeAboy** [comment]
trigger recency

**Comment by GabeAboy** [comment]
trigger checkstyle

**Comment by GabeAboy** [comment]
trigger pmd

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36914)* status: :shipit: complete! ✓

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 223 at r4](https://reviewable.io/reviews/harness/harness-core/36914#-NAkCq15-XijYOjtPMjy:-NAkCq15-XijYOjtPMjz:b-22dfe9) ([raw file](https://github.com/harness/harness-core/blob/2bafbf9a125f27a4162e7fea3beb6e08db82a5b5/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L223)):*
> ```Java
>           getFetchFilesResult(gitOpsTaskParams.getGitFetchFilesConfig(), gitOpsTaskParams.getAccountId());
>       this.logCallback = markDoneAndStartNew(logCallback, UpdateFiles, commandUnitsProgress);
>       updateFiles(gitOpsTaskParams.getFilesToVariablesMap(), fetchFilesResult);
> ```

suggestion: we could extract the updateFiles out from this function. This way the logcallback also would be outside in the main `handleCreatePR`. Would help with readability and better code organization.

**Comment by GabeAboy** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 223 at r4](https://reviewable.io/reviews/harness/harness-core/36914#-NAkCq15-XijYOjtPMjy:-NAkEFYpBK88JBZnmzv8:b-65h9y5) ([raw file](https://github.com/harness/harness-core/blob/2bafbf9a125f27a4162e7fea3beb6e08db82a5b5/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L223)):*
> d extract the updateFiles out from this function. This way the logca
I have the updateFiles in here to only update when we find files from the repo

**Comment by GabeAboy** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 223 at r4](https://reviewable.io/reviews/harness/harness-core/36914#-NAkCq15-XijYOjtPMjy:-NAkELB81ZsnMr4Lk1oI:bskr54s) ([raw file](https://github.com/harness/harness-core/blob/2bafbf9a125f27a4162e7fea3beb6e08db82a5b5/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L223)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

> d extract the updateFiles out from this function. This way the logca
I have the updateFiles in here to only update when we find files from the repo
</blockquote></details>

In golang I would have this updateFiles out of this function, but I'm not sure how I can do what you are suggesting cleanly

**Comment by GabeAboy** [comment]
trigger ti0

**Comment by GabeAboy** [comment]
trigger ti1

**Comment by GabeAboy** [comment]
trigger ti0

**Comment by GabeAboy** [comment]
trigger recency

**Comment by GabeAboy** [comment]
trigger buildnum

**Pull request merged**
