### PR TITLE
[fix]: [PL-29702]: reduced skip index by 1 for SCIM GET APIs

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
reduced skip index by 1 for SCIM GET APIs

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40460)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/40460#-NHSheKz7mZvRngYtFv3:-NHSheKz7mZvRngYtFv4:bnuk66f) ([raw file](https://github.com/harness/harness-core/blob/dae75065dbda5936a0fabcdfca9ddda556417e91/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L114)):*
> ```Java
>       userGroupList = userGroupService.list(
>           Criteria.where(UserGroupKeys.accountIdentifier).is(accountId).and(UserGroupKeys.name).is(searchQuery),
>           startIndex - 1, count);
> ```

What happens when the `startIndex` is set to default value of 0? Did we test in that scenario?
Thanks



_Code quote:_
```Java
startIndex - 1
```

**Review by pbarapatre10 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40460)* status: 3 file(s) to review. 0 of 2 approvals obtained.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40460)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/40460#-NHSheKz7mZvRngYtFv3:-NHY53yV7FCeOo94chlN:b-s6adh5) ([raw file](https://github.com/harness/harness-core/blob/dae75065dbda5936a0fabcdfca9ddda556417e91/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L114)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

What happens when the `startIndex` is set to default value of 0? Did we test in that scenario?
Thanks
</blockquote></details>

This logic is changed, kindly have a look at this doc to know more about all the scenarios. https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21238218755/SCIM+APIs?NO_SSR=1

**Review by pbarapatre10 — APPROVED** [review]
:lgtm:
Make sure we get help from QA to test for other remaining provider as well once it goes to PreQA. Thanks 

> Reviewed 3 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40460#-:-NHYaV-sCHpZfZNhhVMx:bb3uj59)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 71 at r3](https://reviewable.io/reviews/harness/harness-core/40460#-NHdPJ5qBZRrKaKbFrtZ:-NHdPJ5qBZRrKaKbFrt_:b-5bzixw) ([raw file](https://github.com/harness/harness-core/blob/1a6a81b01ecc721f9401f92edd0888228562ce75/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L71)):*
> ```Java
>   @Override
>   public ScimListResponse<ScimGroup> searchGroup(String filter, String accountId, Integer count, Integer startIndex) {
>     startIndex = startIndex == null ? 0 : startIndex - 1;
> ```

This will change the startIndex in Response also.
We shouldn't do that.

If Okta sent startIndex=1 and we send it as 0, that might cause unknown behaviour.

Lets not touch Response and only touch our internal logic.
Use a temp variable for your internal logic.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40460)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java` line 71 at r3](https://reviewable.io/reviews/harness/harness-core/40460#-NHdPJ5qBZRrKaKbFrtZ:-NHdus0G6B1Tajw675hl:bhmbjuy) ([raw file](https://github.com/harness/harness-core/blob/1a6a81b01ecc721f9401f92edd0888228562ce75/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimGroupServiceImpl.java#L71)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

This will change the startIndex in Response also.
We shouldn't do that.

If Okta sent startIndex=1 and we send it as 0, that might cause unknown behaviour.

Lets not touch Response and only touch our internal logic.
Use a temp variable for your internal logic.
</blockquote></details>

Things were working fine even with this response.
However your point is very valid, so I have done the required changes.

**Review by pbarapatre10 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40460#-:-NHdzVy7CtF2eDYMaQpk:bnfp4nl)* status: 6 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by kapil-harness** [comment]
trigger ti1

**Review by shashank-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40460)* status: 1 file(s) to review.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40460)* status: :shipit: complete! ✓

**Pull request merged**
