### PR TITLE
fix: [CDS-40996]: Fix URLs returned in webhook/custom/v2 API

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes

This PR is to fix the already merged https://github.com/harness/harness-core/pull/36173. This will fix the URLs added to the custom webhook trigger response for production environments.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36758)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36758)

**Comment by vcalasansh** [comment]
trigger checkstyle

**Comment by vcalasansh** [comment]
trigger t1,t2,ti4,ti0

**Comment by vcalasansh** [comment]
trigger compile,pmd,ft2

**Comment by vcalasansh** [comment]
trigger ti0,ti1,ti2

**Comment by vcalasansh** [comment]
trigger ti0,ti1,ti4,ft1,ft2,compile

**Comment by vcalasansh** [comment]
trigger ti2,ti3

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36758)* status: :shipit: complete! ✓

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36758)* status: :shipit: complete! ✓

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/UrlHelper.java` line 41 at r3](https://reviewable.io/reviews/harness/harness-core/36758#-NANtOlk6SrEUDgVcE3F:-NANtOlk6SrEUDgVcE3G:b-rjwpzp) ([raw file](https://github.com/harness/harness-core/blob/d2014cd8754bfb9aa860336ba49df649120938a8/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/UrlHelper.java#L41)):*
> ```Java
>   public String buildUiUrl(
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, String pipelineIdentifier) {
>     return format("%s%s#/account/%s/cd/orgs/%s/projects/%s/deployments?pipelineIdentifier=%s&page=0",
> ```

nit, curious, why 0 page no.?

**Review by vcalasansh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36758)* status: 1. unresolved discussions. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/UrlHelper.java` line 41 at r3](https://reviewable.io/reviews/harness/harness-core/36758#-NANtOlk6SrEUDgVcE3F:-NAPF5Vf5atoXd50jd44:b-p7y038) ([raw file](https://github.com/harness/harness-core/blob/d2014cd8754bfb9aa860336ba49df649120938a8/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/UrlHelper.java#L41)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, curious, why 0 page no.?
</blockquote></details>

`page=1` doesn't render properly when there is only one page :sweat:

**Pull request merged**
