### PR TITLE
fix: [CDS-80246] Fix truncation logic for StrategyMetadata's identifierPostFix

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes
Currently, whenever we were generating the `identifierPostFix` for modifying stage names spawned under a strategy, we were truncating the final `identifierPostFix` to 126 characters. In case the matrix combinations (when converted to string), were bigger than 126 characters, we get issues with duplicated stage/stepGroup names. For example:

Each of these matrix combinations have 141 characters:
```
{"service":"DockerService","artifact":"gfgjhjh","tag":"v0.4","infraaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa":"infra1","envs":"testEnv01"}{"service":"DockerService","artifact":"gfgjhjh","tag":"v0.4","infraaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa":"infra1","envs":"testEnv02"}
```

Currently, these will generate the following duplicated `identifierPostFix`es:
```
___artifact___gfgjhjh___infraaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa___infra1___service___DockerService___tag___v04___test
___artifact___gfgjhjh___infraaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa___infra1___service___DockerService___tag___v04___test
```

After these changes, the `identifierPostFix`es will be:
```
___artifact___gfgjhjh___infraaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa___infra1___service___DockerService___tag___v04___test
___artifact___gfgjhjh___infraaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa___infra1___service___DockerService___tag___v04___te_0
```

Thus solving the duplicate stage/stepGroup identifiers issue.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55014)

### CODE REVIEW

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 1 of 4 files at r2, 20 of 20 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55014)* status: 22 file(s) to review. 1 of 2 approvals obtained.

**Comment by vcalasansh** [comment]
trigger uts

**Comment by vcalasansh** [comment]
trigger messagecheck

**Comment by vcalasansh** [comment]
Failed UTs are unrelated and I checked they are also failing in base develop branch:
```
/332-ci-manager/app:[io.harness.app](https://app.harness.io/ng/account/VRuJ8-dqQH6QZgAtoBr66g/ci/orgs/default/projects/PRCHECKS/pipelines/TIAll/executions/FalBlJ8gSnupPm80BZbIIA/io.harness.app).CIMongoIndexesTest                   FAILED in 48.9s
//clients/pipeline-service/pms-sdk-core:io.harness.pms.sdk.core.execution.invokers.AsyncChainStrategyTest FAILED in 31.7s
  /tmp/execroot/harness_monorepo/bazel-out/k8-fastbuild/testlogs/clients/pipeline-service/pms-sdk-core/io.harness.pms.sdk.core.execution.invokers.AsyncChainStrategyTest/test.log
//platform-service/modules/notification-service:io.harness.notification.service.NotificationServiceTest FAILED in 28.4s
  /tmp/execroot/harness_monorepo/bazel-out/k8-fastbuild/testlogs/platform-service/modules/notification-service/io.harness.notification.service.NotificationServiceTest/test.log
//srm-service/modules/cv-nextgen-service/service:[io.harness.cvng.cdng.services](https://app.harness.io/ng/account/VRuJ8-dqQH6QZgAtoBr66g/ci/orgs/default/projects/PRCHECKS/pipelines/TIAll/executions/FalBlJ8gSnupPm80BZbIIA/io.harness.cvng.cdng.services).impl.CVNGStepVariableCreatorTest FAILED in 99.0s
  /tmp/execroot/harness_monorepo/bazel-out/k8-fastbuild/testlogs/srm-service/modules/cv-nextgen-service/service/io.harness.cvng.cdng.services.impl.CVNGStepVariableCreatorTest/test.log
//125-cd-nextgen:io.harness.cdng.executables.CdAsyncChainExecutableTest  FAILED in 58.7s
  /tmp/execroot/harness_monorepo/bazel-out/k8-fastbuild/testlogs/125-cd-nextgen/io.harness.cdng.executables.CdAsyncChainExecutableTest/test.log
//clients/pipeline-service/pms-sdk-core:io.harness.pms.sdk.core.execution.invokers.AsyncStrategyTest FAILED in 7.3s
  /tmp/execroot/harness_monorepo/bazel-out/k8-fastbuild/testlogs/clients/pipeline-service/pms-sdk-core/io.harness.pms.sdk.core.execution.invokers.AsyncStrategyTest/test.log
//idp-service/src/test/java/io/harness/idp/envvariable:[io.harness.idp.envvariable.jobs](https://app.harness.io/ng/account/VRuJ8-dqQH6QZgAtoBr66g/ci/orgs/default/projects/PRCHECKS/pipelines/TIAll/executions/FalBlJ8gSnupPm80BZbIIA/io.harness.idp.envvariable.jobs).BackstageEnvVariablesSyncJobTest FAILED in 26.7s
  /tmp/execroot/harness_monorepo/bazel-out/k8-fastbuild/testlogs/idp-service/src/test/java/io/harness/idp/envvariable/io.harness.idp.envvariable.jobs.BackstageEnvVariablesSyncJobTest/test.log
//125-cd-nextgen:io.harness.cdng.executables.CdAsyncExecutableTest       FAILED in 53.2s
  /tmp/execroot/harness_monorepo/bazel-out/k8-fastbuild/testlogs/125-cd-nextgen/io.harness.cdng.executables.CdAsyncExecutableTest/test.log
//400-rest:[software.wings.sm](https://app.harness.io/ng/account/VRuJ8-dqQH6QZgAtoBr66g/ci/orgs/default/projects/PRCHECKS/pipelines/TIAll/executions/FalBlJ8gSnupPm80BZbIIA/software.wings.sm).states.spotinst.tests                       FAILED in 340.4s
  /tmp/execroot/harness_monorepo/bazel-out/k8-fastbuild/testlogs/400-rest/software.wings.sm.states.spotinst.tests/test.log
//332-ci-manager/app:[io.harness.app](https://app.harness.io/ng/account/VRuJ8-dqQH6QZgAtoBr66g/ci/orgs/default/projects/PRCHECKS/pipelines/TIAll/executions/FalBlJ8gSnupPm80BZbIIA/io.harness.app).yaml.YAMLTest                        FAILED in 51.2s
  /tmp/execroot/harness_monorepo/bazel-out/k8-fastbuild/testlogs/332-ci-manager/app/io.harness.app.yaml.YAMLTest/test.log
//srm-service/modules/cv-nextgen-service/service:io.harness.CVNGMorphiaRegistrarTest FAILED in 122.8s
  /tmp/execroot/harness_monorepo/bazel-out/k8-fastbuild/testlogs/srm-service/modules/cv-nextgen-service/service/io.harness.CVNGMorphiaRegistrarTest/test.log
```

**Review by Y0709 — DISMISSED** [review]

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55014)* status: Some of the checks are too old. 23 file(s) to review.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55014)* status: 23 file(s) to review. 1 of 2 approvals obtained.

**Review by Fernando-Dourado — APPROVED** [review]

**Comment by vcalasansh** [comment]
trigger review

**Pull request merged**
