### PR TITLE
feat: [CDS-80786]: Merge step group templates(v0/v1) in v1 pipelines

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** Add support for running v0 step group inside v1 pipeline and merging of v0/v1 step group templates in v1 pipelines.

**Testing:** Created and updated step group template v1 and ran locally, a v1 pipeline with v0/v1 step group templates.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54715)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger smartchecks

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger gitleaks

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54715)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54715)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54715)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54715)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54715)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java` line 94 at r3](https://reviewable.io/reviews/harness/harness-core/54715#-Ni4TdfW-Z3V8jP1mBBK:-Ni4TdfXEUwM59iIKGO8:b-4s2y25) ([raw file](https://github.com/harness/harness-core/blob/b4dadf385f0d9ec1aaf4b876a106c962fd5c92a2/960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java#L94)):*
> ```Java
>   public static TemplateEntityType getTemplateType(@JsonProperty("type") String yamlType) {
>     if (yamlType.equals("group")) {
>       return TemplateEntityType.STEPGROUP_TEMPLATE;
> ```

check to introduce const in same class

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54715)* status: Some of the checks are too old. 

___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java` line 94 at r3](https://reviewable.io/reviews/harness/harness-core/54715#-Ni4TdfW-Z3V8jP1mBBK:-NiEAVdrEUTOeyPhr1Tt:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b4dadf385f0d9ec1aaf4b876a106c962fd5c92a2/960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java#L94)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

check to introduce const in same class
</blockquote></details>

done

**Pull request merged**
