### PR TITLE
[feat]: [PL-29929]: Adding support for / character in Name field of entity.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
Adding support for / character in Name field by modifying NGEntityNameValidator.

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42572)

### CODE REVIEW

**Comment by Jimit09Gandhi** [comment]
trigger messagecheck

**Comment by pbarapatre10** [comment]
*[`970-ng-commons/src/main/java/io/harness/data/validator/NGEntityNameValidator.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/42572#-NLdl3Oz60r28vZCwtgB:-NLdl3Oz60r28vZCwtgC:bfue86c) ([raw file](https://github.com/harness/harness-core/blob/b322fc25361c2f16e4f252570cd8bb91d3f2a26e/970-ng-commons/src/main/java/io/harness/data/validator/NGEntityNameValidator.java#L44)):*
> ```Java
>       context.disableDefaultConstraintViolation();
>       context
>           .buildConstraintViolationWithTemplate("can only contain alphanumeric, dot, hyphen and underscore characters.")
> ```

nit: please update this msg accordingly. thanks



_Code quote:_
```Java
"can only contain alphanumeric, dot, hyphen and underscore characters."
```

**Review by pbarapatre10 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42572)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42572)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/data/validator/NGEntityNameValidator.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/42572#-NLdl3Oz60r28vZCwtgB:-NLefIF36JzvvDBVpctJ:b-8paa15) ([raw file](https://github.com/harness/harness-core/blob/b322fc25361c2f16e4f252570cd8bb91d3f2a26e/970-ng-commons/src/main/java/io/harness/data/validator/NGEntityNameValidator.java#L44)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

nit: please update this msg accordingly. thanks
</blockquote></details>

Thanks for the catch. Done.

**Review by meenakshi-harness — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42572)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42572)* status: 1. unresolved discussions.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42572)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42572)* status: 1. unresolved discussions.

**Pull request merged**
