### PR TITLE
feat: [IDP-158]: AccountID to Namespace mapping in DB

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43817)

### CODE REVIEW

**Comment by devesh-harness** [comment]
trigger codeformat

**Comment by devesh-harness** [comment]
trigger ti1

**Comment by devesh-harness** [comment]
trigger ti1

**Review by sandeepa-kv-jois — APPROVED** [review]

**Comment by devesh-harness** [comment]
trigger ti1

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 9 of 13 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43817)* status: 13 file(s) to review. 1 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/namespace/BUILD.bazel` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/43817#-NO8VhK01eK8ev08Z_4D:-NO8VhK01eK8ev08Z_4E:br93ild) ([raw file](https://github.com/harness/harness-core/blob/09b8b8419efdb6b967f841df83ec4dfecc1f30c4/idp-service/service/src/main/java/io/harness/idp/namespace/BUILD.bazel#L24)):*
> ```Starlark
>         "//980-commons/src/main/java/io/harness/morphia:module",
>         "//999-annotations:module",
>         "//idp-service/contracts:module",
> ```

Do we need this? Since we don't have any APIs involved here, we might not need this.



_Code quote:_
```Starlark
"//idp-service/contracts:module"
```
___
*[`idp-service/service/src/main/java/io/harness/idp/namespace/beans/dto/NamespaceDTO.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/43817#-NO8WLdW7uPsBKy6lxRJ:-NO8WLdW7uPsBKy6lxRK:b-uqo9y0) ([raw file](https://github.com/harness/harness-core/blob/09b8b8419efdb6b967f841df83ec4dfecc1f30c4/idp-service/service/src/main/java/io/harness/idp/namespace/beans/dto/NamespaceDTO.java#L23)):*
> ```Java
> @JsonInclude(JsonInclude.Include.NON_NULL)
> @OwnedBy(HarnessTeam.IDP)
> public class NamespaceDTO {
> ```

nit: Just wondering if we should suffix with DTO or not
The ones created via open API/swagger will not have a DTO suffix.
One option is an Entity suffix for DB representation and no suffix for this.
`NamespaceEntity` and `Namespace` (instead of NamespaceDTO)



_Code quote:_
```Java
NamespaceDTO
```
___
*[`idp-service/service/src/main/java/io/harness/idp/namespace/service/NamespaceService.java` line 16 at r3](https://reviewable.io/reviews/harness/harness-core/43817#-NO8YeNgAssajMyEeFME:-NO8YeNgAssajMyEeFMF:bejop34) ([raw file](https://github.com/harness/harness-core/blob/09b8b8419efdb6b967f841df83ec4dfecc1f30c4/idp-service/service/src/main/java/io/harness/idp/namespace/service/NamespaceService.java#L16)):*
> ```Java
> 
> public interface NamespaceService {
>   Optional<NamespaceDTO> getNamespaceFromAccountIdentifier(String accountIdentifier);
> ```

nit: How about renaming it to `getNamespaceForAccountIdentifier` or `getNamespaceForAccountId`?



_Code quote:_
```Java
getNamespaceFromAccountIdentifier
```

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43817)* status: 13 file(s) to review. 1 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/namespace/repositories/NamespaceRepositoryCustom.java` line 14 at r3](https://reviewable.io/reviews/harness/harness-core/43817#-NO8x6aF61DP_2VoEmWr:-NO8x6aF61DP_2VoEmWs:b-7cntt2) ([raw file](https://github.com/harness/harness-core/blob/09b8b8419efdb6b967f841df83ec4dfecc1f30c4/idp-service/service/src/main/java/io/harness/idp/namespace/repositories/NamespaceRepositoryCustom.java#L14)):*
> ```Java
> public interface NamespaceRepositoryCustom {
>   NamespaceEntity saveNamespaceEntity(NamespaceEntity namespaceEntity);
> }
> ```

Could we use generated one itself? save method



_Code quote:_
```Java
  NamespaceEntity saveNamespaceEntity(NamespaceEntity namespaceEntity);
}
```

**Review by sandeepa-kv-jois — APPROVED** [review]
> Reviewed 2 of 13 files at r1, 1 of 1 files at r2, 7 of 10 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43817)* status: :shipit: complete! ✓

**Review by deepharness — APPROVED** [review]
> Reviewed 2 of 13 files at r1, 1 of 1 files at r2, 7 of 10 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43817)* status: :shipit: complete! ✓

**Pull request merged**
