### PR TITLE
[feat]:[PIE-8074]: Added loggers for getting batchFetchFile info

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added loggers for getting batchFetchFile information

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43491)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 382 at r1](https://reviewable.io/reviews/harness/harness-core/43491#-NNM4Bu44Znc8q16a8LG:-NNM4Bu44Znc8q16a8LH:b-f131zk) ([raw file](https://github.com/harness/harness-core/blob/0c918db6433e7420450b6fb9668b492aa9592274/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L382)):*
> ```Java
>       ScmGetBatchFilesByBranchRequestDTO scmGetBatchFilesByBranchRequestDTO) {
>     scmGetBatchFilesByBranchRequestDTO.validate();
>     List<String> uniqueFileRequests = new ArrayList<>();
> ```

This is too noisy just for adding a log statement. Please lets either make it simpler 1 line statement or lets move this into a method if we want to log with such details. A log shouldn't have so much background computations, which may deviate us from the original method itself when someone tries to read the code.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43491)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 382 at r1](https://reviewable.io/reviews/harness/harness-core/43491#-NNM4Bu44Znc8q16a8LG:-NNM5xYIDuEuEY9zoru4:b-9xxgs0) ([raw file](https://github.com/harness/harness-core/blob/0c918db6433e7420450b6fb9668b492aa9592274/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L382)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This is too noisy just for adding a log statement. Please lets either make it simpler 1 line statement or lets move this into a method if we want to log with such details. A log shouldn't have so much background computations, which may deviate us from the original method itself when someone tries to read the code.
</blockquote></details>

have moved it a method as of now

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43491)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43491#-:-NNMHHraCfkxAJ4jdlVJ:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43491)* status: :shipit: complete! ✓

**Pull request merged**
