### PR TITLE
feat: [CDS-43057]: apply templates changes

### PR DESCRIPTION
**Pull request by prabu-kr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37507)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 11 Issues 
* Code issue 11 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37507)

**Review by utkarshchoubey-harness — COMMENTED** [review]
> Reviewed 4 of 11 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37507)* status: 6 file(s) to review. 0 of 1 approvals obtained.

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by utkarshchoubey-harness** [comment]
trigger feature-build

**Comment by utkarshchoubey-harness** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, 1 of 2 files at r2, 11 of 30 files at r10, 4 of 6 files at r11, 1 of 2 files at r13, 1 of 2 files at r15, 8 of 14 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37507)* status: 21 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/beans/NGTemplateConstants.java` line 24 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2hbnh0QB4n3uZ99sa:-ND2hbnh0QB4n3uZ99sb:b-7vrdf2) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/beans/NGTemplateConstants.java#L24)):*
> ```Java
>   public static final String TEMPLATE_VERSION_LABEL = "versionLabel";
>   public static final String TEMPLATE_INPUTS = "templateInputs";
>   public static final String TEMPLATE_VARIABLES = "templateVariables";
> ```

nit: could be removed.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 12 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2iP623Yh7t2VlC12W:-ND2iP623Yh7t2VlC12X:b-40ovwq) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L12)):*
> ```Java
> import static io.harness.annotations.dev.HarnessTeam.CDC;
> import static io.harness.data.structure.EmptyPredicate.isEmpty;
> import static io.harness.template.beans.NGTemplateConstants.*;
> ```

nit: import issue.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 131 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2i_QIEEJiihFeLtI8:-ND2i_QIEEJiihFeLtI9:b-m880ir) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L131)):*
> ```Java
> 
>   // Gets the Updated Template Input values
>   private JsonNode getUpdatedTemplateValue(String accountId, String orgId, String projectId, JsonNode TemplateNodeValue,
> ```

nit: rename it to templateNodeValue



_Code quote:_
```Java
TemplateNodeValue
```
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 135 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2iUCN8ErW_m0Hyu7z:-ND2iUCN8ErW_m0Hyu8-:b-338m54) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L135)):*
> ```Java
>     // Template Inputs linked to the YAML
>     JsonNode templateInputs = TemplateNodeValue.get(TEMPLATE_INPUTS);
>     JsonNode templateVariablesFromPipeline = TemplateNodeValue.get(TEMPLATE_VARIABLES);
> ```

check this once.



_Code quote:_
```Java
TEMPLATE_VARIABLES
```
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 154 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2jclk-EKYpfrnrNSd:-ND2jclk-EKYpfrnrNSe:b-epmxk4) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L154)):*
> ```Java
>     ObjectNode templateVariablesFromTemplate = null;
>     try {
>       NGTemplateConfig templateConfig = YamlPipelineUtils.read(templateYaml, NGTemplateConfig.class);
> ```

nit: this could be removed since we are already doing YamlUtils.readTree(templateYaml) below
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 177 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2jp6K9HNTa7DasUsq:-ND2jp6K9HNTa7DasUsr:b-usssbr) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L177)):*
> ```Java
>     if (refreshedJsonNode == null) {
>       // CASE -> When Template does not contain any runtime inputs
>       updatedValue.remove(TEMPLATE_VARIABLES);
> ```

should be TEMPLATE_INPUTS
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 180 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2jxrB8NGwE11WmKBp:-ND2jxrB8NGwE11WmKBq:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L180)):*
> ```Java
>     } else {
>       // Inserting the Updated Value of TemplateInputs corresponding to the TemplateInputs field
>       updatedValue.set(TEMPLATE_VARIABLES, refreshedJsonNode);
> ```

same here
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 199 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2kG89Ar0nxEnCA0JN:-ND2kG89Ar0nxEnCA0JO:blk1zoa) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L199)):*
> ```Java
>     } else {
>       // Inserting the Updated Value of TemplateInputs corresponding to the TemplateInputs field
>       updatedValue.set(YAMLFieldNameConstants.VARIABLES, refreshedTemplateVariablesNode);
> ```

nit: instead try using updatedValue.setAll(refreshedTemplateVariablesNode)
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 176 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2l2Ty03GQSFtnZkxj:-ND2l2Ty03GQSFtnZkxk:bfbdz1t) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L176)):*
> ```Java
>    * @return template inputs yaml
>    */
>   public String createTemplateInputsFromTemplate(String yaml, String accountId) {
> ```

nit: we can directly pass template yaml to RuntimeInputFormHelper.createTemplateFromYaml() and then get spec and variables from it to create templateInputs form.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 421 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2ltzE-89aQxwYmKUg:-ND2ltzE-89aQxwYmKUh:b-wb5fvs) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L421)):*
> ```Java
>     }
> 
>     if (TemplateYamlSchemaMergeHelper.isFeatureFlagEnabled(
> ```

nit: let's use this class NGTemplateFeatureFlagHelperService.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 424 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2ne3L1V_LZ-XbU4Qu:-ND2ne3L1V_LZ-XbU4Qv:b3ofq8t) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L424)):*
> ```Java
>             FeatureName.NG_TEMPLATE_VARIABLES, accountId, accountClient)) {
>       mergedYaml = applyTemplateVariablesInYaml(prepareVariableValueMap(templateVariables),
>           NGVariablesUtils.getStringMapVariables(variablesFromTemplate, 0L), mergedYaml);
> ```

let's not use this since it converts secrets to `ngSecretManager.obtain(, 0)`
instead they should be converted to secrets.getValue()
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 424 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2oFAD1_VqjZEqfQO_:-ND2oFAD1_VqjZEqfQOa:b-vcp7en) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L424)):*
> ```Java
>             FeatureName.NG_TEMPLATE_VARIABLES, accountId, accountClient)) {
>       mergedYaml = applyTemplateVariablesInYaml(prepareVariableValueMap(templateVariables),
>           NGVariablesUtils.getStringMapVariables(variablesFromTemplate, 0L), mergedYaml);
> ```

nit: let's replace variables in template spec and then create merged yaml instead



_Code quote:_
```Java
mergedYaml
```
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 706 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2pAN7AeCY373sBo7b:-ND2pAN7AeCY373sBo7c:b-ijk3z7) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L706)):*
> ```Java
>       templateJson.remove(YAMLFieldNameConstants.VARIABLES);
>       return applyTemplateVariablesInYaml(
>           variableValues, prepareVariableValueMap(templateVariables), YamlUtils.writeYamlString(templateYamlField));
> ```

let's use YamlPipelineUtils.writeYamlString() instead



_Code quote:_
```Java
YamlUtils.writeYamlString
```
___
*[`840-template-service/src/main/java/io/harness/template/helpers/YamlVariablesUtils.java` line 46 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2pN0xB6F4bL3zfQZ5:-ND2pN0xB6F4bL3zfQZ6:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/helpers/YamlVariablesUtils.java#L46)):*
> ```Java
>         getUuidToFQNMapForLeafNodes(uuidInjectedYaml.getNode().getField(rootNode));
>     return VariableMergeServiceResponse.builder()
>         .yaml(YamlUtils.writeYamlString(uuidInjectedYaml))
> ```

same here
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 823 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2po4aAzARFML45I5l:-ND2po4aAzARFML45I5m:bju9lbi) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L823)):*
> ```Java
>               ? templateServiceHelper.addTemplateVariablesToVariablesApi(
>                   variableMergeServiceResponse, appliedTemplateYaml)
>               : variableMergeServiceResponse);
> ```

nit: Either have for all or only for step templates.
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 893 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2pzPc09j--u52v_Ej:-ND2pzPc09j--u52v_Ek:b224cnt) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L893)):*
> ```Java
>     return ResponseDTO.newResponse(templateService.copyTemplateWithVariables(accountIdentifier, orgIdentifier,
>         projectIdentifier, copyTemplateVariableRequestDTO.getTemplateYaml(),
>         NGVariablesUtils.getStringMapVariables(copyTemplateVariableRequestDTO.getVariables(), 0L)));
> ```

This needs to be changed as discussed.



_Code quote:_
```Java
NGVariablesUtils.getStringMapVariables
```
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 544 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2rGTEDeGsHY5obvL8:-ND2rGTEDeGsHY5obvL9:b-lfsb7m) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L544)):*
> ```Java
>   }
> 
>   public VariableMergeServiceResponse addTemplateVariablesToVariablesApi(
> ```

nit: make it more readable
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 762 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2rLQH79hTjqypKaxt:-ND2rLQH79hTjqypKaxu:bj1u5zf) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L762)):*
> ```Java
> 
>   @Override
>   public String copyTemplateWithVariables(String accountIdentifier, String orgIdentifier, String projectIdentifier,
> ```

nit: let's shift to TemplateMergeService
___
*[`840-template-service/src/main/java/io/harness/template/beans/CopyTemplateVariableRequestDTO.java` line 26 at r18](https://reviewable.io/reviews/harness/harness-core/37507#-ND2h8F0B8GFVMYb1pr2:-ND2h8F0B8GFVMYb1pr3:b-7vrdf2) ([raw file](https://github.com/harness/harness-core/blob/398c1d1e7815b9b50bb0bf99be29101f1f74c9e4/840-template-service/src/main/java/io/harness/template/beans/CopyTemplateVariableRequestDTO.java#L26)):*
> ```Java
> @Data
> @Builder
> @JsonIgnoreProperties(ignoreUnknown = true)
> ```

nit: could be removed.

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 6 files at r4, 6 of 13 files at r8, 6 of 30 files at r10, 6 of 14 files at r17, 13 of 57 files at r22, 32 of 44 files at r24, 1 of 135 files at r25, 123 of 131 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37507)* status: 207 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Pull request closed without merging**
