### PR TITLE
feat: [PL-27691]: change for viewing git sync pipelines with pipeline view pwe…

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
With pipeline view permission, git synced pipelines are not able to open as they use connector for getting pipeline and user might not have connector edit permission and that's why pipeline doesn't open up.
So, while encrypting or decrypting connector, the context has been set as service context instead of user context.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37196)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37196)

**Review by reetika04 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37196)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by bhavya181** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 851 at r3](https://reviewable.io/reviews/harness/harness-core/37196#-NBM2uOB0z8kZisZszhj:-NBM2uOB0z8kZisZszhk:bb0nkk6) ([raw file](https://github.com/harness/harness-core/blob/7f52d22b7c15c8227f9e9889dad41b169cc106b3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L851)):*
> ```Java
>         secretManagerClientService.getEncryptionDetails(baseNGAccess, apiAccessDecryptableEntity);
>     if (principal != null) {
>       GlobalContextManager.upsertGlobalContextRecord(principal);
> ```

how is this helping? There are no operations after this statement I believe, so where will this be used?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37196)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 851 at r3](https://reviewable.io/reviews/harness/harness-core/37196#-NBM2uOB0z8kZisZszhj:-NBNJcek36Yc0b-F5LyO:b3okdip) ([raw file](https://github.com/harness/harness-core/blob/7f52d22b7c15c8227f9e9889dad41b169cc106b3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L851)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

how is this helping? There are no operations after this statement I believe, so where will this be used?
</blockquote></details>

we take user profile for committer after this only.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37196#-:-NBW_oco0dq0Ztwwu2j3:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37196)* status: 4 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37196)* status: :shipit: complete! ✓

**Pull request merged**
