### PR TITLE
feat: [PIE-8147]: Throw the same error received from template service whenever there's an error in resolving templates

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Issue:** Pipeline service currently throws same error message: `Exception in resolving template refs in given pipeline yaml.` whenever there's an error in template resolution. This error message is not really verbose and helpful to the user. 

**Changes:** Throw the error received from template service as is rather than changing the error message. 

**Impact:** Now, the error messages thrown are more verbose like when a template with identifier mentioned in yaml doesn't exist, error message will be: `The template identifier test23 and version label v1 does not exist. Could not replace this template`.

Old error message in any case:

Screenshot 2023-02-23 at 4 52 46 PM

**Testing:** Tested following cases locally.
- Try to save a pipeline with template identifier without running template service.
New error message: 

Screenshot 2023-02-23 at 4 54 18 PM

- Try to save pipeline with template service running but incorrect template identifier.
New error message: 

Screenshot 2023-02-23 at 4 54 44 PM

## Checklist

- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44279)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/44279#-NOyMq84BxY-KLbHHhYp:-NOyMq84BxY-KLbHHhYq:bms36ko) ([raw file](https://github.com/harness/harness-core/blob/55e930d77da2684f28181414262731636b380817/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L125)):*
> ```Java
>       } catch (UnexpectedException e) {
>         log.error("Error connecting to Template Service", e);
>         throw new GeneralException("Error connecting to Template Service", e);
> ```

This should be internal server exception

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 124 at r2](https://reviewable.io/reviews/harness/harness-core/44279#-NOyMxAB8kfBNIjCYsA6:-NOyMxAB8kfBNIjCYsA7:bq2gp0m) ([raw file](https://github.com/harness/harness-core/blob/55e930d77da2684f28181414262731636b380817/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L124)):*
> ```Java
>         throw e;
>       } catch (UnexpectedException e) {
>         log.error("Error connecting to Template Service", e);
> ```

why do we log "error connecting to template service" when its "unexpected exception" and not some "connection exception"?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44279)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 124 at r2](https://reviewable.io/reviews/harness/harness-core/44279#-NOyMxAB8kfBNIjCYsA6:-NOzDTBuAz7_G0Mu61T6:bp2famk) ([raw file](https://github.com/harness/harness-core/blob/55e930d77da2684f28181414262731636b380817/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L124)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why do we log "error connecting to template service" when its "unexpected exception" and not some "connection exception"?
</blockquote></details>

It is thrown by NGRestUtils only when the connection or request to template service fails for some reason.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/44279#-NOyMq84BxY-KLbHHhYp:-NOzBLZFAiexSYsfmshU:b-7rl0jd) ([raw file](https://github.com/harness/harness-core/blob/55e930d77da2684f28181414262731636b380817/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L125)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This should be internal server exception
</blockquote></details>

done.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 124 at r2](https://reviewable.io/reviews/harness/harness-core/44279#-NOyMxAB8kfBNIjCYsA6:-NOzMClv5dj83g0cG2tQ:b-dg6e0d) ([raw file](https://github.com/harness/harness-core/blob/55e930d77da2684f28181414262731636b380817/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L124)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

It is thrown by NGRestUtils only when the connection or request to template service fails for some reason.
</blockquote></details>

I checked the code. From the code, its not clear that it sends out this exception when connection error occurs. It says "FailSafeException"


Can you once check this on local what exception is thrown? I think some other exception will be thrown in such case.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/44279#-NOyMq84BxY-KLbHHhYp:-NOzMal_BYyLbgLxj_U0:buq5yb) ([raw file](https://github.com/harness/harness-core/blob/55e930d77da2684f28181414262731636b380817/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L125)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

done.
</blockquote></details>

We should have InternalServerException from wingsExceptions to use here.
Secondly, I think we cannot actually change. It will be a backward incompatible change if we turn it into Internal Server Exception as then HTTP status code will become 500 which will violate the contract.

Probably, we cannot fix it correctly. @archit-harness to check and confirm.

**Comment by shalini-agr** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 124 at r2](https://reviewable.io/reviews/harness/harness-core/44279#-NOyMxAB8kfBNIjCYsA6:-NP1T5X227NZxskabY17:bmq8wzl) ([raw file](https://github.com/harness/harness-core/blob/55e930d77da2684f28181414262731636b380817/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L124)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I checked the code. From the code, its not clear that it sends out this exception when connection error occurs. It says "FailSafeException"


Can you once check this on local what exception is thrown? I think some other exception will be thrown in such case.

</blockquote></details>

I checked on local by not running template service and trying to save a pipeline with templateRef, Unexpected exception was only thrown with `"Error occurred while performing this operation."` message

**Comment by shalini-agr** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/44279#-NOyMq84BxY-KLbHHhYp:-NP1Tx5V2EWW04-_ufnD:bb4ujc) ([raw file](https://github.com/harness/harness-core/blob/55e930d77da2684f28181414262731636b380817/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L125)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should have InternalServerException from wingsExceptions to use here.
Secondly, I think we cannot actually change. It will be a backward incompatible change if we turn it into Internal Server Exception as then HTTP status code will become 500 which will violate the contract.

Probably, we cannot fix it correctly. @archit-harness to check and confirm.
</blockquote></details>

Here, I've created a new internalServerException extending wingsException, and we are also sending the error we got from NGRestUtils in the cause, so the status code is 400 in this case.

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44279)* status: 10 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 6 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44279)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/eraro/ErrorCode.java` line 667 at r4](https://reviewable.io/reviews/harness/harness-core/44279#-NPLiO8q7bpVgn1Z9JXH:-NPLiO8q7bpVgn1Z9JXI:bqde7r9) ([raw file](https://github.com/harness/harness-core/blob/97ebe50ae757bab83fe64c59a7c267c6b56dcf9c/980-commons/src/main/java/io/harness/eraro/ErrorCode.java#L667)):*
> ```Java
>   CLUSTER_CREDENTIALS_NOT_FOUND,
>   SCM_API_ERROR,
>   PIPELINE_INTERNAL_SERVER_ERROR;
> ```

It should be just internal server error code and not pipeline
___
*[`980-commons/src/main/java/io/harness/eraro/ErrorCode.java` line 667 at r4](https://reviewable.io/reviews/harness/harness-core/44279#-NPLiaVi1IGev0kelxwp:-NPLiaVi1IGev0kelxwq:bckrrk8) ([raw file](https://github.com/harness/harness-core/blob/97ebe50ae757bab83fe64c59a7c267c6b56dcf9c/980-commons/src/main/java/io/harness/eraro/ErrorCode.java#L667)):*
> ```Java
>   CLUSTER_CREDENTIALS_NOT_FOUND,
>   SCM_API_ERROR,
>   PIPELINE_INTERNAL_SERVER_ERROR;
> ```

we should add error code here as well

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44279)* status: 4 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/eraro/ErrorCode.java` line 667 at r4](https://reviewable.io/reviews/harness/harness-core/44279#-NPLiO8q7bpVgn1Z9JXH:-NPMjz5o4047iTx7BNQ8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/97ebe50ae757bab83fe64c59a7c267c6b56dcf9c/980-commons/src/main/java/io/harness/eraro/ErrorCode.java#L667)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

It should be just internal server error code and not pipeline
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/eraro/ErrorCode.java` line 667 at r4](https://reviewable.io/reviews/harness/harness-core/44279#-NPLiaVi1IGev0kelxwp:-NPMjzLI8L31x-5LqlZT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/97ebe50ae757bab83fe64c59a7c267c6b56dcf9c/980-commons/src/main/java/io/harness/eraro/ErrorCode.java#L667)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should add error code here as well
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 9 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44279)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/InternalServerErrorException.java` line 13 at r5](https://reviewable.io/reviews/harness/harness-core/44279#-NPN4XdfBQ4Nc3VNWS43:-NPN4XdfBQ4Nc3VNWS44:b-tdajah) ([raw file](https://github.com/harness/harness-core/blob/de6a377baa110e4507a8a17a239aa76d374cf425/980-commons/src/main/java/io/harness/exception/InternalServerErrorException.java#L13)):*
> ```Java
> import io.harness.eraro.Level;
> 
> public class InternalServerErrorException extends WingsException {
> ```

nit: add owned by in next pr plus some comments so people adopt it

**Review by mohitg0795 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 6 of 9 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44279)* status: 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/44279#-NOyMq84BxY-KLbHHhYp:-NPN8B0E13cchzpbg1EU:b-q014x2) ([raw file](https://github.com/harness/harness-core/blob/55e930d77da2684f28181414262731636b380817/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L125)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

No, we shouldn't use InternalServerException as I mentioned in my previous comment. InternalServerException should have HTTP 500, not 400. And if we integrate it in our current flow, our response status code would change which will be a backward incompatible change.
</blockquote></details>

As discussed, we don't propagate this exception directly to user but rather its being processed internally on the next downstream layer, thus its safe to change.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44279#-:-NPN8LnKEvnV6EU9ibqT:bnfp4nl)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44279)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/InternalServerErrorException.java` line 13 at r5](https://reviewable.io/reviews/harness/harness-core/44279#-NPN4XdfBQ4Nc3VNWS43:-NPNETRN8CJspjTiXjin:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/de6a377baa110e4507a8a17a239aa76d374cf425/980-commons/src/main/java/io/harness/exception/InternalServerErrorException.java#L13)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: add owned by in next pr plus some comments so people adopt it
</blockquote></details>

done

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 5 of 9 files at r4, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44279)* status: :shipit: complete! ✓

**Pull request merged**
