### PR TITLE
fix: [DEL-5052]: Consiider hostname as valid delegate selector for NG

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Describe your changes
Previously delegate hostname is not consider as valid selector for NG, as hostname can change post delegate restart. With recent requirement, there are scenarios where customer can dynamically figure out hostname and want to run all task for pipeline on same hostname. For such scenarios, we are not considering hostname as valid selector for NG as well.

Testing:
Testing locally by providing delegate hostname and task execution succeeded.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43402)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java` line 189 at r1](https://reviewable.io/reviews/harness/harness-core/43402#-NNFu39i16ZC1sITMI8I:-NNFu39i16ZC1sITMI8J:b5wrpcu) ([raw file](https://github.com/harness/harness-core/blob/ed6311d7546aab787ff5d3dfdead16c14acbbf0f/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L189)):*
> ```Java
>     }
> 
>     if (isNotEmpty(delegate.getHostName())) {
> ```

will this show up in the UI as well ?

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43402)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java` line 189 at r1](https://reviewable.io/reviews/harness/harness-core/43402#-NNFu39i16ZC1sITMI8I:-NNFucK8Cm_8RXZIoUjG:b38fi28) ([raw file](https://github.com/harness/harness-core/blob/ed6311d7546aab787ff5d3dfdead16c14acbbf0f/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L189)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

will this show up in the UI as well ?
</blockquote></details>

No, this method gets called only during assignment of task. This will not appear in UI. Verified locally.

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43402)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43402)* status: Some of the checks are too old. Waiting on team(s): del-team.

**Pull request merged**
