### PR TITLE
fix: [CDS-81984]: Added handling for different connectors for different files during bulk batch GET FILE operation

### PR DESCRIPTION
**Pull request by mohitg0795**
## Describe your changes
- Currently, during get-batch-file operation, we fetch N files together from GIT as a single delegate task. We let any delegate pick up the task which meets basic capability check.
- Issue arises when N files may have different connectors associated with them and those connectors having different delegate selectors. Then, we can't assign all files fetch operation to a single delegate task.
- In this PR, we try to handle it by distributing the files in groups associated to their dedicated connectors. This way if there are common M connectors amongst N total files, we divide batch file operation into M batch file operation such that they can be performed on perfectly compatible delegate as per their designated delegate selectors.
- Also handled some error scenarios and enhanced error experience.

Testing:
- Tried to fetch 2 different files using 2 different connectors with 2 delegate selectors, works fine now.
- Also, tried out error scenarios in case any of the delegates are down.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54805)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54805)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
trigger uts

**Comment by mohitg0795** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54805)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncUtils.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/54805#-NiDuBSV0XTNUdDD1PoU:-NiDuBSV0XTNUdDD1PoV:bwpgz1j) ([raw file](https://github.com/harness/harness-core/blob/8c8b57f65861e468ba9fdd970b722dcc1d81bbaa/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncUtils.java#L39)):*
> ```Java
> public class GitSyncUtils {
>   static ObjectMapper objectMapper = new ObjectMapper(new YAMLFactory());
>   private static final String ACCOUNT_CONNECTOR_SCOPE_PREFIX = "account.";
> ```

as discussed we can use IdentifierRefHelper

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 7 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54805)* status: 9 file(s) to review. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncUtils.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/54805#-NiDuBSV0XTNUdDD1PoU:-NiEBzMp-qhXnn4ISBJK:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8c8b57f65861e468ba9fdd970b722dcc1d81bbaa/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncUtils.java#L39)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

as discussed we can use IdentifierRefHelper
</blockquote></details>

done

**Review by archit-harness — DISMISSED** [review]

**Review by adivishy1 — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 6 of 7 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54805)* status: 1 file(s) to review.

**Comment by mohitg0795** [comment]
trigger uts

**Comment by mohitg0795** [comment]
trigger review

**Comment by mohitg0795** [comment]
trigger uts

**Comment by mohitg0795** [comment]
trigger ut8

**Comment by mohitg0795** [comment]
trigger uts

**Comment by mohitg0795** [comment]
trigger uts

**Review by adivishy1 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54805)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by shalini-agr — APPROVED** [review]

**Comment by mohitg0795** [comment]
trigger review

**Pull request merged**
