### PR TITLE
fix: [PL-29195]: Update k8s Auth fields in vault if sm is updated

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Describe your changes
Updating a vault SM to k8s auth was not taking in the required fields. With this change, those fields will be picked up and updated in dB.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39097)

### CODE REVIEW

**Comment by VikasMaddukuriHarness** [comment]
trigger messagecheck

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39097)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java` line 130 at r1](https://reviewable.io/reviews/harness/harness-core/39097#-NEuIPbi7NyCssBInHz-:-NEuIPbj-q172e7cVIbX:b-uleeib) ([raw file](https://github.com/harness/harness-core/blob/35c3d75098b9f153fbe09a454c08185d59918b22/400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java#L130)):*
> ```Java
>     updateNameSpace(accountId, vaultConfig, savedVaultConfig);
>     // Handle vault k8s Auth Properties
>     updateK8sAuthConfig(vaultConfig, savedVaultConfig);
> ```

Add UT to cover this change.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39097)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java` line 130 at r1](https://reviewable.io/reviews/harness/harness-core/39097#-NEuIPbi7NyCssBInHz-:-NFHVD1j96tB8gS3yx7x:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/35c3d75098b9f153fbe09a454c08185d59918b22/400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java#L130)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Add UT to cover this change.
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39097)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
