### PR TITLE
feat:[CDS-72257]: Package step changes

### PR DESCRIPTION
**Pull request by piyush-bhuwalka**
## Describe your changes

This PR includes

Serverless Package Step Changes
Serverless Package Plugin Info Provider Changes
Impact:

No real impact, new changes are introduced

Testing:

Ran the step to check its not causing any regression

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49855)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaPackageV2PluginInfoProvider.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/49855#-NZ0LUyo9qRNCFx48E1m:-NZ0LUypAcA2YK8EKI7x:b3e4b5q) ([raw file](https://github.com/harness/harness-core/blob/5be53bc7a7733f08469658b10bd58bdc6fff250c/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaPackageV2PluginInfoProvider.java#L37)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDP)
> public class ServerlessAwsLambdaPackageV2PluginInfoProvider implements CDPluginInfoProvider {
> ```

This should be merged with other pluginInfoProviders

**Comment by piyush-bhuwalka** [comment]
trigger ut0

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 36 of 38 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49855)* status: 38 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Comment by piyush-bhuwalka** [comment]
trigger checkstylecodeformat

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 14 of 16 files at r3, 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49855)* status: 39 file(s) to review. 1 of 2 approvals obtained.

**Review by RishabhGupta34 — APPROVED** [review]

**Comment by piyush-bhuwalka** [comment]
trigger review

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 38 files at r1, 5 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49855)* status: 31 file(s) to review.

**Review by yogesh-chauhan — APPROVED** [review]
Approved for required files from code owner

**Pull request merged**
