### PR TITLE
feat: [PL-39708]: config changes to support redis persistence lock

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
config changes to support redis persistance lock in svcs - 
template svc
ceng
verification svc

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49865)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49865)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`ce-nextgen/service/src/main/java/io/harness/ccm/CENextGenModule.java` line 560 at r1](https://reviewable.io/reviews/harness/harness-core/49865#-NZ0mgjr6hW-Vx806Eeb:-NZ0mgjr6hW-Vx806Eec:bp7ohil) ([raw file](https://github.com/harness/harness-core/blob/5597779156096457e6bb693eb76e0ab1d712fac4/ce-nextgen/service/src/main/java/io/harness/ccm/CENextGenModule.java#L560)):*
> ```Java
>   @Singleton
>   RedisConfig redisConfig() {
>     return configuration.getEventsFrameworkConfiguration().getRedisConfig();
> ```

Why are we providing events framework redis for lock. It should be memstore redis config
___
*[`template-service/service/src/main/java/io/harness/TemplateServiceModule.java` line 321 at r1](https://reviewable.io/reviews/harness/harness-core/49865#-NZ0mpFnESQjf5nrh83L:-NZ0mpFnESQjf5nrh83M:bp7ohil) ([raw file](https://github.com/harness/harness-core/blob/5597779156096457e6bb693eb76e0ab1d712fac4/template-service/service/src/main/java/io/harness/TemplateServiceModule.java#L321)):*
> ```Java
>   @Singleton
>   RedisConfig redisConfig() {
>     return templateServiceConfiguration.getEventsFrameworkConfiguration().getRedisConfig();
> ```

Why are we providing events framework redis for lock. It should be memstore redis config

**Review by ankit-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49865)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by sdsingh07 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r1, 6 of 6 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49865#-:-NZ1vyqS3OJ1DKldeIC0:bnfp4nl)* status: :shipit: complete! ✓

**Review by nikunj-badjatya — DISMISSED** [review]
> Reviewed 3 of 6 files at r1, 6 of 6 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49865)* status: :shipit: complete! ✓

**Review by nassergonzalez — DISMISSED** [review]
LGTM. My only concern is that we should have the changes in the ng-prod-manifest for the quality-assurance and main branch merged before this PR is merged

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49865)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`310-iacm-manager/build/container/scripts/replace_configs.sh` line 433 at r4](https://reviewable.io/reviews/harness/harness-core/49865#-NZ5MbGe9MkSA93WXU9A:-NZ5MbGf3Y5orUrwXdeF:b-6pv8ph) ([raw file](https://github.com/harness/harness-core/blob/b3bc70fce2af2d09cacb361beeef3b3a2646630c/310-iacm-manager/build/container/scripts/replace_configs.sh#L433)):*
> ```Shell
> replace_key_value redisLockConfig.retryInterval $REDIS_RETRY_INTERVAL
> replace_key_value redisLockConfig.retryAttempts $REDIS_RETRY_ATTEMPTS
> replace_key_value redisLockConfig.timeout $REDIS_TIMEOUT
> ```

replace_key_value redisLockConfig.useScriptCache $REDIS_LOCK_CONFIG_REDIS_USE_SCRIPT_CACHE not required here?
___
*[`dockerization/template-service/scripts/replace_configs.sh` line 223 at r4](https://reviewable.io/reviews/harness/harness-core/49865#-NZ5Me103QVdWxMY4cUN:-NZ5Me103QVdWxMY4cUO:bcgkwxv) ([raw file](https://github.com/harness/harness-core/blob/b3bc70fce2af2d09cacb361beeef3b3a2646630c/dockerization/template-service/scripts/replace_configs.sh#L223)):*
> ```Shell
> replace_key_value redisLockConfig.retryInterval $REDIS_RETRY_INTERVAL
> replace_key_value redisLockConfig.retryAttempts $REDIS_RETRY_ATTEMPTS
> replace_key_value redisLockConfig.timeout $REDIS_TIMEOUT
> ```

replace_key_value redisLockConfig.useScriptCache $REDIS_LOCK_CONFIG_REDIS_USE_SCRIPT_CACHE not required?
___
*[`template-service/container/scripts/replace_configs.sh` line 217 at r4](https://reviewable.io/reviews/harness/harness-core/49865#-NZ5Mi9A1XpvXLQ5XXys:-NZ5Mi9A1XpvXLQ5XXyt:buub5v4) ([raw file](https://github.com/harness/harness-core/blob/b3bc70fce2af2d09cacb361beeef3b3a2646630c/template-service/container/scripts/replace_configs.sh#L217)):*
> ```Shell
> replace_key_value redisLockConfig.retryInterval $REDIS_RETRY_INTERVAL
> replace_key_value redisLockConfig.retryAttempts $REDIS_RETRY_ATTEMPTS
> replace_key_value redisLockConfig.timeout $REDIS_TIMEOUT
> ```

replace_key_value redisLockConfig.useScriptCache $REDIS_LOCK_CONFIG_REDIS_USE_SCRIPT_CACHE

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49865)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`310-iacm-manager/build/container/scripts/replace_configs.sh` line 433 at r4](https://reviewable.io/reviews/harness/harness-core/49865#-NZ5MbGe9MkSA93WXU9A:-NZ5RmHeC-NN8431CqyQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b3bc70fce2af2d09cacb361beeef3b3a2646630c/310-iacm-manager/build/container/scripts/replace_configs.sh#L433)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

replace_key_value redisLockConfig.useScriptCache $REDIS_LOCK_CONFIG_REDIS_USE_SCRIPT_CACHE not required here?
</blockquote></details>

Done.
___
*[`dockerization/template-service/scripts/replace_configs.sh` line 223 at r4](https://reviewable.io/reviews/harness/harness-core/49865#-NZ5Me103QVdWxMY4cUN:-NZ5RniWErrxyE6kjJhf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b3bc70fce2af2d09cacb361beeef3b3a2646630c/dockerization/template-service/scripts/replace_configs.sh#L223)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

replace_key_value redisLockConfig.useScriptCache $REDIS_LOCK_CONFIG_REDIS_USE_SCRIPT_CACHE not required?
</blockquote></details>

Done.
___
*[`template-service/container/scripts/replace_configs.sh` line 217 at r4](https://reviewable.io/reviews/harness/harness-core/49865#-NZ5Mi9A1XpvXLQ5XXys:-NZ5RmxH0sXQXm0ems2Y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b3bc70fce2af2d09cacb361beeef3b3a2646630c/template-service/container/scripts/replace_configs.sh#L217)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

replace_key_value redisLockConfig.useScriptCache $REDIS_LOCK_CONFIG_REDIS_USE_SCRIPT_CACHE
</blockquote></details>

Done.

**Review by ashishsanodia-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49865#-:-NZ5ViHnCuNOT2afH0mW:bnfp4nl)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49865)* status: 1 file(s) to review.

**Comment by bhavya181** [comment]
trigger uts

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Pull request merged**
