### PR TITLE
[fix]: [CDS-52588]: Improve Error Handling in Google Functions Swimlane

### PR DESCRIPTION
**Pull request by PragyeshMishra01**
## Describe your changes
Error Handling Enhancements in Google Functions Swimlane
## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43741)

### CODE REVIEW

**Review by alluvamsi-harness — DISMISSED** [review]

**Review by rohitk-h — APPROVED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43741)* status: 17 file(s) to review. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/googlefunctions/GoogleFunctionsHelper.java` line 263 at r1](https://reviewable.io/reviews/harness/harness-core/43741#-NNtnlKU6WYt2_NMnWVy:-NNtnlKU6WYt2_NMnWVz:b-q48z06) ([raw file](https://github.com/harness/harness-core/blob/add26f5a584869d487599753d344096bffeeb4b2/125-cd-nextgen/src/main/java/io/harness/cdng/googlefunctions/GoogleFunctionsHelper.java#L263)):*
> ```Java
>     } else {
>       if (googleFunctionCommandResponse.getFunction() == null) {
>         return stepResponseBuilder.status(Status.SUCCEEDED).build();
> ```

Should we be returning failure here instead? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googlecloudstorage/GoogleCloudStorageArtifactTaskHandler.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/43741#-NNtwd5Y0Ib3zJ9XLfZW:-NNtwd5Y0Ib3zJ9XLfZX:b-786kiv) ([raw file](https://github.com/harness/harness-core/blob/add26f5a584869d487599753d344096bffeeb4b2/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googlecloudstorage/GoogleCloudStorageArtifactTaskHandler.java#L70)):*
> ```Java
>     if (!artifactDelegateRequest.getArtifactPath().equals(expectedBuildDetail.getArtifactPath())) {
>       throw new InvalidRequestException("No artifact exist for the provided artifact path. "
>           + "Please ensure that artifact path is valid");
> ```

nit: we could create a constant for the string. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/googlefunction/GoogleFunctionUtils.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/43741#-NNtsLQ17YLyXn8Lyrok:-NNtsLQ17YLyXn8Lyrol:b-knmlzt) ([raw file](https://github.com/harness/harness-core/blob/add26f5a584869d487599753d344096bffeeb4b2/930-delegate-tasks/src/main/java/io/harness/delegate/task/googlefunction/GoogleFunctionUtils.java#L26)):*
> ```Java
>   public static final String UPDATE_FUNCTION_FAILURE_HINT = "Please check for possible issues in: \n "
>       + "1. Execution logs under deploy section. \n 2. Validate fields in cloud function manifest. \n "
>       + "3. Refer documentation for createFunctionRequest: https://cloud.google.com/functions/docs/reference/rpc/google.cloud.functions.v2#createfunctionrequest \n "
> ```

Is there doc link for updateFunctionRequest? 
___
*[`960-api-services/src/main/java/io/harness/googlecloudstorage/GcsHelperService.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/43741#-NNts2If8_y8vsVhQTI4:-NNts2Ig1SlK3L8SbPvW:b65ixvt) ([raw file](https://github.com/harness/harness-core/blob/add26f5a584869d487599753d344096bffeeb4b2/960-api-services/src/main/java/io/harness/googlecloudstorage/GcsHelperService.java#L93)):*
> ```Java
>       throw new InvalidRequestException(format("Unable to checkout bucket: %s in Google Cloud Storage. Please "
>               + "ensure that provided project and bucket exists in GCP",
>           gcsInternalConfig.getBucket()));
> ```

Can this value be null?

**Comment by rohitk-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitcommon/GitTaskNG.java` line 163 at r1](https://reviewable.io/reviews/harness/harness-core/43741#-NNtyhWQ3x9NXwbrwTwe:-NNtyhWQ3x9NXwbrwTwf:bpqtimr) ([raw file](https://github.com/harness/harness-core/blob/88b4e014e9699bf90bdb2d085706881071476526/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitcommon/GitTaskNG.java#L163)):*
> ```Java
>         try {
>           filesResult =
>               gitFetchTaskHelper.fetchFileFromRepo(gitStoreDelegateConfig, filePaths, accountId, gitConfigDTO);
> ```

This is a common git task, what is the motivation to remove the exception from here?

**Review by PragyeshMishra01 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43741)* status: 17 file(s) to review. 4. unresolved discussions. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googlecloudstorage/GoogleCloudStorageArtifactTaskHandler.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/43741#-NNtwd5Y0Ib3zJ9XLfZW:-NNueXZB1dkebCHXDCKg:b-1mxiwa) ([raw file](https://github.com/harness/harness-core/blob/add26f5a584869d487599753d344096bffeeb4b2/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googlecloudstorage/GoogleCloudStorageArtifactTaskHandler.java#L70)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

nit: we could create a constant for the string. 
</blockquote></details>

sure, doing the change
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitcommon/GitTaskNG.java` line 163 at r1](https://reviewable.io/reviews/harness/harness-core/43741#-NNtyhWQ3x9NXwbrwTwe:-NNuek4t0GR2rEY8BKtA:bw18yco) ([raw file](https://github.com/harness/harness-core/blob/88b4e014e9699bf90bdb2d085706881071476526/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitcommon/GitTaskNG.java#L163)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

This is a common git task, what is the motivation to remove the exception from here? 
</blockquote></details>

It is not required there, we are already throwing proper exceptions from lower layers.  We created this common git task as part of google functions development. Currently, we are only using it in Google Functions. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/googlefunction/GoogleFunctionUtils.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/43741#-NNtsLQ17YLyXn8Lyrok:-NNufthSAEgFJzzDC4b7:b-wbj2vw) ([raw file](https://github.com/harness/harness-core/blob/add26f5a584869d487599753d344096bffeeb4b2/930-delegate-tasks/src/main/java/io/harness/delegate/task/googlefunction/GoogleFunctionUtils.java#L26)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Is there doc link for updateFunctionRequest? 
</blockquote></details>

yes, but from user point of view they will always provide createFunctionRequest object json in manifest.
___
*[`960-api-services/src/main/java/io/harness/googlecloudstorage/GcsHelperService.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/43741#-NNts2If8_y8vsVhQTI4:-NNugXbd8nOfteRIeZRZ:bbhvja) ([raw file](https://github.com/harness/harness-core/blob/add26f5a584869d487599753d344096bffeeb4b2/960-api-services/src/main/java/io/harness/googlecloudstorage/GcsHelperService.java#L93)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Can this value be null? 
</blockquote></details>

yes, I have observed that incase if gcp project/bucket is invalid then google returns null when we call their getBucket() API.

**Review by PragyeshMishra01 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43741)* status: 18 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/googlefunctions/GoogleFunctionsHelper.java` line 263 at r1](https://reviewable.io/reviews/harness/harness-core/43741#-NNtnlKU6WYt2_NMnWVy:-NNwiunp-1TpC20-H_43:b-ux4ajy) ([raw file](https://github.com/harness/harness-core/blob/add26f5a584869d487599753d344096bffeeb4b2/125-cd-nextgen/src/main/java/io/harness/cdng/googlefunctions/GoogleFunctionsHelper.java#L263)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Should we be returning failure here instead? 
</blockquote></details>

I added this to handle case when function will be deleted as part of rollback. But now I have removed this as I realized that function can be null in other cases. Now I am having a field isFunctionDeleted boolean in rollback response to handle this case.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googlecloudstorage/GoogleCloudStorageArtifactTaskHandler.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/43741#-NNtwd5Y0Ib3zJ9XLfZW:-NNwji5J4gn9IyK_Av7n:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/add26f5a584869d487599753d344096bffeeb4b2/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googlecloudstorage/GoogleCloudStorageArtifactTaskHandler.java#L70)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

sure, doing the change
</blockquote></details>

Done

**Review by rohitk-h — APPROVED** [review]
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43741)* status: 18 file(s) to review. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitcommon/GitTaskNG.java` line 163 at r1](https://reviewable.io/reviews/harness/harness-core/43741#-NNtyhWQ3x9NXwbrwTwe:-NNwnFtV6qHgJRNqYnxK:b-8vlfyz) ([raw file](https://github.com/harness/harness-core/blob/88b4e014e9699bf90bdb2d085706881071476526/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitcommon/GitTaskNG.java#L163)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

It is not required there, we are already throwing proper exceptions from lower layers.  We created this common git task as part of google functions development. Currently, we are only using it in Google Functions. 
</blockquote></details>

We should be ok if proper exceptions are from lower layers. Since this is in common package, we will have more tasks consuming this hence the concern. Looks good to me. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/googlefunction/GoogleFunctionUtils.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/43741#-NNtsLQ17YLyXn8Lyrok:-NNwn_5vEFUWqI7sG-rw:bt8rbsw) ([raw file](https://github.com/harness/harness-core/blob/add26f5a584869d487599753d344096bffeeb4b2/930-delegate-tasks/src/main/java/io/harness/delegate/task/googlefunction/GoogleFunctionUtils.java#L26)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

yes, but from user point of view they will always provide createFunctionRequest object json in manifest.
</blockquote></details>

got it, thanks!
___
*[`960-api-services/src/main/java/io/harness/googlecloudstorage/GcsHelperService.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/43741#-NNts2If8_y8vsVhQTI4:-NNwn--aEMPGNfIa9Sub:b-ouhv5k) ([raw file](https://github.com/harness/harness-core/blob/add26f5a584869d487599753d344096bffeeb4b2/960-api-services/src/main/java/io/harness/googlecloudstorage/GcsHelperService.java#L93)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

yes, I have observed that incase if gcp project/bucket is invalid then google returns null when we call their getBucket() API.
</blockquote></details>

So, will `gcsInternalConfig.getBucket()` ever return null?

**Review by PragyeshMishra01 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43741)* status: 18 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/googlecloudstorage/GcsHelperService.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/43741#-NNts2If8_y8vsVhQTI4:-NNwo_o92pWMJArYulz3:bdgrs7g) ([raw file](https://github.com/harness/harness-core/blob/add26f5a584869d487599753d344096bffeeb4b2/960-api-services/src/main/java/io/harness/googlecloudstorage/GcsHelperService.java#L93)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

So, will `gcsInternalConfig.getBucket()` ever return null?  
</blockquote></details>

no, it will not return null but storage.get(gcsInternalConfig.getBucket()) can return null if gcsInternalConfig.getBucket() is not a valid bucket.

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43741)* status: 18 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43741)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Review by alluvamsi-harness — APPROVED** [review]
> Reviewed 7 of 17 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43741)* status: :shipit: complete! ✓

**Pull request merged**
