### PR TITLE
fix: [PIE-3687]: Add support to empty timeout due its optional nature

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
* Added empty value in regexp as accepted on the timeout field
* When an empty value is detected, the code changes it to the default timeout.

**Other minor changes**
* Add isNotNull to ParameterField :: Now is possible use a negative operation instead of the use of exclamation mark in condition evaluation. That brings a better readability into the code.
* Increase the code coverage to timeout conditions

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35391)

### CODE REVIEW

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35391)* status: Some of the checks are too old. 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/validator/NGRegexValidatorConstants.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/35391#-N7IKTKM1gM3CqfZrmhZ:-N7IKTKN6zYUsuMLnPv9:b-hp3sxl) ([raw file](https://github.com/harness/harness-core/blob/da6edc0f16b0a9b02ca09e06c7751bdda9974bab/970-ng-commons/src/main/java/io/harness/validator/NGRegexValidatorConstants.java#L19)):*
> ```Java
>   String NAME_PATTERN = "^[a-zA-Z_][-0-9a-zA-Z_\\s]{0,63}$";
>   String TIMEOUT_PATTERN =
>       "^(([1-9])+\\d+[s])|(((([1-9])+\\d*[mhwd])+([\\s]?\\d+[smhwd])*)|(<\\+input>.*)|(.*<\\+.*>.*)|(^$))$";
> ```

write a UT for empty strings as discussed

eg.s 

""
" ab "

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35391)* status: 8 file(s) to review. 2 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`970-ng-commons/src/main/java/io/harness/validator/NGRegexValidatorConstants.java` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/35391#-N7JvcqW8sQNn3E1VmAT:-N7JvcqW8sQNn3E1VmAU:b1g7yb3) ([raw file](https://github.com/harness/harness-core/blob/aedd69b3d6341957e816ed73629f43737d814ae7/970-ng-commons/src/main/java/io/harness/validator/NGRegexValidatorConstants.java#L19)):*
> ```Java
>   String NAME_PATTERN = "^[a-zA-Z_][-0-9a-zA-Z_\\s]{0,63}$";
>   String TIMEOUT_PATTERN =
>       "^(([1-9])+\\d+[s])|(((([1-9])+\\d*[mhwd])+([\\s]?\\d+[smhwd])*)|(<\\+input>.*)|(.*<\\+.*>.*)|(^$))$";
> ```

We have not added handling for timeout for step and stage plan creators

**Comment by Fernando-Dourado** [comment]
> > Reviewed 3 of 5 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/35391)_ status: 8 file(s) to review. 2 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto.
> 
> _[`970-ng-commons/src/main/java/io/harness/validator/NGRegexValidatorConstants.java` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/35391#-N7JvcqW8sQNn3E1VmAT:-N7JvcqW8sQNn3E1VmAU:b1g7yb3) ([raw file](https://github.com/harness/harness-core/blob/aedd69b3d6341957e816ed73629f43737d814ae7/970-ng-commons/src/main/java/io/harness/validator/NGRegexValidatorConstants.java#L19)):_
> 
> > ```java
> >   String NAME_PATTERN = "^[a-zA-Z_][-0-9a-zA-Z_\\s]{0,63}$";
> >   String TIMEOUT_PATTERN =
> >       "^(([1-9])+\\d+[s])|(((([1-9])+\\d*[mhwd])+([\\s]?\\d+[smhwd])*)|(<\\+input>.*)|(.*<\\+.*>.*)|(^$))$";
> > ```
> 
> We have not added handling for timeout for step and stage plan creators

When an empty value is detected, the code changes it to the default timeout.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35391)* status: 8 file(s) to review. 1 change requests. 1 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`970-ng-commons/src/main/java/io/harness/validator/NGRegexValidatorConstants.java` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/35391#-N7JvcqW8sQNn3E1VmAT:-N7UQeFpB-paimwr9iA3:bm3hq3q) ([raw file](https://github.com/harness/harness-core/blob/aedd69b3d6341957e816ed73629f43737d814ae7/970-ng-commons/src/main/java/io/harness/validator/NGRegexValidatorConstants.java#L19)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

When an empty value is detected, the code changes it to the default timeout.
</blockquote></details>

Yeah confirmed it now, its already there

**Review by vaibhav-si — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35391)* status: 1 change requests. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by williamwissemann — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35391)* status: 1 change requests. Waiting on team(s): sto.

**Review by vaibhav-si — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35391#-:-N7XyGRS-aMJ7muPuNtu:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
