### PR TITLE
feat: [PL-31890]: fix queries that fetch unlimited records for UserMemberShipV2 and servicesNG

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
fix queries that fetch unlimited records for UserMemberShipV2 and servicesNG

- Add limits on APIs to fetch max 1k records
- removed unnecessary findAll methods
- changed to findAll() queries to stream() queries

Tested the changes for API limits by hitting APIs with page se more than 1k, tested list methods where stream() is used locally by calling the APIs, which use those methods

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44767)

### CODE REVIEW

**Review by Jimit09Gandhi — DISMISSED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44767)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44767)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResource.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/44767#-NPu-c048sv8gbwBLyOY:-NPu-c048sv8gbwBLyOZ:bklve3c) ([raw file](https://github.com/harness/harness-core/blob/cbc9d5f4c025432739aff5f6c4ea83c606d87cea/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResource.java#L125)):*
> ```Java
>   public ResponseDTO<PageResponse<ServiceResponseDTO>> createServices(
>       @QueryParam("accountId") String accountId, @NotNull @Valid List<ServiceRequestDTO> serviceRequestDTOs) {
>     if (serviceRequestDTOs.size() > 1000) {
> ```

Can't we specify this check in form of annotation?

Did we change openapispec too?
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 291 at r1](https://reviewable.io/reviews/harness/harness-core/44767#-NPu13HlCdakk8S8P3iH:-NPu13HlCdakk8S8P3iI:bb5s8m2) ([raw file](https://github.com/harness/harness-core/blob/cbc9d5f4c025432739aff5f6c4ea83c606d87cea/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L291)):*
> ```Java
> 
>   @Override
>   public List<String> listUserIds(Scope scope) {
> ```

Where is this method used? Can we avoid putting a limit of 50000 and keep it default here?
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 458 at r1](https://reviewable.io/reviews/harness/harness-core/44767#-NPu0o3d0nmZAFUD7Fis:-NPu0o3d0nmZAFUD7Fit:b-s17wr8) ([raw file](https://github.com/harness/harness-core/blob/cbc9d5f4c025432739aff5f6c4ea83c606d87cea/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L458)):*
> ```Java
>   @VisibleForTesting
>   protected Set<String> getUsersAtScope(Set<String> userFilter, Scope scope) {
>     if (userFilter.size() > 1000) {
> ```

Where is this method used? How did we pick 1000 as value?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44767)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResource.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/44767#-NPu-c048sv8gbwBLyOY:-NQ5KdX_18i8UxA6de50:b-bfl7wz) ([raw file](https://github.com/harness/harness-core/blob/cbc9d5f4c025432739aff5f6c4ea83c606d87cea/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResource.java#L125)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can't we specify this check in form of annotation?

Did we change openapispec too?
</blockquote></details>

applied annotation
yes, openApiSpec is already changed in another pr
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 291 at r1](https://reviewable.io/reviews/harness/harness-core/44767#-NPu13HlCdakk8S8P3iH:-NQ5WLzM5WIOUVqMzWM_:bhfbd10) ([raw file](https://github.com/harness/harness-core/blob/cbc9d5f4c025432739aff5f6c4ea83c606d87cea/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L291)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Where is this method used? Can we avoid putting a limit of 50000 and keep it default here?
</blockquote></details>

it is used at multiple places to list user ids in one scope, again if we put 10k only then different usecases may fail

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44767)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 458 at r1](https://reviewable.io/reviews/harness/harness-core/44767#-NPu0o3d0nmZAFUD7Fis:-NQ5m3a-CgHsIPQJnkEK:bolch2k) ([raw file](https://github.com/harness/harness-core/blob/cbc9d5f4c025432739aff5f6c4ea83c606d87cea/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L458)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Where is this method used? How did we pick 1000 as value?
</blockquote></details>

It is used from one place only, that already has limit of 100 on userFilter

**Comment by bhavya181** [comment]
trigger utAll

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResource.java` line 177 at r4](https://reviewable.io/reviews/harness/harness-core/44767#-NQ6boZT6q7leBNBMW5T:-NQ6boZT6q7leBNBMW5U:bfq9llu) ([raw file](https://github.com/harness/harness-core/blob/e403bab57cfd13ea9a7a88ac3005ee6169950769/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResource.java#L177)):*
> ```Java
>       @QueryParam("accountId") String accountId, @QueryParam(NGCommonEntityConstants.ORG_KEY) String orgIdentifier,
>       @QueryParam(NGCommonEntityConstants.PROJECT_KEY) String projectIdentifier,
>       @QueryParam("serviceIdentifiers") List<String> serviceIdentifiers, @QueryParam("sort") List<String> sort) {
> ```

can we also update the "listServicesForProject" method ?

**Comment by yogesh-chauhan** [comment]
Could you please also take care of "AbstractServicesApiImpl" and its subclasses ?

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44767)* status: 8 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 399 at r4](https://reviewable.io/reviews/harness/harness-core/44767#-NQ6byntEY1shZeUL-Du:-NQ6byntEY1shZeUL-Dv:b6ivfc2) ([raw file](https://github.com/harness/harness-core/blob/e403bab57cfd13ea9a7a88ac3005ee6169950769/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L399)):*
> ```Java
>       @Parameter(description = NGCommonEntityConstants.ACCOUNT_PARAM_MESSAGE) @NotNull @QueryParam(
>           NGCommonEntityConstants.ACCOUNT_KEY) @AccountIdentifier String accountId,
>       @Parameter(description = NGCommonEntityConstants.ORG_PARAM_MESSAGE) @QueryParam(
> ```

other methods
- listAccessServices
- getServicesYamlAndRuntimeInputs

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44767)* status: 8 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/core/impl/ProjectServiceImplTest.java` line 557 at r4](https://reviewable.io/reviews/harness/harness-core/44767#-NQ8QvPg4rw3Ox_nVy24:-NQ8QvPg4rw3Ox_nVy25:b-tbzseq) ([raw file](https://github.com/harness/harness-core/blob/e403bab57cfd13ea9a7a88ac3005ee6169950769/120-ng-manager/src/test/java/io/harness/ng/core/impl/ProjectServiceImplTest.java#L557)):*
> ```Java
>     return new CloseableIterator<T>() {
>       @Override
>       public void close() {}
> ```

We don't need to do anything here?

**Review by bhavya181 — COMMENTED** [review]
limit has already applied to openAPI.yaml in another pr

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44767#-:-NQ9MeW6-WxH7J4u06R3:b-fgtw9j)* status: 8 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResource.java` line 177 at r4](https://reviewable.io/reviews/harness/harness-core/44767#-NQ6boZT6q7leBNBMW5T:-NQ9MmFAC1RXTRlNdbjC:bg41ods) ([raw file](https://github.com/harness/harness-core/blob/e403bab57cfd13ea9a7a88ac3005ee6169950769/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResource.java#L177)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we also update the "listServicesForProject" method ?
</blockquote></details>

it use pagination, applied limit on page size
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 279 at r4](https://reviewable.io/reviews/harness/harness-core/44767#-NQ6c90u-EBkm1EnAww1:-NQ9MsdH3Cm8x8MD4Vrh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e403bab57cfd13ea9a7a88ac3005ee6169950769/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L279)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we use the MAX_LIMIT param here also ?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 399 at r4](https://reviewable.io/reviews/harness/harness-core/44767#-NQ6byntEY1shZeUL-Du:-NQ9MxbRBznMzRYKyp73:bfprkq2) ([raw file](https://github.com/harness/harness-core/blob/e403bab57cfd13ea9a7a88ac3005ee6169950769/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L399)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

other methods
- listAccessServices
- getServicesYamlAndRuntimeInputs

</blockquote></details>

applied limits
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/impl/ProjectServiceImplTest.java` line 557 at r4](https://reviewable.io/reviews/harness/harness-core/44767#-NQ8QvPg4rw3Ox_nVy24:-NQ9N-RV6PbFbAmMpZiv:bwjkgwa) ([raw file](https://github.com/harness/harness-core/blob/e403bab57cfd13ea9a7a88ac3005ee6169950769/120-ng-manager/src/test/java/io/harness/ng/core/impl/ProjectServiceImplTest.java#L557)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We don't need to do anything here?
</blockquote></details>

yes, Its a test we are just returning an iterator as we mock repository methods

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r3, 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44767#-:-NQ9QYIt3iYwAFby9SVX:bnfp4nl)* status: 8 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44767)* status: 8 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 582 at r5](https://reviewable.io/reviews/harness/harness-core/44767#-NQ9UcMhCGIeob2z0QiZ:-NQ9UcMhCGIeob2z0Qi_:bg62cxv) ([raw file](https://github.com/harness/harness-core/blob/7fbdfd79e32b88092b3fe9eeb4f58b3d1b8095db/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L582)):*
> ```Java
>   public ResponseDTO<ServicesV2YamlMetadataDTO>
>   getServicesYamlAndRuntimeInputs(@Parameter(description = SERVICE_YAML_METADATA_INPUT_PARAM_MESSAGE) @Valid
>                                   @NotNull ServicesYamlMetadataApiInput servicesYamlMetadataApiInput,
> ```

can we apply the max limit in that ServicesYamlMetadataApiInput.serviceIdentifiers instead ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44767)* status: 6 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 342 at r5](https://reviewable.io/reviews/harness/harness-core/44767#-NQ9UqM20KS9cu-lsfMU:-NQ9UqM20KS9cu-lsfMV:bstfmx5) ([raw file](https://github.com/harness/harness-core/blob/7fbdfd79e32b88092b3fe9eeb4f58b3d1b8095db/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L342)):*
> ```Java
>   @Override
>   public List<ServiceEntity> listRunTimePermission(Criteria criteria) {
>     return serviceRepository.findAll(criteria, Pageable.ofSize(50000)).toList();
> ```

can we take this constant out ?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44767)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 582 at r5](https://reviewable.io/reviews/harness/harness-core/44767#-NQ9UcMhCGIeob2z0QiZ:-NQ9iktiB4D-CXM-fBwc:b-61g0uz) ([raw file](https://github.com/harness/harness-core/blob/7fbdfd79e32b88092b3fe9eeb4f58b3d1b8095db/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L582)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

No, I meant limits in that class separately? 
```
public class ServicesYamlMetadataApiInput {
  @NotNull @Max(1000) List<String> serviceIdentifiers;
}
```
</blockquote></details>

got it, changed the class
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 342 at r5](https://reviewable.io/reviews/harness/harness-core/44767#-NQ9UqM20KS9cu-lsfMU:-NQ9ioOWAr26hTQHKNx4:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/7fbdfd79e32b88092b3fe9eeb4f58b3d1b8095db/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L342)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we take this constant out ? 
</blockquote></details>

done

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by diptiman-adak** [comment]
trigger ut4

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44767#-:-NQB6--67PlF4B_KDBHI:bnfp4nl)* status: 10 file(s) to review.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 10 files at r1, 2 of 5 files at r3, 3 of 3 files at r4, 3 of 3 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44767)* status: :shipit: complete! ✓

**Pull request merged**
