### PR TITLE
[fix]: [CDS-35830]: Added Validation for artifact type for respective develo…

### PR DESCRIPTION
**Pull request by TarunUba1**
…pment type

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34264)

### CODE REVIEW

**Comment by tchaurasiya** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java` line 507 at r2](https://reviewable.io/reviews/harness/harness-core/34264#-N4VoI568x4z4y_zaIcI:-N4VoI568x4z4y_zaIcJ:bynw05u) ([raw file](https://github.com/harness/harness-core/blob/04f51ffd848f496b605b3e6b9d69d6e019d5b23a/400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java#L507)):*
> ```Java
>           "Artifact from Manifest flag can be set to true only for kubernetes and helm deployment types");
>     }
>     // Checking Artifact Type for respective Deployment type
> ```

Lets delete this comment.
Code is self explanable.



_Code quote:_
```Java
  if(service.getArtifactType() != ArtifactType.DOC
```

**Comment by tchaurasiya** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java` line 508 at r2](https://reviewable.io/reviews/harness/harness-core/34264#-N4VoVINDW4qgNEYOeYp:-N4VoVINDW4qgNEYOeYq:b-ck9ab0) ([raw file](https://github.com/harness/harness-core/blob/04f51ffd848f496b605b3e6b9d69d6e019d5b23a/400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java#L508)):*
> ```Java
>     }
>     // Checking Artifact Type for respective Deployment type
>     switch (service.getDeploymentType()) {
> ```

Let's extract method out of it. 
Its making parent method verbose

**Comment by tchaurasiya** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java` line 494 at r2](https://reviewable.io/reviews/harness/harness-core/34264#-N4Voh9W2A7kS81FX-W_:-N4Voh9W2A7kS81FX-Wa:b-nazu2e) ([raw file](https://github.com/harness/harness-core/blob/04f51ffd848f496b605b3e6b9d69d6e019d5b23a/400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java#L494)):*
> ```Java
>   @Override
>   @ValidationGroups(Create.class)
>   public Service save(Service service, boolean createdFromYaml, boolean createDefaultCommands) {
> ```

We need to do these changes in update() method also.

**Comment by tchaurasiya** [comment]
*[`400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/34264#-N4Vq1DV5Hf2ssLFdvUu:-N4Vq1DV5Hf2ssLFdvUv:b-rh25h5) ([raw file](https://github.com/harness/harness-core/blob/04f51ffd848f496b605b3e6b9d69d6e019d5b23a/400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java#L17)):*
> ```Java
> import static io.harness.k8s.model.HelmVersion.V3;
> 
> import static io.harness.rule.OwnerRule.*;
> ```

Please avoid using import *

**Comment by TarunUba1** [comment]
@tchaurasiya  regarding adding checker in Update function as well
There are many test cases where artifactType is asssigned to be Null and they all are throwing error for the same.
For example, a test case where we change only deployment type,  tests are not changing artifactType and hence are failing
What to do

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 4 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34264)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java` line 3305 at r3](https://reviewable.io/reviews/harness/harness-core/34264#-N4XcII967wXcixxjGql:-N4XcII967wXcixxjGqm:bx2rzzo) ([raw file](https://github.com/harness/harness-core/blob/7d7f97fa4999e3b1466124eb882a5733f56026f8/400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java#L3305)):*
> ```Java
>     switch (service.getDeploymentType()) {
>       case KUBERNETES:
>         if(service.getArtifactType() != ArtifactType.DOCKER) {
> ```

can we also deploy helm chart manifests with K8s deployments ..?
ref. manifest as artifacts is allowed ..? :thinking: 
___
*[`400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java` line 1166 at r3](https://reviewable.io/reviews/harness/harness-core/34264#-N4XcsrJ4Sjq4WMmkvVZ:-N4XcsrJ4Sjq4WMmkvV_:bf5gtd6) ([raw file](https://github.com/harness/harness-core/blob/7d7f97fa4999e3b1466124eb882a5733f56026f8/400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java#L1166)):*
> ```Java
>   @Owner(developers = TARUN_UBA)
>   @Category(UnitTests.class)
>   public void testSavingK8ArtifactFail() {
> ```

add tests for other deployment types as well.

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34264)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java` line 3305 at r3](https://reviewable.io/reviews/harness/harness-core/34264#-N4XcII967wXcixxjGql:-N4aMxOO-CpCAAL1BKzf:b3vfpve) ([raw file](https://github.com/harness/harness-core/blob/7d7f97fa4999e3b1466124eb882a5733f56026f8/400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java#L3305)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

can we also deploy helm chart manifests with K8s deployments ..?
ref. manifest as artifacts is allowed ..? :thinking: 
</blockquote></details>


In the UI "artifactType" is already filled in with "DOCKER" in K8 deployment and is non-editable, We can assign different Artifact Source but for artifact type i didnt find any other case. Also when i chose manifest as artifact it still showed Artifact type Docker. So what to do in this case

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34264)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java` line 508 at r2](https://reviewable.io/reviews/harness/harness-core/34264#-N4VoVINDW4qgNEYOeYp:-N4aPEAp3CPO5oeF4VHh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/04f51ffd848f496b605b3e6b9d69d6e019d5b23a/400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java#L508)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Let's extract method out of it. 
Its making parent method verbose
</blockquote></details>

Done.

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34264)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java` line 507 at r2](https://reviewable.io/reviews/harness/harness-core/34264#-N4VoI568x4z4y_zaIcI:-N4aPGKp554yISGsQomJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/04f51ffd848f496b605b3e6b9d69d6e019d5b23a/400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java#L507)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Lets delete this comment.
Code is self explanable.
</blockquote></details>

Done.

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34264)* status: 1 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/34264#-N4Vq1DV5Hf2ssLFdvUu:-N4aPM73-Ivj8flpm8Ra:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/04f51ffd848f496b605b3e6b9d69d6e019d5b23a/400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java#L17)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Please avoid using import *
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java` line 1174 at r5](https://reviewable.io/reviews/harness/harness-core/34264#-N4bAXEvEQu5vByttbiC:-N4bAXEvEQu5vByttbiD:b3g4zem) ([raw file](https://github.com/harness/harness-core/blob/37c9da705f3f7276c0c443cfcc68b2c628d96b4e/400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java#L1174)):*
> ```Java
>     Service customService = Service.builder().appId(APP_ID).name(SERVICE_NAME).accountId(ACCOUNT_ID).deploymentType(CUSTOM).artifactType(ArtifactType.OTHER).build();
> 
>     serviceResourceService.save(k8sService);
> ```

We should add assert this by 
 assertThatCode(() -> method()).doesNotThrowAnyException();

**Comment by tchaurasiya** [comment]
*[`400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java` line 1162 at r5](https://reviewable.io/reviews/harness/harness-core/34264#-N4bAqC42ThCpJsdDn-i:-N4bAqC42ThCpJsdDn-j:b-8mft28) ([raw file](https://github.com/harness/harness-core/blob/37c9da705f3f7276c0c443cfcc68b2c628d96b4e/400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java#L1162)):*
> ```Java
>     doNothing().when(notificationService).sendNotificationAsync(any());
> 
>     Service k8sService = Service.builder().appId(APP_ID).name(SERVICE_NAME).accountId(ACCOUNT_ID).deploymentType(KUBERNETES).artifactType(ArtifactType.DOCKER).build();
> ```

can we wrap these all services in an array(created by some generateTestData() method) and then call method on each element of array.
Just want to reduce verbosity of main test.

**Comment by tchaurasiya** [comment]
*[`400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java` line 1186 at r5](https://reviewable.io/reviews/harness/harness-core/34264#-N4bB8fP3KxGG1WNbiyu:-N4bB8fP3KxGG1WNbiyv:bg0381t) ([raw file](https://github.com/harness/harness-core/blob/37c9da705f3f7276c0c443cfcc68b2c628d96b4e/400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java#L1186)):*
> ```Java
>     serviceResourceService.save(customService);
> 
>     Service k8FailService = Service.builder().appId(APP_ID).name(SERVICE_NAME).accountId(ACCOUNT_ID).deploymentType(KUBERNETES).artifactType(ArtifactType.NUGET).build();
> ```

Lets put all exception throwing cases in another test.

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34264)* status: 2 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java` line 1166 at r3](https://reviewable.io/reviews/harness/harness-core/34264#-N4XcsrJ4Sjq4WMmkvVZ:-N4b6F-43aYjeh7Hae2f:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d7f97fa4999e3b1466124eb882a5733f56026f8/400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java#L1166)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

add tests for other deployment types as well.
</blockquote></details>

Done.
___
*[`400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java` line 1186 at r5](https://reviewable.io/reviews/harness/harness-core/34264#-N4bB8fP3KxGG1WNbiyu:-N4bcvoA18QiGYWmU5Au:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/37c9da705f3f7276c0c443cfcc68b2c628d96b4e/400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java#L1186)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Lets put all exception throwing cases in another test.
</blockquote></details>

Done.

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34264)* status: 2 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java` line 1174 at r5](https://reviewable.io/reviews/harness/harness-core/34264#-N4bAXEvEQu5vByttbiC:-N4bczITA4ds9KWdmX3F:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/37c9da705f3f7276c0c443cfcc68b2c628d96b4e/400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java#L1174)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

We should add assert this by 
 assertThatCode(() -> method()).doesNotThrowAnyException();
</blockquote></details>

Done.

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34264)* status: 2 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java` line 1162 at r5](https://reviewable.io/reviews/harness/harness-core/34264#-N4bAqC42ThCpJsdDn-i:-N4bd14i2wEIhMY1ZRi2:b-soldnx) ([raw file](https://github.com/harness/harness-core/blob/37c9da705f3f7276c0c443cfcc68b2c628d96b4e/400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java#L1162)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

can we wrap these all services in an array(created by some generateTestData() method) and then call method on each element of array.
Just want to reduce verbosity of main test.

</blockquote></details>

I tried to reduce in one test but in other due to different exception messages was resulting in same line lengths or more

**Review by shubham-in10se — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34264)* status: 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained.

**Review by shubham-in10se — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34264)* status: 6. unresolved discussions.

**Comment by tchaurasiya** [comment]
*[`400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java` line 1195 at r6](https://reviewable.io/reviews/harness/harness-core/34264#-N4evW3c1pbTV3SLQywZ:-N4evW3c1pbTV3SLQyw_:bm9p7ws) ([raw file](https://github.com/harness/harness-core/blob/dc955353d6de54b7ebe01813985a57f963d7c844/400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java#L1195)):*
> ```Java
>     doNothing().when(notificationService).sendNotificationAsync(any());
> 
>     List<Service> services = new ArrayList<Service>(8);
> ```

Java doesn't need array size or Data type in array, for right hand part of declaration.

**Comment by tchaurasiya** [comment]
*[`400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java` line 1197 at r6](https://reviewable.io/reviews/harness/harness-core/34264#-N4eviPpCvEVtAfk-pSV:-N4eviPpCvEVtAfk-pSW:b8sxnlh) ([raw file](https://github.com/harness/harness-core/blob/dc955353d6de54b7ebe01813985a57f963d7c844/400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java#L1197)):*
> ```Java
>     List<Service> services = new ArrayList<Service>(8);
> 
>     services.add(generateTestData(KUBERNETES, ArtifactType.NUGET));
> ```

lets extract these in a method like generateTestServicesData()

**Comment by tchaurasiya** [comment]
*[`400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java` line 1176 at r6](https://reviewable.io/reviews/harness/harness-core/34264#-N4evvmzAagxqus5r7Xp:-N4evvmzAagxqus5r7Xq:b-u5is8c) ([raw file](https://github.com/harness/harness-core/blob/dc955353d6de54b7ebe01813985a57f963d7c844/400-rest/src/test/java/software/wings/service/impl/ServiceResourceServiceImplTest.java#L1176)):*
> ```Java
>     services.add(generateTestData(CUSTOM,ArtifactType.OTHER));
> 
>     for(Service service : services){
> ```

Let't use stream here.

**Comment by tchaurasiya** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java` line 3327 at r6](https://reviewable.io/reviews/harness/harness-core/34264#-N4ew-Si5iG_hBcvwhVn:-N4ew-Si5iG_hBcvwhVo:ba4atry) ([raw file](https://github.com/harness/harness-core/blob/dc955353d6de54b7ebe01813985a57f963d7c844/400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java#L3327)):*
> ```Java
>           if (service.getArtifactType() != ArtifactType.DOCKER) {
>             throw new InvalidRequestException(
>                     "Only Docker ArtifactType allowed for HELM Deployment Type"
> ```

Casing should be consistent.

**Comment by tchaurasiya** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java` line 3334 at r6](https://reviewable.io/reviews/harness/harness-core/34264#-N4ewDe2Ek8GpiqxIxwC:-N4ewDe2Ek8GpiqxIxwD:ba4atry) ([raw file](https://github.com/harness/harness-core/blob/dc955353d6de54b7ebe01813985a57f963d7c844/400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java#L3334)):*
> ```Java
>           if (service.getArtifactType() != ArtifactType.DOCKER) {
>             throw new InvalidRequestException(
>                     "Only DOCKER ArtifactType allowed for Amazon EC2 Container Services (ECS) Deployment Type"
> ```

Casing should be consistent.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 4 files at r2, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34264)* status: 0 of 1 approvals obtained.

**Pull request merged**
