### PR TITLE
techDebt: [CDS-39039]: File store tests

### PR DESCRIPTION
**Pull request by filip5rovic**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34567)

### CODE REVIEW

**Comment by filip5rovic** [comment]
trigger messagecheck

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 7 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34567#-:-N5AY8FXCJOPfG2kO20e:bnfp4nl)* status: :shipit: complete! ✓

___
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileFailsafeServiceImpl.java` line 133 at r2](https://reviewable.io/reviews/harness/harness-core/34567#-N5AXHTz7dJ-pcPa7aSI:-N5AXHTz7dJ-pcPa7aSJ:b-gubbd1) ([raw file](https://github.com/harness/harness-core/blob/9330011dcea4a51f4bba3096a89921c4a6f892ea/877-filestore/src/main/java/io/harness/filestore/service/impl/FileFailsafeServiceImpl.java#L133)):*
> ```Java
>   }
> 
>   void deleteActivities(String accountIdentifier, String orgIdentifier, String projectIdentifier, String identifier) {
> ```

Just add com.google.common.annotations.VisibleForTesting annotation on these three package level methods.

**Review by ivan-83 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34567)* status: 0 of 1 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34567#-:-N5AhcEf4guaUqd7oSb0:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
