### PR TITLE
[feat]: [PIE-2527]: adding pipeline.triggerBy expressions in NG

### PR DESCRIPTION
**Pull request by brijeshdhakar**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30670)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30670)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/expressions/functors/TriggeredByFunctor.java, line 35 at r1](https://reviewable.io/reviews/harness/harness-core/30670#-MvXp4FMBobySCKUxHiQ:-MvXp4FMBobySCKUxHiR:bhhbjkt) ([raw file](https://github.com/harness/harness-core/blob/6d4ac38df3fa4b5054c05b1fa101d3810987aa10/800-pipeline-service/src/main/java/io/harness/pms/expressions/functors/TriggeredByFunctor.java#L35)):*
> ```Java
>     PipelineExecutionSummaryEntity pipelineExecutionSummaryEntity =
>         pmsExecutionService.getPipelineExecutionSummaryEntity(ambiance.getSetupAbstractionsMap().get("accountId"),
>             ambiance.getSetupAbstractionsMap().get("orgIdentifier"),
> ```

use AmbianceUtils for getting information, at every ambiance place



_Code quote:_
```Java
ambiance.getSetupAbstractionsMap().get("orgIdentifier")
```

**Review by naidu-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30670)* status: 3 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/expressions/functors/TriggeredByFunctor.java, line 44 at r2](https://reviewable.io/reviews/harness/harness-core/30670#-MvXtNZtDPkl6DxAaLke:-MvXtNZtDPkl6DxAaLkf:b-4pxx1e) ([raw file](https://github.com/harness/harness-core/blob/58e4a301bd4c1325f95df1c7d59e62aa228d2674/800-pipeline-service/src/main/java/io/harness/pms/expressions/functors/TriggeredByFunctor.java#L44)):*
> ```Java
>         "name", pipelineExecutionSummaryEntity.getExecutionTriggerInfo().getTriggeredBy().getIdentifier());
>     triggeredByMap.put("email",
>         pipelineExecutionSummaryEntity.getExecutionTriggerInfo().getTriggeredBy().getExtraInfoMap().get("email"));
> ```

would this be a null pointer if InfoMap is null? especially with WEBHOOK?

**Review by naidu-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30670)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30670)* status: 3 file(s) to review. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/expressions/functors/TriggeredByFunctor.java, line 35 at r1](https://reviewable.io/reviews/harness/harness-core/30670#-MvXp4FMBobySCKUxHiQ:-MvY37uHE-GhCtCm3kC2:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/6d4ac38df3fa4b5054c05b1fa101d3810987aa10/800-pipeline-service/src/main/java/io/harness/pms/expressions/functors/TriggeredByFunctor.java#L35)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use AmbianceUtils for getting information, at every ambiance place
</blockquote></details>

Done

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30670)* status: :shipit: complete! ✓

**Pull request merged**
