### PR TITLE
fix: [PL-38386]: Fix ECS hostname look up

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
Issue: On every heartbeat call for ECS delegate, existingDelegate is coming as null, hence we do add delegate instead of update HB. Also all PT's that are in TASK_NON_ASSIGNABLE state changing to TASK_UNASSIGNED causing load on iterator and observed slowness in PT assignment process.

Fix: Get ECS hostname with sequence number and hostname coming from delegate 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47324)

### CODE REVIEW

**Review by mdmilic — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47324)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by xingchi-jin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47324)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2493 at r1](https://reviewable.io/reviews/harness/harness-core/47324#-NUiMU2rAXjT7waGF55W:-NUiMU2rAXjT7waGF55X:bz7f24s) ([raw file](https://github.com/harness/harness-core/blob/e76dd613aac6bef2447ea2f3aa27d3d44bfc4755/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2493)):*
> ```Java
> 
>     final Delegate existingDelegate = getExistingDelegate(
>         delegate.getAccountId(), delegate.getHostName(), delegate.isNg(), delegate.getDelegateType(), delegate.getIp());
> ```

do you also need to change here? this function is the heartbeat. The other place is used for registration. 

I still have an open question in my mind need your help: why the host name coming thru heartbeat becomes different from the one thru registration for ECS?

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2493 at r1](https://reviewable.io/reviews/harness/harness-core/47324#-NUiMU2rAXjT7waGF55W:-NUw3hZm9XiCu9YE7imb:brnsdqc) ([raw file](https://github.com/harness/harness-core/blob/e76dd613aac6bef2447ea2f3aa27d3d44bfc4755/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2493)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

do you also need to change here? this function is the heartbeat. The other place is used for registration. 

I still have an open question in my mind need your help: why the host name coming thru heartbeat becomes different from the one thru registration for ECS? 
</blockquote></details>

That's how it's is designed, host name and sequence num comes separately. We append sequence num to hostname in DB while registering. Problem here is existing delegate look up was failing as we checking with hostname instead of hostname_seqnum  
 Delegate handleEcsDelegateRegistration(final Delegate delegate)

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2493 at r1](https://reviewable.io/reviews/harness/harness-core/47324#-NUiMU2rAXjT7waGF55W:-NUw6PQv4dkMbm05eYou:bl09gpn) ([raw file](https://github.com/harness/harness-core/blob/e76dd613aac6bef2447ea2f3aa27d3d44bfc4755/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2493)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

That's how it's is designed, host name and sequence num comes separately. We append sequence num to hostname in DB while registering. Problem here is existing delegate look up was failing as we checking with hostname instead of hostname_seqnum  
 Delegate handleEcsDelegateRegistration(final Delegate delegate) 

</blockquote></details>

it's been this way for a while now, since it's we doing upsert operation every time on ECS HB,  problem never got exposed.

**Review by xingchi-jin — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47324)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Review by raghuAtWings — APPROVED** [review]

**Comment by jennyjames21** [comment]
trigger uts

**Pull request merged**
