### PR TITLE
[fix]: [CDS-25520]: Added workflow type and pipelineExecutionId to alert dat…

### PR DESCRIPTION
**Pull request by lalit-horcrux**
…a to distinguish between alert data of PL and WF

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31160)

### CODE REVIEW

**Review by abhinavmittal-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31160)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java, line 965 at r1](https://reviewable.io/reviews/harness/harness-core/31160#-MxFJqjwAd0xHek59hBs:-MxFJqjyCfNOdGGd6s6P:btnw7xs) ([raw file](https://github.com/harness/harness-core/blob/6349b5832be543c1adea4e493b6043648fca1afd/400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java#L965)):*
> ```Java
>         // Open an alert
>         Environment environment = context.getEnv();
>         String pipelineExecutionId = workflowExecutionService.getPipelineExecutionId(
> ```

We can just move the fetching of WorkflowExecution object written below and move it up. No need to do another db query to fetch in this one.
For the above one we needed as we were not fetching that object

**Comment by lalit-horcrux** [comment]
___
*[400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java, line 965 at r1](https://reviewable.io/reviews/harness/harness-core/31160#-MxFJqjwAd0xHek59hBs:-MxFW6f3DI836OSvSN7M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6349b5832be543c1adea4e493b6043648fca1afd/400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java#L965)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

We can just move the fetching of WorkflowExecution object written below and move it up. No need to do another db query to fetch in this one.
For the above one we needed as we were not fetching that object
</blockquote></details>

Done.

**Review by prabu-kr — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31160)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 

___
*[400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java, line 1266 at r2](https://reviewable.io/reviews/harness/harness-core/31160#-MxXvziC4NJkhbnF7eNn:-MxXvziC4NJkhbnF7eNo:biyrkvr) ([raw file](https://github.com/harness/harness-core/blob/a32fa91ce2f01e888fc1e5e48864de34a7ed1a27/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java#L1266)):*
> ```Java
>                                      .project(WorkflowExecutionKeys.pipelineExecutionId, true)
>                                      .get()
>                                      .getPipelineExecutionId();
> ```

You can also make use fetchWorkflowExecution method in same class instead of making a new method

**Review by prabu-kr — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31160)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by prabu-kr — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31160)* status: 1 change requests. 1. unresolved discussions.

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31160)* status: 1 change requests. 1. unresolved discussions.

**Review by prabu-kr — APPROVED** [review]
:lgtm:

> Reviewed 25 of 25 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31160#-:-MxYwd5_E6GPbm1Pdsq5:bnfp4nl)* status: 1 change requests. 1. unresolved discussions.

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 25 of 25 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31160)* status: 1 change requests. 1. unresolved discussions.

**Review by abhinavmittal-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31160)* status: :shipit: complete! ✓

**Pull request merged**
