### PR TITLE
feat: [CDS-38955]: Sorting Artifacts List Based on lastUpdatedAt

### PR DESCRIPTION
**Pull request by Y0709**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36618)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* Code issue 3 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36618)

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36618)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/WorkflowStandardParamsExtensionService.java` line 178 at r2](https://reviewable.io/reviews/harness/harness-core/36618#-NAOr2BQ2BcjAHWK3stA:-NAOr2BQ2BcjAHWK3stB:b-kkjeyl) ([raw file](https://github.com/harness/harness-core/blob/9360dbd916be9074616bf9eb14cbc6e1e97ee901/400-rest/src/main/java/software/wings/sm/WorkflowStandardParamsExtensionService.java#L178)):*
> ```Java
>    */
>   public Artifact getArtifactForService(WorkflowStandardParams workflowStandardParams, String serviceId) {
>     List<Artifact> artifacts = getArtifacts(workflowStandardParams);
> ```

Should we add this inside getArtifacts() method? 
getArtifacts() is also called from multiple places. 



_Code quote:_
```Java
    if (featureFlagService.isEnabled(FeatureName.SORT_ARTIFACTS_IN_COLLECTED_ORDER, artifacts.get(0).getAccountId())) {
      for (Artifact artifact : artifacts) {
        if (artifact.getLastCollectedAt() == null) {
          artifact.setLastCollectedAt(artifact.getLastUpdatedAt());
        }
      }
      artifacts.sort(Comparator.comparing(Artifact::getLastCollectedAt).reversed());
```
___
*[`957-cg-beans/src/main/java/software/wings/beans/artifact/Artifact.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/36618#-NAOreSz6GuWQdqXFldE:-NAOreT-D0f3Gz87vJ6z:b-dnuksd) ([raw file](https://github.com/harness/harness-core/blob/9360dbd916be9074616bf9eb14cbc6e1e97ee901/957-cg-beans/src/main/java/software/wings/beans/artifact/Artifact.java#L125)):*
> ```Java
>   @EqualsAndHashCode.Exclude @SchemaIgnore private EmbeddedUser lastUpdatedBy;
>   @EqualsAndHashCode.Exclude @SchemaIgnore @NotNull private long lastUpdatedAt;
>   @EqualsAndHashCode.Exclude @SchemaIgnore private Long lastCollectedAt;
> ```

This bean change should go in separate release than it's usages.
This would ensure that our changes are backward compatible.

**Comment by Y0709** [comment]
trigger ti2

**Comment by Y0709** [comment]
trigger compile, ti0, ti1, ti2, ti3, ti4, ft2

**Review by inderschera — COMMENTED** [review]
> Reviewed 10 of 16 files at r3, 1 of 4 files at r4, 9 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36618)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/ArtifactCollectionState.java` line 624 at r5](https://reviewable.io/reviews/harness/harness-core/36618#-NBLYepR9mtAjkOfRdlJ:-NBLYepR9mtAjkOfRdlK:b-ftx3v5) ([raw file](https://github.com/harness/harness-core/blob/c71c4e2c21fe8537b40671e7dd717b0d3caa814f/400-rest/src/main/java/software/wings/sm/states/ArtifactCollectionState.java#L624)):*
> ```Java
>         if (savedArtifact.isDuplicate()) {
>           if (shouldUpdateMetadata(artifact, savedArtifact)) {
>             artifactService.updateMetadataAndRevision(
> ```

when this update is called is lastUpdatedAt field updated in database?

**Comment by Y0709** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36618)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/WorkflowStandardParamsExtensionService.java` line 178 at r2](https://reviewable.io/reviews/harness/harness-core/36618#-NAOr2BQ2BcjAHWK3stA:-NBWKSop9CBG5V9pTRin:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9360dbd916be9074616bf9eb14cbc6e1e97ee901/400-rest/src/main/java/software/wings/sm/WorkflowStandardParamsExtensionService.java#L178)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Should we add this inside getArtifacts() method? 
getArtifacts() is also called from multiple places. 
</blockquote></details>

done
___
*[`400-rest/src/main/java/software/wings/sm/states/ArtifactCollectionState.java` line 624 at r5](https://reviewable.io/reviews/harness/harness-core/36618#-NBLYepR9mtAjkOfRdlJ:-NBWKaKcBoyZFs8MRZEA:b-mygk88) ([raw file](https://github.com/harness/harness-core/blob/c71c4e2c21fe8537b40671e7dd717b0d3caa814f/400-rest/src/main/java/software/wings/sm/states/ArtifactCollectionState.java#L624)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

when this update is called is lastUpdatedAt field updated in database?
</blockquote></details>

yes, it will update

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 10 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36618)* status: :shipit: complete! ✓

**Pull request merged**
