### PR TITLE
[fix]: [PIE-7093]: Validations for reserved words for not to be identifier.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Issue: Certain words need to be blocked from being used as identifiers.
Change: Have added them to regex.
Testing: Expected behaviour on local, also PipelineCRUD test pas against them.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42520)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`970-ng-commons/src/main/java/io/harness/validator/NGRegexValidatorConstants.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/42520#-NL_vL6L26CV4JQNS7SD:-NL_vL6L26CV4JQNS7SE:b-fs8x9t) ([raw file](https://github.com/harness/harness-core/blob/493daccfbd2ef01c3dc011eb5d14bfb78adc742e/970-ng-commons/src/main/java/io/harness/validator/NGRegexValidatorConstants.java#L17)):*
> ```Java
> public interface NGRegexValidatorConstants {
>   String BLACKLIST_WORDS =
>       "^(?!or$|and$|eq$|ne$|it$|gt$|le$|ge$|div$|mod$|not$|null$|true$|false$|new$|var$|return$|step$|parallel$|stepGroup$|org$|account$)";
> ```

Can we construct this variable using static list?
Define a list of constants and then create this list in a static function.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42520)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/validator/NGRegexValidatorConstants.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/42520#-NL_vL6L26CV4JQNS7SD:-NLtntWA-meskkYHXQvP:bcwvgrh) ([raw file](https://github.com/harness/harness-core/blob/d7a1449960eed45b99050142881da4c424a41407/970-ng-commons/src/main/java/io/harness/validator/NGRegexValidatorConstants.java#L17)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we construct this variable using static list?
Define a list of constants and then create this list in a static function.
</blockquote></details>

Tried, but will lead to complie-time failures. Although good suggestion for execution.

**Comment by senjucanon2** [comment]
Will have more discussions with various stakeholders for this, as the impact of the change is very big. Will take this as an enhancement later after apt discussions

**Pull request closed without merging**
