### PR TITLE
feat: [PIE-9799]: Add update and delete APIs for user source code manager

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46900)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger utAll

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/SCMMapperHelper.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/46900#-NTrhhcN4UNdReHNG497:-NTrhhcN4UNdReHNG498:b50zugp) ([raw file](https://github.com/harness/harness-core/blob/63c6e24dd6f445ce359897ac307f79715a6e867f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/SCMMapperHelper.java#L46)):*
> ```Java
>   }
> 
>   public Update getUpdateOperation(UserSourceCodeManagerDTO userSourceCodeManagerDTO) {
> ```

This is a very specific update operation that creates update query for api access. So, lets name our method accordingly.

**Comment by shalini-agr** [comment]
trigger checkstylecodeformat

**Review by senjucanon2 — COMMENTED** [review]
> Reviewed 4 of 13 files at r1, 1 of 7 files at r2, 4 of 4 files at r4, 8 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46900)* status: 18 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/OauthSecretService.java` line 67 at r5](https://reviewable.io/reviews/harness/harness-core/46900#-NTw9LqI2cebFj-DKEGQ:-NTw9LqJBcgLbJKStnOk:bmisddn) ([raw file](https://github.com/harness/harness-core/blob/d2657f45fa993274b636f3fc0652083d5d6b368c/120-ng-manager/src/main/java/io/harness/ng/oauth/OauthSecretService.java#L67)):*
> ```Java
>       userMetadataDTO = ngUserService.getUserByEmail(userDetailsDTO.getUserEmail(), false);
>       if (!userMetadataDTO.isPresent()) {
>         log.error("Failed to get user details for user email: {}", userDetailsDTO.getUserEmail());
> ```

Use String.format here, it has some benefits over regular messages, and you can templatise the error message here
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java` line 161 at r5](https://reviewable.io/reviews/harness/harness-core/46900#-NTw9vy27wUMdwMuib4J:-NTw9vy27wUMdwMuib4K:bgo223d) ([raw file](https://github.com/harness/harness-core/blob/d2657f45fa993274b636f3fc0652083d5d6b368c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java#L161)):*
> ```Java
>       @Parameter(description = "userIdentifier") @QueryParam("userIdentifier") @NotNull String userIdentifier,
>       @Parameter(description = "Type of Git Provider") @QueryParam("type") @NotNull SCMType type) {
>     long deleted = userSourceCodeManagerService.delete(accountIdentifier, userIdentifier, type);
> ```

Can this delete call itself not return boolean if the operation was successful or not?

**Comment by shalini-agr** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java` line 161 at r5](https://reviewable.io/reviews/harness/harness-core/46900#-NTw9vy27wUMdwMuib4J:-NTwHdvv0KHVjd3SUMUF:bpnk27d) ([raw file](https://github.com/harness/harness-core/blob/d2657f45fa993274b636f3fc0652083d5d6b368c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java#L161)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Can this delete call itself not return boolean if the operation was successful or not?
</blockquote></details>

delete method of the repository returns the number of documents deleted from the collection

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 1 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46900)* status: 18 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 4 of 13 files at r1, 1 of 7 files at r2, 4 of 4 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46900)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger reviewq

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
