### PR TITLE
[techdebt]: [CCM-14561]: Configuring deployMode from Values

### PR DESCRIPTION
**Pull request by sdsingh07**
## Describe your changes
Configuring deployMode from Values so that we can override it for devspace.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54226)

### CODE REVIEW

**Review by iamanmolm — DISMISSED** [review]

**Review by harness-jc — APPROVED** [review]

**Comment by harness-jc** [comment]
@akshay-khole should we make this a global value?    hold on merge until we decide.

**Comment by akshay-khole** [comment]
@sdsingh07 @harness-jc  yes its would be better if this is a global value instead of making it chart specific.
Other question is how is this deploymode used in relevant module code, we are converging on various deployment methods like saas , smp and we are removing deploymode through out the code base. If you are clearing up tech debt then best thing would be to get rid of deploymode in code base and avoid these changes

**Comment by sdsingh07** [comment]
@akshay-khole @harness-jc Currently, we employ this deployMode to prevent the execution of batch jobs that are exclusively intended for the SaaS flavor, as well as for initializing BigQuery objects, among other things.

For now, I will shift it to the global scope. However, I have a query: what distinguishes the global and normal values, given that both pertain to that specific service only?

**Comment by sdsingh07** [comment]
@akshay-khole I will create a separate tracking ticket to get rid of the deployMode completely. However, for the time being, can we continue using deployMode? I will move it to the global values.

**Comment by sdsingh07** [comment]
@akshay-khole Need your inputs here.

**Comment by akshay-khole** [comment]
sounds good @sdsingh07, thanks

**Comment by sdsingh07** [comment]
https://github.com/harness/harness-core/pull/54442/files

**Pull request closed without merging**
