### PR TITLE
[fix]: [PL-24866]: Fix for Azure API response

### PR DESCRIPTION
**Pull request by mankrit-singh**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33042)

### CODE REVIEW

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33042)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java` line 146 at r1](https://reviewable.io/reviews/harness/harness-core/33042#-N1mdamSBIhwxwUALbeZ:-N1mdamSBIhwxwUALbe_:b-fcg7sc) ([raw file](https://github.com/harness/harness-core/blob/9949adcd86f679f3d43a003fa8741c8f68c7deb0/932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java#L146)):*
> ```Java
>     }
> 
>     if (reposResponse != null && isNotEmpty(reposResponse.getError())) {
> ```

Add a comment that AzureRepo returns a error with code 203

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33042)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/33042#-N1mfFi09qO-99wLGMhn:-N1mfFi09qO-99wLGMho:b90y9t6) ([raw file](https://github.com/harness/harness-core/blob/a71ed220edffdc7b38af61f9ee27ed7540c7f365/932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java#L148)):*
> ```Java
>     if (reposResponse != null && isNotEmpty(reposResponse.getError())) {
>       ErrorCode errorCode = convertScmStatusCodeToErrorCode(reposResponse.getStatus());
>       throw new ExplanationException("Azure Repo returns an error with code 203",
> ```

No , not in the error message. Add a comment for the developers

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33042)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java` line 146 at r1](https://reviewable.io/reviews/harness/harness-core/33042#-N1mfO6Y70z-mTYtciZ2:-N1mfO6Y70z-mTYtciZ3:bissx47) ([raw file](https://github.com/harness/harness-core/blob/9949adcd86f679f3d43a003fa8741c8f68c7deb0/932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java#L146)):*
> ```Java
>     }
> 
>     if (reposResponse != null && isNotEmpty(reposResponse.getError())) {
> ```

Lets do it like this

if(repoResponse != null && scmConnector istanceOf AzureRepoConnectorDTO && reposResponse == 203){
      throw new ExplanationException("Invalid Personal Access Token",
          SCMRuntimeException.builder().errorCode(errorCode).message(reposResponse.getError()).build());
}

We can add this lines

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33042)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by mankrit-singh** [comment]
trigger ti0

**Pull request closed without merging**
