### PR TITLE
[feat]: [PL-29588]: Adding logs for measuring execution time for Debezium Consumers.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
…Access Control service.

## Describe your changes
Adding logs for measuring execution time for Debezium Consumers in Access Control Service.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39696)

### CODE REVIEW

**Comment by Jimit09Gandhi** [comment]
trigger codeformat

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39696)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ResourceGroupChangeConsumerImpl.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/39696#-NGH2X8p17uF9dSblOI1:-NGH2X8p17uF9dSblOI2:b-puhr85) ([raw file](https://github.com/harness/harness-core/blob/608761be3e0a2fb65d977366c22ada6b861bf649/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ResourceGroupChangeConsumerImpl.java#L115)):*
> ```Java
> 
>     long permissionsTime = System.currentTimeMillis() - startTime;
>     log.info("ResourceGroupChangeConsumerImpl.consumeUpdateEvent: Number of ACLs created: {} for {} Time taken: {}",
> ```

Can we have time logged as part of AutoLogContext so that we can also plot the graph in GCP

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39696)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ResourceGroupChangeConsumerImpl.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/39696#-NGH2X8p17uF9dSblOI1:-NGH2pmE5xpoWEArjscB:b3qu4f8) ([raw file](https://github.com/harness/harness-core/blob/608761be3e0a2fb65d977366c22ada6b861bf649/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ResourceGroupChangeConsumerImpl.java#L115)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we have time logged as part of AutoLogContext so that we can also plot the graph in GCP
</blockquote></details>

Check DelayLogContext for example

**Comment by mohitg0795** [comment]
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ResourceGroupChangeConsumerImpl.java` line 117 at r2](https://reviewable.io/reviews/harness/harness-core/39696#-NGH_L1Y6rQMgDHvOkRG:-NGH_L1Y6rQMgDHvOkRH:b-ij7lcq) ([raw file](https://github.com/harness/harness-core/blob/d3cccddac882fb8b29ef76df6890420c0bc350f6/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ResourceGroupChangeConsumerImpl.java#L117)):*
> ```Java
> 
>     long permissionsChangeTime = System.currentTimeMillis() - startTime;
>     try (DelayLogContext ignore = new DelayLogContext(permissionsChangeTime, OVERRIDE_ERROR)) {
> ```

Can we add a similar new context that takes startTime as input and does the same job as delayLogContext? Basically there's no need to repeat doing "System.currentTime()-startTime" everytime as it can be inherent support in the context itself.
cc @ankit-harness

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39696#-:-NGI2M_d5lwBQh8wK7C9:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by boopesh007 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39696)* status: :shipit: complete! ✓

**Pull request merged**
