### PR TITLE
feat: [PIE-8453]: Improve error message if child pipeline itself is a…

### PR DESCRIPTION
**Pull request by prashantsharma04**
… parent pipeline

## Describe your changes
We are not supporting more than one level nested in pipeline chaining. Have added proper error message when user is trying to add child pipeline which itself is a parent pipeline.

Screenshot 2023-03-21 at 4 29 42 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44612)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/44612#-NPb3-7l6g5q3KLZ2w0G:-NPb3-7l6g5q3KLZ2w0H:b9nl9jv) ([raw file](https://github.com/harness/harness-core/blob/b5bb2b269d609d27087a3625e7e2c82fb4bdc0d0/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java#L102)):*
> ```Java
>     } catch (Exception e) {
>       throw new InvalidRequestException(String.format(
>           "Chained Pipeline %s, added as stage %s, in Parent Pipeline, should not be contain another Pipeline as child",
> ```

Please use some placeholders for differentiating the identifiers, eg: <id> or [id] etc, otherwise the message becomes too confusing to read.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/44612#-NPb3B69A5V7kfJJHS8l:-NPb3B69A5V7kfJJHS8m:b-mhuns6) ([raw file](https://github.com/harness/harness-core/blob/b5bb2b269d609d27087a3625e7e2c82fb4bdc0d0/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java#L100)):*
> ```Java
>     try {
>       pipelineStageHelper.validateNestedChainedPipeline(childPipelineEntity.get());
>     } catch (Exception e) {
> ```

This is a generic exception. Do you think in all possible cases of exception the root cause is only that child pipeline is also a chained pipeline?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/44612#-NPb3NXe4KnZrN9z-E2c:-NPb3NXe4KnZrN9z-E2d:b9lobrp) ([raw file](https://github.com/harness/harness-core/blob/b5bb2b269d609d27087a3625e7e2c82fb4bdc0d0/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java#L102)):*
> ```Java
>     } catch (Exception e) {
>       throw new InvalidRequestException(String.format(
>           "Chained Pipeline %s, added as stage %s, in Parent Pipeline, should not be contain another Pipeline as child",
> ```

Also can we simplify the message a bit. Its bit confusing to understand at the moment.
Can we say something like : "Pipeline used [] is itself a chained pipeline. We don't allow to chain a pipeline which is itself a chained pipeline."  The message logic may be wrong, you can fix it but a simpler message would be good here.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/44612#-NPb3tDM6De_lk3IEqjc:-NPb3tDM6De_lk3IEqjd:b-19uaji) ([raw file](https://github.com/harness/harness-core/blob/b5bb2b269d609d27087a3625e7e2c82fb4bdc0d0/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java#L100)):*
> ```Java
>     try {
>       pipelineStageHelper.validateNestedChainedPipeline(childPipelineEntity.get());
>     } catch (Exception e) {
> ```

also we should log exception here.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44612)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java` line 99 at r1](https://reviewable.io/reviews/harness/harness-core/44612#-NPb5Q_XAcheShRvAQPf:-NPb5Q_XAcheShRvAQPg:b-iax004) ([raw file](https://github.com/harness/harness-core/blob/b5bb2b269d609d27087a3625e7e2c82fb4bdc0d0/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java#L99)):*
> ```Java
>     }
>     try {
>       pipelineStageHelper.validateNestedChainedPipeline(childPipelineEntity.get());
> ```

PipelineStageHelper validateNestedChainedPipeline is throwing InvalidRequestException.
We should attach hint and explanation there



_Code quote (from pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java):_
```Java
validateNestedChainedPipeline
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/44612#-NPb3B69A5V7kfJJHS8l:-NPb5Ykt5FwBWAWwMJ-Q:b-xp03tp) ([raw file](https://github.com/harness/harness-core/blob/b5bb2b269d609d27087a3625e7e2c82fb4bdc0d0/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java#L100)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This is a generic exception. Do you think in all possible cases of exception the root cause is only that child pipeline is also a chained pipeline?
</blockquote></details>

This should only catch InvalidRequestException and rethrow it and for other exceptions, it should be internalServerException with suggestion to please contact harness support.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/44612#-NPb3NXe4KnZrN9z-E2c:-NPcNwTnEoE93btX_mHe:bsghw0m) ([raw file](https://github.com/harness/harness-core/blob/b5bb2b269d609d27087a3625e7e2c82fb4bdc0d0/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java#L102)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Also can we simplify the message a bit. Its bit confusing to understand at the moment.
Can we say something like : "Pipeline used [] is itself a chained pipeline. We don't allow to chain a pipeline which is itself a chained pipeline."  The message logic may be wrong, you can fix it but a simpler message would be good here.
</blockquote></details>

+1
we should add hint too to the error as Archit mentioned.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44612)* status: 2 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java` line 131 at r1](https://reviewable.io/reviews/harness/harness-core/44612#-NPb3mpC9c1WWuX1NJji:-NPcO70w4dZsjq6-5LtB:b32v57) ([raw file](https://github.com/harness/harness-core/blob/b5bb2b269d609d27087a3625e7e2c82fb4bdc0d0/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java#L131)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

if its same exception at both places, please use the string from a common place.
</blockquote></details>

+1

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44612)* status: 4 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/44612#-NPb3tDM6De_lk3IEqjc:-NR2gvLv6xIO-YuYoLsX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b5bb2b269d609d27087a3625e7e2c82fb4bdc0d0/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java#L100)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

also we should log exception here.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/44612#-NPb3-7l6g5q3KLZ2w0G:-NR2gw3-2N-BXCO9LvwD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b5bb2b269d609d27087a3625e7e2c82fb4bdc0d0/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java#L102)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Please use some placeholders for differentiating the identifiers, eg: <id> or [id] etc, otherwise the message becomes too confusing to read.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/44612#-NPb3NXe4KnZrN9z-E2c:-NR2gxAnEoH--sXlp6T2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b5bb2b269d609d27087a3625e7e2c82fb4bdc0d0/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java#L102)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

+1
we should add hint too to the error as Archit mentioned.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java` line 131 at r1](https://reviewable.io/reviews/harness/harness-core/44612#-NPb3mpC9c1WWuX1NJji:-NR2gxrq7iJ34J0klK1R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b5bb2b269d609d27087a3625e7e2c82fb4bdc0d0/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java#L131)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44612)* status: 4 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java` line 99 at r1](https://reviewable.io/reviews/harness/harness-core/44612#-NPb5Q_XAcheShRvAQPf:-NR2kzFh3s4hAUvlthcR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b5bb2b269d609d27087a3625e7e2c82fb4bdc0d0/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java#L99)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

PipelineStageHelper validateNestedChainedPipeline is throwing InvalidRequestException.
We should attach hint and explanation there
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/44612#-NPb3B69A5V7kfJJHS8l:-NR2kxU97SAS4TvfLF2R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b5bb2b269d609d27087a3625e7e2c82fb4bdc0d0/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java#L100)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

@archit-harness , should we create our custom exception rather than using InvalidRequestException? NestedChainedPipelineException maybe? 
</blockquote></details>

Done.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44612)* status: 4 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44612)* status: 1 change requests. 1. unresolved discussions.

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44612)* status: :shipit: complete! ✓

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 92 at r3](https://reviewable.io/reviews/harness/harness-core/44612#-NR6qPFH3NzThvQAsBg5:-NR6qPFH3NzThvQAsBg6:b-f58ttb) ([raw file](https://github.com/harness/harness-core/blob/ab379f145fd5c124db7dd95ad25ad18c22f3c0c9/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L92)):*
> ```Java
>     } catch (Exception e) {
>       log.error("Error during nested chaining validation ", e);
>       throw NestedExceptionUtils.hintWithExplanationException(String.format(NESTED_ERROR_EXCEPTION_HINT, stageName),
> ```

@prashantsharma04 we are only adding hint and explain? and not new exception?

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44612)* status: 1 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 92 at r3](https://reviewable.io/reviews/harness/harness-core/44612#-NR6qPFH3NzThvQAsBg5:-NR6t8UQ3RCyMuc7xrZa:b-s43h03) ([raw file](https://github.com/harness/harness-core/blob/ab379f145fd5c124db7dd95ad25ad18c22f3c0c9/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L92)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@prashantsharma04 we are only adding hint and explain? and not new exception?
</blockquote></details>

We are not adding any new exception.
We have used `new HintException(hintMessage, new ExplanationException(explanationMessage, cause));`

**Pull request closed without merging**
