### PR TITLE
feat: [CVS-8985]: Error budget reset

### PR DESCRIPTION
**Pull request by AbhijithHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30279)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 18 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30279)* status: 13 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLOErrorBudgetResetDTO.java, line 20 at r1](https://reviewable.io/reviews/harness/harness-core/30279#-MuQAY6-BoNzI11cZfeo:-MuQAY6-BoNzI11cZfep:b-mzc47o) ([raw file](https://github.com/harness/harness-core/blob/55d66d12b26b469e6aa77f9c7bcc6b5131177ca7/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLOErrorBudgetResetDTO.java#L20)):*
> ```Java
>   Integer remainingErrorBudgetAtReset;
>   String reason;
>   Long validTill;
> ```

let call this validUntil
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/SLOErrorBudgetReset.java, line 72 at r2](https://reviewable.io/reviews/harness/harness-core/30279#-MuQIzLa8EaAPoqEJddp:-MuQIzLa8EaAPoqEJddq:b-mofsmx) ([raw file](https://github.com/harness/harness-core/blob/1a24dd30b43c79c1f82f57f53bc5b49290177633/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/SLOErrorBudgetReset.java#L72)):*
> ```Java
>   String reason;
> 
>   @FdTtlIndex Date validTill;
> ```

let's call it validUntil to keep it consistent with other collections.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java, line 107 at r2](https://reviewable.io/reviews/harness/harness-core/30279#-MuQJa7a1OHV-dNkYrEm:-MuQJa7a1OHV-dNkYrEn:b-apiwgs) ([raw file](https://github.com/harness/harness-core/blob/1a24dd30b43c79c1f82f57f53bc5b49290177633/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L107)):*
> ```Java
>     serviceLevelObjective = updateSLOEntity(projectParams, serviceLevelObjective, serviceLevelObjectiveDTO);
>     sloHealthIndicatorService.upsert(serviceLevelObjective);
>     sloErrorBudgetResetService.clearErrorBudgetResets(projectParams, identifier);
> ```

why do we need to clear it on create? It won't be present right?
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java, line 360 at r2](https://reviewable.io/reviews/harness/harness-core/30279#-MuQK2QD7z9hSX7iR1LR:-MuQK2QD7z9hSX7iR1LS:bt6b7w8) ([raw file](https://github.com/harness/harness-core/blob/1a24dd30b43c79c1f82f57f53bc5b49290177633/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L360)):*
> ```Java
>                                       .projectIdentifier(serviceLevelObjective.getProjectIdentifier())
>                                       .build();
>     List<SLOErrorBudgetResetDTO> errorBudgetResetDTOS =
> ```

why are getting resets here?
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java, line 115 at r2](https://reviewable.io/reviews/harness/harness-core/30279#-MuQKUyG6GU71egmWklj:-MuQKUyG6GU71egmWklk:ben8wd5) ([raw file](https://github.com/harness/harness-core/blob/1a24dd30b43c79c1f82f57f53bc5b49290177633/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L115)):*
> ```Java
>     int errorBudgetMinutes = serviceLevelObjective.getTotalErrorBudgetMinutes(currentLocalDate);
>     int totalErrorBudgetMinutes =
>         SLOErrorBudgetResetUtils.activeErrorBudgetMinutes(errorBudgetResetDTOS, errorBudgetMinutes);
> ```

is it better to move this logic in the ServiceLevelObjective class?
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOErrorBudgetResetServiceImpl.java, line 42 at r2](https://reviewable.io/reviews/harness/harness-core/30279#-MuQKnmFD_vtS4dqeqyf:-MuQKnmFD_vtS4dqeqyg:b7p2v2h) ([raw file](https://github.com/harness/harness-core/blob/1a24dd30b43c79c1f82f57f53bc5b49290177633/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOErrorBudgetResetServiceImpl.java#L42)):*
> ```Java
>         projectParams, sloErrorBudgetResetDTO.getServiceLevelObjectiveIdentifier());
>     Preconditions.checkNotNull(serviceLevelObjective,
>         "SLO with identifier:" + sloErrorBudgetResetDTO.getServiceLevelObjectiveIdentifier() + " not found");
> ```

nit: you can use %s notation in Precondition instead of string concatenation. 
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/utils/SLOErrorBudgetResetUtils.java, line 17 at r2](https://reviewable.io/reviews/harness/harness-core/30279#-MuQLnZP3rCgTXdv6Q2J:-MuQLnZP3rCgTXdv6Q2K:b-e0l4dr) ([raw file](https://github.com/harness/harness-core/blob/1a24dd30b43c79c1f82f57f53bc5b49290177633/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/utils/SLOErrorBudgetResetUtils.java#L17)):*
> ```Java
>   public static int activeErrorBudgetMinutes(
>       List<SLOErrorBudgetResetDTO> errorBudgetResetDTOList, int errorBudgetMinutes) {
>     if (errorBudgetResetDTOList == null) {
> ```

I think we can move this method to ServiceLevelObjective and also we should just take List of incrementPercentage as input instead of whole DTO. I don't think passing null should be allowed.

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Review by AbhijithHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30279)* status: 16 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLOErrorBudgetResetDTO.java, line 20 at r1](https://reviewable.io/reviews/harness/harness-core/30279#-MuQAY6-BoNzI11cZfeo:-MuTvTtSDYUtMMbmzphK:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/55d66d12b26b469e6aa77f9c7bcc6b5131177ca7/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLOErrorBudgetResetDTO.java#L20)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

let call this validUntil
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java, line 107 at r2](https://reviewable.io/reviews/harness/harness-core/30279#-MuQJa7a1OHV-dNkYrEm:-MuQSabn3i-2xzQ8Dt-4:blm5x3l) ([raw file](https://github.com/harness/harness-core/blob/1a24dd30b43c79c1f82f57f53bc5b49290177633/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L107)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

why do we need to clear it on create? It won't be present right?
</blockquote></details>

We are doing it on update and delete.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java, line 360 at r2](https://reviewable.io/reviews/harness/harness-core/30279#-MuQK2QD7z9hSX7iR1LR:-MuQSs-p-9-Qd77m7Gsg:b-y7r1fp) ([raw file](https://github.com/harness/harness-core/blob/1a24dd30b43c79c1f82f57f53bc5b49290177633/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L360)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

why are getting resets here?
</blockquote></details>

Sorry, this was not getting used.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java, line 115 at r2](https://reviewable.io/reviews/harness/harness-core/30279#-MuQKUyG6GU71egmWklj:-MuTpGDH3ZXM2bflCyEw:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1a24dd30b43c79c1f82f57f53bc5b49290177633/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L115)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

is it better to move this logic in the ServiceLevelObjective class?
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOErrorBudgetResetServiceImpl.java, line 42 at r2](https://reviewable.io/reviews/harness/harness-core/30279#-MuQKnmFD_vtS4dqeqyf:-MuTvm734tUDDQQbibB2:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/1a24dd30b43c79c1f82f57f53bc5b49290177633/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOErrorBudgetResetServiceImpl.java#L42)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

nit: you can use %s notation in Precondition instead of string concatenation. 
</blockquote></details>

updated
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/utils/SLOErrorBudgetResetUtils.java, line 17 at r2](https://reviewable.io/reviews/harness/harness-core/30279#-MuQLnZP3rCgTXdv6Q2J:-MuTvogd8uS4kpN9s6iB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1a24dd30b43c79c1f82f57f53bc5b49290177633/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/utils/SLOErrorBudgetResetUtils.java#L17)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

I think we can move this method to ServiceLevelObjective and also we should just take List of incrementPercentage as input instead of whole DTO. I don't think passing null should be allowed.
</blockquote></details>

Done.

**Review by AbhijithHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30279)* status: 16 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/SLOErrorBudgetReset.java, line 72 at r2](https://reviewable.io/reviews/harness/harness-core/30279#-MuQIzLa8EaAPoqEJddp:-MuUNaQaATHKaOIOqs9J:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1a24dd30b43c79c1f82f57f53bc5b49290177633/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/SLOErrorBudgetReset.java#L72)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

let's call it validUntil to keep it consistent with other collections.
</blockquote></details>

Done.

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 18 files at r1, 8 of 9 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30279#-:-MuUOOtt-ny0jv8Jqun5:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
