### PR TITLE
[feat]: [CDS-73383]: Returned Empty Response if repo in connector is not fetched by gitToken.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Context: An existing Bug was found. Whenever we make a repoLevel connector and give access PAT of any other account, then list-repo api lists the repo of connector in response even though the connector can't access that repo.

Changes: Now list-repo api will not fetch the repo in response if the repo isn't accessible.

Impact: list-repo Api and behaviour only.

Testing: Checked this with a repo level connector having false PAT, and list-repo API, didn't sent it in response. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50001)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoHelper.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/50001#-NZPr1UgEu9-8n7gTH62:-NZPr1UgEu9-8n7gTH63:buox2l2) ([raw file](https://github.com/harness/harness-core/blob/924a7d48ea3feb98549da120de03b6aeed26a454/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoHelper.java#L63)):*
> ```Java
>   }
> 
>   public boolean validatePresenceOfRepoInResponse(List<Repository> repoList, String repoName) {
> ```

This is a generic helper method. Why does it say "inResponse" in the name? 

A simple better name could be : isRepoPresent()

Also, lets rename repoName argument to "absoluteRepoName" as I see from the implementation we aren't comparing the complete repo name here but rather only the absolute name

**Comment by senjucanon2** [comment]
trigger uts

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50001)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoHelper.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/50001#-NZPr1UgEu9-8n7gTH62:-NZQQYb5AWC59rWnkSNH:b-jee10c) ([raw file](https://github.com/harness/harness-core/blob/924a7d48ea3feb98549da120de03b6aeed26a454/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoHelper.java#L63)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This is a generic helper method. Why does it say "inResponse" in the name? 

A simple better name could be : isRepoPresent()

Also, lets rename repoName argument to "absoluteRepoName" as I see from the implementation we aren't comparing the complete repo name here but rather only the absolute name
</blockquote></details>

Renamed variable and methods

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50001)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by senjucanon2** [comment]
trigger uts

**Pull request merged**
