### PR TITLE
feat: [IDP-1310]: Audit trails for access control

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57238)

### CODE REVIEW

**Comment by devesh-harness** [comment]
trigger uts

**Review by sathish-soundarapandian — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57238)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Comment by devesh-harness** [comment]
trigger ut5, ut6, ut7, ut8, ut9

**Review by vikyathharekal — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57238#-:-NnEXYkRCfxP_XqQIiRv:bnfp4nl)* status: <span>:shipit:</span> complete! ✓

___
*[`idp-service/src/main/java/io/harness/idp/audittrails/eventhandlers/PermissionsEventHandler.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/57238#-NnEWaqH5au9gIgsc-Ut:-NnEWaqH5au9gIgsc-Uu:b-ealss9) ([raw file](https://github.com/harness/harness-core/blob/01d33e155f0dc31fbb2b0a4fc4a3b6ae23a44c38/idp-service/src/main/java/io/harness/idp/audittrails/eventhandlers/PermissionsEventHandler.java#L36)):*
> ```Java
> 
> @Slf4j
> public class PermissionsEventHandler implements OutboxEventHandler {
> ```

nit: @OwnedBy(HarnessTeam.IDP)



_Code quote:_
```Java
PermissionsEventHandler
```
___
*[`idp-service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/57238#-NnEWrDI9LWfw98fwvNF:-NnEWrDJD-seWeXRS8Ez:b29fpf4) ([raw file](https://github.com/harness/harness-core/blob/01d33e155f0dc31fbb2b0a4fc4a3b6ae23a44c38/idp-service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java#L15)):*
> ```Java
> import io.harness.annotations.dev.HarnessTeam;
> import io.harness.annotations.dev.OwnedBy;
> import io.harness.idp.common.CommonUtils;
> ```

nit: unused



_Code quote:_
```Java
CommonUtils
```
___
*[`idp-service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/57238#-NnEXE6bAd57eS3hsN9n:-NnEXE6bAd57eS3hsN9o:bp67qc1) ([raw file](https://github.com/harness/harness-core/blob/01d33e155f0dc31fbb2b0a4fc4a3b6ae23a44c38/idp-service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java#L73)):*
> ```Java
>       BackstagePermissions updatedBackstagePermissions =
>           BackstagePermissionsMapper.toDTO(backstagePermissionsRepository.update(permissionsEntity));
>       BackstagePermissions oldBackstagePermissions = oldPermissionsEntity.map(BackstagePermissionsMapper::toDTO).get();
> ```

nit: We are calling get() without checking ifPresent(). Mostly shouldn't be a problem as we'll have a permission entity for any account. But good to check and then call get()



_Code quote:_
```Java
get
```

**Comment by devesh-harness** [comment]
trigger ut7

**Comment by devesh-harness** [comment]
trigger review

**Pull request merged**
