### PR TITLE
fix: [CDS-69342]: use jsonNode for field yaml in execution input helper

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48473)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48473)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/48473#-NWbV7du8YaQZDRBz0Mj:-NWbV7dv3dolQrg4eJ5C:br0ne91) ([raw file](https://github.com/harness/harness-core/blob/69470f2647069134c34a567e80d9e29755ac5ad4/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L112)):*
> ```Java
>       return mapper.writeValueAsString(object);
>     } catch (JsonProcessingException e) {
>       throw new InvalidRequestException("Couldn't convert object to Yaml");
> ```

we should add exception using String.format, lets do change in develop as well
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 120 at r1](https://reviewable.io/reviews/harness/harness-core/48473#-NWbVLWzCwRIZpZR_90v:-NWbVLWzCwRIZpZR_90w:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/69470f2647069134c34a567e80d9e29755ac5ad4/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L120)):*
> ```Java
>       return mapper.writeValueAsString(object).replace("---\n", "");
>     } catch (JsonProcessingException e) {
>       throw new InvalidRequestException("Couldn't convert object to Yaml");
> ```

same as above

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger ut5, ut7

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48473)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/48473#-NWbV7du8YaQZDRBz0Mj:-NWbrVw61QqzVeWkhW5m:bruznx2) ([raw file](https://github.com/harness/harness-core/blob/69470f2647069134c34a567e80d9e29755ac5ad4/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L112)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

my mistake i thoughts its logging, i meant pass exception to invalidRequestException constructor so cause is logged

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48473)* status: 14 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/48473#-NWbV7du8YaQZDRBz0Mj:-NWbtD1zB0ymzWqcN65W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/69470f2647069134c34a567e80d9e29755ac5ad4/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L112)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

my mistake i thoughts its logging, i meant pass exception to invalidRequestException constructor so cause is logged
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger ut5, ut7

**Comment by shalini-agr** [comment]
trigger ut5, ut7

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48473)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Pull request merged**
