### PR TITLE
feat: [CI-3626]: Creating relevant connector and Delegate group

### PR DESCRIPTION
**Pull request by HenAmar**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31978)

### CODE REVIEW

**Comment by jennyjames21** [comment]
*[120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java, line 176 at r2](https://reviewable.io/reviews/harness/harness-core/31978#-N-_2R25D0dkPQn638bg:-N-_2R26DMrUW12KYtH8:b6843n4) ([raw file](https://github.com/harness/harness-core/blob/17c44a269001945b5795f1ab01d05c1a623c3917/120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java#L176)):*
> ```Java
>             .k8sConfigDetails(
>                 K8sConfigDetails.builder().k8sPermissionType(K8sPermissionType.NAMESPACE_ADMIN).namespace("xx").build())
>             .delegateType("KUBERNETES")
> ```

DelegateType.KUBERNETES

**Comment by jennyjames21** [comment]
*[120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java, line 188 at r2](https://reviewable.io/reviews/harness/harness-core/31978#-N-_2hjs2KaAe5Mfd7zd:-N-_2hjs2KaAe5Mfd7ze:b-s5f7jl) ([raw file](https://github.com/harness/harness-core/blob/17c44a269001945b5795f1ab01d05c1a623c3917/120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java#L188)):*
> ```Java
>       }
>     } catch (IOException e) {
>       log.error("Upserting delegate group failed. Account ID {}", accountId);
> ```

print exception also???

**Comment by jennyjames21** [comment]
As discussed please move resource to new file on next checkin, after last week of april.

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31978)* status: 0 of 1 approvals obtained.

**Review by jennyjames21 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31978#-:-N-_3ZZV2j-RSt46dihk:bnfp4nl)* status: :shipit: complete! ✓

**Review by aman-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31978#-:-N-bTUIO7exXj-ErUx1U:bnfp4nl)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 1 of 1 files at r3, 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31978)* status: :shipit: complete! ✓

**Pull request merged**
