### PR TITLE
[fix]: [CDS-42085]: adding logic with feature flag OPTIMIZED_TF_PLAN_NG for storing tf plan to GCS/GridFS

### PR DESCRIPTION
**Pull request by akhilpandey1**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37013)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 26 Issues 
* Vulnerability 11 Vulnerabilities 
 * Code issue 15 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37013)

**Comment by akhilpandey1** [comment]
trigger compile,trigger codeformat,trigger messagecheck,trigger recency,trigger buildnum,trigger dockerizationcheck,trigger authorcheck,trigger checkstyle,trigger pmd,trigger ti0,trigger ti1,trigger ti2,trigger ti3,trigger ti4,trigger ft1,trigger ft2,
trigger codebasehash

**Comment by akhilpandey1** [comment]
trigger messagecheck

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37013)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37013)* status: :shipit: complete! ✓

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37013)* status: :shipit: complete! ✓

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 422 at r4](https://reviewable.io/reviews/harness/harness-core/37013#-NAt4LTc-xSPPHcAA1sZ:-NAt4LTd6uLX42bTQXR3:b-wxswx6) ([raw file](https://github.com/harness/harness-core/blob/6723d6dda888f52d852d32838b23e929089f274a/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L422)):*
> ```Java
>   GIT_WEBHOOK_POLLING("Used to poll git webhook recent delivery events", HarnessTeam.CDP),
>   TRIGGERS_REFACTOR("Enable NG Triggers UI refactoring", HarnessTeam.CDP),
>   NG_SERVICE_MANIFEST_OVERRIDE("Enable Service Manifests override from Environment", HarnessTeam.CDP),
> ```

do we want to add those FF?

**Comment by akhilpandey1** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 422 at r4](https://reviewable.io/reviews/harness/harness-core/37013#-NAt4LTc-xSPPHcAA1sZ:-NAtOCoY0lhSEUR1qvjq:b-vmn3va) ([raw file](https://github.com/harness/harness-core/blob/6723d6dda888f52d852d32838b23e929089f274a/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L422)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

do we want to add those FF?
</blockquote></details>

This is per @markoharness PR cherry pick, so I think yes

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37013)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37013)* status: :shipit: complete! ✓

**Comment by akhilpandey1** [comment]
trigger ti3

**Comment by akhilpandey1** [comment]
trigger ft1

**Comment by akhilpandey1** [comment]
trigger ti2

**Comment by akhilpandey1** [comment]
trigger ti0

**Comment by akhilpandey1** [comment]
trigger ti1,trigger ti3,trigger ti4

**Comment by akhilpandey1** [comment]
trigger ft2

**Comment by akhilpandey1** [comment]
trigger compile

**Comment by akhilpandey1** [comment]
trigger ti2

**Comment by akhilpandey1** [comment]
trigger ti2, trigger ti4, trigger ft2

**Pull request merged**
