### PR TITLE
fix: [CDS-41613]: Fix settings YAML schema

### PR DESCRIPTION
**Pull request by abosii-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36250)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 6 Issues 
* Code issue 6 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36250)

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36250)* status: :shipit: complete! ✓

**Review by abosii-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36250)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 268 at r2](https://reviewable.io/reviews/harness/harness-core/36250#-N96eNn53FmBzxfMeRmw:-N96lbdk947YhWJG4Apo:b-u78dlh) ([raw file](https://github.com/harness/harness-core/blob/782f21b7c6d91e97c6beb136edb055e0940307a6/120-ng-manager/config.yml#L268)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

We don't need it :)
</blockquote></details>

yeah.. reverted

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36250)* status: :shipit: complete! ✓

**Comment by abosii-harness** [comment]
trigger messagecheck

**Comment by abosii-harness** [comment]
trigger messagecheck

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 20 of 21 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36250)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36250)* status: :shipit: complete! ✓

**Review by vlica-harness — APPROVED** [review]

**Review by hextechpal — APPROVED** [review]
> Reviewed 20 of 21 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36250)* status: :shipit: complete! ✓

**Pull request merged**
