### PR TITLE
feat: [CDS-35108]: Support for Custom Deployment in NG

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37069)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 40 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 32 Code issues 
* Anti-pattern 6 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37069)

**Comment by aman-harness** [comment]
trigger messagecheck

**Review by inderschera — COMMENTED** [review]
> Reviewed 6 of 103 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37069)* status: 97 file(s) to review. 0 of 1 approvals obtained.

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 88 of 103 files at r1, 11 of 13 files at r2, 3 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37069#-:-NBJ2wHS3lKdRXiKw-Tg:bnfp4nl)* status: :shipit: complete! ✓

**Comment by RishabhGupta34** [comment]
trigger openapibackwardcompatibilitychecks

**Comment by RishabhGupta34** [comment]
trigger openapibackwardcompatibilitycheck

**Comment by RishabhGupta34** [comment]
trigger openapibackwardcompatibility

**Review by hextechpal — APPROVED** [review]
> Reviewed 87 of 103 files at r1, 11 of 13 files at r2, 3 of 3 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37069)* status: :shipit: complete! ✓

**Review by arpit3107 — APPROVED** [review]
Approving only for 260-delegate files.

> Reviewed 87 of 103 files at r1, 11 of 13 files at r2, 3 of 3 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37069#-:-NBMCCIS6mdgrsYPlUug:bhjsh5t)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37069#-:-NBMEylb8wdiDZTKB3TC:bnfp4nl)* status: :shipit: complete! ✓

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 87 of 103 files at r1, 11 of 13 files at r2, 3 of 3 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37069#-:-NBMfCyX9wMSTTF2hL0q:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
