### PR TITLE
[fix]: [cds-39421]: Hotfix qa for publishSetupUsageEvent

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34966)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34966)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 260 at r2](https://reviewable.io/reviews/harness/harness-core/34966#-N67zRtg5ST3j8UuSYV3:-N67zRtg5ST3j8UuSYV4:b4wldth) ([raw file](https://github.com/harness/harness-core/blob/0af8350bdfa5886a32768c89a233efad082c3669/120-ng-manager/config.yml#L260)):*
> ```YAML
>   authority: localhost
> 
> shouldConfigureWithPMS: true
> ```

revert this



_Code quote:_
```YAML
true
```

**Review by utkarshchoubey-harness — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34966)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 260 at r2](https://reviewable.io/reviews/harness/harness-core/34966#-N67zRtg5ST3j8UuSYV3:-N67zi8ODh70x6FM01eO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0af8350bdfa5886a32768c89a233efad082c3669/120-ng-manager/config.yml#L260)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

revert this
</blockquote></details>

Done.

**Review by inderschera — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34966)* status: 1 change requests. 1. unresolved discussions.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34966)* status: :shipit: complete! ✓

**Pull request merged**
