### PR TITLE
feat: [DEL-4963]: Reduce Mongo footprints to update delegate heartbeat by deprecating DelegateConnection entity

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes

Summary:
- Consolidating delegate heartbeat Mongo updates to reduce footprints

Problem Statement:
- Currently, we have 2 different ways to update heartbeat registration from the delegate, one is to update lastHeartBeat in delegate entity as well as an entry to collection DelegateConnections. The purpose behind both is to track delegate liveness
Delegate HB(HeartBeat) call frequency is one per minute per delegate.

Solution:
- Deprecate DelegateConnections usage and rely on HB from the delegate entity. This will reduce half of the HB(HeartBeat) update + read calls to mongo.  

Test:
CG
- Install CG k8,shell,docker delegate and verify HB updating in DB, verify in UI with older version of the delegate
- Install CG k8,shell,docker delegate and verify HB updating in DB, verify in UI with updated version of the delegate
- Install CG Polling mode delegate and verify HB updating in DB, verify in UI with the older version of the delegate
- Install CG Polling mode delegate and verify HB updating in DB, verify in UI with updated version of the delegate
- K8 task end-to-end flow
- Test delete delegate flow, 1)verify status in DB and UI as disconnected 2)Delete from UI when connected and disconnected
- Test HB update from 2 same location with same delegate connection id and verify self-destruct happening for both polling mode and streaming mode delegate 
- Verify HB updates reflect while delegate restart both in UI and DB
- Verify HB update on new version upgrade
- Verify listing delegate status with Delegate groups

NG
- Install CG k8, docker delegate and verify HB updating in DB, verify in UI with older version of the delegate
- Install CG k8,docker delegate and verify HB updating in DB, verify in UI with updated version of the delegate
- NG pipeline execution, task end-to-end flow
- Test delete delegate and verify status in DB and UI as disconnected
- Verify HB updates reflect while delegate restart both in UI and DB
- Verify HB update on new version upgrade
- Verify listing delegate status with Delegate groups

Immutable
-Verify upgrader, unregister and display of connected delegates in the UI

 GraphQL
- List delegate API call

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42897)

### CODE REVIEW

**Comment by jennyjames21** [comment]
CG Same Delegate Version

K8 Task flow 
image
Shell Task pipeline with non polling mode
image
Shell Task pipeline with polling mode
image


Shell Delegate, verified status
image

K8 Delegate with 2 replicas and verified status
image

Polling Mode Delegate, status verified
image

**Comment by jennyjames21** [comment]
NG  - same version
Delegate with 2 replicas  - verified status and HB update
image
NG pipeline execution with shell script task
image

**Comment by jennyjames21** [comment]
Version upgrade - Verify the new version is showing up in the available version UI list 
image

**Comment by jennyjames21** [comment]
CG  Older version Delegate - verified HB and status on UI
image
CG Task execution with older delegate
image

**Comment by jennyjames21** [comment]
NG Delegate-older version 
image
NG Task execution with older delegate version 
image

**Comment by raghuAtWings** [comment]
*[`380-cg-graphql/src/main/java/io/harness/app/datafetcher/delegate/DelegateListDataFetcher.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/42897#-NMW0obr7ma_CCMj7kyd:-NMW0obs6gsiZIhFi5bv:b53bqx8) ([raw file](https://github.com/harness/harness-core/blob/78524e6e31d77fac990d1d763175404fda3bf8c9/380-cg-graphql/src/main/java/io/harness/app/datafetcher/delegate/DelegateListDataFetcher.java#L54)):*
> ```Java
>       List<DelegateConnection> delegateConnections =
>           delegateConnectionDao.list(delegate.getAccountId(), delegate.getUuid());
>       DelegateController.populateQLDelegate(delegate, qlBuilder, delegateConnections);
> ```

what was the functionality with delegateConnections and the graphQL api?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatDao.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/42897#-NMW10uO-8NTQUlbDtrn:-NMW10uO-8NTQUlbDtro:bpda7wt) ([raw file](https://github.com/harness/harness-core/blob/c166bb3b724185f09dec947afaba2a5423ea72db/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatDao.java#L41)):*
> ```Java
>     setUnset(updateOperations, DelegateKeys.validUntil, validUntil);
>     setUnset(updateOperations, DelegateKeys.version, params.getVersion());
>     setUnset(updateOperations, DelegateKeys.location, params.getLocation());
> ```

what is location used for?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/42897#-NMW1sfs9dGHDIu2VRNC:-NMW1sfs9dGHDIu2VRND:b-7wdgor) ([raw file](https://github.com/harness/harness-core/blob/c166bb3b724185f09dec947afaba2a5423ea72db/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java#L68)):*
> ```Java
> 
>   public Optional<T> precheck(@NotNull final Delegate existingDelegate, @NotNull final DelegateHeartbeatParams params) {
>     if (isNotEmpty(existingDelegate.getDelegateConnectionId())) {
> ```

don't understand this change

**Comment by jennyjames21** [comment]
*[`380-cg-graphql/src/main/java/io/harness/app/datafetcher/delegate/DelegateListDataFetcher.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/42897#-NMW0obr7ma_CCMj7kyd:-NMW1wDz-lqmK9IZFvEB:b9030nw) ([raw file](https://github.com/harness/harness-core/blob/78524e6e31d77fac990d1d763175404fda3bf8c9/380-cg-graphql/src/main/java/io/harness/app/datafetcher/delegate/DelegateListDataFetcher.java#L54)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

what was the functionality with delegateConnections and the graphQL api?
</blockquote></details>

Only for the display of delegate connection with delegate to show connected and version

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/grpc/pingpong/PingPongService.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/42897#-NMW24Ao9lC_5Sbn59p9:-NMW24Ao9lC_5Sbn59pA:b-bo03pl) ([raw file](https://github.com/harness/harness-core/blob/c166bb3b724185f09dec947afaba2a5423ea72db/400-rest/src/main/java/io/harness/grpc/pingpong/PingPongService.java#L31)):*
> ```Java
> @TargetModule(HarnessModule._420_DELEGATE_SERVICE)
> @Slf4j
> public class PingPongService extends PingPongServiceImplBase {
> ```

do we need this? there is no grpc requirement now right? can we get rid of this?

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatDao.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/42897#-NMW10uO-8NTQUlbDtrn:-NMW2NpFD-rQ3CZ1Z-_o:b-wod73f) ([raw file](https://github.com/harness/harness-core/blob/c166bb3b724185f09dec947afaba2a5423ea72db/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatDao.java#L41)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

what is location used for?
</blockquote></details>

only for shell script delegate. Only one delegate can be installed from one location

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/42897#-NMW1sfs9dGHDIu2VRNC:-NMW2XLX9FR4xoqKlsvD:b-2k4t6s) ([raw file](https://github.com/harness/harness-core/blob/c166bb3b724185f09dec947afaba2a5423ea72db/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java#L68)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

don't understand this change
</blockquote></details>

Refer registerHeart() method in DelegateServiceImpl which is called from DelegateStreamHandler and polling api to insert delegate connections

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/grpc/pingpong/PingPongService.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/42897#-NMW24Ao9lC_5Sbn59p9:-NMW2ls2DcdsTFAmwN-6:b-le1fb) ([raw file](https://github.com/harness/harness-core/blob/c166bb3b724185f09dec947afaba2a5423ea72db/400-rest/src/main/java/io/harness/grpc/pingpong/PingPongService.java#L31)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

do we need this? there is no grpc requirement now right? can we get rid of this?
</blockquote></details>

lets me remove that later when we clean up all codes related to grpc

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/grpc/pingpong/PingPongService.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/42897#-NMW24Ao9lC_5Sbn59p9:-NMW2t12B-7mdGnyY_FW:b-1at4gc) ([raw file](https://github.com/harness/harness-core/blob/c166bb3b724185f09dec947afaba2a5423ea72db/400-rest/src/main/java/io/harness/grpc/pingpong/PingPongService.java#L31)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

lets me remove that later when we clean up all codes related to grpc
</blockquote></details>

just removing usage here, we can delete this call later. Its' not used in delegate anymore

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42897)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger messagecheck

**Pull request merged**
