### PR TITLE
feat: [CVNG-3987]: Dynatrace Integration for Change Intelligence

### PR DESCRIPTION
**Pull request by slobodanpavic**
PR Codebasehash Check merge checklist:
1. This is new task type

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30265)

### CODE REVIEW

**Comment by slobodanpavic** [comment]
trigger messagecheck

**Comment by slobodanpavic** [comment]
trigger authorcheck

**Comment by slobodanpavic** [comment]
trigger authorcheck

**Comment by praveensugavanam** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/DynatraceHealthSourceSpec.java, line 154 at r3](https://reviewable.io/reviews/harness/harness-core/30265#-Muw6FYT0rpOR-PqRCGp:-Muw6FYT0rpOR-PqRCGq:bmznwx0) ([raw file](https://github.com/harness/harness-core/blob/8055e13f67712af76cb96615a6b52620a2421397/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/DynatraceHealthSourceSpec.java#L154)):*
> ```Java
>   private Key getKeyFromCVConfig(DynatraceCVConfig cvConfig) {
>     return Key.builder()
>         .serviceName(cvConfig.getServiceName())
> ```

what is the reason for adding service name to this ? Pretty much everything coming into this healthsourcespec will have the same serviceName. So it doesnt have to be here

**Comment by praveensugavanam** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/DynatraceHealthSourceSpec.java, line 164 at r3](https://reviewable.io/reviews/harness/harness-core/30265#-Muw6PQjDINfpms2cLOR:-Muw6PQjDINfpms2cLOS:b-iogyop) ([raw file](https://github.com/harness/harness-core/blob/8055e13f67712af76cb96615a6b52620a2421397/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/DynatraceHealthSourceSpec.java#L164)):*
> ```Java
>   private static class Key {
>     String groupName;
>     String serviceName;
> ```

No need to have serviceName in Key

**Comment by praveensugavanam** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/DynatraceCVConfig.java, line 34 at r3](https://reviewable.io/reviews/harness/harness-core/30265#-Muw6fmq8YCC9BsMtSjr:-Muw6fmr8_5FPbOq_mRv:b-mxcb54) ([raw file](https://github.com/harness/harness-core/blob/8055e13f67712af76cb96615a6b52620a2421397/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/DynatraceCVConfig.java#L34)):*
> ```Java
> @EqualsAndHashCode(callSuper = true)
> public class DynatraceCVConfig extends MetricCVConfig {
>   private String serviceName;
> ```

is this the serviceName in dynatrace ? Can we make it more explicit ?

**Comment by praveensugavanam** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java, line 37 at r3](https://reviewable.io/reviews/harness/harness-core/30265#-Muw8ZPq0Z5rAQr3agBE:-Muw8ZPq0Z5rAQr3agBF:bholwmg) ([raw file](https://github.com/harness/harness-core/blob/8055e13f67712af76cb96615a6b52620a2421397/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java#L37)):*
> ```Java
> 
>   @Override
>   public List<DynatraceServiceDTO> getAllServices(
> ```

is this call paginated ? What if the list of services is 50000. UI will not be able to handle that list. We should limit the return list to 500 and then proceed by filter option if it's not available in that list

**Comment by praveensugavanam** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java, line 53 at r3](https://reviewable.io/reviews/harness/harness-core/30265#-Muw8mu10xuAHYT69OIF:-Muw8mu10xuAHYT69OIG:b-oygd08) ([raw file](https://github.com/harness/harness-core/blob/8055e13f67712af76cb96615a6b52620a2421397/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java#L53)):*
> ```Java
>   }
> 
>   @Override
> ```

same as above. This has the potential to freeze up the UI. We should limit the list of metrics being sent back

**Comment by praveensugavanam** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java, line 79 at r3](https://reviewable.io/reviews/harness/harness-core/30265#-Muw8vSE6xk1AZqAugLG:-Muw8vSE6xk1AZqAugLH:bybz34v) ([raw file](https://github.com/harness/harness-core/blob/8055e13f67712af76cb96615a6b52620a2421397/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java#L79)):*
> ```Java
> 
>   @Override
>   public Set<MetricPackValidationResponse> validateData(ProjectParams projectParams, String connectorIdentifier,
> ```

please add logs

**Review by praveensugavanam — COMMENTED** [review]
> Reviewed 2 of 45 files at r1, 8 of 31 files at r2, 5 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30265)* status: Some of the checks are too old. 34 file(s) to review. 0 of 1 approvals obtained.

**Review by slobodanpavic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30265)* status: Some of the checks are too old. 34 file(s) to review. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/DynatraceHealthSourceSpec.java, line 154 at r3](https://reviewable.io/reviews/harness/harness-core/30265#-Muw6FYT0rpOR-PqRCGp:-MuwQ9OX09BhORd6nXU-:b-1oqz77) ([raw file](https://github.com/harness/harness-core/blob/8055e13f67712af76cb96615a6b52620a2421397/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/DynatraceHealthSourceSpec.java#L154)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

what is the reason for adding service name to this ? Pretty much everything coming into this healthsourcespec will have the same serviceName. So it doesnt have to be here
</blockquote></details>

You are right. We can remove it.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/DynatraceHealthSourceSpec.java, line 164 at r3](https://reviewable.io/reviews/harness/harness-core/30265#-Muw6PQjDINfpms2cLOR:-MuwQ5la3whLQc7ebeiE:bqzl78c) ([raw file](https://github.com/harness/harness-core/blob/8055e13f67712af76cb96615a6b52620a2421397/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/DynatraceHealthSourceSpec.java#L164)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

No need to have serviceName in Key
</blockquote></details>

Correct, will remove it.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/DynatraceCVConfig.java, line 34 at r3](https://reviewable.io/reviews/harness/harness-core/30265#-Muw6fmq8YCC9BsMtSjr:-MuwQMu7ArK498Tx2gfl:b-epz2ef) ([raw file](https://github.com/harness/harness-core/blob/8055e13f67712af76cb96615a6b52620a2421397/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/DynatraceCVConfig.java#L34)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

is this the serviceName in dynatrace ? Can we make it more explicit ?
</blockquote></details>

Yes, it is Dynatrace service name. Yes, will change the name.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java, line 32 at r3](https://reviewable.io/reviews/harness/harness-core/30265#-Muw8POREzRyuxsEhCCD:-MuzLpYj0SMvQ8DD1ZGI:b-bqm6h6) ([raw file](https://github.com/harness/harness-core/blob/8055e13f67712af76cb96615a6b52620a2421397/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java#L32)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

please add more logs to all the methods in this service. Logs help us debug if something goes wrong
</blockquote></details>

Will add.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java, line 37 at r3](https://reviewable.io/reviews/harness/harness-core/30265#-Muw8ZPq0Z5rAQr3agBE:-MuwN3orAs1jP66jNt-1:b-cqter1) ([raw file](https://github.com/harness/harness-core/blob/8055e13f67712af76cb96615a6b52620a2421397/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java#L37)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

is this call paginated ? What if the list of services is 50000. UI will not be able to handle that list. We should limit the return list to 500 and then proceed by filter option if it's not available in that list
</blockquote></details>

Dynatrace API returns maximum of 500 services, so no need to limit at this level.
Also, we are filtering services using selector: "type(\"dt.entity.service\"),toRelationships.isServiceMethodOfService(type(\"dt.entity.service_method\"))", which returns only services that have marked requests as Key Request on Dynatrace.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java, line 53 at r3](https://reviewable.io/reviews/harness/harness-core/30265#-Muw8mu10xuAHYT69OIF:-MuwOk4l8gof6EoBzbfU:b-rluc6p) ([raw file](https://github.com/harness/harness-core/blob/8055e13f67712af76cb96615a6b52620a2421397/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java#L53)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

same as above. This has the potential to freeze up the UI. We should limit the list of metrics being sent back
</blockquote></details>

Same as for services, Dynatrace limit is 500 results per request. Here, we are filtering metrics using "builtin:service.*". The number of builtin service metrics for Dynatrace is 70.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java, line 79 at r3](https://reviewable.io/reviews/harness/harness-core/30265#-Muw8vSE6xk1AZqAugLG:-MuzLrge68a5oaltiXND:b2nhll9) ([raw file](https://github.com/harness/harness-core/blob/8055e13f67712af76cb96615a6b52620a2421397/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java#L79)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

please add logs
</blockquote></details>

Ok.

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
We now have a way to write tests for DSLs. Please write tests for all the DSLs. You can plan it after merging also if you want.
Please check AppDynamicsDataCollectionDSLTest for example and HoverflyTestBase for instructions on how to write these tests.

> Reviewed 12 of 45 files at r1, 13 of 31 files at r2, 6 of 11 files at r3, 18 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30265#-:-MvIOTUCBO1WS5fpSqox:b-6yp9s8)* status: 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java, line 41 at r5](https://reviewable.io/reviews/harness/harness-core/30265#-MvIMSdHDIwXOrU2oybE:-MvIMSdHDIwXOrU2oybF:b-rcwr8k) ([raw file](https://github.com/harness/harness-core/blob/4c2040d958191afe12e1c9803b1a9cf4e5679d27/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java#L41)):*
> ```Java
>   public List<DynatraceServiceDTO> getAllServices(
>       ProjectParams projectParams, String connectorIdentifier, String tracingId) {
>     Instant now = Instant.now();
> ```

please use clock 
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java, line 132 at r5](https://reviewable.io/reviews/harness/harness-core/30265#-MvIMriG0v3oSBLKnkiO:-MvIMriG0v3oSBLKnkiP:b-smefnr) ([raw file](https://github.com/harness/harness-core/blob/4c2040d958191afe12e1c9803b1a9cf4e5679d27/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java#L132)):*
> ```Java
>                                              .type(DataCollectionRequestType.DYNATRACE_SAMPLE_DATA_REQUEST)
>                                              .build();
>     log.debug("Created {} request with params: serviceId {}, metricSelector: {}, from: {}, to: {}", request.getType(),
> ```

I think we can add info logs instead of debug. we don't have debug logs enabled in prod.

**Review by slobodanpavic — COMMENTED** [review]
Sure, let's then first merge this PR.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30265#-:-MvIcgXp6MD31LEqQ9xB:b-dz625e)* status: 2 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java, line 41 at r5](https://reviewable.io/reviews/harness/harness-core/30265#-MvIMSdHDIwXOrU2oybE:-MvIcZBj49fjG8ErxHAE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c2040d958191afe12e1c9803b1a9cf4e5679d27/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java#L41)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

please use clock 
</blockquote></details>

Done.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java, line 132 at r5](https://reviewable.io/reviews/harness/harness-core/30265#-MvIMriG0v3oSBLKnkiO:-MvIcUsoAM4dSl0oaVNn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c2040d958191afe12e1c9803b1a9cf4e5679d27/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DynatraceServiceImpl.java#L132)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

I think we can add info logs instead of debug. we don't have debug logs enabled in prod.
</blockquote></details>

Done.

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30265)* status: 7. unresolved discussions.

**Comment by slobodanpavic** [comment]
trigger authorcheck

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30265#-:-MvJDaVdChTW9tFGIQjj:bnfp4nl)* status: 7. unresolved discussions.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 12 of 45 files at r1, 12 of 31 files at r2, 6 of 11 files at r3, 12 of 18 files at r5, 3 of 5 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30265)* status: 7. unresolved discussions.

**Review by AbhijithHarness — DISMISSED** [review]
> Reviewed 12 of 45 files at r1, 12 of 31 files at r2, 6 of 11 files at r3, 12 of 18 files at r5, 3 of 5 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30265)* status: 7. unresolved discussions.

**Comment by slobodanpavic** [comment]
trigger authorcheck

**Pull request merged**
