### PR TITLE
feat: [DEL-3119]: Add health endpoint

### PR DESCRIPTION
**Pull request by mdmilic**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30087)

### CODE REVIEW

**Comment by mdmilic** [comment]
trigger publish-delegate

**Comment by mdmilic** [comment]
trigger publish-delegate

**Comment by mdmilic** [comment]
trigger publish-delegate

**Comment by mdmilic** [comment]
trigger publish-delegate

**Comment by mdmilic** [comment]
trigger publish-delegate

**Comment by mdmilic** [comment]
trigger publish-delegate

**Comment by mdmilic** [comment]
trigger publish-delegate

**Comment by mdmilic** [comment]
trigger publish-delegate

**Comment by mdmilic** [comment]
trigger publish-delegate

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 9 of 10 files at r3, 1 of 2 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 1 of 3 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30087)* status: :shipit: complete! ✓

**Pull request merged**
