### PR TITLE
fix: [CDS-69259]: save freeze entity outcome in service step

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
Save freeze entity map constructed in service step in sweeping output, to be used in environment step. This is done because with Service V1, we won't have the env. data in service step and so if a user adds both service and environment filters in the freeze it won't match with the service Step.
Now in environment step we can consume this output and have the whole data and it will match with the freeze configured.

Tested in local environment

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47753)

### CODE REVIEW

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger messagecheck

**Review by abhinavmittal-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47753)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/freeze/FreezeEntityMetadataOutcome.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/47753#-NVFZ-Ft67lPneklNEK8:-NVFZ-Ft67lPneklNEK9:b-u2d34t) ([raw file](https://github.com/harness/harness-core/blob/d4297e819be3bfb5f868c45a6abdf288df3b7089/127-cd-nextgen-entities/src/main/java/io/harness/cdng/freeze/FreezeEntityMetadataOutcome.java#L31)):*
> ```Java
> @JsonTypeName("freezeEntityMetadataOutcome")
> @RecasterAlias("io.harness.cdng.freeze.FreezeEntityMetadataOutcome")
> public class FreezeEntityMetadataOutcome implements Outcome, ExecutionSweepingOutput {
> ```

Maybe we don't need Outcome here
Just Weeping output should work
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/stepsdependency/constants/OutcomeExpressionConstants.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/47753#-NVFZ_Qu1E7bYgUzz2oX:-NVFZ_Qu1E7bYgUzz2oY:b8dahzd) ([raw file](https://github.com/harness/harness-core/blob/d4297e819be3bfb5f868c45a6abdf288df3b7089/127-cd-nextgen-entities/src/main/java/io/harness/cdng/stepsdependency/constants/OutcomeExpressionConstants.java#L70)):*
> ```Java
>   public final String ASG_ROLLING_PREPARE_ROLLBACK_DATA_OUTCOME = "asgRollingPrepareRollbackDataOutcome";
>   public final String TAS_APP_SETUP_OUTCOME = "TasAppSetupOutcome";
>   public final String FREEZE_ENTITY_METADATA_OUTCOME = "FreezeEntityMetadataOutcome";
> ```

If we change to weeping output then the name also

**Comment by RishabhGupta34** [comment]
trigger uts

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47753)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by abhinavmittal-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47753)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by RishabhGupta34** [comment]
trigger uts, messagecheck

**Review by sourabh-awashti — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by RishabhGupta34** [comment]
trigger review

**Pull request merged**
