### PR TITLE
fix: [CDS-49609]: Remote WINRM logs - not streaming

### PR DESCRIPTION
**Pull request by bojanmicovic**
## Describe your changes
Using different method for executing command on a remote to stream the logs instead of waiting for the response and reading the logs.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43081)

### CODE REVIEW

**Review by ivan-83 — APPROVED** [review]
:lgtm:  Just add a description for changes.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43081#-:-NMhYf6l49KwWyZJZAV-:b-9sbuh)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by vladimir-peric** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmSession.java` line 241 at r1](https://reviewable.io/reviews/harness/harness-core/43081#-NMhwylN0V2tHYsPx2ya:-NMhwylN0V2tHYsPx2yb:b-n4iyc7) ([raw file](https://github.com/harness/harness-core/blob/03d1502fb8ee873827fb263ca909a11e39bccd6a/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmSession.java#L241)):*
> ```Java
>         return executeCommandWithKerberos(scriptExecCommand, output, false);
>       } else {
>         WinRmToolResponse winRmToolResponse = winRmTool.executeCommand(scriptExecCommand);
> ```

Sinse we are not using winRmTool.executeCommand() method any more, can it be removed as well. Additionally, can we check if whole winRmTool class be removed if all methods from it are not used any more?

**Comment by vladimir-peric** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmSession.java` line 205 at r1](https://reviewable.io/reviews/harness/harness-core/43081#-NMi4BOe8KOAW0XWmwIu:-NMi4BOg5B-QWk2voDhb:b666lqu) ([raw file](https://github.com/harness/harness-core/blob/05afa9cf8333ba8b379b653da48c872e305f5577/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmSession.java#L205)):*
> ```Java
>     } else {
>       for (List<String> list : commandList) {
>         winRmToolResponse = winRmTool.executeCommand(list);
> ```

We have the old approach left here, are we fine with that?

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmSession.java` line 205 at r1](https://reviewable.io/reviews/harness/harness-core/43081#-NMi4BOe8KOAW0XWmwIu:-NMi7PQ-6xizCGnj5_zc:b-xn9d9d) ([raw file](https://github.com/harness/harness-core/blob/05afa9cf8333ba8b379b653da48c872e305f5577/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmSession.java#L205)):*
<details><summary><i>Previously, vladimir-peric (Vladimir Peric) wrote…</i></summary><blockquote>

We have the old approach left here, are we fine with that?
</blockquote></details>

This is fine, since shell.execute() doesn't have list as an argument

**Review by vladimir-peric — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43081)* status: :shipit: complete! ✓

**Comment by bojanmicovic** [comment]
trigger publish-delegate

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43081#-:-NN0mcUW-BFYqVh5X1CK:bnfp4nl)* status: Some of the checks are too old.

**Review by vladimir-peric — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43081)* status: 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43081#-:-NN0voCi3eV030FzkwbS:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
