### PR TITLE
fix: [CDS-34529]: Capturing warnings in errorStream.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31933)

### CODE REVIEW

**Comment by GoelPratyush99** [comment]
I haven't redirected errorStream for 

- repoUpdate
- getHelmRepoList
- templateForK8sV2

Do let we know if we want to redirect errorStream for them as well.

**Comment by GoelPratyush99** [comment]
Checkstyle: trigger checkstyle

**Review by namantalaycha10 — APPROVED** [review]

**Review by namantalaycha10 — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31933)* status: :shipit: complete! ✓

**Review by achyuth-harness — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31933)* status: :shipit: complete! ✓

**Comment by abhinavsingh1196** [comment]
*[960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java, line 101 at r2](https://reviewable.io/reviews/harness/harness-core/31933#-MzYhncA504e3l43-1hn:-MzYhncA504e3l43-1ho:b-yih8mk) ([raw file](https://github.com/harness/harness-core/blob/da5e35eeb317583595f531b00237fadf860a075c/960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java#L101)):*
> ```Java
>     String errorMessagePrefix = "Failed to install helm chart. Executed command: ";
> 
>     try (LogOutputStream errorStream = helmCommandData.getLogCallback() != null
> ```

I see this snippet repeated multiple times. Should we extract a method out of this?

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31933)* status: :shipit: complete! ✓

___
*[960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java, line 577 at r2](https://reviewable.io/reviews/harness/harness-core/31933#-MzYjl7s5Kp2ECZIgx8n:-MzYjl7s5Kp2ECZIgx8o:bru0zl6) ([raw file](https://github.com/harness/harness-core/blob/da5e35eeb317583595f531b00237fadf860a075c/960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java#L577)):*
> ```Java
>         // if helm hist fails due to 'release not found' -- then we don't fail/ throw exception
>         // (because for first time deployment, release history cmd fails with release not found)
>         String outputMessage = helmCliResponse.getOutputWithErrorStream();
> ```

What about other places where or we're using in the similar way or we do log/use in exception? Shouldn't we change this everywhere?

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31933)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java, line 101 at r2](https://reviewable.io/reviews/harness/harness-core/31933#-MzYhncA504e3l43-1hn:-MzZti5wCEpxaFoiKLqA:busaxrw) ([raw file](https://github.com/harness/harness-core/blob/da5e35eeb317583595f531b00237fadf860a075c/960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java#L101)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

I see this snippet repeated multiple times. Should we extract a method out of this?
</blockquote></details>

Fixed it
___
*[960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java, line 577 at r2](https://reviewable.io/reviews/harness/harness-core/31933#-MzYjl7s5Kp2ECZIgx8n:-MzZtktsD6bYcXCWTFUv:busaxrw) ([raw file](https://github.com/harness/harness-core/blob/da5e35eeb317583595f531b00237fadf860a075c/960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java#L577)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What about other places where or we're using in the similar way or we do log/use in exception? Shouldn't we change this everywhere?
</blockquote></details>

Fixed it

**Review by abosii-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31933)* status: 1. unresolved discussions.

**Review by namantalaycha10 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31933)* status: 1. unresolved discussions.

**Review by namantalaycha10 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31933)* status: 1. unresolved discussions.

**Review by abhinavsingh1196 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31933)* status: :shipit: complete! ✓

**Pull request merged**
