### PR TITLE
feat: [CDS-34607]: pipeline deployable per env

### PR DESCRIPTION
**Pull request by abhinav-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31564)

### CODE REVIEW

**Review by hingerabhinav — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31564)* status: Some of the checks are too old. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/security/auth/AuthHandler.java, line 774 at r1](https://reviewable.io/reviews/harness/harness-core/31564#-Mymwbg57-88e9P9a68W:-Mymwbg57-88e9P9a68X:b-g75p49) ([raw file](https://github.com/harness/harness-core/blob/ca0470050d383cd74b7b273acab8adde068eb4c2/400-rest/src/main/java/software/wings/service/impl/security/auth/AuthHandler.java#L774)):*
> ```Java
>     final String executableElementFilterType = executableElementsFilter.getExecutableElementFilterType();
>     final GenericEntityFilter executableElementFilter = executableElementsFilter.getFilter();
>     final Set<String> pipelineIdsByEntityFilter = getPipelineIdsByEntityFilter(pipelines, executableElementFilter);
> ```

Just confirming,Is this where ALL pipeline cases and null case for old permissions are handled?

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31564)* status: Some of the checks are too old. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/security/auth/AuthHandler.java, line 774 at r1](https://reviewable.io/reviews/harness/harness-core/31564#-Mymwbg57-88e9P9a68W:-MymxQqeA16SbXuXZOXp:brwikij) ([raw file](https://github.com/harness/harness-core/blob/ca0470050d383cd74b7b273acab8adde068eb4c2/400-rest/src/main/java/software/wings/service/impl/security/auth/AuthHandler.java#L774)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

Just confirming,Is this where ALL pipeline cases and null case for old permissions are handled?
</blockquote></details>

yes, its pre-existing code - in crud we have to add a null check that we don’t allow null when we have pipeline “selected”

**Review by hingerabhinav — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31564)* status: Some of the checks are too old. 

___
*[400-rest/src/main/java/software/wings/service/impl/security/auth/AuthHandler.java, line 774 at r1](https://reviewable.io/reviews/harness/harness-core/31564#-Mymwbg57-88e9P9a68W:-Mymyv1G9meRFs2bK6Y3:b-3ydmju) ([raw file](https://github.com/harness/harness-core/blob/ca0470050d383cd74b7b273acab8adde068eb4c2/400-rest/src/main/java/software/wings/service/impl/security/auth/AuthHandler.java#L774)):*
>  that we don’t allow null when we have pipeline “selected”
yes, got it

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 5 of 12 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31564)* status: :shipit: complete! ✓

**Pull request merged**
