### PR TITLE
fix: [DEL-4950]: New PT State to track Non_Assignable Delegates

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
Add new state call TASK_NON_ASSIGNABLE to track non eligible and unexpected exception delegates.
 
## Checklist
- [x ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37947)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37947)

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/ccm/health/HealthStatusServiceImpl.java` line 305 at r4](https://reviewable.io/reviews/harness/harness-core/37947#-ND4UKHL-gtjy38kAa1d:-ND4UKHM4fVKDV4k_6Zv:b31uyui) ([raw file](https://github.com/harness/harness-core/blob/523130e901a86c1c70860cc48ad75e2c0163d53a/400-rest/src/main/java/io/harness/ccm/health/HealthStatusServiceImpl.java#L305)):*
> ```Java
>               errors.add(DELEGATE_NOT_INSTALLED);
>               break;
>             case PT_TASK_FAILED:
> ```

don't rename, create a new one

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java` line 191 at r4](https://reviewable.io/reviews/harness/harness-core/37947#-ND4VGtm-iQoHa-0vNjP:-ND4VGtm-iQoHa-0vNjQ:bv38w8d) ([raw file](https://github.com/harness/harness-core/blob/523130e901a86c1c70860cc48ad75e2c0163d53a/400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java#L191)):*
> ```Java
>             PerpetualTaskState.TASK_NON_ASSIGNABLE);
>       } catch (DelegateTaskExpiredException exception) {
>         ignoredOnPurpose(exception);
> ```

expired should not cause unassignable

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java` line 201 at r4](https://reviewable.io/reviews/harness/harness-core/37947#-ND4Vqbv7i6Ny5_vjnLS:-ND4Vqbv7i6Ny5_vjnLT:b-1iezad) ([raw file](https://github.com/harness/harness-core/blob/523130e901a86c1c70860cc48ad75e2c0163d53a/400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java#L201)):*
> ```Java
>       } catch (Exception e) {
>         log.error("Failed to assign any Delegate to perpetual task {} ", taskId, e);
>         perpetualTaskService.updateStateAndTaskUnassignedReason(taskId, PerpetualTaskUnassignedReason.PT_TASK_FAILED,
> ```

1. analyze how many times you are seeing this 
2. we should put the right reasons for here to for people to know why was it marked un assignable 



_Code quote:_
```Java
        log.error("Failed to assign any Delegate to perpetual task {} ", taskId, e);

        perpetualTaskService.updateStateAndTaskUnassignedReason(taskId, PerpetualTaskUnassignedReason.PT_TASK_FAILED,
            taskRecord.getAssignTryCount(), PerpetualTaskState.TASK_NON_ASSIGNABLE);
```

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java` line 196 at r4](https://reviewable.io/reviews/harness/harness-core/37947#-ND4WYR6CmtuJPc_Vt5u:-ND4WYR6CmtuJPc_Vt5v:b8cf6kf) ([raw file](https://github.com/harness/harness-core/blob/523130e901a86c1c70860cc48ad75e2c0163d53a/400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java#L196)):*
> ```Java
>       } catch (DelegateTaskValidationFailedException exception) {
>         ignoredOnPurpose(exception);
>         perpetualTaskService.updateStateAndTaskUnassignedReason(taskId,
> ```

if a customer fixes the reachability, we will still not pick up the task for assignment. 



_Code quote:_
```Java
DelegateTaskValidationFailedException
```

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java` line 227 at r4](https://reviewable.io/reviews/harness/harness-core/37947#-ND4Wzdr487rxXxOt2HL:-ND4Wzdr487rxXxOt2HM:b-z4s0kk) ([raw file](https://github.com/harness/harness-core/blob/523130e901a86c1c70860cc48ad75e2c0163d53a/400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java#L227)):*
> ```Java
>   protected DelegateTask getValidationTask(PerpetualTaskRecord taskRecord) {
>     if (isNotEmpty(taskRecord.getClientContext().getClientParams())) {
>       PerpetualTaskServiceClient client = clientRegistry.getClient(taskRecord.getPerpetualTaskType());
> ```

ensure that all logs are under logging context

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2724 at r4](https://reviewable.io/reviews/harness/harness-core/37947#-ND4XCo-EWWlacHJKlgA:-ND4XCo-EWWlacHJKlgB:b-jacy32) ([raw file](https://github.com/harness/harness-core/blob/523130e901a86c1c70860cc48ad75e2c0163d53a/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2724)):*
> ```Java
>     }
>     // if new delegates gets regsitered re trigger PT task in account to non assignable to assignable,
>     perpetualTaskService.updateTaskAssignable(delegateParams.getAccountId());
> ```

rename the method to may be markUnassignleTasksToUnassigned

**Comment by raghuAtWings** [comment]
*[`430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/CVNGPerpetualTaskState.java` line 14 at r4](https://reviewable.io/reviews/harness/harness-core/37947#-ND4Y_Op2gzEdr4ycPZs:-ND4Y_Oq6xhgHdqf0dd8:bdgjmtg) ([raw file](https://github.com/harness/harness-core/blob/523130e901a86c1c70860cc48ad75e2c0163d53a/430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/CVNGPerpetualTaskState.java#L14)):*
> ```Java
>   TASK_TO_REBALANCE,
>   TASK_PAUSED,
>   TASK_NON_ASSIGNABLE,
> ```

add new state in the end

**Comment by raghuAtWings** [comment]
*[`430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/CVNGPerpetualTaskUnassignedReason.java` line 15 at r4](https://reviewable.io/reviews/harness/harness-core/37947#-ND4Yeq-4SD2EsLGLgoh:-ND4Yeq-4SD2EsLGLgoi:b-eilcd9) ([raw file](https://github.com/harness/harness-core/blob/523130e901a86c1c70860cc48ad75e2c0163d53a/430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/CVNGPerpetualTaskUnassignedReason.java#L15)):*
> ```Java
>   NO_ELIGIBLE_DELEGATES,
>   TASK_EXPIRED, // sync task expired
>   TASK_VALIDATION_FAILED, // sync task validation failed
> ```

add enums in the end

**Review by raghuAtWings — COMMENTED** [review]
tests that need to be done

1. a task which is not assignable should become assignable for following
    a. new delegate comes up
    b. an existing delegate came online
    c. periodic checking of tasks which were not assignable because of validation
    d. anything else?

2. task should become unassignble and not come in the query for 
    a. if there are no delegates which can do the task
    b. if the task keeps failing for a long time we should mark it unassignable and do a periodic check
    c. anything else?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37947#-:-ND4YqzYB2Y1Me7bCbh5:b-2l5bcj)* status: 18 file(s) to review. 0 of 1 approvals obtained.

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 8 of 11 files at r2, 7 of 8 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37947)* status: 0 of 1 approvals obtained.

**Review by xingchi-jin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37947)* status: Some of the checks are too old. 25 file(s) to review. 0 of 1 approvals obtained. 

___
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1284 at r5](https://reviewable.io/reviews/harness/harness-core/37947#-NEbkwInBd3YYyTtN4bc:-NEbkwInBd3YYyTtN4bd:b-kc1upr) ([raw file](https://github.com/harness/harness-core/blob/d408f5f87a19312b120d6276975478dc20aa2b00/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1284)):*
> ```Java
> 
>     delegateExecutor.scheduleWithFixedDelay(new Schedulable("Failed while detecting disconnected delegates",
>                                                 injector.getInstance(DelegateDisconnectedDetector.class)),
> ```

we can remove this class DelegateDisconnectedDetector.java 
___
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 78 at r5](https://reviewable.io/reviews/harness/harness-core/37947#-NEbyTKb8g0XU7sRvZa_:-NEbyTKb8g0XU7sRvZaa:b-1z9fly) ([raw file](https://github.com/harness/harness-core/blob/1db104092728d92bd0fa6d9ddf5aa83d96ebca82/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L78)):*
> ```Java
>   @Override
>   public void handle(Delegate delegate) {
>     if (isDelegateExpiryCheckDoneAlready(delegate)) {
> ```

why this check is needed for connection ? 
___
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 95 at r5](https://reviewable.io/reviews/harness/harness-core/37947#-NEby2GT9iCIDSD17GmI:-NEby2GT9iCIDSD17GmJ:bcg5t6e) ([raw file](https://github.com/harness/harness-core/blob/1db104092728d92bd0fa6d9ddf5aa83d96ebca82/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L95)):*
> ```Java
>   }
> 
>   private boolean isDelegateExpiryCheckDoneAlready(Delegate delegate) {
> ```

This is dup code from DelegateTaskExpiryCheckIterator::isDelegateExpiryCheckDoneAlready , can we move it to some where common ? 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 3118 at r5](https://reviewable.io/reviews/harness/harness-core/37947#-NEbjD-k8rho4E5LyFDh:-NEbjD-k8rho4E5LyFDi:b-7p1m5u) ([raw file](https://github.com/harness/harness-core/blob/1db104092728d92bd0fa6d9ddf5aa83d96ebca82/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3118)):*
> ```Java
>   @Override
>   public void onDelegateDisconnected(String accountId, String delegateId) {
>     subject.fireInform(DelegateObserver::onDisconnected, accountId, delegateId);
> ```

i cannot find where the observers are registered for this private member subject. If none registered, this call does nothing. I am not sure, want to check if you knows

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 78 at r5](https://reviewable.io/reviews/harness/harness-core/37947#-NEbyTKb8g0XU7sRvZa_:-NEc2XNt31Sx2ENIyXnx:b1xmha3) ([raw file](https://github.com/harness/harness-core/blob/1db104092728d92bd0fa6d9ddf5aa83d96ebca82/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L78)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

why this check is needed for connection ? 
</blockquote></details>

The delegate can be in a disconnected state for a long, we only need to execute these checks once(marking task, marking delegate disconnection one time).  
For that purpose delegate already has a field call lastExpiredEventHeartbeatTime to track the last expired timestamp

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 95 at r5](https://reviewable.io/reviews/harness/harness-core/37947#-NEby2GT9iCIDSD17GmI:-NEc3e7z5RquvoXYpUxt:ba9y3oz) ([raw file](https://github.com/harness/harness-core/blob/1db104092728d92bd0fa6d9ddf5aa83d96ebca82/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L95)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

This is dup code from DelegateTaskExpiryCheckIterator::isDelegateExpiryCheckDoneAlready , can we move it to some where common ? 
</blockquote></details>


we are removing DelegateTaskExpiryCheckIterator

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java` line 227 at r4](https://reviewable.io/reviews/harness/harness-core/37947#-ND4Wzdr487rxXxOt2HL:-NEc3rr9DV8sdi5wX6mA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/523130e901a86c1c70860cc48ad75e2c0163d53a/400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java#L227)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

ensure that all logs are under logging context 
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java` line 201 at r4](https://reviewable.io/reviews/harness/harness-core/37947#-ND4Vqbv7i6Ny5_vjnLS:-NEc3qpb0E5yDINQamW0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/523130e901a86c1c70860cc48ad75e2c0163d53a/400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java#L201)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

1. analyze how many times you are seeing this 
2. we should put the right reasons for here to for people to know why was it marked un assignable 
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java` line 191 at r4](https://reviewable.io/reviews/harness/harness-core/37947#-ND4VGtm-iQoHa-0vNjP:-NEc40eW8_CaX2UxeyCZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/523130e901a86c1c70860cc48ad75e2c0163d53a/400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java#L191)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

expired should not cause unassignable 
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2724 at r4](https://reviewable.io/reviews/harness/harness-core/37947#-ND4XCo-EWWlacHJKlgA:-NEc42E06ZgfmoUZuUMG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/523130e901a86c1c70860cc48ad75e2c0163d53a/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2724)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

rename the method to may be markUnassignleTasksToUnassigned
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 3118 at r5](https://reviewable.io/reviews/harness/harness-core/37947#-NEbjD-k8rho4E5LyFDh:-NEc47HB9g-B_9a9nv7Z:buh1a7y) ([raw file](https://github.com/harness/harness-core/blob/1db104092728d92bd0fa6d9ddf5aa83d96ebca82/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3118)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

i cannot find where the observers are registered for this private member subject. If none registered, this call does nothing. I am not sure, want to check if you knows 
</blockquote></details>

class implements DelegateObserver

**Comment by jennyjames21** [comment]
*[`430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/CVNGPerpetualTaskState.java` line 14 at r4](https://reviewable.io/reviews/harness/harness-core/37947#-ND4Y_Op2gzEdr4ycPZs:-NEc4DkmElEbxFFU9kR3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/523130e901a86c1c70860cc48ad75e2c0163d53a/430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/CVNGPerpetualTaskState.java#L14)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

add new state in the end
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/CVNGPerpetualTaskUnassignedReason.java` line 15 at r4](https://reviewable.io/reviews/harness/harness-core/37947#-ND4Yeq-4SD2EsLGLgoh:-NEc4F-T9IKOufN6CHlI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/523130e901a86c1c70860cc48ad75e2c0163d53a/430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/CVNGPerpetualTaskUnassignedReason.java#L15)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

add enums in the end
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/ccm/health/HealthStatusServiceImpl.java` line 305 at r4](https://reviewable.io/reviews/harness/harness-core/37947#-ND4UKHL-gtjy38kAa1d:-NEc4G7bE1sumWA9k3GU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/523130e901a86c1c70860cc48ad75e2c0163d53a/400-rest/src/main/java/io/harness/ccm/health/HealthStatusServiceImpl.java#L305)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

don't rename, create a new one
</blockquote></details>

Done.

**Pull request closed without merging**
