### PR TITLE
fix: [CDS-80491]: Split the getAndValidate function in getPipeline API

### PR DESCRIPTION
**Pull request by sarthakkasat**
## Describe your changes
Currently in the get pipeline call throws exception, fields like orgID, projectID... are not set in responseBody. With this change we are splitting the get and validate pipeline method to set these fields in all cases. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54093)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54093)* status: 4 file(s) to review. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 169 at r2](https://reviewable.io/reviews/harness/harness-core/54093#-Ngw2YSC6S9v7lMNDyNy:-Ngw2YSC6S9v7lMNDyNz:bosts1f) ([raw file](https://github.com/harness/harness-core/blob/0cb8d9f2ca9795ae801f2dd8fd8f58bdd2967b05/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L169)):*
> ```Java
>       PipelineEntity pipelineEntity = optionalPipelineEntity.get();
>       pipelineGetResponseBody = PipelinesApiUtils.getGetResponseBody(pipelineEntity);
>       validationUUID = pmsPipelineService.validatePipelineAndGetValidationId(account, org, project, pipeline,
> ```

can we rename this to validatePipeline only?



_Code quote:_
```Java
validatePipelineAndGetValidationId
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 378 at r2](https://reviewable.io/reviews/harness/harness-core/54093#-Ngw2eZcAtys5UiKdRV9:-Ngw2eZcAtys5UiKdRVA:bn9wrmd) ([raw file](https://github.com/harness/harness-core/blob/0cb8d9f2ca9795ae801f2dd8fd8f58bdd2967b05/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L378)):*
> ```Java
>           accountId, orgIdentifier, projectIdentifier, loadFromCache, pipelineEntity);
>     } else {
>       validatePipeline(orgIdentifier, projectIdentifier, pipelineId, loadFromCache, pipelineEntity);
> ```

lets rename this to validatePipelineSync
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 417 at r2](https://reviewable.io/reviews/harness/harness-core/54093#-Ngw2u1136wUjViUV__r:-Ngw2u1136wUjViUV__s:b-pukbrc) ([raw file](https://github.com/harness/harness-core/blob/0cb8d9f2ca9795ae801f2dd8fd8f58bdd2967b05/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L417)):*
> ```Java
>   }
> 
>   void validatePipeline(String orgIdentifier, String projectIdentifier, String identifier, boolean loadFromCache,
> ```

we should call this method in getAndValidatePipeline as well, to remove duplicated code
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 530 at r2](https://reviewable.io/reviews/harness/harness-core/54093#-Ngw30p0650SiXz1IWzz:-Ngw30p0650SiXz1IX--:bz753lj) ([raw file](https://github.com/harness/harness-core/blob/0cb8d9f2ca9795ae801f2dd8fd8f58bdd2967b05/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L530)):*
> ```Java
>         .build();
>   }
>   String getAsyncValidationIdAndValidatePipeline(String accountId, String orgIdentifier, String projectIdentifier,
> ```

same this method should be used in getPipelineAndAsyncValidationId

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54093)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 169 at r2](https://reviewable.io/reviews/harness/harness-core/54093#-Ngw2YSC6S9v7lMNDyNy:-NgwH8p51CJIysaKuma0:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/0cb8d9f2ca9795ae801f2dd8fd8f58bdd2967b05/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L169)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we rename this to validatePipeline only?
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 378 at r2](https://reviewable.io/reviews/harness/harness-core/54093#-Ngw2eZcAtys5UiKdRV9:-NgwHCjE62B-Gj-nmUVh:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/0cb8d9f2ca9795ae801f2dd8fd8f58bdd2967b05/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L378)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

lets rename this to validatePipelineSync
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 417 at r2](https://reviewable.io/reviews/harness/harness-core/54093#-Ngw2u1136wUjViUV__r:-NgwHHBCAwflqGGujaOD:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/0cb8d9f2ca9795ae801f2dd8fd8f58bdd2967b05/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L417)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should call this method in getAndValidatePipeline as well, to remove duplicated code
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 530 at r2](https://reviewable.io/reviews/harness/harness-core/54093#-Ngw30p0650SiXz1IWzz:-NgwHSwl3ijrdPtVjDqZ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/0cb8d9f2ca9795ae801f2dd8fd8f58bdd2967b05/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L530)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same this method should be used in getPipelineAndAsyncValidationId
</blockquote></details>

done

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54093)* status: :shipit: complete! ✓

**Comment by sarthakkasat** [comment]
trigger uts, trigger review

**Comment by sarthakkasat** [comment]
trigger uts

**Comment by sarthakkasat** [comment]
trigger uts

**Comment by sarthakkasat** [comment]
trigger messagecheck

**Comment by sarthakkasat** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54093)* status: 2 file(s) to review.

**Comment by sarthakkasat** [comment]
trigger review

**Pull request merged**
