### PR TITLE
[fix]: [CDS-35447]: selectively add harness track labels in pod template for…

### PR DESCRIPTION
**Pull request by tchaurasiya**
… non canary succeding rolling

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33182)

### CODE REVIEW

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33182)* status: 4 file(s) to review. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java` line 419 at r2](https://reviewable.io/reviews/harness/harness-core/33182#-N2Bh2llBq6MnChkHfsF:-N2Bh2lm6wSfG0tuE-l_:b6k7byo) ([raw file](https://github.com/harness/harness-core/blob/5bbf43fc12c1de0cb4fa873b966732f481410e10/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java#L419)):*
> ```Java
>         }
> 
>         List<KubernetesResource> deploymentContainingTrackStableSelector =
> ```

nit: this can be final so that it is not modified by the below methods

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33182)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java` line 126 at r2](https://reviewable.io/reviews/harness/harness-core/33182#-N2BotCv1brriK9jSjY4:-N2BotCv1brriK9jSjY5:b-l5pjx0) ([raw file](https://github.com/harness/harness-core/blob/5bbf43fc12c1de0cb4fa873b966732f481410e10/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java#L126)):*
> ```Java
>         kubernetesResource.addLabelsInPodSpec(releaseNamePodLabels);
>       }
>       if (skipAddingTrackSelectorToDeployment) {
> ```

this is a bit confusing. The condition is based on the variable `skipAddingTrackSelectorToDeployment`, yet if this resolves true, we are adding the `HarnessLabels.track` label.



_Code quote:_
```Java
if (skipAddingTrackSelectorToDeployment) {
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java` line 128 at r2](https://reviewable.io/reviews/harness/harness-core/33182#-N2BpAd80jvDhUeCLKw-:-N2BpAd80jvDhUeCLKw0:b-72a77a) ([raw file](https://github.com/harness/harness-core/blob/5bbf43fc12c1de0cb4fa873b966732f481410e10/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java#L128)):*
> ```Java
>       if (skipAddingTrackSelectorToDeployment) {
>         Map<String, String> releaseNameAndTrackPodLabels = ImmutableMap.of(
>             HarnessLabels.releaseName, releaseName, HarnessLabels.track, HarnessLabelValues.trackStable);
> ```

The labels `HarnessLabels.releaseName, releaseName` is added regardless of what different flag values is passed to this function.
Please  simplify this method accordingly.

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33182)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java` line 128 at r2](https://reviewable.io/reviews/harness/harness-core/33182#-N2C5Vuu2xsjDqdUVNao:-N2C5Vuu2xsjDqdUVNap:b-mrlay3) ([raw file](https://github.com/harness/harness-core/blob/5bbf43fc12c1de0cb4fa873b966732f481410e10/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java#L128)):*
> ```Java
>       if (skipAddingTrackSelectorToDeployment) {
>         Map<String, String> releaseNameAndTrackPodLabels = ImmutableMap.of(
>             HarnessLabels.releaseName, releaseName, HarnessLabels.track, HarnessLabelValues.trackStable);
> ```

remove release name label from here
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java` line 210 at r2](https://reviewable.io/reviews/harness/harness-core/33182#-N2C6UUX32W9pRLnm7Oc:-N2C6UUX32W9pRLnm7Od:bi6rj6q) ([raw file](https://github.com/harness/harness-core/blob/5bbf43fc12c1de0cb4fa873b966732f481410e10/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java#L210)):*
> ```Java
>       KubernetesConfig kubernetesConfig) {
>     if (!skipAddingTrackSelectorToDeployment) {
>       return null;
> ```

return empty

**Comment by tchaurasiya** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java` line 126 at r2](https://reviewable.io/reviews/harness/harness-core/33182#-N2BotCv1brriK9jSjY4:-N2COuVY2VlbK0itTns0:b37p62d) ([raw file](https://github.com/harness/harness-core/blob/5bbf43fc12c1de0cb4fa873b966732f481410e10/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java#L126)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

this is a bit confusing. The condition is based on the variable `skipAddingTrackSelectorToDeployment`, yet if this resolves true, we are adding the `HarnessLabels.track` label.
</blockquote></details>

Refactored. we are adding release name to all managed workload.

**Comment by tchaurasiya** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java` line 128 at r2](https://reviewable.io/reviews/harness/harness-core/33182#-N2BpAd80jvDhUeCLKw-:-N2CP47nCTYbzIVz3ot-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5bbf43fc12c1de0cb4fa873b966732f481410e10/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java#L128)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

The labels `HarnessLabels.releaseName, releaseName` is added regardless of what different flag values is passed to this function.
Please  simplify this method accordingly.
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java` line 128 at r2](https://reviewable.io/reviews/harness/harness-core/33182#-N2C5Vuu2xsjDqdUVNao:-N2CP5lv0EWONnWkMxRZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5bbf43fc12c1de0cb4fa873b966732f481410e10/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java#L128)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

remove release name label from here
</blockquote></details>

Done.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33182)* status: 1 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java` line 123 at r3](https://reviewable.io/reviews/harness/harness-core/33182#-N2CL9ym0nRH-ab6APR4:-N2CL9ym0nRH-ab6APR5:b-7mtgbo) ([raw file](https://github.com/harness/harness-core/blob/8ea5cd1124fff10e8e76b70c4309cc05d770b401/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java#L123)):*
> ```Java
>   }
> 
>   private void addTrackLabelInPodSpec(List<KubernetesResource> deploymentContainingTrackStableSelector) {
> ```

the name of this can just be "workloads" now, right ?

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33182)* status: 1 change requests. 2. unresolved discussions.

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33182)* status: :shipit: complete! ✓

**Comment by tchaurasiya** [comment]
trigger ti0

**Review by mdmilic — APPROVED** [review]
Approving delegate related changes

> Reviewed 3 of 6 files at r1, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33182#-:-N2GQwof18rzrIl_gNy1:bz0q1f2)* status: :shipit: complete! ✓

**Pull request merged**
