### PR TITLE
[fix]: [PL-28428]: restrict deletion of LDAP/SAML settings from CG, when groups are linked in NG

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
Currently, we restrict deleting LDAP/SAML settings from NG if any user group is linked in NG with the SSO setting. But the settings can be deleted from CG, as linked user group to SSO on NG check is not accounted in CG. Adding functionality to restrict the deletion from CG in additional case where NG UserGroup are linked to SSO setting.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38215)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38215)

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38215)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 360 at r1](https://reviewable.io/reviews/harness/harness-core/38215#-NDE12kv70WyHcvpneZh:-NDE12kv70WyHcvpneZi:b-7dulai) ([raw file](https://github.com/harness/harness-core/blob/1d240a1b020e82d8d1d5ec22181570e1de6cba23/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L360)):*
> ```Java
>   public boolean deleteSamlSettings(SamlSettings samlSettings) {
>     List<UserGroupDTO> userGroupDTOS = NGRestUtils.getResponse(
>         userGroupClient.getSsoLinkedUserGroups(samlSettings.getUuid(), samlSettings.getAccountId()));
> ```

what if this client call throws an exception? when ng-manager is down. Can we add a try catch.

code quote:
userGroupClient.getSsoLinkedUserGroups()
___
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 466 at r1](https://reviewable.io/reviews/harness/harness-core/38215#-NDE1UR35fnpj9oMT4qg:-NDE1UR35fnpj9oMT4qh:b3gw4rt) ([raw file](https://github.com/harness/harness-core/blob/1d240a1b020e82d8d1d5ec22181570e1de6cba23/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L466)):*
> ```Java
>   public LdapSettings deleteLdapSettings(@NotNull LdapSettings settings) {
>     List<UserGroupDTO> userGroupDTOS =
>         NGRestUtils.getResponse(userGroupClient.getSsoLinkedUserGroups(settings.getUuid(), settings.getAccountId()));
> ```

same here as above comment

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 361 at r1](https://reviewable.io/reviews/harness/harness-core/38215#-NDJhDsT3-FBbFy6GCOI:-NDJhDsT3-FBbFy6GCOJ:b-nfnp8w) ([raw file](https://github.com/harness/harness-core/blob/1d240a1b020e82d8d1d5ec22181570e1de6cba23/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L361)):*
> ```Java
>     List<UserGroupDTO> userGroupDTOS = NGRestUtils.getResponse(
>         userGroupClient.getSsoLinkedUserGroups(samlSettings.getUuid(), samlSettings.getAccountId()));
>     if (userGroupService.existsLinkedUserGroup(samlSettings.getUuid()) || isNotEmpty(userGroupDTOS)) {
> ```

We should separate these conditions out. We can do the check on samlSettings before our call to fetch userGroupDTOs. If it passes, we can directly throw the exception and there's no need to fetch the userGroupDTOs

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 467 at r1](https://reviewable.io/reviews/harness/harness-core/38215#-NDJhQOr3cZoD1OgUkLp:-NDJhQOr3cZoD1OgUkLq:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/1d240a1b020e82d8d1d5ec22181570e1de6cba23/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L467)):*
> ```Java
>     List<UserGroupDTO> userGroupDTOS =
>         NGRestUtils.getResponse(userGroupClient.getSsoLinkedUserGroups(settings.getUuid(), settings.getAccountId()));
>     if (userGroupService.existsLinkedUserGroup(settings.getUuid()) || isNotEmpty(userGroupDTOS)) {
> ```

same here

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 361 at r1](https://reviewable.io/reviews/harness/harness-core/38215#-NDJhDsT3-FBbFy6GCOI:-NDRHDDzCuB10e99FZOJ:blw47vu) ([raw file](https://github.com/harness/harness-core/blob/1d240a1b020e82d8d1d5ec22181570e1de6cba23/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L361)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should separate these conditions out. We can do the check on samlSettings before our call to fetch userGroupDTOs. If it passes, we can directly throw the exception and there's no need to fetch the userGroupDTOs
</blockquote></details>

Done @mohitg0795 , thanks.
However with the `||` condition, if the first argument would have evaluated to `true`, we wouldn't have called the fetch to NG userGroupDTOs. But I've separated this out to check for other condition as well, thanks

**Review by pbarapatre10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38215)* status: 7 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 360 at r1](https://reviewable.io/reviews/harness/harness-core/38215#-NDE12kv70WyHcvpneZh:-NDRHaQkCJ7-jGJDSiOp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1d240a1b020e82d8d1d5ec22181570e1de6cba23/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L360)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

what if this client call throws an exception? when ng-manager is down. Can we add a try catch.

code quote:
userGroupClient.getSsoLinkedUserGroups()
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 466 at r1](https://reviewable.io/reviews/harness/harness-core/38215#-NDE1UR35fnpj9oMT4qg:-NDRHZW53QgYcejlZq6F:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1d240a1b020e82d8d1d5ec22181570e1de6cba23/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L466)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

same here as above comment
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 467 at r1](https://reviewable.io/reviews/harness/harness-core/38215#-NDJhQOr3cZoD1OgUkLp:-NDRH_Pt2N-beF2WR0pr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1d240a1b020e82d8d1d5ec22181570e1de6cba23/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L467)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`230-model-test/src/main/java/io/harness/testframework/restutils/SSORestUtils.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/38215#-NDXTEb9-roQQDG-AdHF:-NDXTEb9-roQQDG-AdHG:b-gflwk4) ([raw file](https://github.com/harness/harness-core/blob/27f0cd0444a0d6c80391a00f932e99fff54a1fb9/230-model-test/src/main/java/io/harness/testframework/restutils/SSORestUtils.java#L91)):*
> ```Java
>                             .log()
>                             .all()
>                             .delete("/sso/delete-saml-idp-metadata");
> ```

this should be a constant with logical name

**Comment by mohitg0795** [comment]
*[`230-model-test/src/main/java/io/harness/testframework/restutils/SSORestUtils.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/38215#-NDXTH5O1QjrugtvgGTv:-NDXTH5O1QjrugtvgGTw:bgtupos) ([raw file](https://github.com/harness/harness-core/blob/27f0cd0444a0d6c80391a00f932e99fff54a1fb9/230-model-test/src/main/java/io/harness/testframework/restutils/SSORestUtils.java#L88)):*
> ```Java
>                             .auth()
>                             .oauth2(bearerToken)
>                             .queryParam("accountId", accountId)
> ```

same here, should be a constant

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 718 at r2](https://reviewable.io/reviews/harness/harness-core/38215#-NDXTzsI11S2Phskg8hb:-NDXTzsI11S2Phskg8hc:b-eauyi2) ([raw file](https://github.com/harness/harness-core/blob/27f0cd0444a0d6c80391a00f932e99fff54a1fb9/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L718)):*
> ```Java
>       }
>     }
>     if (isNotEmpty(userGroupDTOs)) {
> ```

do you want to log it as well?

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 718 at r2](https://reviewable.io/reviews/harness/harness-core/38215#-NDXTzsI11S2Phskg8hb:-NDXWdooDmu5arR1E-rE:b-timjvc) ([raw file](https://github.com/harness/harness-core/blob/27f0cd0444a0d6c80391a00f932e99fff54a1fb9/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L718)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

do you want to log it as well?
</blockquote></details>

Not really. In this case it will be propagated to the user, so directly users will get indication and Deletion of SSO settings is prevented, thanks

**Comment by pbarapatre10** [comment]
*[`230-model-test/src/main/java/io/harness/testframework/restutils/SSORestUtils.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/38215#-NDXTH5O1QjrugtvgGTv:-NDXWws-EjhDcr0w0t2Y:b-iyb9ki) ([raw file](https://github.com/harness/harness-core/blob/27f0cd0444a0d6c80391a00f932e99fff54a1fb9/230-model-test/src/main/java/io/harness/testframework/restutils/SSORestUtils.java#L88)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same here, should be a constant
</blockquote></details>

reverted changes back to original, as we added some logs for running tests which we don't need further. Thanks

**Comment by pbarapatre10** [comment]
*[`230-model-test/src/main/java/io/harness/testframework/restutils/SSORestUtils.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/38215#-NDXTEb9-roQQDG-AdHF:-NDXX9KO90_G6obR2dvp:bfqcn6i) ([raw file](https://github.com/harness/harness-core/blob/27f0cd0444a0d6c80391a00f932e99fff54a1fb9/230-model-test/src/main/java/io/harness/testframework/restutils/SSORestUtils.java#L91)):*
> reverted changes back to original, as we added some logs for running tests which we don't need further. Thanks

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38215)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by kapil-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 7 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38215#-:-NDaaPer4r8SjQGEqsmZ:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
