### PR TITLE
[feat]: [PL-28502]: restrict login audits to only 1 account which user logins into + improved audit logs

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
restrict login audits to only 1 account which user logins into

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38236)

### CODE REVIEW

**Review by pbarapatre10 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38236)* status: 1 file(s) to review. 0 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 392 at r1](https://reviewable.io/reviews/harness/harness-core/38236#-NDOqNlCAR9SbWorNYfh:-NDOqNlCAR9SbWorNYfi:baea8io) ([raw file](https://github.com/harness/harness-core/blob/515df373bbbb02c203cf87d811e5d528c8907226/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L392)):*
> ```Java
>       } else {
>         User loggedInUser = authService.generateBearerTokenForUser(user);
>         authService.auditLogin(Collections.singletonList(account.getUuid()), loggedInUser);
> ```

Nit ??? Should we change the CG side way of auditing? Hope it doesn't have other unnecessary impact, thanks



_Code quote:_
```Java
authService.auditLogin(Collections.singletonList(account.getUuid())
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/38236#-NDOnlkn8CIOllQNF1kO:-NDOnlkn8CIOllQNF1kP:bub5xek) ([raw file](https://github.com/harness/harness-core/blob/515df373bbbb02c203cf87d811e5d528c8907226/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L148)):*
> ```Java
>       Optional<Account> optionalAccount =
>           user.getAccounts().stream().filter(acct -> Objects.equals(defaultAccountId, acct.getUuid())).findFirst();
>       account = optionalAccount.orElseGet(() -> user.getAccounts().get(0));
> ```

Nit  ??? Could it happen that a user has empty`[]` accounts? 



_Code quote:_
```Java
account = optionalAccount.orElseGet(() -> user.getAccounts().get(0));
```

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38236)* status: 32 file(s) to review. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/38236#-NDOnlkn8CIOllQNF1kO:-NDdd1t2DoL0rqZg4wy5:b-gts8u1) ([raw file](https://github.com/harness/harness-core/blob/515df373bbbb02c203cf87d811e5d528c8907226/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L148)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Nit  ??? Could it happen that a user has empty`[]` accounts? 
</blockquote></details>

when a user is added it goes via user invite flow and the invite DTO has the accountId, so it is not possible that a user does not have an account.
___
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 392 at r1](https://reviewable.io/reviews/harness/harness-core/38236#-NDOqNlCAR9SbWorNYfh:-NDde5fCDOUsKbL6qHnW:b964dbx) ([raw file](https://github.com/harness/harness-core/blob/515df373bbbb02c203cf87d811e5d528c8907226/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L392)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Nit ??? Should we change the CG side way of auditing? Hope it doesn't have other unnecessary impact, thanks
</blockquote></details>

It should not have any impact as we are just restricting the accountId's to 1, which can be a true case if the user is only part of 1 account. But I will test this, currently facing some issue in getting login audits for CG.

**Pull request closed without merging**
