### PR TITLE
[fix]: [CDS-2170]: Bug where static var was introduced to store git template file path

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30989)

### CODE REVIEW

**Comment by arvind-choudhary-h** [comment]
trigger messagecheck

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30989)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30989)* status: :shipit: complete! ✓

**Comment by gitNavV** [comment]
@arvind-choudhary-h Hey, have you tested this on Local and/or PR Environment?

I asked you to review this change specifically (https://github.com/harness/harness-core/pull/30658#issuecomment-1041924350) 👇🏾
> @arvind-choudhary-h Could you please review this commit - [0c756fe](https://github.com/harness/harness-core/commit/0c756fef958bee8af237e055a33ca3e6578eb1dc)?
> 
> Needed to change this to preserve the path value after control gets shifted to Delegate and then back to Manager.

**Pull request merged**
