### PR TITLE
feat: [CDS-54488]: Register EnvironmentGroupExpandedHandler for NG Manager 

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
- Register Environment Group OPA Expansion Handler in NG Application
- Update tests with scoped environment group refs
- Add envGroupRef field in the final output json ( alongside identifier )
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47216)

### CODE REVIEW

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/EnvGroupExpandedValue.java` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/47216#-NUV48PB8d0WdHGD5Jnc:-NUV48PB8d0WdHGD5Jnd:bw8nhrj) ([raw file](https://github.com/harness/harness-core/blob/ab14475ff468fce7ca0e690db88e734d219267b4/125-cd-nextgen/src/main/java/io/harness/pms/governance/EnvGroupExpandedValue.java#L32)):*
> ```Java
>   private String name;
>   private String identifier;
>   private String envGroupRef;
> ```

Why do we need identifier and envGroupRef both?

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 2 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47216)* status: 10 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java` line 79 at r2](https://reviewable.io/reviews/harness/harness-core/47216#-NUV54L93PLznZBAzlVK:-NUV54L93PLznZBAzlVL:b-3ivwwa) ([raw file](https://github.com/harness/harness-core/blob/ab14475ff468fce7ca0e690db88e734d219267b4/125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java#L79)):*
> ```Java
>           .value(value)
>           .build();
>     } catch (Exception ex) {
> ```

lets also log this error.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/EnvGroupExpandedValue.java` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/47216#-NUV48PB8d0WdHGD5Jnc:-NUV64TG-2TemfJcdc3U:bw0ot6c) ([raw file](https://github.com/harness/harness-core/blob/ab14475ff468fce7ca0e690db88e734d219267b4/125-cd-nextgen/src/main/java/io/harness/pms/governance/EnvGroupExpandedValue.java#L32)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Why do we need identifier and envGroupRef both?
</blockquote></details>

Discused offline.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 5 of 10 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47216)* status: 10 file(s) to review. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47216)* status: 10 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java` line 79 at r2](https://reviewable.io/reviews/harness/harness-core/47216#-NUV54L93PLznZBAzlVK:-NUVun70Al_Bacgp8eK9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ab14475ff468fce7ca0e690db88e734d219267b4/125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java#L79)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

lets also log this error.
</blockquote></details>

Done.

**Comment by yogesh-chauhan** [comment]
trigger checkstylecodeformat

**Review by hingerabhinav — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47216)* status: 8 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/EnvironmentGroupExpandedHandler.java` line 120 at r3](https://reviewable.io/reviews/harness/harness-core/47216#-NUW-P7lCWGMeqT1COAM:-NUW-P7lCWGMeqT1COAN:b9qg6k2) ([raw file](https://github.com/harness/harness-core/blob/08f18c8d66042c7b9ac8760d6032a1d9670bed89/125-cd-nextgen/src/main/java/io/harness/pms/governance/EnvironmentGroupExpandedHandler.java#L120)):*
> ```Java
>       ExpansionRequestMetadata metadata, JsonNode fieldValue, String envGroupRef) {
>     final JsonNode environments = fieldValue.get(environmentGroupYamlKeys.environments);
>     if (environments == null || !environments.isArray()) {
> ```

What happens in deployToAll case?
Like below YAML 
```
environmentGroup:
            envGroupRef: stagingEnv1
            metadata:
              parallel: true
            deployToAll: true
            environments: <+input>
```

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47216)* status: 8 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/EnvironmentGroupExpandedHandler.java` line 120 at r3](https://reviewable.io/reviews/harness/harness-core/47216#-NUW-P7lCWGMeqT1COAM:-NUW46_H8BGLIX63tv4W:b-qjx4s1) ([raw file](https://github.com/harness/harness-core/blob/08f18c8d66042c7b9ac8760d6032a1d9670bed89/125-cd-nextgen/src/main/java/io/harness/pms/governance/EnvironmentGroupExpandedHandler.java#L120)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

What happens in deployToAll case?
Like below YAML 
```
environmentGroup:
            envGroupRef: stagingEnv1
            metadata:
              parallel: true
            deployToAll: true
            environments: <+input>
```
</blockquote></details>

Even with deploy to all, when pipeline executes, we send all the infrastructures through the UI, hence the yaml at the execution time will have the infrastructures

**Comment by yogesh-chauhan** [comment]
trigger utAll

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 5 of 10 files at r1, 1 of 3 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47216)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47216)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
trigger review

**Review by hingerabhinav — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47216#-:-NUXmJK11bc36pfSh6oh:bnfp4nl)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
trigger review

**Pull request merged**
