### PR TITLE
[feat]: [DEL-3092]: Implement perpetual task error handling

### PR DESCRIPTION
**Pull request by Xin-Harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30130)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java, line 64 at r2](https://reviewable.io/reviews/harness/harness-core/30130#-MtyidBvEQokLeZvtj-s:-MtyidBvEQokLeZvtj-t:bfud0rc) ([raw file](https://github.com/harness/harness-core/blob/0226606deb6d25e2a7038df2f4eb8ef45fea81ba/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L64)):*
> ```Java
>   private final BroadcasterFactory broadcasterFactory;
>   private final PerpetualTaskScheduleService perpetualTaskScheduleService;
>   private int TASK_FAILED_EXECUTION_LIMIT = 100;
> ```

this should be defined as constant and should not be 100, may be just 10

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java, line 294 at r2](https://reviewable.io/reviews/harness/harness-core/30130#-MtykCL71WMzlKpfsgdx:-MtykCL71WMzlKpfsgdy:b-v5aerk) ([raw file](https://github.com/harness/harness-core/blob/0226606deb6d25e2a7038df2f4eb8ef45fea81ba/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L294)):*
> ```Java
>       taskFailedExecutionCount++;
>       return perpetualTaskRecordDao.saveHeartbeat(taskId, heartbeatMillis, taskFailedExecutionCount);
>     }
> ```

we don't need two separate return statements, just find out taskFailedExecutionCount based on the error or not condition and return in the end.

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30130)* status: 0 of 1 approvals obtained.

**Review by Xin-Harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30130)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java, line 64 at r2](https://reviewable.io/reviews/harness/harness-core/30130#-MtyidBvEQokLeZvtj-s:-Mtypowr99hL5kLxiuTw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0226606deb6d25e2a7038df2f4eb8ef45fea81ba/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L64)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this should be defined as constant and should not be 100, may be just 10
</blockquote></details>

Done.
___
*[400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java, line 294 at r2](https://reviewable.io/reviews/harness/harness-core/30130#-MtykCL71WMzlKpfsgdx:-Mtypn-F7kaLu1s8nEwC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0226606deb6d25e2a7038df2f4eb8ef45fea81ba/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L294)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we don't need two separate return statements, just find out taskFailedExecutionCount based on the error or not condition and return in the end.
</blockquote></details>

Done.

**Comment by Xin-Harness** [comment]
trigger tin1, message_metadata

**Comment by Xin-Harness** [comment]
trigger messagecheck

**Comment by Xin-Harness** [comment]
trigger ti1

**Comment by Xin-Harness** [comment]
trigger messagecheck

**Comment by Xin-Harness** [comment]
trigger authorcheck

**Comment by Xin-Harness** [comment]
When the task is failed with 500 error code, it will get record in the database.
The limitation for failed execution is 6 time, when the 6th time happen, manager will backoff the record.
Pasted Graphic 9
The perpetual task get backoff with status TASK_UNASSIGNED and unassigned reason MULTIPLE_FAILED_PERPETUAL_TASK
image
After the retry happens, the task finally get assigned and start to execute again. Only when the task get successfully executed,  the failed execution time will be set to 0.
image
The backoff reduce the execution frequency of the task since when the assign try count goes up, the task will need to wait more time to get assigned.
image

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 3 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30130)* status: :shipit: complete! ✓

**Pull request merged**
