### PR TITLE
fix: [DEL-4354]: Introducing metric for secret cache

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34625)

### CODE REVIEW

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34625)* status: 7 file(s) to review. 0 of 1 approvals obtained. 

___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 636 at r1](https://reviewable.io/reviews/harness/harness-core/34625#-N5Fr4CB5LDaEUDeVO_k:-N5Fr4CB5LDaEUDeVO_l:b9nxoyc) ([raw file](https://github.com/harness/harness-core/blob/d03eb09ec1049052bab8505a180bab178862464e/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L636)):*
> ```Java
>               String delegateVersion = (String) delegateData.get(DELEGATE_VERSION);
>               runningVersions.put(delegateVersion, delegateProcess);
>               int delegateMinorVersion = getMinorVersion(delegateVersion);DelegateMetricsServiceImpl.java
> ```

you added by mistake. remove it.



_Code quote:_
```Java
DelegateMetricsServiceImpl.java
```

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34625)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/expression/NgSecretManagerFunctor.java` line 79 at r2](https://reviewable.io/reviews/harness/harness-core/34625#-N5HaWZq3BXnxTwEACaa:-N5HaWZsE10Q-_8xCtGP:bi6bcmn) ([raw file](https://github.com/harness/harness-core/blob/07557e394e013a058883adea0408f6fb9eab229a/400-rest/src/main/java/software/wings/expression/NgSecretManagerFunctor.java#L79)):*
> ```Java
>   @Builder.Default private Map<String, SecretDetail> secretDetails = new HashMap<>();
> 
>   @Inject private DelegateMetricsService delegateMetricsService;
> ```

By having `@Value` class annotation all the fields are `private final` automagically. You should probably for consistency either add `private final` keyword or remove it everywhere (same result), also you should not use field level injection (makes the proper unit testing impossible). Instead, pass the metrics service through a constructor/builder (from looking at the code, there is one layer in between this one and where the metrics service is available, so you would probably need to wire it through)
___
*[`400-rest/src/main/java/software/wings/expression/SecretManagerFunctor.java` line 79 at r2](https://reviewable.io/reviews/harness/harness-core/34625#-N5HcB-p-B5pbPF9dAm4:-N5HcB-p-B5pbPF9dAm5:b6fvw5j) ([raw file](https://github.com/harness/harness-core/blob/07557e394e013a058883adea0408f6fb9eab229a/400-rest/src/main/java/software/wings/expression/SecretManagerFunctor.java#L79)):*
> ```Java
>   @Default private Map<String, SecretDetail> secretDetails = new HashMap<>();
> 
>   @Inject private io.harness.metrics.intfc.DelegateMetricsService delegateMetricsService;
> ```

Same, don't inject and make all the fields consistent (because you have `@Value`)

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 8 of 10 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34625)* status: 1 change requests. 2. unresolved discussions.

**Review by mdmilic — APPROVED** [review]
> Reviewed 8 of 10 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34625)* status: :shipit: complete! ✓

**Pull request merged**
