### PR TITLE
feat: [CDS-83644]: fix Pipeline V1 individual Schema ( verify it has all values as V0 in nodeToResolvedSchema Map, all stages it is not working )

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
fix Pipeline V1 individual Schema ( verify it has all values as V0 in nodeToResolvedSchema Map, all stages it is not working)
 
 Verified CD and Custom stage steps are coming in schema, for stages like IACM etc, they will need to fix path in schema for v1

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55567)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55567)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by shalini-agr — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55567)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/yaml/individualschema/BasePipelineSchemaParser.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/55567#-NjfMMBo4owr30nR3CdQ:-NjfMMBo4owr30nR3CdR:bpj26jf) ([raw file](https://github.com/harness/harness-core/blob/58e2f25b740a65a8fdf4127a5b4b056c5e87905c/pipeline-service/service/src/main/java/io/harness/yaml/individualschema/BasePipelineSchemaParser.java#L35)):*
> ```Java
>   abstract String getYamlVersion();
> 
>   abstract ObjectNodeWithMetadata getRootStageNode(String currentFqn, ObjectNode objectNode);
> ```

for both v0 and v1, the implementation of these two methods is the same, only the paths of stages oneOf and step node are different, so, can we keep these methods implemented here only and make two abstract methods to get the paths?

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55567)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/yaml/individualschema/BasePipelineSchemaParser.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/55567#-NjfMMBo4owr30nR3CdQ:-NjfPLVK7YWwoIFhM41C:b-ln5jzy) ([raw file](https://github.com/harness/harness-core/blob/58e2f25b740a65a8fdf4127a5b4b056c5e87905c/pipeline-service/service/src/main/java/io/harness/yaml/individualschema/BasePipelineSchemaParser.java#L35)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

for both v0 and v1, the implementation of these two methods is the same, only the paths of stages oneOf and step node are different, so, can we keep these methods implemented here only and make two abstract methods to get the paths?
</blockquote></details>

I thought of that before implementing but in this function apart from comparing the fqn we are just returning ObjectNodeWithMetadata builder object , also this function makes more sense to be in individual parsers

**Review by shalini-agr — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55567)* status: 3 file(s) to review.

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Pull request merged**
