### PR TITLE
[fix]: [PL-21563]: Fix for secret ref not visible / masked

### PR DESCRIPTION
**Pull request by nishantsaini20**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30124)

### CODE REVIEW

**Comment by nishantsaini20** [comment]
trigger messagecheck

**Comment by nishantsaini20** [comment]
trigger messagecheck

**Review by piyush-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30124)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java, line 116 at r1](https://reviewable.io/reviews/harness/harness-core/30124#-Mu-eHHH6q_8ktWCYTEC:-Mu-eHHH6q_8ktWCYTED:b-bmb5yh) ([raw file](https://github.com/harness/harness-core/blob/b2c28c980a046a6f3eeb60ddf19f0125d9a90512/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L116)):*
> ```Java
>     if (secret.getType() == SecretText) {
>       SecretTextSpec secretSpec = (SecretTextSpec) secret.getSecretSpec();
>       if (ValueType.Reference.equals(secretSpec.getValueType())) {
> ```

nit: `ValueType.Reference == secretSpec.getValueType()`

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30124)* status: :shipit: complete! ✓

**Pull request merged**
