### PR TITLE
fix: [CDS-50952]: Improved error message and fixed failure response even after successfully email is sent

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes

We are getting email step execution failure, even though mail got sent successfully
Customer yaml:
`- step:
              identifier: "Email_1"
              type: "Email"
              name: "Email_1"
              spec:
                to: "abc@gmail.com"
                cc: "<+pipeline.triggeredBy.email>"
                subject: "Test Notification"
                body: "<+\"Pod Name\" + <+pipeline.stages.Deploy.spec.execution.steps.rolloutDeployment.deploymentInfoOutcome.serverInstanceInfoList[0].name>\
                  \ >"
              timeout: "1d"`
For the customer case ,
to-email : size is 0 (as provided email [abc@gmail.com] is invalid one, so it will discarded logically)
CC-email: size is 1 (valid email is passed)
Now in the end we are trying to create a boolean list of size 0 (count)

NotificationProcessingResponse.nonSent(toemailIds.size())

According to code we are missing cc emails count while creating boolean list,
This leads to throwing failure error,as it assumes no emails are sent .

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43237)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email/EmailStep.java` line 95 at r1](https://reviewable.io/reviews/harness/harness-core/43237#-NN2zuyk45eVKpaftLtX:-NN2zuyk45eVKpaftLtY:b1minsp) ([raw file](https://github.com/harness/harness-core/blob/454111e13d610ce59ce10ad3473f8b436aa578dc/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email/EmailStep.java#L95)):*
> ```Java
>     }
>     if (emailStepParameters.body == null || StringUtils.isBlank(emailStepParameters.body.getValue())) {
>       throw new InvalidRequestException("Email body cannot be blank");
> ```

We should put @NotNull annotations in EmailStepParameters so that user is not able to save step without these fields

**Comment by vivekkarnatiharness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email/EmailStep.java` line 95 at r1](https://reviewable.io/reviews/harness/harness-core/43237#-NN2zuyk45eVKpaftLtX:-NN4sQ9z9Z0fAafvdiUR:b-u6dnqe) ([raw file](https://github.com/harness/harness-core/blob/454111e13d610ce59ce10ad3473f8b436aa578dc/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email/EmailStep.java#L95)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We should put @NotNull annotations in EmailStepParameters so that user is not able to save step without these fields
</blockquote></details>

Ui by default adds body : "" to yaml,so @notnull does not work

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43237)* status: :shipit: complete! ✓

**Comment by vivekkarnatiharness** [comment]
trigger messagecheck

**Comment by vivekkarnatiharness** [comment]
trigger messagecheck

**Pull request merged**
