### PR TITLE
feat: [PIE-8955]: Add background cache handling for git-file-batch API call (#45381)

### PR DESCRIPTION
**Pull request by mohitg0795**
* feat: [PIE-8955]: refactored background caching gitx service

* feat: [PIE-8955]: added support for background cache refresh for batch files

* feat: [PIE-8955]: fixed dependency injection issue for background cache refresh runnable

* feat: [PIE-8955]: use abortpolicy in gitx cache background thread executor

* feat: [PIE-8955]: fixed handling for git batch file fetch runnable

* feat: [PIE-8955]: added error handling in git batch file fetch runnable

* feat: [PIE-8955]: fix cache update logic for batch file request

* feat: [PIE-8955]: use manager executable for effective context mapping in executor service threads

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[PIE-8955]: https://harness.atlassian.net/browse/PIE-8955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIE-8955]: https://harness.atlassian.net/browse/PIE-8955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIE-8955]: https://harness.atlassian.net/browse/PIE-8955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIE-8955]: https://harness.atlassian.net/browse/PIE-8955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIE-8955]: https://harness.atlassian.net/browse/PIE-8955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIE-8955]: https://harness.atlassian.net/browse/PIE-8955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIE-8955]: https://harness.atlassian.net/browse/PIE-8955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIE-8955]: https://harness.atlassian.net/browse/PIE-8955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45495)

### CODE REVIEW

**Review by kapil-harness — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45495)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45495)* status: :shipit: complete! ✓

**Review by adivishy1 — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45495)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45495)* status: :shipit: complete! ✓

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/core/runnable/GitBackgroundCacheRefreshHelper.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/45495#-NRBqMQ734JnYSkQU-rb:-NRBqMQ734JnYSkQU-rc:bjx7lkb) ([raw file](https://github.com/harness/harness-core/blob/2fb635ac5b1179aa45d43bf46e0269440606c344/136-git-sync-manager/src/main/java/io/harness/gitsync/core/runnable/GitBackgroundCacheRefreshHelper.java#L26)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.PIPELINE)
> public class GitBackgroundCacheRefreshHelper {
> ```

Shouldn't this be a singleton?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/core/runnable/GitBackgroundCacheRefreshHelper.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/45495#-NRBqMQ734JnYSkQU-rb:-NRBuo4f45JMHJ0Ig3eA:b-cr92e8) ([raw file](https://github.com/harness/harness-core/blob/2fb635ac5b1179aa45d43bf46e0269440606c344/136-git-sync-manager/src/main/java/io/harness/gitsync/core/runnable/GitBackgroundCacheRefreshHelper.java#L26)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Shouldn't this be a singleton?
</blockquote></details>

Do you mean @Singleton? What does it do?

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45495)* status: :shipit: complete! ✓

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/core/runnable/GitBackgroundCacheRefreshHelper.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/45495#-NRBqMQ734JnYSkQU-rb:-NRBvHfWC1ybFw9uJRG1:b6an6jr) ([raw file](https://github.com/harness/harness-core/blob/2fb635ac5b1179aa45d43bf46e0269440606c344/136-git-sync-manager/src/main/java/io/harness/gitsync/core/runnable/GitBackgroundCacheRefreshHelper.java#L26)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Do you mean @Singleton? What does it do?
</blockquote></details>

done, discussed offline

**Pull request merged**
