### PR TITLE
feat: [CDS-44498]: Integrate freeze with Pipeline

### PR DESCRIPTION
**Pull request by abhinavmittal-harness**
Screenshot 2022-10-26 at 4 38 34 PM
Screenshot 2022-10-26 at 4 39 04 PM
## Describe your changes

- Introduced a new status FREEZE_FAILED which will be set at the service step if service or env being used are configured to be frozen at the time. in this scenario pipeline will fail and move to this new status and a freeze outcome will be stored in the summary.

Screenshot 2022-10-21 at 5 15 53 PM
Screenshot 2022-10-21 at 5 23 52 PM
Screenshot 2022-10-21 at 5 15 47 PM

All changes are behind ff
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38587)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger feature-build

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 21 files at r1, 8 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38587)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 218 at r2](https://reviewable.io/reviews/harness/harness-core/38587#-NEsx_CY9HSsyg4Vdj2c:-NEsx_CY9HSsyg4Vdj2d:b-yx5iu4) ([raw file](https://github.com/harness/harness-core/blob/061e03d40d2cb4f36db50fdbda103701a3b0fcbe/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L218)):*
> ```Java
>       entityMap.put(FreezeEntityType.PROJECT, Lists.newArrayList(environment.get().getProjectIdentifier()));
>       entityMap.put(FreezeEntityType.ENVIRONMENT, Lists.newArrayList(environment.get().getIdentifier()));
>       entityMap.put(FreezeEntityType.ENV_TYPE, Lists.newArrayList(environment.get().getType().name()));
> ```

This entityMap feels redudant across methods in this class



_Code quote:_
```Java
      entityMap.put(FreezeEntityType.ORG, Lists.newArrayList(environment.get().getOrgIdentifier()));
      entityMap.put(FreezeEntityType.PROJECT, Lists.newArrayList(environment.get().getProjectIdentifier()));
      entityMap.put(FreezeEntityType.ENVIRONMENT, Lists.newArrayList(environment.get().getIdentifier()));
      entityMap.put(FreezeEntityType.ENV_TYPE, Lists.newArrayList(environment.get().getType().name()));
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 481 at r2](https://reviewable.io/reviews/harness/harness-core/38587#-NEsy8ZOCSMiT3juYi2_:-NEsy8ZOCSMiT3juYi2a:bqnk2n3) ([raw file](https://github.com/harness/harness-core/blob/061e03d40d2cb4f36db50fdbda103701a3b0fcbe/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L481)):*
> ```Java
>   protected ChildrenExecutableResponse executeFreezePart(
>       Ambiance ambiance, Map<FreezeEntityType, List<String>> entityMap) {
>     if (ngFeatureFlagHelperService.isEnabled(AmbianceUtils.getAccountId(ambiance), FeatureName.NG_DEPLOYMENT_FREEZE)) {
> ```

I think we are calling feature flag service twice in this plan step
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/execution/ExecutionStatus.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/38587#-NEt0L4J7UjHTxtl660R:-NEt0L4J7UjHTxtl660S:bfcpyi0) ([raw file](https://github.com/harness/harness-core/blob/061e03d40d2cb4f36db50fdbda103701a3b0fcbe/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/execution/ExecutionStatus.java#L55)):*
> ```Java
>   @JsonIgnore APPROVAL_REJECTED(Status.APPROVAL_REJECTED, true),
>   @JsonIgnore WAITING(Status.RESOURCE_WAITING, "Waiting", true),
>   @JsonIgnore ABORTED_DUE_TO_FREEZE(Status.FREEZE_FAILED, "AbortedDueToFreeze");
> ```

Dont add it here, add below input waiting, and without underscore



_Code quote:_
```Java
@JsonIgnore ABORTED_DUE_TO_FREEZE(Status.FREEZE_FAILED, "AbortedDueToFreeze");
```

**Review by abhinavmittal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38587)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 218 at r2](https://reviewable.io/reviews/harness/harness-core/38587#-NEsx_CY9HSsyg4Vdj2c:-NEuRS1H-N-XV1L1v5X5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/061e03d40d2cb4f36db50fdbda103701a3b0fcbe/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L218)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

This entityMap feels redudant across methods in this class
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 481 at r2](https://reviewable.io/reviews/harness/harness-core/38587#-NEsy8ZOCSMiT3juYi2_:-NEuRXuA0AstLdzeFgai:bcb9obp) ([raw file](https://github.com/harness/harness-core/blob/061e03d40d2cb4f36db50fdbda103701a3b0fcbe/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L481)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I think we are calling feature flag service twice in this plan step
</blockquote></details>

Yes but it is needed since it is async call and the method is called from diff scope
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/execution/ExecutionStatus.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/38587#-NEt0L4J7UjHTxtl660R:-NEuRTyaE6xvStxVmVws:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/061e03d40d2cb4f36db50fdbda103701a3b0fcbe/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/execution/ExecutionStatus.java#L55)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Dont add it here, add below input waiting, and without underscore
</blockquote></details>

Done.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 600 at r2](https://reviewable.io/reviews/harness/harness-core/38587#-NEuYy9R94vf-j8tmhuX:-NEuYy9R94vf-j8tmhuY:b-kulr2l) ([raw file](https://github.com/harness/harness-core/blob/061e03d40d2cb4f36db50fdbda103701a3b0fcbe/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L600)):*
> ```Java
>           "NG Freeze: Failure occurred when evaluating execution should fail due to freeze at the time of plan creation");
>     }
>     if (!EmptyPredicate.isEmpty(projectFreezeConfigs)) {
> ```

nit: we can just use EmptyPredicate::isNotEmpty

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 593 at r2](https://reviewable.io/reviews/harness/harness-core/38587#-NEvNInJ9RosMd27MbEY:-NEvNInJ9RosMd27MbEZ:b-efux3l) ([raw file](https://github.com/harness/harness-core/blob/061e03d40d2cb4f36db50fdbda103701a3b0fcbe/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L593)):*
> ```Java
>         PlanCreationContextValue planCreationContextValue = ctx.getMetadata();
>         projectFreezeConfigs =
>             freezeEvaluateService.shouldDisableDeployment(planCreationContextValue.getAccountIdentifier(),
> ```

nit: this looks a bit confusing, shouldDisable should return a boolean ideally

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 601 at r2](https://reviewable.io/reviews/harness/harness-core/38587#-NEvNaETCvrIQkpaQBWU:-NEvNaETCvrIQkpaQBWV:b-fdys6o) ([raw file](https://github.com/harness/harness-core/blob/061e03d40d2cb4f36db50fdbda103701a3b0fcbe/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L601)):*
> ```Java
>     }
>     if (!EmptyPredicate.isEmpty(projectFreezeConfigs)) {
>       throw new NGFreezeException("Execution can't be performed because project is frozen");
> ```

should we give more information here ? like frozen till when or something similar ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 134 at r4](https://reviewable.io/reviews/harness/harness-core/38587#-NEvYJj-7XKBhXCZFnpc:-NEvYJj-7XKBhXCZFnpd:bwz1dkj) ([raw file](https://github.com/harness/harness-core/blob/b87f060a04dd7254d0f0bcadc835e44dec744765/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L134)):*
> ```Java
>       saveExecutionLog(logCallback, "Starting service step...");
> 
>       Map<FreezeEntityType, List<String>> entityMap = new HashMap<>();
> ```

should we do this freeze logic separately i.e let the executeService and executeEnvironment be the same
We already know all the identifiers from the `ServiceStepV3Parameters`

**Review by abhinavmittal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38587)* status: 9 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 593 at r2](https://reviewable.io/reviews/harness/harness-core/38587#-NEvNInJ9RosMd27MbEY:-NF4NDAe5meEoxzpCbs0:bxas6eg) ([raw file](https://github.com/harness/harness-core/blob/061e03d40d2cb4f36db50fdbda103701a3b0fcbe/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L593)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: this looks a bit confusing, shouldDisable should return a boolean ideally
</blockquote></details>

Have renamed this as we will use the list to improve the message sent
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 601 at r2](https://reviewable.io/reviews/harness/harness-core/38587#-NEvNaETCvrIQkpaQBWU:-NF3n1w24G0NIAXwAnw1:bpbtuqt) ([raw file](https://github.com/harness/harness-core/blob/061e03d40d2cb4f36db50fdbda103701a3b0fcbe/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L601)):*
> EmptyPredicate::isNotEmpty
Will be done once as part of notifications ticket.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 134 at r4](https://reviewable.io/reviews/harness/harness-core/38587#-NEvYJj-7XKBhXCZFnpc:-NF4N4ePDdyL0xS0Fl6M:b-mas1gn) ([raw file](https://github.com/harness/harness-core/blob/b87f060a04dd7254d0f0bcadc835e44dec744765/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L134)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we do this freeze logic separately i.e let the executeService and executeEnvironment be the same
We already know all the identifiers from the `ServiceStepV3Parameters`
</blockquote></details>

I have kept it separately as we might need information that may be specific to each and not be present in stepParameters. for instance envType

**Review by abhinavmittal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38587)* status: 12 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 600 at r2](https://reviewable.io/reviews/harness/harness-core/38587#-NEuYy9R94vf-j8tmhuX:-NF4OcYG0VvPorF5Rr9I:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/061e03d40d2cb4f36db50fdbda103701a3b0fcbe/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L600)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: we can just use EmptyPredicate::isNotEmpty
</blockquote></details>

Done

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 7 of 21 files at r1, 10 of 13 files at r2, 1 of 3 files at r3, 4 of 5 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38587)* status: 1 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/freeze/FreezeOutcome.java` line 31 at r6](https://reviewable.io/reviews/harness/harness-core/38587#-NF4xKmu135Y-PLPFs7e:-NF4xKmu135Y-PLPFs7f:b-s45oc7) ([raw file](https://github.com/harness/harness-core/blob/86ebbdd82f06c534518d1d16ec811b8749606ac4/127-cd-nextgen-entities/src/main/java/io/harness/cdng/freeze/FreezeOutcome.java#L31)):*
> ```Java
> @RecasterAlias("io.harness.cdng.freeze.FreezeOutcome")
> public class FreezeOutcome implements Outcome, ExecutionSweepingOutput {
>   // Maps to NGServiceConfig
> ```

comment not valid
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/freeze/FreezeOutcome.java` line 32 at r6](https://reviewable.io/reviews/harness/harness-core/38587#-NF4xO9xAVGUZK_0_bfa:-NF4xO9xAVGUZK_0_bfb:brc7o1k) ([raw file](https://github.com/harness/harness-core/blob/86ebbdd82f06c534518d1d16ec811b8749606ac4/127-cd-nextgen-entities/src/main/java/io/harness/cdng/freeze/FreezeOutcome.java#L32)):*
> ```Java
> public class FreezeOutcome implements Outcome, ExecutionSweepingOutput {
>   // Maps to NGServiceConfig
>   @NotNull boolean frozen;
> ```

@Notnull is redundant

**Review by abhinavmittal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38587)* status: 4 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/freeze/FreezeOutcome.java` line 32 at r6](https://reviewable.io/reviews/harness/harness-core/38587#-NF4xO9xAVGUZK_0_bfa:-NFFTzJf9aDK3qasSX-k:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/86ebbdd82f06c534518d1d16ec811b8749606ac4/127-cd-nextgen-entities/src/main/java/io/harness/cdng/freeze/FreezeOutcome.java#L32)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

@Notnull is redundant
</blockquote></details>

Done.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 21 files at r1, 2 of 13 files at r2, 2 of 3 files at r3, 1 of 5 files at r5, 1 of 3 files at r7, 1 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38587)* status: 4 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by archit-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38587)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 13 files at r2, 1 of 3 files at r3, 2 of 3 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38587)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38587)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38587)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r10, 1 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38587)* status: 2 file(s) to review.

**Pull request merged**
