### PR TITLE
feat: [PL-27627]: user email update via SCIM

### PR DESCRIPTION
**Pull request by ujjawal-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37067)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37067)

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 355 at r2](https://reviewable.io/reviews/harness/harness-core/37067#-NBC4TdK-lVITwrBiChd:-NBC4TdK-lVITwrBiChe:bd2683q) ([raw file](https://github.com/harness/harness-core/blob/6f6190bbd904960269352a953d8ae9eefe9b7890/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L355)):*
> ```Java
>       if (featureFlagService.isEnabled(FeatureName.UPDATE_EMAILS_VIA_SCIM, accountId)
>           && userResource.getEmails() != null && userResource.getEmails().get(0) != null
>           && userResource.getEmails().get(0).get("value").asText() != null
> ```

minor we should add one more check here 
`userResource.getEmails().get(0).findValue("value") != null` 



_Code quote:_
```Java
&& userResource.getEmails().get(0).get("value").asText()
```

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37067)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 272 at r2](https://reviewable.io/reviews/harness/harness-core/37067#-NBEP2lW2m0ifqMdaqLX:-NBEP2lW2m0ifqMdaqLY:b-bsmlz5) ([raw file](https://github.com/harness/harness-core/blob/6f6190bbd904960269352a953d8ae9eefe9b7890/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L272)):*
> ```Java
>       UpdateOperations<User> updateOperation = wingsPersistence.createUpdateOperations(User.class);
>       updateOperation.set(UserKeys.name, patchOperation.getValue(String.class));
>       userService.updateUser(user.getUuid(), updateOperation);
> ```

we are already making an update call above, then we are again updating same user here. We should ideally create a single update call with all updates

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 271 at r2](https://reviewable.io/reviews/harness/harness-core/37067#-NBEPKgn56jU0Tf1AOAy:-NBEPKgn56jU0Tf1AOAz:b-t3z8vl) ([raw file](https://github.com/harness/harness-core/blob/6f6190bbd904960269352a953d8ae9eefe9b7890/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L271)):*
> ```Java
>         && patchOperation.getValue(ScimMultiValuedObject.class).getDisplayName() != null) {
>       UpdateOperations<User> updateOperation = wingsPersistence.createUpdateOperations(User.class);
>       updateOperation.set(UserKeys.name, patchOperation.getValue(String.class));
> ```

just curious, earlier we are setting email as patchOperation.getValue(String.class) and here we are setting name as the same value, how's that so? Is there something I'm missing here?

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 360 at r2](https://reviewable.io/reviews/harness/harness-core/37067#-NBEQ-mM-yKYcKSyrbcT:-NBEQ-mM-yKYcKSyrbcU:bi5ddjv) ([raw file](https://github.com/harness/harness-core/blob/6f6190bbd904960269352a953d8ae9eefe9b7890/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L360)):*
> ```Java
>         String emailFromScim = userResource.getEmails().get(0).get("value").asText();
>         updateOperations.set(UserKeys.email, emailFromScim);
>         log.info("SCIM: Updated user's {}, email from {} to email id: {}", userId, user.getEmail(), emailFromScim);
> ```

This logline can be misleading. It says "updated user's email id" while the operation has still not be done until now. It may happen that update operation fails and we still see this logline which would lead to confusion.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37067)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by ujjawal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37067)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 272 at r2](https://reviewable.io/reviews/harness/harness-core/37067#-NBEP2lW2m0ifqMdaqLX:-NBGc4c31y4q2CeD7ax6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6f6190bbd904960269352a953d8ae9eefe9b7890/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L272)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we are already making an update call above, then we are again updating same user here. We should ideally create a single update call with all updates
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 360 at r2](https://reviewable.io/reviews/harness/harness-core/37067#-NBEQ-mM-yKYcKSyrbcT:-NBGc5lp10b-ssspXeQi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6f6190bbd904960269352a953d8ae9eefe9b7890/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L360)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This logline can be misleading. It says "updated user's email id" while the operation has still not be done until now. It may happen that update operation fails and we still see this logline which would lead to confusion.
</blockquote></details>

Done.

**Comment by ujjawal-harness** [comment]
trigger ti0

**Review by kapil-harness — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37067#-:-NBGohAY86Hta854f_wN:bnfp4nl)* status: 2. unresolved discussions.

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 272 at r2](https://reviewable.io/reviews/harness/harness-core/37067#-NBEP2lW2m0ifqMdaqLX:-NBGtU5wAKOhi8YvD5jS:b6455sq) ([raw file](https://github.com/harness/harness-core/blob/6f6190bbd904960269352a953d8ae9eefe9b7890/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L272)):*
<details><summary><i>Previously, ujjawal-harness (Ujjawal Prasad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see two update calls @ujjawal-harness

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 264 at r4](https://reviewable.io/reviews/harness/harness-core/37067#-NBGtvsp1dQqw1pAzUGm:-NBGtvsp1dQqw1pAzUGn:bqu6kxe) ([raw file](https://github.com/harness/harness-core/blob/74f242792d86d02c3242d1b68cf87fdd9a8fb5fd/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L264)):*
> ```Java
>       updateOperation.set(UserKeys.email, patchOperation.getValue(String.class));
>       userService.updateUser(user.getUuid(), updateOperation);
>       log.info("SCIM: Updated user's {}, email from {} to email id: {}", userId, user.getEmail(),
> ```

log should be : Updating user ??

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 272 at r2](https://reviewable.io/reviews/harness/harness-core/37067#-NBEP2lW2m0ifqMdaqLX:-NBGuOj2-N6eRg5h3jmf:b-tgwjpv) ([raw file](https://github.com/harness/harness-core/blob/6f6190bbd904960269352a953d8ae9eefe9b7890/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L272)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

I still see two update calls @ujjawal-harness 
</blockquote></details>

Also, I see this piece of code is duplicate. We should have a common code to update user properties and use the same to call from everywhere. We can pass the properties to update as parameters in those calls.



_Code quote:_
```Java
      UpdateOperations<User> updateOperation = wingsPersistence.createUpdateOperations(User.class);
      updateOperation.set(UserKeys.name, patchOperation.getValue(String.class));
      userService.updateUser(user.getUuid(), updateOperation);
```

**Review by shashank-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37067)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Review by ujjawal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37067)* status: 1 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 272 at r2](https://reviewable.io/reviews/harness/harness-core/37067#-NBEP2lW2m0ifqMdaqLX:-NBGyak4DZ4wEh5oAYIc:b-we0kzv) ([raw file](https://github.com/harness/harness-core/blob/6f6190bbd904960269352a953d8ae9eefe9b7890/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L272)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Also, I see this piece of code is duplicate. We should have a common code to update user properties and use the same to call from everywhere. We can pass the properties to update as parameters in those calls.
</blockquote></details>

discussed why its required
___
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 264 at r4](https://reviewable.io/reviews/harness/harness-core/37067#-NBGtvsp1dQqw1pAzUGm:-NBGyZhp1XYaKAFo2ujp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/74f242792d86d02c3242d1b68cf87fdd9a8fb5fd/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L264)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

log should be : Updating user ??
</blockquote></details>

Done.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37067)* status: 1 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 272 at r2](https://reviewable.io/reviews/harness/harness-core/37067#-NBEP2lW2m0ifqMdaqLX:-NBHAFfk9piiwGFI2H3M:b-wo3acw) ([raw file](https://github.com/harness/harness-core/blob/6f6190bbd904960269352a953d8ae9eefe9b7890/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L272)):*
<details><summary><i>Previously, ujjawal-harness (Ujjawal Prasad) wrote…</i></summary><blockquote>

discussed why its required
</blockquote></details>

@shashank-harness / @ujjawal-harness can someone mention the discussion details over here for wider visibility

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37067)* status: 1. unresolved discussions.

**Comment by ujjawal-harness** [comment]
ticket for ScimMultiValuedObject understanding 

https://harness.atlassian.net/browse/PL-28006

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37067)* status: :shipit: complete! ✓

**Pull request merged**
