### PR TITLE
fix: [PL-27019]: fixed account user limit check in NG

### PR DESCRIPTION
**Pull request by ujjawal-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35737)

### CODE REVIEW

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35737)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 1345 at r2](https://reviewable.io/reviews/harness/harness-core/35737#-N8-hl6uEKO4lNGGBsYx:-N8-hl6uEKO4lNGGBsYy:b-9uorsu) ([raw file](https://github.com/harness/harness-core/blob/919c8ec871e4c827f771a441441464a6abe2a7af/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L1345)):*
> ```Java
>       return false;
>     } catch (Exception e) {
>       log.error("Exception while checking user limit for account {}", accountId);
> ```

log exception here

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 1347 at r2](https://reviewable.io/reviews/harness/harness-core/35737#-N8-hoEC9nt4yoWnkkOG:-N8-hoEC9nt4yoWnkkOH:btn7yxy) ([raw file](https://github.com/harness/harness-core/blob/919c8ec871e4c827f771a441441464a6abe2a7af/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L1347)):*
> ```Java
>       log.error("Exception while checking user limit for account {}", accountId);
>     }
>     return true;
> ```

is it expected behaviour that if our check has failed, we still say that limit has reached?

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 1362 at r2](https://reviewable.io/reviews/harness/harness-core/35737#-N8-i0EX1iywhCxPBqiu:-N8-i0EX1iywhCxPBqiv:bd09bew) ([raw file](https://github.com/harness/harness-core/blob/919c8ec871e4c827f771a441441464a6abe2a7af/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L1362)):*
> ```Java
>       userServiceLimitChecker.limitCheck(accountId, existingUsersAndInvites, new HashSet<>(Arrays.asList(email)));
>     } catch (WingsException e) {
>       log.error("The user limit has been reached for account {} and email {}", accountId, email);
> ```

Log line looks wrong. Why do we say that limit has reached if its an exception?

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 353 at r2](https://reviewable.io/reviews/harness/harness-core/35737#-N8-iK5h9vrNv2EOeNGb:-N8-iK5h9vrNv2EOeNGc:b-ceggp7) ([raw file](https://github.com/harness/harness-core/blob/919c8ec871e4c827f771a441441464a6abe2a7af/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L353)):*
> ```Java
>     boolean limitHasBeenReached = RestClientUtils.getResponse(userClient.checkUserLimit(accountId, emailId));
>     if (limitHasBeenReached) {
>       throw new InvalidRequestException("The user count limit has been reached in this account");
> ```

shouldn't we simply make it return true if limit is reached and false otherwise? Any particular reason of throwing exception here?

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Vulnerability 1 Vulnerabilities 
 
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35737)

**Review by ujjawal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35737)* status: 7 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 353 at r2](https://reviewable.io/reviews/harness/harness-core/35737#-N8-iK5h9vrNv2EOeNGb:-N8TSdkhAiEGLcuFHPZG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/919c8ec871e4c827f771a441441464a6abe2a7af/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L353)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

shouldn't we simply make it return true if limit is reached and false otherwise? Any particular reason of throwing exception here?
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 1345 at r2](https://reviewable.io/reviews/harness/harness-core/35737#-N8-hl6uEKO4lNGGBsYx:-N8TSerG7VZ5bxn8xt0P:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/919c8ec871e4c827f771a441441464a6abe2a7af/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L1345)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

log exception here
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 1347 at r2](https://reviewable.io/reviews/harness/harness-core/35737#-N8-hoEC9nt4yoWnkkOG:-N8TSgFsEzpWIOLjxSqN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/919c8ec871e4c827f771a441441464a6abe2a7af/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L1347)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

is it expected behaviour that if our check has failed, we still say that limit has reached?
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 1362 at r2](https://reviewable.io/reviews/harness/harness-core/35737#-N8-i0EX1iywhCxPBqiu:-N8TSjLX9MNk7QV6dO4t:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/919c8ec871e4c827f771a441441464a6abe2a7af/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L1362)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Log line looks wrong. Why do we say that limit has reached if its an exception?
</blockquote></details>

Done.

**Comment by ujjawal-harness** [comment]
trigger ti1

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35737)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by boopesh007 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35737)* status: 4 file(s) to review.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35737)* status: :shipit: complete! ✓

**Pull request merged**
