### PR TITLE
[fix]: [CDS-38662]: Support terragrunt destroy -auto-approve in newer versions

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34193)

FF- TG_USE_AUTO_APPROVE_FLAG
with FF off- code flow and behaviour is as it was earlier 
with FF on : 
Inside Destroy, first we are fetching the underlying terraform version that is getting used by used by Terragrunt , Then we are using either of -force and -auto-approve flag in terragrunt destroy command based on the terraform version.
As -force flag is no longer supported in terraform version > 15.0.0
PS:
a) we have tried to ensure that with FF off, behaviour is same
b) Even with FF on, changes are tried to be implemented in scope of "destroy" operation, Keeping all other operation intact. 
c) Same changes are done for both cases, runAll & singleFile

### CODE REVIEW

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34193)* status: 10 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/34193#-N4GiJTWELhLLy-AYlxT:-N4GiJTWELhLLy-AYlxU:b-p1xis9) (no related file):*
should we not do this based on terragrunt cli version ?

___

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Comment by tchaurasiya** [comment]
*[a discussion](https://reviewable.io/reviews/harness/harness-core/34193#-N4GiJTWELhLLy-AYlxT:-N4fjw4y7kVsPt0sYR58:b-896fix) (no related file):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we not do this based on terragrunt cli version ?
</blockquote></details>

Done.

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, 2 of 3 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34193)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerragruntProvisionTaskHelper.java` line 99 at r3](https://reviewable.io/reviews/harness/harness-core/34193#-N4fs-CX3tSWyLfuvVLm:-N4fs-CX3tSWyLfuvVLn:b-4ailbl) ([raw file](https://github.com/harness/harness-core/blob/78dded8beef1fe5d9e143b602203ef525c6b88c8/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerragruntProvisionTaskHelper.java#L99)):*
> ```Java
>     if (tgInfoResponse != null && tgInfoResponse.getOutput() != null) {
>       String tgInfoOutput = tgInfoResponse.getOutput();
>       return (String) JsonUtils.jsonPath(tgInfoOutput, "TerraformBinary");
> ```

can this throw exception or return null/empty ?

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, 2 of 3 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34193)* status: 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerragruntProvisionTask.java` line 297 at r3](https://reviewable.io/reviews/harness/harness-core/34193#-N4fgO0jBY9ocE0KaC8R:-N4fgO0jBY9ocE0KaC8S:b7wukcn) ([raw file](https://github.com/harness/harness-core/blob/78dded8beef1fe5d9e143b602203ef525c6b88c8/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerragruntProvisionTask.java#L297)):*
> ```Java
>       String terraformConfigFileDirectoryPath = EMPTY;
>       TerragruntDelegateTaskOutput terragruntDelegateTaskOutput = null;
>       String tfAutoApproveArgument;
> ```

declare variable before it is about to be initialised. this variable is not used till the `switch-case` block

**Comment by tchaurasiya** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerragruntProvisionTask.java` line 297 at r3](https://reviewable.io/reviews/harness/harness-core/34193#-N4fgO0jBY9ocE0KaC8R:-N4z1OyP-lSeqh2UR_2g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/78dded8beef1fe5d9e143b602203ef525c6b88c8/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerragruntProvisionTask.java#L297)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

declare variable before it is about to be initialised. this variable is not used till the `switch-case` block
</blockquote></details>

Done.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 2 of 9 files at r1, 2 of 3 files at r2, 11 of 13 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34193)* status: 2 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34193)* status: 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34193)* status: 1 change requests. 1. unresolved discussions.

**Review by namantalaycha10 — APPROVED** [review]

**Review by namantalaycha10 — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 2 of 3 files at r2, 11 of 13 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34193)* status: 1 change requests. 1. unresolved discussions.

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34193)* status: :shipit: complete! ✓

**Pull request merged**
