### PR TITLE
[feat]: [CDS-75113]: Applied RepoBasedFilter in listRepo flow for a repo Level connector, without checking presence of repo in GIT response.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Context: For a repoLevel connector many times repo isn't fetched in GIT response and filtering that repoResponse with RepoBasedFilter gave empty response.

Change: Fixed by not checking the presence of repo in GIT repo and directly applying the repoBasedFilter.

Impact: list-repo feature during creation of remote entities.

Testing: Cases tested(all for a repo Level connector)

- Valid Repo
- Invalid Repo
- Repo included in gitFetchResponse
- Repo not included in gitFetchResponse

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50921)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger uts

**Comment by adivishy1** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 818 at r1](https://reviewable.io/reviews/harness/harness-core/50921#-NaBYdWtErs0A1fi1bLB:-NaBYdWtErs0A1fi1bLC:b-f1926z) ([raw file](https://github.com/harness/harness-core/blob/ead859e6757ac99df9479655c2c55f0e47c5dd8a/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L818)):*
> ```Java
>       } catch (HintException ex) {
>         return Collections.EMPTY_LIST;
>       }
> ```

i see there are already 3 such gitRepoAllowlistHelper.validateRepo calls being made, can you create a method and call it from there?

**Review by adivishy1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50921)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 836 at r4](https://reviewable.io/reviews/harness/harness-core/50921#-NaG4kXl63HToYUbaTSI:-NaG4kXl63HToYUbaTSJ:b2yvjym) ([raw file](https://github.com/harness/harness-core/blob/444a2810ff288c6c27368610063bec7ac77ae991/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L836)):*
> ```Java
>           scmConnector, gitRepository.getName());
>       return Collections.singletonList(GitRepositoryResponseDTO.builder().name(gitRepository.getName()).build());
>     } catch (HintException ex) {
> ```

I think we shouldn't rely on HintException or any metadata exception like this. Things may enhance on the server side (in this case gitRepoAllowListHelper) and it may not send HintException as the outermost exception.
In this particular case, we can say it won't matter much but ideally we should rely on a concrete exception. Here, lets simply make it WingsException for now.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 826 at r4](https://reviewable.io/reviews/harness/harness-core/50921#-NaG51m3113QiGRezoCl:-NaG51m3113QiGRezoCm:b-20q06o) ([raw file](https://github.com/harness/harness-core/blob/444a2810ff288c6c27368610063bec7ac77ae991/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L826)):*
> ```Java
>   }
> 
>   private List validateAndGetRepoList(String accountIdentifier, String orgIdentifier, String projectIdentifier,
> ```

return type should be proper, not abstract.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 826 at r4](https://reviewable.io/reviews/harness/harness-core/50921#-NaG5EgQ4NRtfzbNAXPP:-NaG5EgQ4NRtfzbNAXPQ:b-dyf7v4) ([raw file](https://github.com/harness/harness-core/blob/444a2810ff288c6c27368610063bec7ac77ae991/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L826)):*
> ```Java
>   }
> 
>   private List validateAndGetRepoList(String accountIdentifier, String orgIdentifier, String projectIdentifier,
> ```

naming is a bit confusing. We aren't going to get any Repo List as such as we are only validating given single repo. May be we can just say "prepareResponse..." or something similar for better readability.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 817 at r4](https://reviewable.io/reviews/harness/harness-core/50921#-NaG5PHM0UjecrW1jlxc:-NaG5PHM0UjecrW1jlxd:b1yf7lw) ([raw file](https://github.com/harness/harness-core/blob/444a2810ff288c6c27368610063bec7ac77ae991/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L817)):*
> ```Java
>       return validateAndGetRepoList(accountIdentifier, orgIdentifier, projectIdentifier, scmConnector, gitRepository);
>     } else if (isNotEmpty(gitRepository.getOrg()) && isNamespaceNotEmpty(response)) {
>       return prepareListRepoResponseWithNamespace(scmConnector, response, gitRepository);
> ```

Doesn't the same logic should apply in this case also?

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50921)* status: 2 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 818 at r1](https://reviewable.io/reviews/harness/harness-core/50921#-NaBYdWtErs0A1fi1bLB:-NaG8xTs1HxVbi4YgRec:b-rnegdn) ([raw file](https://github.com/harness/harness-core/blob/ead859e6757ac99df9479655c2c55f0e47c5dd8a/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L818)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

i see there are already 3 such gitRepoAllowlistHelper.validateRepo calls being made, can you create a method and call it from there?
</blockquote></details>

Discussed offline that each of the 3 uses has different behaviour, in some exception is expected and in some it is to be caught,etc,
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 817 at r4](https://reviewable.io/reviews/harness/harness-core/50921#-NaG5PHM0UjecrW1jlxc:-NaG99hx3KJ8DdYCI8dO:b-qr20zn) ([raw file](https://github.com/harness/harness-core/blob/444a2810ff288c6c27368610063bec7ac77ae991/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L817)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Doesn't the same logic should apply in this case also?
</blockquote></details>

It was only for the repoLevel connector that didn't use the response of parent method to build its final response, every other case is building its final response by using the response from parent method which has already been exposed to gitRepoAllowlistFilter.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 826 at r4](https://reviewable.io/reviews/harness/harness-core/50921#-NaG51m3113QiGRezoCl:-NaG8uB37OAou383xhmS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/444a2810ff288c6c27368610063bec7ac77ae991/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L826)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

return type should be proper, not abstract.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 826 at r4](https://reviewable.io/reviews/harness/harness-core/50921#-NaG5EgQ4NRtfzbNAXPP:-NaG8uct1wFZ6cUjW6xu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/444a2810ff288c6c27368610063bec7ac77ae991/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L826)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

naming is a bit confusing. We aren't going to get any Repo List as such as we are only validating given single repo. May be we can just say "prepareResponse..." or something similar for better readability.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 836 at r4](https://reviewable.io/reviews/harness/harness-core/50921#-NaG4kXl63HToYUbaTSI:-NaG98uB3tDL7vs14zlD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/444a2810ff288c6c27368610063bec7ac77ae991/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L836)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we shouldn't rely on HintException or any metadata exception like this. Things may enhance on the server side (in this case gitRepoAllowListHelper) and it may not send HintException as the outermost exception.
In this particular case, we can say it won't matter much but ideally we should rely on a concrete exception. Here, lets simply make it WingsException for now.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50921)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by senjucanon2** [comment]
trigger uts

**Review by adivishy1 — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50921)* status: 2 file(s) to review.

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
