### PR TITLE
[feat]: [PL-29887]: Increasing character limit of Name and Id to 128 for Secrets and Connectors .

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
Currently, the character limit for Id and name fields for Harness NG entities is 64 while in CG it is 128.
Customers want to migrate from CG to NG but face this bottleneck as there are entities having Id and name more than 64 chars.
Hence, increasing character limit of Name and Id to 128 for Secrets and Connectors.

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42120)

### CODE REVIEW

**Comment by meenakshi-harness** [comment]
As discussed, we can check with other modules once if they have any integration with connector/secret identifier with 64 char validation

**Review by meenakshi-harness — DISMISSED** [review]
> Reviewed 5 of 12 files at r1, 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42120)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42120)* status: 12 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java` line 151 at r3](https://reviewable.io/reviews/harness/harness-core/42120#-NKpge288CNqysYi8ACZ:-NKpge288CNqysYi8AC_:b-gzeqgb) ([raw file](https://github.com/harness/harness-core/blob/9701757da159e5a014d17db9204fe861165708a2/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java#L151)):*
> ```Java
>   validateTheIdentifierIsUnique(
>       @Parameter(description = "Secret Identifier") @NotNull @PathParam(
>           NGCommonEntityConstants.IDENTIFIER_KEY) @EntityIdentifier(maxLength = 128) String identifier,
> ```

Why put maxLength here?

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42120)* status: 12 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/data/validator/NGEntityNameValidator.java` line 19 at r3](https://reviewable.io/reviews/harness/harness-core/42120#-NKphPSzDG2YESoSffdY:-NKphPSzDG2YESoSffdZ:b-ov1ieq) ([raw file](https://github.com/harness/harness-core/blob/9701757da159e5a014d17db9204fe861165708a2/970-ng-commons/src/main/java/io/harness/data/validator/NGEntityNameValidator.java#L19)):*
> ```Java
>   private static final String ALLOWED_CHARS_STRING =
>       "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_. ";
>   private int maxAllowedLength = 64;
> ```

Should this be initialized here? We have already specified a default value in the annotation
___
*[`980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/42120#-NKphkZ09JFkca9lsp4K:-NKphkZ09JFkca9lsp4L:bt0tsih) ([raw file](https://github.com/harness/harness-core/blob/9701757da159e5a014d17db9204fe861165708a2/980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java#L30)):*
> ```Java
>   // Start with: Alphabets, characters or Underscore
>   // Chars Allowed : Alphanumeric, Underscore, $
>   public Pattern identifierPattern = Pattern.compile("^[a-zA-Z_][0-9a-zA-Z_$]{0,63}$");
> ```

Shouldn't this be 

public static final Pattern IDENTIFIER_PATTERN = Pattern.compile("^[a-zA-Z_][0-9a-zA-Z_$]{0,%s}$");

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42120)* status: 12 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java` line 151 at r3](https://reviewable.io/reviews/harness/harness-core/42120#-NKpge288CNqysYi8ACZ:-NKq-0S087w3idvAKcGi:bqyz6eg) ([raw file](https://github.com/harness/harness-core/blob/9701757da159e5a014d17db9204fe861165708a2/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java#L151)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why put maxLength here? 
</blockquote></details>

The validation on EntityIdentifier Length gets invoked and so need to put maxLength.
___
*[`970-ng-commons/src/main/java/io/harness/data/validator/NGEntityNameValidator.java` line 19 at r3](https://reviewable.io/reviews/harness/harness-core/42120#-NKphPSzDG2YESoSffdY:-NKq-H7NEtaOMI6QVOBb:bunr9cc) ([raw file](https://github.com/harness/harness-core/blob/9701757da159e5a014d17db9204fe861165708a2/970-ng-commons/src/main/java/io/harness/data/validator/NGEntityNameValidator.java#L19)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should this be initialized here? We have already specified a default value in the annotation
</blockquote></details>

Removed initialization in class. Done
___
*[`980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/42120#-NKphkZ09JFkca9lsp4K:-NKq-Lsu29wJT081piCB:b-wxrff9) ([raw file](https://github.com/harness/harness-core/blob/9701757da159e5a014d17db9204fe861165708a2/980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java#L30)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Shouldn't this be 

public static final Pattern IDENTIFIER_PATTERN = Pattern.compile("^[a-zA-Z_][0-9a-zA-Z_$]{0,%s}$");

</blockquote></details>

Pattern is constructed based on maxLength which is input to the class. Removed the assignment here as it is EntityIdentifierValidator initialize now.

**Comment by shashank-harness** [comment]
*[`980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/42120#-NKq8uk964_e5RQGghpU:-NKq8uk964_e5RQGghpV:b-iytue8) ([raw file](https://github.com/harness/harness-core/blob/3c1bd1f1b7c3552bfe4a71a7c35fd15974a6ee02/980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java#L27)):*
> ```Java
> @OwnedBy(PL)
> public class EntityIdentifierValidator implements ConstraintValidator<EntityIdentifier, String> {
>   // Max Length : 64 characters
> ```

Shouldn't we update this comment?

**Review by shashank-harness — APPROVED** [review]
> Reviewed 3 of 12 files at r1, 6 of 8 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42120)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42120)* status: 3 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/42120#-NKq8uk964_e5RQGghpU:-NKqB8MW9X8Fv5CBMAWX:bfsah85) ([raw file](https://github.com/harness/harness-core/blob/168bbb64058bae9b28c1a0a4a306ae13fba8c4a6/980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java#L27)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Shouldn't we update this comment?
</blockquote></details>

Done @shashank-harness .

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42120)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java` line 151 at r3](https://reviewable.io/reviews/harness/harness-core/42120#-NKpge288CNqysYi8ACZ:-NKqHbrfBXHuJGFyKPFm:bnnyn5r) ([raw file](https://github.com/harness/harness-core/blob/9701757da159e5a014d17db9204fe861165708a2/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java#L151)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

The validation on EntityIdentifier Length gets invoked and so need to put maxLength.
</blockquote></details>

This would be extremely unmaintainable and error prone. How would devs know when to override maxLength. Also, there is a high chance devs would miss it. 


I think object validation should happen on the object and not on the parameters. Basically when object is being constructed.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42120)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java` line 151 at r3](https://reviewable.io/reviews/harness/harness-core/42120#-NKpge288CNqysYi8ACZ:-NKr9_Tr6PxGklBRPJ-d:baue89h) ([raw file](https://github.com/harness/harness-core/blob/9701757da159e5a014d17db9204fe861165708a2/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java#L151)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Removed. Done. @ankit-harness . In case of Connector, the validation endpoint is used Create Connector flow, even before actually creating connector. I think we will have revisit that flow to see if we can remove there.
cc @meenakshi-harness @nishantsaini20 
</blockquote></details>

As per our discussion offline-

I will approve the PR since we have committed it to the customer. But @jimit09gandhi will raise another PR to have a standard 128 character limit on all NG entities so that we can avoid this situation

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42120#-:-NKrAAcuCHplUxuEH2Sg:bnfp4nl)* status: 4 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42120#-:-NKrAR0V6nzjW4ygPSn7:bnfp4nl)* status: 4 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42120)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 12 files at r1, 6 of 8 files at r2, 1 of 1 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42120#-:-NKsVDtY7-UV3EnbuBrZ:bnfp4nl)* status: 1. unresolved discussions.

**Pull request merged**
