### PR TITLE
feat: [SRM-12421]: Change ELK to ElasticSearch in Backend

### PR DESCRIPTION
**Pull request by arpit-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38860)

### CODE REVIEW

**Comment by praveensugavanam** [comment]
*[`430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/MonitoredServiceDataSourceType.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/38860#-NEb5BbY3tm2xPri3hRN:-NEb5BbY3tm2xPri3hRO:bcpoqv7) ([raw file](https://github.com/harness/harness-core/blob/cfd3b66ab4c6aead543774067787a542753cc733/430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/MonitoredServiceDataSourceType.java#L28)):*
> ```Java
>   @JsonProperty("CustomHealthLog") CUSTOM_HEALTH_LOG,
>   @JsonProperty("SplunkMetric") SPLUNK_METRIC,
>   @JsonProperty("ElasticSearch") ELK_LOG,
> ```

Info comment: Do we not want to change the enum also ? 



_Code quote:_
```Java
ELK_LOG
```

**Review by praveensugavanam — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38860)* status: :shipit: complete! ✓

___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorType.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/38860#-NEb5PF8ByUsfG_TsvTB:-NEb5PF8ByUsfG_TsvTC:b-19mxfo) ([raw file](https://github.com/harness/harness-core/blob/cfd3b66ab4c6aead543774067787a542753cc733/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorType.java#L63)):*
> ```Java
>   @JsonProperty("OciHelmRepo") OCI_HELM_REPO("OciHelmRepo"),
>   @JsonProperty("CustomSecretManager") CUSTOM_SECRET_MANAGER("CustomSecretManager"),
>   @JsonProperty("ElasticSearch") ELK("ElasticSearch"),
> ```

Same here: Should we change the type as well ?

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38860)* status: :shipit: complete! ✓

**Comment by arpit-harness** [comment]
trigger codebasehash

**Pull request merged**
