### PR TITLE
[fix]: [CDS-76912]: Handle the UserMakredFailure in the InterruptEventHandler and giving a way to differente from abort

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes
Handle the UserMakredFailure properly in the InterruptEventHandler currently its treated same as Aborted and lead to incorrect state of execution.

Change: Created `Abortale::handleAbortAndUserMarkedFailure` and calling this instead of `handleAbort` from InterruptEventHandler when the interruptType is of ABORT or USER_MARKED_FAIL_ALL. This method takes one more parameter `interruptType` so each step can implement a different behaviour when the interrupt type is `USER_MARKED_FAIL_ALL`. The default implementation calls the handleAbort only so by default for each steps it will keep working as is. And if any step want to implement a different behaviour for `USER_MARKED_FAIL_ALL` then they can implement the `handleAbortAndUserMarkedFailure` method in the step

Impact: 

- AbortInterrupt: The default implementation of `handleAbortAndUserMarkedFailure` calls the handleAbort only. So i don't see any impact on Abort interrupt.
- USER_MARKED_FAIL_ALL interrupt: No change in default behaviour. But after this, any step can implement its behaviour different from handleAbort.

Testing: 

- Tested with wait step that if we don't override the `handleAbortAndUserMarkedFailure` method in the step then control comes into the handleAbort method. And if we override the method then the control does not come into handleAbort method rather comes into `handleAbortAndUserMarkedFailure` method.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]

**Review by sahilhindwani-harness — APPROVED** [review]

**Comment by brijeshdhakar** [comment]
trigger ut4

**Review by archit-harness — APPROVED** [review]

**Review by prashantsharma04 — APPROVED** [review]

**Pull request merged**
