### PR TITLE
Feat: [SRM-14070]: Add User Provider Class to fetch from User Principal

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
…y entity

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44515)

### CODE REVIEW

**Comment by naveen-harness** [comment]
Correct me if I'm wrong, since `Downtime` is extending `CreatedByAware`, `createdBy` field will change everytime `Downtime` is initiated. It's not necessary that the  `UserPrincipal` contains the user who created the Downtime.

**Review by dhruv-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44515)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/entities/Downtime.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/44515#-NPQczir8lZtWaQv-PwO:-NPQczir8lZtWaQv-PwP:b-br0iip) ([raw file](https://github.com/harness/harness-core/blob/129405cbdd40df28e7a0756445c1130bfa8e0900/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/entities/Downtime.java#L65)):*
> ```Java
> @OwnedBy(HarnessTeam.CV)
> public class Downtime
>     extends CreatedByAware implements PersistentEntity, UuidAware, UpdatedAtAware, CreatedAtAware, UpdatedByAware {
> ```

This should not be a class. All the entities which need this field will have to inherit this base-case, which is more of a behaviour. Lets convert this to a new interface and explore how we can extend the current save or upsert behaviour to support this new behaviour

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44515)* status: 5 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/UserPrincipalUserProvider.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/44515#-NPRViNb0LKvYxlm27Xc:-NPRViNb0LKvYxlm27Xd:bmi5i56) ([raw file](https://github.com/harness/harness-core/blob/4b0c132c0a318b520aee1597527fb02286415f21/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/UserPrincipalUserProvider.java#L18)):*
> ```Java
>   @Override
>   public EmbeddedUser activeUser() {
>     UserPrincipal userPrincipal = (UserPrincipal) SecurityContextBuilder.getPrincipal();
> ```

Add type check before type casting to UserPrincipal

**Review by dhruv-harness — COMMENTED** [review]
Please add/update UT for the createdBy changes

> Reviewed 3 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44515#-:-NPRX41F9Vux1AEEpRBA:b3vq99v)* status: 1 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/entities/Downtime.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/44515#-NPQczir8lZtWaQv-PwO:-NPRWPRdCoCYoa7eopDj:b-j5835o) ([raw file](https://github.com/harness/harness-core/blob/129405cbdd40df28e7a0756445c1130bfa8e0900/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/entities/Downtime.java#L65)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

This should not be a class. All the entities which need this field will have to inherit this base-case, which is more of a behaviour. Lets convert this to a new interface and explore how we can extend the current save or upsert behaviour to support this new behaviour
</blockquote></details>

Resolving after latest changes.

**Review by naveen-harness — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44515)* status: :shipit: complete! ✓

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44515)* status: :shipit: complete! ✓

**Review by dhruv-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44515)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 3 of 5 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44515)* status: :shipit: complete! ✓

**Pull request merged**
