### PR TITLE
feat: [CDS-83546]: Add IdentifierRef for pipeline to secret runtime usage event data

### PR DESCRIPTION
**Pull request by mani5h-harness**
## Describe your changes
feat: [CDS-83546]: Add IdentifierRef for pipeline to secret runtime usage event data

Context - We want to publish secret runtime usage for ng for parity with cg. UX mocks can be found at https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21404418556/Secrets+Runtime+Usage+in+NG

We are currently capturing refferedBy entity for runtime secret usage, which are Connectors for most CD steps. We also want to capture pipeline information. This PR adds identifier ref for Pipeline to the data published.

Verified that the details are being populated in entityActivity mongo collection on pipeline execution.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-83546]: https://harness.atlassian.net/browse/CDS-83546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55082)

### CODE REVIEW

**Comment by mani5h-harness** [comment]
trigger checkstyle

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55082#-:-Nicrq9jDJSGCIRdVcNm:bnfp4nl)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]

**Comment by mani5h-harness** [comment]
trigger uts

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55082)* status: 9 file(s) to review. 1. unresolved discussions. 

___
*[`970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pipeline_execution_usage_data.proto` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/55082#-Nidj8OQ4apQ9iEe-mUR:-Nidllw--4kn6JWkiZi_:b-q3988s) ([raw file](https://github.com/harness/harness-core/blob/6734b128814c9dbdbc54a39829c667737dd989a8/970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pipeline_execution_usage_data.proto#L19)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We have usageType already, can we not use that?
Also, why to have IdentifierRef, why not just have accoutnId, orgId, projectId and pipelineId
That way we will know what all info we are publishing?
</blockquote></details>

@mani5h-harness pls discuss with @tiwaritejas about this comment.

**Comment by mani5h-harness** [comment]
*[`970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pipeline_execution_usage_data.proto` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/55082#-Nidj8OQ4apQ9iEe-mUR:-Nidk7p60mPaw3oBuNIl:b-jdqgu8) ([raw file](https://github.com/harness/harness-core/blob/6734b128814c9dbdbc54a39829c667737dd989a8/970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pipeline_execution_usage_data.proto#L19)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

@mani5h-harness pls discuss with @tiwaritejas about this comment.
</blockquote></details>

UsageType referes to the runtime event/usecase where the secret was referenced. 
ie PIPELINE_EXECUTION, TEST_CONNECTION etc

yes, having accId, orgId, projId and pipelineId as separate fields is a possibility. 
But identifierRef is what Platform team expects from this event.

I will check for that decision with @tiwaritejas

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55082)* status: 9 file(s) to review. 1. unresolved discussions. 

___
*[`970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pipeline_execution_usage_data.proto` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/55082#-Nidj8OQ4apQ9iEe-mUR:-Nidq2qh8QtrlTIvirZR:b-sjqxcg) ([raw file](https://github.com/harness/harness-core/blob/6734b128814c9dbdbc54a39829c667737dd989a8/970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pipeline_execution_usage_data.proto#L19)):*
<details><summary><i>Previously, mani5h-harness wrote…</i></summary><blockquote>

UsageType referes to the runtime event/usecase where the secret was referenced. 
ie PIPELINE_EXECUTION, TEST_CONNECTION etc

yes, having accId, orgId, projId and pipelineId as separate fields is a possibility. 
But identifierRef is what Platform team expects from this event.

I will check for that decision with @tiwaritejas
</blockquote></details>

@sahilhindwani-harness UsageType has a many to one mapping with EntityType. An entity- PIPELINE can have multiple usageTypes like "Pipeline Execution", "Pipeline setup", etc. Hence, rather than maintaining this mapping on the UI to parse this info to understand that this is a pipeline usage, it is better to have the EntityType field. 
The combination of [EntityType + EntityRef] looks like a standard to communicate about Harness entities. Therefore, there are already existing UI components that can read these and construct navigation URLs given the entityType and the entityRef, which are used for setup usages, audits, etc. Hence, it is better to reuse the components in UI rather than having the scopeIdentifiers and pipeline identifier fields separately. Are there any downsides to having an EntityRef here?
cc: @nishantsaini20

**Comment by sahilhindwani-harness** [comment]
*[`970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pipeline_execution_usage_data.proto` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/55082#-Nidj8OQ4apQ9iEe-mUR:-NihomqbA6B5DgOcRbHR:b-t2eyzc) ([raw file](https://github.com/harness/harness-core/blob/6734b128814c9dbdbc54a39829c667737dd989a8/970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pipeline_execution_usage_data.proto#L19)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

@sahilhindwani-harness UsageType has a many to one mapping with EntityType. An entity- PIPELINE can have multiple usageTypes like "Pipeline Execution", "Pipeline setup", etc. Hence, rather than maintaining this mapping on the UI to parse this info to understand that this is a pipeline usage, it is better to have the EntityType field. 
The combination of [EntityType + EntityRef] looks like a standard to communicate about Harness entities. Therefore, there are already existing UI components that can read these and construct navigation URLs given the entityType and the entityRef, which are used for setup usages, audits, etc. Hence, it is better to reuse the components in UI rather than having the scopeIdentifiers and pipeline identifier fields separately. Are there any downsides to having an EntityRef here?
cc: @nishantsaini20
</blockquote></details>

@tiwaritejas , if identifier is expected for every usage type then I would recommend to move it in EntityUsageDetailProto rather than having it in PipelineExecutionUsageDataProto.
This will ensure that you have all this info for every UsageDataProtoDTO /

**Review by tchaurasiya — APPROVED** [review]

**Review by vtxorxwitty — APPROVED** [review]

**Comment by mani5h-harness** [comment]
*[`970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pipeline_execution_usage_data.proto` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/55082#-Nidj8OQ4apQ9iEe-mUR:-NinRRMW9dKoHxyP_0mN:bujw4ut) ([raw file](https://github.com/harness/harness-core/blob/6734b128814c9dbdbc54a39829c667737dd989a8/970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pipeline_execution_usage_data.proto#L19)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

@tiwaritejas , if identifier is expected for every usage type then I would recommend to move it in EntityUsageDetailProto rather than having it in PipelineExecutionUsageDataProto.
This will ensure that you have all this info for every UsageDataProtoDTO /
</blockquote></details>

Moved identifierRef inside EntityUsageDetailProto

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55082)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by mani5h-harness** [comment]
trigger uts

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55082#-:-Nio3kRwEnDOXIExsym-:bnfp4nl)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55082)* status: :shipit: complete! ✓

**Comment by mani5h-harness** [comment]
trigger uts

**Review by tchaurasiya — APPROVED** [review]

**Review by tiwaritejas — APPROVED** [review]

**Comment by mani5h-harness** [comment]
trigger uts

**Pull request merged**
