### PR TITLE
[fix]: [OPA-127]: increase managed-roles version

### PR DESCRIPTION
**Pull request by dwarren-dev**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31301)

### CODE REVIEW

**Comment by dwarren-dev** [comment]
trigger ti2

**Review by gupta-utkarsh — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31301#-:-My5pGIxCbU75tCcYlMm:bnfp4nl)* status: Some of the checks are too old.

**Comment by dwarren-dev** [comment]
trigger ti0

**Comment by dwarren-dev** [comment]
trigger ti3

**Comment by dwarren-dev** [comment]
tigger ti2

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31301#-:-My8b-J6C1CosZkTl9xo:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
