### PR TITLE
[feat]: [PIE-9437]: transforming plan and reusing old-plan for post-prod-rollback

### PR DESCRIPTION
**Pull request by brijeshdhakar**
…
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46601)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 499 at r1](https://reviewable.io/reviews/harness/harness-core/46601#-NTOOfHXAgj7aAlF6z2p:-NTOOfHXAgj7aAlF6z2q:bfo22tk) ([raw file](https://github.com/harness/harness-core/blob/9a89dda48b69484469725c8f5f947b35dc528a70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L499)):*
> ```Java
>       Plan plan;
>       try {
>         if (executionMetadata.getExecutionMode() == ExecutionMode.POST_EXECUTION_ROLLBACK) {
> ```

Please add UT for this.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/test/java/io/harness/pms/plan/execution/RollbackModeExecutionHelperTest.java` line 296 at r1](https://reviewable.io/reviews/harness/harness-core/46601#-NTOOkg_Bm_hxSABUohg:-NTOOkg_Bm_hxSABUohh:b-czfbwp) ([raw file](https://github.com/harness/harness-core/blob/9a89dda48b69484469725c8f5f947b35dc528a70/pipeline-service/service/src/test/java/io/harness/pms/plan/execution/RollbackModeExecutionHelperTest.java#L296)):*
> ```Java
> 
>     Plan transformedPlan = rollbackModeExecutionHelper.transformPlanForRollbackMode(
>         createdPlan, prevExecId, Collections.singletonList("uuid2"), POST_EXECUTION_ROLLBACK, null);
> ```

Add one more UT with this value as not null

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46601)* status: 11 file(s) to review. 0 of 2 approvals obtained.

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46601)* status: 11 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 499 at r1](https://reviewable.io/reviews/harness/harness-core/46601#-NTOOfHXAgj7aAlF6z2p:-NTO_cfaBNiQeWe8HCYy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9a89dda48b69484469725c8f5f947b35dc528a70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L499)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Please add UT for this.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/test/java/io/harness/pms/plan/execution/RollbackModeExecutionHelperTest.java` line 296 at r1](https://reviewable.io/reviews/harness/harness-core/46601#-NTOOkg_Bm_hxSABUohg:-NTO_dh27xMV7uKdnuU3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9a89dda48b69484469725c8f5f947b35dc528a70/pipeline-service/service/src/test/java/io/harness/pms/plan/execution/RollbackModeExecutionHelperTest.java#L296)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Add one more UT with this value as not null
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46601)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46601)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by namanvermah — APPROVED** [review]
> Reviewed 8 of 11 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46601)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger review

**Pull request merged**
