### PR TITLE
fix: [CDS-46900]: Testing using no auth provider.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
We will go with the option of autodetecting if a plugin is installed on delegate or not. If it is then we will use plugin based authentication otherwise will fallback to auth provider. This means that users will be the one who will have to install it on delegate and all responsibilities of updating and vulnerabilities is on user back. If customer is not using kubectl 1.26 and above, then installing plugins will be optional for them, in other case it will be mandatory.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41231)

### CODE REVIEW

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 609 at r2](https://reviewable.io/reviews/harness/harness-core/41231#-NJKqRPrCEX2q_lHbukw:-NJKqRPs4l2Z6ObLMhVy:bojp6v4) ([raw file](https://github.com/harness/harness-core/blob/93cd64e024b664ae1cb113bd717ba2a17594c9ab/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L609)):*
> ```Java
> 
>     if (azureKubeConfig.getUsers().get(0).getUser().getAuthProvider() != null) {
>       if (isEmpty(azureKubeConfig.getClusters().get(0).getName())) {
> ```

Why is this check removed?

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 884 at r2](https://reviewable.io/reviews/harness/harness-core/41231#-NJKqbP55PVsqqNIUgeX:-NJKqbP55PVsqqNIUgeY:bekw7mf) ([raw file](https://github.com/harness/harness-core/blob/2d76d3e11ae68da3643c62fae4433fc20a91b1a0/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L884)):*
> ```Java
>   }
> 
>   private void azClusterLogin(AzureConfig azureConfig) {
> ```

Usage of AZ cli (or any other cli command) should be done like it is done for kubectl (960-api-services/src/main/java/io/harness/k8s/kubectl/Kubectl.java)

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/test/resources/azure/userKubeConfigExecFormatContent.yaml` line 1 at r2](https://reviewable.io/reviews/harness/harness-core/41231#-NJKrDFWCLjdq876SqLO:-NJKrDFWCLjdq876SqLP:b-jndvbp) ([raw file](https://github.com/harness/harness-core/blob/2d76d3e11ae68da3643c62fae4433fc20a91b1a0/930-delegate-tasks/src/test/resources/azure/userKubeConfigExecFormatContent.yaml#L1)):*
> ```YAML
> YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VVMlJFTkRRWFJEWjBGM1NVSkJaMGxSVVU0NWNsZHFhR1ZwVEZKUmVYcFdSVkZZVVM5amFrRk9RbWRyY1docmFVYzVkekJDUVZGelJrRkVRVTRLVFZGemQwTlJXVVJXVVZGRVJYZEthbGxVUVdkR2R6QjVUV3BCTVUxVVozaE9WRVUwVFVSQ1lVZEJPSGxOUkZWNVRVUlZlRTlFUlRGTmFtZDNUVVp2ZHdwRVZFVk1UVUZyUjBFeFZVVkJlRTFEV1RKRmQyZG5TV2xOUVRCSFExTnhSMU5KWWpORVVVVkNRVkZWUVVFMFNVTkVkMEYzWjJkSlMwRnZTVU5CVVVOckNtZEtTRmhRWWxWMU0xcFpTMUpqZGk5M2NXVnNVR29yZG05RlkySTRNVEUwTTFwbldFeFNlbVpYTTFGa1ZFVlZURU5CYkRFd2IyOURUeXRaYVRKUkt5OEtRalZUTjNwMU5HOU9TakZSYlZSR2RFdEJkVzB4VUhKcE5XYzVMMDAzYWxad1lUVkxkazFoWjJwTWRVZHhWRzlRYW5aa1F6WlNaRkYwVVZwaWFtSTBXQW94WkM5S05FdGtZWFUyWms1MWIyTm1WMFpLTUV4VU1uSm9jWHBWWlZrNE9EaFhlWFpGZVRJNU9HUndaREZUS3pSTE1HTkJVVGR2V1ZoR2QyZG9iMWg2Q2pGS2VuUXZhVTVyTUZSbVJWTkZUelpxTm10Q1praDNTSGxPUW5CTkswUjFVWFpHYW1kMGJtWldWMkZZWms5d1ZWVkNaRE00V0dveU9UQTRaMnRuUVVZS0wxRnhlV296V0hSWFYwRXhXRlE0UzJWalpGQm1OMGhGSzJSUU1YbEhlWEpKT1dsc2RqSkZWVFpNYkV0V09GUnFkMEZ6UTNodlRVMWFOV3RRS3pKaFVBcEZjVWxaYlZkQlpXaEtWalJ0YjFGWGVXZGtaR0o2TjFjeVpWTnhVbXBvU2tsRU5VTnhSak1yYnpBMk0xUjNWMnhVVnpGQmRYQlZSMEpKU0hWV2EydE9Da2R1YmtKVVRtTkJNbWs1VkZwaVkxVkVlbk16UW5wTU4zTkVhbVozYkRGT1MxaFVMMmNyYVRRellrRm5Sa3N3ZDNKb1RtWXpiMHBoYlZkVlNVOXVWV2NLTmpkNU5FOWlObTExSzBwbmIwUTJiVU5GUjNGQ1RYVmpha3BQYVZkNVNHWkJNREJtWlc1aE9ERldLMlo0Y0d3MlJXTlZTVzlOWm1NMk1tWTJTMUpCYXdwaVJHOXFLMjl5Y0VGNVdtMVNkbVJSVnpSUE5EVlZjM1ZyTldzMWR5dFRUR05CUW5JM2JrRnRjMkpPWVU4NVdFUnVlR1pXYUVoVFUySlhlVFZHVTFVMkNucFFha0pJUlhSU1ZFa3hWRVpZWW5wNk1WWmphMUZKVUhkMVpISlRMekY0TjFJMFpHZDFNRzVPT0Rsd2NWZDRWSEpCUm5wRFJGUXlkR3BXZDJKM09HWUtRV296WjFkSlRTOXdiblJQYlM5M2NVZFFNRXhXVFhNMmQyMWpVbUYzVGtsa2JYSTNkbGRyVkVKUlNVUkJVVUZDYnpCSmQxRkVRVTlDWjA1V1NGRTRRZ3BCWmpoRlFrRk5RMEZ4VVhkRWQxbEVWbEl3VkVGUlNDOUNRVlYzUVhkRlFpOTZRV1JDWjA1V1NGRTBSVVpuVVZWRlZGSTFlRmRxVmpJNGFrWkNZVlkwQ2paTldteHBSRzlQZVVVMGQwUlJXVXBMYjFwSmFIWmpUa0ZSUlV4Q1VVRkVaMmRKUWtGSVZHWlJWMHcyTVVGVVZrTlRNMFo1YTJoRllrbEVhVmt5WTJVS1MyTXpiSGRsWW1WT2JXOVBSMU5ZUkVGcWNYVjNaelJsVTNCdFl5OU9Ra0pxV0VoMWNHWnZNamN6Yms1TloyUmxhR0V5TWtOS2IxSndiWHBRTm1OSmJncFFSVm94Y1VzeWNuaGpaRlJ1VldoWmVuQTNlRWhSVTNoRllXMWFTMnRyYVZaTFZHNWFSSGw1WjFSRU1WcFBUaTl2YTJ0WWJFRTROSFF5VkdGR1RrVnBDbHBNZEdjek0yUlFiMFF2YVVNNFoybGlXRGh2T1ZNeVJ6SnpPRFJ6TUU5NE4zcHFNRFpLU0hWT1pXNXdkV1psZEdSUFNFZDJPV1l2UkVWWFEzQlFNRGNLTXpaSGFDdFNRVVozVEU0MFpVMVpNeTlKV1hKRE5GSnZVVGxDZFRsUmVFVnVabEpuZG1OSlMwUTViSEF2T0VSVFZWUjJaMWhZWWpCVFpGVjRhVXhwY2dwWVRXOVZUR1ppWjNkQk5tWk5MMWt2THpGUlJ5dFVlRVJyVGpZNFZWbEJSVkU0Y0dVd1pqVTVPRVU0UTBNeVpXaDVOVTVNUm5aSFRHNU1ja2h0VlVWb0NqVnRUbEYwUW1WYU5XUmpiRkZOWWt0VWVuVk9VVXBaV1hWNldVdHNUbkZDU0dJd1J6ZHBWemRzZGt4b01IbEhOWHB5VlhSQmFsSkdjVkZXUWxsaWNUY0tkSEpWVERSdU5qRm1Oek52WWxCcWRETXpXbTFOUjBSRFExcHlUMVpKYjNsNGFDOVdjRVJtV1VSWlpVMXRUR3c0YTJSV2MwaHFNR2h6VkVSb09YVnBPQXAwZG1zd1YwZ3hZa05CT1RsemVYWlNkR3B2WTNjNE5VVk1URTlSTUc4M1pDdG9TRTlGUTNka1ZFaFZWMGxvWmsxelNVVkVOelZPVVhoU2FtSjNObXAyQ25kNVVISnhNMVI2U25KWVZWVnBiWEpCU1VoNU4zQnJZek1yVmxwbk1DdHNjSEZpVEN0RU9YUnhRMmRXY1daTmVVRldla3gwVG05NE5tOWFTMncxTDJJS1FWUXlkRlZVUmsxNGNtazRiVEZLU1hObFZEY3ZlVloxV1ZKQ1dIaHJSVEZpYlU1Tk9DdGtMMGdyVEhkalVYaG5NVnBsY0VoRVZtTTVkR1JVZUhodlJBb3pXbGxzT1ZZcmMzWXlaV3d3ZG1WakNpMHRMUzB0UlU1RUlFTkZVbFJKUmtsRFFWUkZMUzB0TFMwRgogICAgc2VydmVyOiBodHRwczovL2NkcC1henVyZS10ZXN0LWFrcy1kbnMtYmFhNGJiZGMuaGNwLmVhc3R1cy5hem1rOHMuaW86NDQzCiAgbmFtZTogY2RwLWF6dXJlLXRlc3QtYWtzCmNvbnRleHRzOgotIGNvbnRleHQ6CiAgICBjbHVzdGVyOiBjZHAtYXp1cmUtdGVzdC1ha3MKICAgIHVzZXI6IGNsdXN0ZXJVc2VyX2NkcC10ZXN0LXJnX2NkcC1henVyZS10ZXN0LWFrcwogIG5hbWU6IGNkcC1henVyZS10ZXN0LWFrcwpjdXJyZW50LWNvbnRleHQ6IGNkcC1henVyZS10ZXN0LWFrcwpraW5kOiBDb25maWcKcHJlZmVyZW5jZXM6IHt9CnVzZXJzOgotIG5hbWU6IGNsdXN0ZXJVc2VyX2NkcC10ZXN0LXJnX2NkcC1henVyZS10ZXN0LWFrcwogIHVzZXI6CiAgICBleGVjOgogICAgICBhcGlWZXJzaW9uOiBjbGllbnQuYXV0aGVudGljYXRpb24uazhzLmlvL3YxYmV0YTEKICAgICAgYXJnczoKICAgICAgICAtIC0tc2VydmVyLWlkCiAgICAgICAgLSA2ZGFlNDJmOC00MzY4LTQ2NzgtOTRmZi0zOTYwZTI4ZTM2MzAKICAgICAgICAtIC0tY2xpZW50LWlkCiAgICAgICAgLSA4MGZhZjkyMC0xOTA4LTRiNTItYjVlZi1hOGU3YmVkZmM2N2EKICAgICAgICAtIC0tZW52aXJvbm1lbnQKICAgICAgICAtIEF6dXJlUHVibGljQ2xvdWQKICAgICAgICAtIC0tdGVuYW50LWlkCiAgICAgICAgLSBiMjI5YjJiYi01ZjMzLTRkMjItYmNlMC03MzBmNjQ3NGU5MDYKICAgICAgY29tbWFuZDogdHJ1ZQogICAgICBlbnY6IG51bGwKICAgICAgaW50ZXJhY3RpdmVNb2RlOiBOZXZlcgogICAgICBwcm92aWRlQ2x1c3RlckluZm86IGZhbHNlCg==
> ```

Make sure that this is not a correct Kubeconfig! Make the data invalid.

**Review by markoharness — COMMENTED** [review]
> Reviewed 3 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41231)* status: 14 file(s) to review. 0 of 2 approvals obtained.

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41231)* status: 21 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 609 at r2](https://reviewable.io/reviews/harness/harness-core/41231#-NJKqRPrCEX2q_lHbukw:-NK8f-VL9saTyF58Pa1t:b-g9kwg8) ([raw file](https://github.com/harness/harness-core/blob/93cd64e024b664ae1cb113bd717ba2a17594c9ab/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L609)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

Why is this check removed?
</blockquote></details>

I had moved it outside of the "if statement" as I thought Admin cluster config would also have user. I have moved it back to the if statement.
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 884 at r2](https://reviewable.io/reviews/harness/harness-core/41231#-NJKqbP55PVsqqNIUgeX:-NK8fGxk48mOvLBbfKFY:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/2d76d3e11ae68da3643c62fae4433fc20a91b1a0/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L884)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

Usage of AZ cli (or any other cli command) should be done like it is done for kubectl (960-api-services/src/main/java/io/harness/k8s/kubectl/Kubectl.java)
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/test/resources/azure/userKubeConfigExecFormatContent.yaml` line 1 at r2](https://reviewable.io/reviews/harness/harness-core/41231#-NJKrDFWCLjdq876SqLO:-NK8fJDSEvB-44IPi_l3:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/2d76d3e11ae68da3643c62fae4433fc20a91b1a0/930-delegate-tasks/src/test/resources/azure/userKubeConfigExecFormatContent.yaml#L1)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

Make sure that this is not a correct Kubeconfig! Make the data invalid.
</blockquote></details>

Done

**Review by abosii-harness — CHANGES_REQUESTED** [review]
Some general feedback:
1. Please take care of the sonar issue and mark the ones that are not applicable, but prioritize the one that you can fix
2. Would it be possible to move out everything related to kubeconfig generation in a different class?
3. Can we integrate the log callback into this logic? It would be really helpful if we can give some feedback for the customer and reduce the count of questions on our end. The more important would be:
 - Logs related to that the kublogin is not installed and we will use azure auth provider instead. We can later enhance with the doc link
 - Logs related to that the kubelogin is installed but az cli is not so we will still fallback to azure auth provider

> Reviewed 2 of 14 files at r1, 4 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41231#-:-NKCU_m34Vq4H8ykYre-:bhjhymg)* status: 20 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 892 at r4](https://reviewable.io/reviews/harness/harness-core/41231#-NKCYOZq5HH8mmRgotCZ:-NKCYOZq5HH8mmRgotC_:b-mbssxj) ([raw file](https://github.com/harness/harness-core/blob/9a89482fefa08af242d990df7bd7d2f531ee01e6/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L892)):*
> ```Java
>     String loginCommand = AzureCliCommandToLogin(azureConfig);
>     if (isNotEmpty(loginCommand)) {
>       runCommand(loginCommand);
> ```

This logic doesn't look to me to be safe to use. Few questions need to be answered first:
- How exactly azure keep track of the login result? Is it updating a file, keeping it in the env variables? 
- How azure is referencing login of az login result in kubelogin? 
- What will happen if 2 tasks are doing az login at the same time?
- What will happen if 2 tasks are doing az login but with different cert key?
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 896 at r4](https://reviewable.io/reviews/harness/harness-core/41231#-NKCOt3E9NJeDufseme2:-NKCOt3G4IucjBy6KijJ:b-yom7zz) ([raw file](https://github.com/harness/harness-core/blob/9a89482fefa08af242d990df7bd7d2f531ee01e6/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L896)):*
> ```Java
>   }
> 
>   private String AzureCliCommandToLogin(AzureConfig azureConfig) {
> ```

Name of the method should be camel case
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 919 at r4](https://reviewable.io/reviews/harness/harness-core/41231#-NKCPKLnDuCfBuNJhX4t:-NKCPKLnDuCfBuNJhX4u:bt4zxyd) ([raw file](https://github.com/harness/harness-core/blob/9a89482fefa08af242d990df7bd7d2f531ee01e6/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L919)):*
> ```Java
>   private boolean isKubeloginInstalled(AzureAuthenticationType azureAuthenticationType) {
>     String AZ_VERSION = Az.client(AZ_PATH).version().command();
>     return azureAuthenticationType.equals(AzureAuthenticationType.SERVICE_PRINCIPAL_CERT)
> ```

This is an enum, we should use AzureAuthenticationType.SERVICE_PRINCIPAL_CERT == azureAuthenticationType, where puting const value first for better readability and use == since equals is not null safe 
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 936 at r4](https://reviewable.io/reviews/harness/harness-core/41231#-NKC_wEZ2CSW83Mz9Yra:-NKC_wEZ2CSW83Mz9Yrb:bgkrrif) ([raw file](https://github.com/harness/harness-core/blob/9a89482fefa08af242d990df7bd7d2f531ee01e6/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L936)):*
> ```Java
>       throws IOException, InterruptedException, TimeoutException {
>     final ProcessExecutor processExecutor = new ProcessExecutor()
>                                                 .timeout(TIMEOUTINMINUTES, TimeUnit.MINUTES)
> ```

Can we afford minutes here? Any reasons why this timeout was chosen?
___
*[`970-api-services-beans/src/main/java/io/harness/azure/model/AzureConstants.java` line 407 at r4](https://reviewable.io/reviews/harness/harness-core/41231#-NKCa_I0DOAKKxzQyWRa:-NKCa_I0DOAKKxzQyWRb:b-yk1vf7) ([raw file](https://github.com/harness/harness-core/blob/9a89482fefa08af242d990df7bd7d2f531ee01e6/970-api-services-beans/src/main/java/io/harness/azure/model/AzureConstants.java#L407)):*
> ```Java
>   String KUBELOGIN_BINARY_PATH = "kubelogin";
>   String AZ_PATH = "az";
>   int TIMEOUTINMINUTES = 2;
> ```

please use TIMEOUT_IN_MINUTES

**Pull request closed without merging**
