### PR TITLE
techdebt: [SPG-438]: Terraform Telemetry Filter

### PR DESCRIPTION
**Pull request by rijajoo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38922)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38922)* status: 5 file(s) to review. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 570 at r1](https://reviewable.io/reviews/harness/harness-core/38922#-NEfwfj0BhxeEGSIco-l:-NEfwfj0BhxeEGSIco-m:bfzi5yn) ([raw file](https://github.com/harness/harness-core/blob/c9bdb86f42b53bd4acc98a8fa5f710b739526a01/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L570)):*
> ```Java
>   private void registerTerraformTelemetryFilter(Environment environment, Injector injector) {
>     TelemetryReporter telemetryReporter = injector.getInstance(TelemetryReporter.class);
>     environment.jersey().register(new TerraformTelemetryFilter(telemetryReporter));
> ```

why do we need terraform filter in pipeline service? is it we want to do rate limit for executions run via terraform?

**Comment by rijajoo** [comment]
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 570 at r1](https://reviewable.io/reviews/harness/harness-core/38922#-NEfwfj0BhxeEGSIco-l:-NEiNir0DoAORjERqUp5:b-82negd) ([raw file](https://github.com/harness/harness-core/blob/c9bdb86f42b53bd4acc98a8fa5f710b739526a01/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L570)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do we need terraform filter in pipeline service? is it we want to do rate limit for executions run via terraform?
</blockquote></details>

We are adding a filter to get the telemetry of the APIs that are called via Terraform to understand the Terraform usage of the customers. We need to add it in all the services having APIs being consumed via Terraform. The rate limiter has nothing to do with the APIs, it is just to rate limit the Telemetry from being sent for every request.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38922)* status: 4 file(s) to review.

**Review by reetika04 — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38922)* status: :shipit: complete! ✓

**Pull request merged**
