### PR TITLE
feat: [CDS-86397]: Metadata handling for class fields in inputs-schema api

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Metadata handling for class fields in inputs-schema api

Tested handling metadata for class fields example - timeout field, looping_strategy fields

For this yaml - 
```
version: 1
kind: pipeline
spec:
  inputs:
    timeout:
      type: string
      description: timeout of shell script step
      required: true
      default: 10s
    script:
      type: string
    jenkinsJobName:
      type: string
    jenkinsConnector:
      type: string
    conditional_input:
      type: object
      required: true
    failure_strategy:
      type: object
      required: true
  stages:
    - type: custom
      name: s1
      spec:
        steps:
          - name: JenkinsStep
            type: JenkinsBuild
            spec:
              connectorRef: <+inputs.jenkinsConnector>
              jobName: <+inputs.jenkinsJobName>
            identifier: JenkinsStep
            description: asdsa
            when:
              stageStatus: Success
            timeout: <+inputs.timeout>
            id: JenkinsStep_NieO
          - name: httpStep
            type: http
            spec:
              method: GET
              url: <+inputs.script>
            id: httpStep
            timeout: <+inputs.timeout>
            when: <+inputs.conditional_input>
          - name: my-shell
            type: shell-script
            spec:
              shell: bash
              on_delegate: true
              source:
                type: inline
                spec:
                  script: <+inputs.script>
            description: Updated from form
            id: myshell_eR0O
            timeout: <+inputs.timeout>
      id: s1_CzOU
```

we are getting output as - 
```
{
    "inputs": [
        {
            "details": {
                "name": "timeout",
                "type": "string",
                "description": null,
                "required": true,
                "execution": false,
                "allowed_values": null,
                "regex": null,
                "default": "10s"
            },
            "metadata": {
                "field_properties": [
                    {
                        "input_type": "string",
                        "internal_type": "duration"
                    }
                ],
                "dependencies": {
                    "required_runtime_inputs": [],
                    "required_fixed_values": []
                }
            }
        },
        {
            "details": {
                "name": "script",
                "type": "string",
                "description": null,
                "required": false,
                "execution": false,
                "allowed_values": null,
                "regex": null,
                "default": null
            },
            "metadata": {
                "field_properties": [],
                "dependencies": {
                    "required_runtime_inputs": [],
                    "required_fixed_values": []
                }
            }
        },
        {
            "details": {
                "name": "url",
                "type": "string",
                "description": null,
                "required": false,
                "execution": false,
                "allowed_values": null,
                "regex": null,
                "default": null
            },
            "metadata": {
                "field_properties": [
                    {
                        "input_type": "string",
                        "internal_type": "url"
                    }
                ],
                "dependencies": {
                    "required_runtime_inputs": [],
                    "required_fixed_values": []
                }
            }
        },
        {
            "details": {
                "name": "jenkinsJobName",
                "type": "string",
                "description": null,
                "required": false,
                "execution": false,
                "allowed_values": null,
                "regex": null,
                "default": null
            },
            "metadata": {
                "field_properties": [
                    {
                        "input_type": "string",
                        "internal_type": "jenkins_job_name"
                    }
                ],
                "dependencies": {
                    "required_runtime_inputs": [
                        {
                            "field_name": "connectorRef",
                            "input_name": "jenkinsConnector"
                        }
                    ],
                    "required_fixed_values": []
                }
            }
        },
        {
            "details": {
                "name": "jenkinsConnector",
                "type": "string",
                "description": null,
                "required": false,
                "execution": false,
                "allowed_values": null,
                "regex": null,
                "default": null
            },
            "metadata": {
                "field_properties": [
                    {
                        "input_type": "string",
                        "internal_type": "jenkins_connector"
                    }
                ],
                "dependencies": {
                    "required_runtime_inputs": [],
                    "required_fixed_values": []
                }
            }
        },
        {
            "details": {
                "name": "conditional_input",
                "type": "object",
                "description": null,
                "required": true,
                "execution": false,
                "allowed_values": null,
                "regex": null,
                "default": null
            },
            "metadata": {
                "field_properties": [],
                "dependencies": {
                    "required_runtime_inputs": [],
                    "required_fixed_values": []
                }
            }
        },
        {
            "details": {
                "name": "failure_strategy",
                "type": "object",
                "description": null,
                "required": true,
                "execution": false,
                "allowed_values": null,
                "regex": null,
                "default": null
            },
            "metadata": {
                "field_properties": [],
                "dependencies": null
            }
        }
    ]
}
```

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56488)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by brijeshdhakar** [comment]
*[`953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/InputsSchemaServiceImpl.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/56488#-Nl7d-rU6vVfIO6NEjBR:-Nl7d-rU6vVfIO6NEjBS:b-u2mbvq) ([raw file](https://github.com/harness/harness-core/blob/bce45ded3883736d19b8fa35393510d12945fbc3/953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/InputsSchemaServiceImpl.java#L86)):*
> ```Java
>             }
>           }
>           if (metadataSchemaNode != null) {
> ```

Move this before `if (inputFieldSchemaNode.has(YAMLFieldNameConstants.DOLLAR_REF))` and use if-else and not 2 ifs. If metadata is present at the field then we should not check for metadata at class level. cc: @archit-harness 



_Code quote:_
```Java
f (metadataSchemaNode != null)
```

**Comment by brijeshdhakar** [comment]
*[`953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/InputsSchemaServiceImpl.java` line 78 at r2](https://reviewable.io/reviews/harness/harness-core/56488#-Nl7dVUT8OoNFYqwxmJx:-Nl7dVUT8OoNFYqwxmJy:bbbp6kg) ([raw file](https://github.com/harness/harness-core/blob/bce45ded3883736d19b8fa35393510d12945fbc3/953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/InputsSchemaServiceImpl.java#L78)):*
> ```Java
>           if (inputFieldSchemaNode.has(YAMLFieldNameConstants.DOLLAR_REF)) {
>             JsonNode rootSchema = schemaParser.getRootSchemaJsonNode();
>             JsonNode metadataRef = JsonNodeUtils.goToPath(
> ```

nit: lets call it referencedNode and not metadataRef because its not ref but referenced node.(Ref is TestNode).



_Code quote:_
```Java
metadataRef
```

**Comment by brijeshdhakar** [comment]
*[`template-service/service/src/main/java/io/harness/yaml/individualschema/BaseTemplateSchemaParser.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/56488#-Nl7fFmo1oF1Qo6E0DMz:-Nl7fFmo1oF1Qo6E0DN-:bj8blc6) ([raw file](https://github.com/harness/harness-core/blob/bce45ded3883736d19b8fa35393510d12945fbc3/template-service/service/src/main/java/io/harness/yaml/individualschema/BaseTemplateSchemaParser.java#L59)):*
> ```Java
>   public JsonNode getRootSchemaJsonNode() {
>     return rootSchemaJsonNode;
>   }
> ```

same as above

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Pull request merged**
