### PR TITLE
[feat]:[pie-7340]: move configs impl in pipeline service

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added code implementation for moving the pipeline config from remote to inline and inline to remote

Impact -> Ease of moving configs

Tests covered:
1. Moved the configs inline to remote [default branch]
2. Moved the configs remote to inline [default branch]
3. Moved configs inline to remote [non default branch] and loaded the pipeline to check load from fallback branch
4. Moved configs remote to inline [non default branch]

ReleaseNotes summary needed? No

Is it new task type? No
Did you make changes to the code in a backward-compatible manner? Yes
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? Yes
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? Yes
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No change
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? Yes
if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? Yes
Did you remove an enum → No
Did you add an enum(That too at end of list) → No
FeatureFlag Added/Removed -> No
Verify Changes with affects any -> No

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42135)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/MoveConfigOperationDTO.java` line 25 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKqyLwR6OzvF32NnciL:-NKqyLwS5Fg_6s3tIjIV:b-hi6um) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/MoveConfigOperationDTO.java#L25)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> @JsonInclude(JsonInclude.Include.NON_NULL)
> @Schema(name = "MoveConfigOperationDTO", description = "This contains move config request information")
> ```

not a resource layer dto, so please remove swagger annotation from here

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 495 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKqypy2-Dcby7Yfa4eF:-NKqypy2-Dcby7Yfa4eG:bfduqzu) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L495)):*
> ```Java
>       String projectIdentifier, String pipelineIdentifier, MoveConfigRequestDTO moveConfigRequestDTO) {
>     if (!pipelineIdentifier.equals(moveConfigRequestDTO.getPipelineIdentifier())) {
>       throw new InvalidRequestException("PipelineIdentifiers given in path param and request body don't match.");
> ```

space typo in PipelineIdentifiers

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 514 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKqzT6hAPJqjrub1FQb:-NKqzT6hAPJqjrub1FQc:bfk5sjt) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L514)):*
> ```Java
>   }
> 
>   private MoveConfigOperationType getMoveConfigType(
> ```

move this mapper inside enum itself or a separate mapper

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 136 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKqzbmFE5TREYurSN9S:-NKqzbmG1-vtkvdi0ptR:b-wav3qa) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L136)):*
> ```Java
>   PMSPipelineListRepoResponse getListOfRepos(String accountIdentifier, String orgIdentifier, String projectIdentifier);
> 
>   PipelineCRUDResult moveConfigs(String accountIdentifier, String orgIdentifier, String projectIdentifier,
> ```

move config*

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 724 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKr-IY1ApvOSA4QjwEc:-NKr-IY1ApvOSA4QjwEd:b-wav3qa) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L724)):*
> ```Java
> 
>   @Override
>   public PipelineCRUDResult moveConfigs(String accountIdentifier, String orgIdentifier, String projectIdentifier,
> ```

move config*

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 749 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKr0uReD4hm4x9OdUsg:-NKr0uReD4hm4x9OdUsh:b-tqcv0f) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L749)):*
> ```Java
>     if (INLINE_TO_REMOTE.equals(moveConfigDTO.getMoveConfigOperationType())) {
>       String repoUrl = pmsPipelineRepository.getRepoUrl(accountIdentifier, orgIdentifier, projectIdentifier);
>       pipeline.setRepoURL(repoUrl);
> ```

This is a no-op operation, please remove it

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 757 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKr2E-L6akM9EVxR1JL:-NKr2E-MEqG9sf-Myecu:b-qdjpis) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L757)):*
> ```Java
>     } else if (REMOTE_TO_INLINE.equals(moveConfigDTO.getMoveConfigOperationType())) {
>       pipelineUpdate = PMSPipelineServiceHelper.getPipelineUpdateForRemoteToInline();
>       metadataUpdate = metadataUpdate.set(PipelineMetadataV2.PipelineMetadataV2Keys.branch, DEFAULT);
> ```

we just need to unset this field totally.



_Code quote:_
```Java
PipelineMetadataV2.PipelineMetadataV2Keys.branch, DEFAULT);
```

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 759 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKr2MB5BkAZ40iiqFNR:-NKr2MB5BkAZ40iiqFNS:bg4k4yz) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L759)):*
> ```Java
>       metadataUpdate = metadataUpdate.set(PipelineMetadataV2.PipelineMetadataV2Keys.branch, DEFAULT);
>     } else {
>       throw new InvalidRequestException("Invalid move config operation specified.");
> ```

append invalid operation name as well in the message, also log the error

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 496 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKr2s9N7B8R7TrFwFqY:-NKr2s9N7B8R7TrFwFqZ:b-uxqtnd) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L496)):*
> ```Java
> 
>   @Override
>   public String getRepoUrl(String accountIdentifier, String orgIdentifier, String projectIdentifier) {
> ```

this method doesn't belong here as it doesn't do anything with repository

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 476 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKr3tYE7jmEfk58KHjH:-NKr3tYE7jmEfk58KHjI:b-iaw7yj) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L476)):*
> ```Java
> 
>   @VisibleForTesting
>   PipelineEntity updatePipelineOperations(PipelineEntity pipelineToMove, Update pipelineUpdate,
> ```

method name can be made a bit specific to the use-case here as its not generic enough use-case being served

**Review by mohitg0795 — COMMENTED** [review]
> Reviewed 2 of 10 files at r1, 1 of 4 files at r2, 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42135)* status: 9 file(s) to review. 0 of 1 approvals obtained.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42135)* status: 11 file(s) to review. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/MoveConfigOperationDTO.java` line 25 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKqyLwR6OzvF32NnciL:-NKr4jGi6k3yR2HaT5wD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/MoveConfigOperationDTO.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

not a resource layer dto, so please remove swagger annotation from here
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 495 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKqypy2-Dcby7Yfa4eF:-NKr4mrw35XmhybilrZt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L495)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

space typo in PipelineIdentifiers
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 514 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKqzT6hAPJqjrub1FQb:-NKr5B521cDTCfMnxh-l:b-1udt74) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L514)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

move this mapper inside enum itself or a separate mapper
</blockquote></details>

Done. moved it enum
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 136 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKqzbmFE5TREYurSN9S:-NKr5EtE5hpxzxcTqpFE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L136)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

move config*
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 724 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKr-IY1ApvOSA4QjwEc:-NKr5Hzw6vaiURZdKEDp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L724)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

move config*
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 749 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKr0uReD4hm4x9OdUsg:-NKr5J6p4SESCjK3QFWU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L749)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This is a no-op operation, please remove it
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 757 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKr2E-L6akM9EVxR1JL:-NKr5L7y2Yh05XBXSCZy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L757)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we just need to unset this field totally.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 759 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKr2MB5BkAZ40iiqFNR:-NKr5M94APTxQUX2Gemv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L759)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

append invalid operation name as well in the message, also log the error
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 476 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKr3tYE7jmEfk58KHjH:-NKr6GenD1QG3bheT7BC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L476)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

method name can be made a bit specific to the use-case here as its not generic enough use-case being served
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 496 at r6](https://reviewable.io/reviews/harness/harness-core/42135#-NKr2s9N7B8R7TrFwFqY:-NKr5g3pB3rrEjNN7AvG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f714fa6d628077bc64280c5dde7e634ca29830b0/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L496)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this method doesn't belong here as it doesn't do anything with repository
</blockquote></details>

Done.

**Comment by adivishy1** [comment]
trigger buildnum, ss, checkstylecodeformat

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 1 of 10 files at r1, 1 of 2 files at r6, 8 of 9 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42135)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 2 of 10 files at r1, 1 of 4 files at r2, 1 of 2 files at r6, 8 of 9 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42135)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42135#-:-NKrSABfEZoAR5EOfvsK:bnfp4nl)* status: 1 file(s) to review.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42135)* status: :shipit: complete! ✓

**Pull request merged**
