### PR TITLE
feat: [CDS-52512]: Auto-detect auth plugins.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
Automatically detecting the auth plugins binary installed on the delegate.
Azure: kubelogin
GCP: gke-gcloud-auth-plugin

The changes in this PR are just helper functions and refactoring. The changes could not be tested but I have ensured deployment running successfully with these changes on local environment.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44094)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]

**Comment by GoelPratyush99** [comment]
trigger messagecheck

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44094)* status: 44 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/ContainerDeploymentDelegateBaseHelper.java` line 139 at r3](https://reviewable.io/reviews/harness/harness-core/44094#-NOsgmr6D5adQoZoF5ka:-NOsgmr70MPVzpgWJccL:bcghgao) ([raw file](https://github.com/harness/harness-core/blob/61c282d79bd510d249db1d015583ee71e42bdaad/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/ContainerDeploymentDelegateBaseHelper.java#L139)):*
> ```Java
>               gcpCredentials.getGcpCredentialType() == INHERIT_FROM_DELEGATE, gcpK8sInfraDelegateConfig.getCluster(),
>               gcpK8sInfraDelegateConfig.getNamespace());
>       kubernetesConfig.setShouldUseExecFormat(
> ```

This shouldn't be called till we don't have a working integration
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/ContainerDeploymentDelegateBaseHelperTest.java` line 189 at r3](https://reviewable.io/reviews/harness/harness-core/44094#-NOsh7cs-9tvpdlWxUjD:-NOsh7cs-9tvpdlWxUjE:bplt191) ([raw file](https://github.com/harness/harness-core/blob/61c282d79bd510d249db1d015583ee71e42bdaad/930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/ContainerDeploymentDelegateBaseHelperTest.java#L189)):*
> ```Java
> 
>     MockedStatic kubeConfigAuthPluginHelper = mockStatic(KubeConfigAuthPluginHelper.class);
>     PowerMockito.when(KubeConfigAuthPluginHelper.isExecAuthPluginBinaryAvailable(any(), any())).thenReturn(true);
> ```

Why do you need powermockito here?
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/44094#-NOshKwU79uW2iG2cUrv:-NOshKwU79uW2iG2cUrw:b-sk45im) ([raw file](https://github.com/harness/harness-core/blob/61c282d79bd510d249db1d015583ee71e42bdaad/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java#L30)):*
> ```Java
>     if (!shouldUseExecFormat && logCallback != null) {
>       logCallback.saveExecutionLog(
>           "Auth Plugin is removed for kubernetes>=1.26. Please install %s on the delegate and add the binary in your PATH",
> ```

most probably you meant auth provider
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java` line 58 at r3](https://reviewable.io/reviews/harness/harness-core/44094#-NOshhwoCRme5CeFD8yt:-NOshhwoCRme5CeFD8yu:blxe9oc) ([raw file](https://github.com/harness/harness-core/blob/61c282d79bd510d249db1d015583ee71e42bdaad/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java#L58)):*
> ```Java
> 
>     final ProcessResult result = processExecutor.execute();
>     return result.getExitValue() == 0;
> ```

we need to have logs if exit value is not 0

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44094)* status: 44 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/ContainerDeploymentDelegateBaseHelperTest.java` line 189 at r3](https://reviewable.io/reviews/harness/harness-core/44094#-NOsh7cs-9tvpdlWxUjD:-NPudOIACCYjmLG-dahE:b-rqaye1) ([raw file](https://github.com/harness/harness-core/blob/61c282d79bd510d249db1d015583ee71e42bdaad/930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/ContainerDeploymentDelegateBaseHelperTest.java#L189)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why do you need powermockito here?
</blockquote></details>

Done. Using Mockito instead.
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/K8sConstants.java` line 200 at r2](https://reviewable.io/reviews/harness/harness-core/44094#-NOhmzhuJjnakrnz3vh_-r2-200:-NPudUwa6gXEnofLmzmE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3fd9a52e4b59025acd4f364c3804ca115f4f3941/970-api-services-beans/src/main/java/io/harness/k8s/K8sConstants.java#L200)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We shouldn't expect user to install these binaries at a specific location, instead user should configure PATH for this
</blockquote></details>

Done.
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/44094#-NOhmzhvpsJvCZs-e_z2-r2-50:-NPuddX-6kAOcPFaOrSR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3fd9a52e4b59025acd4f364c3804ca115f4f3941/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java#L50)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Do we need this extensive logging? Can we log only: 
1. Trying to run command <cmd>
2. If failed logging why it failed
</blockquote></details>

Done.
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/44094#-NOshKwU79uW2iG2cUrv:-NPudWfO0X-wPC6G3tIB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/61c282d79bd510d249db1d015583ee71e42bdaad/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java#L30)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

most probably you meant auth provider
</blockquote></details>

Done.
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java` line 58 at r3](https://reviewable.io/reviews/harness/harness-core/44094#-NOshhwoCRme5CeFD8yt:-NPudk9g4Hf-4XtNIKXf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/61c282d79bd510d249db1d015583ee71e42bdaad/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java#L58)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

we need to have logs if exit value is not 0
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/ContainerDeploymentDelegateBaseHelper.java` line 139 at r3](https://reviewable.io/reviews/harness/harness-core/44094#-NOsgmr6D5adQoZoF5ka:-NPudlZXDAwLp1y7N0fQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/61c282d79bd510d249db1d015583ee71e42bdaad/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/ContainerDeploymentDelegateBaseHelper.java#L139)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This shouldn't be called till we don't have a working integration
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 32 of 44 files at r3, 5 of 6 files at r4, 6 of 7 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44094)* status: 40 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`960-api-services/src/main/java/io/harness/k8s/model/KubernetesConfig.java` line 56 at r6](https://reviewable.io/reviews/harness/harness-core/44094#-NPvbxGDCfbAPPp__eeX:-NPvbxGDCfbAPPp__eeY:boblxum) ([raw file](https://github.com/harness/harness-core/blob/4092d0864a936cb922e0ef6e51e4e65039d86efb/960-api-services/src/main/java/io/harness/k8s/model/KubernetesConfig.java#L56)):*
> ```Java
>       String namespace, String accountId, KubernetesClusterAuthType authType, char[] oidcClientId, char[] oidcSecret,
>       String oidcIdentityProviderUrl, String oidcUsername, char[] oidcPassword, String oidcScopes,
>       OidcGrantType oidcGrantType, String clusterName, KubernetesAzureConfig azureConfig, boolean shouldUseExecFormat) {
> ```

Missing set value for exec, and I doubt that we need boolean, we can just use not null check
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java` line 67 at r6](https://reviewable.io/reviews/harness/harness-core/44094#-NPvcJ5_ASvcqAJ72_-N:-NPvcJ5_ASvcqAJ72_-O:b7np8gi) ([raw file](https://github.com/harness/harness-core/blob/4092d0864a936cb922e0ef6e51e4e65039d86efb/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java#L67)):*
> ```Java
>     final ProcessResult result = processExecutor.execute();
>     if (result.getExitValue() != 0) {
>       saveLogs(String.format("Failed executing command: %s %n %s", command, result.outputUTF8()), logCallback);
> ```

This should be Unable to execute... is not like without this will not completely work
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java` line 73 at r6](https://reviewable.io/reviews/harness/harness-core/44094#-NPvcQpGDbgWdAlTkLxt:-NPvcQpGDbgWdAlTkLxu:b-uk9h42) ([raw file](https://github.com/harness/harness-core/blob/4092d0864a936cb922e0ef6e51e4e65039d86efb/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java#L73)):*
> ```Java
>   }
> 
>   private static void saveLogs(String errorMsg, LogCallback logCallback) {
> ```

Maybe we could LogLevel here to have it warn or info where this is required, it shouldn't be always INFO

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44094)* status: 40 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`960-api-services/src/main/java/io/harness/k8s/model/KubernetesConfig.java` line 56 at r6](https://reviewable.io/reviews/harness/harness-core/44094#-NPvbxGDCfbAPPp__eeX:-NPxc1Q5Be-0nfVa4Mv4:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/4092d0864a936cb922e0ef6e51e4e65039d86efb/960-api-services/src/main/java/io/harness/k8s/model/KubernetesConfig.java#L56)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Missing set value for exec, and I doubt that we need boolean, we can just use not null check
</blockquote></details>

Done
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java` line 67 at r6](https://reviewable.io/reviews/harness/harness-core/44094#-NPvcJ5_ASvcqAJ72_-N:-NPxc56u5Vh_GDbKq32D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4092d0864a936cb922e0ef6e51e4e65039d86efb/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java#L67)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This should be Unable to execute... is not like without this will not completely work
</blockquote></details>

Done.
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java` line 73 at r6](https://reviewable.io/reviews/harness/harness-core/44094#-NPvcQpGDbgWdAlTkLxt:-NPxc5czC3nTsursFYrb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4092d0864a936cb922e0ef6e51e4e65039d86efb/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java#L73)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Maybe we could LogLevel here to have it warn or info where this is required, it shouldn't be always INFO
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44094)* status: 40 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java` line 31 at r8](https://reviewable.io/reviews/harness/harness-core/44094#-NQ9vpDJA0kNWTqpzouI:-NQ9vpDK09dNHjgCJLNl:b-vt1cwv) ([raw file](https://github.com/harness/harness-core/blob/d55c60c34d2efe549460329c1e2212bbf69a7778/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java#L31)):*
> ```Java
>     boolean shouldUseExecFormat = runCommand(binaryName + " --version", logCallback);
>     if (!shouldUseExecFormat) {
>       saveLogs(
> ```

Either remove this one or we should print only for newer versions of kubectl

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44094)* status: 40 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java` line 31 at r8](https://reviewable.io/reviews/harness/harness-core/44094#-NQ9vpDJA0kNWTqpzouI:-NQA5uKVA-XUopXWUfuv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d55c60c34d2efe549460329c1e2212bbf69a7778/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java#L31)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Either remove this one or we should print only for newer versions of kubectl
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44094)* status: 40 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44094)* status: 40 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 27 of 44 files at r3, 3 of 6 files at r4, 4 of 7 files at r5, 1 of 3 files at r6, 2 of 3 files at r7, 1 of 1 files at r8, 7 of 7 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44094)* status: Waiting on team(s): del-team.

**Pull request merged**
