### PR TITLE
feat: [CDS-38379]: Adding support for checking referredBy count for f…

### PR DESCRIPTION
**Pull request by bojanmicovic**
…older by path

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34076)

### CODE REVIEW

**Comment by vladimir-peric** [comment]
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/34076#-N41XHMo3Twv8nVAWuu1:-N41XHMp52rva6cRxAlN:bqz8y2m) ([raw file](https://github.com/harness/harness-core/blob/42e8bea92ba50088346b2137887412d7040e3534/877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java#L114)):*
> ```Java
> 
>     if (ROOT_FOLDER_IDENTIFIER.equals(ngFile.getParentIdentifier())) {
>       ngFile.setPath(ROOT_FOLDER_IDENTIFIER + PATH_SEPARATOR + ngFile.getIdentifier());
> ```

Do we want here a Unix like path, with / at the beginning?

**Review by vladimir-peric — COMMENTED** [review]
> Reviewed 3 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34076)* status: 0 of 1 approvals obtained.

**Review by ivan-83 — DISMISSED** [review]
> Reviewed 1 of 7 files at r1, 3 of 6 files at r2, 5 of 7 files at r3, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34076)* status: :shipit: complete! ✓

___
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java` line 512 at r5](https://reviewable.io/reviews/harness/harness-core/34076#-N43dQVM5u1vjG89Hjz3:-N43dQVM5u1vjG89Hjz4:bk57amp) ([raw file](https://github.com/harness/harness-core/blob/32034c657821cae143cfda8962d9fcc93f12873a/877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java#L512)):*
> ```Java
>   }
> 
>   private boolean nameChanged(NGFile oldNGFile, FileDTO fileDto) {
> ```

Minor - move to some utility class
___
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java` line 516 at r5](https://reviewable.io/reviews/harness/harness-core/34076#-N43dWJZ1_k6Rnusp0Z9:-N43dWJZ1_k6Rnusp0ZA:bk57amp) ([raw file](https://github.com/harness/harness-core/blob/32034c657821cae143cfda8962d9fcc93f12873a/877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java#L516)):*
> ```Java
>   }
> 
>   private boolean parentChanged(NGFile oldNGFile, FileDTO fileDto) {
> ```

Minor - move to some utility class
___
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileStructureServiceImpl.java` line 130 at r5](https://reviewable.io/reviews/harness/harness-core/34076#-N43db4b958HE_XGdhQs:-N43db4b958HE_XGdhQt:b-sf6kom) ([raw file](https://github.com/harness/harness-core/blob/32034c657821cae143cfda8962d9fcc93f12873a/877-filestore/src/main/java/io/harness/filestore/service/impl/FileStructureServiceImpl.java#L130)):*
> ```Java
> 
>   @Override
>   public List<NGFile> listFoldersByPath(NGFile folder) {
> ```

Minor - listFolderChildrenByPath
___
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/service/EntitySetupUsageService.java` line 61 at r5](https://reviewable.io/reviews/harness/harness-core/34076#-N43dyr_5I_4KEBtnJ-2:-N43dyr_5I_4KEBtnJ-3:b-9cwtbx) ([raw file](https://github.com/harness/harness-core/blob/32034c657821cae143cfda8962d9fcc93f12873a/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/service/EntitySetupUsageService.java#L61)):*
> ```Java
>       EntityType referredEntityType, EntityType referredByEntityType, String referredByEntityName, Sort sort);
> 
>   Long countReferredByEntitiesByFQNsIn(String accountIdentifier, List<String> folderChildrenIdentifiers);
> ```

Rename >> folderChildrenIdentifiers to referredEntityFQNs



_Code quote:_
```Java
folderChildrenIdentifiers
```

**Comment by bojanmicovic** [comment]
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java` line 512 at r5](https://reviewable.io/reviews/harness/harness-core/34076#-N43dQVM5u1vjG89Hjz3:-N43uOuHAZ3Ulixo845z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/32034c657821cae143cfda8962d9fcc93f12873a/877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java#L512)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - move to some utility class
</blockquote></details>

Done.

**Comment by bojanmicovic** [comment]
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileStructureServiceImpl.java` line 130 at r5](https://reviewable.io/reviews/harness/harness-core/34076#-N43db4b958HE_XGdhQs:-N43uW95A9L5VCHjFeo4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/32034c657821cae143cfda8962d9fcc93f12873a/877-filestore/src/main/java/io/harness/filestore/service/impl/FileStructureServiceImpl.java#L130)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - listFolderChildrenByPath
</blockquote></details>

Done.

**Comment by bojanmicovic** [comment]
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/34076#-N41XHMo3Twv8nVAWuu1:-N43VK7UBNxFa7vflpTV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/42e8bea92ba50088346b2137887412d7040e3534/877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java#L114)):*
<details><summary><i>Previously, vladimir-peric (Vladimir Peric) wrote…</i></summary><blockquote>

Do we want here a Unix like path, with / at the beginning?
</blockquote></details>

Done.

**Review by bojanmicovic — COMMENTED** [review]
> Dismissed @ivan-83 and @vladimir-peric from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34076)* status: 6 file(s) to review. 0 of 1 approvals obtained.

**Pull request merged**
