### PR TITLE
feat: [CDS-54817]: Sync step - testing fixes

### PR DESCRIPTION
**Pull request by meenaravichandran1**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45769)

### CODE REVIEW

**Comment by meenaravichandran1** [comment]
trigger feature-build

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45769)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45769)* status: :shipit: complete! ✓

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45769)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 270 at r3](https://reviewable.io/reviews/harness/harness-core/45769#-NRjiqcvDsNylfkbIy3B:-NRjiqcvDsNylfkbIy3C:bs4mm7i) ([raw file](https://github.com/harness/harness-core/blob/357732a3bb55c8900f6df677ac855bcd2f9bbef1/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L270)):*
> ```Java
>   private void prepareApplicationForSync(List<Application> applicationsToBeSynced,
>       Set<Application> failedToSyncApplications, String accountId, String orgId, String projectId,
>       Set<String> serviceIdsInPipelineExecution, Set<String> envIdsInPipelineExecution,
> ```

I feel that the number of parameters for this method has the potential to grow. When/if I add one more parameter, will make the changes to the parameters. Have a few things in mind like combining the meta (I didn't know about the class IdentifierRef before), combining the serviceIds, envIds, clusterIds

**Comment by meenaravichandran1** [comment]
trigger feature-build

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45769)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 140 at r4](https://reviewable.io/reviews/harness/harness-core/45769#-NRnbste0JLG7UHIjGnh:-NRnbste0JLG7UHIjGni:b-705opu) ([raw file](https://github.com/harness/harness-core/blob/02806d649fde06f6ecb7d9201d3a63bcc83830f9/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L140)):*
> ```Java
>     EnvironmentClusterListing envClusterIds = getEnvAndClusterIdsInPipelineExecution(ambiance);
>     Set<String> envIdsInPipelineExecution =
>         envClusterIds.getEnvironmentIds() != null ? envClusterIds.getEnvironmentIds() : new HashSet<>();
> ```

nit, CollectionUtils.emptyIfnulll

**Comment by meenaravichandran1** [comment]
trigger feature-build

**Comment by meenaravichandran1** [comment]
trigger feature-build

**Review by mankrit-singh — DISMISSED** [review]
> Reviewed 1 of 2 files at r3, 5 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45769)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45769)* status: 7 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 140 at r4](https://reviewable.io/reviews/harness/harness-core/45769#-NRnbste0JLG7UHIjGnh:-NRu5_NA2zug8d4OnLn3:btc5uhb) ([raw file](https://github.com/harness/harness-core/blob/02806d649fde06f6ecb7d9201d3a63bcc83830f9/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L140)):*
> CollectionUtils.emptyIfnulll
done

**Comment by meenaravichandran1** [comment]
trigger feature-build

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 4 of 6 files at r5, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45769)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45769)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by anshul-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, 4 of 6 files at r5, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45769)* status: :shipit: complete! ✓

**Pull request merged**
