### PR TITLE
[feat]: [CDS-40089]: azure weba app jenkins artifact file name issue

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Describe your changes
Jenkins artifact name is now in the same format as other artifact names: timestamp+ArtifactName_BuildNum

jenkins_artifact_web_app

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40934)

### CODE REVIEW

**Comment by vladimir-peric** [comment]
trigger messagecheck

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40934)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/AzureAppServiceDeploymentService.java` line 608 at r3](https://reviewable.io/reviews/harness/harness-core/40934#-NIao4C0BRPkNcH189Bz:-NIao4C0BRPkNcH189C-:bfgf587) ([raw file](https://github.com/harness/harness-core/blob/ed87c4f3da612e4761132f89a22df8e5441067eb/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/AzureAppServiceDeploymentService.java#L608)):*
> ```Java
>       int lastIndexOf = absolutePath.lastIndexOf('_');
>       newName = absolutePath.substring(0, lastIndexOf);
>     }
> ```

Here, having one more else and handle the logic if the name contains # , and if it contains >>> newName =  absolutePath.substring(0, lastIndexOfNum);

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40934#-:-NIbcyVi7PKpNYN6wigl:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40934)* status: 3 file(s) to review.

**Review by vladimir-peric — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40934)* status: 3 file(s) to review.

**Review by markoharness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40934)* status: 3 file(s) to review.

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40934)* status: 3 file(s) to review. 1. unresolved discussions. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/AzureAppServiceDeploymentService.java` line 608 at r3](https://reviewable.io/reviews/harness/harness-core/40934#-NIao4C0BRPkNcH189Bz:-NIc3qPxDNs7H7JDple4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed87c4f3da612e4761132f89a22df8e5441067eb/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/AzureAppServiceDeploymentService.java#L608)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Here, having one more else and handle the logic if the name contains # , and if it contains >>> newName =  absolutePath.substring(0, lastIndexOfNum);
</blockquote></details>

Done.

**Review by markoharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40934)* status: 3 file(s) to review. 1. unresolved discussions.

**Review by markoharness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40934)* status: 1. unresolved discussions.

**Review by vladimir-peric — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40934#-:-NIc4GWs91sqBLEs0Uf4:bnfp4nl)* status: 1. unresolved discussions.

**Review by markoharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40934)* status: 1. unresolved discussions.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40934)* status: 1. unresolved discussions.

**Review by ivan-83 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40934)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40934#-:-NIc9mD95Hm3L4S9WFtZ:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
