### PR TITLE
fix: [PL-31623]: List api should work even if connector not found

### PR DESCRIPTION
**Pull request by nishantsaini20**
## Describe your changes
Currently if the connector used in a streaming destination is not found (in case connector is deleted) the aggregate list api throws an exception and cause the page to break. This PR is to prevent the api breaking in the above mentioned case.

Testing:
1. Created a streaming destination.
2. Deleted the connector used in streaming destination
3. Load the streaming destination page and verified that page doesn't show any exception and list all the streaming destination with missing connector info which is expected.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44496)

### CODE REVIEW

**Review by gn-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44496)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/AggregateStreamingServiceImpl.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/44496#-NPNxlLq1ZtxYLwOIDxo:-NPNxlLrEPLb6ytkKSXq:bw7hd3u) ([raw file](https://github.com/harness/harness-core/blob/9086c66507f2c95968b31e6ffb07621718d0b877/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/AggregateStreamingServiceImpl.java#L125)):*
> ```Java
>           NGRestUtils.getResponse(connectorResourceClient.get(connectorId, accountIdentifier, null, null),
>               "Could not get connector response for account: " + accountIdentifier + " after {} attempts.");
>     } catch (Exception exception) {
> ```

nit: Looks like getResponse can throw UnexpectedException - you can narrow it down to that



_Code quote:_
```Java
Exception exception
```
___
*[`platform-service/modules/audit-service/src/test/java/io/harness/audit/api/streaming/impl/AggregateStreamingServiceImplTest.java` line 204 at r1](https://reviewable.io/reviews/harness/harness-core/44496#-NPNy-oO9yMhjLdazfih:-NPNy-oO9yMhjLdazfii:b7txz3k) ([raw file](https://github.com/harness/harness-core/blob/9086c66507f2c95968b31e6ffb07621718d0b877/platform-service/modules/audit-service/src/test/java/io/harness/audit/api/streaming/impl/AggregateStreamingServiceImplTest.java#L204)):*
> ```Java
>     StreamingDestinationStatus statusEnum = StreamingDestinationStatus.ACTIVE;
>     int page = 0;
>     int limit = 10;
> ```

nit: all of these should be inlined, as those are not relevant to what you are testing to test nor are these reused



_Code quote:_
```Java
    long now = System.currentTimeMillis();
    String searchTerm = randomAlphabetic(RANDOM_STRING_CHAR_COUNT_10);
    StreamingDestinationStatus statusEnum = StreamingDestinationStatus.ACTIVE;
    int page = 0;
    int limit = 10;
```

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44496)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/AggregateStreamingServiceImpl.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/44496#-NPNxlLq1ZtxYLwOIDxo:-NPQqiTNBvfmkw90aaR8:by75n66) ([raw file](https://github.com/harness/harness-core/blob/9086c66507f2c95968b31e6ffb07621718d0b877/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/AggregateStreamingServiceImpl.java#L125)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

nit: Looks like getResponse can throw UnexpectedException - you can narrow it down to that
</blockquote></details>

io.harness.remote.client.NGRestUtils#handleResponse method can throw InvalidRequestException in case the api gives an error response hence need a broader handling.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44496)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44496)* status: 1. unresolved discussions.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44496)* status: :shipit: complete! ✓

**Pull request merged**
