### PR TITLE
[fix]: [DEL-4888]: Make connect and read timeout configurable for the migration service

### PR DESCRIPTION
**Pull request by davejohnston**
## Describe your changes

Adds configuration to let us replace both the connect and read timeouts for the migration service

Every time a user signs up, the migration service is adding a new rule to the USE_IMMUTABLE_DELEGATE flag.  As the number of rules grows over 3000, the time to update is taking longer and the request timesout.

This is a short term solution until the log is changed to have this flag on by default for new users.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39895)

### CODE REVIEW

**Review by AnupamIO — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39895)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`360-cg-manager/container/scripts/replace_configs.sh` line 240 at r1](https://reviewable.io/reviews/harness/harness-core/39895#-NGSdMSY4pBe9bvNW5s7:-NGSdMSY4pBe9bvNW5s8:b-fjgzxp) ([raw file](https://github.com/harness/harness-core/blob/00305f23ca0be01d15b04d2fd30cc6fba6c800c3/360-cg-manager/container/scripts/replace_configs.sh#L240)):*
> ```Shell
> 
> if [[ "" != "$CF_MIGRATION_CONNECT_TIMEOUT" ]]; then
>   export $CF_MIGRATION_CONNECT_TIMEOUT; yq -i '.cfMigrationConfig.connectionTimeout=env($CF_MIGRATION_CONNECT_TIMEOUT)' $CONFIG_FILE
> ```

probably $ might not be needed in cfMigrationConfig.connectionTimeout=env($CF_MIGRATION_CONNECT_TIMEOUT) .

**Review by AnupamIO — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39895)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39895)* status: :shipit: complete! ✓

**Comment by Vbhatia20** [comment]
trigger messagecheck

**Comment by Vbhatia20** [comment]
trigger messagecheck

**Pull request merged**
