### PR TITLE
[fix]: [CDS-52937]: make infrastructure type immutable

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43506)

### CODE REVIEW

**Review by RajBaviskar — APPROVED** [review]

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 239 at r2](https://reviewable.io/reviews/harness/harness-core/43506#-NN_Xc1h-g75KE7rj20N:-NN_Xc1h-g75KE7rj20O:bf9se7h) ([raw file](https://github.com/harness/harness-core/blob/39aa26996cd989d32f0e8b2086213f4be798cd44/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L239)):*
> ```Java
> 
>   private void validateImmutableFieldsAndThrow(
>       @NonNull InfrastructureEntity requestInfra, InfrastructureEntity oldInfra) {
> ```

we have NotNull on only 1 argument ? is this intentional ? Ideally private methods need not need to have argument validations

**Comment by tchaurasiya** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 239 at r2](https://reviewable.io/reviews/harness/harness-core/43506#-NN_hmMg1Tu6_j8d4ukU:-NN_hmMg1Tu6_j8d4ukV:bxvcwuu) ([raw file](https://github.com/harness/harness-core/blob/39aa26996cd989d32f0e8b2086213f4be798cd44/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L239)):*
> ```Java
> 
>   private void validateImmutableFieldsAndThrow(
>       @NonNull InfrastructureEntity requestInfra, InfrastructureEntity oldInfra) {
> ```

yeah agree, i think we dont need argument validation for private method. 
As they are already part of earlier code flow.
It got added while exracting method using IDE.

**Review by RajBaviskar — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43506#-:-NNcXdpy89ZV2FBrm9nT:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43506)* status: 2 file(s) to review.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43506)* status: 2 file(s) to review.

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43506)* status: :shipit: complete! ✓

**Pull request merged**
