### PR TITLE
feat: [CDS-58919]: Upgrade go-template to 0.4.3

### PR DESCRIPTION
**Pull request by alebuh**
## Describe your changes
Upgrade go-template to 0.4.3 (Golang upgrade to 1.20)
Binaries have been uploaded to the next buckets:

**[harness-cdn-binary-source-cd-play](https://console.cloud.google.com/storage/browser/harness-cdn-binary-source/go-template/release;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=platform-205701&prefix=&forceOnObjectsSortingFiltering=false)**
**[harness-cdn-binary-source](https://console.cloud.google.com/storage/browser/harness-cdn-binary-source/go-template/release;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=platform-205701&prefix=&forceOnObjectsSortingFiltering=false)**
**[harness-qa-public](https://console.cloud.google.com/storage/browser/harness-qa-public/public/shared/tools/go-template/release;tab=objects?project=qa-setup&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)**
**[harness-prod-public](https://console.cloud.google.com/storage/browser/harness-prod-public/public/shared/tools/go-template/release;tab=objects?project=prod-setup-205416&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)**
**[snapshot-go-template](https://console.cloud.google.com/storage/browser/snapshot-go-template/release;tab=objects?authuser=0&project=platform-205701&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)**

Testing:
PR env created with immutable delegate with go-template version 0.4.3. 
I've created a few pipelines that required go-template for manifest rendering and executed them to make sore that everything works as expected.
Tested with amd64 and arm64 images as described in https://github.com/wings-software/go-template#readme

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49029)

### CODE REVIEW

**Comment by alebuh** [comment]
trigger uts

**Comment by alebuh** [comment]
trigger uts

**Comment by alebuh** [comment]
trigger publish-delegate

**Review by bharatgoelharness — CHANGES_REQUESTED** [review]
update the testing you have done.
and path of cdn where you have uploaded the binaries.

**Comment by alebuh** [comment]
> update the testing you have done. and path of cdn where you have uploaded the binaries.

The testing was done on the PR env where I tested the new binary version to make sure that it works properly for manifest rendering. However, real testing will be done on the PRE_QA and QA where we need to make sure that no automation is failing because of this.
Not sure what do you mean by the cdn path where I uploaded binaries? I've only uploaded it to the buckets already stated in the PR description, though that is enough. Please let me know if I need to upload it anywhere else

**Review by markoharness — COMMENTED** [review]
Have you done AMD based and ARM based delegate testing?

**Comment by alebuh** [comment]
> Have you done AMD based and ARM based delegate testing?

Yes, as described here https://github.com/wings-software/go-template

**Review by bharatgoelharness — APPROVED** [review]

**Comment by alebuh** [comment]
trigger messagecheck, review

**Pull request merged**
