### PR TITLE
feat: [CDS-46634]: added delegate task for fetching apps and updating info for dashboards

### PR DESCRIPTION
**Pull request by vaibhav-si**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40663)

### CODE REVIEW

**Comment by vaibhav-si** [comment]
trigger smartchecks

**Review by mdmilic — APPROVED** [review]
Approving delegate codeowner changes

> Reviewed 5 of 20 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40663#-:-NHk2hXeDSLnTuNgYCD7:b-rgbdj)* status: 14 file(s) to review.

**Review by rohitk-h — CHANGES_REQUESTED** [review]
> Reviewed 17 of 20 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40663)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/FetchLinkedAppsStep.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/40663#-NHmjtjD86TTPEGx22YX:-NHmjtjD86TTPEGx22YY:b-s23z92) ([raw file](https://github.com/harness/harness-core/blob/e9690a5a132c3f63d85634e9b3105cee438e9818/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/FetchLinkedAppsStep.java#L105)):*
> ```Java
>       ILogStreamingStepClient logStreamingStepClient =
>           logStreamingStepClientFactory.getLogStreamingStepClient(ambiance);
>       logStreamingStepClient.openStream("");
> ```

Let's not have this empty. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/FetchLinkedAppsStep.java` line 161 at r2](https://reviewable.io/reviews/harness/harness-core/40663#-NHmkb-Y1hq6S3OQWSk0:-NHmkb-Y1hq6S3OQWSk1:bbfhety) ([raw file](https://github.com/harness/harness-core/blob/e9690a5a132c3f63d85634e9b3105cee438e9818/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/FetchLinkedAppsStep.java#L161)):*
> ```Java
>       ILogStreamingStepClient logStreamingStepClient =
>           logStreamingStepClientFactory.getLogStreamingStepClient(ambiance);
>       logStreamingStepClient.openStream("");
> ```

Same as above. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsFetchAppTask.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/40663#-NHmlZpF3fxC1kNN88No:-NHmlZpF3fxC1kNN88Np:b-o2nx9j) ([raw file](https://github.com/harness/harness-core/blob/e9690a5a132c3f63d85634e9b3105cee438e9818/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsFetchAppTask.java#L57)):*
> ```Java
>       FetchAppTaskParams taskParams = (FetchAppTaskParams) parameters;
>       NGDelegateLogCallback ngDelegateLogCallback =
>           new NGDelegateLogCallback(getLogStreamingTaskClient(), "", false, null);
> ```

can we not keep this empty as well? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsFetchAppTask.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/40663#-NHmlzTlBr6vu3JuAeBP:-NHmlzTlBr6vu3JuAeBQ:b6hunl5) ([raw file](https://github.com/harness/harness-core/blob/e9690a5a132c3f63d85634e9b3105cee438e9818/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsFetchAppTask.java#L88)):*
> ```Java
>     try {
>       if (gitFile == null || gitFile.getFileContent() == null) {
>         return null;
> ```

nit: If we return empty here, it will reduce the parameter if check above. (non-blocking)
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsFetchAppTask.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/40663#-NHmmDqG0f76pOpJ1nva:-NHmmDqG0f76pOpJ1nvb:b-mai4ol) ([raw file](https://github.com/harness/harness-core/blob/e9690a5a132c3f63d85634e9b3105cee438e9818/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsFetchAppTask.java#L91)):*
> ```Java
>       }
>       Yaml yaml = new Yaml();
>       Map<String, Object> yamlMap = yaml.load(gitFile.getFileContent());
> ```

Are we not supporting `.json` extension? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsTaskHelper.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/40663#-NHlxuaS6kcNw43lqvld:-NHlxuaS6kcNw43lqvle:b-7awyd8) ([raw file](https://github.com/harness/harness-core/blob/e9690a5a132c3f63d85634e9b3105cee438e9818/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsTaskHelper.java#L41)):*
> ```Java
> import java.util.List;
> 
> @Singleton
> ```

nit: add owned by annotation
___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 407 at r2](https://reviewable.io/reviews/harness/harness-core/40663#-NHlzdSF1NbleDO4w6ru:-NHlzdSF1NbleDO4w6rv:b6g4z6y) ([raw file](https://github.com/harness/harness-core/blob/e9690a5a132c3f63d85634e9b3105cee438e9818/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L407)):*
> ```Java
>   TERRAGRUNT_DESTROY_TASK_NG(TaskGroup.TERRAGRUNT, "Terragrunt Destroy Task", true),
>   TERRAGRUNT_ROLLBACK_TASK_NG(TaskGroup.TERRAGRUNT, "Terragrunt Rollback Task", true),
>   GITOPS_FETCH_APP_TASK(TaskGroup.GITOPS, "Gitops Fetch App Task");
> ```

nit: As convention like other tasks can we add _NG suffix

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40663)* status: 1 change requests. 4. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/FetchLinkedAppsStep.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/40663#-NHmjtjD86TTPEGx22YX:-NHn9Xtu2NDtyc4TCIFM:b8tbra9) ([raw file](https://github.com/harness/harness-core/blob/e9690a5a132c3f63d85634e9b3105cee438e9818/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/FetchLinkedAppsStep.java#L105)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Let's not have this empty. 
</blockquote></details>

I have another PR will logging related changes. This will we handled with that.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/FetchLinkedAppsStep.java` line 161 at r2](https://reviewable.io/reviews/harness/harness-core/40663#-NHmkb-Y1hq6S3OQWSk0:-NHn9gOS6sLtneRhr0zW:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/e9690a5a132c3f63d85634e9b3105cee438e9818/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/FetchLinkedAppsStep.java#L161)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Same as above. 
</blockquote></details>

ditto
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsFetchAppTask.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/40663#-NHmlZpF3fxC1kNN88No:-NHn9j8eEJHltB4M8Rwe:b-ks6e4a) ([raw file](https://github.com/harness/harness-core/blob/e9690a5a132c3f63d85634e9b3105cee438e9818/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsFetchAppTask.java#L57)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

can we not keep this empty as well? 
</blockquote></details>

I am not using commandUnit at all
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsFetchAppTask.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/40663#-NHmmDqG0f76pOpJ1nva:-NHn9o2Q-dviJUE5c_bM:b66cagm) ([raw file](https://github.com/harness/harness-core/blob/e9690a5a132c3f63d85634e9b3105cee438e9818/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsFetchAppTask.java#L91)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Are we not supporting `.json` extension? 
</blockquote></details>

will check this with product
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsTaskHelper.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/40663#-NHlxuaS6kcNw43lqvld:-NHn9rI91htJov_eA7i3:bgxc4fb) ([raw file](https://github.com/harness/harness-core/blob/e9690a5a132c3f63d85634e9b3105cee438e9818/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsTaskHelper.java#L41)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

nit: add owned by annotation
</blockquote></details>

will do in follow up PR

**Comment by rohitk-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsFetchAppTask.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/40663#-NHmmDqG0f76pOpJ1nva:-NHnHidHER792eGLgPWn:b-3o8r46) ([raw file](https://github.com/harness/harness-core/blob/e9690a5a132c3f63d85634e9b3105cee438e9818/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsFetchAppTask.java#L91)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

will check this with product
</blockquote></details>

We support both config.json / config.yaml in UpdateReleaseRepo step so we should support here as well.

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40663)* status: :shipit: complete! ✓

**Comment by anshul-harness** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java` line 1968 at r2](https://reviewable.io/reviews/harness/harness-core/40663#-NHoc7q3Amv4p8ALuMP2:-NHoc7q4-VPF88QKgR0O:b844ms2) ([raw file](https://github.com/harness/harness-core/blob/e9690a5a132c3f63d85634e9b3105cee438e9818/950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java#L1968)):*
> ```Java
>     kryo.register(TerragruntDestroyTaskResponse.class, 573559);
>     kryo.register(TerragruntRollbackTaskResponse.class, 573560);
>     kryo.register(FetchAppTaskParams.class, 573561);
> ```

Add GitOps prefix in front of the class as it is very specific to GitOps

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40663)* status: :shipit: complete! ✓

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java` line 1968 at r2](https://reviewable.io/reviews/harness/harness-core/40663#-NHoc7q3Amv4p8ALuMP2:-NHoeScS6l0vPVc4TX7R:bgxc4fb) ([raw file](https://github.com/harness/harness-core/blob/e9690a5a132c3f63d85634e9b3105cee438e9818/950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java#L1968)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Add GitOps prefix in front of the class as it is very specific to GitOps
</blockquote></details>

will do in follow up PR
___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 407 at r2](https://reviewable.io/reviews/harness/harness-core/40663#-NHlzdSF1NbleDO4w6ru:-NHoeVMNBO-Cj6naPBVy:b-9kbulg) ([raw file](https://github.com/harness/harness-core/blob/e9690a5a132c3f63d85634e9b3105cee438e9818/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L407)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

nit: As convention like other tasks can we add _NG suffix
</blockquote></details>

Don't think it's needed for Gitops. Other swimlanes existed in CG as well.

**Pull request merged**
