### PR TITLE
[feat]: [CDS-34225]: Refactor AWSCFTemplate to be used in NG

### PR DESCRIPTION
**Pull request by nassergonzalez**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31099)

### CODE REVIEW

**Comment by nassergonzalez** [comment]
trigger messagecheck

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 16 of 31 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31099)* status: 15 file(s) to review. 1 change requests. 

___
*[400-rest/src/main/java/io/harness/serializer/kryo/ManagerKryoRegistrar.java, line 1141 at r3](https://reviewable.io/reviews/harness/harness-core/31099#-Mx8guxp4pb7wyUgnUo7:-Mx8guxp4pb7wyUgnUo8:b7y6cqp) ([raw file](https://github.com/harness/harness-core/blob/15b3fd013567bf5596fbb12e6fd007605fb1d664/400-rest/src/main/java/io/harness/serializer/kryo/ManagerKryoRegistrar.java#L1141)):*
> ```Java
>     kryo.register(AwsCFRequestType.class, 5475);
>     kryo.register(AwsCFRequest.class, 5474);
>     kryo.register(AwsCFTemplateParamsData.class, 5478);
> ```

It should be added to new module kryoRegistrar

**Review by nassergonzalez — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31099#-:-Mx9DrA93I73h3eNOT5e:bnfp4nl)* status: 34 file(s) to review. 1 change requests. 5. unresolved discussions. 

___
*[400-rest/src/main/java/io/harness/serializer/kryo/ManagerKryoRegistrar.java, line 1141 at r3](https://reviewable.io/reviews/harness/harness-core/31099#-Mx8guxp4pb7wyUgnUo7:-Mx9Dnmt-Etsjk31NmZW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/15b3fd013567bf5596fbb12e6fd007605fb1d664/400-rest/src/main/java/io/harness/serializer/kryo/ManagerKryoRegistrar.java#L1141)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

It should be added to new module kryoRegistrar
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/helpers/AwsCFHelperServiceDelegateImpl.java, line 9 at r3](https://reviewable.io/reviews/harness/harness-core/31099#-Mx8iB0v15q-HWeZqdeX:-Mx9BNlv-gkilFuXpq_g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6294f5696c41f8278549bd5da680e028e43479d0/930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/helpers/AwsCFHelperServiceDelegateImpl.java#L9)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Let's try to move classes to the same packages in new modules.
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/utils/AwsConfigToInternalMapper.java, line 8 at r3](https://reviewable.io/reviews/harness/harness-core/31099#-Mx8iVTPD2mDGpiBinQM:-Mx9BdBW9-mSzrd9tGUc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6294f5696c41f8278549bd5da680e028e43479d0/930-delegate-tasks/src/main/java/io/harness/delegate/utils/AwsConfigToInternalMapper.java#L8)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

 Let's try to move classes to the same packages in new modules.
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/utils/GitUtilsDelegate.java, line 8 at r3](https://reviewable.io/reviews/harness/harness-core/31099#-Mx8igyj4juiH5Sjew_f:-Mx9Bj31AGc6mvR43_Cm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6294f5696c41f8278549bd5da680e028e43479d0/930-delegate-tasks/src/main/java/io/harness/delegate/utils/GitUtilsDelegate.java#L8)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Let's try to move classes to the same packages in new modules.
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/test/java/io/harness/delegate/task/cloudformation/helpers/AwsCFHelperServiceDelegateImplTest.java, line 8 at r3](https://reviewable.io/reviews/harness/harness-core/31099#-Mx8ikVFDjjI_V0SRGN8:-Mx9DmYr7AV7nB7s8-1M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6294f5696c41f8278549bd5da680e028e43479d0/930-delegate-tasks/src/test/java/io/harness/delegate/task/cloudformation/helpers/AwsCFHelperServiceDelegateImplTest.java#L8)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

The same here
</blockquote></details>

Done.

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 9 of 31 files at r2, 1 of 1 files at r3, 23 of 24 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31099)* status: 1 file(s) to review. 1 change requests. 

___
*[950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java, line 1108 at r4](https://reviewable.io/reviews/harness/harness-core/31099#-Mx9HVeM2HHNlBaYHJiz:-Mx9HVeM2HHNlBaYHJj-:b-ty7pgy) ([raw file](https://github.com/harness/harness-core/blob/1e752ac5aa5bf874b7d35c6fa9becf06dadf59ac/950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java#L1108)):*
> ```Java
>     kryo.register(ArtifactoryFetchBuildsResponse.class, 543478);
>     kryo.register(ArtifactoryStoreDelegateConfig.class, 543479);
>     kryo.register(AwsCFTemplateParamsData.class, 543480);
> ```

please add ti with the same number as it was before: 5478



_Suggestion (from 400-rest/src/main/java/io/harness/serializer/kryo/ManagerKryoRegistrar.java):_
```Java
ref https://harness.slack.com/archives/C8DHL8G8P/p1645728045738839
```

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31099)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 

___
*[950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java, line 1108 at r4](https://reviewable.io/reviews/harness/harness-core/31099#-Mx9HVeM2HHNlBaYHJiz:-Mx9UctI9xJHAEEV0jU5:b-l8r9ls) ([raw file](https://github.com/harness/harness-core/blob/1e752ac5aa5bf874b7d35c6fa9becf06dadf59ac/950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java#L1108)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

please add ti with the same number as it was before: 5478
</blockquote></details>

Done.
Didn't know that thanks a lot

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31099)* status: :shipit: complete! ✓

**Pull request merged**
