### PR TITLE
[fix]: [CDS-76622]: Adding support for update TTL methods in respective collections

### PR DESCRIPTION
**Pull request by archit-harness**
## Describe your changes

Changes - Adding support for update TTL methods in respective collections

Impact - Adding support for update TTL methods in respective collections, thus it will be helpful when executions ends we can update ttl from 6 months to currentTime plus 30 days , currently these methods are not called from anywhere

Testing - Added UT for updating TTL as well as tested flows locally

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51477)

### CODE REVIEW

**Comment by archit-harness** [comment]
trigger uts

**Comment by archit-harness** [comment]
trigger uts

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 26 of 50 files at r1, 1 of 1 files at r2, 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51477)* status: 52 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanService.java` line 58 at r3](https://reviewable.io/reviews/harness/harness-core/51477#-NbOj2eb-L_VxP4rEJmY:-NbOj2ec0cJqhNYqzCEp:b-r07bw1) ([raw file](https://github.com/harness/harness-core/blob/93a49515f20623685c027101875a2b2525e36594/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanService.java#L58)):*
> ```Java
>    * @param nodeEntityIds
>    */
>   void updateTTLForNodesForGivenIds(Set<String> nodeEntityIds, Date ttlDate);
> ```

where we will use this method?
___
*[`pipeline-service/service/src/test/resources/mongo/indexes.txt` line 62 at r3](https://reviewable.io/reviews/harness/harness-core/51477#-NbOjpei07kXTIjM8SJc:-NbOjpej7Ckj1m9J80at:b-an37lf) ([raw file](https://github.com/harness/harness-core/blob/93a49515f20623685c027101875a2b2525e36594/pipeline-service/service/src/test/resources/mongo/indexes.txt#L62)):*
> ```help
> nodeExecutionsInfo {"name": "validUntil_1", "background": true, "expireAfterSeconds": 0} {"validUntil": 1}
> nodes {"name": "planId_idx", "background": true} {"planId": 1}
> nodes {"name": "validUntil_1", "background": true, "expireAfterSeconds": 0} {"validUntil": 1}
> ```

We will be indexing a lot of data here. I think we need to to index creation separately to deploy flow

**Comment by archit-harness** [comment]
trigger uts

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51477)* status: 52 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanService.java` line 58 at r3](https://reviewable.io/reviews/harness/harness-core/51477#-NbOj2eb-L_VxP4rEJmY:-NbOlili3ImEGYzxWIVy:b9rq03a) ([raw file](https://github.com/harness/harness-core/blob/93a49515f20623685c027101875a2b2525e36594/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanService.java#L58)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

where we will use this method?
</blockquote></details>

removed it in last commit
___
*[`pipeline-service/service/src/test/resources/mongo/indexes.txt` line 62 at r3](https://reviewable.io/reviews/harness/harness-core/51477#-NbOjpei07kXTIjM8SJc:-NbOlb-b4G5Av1W_qflp:bkonzmv) ([raw file](https://github.com/harness/harness-core/blob/93a49515f20623685c027101875a2b2525e36594/pipeline-service/service/src/test/resources/mongo/indexes.txt#L62)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

We will be indexing a lot of data here. I think we need to to index creation separately to deploy flow
</blockquote></details>

yes that we follow normally, once this is there in qa, post that will create ops ticket to add the index in prod1 and prod2 as well

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 16 of 50 files at r1, 1 of 1 files at r2, 10 of 25 files at r3, 19 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51477)* status: 6 file(s) to review.

**Comment by archit-harness** [comment]
trigger review

**Pull request merged**
