### PR TITLE
[feat]: [CDS-42481]: logging improved for command units

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37003)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37003)

**Comment by vladimir-peric** [comment]
trigger messagecheck

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37003)* status: 0 of 1 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 290 at r1](https://reviewable.io/reviews/harness/harness-core/37003#-NAtIrmY69pNEdJN8XTp:-NAtIrmY69pNEdJN8XTq:b-3vnstq) ([raw file](https://github.com/harness/harness-core/blob/a4fd008b3fc9f3c5b35ff7137f1672540eaaf1f0/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L290)):*
> ```Java
>     StringBuilder commandUnits = new StringBuilder("Command Units: ");
>     units.stream().forEach(unit -> commandUnits.append(unit).append(" > "));
>     log.info(commandUnits.toString());
> ```

Can we have a message, `Sending above command units to delegate task [cu1, cu2, etc]`
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java` line 140 at r1](https://reviewable.io/reviews/harness/harness-core/37003#-NAtJE1EAHxIAuBAbdWL:-NAtJE1EAHxIAuBAbdWM:bn6h6rh) ([raw file](https://github.com/harness/harness-core/blob/a4fd008b3fc9f3c5b35ff7137f1672540eaaf1f0/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java#L140)):*
> ```Java
> 
>   private void logUnits(List<NgCommandUnit> units) {
>     StringBuilder commandUnits = new StringBuilder("Command Units to execute: ");
> ```

here the message, `Received command units to execute on delegate: [cu1, cu2, etc]`

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37003)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained.

**Comment by vladimir-peric** [comment]
trigger messagecheck

**Comment by vladimir-peric** [comment]
trigger messagecheck, ti4, checkstyle, codebasehash, pmd

**Comment by vladimir-peric** [comment]
trigger pmd

**Review by ivan-83 — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37003)* status: 2. unresolved discussions.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37003#-:-NAu3hWH2CZG2Ta5sWWa:bnfp4nl)* status: 2. unresolved discussions.

**Pull request closed without merging**
