### PR TITLE
[fix]: [CDS-78686]: Remove expression resolution from step Inputs for each nodeExecution

### PR DESCRIPTION
**Pull request by archit-harness**
## Describe your changes

Changes - Remove expression resolution from step Inputs for each nodeExecution

Impact - 
a) Now expression engine for each step inputs will not be done, thus reducing same resolution of inputs from twice to one.
b) After this change release to Prod, in next release we can remove support to pass step inputs in plan node proto and saving separately in our DB, thus reducing nodes entity size.
c) As we are saving nodeExecutionsInfo same with nodeExecution, we can remove OrchestrationEventType.STEP_INPUTS_UPDATE thus reducing one log event per nodeExecution.

Testing - 

a) Tested running p0 pipeline executions
b) Tested shell script when it contains secret output variables, those are not coming in input screen as those are excluded.
c) Also added UT where when we are removing fields from map in stepInputs, we are not deleting from resolvedStep parameters as those are shallow copy.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

Screenshot 2023-09-07 at 1 35 50 PM
Screenshot 2023-09-07 at 1 35 56 PM

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52573)

### CODE REVIEW

**Comment by archit-harness** [comment]
trigger uts

**Comment by archit-harness** [comment]
trigger uts

**Comment by archit-harness** [comment]
trigger uts

**Comment by archit-harness** [comment]
trigger ut5

**Review by shivamnegi94 — APPROVED** [review]

**Review by hextechpal — APPROVED** [review]
> Reviewed 26 of 28 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52573)* status: 28 file(s) to review.

**Review by Y0709 — APPROVED** [review]
> Reviewed 25 of 28 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52573)* status: 1 file(s) to review. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/PlanNode.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/52573#-NdnWF_d-D5yUMLDglhl:-NdnWF_d-D5yUMLDglhm:birabyv) ([raw file](https://github.com/harness/harness-core/blob/92ed9852648e5e877b2f01eb0fc2c7741471f97d/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/PlanNode.java#L61)):*
> ```Java
>   // stage fqn
>   @NonFinal @lombok.Setter String stageFqn;
> ```

I dont think we have changed anything here right.

**Comment by archit-harness** [comment]
trigger review

**Review by mohitg0795 — APPROVED** [review]

**Comment by archit-harness** [comment]
trigger review

**Pull request merged**
