### PR TITLE
feat: [PL-27255]: Added indexes for auditEvents

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36038)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36038)

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36038)* status: 1 file(s) to review. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/AuditEvent.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/36038#-N8c-26u8YW9o8yBa-6i:-N8c-26u8YW9o8yBa-6j:bgtbdn5) ([raw file](https://github.com/harness/harness-core/blob/fd676105e9baaa1ee513a99c96ca36825f27e216/platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/AuditEvent.java#L126)):*
> ```Java
>                  .build())
>         .add(SortCompoundMongoIndex.builder()
>                  .name("ngAuditActionIdentiferTypeTime")
> ```

Just curious to know, why there 2 indexes created for identical fields?



_Code quote:_
```Java
                 .name("ngAuditActionIdentiferTypeTime")
```

**Review by puneetsar — COMMENTED** [review]
Missing description for the PR? What scenario use these indices?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36038#-:-N8eCQJl88DtS4kOATjr:bt2pwi6)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/AuditEvent.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/36038#-N8c-26u8YW9o8yBa-6i:-N8eCINvBGeJcnjpWo5c:b-89rovg) ([raw file](https://github.com/harness/harness-core/blob/fd676105e9baaa1ee513a99c96ca36825f27e216/platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/AuditEvent.java#L126)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Just curious to know, why there 2 indexes created for identical fields?
</blockquote></details>

Looks like we have copy paste error here.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36038)* status: 1 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/AuditEvent.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/36038#-N8c-26u8YW9o8yBa-6i:-N8hKLE16OcZijmr28SN:b-x88ts6) ([raw file](https://github.com/harness/harness-core/blob/fd676105e9baaa1ee513a99c96ca36825f27e216/platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/AuditEvent.java#L126)):*
<details><summary><i>Previously, puneetsar (Puneet Saraswat) wrote…</i></summary><blockquote>

Looks like we have copy paste error here. 
</blockquote></details>

I missed the action field, added now

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Pull request closed without merging**
