### PR TITLE
[feat]: [CDS-67183]: Refactored setting up of UserFlow in the threadContext

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have refactored setting up of UserFlow in the threadContext as the earlier way of setting the user flow context in the pipeline gitx helper was misleading.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49438)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`970-ng-commons/src/main/java/io/harness/utils/ThreadOperationContextHelper.java` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/49438#-NYN9L4o3cP8yInE_Xhr:-NYN9L4o3cP8yInE_Xhs:brfutee) ([raw file](https://github.com/harness/harness-core/blob/70797255090411bee4e0e08dd89104c754ca6509/970-ng-commons/src/main/java/io/harness/utils/ThreadOperationContextHelper.java#L40)):*
> ```Java
>   }
> 
>   public void setUserFlowContext(USER_FLOW userFlow) {
> ```

can we name it only "setUserFlow"? The class already has associated name of the context for it.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/utils/ThreadContextHelper.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/49438#-NYN9YJG7oHSLikQj_1u:-NYN9YJG7oHSLikQj_1v:b2kz5vm) ([raw file](https://github.com/harness/harness-core/blob/70797255090411bee4e0e08dd89104c754ca6509/pipeline-service/service/src/main/java/io/harness/utils/ThreadContextHelper.java#L20)):*
> ```Java
> @UtilityClass
> @OwnedBy(HarnessTeam.PIPELINE)
> public class ThreadContextHelper {}
> ```

whats this for?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java` line 277 at r3](https://reviewable.io/reviews/harness/harness-core/49438#-NYN9bJe2ML-a7Y8wb8Q:-NYN9bJfCNP7syMBnkbc:b-v6vz8y) ([raw file](https://github.com/harness/harness-core/blob/10706f63a90be302108e65b25b7adc3f4d5bb54c/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java#L277)):*
> ```Java
>     if (mergeInputSetRequestDTO.isGetOnlyFileContent()
>         && pmsFeatureFlagService.isEnabled(accountId, FeatureName.PIE_GET_FILE_CONTENT_ONLY)) {
>       PipelineGitXHelper.setUserFlowContext(USER_FLOW.EXECUTION);
> ```

what happens to the old method? I don't see any file where the code is removed for it.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49438)* status: 5 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/utils/ThreadOperationContextHelper.java` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/49438#-NYN9L4o3cP8yInE_Xhr:-NYNB17E2Y1H12e3XCG_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/70797255090411bee4e0e08dd89104c754ca6509/970-ng-commons/src/main/java/io/harness/utils/ThreadOperationContextHelper.java#L40)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we name it only "setUserFlow"? The class already has associated name of the context for it.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java` line 277 at r3](https://reviewable.io/reviews/harness/harness-core/49438#-NYN9bJe2ML-a7Y8wb8Q:-NYNBAKB7pvDYUC8mv2z:b7d4nfg) ([raw file](https://github.com/harness/harness-core/blob/10706f63a90be302108e65b25b7adc3f4d5bb54c/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java#L277)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what happens to the old method? I don't see any file where the code is removed for it.
</blockquote></details>

its removed from the pipelineGitXHelper, it was initially missed 
___
*[`pipeline-service/service/src/main/java/io/harness/utils/ThreadContextHelper.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/49438#-NYN9YJG7oHSLikQj_1u:-NYNBJesDLmwIj7qmJ38:brpmqbp) ([raw file](https://github.com/harness/harness-core/blob/70797255090411bee4e0e08dd89104c754ca6509/pipeline-service/service/src/main/java/io/harness/utils/ThreadContextHelper.java#L20)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats this for?
</blockquote></details>

removed

**Comment by adivishy1** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49438)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
