### PR TITLE
[fix]: [CDS-36700]: decouple workflowId from query to fetch rollback artifact

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34146)

### CODE REVIEW

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34146)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java` line 5517 at r1](https://reviewable.io/reviews/harness/harness-core/34146#-N46y2lfBxige6Mvmeko:-N46y2lfBxige6Mvmekp:boka52h) ([raw file](https://github.com/harness/harness-core/blob/b4de5a431f150d5e75c2b85ff17cb308839277f7/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java#L5517)):*
> ```Java
>     return wingsPersistence.createQuery(WorkflowExecution.class)
>         .filter(WorkflowExecutionKeys.appId, workflowExecution.getAppId())
>         .filter(WorkflowExecutionKeys.workflowType, workflowExecution.getWorkflowType())
> ```

should we also be adding a filter for `inframappingId` as well here.
Currently, this will fetch you any successful execution for `KUBERNETES` based deployment for an `appId`.. right ..?
___
*[`400-rest/src/test/java/software/wings/service/impl/WorkflowExecutionServiceImplTest.java` line 3008 at r1](https://reviewable.io/reviews/harness/harness-core/34146#-N46yNG6BIKcr70iQ3AS:-N46yNG6BIKcr70iQ3AT:b2k9f3t) ([raw file](https://github.com/harness/harness-core/blob/b4de5a431f150d5e75c2b85ff17cb308839277f7/400-rest/src/test/java/software/wings/service/impl/WorkflowExecutionServiceImplTest.java#L3008)):*
> ```Java
>     workflowExecutionService.populateRollbackArtifacts(
>         workflowExecution, asList(INFRA_MAPPING_ID, INFRA_MAPPING_ID), stdParams, false);
>     assertThat(stdParams.getRollbackArtifactIds()).containsExactly(ARTIFACT_ID);
> ```

add a test case with FF true as well.

**Comment by tchaurasiya** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java` line 5517 at r1](https://reviewable.io/reviews/harness/harness-core/34146#-N46y2lfBxige6Mvmeko:-N478GS4EDfOG2kHGup7:bga967o) ([raw file](https://github.com/harness/harness-core/blob/b4de5a431f150d5e75c2b85ff17cb308839277f7/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java#L5517)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

should we also be adding a filter for `inframappingId` as well here.
Currently, this will fetch you any successful execution for `KUBERNETES` based deployment for an `appId`.. right ..?
</blockquote></details>

Its already being handled here.



_Code quote:_
```Java
    if (isNotEmpty(infraMappingList)) {
      workflowExecutionQuery.filter(WorkflowExecutionKeys.infraMappingIds, new HashSet<>(infraMappingList));
    }
```

**Comment by tchaurasiya** [comment]
*[`400-rest/src/test/java/software/wings/service/impl/WorkflowExecutionServiceImplTest.java` line 3008 at r1](https://reviewable.io/reviews/harness/harness-core/34146#-N46yNG6BIKcr70iQ3AS:-N47AVbO-pWsEm4WM7Jl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b4de5a431f150d5e75c2b85ff17cb308839277f7/400-rest/src/test/java/software/wings/service/impl/WorkflowExecutionServiceImplTest.java#L3008)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

add a test case with FF true as well.
</blockquote></details>

Done.

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34146)* status: :shipit: complete! ✓

**Review by puthrayaharness — CHANGES_REQUESTED** [review]

**Comment by tchaurasiya** [comment]
trigger ti3

**Comment by tchaurasiya** [comment]
trigger ti0

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 4 of 6 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34146)* status: 1 change requests. 1. unresolved discussions.

**Review by inderschera — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 1 of 1 files at r3, 4 of 6 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34146)* status: 1 change requests. 1. unresolved discussions.

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 1 of 1 files at r3, 4 of 6 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34146)* status: :shipit: complete! ✓

**Pull request merged**
