### PR TITLE
fix: [PL-31498]: Added familyName and givenName in userInfo in scim

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Describe your changes
We are now going to populate givenName and familyName of users enabled via SCIM api. This is behind a FF and this request was specific to jpmc.
Testing:
Tested create, get calls for scim in local using ngRok. Attaching screenShots of the resulting name filed in the return Json.
Screenshot 2023-02-24 at 2 41 57 PM

Screenshot 2023-02-24 at 2 41 47 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44194)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 628 at r2](https://reviewable.io/reviews/harness/harness-core/44194#-NOwXTTV2MVg-PigydWb:-NOwXTTV2MVg-PigydWc:b-37dor8) ([raw file](https://github.com/harness/harness-core/blob/de5d8af3b669c679849c0f430824079bff9acef6/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L628)):*
> ```Java
>       "Allow different Service Principal in Auth Token and Request Body. Used for Internal purpose only.",
>       HarnessTeam.PL),
>   PL_JPMC_SCIM_REQ_NAME_FORMAT(
> ```

Lets keep the name bit generic, this FF will not be just for NAME format but we will use this FF for subsequent items as well, thanks



_Code quote:_
```Java
PL_JPMC_SCIM_REQ_NAME_FORMAT(
```

**Review by pbarapatre10 — COMMENTED** [review]
Please test 'CREATE", 'UPDATE', GET 'USER', GET list 'USERS' with and without FF, they all should have 'givenName', 'familyName', 'formatted' with FF ON. Thanks

> Reviewed 1 of 3 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44194#-:-NOwa7rsCdEEs19BFhEW:b-2g324q)* status: 5 file(s) to review. 0 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 160 at r4](https://reviewable.io/reviews/harness/harness-core/44194#-NOyn0j9-CW1YSpQLfd4:-NOyn0j9-CW1YSpQLfd5:bp9rf3k) ([raw file](https://github.com/harness/harness-core/blob/319eb9c7c2ad5c0e02f9fe2262ebda23a5c1ba6a/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L160)):*
> ```Java
>     Map<String, String> nameMap = new HashMap<String, String>() {
>       {
>         if (featureFlagService.isEnabled(PL_JPMC_SCIM_REQUIREMENTS, user.getDefaultAccountId())) {
> ```

this should be 'accountId' and not the defaultAccountId, thanks



_Code quote:_
```Java
user.getDefaultAccountId()
```

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44194)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Comment by VikasMaddukuriHarness** [comment]
trigger messagecheck

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 4 of 5 files at r4, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44194)* status: :shipit: complete! ✓

**Pull request merged**
