### PR TITLE
feat: [CDS-47125]: Have added active instances exception

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
For ui to catch existence of active instances,have added a new exception incase of  services
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42694)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`980-commons/src/main/java/io/harness/exception/ActiveInstanceException.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/42694#-NLyYDpa8qTyFM4KyiY-:-NLyYDpa8qTyFM4KyiY0:b-t523tw) ([raw file](https://github.com/harness/harness-core/blob/3c9cb3755fc18f021f5c53b79638450edea241e7/980-commons/src/main/java/io/harness/exception/ActiveInstanceException.java#L14)):*
> ```Java
> import io.harness.eraro.Level;
> 
> public class ActiveInstanceException extends WingsException {
> ```

better name would be "ActiveServiceInstancesPresentException" and we should move this class to 125 or 127 module

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42694)* status: 5 file(s) to review. 0 of 2 approvals obtained.

**Review by vivekkarnatiharness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42694)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/ActiveInstanceException.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/42694#-NLyYDpa8qTyFM4KyiY-:-NM-8ID64LKiAiMemHgZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3c9cb3755fc18f021f5c53b79638450edea241e7/980-commons/src/main/java/io/harness/exception/ActiveInstanceException.java#L14)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

better name would be "ActiveServiceInstancesPresentException" and we should move this class to 125 or 127 module
</blockquote></details>

Done.

**Review by RajBaviskar — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42694)* status: :shipit: complete! ✓

**Review by RajBaviskar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42694#-:-NM1ZB4S5WQ7nBnPbZwI:bnfp4nl)* status: :shipit: complete! ✓

**Comment by vivekkarnatiharness** [comment]
trigger ti1

**Comment by vivekkarnatiharness** [comment]
trigger ti1

**Pull request merged**
