### PR TITLE
feat: [PL-22607]: Migration of ResourceGroup V1 to V2 

### PR DESCRIPTION
**Pull request by reetika04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31304)

### CODE REVIEW

**Review by karansiwach360 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31304)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[830-resource-group/src/main/java/io/harness/resourcegroup/framework/v2/events/ResourceGroupCreateEvent.java, line 0 at r1](https://reviewable.io/reviews/harness/harness-core/31304#-MxreiOw0DXMV-vbkTp4:-MxreiOw0DXMV-vbkTp5:b-ux1omg) ([raw file](https://github.com/harness/harness-core/blob/5b4c1643d65d1a663617239fce20e695c65c04af/830-resource-group/src/main/java/io/harness/resourcegroup/framework/v2/events/ResourceGroupCreateEvent.java#L0)):*
Why are we removing these events? Eventually we will need v2 events and the event type should be different from v1 event types.

**Comment by reetika04** [comment]
trigger rebase

**Review by karansiwach360 — COMMENTED** [review]
> Reviewed 5 of 15 files at r1, 1 of 7 files at r2, 5 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31304)* status: 23 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[830-resource-group/src/main/java/io/harness/resourcegroup/migrations/MigrationOfV1ToV2.java, line 31 at r3](https://reviewable.io/reviews/harness/harness-core/31304#-MyBRP9u-Noc-UhMgHmq:-MyBRP9u-Noc-UhMgHmr:boy9bak) ([raw file](https://github.com/harness/harness-core/blob/339a7ced3946e0a7e46ffa0733780e564c86f276/830-resource-group/src/main/java/io/harness/resourcegroup/migrations/MigrationOfV1ToV2.java#L31)):*
> ```Java
>   public void migrate() {
>     log.info("[MigrationOfV1ToV2] starting migration....");
>     resourceGroupRepository.findAll().forEach(resourceGroupService::upsert);
> ```

There might be many documents in the database, should we use some form of pagination or do batch query with iterator (NGSecretManagerMigration)?

**Review by gupta-utkarsh — CHANGES_REQUESTED** [review]
> Reviewed 8 of 15 files at r1, 1 of 7 files at r2, 11 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31304)* status: 13 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[830-resource-group/src/main/java/io/harness/resourcegroup/framework/v1/remote/resource/HarnessResourceGroupResource.java, line 159 at r3](https://reviewable.io/reviews/harness/harness-core/31304#-MyD-Rf711-Ll483UfZY:-MyD-Rf711-Ll483UfZZ:bghiywi) ([raw file](https://github.com/harness/harness-core/blob/ea87f7589e841486420f8cf12092c1d03585ee5d/830-resource-group/src/main/java/io/harness/resourcegroup/framework/v1/remote/resource/HarnessResourceGroupResource.java#L159)):*
> ```Java
>   @InternalApi
>   public ResponseDTO<ResourceGroupResponse>
>   getInternal(@Parameter(description = "This is the Identifier of the Entity") @NotNull @PathParam(
> ```

I don't think this API is used anymore. Can you check in Resource Group Client if anybody still uses it? If not, then we should remove it.
___
*[830-resource-group/src/main/java/io/harness/resourcegroup/framework/v1/remote/resource/HarnessResourceGroupResource.java, line 277 at r3](https://reviewable.io/reviews/harness/harness-core/31304#-MyD-q9B74KwltIwd-mW:-MyD-q9B74KwltIwd-mX:bkuhm6w) ([raw file](https://github.com/harness/harness-core/blob/ea87f7589e841486420f8cf12092c1d03585ee5d/830-resource-group/src/main/java/io/harness/resourcegroup/framework/v1/remote/resource/HarnessResourceGroupResource.java#L277)):*
> ```Java
>     validateResourceSelectors(resourceGroupRequest);
>     Optional<ResourceGroupResponse> resourceGroupResponseOpt = Optional.ofNullable(ResourceGroupMapper.toV1Response(
>         resourceGroupService.update(ResourceGroupMapper.fromV1DTO(resourceGroupRequest.getResourceGroup()), false)
> ```

What is true, false here which is only false in v2?
___
*[830-resource-group/src/main/java/io/harness/resourcegroup/framework/v2/service/ResourceGroupService.java, line 32 at r3](https://reviewable.io/reviews/harness/harness-core/31304#-MyD0pBsBLjtSSpfB3Dx:-MyD0pBsBLjtSSpfB3Dy:bkyrwl0) ([raw file](https://github.com/harness/harness-core/blob/ea87f7589e841486420f8cf12092c1d03585ee5d/830-resource-group/src/main/java/io/harness/resourcegroup/framework/v2/service/ResourceGroupService.java#L32)):*
> ```Java
>       @NotNull Scope scope, @NotEmpty String identifier, @NotNull ManagedFilter managedFilter);
> 
>   Optional<ResourceGroupResponse> upsert(io.harness.resourcegroup.v1.model.ResourceGroup resourceGroup);
> ```

Why Resource Group Service has methods taking v1 Resource Group?
___
*[830-resource-group/src/main/java/io/harness/resourcegroup/migrations/MigrationOfV1ToV2.java, line 31 at r3](https://reviewable.io/reviews/harness/harness-core/31304#-MyBRP9u-Noc-UhMgHmq:-MyD15Zp5loSY79y5vCP:bw393mc) ([raw file](https://github.com/harness/harness-core/blob/ea87f7589e841486420f8cf12092c1d03585ee5d/830-resource-group/src/main/java/io/harness/resourcegroup/migrations/MigrationOfV1ToV2.java#L31)):*
<details><summary><i>Previously, karansiwach360 (Karan Siwach) wrote…</i></summary><blockquote>

There might be many documents in the database, should we use some form of pagination or do batch query with iterator (NGSecretManagerMigration)?
</blockquote></details>

This should be an iterator

**Review by karansiwach360 — COMMENTED** [review]
> Reviewed 4 of 15 files at r1, 4 of 13 files at r3, 14 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31304)* status: 15 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by karansiwach360 — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31304)* status: 15 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31304)* status: 15 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[830-resource-group/src/main/java/io/harness/resourcegroup/framework/v1/remote/resource/HarnessResourceGroupResource.java, line 159 at r3](https://reviewable.io/reviews/harness/harness-core/31304#-MyD-Rf711-Ll483UfZY:-MyvR8clD2MEwQhbeYVa:b2925ql) ([raw file](https://github.com/harness/harness-core/blob/ea87f7589e841486420f8cf12092c1d03585ee5d/830-resource-group/src/main/java/io/harness/resourcegroup/framework/v1/remote/resource/HarnessResourceGroupResource.java#L159)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

I don't think this API is used anymore. Can you check in Resource Group Client if anybody still uses it? If not, then we should remove it.
</blockquote></details>

It is being used in the client. Will remove it in the next PR.
___
*[830-resource-group/src/main/java/io/harness/resourcegroup/framework/v1/remote/resource/HarnessResourceGroupResource.java, line 277 at r3](https://reviewable.io/reviews/harness/harness-core/31304#-MyD-q9B74KwltIwd-mW:-MyvRG0-6C1uxiGp0Ocq:b-5wiax1) ([raw file](https://github.com/harness/harness-core/blob/ea87f7589e841486420f8cf12092c1d03585ee5d/830-resource-group/src/main/java/io/harness/resourcegroup/framework/v1/remote/resource/HarnessResourceGroupResource.java#L277)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

What is true, false here which is only false in v2?
</blockquote></details>

We have sanitise resource selectors in V1 which is always true. Removed that in V2.
___
*[830-resource-group/src/main/java/io/harness/resourcegroup/framework/v2/events/ResourceGroupCreateEvent.java, line  at r1](https://reviewable.io/reviews/harness/harness-core/31304#-MxreiOw0DXMV-vbkTp4:-MybRBic70AbhCf3WgVq:bx3iq6m) ([raw file](https://github.com/harness/harness-core/blob/5b4c1643d65d1a663617239fce20e695c65c04af/830-resource-group/src/main/java/io/harness/resourcegroup/framework/v2/events/ResourceGroupCreateEvent.java#L)):*
<details><summary><i>Previously, karansiwach360 (Karan Siwach) wrote…</i></summary><blockquote>

Why are we removing these events? Eventually we will need v2 events and the event type should be different from v1 event types.
</blockquote></details>

Addressed
___
*[830-resource-group/src/main/java/io/harness/resourcegroup/framework/v2/service/ResourceGroupService.java, line 32 at r3](https://reviewable.io/reviews/harness/harness-core/31304#-MyD0pBsBLjtSSpfB3Dx:-MybREgSBZY0fT7xGPDd:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/ea87f7589e841486420f8cf12092c1d03585ee5d/830-resource-group/src/main/java/io/harness/resourcegroup/framework/v2/service/ResourceGroupService.java#L32)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

Why Resource Group Service has methods taking v1 Resource Group?
</blockquote></details>

Removed
___
*[830-resource-group/src/main/java/io/harness/resourcegroup/migrations/MigrationOfV1ToV2.java, line 31 at r3](https://reviewable.io/reviews/harness/harness-core/31304#-MyBRP9u-Noc-UhMgHmq:-MyvRSUh4RBz1Ytn__xO:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ea87f7589e841486420f8cf12092c1d03585ee5d/830-resource-group/src/main/java/io/harness/resourcegroup/migrations/MigrationOfV1ToV2.java#L31)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

This should be an iterator
</blockquote></details>

Done

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 12 of 15 files at r4, 2 of 3 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31304#-:-MyvSU8P4DPNsFwNWcJ0:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
