### PR TITLE
[feat]: [PIE-6661]: Add policy validations to pipeline validation event

### PR DESCRIPTION
**Pull request by namanvermah**
Impact: Touches a flow not exposed anywhere, and no existing flows are touched. So, no impact.
Testing: Unit Tests Added. E2E testing done by hitting the new API to start the validation process, and then hitting the get result by uuid API added in the previous PR. The response came as expected.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41172)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41172)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/beans/ValidationResult.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/41172#-NIbMw-9DBb2akiCCwn4:-NIbMw-9DBb2akiCCwn5:bk8bgl0) ([raw file](https://github.com/harness/harness-core/blob/082649609667c5677b4ba5c3acfb74e4b993dab4/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/beans/ValidationResult.java#L17)):*
> ```Java
> import lombok.With;
> 
> @Data
> ```

Can we discuss tomorrow how both results are filled, in same thread or different thread

**Comment by ankittiwari-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/handler/PipelineAsyncValidationHandler.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/41172#-NIbNA4S78DUOqwPFNPy:-NIbNA4S78DUOqwPFNPz:b-p88cr8) ([raw file](https://github.com/harness/harness-core/blob/082649609667c5677b4ba5c3acfb74e4b993dab4/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/handler/PipelineAsyncValidationHandler.java#L63)):*
> ```Java
>     // Add Template Module Info temporarily to Pipeline Entity
>     pipelineEntity.setTemplateModules(pipelineTemplateHelper.getTemplatesModuleInfo(templateMergeResponse));
> ```

Let's break both validation into separate smaller methods and call them from the main method

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41172)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/handler/PipelineAsyncValidationHandler.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/41172#-NIbNA4S78DUOqwPFNPy:-NIfAR8z7TCfKLnwew4t:b-c5epc3) ([raw file](https://github.com/harness/harness-core/blob/082649609667c5677b4ba5c3acfb74e4b993dab4/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/handler/PipelineAsyncValidationHandler.java#L63)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

The template validation returns two things, TemplateMergeResponseDTO and ValidationResult. Having a method that returns both just becomes tricky, and imo less readable.
</blockquote></details>

I would also agree to have smaller methods, you can call Template validation and pass the result to both methods, Currently the run method is too big, it should call only one validateAsync methods, which calls single responsible validation methods

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41172)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/handler/PipelineAsyncValidationHandler.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/41172#-NIbNA4S78DUOqwPFNPy:-NIfFP0TCj2OxvhiqkDz:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/082649609667c5677b4ba5c3acfb74e4b993dab4/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/handler/PipelineAsyncValidationHandler.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I would also agree to have smaller methods, you can call Template validation and pass the result to both methods, Currently the run method is too big, it should call only one validateAsync methods, which calls single responsible validation methods
</blockquote></details>

Done

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41172)* status: 6 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Pull request merged**
