### PR TITLE
[feat]: [PIE-3939]: add UT for clone pipeline helpers

### PR DESCRIPTION
**Pull request by smjt-h**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33757)

This PR adds UTs to existing clone Pipeline feature helpers

### CODE REVIEW

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33757)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/test/java/io/harness/pms/helpers/PipelineCloneHelperTest.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/33757#-N3UAUM_CVrXOyavt5DJ:-N3UAUM_CVrXOyavt5DK:bu5uhal) ([raw file](https://github.com/harness/harness-core/blob/d96ea37f5d97c456acf95faca22a47b8072e0c29/800-pipeline-service/src/test/java/io/harness/pms/helpers/PipelineCloneHelperTest.java#L55)):*
> ```Java
>   private final String DEST_PIPELINE_DESCRIPTION = "test description_d";
>   private final String SOURCE_PIPELINE_YAML =
>       "pipeline:\n    name: pip4\n    identifier: pip4\n    projectIdentifier: localproj\n    orgIdentifier: default\n    description: this is decrip\n    tags:\n        tag1: \"\"\n        tag2: \"\"\n        tagg: \"\"\n    stages:\n        - stage:\n              name: first\n              identifier: first\n              type: CI\n              spec:\n                  cloneCodebase: false\n                  infrastructure:\n                      type: KubernetesDirect\n                      spec:\n                          connectorRef: kube2\n                          namespace: harness-deligate\n                          automountServiceAccountToken: true\n                          nodeSelector: {}\n                  execution:\n                      steps:\n                          - step:\n                                type: Run\n                                name: runit\n                                identifier: runit\n                                spec:\n                                    connectorRef: account.harnessImage\n                                    image: golang:1.6\n                                    shell: Sh\n                                    command: echo jkadb\n                                description: runit descrip\n";
> ```

nit, you can keep this in test/resources as file
___
*[`800-pipeline-service/src/test/java/io/harness/pms/pipeline/service/PMSPipelineServiceImplTest.java` line 94 at r1](https://reviewable.io/reviews/harness/harness-core/33757#-N3UAafPBHt79vD4B9e3:-N3UAafPBHt79vD4B9e4:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/d96ea37f5d97c456acf95faca22a47b8072e0c29/800-pipeline-service/src/test/java/io/harness/pms/pipeline/service/PMSPipelineServiceImplTest.java#L94)):*
> ```Java
>   private final String DEST_PIPELINE_DESCRIPTION = "test description_d";
>   private final String PIPELINE_YAML =
>       "pipeline:\n    name: pip4\n    identifier: pip4\n    projectIdentifier: localproj\n    orgIdentifier: default\n    description: this is decrip\n    tags:\n        tag1: \"\"\n        tag2: \"\"\n        tagg: \"\"\n    stages:\n        - stage:\n              name: first\n              identifier: first\n              type: CI\n              spec:\n                  cloneCodebase: false\n                  infrastructure:\n                      type: KubernetesDirect\n                      spec:\n                          connectorRef: kube2\n                          namespace: harness-deligate\n                          automountServiceAccountToken: true\n                          nodeSelector: {}\n                  execution:\n                      steps:\n                          - step:\n                                type: Run\n                                name: runit\n                                identifier: runit\n                                spec:\n                                    connectorRef: account.harnessImage\n                                    image: golang:1.6\n                                    shell: Sh\n                                    command: echo jkadb\n                                description: runit descrip\n";
> ```

ditto

**Review by smjt-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33757)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/test/java/io/harness/pms/pipeline/service/PMSPipelineServiceImplTest.java` line 94 at r1](https://reviewable.io/reviews/harness/harness-core/33757#-N3UAafPBHt79vD4B9e3:-N3XmZ0I66kEi3eD6D3X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d96ea37f5d97c456acf95faca22a47b8072e0c29/800-pipeline-service/src/test/java/io/harness/pms/pipeline/service/PMSPipelineServiceImplTest.java#L94)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33757)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
trigger ti2

**Comment by piyush-harness** [comment]
trigger ti0,ti1,ti2,ti3,ti4

**Pull request merged**
