### PR TITLE
fix: [PL-23659]: Added the error message for SCM_UNPROCESSABLE_ENTITY 422 error code

### PR DESCRIPTION
**Pull request by goelsatyam2**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31448)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31448)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java, line 22 at r1](https://reviewable.io/reviews/harness/harness-core/31448#-MyBLl6aBX5kHO6SCv2R:-MyBLl6aBX5kHO6SCv2S:b-53mrie) ([raw file](https://github.com/harness/harness-core/blob/23c1d153ea1c593bc5d6f14681a7eab078677716/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java#L22)):*
> ```Java
>   public static final String UNABLE_TO_PUSH_TO_REPO_WITH_INVALID_BRANCH_NAME =
>       "We could not perform a push to the git repository with the given branch name. Possible reasons can be:\n"
>       + "1. Branch doesn't exists or has been deleted\n"
> ```

Typo: Branch doesn't "exist"

Also, can't 2nd point be combined in this only? eg: Branch doesn't exist or has been deleted/renamed
___
*[952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionHints.java, line 16 at r1](https://reviewable.io/reviews/harness/harness-core/31448#-MyBMFGw4aJsajEyWGQC:-MyBMFGw4aJsajEyWGQD:b-5qks1y) ([raw file](https://github.com/harness/harness-core/blob/23c1d153ea1c593bc5d6f14681a7eab078677716/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionHints.java#L16)):*
> ```Java
>   public static final String INVALID_CREDENTIALS = "Please check your credentials.";
> 
>   public static final String INVALID_BRANCH_NAME = "Please check branch exists in git";
> ```

Please check "if" branch exists in git.

Also, can we make it customized by also providing branch name?
___
*[952-scm-java-client/src/main/java/io/harness/impl/ScmResponseStatusUtils.java, line 39 at r1](https://reviewable.io/reviews/harness/harness-core/31448#-MyBMPeX7pHEGCpy8z3S:-MyBMPeX7pHEGCpy8z3T:b8jjau6) ([raw file](https://github.com/harness/harness-core/blob/23c1d153ea1c593bc5d6f14681a7eab078677716/952-scm-java-client/src/main/java/io/harness/impl/ScmResponseStatusUtils.java#L39)):*
> ```Java
>         throw NestedExceptionUtils.hintWithExplanationException(SCMExceptionHints.INVALID_CREDENTIALS,
>             SCMExceptionExplanations.UNABLE_TO_PUSH_TO_REPO_WITH_USER_CREDENTIALS, new ScmException(errorCode));
>       } else if (errorCode == ErrorCode.SCM_UNPROCESSABLE_ENTITY) {
> ```

This seems to be a common error code. How do we relate it to only branch issue? It could be anything else also.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31448)* status: :shipit: complete! ✓

**Review by goelsatyam2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31448)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java, line 22 at r1](https://reviewable.io/reviews/harness/harness-core/31448#-MyBLl6aBX5kHO6SCv2R:-MyLqxwr7eKg9HP2eM8P:b-n56lbv) ([raw file](https://github.com/harness/harness-core/blob/23c1d153ea1c593bc5d6f14681a7eab078677716/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java#L22)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Typo: Branch doesn't "exist"

Also, can't 2nd point be combined in this only? eg: Branch doesn't exist or has been deleted/renamed
</blockquote></details>

delete/renamed looks better, Will make this change
___
*[952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionHints.java, line 16 at r1](https://reviewable.io/reviews/harness/harness-core/31448#-MyBMFGw4aJsajEyWGQC:-MyLl3vIAbGrrJ1GqMFD:bpe3qfy) ([raw file](https://github.com/harness/harness-core/blob/23c1d153ea1c593bc5d6f14681a7eab078677716/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionHints.java#L16)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Please check "if" branch exists in git.

Also, can we make it customized by also providing branch name?
</blockquote></details>

checkScmResponseStatusAndThrowException is being used at more than 9-10 places. That's why I didn't add the branch name.
___
*[952-scm-java-client/src/main/java/io/harness/impl/ScmResponseStatusUtils.java, line 39 at r1](https://reviewable.io/reviews/harness/harness-core/31448#-MyBMPeX7pHEGCpy8z3S:-MyLkr-n-RZpEM8BK2G3:bigybdl) ([raw file](https://github.com/harness/harness-core/blob/23c1d153ea1c593bc5d6f14681a7eab078677716/952-scm-java-client/src/main/java/io/harness/impl/ScmResponseStatusUtils.java#L39)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This seems to be a common error code. How do we relate it to only branch issue? It could be anything else also.
</blockquote></details>

Yes, it can be anything. We can start with this errorMsg and can add more with time.

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/31448)

**Pull request closed without merging**
