### PR TITLE
feat: [SSCA-1174]: Add UTs for Remaining APIs, fix filtering logic in listing APIs and address review comments

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57189)

### CODE REVIEW

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by arpit-harness — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57189)* status: 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/mapper/RemediationTrackerMapper.java` line 391 at r1](https://reviewable.io/reviews/harness/harness-core/57189#-Nn8E9gV5elGnKFOkx2b:-Nn8E9gW8dpBMPWKhpar:b9ui089) ([raw file](https://github.com/harness/harness-core/blob/61991a89d28005f0c2ce5b46918609d978688cab/ssca-manager/service/src/main/java/io/harness/ssca/mapper/RemediationTrackerMapper.java#L391)):*
> ```Java
>         || (deployments.getPendingNonProdCount() != null && deployments.getPendingNonProdCount() > 0)
>         || (deployments.getPatchedProdCount() != null && deployments.getPatchedProdCount() > 0)
>         || (deployments.getPatchedNonProdCount() != null && deployments.getPatchedNonProdCount() > 0);
> ```

Can we combine these two into one and use not(!) ?
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/mapper/RemediationTrackerMapper.java` line 401 at r1](https://reviewable.io/reviews/harness/harness-core/57189#-Nn8EV4g5wBbyNWjklNZ:-Nn8EV4g5wBbyNWjklN_:b-rcqbkb) ([raw file](https://github.com/harness/harness-core/blob/61991a89d28005f0c2ce5b46918609d978688cab/ssca-manager/service/src/main/java/io/harness/ssca/mapper/RemediationTrackerMapper.java#L401)):*
> ```Java
>         return Operator.LESSTHANEQUALS;
>       case EQUALS:
>         return EQUALS;
> ```

Should this be Operator.EQUALS;

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by arpit-harness — DISMISSED** [review]

**Review by deepharness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 12 files at r1, 1 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57189)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/mapper/RemediationTrackerMapper.java` line 230 at r5](https://reviewable.io/reviews/harness/harness-core/57189#-NnCO1CR2tS8U2zyvbV8:-NnCO1CR2tS8U2zyvbV9:bb8fswy) ([raw file](https://github.com/harness/harness-core/blob/527ac9990185dd5c6790952996ae5f019bc72df1/ssca-manager/service/src/main/java/io/harness/ssca/mapper/RemediationTrackerMapper.java#L230)):*
> ```Java
>         .pendingProdCount(deploymentStatusEnum == null
>                     || deploymentStatusEnum.equals(RemediationArtifactListingRequestBody.DeploymentStatusEnum.PROD)
>                 ? deploymentsCount.getPendingProdCount()
> ```

why we want deploymentsCount when deploymentStatusEnum  is null ?

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57189)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/mapper/RemediationTrackerMapper.java` line 230 at r5](https://reviewable.io/reviews/harness/harness-core/57189#-NnCO1CR2tS8U2zyvbV8:-NnClV7M6xYCmvXoXtBJ:b2j93a5) ([raw file](https://github.com/harness/harness-core/blob/527ac9990185dd5c6790952996ae5f019bc72df1/ssca-manager/service/src/main/java/io/harness/ssca/mapper/RemediationTrackerMapper.java#L230)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

why we want deploymentsCount when deploymentStatusEnum  is null ?
</blockquote></details>

@deepharness This is a filter, If it's not present we will show for all.

**Review by deepharness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57189)* status: 7 file(s) to review.

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by arpit-harness — APPROVED** [review]

**Pull request merged**
