### PR TITLE
[feat]:[pie-6502]: Git sdk caching integration 

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Git sdk caching integration with git caching. Have tested out the basic get pipeline flows.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40534)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitEntityFindInfoDTO.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/40534#-NHcNpFc0LHVqbZMBUSG:-NHcNpFc0LHVqbZMBUSH:b-8pbhdw) ([raw file](https://github.com/harness/harness-core/blob/57f0a54d4e5ad4bfd0ce13865dd5861b08cee26e/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitEntityFindInfoDTO.java#L55)):*
> ```Java
>   String parentEntityRepoName;
>   @Hidden
>   @Parameter(description = "Parent entity account identifier")
> ```

why are we changing descriptions here when params are already hidden?

**Comment by mohitg0795** [comment]
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 265 at r2](https://reviewable.io/reviews/harness/harness-core/40534#-NHcOcLFClZc2LdTwrrv:-NHcOcLFClZc2LdTwrrw:b3wtt9f) ([raw file](https://github.com/harness/harness-core/blob/57f0a54d4e5ad4bfd0ce13865dd5861b08cee26e/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L265)):*
> ```protobuf
> }
> 
> message CacheResponse {
> ```

may be we should name it "CacheResponseParams"

**Comment by mohitg0795** [comment]
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/40534#-NHcOnb_1N8bbzMsodXJ:-NHcOnb_1N8bbzMsodXK:bhs3tpt) ([raw file](https://github.com/harness/harness-core/blob/57f0a54d4e5ad4bfd0ce13865dd5861b08cee26e/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L116)):*
> ```protobuf
>   string connectorRef = 5;
>   ScopeIdentifiers scopeIdentifiers = 6;
>   bool loadFromCache = 7;
> ```

never break sequence in proto. Always add at the end whatever are the new fields.

**Comment by mohitg0795** [comment]
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/40534#-NHcOw6Y06eh7J1NibSt:-NHcOw6Y06eh7J1NibSu:b-mz5p4l) ([raw file](https://github.com/harness/harness-core/blob/57f0a54d4e5ad4bfd0ce13865dd5861b08cee26e/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L116)):*
> ```protobuf
>   string connectorRef = 5;
>   ScopeIdentifiers scopeIdentifiers = 6;
>   bool loadFromCache = 7;
> ```

Lets create CacheRequestParams also and put "use-cache" inside it. We can add more params later on if required.

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 141 at r2](https://reviewable.io/reviews/harness/harness-core/40534#-NHcPnQw5FYpJH2QlC2q:-NHcPnQw5FYpJH2QlC2r:bfiulgf) ([raw file](https://github.com/harness/harness-core/blob/57f0a54d4e5ad4bfd0ce13865dd5861b08cee26e/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L141)):*
> ```Java
>       }
>       if (loadFromCache) {
>         scmGitMetaData.setCacheResponse(getCacheResponseFromGitProtoResponse(getFileResponse.getCacheResponse()));
> ```

we shouldn't be calling it explicitly. It should be part of method "getScmGitMetadataFromGitProtoResponse."

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40534)* status: 12 file(s) to review. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitEntityFindInfoDTO.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/40534#-NHcNpFc0LHVqbZMBUSG:-NHcQdwo9Tg-7kp6LrKe:bm6tm0p) ([raw file](https://github.com/harness/harness-core/blob/57f0a54d4e5ad4bfd0ce13865dd5861b08cee26e/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitEntityFindInfoDTO.java#L55)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why are we changing descriptions here when params are already hidden?
</blockquote></details>

When this was added the description was wrong, recently Viviek Dixit pointed this out, so thought of updating it as well.
___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 141 at r2](https://reviewable.io/reviews/harness/harness-core/40534#-NHcPnQw5FYpJH2QlC2q:-NHcZi3vEDNSnKYlKkNI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/57f0a54d4e5ad4bfd0ce13865dd5861b08cee26e/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L141)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we shouldn't be calling it explicitly. It should be part of method "getScmGitMetadataFromGitProtoResponse."
</blockquote></details>

Done.
___
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/40534#-NHcOnb_1N8bbzMsodXJ:-NHcRQrQEF3aDMccc21U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/57f0a54d4e5ad4bfd0ce13865dd5861b08cee26e/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L116)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

never break sequence in proto. Always add at the end whatever are the new fields.
</blockquote></details>

Done.
___
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/40534#-NHcOw6Y06eh7J1NibSt:-NHcRhB7-snAnJmU0YtL:b-wo6wgs) ([raw file](https://github.com/harness/harness-core/blob/57f0a54d4e5ad4bfd0ce13865dd5861b08cee26e/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L116)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets create CacheRequestParams also and put "use-cache" inside it. We can add more params later on if required.
</blockquote></details>

Done.
just that in proto variables names we cant have '-', have named it useCache
___
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 265 at r2](https://reviewable.io/reviews/harness/harness-core/40534#-NHcOcLFClZc2LdTwrrv:-NHcTKzx8A9-WR-BJ17d:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/57f0a54d4e5ad4bfd0ce13865dd5861b08cee26e/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L265)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

may be we should name it "CacheResponseParams"
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitEntityFindInfoDTO.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/40534#-NHcNpFc0LHVqbZMBUSG:-NHc_5qMDR-HzoJaZNf-:b8rc8vq) ([raw file](https://github.com/harness/harness-core/blob/57f0a54d4e5ad4bfd0ce13865dd5861b08cee26e/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitEntityFindInfoDTO.java#L55)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

When this was added the description was wrong, recently Viviek Dixit pointed this out, so thought of updating it as well.
</blockquote></details>

No, lets ignore it please. This is not in use. We will fix it properly when its required.

**Comment by mohitg0795** [comment]
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 288 at r3](https://reviewable.io/reviews/harness/harness-core/40534#-NHc_McbCRVhdKC9Hkhk:-NHc_McbCRVhdKC9Hkhl:btxafon) ([raw file](https://github.com/harness/harness-core/blob/2f4ec037b6f9ba6a29a0634c3887533890a8ee70/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L288)):*
> ```protobuf
>   TEMPLATE = 1;
>   PIPELINE_INPUT_SETS = 2;
>   UNKNOWN = 3;
> ```

Lets make UNKNOWN as 0. It will help to have a continuous sequence as more entities get onboarded.

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 127 at r3](https://reviewable.io/reviews/harness/harness-core/40534#-NHc_bybBdhTdfdVvfQE:-NHc_bybBdhTdfdVvfQF:bg1m8am) ([raw file](https://github.com/harness/harness-core/blob/2f4ec037b6f9ba6a29a0634c3887533890a8ee70/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L127)):*
> ```Java
> 
>       ScmGitMetaData scmGitMetaData;
>       if (loadFromCache && getFileResponse.hasCacheResponse()) {
> ```

why are we dependent on "load from cache" field here? Irrespective of anything, we should just check if response has cache response params or not and populate it.

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 426 at r3](https://reviewable.io/reviews/harness/harness-core/40534#-NHca-EE1n1VBSn93vDI:-NHca-EE1n1VBSn93vDJ:b-w228un) ([raw file](https://github.com/harness/harness-core/blob/2f4ec037b6f9ba6a29a0634c3887533890a8ee70/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L426)):*
> ```Java
>       return CacheState.VALID_CACHE;
>     }
>     return null;
> ```

lets return UNKNOWN here. Its like if someone calls this method that we expect it to be valid or UNKNOWN.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40534)* status: 12 file(s) to review. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 127 at r3](https://reviewable.io/reviews/harness/harness-core/40534#-NHc_bybBdhTdfdVvfQE:-NHcbF8aD7kyX_l-AiuF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2f4ec037b6f9ba6a29a0634c3887533890a8ee70/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L127)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why are we dependent on "load from cache" field here? Irrespective of anything, we should just check if response has cache response params or not and populate it.
</blockquote></details>

Done.
___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 426 at r3](https://reviewable.io/reviews/harness/harness-core/40534#-NHca-EE1n1VBSn93vDI:-NHcaMlrDDAcFN-YbgZ2:b-t77xc3) ([raw file](https://github.com/harness/harness-core/blob/2f4ec037b6f9ba6a29a0634c3887533890a8ee70/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L426)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets return UNKNOWN here. Its like if someone calls this method that we expect it to be valid or UNKNOWN.
</blockquote></details>

agreed
___
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 288 at r3](https://reviewable.io/reviews/harness/harness-core/40534#-NHc_McbCRVhdKC9Hkhk:-NHcbi_WAgpJg5FOh1-s:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2f4ec037b6f9ba6a29a0634c3887533890a8ee70/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L288)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets make UNKNOWN as 0. It will help to have a continuous sequence as more entities get onboarded.
</blockquote></details>

Done.
___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitEntityFindInfoDTO.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/40534#-NHcNpFc0LHVqbZMBUSG:-NHcazDdD-r5Sr5Ghfaq:bb7m07t) ([raw file](https://github.com/harness/harness-core/blob/57f0a54d4e5ad4bfd0ce13865dd5861b08cee26e/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitEntityFindInfoDTO.java#L55)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

No, lets ignore it please. This is not in use. We will fix it properly when its required.
</blockquote></details>

okay

**Comment by adivishy1** [comment]
trigger codebasehash

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 4 of 11 files at r1, 2 of 4 files at r2, 1 of 3 files at r3, 2 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40534)* status: :shipit: complete! ✓

**Pull request merged**
