### PR TITLE
fix: [PLG-1719]: Recommendation logic fixes

### PR DESCRIPTION
**Pull request by thomas-grasman**
## Describe your changes
Fix for null reference error when moduleLicense.licenseType is empty.
Leveraged ModuleLicenseHelper to check for licenseType.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44022)

### CODE REVIEW

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44022)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by thomas-grasman** [comment]
trigger messagecheck

**Review by kapil-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44022)* status: Some of the checks are too old. 

___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/44022#-NOhgZjqA1FS98cqvH-z:-NOhgZjqA1FS98cqvH0-:biszhhl) ([raw file](https://github.com/harness/harness-core/blob/b558f3e07e4ff608d49f24f71124b1f7ccb6251b/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java#L117)):*
> ```Java
>     EnumMap<UsageKey, Long> recommendedValues = new EnumMap<>(UsageKey.class);
> 
>     if (ModuleLicenseState.ACTIVE_ENTERPRISE_PAID.equals(latestLicenseState)
> ```

you can import the enum value itself and use that in this logic in order to make the code neat.
import ModuleLicenseState.ACTIVE_ENTERPRISE_PAID
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/44022#-NOhgpZH6AcaPkEbGIP6:-NOhgpZH6AcaPkEbGIP7:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/b558f3e07e4ff608d49f24f71124b1f7ccb6251b/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java#L125)):*
> ```Java
>       recommendedValues.put(UsageKey.NUMBER_OF_USERS, (long) recommendedUsers);
>       recommendedValues.put(UsageKey.NUMBER_OF_MAUS, (long) recommendedMAUs);
>     } else if (ModuleLicenseState.ACTIVE_ENTERPRISE_TRIAL.equals(latestLicenseState)
> ```

same here

**Review by Xin-Harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44022)* status: 1 of 2 approvals obtained.

**Review by kapil-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44022#-:-NOuQxho7bnPkC4go0U3:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by kapil-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44022)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44022)* status: :shipit: complete! ✓

**Pull request merged**
