### PR TITLE
[feat]: [CCM-8834]: AWS connector changes for GovCloud support

### PR DESCRIPTION
**Pull request by abhijeet-harness**
## Describe your changes
The changes are related to adding GovCloud Support for **CEAws connector** only.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37072)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37072)

**Comment by abhijeet-harness** [comment]
trigger messagecheck

**Comment by abhijeet-harness** [comment]
trigger codebasehash

**Review by nikunj-badjatya — APPROVED** [review]
> Reviewed 11 of 14 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37072)* status: :shipit: complete! ✓

**Review by nikunj-badjatya — APPROVED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37072)* status: :shipit: complete! ✓

**Comment by abhijeet-harness** [comment]
@abhinav-harness Can you approve this? CodeBaseHash is failing. However, there're no delegate related changes.

**Comment by abhijeet-harness** [comment]
Is it new task type? (If yes, no need to answer 2 then)
**NO.**

Did you add a new class which is added in kryo serialization - **No**.
if yes then do not use that class in any of the delegate task payload till it makes to delegate release

Did you make changes to the code in a backward-compatible manner?
**YES**
-will the new version of the delegate receive old version task and process? 
-If new version of the manager receives response for the old task will it be able to handle it successfully? 

Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager
- No change to delegate task

If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay
-Yes

if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay
-Yes

Did you remove an enum → this is not backward compatible yet (tracked by [DEL-3648: Move to name based kryo serializer for delegate/manager communicationIN PROGRESS](https://harness.atlassian.net/browse/DEL-3648) ) - **NO**

Did you add an enum? - **NO**

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 5 of 14 files at r1, 2 of 3 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37072)* status: :shipit: complete! ✓

**Pull request merged**
