### PR TITLE
fix: [CDS-48409]: adding valuesPaths as File entity to get Entity Referenced By in Harness Store.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42827)

### CODE REVIEW

**Comment by GoelPratyush99** [comment]
trigger checkstylecodeformat

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42827)* status: 19 file(s) to review. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 699 at r1](https://reviewable.io/reviews/harness/harness-core/42827#-NM9GqcC5FIaKyEVQDXZ:-NM9i156CyIpjaFJNz43:b-f9dudu) ([raw file](https://github.com/harness/harness-core/blob/e6026a36d8c791564ceb3f0845a36d569c1125dd/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L699)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

is this part of filestore change?
</blockquote></details>

My bad. I have reverted them.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmValidationHandler.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/42827#-NM9GutW96k6SRSD-95V:-NM9i4PF73LJpyDQJHle:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e6026a36d8c791564ceb3f0845a36d569c1125dd/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmValidationHandler.java#L58)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

same, why OCI change is here?
</blockquote></details>

done

**Review by acasian-harness — APPROVED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42827)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42827#-:-NM9nGf37IVXx6zSeYgL:bnfp4nl)* status: 19 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42827#-:-NM9nYFCDHPTM5IEOeKR:bnfp4nl)* status: 19 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42827)* status: :shipit: complete! ✓

**Pull request merged**
