### PR TITLE
feat: [DEL-5895]: Store delegate token value encrypted in DB

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes

Summary
- Store delegate token value as encrypted record instead plain text
- Encrypt token via GCP KMS.
- https://harness.atlassian.net/wiki/spaces/DEL/pages/21303197892/Secure+Delegate+Token+in+DB

Test cases
- Install CG and NG delegate for K8, docker, shell, verify HB and run end to end task flow.
- Verify encrypted token record in DB 
- Older version delegate sanity,  Install CG and NG delegate, verify HB and run end-to-end task flow.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43898)

### CODE REVIEW

**Comment by jennyjames21** [comment]
New custom Token created and verified in UI and DB
image
image

**Comment by jennyjames21** [comment]
Sanity Test- 
image
image
image

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 1 of 7 files at r1, 2 of 5 files at r3, 4 of 5 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43898)* status: :shipit: complete! ✓

**Review by xingchi-jin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43898)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 328 at r6](https://reviewable.io/reviews/harness/harness-core/43898#-NOQdn-rDVwAGvt_rr4C:-NOQdn-rDVwAGvt_rr4D:bbw9q2y) ([raw file](https://github.com/harness/harness-core/blob/74cf844f44a2d6885d7c155f9f150fb801a5b0ee/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L328)):*
> ```Java
>   @Override
>   public String decrypt(DelegateToken delegateToken) {
>     if (!featureFlagService.isEnabled(FeatureName.DELEGATE_TOKEN_ENCRYPTION, delegateToken.getAccountId())) {
> ```

why check this again while it's already checked in function getDelegateTokenValue ? 

maybe remove it here, because FF checks are biz logic. keep decrypt only does decrypt 
___
*[`400-rest/src/main/java/io/harness/service/impl/DelegateTokenServiceImpl.java` line 57 at r6](https://reviewable.io/reviews/harness/harness-core/43898#-NOQgLtUCy-YADtL3IR5:-NOQgLtUCy-YADtL3IR6:b-m8j1o0) ([raw file](https://github.com/harness/harness-core/blob/74cf844f44a2d6885d7c155f9f150fb801a5b0ee/400-rest/src/main/java/io/harness/service/impl/DelegateTokenServiceImpl.java#L57)):*
> ```Java
>   @Override
>   public DelegateTokenDetails createDelegateToken(String accountId, String name) {
>     String token = encodeBase64(Misc.generateSecretKey());
> ```

why 64 encode cg tokens ? 
___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java` line 94 at r6](https://reviewable.io/reviews/harness/harness-core/43898#-NOQeiuXCnfGdliud0vn:-NOQeiuXCnfGdliud0vo:b69hpgs) ([raw file](https://github.com/harness/harness-core/blob/74cf844f44a2d6885d7c155f9f150fb801a5b0ee/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java#L94)):*
> ```Java
>   @Encrypted(fieldName = "tokenValue") private char[] tokenValue;
> 
>   @JsonIgnore @JsonView(JsonViews.Internal.class) @SchemaIgnore private String encryptedTokenValue;
> ```

qq to help me understand, why having this field while the tokenValue field is there 
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 269 at r6](https://reviewable.io/reviews/harness/harness-core/43898#-NOQ_I31C3aeNylTLuGq:-NOQ_I31C3aeNylTLuGr:b-89erdt) ([raw file](https://github.com/harness/harness-core/blob/74cf844f44a2d6885d7c155f9f150fb801a5b0ee/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L269)):*
> ```Java
>   HELM_VERSION_3_8_0,
>   DELEGATE_ENABLE_DYNAMIC_HANDLING_OF_REQUEST("Enable dynamic handling of task request", HarnessTeam.DEL),
>   DELEGATE_TOKEN_ENCRYPTION("Store encrypted delegate token in DB", HarnessTeam.DEL),
> ```

nit: this is about read encrypted tokens

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 328 at r6](https://reviewable.io/reviews/harness/harness-core/43898#-NOQdn-rDVwAGvt_rr4C:-NOQhqAz0MdrmHir8u_g:b6i5qeb) ([raw file](https://github.com/harness/harness-core/blob/74cf844f44a2d6885d7c155f9f150fb801a5b0ee/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L328)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

why check this again while it's already checked in function getDelegateTokenValue ? 

maybe remove it here, because FF checks are biz logic. keep decrypt only does decrypt 
</blockquote></details>

it's used in while downloading delegate, but i think we can their directly. I will update and test

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/service/impl/DelegateTokenServiceImpl.java` line 57 at r6](https://reviewable.io/reviews/harness/harness-core/43898#-NOQgLtUCy-YADtL3IR5:-NOQi_TQ5ROBGnaA4t-u:bmcfut5) ([raw file](https://github.com/harness/harness-core/blob/74cf844f44a2d6885d7c155f9f150fb801a5b0ee/400-rest/src/main/java/io/harness/service/impl/DelegateTokenServiceImpl.java#L57)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

why 64 encode cg tokens ? 
</blockquote></details>

yes not needed. This is for the new cg token. Any reason we dont base64encoded for CG?

**Comment by jennyjames21** [comment]
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java` line 94 at r6](https://reviewable.io/reviews/harness/harness-core/43898#-NOQeiuXCnfGdliud0vn:-NOQinB-1bXylIUpZorc:b-o8jgy0) ([raw file](https://github.com/harness/harness-core/blob/74cf844f44a2d6885d7c155f9f150fb801a5b0ee/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java#L94)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

qq to help me understand, why having this field while the tokenValue field is there 
</blockquote></details>

we have a framework that does the underlying task of encrypting value. 
So if the field is annotated with @Encrypted, then the framework will add encrypted value reference to the second field(encryptedTokenValue, a reference to Encrypted Record collection). The actual encrypted value is in the EncryptedRecord entity. Refer my screenshot 
Good thing about this is that all encrypted value belongs to one collection, the rest of the collection points reference this. Also less code considering we need to encrypt fields across the harness

**Comment by jennyjames21** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 269 at r6](https://reviewable.io/reviews/harness/harness-core/43898#-NOQ_I31C3aeNylTLuGq:-NOQknhz9IS4Hne43BPA:be06ag1) ([raw file](https://github.com/harness/harness-core/blob/74cf844f44a2d6885d7c155f9f150fb801a5b0ee/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L269)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

nit: this is about read encrypted tokens
</blockquote></details>

yes, will update

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 149 at r5](https://reviewable.io/reviews/harness/harness-core/43898#-NOQEZYR2SbKTw_1Onys:-NOQkvIu-yXneS5-Dubg:b-wt66a8) ([raw file](https://github.com/harness/harness-core/blob/23a1f96c8e779cfc5eab068a0df2fd364b4dcdc3/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L149)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

there is a difference between ng and non ng token. How is it now with this change?
</blockquote></details>

existing ones remain the same, with no difference.  We encrypt base64 one for NG and for CG non base64encoded

**Review by xingchi-jin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43898)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/io/harness/service/impl/DelegateTokenServiceImpl.java` line 57 at r6](https://reviewable.io/reviews/harness/harness-core/43898#-NOQgLtUCy-YADtL3IR5:-NORFp3s4MjUGnqZXZVu:b-33xmy3) ([raw file](https://github.com/harness/harness-core/blob/74cf844f44a2d6885d7c155f9f150fb801a5b0ee/400-rest/src/main/java/io/harness/service/impl/DelegateTokenServiceImpl.java#L57)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

yes not needed. This is for the new cg token. Any reason we dont base64encoded for CG?
</blockquote></details>

i dont know the history, but i think we can keep  cg unchanged

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/service/impl/DelegateTokenServiceImpl.java` line 57 at r6](https://reviewable.io/reviews/harness/harness-core/43898#-NOQgLtUCy-YADtL3IR5:-NORZzlW-Bd8cA6hK1Ke:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/74cf844f44a2d6885d7c155f9f150fb801a5b0ee/400-rest/src/main/java/io/harness/service/impl/DelegateTokenServiceImpl.java#L57)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

i dont know the history, but i think we can keep  cg unchanged 
</blockquote></details>

updated

**Review by tiwaritejas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43898)* status: Some of the checks are too old. 3 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java` line 92 at r7](https://reviewable.io/reviews/harness/harness-core/43898#-NOo6WKgDCFs8MxyHFXg:-NOo6WKgDCFs8MxyHFXh:bcd243m) ([raw file](https://github.com/harness/harness-core/blob/dacf741122ce355143efdfbde7ca712c2f783104/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java#L92)):*
> ```Java
>   private DelegateEntityOwner owner;
> 
>   @Encrypted(fieldName = "tokenValue") private char[] tokenValue;
> ```

The annotation "@Encrypted" will use the secret managers in the following order of preference (decreasing):
1. Default SM
2. Global KMS
3. Local Encryptor
Hence, we should avoid using this annotation here, as we should not have the delegate token encrypted with customer's default secrets manager.

**Review by tiwaritejas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43898)* status: Some of the checks are too old. 3 file(s) to review. 2 change requests. 0 of 1 approvals obtained.

**Review by mdmilic — CHANGES_REQUESTED** [review]
Will this work for on-prem customers, i.e. what if they use AWS as their infra to install manager and other services, how are we going to encrypt token with GCP KMS in that case?

> Reviewed 2 of 5 files at r3, 4 of 5 files at r4, 2 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43898#-:-NOploiW9Lft06vNw6Sm:b-6qc4h2)* status: 3 change requests. 0 of 1 approvals obtained. Waiting on team(s): del-team. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 28 at r8](https://reviewable.io/reviews/harness/harness-core/43898#-NOpm8zb8ZsyuNHOdJBv:-NOpm8zb8ZsyuNHOdJBw:b-fdhvib) ([raw file](https://github.com/harness/harness-core/blob/77fb0aebe838854a92d928dc0a220f758cc46670/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L28)):*
> ```Java
> @OwnedBy(HarnessTeam.DEL)
> public class EncryptDelegateTokenMigration implements Migration {
>   @Inject private HPersistence persistence;
> ```

FYI it's a good practice to use constructor injection instead of field injection to make the code testable. Probably doesn't matter here since it's a one off thing, but just something to have in mind. I know our service classes often have too many fields, so sometimes not possible to move to ctor injection and you just have to follow along. Take a look at https://harness.atlassian.net/wiki/spaces/~686770990/pages/1889075203/Constructor+Injection for more info



_Code quote:_
```Java
  @Inject private HPersistence persistence;
  @Inject private DelegateNgTokenService delegateTokenService;
```
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 38 at r8](https://reviewable.io/reviews/harness/harness-core/43898#-NOpo7rz87SrhwCkDr0D:-NOpo7s0C0CBRzH-VRqN:byjqzm) ([raw file](https://github.com/harness/harness-core/blob/77fb0aebe838854a92d928dc0a220f758cc46670/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L38)):*
> ```Java
>     try (HIterator<DelegateToken> records = new HIterator<>(query.fetch())) {
>       for (DelegateToken delegateToken : records) {
>         delegateToken.setTokenValue(delegateToken.getValue().toCharArray());
> ```

Does the tokenValue automatically get encrypted because of the annotation it has? You are just reading `value` and setting the same thing to `tokenValue`
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 39 at r8](https://reviewable.io/reviews/harness/harness-core/43898#-NOpoXneA5n7ZIJRysQT:-NOpoXneA5n7ZIJRysQU:bwuuaxf) ([raw file](https://github.com/harness/harness-core/blob/77fb0aebe838854a92d928dc0a220f758cc46670/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L39)):*
> ```Java
>       for (DelegateToken delegateToken : records) {
>         delegateToken.setTokenValue(delegateToken.getValue().toCharArray());
>         persistence.save(delegateToken);
> ```

Is it possible to do bulk update instead of this. It's one off, but I feel this would still be super slow and delay manager startup because we will have thousands of writes. 
___
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 329 at r8](https://reviewable.io/reviews/harness/harness-core/43898#-NOpwfqo1Ckw58UPfKa4:-NOpwfqo1Ckw58UPfKa5:br1s5kd) ([raw file](https://github.com/harness/harness-core/blob/77fb0aebe838854a92d928dc0a220f758cc46670/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L329)):*
> ```Java
>   public String decrypt(DelegateToken delegateToken) {
>     managerDecryptionService.decrypt(delegateToken, secretManager.getEncryptionDetails(delegateToken));
>     return delegateToken.getEncryptedTokenValue();
> ```

you are decrypting, but return encrypted value? What's the use for encryptedTokenValue
___
*[`420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateServiceTokenAuthenticatorImpl.java` line 181 at r8](https://reviewable.io/reviews/harness/harness-core/43898#-NOpxBGmDHJHAsWK8Aq9:-NOpxBGmDHJHAsWK8AqA:bbdl0o4) ([raw file](https://github.com/harness/harness-core/blob/77fb0aebe838854a92d928dc0a220f758cc46670/420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateServiceTokenAuthenticatorImpl.java#L181)):*
> ```Java
>         DelegateToken delegateToken = iterator.next();
>         try {
>           decryptDelegateAuthV2Token(accountId, tokenString, delegateToken.getValue());
> ```

why this?
___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java` line 92 at r8](https://reviewable.io/reviews/harness/harness-core/43898#-NOpvdGEA4_vIR2BG5Ws:-NOpvdGEA4_vIR2BG5Wt:b-nkdiqj) ([raw file](https://github.com/harness/harness-core/blob/77fb0aebe838854a92d928dc0a220f758cc46670/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java#L92)):*
> ```Java
>   private DelegateEntityOwner owner;
> 
>   @Encrypted(fieldName = "tokenValue") private char[] tokenValue;
> ```

Since the collection is already DelegateToken, having token in the name feels redundant. Can we call it encryptedValue (btw what is the other `encryptedTokenValue` used for)?

**Pull request closed without merging**
