### PR TITLE
feat: [CI-8085]: add ci manager to redis

### PR DESCRIPTION
**Pull request by harshjain12**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48022)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`332-ci-manager/app/src/main/java/io/harness/ci/CIManagerApplication.java` line 509 at r2](https://reviewable.io/reviews/harness/harness-core/48022#-NZa63Mu3KkwZyFFJppK:-NZa63Mu3KkwZyFFJppL:b-t350ch) ([raw file](https://github.com/harness/harness-core/blob/4619712e38205424c0d2f6c8fe04409c4f2ef682/332-ci-manager/app/src/main/java/io/harness/ci/CIManagerApplication.java#L509)):*
> ```Java
>     notifyQueuePublisherRegister.register(
>         NG_ORCHESTRATION, payload -> publisher.send(singletonList(NG_ORCHESTRATION), payload));
>     notifyQueuePublisherRegister.register("ci_orchestration", injector.getInstance(CINotifyEventPublisher.class));
> ```

nit: move to constants

**Comment by sahilhindwani-harness** [comment]
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/license/impl/CILicenseServiceImpl.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/48022#-NZa6AB60vNruw_vjxhP:-NZa6AB60vNruw_vjxhQ:bqebhii) ([raw file](https://github.com/harness/harness-core/blob/4619712e38205424c0d2f6c8fe04409c4f2ef682/332-ci-manager/service/src/main/java/io/harness/ci/execution/license/impl/CILicenseServiceImpl.java#L40)):*
> ```Java
> public class CILicenseServiceImpl implements CILicenseService {
>   private final Duration RETRY_SLEEP_DURATION = Duration.ofSeconds(2);
>   private final int MAX_ATTEMPTS = 6;
> ```

why this change?

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48022)* status: Some of the checks are too old. 0 of 1 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48022)* status: Some of the checks are too old.

**Comment by harshjain12** [comment]
trigger uts

**Review by harshjain12 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48022)* status: 5 file(s) to review. 0 of 1 approvals obtained. 

___
*[`332-ci-manager/app/src/main/java/io/harness/ci/CIManagerApplication.java` line 509 at r2](https://reviewable.io/reviews/harness/harness-core/48022#-NZa63Mu3KkwZyFFJppK:-N_3Wbt785v3bBD-Ske_:btcixg7) ([raw file](https://github.com/harness/harness-core/blob/4619712e38205424c0d2f6c8fe04409c4f2ef682/332-ci-manager/app/src/main/java/io/harness/ci/CIManagerApplication.java#L509)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: move to constants
</blockquote></details>

will do it
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/license/impl/CILicenseServiceImpl.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/48022#-NZa6AB60vNruw_vjxhP:-N_3WX313pz3_v083pVI:b-tfmbh6) ([raw file](https://github.com/harness/harness-core/blob/4619712e38205424c0d2f6c8fe04409c4f2ef682/332-ci-manager/service/src/main/java/io/harness/ci/execution/license/impl/CILicenseServiceImpl.java#L40)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

why this change?
</blockquote></details>

This is for different issue which we discovered in scale testing

**Pull request merged**
