### PR TITLE
feat: [CDS-71322]: validate schema based on FF

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Describe your changes
Added static schema fetcher.
Testing: local

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48995)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger ut0

**Comment by prashantsharma04** [comment]
trigger uts

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48995)* status: 5 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java` line 815 at r4](https://reviewable.io/reviews/harness/harness-core/48995#-NXoBmYw6ZHDae4EmBsl:-NXoMNTs67cIczZ1kpY7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cc72718aa9652646c743cd3398ee4caa7cfa7324/pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java#L815)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

keep it 7 days
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java` line 825 at r4](https://reviewable.io/reviews/harness/harness-core/48995#-NXoBlO88lIXTrKyvLYw:-NXoN9DB7T_VA-AN9FBX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cc72718aa9652646c743cd3398ee4caa7cfa7324/pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java#L825)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

keep it 7 days
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 128 at r4](https://reviewable.io/reviews/harness/harness-core/48995#-NXoBwbnDXPK7Thpmudx:-NXoNAXW4fjEMtHunVwv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cc72718aa9652646c743cd3398ee4caa7cfa7324/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L128)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this is not old one right? its just static schema
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 129 at r4](https://reviewable.io/reviews/harness/harness-core/48995#-NXoCAct3JYoSjXEtfor:-NXoNAxlBw72mWfOUqO3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cc72718aa9652646c743cd3398ee4caa7cfa7324/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L129)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

You can use ResponseTimeRecorder
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 133 at r4](https://reviewable.io/reviews/harness/harness-core/48995#-NXoCGn844GG3-VqcBmM:-NXoNBln-KkDnI4zZ8CX:b-7y8ecc) ([raw file](https://github.com/harness/harness-core/blob/cc72718aa9652646c743cd3398ee4caa7cfa7324/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L133)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

did we check cache is getting hit?
</blockquote></details>

Yes cache was getting hit
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 135 at r4](https://reviewable.io/reviews/harness/harness-core/48995#-NXoCK2N2dtG5THi0NeH:-NXoQvoX0HJKZcylaoLm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cc72718aa9652646c743cd3398ee4caa7cfa7324/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L135)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do we need to read again as json, cant we store as json?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 139 at r4](https://reviewable.io/reviews/harness/harness-core/48995#-NXoCRft6ZlfBiOg-R14:-NXoQzPG3dlp0wJRTaF5:b-kgdt51) ([raw file](https://github.com/harness/harness-core/blob/cc72718aa9652646c743cd3398ee4caa7cfa7324/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L139)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

where we are making call to static schema repo url? or it will make it?
</blockquote></details>

readTree(new URL(staticYamlRepoUrl));

staticYamlRepoUrl -> contains the required info

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48995)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 130 at r6](https://reviewable.io/reviews/harness/harness-core/48995#-NXokjiSCLUhNv4hkQ8l:-NXtHnZW3BPt1xqw7VoY:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ceec030cc551018341fe13ed70e252c8fe7fb4ff/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L130)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why to use 2 times try?
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 139 at r7](https://reviewable.io/reviews/harness/harness-core/48995#-NXtHpkJEQ9SFaMlITLq:-NXtHpkJEQ9SFaMlITLr:bl6419d) ([raw file](https://github.com/harness/harness-core/blob/09a53e24253be4a8f4289f8ec71e8ebf07edfe1c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L139)):*
> ```Java
> 
>       JsonNode jsonNode = JsonPipelineUtils.getMapper().readTree(new URL(staticYamlRepoUrl));
>       staticSchemaCache.put(schemaCacheKey, jsonNode.toString());
> ```

dont use to string, JsonPipelineUtils.getJsonString

**Comment by prashantsharma04** [comment]
trigger uts

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48995)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 139 at r7](https://reviewable.io/reviews/harness/harness-core/48995#-NXtHpkJEQ9SFaMlITLq:-NXxksrmE50m6SJYSvvY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/09a53e24253be4a8f4289f8ec71e8ebf07edfe1c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L139)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dont use to string, JsonPipelineUtils.getJsonString
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48995)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48995)* status: :shipit: complete! ✓

**Comment by prashantsharma04** [comment]
trigger review

**Pull request merged**
