### PR TITLE
feat: [SRM-10049]: Create monitoredService from template UTs

### PR DESCRIPTION
**Pull request by AbhijithHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32928)

### CODE REVIEW

**Review by kjoshi12345 — DISMISSED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32928)* status: :shipit: complete! ✓

___
*[`980-commons/src/main/java/io/harness/expression/ExpressionEvaluatorUtils.java` line 240 at r1](https://reviewable.io/reviews/harness/harness-core/32928#-N1cgnX8EG48Wnr2XJAF:-N1cgnX8EG48Wnr2XJAG:b-2r08p8) ([raw file](https://github.com/harness/harness-core/blob/c7daeedd17238aeb997b955a03f4702d8b62489e/980-commons/src/main/java/io/harness/expression/ExpressionEvaluatorUtils.java#L240)):*
> ```Java
>     }
> 
>     if (o instanceof List) {
> ```

nit: I think set and list can be combined to simplify this.

**Review by kjoshi12345 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32928#-:-N1gBqxh8Z0BEI5G67Kh:bnfp4nl)* status: :shipit: complete! ✓

**Comment by AbhijithHarness** [comment]
trigger ti3

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32928#-:-N1h3MJg6Hv6f5kxWtC-:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
