### PR TITLE
[fix]: [CDS-47440]: Deployment Type immutable for service. 

### PR DESCRIPTION
**Pull request by RajBaviskar**
- Not allowing to change Deployment Type Selection for Services 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41413)

### CODE REVIEW

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41413)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by RajBaviskar** [comment]
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/41413)_ status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

added changes for upsert as well.

**Comment by RajBaviskar** [comment]
Screen Shot 2022-12-13 at 1 21 51 PM
Service Upsert/update

**Comment by RajBaviskar** [comment]
Screen Shot 2022-12-13 at 1 26 45 PM

Service update from UI

**Comment by RajBaviskar** [comment]
Screen Shot 2022-12-13 at 1 35 03 PM

Infra upsert

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41413)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 169 at r2](https://reviewable.io/reviews/harness/harness-core/41413#-NJDtXRwEIEgS4Tw3rC0:-NJDtXRwEIEgS4Tw3rC1:b-vbfxnz) ([raw file](https://github.com/harness/harness-core/blob/6f3b33cfab4a7274ae967618eafd073c760b25a3/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L169)):*
> ```Java
>           && requestInfra.getDeploymentType() != null
>           && !oldInfrastructureEntity.getDeploymentType().equals(requestInfra.getDeploymentType())) {
>         throw new InvalidRequestException(String.format("Service Deployment Type is not allowed to change."));
> ```

This message should be "Infrastructure ... " 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 221 at r2](https://reviewable.io/reviews/harness/harness-core/41413#-NJDtaMk9aCh133sYJt8:-NJDtaMk9aCh133sYJt9:b-vbfxnz) ([raw file](https://github.com/harness/harness-core/blob/6f3b33cfab4a7274ae967618eafd073c760b25a3/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L221)):*
> ```Java
>           && requestInfra.getDeploymentType() != null
>           && !oldInfrastructureEntity.getDeploymentType().equals(requestInfra.getDeploymentType())) {
>         throw new InvalidRequestException(String.format("Service Deployment Type is not allowed to change."));
> ```

This message should be "Infrastructure ... "

**Comment by RajBaviskar** [comment]
> > Reviewed 1 of 4 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/41413)_ status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 169 at r2](https://reviewable.io/reviews/harness/harness-core/41413#-NJDtXRwEIEgS4Tw3rC0:-NJDtXRwEIEgS4Tw3rC1:b-vbfxnz) ([raw file](https://github.com/harness/harness-core/blob/6f3b33cfab4a7274ae967618eafd073c760b25a3/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L169)):_
> 
> > ```java
> >           && requestInfra.getDeploymentType() != null
> >           && !oldInfrastructureEntity.getDeploymentType().equals(requestInfra.getDeploymentType())) {
> >         throw new InvalidRequestException(String.format("Service Deployment Type is not allowed to change."));
> > ```
> 
> This message should be "Infrastructure ... "
> 
> _[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 221 at r2](https://reviewable.io/reviews/harness/harness-core/41413#-NJDtaMk9aCh133sYJt8:-NJDtaMk9aCh133sYJt9:b-vbfxnz) ([raw file](https://github.com/harness/harness-core/blob/6f3b33cfab4a7274ae967618eafd073c760b25a3/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L221)):_
> 
> > ```java
> >           && requestInfra.getDeploymentType() != null
> >           && !oldInfrastructureEntity.getDeploymentType().equals(requestInfra.getDeploymentType())) {
> >         throw new InvalidRequestException(String.format("Service Deployment Type is not allowed to change."));
> > ```
> 
> This message should be "Infrastructure ... "

made the changes.

**Comment by RajBaviskar** [comment]
trigger checkstylecodeformat

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41413)* status: 4 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41413)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41413)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by RajBaviskar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41413)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/41413#-NJ6WhHqETgj3HLThJwK:-NJMwuGaBavC2BCAK5Ko:b-896fjx) (no related file):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We should also handle io.harness.ng.core.service.services.impl.ServiceEntityServiceImpl#upsert method
</blockquote></details>

Done

___

**Review by RajBaviskar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41413)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 169 at r2](https://reviewable.io/reviews/harness/harness-core/41413#-NJDtXRwEIEgS4Tw3rC0:-NJMx2puDntmklt8u5kv:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/6f3b33cfab4a7274ae967618eafd073c760b25a3/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L169)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This message should be "Infrastructure ... " 
</blockquote></details>

Done

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41413)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41413)* status: :shipit: complete! ✓

**Pull request merged**
