### PR TITLE
fix: [CDS-69466]: handle classCastException in CommandStepRollbackHelper

### PR DESCRIPTION
**Pull request by achyuth-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47951)

### CODE REVIEW

**Comment by achyuth-harness** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
We are implementing getArtifactsOutcome at different places, shouldn't lombok generate these getter automatically ?

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47951)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/47951#-NViIQ2C-zHOhkhIZAyJ:-NVmzI-Z31xE7L91Se0T:b-wf5scq) (no related file):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We are implementing getArtifactsOutcome at different places, shouldn't lombok generate these getter automatically ?
</blockquote></details>

Agree with @yogesh-chauhan try to use lombok. 

___
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java` line 166 at r1](https://reviewable.io/reviews/harness/harness-core/47951#-NVmyTI43KNdOpamdPET:-NVmyTI43KNdOpamdPEU:b-hxl3o2) ([raw file](https://github.com/harness/harness-core/blob/884451d8bee899d7037207c7bd7665d59a7c30a6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java#L166)):*
> ```Java
> 
>   private Map<String, Object> getEnvVariables(ExecutionDetails executionDetails) {
>     if (executionDetails instanceof SshWinRmStageExecutionDetails) {
> ```

This will not solve the issue. We would like to support the command step in custom deployment rollback. It means we should have one more else with 
(executionDetails instanceof DefaultExecutionDetails)
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java` line 173 at r1](https://reviewable.io/reviews/harness/harness-core/47951#-NVmzBVICJrA51Ph6dwe:-NVmzBVJ3Wb9snI-Utb0:bf26u1) ([raw file](https://github.com/harness/harness-core/blob/884451d8bee899d7037207c7bd7665d59a7c30a6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java#L173)):*
> ```Java
> 
>   private Map<String, Object> getOutVariables(ExecutionDetails executionDetails) {
>     if (executionDetails instanceof SshWinRmStageExecutionDetails) {
> ```

The same as above.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47951)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java` line 166 at r1](https://reviewable.io/reviews/harness/harness-core/47951#-NVmyTI43KNdOpamdPET:-NVo53pW8AVG8hZZftNR:b-votndo) ([raw file](https://github.com/harness/harness-core/blob/884451d8bee899d7037207c7bd7665d59a7c30a6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java#L166)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

This will not solve the issue. We would like to support the command step in custom deployment rollback. It means we should have one more else with 
(executionDetails instanceof DefaultExecutionDetails)
</blockquote></details>

I am sorry I mean CustomExecutionDetails

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47951)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/47951#-NViIQ2C-zHOhkhIZAyJ:-NVo6SRZ-ro6nUxU5S20:b-iemrgz) (no related file):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Agree with @yogesh-chauhan try to use lombok. 
</blockquote></details>

Tried with this but it doesn't override the interface's default method

___
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java` line 166 at r1](https://reviewable.io/reviews/harness/harness-core/47951#-NVmyTI43KNdOpamdPET:-NVo6YfP7ywCRRk7BYgv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/884451d8bee899d7037207c7bd7665d59a7c30a6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java#L166)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I am sorry I mean CustomExecutionDetails
</blockquote></details>

Done.

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47951)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java` line 173 at r1](https://reviewable.io/reviews/harness/harness-core/47951#-NVmzBVICJrA51Ph6dwe:-NVo6_Lt3tAo-vRC32TG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/884451d8bee899d7037207c7bd7665d59a7c30a6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java#L173)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The same as above.
</blockquote></details>

Done.

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java` line 166 at r1](https://reviewable.io/reviews/harness/harness-core/47951#-NVmyTI43KNdOpamdPET:-NVoB3YvD4XCFx7lQXLG:b-2b3afs) ([raw file](https://github.com/harness/harness-core/blob/884451d8bee899d7037207c7bd7665d59a7c30a6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java#L166)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why can't we just do executionDetails.getEnvVariables() and that method can do into the interface with default impl ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47951)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47951)* status: 7 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained.

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47951)* status: 9 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java` line 166 at r1](https://reviewable.io/reviews/harness/harness-core/47951#-NVmyTI43KNdOpamdPET:-NVoIDW90hg8zkbIXytT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/884451d8bee899d7037207c7bd7665d59a7c30a6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java#L166)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

why can't we just do executionDetails.getEnvVariables() and that method can do into the interface with default impl ?
</blockquote></details>

Done.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/spot/elastigroup/ElastigroupStageExecutionDetails.java` line 51 at r5](https://reviewable.io/reviews/harness/harness-core/47951#-NVoIek_-cnKS5UIgw0o:-NVoIek_-cnKS5UIgw0p:bhimzm4) ([raw file](https://github.com/harness/harness-core/blob/97614da0b72fd2ea6fc8590101303018e7baa4c8/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/spot/elastigroup/ElastigroupStageExecutionDetails.java#L51)):*
> ```Java
>   public Map<String, Object> getOutVariables() {
>     return Collections.emptyMap();
>   }
> ```

any reason we are not doing default methods in the interface ?

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47951)* status: 9 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/spot/elastigroup/ElastigroupStageExecutionDetails.java` line 51 at r5](https://reviewable.io/reviews/harness/harness-core/47951#-NVoIek_-cnKS5UIgw0o:-NVoLk77ERo-WKWeTR4R:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/97614da0b72fd2ea6fc8590101303018e7baa4c8/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/spot/elastigroup/ElastigroupStageExecutionDetails.java#L51)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

any reason we are not doing default methods in the interface ?
</blockquote></details>

Done

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 8 of 8 files at r5, 7 of 8 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47951)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47951)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
trigger ut0

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 7 of 8 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47951#-:-NW1VdnD9HDamML2LssW:bnfp4nl)* status: :shipit: complete! ✓

**Comment by achyuth-harness** [comment]
trigger review

**Pull request merged**
