### PR TITLE
feat: [IDP-191]: Add support to handle decrypted environment variable

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44137)

### CODE REVIEW

**Review by deepharness — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44137)* status: 6 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/secret/service/EnvironmentSecretServiceImpl.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/44137#-NOmpA0dAz4rCBDmuLf0:-NOmpA0dAz4rCBDmuLf1:b-1ufnef) ([raw file](https://github.com/harness/harness-core/blob/5dd917d5eafca8f235596794dbc86efb1b9877d7/idp-service/service/src/main/java/io/harness/idp/secret/service/EnvironmentSecretServiceImpl.java#L148)):*
> ```Java
>       String envName = environmentSecret.getEnvName();
>       String secretIdentifier = environmentSecret.getSecretIdentifier();
>       if (StringUtils.isBlank(environmentSecret.getDecryptedValue())) {
> ```

Do we any UT for these checks ?

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44137)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/secret/service/EnvironmentSecretServiceImpl.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/44137#-NOmpA0dAz4rCBDmuLf0:-NOnDkiZ-TCXE8vT-K-N:bkf5g4e) ([raw file](https://github.com/harness/harness-core/blob/5dd917d5eafca8f235596794dbc86efb1b9877d7/idp-service/service/src/main/java/io/harness/idp/secret/service/EnvironmentSecretServiceImpl.java#L148)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Do we any UT for these checks ?
</blockquote></details>

We don't have any UTs for these secrets module as of now. We need this to unblock for the upcoming demo.
I will take up a separate task to add UTs for the secrets module.

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44137)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/secret/service/EnvironmentSecretServiceImpl.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/44137#-NOmpA0dAz4rCBDmuLf0:-NOnEC7zAaxH13fjMMoA:b-lfzn79) ([raw file](https://github.com/harness/harness-core/blob/5dd917d5eafca8f235596794dbc86efb1b9877d7/idp-service/service/src/main/java/io/harness/idp/secret/service/EnvironmentSecretServiceImpl.java#L148)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

We don't have any UTs for these secrets module as of now. We need this to unblock for the upcoming demo.
I will take up a separate task to add UTs for the secrets module.
</blockquote></details>

Created https://harness.atlassian.net/browse/IDP-194

**Review by deepharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44137)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by devesh-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44137)* status: :shipit: complete! ✓

**Pull request merged**
