### PR TITLE
[feat]: [PL-22112]: Added API to update global kms

### PR DESCRIPTION
**Pull request by nishantsaini20**
…pdate global kms

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30165)

### CODE REVIEW

**Review by piyush-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30165)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30165)* status: :shipit: complete! ✓

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30165)* status: :shipit: complete! ✓

___
*[360-cg-manager/src/main/java/software/wings/resources/secretsmanagement/GcpSecretsManagerResource.java, line 105 at r1](https://reviewable.io/reviews/harness/harness-core/30165#-Mu5gaCD8QPsUcwMZl75:-Mu5gaCD8QPsUcwMZl76:b-cj4p3o) ([raw file](https://github.com/harness/harness-core/blob/a944599ca534780de6a2833dfc321e3455578c24/360-cg-manager/src/main/java/software/wings/resources/secretsmanagement/GcpSecretsManagerResource.java#L105)):*
> ```Java
>   @POST
>   @Path("/global-kms")
>   @InternalApi
> ```

By @internalAPI do you mean that customers shouldn't be able to use it? If yes, then we need to add swagger annotation as well to hide it in the swagger doc. I guess there's some annotation @hidden to do so, we can check.
___
*[360-cg-manager/src/main/java/software/wings/resources/secretsmanagement/GcpSecretsManagerResource.java, line 124 at r1](https://reviewable.io/reviews/harness/harness-core/30165#-Mu5gPUaDcei5-53VE-o:-Mu5gPUaDcei5-53VE-p:baorvrw) ([raw file](https://github.com/harness/harness-core/blob/a944599ca534780de6a2833dfc321e3455578c24/360-cg-manager/src/main/java/software/wings/resources/secretsmanagement/GcpSecretsManagerResource.java#L124)):*
> ```Java
>       gcpKmsConfig.setEncryptionType(EncryptionType.GCP_KMS);
>       gcpKmsConfig.setUuid(uuid);
>       gcpKmsConfig.setUsageRestrictions(usageRestrictions);
> ```

Can we move this complete logic to create a gcp kms config to some helper or service layer? Ideally resource layer shouldn't have this complex logic.
___
*[360-cg-manager/src/main/java/software/wings/resources/secretsmanagement/GcpSecretsManagerResource.java, line 125 at r1](https://reviewable.io/reviews/harness/harness-core/30165#-Mu5fgvXErO2T5qGVYON:-Mu5fgvXErO2T5qGVYOO:bylmyfv) ([raw file](https://github.com/harness/harness-core/blob/a944599ca534780de6a2833dfc321e3455578c24/360-cg-manager/src/main/java/software/wings/resources/secretsmanagement/GcpSecretsManagerResource.java#L125)):*
> ```Java
>       gcpKmsConfig.setUuid(uuid);
>       gcpKmsConfig.setUsageRestrictions(usageRestrictions);
>       RestResponse<String> response = accountPermissionUtils.checkIfHarnessUser("User not allowed to save global KMS");
> ```

Lets put this check as the first check in the method. We don't need to do anything before checking permissions on harness user.

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30165)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 

___
*[360-cg-manager/src/main/java/software/wings/resources/secretsmanagement/GcpSecretsManagerResource.java, line 105 at r1](https://reviewable.io/reviews/harness/harness-core/30165#-Mu5gaCD8QPsUcwMZl75:-Mu690YJ82-oyDlTHmuX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a944599ca534780de6a2833dfc321e3455578c24/360-cg-manager/src/main/java/software/wings/resources/secretsmanagement/GcpSecretsManagerResource.java#L105)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

By @internalAPI do you mean that customers shouldn't be able to use it? If yes, then we need to add swagger annotation as well to hide it in the swagger doc. I guess there's some annotation @hidden to do so, we can check.
</blockquote></details>

Done.
___
*[360-cg-manager/src/main/java/software/wings/resources/secretsmanagement/GcpSecretsManagerResource.java, line 124 at r1](https://reviewable.io/reviews/harness/harness-core/30165#-Mu5gPUaDcei5-53VE-o:-Mu693fuAK84O8XAJVzY:b-g655vo) ([raw file](https://github.com/harness/harness-core/blob/a944599ca534780de6a2833dfc321e3455578c24/360-cg-manager/src/main/java/software/wings/resources/secretsmanagement/GcpSecretsManagerResource.java#L124)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can we move this complete logic to create a gcp kms config to some helper or service layer? Ideally resource layer shouldn't have this complex logic.
</blockquote></details>

Refactoring would be out of scope of this PR. Other APIs also need similar refactoring and can be taken as a separate  task.
___
*[360-cg-manager/src/main/java/software/wings/resources/secretsmanagement/GcpSecretsManagerResource.java, line 125 at r1](https://reviewable.io/reviews/harness/harness-core/30165#-Mu5fgvXErO2T5qGVYON:-Mu69LxM6Rza8DmChDLR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a944599ca534780de6a2833dfc321e3455578c24/360-cg-manager/src/main/java/software/wings/resources/secretsmanagement/GcpSecretsManagerResource.java#L125)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets put this check as the first check in the method. We don't need to do anything before checking permissions on harness user.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30165#-:-Mu6AVUj91dH8nZ579Ne:bnfp4nl)* status: 1 file(s) to review.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30165#-:-Mu6sjy98T6WRINykidN:bnfp4nl)* status: 3 file(s) to review.

**Comment by nishantsaini20** [comment]
Codebasehash change:
1) New API and related unit test cases added.
2) Changes to existing API/methods are backward compatible.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30165)* status: 3 file(s) to review.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30165#-:-MuEw8Yt2vIs49PtWjG_:bnfp4nl)* status: 2 file(s) to review.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30165)* status: :shipit: complete! ✓

**Pull request merged**
