### PR TITLE
feat: [SRM-13601]: Added SRM Licensing check for No License and CVNG_ENABLED Feature Flag

### PR DESCRIPTION
**Pull request by arpit-harness**
…NABLED FF

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42550)

### CODE REVIEW

**Comment by arpit-harness** [comment]
trigger messagecheck

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42550)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java` line 3064 at r2](https://reviewable.io/reviews/harness/harness-core/42550#-NLe1un2AlkQGwhyj0Q6:-NLe1un2AlkQGwhyj0Q7:b-k2d33c) ([raw file](https://github.com/harness/harness-core/blob/4d78c646b17bced3d1ed58eb7d30c20f03ac34a1/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java#L3064)):*
> ```Java
>   @Owner(developers = ARPITJ)
>   @Category(UnitTests.class)
>   public void testCheckLicenseForMonitoredServiceToggle_withLicense() {}
> ```

Why are these empty?

**Review by dhruv-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42550)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 1348 at r2](https://reviewable.io/reviews/harness/harness-core/42550#-NLe5_3mAhKdzNgh3NbF:-NLe5_3mAhKdzNgh3NbG:b-k0uqy4) ([raw file](https://github.com/harness/harness-core/blob/4d78c646b17bced3d1ed58eb7d30c20f03ac34a1/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L1348)):*
> ```Java
>         accountLicenseDTO = NGRestUtils.getResponse(accountLicensesCall);
>       } catch (Exception e) {
>         Log.error("Failed to fetch License data");
> ```

Why are we using this Log instance instead of log?

**Review by deepak-harness — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42550)* status: :shipit: complete! ✓

**Pull request merged**
