### PR TITLE
[fix]: [CDS-84967]: Revert Infrastructure References Deserialisation changes

### PR DESCRIPTION
**Pull request by lovish1999**
Reverts harness/harness-core#55759

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56002)

### CODE REVIEW

**Review by tchaurasiya — APPROVED** [review]

**Comment by lovish1999** [comment]
trigger gitLeaks

**Comment by lovish1999** [comment]
trigger gitleaks

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger messagecheck

**Pull request merged**
