### PR TITLE
techdebt: [DEL-5732]: move Helmchart entity out of delegate

### PR DESCRIPTION
**Pull request by raghuAtWings**
## Describe your changes
In an effort to remove mongo dependency in delegate we are doing the following

1. Moved Helmchart to 400-rest
2. created a dto with name Log in 930-delegate-tasks

**PR Tests Done**

1. end to end k8 deployment in cg
2. end to end helm deployment in cg
3. end to end shell script deployment in ng

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42457)

### CODE REVIEW

**Review by abosii-harness — COMMENTED** [review]
> Reviewed 29 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42457)* status: Some of the checks are too old. 2 file(s) to review. 0 of 1 approvals obtained.

**Review by shivamnegi94 — APPROVED** [review]

**Review by shivamnegi94 — APPROVED** [review]
> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42457)* status: Some of the checks are too old.

**Review by vcalasansh — DISMISSED** [review]
> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42457)* status: Some of the checks are too old.

**Review by sribalij — APPROVED** [review]
> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42457)* status: Some of the checks are too old.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/serializer/morphia/ManagerMorphiaRegistrar.java` line 883 at r2](https://reviewable.io/reviews/harness/harness-core/42457#-NMfCyT8BlZpzXfuvAye:-NMfCyT9DwPc24uPl4QE:b-qgqwh1) ([raw file](https://github.com/harness/harness-core/blob/665e45a7a7d07ce568e5beb0baa570f44196c3cc/400-rest/src/main/java/io/harness/serializer/morphia/ManagerMorphiaRegistrar.java#L883)):*
> ```Java
>     set.add(Log.class);
>     set.add(InstanceSyncPTInfoBackup.class);
>     set.add(HelmChart.class);
> ```

why change this from CgOrchestrationBeansMorphiaRegistrar?

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 22 of 31 files at r1, 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42457)* status: 0 of 1 approvals obtained.

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/serializer/morphia/ManagerMorphiaRegistrar.java` line 883 at r2](https://reviewable.io/reviews/harness/harness-core/42457#-NMfCyT8BlZpzXfuvAye:-NMfTNGp1GJuUSQbJ2Qf:b-h8i1e3) ([raw file](https://github.com/harness/harness-core/blob/665e45a7a7d07ce568e5beb0baa570f44196c3cc/400-rest/src/main/java/io/harness/serializer/morphia/ManagerMorphiaRegistrar.java#L883)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

why change this from CgOrchestrationBeansMorphiaRegistrar? 
</blockquote></details>

because the entity is moved from that module to 400-rest

**Review by jennyjames21 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42457)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42457)* status: :shipit: complete! ✓

**Pull request merged**
