### PR TITLE
feat: [PL-28860]: Move Account Password expiry task to iterator framework

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

Move the Account Password expiry background job to the iterator framework from the legacy Quartz framework. This feature is enabled through a feature flag and will be released for few low risk accounts initially to validate it in the Prod environment. Once its validated then it will be released to all the accounts in Prod and the feature flag will be removed. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39073)

### CODE REVIEW

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39073)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/39073#-NEuSbFA7Ds0DIh0mbX_:-NEuSbFA7Ds0DIh0mbXa:b-4kvj9b) ([raw file](https://github.com/harness/harness-core/blob/07bc24871ef4c3b60b93947c0d76d54858a9b9f8/400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java#L81)):*
> ```Java
>             .schedulingType(REGULAR)
>             .persistenceProvider(persistenceProvider)
>             .redistribute(true));
> ```

How are these options configured? acceptableNoAlertDelay, schedulingType, redistribute -- did you refer to some documentation?



_Code quote:_
```Java
            .acceptableNoAlertDelay(Duration.ofHours(12))
            .handler(this)
            .schedulingType(REGULAR)
            .persistenceProvider(persistenceProvider)
            .redistribute(true));
```
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/39073#-NEuSshjA2ZeMPjEzvZr:-NEuSshjA2ZeMPjEzvZs:b-ez1ny) ([raw file](https://github.com/harness/harness-core/blob/07bc24871ef4c3b60b93947c0d76d54858a9b9f8/400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java#L89)):*
> ```Java
>     try {
>       account = accountService.get(user.getDefaultAccountId());
>       if (featureFlagService.isEnabled(FeatureName.USE_ACCOUNT_PASSWORD_EXPIRY_ITERATOR_FW, account.getUuid())) {
> ```

here also, reduce the nested by returning early



_Code quote:_
```Java
 if 
```
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/39073#-NEuU9VxBtHTKZTIelYd:-NEuU9VxBtHTKZTIelYe:b-za5k0l) ([raw file](https://github.com/harness/harness-core/blob/07bc24871ef4c3b60b93947c0d76d54858a9b9f8/400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java#L103)):*
> ```Java
>         } else {
>           log.info(
>               "Skipping AccountPasswordExpirationCheckJob for accountId {} because auth mechanism is not User password",
> ```

nit: add user id too



_Code quote:_
```Java
 accountId {} 
```
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/39073#-NEuTG8I-wE_Q8JAAlNy:-NEuTG8I-wE_Q8JAAlNz:bxony2h) ([raw file](https://github.com/harness/harness-core/blob/07bc24871ef4c3b60b93947c0d76d54858a9b9f8/400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java#L104)):*
> ```Java
>           log.info(
>               "Skipping AccountPasswordExpirationCheckJob for accountId {} because auth mechanism is not User password",
>               account.getUuid());
> ```

How many of these info messages we will be printing? 

2 times per user in a day if auth mechanism is not supported? - probably not too much..



_Code quote:_
```Java
          log.info(
              "Skipping AccountPasswordExpirationCheckJob for accountId {} because auth mechanism is not User password",
              account.getUuid());
```
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java` line 137 at r1](https://reviewable.io/reviews/harness/harness-core/39073#-NEuUh4M4wkBlp_Ar5o7:-NEuUh4M4wkBlp_Ar5o8:b-lbkug) ([raw file](https://github.com/harness/harness-core/blob/07bc24871ef4c3b60b93947c0d76d54858a9b9f8/400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java#L137)):*
> ```Java
>   private boolean hasPasswordExpired(long passwordAgeInDays, PasswordExpirationPolicy passwordExpirationPolicy) {
>     return passwordAgeInDays >= passwordExpirationPolicy.getDaysBeforePasswordExpires();
>   }
> ```

I wish there was a simple way to preserve history while copying files in git. I found this for future reference: https://stackoverflow.com/questions/16937359/git-copy-file-preserving-history



_Code quote:_
```Java
  private boolean hasPasswordExpired(long passwordAgeInDays, PasswordExpirationPolicy passwordExpirationPolicy) {
    return passwordAgeInDays >= passwordExpirationPolicy.getDaysBeforePasswordExpires();
  }
```
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationJob.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/39073#-NEuG6OrBxc10PGXFWTC:-NEuG6OrBxc10PGXFWTD:behsgpr) ([raw file](https://github.com/harness/harness-core/blob/07bc24871ef4c3b60b93947c0d76d54858a9b9f8/400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationJob.java#L90)):*
> ```Java
>         try {
>           account = accountService.get(user.getDefaultAccountId());
>           if (featureFlagService.isNotEnabled(FeatureName.USE_ACCOUNT_PASSWORD_EXPIRY_ITERATOR_FW, account.getUuid())) {
> ```

you can reduce nesting by

if (featureFlagService.isEnabled(FeatureName.USE_ACCOUNT_PASSWORD_EXPIRY_ITERATOR_FW, account.getUuid())) {
              log.info(String.format(
                "Feature flag %s is enabled for account %s - account password expiry task will be handled by iterator framework",
                FeatureName.USE_ACCOUNT_PASSWORD_EXPIRY_ITERATOR_FW, account.getUuid()));
              continue;
}

....

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39073)* status: Some of the checks are too old. 5 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/39073#-NEuSbFA7Ds0DIh0mbX_:-NF5LN_4CCJWuA-DNClG:brqtb74) ([raw file](https://github.com/harness/harness-core/blob/07bc24871ef4c3b60b93947c0d76d54858a9b9f8/400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java#L81)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

How are these options configured? acceptableNoAlertDelay, schedulingType, redistribute -- did you refer to some documentation?
</blockquote></details>

I haven't come across any documentation on these, I just understood from the code - 

acceptableNoAlertDelay - is just used for logging purposes, if the delay for the iteration is more than acceptableNoAlertDelay then just log it.

schedulingType - REGULAR is what is needed for most of the iterators as we need each document to be processed every fixed interval (targetInterval). We use an iteration field in Mongo collections which is incremented by targetInterval for the next iteration and this will ensure that each record gets processed regularly every targetInterval. In IRREGULAR we do not set the iteration field and we just remove the field from the record, it will be inserted again the next time whenever it gets scheduled.

redistribute - This is used to take into account the time it will take for Mongo findAndModify operation to complete and adjust that time with the targetInterval to update next iteration. It has to be true if the schedulingType is REGULAR.

So for this iteration job we want `schedulingType` to be REGULAR since we want the documents to be processed periodically and `redistribute` has to be True for REGULAR schedulingType.
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/39073#-NEuSshjA2ZeMPjEzvZr:-NF5HKOi3DxKLea3bzsU:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/07bc24871ef4c3b60b93947c0d76d54858a9b9f8/400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java#L89)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

here also, reduce the nested by returning early
</blockquote></details>

Done
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/39073#-NEuU9VxBtHTKZTIelYd:-NF5GxQo1fEF1BY0SmYT:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/07bc24871ef4c3b60b93947c0d76d54858a9b9f8/400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java#L103)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

nit: add user id too
</blockquote></details>

Done
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/39073#-NEuTG8I-wE_Q8JAAlNy:-NF5Ef0NEcTh8p11F_TD:b-jbwsiy) ([raw file](https://github.com/harness/harness-core/blob/07bc24871ef4c3b60b93947c0d76d54858a9b9f8/400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java#L104)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

How many of these info messages we will be printing? 

2 times per user in a day if auth mechanism is not supported? - probably not too much..
</blockquote></details>

Yes, it will be just 2 times per day per user if Auth password mechanism is not enabled.
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java` line 137 at r1](https://reviewable.io/reviews/harness/harness-core/39073#-NEuUh4M4wkBlp_Ar5o7:-NF55O9n6QaGePL5olr_:b-4hvi0m) ([raw file](https://github.com/harness/harness-core/blob/07bc24871ef4c3b60b93947c0d76d54858a9b9f8/400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java#L137)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

I wish there was a simple way to preserve history while copying files in git. I found this for future reference: https://stackoverflow.com/questions/16937359/git-copy-file-preserving-history
</blockquote></details>

Got it.
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationJob.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/39073#-NEuG6OrBxc10PGXFWTC:-NF52N05DXEPJri7byDV:b-k0l4ur) ([raw file](https://github.com/harness/harness-core/blob/07bc24871ef4c3b60b93947c0d76d54858a9b9f8/400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationJob.java#L90)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

you can reduce nesting by

if (featureFlagService.isEnabled(FeatureName.USE_ACCOUNT_PASSWORD_EXPIRY_ITERATOR_FW, account.getUuid())) {
              log.info(String.format(
                "Feature flag %s is enabled for account %s - account password expiry task will be handled by iterator framework",
                FeatureName.USE_ACCOUNT_PASSWORD_EXPIRY_ITERATOR_FW, account.getUuid()));
              continue;
}

....

</blockquote></details>

That's neat :). Will do it.

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger messagecheck

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39073)* status: 5 file(s) to review. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/39073#-NEuSbFA7Ds0DIh0mbX_:-NFJXTM73lSIa2jErNiW:b-mfdgup) ([raw file](https://github.com/harness/harness-core/blob/07bc24871ef4c3b60b93947c0d76d54858a9b9f8/400-rest/src/main/java/software/wings/scheduler/AccountPasswordExpirationHandler.java#L81)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

I haven't come across any documentation on these, I just understood from the code - 

acceptableNoAlertDelay - is just used for logging purposes, if the delay for the iteration is more than acceptableNoAlertDelay then just log it.

schedulingType - REGULAR is what is needed for most of the iterators as we need each document to be processed every fixed interval (targetInterval). We use an iteration field in Mongo collections which is incremented by targetInterval for the next iteration and this will ensure that each record gets processed regularly every targetInterval. In IRREGULAR we do not set the iteration field and we just remove the field from the record, it will be inserted again the next time whenever it gets scheduled.

redistribute - This is used to take into account the time it will take for Mongo findAndModify operation to complete and adjust that time with the targetInterval to update next iteration. It has to be true if the schedulingType is REGULAR.

So for this iteration job we want `schedulingType` to be REGULAR since we want the documents to be processed periodically and `redistribute` has to be True for REGULAR schedulingType.
</blockquote></details>

Thanks for the explanations!

**Pull request closed without merging**
