### PR TITLE
[feat]: [CDS-74289]: Add ability to filter pipeline execution by trigger identifier and trigger type

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
## Describe your changes
Add ability to filter pipeline execution by trigger identifier and trigger type
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52611)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 418 at r1](https://reviewable.io/reviews/harness/harness-core/52611#-NdnLVyv2t6nCDp6SbmU:-NdnLVyv2t6nCDp6SbmV:bxqwqtl) ([raw file](https://github.com/harness/harness-core/blob/851a55fd7a09144a9701bfce2031a449b509e5fd/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L418)):*
> ```Java
>       addPipelineLabelsCriteria(combinedAndCriteriaList, pipelineFilter.getPipelineLabels());
>     }
>     if (EmptyPredicate.isNotEmpty(pipelineFilter.getTriggerIdentifiers())) {
> ```

Do we need index on these fields? Could you please check the explain on query once?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52611)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52611)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 418 at r1](https://reviewable.io/reviews/harness/harness-core/52611#-NdnLVyv2t6nCDp6SbmU:-NdnpSLP6RdcixN2upSG:bqwlt91) ([raw file](https://github.com/harness/harness-core/blob/851a55fd7a09144a9701bfce2031a449b509e5fd/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L418)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Do we need index on these fields? Could you please check the explain on query once?
</blockquote></details>

As discussed we wont be adding index for now

**Comment by rathodmeetsatish** [comment]
trigger uts

**Comment by rathodmeetsatish** [comment]
trigger uts

**Comment by rathodmeetsatish** [comment]
trigger uts

**Comment by rathodmeetsatish** [comment]
trigger ut0,ut2

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52611)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by vcalasansh — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52611)* status: :shipit: complete! ✓

**Comment by rathodmeetsatish** [comment]
trigger review

**Pull request merged**
