### PR TITLE
feat: [PL-23346]: principal scope in role assignments

### PR DESCRIPTION
**Pull request by karansiwach360**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31444)

### CODE REVIEW

**Review by gupta-utkarsh — APPROVED** [review]
> Reviewed 22 of 25 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31444)* status: 32 file(s) to review. 1 of 2 approvals obtained. 

___
*[access-control/contracts/api/src/main/java/io/harness/accesscontrol/principals/PrincipalDTO.java, line 28 at r1](https://reviewable.io/reviews/harness/harness-core/31444#-MyD1c6gDYZ3mgvVdMrs:-MyD1c6gDYZ3mgvVdMrt:b7xpq8k) ([raw file](https://github.com/harness/harness-core/blob/6ad7227dd5dbc63bdfa8139244673969ec09a21c/access-control/contracts/api/src/main/java/io/harness/accesscontrol/principals/PrincipalDTO.java#L28)):*
> ```Java
> @OwnedBy(PL)
> public class PrincipalDTO {
>   String scopeLevel;
> ```

scopeLevel or scopeIdentifier?
___
*[access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerServiceImpl.java, line 61 at r1](https://reviewable.io/reviews/harness/harness-core/31444#-MyD27peBnJUkdmIw6S8:-MyD27peBnJUkdmIw6S9:b-yguurs) ([raw file](https://github.com/harness/harness-core/blob/6ad7227dd5dbc63bdfa8139244673969ec09a21c/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerServiceImpl.java#L61)):*
> ```Java
>     Set<String> principals = new HashSet<>();
>     if (USER_GROUP.equals(roleAssignment.getPrincipalType())) {
>       Scope scope = toParentScope(scopeService.buildScopeFromScopeIdentifier(roleAssignment.getScopeIdentifier()),
> ```

Can this be common? Not only for User Groups?
___
*[access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/RoleAssignmentDBO.java, line 66 at r1](https://reviewable.io/reviews/harness/harness-core/31444#-MyD2REa8WP-1ia_ExfV:-MyD2REa8WP-1ia_ExfW:b-9w3945) ([raw file](https://github.com/harness/harness-core/blob/6ad7227dd5dbc63bdfa8139244673969ec09a21c/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/RoleAssignmentDBO.java#L66)):*
> ```Java
>   @NotEmpty final String roleIdentifier;
>   // @NotEmpty in next release
>   final String principalScopeLevel;
> ```

This will be empty for Users and Service Accounts right?
___
*[access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/ScopeHelper.java, line 17 at r1](https://reviewable.io/reviews/harness/harness-core/31444#-MyD2dyeBJIrgGu3BPWM:-MyD2dyeBJIrgGu3BPWN:b-kzii5p) ([raw file](https://github.com/harness/harness-core/blob/6ad7227dd5dbc63bdfa8139244673969ec09a21c/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/ScopeHelper.java#L17)):*
> ```Java
>   public static Scope toParentScope(@NotNull Scope scope, String parentScopeLevel) {
>     if (parentScopeLevel == null) {
>       return scope;
> ```

Why this should return scope?

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31444#-:-Myw3I95CyawEvqau6Et:bnfp4nl)* status: 32 file(s) to review. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31444)* status: 32 file(s) to review. 1 of 2 approvals obtained.

**Comment by karansiwach360** [comment]
trigger ft2

**Review by reetika04 — APPROVED** [review]
> Reviewed 16 of 25 files at r1, 12 of 15 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31444)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31444#-:-MzBio2W4Y5QfZCS1PJB:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
