### PR TITLE
feat: [PIE-4693]: adding prometheus for monitoring in debezium service

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36193)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger messagecheck

**Comment by shalini-agr** [comment]
trigger ti3, ti4

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36193)

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 1 of 3 files at r4, 12 of 13 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36193)* status: Some of the checks are too old. 18 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`952-debezium-engine/src/main/java/io/harness/debezium/EventsFrameworkChangeConsumer.java` line 64 at r6](https://reviewable.io/reviews/harness/harness-core/36193#-NA3VLuO7k7hqyWI8OrD:-NA3VLuO7k7hqyWI8OrE:bdd7gdy) ([raw file](https://github.com/harness/harness-core/blob/b7d6128ca311656cca2aa9f778d8efe8a337d6e5/952-debezium-engine/src/main/java/io/harness/debezium/EventsFrameworkChangeConsumer.java#L64)):*
> ```Java
>                                                     .build();
> 
>       boolean debeziumEnabled =
> ```

Won't this be costly operation as we wll query cfClient always? Should we cache it?

**Comment by sahilhindwani-harness** [comment]
*[`debezium-service/build/container/scripts/start_process.sh` line 40 at r6](https://reviewable.io/reviews/harness/harness-core/36193#-NA3VVGm1Lh2siasOoO3:-NA3VVGm1Lh2siasOoO4:bqqdmj2) ([raw file](https://github.com/harness/harness-core/blob/b7d6128ca311656cca2aa9f778d8efe8a337d6e5/debezium-service/build/container/scripts/start_process.sh#L40)):*
> ```Shell
> fi
> 
> JAVA_OPTS=$JAVA_OPTS" -javaagent:/opt/harness/jmx_prometheus_javaagent-0.17.0.jar=12345:prometheus_config.yaml"
> ```

We should wrap it under an environment variable, similar to ENABLE_APPDYNAMICS.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 3 files at r4, 12 of 13 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36193)* status: Some of the checks are too old. 1 change requests. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
*[`debezium-service/build/container/scripts/start_process.sh` line 40 at r6](https://reviewable.io/reviews/harness/harness-core/36193#-NA3VVGm1Lh2siasOoO3:-NA4-1kQ76-VuhGwdpD_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b7d6128ca311656cca2aa9f778d8efe8a337d6e5/debezium-service/build/container/scripts/start_process.sh#L40)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We should wrap it under an environment variable, similar to ENABLE_APPDYNAMICS.
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger ti0, ti1,ti2,ti3,ti4

**Comment by shalini-agr** [comment]
trigger ti0, ti1, ti2

**Pull request closed without merging**
