### PR TITLE
fix: [PL-30011]: resolved scope bug for validateSshWinRmSecretRef()

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
The scope information was incorrectly getting passed while fetching SSH Key File while validating SSH Credential. After the change, the scope information will be passed from the secretRef and not the secretDTO.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40662)

### CODE REVIEW

**Review by vitsafronovici — APPROVED** [review]

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40662)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/encryption/SecretRefHelper.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/40662#-NIB9IfZEHhgVni-JNan:-NIB9IfZEHhgVni-JNao:bqmigv7) ([raw file](https://github.com/harness/harness-core/blob/15dfb116a3d3121686982aab0b94dbde5dd6769c/970-ng-commons/src/main/java/io/harness/encryption/SecretRefHelper.java#L31)):*
> ```Java
>   }
> 
>   public BaseNGAccess getScopeIdentifierForSecretRef(
> ```

Add UT

**Comment by tiwaritejas** [comment]
trigger codeformat

**Comment by tiwaritejas** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40662)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/encryption/SecretRefHelper.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/40662#-NIB9IfZEHhgVni-JNan:-NIG3B6F95iRvUX4Eu-j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/15dfb116a3d3121686982aab0b94dbde5dd6769c/970-ng-commons/src/main/java/io/harness/encryption/SecretRefHelper.java#L31)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Add UT
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40662)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40662)* status: :shipit: complete! ✓

**Pull request merged**
