### PR TITLE
fix: [CDS-53120]: Added example payload for Infrastructure Create/update/upsert Api's

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
Have added example payload for Infrastructure Create/update/upsert Api's
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44305)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/beans/Constants.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/44305#-NOzU0UGDC2eUZgf-gOj:-NOzU0UGDC2eUZgf-gOk:b-yx9c41) ([raw file](https://github.com/harness/harness-core/blob/cdd897585188d6fc78a39562c9f1bf188307b7a3/120-ng-manager/src/main/java/io/harness/ng/core/beans/Constants.java#L18)):*
> ```Java
> @OwnedBy(CDC)
> @UtilityClass
> public class Constants {
> ```

The name of the class is very generic, it can be confusing
Can we call it something like DocumentationConstants etc

**Review by vivekkarnatiharness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44305)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/beans/Constants.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/44305#-NOzU0UGDC2eUZgf-gOj:-NP0LQ2i2tkc9vv3Md-S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cdd897585188d6fc78a39562c9f1bf188307b7a3/120-ng-manager/src/main/java/io/harness/ng/core/beans/Constants.java#L18)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

The name of the class is very generic, it can be confusing
Can we call it something like DocumentationConstants etc 
</blockquote></details>

Done.

**Review by utkarshchoubey-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44305)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by hingerabhinav — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44305)* status: 1. unresolved discussions.

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 210 at r3](https://reviewable.io/reviews/harness/harness-core/44305#-NP1FXJQAt04Eqr6gQJo:-NP1FXJQAt04Eqr6gQJp:bou95ub) ([raw file](https://github.com/harness/harness-core/blob/e25cf8b3ddac0385653c3db5ea10bc42f3481d54/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L210)):*
> ```Java
>       @RequestBody(required = true, description = "Details of the Infrastructure to be created", content = {
>         @Content(
>             examples = @ExampleObject(name = "Create", summary = "Sample Infrastructure create payload",
> ```

here we are saying sample.. create payload
In update and upsert, we are saying "sample update body" 
Lets make these consistent

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44305)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44305)* status: :shipit: complete! ✓

**Pull request merged**
