### PR TITLE
[Feat]: [CDS-35675] Adds logs to Infrastructure Step on NG

### PR DESCRIPTION
**Pull request by gitNavV**
JIRA: https://harness.atlassian.net/browse/CDS-35675

---

**Screenshots**

- Earlier
Screenshot 2022-05-26 at 7 36 05 PM

- Now
Screenshot 2022-05-27 at 1 11 38 PM

---

**Question:** Do we need UI changes for the logs to show up, as they currently aren't appearing?
**Answer:** No

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33510)

### CODE REVIEW

**Comment by gitNavV** [comment]
trigger feature-build

**Comment by gitNavV** [comment]
trigger feature-build

**Comment by gitNavV** [comment]
trigger feature-build

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33510)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 127 at r4](https://reviewable.io/reviews/harness/harness-core/33510#-N33MLxJ51QsK1rNlRUM:-N33MLxJ51QsK1rNlRUN:b-79ccvc) ([raw file](https://github.com/harness/harness-core/blob/7acd61c22e0a9fe6b0a91726f9c4de4cbd0c106e/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L127)):*
> ```Java
> 
>     NGLogCallback logCallback =
>         infrastructureStepHelper != null ? infrastructureStepHelper.getInfrastructureLogCallback(ambiance, true) : null;
> ```

why this ever be null?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 196 at r4](https://reviewable.io/reviews/harness/harness-core/33510#-N33MRCyBdo9ZzBsuXAM:-N33MRCyBdo9ZzBsuXAN:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/7acd61c22e0a9fe6b0a91726f9c4de4cbd0c106e/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L196)):*
> ```Java
>   void validateConnector(Infrastructure infrastructure, Ambiance ambiance) {
>     NGLogCallback logCallback =
>         infrastructureStepHelper != null ? infrastructureStepHelper.getInfrastructureLogCallback(ambiance) : null;
> ```

same as above



_Code quote:_
```Java
infrastructureStepHelper != null
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 245 at r4](https://reviewable.io/reviews/harness/harness-core/33510#-N33MSyB7uq02XKBKxqy:-N33MSyB7uq02XKBKxqz:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/7acd61c22e0a9fe6b0a91726f9c4de4cbd0c106e/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L245)):*
> ```Java
>   private ConnectorInfoDTO validateAndGetConnector(ParameterField<String> connectorRef, Ambiance ambiance) {
>     NGLogCallback logCallback =
>         infrastructureStepHelper != null ? infrastructureStepHelper.getInfrastructureLogCallback(ambiance) : null;
> ```

same as above



_Code quote:_
```Java
infrastructureStepHelper != null
```

**Comment by gitNavV** [comment]
> > Reviewed 1 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/33510)_ status: 1 change requests. 0 of 1 approvals obtained.
> 
> _[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 127 at r4](https://reviewable.io/reviews/harness/harness-core/33510#-N33MLxJ51QsK1rNlRUM:-N33MLxJ51QsK1rNlRUN:b-79ccvc) ([raw file](https://github.com/harness/harness-core/blob/7acd61c22e0a9fe6b0a91726f9c4de4cbd0c106e/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L127)):_
> 
> > ```java
> >     NGLogCallback logCallback =
> >         infrastructureStepHelper != null ? infrastructureStepHelper.getInfrastructureLogCallback(ambiance, true) : null;
> > ```
> 
> why this ever be null?
> 
> _[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 196 at r4](https://reviewable.io/reviews/harness/harness-core/33510#-N33MRCyBdo9ZzBsuXAM:-N33MRCyBdo9ZzBsuXAN:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/7acd61c22e0a9fe6b0a91726f9c4de4cbd0c106e/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L196)):_
> 
> > ```java
> >   void validateConnector(Infrastructure infrastructure, Ambiance ambiance) {
> >     NGLogCallback logCallback =
> >         infrastructureStepHelper != null ? infrastructureStepHelper.getInfrastructureLogCallback(ambiance) : null;
> > ```
> 
> same as above
> 
> _Code quote:_
> 
> ```java
> infrastructureStepHelper != null
> ```
> 
> _[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 245 at r4](https://reviewable.io/reviews/harness/harness-core/33510#-N33MSyB7uq02XKBKxqy:-N33MSyB7uq02XKBKxqz:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/7acd61c22e0a9fe6b0a91726f9c4de4cbd0c106e/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L245)):_
> 
> > ```java
> >   private ConnectorInfoDTO validateAndGetConnector(ParameterField<String> connectorRef, Ambiance ambiance) {
> >     NGLogCallback logCallback =
> >         infrastructureStepHelper != null ? infrastructureStepHelper.getInfrastructureLogCallback(ambiance) : null;
> > ```
> 
> same as above
> 
> _Code quote:_
> 
> ```java
> infrastructureStepHelper != null
> ```

In case of Junits. @archit-harness

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 1 of 3 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33510)* status: 1 change requests. 1. unresolved discussions.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33510)* status: :shipit: complete! ✓
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 127 at r4](https://reviewable.io/reviews/harness/harness-core/33510#-N33MLxJ51QsK1rNlRUM:-N33csndCT2Z1LAKBahE:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/7acd61c22e0a9fe6b0a91726f9c4de4cbd0c106e/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L127)):*

<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>
why this ever be null?
</blockquote></details>
Added mock `InfrastructureStepHelper` and removed check in d3129a59c33a57eaac4ed23abda6768f28c93aca.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 196 at r4](https://reviewable.io/reviews/harness/harness-core/33510#-N33MRCyBdo9ZzBsuXAM:-N33ct_UEneUAxWiSg4r:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/7acd61c22e0a9fe6b0a91726f9c4de4cbd0c106e/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L196)):*

<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>
same as above
</blockquote></details>
Added mock `InfrastructureStepHelper` and removed check in d3129a59c33a57eaac4ed23abda6768f28c93aca.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 245 at r4](https://reviewable.io/reviews/harness/harness-core/33510#-N33MSyB7uq02XKBKxqy:-N33cu6ND7KPuVw23qkZ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/7acd61c22e0a9fe6b0a91726f9c4de4cbd0c106e/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L245)):*

<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>
It should not be handled in code, You can use @mock annotation and inject into your step and mimick what you are expecting. Example - NGTriggerElementMapperTest
</blockquote></details>
Added mock `InfrastructureStepHelper` and removed check in d3129a59c33a57eaac4ed23abda6768f28c93aca.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33510)* status: :shipit: complete! ✓

**Pull request merged**
