### PR TITLE
[feat]:[pie-6615]: getPipeline cache response BE contract

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Adding cache response in the getPipeline api BE contract

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40599)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40599)* status: :shipit: complete! ✓

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/40599#-NHdY9Tm7wolIu57NlsR:-NHdY9Tn2CAHFXlTpQgk:bx4zv6j) ([raw file](https://github.com/harness/harness-core/blob/fb751c69d53631acdd0fe993840c6432c747c5f2/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java#L43)):*
> ```Java
>   YamlSchemaErrorWrapperDTO yamlSchemaErrorWrapper;
>   ValidateTemplateInputsResponseDTO validateTemplateInputsResponse;
>   CacheResponseDTO cacheResponse;
> ```

I think we should name it CacheResponseParamsDTO

**Review by mohitg0795 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40599)* status: :shipit: complete! ✓

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40599)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/40599#-NHdY9Tm7wolIu57NlsR:-NHdYVVi-UceJUiEULGR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fb751c69d53631acdd0fe993840c6432c747c5f2/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java#L43)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we should name it CacheResponseParamsDTO
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40599)* status: 1. unresolved discussions.

**Comment by adivishy1** [comment]
trigger messagecheck

**Comment by adivishy1** [comment]
trigger messagecheck

**Comment by AnshuH** [comment]
trigger messagecheck

**Comment by adivishy1** [comment]
trigger copyrightcheck

**Comment by AnshuH** [comment]
trigger copyrightcheck

**Comment by adivishy1** [comment]
trigger checkstylecodeformat

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40599)* status: 1. unresolved discussions.

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40599#-:-NHhIPJt06qdaaB3Rvu9:bnfp4nl)* status: 1. unresolved discussions.

**Review by naidu-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40599)* status: 1. unresolved discussions.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40599)* status: 1. unresolved discussions.

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40599)* status: :shipit: complete! ✓

**Pull request merged**
