### PR TITLE
techdebt: [CDS-37180]: serverless command units

### PR DESCRIPTION
**Pull request by PragyeshMishra01**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33336)

### CODE REVIEW

**Comment by PragyeshMishra01** [comment]
trigger feature-build

**Comment by PragyeshMishra01** [comment]
trigger feature-build

**Comment by PragyeshMishra01** [comment]
trigger ti0

**Comment by PragyeshMishra01** [comment]
trigger ti2

**Review by piyush-bhuwalka — APPROVED** [review]
LGTM

**Review by sainath-b — APPROVED** [review]

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger messagecheck

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger messagecheck

**Review by sainath-b — APPROVED** [review]

**Review by sainath-b — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33336)* status: :shipit: complete! ✓

**Comment by piyush-bhuwalka** [comment]
trigger messagecheck

**Pull request merged**
