### PR TITLE
fix: [PL-22204]: Validating the git repo check before enabling the git sync

### PR DESCRIPTION
**Pull request by goelsatyam2**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)

### CODE REVIEW

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 654 at r1](https://reviewable.io/reviews/harness/harness-core/30821#-MwQGdKL9tL-8-2mc2iZ:-MwQGdKL9tL-8-2mc2i_:byjprr9) ([raw file](https://github.com/harness/harness-core/blob/dcb80ac1b9d5fed65760e1f39a2458167d533c04/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L654)):*
> ```Java
>             ygs.getGitConnectorRef(), getDecodedString(ygs.getRepo()));
>     // only throw exception if the status is not success and minimum one error is returned
>     if (result.getStatus() != ConnectivityStatus.SUCCESS && result.getErrors().size() > 0) {
> ```

null check on result.getErrors

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 649 at r1](https://reviewable.io/reviews/harness/harness-core/30821#-MwQGHZf8Jn4tnTJPoRx:-MwQGHZf8Jn4tnTJPoRy:b-74d8lg) ([raw file](https://github.com/harness/harness-core/blob/dcb80ac1b9d5fed65760e1f39a2458167d533c04/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L649)):*
> ```Java
>   // checks if there is any error while connecting to git repo
>   // throws invalid request exception if any error occurred
>   private void checkGitRepoConnection(YamlGitConfigDTO ygs) {
> ```

@goelsatyam2 @bhavya181 can this be moved to a util method? It seems to be a generic utility check. And argument list can be modified to just take required inputs.

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 654 at r1](https://reviewable.io/reviews/harness/harness-core/30821#-MwQGmoa7AR81W0Ln0Qm:-MwQGmoa7AR81W0Ln0Qn:bxn6q2a) ([raw file](https://github.com/harness/harness-core/blob/dcb80ac1b9d5fed65760e1f39a2458167d533c04/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L654)):*
> ```Java
>             ygs.getGitConnectorRef(), getDecodedString(ygs.getRepo()));
>     // only throw exception if the status is not success and minimum one error is returned
>     if (result.getStatus() != ConnectivityStatus.SUCCESS && result.getErrors().size() > 0) {
> ```

Once result.getStatus() is not success, that should be enough to fail the check. Why do we need to check error list here?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: Some of the checks are too old. 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 649 at r1](https://reviewable.io/reviews/harness/harness-core/30821#-MwQGHZf8Jn4tnTJPoRx:-MwQKYer23iFumev9LY9:b-81xomh) ([raw file](https://github.com/harness/harness-core/blob/dcb80ac1b9d5fed65760e1f39a2458167d533c04/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L649)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@goelsatyam2 @bhavya181 can this be moved to a util method? It seems to be a generic utility check. And argument list can be modified to just take required inputs.
</blockquote></details>

There is a method validateTheGitConfigInput in SaveInternal, call this method from there, I think it's ok to put it here only, as this is only used while saving repo.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 654 at r1](https://reviewable.io/reviews/harness/harness-core/30821#-MwQGmoa7AR81W0Ln0Qm:-MwQKVWa4QveJeCouPQm:bh448rr) ([raw file](https://github.com/harness/harness-core/blob/dcb80ac1b9d5fed65760e1f39a2458167d533c04/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L654)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Once result.getStatus() is not success, that should be enough to fail the check. Why do we need to check error list here?
</blockquote></details>

I agree with Mohit

**Comment by abhinav-harness** [comment]
general note: 
Comments in java should be used only when necessary.

**Review by mohitg0795 — COMMENTED** [review]
+1, some comments seem quite generic in this PR. @goelsatyam2 lets try to reduce redundant comments.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821#-:-MwQREHU3ALEvo6L2QpB:bkeke0c)* status: Some of the checks are too old. 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: Some of the checks are too old. 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained.

**Comment by goelsatyam2** [comment]
> 

i added this getErrorCheck because if status is UNKNOWN or PARTIAL, and getErrors list is empty then then what error we are going to show user? Because we ourselves don't know the error

**Comment by mohitg0795** [comment]
Yes, we can say something generic in that case. The idea is we can't skip throwing an error in case connector connection doesn't give us error but says it failed.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821#-:-MwjT6Sn39od8vAL9oAT:bnfp4nl)* status: :shipit: complete! ✓

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by goelsatyam2 — COMMENTED** [review]
> Reviewed 1 of 3 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Review by goelsatyam2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: 3 file(s) to review. 0 of 2 approvals obtained.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 640 at r9](https://reviewable.io/reviews/harness/harness-core/30821#-Mx3e4l79tkcv8islpiG:-Mx3e4l79tkcv8islpiH:b2dz73l) ([raw file](https://github.com/harness/harness-core/blob/1a5333994d5785e1fe737ce1bf58b6cc1e97dc3f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L640)):*
> ```Java
>     List<String> branches = scmFacilitatorService.listBranchesUsingConnector(identifierRef.getAccountIdentifier(),
>         ygs.getOrganizationIdentifier(), ygs.getProjectIdentifier(), ygs.getGitConnectorRef(),
>         getDecodedString(ygs.getRepo()), null, null);
> ```

@goelsatyam2 lets remove this usage of pagerequest and search term from the API. Passing null in both places looks ugly and error prone. And I checked, its not used anywhere going forward into the API, so we can remove these fields itself and refactor some stuff.



_Code quote:_
```Java
listBranchesUsingConnector
```
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 643 at r9](https://reviewable.io/reviews/harness/harness-core/30821#-Mx3ePGF0PFKQ_V98Hwq:-Mx3ePGF0PFKQ_V98Hwr:b-w7upuk) ([raw file](https://github.com/harness/harness-core/blob/1a5333994d5785e1fe737ce1bf58b6cc1e97dc3f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L643)):*
> ```Java
> 
>     if (isEmpty(branches) || !branches.contains(ygs.getBranch())) {
>       throw new InvalidRequestException(String.format("error while checking the branch. Branch doesn't exists."));
> ```

How do we get to know if repo is an issue here? It will only always say that branch is not found?

**Review by goelsatyam2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 640 at r9](https://reviewable.io/reviews/harness/harness-core/30821#-Mx3e4l79tkcv8islpiG:-Mx3fhcj1rssEHtgUxXk:b-zdstjv) ([raw file](https://github.com/harness/harness-core/blob/1a5333994d5785e1fe737ce1bf58b6cc1e97dc3f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L640)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@goelsatyam2 lets remove this usage of pagerequest and search term from the API. Passing null in both places looks ugly and error prone. And I checked, its not used anywhere going forward into the API, so we can remove these fields itself and refactor some stuff.
</blockquote></details>

will make this change.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 643 at r9](https://reviewable.io/reviews/harness/harness-core/30821#-Mx3ePGF0PFKQ_V98Hwq:-Mx3fWpU7GHQ7bQf9URQ:b5w65xl) ([raw file](https://github.com/harness/harness-core/blob/1a5333994d5785e1fe737ce1bf58b6cc1e97dc3f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L643)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

How do we get to know if repo is an issue here? It will only always say that branch is not found?
</blockquote></details>

in that case listBranchesUsingConnector itself will throw error.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 640 at r9](https://reviewable.io/reviews/harness/harness-core/30821#-Mx3e4l79tkcv8islpiG:-Mx3nShO1BQf39H6N2do:b-g9cd4k) ([raw file](https://github.com/harness/harness-core/blob/1a5333994d5785e1fe737ce1bf58b6cc1e97dc3f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L640)):*
<details><summary><i>Previously, goelsatyam2 (Satyam Goel) wrote…</i></summary><blockquote>

will make this change.
</blockquote></details>

Lets take this up as a separate change. We can create a backlog ticket and take it later.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 643 at r9](https://reviewable.io/reviews/harness/harness-core/30821#-Mx3ePGF0PFKQ_V98Hwq:-Mx3nWq2B7Duhq_upS5Y:b8myma0) ([raw file](https://github.com/harness/harness-core/blob/1a5333994d5785e1fe737ce1bf58b6cc1e97dc3f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L643)):*
<details><summary><i>Previously, goelsatyam2 (Satyam Goel) wrote…</i></summary><blockquote>

in that case listBranchesUsingConnector itself will throw error.
</blockquote></details>

Got it, lets add UT to capture this behaviour

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r8, 2 of 2 files at r10, 2 of 2 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 208 at r13](https://reviewable.io/reviews/harness/harness-core/30821#-Mx49lFQ2nUJ16Pd_cA-:-Mx49lFQ2nUJ16Pd_cA0:bhodwgo) ([raw file](https://github.com/harness/harness-core/blob/02ab897d867338135802b4305319e841084667d9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L208)):*
> ```Java
>     // otherwise we end-up saving invalid git configs
>     checkIfBranchExists(ygs);
>     return saveInternal(ygs, ygs.getAccountIdentifier());
> ```

In saveInternal we have a method validateTheGitConfigInput, please put this check inside this method, all the validation checks are present there only.

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 642 at r13](https://reviewable.io/reviews/harness/harness-core/30821#-Mx4A2262MI_r18lmQ8q:-Mx4A2273XbAQ7DKGvzD:b-tp4sw1) ([raw file](https://github.com/harness/harness-core/blob/02ab897d867338135802b4305319e841084667d9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L642)):*
> ```Java
> 
>     if (isEmpty(branches) || !branches.contains(ygs.getBranch())) {
>       throw new InvalidRequestException(String.format("error while checking the branch. Branch doesn't exists."));
> ```

in error e should be capital.

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 208 at r13](https://reviewable.io/reviews/harness/harness-core/30821#-Mx49lFQ2nUJ16Pd_cA-:-Mx4B-_68M_93MBdgim0:b-d8kxbd) ([raw file](https://github.com/harness/harness-core/blob/02ab897d867338135802b4305319e841084667d9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L208)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

In saveInternal we have a method validateTheGitConfigInput, please put this check inside this method, all the validation checks are present there only.
</blockquote></details>

I think this should be fine. SaveInternal() is a private method to actually distinguish validations and actual save. If we put all checks inside saveInternal, then whats the point of it having a separate method altogether.

**Review by goelsatyam2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 642 at r13](https://reviewable.io/reviews/harness/harness-core/30821#-Mx4A2262MI_r18lmQ8q:-Mx4CqHkBMncZhTlLpVb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ab897d867338135802b4305319e841084667d9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L642)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

in error e should be capital.
</blockquote></details>

Done.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 1 of 3 files at r5, 1 of 1 files at r8, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: 3 file(s) to review.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821#-:-Mx4TaF28FJBXahKFcKG:bnfp4nl)* status: 3 file(s) to review.

**Review by goelsatyam2 — COMMENTED** [review]
> Reviewed 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: 3 file(s) to review.

**Review by goelsatyam2 — COMMENTED** [review]
> Reviewed 2 of 2 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: 3 file(s) to review.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821#-:-Mx4VYNt1wZABtHkg3HW:bnfp4nl)* status: 3 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 1 of 2 files at r10, 1 of 2 files at r11, 1 of 1 files at r12, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30821)* status: :shipit: complete! ✓

**Pull request merged**
