### PR TITLE
[feat]: [PIE-3817]: Generate stages execution list using flag value in pipeline yaml

### PR DESCRIPTION
**Pull request by namanvermah**
Pipeline YAML has a flag `allowStageExecutions` whose value is also stored in the DB. However, we need to remove the usage of the DB flag now, because the with git simplification, the YAML on Git can easily be outdated wrt the DB entry. Hence, we need to use the value of the flag in the YAML and not in the DB.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33499)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33499)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 621 at r1](https://reviewable.io/reviews/harness/harness-core/33499#-N2pwkym1nEFl1Tb35J2:-N2pwkym1nEFl1Tb35J3:b-c8no62) ([raw file](https://github.com/harness/harness-core/blob/41aaf4ea6408eb82af8ce4721823883ac5cd699b/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L621)):*
> ```Java
>     boolean shouldAllowStageExecutions;
>     try {
>       BasicPipeline basicPipeline = YamlUtils.read(yaml, BasicPipeline.class);
> ```

remove from ExecutionHelper and remove this methid from PipelineEntity as well



_Code quote:_
```Java
BasicPipeline basicPipeline = YamlUtils.read(yaml, BasicPipeline.cla
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33499)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 621 at r1](https://reviewable.io/reviews/harness/harness-core/33499#-N2pwkym1nEFl1Tb35J2:-N2pycEX1QS8aCFKiGsn:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/41aaf4ea6408eb82af8ce4721823883ac5cd699b/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L621)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

remove from ExecutionHelper and remove this methid from PipelineEntity as well
</blockquote></details>

done

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33499)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33499)* status: :shipit: complete! ✓

**Pull request merged**
