### PR TITLE
feat: [PL-22611]: Access Control to Consume V2 ResourceGroups

### PR DESCRIPTION
**Pull request by reetika04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32167)

### CODE REVIEW

**Review by gupta-utkarsh — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32167)* status: Some of the checks are too old. 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java, line 37 at r1](https://reviewable.io/reviews/harness/harness-core/32167#-N-w2R1Z17_hXcMO1xPk:-N-w2R1Z17_hXcMO1xPl:bur24l2) ([raw file](https://github.com/harness/harness-core/blob/fe5bd043ec9d1a3be06cb78856abcaca72103d47/access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java#L37)):*
> ```Java
>     return ACL.builder()
>         .roleAssignmentId(roleAssignment.getId())
>         .scopeIdentifier(scopeIdentifier)
> ```

This should remain the identifier from the roleAssignment. Please verify if doing so would cause any issues by checking its usages.

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32167)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java, line 37 at r1](https://reviewable.io/reviews/harness/harness-core/32167#-N-w2R1Z17_hXcMO1xPk:-N-wBVj2DFm7wBvnU_yJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fe5bd043ec9d1a3be06cb78856abcaca72103d47/access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java#L37)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

This should remain the identifier from the roleAssignment. Please verify if doing so would cause any issues by checking its usages.
</blockquote></details>

Done.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32167#-:-N-wCttH9UGWqljudfJi:bnfp4nl)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32167)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32167#-:-N-wLCz4B6x1OhSZvWg8:bnfp4nl)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 5 of 9 files at r1, 4 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32167#-:-N-wVuxQ6OXXZFl_mO3l:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
