### PR TITLE
feat:[CDS-84541]: Adding support for Aws S3 Store Download For SAM Manifest and Values Manifest in SAM Swimlane

### PR DESCRIPTION
**Pull request by piyush-bhuwalka**
## Describe your changes

 Adding support for Aws S3 Store Download For SAM Manifest and Values Manifest in SAM Swimlane

For more details, refer this doc

https://harness.atlassian.net/wiki/spaces/DEV/pages/21550334096/Download+S3+Store+Support+for+CD+Container+Based+Step+Group

Cases tested:

S3 for SAM Manifest with zip ( both at root, as well as somePath/zipName)
S3 for SAM Manifest with content at root path
S3 for SAM Manifest with content inside folder
S3 for Values Manifest with single file
S3 for both SAM manifest and values
S3 for SAM and git for values
Git for SAM and s3 for values
Git for both SAM and s3

https://github.com/harness/harness-core/assets/100153994/1a6a4318-3fe8-4b9d-abab-ea46aaeaa7d8

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56272)

### CODE REVIEW

**Comment by piyush-bhuwalka** [comment]
trigger ut8

**Review by ivan-83 — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56272)* status: 6 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 240 at r1](https://reviewable.io/reviews/harness/harness-core/56272#-NktE05i1wGi41KmgRPY:-NktE05i1wGi41KmgRPZ:b-y2bmha) ([raw file](https://github.com/harness/harness-core/blob/c69bd183449da080f94dc401be51c6f8e19cadd2/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L240)):*
> ```Java
>   }
> 
>   public String removeExtraSlashesInString(String path) {
> ```

Minor : should these two methods for removing slashes be private?

**Review by PragyeshMishra01 — APPROVED** [review]

**Comment by piyush-bhuwalka** [comment]
trigger messagecheck

**Comment by piyush-bhuwalka** [comment]
trigger review

**Pull request merged**
