### PR TITLE
feat: [CDS-58899]: Support expression lastPublished.tag for regex for all artifact source

### PR DESCRIPTION
**Pull request by shivamnegi94**
## Describe your changes
Currently there is no way to deploy build regex using trigger as there no field for tag regex.
To support that we have added an expression <+lastPublished.tag>.regex(<>) which can be used to deploy the latest tag of given regex using trigger

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46304)

### CODE REVIEW

**Review by sribalij — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46304)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by puthrayaharness — APPROVED** [review]

**Review by puthrayaharness — APPROVED** [review]

**Comment by shivamnegi94** [comment]
trigger messagecheck

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46304)* status: 3 file(s) to review. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/PMSExpressionEvaluator.java` line 88 at r4](https://reviewable.io/reviews/harness/harness-core/46304#-NU-oeFLEhYZ_vdbLct8:-NU-oeFLEhYZ_vdbLct9:b9e3dvf) ([raw file](https://github.com/harness/harness-core/blob/1f414185710bf04430601acefe3f495e07c4c108/pipeline-service/service/src/main/java/io/harness/pms/expressions/PMSExpressionEvaluator.java#L88)):*
> ```Java
>     addToContext(SetupAbstractionKeys.eventPayload, new EventPayloadFunctor(ambiance, planExecutionMetadataService));
>     addToContext(SetupAbstractionKeys.trigger, new TriggerFunctor(ambiance, planExecutionMetadataService));
>     addToContext(SetupAbstractionKeys.lastPublished, new LastPublishedFunctor(ambiance));
> ```

since we are removing this functor, any backward compatibility issues could be there?

**Review by shivamnegi94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46304)* status: 3 file(s) to review. 1. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/PMSExpressionEvaluator.java` line 88 at r4](https://reviewable.io/reviews/harness/harness-core/46304#-NU-oeFLEhYZ_vdbLct8:-NU-oyIj4kFAoUAsQqxi:bqtyalh) ([raw file](https://github.com/harness/harness-core/blob/1f414185710bf04430601acefe3f495e07c4c108/pipeline-service/service/src/main/java/io/harness/pms/expressions/PMSExpressionEvaluator.java#L88)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

since we are removing this functor, any backward compatibility issues could be there?
</blockquote></details>

No @vaibhav-si , The feature is not yet enabled for any customer. Changes are still in testing phase.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46304)* status: 3 file(s) to review. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java` line 105 at r4](https://reviewable.io/reviews/harness/harness-core/46304#-NU-pgzN5YHvt1uz9iCf:-NU-pgzO3mezOe-x_XD-:b-3ky5kq) ([raw file](https://github.com/harness/harness-core/blob/f4077c2b581be5f675774d5d43f8e309e348b5fc/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java#L105)):*
> ```Java
> public class ArtifactConfigToDelegateReqMapper {
>   private final String ACCEPT_ALL_REGEX = "\\*";
>   private final String LAST_PUBLISHED_EXPRESSION = "<+lastPublished.tag>";
> ```

this expression, where is this supported? Can I use it in  a shell script step?



_Code quote:_
```Java
<+lastPublished.tag>
```

**Review by vaibhav-si — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46304)* status: 3 file(s) to review.

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46304)* status: 3 file(s) to review.

**Review by shivamnegi94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46304)* status: 3 file(s) to review. 1. unresolved discussions. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java` line 105 at r4](https://reviewable.io/reviews/harness/harness-core/46304#-NU-pgzN5YHvt1uz9iCf:-NU-q0Yd4xlBRvOXS8uT:bofiwun) ([raw file](https://github.com/harness/harness-core/blob/f4077c2b581be5f675774d5d43f8e309e348b5fc/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java#L105)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

this expression, where is this supported? Can I use it in  a shell script step?
</blockquote></details>

No it won't be used in shell script, it will be only supported in artifact source or trigger.

**Review by vaibhav-si — APPROVED** [review]
Approved from Pipeline side

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46304#-:-NU-q7WXAYEB2Q1Ku-dD:b-5n5i65)* status: 3 file(s) to review. 1. unresolved discussions.

**Pull request merged**
