### PR TITLE
[fix]: [PIE-6693]: Fix pipeline-stuck due to exception in ng-manager during NodeAdviserEventHandler

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42517)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42517)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/publisher/RedisNodeAdviseEventPublisher.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/42517#-NLZ7hQi8WYLIDrJ-VPZ:-NLZ7hQj6eE4y04aqKAW:blrj0tx) ([raw file](https://github.com/harness/harness-core/blob/b31026550c91d20ac4233c3ee1badbdbcfcc10bd/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/publisher/RedisNodeAdviseEventPublisher.java#L48)):*
> ```Java
> 
>     if (!EmptyPredicate.isEmpty(nodeExecution.getNotifyId())) {
>       builder.setNotifyId(nodeExecution.getNotifyId());
> ```

Can you add handling for empty in handler for error event?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42517)* status: 2 change requests. 0 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/publisher/RedisNodeAdviseEventPublisher.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/42517#-NLZ7hQi8WYLIDrJ-VPZ:-NLZHwMe8xY2pUs7N4bw:b-d90fjq) ([raw file](https://github.com/harness/harness-core/blob/b31026550c91d20ac4233c3ee1badbdbcfcc10bd/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/publisher/RedisNodeAdviseEventPublisher.java#L48)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can you add handling for empty in handler for error event?
</blockquote></details>

It will be handled automatically. Since the notifyId is empty, nothing will happen on waitNotifyEngine.doneWith.

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/publisher/RedisNodeAdviseEventPublisher.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/42517#-NLZ7hQi8WYLIDrJ-VPZ:-NLZThEtArkUzjEKnsyI:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/b31026550c91d20ac4233c3ee1badbdbcfcc10bd/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/publisher/RedisNodeAdviseEventPublisher.java#L48)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

It will be handled automatically. Since the notifyId is empty, nothing will happen on waitNotifyEngine.doneWith. 
</blockquote></details>

Done

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42517)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42517)* status: :shipit: complete! ✓

**Pull request merged**
