### PR TITLE
fix: [PL-25742]:  Default Role assignment changed from Account Viewer to Account Basic role when ACCOUNT_BASIC_ROLE is turned on

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
Default Role assignment changed from Account Viewer to Account Basic role when ACCOUNT_BASIC_ROLE is turned on.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34072)

### CODE REVIEW

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34072#-:-N41X73K0_qsSx63m7Pk:bnfp4nl)* status: :shipit: complete! ✓

**Comment by gupta-utkarsh** [comment]
trigger messagecheck

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34072)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 609 at r1](https://reviewable.io/reviews/harness/harness-core/34072#-N41ZRam8M2Ju62L-QkU:-N41ZRam8M2Ju62L-QkV:b-7odx8a) ([raw file](https://github.com/harness/harness-core/blob/bfd1adfc9be77be0bebde050b44135a00a656689/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L609)):*
> ```Java
>   }
> 
>   private List<String> GetManagedRoleIdentifiers(
> ```

getManagedRoleIdentifiers

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34072#-:-N41g2mK-PzmjKHKJehO:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34072#-:-N41g7qd-JJGnHlMEONP:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34072#-:-N41dTHOCDljW5hn_T3v:bnfp4nl)* status: :shipit: complete! ✓

**Comment by gupta-utkarsh** [comment]
trigger recency

**Review by reetika04 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34072)* status: :shipit: complete! ✓

**Pull request merged**
