### PR TITLE
feat: [PL-28238]: Removed account basic role from role assignments list

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
Added a new field in Role and RoleAssignments- "internal" to identify basic roles, like "_account_basic". This field will be used to remove basic roles from the list API for role assignments
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40173)

### CODE REVIEW

**Comment by naman-goenka** [comment]
trigger feature-build

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40173)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/DefaultUserGroupServiceImpl.java` line 155 at r1](https://reviewable.io/reviews/harness/harness-core/40173#-NISpY9DBuxRhU3i1AEd:-NISpY9DBuxRhU3i1AEe:b-asofsa) ([raw file](https://github.com/harness/harness-core/blob/21fcce6273f483955953bf8f311ccd020106f410/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/DefaultUserGroupServiceImpl.java#L155)):*
> ```Java
> 
>   private void createRoleAssignmentsForOrganization(String userGroupIdentifier, Scope scope) {
>     createRoleAssignment(userGroupIdentifier, scope, true, true, ORGANIZATION_VIEWER_ROLE,
> ```

For ORGANIZATION_VIEWER_ROLE, this should be false.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40173)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/DefaultUserGroupServiceImpl.java` line 155 at r1](https://reviewable.io/reviews/harness/harness-core/40173#-NISpY9DBuxRhU3i1AEd:-NIbJ6Md2HwFY0YoBSul:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fcce6273f483955953bf8f311ccd020106f410/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/DefaultUserGroupServiceImpl.java#L155)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

For ORGANIZATION_VIEWER_ROLE, this should be false.
</blockquote></details>

Done.

**Review by reetika04 — DISMISSED** [review]
> Reviewed 7 of 10 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40173)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40173)* status: 11 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/RoleAssignmentDaoImpl.java` line 170 at r2](https://reviewable.io/reviews/harness/harness-core/40173#-NIfBUquEV_BMKdXxqQd:-NIfBUquEV_BMKdXxqQe:b7de41t) ([raw file](https://github.com/harness/harness-core/blob/2a6897920da50fa92fbb644460971fb4bcd33b3e/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/RoleAssignmentDaoImpl.java#L170)):*
> ```Java
>     }
> 
>     criteria.and(RoleAssignmentDBOKeys.internal).ne(true);
> ```

We should check which all places we need to skip internal Role assignments as the same createCriteriaFromFilter is used in delete of Principal and so the corresponding role assignment needs to be deleted as well.
Please create test cases to track for same.

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 10 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40173#-:-NJ4FoPQ6QEF8EHVhg_4:bnfp4nl)* status: Some of the checks are too old. 1 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40173)* status: 1 file(s) to review.

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40173#-:-NJ8sN8R0ZhwWjDOKbBn:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
