### PR TITLE
fix: [DEL-3784] Client tools default paths

### PR DESCRIPTION
**Pull request by mdmilic**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32335)

### CODE REVIEW

**Review by puneetsar — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32335)* status: :shipit: complete! ✓

**Comment by mdmilic** [comment]
trigger compile codeformat messagecheck recency buildnum dockerizationcheck checkstyle pmd ti0 ti1 ti2 ti3 ti4 ft1 ft2 codebasehash

**Comment by mdmilic** [comment]
trigger ti0

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 11 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32335)* status: :shipit: complete! ✓

**Pull request merged**
