### PR TITLE
feat:[CDS-84540]: Adding support for Aws S3 Store Download For Serverless Manifest and Values Manifest in Serverless V2 Swimlane

### PR DESCRIPTION
**Pull request by piyush-bhuwalka**
## Describe your changes

Adding support for Aws S3 Store Download For Serverless Manifest and Values Manifest in Serverless V2 Swimlane

For more details, refer this doc

https://harness.atlassian.net/wiki/spaces/DEV/pages/21550334096/Download+S3+Store+Support+for+CD+Container+Based+Step+Group

Cases tested:

1) S3 for Serverless Manifest with zip ( both at root, as well as somePath/zipName)
2) S3 for Serverless Manifest with content at root path
3) S3 for Serverless Manifest with content inside folder
4) S3 for Values Manifest with single file
5) S3 for both serverless manifest and values
6) S3 for serverless and git for values
7) Git for serverless and s3 for values
8) Git for both serverless and s3

https://github.com/harness/harness-core/assets/100153994/dab87c75-e856-4a03-8832-09a7535ea035

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56104)

### CODE REVIEW

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Comment by piyush-bhuwalka** [comment]
trigger messagecheck

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Review by PragyeshMishra01 — APPROVED** [review]

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 36 of 42 files at r3, 5 of 6 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56104)* status: Some of the checks are too old. 44 file(s) to review. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsCommonHelper.java` line 165 at r6](https://reviewable.io/reviews/harness/harness-core/56104#-NkkE6PV2by6PTD7Nxsy:-NkkE6PV2by6PTD7Nxsz:b-e9vhdv) ([raw file](https://github.com/harness/harness-core/blob/1cabee4ea6c070df0ec08c397b814f48a067fd0a/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsCommonHelper.java#L165)):*
> ```Java
>         .region(s3StoreConfig.getRegion())
>         .paths(s3StoreConfig.getPaths())
>         .downloadPath(ParameterField.createValueField("/harness/" + manifestOutcome.getIdentifier()))
> ```

Minor: "/harness/" >> could be the const in the common const class or helper.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsCommonHelper.java` line 176 at r6](https://reviewable.io/reviews/harness/harness-core/56104#-NkkEm9IAuR9Ozm--0-l:-NkkEm9IAuR9Ozm--0-m:bf26u1) ([raw file](https://github.com/harness/harness-core/blob/1cabee4ea6c070df0ec08c397b814f48a067fd0a/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsCommonHelper.java#L176)):*
> ```Java
>         .region(s3StoreConfig.getRegion())
>         .paths(s3StoreConfig.getPaths())
>         .downloadPath(ParameterField.createValueField("/harness/" + manifestOutcome.getIdentifier()))
> ```

The same as above.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java` line 184 at r6](https://reviewable.io/reviews/harness/harness-core/56104#-NkkGCxk1usvGz6aQL9w:-NkkGCxk1usvGz6aQL9x:b-fajnih) ([raw file](https://github.com/harness/harness-core/blob/1cabee4ea6c070df0ec08c397b814f48a067fd0a/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java#L184)):*
> ```Java
>         throw new InvalidRequestException("Atleast one git path need to be specified", USER);
>       }
>     } else if (storeConfig instanceof S3StoreConfig) {
> ```

Shouldn't CDS_CONTAINER_STEP_GROUP_AWS_S3_DOWNLOAD be controlled by UI. Why do we need to check here?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java` line 193 at r6](https://reviewable.io/reviews/harness/harness-core/56104#-NkkGRBq7GuK6e28sEjY:-NkkGRBq7GuK6e28sEjZ:b-qguksu) ([raw file](https://github.com/harness/harness-core/blob/1cabee4ea6c070df0ec08c397b814f48a067fd0a/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java#L193)):*
> ```Java
> 
>       if (isEmpty(((S3StoreConfig) storeConfig).getPaths().getValue())) {
>         throw new InvalidRequestException("Atleast one s3 store path need to be specified", USER);
> ```

Minor: At least
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessDownloadManifestsStepHelper.java` line 391 at r6](https://reviewable.io/reviews/harness/harness-core/56104#-NkkKsPHAQ8bMGpyoact:-NkkKsPHAQ8bMGpyoacu:bxy2zmh) ([raw file](https://github.com/harness/harness-core/blob/1cabee4ea6c070df0ec08c397b814f48a067fd0a/125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessDownloadManifestsStepHelper.java#L391)):*
> ```Java
> 
>     if (serverlessAwsLambdaManifestOutcome.getStore() instanceof S3StoreConfig) {
>       if (!cdFeatureFlagHelper.isEnabled(
> ```

Minor: the check for the plugin can me moved to a separate method.

**Comment by piyush-bhuwalka** [comment]
trigger review

**Pull request merged**
