### PR TITLE
[feat]: [IDP-286]: Unit Tests Settings Module

### PR DESCRIPTION
**Pull request by sarthakkasat**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45367)

### CODE REVIEW

**Review by sandeepa-kv-jois — DISMISSED** [review]

**Comment by sarthakkasat** [comment]
trigger ut9

**Review by devesh-harness — DISMISSED** [review]
:lgtm:

> Reviewed 7 of 8 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45367#-:-NR43NUE3fGMpyBtjA-v:bnfp4nl)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45367)* status: 8 file(s) to review. 1 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/45367#-NR4MXYl9cZsoMORvfEf:-NR4MXYl9cZsoMORvfEg:b-oz21vr) ([raw file](https://github.com/harness/harness-core/blob/8cd16136c79824d107c006ba4daec76a28f608cc/idp-service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java#L43)):*
> ```Java
>     Optional<BackstagePermissions> backstagePermissions =
>         backstagePermissionsService.findByAccountIdentifier(harnessAccount);
>     BackstagePermissionsResponse backstagePermissionsResponse = new BackstagePermissionsResponse();
> ```

Can be initialised after the isEmpty if check. SonarQube says the same.
___
*[`idp-service/src/test/java/io/harness/idp/provision/service/ProvisionServiceImplTest.java` line 11 at r3](https://reviewable.io/reviews/harness/harness-core/45367#-NR4MlL04TKIKU3Qe-Zb:-NR4MlL04TKIKU3Qe-Zc:b5nryjo) ([raw file](https://github.com/harness/harness-core/blob/8cd16136c79824d107c006ba4daec76a28f608cc/idp-service/src/test/java/io/harness/idp/provision/service/ProvisionServiceImplTest.java#L11)):*
> ```Java
> 
> import static org.mockito.ArgumentMatchers.any;
> import static org.mockito.Mockito.*;
> ```

Our CheckStyle is not throwing error for star import ?
___
*[`idp-service/src/test/java/io/harness/idp/provision/service/ProvisionServiceImplTest.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/45367#-NR4N3Xl4lXsrUIyyqiS:-NR4N3Xm7Mbt-NLIBLeE:b-c0s423) ([raw file](https://github.com/harness/harness-core/blob/8cd16136c79824d107c006ba4daec76a28f608cc/idp-service/src/test/java/io/harness/idp/provision/service/ProvisionServiceImplTest.java#L66)):*
> ```Java
> 
>   @Test
>   @Category(UnitTests.class)
> ```

Can you add Owner Rule for the test cases that you have written ?
___
*[`idp-service/src/test/java/io/harness/idp/provision/service/ProvisionServiceImplTest.java` line 67 at r3](https://reviewable.io/reviews/harness/harness-core/45367#-NR4NYw38QTP868VE-2w:-NR4NYw38QTP868VE-2x:b-h3obps) ([raw file](https://github.com/harness/harness-core/blob/8cd16136c79824d107c006ba4daec76a28f608cc/idp-service/src/test/java/io/harness/idp/provision/service/ProvisionServiceImplTest.java#L67)):*
> ```Java
>   @Test
>   @Category(UnitTests.class)
>   public void testCreateDefaultBackstagePermissions() {
> ```

I think this is not needed in Provision flow test.

**Comment by sarthakkasat** [comment]
*[`idp-service/src/test/java/io/harness/idp/provision/service/ProvisionServiceImplTest.java` line 11 at r3](https://reviewable.io/reviews/harness/harness-core/45367#-NR4MlL04TKIKU3Qe-Zb:-NR4Rlu4BskfP6-Nl6it:bo9a73y) ([raw file](https://github.com/harness/harness-core/blob/8cd16136c79824d107c006ba4daec76a28f608cc/idp-service/src/test/java/io/harness/idp/provision/service/ProvisionServiceImplTest.java#L11)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Our CheckStyle is not throwing error for star import ?
</blockquote></details>

Does not throw an error

**Comment by sarthakkasat** [comment]
*[`idp-service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/45367#-NR4MXYl9cZsoMORvfEf:-NR4YYnq2XnRIakHz2RY:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/8cd16136c79824d107c006ba4daec76a28f608cc/idp-service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java#L43)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Can be initialised after the isEmpty if check. SonarQube says the same.
</blockquote></details>

Done

**Comment by sarthakkasat** [comment]
*[`idp-service/src/test/java/io/harness/idp/provision/service/ProvisionServiceImplTest.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/45367#-NR4N3Xl4lXsrUIyyqiS:-NR4Y_sGAG60SNvMl8-L:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/8cd16136c79824d107c006ba4daec76a28f608cc/idp-service/src/test/java/io/harness/idp/provision/service/ProvisionServiceImplTest.java#L66)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Can you add Owner Rule for the test cases that you have written ?
</blockquote></details>

Done

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45367)* status: 9 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by sathish-soundarapandian — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45367)* status: :shipit: complete! ✓

**Pull request merged**
