### PR TITLE
feat: [PL-26410]: fixes for ado ssh connector

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
Tested -
1. ado project ssh connector with pipeline crud flows
2. file url with ado ssh project type connector
3. ado repo ssh connector with pipeline crud flows
4. fileurl with ado ssh repo type connector

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35173)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java` line 141 at r1](https://reviewable.io/reviews/harness/harness-core/35173#-N6TGdtx5anSkvj56eau:-N6TGdtx5anSkvj56eav:bw5mq9o) ([raw file](https://github.com/harness/harness-core/blob/ebc88011047cd5815ef773c270f622fdec767402/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L141)):*
> ```Java
>   public GitRepositoryDTO getGitRepositoryDetails() {
>     String orgAndProject;
>     if (GitAuthType.HTTP.equals(authentication.getAuthType())) {
> ```

With Enums, you can always use ==. [not a blocking comment]

**Comment by mohitg0795** [comment]
*[`960-api-services/src/main/java/io/harness/git/GitClientHelper.java` line 266 at r1](https://reviewable.io/reviews/harness/harness-core/35173#-N6TGuHH469K9XAX1Osx:-N6TGuHH469K9XAX1Osy:bdjroe5) ([raw file](https://github.com/harness/harness-core/blob/ebc88011047cd5815ef773c270f622fdec767402/960-api-services/src/main/java/io/harness/git/GitClientHelper.java#L266)):*
> ```Java
>   }
> 
>   public static String getAzureRepoOrgAndProjectSSH(String url) {
> ```

I didn't get the meaning of this method actually, could you please explain or simplify the name?

**Comment by mohitg0795** [comment]
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java` line 122 at r1](https://reviewable.io/reviews/harness/harness-core/35173#-N6TH1lF1H13CVc_fwRa:-N6TH1lGCjf2r_W8HMeL:b-7a9roj) ([raw file](https://github.com/harness/harness-core/blob/ebc88011047cd5815ef773c270f622fdec767402/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L122)):*
> ```Java
> 
>   @Override
>   public String getGitConnectionUrl(GitRepositoryDTO gitRepositoryDTO) {
> ```

we should enhance UT for this method to add test for new code added.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35173)* status: 4 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java` line 122 at r1](https://reviewable.io/reviews/harness/harness-core/35173#-N6TH1lF1H13CVc_fwRa:-N6TKzKc2xszLtwICc6l:bfu5byc) ([raw file](https://github.com/harness/harness-core/blob/ebc88011047cd5815ef773c270f622fdec767402/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L122)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should enhance UT for this method to add test for new code added.
</blockquote></details>

added ut

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35173#-:-N6TLE7x4gPnT-jVZFk-:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35173#-:-N6YNENpDf8X6aKqPNTo:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35173)* status: :shipit: complete! ✓

**Pull request merged**
