### PR TITLE
fix: [PL-40395]: Add redis lock to HB sync job

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:  Add persistence lock to delegate heartbeat sync job from cache

Test
- Test delegate HB updating from redis cache to DB 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51603)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger uts

**Comment by piyush-harness** [comment]
*[`420-delegate-service/src/main/java/io/harness/redis/DelegateHeartBeatSyncFromRedis.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/51603#-NbaUJqWDwqc_4w6z7qj:-NbaUJqX3nvAdQawGrQF:bhrehxe) ([raw file](https://github.com/harness/harness-core/blob/1f44a63dd0b31c7cef55cfd1702b28cfdf0b1931/420-delegate-service/src/main/java/io/harness/redis/DelegateHeartBeatSyncFromRedis.java#L43)):*
> ```Java
>     }
>     try (AcquiredLock<?> lock = persistentLocker.tryToAcquireLock(
>              DelegateHeartBeatSyncFromRedis.class, lockId + generateUuid(), Duration.ofMinutes(2))) {
> ```

This logic will allow all pods to take lock with different lockID, Do not append UUID.

**Comment by piyush-harness** [comment]
*[`400-rest/src/test/java/io/harness/redis/DelegateHeartBeatSyncFromRedisTest.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/51603#-NbaU_ZfABKLNRqmCH7t:-NbaU_ZfABKLNRqmCH7u:btdv8tf) ([raw file](https://github.com/harness/harness-core/blob/1f44a63dd0b31c7cef55cfd1702b28cfdf0b1931/400-rest/src/test/java/io/harness/redis/DelegateHeartBeatSyncFromRedisTest.java#L59)):*
> ```Java
>   @Owner(developers = JENNY)
>   @Category(UnitTests.class)
>   public void testSyncJobLock() throws InterruptedException {
> ```

Write test which confirms Lock is only taken by 1 thread at a time.

**Comment by piyush-harness** [comment]
*[`420-delegate-service/src/main/java/io/harness/redis/DelegateHeartBeatSyncFromRedis.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/51603#-NbaUJqWDwqc_4w6z7qj:-Nba_VS0CDYbyGgE_AqT:b-fjxyy4) ([raw file](https://github.com/harness/harness-core/blob/1f44a63dd0b31c7cef55cfd1702b28cfdf0b1931/420-delegate-service/src/main/java/io/harness/redis/DelegateHeartBeatSyncFromRedis.java#L43)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

This logic will allow all pods to take lock with different lockID, Do not append UUID.
</blockquote></details>

Also you can use tryToAcquireInfiniteLockWithPeriodicRefresh to keep the lock till the operation completes

**Pull request closed without merging**
