### PR TITLE
[fix]: [BT-3706]: Upgrade opentelemetry agent version to 1.25.0

### PR DESCRIPTION
**Pull request by krishi0408**
## Describe your changes
Ticket:- https://harness.atlassian.net/browse/BT-3706
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47308)

### CODE REVIEW

**Review by USB-05 — COMMENTED** [review]
Name should not have the version number in it, as the old name is getting used at other various places. So keep the name as the original name

**Comment by ashishsanodia-harness** [comment]
*[`dockerization/base-images/apm/inject-saas-apm-bins-into-dockerimage.sh` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/47308#-NU_QP0x3wyr7aA0LWPr:-NU_QP0x3wyr7aA0LWPs:b-460hvz) ([raw file](https://github.com/harness/harness-core/blob/a01abcdca5fc81b0415818513a16345ddf67fe4d/dockerization/base-images/apm/inject-saas-apm-bins-into-dockerimage.sh#L33)):*
> ```Shell
> export APPD_AGENT='https://harness.jfrog.io/artifactory/BuildsTools/docker/apm/appd/AppServerAgent-1.8-23.2.0.34668.zip'
> export ET_AGENT='https://get.et.harness.io/releases/latest/nix/harness-et-agent.tar.gz'
> export OT_AGENT='https://harness.jfrog.io/artifactory/BuildsTools/docker/apm/opentelemetry/opentelemetry-javaagent-1.25.0.jar'
> ```

Did you test these changes in PR? 
I think agent name change will cause issue in services because they expect it to be without version in location /opt/harness/opentelemetry-javaagent.jar

**Comment by krishi0408** [comment]
> 
@ashishsanodia-harness please test this bu building your image using this branch. Once the changes are good, will merge in develop.
cc: @USB-05

**Review by diptiman-adak — APPROVED** [review]

**Comment by krishi0408** [comment]
> @ashishsanodia-harness please test this bu building your image using this branch. Once the changes are good, will merge in develop.
> cc: @USB-05

@ashishsanodia-harness are we good to merge this? 
cc: @USB-05 @diptiman-adak

**Comment by krishi0408** [comment]
trigger uts

**Comment by krishi0408** [comment]
trigger message check

**Comment by krishi0408** [comment]
trigger messagecheck

**Comment by krishi0408** [comment]
trigger ut0

**Pull request closed without merging**
