### PR TITLE
[fix]: [DEL-3509]: Race condition allowing older delegate process task simultaneously with newer delegate

### PR DESCRIPTION
**Pull request by raghuAtWings**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31404)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
trigger messagecheck

**Review by jennyjames21 — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31404)* status: :shipit: complete! ✓

**Review by puneetsar — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, 3 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31404)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 1993 at r4](https://reviewable.io/reviews/harness/harness-core/31404#-Mxvwqzf9DAIJmPa3_hr:-Mxvwqzf9DAIJmPa3_hs:b-tp27jq) ([raw file](https://github.com/harness/harness-core/blob/336a44bedaacb5d162ff428c2eb66f6e5d6607f8/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1993)):*
> ```Java
>         updateCounterIfLessThanCurrent(maxValidatingTasksCount, currentlyValidatingTasks.size());
>         delegateValidateTask.validationResults();
>       } else if (delegateId.equals(delegateTaskPackage.getDelegateId())) {
> ```

This needs to be updated as well. but in next PR.



_Code quote:_
```Java
delegateId.equals(delegateTaskPackage.getDelegateId()
```
___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 2033 at r4](https://reviewable.io/reviews/harness/harness-core/31404#-Mxvww8Q8erUQLDfJmfe:-Mxvww8Q8erUQLDfJmff:b-ul3qfv) ([raw file](https://github.com/harness/harness-core/blob/336a44bedaacb5d162ff428c2eb66f6e5d6607f8/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2033)):*
> ```Java
> 
>           if (delegateTaskPackage != null && delegateTaskPackage.getData() != null
>               && delegateInstanceId.equals(delegateTaskPackage.getDelegateInstanceId())) {
> ```

This needs to be reverted, and done in next PR?



_Code quote:_
```Java
elegateInstanceId.equals(delegateTaskPackage.getDelegateInstanceId
```

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 4 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31404)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 2033 at r4](https://reviewable.io/reviews/harness/harness-core/31404#-Mxvww8Q8erUQLDfJmfe:-My5_Uzb227WHFaRsUVh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/336a44bedaacb5d162ff428c2eb66f6e5d6607f8/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2033)):*
<details><summary><i>Previously, puneetsar (Puneet Saraswat) wrote…</i></summary><blockquote>

This needs to be reverted, and done in next PR?
</blockquote></details>

Done.

**Comment by raghuAtWings** [comment]
___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 1993 at r4](https://reviewable.io/reviews/harness/harness-core/31404#-Mxvwqzf9DAIJmPa3_hr:-My5_UCY3smbC_Fqs2JQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/336a44bedaacb5d162ff428c2eb66f6e5d6607f8/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1993)):*
<details><summary><i>Previously, puneetsar (Puneet Saraswat) wrote…</i></summary><blockquote>

This needs to be updated as well. but in next PR.
</blockquote></details>

Done.

**Review by puneetsar — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31404)* status: :shipit: complete! ✓

**Pull request merged**
