### PR TITLE
[feat]:[pie-6255]: changed hashset to list

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Changed Hashset to List in the response objects, the swagger doesnt change. This is done in order to return the list of branches or list of repos in alphabetically sorted manner. 
Tested out the changes, with UI, the Integration is intact. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39919)

### CODE REVIEW

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39919)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39919)* status: :shipit: complete! ✓

___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineListRepoResponse.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/39919#-NGVGsIVAdtXsfyRSCAS:-NGVGsIX1yB6nO5CSQi_:b7wxauq) ([raw file](https://github.com/harness/harness-core/blob/4bc95212da480479e19624f9a7888073beac7971/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineListRepoResponse.java#L31)):*
> ```Java
> @OwnedBy(PL)
> public class PMSPipelineListRepoResponse {
>   @Hidden @Schema(description = "Contains the list of repositories from the execution") List<String> repositories;
> ```

UI response needs to change it as well?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39919)* status: 1 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineListRepoResponse.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/39919#-NGVGsIVAdtXsfyRSCAS:-NGVIgO8EnYq0jcdBo17:bnf85kk) ([raw file](https://github.com/harness/harness-core/blob/4bc95212da480479e19624f9a7888073beac7971/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineListRepoResponse.java#L31)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

UI response needs to change it as well?
</blockquote></details>

No changes needed on the UI side, to confirm on this, checked the swagger before and after the change and the swagger looks same. Secondly hit this api from the UI, the api integration remains intact.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39919)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39919)* status: :shipit: complete! ✓

**Pull request merged**
