### PR TITLE
fix: [PIE-884]: Added validation for pipeline list api

### PR DESCRIPTION
**Pull request by shivamnegi94**
## Describe your changes
Added the validation for Org, Project and module
Testing : 
- Validated for valid and invalid org identifier.
- Validated for valid and invalid project identifer.
- Validated for valid and invalid module type.
- Validated for empty sort order.
Screenshot 2023-04-11 at 10 18 20 AM

Is it new task type? No
Did you make changes to the code in a backward-compatible manner? Yes
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? Yes
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? Yes
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No change
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? Yes
if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? Yes
Did you remove an enum → No
Did you add an enum(That too at end of list) → No
FeatureFlag Added/Removed -> No
Verify Changes with affects any -> No
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46266)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46266)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 150 at r3](https://reviewable.io/reviews/harness/harness-core/46266#-NSihQKF4De_aSa85bmB:-NSihQKF4De_aSa85bmC:b-pb21e4) ([raw file](https://github.com/harness/harness-core/blob/5ae3ba48bf1c80496e16d5b6f969fe8743a4ed64/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L150)):*
> ```Java
>   void checkProjectExists(String accountIdentifier, String orgIdentifier, String projectIdentifier);
> 
>   void checkThatTheOrganizationExists(String accountIdentifier, String orgIdentifier);
> ```

project existence only should be fine
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 969 at r3](https://reviewable.io/reviews/harness/harness-core/46266#-NSihWzC-xoQAHnaN-WF:-NSihWzC-xoQAHnaN-WG:bgginr6) ([raw file](https://github.com/harness/harness-core/blob/5ae3ba48bf1c80496e16d5b6f969fe8743a4ed64/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L969)):*
> ```Java
>                        .filter(moduleType -> moduleType.name().equalsIgnoreCase(module))
>                        .collect(Collectors.toList()))) {
>       throw new InvalidRequestException(format("Invalid module type [%s].", module));
> ```

should we list all available modules as hint exception?

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46266)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 219 at r3](https://reviewable.io/reviews/harness/harness-core/46266#-NSihtCIAIEnLA9AUnbL:-NSihtCIAIEnLA9AUnbM:bwvd0wt) ([raw file](https://github.com/harness/harness-core/blob/5ae3ba48bf1c80496e16d5b6f969fe8743a4ed64/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L219)):*
> ```Java
>     log.info(String.format("Get List of Pipelines in project %s, org %s, account %s", project, org, account));
>     pmsPipelineService.checkThatTheOrganizationExists(account, org);
>     pmsPipelineService.checkProjectExists(account, org, project);
> ```

lets add to other resource as well

**Review by shivamnegi94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46266)* status: 6 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 219 at r3](https://reviewable.io/reviews/harness/harness-core/46266#-NSihtCIAIEnLA9AUnbL:-NSnjxLp1QCEWNecSL1m:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5ae3ba48bf1c80496e16d5b6f969fe8743a4ed64/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L219)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

lets add to other resource as well
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 150 at r3](https://reviewable.io/reviews/harness/harness-core/46266#-NSihQKF4De_aSa85bmB:-NSnk11YCCunxrQwkT34:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5ae3ba48bf1c80496e16d5b6f969fe8743a4ed64/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L150)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

project existence only should be fine
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 969 at r3](https://reviewable.io/reviews/harness/harness-core/46266#-NSihWzC-xoQAHnaN-WF:-NSnk2_X3FXdyEFdbBfW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5ae3ba48bf1c80496e16d5b6f969fe8743a4ed64/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L969)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should we list all available modules as hint exception?
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, 2 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46266)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 969 at r3](https://reviewable.io/reviews/harness/harness-core/46266#-NSihWzC-xoQAHnaN-WF:-NSnpn-1AWkErcx2aHSX:bgyd3ac) ([raw file](https://github.com/harness/harness-core/blob/5ae3ba48bf1c80496e16d5b6f969fe8743a4ed64/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L969)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@shivamnegi94 just throwing hint may not work, we may need to wrap original invalidRequestException with hint, there is util even -> throw NestedExceptionUtils.hintWithExplanationException(HintException.LDAP_ATTRIBUTES_INCORRECT,
          ExplanationException.LDAP_ATTRIBUTES_INCORRECT, new GeneralException(errorMessage));

**Review by shivamnegi94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46266)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 969 at r3](https://reviewable.io/reviews/harness/harness-core/46266#-NSihWzC-xoQAHnaN-WF:-NSoFWI-C_cnYLcvjYXe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5ae3ba48bf1c80496e16d5b6f969fe8743a4ed64/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L969)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@shivamnegi94 just throwing hint may not work, we may need to wrap original invalidRequestException with hint, there is util even -> throw NestedExceptionUtils.hintWithExplanationException(HintException.LDAP_ATTRIBUTES_INCORRECT,
          ExplanationException.LDAP_ATTRIBUTES_INCORRECT, new GeneralException(errorMessage));
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46266)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by Abhishek-CDC — APPROVED** [review]

**Comment by shivamnegi94** [comment]
trigger review

**Pull request merged**
