### PR TITLE
[feat]: [CDS-34617]: add default ssh execution strategy yaml

### PR DESCRIPTION
**Pull request by vitsafronovici**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31223)

### CODE REVIEW

**Comment by vitsafronovici** [comment]
trigger messagecheck

**Comment by vitsafronovici** [comment]
trigger messagecheck

**Review by acasian-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31223)* status: 1 change requests. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/31223#-MxiAXmvAZhw4bfnQ4C9:-MxiAXmvAZhw4bfnQ4CA:b-5fu3zv) (no related file):*
@vitsafronovici can we add this behind feature flag? 

---

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31223)* status: :shipit: complete! ✓

**Pull request merged**
