### PR TITLE
[feat]: [PIE-7555]: Add synchronous schema validations in async pipeline get flow

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44798)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger messagecheck

**Review by archit-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44798)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 398 at r1](https://reviewable.io/reviews/harness/harness-core/44798#-NPuZjiIB1gPyeL2ls_0:-NPuZjiIB1gPyeL2ls_1:b-u9nbtf) ([raw file](https://github.com/harness/harness-core/blob/2f4af6b414dd170aac41807265b2a03a6a364a6e/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L398)):*
> ```Java
>       String identifier, boolean loadFromFallbackBranch, boolean loadFromCache) {
>     Optional<PipelineEntity> optionalPipelineEntity;
>     // todo: add schema validations
> ```

nit: can be removed



_Code quote:_
```Java
// todo: add schema validation
```

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44798)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service/PipelineValidationServiceImpl.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/44798#-NPua0Ea6V-MEHD4dOLZ:-NPua0Ea6V-MEHD4dOL_:bjtiqpy) ([raw file](https://github.com/harness/harness-core/blob/46a83070544823de6fb7190ddeddae8470a68491/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service/PipelineValidationServiceImpl.java#L53)):*
> ```Java
> 
>   @Override
>   public boolean validateYamlWithUnresolvedTemplates(String accountIdentifier, String orgIdentifier,
> ```

whats the point of return type boolean if it always returns true.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service/PipelineValidationServiceImpl.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/44798#-NPua5AV5oPjLhIciX7z:-NPua5AV5oPjLhIciX8-:b-fmyngu) ([raw file](https://github.com/harness/harness-core/blob/46a83070544823de6fb7190ddeddae8470a68491/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service/PipelineValidationServiceImpl.java#L55)):*
> ```Java
>   public boolean validateYamlWithUnresolvedTemplates(String accountIdentifier, String orgIdentifier,
>       String projectIdentifier, String pipelineYaml, String harnessVersion) {
>     if (harnessVersion.equals(PipelineVersion.V0)) {
> ```

lets reverse the comparison : V0.equals(xyz)

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 398 at r2](https://reviewable.io/reviews/harness/harness-core/44798#-NPuaNBh2EvYFRH0VFVH:-NPuaNBh2EvYFRH0VFVI:b-8c3z95) ([raw file](https://github.com/harness/harness-core/blob/46a83070544823de6fb7190ddeddae8470a68491/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L398)):*
> ```Java
>       String identifier, boolean loadFromFallbackBranch, boolean loadFromCache) {
>     Optional<PipelineEntity> optionalPipelineEntity;
>     optionalPipelineEntity = getPipeline(
> ```

here we are declaring a variable in first line and using it in very next line. Lets combine these lines.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44798)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service/PipelineValidationServiceImpl.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/44798#-NPua5AV5oPjLhIciX7z:-NPubuKM3v6DjJ8mFhzU:b-8j2i1o) ([raw file](https://github.com/harness/harness-core/blob/46a83070544823de6fb7190ddeddae8470a68491/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service/PipelineValidationServiceImpl.java#L55)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets reverse the comparison : V0.equals(xyz)
</blockquote></details>

Can you use Object.equals as you dont know if this field is null

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44798)* status: 4 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 398 at r1](https://reviewable.io/reviews/harness/harness-core/44798#-NPuZjiIB1gPyeL2ls_0:-NPucygo2lngAzX2HYlx:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/2f4af6b414dd170aac41807265b2a03a6a364a6e/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L398)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: can be removed
</blockquote></details>

Done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 398 at r2](https://reviewable.io/reviews/harness/harness-core/44798#-NPuaNBh2EvYFRH0VFVH:-NPuczYS1X52G5D-fvQ_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/46a83070544823de6fb7190ddeddae8470a68491/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L398)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

here we are declaring a variable in first line and using it in very next line. Lets combine these lines.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service/PipelineValidationServiceImpl.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/44798#-NPua0Ea6V-MEHD4dOLZ:-NPud-fV3jbvZCBFm1w_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/46a83070544823de6fb7190ddeddae8470a68491/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service/PipelineValidationServiceImpl.java#L53)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats the point of return type boolean if it always returns true.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service/PipelineValidationServiceImpl.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/44798#-NPua5AV5oPjLhIciX7z:-NPud05s-jNy9yzNgfZH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/46a83070544823de6fb7190ddeddae8470a68491/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service/PipelineValidationServiceImpl.java#L55)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can you use Object.equals as you dont know if this field is null
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44798)* status: 4 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44798)* status: :shipit: complete! ✓

**Pull request merged**
