### PR TITLE
[feat]: [CDS-32463]: adding proxy logic for azure

### PR DESCRIPTION
**Pull request by markoharness**
## Describe your changes
Utilizing proxy system properties to configure Azure SDK client as well as Azure Rest clients that we are creating/using.
These changes should cover all Azure services that we supporting both in CG and NG.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41599)

### CODE REVIEW

**Comment by markoharness** [comment]
trigger feature-build

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41599)* status: Some of the checks are too old. 17 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/helpers/ext/azure/AzureHelperService.java` line 342 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJ_iD2kBZAGp4qJDpWL:-NJ_iD2lDyHU5ZdxSJK5:bbq0t8) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/400-rest/src/main/java/software/wings/helpers/ext/azure/AzureHelperService.java#L342)):*
> ```Java
>   protected AzureResourceManager getAzureClient(AzureConfig azureConfig, String subscriptionId) {
>     try {
>       AzureEnvironment azureEnvironment = getAzureEnvironment(azureConfig.getAzureEnvironmentType());
> ```

Minor - get azureEnv, httpClient, azureProfile, retryPolicy, clientCredentials, getAzureHttpPipeline could be moved to separate method to avoid duplicated code.
___
*[`890-sm-delegate/src/main/java/io/harness/delegatetasks/NGAzureKeyVaultFetchEngineTask.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJ_j2eW-M_atqgDcLlq:-NJ_j2eW-M_atqgDcLlr:b-w0ztto) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/890-sm-delegate/src/main/java/io/harness/delegatetasks/NGAzureKeyVaultFetchEngineTask.java#L88)):*
> ```Java
>     List<Vault> vaultList = new ArrayList<>();
>     HttpClient httpClient = AzureUtils.getAzureHttpClient();
>     TokenCredential credentials =
> ```

qq, what is the difference between ClientSecretCredential and TokenCredential? The token is generated by the client secret and has ttl, right?  
Why do we need tokens only for Vault? 
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/azure/AzureDelegateHelperService.java` line 393 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJae7tWAPkNp3JqS3tH:-NJae7tWAPkNp3JqS3tI:bjr9a2t) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/930-delegate-tasks/src/main/java/software/wings/helpers/ext/azure/AzureDelegateHelperService.java#L393)):*
> ```Java
>     }
> 
>     OkHttpClient okHttpClient = okHttpClientBuilder.build();
> ```

Minor - could be a separate method like getOkHtttpClientWithProxy to avoid code duplication.
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/azure/AzureDelegateHelperService.java` line 503 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJadlRcASVvlJAzoxg4:-NJadlRd4CQtFpb0Sxsb:bydov6a) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/930-delegate-tasks/src/main/java/software/wings/helpers/ext/azure/AzureDelegateHelperService.java#L503)):*
> ```Java
>   protected AzureResourceManager getAzureClient(AzureConfig azureConfig, String subscriptionId) {
>     try {
>       AzureEnvironment azureEnvironment = getAzureEnvironment(azureConfig.getAzureEnvironmentType());
> ```

Minor - get azureEnv, httpClient, azureProfile, retryPolicy, clientCredentials, getAzureHttpPipeline could be moved to separate method to avoid duplicated code
___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 249 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJanO5TAZq5VQPyfDLK:-NJajlIs5-uZQh31BIww:b-pjfqb) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L249)):*
> ```Java
> 
>         String nonProxyHosts = System.getProperty("http.nonProxyHosts");
>         if (EmptyPredicate.isNotEmpty(nonProxyHosts)) {
> ```

Minor - does it make sense to log and non-proxy hosts?
___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 281 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJanECY0hWAcMBGuxAb:-NJanECY0hWAcMBGuxAc:b-6vf9iu) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L281)):*
> ```Java
>   }
> 
>   public synchronized HttpClient getAzureHttpClient() {
> ```

Are we consuming this HttpClient for all Azure API calls?
___
*[`970-api-services-beans/src/main/java/io/harness/azure/model/AzureConstants.java` line 325 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJanUYLAeMSZUfQd_tF:-NJanUYLAeMSZUfQd_tG:b-rv8nzy) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/970-api-services-beans/src/main/java/io/harness/azure/model/AzureConstants.java#L325)):*
> ```Java
>   int REST_CLIENT_CONNECT_TIMEOUT = 5;
>   int REST_CLIENT_READ_TIMEOUT = 10;
>   int REST_CLIENT_WRITE_TIMEOUT = 10;
> ```

How do we get these values, are they in seconds? 
___
*[`ce-nextgen/service/src/main/java/io/harness/ccm/connectors/CEAzureConnectorValidator.java` line 294 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJaf9Ff2uNRwCBAGb5w:-NJaf9Ff2uNRwCBAGb5x:bt5yyoe) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/ce-nextgen/service/src/main/java/io/harness/ccm/connectors/CEAzureConnectorValidator.java#L294)):*
> ```Java
>     try {
>       AzureProfile profile = new AzureProfile(tenantId, subscriptionId, AzureEnvironment.AZURE);
>       HttpClient httpClient = AzureUtils.getAzureHttpClient();
> ```

MInor - we could avoid every time calling separately AzureUtils.getAzureHttpClient(), could it be part of getAzureHttpPipeline method?

**Comment by markoharness** [comment]
*[`890-sm-delegate/src/main/java/io/harness/delegatetasks/NGAzureKeyVaultFetchEngineTask.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJ_j2eW-M_atqgDcLlq:-NJeCLJE0alxZZx91668:bguzzf6) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/890-sm-delegate/src/main/java/io/harness/delegatetasks/NGAzureKeyVaultFetchEngineTask.java#L88)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

qq, what is the difference between ClientSecretCredential and TokenCredential? The token is generated by the client secret and has ttl, right?  
Why do we need tokens only for Vault? 
</blockquote></details>

TokenCredential is an interface which all types of Azure credentials implement (ClientSecretCredential, ClientCertificateCredential, ManagedIdentityCredential...). For AKV we only have implemented connection using SPN with secret (represented by ClientSecretCredential). Token used by SDK calls has ttl and is cached. This is all handled by Azure SDK libs. We generate token credential every time we are using Azure SDK.

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 249 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJanO5TAZq5VQPyfDLK:-NJeDkXQElyQXaNwsuYg:b-jpztid) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L249)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - does it make sense to log and non-proxy hosts?
</blockquote></details>

Sure. Will add the logging for it.

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 281 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJanECY0hWAcMBGuxAb:-NJeDph569iAU0LYj7xR:b1adu01) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L281)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Are we consuming this HttpClient for all Azure API calls?
</blockquote></details>

This is only for call that we are making through Azure SDK libs.
Our Rest implemented calls have different HttpClient.

**Comment by markoharness** [comment]
*[`970-api-services-beans/src/main/java/io/harness/azure/model/AzureConstants.java` line 325 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJanUYLAeMSZUfQd_tF:-NJeEP2u9gMMK_8t0_fp:b-rb0rdx) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/970-api-services-beans/src/main/java/io/harness/azure/model/AzureConstants.java#L325)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

How do we get these values, are they in seconds? 
</blockquote></details>

They are in seconds. I can make them be of type Duration instead of int?

**Comment by markoharness** [comment]
*[`400-rest/src/main/java/software/wings/helpers/ext/azure/AzureHelperService.java` line 342 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJ_iD2kBZAGp4qJDpWL:-NJeElbM34BaMkRkxrgh:br2008n) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/400-rest/src/main/java/software/wings/helpers/ext/azure/AzureHelperService.java#L342)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - get azureEnv, httpClient, azureProfile, retryPolicy, clientCredentials, getAzureHttpPipeline could be moved to separate method to avoid duplicated code.
</blockquote></details>

I am not following. 
azureProfile, retryPolicy, clientCredentials, getAzureHttpPipeline are already abstracted into AzureUtils class.

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/azure/AzureDelegateHelperService.java` line 393 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJae7tWAPkNp3JqS3tH:-NJeFAn59FpVvU8YgDt5:b-obds08) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/930-delegate-tasks/src/main/java/software/wings/helpers/ext/azure/AzureDelegateHelperService.java#L393)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - could be a separate method like getOkHtttpClientWithProxy to avoid code duplication.
</blockquote></details>

I will check.

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/azure/AzureDelegateHelperService.java` line 503 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJadlRcASVvlJAzoxg4:-NJeFFRG8iUwZRMVKTyw:br2008n) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/930-delegate-tasks/src/main/java/software/wings/helpers/ext/azure/AzureDelegateHelperService.java#L503)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - get azureEnv, httpClient, azureProfile, retryPolicy, clientCredentials, getAzureHttpPipeline could be moved to separate method to avoid duplicated code
</blockquote></details>

I am not following. 
azureProfile, retryPolicy, clientCredentials, getAzureHttpPipeline are already abstracted into AzureUtils class.

**Comment by markoharness** [comment]
*[`ce-nextgen/service/src/main/java/io/harness/ccm/connectors/CEAzureConnectorValidator.java` line 294 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJaf9Ff2uNRwCBAGb5w:-NJeFQW-D-mbAwBbd9xM:bwagwb6) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/ce-nextgen/service/src/main/java/io/harness/ccm/connectors/CEAzureConnectorValidator.java#L294)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

MInor - we could avoid every time calling separately AzureUtils.getAzureHttpClient(), could it be part of getAzureHttpPipeline method? 
</blockquote></details>

No we can not. In some cases we are not creating HttpPipeline but HttpClient and passing it directly to Azure SDK API call.
Since there are quite a few places from where we are calling AzureUtils.getAzureHttpClient() and in order to avoid creating new object (connection pool as well) every time that is why we have caching for AzureHttpClient in AzureUtils class.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41599)* status: Some of the checks are too old. 17 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/helpers/ext/azure/AzureHelperService.java` line 342 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJ_iD2kBZAGp4qJDpWL:-NJocLOU0bbZ9QZlclDI:b-1yq8nz) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/400-rest/src/main/java/software/wings/helpers/ext/azure/AzureHelperService.java#L342)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

I am not following. 
azureProfile, retryPolicy, clientCredentials, getAzureHttpPipeline are already abstracted into AzureUtils class.

</blockquote></details>

I was thinking to put the whole logic AzureUtils calls to one private separate method here because there are identical calls in the second place in the same class.
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/azure/AzureDelegateHelperService.java` line 503 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJadlRcASVvlJAzoxg4:-NJod25_7MA6TkufiXkn:bstge6t) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/930-delegate-tasks/src/main/java/software/wings/helpers/ext/azure/AzureDelegateHelperService.java#L503)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

I am not following. 
azureProfile, retryPolicy, clientCredentials, getAzureHttpPipeline are already abstracted into AzureUtils class.

</blockquote></details>

the same as above
___
*[`970-api-services-beans/src/main/java/io/harness/azure/model/AzureConstants.java` line 325 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJanUYLAeMSZUfQd_tF:-NJodIutDXLC4euddbq0:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/970-api-services-beans/src/main/java/io/harness/azure/model/AzureConstants.java#L325)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

They are in seconds. I can make them be of type Duration instead of int?
</blockquote></details>

ok

**Comment by markoharness** [comment]
*[`400-rest/src/main/java/software/wings/helpers/ext/azure/AzureHelperService.java` line 342 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJ_iD2kBZAGp4qJDpWL:-NJzGoOU8Ah_SwNWoBaX:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/400-rest/src/main/java/software/wings/helpers/ext/azure/AzureHelperService.java#L342)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I was thinking to put the whole logic AzureUtils calls to one private separate method here because there are identical calls in the second place in the same class.
</blockquote></details>

done

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/azure/AzureDelegateHelperService.java` line 503 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJadlRcASVvlJAzoxg4:-NJzGrTL0xO6t2KUvPhz:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/930-delegate-tasks/src/main/java/software/wings/helpers/ext/azure/AzureDelegateHelperService.java#L503)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

the same as above
</blockquote></details>

done

**Comment by markoharness** [comment]
*[`970-api-services-beans/src/main/java/io/harness/azure/model/AzureConstants.java` line 325 at r2](https://reviewable.io/reviews/harness/harness-core/41599#-NJanUYLAeMSZUfQd_tF:-NJzGu1s7Oqj006zYXsh:b-ge0gwd) ([raw file](https://github.com/harness/harness-core/blob/703af818a5c246a5f5a64f13fe021004c4b262cb/970-api-services-beans/src/main/java/io/harness/azure/model/AzureConstants.java#L325)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Can not make them of type Duration because of the method api that uses them as int parameters. I have renamed them  so it is clear from the name.

**Comment by markoharness** [comment]
trigger feature-build

**Comment by markoharness** [comment]
trigger feature-build

**Review by ivan-83 — APPROVED** [review]
> Reviewed 8 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41599)* status: 21 file(s) to review. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/azure/AzureHelper.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/41599#-NKCguqMASlOKYYmiUXA:-NKCguqN3NpwlkKHH3in:b-q42t3l) ([raw file](https://github.com/harness/harness-core/blob/01d80a4fc3387bb3776adb7026cd695454ac8818/930-delegate-tasks/src/main/java/software/wings/helpers/ext/azure/AzureHelper.java#L27)):*
> ```Java
> @UtilityClass
> @Slf4j
> public class AzureHelper {
> ```

Minor - does it make sense to rename this to AzureCGHelper? 



_Code quote:_
```Java
/* START SECTION: only for CG */
```

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41599)* status: 21 file(s) to review. 1 of 2 approvals obtained.

**Comment by markoharness** [comment]
trigger feature-build

**Comment by markoharness** [comment]
trigger publish-delegate

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41599#-:-NKJJ7j94mAPuhwjfhTj:bnfp4nl)* status: 24 file(s) to review. 1 of 2 approvals obtained.

**Review by markoharness — COMMENTED** [review]
> Reviewed 12 of 14 files at r2, 4 of 9 files at r3, 5 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41599)* status: 24 file(s) to review. 1 of 2 approvals obtained.

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 12 of 14 files at r2, 4 of 9 files at r3, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41599)* status: :shipit: complete! ✓

**Pull request merged**
