### PR TITLE
feat: [PLG-1740]: SubscriptionDetail & moduleType model changes

### PR DESCRIPTION
**Pull request by thomas-grasman**
## Describe your changes
Each customer will have multiple licenses per subscription, so moduleType is no longer relevant.
To preserve their relationship, moduleLicense must point to subscriptionDetails.

Removed moduleType from subscriptionDetail
Added subscriptionId to moduleLicense

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43253)

### CODE REVIEW

**Review by pranil-harness — APPROVED** [review]

**Review by pranil-harness — DISMISSED** [review]

**Review by Xin-Harness — DISMISSED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43253)* status: 14 file(s) to review.

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43253)* status: Some of the checks are too old. 14 file(s) to review. 1 change requests. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/ModuleLicenseToSubscriptionMigration.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhadWIDAbRaI0yhXoq:-NOhadWJ9_gkEJlk0s5j:b-3xs90h) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/ModuleLicenseToSubscriptionMigration.java#L33)):*
> ```Java
> 
>   @Override
>   public void migrate() {
> ```

Make sure this migration has 3 properties i.e. rollback support, idempotent support and immutable migrations.
And after merging this PR raise a OPS ticket and get it approved from @DBRE team.
Just informing you because migrations have become burning topic recently.
___
*[`930-ng-license-manager/src/main/java/io/harness/repositories/SubscriptionDetailRepository.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhffE97yAcUiFud-_j:-NOhffE97yAcUiFud-_k:bs2hi7r) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/930-ng-license-manager/src/main/java/io/harness/repositories/SubscriptionDetailRepository.java#L2)):*
> ```Java
> /*
>  * Copyright 2023 Harness Inc. All rights reserved.
> ```

I don't think this is required because these are auto-generated header comments for polyform licensing.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/entities/SubscriptionDetail.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhfhBUCl3zrMoO0MZL:-NOhfhBUCl3zrMoO0MZM:bj8bld6) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/930-ng-license-manager/src/main/java/io/harness/subscription/entities/SubscriptionDetail.java#L2)):*
> ```Java
> /*
>  * Copyright 2023 Harness Inc. All rights reserved.
> ```

same as above.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/handlers/InvoicePaymentSucceedHandler.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhfkTI8B00RYEEdEWg:-NOhfkTI8B00RYEEdEWh:bj8bld6) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/930-ng-license-manager/src/main/java/io/harness/subscription/handlers/InvoicePaymentSucceedHandler.java#L2)):*
> ```Java
> /*
>  * Copyright 2023 Harness Inc. All rights reserved.
> ```

same as above.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/resource/SubscriptionResource.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhfnF7AiHm30EeyH-C:-NOhfnF7AiHm30EeyH-D:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/930-ng-license-manager/src/main/java/io/harness/subscription/resource/SubscriptionResource.java#L2)):*
> ```Java
> /*
>  * Copyright 2023 Harness Inc. All rights reserved.
> ```

same as above
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/SubscriptionService.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhfpL3B_MlANaq52cV:-NOhfpL3B_MlANaq52cW:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/930-ng-license-manager/src/main/java/io/harness/subscription/services/SubscriptionService.java#L2)):*
> ```Java
> /*
>  * Copyright 2023 Harness Inc. All rights reserved.
> ```

same as above
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java` line 163 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhcaIr1g-vPLo1vxmF:-NOhcaIr1g-vPLo1vxmG:b-jmlg5o) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java#L163)):*
> ```Java
>     List<SubscriptionDetail> subscriptionDetailList =
>         subscriptionDetailRepository.findByAccountIdentifier(accountIdentifier);
>     if (!subscriptionDetailList.isEmpty()) {
> ```

what happens when subscriptionDetailList is empty?
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java` line 238 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhcuu49ncYwH-V0QFc:-NOhcuu49ncYwH-V0QFd:btrgw0y) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java#L238)):*
> ```Java
>     isSelfServiceEnable();
> 
>     // TODO: transaction control in case any race condition
> ```

you can resolve this TODO if done or either remove it.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java` line 257 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhdX740As_-EIWuwX5:-NOhdX740As_-EIWuwX6:bqngndz) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java#L257)):*
> ```Java
>     List<SubscriptionDetail> subscriptionDetailList =
>         subscriptionDetailRepository.findByAccountIdentifier(accountIdentifier);
>     if (!subscriptionDetailList.isEmpty()) {
> ```

same as above, what happens when subscriptionDetailList is empty?
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java` line 327 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOheluXB8FFhUUykfw1:-NOheluZCoKYkDLKVA1o:b-6u903t) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java#L327)):*
> ```Java
>     Optional<Subscription> subscription = stripeHelper.searchSubscription(accountIdentifier);
> 
>     if (!subscription.isPresent()) {
> ```

you can use below for simplicity:
if (subscription.isEmpty()) {}
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java` line 377 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhf0U34CbqeVjPyb_3:-NOhf0U34CbqeVjPyb_4:bfz4tj5) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java#L377)):*
> ```Java
>           StripeSubscriptionRequest.builder().subscriptionId(subscriptionDetail.getSubscriptionId()).build());
>     }
>     return null;
> ```

do not return null rather return optional and let the caller method take decision if response is empty 
___
*[`935-subscription-sdk/src/main/java/io/harness/subscription/helpers/StripeHelper.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhfttEDNkgxf3No2LA:-NOhfttEDNkgxf3No2LB:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/935-subscription-sdk/src/main/java/io/harness/subscription/helpers/StripeHelper.java#L2)):*
> ```Java
> /*
>  * Copyright 2023 Harness Inc. All rights reserved.
> ```

same as above
___
*[`935-subscription-sdk/src/main/java/io/harness/subscription/helpers/impl/StripeHandlerImpl.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhfvLk4pNozpEd2Kxu:-NOhfvLk4pNozpEd2Kxv:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/935-subscription-sdk/src/main/java/io/harness/subscription/helpers/impl/StripeHandlerImpl.java#L2)):*
> ```Java
> /*
>  * Copyright 2023 Harness Inc. All rights reserved.
> ```

same as above
___
*[`935-subscription-sdk/src/main/java/io/harness/subscription/helpers/impl/StripeHelperImpl.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhfwh56Ed1r3lWb0xn:-NOhfwh56Ed1r3lWb0xo:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/935-subscription-sdk/src/main/java/io/harness/subscription/helpers/impl/StripeHelperImpl.java#L2)):*
> ```Java
> /*
>  * Copyright 2023 Harness Inc. All rights reserved.
> ```

same as above
___
*[`950-subscription-beans/src/main/java/io/harness/subscription/dto/SubscriptionDetailDTO.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhfyjzEAixYm1qqRxY:-NOhfyjzEAixYm1qqRxZ:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/950-subscription-beans/src/main/java/io/harness/subscription/dto/SubscriptionDetailDTO.java#L2)):*
> ```Java
> /*
>  * Copyright 2023 Harness Inc. All rights reserved.
> ```

same as above
___
*[`950-subscription-beans/src/main/java/io/harness/subscription/params/SubscriptionItemRequest.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhg-B3B9oFlpP3LDMn:-NOhg-B3B9oFlpP3LDMo:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/950-subscription-beans/src/main/java/io/harness/subscription/params/SubscriptionItemRequest.java#L2)):*
> ```Java
> /*
>  * Copyright 2023 Harness Inc. All rights reserved.
> ```

same as above
___
*[`950-subscription-beans/src/main/java/io/harness/subscription/params/SubscriptionRequest.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhg0Pz43mlbpVgaH3a:-NOhg0Pz43mlbpVgaH3b:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/950-subscription-beans/src/main/java/io/harness/subscription/params/SubscriptionRequest.java#L2)):*
> ```Java
> /*
>  * Copyright 2023 Harness Inc. All rights reserved.
> ```

same as above

**Review by thomas-grasman — COMMENTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43253)* status: Some of the checks are too old. 14 file(s) to review. 1 change requests.

**Review by thomas-grasman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43253)* status: 14 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/ModuleLicenseToSubscriptionMigration.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhadWIDAbRaI0yhXoq:-NOtmXKR-oyydEJpkkzE:b-st4jqk) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/ModuleLicenseToSubscriptionMigration.java#L33)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

Make sure this migration has 3 properties i.e. rollback support, idempotent support and immutable migrations.
And after merging this PR raise a OPS ticket and get it approved from @DBRE team.
Just informing you because migrations have become burning topic recently.
</blockquote></details>

Understood. Thanks for your guidance on this.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java` line 163 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhcaIr1g-vPLo1vxmF:-NOtp63D29FDfyxM2rGb:b-mkof7q) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java#L163)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

what happens when subscriptionDetailList is empty?
</blockquote></details>

Functionality isn't changed here. It will simply not apply a subcriptionId to the request. The list will only have one subscription with this release, but in another iteration, there could be up to two; one for monthly subscriptions and one for yearly. I'll have to add a new method for choosing which one is requested.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java` line 238 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhcuu49ncYwH-V0QFc:-NOtqOtDD-LrcyfMbb3n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java#L238)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

you can resolve this TODO if done or either remove it.
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java` line 257 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhdX740As_-EIWuwX5:-NOtqQUsAENTPSzxKYFG:b-q64pkt) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java#L257)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

same as above, what happens when subscriptionDetailList is empty?
</blockquote></details>

See above.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java` line 377 at r1](https://reviewable.io/reviews/harness/harness-core/43253#-NOhf0U34CbqeVjPyb_3:-NOu49TJ3S4aR54niY0C:b-x0z6oe) ([raw file](https://github.com/harness/harness-core/blob/a675160759e35d6d51cd9c7e75978852260b3e57/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java#L377)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

do not return null rather return optional and let the caller method take decision if response is empty 
</blockquote></details>

I threw an exception here. This felt more appropriate when a subscription is not present and conformed to the other methods in this class.

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43253)* status: 14 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained.

**Review by thomas-grasman — COMMENTED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43253)* status: 14 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained.

**Review by kapil-harness — APPROVED** [review]
> Reviewed 2 of 14 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43253)* status: :shipit: complete! ✓

**Pull request merged**
