### PR TITLE
feat: [PL-25008]: added error handling for getting default branch

### PR DESCRIPTION
**Pull request by bhavya181**
Internally this method calls getUserRepo scm API, which basically gives the details of the repo and from there we are getting default branch of that repo, now error handling is added on getDefaultBranch method as user should get correct error message, no matter internally how we are getting the default branch.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32987)

### CODE REVIEW

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32987)* status: 19 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 143 at r2](https://reviewable.io/reviews/harness/harness-core/32987#-N1iX22f6qUZaJxDGdbx:-N1mLDIPCgpGvYheLK8z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cb3b9b7bb5750b774b5a89bc84a650a2ac5f95ca/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L143)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets call this method directly in the getDefaultBranch API. If we try to use getRepoDetails, then in future if we want to expose this method as an API, then we would be adding error handling on it. Then it would create conflicts as it would throw error directly and not allow getDefaultBranch() to handle -ve cases as per its own implementation.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/ScmErrorExplanations.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/32987#-N1ipO_uE5GsQGXyRzG7:-N1mLVIR5wZyaViltwt0:b3vlukj) ([raw file](https://github.com/harness/harness-core/blob/cb3b9b7bb5750b774b5a89bc84a650a2ac5f95ca/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/ScmErrorExplanations.java#L20)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Can we also specify which credentials?

Can we explicitly say that 

   The personal access token provided .... 
</blockquote></details>

This is the hint  for it (Please check your Github credentials if they are valid or not), which will come first, and also we can say PAT for github, but for bitbucket if username is wrong then also this error will come, that's why kept credentials at both plcaes, but yes for github we can explicitly say PAT.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/ScmErrorExplanations.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/32987#-N1ipa1I7YwS-t7VVM4E:-N1mLLV_4Owm5GQBck5P:b32a548) ([raw file](https://github.com/harness/harness-core/blob/cb3b9b7bb5750b774b5a89bc84a650a2ac5f95ca/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/ScmErrorExplanations.java#L21)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

repo -> repository

Provided -> The
</blockquote></details>

Response message: Please check if requested Github repository exists or not.
                  Fetching default branch from Github failed. Provided Github repo does not exist or has been deleted.
                  Received exception while calling git api  - Status: 404 Not Found. 
I have changed repo to repository but should I remove provided??

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32987)* status: 19 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketGetDefaultBranchScmApiErrorHandler.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/32987#-N1ipBJn39OHsQoTeSFb:-N1mMbE-5qhz3yWiOfVq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cb3b9b7bb5750b774b5a89bc84a650a2ac5f95ca/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketGetDefaultBranchScmApiErrorHandler.java#L26)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

we can rename it to GET_DEFAULT_BRANCH_FAILED_MESSAGE
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListBranchesScmApiErrorHandler.java` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/32987#-N1ipHzL8-sITew4ZgdH:-N1mMagc27GEUyFUchvJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cb3b9b7bb5750b774b5a89bc84a650a2ac5f95ca/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListBranchesScmApiErrorHandler.java#L32)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

same here append message to the string
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListRepoScmApiErrorHandler.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/32987#-N1ipKyi-RpRsdheczGT:-N1mMaDK8AR8kdnKLXes:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cb3b9b7bb5750b774b5a89bc84a650a2ac5f95ca/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketListRepoScmApiErrorHandler.java#L31)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 4 of 4 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32987)* status: 19 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 8 of 19 files at r1, 3 of 4 files at r3, 6 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32987#-:-N1r5Fe7BPWImZDr5pom:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
