### PR TITLE
fix: [PL-26303]: The SSO Settings of NG should not check the CG License

### PR DESCRIPTION
**Pull request by DeepakPatankar**
## Describe your changes
The customer had an ESSENTIALS license in CG and Team license in NG. Still, they were not able to enable SSO in NG.

I checked the code and found out that the SSO code in NG calls the CG code. This means both NG and CG license is applied.

This code fixes that license check should be skipped for NG calls

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35151)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/intfc/SSOService.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/35151#-N6fsn-9-832A5Ye8hxD:-N6fsn-9-832A5Ye8hxE:b8ajlot) ([raw file](https://github.com/harness/harness-core/blob/12fcd8da99f65ceeaffcc3bfce4aa3272eabc0f0/400-rest/src/main/java/software/wings/service/intfc/SSOService.java#L37)):*
> ```Java
> @TargetModule(HarnessModule._950_NG_AUTHENTICATION_SERVICE)
> public interface SSOService {
>   SSOConfig uploadSamlConfiguration(String accountId, InputStream inputStream, String displayName,
> ```

I think it will be a good idea to overload the method here: one with flag, one without. That way we don't change anything existing not using the current method and make the new one point to the newly overloaded one.

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35151)* status: Some of the checks are too old. 8 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/intfc/SSOService.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/35151#-N6fsn-9-832A5Ye8hxD:-N6h7UlU0bXmPNTk6Wol:bz96aua) ([raw file](https://github.com/harness/harness-core/blob/12fcd8da99f65ceeaffcc3bfce4aa3272eabc0f0/400-rest/src/main/java/software/wings/service/intfc/SSOService.java#L37)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

I think it will be a good idea to overload the method here: one with flag, one without. That way we don't change anything existing not using the current method and make the new one point to the newly overloaded one. 
</blockquote></details>

The code for NG and CG is same, hence I didn't create a separate function for NG.

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35151)* status: 12 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/intfc/SSOService.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/35151#-N6fsn-9-832A5Ye8hxD:-N6h7uI7E9PO5ZtaxZbV:bxhd6kt) ([raw file](https://github.com/harness/harness-core/blob/12fcd8da99f65ceeaffcc3bfce4aa3272eabc0f0/400-rest/src/main/java/software/wings/service/intfc/SSOService.java#L37)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

The code for NG and CG is same, hence I didn't create a separate function for NG.
</blockquote></details>

@pbarapatre10 Can you please check is fine. Since the same code is being called from both ng and cg, I had to pass the variable.

If I created a different variable then I would have to copy the credentials

**Review by ujjawal-harness — APPROVED** [review]
:lgtm:

> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35151#-:-N6vGT6t-7L0lwWKtCOi:bnfp4nl)* status: 12 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by DeepakPatankar** [comment]
trigger messagecheck

**Review by mitishapandey — APPROVED** [review]

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35151)* status: :shipit: complete! ✓

**Pull request merged**
