### PR TITLE
[fix]: [CDS-82723]: Adding validation for manifest types while creating overrides V2

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes
This PR adds validation for manifest types while creating overrides V2. 
Also, added support to update overrides (created via terraform provider) via UI.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54682)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/output/BUILD.bazel` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/54682#-NhjadngBel46J4GmtSJ:-NhjadngBel46J4GmtSK:b-g7kwur) ([raw file](https://github.com/harness/harness-core/blob/8268d5fcefd99a21d6d7d4cfd7a3eb4fdae0dcac/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/output/BUILD.bazel#L15)):*
> ```Starlark
>     deps = [
>         "//:lombok",
>         "//127-cd-nextgen-entities:module",
> ```

Does it need to refer to entire 127 module ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/output/NgConfigFilesMetadataSweepingOutput.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/54682#-NhjaiH34gg9Jiw-KADv:-NhjaiH34gg9Jiw-KADw:b7d4988) ([raw file](https://github.com/harness/harness-core/blob/8268d5fcefd99a21d6d7d4cfd7a3eb4fdae0dcac/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/output/NgConfigFilesMetadataSweepingOutput.java#L34)):*
> ```Java
> @JsonTypeName("NgConfigFilesMetadataSweepingOutput")
> @TypeAlias("ngConfigFileMetadataSweepingOutput")
> @RecasterAlias("io.harness.cdng.configfile.steps.output.NgConfigFilesMetadataSweepingOutput")
> ```

we should not change the recaster alias
You can just change the package and keep the alias same

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/outcome/BUILD.bazel` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/54682#-Nhjaq_M9tTNvlgcVXrZ:-Nhjaq_M9tTNvlgcVXr_:b-g7kwur) ([raw file](https://github.com/harness/harness-core/blob/8268d5fcefd99a21d6d7d4cfd7a3eb4fdae0dcac/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/outcome/BUILD.bazel#L15)):*
> ```Starlark
>     deps = [
>         "//:lombok",
>         "//127-cd-nextgen-entities:module",
> ```

Does it need to refer to entire 127 module ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/outcome/ServiceHooksMetadataSweepingOutput.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/54682#-Nhjazi79tL8hoNIgHog:-Nhjazi79tL8hoNIgHoh:bp8e0zc) ([raw file](https://github.com/harness/harness-core/blob/8268d5fcefd99a21d6d7d4cfd7a3eb4fdae0dcac/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/outcome/ServiceHooksMetadataSweepingOutput.java#L28)):*
> ```Java
> @JsonTypeName("ServiceHooksMetadataSweepingOutput")
> @TypeAlias("serviceHooksMetadataSweepingOutput")
> @RecasterAlias("io.harness.cdng.hooks.steps.outcome.ServiceHooksMetadataSweepingOutput")
> ```

we should not change the recaster alias  
You can just change the package and keep the alias same

**Comment by yogesh-chauhan** [comment]
Please write UTs for ServiceOverridesServiceV2Impl.java

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 14 of 22 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54682)* status: 22 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/54682#-NhjaX7239wPtN0_WI_T:-NhjaX7311mwV-60Vwwe:b-c1jddj) ([raw file](https://github.com/harness/harness-core/blob/8268d5fcefd99a21d6d7d4cfd7a3eb4fdae0dcac/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java#L28)):*
> ```Java
> import io.harness.cdng.configfile.ConfigFileAttributes;
> import io.harness.cdng.configfile.ConfigFileWrapper;
> import io.harness.cdng.configfile.steps.output.NgConfigFilesMetadataSweepingOutput;
> ```

we have just added an import to this class ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 26 of 26 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54682)* status: 26 file(s) to review. 0 of 2 approvals obtained.

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger checkstylecodeformat

**Comment by lovish1999** [comment]
trigger commonchecks

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by lovish1999** [comment]
trigger pmd

**Comment by lovish1999** [comment]
trigger codebasehash

**Comment by lovish1999** [comment]
trigger gitleaks

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54682)* status: 27 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 26 of 26 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54682#-:-NhlGHAZ8hS2RPemlIqP:bnfp4nl)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/constants/ServiceOverrideConstants.java` line 32 at r4](https://reviewable.io/reviews/harness/harness-core/54682#-NhlFkoG2I7MW03C8l9S:-NhlFkoG2I7MW03C8l9T:b-w2uc30) ([raw file](https://github.com/harness/harness-core/blob/5087e2e66030d0ce68a5493597213d6828e965d9/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/constants/ServiceOverrideConstants.java#L32)):*
> ```Java
> @UtilityClass
> public class ServiceOverrideConstants {
>   public static Map<String, String> overrideMapper = Map.of(SERVICE.toString(), "service",
> ```

Minor: overriderMapper should be upper-case.

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger review

**Pull request merged**
