### PR TITLE
[feat]: [CDS-39653]: removed hard delete ff from templates

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36032)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36032)

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36032)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 77 at r2](https://reviewable.io/reviews/harness/harness-core/36032#-N8cxVJ49zbbP9g4cWw6:-N8cxVJ49zbbP9g4cWw7:b2tbf9f) ([raw file](https://github.com/harness/harness-core/blob/98caffbc699ac216f688b2cd9e88ccabe4d1f6b6/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L77)):*
> ```Java
>   private final NGTemplateRepository templateRepository;
>   private GitSyncSdkService gitSyncSdkService;
>   private final NGTemplateFeatureFlagHelperService ngTemplateFeatureFlagHelperService;
> ```

let's remove this dependency as well.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36032)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 77 at r2](https://reviewable.io/reviews/harness/harness-core/36032#-N8cxVJ49zbbP9g4cWw6:-N8d95Qq9X1wk7iskLhQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/98caffbc699ac216f688b2cd9e88ccabe4d1f6b6/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L77)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

let's remove this dependency as well.
</blockquote></details>

Done.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36032)* status: 1 change requests. 1. unresolved discussions.

**Review by inderschera — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36032)* status: :shipit: complete! ✓

**Pull request merged**
