### PR TITLE
fix: [PIE-3811]: CI builds with approval stages are being displayed i…

### PR DESCRIPTION
**Pull request by prashantsharma04**
…n the CD deployments

Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33425)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33425)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by brijeshdhakar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33425)* status: 1 file(s) to review.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33425)* status: :shipit: complete! ✓

**Pull request merged**
