### PR TITLE
feat: [PL-27792]: Adding New Service API

### PR DESCRIPTION
**Pull request by TarunUba1**
…d test cases, done validation and sorting as per requirements

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37869)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* Code issue 6 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37869)

**Comment by TarunUba1** [comment]
trigger messagecheck

**Comment by TarunUba1** [comment]
trigger messagecheck

**Comment by TarunUba1** [comment]
trigger messagecheck

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37869)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceApiUtils.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/37869#-NCuDuSq9j7bptWRC1DK:-NCuDuSq9j7bptWRC1DL:b-w83ad5) ([raw file](https://github.com/harness/harness-core/blob/9ef16542ce70ce4efe8596ca3e66c29e303ba8ab/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceApiUtils.java#L72)):*
> ```Java
>     return serviceResponse;
>   }
>   public ServiceResponse getAccessListResponse(ServiceEntity serviceEntity) {
> ```

we should have a better name here for eg. mapToAccessListResponse etc
also, in other method below

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceApiUtils.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/37869#-NCuDn4mB12vAY2c_kZ0:-NCuDn4mB12vAY2c_kZ1:bb61elw) ([raw file](https://github.com/harness/harness-core/blob/9ef16542ce70ce4efe8596ca3e66c29e303ba8ab/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceApiUtils.java#L43)):*
> ```Java
> import javax.ws.rs.core.Response.ResponseBuilder;
> 
> public class ServiceResourceApiUtils {
> ```

should be singleton

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServicesApiImpl.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/37869#-NCuBiQ58tQdpycqJ-2b:-NCuBiQ58tQdpycqJ-2c:b-9ct7e2) ([raw file](https://github.com/harness/harness-core/blob/9ef16542ce70ce4efe8596ca3e66c29e303ba8ab/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServicesApiImpl.java#L67)):*
> ```Java
> import org.springframework.data.mongodb.core.query.Criteria;
> 
> @OwnedBy(PL)
> ```

ownedby = CDC

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37869)* status: 4 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceApiUtils.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/37869#-NCuDn4mB12vAY2c_kZ0:-NCxOE1B8A9tIfbOaIdr:bs7wumb) ([raw file](https://github.com/harness/harness-core/blob/9ef16542ce70ce4efe8596ca3e66c29e303ba8ab/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceApiUtils.java#L43)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should be singleton
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceApiUtils.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/37869#-NCuDqP3486JbNbehwp5:-NCxOH0N81z3LhAGeolE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ef16542ce70ce4efe8596ca3e66c29e303ba8ab/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceApiUtils.java#L52)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should have a better name here for eg. mapToServiceResponse etc
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceApiUtils.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/37869#-NCuDuSq9j7bptWRC1DK:-NCxOI1O8mHbisJZvnah:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ef16542ce70ce4efe8596ca3e66c29e303ba8ab/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceApiUtils.java#L72)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should have a better name here for eg. mapToAccessListResponse etc
also, in other method below
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServicesApiImpl.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/37869#-NCuBiQ58tQdpycqJ-2b:-NCxOLOq0rtZdlVw12SJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ef16542ce70ce4efe8596ca3e66c29e303ba8ab/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServicesApiImpl.java#L67)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

ownedby = CDC
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServicesApiImpl.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/37869#-NCuCvn86iZ_VT6eWPKc:-NCxS2uC69PflvwdxVS_:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9ef16542ce70ce4efe8596ca3e66c29e303ba8ab/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServicesApiImpl.java#L88)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we use constants from some java util class https://docs.oracle.com/javase/6/docs/api/java/net/HttpURLConnection.html
</blockquote></details>

Done
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServicesApiImpl.java` line 161 at r1](https://reviewable.io/reviews/harness/harness-core/37869#-NCuDTxxAR9n7_8X6eaf:-NCxPzwX9n6YC2yKCF52:b-dvmn06) ([raw file](https://github.com/harness/harness-core/blob/9ef16542ce70ce4efe8596ca3e66c29e303ba8ab/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServicesApiImpl.java#L161)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

why is this needed ?
</blockquote></details>

For Pagination

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37869)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Pull request closed without merging**
