### PR TITLE
feat: [SRM-14830]: Sending notification after the firehydrant incident

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Describe your changes

- added the flow when the custom change event will be getting registered through our webhook URL and if, in the payload, it will have a webhook URL. MSHealthReport will be generated and sent to the slack channel.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49205)

### CODE REVIEW

**Comment by karansaraswat19** [comment]
trigger uts

**Comment by karansaraswat19** [comment]
trigger tests

**Comment by karansaraswat19** [comment]
trigger uts

**Comment by karansaraswat19** [comment]
trigger uts

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49205)* status: 31 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/FireHydrantTemplateDataGenerator.java` line 86 at r5](https://reviewable.io/reviews/harness/harness-core/49205#-NXxGxc68pLGxlVIn6pO:-NXxGxc68pLGxlVIn6pP:b-i5p92x) ([raw file](https://github.com/harness/harness-core/blob/a4a9c260356da9c18080a1ac1d19b5a3e89d9e2f/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/FireHydrantTemplateDataGenerator.java#L86)):*
> ```Java
>         ResourceParams resourceParams =
>             ScopedInformation.getResourceParamsFromScopedIdentifier(sloDetails.getScopedMonitoredServiceIdentifier());
>         sb.append("*SLO Name*: ")
> ```

we can keep this as a template with variables and replace them in here.

eg. *SLO TARGET*: $SLOTARGET ... and then replace all variable with slo target.
will be more scalable. and less prone to errors as well.

**Comment by karansaraswat19** [comment]
trigger uts

**Review by deepak-harness — DISMISSED** [review]
> Reviewed 19 of 27 files at r1, 5 of 7 files at r3, 3 of 7 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49205)* status: Some of the checks are too old.

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed 19 of 27 files at r1, 5 of 7 files at r3, 3 of 7 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49205)* status: Some of the checks are too old. 1 change requests. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/api/NotificationRuleTemplateDataGenerator.java` line 99 at r6](https://reviewable.io/reviews/harness/harness-core/49205#-NYHtW9T7NCTVkth3ND3:-NYHtW9T7NCTVkth3ND4:b-qcteyd) ([raw file](https://github.com/harness/harness-core/blob/3ca81ce2cc6aef6fc3c97bb302b36c9874a5bac6/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/api/NotificationRuleTemplateDataGenerator.java#L99)):*
> ```Java
>         put(START_DATE, startDate);
>         put(URL, getUrl(baseUrl, projectParams, entityDetails.get(ENTITY_IDENTIFIER).toString(), endTime));
>         put(getEntityName(), entityDetails.get(ENTITY_NAME).toString());
> ```

Use default value if not present in the map. Also log the error if these values are not present 



_Code quote:_
```Java
        put(URL, getUrl(baseUrl, projectParams, entityDetails.get(ENTITY_IDENTIFIER).toString(), endTime));
        put(getEntityName(), entityDetails.get(ENTITY_NAME).toString());
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/FireHydrantTemplateDataGenerator.java` line 108 at r6](https://reviewable.io/reviews/harness/harness-core/49205#-NYHvVmB-5TSAG7tdkhi:-NYHvVmB-5TSAG7tdkhj:bov2qb4) ([raw file](https://github.com/harness/harness-core/blob/3ca81ce2cc6aef6fc3c97bb302b36c9874a5bac6/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/FireHydrantTemplateDataGenerator.java#L108)):*
> ```Java
>           String variable = String.format("${%s}", key);
>           sloPerformanceSection[0] = new StringBuilder(sloPerformanceSection[0].toString().replace(variable, value));
>         });
> ```

You can directly use string.replace here. Make sure your template is a non final variable.



_Code quote:_
```Java
        final StringBuilder[] sloPerformanceSection = {new StringBuilder(SLO_PERFORMANCE_SECTION)};
        templateDataMap.forEach((key, value) -> {
          String variable = String.format("${%s}", key);
          sloPerformanceSection[0] = new StringBuilder(sloPerformanceSection[0].toString().replace(variable, value));
        });
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/FireHydrantTemplateDataGenerator.java` line 143 at r6](https://reviewable.io/reviews/harness/harness-core/49205#-NYHwM8m83xjleWYi20U:-NYHwM8m83xjleWYi20V:bezfnv6) ([raw file](https://github.com/harness/harness-core/blob/3ca81ce2cc6aef6fc3c97bb302b36c9874a5bac6/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/FireHydrantTemplateDataGenerator.java#L143)):*
> ```Java
>         return "No health score data available for the last hour";
>     }
>   }
> ```

nit: this is duplicated, see how we can avoid that.



_Code quote:_
```Java
  private String getServiceHealthMessage(RiskData currentHealthScore) {
    switch (currentHealthScore.getRiskStatus()) {
      case HEALTHY:
        return String.format(
            "The service health remained healthy with a score of %s%%", currentHealthScore.getHealthScore());
      case OBSERVE:
        return String.format(
            "The service health needs to be observed. It has a score of %s%%", currentHealthScore.getHealthScore());
      case NEED_ATTENTION:
        return String.format(
            "The service health needs attention. It has a score of %s%%", currentHealthScore.getHealthScore());
      case UNHEALTHY:
        return String.format(
            "The service health remained unhealthy with a score of %s%%", currentHealthScore.getHealthScore());
      case NO_DATA:
      case NO_ANALYSIS:
      default:
        return "No health score data available for the last hour";
    }
  }
```

**Review by karansaraswat19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49205)* status: Some of the checks are too old. 1 change requests. 2. unresolved discussions. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/api/NotificationRuleTemplateDataGenerator.java` line 99 at r6](https://reviewable.io/reviews/harness/harness-core/49205#-NYHtW9T7NCTVkth3ND3:-NYITp-26K9LIKCRY7cM:be0oj7z) ([raw file](https://github.com/harness/harness-core/blob/3ca81ce2cc6aef6fc3c97bb302b36c9874a5bac6/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/api/NotificationRuleTemplateDataGenerator.java#L99)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

Use default value if not present in the map. Also log the error if these values are not present 
</blockquote></details>

I am not able to log the notification type as we don't have the type of notification here
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/FireHydrantTemplateDataGenerator.java` line 108 at r6](https://reviewable.io/reviews/harness/harness-core/49205#-NYHvVmB-5TSAG7tdkhi:-NYITybj1f4v6Vwbe8Ps:bjd7a22) ([raw file](https://github.com/harness/harness-core/blob/3ca81ce2cc6aef6fc3c97bb302b36c9874a5bac6/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/FireHydrantTemplateDataGenerator.java#L108)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

You can directly use string.replace here. Make sure your template is a non final variable.
</blockquote></details>

replaced StringBuilder with String

**Comment by karansaraswat19** [comment]
trigger uts

**Review by Varsha-lalwani — COMMENTED** [review]
> Reviewed 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49205)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained.

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49205#-:-NYIpL6P5cTP3HLlBUr5:bnfp4nl)* status: 2. unresolved discussions.

**Pull request merged**
