### PR TITLE
fix: [CDS-44557]: added json filter for Harness Approval

### PR DESCRIPTION
**Pull request by naman-goenka**
## Describe your changes
This is solved by adding a json filter for this step, and adding the validation for scopes of usergroups used should be lower / equal to creation context (which can be step / template etc. ). Now we should not see such scenarios wherein we can save a harness approval template containing user groups from higher scopes.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41974)

### CODE REVIEW

**Comment by naman-goenka** [comment]
trigger messagecheck

**Review by utkarshchoubey-harness — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41974#-:-NK2Yo8K3RK2FfroA1lL:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by vivekkarnatiharness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41974)* status: :shipit: complete! ✓

**Review by vcalasansh — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41974)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/41974#-NKBtoKx3xH9j2m04oWk:-NKBtoKx3xH9j2m04oWl:b-9y1rmz) ([raw file](https://github.com/harness/harness-core/blob/bee6380e1def231830404fb02c2953f2882137c9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L57)):*
> ```Java
>                                   .build();
>     List<String> userGroupsIds =
>         ApproversDTO.fromApprovers(harnessApprovalSpecParameters.getApprovers()).getUserGroups();
> ```

can ``` ApproversDTO.fromApprovers(harnessApprovalSpecParameters.getApprovers())``` be null ?

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/41974#-NKBtz0W94YRZDGy1ep1:-NKBtz0W94YRZDGy1ep2:b55smlm) ([raw file](https://github.com/harness/harness-core/blob/bee6380e1def231830404fb02c2953f2882137c9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L68)):*
> ```Java
>       }
>     });
>     if (!isEmpty(userGroupsIdsWithInvalidScope)) {
> ```

nit: you can use isNotEmpty instead

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41974)* status: :shipit: complete! ✓

**Comment by naman-goenka** [comment]
> _[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/41974#-NKBtoKx3xH9j2m04oWk:-NKBtoKx3xH9j2m04oWl:b-9y1rmz) ([raw file](https://github.com/harness/harness-core/blob/bee6380e1def231830404fb02c2953f2882137c9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L57)):_
> 
> > ```java
> >                                   .build();
> >     List<String> userGroupsIds =
> >         ApproversDTO.fromApprovers(harnessApprovalSpecParameters.getApprovers()).getUserGroups();
> > ```
> 
> can ` ApproversDTO.fromApprovers(harnessApprovalSpecParameters.getApprovers())` be null ?

Not possible in this flow.
```
  @NotNull @VariableExpression(skipVariableExpression = true) Approvers approvers;
```
in HarnessApprovalStepInfo.java

and approvers is a non empty list in ``ApproversDTO.fromApprovers``

**Comment by naman-goenka** [comment]
> _[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/41974#-NKBtz0W94YRZDGy1ep1:-NKBtz0W94YRZDGy1ep2:b55smlm) ([raw file](https://github.com/harness/harness-core/blob/bee6380e1def231830404fb02c2953f2882137c9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L68)):_
> 
> > ```java
> >       }
> >     });
> >     if (!isEmpty(userGroupsIdsWithInvalidScope)) {
> > ```
> 
> nit: you can use isNotEmpty instead

Corrected

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41974)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41974)* status: Some of the checks are too old.

**Comment by naman-goenka** [comment]
trigger ti1

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41974)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41974)* status: :shipit: complete! ✓

**Pull request merged**
