### PR TITLE
fix: [DEL-4384]: set delegate token name in global context data

### PR DESCRIPTION
**Pull request by arpit3107**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34741)

### CODE REVIEW

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34741)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34741)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/34741#-N5dobxb4XAntXIFpc1B:-N5dobxb4XAntXIFpc1C:b-jxuf7h) ([raw file](https://github.com/harness/harness-core/blob/d6be086cf6ee24ac92c773c77a49edf6457c554d/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L108)):*
> ```Java
>     if (isEmpty(delegateTokenName)) {
>       log.warn("Delegate token name is empty.");
>     } else if (validateDelegateJWTFromCache(accountId, tokenHash, shouldSetTokenNameInGlobalContext)) {
> ```

we should flip this if else condition, as in most cache we get cache hit.



_Code quote:_
```Java
 if (validateDelegateJWTFromCache(accountId, tokenHash, shouldSetTokenNameInGlobalContext))
```
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 145 at r1](https://reviewable.io/reviews/harness/harness-core/34741#-N5doJS7CiitAOZynMKE:-N5doJS87VZhFwPDhSmo:b-ewsfsq) ([raw file](https://github.com/harness/harness-core/blob/d6be086cf6ee24ac92c773c77a49edf6457c554d/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L145)):*
> ```Java
>         log.warn("Couldn't parse token", e);
>       }
>       delegateJWTCache.setDelegateJWTCache(tokenHash, delegateTokenName, new DelegateJWTCacheValue(false, 0L, null));
> ```

why not setting delegateTokenName instead ?



_Code quote:_
```Java
null
```
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 163 at r1](https://reviewable.io/reviews/harness/harness-core/34741#-N5do5Jq5y3eLNssPYUz:-N5do5Jq5y3eLNssPYV-:b-37nca9) ([raw file](https://github.com/harness/harness-core/blob/d6be086cf6ee24ac92c773c77a49edf6457c554d/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L163)):*
> ```Java
>       } else {
>         delegateJWTCache.setDelegateJWTCache(tokenHash, delegateTokenName,
>             new DelegateJWTCacheValue(true, expiryInMillis, getDelegateTokenNameFromGlobalContext().orElse(null)));
> ```

you might not be having global context here since your validation call to cache failed already above



_Code quote:_
```Java
 getDelegateTokenNameFromGlobalContext().orElse(null)
```

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34741)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 

___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/34741#-N5dobxb4XAntXIFpc1B:-N5drpUQ-GH_Ld-oSV0I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d6be086cf6ee24ac92c773c77a49edf6457c554d/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L108)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

we should flip this if else condition, as in most cache we get cache hit.
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 145 at r1](https://reviewable.io/reviews/harness/harness-core/34741#-N5doJS7CiitAOZynMKE:-N5drqOZ4BtClQb8UIKo:bnkcftn) ([raw file](https://github.com/harness/harness-core/blob/d6be086cf6ee24ac92c773c77a49edf6457c554d/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L145)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

why not setting delegateTokenName instead ?
</blockquote></details>

because setting tokenName in case of invalid JWT doesnt makes sense. See the first parameter of 

new DelegateJWTCacheValue(false, 0L, null));
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 163 at r1](https://reviewable.io/reviews/harness/harness-core/34741#-N5do5Jq5y3eLNssPYUz:-N5ds4iu3Jz0vkg6AfT3:bofozhe) ([raw file](https://github.com/harness/harness-core/blob/d6be086cf6ee24ac92c773c77a49edf6457c554d/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L163)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

you might not be having global context here since your validation call to cache failed already above
</blockquote></details>

yes validation call from cache will fail and then it will fallback to older method of validating and setting tokenName in global context.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34741)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 4238 at r2](https://reviewable.io/reviews/harness/harness-core/34741#-N5dx4-G5k44MTrdi6oe:-N5dx4-G5k44MTrdi6of:b-66r17d) ([raw file](https://github.com/harness/harness-core/blob/5d299aaa06a1ecc0b11c0a466ad5d00a0e304a91/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L4238)):*
> ```Java
>   }
>   private Optional<String> getDelegateTokenNameFromGlobalContext() {
>     DelegateTokenGlobalContextData delegateTokenGlobalContextData =
> ```

In future we can think of removing this global context and pass down tokenName to respective method who needs it.



_Code quote:_
```Java
  private Optional<String> getDelegateTokenNameFromGlobalContext() {
    DelegateTokenGlobalContextData delegateTokenGlobalContextData =
        GlobalContextManager.get(DelegateTokenGlobalContextData.TOKEN_NAME);
    if (delegateTokenGlobalContextData != null) {
      return Optional.ofNullable(delegateTokenGlobalContextData.getTokenName());
    }
    log.warn("Delegate token name not found in Global Context Data. Please verify manually.");
    return Optional.empty();
  }
```

**Review by Vbhatia20 — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34741)* status: :shipit: complete! ✓

**Comment by arpit3107** [comment]
trigger messagecheck

**Pull request merged**
