### PR TITLE
feat: [DEL-5941]: Change build scripts to include dms 

### PR DESCRIPTION
**Pull request by AnupamIO**
Changes includes:
1- Creating docker image for DMS.
2- Change in build script to push DMS image to GCR.
3- Adding health check point to DMS.

Testing:
Image is getting created and pushed to GCR, pipeline execution link: https://app.harness.io/ng/#/account/vpCkHKsDSxK9_KYfjCTMKA/ci/orgs/default/projects/FEATUREBUILDS/pipelines/OpenJDKUBIPortalFeaturecloneanupam/executions/NrssnWa_QOy4Ke6qEiL5ww/pipeline?storeType=INLINE

successful pr deployment link with passing readiness probe: https://app.harness.io/ng/#/account/vpCkHKsDSxK9_KYfjCTMKA/cd/orgs/default/projects/PREQA_NG_Pipelines/pipelines/PR_Harness_Env/executions/Rri9HHCrS1qULFRUc062Iw/pipeline?connectorRef=account.PRenvHarnessYamlGithub&repoName=ng-pr-manifests&branch=del-5941-dms&storeType=REMOTE

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44043)

### CODE REVIEW

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 5 of 7 files at r2, 3 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44043)* status: Waiting on team(s): del-team.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 5 of 7 files at r2, 3 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44043)* status: :shipit: complete! ✓

**Review by bharatgoelharness — DISMISSED** [review]
> Reviewed 2 of 8 files at r1, 5 of 7 files at r2, 3 of 4 files at r3, 2 of 2 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44043)* status: :shipit: complete! ✓

**Review by diptiman-adak — DISMISSED** [review]
> Reviewed 2 of 8 files at r1, 5 of 7 files at r2, 3 of 4 files at r3, 2 of 2 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44043)* status: :shipit: complete! ✓

**Review by USB-05 — APPROVED** [review]

**Review by USB-05 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 4 of 7 files at r2, 3 of 4 files at r3, 1 of 2 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44043#-:-NPVxu3E5kYsWuiSadA4:bnfp4nl)* status: :shipit: complete! ✓

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44043)* status: :shipit: complete! ✓

**Review by bharatgoelharness — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44043)* status: :shipit: complete! ✓

**Review by arpit3107 — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 4 of 7 files at r2, 3 of 4 files at r3, 1 of 2 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44043)* status: :shipit: complete! ✓

**Pull request merged**
