### PR TITLE
feat: [PIE-3835]: Graph changes to support matrix

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33658)

There are some changes required in graph because now we have one planNode to multiple nodeExecutions and graph relies on planNode. This change introduces few fields in the graph that would be required by the UI and some change in the api.

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 17 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33658)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`860-orchestration-steps/src/test/resources/schema/Pipelines/all.json` line 710 at r1](https://reviewable.io/reviews/harness/harness-core/33658#-N3OvYrD7fksPW7bBu9o:-N3OvYrD7fksPW7bBu9p:b-ghsu8w) ([raw file](https://github.com/harness/harness-core/blob/48caf09b8654c997879cf438b63ee2f18c870a1c/860-orchestration-steps/src/test/resources/schema/Pipelines/all.json#L710)):*
> ```JSON
>       },
>       "$schema": "http://json-schema.org/draft-07/schema#"
>     },
> ```

Just confirm if actual customer schema doesnt show this up



_Code quote:_
```JSON
    "ExcludeConfig": {
      "type": "object",
      "properties": {
        "exclude": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
```
___
*[`860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/33658#-N3Ovdej-p_7BYb-bXyX:-N3Ovdej-p_7BYb-bXyY:bal8lhf) ([raw file](https://github.com/harness/harness-core/blob/48caf09b8654c997879cf438b63ee2f18c870a1c/860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java#L39)):*
> ```Java
>     ExecutionStatus status = ExecutionStatus.getExecutionStatus(nodeExecution.getStatus());
>     if (Objects.equals(level.getStepType().getType(), StepSpecTypeConstants.BARRIER)) {
>       // Todo: Change here
> ```

What is the todo here?



_Code quote:_
```Java
// Todo: Change here
```
___
*[`860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/33658#-N3OvwNQ68fQCD8uIz7_:-N3OvwNQ68fQCD8uIz7a:bu2w4d3) ([raw file](https://github.com/harness/harness-core/blob/48caf09b8654c997879cf438b63ee2f18c870a1c/860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java#L49)):*
> ```Java
>       update.set(PipelineExecutionSummaryEntity.PlanExecutionSummaryKeys.layoutNodeMap + "." + nodeExecution.getNodeId()
>               + ".status",
>           status);
> ```

here we are using nodeId and not executionId? If Yes can you add comment here that only stages inside it are using executionId and rest are nodeId including strategy node



_Code quote:_
```Java
      update.set(PipelineExecutionSummaryEntity.PlanExecutionSummaryKeys.layoutNodeMap + "." + nodeExecution.getNodeId()
              + ".status",
          status);
```
___
*[`860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/beans/dto/GraphLayoutNodeDTO.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/33658#-N3OwlW3Ai8hbUKyxtNF:-N3OwlW3Ai8hbUKyxtNG:b-vsw0b2) ([raw file](https://github.com/harness/harness-core/blob/48caf09b8654c997879cf438b63ee2f18c870a1c/860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/beans/dto/GraphLayoutNodeDTO.java#L58)):*
> ```Java
>   FailureInfoDTO failureInfoDTO;
>   private Map<String, PmsStepDetails> stepDetails;
>   private Boolean hidden;
> ```

this hidden is for? and can we add description comments here?



_Code quote:_
```Java
private Boolean hidden
```
___
*[`860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java` line 181 at r1](https://reviewable.io/reviews/harness/harness-core/33658#-N3OwRxV3mWqxXslKost:-N3OwRxV3mWqxXslKosu:b82oi2m) ([raw file](https://github.com/harness/harness-core/blob/48caf09b8654c997879cf438b63ee2f18c870a1c/860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L181)):*
> ```Java
>           if (pmsFeatureFlagService.isEnabled(
>                   AmbianceUtils.getAccountId(nodeExecution.getAmbiance()), FeatureName.PIPELINE_MATRIX)) {
>             pmsExecutionSummaryService.addStageNodeInGraphIfUnderStrategy(
> ```

should we add this method in ExecutionSummaryUpdateUtils.addStageUpdateCriteria as, regenerateGraph also will be calling that only and it may happen that we are regenerating without adding stages inside strategy node?



_Code quote:_
```Java
pmsExecutionSummaryService.addStageNodeInGraphIfUnderStrategy
```
___
*[`860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java` line 233 at r1](https://reviewable.io/reviews/harness/harness-core/33658#-N3Ox3Z5DT2Hk9PLlhGB:-N3Ox3Z5DT2Hk9PLlhGC:b18qi1f) ([raw file](https://github.com/harness/harness-core/blob/c61afd5fe6b9be815997a7a2b1e50e45ceefc8ed/860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L233)):*
> ```Java
>     }
>     String startingNodeId =
>         obtainStartingIdFromSetupNodeId(orchestrationGraph.getAdjacencyList().getGraphVertexMap(), startingSetupNodeId);
> ```

shouldnt we delete this method if not used anymore?



_Code quote:_
```Java
obtainStartingIdFromSetupNodeId
```

**Comment by sahilhindwani-harness** [comment]
*[`860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/33658#-N3Ovdej-p_7BYb-bXyX:-N3Tjfdx0Ttc-rSiZU-i:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/48caf09b8654c997879cf438b63ee2f18c870a1c/860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java#L39)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

What is the todo here?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/33658#-N3OvwNQ68fQCD8uIz7_:-N3TjgPtE7nwhORHvVh6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/48caf09b8654c997879cf438b63ee2f18c870a1c/860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java#L49)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

here we are using nodeId and not executionId? If Yes can you add comment here that only stages inside it are using executionId and rest are nodeId including strategy node
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/beans/dto/GraphLayoutNodeDTO.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/33658#-N3OwlW3Ai8hbUKyxtNF:-N3TjhEEBp1TaJkHh8be:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/48caf09b8654c997879cf438b63ee2f18c870a1c/860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/beans/dto/GraphLayoutNodeDTO.java#L58)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this hidden is for? and can we add description comments here?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java` line 181 at r1](https://reviewable.io/reviews/harness/harness-core/33658#-N3OwRxV3mWqxXslKost:-N3Tjhx32gGb0q4OnIO4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/48caf09b8654c997879cf438b63ee2f18c870a1c/860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L181)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should we add this method in ExecutionSummaryUpdateUtils.addStageUpdateCriteria as, regenerateGraph also will be calling that only and it may happen that we are regenerating without adding stages inside strategy node?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java` line 233 at r1](https://reviewable.io/reviews/harness/harness-core/33658#-N3Ox3Z5DT2Hk9PLlhGB:-N3Tji_A0O5b0XKpV9Z6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c61afd5fe6b9be815997a7a2b1e50e45ceefc8ed/860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L233)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

shouldnt we delete this method if not used anymore?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`860-orchestration-steps/src/test/resources/schema/Pipelines/all.json` line 710 at r1](https://reviewable.io/reviews/harness/harness-core/33658#-N3OvYrD7fksPW7bBu9o:-N3Xpy5u0N20yppA2y2P:b-7o2qaw) ([raw file](https://github.com/harness/harness-core/blob/48caf09b8654c997879cf438b63ee2f18c870a1c/860-orchestration-steps/src/test/resources/schema/Pipelines/all.json#L710)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Just confirm if actual customer schema doesnt show this up
</blockquote></details>

Validated this. It is not coming in customer schema

**Review by archit-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33658)* status: 22 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 15 of 21 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33658)* status: :shipit: complete! ✓

**Pull request merged**
