### PR TITLE
feat: [PIE-7813]: get batch file implementation in scm facilitator service

### PR DESCRIPTION
**Pull request by mohitg0795**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42908)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42908)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmBatchGetFileRequestDTO.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/42908#-NMRzWOE36IiuYQ75KI9:-NMRzWOE36IiuYQ75KIA:b-tsoq7m) ([raw file](https://github.com/harness/harness-core/blob/5d19b8eb09bbf0f14aae7d2412189a91edb3cf77/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmBatchGetFileRequestDTO.java#L21)):*
> ```Java
> @OwnedBy(HarnessTeam.PL)
> @Getter
> @FieldDefaults(level = AccessLevel.PRIVATE)
> ```

@Value wont be sufficient? and same for others where we used it



_Code quote:_
```Java
@FieldDefaults(level = AccessLevel.PRIVATE)
```
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmBatchGetFileResponseDTO.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/42908#-NMRz_Jt4nnj7V-J9O0R:-NMRz_Jt4nnj7V-J9O0S:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/5d19b8eb09bbf0f14aae7d2412189a91edb3cf77/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmBatchGetFileResponseDTO.java#L21)):*
> ```Java
> @OwnedBy(HarnessTeam.PL)
> @Getter
> @FieldDefaults(level = AccessLevel.PRIVATE)
> ```

same as above
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmGetFileResponseDTO.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/42908#-NMRznT45n71qbUSpZP9:-NMRznT45n71qbUSpZPA:b-6zghmo) ([raw file](https://github.com/harness/harness-core/blob/5d19b8eb09bbf0f14aae7d2412189a91edb3cf77/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmGetFileResponseDTO.java#L22)):*
> ```Java
> @Getter
> @FieldDefaults(level = AccessLevel.PROTECTED)
> @SuperBuilder
> ```

I think we agreed to remove this deprecated annotation for new classes 
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 920 at r2](https://reviewable.io/reviews/harness/harness-core/42908#-NMS-QD34hqqwKhR9DVR:-NMS-QD34hqqwKhR9DVS:baexjl0) ([raw file](https://github.com/harness/harness-core/blob/5d19b8eb09bbf0f14aae7d2412189a91edb3cf77/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L920)):*
> ```Java
>   @Override
>   public GitFileBatchResponse getFileBatch(GitFileBatchRequest gitFileBatchRequest) {
>     ScmBatchGetFileTaskParams scmBatchGetFileTaskParams = getScmBatchGetFileTaskParams(gitFileBatchRequest);
> ```

Can we add unit tests for new added methods 
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1053 at r2](https://reviewable.io/reviews/harness/harness-core/42908#-NMS-6Cw-yahEiPmKuyK:-NMS-6Cw-yahEiPmKuyL:b-tgw3v4) ([raw file](https://github.com/harness/harness-core/blob/5d19b8eb09bbf0f14aae7d2412189a91edb3cf77/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1053)):*
> ```Java
>   }
> 
>   private ScmBatchGetFileTaskParams getScmBatchGetFileTaskParams(GitFileBatchRequest gitFileBatchRequest) {
> ```

Can we add comments on each method about what is achieving
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 379 at r2](https://reviewable.io/reviews/harness/harness-core/42908#-NMS-EWNCupciYSobNg7:-NMS-EWNCupciYSobNg8:b-w9mvs1) ([raw file](https://github.com/harness/harness-core/blob/5d19b8eb09bbf0f14aae7d2412189a91edb3cf77/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L379)):*
> ```Java
> 
>   @Override
>   public ScmGetBatchFilesResponseDTO getBatchFilesByBranch(
> ```

Can we add comments on method and inside method to kinda have documentation as part of code

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmBatchGetFileRequestDTO.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/42908#-NMRzWOE36IiuYQ75KI9:-NMSROq-EO7SvjLmxFuP:b2ha7ek) ([raw file](https://github.com/harness/harness-core/blob/5d19b8eb09bbf0f14aae7d2412189a91edb3cf77/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmBatchGetFileRequestDTO.java#L21)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@Value wont be sufficient? and same for others where we used it
</blockquote></details>

@value does more than whats required, but should be good for our use-case. Will fix it.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmGetFileResponseDTO.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/42908#-NMRznT45n71qbUSpZP9:-NMSR_nK4aZoO3MoGgme:b-ritvgp) ([raw file](https://github.com/harness/harness-core/blob/5d19b8eb09bbf0f14aae7d2412189a91edb3cf77/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmGetFileResponseDTO.java#L22)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I think we agreed to remove this deprecated annotation for new classes 
</blockquote></details>

Ya, actually its already written code and I'm just carving out PRs now. I will change it.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmGetFileResponseDTO.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/42908#-NMRznT45n71qbUSpZP9:-NMwq1DYA75mSL733TkU:b9vm7po) ([raw file](https://github.com/harness/harness-core/blob/bbb5e8aab1f18448e38ef2fab165e9c1aa8afbc6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmGetFileResponseDTO.java#L22)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Ya, actually its already written code and I'm just carving out PRs now. I will change it.
</blockquote></details>

Here, superBuilder is required as its used in one of the classes that extends it. So, all classes should have superbuilder in this case.

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42908)* status: 19 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmBatchGetFileResponseDTO.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/42908#-NMRz_Jt4nnj7V-J9O0R:-NMwpwUq8oPjcEL_ggGU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bbb5e8aab1f18448e38ef2fab165e9c1aa8afbc6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmBatchGetFileResponseDTO.java#L21)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 920 at r2](https://reviewable.io/reviews/harness/harness-core/42908#-NMS-QD34hqqwKhR9DVR:-NMwpxon4KLqiEJ0W2Oa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bbb5e8aab1f18448e38ef2fab165e9c1aa8afbc6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L920)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we add unit tests for new added methods 
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1053 at r2](https://reviewable.io/reviews/harness/harness-core/42908#-NMS-6Cw-yahEiPmKuyK:-NMwpyq89xnbaTw61l-J:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bbb5e8aab1f18448e38ef2fab165e9c1aa8afbc6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1053)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we add comments on each method about what is achieving
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 379 at r2](https://reviewable.io/reviews/harness/harness-core/42908#-NMS-EWNCupciYSobNg7:-NMwpt5N8F3duaGy4NOh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bbb5e8aab1f18448e38ef2fab165e9c1aa8afbc6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L379)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we add comments on method and inside method to kinda have documentation as part of code
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 12 of 18 files at r1, 1 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42908)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Review by sourabh-awashti — APPROVED** [review]
> Reviewed 11 of 18 files at r1, 1 of 2 files at r3, 2 of 4 files at r4, 6 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42908)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by abhinavsingh-ccm** [comment]
approving it to just enable this PR to get merged as per request by @mohitg0795

**Review by abhinavsingh-ccm — APPROVED** [review]
+1

**Review by abhinavsingh-ccm — APPROVED** [review]
> Reviewed 11 of 18 files at r1, 1 of 2 files at r3, 2 of 4 files at r4, 6 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42908)* status: :shipit: complete! ✓

**Pull request merged**
