### PR TITLE
[feat]: [CDS-78986]: Supporting the creating and updating of templates v1

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes
Supporting the creating and updating of templates v1.

Changes: 

- Taking some extra parameters in the template API requestBody to support the create/update operations on v1 templates.
- Made required changes to create v1 templateEntity from the given templateYaml and metadata.

Testing: 

- Tested creation of V0 and V1 template entities.
- Tested updating the V0 and V1 template entities.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53230)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> Reviewed 12 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53230)* status: 14 file(s) to review. 0 of 2 approvals obtained. 

___
*[`template-service/contracts/openapi/v1/openapi.yaml` line 1209 at r2](https://reviewable.io/reviews/harness/harness-core/53230#-Nf9oMaBEAy58aY7lLsz:-Nf9oMaBEAy58aY7lLt-:b-wmbai9) ([raw file](https://github.com/harness/harness-core/blob/68ebe3afe0a4cf32458c8e729f4380d048573045/template-service/contracts/openapi/v1/openapi.yaml#L1209)):*
> ```YAML
>           maxLength: 128
>           description: Template name
>         label:
> ```

did we check to call them label? cc: @mohitg0795 wouldn't we get confused with labels at execution ?
___
*[`template-service/service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 236 at r2](https://reviewable.io/reviews/harness/harness-core/53230#-Nf9p3zRARjQN1WDAH8p:-Nf9p3zRARjQN1WDAH8q:b-r1zmf7) ([raw file](https://github.com/harness/harness-core/blob/68ebe3afe0a4cf32458c8e729f4380d048573045/template-service/service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L236)):*
> ```Java
>     try {
>       templateEntityType = YamlUtils.NG_DEFAULT_OBJECT_MAPPER.treeToValue(
>           templateNode.get(YAMLFieldNameConstants.TYPE), TemplateEntityType.class);
> ```

Why do we need to use objectMapper here?
___
*[`template-service/service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 249 at r2](https://reviewable.io/reviews/harness/harness-core/53230#-Nf9p0ka4H6K0j9Krh6J:-Nf9p0ka4H6K0j9Krh6K:bxi6nwc) ([raw file](https://github.com/harness/harness-core/blob/68ebe3afe0a4cf32458c8e729f4380d048573045/template-service/service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L249)):*
> ```Java
>         .name(requestInfoDTO.getName())
>         .harnessVersion(HarnessYamlVersion.V1)
>         //            .tags(TagMapper.convertToList(templateConfig.getTemplateInfoConfig().getTags()))
> ```

why not tags?
___
*[`template-service/service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 250 at r2](https://reviewable.io/reviews/harness/harness-core/53230#-Nf9p-q129M1Mt1cm7Gi:-Nf9p-q129M1Mt1cm7Gj:b-alqkd5) ([raw file](https://github.com/harness/harness-core/blob/68ebe3afe0a4cf32458c8e729f4380d048573045/template-service/service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L250)):*
> ```Java
>         .harnessVersion(HarnessYamlVersion.V1)
>         //            .tags(TagMapper.convertToList(templateConfig.getTemplateInfoConfig().getTags()))
>         //            .icon(templateConfig.getTemplateInfoConfig().getIcon())
> ```

what is icon?
___
*[`template-service/service/src/main/java/io/harness/template/resources/TemplateRequestInfoDTO.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/53230#-Nf9pf5p6NpcYZ0of0kn:-Nf9pf5p6NpcYZ0of0ko:b-5ubdwm) ([raw file](https://github.com/harness/harness-core/blob/68ebe3afe0a4cf32458c8e729f4380d048573045/template-service/service/src/main/java/io/harness/template/resources/TemplateRequestInfoDTO.java#L22)):*
> ```Java
>   @Getter String name;
>   @Getter String yaml;
>   @Getter String label;
> ```

it should be versionLabel, just label is confusing

**Review by shalini-agr — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53230)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java` line 141 at r2](https://reviewable.io/reviews/harness/harness-core/53230#-Nf9q9a8AVpiJvyrSj5J:-Nf9q9a8AVpiJvyrSj5K:bdv9sa3) ([raw file](https://github.com/harness/harness-core/blob/68ebe3afe0a4cf32458c8e729f4380d048573045/template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java#L141)):*
> ```Java
> 
>   public Response createTemplate(@AccountIdentifier String account, @OrgIdentifier String org,
>       @ProjectIdentifier String project, GitCreateDetails gitEntityCreateInfo, TemplateRequestInfoDTO requestInfoDTO,
> ```

isn't this change backward incompatible?

**Comment by brijeshdhakar** [comment]
*[`template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java` line 141 at r2](https://reviewable.io/reviews/harness/harness-core/53230#-Nf9q9a8AVpiJvyrSj5J:-Nf9vSq_7K5deWYeSmAR:bd9apqq) ([raw file](https://github.com/harness/harness-core/blob/68ebe3afe0a4cf32458c8e729f4380d048573045/template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java#L141)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

isn't this change backward incompatible?
</blockquote></details>

Its not the API contract but inner method invoked from the resource. 
We are creating this dto from the request, so effectively API contract remain same.( Except some some new `nullable` fields added in request body so that would be backward compatible)

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53230)* status: 14 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/contracts/openapi/v1/openapi.yaml` line 1209 at r2](https://reviewable.io/reviews/harness/harness-core/53230#-Nf9oMaBEAy58aY7lLsz:-NfAE5lD0RQAg2nneQDR:b-8vhjaz) ([raw file](https://github.com/harness/harness-core/blob/68ebe3afe0a4cf32458c8e729f4380d048573045/template-service/contracts/openapi/v1/openapi.yaml#L1209)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

did we check to call them label? cc: @mohitg0795 wouldn't we get confused with labels at execution ?
</blockquote></details>

As discussed offline, we will use the label only.
___
*[`template-service/service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 249 at r2](https://reviewable.io/reviews/harness/harness-core/53230#-Nf9p0ka4H6K0j9Krh6J:-NfAAv1F-E7xs9y3WrKE:b-6nw7ez) ([raw file](https://github.com/harness/harness-core/blob/68ebe3afe0a4cf32458c8e729f4380d048573045/template-service/service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L249)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why not tags?
</blockquote></details>

Added the tags and in the API requestBody as well.
___
*[`template-service/service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 250 at r2](https://reviewable.io/reviews/harness/harness-core/53230#-Nf9p-q129M1Mt1cm7Gi:-NfABIhHDKdeYjbp7haz:b-hj125n) ([raw file](https://github.com/harness/harness-core/blob/68ebe3afe0a4cf32458c8e729f4380d048573045/template-service/service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L250)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what is icon?
</blockquote></details>

This is basically adding some icons for the deployment templates denoting that which deployment types it supports.
Since I couldn't find in the YAML. So keeping it as commented as we can revisit it.
___
*[`template-service/service/src/main/java/io/harness/template/resources/TemplateRequestInfoDTO.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/53230#-Nf9pf5p6NpcYZ0of0kn:-NfACtP05dHomfDZK5dN:b-8vhjaz) ([raw file](https://github.com/harness/harness-core/blob/68ebe3afe0a4cf32458c8e729f4380d048573045/template-service/service/src/main/java/io/harness/template/resources/TemplateRequestInfoDTO.java#L22)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

it should be versionLabel, just label is confusing
</blockquote></details>

As discussed offline, we will use the label only.

**Comment by brijeshdhakar** [comment]
*[`template-service/service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 236 at r2](https://reviewable.io/reviews/harness/harness-core/53230#-Nf9p3zRARjQN1WDAH8p:-NfAF9NB5SK6U4bw70Yl:be97ckh) ([raw file](https://github.com/harness/harness-core/blob/68ebe3afe0a4cf32458c8e729f4380d048573045/template-service/service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L236)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why do we need to use objectMapper here?
</blockquote></details>

To map the string value into the Enum. Enum has the JsonProperty annotation on a field so deserialising from the objectMapper works. But Enum.getValue will not work because the string value matches a field value and not the Enum name.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53230)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53230)* status: 14 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger ut9

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by shalini-agr — APPROVED** [review]
> Reviewed 6 of 14 files at r1, 1 of 4 files at r3, 4 of 8 files at r4, 2 of 2 files at r5, 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53230)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 8 files at r4, 2 of 2 files at r5, 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53230)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger ut0 ut2 ut3 ut4

**Review by mankrit-singh — APPROVED** [review]

**Comment by brijeshdhakar** [comment]
trigger ut1

**Comment by brijeshdhakar** [comment]
trigger ut0 ut1 ut2 ut3 ut4

**Comment by brijeshdhakar** [comment]
trigger ut7

**Comment by brijeshdhakar** [comment]
trigger ut0 ut1 ut2 ut3 ut4 ut7

**Comment by brijeshdhakar** [comment]
trigger ut0 ut1 ut3 ut4

**Pull request merged**
