### PR TITLE
feat: [CDS-34114]: Support migarting many entities

### PR DESCRIPTION
**Pull request by puthrayaharness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30913)

### CODE REVIEW

**Review by vaibhav-si — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30913)* status: 4 file(s) to review. 0 of 1 approvals obtained. 

___
*[100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java, line 108 at r1](https://reviewable.io/reviews/harness/harness-core/30913#-Mwyt_KZ-xClLD7RcuiP:-Mwyt_KaCEiGyZKWSaPy:bp0dmfd) ([raw file](https://github.com/harness/harness-core/blob/53ad2ea77d3c4fd279041ed03c9f25ceba38fb13/100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java#L108)):*
> ```Java
>     Map<CgEntityId, Set<CgEntityId>> graph = new HashMap<>();
>     NgMigrationService ngMigrationService = migrationFactory.getMethod(NGMigrationEntityType.DUMMY_HEAD);
>     DiscoveryNode head = ngMigrationService.discover(accountId, null, null);
> ```

Instead of creating dummy entity and dummy migration service, 

we can simply initialize a discovery node as head.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30913)* status: 4 file(s) to review. 0 of 1 approvals obtained. 

___
*[100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java, line 125 at r1](https://reviewable.io/reviews/harness/harness-core/30913#-Mwyu13BDKaQGmNbZNAy:-Mwyu13BDKaQGmNbZNAz:b6lqeci) ([raw file](https://github.com/harness/harness-core/blob/53ad2ea77d3c4fd279041ed03c9f25ceba38fb13/100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java#L125)):*
> ```Java
>         graph.get(head.getEntityNode().getEntityId()).add(node.getEntityNode().getEntityId());
>         // Individually discover the child of every input
>         travel(accountId, appId, entities, graph, null, node);
> ```

nit, `travel` could be renamed with `discoverChildEntitiesRecursively` or similar for readability

**Comment by puthrayaharness** [comment]
___
*[100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java, line 108 at r1](https://reviewable.io/reviews/harness/harness-core/30913#-Mwyt_KZ-xClLD7RcuiP:-MwywUaKC1v-Nx9Gq_v-:bfx2dx9) ([raw file](https://github.com/harness/harness-core/blob/53ad2ea77d3c4fd279041ed03c9f25ceba38fb13/100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java#L108)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Instead of creating dummy entity and dummy migration service, 

we can simply initialize a discovery node as head.
</blockquote></details>

I did not do that because we use the Discovery Result to create inputs & the YAML. Creating the Dummy head makes it simpler.

**Comment by puthrayaharness** [comment]
___
*[100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java, line 125 at r1](https://reviewable.io/reviews/harness/harness-core/30913#-Mwyu13BDKaQGmNbZNAy:-MwyxFac79COuOnBww8l:bs4174r) ([raw file](https://github.com/harness/harness-core/blob/53ad2ea77d3c4fd279041ed03c9f25ceba38fb13/100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java#L125)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, `travel` could be renamed with `discoverChildEntitiesRecursively` or similar for readability
</blockquote></details>

Sure will do.

**Comment by puthrayaharness** [comment]
___
*[100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java, line 108 at r1](https://reviewable.io/reviews/harness/harness-core/30913#-Mwyt_KZ-xClLD7RcuiP:-MwyxLzn6f5PjQrC6Wp1:bjs0ntl) ([raw file](https://github.com/harness/harness-core/blob/53ad2ea77d3c4fd279041ed03c9f25ceba38fb13/100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java#L108)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

I did not do that because we use the Discovery Result to create inputs & the YAML. Creating the Dummy head makes it simpler.
</blockquote></details>

Otherwise I will have to handle nulls.

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 4 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30913)* status: Some of the checks are too old.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30913)* status: :shipit: complete! ✓

**Pull request merged**
