### PR TITLE
feat: [CDS-74848]: Global Template MarketPlace

### PR DESCRIPTION
**Pull request by shivamnegi94**
## Describe your changes
Global Template Market Place is a new feature which introduce templates to be shared across the accounts. Initially Harness only be the contributor to the Market Place.
Design docs: https://harness.atlassian.net/wiki/spaces/CDNG/pages/21420409865/Template+Library+Marketplace+-+Github+Repo
**Implementation:** 

- We will be using the Github trigger to create a template.
- User will create a template and push to the harness repo `harness-template-marketplace`
- Once trigger is activated, we will be making call to template service with git payload
- Template service will parse the files (added, modified or delete) from git commit payload.
- Then template service will get the content of file from git and save to the collection `globalTemplate`.
- UI will be calling list APIs to list all the global template.
- User can import these templates and use it.
Docs for implementation - https://harness.atlassian.net/wiki/spaces/CDNG/pages/21453471893/Global+Template+Library+Marketplace+-+Tech+Spec?focusedCommentId=21453308164

Testing :
TC1: globalTemplate API to read the git commit payload and create th
Screenshot 2023-08-14 at 10 26 54 AM
e global template.

TC2: globalTemplate API to list all the templates.

Screenshot 2023-08-14 at 10 26 31 AM

TC3: API to list the template by identifier.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51526)

### CODE REVIEW

**Comment by shivamnegi94** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java` line 335 at r2](https://reviewable.io/reviews/harness/harness-core/51526#-Nbn0D2b7Dau4rqhz2Ud:-Nbn0D2b7Dau4rqhz2Ue:b-eggae0) ([raw file](https://github.com/harness/harness-core/blob/157f70c92b6ed763f7c5e3c612f156860d3502b7/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java#L335)):*
> ```Java
> 
>   @VisibleForTesting
>   void validateReamMeFilePathHasCorrectExtension(String filePath) {
> ```

nit: Readme

**Comment by sahilhindwani-harness** [comment]
*[`template-service/contracts/src/main/java/io/harness/template/resources/NGGlobalTemplateResource.java` line 103 at r2](https://reviewable.io/reviews/harness/harness-core/51526#-Nbxk8eA2iVFicTpQrWO:-Nbxk8eA2iVFicTpQrWP:bt6cvbp) ([raw file](https://github.com/harness/harness-core/blob/157f70c92b6ed763f7c5e3c612f156860d3502b7/template-service/contracts/src/main/java/io/harness/template/resources/NGGlobalTemplateResource.java#L103)):*
> ```Java
>         @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "default",
>             description = "Fetches Template YAML from git and create global template to Harness DB")
>       })
> ```

Does this api needs to be hidden in openapi?

**Comment by sahilhindwani-harness** [comment]
*[`template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/51526#-NbxkP7Z3srytsH3tqro:-NbxkP7Z3srytsH3tqrp:b-m92kom) ([raw file](https://github.com/harness/harness-core/blob/157f70c92b6ed763f7c5e3c612f156860d3502b7/template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L148)):*
> ```Java
>       if (shouldLogAudits(templateToSave.getAccountId(), templateToSave.getOrgIdentifier(),
>               templateToSave.getProjectIdentifier())) {
>         outboxService.save(
> ```

Do we need audits for global templates? Will we not have commits history already in git for these.

**Comment by sahilhindwani-harness** [comment]
*[`template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 195 at r2](https://reviewable.io/reviews/harness/harness-core/51526#-Nbxkn8p2WjvXvj5NVDq:-Nbxkn8p2WjvXvj5NVDr:bsiuhe3) ([raw file](https://github.com/harness/harness-core/blob/157f70c92b6ed763f7c5e3c612f156860d3502b7/template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L195)):*
> ```Java
> 
>   @Override
>   public Page<GlobalTemplateEntity> findALLGlobalTemplateAndDeletedNot(
> ```

We should limit page size to 100 for now. As we grow user can query for 1000 which could put load on our system.

**Comment by sahilhindwani-harness** [comment]
*[`template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 283 at r2](https://reviewable.io/reviews/harness/harness-core/51526#-Nbxl1ou9SrcFqLr8RYN:-Nbxl1ou9SrcFqLr8RYO:b-wdij7b) ([raw file](https://github.com/harness/harness-core/blob/157f70c92b6ed763f7c5e3c612f156860d3502b7/template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L283)):*
> ```Java
>   private Criteria buildCriteriaForGlobalTemplateFindByIdentifierAndVersionLabelAndDeletedNot(
>       String templateIdentifier, String versionLabel, boolean notDeleted) {
>     return Criteria.where(GlobalTemplateEntityKeys.deleted)
> ```

Are we supporting soft delete of global templates? If not, then should we just remove this field altogether as it has effect on our query and db?

**Comment by sahilhindwani-harness** [comment]
*[`template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 316 at r2](https://reviewable.io/reviews/harness/harness-core/51526#-NbxlFm4E6AVu5pxwQol:-NbxlFm4E6AVu5pxwQom:b-8sgxir) ([raw file](https://github.com/harness/harness-core/blob/157f70c92b6ed763f7c5e3c612f156860d3502b7/template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L316)):*
> ```Java
>     return Criteria.where(GlobalTemplateEntityKeys.deleted)
>         .is(!notDeleted)
>         .and(GlobalTemplateEntityKeys.isStableTemplate)
> ```

Could you please suggest the index which this query and other query will be using for fetching the templates?

**Comment by sahilhindwani-harness** [comment]
*[`template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 370 at r2](https://reviewable.io/reviews/harness/harness-core/51526#-NbxlVpy9fXVv74yMS0X:-NbxlVpy9fXVv74yMS0Y:b-txzwu5) ([raw file](https://github.com/harness/harness-core/blob/157f70c92b6ed763f7c5e3c612f156860d3502b7/template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L370)):*
> ```Java
>       return Optional.empty();
>     }
>     if (getMetadataOnly) {
> ```

nit: This check is redundant, we can directly return

**Comment by sahilhindwani-harness** [comment]
*[`template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 556 at r2](https://reviewable.io/reviews/harness/harness-core/51526#-NbxlidY1O90ZJumBTbQ:-NbxlidY1O90ZJumBTbR:b-ew9ul0) ([raw file](https://github.com/harness/harness-core/blob/157f70c92b6ed763f7c5e3c612f156860d3502b7/template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L556)):*
> ```Java
> 
>   @Override
>   public Page<GlobalTemplateEntity> findAll(String accountIdentifier, Criteria criteria, Pageable pageable) {
> ```

can we combine this with getAllGlobalTemplateEntity?

**Pull request closed without merging**
