### PR TITLE
fix:[PIE-7440]: Code guard to log more details about NPE

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- As we cannot identify the root cause we adopt the code guard to detect the NPE and add more details to the log with current planExecutionMap and resource restraint mapped instances.
- The missing plan execution is taken out from the final result list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42235)

### CODE REVIEW

**Comment by Fernando-Dourado** [comment]
trigger messagecheck

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42235)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java` line 172 at r2](https://reviewable.io/reviews/harness/harness-core/42235#-NKySRpd1g8GhoJO-p2h:-NKySRpd1g8GhoJO-p2i:b-4yzlaz) ([raw file](https://github.com/harness/harness-core/blob/1f0a487bebd9b188db5579b9dc525901056f62cb/pipeline-service/service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java#L172)):*
> ```Java
>   }
> 
>   private AutoLogContext createAutoLogContext(String accountId, String resourceUnit) {
> ```

Instead of doing it this way, will suggest you to create a proper autologcontext class and use it, eg: "K8LogContext" or there are many for reference.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42235)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java` line 172 at r2](https://reviewable.io/reviews/harness/harness-core/42235#-NKySRpd1g8GhoJO-p2h:-NL-43XlB6V9Q-DbXumD:b-an53rj) ([raw file](https://github.com/harness/harness-core/blob/1f0a487bebd9b188db5579b9dc525901056f62cb/pipeline-service/service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java#L172)):*
> K8LogContext
+1

**Review by naidu-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42235)* status: 1. unresolved discussions.

**Pull request merged**
