### PR TITLE
[feat]: [CDS-71916]: Implementing PmsWebhookChannnel to build WebhookChannel object for NotificationClient

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49098)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49098)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/notification/channelDetails/PmsWebhookChannel.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/49098#-NXjCxCYALhWkeIU0__l:-NXjCxCYALhWkeIU0__m:b-iximoe) ([raw file](https://github.com/harness/harness-core/blob/31d97a7d0cc7f2b4d24e8892d5b504dbbf51443d/953-yaml-commons/src/main/java/io/harness/notification/channelDetails/PmsWebhookChannel.java#L51)):*
> ```Java
>         .templateId(templateId)
>         .webhookUrls(
>             Lists.newArrayList(webhookUrl.getValue() != null ? webhookUrl.getValue() : webhookUrl.getExpressionValue()))
> ```

can it be expression at this moment, if yes how will PL resolve it?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 360 at r2](https://reviewable.io/reviews/harness/harness-core/49098#-NXjDE3tBFFNB7G3ZeLt:-NXjDE3u6-W235wivNXo:bvqpycm) ([raw file](https://github.com/harness/harness-core/blob/31d97a7d0cc7f2b4d24e8892d5b504dbbf51443d/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L360)):*
> ```Java
>       webhookNotificationEvent.stageIdentifier(stageIdentifier);
>     }
>     templateData.put("WEBHOOK_EVENT_DATA", JsonUtils.asJson(webhookNotificationEvent.build()));
> ```

Use JsonPipelineUtils, check this utils should also not include unset values

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49098)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/notification/channelDetails/PmsWebhookChannel.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/49098#-NXjCxCYALhWkeIU0__l:-NXjDsdD28j06SRPgJGA:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/31d97a7d0cc7f2b4d24e8892d5b504dbbf51443d/953-yaml-commons/src/main/java/io/harness/notification/channelDetails/PmsWebhookChannel.java#L51)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can it be expression at this moment, if yes how will PL resolve it?
</blockquote></details>

done
___
*[`953-yaml-commons/src/main/java/io/harness/notification/channelDetails/PmsWebhookChannel.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/49098#-NXjDv-57CjPxDaQ46WF:-NXjDv-57CjPxDaQ46WG:bp22194) ([raw file](https://github.com/harness/harness-core/blob/31d97a7d0cc7f2b4d24e8892d5b504dbbf51443d/953-yaml-commons/src/main/java/io/harness/notification/channelDetails/PmsWebhookChannel.java#L51)):*
> ```Java
>         .templateId(templateId)
>         .webhookUrls(
>             Lists.newArrayList(webhookUrl.getValue() != null ? webhookUrl.getValue() : webhookUrl.getExpressionValue()))
> ```

add comment that only secret can be expression for documentation

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49098)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/notification/channelDetails/PmsWebhookChannel.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/49098#-NXjDv-57CjPxDaQ46WF:-NXjGv5K7Y6X2JZgTZc_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31d97a7d0cc7f2b4d24e8892d5b504dbbf51443d/953-yaml-commons/src/main/java/io/harness/notification/channelDetails/PmsWebhookChannel.java#L51)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comment that only secret can be expression for documentation
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 360 at r2](https://reviewable.io/reviews/harness/harness-core/49098#-NXjDE3tBFFNB7G3ZeLt:-NXjGwM_6LlX8KJRsTRL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31d97a7d0cc7f2b4d24e8892d5b504dbbf51443d/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L360)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Use JsonPipelineUtils, check this utils should also not include unset values
</blockquote></details>

Done.

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49098)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 269 at r3](https://reviewable.io/reviews/harness/harness-core/49098#-NXjKPM44Ddz9emcpS8R:-NXjKPM44Ddz9emcpS8S:bf4m9gz) ([raw file](https://github.com/harness/harness-core/blob/a179fe9fc2dd328c1823dd1cec27e0811e3677b7/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L269)):*
> ```Java
>   Map<String, String> constructTemplateData(Ambiance ambiance, PipelineEventType pipelineEventType,
>       NodeExecution nodeExecution, Long updatedAt, String orgIdentifier, String projectIdentifier)
>       throws JsonProcessingException {
> ```

instead use getJsonString



_Code quote:_
```Java
throws JsonProcessingException
```

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49098)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 269 at r3](https://reviewable.io/reviews/harness/harness-core/49098#-NXjKPM44Ddz9emcpS8R:-NXjKaTCCbwmLmDRKtRB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a179fe9fc2dd328c1823dd1cec27e0811e3677b7/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L269)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

instead use getJsonString
</blockquote></details>

Done.

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49098)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 3 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49098)* status: 1 file(s) to review. 0 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/test/resources/schema/Pipelines/all.json` line 4771 at r5](https://reviewable.io/reviews/harness/harness-core/49098#-NXkceuODmwG7vRqNe1B:-NXkevsC78b-RjzoJTD7:b-nebcq) ([raw file](https://github.com/harness/harness-core/blob/c2d0dfd44cbcf179c15332182033101a1de741ec/pipeline-service/modules/orchestration-steps/src/test/resources/schema/Pipelines/all.json#L4771)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Why have we removed this? Can you check if in slack we are getting user groups or not?
</blockquote></details>

Discussed offline, for webhooks user group is not required.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49098)* status: 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]

**Comment by brijeshdhakar** [comment]
trigger review

**Pull request merged**
