### PR TITLE
feat: [PL-27160]: added migration script for disable harness sm setting

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
Migration for the account setting to "Disable Harness Secret Manager" to the new NG settings framework
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38507)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Vulnerability 1 Vulnerabilities 
 
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38507)

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38507)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingIdentifier.java` line 11 at r1](https://reviewable.io/reviews/harness/harness-core/38507#-NE2kJxF4b1H0JCKvQA8:-NE2kJxF4b1H0JCKvQA9:bsip6xu) ([raw file](https://github.com/harness/harness-core/blob/15c1f834b9477cebb917ded3c0cd54dfcf0b101a/120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingIdentifier.java#L11)):*
> ```Java
> 
> public class SettingIdentifier {
>   public static String disable_harness_built_in_SM = "disable_harness_built_in_SM";
> ```

as practice, its better to have constants in CAPITALS

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/38507#-NE2kOxm7qjIrkNO5gh-:-NE2kOxm7qjIrkNO5gh0:bc2ox1q) ([raw file](https://github.com/harness/harness-core/blob/15c1f834b9477cebb917ded3c0cd54dfcf0b101a/120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java#L26)):*
> ```Java
>   @Inject FeatureFlagService featureFlagService;
>   @Inject NGAccountSettingService accountSettingService;
>   @Inject SettingRepository settingRepository;
> ```

leave blank line

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/38507#-NE2knC_C34snKX35_fP:-NE2knCa7FZYyC6enwL0:b-fwv43t) ([raw file](https://github.com/harness/harness-core/blob/15c1f834b9477cebb917ded3c0cd54dfcf0b101a/120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java#L30)):*
> ```Java
>   public void migrate() {
>     String settingIdentifier = SettingIdentifier.disable_harness_built_in_SM;
>     Set<String> accountIds = featureFlagService.getAccountIds(FeatureName.DISABLE_HARNESS_SM);
> ```

it fetches accounts from CG?

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/38507#-NE2knC_C34snKX35_fP:-NE2kvP84bIX34MWt09v:b-ui60pa) ([raw file](https://github.com/harness/harness-core/blob/15c1f834b9477cebb917ded3c0cd54dfcf0b101a/120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java#L30)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

it fetches accounts from CG?
</blockquote></details>

Is it working?

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/38507#-NE2l17d4J5Rc9kyeFc1:-NE2l17d4J5Rc9kyeFc2:b-opdeip) ([raw file](https://github.com/harness/harness-core/blob/15c1f834b9477cebb917ded3c0cd54dfcf0b101a/120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java#L38)):*
> ```Java
>                               .allowOverrides(false)
>                               .category(CORE)
>                               .value("true")
> ```

lets use constant value here

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38507)* status: 3 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingIdentifier.java` line 11 at r1](https://reviewable.io/reviews/harness/harness-core/38507#-NE2kJxF4b1H0JCKvQA8:-NEBKunb7g5DaRX8LIAp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/15c1f834b9477cebb917ded3c0cd54dfcf0b101a/120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingIdentifier.java#L11)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

as practice, its better to have constants in CAPITALS
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/38507#-NE2kOxm7qjIrkNO5gh-:-NEEzpWUEnlbDkwjhwRW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/15c1f834b9477cebb917ded3c0cd54dfcf0b101a/120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java#L26)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

leave blank line
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/38507#-NE2knC_C34snKX35_fP:-NEEzrpIDjmkDJwP6Iqb:bvq3fl) ([raw file](https://github.com/harness/harness-core/blob/15c1f834b9477cebb917ded3c0cd54dfcf0b101a/120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java#L30)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Is it working?
</blockquote></details>

Locally, it is not working, but in QA/prod it should work as expected, right? As it will fetch from the UAT service
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/38507#-NE2l17d4J5Rc9kyeFc1:-NEF-71G7GoLsPcuxdbR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/15c1f834b9477cebb917ded3c0cd54dfcf0b101a/120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java#L38)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets use constant value here
</blockquote></details>

Done.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38507)* status: 2 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/38507#-NEFnXabDxLkpglL5NQK:-NEFnXacD4tGPtfrKnlY:b-4rur1g) ([raw file](https://github.com/harness/harness-core/blob/8a88918ef6ceb321562e9025786f41cf33f6650b/120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java#L27)):*
> ```Java
>   @Inject NGAccountSettingService accountSettingService;
>   @Inject SettingRepository settingRepository;
>   private String settingTrueValue = "true";
> ```

Should be part of method.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38507)* status: 2 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/38507#-NEFnXabDxLkpglL5NQK:-NEFoFCZAH2z-t69wb-4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a88918ef6ceb321562e9025786f41cf33f6650b/120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java#L27)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should be part of method.
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38507)* status: 2 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38507)* status: 2 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38507)* status: 4. unresolved discussions.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/38507#-NE2knC_C34snKX35_fP:-NEFq8OT54W87WPnKVMj:b-4mjrl1) ([raw file](https://github.com/harness/harness-core/blob/15c1f834b9477cebb917ded3c0cd54dfcf0b101a/120-ng-manager/src/main/java/io/harness/ng/core/migration/DisableBuiltInHarnessSMSettingsMigration.java#L30)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

Locally, it is not working, but in QA/prod it should work as expected, right? As it will fetch from the UAT service
</blockquote></details>

No, it won't work. Further, you're working with migrations, so its not that its a dead code and you can test it on any other env just like that. It will break outright.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38507)* status: :shipit: complete! ✓

**Pull request merged**
