### PR TITLE
[fix]: [SRM-12192]: Fixing retry logic for already failed tasks.

### PR DESCRIPTION
**Pull request by deepak-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38210)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38210)

**Review by praveensugavanam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38210)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/DeploymentDataCollectionTask.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/38210#-NDFDQme1rO56IbF3Upv:-NDFDQme1rO56IbF3Upw:b5qtns5) ([raw file](https://github.com/harness/harness-core/blob/2683f66fe7c155f93b943b8798cb0adeba6d4959/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/DeploymentDataCollectionTask.java#L22)):*
> ```Java
>   private static final List<Duration> RETRY_WAIT_DURATIONS = Lists.newArrayList(Duration.ofSeconds(5),
>       Duration.ofSeconds(10), Duration.ofSeconds(20), Duration.ofSeconds(30), Duration.ofMinutes(1));
>   @VisibleForTesting public static int MAX_RETRY_COUNT = 50;
> ```

why 50 ? If deployment tasks are failing, we do not want to retry for a long time. That's why this was consciously set to a low number. 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/ServiceGuardDataCollectionTaskServiceImpl.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/38210#-NDFD_W95N4mh6tHx7_f:-NDFD_W95N4mh6tHx7_g:bu81sw2) ([raw file](https://github.com/harness/harness-core/blob/484d9739a34841c5bf29513522cf14a6ad2e77d7/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/ServiceGuardDataCollectionTaskServiceImpl.java#L91)):*
> ```Java
>         getDataCollectionTask(cvConfig, nextTaskStartTime, nextTaskStartTime.plus(5, ChronoUnit.MINUTES));
>     if (prevServiceGuardTask.getStatus() != DataCollectionExecutionStatus.SUCCESS) {
>       dataCollectionTask.setRetryCount(prevServiceGuardTask.getRetryCount());
> ```

i dont understand this change. Why are we removing the retry setting ?

**Review by praveensugavanam — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38210)* status: 1. unresolved discussions.

**Review by praveensugavanam — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38210)* status: :shipit: complete! ✓

**Pull request merged**
