### PR TITLE
feat: [SSCA-100]: initialize step changes for cd orchestrate step

### PR DESCRIPTION
**Pull request by inderschera**
## Describe your changes
- Moved setting environment variables to common module for cd module to reuse it.
- Created a PluginStep which all pluginStep would implement.
- Handled pluginStep generically in initialize step execution.
- Had separate specParameters than the info class. This would prevent polluting the beans.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45225)

### CODE REVIEW

**Comment by inderschera** [comment]
trigger ut0, ut2

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45225)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/plugin/PluginStep.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/45225#-NQiOi7C0mOLXb9E4Mdt:-NQiOi7C0mOLXb9E4Mdu:b-py3dvc) ([raw file](https://github.com/harness/harness-core/blob/7cc287aeac1e48b84bd11cf20f842d8545b4f671/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/plugin/PluginStep.java#L14)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.SSCA)
> public interface PluginStep extends ContainerStepSpec {}
> ```

can we put this interface in utils and not in contracts, as its not doing anything keeing here.

Even owner is ssca so we should move to common utils
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/plugin/PluginConfig.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/45225#-NQiP4hc2x4Vz3SAwDf_:-NQiP4hd20X21Fxah0pE:b-3vz1le) ([raw file](https://github.com/harness/harness-core/blob/7cc287aeac1e48b84bd11cf20f842d8545b4f671/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/plugin/PluginConfig.java#L15)):*
> ```Java
> @Value
> @Builder
> public class PluginConfig {
> ```

add team annotation
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/plugin/StepImageConfig.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/45225#-NQiP8Hp2wmh0MkbJKo0:-NQiP8Hp2wmh0MkbJKo1:bb7swp0) ([raw file](https://github.com/harness/harness-core/blob/7cc287aeac1e48b84bd11cf20f842d8545b4f671/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/plugin/StepImageConfig.java#L16)):*
> ```Java
> @Value
> @Builder
> public class StepImageConfig {
> ```

same annotation

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45225)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/plugin/PluginStep.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/45225#-NQiOi7C0mOLXb9E4Mdt:-NQiPtmD7UjRePiyKhZD:bvq5dph) ([raw file](https://github.com/harness/harness-core/blob/7cc287aeac1e48b84bd11cf20f842d8545b4f671/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/plugin/PluginStep.java#L14)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we put this interface in utils and not in contracts, as its not doing anything keeing here.

Even owner is ssca so we should move to common utils
</blockquote></details>

It needs to be in contracts. Any future plugin step needs to implement this interface.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/plugin/PluginConfig.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/45225#-NQiP4hc2x4Vz3SAwDf_:-NQiQJUP6ZbK7LjcH910:bhljl18) ([raw file](https://github.com/harness/harness-core/blob/7cc287aeac1e48b84bd11cf20f842d8545b4f671/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/plugin/PluginConfig.java#L15)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add team annotation
</blockquote></details>

Raising separate PR for this.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/plugin/StepImageConfig.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/45225#-NQiP8Hp2wmh0MkbJKo0:-NQiQM8U-bt1X3C9GvJH:bhljl18) ([raw file](https://github.com/harness/harness-core/blob/7cc287aeac1e48b84bd11cf20f842d8545b4f671/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/plugin/StepImageConfig.java#L16)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same annotation
</blockquote></details>

Raising separate PR for this.

**Comment by abhinav-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/PluginUtils.java` line 86 at r1](https://reviewable.io/reviews/harness/harness-core/45225#-NQiTE-7D0zz7wfs2oAq:-NQiTE-7D0zz7wfs2oAr:bn43837) ([raw file](https://github.com/harness/harness-core/blob/7cc287aeac1e48b84bd11cf20f842d8545b4f671/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/PluginUtils.java#L86)):*
> ```Java
>         return ((SyftSbomOrchestration) stepInfo.getTool().getSbomOrchestrationSpec()).getFormat().toString();
>       default:
>         throw new CIStageExecutionUserException(
> ```

No CI ex

**Comment by abhinav-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/plugin/PluginExecutionConfigHelper.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/45225#-NQiTHBX6C3lcTI-j14l:-NQiTHBX6C3lcTI-j14m:b-gtkfhn) ([raw file](https://github.com/harness/harness-core/blob/7cc287aeac1e48b84bd11cf20f842d8545b4f671/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/plugin/PluginExecutionConfigHelper.java#L27)):*
> ```Java
>       case CD_SSCA_ORCHESTRATION:
>         return pluginConfig.getSscaOrchestrationConfig();
>       default:
> ```

No way to live without switch case?

**Comment by abhinav-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/InitContainerStep.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/45225#-NQiTOWP2PEtWt2Tcq7i:-NQiTOWP2PEtWt2Tcq7j:buhq160) ([raw file](https://github.com/harness/harness-core/blob/7cc287aeac1e48b84bd11cf20f842d8545b4f671/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/InitContainerStep.java#L73)):*
> ```Java
>   public void validateResources(Ambiance ambiance, StepElementParameters stepParameters) {
>     ContainerStepSpec stepParameter = (ContainerStepSpec) stepParameters.getSpec();
>     if (stepParameter.getType() == ContainerStepType.RUN_CONTAINER) {
> ```

if else?

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45225)* status: 3 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStepInitHelper.java` line 389 at r1](https://reviewable.io/reviews/harness/harness-core/45225#-NQiTR6QCu7DvOAKpRrw:-NQiUA6_4L51JyOnILwF:b-9ssoli) ([raw file](https://github.com/harness/harness-core/blob/7cc287aeac1e48b84bd11cf20f842d8545b4f671/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStepInitHelper.java#L389)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

switch case :( 
</blockquote></details>

This is in initialization step, separate steps need to have separate container initilialization
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/InitContainerStep.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/45225#-NQiTOWP2PEtWt2Tcq7i:-NQiU0CMEO_veUY3pjsw:b-2mpecc) ([raw file](https://github.com/harness/harness-core/blob/7cc287aeac1e48b84bd11cf20f842d8545b4f671/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/InitContainerStep.java#L73)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

if else?
</blockquote></details>

Yes, haven't handled validate resources for plugin yet. Will raise separate PR for this. Raised a ticket for this.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45225)* status: :shipit: complete! ✓

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/plugin/PluginStep.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/45225#-NQiOi7C0mOLXb9E4Mdt:-NQiXtYK2EJsZ7efgeE9:b6an6jr) ([raw file](https://github.com/harness/harness-core/blob/7cc287aeac1e48b84bd11cf20f842d8545b4f671/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/plugin/PluginStep.java#L14)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

It needs to be in contracts. Any future plugin step needs to implement this interface.
</blockquote></details>

done, discussed offline
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/plugin/PluginConfig.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/45225#-NQiP4hc2x4Vz3SAwDf_:-NQiXw3p7-SrvEYTuaT8:b-rnrarp) ([raw file](https://github.com/harness/harness-core/blob/7cc287aeac1e48b84bd11cf20f842d8545b4f671/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/plugin/PluginConfig.java#L15)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Raising separate PR for this.
</blockquote></details>

done, 
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/plugin/StepImageConfig.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/45225#-NQiP8Hp2wmh0MkbJKo0:-NQiXwqo5sgOZRnnlYU0:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/7cc287aeac1e48b84bd11cf20f842d8545b4f671/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/plugin/StepImageConfig.java#L16)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Raising separate PR for this.
</blockquote></details>

done

**Pull request merged**
