### PR TITLE
fix: [PIE-8864]: Fix processing of audits

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44954)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44954)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 127 at r2](https://reviewable.io/reviews/harness/harness-core/44954#-NQ9AEpK4oBlOjB2k9ia:-NQ9AEpK4oBlOjB2k9ib:b8w8p9o) ([raw file](https://github.com/harness/harness-core/blob/5d194d2bc448f5bb397ccfc8fc4745cd9a2f7db2/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L127)):*
> ```Java
>       principal = new ServicePrincipal(PIPELINE_SERVICE.getServiceId());
>     } else if (globalContext.get(PRINCIPAL_CONTEXT) != null) {
>       principal = ((PrincipalContextData) globalContext.get(PRINCIPAL_CONTEXT)).getPrincipal();
> ```

should we reverse the condition if not null then set else always set servicePrincipal

Also add some docs to debug this - https://harness.atlassian.net/wiki/spaces/PIPE/pages/1746600461/Pipeline+Troubleshooting



_Code quote:_
```Java
    if (globalContext.get(PRINCIPAL_CONTEXT) == null) {
      principal = new ServicePrincipal(PIPELINE_SERVICE.getServiceId());
    } else if (globalContext.get(PRINCIPAL_CONTEXT) != null) {
      principal = ((PrincipalContextData) globalContext.get(PRINCIPAL_CONTEXT)).getPrincipal();
    }
```

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 126 at r2](https://reviewable.io/reviews/harness/harness-core/44954#-NQ9BvQt-Z4oWjNWKUZj:-NQ9BvQu9ZrdsXfEdUUx:b-kl02qq) ([raw file](https://github.com/harness/harness-core/blob/5d194d2bc448f5bb397ccfc8fc4745cd9a2f7db2/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L126)):*
> ```Java
>     if (globalContext.get(PRINCIPAL_CONTEXT) == null) {
>       principal = new ServicePrincipal(PIPELINE_SERVICE.getServiceId());
>     } else if (globalContext.get(PRINCIPAL_CONTEXT) != null) {
> ```

why's there an if again? If previous "if" failed, that means the value is not null only, right?

**Review by ankittiwari-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44954)* status: 6 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 126 at r2](https://reviewable.io/reviews/harness/harness-core/44954#-NQ9BvQt-Z4oWjNWKUZj:-NQO8yqqEfQfwrj8I7eg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5d194d2bc448f5bb397ccfc8fc4745cd9a2f7db2/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L126)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why's there an if again? If previous "if" failed, that means the value is not null only, right?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 127 at r2](https://reviewable.io/reviews/harness/harness-core/44954#-NQ9AEpK4oBlOjB2k9ia:-NQO9-yj38245usPDM-n:b-h698gr) ([raw file](https://github.com/harness/harness-core/blob/5d194d2bc448f5bb397ccfc8fc4745cd9a2f7db2/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L127)):*
> Done.

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44954)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Pull request merged**
