### PR TITLE
feat: [CDS-37891]: GET API for serviceOverrides

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
GET API which takes a non null environmentIdentifier and nullable serviceIdentifier

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33873)

### CODE REVIEW

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33873)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 558 at r1](https://reviewable.io/reviews/harness/harness-core/33873#-N3cGTIb9_QbXACEw9DI:-N3cGTIb9_QbXACEw9DJ:b-o6ebqy) ([raw file](https://github.com/harness/harness-core/blob/e6f6912d5dcc7ed9b041279e4254260e175428b2/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L558)):*
> ```Java
>     environmentValidationHelper.checkThatEnvExists(accountId, orgIdentifier, projectIdentifier, environmentIdentifier);
> 
>     if (serviceIdentifier != null) {
> ```

we should check for isNotEmpty() instead of null
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java` line 189 at r1](https://reviewable.io/reviews/harness/harness-core/33873#-N3cGtyG6Z3riSquKSDm:-N3cGtyG6Z3riSquKSDn:bqxdj8g) ([raw file](https://github.com/harness/harness-core/blob/e6f6912d5dcc7ed9b041279e4254260e175428b2/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java#L189)):*
> ```Java
>       String accountId, String orgIdentifier, String projectIdentifier, String environmentRef, String serviceRef) {
>     Criteria criteria = CoreCriteriaUtils.createCriteriaForGetList(accountId, orgIdentifier, projectIdentifier);
>     criteria.and("environmentRef").is(environmentRef);
> ```

we should use fieldNamekeys instead of hardcoding

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33873)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 558 at r1](https://reviewable.io/reviews/harness/harness-core/33873#-N3cGTIb9_QbXACEw9DI:-N3cLHDj0yuSGOynLFO7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6f6912d5dcc7ed9b041279e4254260e175428b2/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L558)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should check for isNotEmpty() instead of null
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java` line 189 at r1](https://reviewable.io/reviews/harness/harness-core/33873#-N3cGtyG6Z3riSquKSDm:-N3cLII_7IDgT8aEr0i2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6f6912d5dcc7ed9b041279e4254260e175428b2/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java#L189)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should use fieldNamekeys instead of hardcoding 
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33873)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 534 at r2](https://reviewable.io/reviews/harness/harness-core/33873#-N3cLvbE3Ld1TDGzgg5o:-N3cLvbE3Ld1TDGzgg5p:bjqcsqc) ([raw file](https://github.com/harness/harness-core/blob/c01629efb955ec666232e935a9c0304bd05e17d6/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L534)):*
> ```Java
>   // do not delete this.
>   public ResponseDTO<NGServiceOverrideConfig>
>   get() {
> ```

lets change the name of the method from ```get```

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33873)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33873)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
trigger ti0

**Pull request merged**
