### PR TITLE
[fix]: [PIE-8413]: Fix nextStepAdviser not being attached to stepGrou…

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
…p inside stepGrounp under parallel

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44130)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44130)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/test/java/io/harness/utils/PlanCreatorUtilsTest.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/44130#-NOmLf6r81AKo2ihwHz7:-NOmLf6r81AKo2ihwHz8:blbafo6) ([raw file](https://github.com/harness/harness-core/blob/abdb2f433bc89e22fd06746496b349b6de0958f4/878-ng-common-utilities/src/test/java/io/harness/utils/PlanCreatorUtilsTest.java#L105)):*
> ```Java
>   public void testGetFailureStrategiesStepGroupInsideStepGroupWithDepthAs1() throws IOException {
>     ClassLoader classLoader = this.getClass().getClassLoader();
>     final URL testFile = classLoader.getResource("pipeline-with-stepGroup-inside-stepGroup.yaml.yaml");
> ```

is this expected?



_Code quote:_
```Java
pipeline-with-stepGroup-inside-stepGroup.yaml.yaml
```
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/GenericPlanCreatorUtils.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/44130#-NOmLywGDSGFv2qZ40BG:-NOmLywGDSGFv2qZ40BH:bpg6pip) ([raw file](https://github.com/harness/harness-core/blob/abdb2f433bc89e22fd06746496b349b6de0958f4/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/GenericPlanCreatorUtils.java#L83)):*
> ```Java
>           return true;
>         }
>         return !Objects.equals(
> ```

I think instead of comparing complete complete current field can we do, can we connect and see if there is any other better way, as we have many condition added in if condition so we can recheck those and have simple condition if possible?

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/GenericPlanCreatorUtils.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/44130#-NOmLywGDSGFv2qZ40BG:-NOmYrbm35JXP9wFt_eX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/abdb2f433bc89e22fd06746496b349b6de0958f4/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/GenericPlanCreatorUtils.java#L83)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I think instead of comparing complete complete current field can we do, can we connect and see if there is any other better way, as we have many condition added in if condition so we can recheck those and have simple condition if possible?
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44130)* status: 10 file(s) to review. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/test/java/io/harness/utils/PlanCreatorUtilsTest.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/44130#-NOmLf6r81AKo2ihwHz7:-NOmgXCb3it5itVUROFK:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/abdb2f433bc89e22fd06746496b349b6de0958f4/878-ng-common-utilities/src/test/java/io/harness/utils/PlanCreatorUtilsTest.java#L105)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

is this expected?
</blockquote></details>

done

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Pull request merged**
