### PR TITLE
fix: [CDS-50346]: Instances sync for account level agent

### PR DESCRIPTION
**Pull request by meenaravichandran1**
## Describe your changes
This change is to make instances sync possible for account level agents.

For account level agents, the request params will be of format
`{"AccountIdentifier": "kmpySmUISimoRrJL6NL73w",
    "OrgIdentifier": "",
    "ProjectIdentifier": "",
    "AgentIdentifier": "account.localagentkmp"}`

and the request body will be of format
`"Body": [
        {
            "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
            "orgIdentifier": "default",
            "projectIdentifier": "meenalocal",
            "applicationIdentifier": "dashboard-app-cluster11",
            "agentIdentifier": "account.localagentkmp",
            "envIdentifier": "Prod",
            "serviceIdentifier": "myservicek8s",
            ....          
        }
    ]`

request param has agent's account, org and project id and request body has instances's account, org and project id.

Request params will be used for deletion where the account id and agent id will be used for deletion of instances for account level agents.

For instances addition/updation, they are first grouped based on org, project ids (from instance objects in request) and then processed as same as project level agents.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42533)

### CODE REVIEW

**Comment by meenaravichandran1** [comment]
trigger messagecheck

**Comment by meenaravichandran1** [comment]
trigger ti2

**Review by rohitk-h — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42533#-:-NLbnEdpDTkkAx2x5eiu:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42533)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/service/instance/InstanceServiceImpl.java` line 326 at r1](https://reviewable.io/reviews/harness/harness-core/42533#-NLgpM6GC06bD8n9nCr7:-NLgpM6GC06bD8n9nCr8:b-i3zw01) ([raw file](https://github.com/harness/harness-core/blob/efc20a8cd717fd2865a92a04aa7e2c179831d8a4/126-instance/src/main/java/io/harness/service/instance/InstanceServiceImpl.java#L326)):*
> ```Java
>                             .is(false);
> 
>     if (!orgIdentifier.isBlank()) {
> ```

use isNotEmpty check since it can be null too.

**Comment by abhinav-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/42533#-NLgrdA_7FYrByUzg7Fr:-NLgrdAa1xwAwP_ho8FR:bpxgvzt) ([raw file](https://github.com/harness/harness-core/blob/efc20a8cd717fd2865a92a04aa7e2c179831d8a4/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L106)):*
> ```Java
>             prepareInstanceSync(accountId, orgId, projectId, instancesPerProject.getValue());
> 
>         if (processedInstances.isEmpty()) {
> ```

isEmpty method check (although its safe here but better practice)

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42533)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/42533#-NLgriZK95LWzvHG08i3:-NLgriZK95LWzvHG08i4:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/efc20a8cd717fd2865a92a04aa7e2c179831d8a4/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L112)):*
> ```Java
>             gitOpsRequestDTOMapper.toInstanceDTOList(accountId, orgId, projectId, processedInstances);
> 
>         if (instanceDTOs.isEmpty()) {
> ```

ditto

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42533)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/42533#-NLgrdA_7FYrByUzg7Fr:-NLgxpBq7V4zZvgK-QrE:b-bd9qv0) ([raw file](https://github.com/harness/harness-core/blob/efc20a8cd717fd2865a92a04aa7e2c179831d8a4/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L106)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

isEmpty method check (although its safe here but better practice)
</blockquote></details>

did not get this?
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/42533#-NLgriZK95LWzvHG08i3:-NLgxtyz5pDncMvjNOfY:b-bd9qv0) ([raw file](https://github.com/harness/harness-core/blob/efc20a8cd717fd2865a92a04aa7e2c179831d8a4/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L112)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

did not get this?
___
*[`126-instance/src/main/java/io/harness/service/instance/InstanceServiceImpl.java` line 326 at r1](https://reviewable.io/reviews/harness/harness-core/42533#-NLgpM6GC06bD8n9nCr7:-NLgyA1U-jjgnP4TFu52:b-4tu9us) ([raw file](https://github.com/harness/harness-core/blob/efc20a8cd717fd2865a92a04aa7e2c179831d8a4/126-instance/src/main/java/io/harness/service/instance/InstanceServiceImpl.java#L326)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

use isNotEmpty check since it can be null too.
</blockquote></details>

this will not be null. Not null checks are added here https://github.com/harness/harness-core/blob/cds-50346/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42533)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/42533#-NLgrdA_7FYrByUzg7Fr:-NLgzIK8-nTRi3AQzvB1:bjcshj9) ([raw file](https://github.com/harness/harness-core/blob/efc20a8cd717fd2865a92a04aa7e2c179831d8a4/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L106)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

did not get this?
</blockquote></details>

these are initialized with empty lists in the method, so this wouldn't cause any issue right now, will update this in the next PR
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/42533#-NLgriZK95LWzvHG08i3:-NLgz_3bENdW9g-HanAJ:bjcshj9) ([raw file](https://github.com/harness/harness-core/blob/efc20a8cd717fd2865a92a04aa7e2c179831d8a4/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L112)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

did not get this?
</blockquote></details>

these are initialized with empty lists in the method, so this wouldn't cause any issue right now, will update this in the next PR

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42533)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42533#-:-NLhAbz91kqGh2a9AFhf:bnfp4nl)* status: :shipit: complete! ✓

**Review by meenaravichandran1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42533)* status: :shipit: complete! ✓

**Pull request merged**
