### PR TITLE
[feat]: [PL-24910]: Fix SSH, Account test connection for AzureRepo connector

### PR DESCRIPTION
**Pull request by mankrit-singh**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33065)

### CODE REVIEW

**Comment by mankrit-singh** [comment]
trigger ft2

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33065)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 722 at r1](https://reviewable.io/reviews/harness/harness-core/33065#-N1qoFu-3Xs0QrWTeF_N:-N1qoFu-3Xs0QrWTeF_O:bb74tog) ([raw file](https://github.com/harness/harness-core/blob/7e7ca623452cf9efe15d272bdfaa36295d073030/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L722)):*
> ```Java
>     environment.jersey().register(WingsExceptionMapperV2.class);
>     environment.jersey().register(GenericExceptionMapperV2.class);
>     environment.jersey().register(JsonProcessingExceptionMapper.class);
> ```

V2 ?

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33065)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33065)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by ashishsanodia-harness** [comment]
:lgtm:

**Review by ashishsanodia-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33065)* status: 4 file(s) to review.

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33065)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/git/GitClientHelper.java` line 211 at r3](https://reviewable.io/reviews/harness/harness-core/33065#-N2GP2UY2PuHBevuLFOg:-N2GP2UY2PuHBevuLFOh:b-92vqa4) ([raw file](https://github.com/harness/harness-core/blob/3d49046ae835e2125469982a5a8e2982ef274119/960-api-services/src/main/java/io/harness/git/GitClientHelper.java#L211)):*
> ```Java
>   }
> 
>   public static String getAzureRepoOrg(String orgAndProject) {
> ```

Add UTs for this functions too

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33065)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by ashishsanodia-harness** [comment]
:lgtm:

**Review by ashishsanodia-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 4 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33065)* status: :shipit: complete! ✓

**Pull request merged**
