### PR TITLE
feat: [SMP-1381]: Compare expiry time for license validation

### PR DESCRIPTION
**Pull request by kapilgarg1996**
## Describe your changes
1. Compare expiry times of licenses fetched from database and present in license string
2. Refactor code to reduce complexity
3. Change email message on license validation failure

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50192)

### CODE REVIEW

**Comment by kapilgarg1996** [comment]
trigger messagecheck

**Comment by kapilgarg1996** [comment]
trigger uts

**Comment by kapilgarg1996** [comment]
trigger uts

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50192)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/jobs/SMPLicenseValidationJob.java` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/50192#-NZf5W1d23qzgICuIEIz:-NZf5W1d23qzgICuIEJ-:b7i3w00) ([raw file](https://github.com/harness/harness-core/blob/d8a928637354915b3b12f8778f4ccf981e07771a/930-ng-license-manager/src/main/java/io/harness/licensing/jobs/SMPLicenseValidationJob.java#L16)):*
> ```Java
> public interface SMPLicenseValidationJob {
>   void scheduleValidation(
>       String accountId, SMPLicense licenseSign, int frequencyInMinutes, Function<String, SMPLicense> licenseProvider);
> ```

nit: rename the variable to smpLicense, just the way its done at other places
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/jobs/SMPLicenseValidationTask.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/50192#-NZf6SE26oj0rbS_7mBz:-NZf6SE26oj0rbS_7mC-:bgb3sf4) ([raw file](https://github.com/harness/harness-core/blob/d8a928637354915b3b12f8778f4ccf981e07771a/930-ng-license-manager/src/main/java/io/harness/licensing/jobs/SMPLicenseValidationTask.java#L71)):*
> ```Java
>   }
> 
>   private boolean compareLicenses(SMPLicense smpLicenseFromDb, SMPLicense license) {
> ```

nit: IMO compareLicenses() should be renamed to describe which 2 license we are comparing, e.g. isSmpLicenseMatchesXyzLicense(), this sounds more self explanatory
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/jobs/SMPLicenseValidationTask.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/50192#-NZf6I3-DUgasHEOYqnV:-NZf6I3-DUgasHEOYqnW:b-cu5gw8) ([raw file](https://github.com/harness/harness-core/blob/d8a928637354915b3b12f8778f4ccf981e07771a/930-ng-license-manager/src/main/java/io/harness/licensing/jobs/SMPLicenseValidationTask.java#L87)):*
> ```Java
>       }
>       ModuleLicenseDTO dbLicense = licensesFromDb.get(moduleType);
>       ModuleLicenseDTO pLicense = licenses.get(moduleType);
> ```

nit: lets name pLicense better
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/jobs/SMPLicenseValidationTask.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/50192#-NZf7HYA-EIjC95JSAfh:-NZf7HYA-EIjC95JSAfi:bwt1t58) ([raw file](https://github.com/harness/harness-core/blob/d8a928637354915b3b12f8778f4ccf981e07771a/930-ng-license-manager/src/main/java/io/harness/licensing/jobs/SMPLicenseValidationTask.java#L111)):*
> ```Java
>       lastValidTimeMs = System.currentTimeMillis();
>     } else {
>       log.error("SMP License did not match with license in DB");
> ```

you can print accountId for better debugging latter
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/jobs/SMPLicenseValidationTask.java` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/50192#-NZf77FY1iNQ_uZwXe6J:-NZf77FY1iNQ_uZwXe6K:b-3mkzds) ([raw file](https://github.com/harness/harness-core/blob/d8a928637354915b3b12f8778f4ccf981e07771a/930-ng-license-manager/src/main/java/io/harness/licensing/jobs/SMPLicenseValidationTask.java#L112)):*
> ```Java
>     } else {
>       log.error("SMP License did not match with license in DB");
>       if (System.currentTimeMillis() - lastValidTimeMs > 86400000) {
> ```

nit: lets put 86400000 into a static final variable
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/jobs/SMPLicenseValidationTaskFactory.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/50192#-NZf7PJQ6emAT-JPTcUc:-NZf7PJQ6emAT-JPTcUd:b-yzv7ug) ([raw file](https://github.com/harness/harness-core/blob/d8a928637354915b3b12f8778f4ccf981e07771a/930-ng-license-manager/src/main/java/io/harness/licensing/jobs/SMPLicenseValidationTaskFactory.java#L17)):*
> ```Java
> public interface SMPLicenseValidationTaskFactory {
>   SMPLicenseValidationTask create(@Assisted("accountId") String accountIdentifier,
>       @Assisted("license") SMPLicense license,
> ```

nit: rename to smpLicense
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/services/DefaultLicenseServiceImpl.java` line 485 at r2](https://reviewable.io/reviews/harness/harness-core/50192#-NZf7WPyBUoMVqxHDMzk:-NZf7WPyBUoMVqxHDMzl:b-inea4b) ([raw file](https://github.com/harness/harness-core/blob/d8a928637354915b3b12f8778f4ccf981e07771a/930-ng-license-manager/src/main/java/io/harness/licensing/services/DefaultLicenseServiceImpl.java#L485)):*
> ```Java
> 
>     if (Objects.isNull(moduleLicensesFromDb) || moduleLicensesFromDb.isEmpty() || Objects.isNull(accountDTO)) {
>       throw new InvalidRequestException("There might be no account or module license present in db");
> ```

nit: you can use log.error() before throwing the exception for better debugging latter

**Comment by kapilgarg1996** [comment]
trigger uts

**Comment by kapilgarg1996** [comment]
trigger uts

**Comment by kapilgarg1996** [comment]
trigger ut7

**Comment by kapilgarg1996** [comment]
trigger ut7

**Review by kapil-harness — DISMISSED** [review]
> Reviewed 4 of 7 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50192)* status: :shipit: complete! ✓

**Comment by kapilgarg1996** [comment]
trigger uts

**Review by kapil-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50192)* status: :shipit: complete! ✓

**Pull request merged**
