### PR TITLE
feat: [PL-23399]: Change in Resource Filter

### PR DESCRIPTION
**Pull request by reetika04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31183)

### CODE REVIEW

**Comment by reetika04** [comment]
trigger messagecheck

**Review by karansiwach360 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31183)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[830-resource-group/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java, line 146 at r1](https://reviewable.io/reviews/harness/harness-core/31183#-MxOf-lS0kO-Kruj6Jpl:-MxOf-lS0kO-Kruj6Jpm:bocf66z) ([raw file](https://github.com/harness/harness-core/blob/e7ea26530e8e1fa7c9977b1f483689c6d8b04f91/830-resource-group/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java#L146)):*
> ```Java
>       resourceGroupFilterDTO.getResourceSelectorFilterList().forEach(resourceSelectorFilter
>           -> resourceSelectorCriteria.add(Criteria.where(ResourceGroupKeys.resourceFilter)
>                                               .where(ResourceFilterKeys.resources)
> ```

I think it should be ResourceGroupKeys.resourceFilter+ResourceGroupKeys.resources

**Review by karansiwach360 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31183)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[830-resource-group/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java, line 147 at r1](https://reviewable.io/reviews/harness/harness-core/31183#-MxOfTt5Eem7cOULZzOR:-MxOfTt5Eem7cOULZzOS:b-mknp56) ([raw file](https://github.com/harness/harness-core/blob/e7ea26530e8e1fa7c9977b1f483689c6d8b04f91/830-resource-group/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java#L147)):*
> ```Java
>           -> resourceSelectorCriteria.add(Criteria.where(ResourceGroupKeys.resourceFilter)
>                                               .where(ResourceFilterKeys.resources)
>                                               .elemMatch(Criteria.where(ResourceSelectorKeys.resourceType)
> ```

There is an index in v1 model resourceGroupPrimaryKey_resourceSelectors, we would similar for v2 as well for this query.

**Comment by reetika04** [comment]
trigger checkstyle

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 9 of 15 files at r1, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31183#-:-MxhwP0_4JvWAazlyAy-:bnfp4nl)* status: 7 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by ujjawal-harness — APPROVED** [review]
:lgtm:

> Reviewed 9 of 15 files at r1, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31183#-:-MxiJCP3BxvJ9xQeJZbZ:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
