### PR TITLE
feat: [CDS-54375]: add new query parameter and filter to graphql

### PR DESCRIPTION
**Pull request by rafaelmart1ns**
## Describe your changes
The filter and query parameter added is to show disabled users.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44552)

### CODE REVIEW

**Comment by rafaelmart1ns** [comment]
trigger utAll

**Comment by rafaelmart1ns** [comment]
trigger checkstylecodeformat

**Comment by rafaelmart1ns** [comment]
trigger smartchecks

**Comment by rafaelmart1ns** [comment]
trigger ss

**Comment by rafaelmart1ns** [comment]
trigger utAll

**Comment by rafaelmart1ns** [comment]
trigger utAll

**Review by lasdox — DISMISSED** [review]
> Reviewed 17 of 18 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44552)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Review by franciscojuniorharness — APPROVED** [review]
> Reviewed 17 of 18 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44552)* status: :shipit: complete! ✓

**Review by Fernando-Dourado — CHANGES_REQUESTED** [review]
> Reviewed 17 of 18 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44552)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/graphql/datafetcher/user/UserQueryHelper.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/44552#-NQ0NpWdEWo05c28Uv6B:-NQ0NpWdEWo05c28Uv6C:b-6jgz6s) ([raw file](https://github.com/harness/harness-core/blob/75e0e31ee13bb65938f1b7b9ab2180af7de1d2d1/400-rest/src/main/java/software/wings/graphql/datafetcher/user/UserQueryHelper.java#L59)):*
> ```Java
>     }
>     filters.forEach(filter -> {
>       if (!filter.getIncludeDisabled()) {
> ```

I did not see any unit test for this new method. What can happen when getIncludeDisabled returns null?

**Comment by rafaelmart1ns** [comment]
trigger ut7

**Comment by rafaelmart1ns** [comment]
trigger ut1

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 2 of 4 files at r4, 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44552)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44552)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by franciscojuniorharness — APPROVED** [review]
> Reviewed 2 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44552)* status: :shipit: complete! ✓

**Pull request merged**
