### PR TITLE
feat: [PIE-3183]: Debezium Service Refactoring Part 1

### PR DESCRIPTION
**Pull request by hextechpal**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31517)

### CODE REVIEW

**Review by naidu-harness — DISMISSED** [review]
:lgtm:

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31517#-:-MyIuJJq1PupQN9b_u1B:bnfp4nl)* status: 21 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31517)* status: :shipit: complete! ✓

**Comment by hextechpal** [comment]
trigger ti0

**Comment by hextechpal** [comment]
trigger messagecheck

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 10 of 14 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31517#-:-MyfWQWE0I0-jRstUrDJ:bnfp4nl)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Review by shalini-agr — APPROVED** [review]
> Reviewed 10 of 21 files at r1, 10 of 14 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31517)* status: :shipit: complete! ✓

**Pull request merged**
