### PR TITLE
feat: [CODE-1151]: scm facilitator connectorless

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Describe your changes
we are introducing harness code as a git repository which is connectorless since it is internal harness repo. 
To support it we need connectorless git sync. To make the flow easy a dummy harness code connector is introduced once we know connector ref is null.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56204)

### CODE REVIEW

**Comment by abhinav-harness** [comment]
trigger uts

**Comment by abhinav-harness** [comment]
trigger uts

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56204)* status: 13 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/utils/HarnessCodeConnectorUtils.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/56204#-NkqvTF81m8JlBCoWjAS:-NkqvTF81m8JlBCoWjAT:b-knwohx) ([raw file](https://github.com/harness/harness-core/blob/ab4f5ea61ddc64097532ef6ec977dc34674ecd1c/440-connector-nextgen/src/main/java/io/harness/connector/utils/HarnessCodeConnectorUtils.java#L24)):*
> ```Java
> @UtilityClass
> public class HarnessCodeConnectorUtils {
>   public HarnessConnectorDTO getDummyHarnessCodeConnectorWithJwtAuth(String repoName, String projectId, String orgId,
> ```

can we follow some convention for arguments order? eg: Everywhere we tend to keep accountid, orgid, and projectid in given order itself, so lets keep it the same here as well for easy readability.

**Comment by abhinav-harness** [comment]
trigger uts

**Comment by abhinav-harness** [comment]
trigger uts

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56204)* status: 13 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncConnectorServiceImpl.java` line 313 at r4](https://reviewable.io/reviews/harness/harness-core/56204#-NkwDtsbEFwFkcqa_i65:-NkwDtsbEFwFkcqa_i66:b5vi45w) ([raw file](https://github.com/harness/harness-core/blob/b37b9095544c7945b3b961d71bf143c708e374b5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncConnectorServiceImpl.java#L313)):*
> ```Java
> 
>   private ScmConnector getHarnessCodeConnector(
>       String repoName, String projectIdentifier, String orgIdentifier, String accountId) {
> ```

convention for the arguments order

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56204)* status: 13 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/utils/HarnessCodeConnectorUtils.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/56204#-NkwEmRO7O05yzZ5sEi2:-NkwEmRO7O05yzZ5sEi3:b-8ik5n6) ([raw file](https://github.com/harness/harness-core/blob/b37b9095544c7945b3b961d71bf143c708e374b5/440-connector-nextgen/src/main/java/io/harness/connector/utils/HarnessCodeConnectorUtils.java#L26)):*
> ```Java
>   public HarnessConnectorDTO getDummyHarnessCodeConnectorWithJwtAuth(String repoName, String accountId, String orgId,
>       String projectId, String serviceName, String serviceSecret, String harnessCodeApiBaseUrl,
>       ServiceTokenGenerator tokenGenerator) {
> ```

we shouldn't be taking service as an argument. If required, we can convert this class into singleton to avoid taking service as an argument.

**Comment by abhinav-harness** [comment]
trigger uts

**Comment by abhinav-harness** [comment]
trigger uts

**Comment by abhinav-harness** [comment]
trigger uts

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 6 of 10 files at r1, 2 of 3 files at r2, 1 of 3 files at r3, 1 of 3 files at r4, 1 of 3 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56204)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
trigger uts

**Review by mohitg0795 — DISMISSED** [review]

**Review by sribalij — APPROVED** [review]

**Comment by abhinav-harness** [comment]
trigger uts

**Comment by deepak-harness** [comment]
trigger ut7

**Pull request merged**
