### PR TITLE
feat: [CDS-34976]: Add support for json plan in NG

### PR DESCRIPTION
**Pull request by abosii-harness**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---

Is it new task type? (If yes, no need to answer 2 then)
No

Did you add a new class which is added in kryo serialization
N/A

if yes then do not use that class in any of the delegate task payload till it makes to delegate release
N/A

Did you make changes to the code in a backward-compatible manner?
Yes

will the new version of the delegate receive old version task and process?
Yes

If new version of the manager receives response for the old task will it be able to handle it successfully?
Yes

Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager
Yes (added new field in task response)

If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay
Yes

if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay
Yes

Did you remove an enum → this is not backward compatible yet (tracked by [DEL-3648: Move to name based kryo serializer for delegate/manager communicationIN PROGRESS](https://harness.atlassian.net/browse/DEL-3648) )
No

Did you add an enum → make sure that the enum constant is added in the end of the already defined constants. If you don’t do this then you will have issues where wrong enum type will be deserialized in delegate side.
Yes (FeatureName)

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33454)

### CODE REVIEW

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33454)* status: 35 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 241 at r1](https://reviewable.io/reviews/harness/harness-core/33454#-N2vqGNS81LRwIjqFC3Y:-N2vqGNS81LRwIjqFC3Z:b32vhw) ([raw file](https://github.com/harness/harness-core/blob/30115751dceaac3710c642107f2a075ce437cfa4/120-ng-manager/config.yml#L241)):*
> ```YAML
>   authority: localhost
> 
> shouldConfigureWithPMS: true
> ```

:)

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 25 of 35 files at r1, 12 of 15 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33454)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33454)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 21 of 35 files at r1, 11 of 15 files at r2, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33454#-:-N34Mu4k0rlzUR0qWih3:bnfp4nl)* status: :shipit: complete! ✓

**Comment by abosii-harness** [comment]
Is it new task type? (If yes, no need to answer 2 then)
No

Did you add a new class which is added in kryo serialization
N/A

if yes then do not use that class in any of the delegate task payload till it makes to delegate release
N/A

Did you make changes to the code in a backward-compatible manner?
Yes

will the new version of the delegate receive old version task and process?
Yes

If new version of the manager receives response for the old task will it be able to handle it successfully?
Yes

Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager
Yes (added new field in task response)

If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay
Yes

if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay
Yes

Did you remove an enum → this is not backward compatible yet (tracked by [DEL-3648: Move to name based kryo serializer for delegate/manager communicationIN PROGRESS](https://harness.atlassian.net/browse/DEL-3648) )
No

Did you add an enum → make sure that the enum constant is added in the end of the already defined constants. If you don’t do this then you will have issues where wrong enum type will be deserialized in delegate side.
No

**Review by mdmilic — APPROVED** [review]
approve hashcheck change

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33454#-:-N34YHwXB86QlCPCCaLf:b-h090oi)* status: :shipit: complete! ✓

**Pull request merged**
