### PR TITLE
feat: [PIE-6182]: Running executions per account dashboard and alerts

### PR DESCRIPTION
**Pull request by sribalij**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39737)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39737)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetric.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/39737#-NGKPBJI0DTQuIJSZjRI:-NGKPBJI0DTQuIJSZjRJ:b2jzxl6) ([raw file](https://github.com/harness/harness-core/blob/74a686aa585b2a544c40a7ed18b6269f59fba9a6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetric.java#L18)):*
> ```Java
> @Builder
> @EqualsAndHashCode
> public class PlanExecutionMetric {
> ```

I think the PR heading needs to change, this change is still for number of executions per account and not total nodes
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMonitorServiceImpl.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/39737#-NGKPUlT0VCMJ0LIxlx9:-NGKPUlT0VCMJ0LIxlxA:btjnot4) ([raw file](https://github.com/harness/harness-core/blob/74a686aa585b2a544c40a7ed18b6269f59fba9a6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMonitorServiceImpl.java#L51)):*
> ```Java
>       metricMap.put(planExecutionMetric, metricMap.getOrDefault(planExecutionMetric, 0) + 1);
>     }
>     Map<String, String> metricContextMap = new HashMap<>();
> ```

shouldnt this be equal to immutable map in the for loop?



_Code quote:_
```Java
Map<String, String> metricContextMap =
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMonitorServiceImpl.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/39737#-NGKPXqP5AZJphlKU7p8:-NGKPXqP5AZJphlKU7p9:b-nzckok) ([raw file](https://github.com/harness/harness-core/blob/74a686aa585b2a544c40a7ed18b6269f59fba9a6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMonitorServiceImpl.java#L62)):*
> ```Java
> 
>       try (PmsMetricContextGuard pmsMetricContextGuard = new PmsMetricContextGuard(metricContextMap)) {
>         metricService.recordMetric(ACTIVE_EXECUTION_COUNT_METRIC_NAME, entry.getValue());
> ```

Any benefit we will get based on recordMetric vs incCounter? Otherwise the change looks fine
___
*[`pipeline-service/service/src/main/resources/metrics/metricDefinitions/execution-count-metrics.yaml` line 6 at r1](https://reviewable.io/reviews/harness/harness-core/39737#-NGKa_m1CnTzLIBrbE23:-NGKa_m1CnTzLIBrbE24:by309w1) ([raw file](https://github.com/harness/harness-core/blob/74a686aa585b2a544c40a7ed18b6269f59fba9a6/pipeline-service/service/src/main/resources/metrics/metricDefinitions/execution-count-metrics.yaml#L6)):*
> ```YAML
> metrics:
>   - metricName: active_execution_count
>     metricDefinition: Number of active executions at a given instant
> ```

we have group yaml for this count, I think we should add env type there as well

**Comment by abhayganvir** [comment]
trigger igp

**Review by sribalij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39737)* status: 4 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetric.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/39737#-NGKPBJI0DTQuIJSZjRI:-NGQRjgeEBKb8YhgKEMj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/74a686aa585b2a544c40a7ed18b6269f59fba9a6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetric.java#L18)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I think the PR heading needs to change, this change is still for number of executions per account and not total nodes
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMonitorServiceImpl.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/39737#-NGKPUlT0VCMJ0LIxlx9:-NGQRsJ27eGT376jy9Ah:b-iypmbn) ([raw file](https://github.com/harness/harness-core/blob/74a686aa585b2a544c40a7ed18b6269f59fba9a6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMonitorServiceImpl.java#L51)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

shouldnt this be equal to immutable map in the for loop?
</blockquote></details>

Discussed offline
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMonitorServiceImpl.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/39737#-NGKPXqP5AZJphlKU7p8:-NGQRmXs176eKgTByvPP:b-iypmbn) ([raw file](https://github.com/harness/harness-core/blob/74a686aa585b2a544c40a7ed18b6269f59fba9a6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMonitorServiceImpl.java#L62)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Any benefit we will get based on recordMetric vs incCounter? Otherwise the change looks fine
</blockquote></details>

Discussed offline
___
*[`pipeline-service/service/src/main/resources/metrics/metricDefinitions/execution-count-metrics.yaml` line 6 at r1](https://reviewable.io/reviews/harness/harness-core/39737#-NGKa_m1CnTzLIBrbE23:-NGQRvcGEKxFaok6NHLk:b-iypmbn) ([raw file](https://github.com/harness/harness-core/blob/74a686aa585b2a544c40a7ed18b6269f59fba9a6/pipeline-service/service/src/main/resources/metrics/metricDefinitions/execution-count-metrics.yaml#L6)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we have group yaml for this count, I think we should add env type there as well
</blockquote></details>

Discussed offline

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39737)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by sribalij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39737)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMonitorServiceImpl.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/39737#-NGKPUlT0VCMJ0LIxlx9:-NGQVMi65CNQpInzJXt-:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/74a686aa585b2a544c40a7ed18b6269f59fba9a6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMonitorServiceImpl.java#L51)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Discussed offline
</blockquote></details>

Done

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39737)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39737)* status: :shipit: complete! ✓

**Comment by sribalij** [comment]
trigger messagecheck

**Comment by sribalij** [comment]
trigger compile

**Comment by sribalij** [comment]
trigger ti3

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39737)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
