### PR TITLE
feat: [CDS-36395]: populate template references on template crud

### PR DESCRIPTION
**Pull request by inderschera**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32931)

### CODE REVIEW

**Review by inderschera — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 22 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32931)* status: 23 file(s) to review. 0 of 1 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java` line 168 at r2](https://reviewable.io/reviews/harness/harness-core/32931#-N5Kfpdb51Y58FiOn-nU:-N5KfpdcDfyD13jRw1Pi:b-4nftbd) ([raw file](https://github.com/harness/harness-core/blob/22bb8d0e95540ea98fd7bc7fcb63a89977a34432/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java#L168)):*
> ```Java
>       String fqn = null;
>       if (EntityTypeProtoEnum.TEMPLATE.equals(entityDetailProtoDTO.getType())) {
>         fqn = entityDetailProtoDTO.getTemplateRef().getMetadataMap().get("fqn");
> ```

Use PreFlightCheckMetadata.FQN
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java` line 183 at r2](https://reviewable.io/reviews/harness/harness-core/32931#-N5Kf_9CAld0DVgsbxN6:-N5Kf_9CAld0DVgsbxN7:b-cgvh0b) ([raw file](https://github.com/harness/harness-core/blob/22bb8d0e95540ea98fd7bc7fcb63a89977a34432/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java#L183)):*
> ```Java
>   }
> 
>   private EntityReferredByPipelineDetailProtoDTO getSetupDetailProtoDTO(String fqn) {
> ```

If not able to find stageIdentifier and variableName, then default to pipeline_identifier.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/32931#-N5KfGar94whqUHncVGJ:-N5KfGar94whqUHncVGK:be6mgq1) ([raw file](https://github.com/harness/harness-core/blob/22bb8d0e95540ea98fd7bc7fcb63a89977a34432/840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java#L72)):*
> ```Java
> 
>   private boolean skipTemplateReference(TemplateEntity templateEntity) {
>     return TemplateEntityType.MONITORED_SERVICE_TEMPLATE.equals(templateEntity.getTemplateEntityType());
> ```

Change to not owned by Pipeline
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java` line 152 at r2](https://reviewable.io/reviews/harness/harness-core/32931#-N5Kf34r9xKERToWUyJT:-N5Kf34r9xKERToWUyJU:b-3aqmgo) ([raw file](https://github.com/harness/harness-core/blob/22bb8d0e95540ea98fd7bc7fcb63a89977a34432/840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java#L152)):*
> ```Java
>    */
>   public List<EntityDetailProtoDTO> getNestedTemplateReferences(String accountId, String orgId, String projectId,
>       TemplateReferenceRequestDTO templateReferenceRequestDTO, boolean shouldModifyFqn) {
> ```

Use String instead of TemplateReferenceRequestDTO templateReferenceRequestDTO
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java` line 270 at r2](https://reviewable.io/reviews/harness/harness-core/32931#-N5Kf-_54r6EC_goirTi:-N5Kf-_54r6EC_goirTj:b-24e4t3) ([raw file](https://github.com/harness/harness-core/blob/22bb8d0e95540ea98fd7bc7fcb63a89977a34432/840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java#L270)):*
> ```Java
>   private EntityDetailProtoDTO getTemplateReference(IdentifierRef identifierRef, String versionLabel, String fqn) {
>     Map<String, String> metadata = new HashMap<>();
>     metadata.put("fqn", fqn);
> ```

Use PreFlightCheckMetadata.FQN 
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 509 at r2](https://reviewable.io/reviews/harness/harness-core/32931#-N5KeesE5K0_Phc3T_xO:-N5KeesE5K0_Phc3T_xP:b-v65xm0) ([raw file](https://github.com/harness/harness-core/blob/22bb8d0e95540ea98fd7bc7fcb63a89977a34432/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L509)):*
> ```Java
>       return "pipelineIdentifier";
>     }
>     return null;
> ```

As we discussed, not required.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32931)* status: 24 file(s) to review. 0 of 1 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java` line 168 at r2](https://reviewable.io/reviews/harness/harness-core/32931#-N5Kfpdb51Y58FiOn-nU:-N5YdQPo6LEk-bYZqbuT:b-o1u52) ([raw file](https://github.com/harness/harness-core/blob/22bb8d0e95540ea98fd7bc7fcb63a89977a34432/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java#L168)):*
> PreFlightCheckMetadata.FQN

**Review by utkarshchoubey-harness — DISMISSED** [review]
:lgtm:

> Reviewed 23 of 23 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32931#-:-N5ZCIW40BS8t4iuEGXy:bnfp4nl)* status: 1 file(s) to review.

**Review by inderschera — COMMENTED** [review]
> Reviewed 21 of 23 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32931)* status: 1 file(s) to review.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 19 of 23 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32931)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/entitysetupusage/resource/EntitySetupUsageResource.java` line 82 at r4](https://reviewable.io/reviews/harness/harness-core/32931#-N5_0lik3OVvnNxoMpVE:-N5_0lik3OVvnNxoMpVF:bp6jcwt) ([raw file](https://github.com/harness/harness-core/blob/ed4dae2a86c793d098afe03cdcaefed682eff91d/120-ng-manager/src/main/java/io/harness/ng/core/entitysetupusage/resource/EntitySetupUsageResource.java#L82)):*
> ```Java
>       @QueryParam(NGResourceFilterConstants.SIZE_KEY) @DefaultValue("100") int size,
>       @NotEmpty @QueryParam(NGCommonEntityConstants.ACCOUNT_KEY) String accountIdentifier,
>       @QueryParam(REFERRED_ENTITY_FQN) String referredEntityFQN,
> ```

nit: merge changes with UI only
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateSetupUsageHelper.java` line 63 at r4](https://reviewable.io/reviews/harness/harness-core/32931#-N5_7apO6TlL8EJECWpt:-N5_7apO6TlL8EJECWpu:b-r3x6xr) ([raw file](https://github.com/harness/harness-core/blob/ed4dae2a86c793d098afe03cdcaefed682eff91d/840-template-service/src/main/java/io/harness/template/helpers/TemplateSetupUsageHelper.java#L63)):*
> ```Java
> 
>   public void publishSetupUsageEvent(TemplateEntity templateEntity, List<EntityDetailProtoDTO> referredEntities) {
>     deleteExistingSetupUsages(templateEntity);
> ```

add comment that before any publish you are deleting all references so that any deleted entity is not still referred,.



_Code quote:_
```Java
deleteExistingSetupUsages(templateEntity);
```
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateSetupUsageHelper.java` line 99 at r4](https://reviewable.io/reviews/harness/harness-core/32931#-N5_7OvPBtc2zPt7ueqR:-N5_7OvPBtc2zPt7ueqS:b-gqsu7q) ([raw file](https://github.com/harness/harness-core/blob/ed4dae2a86c793d098afe03cdcaefed682eff91d/840-template-service/src/main/java/io/harness/template/helpers/TemplateSetupUsageHelper.java#L99)):*
> ```Java
>               .putAllMetadata(ImmutableMap.of("accountId", accountId,
>                   EventsFrameworkMetadataConstants.REFERRED_ENTITY_TYPE, entry.getKey(),
>                   EventsFrameworkMetadataConstants.ACTION, EventsFrameworkMetadataConstants.FLUSH_CREATE_ACTION))
> ```

you dont need this action, jsut use create action
cc: @sahilhindwani-harness we need to do the same in pipeline, PipelineSetupUsageHelper



_Code quote:_
```Java
FLUSH_CREATE_ACTION
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32931)* status: 1 file(s) to review. 1 change requests. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateSetupUsageHelper.java` line 99 at r4](https://reviewable.io/reviews/harness/harness-core/32931#-N5_7OvPBtc2zPt7ueqR:-N5_F2w5DiNK-npOPnoR:b-g8jdd7) ([raw file](https://github.com/harness/harness-core/blob/ed4dae2a86c793d098afe03cdcaefed682eff91d/840-template-service/src/main/java/io/harness/template/helpers/TemplateSetupUsageHelper.java#L99)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

you dont need this action, jsut use create action
cc: @sahilhindwani-harness we need to do the same in pipeline, PipelineSetupUsageHelper
</blockquote></details>

This is still not addressed

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32931)* status: :shipit: complete! ✓

**Review by utkarshchoubey-harness — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32931#-:-N5_IHNAAqfjIxXrt_5q:bnfp4nl)* status: :shipit: complete! ✓

**Review by ashishsanodia-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 19 of 23 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32931)* status: :shipit: complete! ✓

**Comment by utkarshchoubey-harness** [comment]
trigger ti2

**Review by utkarshchoubey-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 21 files at r7, 22 of 22 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32931#-:-N5cih0w92k4fEKmuKxN:bnfp4nl)* status: :shipit: complete! ✓

**Review by arpit3107 — APPROVED** [review]
> Reviewed 1 of 21 files at r7, 22 of 22 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32931)* status: :shipit: complete! ✓

**Pull request merged**
