### PR TITLE
[techdebt]: [CDS-8897]: updating fabric8

### PR DESCRIPTION
**Pull request by tchaurasiya**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31297)

### CODE REVIEW

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Review by piyush-harness — APPROVED** [review]
> Reviewed 30 of 32 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31297)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31297)* status: 8 file(s) to review. 1 change requests. 

___
*[WORKSPACE, line 4624 at r3](https://reviewable.io/reviews/harness/harness-core/31297#-MykYZ9y2Sz1WObAj_Tp:-MykYZA-414wJ9Mh-cwI:b21rr97) ([raw file](https://github.com/harness/harness-core/blob/3acab49a374c834d1e23c63b473c661cd63e94a8/WORKSPACE#L4624)):*
> ```Starlark
>     "io.dropwizard:dropwizard-views:1.3.24",
>     "io.fabric8:fabric8-utils:3.0.11",
>     "io.fabric8:kubernetes-api:3.0.12",
> ```

do we need this now ?



_Code quote:_
```Starlark
"io.fabric8:kubernetes-api:3.0.12",
```

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 22 of 32 files at r1, 2 of 2 files at r2, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31297)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31297)* status: :shipit: complete! ✓

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 29 of 32 files at r1, 2 of 2 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31297)* status: :shipit: complete! ✓

___
*[WORKSPACE, line 4707 at r2](https://reviewable.io/reviews/harness/harness-core/31297#-MygxQ3-2D8Png6bIzk-:-MygxQ306peOFu_Ygu3C:btjjud1) ([raw file](https://github.com/harness/harness-core/blob/4037a88f0c836e9f1824836a0753502e679d8d6f/WORKSPACE#L4707)):*
> ```Starlark
>     "jaxen:jaxen:1.1.6",
>     "joda-time:joda-time:2.10.1",
>     "me.snowdrop:istio-client:1.7.7.1",
> ```

are we still using snowdrop istio somewhere?
___
*[400-rest/src/main/java/software/wings/beans/command/KubernetesSetupCommandUnit.java, line 837 at r2](https://reviewable.io/reviews/harness/harness-core/31297#-Mygyj8S0Crh04Mbc2Fa:-Mygyj8S0Crh04Mbc2Fb:b-n85v3a) ([raw file](https://github.com/harness/harness-core/blob/4037a88f0c836e9f1824836a0753502e679d8d6f/400-rest/src/main/java/software/wings/beans/command/KubernetesSetupCommandUnit.java#L837)):*
> ```Java
>       ExecutionLogCallback executionLogCallback, StringBuilder summaryOutput) {
>     if (setupParams.isUseIstioRouteRule() && service != null) {
>       // Todo : find out generic way of creating istio resource rather than casting them and calli resource specific api
> ```

any progress on this?
___
*[960-api-services/src/main/java/io/harness/k8s/KubernetesHelperService.java, line 296 at r3](https://reviewable.io/reviews/harness/harness-core/31297#-MykZdjq0SSMp31iLCfh:-MykZdjq0SSMp31iLCfi:bmq4lq8) ([raw file](https://github.com/harness/harness-core/blob/3acab49a374c834d1e23c63b473c661cd63e94a8/960-api-services/src/main/java/io/harness/k8s/KubernetesHelperService.java#L296)):*
> ```Java
>       httpClientBuilder.followSslRedirects(true);
>       if (shouldDisableHttp2()) {
>         if (shouldDisableHttp2() && !config.isHttp2Disable()) {
> ```

unnecessary second check of  shouldDisableHttp2, can be one line
and the logic is not clear for me, shouldn't it be shouldDisableHttp2() || config.isHttp2Disable()? Or we're enforcing use of HTTP 1.1?

**Comment by tchaurasiya** [comment]
___
*[WORKSPACE, line 4624 at r3](https://reviewable.io/reviews/harness/harness-core/31297#-MykYZ9y2Sz1WObAj_Tp:-MypPnP80NSuOg_kZx4u:bj2mzaz) ([raw file](https://github.com/harness/harness-core/blob/3acab49a374c834d1e23c63b473c661cd63e94a8/WORKSPACE#L4624)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need this now ?
</blockquote></details>

Yeah, couple of methods we are using fro this one.
ex loadYaml, software.wings.beans.command.KubernetesSetupCommandUnit#createKubernetesControllerDefinition

**Comment by tchaurasiya** [comment]
___
*[WORKSPACE, line 4707 at r2](https://reviewable.io/reviews/harness/harness-core/31297#-MygxQ3-2D8Png6bIzk-:-Mz0lloQ3BwoA3R-dYdw:b-vsqlk1) ([raw file](https://github.com/harness/harness-core/blob/4037a88f0c836e9f1824836a0753502e679d8d6f/WORKSPACE#L4707)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

are we still using snowdrop istio somewhere?
</blockquote></details>

Done.Removed now.

**Comment by tchaurasiya** [comment]
___
*[400-rest/src/main/java/software/wings/beans/command/KubernetesSetupCommandUnit.java, line 837 at r2](https://reviewable.io/reviews/harness/harness-core/31297#-Mygyj8S0Crh04Mbc2Fa:-Mz0ludeDlKPdQOCavTa:b-cmw74m) ([raw file](https://github.com/harness/harness-core/blob/4037a88f0c836e9f1824836a0753502e679d8d6f/400-rest/src/main/java/software/wings/beans/command/KubernetesSetupCommandUnit.java#L837)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

any progress on this?
</blockquote></details>

Haven't found any method, which return genereric type operations now.

**Comment by tchaurasiya** [comment]
___
*[960-api-services/src/main/java/io/harness/k8s/KubernetesHelperService.java, line 296 at r3](https://reviewable.io/reviews/harness/harness-core/31297#-MykZdjq0SSMp31iLCfh:-Mz0oli58GwJL1m7YJcI:b-o9wc7y) ([raw file](https://github.com/harness/harness-core/blob/3acab49a374c834d1e23c63b473c661cd63e94a8/960-api-services/src/main/java/io/harness/k8s/KubernetesHelperService.java#L296)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

unnecessary second check of  shouldDisableHttp2, can be one line
and the logic is not clear for me, shouldn't it be shouldDisableHttp2() || config.isHttp2Disable()? Or we're enforcing use of HTTP 1.1?
</blockquote></details>

Done.refactored.
this code is inherited from mentioned library method.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 11 of 12 files at r4, 2 of 3 files at r5, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31297)* status: :shipit: complete! ✓

**Pull request merged**
