### PR TITLE
feat: [PIE-9166]: add CRUD APIs for git OAuth details of the user

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

Have written Save and get APIs for now, we can add more going forward as and when needed. 

Tested: Verified locally:

Screenshot 2023-03-31 at 2 17 14 PM

Screenshot 2023-03-31 at 2 17 22 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45823)

### CODE REVIEW

**Review by adivishy1 — COMMENTED** [review]
> Reviewed 1 of 36 files at r1, 12 of 19 files at r2, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45823)* status: 37 file(s) to review. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/45823#-NRmOCLF1VYP0MDkdcCE:-NRmOCLF1VYP0MDkdcCF:b-nk4dn6) ([raw file](https://github.com/harness/harness-core/blob/7f60874b854fc975d99eb48ac92c52e6d84c1d63/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L48)):*
> ```Java
>   @Override
>   public List<UserSourceCodeManagerDTO> getByType(String accountIdentifier, String type) {
>     return getUserIdentifier().map(s -> getInternal(accountIdentifier, s, type)).orElse(null);
> ```

lets use meaningful names and have it consistent across, below you have used userID.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/45823#-NRmOmHa5P85jxmocc9A:-NRmOmHa5P85jxmocc9B:b-feleuy) ([raw file](https://github.com/harness/harness-core/blob/7f60874b854fc975d99eb48ac92c52e6d84c1d63/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L72)):*
> ```Java
>       return scmMapBinder.get(sourceCodeManager.getType()).toDTO(sourceCodeManager);
>     }
>     return null;
> ```

return an object instead of null?
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java` line 97 at r3](https://reviewable.io/reviews/harness/harness-core/45823#-NRmMhlqA5kHTHmyYlpd:-NRmMhlqA5kHTHmyYlpe:bsn57dm) ([raw file](https://github.com/harness/harness-core/blob/7f60874b854fc975d99eb48ac92c52e6d84c1d63/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java#L97)):*
> ```Java
>         ApiResponse(description = "Paginated list of Source Code Managers of given account")
>       })
>   public ResponseDTO<List<UserSourceCodeManagerResponseDTO>>
> ```

Can we create a response class and add List<UserSourceCodeManagerResponseDTO>> within, that we it will be extendable in future and we wouldnt need contract changes
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java` line 109 at r3](https://reviewable.io/reviews/harness/harness-core/45823#-NRmMbHTESp8g1hqhr6h:-NRmMbHU6TtMzIT3dxEj:befvkou) ([raw file](https://github.com/harness/harness-core/blob/7f60874b854fc975d99eb48ac92c52e6d84c1d63/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java#L109)):*
> ```Java
>     List<UserSourceCodeManagerResponseDTO> userSourceCodeManagerResponseDTOs =
>         userSourceCodeManagerDTOs.stream()
>             .map(s -> scmMapBinder.get(s.getType()).toResponseDTO(s))
> ```

can we have a meaningful name instead of 's' ?
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/UserSourceCodeManagerService.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/45823#-NRmNhGA3r9FNh06i6kb:-NRmNhGA3r9FNh06i6kc:b-4i3uy7) ([raw file](https://github.com/harness/harness-core/blob/7f60874b854fc975d99eb48ac92c52e6d84c1d63/136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/UserSourceCodeManagerService.java#L23)):*
> ```Java
> 
>   List<UserSourceCodeManagerDTO> get(String accountIdentifier);
> ```

do we need 3 different overloaded, can have only one method and based on the values present do the needful internally?
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/UserSourceCodeManagerService.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/45823#-NRmO3rE0KhPInQYnn6W:-NRmO3rE0KhPInQYnn6X:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/7f60874b854fc975d99eb48ac92c52e6d84c1d63/136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/UserSourceCodeManagerService.java#L28)):*
> ```Java
>   void delete(String accountIdentifier, String userIdentifier);
> 
>   void delete(String accountIdentifier, String userIdentifier, String type);
> ```

same as above

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45823)* status: 37 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/45823#-NRmVVss3ZOrRrWdFdNx:-NRmVVss3ZOrRrWdFdNy:b9qwerm) ([raw file](https://github.com/harness/harness-core/blob/7f60874b854fc975d99eb48ac92c52e6d84c1d63/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L40)):*
> ```Java
>   @Inject UserSourceCodeManagerRepository userSourceCodeManagerRepository;
>   @Inject private Map<SCMType, UserSourceCodeManagerMapper> scmMapBinder;
> ```

Can improve naming here, maybe not include Binder in name.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java` line 97 at r3](https://reviewable.io/reviews/harness/harness-core/45823#-NRmMhlqA5kHTHmyYlpd:-NRmWhMdC9tq8bvWAT8D:b32v57) ([raw file](https://github.com/harness/harness-core/blob/7f60874b854fc975d99eb48ac92c52e6d84c1d63/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java#L97)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Can we create a response class and add List<UserSourceCodeManagerResponseDTO>> within, that we it will be extendable in future and we wouldnt need contract changes
</blockquote></details>

+1
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java` line 109 at r3](https://reviewable.io/reviews/harness/harness-core/45823#-NRmMbHTESp8g1hqhr6h:-NRmWe_w7xPCgs45Ly8a:b32v57) ([raw file](https://github.com/harness/harness-core/blob/7f60874b854fc975d99eb48ac92c52e6d84c1d63/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java#L109)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

can we have a meaningful name instead of 's' ?
</blockquote></details>

+1
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/UserSourceCodeManagerService.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/45823#-NRmNhGA3r9FNh06i6kb:-NRmWpQG332s2lj78-Il:bn14hp) ([raw file](https://github.com/harness/harness-core/blob/7f60874b854fc975d99eb48ac92c52e6d84c1d63/136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/UserSourceCodeManagerService.java#L23)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

do we need 3 different overloaded, can have only one method and based on the values present do the needful internally?
</blockquote></details>

i believe having them separate is better, reflects different parameters can be used for get, else user of the method has to look into the impl to see if he can make get call with/without type or not.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/UserSourceCodeManagerService.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/45823#-NRmO3rE0KhPInQYnn6W:-NRmXF1N8OimXgIcL0Mh:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/7f60874b854fc975d99eb48ac92c52e6d84c1d63/136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/UserSourceCodeManagerService.java#L28)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

same as above

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45823)* status: 37 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/45823#-NRmVVss3ZOrRrWdFdNx:-NRmZmnO2zC3rL62HTBo:byvodve) ([raw file](https://github.com/harness/harness-core/blob/7f60874b854fc975d99eb48ac92c52e6d84c1d63/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L40)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Can improve naming here, maybe not include Binder in name.
</blockquote></details>

this map is actually binding the type of git provider to its mapper
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/45823#-NRmOmHa5P85jxmocc9A:-NRmauIg6Rqi6VMMosuf:b-c9hif9) ([raw file](https://github.com/harness/harness-core/blob/7f60874b854fc975d99eb48ac92c52e6d84c1d63/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L72)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

return an object instead of null?
</blockquote></details>

should we throw an exception in this case as here, it couldn't be saved because userPrincipal could not be found?
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/UserSourceCodeManagerService.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/45823#-NRmNhGA3r9FNh06i6kb:-NRmbYOpCne4yDEHYSn-:b7kzo67) ([raw file](https://github.com/harness/harness-core/blob/7f60874b854fc975d99eb48ac92c52e6d84c1d63/136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/UserSourceCodeManagerService.java#L23)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

i believe having them separate is better, reflects different parameters can be used for get, else user of the method has to look into the impl to see if he can make get call with/without type or not.
</blockquote></details>

i think yes, we can actually remove the methods with userIdentifier, because ui will never send it in the request and will need to be calculated from principal only, and for other two we can have just one method

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/UserSourceCodeManagerResponseDTOsList.java` line 20 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmq3P0EQHI0qQBq--j:-NRmq3P0EQHI0qQBq--k:boasksc) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/UserSourceCodeManagerResponseDTOsList.java#L20)):*
> ```Java
> @Builder
> @OwnedBy(HarnessTeam.PIPELINE)
> public class UserSourceCodeManagerResponseDTOsList {
> ```

nit: When its "List" then we don't need to say "ResponseDTOs". We can either say "ResponseDTOList" or "ResponseDTOs"

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 88 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmquXvBhydDmcNfAGK:-NRmquXvBhydDmcNfAGL:b-fdqetq) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L88)):*
> ```Java
>   }
> 
>   private Optional<String> getUserIdentifier() {
> ```

why are we taking user identifier from principal?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 50 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmr8tw1bm16vestBQk:-NRmr8tw1bm16vestBQl:b-ua3whz) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L50)):*
> ```Java
>     Optional<String> userIdentifier = getUserIdentifier();
>     if (userIdentifier.isPresent()) {
>       UserSourceCodeManager sourceCodeManager;
> ```

naming isn't appropriate. Its confusing with the argument.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 54 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmsBvO03ED_Oe5Q8Xs:-NRmsBvO03ED_Oe5Q8Xt:b-jefanr) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L54)):*
> ```Java
>       try {
>         sourceCodeManager = userSourceCodeManagerRepository.save(
>             scmMapBinder.get(userSourceCodeManager.getType()).toEntity(userSourceCodeManager));
> ```

I feel there should be a helper that should do all this internally. It should just take dto as argument and return its entity and vice versa. Map binder should also be part of the helper and not directly injected in service.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmsg9o7KB0KPVuULJD:-NRmsg9o7KB0KPVuULJE:bk09rkj) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L81)):*
> ```Java
>   public void delete(String accountIdentifier, String userIdentifier, String type) {
>     if (type == null) {
>       userSourceCodeManagerRepository.deleteByAccountIdentifierAndUserIdentifier(accountIdentifier, userIdentifier);
> ```

I think delete operation returns the count of elements deleted. We should return the same instead of void. That can be informative in cases where we delete multiple scms.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/repositories/userSourceCodeManager/UserSourceCodeManagerRepository.java` line 21 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmtMidD1yg14m_GkK-:-NRmtMidD1yg14m_GkK0:b-nc0j24) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/136-git-sync-manager/src/main/java/io/harness/repositories/userSourceCodeManager/UserSourceCodeManagerRepository.java#L21)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public interface UserSourceCodeManagerRepository extends PagingAndSortingRepository<UserSourceCodeManager, String> {
>   List<UserSourceCodeManager> findByAccountIdentifierAndUserIdentifier(String userIdentifier, String accountIdentifier);
> ```

this method is wrong. I'm not sure if its tested. arguments order should be reversed.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/repositories/userSourceCodeManager/UserSourceCodeManagerRepository.java` line 22 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmtSQR1gNSzmRbPgh3:-NRmtSQR1gNSzmRbPgh4:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/136-git-sync-manager/src/main/java/io/harness/repositories/userSourceCodeManager/UserSourceCodeManagerRepository.java#L22)):*
> ```Java
> public interface UserSourceCodeManagerRepository extends PagingAndSortingRepository<UserSourceCodeManager, String> {
>   List<UserSourceCodeManager> findByAccountIdentifierAndUserIdentifier(String userIdentifier, String accountIdentifier);
>   List<UserSourceCodeManager> findByAccountIdentifierAndUserIdentifierAndType(
> ```

same here

**Comment by mohitg0795** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 699 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmteGOD8S16ZIe-WBp:-NRmteGOD8S16ZIe-WBq:b-nhuh2e) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L699)):*
> ```Java
>   BAMBOO_BUILD("Bamboo Build Step", HarnessTeam.CDC),
>   CDS_AWS_BACKOFF_STRATEGY("Enable AWS SDK Client Backoff Strategy", HarnessTeam.CDP),
>   INTEGRATE_OAUTH_WITH_GITX("Use users' oauth creds to fetch and commit in git", HarnessTeam.PIPELINE);
> ```

I think we need to add "PIE" prefix. Also, lets keep it simple : GITX_OAUTH. Its easier to communicate everytime.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45823)* status: 38 file(s) to review. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 50 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmr8tw1bm16vestBQk:-NRn7hHZDjvd1K76JGtN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L50)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

naming isn't appropriate. Its confusing with the argument.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 54 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmsBvO03ED_Oe5Q8Xs:-NRnB2Ph6i5GenVXX4Yb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L54)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I feel there should be a helper that should do all this internally. It should just take dto as argument and return its entity and vice versa. Map binder should also be part of the helper and not directly injected in service.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmsg9o7KB0KPVuULJD:-NRn8GTM16Vbv5f0-O86:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L81)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think delete operation returns the count of elements deleted. We should return the same instead of void. That can be informative in cases where we delete multiple scms.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 88 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmquXvBhydDmcNfAGK:-NRn8qbn3HCBSp5d2rC7:b-hbo1lu) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L88)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why are we taking user identifier from principal?
</blockquote></details>

here user identifier is actually the id of the user in the users collection in DB, which can come from the principal. and principal in context will be of the one who hit the API so, we'll get the correct userID.
___
*[`136-git-sync-manager/src/main/java/io/harness/repositories/userSourceCodeManager/UserSourceCodeManagerRepository.java` line 21 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmtMidD1yg14m_GkK-:-NRn8QbzB8pNoqwjfiwH:bt6a4zk) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/136-git-sync-manager/src/main/java/io/harness/repositories/userSourceCodeManager/UserSourceCodeManagerRepository.java#L21)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this method is wrong. I'm not sure if its tested. arguments order should be reversed.
</blockquote></details>

it's tested and it worked because the sender is sending in the correct order, I just mistakenly missed updating here. Done now
___
*[`136-git-sync-manager/src/main/java/io/harness/repositories/userSourceCodeManager/UserSourceCodeManagerRepository.java` line 22 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmtSQR1gNSzmRbPgh3:-NRn8eal0vLiEnrkZMkE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/136-git-sync-manager/src/main/java/io/harness/repositories/userSourceCodeManager/UserSourceCodeManagerRepository.java#L22)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/repositories/userSourceCodeManager/UserSourceCodeManagerRepository.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmtUQE9NBXAhfyUllg:-NRn8euV-vvwQeaNFVfL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/136-git-sync-manager/src/main/java/io/harness/repositories/userSourceCodeManager/UserSourceCodeManagerRepository.java#L24)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same in all actually.

Always remember account id will be the first parameter as its the highest governing param everywhere.
</blockquote></details>

Done.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 699 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmteGOD8S16ZIe-WBp:-NRn8mDz8RMNKKlOZH0D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L699)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we need to add "PIE" prefix. Also, lets keep it simple : GITX_OAUTH. Its easier to communicate everytime.
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 88 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmquXvBhydDmcNfAGK:-NRqVzDg796wwrfz60MD:b-a961d0) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L88)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

here user identifier is actually the id of the user in the users collection in DB, which can come from the principal. and principal in context will be of the one who hit the API so, we'll get the correct userID.
</blockquote></details>

No, why would it come from principal? It should be passed as an argument. Any interface should basically say on what account and user id the action it supposed to happen.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45823)* status: 39 file(s) to review. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 88 at r4](https://reviewable.io/reviews/harness/harness-core/45823#-NRmquXvBhydDmcNfAGK:-NRqjB1K2qNiexTDJZGD:b11wn7l) ([raw file](https://github.com/harness/harness-core/blob/ceb1bac1e842b69b43a4f716ce05844f5cd0a890/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L88)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

No, why would it come from principal? It should be passed as an argument. Any interface should basically say on what account and user id the action it supposed to happen.
</blockquote></details>

done as discussed offline.

**Review by senjucanon2 — COMMENTED** [review]
> Reviewed 12 of 19 files at r2, 17 of 21 files at r3, 4 of 7 files at r5, 4 of 6 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45823)* status: 10 file(s) to review. 9. unresolved discussions. 0 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 34 at r8](https://reviewable.io/reviews/harness/harness-core/45823#-NRrWb_M82ZhJM86_wCR:-NRrWb_M82ZhJM86_wCS:b-prs2cm) ([raw file](https://github.com/harness/harness-core/blob/675bf9b6de98871144843d344dce9f87d3f9d501/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L34)):*
> ```Java
> @AllArgsConstructor
> public class UserSourceCodeManagerServiceImpl implements UserSourceCodeManagerService {
>   @Inject UserSourceCodeManagerRepository userSourceCodeManagerRepository;
> ```

all args can be made private here, some are private and some protected right now.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 39 at r8](https://reviewable.io/reviews/harness/harness-core/45823#-NRrWitCAe9J6gjXvUhB:-NRrWitCAe9J6gjXvUhC:b-dzanzl) ([raw file](https://github.com/harness/harness-core/blob/675bf9b6de98871144843d344dce9f87d3f9d501/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L39)):*
> ```Java
>   @Override
>   public List<UserSourceCodeManagerDTO> getByType(String accountIdentifier, String userIdentifier, String type) {
>     return getInternal(accountIdentifier, userIdentifier, type);
> ```

why do we need "getInternal" method here?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45823)* status: 10 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 34 at r8](https://reviewable.io/reviews/harness/harness-core/45823#-NRrWb_M82ZhJM86_wCR:-NRrXe2Z3klOEWz1NH7W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/675bf9b6de98871144843d344dce9f87d3f9d501/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L34)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

all args can be made private here, some are private and some protected right now.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java` line 39 at r8](https://reviewable.io/reviews/harness/harness-core/45823#-NRrWitCAe9J6gjXvUhB:-NRrXjW_0qhObpM8h_Tx:b-rlfolt) ([raw file](https://github.com/harness/harness-core/blob/675bf9b6de98871144843d344dce9f87d3f9d501/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/UserSourceCodeManagerServiceImpl.java#L39)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why do we need "getInternal" method here?
</blockquote></details>

add it earlier because we get multiple get methods, we can remove now.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 12 of 19 files at r2, 17 of 21 files at r3, 3 of 7 files at r5, 4 of 6 files at r6, 1 of 1 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45823)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Pull request merged**
