### PR TITLE
feat: [PL-31602]: k8s ng task module

### PR DESCRIPTION
**Pull request by xingchi-jin**
## Describe your changes
K8s ng task module for 2 handlers K8sApplyRequestHandler and K8sRollingRequestHandler
Including docker file that can build the container with required tools.

Next steps after this PR
1. The goal of k8s task small build target becomes more clear, it is to create the small build target for folder 930-delegate-tasks/src/main/java/io/harness/apps/k8s/application 
2. Minimize kryo registars 
3. Create base docker file, and let k8s docker file inherit from the base 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44329)

### CODE REVIEW

**Review by mdmilic — APPROVED** [review]
> Reviewed 11 of 15 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44329)* status: 15 file(s) to review. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/apps/k8s/dockerization/Dockerfile-task` line 8 at r2](https://reviewable.io/reviews/harness/harness-core/44329#-NP24tMx9Sn8dKMEJdhY:-NP24tMx9Sn8dKMEJdhZ:bgpy0v) ([raw file](https://github.com/harness/harness-core/blob/75d25d8d13a13dd0bddb107d4877e59808eb263c/930-delegate-tasks/src/main/java/io/harness/apps/k8s/dockerization/Dockerfile-task#L8)):*
> ```
> #       TARGETARCH: amd64, arm64
> 
> FROM redhat/ubi8-minimal:8.4
> ```

Use later UBI minimal version (e.g. 8.7 I think is latest now)
___
*[`930-delegate-tasks/src/main/java/io/harness/apps/k8s/dockerization/Dockerfile-task` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/44329#-NP2CQJVAD-5vsK1LWue:-NP2CQJVAD-5vsK1LWuf:b-pqo974) ([raw file](https://github.com/harness/harness-core/blob/75d25d8d13a13dd0bddb107d4877e59808eb263c/930-delegate-tasks/src/main/java/io/harness/apps/k8s/dockerization/Dockerfile-task#L34)):*
> ```
> 
> RUN mkdir -m 777 -p client-tools/kubectl/v1.13.2 \
>     && curl -s -L -o client-tools/kubectl/v1.13.2/kubectl https://app.harness.io/public/shared/tools/kubectl/release/v1.13.2/bin/linux/$TARGETARCH/kubectl \
> ```

upgrade to 1.24.3, that's what delegate currently uses.
___
*[`930-delegate-tasks/src/main/java/io/harness/apps/k8s/dockerization/Dockerfile-task` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/44329#-NP2CIJHBL91lLu0sQck:-NP2CIJI9pOWI02hGwHx:b-1vohvb) ([raw file](https://github.com/harness/harness-core/blob/75d25d8d13a13dd0bddb107d4877e59808eb263c/930-delegate-tasks/src/main/java/io/harness/apps/k8s/dockerization/Dockerfile-task#L36)):*
> ```
>     && curl -s -L -o client-tools/kubectl/v1.13.2/kubectl https://app.harness.io/public/shared/tools/kubectl/release/v1.13.2/bin/linux/$TARGETARCH/kubectl \
>     && mkdir -m 777 -p client-tools/go-template/v0.4 \
>     && curl -s -L -o client-tools/go-template/v0.4/go-template https://app.harness.io/public/shared/tools/go-template/release/v0.4/bin/linux/$TARGETARCH/go-template \
> ```

Lets stick only with v0.4, that's what delegate currently uses.
___
*[`930-delegate-tasks/src/main/java/io/harness/apps/k8s/dockerization/Dockerfile-task` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/44329#-NP24axo4WY6rcLfyx_y:-NP24axo4WY6rcLfyx_z:b-gtvv1q) ([raw file](https://github.com/harness/harness-core/blob/75d25d8d13a13dd0bddb107d4877e59808eb263c/930-delegate-tasks/src/main/java/io/harness/apps/k8s/dockerization/Dockerfile-task#L40)):*
> ```
>     && curl -s -L -o client-tools/go-template/v0.4.1/go-template https://app.harness.io/public/shared/tools/go-template/release/v0.4.1/bin/linux/$TARGETARCH/go-template
> 
> RUN chmod -R 755 /opt/harness \
> ```

You should always try to combine these RUN commands as much as possible. That will reduce the final image size (I know it sounds weird). Of course only if they are consecutive, The order of Dockerfile commands should always be least frequently changing to most frequently changing to better utilize image layer cache (each command is one layer). 
___
*[`930-delegate-tasks/src/main/java/io/harness/apps/k8s/dockerization/taskfile` line 0 at r2](https://reviewable.io/reviews/harness/harness-core/44329#-NP2CbWH8Twli9tQ6_vp:-NP2CbWH8Twli9tQ6_vq:bnyrk5s) ([raw file](https://github.com/harness/harness-core/blob/75d25d8d13a13dd0bddb107d4877e59808eb263c/930-delegate-tasks/src/main/java/io/harness/apps/k8s/dockerization/taskfile#L0)):*
Is this some test file?
___
*[`930-delegate-tasks/src/main/java/io/harness/apps/k8s/dockerization/scripts/start.sh` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/44329#-NP2E44zCEBkfo_2IE2m:-NP2E44zCEBkfo_2IE2n:b8buf5g) ([raw file](https://github.com/harness/harness-core/blob/75d25d8d13a13dd0bddb107d4877e59808eb263c/930-delegate-tasks/src/main/java/io/harness/apps/k8s/dockerization/scripts/start.sh#L24)):*
> ```Shell
> 
> # 1. Start the delegate
> JAVA_OPTS=${JAVA_OPTS//UseCGroupMemoryLimitForHeap/UseContainerSupport}
> ```

This line was to support upgrade from JDK8-11 (for people who specified JAVA_OPTS prior to upgrade). It's not needed here, it is used to replace JDK8 variable with JDK11 alternative.

**Review by mdmilic — APPROVED** [review]
I don't want to block the PR, non of the changes are urgent. You can take a look, respond here what makes sense to do and create a followup ticket to do it. 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44329#-:-NP2FDzs5js70wHj4Iit:b7clo5d)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Comment by xingchi-jin** [comment]
@mdmilic i will address your comments in this task altogether https://harness.atlassian.net/browse/PL-31606
Thank you, these are good comments

**Comment by xingchi-jin** [comment]
> @mdmilic i will address your comments in this task altogether https://harness.atlassian.net/browse/PL-31606 Thank you, these are good comments

NVM, addressed in this PR

**Review by Raghav-Murali — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 3 files at r3, 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44329)* status: 19 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44329)* status: 19 file(s) to review. Waiting on team(s): del-team. 

___
*[`delegate/src/main/java/io/harness/taskapps/k8s/dockerization/build_bazel_k8stask.sh` line 10 at r4](https://reviewable.io/reviews/harness/harness-core/44329#-NPYxEk_AXKs_bTOXG8H:-NPYxEk_AXKs_bTOXG8I:brawdnw) ([raw file](https://github.com/harness/harness-core/blob/a6f9bc2122adcacb4aa8da4e81684e0fe8c22bee/delegate/src/main/java/io/harness/taskapps/k8s/dockerization/build_bazel_k8stask.sh#L10)):*
> ```Shell
> 
> # This script is to build only the delegate.jar for delegate build pipeline. It doesn't build any other services
> # Check bazel_scripts.sh which builds all jars including delegate.jar if needed.
> ```

nit: update the comment?



_Code quote:_
```Shell
# This script is to build only the delegate.jar for delegate build pipeline. It doesn't build any other services
# Check bazel_scripts.sh which builds all jars including delegate.jar if needed.
```
___
*[`delegate/src/main/java/io/harness/taskapps/k8s/dockerization/scripts/start.sh` line 13 at r4](https://reviewable.io/reviews/harness/harness-core/44329#-NPYy3Qz1bn7djFfJrbB:-NPYy3Qz1bn7djFfJrbC:brslk5c) ([raw file](https://github.com/harness/harness-core/blob/a6f9bc2122adcacb4aa8da4e81684e0fe8c22bee/delegate/src/main/java/io/harness/taskapps/k8s/dockerization/scripts/start.sh#L13)):*
> ```Shell
>     echo "$CONFIG_KEY: $CONFIG_VALUE" >> config.yml
>   fi
> }
> ```

nit: is this function used?



_Code quote:_
```Shell
function append_config() {
  CONFIG_KEY=$1
  CONFIG_VALUE=$2
  if [ -n "$CONFIG_VALUE" ] ; then
    echo "$CONFIG_KEY: $CONFIG_VALUE" >> config.yml
  fi
}
```

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 16 of 18 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44329)* status: Some of the checks are too old. 2 file(s) to review. 1 of 2 approvals obtained.

**Review by gn-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 3 files at r3, 16 of 18 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44329)* status: Some of the checks are too old.

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44329)* status: 1 file(s) to review.

**Review by xingchi-jin — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 3 files at r3, 15 of 18 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44329)* status: 1 file(s) to review.

**Review by gn-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44329)* status: :shipit: complete! ✓

**Pull request merged**
