### PR TITLE
feat: [IDP-1482]: API support for Scorecard & Check Stats page

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54957)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 47 of 47 files at r1, 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54957)* status: 48 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 2444 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZFzMC8MKKU5nU7MRZ:-NiZFzMC8MKKU5nU7MR_:b-12x7yz) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/contracts/openapi/v1/openapi.yaml#L2444)):*
> ```YAML
>                   id: nl4f2bigcjdmv
>                 type: string
>             stats:
> ```

Should this be passPercentage or something similar?



_Code quote:_
```YAML
stats
```
___
*[`idp-service/src/main/java/io/harness/idp/migration/AddCheckIdentifierMigration.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZDJGS2Minb_o2LDGo:-NiZDJGS2Minb_o2LDGp:bxafcjr) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/src/main/java/io/harness/idp/migration/AddCheckIdentifierMigration.java#L21)):*
> ```Java
> @OwnedBy(HarnessTeam.IDP)
> public class AddCheckIdentifierMigration implements NGMigration {
>   @Inject ScoreService scoreService;
> ```

When do these migrations run? Is the IDP guice injector created before that and ScoreService already available?



_Code quote:_
```Java
@Inject ScoreService scoreService;
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/checks/entity/CheckStatusEntity.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZEgxc5CFJTcvl72hP:-NiZEgxc5CFJTcvl72hQ:b-x7wlxe) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/src/main/java/io/harness/idp/scorecard/checks/entity/CheckStatusEntity.java#L46)):*
> ```Java
> @OwnedBy(HarnessTeam.IDP)
> public class CheckStatusEntity implements PersistentEntity, CreatedByAware, CreatedAtAware {
>   public static final long TTL_MONTHS = 6;
> ```

So we don't need data older than 6 months? What if there's a long running migration in a company that's tracked by this check? Like if a company is migrating from Java 11 to 17 from 7-8 months?



_Code quote:_
```Java
TTL_MONTHS = 6
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/checks/mappers/CheckMapper.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZF9u_-RAQxEMdbbBj:-NiZF9u_-RAQxEMdbbBk:b4wp41h) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/src/main/java/io/harness/idp/scorecard/checks/mappers/CheckMapper.java#L29)):*
> ```Java
> @UtilityClass
> public class CheckMapper {
>   public CheckListItem toDTO(CheckEntity checkEntity, Map<String, CheckStatusEntity> checkStatusEntityMap) {
> ```

How about passing just the required CheckStatusEntity instead?



_Code quote:_
```Java
CheckStatusEntity
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/checks/repositories/CheckStatusRepository.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZLjkw5zRGFDbqBICe:-NiZLjkw5zRGFDbqBICf:b-1z72lc) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/src/main/java/io/harness/idp/scorecard/checks/repositories/CheckStatusRepository.java#L21)):*
> ```Java
> @OwnedBy(HarnessTeam.IDP)
> public interface CheckStatusRepository extends CrudRepository<CheckStatusEntity, String>, CheckStatusRepositoryCustom {
>   List<CheckStatusEntity> findByAccountIdentifierAndIdentifierAndCustom(
> ```

Is this method call applicable for default checks? If so, we might have to add global account and change this to accountIdentifierIn call



_Code quote:_
```Java
findByAccountIdentifierAndIdentifierAndCustom
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/checks/resources/ChecksApiImpl.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZhb96C7kKH_97-Mob:-NiZhb96C7kKH_97-Moc:bwu2xvv) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/src/main/java/io/harness/idp/scorecard/checks/resources/ChecksApiImpl.java#L119)):*
> ```Java
>   public Response getCheckStats(String checkId, String harnessAccount, Boolean isCustom) {
>     try {
>       List<CheckStats> checkStats = checkService.getCheckStats(harnessAccount, checkId, isCustom);
> ```

Default check will be in global account. How are we storing stats for them per account? :thinking: 



_Code quote:_
```Java
getCheckStats
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scores/jobs/CheckStatusDailyRunJob.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZCYI69mFuYCQxwBGS:-NiZCYI69mFuYCQxwBGT:b-ihm3c4) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/src/main/java/io/harness/idp/scorecard/scores/jobs/CheckStatusDailyRunJob.java#L35)):*
> ```Java
> public class CheckStatusDailyRunJob implements Managed {
>   private ScheduledExecutorService executorService;
>   private CheckService checkService;
> ```

nit: final



_Code quote:_
```Java
checkService
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scores/repositories/ScoreRepositoryCustomImpl.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZnwlv8Y1AmmmUeOHc:-NiZnwlv8Y1AmmmUeOHd:b-io0vte) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/src/main/java/io/harness/idp/scorecard/scores/repositories/ScoreRepositoryCustomImpl.java#L76)):*
> ```Java
>         Aggregation.project()
>             .andExpression(Constants.ID_KEY)
>             .as(Constants.SCORECARD_IDENTIFIER_KEY)
> ```

nit: could we use ScoreKeys.scorecardIdentifier?



_Code quote:_
```Java
Constants.SCORECARD_IDENTIFIER_KEY
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scores/repositories/Scores.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZjrvpBPYx22_QwovL:-NiZjrvqEenzzVl5o0o_:b-g369w3) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/src/main/java/io/harness/idp/scorecard/scores/repositories/Scores.java#L19)):*
> ```Java
> @Builder
> @OwnedBy(HarnessTeam.IDP)
> public class Scores {
> ```

Do we need this wrapper? Can't the group by query results be taken in ScoreEntity?



_Code quote:_
```Java
Scores
```

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54957)* status: 48 file(s) to review. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 2444 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZFzMC8MKKU5nU7MRZ:-Ni_-YqlCsSu8Hnqe0K6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/contracts/openapi/v1/openapi.yaml#L2444)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Should this be passPercentage or something similar?
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/migration/AddCheckIdentifierMigration.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZDJGS2Minb_o2LDGo:-Ni_-CFa0QVnRTc779CF:b-cftnd9) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/src/main/java/io/harness/idp/migration/AddCheckIdentifierMigration.java#L21)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

When do these migrations run? Is the IDP guice injector created before that and ScoreService already available?
</blockquote></details>

yes, ScoreService will be initialised before itself. I was also able to run this migration successfully in local
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/checks/entity/CheckStatusEntity.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZEgxc5CFJTcvl72hP:-Ni_-kfFA2-RFgxz79-t:b7dxar) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/src/main/java/io/harness/idp/scorecard/checks/entity/CheckStatusEntity.java#L46)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

So we don't need data older than 6 months? What if there's a long running migration in a company that's tracked by this check? Like if a company is migrating from Java 11 to 17 from 7-8 months?
</blockquote></details>

yes, in that case we need to keep the data for a longer time. Should we keep it more than 6 months?
But currently in UI we will be showing stats for each day (according to mocks). 
Graph will look clumsy if we display more data right? 
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/checks/mappers/CheckMapper.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZF9u_-RAQxEMdbbBj:-Ni_1dcmCpmbsQHTAg5J:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/src/main/java/io/harness/idp/scorecard/checks/mappers/CheckMapper.java#L29)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

How about passing just the required CheckStatusEntity instead?
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/checks/repositories/CheckStatusRepository.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZLjkw5zRGFDbqBICe:-Ni_1vZ-0Plpy1cvuQPv:b-2fvc0m) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/src/main/java/io/harness/idp/scorecard/checks/repositories/CheckStatusRepository.java#L21)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Is this method call applicable for default checks? If so, we might have to add global account and change this to accountIdentifierIn call
</blockquote></details>

We are not storing __GLOBAL_ACCOUNT_ID__ in CheckStatusEntity as default checks are common across accounts. We will be storing entity similar to below snippet and we can uniquely identify each document with combination of accountIdentifier_identifier_custom



_Code snippet:_
```Java
{
    "_id" : ObjectId("6545ea9a06d57706adb5df8e"),
    "accountIdentifier" : "kmpySmUISimoRrJL6NL73w",
    "identifier" : "__HARNESS__1e7a1199-4362-710c-afb7-01a45283d768",
    "name" : "Open code scanning critical alerts is less than 3",
    "isCustom" : false,
    "passCount" : NumberInt(2),
    "total" : NumberInt(3),
    "timestamp" : NumberLong(1699080858680),
    "validUntil" : ISODate("2024-05-04T06:54:18.680+0000"),
    "createdAt" : NumberLong(1699080858732),
    "_class" : "io.harness.idp.scorecard.checks.entity.CheckStatusEntity"
}
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/checks/resources/ChecksApiImpl.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZhb96C7kKH_97-Mob:-Ni_2lHO47EQt-hpcoqZ:b-ksrqy3) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/src/main/java/io/harness/idp/scorecard/checks/resources/ChecksApiImpl.java#L119)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Default check will be in global account. How are we storing stats for them per account? :thinking:
</blockquote></details>

yes, we are storing stats per account as default checks are common across accounts and we will be showing same default check calculation for all the accounts.
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scores/jobs/CheckStatusDailyRunJob.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZCYI69mFuYCQxwBGS:-Ni_3OYW9OcrYkgvaO2o:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/src/main/java/io/harness/idp/scorecard/scores/jobs/CheckStatusDailyRunJob.java#L35)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

nit: final
</blockquote></details>

Done
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scores/repositories/Scores.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/54957#-NiZjrvpBPYx22_QwovL:-Ni_3ujh4y0oFzoL30ls:b-155hrz) ([raw file](https://github.com/harness/harness-core/blob/9fa79f1afd2fcb76b2e5424339d4621b101342c3/idp-service/src/main/java/io/harness/idp/scorecard/scores/repositories/Scores.java#L19)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Do we need this wrapper? Can't the group by query results be taken in ScoreEntity?
</blockquote></details>

I have changed the structure of this object. Please check once

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 3 of 11 files at r2, 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54957)* status: 48 file(s) to review. 1 of 2 approvals obtained.

**Review by mankrit-singh — APPROVED** [review]

**Comment by vigneswara-propelo** [comment]
trigger review

**Comment by vigneswara-propelo** [comment]
trigger checkstyle, pmd

**Review by arya-harness — APPROVED** [review]

**Pull request merged**
