### PR TITLE
feat: [PL-28166]: added setup usage for git connector

### PR DESCRIPTION
**Pull request by bhavya181**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37538)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37538)

**Review by archit-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37538)* status: Some of the checks are too old. 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/filter/creation/FilterCreatorMergeService.java` line 272 at r1](https://reviewable.io/reviews/harness/harness-core/37538#-NCPCQ4y6SCRv9CPoVBI:-NCPCQ4y6SCRv9CPoVBJ:b-j8yxxd) ([raw file](https://github.com/harness/harness-core/blob/861d98b72453be5d5a9f2de0aad48a9266ad067c/pipeline-service/service/src/main/java/io/harness/pms/filter/creation/FilterCreatorMergeService.java#L272)):*
> ```Java
>     GitAwareContextHelper.initDefaultScmGitMetaData();
>     GitEntityInfo gitEntityInfo = GitContextHelper.getGitEntityInfo();
>     if (gitEntityInfo != null && StoreType.REMOTE.equals(gitEntityInfo.getStoreType())
> ```

why don't we simply check if pipelineEntity.getStoreType() is REMOTE?

Also, lets move the complete if logic for checking if its a valid remote entity into a private method for clarity.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/filter/creation/FilterCreatorMergeService.java` line 276 at r1](https://reviewable.io/reviews/harness/harness-core/37538#-NCPDfG68mBslYZfdWOB:-NCPDfG68mBslYZfdWOC:b-opzz69) ([raw file](https://github.com/harness/harness-core/blob/861d98b72453be5d5a9f2de0aad48a9266ad067c/pipeline-service/service/src/main/java/io/harness/pms/filter/creation/FilterCreatorMergeService.java#L276)):*
> ```Java
>             pipelineEntity.getOrgIdentifier(), pipelineEntity.getProjectIdentifier())) {
>       IdentifierRef identifierRef =
>           IdentifierRefHelper.getIdentifierRef(gitEntityInfo.getConnectorRef(), pipelineEntity.getAccountIdentifier(),
> ```

same here, can't we use connectorRef from pipelineEntity?

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37538)* status: Some of the checks are too old.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37538)* status: Some of the checks are too old. 2. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/filter/creation/FilterCreatorMergeService.java` line 272 at r1](https://reviewable.io/reviews/harness/harness-core/37538#-NCPCQ4y6SCRv9CPoVBI:-NCPfjXr6LCo9Sbt8K6D:b6ou0ga) ([raw file](https://github.com/harness/harness-core/blob/861d98b72453be5d5a9f2de0aad48a9266ad067c/pipeline-service/service/src/main/java/io/harness/pms/filter/creation/FilterCreatorMergeService.java#L272)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why don't we simply check if pipelineEntity.getStoreType() is REMOTE?

Also, lets move the complete if logic for checking if its a valid remote entity into a private method for clarity.
</blockquote></details>

pipeline entity does not have git details in it, In flow pipeline entity got updated with git details later on, so, we have to find it via GitContextThreadOnly
___
*[`pipeline-service/service/src/main/java/io/harness/pms/filter/creation/FilterCreatorMergeService.java` line 276 at r1](https://reviewable.io/reviews/harness/harness-core/37538#-NCPDfG68mBslYZfdWOB:-NCPg8f39miYf1TZwcv3:bnj7hli) ([raw file](https://github.com/harness/harness-core/blob/861d98b72453be5d5a9f2de0aad48a9266ad067c/pipeline-service/service/src/main/java/io/harness/pms/filter/creation/FilterCreatorMergeService.java#L276)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same here, can't we use connectorRef from pipelineEntity?
</blockquote></details>

same as abovw

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37538)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by bhavya181** [comment]
trigger ti2

**Review by namanvermah — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37538)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37538)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37538)* status: :shipit: complete! ✓

**Pull request merged**
