### PR TITLE
feat: [CDS-39012] Terraform backend configuration file path - NG

### PR DESCRIPTION
**Pull request by jelenaHarness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36875)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* Code issue 7 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36875)

**Comment by jelenaHarness** [comment]
trigger publish-delegate

**Comment by jelenaHarness** [comment]
trigger feature-build

**Comment by jelenaHarness** [comment]
trigger feature-build

**Comment by jelenaHarness** [comment]
trigger feature-build

**Comment by jelenaHarness** [comment]
trigger feature-build

**Comment by jelenaHarness** [comment]
trigger feature-build

**Comment by jelenaHarness** [comment]
trigger feature-build

**Comment by jelenaHarness** [comment]
trigger feature-build

**Comment by jelenaHarness** [comment]
trigger feature-build

**Comment by jelenaHarness** [comment]
trigger feature-build

**Comment by alebuh** [comment]
trigger ti4

**Comment by alebuh** [comment]
trigger feature-build

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 3 of 24 files at r1, 5 of 22 files at r2, 3 of 15 files at r3, 13 of 73 files at r5, 20 of 30 files at r7, 25 of 35 files at r9, 11 of 21 files at r10, 4 of 8 files at r12, 3 of 12 files at r15, 4 of 15 files at r17, 11 of 11 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36875)* status: :shipit: complete! ✓

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36875)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 397 at r18](https://reviewable.io/reviews/harness/harness-core/36875#-NGQXfEo9_XgEtwVGYNa:-NGQXfEo9_XgEtwVGYNb:b-rfb8go) ([raw file](https://github.com/harness/harness-core/blob/5e8e93debb9ecef1f12c95ecdaafbc0ff0ed44e7/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L397)):*
> ```Java
>   SPOT_TASK_NG(TaskGroup.SPOTINST, "Spot NG Task"),
>   FETCH_INSTANCE_SCRIPT_TASK_NG(TaskGroup.CUSTOM_DEPLOYMENT_NG, "Fetch Instance Script Task"),
>   AZURE_WEB_APP_TASK_NG_V2(TaskGroup.AZURE, "Azure Web App Task V2", true),
> ```

unintentional change?

**Review by alebuh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36875)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 397 at r18](https://reviewable.io/reviews/harness/harness-core/36875#-NGQXfEo9_XgEtwVGYNa:-NGQdU38CWlTussnLupl:bdev9as) ([raw file](https://github.com/harness/harness-core/blob/5e8e93debb9ecef1f12c95ecdaafbc0ff0ed44e7/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L397)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

unintentional change?
</blockquote></details>

I think that change has been picked up with rebasing. And it should be false right? As false is currently on the develop https://github.com/harness/harness-core/blob/e25527137113f4dc08df1d5d416d51335c06a786/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java



_Code quote:_
```Java
AZURE_WEB_APP_TASK_NG_V2
```

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 1 of 11 files at r20.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36875)* status: :shipit: complete! ✓

**Comment by alebuh** [comment]
trigger ti3

**Review by abosii-harness — APPROVED** [review]
> Reviewed 3 of 24 files at r1, 5 of 22 files at r2, 3 of 15 files at r3, 11 of 73 files at r5, 20 of 30 files at r7, 25 of 35 files at r9, 10 of 21 files at r10, 4 of 8 files at r12, 3 of 12 files at r15, 4 of 15 files at r17, 11 of 11 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36875)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36875)* status: :shipit: complete! ✓

**Comment by alebuh** [comment]
trigger codebasehash

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 24 files at r1, 5 of 22 files at r2, 3 of 15 files at r3, 11 of 73 files at r5, 20 of 30 files at r7, 25 of 35 files at r9, 10 of 21 files at r10, 4 of 8 files at r12, 3 of 12 files at r15, 4 of 15 files at r17, 11 of 11 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36875#-:-NGSESuMEvEYCCtCaK22:bnfp4nl)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 15 files at r17.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36875)* status: :shipit: complete! ✓

**Pull request merged**
