### PR TITLE
[feat]: [CDS-39372]: Add module info in template entity

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34893)

### CODE REVIEW

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34893)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/entity/TemplateEntity.java` line 96 at r2](https://reviewable.io/reviews/harness/harness-core/34893#-N6I8o0E0zI6_EXOnpQ7:-N6I8o0E0zI6_EXOnpQ8:bny77sd) ([raw file](https://github.com/harness/harness-core/blob/f65b404054c85da6ce3247481d8810623b15a72a/840-template-service/src/main/java/io/harness/template/entity/TemplateEntity.java#L96)):*
> ```Java
>   @Setter @NonFinal @SchemaIgnore @NotNull @LastModifiedDate long lastUpdatedAt;
> 
>   @Setter @NonFinal Set<String> module;
> ```

nit: modules
___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 178 at r2](https://reviewable.io/reviews/harness/harness-core/34893#-N6IAYpv-YTQB_JEQaIt:-N6IAYpw1G35NutsvvpT:bbkkt8v) ([raw file](https://github.com/harness/harness-core/blob/f65b404054c85da6ce3247481d8810623b15a72a/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L178)):*
> ```Java
>           Optional<TemplateEntity> templateEntity = templateService.getOrThrowExceptionIfInvalid(
>               templateIdentifierRef.getAccountIdentifier(), templateIdentifierRef.getOrgIdentifier(),
>               templateIdentifierRef.getProjectIdentifier(), templateIdentifierRef.getIdentifier(), versionLabel, false);
> ```

Use templateCache to fetch template.
Add a method in TemplateMergeServiceHelper to get template from templateCache.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34893)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 178 at r2](https://reviewable.io/reviews/harness/harness-core/34893#-N6IAYpv-YTQB_JEQaIt:-N6MLBKC85sIE9Ebnl6Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f65b404054c85da6ce3247481d8810623b15a72a/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L178)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Use templateCache to fetch template.
Add a method in TemplateMergeServiceHelper to get template from templateCache.
</blockquote></details>

Done.

**Review by inderschera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34893)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/34893#-N6NM-Uw7TZp0VBGfyLG:-N6NM-Uw7TZp0VBGfyLH:b-xcoee7) ([raw file](https://github.com/harness/harness-core/blob/2006e152d455287e9619a2752f7399ba47276a4c/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L85)):*
> ```Java
>     }
> 
>     IdentifierRef templateIdentifierRef = IdentifierRefHelper.getIdentifierRef(identifier, accountId, orgId, projectId);
> ```

This is duplicate code. move it into a method.



_Code quote:_
```Java
    IdentifierRef templateIdentifierRef = IdentifierRefHelper.getIdentifierRef(identifier, accountId, orgId, projectId);

    String templateUniqueIdentifier = generateUniqueTemplateIdentifier(templateIdentifierRef.getAccountIdentifier(),
        templateIdentifierRef.getOrgIdentifier(), templateIdentifierRef.getProjectIdentifier(),
        templateIdentifierRef.getIdentifier(), versionMarker);
    if (templateCacheMap.containsKey(templateUniqueIdentifier)) {
      return templateCacheMap.get(templateUniqueIdentifier);
    }

    Optional<TemplateEntity> templateEntity = templateService.getOrThrowExceptionIfInvalid(
        templateIdentifierRef.getAccountIdentifier(), templateIdentifierRef.getOrgIdentifier(),
        templateIdentifierRef.getProjectIdentifier(), templateIdentifierRef.getIdentifier(), versionLabel, false);
    if (!templateEntity.isPresent()) {
      throw new NGTemplateException(String.format(
          "The template identifier %s and version label %s does not exist. Could not replace this template",
          templateIdentifierRef.getIdentifier(), versionLabel));
    }
    TemplateEntity template = templateEntity.get();
    templateCacheMap.put(templateUniqueIdentifier, template);
    return template;
```
___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 178 at r2](https://reviewable.io/reviews/harness/harness-core/34893#-N6IAYpv-YTQB_JEQaIt:-N6NMB_50JADWkIg2lWp:b6rz818) ([raw file](https://github.com/harness/harness-core/blob/f65b404054c85da6ce3247481d8810623b15a72a/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L178)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Get template from templateMergeServiceHelper using the getLinkedTemplateEntity() method you created.

**Review by utkarshchoubey-harness — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34893#-:-N6SlkVC-pr9AYYvjdGc:bnfp4nl)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1, 1 of 5 files at r2, 1 of 4 files at r3, 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34893)* status: 2 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/filter/creation/FilterCreationBlobResponseUtils.java` line 56 at r5](https://reviewable.io/reviews/harness/harness-core/34893#-N6SlJI1DP1vL31ZnJFy:-N6SlJI1DP1vL31ZnJFz:b-t7skz0) ([raw file](https://github.com/harness/harness-core/blob/74a3f3c22ecf7381ce8f068638c772ffef0e6831/800-pipeline-service/src/main/java/io/harness/pms/filter/creation/FilterCreationBlobResponseUtils.java#L56)):*
> ```Java
>     if (!filters.containsKey(response.getServiceName())) {
>       filters.put(response.getServiceName(), response.getResponse().getFilter());
>     }
> ```

When was it not coming?



_Code quote:_
```Java
    if (!filters.containsKey(response.getServiceName())) {
      filters.put(response.getServiceName(), response.getResponse().getFilter());
    }
```
___
*[`840-template-service/src/main/java/io/harness/template/entity/TemplateEntity.java` line 96 at r5](https://reviewable.io/reviews/harness/harness-core/34893#-N6SlZ9t735Y5qCUTaGH:-N6SlZ9t735Y5qCUTaGI:bv8g0qd) ([raw file](https://github.com/harness/harness-core/blob/74a3f3c22ecf7381ce8f068638c772ffef0e6831/840-template-service/src/main/java/io/harness/template/entity/TemplateEntity.java#L96)):*
> ```Java
>   @Setter @NonFinal @SchemaIgnore @NotNull @LastModifiedDate long lastUpdatedAt;
> 
>   @Setter @NonFinal Set<String> modules;
> ```

@inderschera didnt we decide to show templates in every module, then we are doing this for pipeline having templates right?

**Review by inderschera — APPROVED** [review]
> Reviewed 2 of 4 files at r3, 1 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34893)* status: :shipit: complete! ✓

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 70 at r5](https://reviewable.io/reviews/harness/harness-core/34893#-N6SleNEANExfNUIIPzp:-N6SleNEANExfNUIIPzq:b-bg24dj) ([raw file](https://github.com/harness/harness-core/blob/74a3f3c22ecf7381ce8f068638c772ffef0e6831/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L70)):*
> ```Java
>         accountId, orgId, projectId, identifier, versionLabel, templateCacheMap, versionMarker);
>   }
>   public TemplateEntity getLinkedTemplateEntityHelper(String accountId, String orgId, String projectId,
> ```

nit: should be private
___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 177 at r5](https://reviewable.io/reviews/harness/harness-core/34893#-N6SlEnx5bHO-jMJhQE4:-N6SlEnx5bHO-jMJhQE5:b-9b1tjd) ([raw file](https://github.com/harness/harness-core/blob/74a3f3c22ecf7381ce8f068638c772ffef0e6831/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L177)):*
> ```Java
>               accountId, orgId, projectId, identifier, versionLabel, templateCacheMap);
>           Set<String> moduleInfo = new HashSet<>();
>           moduleInfo = isNotEmpty(templateEntity.getModules()) ? templateEntity.getModules() : moduleInfo;
> ```

nit: use static imports with the classes, here EmptyPredicate.isNotEmpty(). It's easier for reader to understand where it's coming from.
___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 186 at r5](https://reviewable.io/reviews/harness/harness-core/34893#-N6Sm6j6EEROGkOsYX63:-N6Sm6j6EEROGkOsYX64:b-f6wcox) ([raw file](https://github.com/harness/harness-core/blob/74a3f3c22ecf7381ce8f068638c772ffef0e6831/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L186)):*
> ```Java
>                   .fqn(FQN.builder().fqnList(fqnList).build().getExpressionFqn())
>                   .templateIdentifier(templateEntity.getIdentifier())
>                   .versionLabel(versionLabelNode == null ? templateEntity.getVersionLabel() : versionLabel)
> ```

nit: you can always set it as templateEntity.getVersionLabel()

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34893)* status: 1 change requests. 2. unresolved discussions. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/filter/creation/FilterCreationBlobResponseUtils.java` line 56 at r5](https://reviewable.io/reviews/harness/harness-core/34893#-N6SlJI1DP1vL31ZnJFy:-N6StiMZ8yNA0fBZbL_f:b-gur40v) ([raw file](https://github.com/harness/harness-core/blob/74a3f3c22ecf7381ce8f068638c772ffef0e6831/800-pipeline-service/src/main/java/io/harness/pms/filter/creation/FilterCreationBlobResponseUtils.java#L56)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

When was it not coming?
</blockquote></details>

Done.
Confirmed with @sahil this wont cause any issue
___
*[`840-template-service/src/main/java/io/harness/template/entity/TemplateEntity.java` line 96 at r5](https://reviewable.io/reviews/harness/harness-core/34893#-N6SlZ9t735Y5qCUTaGH:-N6Stp0f7UPc62eTnod8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/74a3f3c22ecf7381ce8f068638c772ffef0e6831/840-template-service/src/main/java/io/harness/template/entity/TemplateEntity.java#L96)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@inderschera didnt we decide to show templates in every module, then we are doing this for pipeline having templates right?
</blockquote></details>

Done.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34893)* status: 1 change requests. 1. unresolved discussions.

**Review by utkarshchoubey-harness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34893#-:-N6SzUs8ESYm1NjDzj4h:bnfp4nl)* status: :shipit: complete! ✓

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 70 at r5](https://reviewable.io/reviews/harness/harness-core/34893#-N6SleNEANExfNUIIPzp:-N6SzZst1tylSklqDx3J:bfps870) ([raw file](https://github.com/harness/harness-core/blob/74a3f3c22ecf7381ce8f068638c772ffef0e6831/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L70)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: should be private
</blockquote></details>

OK will fix in next PR
___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 177 at r5](https://reviewable.io/reviews/harness/harness-core/34893#-N6SlEnx5bHO-jMJhQE4:-N6SzcgIDckAB75IP31v:b-kxsdi) ([raw file](https://github.com/harness/harness-core/blob/74a3f3c22ecf7381ce8f068638c772ffef0e6831/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L177)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: use static imports with the classes, here EmptyPredicate.isNotEmpty(). It's easier for reader to understand where it's coming from.
</blockquote></details>

OK , will fix in next PR
___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 186 at r5](https://reviewable.io/reviews/harness/harness-core/34893#-N6Sm6j6EEROGkOsYX63:-N6SzjGd8AGvTv1KzYYY:bp7or1e) ([raw file](https://github.com/harness/harness-core/blob/74a3f3c22ecf7381ce8f068638c772ffef0e6831/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L186)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: you can always set it as templateEntity.getVersionLabel()
</blockquote></details>

OK will fill in next PR

**Pull request merged**
