### PR TITLE
feat: [CDS-54409]: servicenow custom table support

### PR DESCRIPTION
**Pull request by naman-goenka**
## Describe your changes
- Removed checks for standard tables.
- Added a ticketV2 API to fetch tables extending task and 4 standard tables.
- But, we allow any custom table to supplied as ticketType because of the permissions required to execute the new API (itil)
- In v2 api, sufficient perms are not present, we default to standard tables.
- [Permissions Required testing](https://harness.atlassian.net/wiki/spaces/CDNG/pages/21309292813/ServiceNow+Custom+Table+Support#Permissions)
- [Documentation Pointers](https://harness.atlassian.net/wiki/spaces/CDNG/pages/21309292813/ServiceNow+Custom+Table+Support#Documentation-Pointers)
- FF used by UI to use v2 endpoint instead of v1.
- Testing: Snow create (w / wout templates), Snow update (w / wout templates), Snow approval, UI metadata/ createMetadata calls tested with a custom table extending task and a custom table extending change_request. (two customer scenarios)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45215)

### CODE REVIEW

**Comment by naman-goenka** [comment]
trigger messagecheck

**Review by hingerabhinav — COMMENTED** [review]
> Reviewed 17 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45215)* status: Some of the checks are too old. 18 file(s) to review. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/45215#-NR7RXq_Da4Y90Ktyymw:-NR7RXq_Da4Y90Ktyymx:b-cxwlq4) ([raw file](https://github.com/harness/harness-core/blob/9258522781e9fcb72614a0c59e4d6fda01600220/120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java#L91)):*
> ```Java
>   @GET
>   @Path("ticketTypesV2")
>   @ApiOperation(value = "Get serviceNow ticket types V2", nickname = "getServiceNowTicketTypesV2")
> ```

Let's add @Hidden until UI is ready

**Comment by naman-goenka** [comment]
> > Reviewed 17 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/45215)_ status: Some of the checks are too old. 18 file(s) to review. 0 of 2 approvals obtained.
> 
> _[`120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/45215#-NR7RXq_Da4Y90Ktyymw:-NR7RXq_Da4Y90Ktyymx:b-cxwlq4) ([raw file](https://github.com/harness/harness-core/blob/9258522781e9fcb72614a0c59e4d6fda01600220/120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java#L91)):_
> 
> > ```java
> >   @GET
> >   @Path("ticketTypesV2")
> >   @ApiOperation(value = "Get serviceNow ticket types V2", nickname = "getServiceNowTicketTypesV2")
> > ```
> 
> Let's add @hidden until UI is ready

In this resource, all APIs are by default hidden. Others APIs also are not hidden and don't have @hidden.

**Review by hingerabhinav — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45215)* status: Some of the checks are too old. 18 file(s) to review. 1 of 2 approvals obtained.

**Review by hingerabhinav — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45215)* status: Some of the checks are too old. 18 file(s) to review. 1 of 2 approvals obtained.

**Comment by naman-goenka** [comment]
trigger ut8

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45215)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 13 of 17 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45215)* status: :shipit: complete! ✓

**Pull request merged**
