### PR TITLE
fix: [PL-23093]: Displayed only the essential error to the user and l…

### PR DESCRIPTION
**Pull request by boopesh007**
…ogged the rest as error.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31347)

### CODE REVIEW

**Comment by boopesh007** [comment]
trigger messagecheck

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31347)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/security/KmsServiceImpl.java, line 314 at r1](https://reviewable.io/reviews/harness/harness-core/31347#-MxoBEbr1eaPBP-53WOT:-MxoBEbr1eaPBP-53WOU:b9h7n3j) ([raw file](https://github.com/harness/harness-core/blob/c90683ac7b1287ab3f2244256ea537c67cbc3040/400-rest/src/main/java/software/wings/service/impl/security/KmsServiceImpl.java#L314)):*
> ```Java
>           accountId, UUID.randomUUID().toString(), kmsConfig);
>     } catch (WingsException e) {
>       String message = "Was not able to encrypt using given credentials. Please check your credentials and try again.";
> ```

Changes as discussed over call.

**Review by shashank-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31347)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31347)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31347)* status: :shipit: complete! ✓

**Pull request merged**
