### PR TITLE
[feat]: [CDS-44247]: Created table deployment_step and execution_interrupt

### PR DESCRIPTION
**Pull request by Abhishek-CDC**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38856)

### CODE REVIEW

**Review by prabu-kr — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38856)* status: Some of the checks are too old.

**Review by abhinavmittal-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38856)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/resources/timescaledb/create_table_deployment_step.sql` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/38856#-NFxzcRP1WV3HpXefrNP:-NFxzcRP1WV3HpXefrNQ:bhe94pa) ([raw file](https://github.com/harness/harness-core/blob/e4a59af22b91a8849e2e02679b3637a7438fe575/400-rest/src/main/resources/timescaledb/create_table_deployment_step.sql#L15)):*
> ```TSQL
>     STAGE_NAME TEXT,
>     EXECUTION_ID TEXT NOT NULL,
>     APPROVED_BY TEXT,
> ```

add index on accountId, endtime, startId
___
*[`400-rest/src/main/resources/timescaledb/create_table_deployment_step.sql` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/38856#-NFxzabC54R1jO_V72Xm:-NFxzabC54R1jO_V72Xn:bkuplnp) ([raw file](https://github.com/harness/harness-core/blob/e4a59af22b91a8849e2e02679b3637a7438fe575/400-rest/src/main/resources/timescaledb/create_table_deployment_step.sql#L26)):*
> ```TSQL
> 
> 
> SELECT CREATE_HYPERTABLE('DEPLOYMENT_STEP','start_time',if_not_exists => TRUE,migrate_data => true,chunk_time_interval => INTERVAL '1 day');
> ```

7 days
___
*[`400-rest/src/main/resources/timescaledb/create_table_execution_interrupt.sql` line 8 at r2](https://reviewable.io/reviews/harness/harness-core/38856#-NFxzuAIDDfgeJ_LfCO3:-NFxzuAJ8ymFEEG_ymsa:bhe94pa) ([raw file](https://github.com/harness/harness-core/blob/e4a59af22b91a8849e2e02679b3637a7438fe575/400-rest/src/main/resources/timescaledb/create_table_execution_interrupt.sql#L8)):*
> ```TSQL
>     EXECUTION_ID TEXT NOT NULL,
>     STATE_EXECUTION_INSTANCE_ID TEXT,
>     TYPE TEXT NOT NULL,
> ```

add index on accountId, endtime, startId
___
*[`400-rest/src/main/resources/timescaledb/create_table_execution_interrupt.sql` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/38856#-NFxzwTAB7ol-nKsFChU:-NFxzwTAB7ol-nKsFChV:bkuplnp) ([raw file](https://github.com/harness/harness-core/blob/e4a59af22b91a8849e2e02679b3637a7438fe575/400-rest/src/main/resources/timescaledb/create_table_execution_interrupt.sql#L17)):*
> ```TSQL
> COMMIT;
> ```

7 days

**Comment by Abhishek-CDC** [comment]
*[`400-rest/src/main/resources/timescaledb/create_table_deployment_step.sql` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/38856#-NFxzcRP1WV3HpXefrNP:-NG-z-DA15yjPfe5TcIb:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e4a59af22b91a8849e2e02679b3637a7438fe575/400-rest/src/main/resources/timescaledb/create_table_deployment_step.sql#L15)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

add index on accountId, endtime, startId
</blockquote></details>

Done

**Comment by Abhishek-CDC** [comment]
*[`400-rest/src/main/resources/timescaledb/create_table_deployment_step.sql` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/38856#-NFxzabC54R1jO_V72Xm:-NG-z1Kz7JFQOr2oMMFL:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e4a59af22b91a8849e2e02679b3637a7438fe575/400-rest/src/main/resources/timescaledb/create_table_deployment_step.sql#L26)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

7 days
</blockquote></details>

Done

**Comment by Abhishek-CDC** [comment]
*[`400-rest/src/main/resources/timescaledb/create_table_execution_interrupt.sql` line 8 at r2](https://reviewable.io/reviews/harness/harness-core/38856#-NFxzuAIDDfgeJ_LfCO3:-NG-z3bm2xJ2urHRoqY4:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e4a59af22b91a8849e2e02679b3637a7438fe575/400-rest/src/main/resources/timescaledb/create_table_execution_interrupt.sql#L8)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

add index on accountId, endtime, startId
</blockquote></details>

Done

**Comment by Abhishek-CDC** [comment]
*[`400-rest/src/main/resources/timescaledb/create_table_execution_interrupt.sql` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/38856#-NFxzwTAB7ol-nKsFChU:-NG-z5Gr--ohZqjUwAK8:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e4a59af22b91a8849e2e02679b3637a7438fe575/400-rest/src/main/resources/timescaledb/create_table_execution_interrupt.sql#L17)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

7 days
</blockquote></details>

Done

**Pull request merged**
