### PR TITLE
feat: [PIE-3591]: Add foreach support in strategy

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

What the change is about?
Addition of a new foreach strategy that would allow users to iterate on a list of strings.

What is the yaml structure for the same?
for: 
  params: ["A", "b", "c"]

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35093)

### CODE REVIEW

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35093#-:-N6MawN_6thSh9nf4K0d:bnfp4nl)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35093)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`870-orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyFunctor.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/35093#-N6R9GIZ8Kbr5HR9oKg9:-N6R9GI_COmFzRoCGgA1:b83hghr) ([raw file](https://github.com/harness/harness-core/blob/c7ff3e9bffd72ef7d2f6d6ab52fc21f75a7a9b0d/870-orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyFunctor.java#L44)):*
> ```Java
>       }
>       if (level.getStrategyMetadata().hasForMetadata()) {
>         strategyObjectMap.put(FOR, ImmutableMap.of("param", level.getStrategyMetadata().getForMetadata().getValue()));
> ```

For maybe next pr, create matrix constants class to have constant fields



_Code quote:_
```Java
aram"
```
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/strategy/HarnessForConfig.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/35093#-N6RASapE1kHeWnPsxM7:-N6RASaqEOzMMQTgl9XD:b-ix3kdp) ([raw file](https://github.com/harness/harness-core/blob/c7ff3e9bffd72ef7d2f6d6ab52fc21f75a7a9b0d/953-yaml-commons/src/main/java/io/harness/plancreator/strategy/HarnessForConfig.java#L53)):*
> ```Java
>   ParameterField<Integer> maxConcurrency;
> 
>   @YamlSchemaTypes(value = {expression})
> ```

params can be both runtime and expression right?



_Code quote:_
```Java
@YamlSchemaTypes(value = {expression})
```

**Comment by sahilhindwani-harness** [comment]
trigger ti1

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 29 of 30 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35093)* status: 30 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/StepGroupElementConfig.java` line 76 at r3](https://reviewable.io/reviews/harness/harness-core/35093#-N7OyX8uEhhPOSzfzBbY:-N7OyX8v2KaiGk0xe28C:bgsh7ym) ([raw file](https://github.com/harness/harness-core/blob/0c7e0618472e80e7cb1cc0781ab3babee333e178/878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/StepGroupElementConfig.java#L76)):*
> ```Java
>   ParameterField<List<TaskSelectorYaml>> delegateSelectors;
> 
>   @VariableExpression(skipVariableExpression = true) @JsonProperty("strategy") StrategyConfig strategy;
> ```

nit: We still use stepGroupElementConfig for step groups. Is there any plan to use StepGroupNode like we use for steps and stages?
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/strategy/HarnessForConfig.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/35093#-N6RASapE1kHeWnPsxM7:-N7P-945EJZ4VqsHgy5o:b-cwxtuc) ([raw file](https://github.com/harness/harness-core/blob/c7ff3e9bffd72ef7d2f6d6ab52fc21f75a7a9b0d/953-yaml-commons/src/main/java/io/harness/plancreator/strategy/HarnessForConfig.java#L53)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

params can be both runtime and expression right?
</blockquote></details>

{expression} will cover both runtime and expression.

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 30 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35093)* status: 30 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Comment by sahilhindwani-harness** [comment]
trigger ti3

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 5 of 6 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35093)* status: 33 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 22 of 30 files at r3, 4 of 6 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35093)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/StepGroupElementConfig.java` line 76 at r3](https://reviewable.io/reviews/harness/harness-core/35093#-N7OyX8uEhhPOSzfzBbY:-N7U6toB3t_F0RLpJKDw:b-lbute0) ([raw file](https://github.com/harness/harness-core/blob/0c7e0618472e80e7cb1cc0781ab3babee333e178/878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/StepGroupElementConfig.java#L76)):*
> StepGroupNode
There is no stepGroupNode, for others we created Because each step we want to contain, @brijeshdhakar can you check how to remove dependency that ExecutionElementConfig is using StepElementConfig, etc.
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/ForLoopStrategyConfigService.java` line 75 at r5](https://reviewable.io/reviews/harness/harness-core/35093#-N7U9r0n3uziFiJA-Qix:-N7U9r0n3uziFiJA-Qiy:b5grny5) ([raw file](https://github.com/harness/harness-core/blob/ee53c2afb044a3f4bd08a358b2729406e3c0030c/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/ForLoopStrategyConfigService.java#L75)):*
> ```Java
>       validateStartEnd(start, end, params.size());
>       return params.subList(start, end);
>     } else {
> ```

Can you create methods based on different unit 



_Code quote:_
```Java
    if (harnessForConfig.getUnit() == RepeatUnit.PERCENTAGE) {
      int start = 0;
      int end = params.size() - 1;
      if (!ParameterField.isBlank(harnessForConfig.getStart())) {
        start = (int) (((harnessForConfig.getStart().getValue().floatValue()) / 100) * params.size());
      }
      if (!ParameterField.isBlank(harnessForConfig.getEnd())) {
        end = (int) (((harnessForConfig.getEnd().getValue().floatValue()) / 100) * params.size());
      }
      validateStartEnd(start, end, params.size());
      return params.subList(start, end);
    } else {
```
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/ForLoopStrategyConfigService.java` line 128 at r5](https://reviewable.io/reviews/harness/harness-core/35093#-N7UA0zd0e_QwAnl5iGd:-N7UA0zd0e_QwAnl5iGe:b-1r09ei) ([raw file](https://github.com/harness/harness-core/blob/ee53c2afb044a3f4bd08a358b2729406e3c0030c/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/ForLoopStrategyConfigService.java#L128)):*
> ```Java
>         currentIteration++;
>       }
>     }
> ```

you need to handle start and end right?



_Code quote:_
```Java
    if (!ParameterField.isBlank(harnessForConfig.getTimes())) {
      for (int i = 0; i < harnessForConfig.getTimes().getValue(); i++) {
        JsonNode clonedNode = JsonPipelineUtils.asTree(JsonUtils.asMap(StageStrategyUtils.replaceExpressions(
            jsonNode.deepCopy().toString(), new HashMap<>(), i, harnessForConfig.getTimes().getValue(), null)));
        StageStrategyUtils.modifyJsonNode(clonedNode, Lists.newArrayList(String.valueOf(i)));
        jsonNodes.add(clonedNode);
      }
    } else {
      int currentIteration = 0;
      List<String> params = splitParamsIfNeeded(harnessForConfig);
      for (String value : params) {
        JsonNode clonedNode = JsonPipelineUtils.asTree(JsonUtils.asMap(StageStrategyUtils.replaceExpressions(
            jsonNode.deepCopy().toString(), new HashMap<>(), currentIteration, params.size(), value)));
        StageStrategyUtils.modifyJsonNode(clonedNode, Lists.newArrayList(String.valueOf(currentIteration)));
        jsonNodes.add(clonedNode);
        currentIteration++;
      }
    }
```
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/strategy/RepeatUnit.java` line 4 at r5](https://reviewable.io/reviews/harness/harness-core/35093#-N7UADF4-EsDMw3mex5S:-N7UADF4-EsDMw3mex5T:b9qqiky) ([raw file](https://github.com/harness/harness-core/blob/ee53c2afb044a3f4bd08a358b2729406e3c0030c/953-yaml-commons/src/main/java/io/harness/plancreator/strategy/RepeatUnit.java#L4)):*
> ```Java
> 
> public enum RepeatUnit {
>   PERCENTAGE,
> ```

For yaml it should be used as Camel case, Percentage rather PERCENTAGE, thus please add JsonProperty just like ExecutionStatus

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/ForLoopStrategyConfigService.java` line 75 at r5](https://reviewable.io/reviews/harness/harness-core/35093#-N7U9r0n3uziFiJA-Qix:-N7UCOo74zHNluCLqdfP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee53c2afb044a3f4bd08a358b2729406e3c0030c/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/ForLoopStrategyConfigService.java#L75)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can you create methods based on different unit 
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/ForLoopStrategyConfigService.java` line 128 at r5](https://reviewable.io/reviews/harness/harness-core/35093#-N7UA0zd0e_QwAnl5iGd:-N7UCQ1n6k3Rf2dg76Xa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee53c2afb044a3f4bd08a358b2729406e3c0030c/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/ForLoopStrategyConfigService.java#L128)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

you need to handle start and end right?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`953-yaml-commons/src/main/java/io/harness/plancreator/strategy/RepeatUnit.java` line 4 at r5](https://reviewable.io/reviews/harness/harness-core/35093#-N7UADF4-EsDMw3mex5S:-N7UCRl37TXS5VyhkrLv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee53c2afb044a3f4bd08a358b2729406e3c0030c/953-yaml-commons/src/main/java/io/harness/plancreator/strategy/RepeatUnit.java#L4)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

For yaml it should be used as Camel case, Percentage rather PERCENTAGE, thus please add JsonProperty just like ExecutionStatus
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35093)* status: 5 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35093)* status: 10 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by brijeshdhakar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35093)* status: 10 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35093)* status: 10 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Pull request merged**
