### PR TITLE
feat: [PIE-4773]: Addition of services and environments in deployment stage…

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
… config

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36449)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36449)

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 152 at r3](https://reviewable.io/reviews/harness/harness-core/36449#-NA8B-Al7AFiqJqp9Daj:-NA8B-Am4fRmYaQWHtLR:b-9qsi47) ([raw file](https://github.com/harness/harness-core/blob/a73193da671145b9a89a1aa0beeec5fa54e73e1d/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L152)):*
> ```Java
>     } else if (ParameterField.isBlank(deploymentStageConfig.getServices())) {
>       throw new InvalidYamlRuntimeException(
>           format("serviceConfig or Service should be present in stage [%s]. Please add it and try again",
> ```

nit: log message should say "serviceConfig or service or services".

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java` line 71 at r4](https://reviewable.io/reviews/harness/harness-core/36449#-NAhUzQl3lMTMv6DQRai:-NAhUzQl3lMTMv6DQRaj:b-qbh9tn) ([raw file](https://github.com/harness/harness-core/blob/aedf9960165993df45bdbdecdb94962e1ba88968/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java#L71)):*
> ```Java
>   @VariableExpression(skipVariableExpression = true) ServiceYamlV2 service;
>   // For multiple services support
>   @VariableExpression(skipVariableExpression = true) Services services;
> ```

nit: should we call this ServicesYaml or call the EnvironmentsYaml as Environments, just to be consistent

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/beans/MultiDeploymentStepParameters.java` line 32 at r4](https://reviewable.io/reviews/harness/harness-core/36449#-NAhVDMKALrCfFCYbkH9:-NAhVDMKALrCfFCYbkHA:b-3v9dyf) ([raw file](https://github.com/harness/harness-core/blob/aedf9960165993df45bdbdecdb94962e1ba88968/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/beans/MultiDeploymentStepParameters.java#L32)):*
> ```Java
>   String childNodeId;
>   ParameterField<Integer> maxConcurrency;
>   StrategyType strategyType;
> ```

nit: Can we add NotNull annotations from javax here

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 14 files at r3, 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36449)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36449)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 3 of 14 files at r3, 8 of 15 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36449)* status: :shipit: complete! ✓

**Review by hextechpal — APPROVED** [review]
> Reviewed 3 of 14 files at r3, 8 of 15 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36449)* status: :shipit: complete! ✓

**Pull request merged**
