### PR TITLE
fix: [DEL-4203]: Removed JDK11_WATCHER FF

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35695)

### CODE REVIEW

**Comment by jennyjames21** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 354 at r1](https://reviewable.io/reviews/harness/harness-core/35695#-N7q7kCEBDb7kIpiWN0d:-N7q7kCEBDb7kIpiWN0e:b-5qfr77) ([raw file](https://github.com/harness/harness-core/blob/b2e8bd99e0582a754a826988a64695e66e80d5df/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L354)):*
> ```Java
>   EXPORT_TF_PLAN_JSON_NG,
>   ADD_MANIFEST_COLLECTION_STEP,
>   JDK11_WATCHER("Upgrade watcher to java11", HarnessTeam.DEL),
> ```

As per new instructions from FF we need to track delete from FF page also to remove completely.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1735 at r1](https://reviewable.io/reviews/harness/harness-core/35695#-N7q8A7fBOyJ4zF3iADB:-N7q8A7fBOyJ4zF3iADC:b7w0aqj) ([raw file](https://github.com/harness/harness-core/blob/f857bcd11553e6642b13a32da5381d2c14d5e819/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1735)):*
> ```Java
>       if (Integer.parseInt(watcherVersion) < jdk11_base_watcher_version) {
>         return false;
>       }
> ```

why do we need to check this? is this called from delegate?

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35695)* status: 0 of 1 approvals obtained.

**Review by arpit3107 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35695)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35695)* status: 2. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1735 at r1](https://reviewable.io/reviews/harness/harness-core/35695#-N7q8A7fBOyJ4zF3iADB:-N7qEgmGAc2_bcgwWKRZ:bsgwkzv) ([raw file](https://github.com/harness/harness-core/blob/f857bcd11553e6642b13a32da5381d2c14d5e819/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1735)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

why do we need to check this? is this called from delegate?
</blockquote></details>

We planned to run JDK11 watcher from 75276 release onwards, that's the static condition we have in start up scripts as well.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 354 at r1](https://reviewable.io/reviews/harness/harness-core/35695#-N7q7kCEBDb7kIpiWN0d:-N7qEZ4E0IMV_mDfzrSt:b6q3r2w) ([raw file](https://github.com/harness/harness-core/blob/b2e8bd99e0582a754a826988a64695e66e80d5df/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L354)):*
> page also to remove completely.
Sure, will be great if you share some docs around the process

**Comment by jennyjames21** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 354 at r1](https://reviewable.io/reviews/harness/harness-core/35695#-N7q7kCEBDb7kIpiWN0d:-N7qFNhq96KEsfV4Lusp:bumhlz7) ([raw file](https://github.com/harness/harness-core/blob/b2e8bd99e0582a754a826988a64695e66e80d5df/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L354)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

> page also to remove completely.
Sure, will be great if you share some docs around the process
</blockquote></details>

i have meeting with ethan from FF team, will share it with team

**Review by jennyjames21 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35695)* status: :shipit: complete! ✓

**Pull request merged**
