### PR TITLE
[feat]: [CDS-77639]: Writing template schema parser to generate individual templates schema

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51926)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51926)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/PipelineSchemaMetadata.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/51926#-NcVp2MA5IZaZ68uUEsP:-NcVp2MA5IZaZ68uUEsQ:bp1y5ln) ([raw file](https://github.com/harness/harness-core/blob/d13867797e6761c682fb3d0dd657c615e06df567/953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/PipelineSchemaMetadata.java#L25)):*
> ```Java
>   private String nodeType; // type of the node eg: Http, Custom, Deployment
> 
>   // Generate unique key for the given nodeType/group/stageName. This key will be used to store the calculated results
> ```

lets not use stageName maybe mention in example differentiator = stageName for this schema



_Code quote:_
```Java
stageName
```
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/TemplateSchemaMetadata.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/51926#-NcVpJja4zST4oi97-J2:-NcVpJja4zST4oi97-J3:b-qq8lf) ([raw file](https://github.com/harness/harness-core/blob/d13867797e6761c682fb3d0dd657c615e06df567/953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/TemplateSchemaMetadata.java#L18)):*
> ```Java
> @Builder
> public class TemplateSchemaMetadata extends IndividualSchemaMetadata {
>   private String nodeGroup; // Group of the node. eg; Step, Stage, SecretManager
> ```

can you add suffix these are templates types and not internal entities
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/TemplateSchemaParserV0.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/51926#-NcVpjBMBpmiGqPoWPKP:-NcVpjBMBpmiGqPoWPKQ:b-x4pf2a) ([raw file](https://github.com/harness/harness-core/blob/d13867797e6761c682fb3d0dd657c615e06df567/953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/TemplateSchemaParserV0.java#L52)):*
> ```Java
>   @Override
>   String getApplicableNodePath(String parentNode, String nodeType) {
>     return parentNode + (EmptyPredicate.isNotEmpty(nodeType) ? "/" : "") + nodeType;
> ```

why its separate for both pipeline and template?
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/TemplateSchemaParserV0.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/51926#-NcVpxPg2xmLrrZYrgWA:-NcVpxPg2xmLrrZYrgWB:bjy81s2) ([raw file](https://github.com/harness/harness-core/blob/d13867797e6761c682fb3d0dd657c615e06df567/953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/TemplateSchemaParserV0.java#L56)):*
> ```Java
> 
>   @Override
>   void checkIfRootNodeAndAddIntoFqnToNodeMap(String currentFqn, String childNodeRefValue, ObjectNode objectNode) {
> ```

from this method its not clear step/stage/stepgroup templates are in first if condition or in second?

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51926)* status: 7 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/PipelineSchemaMetadata.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/51926#-NcVp2MA5IZaZ68uUEsP:-NcVw42d7PSMCDELa1UM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d13867797e6761c682fb3d0dd657c615e06df567/953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/PipelineSchemaMetadata.java#L25)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

lets not use stageName maybe mention in example differentiator = stageName for this schema
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/TemplateSchemaMetadata.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/51926#-NcVpJja4zST4oi97-J2:-NcVw4Uf6lDtyAger-Mf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d13867797e6761c682fb3d0dd657c615e06df567/953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/TemplateSchemaMetadata.java#L18)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you add suffix these are templates types and not internal entities
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/TemplateSchemaParserV0.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/51926#-NcVpjBMBpmiGqPoWPKP:-NcVw54w9ydFkHAxZ4_j:beqcaww) ([raw file](https://github.com/harness/harness-core/blob/d13867797e6761c682fb3d0dd657c615e06df567/953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/TemplateSchemaParserV0.java#L52)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why its separate for both pipeline and template?
</blockquote></details>

This method is not needed. Removed now.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/TemplateSchemaParserV0.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/51926#-NcVpxPg2xmLrrZYrgWA:-NcW-h3KE5GFArBYRFOl:b-277h9n) ([raw file](https://github.com/harness/harness-core/blob/d13867797e6761c682fb3d0dd657c615e06df567/953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/TemplateSchemaParserV0.java#L56)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

from this method its not clear step/stage/stepgroup templates are in first if condition or in second?
</blockquote></details>

Added comments.

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51926)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/TemplateSchemaParserV0.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/51926#-NcVpxPg2xmLrrZYrgWA:-NcWBJ7w27hRk4amBqeH:b-avtbnz) ([raw file](https://github.com/harness/harness-core/blob/d13867797e6761c682fb3d0dd657c615e06df567/953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/TemplateSchemaParserV0.java#L56)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Added comments.
</blockquote></details>

as discussed offline, changing the rule

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51926)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/TemplateSchemaParserV0.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/51926#-NcVpxPg2xmLrrZYrgWA:-NcYJtjb64vLQKxosSJ5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d13867797e6761c682fb3d0dd657c615e06df567/953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/TemplateSchemaParserV0.java#L56)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

as discussed offline, changing the rule
</blockquote></details>

Done.

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger ut0 ut1 ut2 ut3 ut4 ut5 ut6 ut7 ut8 ut9

**Comment by brijeshdhakar** [comment]
trigger ut0 ut1 ut2 ut3 ut4

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by brijeshdhakar** [comment]
trigger review

**Pull request merged**
