### PR TITLE
[feat]: [PIE-5595]: Proper implementation for Rollback Stage plan creator

### PR DESCRIPTION
**Pull request by namanvermah**
Also added constant for "_rollbackStage"

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39005)

### CODE REVIEW

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39005)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/RollbackStagePlanCreator.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/39005#-NEtCnMF3KrGy4-2RJQV:-NEtCnMF3KrGy4-2RJQW:b9w8pwg) ([raw file](https://github.com/harness/harness-core/blob/9a18db86b8d49e8d54b6bdfb2d9dc4be8f39e2f9/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/RollbackStagePlanCreator.java#L52)):*
> ```Java
>             .stepParameters(
>                 NGSectionStepParameters.builder()
>                     .childNodeId(stageNode.getUuid() + NGCommonUtilPlanCreationConstants.COMBINED_ROLLBACK_ID_SUFFIX)
> ```

combined keyword is specific for CD.

Can we rename this to CHILD_ROLLBACK_ID?

**Review by vaibhav-si — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39005)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39005#-:-NEtDPx6-qi1Mq6nORiO:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39005)* status: :shipit: complete! ✓

**Pull request merged**
