### PR TITLE
feat: [CI-6719]: Added Registry support for V1 pipeline yaml

### PR DESCRIPTION
**Pull request by raghavharness**
## Describe your changes
Added Registry support for V1 pipeline yaml
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42698)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42698)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/PipelineYamlHelper.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/42698#-NLymo5eDuHsDvtd244H:-NLymo5eDuHsDvtd244I:b-o3ovyh) ([raw file](https://github.com/harness/harness-core/blob/b498d31c36c7bf8cbfe11de1c1bb975e6488e088/884-pms-commons/src/main/java/io/harness/pms/utils/PipelineYamlHelper.java#L67)):*
> ```Java
>     } catch (IOException ex) {
>       String message = "Invalid pipeline yaml";
>       log.error(message, ex);
> ```

we should not log and throw exception both, as it will increase logs, and why this util



_Code quote:_
```Java
log.error(message, ex);
```

**Comment by raghavharness** [comment]
> > Reviewed 11 of 12 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/42698)_ status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`884-pms-commons/src/main/java/io/harness/pms/utils/PipelineYamlHelper.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/42698#-NLymo5eDuHsDvtd244H:-NLymo5eDuHsDvtd244I:b-o3ovyh) ([raw file](https://github.com/harness/harness-core/blob/b498d31c36c7bf8cbfe11de1c1bb975e6488e088/884-pms-commons/src/main/java/io/harness/pms/utils/PipelineYamlHelper.java#L67)):_
> 
> > ```java
> >     } catch (IOException ex) {
> >       String message = "Invalid pipeline yaml";
> >       log.error(message, ex);
> > ```
> 
> we should not log and throw exception both, as it will increase logs, and why this util
> 
> _Code quote:_
> 
> ```java
> log.error(message, ex);
> ```

@archit-harness Do you suggest any other util to be used here ? Since registry is part of pipeline I kept it under pipelineYamlHelper util.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42698)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/PipelineYamlHelper.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/42698#-NLymo5eDuHsDvtd244H:-NLzp0ji6_n3veu2QdsY:b-s9ptxp) ([raw file](https://github.com/harness/harness-core/blob/b498d31c36c7bf8cbfe11de1c1bb975e6488e088/884-pms-commons/src/main/java/io/harness/pms/utils/PipelineYamlHelper.java#L67)):*
<details><summary><i>Previously, raghavharness (Raghav) wrote…</i></summary><blockquote>

@archit-harness Do you suggest any other util to be used here ? Since registry is part of pipeline I kept it under pipelineYamlHelper util.
</blockquote></details>

just removing log line is fine, as we throwing exception



_Code quote:_
```Java
YamlUtils.readTree(yaml)
```

**Comment by raghavharness** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/42698)_ status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`884-pms-commons/src/main/java/io/harness/pms/utils/PipelineYamlHelper.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/42698#-NLymo5eDuHsDvtd244H:-NLzp0ji6_n3veu2QdsY:b-s9ptxp) ([raw file](https://github.com/harness/harness-core/blob/b498d31c36c7bf8cbfe11de1c1bb975e6488e088/884-pms-commons/src/main/java/io/harness/pms/utils/PipelineYamlHelper.java#L67)):_
> 
> Previously, raghavharness (Raghav) wrote…
> just removing log line is fine, as we throwing exception
> 
> _Code quote:_
> 
> ```java
> YamlUtils.readTree(yaml)
> ```

@archit-harness Done

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42698)* status: :shipit: complete! ✓

___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/PipelineYamlHelper.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/42698#-NLymo5eDuHsDvtd244H:-NM2anQX4LJaZRwHLdna:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b498d31c36c7bf8cbfe11de1c1bb975e6488e088/884-pms-commons/src/main/java/io/harness/pms/utils/PipelineYamlHelper.java#L67)):*
<details><summary><i>Previously, raghavharness (Raghav) wrote…</i></summary><blockquote>

@archit-harness Done
</blockquote></details>

done

**Pull request merged**
