### PR TITLE
fix: [CDS-78855]: Expression Support for script input variable

### PR DESCRIPTION
**Pull request by sarthakkasat**
## Describe your changes
Expression Support for script input variable.

Test Performed:
Created a custom artifact and in the script used expression from input variables, the expressions are resolved after this change

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52899)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 1045 at r1](https://reviewable.io/reviews/harness/harness-core/52899#-NeHzqc3Akq3I0kZlLL4:-NeHzqc3Akq3I0kZlLL5:ba7s1zd) ([raw file](https://github.com/harness/harness-core/blob/4f55c12be3ee182d8e518e301423e0114d404684/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L1045)):*
> ```Java
>     ResolvedFieldValueWithYamlExpressionEvaluator resolvedFieldValueWithYamlExpressionEvaluator = null;
>     if (isNotEmpty(customScriptInfo.getRuntimeInputYaml())) {
>       script = getResolvedExpression(accountId, orgIdentifier, projectIdentifier, pipelineIdentifier,
> ```

can we not call `getResolvedFieldValueWithYamlExpressionEvaluator` here also ?

**Comment by sarthakkasat** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 1045 at r1](https://reviewable.io/reviews/harness/harness-core/52899#-NeHzqc3Akq3I0kZlLL4:-NeNF_kcB-GaEwPvqCTN:bjqneax) ([raw file](https://github.com/harness/harness-core/blob/4f55c12be3ee182d8e518e301423e0114d404684/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L1045)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we not call `getResolvedFieldValueWithYamlExpressionEvaluator` here also ?
</blockquote></details>

This is a different method, to resolve other expressions we were using the method getResolvedFieldValue method

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 11 of 18 files at r1, 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52899)* status: 18 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 1068 at r2](https://reviewable.io/reviews/harness/harness-core/52899#-NeNNxRS59xITsmK9O76:-NeNNxRS59xITsmK9O77:b-1va7nz) ([raw file](https://github.com/harness/harness-core/blob/ac68d65c47bd1fcacbcca3338f444c02b62bbac8/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L1068)):*
> ```Java
>       inputVariables.put(entry.getKey(), resolvedFieldValueWithYamlExpressionEvaluator.getValue());
>     }
>     return customResourceService.getBuilds(script, versionPath, arrayPath, inputVariables, accountId, orgIdentifier,
> ```

We should write UT for this as well

**Review by sarthakkasat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52899)* status: 18 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 1068 at r2](https://reviewable.io/reviews/harness/harness-core/52899#-NeNNxRS59xITsmK9O76:-NeO2qpnAT3tDMdGj64k:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac68d65c47bd1fcacbcca3338f444c02b62bbac8/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L1068)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We should write UT for this as well
</blockquote></details>

Done.

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/test/java/io/harness/ng/core/artifacts/resources/ArtifactResourceUtilsTest.java` line 888 at r3](https://reviewable.io/reviews/harness/harness-core/52899#-NealmDkBLaU7tXK69Qe:-NealmDkBLaU7tXK69Qf:b-8vk4ch) ([raw file](https://github.com/harness/harness-core/blob/fb0cd117d3f06498d007a506688a076ebce5bae0/120-ng-manager/src/test/java/io/harness/ng/core/artifacts/resources/ArtifactResourceUtilsTest.java#L888)):*
> ```Java
>              eq(null)))
>         .thenReturn(
>             ResolvedFieldValueWithYamlExpressionEvaluator.builder().value("/Users/Desktop/jsonpayload").build());
> ```

we should improve this test
- add a case where expression evaluator is returned 
- verify that pipeline/template service API is called once only

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52899)* status: 18 file(s) to review. 0 of 2 approvals obtained.

**Review by sarthakkasat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52899)* status: 18 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/core/artifacts/resources/ArtifactResourceUtilsTest.java` line 888 at r3](https://reviewable.io/reviews/harness/harness-core/52899#-NealmDkBLaU7tXK69Qe:-Nebu-Na7lyxREMvraMV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fb0cd117d3f06498d007a506688a076ebce5bae0/120-ng-manager/src/test/java/io/harness/ng/core/artifacts/resources/ArtifactResourceUtilsTest.java#L888)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should improve this test
- add a case where expression evaluator is returned 
- verify that pipeline/template service API is called once only
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 18 files at r1, 1 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52899)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Comment by sarthakkasat** [comment]
trigger uts

**Comment by sarthakkasat** [comment]
trigger uts

**Review by sourabh-awashti — APPROVED** [review]
LGTM!!

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52899)* status: 3 file(s) to review.

**Comment by sarthakkasat** [comment]
trigger review

**Pull request merged**
