### PR TITLE
[fix]: [CDS-83290]: Added check to prevent blank updates

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added a get file content call in the update file case for preventing from performing a blank update. Have tested out the same for sync enabled and disabled entities:
1. For pipeline where we are doing blank update by not updating the yaml
2. For pipeline where we are not doing blank update by updating the yaml

Screenshot 2023-12-11 at 1 25 06 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)

### CODE REVIEW

**Comment by adivishy1** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 742 at r1](https://reviewable.io/reviews/harness/harness-core/56171#-Nkc-dOK8rGmewCT4w_m:-NktfWut9tmOjUXQROSY:b-5yj31j) ([raw file](https://github.com/harness/harness-core/blob/a05232f142a6c4a8f2111ed8ead2b4e7aeb9aac0/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L742)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This isn't scalable. What if we write another update method and then this check can be missed. These kind of mandatory checks should be done on the core layer and not on the orchestration layer.
</blockquote></details>

we are doing a similar check in the same method, validateUpdateFileRequest(scmUpdateFileRequestDTO);, 
we can refactor both these into orchestration layer

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 742 at r1](https://reviewable.io/reviews/harness/harness-core/56171#-Nkc-dOK8rGmewCT4w_m:-NktpoBDEhOKhYa2Y95Q:bx2uhz4) ([raw file](https://github.com/harness/harness-core/blob/a05232f142a6c4a8f2111ed8ead2b4e7aeb9aac0/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L742)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

we are doing a similar check in the same method, validateUpdateFileRequest(scmUpdateFileRequestDTO);, 
we can refactor both these into orchestration layer
</blockquote></details>


 
we are doing basic request validation, nothing fancy stuff in that method. Its not anything computational that we are doing there.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1375 at r2](https://reviewable.io/reviews/harness/harness-core/56171#-Nl4mlac-5vhMkUeMJFb:-Nl4mlac-5vhMkUeMJFc:b-g0p5di) ([raw file](https://github.com/harness/harness-core/blob/4f6ede1ca43342d577616a7dab42d11c64a6a7cf/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1375)):*
> ```Java
>     try {
>       GitFileResponse gitFileResponse = getFile(scmConnector,
>           GitFileRequest.builder()
> ```

this has another param for "getOnlyFileContent". We should mark it as TRUE. We only want file content in this case.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1381 at r2](https://reviewable.io/reviews/harness/harness-core/56171#-Nl4mtqM2GlLPnHhM4pW:-Nl4mtqM2GlLPnHhM4pX:b-keheoa) ([raw file](https://github.com/harness/harness-core/blob/4f6ede1ca43342d577616a7dab42d11c64a6a7cf/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1381)):*
> ```Java
>               .build(),
>           scmBlockingStub);
>       if (gitFileResponse.getContent().equals(gitFileDetails.getFileContent())) {
> ```

We should have null checks here.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1391 at r2](https://reviewable.io/reviews/harness/harness-core/56171#-Nl4n5LWEfutMaxEJzKU:-Nl4n5LWEfutMaxEJzKV:b-hc6302) ([raw file](https://github.com/harness/harness-core/blob/4f6ede1ca43342d577616a7dab42d11c64a6a7cf/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1391)):*
> ```Java
>     } catch (Exception exception) {
>       log.error(String.format(
>           "Error occurred while performing blank update check for file %s", gitFileDetails.getFilePath()));
> ```

no exception is being logged

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 207 at r2](https://reviewable.io/reviews/harness/harness-core/56171#-Nl4nGjRE-2bVrra1s6l:-Nl7yoBLCCLYy_atxX3c:b-89qv4t) ([raw file](https://github.com/harness/harness-core/blob/4f6ede1ca43342d577616a7dab42d11c64a6a7cf/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L207)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this can go inside "runUpdateFileOpsPreChecks"
</blockquote></details>

DOne
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1375 at r2](https://reviewable.io/reviews/harness/harness-core/56171#-Nl4mlac-5vhMkUeMJFb:-Nl82gD69bciFmmd5O0-:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/4f6ede1ca43342d577616a7dab42d11c64a6a7cf/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1375)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this has another param for "getOnlyFileContent". We should mark it as TRUE. We only want file content in this case.
</blockquote></details>

done
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1381 at r2](https://reviewable.io/reviews/harness/harness-core/56171#-Nl4mtqM2GlLPnHhM4pW:-Nl84KPcETGLNOWMepuu:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/4f6ede1ca43342d577616a7dab42d11c64a6a7cf/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1381)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should have null checks here.
</blockquote></details>

Done
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1391 at r2](https://reviewable.io/reviews/harness/harness-core/56171#-Nl4n5LWEfutMaxEJzKU:-Nl84JjuDMVaPpQzVZYO:bb6tzbb) ([raw file](https://github.com/harness/harness-core/blob/4f6ede1ca43342d577616a7dab42d11c64a6a7cf/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1391)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

no exception is being logged
</blockquote></details>

DOne

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1396 at r5](https://reviewable.io/reviews/harness/harness-core/56171#-NlPz0pA-ldqL0YQ0biV:-NlPz0pA-ldqL0YQ0biW:b-mseehb) ([raw file](https://github.com/harness/harness-core/blob/06268b7f02afe48fab26e051dbb1f19992399092/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1396)):*
> ```Java
>           exception);
>     }
>     return null;
> ```

what state does "null" represent here?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1371 at r5](https://reviewable.io/reviews/harness/harness-core/56171#-NlPz79Z0JLMfw5mqI6B:-NlPz79Z0JLMfw5mqI6C:b-81u1zm) ([raw file](https://github.com/harness/harness-core/blob/06268b7f02afe48fab26e051dbb1f19992399092/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1371)):*
> ```Java
>   }
> 
>   private UpdateFileResponse returnIfBlankUpdate(
> ```

this method only checks for blank updates. It doesn't "return", so lets make the method name a bit more intuitive.

**Review by senjucanon2 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1240 at r5](https://reviewable.io/reviews/harness/harness-core/56171#-NlPySMgEUQvpTCiSH6y:-NlS0bcA-C2-P3xFOege:brcors) ([raw file](https://github.com/harness/harness-core/blob/06268b7f02afe48fab26e051dbb1f19992399092/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1240)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this check should be moved at end of this method. We are doing a "commit" check which seems a simpler and effective check before we do "file content" check. File content check involves multiple apis.
Also, I think file content check is required only for "Github". For others, I think they work on commit id, and thus the next check shall work automatically for them. Please can you validate. In that sense, it would make more sense to put the file content check at the end so that we don't do it for all.
</blockquote></details>

Moved The check to end of the method
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1371 at r5](https://reviewable.io/reviews/harness/harness-core/56171#-NlPz79Z0JLMfw5mqI6B:-NlRz2WD7gg0soZKV_1n:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/06268b7f02afe48fab26e051dbb1f19992399092/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1371)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this method only checks for blank updates. It doesn't "return", so lets make the method name a bit more intuitive.
</blockquote></details>

Done
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1396 at r5](https://reviewable.io/reviews/harness/harness-core/56171#-NlPz0pA-ldqL0YQ0biV:-NlRzCfIDzzLjs3xHRa9:b-yhpbx9) ([raw file](https://github.com/harness/harness-core/blob/06268b7f02afe48fab26e051dbb1f19992399092/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1396)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what state does "null" represent here?
</blockquote></details>

null -> represents that the new yaml and old yaml have changes(not a blank update), and the updateFlow proceeds.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1269 at r6](https://reviewable.io/reviews/harness/harness-core/56171#-NlUdtwd2pBUtq3TabEM:-NlUdtwd2pBUtq3TabEN:b-drxeqj) ([raw file](https://github.com/harness/harness-core/blob/b0963ceb921119933c6fbf8bc3e04456611ff108/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1269)):*
> ```Java
> 
>     // Check if current file is same as the previous file for update operation.
>     UpdateFileResponse updateFileResponseInCaseOfBlankUpdate =
> ```

we don't need to do this check for the above mentioned GIT providers. If incoming commit id matches to the commit id on the GIT, then automatically we know that file content is the same.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1396 at r5](https://reviewable.io/reviews/harness/harness-core/56171#-NlPz0pA-ldqL0YQ0biV:-NlUeMS30Ge_03PHxPBW:b-fbp4fq) ([raw file](https://github.com/harness/harness-core/blob/06268b7f02afe48fab26e051dbb1f19992399092/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1396)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

null -> represents that the new yaml and old yaml have changes(not a blank update), and the updateFlow proceeds.
</blockquote></details>

In case of exception also you're returning null. How's that correct then?

**Comment by senjucanon2** [comment]
trigger uts

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1396 at r5](https://reviewable.io/reviews/harness/harness-core/56171#-NlPz0pA-ldqL0YQ0biV:-NlWdkOp1jXlGzmCUDTg:b-nkp1pf) ([raw file](https://github.com/harness/harness-core/blob/06268b7f02afe48fab26e051dbb1f19992399092/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1396)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

In case of exception also you're returning null. How's that correct then?
</blockquote></details>

Returned Error response in case of exceptions
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1269 at r6](https://reviewable.io/reviews/harness/harness-core/56171#-NlUdtwd2pBUtq3TabEM:-NlWdoKH7-lLdjfGbaTg:b-hlv2ot) ([raw file](https://github.com/harness/harness-core/blob/b0963ceb921119933c6fbf8bc3e04456611ff108/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1269)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we don't need to do this check for the above mentioned GIT providers. If incoming commit id matches to the commit id on the GIT, then automatically we know that file content is the same.
</blockquote></details>

Added check

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1396 at r5](https://reviewable.io/reviews/harness/harness-core/56171#-NlPz0pA-ldqL0YQ0biV:-NlWkUJi4MSnilVPih8p:b-2jqrpu) ([raw file](https://github.com/harness/harness-core/blob/06268b7f02afe48fab26e051dbb1f19992399092/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1396)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Returned Error response in case of exceptions
</blockquote></details>

Then this null shouldn't be required. Lets remove it.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1396 at r7](https://reviewable.io/reviews/harness/harness-core/56171#-NlWkpH_1GNthpwKU7hb:-NlWkpH_1GNthpwKU7hc:bwkxhzd) ([raw file](https://github.com/harness/harness-core/blob/79e81379f668474db08fb35ff8539a55bdf46e18/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1396)):*
> ```Java
>           String.format("Error occurred while performing blank update check for file %s", gitFileDetails.getFilePath()),
>           exception);
>       return UpdateFileResponse.newBuilder()
> ```

we also need to set error otherwise how will we know what happened.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1396 at r5](https://reviewable.io/reviews/harness/harness-core/56171#-NlPz0pA-ldqL0YQ0biV:-NlWv4Z36ZE5dlfoCUIe:bb6tzbb) ([raw file](https://github.com/harness/harness-core/blob/06268b7f02afe48fab26e051dbb1f19992399092/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1396)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Then this null shouldn't be required. Lets remove it.
</blockquote></details>

DOne
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1396 at r7](https://reviewable.io/reviews/harness/harness-core/56171#-NlWkpH_1GNthpwKU7hb:-NlWv5knCu1IK2OjsZv8:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/79e81379f668474db08fb35ff8539a55bdf46e18/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1396)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we also need to set error otherwise how will we know what happened.
</blockquote></details>

Done

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1394 at r8](https://reviewable.io/reviews/harness/harness-core/56171#-NlX1f9Y1wKqmcVvlSZS:-NlX1f9Y1wKqmcVvlSZT:bbuldab) ([raw file](https://github.com/harness/harness-core/blob/7fcb734d7e04c59bcaf34dae1a345977c8843582/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1394)):*
> ```Java
>       return Optional.of(UpdateFileResponse.newBuilder()
>                              .setStatus(Constants.SCM_INTERNAL_SERVER_ERROR_CODE)
>                              .setError(String.format("Error occurred while performing blank update check for file %s",
> ```

error we should take from the exception.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1396 at r5](https://reviewable.io/reviews/harness/harness-core/56171#-NlPz0pA-ldqL0YQ0biV:-NlX1iOR4_ma3-4g3knD:b118ei0) ([raw file](https://github.com/harness/harness-core/blob/06268b7f02afe48fab26e051dbb1f19992399092/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1396)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

DOne
</blockquote></details>

Just move return to try, catch already has it, then we don't need it here.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1396 at r5](https://reviewable.io/reviews/harness/harness-core/56171#-NlPz0pA-ldqL0YQ0biV:-NlX36ro8JLN37bj7hBZ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/06268b7f02afe48fab26e051dbb1f19992399092/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1396)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Just move return to try, catch already has it, then we don't need it here.
</blockquote></details>

Done
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1394 at r8](https://reviewable.io/reviews/harness/harness-core/56171#-NlX1f9Y1wKqmcVvlSZS:-NlX360KCw83Pm0Xo9OT:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/7fcb734d7e04c59bcaf34dae1a345977c8843582/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1394)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

error we should take from the exception.
</blockquote></details>

Done

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56171)* status: 1 file(s) to review.

**Comment by senjucanon2** [comment]
trigger review

**Comment by senjucanon2** [comment]
trigger uts

**Pull request merged**
