### PR TITLE
feat: [CDS-37901]: Plan Creator for Gitops Clusters Step

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33457)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
trigger authorcheck

**Review by prashantsharma04 — DISMISSED** [review]
> Reviewed 2 of 7 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33457)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 12 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33457)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 336 at r2](https://reviewable.io/reviews/harness/harness-core/33457#-N2z1pGdDEwnoWwgDOLa:-N2z1pGdDEwnoWwgDOLb:b-4ii4qn) ([raw file](https://github.com/harness/harness-core/blob/db6d0cc67d09ffe527faa2f53ab35b9163c2df5f/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L336)):*
> ```Java
>     }
>     return serviceEntityService.get(ctx.getMetadata().getAccountIdentifier(), ctx.getMetadata().getOrgIdentifier(),
>         ctx.getMetadata().getProjectIdentifier(), (String) yaml.getServiceRef().fetchFinalValue(), false);
> ```

We should not need to fetch the entity again, @prashantsharma04 can you please get the data from resolvedService field and pass it as metadata to env?



_Code quote:_
```Java
  private boolean isGitopsEnabled(PlanCreationContext ctx, ServiceYamlV2 yaml) {
    Optional<ServiceEntity> serviceEntity = fetchServiceEntity(ctx, yaml);
    return serviceEntity.map(ServiceEntity::getGitOpsEnabled).orElse(false);
  }

  private Optional<ServiceEntity> fetchServiceEntity(PlanCreationContext ctx, ServiceYamlV2 yaml) {
    if (yaml == null || isEmpty((String) yaml.getServiceRef().fetchFinalValue())) {
      return Optional.empty();
    }
    return serviceEntityService.get(ctx.getMetadata().getAccountIdentifier(), ctx.getMetadata().getOrgIdentifier(),
        ctx.getMetadata().getProjectIdentifier(), (String) yaml.getServiceRef().fetchFinalValue(), false);
```

**Review by archit-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33457)* status: :shipit: complete! ✓

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/ExecutionNodeType.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/33457#-N2z28dQ2_XUU5-zico5:-N2z28dQ2_XUU5-zico6:b9brcmu) ([raw file](https://github.com/harness/harness-core/blob/db6d0cc67d09ffe527faa2f53ab35b9163c2df5f/127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/ExecutionNodeType.java#L34)):*
> ```Java
>   INFRASTRUCTURE_SECTION("INFRASTRUCTURE_SECTION", YamlTypes.PIPELINE_INFRASTRUCTURE),
>   INFRASTRUCTURE("INFRASTRUCTURE", YamlTypes.INFRASTRUCTURE_DEF),
>   GITOPS_CLUSTERS("GITOPS CLUSTERS", YamlTypes.ENVIRONMENT_YAML),
> ```

This should be new YamlTypes, say cluster create new one



_Code quote:_
```Java
YamlTypes.ENVIRONMENT_YAML
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33457)* status: :shipit: complete! ✓

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/ExecutionNodeType.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/33457#-N2z28dQ2_XUU5-zico5:-N2zR8CQAr8SVcpFyned:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/db6d0cc67d09ffe527faa2f53ab35b9163c2df5f/127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/ExecutionNodeType.java#L34)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

This should be new YamlTypes, say cluster create new one
</blockquote></details>

done

**Pull request merged**
