### PR TITLE
[feat]: [PIE-9142]: Writing the haldler logic for storing expressions

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45536)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 1 of 2 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45536)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 675 at r3](https://reviewable.io/reviews/harness/harness-core/45536#-NRGuCJy3DrfyB2_9OOH:-NRGuCJy3DrfyB2_9OOI:b7ykl3e) ([raw file](https://github.com/harness/harness-core/blob/3c7e7cad15a8f612c93cf662328d9002ebc719d4/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L675)):*
> ```Java
>       "Unnecessary restriction apps calls are not called from UI", HarnessTeam.SPG),
>   FF_ALLOW_OPTIONAL_VARIABLE("Allow Optional Variable from UI in NG.", HarnessTeam.PIPELINE),
>   STORE_USED_EXPRESSIONS("FF to use store the expressions used during the pipeline executions", HarnessTeam.PIPELINE),
> ```

add PIE prefix for team
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionUsagesEventHandler.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/45536#-NRGvqe9DR_Ipqd3vXNm:-NRGvqe9DR_Ipqd3vXNn:b9api07) ([raw file](https://github.com/harness/harness-core/blob/3c7e7cad15a8f612c93cf662328d9002ebc719d4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionUsagesEventHandler.java#L46)):*
> ```Java
>   @Override
>   public void handleEvent(OrchestrationEvent event) {
>     // TODO: Do sampling of the requests.
> ```

until sampling is done, we should check if record already exists for a pipeline, don't process anything and return

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45536)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionUsageServiceImpl.java` line 39 at r4](https://reviewable.io/reviews/harness/harness-core/45536#-NRI5_4vBXOkEAuBbv4B:-NRI5_4w9YEnHtrWw4SX:bjk08i3) ([raw file](https://github.com/harness/harness-core/blob/6f6f9ecc7ea7ebf31dc6b1e7bc50dc836fb99147/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionUsageServiceImpl.java#L39)):*
> ```Java
>       String projectId, Map<ExpressionCategory, Set<ExpressionMetadata>> expressionUsages) {
>     Optional<ExpressionUsagesEntity> optional =
>         expressionUsagesRepository.findByAccountIdentifierAndOrgIdentifierAndProjectIdentifierAndPipelineIdentifier(
> ```

This should be wrapped in a distributed lock else we might miss some expressions.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 5 of 9 files at r1, 1 of 2 files at r2, 2 of 3 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45536)* status: :shipit: complete! ✓

**Pull request merged**
