### PR TITLE
fix: [del-4220]: multi arch image for ubi and removing jenkins from file

### PR DESCRIPTION
**Pull request by bharatgoelharness**
This is a feature where we are introducing a multi arch delegate image.
This will be available for ubi-no-tools.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35789)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/35789#-N8RushR5qLqrCK5OpOz):*
@bharatgoelharness please add description and checklist in the PR

**Comment by raghuAtWings** [comment]
*[`dockerization/delegate/Dockerfile` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/35789#-N8RvEsY4RiOQ9lYrXNz:-N8RvEsY4RiOQ9lYrXO-:b-3ktbk1) ([raw file](https://github.com/harness/harness-core/blob/68bf656540d1b16fbb7a5c3e17420d6d9c2408cb/dockerization/delegate/Dockerfile#L1)):*
> ```Dockerfile
> FROM ubuntu:20.04
> ```

rename the file to specific name
also why are we changing the OS from ubuntu to redhat

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35789)* status: Some of the checks are too old. 0 of 1 approvals obtained.

**Comment by bharatgoelharness** [comment]
@raghuAtWings in buiildx tool it always takes Dockerfile name. 
Regarding OS change: In ubi base image we are always using redhat base OS.

**Review by bharatgoelharness — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35789)* status: Some of the checks are too old. 0 of 1 approvals obtained.

**Review by bharatgoelharness — COMMENTED** [review]
@raghuAtWings in buiildx tool it always takes Dockerfile name.
Regarding OS change: In ubi base image we are always using redhat base OS.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35789#-:-N8b_l0a75rU1FZPvLYg:b-tbmibg)* status: Some of the checks are too old. 0 of 1 approvals obtained.

**Review by bharatgoelharness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35789)* status: Some of the checks are too old. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`dockerization/delegate/Dockerfile` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/35789#-N8RvEsY4RiOQ9lYrXNz:-N8b_pTZ9lX42GePQdXk:b-tbmibg) ([raw file](https://github.com/harness/harness-core/blob/68bf656540d1b16fbb7a5c3e17420d6d9c2408cb/dockerization/delegate/Dockerfile#L1)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

rename the file to specific name
also why are we changing the OS from ubuntu to redhat
</blockquote></details>

@raghuAtWings in buiildx tool it always takes Dockerfile name.
Regarding OS change: In ubi base image we are always using redhat base OS.

**Comment by raghuAtWings** [comment]
*[`dockerization/delegate/Dockerfile` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/35789#-N8RvEsY4RiOQ9lYrXNz:-N8baQb51m6BN1r4g4KX:bkuhx91) ([raw file](https://github.com/harness/harness-core/blob/68bf656540d1b16fbb7a5c3e17420d6d9c2408cb/dockerization/delegate/Dockerfile#L1)):*
<details><summary><i>Previously, bharatgoelharness (Bharat Goel) wrote…</i></summary><blockquote>

@raghuAtWings in buiildx tool it always takes Dockerfile name.
Regarding OS change: In ubi base image we are always using redhat base OS.
</blockquote></details>

you can copy the renamed file to Dockerfile in your build step

**Comment by raghuAtWings** [comment]
*[`dockerization/delegate/Dockerfile` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/35789#-N8RvEsY4RiOQ9lYrXNz:-N8badY52Q9MaQGtjbzc:b41ohpt) ([raw file](https://github.com/harness/harness-core/blob/68bf656540d1b16fbb7a5c3e17420d6d9c2408cb/dockerization/delegate/Dockerfile#L1)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

you can copy the renamed file to Dockerfile in your build step
</blockquote></details>

also i don't follow the OS change, what is this file supposed to build? the no tools with multi arch?

**Review by bharatgoelharness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35789)* status: Some of the checks are too old. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/35789#-N8RushR5qLqrCK5OpOz):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

@bharatgoelharness please add description and checklist in the PR
</blockquote></details>

Done.
___
*[`dockerization/delegate/Dockerfile` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/35789#-N8RvEsY4RiOQ9lYrXNz:-N8d61860EBO9X8q5ZVO:b2doqrx) ([raw file](https://github.com/harness/harness-core/blob/68bf656540d1b16fbb7a5c3e17420d6d9c2408cb/dockerization/delegate/Dockerfile#L1)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

also i don't follow the OS change, what is this file supposed to build? the no tools with multi arch?
</blockquote></details>

Regarding filename we can do this what you suggested.

Regarding OS: We are building ubi-no-tools multiarch image. For this we need redhat ubi base version.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35789)* status: 2. unresolved discussions.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35789)* status: :shipit: complete! ✓

**Pull request merged**
