### PR TITLE
fix: [PL-25423]: Removed cyberArk SM from codebase

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
Removed the code related to CyberArk SM as we do not support it anymore. Checked the backward compatibility of delegate in this case and it is working fine.
CyberArk is a connector that we used to support. 

For testing, I tried creating other connectors after removing this code. 
Backward compatibility testing, left the delegate code changes as part of this and tested all the connectors. Everything seems to be working.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36784)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* Code issue 7 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36784)

**Comment by VikasMaddukuriHarness** [comment]
trigger checkstyle, ti2, ti3, ti4

**Comment by VikasMaddukuriHarness** [comment]
trigger ti0

**Comment by VikasMaddukuriHarness** [comment]
trigger ti0, messagecheck

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 36 of 39 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36784)* status: 40 file(s) to review. 1 of 2 approvals obtained.

**Comment by gn-harness** [comment]
Can you please add some description what CyberArk is / what is used for (If you have some link that would be enough too)? Also, can you please write about your test setup in the description?

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 36 of 39 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36784)* status: :shipit: complete! ✓

**Comment by VikasMaddukuriHarness** [comment]
trigger codebasehash

**Review by rijajoo — APPROVED** [review]
> Reviewed 36 of 39 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36784)* status: :shipit: complete! ✓

**Comment by rijajoo** [comment]
trigger codebasehash

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 36 of 39 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36784)* status: :shipit: complete! ✓

**Pull request merged**
