### PR TITLE
fix: [CDS-45758]: Supporting rbac based paginated filtering for Env groups list API 

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
image

image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45112)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupRbacHelper.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/45112#-NQiOywV2lIU5SpoTTcm:-NQiOywV2lIU5SpoTTcn:b-865r0k) ([raw file](https://github.com/harness/harness-core/blob/50fdebc474b7887909ed3aa20b52524d922f5fa0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupRbacHelper.java#L65)):*
> ```Java
>       if (accessControlDTO.isPermitted()) {
>         permittedEnvironmentGroups.add(
>             environmentGroupMap.get(EnvironmentGroupRbacHelper.getEntityScopeInfoFromAccessControlDTO(accessControlDTO))
> ```

what if ACL does not send some env group in the response ? Lets not assume that it will always be found in envGroupMap

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupRbacHelper.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/45112#-NQiPAd-AcaTLFzneURF:-NQiPAd-AcaTLFzneURG:b-jgw95m) ([raw file](https://github.com/harness/harness-core/blob/50fdebc474b7887909ed3aa20b52524d922f5fa0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupRbacHelper.java#L47)):*
> ```Java
>     }
>     Map<EntityScopeInfo, List<EnvironmentGroupEntity>> environmentGroupMap = environmentGroups.stream().collect(
>         groupingBy(EnvironmentGroupRbacHelper::getEntityScopeInfoFromEnvironmentGroup));
> ```

will the llst always be of size (1) , if yes, lets not group by but instead collect to Map<EntityScopeInfo, EnvironmentGroupEntity>

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupRbacHelper.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/45112#-NQiPO5YDPhRasq1vkwa:-NQiPO5YDPhRasq1vkwb:b-nneztu) ([raw file](https://github.com/harness/harness-core/blob/50fdebc474b7887909ed3aa20b52524d922f5fa0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupRbacHelper.java#L39)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.CDC)
> public class EnvironmentGroupRbacHelper {
> ```

Please write tests for this class

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java` line 262 at r2](https://reviewable.io/reviews/harness/harness-core/45112#-NQiPmdyEW2w5l1ZOcy0:-NQiPmdyEW2w5l1ZOcy1:b-uryy92) ([raw file](https://github.com/harness/harness-core/blob/50fdebc474b7887909ed3aa20b52524d922f5fa0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L262)):*
> ```Java
>     if (accessControlClient.hasAccess(ResourceScope.of(accountId, orgIdentifier, projectIdentifier),
>             Resource.of(NGResourceType.ENVIRONMENT_GROUP, null),
>             CDNGRbacPermissions.ENVIRONMENT_GROUP_VIEW_PERMISSION)) {
> ```

can we extract into a method "hasViewPermissionForAll.. or something similar"



_Code quote:_
```Java
    if (accessControlClient.hasAccess(ResourceScope.of(accountId, orgIdentifier, projectIdentifier),
            Resource.of(NGResourceType.ENVIRONMENT_GROUP, null),
            CDNGRbacPermissions.ENVIRONMENT_GROUP_VIEW_PERMISSION)) {
```

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45112)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupRbacHelper.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/45112#-NQiOdHl0SvJgER4Wj8u:-NQiOdHm3YgvMtuYGJwl:bvbtne9) ([raw file](https://github.com/harness/harness-core/blob/50fdebc474b7887909ed3aa20b52524d922f5fa0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupRbacHelper.java#L42)):*
> ```Java
>   @Inject private AccessControlClient accessControlClient;
> 
>   public List<EnvironmentGroupEntity> getPermitted(List<EnvironmentGroupEntity> environmentGroups) {
> ```

can we say getPermittedForView(..) or something similar. The method implicitly used a env group view permission
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java` line 272 at r2](https://reviewable.io/reviews/harness/harness-core/45112#-NQiQFOC7V5t02jAN11d:-NQiQFOC7V5t02jAN11e:b-9k4yvw) ([raw file](https://github.com/harness/harness-core/blob/50fdebc474b7887909ed3aa20b52524d922f5fa0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L272)):*
> ```Java
>       if (isEmpty(environmentGroupEntities)) {
>         envGroupEntities = Page.empty();
>       }
> ```

Lets say there are a total of 100 env groups
User requests for page size = 10, index = 0
```
      List<EnvironmentGroupEntity> environmentGroupEntities =
          environmentGroupService.list(criteria, pageRequest, projectIdentifier, orgIdentifier, accountId).getContent();
```
will give 10 env groups

If user does not have access to these 10 env groups but has access to other 90, we are returning empty from the method, this does not look correct ?

**Comment by vivekkarnatiharness** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupRbacHelper.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/45112#-NQiOdHl0SvJgER4Wj8u:-NR3WvPe-tcHhzyoK7lQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50fdebc474b7887909ed3aa20b52524d922f5fa0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupRbacHelper.java#L42)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we say getPermittedForView(..) or something similar. The method implicitly used a env group view permission
</blockquote></details>

Done.

**Comment by vivekkarnatiharness** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupRbacHelper.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/45112#-NQiOywV2lIU5SpoTTcm:-NR3X69B5UDjG9NCShXb:b-ovz6ul) ([raw file](https://github.com/harness/harness-core/blob/50fdebc474b7887909ed3aa20b52524d922f5fa0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupRbacHelper.java#L65)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

what if ACL does not send some env group in the response ? Lets not assume that it will always be found in envGroupMap
</blockquote></details>

Have handled this case well

**Comment by vivekkarnatiharness** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java` line 262 at r2](https://reviewable.io/reviews/harness/harness-core/45112#-NQiPmdyEW2w5l1ZOcy0:-NR3XI9k4gCYcj9-jPtW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50fdebc474b7887909ed3aa20b52524d922f5fa0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L262)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we extract into a method "hasViewPermissionForAll.. or something similar"
</blockquote></details>

Done.

**Comment by vivekkarnatiharness** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupRbacHelper.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/45112#-NQiPO5YDPhRasq1vkwa:-NR9V97w7Jpb7JRBUMtK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50fdebc474b7887909ed3aa20b52524d922f5fa0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupRbacHelper.java#L39)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Please write tests for this class
</blockquote></details>

Done.

**Comment by vivekkarnatiharness** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java` line 270 at r2](https://reviewable.io/reviews/harness/harness-core/45112#-NQiPzqN9vRaxkIR-xZc:-NR9VHeBCC3SObJGo9PB:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/50fdebc474b7887909ed3aa20b52524d922f5fa0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L270)):*
<details><summary><i>Previously, vivekkarnatiharness wrote…</i></summary><blockquote>

I didn't understand this.
</blockquote></details>

done

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45112)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by hingerabhinav — COMMENTED** [review]
> Reviewed 2 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45112)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java` line 278 at r4](https://reviewable.io/reviews/harness/harness-core/45112#-NRBnJvR87sTzJlKpH3v:-NRBnJvR87sTzJlKpH3w:b-o1gju1) ([raw file](https://github.com/harness/harness-core/blob/585445989814a29d39e65dac2d6a190c5f7b2139/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L278)):*
> ```Java
>           environmentGroupEntities.stream().map(EnvironmentGroupEntity::getIdentifier).collect(toList()));
>       envGroupEntities =
>           environmentGroupService.list(criteria, pageRequest, projectIdentifier, orgIdentifier, accountId);
> ```

why are we calling environmentGroupService.list twice? didn't we get the list the first time?

**Comment by vivekkarnatiharness** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java` line 278 at r4](https://reviewable.io/reviews/harness/harness-core/45112#-NRBnJvR87sTzJlKpH3v:-NRBo1Sj3AHc2IY38u0i:b-oahj98) ([raw file](https://github.com/harness/harness-core/blob/585445989814a29d39e65dac2d6a190c5f7b2139/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L278)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

why are we calling environmentGroupService.list twice? didn't we get the list the first time? 
</blockquote></details>

We have to send the result in paginated way in the end.If we remove to some  envgroups in first call,we need to reset the pagination,for which implementation can again bring bugs.

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45112)* status: :shipit: complete! ✓

**Pull request merged**
