### PR TITLE
feat: [FFM-4121]: add FF for SRM epic

### PR DESCRIPTION
**Pull request by crystal-fong**
## Describe your changes

New FF for new module SRM integration 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35816)

### CODE REVIEW

**Comment by crystal-fong** [comment]
trigger messagecheck

**Review by conormurray95 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35816)* status: 0 of 1 approvals obtained.

**Review by conormurray95 — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35816)* status: :shipit: complete! ✓

**Review by davejohnston — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35816)* status: :shipit: complete! ✓

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 86 at r1](https://reviewable.io/reviews/harness/harness-core/35816#-N83rMfrEuq6-3RqT4n9:-N83rMfrEuq6-3RqT4nA:blgw990) ([raw file](https://github.com/harness/harness-core/blob/dbe36857e90f7ee65a390581562fa5097c943d8a/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L86)):*
> ```Java
>   FFM_2134_FF_PIPELINES_TRIGGER,
>   FFM_3938_STALE_FLAGS_ACTIVE_CARD_HIDE_SHOW,
>   FFM_4117_INTEGRATE_SRM,
> ```

It would be good if we could include the description and team for this flag (this is a new feature that was added recently).  The format is like this 



_Code snippet:_
```Java
FFM_4117_INTEGRATE_SRM("Enable Feature Flags to send events to the SRM module", HarnessTeam.FF),
```

**Review by davejohnston — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35816)* status: :shipit: complete! ✓

**Pull request merged**
