### PR TITLE
fix: [CDS-49567]: use of expressions that use workflow variables to skip the pipeline stage 

### PR DESCRIPTION
**Pull request by rafaelmart1ns**
## Describe your changes
When the user uses expressions like `${empty(${workflow.variables.data})}` as a condition to skip a pipeline stage, this expression could not be resolved. With this code, he basically updates the workflow variables for each stage and correctly resolves the expressions using these variables.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43299)

### CODE REVIEW

**Review by rafaelmart1ns — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43299)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/EnvState.java` line 622 at r1](https://reviewable.io/reviews/harness/harness-core/43299#-NN7GIqP8RKCAvonFrLP:-NN7RCCD0W2ZscMz5aMR:b-hfn8wg) ([raw file](https://github.com/harness/harness-core/blob/1fd642ffe39e0e562527641241b9a6a04f6cf9f1/400-rest/src/main/java/software/wings/sm/states/EnvState.java#L622)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

Why we are changing the timeout?
</blockquote></details>

it was wrong, Ifixed it. done

**Review by Fernando-Dourado — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43299)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/EnvState.java` line 133 at r2](https://reviewable.io/reviews/harness/harness-core/43299#-NN8ugWr-wzE25y_7FF3:-NN8ugWr-wzE25y_7FF4:bo2k7g0) ([raw file](https://github.com/harness/harness-core/blob/57360e15c70f4f8513f13ac0031945373d08c435/400-rest/src/main/java/software/wings/sm/states/EnvState.java#L133)):*
> ```Java
> @TargetModule(HarnessModule._870_CG_ORCHESTRATION)
> public class EnvState extends State implements WorkflowState {
>   public static final Integer ENV_STATE_TIMEOUT_MILLIS = 7 * 24 * 60 * 60 * 1000;
> ```

We should remove this final field too.
___
*[`400-rest/src/main/java/software/wings/sm/states/EnvState.java` line 687 at r2](https://reviewable.io/reviews/harness/harness-core/43299#-NN8umY59YOOYPt_ed_B:-NN8umY62Ur_MjUmV35I:bkcw5tk) ([raw file](https://github.com/harness/harness-core/blob/57360e15c70f4f8513f13ac0031945373d08c435/400-rest/src/main/java/software/wings/sm/states/EnvState.java#L687)):*
> ```Java
> 
>   @Override
>   public ExecutionResponse checkDisableAssertion(
> ```

Could you help me to remind, why we are implementing a method where we already have a default one from interface?

**Review by rafaelmart1ns — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43299)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/EnvState.java` line 133 at r2](https://reviewable.io/reviews/harness/harness-core/43299#-NN8ugWr-wzE25y_7FF3:-NN8ve7uEdnV6c3zGjUz:b-7us6j4) ([raw file](https://github.com/harness/harness-core/blob/57360e15c70f4f8513f13ac0031945373d08c435/400-rest/src/main/java/software/wings/sm/states/EnvState.java#L133)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

We should remove this final field too.
</blockquote></details>

Ok. It removed.
___
*[`400-rest/src/main/java/software/wings/sm/states/EnvState.java` line 687 at r2](https://reviewable.io/reviews/harness/harness-core/43299#-NN8umY59YOOYPt_ed_B:-NN8vh3BClOsiX_9npDx:bhx45qk) ([raw file](https://github.com/harness/harness-core/blob/57360e15c70f4f8513f13ac0031945373d08c435/400-rest/src/main/java/software/wings/sm/states/EnvState.java#L687)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

Could you help me to remind, why we are implementing a method where we already have a default one from interface?
</blockquote></details>

Just to put all changes behind a FF.

**Review by Fernando-Dourado — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43299)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/EnvState.java` line 687 at r2](https://reviewable.io/reviews/harness/harness-core/43299#-NN8umY59YOOYPt_ed_B:-NNDHE3VDCeHlmz1DRA3:b-fmpgv3) ([raw file](https://github.com/harness/harness-core/blob/57360e15c70f4f8513f13ac0031945373d08c435/400-rest/src/main/java/software/wings/sm/states/EnvState.java#L687)):*
<details><summary><i>Previously, rafaelmart1ns (Rafael Martins) wrote…</i></summary><blockquote>

Just to put all changes behind a FF.
</blockquote></details>

Got it, now I can see your point. Approved.

One important note is to create the GA ticket for this FF and mention that we need to move the fix to the default method to avoid duplicate code.

**Review by lasdox — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43299)* status: 3 file(s) to review. 1. unresolved discussions.

**Review by rafaelmart1ns — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43299)* status: 3 file(s) to review. 2. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/sm/states/EnvState.java` line 687 at r2](https://reviewable.io/reviews/harness/harness-core/43299#-NN8umY59YOOYPt_ed_B:-NNDIjkl30p-m0skJ98M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/57360e15c70f4f8513f13ac0031945373d08c435/400-rest/src/main/java/software/wings/sm/states/EnvState.java#L687)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

Got it, now I can see your point. Approved.

One important note is to create the GA ticket for this FF and mention that we need to move the fix to the default method to avoid duplicate code.
</blockquote></details>

Done.

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43299)* status: :shipit: complete! ✓

**Pull request merged**
