### PR TITLE
[fix]: [PL-32585]: Fixed Account Edition Incorrect in Switch Account 

### PR DESCRIPTION
**Pull request by adiyaar24**
## Describe your changes
Whenever a customer used to purchase a NG license of FF / CCM or any other module then on switching account it showed them as TRIAL account even though they have paid for it . That has been fixed over here 

Testing has been perfomed using the following scenario
- A New account is created with no CD License in CG and only a SRM Enterprise License is added to the account. The results are now coming as expected and it shows as **PAID** instead of **TRIAL**

**Previously**
Screenshot 2023-07-20 at 4 53 25 PM 
**Account Collection with TRIAL License**
Screenshot 2023-07-20 at 4 49 10 PM
**Module License Collection with SRM License**
Screenshot 2023-07-20 at 4 48 45 PM
**Current Result**
Screenshot 2023-07-20 at 5 15 39 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50817)

### CODE REVIEW

**Comment by adiyaar24** [comment]
trigger messagecheck

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50817)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 637 at r1](https://reviewable.io/reviews/harness/harness-core/50817#-N_nCWcT58DDE8zmZtxD:-N_nCWcT58DDE8zmZtxE:b-viijz5) ([raw file](https://github.com/harness/harness-core/blob/84d2147f96004fe6fcaebcaacf311b789721eecb/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L637)):*
> ```Java
>   }
> 
>   public String getNgLicense(String accountId) {
> ```

name it better, some like getHighestEditionNgLicense()
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 638 at r1](https://reviewable.io/reviews/harness/harness-core/50817#-N_nAwGgC-d3L5u2MdK7:-N_nAwGgC-d3L5u2MdK8:b-ze6wny) ([raw file](https://github.com/harness/harness-core/blob/84d2147f96004fe6fcaebcaacf311b789721eecb/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L638)):*
> ```Java
> 
>   public String getNgLicense(String accountId) {
>     AccountLicenseDTO response = NGRestUtils.getResponse(adminLicenseHttpClient.getAccountLicense(accountId));
> ```

client calls should be inside a try catch 
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 643 at r1](https://reviewable.io/reviews/harness/harness-core/50817#-N_nBPRT3Xh9es1Na90L:-N_nBPRT3Xh9es1Na90M:bvk93z) ([raw file](https://github.com/harness/harness-core/blob/84d2147f96004fe6fcaebcaacf311b789721eecb/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L643)):*
> ```Java
>     Optional<ModuleLicenseDTO> highestEditionLicense =
>         allModuleLicenses.values().stream().flatMap(Collection::stream).reduce((compareLicense, currentLicense) -> {
>           if (compareLicense.getEdition().compareTo(currentLicense.getEdition()) < 0) {
> ```

why can't we use a comparator?
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 664 at r1](https://reviewable.io/reviews/harness/harness-core/50817#-N_nC5Jm-w4Bc30vte0g:-N_nC5Jm-w4Bc30vte0h:bo8wuh8) ([raw file](https://github.com/harness/harness-core/blob/84d2147f96004fe6fcaebcaacf311b789721eecb/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L664)):*
> ```Java
>     if (highestEditionLicense.get().getEdition() == Edition.ENTERPRISE
>         || highestEditionLicense.get().getEdition() == Edition.TEAM) {
>       return "PAID";
> ```

you should return the actual edition value e.g. TEAM/ENTERPRISE and not PAID and then let the callee method have the logic to deal with it

**Review by adiyaar24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50817)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 664 at r1](https://reviewable.io/reviews/harness/harness-core/50817#-N_nC5Jm-w4Bc30vte0g:-N_nt0aQD5njI2uT5G4k:b-qjjwxs) ([raw file](https://github.com/harness/harness-core/blob/84d2147f96004fe6fcaebcaacf311b789721eecb/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L664)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

you should return the actual edition value e.g. TEAM/ENTERPRISE and not PAID and then let the callee method have the logic to deal with it
</blockquote></details>

We are only showing PAID/FREE/TRIAL in the switch account dialog box so I have kept the behaviour same based on that

**Review by adiyaar24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50817)* status: 1 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 637 at r1](https://reviewable.io/reviews/harness/harness-core/50817#-N_nCWcT58DDE8zmZtxD:-N_ntBB7Ew32LsmuYGOg:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/84d2147f96004fe6fcaebcaacf311b789721eecb/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L637)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

name it better, some like getHighestEditionNgLicense()
</blockquote></details>

ok
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 638 at r1](https://reviewable.io/reviews/harness/harness-core/50817#-N_nAwGgC-d3L5u2MdK7:-N_ntDvpBdUm6elO27A-:b-e2hig5) ([raw file](https://github.com/harness/harness-core/blob/84d2147f96004fe6fcaebcaacf311b789721eecb/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L638)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

client calls should be inside a try catch 
</blockquote></details>

Okay will update it
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 643 at r1](https://reviewable.io/reviews/harness/harness-core/50817#-N_nBPRT3Xh9es1Na90L:-N_ntGOR8_KkRWHO5mR-:b-xe037j) ([raw file](https://github.com/harness/harness-core/blob/84d2147f96004fe6fcaebcaacf311b789721eecb/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L643)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

why can't we use a comparator?
</blockquote></details>

Haven't tried that will update it over here

**Comment by adiyaar24** [comment]
trigger checkstyle

**Review by kapil-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50817)* status: 1 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger uts

**Review by kapil-harness — APPROVED** [review]

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger uts

**Review by imrantechwiz — APPROVED** [review]

**Comment by adiyaar24** [comment]
Moving forward with the merge @kapil-harness @bhavya181 , changes already approved by @kapil-harness but due to some issues in PR checks needed re approval

**Pull request merged**
