### PR TITLE
feat: [CDS-58922]: add extended timeout for azure webapps deployment

### PR DESCRIPTION
**Pull request by vlica-harness**
## Describe your changes
The purpose of this PR is to extend the timeout for Azure HttpClient from 30 seconds to 150 seconds, for: Slot deployment, Swap Slot, Traffic Shift. 
The changes are based on this suggestion: https://github.com/Azure/azure-sdk-for-java/issues/27221
Below are examples from the customer where they got SocketTimeoutException for deploy to slot, swap slot, update slot configuration settings. 
Screenshot 2023-04-19 at 17 07 34
Screenshot 2023-04-19 at 16 54 15
Screenshot 2023-04-20 at 09 45 19

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46621)

### CODE REVIEW

**Comment by vlica-harness** [comment]
trigger messagecheck

**Comment by vlica-harness** [comment]
trigger feature-build

**Comment by vlica-harness** [comment]
trigger smartchecks

**Comment by vlica-harness** [comment]
trigger feature-build

**Comment by vlica-harness** [comment]
trigger messagecheck

**Review by markoharness — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46621)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46621)* status: :shipit: complete! ✓

**Comment by vlica-harness** [comment]
trigger review

**Review by ivan-83 — APPROVED** [review]
Overall looks good to me, I have a filing that useExtendedReadTimeout can be properly of AzureConfig with default false value. And set it explicitly to false when it is needed. Just to prevent more files changes. However, I am ok and with these changes. 

> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46621#-:-NTZ0JxUBCl_DloCguuK:bdqk6u7)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
> false
I mean set it to true where is needed. 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46621#-:-NTZ18t57Vf9gb9dHmxW:b-mog4ve)* status: :shipit: complete! ✓

**Comment by vlica-harness** [comment]
I see, but it will require also lots of files to be changed where we set at as false. All the endpoints from azure uses this http client, and also from the connector, registry, and other swimlines like scale sets + cg part.

**Pull request merged**
