### PR TITLE
feat: [CDS-38925]: Update CreatePR step to consume environment outcome

### PR DESCRIPTION
**Pull request by rohitk-h**
## Describe your changes
- Update CreatePR step to consume environment outcome

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34437)

### CODE REVIEW

**Review by anshul-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34437)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/git/NGGitOpsTaskParams.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/34437#-N4y3MMhD61YDMfsk8bV:-N4y3MMiCmWxd0zDqFt4:b-1d7oef) ([raw file](https://github.com/harness/harness-core/blob/32b1515906ff932873807fb1ced4e6796bb202c1/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/git/NGGitOpsTaskParams.java#L34)):*
> ```Java
> public class NGGitOpsTaskParams implements TaskParameters, ExecutionCapabilityDemander {
>   private GitFetchFilesConfig gitFetchFilesConfig; // will have ScmConnector
>   Map<String, Map<String, String>> filesToVariablesMap;
> ```

three question

1. what happens to the task if the delegate doesn't have the new code
2. why is it not private
3. what was being sent in this map before? if that object is not sent anymore then can we remove them from kryo registration?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34437)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34437)* status: :shipit: complete! ✓

**Pull request merged**
