### PR TITLE
[feat]: [CDS-57898]: Updated flag info for CG and NG and integrated with SshSessionConfig

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
## Describe your changes
This includes flows where we need FF to be forward to SSH Session factory or SSH Session Manager to make SSH calls.
Introduced FF: `CDS_SSH_CLIENT` and `CDS_SSH_SSHJ`
There is no logic change here and we are just passing flag to the delegate.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45933)

### CODE REVIEW

**Review by lovish1999 — APPROVED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45933)* status: 24 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 20 of 24 files at r1, 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45933)* status: 8 file(s) to review. 0 of 2 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/helper/InstanceSyncHelper.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/45933#-NRtC4ZV0EzS67DTMXa_:-NRtC4ZV0EzS67DTMXaa:b-mik8kx) ([raw file](https://github.com/harness/harness-core/blob/bd3b42b3c0b60f910223c91f98484c38f55d7862/126-instance/src/main/java/io/harness/helper/InstanceSyncHelper.java#L72)):*
> ```Java
>   public void updateFeatureFlagForSsh(SecretSpecDTO secretSpecDTO, String accountId) {
>     try {
>       if (secretSpecDTO instanceof SSHKeySpecDTO) {
> ```

nit: good to add an else block with a logger to denote a noop scenario. will aid in troubleshooting. (non-blocking)

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45933)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45933)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — APPROVED** [review]

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 21 of 24 files at r1, 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45933)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45933)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 18 of 24 files at r1, 6 of 6 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45933)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretServiceV2Impl.java` line 299 at r4](https://reviewable.io/reviews/harness/harness-core/45933#-NS2qpAQEiNzGY8DF5cW:-NS2qpAQEiNzGY8DF5cX:b-nkvtp) ([raw file](https://github.com/harness/harness-core/blob/0ccebbcf193c5f062c5000fa517993b44502bd96/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretServiceV2Impl.java#L299)):*
> ```Java
>           ngFeatureFlagHelperService.isEnabled(accountIdentifier, FeatureName.CDS_SSH_CLIENT));
>       secretSpecDTO.getAuth().setUseSshj(
>           ngFeatureFlagHelperService.isEnabled(accountIdentifier, FeatureName.CDS_SSH_SSHJ));
> ```

Do we need two FFs, can we only have one CDS_SSH_SSHJ, and default behavior should be using an existing(JSch)/SSH client? It is difficult to maintain two FFs.
___
*[`400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java` line 276 at r4](https://reviewable.io/reviews/harness/harness-core/45933#-NS2sNyD-6iez3QdjalN:-NS2rqxw90wNXOMdm_3J:b-52toy4) ([raw file](https://github.com/harness/harness-core/blob/0ccebbcf193c5f062c5000fa517993b44502bd96/400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java#L276)):*
> ```Java
>   private static final String OPEN_SSH = "OPENSSH";
> 
>   // Used by migration
> ```

Should we remove this and the below comments?
___
*[`930-delegate-tasks/src/main/java/software/wings/beans/host/HostConnectionAttributes.java` line 84 at r4](https://reviewable.io/reviews/harness/harness-core/45933#-NS2zMJR94RNloMpvL8M:-NS2zMJSALIk9WKuYBVs:b-3mf8xa) ([raw file](https://github.com/harness/harness-core/blob/0ccebbcf193c5f062c5000fa517993b44502bd96/930-delegate-tasks/src/main/java/software/wings/beans/host/HostConnectionAttributes.java#L84)):*
> ```Java
> 
>   @SchemaIgnore @Transient private boolean useSshClient;
>   @SchemaIgnore @Transient private boolean useSshj;
> ```

Can we have only one property and the default behavior should be sshClient(JSch) existing client/lib?
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 703 at r4](https://reviewable.io/reviews/harness/harness-core/45933#-NS3-Avs9XFEHNI08Jdu:-NS3-Avs9XFEHNI08Jdv:b-fbzekl) ([raw file](https://github.com/harness/harness-core/blob/0ccebbcf193c5f062c5000fa517993b44502bd96/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L703)):*
> ```Java
>   CDS_AWS_BACKOFF_STRATEGY("Enable AWS SDK Client Backoff Strategy", HarnessTeam.CDP),
>   CDS_SSH_CLIENT("Enable SSH new implementation via SSH Client", HarnessTeam.CDP),
>   CDS_SSH_SSHJ("Enable SSH for Vault flow via SSHJ", HarnessTeam.CDP),
> ```

Do we use SSHJ only for Vault flow?

**Comment by arvind-choudhary-h** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretServiceV2Impl.java` line 299 at r4](https://reviewable.io/reviews/harness/harness-core/45933#-NS2qpAQEiNzGY8DF5cW:-NS7rPJk2d9EcDS_-u5v:bjnnvdz) ([raw file](https://github.com/harness/harness-core/blob/0ccebbcf193c5f062c5000fa517993b44502bd96/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretServiceV2Impl.java#L299)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Do we need two FFs, can we only have one CDS_SSH_SSHJ, and default behavior should be using an existing(JSch)/SSH client? It is difficult to maintain two FFs.
</blockquote></details>

At one time, we'll globally enable CDS_SSH_CLIENT and it's required for safe migration.
Link: https://harness.atlassian.net/wiki/spaces/CDNG/pages/21353759083/SSH+Library+upgrade

**Comment by arvind-choudhary-h** [comment]
*[`126-instance/src/main/java/io/harness/helper/InstanceSyncHelper.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/45933#-NRtC4ZV0EzS67DTMXa_:-NS7rlgGB6S2yEMR_7_q:b-h4erml) ([raw file](https://github.com/harness/harness-core/blob/bd3b42b3c0b60f910223c91f98484c38f55d7862/126-instance/src/main/java/io/harness/helper/InstanceSyncHelper.java#L72)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

nit: good to add an else block with a logger to denote a noop scenario. will aid in troubleshooting. (non-blocking)
</blockquote></details>

Yes, will add in next PR.

**Comment by arvind-choudhary-h** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java` line 276 at r4](https://reviewable.io/reviews/harness/harness-core/45933#-NS2sNyD-6iez3QdjalN:-NS7rqRiCYzLIhAC2ICe:bwu8328) ([raw file](https://github.com/harness/harness-core/blob/0ccebbcf193c5f062c5000fa517993b44502bd96/400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java#L276)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Should we remove this and the below comments?
</blockquote></details>

removing in next PR.

**Comment by arvind-choudhary-h** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/beans/host/HostConnectionAttributes.java` line 84 at r4](https://reviewable.io/reviews/harness/harness-core/45933#-NS2zMJR94RNloMpvL8M:-NS7rvQF1Vl9YoH_x7hf:bjnnvdz) ([raw file](https://github.com/harness/harness-core/blob/0ccebbcf193c5f062c5000fa517993b44502bd96/930-delegate-tasks/src/main/java/software/wings/beans/host/HostConnectionAttributes.java#L84)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can we have only one property and the default behavior should be sshClient(JSch) existing client/lib?
</blockquote></details>

At one time, we'll globally enable CDS_SSH_CLIENT and it's required for safe migration.
Link: https://harness.atlassian.net/wiki/spaces/CDNG/pages/21353759083/SSH+Library+upgrade

**Comment by arvind-choudhary-h** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 703 at r4](https://reviewable.io/reviews/harness/harness-core/45933#-NS3-Avs9XFEHNI08Jdu:-NS7ryNs-a4M5rB540eB:b95oc4j) ([raw file](https://github.com/harness/harness-core/blob/0ccebbcf193c5f062c5000fa517993b44502bd96/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L703)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Do we use SSHJ only for Vault flow?
</blockquote></details>

Yes. More details here -- https://harness.atlassian.net/wiki/spaces/CDNG/pages/21353759083/SSH+Library+upgrade

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45933#-:-NSCANptEmOoW2uApZLr:bnfp4nl)* status: Some of the checks are too old.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45933)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
