### PR TITLE
feat: [CDS-82770]: add metrics for Service, Environment and Infrastructure resources

### PR DESCRIPTION
**Pull request by tmacari-harness**
feat: [CDS-82770]: add metrics for Service, Environment and Infrastructure resources

## Describe your changes
Add metrics for Service, Environment and Infrastructure resources
Didn't add metrics for @Hidden APIs, Should we do it?

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-82770]: https://harness.atlassian.net/browse/CDS-82770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55212)

### CODE REVIEW

**Comment by tmacari-harness** [comment]
trigger uts

**Comment by tmacari-harness** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55212)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/metrics/NextGenManagerDropwizardMetricsPublisherImpl.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/55212#-Nit0Hhb1PDGBk29iPKl:-Nit0Hhb1PDGBk29iPKm:b-1h8ese) ([raw file](https://github.com/harness/harness-core/blob/86055927979107d9fc3cf3204f95444604eef4ce/120-ng-manager/src/main/java/io/harness/metrics/NextGenManagerDropwizardMetricsPublisherImpl.java#L44)):*
> ```Java
>       MetricFilter.startsWith("io.dropwizard.jetty.MutableServletContextHandler");
> 
>   private static final List<String> RESOURCE_METRIC_NAMES_PREFIXES =
> ```

cant we just have this contain just resource name and not complete path? as we are still doing contains method
___
*[`120-ng-manager/src/main/resources/metrics/metricDefinitions/ng_manager_resources_metrics.yaml` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/55212#-Nit07VxC1X5Iy_rfMZB:-Nit07VxC1X5Iy_rfMZC:b-v88az3) ([raw file](https://github.com/harness/harness-core/blob/86055927979107d9fc3cf3204f95444604eef4ce/120-ng-manager/src/main/resources/metrics/metricDefinitions/ng_manager_resources_metrics.yaml#L17)):*
> ```YAML
>     type: LastValue
>     unit: count
>   - metricName: io_harness_ng_manager_resources_total_snapshot_999thPercentile
> ```

do we really need this, as we are not using this initially

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55212)* status: 10 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/metrics/NextGenManagerDropwizardMetricsPublisherImpl.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/55212#-Nit0Hhb1PDGBk29iPKl:-Nit1grGD3lfAPpwuN-Y:b-l96agh) ([raw file](https://github.com/harness/harness-core/blob/86055927979107d9fc3cf3204f95444604eef4ce/120-ng-manager/src/main/java/io/harness/metrics/NextGenManagerDropwizardMetricsPublisherImpl.java#L44)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

cant we just have this contain just resource name and not complete path? as we are still doing contains method
</blockquote></details>

Only resource name is not unique, at some point it may lead to unexpected result.
For ex: there would be a resource called "resource123" that we want to handle and another called "resource1" that we do not want to handle.... "resource1" still would match.

But instead of contains() we can check with startsWith().
___
*[`120-ng-manager/src/main/resources/metrics/metricDefinitions/ng_manager_resources_metrics.yaml` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/55212#-Nit07VxC1X5Iy_rfMZB:-Nit3ZAABrU86XKSrwTF:baiqsf8) ([raw file](https://github.com/harness/harness-core/blob/86055927979107d9fc3cf3204f95444604eef4ce/120-ng-manager/src/main/resources/metrics/metricDefinitions/ng_manager_resources_metrics.yaml#L17)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

do we really need this, as we are not using this initially
</blockquote></details>

I saw it is there for io_dropwizard_jetty_MutableServletContextHandler_requests_snapshot_999thPercentile so added it for resource metrics.
Do you think we don't need it?

**Comment by tmacari-harness** [comment]
trigger uts

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55212)* status: 10 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/metrics/NextGenManagerDropwizardMetricsPublisherImpl.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/55212#-Nit0Hhb1PDGBk29iPKl:-NjHNopU-nR_SOwoJRYN:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/86055927979107d9fc3cf3204f95444604eef4ce/120-ng-manager/src/main/java/io/harness/metrics/NextGenManagerDropwizardMetricsPublisherImpl.java#L44)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Only resource name is not unique, at some point it may lead to unexpected result.
For ex: there would be a resource called "resource123" that we wast to handle and another called named "resource1" that we do not want to handle.... "resource1" still would match.

But instead of contains() we can check with startsWith().
</blockquote></details>

Done
___
*[`120-ng-manager/src/main/resources/metrics/metricDefinitions/ng_manager_resources_metrics.yaml` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/55212#-Nit07VxC1X5Iy_rfMZB:-NjHNlxB5r7lUtJeh6m4:brlf3dc) ([raw file](https://github.com/harness/harness-core/blob/86055927979107d9fc3cf3204f95444604eef4ce/120-ng-manager/src/main/resources/metrics/metricDefinitions/ng_manager_resources_metrics.yaml#L17)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

I saw it is there for io_dropwizard_jetty_MutableServletContextHandler_requests_snapshot_999thPercentile so added it for resource metrics.
Do you think we don't need it?
</blockquote></details>

Removed it

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55212)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by tmacari-harness** [comment]
trigger review

**Pull request merged**
