### PR TITLE
[techDebt]: [DEL-3842]: Move GCB task out of 400-rest

### PR DESCRIPTION
**Pull request by jennyjames21**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32456)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/test/java/software/wings/delegatetasks/GcbTaskTest.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/32456#-N0WfFLH4h4jptIL52TN:-N0WfFLH4h4jptIL52TO:bo2ly5c) ([raw file](https://github.com/harness/harness-core/blob/c1d6971d5c2dbc93bbe793315bd0b14a58f32a95/260-delegate/src/test/java/software/wings/delegatetasks/GcbTaskTest.java#L19)):*
> ```Java
> import static software.wings.beans.command.GcbTaskParams.GcbTaskType.POLL;
> import static software.wings.beans.command.GcbTaskParams.GcbTaskType.START;
> import static software.wings.sm.states.GcbState.GcbDelegateResponse.gcbDelegateResponseOf;
> ```

this will probably break things, the same reason i didn't move http task. Currently software.wings.sm.states.GcbState.GcbDelegateResponse will be added in the kryo, once you move it out, the class name will change and that may break kryo. To verify that we need to run the manager with this change and the delegate without it. If it passes we can merge, or we will need to think of a way.

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32456)* status: 0 of 1 approvals obtained.

**Review by raghuAtWings — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32456)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
trigger messagecheck

**Pull request merged**
