### PR TITLE
feat: [CDS-81575]: Publish secret runtime usage - Common changes

### PR DESCRIPTION
**Pull request by mani5h-harness**
## Describe your changes
Publish secret runtime usage
This PR adds secret runtime usages for the following steps
-- Artifact step
-- ConfigFile step
-- Infra step
-- ApplicationSetting step
-- ConnectionStrings Step

Added entity details for the events published

Testing notes
Tested that events are being generated in entity-activity stream using Redis-Insights and MongoDB

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53986)

### CODE REVIEW

**Comment by mani5h-harness** [comment]
trigger uts

**Review by ivan-83 — DISMISSED** [review]
> Reviewed 61 of 61 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53986)* status: 61 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java` line 371 at r1](https://reviewable.io/reviews/harness/harness-core/53986#-NgOyU7HEuPC78wBCGjj:-NgOyU7HEuPC78wBCGjk:b-xl1axc) ([raw file](https://github.com/harness/harness-core/blob/6def4d9cf31dc91933d7a0a665deafcf84f92d98/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java#L371)):*
> ```Java
>   }
> 
>   private void publishRuntimeSecretUsage(Ambiance ambiance, Infrastructure infraSpec) {
> ```

Minor: We could have a common method in service,  publishRuntimeSecretUsage(Ambiance ambiance, List<Object> objs),  because extractReferredSecrets accept obj.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/azure/AzureHelperService.java` line 273 at r1](https://reviewable.io/reviews/harness/harness-core/53986#-NgOyuio69KYXCMYefBu:-NgOyuio69KYXCMYefBv:b-1ei3eh) ([raw file](https://github.com/harness/harness-core/blob/6def4d9cf31dc91933d7a0a665deafcf84f92d98/127-cd-nextgen-entities/src/main/java/io/harness/cdng/azure/AzureHelperService.java#L273)):*
> ```Java
>   }
> 
>   public void publishSecretRuntimeUsage(Ambiance ambiance, StoreConfigWrapper storeConfig) {
> ```

The same comment is for all publishSecretRuntimeUsage methods.

**Comment by mani5h-harness** [comment]
trigger ut0

**Comment by mani5h-harness** [comment]
trigger uts

**Comment by mani5h-harness** [comment]
trigger uts

**Comment by mani5h-harness** [comment]
trigger uts

**Review by piyush-bhuwalka — APPROVED** [review]

**Comment by mani5h-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java` line 371 at r1](https://reviewable.io/reviews/harness/harness-core/53986#-NgOyU7HEuPC78wBCGjj:-NgTUlus7IFeExNIzzdp:b-g7q06t) ([raw file](https://github.com/harness/harness-core/blob/6def4d9cf31dc91933d7a0a665deafcf84f92d98/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java#L371)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor: We could have a common method in service,  publishRuntimeSecretUsage(Ambiance ambiance, List<Object> objs),  because extractReferredSecrets accept obj.
</blockquote></details>

I feel secret extraction and publishing are two tasks. That's why I kept it this way.  
we would also need to pass usageDetail everywhere as well (since we can have more type of usages later), so won't help much with code dedup as well
marking as resolved

**Comment by mani5h-harness** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/azure/AzureHelperService.java` line 273 at r1](https://reviewable.io/reviews/harness/harness-core/53986#-NgOyuio69KYXCMYefBu:-NgTUpTW12eTyUacyEBv:bbq0t4l) ([raw file](https://github.com/harness/harness-core/blob/6def4d9cf31dc91933d7a0a665deafcf84f92d98/127-cd-nextgen-entities/src/main/java/io/harness/cdng/azure/AzureHelperService.java#L273)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The same comment is for all publishSecretRuntimeUsage methods.
</blockquote></details>

marking as resolved with same comment

**Comment by mani5h-harness** [comment]
trigger uts

**Review by piyush-bhuwalka — APPROVED** [review]

**Comment by mani5h-harness** [comment]
trigger uts

**Comment by mani5h-harness** [comment]
trigger featurenamecheck

**Comment by mani5h-harness** [comment]
trigger messagecheck

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53986)* status: 63 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/secretusage/SecretRuntimeUsageServiceImpl.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/53986#-NgTkZTG1aqXW09az-6w:-NgTkZTG1aqXW09az-6x:b-5ikgvk) ([raw file](https://github.com/harness/harness-core/blob/2eba6a83ef756a899d4ac2205d58926c2cc694de/878-ng-common-utilities/src/main/java/io/harness/secretusage/SecretRuntimeUsageServiceImpl.java#L42)):*
> ```Java
>       IdentifierRef secretIdentifierRef, EntityDetailProtoDTO referredByEntity, EntityUsageDetailProto usageDetail) {
>     if (ngFeatureFlagHelperService.isEnabled(
>             secretIdentifierRef.getAccountIdentifier(), FeatureName.NG_SECRET_RUNTIME_USAGE_EVENT_GENERATION)) {
> ```

We need the CDS_ prefix for the FF name.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53986#-:-NgTnPsZD_boBm6iCKXe:bnfp4nl)* status: 63 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53986)* status: 63 file(s) to review. 1 of 2 approvals obtained.

**Comment by mani5h-harness** [comment]
trigger uts

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53986)* status: 68 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/azure/AzureHelperService.java` line 274 at r4](https://reviewable.io/reviews/harness/harness-core/53986#-NgUOcEE8HbCVBZunUCk:-NgUOcEF7yBtQ9fhoatr:bwut30e) ([raw file](https://github.com/harness/harness-core/blob/b429c4937cbf58eeb5ec47c19f063121b60d5eff/127-cd-nextgen-entities/src/main/java/io/harness/cdng/azure/AzureHelperService.java#L274)):*
> ```Java
>   }
> 
>   public void publishSecretRuntimeUsage(Ambiance ambiance, Visitable visitable) {
> ```

It should be WithConnectorRef instead of Visitable, pls take a look at this io.harness.filters.ConnectorRefExtractorHelper#addReference method.

**Comment by mani5h-harness** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/azure/AzureHelperService.java` line 274 at r4](https://reviewable.io/reviews/harness/harness-core/53986#-NgUOcEE8HbCVBZunUCk:-NgUR4lX4F9Ldw2FOMyD:byle9js) ([raw file](https://github.com/harness/harness-core/blob/b429c4937cbf58eeb5ec47c19f063121b60d5eff/127-cd-nextgen-entities/src/main/java/io/harness/cdng/azure/AzureHelperService.java#L274)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

It should be WithConnectorRef instead of Visitable, pls take a look at this io.harness.filters.ConnectorRefExtractorHelper#addReference method.
</blockquote></details>

yes, that is right
But if we use that, we will have to traverse to the child which implement withReference
like AzureWebAppServiceSpec->applicationSettings->store->spec
and spec is of type StoreConfig which doesn't implement WithConnectorRef. It's concrete implementations does. So we also need to check if spec implements WithConnectorRef

By using Visitor here, we don't have to do this traversal. This will be done by Visitor recursively.
In SecretReferenceExtractorVisitor, we only visit the elements with SecretReferenceExtractor as helper class

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53986#-:-NgUXbRS-VGo9A4jWuRo:bnfp4nl)* status: 68 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — DISMISSED** [review]

**Comment by mani5h-harness** [comment]
trigger review

**Comment by yogesh-chauhan** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/secretusage/SecretRuntimeUsageServiceImpl.java` line 68 at r4](https://reviewable.io/reviews/harness/harness-core/53986#-NgUsyjZBB8tyNYIt7fo:-NgUsyjZBB8tyNYIt7fp:boxjao9) ([raw file](https://github.com/harness/harness-core/blob/b429c4937cbf58eeb5ec47c19f063121b60d5eff/878-ng-common-utilities/src/main/java/io/harness/secretusage/SecretRuntimeUsageServiceImpl.java#L68)):*
> ```Java
>   @Override
>   public void createSecretRuntimeUsage(
>       Set<VisitedSecretReference> secretReferences, EntityUsageDetailProto usageDetail) {
> ```

do we need feature flag check here also ?
`FeatureName.CDS_NG_SECRET_RUNTIME_USAGE_EVENT_GENERATION`

**Comment by yogesh-chauhan** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/secretusage/SecretRuntimeUsageServiceImpl.java` line 68 at r4](https://reviewable.io/reviews/harness/harness-core/53986#-NgUsyjZBB8tyNYIt7fo:-NgUt4Uh52bo515J8_QZ:bb9mf9c) ([raw file](https://github.com/harness/harness-core/blob/b429c4937cbf58eeb5ec47c19f063121b60d5eff/878-ng-common-utilities/src/main/java/io/harness/secretusage/SecretRuntimeUsageServiceImpl.java#L68)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need feature flag check here also ?
`FeatureName.CDS_NG_SECRET_RUNTIME_USAGE_EVENT_GENERATION`
</blockquote></details>

otherwise, FF APIs will be called multiple times

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 56 of 61 files at r1, 4 of 5 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53986)* status: 1 file(s) to review.

**Comment by mani5h-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/secretusage/SecretRuntimeUsageServiceImpl.java` line 68 at r4](https://reviewable.io/reviews/harness/harness-core/53986#-NgUsyjZBB8tyNYIt7fo:-NgVA7psEX3ANqrIXovX:bbeo93j) ([raw file](https://github.com/harness/harness-core/blob/b429c4937cbf58eeb5ec47c19f063121b60d5eff/878-ng-common-utilities/src/main/java/io/harness/secretusage/SecretRuntimeUsageServiceImpl.java#L68)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

otherwise, FF APIs will be called multiple times
</blockquote></details>

makes sense, will add it in a separate PR

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53986)* status: :shipit: complete! ✓

**Comment by mani5h-harness** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53986)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by mani5h-harness** [comment]
trigger ut1, ut6, ut9

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53986#-:-NgXk9Ad7eUL9AchEM1B:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
