### PR TITLE
[feat]: [PIE-7252]: Yaml-simplification: use default-value for input if not provided in input-set while starting execution

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

use default-value for input if not provided in input-set while starting execution.

Impact: pipeline-execution flow when inputs are used in yaml-simplification. Everything behind ff.

Testing: Tested pipeline-execute flow with and without inputs. And with default values.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41891)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41891)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputsFunctor.java` line 86 at r1](https://reviewable.io/reviews/harness/harness-core/41891#-NJs8paZAB_HwYlqQqSY:-NJs8pab-GmQsT6j3HmM:bjpprrk) ([raw file](https://github.com/harness/harness-core/blob/eaff42c6da07a9d1e264c6bdd6ebb179ee34a813/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputsFunctor.java#L86)):*
> ```Java
>     Map<String, Object> inputsMap = getDefaultValuesMap(inputsYamlNode);
>     Map<String, Object> inputSetMap =
>         JsonUtils.jsonNodeToMap(JsonUtils.readTree(inputSet).get(YAMLFieldNameConstants.INPUTS));
> ```

we already have yamlNode, we are reading it into jsonNode via util why?
Also can we use JsonPipelineUtils and copy HobjectMapper there to use common object mapper



_Code quote:_
```Java
JsonUtils.readTree(inputSet).get(YAMLFieldNameConstants.INPUTS)
```

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputsFunctor.java` line 86 at r1](https://reviewable.io/reviews/harness/harness-core/41891#-NJs8paZAB_HwYlqQqSY:-NJsNlsz5UdRxks_v53H:b-x0kf38) ([raw file](https://github.com/harness/harness-core/blob/eaff42c6da07a9d1e264c6bdd6ebb179ee34a813/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputsFunctor.java#L86)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we already have yamlNode, we are reading it into jsonNode via util why?
Also can we use JsonPipelineUtils and copy HobjectMapper there to use common object mapper
</blockquote></details>

These are 2 different things. One inputSet is the inputs provided in the pipeline-execute API. While the yamlNode we have is from the pipelineYaml. That is basically metadata of inputs like what is the field name, field type and field properties. We generate the inputs template from this field.

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputsFunctor.java` line 86 at r1](https://reviewable.io/reviews/harness/harness-core/41891#-NJs8paZAB_HwYlqQqSY:-NJsOPCsEss4xi0XMLDO:btstkj6) ([raw file](https://github.com/harness/harness-core/blob/eaff42c6da07a9d1e264c6bdd6ebb179ee34a813/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputsFunctor.java#L86)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

These are 2 different things. One inputSet is the inputs provided in the pipeline-execute API. While the yamlNode we have is from the pipelineYaml. That is basically metadata of inputs like what is the field name, field type and field properties. We generate the inputs template from this field.
</blockquote></details>

Adding comment in the code.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41891)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41891)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/utils/JsonPipelineUtils.java` line 138 at r3](https://reviewable.io/reviews/harness/harness-core/41891#-NJtiVP61RYWJqCDH-Mb:-NJtiVP61RYWJqCDH-Mc:bnierv1) ([raw file](https://github.com/harness/harness-core/blob/934874b2567fcde6501fc10fcf51cd6befbe19ff/953-yaml-commons/src/main/java/io/harness/yaml/utils/JsonPipelineUtils.java#L138)):*
> ```Java
>         log.error("Trace: {}", elem);
>       }
>       throw new RuntimeException(e);
> ```

invalidRequestException?



_Code quote:_
```Java
RuntimeException
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41891)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41891)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41891)* status: :shipit: complete! ✓

**Pull request merged**
