### PR TITLE
[feat]:[pie-6559]: Cache response impl for getPipeline api 

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Implementation added for the cache response for the getPipeline api. The basic get flows were tested.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40700)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/40700#-NHx7xeX6GouPWx4U2r5:-NHx7xeX6GouPWx4U2r6:b-o7j20) ([raw file](https://github.com/harness/harness-core/blob/25d060e63654ff9d2ae28ee97592863473472143/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java#L88)):*
> ```Java
>     ScmGitMetaData scmGitMetaData = getScmGitMetaData();
>     if (scmGitMetaData == null || scmGitMetaData.getCacheResponse() == null) {
>       return CacheResponse.builder().build();
> ```

what if we send null in response? I'm wondering that an empty object may not be correct way to represent that something hasn't come from cache. The field should be null to represent clearly that there's no caching here in the response.



_Code quote:_
```Java
return CacheResponse.builder().build();
```

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java` line 138 at r2](https://reviewable.io/reviews/harness/harness-core/40700#-NHx8KBn0-Du_LUY-O3l:-NHx8KBn0-Du_LUY-O3m:b-ml0k1e) ([raw file](https://github.com/harness/harness-core/blob/25d060e63654ff9d2ae28ee97592863473472143/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java#L138)):*
> ```Java
>       return null;
>     }
>     CacheResponseMetadataDTO cacheResponseMetadataDTO = new CacheResponseMetadataDTO();
> ```

lets use builder here?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java` line 145 at r2](https://reviewable.io/reviews/harness/harness-core/40700#-NHx8OhU6v9HSE021-_A:-NHx8OhU6v9HSE021-_B:bvm048f) ([raw file](https://github.com/harness/harness-core/blob/25d060e63654ff9d2ae28ee97592863473472143/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java#L145)):*
> ```Java
>   }
> 
>   public static CacheStateEnum getCacheStateEnum(CacheState cacheState) {
> ```

can we move this mapper to CacheStateEnum or CacheState class? or a separate mapper would also be good.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40700)* status: 7 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/40700#-NHx7xeX6GouPWx4U2r5:-NHxAcU34rkiujfmhpSv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/25d060e63654ff9d2ae28ee97592863473472143/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java#L88)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if we send null in response? I'm wondering that an empty object may not be correct way to represent that something hasn't come from cache. The field should be null to represent clearly that there's no caching here in the response.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java` line 138 at r2](https://reviewable.io/reviews/harness/harness-core/40700#-NHx8KBn0-Du_LUY-O3l:-NHxCVnnAVIDJhkphH19:buof99o) ([raw file](https://github.com/harness/harness-core/blob/25d060e63654ff9d2ae28ee97592863473472143/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java#L138)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets use builder here?
</blockquote></details>

This was a generated class from the openapi.yaml, dont think we will be able to add the@Builder annotation to this. 
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java` line 145 at r2](https://reviewable.io/reviews/harness/harness-core/40700#-NHx8OhU6v9HSE021-_A:-NHxDueu32x_CCuAveOZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/25d060e63654ff9d2ae28ee97592863473472143/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java#L145)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we move this mapper to CacheStateEnum or CacheState class? or a separate mapper would also be good.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40700)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40700)* status: :shipit: complete! ✓

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/CacheStateMapper.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/40700#-NHxi8DN7tftTLVMBQBZ:-NHxi8DN7tftTLVMBQB_:b-ogc1kp) ([raw file](https://github.com/harness/harness-core/blob/28761a34a881d4a33363623c27e629f95de1fc58/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/CacheStateMapper.java#L20)):*
> ```Java
> @OwnedBy(PIPELINE)
> @UtilityClass
> public class CacheStateMapper {
> ```

Everything related to cacheState or dto for it should be in git sync SDK or any other layer as each service will need to do this, example template-service

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/CacheStateMapper.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/40700#-NHxi8DN7tftTLVMBQBZ:-NHxj_vUBCvyreVGjf9M:b96nm3j) ([raw file](https://github.com/harness/harness-core/blob/28761a34a881d4a33363623c27e629f95de1fc58/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/CacheStateMapper.java#L20)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Everything related to cacheState or dto for it should be in git sync SDK or any other layer as each service will need to do this, example template-service
</blockquote></details>

git sync SDK would never contain such files as its not related to git-service.

Ideally, having such files in every other services is the most right way to do things. No service should care about how other service is reacting to things, they should have their own say in how they want to do things.

But, taking a conscious call, we can put it in some module that other services can use. Still the final call is with the service owner only if they wish to use it from common module or they wish to use it as separate structs in their own service.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40700)* status: 1 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/CacheStateMapper.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/40700#-NHxi8DN7tftTLVMBQBZ:-NHxmQ1O-mESPMVSC5w6:b-nci72f) ([raw file](https://github.com/harness/harness-core/blob/28761a34a881d4a33363623c27e629f95de1fc58/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/CacheStateMapper.java#L20)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

git sync SDK would never contain such files as its not related to git-service.

Ideally, having such files in every other services is the most right way to do things. No service should care about how other service is reacting to things, they should have their own say in how they want to do things.

But, taking a conscious call, we can put it in some module that other services can use. Still the final call is with the service owner only if they wish to use it from common module or they wish to use it as separate structs in their own service.
</blockquote></details>

Each service definitely will have say to do anything in their API exposed to UI and customer.

But if we talk about git service, its a contract between other service and git service and owned by them as they are exposing this extra metadata in their API.

The DTO or mappers to convert inter-service entity to customer exposed one can be done and owned by each service (for starters as every service will rely on same, it can be in common service.)

But the cache response coming from git service should be in git sdk

**Comment by adivishy1** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/40700)_ status: 1 change requests. 1. unresolved discussions.
> 
> _[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/CacheStateMapper.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/40700#-NHxi8DN7tftTLVMBQBZ:-NHxmQ1O-mESPMVSC5w6:b-nci72f) ([raw file](https://github.com/harness/harness-core/blob/28761a34a881d4a33363623c27e629f95de1fc58/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/CacheStateMapper.java#L20)):_
> 
> Previously, mohitg0795 (Mohit Garg) wrote…
> Each service definitely will have say to do anything in their API exposed to UI and customer.
> 
> But if we talk about git service, its a contract between other service and git service and owned by them as they are exposing this extra metadata in their API.
> 
> The DTO or mappers to convert inter-service entity to customer exposed one can be done and owned by each service (for starters as every service will rely on same, it can be in common service.)
> 
> But the cache response coming from git service should be in git sdk

I dont think we can move the mapper to a common module, if you take the example of CacheResponseMetadataDTO object in the new spec, we have to add this in every service if needed. Cause this object CacheResponseMetadataDTO will be generated from the openapi yaml of a pipeline service, we need to have it in every service.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/CacheStateMapper.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/40700#-NHxi8DN7tftTLVMBQBZ:-NHxsmTBEio7WMVHqmOX:brinhc4) ([raw file](https://github.com/harness/harness-core/blob/28761a34a881d4a33363623c27e629f95de1fc58/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/CacheStateMapper.java#L20)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

I dont think we can move the mapper to a common module, if you take the example of CacheResponseMetadataDTO object in the new spec, we have to add this in every service if needed. Cause this object CacheResponseMetadataDTO will be generated from the openapi yaml of a pipeline service, we need to have it in every service.
</blockquote></details>

Yes, cache response from git-service will be in git-sdk. From my understanding, that was already taken care of and this PR only focussed on pipeline service resource layer APIs with caching. For any other metadata DTOs, git-service/git-sdk won't hold it. @adivishy1 if this is missed anywhere, please fix it on priority.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40700)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40700)* status: :shipit: complete! ✓

**Pull request merged**
