### PR TITLE
[feat]: [CDS-77612]: Implementing CRUD operations for gitXWebhooks

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have implemented the CRUD and List operations for the GitXWebhooks. As part of the implementation, have added the service and repository layers to the git webhooks resource apis. To support the service layer, have added the required DTOs and mappers.

Have tested out the creation, updation, fetching, deleting and listing of webhooks via curls.

For the fetching the webhook, the winning index is `accountIdentifier_identifier_repoName_unique_idx`

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> Reviewed 11 of 21 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 21 file(s) to review. 0 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/gitxwebhook/GitXWebhooksApiImpl.java` line 64 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4HFar8RufWDNqXjac:-Nd4HFar8RufWDNqXjad:b1xewko) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/120-ng-manager/src/main/java/io/harness/ng/gitxwebhook/GitXWebhooksApiImpl.java#L64)):*
> ```Java
>     GetGitXWebhookResponseDTO getGitXWebhookResponseDTO = gitXWebhookService.getGitXWebhook(getGitXWebhookRequestDTO);
>     GitXWebhookResponse responseBody = GitXWebhookMapper.buildGetGitXWebhookResponseDTO(getGitXWebhookResponseDTO);
>     return Response.status(200).entity(responseBody).build();
> ```

Shouldn't it be Response.ok() instead of hardcoding 200?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/DeleteGitXWebhookRequestDTO.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4HpwaBI5fOawf1Vqc:-Nd4HpwaBI5fOawf1Vqd:bxpytpc) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/DeleteGitXWebhookRequestDTO.java#L33)):*
> ```Java
>   String accountIdentifier;
>   String webhookIdentifier;
>   String repoName;
> ```

why's repoName required here?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4IPTWCyCbew2_i7xK:-Nd4IPTWCyCbew2_i7xL:b-gecpsq) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L72)):*
> ```Java
>   @Override
>   public CreateGitXWebhookResponseDTO createGitXWebhook(CreateGitXWebhookRequestDTO createGitXWebhookRequestDTO) {
>     GitXWebhooks gitXWebhooks = buildGitXWebhooks(createGitXWebhookRequestDTO);
> ```

this should be "GitXWebhook"

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 209 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4JNLs2j2wNZmWte5x:-Nd4JNLs2j2wNZmWte5y:b2rhylo) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L209)):*
> ```Java
>     UpsertWebhookRequestDTO upsertWebhookRequestDTO = buildUpsertWebhookRequestDTO(gitXWebhooks);
>     try {
>       UpsertWebhookResponseDTO upsertWebhookResponseDTO = webhookEventService.upsertWebhook(upsertWebhookRequestDTO);
> ```

Lets log webhook response here for better clarity

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 87 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4KNnR-GbHEINZeNCo:-Nd4KNnR-GbHEINZeNCp:b-v5ylo7) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L87)):*
> ```Java
>     if (createdGitXWebhook == null) {
>       log.error(String.format("Error while saving webhook [%s] in DB", gitXWebhooks.getIdentifier()));
>       throw new InvalidRequestException(
> ```

why invalidRequestException here?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 73 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4Ktjq2SDYbD2lolgw:-Nd4Ktjq2SDYbD2lolgx:b-ctzaao) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L73)):*
> ```Java
>   public CreateGitXWebhookResponseDTO createGitXWebhook(CreateGitXWebhookRequestDTO createGitXWebhookRequestDTO) {
>     GitXWebhooks gitXWebhooks = buildGitXWebhooks(createGitXWebhookRequestDTO);
>     log.info(String.format("Creating Webhook with identifier %s in account %s",
> ```

use try with resource here to put details into context.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 101 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4LeMv8fWzL_V7YayZ:-Nd4LeMv8fWzL_V7Yay_:b-5uxdk7) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L101)):*
> ```Java
>         getGitXWebhookRequestDTO.getAccountIdentifier(), getGitXWebhookRequestDTO.getWebhookIdentifier(),
>         getGitXWebhookRequestDTO.getRepoName());
>     if (isEmpty(gitXWebhooksList)) {
> ```

we should send 404 in case no webhook found, this needs to be incorporated in open api as well

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 94 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4LlBoBk613aCAwUMT:-Nd4LlBoBk613aCAwUMU:biezr6a) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L94)):*
> ```Java
> 
>   @Override
>   public GetGitXWebhookResponseDTO getGitXWebhook(GetGitXWebhookRequestDTO getGitXWebhookRequestDTO) {
> ```

we can make it Optional<GitX...>

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 109 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4LtLW6bn49mGb7K4z:-Nd4LtLW6bn49mGb7K5-:b-h9j0i) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L109)):*
> ```Java
>     List<GetGitXWebhookResponseDTO> getGitXWebhookResponseList = prepareGitXWebhooks(gitXWebhooksList);
>     if (getGitXWebhookResponseList.size() > 1) {
>       throw new InvalidRequestException(String.format(
> ```

not invalidRequestException, it should be internalServerException that we have inconsistency in our Db

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4MHJ4-yFhcmFrIjwy:-Nd4MHJ4-yFhcmFrIjwz:bpvifbi) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L125)):*
> ```Java
>     Query query = new Query(criteria);
>     Update update = buildUpdate(updateGitXWebhookRequestDTO);
>     GitXWebhooks updatedGitXWebhook = gitXWebhookRepository.update(query, update);
> ```

put it into try catch so that we can decorate errors and return customized errors back .

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 139 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4MPnW8uY0iptLE9I8:-Nd4MPnW8uY0iptLE9I9:b20xlnc) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L139)):*
> ```Java
>     log.info(String.format("Get List of pipelines in account %s", listGitXWebhookRequestDTO.getAccountIdentifier()));
>     Criteria criteria = buildListCriteria(listGitXWebhookRequestDTO);
>     List<GitXWebhooks> gitXWebhooksList = gitXWebhookRepository.list(criteria);
> ```

use try catch

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 163 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4MUHWEpFTX4Z2P0B8:-Nd4MUHWEpFTX4Z2P0B9:b-jrbk8i) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L163)):*
> ```Java
>                    .connectorRef(gitXWebhookResponseDTO.getConnectorRef())
>                    .folderPaths(gitXWebhookResponseDTO.getFolderPaths())
>                    .folderPaths(gitXWebhookResponseDTO.getFolderPaths())
> ```

folderPath twice here, remove one

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/mapper/GitXWebhookMapper.java` line 45 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4N33s2vwB6uUrZdLI:-Nd4N33s2vwB6uUrZdLJ:b-1brlwr) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/mapper/GitXWebhookMapper.java#L45)):*
> ```Java
> public class GitXWebhookMapper {
>   private final int PAGE = 0;
>   private final int SIZE = 30;
> ```

line spacing issue

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/ListGitXWebhookRequestDTO.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4OeEx10wlc-tPRsjf:-Nd4OeEx10wlc-tPRsjg:b9zgruo) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/ListGitXWebhookRequestDTO.java#L31)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public class ListGitXWebhookRequestDTO {
>   String webhookSearchTerm;
> ```

should contain simply the fields on which we allow listing, thats it

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/UpdateGitXWebhookRequestDTO.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4QxZl2fQW3Q9Jj8cv:-Nd4QxZl2fQW3Q9Jj8cw:bbroevj) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/UpdateGitXWebhookRequestDTO.java#L32)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public class UpdateGitXWebhookRequestDTO {
>   String accountIdentifier;
> ```

change to updateCriteria and updateObject

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 22 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/gitxwebhook/GitXWebhooksApiImpl.java` line 64 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4HFar8RufWDNqXjac:-Nd4tV0qENbWvZQdBhUy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/120-ng-manager/src/main/java/io/harness/ng/gitxwebhook/GitXWebhooksApiImpl.java#L64)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Shouldn't it be Response.ok() instead of hardcoding 200?
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/DeleteGitXWebhookRequestDTO.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4HpwaBI5fOawf1Vqc:-Nd4orlx7XOngDm_CJpr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/DeleteGitXWebhookRequestDTO.java#L33)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why's repoName required here?
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/GetGitXWebhookRequestDTO.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4OhZpAXYTw2ItYd80:-Nd4osM63pVLQGiiGIaF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/GetGitXWebhookRequestDTO.java#L33)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

don't need repo name
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/ListGitXWebhookRequestDTO.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4OeEx10wlc-tPRsjf:-Nd4otih3EwWrF6Nts19:besyisn) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/ListGitXWebhookRequestDTO.java#L31)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

should contain simply the fields on which we allow listing, thats it
</blockquote></details>

Removed the list api request body.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/UpdateGitXWebhookRequestDTO.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4QxZl2fQW3Q9Jj8cv:-Nd4p-d28JfvfueGmnz0:bg6pms1) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/UpdateGitXWebhookRequestDTO.java#L32)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

change to updateCriteria and updateObject
</blockquote></details>

I feel for now, we can keep it in a single object and later when repoName becomes a field from which we have to identify a resource we can split it. 
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/mapper/GitXWebhookMapper.java` line 45 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4N33s2vwB6uUrZdLI:-Nd4pIrG1zrPJ-AvvNyd:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/mapper/GitXWebhookMapper.java#L45)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

line spacing issue
</blockquote></details>

Done
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4IPTWCyCbew2_i7xK:-Nd4pOtH6PYlx7mg-Cez:b56pud3) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L72)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this should be "GitXWebhook"
</blockquote></details>

will create a different pr for changing the entity name, if we do change in current pr, it will bloat up even more
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 87 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4KNnR-GbHEINZeNCo:-Nd4paOY31nUKY86W3f0:b2xlja3) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L87)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why invalidRequestException here?
</blockquote></details>

changed to internalServerException
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 94 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4LlBoBk613aCAwUMT:-Nd4q9Fz82_jkY0VyOUQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L94)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we can make it Optional<GitX...>
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 101 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4LeMv8fWzL_V7YayZ:-Nd4q9rjEWSEIKWjHa7s:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L101)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should send 404 in case no webhook found, this needs to be incorporated in open api as well
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 102 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4L8qBC_lALmpoLAM9:-Nd4qOcrCPsFRb55kXiv:b2xlja3) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L102)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why invalidRequestException?
</blockquote></details>

changed to internalServerException
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 163 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4MUHWEpFTX4Z2P0B8:-Nd4qW1W-cBga3_Bye6j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L163)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

folderPath twice here, remove one
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 209 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4JNLs2j2wNZmWte5x:-Nd4tT3n6NRrJurF-lni:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L209)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets log webhook response here for better clarity
</blockquote></details>

Done.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 22 file(s) to review. 1 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 109 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4LtLW6bn49mGb7K4z:-Nd4vsqt3-PC939oU6_v:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L109)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

not invalidRequestException, it should be internalServerException that we have inconsistency in our Db
</blockquote></details>

Done.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 22 file(s) to review. 1 change requests. 17. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 73 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4Ktjq2SDYbD2lolgw:-Nd5TxR87T6kkNJLdtcC:b-z03su2) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L73)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

use try with resource here to put details into context.
</blockquote></details>

as discussed offline will be adding as part of another ticket: https://harness.atlassian.net/browse/CDS-78349
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4MHJ4-yFhcmFrIjwy:-Nd5U2uyD_hn2xHVbIPs:b-z03su2) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L125)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

put it into try catch so that we can decorate errors and return customized errors back .
</blockquote></details>

as discussed offline will be adding as part of another ticket: https://harness.atlassian.net/browse/CDS-78349
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 139 at r3](https://reviewable.io/reviews/harness/harness-core/52131#-Nd4MPnW8uY0iptLE9I8:-Nd5U3isD9juWLLL-DJr:b-z03su2) ([raw file](https://github.com/harness/harness-core/blob/9574722ac66f25704a0b91e9344ce7d7d931aaf9/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L139)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

use try catch
</blockquote></details>

as discussed offline will be adding as part of another ticket: https://harness.atlassian.net/browse/CDS-78349

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 12 of 21 files at r1, 4 of 10 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52131)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]

**Review by utkarshchoubey-harness — DISMISSED** [review]

**Review by mohitg0795 — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger uts

**Comment by adivishy1** [comment]
trigger uts

**Review by utkarshchoubey-harness — APPROVED** [review]

**Review by mohitg0795 — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
