### PR TITLE
fix: [CDS-57984]: Sending Proper Formated failed responce from Delegate Side for instance sync V2

### PR DESCRIPTION
**Pull request by namantalaycha10**
…ate Side for instance sync V2

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45602)

### CODE REVIEW

**Review by abhinavsingh1196 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45602)* status: 2 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgInstanceSyncV2TaskExecutor.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/45602#-NRHwZvj8AYuCToFAnG5:-NRHwZvj8AYuCToFAnG6:b-wj8jm3) ([raw file](https://github.com/harness/harness-core/blob/097e77d3ebd80a971091d1a8f40791391904496c/260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgInstanceSyncV2TaskExecutor.java#L79)):*
> ```Java
>             trackedDeployment.getInfraMappingId(), trackedDeployment.getInfraMappingId(),
>             trackedDeployment.getTaskDetailsId());
>         responseBuilder.addInstanceData(InstanceSyncData.newBuilder()
> ```

why are we removing this?

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45602)* status: 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgInstanceSyncV2TaskExecutor.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/45602#-NRHwZvj8AYuCToFAnG5:-NRI6uxj7XQMvVVIuwrp:be5jouq) ([raw file](https://github.com/harness/harness-core/blob/097e77d3ebd80a971091d1a8f40791391904496c/260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgInstanceSyncV2TaskExecutor.java#L79)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

why are we removing this? 
</blockquote></details>

We shouldn't delete this but instead handle this on manager side

**Review by namantalaycha10 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45602)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45602)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
