### PR TITLE
feat: [PL-25907]: integration for account level ado connector

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
added params for account level ado connector

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34465)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 551 at r2](https://reviewable.io/reviews/harness/harness-core/34465#-N5-hHSB78F1-lFyoPiK:-N5-hHSB78F1-lFyoPiL:bug18c1) ([raw file](https://github.com/harness/harness-core/blob/e560787c606da4b88da26fe5908619a884156a53/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L551)):*
> ```Java
>       GetFileRequest getFileRequest, ScmGetFileResponseDTO scmGetFileResponseDTO, Scope scope) {
>     GitRepositoryDTOBuilder gitRepositoryDTOBuilder = GitRepositoryDTO.builder().name(getFileRequest.getRepoName());
>     if (getFileRequest.getGitConnectivityParams() != null) {
> ```

I see this is a repetitive block, can we move it into a private function. This way it will carry a clear understanding as well with it.

We can may be have a method saying getGitRepositoryDetails() or something

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 633 at r2](https://reviewable.io/reviews/harness/harness-core/34465#-N5-hZLXDuTI2eQ0T2nT:-N5-hZLXDuTI2eQ0T2nU:b9tr9mn) ([raw file](https://github.com/harness/harness-core/blob/e560787c606da4b88da26fe5908619a884156a53/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L633)):*
> ```Java
>   }
> 
>   private GitConnectivityParams convertGitConnectivityParamsProtoToRest(
> ```

This method name is wrong in its logical sense coz there's no "Rest". Lets simply name it gitConnectivityParamsMapper or getGitConnectivityParamsFromProtoRequest or anything simpler.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/34465#-N5-hvTJ5cY9fIDDORgq:-N5-hvTJ5cY9fIDDORgr:b-2oxvsi) ([raw file](https://github.com/harness/harness-core/blob/e560787c606da4b88da26fe5908619a884156a53/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L83)):*
> ```Java
>     ScmConnector scmConnector =
>         gitSyncConnectorHelper.getScmConnector(accountIdentifier, orgIdentifier, projectIdentifier, connectorRef);
>     if (gitConnectivityParams != null) {
> ```

same as before, lets move repetitive block out as a separate meaningful method.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmOrchestratorServiceImpl.java` line 106 at r2](https://reviewable.io/reviews/harness/harness-core/34465#-N5-iKBI7JVz0c87n-9T:-N5-iKBI7JVz0c87n-9U:b-k52844) ([raw file](https://github.com/harness/harness-core/blob/e560787c606da4b88da26fe5908619a884156a53/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmOrchestratorServiceImpl.java#L106)):*
> ```Java
>       }
>     }
>     return scmRequest.apply(scmClientManagerService);
> ```

This was correctly coded as Delegate, why did we change it to manager? By default everything should run via delegate. And only if manager is chosen as connectivity mode, then we run via manager.

**Comment by mohitg0795** [comment]
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 197 at r2](https://reviewable.io/reviews/harness/harness-core/34465#-N5-ijRa36IE5Z09JYwp:-N5-ijRb0PHABjenFEe2:b-k512vc) ([raw file](https://github.com/harness/harness-core/blob/e560787c606da4b88da26fe5908619a884156a53/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L197)):*
> ```protobuf
> 
> message GitConnectivityParams {
>   string repositoryProjectName = 1;
> ```

Lets keep it simply projectName. RepositoryProjectName just becomes too complex to understand and maintain.

**Comment by mohitg0795** [comment]
*[`970-ng-commons/src/main/java/io/harness/gitsync/beans/GitConnectivityParams.java` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/34465#-N5-itHpB3ZyPN6QjcPQ:-N5-itHpB3ZyPN6QjcPR:baf21en) ([raw file](https://github.com/harness/harness-core/blob/e560787c606da4b88da26fe5908619a884156a53/970-ng-commons/src/main/java/io/harness/gitsync/beans/GitConnectivityParams.java#L16)):*
> ```Java
> public class GitConnectivityParams {
>   @Parameter(description = "Provide repository's project name in case of Azure repo Connector.")
>   String repositoryProjectName;
> ```

Lets keep it simply projectName, as suggested before.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34465)* status: 24 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 551 at r2](https://reviewable.io/reviews/harness/harness-core/34465#-N5-hHSB78F1-lFyoPiK:-N5-ryk3AgFucRQaoOOZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e560787c606da4b88da26fe5908619a884156a53/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L551)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I see this is a repetitive block, can we move it into a private function. This way it will carry a clear understanding as well with it.

We can may be have a method saying getGitRepositoryDetails() or something
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 633 at r2](https://reviewable.io/reviews/harness/harness-core/34465#-N5-hZLXDuTI2eQ0T2nT:-N5-rzn02sDzlAG1aweh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e560787c606da4b88da26fe5908619a884156a53/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L633)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This method name is wrong in its logical sense coz there's no "Rest". Lets simply name it gitConnectivityParamsMapper or getGitConnectivityParamsFromProtoRequest or anything simpler.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/34465#-N5-hvTJ5cY9fIDDORgq:-N5-s-Rs4-T4LKvfmmdU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e560787c606da4b88da26fe5908619a884156a53/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L83)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as before, lets move repetitive block out as a separate meaningful method.
</blockquote></details>

Done.
___
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 197 at r2](https://reviewable.io/reviews/harness/harness-core/34465#-N5-ijRa36IE5Z09JYwp:-N5-s0vP3r1jV958xuNl:bg2wx36) ([raw file](https://github.com/harness/harness-core/blob/e560787c606da4b88da26fe5908619a884156a53/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L197)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets keep it simply projectName. RepositoryProjectName just becomes too complex to understand and maintain.
</blockquote></details>

I don't think it's complex to understand, we already have a field name projectId, it became more confusing if we write projrct name only.
___
*[`970-ng-commons/src/main/java/io/harness/gitsync/beans/GitConnectivityParams.java` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/34465#-N5-itHpB3ZyPN6QjcPQ:-N5-sGz12SWgp1ohBmlM:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/e560787c606da4b88da26fe5908619a884156a53/970-ng-commons/src/main/java/io/harness/gitsync/beans/GitConnectivityParams.java#L16)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets keep it simply projectName, as suggested before.
</blockquote></details>

same as above
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmOrchestratorServiceImpl.java` line 106 at r2](https://reviewable.io/reviews/harness/harness-core/34465#-N5-iKBI7JVz0c87n-9T:-N5-sIVY3uqzsEGUFfTw:b-6wdvw8) ([raw file](https://github.com/harness/harness-core/blob/e560787c606da4b88da26fe5908619a884156a53/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmOrchestratorServiceImpl.java#L106)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This was correctly coded as Delegate, why did we change it to manager? By default everything should run via delegate. And only if manager is chosen as connectivity mode, then we run via manager.
</blockquote></details>

it was changed by mistake

**Comment by mohitg0795** [comment]
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 197 at r2](https://reviewable.io/reviews/harness/harness-core/34465#-N5-ijRa36IE5Z09JYwp:-N5-szpD0UDAfw_wbTRm:b1gflxi) ([raw file](https://github.com/harness/harness-core/blob/e560787c606da4b88da26fe5908619a884156a53/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L197)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

I don't think it's complex to understand, we already have a field name projectId, it became more confusing if we write projrct name only.
</blockquote></details>

It doesn't have any meaning in itself, which is the issue. You can may be replace it with gitProjectName if that sounds better or we can check with team on it for better suggestions.

**Comment by mohitg0795** [comment]
*[`970-ng-commons/src/main/java/io/harness/gitsync/beans/GitConnectivityParams.java` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/34465#-N5-itHpB3ZyPN6QjcPQ:-N5-tK3gBf3Xys9ReZcr:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/e560787c606da4b88da26fe5908619a884156a53/970-ng-commons/src/main/java/io/harness/gitsync/beans/GitConnectivityParams.java#L16)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

same

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 84 at r3](https://reviewable.io/reviews/harness/harness-core/34465#-N5-tglxES7JMl7fHlmI:-N5-tglxES7JMl7fHlmJ:b-n8tgt2) ([raw file](https://github.com/harness/harness-core/blob/c85484b0ace824cdbfb87346082f9f901741b888/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L84)):*
> ```Java
>         gitSyncConnectorHelper.getScmConnector(accountIdentifier, orgIdentifier, projectIdentifier, connectorRef);
>     if (gitConnectivityParams != null) {
>       scmConnector.setGitConnectionUrl(scmConnector.getGitConnectionUrl(
> ```

Does it impact anything if someone passes empty gitConnectivityParams?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34465)* status: 24 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 84 at r3](https://reviewable.io/reviews/harness/harness-core/34465#-N5-tglxES7JMl7fHlmI:-N5-zDmoE2yh6G0XeBeD:bxg2i41) ([raw file](https://github.com/harness/harness-core/blob/c85484b0ace824cdbfb87346082f9f901741b888/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L84)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Does it impact anything if someone passes empty gitConnectivityParams?
</blockquote></details>

yes, it will
___
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 197 at r2](https://reviewable.io/reviews/harness/harness-core/34465#-N5-ijRa36IE5Z09JYwp:-N5-zGZk9ETlFZLADFKx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e560787c606da4b88da26fe5908619a884156a53/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L197)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

It doesn't have any meaning in itself, which is the issue. You can may be replace it with gitProjectName if that sounds better or we can check with team on it for better suggestions. 
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/gitsync/beans/GitConnectivityParams.java` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/34465#-N5-itHpB3ZyPN6QjcPQ:-N5-zH676WHlRlhE0V9_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e560787c606da4b88da26fe5908619a884156a53/970-ng-commons/src/main/java/io/harness/gitsync/beans/GitConnectivityParams.java#L16)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34465)* status: 24 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 84 at r3](https://reviewable.io/reviews/harness/harness-core/34465#-N5-tglxES7JMl7fHlmI:-N50-gFj2ShPsDtUX2NN:b9fekzn) ([raw file](https://github.com/harness/harness-core/blob/c85484b0ace824cdbfb87346082f9f901741b888/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L84)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

yes, it will
</blockquote></details>

I mean to just confirm that it shouldn't result in any unwanted errors if gitConnectivityParams isn't null but an empty object. If thats the case, then we are good.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34465)* status: 24 file(s) to review. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 84 at r3](https://reviewable.io/reviews/harness/harness-core/34465#-N5-tglxES7JMl7fHlmI:-N503BQe0AvJEaZtBS4R:b-62p3tx) ([raw file](https://github.com/harness/harness-core/blob/c85484b0ace824cdbfb87346082f9f901741b888/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L84)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I mean to just confirm that it shouldn't result in any unwanted errors if gitConnectivityParams isn't null but an empty object. If thats the case, then we are good.
</blockquote></details>

yes, so added check, so that empty object will not be considered

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 6 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34465)* status: 24 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/CreatePRRequest.java` line 35 at r5](https://reviewable.io/reviews/harness/harness-core/34465#-N50528u68FslRq84XqT:-N50528u68FslRq84XqU:b6ql60f) ([raw file](https://github.com/harness/harness-core/blob/229cc8e235b83b2e431bd885cf37f56028de1303/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/CreatePRRequest.java#L35)):*
> ```Java
>   String title;
>   @Parameter(description = GitSyncApiConstants.GIT_CONNECTIVITY_PARAM_MESSAGE)
>   GitConnectivityParams gitConnectivityParams;
> ```

When I read the name GitConnectivity I thought it is only used for test connection. Can we use GitRepoDetails or something ?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34465)* status: 24 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/CreatePRRequest.java` line 35 at r5](https://reviewable.io/reviews/harness/harness-core/34465#-N50528u68FslRq84XqT:-N50CJby4mG0UFvfMQVT:bx688ba) ([raw file](https://github.com/harness/harness-core/blob/229cc8e235b83b2e431bd885cf37f56028de1303/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/CreatePRRequest.java#L35)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

When I read the name GitConnectivity I thought it is only used for test connection. Can we use GitRepoDetails or something ? 
</blockquote></details>

It will contain all the extra fields, that will be needed to connect to git repos, maybe moving forward, in any ther provider, we will need any other field, that also will come under it

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34465)* status: 24 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 8 of 21 files at r1, 4 of 5 files at r2, 1 of 3 files at r3, 3 of 4 files at r4, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34465)* status: 24 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by DeepakPatankar — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34465)* status: 24 file(s) to review. 1 of 2 approvals obtained.

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 21 files at r1, 4 of 5 files at r2, 1 of 3 files at r3, 13 of 13 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34465#-:-N54Pk3SCf15LVdfgtvh:bnfp4nl)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 13 of 13 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34465)* status: :shipit: complete! ✓

**Pull request merged**
