### PR TITLE
feat: [PL-30869]: Fetch audit events for streaming destination

### PR DESCRIPTION
**Pull request by nishantsaini20**
## Describe your changes
As part of audit event streaming, this PR covers fetching audit events from ng audit DB for a given streaming destination. 
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42490)

### CODE REVIEW

**Comment by piyush-harness** [comment]
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/AuditEventRepositoryImpl.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/42490#-NLVouupAUrWr8QhxpdT:-NLVouupAUrWr8QhxpdU:bfqtcgs) ([raw file](https://github.com/harness/harness-core/blob/70c7113a2414452eaac0fd56577d87404aa72963/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/AuditEventRepositoryImpl.java#L33)):*
> ```Java
>     Query query =
>         new Query(criteria).with(sort).cursorBatchSize(batchConfig.getCursorBatchSize()).limit(batchConfig.getLimit());
>     return mongoTemplate.find(query, AuditEvent.class);
> ```

Why not return a cursor and do hasNext()
? It will be efficient we will use only one connection per job.

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42490)* status: 19 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/AuditEventRepositoryImpl.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/42490#-NLVouupAUrWr8QhxpdT:-NL_x-3Z9lwILf_u8oOJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/70c7113a2414452eaac0fd56577d87404aa72963/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/AuditEventRepositoryImpl.java#L33)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why not return a cursor and do hasNext()
? It will be efficient we will use only one connection per job.
</blockquote></details>

Done.

**Comment by piyush-harness** [comment]
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/entities/BatchFailureInfo.java` line 19 at r3](https://reviewable.io/reviews/harness/harness-core/42490#-NLa1Guv7aoHscNolteh:-NLa1Guw2WCEI9Z8q89x:b-l8ji3a) ([raw file](https://github.com/harness/harness-core/blob/c31e51cf98a62da658f0e0af780ee4c584b3372b/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/entities/BatchFailureInfo.java#L19)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> public class BatchFailureInfo {
>   String errorCode;
> ```

We should store more information like batchId, time , recordsProcessed before failure etc

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 15 of 18 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42490)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/services/impl/StreamingBatchServiceImpl.java` line 73 at r3](https://reviewable.io/reviews/harness/harness-core/42490#-NLa4fak0uBdz1R-x3JY:-NLa4fak0uBdz1R-x3JZ:byyeni8) ([raw file](https://github.com/harness/harness-core/blob/c31e51cf98a62da658f0e0af780ee4c584b3372b/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/services/impl/StreamingBatchServiceImpl.java#L73)):*
> ```Java
>       return createInitialBatch(streamingDestination, timestamp);
>     }
>     @NotNull BatchStatus status = lastStreamingBatch.get().getStatus();
> ```

Does this annotation works here?

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42490)* status: 19 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/entities/BatchFailureInfo.java` line 19 at r3](https://reviewable.io/reviews/harness/harness-core/42490#-NLa1Guv7aoHscNolteh:-NLa5bEY-vukXwkAcxtO:b-wbbehl) ([raw file](https://github.com/harness/harness-core/blob/c31e51cf98a62da658f0e0af780ee4c584b3372b/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/entities/BatchFailureInfo.java#L19)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

We should store more information like batchId, time , recordsProcessed before failure etc
</blockquote></details>

That info is already part of StreamingBatch
BatchFailureInfo is one of the field of StreamingBatch
___
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/services/impl/StreamingBatchServiceImpl.java` line 73 at r3](https://reviewable.io/reviews/harness/harness-core/42490#-NLa4fak0uBdz1R-x3JY:-NLa5KYQ1mZUVkm_AMr7:b-85hy4r) ([raw file](https://github.com/harness/harness-core/blob/c31e51cf98a62da658f0e0af780ee4c584b3372b/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/services/impl/StreamingBatchServiceImpl.java#L73)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Does this annotation works here?
</blockquote></details>

This will be removed in subsequent PRs

**Review by piyush-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42490)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 14 of 18 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42490)* status: :shipit: complete! ✓

**Pull request merged**
