### PR TITLE
[feat]: [CDS-35577] Implement get-params endpoint for CF NG

### PR DESCRIPTION
**Pull request by nassergonzalez**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32054)

### CODE REVIEW

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32054)* status: 20 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java, line 66 at r2](https://reviewable.io/reviews/harness/harness-core/32054#-MzygmxA1gIbqQgyFgaO:-MzzEmOp9zXSc3boGfT7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3dd096d257084364a271a53dd04481f7ff65367/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L66)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

nickname could be CFParametersForAws or simply CoudformationParameters
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceService.java, line 22 at r2](https://reviewable.io/reviews/harness/harness-core/32054#-Mzz98Um7kw98Xaf3j00:-MzzH-y-8mMJOSi-g6M1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3dd096d257084364a271a53dd04481f7ff65367/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceService.java#L22)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's keep consistency and call it AwsResourceService, the same for implementation.
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceService.java, line 70 at r2](https://reviewable.io/reviews/harness/harness-core/32054#-MzyzHoJ8A6SiKQFYUo8:-MzzHGkhDPMHsXOPjLGu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3dd096d257084364a271a53dd04481f7ff65367/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceService.java#L70)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's call it getCFparametrsKeys
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java, line 61 at r2](https://reviewable.io/reviews/harness/harness-core/32054#-Mzz0wZmDMoagBIqW_r2:-MzzHmftAm9JCGiYLYia:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ec8e7e073661a8f9ae55112e17d48cfc988a862c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java#L61)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's keep the empty line
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java, line 69 at r2](https://reviewable.io/reviews/harness/harness-core/32054#-Mzz9JoeEchJAxTFEH-h:-MzzHTp07JkVpBXSrAH7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3dd096d257084364a271a53dd04481f7ff65367/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java#L69)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Why not to inject it the same way as we do for GitResourceServiceHelper?
</blockquote></details>

Done.

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 8 of 19 files at r2, 1 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32054)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java, line 69 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2-fK30CBbD-SCwPDo:-N-2-fK30CBbD-SCwPDp:becbt2i) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L69)):*
> ```Java
>   public ResponseDTO<List<AwsCFTemplateParamsData>>
>   listCFParameterKeys(@QueryParam("type") @NotNull String type, @QueryParam("region") @NotNull String region,
>       @QueryParam("isBrach") boolean isBranch, @QueryParam("branch") String branch,
> ```

@QueryParam("isBrach") -> @QueryParam("isBranch")



_Code quote:_
```Java
@QueryParam("isBrach")
```
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java, line 37 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2DjR2-us03V16hp8K:-N-2DjR2-us03V16hp8L:bmrwd90) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/125-cd-nextgen/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java#L37)):*
> ```Java
> import java.util.Optional;
> 
> public class GitResourceServiceHelper {
> ```

add @OwnedBy and @Singleton
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java, line 39 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2LjUx22Q0qeRKuYnx:-N-2LjUx22Q0qeRKuYny:b-qe9xhx) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/125-cd-nextgen/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java#L39)):*
> ```Java
> public class GitResourceServiceHelper {
>   private final ConnectorService connectorService;
>   private final GitConfigAuthenticationInfoHelper gitConfigAuthenticationInfoHelper;
> ```

Add empty line
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java, line 47 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2LlOQ2X9K7628K-TY:-N-2LlOQ2X9K7628K-TZ:bh7vjpa) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/125-cd-nextgen/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java#L47)):*
> ```Java
>   }
> 
>   public BaseNGAccess getBaseNGAccess(String accountId, String orgIdentifier, String projectIdentifier) {
> ```

this method is not used
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/common/resources/GitResourceServiceHelperTest.java, line 41 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2MkKI1nUDenS-aV8y:-N-2MkKI1nUDenS-aV8z:b-qw0d4v) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/125-cd-nextgen/src/test/java/io/harness/cdng/common/resources/GitResourceServiceHelperTest.java#L41)):*
> ```Java
> import org.mockito.MockitoAnnotations;
> 
> public class GitResourceServiceHelperTest extends CategoryTest {
> ```

@OwnedBy
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/common/resources/GitResourceServiceHelperTest.java, line 64 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2MGz34A8OK24LsDD-:-N-2MGz34A8OK24LsDD0:brh6tf2) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/125-cd-nextgen/src/test/java/io/harness/cdng/common/resources/GitResourceServiceHelperTest.java#L64)):*
> ```Java
>         "foo", BaseNGAccess.builder().accountIdentifier("bar").orgIdentifier("baz").projectIdentifier("zar").build());
>     assertThat(response.getConnectorType()).isEqualTo(ConnectorType.GIT);
>   }
> ```

let's have an empty line between methods, it's more readable.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsCFDelegateTaskHelper.java, line 43 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2QUaW4UNOS2QmSUlI:-N-2QUaYE_HauB4AXen4:bjuwa7y) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsCFDelegateTaskHelper.java#L43)):*
> ```Java
> import lombok.extern.slf4j.Slf4j;
> 
> @AllArgsConstructor(access = AccessLevel.PACKAGE, onConstructor = @__({ @Inject }))
> ```

Let's stick with only one way of injecting, let's use field injection.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsDelegateTask.java, line 48 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2QktL5xbWoszZoG9b:-N-2QktL5xbWoszZoG9c:ba5ulhv) ([raw file](https://github.com/harness/harness-core/blob/ec8e7e073661a8f9ae55112e17d48cfc988a862c/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsDelegateTask.java#L48)):*
> ```Java
>   @Inject private AwsS3DelegateTaskHelper awsS3DelegateTaskHelper;
>   @Inject private AwsIAMDelegateTaskHelper awsIAMDelegateTaskHelper;
> ```

Let's keep the empty line
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsDelegateTask.java, line 84 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2R2e5BEwcLQS_9hrQ:-N-2R2e5BEwcLQS_9hrR:b-r0jbtb) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsDelegateTask.java#L84)):*
> ```Java
>       case CF_LIST_PARAMS:
>         final AwsCFTaskParamsRequest awsCFTaskParams = (AwsCFTaskParamsRequest) parameters;
>         return awsCFDelegateTaskHelper.getCFParamsList(awsCFTaskParams);
> ```

we can do "return awsCFDelegateTaskHelper.getCFParamsList((AwsCFTaskParamsRequest) parameters);" and remove the line above.
___
*[930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/AwsCFDelegateTaskHelperTest.java, line 53 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2RK1q6kvw9svWe_9F:-N-2RK1q6kvw9svWe_9G:bpuawzu) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/AwsCFDelegateTaskHelperTest.java#L53)):*
> ```Java
> import org.mockito.Mock;
> import org.mockito.MockitoAnnotations;
> ```

@Owned
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsCFTaskParamsRequest.java, line 38 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2ZYCy-Rxfy7l3ZW2v:-N-2StxR3IP6l-wPe99L:byugpx3) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsCFTaskParamsRequest.java#L38)):*
> ```Java
>   public List<ExecutionCapability> fetchRequiredExecutionCapabilities(ExpressionEvaluator maskingEvaluator) {
>     List<ExecutionCapability> capabilityList = new ArrayList<>();
>     if (fileStoreType.equalsIgnoreCase("git")) {
> ```

Let's have a constant for it. 
___
*[960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java, line 262 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2ZE_SB_Zx3ALEfiQM:-N-2ZE_SB_Zx3ALEfiQN:b-ligf81) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L262)):*
> ```Java
>              new CloseableAmazonWebServiceClient(getAmazonCloudFormationClient(Regions.fromName(region), awsConfig))) {
>       GetTemplateSummaryRequest request = new GetTemplateSummaryRequest();
>       if ("s3".equalsIgnoreCase(type)) {
> ```

Let's define some constants for type and use the across the flow (manager and delegate side)
___
*[960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java, line 267 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2WbR9C2Zne_42qT0T:-N-2WbR9C2Zne_42qT0U:bjqdnwg) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L267)):*
> ```Java
>         request.withTemplateBody(gitDataFile);
>       } else {
>         request.withTemplateBody(data);
> ```

we can make it simple, once both gitDataFile ,and data are template body we can pass only one parameter to this method and set it to request.templateBody if it is not s3
___
*[960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java, line 297 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2WEiZ7z-AxhrnkPy9:-N-2WEiZ7z-AxhrnkPyA:b-qjkg44) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L297)):*
> ```Java
>     return new AmazonCloudFormationWaiters(closeableAmazonCloudFormationClient.getClient());
>   }
>   public void printStackEvents(String region, String stackId, AwsInternalConfig awsConfig, LogCallback callback) {
> ```

why do we need this method?



_Code quote:_
```Java
public void printStackEvents
```
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceServiceImpl.java, line 159 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-24Mtz24VA1IOAOZRj:-N-24Mu-0kFs4-9zBNJO:b-9lwqm) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceServiceImpl.java#L159)):*
> ```Java
>                                         .build();
> 
>     AwsCFTaskResponse response = executeSyncTask(params, access);
> ```

That's not correct, in  "executeSyncTask(params, access)" we cast response to "AwsCFTaskResponse" then in "getCFTaskExecutionResponse(response)" we check if it is an instance of ErrorNotifyResponseData.
you can follow the same approach as on "protected AwsIAMRolesResponse executeSyncTask(AwsTaskParams awsTaskParams, BaseNGAccess baseNGAccess)". 
Let's have a test for it when response data is instance of ErrorNotifyResponseData.

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32054)* status: Some of the checks are too old. 13 file(s) to review. 1 change requests. 16. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java, line 69 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2-fK30CBbD-SCwPDo:-N-31Ajo7xbf91HAtX7q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L69)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

@QueryParam("isBrach") -> @QueryParam("isBranch")
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java, line 37 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2DjR2-us03V16hp8K:-N-31s5A8LfDEpyouYDp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/125-cd-nextgen/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java#L37)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

add @OwnedBy and @Singleton
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java, line 39 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2LjUx22Q0qeRKuYnx:-N-31yaV19opaGIULP_3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/125-cd-nextgen/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java#L39)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Add empty line
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java, line 47 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2LlOQ2X9K7628K-TY:-N-327OTD4vA0H1UhYyN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/125-cd-nextgen/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java#L47)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

this method is not used
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/common/resources/GitResourceServiceHelperTest.java, line 41 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2MkKI1nUDenS-aV8y:-N-32EpyDGjuQvI29GhZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/125-cd-nextgen/src/test/java/io/harness/cdng/common/resources/GitResourceServiceHelperTest.java#L41)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

@OwnedBy
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/common/resources/GitResourceServiceHelperTest.java, line 64 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2MGz34A8OK24LsDD-:-N-32io7AeGVXOLtnHtc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/125-cd-nextgen/src/test/java/io/harness/cdng/common/resources/GitResourceServiceHelperTest.java#L64)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's have an empty line between methods, it's more readable.
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsCFDelegateTaskHelper.java, line 43 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2QUaW4UNOS2QmSUlI:-N-32vFKCB68ChISKFWd:b-7ejpk1) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsCFDelegateTaskHelper.java#L43)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Let's stick with only one way of injecting, let's use field injection.
</blockquote></details>

That is me using that kind of inject because I saw it in another file similar to this one. I actually don't know what would be the substitute for this constructor tag
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsDelegateTask.java, line 48 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2QktL5xbWoszZoG9b:-N-33EVLD4p9o6h_2EZJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ec8e7e073661a8f9ae55112e17d48cfc988a862c/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsDelegateTask.java#L48)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Let's keep the empty line
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsDelegateTask.java, line 84 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2R2e5BEwcLQS_9hrQ:-N-33S7230A8g7gHqdc2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsDelegateTask.java#L84)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

we can do "return awsCFDelegateTaskHelper.getCFParamsList((AwsCFTaskParamsRequest) parameters);" and remove the line above.
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/AwsCFDelegateTaskHelperTest.java, line 53 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2RK1q6kvw9svWe_9F:-N-33cVIEDELzxbeBNdH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/AwsCFDelegateTaskHelperTest.java#L53)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

@Owned
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsCFTaskParamsRequest.java, line 38 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2ZYCy-Rxfy7l3ZW2v:-N-33pRx9e86M3s5KRji:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsCFTaskParamsRequest.java#L38)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Let's have a constant for it. 
</blockquote></details>

Done.
___
*[960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java, line 262 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2ZE_SB_Zx3ALEfiQM:-N-36Rul7EspyXTmCa2g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L262)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Let's define some constants for type and use the across the flow (manager and delegate side)
</blockquote></details>

Done.
___
*[960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java, line 267 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2WbR9C2Zne_42qT0T:-N-3G2SZDUBz4DLMiJ-W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L267)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

we can make it simple, once both gitDataFile ,and data are template body we can pass only one parameter to this method and set it to request.templateBody if it is not s3
</blockquote></details>

Done.
___
*[960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java, line 297 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-2WEiZ7z-AxhrnkPy9:-N-36z3A8Qzh4tG8ZlUS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L297)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

why do we need this method?
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceServiceImpl.java, line 159 at r4](https://reviewable.io/reviews/harness/harness-core/32054#-N-24Mtz24VA1IOAOZRj:-N-MmC_n7LJr6jV40inW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/582dee5dafa93fe6def8ccdc160a4041de538b5c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceServiceImpl.java#L159)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

That's not correct, in  "executeSyncTask(params, access)" we cast response to "AwsCFTaskResponse" then in "getCFTaskExecutionResponse(response)" we check if it is an instance of ErrorNotifyResponseData.
you can follow the same approach as on "protected AwsIAMRolesResponse executeSyncTask(AwsTaskParams awsTaskParams, BaseNGAccess baseNGAccess)". 
Let's have a test for it when response data is instance of ErrorNotifyResponseData.
</blockquote></details>

Done.

**Review by tmacari-harness — COMMENTED** [review]
> Reviewed 12 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32054)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32054)* status: :shipit: complete! ✓

**Pull request merged**
