### PR TITLE
[fix]: [PIE-8601]: Always pass runtime input checks in preflight if pipeline has no runtime inputs

### PR DESCRIPTION
**Pull request by namanvermah**
In preflight checks, we longer throw an error if runtime input yaml has a field that is not an input in the Pipeline. However, the case where if pipeline has no runtime inputs, but user still provides a runtime input yaml, was failing. This PR fixes this case

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44403)

### CODE REVIEW

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44403)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44403)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/InputSetErrorsHelper.java` line 164 at r2](https://reviewable.io/reviews/harness/harness-core/44403#-NPHqKStDU_gs7_Yf5s4:-NPHqKStDU_gs7_Yf5s5:b-hj7hvy) ([raw file](https://github.com/harness/harness-core/blob/84b822e70716da6919d77cf19149885231ed6107/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/InputSetErrorsHelper.java#L164)):*
> ```Java
>     Map<FQN, String> errorMap = new LinkedHashMap<>();
>     Set<FQN> inputSetFQNs = new LinkedHashSet<>(inputSetConfig.getFqnToValueMap().keySet());
>     if (!checkOnlyValidators && (templateConfig == null || EmptyPredicate.isEmpty(templateConfig.getFqnToValueMap()))) {
> ```

(templateConfig == null || EmptyPredicate.isEmpty(templateConfig.getFqnToValueMap()) is already in above if condition



_Code quote:_
```Java
(templateConfig == null || EmptyPredicate.isEmpty(templateConfig.getFqnToValueMap()))
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44403)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44403)* status: :shipit: complete! ✓

**Pull request merged**
