### PR TITLE
fix: [CDS-43398]: ensuring response body is closed in all cases

### PR DESCRIPTION
**Pull request by shubham-in10se**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37938)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37938)

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37938)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/37938#-NCwOAHG1OZ20B--mOjN:-NCwOAHH-CI4KIW6Ua_C:b-va8wuj) ([raw file](https://github.com/harness/harness-core/blob/8b9f9e5cd66694a6dd412301fb00d4e4b8cc2344/970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java#L86)):*
> ```Java
>           StringUtils.isEmpty(errorMessage) ? defaultErrorMessage : errorMessage, restResponse.getMetadata());
>     } catch (InvalidRequestException e) {
>       log.error("Invalid request exception for response: [{}]", response, e);
> ```

Why this log line

**Review by shubham-in10se — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37938)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/37938#-NCwOAHG1OZ20B--mOjN:-NCxMOzhB1tWCyY5WuQC:brpmqc3) ([raw file](https://github.com/harness/harness-core/blob/8b9f9e5cd66694a6dd412301fb00d4e4b8cc2344/970-ng-commons/src/main/java/io/harness/remote/client/NGRestUtils.java#L86)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this log line
</blockquote></details>

removed.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37938#-:-NCxS-DA747ODUu0wJBS:bnfp4nl)* status: 1. unresolved discussions.

**Review by ankit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37938)* status: :shipit: complete! ✓

**Pull request merged**
