### PR TITLE
feat: [CDS-49005]: Show last pipeline execution id time in the service dashboard instead of pod deployed time

### PR DESCRIPTION
**Pull request by meenaravichandran1**
## Describe your changes
Currently, we show the pod deployed time under the pipeline execution link. This change is to start showing pipeline execution time under the link. And the pod deployed time should be shown in the instance detail view.
- one other change is to start including agent id in the request for fetching instance details, since multiple agents can have applications related to same service (this change is reverted because the response strucutre has been changed and with the new response this should work as expected)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42053)

### CODE REVIEW

**Review by Abhishek-CDC — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42053)* status: 22 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java` line 376 at r3](https://reviewable.io/reviews/harness/harness-core/42053#-NKXHFyfBSxPoB1rt1Kc:-NKXHFyfBSxPoB1rt1Kd:b2sspf9) ([raw file](https://github.com/harness/harness-core/blob/5dc4b9f87c904a0c2bb5ff9bb8bf916772b80d0a/120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java#L376)):*
> ```Java
>       @QueryParam(NGCommonEntityConstants.PIPELINE_EXECUTION_ID) String pipelineExecutionId,
>       @QueryParam(NGCommonEntityConstants.LAST_DEPLOYED_AT) Long lastDeployedAt,
>       @QueryParam(NGCommonEntityConstants.AGENT_IDENTIFIER) String agentIdentifier) {
> ```

Is it possible to have cluster belonging to different agents have same cluster id?

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42053)* status: 22 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java` line 376 at r3](https://reviewable.io/reviews/harness/harness-core/42053#-NKXHFyfBSxPoB1rt1Kc:-NKZ0KKb3FcKr3zP8luZ:b3dyxk4) ([raw file](https://github.com/harness/harness-core/blob/5dc4b9f87c904a0c2bb5ff9bb8bf916772b80d0a/120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java#L376)):*
<details><summary><i>Previously, Abhishek-CDC (Abhishek) wrote…</i></summary><blockquote>

Is it possible to have cluster belonging to different agents have same cluster id?
</blockquote></details>

yes, that is possible

**Review by Abhishek-CDC — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42053)* status: 22 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java` line 376 at r3](https://reviewable.io/reviews/harness/harness-core/42053#-NKXHFyfBSxPoB1rt1Kc:-NKm2Id5-ahUPTYxXi33:b-roqvud) ([raw file](https://github.com/harness/harness-core/blob/5dc4b9f87c904a0c2bb5ff9bb8bf916772b80d0a/120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java#L376)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

yes, that is possible
</blockquote></details>

current logic we have for grouping consider only cluster id and not the agent id associated with it. first we should treat instances having same cluster id but different agent id as separate entities while grouping and then proceed with this.

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42053)* status: 22 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java` line 376 at r3](https://reviewable.io/reviews/harness/harness-core/42053#-NKXHFyfBSxPoB1rt1Kc:-NKnVNwjCzzOmjOyLIfs:bg6i5ci) ([raw file](https://github.com/harness/harness-core/blob/5dc4b9f87c904a0c2bb5ff9bb8bf916772b80d0a/120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java#L376)):*
<details><summary><i>Previously, Abhishek-CDC (Abhishek) wrote…</i></summary><blockquote>

current logic we have for grouping consider only cluster id and not the agent id associated with it. first we should treat instances having same cluster id but different agent id as separate entities while grouping and then proceed with this.
</blockquote></details>

I feel it is not required, we are not worried about different agents here (confirmed with @samarthwadhwa sometime back) . Agent is internal. The reason we are adding agent id to the instance metadata call is that, clusters can belong to different agents and hence we can have multiple records for them. 

The only reason is to filter out multiple records (in the instance metadata call). We are not worried about grouping based on agents.

**Review by Abhishek-CDC — APPROVED** [review]
> Reviewed 6 of 18 files at r1, 2 of 16 files at r2, 14 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42053)* status: 22 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 6 of 18 files at r1, 2 of 16 files at r2, 14 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42053)* status: :shipit: complete! ✓

**Pull request merged**
