### PR TITLE
feat: [CDS-86777]: Combine node execution metrics for module and stepType and add cache for planExecution metrics

### PR DESCRIPTION
**Pull request by Y0709**
In this pr we are adding caching for the active pipeline executions count metric as current when for some account the no of running execution becomes 0 it is not reflected via prometheus hence in case for no running executions we have to seperately populate the count for that account as 0

Screenshot 2023-12-13 at 2 01 52 AM

Also we have combined the node executions per module and steptype metrics in one 

Screenshot 2023-12-14 at 3 41 21 PM

Also tested if cache is properly working for this combined metric 

Screenshot 2023-12-14 at 3 46 01 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56779)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger ut2, ut5, ut6, ut7, ut8, ut9

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56779)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionMonitorServiceImpl.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/56779#-NlfdgraEBoNiCe4UhRX:-NlfdgraEBoNiCe4UhRY:b-ndqp15) ([raw file](https://github.com/harness/harness-core/blob/58596864257557f970c646394cb8f9f9154d9f23/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionMonitorServiceImpl.java#L106)):*
> ```Java
>     }
>     populateZeroCount(currentModulesWithStepTypes,
>         PmsEventMonitoringConstants.MODULE + "_" + PmsEventMonitoringConstants.STEP_TYPE,
> ```

we should append one more const here so it doesn't collide with something else in cache
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionMonitorServiceImpl.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/56779#-NlfdrVz877mssZms08k:-NlfdrVz877mssZms08l:bhhee4r) ([raw file](https://github.com/harness/harness-core/blob/58596864257557f970c646394cb8f9f9154d9f23/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionMonitorServiceImpl.java#L125)):*
> ```Java
>   }
> 
>   private Map<String, String> getMetricContextMap(String key, String nodeExecutionActiveExecutionCountMetricName) {
> ```

why we need to do this again? cant caller populate and send this?

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56779)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger ut2

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56779)* status: <span>:shipit:</span> complete! ✓

**Comment by Y0709** [comment]
trigger review

**Pull request merged**
