### PR TITLE
feat: [CDS-35315]: Add visualization API

### PR DESCRIPTION
**Pull request by puthrayaharness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32223)

### CODE REVIEW

**Comment by puthrayaharness** [comment]
trigger messagecheck

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32223)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java, line 150 at r1](https://reviewable.io/reviews/harness/harness-core/32223#-N-Wc61v-de88XXw0i1E:-N-Wc61v-de88XXw0i1F:b-84udnh) ([raw file](https://github.com/harness/harness-core/blob/88d6c515fb7ccd1c6f2810046fafb802572ec115/100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java#L150)):*
> ```Java
>   public StreamingOutput discoverImg(String accountId, String appId, String entityId, NGMigrationEntityType entityType)
>       throws IOException {
>     Path path = Files.createTempDirectory("viz-output");
> ```

Can we put this constant in a constants file(already exists)?
___
*[100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java, line 151 at r1](https://reviewable.io/reviews/harness/harness-core/32223#-N-WcEGp0KZ2gooESGgO:-N-WcEGp0KZ2gooESGgP:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/88d6c515fb7ccd1c6f2810046fafb802572ec115/100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java#L151)):*
> ```Java
>       throws IOException {
>     Path path = Files.createTempDirectory("viz-output");
>     String imgPath = path.toFile().getAbsolutePath() + "/viz.png";
> ```

ditto

**Review by puthrayaharness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32223)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java, line 150 at r1](https://reviewable.io/reviews/harness/harness-core/32223#-N-Wc61v-de88XXw0i1E:-N-WeOEV3qqF36PWg56p:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/88d6c515fb7ccd1c6f2810046fafb802572ec115/100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java#L150)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Can we put this constant in a constants file(already exists)?
</blockquote></details>

Done.
___
*[100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java, line 151 at r1](https://reviewable.io/reviews/harness/harness-core/32223#-N-WcEGp0KZ2gooESGgO:-N-WeOhHE5ogcVd7UmtR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/88d6c515fb7ccd1c6f2810046fafb802572ec115/100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java#L151)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32223)* status: :shipit: complete! ✓

**Pull request merged**
