### PR TITLE
feat: [STO-3513]: Security Stage definitions

### PR DESCRIPTION
**Pull request by r0610205**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32266)

### CODE REVIEW

**Comment by r0610205** [comment]
trigger messagecheck

**Review by williamwissemann — DISMISSED** [review]

**Review by atmollo-harness — DISMISSED** [review]

**Review by williamwissemann — APPROVED** [review]

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 9 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32266)* status: :shipit: complete! ✓

**Comment by r0610205** [comment]
trigger ti0

**Review by atmollo-harness — APPROVED** [review]

**Comment by r0610205** [comment]
trigger ti0

**Pull request merged**
