### PR TITLE
[feat]: [CDP-20330]: handle artifactory config and var files on terra…

### PR DESCRIPTION
**Pull request by tmacari-harness**
[feat]: [CDP-20330]: handle artifactory config and var files on terraform task handlers

[CDP-20330]: https://harness.atlassian.net/browse/CDP-20330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30478)

### CODE REVIEW

**Review by nassergonzalez — APPROVED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30478)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30478)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java, line 542 at r1](https://reviewable.io/reviews/harness/harness-core/30478#-MutnT_I6iVDas2Yh2Zf:-MutnT_I6iVDas2Yh2Zg:b-h1xvwh) ([raw file](https://github.com/harness/harness-core/blob/80e1d6e3dd33ed47c943aaf109d897dad2179cd8/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L542)):*
> ```Java
>       String accountId, String workspace, String currentStateFileId, LogCallback logCallback, String baseDir) {
>     if (artifactoryStoreDelegateConfig.getArtifacts().size() < 1) {
>       throw new TerraformCommandExecutionException("No Artifactory config files details found", WingsException.USER);
> ```

Is this used only by NG, right? If so, can we add more details in exception, some hints and explanations may be helpful here
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java, line 560 at r1](https://reviewable.io/reviews/harness/harness-core/30478#-MutmNOqCbvpFY3sughb:-MutmNOqCbvpFY3sughc:b-gqdccz) ([raw file](https://github.com/harness/harness-core/blob/80e1d6e3dd33ed47c943aaf109d897dad2179cd8/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L560)):*
> ```Java
> 
>     copyConfigFilesToWorkingDirectory(
>         logCallback, artifactInputStream, baseDir, workingDir, artifactoryStoreDelegateConfig.getRepositoryPath());
> ```

From what I remember from previous PR, downloadArtifacts method can return null. Shall we handle this use case as well?
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java, line 646 at r1](https://reviewable.io/reviews/harness/harness-core/30478#-MutzpJS1i9rZZ2inDTF:-MutyNhuBbPnh1woGn3c:buqdwwu) ([raw file](https://github.com/harness/harness-core/blob/80e1d6e3dd33ed47c943aaf109d897dad2179cd8/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L646)):*
> ```Java
>     } catch (Exception ex) {
>       log.error(String.format("Exception in copying files to provisioner specific directory", ex.getMessage()), ex);
>       FileUtils.deleteQuietly(new File(baseDir));
> ```

nit: don't think really matter, but why we would like to delete baseDir if all logic is happening against workingDir? It's just confusing
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java, line 649 at r1](https://reviewable.io/reviews/harness/harness-core/30478#-MutmlfADYgOMLkA5RqJ:-MutmlfADYgOMLkA5RqK:b-h1xvwh) ([raw file](https://github.com/harness/harness-core/blob/80e1d6e3dd33ed47c943aaf109d897dad2179cd8/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L649)):*
> ```Java
>       logCallback.saveExecutionLog(
>           "Failed copying files to provisioner specific directory", ERROR, CommandExecutionStatus.RUNNING);
>       throw new TerraformCommandExecutionException(
> ```

Is this used only by NG, right? If so, can we add more details in exception, some hints and explanations may be helpful here
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java, line 744 at r1](https://reviewable.io/reviews/harness/harness-core/30478#-MutyoZL6wr5CptCxnFt:-MutyoZL6wr5CptCxnFu:bihm02e) ([raw file](https://github.com/harness/harness-core/blob/80e1d6e3dd33ed47c943aaf109d897dad2179cd8/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L744)):*
> ```Java
>       artifactMetadata.put(ARTIFACT_PATH_METADATA_KEY, artifactoryFile.getPath());
>       artifactMetadata.put(ARTIFACT_NAME_METADATA_KEY, artifactoryFile.getName());
>       InputStream artifactInputStream = artifactoryNgService.downloadArtifacts(artifactoryConfigRequest,
> ```

Same here, don't we need to handle null case? 
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/handlers/TerraformDestroyTaskHandler.java, line 99 at r1](https://reviewable.io/reviews/harness/harness-core/30478#-Mutz2aN6dN06Jj9eQOe:-Mutz2aN6dN06Jj9eQOf:b26sg38) ([raw file](https://github.com/harness/harness-core/blob/80e1d6e3dd33ed47c943aaf109d897dad2179cd8/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/handlers/TerraformDestroyTaskHandler.java#L99)):*
> ```Java
>           logCallback, baseDir);
>     } else {
>       throw new TerraformCommandExecutionException("No Terraform config set", WingsException.USER);
> ```

Can we add hint and explanation for exception?

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30478)* status: 7 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java, line 542 at r1](https://reviewable.io/reviews/harness/harness-core/30478#-MutnT_I6iVDas2Yh2Zf:-MuvWc-F0iY5zRHBH9VZ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/80e1d6e3dd33ed47c943aaf109d897dad2179cd8/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L542)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Is this used only by NG, right? If so, can we add more details in exception, some hints and explanations may be helpful here
</blockquote></details>

Done
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java, line 560 at r1](https://reviewable.io/reviews/harness/harness-core/30478#-MutmNOqCbvpFY3sughb:-MuvWX7r0unHY8DcOjmn:bs5wl4r) ([raw file](https://github.com/harness/harness-core/blob/80e1d6e3dd33ed47c943aaf109d897dad2179cd8/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L560)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

From what I remember from previous PR, downloadArtifacts method can return null. Shall we handle this use case as well?
</blockquote></details>

Done, handling this above
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java, line 646 at r1](https://reviewable.io/reviews/harness/harness-core/30478#-MutzpJS1i9rZZ2inDTF:-MuuskGCBB311vLsEy4Y:br5dz2n) ([raw file](https://github.com/harness/harness-core/blob/80e1d6e3dd33ed47c943aaf109d897dad2179cd8/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L646)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: don't think really matter, but why we would like to delete baseDir if all logic is happening against workingDir? It's just confusing
</blockquote></details>

thats the same as we do when we are copying git files, I will just extract that into a method and reuse in both places
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java, line 649 at r1](https://reviewable.io/reviews/harness/harness-core/30478#-MutmlfADYgOMLkA5RqJ:-MuvW99D5vQYvz5VnpQL:b-o6vyr3) ([raw file](https://github.com/harness/harness-core/blob/80e1d6e3dd33ed47c943aaf109d897dad2179cd8/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L649)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Is this used only by NG, right? If so, can we add more details in exception, some hints and explanations may be helpful here
</blockquote></details>

It is only on NG but there may be different reasons exception was thrown, not sure what else we could mention here.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java, line 744 at r1](https://reviewable.io/reviews/harness/harness-core/30478#-MutyoZL6wr5CptCxnFt:-MuvWrIzBdtaJVqXHwPZ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/80e1d6e3dd33ed47c943aaf109d897dad2179cd8/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L744)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Same here, don't we need to handle null case? 
</blockquote></details>

Done
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/handlers/TerraformDestroyTaskHandler.java, line 99 at r1](https://reviewable.io/reviews/harness/harness-core/30478#-Mutz2aN6dN06Jj9eQOe:-MuvWfvO3Ee8lXFmEb4w:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/80e1d6e3dd33ed47c943aaf109d897dad2179cd8/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/handlers/TerraformDestroyTaskHandler.java#L99)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we add hint and explanation for exception?
</blockquote></details>

Done

**Comment by tmacari-harness** [comment]
trigger TIbootstrap1-tin1

**Review by abosii-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30478)* status: 7 file(s) to review.

**Pull request merged**
