### PR TITLE
feat: [PL-25121]: Getting count of queue size in gitsync

### PR DESCRIPTION
**Pull request by Y0709**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34894)

### CODE REVIEW

**Comment by abhinav-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/GitSyncResource.java` line 292 at r1](https://reviewable.io/reviews/harness/harness-core/34894#-N5sVUWT5OX8ZcSd2-zi:-N5sVUWT5OX8ZcSd2-zj:bwipz4c) ([raw file](https://github.com/harness/harness-core/blob/fc6bce9eeb8bcaeb9ddd5c6f1048f41f0b4367d2/400-rest/src/main/java/software/wings/resources/GitSyncResource.java#L292)):*
> ```Java
>   public long getQueueItemsCount(@QueryParam("accountId") String accountId, @QueryParam("appId") String appId) {
>     YamlGitConfig yamlGitConfig = yamlGitConfigService.getYamlGitConfigFromAppId(appId, accountId);
>     return yamlChangeSetService.getItemsInQueueKey(yamlGitConfig);
> ```

getQueuedCountForQueueKey

**Review by abhinav-harness — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34894)* status: 6 file(s) to review. 0 of 2 approvals obtained.

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34894)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/GitSyncResource.java` line 291 at r2](https://reviewable.io/reviews/harness/harness-core/34894#-N5sqDrXB5yxeesXzG8s:-N5sqDrXB5yxeesXzG8t:bxeojtz) ([raw file](https://github.com/harness/harness-core/blob/936df087da2c89fbd6c08fcb7aa0436a897e01fe/400-rest/src/main/java/software/wings/resources/GitSyncResource.java#L291)):*
> ```Java
>   @GET
>   @Path("queuedCount")
>   public long getQueuedCountForQueueKey(@QueryParam("accountId") String accountId, @QueryParam("appId") String appId) {
> ```

@abhinav-harness  But queue key is internal concept. Who requires this count ?

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34894)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/GitSyncResource.java` line 292 at r2](https://reviewable.io/reviews/harness/harness-core/34894#-N5sqKsu9c61p1kqS_Kx:-N5sqKsu9c61p1kqS_Ky:b-e6wt20) ([raw file](https://github.com/harness/harness-core/blob/936df087da2c89fbd6c08fcb7aa0436a897e01fe/400-rest/src/main/java/software/wings/resources/GitSyncResource.java#L292)):*
> ```Java
>   @Path("queuedCount")
>   public long getQueuedCountForQueueKey(@QueryParam("accountId") String accountId, @QueryParam("appId") String appId) {
>     YamlGitConfig yamlGitConfig = yamlGitConfigService.getYamlGitConfigFromAppId(appId, accountId);
> ```

We usually try to keep the logic in service layer and no core logic in resource layer. Can you move this function to get yaml git config to the service layer

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 21 of 23 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34894)* status: 24 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34894)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/GitSyncResource.java` line 291 at r2](https://reviewable.io/reviews/harness/harness-core/34894#-N5sqDrXB5yxeesXzG8s:-N68Hu9R702G2QQcf0Nq:b-stuffk) ([raw file](https://github.com/harness/harness-core/blob/936df087da2c89fbd6c08fcb7aa0436a897e01fe/400-rest/src/main/java/software/wings/resources/GitSyncResource.java#L291)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

@abhinav-harness  But queue key is internal concept. Who requires this count ?
</blockquote></details>

Kroger wants to view count in queue in UI to understand if they are delayed in git sync

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34894)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/GitSyncResource.java` line 291 at r2](https://reviewable.io/reviews/harness/harness-core/34894#-N5sqDrXB5yxeesXzG8s:-N68oaYQA8czfK_stey4:b-s9up8r) ([raw file](https://github.com/harness/harness-core/blob/936df087da2c89fbd6c08fcb7aa0436a897e01fe/400-rest/src/main/java/software/wings/resources/GitSyncResource.java#L291)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

Kroger wants to view count in queue in UI to understand if they are delayed in git sync 
</blockquote></details>

Yes but lets name it something else like get count by application

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 1 of 23 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34894)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by DeepakPatankar — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34894#-:-N6Bvtj920NIukbFhLUa:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger ft1,ft2

**Review by abhinav-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34894)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34894#-:-N6CIKu3DD_KCqGT_ufY:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
