### PR TITLE
fix: [CDS-77736]: Added the null check for triggerPayload

### PR DESCRIPTION
**Pull request by shivamnegi94**
## Describe your changes
TriggerPayload could be null if user using trigger expression in manual runs.
When mapping the connectorRef expression we were not validating the triggerPayload is null or not which caused NPE.

Fix:
Added the validation for NPE
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51954)

### CODE REVIEW

**Comment by shivamnegi94** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51954)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/expression/ExpressionEvaluatorUtils.java` line 298 at r2](https://reviewable.io/reviews/harness/harness-core/51954#-NcX5Eq183QiUi9aZTO0:-NcX5Eq183QiUi9aZTO1:bzbhyzv) ([raw file](https://github.com/harness/harness-core/blob/1470a66b1975f9e905b128d72dbf995dad71eb0f/980-commons/src/main/java/io/harness/expression/ExpressionEvaluatorUtils.java#L298)):*
> ```Java
>         } catch (Exception ex) {
>           // Fallback to the older mechanism if there is any exception
>           log.warn(String.format("Exception while rendering map: [%s]", ex.getMessage()));
> ```

@hingerabhinav can you check why warn are coming a lot? if not useful can we remove?

**Comment by hingerabhinav** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/51954)_ status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`980-commons/src/main/java/io/harness/expression/ExpressionEvaluatorUtils.java` line 298 at r2](https://reviewable.io/reviews/harness/harness-core/51954#-NcX5Eq183QiUi9aZTO0:-NcX5Eq183QiUi9aZTO1:bzbhyzv) ([raw file](https://github.com/harness/harness-core/blob/1470a66b1975f9e905b128d72dbf995dad71eb0f/980-commons/src/main/java/io/harness/expression/ExpressionEvaluatorUtils.java#L298)):_
> 
> > ```java
> >         } catch (Exception ex) {
> >           // Fallback to the older mechanism if there is any exception
> >           log.warn(String.format("Exception while rendering map: [%s]", ex.getMessage()));
> > ```
> 
> @hingerabhinav can you check why warn are coming a lot? if not useful can we remove?

@archit-harness we added this block to ensure, we were falling back to the old approach of updating just the value in place. From the logs it does not look like there is any issue with the approach itself, most errors are legit errors of unresolved expressions.
We can just catch the unresolved exceptions and handle it differently than other exceptions instead of removing the fallback completely.

**Comment by shivamnegi94** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51954)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/expression/ExpressionEvaluatorUtils.java` line 298 at r2](https://reviewable.io/reviews/harness/harness-core/51954#-NcX5Eq183QiUi9aZTO0:-NcXISyfCwpOViG4SX9H:bs9hav3) ([raw file](https://github.com/harness/harness-core/blob/1470a66b1975f9e905b128d72dbf995dad71eb0f/980-commons/src/main/java/io/harness/expression/ExpressionEvaluatorUtils.java#L298)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

@archit-harness we added this block to ensure, we were falling back to the old approach of updating just the value in place. From the logs it does not look like there is any issue with the approach itself, most errors are legit errors of unresolved expressions.
We can just catch the unresolved exceptions and handle it differently than other exceptions instead of removing the fallback completely. 

</blockquote></details>

done, @hingerabhinav please follow offline

**Comment by shivamnegi94** [comment]
trigger ut0

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by shivamnegi94** [comment]
trigger review

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51954)* status: :shipit: complete! ✓

**Pull request merged**
