### PR TITLE
[fix]: [CDP-20483]: fix for pcf inbuilt variables

### PR DESCRIPTION
**Pull request by anilchowdhury-harness**
[fix]: [CDP-20483]: fix for pcf inbuilt variables

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

[CDP-20483]: https://harness.atlassian.net/browse/CDP-20483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30419)

### CODE REVIEW

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30419#-:-Muv5bbO1-0kbC6mrnAq:bnfp4nl)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Review by suhas-sridharan — APPROVED** [review]
> Reviewed 19 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30419)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30419#-:-Muvs_no4IHcnmyp3Ej7:bnfp4nl)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30419)* status: :shipit: complete! ✓

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 19 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30419)* status: :shipit: complete! ✓

**Pull request merged**
