### PR TITLE
fix: [DEL-4425]: dont allow readOnly users to download delegates

### PR DESCRIPTION
**Pull request by arpit3107**
## Describe your changes
1. Ng docker delegate apis was not using access control properly. 
2. In CG deprecate the GET api for downloading api and expose a POST api so that UI can use.
3. Will remove the deprecated api.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35156)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResourceV3.java` line 956 at r2](https://reviewable.io/reviews/harness/harness-core/35156#-N6iHp732L9Vwso9wdz9:-N6iHp732L9Vwso9wdzA:b-trexdm) ([raw file](https://github.com/harness/harness-core/blob/b41f6fc977b56923ef06c210db71fea9f5815299/400-rest/src/main/java/software/wings/resources/DelegateSetupResourceV3.java#L956)):*
> ```Java
>       @RequestBody(required = true, description = "Delegate setup details, containing data to populate file values.")
>       DelegateSetupDetails delegateSetupDetails) throws IOException {
>     accessControlClient.checkForAccessOrThrow(ResourceScope.of(accountId, delegateSetupDetails.getOrgIdentifier(),
> ```

@arpit3107 we should add unit tests for this change

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35156)* status: Some of the checks are too old. 2 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResourceV3.java` line 956 at r2](https://reviewable.io/reviews/harness/harness-core/35156#-N6iHp732L9Vwso9wdz9:-N6l_7sA89ryRQh93pEe:b-1uevro) ([raw file](https://github.com/harness/harness-core/blob/b41f6fc977b56923ef06c210db71fea9f5815299/400-rest/src/main/java/software/wings/resources/DelegateSetupResourceV3.java#L956)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

@arpit3107 we should add unit tests for this change
</blockquote></details>

unit tests for resource layer? for api endpoints? I dont think they are of much use, since the unit tests for internal logic is already there

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35156)* status: Some of the checks are too old.

**Review by Vbhatia20 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35156)* status: :shipit: complete! ✓

**Pull request merged**
