### PR TITLE
feat: [SRM-9969]: Propogate delay to next state machines

### PR DESCRIPTION
**Pull request by AbhijithHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32136)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32136)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/AnalysisStateMachineServiceImpl.java, line 155 at r1](https://reviewable.io/reviews/harness/harness-core/32136#-N-2firyAldK63JUvpOt:-N-2firyAldK63JUvpOu:b-z0fuhh) ([raw file](https://github.com/harness/harness-core/blob/735a6fc56f1e3b0d68970eaa32683d5a99bfa9e2/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/AnalysisStateMachineServiceImpl.java#L155)):*
> ```Java
>   @Override
>   public AnalysisStatus executeStateMachine(AnalysisStateMachine analysisStateMachine) {
>     if (Instant.ofEpochMilli(analysisStateMachine.getNextAttemptTime()).isAfter(Instant.now())) {
> ```

please use clock.instant() instead of Instant.now()

Can't we put this as part of the query? does this mean that this never worked?
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/AnalysisStateMachineServiceImpl.java, line 167 at r1](https://reviewable.io/reviews/harness/harness-core/32136#-N-2gP6T1kR8EvIQHL7E:-N-2gP6T1kR8EvIQHL7F:b-v0grcn) ([raw file](https://github.com/harness/harness-core/blob/735a6fc56f1e3b0d68970eaa32683d5a99bfa9e2/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/AnalysisStateMachineServiceImpl.java#L167)):*
> ```Java
>     if (status.equals(AnalysisStatus.RETRY) && !currentState.getStatus().equals(AnalysisStatus.RETRY)) {
>       analysisStateMachine.getCurrentState().setStatus(AnalysisStatus.RETRY);
>       analysisStateMachine.updateNextAttemptTime(clock.instant());
> ```

why clock.instant() for retry?
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/AnalysisStateMachineServiceImpl.java, line 236 at r1](https://reviewable.io/reviews/harness/harness-core/32136#-N-2g_rAB5kn4TcfJE78:-N-2g_rAB5kn4TcfJE79:byzo9fl) ([raw file](https://github.com/harness/harness-core/blob/735a6fc56f1e3b0d68970eaa32683d5a99bfa9e2/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/AnalysisStateMachineServiceImpl.java#L236)):*
> ```Java
>       nextStateExecutor.handleFinalStatuses(nextState);
>     } else if (AnalysisStatus.getFinalStates().contains(nextState.getStatus())) {
>       analysisStateMachine.updateNextAttemptTime(clock.instant());
> ```

this is for default value? Should we keep it null or zero. The condition to execute will work with zero also right?
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java, line 205 at r1](https://reviewable.io/reviews/harness/harness-core/32136#-N-2goG101ABrC9p1qpM:-N-2goG101ABrC9p1qpN:b-qpalzk) ([raw file](https://github.com/harness/harness-core/blob/735a6fc56f1e3b0d68970eaa32683d5a99bfa9e2/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java#L205)):*
> ```Java
>   }
> 
>   private void orchestrateNewAnalysisStateMachine(
> ```

can we only pass previousStateMachine.getTotalRetryCount() instead of the whole object? We can set the default to be zero. Always better to pass the minimal information needed.

**Review by kjoshi12345 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32136#-:-N-2lsw19ltY6x2_zkKx:bnfp4nl)* status: :shipit: complete! ✓

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/entities/AnalysisStateMachine.java, line 98 at r1](https://reviewable.io/reviews/harness/harness-core/32136#-N-2iJkT-aPJczu2H7f8:-N-2iJkT-aPJczu2H7f9:bvy8kzl) ([raw file](https://github.com/harness/harness-core/blob/735a6fc56f1e3b0d68970eaa32683d5a99bfa9e2/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/entities/AnalysisStateMachine.java#L98)):*
> ```Java
>   }
> 
>   public void updateNextAttemptTime(Instant now) {
> ```

setNextAttemptTimeUsingRetryCount

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32136)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java, line 159 at r2](https://reviewable.io/reviews/harness/harness-core/32136#-N-2xDpU5vRrPPWOTa7L:-N-2xDpU5vRrPPWOTa7M:b-kq8ihk) ([raw file](https://github.com/harness/harness-core/blob/17eee0b6a8fcec76150b515a5699211b949ac208/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java#L159)):*
> ```Java
>         case SUCCESS:
>         case IGNORED:
>           orchestrateNewAnalysisStateMachine(
> ```

can currentlyExecutingStateMachine be null? earlier you had null conditions also

**Review by AbhijithHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32136)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/AnalysisStateMachineServiceImpl.java, line 155 at r1](https://reviewable.io/reviews/harness/harness-core/32136#-N-2firyAldK63JUvpOt:-N-2r515AabzZYRZLK2f:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/735a6fc56f1e3b0d68970eaa32683d5a99bfa9e2/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/AnalysisStateMachineServiceImpl.java#L155)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

please use clock.instant() instead of Instant.now()

Can't we put this as part of the query? does this mean that this never worked?
</blockquote></details>

Done.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java, line 159 at r2](https://reviewable.io/reviews/harness/harness-core/32136#-N-2xDpU5vRrPPWOTa7L:-N-2xjuZ4EVFHFoCcU9n:b-453pmz) ([raw file](https://github.com/harness/harness-core/blob/17eee0b6a8fcec76150b515a5699211b949ac208/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java#L159)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

can currentlyExecutingStateMachine be null? earlier you had null conditions also
</blockquote></details>

No, both usages inside urrentlyExecutingStateMachine != null

**Review by kjoshi12345 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32136)* status: :shipit: complete! ✓

**Review by kjoshi12345 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32136)* status: :shipit: complete! ✓

**Pull request merged**
