### PR TITLE
techDebt: [PL-29712] Create DTO for PersistentEntity

### PR DESCRIPTION
**Pull request by kshitij-harness**
## Describe your changes
Created DTO for Artifact, ArtifactFile, AppContainer and BaseFile.
Moved persistence entity for same to 400-rest in different package.

Basic sanity testing done in PR env by submitting a delegate task. Would get it tested by automation tests in preQA before merging it to QA.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40065)

### CODE REVIEW

**Review by gn-harness — DISMISSED** [review]
> Reviewed 40 of 306 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40065)* status: 265 file(s) to review. 

___
*[`957-cg-beans/src/main/java/software/wings/beans/artifact/Artifact.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/40065#-NI_eNlq6W8M5EK67j9I:-NI_eNlq6W8M5EK67j9J:b-ivi980) ([raw file](https://github.com/harness/harness-core/blob/928120c51f623d42c7babf9540ec12d3b4b16c2f/957-cg-beans/src/main/java/software/wings/beans/artifact/Artifact.java#L44)):*
> ```Java
> @Data
> @FieldNameConstants(innerTypeName = "ArtifactKeys")
> @StoreIn(DbAliases.HARNESS)
> ```

this should be cleaned too?



_Code quote:_
```Java
@StoreIn(DbAliases.HARNESS)
```
___
*[`957-cg-beans/src/main/java/software/wings/beans/artifact/Artifact.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/40065#-NI_eShMDS6fKipPmfuA:-NI_eShMDS6fKipPmfuB:b-kvh115) ([raw file](https://github.com/harness/harness-core/blob/928120c51f623d42c7babf9540ec12d3b4b16c2f/957-cg-beans/src/main/java/software/wings/beans/artifact/Artifact.java#L45)):*
> ```Java
> @FieldNameConstants(innerTypeName = "ArtifactKeys")
> @StoreIn(DbAliases.HARNESS)
> @TargetModule(HarnessModule._957_CG_BEANS)
> ```

nit: not required anymore



_Code quote:_
```Java
@TargetModule(HarnessModule._957_CG_BEANS)
```

**Review by gn-harness — APPROVED** [review]
> Reviewed 259 of 306 files at r1, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40065)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 297 of 306 files at r1, 1 of 1 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40065)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
*[`190-deployment-functional-tests/src/test/java/io/harness/functional/workflow/AmiWorkflowFunctionalTest.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/40065#-NImrhHO8jUjMIyIyNJq:-NImrhHO8jUjMIyIyNJr:b-e1a4uo) ([raw file](https://github.com/harness/harness-core/blob/377b30b041e3c92a60a335dcdd3cb51b3b33fd37/190-deployment-functional-tests/src/test/java/io/harness/functional/workflow/AmiWorkflowFunctionalTest.java#L46)):*
> ```Java
> import software.wings.infra.AwsAmiInfrastructure;
> import software.wings.infra.InfrastructureDefinition;
> import software.wings.persistence.artifact.Artifact;
> ```

why change all the existing package names? it makes it hard to review. Do not change the package name for existing class.

**Pull request merged**
