### PR TITLE
[feat]: [SRM-10894]: refactoring Notification template data generation

### PR DESCRIPTION
**Pull request by kapil-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34943)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger messagecheck

**Comment by kapil-harness** [comment]
trigger ft1

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34943)* status: 18 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/api/NotificationRuleTemplateDataGenerator.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N68a9H921Ny7h0L9STe:-N68a9H921Ny7h0L9STf:b-sjmsq9) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/api/NotificationRuleTemplateDataGenerator.java#L39)):*
> ```Java
>   @Inject private Clock clock;
> 
>   private static final String themeColor = "#EC372E";
> ```

nit: according to convention static fields should be at top
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/api/NotificationRuleTemplateDataGenerator.java` line 50 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69aqKR-OLf2GROE1Hb:-N69aqKR-OLf2GROE1Hc:b-oeq2ol) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/api/NotificationRuleTemplateDataGenerator.java#L50)):*
> ```Java
>   private static final String URL = "URL";
> 
>   public abstract Map<String, String> getTemplateData(ProjectParams projectParams, String name, String identifier,
> ```

This function parameters is too confusing. Take the whole entity as input.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/api/NotificationRuleTemplateDataGenerator.java` line 86 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69XqoF63sHEo1SRK3R:-N69XqoF63sHEo1SRK3S:bumqnf0) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/api/NotificationRuleTemplateDataGenerator.java#L86)):*
> ```Java
>   }
> 
>   private String getUrl(
> ```

Move this to different abstract classes, and extend accordingly.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/BurnRateTemplateDataGenerator.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69UuOA-Pc0x1JTXjdJ:-N69UuOA-Pc0x1JTXjdK:b-w0ut1w) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/BurnRateTemplateDataGenerator.java#L23)):*
> ```Java
> 
> public class BurnRateTemplateDataGenerator
>     extends NotificationRuleTemplateDataGenerator<SLOErrorBudgetBurnRateCondition> {
> ```

Take the entity also in as Generics, so that complete notification data can be decided here. 
Create other abstractClasses of SLO and MonitoredService if required to reduce duplicate. 
May be something like: NotificationRuleTemplateDataGenerator<SLOErrorBudgetBurnRateCondition, ServiceLevelObjective> 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/ChangeImpactTemplateDataGenerator.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69amG5E9VDT35Bl99G:-N69amG5E9VDT35Bl99H:b-zceq0k) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/ChangeImpactTemplateDataGenerator.java#L27)):*
> ```Java
>     extends NotificationRuleTemplateDataGenerator<MonitoredServiceChangeImpactCondition> {
>   @Override
>   public Map<String, String> getTemplateData(ProjectParams projectParams, String name, String identifier,
> ```

This i



_Code quote (from 300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java):_
```Java
condition
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/ChangeImpactTemplateDataGenerator.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69YQmy6drzl51TYBzj:-N69YQmy6drzl51TYBzk:bqyzlz4) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/ChangeImpactTemplateDataGenerator.java#L30)):*
> ```Java
>       String serviceIdentifier, MonitoredServiceChangeImpactCondition condition,
>       Map<String, String> notificationDataMap) {
>     Map<String, String> templateData = getCommonTemplateData(projectParams, identifier, serviceIdentifier, condition);
> ```

Instead of forcing every class to call this getCommonTemplateData. 
You can make each class override some other function "getConditionSpecificTemplateData" and call it from getTemplateData.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 449 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69Tag91gyRlLsrg26d:-N69Tag91gyRlLsrg26e:b-3rlrsa) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L449)):*
> ```Java
> 
>   @Override
>   public void sendNotification(ServiceLevelObjective serviceLevelObjective) {
> ```

MonitoredService or SLO shouldnt worry about notification. Can we move this also into a different class. 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 464 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69__7LAVFLgwgBk3UU:-N69__7LAVFLgwgBk3UV:b-tca672) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L464)):*
> ```Java
>         if (notificationData.isShouldSendNotification()) {
>           CVNGNotificationChannel notificationChannel = notificationRule.getNotificationMethod();
>           String templateId = getNotificationTemplateId(notificationRule.getType(), notificationChannel.getType());
> ```

Move templateId also into generator. that just takes notificationChannel.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 558 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69T04PAjhgOu21nYNg:-N69T04PAjhgOu21nYNh:b-elsu0o) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L558)):*
> ```Java
> 
>   @VisibleForTesting
>   NotificationData getNotificationData(
> ```

Can we move this also into the DataGenerator. 
MonitoredService/SLO shouldn't worry about Notifications. 
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/client/FakeAccountClient.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69QunZ5Qdd9ozZ8PBF:-N69QunZ5Qdd9ozZ8PBG:b-p2uybg) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/test/java/io/harness/cvng/client/FakeAccountClient.java#L25)):*
> ```Java
> import retrofit2.Response;
> 
> public class FakeAccountClient implements AccountClient {
> ```

nit: Using Mockito mock should have been easier. as we need to only mock the required functions.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34943)* status: 21 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/api/NotificationRuleTemplateDataGenerator.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N68a9H921Ny7h0L9STe:-N6ENBNNDAtgTbQyf50g:b-9op6uj) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/api/NotificationRuleTemplateDataGenerator.java#L39)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

nit: according to convention static fields should be at top
</blockquote></details>

done, shifted to a dedicated class for constants
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/api/NotificationRuleTemplateDataGenerator.java` line 50 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69aqKR-OLf2GROE1Hb:-N6ENHQ20mkTEY_Pgx-E:b55ol17) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/api/NotificationRuleTemplateDataGenerator.java#L50)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

This function parameters is too confusing. Take the whole entity as input.
</blockquote></details>

discussed with Deepak, its fine, we have something similar for SLIs as well
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/api/NotificationRuleTemplateDataGenerator.java` line 86 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69XqoF63sHEo1SRK3R:-N6ENN7nEOJWJuIflwdm:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/api/NotificationRuleTemplateDataGenerator.java#L86)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Move this to different abstract classes, and extend accordingly.
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/BurnRateTemplateDataGenerator.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69UuOA-Pc0x1JTXjdJ:-N6ENP4l8hkF2tEks-Ot:bngrc3r) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/BurnRateTemplateDataGenerator.java#L23)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Take the entity also in as Generics, so that complete notification data can be decided here. 
Create other abstractClasses of SLO and MonitoredService if required to reduce duplicate. 
May be something like: NotificationRuleTemplateDataGenerator<SLOErrorBudgetBurnRateCondition, ServiceLevelObjective> 
</blockquote></details>

I have not done exactly this, but improved previous design, we cannot have entity as a generic due to design complications
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/ChangeImpactTemplateDataGenerator.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69amG5E9VDT35Bl99G:-N6ENbOvA6skQDTyeMCj:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/ChangeImpactTemplateDataGenerator.java#L27)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

This i
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/ChangeImpactTemplateDataGenerator.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69YQmy6drzl51TYBzj:-N6ENcX-3WbawOFK23Cm:bn5eh12) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/ChangeImpactTemplateDataGenerator.java#L30)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Instead of forcing every class to call this getCommonTemplateData. 
You can make each class override some other function "getConditionSpecificTemplateData" and call it from getTemplateData.
</blockquote></details>

done, thanks for this nice suggestion.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 449 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69Tag91gyRlLsrg26d:-N6ENlKm-B9COqTdRXP5:bt9au72) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L449)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

MonitoredService or SLO shouldnt worry about notification. Can we move this also into a different class. 
</blockquote></details>

this is the design which we have agreed and is present in SRM Notification tech spec as well. This cannot be changed.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 464 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69__7LAVFLgwgBk3UU:-N6ENy5n2vMVKRJqPvyT:bgg9k0g) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L464)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Move templateId also into generator. that just takes notificationChannel.
</blockquote></details>

templateDataGenerator is dedicated for getting template data, so not required
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 558 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69T04PAjhgOu21nYNg:-N6EOIARDWhjGAOd88yM:bpp6stj) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L558)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Can we move this also into the DataGenerator. 
MonitoredService/SLO shouldn't worry about Notifications. 
</blockquote></details>

not needed
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/client/FakeAccountClient.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/34943#-N69QunZ5Qdd9ozZ8PBF:-N6EOKJo0PM6pz36BqHQ:b-82ddr6) ([raw file](https://github.com/harness/harness-core/blob/3bc38f183e4b9c32189683541e1e09ad4dfe531c/300-cv-nextgen/src/test/java/io/harness/cvng/client/FakeAccountClient.java#L25)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

nit: Using Mockito mock should have been easier. as we need to only mock the required functions.
</blockquote></details>

I tried mocking in the first place, however due to AccountClient being present inside NotificationRuleTemplateDataGenerator and this inside a MapBinder, I was not able to bind the implementation. This approach is also fine, as per our testing strategy we usually create Fake impl classes for External clients rather than mocking.

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34943)* status: 21 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 449 at r4](https://reviewable.io/reviews/harness/harness-core/34943#-N6IC03V2Gr9yg6Ro5SQ:-N6IC03V2Gr9yg6Ro5SR:b-j41mxj) ([raw file](https://github.com/harness/harness-core/blob/fd25d381bdb2ff83f1463925a995a9b1cb45222a/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L449)):*
> ```Java
> 
>   @Override
>   public void sendNotification(ServiceLevelObjective serviceLevelObjective) {
> ```

nit: We can use processNotification or handleNotification
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 462 at r4](https://reviewable.io/reviews/harness/harness-core/34943#-N6IBmzQBx6wdFulY4Ew:-N6IBmzQBx6wdFulY4Ex:bgfi8sm) ([raw file](https://github.com/harness/harness-core/blob/fd25d381bdb2ff83f1463925a995a9b1cb45222a/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L462)):*
> ```Java
>       for (SLONotificationRuleCondition condition : conditions) {
>         NotificationData notificationData = getNotificationData(serviceLevelObjective, condition);
>         if (notificationData.isShouldSendNotification()) {
> ```

use fluent to remove is from the getter for shouldSendNotification

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34943)* status: 25 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 449 at r4](https://reviewable.io/reviews/harness/harness-core/34943#-N6IC03V2Gr9yg6Ro5SQ:-N6IJruJDSVC2pfClk5e:b-r92v3q) ([raw file](https://github.com/harness/harness-core/blob/fd25d381bdb2ff83f1463925a995a9b1cb45222a/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L449)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

nit: We can use processNotification or handleNotification
</blockquote></details>

done, using handleNotification
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 462 at r4](https://reviewable.io/reviews/harness/harness-core/34943#-N6IBmzQBx6wdFulY4Ew:-N6IJubq66z06TkF_U6v:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/fd25d381bdb2ff83f1463925a995a9b1cb45222a/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L462)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

use fluent to remove is from the getter for shouldSendNotification
</blockquote></details>

done

**Review by deepak-harness — APPROVED** [review]
> Reviewed 4 of 14 files at r1, 2 of 14 files at r3, 10 of 13 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34943)* status: 1 change requests. 7. unresolved discussions.

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34943)* status: 7. unresolved discussions.

**Review by AbhijithHarness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34943)* status: :shipit: complete! ✓

**Pull request merged**
