### PR TITLE
fix: [PL-30838]: Enforce limits to secrets in ng for free license

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Describe your changes
Secrets are limited to 100 for free users
Tested whether the check locally by trying to add secrets beyond limit
UT's are not required as this is straight check 

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42743)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42743)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/repositories/ng/core/spring/SecretRepository.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/42743#-NM2Xt3fBX_spGQL0MbH:-NM2Xt3g77HYg0M3rMk4:bsinf3w) ([raw file](https://github.com/harness/harness-core/blob/32275212634231ed77905ae51b8c03ba99c96fe2/120-ng-manager/src/main/java/io/harness/repositories/ng/core/spring/SecretRepository.java#L29)):*
> ```Java
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, String identifier);
> 
>   Long countByAccountIdentifier(String accountIdentifier);
> ```

If an account still has soft deleted secrets then this will give unexpected count. This goes for other entities as well.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42743)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42743)* status: 11 file(s) to review. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/repositories/ng/core/spring/SecretRepository.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/42743#-NM2Xt3fBX_spGQL0MbH:-NM3HEzvB08RFTiPc3gh:b-3i9zcq) ([raw file](https://github.com/harness/harness-core/blob/32275212634231ed77905ae51b8c03ba99c96fe2/120-ng-manager/src/main/java/io/harness/repositories/ng/core/spring/SecretRepository.java#L29)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

If an account still has soft deleted secrets then this will give unexpected count. This goes for other entities as well.
</blockquote></details>

Soft deletion is not there in secrets

**Review by piyush-harness — APPROVED** [review]
> Reviewed 7 of 11 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42743)* status: :shipit: complete! ✓

**Pull request merged**
