### PR TITLE
feat: [CDS-34206]: Details about Helm-Chart as artifact on service available

### PR DESCRIPTION
**Pull request by atharvatrivedi1**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31451)

### CODE REVIEW

**Review by prabu-kr — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31451)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/resources/graphql/public/execution.graphql, line 114 at r2](https://reviewable.io/reviews/harness/harness-core/31451#-MyBeXxODo4h34czXWNW:-MyBeXxODo4h34czXWNX:b-vvjozx) ([raw file](https://github.com/harness/harness-core/blob/2f55e66ca8580b9afe8bc993050ceb5614caa39e/400-rest/src/main/resources/graphql/public/execution.graphql#L114)):*
> ```GraphQL
> }
> 
> type Manifest {
> ```

Please add short descriptions for the new fields for better understandability in the docs. Refer the artifact graphql structure

**Comment by atharvatrivedi1** [comment]
trigger ti0

**Comment by atharvatrivedi1** [comment]
trigger ti0

**Review by prabu-kr — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31451)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by prabu-kr — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31451)* status: :shipit: complete! ✓

**Pull request merged**
