### PR TITLE
[feat]: [CCM-7308]: Next-Gen Filter Panel support [Recommendations]

### PR DESCRIPTION
**Pull request by abhijeet-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32466)

### CODE REVIEW

**Review by Rohit-Kaliki — APPROVED** [review]
> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32466)* status: :shipit: complete! ✓

___
*[`340-ce-nextgen/src/main/java/io/harness/ccm/remote/beans/recommendation/K8sRecommendationFilterPropertiesDTO.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/32466#-N0UvQ1W0pcUVWHAzC31:-N0UvQ1X2Tw9c-Bx71QC:b-bhx2m7) ([raw file](https://github.com/harness/harness-core/blob/227ce5fab5ca1d479c168878a2dd048f59ae5705/340-ce-nextgen/src/main/java/io/harness/ccm/remote/beans/recommendation/K8sRecommendationFilterPropertiesDTO.java#L44)):*
> ```Java
> public class K8sRecommendationFilterPropertiesDTO extends FilterPropertiesDTO {
>     List<String> ids;
>     List<String> names;
> ```

I'm still a bit unclear on what is the actual call that UI fires and what is the underlying Query that hits the DB. If you have tested out the APIs can you post the samples in the comments

**Comment by abhijeet-harness** [comment]
trigger message_metadata

**Comment by abhijeet-harness** [comment]
trigger messagecheck

**Review by abhijeet-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32466)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`340-ce-nextgen/src/main/java/io/harness/ccm/remote/beans/recommendation/K8sRecommendationFilterPropertiesDTO.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/32466#-N0UvQ1W0pcUVWHAzC31:-N0WKv193DzJJ4Hgj7yy:b-blbrkk) ([raw file](https://github.com/harness/harness-core/blob/227ce5fab5ca1d479c168878a2dd048f59ae5705/340-ce-nextgen/src/main/java/io/harness/ccm/remote/beans/recommendation/K8sRecommendationFilterPropertiesDTO.java#L44)):*
<details><summary><i>Previously, Rohit-Kaliki (K Rohit Reddy) wrote…</i></summary><blockquote>

I'm still a bit unclear on what is the actual call that UI fires and what is the underlying Query that hits the DB. If you have tested out the APIs can you post the samples in the comments 
</blockquote></details>

Sample API calls:

GET
https://ce-dev.harness.io/gateway/ccm/api/filters?accountIdentifier=EfOfrUbHTtupeZjUqxlHBg&routingId=EfOfrUbHTtupeZjUqxlHBg&type=CCMRecommendation

POST
https://ce-dev.harness.io/gateway/ccm/api/filters?accountIdentifier=EfOfrUbHTtupeZjUqxlHBg&routingId=EfOfrUbHTtupeZjUqxlHBg
Body:
{
"name":"FilterTest1",
"identifier":"FilterTest1",
"filterVisibility":"OnlyCreator",
"filterProperties": {
"filterType":"CCMRecommendation",
"clusterNames":["Cluster1","Cluster2","Cluster3"],
"minCost":1200
}
}

**Review by hitesharinga — DISMISSED** [review]
> Reviewed 4 of 10 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32466)* status: 1. unresolved discussions.

**Review by hitesharinga — APPROVED** [review]
> Reviewed 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32466)* status: 1. unresolved discussions.

**Pull request merged**
