### PR TITLE
fix: [CDS-47378]: Add service identifier index as part of distinct query

### PR DESCRIPTION
**Pull request by abosii-harness**
## Describe your changes
Without this index distinct query (or any group query) based on service identifier will end up in examining documents
Screenshot 2022-11-28 at 17 49 24

Screenshot 2022-11-28 at 18 18 29

With this index:
Screenshot 2022-11-28 at 17 47 36

Screenshot 2022-11-28 at 18 17 34

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40726)

### CODE REVIEW

**Comment by abosii-harness** [comment]
trigger messagecheck

**Review by abosii-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40726)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/entities/Instance.java` line 142 at r1](https://reviewable.io/reviews/harness/harness-core/40726#-NHzJZaQ2rfd8ieAhl-f:-NI16MnG70AtLVEu6OER:b-ido51j) ([raw file](https://github.com/harness/harness-core/blob/ba4edac5509c008d88ca0082d0ddf1f2271a1c07/126-instance/src/main/java/io/harness/entities/Instance.java#L142)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

any query that passes on accountId and serviceId should be doing something wrong probably since services are scoped to projects ?
</blockquote></details>

I would assume this query is used to get all services instances for a specific account and all orgs and projects. I didn't really go deep in this logic, I just see that it's used in a few places and the query is there so I would expect that it could be an expected logic for some telemetry

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40726)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40726)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40726)* status: :shipit: complete! ✓

**Pull request merged**
