### PR TITLE
techdebt: [PL-25157]: moving ng-variable code under single  module

### PR DESCRIPTION
**Pull request by nishantsaini20**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34410)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 43 of 43 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34410)* status: 43 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-variable/BUILD.bazel` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/34410#-N58ybfG6wtJaEjv7IsN:-N58ybfG6wtJaEjv7IsO:b-r6oy97) ([raw file](https://github.com/harness/harness-core/blob/e7aef0c3b3f70926b69b449e66a0058cb97a4f65/120-ng-manager/modules/ng-variable/BUILD.bazel#L33)):*
> ```Starlark
>         ":module",
>         "//:lombok",
>         "//120-ng-manager/modules/ng-variable/contracts:module",
> ```

can we name the module ng-variables instead of ng-variable
___
*[`120-ng-manager/modules/ng-variable/src/main/java/io/harness/ng/core/variable/resources/VariableResourceImpl.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/34410#-N58ys0lDQeUWuEddtvF:-N58ys0lDQeUWuEddtvG:b-irdgot) ([raw file](https://github.com/harness/harness-core/blob/e7aef0c3b3f70926b69b449e66a0058cb97a4f65/120-ng-manager/modules/ng-variable/src/main/java/io/harness/ng/core/variable/resources/VariableResourceImpl.java#L37)):*
> ```Java
> @OwnedBy(HarnessTeam.PL)
> @AllArgsConstructor(onConstructor = @__({ @Inject }))
> public class VariableResourceImpl implements VariableResource {
> ```

Pls make sure all Harness annotations (like @InternalApi etc) on Resource are also applied here because Harness annotations don't take effect on interfaces
___
*[`120-ng-manager/modules/ng-variable/contracts/src/main/java/io/harness/ng/core/variable/resources/VariableResource.java` line 87 at r1](https://reviewable.io/reviews/harness/harness-core/34410#-N58zEz-1UolTGQN_S1_:-N58zEz-1UolTGQN_S1a:b-h4naum) ([raw file](https://github.com/harness/harness-core/blob/e7aef0c3b3f70926b69b449e66a0058cb97a4f65/120-ng-manager/modules/ng-variable/contracts/src/main/java/io/harness/ng/core/variable/resources/VariableResource.java#L87)):*
> ```Java
>       , @ApiResponse(code = 500, response = ErrorDTO.class, message = "Internal server error")
>     })
> public interface VariableResource {
> ```

No need for Harness annotations like NGAccessControlCheck here

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34410)* status: 43 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-variable/src/main/java/io/harness/serializer/NGVariableRegistrars.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/34410#-N591cv-8wJ064Z9CwfN:-N591cv-8wJ064Z9CwfO:b-ie4v3r) ([raw file](https://github.com/harness/harness-core/blob/e7aef0c3b3f70926b69b449e66a0058cb97a4f65/120-ng-manager/modules/ng-variable/src/main/java/io/harness/serializer/NGVariableRegistrars.java#L20)):*
> ```Java
> @OwnedBy(HarnessTeam.PL)
> @UtilityClass
> public class NGVariableRegistrars {
> ```

Why do we need morphia registrars?
___
*[`120-ng-manager/modules/ng-variable/src/main/java/io/harness/serializer/morphia/NGVariableMorphiaRegistrar.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/34410#-N590HNECjeVayni1LUE:-N590HNECjeVayni1LUF:b-7yuzha) ([raw file](https://github.com/harness/harness-core/blob/e7aef0c3b3f70926b69b449e66a0058cb97a4f65/120-ng-manager/modules/ng-variable/src/main/java/io/harness/serializer/morphia/NGVariableMorphiaRegistrar.java#L17)):*
> ```Java
> import java.util.Set;
> 
> public class NGVariableMorphiaRegistrar implements MorphiaRegistrar {
> ```

Where

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34410)* status: 44 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-variable/BUILD.bazel` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/34410#-N58ybfG6wtJaEjv7IsN:-N5A60zaESwfBIexTx-B:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e7aef0c3b3f70926b69b449e66a0058cb97a4f65/120-ng-manager/modules/ng-variable/BUILD.bazel#L33)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

can we name the module ng-variables instead of ng-variable
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-variable/contracts/src/main/java/io/harness/ng/core/variable/resources/VariableResource.java` line 87 at r1](https://reviewable.io/reviews/harness/harness-core/34410#-N58zEz-1UolTGQN_S1_:-N5A65kcDpi6kuFRIvPt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e7aef0c3b3f70926b69b449e66a0058cb97a4f65/120-ng-manager/modules/ng-variable/contracts/src/main/java/io/harness/ng/core/variable/resources/VariableResource.java#L87)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

No need for Harness annotations like NGAccessControlCheck here
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-variable/src/main/java/io/harness/ng/core/variable/resources/VariableResourceImpl.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/34410#-N58ys0lDQeUWuEddtvF:-N5A6EDzDk7mHon6Xouz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e7aef0c3b3f70926b69b449e66a0058cb97a4f65/120-ng-manager/modules/ng-variable/src/main/java/io/harness/ng/core/variable/resources/VariableResourceImpl.java#L37)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Pls make sure all Harness annotations (like @InternalApi etc) on Resource are also applied here because Harness annotations don't take effect on interfaces
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-variable/src/main/java/io/harness/serializer/NGVariableRegistrars.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/34410#-N591cv-8wJ064Z9CwfN:-N5A6Fc59vV0kqby8nD9:b-on8rrz) ([raw file](https://github.com/harness/harness-core/blob/e7aef0c3b3f70926b69b449e66a0058cb97a4f65/120-ng-manager/modules/ng-variable/src/main/java/io/harness/serializer/NGVariableRegistrars.java#L20)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why do we need morphia registrars?
</blockquote></details>

As discussed this can't be avoided as of now.
___
*[`120-ng-manager/modules/ng-variable/src/main/java/io/harness/serializer/morphia/NGVariableMorphiaRegistrar.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/34410#-N590HNECjeVayni1LUE:-N5A6ddR0CG8OHcC6_zS:b-chzbcx) ([raw file](https://github.com/harness/harness-core/blob/e7aef0c3b3f70926b69b449e66a0058cb97a4f65/120-ng-manager/modules/ng-variable/src/main/java/io/harness/serializer/morphia/NGVariableMorphiaRegistrar.java#L17)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Where
</blockquote></details>

As discussed we can't avoid Morphia registration.

**Comment by nishantsaini20** [comment]
trigger ti0

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> Reviewed 37 of 42 files at r2, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34410#-:-N5j81MqA5Bzew7a_QJ_:bnfp4nl)* status: 49 file(s) to review. 1 of 2 approvals obtained.

**Review by piyush-harness — DISMISSED** [review]
> Reviewed 3 of 42 files at r2, 1 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34410)* status: 45 file(s) to review.

**Comment by piyush-harness** [comment]
:lgtm:

**Comment by nishantsaini20** [comment]
trigger ti0

**Comment by nishantsaini20** [comment]
trigger ti1

**Review by piyush-harness — APPROVED** [review]
> Reviewed 2 of 43 files at r1, 34 of 42 files at r2, 7 of 10 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34410)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34410#-:-N5szzxZ05Y0SXu4yKOP:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
