### PR TITLE
[feat]: [PIE-7738]: Add yaml validation on resolved templates and wit…

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
…hout <+input>

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43008)

### CODE REVIEW

**Review by namanvermah — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43008)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43008)* status: 6 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/43008#-NMbHip4-2lCK85DnslV:-NMbHip595G2noVI2TAE:b-ghrtsw) ([raw file](https://github.com/harness/harness-core/blob/6a6836f2a57407d7802f776d64182cdefcd345ba/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L59)):*
> ```Java
> public class YamlUtils {
>   public final String STRATEGY_IDENTIFIER_POSTFIX = "<+strategy.identifierPostFix>";
>   private final List<String> VALIDATORS = Lists.newArrayList("allowedValues", "regex", "default", "executionInput");
> ```

for these can we add InputSetValidatorType.values so that any new validator is automatically added



_Code quote:_
```Java
allowedValues", "regex"
```
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 611 at r1](https://reviewable.io/reviews/harness/harness-core/43008#-NMbHqYx9umtuSg_fNgf:-NMbHqYx9umtuSg_fNgg:b-z3xe4f) ([raw file](https://github.com/harness/harness-core/blob/6a6836f2a57407d7802f776d64182cdefcd345ba/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L611)):*
> ```Java
>           if (trimValue.contains(validator)) {
>             ParameterField<?> parameterField = YamlUtils.read(trimValue, ParameterField.class);
>             if (parameterField.getInputSetValidator() != null) {
> ```

@sahilhindwani-harness even if it has only default then also we need to remove it right? as you mentioned timeout field will fail if given as 1h.default(12h)
i think we should not do this if and if it contains validator strings, then just get fetchFInalVaule -> as that will give you expression as well
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 617 at r1](https://reviewable.io/reviews/harness/harness-core/43008#-NMbII1l0fck-8veyAFP:-NMbII1l0fck-8veyAFQ:b-y7qdcp) ([raw file](https://github.com/harness/harness-core/blob/6a6836f2a57407d7802f776d64182cdefcd345ba/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L617)):*
> ```Java
>           }
>         }
>         if (!NGExpressionUtils.matchesRawInputSetPattern(trimValue)) {
> ```

can we check this on the valueWithoutValidator directly? it should match <+input> equals string isn't?
___
*[`953-yaml-commons/src/test/java/io/harness/pms/yaml/YamlUtilsTest.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/43008#-NMbIOwl81wmmyD_Lga8:-NMbIOwl81wmmyD_Lga9:bkb8swl) ([raw file](https://github.com/harness/harness-core/blob/6a6836f2a57407d7802f776d64182cdefcd345ba/953-yaml-commons/src/test/java/io/harness/pms/yaml/YamlUtilsTest.java#L88)):*
> ```Java
>       + "            identifier: \"stagingInfra\"\n"
>       + "            type: \"PreProduction\"\n"
>       + "            name: null\n"
> ```

we will get null or no field?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 314 at r1](https://reviewable.io/reviews/harness/harness-core/43008#-NMbIVxy3-Lfe3Qvzhov:-NMbIVxy3-Lfe3Qvzhow:bx6qtwh) ([raw file](https://github.com/harness/harness-core/blob/c4f28948738aa0886b59a54c206d22e613c9248f/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L314)):*
> ```Java
>       in pipelineYamlConfig will be 12h.allowedValues(12h, 1d) for validation during execution. However, this value will
>       give an error in schema validation. That's why we need a value that doesn't have this validator appended.
>        */
> ```

can we retain the comment as it helped us building this usecase in the code



_Code quote:_
```Java
      /*
      For schema validations, we don't want input set validators to be appended. For example, if some timeout field in
      the pipeline is <+input>.allowedValues(12h, 1d), and the runtime input gives a value 12h, the value for this field
      in pipelineYamlConfig will be 12h.allowedValues(12h, 1d) for validation during execution. However, this value will
      give an error in schema validation. That's why we need a value that doesn't have this validator appended.
       */
```

**Comment by sahilhindwani-harness** [comment]
*[`953-yaml-commons/src/test/java/io/harness/pms/yaml/YamlUtilsTest.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/43008#-NMbIOwl81wmmyD_Lga8:-NMcIoG_ByKDcrnhaY2T:bb7lkwc) ([raw file](https://github.com/harness/harness-core/blob/6a6836f2a57407d7802f776d64182cdefcd345ba/953-yaml-commons/src/test/java/io/harness/pms/yaml/YamlUtilsTest.java#L88)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we will get null or no field?
</blockquote></details>

null

**Comment by sahilhindwani-harness** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 611 at r1](https://reviewable.io/reviews/harness/harness-core/43008#-NMbHqYx9umtuSg_fNgf:-NMcQ8J_51HkVoaL3Q0l:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6a6836f2a57407d7802f776d64182cdefcd345ba/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L611)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@sahilhindwani-harness even if it has only default then also we need to remove it right? as you mentioned timeout field will fail if given as 1h.default(12h)
i think we should not do this if and if it contains validator strings, then just get fetchFInalVaule -> as that will give you expression as well
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 314 at r1](https://reviewable.io/reviews/harness/harness-core/43008#-NMbIVxy3-Lfe3Qvzhov:-NMcQE2WARKw7UDz42pQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4f28948738aa0886b59a54c206d22e613c9248f/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L314)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we retain the comment as it helped us building this usecase in the code
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/43008#-NMbHip4-2lCK85DnslV:-NMcQpVd7rrRbxEtqLXH:b-esznkx) ([raw file](https://github.com/harness/harness-core/blob/6a6836f2a57407d7802f776d64182cdefcd345ba/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L59)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

for these can we add InputSetValidatorType.values so that any new validator is automatically added
</blockquote></details>

default is not a part InputSetValidator, therefore created this new constant.

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43008)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
