### PR TITLE
fix: [CDS-38620]: fixed helm rollback errors

### PR DESCRIPTION
**Pull request by achyuth-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34255)

### CODE REVIEW

**Comment by achyuth-harness** [comment]
trigger pmd

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34255)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 432 at r2](https://reviewable.io/reviews/harness/harness-core/34255#-N4SHnKM05wEr5Pf0Qkj:-N4SHnKM05wEr5Pf0Qkk:byslker) ([raw file](https://github.com/harness/harness-core/blob/b1895f03400dd8851b97d4ecf35bd45827042699/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L432)):*
> ```Java
>     }
>     if (prevReleaseVersion != null) {
>       releaseHistory.setPenultimateReleaseNumber(prevReleaseVersion);
> ```

This is required only one time, to fix user release history, since no one yet reported any issues around it we can not do this
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 507 at r2](https://reviewable.io/reviews/harness/harness-core/34255#-N4SJwiQAwnZQYEr2SOI:-N4SJwiQAwnZQYEr2SOJ:b-2ppse5) ([raw file](https://github.com/harness/harness-core/blob/b1895f03400dd8851b97d4ecf35bd45827042699/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L507)):*
> ```Java
>       commandResponse.setHelmVersion(commandRequest.getHelmVersion());
> 
>       HelmCliResponse helmHistResponse =
> ```

nit: we should move this logic in getHelmChartDetails
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 952 at r2](https://reviewable.io/reviews/harness/harness-core/34255#-N4SHXiW4gfEuA7b52cl:-N4SHXiX8qPuZgMB6p6W:b32bg2y) ([raw file](https://github.com/harness/harness-core/blob/b1895f03400dd8851b97d4ecf35bd45827042699/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L952)):*
> ```Java
>     else {
>       String chartName = releaseInfo.getChart();
>       int index = chartName.indexOf('.');
> ```

Isn't format of chartName chart-name-x.y.z? So we're getting only: .y.z?

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34255)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 432 at r2](https://reviewable.io/reviews/harness/harness-core/34255#-N4SHnKM05wEr5Pf0Qkj:-N4VXfAz37z2jEM6LScA:b-79vsau) ([raw file](https://github.com/harness/harness-core/blob/b1895f03400dd8851b97d4ecf35bd45827042699/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L432)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This is required only one time, to fix user release history, since no one yet reported any issues around it we can not do this
</blockquote></details>

Will discuss offline
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 507 at r2](https://reviewable.io/reviews/harness/harness-core/34255#-N4SJwiQAwnZQYEr2SOI:-N4VfsDW0wwC95ljLvAL:bexvyon) ([raw file](https://github.com/harness/harness-core/blob/b1895f03400dd8851b97d4ecf35bd45827042699/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L507)):*
> This is required only one time, to fix user release history, since no one yet reported any issues around it we can not do this
Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 952 at r2](https://reviewable.io/reviews/harness/harness-core/34255#-N4SHXiW4gfEuA7b52cl:-N4VY8xh8yTxwFoMK3Yz:b-b6gmyd) ([raw file](https://github.com/harness/harness-core/blob/b1895f03400dd8851b97d4ecf35bd45827042699/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L952)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Isn't format of chartName chart-name-x.y.z? So we're getting only: .y.z?
</blockquote></details>

no, taking substring from index - 1

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34255)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 952 at r2](https://reviewable.io/reviews/harness/harness-core/34255#-N4SHXiW4gfEuA7b52cl:-N4VpLaD1uDyRXGHdqlZ:bu9b0bv) ([raw file](https://github.com/harness/harness-core/blob/b1895f03400dd8851b97d4ecf35bd45827042699/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L952)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

no, taking substring from index - 1
</blockquote></details>

yes, but if version is xy.z.x then the result version will be y.x.z, right?

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34255)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 952 at r2](https://reviewable.io/reviews/harness/harness-core/34255#-N4SHXiW4gfEuA7b52cl:-N4VsxtrCbPAENh7SWwj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b1895f03400dd8851b97d4ecf35bd45827042699/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L952)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

yes, but if version is xy.z.x then the result version will be y.x.z, right? 
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34255)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 943 at r4](https://reviewable.io/reviews/harness/harness-core/34255#-N4Vw37uBOXUPgSxXLRi:-N4Vw37uBOXUPgSxXLRj:bk28ogw) ([raw file](https://github.com/harness/harness-core/blob/abd04837bcff3c25da4e8a2370c4242332d83573/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L943)):*
> ```Java
>       String chartName = releaseInfoList.get(releaseInfoList.size() - 1).getChart();
>       int index = chartName.indexOf('.');
>       while (chartName.charAt(index) != '-') {
> ```

can use lastIndexOf('-') instead chartName.indexOf('.')

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34255)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 943 at r4](https://reviewable.io/reviews/harness/harness-core/34255#-N4Vw37uBOXUPgSxXLRi:-N4W-sy77M5uxoa8m1sK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/abd04837bcff3c25da4e8a2370c4242332d83573/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L943)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

can use lastIndexOf('-') instead chartName.indexOf('.')
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34255#-:-N4W0DFC1VEyiVo84z0f:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
