### PR TITLE
techdebt: [CDS-77763]: Use service based streams for pipeline-service

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53075)

### CODE REVIEW

**Review by harshjain12 — DISMISSED** [review]

**Review by deepak-harness — APPROVED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53075)* status: 29 file(s) to review. Waiting on team(s): sto.

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53075)* status: 1 change requests. Waiting on team(s): sto. 

___
*[`310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerApplication.java` line 469 at r1](https://reviewable.io/reviews/harness/harness-core/53075#-Neq2r4m2ehIu9wuaA_o:-Neq2r4m2ehIu9wuaA_p:b-yvulmc) ([raw file](https://github.com/harness/harness-core/blob/9cd5f306729a40d0b31ce816bebfb905de4a1543/310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerApplication.java#L469)):*
> ```Java
>     pipelineEventConsumerController.register(injector.getInstance(NodeStartEventRedisConsumerV2.class), 2);
>     pipelineEventConsumerController.register(injector.getInstance(NodeProgressEventRedisConsumerV2.class), 1);
>     pipelineEventConsumerController.register(injector.getInstance(NodeAdviseRedisConsumerV2.class), 2);
> ```

Do we need 2 threads?

**Review by archit-harness — APPROVED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53075)* status: 1 change requests. Waiting on team(s): sto.

**Comment by sahilhindwani-harness** [comment]
*[`310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerApplication.java` line 469 at r1](https://reviewable.io/reviews/harness/harness-core/53075#-Neq2r4m2ehIu9wuaA_o:-Neq3Zqq92wJL2sfXO7S:b-uwmfn9) ([raw file](https://github.com/harness/harness-core/blob/9cd5f306729a40d0b31ce816bebfb905de4a1543/310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerApplication.java#L469)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Do we need 2 threads?
</blockquote></details>

Have tried to keep the same configuration as earlier, will check with idp team if they really need two threads.

**Review by hextechpal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53075)* status: Waiting on team(s): sto. 

___
*[`310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerApplication.java` line 469 at r1](https://reviewable.io/reviews/harness/harness-core/53075#-Neq2r4m2ehIu9wuaA_o:-Neq6WvuEte8QVYcC_NN:bxl9x5b) ([raw file](https://github.com/harness/harness-core/blob/9cd5f306729a40d0b31ce816bebfb905de4a1543/310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerApplication.java#L469)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Have tried to keep the same configuration as earlier, will check with idp team if they really need two threads.
</blockquote></details>

I think they just copied too lets make this 1 in every place we never need 2 threads, I am approving the PR for now though

**Review by hextechpal — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53075)* status: Waiting on team(s): sto.

**Review by sandeepa-kv-jois — DISMISSED** [review]

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53075)* status: Waiting on team(s): sto. 

___
*[`pipeline-service/config/config.yml` line 673 at r1](https://reviewable.io/reviews/harness/harness-core/53075#-NeqKJdT90CAxqbLTQwF:-NeqKJdT90CAxqbLTQwG:b-qn4ejs) ([raw file](https://github.com/harness/harness-core/blob/9cd5f306729a40d0b31ce816bebfb905de4a1543/pipeline-service/config/config.yml#L673)):*
> ```YAML
> graphConsumerSleepIntervalMs: ${GRAPH_CONSUMER_SLEEP_INTERVAL_MS:-0}
> 
> streamPerServiceConfiguration: ${PIE_STREAM_PER_SERVICE:- fale}
> ```

typo  "false"



_Code quote:_
```YAML
fale
```

**Comment by sahilhindwani-harness** [comment]
trigger review

**Comment by sahilhindwani-harness** [comment]
trigger review

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger ut9

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53075)* status: 7 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Pull request merged**
