### PR TITLE
Fix: [CDS-75213]: Add policy step details to console

### PR DESCRIPTION
**Pull request by yagyanshbhatia**
## Describe your changes

Add changes to support showing policy step details in the console view

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51901)

### CODE REVIEW

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51901)* status: :shipit: complete! ✓

**Comment by yagyanshbhatia** [comment]
trigger messagecheck

**Comment by yagyanshbhatia** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51901)* status: :shipit: complete! ✓

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/policy/step/PolicyStep.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/51901#-NcRhtz6EYleiAdUFbV_:-NcRhtz6EYleiAdUFbVa:b-2xlz68) ([raw file](https://github.com/harness/harness-core/blob/a61ec22b94c805f8a100573691a8597a1edf4467/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/policy/step/PolicyStep.java#L128)):*
> ```Java
> 
>     ILogStreamingStepClient logStreamingStepClient = logStreamingStepClientFactory.getLogStreamingStepClient(ambiance);
>     logStreamingStepClient.openStream(policyStepSpecParameters.COMMAND_UNIT);
> ```

instead you can pass flag true, it will be handled right?



_Code quote:_
```Java
logStreamingStepClient.openStream(policyStepSpecParameters.COMMAND_UNIT);
```
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/policy/step/PolicyStep.java` line 146 at r1](https://reviewable.io/reviews/harness/harness-core/51901#-NcRiA5I6PLOMOHcwMBe:-NcRiA5I6PLOMOHcwMBf:b-s4uei) ([raw file](https://github.com/harness/harness-core/blob/a61ec22b94c805f8a100573691a8597a1edf4467/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/policy/step/PolicyStep.java#L146)):*
> ```Java
>                     Red));
>           });
>         }
> ```

can you extract into another method?



_Code quote:_
```Java
      outcome.getPolicySetDetails().forEach((policySetName, policySetOutcome) -> {
        saveExecutionLog(logCallback,
            color(format("PolicySet: %s status : %s", policySetName, policySetOutcome.getStatus()), Yellow));
        if (policySetOutcome.getStatus().equals(OpaConstants.OPA_STATUS_ERROR)) {
          policySetOutcome.getPolicyDetails().forEach((policyName, policyOutcome) -> {
            String denyMessages = String.join(", ", policyOutcome.getDenyMessages());
            saveExecutionLog(logCallback,
                color(
                    format("Policy: %s, status: %s, details: %s", policyName, policyOutcome.getStatus(), denyMessages),
                    Red));
          });
        }
```

**Review by yagyanshbhatia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51901)* status: 1 change requests. 2. unresolved discussions. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/policy/step/PolicyStep.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/51901#-NcRhtz6EYleiAdUFbV_:-NcWBdK03UvIa8Y-FE3W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a61ec22b94c805f8a100573691a8597a1edf4467/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/policy/step/PolicyStep.java#L128)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

instead you can pass flag true, it will be handled right?
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/policy/step/PolicyStep.java` line 146 at r1](https://reviewable.io/reviews/harness/harness-core/51901#-NcRiA5I6PLOMOHcwMBe:-NcWBdvb-a7vPIZ2yjNB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a61ec22b94c805f8a100573691a8597a1edf4467/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/policy/step/PolicyStep.java#L146)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you extract into another method?
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51901)* status: :shipit: complete! ✓

**Comment by yagyanshbhatia** [comment]
trigger uts

**Comment by yagyanshbhatia** [comment]
trigger review

**Comment by yagyanshbhatia** [comment]
trigger uts

**Comment by yagyanshbhatia** [comment]
trigger uts

**Comment by yagyanshbhatia** [comment]
trigger uts

**Comment by yagyanshbhatia** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51901)* status: :shipit: complete! ✓

**Comment by yagyanshbhatia** [comment]
trigger review, messagecheck

**Comment by yagyanshbhatia** [comment]
trigger uts, messagechecks

**Comment by yagyanshbhatia** [comment]
trigger ss, codebasehash, ut5, ut6, ut9, pmd

**Comment by yagyanshbhatia** [comment]
trigger checkstylecodeformat

**Comment by yagyanshbhatia** [comment]
trigger checkstylecodeformat

**Comment by yagyanshbhatia** [comment]
trigger uts, checkstylecodeformat, messagechecks, pmd

**Comment by yagyanshbhatia** [comment]
trigger smartchecks

**Comment by yagyanshbhatia** [comment]
trigger ut1, ut4, ut5, ut6

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51901)* status: :shipit: complete! ✓

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51901)* status: :shipit: complete! ✓

**Comment by yagyanshbhatia** [comment]
trigger review

**Pull request merged**
