### PR TITLE
feat: [PIE-2569]: Renaming module 878 to better module name

### PR DESCRIPTION
**Pull request by archit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30675)

### CODE REVIEW

**Comment by archit-harness** [comment]
trigger FunctionalTest1

**Comment by archit-harness** [comment]
trigger FunctionalTest1

**Comment by archit-harness** [comment]
trigger ft1

**Review by hextechpal — APPROVED** [review]
> Reviewed 100 of 100 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30675)* status: 100 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 100 of 100 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30675)* status: :shipit: complete! ✓

**Pull request merged**
