### PR TITLE
feat:[CDS-80717]: Reduce number of exported logs to download on each request

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- The customer want to increase the number of downloads per day and accept reduce the number of logs to download to just one. The initial request can be done over our structure of rate limit and set a higher value to that account. However, the second change need a code change.
- We are going to reduce the number of logs to download to 5 to provide some margin.
- The change is behind a FF.
- To change the rate limit of `EXPORT_EXECUTIONS_REQUEST` we need an OPS ticket and request to add a document to `allowedLimits` collection.

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53800)

### CODE REVIEW

**Comment by Fernando-Dourado** [comment]
trigger uts

**Review by anilchowdhury-harness — APPROVED** [review]

**Comment by Fernando-Dourado** [comment]
trigger ut5

**Review by vcalasansh — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53800#-:-Ng4-f5U3pia0n7WRwSp:bnfp4nl)* status: 3 file(s) to review.

**Comment by Fernando-Dourado** [comment]
trigger review

**Review by puthrayaharness — APPROVED** [review]

**Pull request merged**
