### PR TITLE
feat: [PL-38974]: Allow deletion of SCIM users

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
We will now support deletion of externallyManaged user from the UI with a warning. Hence, to support this, we are removing the externallyManaged check from the backend API for user deletion.

Testing (the below scenarios are tried with the FF- "PL_USER_DELETION_V2" enabled):-
1. Tested deleting a SCIM managed user in NG, who is not SCIM managed in CG -> User deletion successful from NG.
2. Tested deleting a SCIM managed user in NG, who is also SCIM managed in CG -> User deletion successful from NG.
3. Tested deleting a SCIM managed user in CG, who is also present in NG -> User is not deleted. However, they get removed from all the userGroups in CG (which is the current behaviour).
4. Tested deleting a SCIM managed user in CG, who is not present in NG -> User deletion successful from CG.

The UI modal for SCIM user deletion:-
Screenshot 2023-05-26 at 2 27 31 PM

Screenshot 2023-05-26 at 5 01 11 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48404)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Comment by pbarapatre10** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 617 at r3](https://reviewable.io/reviews/harness/harness-core/48404#-NWXB1k68E8zfQ6LYBKh:-NWXB1k795Kkdf1Z8WdP:bledykx) ([raw file](https://github.com/harness/harness-core/blob/9880a13462641eb16ded8933b579103157627cf4/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L617)):*
> ```Java
>     if ((ScopeLevel.ACCOUNT.equals(ScopeLevel.of(accountIdentifier, orgIdentifier, projectIdentifier)))
>         && isUserExternallyManaged(userId, accountIdentifier)) {
>       log.error("Externally managed user with userId: {} is being deleted from account: {}", userId, accountIdentifier);
> ```

Minor: This should be log.warn now, since we are warning users and going ahead to delete the user. Thanks



_Code quote:_
```Java
log.error(
```

**Comment by pbarapatre10** [comment]
> -   Tested deleting a SCIM managed user in NG, who is not SCIM managed in CG -> User deletion successful from NG.
> -   Tested deleting a SCIM managed user in NG, who is also SCIM managed in CG -> User deletion successful from NG.
> -   Tested deleting a SCIM managed user in CG, who is also present in NG -> User is not deleted. However, they get removed from all the userGroups in CG (which is the current behaviour).
> -   Tested deleting a SCIM managed user in CG, who is not present in NG -> User deletion successful from CG.


If not tested we should test these scenarios when user is part of more than one accounts across CG & NG, thanks

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48404)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48404)* status: 1 file(s) to review.

**Review by shashank-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48404)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 617 at r3](https://reviewable.io/reviews/harness/harness-core/48404#-NWXB1k68E8zfQ6LYBKh:-NWZPpr25FBYvcLXGMRM:b32v57) ([raw file](https://github.com/harness/harness-core/blob/9880a13462641eb16ded8933b579103157627cf4/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L617)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Minor: This should be log.warn now, since we are warning users and going ahead to delete the user. Thanks
</blockquote></details>

+1

**Review by shashank-harness — CHANGES_REQUESTED** [review]
Please mention what testing has been done on SCIM provider side to support this usecase.
Also, what are the steps to get unblocked if a customer mistakenly deletes a user?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48404#-:-NWZPumS1clZJXrhlmZx:b-guez1u)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by tiwaritejas** [comment]
trigger uts

**Review by shashank-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48404)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
