### PR TITLE
feat: [CDS-83938]: Update queries for acc/org scope services license calculation

### PR DESCRIPTION
**Pull request by mani5h-harness**
## Describe your changes
Update queries for acc/org scope services license calculation 

### Context
CD NG supports creating a service at account level and deploying it across orgs/projects. We also support creating a service at org level and deploying it across projects. Our current license calculation queries do not consider those to be single service, but each occurrence in a project/org combination is considered a single service. 

This PR updates the queries to consider account/org level services as single services.

This will update the license calculation in subscriptions page and CSV download api on subscriptions page.

### Changes
Updated the query for license calculation
For account level service (ie service id prefixed with 'account.'), we now consider projectId and orgId as null
For org level service (ie service id prefixed with 'org.'), we now consider projectId as null

Change is behind FF - CDS_NG_ACC_ORG_LEVEL_SERVICE_LICENSING_FIX

Testing notes 
-- The queries generated at runtime were tested on PreQA timescale DB
-- The query was tested on prod2 for MoEngage customer
-- Tested CSV download endpoint

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55569)

### CODE REVIEW

**Comment by mani5h-harness** [comment]
trigger smartchecks

**Comment by mani5h-harness** [comment]
trigger uts

**Comment by mani5h-harness** [comment]
trigger uts

**Comment by mani5h-harness** [comment]
trigger uts

**Review by ivan-83 — APPROVED** [review]
> Reviewed 6 of 8 files at r1, 6 of 7 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55569)* status: 5 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageDAL.java` line 361 at r4](https://reviewable.io/reviews/harness/harness-core/55569#-NjlZfxKDodAtXGTOTvQ:-NjlZfxKDodAtXGTOTvR:b-wft2hl) ([raw file](https://github.com/harness/harness-core/blob/5118b137bf9fa84008031e6163e5cfa27b7254c8/125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageDAL.java#L361)):*
> ```Java
> 
>     final String fetchActiveServicesFinalQuery;
>     if (featureFlagService.isEnabled(accountIdentifier, FeatureName.CDS_NG_ACC_ORG_LEVEL_SERVICE_LICENSING_FIX)) {
> ```

Minor: we could only use get query based on FF and then on query apply replace methods. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageDAL.java` line 428 at r4](https://reviewable.io/reviews/harness/harness-core/55569#-Njlgi-B0THCeqmybOvP:-Njlgi-B0THCeqmybOvQ:b-39lwws) ([raw file](https://github.com/harness/harness-core/blob/5118b137bf9fa84008031e6163e5cfa27b7254c8/125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageDAL.java#L428)):*
> ```Java
>     final String fetchActiveServicesNameOrgAndProjectNameFinalQuery;
>     if (featureFlagService.isEnabled(accountIdentifier, FeatureName.CDS_NG_ACC_ORG_LEVEL_SERVICE_LICENSING_FIX)) {
>       fetchActiveServicesNameOrgAndProjectNameFinalQuery =
> ```

Minor: the same as above

**Comment by mani5h-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageDAL.java` line 361 at r4](https://reviewable.io/reviews/harness/harness-core/55569#-NjlZfxKDodAtXGTOTvQ:-NjlsL0o35VHK1L3hvcl:bx81445) ([raw file](https://github.com/harness/harness-core/blob/5118b137bf9fa84008031e6163e5cfa27b7254c8/125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageDAL.java#L361)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor: we could only use get query based on FF and then on query apply replace methods.
</blockquote></details>

yes, but that would cost us making the string non final, as it will have to reassigned later after replaces.
Keeping it this way to keep the string final.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55569#-:-NjlvNMl7uo0KuPPyGKv:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by mani5h-harness** [comment]
trigger uts

**Comment by mani5h-harness** [comment]
trigger uts

**Pull request merged**
