### PR TITLE
[feat]: [PL-29058]:  Add Saml origin fallback to accountId match when 'origin' header doesn't match

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
Currently in 'manager' for SAML login, we rely on the 'origin' referrer header coming from IdP along with SAML response. This is used to locate the SSO settings and determine the type of SAML IdP (Google, Microsoft, Other, etc). Few Customers do have IdP configured under vanity URL with multiple instances behind it, and thus multiple origin coming along in header of SAML response, after successful authentication. In this change set introduced a fallback to check SSOSettings of SAML type in account, if one with the origin can't be found. This would resolve scenario for such customers without impacting anything on current flow.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39179)

### CODE REVIEW

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39179)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 413 at r1](https://reviewable.io/reviews/harness/harness-core/39179#-NFSLZZ_-GLNZmDYMYsY:-NFSLZZ_-GLNZmDYMYsZ:bkaa9n) ([raw file](https://github.com/harness/harness-core/blob/7f8c880e1161061a916a1237a0d8caffaf1f41d9/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L413)):*
> ```Java
>                   .equal(accountId)
>                   .field("type")
>                   .equal(SSOType.SAML);
> ```

nit: just sharing a thought, if collection is SamlSettings then we don't need a query filter like type=SSOType.SAML

**Review by boopesh007 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39179)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 413 at r1](https://reviewable.io/reviews/harness/harness-core/39179#-NFSLZZ_-GLNZmDYMYsY:-NFSQvw-3V1S8k4RGs4O:bfmoqjn) ([raw file](https://github.com/harness/harness-core/blob/7f8c880e1161061a916a1237a0d8caffaf1f41d9/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L413)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

nit: just sharing a thought, if collection is SamlSettings then we don't need a query filter like type=SSOType.SAML
</blockquote></details>

mongo Collection is ssoSettings with property 'type' used as name for Saml, Ldap, OAuth. Its best to use this type as accountId , type is also used as index so query will be faster as well. Thanks

**Review by kapil-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39179#-:-NFSSbiE2ka95Zu8XScU:bnfp4nl)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 413 at r1](https://reviewable.io/reviews/harness/harness-core/39179#-NFSLZZ_-GLNZmDYMYsY:-NFSSZGN3NHl8aIECnFS:b-ciey3m) ([raw file](https://github.com/harness/harness-core/blob/7f8c880e1161061a916a1237a0d8caffaf1f41d9/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L413)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

mongo Collection is ssoSettings with property 'type' used as name for Saml, Ldap, OAuth. Its best to use this type as accountId , type is also used as index so query will be faster as well. Thanks
</blockquote></details>

ok, thanks

**Pull request merged**
