### PR TITLE
[feat]: [CDS-34869]: Add init support for exec ssh task

### PR DESCRIPTION
**Pull request by vitsafronovici**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31607)

### CODE REVIEW

**Comment by vitsafronovici** [comment]
trigger messagecheck

**Comment by vitsafronovici** [comment]
trigger messagecheck

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 12 of 15 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31607)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java, line 40 at r3](https://reviewable.io/reviews/harness/harness-core/31607#-MyqxmNn6Zz5OUpAJADM:-MyqxmNoDCgj1u5x-mci:bm1swad) ([raw file](https://github.com/harness/harness-core/blob/23d331e8255a8c189d0a192c2b909c44408ef2c4/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java#L40)):*
> ```Java
> @OwnedBy(CDP)
> public class CommandTaskNG extends AbstractDelegateRunnableTask {
>   public static final String COMMAND_UNIT = "Execute";
> ```

we will be passing command execution logs from the step itself, i guess this is not needed.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java, line 69 at r3](https://reviewable.io/reviews/harness/harness-core/31607#-MyqyBhL5mMtOewGPejJ:-MyqyBhME3n8VxCVHlMt:b-cbqcke) ([raw file](https://github.com/harness/harness-core/blob/23d331e8255a8c189d0a192c2b909c44408ef2c4/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java#L69)):*
> ```Java
>   }
> 
>   private DelegateResponseData runSsh(SshCommandTaskParameters parameters) {
> ```

we have to cover 2 cases here:
1. Execute on delegate
2. Execute on host (i think we only cover this item in code)



_Code quote:_
```Java
ScriptSshExecutor
```
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java, line 86 at r3](https://reviewable.io/reviews/harness/harness-core/31607#-Myqyw8n5uK0-5kC_TgF:-Myqyw8n5uK0-5kC_TgG:b-v94por) ([raw file](https://github.com/harness/harness-core/blob/23d331e8255a8c189d0a192c2b909c44408ef2c4/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java#L86)):*
> ```Java
>         cleanupSsh(parameters, executor);
>       } catch (Exception e) {
>         log.warn("Failed to cleanup ssh {0}", e.getMessage());
> ```

we should mark the task as Failed if for some reason we failed to cleanup or init.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java, line 108 at r3](https://reviewable.io/reviews/harness/harness-core/31607#-MyqzFj69EmN-0pnAjBg:-MyqzFj69EmN-0pnAjBh:b-frcrop) ([raw file](https://github.com/harness/harness-core/blob/23d331e8255a8c189d0a192c2b909c44408ef2c4/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java#L108)):*
> ```Java
>   }
> 
>   private void cleanupSsh(SshCommandTaskParameters taskParameters, ScriptSshExecutor executor) {
> ```

nit: perhaps we might need to extract this into separate class so that it can be re-used later on when by other steps also.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 35 at r3](https://reviewable.io/reviews/harness/harness-core/31607#-MyqzvVG23Lgvo6X6JFz:-MyqzvVG23Lgvo6X6JG-:b-f017rt) ([raw file](https://github.com/harness/harness-core/blob/23d331e8255a8c189d0a192c2b909c44408ef2c4/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L35)):*
> ```Java
> @OwnedBy(CDP)
> @Singleton
> public class SshInitCommandTaskNG {
> ```

Usually we name with Task what's a delegate task, for this particular case we can use `SshInitCommandHandler` or anything else meaningfull.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31607)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java, line 70 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrA3dx6UQdQ6qLooZh:-MyrA3dx6UQdQ6qLooZi:b-arqae1) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java#L70)):*
> ```Java
> 
>     try {
>       String script = sshInitCommandTaskNG.prepareScript(
> ```

we could extract prepreScript as well as cleanUp methods to some new class
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java, line 108 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrAamL8xSdVk0k9YDy:-MyrAamL8xSdVk0k9YDz:b-y0kvlr) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java#L108)):*
> ```Java
>     if (CommandExecutionStatus.SUCCESS != status) {
>       throw new RuntimeException("Failed to cleanup");
>     }
> ```

we could return true or false instead of throwing an exception
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 36 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrAmOWEAecv4dP8RCW:-MyrAmOWEAecv4dP8RCX:bvfqggf) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L36)):*
> ```Java
> @Singleton
> public class SshInitCommandTaskNG {
>   private static final String EXECLAUNCHERV2_SH_FTL = "execlauncherv2.sh.ftl";
> ```

Moving constants into some Constants class. 
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 41 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrBxZY6wBAJUc_Ds4s:-MyrBxZY6wBAJUc_Ds4t:behbzpu) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L41)):*
> ```Java
>   static final String PRE_INIT_COMMAND_ERR_MSG = "Failed to run PreInitCommand";
> 
>   private static final Configuration cfg = new Configuration(VERSION_2_3_23);
> ```

We could move logic for population Configuration into a separate class ScriptConfigurationLoader or SshConfigurationLoader or ....
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 47 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrCMJb3danzrwbApCF:-MyrCMJb3danzrwbApCG:b-h9pkqm) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L47)):*
> ```Java
>       StringTemplateLoader stringLoader = new StringTemplateLoader();
> 
>       InputStream execLauncherInputStream =
> ```

extract to a separate method 
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 50 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrCPZ-2gxeMVizv8C2:-MyrCPZ-2gxeMVizv8C3:bm2wps4) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L50)):*
> ```Java
>           SshInitCommandTaskNG.class.getClassLoader().getResourceAsStream("commandtemplates/" + EXECLAUNCHERV2_SH_FTL);
>       if (execLauncherInputStream == null) {
>         throw new RuntimeException(EXECLAUNCHERV2_SH_FTL + " file is missing.");
> ```

be specific with the exception 
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 56 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrCUCe1IwZ2byfIbsJ:-MyrCUCe1IwZ2byfIbsK:b-h9pkqm) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L56)):*
> ```Java
>           convertToUnixStyleLineEndings(IOUtils.toString(execLauncherInputStream, StandardCharsets.UTF_8)));
> 
>       InputStream tailWrapperInputStream =
> ```

extract to a separate method 
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 59 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrCWF6C7scvCJefoTD:-MyrCWF6C7scvCJefoTE:bm2wps4) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L59)):*
> ```Java
>           SshInitCommandTaskNG.class.getClassLoader().getResourceAsStream("commandtemplates/" + TAILWRAPPERV2_SH_FTL);
>       if (tailWrapperInputStream == null) {
>         throw new RuntimeException(TAILWRAPPERV2_SH_FTL + " file is missing.");
> ```

be specific with the exception 
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 92 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrCdUY0EWJHDGq39Z6:-MyrCdUY0EWJHDGq39Z7:boh2hfv) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L92)):*
> ```Java
> 
>     } catch (IOException | TemplateException e) {
>       throw new RuntimeException(e);
> ```

throw more Harness specific runtime exception 
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 108 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrEi719PtdTWuDTRKG:-MyrEi719PtdTWuDTRKH:b-oy8snk) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L108)):*
> ```Java
>   }
> 
>   private String generateExecLauncherV2Command(SshCommandTaskParameters taskParameters, boolean includeTailFunctions)
> ```

We could move this logic for generation generateTailWrapperV2Command, generateExecLauncherV2Command commands into a separate class.

**Comment by acasian-harness** [comment]
trigger ti0

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31607)* status: :shipit: complete! ✓

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31607)* status: 1 change requests. 10. unresolved discussions. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java, line 70 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrA3dx6UQdQ6qLooZh:-Mywwd_3BbHbfXy0aoWy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java#L70)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

we could extract prepreScript as well as cleanUp methods to some new class
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java, line 108 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrAamL8xSdVk0k9YDy:-Mywx2I6EaHG7tdq1c1N:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java#L108)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

we could return true or false instead of throwing an exception
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 36 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrAmOWEAecv4dP8RCW:-Mywx4tyCt0MAPQUogWF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L36)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Moving constants into some Constants class. 
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 41 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrBxZY6wBAJUc_Ds4s:-Mywx5Id6pARx79B-kGy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L41)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We could move logic for population Configuration into a separate class ScriptConfigurationLoader or SshConfigurationLoader or ....
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 47 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrCMJb3danzrwbApCF:-Mywx6VX3kqtRtsR_faJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L47)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

extract to a separate method 
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 50 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrCPZ-2gxeMVizv8C2:-Mywx6xo3ntfdY8rY5Y1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L50)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

be specific with the exception 
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 56 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrCUCe1IwZ2byfIbsJ:-Mywx7M_BxvMoENs6NK8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L56)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

extract to a separate method 
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 59 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrCWF6C7scvCJefoTD:-Mywx9eLChtcH6m2-jFs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L59)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

be specific with the exception 
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 92 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrCdUY0EWJHDGq39Z6:-MywxAJEBcR8kq--BGrD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L92)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

throw more Harness specific runtime exception 
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java, line 108 at r4](https://reviewable.io/reviews/harness/harness-core/31607#-MyrEi719PtdTWuDTRKG:-MywxAw6AkgZr3jcNWgm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d64bb6811c9ccfac3d7d4118106f9281524cb71e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandTaskNG.java#L108)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We could move this logic for generation generateTailWrapperV2Command, generateExecLauncherV2Command commands into a separate class. 
</blockquote></details>

Done.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31607)* status: :shipit: complete! ✓

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java, line 75 at r5](https://reviewable.io/reviews/harness/harness-core/31607#-Mz-ZhFs7po99Zg7xqtw:-Mz-ZhFs7po99Zg7xqtx:bc4sjn4) ([raw file](https://github.com/harness/harness-core/blob/a3a7c29b6cbf386694e3da1439d84e5a80f3a9f9/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java#L75)):*
> ```Java
>     CommandUnitsProgress commandUnitsProgress = CommandUnitsProgress.builder().build();
> 
>     Function<String, AbstractScriptExecutor> getExecutorFun =
> ```

Minor - 
Function<String, AbstractScriptExecutor> getExecutorFun =(commandUnit) -> getExecutor(parameters, commandUnit, commandUnitsProgress); 
And, 
AbstractScriptExecutor initExecutor = getExecutorFun.apply(SshCommandUnitConstants.Init)

AbstractScriptExecutor someExecutor = getExecutor(parameters, SshCommandUnitConstants.Init, commandUnitsProgress)

Same for others snippets.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/utils/Action.java, line 11 at r5](https://reviewable.io/reviews/harness/harness-core/31607#-Mz-_F0yBjXNzWbR9cZB:-Mz-_F0z5dXiTmH_KqBN:b-7e0od1) ([raw file](https://github.com/harness/harness-core/blob/a3a7c29b6cbf386694e3da1439d84e5a80f3a9f9/930-delegate-tasks/src/main/java/io/harness/delegate/utils/Action.java#L11)):*
> ```Java
> 
> @FunctionalInterface
> public interface Action {
> ```

Minor - Rename Action to NoArgsConsumer or similar also move to the common module.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/utils/LazyInit.java, line 13 at r5](https://reviewable.io/reviews/harness/harness-core/31607#-Mz-_1lG8eketYQM4OzK:-Mz-_1lG8eketYQM4OzL:b-aqwaom) ([raw file](https://github.com/harness/harness-core/blob/a3a7c29b6cbf386694e3da1439d84e5a80f3a9f9/930-delegate-tasks/src/main/java/io/harness/delegate/utils/LazyInit.java#L13)):*
> ```Java
> import java.util.function.Supplier;
> 
> public class LazyInit {
> ```

 If we really need lazy init move this to some common module.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/utils/LazyInit.java, line 22 at r5](https://reviewable.io/reviews/harness/harness-core/31607#-Mz-_Iqe2COEq_rgP6NI:-Mz-_Iqe2COEq_rgP6NJ:bjzor0u) ([raw file](https://github.com/harness/harness-core/blob/a3a7c29b6cbf386694e3da1439d84e5a80f3a9f9/930-delegate-tasks/src/main/java/io/harness/delegate/utils/LazyInit.java#L22)):*
> ```Java
>    * @return T singleton
>    */
>   public static <T> T apply(Object lock, Supplier<T> load, Action init) {
> ```

If I call LazyInit.applay(SomeClass.class, () -> new SomeClass(), someInitAction) first apply method in several places in code I will break singleton pattern right, or missing something.  
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/utils/LazyInit.java, line 45 at r5](https://reviewable.io/reviews/harness/harness-core/31607#-Mz-ZyT41359inuENSi_:-Mz-ZyT41359inuENSia:b-qvlz8i) ([raw file](https://github.com/harness/harness-core/blob/a3a7c29b6cbf386694e3da1439d84e5a80f3a9f9/930-delegate-tasks/src/main/java/io/harness/delegate/utils/LazyInit.java#L45)):*
> ```Java
>    * @param init Action - function that runs the singleton creation block
>    */
>   public static void apply(Object lock, BooleanSupplier condition, Action init) {
> ```


Maybe we don’t want to lock all methods in some class for the second apply method, instead of it creating a lock object within LazyInit class.
Minor - Try to use Intrinsic(ReentrantLock) instead of Explicit locking 
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandHandler.java, line 47 at r5](https://reviewable.io/reviews/harness/harness-core/31607#-Mz-ZbPG8gPoiPXJcYcR:-Mz-ZbPHAooHXwG7ZYdg:bezhaem) ([raw file](https://github.com/harness/harness-core/blob/a3a7c29b6cbf386694e3da1439d84e5a80f3a9f9/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandHandler.java#L47)):*
> ```Java
>     try {
>       String generatedExecLauncherV2Command = generateExecLauncherV2Command(taskParameters, includeTailFunctions);
>       StringBuilder preparedCommand = new StringBuilder(generatedExecLauncherV2Command);
> ```

Very nice thing you replaced StringBuffer with StringBuilder.

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31607)* status: 1 change requests. 1. unresolved discussions. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/utils/LazyInit.java, line 22 at r5](https://reviewable.io/reviews/harness/harness-core/31607#-Mz-_Iqe2COEq_rgP6NI:-Mz-cE1PBdxSjX2U4lY9:bladpqj) ([raw file](https://github.com/harness/harness-core/blob/a3a7c29b6cbf386694e3da1439d84e5a80f3a9f9/930-delegate-tasks/src/main/java/io/harness/delegate/utils/LazyInit.java#L22)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

If I call LazyInit.applay(SomeClass.class, () -> new SomeClass(), someInitAction) first apply method in several places in code I will break singleton pattern right, or missing something.  
</blockquote></details>

But singleton pattern means that an instance needs to be assigned to something. E.g: 
MyClass getInstance() { return instance; } // assigned to instance ref
OR
myMap.get("someKey") // assigned to ref under a key
The Supplier should return the same ref instead of creating a new instance, that's why it is named load, but init creates and assigns instance to ref

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31607)* status: 1 change requests. 2. unresolved discussions. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/utils/LazyInit.java, line 45 at r5](https://reviewable.io/reviews/harness/harness-core/31607#-Mz-ZyT41359inuENSi_:-Mz-e_Vq8wdODx8zw6Tv:b4d3mp) ([raw file](https://github.com/harness/harness-core/blob/a3a7c29b6cbf386694e3da1439d84e5a80f3a9f9/930-delegate-tasks/src/main/java/io/harness/delegate/utils/LazyInit.java#L45)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>


Maybe we don’t want to lock all methods in some class for the second apply method, instead of it creating a lock object within LazyInit class.
Minor - Try to use Intrinsic(ReentrantLock) instead of Explicit locking 
</blockquote></details>

The double check locking pattern prevents from locking, it will enter the lock block ideally once when creating and assigning the init phase. In case of multithreading it could enter a couple of times, but this is again only during init, once the init is executed, it will not enter in any locks

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31607)* status: 1 change requests. 3. unresolved discussions. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java, line 75 at r5](https://reviewable.io/reviews/harness/harness-core/31607#-Mz-ZhFs7po99Zg7xqtw:-Mz-oCpQ2yC6JuRkabj8:beutmlc) ([raw file](https://github.com/harness/harness-core/blob/a3a7c29b6cbf386694e3da1439d84e5a80f3a9f9/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/CommandTaskNG.java#L75)):*
> SshInitCommandHandler
it just makes it much readable with one arg

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31607)* status: 1 change requests. 4. unresolved discussions. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandHandler.java, line 47 at r5](https://reviewable.io/reviews/harness/harness-core/31607#-Mz-ZbPG8gPoiPXJcYcR:-Mz-oTzx2i2snknS_U3j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a3a7c29b6cbf386694e3da1439d84e5a80f3a9f9/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/SshInitCommandHandler.java#L47)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Very nice thing you replaced StringBuffer with StringBuilder.
</blockquote></details>

Done.

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31607)* status: 1 change requests. 4. unresolved discussions. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/utils/LazyInit.java, line 45 at r5](https://reviewable.io/reviews/harness/harness-core/31607#-Mz-ZyT41359inuENSi_:-Mz-wcuG1AH5BTJpS2l1:betiuec) ([raw file](https://github.com/harness/harness-core/blob/a3a7c29b6cbf386694e3da1439d84e5a80f3a9f9/930-delegate-tasks/src/main/java/io/harness/delegate/utils/LazyInit.java#L45)):*
<details><summary><i>Previously, vitsafronovici (Vitalie Safronovici) wrote…</i></summary><blockquote>

The double check locking pattern prevents from locking, it will enter the lock block ideally once when creating and assigning the init phase. In case of multithreading it could enter a couple of times, but this is again only during init, once the init is executed, it will not enter in any locks 
</blockquote></details>

and you could provide any lock object you wish, not necessary the class itself. I used the class because I don't have any static synchronized methods in it. But making a lock on LazyInit side could lead to more locks as many classes could use these methods

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31607)* status: 3 file(s) to review. 1 change requests. 5. unresolved discussions. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/utils/Action.java, line 11 at r5](https://reviewable.io/reviews/harness/harness-core/31607#-Mz-_F0yBjXNzWbR9cZB:-Mz0Abn53wN0PwEVXa-4:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/a3a7c29b6cbf386694e3da1439d84e5a80f3a9f9/930-delegate-tasks/src/main/java/io/harness/delegate/utils/Action.java#L11)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - Rename Action to NoArgsConsumer or similar also move to the common module.
</blockquote></details>

done
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/utils/LazyInit.java, line 13 at r5](https://reviewable.io/reviews/harness/harness-core/31607#-Mz-_1lG8eketYQM4OzK:-Mz0AWeNCWKVG4ERs-cY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a3a7c29b6cbf386694e3da1439d84e5a80f3a9f9/930-delegate-tasks/src/main/java/io/harness/delegate/utils/LazyInit.java#L13)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

 If we really need lazy init move this to some common module.
</blockquote></details>

Done.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31607#-:-Mz0BvTCCa8tPaaA-DQf:bnfp4nl)* status: :shipit: complete! ✓

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 10 of 15 files at r1, 2 of 2 files at r3, 1 of 3 files at r4, 4 of 7 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31607)* status: :shipit: complete! ✓

**Review by acasian-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31607)* status: :shipit: complete! ✓

**Pull request merged**
