### PR TITLE
feat: [CDS-17425]: Move copy files from FileBasedScriptExecutor to FileBasedScriptExecutorNG

### PR DESCRIPTION
**Pull request by vitsafronovici**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30719)

### CODE REVIEW

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30719)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30719)* status: :shipit: complete! ✓

___
*[400-rest/src/main/java/software/wings/core/ssh/executors/FileBasedAbstractScriptExecutor.java, line 199 at r2](https://reviewable.io/reviews/harness/harness-core/30719#-Mw3u2TnBAZb2gah-sEs:-Mw3u2ToAhP3XT20tg_J:b-ljqj9p) ([raw file](https://github.com/harness/harness-core/blob/056749b73ca0321e594ca9ee73711ad3557c8da1/400-rest/src/main/java/software/wings/core/ssh/executors/FileBasedAbstractScriptExecutor.java#L199)):*
> ```Java
> 
>   protected void saveExecutionLog(String line) {
>     SshHelperUtils.saveExecutionLog(line, logCallback, shouldSaveExecutionLogs);
> ```

doesn't look good to pass the boolean shouldSaveExecutionLogs to a method called saveExecutionLog
IMO better to do the check before calling the method

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30719)* status: Some of the checks are too old. 647 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.  (waiting on @acasian-harness)

___
*[400-rest/src/main/java/software/wings/core/ssh/executors/FileBasedAbstractScriptExecutor.java, line 199 at r2](https://reviewable.io/reviews/harness/harness-core/30719#-Mw3u2TnBAZb2gah-sEs:-MwQIuuY9c4vFSY5TtIQ:b-b04v26) ([raw file](https://github.com/harness/harness-core/blob/056749b73ca0321e594ca9ee73711ad3557c8da1/400-rest/src/main/java/software/wings/core/ssh/executors/FileBasedAbstractScriptExecutor.java#L199)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

doesn't look good to pass the boolean shouldSaveExecutionLogs to a method called saveExecutionLog
IMO better to do the check before calling the method
</blockquote></details>

renamed the method to be more discriptive `checkAndSaveExecutionLog`

**Comment by vitsafronovici** [comment]
it seems like someone didn't squash the commits before merging his PR and cherry-picking on my old PR branch gives me some compilation errors, I had to create a new one

**Pull request closed without merging**
