### PR TITLE
fix: [CDS-37890]: fix image tag list not coming when image path is expression in a template

### PR DESCRIPTION
**Pull request by inderschera**
## Describe your changes
When image path is expression and it comes from templates, then image tag list doesn't come up in UI.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33623)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33623)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/33623#-N3xkmNz9rNd7tbG1cvf:-N3xkmO-6Tdf3qjIqhC7:b-flgxnr) ([raw file](https://github.com/harness/harness-core/blob/e473e1da775917a4b744da7d93d395ceaa8daed0/120-ng-manager/config.yml#L56)):*
> ```YAML
>   ceNextGenServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
>   ffServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
>   templateServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
> ```

create ticket for qa, pre-qa, free, prod and on-prem to put these configs
cc: @poojasinghal 



_Code quote:_
```YAML
templateServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
```
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/33623#-N3xl4A59580F2ONEnPa:-N3xl4A59580F2ONEnPb:b3xwxiv) ([raw file](https://github.com/harness/harness-core/blob/e473e1da775917a4b744da7d93d395ceaa8daed0/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L33)):*
> ```Java
> @Slf4j
> public class ArtifactResourceUtils {
>   @Inject PipelineServiceClient pipelineServiceClient;
> ```

where is this client used?



_Code quote:_
```Java
@Inject PipelineServiceClient pipelineServiceClient
```
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/33623#-N3xlHHH7IkfOG6h5Xtn:-N3xlHHH7IkfOG6h5Xto:b-9paw7p) ([raw file](https://github.com/harness/harness-core/blob/e473e1da775917a4b744da7d93d395ceaa8daed0/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L74)):*
> ```Java
>       String pipelineIdentifier, String runtimeInputYaml, String imagePath, String fqnPath,
>       GitEntityFindInfoDTO gitEntityBasicInfo) {
>     if (EngineExpressionEvaluator.hasExpressions(imagePath)) {
> ```

before templates merge, we should merge the input set if any right?



_Code quote:_
```Java
if (EngineExpressionEvaluator.hasExpressions(
```

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33623)* status: 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/33623#-N3xkmNz9rNd7tbG1cvf:-N3xzsgqEldkBnp9AHUd:b-qy3qbu) ([raw file](https://github.com/harness/harness-core/blob/e473e1da775917a4b744da7d93d395ceaa8daed0/120-ng-manager/config.yml#L56)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

create ticket for qa, pre-qa, free, prod and on-prem to put these configs
cc: @poojasinghal 
</blockquote></details>

yes, done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/33623#-N3xl4A59580F2ONEnPa:-N3xzn9o0kkq3Cuckgpy:bo7thsu) ([raw file](https://github.com/harness/harness-core/blob/e473e1da775917a4b744da7d93d395ceaa8daed0/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L33)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

where is this client used?
</blockquote></details>

This is used to merge input set to pipeline.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/33623#-N3xlHHH7IkfOG6h5Xtn:-N3xzbJo3hcjRfWfNqpJ:bsdhkn5) ([raw file](https://github.com/harness/harness-core/blob/e473e1da775917a4b744da7d93d395ceaa8daed0/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L74)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

before templates merge, we should merge the input set if any right?
</blockquote></details>

We need to do it only when there are expressions.
We do it here.



_Code quote:_
```Java
      String mergedCompleteYaml = getMergedCompleteYaml(
          accountId, orgIdentifier, projectIdentifier, pipelineIdentifier, runtimeInputYaml, gitEntityBasicInfo);
```

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33623)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33623)* status: :shipit: complete! ✓

**Pull request merged**
