### PR TITLE
fix: [SPG-148]: AWS SDK upgrade from 1.12.220 to 1.12.261 HOT FIX

### PR DESCRIPTION
**Pull request by sainath-b**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35901)

### CODE REVIEW

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35901)* status: :shipit: complete! ✓

**Comment by arvind-choudhary-h** [comment]
*[`WORKSPACE` line 5030 at r2](https://reviewable.io/reviews/harness/harness-core/35901#-N8OPGUsDHuWObyq50lY:-N8OPGUsDHuWObyq50lZ:b-ij8lxe) ([raw file](https://github.com/harness/harness-core/blob/7f2496705dd632c29dac899f93998f53b0e77712/WORKSPACE#L5030)):*
> ```Starlark
>         group = "com.amazonaws",
>         artifact = x,
>         version = "1.12.261",
> ```

do we need to update maven_install json file?

**Comment by sainath-b** [comment]
trigger compatibility_check

**Comment by sainath-b** [comment]
trigger openapi-backward-compatibility-checks

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_NA_** 
 


            
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35901)

**Pull request closed without merging**
