### PR TITLE
feat: [CI-4587]: Delegate api changes to support V2 tasks

### PR DESCRIPTION
**Pull request by vistaarjuneja**
## Describe your changes
This PR adds support for V2 delegate tasks. CI plans to integrate the drone docker runner and VM runner with the Harness platform without depending on the java delegate. For this, we want to support V2 tasks where we can acquire and update the status of these new tasks without depending on the kryo serialization format (these runners are written in go).

This PR changes the request and response slightly for the tasks. The underlying implementation calls are still the same, only the user facing API has been changed in this PR. Before task acquisition, we convert a `DelegateTaskPackage` to a `DelegateTaskPackageV2`. And likewise, on getting a `DelegateTaskResponseV2`, we convert it into a `DelegateTaskResponse`. We use JSON as the de-facto request/response for these APIs.

It also creates a new class `TaskTypeV2` which take in the task name, the request class, and the response class. The response class declared here is used in the deserialization from the API response. This is done in `DelegateTaskResponseV2Deserializer`. 

The API endpoints have `v2` suffixed at the end.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33662)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java` line 325 at r2](https://reviewable.io/reviews/harness/harness-core/33662#-N3udZA8-RE33l8O7R9f:-N3udZA97oALXQy8N9xd:bzicnmz) ([raw file](https://github.com/harness/harness-core/blob/36228eda1c28607f61f74c08d05c1354b7b45c5f/400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java#L325)):*
> ```Java
>   @Timed
>   @ExceptionMetered
>   public DelegateTaskPackageV2 acquireDelegateTaskV2(@PathParam("delegateId") String delegateId,
> ```

we should create a new resource instead of using the same. just add v2 at the resource layer

**Comment by raghuAtWings** [comment]
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 343 at r2](https://reviewable.io/reviews/harness/harness-core/33662#-N3ueKhSDdnbpAZBdVCI:-N3ueKhU4r1ZGH-WkzzK:b-myq0uk) ([raw file](https://github.com/harness/harness-core/blob/36228eda1c28607f61f74c08d05c1354b7b45c5f/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L343)):*
> ```Java
>   SCM_PATH_FILTER_EVALUATION_TASK(TaskGroup.GIT, "SCM Path Filter Evaluation Task"),
>   SCM_GIT_REF_TASK(TaskGroup.GIT, "SCM Git Ref Task"),
>   CI_DOCKER_INITIALIZE_TASK(TaskGroup.CI),
> ```

this should be added in the end of the list

**Review by vistaarjuneja — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33662)* status: 32 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 343 at r2](https://reviewable.io/reviews/harness/harness-core/33662#-N3ueKhSDdnbpAZBdVCI:-N4XzMydC_tmPWUagG6I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/36228eda1c28607f61f74c08d05c1354b7b45c5f/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L343)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this should be added in the end of the list
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java` line 325 at r2](https://reviewable.io/reviews/harness/harness-core/33662#-N3udZA8-RE33l8O7R9f:-N4XzOB13euGoka-czv7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/36228eda1c28607f61f74c08d05c1354b7b45c5f/400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java#L325)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should create a new resource instead of using the same. just add v2 at the resource layer
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
@vistaarjuneja Can you also add review feedback from @abhinav-harness PR?

**Comment by raghuAtWings** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/TaskData.java` line 40 at r6](https://reviewable.io/reviews/harness/harness-core/33662#-N57pXeq1F3oLXSo3_cy:-N57pXer9zWF_sNZR_7Q:b-j2pr50) ([raw file](https://github.com/harness/harness-core/blob/f9ef86c779034b96642437472265d7737888988f/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/TaskData.java#L40)):*
> ```Java
>   Map<String, String> expressions;
> 
>   @Builder.Default SerializationFormat serializationFormat = SerializationFormat.KRYO;
> ```

what will happen to the tasks when delegates do not have this change?

**Comment by raghuAtWings** [comment]
*[`980-commons/src/main/java/io/harness/tasks/SerializableResponseData.java` line 10 at r6](https://reviewable.io/reviews/harness/harness-core/33662#-N57puq--XsG6jberJNl:-N57puq--XsG6jberJNm:b-kvj6ev) ([raw file](https://github.com/harness/harness-core/blob/f9ef86c779034b96642437472265d7737888988f/980-commons/src/main/java/io/harness/tasks/SerializableResponseData.java#L10)):*
> ```Java
>   byte[] serialize();
>   //  ResponseData deserialize();
> }
> ```

remove the commented method

**Review by vistaarjuneja — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33662)* status: 30 file(s) to review. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateAgentResourceV2.java` line 40 at r5](https://reviewable.io/reviews/harness/harness-core/33662#-N56HNTL6HHlVceO5hHO:-N5AJonGDQZaJ_ARViO7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b28b13c6b54c966ef09d0d86aca891bf5a48810b/400-rest/src/main/java/software/wings/resources/DelegateAgentResourceV2.java#L40)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

add v2 at the resource layer
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/TaskData.java` line 40 at r6](https://reviewable.io/reviews/harness/harness-core/33662#-N57pXeq1F3oLXSo3_cy:-N5AJr-DAd78I7Y48oA6:bc2zdwp) ([raw file](https://github.com/harness/harness-core/blob/f9ef86c779034b96642437472265d7737888988f/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/TaskData.java#L40)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

what will happen to the tasks when delegates do not have this change?
</blockquote></details>

I have done local testing with an older delegate agent and the newer versions of manager. I was able to run older tasks successfully.
___
*[`980-commons/src/main/java/io/harness/tasks/SerializableResponseData.java` line 10 at r6](https://reviewable.io/reviews/harness/harness-core/33662#-N57puq--XsG6jberJNl:-N5AK2Va2WL_L3FweBZR:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/f9ef86c779034b96642437472265d7737888988f/980-commons/src/main/java/io/harness/tasks/SerializableResponseData.java#L10)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

remove the commented method
</blockquote></details>

Done

**Comment by vistaarjuneja** [comment]
trigger ti3

**Review by raghuAtWings — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 12 files at r3, 17 of 30 files at r4, 2 of 9 files at r5, 5 of 8 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33662#-:-N5BwNF54SUJa2TwHhLA:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
