### PR TITLE
feat: [CDS-80941]: Add support for expressions in  v1 plan creator for custom stage

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Add support for expressions in  v1 plan creator for custom stage

Tested Expressions in Local with V1 pipeline with ShellScript Step

echo <+stage.name> <+stage.desc> <+stage.uuid> <+stage.delegate>  <+stage.type>
stage1 yess gdhmCMliTBekA8hs-fRqfA [a,b] custom

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53866)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 9 of 14 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53866)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/v1/StageElementParametersV1.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/53866#-NgNgHI1BjqXA4MbIyCW:-NgNgHI1BjqXA4MbIyCX:bjfepi9) ([raw file](https://github.com/harness/harness-core/blob/cbf9242907de0f8286fff6bb7997f2d13cf98ed1/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/v1/StageElementParametersV1.java#L37)):*
> ```Java
>   ParameterField<String> desc;
> 
>   ParameterField<String> skipCondition;
> ```

we don't need skipCondition. 
___
*[`pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/steps/StepSpecTypeConstantsV1.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/53866#-NgNgMV5-JcLy8B2fKqO:-NgNgMV5-JcLy8B2fKqP:b7jhggv) ([raw file](https://github.com/harness/harness-core/blob/cbf9242907de0f8286fff6bb7997f2d13cf98ed1/pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/steps/StepSpecTypeConstantsV1.java#L57)):*
> ```Java
>                                               .setStepCategory(StepCategory.STEP)
>                                               .build();
>   StepType QUEUE_STEP_TYPE =
> ```

Why adding all constants now when these are not being used? These might change when onboarded to v1. So we should add only those which we are using.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java` line 143 at r2](https://reviewable.io/reviews/harness/harness-core/53866#-NgNhVZc1g1TFlBpSMpY:-NgNhVZc1g1TFlBpSMpZ:b-1jjv1j) ([raw file](https://github.com/harness/harness-core/blob/cbf9242907de0f8286fff6bb7997f2d13cf98ed1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java#L143)):*
> ```Java
>   }
> 
>   @SneakyThrows
> ```

We should not do @SneakyThrows. Catch and handle the exception if any exception is being thrown or rethrow wingException.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java` line 178 at r2](https://reviewable.io/reviews/harness/harness-core/53866#-NgNhTpP4FNcGu-pbe6Y:-NgNhTpP4FNcGu-pbe6Z:bg1i649) ([raw file](https://github.com/harness/harness-core/blob/cbf9242907de0f8286fff6bb7997f2d13cf98ed1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java#L178)):*
> ```Java
>   }
> 
>   public SpecParameters getSpecParameters(
> ```

Why this method?

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53866)* status: 14 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/v1/StageElementParametersV1.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/53866#-NgNgHI1BjqXA4MbIyCW:-NgNrpVO2LobOAJoj3ZX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cbf9242907de0f8286fff6bb7997f2d13cf98ed1/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/v1/StageElementParametersV1.java#L37)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

we don't need skipCondition.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/steps/StepSpecTypeConstantsV1.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/53866#-NgNgMV5-JcLy8B2fKqO:-NgNz8eo2jPbimnIFQwT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cbf9242907de0f8286fff6bb7997f2d13cf98ed1/pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/steps/StepSpecTypeConstantsV1.java#L57)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Why adding all constants now when these are not being used? These might change when onboarded to v1. So we should add only those which we are using.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java` line 143 at r2](https://reviewable.io/reviews/harness/harness-core/53866#-NgNhVZc1g1TFlBpSMpY:-NgNtyLd8kiuGPKP6k0a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cbf9242907de0f8286fff6bb7997f2d13cf98ed1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java#L143)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

We should not do @SneakyThrows. Catch and handle the exception if any exception is being thrown or rethrow wingException.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java` line 178 at r2](https://reviewable.io/reviews/harness/harness-core/53866#-NgNhTpP4FNcGu-pbe6Y:-NgNrr_zCD2T9kvqYZ7B:b-aosrpu) ([raw file](https://github.com/harness/harness-core/blob/cbf9242907de0f8286fff6bb7997f2d13cf98ed1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java#L178)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Why this method?
</blockquote></details>

Done.

Yep its not required
Removed it

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53866)* status: 16 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java` line 149 at r3](https://reviewable.io/reviews/harness/harness-core/53866#-NgO-cEQ2mTN2zLl_fMW:-NgO-cEQ2mTN2zLl_fMX:b7ctw1e) ([raw file](https://github.com/harness/harness-core/blob/b0d657f8dce533ea5d3781b4e2ed1292b2b27783/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java#L149)):*
> ```Java
>       customStageNodeV1 = YamlUtils.read(config.getNode().toString(), CustomStageNodeV1.class);
>     } catch (Exception e) {
>       throw new WingsException(e);
> ```

Throw InvalidYamlException with proper error-message. By WingsException i meant any Implementation of WingsException.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53866)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53866)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/stages/v1/PmsAbstractStageNodeV1.java` line 20 at r4](https://reviewable.io/reviews/harness/harness-core/53866#-NgO49TbCQzc4mSfAiIw:-NgOPrvmC2IDK95vqLza:b-le5mbl) ([raw file](https://github.com/harness/harness-core/blob/7f837ba320cdac42f6dbd9c4d3a909e90be71567/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/stages/v1/PmsAbstractStageNodeV1.java#L20)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we already have faiure in abstract isnt?
</blockquote></details>

Done.

No we dont have failure in abstract, this is as PmsAbstractStageNode and AbstractStageNode
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java` line 43 at r4](https://reviewable.io/reviews/harness/harness-core/53866#-NgO4Djj9XolD4U8MnzZ:-NgOPz0Q3KN4kO-pzXSo:b-wrj32y) ([raw file](https://github.com/harness/harness-core/blob/7f837ba320cdac42f6dbd9c4d3a909e90be71567/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java#L43)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

do we need labels in stage? confirm with @mohitg0795
</blockquote></details>

@mohitg0795 can you please confirm ?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/CustomStageFilterCreator.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/53866#-NgO4S578zzd7h2e1s90:-NgOQ2R45ackguWHA1wP:boi2kxi) ([raw file](https://github.com/harness/harness-core/blob/7f837ba320cdac42f6dbd9c4d3a909e90be71567/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/CustomStageFilterCreator.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

if we allow v1 here, wouldnt it cause issues?
cc: @shalini-agr
</blockquote></details>

Done.
Ideally it shouldn't cause issue

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53866)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/CustomStageFilterCreator.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/53866#-NgO4S578zzd7h2e1s90:-NgOYmVX4LIVVZr_Gko1:b-w05pki) ([raw file](https://github.com/harness/harness-core/blob/7f837ba320cdac42f6dbd9c4d3a909e90be71567/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/CustomStageFilterCreator.java#L23)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
Ideally it shouldn't cause issue
</blockquote></details>

i think it will please check with @shalini-agr 
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/CustomStageVariableCreator.java` line 63 at r4](https://reviewable.io/reviews/harness/harness-core/53866#-NgO5KcV9tb05nSw-rt9:-NgOYpZ93s7uOLOEUsK-:b2w6lx8) ([raw file](https://github.com/harness/harness-core/blob/7f837ba320cdac42f6dbd9c4d3a909e90be71567/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/CustomStageVariableCreator.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we create one variable creator for all v1 version to return empty response?
</blockquote></details>

we created different variable creator for this, please check with @shalini-agr

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53866)* status: 14 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/CustomStageVariableCreator.java` line 63 at r4](https://reviewable.io/reviews/harness/harness-core/53866#-NgO5KcV9tb05nSw-rt9:-NgOuZ_B0US8AfNO3PgV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7f837ba320cdac42f6dbd9c4d3a909e90be71567/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/CustomStageVariableCreator.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we created different variable creator for this, please check with @shalini-agr
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/CustomStageFilterCreator.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/53866#-NgO4S578zzd7h2e1s90:-NgOu_sw7wZ_TFDqdoiL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7f837ba320cdac42f6dbd9c4d3a909e90be71567/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/CustomStageFilterCreator.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i think it will please check with @shalini-agr
</blockquote></details>

Done.

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by archit-harness — COMMENTED** [review]
> Reviewed 9 of 14 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53866)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 14 files at r5, 2 of 2 files at r7, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53866)* status: 15 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java` line 43 at r4](https://reviewable.io/reviews/harness/harness-core/53866#-NgO4Djj9XolD4U8MnzZ:-NgTc-bu6BKxwKi78SbE:blmshpd) ([raw file](https://github.com/harness/harness-core/blob/7f837ba320cdac42f6dbd9c4d3a909e90be71567/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java#L43)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

@archit-harness In the schema, we discussed having labels at the stage level and removing tags
so, in this DTO also, we should do the same, right?
</blockquote></details>

@utkarshchoubey-harness can we convert tags into labels?

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by shalini-agr — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53866)* status: 20 file(s) to review.

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Pull request merged**
