### PR TITLE
feat: [DEL-4098]: Add eligibleToExecuteDelegateIds field to SubmitTaskRequest

### PR DESCRIPTION
**Pull request by jennyjames21**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32749)

### CODE REVIEW

**Review by shubham149 — APPROVED** [review]

**Comment by mdmilic** [comment]
Hey @jennyjames21 could you merge from develop branch. I don't see any reason why codebase should be changed, so it's probably because you need a merge from develop (and use develop version).

**Comment by jennyjames21** [comment]
trigger ti1

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 838 at r3](https://reviewable.io/reviews/harness/harness-core/32749#-N2EE_8t7EVAj9ysmt43:-N2EE_8u7VU8g54Auon-:b-962b8x) ([raw file](https://github.com/harness/harness-core/blob/3627f52fdcc44798aa6cd5fe06c41128571ea97f/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L838)):*
> ```Java
>       log.info(
>           "Task {} has eligibleToExecuteDelegateIds:  {} ", task.getUuid(), task.getEligibleToExecuteDelegateIds());
>       return task.getEligibleToExecuteDelegateIds();
> ```

we should put something in the selection logs as well indicating thats the case

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32749)* status: 0 of 1 approvals obtained.

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32749)* status: 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 838 at r3](https://reviewable.io/reviews/harness/harness-core/32749#-N2EE_8t7EVAj9ysmt43:-N2KWcdp4Dzr8qhZtZvS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3627f52fdcc44798aa6cd5fe06c41128571ea97f/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L838)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should put something in the selection logs as well indicating thats the case
</blockquote></details>

Done.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32749)* status: :shipit: complete! ✓

**Pull request merged**
