### PR TITLE
feat: [cds-52528]: Added support for filtering with tags for templates in list-metadata call

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Added support for filtering with tags and filter identifier for templates in list-metadata & list templates call

1). Filtering with filter Identifier
image

2). Filtering with filterProperties
image

3). Filtering with both filter Identifier & filterProperties
image

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43996)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`930-ng-core-clients/src/main/java/io/harness/template/TemplateFilterPropertiesDTO.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/43996#-NOOeaka1YDFSR45xpMp:-NOOeaka1YDFSR45xpMq:b-9c7f3y) ([raw file](https://github.com/harness/harness-core/blob/a263c68e87dfac15f6263cb68665805240f8b97b/930-ng-core-clients/src/main/java/io/harness/template/TemplateFilterPropertiesDTO.java#L50)):*
> ```Java
>   List<TemplateEntityType> templateEntityTypes;
>   List<String> childTypes;
>   List<NGTag> templateTags;
> ```

can we just call it tags ?

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43996)* status: :shipit: complete! ✓

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43996)* status: :shipit: complete! ✓

___
*[`930-ng-core-clients/src/main/java/io/harness/template/TemplateFilterPropertiesDTO.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/43996#-NOOeaka1YDFSR45xpMp:-NOOgD2PE6-XZOWWMMsh:bgmmzyu) ([raw file](https://github.com/harness/harness-core/blob/a263c68e87dfac15f6263cb68665805240f8b97b/930-ng-core-clients/src/main/java/io/harness/template/TemplateFilterPropertiesDTO.java#L50)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we just call it tags ?
</blockquote></details>

we cannot call it just tags as TemplateFilterPropertiesDTO is extending FilterPropertiesDTO which also has Map<String, String> tags;

**Review by vivekkarnatiharness — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43996)* status: :shipit: complete! ✓

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
can we remove the reverted files from the PR ?

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 245 at r6](https://reviewable.io/reviews/harness/harness-core/43996#-NPHRkZI6emqt0z4qWPF:-NPHRkZI6emqt0z4qWPG:bb373yc) ([raw file](https://github.com/harness/harness-core/blob/52aa711bffad2a0a2dcc12e6affd0d03428e228a/840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L245)):*
> ```Java
>   public TemplateFilterProperties toTemplateFilterProperties(TemplateFilterPropertiesDTO filterProperties) {
>     if (filterProperties == null) {
>       return null;
> ```

can we not return empty object as before ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 89 files at r3, 80 of 85 files at r4, 3 of 6 files at r5, 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43996)* status: 2 file(s) to review. 0 of 1 approvals obtained.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43996)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 245 at r6](https://reviewable.io/reviews/harness/harness-core/43996#-NPHRkZI6emqt0z4qWPF:-NPHS7slB4w9pbvmo3bt:bwj9sa7) ([raw file](https://github.com/harness/harness-core/blob/52aa711bffad2a0a2dcc12e6affd0d03428e228a/840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L245)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we not return empty object as before ?
</blockquote></details>

earlier we never tested by passing filterIdentifier, there was an issue in the existing code 

    if (EmptyPredicate.isNotEmpty(filterIdentifier) && filterProperties != null) {
      throw new InvalidRequestException("Can not apply both filter properties and saved filter together");
    } else if (EmptyPredicate.isNotEmpty(filterIdentifier) && filterProperties == null) {
      populateFilterUsingIdentifier(
          criteria, accountId, orgId, projectId, filterIdentifier, searchTerm, includeAllTemplatesCriteria);
 }

Here incase filterIdentifier was passed and as filterProperties was always notNull therefore it would have always thrown InvalidRequestException

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43996)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 245 at r6](https://reviewable.io/reviews/harness/harness-core/43996#-NPHRkZI6emqt0z4qWPF:-NPHSzaF6NMN4IdIOFl4:bardvr0) ([raw file](https://github.com/harness/harness-core/blob/52aa711bffad2a0a2dcc12e6affd0d03428e228a/840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L245)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

earlier we never tested by passing filterIdentifier, there was an issue in the existing code 

    if (EmptyPredicate.isNotEmpty(filterIdentifier) && filterProperties != null) {
      throw new InvalidRequestException("Can not apply both filter properties and saved filter together");
    } else if (EmptyPredicate.isNotEmpty(filterIdentifier) && filterProperties == null) {
      populateFilterUsingIdentifier(
          criteria, accountId, orgId, projectId, filterIdentifier, searchTerm, includeAllTemplatesCriteria);
 }

Here incase filterIdentifier was passed and as filterProperties was always notNull therefore it would have always thrown InvalidRequestException 
</blockquote></details>

as we didn't support for saved filters from UI, I guess it never came into attention

**Review by adivishy1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43996)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 245 at r6](https://reviewable.io/reviews/harness/harness-core/43996#-NPHRkZI6emqt0z4qWPF:-NPHVB6X9pgQBcDeNCs_:b-1u315p) ([raw file](https://github.com/harness/harness-core/blob/52aa711bffad2a0a2dcc12e6affd0d03428e228a/840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L245)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

as we didn't support for saved filters from UI, I guess it never came into attention
</blockquote></details>

@yogesh-chauhan, how do you check if an object is null when something like this TemplateFilterProperties.builder().build()?

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43996)* status: :shipit: complete! ✓

**Pull request merged**
