### PR TITLE
feat: [SSCA-1066]: Add Add details for fetching the artifact with lat…

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
…est fix, Deployment counts based on the SBOM orchestration

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56759)

### CODE REVIEW

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepharness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56759)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/56759#-NlbCs-rERm-SjuiBfGR:-NlbCs-rERm-SjuiBfGS:b4ench0) ([raw file](https://github.com/harness/harness-core/blob/f97b23fde1b03da25c995bc69cd2118b6a4fc50f/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L81)):*
> ```Java
> 
>   @Override
>   public void updateArtifactsAndEnvironmentsInRemediationTracker(RemediationTrackerEntity remediationTracker) {
> ```

InRemediationTracker is redundant as this belong to RemediationTrackerService
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/56759#-NlbYaMi6gLUotJLKm7f:-NlbYaMi6gLUotJLKm7g:bebt3ab) ([raw file](https://github.com/harness/harness-core/blob/f97b23fde1b03da25c995bc69cd2118b6a4fc50f/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L124)):*
> ```Java
>   }
> 
>   private void closeRemediationTrackerIfNoOrchestrations(
> ```

suggestion as its a remediationTrackerService , you can avoid using remediation word , its become redundant
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 223 at r1](https://reviewable.io/reviews/harness/harness-core/56759#-NlbcjIu4gGTujqVlXO9:-NlbcjIu4gGTujqVlXOA:b-hfddbb) ([raw file](https://github.com/harness/harness-core/blob/f97b23fde1b03da25c995bc69cd2118b6a4fc50f/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L223)):*
> ```Java
>                  .environments(new ArrayList<>())
>                  .build());
>       if (details.isPatched() && info.getLatestTagWithFixPipelineTriggeredAt() < details.getCreatedOn()) {
> ```

Can you add the steps in comment of your workflow ? like
Step 1 -> fetch CDinstance
Step 2 -> update PatchedAndLatestTagBefore Creation
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 322 at r1](https://reviewable.io/reviews/harness/harness-core/56759#-NlbeRRX9CYMwSSa5dSk:-NlbeRRX9CYMwSSa5dSl:bi4olz2) ([raw file](https://github.com/harness/harness-core/blob/f97b23fde1b03da25c995bc69cd2118b6a4fc50f/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L322)):*
> ```Java
>   }
> 
>   private DeploymentsCount getDeploymentCount(DeploymentsCount deploymentsCount, EnvType envType, boolean isPatched) {
> ```

This can be moved to DeploymentCount.  As this is domain logic for remediation tracker
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 342 at r1](https://reviewable.io/reviews/harness/harness-core/56759#-Nlbeukf2qQybDHXUoVO:-Nlbeukf2qQybDHXUoVP:b-n3ws9o) ([raw file](https://github.com/harness/harness-core/blob/f97b23fde1b03da25c995bc69cd2118b6a4fc50f/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L342)):*
> ```Java
>   }
> 
>   private void addDeploymentCount(DeploymentsCount deploymentsCount, DeploymentsCount deploymentsCountToAdd) {
> ```

 can be moved to DeploymentCount

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56759)* status: 8 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/56759#-NlbCs-rERm-SjuiBfGR:-Nlbo2V-Ete0STotil5x:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f97b23fde1b03da25c995bc69cd2118b6a4fc50f/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L81)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

InRemediationTracker is redundant as this belong to RemediationTrackerService
</blockquote></details>

Done.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/56759#-NlbYaMi6gLUotJLKm7f:-Nlbo3SmE0wnVRNBXKie:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f97b23fde1b03da25c995bc69cd2118b6a4fc50f/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L124)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

suggestion as its a remediationTrackerService , you can avoid using remediation word , its become redundant
</blockquote></details>

Done.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 223 at r1](https://reviewable.io/reviews/harness/harness-core/56759#-NlbcjIu4gGTujqVlXO9:-Nlbo0Cf5Vd03HtFct5m:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f97b23fde1b03da25c995bc69cd2118b6a4fc50f/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L223)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Can you add the steps in comment of your workflow ? like
Step 1 -> fetch CDinstance
Step 2 -> update PatchedAndLatestTagBefore Creation
</blockquote></details>

Done.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 322 at r1](https://reviewable.io/reviews/harness/harness-core/56759#-NlbeRRX9CYMwSSa5dSk:-Nlbo12S23L6CyQTJ7EL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f97b23fde1b03da25c995bc69cd2118b6a4fc50f/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L322)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

This can be moved to DeploymentCount.  As this is domain logic for remediation tracker
</blockquote></details>

Done.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 342 at r1](https://reviewable.io/reviews/harness/harness-core/56759#-Nlbeukf2qQybDHXUoVO:-Nlbo1N168R_dFIloOEl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f97b23fde1b03da25c995bc69cd2118b6a4fc50f/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L342)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

can be moved to DeploymentCount
</blockquote></details>

Done.

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepharness — DISMISSED** [review]
> Reviewed 6 of 8 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56759)* status: <span>:shipit:</span> complete! ✓

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Pull request merged**
