### PR TITLE
feat: [CDS-52364]: support terraform cloud cli with remote backend

### PR DESCRIPTION
**Pull request by vlica-harness**
## Describe your changes
Feature is behind a feature flag. 
Doc with details: https://harness.atlassian.net/wiki/spaces/~260363762/pages/21274690734/Spec+Terraform+Enterprise+Support+via+CLI
In this PR we are adding a new configuration beside the current. For terraform plan step (this won't have secretManager, workspace, exportJson, exportHummandReadable. For Apply/Destroy steps it won't have workspace. The Apply/Destroy will only only be available to have **Inline** configuration.
```
spec:
    cloudCliConfiguration:
```
beside current (but only one will be available in the yaml, or **configuration** or **cloudCliConfiguration**
```
spec:
    configuration:
```
This PR changes are backward compatible with current/old yaml. It won't require customers to update any existing pipelines.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44175)

### CODE REVIEW

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 37 of 44 files at r1, 3 of 3 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, 7 of 13 files at r5, 6 of 6 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44175)* status: 50 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/terraform/TerraformBaseHelperImplTest.java` line 627 at r7](https://reviewable.io/reviews/harness/harness-core/44175#-NP2jWwt8YyyqQIxBAEX:-NP2jWwu6bcnzUkqNT_A:b-bf4wwu) ([raw file](https://github.com/harness/harness-core/blob/98168e4b42f49ac7b06e3d34662125de319fc111/930-delegate-tasks/src/test/java/io/harness/delegate/task/terraform/TerraformBaseHelperImplTest.java#L627)):*
> ```Java
>   }
> 
> //  @Test // in progress
> ```

Do we leave it like this?
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/terraform/handlers/TerraformPlanTaskHandlerTest.java` line 127 at r7](https://reviewable.io/reviews/harness/harness-core/44175#-NP2kXz7CZq_1ACrD6CA:-NP2kXz7CZq_1ACrD6CB:b4hzqgh) ([raw file](https://github.com/harness/harness-core/blob/98168e4b42f49ac7b06e3d34662125de319fc111/930-delegate-tasks/src/test/java/io/harness/delegate/task/terraform/handlers/TerraformPlanTaskHandlerTest.java#L127)):*
> ```Java
> 
>   @Test
>   @Owner(developers = ROHITKARELIA)
> ```

Add you name on Owners
___
*[`960-api-services/src/test/java/io/harness/terraform/TerraformClientImplTest.java` line 154 at r7](https://reviewable.io/reviews/harness/harness-core/44175#-NP2l0UQ19_eMqDzew4r:-NP2l0UQ19_eMqDzew4s:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/98168e4b42f49ac7b06e3d34662125de319fc111/960-api-services/src/test/java/io/harness/terraform/TerraformClientImplTest.java#L154)):*
> ```Java
>   @Owner(developers = ROHITKARELIA)
>   @Category(UnitTests.class)
>   public void testDestroyCommandUsingTf012AndTfCloudCli() throws InterruptedException, IOException, TimeoutException {
> ```

same here

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44175)* status: 50 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Comment by vlica-harness** [comment]
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/terraform/TerraformBaseHelperImplTest.java` line 627 at r7](https://reviewable.io/reviews/harness/harness-core/44175#-NP2jWwt8YyyqQIxBAEX:-NP3HFZxAq2OkvFYT7Mo:b-9fwl6e) ([raw file](https://github.com/harness/harness-core/blob/98168e4b42f49ac7b06e3d34662125de319fc111/930-delegate-tasks/src/test/java/io/harness/delegate/task/terraform/TerraformBaseHelperImplTest.java#L627)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Do we leave it like this?
</blockquote></details>

I was in progress with unit tests, done

**Review by vlica-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44175)* status: 54 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/terraform/handlers/TerraformPlanTaskHandlerTest.java` line 127 at r7](https://reviewable.io/reviews/harness/harness-core/44175#-NP2kXz7CZq_1ACrD6CA:-NP3HMkq7a1KUGNqVp-t:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/98168e4b42f49ac7b06e3d34662125de319fc111/930-delegate-tasks/src/test/java/io/harness/delegate/task/terraform/handlers/TerraformPlanTaskHandlerTest.java#L127)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Add you name on Owners
</blockquote></details>

done
___
*[`960-api-services/src/test/java/io/harness/terraform/TerraformClientImplTest.java` line 154 at r7](https://reviewable.io/reviews/harness/harness-core/44175#-NP2l0UQ19_eMqDzew4r:-NP3HOVT-6JmIm6bgJII:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/98168e4b42f49ac7b06e3d34662125de319fc111/960-api-services/src/test/java/io/harness/terraform/TerraformClientImplTest.java#L154)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

same here
</blockquote></details>

done

**Review by alebuh — CHANGES_REQUESTED** [review]
> Reviewed 27 of 44 files at r1, 1 of 3 files at r3, 4 of 13 files at r5, 4 of 6 files at r6, 3 of 4 files at r7, 4 of 5 files at r8, 10 of 10 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44175)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformApplyStep.java` line 94 at r10](https://reviewable.io/reviews/harness/harness-core/44175#-NPH9dr35OFyFz4LTktA:-NPH9dr35OFyFz4LTktB:bs0jwb0) ([raw file](https://github.com/harness/harness-core/blob/ecb5d7c39c3e400744ee7fe59de39e864cc6aa79/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformApplyStep.java#L94)):*
> ```Java
> 
>     if (stepParametersSpec.getConfiguration().getType().getDisplayName().equalsIgnoreCase(
>             TerraformStepConfigurationType.INLINE.getDisplayName())) {
> ```

Is there a reason why we are checking for display names instead of Enum values?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 1148 at r11](https://reviewable.io/reviews/harness/harness-core/44175#-NPH_jDW97hkezKrq-vO:-NPH_jDW97hkezKrq-vP:b-c6b99d) ([raw file](https://github.com/harness/harness-core/blob/ef592a729a25d4c476e64d775bdce46cadfc2c28/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L1148)):*
> ```Java
>   }
> 
>   public void checkIfDelegateSupportsCloudCli(Ambiance ambiance) {
> ```

just curious, is this now the way we should handle delegate backward compatibility? Should we always check if the delegate supports a version of the task that we are sending? I know that before we didn't do this, we just send a Task and if it's not picked up that means it's not supported. What is the value of having this check as well, is it a custom error message explaining what the delegate does not support?  Also, is there a plan to clean up this after some time, when we presume that all delegates are supporting this task type and how that is handled?

**Review by vlica-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44175)* status: 11 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformApplyStep.java` line 94 at r10](https://reviewable.io/reviews/harness/harness-core/44175#-NPH9dr35OFyFz4LTktA:-NPHexrY7tHxrosyU7nU:br6o3u6) ([raw file](https://github.com/harness/harness-core/blob/ecb5d7c39c3e400744ee7fe59de39e864cc6aa79/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformApplyStep.java#L94)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

Is there a reason why we are checking for display names instead of Enum values?
</blockquote></details>

yes, because the new config type cloudCliConfiugration doesn't support InheritFromPlan or InheritFromApply, it only supports the Inline. (that's why I switched to check based on displayName not getting an error when step inherits)
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 1148 at r11](https://reviewable.io/reviews/harness/harness-core/44175#-NPH_jDW97hkezKrq-vO:-NPHfTZ36gvQN-xEIwcd:byoo891) ([raw file](https://github.com/harness/harness-core/blob/ef592a729a25d4c476e64d775bdce46cadfc2c28/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L1148)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

just curious, is this now the way we should handle delegate backward compatibility? Should we always check if the delegate supports a version of the task that we are sending? I know that before we didn't do this, we just send a Task and if it's not picked up that means it's not supported. What is the value of having this check as well, is it a custom error message explaining what the delegate does not support?  Also, is there a plan to clean up this after some time, when we presume that all delegates are supporting this task type and how that is handled? 
</blockquote></details>

this is just an improvement when you add a new feature and only a new delegate version will support this logic then we should. Yes, the value is that you can write a custom error message. yes, I believe we should cleanup this logic once the feature flag is GA

**Review by alebuh — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44175)* status: 11 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 10 of 10 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44175)* status: Waiting on team(s): del-team.

**Review by yogesh-chauhan — DISMISSED** [review]

**Review by alebuh — APPROVED** [review]
> Reviewed 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44175)* status: 6 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44175)* status: Waiting on team(s): del-team.

**Review by yogesh-chauhan — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 27 of 44 files at r1, 1 of 3 files at r3, 4 of 13 files at r5, 1 of 6 files at r6, 3 of 4 files at r7, 4 of 5 files at r8, 8 of 10 files at r9, 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44175)* status: Waiting on team(s): del-team.

**Review by alebuh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44175)* status: Waiting on team(s): del-team.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 27 of 44 files at r1, 1 of 3 files at r3, 4 of 13 files at r5, 1 of 6 files at r6, 3 of 4 files at r7, 4 of 5 files at r8, 8 of 10 files at r9, 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44175)* status: Waiting on team(s): del-team.

**Pull request merged**
