### PR TITLE
feat: [CDS-85834]: fix inputset merge api to accept inputs in last yaml to merge

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
fix inputset merge api to accept inputs in last yaml to merge

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56218)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56218)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 265 at r1](https://reviewable.io/reviews/harness/harness-core/56218#-Nk_-l4P7nGHzaPGCeYm:-Nk_-l4P7nGHzaPGCeYn:b9xioxj) ([raw file](https://github.com/harness/harness-core/blob/1ab264a244303bf257f1408b610b82bc7705adb7/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L265)):*
> ```Java
>     if (inputSetVersions.contains(HarnessYamlVersion.V1)) {
>       if (!EmptyPredicate.isEmpty(lastJsonNodeToMerge)) {
>         inputSetJsonNodeList.add(getLastYamlToMergeInputSetForm(lastJsonNodeToMerge));
> ```

discussed offline to adopt different design

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56218)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 265 at r1](https://reviewable.io/reviews/harness/harness-core/56218#-Nk_-l4P7nGHzaPGCeYm:-NknXDd_3LYTYpi2a0Z_:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1ab264a244303bf257f1408b610b82bc7705adb7/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L265)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

discussed offline to adopt different design
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 261 at r2](https://reviewable.io/reviews/harness/harness-core/56218#-Nk_OLca3JrL00wc56IO:-NknXC0E5lzEwoSK7vLC:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ed5df5a89107ac2b8061fb47e95d1c06d8a587a6/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L261)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we add validation that all inputSetVersions and pipelineVersion is same?
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 262 at r2](https://reviewable.io/reviews/harness/harness-core/56218#-Nk_ORFn2WqTcIZ5PmMT:-NknXCgi42hFyr3IhF8o:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ed5df5a89107ac2b8061fb47e95d1c06d8a587a6/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L262)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

check only pipelineVersion as all will be same so no Or operator is required
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 294 at r2](https://reviewable.io/reviews/harness/harness-core/56218#-Nk_OYug7NNi2g2sb9T2:-NknXGVT56JDsDRRhhU8:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ed5df5a89107ac2b8061fb47e95d1c06d8a587a6/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L294)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

default should always be v0
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetService.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/56218#-Nk_Oabt3Wftd4XIeUyN:-NknXMGKBgRyEKWkq5f0:b-aekpu8) ([raw file](https://github.com/harness/harness-core/blob/ed5df5a89107ac2b8061fb47e95d1c06d8a587a6/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetService.java#L88)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comments what does it return?
</blockquote></details>

this is not done yet

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56218)* status: 6 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetService.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/56218#-Nk_Oabt3Wftd4XIeUyN:-NknYSHY7IM4cQPoU0ya:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ed5df5a89107ac2b8061fb47e95d1c06d8a587a6/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetService.java#L88)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this is not done yet
</blockquote></details>

done

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56218)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Pull request merged**
