### PR TITLE
feat: [CDS-33644]: marking connector field as mandatory for CDP connector(s)

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
You can use the following comments to re-trigger PR Checks
- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32171)

### CODE REVIEW

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Review by sainath-b — APPROVED** [review]

**Review by sainath-b — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32171)* status: :shipit: complete! ✓

**Comment by abhinavsingh1196** [comment]
The /connectors API throws 500 Internal Server Error currently, if a null credential is passed:
> {
    "status": "ERROR",
    "code": "UNKNOWN_ERROR",
    "message": "Oops, something went wrong on our end. Please contact Harness Support.",
    "correlationId": "0847b0f9-897e-499b-afe8-561658d3b206",
    "detailedMessage": null,
    "responseMessages": [],
    "metadata": null
}

After this change, the response would be 400 Bad Request:
> {
    "status": "FAILURE",
    "code": "INVALID_REQUEST",
    "message": null,
    "correlationId": "91ae1368-eb8b-4475-80d8-69a1b228bec9",
    "errors": [
        {
            "fieldId": "credential",
            "error": "may not be null"
        }
    ]
}

**Comment by abhinavsingh1196** [comment]
The /connectors API throws 500 Internal Server Error currently, if a null credential is passed:
> {
    "status": "ERROR",
    "code": "UNKNOWN_ERROR",
    "message": "Oops, something went wrong on our end. Please contact Harness Support.",
    "correlationId": "0847b0f9-897e-499b-afe8-561658d3b206",
    "detailedMessage": null,
    "responseMessages": [],
    "metadata": null
}

After this change, the response would be 400 Bad Request:
> {
    "status": "FAILURE",
    "code": "INVALID_REQUEST",
    "message": null,
    "correlationId": "91ae1368-eb8b-4475-80d8-69a1b228bec9",
    "errors": [
        {
            "fieldId": "credential",
            "error": "may not be null"
        }
    ]
}

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32171)* status: :shipit: complete! ✓

**Pull request merged**
