### PR TITLE
[feat]: [PIE-3839]: Being able to send notifications to only the user who triggers the pipeline for Pipeline Start and Pipeline End

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Please review My PR ,
Enhancement : When we run a pipeline, there's a checkbox ->"Notify only me about execution status", upon clicking it, now onwards Notifications will be sent only to the user who triggered pipeline bypassing all other previously configured Notifications.
Note: In the first phase of development, it is hardcoded for only for events: Pipeline Start and Pipeline End.
Tests: Expected behaviour was reproduced on Local, Also EmailNotificationsTest Pipelines were successful

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36469)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Vulnerability 1 Vulnerabilities 
 * Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36469)

**Review by namanvermah — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36469)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/36469#-N9jCEnL2jlSpBNsa5WW:-N9jCEnMBDlCmm_dtWqR:by06he5) ([raw file](https://github.com/harness/harness-core/blob/fa8ee20e4a857460598fb87d65e8c5fb8a1e5fe5/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L81)):*
> ```Java
>       Ambiance ambiance, PipelineEventType pipelineEventType, NodeExecution nodeExecution, Long updatedAt) {
>     if (ambiance.getNotifyOnlyMe()) {
>       if (!(pipelineEventType.getDisplayName().equals(PipelineEventTypeConstants.PIPELINE_START)
> ```

You can add a list with `PipelineEventTypeConstants.PIPELINE_START` and `PipelineEventTypeConstants.PIPELINE_END` and check if the display name is in that list. This way if in future we want to include more event types we won't have to add another if condition.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36469)* status: 17 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/36469#-N9jCEnL2jlSpBNsa5WW:-NA8djtz9xzNhMsMd8xD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fa8ee20e4a857460598fb87d65e8c5fb8a1e5fe5/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L81)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

You can add a list with `PipelineEventTypeConstants.PIPELINE_START` and `PipelineEventTypeConstants.PIPELINE_END` and check if the display name is in that list. This way if in future we want to include more event types we won't have to add another if condition.
</blockquote></details>

Done.

**Comment by senjucanon2** [comment]
trigger ti1

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/ambiance/ambiance.proto` line 25 at r4](https://reviewable.io/reviews/harness/harness-core/36469#-NAFRi4wANancqBWkLop:-NAFRi4wANancqBWkLoq:bxydeo7) ([raw file](https://github.com/harness/harness-core/blob/3f5bbb251f651fdab84a25c41e3978f380ca69ce/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/ambiance/ambiance.proto#L25)):*
> ```protobuf
> 
>   string stageExecutionId = 8;
>   bool notifyOnlyMe = 9;
> ```

@senjucanon2 I think we don't need to add this field in ambiance. We can store this field in PlanExecutionMetadata. And we already query planExecutionMetadata in notificationHelper for getting pipeline yaml so we can get this info also in the same object.
Also ambience remains throughout the pipeline execution so We should not make add fields to ambiance until its really needed.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36469)* status: 18 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/ambiance/ambiance.proto` line 25 at r4](https://reviewable.io/reviews/harness/harness-core/36469#-NAFRi4wANancqBWkLop:-NAJVacV7fiSaF0hv6-m:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3f5bbb251f651fdab84a25c41e3978f380ca69ce/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/ambiance/ambiance.proto#L25)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

@senjucanon2 I think we don't need to add this field in ambiance. We can store this field in PlanExecutionMetadata. And we already query planExecutionMetadata in notificationHelper for getting pipeline yaml so we can get this info also in the same object.
Also ambience remains throughout the pipeline execution so We should not make add fields to ambiance until its really needed.
</blockquote></details>

Done.

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 8 of 15 files at r1, 1 of 3 files at r2, 11 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36469)* status: 18 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/OrchestrationService.java` line 34 at r5](https://reviewable.io/reviews/harness/harness-core/36469#-NAKVTiZ-A7-obvgWXfx:-NAKVTiZ-A7-obvgWXfy:b-h1ok8r) ([raw file](https://github.com/harness/harness-core/blob/5bc40070a267faea8f1e39186b663d472956b989/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/OrchestrationService.java#L34)):*
> ```Java
>       PlanExecutionMetadata planExecutionMetadata);
> 
>   PlanExecution executePlan(@Valid Plan plan, @NonNull Map<String, String> setupAbstractions,
> ```

why @NonNull was removed?
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/OrchestrationServiceImpl.java` line 49 at r5](https://reviewable.io/reviews/harness/harness-core/36469#-NAKVZLkB0kZiaKnI712:-NAKVZLkB0kZiaKnI713:b53ftb7) ([raw file](https://github.com/harness/harness-core/blob/5bc40070a267faea8f1e39186b663d472956b989/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/OrchestrationServiceImpl.java#L49)):*
> ```Java
>   }
> 
>   @Override
> ```

Why @Override was reomved?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 69 at r5](https://reviewable.io/reviews/harness/harness-core/36469#-NAKSz4y0pidj15JuPv4:-NAKSz4y0pidj15JuPv5:b1usb1e) ([raw file](https://github.com/harness/harness-core/blob/c98542ad550e7ca68c8e5c5449e3434e17fbfac4/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L69)):*
> ```Java
> 
>   public static List<String> notifyOnlyMeEvents =
>       Arrays.asList(PipelineEventTypeConstants.PIPELINE_START, PipelineEventTypeConstants.PIPELINE_END);
> ```

should use PipelineEventType.PIPELINE_START and PipelineEventType.PIPELINE_END enum here. 
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 89 at r5](https://reviewable.io/reviews/harness/harness-core/36469#-NAKR8lW77qQJIaYE1LF:-NAKR8lW77qQJIaYE1LG:b-t9jclu) ([raw file](https://github.com/harness/harness-core/blob/c98542ad550e7ca68c8e5c5449e3434e17fbfac4/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L89)):*
> ```Java
>     boolean notifyOnlyMe = Boolean.TRUE.equals(planExecutionMetadata.getNotifyOnlyMe());
>     if (notifyOnlyMe) {
>       for (String currPipelineEventType : notifyOnlyMeEvents) {
> ```

Here you are iterating over notifyOnlyMeEvent and checking if that event is PipelineEventTypeConstants.PIPELINE_START or PipelineEventTypeConstants.PIPELINE_END, so it will always be true. And for each time we will send 2 notification for pipelineStart and pipelineEnd on all events.
You should check if(notifyOnlyMeEvents.contains(pipelineEventType)). If yes then send the notification.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36469)* status: 18 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/OrchestrationService.java` line 34 at r5](https://reviewable.io/reviews/harness/harness-core/36469#-NAKVTiZ-A7-obvgWXfx:-NAOx-lx-ir6pyuDaDgX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5bc40070a267faea8f1e39186b663d472956b989/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/OrchestrationService.java#L34)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

why @NonNull was removed?
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/OrchestrationServiceImpl.java` line 49 at r5](https://reviewable.io/reviews/harness/harness-core/36469#-NAKVZLkB0kZiaKnI712:-NAOx-Fd6PSSzxGyb6xm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5bc40070a267faea8f1e39186b663d472956b989/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/OrchestrationServiceImpl.java#L49)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Why @Override was reomved?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 69 at r5](https://reviewable.io/reviews/harness/harness-core/36469#-NAKSz4y0pidj15JuPv4:-NAOwxauCcjoKWF1aKrP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c98542ad550e7ca68c8e5c5449e3434e17fbfac4/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L69)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

should use PipelineEventType.PIPELINE_START and PipelineEventType.PIPELINE_END enum here. 
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 89 at r5](https://reviewable.io/reviews/harness/harness-core/36469#-NAKR8lW77qQJIaYE1LF:-NAOwygQCxP2lFn7mJgD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c98542ad550e7ca68c8e5c5449e3434e17fbfac4/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L89)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Here you are iterating over notifyOnlyMeEvent and checking if that event is PipelineEventTypeConstants.PIPELINE_START or PipelineEventTypeConstants.PIPELINE_END, so it will always be true. And for each time we will send 2 notification for pipelineStart and pipelineEnd on all events.
You should check if(notifyOnlyMeEvents.contains(pipelineEventType)). If yes then send the notification.
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 69 at r5](https://reviewable.io/reviews/harness/harness-core/36469#-NAKSz4y0pidj15JuPv4:-NAPAKZI67WiujsN_-c8:b-q3q9pk) ([raw file](https://github.com/harness/harness-core/blob/c98542ad550e7ca68c8e5c5449e3434e17fbfac4/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L69)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Move this to PipelineEventTypeEnum itself so that all of this is contained in that file itself.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 92 at r6](https://reviewable.io/reviews/harness/harness-core/36469#-NAPAViF6r49bmi7yPVp:-NAPAViF6r49bmi7yPVq:b-jclb8w) ([raw file](https://github.com/harness/harness-core/blob/4fb55c16451257bd35a7ab917f03547c4d7afde2/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L92)):*
> ```Java
>         sendNotificationOnlyToUserWhoTriggeredPipeline(ambiance, pipelineEventType, nodeExecution, updatedAt, true);
>       }
>       return;
> ```

What happens if notifyMe is true and also pipeline yaml has notifications configured? Do we not send notification?

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36469)* status: 18 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 69 at r5](https://reviewable.io/reviews/harness/harness-core/36469#-NAKSz4y0pidj15JuPv4:-NAPDQeGB8Ptn9geGBXa:b-krnprw) ([raw file](https://github.com/harness/harness-core/blob/c98542ad550e7ca68c8e5c5449e3434e17fbfac4/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L69)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Move this to PipelineEventTypeEnum itself so that all of this is contained in that file itself.
</blockquote></details>

Need to discuss it with Brijesh Once, and then I'll let you know.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 92 at r6](https://reviewable.io/reviews/harness/harness-core/36469#-NAPAViF6r49bmi7yPVp:-NAPDYlG1R60wLWpo4Ro:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/4fb55c16451257bd35a7ab917f03547c4d7afde2/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L92)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

What happens if notifyMe is true and also pipeline yaml has notifications configured? Do we not send notification?
</blockquote></details>

yes

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36469)* status: 18 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 69 at r5](https://reviewable.io/reviews/harness/harness-core/36469#-NAKSz4y0pidj15JuPv4:-NAcE2fg69fwP1ZjXvfq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c98542ad550e7ca68c8e5c5449e3434e17fbfac4/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L69)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

yes, it would be better to keep this static list inside the PipelineEventType enum.
</blockquote></details>

Done.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 5 files at r6, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36469)* status: 19 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 92 at r6](https://reviewable.io/reviews/harness/harness-core/36469#-NAPAViF6r49bmi7yPVp:-NAhNg6p9ORbjbz2UWkX:b-kkd21r) ([raw file](https://github.com/harness/harness-core/blob/4fb55c16451257bd35a7ab917f03547c4d7afde2/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L92)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

yes
</blockquote></details>

as per code, I think it is not happening, could you please validate this once? cc - @brijeshdhakar

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36469)* status: 19 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 92 at r6](https://reviewable.io/reviews/harness/harness-core/36469#-NAPAViF6r49bmi7yPVp:-NAhQewC5zVQGrz18jBr:btepppz) ([raw file](https://github.com/harness/harness-core/blob/4fb55c16451257bd35a7ab917f03547c4d7afde2/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L92)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

as per code, I think it is not happening, could you please validate this once? cc - @brijeshdhakar 
</blockquote></details>

If any other PipelineEvent triggers sendNotification method, and notifyOnlyMe is set to true, and notifyOnlyUserEvents doesn't have it, then it will just return out of method, no following code would be executed

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 15 files at r1, 1 of 3 files at r2, 4 of 13 files at r5, 4 of 5 files at r6, 1 of 1 files at r7, 6 of 7 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36469)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36469)* status: 1 change requests. 2. unresolved discussions.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 15 files at r1, 1 of 3 files at r2, 4 of 13 files at r5, 4 of 5 files at r6, 1 of 1 files at r7, 6 of 7 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36469)* status: 1 change requests. 1. unresolved discussions.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 2 of 15 files at r1, 1 of 3 files at r2, 4 of 13 files at r5, 4 of 5 files at r6, 1 of 1 files at r7, 6 of 7 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36469#-:-NArJy7B6u-SGKEl5Acm:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
