### PR TITLE
[fix]: [PIE-7294]: Only check for children in non leaf fields

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42709)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger messageCheck

**Review by ankittiwari-harness — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42709#-:-NLyx3rd8fI-ahz-TQ3V:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by namanvermah** [comment]
trigger messagecheck

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42709)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42709)* status: :shipit: complete! ✓

**Pull request merged**
