### PR TITLE
feat: [CI-4817]: Publish telemetry events for harness hosted provision resources

### PR DESCRIPTION
**Pull request by rutvijmehta-harness**
## Describe your changes
Add provision_started and provision_completed telemetry events when the user tries to provision resources for harness hosted builds.
1. provision_started is published when the connector is created for the first time
2. provision_completed is published when the API delegate-install-status returns Success (duplicates possible)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34594)

### CODE REVIEW

**Review by hemanthmantri — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34594)* status: 1 file(s) to review. 1 of 3 approvals obtained.  (waiting on @harshjain12 and @jamie-harness)

___
*[`120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java` line 118 at r1](https://reviewable.io/reviews/harness/harness-core/34594#-N5CYhucBoRvg09dgNfv:-N5CYhucBoRvg09dgNfw:b-ussyog) ([raw file](https://github.com/harness/harness-core/blob/1c37986578a18d368f5288c89bbf88950185e7e0/120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java#L118)):*
> ```Java
>     }
> 
>     Boolean delegateUpsertStatus = updateDelegateGroup(accountId);
> ```

Is it safe to move this after installConnector? Is yes we can keep the installConnector as starting point for this method and add a comment saying all new resource installations should be done after installConnector.
___
*[`120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java` line 199 at r1](https://reviewable.io/reviews/harness/harness-core/34594#-N5CYGeiES01ZK3uh3Ta:-N5CYGeiES01ZK3uh3Tb:b-w5c87v) ([raw file](https://github.com/harness/harness-core/blob/1c37986578a18d368f5288c89bbf88950185e7e0/120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java#L199)):*
> ```Java
>       }
> 
>       HashMap<String, Object> provisionMap = new HashMap<>();
> ```

What's this used for? Sending an empty map?

**Comment by rutvijmehta-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java` line 199 at r1](https://reviewable.io/reviews/harness/harness-core/34594#-N5CYGeiES01ZK3uh3Ta:-N5CbYPJ9AKWoXJDnqhj:b-xg5hvx) ([raw file](https://github.com/harness/harness-core/blob/1c37986578a18d368f5288c89bbf88950185e7e0/120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java#L199)):*
<details><summary><i>Previously, hemanthmantri (Hemanth Mantri) wrote…</i></summary><blockquote>

What's this used for? Sending an empty map?
</blockquote></details>

It could be set to null as well as a new HashMap will be created here https://github.com/harness/harness-core/blob/1c37986578a18d368f5288c89bbf88950185e7e0/950-telemetry/src/main/java/io/harness/telemetry/segment/SegmentReporterImpl.java#L68

**Comment by rutvijmehta-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java` line 118 at r1](https://reviewable.io/reviews/harness/harness-core/34594#-N5CYhucBoRvg09dgNfv:-N5Cbul69tvQIR5gu6UW:b-ud1kc6) ([raw file](https://github.com/harness/harness-core/blob/1c37986578a18d368f5288c89bbf88950185e7e0/120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java#L118)):*
<details><summary><i>Previously, hemanthmantri (Hemanth Mantri) wrote…</i></summary><blockquote>

Is it safe to move this after installConnector? Is yes we can keep the installConnector as starting point for this method and add a comment saying all new resource installations should be done after installConnector.
</blockquote></details>

I think we need to confirm this with Aman/Hen but should be okay. Since we didn't want to change the flow of the API, we just added the telemetry events at the best place possible.

**Comment by rutvijmehta-harness** [comment]
trigger messagecheck

**Review by dgarg-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34594)* status: :shipit: complete! ✓

**Review by rutvijmehta-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34594)* status: :shipit: complete! ✓

**Pull request merged**
