### PR TITLE
feat: [PL-29028]: added reset 2fa support for NG

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
Feature:- 
Added support to resend two factor authentication mail from NG. This PR adds an NG REST API for the same.
Testing:-
Local testing has been done for this change. Two factor has been enabled for a user in local. Using the new API, the 2fa mail is resent and the new 2fa code is used to login again. Login is successful. 
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42366)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger ti3

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Comment by pbarapatre10** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 557 at r3](https://reviewable.io/reviews/harness/harness-core/42366#-NLzFcmH-VuWcdN5uvYf:-NLzFcmH-VuWcdN5uvYg:b-ynddq1) ([raw file](https://github.com/harness/harness-core/blob/f6f8dfecbd4a484061bcf3362ad90d55000d2acc/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L557)):*
> ```Java
>   @AuthRule(permissionType = USER_PERMISSION_MANAGEMENT)
>   public RestResponse<Boolean> reset2fa(
>       @PathParam("userId") @NotEmpty String userId, @QueryParam("accountId") @NotEmpty String accountId) {
> ```

Please correct this to `NGCommonEntityConstants.ACCOUNT_KEY)` we should use 'accountIdentifier' as the query param. Thanks



_Code quote:_
```Java
 @QueryParam("accountId")
```

**Comment by pbarapatre10** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 555 at r3](https://reviewable.io/reviews/harness/harness-core/42366#-NLzIQ364lWQIU7D8pEC:-NLzIQ364lWQIU7D8pED:b-ujmr4x) ([raw file](https://github.com/harness/harness-core/blob/f6f8dfecbd4a484061bcf3362ad90d55000d2acc/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L555)):*
> ```Java
>   @Path("reset-two-factor-auth/{userId}")
>   @ApiOperation(value = "resend email for two factor authorization", nickname = "resetTwoFactorAuth")
>   @AuthRule(permissionType = USER_PERMISSION_MANAGEMENT)
> ```

Minor: Question? This seems to be CG side set of permission, does this work in NG? IMO, it should be `MANAGE_USER_PERMISSION` , please check with Jimit/Meenakshi and confirm on this. Thanks



_Code quote:_
```Java
@AuthRule(permissionType = USER_PERMISSION_MANAGEMENT)
```

**Review by pbarapatre10 — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42366)* status: 5 file(s) to review. 0 of 2 approvals obtained.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42366)* status: 6 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 555 at r3](https://reviewable.io/reviews/harness/harness-core/42366#-NLzIQ364lWQIU7D8pEC:-NLzblSh0s000fgppKbs:btzzsz6) ([raw file](https://github.com/harness/harness-core/blob/f6f8dfecbd4a484061bcf3362ad90d55000d2acc/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L555)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Minor: Question? This seems to be CG side set of permission, does this work in NG? IMO, it should be `MANAGE_USER_PERMISSION` , please check with Jimit/Meenakshi and confirm on this. Thanks
</blockquote></details>

Changed the ACL check
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 557 at r3](https://reviewable.io/reviews/harness/harness-core/42366#-NLzFcmH-VuWcdN5uvYf:-NLzbpgD-7LRubWSNvNo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f6f8dfecbd4a484061bcf3362ad90d55000d2acc/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L557)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Please correct this to `NGCommonEntityConstants.ACCOUNT_KEY)` we should use 'accountIdentifier' as the query param. Thanks
</blockquote></details>

Done.

**Review by pbarapatre10 — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42366)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 549 at r4](https://reviewable.io/reviews/harness/harness-core/42366#-NM2KbDu0ecn6hyqsWvT:-NM2KbDu0ecn6hyqsWvU:b-vjqv0u) ([raw file](https://github.com/harness/harness-core/blob/6a050b3c80e524858059c962902d78ef9504d564/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L549)):*
> ```Java
> 
>   @GET
>   @Path("reset-two-factor-auth/{userId}")
> ```

Shouldn't we create new APIs only using OpenAPI?
cc: @pbarapatre10

**Comment by shashank-harness** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/UserInfoServiceImpl.java` line 120 at r4](https://reviewable.io/reviews/harness/harness-core/42366#-NM2KszM2aFD2eSHoiBj:-NM2KszM2aFD2eSHoiBk:bjbrrxs) ([raw file](https://github.com/harness/harness-core/blob/6a050b3c80e524858059c962902d78ef9504d564/123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/UserInfoServiceImpl.java#L120)):*
> ```Java
> 
>   @Override
>   public boolean sendTwoFactorAuthenticationResetEmail(String userId, String accountId) {
> ```

We are using Boolean variable and method is returning boolean.
We can keep them consistent.

**Comment by shashank-harness** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/UserInfoServiceImpl.java` line 122 at r4](https://reviewable.io/reviews/harness/harness-core/42366#-NM2LTe09K2dRu9I58RE:-NM2LTe09K2dRu9I58RF:b5l4era) ([raw file](https://github.com/harness/harness-core/blob/6a050b3c80e524858059c962902d78ef9504d564/123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/UserInfoServiceImpl.java#L122)):*
> ```Java
>   public boolean sendTwoFactorAuthenticationResetEmail(String userId, String accountId) {
>     Boolean twoFactorResetEmailSent =
>         CGRestUtils.getResponse(userClient.sendTwoFactorAuthenticationResetEmail(userId, accountId));
> ```

So, here we are basically using CG's code to send email.
Have you discussed with Kapil Digani that this is expected and we do not need to send a different email for NG?

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42366)* status: 6 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/UserInfoServiceImpl.java` line 120 at r4](https://reviewable.io/reviews/harness/harness-core/42366#-NM2KszM2aFD2eSHoiBj:-NNCSyNy7iwJ5iO3uy2h:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6a050b3c80e524858059c962902d78ef9504d564/123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/UserInfoServiceImpl.java#L120)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

We are using Boolean variable and method is returning boolean.
We can keep them consistent.
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/UserInfoServiceImpl.java` line 122 at r4](https://reviewable.io/reviews/harness/harness-core/42366#-NM2LTe09K2dRu9I58RE:-NNCSyl_9BVDy4ehwnF0:b3shlbu) ([raw file](https://github.com/harness/harness-core/blob/6a050b3c80e524858059c962902d78ef9504d564/123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/UserInfoServiceImpl.java#L122)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

So, here we are basically using CG's code to send email.
Have you discussed with Kapil Digani that this is expected and we do not need to send a different email for NG?
</blockquote></details>

Confirmed with him. This email is fine.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42366)* status: 6 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 549 at r4](https://reviewable.io/reviews/harness/harness-core/42366#-NM2KbDu0ecn6hyqsWvT:-NNg7NR-6_4ooyJUdy6j:blmd2nt) ([raw file](https://github.com/harness/harness-core/blob/6a050b3c80e524858059c962902d78ef9504d564/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L549)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Shouldn't we create new APIs only using OpenAPI?
cc: @pbarapatre10 
</blockquote></details>

We can have this migrated to OpenAPI when the other UserResource APIs are migrated.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42366)* status: 6 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42366)* status: :shipit: complete! ✓

**Pull request merged**
