### PR TITLE
feat: [SSCA-981]: add skeleton implementation of getting drift between 2 artifact versions

### PR DESCRIPTION
**Pull request by inderschera**
## Describe your changes
- Added component drift api implementation.
- Modified open api spec to create componentDriftResponse model.
- Added getArtifactName() api in artifact service.
- Added drift entity - document which will be saved in database
- Added mapper for mapping internal beans to output models.
- Added repository layer for drift entity

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56198)

### CODE REVIEW

**Comment by inderschera** [comment]
trigger uts

**Review by mankrit-singh — APPROVED** [review]

**Comment by inderschera** [comment]
trigger uts

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56198)* status: 3. unresolved discussions. 

___
*[`ssca-manager/service/src/main/java/io/harness/repositories/ArtifactRepositoryCustomImpl.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/56198#-NkZ0qAS27xsUAqCUF_E:-NkZ7vrx4rfBPMLYiNQu:b-qx2l7k) ([raw file](https://github.com/harness/harness-core/blob/a255ea8628aeebe7e8aa013bc2a433e54874e657/ssca-manager/service/src/main/java/io/harness/repositories/ArtifactRepositoryCustomImpl.java#L63)):*
<details><summary><i>Previously, arpit-harness wrote…</i></summary><blockquote>

can we also call the newly added findOne function with null for pageable and projectionFields.
</blockquote></details>

Will do in next PR
___
*[`ssca-manager/service/src/main/java/io/harness/repositories/ArtifactRepositoryCustomImpl.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/56198#-NkZ0XE34FEjpFBgGc8r:-NkZ7g_S-KQCbeufv42Z:b-xgj5xl) ([raw file](https://github.com/harness/harness-core/blob/a255ea8628aeebe7e8aa013bc2a433e54874e657/ssca-manager/service/src/main/java/io/harness/repositories/ArtifactRepositoryCustomImpl.java#L67)):*
<details><summary><i>Previously, arpit-harness wrote…</i></summary><blockquote>

Why are we putting pageable for a find one type of query?
</blockquote></details>

Added that for sort. But makes more sense to just have sort as argument instead of pageable. Will change it in next PR.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/entities/drift/DriftEntity.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/56198#-NkZ3M7W0Lou4QSJ5Sv8:-NkZ86Vk5eqgQ_-2kNYO:b-bn10er) ([raw file](https://github.com/harness/harness-core/blob/a255ea8628aeebe7e8aa013bc2a433e54874e657/ssca-manager/service/src/main/java/io/harness/ssca/entities/drift/DriftEntity.java#L47)):*
<details><summary><i>Previously, arpit-harness wrote…</i></summary><blockquote>

Should we have created and updated fields here?
</blockquote></details>

This document should never be updated ideally. Will add createdat field in next PR.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/56198#-NkZ4zPk7bKBMRAk1PQU:-NkZ8GuX7anOFMMC_Hcf:b-d3441) ([raw file](https://github.com/harness/harness-core/blob/a255ea8628aeebe7e8aa013bc2a433e54874e657/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L148)):*
<details><summary><i>Previously, arpit-harness wrote…</i></summary><blockquote>

Can we rename this function to getlatestOrchestratedArtifact and return artifact instead of returning the name.
</blockquote></details>

I don't want the entire artifact, hence created this method.
What about updating it to
Optional<ArtifactEntity> getlatestArtifactWithProjections(String accountId, String orgIdentifier, String projectIdentifier, String artifactId, List<String> projections)

**Review by arpit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56198#-:-NkZDq-4Bie8hfvCWjJs:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
