### PR TITLE
fix: [CDS-42401]: Use public DNS for Azure infra

### PR DESCRIPTION
**Pull request by filip5rovic**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36951)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36951)

**Review by ivan-83 — CHANGES_REQUESTED** [review]
LGTM with a request for minor changes. Quick question, where is the logic to establishing an SSH connection over a public address if usePublicDNS is set?  

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36951#-:-NAitsXJ2EPZVICb-Nh8:b6u56n1)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/azure/response/AzureHostResponse.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/36951#-NAirqEM6nGCh-w2S0lb:-NAirqEM6nGCh-w2S0lc:b62p4jg) ([raw file](https://github.com/harness/harness-core/blob/c115bbc6f83ede1cbfaf723a9738bc1e1e14ee30/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/azure/response/AzureHostResponse.java#L25)):*
> ```Java
>   private String publicAddress;
> 
>   public String getPublicAddress() {
> ```

Do we have this behavior on CG?
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/azureconnector/AzureAdditionalParams.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/36951#-NAis1Za0sZoEOruCJJB:-NAis1Za0sZoEOruCJJC:bbrr2s) ([raw file](https://github.com/harness/harness-core/blob/c115bbc6f83ede1cbfaf723a9738bc1e1e14ee30/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/azureconnector/AzureAdditionalParams.java#L20)):*
> ```Java
>   WEB_APP_NAME("Web App name"),
>   OS_TYPE("OS type"),
>   USE_PUBLIC_DNS("OS type");
> ```

"OS type" >> Use public DNS
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/AzureSshInfraDelegateConfig.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/36951#-NAitdb86pBntz7bzeZk:-NAitdb919aTxRDhkuDs:b8wjg4r) ([raw file](https://github.com/harness/harness-core/blob/c115bbc6f83ede1cbfaf723a9738bc1e1e14ee30/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/AzureSshInfraDelegateConfig.java#L33)):*
> ```Java
>       List<EncryptedDataDetail> connectorEncryptionDataDetails, String subscriptionId, String resourceGroup,
>       Map<String, String> tags, List<EncryptedDataDetail> encryptionDataDetails, SSHKeySpecDTO sshKeySpecDto,
>       Boolean usePublicDns) {
> ```

Minor - is it possible to use boolean instead of  Boolean? 
___
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureComputeClientImpl.java` line 666 at r1](https://reviewable.io/reviews/harness/harness-core/36951#-NAiuiKlE1e93kV8OPFv:-NAiuiKlE1e93kV8OPFw:b-pu5sun) ([raw file](https://github.com/harness/harness-core/blob/c115bbc6f83ede1cbfaf723a9738bc1e1e14ee30/960-api-services/src/main/java/io/harness/azure/impl/AzureComputeClientImpl.java#L666)):*
> ```Java
>     VirtualMachineDataBuilder builder = VirtualMachineData.builder().hostName(virtualMachine.name());
> 
>     if (usePublicDns && virtualMachine.getPrimaryPublicIPAddress() != null) {
> ```

Maybe here anyway set public IP address if virtualMachine.getPrimaryPublicIPAddress() != null and later on base usePublicDNS property make decision to use publicAddress or hostName. 
___
*[`970-api-services-beans/src/main/java/io/harness/azure/model/VirtualMachineData.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/36951#-NAisaPyA7y4o2Vxa2tE:-NAisaPyA7y4o2Vxa2tF:bwyr6d4) ([raw file](https://github.com/harness/harness-core/blob/c115bbc6f83ede1cbfaf723a9738bc1e1e14ee30/970-api-services-beans/src/main/java/io/harness/azure/model/VirtualMachineData.java#L21)):*
> ```Java
>   private String publicAddress;
> 
>   public String getPublicAddress() {
> ```

Ths same question as above, if don't have this behavior on CG just remove this method.

**Review by filip5rovic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36951)* status: 8 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/azure/response/AzureHostResponse.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/36951#-NAirqEM6nGCh-w2S0lb:-NAmrcpzDLZBeWD38W5A:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/c115bbc6f83ede1cbfaf723a9738bc1e1e14ee30/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/azure/response/AzureHostResponse.java#L25)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Do we have this behavior on CG?
</blockquote></details>

Yes
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/azureconnector/AzureAdditionalParams.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/36951#-NAis1Za0sZoEOruCJJB:-NAmrfRiAIdI0zp3Uz9m:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c115bbc6f83ede1cbfaf723a9738bc1e1e14ee30/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/azureconnector/AzureAdditionalParams.java#L20)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

"OS type" >> Use public DNS
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureComputeClientImpl.java` line 666 at r1](https://reviewable.io/reviews/harness/harness-core/36951#-NAiuiKlE1e93kV8OPFv:-NAmro4H9PlPDhoc5URW:bj549gy) ([raw file](https://github.com/harness/harness-core/blob/c115bbc6f83ede1cbfaf723a9738bc1e1e14ee30/960-api-services/src/main/java/io/harness/azure/impl/AzureComputeClientImpl.java#L666)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Maybe here anyway set public IP address if virtualMachine.getPrimaryPublicIPAddress() != null and later on base usePublicDNS property make decision to use publicAddress or hostName. 
</blockquote></details>

I've made this work just like in CG. 
___
*[`970-api-services-beans/src/main/java/io/harness/azure/model/VirtualMachineData.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/36951#-NAisaPyA7y4o2Vxa2tE:-NAmrta08FsyK107BwXL:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/c115bbc6f83ede1cbfaf723a9738bc1e1e14ee30/970-api-services-beans/src/main/java/io/harness/azure/model/VirtualMachineData.java#L21)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Ths same question as above, if don't have this behavior on CG just remove this method. 
</blockquote></details>

Yes

**Comment by filip5rovic** [comment]
trigger messagecheck

**Review by ivan-83 — COMMENTED** [review]
One more thing, in InfrastructureTaskExecutableStep::publishAzureHosts method, get usePublicDNS from InfrastructureOutcome and based on it set hosts from AzureHostResponse::getHostName or from AzureHostResponse::getPublicAddress

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36951#-:-NAmz1EO6LIKSCxJFwc6:b7rwxjb)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 12 of 18 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36951)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36951#-:-NAsMwGQ1UxDZR3-74EQ:bnfp4nl)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
Approving since this is still in development

**Comment by filip5rovic** [comment]
trigger codebasehash

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36951#-:-NAsUmC51LEadrP84IxO:bnfp4nl)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 12 of 18 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36951#-:-NAsX4uU02VVJGyanNBE:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
