### PR TITLE
techdebt: [SRM-11076]: Adding unit tests for New Relic Data Collection DSL with…

### PR DESCRIPTION
**Pull request by dhruv-harness**
…out host info

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35710)

### CODE REVIEW

**Comment by dhruv-harness** [comment]
trigger ti1

**Comment by dhruv-harness** [comment]
trigger ti2

**Review by naveen-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35710)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/core/dsl/NewRelicDataCollectionDSLTest.java` line 227 at r1](https://reviewable.io/reviews/harness/harness-core/35710#-N7tywuDCIm-tIZwsjRZ:-N7tywuDCIm-tIZwsjR_:b-d4a7cu) ([raw file](https://github.com/harness/harness-core/blob/2125cc710dd3ee38ce8377d95eda7514a88a2f97/300-cv-nextgen/src/test/java/io/harness/cvng/core/dsl/NewRelicDataCollectionDSLTest.java#L227)):*
> ```Java
> 
>     assertThat(timeSeriesRecords.size()).isEqualTo(4);
>     assertThat(timeSeriesRecords.get(0).getHostname()).isNull();
> ```

We should verify other attributes of timeSeriesRecords as well ?
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/core/dsl/NewRelicDataCollectionDSLTest.java` line 270 at r1](https://reviewable.io/reviews/harness/harness-core/35710#-N7tz02M1WQJa_Kwp2Eb:-N7tz02M1WQJa_Kwp2Ec:b-89a4l7) ([raw file](https://github.com/harness/harness-core/blob/2125cc710dd3ee38ce8377d95eda7514a88a2f97/300-cv-nextgen/src/test/java/io/harness/cvng/core/dsl/NewRelicDataCollectionDSLTest.java#L270)):*
> ```Java
> 
>     assertThat(timeSeriesRecords.size()).isEqualTo(6);
>     assertThat(timeSeriesRecords.get(0).getHostname()).isNotBlank();
> ```

Ditto

**Review by naveen-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35710#-:-N7vO8Uj-G6k735wIN_6:bnfp4nl)* status: 4 file(s) to review.

**Review by naveen-harness — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35710)* status: :shipit: complete! ✓

**Pull request merged**
