### PR TITLE
feat: [CDS-38819]: K8s API based steady state check for workloads

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
## Describe your changes
Introduce steady state check for workloads(Deployment, StatefulSet, DaemonSet, Job) using kubernetes java client instead of kubectl binary (DeploymentConfig will continue to use OC binary).
Currently, changes are only for NG steps (K8s Apply, Rolling, BG, Canary & Scale).

Backward compatibility: 
A new boolean(primitive) has been introduced in NG manager request, which should be ignored if request is sent to an older delegate. All remaining changes are within the delegate.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34852)

### CODE REVIEW

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 38 of 85 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34852)* status: 31 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sApplyBaseHandler.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5sa3cG7bqZMzYUDE0r:-N5sa3cG7bqZMzYUDE0s:bnk5kmu) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sApplyBaseHandler.java#L114)):*
> ```Java
> 
>     boolean success = true;
>     if (!isErrorFrameworkEnabled) {
> ```

Does this mean that if error framework is enabled, we will not do status check for all resources ?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sApplyRequestHandler.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5salGT9uLoxVlOCqfn:-N5salGVDW-ulIwyJyPR:bw8gvk3) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sApplyRequestHandler.java#L112)):*
> ```Java
>         k8sTaskHelperBase.getLogCallback(logStreamingTaskClient, Apply, true, commandUnitsProgress), true,
>         isErrorFrameworkSupported());
>     LogCallback waitForSteadyStateLogCallback =
> ```

nit: can be final
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sApplyRequestHandler.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5saHklCXNGq7Jx8qvD:-N5saHklCXNGq7Jx8qvE:b-evs7g3) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sApplyRequestHandler.java#L115)):*
> ```Java
>         k8sTaskHelperBase.getLogCallback(logStreamingTaskClient, WaitForSteadyState, true, commandUnitsProgress);
> 
>     if (!k8sApplyRequest.isSkipSteadyStateCheck() && EmptyPredicate.isNotEmpty(k8sApplyHandlerConfig.getWorkloads())) {
> ```

nit: we can do static import of isNotEmpty to reduce verbosity
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/client/K8sApiClient.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5sce6PDxMtYMDri50y:-N5sce6Q0MW_0mIrPPst:bgfms0q) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/client/K8sApiClient.java#L54)):*
> ```Java
>     LogCallback executionLogCallback = steadyStateDTO.getExecutionLogCallback();
> 
>     executionLogCallback.saveExecutionLog("Executing steady state check using Kubernetes java client.");
> ```

maybe better to log this in the delegate logs instead of UI ? or hide the word "java" from the user 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/client/K8sApiClient.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5scuPw7pdN0blzX-w9:-N5scuPw7pdN0blzX-wA:b-ykta6p) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/client/K8sApiClient.java#L56)):*
> ```Java
>     executionLogCallback.saveExecutionLog("Executing steady state check using Kubernetes java client.");
> 
>     K8sEventWatchDTO eventWatchDTO = k8sClientHelper.createEventWatchDTO(steadyStateDTO, apiClient, null);
> ```

better to have 2 overloaded methods here, instead of passing 1 value as null
```
public K8sEventWatchDTO createEventWatchDTO(K8sSteadyStateDTO steadyStateDTO, ApiClient apiClient, Kubectl client) 
public K8sEventWatchDTO createEventWatchDTO(K8sSteadyStateDTO steadyStateDTO, ApiClient apiClient)
``` 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/client/K8sClientHelper.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5sgGqdDtMEsVeEqxz6:-N5sgGqe3bF9W6tS-imH:bmojsil) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/client/K8sClientHelper.java#L34)):*
> ```Java
>   @Inject private ContainerDeploymentDelegateBaseHelper containerDeploymentDelegateBaseHelper;
> 
>   public K8sEventWatchDTO createEventWatchDTO(K8sSteadyStateDTO steadyStateDTO, ApiClient apiClient, Kubectl client) {
> ```

since this is a client helper and supposed to be used by the K8sClient only, can we mark the methods as package private instead ?

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 41 of 85 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34852)* status: 16 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sApplyBaseHandler.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5oArB1-LPL9q7pfjOP:-N5oArB1-LPL9q7pfjOQ:b-esutpo) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sApplyBaseHandler.java#L114)):*
> ```Java
> 
>     boolean success = true;
>     if (!isErrorFrameworkEnabled) {
> ```

Why we're doing steady state check based on if ErrorFramework is enabled?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/client/K8sApiClient.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5ssjH664WYGGAnBZ0J:-N5ssjH664WYGGAnBZ0K:bcpqumn) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/client/K8sApiClient.java#L65)):*
> ```Java
>       for (String ns : namespaces) {
>         Future<?> threadRef = k8sApiEventWatcher.watchForEvents(ns, eventWatchDTO, executionLogCallback);
>         futureList.add(threadRef);
> ```

Because you never call get on these futures, any exceptions thrown by event watch logic will be ignored
___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5sn4mE0KPu2KtgmoJg:-N5sn4mFEkiuDtWfHMjF:b-vo4d2d) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java#L62)):*
> ```Java
>       boolean cancelled = future.cancel(true);
>       if (!cancelled) {
>         future.cancel(true);
> ```

we should log if we weren't able to cancel future and then try one more time. I don't think this is an expected behavior that we weren't able to cancel it
___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5sojvjDr2zUDmktoyp:-N5sojvjDr2zUDmktoyq:b-rconpq) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java#L96)):*
> ```Java
>             V1ObjectReference ref = event.getInvolvedObject();
>             if (ref.getName() != null
>                 && workloadNames.parallelStream().noneMatch(workloadName -> ref.getName().contains(workloadName))) {
> ```

I don't think that we will get any good of using parallelStream here, having few workloadsNames will most probably increase processing time due to thread pool overhead
___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java` line 122 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5sp6NY2xryR8QW2h3V:-N5sp6NY2xryR8QW2h3W:b-ihdkux) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java#L122)):*
> ```Java
>         }
>       }
>     } catch (Exception e) {
> ```

This catch is bugging me a bit. If behind Exception is hidden InterruptedException that can be potentially thrown by any blocking requests on k8s api client. And since we're mostly always calling future.cancel, then I would expect that this will happen mostly always. Will it result in some issues or thread leaking if we aren't going to reset interrupt status? Can we check this and ensure that we don't need to call Thread.currentThread().interrupt() in case of InterruptedException? And basically in case of InterruptedException we should treat this as successful state, right? 
___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/workload/DeploymentApiWatcher.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5oBt4m4tHT0PPjg7iM:-N5oBt4m4tHT0PPjg7iN:b-v1q9t) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/workload/DeploymentApiWatcher.java#L81)):*
> ```Java
>                   "object has been deleted", KubernetesCliCommandType.STEADY_STATE_CHECK);
>             default:
>               throw new KubernetesCliTaskRuntimeException(
> ```

any reason why we should fail if event is of unknown type?

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 6 of 85 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34852)* status: 10 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/statusviewer/DaemonSetStatusViewer.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5spE-y1rOjEhbnJczM:-N5spE-y1rOjEhbnJczN:bhxf2gh) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/960-api-services/src/main/java/io/harness/k8s/steadystate/statusviewer/DaemonSetStatusViewer.java#L27)):*
> ```Java
> @Singleton
> public class DaemonSetStatusViewer {
>   private static final String ROLLING_UPDATE_STRATEGY_TYPE = "RollingUpdate";
> ```

nit: new line here for better readability
___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/statusviewer/DaemonSetStatusViewer.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5sqhTW6g5_rmmd8e5q:-N5sqhTW6g5_rmmd8e5r:b-mmsmxe) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/960-api-services/src/main/java/io/harness/k8s/steadystate/statusviewer/DaemonSetStatusViewer.java#L34)):*
> ```Java
>     }
>     V1ObjectMeta meta = daemonSet.getMetadata();
> ```

can we put a comment here that this logic was taken from kubectl, for future reference
___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/workload/DaemonSetApiWatcher.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5swdXT-tbF3SXfbTMl:-N5swdXT-tbF3SXfbTMm:b-zbanjm) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/workload/DaemonSetApiWatcher.java#L53)):*
> ```Java
>       try (Watch<V1DaemonSet> watch = Watch.createWatch(apiClient,
>                appsV1Api.listNamespacedDaemonSetCall(
>                    workload.getNamespace(), null, true, null, null, null, null, null, null, 300, true, null),
> ```

lets extract this constant out 
___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/workload/DaemonSetApiWatcher.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5t2bjwBHenT1bGcbdt:-N5t2bjwBHenT1bGcbdu:byng7yz) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/workload/DaemonSetApiWatcher.java#L75)):*
> ```Java
>             default:
>               throw new KubernetesCliTaskRuntimeException(
>                   String.format("unexpected k8s event %s", event.type), KubernetesCliCommandType.STEADY_STATE_CHECK);
> ```

should we not just log a warning here ( instead of throwing exception ) ? because k8s can add new events on there end that can impact our deployments if we start throwing exception
___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/workload/DaemonSetApiWatcher.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5t3l225FD4Qhggl4PU:-N5t3l225FD4Qhggl4PV:b-pfjbou) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/workload/DaemonSetApiWatcher.java#L80)):*
> ```Java
>       } catch (IOException e) {
>         IOException ex = ExceptionMessageSanitizer.sanitizeException(e);
>         String errorMessage = "Failed to close Kubernetes watch." + ExceptionUtils.getMessage(ex);
> ```

this message might not be useful to the end user. 
is there any way we can recover from this ? maybe continue watching ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 25 of 85 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34852)* status: Some of the checks are too old. 2 change requests. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34852)* status: Some of the checks are too old. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5sojvjDr2zUDmktoyp:-N61a9z3AWUjRmSxV5n_:b32v57) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java#L96)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I don't think that we will get any good of using parallelStream here, having few workloadsNames will most probably increase processing time due to thread pool overhead
</blockquote></details>

+1

**Comment by abhinavsingh1196** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/client/K8sApiClient.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5sce6PDxMtYMDri50y:-N67Ui6E-Mndb8tlLj2n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/client/K8sApiClient.java#L54)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

maybe better to log this in the delegate logs instead of UI ? or hide the word "java" from the user 
</blockquote></details>

Done.

**Comment by abhinavsingh1196** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/client/K8sApiClient.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5scuPw7pdN0blzX-w9:-N67UjkkA7Wek72y8hlA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/client/K8sApiClient.java#L56)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

better to have 2 overloaded methods here, instead of passing 1 value as null
```
public K8sEventWatchDTO createEventWatchDTO(K8sSteadyStateDTO steadyStateDTO, ApiClient apiClient, Kubectl client) 
public K8sEventWatchDTO createEventWatchDTO(K8sSteadyStateDTO steadyStateDTO, ApiClient apiClient)
``` 
</blockquote></details>

Done.

**Comment by abhinavsingh1196** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/client/K8sClientHelper.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5sgGqdDtMEsVeEqxz6:-N67VEL2B84GoCqdanbS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/client/K8sClientHelper.java#L34)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

since this is a client helper and supposed to be used by the K8sClient only, can we mark the methods as package private instead ?
</blockquote></details>

Done.

**Comment by abhinavsingh1196** [comment]
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5sn4mE0KPu2KtgmoJg:-N67VYez9s80LWvAAM3L:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java#L62)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

we should log if we weren't able to cancel future and then try one more time. I don't think this is an expected behavior that we weren't able to cancel it
</blockquote></details>

Done.

**Comment by abhinavsingh1196** [comment]
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5sojvjDr2zUDmktoyp:-N67VaiBBLlc3SGZguEB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java#L96)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Comment by abhinavsingh1196** [comment]
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java` line 122 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5sp6NY2xryR8QW2h3V:-N67Vbyr7B_0gQN1tZUr:b-3f58yd) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java#L122)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This catch is bugging me a bit. If behind Exception is hidden InterruptedException that can be potentially thrown by any blocking requests on k8s api client. And since we're mostly always calling future.cancel, then I would expect that this will happen mostly always. Will it result in some issues or thread leaking if we aren't going to reset interrupt status? Can we check this and ensure that we don't need to call Thread.currentThread().interrupt() in case of InterruptedException? And basically in case of InterruptedException we should treat this as successful state, right? 
</blockquote></details>

Thanks for pointing out, I have removed the generic Exception from the catch block as it was not needed. InterruptedException should now interrupt the thread as expected. I will test this once, just to confirm.

**Comment by abhinavsingh1196** [comment]
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/workload/DaemonSetApiWatcher.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5t3l225FD4Qhggl4PU:-N67VwB396j-vrdZ3Y13:b-2fxikg) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/workload/DaemonSetApiWatcher.java#L80)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this message might not be useful to the end user. 
is there any way we can recover from this ? maybe continue watching ?
</blockquote></details>

Placed a boolean to indicate the overall end status if this exception is thrown. Not logging it on the UI anymore.

**Comment by abhinavsingh1196** [comment]
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/workload/DeploymentApiWatcher.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5oBt4m4tHT0PPjg7iM:-N67W9O-9wSjd9yXnJoe:bf90wta) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/workload/DeploymentApiWatcher.java#L81)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

any reason why we should fail if event is of unknown type?
</blockquote></details>

can't think of a reasonable explanation for keeping this. have changed it to log warning instead of failing.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 38 of 42 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34852)* status: 2 change requests. 5. unresolved discussions. 0 of 1 approvals obtained.

**Comment by abhinavsingh1196** [comment]
trigger feature-build

**Comment by abhinavsingh1196** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sApplyBaseHandler.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/34852#-N5oArB1-LPL9q7pfjOP:-N6HoC4P1eO8Ewgvh8Me:b-6lksr4) ([raw file](https://github.com/harness/harness-core/blob/abd506760ade6c135e3b072bc0ed3b337968ab93/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sApplyBaseHandler.java#L114)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

In this case a different flag should be passed. Doing steady state based on isErrorFrameworkEnabled is confusing from logical point of view and can result in an unexpected behaviour if this flag will be set as true for CG 
</blockquote></details>

added a new flag instead of using the errorFramework flag

**Comment by abhinavsingh1196** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 350 at r4](https://reviewable.io/reviews/harness/harness-core/34852#-N68Hvq5-OJZPfZ2iMR_:-N6HoNIT1teverJTueAh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/334f687f5c990d72bada5a4761196f6d1b857025/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L350)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

FeatureName ideally should be added at the end of list
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 11 of 12 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34852)* status: :shipit: complete! ✓

**Pull request merged**
