### PR TITLE
[fix]:[pl-26312]: Fix for adding repoName for getTemplate

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Fix for adding repoName for getTemplate, have tested out locally, with this change we are able to get the repoName and the filePath in gitDetails for the list-metadata api

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36076)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36076)

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 480 at r1](https://reviewable.io/reviews/harness/harness-core/36076#-N8gvXok88J1mncE1zjV:-N8gvXok88J1mncE1zjW:b-o8vea5) ([raw file](https://github.com/harness/harness-core/blob/733acc957b25d6d92524e62d62a25a7d6b58e0a2/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L480)):*
> ```Java
>           INCLUDE_ALL_TEMPLATES_ACCESSIBLE) boolean includeAllTemplatesAccessibleAtScope,
>       @Parameter(description = "This contains details of Git Entity like Git Branch info")
>       @BeanParam GitEntityFindInfoDTO gitEntityBasicInfo,
> ```

is this class being used at all other places and thats why we are using the same for info?

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 79 at r1](https://reviewable.io/reviews/harness/harness-core/36076#-N8gvg2F8ayUQ6uY8TGa:-N8gvg2F8ayUQ6uY8TGb:bvbsec7) ([raw file](https://github.com/harness/harness-core/blob/733acc957b25d6d92524e62d62a25a7d6b58e0a2/840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L79)):*
> ```Java
>         : EntityGitDetails.builder().build();
>   }
>   public EntityGitDetails getEntityGitDetailsForListTemplates(TemplateEntity templateEntity) {
> ```

why is it dedicated for List? Is it doing something special?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36076)* status: 3 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 79 at r1](https://reviewable.io/reviews/harness/harness-core/36076#-N8gvg2F8ayUQ6uY8TGa:-N8gw1dA3duyHnwnNvf6:b-kmax8q) ([raw file](https://github.com/harness/harness-core/blob/733acc957b25d6d92524e62d62a25a7d6b58e0a2/840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L79)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is it dedicated for List? Is it doing something special?
</blockquote></details>

In the list case, for remote templates we cannt use the getEntityGitDetailsFromScm as the values are null
for the getTemplate, we need to use getEntityGitDetailsFromScm for populating the git entity fields 
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 480 at r1](https://reviewable.io/reviews/harness/harness-core/36076#-N8gvXok88J1mncE1zjV:-N8gzi34E_XA63cSqFCa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/733acc957b25d6d92524e62d62a25a7d6b58e0a2/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L480)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

is this class being used at all other places and thats why we are using the same for info?
</blockquote></details>

Done.

**Review by bhavya181 — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36076)* status: 2. unresolved discussions.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36076)* status: 2. unresolved discussions.

**Pull request merged**
