### PR TITLE
[fix]: [PL-27201] : ng ldap invite flow cases

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
Handling NG-Ldap group sync scenario. Syncing LDAP user groups and corresponding users under it, need to create/update/remove users in Harness as well. When the user is not present in Harness, we invite the user, auto-accept the invite and then create userMetadata/userMemberships record in NG collections. The above things are fixed as part of this PR.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36259)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36259)

**Comment by pbarapatre10** [comment]
trigger ti4

**Comment by mohitg0795** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java` line 162 at r2](https://reviewable.io/reviews/harness/harness-core/36259#-N98MQvt0NoE0GEYvNF9:-N98MQvt0NoE0GEYvNFA:baf72g6) ([raw file](https://github.com/harness/harness-core/blob/b6b1beb3ba4fe0fdbe490503f3934b858486a90e/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java#L162)):*
> ```Java
> 
>     if (userOptional.isEmpty()) {
>       log.warn(
> ```

any particular reason to make it warn? If its important, we can make it error log itself. Atleast then its useful to us.

**Review by puneetsar — COMMENTED** [review]
There is no description on the change done in this PR.
Also details on the ticket are missing https://harness.atlassian.net/browse/PL-27201

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36259#-:-N992jCJ8xwkef-1Wh5B:bvfbuqf)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java` line 162 at r2](https://reviewable.io/reviews/harness/harness-core/36259#-N98MQvt0NoE0GEYvNF9:-N9AC1TFATtfluTGhPFH:b32p4ke) ([raw file](https://github.com/harness/harness-core/blob/b6b1beb3ba4fe0fdbe490503f3934b858486a90e/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java#L162)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

any particular reason to make it warn? If its important, we can make it error log itself. Atleast then its useful to us.
</blockquote></details>

@mohitg0795 if the user invite/or add to scope for the user fails, we don't fail entire sync for the group & other users, rather just log it (as warn) and continue. This user should get synced in the next cron sync cycle. Thanks

**Comment by pbarapatre10** [comment]
@puneetsar Added description and also updated in the JIRA ticket. Thanks

**Comment by mohitg0795** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java` line 162 at r2](https://reviewable.io/reviews/harness/harness-core/36259#-N98MQvt0NoE0GEYvNF9:-N9AK1vj6eNGJVogEOyv:b-feunn9) ([raw file](https://github.com/harness/harness-core/blob/b6b1beb3ba4fe0fdbe490503f3934b858486a90e/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java#L162)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

@mohitg0795 if the user invite/or add to scope for the user fails, we don't fail entire sync for the group & other users, rather just log it (as warn) and continue. This user should get synced in the next cron sync cycle. Thanks
</blockquote></details>

So, I just wanted to point out that warn logs won't get printed on production. So, if we need it, we should make it error log.

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java` line 162 at r2](https://reviewable.io/reviews/harness/harness-core/36259#-N98MQvt0NoE0GEYvNF9:-N9AXJ88AJvI7_wXoAsx:b-3mtis5) ([raw file](https://github.com/harness/harness-core/blob/b6b1beb3ba4fe0fdbe490503f3934b858486a90e/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java#L162)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

So, I just wanted to point out that warn logs won't get printed on production. So, if we need it, we should make it error log.
</blockquote></details>

@mohitg0795 warn logs do get printed in prod. Example- https://cloudlogging.app.goo.gl/o6aq4BkYFyco9m6v6 , this is from prod ng-manager pod logs only. Thanks

**Comment by mohitg0795** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java` line 162 at r2](https://reviewable.io/reviews/harness/harness-core/36259#-N98MQvt0NoE0GEYvNF9:-N9AYhC0EMGQRjXU2-Io:bcbzp9j) ([raw file](https://github.com/harness/harness-core/blob/b6b1beb3ba4fe0fdbe490503f3934b858486a90e/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java#L162)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

@mohitg0795 warn logs do get printed in prod. Example- https://cloudlogging.app.goo.gl/o6aq4BkYFyco9m6v6 , this is from prod ng-manager pod logs only. Thanks
</blockquote></details>

Ok, not sure. We had some warn logs which I didn't see previously. Anyways if they are coming we are good.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java` line 162 at r2](https://reviewable.io/reviews/harness/harness-core/36259#-N98MQvt0NoE0GEYvNF9:-N9AYqfF-EOsWHOXFuSF:b58rfi) ([raw file](https://github.com/harness/harness-core/blob/b6b1beb3ba4fe0fdbe490503f3934b858486a90e/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java#L162)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Ok, not sure. We had some warn logs which I didn't see previously. Anyways if they are coming we are good. 
</blockquote></details>

Also, just to mention, this thread wasn't a blocking thread, but "discussing" thread.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36259)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by boopesh007 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36259)* status: :shipit: complete! ✓

**Review by kapil-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36259)* status: :shipit: complete! ✓

**Pull request merged**
