### PR TITLE
[feat]: [PIE-7131]: Remove strict input set validation to ignore extra fields

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41782)

### CODE REVIEW

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 7 of 14 files at r1, 14 of 15 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41782)* status: 22 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41782)* status: 23 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 14 files at r1, 4 of 15 files at r2, 1 of 1 files at r3, 13 of 15 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41782)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 90 at r5](https://reviewable.io/reviews/harness/harness-core/41782#-NL62WRBAfDJ21z14w7r:-NL62WRBAfDJ21z14w7s:bkc6qar) ([raw file](https://github.com/harness/harness-core/blob/2a265f202e82e94ded58fa3da551ade5df0949de/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L90)):*
> ```Java
>         if (value instanceof TextNode && NGExpressionUtils.matchesInputSetPattern(((TextNode) value).asText())) {
>           return;
>         }
> ```

can you add comment to code why specially we are checking this?



_Code quote:_
```Java
        if (value instanceof TextNode && NGExpressionUtils.matchesInputSetPattern(((TextNode) value).asText())) {
          return;
        }
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 203 at r5](https://reviewable.io/reviews/harness/harness-core/41782#-NL646QgEfGSyu3KwVdt:-NL646QgEfGSyu3KwVdu:bw2hc85) ([raw file](https://github.com/harness/harness-core/blob/2a265f202e82e94ded58fa3da551ade5df0949de/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L203)):*
> ```Java
>     String pipelineTemplateForValidations = createTemplateFromPipeline(pipelineYaml);
>     String pipelineTemplate = EmptyPredicate.isEmpty(stageIdentifiers)
>         ? createTemplateFromPipeline(pipelineYaml)
> ```

why we are creating again?



_Code quote:_
```Java
createTemplateFromPipeline(pipelineYaml)
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 252 at r5](https://reviewable.io/reviews/harness/harness-core/41782#-NL64BJWEzEvtUNpdVAP:-NL64BJWEzEvtUNpdVAQ:bs9oznw) ([raw file](https://github.com/harness/harness-core/blob/c8fb78a35d3b0b7a1d5ac0fd491dceea0d0244d9/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L252)):*
> ```Java
>           if (!entity2.isPresent()) {
>             invalidReferences.add(identifier);
>           } else {
> ```

are we not checking if input set is not present then we should fail?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/OverlayInputSetValidationHelper.java` line 70 at r5](https://reviewable.io/reviews/harness/harness-core/41782#-NL64uR31muJKUs4Fp64:-NL64uR31muJKUs4Fp65:b-qlk2fy) ([raw file](https://github.com/harness/harness-core/blob/2a265f202e82e94ded58fa3da551ade5df0949de/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/OverlayInputSetValidationHelper.java#L70)):*
> ```Java
>         inputSetService, inputSetReferences, accountId, orgIdentifier, projectIdentifier, pipelineIdentifier);
>     Map<String, String> invalidReferences =
>         InputSetErrorsHelper.getInvalidInputSetReferences(inputSets, inputSetReferences);
> ```

can this only check if input set is present?

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41782)* status: 5 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 90 at r5](https://reviewable.io/reviews/harness/harness-core/41782#-NL62WRBAfDJ21z14w7r:-NLH2p3987UYLSN40Do0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2a265f202e82e94ded58fa3da551ade5df0949de/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L90)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you add comment to code why specially we are checking this?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 203 at r5](https://reviewable.io/reviews/harness/harness-core/41782#-NL646QgEfGSyu3KwVdt:-NLH2plfBDaLsL3ZPjIs:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/2a265f202e82e94ded58fa3da551ade5df0949de/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L203)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are creating again?
</blockquote></details>

Removed
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 252 at r5](https://reviewable.io/reviews/harness/harness-core/41782#-NL64BJWEzEvtUNpdVAP:-NLH2qUo5OrWdOSLpXl8:bdjbibn) ([raw file](https://github.com/harness/harness-core/blob/c8fb78a35d3b0b7a1d5ac0fd491dceea0d0244d9/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L252)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

are we not checking if input set is not present then we should fail?
</blockquote></details>

Yes we won't fail, just ignore
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/OverlayInputSetValidationHelper.java` line 70 at r5](https://reviewable.io/reviews/harness/harness-core/41782#-NL64uR31muJKUs4Fp64:-NLH36GfDA6ofxMz8Zy1:b-owmx1z) ([raw file](https://github.com/harness/harness-core/blob/2a265f202e82e94ded58fa3da551ade5df0949de/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/OverlayInputSetValidationHelper.java#L70)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can this only check if input set is present?
</blockquote></details>

It checks if input set is present and is a normal input set and not an overlay input set

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41782)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41782)* status: :shipit: complete! ✓

**Pull request merged**
