### PR TITLE
feat: [PL-41382]: Added new usergroup api with filter and pagination support

### PR DESCRIPTION
**Pull request by meenakshi-harness**
## Describe your changes
Added new API to fetch user-groups. This has support of both filterDTo and paginations.

Testing:
1. User have permission on ALL USER GROUP. API should return paged data as requested in page requested.
2. User have permission on SELECTED USER GROUP that exist in page 1 and 2. API should return paged data as requested in page requested with only the permitted UGs. In this case USER GROUP in page 1 and page 2 can be returned in page1.
3. Add filter for Ids. If identifier list size is less that page size than result will have either all UGs in filter or the ones permitted.
4. Add filter for Ids. If identifier list size is more that page size than result will have either all UGs of page size or the ones permitted.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53802)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53802)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java` line 374 at r1](https://reviewable.io/reviews/harness/harness-core/53802#-Ng396Rr3Pf1TFnysABc:-Ng396Rr3Pf1TFnysABd:b-dlil3y) ([raw file](https://github.com/harness/harness-core/blob/d4a7c28e53d49303fa8a006f1a0c846cd6f19fdf/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java#L374)):*
> ```Java
>   @POST
>   @Path("filter")
>   @ApiOperation(value = "Get User Group List with Filter", nickname = "getUserGroupListFilter")
> ```

Can we get these messages and description reviewed once by doc
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java` line 375 at r1](https://reviewable.io/reviews/harness/harness-core/53802#-Ng39N519zjHrRtZkvVf:-Ng39N519zjHrRtZkvVg:b-hvp08j) ([raw file](https://github.com/harness/harness-core/blob/d4a7c28e53d49303fa8a006f1a0c846cd6f19fdf/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java#L375)):*
> ```Java
>   @Path("filter")
>   @ApiOperation(value = "Get User Group List with Filter", nickname = "getUserGroupListFilter")
>   @Operation(operationId = "getUsersGroupLisFilter", summary = "List User Groups by filter",
> ```

spelling mistake - getUsersGroupListFilter
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java` line 388 at r1](https://reviewable.io/reviews/harness/harness-core/53802#-Ng38ynXCVdFJ-2XbUPP:-Ng38ynXCVdFJ-2XbUPQ:b-6fy7ap) ([raw file](https://github.com/harness/harness-core/blob/d4a7c28e53d49303fa8a006f1a0c846cd6f19fdf/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java#L388)):*
> ```Java
>       @NotNull UserGroupFilterDTO userGroupFilterDTO, @BeanParam PageRequest pageRequest) {
>     if (isEmpty(pageRequest.getSortOrders())) {
>       SortOrder order = SortOrder.Builder.aSortOrder().withField("lastModifiedAt", SortOrder.OrderType.DESC).build();
> ```

Can we use UserGroupKeys.lastModifiedAt? 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java` line 401 at r1](https://reviewable.io/reviews/harness/harness-core/53802#-Ng38f-F5-X8V1PLn2Mi:-Ng38f-F5-X8V1PLn2Mj:bmxh1hd) ([raw file](https://github.com/harness/harness-core/blob/d4a7c28e53d49303fa8a006f1a0c846cd6f19fdf/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java#L401)):*
> ```Java
>       return ResponseDTO.newResponse(getNGPageResponse(userGroups));
>     }
>     Pageable pageable = Pageable.ofSize(50000); // keeping the default max supported value
> ```

This isn't clear
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/53802#-Ng37r8v5BDXADrsVOOL:-Ng37r8w3f9n3pH-4Y-D:bbb5qds) ([raw file](https://github.com/harness/harness-core/blob/d4a7c28e53d49303fa8a006f1a0c846cd6f19fdf/123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java#L74)):*
> ```Java
>   List<UserGroup> list(UserGroupFilterDTO userGroupFilterDTO);
> 
>   Page<UserGroup> list(UserGroupFilterDTO userGroupFilterDTO, Pageable pageable);
> ```

Let it return List<UserGroup> like above method
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 392 at r1](https://reviewable.io/reviews/harness/harness-core/53802#-Ng382gwEjTLRcDquF4o:-Ng382gwEjTLRcDquF4p:bnqzmwc) ([raw file](https://github.com/harness/harness-core/blob/d4a7c28e53d49303fa8a006f1a0c846cd6f19fdf/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L392)):*
> ```Java
> 
>   @Override
>   public List<UserGroup> list(UserGroupFilterDTO userGroupFilterDTO) {
> ```

Can we delegate 
list(userGroupFilterDTO, Pageable.unpaged())

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53802)* status: 3 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 395 at r1](https://reviewable.io/reviews/harness/harness-core/53802#-NgDwY9kDxt77lIf3-_n:-NgDwY9kDxt77lIf3-_o:bhotjzc) ([raw file](https://github.com/harness/harness-core/blob/d4a7c28e53d49303fa8a006f1a0c846cd6f19fdf/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L395)):*
> ```Java
>     validateFilter(userGroupFilterDTO);
>     Criteria criteria = createCriteriaWithFilterDTOWithInheritedUG(userGroupFilterDTO);
>     return userGroupRepository.findAll(criteria, Pageable.unpaged()).getContent();
> ```

Shouldn't this be limited to 50k ?

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53802)* status: 3 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java` line 374 at r1](https://reviewable.io/reviews/harness/harness-core/53802#-Ng396Rr3Pf1TFnysABc:-NgHIWvi6XhbkZtrlOov:b-kxwnm9) ([raw file](https://github.com/harness/harness-core/blob/d4a7c28e53d49303fa8a006f1a0c846cd6f19fdf/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java#L374)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we get these messages and description reviewed once by doc
</blockquote></details>

sure cc: @deepakbolangady 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java` line 375 at r1](https://reviewable.io/reviews/harness/harness-core/53802#-Ng39N519zjHrRtZkvVf:-NgHIgXeB3aEvd4p_5Ma:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d4a7c28e53d49303fa8a006f1a0c846cd6f19fdf/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java#L375)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

spelling mistake - getUsersGroupListFilter
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java` line 388 at r1](https://reviewable.io/reviews/harness/harness-core/53802#-Ng38ynXCVdFJ-2XbUPP:-NgHJYtY8EHMpTCHN8cQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d4a7c28e53d49303fa8a006f1a0c846cd6f19fdf/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java#L388)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we use UserGroupKeys.lastModifiedAt?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java` line 401 at r1](https://reviewable.io/reviews/harness/harness-core/53802#-Ng38f-F5-X8V1PLn2Mi:-NgHJ_IMAhHmNfoLznKD:baq0u58) ([raw file](https://github.com/harness/harness-core/blob/d4a7c28e53d49303fa8a006f1a0c846cd6f19fdf/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java#L401)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This isn't clear
</blockquote></details>

This is to fetch max 50k UG to filter permitted UG when user has permission on only selected UserGroups. This is inline with other entities.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/53802#-Ng37r8v5BDXADrsVOOL:-NgHJteGEsXEmC2m6RqV:b-kx9m8h) ([raw file](https://github.com/harness/harness-core/blob/d4a7c28e53d49303fa8a006f1a0c846cd6f19fdf/123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java#L74)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Let it return List<UserGroup> like above method
</blockquote></details>

We need page return type in this case. We will remove list method once that API is deprecated.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 392 at r1](https://reviewable.io/reviews/harness/harness-core/53802#-Ng382gwEjTLRcDquF4o:-NgHK4cz2JAxidNqTMYt:bgxfabb) ([raw file](https://github.com/harness/harness-core/blob/d4a7c28e53d49303fa8a006f1a0c846cd6f19fdf/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L392)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we delegate 
list(userGroupFilterDTO, Pageable.unpaged())
</blockquote></details>

Din't get this
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 395 at r1](https://reviewable.io/reviews/harness/harness-core/53802#-NgDwY9kDxt77lIf3-_n:-NgHKK4-7bJHih1i3dsg:bn714ap) ([raw file](https://github.com/harness/harness-core/blob/d4a7c28e53d49303fa8a006f1a0c846cd6f19fdf/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L395)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Shouldn't this be limited to 50k ?
</blockquote></details>

This will be default 10k limit only as per service level config. Also we will deprecate this API once paginated is released

**Comment by meenakshi-harness** [comment]
trigger uts

**Review by ankit-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53802)* status: 4 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained.

**Review by ankit-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53802)* status: 4 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained.

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Comment by meenakshi-harness** [comment]
trigger ut6

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53802)* status: 4 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java` line 379 at r4](https://reviewable.io/reviews/harness/harness-core/53802#-NgReP6IBzSe4HNtbhve:-NgReP6IBzSe4HNtbhvf:bhmwjg0) ([raw file](https://github.com/harness/harness-core/blob/0531e3e96808690e4ce27f25fb3eb368a6a45d73/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java#L379)):*
> ```Java
>   @Path("filter")
>   @ApiOperation(value = "Get User Group List with Filter", nickname = "getUserGroupListFilter")
>   @Operation(operationId = "getUsersGroupListFilter", summary = "List User Groups by filter",
> ```

getFilteredUserGroupsList
Get filtered User Groups

Lets use this

**Comment by meenakshi-harness** [comment]
trigger uts

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53802)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53802)* status: :shipit: complete! ✓

**Review by Jimit09Gandhi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53802)* status: :shipit: complete! ✓

**Pull request merged**
