### PR TITLE
[feat]: [PIE-2727]: creating Yaml Schema ErorrDTO

### PR DESCRIPTION
**Pull request by brijeshdhakar**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31214)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by naidu-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31214)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/yaml/YamlSchemaErrorDTO.java, line 21 at r1](https://reviewable.io/reviews/harness/harness-core/31214#-MxZUtoy8lZyqaU2UHQS:-MxZUtozAo8XFWtcfpw5:bww7a7e) ([raw file](https://github.com/harness/harness-core/blob/e9c3e70c947e78f29061c40605d589d3f4ad496c/800-pipeline-service/src/main/java/io/harness/pms/pipeline/yaml/YamlSchemaErrorDTO.java#L21)):*
> ```Java
> public class YamlSchemaErrorDTO {
>   String message;
>   String stage;
> ```

do we need to separate stage & step?
cant we give FQN?

if we have to give both, what above fields should contain the info about?

**Comment by brijeshdhakar** [comment]
___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/yaml/YamlSchemaErrorDTO.java, line 21 at r1](https://reviewable.io/reviews/harness/harness-core/31214#-MxZUtoy8lZyqaU2UHQS:-Mx_9uV43Z0wUEexUylN:b-2unzqi) ([raw file](https://github.com/harness/harness-core/blob/e9c3e70c947e78f29061c40605d589d3f4ad496c/800-pipeline-service/src/main/java/io/harness/pms/pipeline/yaml/YamlSchemaErrorDTO.java#L21)):*
<details><summary><i>Previously, naidu-harness (Sanyasi Naidu Annepu) wrote…</i></summary><blockquote>

do we need to separate stage & step?
cant we give FQN?

if we have to give both, what above fields should contain the info about?
</blockquote></details>

UI will use stage and step to do the grouping of messages. And yes we need to give FQN as well. I will the FQN.

**Review by hextechpal — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31214)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31214)* status: 1 change requests. 1. unresolved discussions.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 10 of 11 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31214)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31214)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 10 of 11 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31214#-:-N-2NT2JBGl8wkoHabsw:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
