### PR TITLE
[feat]: [PIE-9101]: Add advisor for pipeline rollback failure strategy

### PR DESCRIPTION
**Pull request by namanvermah**
When a step fails with Pipeline Rollback as Failure Strategy, it will publish sweeping output at pipeline level to use pipeline rollback. In a future PR, functionality will be added to consume this sweeping output and actually start pipeline rollback.

As Pipeline Rollback Failure Strategy is not released yet, this PR has no changes in the current behaviour

Also, RollbackStartAdvisor has been deleted as it isn't used anywhere.
Some of the Changes required alongside:
* 5 step plan creators have the same change where the advisor is being set for pipeline rollback
* 6 alias.txt changes, 1 change in txt file for kryo

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45407)

### CODE REVIEW

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 11 of 14 files at r1, 12 of 12 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45407)* status: 24 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45407)* status: 24 file(s) to review. 1 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/prb/OnFailPipelineRollbackAdviser.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/45407#-NR7UgYG8Y-dpbTUjkkS:-NR7UgYG8Y-dpbTUjkkT:b3d4bar) ([raw file](https://github.com/harness/harness-core/blob/586fda72a732b942597dd4dcdc61e9675538efac/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/prb/OnFailPipelineRollbackAdviser.java#L44)):*
> ```Java
> 
>   @Override
>   public AdviserResponse onAdviseEvent(AdvisingEvent advisingEvent) {
> ```

can you please add comment where and how outcome will be used?

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45407)* status: 18 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`332-ci-manager/service/src/test/resources/recaster/alias/alias.txt` line 341 at r4](https://reviewable.io/reviews/harness/harness-core/45407#-NR7eqet0beENzeXu8Rr:-NRBUCjOAfsor52cgTSr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f5dd2060efa6aab62eba6b36e09d64b72ab81d6e/332-ci-manager/service/src/test/resources/recaster/alias/alias.txt#L341)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`400-rest/src/test/resources/manager-kryo-registrations.txt` line 2943 at r4](https://reviewable.io/reviews/harness/harness-core/45407#-NR7rmOy2oxUPECFseE7:-NRBUD5p8agVvlGWm1V5:b-orof6e) ([raw file](https://github.com/harness/harness-core/blob/f5dd2060efa6aab62eba6b36e09d64b72ab81d6e/400-rest/src/test/resources/manager-kryo-registrations.txt#L2943)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why its needed here?
</blockquote></details>

Needed for testKryoRegistrarForUnexpectedChanges

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45407)* status: 18 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/prb/OnFailPipelineRollbackAdviser.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/45407#-NR7UgYG8Y-dpbTUjkkS:-NRBUGv9--zmNW1t8g_l:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/586fda72a732b942597dd4dcdc61e9675538efac/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/prb/OnFailPipelineRollbackAdviser.java#L44)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

can you please add comment where and how outcome will be used?
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 14 files at r1, 4 of 12 files at r2, 1 of 1 files at r3, 17 of 18 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45407)* status: 18 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 17 of 18 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45407)* status: 1. unresolved discussions.

**Review by harshjain12 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 14 files at r1, 2 of 12 files at r2, 17 of 18 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45407#-:-NRC1f4uEuVA0Y6GpD_O:bnfp4nl)* status: 1. unresolved discussions.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 4 of 14 files at r1, 2 of 12 files at r2, 17 of 18 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45407)* status: :shipit: complete! ✓

**Review by harshjain12 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45407#-:-NRCEzz5AEsf2RIbN2a3:bnfp4nl)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]

**Pull request merged**
