### PR TITLE
feat: [SPG-190]: artifact index improvement

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37730)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37730)

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37730)* status: 2 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/test/resources/mongo/indexes.txt` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/37730#-NCcyoXy7I1C44GqYrBa:-NCcyoXz3XyAGZy7aRrr:b-5d7sel) ([raw file](https://github.com/harness/harness-core/blob/da4bfc68b46cfeaaee4f351a142221ab5c095f40/400-rest/src/test/resources/mongo/indexes.txt#L75)):*
> ```help
> artifacts {"name": "accountId_1", "background": true} {"accountId": 1}
> artifacts {"name": "accountId_artifactStreamId_createdAt", "background": true} {"accountId": 1, "artifactStreamId": 1, "createdAt": -1}
> artifacts {"name": "appId_artifactStreamId_metadata_image", "background": true} {"accountId": 1, "artifactStreamId": 1, "metadata.image": -1}
> ```

It should be "appId" : 1

**Review by abhinav-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37730)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/test/resources/mongo/indexes.txt` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/37730#-NCcyoXy7I1C44GqYrBa:-NCd7o-L7yRTyxQl-weI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/da4bfc68b46cfeaaee4f351a142221ab5c095f40/400-rest/src/test/resources/mongo/indexes.txt#L75)):*
<details><summary><i>Previously, Y0709 (Yuvraj Singhal) wrote…</i></summary><blockquote>

It should be "appId" : 1
</blockquote></details>

Done.

**Review by Y0709 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37730)* status: 1. unresolved discussions.

**Review by Y0709 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37730)* status: :shipit: complete! ✓

**Review by Y0709 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37730)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by Y0709 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37730)* status: :shipit: complete! ✓

**Review by abhinav-harness — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37730#-:-NCiIUBi6LuqbKlvfukt:bnfp4nl)* status: 0 of 1 approvals obtained.

**Review by Y0709 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37730)* status: :shipit: complete! ✓

**Review by Y0709 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37730)* status: :shipit: complete! ✓

**Review by sribalij — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37730#-:-ND3rjQX3HO5OitSQzoJ:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
