### PR TITLE
[feat]: [CDS-78705]: Code changes to implement the gitx webhook events added

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have added code to implement the gitx webhook events api. Have tested the api locally by passing different query params and its working as expected.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/EventsListGitXWebhookResponseDTO.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA6gpF3dhQ87FxkP-m:-NeA6gpGBraWvWYRg67_:b-p8l9) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/EventsListGitXWebhookResponseDTO.java#L27)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @OwnedBy(HarnessTeam.PIPELINE)
> public class EventsListGitXWebhookResponseDTO {
> ```

The class name is confusing

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventService.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA6wAvBGbE1azL9crP:-NeA6wAvBGbE1azL9crQ:btp5yrf) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventService.java#L22)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public interface GitXWebhookEventService {
>   void processEvent(WebhookDTO webhookDTO);
> ```

add line spacing

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventService.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA6zm36MBR_9bw3qQr:-NeA6zm36MBR_9bw3qQs:btww78l) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventService.java#L23)):*
> ```Java
> public interface GitXWebhookEventService {
>   void processEvent(WebhookDTO webhookDTO);
>   EventsListGitXWebhookResponseDTO listGitXWebhookEvents(
> ```

shouldn't it be "listEvents" simply? Already the service name clearly tells about gitx webhooks

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA78fxC6s7jQ_G70-z:-NeA78fxC6s7jQ_G700-:b-ysvrm8) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L83)):*
> ```Java
>     try (GitXWebhookLogContext context = new GitXWebhookLogContext(eventsListGitXWebhookRequestDTO)) {
>       try {
>         log.info(String.format(
> ```

need this log? Seems redundant.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA7CgeAxCu-K7T_xqR:-NeA7CgeAxCu-K7T_xqS:bovsp72) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L90)):*
> ```Java
>             .gitXEventDTOS(prepareGitXWebhookEvents(gitXWebhookEventList))
>             .build();
>       } catch (Exception exception) {
> ```

log exception

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA7JOUBEH-OU_84UZB:-NeA7JOUBEH-OU_84UZC:b-8dhapo) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L91)):*
> ```Java
>             .build();
>       } catch (Exception exception) {
>         throw new InternalServerErrorException(String.format(WEBHOOK_FAILURE_ERROR_MESSAGE, "listing events"));
> ```

"listing events" should also be a constant

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA7jDK8e2sr-rkF3eK:-NeA7jDK8e2sr-rkF3eL:b-kr1wrz) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L119)):*
> ```Java
>     }
>     if (eventsListGitXWebhookRequestDTO.getEventStartTime() != null
>         && eventsListGitXWebhookRequestDTO.getEventEndTime() != null) {
> ```

what if one of eventStartTime or eventEndTime is null? Why do we skip using the other one in that case?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)* status: 13 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/EventsListGitXWebhookResponseDTO.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA6gpF3dhQ87FxkP-m:-NeBocpX3ZptegG1jBnu:bqskacq) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/dtos/EventsListGitXWebhookResponseDTO.java#L27)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The class name is confusing
</blockquote></details>

renamed it
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventService.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA6wAvBGbE1azL9crP:-NeBokEwBPl0g7NrLNjG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventService.java#L22)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

add line spacing
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventService.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA6zm36MBR_9bw3qQr:-NeBokcP2nXtuSMXYKgI:b-5g9o7c) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventService.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

shouldn't it be "listEvents" simply? Already the service name clearly tells about gitx webhooks
</blockquote></details>

yes, done
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA78fxC6s7jQ_G70-z:-NeBooho5sYeWhj-OevS:b-vt936k) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L83)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

need this log? Seems redundant.
</blockquote></details>

in the entire list events flow, this is the only place where we are logging about the events call, better to have it
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA7CgeAxCu-K7T_xqR:-NeBpKWn9ABbvk9JnbXV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L90)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

log exception
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA7JOUBEH-OU_84UZB:-NeBp3gF-JOW_bYB88Xs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L91)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

"listing events" should also be a constant
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA7jDK8e2sr-rkF3eK:-NeBpLZrByuVEHAUB1_1:bb7k4sz) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L119)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if one of eventStartTime or eventEndTime is null? Why do we skip using the other one in that case?
</blockquote></details>

even i had the same question, 
as per the mocks and other existing components we always have to give both the fields, by default we are showing the events for last 7 days
say if we want to check all the webhooks after a date, in that case move only the start date and leave the end date as current date and vice versa

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)* status: 13 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA78fxC6s7jQ_G70-z:-NeC1CVU49YiTYecTW9A:b422st1) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L83)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

in the entire list events flow, this is the only place where we are logging about the events call, better to have it
</blockquote></details>

What purpose does it serve? We don't need redundant logging at all.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)* status: 13 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA7CgeAxCu-K7T_xqR:-NeC1Ki30AMCpp9-oDY2:b45erpo) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L90)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It should be : while listing "gitx" events, otherwise this same log line may coincide with something else and will create issues while debugging.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA7jDK8e2sr-rkF3eK:-NeC1Y7u87O2TN6ztaxl:b-3si02z) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L119)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

even i had the same question, 
as per the mocks and other existing components we always have to give both the fields, by default we are showing the events for last 7 days
say if we want to check all the webhooks after a date, in that case move only the start date and leave the end date as current date and vice versa
</blockquote></details>

We don't design our APIs as per mocks. Its confusing as an API user, that if I send one of the params, its not respecting it. Either throw invalid request exception in such cases that 1 param alone isn't supported or respect it and process it accordingly.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)* status: 13 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA78fxC6s7jQ_G70-z:-NeC2OoH58G-JJcayuPP:b-jcg4ha) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L83)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

What purpose does it serve? We don't need redundant logging at all.
</blockquote></details>

Removed it but i really feel its not redundant log, as this is the only log line which will tell us if the events listing has started or not
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA7CgeAxCu-K7T_xqR:-NeC2euN4nWiEIeIbR8d:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L90)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

It should be : while listing "gitx" events, otherwise this same log line may coincide with something else and will create issues while debugging.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA7jDK8e2sr-rkF3eK:-NeC4Olc3f60TKkv_VqK:b-qzt63m) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L119)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We don't design our APIs as per mocks. Its confusing as an API user, that if I send one of the params, its not respecting it. Either throw invalid request exception in such cases that 1 param alone isn't supported or respect it and process it accordingly.
</blockquote></details>

i agree we dont design as per mocks,
throwing an exception when either of them is missing and the other is present

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA78fxC6s7jQ_G70-z:-NeC4eiv2ijYwMiN-ooH:b-8560wj) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L83)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Removed it but i really feel its not redundant log, as this is the only log line which will tell us if the events listing has started or not
</blockquote></details>

Whole point is then every API should have this log to say an operation has started. What is that we get from this is the question. Why's there no other way to identify if something got started or not.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA7jDK8e2sr-rkF3eK:-NeC4yCM0YiDk5A6EYut:bknsg5f) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L119)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

i agree we dont design as per mocks,
throwing an exception when either of them is missing and the other is present
</blockquote></details>

This is in service impl internal method. This shouldn't care about any other logic than operating on whats presented to it. If any of the params is available, it should try and handle it in most generic way. So, here if we have startTime but no endTime, then endTime is assumed to be the end most time possible.
If you want to add any validation, then add it on first point where service impl starts. Ideally service should also not have any such constraint as there's no constraint from the system here. If you API has such limitation, then add validation on the API layer.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA7jDK8e2sr-rkF3eK:-NeC65AI71Sq-t1ceDzZ:b-1b3tq) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L119)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This is in service impl internal method. This shouldn't care about any other logic than operating on whats presented to it. If any of the params is available, it should try and handle it in most generic way. So, here if we have startTime but no endTime, then endTime is assumed to be the end most time possible.
If you want to add any validation, then add it on first point where service impl starts. Ideally service should also not have any such constraint as there's no constraint from the system here. If you API has such limitation, then add validation on the API layer.
</blockquote></details>

agreed, moved it to starting point

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> Dismissed @mohitg0795 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA7jDK8e2sr-rkF3eK:-NeC7XG4-wuhH1ZTrZ7D:b-tes84j) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L119)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

agreed, moved it to starting point
</blockquote></details>

Then remove checks from this class right.

**Comment by adivishy1** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/52792#-NeA7jDK8e2sr-rkF3eK:-NeC8dxeAiyBcQzw-kfU:b-lyl4sw) ([raw file](https://github.com/harness/harness-core/blob/0e5a9ddbc906e2b4ab8693a395f32c7433f808da/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L119)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Then remove checks from this class right.
</blockquote></details>

moved it to GitXWebhookMapper

**Comment by adivishy1** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52792)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Comment by adivishy1** [comment]
trigger ut2, ut4, ut6, ut7

**Pull request merged**
