### PR TITLE
feat: [PL-39275]: SEND METRICS TO SEGMENT NG changes

### PR DESCRIPTION
**Pull request by sahibaHarness**
## Describe your changes
Send metrics to segment[Amplitude]  to monitor accounts statistics. This has to be done to monitor stickiness of feature

We're transmitting metrics for the project count within a 24-hour period, along with the count of users during the same window. The job operates once every 24 hours and has incorporated a database to ensure it runs exclusively on a single pod.
Pasted Graphic 12

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54747)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54747)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/metrics/entities/AccountStatisticsTracker.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2_rYJ6tkmbRwB9RO6:-Ni2_rYJ6tkmbRwB9RO7:b7t8k38) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/metrics/entities/AccountStatisticsTracker.java#L34)):*
> ```Java
> @Document("AccountStatisticsTracker")
> @TypeAlias("AccountStatisticsTracker")
> public class AccountStatisticsTracker {
> ```

AccountStatisticsPublishTracker
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 1030 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2a8xmA08k4AVxGLXA:-Ni2a8xmA08k4AVxGLXB:boxfiu2) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L1030)):*
> ```Java
>         .scheduleWithFixedDelay(injector.getInstance(CDLicenseDailyReportTask.class), 0, 3, TimeUnit.HOURS);
>     injector.getInstance(Key.get(ScheduledExecutorService.class, Names.named("taskPollExecutor")))
>         .scheduleWithFixedDelay(injector.getInstance(AccountStatisticsForSegment.class), 0, 24, TimeUnit.HOURS);
> ```

SendAccountStatisticsToSegmentTask
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2cZJm7ngarJz1d_VF:-Ni2cZJm7ngarJz1d_VG:b-tipa7e) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L57)):*
> ```Java
>   public void publishMetrics() {
>     int pageIndex = 0;
>     int pageSize = 100;
> ```

Can we bump it up to 1000

Also, did we think of aggregating for all accounts in a single query? Any issues there?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2cAYE5NvtIhNFmJvp:-Ni2cAYE5NvtIhNFmJvq:bcu7gse) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L66)):*
> ```Java
> 
>     try (ResponseTimeRecorder ignore1 = new ResponseTimeRecorder(
>              "Audit metrics sent for unique project activity and unique logins for accounts startTime:" + startTime
> ```

Message seems to be copied from other PR. Its incorrect here
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2cJjr98a3exoEAjWY:-Ni2cJjr98a3exoEAjWZ:banvgvf) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L71)):*
> ```Java
>         List<String> accountIds = new ArrayList<>();
>         PageResponse<AccountDTO> pageResponse =
>             CGRestUtils.getResponse(accountClient.listAccounts(pageIndex, pageSize));
> ```

Should we filter out publishing metrics for accounts for whom NG is not enabled?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2bSH2ABwGm4g3MkpV:-Ni2bSH2ABwGm4g3MkpW:b-99pj3d) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L94)):*
> ```Java
>   Query getQueryForLastEntry() {
>     return new Query(
>         Criteria.where(AccountStatisticsTrackerKeys.lastPublishTime).gte(Instant.now().minus(24, ChronoUnit.HOURS)));
> ```

This isn't query for last entry as method name is suggesting.

This is query if we we published metrics less than 24 hours ago.

Lets change method name accordingly for readability
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2crNV4G8yi0234Nfs:-Ni2crNV4G8yi0234Nft:b-1ipcim) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L97)):*
> ```Java
>   }
> 
>   private void sendAuditEventMetricsToSegment(String accountIdentifier, int projectCount, int usersCount) {
> ```

This method name is incorrect
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 106 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2bLbWC_9iiRbmU6bX:-Ni2bLbWC_9iiRbmU6bY:b-gyxz7a) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L106)):*
> ```Java
>     HashMap<String, Object> properties = new HashMap<>();
>     properties.put("projectCount", projectCount);
>     properties.put("usersCount", usersCount);
> ```

Lets be consistent : userCount
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2bOXF9q1ktw2GUMwm:-Ni2bOXF9q1ktw2GUMwn:b-rbzdj6) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L108)):*
> ```Java
>     properties.put("usersCount", usersCount);
> 
>     telemetryReporter.sendTrackEvent("account_statistic_metrics",
> ```

account_statistics_metrics
___
*[`123-ng-core-user/src/main/java/io/harness/repositories/user/custom/UserMembershipRepositoryCustomImpl.java` line 153 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2ahulEunlETf7SXRU:-Ni2ahulEunlETf7SXRV:b-1944zk) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/123-ng-core-user/src/main/java/io/harness/repositories/user/custom/UserMembershipRepositoryCustomImpl.java#L153)):*
> ```Java
>   }
> 
>   public <T> AggregationResults<T> aggregate(Aggregation aggregation, Class<T> classToFillResultIn) {
> ```

Why is this method public?

**Review by sahibaHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54747)* status: 9 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/metrics/entities/AccountStatisticsTracker.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2_rYJ6tkmbRwB9RO6:-Ni38bcg-IORtHYrG-W-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/metrics/entities/AccountStatisticsTracker.java#L34)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

AccountStatisticsPublishTracker
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 1030 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2a8xmA08k4AVxGLXA:-Ni38asBCKRGE8vV9HcE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L1030)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

SendAccountStatisticsToSegmentTask
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/repositories/user/custom/UserMembershipRepositoryCustomImpl.java` line 153 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2ahulEunlETf7SXRU:-Ni364oYAOwChbByQcHc:bmq1yok) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/123-ng-core-user/src/main/java/io/harness/repositories/user/custom/UserMembershipRepositoryCustomImpl.java#L153)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why is this method public?
</blockquote></details>

made it private
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2cZJm7ngarJz1d_VF:-Ni37gtEDxgTTHdH8fqu:bv2oxgh) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L57)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we bump it up to 1000

Also, did we think of aggregating for all accounts in a single query? Any issues there?
</blockquote></details>

Bumping up to a 1000 as projects and users collection shouldn't cause problem on being called with this limit.
I recall  we where planing on having limits on all calls, I think we should be good with the batch size being 1000
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2cAYE5NvtIhNFmJvp:-Ni37e3VDV0rC4FqWIxX:bg4eos8) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L66)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Message seems to be copied from other PR. Its incorrect here
</blockquote></details>

corrected the text
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2cJjr98a3exoEAjWY:-Ni36QWX3212H4qEnWUf:b-4isd80) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L71)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we filter out publishing metrics for accounts for whom NG is not enabled?
</blockquote></details>

As we are migrating users from CG to NG soon all accounts will be NG. And if we publish for CG only accounts the metrics count will be 0, it can help Identify accounts that are still CG only.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2bSH2ABwGm4g3MkpV:-Ni36Fva6eqjp3L4yaED:b-jwcvii) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L94)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This isn't query for last entry as method name is suggesting.

This is query if we we published metrics less than 24 hours ago.

Lets change method name accordingly for readability
</blockquote></details>

changed it to getQueryForEntryInLast24Hours
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2crNV4G8yi0234Nfs:-Ni36AXA9jIs9tvThD-3:b4qa8u2) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L97)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This method name is incorrect
</blockquote></details>

changed it to sendAccountStatisticsMetricsEventToSegment
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 106 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2bLbWC_9iiRbmU6bX:-Ni3697117JCXoU-OfkQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L106)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Lets be consistent : userCount
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2bOXF9q1ktw2GUMwm:-Ni369NxDMH_s6Ji4kTM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L108)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

account_statistics_metrics
</blockquote></details>

Done.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54747)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2cJjr98a3exoEAjWY:-Ni4NvLR-swX_GT-Ir_n:bqqsrnm) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L71)):*
<details><summary><i>Previously, sahibaHarness (Sahiba Khan) wrote…</i></summary><blockquote>

As we are migrating users from CG to NG soon all accounts will be NG. And if we publish for CG only accounts the metrics count will be 0, it can help Identify accounts that are still CG only.
</blockquote></details>

How would we distinguish between the case where an account is not NG enabled vs an account doesn't have any project

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54747#-:-Ni4U_Rr7PCl9k2BKOfo:bnfp4nl)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahibaHarness** [comment]
trigger uts

**Review by sahibaHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54747)* status: 9 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2cJjr98a3exoEAjWY:-Ni4lYQj9KCfjhE9yhTz:brgvz1v) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L71)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

How would we distinguish between the case where an account is not NG enabled vs an account doesn't have any project
</blockquote></details>

based of current information we cant, should we filter for NG accounts then?

**Comment by sahibaHarness** [comment]
trigger ut9

**Comment by sahibaHarness** [comment]
trigger ut9

**Comment by sahibaHarness** [comment]
trigger uts

**Comment by sahibaHarness** [comment]
trigger ut5

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54747)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/SendAccountStatisticsToSegmentTask.java` line 47 at r5](https://reviewable.io/reviews/harness/harness-core/54747#-NiEFiTX7VzDMyZF8IG7:-NiEFiTX7VzDMyZF8IG8:b-58y3ns) ([raw file](https://github.com/harness/harness-core/blob/7f2ae957af8b225de05ac086b58f7a937d9bf3c4/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/SendAccountStatisticsToSegmentTask.java#L47)):*
> ```Java
>   public void run() {
>     if (shouldPublishMetrics()) {
>       publishMetrics();
> ```

lets add a try catch here, this job would run once in 24 hours, os if it fails we should log proper exception

**Review by sahibaHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54747)* status: 10 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/SendAccountStatisticsToSegmentTask.java` line 47 at r5](https://reviewable.io/reviews/harness/harness-core/54747#-NiEFiTX7VzDMyZF8IG7:-NiEI8Ky-sNr-RDRWh3S:bvsw2pn) ([raw file](https://github.com/harness/harness-core/blob/7f2ae957af8b225de05ac086b58f7a937d9bf3c4/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/SendAccountStatisticsToSegmentTask.java#L47)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

lets add a try catch here, this job would run once in 24 hours, os if it fails we should log proper exception
</blockquote></details>

If a job fails to run on one pod it will be pick by other pod to get completed. We can track executions with ResponseTimeRecorder ; more over we dont want data to be strictly consistent.

**Comment by sahibaHarness** [comment]
trigger uts

**Review by kapil-harness — DISMISSED** [review]
> Reviewed 3 of 9 files at r1, 2 of 3 files at r3, 2 of 5 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54747)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54747)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/54747#-Ni2cJjr98a3exoEAjWY:-NiETuPw3vk7aNMvuVnC:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/aaaa54c924ade08531e7db99d619561623d2e871/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/AccountStatisticsForSegment.java#L71)):*
<details><summary><i>Previously, sahibaHarness (Sahiba Khan) wrote…</i></summary><blockquote>

based of current information we cant, should we filter for NG accounts then?
</blockquote></details>

yes

**Comment by sahibaHarness** [comment]
trigger uts

**Comment by sahibaHarness** [comment]
trigger uts

**Comment by sahibaHarness** [comment]
trigger ut8,ut9

**Comment by sahibaHarness** [comment]
trigger ut8,ut9

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54747#-:-NiI2ApYDGeBdafPmYLr:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
