### PR TITLE
fix: [GTM-1133]: check module license activate from all resources

### PR DESCRIPTION
**Pull request by Xin-Harness**
## Add a field in account collection to mark the account is actively used cross environment
Test is done locally https://harness.atlassian.net/wiki/spaces/~487660713/pages/21107900536/Local+test+for+introduce+accountActivelyUsed+field+in+account+table
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34329)

### CODE REVIEW

**Review by pranil-harness — APPROVED** [review]

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/workers/background/CrossEnvironmentAccountLevelEntityProcessController.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/34329#-N4hRsUnAuKg4hkTYrDW:-N4hRsUnAuKg4hkTYrDX:b-dj14n3) ([raw file](https://github.com/harness/harness-core/blob/289179add95d11e7df51d8b78e165f665b0c6030/400-rest/src/main/java/io/harness/workers/background/CrossEnvironmentAccountLevelEntityProcessController.java#L26)):*
> ```Java
>  * The account level check cross cg and ng environment
>  */
> public class CrossEnvironmentAccountLevelEntityProcessController implements EntityProcessController<Account> {
> ```

why do we need two of these?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 5 of 8 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34329)* status: 0 of 1 approvals obtained.

**Comment by Xin-Harness** [comment]
https://harness.atlassian.net/wiki/spaces/~487660713/pages/21107900536/Local+test+for+introduce+accountActivelyUsed+field+in+account+table

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/workers/background/CrossEnvironmentAccountLevelEntityProcessController.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/34329#-N4hRsUnAuKg4hkTYrDW:-N4i0RwI6AoSQhbImOFO:b-vch9ey) ([raw file](https://github.com/harness/harness-core/blob/289179add95d11e7df51d8b78e165f665b0c6030/400-rest/src/main/java/io/harness/workers/background/CrossEnvironmentAccountLevelEntityProcessController.java#L26)):*
> AccountLevelEntityProcessController
check the code for AccountLevelEntityProcessController and AccountStatusBasedEntityProcessController

they are exactly the same code except in one we pass the account and in another we pass the entity. We don't need both since we are moving away from account based iterators. we just need the replacement for AccountStatusBasedEntityProcessController

**Comment by Xin-Harness** [comment]
trigger ti0

**Review by Xin-Harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34329)* status: 1 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/workers/background/CrossEnvironmentAccountStatusBasedEntityProcessController.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/34329#-N4dYaRZcEg0cGwGJomY-r2-23:-N4mJ7e36zhUoob9flas:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/706d8161027ccfeaee11cdd226d84b812285f7d1/400-rest/src/main/java/io/harness/workers/background/CrossEnvironmentAccountStatusBasedEntityProcessController.java#L23)):*
<details><summary><i>Previously, pranil-harness (Pranil Dasika) wrote…</i></summary><blockquote>

Please add more documentation here - when should this be used versus when to use the other existing class
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java` line 627 at r2](https://reviewable.io/reviews/harness/harness-core/34329#-N4ZGvXQaD3Wp69O_J98-r2-627:-N4mJ8xA41sKcRURMb-h:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/706d8161027ccfeaee11cdd226d84b812285f7d1/400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java#L627)):*
<details><summary><i>Previously, pranil-harness (Pranil Dasika) wrote…</i></summary><blockquote>

Please add documentation here
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/io/harness/workers/background/CrossEnvironmentAccountLevelEntityProcessController.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/34329#-N4hRsUnAuKg4hkTYrDW:-N4mJAZ--XPFJiKUsjq0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/289179add95d11e7df51d8b78e165f665b0c6030/400-rest/src/main/java/io/harness/workers/background/CrossEnvironmentAccountLevelEntityProcessController.java#L26)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

> AccountLevelEntityProcessController
check the code for AccountLevelEntityProcessController and AccountStatusBasedEntityProcessController

they are exactly the same code except in one we pass the account and in another we pass the entity. We don't need both since we are moving away from account based iterators. we just need the replacement for AccountStatusBasedEntityProcessController
</blockquote></details>

Done.

**Pull request merged**
