### PR TITLE
[feat]: [PL-27428]: Adds implementation for role assignment resource using spec first approach

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38599)

### CODE REVIEW

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38599)* status: 25 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/AccountRoleAssignmentsApiImpl.java` line 128 at r5](https://reviewable.io/reviews/harness/harness-core/38599#-NEGN0rv9WHED1ZhaIH4:-NEGN0rv9WHED1ZhaIH5:b-yiijrp) ([raw file](https://github.com/harness/harness-core/blob/20b360ef36c1c192caf0c0a2f8947949f9654fdd/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/AccountRoleAssignmentsApiImpl.java#L128)):*
> ```Java
>     io.harness.accesscontrol.roleassignments.RoleAssignment roleAssignment =
>         roleAssignmentService.get(roleassignment, scopeIdentifier).<InvalidRequestException>orElseThrow(() -> {
>           throw new InvalidRequestException("Invalid Role Assignment");
> ```

Lets throw consistent exception as below. NotFoundException instead of InvalidRequestException.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/AccountRoleAssignmentsApiImpl.java` line 157 at r5](https://reviewable.io/reviews/harness/harness-core/38599#-NEGNUCe-6nfRoJjkWmF:-NEGNUCe-6nfRoJjkWmG:b-vjlfn5) ([raw file](https://github.com/harness/harness-core/blob/20b360ef36c1c192caf0c0a2f8947949f9654fdd/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/AccountRoleAssignmentsApiImpl.java#L157)):*
> ```Java
>     io.harness.accesscontrol.roleassignments.RoleAssignment roleAssignment =
>         roleAssignmentService.get(roleassignment, scope.toString()).<NotFoundException>orElseThrow(() -> {
>           throw new NotFoundException("Role Assignment with given identifier doesn't exists");
> ```

make this message as constant which can reused.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/OrgRoleAssignmentsApiImpl.java` line 131 at r5](https://reviewable.io/reviews/harness/harness-core/38599#-NEMITY_8BAGJfOhTpIs:-NEMITY_8BAGJfOhTpIt:b-uk9i8z) ([raw file](https://github.com/harness/harness-core/blob/20b360ef36c1c192caf0c0a2f8947949f9654fdd/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/OrgRoleAssignmentsApiImpl.java#L131)):*
> ```Java
>     io.harness.accesscontrol.roleassignments.RoleAssignment roleAssignment =
>         roleAssignmentService.get(roleassignment, scopeIdentifier).<InvalidRequestException>orElseThrow(() -> {
>           throw new InvalidRequestException("Invalid Role Assignment");
> ```

NotFoundException instead of InvalidRequestException.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/ProjectRoleAssignmentsApiImpl.java` line 137 at r5](https://reviewable.io/reviews/harness/harness-core/38599#-NEMZPMmAiXZzPWhAso8:-NEMZPMmAiXZzPWhAso9:b-uk9i8z) ([raw file](https://github.com/harness/harness-core/blob/20b360ef36c1c192caf0c0a2f8947949f9654fdd/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/ProjectRoleAssignmentsApiImpl.java#L137)):*
> ```Java
>     io.harness.accesscontrol.roleassignments.RoleAssignment roleAssignment =
>         roleAssignmentService.get(roleassignment, scopeIdentifier).<InvalidRequestException>orElseThrow(() -> {
>           throw new InvalidRequestException("Invalid Role Assignment");
> ```

NotFoundException instead of InvalidRequestException.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java` line 267 at r5](https://reviewable.io/reviews/harness/harness-core/38599#-NEMW2q80SqA-kiUhguw:-NEMW2q93CJfbciwlDPL:b-lm7cl7) ([raw file](https://github.com/harness/harness-core/blob/20b360ef36c1c192caf0c0a2f8947949f9654fdd/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java#L267)):*
> ```Java
> 
>   public void checkUpdatePermission(
>       HarnessScopeParams harnessScopeParams, io.harness.accesscontrol.roleassignments.RoleAssignment roleAssignment) {
> ```

I see this is common code in this utils class. I understand separation of concerns and having different class.
Can we have existing APIs use it as well to avoid maintenance overhead otherwise we will have to track every fix in that code would need to be done in newer APIs until we transition and discard old APIs.

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/AccountRoleAssignmentsApiImpl.java` line 128 at r5](https://reviewable.io/reviews/harness/harness-core/38599#-NEGN0rv9WHED1ZhaIH4:-NEQ1iVI-YENtX9CP862:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/20b360ef36c1c192caf0c0a2f8947949f9654fdd/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/AccountRoleAssignmentsApiImpl.java#L128)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Lets throw consistent exception as below. NotFoundException instead of InvalidRequestException.
</blockquote></details>

Fixed

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/AccountRoleAssignmentsApiImpl.java` line 157 at r5](https://reviewable.io/reviews/harness/harness-core/38599#-NEGNUCe-6nfRoJjkWmF:-NEQ1lm52aRoJf3C4Utj:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/20b360ef36c1c192caf0c0a2f8947949f9654fdd/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/AccountRoleAssignmentsApiImpl.java#L157)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

make this message as constant which can reused.
</blockquote></details>

Fixed

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/OrgRoleAssignmentsApiImpl.java` line 131 at r5](https://reviewable.io/reviews/harness/harness-core/38599#-NEMITY_8BAGJfOhTpIs:-NEQ1nyl1SG6s3_0zAqU:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/20b360ef36c1c192caf0c0a2f8947949f9654fdd/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/OrgRoleAssignmentsApiImpl.java#L131)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

NotFoundException instead of InvalidRequestException.
</blockquote></details>

Fixed

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/ProjectRoleAssignmentsApiImpl.java` line 137 at r5](https://reviewable.io/reviews/harness/harness-core/38599#-NEMZPMmAiXZzPWhAso8:-NEQ1pjS5sPzA19KzlB-:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/20b360ef36c1c192caf0c0a2f8947949f9654fdd/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/ProjectRoleAssignmentsApiImpl.java#L137)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

NotFoundException instead of InvalidRequestException.
</blockquote></details>

Fixed

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java` line 267 at r5](https://reviewable.io/reviews/harness/harness-core/38599#-NEMW2q80SqA-kiUhguw:-NEQ1rfJA6oD7chp1fer:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/20b360ef36c1c192caf0c0a2f8947949f9654fdd/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java#L267)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

I see this is common code in this utils class. I understand separation of concerns and having different class.
Can we have existing APIs use it as well to avoid maintenance overhead otherwise we will have to track every fix in that code would need to be done in newer APIs until we transition and discard old APIs. 
</blockquote></details>

Fixed

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 25 files at r4, 10 of 18 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38599#-:-NEX1FOy2cbpbJW0bzpQ:bnfp4nl)* status: 27 file(s) to review. 1 of 2 approvals obtained.

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 7 of 25 files at r4, 11 of 18 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38599)* status: :shipit: complete! ✓

**Pull request merged**
