### PR TITLE
[fix]:[pl-28774]: Hide remote templates for gitSync project

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Hide remote templates for gitSync project. Have tested out showing up of remote templates at all scopes for 

USE_OLD_GIT_SYNC = TRUE:

1) INLINE project -- No 
	 NG_TEMPLATE_GITX = true - working
	 NG_TEMPLATE_GITX = false - working

2) Git Sync project -- No 
	 NG_TEMPLATE_GITX = true - working
	 NG_TEMPLATE_GITX = false - working

3) GitX project -- Yes (if NG Template FF is ON)
	 NG_TEMPLATE_GITX = true - working
	 NG_TEMPLATE_GITX = false - working

4) on org level -- Yes (if NG Template FF is ON)
	 NG_TEMPLATE_GITX = true - working
	 NG_TEMPLATE_GITX = false - working

5) on acc level -- Yes (if NG Template FF is ON)
	 NG_TEMPLATE_GITX = true - working
	 NG_TEMPLATE_GITX = false - working

---------------------------------------------------------------------------------
USE_OLD_GITS_SYNC = FALSE

1) GitX Project (all projects that are new are gitX enabled) 
	 NG_TEMPLATE_GITX = true - working
	 NG_TEMPLATE_GITX = false - working

2) Old git sync project -- NO 
	 NG_TEMPLATE_GITX = true - working
	 NG_TEMPLATE_GITX = false - wokring

3) org level -- Yes (if NG Template FF is ON)
	 NG_TEMPLATE_GITX = true - working
	 NG_TEMPLATE_GITX = false - working

4) acc level -- Yes (if NG Template FF is ON)
	 NG_TEMPLATE_GITX = true - working
	 NG_TEMPLATE_GITX = false - working

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38453)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38453)

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/38453#-NDis9gtEIeMrVdb8am7:-NDis9gtEIeMrVdb8am8:b-cwnbax) ([raw file](https://github.com/harness/harness-core/blob/2489d4711b434f332daea34bcbf93277c65bac1d/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L116)):*
> ```Java
>     if (ngTemplateFeatureFlagHelperService.isEnabled(accountIdentifier, FeatureName.USE_OLD_GIT_SYNC)) {
>       // when we have new gitx project in oldGitSync account created
>       return !ngTemplateFeatureFlagHelperService.isEnabled(accountIdentifier, FeatureName.NG_TEMPLATE_GITX);
> ```

this condition is wrong. When Old git sync is TRUE, then default projects aren't all new gitX projects. They are INLINE projects.

So condition should check basically, if OLD GIT SYNC is TRUE, then isNewGitXEnabled() then we show, otherwise not.

**Comment by adivishy1** [comment]
> _[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/38453#-NDis9gtEIeMrVdb8am7:-NDis9gtEIeMrVdb8am8:b-cwnbax) ([raw file](https://github.com/harness/harness-core/blob/2489d4711b434f332daea34bcbf93277c65bac1d/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L116)):_
> 
> > ```java
> >     if (ngTemplateFeatureFlagHelperService.isEnabled(accountIdentifier, FeatureName.USE_OLD_GIT_SYNC)) {
> >       // when we have new gitx project in oldGitSync account created
> >       return !ngTemplateFeatureFlagHelperService.isEnabled(accountIdentifier, FeatureName.NG_TEMPLATE_GITX);
> > ```
> 
> this condition is wrong. When Old git sync is TRUE, then default projects aren't all new gitX projects. They are INLINE projects.
> 
> So condition should check basically, if OLD GIT SYNC is TRUE, then isNewGitXEnabled() then we show, otherwise not.

yes, what you have mentioned is the same implemented here, when isNewGitXEnabled is true, we this method would retrun false, which means that we wont be adding the criteria for hiding the remote templates.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 7 of 9 files at r4, 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38453)* status: :shipit: complete! ✓

**Pull request merged**
