### PR TITLE
feat: [CDS-39170]: skeletal framework for createInstances API

### PR DESCRIPTION
**Pull request by achyuth-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34656)

### CODE REVIEW

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34656)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K8gs_3pEnw8MMH6dX:-N5K8gs_3pEnw8MMH6dY:b-20wvfn) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L44)):*
> ```Java
>   private final InstanceService instanceService;
>   @POST
>   @Path("/create")
> ```

We do not need a PATH for this API. This can be the default POST API under ```@Path("gitOpsInstanceSync")```
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K6pZY7RvmfHP6KCpn:-N5K6pZY7RvmfHP6KCpo:b-bc0jn7) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L46)):*
> ```Java
>   @Path("/create")
>   @ApiOperation(value = "Create instances and save in DB", nickname = "createGitOpsInstances")
>   public ResponseDTO<Boolean> createGitOpsInstances(
> ```

Lets return an object which can consist of 
- boolean : indicating status of request
- List<T> where T can be a DTO encapsulating information of created instances.  Information like uuid, service, env ids etc
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K7JsQ54IUsX85bQLQ:-N5K7JsQ54IUsX85bQLR:bjdji1c) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L47)):*
> ```Java
>   @ApiOperation(value = "Create instances and save in DB", nickname = "createGitOpsInstances")
>   public ResponseDTO<Boolean> createGitOpsInstances(
>       @NotNull List<GitOpsInstanceRequestDTO> gitOpsInstanceRequestDTOList, String accountId) {
> ```

1. Move accountId to 1st Param & add 
```@QueryParam(NGCommonEntityConstants.ACCOUNT_KEY) String accountId```
2. Also add. @NotNull/@NotEmpty to accountId
3. Add @Valid annotation from javax, to the List<..> parameter
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K8YRL7lIIfq3_EFMW:-N5K8YRL7lIIfq3_EFMX:b-vlarzz) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L50)):*
> ```Java
>     instanceService.saveAll(GitOpsRequestDTOMapper.instanceDTOList(gitOpsInstanceRequestDTOList, accountId));
>     return ResponseDTO.newResponse(Boolean.TRUE);
>   }
> ```

Lets also add DELETE method
___
*[`126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java` line 9 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K7rq0-Lp0pbr5YE6A:-N5K7rq0-Lp0pbr5YE6B:bb2rw33) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java#L9)):*
> ```Java
> import lombok.Builder;
> import lombok.Getter;
> import lombok.Setter;
> ```

nit: empty line here
___
*[`126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java` line 12 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K7u6R8g26Jo1knsiF:-N5K7u6R8g26Jo1knsiG:bozrxnz) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java#L12)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> @Getter
> @Setter
> ```

can we use @Value or @data from lombok ?
___
*[`126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K82ME86pVEA_bDdrK:-N5K82ME86pVEA_bDdrL:bkj7vp7) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java#L23)):*
> ```Java
>   private String lastDeployedByName;
>   private long lastDeployedAt;
>   private InstanceInfo instanceInfo; // private K8sBasicInfo instanceInfo
> ```

Lets add javax NotEmpty/NotNull annotations here
___
*[`126-instance/src/main/java/io/harness/entities/instanceinfo/K8sBasicInfo.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K8H8Q6MdtkbA5T4Tn:-N5K8H8Q6MdtkbA5T4To:b-sied0a) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/126-instance/src/main/java/io/harness/entities/instanceinfo/K8sBasicInfo.java#L21)):*
> ```Java
>   @NotNull private String podName;
>   private String podIP;
>   @NotNull private List<K8sContainer> containerList;
> ```

List<K8sContainer> containerList. This can be null for now. We are not sure if gitops has this information as of now

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34656)* status: 6 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K8gs_3pEnw8MMH6dX:-N5KC-4a32yyaPFCbfPK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L44)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We do not need a PATH for this API. This can be the default POST API under ```@Path("gitOpsInstanceSync")```
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K7JsQ54IUsX85bQLQ:-N5KCQcB7P7q6zXHM850:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L47)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

1. Move accountId to 1st Param & add 
```@QueryParam(NGCommonEntityConstants.ACCOUNT_KEY) String accountId```
2. Also add. @NotNull/@NotEmpty to accountId
3. Add @Valid annotation from javax, to the List<..> parameter
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K8YRL7lIIfq3_EFMW:-N5KJRRg0tL7_DRL60ae:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L50)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets also add DELETE method
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java` line 12 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K7u6R8g26Jo1knsiF:-N5KCo1m0DyNtGlRgpbG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java#L12)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we use @Value or @data from lombok ?
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K82ME86pVEA_bDdrK:-N5KD450-OWnGEwKxAwh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java#L23)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets add javax NotEmpty/NotNull annotations here
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/entities/instanceinfo/K8sBasicInfo.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K8H8Q6MdtkbA5T4Tn:-N5KDAV-8XJhndfLv8-d:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/126-instance/src/main/java/io/harness/entities/instanceinfo/K8sBasicInfo.java#L21)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

List<K8sContainer> containerList. This can be null for now. We are not sure if gitops has this information as of now
</blockquote></details>

Done.

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34656)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K6pZY7RvmfHP6KCpn:-N5KUqLq85geXYT2ds63:b-5gp2ma) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L46)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets return an object which can consist of 
- boolean : indicating status of request
- List<T> where T can be a DTO encapsulating information of created instances.  Information like uuid, service, env ids etc
</blockquote></details>

No, lets not use Pair. We can just return ```ResponseDTO<PageResponse<InstanceDTO>> ```
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K7JsQ54IUsX85bQLQ:-N5KV-tM7n6Qer_uhNPF:baglhas) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L47)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

2 is pending
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K8YRL7lIIfq3_EFMW:-N5KV5Lz0pcjP3H22PHz:bkaebp9) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L50)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Lets create a wrapper object here also so that it is easy to add more data in future
```
DeleteInstancesDTO {
   bool status;
   int deletedCount;
}
```

**Review by henry-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34656)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/34656#-N5Mlm5I8TVyCNrrODTR:-N5Mlm5I8TVyCNrrODTS:b8eavc2) ([raw file](https://github.com/harness/harness-core/blob/5c6eb305d3fb8b003f834d51f81ac9ed1fd5c889/126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java#L21)):*
> ```Java
>   @NotEmpty private String serviceIdentifier;
>   @NotEmpty private String instanceKey;
>   @NotEmpty private String lastDeployedById;
> ```

I believe this (and lastDeployedByName) is the in user that last deployed the pipeline. I don't think we'll have this info when we publish the instance information from gitops. If this is true, then this should allow empty value (null or empty string). Correct me if i'm wrong @gabeaboy @anshul-harness @rohitk-h 
___
*[`126-instance/src/main/java/io/harness/entities/instanceinfo/K8sBasicInfo.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/34656#-N5MmRzs4WH74QqXWR0a:-N5MmRzs4WH74QqXWR0b:bpdf0of) ([raw file](https://github.com/harness/harness-core/blob/5c6eb305d3fb8b003f834d51f81ac9ed1fd5c889/126-instance/src/main/java/io/harness/entities/instanceinfo/K8sBasicInfo.java#L17)):*
> ```Java
> @Builder
> @EqualsAndHashCode(callSuper = true)
> public class K8sBasicInfo extends InstanceInfo {
> ```

@anshul-harness @rohitk-h @gabeaboy -- do we use this class to define the pod info or do we create a new one (like `GitopsBasicInfo extends InstanceInfo`) ?
___
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/34656#-N5MnO5B0-YFwW1jFgHw:-N5MnO5B0-YFwW1jFgHx:by98wnw) ([raw file](https://github.com/harness/harness-core/blob/5c6eb305d3fb8b003f834d51f81ac9ed1fd5c889/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L29)):*
> ```Java
>     String envId = gitOpsInstanceRequestDTO.getEnvIdentifier();
> 
>     Optional<Environment> environment = environmentService.get(accountId, orgId, projId, envId, false);
> ```

I think you can do
```
Environment environment = environmentService.get(accountId, orgId, projId, envId, false)
    .orElseGet(() -> Environment.builder().build());
```
___
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/34656#-N5Mns3z0XZByx3cOpG_:-N5Mns3z0XZByx3cOpGa:b-95fdi0) ([raw file](https://github.com/harness/harness-core/blob/5c6eb305d3fb8b003f834d51f81ac9ed1fd5c889/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L36)):*
> ```Java
>     }
> 
>     return InstanceDTO.builder()
> ```

curious - do we not use orika mappers?

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34656)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K6pZY7RvmfHP6KCpn:-N5YYZPKEdYx59mZ71kd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L46)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

No, lets not use Pair. We can just return ```ResponseDTO<PageResponse<InstanceDTO>> ```
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K7JsQ54IUsX85bQLQ:-N5YXmccCzjAK5K759s_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L47)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

2 is pending
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/34656#-N5K8YRL7lIIfq3_EFMW:-N5YaaXvBE962YoO4HqY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/89b7be9e70b416987d63f33245155a74f53f554c/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L50)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets create a wrapper object here also so that it is easy to add more data in future
```
DeleteInstancesDTO {
   bool status;
   int deletedCount;
}
```
</blockquote></details>

Done.

**Comment by GabeAboy** [comment]
*[`126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/34656#-N5Mlm5I8TVyCNrrODTR:-N5_lZerEltXjh-84Dzy:b-devw83) ([raw file](https://github.com/harness/harness-core/blob/5c6eb305d3fb8b003f834d51f81ac9ed1fd5c889/126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java#L21)):*
> he in user that last deployed the
@henry-harness Correct this is a deployment by the pipeline executor. We should populate this field by getting the pipeline information before we write instances

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34656)* status: 2 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 3 files at r3, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34656)* status: 4. unresolved discussions.

**Review by henry-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34656)* status: 4. unresolved discussions. 

___
*[`126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/34656#-N5Mlm5I8TVyCNrrODTR:-N5_ynFuCQfA5atp8cQR:blnc8ds) ([raw file](https://github.com/harness/harness-core/blob/5c6eb305d3fb8b003f834d51f81ac9ed1fd5c889/126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java#L21)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

> he in user that last deployed the
@henry-harness Correct this is a deployment by the pipeline executor. We should populate this field by getting the pipeline information before we write instances
</blockquote></details>

If we populate the pipeline executor first, then i'm assuming the other information is available except for instance info? if that is true, then can `InstanceInfo` is still non null. Are the fields in `InstanceInfo` be nullable or empty?
___
*[`126-instance/src/main/java/io/harness/entities/instanceinfo/K8sBasicInfo.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/34656#-N5MmRzs4WH74QqXWR0a:-N5_zgZ0-1XcI2iYnot9:b-s40a6) ([raw file](https://github.com/harness/harness-core/blob/5c6eb305d3fb8b003f834d51f81ac9ed1fd5c889/126-instance/src/main/java/io/harness/entities/instanceinfo/K8sBasicInfo.java#L17)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

We should use this class, we have everything here expect for podIP. Right?
</blockquote></details>

Yes, we don't have podIP info. I also don't know what `K8sContainer` object looks like, so its possible we may be missing info in there too.

**Comment by anshul-harness** [comment]
*[`126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/34656#-N5Mlm5I8TVyCNrrODTR:-N5aV91v7R-bjndNKtoI:b-z7uwzr) ([raw file](https://github.com/harness/harness-core/blob/5c6eb305d3fb8b003f834d51f81ac9ed1fd5c889/126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java#L21)):*
<details><summary><i>Previously, henry-harness (henry leong) wrote…</i></summary><blockquote>

If we populate the pipeline executor first, then i'm assuming the other information is available except for instance info? if that is true, then can `InstanceInfo` is still non null. Are the fields in `InstanceInfo` be nullable or empty?
</blockquote></details>

@henry-harness:  Yes, we will not have the lastDeployedByName from the GitOpsService.

**Comment by anshul-harness** [comment]
*[`126-instance/src/main/java/io/harness/entities/instanceinfo/K8sBasicInfo.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/34656#-N5MmRzs4WH74QqXWR0a:-N5aWAOj6Sk6BDUgfBE8:b-92n3fi) ([raw file](https://github.com/harness/harness-core/blob/5c6eb305d3fb8b003f834d51f81ac9ed1fd5c889/126-instance/src/main/java/io/harness/entities/instanceinfo/K8sBasicInfo.java#L17)):*
<details><summary><i>Previously, henry-harness (henry leong) wrote…</i></summary><blockquote>

Yes, we don't have podIP info. I also don't know what `K8sContainer` object looks like, so its possible we may be missing info in there too.
</blockquote></details>

@henry-harness: This is the K8sContainer object
https://github.com/harness/harness-core/blob/develop/970-api-services-beans/src/main/java/io/harness/k8s/model/K8sContainer.java



_Code quote:_
```Java
K8sContainer
```

**Review by GabeAboy — COMMENTED** [review]
> Reviewed 3 of 6 files at r2, 1 of 3 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34656)* status: 1. unresolved discussions.

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34656)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 52 at r5](https://reviewable.io/reviews/harness/harness-core/34656#-N63a0HcDEJjs5naBF_d:-N63a0HdAjJCKlTpBp40:b-b0plu) ([raw file](https://github.com/harness/harness-core/blob/6b4241a463b9e1bcc84ff844b6d4c8d77041308f/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L52)):*
> ```Java
> public class GitOpsInstanceSyncResource {
>   private final InstanceService instanceService;
>   private final GitOpsRequestDTOMapper gitOpsRequestDTOMapper;
> ```

nit: empty line for readability
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 63 at r5](https://reviewable.io/reviews/harness/harness-core/34656#-N63a2zR9doVQ9I9R89c:-N63a2zR9doVQ9I9R89d:b-b0plu) ([raw file](https://github.com/harness/harness-core/blob/6b4241a463b9e1bcc84ff844b6d4c8d77041308f/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L63)):*
> ```Java
>         PageResponse.<InstanceDTO>builder().content(new ArrayList<>(instanceDTOList)).empty(false).build();
>     return ResponseDTO.newResponse(pageResponse);
>   }
> ```

nit: empty line for readability
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 65 at r5](https://reviewable.io/reviews/harness/harness-core/34656#-N63a5PH9hJkhXWOmgSG:-N63a5PH9hJkhXWOmgSH:b-cpym8s) ([raw file](https://github.com/harness/harness-core/blob/6b4241a463b9e1bcc84ff844b6d4c8d77041308f/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L65)):*
> ```Java
>   }
>   @DELETE
>   @Path("/delete")
> ```

We do not need a Path for DELETE. If you add one more delete method, we can add a path
___
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/34656#-N5Mns3z0XZByx3cOpG_:-N63aKb-EFPKzqO5Ee8L:bk02o93) ([raw file](https://github.com/harness/harness-core/blob/5c6eb305d3fb8b003f834d51f81ac9ed1fd5c889/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L36)):*
<details><summary><i>Previously, henry-harness (henry leong) wrote…</i></summary><blockquote>

curious - do we not use orika mappers?
</blockquote></details>

Unfortunately, we do not yet

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/34656)

**Comment by GabeAboy** [comment]
*[a discussion](https://reviewable.io/reviews/harness/harness-core/34656#-N8UCRqT01XozJi278PC:-N8UCRqT01XozJi278PD:b-y90naz) (no related file):*
We can close this @yogesh-chauhan

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34656)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/34656#-N8UCRqT01XozJi278PC:-N8hCWpt1nyM84F5yzSO:bg092sm) (no related file):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

We can close this @yogesh-chauhan 
</blockquote></details>

@achyuth-harness , lets close

___

**Pull request closed without merging**
