### PR TITLE
techdebt: [DEL-5305]: Created DTO version of YamlGitConfig for delegate

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes

We are working on removing mongo dependencies in delegate. As part of that project, we have to create DTO version of a few classes to be passed on to delegate.

Created DTO version of the YamlGitConfig

* Started treating `software.wings.yaml.gitSync.YamlGitConfig` as the DTO Version to avoid any Kryo issues
* Created `software.wings.yaml.gitSync.beans.YamlGitConfig` for the persistence layer.

## Checklist
- [X] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39765)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/yaml/converter/YamlGitConfigBeanConverter.java` line 12 at r1](https://reviewable.io/reviews/harness/harness-core/39765#-NGNs2eD5LuUnL6iMRtg:-NGNs2eF1Z8221TUB_1r:b-nj9jvn) ([raw file](https://github.com/harness/harness-core/blob/cc9a4649240e5906a059aa3cde3e9a40c915af0d/400-rest/src/main/java/software/wings/yaml/converter/YamlGitConfigBeanConverter.java#L12)):*
> ```Java
> import software.wings.yaml.gitSync.YamlGitConfig;
> 
> public class YamlGitConfigBeanConverter {
> ```

i would recommend to not add this as new file. move toDto in the entity class itself

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 47 of 47 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39765)* status: 0 of 1 approvals obtained.

**Review by gn-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39765)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/yaml/converter/YamlGitConfigBeanConverter.java` line 12 at r1](https://reviewable.io/reviews/harness/harness-core/39765#-NGNs2eD5LuUnL6iMRtg:-NGQq-UtEuPOFqyhYcjC:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/cc9a4649240e5906a059aa3cde3e9a40c915af0d/400-rest/src/main/java/software/wings/yaml/converter/YamlGitConfigBeanConverter.java#L12)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

i would recommend to not add this as new file. move toDto in the entity class itself
</blockquote></details>

Done

**Review by jennyjames21 — DISMISSED** [review]
> Reviewed 42 of 47 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39765)* status: 1. unresolved discussions.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39765)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 42 of 47 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39765)* status: :shipit: complete! ✓

**Pull request merged**
