### PR TITLE
[fix]: [SRM-14464]: Moving db reads to secondary instance

### PR DESCRIPTION
**Pull request by dhruv-harness**
## Describe your changes
Moving reads for some of the heavily used collections to the secondary db.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46066)

### CODE REVIEW

**Comment by dhruv-harness** [comment]
trigger messagecheck

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46066)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/ChangeEventServiceImpl.java` line 416 at r1](https://reviewable.io/reviews/harness/harness-core/46066#-NSBLJf05pUaukjdIes7:-NSBLJf05pUaukjdIes8:bhnamii) ([raw file](https://github.com/harness/harness-core/blob/381b425dd8f3e345f8e452d134beed2abf927155/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/ChangeEventServiceImpl.java#L416)):*
> ```Java
>     query.and(criteria.toArray(new Criteria[criteria.size()]));
>     query.and(criteriasForAppAndInfraEvents);
>     query.useReadPreference(ReadPreference.secondaryPreferred());
> ```

why didn't we do it for read queries here like in this method createTextSearchQuery



_Code quote:_
```Java
 query.useReadPreference(ReadPreference.secondaryPreferred());
```

**Review by dhruv-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46066)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/ChangeEventServiceImpl.java` line 416 at r1](https://reviewable.io/reviews/harness/harness-core/46066#-NSBLJf05pUaukjdIes7:-NSEjlF06BE7TtmWp08G:b9fpddv) ([raw file](https://github.com/harness/harness-core/blob/381b425dd8f3e345f8e452d134beed2abf927155/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/ChangeEventServiceImpl.java#L416)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

why didn't we do it for read queries here like in this method createTextSearchQuery
</blockquote></details>

We have set the preference at a common place for createTextSearchQuery. Also we are moving those reads where we dont have updates, ie API calls

**Review by AbhijithHarness — DISMISSED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46066)* status: :shipit: complete! ✓

**Review by deepak-harness — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46066)* status: :shipit: complete! ✓

**Review by Varsha-lalwani — DISMISSED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46066)* status: :shipit: complete! ✓

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46066)* status: :shipit: complete! ✓

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46066)* status: :shipit: complete! ✓

**Pull request merged**
