### PR TITLE
[feat]: [CVNG-4083]: added group & node filters to deployment-timeseries-data API

### PR DESCRIPTION
**Pull request by kapil-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30097)

### CODE REVIEW

**Comment by kapil-harness** [comment]
Transaction Filters:
@GET API URL: https://localhost:8181/cv/api/verify-step/TLnHH0uvTCqqJkxaXlV81g/deployment-timeseries-data?routingId=kmpySmUISimoRrJL6NL73w&accountId=kmpySmUISimoRrJL6NL73w&anomalousMetricsOnly=false&pageNumber=0&pageSize=10&transactionNames=%2Ftodolist%2Fregister&transactionNames=%2Ftodolist%2Finside
Response:
TransactionFilters.json

Host Name Filter:
@GET API URL: https://localhost:8181/cv/api/activity/TLnHH0uvTCqqJkxaXlV81g/deployment-timeseries-data?routingId=kmpySmUISimoRrJL6NL73w&accountId=kmpySmUISimoRrJL6NL73w&anomalousMetricsOnly=false&hostName=harness-deployment-canary-56b5cc7c5b-9rpq7&pageNumber=0&pageSize=10&hostNames=harness-deployment-canary-7445f86dbf-ml857
Response:
HostNameFilter.json

Host Names Filters
@GET API URL: https://localhost:8181/cv/api/activity/TLnHH0uvTCqqJkxaXlV81g/deployment-timeseries-data?routingId=kmpySmUISimoRrJL6NL73w&accountId=kmpySmUISimoRrJL6NL73w&anomalousMetricsOnly=false&pageNumber=0&pageSize=10&hostNames=harness-deployment-canary-7445f86dbf-ml857&hostNames=harness-deployment-canary-56b5cc7c5b-9rpq7
Response:
HostNamesFilter.json

**Review by kanhaiyarat — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30097)* status: 11 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java, line 227 at r2](https://reviewable.io/reviews/harness/harness-core/30097#-Mto8z7r8ujgduN4_97g:-Mto8z7s0C589obslUfR:bq8a0ij) ([raw file](https://github.com/harness/harness-core/blob/36c36b3eb8f85f5d3e1b1101e3553a4beb6b7997/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java#L227)):*
> ```Java
>     if (deploymentTimeSeriesAnalysisFilter.filterByHostName()) {
>       hostNames.add(deploymentTimeSeriesAnalysisFilter.getHostName());
>     }
> ```

lets move this logic to resource

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30097)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java, line 227 at r2](https://reviewable.io/reviews/harness/harness-core/30097#-Mto8z7r8ujgduN4_97g:-MtoP7N72GbNjtm1kwWy:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/36c36b3eb8f85f5d3e1b1101e3553a4beb6b7997/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java#L227)):*
<details><summary><i>Previously, kanhaiyarat (Kanhaiya Rathi) wrote…</i></summary><blockquote>

lets move this logic to resource
</blockquote></details>

done

**Review by kanhaiyarat — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30097)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java, line 290 at r3](https://reviewable.io/reviews/harness/harness-core/30097#-MtpkJT12k4EjU_5Cfwo:-MtpkJT12k4EjU_5Cfwp:bdnlbyx) ([raw file](https://github.com/harness/harness-core/blob/29ec7a0d9469ed5f47464aff529d4e16aaa7c54e/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java#L290)):*
> ```Java
>   private boolean filterHostData(
>       DeploymentTimeSeriesAnalysisDTO.HostData hostData, List<String> hostNames, boolean anomalousMetricsOnly) {
>     if (hostNames == null || hostNames.isEmpty()) {
> ```

let's use isNotEmpty methdo for this
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/cdng/resources/CVNGStepResource.java, line 91 at r3](https://reviewable.io/reviews/harness/harness-core/30097#-Mtpk7Vm5uGKggxgUYzN:-Mtpk7VnAI0z-zjpCwH3:b-maj0tz) ([raw file](https://github.com/harness/harness-core/blob/29ec7a0d9469ed5f47464aff529d4e16aaa7c54e/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/resources/CVNGStepResource.java#L91)):*
> ```Java
>     if (deploymentTimeSeriesAnalysisFilter.filterByHostNames()) {
>       hostNames.addAll(deploymentTimeSeriesAnalysisFilter.getHostNames());
>     }
> ```

is this if condition required ^^ ?

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30097)* status: 11 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java, line 290 at r3](https://reviewable.io/reviews/harness/harness-core/30097#-MtpkJT12k4EjU_5Cfwo:-MtptdUN-5kuVskHZV-b:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/29ec7a0d9469ed5f47464aff529d4e16aaa7c54e/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java#L290)):*
<details><summary><i>Previously, kanhaiyarat (Kanhaiya Rathi) wrote…</i></summary><blockquote>

let's use isNotEmpty methdo for this
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/cdng/resources/CVNGStepResource.java, line 91 at r3](https://reviewable.io/reviews/harness/harness-core/30097#-Mtpk7Vm5uGKggxgUYzN:-MtpteVB0GzpkFSxEbuc:b-sp4x11) ([raw file](https://github.com/harness/harness-core/blob/29ec7a0d9469ed5f47464aff529d4e16aaa7c54e/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/resources/CVNGStepResource.java#L91)):*
<details><summary><i>Previously, kanhaiyarat (Kanhaiya Rathi) wrote…</i></summary><blockquote>

is this if condition required ^^ ?
</blockquote></details>

yes these 2 if's are required, they basically check whether both hostName & hostNames filters are null. They handle many permutations and combinations of either or both being null.

**Review by kanhaiyarat — APPROVED** [review]
> Reviewed 6 of 11 files at r2, 1 of 3 files at r3, 2 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30097)* status: :shipit: complete! ✓

**Review by kanhaiyarat — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30097)* status: :shipit: complete! ✓

**Pull request merged**
