### PR TITLE
fix: [CDS-47488]: Template Api no git details error

### PR DESCRIPTION
**Pull request by TarunUba1**
## Describe your changes
Removing error coming when Storetype sent as null in gitdetails.
## Testing
1. Store type with no git details 
Screenshot 2022-12-04 at 6 28 23 PM

2. Store type INLINE 
Screenshot 2022-12-04 at 6 29 11 PM

3. Store Type Remote
Screenshot 2022-12-04 at 6 31 23 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41069)

### CODE REVIEW

**Comment by tchaurasiya** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/TemplateResourceApiMapper.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/41069#-NIT9yHJ-y5N2jgXiOO1:-NIT9yHJ-y5N2jgXiOO2:bkht8fk) ([raw file](https://github.com/harness/harness-core/blob/2ad4e8e7a34d688e24376f9d46628063eaaad0a7/840-template-service/src/main/java/io/harness/template/resources/TemplateResourceApiMapper.java#L182)):*
> ```Java
> 
>   public GitEntityInfo populateGitCreateDetails(GitCreateDetails gitDetails) {
>     if (gitDetails == null) {
> ```

As i understood this issue is coming because of GitCreateDetails being null in request.
Then how does setting store type INLINE, by default fix the issue. wont code will return from here itself?

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41069)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/TemplateResourceApiMapper.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/41069#-NIT9yHJ-y5N2jgXiOO1:-NIVmT9j4LOdDwPp9C3J:bmsqu51) ([raw file](https://github.com/harness/harness-core/blob/2ad4e8e7a34d688e24376f9d46628063eaaad0a7/840-template-service/src/main/java/io/harness/template/resources/TemplateResourceApiMapper.java#L182)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

As i understood this issue is coming because of GitCreateDetails being null in request.
Then how does setting store type INLINE, by default fix the issue. wont code will return from here itself?
</blockquote></details>

I also thought the same but 'Meet Rathod' passed an empty array.
  "git_details": {
  }
the case of null works when gitDetails is not sent at all.
 In that case gitDetails is not null but its parameters are. This leads to bypass this condition. I can also try to check gitDetails.getStoreType in the same if condition. This could also solve the problem.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41069)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41069)* status: 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41069)* status: 1. unresolved discussions.

**Review by TarunUba1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41069)* status: 1. unresolved discussions.

**Review by TarunUba1 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41069#-:-NIbMPjO6YK6MXED7yc5:bnfp4nl)* status: 1. unresolved discussions.

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41069)* status: 1. unresolved discussions. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/TemplateResourceApiMapper.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/41069#-NIT9yHJ-y5N2jgXiOO1:-NIbMTyICyQ-ZUtbJJkx:b-85i64v) ([raw file](https://github.com/harness/harness-core/blob/2ad4e8e7a34d688e24376f9d46628063eaaad0a7/840-template-service/src/main/java/io/harness/template/resources/TemplateResourceApiMapper.java#L182)):*
<details><summary><i>Previously, TarunUba1 (Tarun Uba) wrote…</i></summary><blockquote>

I also thought the same but 'Meet Rathod' passed an empty array.
  "git_details": {
  }
the case of null works when gitDetails is not sent at all.
 In that case gitDetails is not null but its parameters are. This leads to bypass this condition. I can also try to check gitDetails.getStoreType in the same if condition. This could also solve the problem.
</blockquote></details>

LGTM

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41069)* status: :shipit: complete! ✓

**Pull request merged**
