### PR TITLE
feat: [PL-30374]: Added job for adding basic role to default user group at project and org scope

### PR DESCRIPTION
**Pull request by meenakshi-harness**
## Describe your changes
1. Added Job to assign basic role to default user groups in existing org/project. - Tested this migration with QA data.
2. Made viewer role assignment optional as part of same Job in point 1 - Tested this migration with QA data.
3. Add basic role to default usergroup for new org/project.
4. Add viewer role to default usergroup for new org/project with managed as false i.e. optional. -
 Details :Viewer Roles assignment was already added in Default User Groups (when new org/project was created). But this role assignmnet was added as managed role assignment i.e. non deletable. We have made this assignment with managed as false. Hence making it optional and now users will be able to delete this assignment if they want. (
5. Point 3 and 4 changes will also be reflected in DefaultGroupReconcilationJob as it also calls same piece of code.

Note: All these changes are added behind FF. We will enable this for few accounts->test->GA it in any cluster
 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42081)

### CODE REVIEW

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42081)* status: Some of the checks are too old. 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/DefaultUserGroupServiceImpl.java` line 160 at r2](https://reviewable.io/reviews/harness/harness-core/42081#-NLOxArU4Ks5iTk_MzcD:-NLOxArU4Ks5iTk_MzcE:b6qq72d) ([raw file](https://github.com/harness/harness-core/blob/385cdd15840d493e7ff179782c8c2a06a5d9e34b/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/DefaultUserGroupServiceImpl.java#L160)):*
> ```Java
>   private void createRoleAssignmentForProject(String userGroupIdentifier, Scope scope) {
>     createRoleAssignment(
>         userGroupIdentifier, scope, true, true, PROJECT_BASIC_ROLE, DEFAULT_PROJECT_LEVEL_RESOURCE_GROUP_IDENTIFIER);
> ```

When creating Default UG for Org, we need to assign both Org Viewer and Org Basic. Org viewer would be created with managed=false i.e making the role assignment deletable and Org basic should be created with managed=true. Similarly for Project.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42081)* status: Some of the checks are too old. 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/OrgProjectBasicRoleAssignmentMigrations.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/42081#-NLOzD8S3gYwtu5steeo:-NLOzD8S3gYwtu5steep:b-pfhj9c) ([raw file](https://github.com/harness/harness-core/blob/385cdd15840d493e7ff179782c8c2a06a5d9e34b/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/OrgProjectBasicRoleAssignmentMigrations.java#L55)):*
> ```Java
>   public void migrate() {
>     Criteria projectCriteria = Criteria.where(RoleAssignmentDBO.RoleAssignmentDBOKeys.roleIdentifier)
>                                    .is(PROJECT_VIEWER)
> ```

Check the order of the fields to use existing index.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/OrgProjectBasicRoleAssignmentMigrations.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/42081#-NLOzIme7Ik0CdSmFmG7:-NLOzIme7Ik0CdSmFmG8:b-fi936o) ([raw file](https://github.com/harness/harness-core/blob/385cdd15840d493e7ff179782c8c2a06a5d9e34b/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/OrgProjectBasicRoleAssignmentMigrations.java#L58)):*
> ```Java
>                                    .and(RoleAssignmentDBO.RoleAssignmentDBOKeys.resourceGroupIdentifier)
>                                    .is(DEFAULT_PROJECT_LEVEL_RESOURCE_GROUP_IDENTIFIER)
>                                    .and(RoleAssignmentDBO.RoleAssignmentDBOKeys.scopeLevel)
> ```

Also, add condition to query by principalScopeLevel.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/OrgProjectBasicRoleAssignmentMigrations.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/42081#-NLOz5OGDdFIIzPZTg8D:-NLOz5OGDdFIIzPZTg8E:b-bgz0g) ([raw file](https://github.com/harness/harness-core/blob/385cdd15840d493e7ff179782c8c2a06a5d9e34b/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/OrgProjectBasicRoleAssignmentMigrations.java#L61)):*
> ```Java
>                                    .is(HarnessScopeLevel.PROJECT.getName())
>                                    .and(RoleAssignmentDBO.RoleAssignmentDBOKeys.principalType)
>                                    .is(USER)
> ```

We need to this migration for USER_GROUP.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/OrgProjectBasicRoleAssignmentMigrations.java` line 81 at r2](https://reviewable.io/reviews/harness/harness-core/42081#-NLOxo-fAJqnOOpnG4op:-NLOxo-fAJqnOOpnG4oq:b-yrf2wk) ([raw file](https://github.com/harness/harness-core/blob/385cdd15840d493e7ff179782c8c2a06a5d9e34b/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/OrgProjectBasicRoleAssignmentMigrations.java#L81)):*
> ```Java
>     int pageSize = 1000;
>     int pageIndex = 0;
>     Pageable pageable = PageRequest.of(pageIndex, pageSize);
> ```

Pageable object should be created for every page.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42081)* status: Some of the checks are too old. 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/OrgProjectBasicRoleAssignmentMigrations.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/42081#-NLQXFLb9z3cETrwRaND:-NLQXFLc0a3wMZa1bFJf:b888ehm) ([raw file](https://github.com/harness/harness-core/blob/385cdd15840d493e7ff179782c8c2a06a5d9e34b/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/OrgProjectBasicRoleAssignmentMigrations.java#L72)):*
> ```Java
>                                .and(RoleAssignmentDBO.RoleAssignmentDBOKeys.principalType)
>                                .is(USER)
>                                .and(RoleAssignmentDBO.RoleAssignmentDBOKeys.managed)
> ```

Add Principal Identifier of default user groups in critetria. In case of Org, it is _organization_all_users and project it is _project_all_users.

**Comment by meenakshi-harness** [comment]
trigger ft1

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Comment by USB-05** [comment]
trigger gitleaks

**Comment by USB-05** [comment]
trigger gitleaks

**Comment by USB-05** [comment]
trigger gitleaks

**Comment by USB-05** [comment]
trigger gitleaks

**Comment by USB-05** [comment]
trigger gitleaks

**Comment by USB-05** [comment]
trigger gitleaks

**Comment by USB-05** [comment]
trigger gitleaks

**Comment by USB-05** [comment]
trigger gitleaks

**Comment by USB-05** [comment]
trigger gitleaks

**Comment by USB-05** [comment]
trigger gl

**Review by reetika04 — APPROVED** [review]
> Reviewed 6 of 7 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42081)* status: 9 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42081)* status: 13 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/ProjectOrgBasicRoleCreationJob.java` line 149 at r7](https://reviewable.io/reviews/harness/harness-core/42081#-NNfo4lsEdD7NdvcjSxG:-NNfo4lsEdD7NdvcjSxH:b-gp92j8) ([raw file](https://github.com/harness/harness-core/blob/c242a33de4082d7cdb39c67b534045ebe6506e5c/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/ProjectOrgBasicRoleCreationJob.java#L149)):*
> ```Java
>       }
>     } catch (Exception ex) {
>       log.error(DEBUG_MESSAGE + "Failed to filter accounts for ff", ex);
> ```

Check this message.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/ProjectOrgBasicRoleCreationJob.java` line 166 at r7](https://reviewable.io/reviews/harness/harness-core/42081#-NNfo-rd0En-Nonuk9Js:-NNfo-rd0En-Nonuk9Jt:b-6nzv6v) ([raw file](https://github.com/harness/harness-core/blob/c242a33de4082d7cdb39c67b534045ebe6506e5c/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/ProjectOrgBasicRoleCreationJob.java#L166)):*
> ```Java
>       log.error(DEBUG_MESSAGE + "Failed to filter accounts for FF PL_ENABLE_BASIC_ROLE_FOR_PROJECTS_ORGS");
>     }
>     targetAccounts.add("kmpySmUISimoRrJL6NL73w");
> ```

Remove this.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/ProjectOrgBasicRoleCreationService.java` line 34 at r7](https://reviewable.io/reviews/harness/harness-core/42081#-NNfnWVb6XPfUeKso_yL:-NNfnWVb6XPfUeKso_yM:b-7xeyip) ([raw file](https://github.com/harness/harness-core/blob/c242a33de4082d7cdb39c67b534045ebe6506e5c/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/ProjectOrgBasicRoleCreationService.java#L34)):*
> ```Java
>   public ProjectOrgBasicRoleCreationService(ProjectOrgBasicRoleCreationJob projectOrgBasicRoleCreationJob) {
>     this.projectOrgBasicRoleCreationJob = projectOrgBasicRoleCreationJob;
>     String threadName = "user-roleAssignment-removal-service-thread";
> ```

change the threadName.

**Comment by meenakshi-harness** [comment]
trigger ti4

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 6 of 7 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42081)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 603 at r8](https://reviewable.io/reviews/harness/harness-core/42081#-NNjGHMs7FqIn_ZCqh1Y:-NNjGHMs7FqIn_ZCqh1Z:bm771q2) ([raw file](https://github.com/harness/harness-core/blob/422b97e2359849bc0c899be0728d31f28b583961/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L603)):*
> ```Java
> 
>   PL_ENABLE_BASIC_ROLE_FOR_PROJECTS_ORGS(
>       "Enable Basic Role assignment  Default User Group in Orgs and Projects", HarnessTeam.PL),
> ```

nit  multiple whitespaces

**Comment by pbarapatre10** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/ProjectOrgBasicRoleCreationJob.java` line 101 at r8](https://reviewable.io/reviews/harness/harness-core/42081#-NNjGtlp0NndI4JACWYz:-NNjGtlp0NndI4JACWZ-:b-cpnj6k) ([raw file](https://github.com/harness/harness-core/blob/422b97e2359849bc0c899be0728d31f28b583961/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/ProjectOrgBasicRoleCreationJob.java#L101)):*
> ```Java
>       log.error(DEBUG_MESSAGE + " failed to acquire lock", ex);
>     }
>     log.info(DEBUG_MESSAGE + " completed...");
> ```

minor: once we log the error for lock acquiring, we shouldn't log "Job completed" as well, I think we can directly return if acquiring lock throws exception. Thanks



_Code quote:_
```Java
      log.error(DEBUG_MESSAGE + " failed to acquire lock", ex);
    }
    log.info(DEBUG_MESSAGE + " completed...");
```

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 5 of 7 files at r4, 1 of 3 files at r6, 5 of 7 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42081)* status: :shipit: complete! ✓

**Pull request merged**
