### PR TITLE
[fix]: [CDS-68258]: Fixing terraformPlan steps output not including the strategy-iteration sufix in value

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Fixing terraformPlanStep output var's value(value is an expressions) is being evaluated to null when accessed from next steps. This is happening when there is strategy used at any level for that step.

Issue: When we copy the outputVar `jsonFilePath` value in the terraformPlan step, the value is an expression having FQN till step. And the FQN is calculated during planCreation from the YAML and it does not contain the strategy-prefixes. 
So the expression was evaluating to null when the step was under the strategy.

Example expression before my change. There is strategy at stage and stepGroup level. But expression does not include strategy-prefix
```<+terraformPlanJson."pipeline.stages.cs0.spec.execution.steps.SG.steps.TerraformPlan_1.terPlan_planJson">```

Fix: Instead of calculating the stepFQN at planCreation, calculate it at runtime. It will handle the strategy if present at any parent level.

The same output value after my fix:
```<+terraformPlanJson."pipeline.stages.cs0_0.spec.execution.steps.SG_0.steps.TerraformPlan_1.terPlan_planJson">```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47311)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47311)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStep.java` line 310 at r2](https://reviewable.io/reviews/harness/harness-core/47311#-NU_8BXg-vBKZJFacWV9:-NU_8BXg-vBKZJFacWVA:b-74cv1v) ([raw file](https://github.com/harness/harness-core/blob/aee160124db3ff7247d8b1f6e7865a4719722960/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStep.java#L310)):*
> ```Java
>   }
> 
>   private String getStepFQNFromAmbiance(Ambiance ambiance) {
> ```

@brijeshdhakar i think we would have this function already somewhere?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStepParameters.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/47311#-NU_8Fbi8QfbjrqxeBY9:-NU_8Fbi8QfbjrqxeBYA:bkkyp6g) ([raw file](https://github.com/harness/harness-core/blob/aee160124db3ff7247d8b1f6e7865a4719722960/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStepParameters.java#L33)):*
> ```Java
>   // Not needed. We are calculating the stepFQN during runtime. Remove this stepFqn field in after few releases. Keeping
>   // for backward compatibility.
>   String stepFqn;
> ```

Add deprecated annotation

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47311)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStep.java` line 310 at r2](https://reviewable.io/reviews/harness/harness-core/47311#-NU_8BXg-vBKZJFacWV9:-NU_F7Dk50oNVyC0tyoY:ba5m8vg) ([raw file](https://github.com/harness/harness-core/blob/aee160124db3ff7247d8b1f6e7865a4719722960/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStep.java#L310)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@brijeshdhakar i think we would have this function already somewhere?
</blockquote></details>

Didn't find the right method. Moved this method to AmbianceUtils.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStepParameters.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/47311#-NU_8Fbi8QfbjrqxeBY9:-NU_FDHl7H2vqAil43Lu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aee160124db3ff7247d8b1f6e7865a4719722960/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStepParameters.java#L33)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Add deprecated annotation
</blockquote></details>

Done.

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger ss

**Review by archit-harness — DISMISSED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47311)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47311)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47311)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 509 at r6](https://reviewable.io/reviews/harness/harness-core/47311#-NUa0hwTABGtUsxTRoHz:-NUa0hwTABGtUsxTRoI-:bxk9u2l) ([raw file](https://github.com/harness/harness-core/blob/ea03146e14fb76294ed62d16ce415f42ab021c3d/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L509)):*
> ```Java
>   public static boolean shouldIncludeInQualifiedName(
>       final String identifier, final String setupId, boolean skipExpressionChain) {
>     return !shouldNotIncludeInQualifiedName(identifier) && !identifier.equals(YAMLFieldNameConstants.PARALLEL + setupId)
> ```

nit: better to always have constants on the left side of the comparison
(YAMLFieldNameConstants.PARALLEL + setupId).equals(identifier)

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 1 of 4 files at r3, 2 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47311)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger review

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 4 files at r3, 2 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47311)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47311)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger review

**Pull request merged**
