### PR TITLE
[fix]: [PL-22649]: Update rootFolder path that we get from github

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
Update rootFolder path that we get from github

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31009)

### CODE REVIEW

**Comment by rathodmeetsatish** [comment]
trigger messagecheck

**Comment by abhinav-harness** [comment]
do we need migration for old ones?

**Comment by abhinav-harness** [comment]
can you check db how many such records we have

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31009)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitChangeSetMapper.java, line 71 at r1](https://reviewable.io/reviews/harness/harness-core/31009#-Mx0uhsT6lEPsO7jmvst:-Mx43Or2CKtNWf3XdDyE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0ea03303c889f7cf35b8594c3154caf74d092c71/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitChangeSetMapper.java#L71)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Please move this to a util. We must be having some util related to file paths etc.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31009#-:-Mx43wgl6JoYxZhRtQG1:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by rathodmeetsatish** [comment]
trigger ft2

**Review by rijajoo — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31009#-:-Mx4EkB14V78ptaJrW7p:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
