### PR TITLE
feat: [CDS-36910]: Pipeline CRUD with EnvGroup Ref

### PR DESCRIPTION
**Pull request by prashantsharma04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32904)

### CODE REVIEW

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32904)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32904)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32904)* status: :shipit: complete! ✓

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/envgroup/helper/EnvironmentGroupYamlVisitorHelper.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/32904#-N1bGcA17TyYbfx_meqx:-N1bGcA17TyYbfx_meqy:b-f1g3kt) ([raw file](https://github.com/harness/harness-core/blob/71f43e1c705ad063469382034cc1611eae345be6/127-cd-nextgen-entities/src/main/java/io/harness/cdng/envgroup/helper/EnvironmentGroupYamlVisitorHelper.java#L14)):*
> ```Java
> import io.harness.walktree.visitor.validation.ValidationVisitor;
> 
> public class EnvironmentGroupYamlVisitorHelper implements ConfigValidator {
> ```

Please add owner

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32904)* status: :shipit: complete! ✓

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/envgroup/helper/EnvironmentGroupYamlVisitorHelper.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/32904#-N1bGcA17TyYbfx_meqx:-N1cBVsO73CsP51zCqU9:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/71f43e1c705ad063469382034cc1611eae345be6/127-cd-nextgen-entities/src/main/java/io/harness/cdng/envgroup/helper/EnvironmentGroupYamlVisitorHelper.java#L14)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Please add owner
</blockquote></details>

done

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32904)* status: :shipit: complete! ✓

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, 3 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32904)* status: :shipit: complete! ✓

**Pull request merged**
