### PR TITLE
feat: [PIE-9504]: Write a method in ScmFacilitatorServiceImpl to get authenticated user 

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46063)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GetAuthenticatedUserDTO.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/46063#-NSdv62G3omOtXHSA2Tt:-NSdv62G3omOtXHSA2Tu:b-3728eh) ([raw file](https://github.com/harness/harness-core/blob/4737e14a4570aeaf03b13f256906c1ffe9914613/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GetAuthenticatedUserDTO.java#L22)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @OwnedBy(HarnessTeam.PIPELINE)
> public class GetAuthenticatedUserDTO {
> ```

is it a response dto or a request dto? We can name it better to be clear

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 392 at r3](https://reviewable.io/reviews/harness/harness-core/46063#-NSdvHCO278ULhsSx9j0:-NSdvHCO278ULhsSx9j1:b-wk3rym) ([raw file](https://github.com/harness/harness-core/blob/4737e14a4570aeaf03b13f256906c1ffe9914613/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L392)):*
> ```Java
>   }
> 
>   public boolean isUserSCMRegistered(String accountIdentifier, ScmConnector connectorDTO) {
> ```

why is this method inside git-sync connector helper, this looks different logically

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 409 at r3](https://reviewable.io/reviews/harness/harness-core/46063#-NSdvl-k6Q950pACHVjI:-NSdvl-k6Q950pACHVjJ:blr2wva) ([raw file](https://github.com/harness/harness-core/blob/4737e14a4570aeaf03b13f256906c1ffe9914613/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L409)):*
> ```Java
>   }
> 
>   public GetAuthenticatedUserDTO getAuthenticatedUser(String accountIdentifier, ScmConnector connectorDTO) {
> ```

this method is confusing to understand actually what it does. What is it actually doing? Its name doesn't correspond to the functionality of the code.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1146 at r3](https://reviewable.io/reviews/harness/harness-core/46063#-NSdwHHmC8JTRKObYH61:-NSdwHHmC8JTRKObYH62:bjtjxp7) ([raw file](https://github.com/harness/harness-core/blob/4737e14a4570aeaf03b13f256906c1ffe9914613/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1146)):*
> ```Java
> 
>   @Override
>   public GetAuthenticatedUserDTO getAuthenticatedUser(GitAccessDTO gitAccessDTO) {
> ```

lets create a request dto just like other methods. We can encapsulate this field inside the request dto such that its scalable if we want to add more request fields later on.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmManagerFacilitatorServiceImpl.java` line 363 at r3](https://reviewable.io/reviews/harness/harness-core/46063#-NSdwoS4792_X_xw1F5J:-NSdwoS4792_X_xw1F5K:b-amip34) ([raw file](https://github.com/harness/harness-core/blob/4737e14a4570aeaf03b13f256906c1ffe9914613/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmManagerFacilitatorServiceImpl.java#L363)):*
> ```Java
>     ScmConnector scmConnector = createGitFileRequestDTO.getScmConnector();
>     if (gitSyncConnectorHelper.isUserSCMRegistered(scope.getAccountIdentifier(), scmConnector)) {
>       gitSyncConnectorHelper.setUserGitCredsInConnector(scope.getAccountIdentifier(), scmConnector);
> ```

can't we just create a method "setUserGitCredsInConnectorIfPresent" and do all of this if else inside it?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46063)* status: 34 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 392 at r3](https://reviewable.io/reviews/harness/harness-core/46063#-NSdvHCO278ULhsSx9j0:-NSdwtaw-_ifE2iqwMP-:be9qht3) ([raw file](https://github.com/harness/harness-core/blob/4737e14a4570aeaf03b13f256906c1ffe9914613/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L392)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is this method inside git-sync connector helper, this looks different logically
</blockquote></details>

this method determines whether or not a user source code manager is registered for the given accountId and type of scm connector. Removed this method now as it seems redundant.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 409 at r3](https://reviewable.io/reviews/harness/harness-core/46063#-NSdvl-k6Q950pACHVjI:-NSdwiBW5WU9Kpk8aKS6:bfj39ov) ([raw file](https://github.com/harness/harness-core/blob/4737e14a4570aeaf03b13f256906c1ffe9914613/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L409)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this method is confusing to understand actually what it does. What is it actually doing? Its name doesn't correspond to the functionality of the code.
</blockquote></details>

this method returns the details of the user by extracting them from the user source code manager db. Renamed to make it more verbose.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1146 at r3](https://reviewable.io/reviews/harness/harness-core/46063#-NSdwHHmC8JTRKObYH61:-NSdyX8s6eHdxAWNC5aY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4737e14a4570aeaf03b13f256906c1ffe9914613/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1146)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets create a request dto just like other methods. We can encapsulate this field inside the request dto such that its scalable if we want to add more request fields later on.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmManagerFacilitatorServiceImpl.java` line 363 at r3](https://reviewable.io/reviews/harness/harness-core/46063#-NSdwoS4792_X_xw1F5J:-NSdyWPzDBLTP1kbhiC5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4737e14a4570aeaf03b13f256906c1ffe9914613/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmManagerFacilitatorServiceImpl.java#L363)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can't we just create a method "setUserGitCredsInConnectorIfPresent" and do all of this if else inside it?
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GetAuthenticatedUserDTO.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/46063#-NSdv62G3omOtXHSA2Tt:-NSdxBUBCvauoNtLQJL3:b-e6vkdk) ([raw file](https://github.com/harness/harness-core/blob/4737e14a4570aeaf03b13f256906c1ffe9914613/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GetAuthenticatedUserDTO.java#L22)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

is it a response dto or a request dto? We can name it better to be clear
</blockquote></details>

it's a response dto, renamed the class

**Comment by shalini-agr** [comment]
trigger ut0

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 9 of 32 files at r2, 1 of 9 files at r4, 28 of 28 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46063)* status: Some of the checks are too old. 38 file(s) to review. 5. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 9 of 32 files at r2, 1 of 9 files at r4, 28 of 28 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46063)* status: Some of the checks are too old. Waiting on team(s): del-team.

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
