### PR TITLE
[feat]: [CDS-40079]: Implement S3 artifact download

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Describe your changes
Support for downloading artifacts from AWS S3 bucket is added for ng, for ssh and winrm deployments. A proper Bash or PowerShell download script is generated, which includes all necessary authentication/authorisation headers. Artifact is saved in the destination folder location on target host. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37748)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 11 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 8 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37748)

**Comment by vladimir-peric** [comment]
trigger messagecheck

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/AwsS3ArtifactDownloadHandler.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/37748#-NCUXQULBV4oouO1gb4l:-NCUXQULBV4oouO1gb4m:b-popbks) ([raw file](https://github.com/harness/harness-core/blob/06c4251eff4ffff0d3778eea145b5ceab574138e/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/AwsS3ArtifactDownloadHandler.java#L35)):*
> ```Java
> 
>   private String getSshCommand(AwsS3FetchFileDelegateConfig awsS3FetchFileDelegateConfig, String destinationPath) {
>     return awsS3ArtifactsUtils.createBashCommandForS3ArtifactDownload(awsS3FetchFileDelegateConfig, destinationPath);
> ```

Consider moving code from utility class here since it is not too massive and to have it on one place.

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/AwsS3ArtifactDownloadHandler.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/37748#-NCUXcLU1cpGCYUu1e_h:-NCUXcLU1cpGCYUu1e_i:b-to51rx) ([raw file](https://github.com/harness/harness-core/blob/06c4251eff4ffff0d3778eea145b5ceab574138e/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/AwsS3ArtifactDownloadHandler.java#L40)):*
> ```Java
>   private String getPowerShellCommand(
>       AwsS3FetchFileDelegateConfig awsS3FetchFileDelegateConfig, String destinationPath) {
>     return awsS3ArtifactsUtils.createPsCommandForS3ArtifactDownload(awsS3FetchFileDelegateConfig, destinationPath);
> ```

same here. Especially, because power shell and curl should use same methods for creating header and url

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/utils/AwsS3ArtifactsUtils.java` line 96 at r2](https://reviewable.io/reviews/harness/harness-core/37748#-NCUXw7v5j4jx5tfffBq:-NCUXw7v5j4jx5tfffBr:brcrwpl) ([raw file](https://github.com/harness/harness-core/blob/06c4251eff4ffff0d3778eea145b5ceab574138e/930-delegate-tasks/src/main/java/io/harness/delegate/utils/AwsS3ArtifactsUtils.java#L96)):*
> ```Java
>         AWS4SignerForAuthorizationHeader.getEndpointWithCanonicalizedResourcePath(endpointUrl, true);
>     String command = "$Headers = @{\n"
>         + "    Authorization = \"" + authorizationHeader + "\"\n"
> ```

Missing key word Basic or some other

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/utils/AwsS3ArtifactsUtils.java` line 120 at r2](https://reviewable.io/reviews/harness/harness-core/37748#-NCUY1PB6iSTAKQg6bfH:-NCUY1PB6iSTAKQg6bfI:b-m621ka) ([raw file](https://github.com/harness/harness-core/blob/06c4251eff4ffff0d3778eea145b5ceab574138e/930-delegate-tasks/src/main/java/io/harness/delegate/utils/AwsS3ArtifactsUtils.java#L120)):*
> ```Java
>   private String getHeaders(AwsS3FetchFileDelegateConfig s3ArtifactDelegateConfig) {
>     AwsConnectionDetails connectionDetails = mapAwsConnectionDetails(s3ArtifactDelegateConfig, "");
>     return " Authorization = \"" + connectionDetails.authorizationHeader + "\"\n"
> ```

Key word missing

**Comment by bojanmicovic** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/aws/s3/AwsS3FetchFileDelegateConfig.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/37748#-NCUYCQP-BATR2t-Syza:-NCUYCQP-BATR2t-Syzb:b-9gkdzk) ([raw file](https://github.com/harness/harness-core/blob/06c4251eff4ffff0d3778eea145b5ceab574138e/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/aws/s3/AwsS3FetchFileDelegateConfig.java#L28)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> public class AwsS3FetchFileDelegateConfig
>     implements SshWinRmArtifactDelegateConfig, ExpressionReflectionUtils.NestedAnnotationResolver {
> ```

Consider creating new class for config with the fields we need

**Comment by bojanmicovic** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/aws/s3/AwsS3FetchFileDelegateConfig.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/37748#-NCUYCQP-BATR2t-Syza:-NCUYOIj8j76yE57d5Mz:b-lxlba) ([raw file](https://github.com/harness/harness-core/blob/06c4251eff4ffff0d3778eea145b5ceab574138e/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/aws/s3/AwsS3FetchFileDelegateConfig.java#L28)):*
<details><summary><i>Previously, bojanmicovic (Bojan Micovic) wrote…</i></summary><blockquote>

Consider creating new class for config with the fields we need
</blockquote></details>

artifactPath
bucket
region
encryptedDetails
connectorDTO

**Comment by bojanmicovic** [comment]
Modify io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java:138 error message since we now support AwsS3

**Comment by vladimir-peric** [comment]
1. Is it new task type? No
2. Did you add a new class which is added in kryo serialization Yes
3. Did you make changes to the code in a backward-compatible manner? will the new version of the delegate receive old version task and process? Yes
4. If new version of the manager receives response for the old task will it be able to handle it successfully? Yes
5. Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager No
6. If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay
7. if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay
8. Did you remove an enum → this is not backward compatible yet  No
9. Did you add an enum → make sure that the enum constant is added in the end of the already defined constants. If you don’t do this then you will have issues where wrong enum type will be deserialized in delegate side. Yes

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37748)* status: 17 file(s) to review. 6. unresolved discussions. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/37748#-NCUZ9TL86E63ai6yMoG:-NCYsUL8DmYwJaNHWZtr:b-896fix) (no related file):*
<details><summary><i>Previously, bojanmicovic (Bojan Micovic) wrote…</i></summary><blockquote>

Modify io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java:138 error message since we now support AwsS3
</blockquote></details>

Done.

___
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/AwsS3ArtifactDownloadHandler.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/37748#-NCUXQULBV4oouO1gb4l:-NCYsVyy9YlE6WxLWCM3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/06c4251eff4ffff0d3778eea145b5ceab574138e/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/AwsS3ArtifactDownloadHandler.java#L35)):*
<details><summary><i>Previously, bojanmicovic (Bojan Micovic) wrote…</i></summary><blockquote>

Consider moving code from utility class here since it is not too massive and to have it on one place.
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/AwsS3ArtifactDownloadHandler.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/37748#-NCUXcLU1cpGCYUu1e_h:-NCYsZbGCvnqjCbttdf7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/06c4251eff4ffff0d3778eea145b5ceab574138e/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/AwsS3ArtifactDownloadHandler.java#L40)):*
<details><summary><i>Previously, bojanmicovic (Bojan Micovic) wrote…</i></summary><blockquote>

same here. Especially, because power shell and curl should use same methods for creating header and url
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/utils/AwsS3ArtifactsUtils.java` line 96 at r2](https://reviewable.io/reviews/harness/harness-core/37748#-NCUXw7v5j4jx5tfffBq:-NCYs_ww-APujQeoh_fL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/06c4251eff4ffff0d3778eea145b5ceab574138e/930-delegate-tasks/src/main/java/io/harness/delegate/utils/AwsS3ArtifactsUtils.java#L96)):*
<details><summary><i>Previously, bojanmicovic (Bojan Micovic) wrote…</i></summary><blockquote>

Missing key word Basic or some other
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/utils/AwsS3ArtifactsUtils.java` line 120 at r2](https://reviewable.io/reviews/harness/harness-core/37748#-NCUY1PB6iSTAKQg6bfH:-NCYsaRSEoX526qQ_WcA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/06c4251eff4ffff0d3778eea145b5ceab574138e/930-delegate-tasks/src/main/java/io/harness/delegate/utils/AwsS3ArtifactsUtils.java#L120)):*
<details><summary><i>Previously, bojanmicovic (Bojan Micovic) wrote…</i></summary><blockquote>

Key word missing
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/aws/s3/AwsS3FetchFileDelegateConfig.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/37748#-NCUYCQP-BATR2t-Syza:-NCYsbr47Tc9E3N6ML5Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/06c4251eff4ffff0d3778eea145b5ceab574138e/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/aws/s3/AwsS3FetchFileDelegateConfig.java#L28)):*
<details><summary><i>Previously, bojanmicovic (Bojan Micovic) wrote…</i></summary><blockquote>

artifactPath
bucket
region
encryptedDetails
connectorDTO


</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 3 of 11 files at r1, 1 of 8 files at r2, 1 of 6 files at r3, 4 of 9 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37748)* status: 6. unresolved discussions. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java` line 44 at r5](https://reviewable.io/reviews/harness/harness-core/37748#-NCYsw6K1TPwWd_Piq4t:-NCYsw6K1TPwWd_Piq4u:b-7jxcbj) ([raw file](https://github.com/harness/harness-core/blob/bb10296eb7ebec649a9e60ac80bbb0165d66cc06/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java#L44)):*
> ```Java
>         return getS3FileInputStream((AwsS3ArtifactDelegateConfig) context.getArtifactDelegateConfig(), logCallback);
>       } catch (IOException e) {
>         log.error(format("Error while fetching S3 artifact: %s", e.getMessage()));
> ```

we need to throw exception with hint and explanation, don't hide the in logs only.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java` line 57 at r5](https://reviewable.io/reviews/harness/harness-core/37748#-NCYt2aLD0dQy0n4H6Dw:-NCYt2aLD0dQy0n4H6Dx:bb2wf4l) ([raw file](https://github.com/harness/harness-core/blob/bb10296eb7ebec649a9e60ac80bbb0165d66cc06/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java#L57)):*
> ```Java
>         return getS3FileSize((AwsS3ArtifactDelegateConfig) context.getArtifactDelegateConfig(), logCallback);
>       } catch (IOException e) {
>         log.error(format("Error while fetching S3 artifact: %s", e.getMessage()));
> ```

same here, we need to throw exception with hint and explanation, don't hide the in logs only.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java` line 79 at r5](https://reviewable.io/reviews/harness/harness-core/37748#-NCYtE1S0EXsVCN0iCmT:-NCYtE1S0EXsVCN0iCmU:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/bb10296eb7ebec649a9e60ac80bbb0165d66cc06/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java#L79)):*
> ```Java
>       log.error(errorMsg, e.getMessage());
>       executionLogCallback.saveExecutionLog(errorMsg, ERROR, CommandExecutionStatus.FAILURE);
>       throw e;
> ```

same here
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java` line 101 at r5](https://reviewable.io/reviews/harness/harness-core/37748#-NCYtAtRDkJgWAL17WiM:-NCYtAtRDkJgWAL17WiN:b7jg5dt) ([raw file](https://github.com/harness/harness-core/blob/bb10296eb7ebec649a9e60ac80bbb0165d66cc06/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java#L101)):*
> ```Java
>       log.error(errorMsg, e.getMessage());
>       executionLogCallback.saveExecutionLog(errorMsg, ERROR, CommandExecutionStatus.FAILURE);
>       throw e;
> ```

same, exception with hint and explanation
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java` line 119 at r5](https://reviewable.io/reviews/harness/harness-core/37748#-NCYtMnCDP8h9tQgYvTG:-NCYtMnCDP8h9tQgYvTH:bz6cib3) ([raw file](https://github.com/harness/harness-core/blob/bb10296eb7ebec649a9e60ac80bbb0165d66cc06/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java#L119)):*
> ```Java
>         io.harness.artifact.ArtifactMetadataKeys.artifactPath, awsS3ArtifactDelegateConfig.getArtifactPath());
>     artifactMetadata.put(ArtifactMetadataKeys.artifactName,
>         Paths.get(awsS3ArtifactDelegateConfig.getArtifactPath()).getFileName().toString());
> ```

are `fileName` and `artifactPath` always present? Shall we validate those to avoid NP?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/AwsS3ArtifactDownloadHandler.java` line 145 at r5](https://reviewable.io/reviews/harness/harness-core/37748#-NCYvlXTAQzTtL8Ab8pA:-NCYvlXUD2g6tg8udHb9:b-4inp87) ([raw file](https://github.com/harness/harness-core/blob/bb10296eb7ebec649a9e60ac80bbb0165d66cc06/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/AwsS3ArtifactDownloadHandler.java#L145)):*
> ```Java
>   }
> 
>   private void initBucketRegions() {
> ```

gov cloud regions are missing.

**Comment by vladimir-peric** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java` line 79 at r5](https://reviewable.io/reviews/harness/harness-core/37748#-NCYtE1S0EXsVCN0iCmT:-NCZ7lr_DXYMGR2PQ2yn:b-ovr59z) ([raw file](https://github.com/harness/harness-core/blob/bb10296eb7ebec649a9e60ac80bbb0165d66cc06/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java#L79)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

same here
</blockquote></details>

as this method is called within try/catch of the above one I removed try/catch block in it

**Comment by vladimir-peric** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java` line 101 at r5](https://reviewable.io/reviews/harness/harness-core/37748#-NCYtAtRDkJgWAL17WiM:-NCZ7vvR7asmeJaolcPr:b-ovr59z) ([raw file](https://github.com/harness/harness-core/blob/bb10296eb7ebec649a9e60ac80bbb0165d66cc06/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java#L101)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

same, exception with hint and explanation
</blockquote></details>

as this method is called within try/catch of the above one I removed try/catch block in it

**Comment by vladimir-peric** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java` line 119 at r5](https://reviewable.io/reviews/harness/harness-core/37748#-NCYtMnCDP8h9tQgYvTG:-NCZ7zsT8VRC4rQXmLuU:bsrtlz2) ([raw file](https://github.com/harness/harness-core/blob/bb10296eb7ebec649a9e60ac80bbb0165d66cc06/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java#L119)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

are `fileName` and `artifactPath` always present? Shall we validate those to avoid NP?
</blockquote></details>

They are mandatory when defining artefact in ui, but to be on safe side I will validate them either way

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37748)* status: 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java` line 44 at r5](https://reviewable.io/reviews/harness/harness-core/37748#-NCYsw6K1TPwWd_Piq4t:-NCZ7ibM3ixX-J6MbV7b:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bb10296eb7ebec649a9e60ac80bbb0165d66cc06/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java#L44)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

we need to throw exception with hint and explanation, don't hide the in logs only.
</blockquote></details>

Done.



_Code quote:_
```Java
log.error(format("Error while fetching S3 artifact: %s", e.getMessage()));
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java` line 57 at r5](https://reviewable.io/reviews/harness/harness-core/37748#-NCYt2aLD0dQy0n4H6Dw:-NCZ7kLT13NOhYEa7cfo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bb10296eb7ebec649a9e60ac80bbb0165d66cc06/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java#L57)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

same here, we need to throw exception with hint and explanation, don't hide the in logs only.
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/AwsS3ArtifactDownloadHandler.java` line 145 at r5](https://reviewable.io/reviews/harness/harness-core/37748#-NCYvlXTAQzTtL8Ab8pA:-NCZF8jbDu8kcZGwe8Ag:bwslb6j) ([raw file](https://github.com/harness/harness-core/blob/bb10296eb7ebec649a9e60ac80bbb0165d66cc06/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/AwsS3ArtifactDownloadHandler.java#L145)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

gov cloud regions are missing. 
</blockquote></details>

added all that are missing, compared to aws docs



_Code quote (from 930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java):_
```Java
private void updateArtifactMetadata(SshExecutorFactoryContext context) throws IOException {
```

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37748)* status: 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java` line 128 at r6](https://reviewable.io/reviews/harness/harness-core/37748#-NCZMgzf-xibZbJ7Dcd1:-NCZMgzf-xibZbJ7Dcd2:bxlzdpu) ([raw file](https://github.com/harness/harness-core/blob/014a2da9b3e49b15bce1bc6cafd46aa1c68ec6db/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java#L128)):*
> ```Java
>         (AwsS3ArtifactDelegateConfig) context.getArtifactDelegateConfig();
>     if (isEmpty(awsS3ArtifactDelegateConfig.getArtifactPath())) {
>       throw new IOException("Artifact path is not provided");
> ```

why IOException? i would expect here all the exceptions to be with hint and explanation. If this is mandatory and we cannot have it null, then there is no need to perform that check.

**Comment by vladimir-peric** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java` line 128 at r6](https://reviewable.io/reviews/harness/harness-core/37748#-NCZMgzf-xibZbJ7Dcd1:-NCZO-sPC6NIe4mocRuN:bgwo0jx) ([raw file](https://github.com/harness/harness-core/blob/014a2da9b3e49b15bce1bc6cafd46aa1c68ec6db/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AwsS3ArtifactCommandUnitHandler.java#L128)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

why IOException? i would expect here all the exceptions to be with hint and explanation. If this is mandatory and we cannot have it null, then there is no need to perform that check.
</blockquote></details>

My bad, wanted InvalidRequestException instead. But you're right, we can skip the check here as artifact path is mandatory anyway.

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 3 of 11 files at r1, 1 of 8 files at r2, 1 of 6 files at r3, 4 of 9 files at r4, 3 of 9 files at r5, 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37748)* status: 1. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37748)* status: :shipit: complete! ✓

**Comment by vladimir-peric** [comment]
trigger codebasehash

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 3 of 11 files at r1, 1 of 8 files at r2, 1 of 6 files at r3, 4 of 9 files at r4, 6 of 9 files at r5, 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37748)* status: :shipit: complete! ✓

**Pull request merged**
