### PR TITLE
fix: [DEL-4213]: fetch delegateImageTag from versionOverride for upgr…

### PR DESCRIPTION
**Pull request by arpit3107**
…ader

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33909)

### CODE REVIEW

**Review by mdmilic — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33909)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33909)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateUpgraderServiceImpl.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/33909#-N3eTbGuDdNxjRCus-pn:-N3eTbGuDdNxjRCus-po:b-8ck7zb) ([raw file](https://github.com/harness/harness-core/blob/facb974dd3e4f1cfc29219a910ed0b26b759cf51/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateUpgraderServiceImpl.java#L37)):*
> ```Java
>   public UpgradeCheckResult getDelegateImageTag(String accountId, String currentDelegateImageTag) {
>     String newDelegateImageTag = delegateVersionService.getDelegateImageTag(accountId, DelegateType.KUBERNETES);
>     boolean shouldUpgrade = !currentDelegateImageTag.equals(newDelegateImageTag);
> ```

final boolean



_Code quote:_
```Java
boolean
```
___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateUpgraderServiceImpl.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/33909#-N3eTe8CCiD9T38OOaB8:-N3eTe8CCiD9T38OOaB9:b-8ck7zb) ([raw file](https://github.com/harness/harness-core/blob/facb974dd3e4f1cfc29219a910ed0b26b759cf51/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateUpgraderServiceImpl.java#L44)):*
> ```Java
>   public UpgradeCheckResult getUpgraderImageTag(String accountId, String currentUpgraderImageTag) {
>     String newUpgraderImageTag = delegateVersionService.getUpgraderImageTag(accountId, DelegateType.KUBERNETES);
>     boolean shouldUpgrade = !currentUpgraderImageTag.equals(newUpgraderImageTag);
> ```

final boolean

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33909)* status: :shipit: complete! ✓

**Review by Vbhatia20 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33909)* status: :shipit: complete! ✓

**Pull request merged**
