### PR TITLE
[fix]: [DEL-3252]: change default CPU to 1 for docker delegate

### PR DESCRIPTION
**Pull request by AnupamIO**
- Change default CPU to 1 for docker delegate
- Change in UI would be needed, change description of default CPU.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34394)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34394)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/resources/delegatesizes/default_community_size.json` line 4 at r1](https://reviewable.io/reviews/harness/harness-core/34394#-N4g27Dl0DBybJJ6SpxJ:-N4g27Dl0DBybJJ6SpxK:b-tj62ji) ([raw file](https://github.com/harness/harness-core/blob/7c7ef0680c773a81eefebefb6c5de806d8ed42d9/400-rest/src/main/resources/delegatesizes/default_community_size.json#L4)):*
> ```JSON
>   "label" : "Default Community Size",
>   "taskLimit" : "50",
>   "ram" : "768",
> ```

will this work ? 768MB is too less, what is the xmx in this case ?
___
*[`400-rest/src/main/resources/delegatesizes/default_size.json` line 5 at r1](https://reviewable.io/reviews/harness/harness-core/34394#-N4g2JUa4wdgRgg2I_Pm:-N4g2JUa4wdgRgg2I_Pn:b8dkilm) ([raw file](https://github.com/harness/harness-core/blob/7c7ef0680c773a81eefebefb6c5de806d8ed42d9/400-rest/src/main/resources/delegatesizes/default_size.json#L5)):*
> ```JSON
>   "taskLimit" : "50",
>   "ram" : "2048",
>   "cpu" : "1"
> ```

when do we use this file ? is it for both ng/cg ?



_Code quote:_
```JSON
"1"
```

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34394)* status: Some of the checks are too old. 1 change requests.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34394)* status: Some of the checks are too old. 1 change requests. 2. unresolved discussions. 

___
*[`400-rest/src/main/resources/delegatesizes/default_size.json` line 5 at r1](https://reviewable.io/reviews/harness/harness-core/34394#-N4g2JUa4wdgRgg2I_Pm:-N5990Ck-FhYO1SEuc1X:b-455emk) ([raw file](https://github.com/harness/harness-core/blob/7c7ef0680c773a81eefebefb6c5de806d8ed42d9/400-rest/src/main/resources/delegatesizes/default_size.json#L5)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

when do we use this file ? is it for both ng/cg ?
</blockquote></details>

This is for ng docker delegates. For cg i don't see any CPU configuration in shell script we use: https://github.com/harness/harness-core/blob/develop/400-rest/src/main/resources/delegatetemplates/launch-harness-delegate.sh.ftl probably it is configured by user only.

**Review by gaurav-jain1 — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34394)* status: Some of the checks are too old. 

___
*[`400-rest/src/main/resources/delegatesizes/default_community_size.json` line 4 at r1](https://reviewable.io/reviews/harness/harness-core/34394#-N4g27Dl0DBybJJ6SpxJ:-N59VuIa4cgNfWloqbV8:b-pp40ku) ([raw file](https://github.com/harness/harness-core/blob/7c7ef0680c773a81eefebefb6c5de806d8ed42d9/400-rest/src/main/resources/delegatesizes/default_community_size.json#L4)):*
> se of community and docker delegate is same at 512 
Ok, thanks for identifying this

**Comment by AnupamIO** [comment]
trigger messagecheck

**Review by amitsh14 — APPROVED** [review]

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34394)* status: 1 file(s) to review. 

___
*[`400-rest/src/main/resources/delegatesizes/default_size.json` line 5 at r1](https://reviewable.io/reviews/harness/harness-core/34394#-N4g2JUa4wdgRgg2I_Pm:-N5FLRSL4p7xdq6Bj940:b-lcvts1) ([raw file](https://github.com/harness/harness-core/blob/7c7ef0680c773a81eefebefb6c5de806d8ed42d9/400-rest/src/main/resources/delegatesizes/default_size.json#L5)):*
>  for ng docker delegates. For cg i don't see any CPU configuration in shell script
For NG today we use 0.5 cpu for all delegate types, I think we do have plan to make config similar to CG, @raghuatwings

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34394)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34394)* status: Some of the checks are too old.

**Comment by AnupamIO** [comment]
trigger ti3

**Pull request merged**
