### PR TITLE
feat: [CDS-40868]: Support delete source branch option for azurerepo/github

### PR DESCRIPTION
**Pull request by rohitk-h**
…thub

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36756)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36756)

**Comment by rohitk-h** [comment]
trigger compile, ft1, ft2

**Comment by rohitk-h** [comment]
trigger ti2

**Comment by rohitk-h** [comment]
trigger compile

**Comment by GabeAboy** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GithubApiClient.java` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/36756#-NAKXEDi2XhXcr_m03K9:-NAKXEDi2XhXcr_m03KA:b-mno62t) ([raw file](https://github.com/harness/harness-core/blob/ead7148ebf69e9dc1704b80df6c604cecd782300/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GithubApiClient.java#L148)):*
> ```Java
>       boolean success = githubService.deleteRef(gitApiURL, token, gitApiTaskParams.getOwner(), repo, ref);
>       if (!success) {
>         String err = format("Failed to delete reference %s", ref);
> ```

I think we should display repo, just encase we see this happening we can trace back to the connector. Similar to the catch below.

**Review by GabeAboy — COMMENTED** [review]
> Reviewed 12 of 15 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36756)* status: 0 of 1 approvals obtained.

**Comment by rohitk-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GithubApiClient.java` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/36756#-NAKXEDi2XhXcr_m03K9:-NAL4L0c6s_sKmz2TvGy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ead7148ebf69e9dc1704b80df6c604cecd782300/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GithubApiClient.java#L148)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

I think we should display repo, just encase we see this happening we can trace back to the connector. Similar to the catch below.
</blockquote></details>

Done.

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 12 of 15 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36756)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained.

**Comment by rohitk-h** [comment]
trigger codebasehash

**Review by GabeAboy — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36756)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 12 of 15 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36756)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
trigger codebasehash

**Pull request merged**
