### PR TITLE
[fix]: [CDS-33905]: Terraform sweeping output vars available at pipeline level also

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31033)

### CODE REVIEW

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31033)* status: 4 file(s) to review. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java, line 486 at r2](https://reviewable.io/reviews/harness/harness-core/31033#-MwzYwLHBrTA4WEt-5nZ:-MwzYwLHBrTA4WEt-5n_:bkoxsw4) ([raw file](https://github.com/harness/harness-core/blob/71cf30b792cddd9f8d8cff8300a93b34ab2b8efe/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L486)):*
> ```Java
>     sweepingOutputService.save(
>         context.prepareSweepingOutputBuilder(SweepingOutputInstance.Scope.PIPELINE)
>             .name(TerraformOutputVariables.SWEEPING_OUTPUT_NAME + phaseElement.getInfraDefinitionId()
> ```

nit: add "/"

**Comment by arvind-choudhary-h** [comment]
trigger messagecheck

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31033)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31033)* status: :shipit: complete! ✓

**Pull request merged**
