### PR TITLE
[fix]: [CDS-4003]: added SINGLE_MANIFEST_SUPPORT and associated unit tests

### PR DESCRIPTION
**Pull request by vaibhav-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31512)

### CODE REVIEW

**Review by anilchowdhury-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31512)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java, line 708 at r1](https://reviewable.io/reviews/harness/harness-core/31512#-MyHf5cR3KthCAhGKTKt:-MyHf5cR3KthCAhGKTKu:b6fjh64) ([raw file](https://github.com/harness/harness-core/blob/1c09312d7accf0ca0d714c77f3bc9ec991071ff2/400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java#L708)):*
> ```Java
>   }
> 
>   @SuppressWarnings("checkstyle:UselessSingleCatch")
> ```

what is this suppresswarning for ?

**Comment by arvind-choudhary-h** [comment]
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/pcf/response/CFDeploymentData.java, line 13 at r1](https://reviewable.io/reviews/harness/harness-core/31512#-MyLSlUWA1f8C8bf0aMi:-MyLSlUWA1f8C8bf0aMj:be3ta95) ([raw file](https://github.com/harness/harness-core/blob/1c09312d7accf0ca0d714c77f3bc9ec991071ff2/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/pcf/response/CFDeploymentData.java#L13)):*
> ```Java
> @Data
> @Builder
> public class CFDeploymentData {
> ```

CFManifestDataInfo should be better. It doesn't have complete deployment data and could be confusing.

**Comment by arvind-choudhary-h** [comment]
___
*[400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java, line 517 at r1](https://reviewable.io/reviews/harness/harness-core/31512#-MyLUR8_-BKWMQCoH7ps:-MyLUR8_-BKWMQCoH7pt:b38g2i2) ([raw file](https://github.com/harness/harness-core/blob/1c09312d7accf0ca0d714c77f3bc9ec991071ff2/400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java#L517)):*
> ```Java
>     boolean autoscalarManifestFound = false;
> 
>     List<K8sValuesLocation> k8sValuesLocationsOrder = new ArrayList<K8sValuesLocation>() {
> ```

this is static - can extract out to class level.

**Comment by arvind-choudhary-h** [comment]
___
*[400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java, line 487 at r1](https://reviewable.io/reviews/harness/harness-core/31512#-MyLUn7L2Ev_f-JmjsGb:-MyLUn7L2Ev_f-JmjsGc:bmt5i3i) ([raw file](https://github.com/harness/harness-core/blob/1c09312d7accf0ca0d714c77f3bc9ec991071ff2/400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java#L487)):*
> ```Java
>           int numManifests = manifestMap.get(k8sValuesLocation).get(manifestType).size();
>           if (numManifests > 1) {
>             throw new GeneralException("Multiple manifest files found");
> ```

can improve this message to include manifestType / k8sValuesLocation / manifest count. like how many did you find.

**Comment by arvind-choudhary-h** [comment]
___
*[400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java, line 532 at r1](https://reviewable.io/reviews/harness/harness-core/31512#-MyLV2eQ6ngUNICSbFz8:-MyLV2eQ6ngUNICSbFz9:b-83cfsz) ([raw file](https://github.com/harness/harness-core/blob/1c09312d7accf0ca0d714c77f3bc9ec991071ff2/400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java#L532)):*
> ```Java
>                   validateSingleManifestAtGivenLevel(k8sValuesLocation, APPLICATION_MANIFEST, cfDeploymentData);
>         } catch (GeneralException ex) {
>           logCallback.saveExecutionLog(MULTIPLE_APPLICATION_MANIFEST_MESSAGE, ERROR, CommandExecutionStatus.FAILURE);
> ```

And here, can directly get ex -> message(). It will help used find at what level.

**Comment by arvind-choudhary-h** [comment]
___
*[400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java, line 540 at r1](https://reviewable.io/reviews/harness/harness-core/31512#-MyLVHPL6B3ObOJnTVm_:-MyLVHPL6B3ObOJnTVma:b-vt7ikv) ([raw file](https://github.com/harness/harness-core/blob/1c09312d7accf0ca0d714c77f3bc9ec991071ff2/400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java#L540)):*
> ```Java
>         try {
>           autoscalarManifestFound =
>                   validateSingleManifestAtGivenLevel(k8sValuesLocation, AUTOSCALAR_MANIFEST, cfDeploymentData);
> ```

similarly here.

**Comment by arvind-choudhary-h** [comment]
___
*[400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java, line 502 at r1](https://reviewable.io/reviews/harness/harness-core/31512#-MyLVZx37LqucZu47ogZ:-MyLVZx37LqucZu47og_:b43guyx) ([raw file](https://github.com/harness/harness-core/blob/1c09312d7accf0ca0d714c77f3bc9ec991071ff2/400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java#L502)):*
> ```Java
>     String manifestYml = pcfManifestsPackage.getManifestYml();
>     try {
>       notNullCheck(INVALID_MANIFEST_MESSAGE, manifestYml);
> ```

We can use either this logic or above one. We don't need both of these. I think for that, we can extract out FF check from inside validateSingleManifestPresent to this method with if else block..

**Comment by arvind-choudhary-h** [comment]
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/pcf/response/CFDeploymentData.java, line 16 at r1](https://reviewable.io/reviews/harness/harness-core/31512#-MyLVwTFDJ4OUPiwr8cV:-MyLVwTFDJ4OUPiwr8cW:b-8abn1d) ([raw file](https://github.com/harness/harness-core/blob/1c09312d7accf0ca0d714c77f3bc9ec991071ff2/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/pcf/response/CFDeploymentData.java#L16)):*
> ```Java
>     private Map<K8sValuesLocation, Map<ManifestType, List<String>>> manifestMap;
>     private String applicationManifestFilePath;
>     private String autoscalarManifestFilePath;
> ```

Will it be helpful @vaibhav-harness / @anilchowdhury-harness to include all file paths for var files? In order..

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31512)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Comment by arvind-choudhary-h** [comment]
___
*[400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java, line 593 at r1](https://reviewable.io/reviews/harness/harness-core/31512#-MyLWOFk1sfqX7yuRslm:-MyLWOFk1sfqX7yuRsln:b2wppzi) ([raw file](https://github.com/harness/harness-core/blob/1c09312d7accf0ca0d714c77f3bc9ec991071ff2/400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java#L593)):*
> ```Java
>   }
> 
>   private void validateInlineFiles(
> ```

Could you please add some doc above this method like what is the purpose of this, why are we doing.. In future, this could help to understand the purpose

**Comment by arvind-choudhary-h** [comment]
___
*[400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java, line 497 at r1](https://reviewable.io/reviews/harness/harness-core/31512#-MyLWcuiAqBCdPD7w877:-MyLWcuiAqBCdPD7w878:b-4s9sww) ([raw file](https://github.com/harness/harness-core/blob/1c09312d7accf0ca0d714c77f3bc9ec991071ff2/400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java#L497)):*
> ```Java
>   }
> 
>   public void validateManifest(PcfManifestsPackage pcfManifestsPackage, LogCallback logCallback, String accountId, CFDeploymentData cfDeploymentData) {
> ```

Could you please add some doc above this method too like what is the purpose of this, why are we doing..

**Comment by arvind-choudhary-h** [comment]
___
*[400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java, line 460 at r1](https://reviewable.io/reviews/harness/harness-core/31512#-MyLX6t1CFDeVvlh11b-:-MyLX6t1CFDeVvlh11b0:bjypgi4) ([raw file](https://github.com/harness/harness-core/blob/1c09312d7accf0ca0d714c77f3bc9ec991071ff2/400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java#L460)):*
> ```Java
>     PcfManifestsPackage pcfManifestsPackage = PcfManifestsPackage.builder().build();
> 
>     ApplicationManifest applicationManifest = appManifestMap.get(K8sValuesLocation.Service);
> ```

nit: As we have defined `k8sValuesLocationsOrder`, we can use the same order in reverse here. This will make sure some change in order is used in both the methods - `getFinalManifestFilesMap` and `validateSingleManifestPresent`

**Comment by arvind-choudhary-h** [comment]
___
*[400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java, line 517 at r1](https://reviewable.io/reviews/harness/harness-core/31512#-MyLXRXC9hC7RlSs7RUc:-MyLXRXC9hC7RlSs7RUd:buky3co) ([raw file](https://github.com/harness/harness-core/blob/1c09312d7accf0ca0d714c77f3bc9ec991071ff2/400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java#L517)):*
> ```Java
>     boolean autoscalarManifestFound = false;
> 
>     List<K8sValuesLocation> k8sValuesLocationsOrder = new ArrayList<K8sValuesLocation>() {
> ```

nit: Can rename this.

**Pull request closed without merging**
