### PR TITLE
feat: [CDS-46072]: Add support for environment variables for GitOps

### PR DESCRIPTION
**Pull request by rohitk-h**
## Describe your changes
- With Multi Service and Multi Infra Deployments, the gitops worksflows need special handling for resolving environment variables. This is because there no environment outcome is produced in GitOps Case. 
- In this change, for environments and environment group for gitops enabled stage we merge the envInputs across all environments and finally merge the variables that were resolved part of service/environments and service overrides within environments. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40097)

### CODE REVIEW

**Comment by rohitk-h** [comment]
trigger feature-build

**Comment by abhayganvir** [comment]
trigger checkstylecodeformat

**Comment by rohitk-h** [comment]
trigger feature-build

**Comment by rohitk-h** [comment]
trigger feature-build

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java` line 112 at r3](https://reviewable.io/reviews/harness/harness-core/40097#-NGr0LlqBM6Jabw-ggB2:-NGr0LlqBM6Jabw-ggB3:b-70g355) ([raw file](https://github.com/harness/harness-core/blob/b0c867ffc3a050a3605c922d31a2924ac3f6aeb3/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java#L112)):*
> ```Java
>             .inputs(finalServiceYaml.getServiceInputs())
>             .envGroupRef(environmentGroupYaml.getEnvGroupRef())
>             .envRefs(environmentGroupYaml.getEnvironments()
> ```

environmentGroupYaml.getEnvironments() might be null right ? if deployToAll is true

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 196 at r3](https://reviewable.io/reviews/harness/harness-core/40097#-NGrdJuM4v2y0Q90SGSQ:-NGrdJuM4v2y0Q90SGSR:b-z8lfgq) ([raw file](https://github.com/harness/harness-core/blob/b0c867ffc3a050a3605c922d31a2924ac3f6aeb3/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L196)):*
> ```Java
> 
>     for (ParameterField<String> env : parameters.getEnvRefs()) {
>       Optional<Environment> environment = getEnvironmentFromEnvRef(ambiance, env.getValue());
> ```

can we club multiple DB calls into 1 single DB call or use HIterator<..> instead ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 202 at r3](https://reviewable.io/reviews/harness/harness-core/40097#-NGre-bCE5cvfpnSiBI6:-NGre-bCE5cvfpnSiBI7:b-7d86av) ([raw file](https://github.com/harness/harness-core/blob/b0c867ffc3a050a3605c922d31a2924ac3f6aeb3/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L202)):*
> ```Java
>       if (isEmpty(environment.get().getYaml())) {
>         getNGEnvironmentConfig(environment.get());
>       }
> ```

we can directly use environment.get().fetchNonEmptyYaml(..) method here

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 200 at r3](https://reviewable.io/reviews/harness/harness-core/40097#-NGre7dLEbbzmOs8WeZU:-NGre7dLEbbzmOs8WeZV:b-b1poab) ([raw file](https://github.com/harness/harness-core/blob/b0c867ffc3a050a3605c922d31a2924ac3f6aeb3/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L200)):*
> ```Java
>       NGEnvironmentConfig ngEnvironmentConfig;
>       // handle old environments
>       if (isEmpty(environment.get().getYaml())) {
> ```

what happens here if the environment is not found or env.getValue() is not resolved ( maybe an expression )

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 206 at r3](https://reviewable.io/reviews/harness/harness-core/40097#-NGrfObw-SHUSqqRXrfa:-NGrfObw-SHUSqqRXrfb:baklkv0) ([raw file](https://github.com/harness/harness-core/blob/b0c867ffc3a050a3605c922d31a2924ac3f6aeb3/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L206)):*
> ```Java
>       try {
>         ngEnvironmentConfig =
>             mergeEnvironmentInputs(environment.get().getYaml(), parameters.getEnvToEnvInputs().get(env.getValue()));
> ```

do we need to check for the case when there are no inputs present some environment ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40097)* status: 3 file(s) to review. 0 of 1 approvals obtained.

**Review by rohitk-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40097)* status: 3 file(s) to review. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java` line 112 at r3](https://reviewable.io/reviews/harness/harness-core/40097#-NGr0LlqBM6Jabw-ggB2:-NGyy_CR41HVWGc7sXcF:bmf1pdr) ([raw file](https://github.com/harness/harness-core/blob/b0c867ffc3a050a3605c922d31a2924ac3f6aeb3/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java#L112)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

environmentGroupYaml.getEnvironments() might be null right ? if deployToAll is true 
</blockquote></details>

Even if deployToAll is true, environmentGroupYaml.getEnvironments() has the list of environments
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 196 at r3](https://reviewable.io/reviews/harness/harness-core/40097#-NGrdJuM4v2y0Q90SGSQ:-NGyyglk6HEGyu4_KD3u:broubdk) ([raw file](https://github.com/harness/harness-core/blob/b0c867ffc3a050a3605c922d31a2924ac3f6aeb3/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L196)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we club multiple DB calls into 1 single DB call or use HIterator<..> instead ?
</blockquote></details>

Yes, done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 200 at r3](https://reviewable.io/reviews/harness/harness-core/40097#-NGre7dLEbbzmOs8WeZU:-NGyyjCP0Ij4dpNj2TZ_:b66jpz9) ([raw file](https://github.com/harness/harness-core/blob/b0c867ffc3a050a3605c922d31a2924ac3f6aeb3/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L200)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

what happens here if the environment is not found or env.getValue() is not resolved ( maybe an expression )
</blockquote></details>

I am able to make the environments as an expression, it can either be a fixed value of runtime input. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 202 at r3](https://reviewable.io/reviews/harness/harness-core/40097#-NGre-bCE5cvfpnSiBI6:-NGyysSn9OdFuBP3WTCw:b95idi2) ([raw file](https://github.com/harness/harness-core/blob/b0c867ffc3a050a3605c922d31a2924ac3f6aeb3/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L202)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we can directly use environment.get().fetchNonEmptyYaml(..) method here
</blockquote></details>

Now, directly iterating over environments, so this is not needed. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 206 at r3](https://reviewable.io/reviews/harness/harness-core/40097#-NGrfObw-SHUSqqRXrfa:-NGyyyk66EyqhF9Dk3Of:b3tzxk5) ([raw file](https://github.com/harness/harness-core/blob/b0c867ffc3a050a3605c922d31a2924ac3f6aeb3/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L206)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need to check for the case when there are no inputs present some environment ?
</blockquote></details>

In case no envInputs are present for the environment then `mergeEnvironmentInputs` returns original yaml 
Ref: io/harness/cdng/service/steps/ServiceStepV3.java:510

**Comment by rohitk-h** [comment]
trigger feature-build

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java` line 368 at r6](https://reviewable.io/reviews/harness/harness-core/40097#-NH4zY9ICpi1ZeHdQsFl:-NH4zY9ICpi1ZeHdQsFm:b-6gdass) ([raw file](https://github.com/harness/harness-core/blob/7aec57a273fa49a4ee729c6719804a35315bf6e8/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java#L368)):*
> ```Java
>       }
>       if (isNotEmpty(svcVariables) && !envSvcOverrideVars.values().isEmpty()
>           && envSvcOverrideVars.get(clusterInternal.getEnvRef()) != null) {
> ```

do we need the condition of svcVariables != empty here?

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 1 of 1 files at r3, 2 of 3 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40097)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 202 at r6](https://reviewable.io/reviews/harness/harness-core/40097#-NH4zoTu6SEFdsU3-FMa:-NH4zoTu6SEFdsU3-FMb:b-t0jd3o) ([raw file](https://github.com/harness/harness-core/blob/7aec57a273fa49a4ee729c6719804a35315bf6e8/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L202)):*
> ```Java
>     }
> 
>     List<Environment> environments = getEnvironmentFromEnvRef(ambiance, parameters.getEnvRefs());
> ```

nit: name should be getEnvironments(..)

**Review by rohitk-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40097)* status: 3 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java` line 125 at r6](https://reviewable.io/reviews/harness/harness-core/40097#-NH50VX34y_-BFFyVTGz:-NHIlB4sA8a_IAJKp_pT:bqnv4sd) ([raw file](https://github.com/harness/harness-core/blob/7aec57a273fa49a4ee729c6719804a35315bf6e8/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java#L125)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

1 thing to note here: 
the way we are using resolve here, it will make 1 API call for each expression field in the input which can be expensive
IMO we should take this up separately but we should definitely take this up

The expression evaluator can also evaluate 1 object at a time, so unless its too big, we can pass the entire svcVariables to EngineExpressionService
</blockquote></details>

+1, created ticket: https://harness.atlassian.net/browse/CDS-46876
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java` line 368 at r6](https://reviewable.io/reviews/harness/harness-core/40097#-NH4zY9ICpi1ZeHdQsFl:-NHIlobw1AwCTqnrsX_Z:bsxg9ig) ([raw file](https://github.com/harness/harness-core/blob/7aec57a273fa49a4ee729c6719804a35315bf6e8/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java#L368)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need the condition of svcVariables != empty here?
</blockquote></details>

good catch, it is not needed, 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 202 at r6](https://reviewable.io/reviews/harness/harness-core/40097#-NH4zoTu6SEFdsU3-FMa:-NHIlufN-YLLHc4sBzBg:boac9c8) ([raw file](https://github.com/harness/harness-core/blob/7aec57a273fa49a4ee729c6719804a35315bf6e8/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L202)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: name should be getEnvironments(..)
</blockquote></details>

updated.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40097)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
trigger feature-build

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 4 of 8 files at r1, 2 of 3 files at r5, 1 of 4 files at r6, 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40097)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40097)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]

**Pull request merged**
