### PR TITLE
[feat]: [SPG-872]: Merge openAPI scripts added to harness-core

### PR DESCRIPTION
**Pull request by mankrit-singh**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40188)

### CODE REVIEW

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40188)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`scripts/api/x-tags.yaml` line 1 at r2](https://reviewable.io/reviews/harness/harness-core/40188#-NGz29igDRRmPu8EvEnB:-NGz29igDRRmPu8EvEnC:b-5my4rx) ([raw file](https://github.com/harness/harness-core/blob/898a6554bef3824f4bf832d9547eabb702174559/scripts/api/x-tags.yaml#L1)):*
> ```YAML
> - name: Organization
> ```

curious, why xtags needs to be maintained independently? The merge tool doesn't merge them?

**Comment by mankrit-singh** [comment]
*[`scripts/api/x-tags.yaml` line 1 at r2](https://reviewable.io/reviews/harness/harness-core/40188#-NGz29igDRRmPu8EvEnB:-NGz3B5Y6a_Vj_FQ0VmW:b-43w9iy) ([raw file](https://github.com/harness/harness-core/blob/898a6554bef3824f4bf832d9547eabb702174559/scripts/api/x-tags.yaml#L1)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

curious, why xtags needs to be maintained independently? The merge tool doesn't merge them?
</blockquote></details>

it doesn't. x-tags are some add on feature not natively supported in merge tool.

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40188)* status: 9 file(s) to review.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40188)* status: :shipit: complete! ✓

**Pull request merged**
