### PR TITLE
[feat]: [CDS-79678]: Integrated the get file flow with gitx webhooks

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added code to integrate the get file flow with the gitx webhooks. Have tested the following:
1. Pipeline with the webhook configured, get pipeline flow -> only cache is being used
2. Pipeline with the webhook configured, run pipeline flow -> only cache is being used
3. Pipeline without the webhook configured, get pipeline flow -> only cache is being used based on the header param
4. Pipeline without the webhook configured, run pipeline flow -> remote call is made

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53198)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger uts

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53198)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1042 at r4](https://reviewable.io/reviews/harness/harness-core/53198#-Nex1yzABAZ2qrXzZmkv:-Nex1yzABAZ2qrXzZmkw:btdoy78) ([raw file](https://github.com/harness/harness-core/blob/d20491c007096f6d994e084475849975762af671/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1042)):*
> ```Java
>       }
>     }
>     if (isUseCache(matchingFolderPaths, scmGetFileByBranchRequestDTO.isUseCache())) {
> ```

The whole logic to use cache or not for bi directional sync should be encapsulated inside a single method. The method should be simply integrated here to use.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53198)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1042 at r4](https://reviewable.io/reviews/harness/harness-core/53198#-Nex1yzABAZ2qrXzZmkv:-NexfCviDm0Gs8KhUyj9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d20491c007096f6d994e084475849975762af671/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1042)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The whole logic to use cache or not for bi directional sync should be encapsulated inside a single method. The method should be simply integrated here to use.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1057 at r4](https://reviewable.io/reviews/harness/harness-core/53198#-Nex1BXu24uf-Mj0loEp:-NexdDE8DL0d7AezRNOv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d20491c007096f6d994e084475849975762af671/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1057)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

method name should be "shouldUseCache"
</blockquote></details>

Done.

**Comment by adivishy1** [comment]
trigger uts

**Review by mohitg0795 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53198)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Comment by adivishy1** [comment]
trigger ut2, ut4

**Pull request merged**
