### PR TITLE
fix: [CDS-77685]: UI issues for Timespent beside steps showing wrong …

### PR DESCRIPTION
**Pull request by prashantsharma04**
…timings (all in miliseconds) & Pipeline execution inputs not showing all enviornments

## Describe your changes

**Problem**: During retry of pipeline, the service info was not getting displayed. This was happening only when non-retried stage is a multi-service stage.

**Fix**: For multiservice stage or matrix stage, we have a different Identity step: `IdentityStrategyInternalStep`.
Here in `testHandleChildrenResponse`, the outcomes save code was missing.

Testing: Have tested in local.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52627)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Comment by prashantsharma04** [comment]
triggger uts

**Comment by prashantsharma04** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52627)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java` line 143 at r2](https://reviewable.io/reviews/harness/harness-core/52627#-Ne1sd5X1QT8FdI-Ipl7:-Ne1sd5X1QT8FdI-Ipl8:b-u8fqwc) ([raw file](https://github.com/harness/harness-core/blob/67388ab322be838ec8583c336397a0ecb8a80b6c/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java#L143)):*
> ```Java
>   public StepResponse handleChildrenResponse(
>       Ambiance ambiance, IdentityStepParameters identityParams, Map<String, ResponseData> responseDataMap) {
>     NodeExecution originalNodeExecution = nodeExecutionService.get(identityParams.getOriginalNodeExecutionId());
> ```

why do you need get here?

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52627)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java` line 143 at r2](https://reviewable.io/reviews/harness/harness-core/52627#-Ne1sd5X1QT8FdI-Ipl7:-Ne1vbGrDcdL9oa8gfvB:b-tamqih) ([raw file](https://github.com/harness/harness-core/blob/67388ab322be838ec8583c336397a0ecb8a80b6c/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java#L143)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do you need get here?
</blockquote></details>

This is to copy the outcomes of the steps/ stage which is not actually running in retry pipeline.

Matrix/Multi-service nodes are executed via IdentityStrategyInternalStep

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger uts

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52627)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java` line 143 at r2](https://reviewable.io/reviews/harness/harness-core/52627#-Ne1sd5X1QT8FdI-Ipl7:-Ne2o0tt-kzyEZmgC1tn:b-rm2pl1) ([raw file](https://github.com/harness/harness-core/blob/67388ab322be838ec8583c336397a0ecb8a80b6c/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java#L143)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

This is to copy the outcomes of the steps/ stage which is not actually running in retry pipeline.

Matrix/Multi-service nodes are executed via IdentityStrategyInternalStep
</blockquote></details>

Have removed nodeExecution get call

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52627)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/52627#-Ne3FdUl7sTMMKUvh-in:-Ne3FdUl7sTMMKUvh-io:bm5100z) ([raw file](https://github.com/harness/harness-core/blob/1359902dad12dcd73eccf3ccf36777c40506fe66/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java#L63)):*
> ```Java
>     NodeExecution originalNodeExecution =
>         nodeExecutionService.getWithFieldsIncluded(identityParams.getOriginalNodeExecutionId(),
>             Sets.newHashSet(NodeExecution.NodeExecutionKeys.uuid, NodeExecution.NodeExecutionKeys.status));
> ```

why is uuid needed in get? you already have uuid, just use getStatus method
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/52627#-Ne3FiD59CYszy3VnQvc:-Ne3FiD59CYszy3VnQvd:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/1359902dad12dcd73eccf3ccf36777c40506fe66/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java#L82)):*
> ```Java
>       Ambiance ambiance, IdentityStepParameters identityParams, Map<String, ResponseData> responseDataMap) {
>     NodeExecution originalNodeExecution =
>         nodeExecutionService.getWithFieldsIncluded(identityParams.getOriginalNodeExecutionId(),
> ```

same as above

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52627)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/52627#-Ne3FdUl7sTMMKUvh-in:-Ne7JUxJ9p5tj02dDtsE:b-sxnt15) ([raw file](https://github.com/harness/harness-core/blob/1359902dad12dcd73eccf3ccf36777c40506fe66/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java#L63)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

Have removed uuid
</blockquote></details>

i still dont see getStatus method getting used?
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/52627#-Ne3FiD59CYszy3VnQvc:-Ne7JY6K7KQ_uLaKIEVh:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/1359902dad12dcd73eccf3ccf36777c40506fe66/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java#L82)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

same as above

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52627)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/52627#-Ne3FdUl7sTMMKUvh-in:-Ne7L5WU6iHKzlWx49hw:bfmiz0g) ([raw file](https://github.com/harness/harness-core/blob/1359902dad12dcd73eccf3ccf36777c40506fe66/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i still dont see getStatus method getting used?
</blockquote></details>

StepResponse.builder().status(originalNodeExecution.getStatus()).build();

In the return statement
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/52627#-Ne3FiD59CYszy3VnQvc:-Ne7LALe1OAWIVuJHDOl:bfmiz0g) ([raw file](https://github.com/harness/harness-core/blob/1359902dad12dcd73eccf3ccf36777c40506fe66/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java#L82)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

StepResponse.builder().status(originalNodeExecution.getStatus()).build();

In the return statement

**Review by archit-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52627)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger uts

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52627)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java` line 143 at r9](https://reviewable.io/reviews/harness/harness-core/52627#-Ne94oaF8hySVfp9kAGV:-Ne94oaF8hySVfp9kAGW:b-dwvd4o) ([raw file](https://github.com/harness/harness-core/blob/29c97aca1014d8a8c1f2f3e9827402cc9da313c2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java#L143)):*
> ```Java
>       Ambiance ambiance, IdentityStepParameters identityParams, Map<String, ResponseData> responseDataMap) {
>     pmsOutcomeService.cloneForRetryExecution(ambiance, identityParams.getOriginalNodeExecutionId());
>     return createStepResponseFromChildResponse(responseDataMap);
> ```

I think we can return the `StepResponse.builder().status(originalNodeExecution.getStatus()).build();` instead of invoking `createStepResponseFromChildResponse` because the nodeExecution is being copied so it will always be same response as originalNodeExecution Similar to what we do in `IdentityStep::handleChildrenResponse`

**Comment by prashantsharma04** [comment]
trigger uts

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52627)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java` line 143 at r9](https://reviewable.io/reviews/harness/harness-core/52627#-Ne94oaF8hySVfp9kAGV:-NeBwc6j3vWtXipyaK00:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/29c97aca1014d8a8c1f2f3e9827402cc9da313c2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java#L143)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

I think we can return the `StepResponse.builder().status(originalNodeExecution.getStatus()).build();` instead of invoking `createStepResponseFromChildResponse` because the nodeExecution is being copied so it will always be same response as originalNodeExecution Similar to what we do in `IdentityStep::handleChildrenResponse`
</blockquote></details>

Done.

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 3 files at r8, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52627)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java` line 82 at r10](https://reviewable.io/reviews/harness/harness-core/52627#-NeCNWzv5d0zjZlIcXT8:-NeCNWzv5d0zjZlIcXT9:bj8blc6) ([raw file](https://github.com/harness/harness-core/blob/d666e141ceee1a5e75cb825315a98ecd190466b5/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java#L82)):*
> ```Java
>       Ambiance ambiance, IdentityStepParameters identityParams, Map<String, ResponseData> responseDataMap) {
>     NodeExecution originalNodeExecution = nodeExecutionService.getWithFieldsIncluded(
>         identityParams.getOriginalNodeExecutionId(), Collections.singleton(NodeExecutionKeys.status));
> ```

same as above

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r8, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52627)* status: :shipit: complete! ✓

**Comment by prashantsharma04** [comment]
trigger review

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52627)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java` line 63 at r10](https://reviewable.io/reviews/harness/harness-core/52627#-NeCNRWZ1gVUWqmISWxX:-NeCToUHEPZqZZidlSZV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d666e141ceee1a5e75cb825315a98ecd190466b5/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java#L63)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Use NodeProjectionUtils#withStatus here
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java` line 82 at r10](https://reviewable.io/reviews/harness/harness-core/52627#-NeCNWzv5d0zjZlIcXT8:-NeCTpOlEHeVsHqatUW1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d666e141ceee1a5e75cb825315a98ecd190466b5/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStep.java#L82)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Comment by prashantsharma04** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52627)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by prashantsharma04** [comment]
trigger review

**Pull request merged**
