### PR TITLE
feat: [CDS-37326]: add Environment Filter DTO, other minor fixes

### PR DESCRIPTION
**Pull request by hingerabhinav**
1. add filters for environments
2. infra request DTO to use environmentRef - same as yaml representation
3. fix yaml-schema API to return Infrastructure as well.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33313)

### CODE REVIEW

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33313)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentFilterPropertiesDTO.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/33313#-N2NkF6JD-9iOT3W8437:-N2NkF6JD-9iOT3W8438:bwtccpo) ([raw file](https://github.com/harness/harness-core/blob/da9f9f602a92669ff8a2b49aaf304912f8a46d91/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentFilterPropertiesDTO.java#L38)):*
> ```Java
> @JsonTypeName(ENVIRONMENT)
> public class EnvironmentFilterPropertiesDTO extends FilterPropertiesDTO {
>   private List<String> environmentNames;
> ```

nit: we do not need ```private``` keyword because of ```@FieldDefaults(level = AccessLevel.PRIVATE)```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/33313#-N2Nl3I5AOs-Aw5CeQ_9:-N2Nl2CU3ze9ZYwmKbdm:b-z2wzmi) ([raw file](https://github.com/harness/harness-core/blob/da9f9f602a92669ff8a2b49aaf304912f8a46d91/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java#L88)):*
> ```Java
>     if (envFilterDTO == null) {
>       throw new InvalidRequestException(
>           String.format("Could not find a environment filter with the identifier %s, in %s",
> ```

Too few arguments for format string (found: 1, expected: 2)

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33313)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/33313#-N2Nl3I5AOs-Aw5CeQ_9:-N2Q422KBJxoJUIpXOBc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/da9f9f602a92669ff8a2b49aaf304912f8a46d91/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java#L88)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Too few arguments for format string (found: 1, expected: 2) 
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33313)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 9 of 11 files at r1, 7 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33313)* status: :shipit: complete! ✓

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 9 of 11 files at r1, 7 of 7 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33313)* status: :shipit: complete! ✓

**Pull request merged**
