### PR TITLE
feat: [PIE-3808]: Addition of pojo for matrix and for strategy in our codebase

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33397)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33397)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/strategy/ParameterizedString.java` line 5 at r1](https://reviewable.io/reviews/harness/harness-core/33397#-N2X0k5XDUoBK1k77njK:-N2X0k5XDUoBK1k77njL:b-x5pn2o) ([raw file](https://github.com/harness/harness-core/blob/3331a35130549bb654c9dacb253e543c10a51498/953-yaml-commons/src/main/java/io/harness/plancreator/strategy/ParameterizedString.java#L5)):*
> ```Java
> import io.harness.pms.yaml.ParameterField;
> 
> public class ParameterizedString {
> ```

why do you need this?

**Comment by sahilhindwani-harness** [comment]
*[`953-yaml-commons/src/main/java/io/harness/plancreator/strategy/ParameterizedString.java` line 5 at r1](https://reviewable.io/reviews/harness/harness-core/33397#-N2X0k5XDUoBK1k77njK:-N2jFhfwDp8aU5NP7Xot:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3331a35130549bb654c9dacb253e543c10a51498/953-yaml-commons/src/main/java/io/harness/plancreator/strategy/ParameterizedString.java#L5)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do you need this?
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 14 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33397)* status: 16 file(s) to review. 1 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 352 at r2](https://reviewable.io/reviews/harness/harness-core/33397#-N2jGsej7gpwrscpcroF:-N2jGsek7tcRY1KjeBEZ:bdjhs8) ([raw file](https://github.com/harness/harness-core/blob/f9c7e536789aee56708401921a973fcc457b3144/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L352)):*
> ```Java
>   USAGE_SCOPE_RBAC,
> 
>   HARD_DELETE_SECRETS,
> ```

do you need this?



_Code quote:_
```Java
HARD_DELETE_SECRETS,
```

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 11 of 14 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33397)* status: :shipit: complete! ✓

**Pull request merged**
