### PR TITLE
feat: [SRM-15004]: Create and register deployment analysis step

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Describe your changes

What this PR consists of?
Deployment Step Info and Register
Deployment Step Node and it's details.
Registering of Plan, Filter and Variable Creators  for this step.
Tests for these creators.
Have tested that this step runs from the yaml.
image

What this doesn't consist?
Execution method of this step.
Registering the Node as YamlSchemaRootClass

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49555)

### CODE REVIEW

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> Reviewed 27 of 38 files at r1, 11 of 13 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49555)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/beans/CVNGDeploymentImpactStepParameter.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/49555#-NZ4KQqk6HT9Z8FmhEVa:-NZ4KQqk6HT9Z8FmhEVb:bdixadb) ([raw file](https://github.com/harness/harness-core/blob/0d4541f867c6e8108a46de821ef05458c9500082/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/beans/CVNGDeploymentImpactStepParameter.java#L25)):*
> ```Java
>   ParameterField<String> serviceIdentifier;
>   ParameterField<String> envIdentifier;
>   ParameterField<Integer> durationInDays;
> ```

We should convert it into string(enum). we should have 12H, 1D, 2D.
Problem with this is that we can't support less than 1 Day which might be a use case in the future.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/beans/CVNGDeploymentStepInfo.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/49555#-NZ4KeuWBGUWw-NXszwJ:-NZ4KeuWBGUWw-NXszwK:b-5wf02u) ([raw file](https://github.com/harness/harness-core/blob/0d4541f867c6e8108a46de821ef05458c9500082/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/beans/CVNGDeploymentStepInfo.java#L79)):*
> ```Java
>   }
> 
>   public void validate() {
> ```

will change accordingly.

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
triggeruts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepak-harness — DISMISSED** [review]
> Reviewed 12 of 13 files at r4, 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49555)* status: :shipit: complete! ✓

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger ut8

**Comment by Varsha-lalwani** [comment]
trigger ut0, ut8

**Pull request merged**
