### PR TITLE
fix: [CDS-68588]: fixed ssh/winrm rollback for pipeline rollback

### PR DESCRIPTION
**Pull request by vitsafronovici**
## Describe your changes
At the moment rollback data is prepared right after a rollback is triggered, getting the stageExecutionDetails. This works for stage rollback, but during pipeline rollback the below happens:
1. let's asume that last successful deployment was with artifact V1 and we want to make a new deployment with V2
2. stage runs successfully and stageExecutionDetails is saved with V2
3. next stage fails and the pipeline rollback is triggered and ssh/winrm rollback is executed
4. the rollback data is prepared based on stageExecutionDetails with V2 whiuch is not correct

Solution:
1. before ssh/winrm step execution we prepare the rollback with latest stageExecutionInfoId and store it in sweeping output
2. if stage rollback happens then we get from sweepingOutput the stageExecutionInfoId and findById the stageExecutionInfo and create rollback data 
3. if pipeline rollback happens then we get from sweepingOutput the stageExecutionInfoId and findById the stageExecutionInfo and create rollback data  and also update the stageExecutionInfo with V1

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47431)

### CODE REVIEW

**Review by yogesh-chauhan — DISMISSED** [review]

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47431)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java` line 116 at r3](https://reviewable.io/reviews/harness/harness-core/47431#-NV4fLCc07BaWqOFnDpU:-NV4mkVK2hxRxGAc9pZW:b-t8o8xx) ([raw file](https://github.com/harness/harness-core/blob/b0293770214c473d2818d568774c66a456b23aaa/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java#L116)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We need this saving because, let's say we have stg1, stg2 and stg3 and sgt3 fails. When rollback starts and sg1 is done successfully then stg1 is the latest successful stage deployment not already stored stg2, right?
</blockquote></details>

Just check here whether io.harness.cdng.execution.service.StageExecutionInfoServiceImpl#updateStatus is called from the listener to update the status when stage rollback is done.

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47431)* status: 10 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/47431#-NV4d5b_2c1WcOlFkLO5:-NV59cg35V3xXEerkoKD:bvw4vqf) (no related file):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

@vitsafronovici one scenario to test and pls confirm whether it works,

We already deployed v1 for s1 on host1

New pipeline deployment starts where we are having two stages stg1, stg2, and stg3. 

In stg1 we deployed v2 on host1, in stg2 we deployed v3 on host1. Now stg3 failes and pipeline rollback starts.   

With the current code changes when rollback starts, stg1 will rollback to v1 which is ok, while stg2 will rollback to v2 what is wrong, right? 

It should redeploy v1 or skip rollback because it's already deployed. 



</blockquote></details>

In this case pipeline rollback will rollback in inverse order: st3 to V3, st2 to V2, st1 to V1 

___

**Review by yogesh-chauhan — APPROVED** [review]

**Review by yogesh-chauhan — DISMISSED** [review]

**Review by acasian-harness — APPROVED** [review]

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47431)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java` line 116 at r3](https://reviewable.io/reviews/harness/harness-core/47431#-NV4fLCc07BaWqOFnDpU:-NV6iWRB7h2Ajhz1GKya:b-kugnb9) ([raw file](https://github.com/harness/harness-core/blob/b0293770214c473d2818d568774c66a456b23aaa/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java#L116)):*
<details><summary><i>Previously, vitsafronovici (Vitalie Safronovici) wrote…</i></summary><blockquote>

We need that only for pipeline rollback. We have  st1 with a successful deployment V1.
Next pipeline we have st1 and update service with V2 and st2 fails. Then latest successful artifact will have V2 which is not correct.
</blockquote></details>

Totally agree, when st2 fails rollback starts and firstly st1 is rollbacked. 

When st1 rollback starts  v1 rollback data is used, and stored in the 'StageExecutionInfo' collection with IN_PROGRESS status. That status should be updated to SUCCESS in 'io.harness.cdng.pipeline.executions.CdngPipelineExecutionUpdateEventHandler#processDeploymentStageEvent' when st1 rollback is done. 
Could you pls check that status is updated to SUCCESS? 
Why, because when the new pipeline starts in the stage command step we will query for the latest successful stage deployment where the status is SUCCESS.

All other logic looks good to me.

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47431)* status: 10 file(s) to review. 1 change requests. 2. unresolved discussions. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java` line 116 at r3](https://reviewable.io/reviews/harness/harness-core/47431#-NV4fLCc07BaWqOFnDpU:-NV8lXB23KItgHbPtKrb:bv4d9nj) ([raw file](https://github.com/harness/harness-core/blob/b0293770214c473d2818d568774c66a456b23aaa/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java#L116)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Totally agree, when st2 fails rollback starts and firstly st1 is rollbacked. 

When st1 rollback starts  v1 rollback data is used, and stored in the 'StageExecutionInfo' collection with IN_PROGRESS status. That status should be updated to SUCCESS in 'io.harness.cdng.pipeline.executions.CdngPipelineExecutionUpdateEventHandler#processDeploymentStageEvent' when st1 rollback is done. 
Could you pls check that status is updated to SUCCESS? 
Why, because when the new pipeline starts in the stage command step we will query for the latest successful stage deployment where the status is SUCCESS.

All other logic looks good to me.
</blockquote></details>

It's success

**Comment by vitsafronovici** [comment]
trigger ut0

**Review by ivan-83 — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47431)* status: 10 file(s) to review. 1. unresolved discussions.

**Comment by vitsafronovici** [comment]
trigger ut1, ut2, ut3, ut4, ut5, ut6, ut7, ut8, ut9

**Comment by vitsafronovici** [comment]
trigger review

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47431#-:-NV91rvx2NuAMiKyA-e3:bnfp4nl)* status: 11 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 8 of 9 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47431)* status: 1. unresolved discussions.

**Comment by vitsafronovici** [comment]
trigger uts

**Review by puthrayaharness — APPROVED** [review]

**Review by puthrayaharness — APPROVED** [review]

**Review by puthrayaharness — APPROVED** [review]

**Review by puthrayaharness — APPROVED** [review]

**Review by acasian-harness — APPROVED** [review]

**Comment by vitsafronovici** [comment]
trigger review

**Pull request merged**
