### PR TITLE
feat: [PL-29159]: Changed mongo iterator in Audit Iterator and make a…

### PR DESCRIPTION
**Pull request by meenakshi-harness**
…ccountId not null

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39787)

### CODE REVIEW

**Review by nishantsaini20 — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39787)* status: 3 file(s) to review. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 609 at r1](https://reviewable.io/reviews/harness/harness-core/39787#-NGQdNGu0kPQR1OtJuue:-NGQdNGu0kPQR1OtJuuf:b-wsqds9) ([raw file](https://github.com/harness/harness-core/blob/92b99b8e22fe9923d209d883e0cfdcf99dfb0dd5/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L609)):*
> ```Java
>           wingsPersistence.save(auditRecord);
>         } else {
>           log.warn("Unable to create audit for entityAuditRecord {} because accountId is {}", record, accountId);
> ```

Should we log limited fields of record rather than complete record?
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/gitdiff/gitaudit/YamlAuditRecordGenerationUtils.java` line 152 at r1](https://reviewable.io/reviews/harness/harness-core/39787#-NGQdwgjCuYgeGgFmyKJ:-NGQdwgjCuYgeGgFmyKK:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/92b99b8e22fe9923d209d883e0cfdcf99dfb0dd5/400-rest/src/main/java/software/wings/service/impl/yaml/gitdiff/gitaudit/YamlAuditRecordGenerationUtils.java#L152)):*
> ```Java
>               wingsPersistence.save(auditRecord);
>             } else {
>               log.warn("Unable to create audit for entityAuditRecord {} because accountId is {}", record, accountId);
> ```

same here

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39787)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 609 at r1](https://reviewable.io/reviews/harness/harness-core/39787#-NGQdNGu0kPQR1OtJuue:-NGRCIEX01X97g02dLH3:bovgldp) ([raw file](https://github.com/harness/harness-core/blob/92b99b8e22fe9923d209d883e0cfdcf99dfb0dd5/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L609)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should we log limited fields of record rather than complete record?
</blockquote></details>

Logging all fields for one release for proper debugging. Will refine the log with next release.

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39787)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39787)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 610 at r3](https://reviewable.io/reviews/harness/harness-core/39787#-NGUuS9g3Vyt24dY1-To:-NGUuS9g3Vyt24dY1-Tp:b-j4awja) ([raw file](https://github.com/harness/harness-core/blob/d42358c19a9e27d53f8ea0ef4959cf05b74b47e0/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L610)):*
> ```Java
>         } else {
>           log.warn("Unable to create audit for entityAuditRecord {} because accountId is {}", record, accountId,
>               new Exception());
> ```

Is this working as expected? The message has two placeholders which will be replaced by record and accountId. What is new Exception() here for? Does it matches the intended method signature of log.warn?

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39787)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 610 at r3](https://reviewable.io/reviews/harness/harness-core/39787#-NGUuS9g3Vyt24dY1-To:-NGUvDWyCEBGd5mOX4Jc:b-3fzz8m) ([raw file](https://github.com/harness/harness-core/blob/d42358c19a9e27d53f8ea0ef4959cf05b74b47e0/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L610)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Is this working as expected? The message has two placeholders which will be replaced by record and accountId. What is new Exception() here for? Does it matches the intended method signature of log.warn?
</blockquote></details>

Yes tested it. new Exception() prints the stack trace and it don't need a placeholder.

**Review by nishantsaini20 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39787)* status: :shipit: complete! ✓

**Review by nishantsaini20 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39787)* status: :shipit: complete! ✓

**Pull request merged**
