### PR TITLE
fix: [CDS-87012]: Show pipeline metadata and account id in variable s…

### PR DESCRIPTION
**Pull request by meenaravichandran1**
…uggestions

## Describe your changes

The below variables get resolved when executed but they don't show up in the suggestions.
<+account.identifier>
<+pipeline.executionUrl>
<+pipeline.branch>
<+pipeline.repo>
<+pipeline.storeType>
<+pipeline.selectedStages>
This change is to show these in suggestions.
image
image
image

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56847)

### CODE REVIEW

**Comment by meenaravichandran1** [comment]
trigger uts

**Review by rohitk-h — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56847)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/dto/AccountDTO.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/56847#-Nlxq8FQ8Y6luD1tJSoq:-Nlxq8FR2Sro1Cdm_YQZ:b-llct90) ([raw file](https://github.com/harness/harness-core/blob/9ad3ed10ec54ec393594230c7f54684f879d4d27/960-ng-core-beans/src/main/java/io/harness/ng/core/dto/AccountDTO.java#L38)):*
> ```Java
> @JsonInclude(NON_NULL)
> @ApiModel(value = "AccountDTO")
> @OwnedBy(PL)
> ```

 Can we get a review from PL team since this is owned by them?

**Comment by rohitk-h** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/pms/sdk/core/pipeline/variables/PipelineVariableCreator.java` line 225 at r1](https://reviewable.io/reviews/harness/harness-core/56847#-NlzGcjW2cd86YAzPfDs:-NlzGcjW2cd86YAzPfDt:b18442q) ([raw file](https://github.com/harness/harness-core/blob/d60f5f59797c5869ea11298919cd55161d38f157/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/pms/sdk/core/pipeline/variables/PipelineVariableCreator.java#L225)):*
> ```Java
>         YamlProperties.newBuilder().setFqn(YAMLFieldNameConstants.PIPELINE + ".selectedStages").build();
>     YamlProperties branchProperty =
>         YamlProperties.newBuilder().setFqn(YAMLFieldNameConstants.PIPELINE + ".branch").build();
> ```

can we update the unit test as well?

**Comment by meenaravichandran1** [comment]
trigger uts

**Comment by meenaravichandran1** [comment]
trigger messagecheck

**Review by vcalasansh — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56847#-:-Nm1TNkb6zzLNaiF3lPa:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by gn-harness — APPROVED** [review]

**Comment by meenaravichandran1** [comment]
trigger review

**Pull request merged**
