### PR TITLE
[feat]: [PIE-5793]: Added variables for current and total global iterations

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Issue: Separate variables were required for current and total iterations for Stages+Step parallelism
Change: Have added two separate fields for it and also added logic for calculations
Test: expected behaviour on local. Added some UTs, Following tests pass against my changes:
Screenshot 2023-01-16 at 9 26 43 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42017)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyConstants.java` line 22 at r4](https://reviewable.io/reviews/harness/harness-core/42017#-NLKfl6ZCow8szTS_aI3:-NLKfl6ZCow8szTS_aI4:b-q7wdtd) ([raw file](https://github.com/harness/harness-core/blob/c09bab903f446d9d228b6a749f41718493448dd6/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyConstants.java#L22)):*
> ```Java
>   public static final String PARTITION = "partition";
>   public static final String TOTAL_ITERATIONS = "totalIterations";
>   public static final String CURRENT_GLOBAL_ITERATION = "currentGlobalIteration";
> ```

Let's get confirmation from product for this expression.

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 320 at r4](https://reviewable.io/reviews/harness/harness-core/42017#-NLKg0AADZ-2XBNIsARI:-NLKg0AADZ-2XBNIsARJ:b-5p82f5) ([raw file](https://github.com/harness/harness-core/blob/c09bab903f446d9d228b6a749f41718493448dd6/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L320)):*
> ```Java
> 
>   @VisibleForTesting
>   void fetchGlobalIterations(
> ```

Can we optimise this code without iterating on the levels again. We are already doing it in the above function

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42017)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 327 at r6](https://reviewable.io/reviews/harness/harness-core/42017#-NLZMM_N0rQv2rAzyqFA:-NLZMM_N0rQv2rAzyqFB:by7z3zr) ([raw file](https://github.com/harness/harness-core/blob/3bb840e2a117278bee42e22a758bcf69a471ec3f/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L327)):*
> ```Java
>   }
> 
>   private void fetchGlobalIterations(Map<String, Object> strategyObjectMap, List<ArrayList<Integer>> levels) {
> ```

Can we add a test for this?

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42017)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 320 at r4](https://reviewable.io/reviews/harness/harness-core/42017#-NLKg0AADZ-2XBNIsARI:-NLZsRFU99_iZWG1uYEB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c09bab903f446d9d228b6a749f41718493448dd6/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L320)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we optimise this code without iterating on the levels again. We are already doing it in the above function
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 327 at r6](https://reviewable.io/reviews/harness/harness-core/42017#-NLZMM_N0rQv2rAzyqFA:-NLZsRoL66LDQdfQ_oVg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3bb840e2a117278bee42e22a758bcf69a471ec3f/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L327)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we add a test for this?
</blockquote></details>

Done.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42017)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 297 at r7](https://reviewable.io/reviews/harness/harness-core/42017#-NLuXsk6CrjvrbIZzN35:-NLuXsk6CrjvrbIZzN36:b-gfxghi) ([raw file](https://github.com/harness/harness-core/blob/7bed06698c12e0bbef73204a37457e5a7112dc13/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L297)):*
> ```Java
>     Map<String, Object> repeatValuesMap = new HashMap<>();
> 
>     List<ArrayList<Integer>> levels = new ArrayList<>();
> ```

Looking at the logic how its used, can't we have it more structured instead of a generic Integer Array? eg: We could have array of some defined struct which contains currentIteration and totalIterations. It will make complete logic neat and clean.

**Comment by mohitg0795** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/IterationVariables.java` line 26 at r9](https://reviewable.io/reviews/harness/harness-core/42017#-NM3AnYY4rwCs8BZ6VoK:-NM3AnYY4rwCs8BZ6VoL:b-2iecy4) ([raw file](https://github.com/harness/harness-core/blob/e34fee28067af0bac62a3c4c0b2457b0ca8fed04/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/IterationVariables.java#L26)):*
> ```Java
> @Builder
> @Getter
> @Setter
> ```

use @data 



_Code quote:_
```Java
@Getter
@Setter
```

**Comment by mohitg0795** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 317 at r9](https://reviewable.io/reviews/harness/harness-core/42017#-NM3B6uc4dprCM1gmige:-NM3B6uc4dprCM1gmigf:b-umubhu) ([raw file](https://github.com/harness/harness-core/blob/e34fee28067af0bac62a3c4c0b2457b0ca8fed04/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L317)):*
> ```Java
>       }
> 
>       if (level.getGroup().equals("STEP")) {
> ```

This should be modular and easily usable across all classes rather than hardcoding it.



_Code quote:_
```Java
if (level.getGroup().equals("STEP")) {
```

**Comment by mohitg0795** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 341 at r9](https://reviewable.io/reviews/harness/harness-core/42017#-NM3BXZw0Cgen5FDvHxk:-NM3BXZw0Cgen5FDvHxl:bvrj9tv) ([raw file](https://github.com/harness/harness-core/blob/e34fee28067af0bac62a3c4c0b2457b0ca8fed04/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L341)):*
> ```Java
>    */
>   public void fetchGlobalIterations(Map<String, Object> strategyObjectMap, List<IterationVariables> levels) {
>     List<Integer> prodArr = new ArrayList<>();
> ```

name is unclear with respect to its logic

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42017)* status: 4 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/IterationVariables.java` line 26 at r9](https://reviewable.io/reviews/harness/harness-core/42017#-NM3AnYY4rwCs8BZ6VoK:-NM7yvblCVrQarupImm7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e34fee28067af0bac62a3c4c0b2457b0ca8fed04/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/IterationVariables.java#L26)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

use @data 
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyConstants.java` line 22 at r4](https://reviewable.io/reviews/harness/harness-core/42017#-NLKfl6ZCow8szTS_aI3:-NLZsc3h1gHmFOpifUJp:b-227o0u) ([raw file](https://github.com/harness/harness-core/blob/c09bab903f446d9d228b6a749f41718493448dd6/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyConstants.java#L22)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Let's get confirmation from product for this expression.
</blockquote></details>

I have asked on the ticket itself tagging the required folks, but got no response, so for now if you think they'r appropriate please appprove
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 297 at r7](https://reviewable.io/reviews/harness/harness-core/42017#-NLuXsk6CrjvrbIZzN35:-NM7zEG2E20dDsgTX0yT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7bed06698c12e0bbef73204a37457e5a7112dc13/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L297)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Looking at the logic how its used, can't we have it more structured instead of a generic Integer Array? eg: We could have array of some defined struct which contains currentIteration and totalIterations. It will make complete logic neat and clean.
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 317 at r9](https://reviewable.io/reviews/harness/harness-core/42017#-NM3B6uc4dprCM1gmige:-NM7zElPAbQaZ3TprD-W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e34fee28067af0bac62a3c4c0b2457b0ca8fed04/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L317)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This should be modular and easily usable across all classes rather than hardcoding it.
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 341 at r9](https://reviewable.io/reviews/harness/harness-core/42017#-NM3BXZw0Cgen5FDvHxk:-NM7zFI_5sOCzo4oNkMw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e34fee28067af0bac62a3c4c0b2457b0ca8fed04/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L341)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

name is unclear with respect to its logic
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 331 at r10](https://reviewable.io/reviews/harness/harness-core/42017#-NM8KqPsC0wzarZqR0h7:-NM8KqPt8SUdExC67WDJ:b-88fv8k) ([raw file](https://github.com/harness/harness-core/blob/a00860521ad962c94c0a972eb58440f872cec4ba/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L331)):*
> ```Java
>   }
> 
>   private boolean isStep(Level level) {
> ```

The method name should be "isStepLevel" not "IsStep". Also, do you think if this can be a part of common utils where we add more such methods for Levels?

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42017)* status: 5 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 331 at r10](https://reviewable.io/reviews/harness/harness-core/42017#-NM8KqPsC0wzarZqR0h7:-NM9efAL7igbzN9bCBEl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a00860521ad962c94c0a972eb58440f872cec4ba/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L331)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The method name should be "isStepLevel" not "IsStep". Also, do you think if this can be a part of common utils where we add more such methods for Levels?
</blockquote></details>

Done.

**Comment by senjucanon2** [comment]
trigger ti0

**Comment by senjucanon2** [comment]
trigger pmd

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 3 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42017)* status: 4 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42017)* status: 4 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by shalini-agr — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 3 files at r10, 2 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42017)* status: 1. unresolved discussions.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r10, 2 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42017)* status: :shipit: complete! ✓

**Pull request merged**
