### PR TITLE
fix: [CCM-5520]: workloadLabelCache usage removed

### PR DESCRIPTION
**Pull request by trunapushpa**
Processing the instanceBillingData in groups, grouped by `instanceBillingData.getAccountId() + "_" + instanceBillingData.getClusterId()+ "_" + instanceBillingData.getNamespace()`, so we can make use of the mongo batch query without using much of heap memory.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30763)

### CODE REVIEW

**Comment by trunapushpa** [comment]
trigger messagecheck

**Comment by trunapushpa** [comment]
trigger checkstyle

**Comment by trunapushpa** [comment]
trigger codeformat

**Comment by ketankr9** [comment]
___
*[280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java, line 116 at r2](https://reviewable.io/reviews/harness/harness-core/30763#-Mvw37cY2bVkItI0Iw2o:-Mvw37cZ8dDVWxBUB8RC:b-frb5fn) ([raw file](https://github.com/harness/harness-core/blob/c47dd952ae4413072a2ad7652dc5bd085dc32ebd/280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java#L116)):*
> ```Java
>       Map<String, List<InstanceBillingData>> instanceBillingDataGrouped = instanceBillingDataList.stream()
>           .collect(Collectors.groupingBy(instanceBillingData ->
>               instanceBillingData.getAccountId() + "_" + instanceBillingData.getClusterId()
> ```

Please avoid this pattern of constructing key. It adds a little ambiguity to the code and is not clean.

Instead create a static CacheKey class and use it as a key.



_Code quote:_
```Java
              instanceBillingData.getAccountId() + "_" + instanceBillingData.getClusterId()
                  + "_" + instanceBillingData.getNamespace()));
```

**Comment by ketankr9** [comment]
___
*[280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java, line 131 at r2](https://reviewable.io/reviews/harness/harness-core/30763#-Mvw3caf6hZVhqD4JNiZ:-Mvw3cag-jF5jURGVBN4:bbnkknp) ([raw file](https://github.com/harness/harness-core/blob/c47dd952ae4413072a2ad7652dc5bd085dc32ebd/280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java#L131)):*
> ```Java
>                         instanceBillingData,
>                         labelMap.getOrDefault(
>                             new K8SWorkloadService.CacheKey(instanceBillingData.getAccountId(),
> ```

Please don't use nested `.forEach()`, it's very difficult to understand the code block. Use it only if it helps with readability. Ref: https://blog.jooq.org/3-reasons-why-you-shouldnt-replace-your-for-loops-by-stream-foreach/

Use simple for loop, and if there are multiple for loops then try to extract a method out of it.



_Code quote:_
```Java
      instanceBillingDataGrouped.forEach((key, instanceBillingDataListForKey) -> {

        Map<K8SWorkloadService.CacheKey, Map<String, String>> labelMap =
            getLabelMapForGroup(instanceBillingDataListForKey);
        log.debug("labelMap: {}", labelMap);

        instanceBillingDataListForKey.forEach(
            instanceBillingData ->
                clusterBillingData.add(
                    convertInstanceBillingDataToAVROObjects(
                        instanceBillingData,
                        labelMap.getOrDefault(
                            new K8SWorkloadService.CacheKey(instanceBillingData.getAccountId(),
                                instanceBillingData.getClusterId(), instanceBillingData.getNamespace(),
                                instanceBillingData.getWorkloadName()),
                            null
                        )
                    )
                )
        );
```

**Review by ketankr9 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30763)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java, line 156 at r3](https://reviewable.io/reviews/harness/harness-core/30763#-Mvx6Qna0YHTDKDb1t6z:-Mvx6Qna0YHTDKDb1t7-:b-fc2inm) ([raw file](https://github.com/harness/harness-core/blob/670a7b197139b39b08bad9d60edcda469000e31a/280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java#L156)):*
> ```Java
>         Map<String, String> labels = labelMap.getOrDefault(
>             new K8SWorkloadService.CacheKey(instanceBillingData.getAccountId(), instanceBillingData.getClusterId(),
>                 instanceBillingData.getNamespace(), instanceBillingData.getWorkloadName()),
> ```

Using `getOrDefault(key, null)` is redundant, get will aways return null value if key is not present.



_Code quote:_
```Java
        Map<String, String> labels = labelMap.getOrDefault(
            new K8SWorkloadService.CacheKey(instanceBillingData.getAccountId(), instanceBillingData.getClusterId(),
                instanceBillingData.getNamespace(), instanceBillingData.getWorkloadName()),
            null);
```
___
*[280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java, line 170 at r3](https://reviewable.io/reviews/harness/harness-core/30763#-Mvx4IfPCghHW2nPUk7F:-Mvx4IfPCghHW2nPUk7G:b804pg4) ([raw file](https://github.com/harness/harness-core/blob/670a7b197139b39b08bad9d60edcda469000e31a/280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java#L170)):*
> ```Java
>     String accountId = instanceBillingDataList.get(0).getAccountId();
>     String clusterId = instanceBillingDataList.get(0).getClusterId();
>     String namespace = instanceBillingDataList.get(0).getNamespace();
> ```

nit: This method is not self-explainable and have certain assumptions, might get mistaken since there isn't any constraint on input list values, I would personally prefer passing `Key` as a 2nd param, since the caller method already has `instanceBillingDataGrouped.Key` available with it.



_Code quote:_
```Java
  private Map<K8SWorkloadService.CacheKey, Map<String, String>> getLabelMapForGroup(
      List<InstanceBillingData> instanceBillingDataList) {
    String accountId = instanceBillingDataList.get(0).getAccountId();
    String clusterId = instanceBillingDataList.get(0).getClusterId();
    String namespace = instanceBillingDataList.get(0).getNamespace();
```
___
*[280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java, line 172 at r3](https://reviewable.io/reviews/harness/harness-core/30763#-Mvx3fLiCmFMk0LThR3G:-Mvx3fLiCmFMk0LThR3H:b-dgsq6y) ([raw file](https://github.com/harness/harness-core/blob/670a7b197139b39b08bad9d60edcda469000e31a/280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java#L172)):*
> ```Java
>     String namespace = instanceBillingDataList.get(0).getNamespace();
>     Set<String> workloadNames = new HashSet<>();
>     instanceBillingDataList.forEach(instanceBillingData -> workloadNames.add(instanceBillingData.getWorkloadName()));
> ```

not required in this commit (nit): Another cleaner way to do this would be `Set<String> workloadNames = instanceBillingDataList.stream().map(InstanceBillingData::getWorkloadName).collect(Collectors.toSet());`



_Code quote:_
```Java
    Set<String> workloadNames = new HashSet<>();
    instanceBillingDataList.forEach(instanceBillingData -> workloadNames.add(instanceBillingData.getWorkloadName()));
```

**Review by ketankr9 — CHANGES_REQUESTED** [review]
1. Please clean `io.harness.batch.processing.tasklet.ClusterDataToBigQueryTasklet#refreshLabelCache`, it's no longer used.
2. Please write few unitTests to verify that only limited and required number of workloadLabel mongo calls are made and the labels are passed to the final function properly.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30763#-:-MvxCR_c3B2UM-FAE3du:byjctrf)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by trunapushpa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30763)* status: 3 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java, line 116 at r2](https://reviewable.io/reviews/harness/harness-core/30763#-Mvw37cY2bVkItI0Iw2o:-MvxFKfpBVUc-0xx6mRu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c47dd952ae4413072a2ad7652dc5bd085dc32ebd/280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java#L116)):*
<details><summary><i>Previously, ketankr9 (Utsav Krishnan) wrote…</i></summary><blockquote>

Please avoid this pattern of constructing key. It adds a little ambiguity to the code and is not clean.

Instead create a static CacheKey class and use it as a key.
</blockquote></details>

Done.
___
*[280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java, line 131 at r2](https://reviewable.io/reviews/harness/harness-core/30763#-Mvw3caf6hZVhqD4JNiZ:-MvxFKJpB5KTx-Ma4hcL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c47dd952ae4413072a2ad7652dc5bd085dc32ebd/280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java#L131)):*
<details><summary><i>Previously, ketankr9 (Utsav Krishnan) wrote…</i></summary><blockquote>

Please don't use nested `.forEach()`, it's very difficult to understand the code block. Use it only if it helps with readability. Ref: https://blog.jooq.org/3-reasons-why-you-shouldnt-replace-your-for-loops-by-stream-foreach/

Use simple for loop, and if there are multiple for loops then try to extract a method out of it.
</blockquote></details>

Done.
___
*[280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java, line 156 at r3](https://reviewable.io/reviews/harness/harness-core/30763#-Mvx6Qna0YHTDKDb1t6z:-Mvy-Ocn3NdvHXgeZZgR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/670a7b197139b39b08bad9d60edcda469000e31a/280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java#L156)):*
<details><summary><i>Previously, ketankr9 (Utsav Krishnan) wrote…</i></summary><blockquote>

Using `getOrDefault(key, null)` is redundant, get will aways return null value if key is not present.
</blockquote></details>

Done.
___
*[280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java, line 170 at r3](https://reviewable.io/reviews/harness/harness-core/30763#-Mvx4IfPCghHW2nPUk7F:-Mvy-hGc68ckkrjxxcAc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/670a7b197139b39b08bad9d60edcda469000e31a/280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java#L170)):*
<details><summary><i>Previously, ketankr9 (Utsav Krishnan) wrote…</i></summary><blockquote>

nit: This method is not self-explainable and have certain assumptions, might get mistaken since there isn't any constraint on input list values, I would personally prefer passing `Key` as a 2nd param, since the caller method already has `instanceBillingDataGrouped.Key` available with it.
</blockquote></details>

Done.
___
*[280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java, line 172 at r3](https://reviewable.io/reviews/harness/harness-core/30763#-Mvx3fLiCmFMk0LThR3G:-Mvy-pYZBVJgnqIuftPA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/670a7b197139b39b08bad9d60edcda469000e31a/280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java#L172)):*
<details><summary><i>Previously, ketankr9 (Utsav Krishnan) wrote…</i></summary><blockquote>

not required in this commit (nit): Another cleaner way to do this would be `Set<String> workloadNames = instanceBillingDataList.stream().map(InstanceBillingData::getWorkloadName).collect(Collectors.toSet());`
</blockquote></details>

Done.

**Review by ketankr9 — APPROVED** [review]
Nice work, the code is significantly readable and cleaner now 👌👌👌

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30763#-:-Mw-kmoV1t6av52H7Vvf:byd78rp)* status: :shipit: complete! ✓

**Pull request merged**
