### PR TITLE
feat:  [CDS-41366]: Revert GA service as expression FF

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
Reverts harness/harness-core#38238

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38317)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38317)

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
trigger authorcheck

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38317)* status: :shipit: complete! ✓

**Pull request merged**
