### PR TITLE
fix: [CDS-84033]: timeout as expression resolved

### PR DESCRIPTION
**Pull request by shivamnegi94**
## Describe your changes

- In case of timeout as expression, we were getting NPE as the expression was not handle correctly.  Added the validation for expression before setting the timeout to planNode.
- Pipeline Node was also referring to stage timeout config, fixed the issue.

TCs:

1. Create stage with Timeout as expression and verify the pipeline successful and expression resolved successfully
2. Create stage with fixed timeout value and verify the pipeline successful.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55287)

### CODE REVIEW

**Comment by shivamnegi94** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55287)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/ChildrenPlanCreator.java` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/55287#-NiszzPC4jYGc7fiG_lN:-NiszzPC4jYGc7fiG_lO:bsguxfa) ([raw file](https://github.com/harness/harness-core/blob/fad67cd6382f65b8fa3656519707087efce48367/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/ChildrenPlanCreator.java#L77)):*
> ```Java
>   }
> 
>   public ParameterField<String> getTimeoutString(ParameterField<Timeout> timeout) {
> ```

this util should exist in timeoutUtils

**Comment by shivamnegi94** [comment]
trigger uts

**Comment by shivamnegi94** [comment]
trigger uts

**Comment by shivamnegi94** [comment]
trigger uts

**Comment by shivamnegi94** [comment]
trigger uts

**Comment by shivamnegi94** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55287)* status: 5 file(s) to review. 1 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/ChildrenPlanCreator.java` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/55287#-NiszzPC4jYGc7fiG_lN:-Nj70EC93bFnZmgRppcH:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/fad67cd6382f65b8fa3656519707087efce48367/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/ChildrenPlanCreator.java#L77)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this util should exist in timeoutUtils
</blockquote></details>

done

**Comment by shivamnegi94** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java` line 99 at r4](https://reviewable.io/reviews/harness/harness-core/55287#-NjGEGzZ71JNsWq4EL7C:-NjGEGzZ71JNsWq4EL7D:b-c25hj0) ([raw file](https://github.com/harness/harness-core/blob/da468a25e404263c13cbb913ba832aef073fc16b/970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java#L99)):*
> ```Java
> 
>   public ParameterField<String> getParameterTimeoutString(ParameterField<Timeout> timeout) {
>     if (timeout.isExpression()) {
> ```

why do we need this special logic, why can't we use the same parameter field passed as input?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55287)* status: 1 change requests. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55287)* status: :shipit: complete! ✓

**Comment by sahilhindwani-harness** [comment]
trigger review

**Pull request merged**
