### PR TITLE
feat: [IDP-1088]: Scorecards github DSL fixes

### PR DESCRIPTION
**Pull request by sathish-soundarapandian**
## Describe your changes
Scorecards github DSL fixes

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52302)

### CODE REVIEW

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52302)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52302)* status: 5 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/migration/IdpBGMigrationDetails.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/52302#-NdA5qmW9oxOwQ8BTScz:-NdA5qmW9oxOwQ8BTSd-:b-nn8eh3) ([raw file](https://github.com/harness/harness-core/blob/d95ab81534ef1cd93852552fd96204f8fee6fed3/idp-service/src/main/java/io/harness/idp/migration/IdpBGMigrationDetails.java#L48)):*
> ```Java
>         .add(Pair.of(12, NameSpaceEntityNextIterationMigration.class))
>         .add(Pair.of(13, ScorecardMigration.class))
>         .add(Pair.of(14, ScorecardMigration.class))
> ```

We can just use the previous version and edit the version in preQA as it is not deployed to QA or Prod. 
Otherwise, migration will happen twice when we deploy to QA and prod
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/GithubIsBranchProtectedParser.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/52302#-NdA5VIf4a-lzXNOoE7F:-NdA5VIf4a-lzXNOoE7G:b-jlthgk) ([raw file](https://github.com/harness/harness-core/blob/8c739140716431ccc70a37c8a6348529ce318df5/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/GithubIsBranchProtectedParser.java#L28)):*
> ```Java
>   public Object parseDataPoint(Map<String, Object> data, DataPointEntity dataPoint, Set<String> inputValues) {
>     Map<String, Object> dataPointInfo = new HashMap<>();
>     if (CommonUtils.findObjectByName(data, "defaultBranchRef") == null
> ```

why are we checking for defaultBranchRef also?



_Code quote:_
```Java
defaultBranchRef
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/GithubMeanTimeToMergePRDsl.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/52302#-NdA5j-M4-Fia3wDoaxv:-NdA5j-M4-Fia3wDoaxw:b-4a81va) ([raw file](https://github.com/harness/harness-core/blob/8c739140716431ccc70a37c8a6348529ce318df5/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/GithubMeanTimeToMergePRDsl.java#L78)):*
> ```Java
>         requestBody = requestBody.replace(REPOSITORY_BRANCH_NAME_REPLACER,
>             ",baseRefName:"
>                 + "\\"
> ```

Is single escape character not working?

**Comment by sathish-soundarapandian** [comment]
> We can just use the previous version and edit the version in preQA as it is not deployed to QA or Prod.
> Otherwise, migration will happen twice when we deploy to QA and prod

That is fine. We have implemented this scorecards migration using saveAll which takes care of create and update internally. So, even if it runs twice or more than that, we should be good.

> why are we checking for defaultBranchRef also?

The GraphQL response is different with and without branch name input. So we need to consider both the cases.

> Is single escape character not working?

Yes. As this a complete placeholder replace value which includes double quotes as well, we need to handle it his way.

**Review by vigneswara-propelo — DISMISSED** [review]

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52302)* status: 10 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/GithubFileExistsParser.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/52302#-NdDjjKNArdURkqbWwzw:-NdDjjKNArdURkqbWwzx:bt05sq0) ([raw file](https://github.com/harness/harness-core/blob/1076a9fb1260780dcdb3d3abf8e5639ea4070444/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/GithubFileExistsParser.java#L46)):*
> ```Java
>     }
> 
>     dataPointInfo.put(inputFile, Map.of(DATA_POINT_VALUE_KEY, isPresent));
> ```

while evaluating the expression we need to iterate conditionalInput first and then comes the value.
Does the current logic supports it?
___
*[`idp-service/src/main/resources/migrations/scorecard/checks.json` line 113 at r3](https://reviewable.io/reviews/harness/harness-core/52302#-NdDkCAM9htlHC02E0AZ:-NdDkCAM9htlHC02E0A_:b-szhi5e) ([raw file](https://github.com/harness/harness-core/blob/1076a9fb1260780dcdb3d3abf8e5639ea4070444/idp-service/src/main/resources/migrations/scorecard/checks.json#L113)):*
> ```JSON
>         "data_source_identifier": "github",
>         "data_point_identifier": "isFileExists",
>         "conditional_input_value": "\".gitleaks.toml\"",
> ```

Are we planning to handle the same for custom checks where users give input file of their choice ?
___
*[`idp-service/src/main/resources/migrations/scorecard/datasourceLocations.json` line 54 at r3](https://reviewable.io/reviews/harness/harness-core/52302#-NdDkyW09Hlg8VV6tCXB:-NdDkyW1ECYPlWh-sdAD:b-9caeot) ([raw file](https://github.com/harness/harness-core/blob/1076a9fb1260780dcdb3d3abf8e5639ea4070444/idp-service/src/main/resources/migrations/scorecard/datasourceLocations.json#L54)):*
> ```JSON
>         "Authorization": "{BEARER_AUTH}"
>       },
>       "requestBody": "{\"query\":\"{\\n  repository(owner: \\\"{REPOSITORY_OWNER}\\\", name: \\\"{REPOSITORY_NAME}\\\") {\\n    defaultBranchRef {\\n      repository {\\n        object(expression : \\\"{GITHUB_FILE_EXISTS_REPLACER}\\\") {\\n          ... on Tree {\\n            id\\n            entries {\\n              name\\n              path\\n              type\\n            }\\n          }\\n        }\\n      }\\n    }\\n  }\\n}\",\"variables\":{}}"
> ```

another "query" is not required?



_Code quote:_
```JSON
query
```

**Comment by sathish-soundarapandian** [comment]
> another "query" is not required?

Yeah, it is not required. It still works the same.

> Are we planning to handle the same for custom checks where users give input file of their choice ?

Yes. Because all the file name will have dot character for the file extension. We will handle it at the UI level itself i.e if conditional input filename is provided for GitHub fileExists DP, then that will be wrapped in double quotes

> while evaluating the expression we need to iterate conditionalInput first and then comes the value. Does the current logic supports it?

Yes. It supports it. So the expression will be formed by parsing the rules and it becomes - github.isFileExists.".gitleaks.toml" == true and then the data to evaluator will be github.isFileExists.".gitleaks.toml".value == true

**Comment by vigneswara-propelo** [comment]
> Yes. Because all the file name will have dot character for the file extension. We will handle it at the UI level itself i.e if conditional input filename is provided for GitHub fileExists DP, then that will be wrapped in double quotes
> ok then, lets inform UI team to handle the same

**Review by vigneswara-propelo — APPROVED** [review]

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52302)* status: 10 file(s) to review.

**Comment by sathish-soundarapandian** [comment]
trigger review

**Comment by sathish-soundarapandian** [comment]
trigger review

**Pull request merged**
