### PR TITLE
feat: [PL-29245]: NG endpoint to fetch accountIds for an FF

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
Introduced an endpoint in AccountResourceNG.java to fetch accountIds for which a feature flag is enabled. 
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39091)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39091)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1574 at r1](https://reviewable.io/reviews/harness/harness-core/39091#-NEtEg-u4ieiRpAGOE72:-NEtEg-u4ieiRpAGOE73:b-ilo5f8) ([raw file](https://github.com/harness/harness-core/blob/8996346dd0c13bff7ba131d2762637f79ae41add/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1574)):*
> ```Java
> 
>   @Override
>   public Set<String> getAccountIds(String featureName) {
> ```

Validate that the featureName is a valid FF before calling feature flag service method.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/utils/featureflaghelper/NGFeatureFlagHelperService.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/39091#-NEtMGBS0iSNA6RYmU0A:-NEtMGBS0iSNA6RYmU0B:b-c0sum5) ([raw file](https://github.com/harness/harness-core/blob/8996346dd0c13bff7ba131d2762637f79ae41add/120-ng-manager/src/main/java/io/harness/utils/featureflaghelper/NGFeatureFlagHelperService.java#L27)):*
> ```Java
>   }
> 
>   public Set<String> getAccountIds(String featureName) {
> ```

can we name it "getActiveAccountIds" or "getEnabledAccountIds" to be more intuitive here

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39091)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/utils/featureflaghelper/NGFeatureFlagHelperService.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/39091#-NEtMGBS0iSNA6RYmU0A:-NEtq0HDBra7oWlUbqFp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8996346dd0c13bff7ba131d2762637f79ae41add/120-ng-manager/src/main/java/io/harness/utils/featureflaghelper/NGFeatureFlagHelperService.java#L27)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we name it "getActiveAccountIds" or "getEnabledAccountIds" to be more intuitive here
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1574 at r1](https://reviewable.io/reviews/harness/harness-core/39091#-NEtEg-u4ieiRpAGOE72:-NEtq1YJ0jH_uzk-hmuM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8996346dd0c13bff7ba131d2762637f79ae41add/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1574)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Validate that the featureName is a valid FF before calling feature flag service method.
</blockquote></details>

Done.

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 1 of 5 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39091)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39091)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/utils/featureflaghelper/NGFeatureFlagHelperService.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/39091#-NEtMGBS0iSNA6RYmU0A:-NEtqh6g2ntTWmJuXN6C:b-li70no) ([raw file](https://github.com/harness/harness-core/blob/8996346dd0c13bff7ba131d2762637f79ae41add/120-ng-manager/src/main/java/io/harness/utils/featureflaghelper/NGFeatureFlagHelperService.java#L27)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

getActiveAccountIds seems more associated to the account status (active/inactive/expired etc.) rather than associated to status of FF for the accounts.
My suggestion would be to name it as getFeatureFlagEnabledAccountIds
___
*[`400-rest/src/main/java/software/wings/resources/AccountResourceNG.java` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/39091#-NEtsGMD2dNUOt3ArUoc:-NEtsGMD2dNUOt3ArUod:bibsdco) ([raw file](https://github.com/harness/harness-core/blob/b5fe3289cab9d879030e36b2a86852f0344d9a61/400-rest/src/main/java/software/wings/resources/AccountResourceNG.java#L116)):*
> ```Java
>   @GET
>   @Path("/feature-flag-enabled-accounts")
>   public RestResponse<Set<String>> getEnabledAccountIds(@QueryParam("featureName") String featureName) {
> ```

rename to getFeatureFlagEnabledAccountIds

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39091)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/utils/featureflaghelper/NGFeatureFlagHelperService.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/39091#-NEtMGBS0iSNA6RYmU0A:-NEttaaGE4AeqUWeIKxI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8996346dd0c13bff7ba131d2762637f79ae41add/120-ng-manager/src/main/java/io/harness/utils/featureflaghelper/NGFeatureFlagHelperService.java#L27)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

getActiveAccountIds seems more associated to the account status (active/inactive/expired etc.) rather than associated to status of FF for the accounts.
My suggestion would be to name it as getFeatureFlagEnabledAccountIds
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/resources/AccountResourceNG.java` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/39091#-NEtsGMD2dNUOt3ArUoc:-NEttbde0pyVubWlRctl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b5fe3289cab9d879030e36b2a86852f0344d9a61/400-rest/src/main/java/software/wings/resources/AccountResourceNG.java#L116)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

rename to getFeatureFlagEnabledAccountIds
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/utils/featureflaghelper/NGFeatureFlagHelperService.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/39091#-NEtMGBS0iSNA6RYmU0A:-NEtzDq33QZCM5TLK3qk:bbijpce) ([raw file](https://github.com/harness/harness-core/blob/8996346dd0c13bff7ba131d2762637f79ae41add/120-ng-manager/src/main/java/io/harness/utils/featureflaghelper/NGFeatureFlagHelperService.java#L27)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why I preferred getActiveAccountIds is because we are already inside NGFeatureFlagService and all its methods will correspond to its meaning. Its the same way other method name is only "isEnabled" coz its understood we are talking of FFs here and not anything else.

Naming it more explicit does no harm, so I don't have any issues with that as well.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39091)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/impl/AccountServiceImplTest.java` line 261 at r5](https://reviewable.io/reviews/harness/harness-core/39091#-NEuNp7v7cTwn19s_D27:-NEuNp7v7cTwn19s_D28:b-ci1xh8) ([raw file](https://github.com/harness/harness-core/blob/39bf9fee0d8a169ebcef60b178a7120f1f8b6bd4/400-rest/src/test/java/software/wings/service/impl/AccountServiceImplTest.java#L261)):*
> ```Java
>   public void testGetFeatureFlagEnabledAccountIds() {
>     FeatureName featureName = FeatureName.values()[0];
>     Set<String> featureFlagEnabledAccounts = accountService.getFeatureFlagEnabledAccountIds(featureName.name());
> ```

Mock eatureFlagService.getAccountIds to return expected value and add assert comparing value of featureFlagEnabledAccounts with the expected return value.
___
*[`400-rest/src/test/java/software/wings/service/impl/AccountServiceImplTest.java` line 274 at r5](https://reviewable.io/reviews/harness/harness-core/39091#-NEuO_xsCiM-q6PAc_Ww:-NEuO_xsCiM-q6PAc_Wx:bnu68r0) ([raw file](https://github.com/harness/harness-core/blob/39bf9fee0d8a169ebcef60b178a7120f1f8b6bd4/400-rest/src/test/java/software/wings/service/impl/AccountServiceImplTest.java#L274)):*
> ```Java
>       fail("Should have failed with InvalidRequestException due to incorrect feature flag name");
>     } catch (InvalidRequestException ex) {
>       assertEquals(ex.getMessage(), String.format("Invalid feature flag name received: %s", featureFlagName));
> ```

Instead of try catch you can modify test to expect an exception to be thrown. Use ExpectedException for this.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39091)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/impl/AccountServiceImplTest.java` line 261 at r5](https://reviewable.io/reviews/harness/harness-core/39091#-NEuNp7v7cTwn19s_D27:-NEuY_8FAsHx3X6AD2-3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/39bf9fee0d8a169ebcef60b178a7120f1f8b6bd4/400-rest/src/test/java/software/wings/service/impl/AccountServiceImplTest.java#L261)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Mock eatureFlagService.getAccountIds to return expected value and add assert comparing value of featureFlagEnabledAccounts with the expected return value.
</blockquote></details>

Done.
___
*[`400-rest/src/test/java/software/wings/service/impl/AccountServiceImplTest.java` line 274 at r5](https://reviewable.io/reviews/harness/harness-core/39091#-NEuO_xsCiM-q6PAc_Ww:-NEuY_s07dBUnEm3YY3W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/39bf9fee0d8a169ebcef60b178a7120f1f8b6bd4/400-rest/src/test/java/software/wings/service/impl/AccountServiceImplTest.java#L274)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Instead of try catch you can modify test to expect an exception to be thrown. Use ExpectedException for this.
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39091)* status: Some of the checks are too old. 5 file(s) to review. 1 of 2 approvals obtained.

**Review by meenakshi-harness — APPROVED** [review]

**Pull request merged**
