### PR TITLE
[feat]:[pie-7551]: Integrate caching with templateInputs api

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have integrated git caching with the templateInputs api. 

Testing:
1. Have tested the templateInputs api with caching, response time around 150 ms
2. Have tested the templateInputs api with caching, response time around 1.5s 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42433)

### CODE REVIEW

**Review by utkarshchoubey-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42433)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/42433#-NLQE-nT1mOEty5AICtq:-NLQE-nT1mOEty5AICtr:b-d53p1r) ([raw file](https://github.com/harness/harness-core/blob/38b8b2bba18cda6d5fdd0dacbc5d717e6bfd70ae/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L68)):*
> ```Java
>     Optional<TemplateEntity> optionalTemplateEntity = templateServiceHelper.getTemplateOrThrowExceptionIfInvalid(
>         accountId, orgIdentifier, projectIdentifier, templateIdentifier, versionLabel, false, loadFromCache);
>     if (optionalTemplateEntity.isEmpty()) {
> ```

Any specific reason to change this ? 
___
*[`840-template-service/src/test/java/io/harness/template/services/TemplateMergeServiceImplTest.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/42433#-NLQE4vV9DsScRSX0rb2:-NLQE4vV9DsScRSX0rb3:btnszgm) ([raw file](https://github.com/harness/harness-core/blob/38b8b2bba18cda6d5fdd0dacbc5d717e6bfd70ae/840-template-service/src/test/java/io/harness/template/services/TemplateMergeServiceImplTest.java#L21)):*
> ```Java
> import static org.mockito.ArgumentMatchers.anyString;
> import static org.mockito.ArgumentMatchers.eq;
> import static org.mockito.Mockito.*;
> ```

can we only import whatever we have used instead of using *

**Review by utkarshchoubey-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42433)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/test/java/io/harness/template/services/TemplateMergeServiceImplTest.java` line 729 at r1](https://reviewable.io/reviews/harness/harness-core/42433#-NLQEMpH6WVerZiw7bPU:-NLQEMpH6WVerZiw7bPV:b-6h3m57) ([raw file](https://github.com/harness/harness-core/blob/38b8b2bba18cda6d5fdd0dacbc5d717e6bfd70ae/840-template-service/src/test/java/io/harness/template/services/TemplateMergeServiceImplTest.java#L729)):*
> ```Java
>   @Owner(developers = ADITHYA)
>   @Category(UnitTests.class)
>   public void testGetTemplateInputsWithCaching() {
> ```

Also can we add test for one negative scenerio

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/42433#-NLQE-nT1mOEty5AICtq:-NLQFgBj4dOxpjk1TV9n:b-o19sjw) ([raw file](https://github.com/harness/harness-core/blob/38b8b2bba18cda6d5fdd0dacbc5d717e6bfd70ae/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L68)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Any specific reason to change this ? 
</blockquote></details>

Yes, if not any specific reason, lets avoid unrelated changes.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42433)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/42433#-NLQE-nT1mOEty5AICtq:-NLQEwfJ3i5qNEHzXZqP:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/38b8b2bba18cda6d5fdd0dacbc5d717e6bfd70ae/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L68)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Yes, if not any specific reason, lets avoid unrelated changes.
</blockquote></details>

done
___
*[`840-template-service/src/test/java/io/harness/template/services/TemplateMergeServiceImplTest.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/42433#-NLQE4vV9DsScRSX0rb2:-NLQFF3PC4DAu8mqL-oT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/38b8b2bba18cda6d5fdd0dacbc5d717e6bfd70ae/840-template-service/src/test/java/io/harness/template/services/TemplateMergeServiceImplTest.java#L21)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

can we only import whatever we have used instead of using *
</blockquote></details>

Done.
___
*[`840-template-service/src/test/java/io/harness/template/services/TemplateMergeServiceImplTest.java` line 729 at r1](https://reviewable.io/reviews/harness/harness-core/42433#-NLQEMpH6WVerZiw7bPU:-NLQImMnC9vVgfJqvsZ6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/38b8b2bba18cda6d5fdd0dacbc5d717e6bfd70ae/840-template-service/src/test/java/io/harness/template/services/TemplateMergeServiceImplTest.java#L729)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Also can we add test for one negative scenerio
</blockquote></details>

Done.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42433)* status: :shipit: complete! ✓

**Pull request merged**
