### PR TITLE
feat: [CDS-72220]: functor to use step group service overrides

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
Added a new functor to use the expression serviceVariableOverrides 
Users will use step group variables to override service variables. They can give expression `serviceVariableOverrides.var1`

This functor builds fqns for each Level of type step group (to find variable value)
this fqn is rendered using pms engine expression service 

Base fqn is still serviceVariables.var1 so if no variables are defined, this defaults to service variables 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49971)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/49971#-NZAMPLAEOLYFd7AyqjX:-NZAMPLBBzz0yjlTDPi8:bjvzgsk) ([raw file](https://github.com/harness/harness-core/blob/47744458038a7722f359498f2834502ab45046f8/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java#L70)):*
> ```Java
>       String fqnRendered = engineExpressionService.renderExpression(ambiance, fqnList.get(i));
> 
>       // nearest non-null value needs to be picked up
> ```

This won't give nearest, right?
We are starting from first group, should'nt it be reverse?

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by hingerabhinav** [comment]
trigger uts

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49971)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/49971#-NZAMPLAEOLYFd7AyqjX:-NZVKqcL2FFcyNDoTK_x:b-fqg3v6) ([raw file](https://github.com/harness/harness-core/blob/47744458038a7722f359498f2834502ab45046f8/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java#L70)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

This won't give nearest, right?
We are starting from first group, should'nt it be reverse?
</blockquote></details>

Done. We're checking in reverse.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java` line 57 at r3](https://reviewable.io/reviews/harness/harness-core/49971#-NZVO4GQ5VfqE_TXVgwo:-NZVO4GQ5VfqE_TXVgwp:bj05m5c) ([raw file](https://github.com/harness/harness-core/blob/d209f24ede5b1384d29066ef8ab00ab9d8032fa6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java#L57)):*
> ```Java
> 
>         // append variables.variable_name
>         fqn = fqn + ".variables." + variableName;
> ```

Use String.format and also use constants here

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java` line 60 at r3](https://reviewable.io/reviews/harness/harness-core/49971#-NZVOAk1BGUZSWqDJ-Xh:-NZVOAk1BGUZSWqDJ-Xi:bgjdqw3) ([raw file](https://github.com/harness/harness-core/blob/d209f24ede5b1384d29066ef8ab00ab9d8032fa6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java#L60)):*
> ```Java
> 
>         // create expression for the engine
>         fqn = EXPR_START + fqn + EXPR_END;
> ```

Same as above, use String.format

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/49971#-NZVOHI4328TFdQP6lTw:-NZVOHI4328TFdQP6lTx:b-powfgd) ([raw file](https://github.com/harness/harness-core/blob/d209f24ede5b1384d29066ef8ab00ab9d8032fa6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java#L25)):*
> ```Java
> import java.util.Objects;
> 
> public class ServiceVariableOverridesFunctor extends LateBindingMap {
> ```

Move this functor to pipeline-service/service/src/main/java/io/harness/pms/expressions/functors
This should not be a part of orchestration engine.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/AmbianceExpressionEvaluator.java` line 151 at r3](https://reviewable.io/reviews/harness/harness-core/49971#-NZVOUdC5udua7xqgUXw:-NZVOUdC5udua7xqgUXx:b3vsi9c) ([raw file](https://github.com/harness/harness-core/blob/d209f24ede5b1384d29066ef8ab00ab9d8032fa6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/AmbianceExpressionEvaluator.java#L151)):*
> ```Java
>     }
> 
>     addToContext(
> ```

Add this in PMSExpressionEvaluator.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49971)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/AmbianceExpressionEvaluator.java` line 97 at r3](https://reviewable.io/reviews/harness/harness-core/49971#-NZVQZzW6af7L6GI_6Qz:-NZVQZzW6af7L6GI_6R-:bdk7ku9) ([raw file](https://github.com/harness/harness-core/blob/d209f24ede5b1384d29066ef8ab00ab9d8032fa6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/AmbianceExpressionEvaluator.java#L97)):*
> ```Java
>   @Inject private PmsFeatureFlagService pmsFeatureFlagService;
>   @Inject private PipelineRbacHelper pipelineRbacHelper;
>   @Inject EngineExpressionService engineExpressionService;
> ```

Why is this needed?
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/49971#-NZVSX7z5HwPhsAOsixU:-NZVSX7z5HwPhsAOsixV:b-xhi3m8) ([raw file](https://github.com/harness/harness-core/blob/d209f24ede5b1384d29066ef8ab00ab9d8032fa6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java#L27)):*
> ```Java
> public class ServiceVariableOverridesFunctor extends LateBindingMap {
>   private final Ambiance ambiance;
>   private final EngineExpressionService engineExpressionService;
> ```

why do you need this? 
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java` line 70 at r3](https://reviewable.io/reviews/harness/harness-core/49971#-NZVT3S6-6E8_yclePc7:-NZVT3S70LYsGoIYDVuR:b-x5pn2o) ([raw file](https://github.com/harness/harness-core/blob/d209f24ede5b1384d29066ef8ab00ab9d8032fa6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java#L70)):*
> ```Java
>     for (int i = fqnList.size() - 1; i >= 0; i--) {
>       String fqnRendered =
>           engineExpressionService.renderExpression(ambiance, fqnList.get(i), ExpressionMode.RETURN_NULL_IF_UNRESOLVED);
> ```

why do you need this?

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49971)* status: 4 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/AmbianceExpressionEvaluator.java` line 151 at r3](https://reviewable.io/reviews/harness/harness-core/49971#-NZVOUdC5udua7xqgUXw:-NZVzN6k1FaOG5b32vUt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d209f24ede5b1384d29066ef8ab00ab9d8032fa6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/AmbianceExpressionEvaluator.java#L151)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Add this in PMSExpressionEvaluator. 
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java` line 57 at r3](https://reviewable.io/reviews/harness/harness-core/49971#-NZVO4GQ5VfqE_TXVgwo:-NZVzRYDELRas8qzd9nM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d209f24ede5b1384d29066ef8ab00ab9d8032fa6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java#L57)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Use String.format and also use constants here
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java` line 60 at r3](https://reviewable.io/reviews/harness/harness-core/49971#-NZVOAk1BGUZSWqDJ-Xh:-NZVzRwB2hYU_fFaRRdx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d209f24ede5b1384d29066ef8ab00ab9d8032fa6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java#L60)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Same as above, use String.format
</blockquote></details>

Done.

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49971)* status: 4 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/AmbianceExpressionEvaluator.java` line 97 at r3](https://reviewable.io/reviews/harness/harness-core/49971#-NZVQZzW6af7L6GI_6Qz:-NZW-z3uEFxlRK6nJMxD:b7bzdj7) ([raw file](https://github.com/harness/harness-core/blob/d209f24ede5b1384d29066ef8ab00ab9d8032fa6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/AmbianceExpressionEvaluator.java#L97)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

we're returning the fqn which returns a non null value when rendered. We can't just return the nearest fqn.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/49971#-NZVOHI4328TFdQP6lTw:-NZW-vJI9Y24x7bSLOP7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d209f24ede5b1384d29066ef8ab00ab9d8032fa6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java#L25)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Move this functor to pipeline-service/service/src/main/java/io/harness/pms/expressions/functors
This should not be a part of orchestration engine.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/49971#-NZVSX7z5HwPhsAOsixU:-NZW-nTZ32GMQ5jIOLcz:b7bzdj7) ([raw file](https://github.com/harness/harness-core/blob/d209f24ede5b1384d29066ef8ab00ab9d8032fa6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java#L27)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do you need this? 
</blockquote></details>

we're returning the fqn which returns a non null value when rendered. We can't just return the nearest fqn.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java` line 70 at r3](https://reviewable.io/reviews/harness/harness-core/49971#-NZVT3S6-6E8_yclePc7:-NZW-wmA7fuZ7qreVoif:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d209f24ede5b1384d29066ef8ab00ab9d8032fa6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ServiceVariableOverridesFunctor.java#L70)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do you need this?
</blockquote></details>

Done.

**Comment by hingerabhinav** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49971)* status: 4 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/PMSExpressionEvaluator.java` line 65 at r5](https://reviewable.io/reviews/harness/harness-core/49971#-NZ_Pa7Z7WYx6Yp5qpUp:-NZ_Pa7Z7WYx6Yp5qpUq:b2nmwaw) ([raw file](https://github.com/harness/harness-core/blob/c31b811e9ff92ac0cfc93baa4d42e9b8aa340105/pipeline-service/service/src/main/java/io/harness/pms/expressions/PMSExpressionEvaluator.java#L65)):*
> ```Java
>   @Inject PmsExecutionSummaryService pmsExecutionSummaryService;
> 
>   @Inject EngineExpressionService engineExpressionService;
> ```

Use @Inject PmsEngineExpressionService pmsEngineExpressionService;

**Comment by hingerabhinav** [comment]
trigger uts

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49971)* status: 4 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/PMSExpressionEvaluator.java` line 65 at r5](https://reviewable.io/reviews/harness/harness-core/49971#-NZ_Pa7Z7WYx6Yp5qpUp:-NZa2n9c-oo8BXRQTu7K:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c31b811e9ff92ac0cfc93baa4d42e9b8aa340105/pipeline-service/service/src/main/java/io/harness/pms/expressions/PMSExpressionEvaluator.java#L65)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Use @Inject PmsEngineExpressionService pmsEngineExpressionService;
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49971)* status: 4 file(s) to review. 5. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49971)* status: 1. unresolved discussions.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49971)* status: 1. unresolved discussions.

**Comment by hingerabhinav** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49971)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49971)* status: 1. unresolved discussions.

**Comment by hingerabhinav** [comment]
trigger review

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Comment by hingerabhinav** [comment]
trigger review

**Pull request merged**
