### PR TITLE
[feat]: [CDS-46690]: active service instance api for env details

### PR DESCRIPTION
**Pull request by Abhishek-CDC**
## Describe your changes

created API for ActiveServiceInstances for Env Dashboard, similar to we have in service-env dashboard

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40217)

### CODE REVIEW

**Review by abhinavmittal-harness — CHANGES_REQUESTED** [review]
> Reviewed 9 of 12 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40217)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java` line 1940 at r2](https://reviewable.io/reviews/harness/harness-core/40217#-NHzMQFv9TxKVmt9RGga:-NHzMQFv9TxKVmt9RGgb:b-l9l0w0) ([raw file](https://github.com/harness/harness-core/blob/40929f4f5a6a0ec6b471a5ac4abc0516e9489209/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java#L1940)):*
> ```Java
>       Map<String,
>           Map<String,
>               Map<String,
> ```

nit: Break this method and add some comments
___
*[`126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java` line 244 at r2](https://reviewable.io/reviews/harness/harness-core/40217#-NHzMWodD8sIEPpc1eN_:-NHzMWodD8sIEPpc1eNa:b-5o2lte) ([raw file](https://github.com/harness/harness-core/blob/40929f4f5a6a0ec6b471a5ac4abc0516e9489209/126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java#L244)):*
> ```Java
>     if (envIdentifier != null) {
>       criteria.and(InstanceKeys.envIdentifier).is(envIdentifier);
>     }
> ```

Add index

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40217)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by Abhishek-CDC** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java` line 1940 at r2](https://reviewable.io/reviews/harness/harness-core/40217#-NHzMQFv9TxKVmt9RGga:-NI7KzaI5wUCrxkVtMFN:bujqfi5) ([raw file](https://github.com/harness/harness-core/blob/40929f4f5a6a0ec6b471a5ac4abc0516e9489209/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java#L1940)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

nit: Break this method and add some comments
</blockquote></details>

resolved

**Comment by Abhishek-CDC** [comment]
*[`126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java` line 244 at r2](https://reviewable.io/reviews/harness/harness-core/40217#-NHzMWodD8sIEPpc1eN_:-NI7L0PU7P4sgPhPR0gj:bujqfi5) ([raw file](https://github.com/harness/harness-core/blob/40929f4f5a6a0ec6b471a5ac4abc0516e9489209/126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java#L244)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Add index
</blockquote></details>

resolved

**Review by Y0709 — APPROVED** [review]
> Reviewed 7 of 12 files at r1, 2 of 3 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40217)* status: 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by abhinavmittal-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40217)* status: :shipit: complete! ✓

**Pull request merged**
