### PR TITLE
feat: [PL-29895]: Added settings for force delete

### PR DESCRIPTION
**Pull request by meenakshi-harness**
## Describe your changes
1. Added Force Delete as Account Level Setting
2. Integrated the setting with connector force delete.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40553)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 76 at r3](https://reviewable.io/reviews/harness/harness-core/40553#-NHh5V9R699WPi9r6DiW:-NHh5V9R699WPi9r6DiX:bobl8f3) ([raw file](https://github.com/harness/harness-core/blob/5b780d079eefbe6630c072ae799fad97ccf9b96f/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L76)):*
> ```YAML
>     category: CORE
>     defaultValue: false
>     valueType: BOOLEAN
> ```

minor : `allowOverrides` seems to be missing



_Code quote:_
```YAML
  - identifier: enable_force_delete
    name: Enable Force Delete of Harness Resources
    category: CORE
    defaultValue: false
    valueType: BOOLEAN
```

**Review by pbarapatre10 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40553#-:-NHh7jhrE4YHRn2ZqYF4:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40553)* status: 4 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 76 at r3](https://reviewable.io/reviews/harness/harness-core/40553#-NHh5V9R699WPi9r6DiW:-NHhA7xy6umvup-OA8O5:bvepbr2) ([raw file](https://github.com/harness/harness-core/blob/5b780d079eefbe6630c072ae799fad97ccf9b96f/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L76)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor : `allowOverrides` seems to be missing
</blockquote></details>

I don't think we should need allowOverrides for Accounts scope setting. @tiwaritejas can you confirm?

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40553)* status: 1. unresolved discussions.

**Review by tiwaritejas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40553)* status: 1. unresolved discussions. 

___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 76 at r3](https://reviewable.io/reviews/harness/harness-core/40553#-NHh5V9R699WPi9r6DiW:-NHhAsK7-ib8FnR2HxFK:b7lucup) ([raw file](https://github.com/harness/harness-core/blob/5b780d079eefbe6630c072ae799fad97ccf9b96f/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L76)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

I don't think we should need allowOverrides for Accounts cope setting. @tiwaritejas can you confirm? 
</blockquote></details>

allowOverrides is not required, correct

**Review by tiwaritejas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40553)* status: :shipit: complete! ✓

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 76 at r3](https://reviewable.io/reviews/harness/harness-core/40553#-NHh5V9R699WPi9r6DiW:-NHhL4LL-Zl_-gK5mBKH:b-3wjk5s) ([raw file](https://github.com/harness/harness-core/blob/5b780d079eefbe6630c072ae799fad97ccf9b96f/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L76)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

allowOverrides is not required, correct
</blockquote></details>

Thanks for clarifying. I did ask because I see 'allowOverrides' attribute marked as NotNull https://github.com/harness/harness-core/blob/6a8bc798096346f678be85bc48f7ac8e4b1ac6d1/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/entities/Setting.java#L56 
I believe it will pick `false`  by default, so should be fine.

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40553)* status: :shipit: complete! ✓

**Pull request merged**
