### PR TITLE
feat: [CDS-78680]: return distinct repos for Service entities

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
Add API to collect distinct repos for service entities. Did not create a single resource for NG entities since there was not much code that could be extracted out as common. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52427)

### CODE REVIEW

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 1196 at r2](https://reviewable.io/reviews/harness/harness-core/52427#-NdYq0thEyiJneS_cchC:-NdYq0thEyiJneS_cchD:b-s8p3ye) ([raw file](https://github.com/harness/harness-core/blob/4123e24a32dc0849959a1e1228676fb423ce1565/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L1196)):*
> ```Java
>           NGCommonEntityConstants.PROJECT_KEY) @ProjectIdentifier String projectIdentifier,
>       @Parameter(description = "Specify true if all accessible Services are to be included") @QueryParam(
>           "includeAllServicesAccessibleAtScope") boolean includeAllServicesAccessibleAtScope) {
> ```

```
includeAllServicesAccessibleAtScope
``` 
do we need this for repo list ?

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustom.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/52427#-NdYrVjU0v8wskStVNw9:-NdYrVjU0v8wskStVNwA:b1hr4p5) ([raw file](https://github.com/harness/harness-core/blob/4123e24a32dc0849959a1e1228676fb423ce1565/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustom.java#L51)):*
> ```Java
>       boolean notDeleted, boolean loadFromCache, boolean loadFromFallbackBranch);
> 
>   List<String> getListOfDistinctRepos(Criteria criteria);
> ```

should we have accountId field here to make, we cannot query cross account data using this method ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52427)* status: 7 file(s) to review. 0 of 2 approvals obtained.

**Comment by hingerabhinav** [comment]
> _[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 1196 at r2](https://reviewable.io/reviews/harness/harness-core/52427#-NdYq0thEyiJneS_cchC:-NdYq0thEyiJneS_cchD:b-s8p3ye) ([raw file](https://github.com/harness/harness-core/blob/4123e24a32dc0849959a1e1228676fb423ce1565/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L1196)):_
> 
> > ```java
> >           NGCommonEntityConstants.PROJECT_KEY) @ProjectIdentifier String projectIdentifier,
> >       @Parameter(description = "Specify true if all accessible Services are to be included") @QueryParam(
> >           "includeAllServicesAccessibleAtScope") boolean includeAllServicesAccessibleAtScope) {
> > ```
> 
> ```
> includeAllServicesAccessibleAtScope
> ```
> 
> do we need this for repo list ?

@yogesh-chauhan we are still finalising the mocks for service selection, we might need it in case it is similar to templates sidebar where all services at scope are shown together. In that case, we will need repos for all levels of services

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustom.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/52427#-NdYrVjU0v8wskStVNw9:-NdZ2vp56b9MXZJtdBvz:b-imbmg7) ([raw file](https://github.com/harness/harness-core/blob/4123e24a32dc0849959a1e1228676fb423ce1565/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustom.java#L51)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

@yogesh-chauhan Users should use service layer methods where we have exposed account id etc. Repository methods should not be used directly right? 
</blockquote></details>

Ideally yes. I think its okay as long as service layer has the checks

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52427)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52427)* status: :shipit: complete! ✓

**Comment by hingerabhinav** [comment]
trigger review

**Pull request merged**
