### PR TITLE
[feat]:[CDS-43529]: Add exception to the blueprint steps

### PR DESCRIPTION
**Pull request by nassergonzalez**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37807)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 23 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 19 Code issues 
* Anti-pattern 2 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37807)

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 24 files at r2, 22 of 24 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37807)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateBPStep.java` line 411 at r3](https://reviewable.io/reviews/harness/harness-core/37807#-NCsSmUpEGE0a3Mm_qcZ:-NCsSmUpEGE0a3Mm_qc_:bnzewzm) ([raw file](https://github.com/harness/harness-core/blob/c0e7d48a2f78747a53da8a81d251ec50e3c5d760/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateBPStep.java#L411)):*
> ```Java
>           if (fileNodeDTO.getContent() != null) {
>             fileMap.put(f.getName(),
>                 engineExpressionService.renderExpression(ambiance, fileNodeDTO.getContent().replaceAll("\\r", "")));
> ```

didn't pay attention to that earlier, whats the reason for: "fileNodeDTO.getContent().replaceAll("\\r", ""))"
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/37807#-NCsTVDk-8VsJQZnsxIT:-NCsTVDk-8VsJQZnsxIU:b-yh3cpa) ([raw file](https://github.com/harness/harness-core/blob/c0e7d48a2f78747a53da8a81d251ec50e3c5d760/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java#L74)):*
> ```Java
>         while (true) {
>           String provisioningState = azureManagementClient.getARMDeploymentStatus(context);
>           logCallback.saveExecutionLog(color(
> ```

I don't think we need to change this one, let's keep different style only for successful or failed.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java` line 176 at r3](https://reviewable.io/reviews/harness/harness-core/37807#-NCsU5rl990Nvr6uk9lB:-NCsU5rl990Nvr6uk9lC:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/c0e7d48a2f78747a53da8a81d251ec50e3c5d760/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java#L176)):*
> ```Java
>           String assignmentProvisioningStatus = getAssignmentProvisioningStatus(context, azureBlueprintClient);
>           logCallback.saveExecutionLog(
>               color(String.format("Deployment Status for - [%s] is [%s]", assignmentName, assignmentProvisioningStatus),
> ```

same here
___
*[`980-commons/src/main/java/io/harness/exception/ngexception/AzureBPTaskException.java` line 17 at r3](https://reviewable.io/reviews/harness/harness-core/37807#-NCsUWej11Tke0ntZnWF:-NCsUWej11Tke0ntZnWG:b-ck8s5i) ([raw file](https://github.com/harness/harness-core/blob/c0e7d48a2f78747a53da8a81d251ec50e3c5d760/980-commons/src/main/java/io/harness/exception/ngexception/AzureBPTaskException.java#L17)):*
> ```Java
> 
> import java.util.EnumSet;
> ```

Please add owner team
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureBPDeploymentException.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/37807#-NCsUagKDcHTGTyvDIkk:-NCsUagKDcHTGTyvDIkl:b-ck8s5i) ([raw file](https://github.com/harness/harness-core/blob/c0e7d48a2f78747a53da8a81d251ec50e3c5d760/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureBPDeploymentException.java#L10)):*
> ```Java
> package io.harness.exception.runtime.azure;
> 
> public class AzureBPDeploymentException extends AzureBPRuntimeException {
> ```

Please add owner team
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureBPRuntimeException.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/37807#-NCsUfqn5lX1z1x5N1Qq:-NCsUfqn5lX1z1x5N1Qr:b-ck8s5i) ([raw file](https://github.com/harness/harness-core/blob/c0e7d48a2f78747a53da8a81d251ec50e3c5d760/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureBPRuntimeException.java#L10)):*
> ```Java
> package io.harness.exception.runtime.azure;
> 
> public class AzureBPRuntimeException extends RuntimeException {
> ```

Please add owner team

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37807)* status: 6 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateBPStep.java` line 411 at r3](https://reviewable.io/reviews/harness/harness-core/37807#-NCsSmUpEGE0a3Mm_qcZ:-NCszcK5BwVNDOy6lg9i:b-d2z5nq) ([raw file](https://github.com/harness/harness-core/blob/c0e7d48a2f78747a53da8a81d251ec50e3c5d760/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateBPStep.java#L411)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

didn't pay attention to that earlier, whats the reason for: "fileNodeDTO.getContent().replaceAll("\\r", ""))"
</blockquote></details>

When I was inspecting the content of the files, i could see that the content of the inline files had \r at the end of every line so I though that it will be better to remove it here. With that said, I did that while i was investigating something because I thought that could be relevant for the investigation but at the end it didn't. So right now we can remove this or leave it as it is, nothing should change
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/37807#-NCsTVDk-8VsJQZnsxIT:-NCt-MOTDbATdicLogs0:b57t6kr) ([raw file](https://github.com/harness/harness-core/blob/c0e7d48a2f78747a53da8a81d251ec50e3c5d760/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java#L74)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

I don't think we need to change this one, let's keep different style only for successful or failed.
</blockquote></details>

Didn't Alex said to put in bold everything that was "an azure log" and we decided that this was an azure log? I am happy removing it if that is what we decide but just to double check
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java` line 176 at r3](https://reviewable.io/reviews/harness/harness-core/37807#-NCsU5rl990Nvr6uk9lB:-NCt-a2_Ew83t8z4HXxY:b-as4bkz) ([raw file](https://github.com/harness/harness-core/blob/c0e7d48a2f78747a53da8a81d251ec50e3c5d760/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java#L176)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Answered before
___
*[`980-commons/src/main/java/io/harness/exception/ngexception/AzureBPTaskException.java` line 17 at r3](https://reviewable.io/reviews/harness/harness-core/37807#-NCsUWej11Tke0ntZnWF:-NCt-hTc5YdQlYiwrpfX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0e7d48a2f78747a53da8a81d251ec50e3c5d760/980-commons/src/main/java/io/harness/exception/ngexception/AzureBPTaskException.java#L17)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Please add owner team
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureBPDeploymentException.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/37807#-NCsUagKDcHTGTyvDIkk:-NCt-ly9-sBF6iBsXbot:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0e7d48a2f78747a53da8a81d251ec50e3c5d760/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureBPDeploymentException.java#L10)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Please add owner team
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/exception/runtime/azure/AzureBPRuntimeException.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/37807#-NCsUfqn5lX1z1x5N1Qq:-NCt-ojv9grgfiPTzaew:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0e7d48a2f78747a53da8a81d251ec50e3c5d760/980-commons/src/main/java/io/harness/exception/runtime/azure/AzureBPRuntimeException.java#L10)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Please add owner team
</blockquote></details>

Done.

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 24 files at r3, 4 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37807)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/37807#-NCsTVDk-8VsJQZnsxIT:-NCtneKiCktU6vN5aCzf:b-un183j) ([raw file](https://github.com/harness/harness-core/blob/c0e7d48a2f78747a53da8a81d251ec50e3c5d760/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java#L74)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

Didn't Alex said to put in bold everything that was "an azure log" and we decided that this was an azure log? I am happy removing it if that is what we decide but just to double check
</blockquote></details>

No, I was saying that for Azure Web Apps ( we were asked to use a different style for the log we are streaming rom azure).
Here it is not that case.
We should use different style only for success / failure logs (be cause we do that in other places).

**Review by tmacari-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37807)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37807)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/37807#-NCsTVDk-8VsJQZnsxIT:-NCuM7v55XjoDBAy4COl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0e7d48a2f78747a53da8a81d251ec50e3c5d760/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java#L74)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

No, I was saying that for Azure Web Apps ( we were asked to use a different style for the log we are streaming rom azure).
Here it is not that case.
We should use different style only for success / failure logs (be cause we do that in other places).
</blockquote></details>

Done.

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37807)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — DISMISSED** [review]
:lgtm:

> Reviewed 12 of 24 files at r2, 23 of 24 files at r3, 3 of 5 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37807#-:-ND394phDovqRkD3xVeL:bnfp4nl)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37807)* status: :shipit: complete! ✓

**Pull request merged**
