### PR TITLE
fix: [CDS-54943]: handle scoped refs in list calls for service/env

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes

1. Create 2 new internal APIs for listing services, envs 
2. These APIs take list of scoped refs. Eg. [account.ser1, org.ser1, ser1]
3. Use these APIs for CV NG client.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44920)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 431 at r4](https://reviewable.io/reviews/harness/harness-core/44920#-NQ8tvh26hI8k3gDAFWm:-NQ8tvh26hI8k3gDAFWn:b-qm8tzu) ([raw file](https://github.com/harness/harness-core/blob/a0097e18a642e7a4dcf7a9079502221008a761aa/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L431)):*
> ```Java
>       @Parameter(description = "List of EnvironmentIds") @QueryParam("envIdentifiers") List<String> envIdentifiers) {
>     accessControlClient.checkForAccessOrThrow(ResourceScope.of(accountId, orgIdentifier, projectIdentifier),
>         Resource.of(ENVIRONMENT, null), ENVIRONMENT_VIEW_PERMISSION, "Unauthorized to list environments");
> ```

this ACL check might not be accurate since we are checking only at project level

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 472 at r4](https://reviewable.io/reviews/harness/harness-core/44920#-NQ8u6vS5CGfCsqRFinb:-NQ8u6vS5CGfCsqRFinc:br7qtus) ([raw file](https://github.com/harness/harness-core/blob/a0097e18a642e7a4dcf7a9079502221008a761aa/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L472)):*
> ```Java
>       @Parameter(description = "List of ServicesIds") @QueryParam(
>           "serviceIdentifiers") List<String> serviceIdentifiers) {
>     accessControlClient.checkForAccessOrThrow(ResourceScope.of(accountId, orgIdentifier, projectIdentifier),
> ```

this ACL check might not be accurate since we are checking only at project level

**Review by deepak-harness — DISMISSED** [review]
> Reviewed 1 of 6 files at r2, 2 of 7 files at r3, 4 of 7 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44920)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 867 at r5](https://reviewable.io/reviews/harness/harness-core/44920#-NQA7mwt4Ybqx0KRH5Li:-NQA7mwt4Ybqx0KRH5Lj:bmfqkga) ([raw file](https://github.com/harness/harness-core/blob/f3e846317f36d4a48a030797979e8da3fcddae6f/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L867)):*
> ```Java
> 
>   private void checkAccessForListingAtScope(
>       String accountId, String orgIdentifier, String projectIdentifier, List<String> envIdentifiers) {
> ```

can we just return at the beginning ?
```
if isEmpty(envIdentifier) {
 return
}
```

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44920)* status: 15 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 431 at r4](https://reviewable.io/reviews/harness/harness-core/44920#-NQ8tvh26hI8k3gDAFWm:-NQAE5FWDDAi0jMRlfDM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a0097e18a642e7a4dcf7a9079502221008a761aa/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L431)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this ACL check might not be accurate since we are checking only at project level
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 867 at r5](https://reviewable.io/reviews/harness/harness-core/44920#-NQA7mwt4Ybqx0KRH5Li:-NQAE5faBpdeDLSp0pfe:b-i24ku) ([raw file](https://github.com/harness/harness-core/blob/f3e846317f36d4a48a030797979e8da3fcddae6f/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L867)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we just return at the beginning ?
```
if isEmpty(envIdentifier) {
 return
}
```
</blockquote></details>

We have to check access for listing at that scope even if envIds are not present. That is done along with checking for project level listing below.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 472 at r4](https://reviewable.io/reviews/harness/harness-core/44920#-NQ8u6vS5CGfCsqRFinb:-NQAENrl3cQZNA-i9yq_:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a0097e18a642e7a4dcf7a9079502221008a761aa/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L472)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this ACL check might not be accurate since we are checking only at project level
</blockquote></details>

Done

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 1 of 6 files at r2, 2 of 7 files at r3, 4 of 7 files at r4, 7 of 9 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44920)* status: 2 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 6 files at r2, 2 of 7 files at r3, 5 of 7 files at r4, 7 of 9 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44920)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44920)* status: :shipit: complete! ✓

**Pull request merged**
