### PR TITLE
feat: [PL-29443]: Added forceDelete query param in connector delete api

### PR DESCRIPTION
**Pull request by meenakshi-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39514)

### CODE REVIEW

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 15 of 17 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39514)* status: Some of the checks are too old. 18 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/test/java/io/harness/connector/impl/DefaultConnectorServiceImplTest.java` line 398 at r3](https://reviewable.io/reviews/harness/harness-core/39514#-NGHLM-J1ZGeQSkUf9j0:-NGHLM-J1ZGeQSkUf9j1:b-s6wd6r) ([raw file](https://github.com/harness/harness-core/blob/a784e3c2cbe846f326dcc9b948def4972443208b/440-connector-nextgen/src/test/java/io/harness/connector/impl/DefaultConnectorServiceImplTest.java#L398)):*
> ```Java
>   public void testDelete_withForceDeleteAsTrue() {
>     createConnector(identifier, name);
>     when(connectorEntityReferenceHelper.deleteConnectorEntityReferenceWhenConnectorGetsDeleted(
> ```

Add test case for the case when deleteConnectorEntityReferenceWhenConnectorGetsDeleted throws an exception and forceDelete is true.

**Review by tiwaritejas — DISMISSED** [review]
> Reviewed 1 of 6 files at r1, 15 of 17 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39514)* status: Some of the checks are too old. 1 change requests. 1 of 2 approvals obtained.

**Comment by meenakshi-harness** [comment]
trigger buildnum

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39514)* status: 8 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39514)* status: :shipit: complete! ✓

**Pull request merged**
