### PR TITLE
fix: [DEL-4606]: generate error msg for unsatisfied capabilities

### PR DESCRIPTION
**Pull request by xingchi-jin**
## Describe your changes
fix error message to print the capabilities none of the eligible delegates can do
added a unit test

Tests pass

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36755)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36755)

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/iterator/ValidationFailedTaskMessageHelper.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/36755#-NAQwMu83NPn1NO6eDHj:-NAQwMu83NPn1NO6eDHk:b-hio73b) ([raw file](https://github.com/harness/harness-core/blob/309f5ff8df23e4654246b5b1864b1003c7a10a0d/400-rest/src/main/java/io/harness/iterator/ValidationFailedTaskMessageHelper.java#L47)):*
> ```Java
>                 .map(ExecutionCapability::fetchCapabilityBasis)
>                 .collect(Collectors.toSet());
>         Set<String> eligibleDelegateIdsSet = new HashSet<>(delegateTask.getEligibleToExecuteDelegateIds());
> ```

this is already unique, you don't need to add in a set

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/iterator/ValidationFailedTaskMessageHelper.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/36755#-NAQwmKn4RI678pHKMJq:-NAQwmKn4RI678pHKMJr:b-b5xknj) ([raw file](https://github.com/harness/harness-core/blob/309f5ff8df23e4654246b5b1864b1003c7a10a0d/400-rest/src/main/java/io/harness/iterator/ValidationFailedTaskMessageHelper.java#L34)):*
> ```Java
> @Singleton
> @Slf4j
> public final class ValidationFailedTaskMessageHelper {
> ```

can you post a screenshot of how the error message look like in the UI?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36755)* status: 0 of 1 approvals obtained.

**Review by xingchi-jin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36755)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/iterator/ValidationFailedTaskMessageHelper.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/36755#-NAQwMu83NPn1NO6eDHj:-NAR-LrPARnXMsDKO5JK:bgcwexd) ([raw file](https://github.com/harness/harness-core/blob/309f5ff8df23e4654246b5b1864b1003c7a10a0d/400-rest/src/main/java/io/harness/iterator/ValidationFailedTaskMessageHelper.java#L47)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this is already unique, you don't need to add in a set
</blockquote></details>

Used Set here because line 58 needs to use it to filter. Maybe preferred to keep this way?

**Comment by xingchi-jin** [comment]
Screen Shot 2022-08-29 at 6 16 53 PM

**Comment by xingchi-jin** [comment]
Screen Shot 2022-08-30 at 1 12 15 PM
Screen Shot 2022-08-30 at 1 12 25 PM

**Comment by xingchi-jin** [comment]
trigger ti3

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 7 of 8 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36755)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 7 of 8 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36755)* status: :shipit: complete! ✓

**Pull request merged**
