### PR TITLE
fix: [PIE-1338]: Adding support for automatic traversing for objects inside ParameterField

### PR DESCRIPTION
**Pull request by archit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32288)

### CODE REVIEW

**Comment by archit-harness** [comment]
trigger messagecheck

**Review by namanvermah — COMMENTED** [review]
> Reviewed 6 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32288)* status: 24 file(s) to review. 0 of 2 approvals obtained.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 18 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32288#-:-N00lY_B9B16Dk3bOT-V:bnfp4nl)* status: 24 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32288#-:-N00m10v6sxx3sXIUmqO:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
