### PR TITLE
feat: [CDS-35381]: create stack support

### PR DESCRIPTION
**Pull request by tmacari-harness**
[CDS-35381]: create stack support
Delete stack inherited support
Support fetching files from S3

[CDS-35381]: https://harness.atlassian.net/browse/CDS-35381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31866)

### CODE REVIEW

**Comment by tmacari-harness** [comment]
trigger MessageMetadata-message_metadata

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 80 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31866)* status: 79 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/test/resources/recaster/alias/alias.txt, line 282 at r1](https://reviewable.io/reviews/harness/harness-core/31866#-MzOzZw1-TdyaFtnoaCv:-MzOzZw1-TdyaFtnoaCw:b-63n44k) ([raw file](https://github.com/harness/harness-core/blob/3a8542a4b0a14a2984f278e1fa7e7636970018bb/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L282)):*
> ```help
> io.harness.yaml.core.parallelStepElementConfig
> io.harness.cdng.envGroup.beans.EnvironmentGroupConfig
> io.harness.cdng.provision.cloudformation.CloudformationCreateStackStepInfo
> ```

Do not change aliases even if you change class names/packages . This is an identifier for mongo to deserialize the saved data (json) in to a class tagged with this alias. If you change this mongo will not be able to deserialize already saved fields
___
*[125-cd-nextgen/src/test/resources/recaster/alias/alias.txt, line 289 at r1](https://reviewable.io/reviews/harness/harness-core/31866#-MzP-G9UD_ja_9p8Sdy1:-MzP-G9UD_ja_9p8Sdy2:b-ekx31v) ([raw file](https://github.com/harness/harness-core/blob/3a8542a4b0a14a2984f278e1fa7e7636970018bb/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L289)):*
> ```help
> io.harness.cdng.provision.cloudformation.CloudformationDeleteStackStepConfiguration
> io.harness.cdng.provision.cloudformation.CloudformationDeleteStackStepInfo
> io.harness.cdng.provision.cloudformation.CloudformationDeleteStackBaseStepInfo
> ```

ditto for these as well
___
*[125-cd-nextgen/src/test/resources/recaster/alias/alias.txt, line 300 at r1](https://reviewable.io/reviews/harness/harness-core/31866#-MzP-IdZ7XJMK4B8YlSk:-MzP-Id_9veG7QXkyTpS:b3vpnpv) ([raw file](https://github.com/harness/harness-core/blob/3a8542a4b0a14a2984f278e1fa7e7636970018bb/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L300)):*
> ```help
> io.harness.cdng.provision.cloudformation.S3UrlCloudformationTemplateFileSpec
> io.harness.cdng.provision.cloudformation.RemoteCloudformationTemplateFileSpec
> io.harness.cdng.manifest.yaml.S3UrlStoreConfig
> ```

addin is ok

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31866)* status: 79 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/test/resources/recaster/alias/alias.txt, line 282 at r1](https://reviewable.io/reviews/harness/harness-core/31866#-MzOzZw1-TdyaFtnoaCv:-MzP-nut6w6dEW2Op9jX:b-uan157) ([raw file](https://github.com/harness/harness-core/blob/3a8542a4b0a14a2984f278e1fa7e7636970018bb/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L282)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Do not change aliases even if you change class names/packages . This is an identifier for mongo to deserialize the saved data (json) in to a class tagged with this alias. If you change this mongo will not be able to deserialize already saved fields
</blockquote></details>

ok, for now we merge this in a feature branch, The class aliases I changed are not yet in master so I decided to adjust them to mach package/class name (as it is safe for now).
___
*[125-cd-nextgen/src/test/resources/recaster/alias/alias.txt, line 289 at r1](https://reviewable.io/reviews/harness/harness-core/31866#-MzP-G9UD_ja_9p8Sdy1:-MzP0UwTAgVaXe4jRFj5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3a8542a4b0a14a2984f278e1fa7e7636970018bb/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L289)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

ditto for these as well
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/test/resources/recaster/alias/alias.txt, line 300 at r1](https://reviewable.io/reviews/harness/harness-core/31866#-MzP-IdZ7XJMK4B8YlSk:-MzP0WSr0UaS7WbisbML:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3a8542a4b0a14a2984f278e1fa7e7636970018bb/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L300)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

addin is ok
</blockquote></details>

Done.

**Review by hextechpal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31866)* status: 79 file(s) to review. 

___
*[125-cd-nextgen/src/test/resources/recaster/alias/alias.txt, line 282 at r1](https://reviewable.io/reviews/harness/harness-core/31866#-MzOzZw1-TdyaFtnoaCv:-MzP6Um15Ln2cD9nZWbp:bb6u032) ([raw file](https://github.com/harness/harness-core/blob/3a8542a4b0a14a2984f278e1fa7e7636970018bb/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L282)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

ok, for now we merge this in a feature branch, The class aliases I changed are not yet in master so I decided to adjust them to mach package/class name (as it is safe for now).
</blockquote></details>

Cool

**Review by nassergonzalez — CHANGES_REQUESTED** [review]
> Reviewed 64 of 80 files at r1, 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31866)* status: Some of the checks are too old. 1 change requests. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationAbstractTaskHandler.java, line 48 at r2](https://reviewable.io/reviews/harness/harness-core/31866#-Mzo-FEf6kXI1gI-bZtN:-Mzo-FEf6kXI1gI-bZtO:bk9jo9v) ([raw file](https://github.com/harness/harness-core/blob/96c7a9498593baf67bbe04e7ca951dd6f625e733/930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationAbstractTaskHandler.java#L48)):*
> ```Java
>   @Inject CloudformationBaseHelper cloudformationBaseHelper;
>   @Inject protected AWSCloudformationClient awsCloudformationClient;
>   @Inject protected AwsCFHelperServiceDelegate awsCFHelperServiceDelegate;
> ```

It looks like this class is not used
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationDeleteStackTaskHandler.java, line 40 at r2](https://reviewable.io/reviews/harness/harness-core/31866#-Mzo1MFaBhlj2vlbf0BZ:-Mzo1MFaBhlj2vlbf0B_:b-z8wu3m) ([raw file](https://github.com/harness/harness-core/blob/96c7a9498593baf67bbe04e7ca951dd6f625e733/930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationDeleteStackTaskHandler.java#L40)):*
> ```Java
>       logCallback.saveExecutionLog("Stack does not exist", ERROR);
>       return CloudformationTaskNGResponse.builder()
>           .commandExecutionStatus(CommandExecutionStatus.SUCCESS)
> ```

Should we not return this as error as the stack doesn't exist?

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31866)* status: Some of the checks are too old. 1 change requests. 2. unresolved discussions. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationAbstractTaskHandler.java, line 48 at r2](https://reviewable.io/reviews/harness/harness-core/31866#-Mzo-FEf6kXI1gI-bZtN:-MzoAz5nDcQLL1IQcMgL:b-8dpk9o) ([raw file](https://github.com/harness/harness-core/blob/96c7a9498593baf67bbe04e7ca951dd6f625e733/930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationAbstractTaskHandler.java#L48)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

It looks like this class is not used
</blockquote></details>

it is used in subclasses
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationDeleteStackTaskHandler.java, line 40 at r2](https://reviewable.io/reviews/harness/harness-core/31866#-Mzo1MFaBhlj2vlbf0BZ:-MzoBO8g8Iu9OfbDKow9:blq5q9k) ([raw file](https://github.com/harness/harness-core/blob/96c7a9498593baf67bbe04e7ca951dd6f625e733/930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationDeleteStackTaskHandler.java#L40)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

Should we not return this as error as the stack doesn't exist?
</blockquote></details>

In CG it behaves like that, and in case the stack is not found we do not fail the execution.

**Review by nassergonzalez — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31866)* status: Some of the checks are too old.

**Pull request merged**
