### PR TITLE
fix: [DEL-5236]: Filter list of PT with state task_assigned

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
- Filter by state TASK_ASSIGNED to fetch list of assigned PT's
- Improved log statements
- UnSet Assigntry count when PT gets reset 
- Remove unused rebalance method

Test
-PT Sanity

## Checklist
- [ x] I've documented the changes in the PR description.
- [ x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39246)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java` line 129 at r2](https://reviewable.io/reviews/harness/harness-core/39246#-NFPfGce9P6prtaDgwW-:-NFPfGcfABad1VUhj17N:b-m32tes) ([raw file](https://github.com/harness/harness-core/blob/222249ac236d5ed6cc10395a2cdfcb831d670a60/400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java#L129)):*
> ```Java
>       DelegateTask validationTask = getValidationTask(taskRecord);
>       if (validationTask == null) {
>         log.info("Getting validation task null for perpetual task id {}.", taskId);
> ```

do we need to return here?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39246)* status: 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java` line 129 at r2](https://reviewable.io/reviews/harness/harness-core/39246#-NFPfGce9P6prtaDgwW-:-NFPnjm0E99Wylgpq5vs:b-7r2cz) ([raw file](https://github.com/harness/harness-core/blob/222249ac236d5ed6cc10395a2cdfcb831d670a60/400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java#L129)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

do we need to return here?
</blockquote></details>

yes, good idea. return and as well as update reason and assign try. If more than 10 , mark as invalid

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java` line 129 at r2](https://reviewable.io/reviews/harness/harness-core/39246#-NFPfGce9P6prtaDgwW-:-NFPnzaP0IfqYMe-FnJK:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/222249ac236d5ed6cc10395a2cdfcb831d670a60/400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java#L129)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

yes, good idea. return and as well as update reason and assign try. If more than 10 , mark as invalid
</blockquote></details>

updated

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java` line 129 at r2](https://reviewable.io/reviews/harness/harness-core/39246#-NFPfGce9P6prtaDgwW-:-NFS9qnOAv_IpnhG8JfG:b-przn59) ([raw file](https://github.com/harness/harness-core/blob/222249ac236d5ed6cc10395a2cdfcb831d670a60/400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java#L129)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

updated
</blockquote></details>

i will fix this on next PR

**Review by raghuAtWings — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39246)* status: :shipit: complete! ✓

**Pull request merged**
