### PR TITLE
feat: [PLG-2225]: Additional telemetry

### PR DESCRIPTION
**Pull request by thomas-grasman**
## Describe your changes
Added more back end telemetry for the subscription process.

Events added:
- Subscription Payment Initiated
- Subscription Payment Failed
- Subscription Invoice Finalize Initiated
- Subscription Invoice Finalize Succeeded
- Subscription Deletion Initiated
- Subscription Deletion Succeeded
- Subscription Update Initiated
- Subscription Update Succeeded

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47683)

### CODE REVIEW

**Comment by thomas-grasman** [comment]
trigger uts

**Comment by thomas-grasman** [comment]
trigger messagecheck

**Review by pranil-harness — APPROVED** [review]

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47683)* status: 11 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/handlers/InvoicePaymentSucceedHandler.java` line 79 at r1](https://reviewable.io/reviews/harness/harness-core/47683#-NVFckrz0legwSv5NDFD:-NVFckrz0legwSv5NDFE:b-ue3992) ([raw file](https://github.com/harness/harness-core/blob/9497594f342c073400b073775b37c399f3ce5402/930-ng-license-manager/src/main/java/io/harness/subscription/handlers/InvoicePaymentSucceedHandler.java#L79)):*
> ```Java
> 
>     HashMap<String, Object> properties = new HashMap<>();
>     telemetryReporter.sendTrackEvent(SUBSCRIPTION_TELEMETRY_EVENT_INITIATED, invoice.getCustomerEmail(),
> ```

you need to send telemetryReporter.sendIdentifyEvent() before a track event because first user will registered and then his activity can be tracked



_Code snippet:_
```Java
io.harness.telemetry.TelemetryReporter#sendIdentifyEvent
```
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/handlers/InvoicePaymentSucceedHandler.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/47683#-NVFd404Btkmwc5TowXd:-NVFd404Btkmwc5TowXe:bv40ud8) ([raw file](https://github.com/harness/harness-core/blob/9497594f342c073400b073775b37c399f3ce5402/930-ng-license-manager/src/main/java/io/harness/subscription/handlers/InvoicePaymentSucceedHandler.java#L89)):*
> ```Java
>     telemetryReporter.sendTrackEvent(SUBSCRIPTION_TELEMETRY_EVENT_SUCCESS, invoice.getCustomerEmail(),
>         accountIdentifier, properties,
>         ImmutableMap.<Destination, Boolean>builder().put(Destination.AMPLITUDE, true).build(),
> ```

are we sure we only need to send it to Amplitude? and not to other destinations like marketo, big-query etc.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/handlers/InvoiceUpdatedHandler.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/47683#-NVFdFE8A8zgiNW8bq7L:-NVFdFE9BqjrZTxPrBTI:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/9497594f342c073400b073775b37c399f3ce5402/930-ng-license-manager/src/main/java/io/harness/subscription/handlers/InvoiceUpdatedHandler.java#L56)):*
> ```Java
> 
>     HashMap<String, Object> properties = new HashMap<>();
>     telemetryReporter.sendTrackEvent(SUBSCRIPTION_TELEMETRY_EVENT_INITIATED, invoice.getCustomerEmail(),
> ```

same as above
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/handlers/SubscriptionDeleteHandler.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/47683#-NVFdHpM90ey1tqTP0o8:-NVFdHpM90ey1tqTP0o9:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/9497594f342c073400b073775b37c399f3ce5402/930-ng-license-manager/src/main/java/io/harness/subscription/handlers/SubscriptionDeleteHandler.java#L45)):*
> ```Java
>     String accountIdentifier = getAccountIdentifier(subscription);
>     HashMap<String, Object> properties = new HashMap<>();
>     telemetryReporter.sendTrackEvent(SUBSCRIPTION_TELEMETRY_EVENT_INITIATED,
> ```

same as above
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/handlers/SubscriptionUpdateHandler.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/47683#-NVFdKLHEFcwljvHn6mS:-NVFdKLHEFcwljvHn6mT:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/9497594f342c073400b073775b37c399f3ce5402/930-ng-license-manager/src/main/java/io/harness/subscription/handlers/SubscriptionUpdateHandler.java#L71)):*
> ```Java
>     log.info("Handled subscription update for {}", subscription.getId());
> 
>     telemetryReporter.sendTrackEvent(SUBSCRIPTION_TELEMETRY_EVENT_SUCCEEDED,
> ```

same as above

**Comment by thomas-grasman** [comment]
trigger uts

**Review by thomas-grasman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47683)* status: 11 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/handlers/InvoicePaymentSucceedHandler.java` line 79 at r1](https://reviewable.io/reviews/harness/harness-core/47683#-NVFckrz0legwSv5NDFD:-NVWCXn96p0IKpbg8Ajg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9497594f342c073400b073775b37c399f3ce5402/930-ng-license-manager/src/main/java/io/harness/subscription/handlers/InvoicePaymentSucceedHandler.java#L79)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

you need to send telemetryReporter.sendIdentifyEvent() before a track event because first user will registered and then his activity can be tracked
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/handlers/InvoicePaymentSucceedHandler.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/47683#-NVFd404Btkmwc5TowXd:-NVWCYm2A61MpERDarcG:b-4lnjlv) ([raw file](https://github.com/harness/harness-core/blob/9497594f342c073400b073775b37c399f3ce5402/930-ng-license-manager/src/main/java/io/harness/subscription/handlers/InvoicePaymentSucceedHandler.java#L89)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

are we sure we only need to send it to Amplitude? and not to other destinations like marketo, big-query etc.
</blockquote></details>

I'm using just Amplitude for now. All other subscription telemetry only goes to Amplitude. If we need more destinations, we can add them later.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/handlers/InvoiceUpdatedHandler.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/47683#-NVFdFE8A8zgiNW8bq7L:-NVWCiNK5f9c-ZO82oAC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9497594f342c073400b073775b37c399f3ce5402/930-ng-license-manager/src/main/java/io/harness/subscription/handlers/InvoiceUpdatedHandler.java#L56)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/handlers/SubscriptionDeleteHandler.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/47683#-NVFdHpM90ey1tqTP0o8:-NVWCj_nEwOH2l5kAEWq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9497594f342c073400b073775b37c399f3ce5402/930-ng-license-manager/src/main/java/io/harness/subscription/handlers/SubscriptionDeleteHandler.java#L45)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/handlers/SubscriptionUpdateHandler.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/47683#-NVFdKLHEFcwljvHn6mS:-NVWCkEm-XahSkqZIuaR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9497594f342c073400b073775b37c399f3ce5402/930-ng-license-manager/src/main/java/io/harness/subscription/handlers/SubscriptionUpdateHandler.java#L71)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by kapil-harness — DISMISSED** [review]
> Reviewed 7 of 11 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47683)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by neelam-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47683)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/handlers/InvoiceUpdatedHandler.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/47683#-NVWsDvlAEcxg4fkCfgX:-NVWsDvlAEcxg4fkCfgY:b-6tfgm5) ([raw file](https://github.com/harness/harness-core/blob/68832f199ba56199340ce8ba198c36ef79859036/930-ng-license-manager/src/main/java/io/harness/subscription/handlers/InvoiceUpdatedHandler.java#L47)):*
> ```Java
>     Invoice invoice = StripeEventUtils.convertEvent(event, Invoice.class);
>     if (invoice.getStatus().equals(INVOICE_DRAFT_STATUS)
>         && invoice.getLines().getData().stream().anyMatch(n -> "true".equals(n.getMetadata().get(AVATAX_KEY)))) {
> ```

Nit: `Boolean.TRUE` instead of "true"
___
*[`935-subscription-sdk/src/main/java/io/harness/subscription/helpers/impl/StripeHandlerImpl.java` line 207 at r2](https://reviewable.io/reviews/harness/harness-core/47683#-NVWtzIN0WsvYIVDfSV8:-NVWtzIN0WsvYIVDfSV9:b-skzzul) ([raw file](https://github.com/harness/harness-core/blob/68832f199ba56199340ce8ba198c36ef79859036/935-subscription-sdk/src/main/java/io/harness/subscription/helpers/impl/StripeHandlerImpl.java#L207)):*
> ```Java
>       Invoice invoice = Invoice.retrieve(invoiceId);
> 
>       sendTelemetryEvent("Subscription Payment Initiated", invoice.getCustomerEmail(), accountIdentifier, null);
> ```

make these: `"Subscription Payment Initiated"` and `"Subscription Payment Failed"` also constants please.
___
*[`935-subscription-sdk/src/main/java/io/harness/subscription/helpers/impl/StripeHandlerImpl.java` line 210 at r2](https://reviewable.io/reviews/harness/harness-core/47683#-NVWuC-U70AU7VIN4ZVX:-NVWuC-U70AU7VIN4ZVY:bwtup63) ([raw file](https://github.com/harness/harness-core/blob/68832f199ba56199340ce8ba198c36ef79859036/935-subscription-sdk/src/main/java/io/harness/subscription/helpers/impl/StripeHandlerImpl.java#L210)):*
> ```Java
>       return invoice.pay();
>     } catch (StripeException e) {
>       sendTelemetryEvent("Subscription Payment Failed", null, accountIdentifier, null);
> ```

Also, log this error before trowing an exception.

**Comment by thomas-grasman** [comment]
trigger uts

**Review by kapil-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47683)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by pranil-harness — APPROVED** [review]

**Comment by thomas-grasman** [comment]
trigger review

**Review by neelam-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47683#-:-NVaFcMMBYI1LNIUD50n:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
