### PR TITLE
[feat]: [CDS-41831]: AWS govcloud Support NG

### PR DESCRIPTION
**Pull request by PragyeshMishra01**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36580)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 1 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36580)

**Comment by PragyeshMishra01** [comment]
trigger feature-build

**Comment by PragyeshMishra01** [comment]
trigger compile

**Comment by PragyeshMishra01** [comment]
trigger ti4

**Comment by PragyeshMishra01** [comment]
trigger feature-build

**Comment by PragyeshMishra01** [comment]
trigger feature-build

**Comment by PragyeshMishra01** [comment]
trigger ti1

**Comment by arvind-choudhary-h** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java` line 126 at r3](https://reviewable.io/reviews/harness/harness-core/36580#-NAJ9ZRX0O2XBkQGd7tT:-NAJ9ZRX0O2XBkQGd7tU:bayy9c) ([raw file](https://github.com/harness/harness-core/blob/2a33a8038231053c44d6ddd81040febcbc692749/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L126)):*
> ```Java
>       @NotNull @QueryParam(NGCommonEntityConstants.ORG_KEY) String orgIdentifier,
>       @NotNull @QueryParam(NGCommonEntityConstants.PROJECT_KEY) String projectIdentifier,
>       @NotNull @QueryParam("region") String region) {
> ```

Can we mark the `region` optional?

**Comment by arvind-choudhary-h** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java` line 126 at r3](https://reviewable.io/reviews/harness/harness-core/36580#-NAJ9ZRX0O2XBkQGd7tT:-NAJ9dEQEMtHHNoTyWDv:b8auzxo) ([raw file](https://github.com/harness/harness-core/blob/2a33a8038231053c44d6ddd81040febcbc692749/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L126)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

Can we mark the `region` optional?
</blockquote></details>

If there is no region, we can use default region for now.

**Comment by PragyeshMishra01** [comment]
> _[`120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java` line 126 at r3](https://reviewable.io/reviews/harness/harness-core/36580#-NAJ9ZRX0O2XBkQGd7tT:-NAJ9ZRX0O2XBkQGd7tU:bayy9c) ([raw file](https://github.com/harness/harness-core/blob/2a33a8038231053c44d6ddd81040febcbc692749/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L126)):_
> 
> > ```java
> >       @NotNull @QueryParam(NGCommonEntityConstants.ORG_KEY) String orgIdentifier,
> >       @NotNull @QueryParam(NGCommonEntityConstants.PROJECT_KEY) String projectIdentifier,
> >       @NotNull @QueryParam("region") String region) {
> > ```
> 
> Can we mark the `region` optional?

Removed the @NotNull annotation from region?

**Comment by PragyeshMishra01** [comment]
> _[`120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java` line 126 at r3](https://reviewable.io/reviews/harness/harness-core/36580#-NAJ9ZRX0O2XBkQGd7tT:-NAJ9dEQEMtHHNoTyWDv:b8auzxo) ([raw file](https://github.com/harness/harness-core/blob/2a33a8038231053c44d6ddd81040febcbc692749/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L126)):_
> 
> Previously, arvind-choudhary-h (Arvind Choudhary) wrote…
> If there is no region, we can use default region for now.

we are already doing it.

**Comment by PragyeshMishra01** [comment]
trigger ti2

**Comment by PragyeshMishra01** [comment]
trigger ti4

**Comment by PragyeshMishra01** [comment]
trigger ti0

**Comment by PragyeshMishra01** [comment]
trigger ti1

**Comment by PragyeshMishra01** [comment]
trigger ti2

**Comment by PragyeshMishra01** [comment]
trigger ti3

**Comment by PragyeshMishra01** [comment]
trigger ti2

**Comment by PragyeshMishra01** [comment]
trigger ti3

**Comment by PragyeshMishra01** [comment]
trigger ti3

**Comment by PragyeshMishra01** [comment]
trigger messagecheck

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java` line 82 at r6](https://reviewable.io/reviews/harness/harness-core/36580#-NAOXSvREpmjkplVMQea:-NAOXSvREpmjkplVMQeb:b-mggv2l) ([raw file](https://github.com/harness/harness-core/blob/9abd9a1fbf3cb911b133efc126452ff3bbb56d62/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java#L82)):*
> ```Java
>     return ArtifactDelegateRequestUtils.getAmazonS3DelegateRequest(artifactConfig.getBucketName().getValue(), filePath,
>         filePathRegex, null, connectorRef, connectorDTO, encryptedDataDetails, ArtifactSourceType.AMAZONS3,
>         artifactConfig.getRegion() != null ? artifactConfig.getRegion().getValue() : "us-east-1");
> ```

nit: artifactConfig.getRegion() -> Can use empty predicate.
Also, can we use SDK enums of regions instead of plain string "us-east-1"



_Code quote:_
```Java
artifactConfig.getRegion()
```

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java` line 140 at r6](https://reviewable.io/reviews/harness/harness-core/36580#-NAOXeSXAtBqf1REeJ-P:-NAOXeSXAtBqf1REeJ-Q:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/9abd9a1fbf3cb911b133efc126452ff3bbb56d62/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java#L140)):*
> ```Java
>         .bucketName(amazonS3ArtifactConfig.getBucketName().getValue())
>         .region(
>             amazonS3ArtifactConfig.getRegion() != null ? amazonS3ArtifactConfig.getRegion().getValue() : "us-east-1")
> ```

same here

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/polling/bean/artifact/S3ArtifactInfo.java` line 41 at r6](https://reviewable.io/reviews/harness/harness-core/36580#-NAOXkfZ-qZXoAMi6B2f:-NAOXkfZ-qZXoAMi6B2g:bhtapet) ([raw file](https://github.com/harness/harness-core/blob/9abd9a1fbf3cb911b133efc126452ff3bbb56d62/125-cd-nextgen/src/main/java/io/harness/polling/bean/artifact/S3ArtifactInfo.java#L41)):*
> ```Java
>         .connectorRef(ParameterField.<String>builder().value(connectorRef).build())
>         .region(
>             ParameterField.<String>builder().value(EmptyPredicate.isNotEmpty(region) ? region : "us-east-1").build())
> ```

here too.

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 10 of 24 files at r1, 9 of 12 files at r2, 4 of 5 files at r3, 3 of 5 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36580)* status: 0 of 1 approvals obtained.

**Comment by arvind-choudhary-h** [comment]
trigger messagecheck

**Review by arvind-choudhary-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36580)* status: :shipit: complete! ✓

**Comment by arvind-choudhary-h** [comment]
trigger codebasehash

**Pull request merged**
