### PR TITLE
feat: [CDS-35475]: Improving file filter engine for referenced by and…

### PR DESCRIPTION
**Pull request by bojanmicovic**
… created by search

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33133)

### CODE REVIEW

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33133)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 712 at r1](https://reviewable.io/reviews/harness/harness-core/33133#-N1tNHsg8nxhs7z5EaYf:-N1tNHsg8nxhs7z5EaYg:bcfzj74) ([raw file](https://github.com/harness/harness-core/blob/6f07ee381cd11e57371ee2956de4e6bcc6db0e41/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L712)):*
> ```Java
>     bindExceptionHandlers();
> 
>     MapBinder<String, FilterPropertiesMapper> filterPropertiesMapper =
> ```

Just for me. Why do we need mapBinder here? 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/filestore/api/impl/FileReferenceServiceImpl.java` line 133 at r1](https://reviewable.io/reviews/harness/harness-core/33133#-N1tN7MX78AN6FgkJU0T:-N1tN7MX78AN6FgkJU0U:bngumhc) ([raw file](https://github.com/harness/harness-core/blob/6f07ee381cd11e57371ee2956de4e6bcc6db0e41/120-ng-manager/src/main/java/io/harness/ng/core/filestore/api/impl/FileReferenceServiceImpl.java#L133)):*
> ```Java
>   }
> 
>   public List<String> listAllReferredFileUsageIdentifiers(String accountIdentifier, String referredByEntityFQN) {
> ```

Minor - listAllReferredFileUsageIdentifiers >> listAllReferredFileIdentifiers
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/filestore/api/impl/FileStoreServiceImpl.java` line 241 at r1](https://reviewable.io/reviews/harness/harness-core/33133#-N1tMBH74jf3ifhz4jvg:-N1tMBH8-Zu_SH9Q9-x6:bt69f4v) ([raw file](https://github.com/harness/harness-core/blob/6f07ee381cd11e57371ee2956de4e6bcc6db0e41/120-ng-manager/src/main/java/io/harness/ng/core/filestore/api/impl/FileStoreServiceImpl.java#L241)):*
> ```Java
>     List<String> fileIdentifiers = null;
>     if (filterProperties != null && filterProperties.getReferencedBy() != null) {
>       fileIdentifiers = fileReferenceService.listAllReferredFileUsageIdentifiers(
> ```

listAllReferredFileUsageIdentifiers will list all file identifiers based on referedByEntityFQN, these file identifiers can be on project, org or account level. Are we sure to return files for all levels if a user does filtering on let's say project level, 



_Code quote:_
```Java
listAllReferredFileUsageIdentifiers
```
___
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/impl/EntitySetupUsageServiceImpl.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/33133#-N1tHjNnAnoWQztMQybT:-N1tHjNnAnoWQztMQybU:b-pjtkn1) ([raw file](https://github.com/harness/harness-core/blob/6f07ee381cd11e57371ee2956de4e6bcc6db0e41/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/impl/EntitySetupUsageServiceImpl.java#L102)):*
> ```Java
> 
>   @Override
>   public List<EntitySetupUsageDTO> listAllReferredUsages(
> ```

Need pagination here. 
___
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/service/EntitySetupUsageService.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/33133#-N1tI4hQ21K3uC-9Coo5:-N1tI4hQ21K3uC-9Coo6:b-z6zfk3) ([raw file](https://github.com/harness/harness-core/blob/6f07ee381cd11e57371ee2956de4e6bcc6db0e41/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/service/EntitySetupUsageService.java#L33)):*
> ```Java
>       String referredByEntityFQN, EntityType referredEntityType, String searchTerm);
> 
>   List<EntitySetupUsageDTO> listAllReferredUsages(
> ```

Need pagination here.

**Comment by bojanmicovic** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 712 at r1](https://reviewable.io/reviews/harness/harness-core/33133#-N1tNHsg8nxhs7z5EaYf:-N1tvbDS90hCgNPwdGHt:b-tge496) ([raw file](https://github.com/harness/harness-core/blob/6f07ee381cd11e57371ee2956de4e6bcc6db0e41/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L712)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Just for me. Why do we need mapBinder here? 
</blockquote></details>

We need it to use filters framework, we are registering mapper in 120-ng-manager module to map FilesFilterPropertiesDTO to FilesFilterProperties

**Comment by bojanmicovic** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/filestore/api/impl/FileStoreServiceImpl.java` line 241 at r1](https://reviewable.io/reviews/harness/harness-core/33133#-N1tMBH74jf3ifhz4jvg:-N1twr-I1WNABryQAGhj:bu440sj) ([raw file](https://github.com/harness/harness-core/blob/6f07ee381cd11e57371ee2956de4e6bcc6db0e41/120-ng-manager/src/main/java/io/harness/ng/core/filestore/api/impl/FileStoreServiceImpl.java#L241)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

listAllReferredFileUsageIdentifiers will list all file identifiers based on referedByEntityFQN, these file identifiers can be on project, org or account level. Are we sure to return files for all levels if a user does filtering on let's say project level, 
</blockquote></details>

Since those references are returned from an API which depends on scope, UI will select one of those references and send it back to filter API.

**Comment by bojanmicovic** [comment]
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/impl/EntitySetupUsageServiceImpl.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/33133#-N1tHjNnAnoWQztMQybT:-N1txSKr4Jzz0x_xCrid:b87j7n6) ([raw file](https://github.com/harness/harness-core/blob/6f07ee381cd11e57371ee2956de4e6bcc6db0e41/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/impl/EntitySetupUsageServiceImpl.java#L102)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Need pagination here. 
</blockquote></details>

I think we are good here without pagination, because this method is only used to retrieve identifiers which are not returned to UI.

**Comment by bojanmicovic** [comment]
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/service/EntitySetupUsageService.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/33133#-N1tI4hQ21K3uC-9Coo5:-N1txx2f4fmI9h_5e09f:brhumzt) ([raw file](https://github.com/harness/harness-core/blob/6f07ee381cd11e57371ee2956de4e6bcc6db0e41/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/service/EntitySetupUsageService.java#L33)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Need pagination here.
</blockquote></details>

Same here.

**Comment by bojanmicovic** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/filestore/api/impl/FileReferenceServiceImpl.java` line 133 at r1](https://reviewable.io/reviews/harness/harness-core/33133#-N1tN7MX78AN6FgkJU0T:-N1ty3Bf3mYR3Klx5CwU:b-8pqadh) ([raw file](https://github.com/harness/harness-core/blob/6f07ee381cd11e57371ee2956de4e6bcc6db0e41/120-ng-manager/src/main/java/io/harness/ng/core/filestore/api/impl/FileReferenceServiceImpl.java#L133)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - listAllReferredFileUsageIdentifiers >> listAllReferredFileIdentifiers
</blockquote></details>

Will do :)

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33133)* status: Some of the checks are too old. 1 change requests. 4. unresolved discussions.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33133#-:-N2B34Ua63wQZfbAuVR0:bnfp4nl)* status: Some of the checks are too old.

**Comment by bojanmicovic** [comment]
trigger ti0 ti3

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33133#-:-N2BrzN0BviUMTgzHhsY:bnfp4nl)* status: :shipit: complete! ✓

**Comment by bojanmicovic** [comment]
trigger ti0

**Pull request merged**
