### PR TITLE
feat: [CDS-73246]: Removing uuid from polling document before saving in db

### PR DESCRIPTION
**Pull request by Y0709**
Removing the uuid for polling document before saving the trigger so that we do not overwrite the polling document in case it is used by another trigger.
Currently we override the existing polling document even though other triggers are using it making them unable to fire unless trun them off and on again

1) Tested this by updating pollinginfo for a single trigger using the polling document -- old polling document is deleted and new is created
2) Tested this by updating polling info with one of the 2 triggers using same polling document -- new document is created and a signature is reduced in old. In case we make the configuration same again the extra polling document is deleted and the used one has 2 signatures .

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49880)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Comment by rohitk-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/49880#-NZ1fWWwE9HaT6p8dfgz:-NZ1fWWwE9HaT6p8dfh-:b-azkzuk) ([raw file](https://github.com/harness/harness-core/blob/fdb0d13df0cf8a6302da8495bcce237c9a5fce56/125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java#L55)):*
> ```Java
>     // savedPollingDoc will be null if we couldn't find polling doc with the same entries as pollingDocument.
>     if (savedPollingDoc == null) {
>       pollingDocument.setUuid(null);
> ```

nit: non-blocking: having a  comment would be helpful for future devs.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49880)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — DISMISSED** [review]
Let's make sure to add and run automation for this change in the pre-qa.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49880#-:-NZ1g55J4FIgQaYPBdO4:b-kz17gz)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49880)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49880)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger uts

**Review by vcalasansh — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49880)* status: :shipit: complete! ✓

**Pull request merged**
