### PR TITLE
fix: [CDS-47601]: ignore chart version strict match in case i/p is a …

### PR DESCRIPTION
**Pull request by achyuth-harness**
…range

## Describe your changes
We are ignoring strict chart version check if input chart version is in the form of a range. 

Tests added: 
Added a UT to check if i/p chart version is in range format then we pass this chart version matching check

Before changes:
image

After changes:
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40941)

### CODE REVIEW

**Comment by achyuth-harness** [comment]
trigger pmd

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Review by acasian-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40941)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/40941#-NICZQD96YUUI1C2fAGa:-NICZQDA4h4qSo9U8DDB:bwkb6a9) (no related file):*
@achyuth-harness can you plss provide the image with before and after the fix?

___

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40941)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/40941#-NICZQD96YUUI1C2fAGa:-NICyS2G0gOtVxZN759r:b-19q1gy) (no related file):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

@achyuth-harness can you plss provide the image with before and after the fix?
</blockquote></details>

https://harness.atlassian.net/browse/CDS-47601?focusedCommentId=387183

have updated in the comments

___

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40941)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by TarunUba1 — APPROVED** [review]

**Review by TarunUba1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40941)* status: :shipit: complete! ✓

**Pull request merged**
