### PR TITLE
techDebt: [PL-30625] Remove usage of morphia cloneQuery

### PR DESCRIPTION
**Pull request by kshitij-harness**
## Describe your changes
Clone Query is deprecated in Morphia 1.6
We are using it only at 2 places, so I've created duplicate object to not make major changes to existing flow

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42019)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42019)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java` line 1067 at r2](https://reviewable.io/reviews/harness/harness-core/42019#-NKMYO8H2LnK_t0I-B2W:-NKMYO8H2LnK_t0I-B2X:bmprtl9) ([raw file](https://github.com/harness/harness-core/blob/793623e6462bc3680d31ac932ed760b0341a405f/400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java#L1067)):*
> ```Java
>   @Override
>   public Set<String> getDeletedAppIds(String accountId, long timestamp) {
>     List<Instance> instancesForAccount = getInstancesForAccount(accountId, timestamp,
> ```

We should construct this query in getInstancesForAccount method itself and not pass from here.

**Comment by kshitij-harness** [comment]
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/42019)_ status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java` line 1067 at r2](https://reviewable.io/reviews/harness/harness-core/42019#-NKMYO8H2LnK_t0I-B2W:-NKMYO8H2LnK_t0I-B2X:bmprtl9) ([raw file](https://github.com/harness/harness-core/blob/793623e6462bc3680d31ac932ed760b0341a405f/400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java#L1067)):_
> 
> > ```java
> >   @Override
> >   public Set<String> getDeletedAppIds(String accountId, long timestamp) {
> >     List<Instance> instancesForAccount = getInstancesForAccount(accountId, timestamp,
> > ```
> 
> We should construct this query in getInstancesForAccount method itself and not pass from here.

getInstancesForAccount is being called from 2 different places and have different queries.
Earlier, we were passing 1 query and cloning it there, now we need to pass duplicate objects from both places.

**Review by ankit-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42019)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42019#-:-NKN_Vfb-Kclt9vsrDM6:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
