### PR TITLE
feat: [CDS-38470]: Hard delete environment entity

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
- hard delete environment entity based on FF `HARD_DELETE_ENTITIES`
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34066)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
trigger ti2,ti4

**Comment by yogesh-chauhan** [comment]
trigger codebasehash

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by archit-harness — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34066)* status: 2 file(s) to review. 0 of 1 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34066)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/34066#-N40aEXCDv_z93qMx_B_:-N40aEXD7QjevAmAgeoQ:boqls0r) ([raw file](https://github.com/harness/harness-core/blob/c3435e4a522f2b0696918328d7a064b7829c44c2/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L92)):*
> ```Java
>         "[Retrying]: Failed deleting Environment; attempt: {}", "[Failed]: Failed deleting Environment; attempt: {}");
>     DeleteResult deleteResult = Failsafe.with(retryPolicy).get(() -> mongoTemplate.remove(query, Environment.class));
>     return deleteResult.wasAcknowledged() && deleteResult.getDeletedCount() > 0;
> ```

we can discuss this



_Code quote:_
```Java
        "[Retrying]: Failed deleting Environment; attempt: {}", "[Failed]: Failed deleting Environment; attempt: {}");
    UpdateResult updateResult =
        Failsafe.with(retryPolicy)
            .get(() -> mongoTemplate.updateFirst(query, updateOperationsForDelete, Environment.class));
    return updateResult.wasAcknowledged() && updateResult.getModifiedCount() == 1;
  }

  @Override
  public boolean delete(Criteria criteria) {
    Query query = new Query(criteria);
    RetryPolicy<Object> retryPolicy = getRetryPolicy(
        "[Retrying]: Failed deleting Environment; attempt: {}", "[Failed]: Failed deleting Environment; attempt: {}");
    DeleteResult deleteResult = Failsafe.with(retryPolicy).get(() -> mongoTemplate.remove(query, Environment.class));
    return deleteResult.wasAcknowledged() && deleteResult.getDeletedCount() > 0;
```

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34066)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/34066#-N40aEXCDv_z93qMx_B_:-N41XMTMADokwM7KCkUp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c3435e4a522f2b0696918328d7a064b7829c44c2/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L92)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we can discuss this
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34066)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
trigger ti2

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 2 of 5 files at r2, 1 of 2 files at r3, 5 of 5 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34066)* status: :shipit: complete! ✓

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34066#-:-N4BXoSWDZoPuIEbxsKH:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
