### PR TITLE
Fix: [SRM-14078]: [SRM-14071]: Fix notification URLs and monitored service update in health indicator update

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44463)

### CODE REVIEW

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44463)* status: 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/SLOTemplateDataGenerator.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/44463#-NPQY-LuDvgSLeXVxFF1:-NPQY-LuDvgSLeXVxFF2:b-k8yywm) ([raw file](https://github.com/harness/harness-core/blob/ec9f9ca5772a1be2a556589d4efdd616c56f32f9/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/SLOTemplateDataGenerator.java#L35)):*
> ```Java
>       String baseUrl, ProjectParams projectParams, String identifier, NotificationRuleType type, Long endTime) {
>     return String.format("%s/account/%s/%s/orgs/%s/projects/%s/slos/%s?tab=Details&sloType=Simple&notificationTime=%s",
>         baseUrl, projectParams.getAccountIdentifier(), MODULE_NAME, projectParams.getOrgIdentifier(),
> ```

Should we add any UT to ensure these URLs are not changed without due consideration?

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44463)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/SLOTemplateDataGenerator.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/44463#-NPQY-LuDvgSLeXVxFF1:-NPX5OBE39GR22SkDnTp:b-dwicm) ([raw file](https://github.com/harness/harness-core/blob/ec9f9ca5772a1be2a556589d4efdd616c56f32f9/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/SLOTemplateDataGenerator.java#L35)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Should we add any UT to ensure these URLs are not changed without due consideration?
</blockquote></details>

We have a lot of templates, none has UTs. I don't think people will change the code of URL until they want to. Having UTs is always good, for that reason we can add, but then we should add for all the templates. So in  some other PR I can take this up.

**Review by dhruv-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44463)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/SLOTemplateDataGenerator.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/44463#-NPQY-LuDvgSLeXVxFF1:-NPX8YjJAgxAB5F9x9dq:b-h5566) ([raw file](https://github.com/harness/harness-core/blob/30576dbad22db4d9b4b55ced5654c914e6482e1e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/SLOTemplateDataGenerator.java#L35)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

We have a lot of templates, none has UTs. I don't think people will change the code of URL until they want to. Having UTs is always good, for that reason we can add, but then we should add for all the templates. So in  some other PR I can take this up.
</blockquote></details>

I agree all the templates should have UTs. Since we cant add UTs for all the templates in one go, we do incremental changes, improving the coverage with each PR. Lets add UTs for the changes done in this PR here itself and for the ones which have been left out, you can create a techdebt ticket

**Review by deepak-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44463)* status: :shipit: complete! ✓

**Review by dhruv-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44463)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44463)* status: :shipit: complete! ✓

**Pull request merged**
