### PR TITLE
fix: [CDS-37299]: Handle missing service definition in serviceYamlV2 gracefully

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33134)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33134)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 167 at r1](https://reviewable.io/reviews/harness/harness-core/33134#-N1w7KsU2u64W7FiREHX:-N1w7KsW15T7FGa08F8x:b39olwb) ([raw file](https://github.com/harness/harness-core/blob/86ade7c609071129085480c19cc0756b2e7de0a8/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L167)):*
> ```Java
>           throw new InvalidYamlRuntimeException(
>               format("ServiceDefinition should be present in service [%s]. Please add it and try again", se.getName()));
>         }
> ```

Firstly can serviceRef, envRef and infraRef be expressions? apart from runtime inputs? i think it should not be. this can be restricted via schema, then in creating filters we can check if serviceRef has serviceDef if not, then fail early?



_Code quote:_
```Java
        if (cfg.getServiceDefinition() == null) {
          throw new InvalidYamlRuntimeException(
              format("ServiceDefinition should be present in service [%s]. Please add it and try again", se.getName()));
        }
```

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33134)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 167 at r1](https://reviewable.io/reviews/harness/harness-core/33134#-N1w7KsU2u64W7FiREHX:-N2C3jHS15QfTNcN62KL:bj05zir) ([raw file](https://github.com/harness/harness-core/blob/86ade7c609071129085480c19cc0756b2e7de0a8/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L167)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Firstly can serviceRef, envRef and infraRef be expressions? apart from runtime inputs? i think it should not be. this can be restricted via schema, then in creating filters we can check if serviceRef has serviceDef if not, then fail early?
</blockquote></details>

Yes, as discussed, they cannot be expressions. Added Regex validation to prevent them at schema level. Also discussed with Srinivas that this is okay

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33134)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 167 at r1](https://reviewable.io/reviews/harness/harness-core/33134#-N1w7KsU2u64W7FiREHX:-N2FVEKi-HK64iv4T0xA:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/86ade7c609071129085480c19cc0756b2e7de0a8/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L167)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Yes, as discussed, they cannot be expressions. Added Regex validation to prevent them at schema level. Also discussed with Srinivas that this is okay
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 175 at r3](https://reviewable.io/reviews/harness/harness-core/33134#-N2FVwPF64BRzAcOcrMN:-N2FVwPF64BRzAcOcrMO:bs311gm) ([raw file](https://github.com/harness/harness-core/blob/bfa0a321a4df266643d887622a7621984894ded9/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L175)):*
> ```Java
>         NGServiceV2InfoConfig config = NGServiceEntityMapper.toNGServiceConfig(se).getNgServiceV2InfoConfig();
>         filterBuilder.serviceName(se.getName());
>         if (config.getServiceDefinition() == null) {
> ```

we decided to make serviceDef compulosry for deploy stage?



_Code quote:_
```Java
config.getServiceDefinition() == null
```

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33134)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 175 at r3](https://reviewable.io/reviews/harness/harness-core/33134#-N2FVwPF64BRzAcOcrMN:-N2FZ1XXEddUz6wcfsG7:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/bfa0a321a4df266643d887622a7621984894ded9/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L175)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we decided to make serviceDef compulosry for deploy stage?
</blockquote></details>

Yes

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33134)* status: :shipit: complete! ✓

**Pull request merged**
