### PR TITLE
feat: [CDS-42404]: Add file script support for Ssh and WinRm

### PR DESCRIPTION
**Pull request by filip5rovic**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36974)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36974)

**Review by ivan-83 — APPROVED** [review]
Well done! Minor comments.

> Reviewed 2 of 3 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36974#-:-NAnUoLL2d0BLNnrVuHk:b-bln70f)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java` line 455 at r2](https://reviewable.io/reviews/harness/harness-core/36974#-NAnRSbo5iE88-YKOfgs:-NAnRSbo5iE88-YKOfgt:bq62n8i) ([raw file](https://github.com/harness/harness-core/blob/07189e4d28f46d71fec75cf8b2e241fb76d0fd0c/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java#L455)):*
> ```Java
> 
>   private String getShellScript(Ambiance ambiance, @Nonnull ShellScriptSourceWrapper shellScriptSourceWrapper) {
>     if ("Inline".equals(shellScriptSourceWrapper.getType())) {
> ```

Minor - Inline and Harness could be constants or enum.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java` line 464 at r2](https://reviewable.io/reviews/harness/harness-core/36974#-NAnRYHm8gRUei2mnPlS:-NAnRYHm8gRUei2mnPlT:b46ytod) ([raw file](https://github.com/harness/harness-core/blob/07189e4d28f46d71fec75cf8b2e241fb76d0fd0c/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java#L464)):*
> ```Java
>           FileReference.of(spec.getFile().getValue(), AmbianceUtils.getAccountId(ambiance),
>               AmbianceUtils.getOrgIdentifier(ambiance), AmbianceUtils.getProjectIdentifier(ambiance)));
>       return cdExpressionResolver.renderExpression(ambiance, script);
> ```

Just double check are we supporting expressions within the script. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshWinRmConfigFileHelper.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/36974#-NAnRsA411A0Y0HfbK63:-NAnRsA5CNiIIr8M78V3:bk63dsy) ([raw file](https://github.com/harness/harness-core/blob/07189e4d28f46d71fec75cf8b2e241fb76d0fd0c/127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshWinRmConfigFileHelper.java#L59)):*
> ```Java
> 
>   public String fetchFileContent(FileReference fileReference) {
>     Optional<FileStoreNodeDTO> configFile = fileStoreService.getWithChildrenByPath(fileReference.getAccountIdentifier(),
> ```

Minor - rename configFile to file 
___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/HarnessFileStoreSource.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/36974#-NAnUkcDAEhAoEfCzEEl:-NAnUkcE-MXoV5LL7hHt:bf4ihci) ([raw file](https://github.com/harness/harness-core/blob/07189e4d28f46d71fec75cf8b2e241fb76d0fd0c/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/HarnessFileStoreSource.java#L25)):*
> ```Java
> @Builder
> @JsonTypeName("Harness")
> @OwnedBy(CDC)
> ```

CDC >> CDP
___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/HarnessFileStoreSource.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/36974#-NAnSXWp7DA-8wxoayIO:-NAnSXWq06JkPFo0MMGI:b9hyfjb) ([raw file](https://github.com/harness/harness-core/blob/07189e4d28f46d71fec75cf8b2e241fb76d0fd0c/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/HarnessFileStoreSource.java#L28)):*
> ```Java
> @RecasterAlias("io.harness.steps.shellscript.HarnessFileStoreSource")
> public class HarnessFileStoreSource implements ShellScriptBaseSource {
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) ParameterField<String> file;
> ```

Missing @YamlSchemaTypes({expression})

**Review by acasian-harness — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36974)* status: :shipit: complete! ✓

**Review by filip5rovic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36974)* status: 3. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java` line 464 at r2](https://reviewable.io/reviews/harness/harness-core/36974#-NAnRYHm8gRUei2mnPlS:-NAtD4msAjozzKpfcC1e:b89220d) ([raw file](https://github.com/harness/harness-core/blob/07189e4d28f46d71fec75cf8b2e241fb76d0fd0c/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java#L464)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Just double check are we supporting expressions within the script. 
</blockquote></details>

Yes, we are supporting expressions in bash scripts
___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/HarnessFileStoreSource.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/36974#-NAnUkcDAEhAoEfCzEEl:-NAtDBZR0QnZS9MfRvBI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/07189e4d28f46d71fec75cf8b2e241fb76d0fd0c/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/HarnessFileStoreSource.java#L25)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

CDC >> CDP
</blockquote></details>

Done.
___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/HarnessFileStoreSource.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/36974#-NAnSXWp7DA-8wxoayIO:-NAtDC5t5eYnVrgwhdfE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/07189e4d28f46d71fec75cf8b2e241fb76d0fd0c/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/HarnessFileStoreSource.java#L28)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Missing @YamlSchemaTypes({expression})
</blockquote></details>

Done.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36974)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36974#-:-NAtUv2-9O31tNX6skhl:bg7igk9)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]

**Review by hextechpal — APPROVED** [review]
> Reviewed 3 of 10 files at r2, 6 of 9 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36974)* status: :shipit: complete! ✓

**Pull request merged**
