### PR TITLE
feat: [CDS-40864]: merge pr git lab

### PR DESCRIPTION
**Pull request by GabeAboy**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36114)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36114)

**Comment by GabeAboy** [comment]
*[`960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabServiceImpl.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/36114#-N8kNdYDE0M0a_fQQ_zD:-N8kNdYE67rGyycrx3eu:b-oofh7l) ([raw file](https://github.com/harness/harness-core/blob/9602cb542ce7e69bae7345e4b23fa400674a14f5/960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabServiceImpl.java#L87)):*
> ```Java
> 
>   @VisibleForTesting
>   public GitlabRestClient getGitlabRestClient(GitlabConfig gitlabConfig) {
> ```

@rohitk-h @anshul-harness This encryptionDetails field wasn't used so I removed it

**Comment by GabeAboy** [comment]
*[`960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabServiceImpl.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/36114#-N8kNdYDE0M0a_fQQ_zD:-N8kNoNg9yVSdkETLv5H:b2nhei9) ([raw file](https://github.com/harness/harness-core/blob/9602cb542ce7e69bae7345e4b23fa400674a14f5/960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabServiceImpl.java#L87)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

@rohitk-h @anshul-harness This encryptionDetails field wasn't used so I removed it 
</blockquote></details>

FYI

**Review by henry-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36114)* status: 6 file(s) to review. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/36114#-N8kO6HPEleuSY4dfqJU:-N8kO6HPEleuSY4dfqJV:b-gtjju2) ([raw file](https://github.com/harness/harness-core/blob/9602cb542ce7e69bae7345e4b23fa400674a14f5/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java#L95)):*
> ```Java
> 
>   private String getGitApiURL(String url) {
>     Pattern GIT_URL = Pattern.compile(GIT_URL_REGEX);
> ```

nitpick: you can probably move this outside so its `private static final` since it won't change.

**Review by rohitk-h — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36114)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java` line 68 at r3](https://reviewable.io/reviews/harness/harness-core/36114#-N8p8_RC3eVyn4Ep35ar:-N8p8_RC3eVyn4Ep35as:b-k4mpdg) ([raw file](https://github.com/harness/harness-core/blob/969876a17d066937073253d3e1436f2aaf0864aa/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java#L68)):*
> ```Java
>           || !gitConnector.getConnectorConfig().getClass().isAssignableFrom(GitlabConnectorDTO.class)) {
>         throw new InvalidRequestException(
>             format("Invalid Connector %s, Need GithubConfig: ", gitConnector.getIdentifier()));
> ```

Need gitlab config.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/36114#-N8p8mKyBPG-LrIf1jox:-N8p8mKyBPG-LrIf1joy:b9avmrj) ([raw file](https://github.com/harness/harness-core/blob/969876a17d066937073253d3e1436f2aaf0864aa/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java#L79)):*
> ```Java
>             .gitApiResult(GitApiMergePRTaskResponse.builder()
>                               .sha(mergePRResponse.get("sha").toString())
>                               .message(mergePRResponse.get("message").toString())
> ```

We have hardcoded the message string in NGGitCommandTask. This can be removed. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/36114#-N8p9HIx6topVXNl2TUm:-N8p9HIy46VwI34jNtya:b-mazegt) ([raw file](https://github.com/harness/harness-core/blob/969876a17d066937073253d3e1436f2aaf0864aa/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java#L82)):*
> ```Java
>                               .build());
>       } else {
>         responseBuilder.commandExecutionStatus(FAILURE).errorMessage("Merging PR encountered a problem");
> ```

Nitpick: Can we update the message to contain information about the pr or the connector name to aid in troubleshooting
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java` line 102 at r3](https://reviewable.io/reviews/harness/harness-core/36114#-N8p95MxC-qbl-YWtnfy:-N8p95MxC-qbl-YWtnfz:b-x6hxu0) ([raw file](https://github.com/harness/harness-core/blob/969876a17d066937073253d3e1436f2aaf0864aa/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java#L102)):*
> ```Java
>     if (domain.equalsIgnoreCase("gitlab.com")) {
>       return GITLAB_API_URL;
>     } else {
> ```

nitpick: No else needed
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabService.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/36114#-N8p9ofH99A_PlCctpCs:-N8p9ofH99A_PlCctpCt:b-fvm38p) ([raw file](https://github.com/harness/harness-core/blob/969876a17d066937073253d3e1436f2aaf0864aa/960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabService.java#L10)):*
> ```Java
> package io.harness.cistatus.service.gitlab;
> 
> import io.harness.cistatus.service.GithubAppConfig;
> ```

This class can be removed. Doesn't seem to be needed here. 
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabServiceImpl.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/36114#-N8kNdYDE0M0a_fQQ_zD:-N8pBRy70Qralx7X0tnh:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/9602cb542ce7e69bae7345e4b23fa400674a14f5/960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabServiceImpl.java#L87)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

FYI
</blockquote></details>

ok
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabServiceImpl.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/36114#-N8pAEqG5zUqvLJofRP5:-N8pAEqG5zUqvLJofRP6:blekpj8) ([raw file](https://github.com/harness/harness-core/blob/969876a17d066937073253d3e1436f2aaf0864aa/960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabServiceImpl.java#L53)):*
> ```Java
>         JSONObject json = new JSONObject();
>         json.put("sha", ((LinkedHashMap) response.body()).get("sha"));
>         json.put("message", ((LinkedHashMap) response.body()).get("title"));
> ```

We can remove this field. We are hardcoding it. This title seems to be the same PR title. I had initially added because I was under impression each provided would have a different response message on merge but that is not true. 
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabServiceImpl.java` line 56 at r3](https://reviewable.io/reviews/harness/harness-core/36114#-N8pBCfiAYSpGidNgwX2:-N8pBCfiAYSpGidNgwX3:b39vtab) ([raw file](https://github.com/harness/harness-core/blob/969876a17d066937073253d3e1436f2aaf0864aa/960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabServiceImpl.java#L56)):*
> ```Java
>         return json;
>       } else {
>         return null;
> ```

We should log an error here and return a new object. Eg. 
```log.warn("Merge Request for merging Azure repo with url {} and sha {} returned with response code {}",
            azureRepoConfig.getAzureRepoUrl(), sha, response.code());
        return new JSONObject();```
```

**Review by GabeAboy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36114)* status: 5 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/36114#-N8kO6HPEleuSY4dfqJU:-N8y6Sar62gI-cg0wEOO:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9602cb542ce7e69bae7345e4b23fa400674a14f5/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java#L95)):*
<details><summary><i>Previously, henry-harness (henry leong) wrote…</i></summary><blockquote>

nitpick: you can probably move this outside so its `private static final` since it won't change.
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java` line 68 at r3](https://reviewable.io/reviews/harness/harness-core/36114#-N8p8_RC3eVyn4Ep35ar:-N8y66ig6lULXcODcO6N:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/969876a17d066937073253d3e1436f2aaf0864aa/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java#L68)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Need gitlab config.
</blockquote></details>

Done



_Code quote:_
```Java
Invalid Connector %s, Need GithubConfig
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/36114#-N8p8mKyBPG-LrIf1jox:-N8y6DwU5fggQ6pzTaZI:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/969876a17d066937073253d3e1436f2aaf0864aa/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java#L79)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

We have hardcoded the message string in NGGitCommandTask. This can be removed. 
</blockquote></details>

Done



_Code quote:_
```Java
.message(mergePRResponse.get("message").toString())
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/36114#-N8p9HIx6topVXNl2TUm:-N8y9vZg76eMHBx8sjPq:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/969876a17d066937073253d3e1436f2aaf0864aa/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java#L82)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Nitpick: Can we update the message to contain information about the pr or the connector name to aid in troubleshooting
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java` line 102 at r3](https://reviewable.io/reviews/harness/harness-core/36114#-N8p95MxC-qbl-YWtnfy:-N8y6ZL6BfgqC4uUDpzB:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/969876a17d066937073253d3e1436f2aaf0864aa/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java#L102)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

nitpick: No else needed
</blockquote></details>

Done



_Code quote:_
```Java
    if (domain.equalsIgnoreCase("gitlab.com")) {
      return GITLAB_API_URL;
    } else {
```
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabService.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/36114#-N8p9ofH99A_PlCctpCs:-N8y6jPV3xPmYE9IOqyR:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/969876a17d066937073253d3e1436f2aaf0864aa/960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabService.java#L10)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

This class can be removed. Doesn't seem to be needed here. 
</blockquote></details>

Done
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabServiceImpl.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/36114#-N8pAEqG5zUqvLJofRP5:-N8y6kwd1c3jAcWvOddB:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/969876a17d066937073253d3e1436f2aaf0864aa/960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabServiceImpl.java#L53)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

We can remove this field. We are hardcoding it. This title seems to be the same PR title. I had initially added because I was under impression each provided would have a different response message on merge but that is not true. 
</blockquote></details>

Done
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabServiceImpl.java` line 56 at r3](https://reviewable.io/reviews/harness/harness-core/36114#-N8pBCfiAYSpGidNgwX2:-N8y7CNaErEZP4WNhYbK:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/969876a17d066937073253d3e1436f2aaf0864aa/960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabServiceImpl.java#L56)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

We should log an error here and return a new object. Eg. 
```log.warn("Merge Request for merging Azure repo with url {} and sha {} returned with response code {}",
            azureRepoConfig.getAzureRepoUrl(), sha, response.code());
        return new JSONObject();```
```

</blockquote></details>

Done



_Code quote:_
```Java
        return json;
      } else {
        return null;
```

**Review by rohitk-h — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36114)* status: 1. unresolved discussions.

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36114)* status: 1. unresolved discussions.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36114)* status: 1. unresolved discussions.

**Review by henry-harness — COMMENTED** [review]
> Reviewed 1 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36114)* status: 1. unresolved discussions.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36114)* status: 1. unresolved discussions.

**Pull request merged**
