### PR TITLE
feat: [PL-25634]: Add support for evaluating conditions in Access Control

### PR DESCRIPTION
**Pull request by gupta-utkarsh**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34282)

### CODE REVIEW

**Comment by gupta-utkarsh** [comment]
trigger messagecheck

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34282)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/34282#-N4W3wc5EWDFar2UlVeQ:-N4W3wc5EWDFar2UlVeR:b-oi2fzi) ([raw file](https://github.com/harness/harness-core/blob/2a9ce8290ea34fa53159adbae2a0079a32b4cc4c/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java#L88)):*
> ```Java
>   }
> 
>   private List<Boolean> checkAccessInternal(List<PermissionCheck> permissionChecks, List<List<ACL>> matchedACLs) {
> ```

private List<Boolean> checkAccessInternal(List<PermissionCheck> permissionChecks, List<List<ACL>> matchedACLs) {
    return IntStream.range(0, permissionChecks.size())
        .mapToObj(i -> {
          return checkAccess(permissionChecks.get(i), matchedACLs.get(i));
        })
        .collect(Collectors.toList());
  }

  private boolean checkAccess(PermissionCheck permissionCheck, List<ACL> matchedACLs) {
    List<ACL> conditionalACLs = matchedACLs.stream().filter(ACL::isConditional).collect(Collectors.toList());
    for (ACL acl : matchedACLs) {
        if (hasAccessFromACL(permissionCheck, acl)) {
            retur true;
        }
    }

    return false;
  }

  private boolean hasAccessFromACL(PermissionCheck permissionCheck, ACL acl) {
      if (!acl.isConditional()) {
          return true;
      } 

      Map<String, String> attributes = getAttributes(permissionChecks.get(i));
      ACLExpressionEvaluator engineExpressionEvaluator =
        aclExpressionEvaluatorProvider.get(permissionChecks.get(i), attributes);
      return engineExpressionEvaluator.evaluateExpression(acl.getJexlCondition());
  }

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34282)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/34282#-N4W43gQ2_gY4Ac2tQDK:-N4W43gQ2_gY4Ac2tQDL:b45h) ([raw file](https://github.com/harness/harness-core/blob/2a9ce8290ea34fa53159adbae2a0079a32b4cc4c/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java#L88)):*
> ```Java
>   }
> 
>   private List<Boolean> checkAccessInternal(List<PermissionCheck> permissionChecks, List<List<ACL>> matchedACLs) {
> ```





_Code snippet:_
```Java
 private List<Boolean> checkAccessInternal(List<PermissionCheck> permissionChecks, List<List<ACL>> matchedACLs) {
    return IntStream.range(0, permissionChecks.size())
        .mapToObj(i -> {
          return checkAccess(permissionChecks.get(i), matchedACLs.get(i));
        })
        .collect(Collectors.toList());
  }

  private boolean checkAccess(PermissionCheck permissionCheck, List<ACL> matchedACLs) {
    List<ACL> conditionalACLs = matchedACLs.stream().filter(ACL::isConditional).collect(Collectors.toList());
    for (ACL acl : matchedACLs) {
        if (hasAccessFromACL(permissionCheck, acl)) {
            retur true;
        }
    }

    return false;
  }

  private boolean hasAccessFromACL(PermissionCheck permissionCheck, ACL acl) {
      if (!acl.isConditional()) {
          return true;
      } 

      Map<String, String> attributes = getAttributes(permissionChecks.get(i));
      ACLExpressionEvaluator engineExpressionEvaluator =
        aclExpressionEvaluatorProvider.get(permissionChecks.get(i), attributes);
      return engineExpressionEvaluator.evaluateExpression(acl.getJexlCondition());
  }
```

**Review by gupta-utkarsh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34282)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/34282#-N4W3wc5EWDFar2UlVeQ:-N4_IXUQ3Tz339-cgKRJ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/2a9ce8290ea34fa53159adbae2a0079a32b4cc4c/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java#L88)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

private List<Boolean> checkAccessInternal(List<PermissionCheck> permissionChecks, List<List<ACL>> matchedACLs) {
    return IntStream.range(0, permissionChecks.size())
        .mapToObj(i -> {
          return checkAccess(permissionChecks.get(i), matchedACLs.get(i));
        })
        .collect(Collectors.toList());
  }

  private boolean checkAccess(PermissionCheck permissionCheck, List<ACL> matchedACLs) {
    List<ACL> conditionalACLs = matchedACLs.stream().filter(ACL::isConditional).collect(Collectors.toList());
    for (ACL acl : matchedACLs) {
        if (hasAccessFromACL(permissionCheck, acl)) {
            retur true;
        }
    }

    return false;
  }

  private boolean hasAccessFromACL(PermissionCheck permissionCheck, ACL acl) {
      if (!acl.isConditional()) {
          return true;
      } 

      Map<String, String> attributes = getAttributes(permissionChecks.get(i));
      ACLExpressionEvaluator engineExpressionEvaluator =
        aclExpressionEvaluatorProvider.get(permissionChecks.get(i), attributes);
      return engineExpressionEvaluator.evaluateExpression(acl.getJexlCondition());
  }
</blockquote></details>

Done
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/34282#-N4W43gQ2_gY4Ac2tQDK:-N4_IYDF6cvl8m2w4dzb:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/2a9ce8290ea34fa53159adbae2a0079a32b4cc4c/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java#L88)):*
> ```Java
>   }
> 
>   private List<Boolean> checkAccessInternal(List<PermissionCheck> permissionChecks, List<List<ACL>> matchedACLs) {
> ```

Done

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34282#-:-N4_n-0n0HF-IDC6qY13:bnfp4nl)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34282)* status: :shipit: complete! ✓

**Pull request merged**
