### PR TITLE
[feat]: [CDS-78125]: Propogating the parent info to the children in plan-creation framework

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52362)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52362)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 217 at r1](https://reviewable.io/reviews/harness/harness-core/52362#-NdFYB9f6-T_CyaEsFzp:-NdFYB9f6-T_CyaEsFzq:b-bhkmue) ([raw file](https://github.com/harness/harness-core/blob/28654e5112835c34cd3395e9b3bdb17d2a3441f9/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L217)):*
> ```Java
> 
>   public void decorateResponseWithParentInfo(
>       Dependency initialDependencyDetails, PlanCreationResponse planForField, String yamlVersion) {
> ```

can you pass as Map? key as YAML_VERSION, and value of field, so other can add to same map



_Code quote:_
```Java
String yamlVersion
```
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 229 at r1](https://reviewable.io/reviews/harness/harness-core/52362#-NdFYc2Q6m5nvjFWQDBA:-NdFYc2Q6m5nvjFWQDBB:b-98ev2l) ([raw file](https://github.com/harness/harness-core/blob/28654e5112835c34cd3395e9b3bdb17d2a3441f9/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L229)):*
> ```Java
>         dependencyMetadata = Dependency.newBuilder().build();
>       }
>       HarnessStruct parentInfoFromPlanCreator = dependencyMetadata.getParentInfo();
> ```

can you rename to parentInfoOfCurrentNode
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 230 at r1](https://reviewable.io/reviews/harness/harness-core/52362#-NdFYLLJ7PnNm9Alqzfy:-NdFYLLJ7PnNm9Alqzfz:b34aq5u) ([raw file](https://github.com/harness/harness-core/blob/28654e5112835c34cd3395e9b3bdb17d2a3441f9/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L230)):*
> ```Java
>       }
>       HarnessStruct parentInfoFromPlanCreator = dependencyMetadata.getParentInfo();
>       // If the planCreator already sent the yamlVersion for its children then that value will be considered. So
> ```

lets not useYaml version, here mentioned metadata sent by currentNode take priority than parent one
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 232 at r1](https://reviewable.io/reviews/harness/harness-core/52362#-NdFYyJuAHbSLnAT8GMF:-NdFYyJuAHbSLnAT8GMG:bsrnwnj) ([raw file](https://github.com/harness/harness-core/blob/28654e5112835c34cd3395e9b3bdb17d2a3441f9/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L232)):*
> ```Java
>       // If the planCreator already sent the yamlVersion for its children then that value will be considered. So
>       // continue.
>       if (parentInfoFromPlanCreator.getDataMap().containsKey(PlanCreatorConstants.YAML_VERSION)) {
> ```

insert all currentNodeParentInfo, then iterate parentNode from initialDependencies, if any key already present in current node then skip, else copy it to make it generic
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 241 at r1](https://reviewable.io/reviews/harness/harness-core/52362#-NdFYwSZ6ugrJVjUgLHE:-NdFYwSZ6ugrJVjUgLHF:b-70dvcy) ([raw file](https://github.com/harness/harness-core/blob/28654e5112835c34cd3395e9b3bdb17d2a3441f9/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L241)):*
> ```Java
>       }
>       HarnessStruct newParentInfo =
>           parentInfoFromPlanCreator.toBuilder().putData(PlanCreatorConstants.YAML_VERSION, parentVersion).build();
> ```

use above method map

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52362)* status: 2 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 217 at r1](https://reviewable.io/reviews/harness/harness-core/52362#-NdFYB9f6-T_CyaEsFzp:-NdFhF7q2t4ajcrc-Lao:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/28654e5112835c34cd3395e9b3bdb17d2a3441f9/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L217)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you pass as Map? key as YAML_VERSION, and value of field, so other can add to same map
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 229 at r1](https://reviewable.io/reviews/harness/harness-core/52362#-NdFYc2Q6m5nvjFWQDBA:-NdFhG0n6NmxQEV9y1y7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/28654e5112835c34cd3395e9b3bdb17d2a3441f9/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L229)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you rename to parentInfoOfCurrentNode
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 230 at r1](https://reviewable.io/reviews/harness/harness-core/52362#-NdFYLLJ7PnNm9Alqzfy:-NdFhH0t9zGjAuIhH2-I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/28654e5112835c34cd3395e9b3bdb17d2a3441f9/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L230)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

lets not useYaml version, here mentioned metadata sent by currentNode take priority than parent one
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 232 at r1](https://reviewable.io/reviews/harness/harness-core/52362#-NdFYyJuAHbSLnAT8GMF:-NdFhHjD3a42bP1uzXEf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/28654e5112835c34cd3395e9b3bdb17d2a3441f9/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L232)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

insert all currentNodeParentInfo, then iterate parentNode from initialDependencies, if any key already present in current node then skip, else copy it to make it generic
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 241 at r1](https://reviewable.io/reviews/harness/harness-core/52362#-NdFYwSZ6ugrJVjUgLHE:-NdFhIa25oKvhu4Beslu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/28654e5112835c34cd3395e9b3bdb17d2a3441f9/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L241)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use above method map
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52362)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 241 at r2](https://reviewable.io/reviews/harness/harness-core/52362#-NdGDZsn7nKp-IYqd415:-NdGDZsoCLEtsECp-N4k:b-65ea28) ([raw file](https://github.com/harness/harness-core/blob/29d57c7ae7ccd8eabe3ae276c65c8fab1e404d0c/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L241)):*
> ```Java
>         // If parentVersion is null then populate from the metadata from initialValuesMap. This will happen for the root
>         // yaml node. Pipeline.
>         if (parentInfoValue == null && initialValuesMap.get(parentInfoKey) != null) {
> ```

isnt intialiValuesMap same as parentInfoOfCurrentNode.getDataMap() or if not getParentInfoFromParentDependency, why there would be 3 maps? only 2should be there right?



_Code quote:_
```Java
initialValuesMap.get(parentInfoKey)
```

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52362)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 241 at r2](https://reviewable.io/reviews/harness/harness-core/52362#-NdGDZsn7nKp-IYqd415:-NdUJ1wmDZLbSyKVW9i8:by2sgw9) ([raw file](https://github.com/harness/harness-core/blob/29d57c7ae7ccd8eabe3ae276c65c8fab1e404d0c/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L241)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

isnt intialiValuesMap same as parentInfoOfCurrentNode.getDataMap() or if not getParentInfoFromParentDependency, why there would be 3 maps? only 2should be there right?
</blockquote></details>

Its different. parentInfoOfCurrentNode is from the parent. But intialiValuesMap would be used when the value from parent in not prensent.(means no parent had passed the value.) Basically for the starting node pipeline.

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52362)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by prashantsharma04 — APPROVED** [review]

**Pull request merged**
