### PR TITLE
feat: [PL-43284]: Added API for secret text migration from CG to Ng

### PR DESCRIPTION
**Pull request by meenakshi-harness**
## Describe your changes
Added `textMigration` API to migrate secret text from CG to NG.

Testing:
1. Migrated a secret from CG via this APi and used in github connector to test decryption.
2. Verified mongo data

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57044)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57044)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 225 at r1](https://reviewable.io/reviews/harness/harness-core/57044#-NmB2diB359U0PnDzClO:-NmB2diB359U0PnDzClP:b-fe6sdc) ([raw file](https://github.com/harness/harness-core/blob/50a0fd18a133545d5c0e7792dbac0fef22229504/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L225)):*
> ```Java
> 
>     validateAdditionalMetadata(secretManager, secret);
>     NGEncryptedData encryptedData = buildNGEncryptedData(accountIdentifier, dto, secretManager);
> ```

This is duplicate in overloaded method. Can we de-duplicate and reuse?



_Code quote:_
```Java
    validateSecretDoesNotExist(
        accountIdentifier, dto.getOrgIdentifier(), dto.getProjectIdentifier(), dto.getIdentifier());
    SecretTextSpecDTO secret = (SecretTextSpecDTO) dto.getSpec();
    SecretManagerConfigDTO secretManager = getSecretManagerOrThrow(accountIdentifier, dto.getOrgIdentifier(),
        dto.getProjectIdentifier(), secret.getSecretManagerIdentifier(), false);

    validateAdditionalMetadata(secretManager, secret);
    NGEncryptedData encryptedData = buildNGEncryptedData(accountIdentifier, dto, secretManager);
```
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 318 at r1](https://reviewable.io/reviews/harness/harness-core/57044#-NmB3WUE2KHDEjqDs6sH:-NmB3WUF5NLFI4qDhXky:bdmlad3) ([raw file](https://github.com/harness/harness-core/blob/50a0fd18a133545d5c0e7792dbac0fef22229504/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L318)):*
> ```Java
>       throw new InvalidRequestException(
>           "Built-in Harness Secret Manager cannot be used to create Secret as it has been disabled.");
>     }
> ```

Same here. Can we extract duplicate code and reuse.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java` line 563 at r1](https://reviewable.io/reviews/harness/harness-core/57044#-NmB3tbT3zuqJV6T_hZD:-NmB3tbT3zuqJV6T_hZE:buqt45z) ([raw file](https://github.com/harness/harness-core/blob/50a0fd18a133545d5c0e7792dbac0fef22229504/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java#L563)):*
> ```Java
>       })
>   @Consumes(MediaType.MULTIPART_FORM_DATA)
>   public ResponseDTO<SecretResponseWrapper>
> ```

Should be marked as Internal as well?

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57044)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java` line 563 at r1](https://reviewable.io/reviews/harness/harness-core/57044#-NmB3tbT3zuqJV6T_hZD:-NmB5ajU-4ZMp4HlNAoX:bvqnjtz) ([raw file](https://github.com/harness/harness-core/blob/50a0fd18a133545d5c0e7792dbac0fef22229504/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java#L563)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should be marked as Internal as well?
</blockquote></details>

Have added  `@Hidden` do we need internal annotation as well?

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57044)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 225 at r1](https://reviewable.io/reviews/harness/harness-core/57044#-NmB2diB359U0PnDzClO:-NmBRO-pCvwxcI7aNri_:bgt400j) ([raw file](https://github.com/harness/harness-core/blob/50a0fd18a133545d5c0e7792dbac0fef22229504/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L225)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This is duplicate in overloaded method. Can we de-duplicate and reuse?
</blockquote></details>

Yes this is duplicate but does not have any logical code. In each line we are calling some method and its returned value is used in further in above method. hence extracting these lines might not help much
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 318 at r1](https://reviewable.io/reviews/harness/harness-core/57044#-NmB3WUE2KHDEjqDs6sH:-NmBSpIB5I9RLN3FjlkF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50a0fd18a133545d5c0e7792dbac0fef22229504/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L318)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Same here. Can we extract duplicate code and reuse.
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57044)* status: 5 file(s) to review. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java` line 563 at r1](https://reviewable.io/reviews/harness/harness-core/57044#-NmB3tbT3zuqJV6T_hZD:-NmFex-54Z6fZDbTaQTT:b-v3bykb) ([raw file](https://github.com/harness/harness-core/blob/50a0fd18a133545d5c0e7792dbac0fef22229504/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java#L563)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Have added  `@Hidden` do we need internal annotation as well?
</blockquote></details>

We can check based on requirement from migration service.

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Pull request merged**
