### PR TITLE
[feat]: [CDS-82354]: Support for Input Selection for Remote Infrastructures.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:

Changes: Have added a new API for fetching runtimeInputYaml for Remote Services, (also handles INLINE entites), Have added EntityGitDetails in Env and Infra response.

Cases Tested: 

- Infrastructure in the same branch and repo as that of Env. Correct RuntimeInputYaml was observed on the API response.
- Regarding Addition of ConcurrentQueues , Correct RuntimeInputYaml was observed on the API response for Srv, Env and Infra.
- GetMetadata Support for Infra was tested and no gitCall was made and only dB entity was returned.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54573)

### CODE REVIEW

**Review by hingerabhinav — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54573)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenConfiguration.java` line 307 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-Nhf81v03SxGM8BdZK7v:-Nhf81v03SxGM8BdZK7w:bcuiz2e) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/120-ng-manager/src/main/java/io/harness/ng/NextGenConfiguration.java#L307)):*
> ```Java
>   @JsonProperty("environmentGitXThreadConfig") private EnvironmentGitXThreadConfiguration environmentGitXThreadConfig;
>   @JsonProperty("infrastructureGitXThreadConfig")
>   private InfrastructureGitXThreadConfiguration infrastructureGitXThreadConfig;
> ```

@yogesh-chauhan should we utilise the same thread pool of environments? Can increase pool if needed. Since env/infra are related, I think we can. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 623 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfBix98Iq0tYEkuQZT:-NhfBix98Iq0tYEkuQZU:b-p8i6fx) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L623)):*
> ```Java
>   }
> 
>   private Map<String, String> getInfrastrctureBranchMap(String accountIdentifier, String orgIdentifier,
> ```

we can remove this 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1042 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfD0tr28QsMR4LsbhH:-NhfD0tr28QsMR4LsbhI:bj9znqt) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1042)):*
> ```Java
>                   environmentRepository.getRemoteEnvironmentWithYaml(env, loadFromCache, false);
>               environmentRefAndEntityMap.put(envRef, environmentFromRemote);
>               environmentRefAndGitDetailsMap.put(
> ```

We should use a concurrent hash map since these threads are writing into map async. Also why do we need this map at all? Can we create environment inputs here itself? Environment YAML will get updated in place. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 908 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfFa1-2YOwnTyDlgSH:-NhfFa1-2YOwnTyDlgSI:b-iemwc2) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L908)):*
> ```Java
>       boolean loadFromCache) {
>     List<InfrastructureEntity> infrastructureEntities = new ArrayList<>();
>     if (!EngineExpressionEvaluator.hasExpressions(environmentRef)) {
> ```

if environment ref is an expression we should return early and not call child method 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 929 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfFwPh-lUHoPj1679W:-NhfFwPiD-fP7FvapqY4:b-coa0z7) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L929)):*
> ```Java
>         if (StoreType.REMOTE.equals(infra.getStoreType())) {
>           CompletableFuture<Void> future = CompletableFuture.runAsync(() -> {
>             try (GitXTransientBranchGuard ignore = new GitXTransientBranchGuard(branch)) {
> ```

Do you need transient branch guard if the branch is already set in git context? 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 935 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfGk9C23WNwp5Q-8y8:-NhfGk9C23WNwp5Q-8y9:bnntzp3) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L935)):*
> ```Java
>                   createInfrastructureYamlMetadataInternal(infrastructureFromRemote);
>               addScopeIdentifiersInResponse(infra, infrastructureYamlMetadataInternal);
>               addGitXParamsToResponse(infrastructureFromRemote, infrastructureYamlMetadataInternal);
> ```

we should have a single method to create infra metadata from the entity. scope and git params can be added together. helps avoid repeating code.  
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 970 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfHOmE0oRSbMteembE:-NhfHOmE0oRSbMteembF:bbngmv1) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L970)):*
> ```Java
>   }
> 
>   public static EntityGitDetails getEntityGitDetails(InfrastructureEntity infrastructureEntity) {
> ```

We should have a similar method in Infra mapper. Please use that.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54573)* status: 19 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 623 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfBix98Iq0tYEkuQZT:-NhfQSc83MiAy9qJyFiY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L623)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

we can remove this
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 908 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfFa1-2YOwnTyDlgSH:-NhfR9uI90QauehPQdiX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L908)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

if environment ref is an expression we should return early and not call child method
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 929 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfFwPh-lUHoPj1679W:-NhfRF8J23fL48ZF6vcP:brpmqc3) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L929)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

Do you need transient branch guard if the branch is already set in git context?
</blockquote></details>

removed.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 935 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfGk9C23WNwp5Q-8y8:-NhfRGkZCgjiLrKa3GPN:b-u14s56) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L935)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

we should have a single method to create infra metadata from the entity. scope and git params can be added together. helps avoid repeating code.
</blockquote></details>

In the new Yaml version scope Identifiers will be in the entity in DB hence used from there, else fields are used from entity fetched from remote.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 970 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfHOmE0oRSbMteembE:-NhfR_jM-Kk_6dwrr-1k:b-m8ieww) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L970)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

We should have a similar method in Infra mapper. Please use that.
</blockquote></details>

InfrastructureMapper is not visible in this file instead of including in build file for just smaal piece of code i duplicated it.

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenConfiguration.java` line 307 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-Nhf81v03SxGM8BdZK7v:-NhfbXI-AatEuAAFYJel:bb7uw1q) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/120-ng-manager/src/main/java/io/harness/ng/NextGenConfiguration.java#L307)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

@yogesh-chauhan should we utilise the same thread pool of environments? Can increase pool if needed. Since env/infra are related, I think we can.
</blockquote></details>

Yes, we should re-use

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 623 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfBix98Iq0tYEkuQZT:-NhfbiOS7sDC4GrVNmsI:b-p7hr0v) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L623)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Does this assume all infra will always belong to the same environment ?

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/InfrastructureEntityService.java` line 95 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfcFmoBxNQP8yd3N8U:-NhfcFmoBxNQP8yd3N8V:bhdujyv) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/InfrastructureEntityService.java#L95)):*
> ```Java
> 
>   List<InfrastructureYamlMetadata> createInfrastructureYamlMetadata(String accountId, String orgIdentifier,
>       String projectIdentifier, String environmentIdentifier, List<String> infraIds);
> ```

can we not add loadFromCache in this method itself ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 5 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54573)* status: 14 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54573)* status: 15 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 623 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfBix98Iq0tYEkuQZT:-NhjKov0CpkOf3B53Z3C:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L623)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Does this assume all infra will always belong to the same environment ?
</blockquote></details>

yes
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1042 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfD0tr28QsMR4LsbhH:-NhjKqW--G3B7vCQnxr4:b-ll1b1z) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1042)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

We should use a concurrent hash map since these threads are writing into map async. Also why do we need this map at all? Can we create environment inputs here itself? Environment YAML will get updated in place.
</blockquote></details>

Improved Logic and Now calculating the runtimeInputYaml within the brach guards.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/InfrastructureEntityService.java` line 95 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfcFmoBxNQP8yd3N8U:-NhjL8RR6_--aJubPvO2:b-ybshbn) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/InfrastructureEntityService.java#L95)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we not add loadFromCache in this method itself ?
</blockquote></details>

For both Env and Infra new APIs are made, with separate flows to minimize the chances of regressions.
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenConfiguration.java` line 307 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-Nhf81v03SxGM8BdZK7v:-NhjKfgN3ylRnD-39bfP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/120-ng-manager/src/main/java/io/harness/ng/NextGenConfiguration.java#L307)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Yes, we should re-use
</blockquote></details>

Done.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 953 at r3](https://reviewable.io/reviews/harness/harness-core/54573#-NhjhYLD5tF6MerennoM:-NhjhYLE7wVBjygUFrBz:b-8k59l) ([raw file](https://github.com/harness/harness-core/blob/65356b7c6eafbc094df75a95d839482cf182cf61/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L953)):*
> ```Java
> 
>     for (int i = 0; i < environmentEntities.size(); i += REMOTE_ENVIRONMENTS_BATCH_SIZE) {
>       List<Environment> batch = getBatch(environmentEntities, i);
> ```

did we sort environments by store Type ?

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 948 at r3](https://reviewable.io/reviews/harness/harness-core/54573#-Nhjj7pL5YzyHKEb5ece:-Nhjj7pL5YzyHKEb5ecf:bat7zkg) ([raw file](https://github.com/harness/harness-core/blob/65356b7c6eafbc094df75a95d839482cf182cf61/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L948)):*
> ```Java
>       List<String> serviceRefs, boolean isServiceOverrideV2FFEnabled, boolean loadFromCache) {
>     List<EnvironmentInputSetYamlAndServiceOverridesMetadata> environmentInputSetYamlAndServiceOverridesMetadataList =
>         new ArrayList<>();
> ```

This is a simple array list. Since we are adding elements to it via multiple threads in parallel, it can lead to ConcurrentModificationException
Ref: https://blog.codingblocks.com/2019/keeping-arraylists-safe-across-threads-in-java/

We can use thread safe variants of the List as belows
- https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ConcurrentLinkedQueue.html
- CopyOnWriteArrayList

I feel the ConcurrentLinkedQueue is better for our use case cc: @hingerabhinav

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 6 of 19 files at r1, 2 of 4 files at r2, 5 of 6 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54573)* status: 10 file(s) to review. 1 change requests. 7. unresolved discussions. 1 of 2 approvals obtained.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54573)* status: 10 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 948 at r3](https://reviewable.io/reviews/harness/harness-core/54573#-Nhjj7pL5YzyHKEb5ece:-Nhl6mx13wS1rn6O__bf:bb6tzbb) ([raw file](https://github.com/harness/harness-core/blob/65356b7c6eafbc094df75a95d839482cf182cf61/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L948)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This is a simple array list. Since we are adding elements to it via multiple threads in parallel, it can lead to ConcurrentModificationException
Ref: https://blog.codingblocks.com/2019/keeping-arraylists-safe-across-threads-in-java/

We can use thread safe variants of the List as belows
- https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ConcurrentLinkedQueue.html
- CopyOnWriteArrayList

I feel the ConcurrentLinkedQueue is better for our use case cc: @hingerabhinav
</blockquote></details>

DOne
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 953 at r3](https://reviewable.io/reviews/harness/harness-core/54573#-NhjhYLD5tF6MerennoM:-Nhl6nny0gsWCTg4eYDJ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/65356b7c6eafbc094df75a95d839482cf182cf61/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L953)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

did we sort environments by store Type ?
</blockquote></details>

Done

**Comment by senjucanon2** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54573)* status: 10 file(s) to review. 1 change requests. 7. unresolved discussions. 1 of 2 approvals obtained.

**Review by hingerabhinav — COMMENTED** [review]
> Reviewed 2 of 4 files at r2, 5 of 6 files at r3, 3 of 3 files at r6, all commit messages.
> Dismissed @hingerabhinav from a discussion.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54573)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 623 at r1](https://reviewable.io/reviews/harness/harness-core/54573#-NhfBix98Iq0tYEkuQZT:-Nhfr5dE2f-CIjTePfig:btyti1p) ([raw file](https://github.com/harness/harness-core/blob/477142ec1faab6d2f2f69a6af72f882d695aafc7/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L623)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Does this assume all infra will always belong to the same environment ?
</blockquote></details>

Yes @yogesh-chauhan .Current implementation will assume all infrastructures will belong to a specific branch. Static support will be implemented based on user feedback.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Review by yogesh-chauhan — DISMISSED** [review]

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54573)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]

**Pull request merged**
