### PR TITLE
techdebt: [CDS-80503]: Add param to fetch retry failed pipelines in e…

### PR DESCRIPTION
**Pull request by prashantsharma04**
…xecution summary list

## Describe your changes

The PR contains two changes
1. adding showAllExecutions as query param in summary api: With value as true, this will list all executions along with retried one. Currently we only show the latest of all retried execution. The default value is false, hence no change in current flow. How ever user can set its value as true in order to fetch all execution

2. Added unit test for execution list page.

Testing: local

Screenshot 2023-09-29 at 12 32 34 PM
Screenshot 2023-09-29 at 12 33 17 PM

Pipeline And ExecutionList page.

Screenshot 2023-09-29 at 1 21 30 PM
Screenshot 2023-09-29 at 1 24 16 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53528)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger uts

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53528)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53528)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 702 at r3](https://reviewable.io/reviews/harness/harness-core/53528#-NfUkmH69APMOYqHwWMT:-NfUkmH69APMOYqHwWMU:b-r7zvcb) ([raw file](https://github.com/harness/harness-core/blob/f07a26566ae3db040e58a18b90795e1de9591e7c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L702)):*
> ```Java
>           pmsPipelineService.getPermittedPipelineIdentifier(accountId, orgId, projectId, allPipelineIdentifiers);
> 
>       criteria.and(PlanExecutionSummaryKeys.pipelineIdentifier).in(permittedPipelineIdentifiers);
> ```

why this should change? i think pipeline list and execution summary list has different criteria that's why -> can you take pipelineField name from caller then?

**Comment by prashantsharma04** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53528)* status: 6 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 702 at r3](https://reviewable.io/reviews/harness/harness-core/53528#-NfUkmH69APMOYqHwWMT:-NfUxt-q8OQaeGoPBu4w:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f07a26566ae3db040e58a18b90795e1de9591e7c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L702)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this should change? i think pipeline list and execution summary list has different criteria that's why -> can you take pipelineField name from caller then?
</blockquote></details>

done

**Comment by prashantsharma04** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53528)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by prashantsharma04** [comment]
trigger review

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53528)* status: :shipit: complete! ✓

**Comment by prashantsharma04** [comment]
trigger review

**Pull request merged**
