### PR TITLE
[fix]: [PL-42156]: Adds handling to block acl processing if account is blocked

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
Adds handling to block ACL processing if account is blocked. This support is added in new flows of Access control as per
https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21361983548/Access+Control+Service+Design+Improvements

Tests:
- If account is not blocked
  - Usergroup updates processing ACL as expected
  - Role updates processing ACL as expected
  - Rresource group updates processing ACL as expected
  - Role assignment updates processing ACL as expected
- If account is blocked
  - Usergroup updates not processing ACL as expected
  - Role updates not processing ACL as expected
  - Rresource group updates not processing ACL as expected
  - Role assignment updates not processing ACL as expected
- After unblocking a blocked account
  - ACLs got generated for all role assignments present in account as expected

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54855)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54855)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/GenerateACLsFromRoleAssignmentsJob.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/54855#-NiE8tRb9c4-wmnl0QMg:-NiE8tRb9c4-wmnl0QMh:b86edvd) ([raw file](https://github.com/harness/harness-core/blob/88c1f8a7bc0adb763f90cf49b7417356e46881c1/access-control/libs/aggregator/src/main/java/io/harness/aggregator/GenerateACLsFromRoleAssignmentsJob.java#L66)):*
> ```Java
> 
>   private long upsertACLs(RoleAssignmentDBO roleAssignment) {
>     // aclRepository.deleteByRoleAssignmentId(roleAssignment.getId());
> ```

rebase as merged this change.

**Comment by ashishsanodia-harness** [comment]
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/GenerateACLsFromRoleAssignmentsJob.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/54855#-NiE8tRb9c4-wmnl0QMg:-NiEA0jQCEcVV5ZXFMZ4:berotl2) ([raw file](https://github.com/harness/harness-core/blob/88c1f8a7bc0adb763f90cf49b7417356e46881c1/access-control/libs/aggregator/src/main/java/io/harness/aggregator/GenerateACLsFromRoleAssignmentsJob.java#L66)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

rebase as merged this change.
</blockquote></details>

There is no merge conflict. Also changes are same so auto merge will take care of this

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 11 of 16 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54855)* status: 16 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AccessControlChangeEventData.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/54855#-NiEE3nZ3IB_rsLKCjtS:-NiEE3nZ3IB_rsLKCjtT:b-kn7hvk) ([raw file](https://github.com/harness/harness-core/blob/3a4e651ebad2e9f3c2bc04d0192067b493be5ac7/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AccessControlChangeEventData.java#L14)):*
> ```Java
> import java.util.Optional;
> 
> public interface AccessControlChangeEventData {
> ```

This should not be an interface but a class
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/models/RoleChangeEventData.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/54855#-NiEEBDt1AKhHbpoF__P:-NiEEBDt1AKhHbpoF__Q:b-nhqe6y) ([raw file](https://github.com/harness/harness-core/blob/3a4e651ebad2e9f3c2bc04d0192067b493be5ac7/access-control/libs/aggregator/src/main/java/io/harness/aggregator/models/RoleChangeEventData.java#L18)):*
> ```Java
> import java.util.Set;
> import lombok.Data;
> import lombok.experimental.SuperBuilder;
> ```

What does this SuperBuilder do?

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54855)* status: 16 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AccessControlChangeEventData.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/54855#-NiEE3nZ3IB_rsLKCjtS:-NiEjd2N5fiQejre6V5m:bfwf8rg) ([raw file](https://github.com/harness/harness-core/blob/3a4e651ebad2e9f3c2bc04d0192067b493be5ac7/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AccessControlChangeEventData.java#L14)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This should not be an interface but a class
</blockquote></details>

@ankit-harness why so?

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/models/RoleChangeEventData.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/54855#-NiEEBDt1AKhHbpoF__P:-NiEk4-PBx_3wMvDhYZe:bqmi3w7) ([raw file](https://github.com/harness/harness-core/blob/3a4e651ebad2e9f3c2bc04d0192067b493be5ac7/access-control/libs/aggregator/src/main/java/io/harness/aggregator/models/RoleChangeEventData.java#L18)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

What does this SuperBuilder do?
</blockquote></details>

SuperBuilder works with fields from superclasses as well.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AccessControlChangeEventData.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/54855#-NiEE3nZ3IB_rsLKCjtS:-NiIItrSEoWIFVO5ya3l:b-adj3vc) ([raw file](https://github.com/harness/harness-core/blob/3a4e651ebad2e9f3c2bc04d0192067b493be5ac7/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AccessControlChangeEventData.java#L14)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

@ankit-harness why so?
</blockquote></details>

Converted to class.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 16 files at r1, 5 of 5 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54855)* status: 19 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54855)* status: 26 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AbstractAccessControlChangeConsumer.java` line 25 at r6](https://reviewable.io/reviews/harness/harness-core/54855#-NjRUV4Q7FFrZWVrj8ul:-NjRUV4Q7FFrZWVrj8um:b-im0xol) ([raw file](https://github.com/harness/harness-core/blob/9675431515a245c7a8a1dea21761a405b7359451/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AbstractAccessControlChangeConsumer.java#L25)):*
> ```Java
> 
>   public boolean shouldBlock(AccessControlChangeEventData changeEventData) {
>     if (isNull(changeEventData.getScope()) || changeEventData.getScope().isEmpty()) {
> ```

Lets use io.harness.data.structure.EmptyPredicate#isEmpty(java.lang.String)

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54855)* status: 26 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java` line 363 at r6](https://reviewable.io/reviews/harness/harness-core/54855#-NjRdKqd4yHPtTcrOB3S:-NjRdKqd4yHPtTcrOB3T:bm8e1lk) ([raw file](https://github.com/harness/harness-core/blob/9675431515a245c7a8a1dea21761a405b7359451/access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java#L363)):*
> ```Java
>     roleEventHandler.handle(outboxEvent);
>     verify(auditClientService, times(1)).publishAudit(auditEntryArgumentCaptor.capture(), any());
>     verify(roleChangeConsumer, never()).consumeEvent(any(), any(), any());
> ```

I think we should change to
verify(roleChangeConsumer, never()).consumeEvent(eq(UPDATE_ACTION) any(), any());

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54855)* status: 26 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java` line 329 at r6](https://reviewable.io/reviews/harness/harness-core/54855#-NjRdRRB-BbBx0Dxxf_9:-NjRdRRB-BbBx0Dxxf_A:bm8e1lk) ([raw file](https://github.com/harness/harness-core/blob/9675431515a245c7a8a1dea21761a405b7359451/access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java#L329)):*
> ```Java
>     roleEventHandler.handle(outboxEvent);
>     verify(auditClientService, times(1)).publishAudit(auditEntryArgumentCaptor.capture(), any());
>     verify(roleChangeConsumer, never()).consumeEvent(any(), any(), any());
> ```

I think we should change to
verify(roleChangeConsumer, never()).consumeEvent(eq(UPDATE_ACTION) any(), any());
___
*[`access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java` line 394 at r6](https://reviewable.io/reviews/harness/harness-core/54855#-NjRdSBJ3gruaN_aQijZ:-NjRdSBJ3gruaN_aQij_:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/9675431515a245c7a8a1dea21761a405b7359451/access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java#L394)):*
> ```Java
>     verify(auditClientService, never()).publishAudit(any(), any());
>     verify(scopeService, never()).buildScopeFromScopeIdentifier(any());
>     verify(roleChangeConsumer, never()).consumeEvent(any(), any(), any());
> ```

same as above

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AbstractAccessControlChangeConsumer.java` line 25 at r6](https://reviewable.io/reviews/harness/harness-core/54855#-NjRUV4Q7FFrZWVrj8ul:-NjS3eVZ0WcMH5mjYoJ3:bkqgucu) ([raw file](https://github.com/harness/harness-core/blob/9675431515a245c7a8a1dea21761a405b7359451/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AbstractAccessControlChangeConsumer.java#L25)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Lets use io.harness.data.structure.EmptyPredicate#isEmpty(java.lang.String)
</blockquote></details>

changeEventData.getScope() returns Optional and there is no support for Optional in EmptyPredicate.

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java` line 329 at r6](https://reviewable.io/reviews/harness/harness-core/54855#-NjRdRRB-BbBx0Dxxf_9:-NjS3qDn0fRPI_WsAF35:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9675431515a245c7a8a1dea21761a405b7359451/access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java#L329)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

I think we should change to
verify(roleChangeConsumer, never()).consumeEvent(eq(UPDATE_ACTION) any(), any());
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java` line 363 at r6](https://reviewable.io/reviews/harness/harness-core/54855#-NjRdKqd4yHPtTcrOB3S:-NjS3qyQ5YYzXk7-u2Th:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9675431515a245c7a8a1dea21761a405b7359451/access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java#L363)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

I think we should change to
verify(roleChangeConsumer, never()).consumeEvent(eq(UPDATE_ACTION) any(), any());
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java` line 394 at r6](https://reviewable.io/reviews/harness/harness-core/54855#-NjRdSBJ3gruaN_aQijZ:-NjS3xbgCWKPeGyRxomW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9675431515a245c7a8a1dea21761a405b7359451/access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java#L394)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54855)* status: 25 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java` line 419 at r7](https://reviewable.io/reviews/harness/harness-core/54855#-NjSPPr7AkX7HFRqIswz:-NjSPPr8DnS27CscNsz0:b-b49vj1) ([raw file](https://github.com/harness/harness-core/blob/080248cd7ebec841aee274de030217419db1fcc6/access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java#L419)):*
> ```Java
>     verify(auditClientService, never()).publishAudit(any(), any());
>     verify(scopeService, never()).buildScopeFromScopeIdentifier(any());
>     verify(roleChangeConsumer, never()).consumeEvent(any(), any(), any());
> ```

Change this one as well.

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java` line 419 at r7](https://reviewable.io/reviews/harness/harness-core/54855#-NjSPPr7AkX7HFRqIswz:-NjSQJNo1o1iHI5EzAqM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/080248cd7ebec841aee274de030217419db1fcc6/access-control/service/src/test/java/io/harness/accesscontrol/commons/outbox/RoleEventHandlerTest.java#L419)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Change this one as well.
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 2 of 16 files at r1, 1 of 4 files at r2, 5 of 5 files at r3, 1 of 3 files at r5, 15 of 16 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54855)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
