### PR TITLE
[fix]: [CDS-54390]: Do not add secret reference when value is absent

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
If a secret ng variable, does not have an associated value, we should not extract references from it
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45049)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`953-yaml-commons/src/main/java/io/harness/visitor/helpers/variables/SecretVariableVisitorHelper.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/45049#-NQQ8-yH-3dsHZZMC5PD:-NQQ8-yH-3dsHZZMC5PE:bytjt2a) ([raw file](https://github.com/harness/harness-core/blob/0709ed513de435e26991828687e18fa0ff2914db/953-yaml-commons/src/main/java/io/harness/visitor/helpers/variables/SecretVariableVisitorHelper.java#L62)):*
> ```Java
>       return result;
>     } catch (Exception ex) {
>       throw new InvalidRequestException("Failed to create reference for secret " + secretNGVariable.getName(), ex);
> ```

This adds more context to the message

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45049)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45049)* status: :shipit: complete! ✓

**Review by utkarshchoubey-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45049#-:-NQ_Lic23r9b5i3YBzRY:bnfp4nl)* status: :shipit: complete! ✓

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45049)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45049)* status: :shipit: complete! ✓

**Pull request merged**
