### PR TITLE
fix: [PL-31097]: Service account entity deletion when scope gets deleted

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Describe your changes
Whenever a project, org or account gets deleted, we will delete the service accounts at that scope level. As of now whenever a project/org is deleted, we are not deleting the serivce accounts in that scope. After this change, these will get deleted.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43121)

### CODE REVIEW

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43121)* status: 6 file(s) to review. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/impl/ServiceAccountServiceImpl.java` line 191 at r1](https://reviewable.io/reviews/harness/harness-core/43121#-NMlj__Y0j9yMGBaoaoI:-NMlj__Y0j9yMGBaoaoJ:b-pkp6pe) ([raw file](https://github.com/harness/harness-core/blob/ef3e51cebd428e15ab174e52eb9172dd0415cd5f/120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/impl/ServiceAccountServiceImpl.java#L191)):*
> ```Java
>   @Override
>   public void deleteBatch(String accountIdentifier, String orgIdentifier, String projectIdentifier) {
>     List<ServiceAccount> serviceAccounts =
> ```

In order to make sure the subscope service accounts are also deleted, I want to confirm that a message will published for each subscope as well. Like if an org is deleted, a project delete message will be published for each of its projects, right?

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43121)* status: 6 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/impl/ServiceAccountServiceImpl.java` line 191 at r1](https://reviewable.io/reviews/harness/harness-core/43121#-NMlj__Y0j9yMGBaoaoI:-NMlkZ432LX7zXl5gM6D:bjt5q5e) ([raw file](https://github.com/harness/harness-core/blob/ef3e51cebd428e15ab174e52eb9172dd0415cd5f/120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/impl/ServiceAccountServiceImpl.java#L191)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

In order to make sure the subscope service accounts are also deleted, I want to confirm that a message will published for each subscope as well. Like if an org is deleted, a project delete message will be published for each of its projects, right?
</blockquote></details>

Yes if org gets deleted, then we will have project delete events publish. This will make sure all those project scope entities also gets deleted. Similarly for account deletion, all orgs deleted events are also published. Tested this flow for service accounts deletion.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43121)* status: 4 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43121)* status: :shipit: complete! ✓

**Pull request merged**
