### PR TITLE
fix: [DEL-4189]: add JsonIgnoreProperties

### PR DESCRIPTION
**Pull request by arpit3107**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33683)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33683)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateRegisterResponse.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/33683#-N3K7C6yAR5Du2s69wfw:-N3K7C6yAR5Du2s69wfx:b-d3cv1r) ([raw file](https://github.com/harness/harness-core/blob/8e17e9188198e9c4428c2728e878bccb56329d3b/920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateRegisterResponse.java#L21)):*
> ```Java
>   String sequenceNum;
>   String delegateRandomToken;
>   String delegateTokenName;
> ```

Why do we both remove the tokenName and add jsonIgnore. Is tokenName needed? what was rationale behind adding it?

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33683)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateRegisterResponse.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/33683#-N3K7C6yAR5Du2s69wfw:-N3K7iQi9lHyD-wvB5j-:bwy1ewa) ([raw file](https://github.com/harness/harness-core/blob/8e17e9188198e9c4428c2728e878bccb56329d3b/920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateRegisterResponse.java#L21)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Btw json ignore properties will not help here with older delegates and it would still be backwards incompatible, since they are not ignoring it (the change would only apply to new delegates)
</blockquote></details>

tokenName is needed, but i am removing it and adding JsonIgnore so that in case if we ever want to rollback delegate in prod, we will not face any issues.

So, the plan is that attach JsonIgnore now, and then from next week start using tokenName

**Review by mdmilic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33683)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateRegisterResponse.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/33683#-N3K7C6yAR5Du2s69wfw:-N3K8_ZF4NUDzjY0X6wg:bprglav) ([raw file](https://github.com/harness/harness-core/blob/8e17e9188198e9c4428c2728e878bccb56329d3b/920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateRegisterResponse.java#L21)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

tokenName is needed, but i am removing it and adding JsonIgnore so that in case if we ever want to rollback delegate in prod, we will not face any issues.

So, the plan is that attach JsonIgnore now, and then from next week start using tokenName 
</blockquote></details>

Ok, but you still have immutable delegates, they might pick this change up only in few months! 
Also, I think we should do ignoreUnknown globally on delegate, it would make it much easier to introduce changes in the future, but that is a big (logical) change and we would need team buy-in. I think you should look into pros and cons and start the discussion on slack about it.

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33683)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateRegisterResponse.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/33683#-N3K7C6yAR5Du2s69wfw:-N3KC5jZEuFyoF1wPIXL:b4b5zta) ([raw file](https://github.com/harness/harness-core/blob/8e17e9188198e9c4428c2728e878bccb56329d3b/920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateRegisterResponse.java#L21)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Ok, but you still have immutable delegates, they might pick this change up only in few months! 
Also, I think we should do ignoreUnknown globally on delegate, it would make it much easier to introduce changes in the future, but that is a big (logical) change and we would need team buy-in. I think you should look into pros and cons and start the discussion on slack about it. 
</blockquote></details>

this hasnt gone into master. Its in develop only till now. So we can remove it

**Review by mdmilic — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33683)* status: :shipit: complete! ✓

**Comment by arpit3107** [comment]
trigger messagecheck

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33683)* status: :shipit: complete! ✓

**Pull request merged**
