### PR TITLE
[feat]: [PIE-2708]: Add step outcomes for Policy Step

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31010)

### CODE REVIEW

**Review by naidu-harness — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31010)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31010)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[970-ng-commons/src/main/java/io/harness/beans/IdentifierRef.java, line 43 at r1](https://reviewable.io/reviews/harness/harness-core/31010#-Mwk4WCmDPnx1eNLVzTO:-Mwk7p4oEfZ21YYULkaA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dc24857909d29dec61444303afae872c9934700f/970-ng-commons/src/main/java/io/harness/beans/IdentifierRef.java#L43)):*
<details><summary><i>Previously, naidu-harness (Sanyasi Naidu Annepu) wrote…</i></summary><blockquote>

should be `account.`
</blockquote></details>

Done.

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31010#-:-Mwk7zkF1r7OjnwrJeHR:bnfp4nl)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Comment by namanvermah** [comment]
trigger ti0, ti1, ti2, ti3, ti4, ft1, ft2

**Comment by namanvermah** [comment]
trigger compile, checkstyle

**Comment by namanvermah** [comment]
trigger ft1, ft2

**Comment by namanvermah** [comment]
trigger compile, checkstyle

**Comment by namanvermah** [comment]
trigger ft2

**Review by hextechpal — APPROVED** [review]
> Reviewed 7 of 10 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31010)* status: :shipit: complete! ✓

**Pull request merged**
