### PR TITLE
feat: [SRM-13987]: Added Notifications for composite SLO

### PR DESCRIPTION
**Pull request by arpit-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45302)

### CODE REVIEW

**Review by Varsha-lalwani — APPROVED** [review]
> Reviewed 19 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45302)* status: :shipit: complete! ✓

**Comment by arpit-harness** [comment]
trigger messagecheck

**Comment by arpit-harness** [comment]
trigger ut3

**Comment by arpit-harness** [comment]
trigger ut9

**Comment by arpit-harness** [comment]
trigger ut3

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45302)* status: Some of the checks are too old. 1 change requests. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/SLOTemplateDataGenerator.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/45302#-NQzUCdxDynPgCU7l-Nn:-NQzUCdxDynPgCU7l-No:b-svloo1) ([raw file](https://github.com/harness/harness-core/blob/02d282055a6b775ba0b1eddee02d9d3d1fb08b50/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/SLOTemplateDataGenerator.java#L66)):*
> ```Java
>         projectParams, name, identifier, serviceIdentifier, monitoredServiceIdentifier, condition, notificationDataMap);
>     templateData.put(MONITORED_SERVICE_URL, getMonitoredServiceUrl(baseUrl, projectParams, monitoredServiceIdentifier));
>     if (templateData.get(SERVICE_NAME) == null) {
> ```

why are we removing the null value? shouldn’t template take care of it?



_Code quote:_
```Java
    if (templateData.get(SERVICE_NAME) == null) {
      templateData.remove(SERVICE_NAME);
    }
```

**Review by deepak-harness — DISMISSED** [review]
> Reviewed 17 of 20 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45302)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45302)* status: :shipit: complete! ✓

**Pull request merged**
