### PR TITLE
feat: [CDS-31042]: Shell Script Timeout

### PR DESCRIPTION
**Pull request by abhinavmittal-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30751)

### CODE REVIEW

**Comment by jennyjames21** [comment]
___
*[400-rest/src/main/java/software/wings/app/DelegateQueueTask.java, line 237 at r1](https://reviewable.io/reviews/harness/harness-core/30751#-MvtcbpA-gE9zmu78Ouk:-MvtcbpB1HiKD-NMR6Ei:brodg0m) ([raw file](https://github.com/harness/harness-core/blob/c93db238dfed89b81dc5dad3f2fa9c932869245d/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L237)):*
> ```Java
>                     .accountId(delegateTasks.get(taskId).getAccountId())
>                     .responseCode(DelegateTaskResponse.ResponseCode.FAILED)
>                     .expired(true)
> ```

why do you need expired both places? can we keep only inside ErrorNotifyResponse?

**Comment by jennyjames21** [comment]
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/DelegateTaskResponse.java, line 25 at r1](https://reviewable.io/reviews/harness/harness-core/30751#-Mvtdoag9m7ydLV14qeb:-Mvtdoag9m7ydLV14qec:b7oyle1) ([raw file](https://github.com/harness/harness-core/blob/c93db238dfed89b81dc5dad3f2fa9c932869245d/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/DelegateTaskResponse.java#L25)):*
> ```Java
>   private DelegateResponseData response;
>   private ResponseCode responseCode;
>   private boolean expired;
> ```

can u include this part of DelegateResponseData?

**Review by jennyjames21 — DISMISSED** [review]
> Reviewed 22 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30751)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30751)* status: :shipit: complete! ✓

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 21 of 26 files at r1, 1 of 2 files at r2, 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30751)* status: :shipit: complete! ✓

**Pull request merged**
