### PR TITLE
[fix]: [PL-27472]: Added KryoWrapper

### PR DESCRIPTION
**Pull request by piyush-harness**
## Describe your changes

Added Serialization, DeSerialization kryo wrapper to always use setReferences to false first. More details are [here](https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21159673970/Kryo+Serialization) 

Testing done:

- First round of testing and verification with Richa on platform-service for notification. Without the fix the KryoException was observed in case where the create task param has "cc" notification attribute which is recently introduced, with the Wrapper we didn’t see Kryo Exceptions and email notification was success. 

- Internally tested the vault on the local and that also working fine with wrapper changes, whereas without the wrapper observed secret creation failure with kryo exceptions.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36443)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36443)

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 2 of 3 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36443)* status: 14 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Comment by piyush-harness** [comment]
:lgtm:

**Review by piyush-harness — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36443)* status: 14 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 12 of 12 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36443#-:-NE9iVMvBCD3iuHq1cJh:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 12 of 12 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36443)* status: Waiting on team(s): sto.

**Pull request merged**
