### PR TITLE
fix: [CDS-46295]: optimise memory intensive calls to mongo

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
## Describe your changes

Continuation of https://github.com/harness/harness-core/pull/39930
Replacing some mongo calls where we fetch all the data in memory and then process it, by directly querying mongo for desired metrics.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40011)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/telemetry/NGTelemetryPublisher.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/40011#-NGgawLj5moM5a_TowB7:-NGgawLk4nKOt9hCT3Fr:b-cv0omw) ([raw file](https://github.com/harness/harness-core/blob/d122475d09a73e52119b76742113f922eebba19d/120-ng-manager/src/main/java/io/harness/telemetry/NGTelemetryPublisher.java#L50)):*
> ```Java
>         long totalNumberOfServiceInstancesInAMonth =
>             cdPipelineInstrumentationHelper.getCountOfServiceInstancesDeployedInInterval(
>                 accountId, currentTimeMillis - MILLISECONDS_IN_A_MONTH, currentTimeMillis);
> ```

nit: we can compute this difference just once instead of doing this in every method call

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40011)* status: :shipit: complete! ✓

**Comment by abhinavsingh1196** [comment]
trigger SmartPRChecks-fn_pr_ck

**Comment by abhinavsingh1196** [comment]
trigger SmartPRChecks-MessageCheck

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40011)* status: Some of the checks are too old.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40011)* status: :shipit: complete! ✓

**Pull request merged**
