### PR TITLE
feat: [PIE-7776]: Disable delegate selectors for git batch file fetch task

### PR DESCRIPTION
**Pull request by mohitg0795**
## Describe your changes
https://harness.slack.com/archives/C0399D8B6AX/p1674123149247209?thread_ts=1672915297.771419&cid=C0399D8B6AX

- We won't respect delegate selectors of the different scm connectors in the get batch file task
- We would try and find best combination of scope of delegates that are eligible for picking up the task. eg: If all files are org scoped or project scoped, then best combination of eligible delegates will be to allow any of the org level delegates to pick up the task.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43251)

### CODE REVIEW

**Review by archit-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43251)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1140 at r1](https://reviewable.io/reviews/harness/harness-core/43251#-NN5Ai3e7cv4WAG1kcHX:-NN5Ai3e7cv4WAG1kcHY:bayy1i) ([raw file](https://github.com/harness/harness-core/blob/ad6b30498d5d71e5ebb027809a7abd43522de54e/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1140)):*
> ```Java
>   }
> 
>   // Decides what all scope of delegates are eligible to pick up this task
> ```

nit: can we document as mentioned in slack why we are doing scoping and what scoping is that

**Review by adivishy1 — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43251)* status: :shipit: complete! ✓

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1140 at r1](https://reviewable.io/reviews/harness/harness-core/43251#-NN5Ai3e7cv4WAG1kcHX:-NN6GLkf6GipX3dKy-Ea:bboe4sg) ([raw file](https://github.com/harness/harness-core/blob/ad6b30498d5d71e5ebb027809a7abd43522de54e/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1140)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: can we document as mentioned in slack why we are doing scoping and what scoping is that
</blockquote></details>

Yes, it all will be documented on Harness docs itself as its something important for our customers also to understand.

**Review by vcalasansh — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43251)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by vcalasansh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43251)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43251)* status: 1. unresolved discussions.

**Pull request merged**
