### PR TITLE
fix: [DEL-6136]: remove software.wings.beans.infrastructure.Host from delegate

### PR DESCRIPTION
**Pull request by raghuAtWings**
In an effort to remove mongo dependency in delegate we are doing the following

1. Moved software.wings.beans.infrastructure.Host to 400-rest
2. created a dto with name software.wings.beans.beans.Host in 930-delegate-tasks

**PR Tests Done**
1. end to end k8 deployment in cg
3. end to end k8 deployment in cg

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45312)

### CODE REVIEW

**Review by abosii-harness — APPROVED** [review]
> Reviewed 23 of 24 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45312)* status: Waiting on team(s): del-team.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 23 of 24 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45312)* status: Waiting on team(s): del-team.

**Review by gn-harness — APPROVED** [review]
> Reviewed 23 of 24 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45312)* status: Waiting on team(s): del-team. 

___
*[`957-cg-beans/src/main/java/io/harness/serializer/kryo/CgOrchestrationBeansKryoRegistrar.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/45312#-NQl0FBZCCmLAs1Jl4Fv:-NQl0FBZCCmLAs1Jl4Fw:bzclbet) ([raw file](https://github.com/harness/harness-core/blob/3915455165e7d4086cbd8c2a32a0a8cd4e98af50/957-cg-beans/src/main/java/io/harness/serializer/kryo/CgOrchestrationBeansKryoRegistrar.java#L100)):*
> ```Java
>     kryo.register(CountsByStatuses.class, 4008);
>     kryo.register(AppContainer.class, 5064);
>     kryo.register(Host.class, 5067);
> ```

I think you need to register the DTO version too



_Code quote:_
```Java
 kryo.register(Host.class, 5067);
```

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45312)* status: Some of the checks are too old. 1. unresolved discussions.

**Review by gn-harness — APPROVED** [review]
> Reviewed 5 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45312)* status: 1. unresolved discussions.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45312)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
trigger ut2

**Comment by raghuAtWings** [comment]
trigger ut5

**Pull request closed without merging**
