### PR TITLE
fix: [CDS-47637]: Supporting Expression in the Values Override of Apply Step

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Describe your changes
Issue found that expressions are not resolving when used inside Values Override of Apply Step
Fix: Supporting Expression in the Values Override of Apply Step

### SS before Fix
Screenshot 2022-12-05 at 3 03 00 PM

### SS after Fix
Screenshot 2022-12-05 at 3 27 02 PM

## Test Result:
Locally tested changes are looking good
Unit Test Added

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41040)

### CODE REVIEW

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41040)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 406 at r1](https://reviewable.io/reviews/harness/harness-core/41040#-NIW-eY-08WihffnpGz-:-NIW-eY-08WihffnpGz0:b-g4ciob) ([raw file](https://github.com/harness/harness-core/blob/df93ca24b9caff3eed3c6cd8428ef5383555b67e/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L406)):*
> ```Java
> 
>   public void resolveManifestsConfigExpressions(Ambiance ambiance, List<ManifestConfigWrapper> manifestConfigWrappers) {
>     ExpressionEvaluatorUtils.updateExpressions(
> ```

Let's reduce this to 
List<ManifestConfig> configs = manifestConfigWrappers.stream().map(ManifestConfigWrapper::getManifest).collect(Collectors.toList());
ExpressionEvaluatorUtils.updateExpressions(
            configs, new CDExpressionResolveFunctor(engineExpressionService, ambiance));

As well please add UTs for this

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41040)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/41040#-NIWTDK-9erwAYGuPLIG:-NIWTDK-9erwAYGuPLIH:b-dlc2vo) (no related file):*
@namantalaycha10 can you please update PR description with before/after fix screenshots. Does this change apply only for ApplyStep? Do we need to consider for other k8s steps also?

___

**Comment by namantalaycha10** [comment]
Hi @acasian-harness I updated this PR as you mentioned also I tested the other k8s steps
this issue is not happening in other K8s Steps

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41040)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
