### PR TITLE
feat: [PIE-4973]: Improve code coverage of PipelineEnforcementServiceImpl and PipelineMetadataServiceImpl

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
Coverage
- PipelineMetadataServiceImpl: 9% > +80%
- PipelineEnforcementServiceImpl: 45% > +75%

Code Smells
- PMSPipelineServiceImpl: 14 > 7

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36910)

### CODE REVIEW

**Comment by Fernando-Dourado** [comment]
trigger ft1, ft2

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36910)

**Comment by Fernando-Dourado** [comment]
trigger compile, ft1, ft2, ti1, ti2, tin, codeformat

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36910)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by Fernando-Dourado** [comment]
trigger ti0

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36910)* status: Some of the checks are too old. 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by Fernando-Dourado** [comment]
trigger ti0

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36910)* status: Some of the checks are too old.

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36910)* status: Some of the checks are too old.

**Pull request merged**
