### PR TITLE
feat: [CDS-35305]: Added PDC infra integration with exec step

### PR DESCRIPTION
**Pull request by acasian-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31911)

### CODE REVIEW

**Comment by acasian-harness** [comment]
trigger license/cla, license, cla

**Review by ivan-83 — APPROVED** [review]
> Reviewed 20 of 29 files at r1, 6 of 7 files at r2, 1 of 1 files at r3, 3 of 4 files at r4, 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31911)* status: :shipit: complete! ✓

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java, line 139 at r5](https://reviewable.io/reviews/harness/harness-core/31911#-N-NI5x8DY0cFgebDji6:-N-NI5x8DY0cFgebDji7:b-31cd7n) ([raw file](https://github.com/harness/harness-core/blob/fceecb8e56ac6612bb6d76344353acafd55fd5d6/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L139)):*
> ```Java
> 
> public class CDStepHelper {
>   public static final String MISSING_INFRASTRUCTURE_ERROR = "Infrastructure section is missing or is not configured";
> ```

Minor - Try to move to some constance class.
___
*[127-cd-nextgen-beans/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java, line 65 at r5](https://reviewable.io/reviews/harness/harness-core/31911#-N-NMWpjAteMMZVdyrAZ:-N-NMWpjAteMMZVdyrA_:b-4l7ybg) ([raw file](https://github.com/harness/harness-core/blob/fceecb8e56ac6612bb6d76344353acafd55fd5d6/127-cd-nextgen-beans/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java#L65)):*
> ```Java
>         ConnectorInfoDTO connectorDTO = getConnectorInfoDTO(infrastructure, ngAccess);
>         PdcInfrastructureOutcome pdcDirectInfrastructure = (PdcInfrastructureOutcome) infrastructure;
>         PhysicalDataCenterConnectorDTO pdcConnectorDTO =
> ```

Should we throw error when pdcConnectorDTO or connectorDTO is null? 
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/utils/SshUtils.java, line 41 at r5](https://reviewable.io/reviews/harness/harness-core/31911#-N-NOEt00oKL1MQ-YI2S:-N-NOEt00oKL1MQ-YI2T:b-afjau2) ([raw file](https://github.com/harness/harness-core/blob/fceecb8e56ac6612bb6d76344353acafd55fd5d6/930-delegate-tasks/src/main/java/io/harness/delegate/utils/SshUtils.java#L41)):*
> ```Java
>     sshSessionConfig.setAccountId(taskParameters.getAccountId());
>     sshSessionConfig.setExecutionId(taskParameters.getExecutionId());
>     sshSessionConfig.setHost(taskParameters.getSshInfraDelegateConfig().getHosts().get(0));
> ```

Should we iterate over other hosts and create more SshSessionConfig/s?

**Review by acasian-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31911)* status: 3. unresolved discussions. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java, line 139 at r5](https://reviewable.io/reviews/harness/harness-core/31911#-N-NI5x8DY0cFgebDji6:-N-NPQMX0Pwl_k_sjeqA:b9q243h) ([raw file](https://github.com/harness/harness-core/blob/fceecb8e56ac6612bb6d76344353acafd55fd5d6/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L139)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - Try to move to some constance class.
</blockquote></details>

i will move that in the upper pr since this is a pr to another pr.
___
*[127-cd-nextgen-beans/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java, line 65 at r5](https://reviewable.io/reviews/harness/harness-core/31911#-N-NMWpjAteMMZVdyrAZ:-N-NP6WC2c9rWsMJWK_d:bciekbr) ([raw file](https://github.com/harness/harness-core/blob/fceecb8e56ac6612bb6d76344353acafd55fd5d6/127-cd-nextgen-beans/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java#L65)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Should we throw error when pdcConnectorDTO or connectorDTO is null? 
</blockquote></details>

no, hosts can be provided along with ssh key without pdc connector. Also, it could be dynamic infra provisioning.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/utils/SshUtils.java, line 41 at r5](https://reviewable.io/reviews/harness/harness-core/31911#-N-NOEt00oKL1MQ-YI2S:-N-NPIBk0t3BpASwWw7h:b4qqtvw) ([raw file](https://github.com/harness/harness-core/blob/fceecb8e56ac6612bb6d76344353acafd55fd5d6/930-delegate-tasks/src/main/java/io/harness/delegate/utils/SshUtils.java#L41)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Should we iterate over other hosts and create more SshSessionConfig/s? 
</blockquote></details>

multi host support will be in place once we have step forking supported by pipeline.

**Review by ivan-83 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31911)* status: :shipit: complete! ✓

**Pull request merged**
