### PR TITLE
[feat]: [PIE-3696]: Add import pipeline YAML API

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32932)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitImportInfoDTO.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/32932#-N1eJfmA1Jm3OJptHgB8:-N1eJfmF6rUpI8nQuLS4:bbo3wad) ([raw file](https://github.com/harness/harness-core/blob/7b244baa150df388f08519fed928f4141f86e92f/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitImportInfoDTO.java#L30)):*
> ```Java
>   @Parameter(description = GitSyncApiConstants.REPO_NAME_PARAM_MESSAGE)
>   @QueryParam(GitSyncApiConstants.REPO_NAME)
>   String yamlGitConfigId;
> ```

wrong param

**Review by mohitg0795 — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32932)* status: 7 file(s) to review. 0 of 2 approvals obtained.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32932)* status: 7 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitImportInfoDTO.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/32932#-N1eJfmA1Jm3OJptHgB8:-N1g2f0U0n_w_cMZonin:bclcs3w) ([raw file](https://github.com/harness/harness-core/blob/7b244baa150df388f08519fed928f4141f86e92f/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitImportInfoDTO.java#L30)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

wrong param
</blockquote></details>

repoName is wrong? What should it be instead?

**Comment by namanvermah** [comment]
trigger codebasehash, compile

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitImportInfoDTO.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/32932#-N1eJfmA1Jm3OJptHgB8:-N1grLV86xz8UpXuT-xv:b-s7zo7i) ([raw file](https://github.com/harness/harness-core/blob/7b244baa150df388f08519fed928f4141f86e92f/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitImportInfoDTO.java#L30)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

repoName is wrong? What should it be instead?
</blockquote></details>

I meant to point "yamlGitConfigId". It should be repoName.

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitImportInfoDTO.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/32932#-N1eJfmA1Jm3OJptHgB8:-N1grRQE03oRpl7qDjvo:br0htmg) ([raw file](https://github.com/harness/harness-core/blob/7b244baa150df388f08519fed928f4141f86e92f/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitImportInfoDTO.java#L30)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I meant to point "yamlGitConfigId". It should be repoName.
</blockquote></details>

Cool, I see its fixed.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32932#-:-N1grVop5eL_hJBiwTqG:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32932)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
The code base hash has changed because of GitEntityInfo, which has no link to any delegate task, hence this change is backwards compatible.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32932#-:-N1h93bU9_DOCCPzvhgf:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32932)* status: :shipit: complete! ✓

**Review by arpit3107 — APPROVED** [review]
Approving, though I wonder why the codebase hash changed for this pr.

> Reviewed 4 of 5 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32932#-:-N1h9cmvAXfMnmZJFffi:b-311r8a)* status: :shipit: complete! ✓

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32932#-:-N1hFFW38h_d29EuWGKd:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
