### PR TITLE
[Feat]: [PL-29789]: Updates delegate response flow to use reference false kryo serializer

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes

Summary:

Kryo using CompatibleFieldSerializer along with references set to true does not behave correctly. There are some backward compatibility issues faced for below scenarios

- A new field is introduced or exiting field is updated which refers another field.
- New field is not present in Manager/Delegate code.
- During deserialisation you will get incorrect data or IndexOutOfBound in some deep nested object cases.

Delegate to manager communication already started using kryo with reference false. 

This PR is continuation of migrating from kryo reference true to falase. This upgrades all microservices which consumes delegate response to conditionally handle the logic of usingKryoWithReference OR usingKryoWithoutReference .

Test case tested locally

- Async Notification Delegate task
- Sync Notification Delegate task

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40590)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger feature-build

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 142 at r2](https://reviewable.io/reviews/harness/harness-core/40590#-NHwzgICErpohXdufpVo:-NHwzgIHE3zRMmbA3rbx:baamuhy) ([raw file](https://github.com/harness/harness-core/blob/4831faecba8d3589e8007193d60ac67bf99fa500/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L142)):*
> ```Java
>         }
>         log.info("Response received for task: {} from Delegate: {}", taskId, delegateId);
>         if (response.isUsingKryoWithoutReference()) {
> ```

why do we need this? wouldn't delegate always send the response with referenceFalse? also at this time the object is deserialized already, so the logic of this should be only present at the time of sending it over the wire.

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 280 at r2](https://reviewable.io/reviews/harness/harness-core/40590#-NHx-e_-6oVwLhGL0Vqi:-NHx-e_-6oVwLhGL0Vqj:b-hjz2cb) ([raw file](https://github.com/harness/harness-core/blob/4831faecba8d3589e8007193d60ac67bf99fa500/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L280)):*
> ```Java
>         return;
>       }
>       boolean async = delegateTask.getTaskDataV2() != null ? delegateTask.getTaskDataV2().isAsync()
> ```

shouldn't we make this change to send the response using the referenceFalse only when all consuming microservices have been upgraded to handle the logic of usingKryoWithoutReference?

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/intfc/DelegateCallbackService.java` line 11 at r2](https://reviewable.io/reviews/harness/harness-core/40590#-NHx02A65IBqFJP0D0kV:-NHx02A65IBqFJP0D0kW:bi7tcu0) ([raw file](https://github.com/harness/harness-core/blob/4831faecba8d3589e8007193d60ac67bf99fa500/420-delegate-service/src/main/java/io/harness/service/intfc/DelegateCallbackService.java#L11)):*
> ```Java
> 
> public interface DelegateCallbackService {
>   void publishSyncTaskResponse(String delegateTaskId, byte[] responseData, boolean usingKryoWithoutReference);
> ```

do we need these api changes? shouldn't we just add usingKryoWithoutReference to be true in the document that we write once consuming microservices have been upgraded?

**Comment by raghuAtWings** [comment]
*[`910-delegate-service-driver/src/main/java/io/harness/service/impl/DelegateAsyncServiceImpl.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/40590#-NHx0SaT9yQRqkgF6ocb:-NHx0SaT9yQRqkgF6occ:bd0l6rl) ([raw file](https://github.com/harness/harness-core/blob/4831faecba8d3589e8007193d60ac67bf99fa500/910-delegate-service-driver/src/main/java/io/harness/service/impl/DelegateAsyncServiceImpl.java#L108)):*
> ```Java
>           doneWithEndTime = stopwatch.elapsed(TimeUnit.MILLISECONDS);
>         } else {
>           if (lockedAsyncTaskResponse.isUsingKryoWithoutReference()) {
> ```

we do not need if else block here. you could do something like below so the logic is not duplicated, 


ResponseData data = lockedAsyncTaskResponse.isUsingKryoWithoutReference() ? (ResponseData) referenceFalseKryoSerializer.asInflatedObject(lockedAsyncTaskResponse.getResponseData()) : (ResponseData) kryoSerializer.asInflatedObject(lockedAsyncTaskResponse.getResponseData());

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 25 of 30 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40590)* status: 0 of 1 approvals obtained.

**Comment by ashishsanodia-harness** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 142 at r2](https://reviewable.io/reviews/harness/harness-core/40590#-NHwzgICErpohXdufpVo:-NHxf0gj1pxrbObdPJhB:b-wbr4tj) ([raw file](https://github.com/harness/harness-core/blob/4831faecba8d3589e8007193d60ac67bf99fa500/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L142)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need this? wouldn't delegate always send the response with referenceFalse? also at this time the object is deserialized already, so the logic of this should be only present at the time of sending it over the wire. 
</blockquote></details>

Yes, This is just to control enablement of kryFalseSerializer. once all consuming microservices have been upgraded to handle the logic of usingKryoWithoutReference. We will enable response flow to serialize data using kryoReferenceFalse only.

**Comment by ashishsanodia-harness** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/intfc/DelegateCallbackService.java` line 11 at r2](https://reviewable.io/reviews/harness/harness-core/40590#-NHx02A65IBqFJP0D0kV:-NHxgTX_3gP23HUQPONn:byls2tx) ([raw file](https://github.com/harness/harness-core/blob/4831faecba8d3589e8007193d60ac67bf99fa500/420-delegate-service/src/main/java/io/harness/service/intfc/DelegateCallbackService.java#L11)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

do we need these api changes? shouldn't we just add usingKryoWithoutReference to be true in the document that we write once consuming microservices have been upgraded?
</blockquote></details>

This PR contains changes to upgrade all consuming microservices to handle the logic of usingKryoWithoutReference. 
once all consuming microservices have been upgraded to handle the logic of usingKryoWithoutReference. We will enable response flow to serialize data using kryoReferenceFalse only in next PR

**Comment by ashishsanodia-harness** [comment]
*[`910-delegate-service-driver/src/main/java/io/harness/service/impl/DelegateAsyncServiceImpl.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/40590#-NHx0SaT9yQRqkgF6ocb:-NHxghhy1SJOkEd0P_oh:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/4831faecba8d3589e8007193d60ac67bf99fa500/910-delegate-service-driver/src/main/java/io/harness/service/impl/DelegateAsyncServiceImpl.java#L108)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we do not need if else block here. you could do something like below so the logic is not duplicated, 


ResponseData data = lockedAsyncTaskResponse.isUsingKryoWithoutReference() ? (ResponseData) referenceFalseKryoSerializer.asInflatedObject(lockedAsyncTaskResponse.getResponseData()) : (ResponseData) kryoSerializer.asInflatedObject(lockedAsyncTaskResponse.getResponseData());

</blockquote></details>

Done

**Comment by raghuAtWings** [comment]
*[`910-delegate-service-driver/src/main/java/io/harness/service/impl/DelegateAsyncServiceImpl.java` line 113 at r4](https://reviewable.io/reviews/harness/harness-core/40590#-NI0t6Vb0omFrRlRdqcl:-NI0t6Vb0omFrRlRdqcm:brpwe71) ([raw file](https://github.com/harness/harness-core/blob/81eca624b2dd859d9c82e076bb8a6d11e3e3d5bd/910-delegate-service-driver/src/main/java/io/harness/service/impl/DelegateAsyncServiceImpl.java#L113)):*
> ```Java
>           waitNotifyEngine.doneWith(lockedAsyncTaskResponse.getUuid(), responseData);
>         } else {
>           waitNotifyEngine.doneWithV2(lockedAsyncTaskResponse.getUuid(), responseData);
> ```

we don't need this.

**Comment by ashishsanodia-harness** [comment]
*[`910-delegate-service-driver/src/main/java/io/harness/service/impl/DelegateAsyncServiceImpl.java` line 113 at r4](https://reviewable.io/reviews/harness/harness-core/40590#-NI0t6Vb0omFrRlRdqcl:-NICjvbwDeUhHF_07Cqm:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/81eca624b2dd859d9c82e076bb8a6d11e3e3d5bd/910-delegate-service-driver/src/main/java/io/harness/service/impl/DelegateAsyncServiceImpl.java#L113)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we don't need this. 
</blockquote></details>

Fixed

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 4 files at r4, 25 of 25 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40590)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 11 of 30 files at r1, 2 of 4 files at r4, 25 of 25 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40590)* status: :shipit: complete! ✓

**Pull request merged**
