### PR TITLE
[feat]: [CCM-7536]: Integration of Filter-Panel DTO with APIs

### PR DESCRIPTION
**Pull request by abhijeet-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33329)

### CODE REVIEW

**Review by svmav — COMMENTED** [review]
> Reviewed 11 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33329)* status: Some of the checks are too old. 9 file(s) to review. 0 of 1 approvals obtained.

**Comment by abhijeet-harness** [comment]
trigger codeformat

**Comment by abhijeet-harness** [comment]
trigger ti2

**Comment by abhijeet-harness** [comment]
trigger ti4

**Pull request merged**
