### PR TITLE
fix: [PL-31586]: Added migration for ng secrets for prod3 from local to gcp_kms

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
We are going to introduce gcp_kms as default SM in ng in prod3. So we have migration which should run before this to move all the local Sm to gcp_kms. Once that is done, we will have to move all the secrets that are locally encrypted till now to the new GCP_KMS Sm's.
This migration handles this movement of secrets from local to gcp_kms. We made this migration behind a FF.

Testing:
1. Tested the secrets migration locally by creating a gcp_kms and making it as default and then turning this iterator on and verfied the migation of those secrets.
2. Tested the same in pr-env as well. Verified the iterator working based on FF.

TestSteps:
1. created a secret file (gcpKms creds). This is locally encrypted.
2 . Created gcpKms sm using this file. Did a testConnection and also created a new secret with this SM to store vault root token.
4. Now ran the migration. Now the secretfile is turned into gcpKms encryption.
5. Did a testConnection for the Gcp-kms sm. It is success. Created a vault using the created secret (in step2). Validated the vault connection. It is also success.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44493)

### CODE REVIEW

**Comment by VikasMaddukuriHarness** [comment]
trigger ut3

**Comment by VikasMaddukuriHarness** [comment]
trigger ut3

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44493)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/NgLocalToGlobalSecretsMigrationJob.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/44493#-NPRNhK9Ex4SiPyqR_oz:-NPRNhKA35MzyXQXtXLk:bxw916i) ([raw file](https://github.com/harness/harness-core/blob/68b985017f6f91d4fbc922bc0c8061355c09cb68/120-ng-manager/src/main/java/io/harness/ng/core/migration/NgLocalToGlobalSecretsMigrationJob.java#L46)):*
> ```Java
>     int delay = random.nextInt(2) + 15;
>     ngLocalToGlobalSecretsMigrationFuture =
>         executorService.scheduleWithFixedDelay(ngLocalToGlobalSecretsMigrationService, delay, 120, TimeUnit.MINUTES);
> ```

Any reason to keep it 2 hours?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/NgLocalToGlobalSecretsMigrationService.java` line 155 at r2](https://reviewable.io/reviews/harness/harness-core/44493#-NPRQbQo4DlzMl7GLNiR:-NPRQbQo4DlzMl7GLNiS:b4uybnp) ([raw file](https://github.com/harness/harness-core/blob/68b985017f6f91d4fbc922bc0c8061355c09cb68/120-ng-manager/src/main/java/io/harness/ng/core/migration/NgLocalToGlobalSecretsMigrationService.java#L155)):*
> ```Java
>               .name(ngEncryptedData.getName())
>               .type(SecretType.SecretFile)
>               .spec(SecretFileSpecDTO.builder().secretManagerIdentifier("harnessSecretManager").build())
> ```

We can use HARNESS_SECRET_MANAGER_IDENTIFIER

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44493)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 126 at r3](https://reviewable.io/reviews/harness/harness-core/44493#-NPRR6XODhFtvqZ1D981:-NPRR6XODhFtvqZ1D982:b-13025t) ([raw file](https://github.com/harness/harness-core/blob/303755f57c55231e0262a17a105bd4475909865a/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L126)):*
> ```Java
>   private final AdditionalMetadataValidationHelper additionalMetadataValidationHelper;
>   private final DynamicSecretReferenceHelper dynamicSecretReferenceHelper;
>   private static final long encryptedFileLimit = 10L * 1024 * 1024 /*10 MB */;
> ```

What is its use?

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44493)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/NgLocalToGlobalSecretsMigrationService.java` line 155 at r2](https://reviewable.io/reviews/harness/harness-core/44493#-NPRQbQo4DlzMl7GLNiR:-NPRXXj_Aouuqmx39NdK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/68b985017f6f91d4fbc922bc0c8061355c09cb68/120-ng-manager/src/main/java/io/harness/ng/core/migration/NgLocalToGlobalSecretsMigrationService.java#L155)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We can use HARNESS_SECRET_MANAGER_IDENTIFIER
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 126 at r3](https://reviewable.io/reviews/harness/harness-core/44493#-NPRR6XODhFtvqZ1D981:-NPRXYeu9T8k2gdsb8u-:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/303755f57c55231e0262a17a105bd4475909865a/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L126)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

What is its use?
</blockquote></details>

Removed

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44493)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/NgLocalToGlobalSecretsMigrationJob.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/44493#-NPRNhK9Ex4SiPyqR_oz:-NPRX_3M8dsA1zqCfxoE:btgqe2h) ([raw file](https://github.com/harness/harness-core/blob/68b985017f6f91d4fbc922bc0c8061355c09cb68/120-ng-manager/src/main/java/io/harness/ng/core/migration/NgLocalToGlobalSecretsMigrationJob.java#L46)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Any reason to keep it 2 hours?
</blockquote></details>

made it 12 hrs

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44493#-:-NPRxMwGD1EG3ayL69k-:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44493#-:-NPRxag66mIqHpKQMT8A:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44493)* status: :shipit: complete! ✓

**Pull request merged**
