### PR TITLE
fix: [CDS-73424]: Fixed new line issue with base64encode functor in Jexl expressions

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
## Describe your changes
The issue is with new line characters while encoding config files with `ngBase64Manager.encode("decoded content with\nnew line")` This is fixed with replace new line chars with unicode.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49999)

### CODE REVIEW

**Review by rohitk-h — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49999)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
*[`980-commons/src/main/java/io/harness/expression/ExpressionEvaluator.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/49999#-NZKXA1Q3verPaz56Nqt:-NZKXA1Q3verPaz56Nqu:b-i5n6yc) ([raw file](https://github.com/harness/harness-core/blob/8530a73f1f9c131c982dd5f8169c9928d0000908/980-commons/src/main/java/io/harness/expression/ExpressionEvaluator.java#L92)):*
> ```Java
>     if (expression.contains("\n")) {
>       expression = expression.replaceAll("\n", "\\\\u000a");
>     }
> ```

this affect both CG and NG ?

**Comment by arvind-choudhary-h** [comment]
*[`980-commons/src/main/java/io/harness/expression/ExpressionEvaluator.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/49999#-NZKXA1Q3verPaz56Nqt:-NZRyVQyDguSn4OgorFW:bb77ufg) ([raw file](https://github.com/harness/harness-core/blob/8530a73f1f9c131c982dd5f8169c9928d0000908/980-commons/src/main/java/io/harness/expression/ExpressionEvaluator.java#L92)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this affect both CG and NG ?
</blockquote></details>

Yes.

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49999)* status: Some of the checks are too old. 1. unresolved discussions. 

___
*[`980-commons/src/main/java/io/harness/expression/ExpressionEvaluator.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/49999#-NZKXA1Q3verPaz56Nqt:-NZUIdcYCNZor-mnCT81:b-4xduka) ([raw file](https://github.com/harness/harness-core/blob/8530a73f1f9c131c982dd5f8169c9928d0000908/980-commons/src/main/java/io/harness/expression/ExpressionEvaluator.java#L92)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

we should not make such change in expression evaluator

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49999)* status: Some of the checks are too old. 1. unresolved discussions. 

___
*[`980-commons/src/main/java/io/harness/expression/ExpressionEvaluator.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/49999#-NZKXA1Q3verPaz56Nqt:-NZViIrJ1TGTh1f2weWo:b-y1g5r3) ([raw file](https://github.com/harness/harness-core/blob/8530a73f1f9c131c982dd5f8169c9928d0000908/980-commons/src/main/java/io/harness/expression/ExpressionEvaluator.java#L92)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should not make such change in expression evaluator
</blockquote></details>

@hextechpal the change is in CG evaluator, according to StackOverflow seems fine, can you also review once

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by yogesh-chauhan** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Pull request merged**
