### PR TITLE
[feat]: [PL-25184]: Upgrade scm version

### PR DESCRIPTION
**Pull request by DeepakPatankar**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33448)

### CODE REVIEW

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33448#-:-N2m6hFU9FA9gEB3B0jY:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33448)* status: 1 file(s) to review.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33448)* status: :shipit: complete! ✓

**Pull request merged**
