### PR TITLE
[feat]: [CDS-41433]: Add Rollback step for Azure ARM NG

### PR DESCRIPTION
**Pull request by nassergonzalez**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 14 Issues 
* Code issue 10 Code issues 
* Anti-pattern 4 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37382)

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 16 files at r1, 11 of 13 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java` line 114 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBqTe_b1-bnTHn8O_d_:-NBqTe_b1-bnTHn8O_da:b-sadjsh) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java#L114)):*
> ```Java
>     log.info("Starting execution for the Azure Rollback Step");
>     if (azureARMRollbackStepParameters.getProvisionerIdentifier() == null) {
>       return obtainSkipRollbackTask("Provisioner ID can't be null");
> ```

this should result to a failure, provisioner identifier is mandatory
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java` line 120 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBqU947-8QzbXtLz38W:-NBqU947-8QzbXtLz38X:b5jtl7w) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java#L120)):*
> ```Java
>     AzureARMValidator validator = validateIfRollbackCanBePerformed(templateDataOutput);
>     if (!validator.isValid()) {
>       return obtainSkipRollbackTask(validator.getErrorMsg());
> ```

If config is not valid or rollback is not supported, doesn't it make sense to fail rollback?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java` line 126 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBqUa70DsTCm-Nv1LWs:-NBqUa70DsTCm-Nv1LWt:bbsbm74) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java#L126)):*
> ```Java
>     ConnectorInfoDTO connectorDTO = cdStepHelper.getConnector(azureARMConfig.getConnectorRef(), ambiance);
>     if (!(connectorDTO.getConnectorConfig() instanceof AzureConnectorDTO)) {
>       throw new InvalidRequestException("Invalid connector selected in Azure step. Select Azure connector");
> ```

nit: would be helpful to give connector id in error message
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java` line 150 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBqdRulCA2QkXrFflWZ:-NBqdRulCA2QkXrFflW_:b7lw4ae) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java#L150)):*
> ```Java
>     String provisionerID =
>         getParameterFieldValue(((AzureARMRollbackStepParameters) stepParameters.getSpec()).getProvisionerIdentifier());
>     azureARMConfigDAL.clearStoredAzureARMConfig(ambiance, provisionerID);
> ```

shouldn't clean up be done even if task failed?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 254 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBqsWVF3rax-2r1zjXz:-NBqsWVI-7lo8Sk0VrB4:bpdjxmz) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L254)):*
> ```Java
>     } catch (IOException exception) {
>       log.warn("Exception while parsing ARM outputs", exception);
>       return new LinkedHashMap<>();
> ```

if output is invalid shouldn't we throw an exception? It will block customer if something goes wrong, but I believe if customer will expect outputs to be there and we can't parse it can lead to more frustrations to try to understand what went wrong
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java` line 267 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBqsn1vAYj-Htkov98B:-NBqsn1vAYj-Htkov98C:b-khqpou) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java#L267)):*
> ```Java
>       // need to rollback in the next step if this step failed
>       AzureARMConfig azureARMConfig = getAzureARMConfig(ambiance, stepParameters);
>       azureARMConfigDAL.saveAzureARMConfig(azureARMConfig);
> ```

If we don't care about if step is successful or not, then shouldn't we store it before executing Azure ARM task, this will handle case with timeout

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: 3 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java` line 114 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBqTe_b1-bnTHn8O_d_:-NBr1x9w53rXT6GBfAhm:bn0u1we) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java#L114)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

I think that we are covered by the @NonNull annotation in the StepConfiguration but I changed this part of the code to also throw an exception if the provisionerID is null
</blockquote></details>

then we don't need to validate it twice
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java` line 115 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBr-gBq6eSvOCnvDxwD:-NBr-gBq6eSvOCnvDxwE:bvsqho6) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java#L115)):*
> ```Java
>     if (azureARMRollbackStepParameters.getProvisionerIdentifier() == null) {
>       return obtainSkipRollbackTask("Provisioner ID can't be null");
>     }
> ```

please add empty lines between methods
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStepInfo.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBr2hqb-7I6_mvHq5qT:-NBr2hqb-7I6_mvHq5qU:b3zs9bt) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStepInfo.java#L66)):*
> ```Java
> 
>   void validateSpecParameters() {
>     Validator.notNullCheck("The provisioner Identifier can't be empty", provisionerIdentifier);
> ```

@NotNull should do the validation, If it is not enough we shouldn't validate for null the ParameterField<String> object  but validate it's value for null or empty.



_Code quote:_
```Java
@NotNull
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStepParameters.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBr3Ygs9TKyPrnbGcin:-NBr3Ygs9TKyPrnbGcio:belrama) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStepParameters.java#L34)):*
> ```Java
> @RecasterAlias("io.harness.cdng.provision.azure.AzureARMRollbackStepParameters")
> public class AzureARMRollbackStepParameters extends AzureARMRollbackBaseStepInfo implements SpecParameters {
>   @NotNull @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) ParameterField<String> provisionerIdentifier;
> ```

For Create ARM resource provisionerIdentifier is in AzureCreateARMResourceStepBaseStepInfo and inherited by stepInfo and step parameters class. Shouldn't we have a similar approach here/

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 16 files at r1, 11 of 13 files at r2, 2 of 7 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: 1 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java` line 119 at r4](https://reviewable.io/reviews/harness/harness-core/37382#-NBrF5SB58K9Urx11MNE:-NBrF5SB58K9Urx11MNF:b-75iz5f) ([raw file](https://github.com/harness/harness-core/blob/aa802e2a1c8934c72c30a9ae44d52ec29089742e/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java#L119)):*
> ```Java
>     String provisionerID = getParameterFieldValue(azureARMRollbackStepParameters.getProvisionerIdentifier());
>     AzureARMTemplateDataOutput templateDataOutput = getAzureARMTemplateDataOutput(provisionerID, ambiance);
>     AzureARMValidator validator = validateIfRollbackCanBePerformed(templateDataOutput);
> ```

Lets get rid of the AzureARMValidator
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java` line 267 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBqsn1vAYj-Htkov98B:-NBrAzyn1WkoLRQHvOmf:b-ou5k4c) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java#L267)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

I may be wrong but the idea of saving it before checking if the step is success or not, is because if it fails, we will need to get the connectorRef for the Rollback Step. Where are you saying to save it? Before we send the AZURE_NG_TASK? Would a timeout also trigger a rollback?
</blockquote></details>

@abosii-harness we will handle the in a separate PR (to fetch and save preDeployment data before executing deployment task)

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 16 files at r1, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: 1 change requests. 5. unresolved discussions.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: 1 change requests. 1. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStepInfo.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/37382#-NBus8u6ADJvzMJScIn7:-NBus8u6ADJvzMJScIn8:b483wch) ([raw file](https://github.com/harness/harness-core/blob/405b111246ff09014b494fdd2c01ed7cf2571c07/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStepInfo.java#L66)):*
> ```Java
> 
>   void validateSpecParameters() {
>     Validator.notNullCheck("The provisioner Identifier can't be empty", provisionerIdentifier);
> ```

nit: I believe this is still valid validation because value can be an expression and can result to null
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java` line 267 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBqsn1vAYj-Htkov98B:-NBr4g1H5e6_qG7ZOGOw:bfdwi5r) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java#L267)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

I may be wrong but the idea of saving it before checking if the step is success or not, is because if it fails, we will need to get the connectorRef for the Rollback Step. Where are you saying to save it? Before we send the AZURE_NG_TASK? Would a timeout also trigger a rollback?
</blockquote></details>

If step fails with timeout then no response from delegate will be sent so you will never store AzureARMConfig. But task was in progress and basically could made some changes in environment so theoretically we should revert them

**Review by tmacari-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: 1 change requests. 1. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java` line 267 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBqsn1vAYj-Htkov98B:-NBuv0nG1S9Pccz8JL4G:b-aijen2) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java#L267)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

If step fails with timeout then no response from delegate will be sent so you will never store AzureARMConfig. But task was in progress and basically could made some changes in environment so theoretically we should revert them 
</blockquote></details>

Yes, we will save rollback data before deployment, is task would timeout, rollback will be triggered and there we use saved data. (that would be implemented in a separate PR)

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStepInfo.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/37382#-NBus8u6ADJvzMJScIn7:-NBuvXHH4k3pD71-gmsi:b-orumjy) ([raw file](https://github.com/harness/harness-core/blob/405b111246ff09014b494fdd2c01ed7cf2571c07/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStepInfo.java#L66)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: I believe this is still valid validation because value can be an expression and can result to null
</blockquote></details>

Good point

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java` line 114 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBqTe_b1-bnTHn8O_d_:-NBrLeey6n6iyLcwaNjw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java#L114)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

then we don't need to validate it twice
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java` line 115 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBr-gBq6eSvOCnvDxwD:-NBrMW9k0YXWdUyQoxu7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java#L115)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

please add empty lines between methods
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java` line 119 at r4](https://reviewable.io/reviews/harness/harness-core/37382#-NBrF5SB58K9Urx11MNE:-NBrMWf9D0aNR2eGwUHp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa802e2a1c8934c72c30a9ae44d52ec29089742e/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStep.java#L119)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Lets get rid of the AzureARMValidator
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStepInfo.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBr2hqb-7I6_mvHq5qT:-NBrMdNX29VikWYhOMKj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStepInfo.java#L66)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

@NotNull should do the validation, If it is not enough we shouldn't validate for null the ParameterField<String> object  but validate it's value for null or empty.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java` line 267 at r3](https://reviewable.io/reviews/harness/harness-core/37382#-NBqsn1vAYj-Htkov98B:-NBv-h158aaEW-s4MQ-M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/55e2e750f1bd2da28fd6e701018bbed835a8a30a/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java#L267)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Yes, we will save rollback data before deployment, is task would timeout, rollback will be triggered and there we use saved data. (that would be implemented in a separate PR)
</blockquote></details>

Done.

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: 1 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStepInfo.java` line 59 at r6](https://reviewable.io/reviews/harness/harness-core/37382#-NBv1kHJBvs6jiXJOAFg:-NBv1kHJBvs6jiXJOAFh:bwntzdo) ([raw file](https://github.com/harness/harness-core/blob/61349cc01963516bbba99a4c6303a047d09238c6/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStepInfo.java#L59)):*
> ```Java
>         .build();
>   }
>   void validateSpecParameters() {
> ```

Please add empty line.
Also we should d null/empty check on provisionerIdentifier value not on ParameterFieldHelper.getParameterFieldValue(provisionerIdentifier) not on provisionerIdentifier itself.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: :shipit: complete! ✓

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: 1 change requests. 1. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStepInfo.java` line 59 at r6](https://reviewable.io/reviews/harness/harness-core/37382#-NBv1kHJBvs6jiXJOAFg:-NBv33LQ8XkVvT35j5kD:blkk2ys) ([raw file](https://github.com/harness/harness-core/blob/61349cc01963516bbba99a4c6303a047d09238c6/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMRollbackStepInfo.java#L59)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Please add empty line.
Also we should d null/empty check on provisionerIdentifier value not on ParameterFieldHelper.getParameterFieldValue(provisionerIdentifier) not on provisionerIdentifier itself.
</blockquote></details>

I don't understand this. We are checking that the provisionerIdentifier parameter is not null

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r7, 1 of 1 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: :shipit: complete! ✓

**Comment by nassergonzalez** [comment]
trigger checkstyle

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: :shipit: complete! ✓

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 1 of 4 files at r7, 1 of 1 files at r8, 5 of 5 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: :shipit: complete! ✓

**Review by hextechpal — APPROVED** [review]
> Reviewed 6 of 16 files at r1, 8 of 13 files at r2, 4 of 7 files at r3, 2 of 3 files at r4, 1 of 5 files at r5, 1 of 4 files at r6, 1 of 4 files at r7, 1 of 1 files at r8, 5 of 5 files at r9, 1 of 1 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37382)* status: :shipit: complete! ✓

**Pull request merged**
