### PR TITLE
feat: [PL-29447]: Added Selective view permissiion on user-group

### PR DESCRIPTION
**Pull request by meenakshi-harness**
## Describe your changes
APIs changed
https://harness.atlassian.net/browse/PL-29447

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41401)

### CODE REVIEW

**Review by reetika04 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41401)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41401)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 314 at r1](https://reviewable.io/reviews/harness/harness-core/41401#-NJK4ir0DGGCJozInSQw:-NJK4ir0DGGCJozInSQx:b-yy30mv) ([raw file](https://github.com/harness/harness-core/blob/4f121281e6cd631e8306f496559c8a093d6a2d04/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L314)):*
> ```Java
>     }
> 
>     Map<EntityScopeInfo, List<UserGroup>> allUserScopesMap =
> ```

change allUserScopesMap to allUserGroupScopesMap
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 330 at r1](https://reviewable.io/reviews/harness/harness-core/41401#-NJK57F57gImbRmdfs0U:-NJK57F57gImbRmdfs0V:b-24ckvl) ([raw file](https://github.com/harness/harness-core/blob/4f121281e6cd631e8306f496559c8a093d6a2d04/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L330)):*
> ```Java
>     AccessCheckResponseDTO accessCheckResponse = accessControlClient.checkForAccessOrThrow(permissionChecks);
> 
>     List<UserGroup> permittedConnectors = new ArrayList<>();
> ```

change permittedConnectors to  permittedUserGroups

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41401)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java` line 523 at r1](https://reviewable.io/reviews/harness/harness-core/41401#-NJKG-FUD3nj2-1Bhicr:-NJKG-FUD3nj2-1Bhics:b-5as37e) ([raw file](https://github.com/harness/harness-core/blob/4f121281e6cd631e8306f496559c8a093d6a2d04/123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java#L523)):*
> ```Java
>                                                                              .projectIdentifier(PROJECT_IDENTIFIER)
>                                                                              .build());
>     List<AccessControlDTO> accessControlDTOS = new ArrayList<>();
> ```

This variable exists at class level as well.



_Code quote:_
```Java
accessControlDTOS
```

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41401)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 314 at r1](https://reviewable.io/reviews/harness/harness-core/41401#-NJK4ir0DGGCJozInSQw:-NJKQqjt-WwCavGXMteX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4f121281e6cd631e8306f496559c8a093d6a2d04/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L314)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

change allUserScopesMap to allUserGroupScopesMap
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 330 at r1](https://reviewable.io/reviews/harness/harness-core/41401#-NJK57F57gImbRmdfs0U:-NJKQr2h5VCKvtxezJ2n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4f121281e6cd631e8306f496559c8a093d6a2d04/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L330)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

change permittedConnectors to  permittedUserGroups
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java` line 523 at r1](https://reviewable.io/reviews/harness/harness-core/41401#-NJKG-FUD3nj2-1Bhicr:-NJKQsUr5wwNwzcn6BaO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4f121281e6cd631e8306f496559c8a093d6a2d04/123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java#L523)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

This variable exists at class level as well.
</blockquote></details>

Done.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41401)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41401)* status: :shipit: complete! ✓

**Pull request merged**
