### PR TITLE
feat: [SRM-10798]: Add toggle event.

### PR DESCRIPTION
**Pull request by naveen-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34273)

### CODE REVIEW

**Comment by naveen-harness** [comment]
trigger messagecheck

**Comment by naveen-harness** [comment]
trigger messagecheck

**Comment by naveen-harness** [comment]
trigger messagecheck

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34273)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/MonitoredServiceListItemDTO.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/34273#-N4bMbpc1MnE0Z93dnVH:-N4bMbpc1MnE0Z93dnVI:b-xijcay) ([raw file](https://github.com/harness/harness-core/blob/5b9041e42d4c6a0580ca747fb80301709ff611cf/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/MonitoredServiceListItemDTO.java#L26)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @Builder
> public class MonitoredServiceListItemDTO implements YamlDTO {
> ```

why did we add YamlDTO here?
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 1147 at r2](https://reviewable.io/reviews/harness/harness-core/34273#-N4bN9t4Bdz8K-e0Euvt:-N4bN9t4Bdz8K-e0Euvu:b-9nk9g3) ([raw file](https://github.com/harness/harness-core/blob/5b9041e42d4c6a0580ca747fb80301709ff611cf/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L1147)):*
> ```Java
>     Preconditions.checkNotNull(monitoredService, "Monitored service with identifier %s does not exists", identifier);
> 
>     MonitoredServiceParams monitoredServiceParams = MonitoredServiceParams.builder()
> ```

please update tests to make sure this is added. 
Also we should populate enabled from other places also. 
enabled is not added for only audit usecase. It is part of the yaml now. It should reflect the state of MonitoredService#enabled flag everywhere.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 1153 at r2](https://reviewable.io/reviews/harness/harness-core/34273#-N4bN0Sc4NKUAy7eGugX:-N4bN0Sc4NKUAy7eGugY:b-wh3h96) ([raw file](https://github.com/harness/harness-core/blob/5b9041e42d4c6a0580ca747fb80301709ff611cf/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L1153)):*
> ```Java
>                                                         .monitoredServiceIdentifier(identifier)
>                                                         .build();
>     MonitoredServiceDTO currentMonitoredServiceDTO = getMonitoredServiceDTO(monitoredServiceParams);
> ```

is this being used? I only see old and new being used 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/outbox/MonitoredServiceOutboxEventHandler.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/34273#-N4bNYhc2tphuP-hMxxI:-N4bNYhd0u_hAn_NPlo7:b-7mfbzf) ([raw file](https://github.com/harness/harness-core/blob/5b9041e42d4c6a0580ca747fb80301709ff611cf/300-cv-nextgen/src/main/java/io/harness/cvng/outbox/MonitoredServiceOutboxEventHandler.java#L105)):*
> ```Java
>                                 .action(Action.UPDATE)
>                                 .module(ModuleType.CV)
>                                 .oldYaml(getYamlString(monitoredServiceToggleEvent.getOldMonitoredServiceYamlDTO()))
> ```

do we have tests for this?

**Review by naveen-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34273)* status: 2 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/MonitoredServiceListItemDTO.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/34273#-N4bMbpc1MnE0Z93dnVH:-N4qtCTDDB3o4LcZzmQA:bybc9lf) ([raw file](https://github.com/harness/harness-core/blob/5b9041e42d4c6a0580ca747fb80301709ff611cf/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/MonitoredServiceListItemDTO.java#L26)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

why did we add YamlDTO here?
</blockquote></details>


Removed.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 1147 at r2](https://reviewable.io/reviews/harness/harness-core/34273#-N4bN9t4Bdz8K-e0Euvt:-N4qtHIA9rr2leK0MKNC:bssdtdt) ([raw file](https://github.com/harness/harness-core/blob/5b9041e42d4c6a0580ca747fb80301709ff611cf/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L1147)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

please update tests to make sure this is added. 
Also we should populate enabled from other places also. 
enabled is not added for only audit usecase. It is part of the yaml now. It should reflect the state of MonitoredService#enabled flag everywhere.
</blockquote></details>

Updated the tests, populated the enabled to other places as well.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 1153 at r2](https://reviewable.io/reviews/harness/harness-core/34273#-N4bN0Sc4NKUAy7eGugX:-N4qtLLp5itdrzy187gn:b-4htota) ([raw file](https://github.com/harness/harness-core/blob/5b9041e42d4c6a0580ca747fb80301709ff611cf/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L1153)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

is this being used? I only see old and new being used 
</blockquote></details>

Yes this is being used. 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/outbox/MonitoredServiceOutboxEventHandler.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/34273#-N4bNYhc2tphuP-hMxxI:-N4qtMhc7e909xsPw4jI:b-nzxwwb) ([raw file](https://github.com/harness/harness-core/blob/5b9041e42d4c6a0580ca747fb80301709ff611cf/300-cv-nextgen/src/main/java/io/harness/cvng/outbox/MonitoredServiceOutboxEventHandler.java#L105)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

do we have tests for this?
</blockquote></details>

Modified the unit-tests.

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34273)* status: :shipit: complete! ✓

___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java` line 887 at r3](https://reviewable.io/reviews/harness/harness-core/34273#-N4yu764AAhWyU2P6l-4:-N4yu764AAhWyU2P6l-5:bzeah2d) ([raw file](https://github.com/harness/harness-core/blob/5740550927fa180a3f5537b51ffac17e0495055d/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java#L887)):*
> ```Java
>     assertThat(monitoredServiceListItemDTO.getEnvironmentRef()).isEqualTo(environmentIdentifier);
>     assertThat(monitoredServiceListItemDTO.getType()).isEqualTo(MonitoredServiceType.APPLICATION);
>     assertThat(monitoredServiceListItemDTO.isHealthMonitoringEnabled()).isTrue();
> ```

nit: you have to add assert for enabled also right? You only changed healthMonitoringEnabled? This is part of list api but we should add few assert for MonitoredServiceDTO also.
You can take care of this in the next PR.

**Pull request merged**
