### PR TITLE
fix: [CDS-53322]: Publishing number of env during filter list envs.

### PR DESCRIPTION
**Pull request by mankrit-singh**
## Describe your changes
Publishing number of env during filter list envs.
This information was not being directly passed by response object, and thus it created a bug on UI side
Publishing info so UI can consume explicitly

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44532)

### CODE REVIEW

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44532)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 332 at r1](https://reviewable.io/reviews/harness/harness-core/44532#-NPREXRZ2VLzm1Gk4APM:-NPREXRZ2VLzm1Gk4APN:b887648) ([raw file](https://github.com/harness/harness-core/blob/b58de0ff79c240a5eb12a77e352b4e550e40b4c7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L332)):*
> ```Java
>     // Apply filters on environments
>     Set<Environment> filteredEnvs = EnvironmentInfraFilterUtils.applyFiltersOnEnvs(allPossibleEnvs, filterYamls);
>     MultiDeploymentSpawnerStepDetailsInfo multiDeploymentSpawnerStepDetailsInfo =
> ```

This is not the right place for publishing it.

- The method processEnvInfraFilter.. is generic and can be called from multiple places. But this logic to publish applies only to the step.
- The publishing of envs needs to happen in both the cases - filters and non-filters. Only then UI can read consistently from the API response.

You can do it in the end of SpawnerStep.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44532)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStepDetailsInfo.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/44532#-NPRFDNG5kj-BzIc_REM:-NPRFDNG5kj-BzIc_REN:b-xpvmvo) ([raw file](https://github.com/harness/harness-core/blob/b58de0ff79c240a5eb12a77e352b4e550e40b4c7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStepDetailsInfo.java#L22)):*
> ```Java
> @RecasterAlias("io.harness.cdng.pipeline.steps.MultiDeploymentSpawnerStepDetailsInfo")
> public class MultiDeploymentSpawnerStepDetailsInfo implements StepDetailsInfo {
>     Integer numberOfEnvironments;
> ```

nit, envCount? (concise)

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44532)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 179 at r3](https://reviewable.io/reviews/harness/harness-core/44532#-NPW8s4S1MWpDBNeKPC6:-NPW8s4T8WdOq42zHDf8:b-qmmllj) ([raw file](https://github.com/harness/harness-core/blob/82c42ae0e804a8f98dfd850d6416d79a1ab86155/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L179)):*
> ```Java
>           MultiDeploymentSpawnerStepDetailsInfo.builder().svcCount(1).envCount(environmentsMapList.size()).build();
>       sdkGraphVisualizationDataService.publishStepDetailInformation(
>           ambiance, multiDeploymentSpawnerStepDetailsInfo, "svcEnvCountEvent", StepCategory.STRATEGY);
> ```

pull this hardcoded out as a static final constant.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44532)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 220 at r3](https://reviewable.io/reviews/harness/harness-core/44532#-NPW9e6R0n0bMRlC-9tx:-NPW9e6R0n0bMRlC-9ty:bn2rhl3) ([raw file](https://github.com/harness/harness-core/blob/82c42ae0e804a8f98dfd850d6416d79a1ab86155/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L220)):*
> ```Java
> 
>     // publish Service and Env count for Stage Graph
>     MultiDeploymentSpawnerStepDetailsInfo multiDeploymentSpawnerStepDetailsInfo =
> ```

nit, we can create a seperate method for publishing these details. Pass it svc, env count and it can take care of the rest.
I see these 3-4 lines being duplicated in multiple places.

**Review by mankrit-singh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44532)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 179 at r3](https://reviewable.io/reviews/harness/harness-core/44532#-NPW8s4S1MWpDBNeKPC6:-NPWgxjo-8DdZzZDJHhr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/82c42ae0e804a8f98dfd850d6416d79a1ab86155/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L179)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

pull this hardcoded out as a static final constant.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 332 at r1](https://reviewable.io/reviews/harness/harness-core/44532#-NPREXRZ2VLzm1Gk4APM:-NPWgzCYAzRVMwVLjy_u:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b58de0ff79c240a5eb12a77e352b4e550e40b4c7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L332)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

This is not the right place for publishing it.

- The method processEnvInfraFilter.. is generic and can be called from multiple places. But this logic to publish applies only to the step.
- The publishing of envs needs to happen in both the cases - filters and non-filters. Only then UI can read consistently from the API response.

You can do it in the end of SpawnerStep.
</blockquote></details>

Done.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 6 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44532)* status: 7 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 89 at r4](https://reviewable.io/reviews/harness/harness-core/44532#-NPWkaoLAQrfV7JTjirN:-NPWkaoLAQrfV7JTjirO:bkdbzkx) ([raw file](https://github.com/harness/harness-core/blob/122741171d22cea11b6c99997c6ca45568e6a050/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L89)):*
> ```Java
>       StepType.newBuilder().setType("multiDeployment").setStepCategory(StepCategory.STRATEGY).build();
> 
>   public static final String SVC_ENV_EVENT = "svcEnvCountEvent";
> ```

nit, the name can just be "SVC_ENV_COUNTS", `event` is not needed in name. This name will also come up in Graph API response.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStepDetailsInfo.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/44532#-NPWk6LZ0gbyMv82l_4V:-NPWk6LZ0gbyMv82l_4W:bkt6jvw) ([raw file](https://github.com/harness/harness-core/blob/122741171d22cea11b6c99997c6ca45568e6a050/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStepDetailsInfo.java#L19)):*
> ```Java
> @Value
> @Builder
> @OwnedBy(HarnessTeam.PIPELINE)
> ```

nit, team should be CD

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 4 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44532)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44532)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 6 files at r2, 1 of 1 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44532)* status: :shipit: complete! ✓

**Pull request merged**
