### PR TITLE
fix: [CDS-35637]: fix indexoutofbounds exception during instance sync in NG

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
Fixed indexoutofbounds exception by passing instance handler based on deployment type (from deploymentInfo or based PTResponse type).

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32513)

### CODE REVIEW

**Review by achyuth-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32513)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32513)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 13 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32513)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 241 at r3](https://reviewable.io/reviews/harness/harness-core/32513#-N0awbUC5KPaSK8ZRALF:-N0awbUC5KPaSK8ZRALG:b-l2d77f) ([raw file](https://github.com/harness/harness-core/blob/bb68cfb5301c37f0ad94d85e19bc3e86ca1c9bcb/120-ng-manager/config.yml#L241)):*
> ```YAML
>   authority: localhost
> 
> shouldConfigureWithPMS: ${SHOULD_CONFIGURE_WITH_PMS:-true}
> ```

is this intentional ?

**Comment by abhinavsingh1196** [comment]
*[`120-ng-manager/config.yml` line 241 at r3](https://reviewable.io/reviews/harness/harness-core/32513#-N0awbUC5KPaSK8ZRALF:-N0b-8TbDnaKdu80Ws_L:bvvgczw) ([raw file](https://github.com/harness/harness-core/blob/bb68cfb5301c37f0ad94d85e19bc3e86ca1c9bcb/120-ng-manager/config.yml#L241)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this intentional ?
</blockquote></details>

unintentional, reverted it :)

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 17 files at r3, 1 of 1 files at r4, 35 of 35 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32513)* status: :shipit: complete! ✓

**Review by achyuth-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32513)* status: :shipit: complete! ✓

**Pull request merged**
