### PR TITLE
techdebt: [PIE-6385]: Added UTs

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Added UTs for coverage

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40380)

### CODE REVIEW

**Review by shalini-agr — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40380)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by senjucanon2** [comment]
trigger ss

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40380)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`979-recaster/src/test/java/io/harness/exceptions/CastedFieldExceptionTest.java` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/40380#-NHSm6FT8TJh3yIO_zaw:-NHSm6FU-OfRKEm8Y9D2:bomu3nj) ([raw file](https://github.com/harness/harness-core/blob/0b2b27d1ba7571d01141ad0dc6f54bce8c8bc91d/979-recaster/src/test/java/io/harness/exceptions/CastedFieldExceptionTest.java#L13)):*
> ```Java
> import org.junit.experimental.categories.Category;
> 
> public class CastedFieldExceptionTest {
> ```

Rather than like this? can we add this test to a flow which can throw this exception, it would do both unit test for both methods, same for below exceptions



_Code quote:_
```Java
CastedFieldExceptionTes
```

**Comment by senjucanon2** [comment]
This PR includes some already merged files and some new ones, closing this and will raise new ones.

**Pull request closed without merging**
