### PR TITLE
fix: [DEL-3593]: Dont start the CCM tailer unless it is immutable delegate

### PR DESCRIPTION
**Pull request by mdmilic**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31703)

### CODE REVIEW

**Review by hitesharinga — DISMISSED** [review]
> Reviewed 6 of 10 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31703)* status: :shipit: complete! ✓

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31703)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java, line 106 at r3](https://reviewable.io/reviews/harness/harness-core/31703#-MyvN3fL2xnf9VZ2d87k:-MyvN3fL2xnf9VZ2d87l:b-sm4s4q) ([raw file](https://github.com/harness/harness-core/blob/b5ef9410f468116f77f1494bbef6e0ce30cde7d9/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java#L106)):*
> ```Java
>       }
>     } else {
>       log.info("Running mutable delegate, not starting CCM event tailer");
> ```

May be add one more line that watcher will take publish these events.



_Code quote:_
```Java
Running mutable delegate, not starting CCM event tailer
```
___
*[970-grpc/src/main/java/io/harness/event/client/impl/tailer/DelegateTailerModule.java, line 35 at r3](https://reviewable.io/reviews/harness/harness-core/31703#-MyvOV7yBeBg082WRtfv:-MyvOV7yBeBg082WRtfw:b-mqnhpo) ([raw file](https://github.com/harness/harness-core/blob/94b13c807148e2d9c4f6a0fcbd4e710a7f889fc8/970-grpc/src/main/java/io/harness/event/client/impl/tailer/DelegateTailerModule.java#L35)):*
> ```Java
>   private final Config config;
> 
>   public DelegateTailerModule(final Config config) {
> ```

Whats the benefit of removing it and using @RequiredArgsConstructor



_Code quote:_
```Java
  public DelegateTailerModule(final Config config) {
    this.config = config;
```

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 6 of 10 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31703)* status: :shipit: complete! ✓

**Comment by mdmilic** [comment]
trigger messagecheck

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31703)* status: :shipit: complete! ✓

___
*[260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java, line 106 at r3](https://reviewable.io/reviews/harness/harness-core/31703#-MyvN3fL2xnf9VZ2d87k:-MyyHEUkE8JgO5guEIrK:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b5ef9410f468116f77f1494bbef6e0ce30cde7d9/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java#L106)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

May be add one more line that watcher will take publish these events.
</blockquote></details>

done
___
*[970-grpc/src/main/java/io/harness/event/client/impl/tailer/DelegateTailerModule.java, line 35 at r3](https://reviewable.io/reviews/harness/harness-core/31703#-MyvOV7yBeBg082WRtfv:-MyyH2bs-NSJQBHZxF75:b-sud3c3) ([raw file](https://github.com/harness/harness-core/blob/94b13c807148e2d9c4f6a0fcbd4e710a7f889fc8/970-grpc/src/main/java/io/harness/event/client/impl/tailer/DelegateTailerModule.java#L35)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

Whats the benefit of removing it and using @RequiredArgsConstructor
</blockquote></details>

It's equivalent code, but reduces boilerplate (using Lombok)

**Comment by mdmilic** [comment]
trigger authorcheck

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 6 of 10 files at r1, 4 of 5 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31703)* status: :shipit: complete! ✓

**Pull request merged**
