### PR TITLE
Feat: [SRM-12517]: Add methods for reset Composite SLO calculation

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39120)

### CODE REVIEW

**Comment by praveensugavanam** [comment]
Please add tests

**Comment by praveensugavanam** [comment]
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/CompositeSLORecordsCleanupSideKickExecutor.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/39120#-NFLXHML0culrhYqIR1m:-NFLXHML0culrhYqIR1n:bez3c2d) ([raw file](https://github.com/harness/harness-core/blob/8320ea9072a401cdae2c783919b6896397622980/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/CompositeSLORecordsCleanupSideKickExecutor.java#L39)):*
> ```Java
>       log.info("Triggering cleanup for Composite SLO Records for sloId {}", compositeSLOId);
>       // (TODO) Figure out if we need to(can do) delete in batches.
>       hPersistence.delete(hPersistence.createQuery(CompositeSLORecord.class)
> ```

this could be an extremely expensive operation depending on how many records are being deleted. We should do the delete in batches of 100 or 500 records at a time.

**Comment by praveensugavanam** [comment]
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/CompositeSLORecordsCleanupSideKickExecutor.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/39120#-NFLXHML0culrhYqIR1m:-NFLXTqw4I8jP5XDDOHV:bjuxs2q) ([raw file](https://github.com/harness/harness-core/blob/8320ea9072a401cdae2c783919b6896397622980/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/CompositeSLORecordsCleanupSideKickExecutor.java#L39)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

this could be an extremely expensive operation depending on how many records are being deleted. We should do the delete in batches of 100 or 500 records at a time. 
</blockquote></details>

You can do a .count() to first get the total number of records to be deleted and the batch the call using HIterator

**Comment by Varsha-lalwani** [comment]
trigger messagecheck, checkstyle

**Comment by Varsha-lalwani** [comment]
trigger checkstyle

**Review by deepak-harness — APPROVED** [review]
> Reviewed 6 of 12 files at r1, 8 of 12 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39120)* status: :shipit: complete! ✓

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 474 at r3](https://reviewable.io/reviews/harness/harness-core/39120#-NGG9ndA2ScHmcuAZ0Mq:-NGG9ndA2ScHmcuAZ0Mr:b-m6fyl) ([raw file](https://github.com/harness/harness-core/blob/1517010a3d7a6c7c325f91f4aa91f3ecd4a71d6d/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L474)):*
> ```Java
> 
>   private boolean isReferencedInCompositeSLO(SimpleServiceLevelObjective simpleServiceLevelObjective) {
>     List<AbstractServiceLevelObjective> compositeServiceLevelObjectives =
> ```

nit: can be moved to the Composite SLO service to fetch all Composite SLO where Simple SLo is referenced.

**Pull request merged**
