### PR TITLE
fix: [PL-22511]: Expose External UserId in GraphQL User create/update/list

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30682)

### CODE REVIEW

**Comment by shashank-harness** [comment]
___
*[380-cg-graphql/src/test/java/software/wings/graphql/datafetcher/user/CreateUserDataFetcherTest.java, line 88 at r3](https://reviewable.io/reviews/harness/harness-core/30682#-MvsSIDN3BPzRlTLG8JC:-MvsSIDN3BPzRlTLG8JD:b2e9g1d) ([raw file](https://github.com/harness/harness-core/blob/06eeab9ae25feaa78768c6ea03195b8cf94e50f6/380-cg-graphql/src/test/java/software/wings/graphql/datafetcher/user/CreateUserDataFetcherTest.java#L88)):*
> ```Java
>       assertThat(user.getExternalUserId()).isEqualTo(savedUser.getExternalUserId());
>     }
>   }
> ```

Add both with and without value



_Code quote (from 400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java):_
```Java
 update(User user) {
```

**Review by prabu-kr — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30682)* status: 14 file(s) to review. 0 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30682)* status: 14 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[380-cg-graphql/src/test/java/software/wings/graphql/datafetcher/user/CreateUserDataFetcherTest.java, line 88 at r3](https://reviewable.io/reviews/harness/harness-core/30682#-MvsSIDN3BPzRlTLG8JC:-MvsVJIJAoTYg_UXJj0f:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/06eeab9ae25feaa78768c6ea03195b8cf94e50f6/380-cg-graphql/src/test/java/software/wings/graphql/datafetcher/user/CreateUserDataFetcherTest.java#L88)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Add both with and without value
</blockquote></details>

Done.
___
*[380-cg-graphql/src/test/java/software/wings/graphql/datafetcher/user/UpdateUserDataFetcherTest.java, line 92 at r3](https://reviewable.io/reviews/harness/harness-core/30682#-MvsSP5m4-4S9GgLLFCs:-MvsVJqpAXSeC4xAobug:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/06eeab9ae25feaa78768c6ea03195b8cf94e50f6/380-cg-graphql/src/test/java/software/wings/graphql/datafetcher/user/UpdateUserDataFetcherTest.java#L92)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Add with and without value
</blockquote></details>

Done.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 8 of 8 files at r1, 4 of 4 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30682)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by prabu-kr — DISMISSED** [review]
> Reviewed 8 of 8 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30682)* status: :shipit: complete! ✓

**Comment by shashank-harness** [comment]
___
*[380-cg-graphql/src/test/java/software/wings/graphql/datafetcher/user/UpdateUserDataFetcherTest.java, line 60 at r5](https://reviewable.io/reviews/harness/harness-core/30682#-Mvse--sA_7anYW6Tfb0:-Mvse--sA_7anYW6Tfb1:bqs00pa) ([raw file](https://github.com/harness/harness-core/blob/212c150d88e850394dddc8d99785c50a830e7297/380-cg-graphql/src/test/java/software/wings/graphql/datafetcher/user/UpdateUserDataFetcherTest.java#L60)):*
> ```Java
>     doReturn(User.Builder.anUser().uuid("userId").name("old name").email("test@harness.io").build())
>         .when(userService)
>         .get("userId");
> ```

Why do we need to add anything to an existing test case here?
Should not it run successfully by itself?

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30682)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[380-cg-graphql/src/test/java/software/wings/graphql/datafetcher/user/UpdateUserDataFetcherTest.java, line 60 at r5](https://reviewable.io/reviews/harness/harness-core/30682#-Mvse--sA_7anYW6Tfb0:-Mvt0x4_D0V3Q-ObO9ef:b-8k5juh) ([raw file](https://github.com/harness/harness-core/blob/212c150d88e850394dddc8d99785c50a830e7297/380-cg-graphql/src/test/java/software/wings/graphql/datafetcher/user/UpdateUserDataFetcherTest.java#L60)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Why do we need to add anything to an existing test case here?
Should not it run successfully by itself?
</blockquote></details>

these three fields should be not null

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 8 of 8 files at r1, 4 of 4 files at r2, 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30682)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30682)* status: :shipit: complete! ✓

**Pull request merged**
