### PR TITLE
fix: [IDP-1152]: Datapoint, datasource, DSL - constants vs json match…

### PR DESCRIPTION
**Pull request by Aashrit-Harness**
…ing UT

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54440)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54440)* status: 7 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/test/java/io/harness/idp/scorecard/common/service/CommonTest.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/54440#-NhCA1RNBlpaKNGsCexo:-NhCA1RNBlpaKNGsCexp:bboecv5) ([raw file](https://github.com/harness/harness-core/blob/92185bc37204eceed09fa3b4ddb1b16781b84814/idp-service/src/test/java/io/harness/idp/scorecard/common/service/CommonTest.java#L48)):*
> ```Java
>       }
>     } catch (IllegalAccessException e) {
>       e.printStackTrace(); // Handle exceptions appropriately
> ```

How about having fail(...) here?



_Code quote:_
```Java
e.printStackTrace();
```
___
*[`idp-service/src/test/java/io/harness/idp/scorecard/common/service/CommonTest.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/54440#-NhC9lBTAVSWtlGSM5d_:-NhC9lBTAVSWtlGSM5da:b-d2wpge) ([raw file](https://github.com/harness/harness-core/blob/92185bc37204eceed09fa3b4ddb1b16781b84814/idp-service/src/test/java/io/harness/idp/scorecard/common/service/CommonTest.java#L78)):*
> ```Java
>       dataSourceObjects = convertJsonToListOfMaps("migrations/scorecard/dataSources.json");
>     } catch (Exception e) {
>       fail("Not able to fetch resources");
> ```

Can the message be specific? Like "Not able to fetch data sources"



_Code quote:_
```Java
Not able to fetch resources
```
___
*[`idp-service/src/test/java/io/harness/idp/scorecard/common/service/CommonTest.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/54440#-NhC9rvx4CHwRTERbqLh:-NhC9rvx4CHwRTERbqLi:b-yq1r0v) ([raw file](https://github.com/harness/harness-core/blob/92185bc37204eceed09fa3b4ddb1b16781b84814/idp-service/src/test/java/io/harness/idp/scorecard/common/service/CommonTest.java#L93)):*
> ```Java
>       dataSourceLocationObjects = convertJsonToListOfMaps("migrations/scorecard/datasourceLocations.json");
>     } catch (Exception e) {
>       fail("Not able to fetch resources");
> ```

Can the message be specific? Like "Not able to fetch data source locations"
___
*[`idp-service/src/test/java/io/harness/idp/scorecard/common/service/CommonTest.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/54440#-NhCCV7_DNFIChlMuxM-:-NhCCV7_DNFIChlMuxM0:b9qj6am) ([raw file](https://github.com/harness/harness-core/blob/92185bc37204eceed09fa3b4ddb1b16781b84814/idp-service/src/test/java/io/harness/idp/scorecard/common/service/CommonTest.java#L114)):*
> ```Java
> 
>     List<String> dataPointConstants = fetchConstants(DataPoints.class);
>     List<String> dataPoints = new ArrayList<>();
> ```

Wondering if HashSet would be better... contains() would be faster



_Code quote:_
```Java
    List<String> dataPointConstants = fetchConstants(DataPoints.class);
    List<String> dataPoints = new ArrayList<>();
```

**Review by Aashrit-Harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54440)* status: 7 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/test/java/io/harness/idp/scorecard/common/service/CommonTest.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/54440#-NhCA1RNBlpaKNGsCexo:-NhPt7BUDiX8mVw_PXPC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/92185bc37204eceed09fa3b4ddb1b16781b84814/idp-service/src/test/java/io/harness/idp/scorecard/common/service/CommonTest.java#L48)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

How about having fail(...) here?
</blockquote></details>

Done.
___
*[`idp-service/src/test/java/io/harness/idp/scorecard/common/service/CommonTest.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/54440#-NhC9lBTAVSWtlGSM5d_:-NhPt60j0BM0nZSzcGSg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/92185bc37204eceed09fa3b4ddb1b16781b84814/idp-service/src/test/java/io/harness/idp/scorecard/common/service/CommonTest.java#L78)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can the message be specific? Like "Not able to fetch data sources"
</blockquote></details>

Done.
___
*[`idp-service/src/test/java/io/harness/idp/scorecard/common/service/CommonTest.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/54440#-NhC9rvx4CHwRTERbqLh:-NhPt4D653KYfisDQg2F:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/92185bc37204eceed09fa3b4ddb1b16781b84814/idp-service/src/test/java/io/harness/idp/scorecard/common/service/CommonTest.java#L93)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can the message be specific? Like "Not able to fetch data source locations"
</blockquote></details>

Done.
___
*[`idp-service/src/test/java/io/harness/idp/scorecard/common/service/CommonTest.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/54440#-NhCCV7_DNFIChlMuxM-:-NhPt2yhEXzKDRhJbYxX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/92185bc37204eceed09fa3b4ddb1b16781b84814/idp-service/src/test/java/io/harness/idp/scorecard/common/service/CommonTest.java#L114)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Wondering if HashSet would be better... contains() would be faster
</blockquote></details>

Done.

**Comment by Aashrit-Harness** [comment]
trigger uts

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54440)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by devesh-harness — APPROVED** [review]

**Comment by Aashrit-Harness** [comment]
trigger review

**Pull request merged**
