### PR TITLE
feat: [PIE-2285]: Making implement sidecars a partial plan creator

### PR DESCRIPTION
**Pull request by prashantsharma04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/29952)

### CODE REVIEW

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 3 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29952)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/bean/yaml/SidecarsListWrapper.java, line 27 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlJ5YY6StWmInLrrH8:-MtlJ5YZBd5-BPICzIRD:bj9k4tk) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/bean/yaml/SidecarsListWrapper.java#L27)):*
> ```Java
> @SimpleVisitorHelper(helperClass = SidecarWrapperArtifactVisitorHelper.class)
> @TypeAlias("sidecarArtifactWrapper")
> public class SidecarsListWrapper implements Visitable {
> ```

try removing visitable, not sure if required here
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/PlanCreatorConstants.java, line 36 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlWOvp5ghtnPex-0sF:-MtlWOvp5ghtnPex-0sG:b-pfkt2v) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/PlanCreatorConstants.java#L36)):*
> ```Java
>   public final String SPEC_IDENTIFIER = "spec";
>   public final String PRIMARY_STEP_PARAMETERS = "primaryStepParameters";
>   public final String SIDECARS_PARAMETERS_MAP = "sideCarsParametersMap";
> ```

add comment for dependencyMetadata constants.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/artifact/SideCarArtifactPlanCreator.java, line 5 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlWmMx6a0VXLqWUymE:-MtlWmMx6a0VXLqWUymF:bnrnsv0) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/artifact/SideCarArtifactPlanCreator.java#L5)):*
> ```Java
>  * Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
>  * that can be found in the licenses directory at the root of this repository, also available at
>  * https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.
> ```

Polyform Sheild
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/artifact/SideCarListPlanCreator.java, line 83 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlN14d86AeR4v9myv_:-MtlN14d86AeR4v9myva:bqedmco) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/artifact/SideCarListPlanCreator.java#L83)):*
> ```Java
>   }
> 
>   public String addDependenciesForIndividualSideCar(YamlField sideCarsYamlField, String identifier,
> ```

nit, rename "identifier" to "sidecaridentifier"
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/artifact/SideCarListPlanCreator.java, line 84 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlN79F93XSgWFz4zy2:-MtlN79F93XSgWFz4zy3:bfeiet5) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/artifact/SideCarListPlanCreator.java#L84)):*
> ```Java
> 
>   public String addDependenciesForIndividualSideCar(YamlField sideCarsYamlField, String identifier,
>       ArtifactStepParameters stepParameters, Map<String, YamlNode> mapIdentifierWithYamlNode,
> ```

rename this to identifierToYamNodeMap
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/artifact/SideCarListPlanCreator.java, line 87 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlNKCvCqwrdeAviuKB:-MtlNKCvCqwrdeAviuKC:b-bnxaqr) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/artifact/SideCarListPlanCreator.java#L87)):*
> ```Java
>       LinkedHashMap<String, PlanCreationResponse> planCreationResponseMap) {
>     YamlField individualSideCar =
>         SideCarsListArtifactsUtility.createIndividualSideCarsArtifactYamlFieldAndSetYamlUpdate(
> ```

rename this, remove yamlupdate
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/utilities/SideCarsListArtifactsUtility.java, line 47 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlORWt7uYvDc57Zh0A:-MtlORWt7uYvDc57Zh0B:b-hf7exf) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/utilities/SideCarsListArtifactsUtility.java#L47)):*
> ```Java
>   }
> 
>   public YamlField createIndividualSideCarsArtifactYamlFieldAndSetYamlUpdate(
> ```

rename method to fetchSidecarYamlField
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/utilities/SideCarsListArtifactsUtility.java, line 48 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlOD9J9MfSrXetMafK:-MtlOD9KBkoupmMN763p:b-5b39ih) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/utilities/SideCarsListArtifactsUtility.java#L48)):*
> ```Java
> 
>   public YamlField createIndividualSideCarsArtifactYamlFieldAndSetYamlUpdate(
>       YamlField sideCarsYamlField, String sideCarIdentifier, Map<String, YamlNode> mapIdentifierWithYamlNode) {
> ```

sidecarIdentifierToYamlNodeMap
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/utilities/SideCarsListArtifactsUtility.java, line 50 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlQWGQ9TBmTSJ_F0pZ:-MtlQWGQ9TBmTSJ_F0p_:b-nohlx9) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/utilities/SideCarsListArtifactsUtility.java#L50)):*
> ```Java
>       YamlField sideCarsYamlField, String sideCarIdentifier, Map<String, YamlNode> mapIdentifierWithYamlNode) {
>     if (mapIdentifierWithYamlNode.containsKey(sideCarIdentifier)) {
>       return new YamlField(mapIdentifierWithYamlNode.get(sideCarIdentifier))
> ```

check if new can be avoided here
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/utilities/SideCarsListArtifactsUtility.java, line 71 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlQIVv4JDUSgOBy4VL:-MtlQIVv4JDUSgOBy4VM:b-fs6kxd) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/utilities/SideCarsListArtifactsUtility.java#L71)):*
> ```Java
>   }
> 
>   private static YamlUpdates.Builder setYamlUpdate(YamlField yamlField, YamlUpdates.Builder yamlUpdates) {
> ```

move this to util

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29952)* status: 16 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/bean/yaml/SidecarsListWrapper.java, line 27 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlJ5YY6StWmInLrrH8:-Mtm5MsrCOey9rX7FrwA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/bean/yaml/SidecarsListWrapper.java#L27)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

try removing visitable, not sure if required here
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/PlanCreatorConstants.java, line 36 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlWOvp5ghtnPex-0sF:-Mtm5clP72hkPUhq3CRj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/PlanCreatorConstants.java#L36)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

add comment for dependencyMetadata constants.
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/artifact/SideCarArtifactPlanCreator.java, line 5 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlWmMx6a0VXLqWUymE:-Mtm5f600Bu8BPgcndd1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/artifact/SideCarArtifactPlanCreator.java#L5)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Polyform Sheild
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/artifact/SideCarListPlanCreator.java, line 84 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlN79F93XSgWFz4zy2:-Mtm5qmG5I0xmb7_SLZi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/artifact/SideCarListPlanCreator.java#L84)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

rename this to identifierToYamNodeMap
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/artifact/SideCarListPlanCreator.java, line 87 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlNKCvCqwrdeAviuKB:-Mtm5rZG-d_L9hpJ53Rg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/artifact/SideCarListPlanCreator.java#L87)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

rename this, remove yamlupdate
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/utilities/SideCarsListArtifactsUtility.java, line 47 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlORWt7uYvDc57Zh0A:-Mtm5uKO1-OcEfi0LkSm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/utilities/SideCarsListArtifactsUtility.java#L47)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

rename method to fetchSidecarYamlField
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/utilities/SideCarsListArtifactsUtility.java, line 48 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlOD9J9MfSrXetMafK:-Mtm5vSG5Sib4r5UcYvU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/utilities/SideCarsListArtifactsUtility.java#L48)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

sidecarIdentifierToYamlNodeMap
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/utilities/SideCarsListArtifactsUtility.java, line 50 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlQWGQ9TBmTSJ_F0pZ:-Mtm5vuG84oNQVpoQ18G:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/utilities/SideCarsListArtifactsUtility.java#L50)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

check if new can be avoided here
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/utilities/SideCarsListArtifactsUtility.java, line 71 at r2](https://reviewable.io/reviews/harness/harness-core/29952#-MtlQIVv4JDUSgOBy4VL:-Mtm5wh0-v7PxX3r6r8J:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e7952017d78a9a28ada09bb2d9cc6e4b9b74245e/125-cd-nextgen/src/main/java/io/harness/cdng/utilities/SideCarsListArtifactsUtility.java#L71)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

move this to util
</blockquote></details>

Done.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29952)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[882-pms-sdk-core/src/main/java/io/harness/pms/utilities/PlanCreatorsUtility.java, line 22 at r4](https://reviewable.io/reviews/harness/harness-core/29952#-MtmBG0pDfCIoj7rffvy:-MtmBG0pDfCIoj7rffvz:b-vvjmlu) ([raw file](https://github.com/harness/harness-core/blob/8acbb77d64e577af06276ee5640567432eae66ad/882-pms-sdk-core/src/main/java/io/harness/pms/utilities/PlanCreatorsUtility.java#L22)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> @UtilityClass
> public class PlanCreatorsUtility {
> ```

there is already a PlanCreatorsUtil

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29952)* status: 17 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[882-pms-sdk-core/src/main/java/io/harness/pms/utilities/PlanCreatorsUtility.java, line 22 at r4](https://reviewable.io/reviews/harness/harness-core/29952#-MtmBG0pDfCIoj7rffvy:-MtmIf-V7WdVMTOY3iNb:b-6xjqhn) ([raw file](https://github.com/harness/harness-core/blob/8acbb77d64e577af06276ee5640567432eae66ad/882-pms-sdk-core/src/main/java/io/harness/pms/utilities/PlanCreatorsUtility.java#L22)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

there is already a PlanCreatorsUtil
</blockquote></details>

Done. Deleted the created utility

**Comment by prashantsharma04** [comment]
trigger ft2

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 14 files at r1, 1 of 1 files at r2, 1 of 9 files at r3, 5 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29952)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 5 of 14 files at r1, 1 of 1 files at r2, 4 of 9 files at r3, 5 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29952#-:-MtqrBey-vk6uFkp33MC:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
