### PR TITLE
[feat]: [PL-22030]: For a full synced git connector store its repo and branch too

### PR DESCRIPTION
**Pull request by DeepakPatankar**
https://harness.atlassian.net/wiki/spaces/~240970147/pages/21024276805/All+connectors+not+synced+to+Github+when+new+branch+option+is+selected+when+enabling+git+exp

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30215)

### CODE REVIEW

**Review by bhavya181 — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30215)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30215)* status: 10 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/YamlGitConfig.java, line 71 at r1](https://reviewable.io/reviews/harness/harness-core/30215#-MuNQc3G7UACjcD1q1zX:-MuNQc3G7UACjcD1q1zY:b-h4ce08) ([raw file](https://github.com/harness/harness-core/blob/f993be386471d2be13e9d9392f9e26df2b90f8fe/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/YamlGitConfig.java#L71)):*
> ```Java
>   @NotEmpty String gitConnectorRef;
>   String gitConnectorsRepo;
>   String gitConnectorsBranch;
> ```

Can we name it bit better? And also add comments over here for its use-case otherwise it would be difficult to comprehend in long run
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 394 at r1](https://reviewable.io/reviews/harness/harness-core/30215#-MuNSvDi0tlRk7lbj14Q:-MuNSvDi0tlRk7lbj14R:b3ib96z) ([raw file](https://github.com/harness/harness-core/blob/f993be386471d2be13e9d9392f9e26df2b90f8fe/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L394)):*
> ```Java
>   public void updateTheConnectorRepoAndBranch(YamlGitConfigDTO yamlGitConfigDTO, String repo, String branch) {
>     yamlGitConfigDTO.setGitConnectorsRepo(repo);
>     yamlGitConfigDTO.setGitConnectorsBranch(branch);
> ```

why are we setting values here? I don't see any usages of yamlGitConfigDTO
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 396 at r1](https://reviewable.io/reviews/harness/harness-core/30215#-MuNTdzB0v7fRmiwTwtZ:-MuNTdzCCRanJqc24FAI:bid4bg1) ([raw file](https://github.com/harness/harness-core/blob/f993be386471d2be13e9d9392f9e26df2b90f8fe/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L396)):*
> ```Java
>     yamlGitConfigDTO.setGitConnectorsBranch(branch);
>     Optional<YamlGitConfig> existingYamlGitConfigDTO =
>         yamlGitConfigRepository.findByAccountIdAndOrgIdentifierAndProjectIdentifierAndIdentifier(
> ```

why do we need a get call here? Why can't we just simply put a update call here?

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30215)* status: 13 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/YamlGitConfig.java, line 71 at r1](https://reviewable.io/reviews/harness/harness-core/30215#-MuNQc3G7UACjcD1q1zX:-MuP8FfGB7k-MqIbIPgj:bhzkj09) ([raw file](https://github.com/harness/harness-core/blob/f993be386471d2be13e9d9392f9e26df2b90f8fe/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/YamlGitConfig.java#L71)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can we name it bit better? And also add comments over here for its use-case otherwise it would be difficult to comprehend in long run
</blockquote></details>

The name looks ok. Added the comment.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 394 at r1](https://reviewable.io/reviews/harness/harness-core/30215#-MuNSvDi0tlRk7lbj14Q:-MuPGBKO4lJ0PqVVAIs7:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/f993be386471d2be13e9d9392f9e26df2b90f8fe/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L394)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why are we setting values here? I don't see any usages of yamlGitConfigDTO
</blockquote></details>

Removed



_Code quote:_
```Java
updateTheConnectorRepoAndBranch
```
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 396 at r1](https://reviewable.io/reviews/harness/harness-core/30215#-MuNTdzB0v7fRmiwTwtZ:-MuPGCGq3KhyAToQB_5K:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f993be386471d2be13e9d9392f9e26df2b90f8fe/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L396)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why do we need a get call here? Why can't we just simply put a update call here?
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 135 at r2](https://reviewable.io/reviews/harness/harness-core/30215#-MuPUKwW6JorkoOERi00:-MuPUKwW6JorkoOERi01:b-h2wrnk) ([raw file](https://github.com/harness/harness-core/blob/f9a5bd015a7b6964104c8fb4f9979d8aef76797f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L135)):*
> ```Java
>   Optional<ConnectorResponseDTO> getConnectorFromDefaultBranchElseFromGitBranch(String accountId, String orgIdentifier,
>       String projectIdentifier, String identifier, String connectorRepo, String connectorBranch) {
>     final Optional<ConnectorResponseDTO> connectorResponseDTO =
> ```

we should replace git entity to ensure it gets connector from default scope

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30215)* status: 13 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 135 at r2](https://reviewable.io/reviews/harness/harness-core/30215#-MuPUKwW6JorkoOERi00:-MuPYkwhAk5vmcbOCNoh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9a5bd015a7b6964104c8fb4f9979d8aef76797f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L135)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should replace git entity to ensure it gets connector from default scope
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 6 of 10 files at r1, 7 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30215)* status: 8 file(s) to review.

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30215)* status: 8 file(s) to review.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30215#-:-MuQ-spZ6v79zDSRrVfw:bnfp4nl)* status: 8 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 5 of 10 files at r1, 6 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30215)* status: :shipit: complete! ✓

**Pull request merged**
