### PR TITLE
fix: [PL-26288]: Prevent privilege escalation on implicit access grant on scopes

### PR DESCRIPTION
**Pull request by gupta-utkarsh**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35672)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35672)* status: Some of the checks are too old. 24 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/35672#-N88AAYP0A4S1BRrfIM1:-N88AAYP0A4S1BRrfIM2:blvrib5) ([raw file](https://github.com/harness/harness-core/blob/f6edbd6a10f554d2300b6dcc0b9c13eddf8f44f1/access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java#L29)):*
> ```Java
> @UtilityClass
> public class ACLUtils {
>   public static ACL buildACL(String permission, Principal principal, RoleAssignmentDBO roleAssignment,
> ```

Can we create implicit acl's in this method itself as we have all the info to create implicit acl's right here. I think it would reduce a lot of code duplication and be more readable.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35672)* status: Some of the checks are too old. 24 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerServiceImpl.java` line 113 at r2](https://reviewable.io/reviews/harness/harness-core/35672#-N8PmVeSBVSvdn9i7mGx:-N8PmVeSBVSvdn9i7mGy:b-dx6d5k) ([raw file](https://github.com/harness/harness-core/blob/f6edbd6a10f554d2300b6dcc0b9c13eddf8f44f1/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerServiceImpl.java#L113)):*
> ```Java
>   public List<ACL> getImplicitACLsForRoleAssignment(RoleAssignmentDBO roleAssignment) {
>     Set<String> principals = new HashSet<>();
>     if (USER_GROUP.equals(roleAssignment.getPrincipalType())) {
> ```

Extract this out into another method, something like getPrincipals(RoleAssignmentDBO roleAssignment).
___
*[`access-control/libs/aggregator/src/test/java/io/harness/aggregator/consumers/ResourceGroupChangeConsumerImplTest.java` line 81 at r2](https://reviewable.io/reviews/harness/harness-core/35672#-N8Pnubm2wWom5FYfB2o:-N8Pnubm2wWom5FYfB2p:blaly78) ([raw file](https://github.com/harness/harness-core/blob/f6edbd6a10f554d2300b6dcc0b9c13eddf8f44f1/access-control/libs/aggregator/src/test/java/io/harness/aggregator/consumers/ResourceGroupChangeConsumerImplTest.java#L81)):*
> ```Java
>     resourceGroupRepository = mock(ResourceGroupRepository.class);
>     ChangeConsumerService changeConsumerService = new ChangeConsumerServiceImpl(
>         roleService, userGroupService, resourceGroupService, scopeService, new HashMap<>());
> ```

Fix the unit tests as they are failing.

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* Code issue 5 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35672)

**Comment by gupta-utkarsh** [comment]
trigger messagecheck

**Review by gupta-utkarsh — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35672#-:-N89GMUm9-6XbAe1f1Wh:bnfp4nl)* status: 28 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/35672#-N88AAYP0A4S1BRrfIM1:-N8wYkIv-2DPTqh2_JME:b-gt81el) ([raw file](https://github.com/harness/harness-core/blob/f6edbd6a10f554d2300b6dcc0b9c13eddf8f44f1/access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java#L29)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we create implicit acl's in this method itself as we have all the info to create implicit acl's right here. I think it would reduce a lot of code duplication and be more readable.
</blockquote></details>

Refactored as discussed.
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerServiceImpl.java` line 113 at r2](https://reviewable.io/reviews/harness/harness-core/35672#-N8PmVeSBVSvdn9i7mGx:-N8wYhNp5c792cHajQ_z:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/f6edbd6a10f554d2300b6dcc0b9c13eddf8f44f1/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerServiceImpl.java#L113)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Extract this out into another method, something like getPrincipals(RoleAssignmentDBO roleAssignment).
</blockquote></details>

Done
___
*[`access-control/libs/aggregator/src/test/java/io/harness/aggregator/consumers/ResourceGroupChangeConsumerImplTest.java` line 81 at r2](https://reviewable.io/reviews/harness/harness-core/35672#-N8Pnubm2wWom5FYfB2o:-N8wYijT63s-Gf0JIfmy:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/f6edbd6a10f554d2300b6dcc0b9c13eddf8f44f1/access-control/libs/aggregator/src/test/java/io/harness/aggregator/consumers/ResourceGroupChangeConsumerImplTest.java#L81)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Fix the unit tests as they are failing. 
</blockquote></details>

Done

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35672)* status: Some of the checks are too old. 28 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerServiceImpl.java` line 83 at r4](https://reviewable.io/reviews/harness/harness-core/35672#-NAcPbSQ67c7yC_ZrX9U:-NAcPbSQ67c7yC_ZrX9V:b32g7ji) ([raw file](https://github.com/harness/harness-core/blob/c2c83de02cbd299a96cdf56b2fcae122786e7232/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerServiceImpl.java#L83)):*
> ```Java
> 
>   @Override
>   public List<ACL> getImplicitACLsForRoleAssignment(RoleAssignmentDBO roleAssignment) {
> ```

Can make this method private and keep only getImplicitACLsForChangeSet as the entry point?

**Review by gupta-utkarsh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35672)* status: 28 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerServiceImpl.java` line 83 at r4](https://reviewable.io/reviews/harness/harness-core/35672#-NAcPbSQ67c7yC_ZrX9U:-NAcz10b-K8DifD0S8tu:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c2c83de02cbd299a96cdf56b2fcae122786e7232/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerServiceImpl.java#L83)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can make this method private and keep only getImplicitACLsForChangeSet as the entry point?
</blockquote></details>

Done

**Comment by gupta-utkarsh** [comment]
trigger ft1

**Review by ankit-harness — APPROVED** [review]
> Reviewed 10 of 24 files at r1, 2 of 6 files at r2, 1 of 8 files at r3, 8 of 8 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35672)* status: 28 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by gupta-utkarsh** [comment]
trigger ti1

**Comment by gupta-utkarsh** [comment]
trigger ti3

**Comment by gupta-utkarsh** [comment]
trigger ti4

**Comment by gupta-utkarsh** [comment]
trigger ft1

**Review by Jimit09Gandhi — COMMENTED** [review]
> Reviewed 10 of 24 files at r1, 2 of 6 files at r2, 2 of 8 files at r3, 8 of 8 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35672)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Pull request merged**
