### PR TITLE
feat: [CDS-85655]: For devspace env use schema from harness schema repo for pipeline/template src

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
For devspace env use schema from harness schema repo for pipeline/template src
we have introduced a config - 
```
useSchemaFromHarnessSchemaRepo: ${USE_SCHEMA_FROM_HARNESS_SCHEMA_REPO:-false}
```
the default value of this config is false, we will need to set it as true for PREQA and Devspaces Env

when this flag is set - we will fetch the schema from Harness schema repo, else we will read it from local schema file

Q. why it is needed ?
A. With PREQA getting deprecated, and devspaces gaining more visibility, when some wanted to test their schema changes, they needed to wait till branch cut to test out this changes, earlier in PREQA env we use to fetch schema directly from harness schema repo, So now we are shifting the same to devspaces and local

If in local someone wants to test the local schema, they will need to disable this config, they can use env variable, based on which we either fetch schema from local schema file or harness schema repo 

Tests Done - 
* Verified individual schema getting reinitialised after 15mins, when this config is set for pipeline and template src for both v0 and v1
* Verified we are using local schema file when this config is set to false for pipeline and template src for both v0 and v1

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56655)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/56655#-NlSJ0Wc4uy3QGrtOM02:-NlSJ0Wc4uy3QGrtOM03:boz05or) ([raw file](https://github.com/harness/harness-core/blob/80f749c225923e5d6df05390070d6b1298e3227c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L80)):*
> ```Java
>     String env = System.getenv("ENV");
>     Boolean useSchemaFromHarnessSchemaRepo = pipelineServiceConfiguration.getUseSchemaFromHarnessSchemaRepo();
>     if (PREQA.equals(env) || useSchemaFromHarnessSchemaRepo) {
> ```

Can we only do `useSchemaFromHarnessSchemaRepo` ? And set the config value `USE_SCHEMA_FROM_HARNESS_SCHEMA_REPO` true for devspace and pre-qa.

And lets keep the default value of `USE_SCHEMA_FROM_HARNESS_SCHEMA_REPO`as false.

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 77 at r2](https://reviewable.io/reviews/harness/harness-core/56655#-NlSXblQ2iKzXvmiwtnp:-NlSXblQ2iKzXvmiwtnq:bevpxl7) ([raw file](https://github.com/harness/harness-core/blob/2faaceb8cc00a02fbe9f46834ebe1362b6c58476/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L77)):*
> ```Java
> 
>   public Boolean useSchemaFromHarnessSchemaRepo() {
>     Boolean useSchemaFromHarnessSchemaRepo = pipelineServiceConfiguration.getUseSchemaFromHarnessSchemaRepo();
> ```

We can directly return this. No need of if condition.



_Code quote:_
```Java
pipelineServiceConfiguration.getUseSchemaFromHarnessSchemaRepo()
```

**Comment by brijeshdhakar** [comment]
*[`template-service/service/src/main/java/io/harness/template/utils/TemplateSchemaFetcher.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/56655#-NlSXst21tAqCTmbh6su:-NlSXst39Ic176cdaQJu:b-qhok1u) ([raw file](https://github.com/harness/harness-core/blob/2faaceb8cc00a02fbe9f46834ebe1362b6c58476/template-service/service/src/main/java/io/harness/template/utils/TemplateSchemaFetcher.java#L44)):*
> ```Java
> 
>   public Boolean useSchemaFromHarnessSchemaRepo() {
>     Boolean useSchemaFromHarnessSchemaRepo = templateServiceConfiguration.getUseSchemaFromHarnessSchemaRepo();
> ```

same as above. We can directly return this.



_Code quote:_
```Java
 templateServiceConfiguration.getUseSchemaFromHarnessSchemaRepo()
```

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 8 of 12 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56655)* status: 12 file(s) to review. 0 of 2 approvals obtained.

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56655)* status: 12 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/56655#-NlSJ0Wc4uy3QGrtOM02:-NlSbNz45LG39ruICiDG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/80f749c225923e5d6df05390070d6b1298e3227c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L80)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Can we only do `useSchemaFromHarnessSchemaRepo` ? And set the config value `USE_SCHEMA_FROM_HARNESS_SCHEMA_REPO` true for devspace and pre-qa.

And lets keep the default value of `USE_SCHEMA_FROM_HARNESS_SCHEMA_REPO`as false.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 77 at r2](https://reviewable.io/reviews/harness/harness-core/56655#-NlSXblQ2iKzXvmiwtnp:-NlSbOO92FW3Tlooy9Lc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2faaceb8cc00a02fbe9f46834ebe1362b6c58476/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L77)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

We can directly return this. No need of if condition.
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/utils/TemplateSchemaFetcher.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/56655#-NlSXst21tAqCTmbh6su:-NlSbPF71Nh-G37ujL-E:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2faaceb8cc00a02fbe9f46834ebe1362b6c58476/template-service/service/src/main/java/io/harness/template/utils/TemplateSchemaFetcher.java#L44)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

same as above. We can directly return this.
</blockquote></details>

Done.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56655)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 7 of 12 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56655)* status: <span>:shipit:</span> complete! ✓

**Comment by utkarshchoubey-harness** [comment]
trigger ut2, ut5, ut6, ut7, ut8, ut9

**Comment by utkarshchoubey-harness** [comment]
trigger ut7

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Pull request merged**
