### PR TITLE
fix: [CDS-54023]: K8s BG/Canary w/ declarative rollback - add suffixes for secrets/configmaps

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
## Describe your changes
**[CG + NG]**
With kubernetes declarative rollback, there is no versioning for configmaps and secrets. This could cause potential conflicts in co-existing objects of a single deployment strategy. 

- K8s BG: "blue" and "green" deployments could end up sharing the same configmap/secret
- K8s Canary: "canary" and actual deployment could end up sharing the same configmap/secret

To fix this:
- K8s BG: add "blue" or "green" suffix to configmaps and secrets (along with updating their refs in workloads)
- K8s Canary: add "canary" suffix to configmaps and secrets. Also, add names of these configmaps and secrets to "canaryWorkload" string, which is used to compute the resources to be deleted during Canary Delete stage.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44431)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44431)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java` line 422 at r1](https://reviewable.io/reviews/harness/harness-core/44431#-NPMUHn10naugOMWwHTl:-NPMUHn10naugOMWwHTm:b-hwrmpp) ([raw file](https://github.com/harness/harness-core/blob/3cd3378a3b06674f4d969ca8e4131e6f618d54c5/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java#L422)):*
> ```Java
> 
>       if (useDeclarativeRollback) {
>         addSuffixToConfigmapsAndSecrets(
> ```

please add some logging to make user aware of what we're doing
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/K8sConstants.java` line 189 at r1](https://reviewable.io/reviews/harness/harness-core/44431#-NPMUt6_42QZ9jy6Ck7i:-NPMUt6_42QZ9jy6Ck7j:b-3jrhvv) ([raw file](https://github.com/harness/harness-core/blob/3cd3378a3b06674f4d969ca8e4131e6f618d54c5/970-api-services-beans/src/main/java/io/harness/k8s/K8sConstants.java#L189)):*
> ```Java
>   String HARNESS_KUBE_CONFIG_PATH = "HARNESS_KUBE_CONFIG_PATH";
> 
>   String CANARY_WORKLOAD_SUFFIX_NAME_WITH_SEPARATOR = "-canary";
> ```

nit: this can be "-" + CANARY_WORKLOAD_SUFFIX_NAME
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/manifest/VersionUtils.java` line 109 at r1](https://reviewable.io/reviews/harness/harness-core/44431#-NPMUzay9h3FFI2IUAJS:-NPMUzay9h3FFI2IUAJT:b-umx5my) ([raw file](https://github.com/harness/harness-core/blob/3cd3378a3b06674f4d969ca8e4131e6f618d54c5/970-api-services-beans/src/main/java/io/harness/k8s/manifest/VersionUtils.java#L109)):*
> ```Java
> 
>   public static void addSuffixToConfigmapsAndSecrets(List<KubernetesResource> resources, String suffix) {
>     UnaryOperator<Object> appendColor = t -> t + "-" + suffix;
> ```

nit: name should be appendSuffix

**Comment by abhinavsingh1196** [comment]
trigger ut3

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44431)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
1 edge case here can be when names of the config maps and secrets are very close to the limit i.e 63 characters 
earlier we were only adding "-" + some integer ( 2-3 digits )

now we are adding a string "canary", can we considering trimming in case it exceeds ?

**Comment by yogesh-chauhan** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java` line 261 at r2](https://reviewable.io/reviews/harness/harness-core/44431#-NPSQ19S6i8vZvTN6G8L:-NPSQ19S6i8vZvTN6G8M:b-s2wm0z) ([raw file](https://github.com/harness/harness-core/blob/5861e5c0639667a4495fd8ba8b9679a984e52dff/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java#L261)):*
> ```Java
>         resources.stream()
>             .map(KubernetesResource::getResourceId)
>             .filter(resourceId -> Set.of(Kind.ConfigMap.name(), Kind.Secret.name()).contains(resourceId.getKind()))
> ```

can we create this set once before the stream operation instead of creating it everytime ?



_Code quote:_
```Java
Set.of(Kind.ConfigMap.name(), Kind.Secret.name()
```

**Review by abhinavsingh1196 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44431)* status: 14 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java` line 251 at r2](https://reviewable.io/reviews/harness/harness-core/44431#-NPSQrS4DV42dmKt1Qq7:-NPSiUEo1GnH6hIVCUei:b-g1u4ei) ([raw file](https://github.com/harness/harness-core/blob/5861e5c0639667a4495fd8ba8b9679a984e52dff/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java#L251)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

`canaryWorkloadNames` -> is this a plural ? or its just the name of the canary workload ?
</blockquote></details>

It shouldn't be, it will just be the canary workload name. Renamed.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java` line 261 at r2](https://reviewable.io/reviews/harness/harness-core/44431#-NPSQ19S6i8vZvTN6G8L:-NPSiX016_rPCBv1LMgj:b-ualzuj) ([raw file](https://github.com/harness/harness-core/blob/5861e5c0639667a4495fd8ba8b9679a984e52dff/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java#L261)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we create this set once before the stream operation instead of creating it everytime ?
</blockquote></details>

Created local set for this

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44431)* status: 14 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/44431#-NPWeP0tAd2yRjf4IULA:-NPWeP0tAd2yRjf4IULB:b-4k7cfm) ([raw file](https://github.com/harness/harness-core/blob/ff52623e27b529ef9fdd764405b0b442e5c394cf/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java#L72)):*
> ```Java
> public class K8sCanaryBaseHandler {
>   @Inject private K8sTaskHelperBase k8sTaskHelperBase;
>   private static final Set<String> secretAndConfigMapKinds = Set.of(Kind.ConfigMap.name(), Kind.Secret.name());
> ```

nit: this should be uppercase with underscore

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44431)* status: 14 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 4 of 7 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44431)* status: 15 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44431)* status: 15 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Pull request merged**
