### PR TITLE
[fix]: [PL-38384]: The scm api sshould also support http url for the onprem setups

### PR DESCRIPTION
**Pull request by DeepakPatankar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34317)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34317)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/git/GitClientHelper.java` line 207 at r1](https://reviewable.io/reviews/harness/harness-core/34317#-N4XQNJ71MsDGz3jC-kj:-N4XQNJ71MsDGz3jC-kk:b-u72s9q) ([raw file](https://github.com/harness/harness-core/blob/15eb1592306c4800b105e899960bafd2b7d808ce/960-api-services/src/main/java/io/harness/git/GitClientHelper.java#L207)):*
> ```Java
> 
>   private static boolean isUrlHTTP(String url) {
>     return url.startsWith("http") && !url.startsWith("https");
> ```

Should it be a case sensitive check? Isn't "HTTP://amazon.com" not valid?
___
*[`960-api-services/src/main/java/io/harness/git/GitClientHelper.java` line 210 at r1](https://reviewable.io/reviews/harness/harness-core/34317#-N4XQj3jB6TExntcaGfu:-N4XQj3jB6TExntcaGfv:b-qx1w8n) ([raw file](https://github.com/harness/harness-core/blob/15eb1592306c4800b105e899960bafd2b7d808ce/960-api-services/src/main/java/io/harness/git/GitClientHelper.java#L210)):*
> ```Java
>   }
> 
>   private static String getHttpProtocol(String url) {
> ```

Lets name it better: "getHttpProtocolPrefix" or something similar.

**Review by Fernando-Dourado — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34317)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/test/java/io/harness/git/GitClientHelperTest.java` line 458 at r1](https://reviewable.io/reviews/harness/harness-core/34317#-N4XSfeSE9v3R4-CuUmy:-N4XSfeSE9v3R4-CuUmz:bj9eihl) ([raw file](https://github.com/harness/harness-core/blob/15eb1592306c4800b105e899960bafd2b7d808ce/960-api-services/src/test/java/io/harness/git/GitClientHelperTest.java#L458)):*
> ```Java
>     assertThat(GitClientHelper.getGithubApiURL("git@www.github.com:harness/harness-core.git"))
>         .isEqualTo("https://api.github.com/");
>     assertThat(GitClientHelper.getGithubApiURL("http://10.67.0.1/devkimittal/harness-core"))
> ```

Add coverage for upper case
___
*[`960-api-services/src/test/java/io/harness/git/GitClientHelperTest.java` line 480 at r1](https://reviewable.io/reviews/harness/harness-core/34317#-N4XSm2R9WDx1nOwdCG_:-N4XSm2R9WDx1nOwdCGa:bj9eihl) ([raw file](https://github.com/harness/harness-core/blob/15eb1592306c4800b105e899960bafd2b7d808ce/960-api-services/src/test/java/io/harness/git/GitClientHelperTest.java#L480)):*
> ```Java
>     assertThat(GitClientHelper.getGitlabApiURL("git@www.gitlab.com:devki.mittal/test.git"))
>         .isEqualTo("https://gitlab.com/");
>     assertThat(GitClientHelper.getGitlabApiURL("http://10.67.0.1/devkimittal/harness-core"))
> ```

Add coverage for upper case

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34317)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/git/GitClientHelper.java` line 207 at r1](https://reviewable.io/reviews/harness/harness-core/34317#-N4XQNJ71MsDGz3jC-kj:-N4_t1us5ZIusM3akBkJ:bnmmbhs) ([raw file](https://github.com/harness/harness-core/blob/15eb1592306c4800b105e899960bafd2b7d808ce/960-api-services/src/main/java/io/harness/git/GitClientHelper.java#L207)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Should it be a case sensitive check? Isn't "HTTP://amazon.com" not valid?
</blockquote></details>

Yes it is case sensitive

And HTTP://amazon.com is invalid input
___
*[`960-api-services/src/main/java/io/harness/git/GitClientHelper.java` line 210 at r1](https://reviewable.io/reviews/harness/harness-core/34317#-N4XQj3jB6TExntcaGfu:-N4_tGHv3VxWRFM9F6Mt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/15eb1592306c4800b105e899960bafd2b7d808ce/960-api-services/src/main/java/io/harness/git/GitClientHelper.java#L210)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets name it better: "getHttpProtocolPrefix" or something similar.
</blockquote></details>

Done.
___
*[`960-api-services/src/test/java/io/harness/git/GitClientHelperTest.java` line 458 at r1](https://reviewable.io/reviews/harness/harness-core/34317#-N4XSfeSE9v3R4-CuUmy:-N4_tM9I2kDq9EZvrmHF:bscx200) ([raw file](https://github.com/harness/harness-core/blob/15eb1592306c4800b105e899960bafd2b7d808ce/960-api-services/src/test/java/io/harness/git/GitClientHelperTest.java#L458)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

Add coverage for upper case
</blockquote></details>

Upper case HTTP would be an invalid input. 

If the user gives HTTP://domainName/ as input then with our current code we will treat it as https. But I think since HTTP is invalid input, we shouldn't be handling it ?

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34317#-:-N4bNlbO89oCg6TsD9VB:bnfp4nl)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34317)* status: 2 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34317)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34317)* status: :shipit: complete! ✓

**Pull request merged**
