### PR TITLE
[fix]: [CDS-79000]: Increasing batching size for nodeExecutions delete during pipeline delete event

### PR DESCRIPTION
**Pull request by archit-harness**
## Describe your changes

Changes - Increasing batching size for nodeExecutions delete during pipeline delete event

Impact -> Increasing speed of deleting records

Testing - UTs are handling it

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52644)

### CODE REVIEW

**Comment by archit-harness** [comment]
trigger messagecheck

**Comment by archit-harness** [comment]
trigger uts

**Review by Y0709 — DISMISSED** [review]

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52644)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 210 at r2](https://reviewable.io/reviews/harness/harness-core/52644#-Ne1uJUY-g3KtmQ648sa:-Ne1uJUY-g3KtmQ648sb:btt7sbi) ([raw file](https://github.com/harness/harness-core/blob/f33c4f02d2599734b69dbde8b3bdaf45a87b3f56/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L210)):*
> ```Java
>     planExecutionService.deleteAllPlanExecutionAndMetadata(planExecutionsToDelete);
>     planExpansionService.deleteAllExpansions(planExecutionsToDelete);
>   }
> ```

Can we all of this in parallel and wait on futures



_Code quote:_
```Java
  private void deletePipelineExecutionsDetailsInternal(Set<String> planExecutionsToDelete) {
    // Deletes the barrierInstances
    barrierService.deleteAllForGivenPlanExecutionId(planExecutionsToDelete);
    // Delete sweepingOutput
    pmsSweepingOutputService.deleteAllSweepingOutputInstances(planExecutionsToDelete);
    // Delete outcome instances
    pmsOutcomeService.deleteAllOutcomesInstances(planExecutionsToDelete);
    // Delete all interrupts
    interruptService.deleteAllInterrupts(planExecutionsToDelete);
    // Delete all graph metadata
    graphGenerationService.deleteAllGraphMetadataForGivenExecutionIds(planExecutionsToDelete);
    // Delete nodeExecutions and its metadata
    nodeExecutionService.deleteAllNodeExecutionAndMetadata(planExecutionsToDelete);
    // Delete all planExecutions and its metadata
    planExecutionService.deleteAllPlanExecutionAndMetadata(planExecutionsToDelete);
    planExpansionService.deleteAllExpansions(planExecutionsToDelete);
  }
```

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 210 at r2](https://reviewable.io/reviews/harness/harness-core/52644#-Ne1uJUY-g3KtmQ648sa:-Ne1vlwPEXblWZMOtPO5:b32v57) ([raw file](https://github.com/harness/harness-core/blob/f33c4f02d2599734b69dbde8b3bdaf45a87b3f56/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L210)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Can we all of this in parallel and wait on futures
</blockquote></details>

+1

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52644)* status: 1 change requests. 1. unresolved discussions.

**Comment by archit-harness** [comment]
trigger uts

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52644)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 210 at r2](https://reviewable.io/reviews/harness/harness-core/52644#-Ne1uJUY-g3KtmQ648sa:-Ne6kVcP7ESrIRTRT9ry:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f33c4f02d2599734b69dbde8b3bdaf45a87b3f56/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L210)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52644)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 253 at r4](https://reviewable.io/reviews/harness/harness-core/52644#-Ne6sBHgEFMD0EO-Xu8_:-Ne6sBHgEFMD0EO-Xu8a:b-vwgbb2) ([raw file](https://github.com/harness/harness-core/blob/930e14d5080696a6ff55f75a963a79be8790adb9/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L253)):*
> ```Java
>     try {
>       // waiting for all futures to get complete
>       completableFutures.allOf().get();
> ```

Do we need a timeout here? I think we should at least start with a timeout even if this is big

**Comment by archit-harness** [comment]
trigger uts

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52644)* status: 8 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 253 at r4](https://reviewable.io/reviews/harness/harness-core/52644#-Ne6sBHgEFMD0EO-Xu8_:-Ne6v3VHEQykhdY_RdW7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/930e14d5080696a6ff55f75a963a79be8790adb9/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L253)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Do we need a timeout here? I think we should at least start with a timeout even if this is big
</blockquote></details>

Done.

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52644)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by Y0709 — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 6 of 7 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52644)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 7 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52644)* status: :shipit: complete! ✓

**Comment by archit-harness** [comment]
trigger review

**Pull request merged**
