### PR TITLE
fix: [PL-22567]: get, list graphql tests

### PR DESCRIPTION
**Pull request by mitishapandey**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34896)

### CODE REVIEW

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34896)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34896)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34896#-:-N5t-k6b-7xbk0pewzHE:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34896)* status: :shipit: complete! ✓

**Pull request merged**
