### PR TITLE
feat: [PL-38584]: Publish Platform Service Metrics

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

This PR does the below -
1. Enhances the Metrics module by instantiating a single Metrics Service Object and using it during Guice configuration.
2. Publishes DW metrics from Platform service to prometheus.

Tested it in local environment.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51304)

### CODE REVIEW

**Comment by Raghav-Murali** [comment]
trigger uts

**Comment by Raghav-Murali** [comment]
trigger uts

**Review by raghuAtWings — DISMISSED** [review]

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51304)* status: 9 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`platform-service/service/src/main/resources/metrics/metricDefinitions/platform_service_metrics.yaml` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/51304#-NayPTcgBinJACYNJ0cA:-NayPTcgBinJACYNJ0cB:bfyedqw) ([raw file](https://github.com/harness/harness-core/blob/8430540f03b4672be8dfbc6cbb36f4c2ffc78fdb/platform-service/service/src/main/resources/metrics/metricDefinitions/platform_service_metrics.yaml#L117)):*
> ```YAML
>     type: LastValue
>     unit: count
>   - metricName: org_eclipse_jetty_server_HttpConnectionFactory_7090_connections_count
> ```

Should this be org_eclipse_jetty_server_HttpConnectionFactory_9005_connections_count as server is listening on port 9005. Pls check once.

Also, I am assuming we have copied the metrics from manager service?

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51304)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/service/src/main/resources/metrics/metricDefinitions/platform_service_metrics.yaml` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/51304#-NayPTcgBinJACYNJ0cA:-NayYa9h7jhqB5B7j3nI:bu1p8jv) ([raw file](https://github.com/harness/harness-core/blob/8430540f03b4672be8dfbc6cbb36f4c2ffc78fdb/platform-service/service/src/main/resources/metrics/metricDefinitions/platform_service_metrics.yaml#L117)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should this be org_eclipse_jetty_server_HttpConnectionFactory_9005_connections_count as server is listening on port 9005. Pls check once.

Also, I am assuming we have copied the metrics from manager service?
</blockquote></details>

Yes, thanks for catching this. It should be 9005. And in manager it should be 9090 instead of 7090, I have fixed that in this PR too. Thanks.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 8 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51304)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Comment by Raghav-Murali** [comment]
trigger uts

**Comment by Raghav-Murali** [comment]
trigger checkstylecodeformat, messagecheck, pmd, codebasehash

**Comment by Raghav-Murali** [comment]
trigger commonchecks, review, mdc, ut4

**Comment by Raghav-Murali** [comment]
trigger commonchecks

**Pull request merged**
