### PR TITLE
[fix]: [SRM-10551]: throw exception back in case of error while saving time series records

### PR DESCRIPTION
**Pull request by kjoshi12345**
* This will show the exception in the UI and in the execution logs

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33232)

### CODE REVIEW

**Comment by kjoshi12345** [comment]
image

**Comment by kjoshi12345** [comment]
image

**Comment by kjoshi12345** [comment]
trigger messagecheck

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33232)* status: :shipit: complete! ✓

**Review by arpit3107 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33232)* status: :shipit: complete! ✓

**Pull request merged**
