### PR TITLE
feat: [CDS-73385]: remove older methods using yaml

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49976)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger ut5

**Comment by shalini-agr** [comment]
trigger ut5

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 24 of 26 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49976)* status: 27 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 170 at r3](https://reviewable.io/reviews/harness/harness-core/49976#-NZVMcbh5Z7a9f8yFJyM:-NZVMcbh5Z7a9f8yFJyN:b-hxyhzi) ([raw file](https://github.com/harness/harness-core/blob/c11d9f80f831efca91e44a44da84c4c1c9bc24c6/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L170)):*
> ```Java
> 
>   @Override
>   public boolean validateYamlSchema(String accountId, String orgId, String projectId, JsonNode jsonNode) {
> ```

Add static schema changes
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 234 at r3](https://reviewable.io/reviews/harness/harness-core/49976#-NZVMePm9lTGX1vnpcFY:-NZVMePm9lTGX1vnpcFZ:b-hxyhzi) ([raw file](https://github.com/harness/harness-core/blob/c11d9f80f831efca91e44a44da84c4c1c9bc24c6/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L234)):*
> ```Java
>   // TODO(shalini): remove older methods with yaml string once all are moved to jsonNode
>   @VisibleForTesting
>   boolean validateYamlSchemaInternal(String accountIdentifier, String orgId, String projectId, JsonNode jsonNode) {
> ```

Add static schema changes
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java` line 99 at r3](https://reviewable.io/reviews/harness/harness-core/49976#-NZVNC6k-iYBxRggx5Da:-NZVNC6k-iYBxRggx5Db:b-pcj4bx) ([raw file](https://github.com/harness/harness-core/blob/c11d9f80f831efca91e44a44da84c4c1c9bc24c6/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java#L99)):*
> ```Java
>             .inputSetReferences(config.getInputSetReferences())
>             .outputs(ParameterField.createValueField(PipelineStageOutputs.getMapOfString(config.getOutputs())));
>     if (pmsFeatureFlagService.isEnabled(accountIdentifier, FeatureName.PIE_PROCESS_ON_JSON_NODE)) {
> ```

remove FF as well
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java` line 276 at r3](https://reviewable.io/reviews/harness/harness-core/49976#-NZVNyf99Asfe7SUpCUE:-NZVNyf99Asfe7SUpCUF:bo3ih5s) ([raw file](https://github.com/harness/harness-core/blob/c11d9f80f831efca91e44a44da84c4c1c9bc24c6/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java#L276)):*
> ```Java
> 
>     StagesExecutionMetadata stagesExecutionMetadata = planExecutionMetadata.getStagesExecutionMetadata();
>     ExecArgs execArgs = executionHelper.buildExecutionArgs(pipelineEntity, moduleType, inputSetPipelineYaml,
> ```

inputSetPipelineYaml to jsonNode to buildexecutionArgs method

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49976)* status: 28 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 170 at r3](https://reviewable.io/reviews/harness/harness-core/49976#-NZVMcbh5Z7a9f8yFJyM:-NZVT3sj1iOkP80aMv9o:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c11d9f80f831efca91e44a44da84c4c1c9bc24c6/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L170)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Add static schema changes
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 234 at r3](https://reviewable.io/reviews/harness/harness-core/49976#-NZVMePm9lTGX1vnpcFY:-NZVT467-y5stjjpo_Oh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c11d9f80f831efca91e44a44da84c4c1c9bc24c6/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L234)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Add static schema changes
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java` line 99 at r3](https://reviewable.io/reviews/harness/harness-core/49976#-NZVNC6k-iYBxRggx5Da:-NZVT8U8-XVCeogtwPGi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c11d9f80f831efca91e44a44da84c4c1c9bc24c6/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java#L99)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

remove FF as well
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java` line 276 at r3](https://reviewable.io/reviews/harness/harness-core/49976#-NZVNyf99Asfe7SUpCUE:-NZVTSmd0SLKkXSXg4tp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c11d9f80f831efca91e44a44da84c4c1c9bc24c6/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java#L276)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

inputSetPipelineYaml to jsonNode to buildexecutionArgs method
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49976)* status: 29 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 22 of 26 files at r1, 2 of 2 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49976)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
