### PR TITLE
Feat: [SRM-13846]: Update Monitored services API to have search filte…

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
…r, env name, service name and SLO Identifiers

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43525)

### CODE REVIEW

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43525)* status: 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 695 at r1](https://reviewable.io/reviews/harness/harness-core/43525#-NNaZa-u1bkgt0-kbS4f:-NNaZa-u1bkgt0-kbS4g:boqqp40) ([raw file](https://github.com/harness/harness-core/blob/76effef3b2249dfafa5e761c4823b305bf836910/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L695)):*
> ```Java
>         getMonitoredServicesByEnvIds(projectParams, environmentIdentifiers);
>     List<String> serviceIdentifiers = new ArrayList<>();
>     List<String> environmentIdentifierList = new ArrayList<>();
> ```

nit: We are using the suffix List intermittently. Should either be plural noun or suffixed with list
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/resources/DowntimeProjectLevelResource.java` line 123 at r1](https://reviewable.io/reviews/harness/harness-core/43525#-NNaZwGSEA1tjScCb1qv:-NNaZwGSEA1tjScCb1qw:b-80yz22) ([raw file](https://github.com/harness/harness-core/blob/76effef3b2249dfafa5e761c4823b305bf836910/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/resources/DowntimeProjectLevelResource.java#L123)):*
> ```Java
>   @Path("/monitored-services/{identifier}")
>   @ApiOperation(value = "get associated Monitored Services", nickname = "getDowntimeAssociatedMonitoredServices")
>   /*  @Operation(operationId = "getDowntime", summary = "Get Downtime data",
> ```

Smell

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43525)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/resources/DowntimeProjectLevelResource.java` line 123 at r1](https://reviewable.io/reviews/harness/harness-core/43525#-NNaZwGSEA1tjScCb1qv:-NNafAAkB-yxNZO169fl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/76effef3b2249dfafa5e761c4823b305bf836910/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/resources/DowntimeProjectLevelResource.java#L123)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Smell
</blockquote></details>

Done.

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43525)* status: 1 file(s) to review. 0 of 1 approvals obtained.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 9 of 17 files at r1, 6 of 10 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43525)* status: :shipit: complete! ✓

**Pull request merged**
