### PR TITLE
fix: [CDS-71707]: Adding  check for required variables value that are exec…

### PR DESCRIPTION
**Pull request by Y0709**
…utionInput

Issue - We had to add support from backed to check whether value is present for required variables that are runtime execution inputs

Solution -  We have used field yaml to check which all variables are execution input and required and if their values are not present or empty in execution input yam then we throw an exception. This solution will work only for stage variables and some step variables . From UI as well this is supported for stage variables only. Pipeline variables cannot be execution input and service and env variables are evaluated when the service step begins hence if we do enter empty value value for a required service or environment variable it will fail at the service step. 

Testing -- Tested this for stage variables for custom and cd stage. Both with required and not required string and number variables as secret variables cannot be execution inputs. Also tested that when execution input yaml is empty and some required variable is present in field yaml than we throw an error. Also tested with templatized cd stage variables required and non required

Also we are applying this check on values for variables before the expressions are resolved in the execution input yaml so that in case some expression resolves to empty value we do not throw an error to keep it similar as normal runtime input behaviour.

Also to find the variables in the field yaml we just go first child node of the field yaml node and find the variables array node .

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49609)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger uts

**Review by shalini-agr — DISMISSED** [review]

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger uts

**Review by shalini-agr — APPROVED** [review]

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49609)* status: 3 file(s) to review.

**Comment by Y0709** [comment]
trigger review

**Comment by Y0709** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 159 at r3](https://reviewable.io/reviews/harness/harness-core/49609#-NYsmKdq9ouTufzryaS4:-NYsmKdq9ouTufzryaS5:b-qe9l2l) ([raw file](https://github.com/harness/harness-core/blob/e31e4014e7098caae2f042baef9125d9b24ac8c5/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L159)):*
> ```Java
>   }
> 
>   public void checkValueForRequiredVariablesProvided(
> ```

nit: This looks like a pretty complicated function, can we add comments on it?

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49609)* status: :shipit: complete! ✓

**Comment by Y0709** [comment]
Will be adding comment in a new pr. Merged this so that it goes to preqa tomorrow and maybe qa if branch cut happens

**Pull request merged**
