### PR TITLE
[feat]: [CDS-33522]: APIs and related classes

### PR DESCRIPTION
**Pull request by markoharness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32204)

### CODE REVIEW

**Review by alebuh — COMMENTED** [review]
> Reviewed 57 of 57 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32204)* status: 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java, line 61 at r1](https://reviewable.io/reviews/harness/harness-core/32204#-N-Smrm2D7n6Q7wfQQYA:-N-Smrm2D7n6Q7wfQQYB:byif1oh) ([raw file](https://github.com/harness/harness-core/blob/e791f38dfd83f4275d9252433e115a84fc43daab/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java#L61)):*
> ```Java
> 
>   @GET
>   @Path("subscriptions/{subscription}/container-registries")
> ```

As we moved subscription API to another class does it make sense to remove "subscriptions/{subscription}/" from the path here, and pass just subscriptionId as QueryParam?
"/artifacts/acr/subscriptions/{subscription}/container-registries/" is little robust for path and it's strange for subscriptions to be in the scope below /artifact/acr
___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java, line 76 at r1](https://reviewable.io/reviews/harness/harness-core/32204#-N-SnUPA9JCJPzN08ruX:-N-SnUPA9JCJPzN08ruY:b-dos0ms) ([raw file](https://github.com/harness/harness-core/blob/e791f38dfd83f4275d9252433e115a84fc43daab/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java#L76)):*
> ```Java
> 
>   @GET
>   @Path("subscriptions/{subscription}/container-registries/{registry}/repositories")
> ```

same as for getRegistriesBySubscription method

**Comment by markoharness** [comment]
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java, line 61 at r1](https://reviewable.io/reviews/harness/harness-core/32204#-N-Smrm2D7n6Q7wfQQYA:-N-SvPQFECcBRZFlsfMJ:b-o3rxwv) ([raw file](https://github.com/harness/harness-core/blob/e791f38dfd83f4275d9252433e115a84fc43daab/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java#L61)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

As we moved subscription API to another class does it make sense to remove "subscriptions/{subscription}/" from the path here, and pass just subscriptionId as QueryParam?
"/artifacts/acr/subscriptions/{subscription}/container-registries/" is little robust for path and it's strange for subscriptions to be in the scope below /artifact/acr
</blockquote></details>

You are right. Refactored.

**Comment by markoharness** [comment]
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java, line 76 at r1](https://reviewable.io/reviews/harness/harness-core/32204#-N-SnUPA9JCJPzN08ruX:-N-SvSZj1hvfEKtLk55O:b-o3rxwv) ([raw file](https://github.com/harness/harness-core/blob/e791f38dfd83f4275d9252433e115a84fc43daab/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java#L76)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

same as for getRegistriesBySubscription method
</blockquote></details>

You are right. Refactored.

**Review by alebuh — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32204)* status: 2. unresolved discussions.

**Comment by markoharness** [comment]
trigger license/cla

**Review by alebuh — DISMISSED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32204)* status: :shipit: complete! ✓

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 54 of 57 files at r1, 2 of 4 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32204)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java, line 63 at r5](https://reviewable.io/reviews/harness/harness-core/32204#-N-WfSTEDC64WsT6NZQw:-N-WfSTEDC64WsT6NZQx:b1ymnzf) ([raw file](https://github.com/harness/harness-core/blob/e1fcd7a38f8d06d2b4bd8e7987c3b17962681a94/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java#L63)):*
> ```Java
>   @Path("container-registries")
>   @ApiOperation(value = "Gets ACR registries by subscription ", nickname = "getACRRegistriesBySubscription")
>   public ResponseDTO<List<String>> getRegistriesBySubscription(
> ```

nit: I don't think that returning plain list is a good idea, this is not something that can be extended without introducing a new version of API (the same is applying to other places and for Map). If this API was already agreed then I'm good, but we shouldn't do this in future
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/azure/AzureHelperService.java, line 77 at r5](https://reviewable.io/reviews/harness/harness-core/32204#-N-WgJIp8whr3r7vvd85:-N-WgJIp8whr3r7vvd86:b-ltsoab) ([raw file](https://github.com/harness/harness-core/blob/e1fcd7a38f8d06d2b4bd8e7987c3b17962681a94/125-cd-nextgen/src/main/java/io/harness/cdng/azure/AzureHelperService.java#L77)):*
> ```Java
>             azureConnectorRef.getProjectIdentifier(), azureConnectorRef.getIdentifier());
> 
>     if (!connectorDTO.isPresent() || !isAzureConnector(connectorDTO.get())) {
> ```

isAzureConnector can be a different error. It can be confusing when you provide a known connector identifier and it is saying that is not found
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/azure/AzureHelperService.java, line 121 at r5](https://reviewable.io/reviews/harness/harness-core/32204#-N-WgbCx78JPkSxVBPBU:-N-WgbCx78JPkSxVBPBV:b-nn2qd2) ([raw file](https://github.com/harness/harness-core/blob/e1fcd7a38f8d06d2b4bd8e7987c3b17962681a94/125-cd-nextgen/src/main/java/io/harness/cdng/azure/AzureHelperService.java#L121)):*
> ```Java
>       taskSelectors = azureTaskParams.getDelegateSelectors();
>     }
>     if (executionCapabilityDemander instanceof AcrArtifactDelegateRequest) {
> ```

nit: else if
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/azure/AzureHelperService.java, line 155 at r5](https://reviewable.io/reviews/harness/harness-core/32204#-N-WhitH3VepwTQYic4p:-N-WhitH3VepwTQYic4q:b-nn2qd2) ([raw file](https://github.com/harness/harness-core/blob/e1fcd7a38f8d06d2b4bd8e7987c3b17962681a94/125-cd-nextgen/src/main/java/io/harness/cdng/azure/AzureHelperService.java#L155)):*
> ```Java
>       throw new ArtifactServerException(ifFailedMessage + " - " + errorNotifyResponseData.getErrorMessage());
>     }
>     if (responseData instanceof AzureDelegateTaskResponse) {
> ```

nit: else if
___
*[125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java, line 124 at r5](https://reviewable.io/reviews/harness/harness-core/32204#-N-WjTi2DQUuyfjBlc69:-N-WjTi2DQUuyfjBlc6A:b-fee5g6) ([raw file](https://github.com/harness/harness-core/blob/e1fcd7a38f8d06d2b4bd8e7987c3b17962681a94/125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java#L124)):*
> ```Java
>     kryo.register(DockerHubArtifactConfig.class, 8011);
>     kryo.register(GcrArtifactConfig.class, 8012);
>     kryo.register(AcrArtifactConfig.class, 8013);
> ```

Let's not reuse id's that were used in past and removed, even that it is very old
And let's move it to the class end, this is the last id 12563 used by this module. We stop use of 8xxx because it is referenced in 400-rest as well

**Comment by markoharness** [comment]
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java, line 63 at r5](https://reviewable.io/reviews/harness/harness-core/32204#-N-WfSTEDC64WsT6NZQw:-N-WpWokEsWmvLVYhgR_:bi060ye) ([raw file](https://github.com/harness/harness-core/blob/e1fcd7a38f8d06d2b4bd8e7987c3b17962681a94/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java#L63)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: I don't think that returning plain list is a good idea, this is not something that can be extended without introducing a new version of API (the same is applying to other places and for Map). If this API was already agreed then I'm good, but we shouldn't do this in future
</blockquote></details>

I agree. Currently this API was agreed as it is. However we can still make changes (as it is not going to be used in production for while). I will see to making this change in the next PR.

**Comment by markoharness** [comment]
*[125-cd-nextgen/src/main/java/io/harness/cdng/azure/AzureHelperService.java, line 77 at r5](https://reviewable.io/reviews/harness/harness-core/32204#-N-WgJIp8whr3r7vvd85:-N-WpyDO06NPfnwQVhZK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e1fcd7a38f8d06d2b4bd8e7987c3b17962681a94/125-cd-nextgen/src/main/java/io/harness/cdng/azure/AzureHelperService.java#L77)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

isAzureConnector can be a different error. It can be confusing when you provide a known connector identifier and it is saying that is not found
</blockquote></details>

Done.

**Comment by markoharness** [comment]
*[125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java, line 124 at r5](https://reviewable.io/reviews/harness/harness-core/32204#-N-WjTi2DQUuyfjBlc69:-N-Wq-zW0h48ttUtdoMS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e1fcd7a38f8d06d2b4bd8e7987c3b17962681a94/125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java#L124)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's not reuse id's that were used in past and removed, even that it is very old
And let's move it to the class end, this is the last id 12563 used by this module. We stop use of 8xxx because it is referenced in 400-rest as well
</blockquote></details>

Done.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32204)* status: :shipit: complete! ✓

**Review by alebuh — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32204)* status: :shipit: complete! ✓

**Comment by markoharness** [comment]
trigger ti0

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32204)* status: :shipit: complete! ✓

**Review by alebuh — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32204)* status: :shipit: complete! ✓

**Pull request merged**
