### PR TITLE
techdebt: [PIE-4710]: code refactoring for independent deployment - debezium service

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36195)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 12 Issues 
* Vulnerability 5 Vulnerabilities 
 * Code issue 7 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36195)

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 19 of 19 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36195)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36195)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 35 of 35 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36195)* status: 35 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 35 of 35 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36195)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36195)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`WORKSPACE` line 5302 at r5](https://reviewable.io/reviews/harness/harness-core/36195#-N95aWzD7HRThnTz-uvT:-N95aWzD7HRThnTz-uvU:b-g8undk) ([raw file](https://github.com/harness/harness-core/blob/954e4da2283198e41ce438b202fdd23b9473868f/WORKSPACE#L5302)):*
> ```Starlark
>             group = "io.debezium",
>             artifact = "debezium-embedded",
>             version = "1.9.0-SNAPSHOT",
> ```

reason for update?
___
*[`WORKSPACE` line 5312 at r5](https://reviewable.io/reviews/harness/harness-core/36195#-N95aI5N9k-T-cc-kA8P:-N95aI5O8Uyh29rcL-lI:bss7p65) ([raw file](https://github.com/harness/harness-core/blob/954e4da2283198e41ce438b202fdd23b9473868f/WORKSPACE#L5312)):*
> ```Starlark
>         "https://harness.jfrog.io/harness/thirdparty-annonymous",
> #        "https://repo1.maven.org/maven2",
> #        "http://jfrogdev.dev.harness.io:80/artifactory/portal-maven",
> ```

why are we removing these? Even though we if we are removing, remove them from comments
___
*[`scripts/jenkins/portal-openjdk-bazel.sh` line 281 at r5](https://reviewable.io/reviews/harness/harness-core/36195#-N95gVFu7RnQGAuXPaDf:-N95gVFu7RnQGAuXPaDg:bhrfixa) ([raw file](https://github.com/harness/harness-core/blob/954e4da2283198e41ce438b202fdd23b9473868f/scripts/jenkins/portal-openjdk-bazel.sh#L281)):*
> ```Shell
> cp ../../dockerization/debezium-service/Dockerfile-debezium-service-jenkins-k8-openjdk ./Dockerfile
> cp ../../dockerization/debezium-service/Dockerfile-debezium-service-jenkins-k8-gcr-openjdk ./Dockerfile-gcr
> cp ../../dockerization/debezium-service/Dockerfile-debezium-service-cie-jdk ./Dockerfile-cie-jdk
> ```

why this line is added?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36195)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`WORKSPACE` line 5302 at r5](https://reviewable.io/reviews/harness/harness-core/36195#-N95aWzD7HRThnTz-uvT:-N95gzqM9mPOpoJL_Jt0:bsnc5ay) ([raw file](https://github.com/harness/harness-core/blob/954e4da2283198e41ce438b202fdd23b9473868f/WORKSPACE#L5302)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

reason for update?
</blockquote></details>

reverted this change
___
*[`WORKSPACE` line 5312 at r5](https://reviewable.io/reviews/harness/harness-core/36195#-N95aI5N9k-T-cc-kA8P:-N95gx2361pGTWddtRBv:b-t0fo50) ([raw file](https://github.com/harness/harness-core/blob/954e4da2283198e41ce438b202fdd23b9473868f/WORKSPACE#L5312)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

why are we removing these? Even though we if we are removing, remove them from comments
</blockquote></details>

reverted this change.

**Review by prashantsharma04 — DISMISSED** [review]
> Reviewed 32 of 35 files at r3, 1 of 1 files at r4, 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36195)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger ti1

**Comment by shalini-agr** [comment]
trigger ti1

**Comment by shalini-agr** [comment]
trigger ft1, ft2, compile

**Comment by shalini-agr** [comment]
trigger ti0

**Comment by shalini-agr** [comment]
trigger ti0

**Comment by shalini-agr** [comment]
trigger ti0

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 28 of 35 files at r3, 1 of 1 files at r4, 2 of 2 files at r6, 4 of 4 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36195)* status: Some of the checks are too old. 6 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — DISMISSED** [review]
> Reviewed 4 of 4 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36195)* status: Some of the checks are too old.

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 2 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36195)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 28 of 35 files at r3, 1 of 1 files at r4, 1 of 2 files at r6, 2 of 4 files at r8, 2 of 2 files at r9, 3 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36195)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
