### PR TITLE
feat: [PL-29433]: fix listFilesInCommitAPI pagination issues and add corresponding SCM to delegate

### PR DESCRIPTION
**Pull request by mohitg0795**
## Describe your changes
Tested listFilesInCommitAPI with bitbucket, it works with proper paginated response.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39392)

### CODE REVIEW

**Review by adivishy1 — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39392)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
trigger ft1

**Comment by mohitg0795** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
trigger ft2

**Comment by mohitg0795** [comment]
trigger compile

**Comment by diptiman-adak** [comment]
trigger ft1, ft2

**Review by shubham149 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39392#-:-NFguliM5E7Nv2Gm9BNb:bnfp4nl)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
trigger ft2

**Comment by mohitg0795** [comment]
trigger ft1

**Comment by mohitg0795** [comment]
trigger ft2

**Comment by mohitg0795** [comment]
trigger ft2

**Comment by mohitg0795** [comment]
trigger ft2

**Comment by mohitg0795** [comment]
trigger ft1

**Comment by mohitg0795** [comment]
trigger ti0

**Comment by mohitg0795** [comment]
trigger ti1

**Comment by mohitg0795** [comment]
trigger ti3

**Comment by mohitg0795** [comment]
trigger ti4

**Comment by mohitg0795** [comment]
trigger ti5

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39392)* status: :shipit: complete! ✓

**Pull request merged**
