### PR TITLE
[feat]: [CDS-38223]: List file by referred entity enhancement

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Describe your changes
file-store/referenced-by-entity-scope API endpoint enhancement: List files referred by provided entity type and entity name.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33708)

### CODE REVIEW

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33708)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/EntitySetupUsageQueryFilterHelper.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/33708#-N3O63qS1AYV8JR4cB10:-N3O63qS1AYV8JR4cB11:b-t236is) ([raw file](https://github.com/harness/harness-core/blob/ca7ff1bbc5301493c0b2abc0162b50dbd0441c22/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/EntitySetupUsageQueryFilterHelper.java#L182)):*
> ```Java
>       criteria.and(EntitySetupUsageKeys.referredByEntityType).is(referredByEntityType.getYamlName());
>     }
>     if (null != referredByEntityName) {
> ```

do we need check if referredByEntityName is not empty?
___
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/EntitySetupUsageQueryFilterHelper.java` line 183 at r1](https://reviewable.io/reviews/harness/harness-core/33708#-N3O6Crg0FY5ZvWVCve-:-N3O6Crg0FY5ZvWVCve0:b2mleob) ([raw file](https://github.com/harness/harness-core/blob/ca7ff1bbc5301493c0b2abc0162b50dbd0441c22/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/EntitySetupUsageQueryFilterHelper.java#L183)):*
> ```Java
>     }
>     if (null != referredByEntityName) {
>       criteria.and(EntitySetupUsageKeys.referredByEntityName).is(referredByEntityName);
> ```

should we use regex(referredByEntityName) instead of is(referredByEntityName); ?

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33708)* status: 29 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/EntitySetupUsageQueryFilterHelper.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/33708#-N3O63qS1AYV8JR4cB10:-N3cZIB2EwUNEU93s5S3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ca7ff1bbc5301493c0b2abc0162b50dbd0441c22/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/EntitySetupUsageQueryFilterHelper.java#L182)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

do we need check if referredByEntityName is not empty?
</blockquote></details>

Done.
___
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/EntitySetupUsageQueryFilterHelper.java` line 183 at r1](https://reviewable.io/reviews/harness/harness-core/33708#-N3O6Crg0FY5ZvWVCve-:-N3cZIWO4ruzdl7Szwfl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ca7ff1bbc5301493c0b2abc0162b50dbd0441c22/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/EntitySetupUsageQueryFilterHelper.java#L183)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

should we use regex(referredByEntityName) instead of is(referredByEntityName); ?
</blockquote></details>

Done.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 17 of 17 files at r2, 3 of 3 files at r3, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33708#-:-N3c_loR1Vr4wKGdOSGy:bnfp4nl)* status: :shipit: complete! ✓

___
*[`877-filestore/src/main/java/io/harness/repositories/FileStoreRepositoryCriteriaCreator.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/33708#-N3cWh976y4iZUiPwlpG:-N3cWh976y4iZUiPwlpH:b-f1yzfk) ([raw file](https://github.com/harness/harness-core/blob/88749393c32b14e76c60de7c13ce6ef013dbfc51/877-filestore/src/main/java/io/harness/repositories/FileStoreRepositoryCriteriaCreator.java#L70)):*
> ```Java
>     }
> 
>     if (filterProperties != null && null != filterProperties.getReferencedBy()) {
> ```

Minor - do we need here and filterProperties.getReferencedBy().getType != null

**Comment by bojanmicovic** [comment]
*[`877-filestore/src/main/java/io/harness/filestore/dto/mapper/FilesFilterPropertiesMapper.java` line 24 at r8](https://reviewable.io/reviews/harness/harness-core/33708#-N3cvLep6kkh0hbGxSNO:-N3cvLep6kkh0hbGxSNP:bam3xit) ([raw file](https://github.com/harness/harness-core/blob/6d7b95e5c02208374742db5788ca035823ea06f3/877-filestore/src/main/java/io/harness/filestore/dto/mapper/FilesFilterPropertiesMapper.java#L24)):*
> ```Java
>     implements FilterPropertiesMapper<FilesFilterPropertiesDTO, FilesFilterProperties> {
>   @Override
>   public FilesFilterPropertiesDTO writeDTO(FilterProperties filterProperties) {
> ```

Was there a specific reason why we changed the type?

**Comment by vladimir-peric** [comment]
*[`877-filestore/src/main/java/io/harness/filestore/dto/mapper/FilesFilterPropertiesMapper.java` line 24 at r8](https://reviewable.io/reviews/harness/harness-core/33708#-N3cvLep6kkh0hbGxSNO:-N3cvvWr4AX6uqhWUSyL:b6aw37g) ([raw file](https://github.com/harness/harness-core/blob/6d7b95e5c02208374742db5788ca035823ea06f3/877-filestore/src/main/java/io/harness/filestore/dto/mapper/FilesFilterPropertiesMapper.java#L24)):*
<details><summary><i>Previously, bojanmicovic (Bojan Micovic) wrote…</i></summary><blockquote>

Was there a specific reason why we changed the type?
</blockquote></details>

Could be this was not needed, indeed. Will check if everything works fine without this change and revert it if so.

**Comment by vladimir-peric** [comment]
*[`877-filestore/src/main/java/io/harness/repositories/FileStoreRepositoryCriteriaCreator.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/33708#-N3cWh976y4iZUiPwlpG:-N3cwztY7zGWHQxY5Kiu:bqog7zb) ([raw file](https://github.com/harness/harness-core/blob/88749393c32b14e76c60de7c13ce6ef013dbfc51/877-filestore/src/main/java/io/harness/repositories/FileStoreRepositoryCriteriaCreator.java#L70)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - do we need here and filterProperties.getReferencedBy().getType != null
</blockquote></details>

Agree.

**Comment by bojanmicovic** [comment]
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/EntitySetupUsageQueryFilterHelper.java` line 185 at r8](https://reviewable.io/reviews/harness/harness-core/33708#-N3cznUHE_eALMMzufil:-N3cznUHE_eALMMzufim:b8b73h8) ([raw file](https://github.com/harness/harness-core/blob/6d7b95e5c02208374742db5788ca035823ea06f3/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/EntitySetupUsageQueryFilterHelper.java#L185)):*
> ```Java
>       criteria.and(EntitySetupUsageKeys.referredByEntityType).is(referredByEntityType.getYamlName());
>     }
>     if (null != referredByEntityName) {
> ```

Consider checking if the string is not Empty also

**Comment by bojanmicovic** [comment]
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/EntitySetupUsageQueryFilterHelper.java` line 178 at r8](https://reviewable.io/reviews/harness/harness-core/33708#-N3d0tGC0skfLiDvkrUJ:-N3d0tGC0skfLiDvkrUK:b2rcf6g) ([raw file](https://github.com/harness/harness-core/blob/6d7b95e5c02208374742db5788ca035823ea06f3/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/EntitySetupUsageQueryFilterHelper.java#L178)):*
> ```Java
>     criteria.and(EntitySetupUsageKeys.accountIdentifier).is(scope.getAccountIdentifier());
>     criteria.and(EntitySetupUsageKeys.referredEntityFQN).regex(referredEntityFQScope);
>     criteria.and(EntitySetupUsageKeys.referredEntityRefScope).is(ScopeLevel.of(scope));
> ```

Doublecheck if this is the right criteria, since ScopeLevel and Scope from EntityRef are not the same enums.

**Comment by vladimir-peric** [comment]
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/EntitySetupUsageQueryFilterHelper.java` line 178 at r8](https://reviewable.io/reviews/harness/harness-core/33708#-N3d0tGC0skfLiDvkrUJ:-N3d6zZX7eIFp2VVGh2j:b9yrwu2) ([raw file](https://github.com/harness/harness-core/blob/6d7b95e5c02208374742db5788ca035823ea06f3/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/EntitySetupUsageQueryFilterHelper.java#L178)):*
<details><summary><i>Previously, bojanmicovic (Bojan Micovic) wrote…</i></summary><blockquote>

Doublecheck if this is the right criteria, since ScopeLevel and Scope from EntityRef are not the same enums.
</blockquote></details>

In my local tests this worked fine, looks like mongo compares enum names, not exact objects, so it made no issues. However, you might be right on this, I'll definitely rewrite this

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33708)* status: 31 file(s) to review. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/EntitySetupUsageQueryFilterHelper.java` line 185 at r8](https://reviewable.io/reviews/harness/harness-core/33708#-N3cznUHE_eALMMzufil:-N3d6yyD7-3CK31mSpFf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6d7b95e5c02208374742db5788ca035823ea06f3/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/EntitySetupUsageQueryFilterHelper.java#L185)):*
<details><summary><i>Previously, bojanmicovic (Bojan Micovic) wrote…</i></summary><blockquote>

Consider checking if the string is not Empty also
</blockquote></details>

Done.

**Comment by vladimir-peric** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Comment by vladimir-peric** [comment]
trigger ti2

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 26 of 29 files at r8, 1 of 1 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33708#-:-N3dbWoy7IVy7fl_Ilxi:bnfp4nl)* status: 1 file(s) to review. 3. unresolved discussions.

**Comment by vladimir-peric** [comment]
trigger ti2

**Pull request closed without merging**
