### PR TITLE
feat: [CDS-79714]: Add yaml hash in Pipeline Entity

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Add yaml hash in Pipeline Entity

Tested Pipeline Create/Update Flows the hash is getting changed on yaml update and hash is consistent if we try to update same yaml

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53145)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java` line 197 at r1](https://reviewable.io/reviews/harness/harness-core/53145#-Ner1Z6mCVqck31YTGfV:-Ner1Z6mCVqck31YTGfW:b64ie8g) ([raw file](https://github.com/harness/harness-core/blob/87b0ce42446b5997f37ec673af03415f1b3d9719/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java#L197)):*
> ```Java
>   @Wither @Setter @NonFinal String connectorRef;
>   @Wither @Setter @NonFinal String repoURL;
>   @Setter @NonFinal int yamlHash;
> ```

should be boxed integer else old yamls will not open.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53145)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53145)* status: 3 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java` line 197 at r1](https://reviewable.io/reviews/harness/harness-core/53145#-Ner1Z6mCVqck31YTGfV:-Ner5jOi-9q9qEaUVIqH:b32v57) ([raw file](https://github.com/harness/harness-core/blob/87b0ce42446b5997f37ec673af03415f1b3d9719/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java#L197)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

should be boxed integer else old yamls will not open.
</blockquote></details>

+1
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 257 at r1](https://reviewable.io/reviews/harness/harness-core/53145#-Ner5zZo0Y5B76CkUIi7:-Ner5zZo0Y5B76CkUIi8:bk5hyrk) ([raw file](https://github.com/harness/harness-core/blob/87b0ce42446b5997f37ec673af03415f1b3d9719/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L257)):*
> ```Java
>         isDraft = false;
>       }
>       int yamlHash = getYamlHash(requestInfoDTO.getYaml());
> ```

intermediate variable is not required



_Code quote:_
```Java
getYamlHash(requestInfoDTO.getYaml())
```

**Review by utkarshchoubey-harness — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53145)* status: 4 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java` line 197 at r1](https://reviewable.io/reviews/harness/harness-core/53145#-Ner1Z6mCVqck31YTGfV:-NerAnXFADA9hawabphS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/87b0ce42446b5997f37ec673af03415f1b3d9719/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java#L197)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 257 at r1](https://reviewable.io/reviews/harness/harness-core/53145#-Ner5zZo0Y5B76CkUIi7:-NerAnzqD2MqA0kKjfPf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/87b0ce42446b5997f37ec673af03415f1b3d9719/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L257)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

intermediate variable is not required
</blockquote></details>

Done.

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53145)* status: 4 file(s) to review. 3 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 178 at r1](https://reviewable.io/reviews/harness/harness-core/53145#-Ner3R715dtsgqIkaffd:-Ner3R723uCRmNO7uWpy:b142743) ([raw file](https://github.com/harness/harness-core/blob/87b0ce42446b5997f37ec673af03415f1b3d9719/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L178)):*
> ```Java
> 
>   int getYamlHash(String yaml) {
>     return Objects.hashCode(yaml);
> ```

This is not correct this hash can change across multiple executions of the application and also with java version etc.

You should use a noon cryptographic fast hash function here like Murmurhash, I think it is provided by Guava and apache commons
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 257 at r1](https://reviewable.io/reviews/harness/harness-core/53145#-Ner5zZo0Y5B76CkUIi7:-NerJpFI9_YrDjbifoIE:b-n54bip) ([raw file](https://github.com/harness/harness-core/blob/87b0ce42446b5997f37ec673af03415f1b3d9719/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L257)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can we use some pre persist hooks from spring to ensure we never miss populating this. I think spring has onSave()

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53145)* status: 5 file(s) to review. 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53145)* status: 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53145)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53145)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 178 at r1](https://reviewable.io/reviews/harness/harness-core/53145#-Ner3R715dtsgqIkaffd:-NewIJcX2uY2-net4DzR:bhll9hl) ([raw file](https://github.com/harness/harness-core/blob/87b0ce42446b5997f37ec673af03415f1b3d9719/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L178)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

:thumbsup: 
Guava example - Hashing.murmur3\_32().hashString(input, StandardCharsets.UTF\_8).asInt();
</blockquote></details>

this is deprecated use [`murmur3_32_fixed()`](https://guava.dev/releases/snapshot/api/docs/com/google/common/hash/Hashing.html#murmur3_32_fixed())

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53145)* status: 1 change requests. 1. unresolved discussions.

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53145)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53145)* status: :shipit: complete! ✓

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger ut0

**Comment by utkarshchoubey-harness** [comment]
trigger ut0, ut1, ut2, ut5, ut9, ut6

**Comment by utkarshchoubey-harness** [comment]
ut2, ut9

**Comment by utkarshchoubey-harness** [comment]
ut2, ut9

**Comment by utkarshchoubey-harness** [comment]
ut2, ut9

**Review by AnshuH — APPROVED** [review]

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Pull request merged**
