### PR TITLE
feat: [IDP-1307]: Audit trials - OAuth config - create, update

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54495)

### CODE REVIEW

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 15 of 15 files at r1, 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54495)* status: 16 file(s) to review. 1 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/audittrails/eventhandlers/utils/OAuthEventUtils.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/54495#-NhUQWXMAMoTA1VV4wK_:-NhUQWXMAMoTA1VV4wKa:b-c1ydnu) ([raw file](https://github.com/harness/harness-core/blob/20db08a3c3bd8f1d73bfe2684b298121b7af2eba/idp-service/src/main/java/io/harness/idp/audittrails/eventhandlers/utils/OAuthEventUtils.java#L59)):*
> ```Java
> 
>     String enterpriseUrl = null;
>     if (mappedEnvVariables.get(AUTH_GITHUB_ENTERPRISE_INSTANCE_URL) != null) {
> ```

nit: we could use mappedEnvVariables.containsKey(AUTH_GITHUB_ENTERPRISE_INSTANCE_URL) instead



_Code quote:_
```Java
mappedEnvVariables.get
```
___
*[`idp-service/src/main/java/io/harness/idp/plugin/services/AuthInfoServiceImpl.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/54495#-NhURhod5sRMFZs6KUtM:-NhURhod5sRMFZs6KUtN:b-blsf4m) ([raw file](https://github.com/harness/harness-core/blob/20db08a3c3bd8f1d73bfe2684b298121b7af2eba/idp-service/src/main/java/io/harness/idp/plugin/services/AuthInfoServiceImpl.java#L81)):*
> ```Java
>       List<BackstageEnvVariable> backstageEnvVariables =
>           backstageEnvVariableService.createOrUpdate(envVariables, harnessAccount);
>       if (oldBackstageEnvVariables.size() == 0) {
> ```

nit: oldBackstageEnvVariables.isEmpty()



_Code quote:_
```Java
oldBackstageEnvVariables.size() == 0
```

**Comment by devesh-harness** [comment]
trigger uts

**Comment by devesh-harness** [comment]
trigger ut2

**Comment by devesh-harness** [comment]
trigger uts

**Comment by devesh-harness** [comment]
trigger ut4, u8

**Comment by devesh-harness** [comment]
trigger ut8

**Comment by devesh-harness** [comment]
trigger uts

**Comment by devesh-harness** [comment]
trigger uts

**Comment by devesh-harness** [comment]
trigger ut1, ut3, ut9

**Comment by devesh-harness** [comment]
trigger ut1

**Comment by devesh-harness** [comment]
trigger ut3

**Review by sandeepa-kv-jois — APPROVED** [review]

**Comment by sandeepa-kv-jois** [comment]
Going with FM as unrelated tests are failing

**Pull request merged**
