### PR TITLE
fix: [CDS-4025]: skip rollback when k8s deploy is not run

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
While performing a K8s rolling deployment, if the GitFetchFiles task fails with an exception, an empty k8s context element(with all fields null, including release number) is passed to rollback step.

This leads to the following exception when trying to fetch release history: 
> Failed to get sample-namespace/ConfigMap/null. Code: 0, message: null
> ...
> Caused by: io.kubernetes.client.openapi.ApiException: Missing the required parameter 'name' when calling readNamespacedConfigMap(Async)

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31662)

### CODE REVIEW

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31662)* status: :shipit: complete! ✓

___
*[400-rest/src/main/java/software/wings/sm/states/k8s/K8sRollingDeployRollback.java, line 133 at r2](https://reviewable.io/reviews/harness/harness-core/31662#-MypKIZK0BNkIDZTfnCv:-MypKIZL6UJzC0m6Wdpz:bfys95s) ([raw file](https://github.com/harness/harness-core/blob/ceaf219bdf513f4cf348da684a358e650c70bc51/400-rest/src/main/java/software/wings/sm/states/k8s/K8sRollingDeployRollback.java#L133)):*
> ```Java
>       ContainerInfrastructureMapping infraMapping = k8sStateHelper.fetchContainerInfrastructureMapping(context);
> 
>       if (k8sContextElement == null || isNull(k8sContextElement.getReleaseName())) {
> ```

nit: better to check for null & empty using EmptyPredicate.isEmpty(...)

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31662)* status: :shipit: complete! ✓

___
*[400-rest/src/main/java/software/wings/sm/states/k8s/K8sRollingDeployRollback.java, line 133 at r2](https://reviewable.io/reviews/harness/harness-core/31662#-MypKIZK0BNkIDZTfnCv:-MypKjEu9PO-bY9K9T_V:b-ighk6j) ([raw file](https://github.com/harness/harness-core/blob/ceaf219bdf513f4cf348da684a358e650c70bc51/400-rest/src/main/java/software/wings/sm/states/k8s/K8sRollingDeployRollback.java#L133)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: better to check for null & empty using EmptyPredicate.isEmpty(...)
</blockquote></details>

Also, we should add a test

**Comment by abhinavsingh1196** [comment]
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/K8sRollingDeployRollback.java, line 133 at r2](https://reviewable.io/reviews/harness/harness-core/31662#-MypKIZK0BNkIDZTfnCv:-MypntuLDqrymtdZoEaS:b-ulo7if) ([raw file](https://github.com/harness/harness-core/blob/ceaf219bdf513f4cf348da684a358e650c70bc51/400-rest/src/main/java/software/wings/sm/states/k8s/K8sRollingDeployRollback.java#L133)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Also, we should add a test 
</blockquote></details>

Changed to use EmptyPredicate. Test is already added.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31662)* status: :shipit: complete! ✓

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31662)* status: :shipit: complete! ✓

**Pull request merged**
