### PR TITLE
feat: [PL-38631]: Added API to update externallyManaged status of a user

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
Added an API to update the externallyManaged status for a user.
It takes the generation (CG/NG) as a param and updates the status accordingly in the given generation.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47749)

### CODE REVIEW

**Comment by shashank-harness** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 761 at r1](https://reviewable.io/reviews/harness/harness-core/47749#-NVFEQOW61GAienNme8y:-NVFEQOW61GAienNme8z:btiqekh) ([raw file](https://github.com/harness/harness-core/blob/41ca7f169bf99e5e1d204d05aa907f1175457d86/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L761)):*
> ```Java
>         ApiResponse(responseCode = "default", description = "Returns user information")
>       })
>   //  @InternalApi
> ```

uncomment

**Comment by shashank-harness** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 1067 at r1](https://reviewable.io/reviews/harness/harness-core/47749#-NVFESHV04N8W-XS9fhL:-NVFESHV04N8W-XS9fhM:b-sphfcx) ([raw file](https://github.com/harness/harness-core/blob/41ca7f169bf99e5e1d204d05aa907f1175457d86/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L1067)):*
> ```Java
> 
>   @Override
>   public UserMetadata updateUserMetadata_Privileged(UserMetadataDTO user) {
> ```

change Name to CamelCase

**Comment by shashank-harness** [comment]
*[`930-ng-core-clients/src/main/java/io/harness/user/remote/UserClient.java` line 190 at r1](https://reviewable.io/reviews/harness/harness-core/47749#-NVFEW8tBU7Rr-gdrZSj:-NVFEW8tBU7Rr-gdrZSk:bpm0ola) ([raw file](https://github.com/harness/harness-core/blob/41ca7f169bf99e5e1d204d05aa907f1175457d86/930-ng-core-clients/src/main/java/io/harness/user/remote/UserClient.java#L190)):*
> ```Java
>       @Query(value = "startTime") long startInterval, @Query(value = "endTime") long endInterval);
> 
>   @PUT(USERS_AGGREGATE_API + "/updateUserMetadata/{userId}")
> ```

we can add this to NgInviteModule which is already present in WingsModule already

**Comment by pbarapatre10** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 753 at r1](https://reviewable.io/reviews/harness/harness-core/47749#-NVFFSZQArex3yIXlWwV:-NVFFSZR8f8EhseIRMtO:b2gbca6) ([raw file](https://github.com/harness/harness-core/blob/41ca7f169bf99e5e1d204d05aa907f1175457d86/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L753)):*
> ```Java
>   @Path("updateUserMetadata/{userId}")
>   @Produces("application/json")
>   @Consumes()
> ```

minor remove these since class is already annotated with supported media type. Thanks



_Code quote:_
```Java
  @Produces("application/json")
  @Consumes()
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 1420 at r1](https://reviewable.io/reviews/harness/harness-core/47749#-NVFHoxZ4LawdJvOrDtl:-NVFHoxZ4LawdJvOrDtm:b-edr18t) ([raw file](https://github.com/harness/harness-core/blob/41ca7f169bf99e5e1d204d05aa907f1175457d86/400-rest/src/main/java/software/wings/resources/UserResource.java#L1420)):*
> ```Java
> 
>   @PUT
>   @Path("updateExternallyManaged/{userId}")
> ```

nit change it to `update-externally-managed/`



_Code quote:_
```Java
updateExternallyManaged/
```

**Comment by pbarapatre10** [comment]
*[`930-ng-core-clients/src/main/java/io/harness/user/remote/UserClient.java` line 190 at r1](https://reviewable.io/reviews/harness/harness-core/47749#-NVFEW8tBU7Rr-gdrZSj:-NVFIPBGCEiC9OjP12zZ:b2ngthx) ([raw file](https://github.com/harness/harness-core/blob/41ca7f169bf99e5e1d204d05aa907f1175457d86/930-ng-core-clients/src/main/java/io/harness/user/remote/UserClient.java#L190)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

we can add this to NgInviteModule which is already present in WingsModule already
</blockquote></details>

+1

**Review by pbarapatre10 — COMMENTED** [review]
> Reviewed 3 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47749)* status: 13 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47749)* status: 14 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 753 at r1](https://reviewable.io/reviews/harness/harness-core/47749#-NVFFSZQArex3yIXlWwV:-NVFSi5E2iFTmqNkQjTV:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/41ca7f169bf99e5e1d204d05aa907f1175457d86/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L753)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor remove these since class is already annotated with supported media type. Thanks
</blockquote></details>

Done
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 761 at r1](https://reviewable.io/reviews/harness/harness-core/47749#-NVFEQOW61GAienNme8y:-NVFSjxp7ezawLIbsmWX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/41ca7f169bf99e5e1d204d05aa907f1175457d86/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L761)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

uncomment
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 1067 at r1](https://reviewable.io/reviews/harness/harness-core/47749#-NVFESHV04N8W-XS9fhL:-NVFSks2B1ktRm_bO3uu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/41ca7f169bf99e5e1d204d05aa907f1175457d86/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L1067)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

change Name to CamelCase
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 1420 at r1](https://reviewable.io/reviews/harness/harness-core/47749#-NVFHoxZ4LawdJvOrDtl:-NVFSmJv8R1qGAOdnpVc:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/41ca7f169bf99e5e1d204d05aa907f1175457d86/400-rest/src/main/java/software/wings/resources/UserResource.java#L1420)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

nit change it to `update-externally-managed/`
</blockquote></details>

Done
___
*[`930-ng-core-clients/src/main/java/io/harness/user/remote/UserClient.java` line 190 at r1](https://reviewable.io/reviews/harness/harness-core/47749#-NVFEW8tBU7Rr-gdrZSj:-NVFSno_8IrSVtZoZOQU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/41ca7f169bf99e5e1d204d05aa907f1175457d86/930-ng-core-clients/src/main/java/io/harness/user/remote/UserClient.java#L190)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

+1 
</blockquote></details>

Done.

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger uts

**Review by shashank-harness — APPROVED** [review]
> Reviewed 4 of 13 files at r1, 9 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47749)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Comment by tiwaritejas** [comment]
trigger uts

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47749)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
