### PR TITLE
feat: [PIE-3174]: debezium service dockerization

### PR DESCRIPTION
**Pull request by shalini-agr**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31652)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 10 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31652)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Comment by shalini-agr** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31652)* status: :shipit: complete! ✓

**Pull request merged**
