### PR TITLE
[feat]: [PL-21198]: Hierarchical Resource Groups and Permissions

### PR DESCRIPTION
**Pull request by ghost**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/29968)

### CODE REVIEW

**Comment by karansiwach** [comment]
trigger compile

**Review by gupta-utkarsh — COMMENTED** [review]
> Reviewed 27 of 46 files at r1, 1 of 2 files at r2, 8 of 10 files at r3, 3 of 3 files at r4, 3 of 11 files at r5, 16 of 17 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29968)* status: 59 file(s) to review. 0 of 2 approvals obtained.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29968#-:-Mu9el2w-LqAndj5qIwX:bnfp4nl)* status: 60 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 27 of 46 files at r1, 1 of 2 files at r2, 8 of 10 files at r3, 3 of 3 files at r4, 1 of 11 files at r5, 16 of 17 files at r7, 1 of 2 files at r8, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29968)* status: 3 file(s) to review.

**Review by reetika04 — APPROVED** [review]
> Reviewed 2 of 11 files at r5, 1 of 17 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29968)* status: 1 file(s) to review.

**Review by reetika04 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29968)* status: 1 file(s) to review.

**Review by gupta-utkarsh — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29968)* status: :shipit: complete! ✓

**Pull request closed without merging**
