### PR TITLE
feat:[CDS-84547]: Harness Store Support for Serverless Aws Lambda and Values Manifest

### PR DESCRIPTION
**Pull request by piyush-bhuwalka**
## Describe your changes

Harness Store Support for Serverless Aws Lambda and Values Manifest

For more details, refer this doc:

https://harness.atlassian.net/wiki/spaces/DEV/pages/21551744043/Download+Manifest+From+Harness+Store+in+CD+Container+Step+Group

Cases Tested

- Serverless Aws Lambda Manifest in Harness Store and Values in Git
- Serverless Aws Lambda Manifest in Git and Values in Harness Store
- Both Serverless Aws Lambda Manifest and Values in Harness Store
- Both Serverless Aws Lambda Manifest and Values in Git
- Providing a folder as path for Serverless Aws Lambda Manifest
- Providing a file as path for Serverless Aws Lambda Manifest

https://github.com/harness/harness-core/assets/100153994/83a121a3-de76-4e95-a678-2be2710a42a4

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56663)

### CODE REVIEW

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Comment by piyush-bhuwalka** [comment]
trigger ut9

**Comment by piyush-bhuwalka** [comment]
trigger ut8, ut9

**Comment by piyush-bhuwalka** [comment]
trigger ut9

**Comment by piyush-bhuwalka** [comment]
trigger messagecheck

**Comment by piyush-bhuwalka** [comment]
trigger ut8

**Review by ivan-83 — APPROVED** [review]
LGTM with minor comments

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56663#-:-NlYXLs3Ak9c6KriVquL:b-z5hs9a)* status: 6 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsCommonHelper.java` line 245 at r1](https://reviewable.io/reviews/harness/harness-core/56663#-NlYVum59fwOtcsHiRR1:-NlYVum59fwOtcsHiRR2:bvj79j7) ([raw file](https://github.com/harness/harness-core/blob/c81ffbe820583a499bee972feefd0dfd01f20629/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsCommonHelper.java#L245)):*
> ```Java
>         .identifier(manifestOutcome.getIdentifier())
>         .spec(downloadHarnessStoreStepParameters)
>         .timeout(ParameterField.createValueField("10m"))
> ```

Minor: 10m should be const.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java` line 210 at r1](https://reviewable.io/reviews/harness/harness-core/56663#-NlYWghCEVYiAeKUseDb:-NlYWghCEVYiAeKUseDc:bhvjgh2) ([raw file](https://github.com/harness/harness-core/blob/c81ffbe820583a499bee972feefd0dfd01f20629/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java#L210)):*
> ```Java
>       checkForNewManifestStoreFeatureFlag(ambiance);
> 
>       if (isEmpty(((HarnessStore) storeConfig).getFiles().getValue())) {
> ```

Can this ((HarnessStore) storeConfig).getFiles() be null?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java` line 211 at r1](https://reviewable.io/reviews/harness/harness-core/56663#-NlYWUsb8hfDoG23WObN:-NlYWUsb8hfDoG23WObO:bk2139i) ([raw file](https://github.com/harness/harness-core/blob/c81ffbe820583a499bee972feefd0dfd01f20629/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java#L211)):*
> ```Java
> 
>       if (isEmpty(((HarnessStore) storeConfig).getFiles().getValue())) {
>         throw new InvalidRequestException("Atleast one harness store path needs to be specified", USER);
> ```

Minor: At least one Harness...
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java` line 603 at r1](https://reviewable.io/reviews/harness/harness-core/56663#-NlYWzmQ9_pru-iurFvF:-NlYWzmRCkvlY0xgwXka:b-vyxwg0) ([raw file](https://github.com/harness/harness-core/blob/c81ffbe820583a499bee972feefd0dfd01f20629/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java#L603)):*
> ```Java
>             AmbianceUtils.getAccountId(ambiance), FeatureName.CDS_CONTAINER_STEP_GROUP_AWS_S3_DOWNLOAD)) {
>       throw new AccessDeniedException(
>           "CDS_CONTAINER_STEP_GROUP_AWS_S3_DOWNLOAD FF is not enabled for this account. Please contact harness customer care.",
> ```

We are using the same FF for S3 and Harness Store, right?

**Comment by piyush-bhuwalka** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsCommonHelper.java` line 245 at r1](https://reviewable.io/reviews/harness/harness-core/56663#-NlYVum59fwOtcsHiRR1:-NlaVv870BSdd4nt_dj4:b-i8srqw) ([raw file](https://github.com/harness/harness-core/blob/c81ffbe820583a499bee972feefd0dfd01f20629/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsCommonHelper.java#L245)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor: 10m should be const.
</blockquote></details>

I'll make this change in the PR for https://harness.atlassian.net/browse/CDS-84546

**Comment by piyush-bhuwalka** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java` line 210 at r1](https://reviewable.io/reviews/harness/harness-core/56663#-NlYWghCEVYiAeKUseDb:-NlaWkYY-4Gs12FrAR2d:bcdct7h) ([raw file](https://github.com/harness/harness-core/blob/c81ffbe820583a499bee972feefd0dfd01f20629/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java#L210)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can this ((HarnessStore) storeConfig).getFiles() be null?
</blockquote></details>

I'll make this change in the PR for [https://harness.atlassian.net/browse/CDS-84546](https://harness.atlassian.net/browse/CDS-84546)

**Comment by piyush-bhuwalka** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java` line 211 at r1](https://reviewable.io/reviews/harness/harness-core/56663#-NlYWUsb8hfDoG23WObN:-NlaWkzs4rX4_KZq7VSw:bcdct7h) ([raw file](https://github.com/harness/harness-core/blob/c81ffbe820583a499bee972feefd0dfd01f20629/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java#L211)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor: At least one Harness...
</blockquote></details>

I'll make this change in the PR for [https://harness.atlassian.net/browse/CDS-84546](https://harness.atlassian.net/browse/CDS-84546)

**Comment by piyush-bhuwalka** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java` line 603 at r1](https://reviewable.io/reviews/harness/harness-core/56663#-NlYWzmQ9_pru-iurFvF:-NlaWoAd5fdvKZklERJC:bu6rdbu) ([raw file](https://github.com/harness/harness-core/blob/c81ffbe820583a499bee972feefd0dfd01f20629/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java#L603)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We are using the same FF for S3 and Harness Store, right?
</blockquote></details>

Yes, same Feature Flag

**Review by PragyeshMishra01 — APPROVED** [review]

**Comment by piyush-bhuwalka** [comment]
trigger review

**Pull request merged**
