### PR TITLE
[feat]: [CDS-75518]: Close the log-stream with exact key and not without the prefix so that log-service does not have to find the keys with given prefix

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Close the log-stream with exact key and not without the prefix so that log-service does not have to find the keys with given prefix. 
And finding the all keys for a given prefix was found to be problematic under high load and was causing pipeline-executions slowness and many executions were failing.

What is the change: Using the `closeStream` with exact log-key instead of `closeAllOpenStreamsWithPrefix` method by providing the prefix. Since we already know the log-key so there is not point to send the prefix and ask log-service to find all log-keys of that prefix.

Impact: I do not anticipate any impact as we are closing the required log-stream. But if it can affect anything then its logs of ShellScript step.

Testing: We have tested that logs come as it is after making this change. And on high load, it enables us to execute more pipelines concurrency without causing slowness.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51071)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51071)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptStep.java` line 183 at r1](https://reviewable.io/reviews/harness/harness-core/51071#-NaMKJ3_DrTcicj4dOUT:-NaMKJ3_DrTcicj4dOUU:b-sa6k19) ([raw file](https://github.com/harness/harness-core/blob/e8e8a8704e1e9cf3ae4405e797689276f4f4cb13/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptStep.java#L183)):*
> ```Java
>       ILogStreamingStepClient logStreamingStepClient =
>           logStreamingStepClientFactory.getLogStreamingStepClient(ambiance);
>       logStreamingStepClient.closeStream(ShellScriptTaskNG.COMMAND_UNIT);
> ```

We open other streams also here: ```io.harness.steps.shellscript.ShellScriptStep#obtainPowerShellTask```
```
List<String\> units \= Arrays.asList(WinRmShellScriptTaskNG.INIT\_UNIT, WinRmShellScriptTaskNG.COMMAND\_UNIT);
```

I think its better to create a method called getAllPossibleCommandUnits and then call
```
getAllPossibleCommandUnits.forEach*logStreamingStepClient::closeStream)
```

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51071)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51071)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptStep.java` line 183 at r1](https://reviewable.io/reviews/harness/harness-core/51071#-NaMKJ3_DrTcicj4dOUT:-NaN58gD4_hwDY5pcbAR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e8e8a8704e1e9cf3ae4405e797689276f4f4cb13/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptStep.java#L183)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We open other streams also here: ```io.harness.steps.shellscript.ShellScriptStep#obtainPowerShellTask```
```
List<String\> units \= Arrays.asList(WinRmShellScriptTaskNG.INIT\_UNIT, WinRmShellScriptTaskNG.COMMAND\_UNIT);
```

I think its better to create a method called getAllPossibleCommandUnits and then call
```
getAllPossibleCommandUnits.forEach*logStreamingStepClient::closeStream)
```
</blockquote></details>

Done.

**Pull request closed without merging**
