### PR TITLE
feat: [CDS-67866]: Changes to support step group in CD

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46851)

### CODE REVIEW

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 21 of 32 files at r1, 7 of 7 files at r2, 3 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46851)* status: 35 file(s) to review. 1 of 2 approvals obtained.

**Comment by rohitk-h** [comment]
*[`879-pipeline-ci-commons/src/main/java/io/harness/plancreator/steps/pluginstep/K8sStepGroupHandler.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/46851#-NToWoJrDqUIdK0kf9EF:-NToWoJrDqUIdK0kf9EG:bdvrk2x) ([raw file](https://github.com/harness/harness-core/blob/6373f6c44506d385995646c7af3e5106f2e27f4b/879-pipeline-ci-commons/src/main/java/io/harness/plancreator/steps/pluginstep/K8sStepGroupHandler.java#L40)):*
> ```Java
>     String initNodeId = "init-" + ctx.getCurrentField().getNode().getUuid();
> 
>     String nextNodeId = stepsField.getNode().asArray().get(0).getUuid();
> ```

I think this needs to be `String nextNodeId = stepsField.getNode().asArray().get(0).getField("step").getUuid();` ?

**Review by rohitk-h — APPROVED** [review]
> Reviewed 24 of 32 files at r1, 7 of 7 files at r2, 3 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46851)* status: :shipit: complete! ✓

**Review by rohitk-h — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46851)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — DISMISSED** [review]

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46851)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — DISMISSED** [review]
> Reviewed 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46851)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46851)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46851)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46851)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46851)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Comment by rohitk-h** [comment]
trigger smartchecks

**Comment by rohitk-h** [comment]
trigger messagecheck

**Comment by rohitk-h** [comment]
trigger messagecheck

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, 10 of 11 files at r7, 2 of 4 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46851)* status: :shipit: complete! ✓

**Review by ankittiwari-harness — APPROVED** [review]

**Review by harshjain12 — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]

**Pull request merged**
