### PR TITLE
feat: [CDS-43505]: AMI integration to Elastigroup Swimlane

### PR DESCRIPTION
**Pull request by piyush-bhuwalka**
## Describe your changes

AMI artifact Integration with Elastigroup Swimlane and some bug fixes

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39853)

### CODE REVIEW

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepCommonHelper.java` line 476 at r2](https://reviewable.io/reviews/harness/harness-core/39853#-NGRU0BH8zRABzSW334w:-NGRU0BH8zRABzSW334x:bhkc2hi) ([raw file](https://github.com/harness/harness-core/blob/03a83490557ea0c68c73a916c4e6c3821483e5cb/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepCommonHelper.java#L476)):*
> ```Java
> 
>     String image = null;
>     if (artifactOutcome.isPresent()) {
> ```

should we throw an exception if outcome is not present?

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39853)* status: 1 file(s) to review. 0 of 1 approvals obtained.

**Review by filip5rovic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39853)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepCommonHelper.java` line 229 at r4](https://reviewable.io/reviews/harness/harness-core/39853#-NHP5jZi9PtNerX3af-H:-NHP5jZi9PtNerX3af-I:b-w1mfrq) ([raw file](https://github.com/harness/harness-core/blob/aaf620492b0419ff1a4e0cc7fc9918832cccff96/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepCommonHelper.java#L229)):*
> ```Java
>     } else if (ManifestStoreType.INLINE.equals(storeConfig.getKind())) {
>       logCallback.saveExecutionLog(
>           color(format("Fetching %s from Inline Store", "elastigroup json"), LogColor.White, LogWeight.Bold));
> ```

Is `format` needed here?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepCommonHelper.java` line 477 at r4](https://reviewable.io/reviews/harness/harness-core/39853#-NHP644HC8KQKV5EWabT:-NHP644HC8KQKV5EWabU:brst5qk) ([raw file](https://github.com/harness/harness-core/blob/aaf620492b0419ff1a4e0cc7fc9918832cccff96/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepCommonHelper.java#L477)):*
> ```Java
>     if (isEmpty(image)) {
>       return stepFailureTaskResponseWithMessage(
>           unitProgressData, "AMI not available. Please specify the AMI artifact in the pipeline.");
> ```

Can we have a better message here? AMI is not specified in the pipeline, it's defined in service spec - which doesn't have to be part of the pipeline.

**Comment by piyush-bhuwalka** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepCommonHelper.java` line 477 at r4](https://reviewable.io/reviews/harness/harness-core/39853#-NHP644HC8KQKV5EWabT:-NHPct_1948f1v2wivjB:b499q7j) ([raw file](https://github.com/harness/harness-core/blob/aaf620492b0419ff1a4e0cc7fc9918832cccff96/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepCommonHelper.java#L477)):*
<details><summary><i>Previously, filip5rovic (Filip Petrovic) wrote…</i></summary><blockquote>

Can we have a better message here? AMI is not specified in the pipeline, it's defined in service spec - which doesn't have to be part of the pipeline. 
</blockquote></details>

Changed

**Comment by piyush-bhuwalka** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepCommonHelper.java` line 229 at r4](https://reviewable.io/reviews/harness/harness-core/39853#-NHP5jZi9PtNerX3af-H:-NHPcvIC25JcGLkELE5v:bk50r92) ([raw file](https://github.com/harness/harness-core/blob/aaf620492b0419ff1a4e0cc7fc9918832cccff96/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepCommonHelper.java#L229)):*
<details><summary><i>Previously, filip5rovic (Filip Petrovic) wrote…</i></summary><blockquote>

Is `format` needed here?
</blockquote></details>

Yes %s is used there, so we have to use it

**Comment by piyush-bhuwalka** [comment]
Merged to a commom branch, so closing it

**Pull request closed without merging**
