### PR TITLE
feat: [IDP-309]: Plugin APIs Integration changes

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Describe your changes
1. Plugin APIs Integration changes
2. Changed layout section to export
3. Created beans, enums for supporting export section

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45832)

### CODE REVIEW

**Comment by vigneswara-propelo** [comment]
trigger ut7

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45832)* status: 14 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/plugin/mappers/PluginDetailedInfoMapper.java` line 30 at r4](https://reviewable.io/reviews/harness/harness-core/45832#-NRlYXP7Bba0vMWDHmEA:-NRlYXP7Bba0vMWDHmEB:b-nacpr2) ([raw file](https://github.com/harness/harness-core/blob/72acbca3716e1fe22b79a56798a4f20b9172aaa7/idp-service/src/main/java/io/harness/idp/plugin/mappers/PluginDetailedInfoMapper.java#L30)):*
> ```Java
>         (appConfig != null && appConfig.isEnabled()) ? appConfig.getConfigs() : pluginInfoEntity.getConfig();
>     Exports exports = new Exports();
>     exports.setCards((int) pluginInfoEntity.getExports()
> ```

Can be made as a function and re-used for each type.

private int getExportTypeCount(List<ExportDetails> exportDetails , ExportType exportType) {
}

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45832)* status: 14 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/plugin/mappers/PluginDetailedInfoMapper.java` line 30 at r4](https://reviewable.io/reviews/harness/harness-core/45832#-NRlYXP7Bba0vMWDHmEA:-NRlbSjzCAokjpzbI51d:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/72acbca3716e1fe22b79a56798a4f20b9172aaa7/idp-service/src/main/java/io/harness/idp/plugin/mappers/PluginDetailedInfoMapper.java#L30)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Can be made as a function and re-used for each type.

private int getExportTypeCount(List<ExportDetails> exportDetails , ExportType exportType) {
}
</blockquote></details>

done

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45832)* status: 14 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/plugin/mappers/PluginDetailedInfoMapper.java` line 27 at r5](https://reviewable.io/reviews/harness/harness-core/45832#-NRhMBaERhUKfcsE_si7-r5-27:-NRli7QJCXF32R7WB8qC:b-mc5jsh) ([raw file](https://github.com/harness/harness-core/blob/2c531ba47b071078fcc04961f9e1789dcba9235e/idp-service/src/main/java/io/harness/idp/plugin/mappers/PluginDetailedInfoMapper.java#L27)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

nit: Not related to this PR - Can we use the above isEnabled instead of having the same check again?
</blockquote></details>

will change this in next PR
___
*[`idp-service/src/main/java/io/harness/idp/plugin/mappers/PluginDetailedInfoMapper.java` line 28 at r5](https://reviewable.io/reviews/harness/harness-core/45832#-NRhMBaERhUKfcsE_si7-r5-28:-NRlhmo1531tzhRSrSiS:bo02dwx) ([raw file](https://github.com/harness/harness-core/blob/2c531ba47b071078fcc04961f9e1789dcba9235e/idp-service/src/main/java/io/harness/idp/plugin/mappers/PluginDetailedInfoMapper.java#L28)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

If the plugin is disabled, should we show the config user had configured earlier or show the static config?
</blockquote></details>

valid question. let me check with the product and modify in next PR

**Review by vikyathharekal — APPROVED** [review]

**Review by sathish-soundarapandian — APPROVED** [review]
> Reviewed 7 of 11 files at r1, 1 of 1 files at r3, 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45832)* status: 14 file(s) to review. 1. unresolved discussions.

**Review by sathish-soundarapandian — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45832)* status: 14 file(s) to review. 1. unresolved discussions.

**Review by vikyathharekal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45832)* status: 14 file(s) to review.

**Review by sathish-soundarapandian — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45832)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by vikyathharekal — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45832)* status: :shipit: complete! ✓

**Review by mankrit-singh — DISMISSED** [review]
> Reviewed 7 of 11 files at r1, 1 of 1 files at r3, 5 of 5 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45832)* status: :shipit: complete! ✓

**Review by sathish-soundarapandian — APPROVED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45832)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45832)* status: :shipit: complete! ✓

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45832)* status: :shipit: complete! ✓

**Comment by vigneswara-propelo** [comment]
trigger utAll

**Pull request merged**
