### PR TITLE
[feat]: [PIE-6887]: Clean up validation events older than 14 days

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42531)

### CODE REVIEW

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42531)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service/PipelineAsyncValidationServiceImpl.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/42531#-NLZ7mlYDq7C1YrlxOwO:-NLZONPxDGIxPZyZqN8V:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/78e82be095d5e1473eb299443e9c4348170bc138/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service/PipelineAsyncValidationServiceImpl.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you set this directly in entity using @Builder.default , check nodeExecution
Reason - then you don't need to put this at each creation place and If missed records will remain forever
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42531)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42531#-:-NN02ZEQ7xe2l4tjFS9A:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42531)* status: 1 file(s) to review.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42531)* status: :shipit: complete! ✓

**Pull request merged**
