### PR TITLE
[fix]: [PIE-3142]: Resolve policy set expressions at step level

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31671)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31671)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[860-orchestration-steps/src/main/java/io/harness/steps/policy/step/PolicyStep.java, line 71 at r1](https://reviewable.io/reviews/harness/harness-core/31671#-Myp8V656fzPYJXLcGAG:-Myp8V6A0RV_q0FEEul7:b-4zd4wx) ([raw file](https://github.com/harness/harness-core/blob/fec2208cd9458045a4394d928f3add2d269b2772/860-orchestration-steps/src/main/java/io/harness/steps/policy/step/PolicyStep.java#L71)):*
> ```Java
>     List<String> policySets = new ArrayList<>();
>     for (String policySetUnresolved : policySetsUnresolved) {
>       if (NGExpressionUtils.matchesPattern(NGExpressionUtils.GENERIC_EXPRESSIONS_PATTERN, policySetUnresolved)) {
> ```

can use hasExpression method inside NGExpressionUtils



_Code quote:_
```Java
matchesPattern
```
___
*[884-pms-commons/src/main/java/io/harness/pms/expression/EngineExpressionService.java, line 16 at r1](https://reviewable.io/reviews/harness/harness-core/31671#-Myp9Uvq5WvkfKoPoMZ8:-Myp9Uvq5WvkfKoPoMZ9:b-97z2f6) ([raw file](https://github.com/harness/harness-core/blob/fec2208cd9458045a4394d928f3add2d269b2772/884-pms-commons/src/main/java/io/harness/pms/expression/EngineExpressionService.java#L16)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public interface EngineExpressionService {
>   // todo: Have a method that takes an object as input instead of string
> ```

this todo we should remove.
@hextechpal should we expose resolve in our grpc? the requirement is for policyStep has a field for they want to throw exception if unresolved for other fields they want to have null in case of unresolved, so they are putting skipevaluation annotation and rendering expression inside the step, but calling render for a list will incur many calls, so should we expose resolve or think another resolution?



_Code quote:_
```Java
// todo: Have a method that takes an object as input instead of string
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31671)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[860-orchestration-steps/src/main/java/io/harness/steps/policy/step/PolicyStep.java, line 71 at r1](https://reviewable.io/reviews/harness/harness-core/31671#-Myp8V656fzPYJXLcGAG:-MypDHd3Ek_GP-WBJYfO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fec2208cd9458045a4394d928f3add2d269b2772/860-orchestration-steps/src/main/java/io/harness/steps/policy/step/PolicyStep.java#L71)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can use hasExpression method inside NGExpressionUtils
</blockquote></details>

Done.
___
*[884-pms-commons/src/main/java/io/harness/pms/expression/EngineExpressionService.java, line 16 at r1](https://reviewable.io/reviews/harness/harness-core/31671#-Myp9Uvq5WvkfKoPoMZ8:-MypDJ-6BMktE3hQzKlv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fec2208cd9458045a4394d928f3add2d269b2772/884-pms-commons/src/main/java/io/harness/pms/expression/EngineExpressionService.java#L16)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this todo we should remove.
@hextechpal should we expose resolve in our grpc? the requirement is for policyStep has a field for they want to throw exception if unresolved for other fields they want to have null in case of unresolved, so they are putting skipevaluation annotation and rendering expression inside the step, but calling render for a list will incur many calls, so should we expose resolve or think another resolution?
</blockquote></details>

Done.

**Review by hextechpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31671)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[884-pms-commons/src/main/java/io/harness/pms/expression/EngineExpressionService.java, line 16 at r1](https://reviewable.io/reviews/harness/harness-core/31671#-Myp9Uvq5WvkfKoPoMZ8:-MypEazjEJWAGjUOC9xI:b-snhgtl) ([raw file](https://github.com/harness/harness-core/blob/fec2208cd9458045a4394d928f3add2d269b2772/884-pms-commons/src/main/java/io/harness/pms/expression/EngineExpressionService.java#L16)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yes we can expose resolve should be Easy to do in my opinion

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31671)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[884-pms-commons/src/main/java/io/harness/pms/expression/EngineExpressionService.java, line 16 at r1](https://reviewable.io/reviews/harness/harness-core/31671#-Myp9Uvq5WvkfKoPoMZ8:-MypEt9Q5V5U54jbaxPD:b-s94fpm) ([raw file](https://github.com/harness/harness-core/blob/fec2208cd9458045a4394d928f3add2d269b2772/884-pms-commons/src/main/java/io/harness/pms/expression/EngineExpressionService.java#L16)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Yes we can expose resolve should be Easy to do in my opinion
</blockquote></details>

Yes it will be easy only, just wanted to double confirm, @namanvermah lets connect on this one as well

**Comment by namanvermah** [comment]
Need to have the resolve method exposed in `EngineExpressionService` for this resolution to happen efficiently. Closing this ticket, will create another PR for this task.

**Pull request closed without merging**
