### PR TITLE
feat:[DEL-5868]: downloading delegate jar from gcp

### PR DESCRIPTION
**Pull request by bharatgoelharness**
Currently we are generating the delegate jar on runtime and coping the jar in image.
As per new requirement, we have to build the jar separately and push it in gcs. download the jar from GCS while baking the image.

With this feature customer can also bake delegate images as per their requirement when we move out these docker file our of portal.

Internal: There are 4 env as of now
pre-qa: https://qa.harness.io/public/shared/delegates/78101/delegate.jar
qa: https://qa.harness.io/public/shared/delegates/78101/delegate.jar
prod: https://app.harness.io/public/shared/delegates/78101/delegate.jar

Customer: https://app.harness.io/public/shared/delegates/78101/delegate.jar

Basically for internal we will going to update the URL on run time in build image step. That pipeline will take the delegate version as input.
And when we publish the image in prod3 at that time we will going to update the public docker file with the prod3 delegate version.

Testing:
Tested this change by creating a image and delegate jar was there in image.
We will make changes in PR pipeline and qa pipeline once this change gets merged.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43139)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43139)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`dockerization/delegate/Dockerfile` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/43139#-NMnrFnBEIs_7EH7Z7F7:-NMnrFnBEIs_7EH7Z7F8:b-7m02r9) ([raw file](https://github.com/harness/harness-core/blob/0b8d8953a430dad2b0aae976f8bbd9957bcd8d02/dockerization/delegate/Dockerfile#L71)):*
> ```Dockerfile
> ENV PATH=/opt/harness-delegate/client-tools/kustomize/v4.5.4/:$PATH
> 
> RUN curl -s -L -o delegate.jar https://app.harness.io/public/shared/delegates/78101/delegate.jar
> ```

This will break existing PR/QA pipelines

**Comment by bharatgoelharness** [comment]
> > Reviewed 2 of 2 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/43139)_ status: 1 change requests. 0 of 1 approvals obtained.
> 
> _[`dockerization/delegate/Dockerfile` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/43139#-NMnrFnBEIs_7EH7Z7F7:-NMnrFnBEIs_7EH7Z7F8:b-7m02r9) ([raw file](https://github.com/harness/harness-core/blob/0b8d8953a430dad2b0aae976f8bbd9957bcd8d02/dockerization/delegate/Dockerfile#L71)):_
> 
> > ```dockerfile
> > ENV PATH=/opt/harness-delegate/client-tools/kustomize/v4.5.4/:$PATH
> > 
> > RUN curl -s -L -o delegate.jar https://app.harness.io/public/shared/delegates/78101/delegate.jar
> > ```
> 
> This will break existing PR/QA pipelines

Yes we have updated the pipeline with previous changes and with this change also we have to update it.

**Comment by bharatgoelharness** [comment]
@raghuAtWings @mdmilic Please review and approve this change.

**Comment by bharatgoelharness** [comment]
trigger publish-delegate

**Review by mdmilic — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43139)* status: :shipit: complete! ✓

**Comment by bharatgoelharness** [comment]
trigger recency

**Pull request merged**
