### PR TITLE
feat: [CDS-34033]: add AWS ssh/winrm for instance sync

### PR DESCRIPTION
**Pull request by vitsafronovici**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36106)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36106)

**Comment by vitsafronovici** [comment]
trigger ti4

**Comment by vitsafronovici** [comment]
trigger ti4

**Comment by vitsafronovici** [comment]
trigger ti4

**Comment by vitsafronovici** [comment]
trigger ti0

**Comment by vitsafronovici** [comment]
trigger ti0

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 57 of 58 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36106)* status: 1 file(s) to review. 0 of 1 approvals obtained.

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 58 of 58 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36106)* status: :shipit: complete! ✓

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36106)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/aws/AwsSshWinrmInstanceSyncPerpetualTaskHandler.java` line 155 at r1](https://reviewable.io/reviews/harness/harness-core/36106#-N9CKX3b99vsjeIx3EhU:-N9FrUlODQilmDbIzM5t:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f999d1b08e78bd8c1a9642abf00da3587f5ad1c0/126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/aws/AwsSshWinrmInstanceSyncPerpetualTaskHandler.java#L155)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

.filterInfraTags 
</blockquote></details>

Done.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36106)* status: 1. unresolved discussions.

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36106)* status: 1. unresolved discussions. 

___
*[`126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/aws/AwsSshWinrmInstanceSyncPerpetualTaskHandler.java` line 155 at r1](https://reviewable.io/reviews/harness/harness-core/36106#-N9CKX3b99vsjeIx3EhU:-N9FrqDYEXc7e5Wj-PZS:bb7s1ad) ([raw file](https://github.com/harness/harness-core/blob/f999d1b08e78bd8c1a9642abf00da3587f5ad1c0/126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/aws/AwsSshWinrmInstanceSyncPerpetualTaskHandler.java#L155)):*
<details><summary><i>Previously, vitsafronovici (Vitalie Safronovici) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

xxxx

**Comment by vitsafronovici** [comment]
trigger ti1

**Comment by vitsafronovici** [comment]
trigger ti0

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36106)* status: :shipit: complete! ✓

**Review by arvind-choudhary-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36106)* status: :shipit: complete! ✓

**Comment by arvind-choudhary-h** [comment]
trigger codebasehash

**Review by anilchowdhury-harness — APPROVED** [review]
> Reviewed 56 of 58 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36106)* status: :shipit: complete! ✓

**Pull request merged**
