### PR TITLE
[fix]: [CDS-85972]: adding task context for helm

### PR DESCRIPTION
**Pull request by markoharness**
## Describe your changes
Created a TaskContext class to be use as a common context object during task execution.
Implementation is only for Helm task.

We are keeping infra connector info in the context object. Currently only Azure infra connector info has been implemented. For the rest of them can be done in subsequent PRs (seeing how this PR is already huge).

Screenshot 2023-12-26 at 17 31 26

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57091)

### CODE REVIEW

**Review by alebuh — COMMENTED** [review]
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57091)* status: 35 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`970-api-services-beans/src/main/java/io/harness/taskcontext/HelmTaskContext.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/57091#-NmVWeem6JHWrJSCc8OQ:-NmVWeem6JHWrJSCc8OR:b8varkw) ([raw file](https://github.com/harness/harness-core/blob/e9e675663039f60e918878bd039328a7536fd9f2/970-api-services-beans/src/main/java/io/harness/taskcontext/HelmTaskContext.java#L24)):*
> ```Java
> @CodePulse(module = ProductModule.CDS, unitCoverageRequired = true, components = {HarnessModuleComponent.CDS_K8S})
> public class HelmTaskContext implements TaskContext {
>   Set<String> hints;
> ```

Are we setting those hints anywhere in the code, or it is here just as a placeholder for the future?
___
*[`970-api-services-beans/src/main/java/io/harness/taskcontext/TaskContext.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/57091#-NmVX7Iz9pOtxn950__g:-NmVX7Iz9pOtxn950__h:b-metou9) ([raw file](https://github.com/harness/harness-core/blob/e9e675663039f60e918878bd039328a7536fd9f2/970-api-services-beans/src/main/java/io/harness/taskcontext/TaskContext.java#L19)):*
> ```Java
> 
> @CodePulse(module = ProductModule.CDS, unitCoverageRequired = false, components = {HarnessModuleComponent.CDS_K8S})
> public interface TaskContext {
> ```

if those are getter and setter methods might be better to transform this to an abstract class as I presume that all subclasses will have same implementations of those methods?

**Comment by markoharness** [comment]
*[`970-api-services-beans/src/main/java/io/harness/taskcontext/HelmTaskContext.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/57091#-NmVWeem6JHWrJSCc8OQ:-NmVmReQDWLH6poQB2PL:b-i76af2) ([raw file](https://github.com/harness/harness-core/blob/e9e675663039f60e918878bd039328a7536fd9f2/970-api-services-beans/src/main/java/io/harness/taskcontext/HelmTaskContext.java#L24)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

Are we setting those hints anywhere in the code, or it is here just as a placeholder for the future?
</blockquote></details>

No we are not. This is to be potentially used in the future.

**Comment by markoharness** [comment]
*[`970-api-services-beans/src/main/java/io/harness/taskcontext/TaskContext.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/57091#-NmVX7Iz9pOtxn950__g:-NmVp25GBIQV7-8_C9-f:bctz87m) ([raw file](https://github.com/harness/harness-core/blob/e9e675663039f60e918878bd039328a7536fd9f2/970-api-services-beans/src/main/java/io/harness/taskcontext/TaskContext.java#L19)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

if those are getter and setter methods might be better to transform this to an abstract class as I presume that all subclasses will have same implementations of those methods?
</blockquote></details>

They might, but not necessarily. I can introduce an abstract class (in addition to the interface) and if necessary these method can be overriden in the actual implementation classes.

**Review by alebuh — APPROVED** [review]

**Review by GoelPratyush99 — APPROVED** [review]

**Comment by markoharness** [comment]
trigger smartchecks

**Comment by markoharness** [comment]
trigger uts

**Comment by markoharness** [comment]
trigger review

**Comment by markoharness** [comment]
trigger ut5,ut6,ut7,u8.ut9

**Comment by markoharness** [comment]
trigger ut8

**Comment by markoharness** [comment]
trigger ut4

**Comment by markoharness** [comment]
trigger ut8

**Comment by markoharness** [comment]
trigger ut5,ut6,ut7

**Pull request merged**
