### PR TITLE
feat:[PL-40417] adding python 3.11 and 3.9 and renaming files with version

### PR DESCRIPTION
**Pull request by bharatgoelharness**
## Describe your changes
feat:[PL-40417] adding python 3.11 and 3.9 and renaming files with version

Testing:
gcr link https://console.cloud.google.com/gcr/images/platform-205701/us/harness/ubi88?project=platform-205701
Tested with 2 different input set
Screenshot 2023-07-31 at 10 40 21 PM
Screenshot 2023-07-31 at 10 40 26 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[PL-40417]: https://harness.atlassian.net/browse/PL-40417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51164)

### CODE REVIEW

**Comment by bharatgoelharness** [comment]
trigger uts

**Review by mdmilic — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51164)* status: 6 file(s) to review. 0 of 2 approvals obtained. 

___
*[`dockerization/base-images/Dockerfile-ubi-java17.0.7_7-base` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/51164#-NafTapc1kJMfpjYbwwp:-NafTapc1kJMfpjYbwwq:b-pn0h0y) ([raw file](https://github.com/harness/harness-core/blob/17c5c906f4b78a19ce037ad92ee7df0ca5b3ae87/dockerization/base-images/Dockerfile-ubi-java17.0.7_7-base#L17)):*
> ```
> 
> FROM us.gcr.io/platform-205701/harness/ubi88/ubi-base:8.8
> RUN curl -OL https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.7%2B7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.7_7.tar.gz && mkdir -p /opt/harness/OpenJDK17 && tar -xzf OpenJDK17U-jdk_x64_linux_hotspot_17.0.7_7.tar.gz -C /opt/harness/OpenJDK17 && ls -al /opt/harness/OpenJDK17/jdk-17.0.7+7 && /opt/harness/OpenJDK17/jdk-17.0.7+7/bin/java -version &&  rm -rf OpenJDK17U-jdk_x64_linux_hotspot_17.0.7_7.tar.gz
> ```

* Looking at the link I would say this is JDK not JRE. Do we intentionally bake in JDK?
* Take a look at the command we use for getting JRE to delegate (copies JRE folder from their public dockerhub image for UBI-minimal). It's simpler and during testing I found this to produce smaller image sizes for some reason.
* Consider adding [language pack](https://www.baeldung.com/linux/locale-environment-variables) to the base image. E. g for delegate we install `glibc-langpack-en` and set `ENV LANG=en_US.UTF-8`

**Comment by bharatgoelharness** [comment]
> > Reviewed 6 of 6 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/51164)_ status: 6 file(s) to review. 0 of 2 approvals obtained.
> 
> _[`dockerization/base-images/Dockerfile-ubi-java17.0.7_7-base` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/51164#-NafTapc1kJMfpjYbwwp:-NafTapc1kJMfpjYbwwq:b-pn0h0y) ([raw file](https://github.com/harness/harness-core/blob/17c5c906f4b78a19ce037ad92ee7df0ca5b3ae87/dockerization/base-images/Dockerfile-ubi-java17.0.7_7-base#L17)):_
> 
> > ```
> > 
> > FROM us.gcr.io/platform-205701/harness/ubi88/ubi-base:8.8
> > RUN curl -OL https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.7%2B7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.7_7.tar.gz && mkdir -p /opt/harness/OpenJDK17 && tar -xzf OpenJDK17U-jdk_x64_linux_hotspot_17.0.7_7.tar.gz -C /opt/harness/OpenJDK17 && ls -al /opt/harness/OpenJDK17/jdk-17.0.7+7 && /opt/harness/OpenJDK17/jdk-17.0.7+7/bin/java -version &&  rm -rf OpenJDK17U-jdk_x64_linux_hotspot_17.0.7_7.tar.gz
> > ```
> 
> * Looking at the link I would say this is JDK not JRE. Do we intentionally bake in JDK?
> * Take a look at the command we use for getting JRE to delegate (copies JRE folder from their public dockerhub image for UBI-minimal). It's simpler and during testing I found this to produce smaller image sizes for some reason.
> * Consider adding [language pack](https://www.baeldung.com/linux/locale-environment-variables) to the base image. E. g for delegate we install `glibc-langpack-en` and set `ENV LANG=en_US.UTF-8`

Yes we baked JDK for services. I think JRE should work for services too.
Improvement in dockerfiles I will take it in next PR where I will work in removing libraries which are not in use and make the image multi arch.

**Review by mdmilic — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51164)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — COMMENTED** [review]
@bharatgoelharness As discussed let's organize these files as we are organizing them in gcr

**Comment by bharatgoelharness** [comment]
trigger uts

**Comment by bharatgoelharness** [comment]
trigger uts

**Review by mdmilic — APPROVED** [review]

**Comment by bharatgoelharness** [comment]
trigger ut0

**Pull request merged**
