### PR TITLE
feat: [SRM-13159]: Refactoring SLO V2 APIs. API signature changes, Swagger changes, Request changes

### PR DESCRIPTION
**Pull request by sathish-soundarapandian**
## Describe your changes
Refactoring SLO V2 APIs. API signature changes, Swagger changes, Request changes

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41602)

### CODE REVIEW

**Review by deepak-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41602)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ProjectPathParams.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/41602#-NJJbhaE13qP0bDf1nms:-NJJbhaE13qP0bDf1nmt:bjyzev4) ([raw file](https://github.com/harness/harness-core/blob/c5b1fdab4af991a2f8870518411e5311549ee297/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ProjectPathParams.java#L34)):*
> ```Java
>   @Parameter(description = NGCommonEntityConstants.ACCOUNT_PARAM_MESSAGE)
>   @AccountIdentifier
>   @PathParam("accountIdentifier")
> ```

use : CVNextGenConstants.ACCOUNT_IDENTIFIER_KEY
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ProjectPathParams.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/41602#-NJJbmwE-yB0zRCPRRbM:-NJJbmwE-yB0zRCPRRbN:b-jg5vbs) ([raw file](https://github.com/harness/harness-core/blob/c5b1fdab4af991a2f8870518411e5311549ee297/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ProjectPathParams.java#L40)):*
> ```Java
>   @Parameter(description = NGCommonEntityConstants.ORG_PARAM_MESSAGE)
>   @OrgIdentifier
>   @PathParam("orgIdentifier")
> ```

CVNextGenConstants.ORG_IDENTIFIER_KEY
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ProjectPathParams.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/41602#-NJJbqcR0RdeaHbkcj7U:-NJJbqcR0RdeaHbkcj7V:bvk23pv) ([raw file](https://github.com/harness/harness-core/blob/c5b1fdab4af991a2f8870518411e5311549ee297/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ProjectPathParams.java#L45)):*
> ```Java
>   @Parameter(description = NGCommonEntityConstants.PROJECT_PARAM_MESSAGE)
>   @ProjectIdentifier
>   @PathParam("projectIdentifier")
> ```

CVNextGenConstants.PROJECT_IDENTIFIER_KEY

**Comment by sathish-soundarapandian** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/41602)_ status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ProjectPathParams.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/41602#-NJJbhaE13qP0bDf1nms:-NJJbhaE13qP0bDf1nmt:bjyzev4) ([raw file](https://github.com/harness/harness-core/blob/c5b1fdab4af991a2f8870518411e5311549ee297/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ProjectPathParams.java#L34)):_
> 
> > ```java
> >   @Parameter(description = NGCommonEntityConstants.ACCOUNT_PARAM_MESSAGE)
> >   @AccountIdentifier
> >   @PathParam("accountIdentifier")
> > ```
> 
> use : CVNextGenConstants.ACCOUNT_IDENTIFIER_KEY
> 
> _[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ProjectPathParams.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/41602#-NJJbmwE-yB0zRCPRRbM:-NJJbmwE-yB0zRCPRRbN:b-jg5vbs) ([raw file](https://github.com/harness/harness-core/blob/c5b1fdab4af991a2f8870518411e5311549ee297/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ProjectPathParams.java#L40)):_
> 
> > ```java
> >   @Parameter(description = NGCommonEntityConstants.ORG_PARAM_MESSAGE)
> >   @OrgIdentifier
> >   @PathParam("orgIdentifier")
> > ```
> 
> CVNextGenConstants.ORG_IDENTIFIER_KEY
> 
> _[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ProjectPathParams.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/41602#-NJJbqcR0RdeaHbkcj7U:-NJJbqcR0RdeaHbkcj7V:bvk23pv) ([raw file](https://github.com/harness/harness-core/blob/c5b1fdab4af991a2f8870518411e5311549ee297/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ProjectPathParams.java#L45)):_
> 
> > ```java
> >   @Parameter(description = NGCommonEntityConstants.PROJECT_PARAM_MESSAGE)
> >   @ProjectIdentifier
> >   @PathParam("projectIdentifier")
> > ```
> 
> CVNextGenConstants.PROJECT_IDENTIFIER_KEY

Done.

**Review by Varsha-lalwani — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41602)* status: 1. unresolved discussions.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41602)* status: :shipit: complete! ✓

**Pull request merged**
