### PR TITLE
Feat: [CDS-77217] : RBAC OPA policy and policyset onboarding (backend changes)

### PR DESCRIPTION
**Pull request by yagyanshbhatia**
## Describe your changes
This PR contains changes required in platform to onboard OPA as a specified resource type, add new permissions, and update managed roles to reflect the new permissions. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53912)

### CODE REVIEW

**Comment by AnshuH** [comment]
trigger messagecheck

**Comment by yagyanshbhatia** [comment]
trigger uts

**Comment by yagyanshbhatia** [comment]
trigger uts

**Comment by yagyanshbhatia** [comment]
trigger uts

**Comment by yagyanshbhatia** [comment]
trigger uts

**Comment by yagyanshbhatia** [comment]
trigger uts

**Comment by yagyanshbhatia** [comment]
trigger ut0, ut5, ut6, ut7

**Comment by yagyanshbhatia** [comment]
trigger ut6

**Comment by yagyanshbhatia** [comment]
trigger uts

**Comment by yagyanshbhatia** [comment]
trigger uts

**Comment by yagyanshbhatia** [comment]
trigger ut5, ut6, ut7, ut8, ut9

**Comment by yagyanshbhatia** [comment]
trigger uts

**Comment by yagyanshbhatia** [comment]
trigger uts

**Comment by yagyanshbhatia** [comment]
trigger ut5, ut6

**Comment by mohitg0795** [comment]
@yagyanshbhatia please can you add description and testing scope for this PR. Its completely blank rn.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53912)* status: 33 file(s) to review. 1 change requests. 0 of 1 approvals obtained. Waiting on team(s): build-engineering,sto,del-team. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 659 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-NncVZL8BDEJtKzXL-Su:-NncVZL8BDEJtKzXL-Sv:b-nb82d0) ([raw file](https://github.com/harness/harness-core/blob/025200f48d01573b1bfe2743635a3e9f7d42eb38/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L659)):*
> ```YAML
>       - project
>   - identifier: core_governancePolicy_edit
>     name: Create or Edit Policies
> ```

While testing please check if this gets reflected.

**Comment by mohitg0795** [comment]
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/opa/PolicyResourceImpl.java` line 58 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-NncXDqID6smMnnVqrw5:-NncXDqID6smMnnVqrw6:b-xaktov) ([raw file](https://github.com/harness/harness-core/blob/1d3df51110665c36e194a895f81da69e88eafeb2/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/opa/PolicyResourceImpl.java#L58)):*
> ```Java
>   @Override
>   public String getType() {
>     return "GOVERNANCEPOLICY";
> ```

Is it possible to use snake case here for better readability?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53912)* status: 33 file(s) to review. 2 change requests. 0 of 1 approvals obtained. Waiting on team(s): build-engineering,sto,del-team. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/opa/PolicySetResourceImpl.java` line 105 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-NncXKqJ03rN-T76z5uH:-NncXKqJ03rN-T76z5uI:b-kpntc5) ([raw file](https://github.com/harness/harness-core/blob/1d3df51110665c36e194a895f81da69e88eafeb2/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/opa/PolicySetResourceImpl.java#L105)):*
> ```Java
>       return resourceIds.stream().map(policyIdentifiers::contains).collect(Collectors.toList());
>     } catch (IOException ex) {
>       log.error("Exception while listing OPA policies", ex);
> ```

log line should be "policy sets" not policies.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53912)* status: 33 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): build-engineering,sto,del-team. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 680 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-NncVga8Dn9Y89jhRGyL:-NncVga9DMFFowQ8jFIl:bj8bld6) ([raw file](https://github.com/harness/harness-core/blob/025200f48d01573b1bfe2743635a3e9f7d42eb38/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L680)):*
> ```YAML
>       - project
>   - identifier: core_governancePolicySets_edit
>     name: Create or Edit Policy Sets
> ```

same as above.
___
*[`platform-service/config/config.yml` line 180 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-Nnc__j9DKAUE3-FcRGS:-Nnc__j9DKAUE3-FcRGT:b-avo761) ([raw file](https://github.com/harness/harness-core/blob/1d3df51110665c36e194a895f81da69e88eafeb2/platform-service/config/config.yml#L180)):*
> ```YAML
>       secret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
>     policyManagerSecret: secret
>     opaClientConfig:
> ```

Lets have consistent naming convention.
Should it be prefixed with opaPolicy?

opaPolicyClientConfig
opaPolicyManagerSecret
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/ResourceGroupModule.java` line 200 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-Nncb5U91Z03H65soamT:-Nncb5U91Z03H65soamU:b-ftx13w) ([raw file](https://github.com/harness/harness-core/blob/1d3df51110665c36e194a895f81da69e88eafeb2/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/ResourceGroupModule.java#L200)):*
> ```Java
>         resourceClients.getCeNextGen().getSecret(), RESOUCE_GROUP_SERVICE.toString(), ClientMode.PRIVILEGED));
>     install(new OpaClientModule(resourceClients.getOpaClientConfig(), resourceClients.getPolicyManagerSecret(),
>         RESOUCE_GROUP_SERVICE.toString()));
> ```

Add support  ClientMode.PRIVILEGED.  .refer other client modules.
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/opa/PolicyResourceImpl.java` line 58 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-NncXDqID6smMnnVqrw5:-Nnc_xGD660ef3CGxrJp:bda7n97) ([raw file](https://github.com/harness/harness-core/blob/1d3df51110665c36e194a895f81da69e88eafeb2/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/opa/PolicyResourceImpl.java#L58)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Is it possible to use snake case here for better readability?
</blockquote></details>

This can be GOVERNANCE_POLICY. ensure same is the resource identifier in resourceTypes.yml
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/opa/PolicySetResourceImpl.java` line 105 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-NncXKqJ03rN-T76z5uH:-NncaKMdAadzfnDFNoL7:b-o67rx8) ([raw file](https://github.com/harness/harness-core/blob/1d3df51110665c36e194a895f81da69e88eafeb2/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/opa/PolicySetResourceImpl.java#L105)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

log line should be "policy sets" not policies.
</blockquote></details>

Please test this case, how does system respond from this response?

**Review by yagyanshbhatia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53912)* status: 33 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): build-engineering,sto,del-team. 

___
*[`950-opa-client/src/main/java/io/harness/opaclient/model/PolicySetData.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-NncTupKEFBfT3PPLqdN:-NngpNTf2NfUG1CrU-sn:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/1d3df51110665c36e194a895f81da69e88eafeb2/950-opa-client/src/main/java/io/harness/opaclient/model/PolicySetData.java#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think it would be really great if we start putting fields in some logical order. eg: account id, org id and project id can be together one after another, etc.
</blockquote></details>

Done
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 659 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-NncVZL8BDEJtKzXL-Su:-Nngq7897FupTd9XRtOY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/025200f48d01573b1bfe2743635a3e9f7d42eb38/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L659)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

While testing please check if this gets reflected.
</blockquote></details>

Done.
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 680 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-NncVga8Dn9Y89jhRGyL:-Nngq7jW2XUW4YerqXvQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/025200f48d01573b1bfe2743635a3e9f7d42eb38/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L680)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

Done.
___
*[`platform-service/config/config.yml` line 180 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-Nnc__j9DKAUE3-FcRGS:-NngqWOL8qwXR0m1h-Z3:b-auhwfm) ([raw file](https://github.com/harness/harness-core/blob/1d3df51110665c36e194a895f81da69e88eafeb2/platform-service/config/config.yml#L180)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Lets have consistent naming convention.
Should it be prefixed with opaPolicy?

opaPolicyClientConfig
opaPolicyManagerSecret
</blockquote></details>

OPA and policy-mgmt service are both names for the same service, often used interchangeably. Although these variables seem inconsistent, they're consistent with the similar variables used in PMS and other services. Later, we can take it up as an enhancement across services though!
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/ResourceGroupModule.java` line 200 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-Nncb5U91Z03H65soamT:-Nngrwmm1hKUc7beRL5P:b72gwoy) ([raw file](https://github.com/harness/harness-core/blob/1d3df51110665c36e194a895f81da69e88eafeb2/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/ResourceGroupModule.java#L200)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Add support  ClientMode.PRIVILEGED.  .refer other client modules.
</blockquote></details>

OpaClientModule currently uses NON PRIVILEGED only across services, this is because we're using getSafeOkHttpClient instead of getUnsafeOkHttpClient where clientMode is specified.
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/opa/PolicyResourceImpl.java` line 58 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-NncXDqID6smMnnVqrw5:-NngszoD7_HtgFjSQLV2:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/1d3df51110665c36e194a895f81da69e88eafeb2/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/opa/PolicyResourceImpl.java#L58)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

This can be GOVERNANCE_POLICY. ensure same is the resource identifier in resourceTypes.yml
</blockquote></details>

Done
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/opa/PolicySetResourceImpl.java` line 105 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-NncXKqJ03rN-T76z5uH:-Nngv4B6EHO4aboKOr8D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1d3df51110665c36e194a895f81da69e88eafeb2/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/opa/PolicySetResourceImpl.java#L105)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Please test this case, how does system respond from this response?
</blockquote></details>

Done.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 10 of 29 files at r1, 5 of 5 files at r2, 14 of 15 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53912)* status: 1 change requests. 1. unresolved discussions. Waiting on team(s): build-engineering,sto,del-team.

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53912)* status: 1 change requests. 1. unresolved discussions. Waiting on team(s): build-engineering,sto,del-team. 

___
*[`950-opa-client/src/main/java/io/harness/opaclient/model/PolicySetData.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-NncTupKEFBfT3PPLqdN:-NnhnCUaDzHKwK1SYgWe:b-icjnfr) ([raw file](https://github.com/harness/harness-core/blob/1d3df51110665c36e194a895f81da69e88eafeb2/950-opa-client/src/main/java/io/harness/opaclient/model/PolicySetData.java#L29)):*
<details><summary><i>Previously, yagyanshbhatia (Yagyansh Bhatia) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Ideally it would have been great to have first account id, then org, then project, then rest of the params in most logical fashion. Currently, the order is still bit jumbled up.

PS: Its a non blocking comment anyways

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53912)* status: 1 change requests. 1. unresolved discussions. Waiting on team(s): build-engineering,sto,del-team. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/opa/PolicySetResourceImpl.java` line 105 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-NncXKqJ03rN-T76z5uH:-NnhnQGN1GjW2DTUGbUj:bjuounb) ([raw file](https://github.com/harness/harness-core/blob/1d3df51110665c36e194a895f81da69e88eafeb2/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/opa/PolicySetResourceImpl.java#L105)):*
<details><summary><i>Previously, yagyanshbhatia (Yagyansh Bhatia) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please try to use same identifier string for logs. eg: Somewhere you're using "policySet", somewhere you're using "policy-sets". These things will increase difficulty to debug in case of issues.

**Review by yagyanshbhatia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53912)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): build-engineering,sto,del-team. 

___
*[`950-opa-client/src/main/java/io/harness/opaclient/model/PolicySetData.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-NncTupKEFBfT3PPLqdN:-NniWJiE1oq5ISdekft_:b-xnsbxq) ([raw file](https://github.com/harness/harness-core/blob/1d3df51110665c36e194a895f81da69e88eafeb2/950-opa-client/src/main/java/io/harness/opaclient/model/PolicySetData.java#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Ideally it would have been great to have first account id, then org, then project, then rest of the params in most logical fashion. Currently, the order is still bit jumbled up.

PS: Its a non blocking comment anyways
</blockquote></details>

`Boolean enabled;  
String account\_id;  
String project\_id;  
String org\_id;  
String action;  
String entity\_selector;  
String identifier;  
String name;  
String type;  
long created;  
long updated;  
List<PolicyData> policies;`
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/opa/PolicySetResourceImpl.java` line 105 at r4](https://reviewable.io/reviews/harness/harness-core/53912#-NncXKqJ03rN-T76z5uH:-NniW-fU-8bMwELh3bwx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1d3df51110665c36e194a895f81da69e88eafeb2/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/opa/PolicySetResourceImpl.java#L105)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Please try to use same identifier string for logs. eg: Somewhere you're using "policySet", somewhere you're using "policy-sets". These things will increase difficulty to debug in case of issues.
</blockquote></details>

Done.

**Comment by yagyanshbhatia** [comment]
trigger uts

**Comment by yagyanshbhatia** [comment]
trigger ut5

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53912)* status: 12 file(s) to review. Waiting on team(s): build-engineering,sto,del-team.

**Comment by yagyanshbhatia** [comment]
trigger ut5

**Comment by yagyanshbhatia** [comment]
trigger ut5, reviewcheck

**Comment by yagyanshbhatia** [comment]
trigger review

**Comment by yagyanshbhatia** [comment]
trigger uts

**Comment by yagyanshbhatia** [comment]
trigger review

**Review by Jimit09Gandhi — APPROVED** [review]

**Pull request merged**
