### PR TITLE
fix: [SRM-14506]: Added scoped Identifiers for evaluation type calculation

### PR DESCRIPTION
**Pull request by arpit-harness**
…tion

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46189)

### CODE REVIEW

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46189)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 816 at r1](https://reviewable.io/reviews/harness/harness-core/46189#-NSMvt0XAqSNZ5tkz6Vm:-NSMvt0XAqSNZ5tkz6Vn:b-ey5svq) ([raw file](https://github.com/harness/harness-core/blob/b06c426e9443cecc83a0b76035e49900612f5c50/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L816)):*
> ```Java
>           ScopedInformation.getScopedInformation(simpleServiceLevelObjective.getAccountId(),
>               simpleServiceLevelObjective.getOrgIdentifier(), simpleServiceLevelObjective.getProjectIdentifier(),
>               simpleServiceLevelObjective.getServiceLevelIndicators().get(0)),
> ```

write a method for this as well as it is duplicated in other places



_Code quote:_
```Java
          ScopedInformation.getScopedInformation(simpleServiceLevelObjective.getAccountId(),
              simpleServiceLevelObjective.getOrgIdentifier(), simpleServiceLevelObjective.getProjectIdentifier(),
              simpleServiceLevelObjective.getServiceLevelIndicators().get(0)),
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 855 at r1](https://reviewable.io/reviews/harness/harness-core/46189#-NSMwYff5fBRSEtiRZHv:-NSMwYff5fBRSEtiRZHw:byow1ta) ([raw file](https://github.com/harness/harness-core/blob/b06c426e9443cecc83a0b76035e49900612f5c50/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L855)):*
> ```Java
>   private List<SimpleServiceLevelObjective> getSimpleServiceLevelObjective(
>       ProjectParams projectParams, List<AbstractServiceLevelObjective> serviceLevelObjectiveList) {
>     Map<String, ServiceLevelObjectivesDetail> scopedIdentifierToServiceLevelObjectiveRefSet = new HashMap<>();
> ```

RefMap



_Code quote:_
```Java
RefSet
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImplTest.java` line 1765 at r1](https://reviewable.io/reviews/harness/harness-core/46189#-NSMxGKi2vttQ5lxED08:-NSMxGKi2vttQ5lxED09:b-2axpoj) ([raw file](https://github.com/harness/harness-core/blob/6415df069167705e215c90890a5dd2bc59f93d38/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImplTest.java#L1765)):*
> ```Java
>         ProjectParams.builder().accountIdentifier(projectParams.getAccountIdentifier()).build();
>     List<AbstractServiceLevelObjective> serviceLevelObjectiveList = serviceLevelObjectiveV2Service.getWithChildResource(
>         accountProjectParams, Collections.singletonList(sloDTO.getIdentifier()));
> ```

Can you add UT for the scenario for which the issue occured



_Code quote:_
```Java
    ProjectParams accountProjectParams =
        ProjectParams.builder().accountIdentifier(projectParams.getAccountIdentifier()).build();
    List<AbstractServiceLevelObjective> serviceLevelObjectiveList = serviceLevelObjectiveV2Service.getWithChildResource(
        accountProjectParams, Collections.singletonList(sloDTO.getIdentifier()));
```

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46189#-:-NSPr01DCBc6HveNvVuq:bnfp4nl)* status: :shipit: complete! ✓

**Comment by arpit-harness** [comment]
trigger messagecheck

**Review by deepak-harness — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46189)* status: :shipit: complete! ✓

**Pull request merged**
