### PR TITLE
[feat]: [CDS-33893]: generate yaml snippet for ssh service

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35812)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35812)

**Comment by vladimir-peric** [comment]
trigger ti0

**Comment by vladimir-peric** [comment]
trigger ti0

**Comment by vladimir-peric** [comment]
trigger ti0

**Review by acasian-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 55 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35812)* status: 47 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineConfigurationHelper.java` line 135 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x61iyChTIJ0BPyrey:-N8x61iyChTIJ0BPyrez:b7q9i5m) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineConfigurationHelper.java#L135)):*
> ```Java
>     try (StringWriter stringWriter = new StringWriter()) {
>       ClassLoader classLoader = this.getClass().getClassLoader();
>       String failureStrategiesSnippet = Resources.toString(
> ```

we need to load those only once, not everytime we hit the request



_Code quote:_
```Java
CDNGPipelineConfigurationHelper
```
___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/kubernetes-bluegreen-with-verify.yaml` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x6lzI-YAYkr_z8pAr:-N8x6lzI-YAYkr_z8pAs:b3x0ar5) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/kubernetes-bluegreen-with-verify.yaml#L1)):*
> ```YAML
>     failureStrategies:
> ```

why are we changing this one?
___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-basic.yaml` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x6wn802BY2Q6AL-m0:-N8x6wn802BY2Q6AL-m1:buuwhdx) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-basic.yaml#L25)):*
> ```YAML
>                 type: Script
>                 spec:
>                   workingDirectory: <+HARNESS_RUNTIME_PATH>
> ```

this is invalid, in bash it is used with `$`, for powershell as %%



_Code quote:_
```YAML
<+HARNESS_RUNTIME_PATH>
```
___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-basic.yaml` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x7kwk9zdtbE08Vl6-:-N8x7kwk9zdtbE08Vl60:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-basic.yaml#L74)):*
> ```YAML
>                 spec:
>                   sourceType: Config
>                   destinationPath: <+HARNESS_RUNTIME_PATH>
> ```

same
___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-basic.yaml` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x7mR-At1Zuwub_uc4:-N8x7mR-At1Zuwub_uc5:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-basic.yaml#L90)):*
> ```YAML
>                 type: Script
>                 spec:
>                   workingDirectory: <+HARNESS_RUNTIME_PATH>
> ```

same
___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary.yaml` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x7v4W-1SQMi7TXEi3:-N8x7v4W-1SQMi7TXEi4:bfb2885) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary.yaml#L15)):*
> ```YAML
>           strategy:
>             repeat:
>               items: <+instances>
> ```

can we have those as `<+stage.output.hosts>`? How was this tested? this will never successfully execute...
___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary.yaml` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x8G039GCI5vh7vMY_:-N8x8G04-j3PmtfcKSdo:b-4use4h) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary.yaml#L47)):*
> ```YAML
>                 timeout: 10m
>                 spec:
>                   host: <+repeat.items>
> ```

it is `<+repeat.item>`
___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary.yaml` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x8WBq7SPHOAupUQ_B:-N8x8WBq7SPHOAupUQ_C:b-wdnqf5) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary.yaml#L57)):*
> ```YAML
>                       spec:
>                         shell: Bash
>                         workingDirectory: <+HARNESS_RUNTIME_PATH>
> ```

same, $ instead of <+
___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary-with-verify.yaml` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8xCKujC-dPnD74Uykm:-N8xCKujC-dPnD74Uykn:b5o8vt) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary-with-verify.yaml#L47)):*
> ```YAML
>                 timeout: 10m
>                 spec:
>                   host: <+repeat.items>
> ```

same issue, in some place it is correct in other not, pls be carrefull here
___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-rolling.yaml` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8xCYGXEkCO7vc5pvAt:-N8xCYGY-oNaUC1uMD2F:b-h3ztl6) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-rolling.yaml#L56)):*
> ```YAML
>                       spec:
>                         shell: Bash
>                         workingDirectory: <+HARNESS_RUNTIME_PATH>
> ```

same, this should be fixed in all the places

**Comment by vladimir-peric** [comment]
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/kubernetes-bluegreen-with-verify.yaml` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x6lzI-YAYkr_z8pAr:-N8xULbsBVRlpzNKim65:bpv2thr) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/kubernetes-bluegreen-with-verify.yaml#L1)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

why are we changing this one?
</blockquote></details>

Removing this change, a typo

**Comment by vladimir-peric** [comment]
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary.yaml` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x7v4W-1SQMi7TXEi3:-N8xUtpdCVGgr2HiyeMn:b-dsa93w) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary.yaml#L15)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

can we have those as `<+stage.output.hosts>`? How was this tested? this will never successfully execute...
</blockquote></details>

This snippet is used by the GET api, that's why it wen't unnoticed. Correcting it.

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35812)* status: 54 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-basic.yaml` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x6wn802BY2Q6AL-m0:-N8xS_5E-fs990faeWM2:b-joqehr) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-basic.yaml#L25)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

this is invalid, in bash it is used with `$`, for powershell as %%
</blockquote></details>

I thought this is a runtime env.

**Comment by vladimir-peric** [comment]
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/kubernetes-bluegreen-with-verify.yaml` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x6lzI-YAYkr_z8pAr:-N8xpXZc-TkPaWmvdUcT:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/kubernetes-bluegreen-with-verify.yaml#L1)):*
<details><summary><i>Previously, vladimir-peric (Vladimir Peric) wrote…</i></summary><blockquote>

Removing this change, a typo
</blockquote></details>

Done

**Comment by vladimir-peric** [comment]
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-basic.yaml` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x6wn802BY2Q6AL-m0:-N8xpaMz2vGWyp8EzXs-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-basic.yaml#L25)):*
<details><summary><i>Previously, vladimir-peric (Vladimir Peric) wrote…</i></summary><blockquote>

I thought this is a runtime env. 
</blockquote></details>

Done.

**Comment by vladimir-peric** [comment]
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary.yaml` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x7v4W-1SQMi7TXEi3:-N8xpfTs3P6szm68RemL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary.yaml#L15)):*
<details><summary><i>Previously, vladimir-peric (Vladimir Peric) wrote…</i></summary><blockquote>

This snippet is used by the GET api, that's why it wen't unnoticed. Correcting it.
</blockquote></details>

Done.

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35812)* status: 54 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineConfigurationHelper.java` line 135 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x61iyChTIJ0BPyrey:-N8xpVlzCHGTn-mHFJuK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineConfigurationHelper.java#L135)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

we need to load those only once, not everytime we hit the request
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-basic.yaml` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x7kwk9zdtbE08Vl6-:-N8xpddvBoNC9Qfkn1kg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-basic.yaml#L74)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-basic.yaml` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x7mR-At1Zuwub_uc4:-N8xpeM01p6bmld58Ks2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-basic.yaml#L90)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary.yaml` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x8G039GCI5vh7vMY_:-N8xphdv81CeJjKD_RYG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary.yaml#L47)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

it is `<+repeat.item>`
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary.yaml` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8x8WBq7SPHOAupUQ_B:-N8xphzY4pniT-wAyZDE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary.yaml#L57)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

same, $ instead of <+
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary-with-verify.yaml` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8xCKujC-dPnD74Uykm:-N8xpint9BPzKk34OjJu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-canary-with-verify.yaml#L47)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

same issue, in some place it is correct in other not, pls be carrefull here
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-rolling.yaml` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/35812#-N8xCYGXEkCO7vc5pvAt:-N8xpjN4-8KuYHa2mAzp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ab8cf8a6540514015977a9cd9c46b739405361e/125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-rolling.yaml#L56)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

same, this should be fixed in all the places
</blockquote></details>

Done.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 7 of 62 files at r1, 3 of 53 files at r2, 3 of 5 files at r3, 15 of 62 files at r4, 44 of 49 files at r5, 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35812)* status: :shipit: complete! ✓

**Pull request merged**
