### PR TITLE
[fix]: [CDS-59179]: log warning if chart name is input expression for helm chart manifest

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes
Logging a warning if chart name is input expression for helm chart manifest for non-git and non-harness store types.
Screenshot 2023-05-18 at 3 40 09 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48019)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/HelmChartManifest.java` line 192 at r2](https://reviewable.io/reviews/harness/harness-core/48019#-NVilBD3Ac5ErdZy97Xt:-NVilBD3Ac5ErdZy97Xu:b-cwc67w) ([raw file](https://github.com/harness/harness-core/blob/15a924c04995414539546f71e7cc37d5283803d7/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/HelmChartManifest.java#L192)):*
> ```Java
>       invalidParameters.addAll(storeConfig.validateAtRuntime());
>     }
>     if (!isInstanceOf(GitStoreConfig.class, storeConfig) && !isInstanceOf(HarnessStoreConfig.class, storeConfig)) {
> ```

can we do if storeConfig.getStoreType.isGitBased()

You would need to create a new method isGitBased() in the enum `StoreConfigType`

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48019)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by lovish1999** [comment]
trigger uts

**Comment by tchaurasiya** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/HelmChartManifest.java` line 191 at r3](https://reviewable.io/reviews/harness/harness-core/48019#-NW1lK_uBLBkFk8ltcYs:-NW1lK_uBLBkFk8ltcYt:b-b6mj6r) ([raw file](https://github.com/harness/harness-core/blob/eef3f4f7b8185f7663a0249ee47bf5248a20d0fd/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/HelmChartManifest.java#L191)):*
> ```Java
>       invalidParameters.addAll(storeConfig.validateAtRuntime());
>     }
>     if (!(ManifestStoreType.isInGitSubset(storeConfig.getKind()))
> ```

This code should be null guarded.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48019)* status: 1 file(s) to review. 0 of 2 approvals obtained.

**Comment by lovish1999** [comment]
trigger uts

**Review by lovish1999 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48019)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/HelmChartManifest.java` line 191 at r3](https://reviewable.io/reviews/harness/harness-core/48019#-NW1lK_uBLBkFk8ltcYs:-NW70_Io0zcildB99Te1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eef3f4f7b8185f7663a0249ee47bf5248a20d0fd/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/HelmChartManifest.java#L191)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

This code should be null guarded.
</blockquote></details>

Done.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48019)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48019)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
