### PR TITLE
feat:[CDS-54222]: Support for Freeze account/org level for Environments and Services

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
Support for Freeze account/org level for Environments and Services

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44468)

### CODE REVIEW

**Comment by RishabhGupta34** [comment]
trigger ut2

**Comment by RishabhGupta34** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/steps/EnvironmentStep.java` line 111 at r3](https://reviewable.io/reviews/harness/harness-core/44468#-NQxNLxKAa_sdOWci3WU:-NQxNLxKAa_sdOWci3WV:b-xjua8f) ([raw file](https://github.com/harness/harness-core/blob/403c98d691d52dfe8d48bdf5ff7fa30a8036e107/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/steps/EnvironmentStep.java#L111)):*
> ```Java
>   @VisibleForTesting
>   protected String getEnviromentRef(
>       EnvironmentYaml environmentYaml, ParameterField<String> environmentRef, EnvironmentOutcome environmentOutcome) {
> ```

what is the value of environmentOutcome.getIdentifier() in case of org/account scoped environment ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44468)* status: 7 file(s) to review. 0 of 2 approvals obtained.

**Comment by RishabhGupta34** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/steps/EnvironmentStep.java` line 111 at r3](https://reviewable.io/reviews/harness/harness-core/44468#-NQxNLxKAa_sdOWci3WU:-NQxbWuJ2fW-iuhygn38:b-vka4dv) ([raw file](https://github.com/harness/harness-core/blob/403c98d691d52dfe8d48bdf5ff7fa30a8036e107/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/steps/EnvironmentStep.java#L111)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

what is the value of environmentOutcome.getIdentifier() in case of org/account scoped environment ?
</blockquote></details>

it contains only identifier, without the scope

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44468)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44468)* status: :shipit: complete! ✓

**Pull request merged**
