### PR TITLE
fix: [CDS-84968]: removes ngaccesscontrolcheck annotion, adds custom accesscontrolcheck

### PR DESCRIPTION
**Pull request by sandeshsalunkhegh**
fix: [CDS-84968]: removes ngaccesscontrolcheck annotion, adds custom accesscontrolcheck within the ExecutionDetailsResource#getExecutions API

### Issue:
With ExecutionDetailsResource#getExecutions API, the only required fields were accountIdentifier and planExecutionId, still with the ngaccesscontrolcheck annotion, it was checking for accountIdentifier, organisationIdentifier, projectIdentifier which was resulting in the request turning out to be unauthorised if a user with `PIPELINE_VIEW` permissions was trying to get compiled YAML for an execution.

### Changes:
Added custom accesscontrolcheck which checks for the access within the API and not before the API, which enables to retrieve the missing data - accountIdentifier, organisationIdentifier, projectIdentifier. Thus, performing the authorisation appropriately.

### Testing:
Added unit tests, and tested user scenarios locally.
Scenario: User has `PIPELINE_VIEW` permission for a project, and tries to retrieve the compiled YAML for an execution within that project.
Earlier response:
```json
{
    "status": "ERROR",
    "code": "NG_ACCESS_DENIED",
    "message": "Principal of type USER with identifier BnTbQTIJS4SkadzYv0BcbA : Missing permission core_pipeline_view on pipeline",
    "correlationId": null,
    "detailedMessage": null,
    "responseMessages": null,
    "metadata": null,
    "failedPermissionChecks": [
        {
            "resourceScope": {
                "accountIdentifier": "kmpySmUISimoRrJL6NL73w"
            },
            "resourceType": "PIPELINE",
            "resourceAttributes": null,
            "resourceIdentifier": null,
            "permission": "core_pipeline_view"
        }
    ]
}
```

Response after the change:

```json
{
    "status": "SUCCESS",
    "data": {
        "executionId": "7S4BvhGkSEK9dilcCwnjMg",
        "executionYaml": "pipeline:\n  identifier: CDS84727\n  projectIdentifier: Project_1\n  orgIdentifier: default\n  tags: {}\n  stages:\n    - stage:\n        identifier: test\n        name: test\n        type: Custom\n        spec:\n          execution:\n            steps:\n              - step:\n                  type: ShellScript\n                  name: ShellScript_1\n                  identifier: ShellScript_1\n                  spec:\n                    shell: Bash\n                    onDelegate: true\n                    source:\n                      type: Inline\n                      spec:\n                        script: |-\n                          echo <+template.tags>\n                          echo <+template.description>\n                          echo <+org.tags>\n                          echo <+org.description>\n                          echo <+stage.tags>\n                          echo <+stage.description>\n                          echo <+project.tags>\n                          echo <+project.description>\n                    environmentVariables: []\n                    outputVariables: []\n                  timeout: 10m\n        variables:\n          - name: test1\n            type: String\n            description: test1\n            required: false\n            value: test1\n        timeout: 2m\n        delegateSelectors:\n          - localdelegate\n        when:\n          pipelineStatus: Success\n  name: CDS-84727\n"
    },
    "metaData": null,
    "correlationId": "753e8beb-15c3-4bc7-8d21-f194c2ecfb2b"
}
```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-84968]: https://harness.atlassian.net/browse/CDS-84968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56064)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 514 at r2](https://reviewable.io/reviews/harness/harness-core/56064#-NkOLNicA5EalTvfc4is:-NkOLNicA5EalTvfc4it:b-6hxhdb) ([raw file](https://github.com/harness/harness-core/blob/1fa21a99034e9090a0a4b7d067fa749841a82e70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L514)):*
> ```Java
>       @NotNull @PathParam(NGCommonEntityConstants.PLAN_KEY) @Parameter(
>           description = "ExecutionId of the execution for which we want to get Metadata") String planExecutionId) {
>     PipelineExecutionSummaryEntity pipelineExecutionSummaryEntity =
> ```

Please use getPipelineExecutionSummaryWithProjections from PmsExecutionSummaryService here and only fetch account, org , projectId and pipelineIdentifier from there.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 520 at r2](https://reviewable.io/reviews/harness/harness-core/56064#-NkOLZn4BuQ5TEzE9HF4:-NkOLZn4BuQ5TEzE9HF5:bp3uhs1) ([raw file](https://github.com/harness/harness-core/blob/1fa21a99034e9090a0a4b7d067fa749841a82e70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L520)):*
> ```Java
>             pipelineExecutionSummaryEntity.getProjectIdentifier()),
>         Resource.of(PIPELINE_RESOURCE_TYPE, pipelineExecutionSummaryEntity.getPipelineIdentifier()),
>         PipelineRbacPermissions.PIPELINE_VIEW, UNAUTHORIZED_TO_LIST_ENVIRONMENTS_MESSAGE);
> ```

This error message is wrong, we should throw proper error message.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 588 at r2](https://reviewable.io/reviews/harness/harness-core/56064#-NkOLfCG0PKLEWDruj4f:-NkOLfCG0PKLEWDruj4g:b7pbuqy) ([raw file](https://github.com/harness/harness-core/blob/1fa21a99034e9090a0a4b7d067fa749841a82e70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L588)):*
> ```Java
>       String accountId, String orgId, String projectId, String planExecutionId) {
>     Optional<PipelineExecutionSummaryEntity> pipelineExecutionSummaryEntityOptional;
>     if (EmptyPredicate.isEmpty(accountId) || EmptyPredicate.isEmpty(orgId) || EmptyPredicate.isEmpty(projectId)) {
> ```

This should not be required if we use the suggested function above

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56064)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by sandeshsalunkhegh — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56064)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 514 at r2](https://reviewable.io/reviews/harness/harness-core/56064#-NkOLNicA5EalTvfc4is:-NkPetAU2LhcuQo0iB9Y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fa21a99034e9090a0a4b7d067fa749841a82e70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L514)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Please use getPipelineExecutionSummaryWithProjections from PmsExecutionSummaryService here and only fetch account, org , projectId and pipelineIdentifier from there.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 520 at r2](https://reviewable.io/reviews/harness/harness-core/56064#-NkOLZn4BuQ5TEzE9HF4:-NkPetf0C6SkTl2fRDVk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fa21a99034e9090a0a4b7d067fa749841a82e70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L520)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

This error message is wrong, we should throw proper error message.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 588 at r2](https://reviewable.io/reviews/harness/harness-core/56064#-NkOLfCG0PKLEWDruj4f:-NkPez1d7wLXk31wsDXr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fa21a99034e9090a0a4b7d067fa749841a82e70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L588)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

This should not be required if we use the suggested function above
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 517 at r4](https://reviewable.io/reviews/harness/harness-core/56064#-NkTfmIa6xR69zTPZEBd:-NkTfmIa6xR69zTPZEBe:b-se86c) ([raw file](https://github.com/harness/harness-core/blob/4ae1d1adb2fc565999a6ac5598f473756b9e4a19/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L517)):*
> ```Java
>     PipelineExecutionSummaryEntity pipelineExecutionSummaryEntity =
>         pmsExecutionSummaryService.getPipelineExecutionSummaryWithProjections(
>             planExecutionId, Set.of("accountIdentifier", "organizationIdentifier", "projectIdentifier"));
> ```

nit: use constants

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 520 at r2](https://reviewable.io/reviews/harness/harness-core/56064#-NkOLZn4BuQ5TEzE9HF4:-NkTfuMdCr2IBSeSorwT:b8olgv9) ([raw file](https://github.com/harness/harness-core/blob/1fa21a99034e9090a0a4b7d067fa749841a82e70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L520)):*
<details><summary><i>Previously, sandeshsalunkhegh (Sandesh Salunkhe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is still wrong, could you please post the screenshot of what error are we getting?

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56064)* status: 4 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 148 at r4](https://reviewable.io/reviews/harness/harness-core/56064#-NkTiulp5sfL30a8Mm1g:-NkTiulqCxhwRlD1Hx9-:b-ectjqy) ([raw file](https://github.com/harness/harness-core/blob/4ae1d1adb2fc565999a6ac5598f473756b9e4a19/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L148)):*
> ```Java
>       "Please Verify Executions list parameters for page and size, page should be >= 0 and size should be > 0 and <=1000";
>   private final String PIPELINE_RESOURCE_TYPE = "PIPELINE";
>   private final String UNAUTHORIZED_TO_LIST_ENVIRONMENTS_MESSAGE = "Missing permission %s on %s";
> ```

is the variable name correct?



_Code quote:_
```Java
UNAUTHORIZED_TO_LIST_ENVIRONMENTS_MESSAGE
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 517 at r4](https://reviewable.io/reviews/harness/harness-core/56064#-NkTiO_K0vSyBuhjBmPN:-NkTiO_K0vSyBuhjBmPO:b-x16jez) ([raw file](https://github.com/harness/harness-core/blob/4ae1d1adb2fc565999a6ac5598f473756b9e4a19/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L517)):*
> ```Java
>     PipelineExecutionSummaryEntity pipelineExecutionSummaryEntity =
>         pmsExecutionSummaryService.getPipelineExecutionSummaryWithProjections(
>             planExecutionId, Set.of("accountIdentifier", "organizationIdentifier", "projectIdentifier"));
> ```

there is accountId and not accountIdentifier, did we test post these changes?



_Code quote:_
```Java
accountIdentifier
```

**Comment by sandeshsalunkhegh** [comment]
Tested on Local - both valid and invalid scenarios

https://github.com/harness/harness-core/assets/22246973/e6076706-04fe-40c3-8895-05ff1e77e221

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 148 at r7](https://reviewable.io/reviews/harness/harness-core/56064#-NkUvjR78x2RdNp6W5Y0:-NkUvjR78x2RdNp6W5Y1:bbkdsq1) ([raw file](https://github.com/harness/harness-core/blob/6940e0239ce7278be499b08978d40aabdf312139/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L148)):*
> ```Java
>       "Please Verify Executions list parameters for page and size, page should be >= 0 and size should be > 0 and <=1000";
>   private final String PIPELINE_RESOURCE_TYPE = "PIPELINE";
>   private final String PERMISSION_MISSING_MESSAGE = "Missing permission %s on %s";
> ```

Lets add account, org and project id in the message.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56064)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56064)* status: 1. unresolved discussions.

**Pull request merged**
