### PR TITLE
fix: [BT-873]: More easily handle changes to allowed Jira projects

### PR DESCRIPTION
**Pull request by mbatchelor**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30955)

### CODE REVIEW

**Comment by mbatchelor** [comment]
Note - it was unclear to me whether the scripts folder would be available to the commit-msg.sh script file, so I made two jira-projects.txt files, one in toolset/githooks and one in scripts/jenkins. This was on purpose in case when the commit-msg.sh executes, it doesn't have scripts/jenkins folder available.

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30955)* status: :shipit: complete! ✓

**Comment by mbatchelor** [comment]
trigger ti0

**Comment by mbatchelor** [comment]
trigger ti1

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 10 of 10 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30955)* status: :shipit: complete! ✓

**Comment by mbatchelor** [comment]
Too much back-and-forth on this. Closing PR and opening a new one.

**Pull request closed without merging**
