### PR TITLE
techdebt: [CDS-33746]: Added control statement to verify authentication type fo…

### PR DESCRIPTION
**Pull request by GoelPratyush99**
…r connectors.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32243)

### CODE REVIEW

**Review by achyuth-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32243)* status: Some of the checks are too old.

**Comment by tchaurasiya** [comment]
*[400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/sourcerepoprovider/GitConfigYamlHandler.java, line 67 at r1](https://reviewable.io/reviews/harness/harness-core/32243#-N-vL32D20Lp4JmPhaKM:-N-vL32D20Lp4JmPhaKN:bw0ji1n) ([raw file](https://github.com/harness/harness-core/blob/12ab3461bdbb47f07775c7599a70a5615004b915/400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/sourcerepoprovider/GitConfigYamlHandler.java#L67)):*
> ```Java
>     String sshSettingId =
>         yaml.getSshKeyName() != null ? settingsService.getSSHSettingId(accountId, yaml.getSshKeyName()) : null;
>     if (password == ENCRYPTED_VALUE_STR && sshSettingId == null) {
> ```

nit: use .equals in place of ==



_Code quote (from 400-rest/src/test/java/software/wings/yaml/handler/connectors/configyamlhandlers/GitConfigYamlHandlerTest.java):_
```Java
testToBeanWithSSHKeyNameAndPassword
```

**Comment by tchaurasiya** [comment]
*[400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/sourcerepoprovider/GitConfigYamlHandler.java, line 70 at r1](https://reviewable.io/reviews/harness/harness-core/32243#-N-vL9VsEqonV-t65qJr:-N-vL9VsEqonV-t65qJs:b-1gyf8d) ([raw file](https://github.com/harness/harness-core/blob/12ab3461bdbb47f07775c7599a70a5615004b915/400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/sourcerepoprovider/GitConfigYamlHandler.java#L70)):*
> ```Java
>       throw new InvalidRequestException("Both SSH key and password cannot be null", USER);
>     }
>     if (password != ENCRYPTED_VALUE_STR && sshSettingId != null) {
> ```

use .notEquala() in place of != (to ensure null safety)

**Comment by tchaurasiya** [comment]
*[400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/sourcerepoprovider/GitConfigYamlHandler.java, line 67 at r1](https://reviewable.io/reviews/harness/harness-core/32243#-N-vLKYF4y9FbDxyfcCz:-N-vLKYF4y9FbDxyfcD-:bta78a8) ([raw file](https://github.com/harness/harness-core/blob/12ab3461bdbb47f07775c7599a70a5615004b915/400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/sourcerepoprovider/GitConfigYamlHandler.java#L67)):*
> ```Java
>     String sshSettingId =
>         yaml.getSshKeyName() != null ? settingsService.getSSHSettingId(accountId, yaml.getSshKeyName()) : null;
>     if (password == ENCRYPTED_VALUE_STR && sshSettingId == null) {
> ```

how are we ensuring in case  of null password, it would be equal to ENCRYPTED_VALUE_STR?
Have you tested this out?

**Comment by tchaurasiya** [comment]
*[400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/sourcerepoprovider/GitConfigYamlHandler.java, line 32 at r1](https://reviewable.io/reviews/harness/harness-core/32243#-N-vLgnXDDg9KavhoWyG:-N-vLgnXDDg9KavhoWyH:b-q56r20) ([raw file](https://github.com/harness/harness-core/blob/12ab3461bdbb47f07775c7599a70a5615004b915/400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/sourcerepoprovider/GitConfigYamlHandler.java#L32)):*
> ```Java
>   public Yaml toYaml(SettingAttribute settingAttribute, String appId) {
>     GitConfig gitConfig = (GitConfig) settingAttribute.getValue();
> ```

We should also use similar validation in this toYaml method.
to handle the case when crud are happening from api.

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32243)* status: 2 file(s) to review. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/sourcerepoprovider/GitConfigYamlHandler.java, line 32 at r1](https://reviewable.io/reviews/harness/harness-core/32243#-N-vLgnXDDg9KavhoWyG:-N0GQ8xqEmBfKLmJVoe_:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/12ab3461bdbb47f07775c7599a70a5615004b915/400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/sourcerepoprovider/GitConfigYamlHandler.java#L32)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

We should also use similar validation in this toYaml method.
to handle the case when crud are happening from api.
</blockquote></details>

Done
___
*[400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/sourcerepoprovider/GitConfigYamlHandler.java, line 67 at r1](https://reviewable.io/reviews/harness/harness-core/32243#-N-vL32D20Lp4JmPhaKM:-N0GQCA48gJABpzTQZYO:b-7m2y43) ([raw file](https://github.com/harness/harness-core/blob/12ab3461bdbb47f07775c7599a70a5615004b915/400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/sourcerepoprovider/GitConfigYamlHandler.java#L67)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

nit: use .equals in place of ==
</blockquote></details>

noted
___
*[400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/sourcerepoprovider/GitConfigYamlHandler.java, line 67 at r1](https://reviewable.io/reviews/harness/harness-core/32243#-N-vLKYF4y9FbDxyfcCz:-N0GQGu856J40QLEw9M3:b-e5fsjr) ([raw file](https://github.com/harness/harness-core/blob/12ab3461bdbb47f07775c7599a70a5615004b915/400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/sourcerepoprovider/GitConfigYamlHandler.java#L67)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

how are we ensuring in case  of null password, it would be equal to ENCRYPTED_VALUE_STR?
Have you tested this out?
</blockquote></details>

ENCRYPTED_VALUE_STR is default value
___
*[400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/sourcerepoprovider/GitConfigYamlHandler.java, line 70 at r1](https://reviewable.io/reviews/harness/harness-core/32243#-N-vL9VsEqonV-t65qJr:-N0GQMXWAbCKdnjzihwj:b-7m2y43) ([raw file](https://github.com/harness/harness-core/blob/12ab3461bdbb47f07775c7599a70a5615004b915/400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/sourcerepoprovider/GitConfigYamlHandler.java#L70)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

use .notEquala() in place of != (to ensure null safety)
</blockquote></details>

noted

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32243)* status: 2 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/32243#-N0UVhqZ816nvwg1uaRX:-N0UVhqZ816nvwg1uaRY:b-9zxysw) (no related file):*
Could you please summarize what this PR is doing on a high level ? You could use the PR summary for that @goelpratyush99 ?

---

**Comment by GoelPratyush99** [comment]
Hey @yogesh-chauhan ! I have updated the PR Summary
I will add pics by evening to be more clear.

> In short, now it is mandatory for the users to select only one of the authentication method for git connector in cg either HTTP or SSH. Even if they try to view or edit the connector yaml [In configuration as code] either using both or none of the authentication methods they will review "InvalidRequestException error".

**Comment by GoelPratyush99** [comment]
@yogesh-chauhan I have added the pics in to explain the behaviour in the comments of ticket [](https://harness.atlassian.net/browse/CDS-33746)

**Comment by GoelPratyush99** [comment]
The changes are not backward compatible

**Pull request closed without merging**
