### PR TITLE
[feat]:[PIE-5782]: Adding Jwt Authentication in hsqs 

### PR DESCRIPTION
**Pull request by ankittiwari-harness**
[feat]:[PIE-5782]: Adding Jwt Authentication in hsqs 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38583)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38583)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`queue-service/hsqs/router/router.go` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/38583#-NE4Jylt7lI5jVqD5i9Q:-NE4Jylt7lI5jVqD5i9R:boku7dv) ([raw file](https://github.com/harness/harness-core/blob/24ac5d6dd54feeda591c36d3348785787ee5ff93/queue-service/hsqs/router/router.go#L60)):*
> ```Go
> 			return false
> 		},
> 	}
> ```

Can we carve it out in another function



_Code quote:_
```Go
	jwtConfig := middleware.JWTConfig{
		ParseTokenFunc: func(token string, c echo.Context) (interface{}, error) {
			tkn, err := jwt.Parse(token, func(token *jwt.Token) (interface{}, error) {
				if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
					return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
				}
				return []byte(config.Secret), nil
			})

			if err != nil {
				return nil, err
			}

			if !tkn.Valid {
				return nil, errors.New("invalid Token")
			}

			claims, ok := tkn.Claims.(jwt.MapClaims)
			if ok {
				return claims, nil
			}

			return nil, errors.New("invalid token")
		},
		Skipper: func(c echo.Context) bool {
			if strings.Contains(c.Request().URL.Path, "swagger") {
				return true
			}
			return false
		},
	}
```

**Comment by ankittiwari-harness** [comment]
*[`queue-service/hsqs/router/router.go` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/38583#-NE4Jylt7lI5jVqD5i9Q:-NE4rwpX32VcgSWcMQzG:b-tihtbb) ([raw file](https://github.com/harness/harness-core/blob/24ac5d6dd54feeda591c36d3348785787ee5ff93/queue-service/hsqs/router/router.go#L60)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we carve it out in another function
</blockquote></details>

Done in new commit

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38583)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38583)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 1 of 2 files at r2, 6 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38583)* status: 1 file(s) to review.

**Pull request merged**
