### PR TITLE
feat: [CCM-6991]: Segment Track Event on Data Generation for the first time

### PR DESCRIPTION
**Pull request by Rohit-Kaliki**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31422)

### CODE REVIEW

**Comment by Rohit-Kaliki** [comment]
trigger codebasehash

**Comment by Rohit-Kaliki** [comment]
trigger ti1

**Comment by Rohit-Kaliki** [comment]
trigger ti4

**Comment by Rohit-Kaliki** [comment]
trigger compile

**Comment by Rohit-Kaliki** [comment]
trigger ft1

**Comment by Rohit-Kaliki** [comment]
trigger ft2

**Comment by Rohit-Kaliki** [comment]
21558 -> Current Commits + Disable Product Metrics

**Comment by Rohit-Kaliki** [comment]
trigger ft2

**Review by hitesharinga — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31422)* status: Some of the checks are too old.

**Review by hitesharinga — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31422)* status: Some of the checks are too old.

**Pull request merged**
