### PR TITLE
fix: [CDS-42522]: added identifier validation on passwords

### PR DESCRIPTION
**Pull request by vitsafronovici**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37082)

### CODE REVIEW

**Comment by vitsafronovici** [comment]
trigger messagecheck

**Review by acasian-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37082)* status: 3 file(s) to review. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 680 at r1](https://reviewable.io/reviews/harness/harness-core/37082#-NB0yeI23yz74cGWNdxq:-NB0yeI3-TY30_qdh-S9:b-ccb5d) ([raw file](https://github.com/harness/harness-core/blob/f3f06250af3bf56dc41c115f254939c94c18df2b/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L680)):*
> ```Java
> 
>     if (password == null) {
>       return;
> ```

shall we throw exception if password is null? It is a mandatory field, no?

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37082)* status: 0 of 1 approvals obtained.

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37082)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 680 at r1](https://reviewable.io/reviews/harness/harness-core/37082#-NB0yeI23yz74cGWNdxq:-NBBiPMYAM339HOXaKdp:bd2rcir) ([raw file](https://github.com/harness/harness-core/blob/f3f06250af3bf56dc41c115f254939c94c18df2b/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L680)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

shall we throw exception if password is null? It is a mandatory field, no?
</blockquote></details>

We have a password ref field only in 3 cases:
- ssh kerberos tgt password
- winrm ntlm
- winrm kerberos tgt password

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37082)* status: :shipit: complete! ✓

**Pull request merged**
