### PR TITLE
[feat]: [PL-32383]: Added RoleAssignment Counts in Roles API

### PR DESCRIPTION
**Pull request by adiyaar24**
## Describe your changes
This is addition to our existing roles APIs, Now we have added the support for getting the count of User , UserGroup and Service Account role assignments.
Screenshot 2023-08-03 at 3 51 36 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51323)

### CODE REVIEW

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51323)* status: Some of the checks are too old. 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleResponseDTO.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/51323#-NbJ7FZK6DWARBbXy7x5:-NbJ7FZK6DWARBbXy7x6:brjssva) ([raw file](https://github.com/harness/harness-core/blob/40504fe137b1510e6780660820716d05769e764a/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleResponseDTO.java#L33)):*
> ```Java
>   Long createdAt;
>   Long lastModifiedAt;
>   Integer userRoleCount;
> ```

change to roleAssignedToUserCount, roleAssignedToUserGroupCount and roleAssignedToServiceAccountCount.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/51323#-NbJAH5C6NGitM7NAdiE:-NbJAH5C6NGitM7NAdiF:boivp0t) ([raw file](https://github.com/harness/harness-core/blob/40504fe137b1510e6780660820716d05769e764a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java#L72)):*
> ```Java
>     this.roleRepository = roleRepository;
>     this.scopeService = scopeService;
>     this.roleAssignmentService = roleAssignmentService;
> ```

We should never mix service layer in Dao layer. Bring this up in RoleService.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51323)* status: Some of the checks are too old. 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/51323#-NbJAH5C6NGitM7NAdiE:-NbJBKx92MWrzs7oAdiw:b8qie89) ([raw file](https://github.com/harness/harness-core/blob/40504fe137b1510e6780660820716d05769e764a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java#L72)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

We should never mix service layer in Dao layer. Bring this up in RoleService.
</blockquote></details>

You can read about 
https://stackoverflow.com/questions/10025028/what-is-dao-and-service-layer-exactly-in-spring-framework
https://www.digitalocean.com/community/tutorials/dao-design-pattern

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51323)* status: Some of the checks are too old. 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/51323#-NbJBoli2nCteFgIWv7H:-NbJBoli2nCteFgIWv7I:b-rkl4wf) ([raw file](https://github.com/harness/harness-core/blob/40504fe137b1510e6780660820716d05769e764a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java#L104)):*
> ```Java
>         roleAssignmentService.list(pageRequest, roleAssignmentFilter, true);
> 
>     Map<String, Map<String, Map<PrincipalType, Integer>>> countMap = new HashMap<>();
> ```

Why 2 keys for roleIdentifier? Simplify this.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java` line 113 at r2](https://reviewable.io/reviews/harness/harness-core/51323#-NbJBn2K6wSKWdeqWA2F:-NbJBn2K6wSKWdeqWA2G:bb76mt9) ([raw file](https://github.com/harness/harness-core/blob/40504fe137b1510e6780660820716d05769e764a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java#L113)):*
> ```Java
>         countMap.putIfAbsent(key, new HashMap<>());
>         countMap.get(key).putIfAbsent(roleAssignment.getRoleIdentifier(), new HashMap<>());
>         countMap.get(key)
> ```

Why

**Review by adiyaar24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51323)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/51323#-NbJAH5C6NGitM7NAdiE:-NcMJso355_epGBktK2N:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/40504fe137b1510e6780660820716d05769e764a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java#L72)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

You can read about 
https://stackoverflow.com/questions/10025028/what-is-dao-and-service-layer-exactly-in-spring-framework
https://www.digitalocean.com/community/tutorials/dao-design-pattern

</blockquote></details>

Done.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/51323#-NbJBoli2nCteFgIWv7H:-NcMJs5gAYUSAI_BQufK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/40504fe137b1510e6780660820716d05769e764a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java#L104)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Why 2 keys for roleIdentifier? Simplify this.
</blockquote></details>

Done.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java` line 113 at r2](https://reviewable.io/reviews/harness/harness-core/51323#-NbJBn2K6wSKWdeqWA2F:-NcMJrY2-foaCkeLEWfA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/40504fe137b1510e6780660820716d05769e764a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java#L113)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Why 
</blockquote></details>

Done.

**Review by adiyaar24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51323)* status: 9 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleResponseDTO.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/51323#-NbJ7FZK6DWARBbXy7x5:-NcMJzIr5tkSJoPnkvnR:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/40504fe137b1510e6780660820716d05769e764a/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleResponseDTO.java#L33)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

change to roleAssignedToUserCount, roleAssignedToUserGroupCount and roleAssignedToServiceAccountCount.
</blockquote></details>

Done

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51323)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java` line 113 at r5](https://reviewable.io/reviews/harness/harness-core/51323#-NcT5UQn44GfIPcaFfGG:-NcT5UQq2botQBvyiM-X:b-gfcntv) ([raw file](https://github.com/harness/harness-core/blob/73549a009998c117658b968d2750e04d44d0d3f8/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java#L113)):*
> ```Java
>     }
> 
>     for (Role roleDBO : rolePages.getContent()) {
> ```

Change it to role.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/51323#-NbJAH5C6NGitM7NAdiE:-NcT61VU7JG7cm5fPg_x:bpgwzyo) ([raw file](https://github.com/harness/harness-core/blob/40504fe137b1510e6780660820716d05769e764a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java#L72)):*
<details><summary><i>Previously, adiyaar24 (Aditya Kashyap) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why is  RoleAssignmentService roleAssignmentService still existing in Dao ?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDBOMapper.java` line 34 at r5](https://reviewable.io/reviews/harness/harness-core/51323#-NcT6IL87vOSHPLoTWlR:-NcT6IL87vOSHPLoTWlS:bmh1612) ([raw file](https://github.com/harness/harness-core/blob/73549a009998c117658b968d2750e04d44d0d3f8/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDBOMapper.java#L34)):*
> ```Java
>         .version(object.getVersion())
>         .roleAssignedToUserCount(object.getRoleAssignedToUserCount())
>         .roleAssignedToUserGroupCount(object.getRoleAssignedToUserGroupCount())
> ```

Dont see need for this.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDBOMapper.java` line 56 at r5](https://reviewable.io/reviews/harness/harness-core/51323#-NcT6MMP9Fpu7dUzo5Bf:-NcT6MMP9Fpu7dUzo5Bg:bmh1612) ([raw file](https://github.com/harness/harness-core/blob/73549a009998c117658b968d2750e04d44d0d3f8/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDBOMapper.java#L56)):*
> ```Java
>         .roleAssignedToUserCount(roleDBO.getRoleAssignedToUserCount())
>         .roleAssignedToUserGroupCount(roleDBO.getRoleAssignedToUserGroupCount())
>         .roleAssignedToServiceAccountCount(roleDBO.getRoleAssignedToServiceAccountCount())
> ```

Dont see need for this.
___
*[`access-control/libs/core/src/test/java/io/harness/accesscontrol/roles/persistence/RoleDaoImplTest.java` line 81 at r5](https://reviewable.io/reviews/harness/harness-core/51323#-NcT6Qpc5fNCCu6ZO46r:-NcT6Qpc5fNCCu6ZO46s:bpkqc2j) ([raw file](https://github.com/harness/harness-core/blob/73549a009998c117658b968d2750e04d44d0d3f8/access-control/libs/core/src/test/java/io/harness/accesscontrol/roles/persistence/RoleDaoImplTest.java#L81)):*
> ```Java
>     roleAssignmentService = mock(RoleAssignmentService.class);
>     roleDao = spy(new RoleDaoImpl(roleRepository, scopeService, roleAssignmentService));
>   }
> ```

Remove  roleAssignmentService from Dao.

**Comment by adiyaar24** [comment]
trigger uts

**Review by adiyaar24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51323)* status: 9 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java` line 113 at r5](https://reviewable.io/reviews/harness/harness-core/51323#-NcT5UQn44GfIPcaFfGG:-NcTRs4560WERd70ROjD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/73549a009998c117658b968d2750e04d44d0d3f8/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java#L113)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Change it to role.
</blockquote></details>

Done.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/51323#-NbJAH5C6NGitM7NAdiE:-NcTRr7iEL5h2NlRza9l:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/40504fe137b1510e6780660820716d05769e764a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDaoImpl.java#L72)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Why is  RoleAssignmentService roleAssignmentService still existing in Dao ?
</blockquote></details>

Done.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDBOMapper.java` line 34 at r5](https://reviewable.io/reviews/harness/harness-core/51323#-NcT6IL87vOSHPLoTWlR:-NcTRnAfAeo3fvLWnaHH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/73549a009998c117658b968d2750e04d44d0d3f8/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDBOMapper.java#L34)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Dont see need for this.
</blockquote></details>

Done.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDBOMapper.java` line 56 at r5](https://reviewable.io/reviews/harness/harness-core/51323#-NcT6MMP9Fpu7dUzo5Bf:-NcTRnm35HMUmXwVHJqS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/73549a009998c117658b968d2750e04d44d0d3f8/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDBOMapper.java#L56)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Dont see need for this.
</blockquote></details>

Done.
___
*[`access-control/libs/core/src/test/java/io/harness/accesscontrol/roles/persistence/RoleDaoImplTest.java` line 81 at r5](https://reviewable.io/reviews/harness/harness-core/51323#-NcT6Qpc5fNCCu6ZO46r:-NcTQmTYBDPwwZ1Am38U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/73549a009998c117658b968d2750e04d44d0d3f8/access-control/libs/core/src/test/java/io/harness/accesscontrol/roles/persistence/RoleDaoImplTest.java#L81)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Remove  roleAssignmentService from Dao.
</blockquote></details>

Done.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51323)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java` line 104 at r6](https://reviewable.io/reviews/harness/harness-core/51323#-NcXpbul0uGiXzLb9VE1:-NcXpbul0uGiXzLb9VE2:b-c472bc) ([raw file](https://github.com/harness/harness-core/blob/20deb2a542d237d660076e623e35b6f28ac47200/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java#L104)):*
> ```Java
>     for (RoleAssignment roleAssignment : roleAssignmentServicePageResponse.getContent()) {
>       PrincipalType principalType = roleAssignment.getPrincipalType();
>       if (principalType == PrincipalType.USER || principalType == PrincipalType.SERVICE_ACCOUNT
> ```

Add UTs to cover all cases.

**Review by Jimit09Gandhi — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51323)* status: Some of the checks are too old. 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java` line 93 at r6](https://reviewable.io/reviews/harness/harness-core/51323#-Nd59Zlj9rx6miTjlqm-:-Nd59Zlk9FXb8bNgYqsO:bheh4pf) ([raw file](https://github.com/harness/harness-core/blob/20deb2a542d237d660076e623e35b6f28ac47200/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java#L93)):*
> ```Java
>   @Override
>   public PageResponse<Role> list(PageRequest pageRequest, RoleFilter roleFilter, boolean hideInternal) {
>     PageResponse<Role> rolePages = roleDao.list(pageRequest, roleFilter, hideInternal);
> ```

As discussed expose new method in UI and create new Role wrapper called RoleAggregate model which can have count for now. That can be extensible to even add Role assignment for each principal type. This will ensure we have role method which just returns list of roles.

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger uts

**Review by adiyaar24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51323)* status: 16 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java` line 93 at r6](https://reviewable.io/reviews/harness/harness-core/51323#-Nd59Zlj9rx6miTjlqm-:-NdYVJIi9vcqWchExppv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/20deb2a542d237d660076e623e35b6f28ac47200/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java#L93)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

As discussed expose new method in UI and create new Role wrapper called RoleAggregate model which can have count for now. That can be extensible to even add Role assignment for each principal type. This will ensure we have role method which just returns list of roles.
</blockquote></details>

Done.

**Review by adiyaar24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51323)* status: 16 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java` line 104 at r6](https://reviewable.io/reviews/harness/harness-core/51323#-NcXpbul0uGiXzLb9VE1:-NdYVKVVAevG6IXzinBr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/20deb2a542d237d660076e623e35b6f28ac47200/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java#L104)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Add UTs to cover all cases.
</blockquote></details>

Done.

**Comment by adiyaar24** [comment]
trigger checkstyle

**Comment by adiyaar24** [comment]
trigger pmd

**Comment by adiyaar24** [comment]
trigger uts

**Review by ashishsanodia-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 11 files at r7, 3 of 4 files at r8, 2 of 2 files at r9, 1 of 2 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51323#-:-NdZUHUg8dGnv8BBNc6W:bnfp4nl)* status: 16 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Pull request merged**
