### PR TITLE
feat: [DEL-4331]: provide option to block shell script tasks in delegate

### PR DESCRIPTION
**Pull request by arpit3107**
## Describe your changes
Customers wants a method through which they can block a delegate from executing shell script tasks. So, we have provided an env variable name (BLOCK_SHELL_TASK) which can be specified in the yaml. 
Tested in pr env and attached screenshot in jira.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35504)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35504)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 329 at r1](https://reviewable.io/reviews/harness/harness-core/35504#-N7QBhEW4v58eDZBfkSx:-N7QBhEW4v58eDZBfkSy:b-u4cr2q) ([raw file](https://github.com/harness/harness-core/blob/eadc507a46d79eef97ba5a19a9bac1f890ba68ea/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L329)):*
> ```Java
>   private String MANAGER_HOST_AND_PORT = System.getenv().get("MANAGER_HOST_AND_PORT");
> 
>   // for both cg and ng
> ```

remove this comment, it's implicit that this change is applicable for both delegate types



_Code quote:_
```Java
 // for both cg and ng
```
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1966 at r1](https://reviewable.io/reviews/harness/harness-core/35504#-N7QCEiQ7PtEg-j7HhIC:-N7QCEiQ7PtEg-j7HhID:b-yndfzr) ([raw file](https://github.com/harness/harness-core/blob/eadc507a46d79eef97ba5a19a9bac1f890ba68ea/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1966)):*
> ```Java
>           return;
>         } else if (isShellScriptTaskBlocked(delegateTaskPackage)) {
>           log.error("Delegate {} has been disabled for executing shell script task.", delegateId);
> ```

let's write a separate if condition, not merge with rest response conditions.



_Code quote:_
```Java
        } else if (isShellScriptTaskBlocked(delegateTaskPackage)) {
          log.error("Delegate {} has been disabled for executing shell script task.", delegateId);
          return;
```
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2751 at r1](https://reviewable.io/reviews/harness/harness-core/35504#-N7QCNSFBfZGa7m0oy-z:-N7QCNSFBfZGa7m0oy0-:b7bpavw) ([raw file](https://github.com/harness/harness-core/blob/eadc507a46d79eef97ba5a19a9bac1f890ba68ea/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2751)):*
> ```Java
>   }
> 
>   private boolean isShellScriptTaskBlocked(DelegateTaskPackage delegateTaskPackage) {
> ```

consider renaming this to 'canExecuteTask'

**Review by mdmilic — COMMENTED** [review]
Looks good, but seems inefficient. Why do we even try to assign a shell task to delegate that can't execute it? Cant we do something from manager side so that the task never even gets to the delegate? Does the customer want to block all delegates or just some from executing the shell tasks. If all, we could do a simple FF on manager side which just fails the shell tasks immediately if they are being assigned. If it's per delegate it would be a bit more complex. 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35504#-:-N7QQyC8CioKCPiR0waf:boeuz3a)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by arpit3107 — COMMENTED** [review]
I had forgot about this. Thanks!

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35504#-:-N7RL9tv7_97vokKCDwY:b-fdcc7r)* status: 1 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 329 at r1](https://reviewable.io/reviews/harness/harness-core/35504#-N7QBhEW4v58eDZBfkSx:-N7RKsuG0vP-vvIEovRl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eadc507a46d79eef97ba5a19a9bac1f890ba68ea/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L329)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

remove this comment, it's implicit that this change is applicable for both delegate types
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1966 at r1](https://reviewable.io/reviews/harness/harness-core/35504#-N7QCEiQ7PtEg-j7HhIC:-N7RKuqEAuPrIHvHHdQ0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eadc507a46d79eef97ba5a19a9bac1f890ba68ea/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1966)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

let's write a separate if condition, not merge with rest response conditions.
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2751 at r1](https://reviewable.io/reviews/harness/harness-core/35504#-N7QCNSFBfZGa7m0oy-z:-N7RKxTy2U6-GH6OgsIs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eadc507a46d79eef97ba5a19a9bac1f890ba68ea/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2751)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

consider renaming this to 'canExecuteTask'
</blockquote></details>

Done.

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35504)* status: 1 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 329 at r2](https://reviewable.io/reviews/harness/harness-core/35504#-N7RRaGq656_KwOSt6Os:-N7RRaGq656_KwOSt6Ot:b-8ck7zb) ([raw file](https://github.com/harness/harness-core/blob/b5bb39210ec5260337063639d9e5a3ee6777b2f7/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L329)):*
> ```Java
>   private String MANAGER_HOST_AND_PORT = System.getenv().get("MANAGER_HOST_AND_PORT");
> 
>   private boolean BLOCK_SHELL_TASK = Boolean.parseBoolean(System.getenv().get("BLOCK_SHELL_TASK"));
> ```

final boolean
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 553 at r2](https://reviewable.io/reviews/harness/harness-core/35504#-N7RRWOV1XUxyitWsLZQ:-N7RRWOV1XUxyitWsLZR:bb7geun) ([raw file](https://github.com/harness/harness-core/blob/b5bb39210ec5260337063639d9e5a3ee6777b2f7/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L553)):*
> ```Java
> 
>       if (BLOCK_SHELL_TASK) {
>         log.info("Delegate is blocked for executing shell script tasks.");
> ```

from

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35504)* status: 1 change requests. 3. unresolved discussions.

**Review by arpit3107 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35504)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 329 at r2](https://reviewable.io/reviews/harness/harness-core/35504#-N7RRaGq656_KwOSt6Os:-N7UrfWKEB7UiC5bGVgs:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b5bb39210ec5260337063639d9e5a3ee6777b2f7/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L329)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

final boolean
</blockquote></details>

done
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 553 at r2](https://reviewable.io/reviews/harness/harness-core/35504#-N7RRWOV1XUxyitWsLZQ:-N7UrgM26065Jl7DOEhm:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b5bb39210ec5260337063639d9e5a3ee6777b2f7/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L553)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

from
</blockquote></details>

done

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35504)* status: :shipit: complete! ✓

**Comment by arpit3107** [comment]
trigger codebasehash

**Pull request merged**
