### PR TITLE
[fix]: [PL-31829]: Adds missing tracing filter in template service

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
Adds missing tracing filter in template service

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44685)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Comment by ashishsanodia-harness** [comment]
trigger ut5, trigger ut6, trigger ut7, trigger utAll

**Comment by ashishsanodia-harness** [comment]
trigger ut7

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44685)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/TemplateServiceApplication.java` line 231 at r4](https://reviewable.io/reviews/harness/harness-core/44685#-NPcYJMZCu8eaZWjbpHd:-NPcYJMZCu8eaZWjbpHe:boyzztq) ([raw file](https://github.com/harness/harness-core/blob/501feaf2304bcc248b0f394633c721763f574a50/840-template-service/src/main/java/io/harness/TemplateServiceApplication.java#L231)):*
> ```Java
>     registerApiResponseFilter(environment, injector);
> 
>     if (isTrue(templateServiceConfiguration.getEnableOpentelemetry())) {
> ```

Do we really need to use isTrue function - we are adding a dependency on the org.apache.commons here.

If absolutely necessary (out of scope of this PR), we can probably write these functions in some commons and minimize external deps - which add to size.



_Code quote:_
```Java
isTrue
```
___
*[`840-template-service/src/main/java/io/harness/TemplateServiceConfiguration.java` line 94 at r4](https://reviewable.io/reviews/harness/harness-core/44685#-NPcYeY1E6NQUdUZCAYf:-NPcYeY1E6NQUdUZCAYg:bdjhjo1) ([raw file](https://github.com/harness/harness-core/blob/501feaf2304bcc248b0f394633c721763f574a50/840-template-service/src/main/java/io/harness/TemplateServiceConfiguration.java#L94)):*
> ```Java
>   @JsonProperty("allowedParallelStages") private int allowedParallelStages;
> 
>   @JsonProperty(value = "enableOpentelemetry") private Boolean enableOpentelemetry;
> ```

Any reason to use Boolean class rather than the primitive?



_Code quote:_
```Java
Boolean
```

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44685)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by ashishsanodia-harness** [comment]
*[`840-template-service/src/main/java/io/harness/TemplateServiceApplication.java` line 231 at r4](https://reviewable.io/reviews/harness/harness-core/44685#-NPcYJMZCu8eaZWjbpHd:-NPcasni5mPI6IbMA-0M:b929m77) ([raw file](https://github.com/harness/harness-core/blob/501feaf2304bcc248b0f394633c721763f574a50/840-template-service/src/main/java/io/harness/TemplateServiceApplication.java#L231)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Do we really need to use isTrue function - we are adding a dependency on the org.apache.commons here.

If absolutely necessary (out of scope of this PR), we can probably write these functions in some commons and minimize external deps - which add to size.
</blockquote></details>

It's not new dependency org.apache.commons already being used in Template service in multiple places. I'm ok to remove it's usage from here as well.

**Comment by ashishsanodia-harness** [comment]
*[`840-template-service/src/main/java/io/harness/TemplateServiceConfiguration.java` line 94 at r4](https://reviewable.io/reviews/harness/harness-core/44685#-NPcYeY1E6NQUdUZCAYf:-NPcbv7wClDMvp--ScsP:b5sjxpt) ([raw file](https://github.com/harness/harness-core/blob/501feaf2304bcc248b0f394633c721763f574a50/840-template-service/src/main/java/io/harness/TemplateServiceConfiguration.java#L94)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Any reason to use Boolean class rather than the primitive?
</blockquote></details>

Just copied over code from earlier PR to enable tracing filter https://github.com/harness/harness-core/pull/38140/files

We might need to refactor this in other services as well

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44685)* status: 5 file(s) to review. 

___
*[`840-template-service/src/main/java/io/harness/TemplateServiceApplication.java` line 231 at r4](https://reviewable.io/reviews/harness/harness-core/44685#-NPcYJMZCu8eaZWjbpHd:-NPdDWkACU49oSmOUJlc:bsceghh) ([raw file](https://github.com/harness/harness-core/blob/501feaf2304bcc248b0f394633c721763f574a50/840-template-service/src/main/java/io/harness/TemplateServiceApplication.java#L231)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

It's not new dependency org.apache.commons already being used in Template service in multiple places. I'm ok to remove it's usage from here as well.
</blockquote></details>

Yes makes sense, probably this is something template-service can cleanup everywhere. My idea was to catch your attention on such issues. I remember doing similar cleanup for delegate too.

Marking this resolved - but can you open a ticket to replace "org.apache.commons.lang3.BooleanUtils.isTrue;" with inhouse implementation and assignit to me
___
*[`840-template-service/src/main/java/io/harness/TemplateServiceConfiguration.java` line 94 at r4](https://reviewable.io/reviews/harness/harness-core/44685#-NPcYeY1E6NQUdUZCAYf:-NPdEBXn2H49QKmarUIB:b7s07ll) ([raw file](https://github.com/harness/harness-core/blob/501feaf2304bcc248b0f394633c721763f574a50/840-template-service/src/main/java/io/harness/TemplateServiceConfiguration.java#L94)):*
> https://github.com/harness/harness-core/pull/38140/files
+1

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44685)* status: :shipit: complete! ✓

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Pull request merged**
