### PR TITLE
fix:[CDS-68927]:Added validation for the required Field in ArtifactStepV2

### PR DESCRIPTION
**Pull request by Rakshitharness**
## Describe your changes
Added Validation for the different Fields in the ArtifactStepV2 file. For the NULL,EMPTY and INPUT cases.
Added Validation for these Artifact :

- AMI 
Screenshot 2023-12-13 at 12 35 23 PM
With correct Values
Screenshot 2023-12-13 at 12 49 49 PM

- ACR Artifact
Screenshot 2023-12-12 at 5 15 14 PM
Screenshot 2023-12-12 at 5 17 15 PM
With correct values
Screenshot 2023-12-13 at 12 01 25 PM

- AmazonS3 Artifact
Screenshot 2023-12-12 at 5 04 04 PM
When Provide correct Value
Screenshot 2023-12-13 at 10 24 54 AM

- Azure Artifact
Screenshot 2023-12-12 at 5 28 34 PM
With the correct Details 
Screenshot 2023-12-13 at 12 17 38 PM

- Docker Artifact
- Screenshot 2023-12-12 at 4 21 57 PM
With correct Values
Screenshot 2023-12-13 at 11 27 36 AM

- ECR Artifact
Screenshot 2023-12-12 at 5 51 57 PM
Screenshot 2023-12-12 at 5 52 31 PM
With the correct values
Screenshot 2023-12-13 at 11 24 03 AM

- GCR Artifact
Screenshot 2023-12-12 at 6 05 11 PM
Screenshot 2023-12-12 at 6 05 53 PM
With Correct Values
Screenshot 2023-12-13 at 11 30 10 AM

- GithubPackages Artifact
Screenshot 2023-12-12 at 4 53 40 PM
Screenshot 2023-12-13 at 10 37 20 AM

- Google Artifact Registry Artifact
Screenshot 2023-12-12 at 4 47 54 PM
Screenshot 2023-12-12 at 4 49 13 PM
Screenshot 2023-12-13 at 10 30 00 AM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56616)

### CODE REVIEW

**Review by Abhishek-CDC — DISMISSED** [review]

**Comment by Abhishek-CDC** [comment]
@Rakshitharness Can we make error message as "Artifact configuration: value for image is empty or not provided"?
It would bring more clarity that this error is because of incorrect artifact configuration

**Comment by Rakshitharness** [comment]
trigger uts

**Comment by Rakshitharness** [comment]
trigger ut6

**Comment by Rakshitharness** [comment]
trigger ut6

**Comment by Rakshitharness** [comment]
trigger uts

**Comment by Rakshitharness** [comment]
trigger uts

**Comment by Rakshitharness** [comment]
trigger ut6

**Comment by Rakshitharness** [comment]
trigger ut6

**Comment by Rakshitharness** [comment]
trigger uts

**Review by abhinavmittal-harness — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56616#-:-Nm_ngTdEuZaWoNuvPS1:bnfp4nl)* status: Some of the checks are too old. 13 file(s) to review.

**Comment by Rakshitharness** [comment]
trigger review

**Pull request merged**
