### PR TITLE
fix: [PL-20317]: fix for default user name

### PR DESCRIPTION
**Pull request by bhavya181**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30018)

### CODE REVIEW

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java, line 89 at r1](https://reviewable.io/reviews/harness/harness-core/30018#-MtlZZtC1cBo9X7EUM8c:-MtlZZtC1cBo9X7EUM8d:bax82uz) ([raw file](https://github.com/harness/harness-core/blob/c078e23bcbf7b4a275a2771ab07c0df4915bdefd/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L89)):*
> ```Java
>   private void setPrincipal(FileInfo request) {
>     final io.harness.security.dto.Principal principal = getPrincipal(request);
>     GlobalContextManager.upsertGlobalContextRecord(SourcePrincipalContextData.builder().principal(principal).build());
> ```

This used to work earlier. I think the PL team changed from PrincipalContextData to SourcePrincipalContextData. 

Since they did the change at the rest interceptor layer, it is not possible for us to catch this issue in the unit test.

Do you have any suggestion how this issue could have been caught ?

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018)* status: 5 file(s) to review. 2 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java, line 88 at r2](https://reviewable.io/reviews/harness/harness-core/30018#-MuuhYfZ4Fc13Q8Y0hIo:-MuuhYf_39IzexN4STna:b-ay9g4i) ([raw file](https://github.com/harness/harness-core/blob/a28005b0f7ceeacfd556019b338fb66d896a3dc8/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java#L88)):*
> ```Java
>   }
> 
>   public String getScmUserName(String accountId) {
> ```

should be accountIdentifier?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java, line 89 at r1](https://reviewable.io/reviews/harness/harness-core/30018#-MtlZZtC1cBo9X7EUM8c:-MuuhjDL9VWeAPdpsknt:b-88lswa) ([raw file](https://github.com/harness/harness-core/blob/b0a649902eac4d27244ee4fbcdd9a0af9144aee0/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L89)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

This used to work earlier. I think the PL team changed from PrincipalContextData to SourcePrincipalContextData. 

Since they did the change at the rest interceptor layer, it is not possible for us to catch this issue in the unit test.

Do you have any suggestion how this issue could have been caught ?
</blockquote></details>

Firstly, lets try to bring these issues pro-actively in our discussions if something breaks due to other platform changes.
Secondly, if not UT, but our Functional tests should've caught it. I suppose we don't check in general if correct user is committing the change, so probably there we have scope of improvement.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018)* status: 5 file(s) to review. 2 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java, line 97 at r2](https://reviewable.io/reviews/harness/harness-core/30018#-Muuia4A1ahPZe0oSDJk:-Muuia4A1ahPZe0oSDJl:bgnytd0) ([raw file](https://github.com/harness/harness-core/blob/a28005b0f7ceeacfd556019b338fb66d896a3dc8/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java#L97)):*
> ```Java
>               .getUsername();
>       return scmUserName;
>     } catch (Exception e) {
> ```

log this exception as well.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java, line 106 at r2](https://reviewable.io/reviews/harness/harness-core/30018#-MuuiQKr-UZRbZJ0wO7j:-MuuiQKr-UZRbZJ0wO7k:b-7nm514) ([raw file](https://github.com/harness/harness-core/blob/a28005b0f7ceeacfd556019b338fb66d896a3dc8/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java#L106)):*
> ```Java
>         sourceCodeManagerService.get(userPrincipal.getUserId().getValue(), accountId);
>     final Optional<SourceCodeManagerDTO> sourceCodeManagerDTO =
>         sourceCodeManager.stream().filter(scm -> scm.getType().equals(SCMType.GITHUB)).findFirst();
> ```

Can we make this code modular enough so that its easily extendible for bitbucket as well in future.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java, line 108 at r2](https://reviewable.io/reviews/harness/harness-core/30018#-MuuiefG70ukmqQsZi0p:-MuuiefG70ukmqQsZi0q:b-9yiwm8) ([raw file](https://github.com/harness/harness-core/blob/a28005b0f7ceeacfd556019b338fb66d896a3dc8/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java#L108)):*
> ```Java
>         sourceCodeManager.stream().filter(scm -> scm.getType().equals(SCMType.GITHUB)).findFirst();
>     if (!sourceCodeManagerDTO.isPresent()) {
>       throw new InvalidRequestException("User profile doesn't contain github scm details");
> ```

log exception.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018)* status: 5 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java, line 88 at r2](https://reviewable.io/reviews/harness/harness-core/30018#-MuuhYfZ4Fc13Q8Y0hIo:-MuuoyxKEFcaDdBsICYG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a28005b0f7ceeacfd556019b338fb66d896a3dc8/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java#L88)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

should be accountIdentifier?
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java, line 97 at r2](https://reviewable.io/reviews/harness/harness-core/30018#-Muuia4A1ahPZe0oSDJk:-MuuozMs9IFRm1jNk8uN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a28005b0f7ceeacfd556019b338fb66d896a3dc8/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java#L97)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

log this exception as well.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java, line 106 at r2](https://reviewable.io/reviews/harness/harness-core/30018#-MuuiQKr-UZRbZJ0wO7j:-Muuozo4DdVlCHuaOysk:b-1xbby8) ([raw file](https://github.com/harness/harness-core/blob/a28005b0f7ceeacfd556019b338fb66d896a3dc8/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java#L106)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can we make this code modular enough so that its easily extendible for bitbucket as well in future.
</blockquote></details>

This code is used by different methods where specifically GithubSCMDTO is required. for bitbucket, I think we should write a different method.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java, line 108 at r2](https://reviewable.io/reviews/harness/harness-core/30018#-MuuiefG70ukmqQsZi0p:-MuupDTMA_q0sccXdQZQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a28005b0f7ceeacfd556019b338fb66d896a3dc8/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java#L108)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

log exception.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java, line 89 at r1](https://reviewable.io/reviews/harness/harness-core/30018#-MtlZZtC1cBo9X7EUM8c:-MuupEUo899LBaBeZc96:b87akhj) ([raw file](https://github.com/harness/harness-core/blob/b0a649902eac4d27244ee4fbcdd9a0af9144aee0/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L89)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Firstly, lets try to bring these issues pro-actively in our discussions if something breaks due to other platform changes.
Secondly, if not UT, but our Functional tests should've caught it. I suppose we don't check in general if correct user is committing the change, so probably there we have scope of improvement.
</blockquote></details>

We cannot write UT for this as in this, things are by GlobaloContextThread, sourceprincipal profile and all.

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java, line 106 at r2](https://reviewable.io/reviews/harness/harness-core/30018#-MuuiQKr-UZRbZJ0wO7j:-Muux-uZ98KLOc2q-T0X:biedtso) ([raw file](https://github.com/harness/harness-core/blob/a28005b0f7ceeacfd556019b338fb66d896a3dc8/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java#L106)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

This code is used by different methods where specifically GithubSCMDTO is required. for bitbucket, I think we should write a different method.
</blockquote></details>

We can easily create a method that returns a matching SCM based on type and then typecasting can be done in each scm's personal method, works?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018)* status: 5 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java, line 106 at r2](https://reviewable.io/reviews/harness/harness-core/30018#-MuuiQKr-UZRbZJ0wO7j:-MuuzgKuBCxOjiBzzNjT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a28005b0f7ceeacfd556019b338fb66d896a3dc8/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java#L106)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We can easily create a method that returns a matching SCM based on type and then typecasting can be done in each scm's personal method, works?
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 4 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018#-:-MuzYHNK1nkoJD-80PbS:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java, line 106 at r4](https://reviewable.io/reviews/harness/harness-core/30018#-Mv-Owi0EXkqlcqbeucj:-Mv-Owi0EXkqlcqbeuck:b-s6qp9p) ([raw file](https://github.com/harness/harness-core/blob/ae693479691167a4cb509770352b0e53d488140f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java#L106)):*
> ```Java
>   private SourceCodeManagerDTO getScmUserProfile(String accountId, UserPrincipal userPrincipal, SCMType scmType) {
>     final List<SourceCodeManagerDTO> sourceCodeManager =
>         sourceCodeManagerService.get(userPrincipal.getUserId().getValue(), accountId);
> ```

what if userPrincipal is null ?

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/AbstractScmClientFacilitatorServiceImpl.java, line 166 at r4](https://reviewable.io/reviews/harness/harness-core/30018#-Mv-P70t48DrTYkJDmMq:-Mv-P70t48DrTYkJDmMr:b-wd1gr5) ([raw file](https://github.com/harness/harness-core/blob/ae693479691167a4cb509770352b0e53d488140f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/AbstractScmClientFacilitatorServiceImpl.java#L166)):*
> ```Java
>       scmUserName = userProfileHelper.getScmUserName(accountId);
>     } catch (Exception ex) {
>       // In case of exception we send empty string.
> ```

We can add log.error here which will help us in debugging

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018)* status: 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java, line 106 at r4](https://reviewable.io/reviews/harness/harness-core/30018#-Mv-Owi0EXkqlcqbeucj:-Mv2Vbwq6gGdlkQdBeTG:b-imnn52) ([raw file](https://github.com/harness/harness-core/blob/ae693479691167a4cb509770352b0e53d488140f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java#L106)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

what if userPrincipal is null ?
</blockquote></details>

UserPrincipal is taken out in another method, if its is null, that method will throw error and this method will never be called.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/AbstractScmClientFacilitatorServiceImpl.java, line 166 at r4](https://reviewable.io/reviews/harness/harness-core/30018#-Mv-P70t48DrTYkJDmMq:-Mv2VVp58s_ooKrGPaww:b-pydas0) ([raw file](https://github.com/harness/harness-core/blob/ae693479691167a4cb509770352b0e53d488140f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/AbstractScmClientFacilitatorServiceImpl.java#L166)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

We can add log.error here which will help us in debugging
</blockquote></details>

upper layer has already logs, so, writing logs both side will be of no use.

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java, line 106 at r4](https://reviewable.io/reviews/harness/harness-core/30018#-Mv-Owi0EXkqlcqbeucj:-Mv2XEy2DgQG60uxixbf:b-j10vkw) ([raw file](https://github.com/harness/harness-core/blob/ae693479691167a4cb509770352b0e53d488140f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java#L106)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

UserPrincipal is taken out in another method, if its is null, that method will throw error and this method will never be called.
</blockquote></details>

Every function should be an independent entity and it should not make assumptions about what input it will get.

Lets say if someone else calls this function then he won't know about our assumption,

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/AbstractScmClientFacilitatorServiceImpl.java, line 166 at r4](https://reviewable.io/reviews/harness/harness-core/30018#-Mv-P70t48DrTYkJDmMq:-Mv2XZeg-m5Igj23w8Db:b-kvfclo) ([raw file](https://github.com/harness/harness-core/blob/ae693479691167a4cb509770352b0e53d488140f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/AbstractScmClientFacilitatorServiceImpl.java#L166)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

upper layer has already logs, so, writing logs both side will be of no use.
</blockquote></details>

But we catched the exception and we won't know that what exception occured

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018)* status: 1 change requests. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018#-:-Mv4MZaG5HTz1CEWHL1y:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30018#-:-Mv5ONLp63K2jV8-UhHB:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
