### PR TITLE
[feat]: [CDS-51521]: shell script error handling enhancement

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43291)

### CODE REVIEW

**Comment by vladimir-peric** [comment]
trigger messagecheck, ft1

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43291)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java` line 353 at r1](https://reviewable.io/reviews/harness/harness-core/43291#-NNBuiDd8j7OC4zPwG2u:-NNBuiDe1MhdU2A35ZpD:b-105vpe) ([raw file](https://github.com/harness/harness-core/blob/12030d05e1b030ca45f0755ce222e673449bae81/960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java#L353)):*
> ```Java
>           executionDataBuilder, envVariablesMap, e, format("Exception occurred in Script execution. Reason: %s", e));
>     } catch (Exception e) {
>       commandExecutionStatus = FAILURE;
> ```

With catching and handling exceptions here we are making exception handling unusable in the following method, I suggest adding a FAILURE value to executeCommandResponse in caller method or removing handling exception logic in the caller method.
io.harness.shell.ScriptProcessExecutor#executeCommandString(java.lang.String, java.util.List<java.lang.String>, java.util.List<java.lang.String>, java.lang.Long)

**Comment by vladimir-peric** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java` line 353 at r1](https://reviewable.io/reviews/harness/harness-core/43291#-NNBuiDd8j7OC4zPwG2u:-NNC-7Uy7gKxqxmSlfaw:b-k30b86) ([raw file](https://github.com/harness/harness-core/blob/12030d05e1b030ca45f0755ce222e673449bae81/960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java#L353)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

With catching and handling exceptions here we are making exception handling unusable in the following method, I suggest adding a FAILURE value to executeCommandResponse in caller method or removing handling exception logic in the caller method.
io.harness.shell.ScriptProcessExecutor#executeCommandString(java.lang.String, java.util.List<java.lang.String>, java.util.List<java.lang.String>, java.lang.Long)
</blockquote></details>

I considered different approaches here, but this one seemed the least risky. I'll try the approach you suggested, and in case it doesn't produce any side effects, we can go with it as well.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43291)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java` line 353 at r1](https://reviewable.io/reviews/harness/harness-core/43291#-NNBuiDd8j7OC4zPwG2u:-NNM3_pJEZtNHtqYnYBZ:b-ggx2wz) ([raw file](https://github.com/harness/harness-core/blob/12030d05e1b030ca45f0755ce222e673449bae81/960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java#L353)):*
<details><summary><i>Previously, vladimir-peric (Vladimir Peric) wrote…</i></summary><blockquote>

I considered different approaches here, but this one seemed the least risky. I'll try the approach you suggested, and in case it doesn't produce any side effects, we can go with it as well. 
</blockquote></details>

Just do not handle exceptions here pass them, nothing to do, and manage them in the parent method where having the logic  commandExecutionStatus = FAILURE . With your current logic, let's say another non FileNotFoundException exception is thrown we will face NPE again in the parent method because, in the parent method, we just caught the exception and log it as not creating commandExecutionStatus whose initial value is null.

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43291#-:-NNMlseD4iOqjH4onLeM:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by bojanmicovic — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43291)* status: :shipit: complete! ✓

**Review by markoharness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43291)* status: :shipit: complete! ✓

**Comment by vladimir-peric** [comment]
trigger compile, checkstylecodeformat

**Review by markoharness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43291)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by markoharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43291)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43291#-:-NN_sxy5DcxV_BtvQtYd:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
