### PR TITLE
[fix]: [cds-59271]: Throw exception when project id is passed with environment at org or account  level

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes
Throw exception when project id is passed with environment at org or account  level

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47285)

### CODE REVIEW

**Review by tchaurasiya — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47285)* status: :shipit: complete! ✓

**Comment by tchaurasiya** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/mapper/ServiceOverridesMapper.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/47285#-NUXFmlgEi4c2GiGq6GL:-NUXFmlgEi4c2GiGq6GM:bf00zts) ([raw file](https://github.com/harness/harness-core/blob/006a687d8bf7565b695881101217d0705950925f/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/mapper/ServiceOverridesMapper.java#L47)):*
> ```Java
>     if (environmentRefSplit.length != 1 && isNotEmpty(serviceOverrideRequestDTO.getProjectIdentifier())) {
>       throw new InvalidRequestException(
>           "Project Identifier should not be passed when environment scope is organisation or account level");
> ```

Let's specify that its happening in serviceoverride.
"Project Identifier should not be passed when environment used in Service Override is at organisation or account scoped"

**Comment by lovish1999** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/mapper/ServiceOverridesMapper.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/47285#-NU_z7hf5ue2z0crjBt2:-NU_z7hf5ue2z0crjBt3:bcq2jrq) ([raw file](https://github.com/harness/harness-core/blob/006a687d8bf7565b695881101217d0705950925f/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/mapper/ServiceOverridesMapper.java#L44)):*
> ```Java
>       String accountId, ServiceOverrideRequestDTO serviceOverrideRequestDTO) {
>     String[] environmentRefSplit =
>         StringUtils.split(serviceOverrideRequestDTO.getEnvironmentIdentifier(), ".", MAX_RESULT_THRESHOLD_FOR_SPLIT);
> ```

can we explore using IdentifierRefHelper for this purpose maybe `io.harness.utils.IdentifierRefHelper#getIdentifierRef(java.lang.String, java.lang.String, java.lang.String, java.lang.String)`

**Comment by lovish1999** [comment]
trigger messagecheck

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47285)* status: :shipit: complete! ✓

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by lovish1999** [comment]
trigger messagecheck

**Pull request merged**
