### PR TITLE
[feat]: [PIE-8054]: Supporting retry failed pipeline with Yaml V1

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Supporting retry-failed-pipeline with yaml V1.

Impact: Retry failed-pipeline with current Yaml V0. And stageFqn calcutation.

Testing: Manually tested the retry-failed pipeline with current YAML V0 and Simplified YAML V1. Added the unit-tests.
Executed retry-failed pipeline automation. All passed.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43442)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 389 at r1](https://reviewable.io/reviews/harness/harness-core/43442#-NNIhjewDAZ4zJGb8ykk:-NNIhjewDAZ4zJGb8ykl:b-ti112t) ([raw file](https://github.com/harness/harness-core/blob/442f4bec05db9da650a3e2966a394d45546561b3/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L389)):*
> ```Java
>     }
>     return qualifiedNames.get(0) + "." + qualifiedNames.get(1);
>   }
> ```

blank line missing

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 257 at r1](https://reviewable.io/reviews/harness/harness-core/43442#-NNIi-bw0qSCeAu9gwcx:-NNIi-bw0qSCeAu9gwcy:bc5wc9j) ([raw file](https://github.com/harness/harness-core/blob/442f4bec05db9da650a3e2966a394d45546561b3/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L257)):*
> ```Java
> 
>   private JsonNode getStagesNodeFromParallelNode(JsonNode parallelNode, String pipelineVersion) {
>     if (PipelineVersion.V1.equals(pipelineVersion)) {
> ```

I see this if condition at a lot of places. Do you think we can move this statement into a util method something like "isV1PipelineVersion()" and this can be helpful to use?

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43442)* status: 7 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 389 at r1](https://reviewable.io/reviews/harness/harness-core/43442#-NNIhjewDAZ4zJGb8ykk:-NNIkUuo8VjGE2sRbKHr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/442f4bec05db9da650a3e2966a394d45546561b3/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L389)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

blank line missing
</blockquote></details>

Done.

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 3 of 3 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43442)* status: 16 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger ft1 ft2

**Comment by brijeshdhakar** [comment]
trigger ti0 ti2 ti3 ti4 ti1

**Comment by brijeshdhakar** [comment]
trigger ti1

**Comment by brijeshdhakar** [comment]
trigger ti1

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43442)* status: 16 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 266 at r5](https://reviewable.io/reviews/harness/harness-core/43442#-NNtqH3F4LN4RKZmFi-W:-NNtqH3F4LN4RKZmFi-X:bnjt4rc) ([raw file](https://github.com/harness/harness-core/blob/06b145e5a1486e865556cca903f04a74a2849382/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L266)):*
> ```Java
> 
>   private JsonNode getStageNodeFromStagesNode(ArrayNode stagesNode, int stageIndex, String pipelineVersion) {
>     if (PipelineVersion.isV1(pipelineVersion)) {
> ```

same as below
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 284 at r5](https://reviewable.io/reviews/harness/harness-core/43442#-NNtq2qM36-R1kPFJmrJ:-NNtq2qP6RmHZeCsJ4wV:b-bpwpym) ([raw file](https://github.com/harness/harness-core/blob/06b145e5a1486e865556cca903f04a74a2849382/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L284)):*
> ```Java
>     }
>     return currentJsonNode.get(YAMLFieldNameConstants.STAGE);
>   }
> ```

this seems generic to json or pipeline yaml utils, can we create new utils like PipelineYamlUtils and move it there



_Code quote:_
```Java
  private JsonNode getStageNodeFromStagesElement(JsonNode currentJsonNode, String pipelineVersion) {
    if (PipelineVersion.isV1(pipelineVersion)) {
      return currentJsonNode;
    }
    return currentJsonNode.get(YAMLFieldNameConstants.STAGE);
  }
```

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43442)* status: 17 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 266 at r5](https://reviewable.io/reviews/harness/harness-core/43442#-NNtqH3F4LN4RKZmFi-W:-NNuIDsO84VR0BgmC7pg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/06b145e5a1486e865556cca903f04a74a2849382/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L266)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as below
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 284 at r5](https://reviewable.io/reviews/harness/harness-core/43442#-NNtq2qM36-R1kPFJmrJ:-NNuIELs1yQl-x9Icfxk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/06b145e5a1486e865556cca903f04a74a2849382/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L284)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this seems generic to json or pipeline yaml utils, can we create new utils like PipelineYamlUtils and move it there
</blockquote></details>

Done.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 2 of 3 files at r2, 8 of 9 files at r3, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43442)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43442)* status: 1. unresolved discussions.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43442#-:-NNv2ysa7ND_cHBlgQVb:bnfp4nl)* status: 1. unresolved discussions.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 2 of 3 files at r2, 8 of 9 files at r3, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43442)* status: :shipit: complete! ✓

**Pull request merged**
