### PR TITLE
fix: [PL-29030]: added exception for invalid sso type

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
For invalid SSO type in the DTO, appropriate error will be thrown
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40210)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger ft1, ft2

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Comment by pbarapatre10** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/utils/UserGroupMapper.java` line 181 at r1](https://reviewable.io/reviews/harness/harness-core/40210#-NH9GGdp6FGWh3NaL5DP:-NH9GGdp6FGWh3NaL5DQ:b-oe7jal) ([raw file](https://github.com/harness/harness-core/blob/8e20c6196da0332b232c18bd2a0b5b0a0ef7d38a/123-ng-core-user/src/main/java/io/harness/ng/core/utils/UserGroupMapper.java#L181)):*
> ```Java
>         ssoType = SSOType.valueOf(userGroupDTO.getLinkedSsoType());
>       } catch (java.lang.IllegalArgumentException ex) {
>         throw new IllegalArgumentException(
> ```

minor: can we change this to use the same `java.lang. IllegalArgumentException` here as well? 
Thanks



_Code quote:_
```Java
throw new IllegalArgumentException(
```

**Review by pbarapatre10 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40210)* status: 1 file(s) to review. 0 of 2 approvals obtained.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40210)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/utils/UserGroupMapper.java` line 181 at r1](https://reviewable.io/reviews/harness/harness-core/40210#-NH9GGdp6FGWh3NaL5DP:-NH9H8nm1H3K51fiTx8j:by16hcq) ([raw file](https://github.com/harness/harness-core/blob/8e20c6196da0332b232c18bd2a0b5b0a0ef7d38a/123-ng-core-user/src/main/java/io/harness/ng/core/utils/UserGroupMapper.java#L181)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor: can we change this to use the same `java.lang. IllegalArgumentException` here as well? 
Thanks
</blockquote></details>

I think Harness defined exceptions(implementations of WingsException) are automatically propagated to UI to render correctly, throwing the java.lang.IllegalArgumentException directly gives a generic error on UI. This is what I have observed, but let me know if I am missing something. Thanks!

**Review by nishantsaini20 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40210)* status: Some of the checks are too old. 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/utils/UserGroupMapper.java` line 181 at r1](https://reviewable.io/reviews/harness/harness-core/40210#-NH9GGdp6FGWh3NaL5DP:-NHNPMcZ2aUN68Lv3kyM:b2bg7bj) ([raw file](https://github.com/harness/harness-core/blob/8e20c6196da0332b232c18bd2a0b5b0a0ef7d38a/123-ng-core-user/src/main/java/io/harness/ng/core/utils/UserGroupMapper.java#L181)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

I think Harness defined exceptions(implementations of WingsException) are automatically propagated to UI to render correctly, throwing the java.lang.IllegalArgumentException directly gives a generic error on UI. This is what I have observed, but let me know if I am missing something. Thanks!
</blockquote></details>

IMO this should be InvalidRequestException.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40210)* status: :shipit: complete! ✓

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40210)* status: :shipit: complete! ✓

**Pull request merged**
