### PR TITLE
feat: [DEL-3808]: Make optional delegate task limit configurable

### PR DESCRIPTION
**Pull request by AnupamIO**
JIRA: https://harness.atlassian.net/browse/DEL-3808

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32708)

### CODE REVIEW

**Comment by AnupamIO** [comment]
trigger messagecheck

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32708)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`360-cg-manager/container/scripts/replace_configs.sh` line 488 at r1](https://reviewable.io/reviews/harness/harness-core/32708#-N1DAMTY2NLzp-_W2jQw:-N1DAMTZ5UXPRmF2fyJE:b-m8xb77) ([raw file](https://github.com/harness/harness-core/blob/5ab4ec6a45b47d5172301b18d2e28571f668c8b0/360-cg-manager/container/scripts/replace_configs.sh#L488)):*
> ```Shell
> 
> if [[ "" != "$OPTIONAL_DELEGATE_TASK_REJECT_AT_LIMIT" ]]; then
>   yq write -i $CONFIG_FILE cg.portal.optionalDelegateTaskRejectAtLimit "$OPTIONAL_DELEGATE_TASK_REJECT_AT_LIMIT"
> ```

How will this config be reflected to manager ? 



_Code quote:_
```Shell
cg.portal.optionalDelegateTaskRejectAtLimit 
```

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32708)* status: 6 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`100-migrator/container/scripts/replace_configs.sh` line 442 at r1](https://reviewable.io/reviews/harness/harness-core/32708#-N1EO1mF9wwwScXfkXgp:-N1IjDktD6QUsUOJLcNP:b-b9ko4y) ([raw file](https://github.com/harness/harness-core/blob/5ab4ec6a45b47d5172301b18d2e28571f668c8b0/100-migrator/container/scripts/replace_configs.sh#L442)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

This will be portal.optionalDelegateTaskRejectAtLimit . In all the config.yml this variable is defined as portal.optionalDelegateTaskRejectAtLimit
</blockquote></details>

thanks, changing in next rev.
___
*[`360-cg-manager/container/scripts/replace_configs.sh` line 488 at r1](https://reviewable.io/reviews/harness/harness-core/32708#-N1DAMTY2NLzp-_W2jQw:-N1Iio2n0Q4nOrc7Z11x:b-xi3471) ([raw file](https://github.com/harness/harness-core/blob/5ab4ec6a45b47d5172301b18d2e28571f668c8b0/360-cg-manager/container/scripts/replace_configs.sh#L488)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

@gaurav-jain1 this will replace the portal.optionalDelegateTaskRejectAtLimit variable defined at config.yml of manager.
</blockquote></details>

@gaurav-jain1 env owner would need to add OPTIONAL_DELEGATE_TASK_REJECT_AT_LIMIT in config file. OPTIONAL_DELEGATE_TASK_REJECT_AT_LIMIT env variable will override optionalDelegateTaskRejectAtLimit  variable in .yaml file.

**Review by arpit3107 — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32708)* status: 1 change requests. 1. unresolved discussions.

**Review by arpit3107 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32708)* status: 1 change requests. 1. unresolved discussions.

**Review by arpit3107 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32708#-:-N1J1iwj-kFRzVgSN79q:bnfp4nl)* status: 1 change requests. 1. unresolved discussions. 

___
*[`360-cg-manager/container/scripts/replace_configs.sh` line 488 at r1](https://reviewable.io/reviews/harness/harness-core/32708#-N1DAMTY2NLzp-_W2jQw:-N1J1jouDi15-0ydlBKs:bb7k0qh) ([raw file](https://github.com/harness/harness-core/blob/5ab4ec6a45b47d5172301b18d2e28571f668c8b0/360-cg-manager/container/scripts/replace_configs.sh#L488)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

@gaurav-jain1 env owner would need to add OPTIONAL_DELEGATE_TASK_REJECT_AT_LIMIT in config file. OPTIONAL_DELEGATE_TASK_REJECT_AT_LIMIT env variable will override optionalDelegateTaskRejectAtLimit  variable in .yaml file.
</blockquote></details>

lgtm

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32708)* status: 1 change requests. 1. unresolved discussions. 

___
*[`360-cg-manager/container/scripts/replace_configs.sh` line 488 at r1](https://reviewable.io/reviews/harness/harness-core/32708#-N1DAMTY2NLzp-_W2jQw:-N1KIJBT6fZEHgzv26qn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5ab4ec6a45b47d5172301b18d2e28571f668c8b0/360-cg-manager/container/scripts/replace_configs.sh#L488)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

lgtm
</blockquote></details>

Done.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32708)* status: :shipit: complete! ✓

**Pull request merged**
