### PR TITLE
[feat]: [CDS-82479]: adding TrafficRouting step with related logic

### PR DESCRIPTION
**Pull request by markoharness**
## Describe your changes

Adding new kubernetes related step named Traffic Routing.
It will be used for splitting, filtering and routing traffic flow in kubernetes cluster step.
Also added related UTs.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56716)

### CODE REVIEW

**Comment by markoharness** [comment]
trigger uts

**Comment by markoharness** [comment]
trigger smartchecks

**Comment by markoharness** [comment]
trigger uts

**Comment by markoharness** [comment]
trigger ut6,ut7

**Review by alebuh — CHANGES_REQUESTED** [review]
> Reviewed 38 of 39 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56716)* status: 40 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/K8sTrafficRoutingStepPlanCreator.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-nFcUCj7LC3Se40za:-Nm-nFcUCj7LC3Se40zb:b-wy8s4p) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/K8sTrafficRoutingStepPlanCreator.java#L33)):*
> ```Java
> @CodePulse(module = ProductModule.CDS, unitCoverageRequired = false, components = {HarnessModuleComponent.CDS_K8S})
> public class K8sTrafficRoutingStepPlanCreator extends CDPMSStepPlanCreatorV2<K8sTrafficRoutingStepNode> {
>   @Inject private CDFeatureFlagHelper featureFlagService;
> ```

this is sufficient
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/K8sTrafficRoutingStepPlanCreator.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-sa0Y6JkZwjS5Emwc:-Nm-sa0Y6JkZwjS5Emwd:b-xh8aw5) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/K8sTrafficRoutingStepPlanCreator.java#L62)):*
> ```Java
>   @Override
>   public String getFacilitatorType(PlanCreationContext ctx, K8sTrafficRoutingStepNode stepElement) {
>     return OrchestrationFacilitatorType.ASYNC_CHAIN;
> ```

I don't think wee need it to be chain
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sTrafficRoutingStepInfo.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-nnzs9iMLiXlIT0q_:-Nm-nnzt9twTjYJ77mkA:b4oifw) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sTrafficRoutingStepInfo.java#L72)):*
> ```Java
>   @Override
>   public String getFacilitatorType() {
>     return OrchestrationFacilitatorType.TASK_CHAIN;
> ```

It should be the same as in the PlanCreator
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sTrafficRoutingStepParameters.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-oTjt0YxB6sluePoh:-Nm-oTjt0YxB6sluePoi:b-qdval4) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sTrafficRoutingStepParameters.java#L49)):*
> ```Java
>   @Override
>   public List<String> getCommandUnits() {
>     return Arrays.asList(K8sCommandUnitConstants.Init, K8sCommandUnitConstants.Prepare,
> ```

Not sure if we need all of those CommandUnits, what is expectation to happen in each of them?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingBaseStep.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-p0PxEJwCOV0mAtvx:-Nm-p0PxEJwCOV0mAtvy:buv4d8i) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingBaseStep.java#L62)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> @Slf4j
> public class K8sTrafficRoutingBaseStep extends CdTaskChainExecutable implements K8sStepExecutor {
> ```

I don't think we should use CdTaskChainExecutable anymore, as sometime in the future we want to remove it completely. So I think it would be better not to have this this BaseStep. You can just implement AsyncChainExecutableWithRbac<StepBaseParameters> in K8sTrafficRoutingStep and implement async logic there. 
The other thing is, do we need this logic to be AsyncChain? If don't have fetch files I don't see the reason for it, it would be easier just to implement AsyncExectuable, and in that case, you would need to extend just AsyncExecutableWithCapabilities
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingStep.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-sk_P0rqzwMvzTIy3:-Nm-sk_P0rqzwMvzTIy4:b-n9au14) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingStep.java#L25)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> @Slf4j
> public class K8sTrafficRoutingStep extends CdAsyncChainExecutable<K8sTrafficRoutingBaseStep> {
> ```

would be better to extend AsyncExecutableWithCapabilities directly
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/beans/K8sTrafficRoutingExecutionOutput.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-svOkAp5DXZwymG35:-Nm-svOkAp5DXZwymG36:bfj4eps) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/beans/K8sTrafficRoutingExecutionOutput.java#L26)):*
> ```Java
> @JsonTypeName("k8sTrafficRoutingExecutionOutput")
> @RecasterAlias("io.harness.cdng.k8s.beans.K8sTrafficRoutingExecutionOutput")
> public class K8sTrafficRoutingExecutionOutput implements ExecutionSweepingOutput {
> ```

do we need output and what it will contain?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/visitor/helpers/cdstepinfo/K8sTrafficRoutingStepInfoVisitorHelper.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-tSpo09YGkDLqhrkZ:-Nm-tSpo09YGkDLqhrk_:b-za0zp4) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/cdng/visitor/helpers/cdstepinfo/K8sTrafficRoutingStepInfoVisitorHelper.java#L18)):*
> ```Java
> 
> @OwnedBy(CDP)
> public class K8sTrafficRoutingStepInfoVisitorHelper implements ConfigValidator {
> ```

just curious, for what is this visitor used?
___
*[`125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java` line 332 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-uBZKBlwRlgwDDdLB:-Nm-uBZKBlwRlgwDDdLC:b-1ztbxl) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java#L332)):*
> ```Java
> 
>     kryo.register(K8sTrafficRoutingStepInfo.class, 12675);
>     kryo.register(K8sTrafficRoutingStepParameters.class, 12676);
> ```

My understanding is that we should register just classes that will be passed to the delegate, and those two we are not sending. (Even if I saw some other StepInfo and StepParameters classes here as well), or do I get it wrong?

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/K8sTrafficRoutingStepPlanCreator.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-nFcUCj7LC3Se40za:-Nm1rKyPBt6yZavQzshZ:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/K8sTrafficRoutingStepPlanCreator.java#L33)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

this is sufficient
</blockquote></details>

Removed

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/K8sTrafficRoutingStepPlanCreator.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-sa0Y6JkZwjS5Emwc:-Nm1rNBwCTLkF56jjQaV:b-1dcph8) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/K8sTrafficRoutingStepPlanCreator.java#L62)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

I don't think wee need it to be chain
</blockquote></details>

Corrected

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sTrafficRoutingStepInfo.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-nnzs9iMLiXlIT0q_:-Nm1rQQx3Tr1zde3u6q9:b-1dcph8) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sTrafficRoutingStepInfo.java#L72)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

It should be the same as in the PlanCreator
</blockquote></details>

Corrected

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sTrafficRoutingStepParameters.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-oTjt0YxB6sluePoh:-Nm1rSKbErHJ11k2-rp6:bepurgq) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sTrafficRoutingStepParameters.java#L49)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

Not sure if we need all of those CommandUnits, what is expectation to happen in each of them?
</blockquote></details>

reduced to Traffic Routing and Apply

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/visitor/helpers/cdstepinfo/K8sTrafficRoutingStepInfoVisitorHelper.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-tSpo09YGkDLqhrkZ:-Nm1rZk12MOH8235nsYN:bzcoy8d) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/cdng/visitor/helpers/cdstepinfo/K8sTrafficRoutingStepInfoVisitorHelper.java#L18)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

just curious, for what is this visitor used?
</blockquote></details>

It is used during save and execution of pipeline during traversal of Yaml elements.
For more details take a look at the code or check with pipeline team.

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java` line 332 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-uBZKBlwRlgwDDdLB:-Nm1rnN62OncsqLpZ7v3:b4pfd73) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java#L332)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

My understanding is that we should register just classes that will be passed to the delegate, and those two we are not sending. (Even if I saw some other StepInfo and StepParameters classes here as well), or do I get it wrong?
</blockquote></details>

I was just following the document 
https://harness.atlassian.net/wiki/spaces/~458180444/pages/21048001117/How+To+Create+a+new+Step+in+NextGen+NG#NGKryoRegistrar

But i have tried without them defined in this kryo class and it was working fine so i removed them.

**Comment by markoharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/beans/K8sTrafficRoutingExecutionOutput.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-svOkAp5DXZwymG35:-Nm1s9796NyQyQUgp2H3:b-pyrbqy) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/beans/K8sTrafficRoutingExecutionOutput.java#L26)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

do we need output and what it will contain?
</blockquote></details>

No. Removed.

**Comment by markoharness** [comment]
trigger uts

**Comment by markoharness** [comment]
trigger uts

**Comment by markoharness** [comment]
trigger ut0,ut4

**Comment by markoharness** [comment]
trigger uts

**Review by alebuh — CHANGES_REQUESTED** [review]
> Reviewed 16 of 19 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56716)* status: 46 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingBaseStep.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/56716#-Nm-p0PxEJwCOV0mAtvx:-Nm4tFtS4xcOF24Aez7k:b51oda8) ([raw file](https://github.com/harness/harness-core/blob/2b9dcf8d43723a769e0dfbab4a97730017cf83d7/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingBaseStep.java#L62)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

I made the change. Why was this not done directly for other k8s steps then?
</blockquote></details>

At that moment we didn't have enough capacity to refactor logic for each step, so this was temp solution to make sure that everything worked with ASYNC steps. We will probably need to do the same thing for other steps once, but for new steps there is not point in using old approach

**Review by alebuh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56716)* status: 46 file(s) to review. 1 of 2 approvals obtained.

**Comment by markoharness** [comment]
trigger ut0,ut7

**Comment by markoharness** [comment]
trigger uts

**Comment by markoharness** [comment]
trigger ut5

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 25 of 39 files at r1, 1 of 2 files at r2, 16 of 19 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56716)* status: Waiting on team(s): k8s-team.

**Comment by markoharness** [comment]
trigger review

**Pull request merged**
