### PR TITLE
feat: [DEL-4617]: Add websocket UUID as a log context when receiving and publishing events

### PR DESCRIPTION
**Pull request by mdmilic**
Add websocket UUID as a log context when receiving and publishing events

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36355)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36355)

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36355)* status: 0 of 1 approvals obtained.

**Review by jennyjames21 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36355#-:-N9Jo9oX3TFV1mtX95yu:bnfp4nl)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 110 at r2](https://reviewable.io/reviews/harness/harness-core/36355#-N9JqoRx9v8YUMHAtZ4G:-N9JqoRy7PvyIwOs0cnl:b-j2h4xk) ([raw file](https://github.com/harness/harness-core/blob/c26d5afdde4d28da63ec0642b513de740bc9f798/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L110)):*
> ```Java
>                    AutoLogContext ignore2 = new DelegateLogContext(delegateId, OVERRIDE_ERROR);
>                    AutoLogContext ignore3 = new WebsocketLogContext(event.getResource().uuid(), OVERRIDE_ERROR)) {
>                 log.info("delegate socket disconnected");
> ```

why not add more log here? So we will know more on reason behind delegate disconnect
if (event.isCancelled()  ) {

}
if (event.isClosedByClient() ) {

}

https://www.tabnine.com/code/java/methods/org.atmosphere.cpr.AtmosphereResourceEvent/isCancelled

**Review by jennyjames21 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36355#-:-N9JrkyG4KBoV50WuWJy:bnfp4nl)* status: :shipit: complete! ✓

**Review by puneetsar — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36355)* status: :shipit: complete! ✓

**Pull request merged**
