### PR TITLE
[fix]: [CDS-25445]: Service instance unconsistency UI

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31691)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger compile

**Comment by utkarshchoubey-harness** [comment]
trigger codebasehash

**Comment by utkarshchoubey-harness** [comment]
trigger ft2

**Comment by utkarshchoubey-harness** [comment]
trigger ft1

**Comment by utkarshchoubey-harness** [comment]
trigger ti0

**Comment by utkarshchoubey-harness** [comment]
trigger ti1

**Comment by utkarshchoubey-harness** [comment]
trigger ti2

**Comment by utkarshchoubey-harness** [comment]
trigger ti3

**Comment by utkarshchoubey-harness** [comment]
trigger ti4

**Comment by utkarshchoubey-harness** [comment]
trigger codeformat

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by utkarshchoubey-harness** [comment]
trigger recency

**Comment by utkarshchoubey-harness** [comment]
trigger dockerizationcheck

**Comment by utkarshchoubey-harness** [comment]
trigger pmd

**Comment by utkarshchoubey-harness** [comment]
trigger checkstyle

**Comment by utkarshchoubey-harness** [comment]
trigger buildnum

**Review by poojaSinghal — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31691)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java, line 227 at r2](https://reviewable.io/reviews/harness/harness-core/31691#-MzJEex20-d5T5sWYBpg:-MzJEex37rcTCDsTR_bM:b10bn3y) ([raw file](https://github.com/harness/harness-core/blob/20dc3b2efa30f198509790a50fce96f97aee7d19/400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java#L227)):*
> ```Java
>       serviceIds.add(serviceSummary.getEntitySummary().getId());
>     }
>     Map<String, String> serviceIdNameMapping =
> ```

can we add test for these changes?

**Review by inderschera — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31691)* status: :shipit: complete! ✓

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31691)* status: 1 change requests. 1. unresolved discussions. 

___
*[400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java, line 227 at r2](https://reviewable.io/reviews/harness/harness-core/31691#-MzJEex20-d5T5sWYBpg:-MzULQLp0rgH6v_gbgfK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/20dc3b2efa30f198509790a50fce96f97aee7d19/400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java#L227)):*
<details><summary><i>Previously, poojaSinghal (Pooja Singhal) wrote…</i></summary><blockquote>

can we add test for these changes? 
</blockquote></details>

Done.

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31691)* status: :shipit: complete! ✓

**Pull request merged**
