### PR TITLE
[feat]: [PIE-2435]: adding resource name in labels of pipeline audit trails

### PR DESCRIPTION
**Pull request by brijeshdhakar**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30183)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30183)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30183)* status: 6 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/events/InputSetCreateEvent.java, line 50 at r1](https://reviewable.io/reviews/harness/harness-core/30183#-MuAEItg7ninZ60oahLq:-MuAEItg7ninZ60oahLr:b-exq0c0) ([raw file](https://github.com/harness/harness-core/blob/4cd4f580129a21fd6028adf5497a9d53b319d499/800-pipeline-service/src/main/java/io/harness/pms/events/InputSetCreateEvent.java#L50)):*
> ```Java
>     Map<String, String> labels = new HashMap<>();
>     labels.put(ResourceConstants.LABEL_KEY_RESOURCE_NAME, inputSet.getName());
>     labels.put("pipelineIdentifier", pipelineIdentifier);
> ```

Create a constant for the key pipelineIdentifier
___
*[800-pipeline-service/src/main/java/io/harness/pms/events/InputSetDeleteEvent.java, line 50 at r1](https://reviewable.io/reviews/harness/harness-core/30183#-MuAETFRBAhTxuUDXxlj:-MuAETFRBAhTxuUDXxlk:b-exq0c0) ([raw file](https://github.com/harness/harness-core/blob/4cd4f580129a21fd6028adf5497a9d53b319d499/800-pipeline-service/src/main/java/io/harness/pms/events/InputSetDeleteEvent.java#L50)):*
> ```Java
>     Map<String, String> labels = new HashMap<>();
>     labels.put(ResourceConstants.LABEL_KEY_RESOURCE_NAME, inputSet.getName());
>     labels.put("pipelineIdentifier", pipelineIdentifier);
> ```

Create a constant for the key pipelineIdentifier
___
*[800-pipeline-service/src/main/java/io/harness/pms/events/InputSetUpdateEvent.java, line 51 at r1](https://reviewable.io/reviews/harness/harness-core/30183#-MuAEZ1GCHMwRSx0eak4:-MuAEZ1GCHMwRSx0eak5:b-exq0c0) ([raw file](https://github.com/harness/harness-core/blob/4cd4f580129a21fd6028adf5497a9d53b319d499/800-pipeline-service/src/main/java/io/harness/pms/events/InputSetUpdateEvent.java#L51)):*
> ```Java
>     Map<String, String> labels = new HashMap<>();
>     labels.put(ResourceConstants.LABEL_KEY_RESOURCE_NAME, newInputSet.getName());
>     labels.put("pipelineIdentifier", pipelineIdentifier);
> ```

Create a constant for the key pipelineIdentifier

**Comment by brijeshdhakar** [comment]
___
*[800-pipeline-service/src/main/java/io/harness/pms/events/InputSetCreateEvent.java, line 50 at r1](https://reviewable.io/reviews/harness/harness-core/30183#-MuAEItg7ninZ60oahLq:-MuAIcMh85_uU_Tzzeed:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4cd4f580129a21fd6028adf5497a9d53b319d499/800-pipeline-service/src/main/java/io/harness/pms/events/InputSetCreateEvent.java#L50)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Create a constant for the key pipelineIdentifier
</blockquote></details>

Done.

**Comment by brijeshdhakar** [comment]
___
*[800-pipeline-service/src/main/java/io/harness/pms/events/InputSetDeleteEvent.java, line 50 at r1](https://reviewable.io/reviews/harness/harness-core/30183#-MuAETFRBAhTxuUDXxlj:-MuAIdgB0SRvbWONtcsK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4cd4f580129a21fd6028adf5497a9d53b319d499/800-pipeline-service/src/main/java/io/harness/pms/events/InputSetDeleteEvent.java#L50)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Create a constant for the key pipelineIdentifier
</blockquote></details>

Done.

**Comment by brijeshdhakar** [comment]
___
*[800-pipeline-service/src/main/java/io/harness/pms/events/InputSetUpdateEvent.java, line 51 at r1](https://reviewable.io/reviews/harness/harness-core/30183#-MuAEZ1GCHMwRSx0eak4:-MuAIeqtAdH9yS4aC2HL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4cd4f580129a21fd6028adf5497a9d53b319d499/800-pipeline-service/src/main/java/io/harness/pms/events/InputSetUpdateEvent.java#L51)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Create a constant for the key pipelineIdentifier
</blockquote></details>

Done.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30183)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[970-ng-commons/src/main/java/io/harness/ng/core/ResourceConstants.java, line 13 at r3](https://reviewable.io/reviews/harness/harness-core/30183#-MuANl6MCGioYtesZdCw:-MuANl6MCGioYtesZdCx:bcqe9p2) ([raw file](https://github.com/harness/harness-core/blob/fb91cd8b1cf24da93760f462f0c628db28f6252f/970-ng-commons/src/main/java/io/harness/ng/core/ResourceConstants.java#L13)):*
> ```Java
>   public static final String LABEL_KEY_RESOURCE_NAME = "resourceName";
>   public static final String LABEL_KEY_USER_ID = "userId";
>   public static final String PIPELINE_IDENTIFIER = "pipelineIdentifier";
> ```

Can this be renamed as LABEL_KEY_PIPELINE_IDENTIFIER ?

**Comment by brijeshdhakar** [comment]
___
*[970-ng-commons/src/main/java/io/harness/ng/core/ResourceConstants.java, line 13 at r3](https://reviewable.io/reviews/harness/harness-core/30183#-MuANl6MCGioYtesZdCw:-MuAOQSy5V_i7CnDBLWf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fb91cd8b1cf24da93760f462f0c628db28f6252f/970-ng-commons/src/main/java/io/harness/ng/core/ResourceConstants.java#L13)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Can this be renamed as LABEL_KEY_PIPELINE_IDENTIFIER ?
</blockquote></details>

Done.

**Comment by brijeshdhakar** [comment]
trigger compile

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30183)* status: 4 file(s) to review.

**Comment by brijeshdhakar** [comment]
trigger compile

**Comment by brijeshdhakar** [comment]
trigger codeformat

**Comment by brijeshdhakar** [comment]
trigger codeformat

**Pull request merged**
