### PR TITLE
[feat]: [CDS-35469]: Add CF endpoints

### PR DESCRIPTION
**Pull request by nassergonzalez**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31757)

### CODE REVIEW

**Review by tmacari-harness — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31757)* status: 1 file(s) to review. 0 of 1 approvals obtained.

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31757)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java, line 52 at r2](https://reviewable.io/reviews/harness/harness-core/31757#-MzOo2ym23AH0OfcWy--:-MzOo2ym23AH0OfcWy-0:bshgj4v) ([raw file](https://github.com/harness/harness-core/blob/9ecf2463968bfc911d65527b1092157246fa64c9/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L52)):*
> ```Java
>   @Path("regions")
>   @ApiOperation(value = "Get all the AWS regions defined in the application", nickname = "RegionsForAwsHelper")
>   public ResponseDTO<Map<String, String>> getRegions() throws IOException {
> ```

let's not throw exception here but  handle it in service layer.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java, line 30 at r2](https://reviewable.io/reviews/harness/harness-core/31757#-MzOnuTy5XsQ1aV0n6SS:-MzOnuTy5XsQ1aV0n6ST:b4bmfdg) ([raw file](https://github.com/harness/harness-core/blob/9ecf2463968bfc911d65527b1092157246fa64c9/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java#L30)):*
> ```Java
> import java.util.stream.Stream;
> 
> public class AwsHelperResourceServiceImpl implements AwsHelperResourceService {
> ```

Let's add some tests for those methods.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java, line 55 at r2](https://reviewable.io/reviews/harness/harness-core/31757#-MzOnLSP2978-mV0PfcO:-MzOnLSP2978-mV0PfcP:bwu2wfc) ([raw file](https://github.com/harness/harness-core/blob/9ecf2463968bfc911d65527b1092157246fa64c9/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java#L55)):*
> ```Java
>   }
> 
>   private void getMapFromJson(String parametersJson) throws IOException {
> ```

let's give a more meaningful name to method and parameter.
ex: etMapFormYaml(String yamlMap)
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java, line 63 at r2](https://reviewable.io/reviews/harness/harness-core/31757#-MzOnqT71riStz-lII9o:-MzOnqT71riStz-lII9p:b-ybae9d) ([raw file](https://github.com/harness/harness-core/blob/9ecf2463968bfc911d65527b1092157246fa64c9/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java#L63)):*
> ```Java
>       regionMap = mapper.readValue(String.valueOf(regions), new TypeReference<Map<String, String>>() {});
>     } catch (IOException e) {
>       throw new InvalidArgumentsException("Failed to Deserialize json" + e);
> ```

Failed to Deserialize yaml



_Code quote:_
```Java
Failed to Deserialize json
```

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31757)* status: 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java, line 52 at r2](https://reviewable.io/reviews/harness/harness-core/31757#-MzOo2ym23AH0OfcWy--:-MzP1YX_2HXiEUuKwuvJ:b-ofg3p4) ([raw file](https://github.com/harness/harness-core/blob/9ecf2463968bfc911d65527b1092157246fa64c9/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L52)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's not throw exception here but  handle it in service layer.
</blockquote></details>

So I was checking other endpoints before doing this and I saw that is done in other endpoints. The error message also by throwing an exception is better than if I have to craft an error by myself. For example the error for this exception will be

{
    "status": "ERROR",
    "code": "INVALID_ARGUMENT",
    "message": "Invalid argument(s): Failed to Deserialize json",
    "correlationId": "4fad6940-bd4a-423c-b7b3-6ee0600c3fd4",
    "detailedMessage": null,
    "responseMessages": [
        {
            "code": "INVALID_ARGUMENT",
            "level": "ERROR",
            "message": "Invalid argument(s): Failed to Deserialize json",
            "exception": null,
            "failureTypes": []
        }
    ],
    "metadata": null
}

_I thought_ that it was a good idea to throw the exception but if after this you keep thinking that we should not throw it let me know
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java, line 30 at r2](https://reviewable.io/reviews/harness/harness-core/31757#-MzOnuTy5XsQ1aV0n6SS:-MzPO9SDA_7fm9ZtMEyR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ecf2463968bfc911d65527b1092157246fa64c9/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java#L30)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Let's add some tests for those methods.
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java, line 55 at r2](https://reviewable.io/reviews/harness/harness-core/31757#-MzOnLSP2978-mV0PfcO:-MzP2hq80WHDHKP3XNIK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ecf2463968bfc911d65527b1092157246fa64c9/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java#L55)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's give a more meaningful name to method and parameter.
ex: etMapFormYaml(String yamlMap)
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java, line 63 at r2](https://reviewable.io/reviews/harness/harness-core/31757#-MzOnqT71riStz-lII9o:-MzP2HZ62MHqjTXCoPwh:b1bq9sd) ([raw file](https://github.com/harness/harness-core/blob/9ecf2463968bfc911d65527b1092157246fa64c9/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsHelperResourceServiceImpl.java#L63)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Failed to Deserialize yaml
</blockquote></details>

In all fairness we are deserialising a json at this stage as we parsed the yaml file to a jsonNode but yeah I will change it as this will be the error sent to the user.

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31757)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java, line 52 at r2](https://reviewable.io/reviews/harness/harness-core/31757#-MzOo2ym23AH0OfcWy--:-MzPjM1BBqfH6jabOFQh:b-6k55ug) ([raw file](https://github.com/harness/harness-core/blob/9ecf2463968bfc911d65527b1092157246fa64c9/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L52)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

So I was checking other endpoints before doing this and I saw that is done in other endpoints. The error message also by throwing an exception is better than if I have to craft an error by myself. For example the error for this exception will be

{
    "status": "ERROR",
    "code": "INVALID_ARGUMENT",
    "message": "Invalid argument(s): Failed to Deserialize json",
    "correlationId": "4fad6940-bd4a-423c-b7b3-6ee0600c3fd4",
    "detailedMessage": null,
    "responseMessages": [
        {
            "code": "INVALID_ARGUMENT",
            "level": "ERROR",
            "message": "Invalid argument(s): Failed to Deserialize json",
            "exception": null,
            "failureTypes": []
        }
    ],
    "metadata": null
}

_I thought_ that it was a good idea to throw the exception but if after this you keep thinking that we should not throw it let me know
</blockquote></details>

I was talking about IOException, let's add everything in  getMapRegionFromYaml() in try catch so we will handle it and not propagate

**Pull request merged**
