### PR TITLE
fix: [CDS-39237]: Adding expression support for specifying provisioner

### PR DESCRIPTION
**Pull request by shubham-in10se**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34878)

### CODE REVIEW

**Comment by shubham-in10se** [comment]
trigger messagecheck

**Comment by shubham-in10se** [comment]
trigger messagecheck

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34878)* status: 2 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/provision/ShellScriptProvisionState.java` line 174 at r2](https://reviewable.io/reviews/harness/harness-core/34878#-N5tVhP_7XAPVHj7jh9o:-N5tVhP_7XAPVHj7jh9p:b-xeaw77) ([raw file](https://github.com/harness/harness-core/blob/13cd8aecb788d74a9793d94e1adae76995ea0d6d/400-rest/src/main/java/software/wings/sm/states/provision/ShellScriptProvisionState.java#L174)):*
> ```Java
> 
>   private ShellScriptInfrastructureProvisioner resolveProvisionerId(ExecutionContext context) {
>     String renderedProvisionerName = context.renderExpression(provisionerId);
> ```

should we check for renderedProvisionerName not being null ? basically the behaviour when variable is an invalid expression that could not be resolved

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34878)* status: :shipit: complete! ✓

**Pull request merged**
