### PR TITLE
feat: [CDS-37324]: Create RequestDTO for environment group

### PR DESCRIPTION
**Pull request by prashantsharma04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33030)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33030)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/envGroup/dto/EnvironmentGroupRequestDTO.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/33030#-N1m227X0Ootpha11rOm:-N1m227X0Ootpha11rOn:b3xnq0d) ([raw file](https://github.com/harness/harness-core/blob/4b328a8889d025180c1719248aaf3520ecb5112e/960-ng-core-beans/src/main/java/io/harness/ng/core/envGroup/dto/EnvironmentGroupRequestDTO.java#L45)):*
> ```Java
>   String description;
>   String color;
>   List<String> envIdentifiers;
> ```

apart from org, project and color, and identifier rest values should come from a new field string yaml.
PLus in validation you should verify identifier, org, project passed here should match in yaml.



_Code quote:_
```Java
List<String> envIdentifiers;
```

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33030)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33030)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/mappers/EnvironmentGroupMapper.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/33030#-N1qWplo7ASz3rmMf5xq:-N1qWplo7ASz3rmMf5xr:b-h3n4gg) ([raw file](https://github.com/harness/harness-core/blob/82afe71c69147a580f1425427d8695d95f328522/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/mappers/EnvironmentGroupMapper.java#L82)):*
> ```Java
>   public EnvironmentGroupEntity toEnvironmentGroupEntity(
>       String accId, EnvironmentGroupRequestDTO environmentGroupRequestDTO) {
>     if (isNotEmpty(environmentGroupRequestDTO.getYaml())) {
> ```

shouldnt yaml be compulsory?



_Code quote:_
```Java
isNotEmpty(environmentGroupRequestDTO.getYaml())
```
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/envGroup/dto/EnvironmentGroupRequestDTO.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/33030#-N1m227X0Ootpha11rOm:-N1qWh_l-5tV_irF0cGS:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/4b328a8889d025180c1719248aaf3520ecb5112e/960-ng-core-beans/src/main/java/io/harness/ng/core/envGroup/dto/EnvironmentGroupRequestDTO.java#L45)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

apart from org, project and color, and identifier rest values should come from a new field string yaml.
PLus in validation you should verify identifier, org, project passed here should match in yaml.
</blockquote></details>

done

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33030)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/mappers/EnvironmentGroupMapper.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/33030#-N1qWplo7ASz3rmMf5xq:-N1r8KVR2CV9xORV2pXd:b710svo) ([raw file](https://github.com/harness/harness-core/blob/82afe71c69147a580f1425427d8695d95f328522/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/mappers/EnvironmentGroupMapper.java#L82)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

shouldnt yaml be compulsory?
</blockquote></details>

I have added a not null validation for yaml in EnvironmentGroupRequestDto. So ideally yaml will never be nul.l

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33030)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/mappers/EnvironmentGroupMapper.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/33030#-N1qWplo7ASz3rmMf5xq:-N1r9G00A8hjJ2aGxRMY:b5ua8e6) ([raw file](https://github.com/harness/harness-core/blob/82afe71c69147a580f1425427d8695d95f328522/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/mappers/EnvironmentGroupMapper.java#L82)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

I have added a not null validation for yaml in EnvironmentGroupRequestDto. So ideally yaml will never be nul.l
</blockquote></details>

okay, but then we should not handle here for If condition, we should fail if empty, approving for now

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33030)* status: :shipit: complete! ✓

**Pull request merged**
