### PR TITLE
fix: [CDS-71889]: Change the type of field deploymentMetaData to interface in DeploymentStageConfig class

### PR DESCRIPTION
**Pull request by PragyeshMishra01**
## Describe your changes
Change the type of field deploymentMetaData to interface in DeploymentStageConfig class. This field is only getting used for Google Cloud Functions swimlane, so I have created separate empty metadata classes for other swimlanes and added @JsontypeInfo annotation with external type equal to deployment type.
I tried creating a single empty metadata class for other swimlanes but this was not working because we have extended [this](https://github.com/harness/harness-core/pull/collectAndResolveSubtypes) method of Jackson [here](http://io.harness.serializer.annotationawarejsonsubtyperesolver/#collectAndResolveSubtypes) and added some logic on top of it and we call [this](https://fasterxml.github.io/jackson-databind/javadoc/2.12/com/fasterxml/jackson/databind/jsontype/SubtypeResolver.html#collectAndResolveSubtypesByClass-com.fasterxml.jackson.databind.cfg.MapperConfig-com.fasterxml.jackson.databind.introspect.AnnotatedClass-) method(which is deprecated now) to resolve subtypes which collects mapping of all implementations by class id. So, it can collect EmptyMetadata.class for only one deployment type not all.

## Testing
1. Able to create and save new pipeline for K8s, native helm, ecs, google function and serverless swimlane.
2. Able to edit and save existing pipeline for K8s, native helm, ecs, google function and serverless swimlane.
3. Able to run existing pipeline for K8s, native helm, ecs, google function and serverless swimlane.
4. Able to run new pipeline for K8s, native helm, ecs, google function and serverless swimlane.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49456)

### CODE REVIEW

**Comment by PragyeshMishra01** [comment]
trigger uts

**Comment by PragyeshMishra01** [comment]
trigger messagecheck

**Review by piyush-bhuwalka — APPROVED** [review]

**Comment by PragyeshMishra01** [comment]
trigger review

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49456)* status: 16 file(s) to review.

**Comment by PragyeshMishra01** [comment]
trigger review

**Comment by PragyeshMishra01** [comment]
trigger review

**Pull request merged**
