### PR TITLE
[feat]: [CDS-39604]: Yaml Definition for usefromStage with service v2

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
This PR adds `usefromStage` yaml field to `ServiceYamlV2`
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35707)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35707)

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35707)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/beans/ServiceUseFromStageV2.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/35707#-N8bKcqY9xZyDhfM8vPA:-N8bKcqY9xZyDhfM8vPB:b-tiw97z) ([raw file](https://github.com/harness/harness-core/blob/8ed7dec9c6363f91bad8f7288b8b942b1c6e4471/125-cd-nextgen/src/main/java/io/harness/cdng/service/beans/ServiceUseFromStageV2.java#L29)):*
> ```Java
> @TypeAlias("serviceUseFromStageV2")
> @RecasterAlias("io.harness.cdng.service.beans.ServiceUseFromStageV2")
> public class ServiceUseFromStageV2 implements Serializable, Visitable {
> ```

dont need serialisable interface



_Code quote:_
```Java
Serializable
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/beans/ServiceYamlV2.java` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/35707#-N8bHum3EWoZXGT7SFHR:-N8bHum3EWoZXGT7SFHS:ba69ati) ([raw file](https://github.com/harness/harness-core/blob/8ed7dec9c6363f91bad8f7288b8b942b1c6e4471/125-cd-nextgen/src/main/java/io/harness/cdng/service/beans/ServiceYamlV2.java#L40)):*
> ```Java
> @RecasterAlias("io.harness.cdng.service.beans.ServiceYamlV2")
> // Todo (yogesh): uncomment this
> //@OneOfField(fields = {"serviceRef", "useFromStage"})
> ```

dont we need to uncomment this?



_Code quote:_
```Java
// Todo (yogesh): uncomment this
//@OneOfField(fields = {"serviceRef", "useFromStage"})
```
___
*[`125-cd-nextgen/src/main/java/io/harness/serializer/morphia/NGMorphiaRegistrar.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/35707#-N8bKQZ317bK4yVWiC_o:-N8bKQZ317bK4yVWiC_p:b-j3oh2a) ([raw file](https://github.com/harness/harness-core/blob/8ed7dec9c6363f91bad8f7288b8b942b1c6e4471/125-cd-nextgen/src/main/java/io/harness/serializer/morphia/NGMorphiaRegistrar.java#L75)):*
> ```Java
>     h.put("io.harness.polling.bean.PollingDocument", PollingDocument.class);
>     h.put("io.harness.cdng.rollback.RollbackData", RollbackData.class);
>     h.put("cdng.service.beans.ServiceUseFromStageV2", ServiceUseFromStageV2.class);
> ```

dont think we need to add as we are not storing complete pojos in mongo



_Code quote:_
```Java
 h.put("cdng.service.beans.ServiceUseFromStageV2", ServiceUseFromStageV2.class);
```

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35707)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/beans/ServiceYamlV2.java` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/35707#-N8bHum3EWoZXGT7SFHR:-N8cBn4l6H5yF30RIrt_:boxdnmz) ([raw file](https://github.com/harness/harness-core/blob/8ed7dec9c6363f91bad8f7288b8b942b1c6e4471/125-cd-nextgen/src/main/java/io/harness/cdng/service/beans/ServiceYamlV2.java#L40)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dont we need to uncomment this?
</blockquote></details>

will uncomment in next PR when execution side is complete

**Comment by yogesh-chauhan** [comment]
trigger ti0

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35707)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/beans/ServiceUseFromStageV2.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/35707#-N8bKcqY9xZyDhfM8vPA:-N8cgvFa6Yf0bXOo1N60:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8ed7dec9c6363f91bad8f7288b8b942b1c6e4471/125-cd-nextgen/src/main/java/io/harness/cdng/service/beans/ServiceUseFromStageV2.java#L29)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dont need serialisable interface
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/serializer/morphia/NGMorphiaRegistrar.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/35707#-N8bKQZ317bK4yVWiC_o:-N8cgy6lAqXJFaTkcMsS:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8ed7dec9c6363f91bad8f7288b8b942b1c6e4471/125-cd-nextgen/src/main/java/io/harness/serializer/morphia/NGMorphiaRegistrar.java#L75)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dont think we need to add as we are not storing complete pojos in mongo
</blockquote></details>

done

**Pull request merged**
