### PR TITLE
[feat]: [CCM-7167]: Business mapping JUnit test cases

### PR DESCRIPTION
**Pull request by sdsingh07**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31988)

### CODE REVIEW

**Comment by sdsingh07** [comment]
trigger messagecheck

**Review by Rohit-Kaliki — APPROVED** [review]
> Reviewed 6 of 15 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31988)* status: Some of the checks are too old.

**Review by svmav — APPROVED** [review]
> Reviewed 6 of 15 files at r1, 9 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31988)* status: :shipit: complete! ✓

**Review by Rohit-Kaliki — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31988#-:-N0-ZI2uAzHwEVjs0ja-:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
