### PR TITLE
fix: [CDS-85704]: improve v2/variables performance

### PR DESCRIPTION
**Pull request by manavjot-harness**
## Describe your changes
As of now the v2/variables API has 2 segments in the gRPC layer which contribute to majority of its execution time.
1. The processing of the variables with the respective services like cd,pms,etc.
2. The common shared logic which runs after the details have been processed/pulled from the respective services.

This PR addresses point 2, the common logic used to merge the data received from various services during a number iterations.

The major time consuming logic is serialization/deserialization of string to yaml and json in this whole flow. This flow has the following problems:
1. We are deserializing the complete yaml string to object for each iteration of dependencies.
2. We are serializing the same object after modification for each iteration of dependencies.
3. We are deserializing the a node data of all the dependencies for each iteration or dependencies and then each iteration of fqn names until that dependency recursively, which causes a lot of compution which is already done and can be reused.
	
VariableCreatorService.createVariablesResponse -> BaseCreatorService.processNodesRecursively(runs in loop until depencies are empty) -> BaseCreatorService.processNodes(loops over dependencies) -> VariableCreatorService.mergeResponses -> PlanCreationBlobResponseUtils.mergeYamlUpdates -> MergeHelper.mergeUpdatesIntoJsonParametrisedOnPathSeparator
1. deserializes the whole pipeline yaml
2. deserializes the fqn node json
3. serialize the whole pipeline yaml again after modifications

This whole process can be improved, instead of converting from string->object->string, we can do all the modifications for the whole flow and then convert to string only at the very end, after all the iterations.

# Steps to observe
Create a big pipeline with multiple stages(more than 10) and variables at any level.

# Test Cases
- [x] Pipeline with 24 stages(templates) and each stage having around 8-10 steps in it and 10 variables per stage.
- [x] Pipeline with 3 stages but with a lot of variables with 10 steps in each stage.

# Local testing numbers
Before the changes(Response time of the v2/variables API): 
1. Pipeline with 24 stages : 12-15 seconds (9-11 seconds in merging logic, rest is processing in service layer)
2. Pipeline with 3 stages : 5-7 seconds (3-4 secs in merging logic, rest is processing in service layer)

After the changes:
1. Pipeline with 24 stages : 2-3 seconds
2. Pipeline with 3 stages : 3-4 seconds

# Next Steps
Improve the processing time of each service's implementation of steps/overridden logic to improve the RT even further.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56556)

### CODE REVIEW

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 5 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56556)* status: 6 file(s) to review. 0 of 2 approvals obtained.

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56556)* status: 6 file(s) to review. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreationBlobResponseUtils.java` line 207 at r3](https://reviewable.io/reviews/harness/harness-core/56556#-NlCrT4-0awZW3chCf4w:-NlCrT4-0awZW3chCf4x:b-7f5215) ([raw file](https://github.com/harness/harness-core/blob/f4863add5d7e1c3a83dbb52f307d6f8269104ac4/884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreationBlobResponseUtils.java#L207)):*
> ```Java
>   }
> 
>   public void mergeYamlUpdates(YamlField yamlField, Map<String, JsonNode> fqnToJsonMap) {
> ```

@manavjot-harness lets discuss once on Monday regarding the changes, it could be improved on serialisation/deserialisation but i think we are skipping some imp steps

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56556)* status: Some of the checks are too old. 6 file(s) to review. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 383 at r3](https://reviewable.io/reviews/harness/harness-core/56556#-NlTPVdC7VKCyKyNa6Yl:-NlTPVdC7VKCyKyNa6Ym:b-3x9pzw) ([raw file](https://github.com/harness/harness-core/blob/f4863add5d7e1c3a83dbb52f307d6f8269104ac4/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L383)):*
> ```Java
>     });
>   }
>   public String mergeUpdatesIntoJsonParametrisedOnPathSeparator(
> ```

can we add fqntoJsonMap empty condition at top so that filter creator is also helpful
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/creators/BaseCreatorService.java` line 87 at r3](https://reviewable.io/reviews/harness/harness-core/56556#-NlTS6DG5_5lZWwMaXpq:-NlTS6DHEFERW38cxa-W:b-81ldic) ([raw file](https://github.com/harness/harness-core/blob/f4863add5d7e1c3a83dbb52f307d6f8269104ac4/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/creators/BaseCreatorService.java#L87)):*
> ```Java
> 
>     if (finalResponse instanceof VariableCreationResponse finalResp) {
>       finalResp.updateYamlInDependencies(JsonUtils.asJson(fullYaml.getNode()));
> ```

make a overriden method to override in VariableCreatorService

**Comment by manavjot-harness** [comment]
trigger uts

**Comment by manavjot-harness** [comment]
trigger smartchecks

**Comment by manavjot-harness** [comment]
trigger uts,smartchecks

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r3, 7 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56556)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreationBlobResponseUtils.java` line 210 at r5](https://reviewable.io/reviews/harness/harness-core/56556#-NlYvVL670sKBtmpQ4By:-NlYvVL670sKBtmpQ4Bz:b-m13sn5) ([raw file](https://github.com/harness/harness-core/blob/e9e78c4349baaf5034ec70d557b46adc0e51b7dc/884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreationBlobResponseUtils.java#L210)):*
> ```Java
>   }
> 
>   public void mergeYamlUpdates(YamlField yamlField, Map<String, JsonNode> fqnToJsonMap) {
> ```

why to create this method if mergeHelper has this already?
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 928 at r5](https://reviewable.io/reviews/harness/harness-core/56556#-NlYvd_B4RXn0vwdmQYX:-NlYvd_B4RXn0vwdmQYY:b-rovn5e) ([raw file](https://github.com/harness/harness-core/blob/e9e78c4349baaf5034ec70d557b46adc0e51b7dc/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L928)):*
> ```Java
>   SSCA_USE_ELK("Enables ELK search for Artifact listing instead of Mongo", HarnessTeam.SSCA),
>   SSCA_REMEDIATION_TRACKER("FF for Remediation Tracker flow.", HarnessTeam.SSCA),
>   PIE_VARIABLES_MERGE_V2_OPTIMIZED_FLOW(
> ```

our ff starts with CDS now, and not PIE
team is also CDC
Example - CDS\_DISABLE\_MAX\_TIMEOUT\_CONFIG
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/creators/BaseCreatorService.java` line 87 at r3](https://reviewable.io/reviews/harness/harness-core/56556#-NlTS6DG5_5lZWwMaXpq:-NlYvu55CZZUCzJkd9_6:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6cd46fa6cc1330918e569183ff10283b26e222e0/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/creators/BaseCreatorService.java#L87)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

make a overriden method to override in VariableCreatorService
</blockquote></details>

done
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/creators/BaseCreatorService.java` line 85 at r5](https://reviewable.io/reviews/harness/harness-core/56556#-NlYvu_2ApppNkorII1N:-NlYvu_2ApppNkorII1O:b-kw3pn8) ([raw file](https://github.com/harness/harness-core/blob/e9e78c4349baaf5034ec70d557b46adc0e51b7dc/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/creators/BaseCreatorService.java#L85)):*
> ```Java
>     }
> 
>     updateYamlInDependencies(finalResponse, JsonUtils.asJson(fullYaml.getNode()));
> ```

can this method 2nd param bhi yamlNode only as for filterCreator we are unnecessary converting to string?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/VariableCreatorService.java` line 128 at r5](https://reviewable.io/reviews/harness/harness-core/56556#-NlYwBfb8RhqullcLdBf:-NlYwBfb8RhqullcLdBg:bay8mn4) ([raw file](https://github.com/harness/harness-core/blob/e9e78c4349baaf5034ec70d557b46adc0e51b7dc/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/VariableCreatorService.java#L128)):*
> ```Java
>         && request.getMetadata().getMetadataMap().get(FeatureName.PIE_VARIABLES_MERGE_V2_OPTIMIZED_FLOW.name()) != null
>         && Boolean.parseBoolean(
>             request.getMetadata().getMetadataMap().get(FeatureName.PIE_VARIABLES_MERGE_V2_OPTIMIZED_FLOW.name()));
> ```

can you extract this as private method? for code readibility



_Code quote:_
```Java
    boolean mergePerfFlow = request != null
        && request.getMetadata().getMetadataMap().get(FeatureName.PIE_VARIABLES_MERGE_V2_OPTIMIZED_FLOW.name()) != null
        && Boolean.parseBoolean(
            request.getMetadata().getMetadataMap().get(FeatureName.PIE_VARIABLES_MERGE_V2_OPTIMIZED_FLOW.name()));
```

**Comment by manavjot-harness** [comment]
*[`884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreationBlobResponseUtils.java` line 210 at r5](https://reviewable.io/reviews/harness/harness-core/56556#-NlYvVL670sKBtmpQ4By:-Nl_KCZK0V8j4L83HUfV:b-jj4f3x) ([raw file](https://github.com/harness/harness-core/blob/e9e78c4349baaf5034ec70d557b46adc0e51b7dc/884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreationBlobResponseUtils.java#L210)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why to create this method if mergeHelper has this already?
</blockquote></details>

the parameters are different.

**Comment by manavjot-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/VariableCreatorService.java` line 128 at r5](https://reviewable.io/reviews/harness/harness-core/56556#-NlYwBfb8RhqullcLdBf:-Nl_OgVd2ag-9oI1LVFc:b-7rl0jd) ([raw file](https://github.com/harness/harness-core/blob/e9e78c4349baaf5034ec70d557b46adc0e51b7dc/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/VariableCreatorService.java#L128)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you extract this as private method? for code readibility
</blockquote></details>

done.

**Comment by manavjot-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/creators/BaseCreatorService.java` line 85 at r5](https://reviewable.io/reviews/harness/harness-core/56556#-NlYvu_2ApppNkorII1N:-Nl_OieL5ARcH9hQ_0HY:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e9e78c4349baaf5034ec70d557b46adc0e51b7dc/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/creators/BaseCreatorService.java#L85)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can this method 2nd param bhi yamlNode only as for filterCreator we are unnecessary converting to string?
</blockquote></details>

done

**Comment by manavjot-harness** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 928 at r5](https://reviewable.io/reviews/harness/harness-core/56556#-NlYvd_B4RXn0vwdmQYX:-Nl_OkfP8jl-j0-4R3Cy:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e9e78c4349baaf5034ec70d557b46adc0e51b7dc/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L928)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

our ff starts with CDS now, and not PIE
team is also CDC
Example - CDS\_DISABLE\_MAX\_TIMEOUT\_CONFIG
</blockquote></details>

done

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56556)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 7 of 8 files at r4, 1 of 1 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56556)* status: <span>:shipit:</span> complete! ✓

**Comment by manavjot-harness** [comment]
trigger uts,review

**Comment by manavjot-harness** [comment]
trigger uts

**Pull request merged**
