### PR TITLE
fix: [CDS-54860]: yaml side changes for kustomize command flags

### PR DESCRIPTION
**Pull request by achyuth-harness**
## Describe your changes
This PR contains changes for the Kustomize manifest yaml to support command flags

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45101)

### CODE REVIEW

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45101)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45101)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 8640 at r1](https://reviewable.io/reviews/harness/harness-core/45101#-NQZhM8tBrV0S_8J3o0S:-NQZhM8u0Nl41gdnCbKK:b74q5nl) ([raw file](https://github.com/harness/harness-core/blob/af115f83a961f19dab81db2164fa33ce8689d10e/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L8640)):*
> ```JSON
>           "type": "string",
>           "enum": [
>             "BUILD"
> ```

This should be Build
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/KustomizeManifestCommandFlag.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/45101#-NQZjiEI5--JhlEsOr2_:-NQZjiEK-EWjsHdNXxto:byyrtz8) ([raw file](https://github.com/harness/harness-core/blob/af115f83a961f19dab81db2164fa33ce8689d10e/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/KustomizeManifestCommandFlag.java#L35)):*
> ```Java
> @OwnedBy(CDP)
> public class KustomizeManifestCommandFlag {
>   @NotNull KustomizeCommand kustomizeCommand;
> ```

We need a different class for YAML representation

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45101)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 8640 at r1](https://reviewable.io/reviews/harness/harness-core/45101#-NQZhM8tBrV0S_8J3o0S:-NQ_av_aC-IVQtMmFLxp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af115f83a961f19dab81db2164fa33ce8689d10e/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L8640)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This should be Build
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/KustomizeManifestCommandFlag.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/45101#-NQZjiEI5--JhlEsOr2_:-NQ_azox4EAIIBVJDs9I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af115f83a961f19dab81db2164fa33ce8689d10e/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/KustomizeManifestCommandFlag.java#L35)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We need a different class for YAML representation
</blockquote></details>

Done.

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45101)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45101)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/KustomizeCommand.java` line 15 at r4](https://reviewable.io/reviews/harness/harness-core/45101#-NQe-VTl8aiFAsqisNXF:-NQe-VTl8aiFAsqisNXG:b-cbegic) ([raw file](https://github.com/harness/harness-core/blob/385f63688ac63eabead54599545b24951a7736b3/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/KustomizeCommand.java#L15)):*
> ```Java
> 
> @OwnedBy(CDP)
> public enum KustomizeCommand {
> ```

We can rename this to KustomizeCommandFlagType to have a clear distinction. And let's have a private method and field like KustomizeCommand command that will map from YAML to Delegate in one place so this can be customizable. 
nit: Enum name can be upper case and you can use JsonProperty to rename it to lower case

**Comment by achyuth-harness** [comment]
trigger smartchecks

**Comment by jamie-harness** [comment]
trigger ut6

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45101)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/KustomizeCommand.java` line 15 at r4](https://reviewable.io/reviews/harness/harness-core/45101#-NQe-VTl8aiFAsqisNXF:-NQjDr-73BoENZnO1OZS:b-h5j9y2) ([raw file](https://github.com/harness/harness-core/blob/385f63688ac63eabead54599545b24951a7736b3/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/KustomizeCommand.java#L15)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We can rename this to KustomizeCommandFlagType to have a clear distinction. And let's have a private method and field like KustomizeCommand command that will map from YAML to Delegate in one place so this can be customizable. 
nit: Enum name can be upper case and you can use JsonProperty to rename it to lower case
</blockquote></details>

Done. 
(Not having any method to convert to KustomizeCommand as the delegate request directly uses String)

**Review by abosii-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45101)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
