### PR TITLE
feat: [PL-39553]: Added a setting to configure public access

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
This PR adds a setting to enable/disable public access at the account level. This setting will be exposed to the customer on the authentication page. 
Testing-
1. Tested that enable/disable works as expected on hitting the API for public-access.
2. Tested that only the users with "core_authsetting_edit" permission are able to edit the setting.
3. Added unit testing
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50504)

### CODE REVIEW

**Review by abhinav-harness — DISMISSED** [review]

**Comment by tiwaritejas** [comment]
trigger uts

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 11 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50504)* status: Some of the checks are too old. 13 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/Account.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/50504#-N__0PpM8IMrm-XlDlFt:-N__0PpM8IMrm-XlDlFu:b-l24s4) ([raw file](https://github.com/harness/harness-core/blob/f29e2673e69bb2c60827365f1eb4f8bbe95db0a6/400-rest/src/main/java/software/wings/beans/Account.java#L149)):*
> ```Java
>   @Getter @Setter private boolean smpAccount;
>   @Getter @Setter private Integer sessionTimeOutInMinutes = DEFAULT_SESSION_TIMEOUT_IN_MINUTES;
>   @Getter @Setter boolean publicAccessEnabled;
> ```

We should set its default value to false.

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 666 at r1](https://reviewable.io/reviews/harness/harness-core/50504#-N__0kbWDFdeMwGV8Z4N:-N__0kbWDFdeMwGV8Z4O:bre0mt7) ([raw file](https://github.com/harness/harness-core/blob/f29e2673e69bb2c60827365f1eb4f8bbe95db0a6/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L666)):*
> ```Java
> 
>   @Override
>   public void setPublicAccessEnabled(String accountId, Boolean publicAccessEnabled) {
> ```

Why taking Boolean as an argument instead of boolean?

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50504)* status: 13 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/Account.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/50504#-N__0PpM8IMrm-XlDlFt:-N_c4mUN4HkLSpktoO_c:b-n95jnz) ([raw file](https://github.com/harness/harness-core/blob/f29e2673e69bb2c60827365f1eb4f8bbe95db0a6/400-rest/src/main/java/software/wings/beans/Account.java#L149)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

We should set its default value to false.
</blockquote></details>

It is primitive boolean, so it is defaulting to false implicitly.
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 666 at r1](https://reviewable.io/reviews/harness/harness-core/50504#-N__0kbWDFdeMwGV8Z4N:-N_c4vqE8PP7noCREn0K:b-mveux4) ([raw file](https://github.com/harness/harness-core/blob/f29e2673e69bb2c60827365f1eb4f8bbe95db0a6/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L666)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why taking Boolean as an argument instead of boolean?
</blockquote></details>

Changed it "boolean"

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/beans/Account.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/50504#-N__0PpM8IMrm-XlDlFt:-Na7i1Ru-69En7o3GUhX:b7xrn55) ([raw file](https://github.com/harness/harness-core/blob/f29e2673e69bb2c60827365f1eb4f8bbe95db0a6/400-rest/src/main/java/software/wings/beans/Account.java#L149)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

It is primitive boolean, so it is defaulting to false implicitly.
</blockquote></details>

If Account collection does not have this field then also its defaulting to false? also mark it private.

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 775 at r3](https://reviewable.io/reviews/harness/harness-core/50504#-Na7iOOD2iQ4djCsg2x-:-Na7iOOD2iQ4djCsg2x0:b22efgc) ([raw file](https://github.com/harness/harness-core/blob/aab81e3ae7ab8a6e9e2121b33a25dd5fa7887432/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L775)):*
> ```Java
>     updateAccountStatus(accountId, MARKED_FOR_DELETION);
>     try {
>       publishAccountChangeEventViaEventFramework(accountId, DELETE_ACTION);
> ```

Did not understand this change?

**Review by piyush-harness — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50504)* status: Some of the checks are too old. 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50504)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/Account.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/50504#-N__0PpM8IMrm-XlDlFt:-NaBq8kd7JfpBZKEXzPQ:bgqkw1w) ([raw file](https://github.com/harness/harness-core/blob/f29e2673e69bb2c60827365f1eb4f8bbe95db0a6/400-rest/src/main/java/software/wings/beans/Account.java#L149)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

If Account collection does not have this field then also its defaulting to false? also mark it private.
</blockquote></details>

Yes, it defaults to false. Marked as private.
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 775 at r3](https://reviewable.io/reviews/harness/harness-core/50504#-Na7iOOD2iQ4djCsg2x-:-NaBqKeiC_CBwQt8he6N:bf95dej) ([raw file](https://github.com/harness/harness-core/blob/aab81e3ae7ab8a6e9e2121b33a25dd5fa7887432/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L775)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Did not understand this change?
</blockquote></details>

I don't think any change has been made in this piece of code. Not sure why this is being shown as a change.

**Comment by tiwaritejas** [comment]
trigger uts_JDK11

**Comment by tiwaritejas** [comment]
trigger uts_JDK11

**Comment by tiwaritejas** [comment]
trigger uts_JDK11

**Comment by tiwaritejas** [comment]
trigger ut8

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50504)* status: Some of the checks are too old. 14 file(s) to review. 1 of 2 approvals obtained.

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Pull request merged**
