### PR TITLE
techdebt: [PL-27403]: Make threads wait for execution till service startup completes

### PR DESCRIPTION
**Pull request by ankit-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36696)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 3 Issues 
* Code issue 3 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36696)

**Comment by ankit-harness** [comment]
trigger compile

**Comment by ankit-harness** [comment]
trigger ti0

**Comment by ankit-harness** [comment]
trigger ti1

**Comment by ankit-harness** [comment]
trigger ti1

**Comment by ankit-harness** [comment]
trigger ti4

**Comment by ankit-harness** [comment]
trigger ti1

**Comment by ankit-harness** [comment]
trigger ti1

**Comment by ankit-harness** [comment]
trigger messagecheck

**Comment by ankit-harness** [comment]
trigger ti0

**Comment by ankit-harness** [comment]
trigger ti1

**Comment by ankit-harness** [comment]
trigger ti3

**Comment by ankit-harness** [comment]
trigger ti4

**Comment by ankit-harness** [comment]
trigger ti1

**Comment by ankit-harness** [comment]
trigger ti3

**Comment by ankit-harness** [comment]
trigger ti3

**Review by rijajoo — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 20 of 24 files at r2, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36696)* status: 29 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36696)* status: 29 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/search/framework/ElasticsearchSyncJob.java` line 54 at r4](https://reviewable.io/reviews/harness/harness-core/36696#-NAKD7kiW9ILy7xkzXOk-r4-54:-NAikehDAQV8EUCd72-N:b-gjgu1f) ([raw file](https://github.com/harness/harness-core/blob/fc8a1074a85adae527493d3ded5025d077797f58/400-rest/src/main/java/software/wings/search/framework/ElasticsearchSyncJob.java#L54)):*
<details><summary><i>Previously, rickmarry (Rick Marry) wrote…</i></summary><blockquote>

since getMaintenanceFlag is such an inexpensive call, should we call it more frequently than every 30 seconds?
</blockquote></details>

No. 30 secs is ok here as its a background job.

**Review by rickmarry — APPROVED** [review]

**Review by rickmarry — APPROVED** [review]

**Review by rickmarry — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 20 of 24 files at r2, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36696)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/search/framework/ElasticsearchSyncJob.java` line 54 at r4](https://reviewable.io/reviews/harness/harness-core/36696#-NAKD7kiW9ILy7xkzXOk-r4-54:-NAinPptDwloRbxsPf2J:bde9kuj) ([raw file](https://github.com/harness/harness-core/blob/fc8a1074a85adae527493d3ded5025d077797f58/400-rest/src/main/java/software/wings/search/framework/ElasticsearchSyncJob.java#L54)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

No. 30 secs is ok here as its a background job.
</blockquote></details>

good.. thank you

**Review by rickmarry — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36696)* status: :shipit: complete! ✓

**Comment by ankit-harness** [comment]
trigger ti1

**Comment by ankit-harness** [comment]
trigger ti4

**Comment by ankit-harness** [comment]
trigger ti3

**Review by rijajoo — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36696)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by rijajoo — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36696)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by ankit-harness** [comment]
trigger ti1

**Comment by ankit-harness** [comment]
trigger ti3

**Review by rijajoo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36696#-:-NAsmI3k3IDIsi7xAs5a:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by rickmarry — APPROVED** [review]
> Reviewed 4 of 4 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36696)* status: :shipit: complete! ✓

**Pull request merged**
