### PR TITLE
feat: [CDS-71303]: Added Step execution entity service and Repository to save in mongo

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
Added Step execution entity service and Repository to save in mongo db
Did local testing to check if the save is happening properly
Tech spec: https://harness.atlassian.net/l/cp/e43RLjm7

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49338)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49338)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityService.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/49338#-NYRWNpOA0EZSv58l4ID:-NYRWNpOA0EZSv58l4IE:bh128rz) ([raw file](https://github.com/harness/harness-core/blob/de27be95652a786677405c8dc890fec22a203055/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityService.java#L31)):*
> ```Java
>    * @return step execution entity
>    */
>   StepExecutionEntity save(@Valid @NotNull StepExecutionEntity stepExecutionEntity);
> ```

do we need both save and create method?



_Code quote:_
```Java
StepExecutionEntity save(@Vali
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityService.java` line 81 at r2](https://reviewable.io/reviews/harness/harness-core/49338#-NYRWSsZEqj3Pnghpxuj:-NYRWSsZEqj3Pnghpxuk:b-ivnrjd) ([raw file](https://github.com/harness/harness-core/blob/de27be95652a786677405c8dc890fec22a203055/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityService.java#L81)):*
> ```Java
>    * @param updates updates
>    */
>   void update(Scope scope, String stepExecutionId, Map<String, Object> updates);
> ```

add in comments, which index it would be using
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityService.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/49338#-NYRWV1391MCiYdR-FhA:-NYRWV1391MCiYdR-FhB:b-ivnrjd) ([raw file](https://github.com/harness/harness-core/blob/de27be95652a786677405c8dc890fec22a203055/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityService.java#L90)):*
> ```Java
>    * @param status step status
>    */
>   void updateStatus(@NotNull Scope scope, @NotNull String stepExecutionId, Status status);
> ```

add in comments, which index it would be using
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityServiceImpl.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/49338#-NYRWWaG7dgXeWacID1s:-NYRWWaG7dgXeWacID1t:bw234mg) ([raw file](https://github.com/harness/harness-core/blob/de27be95652a786677405c8dc890fec22a203055/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityServiceImpl.java#L65)):*
> ```Java
>             .pipelineIdentifier(AmbianceUtils.getPipelineIdentifier(ambiance))
>             .stepIdentifier(AmbianceUtils.obtainStepIdentifier(ambiance))
>             //            .stepName(AmbianceUtils.obtainStepName(ambiance)) // TODO: change to name from level when
> ```

why commented code is needed?

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49338)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by abhinavmittal-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49338)* status: 4 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityServiceImpl.java` line 102 at r2](https://reviewable.io/reviews/harness/harness-core/49338#-NYSYzAF3eDPtlzOVva6:-NYSYzAG8McOWSzddMus:bkwv4ac) ([raw file](https://github.com/harness/harness-core/blob/de27be95652a786677405c8dc890fec22a203055/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityServiceImpl.java#L102)):*
> ```Java
>         findStepExecutionEntity(accountIdentifier, orgIdentifier, projectIdentifier, stepExecutionId);
>     Scope scope = Scope.of(accountIdentifier, orgIdentifier, projectIdentifier);
>     if (stepExecutionEntity == null) {
> ```

StepExecutionEntityUpdateDTO has status value. Is there a reason we are not using that
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityServiceImpl.java` line 151 at r2](https://reviewable.io/reviews/harness/harness-core/49338#-NYSZHuE4xA_ptPloJSv:-NYSZHuE4xA_ptPloJSw:b-dr5mqu) ([raw file](https://github.com/harness/harness-core/blob/de27be95652a786677405c8dc890fec22a203055/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityServiceImpl.java#L151)):*
> ```Java
>     if (stepExecutionEntityUpdateDTO.getStepExecutionDetails() != null) {
>       updates.put(StepExecutionEntityKeys.executionDetails, stepExecutionEntityUpdateDTO.getStepExecutionDetails());
>     }
> ```

nit: You might want to add equals check here in case you are updating stepExecutionDetails multiple time.
If this is happening only once for now it is fine but later you might need that

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityServiceImpl.java` line 102 at r2](https://reviewable.io/reviews/harness/harness-core/49338#-NYSYzAF3eDPtlzOVva6:-NYWtmmI6L4_znGXoaj7:b-iyp69i) ([raw file](https://github.com/harness/harness-core/blob/de27be95652a786677405c8dc890fec22a203055/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityServiceImpl.java#L102)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

StepExecutionEntityUpdateDTO has status value. Is there a reason we are not using that
</blockquote></details>

Because we only want to use the status value, in case the record for the entity was not present itself. If it's present it will have the status from the node start event, or the node end event handler, and we don't want to update the status again. As there are only 2 type of status possible running or terminal.

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityServiceImpl.java` line 151 at r2](https://reviewable.io/reviews/harness/harness-core/49338#-NYSZHuE4xA_ptPloJSv:-NYXBFG3-q1dKSk8zo7r:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/de27be95652a786677405c8dc890fec22a203055/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityServiceImpl.java#L151)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

nit: You might want to add equals check here in case you are updating stepExecutionDetails multiple time.
If this is happening only once for now it is fine but later you might need that
</blockquote></details>

done

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityServiceImpl.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/49338#-NYRWWaG7dgXeWacID1s:-NYXBHzKErQ9qfIOTknL:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/de27be95652a786677405c8dc890fec22a203055/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityServiceImpl.java#L65)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why commented code is needed?
</blockquote></details>

removed

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityService.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/49338#-NYRWV1391MCiYdR-FhA:-NYXBJjD1JMDrevojftO:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/de27be95652a786677405c8dc890fec22a203055/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityService.java#L90)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add in comments, which index it would be using
</blockquote></details>

done

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityService.java` line 81 at r2](https://reviewable.io/reviews/harness/harness-core/49338#-NYRWSsZEqj3Pnghpxuj:-NYXBLn28CIZpgTojTmm:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/de27be95652a786677405c8dc890fec22a203055/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityService.java#L81)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add in comments, which index it would be using
</blockquote></details>

done

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityService.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/49338#-NYRWNpOA0EZSv58l4ID:-NYXBMhA7RcRgPL2xMLp:b5d4dzs) ([raw file](https://github.com/harness/harness-core/blob/de27be95652a786677405c8dc890fec22a203055/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step/StepExecutionEntityService.java#L31)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

do we need both save and create method?
</blockquote></details>

we didn't need as we were using create only, save was used internally only, removed it

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger uts

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 3 of 12 files at r3, 3 of 9 files at r4, 1 of 3 files at r5, 1 of 12 files at r6, 20 of 20 files at r8, 4 of 4 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49338)* status: 34 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained.

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 3 of 12 files at r3, 3 of 9 files at r4, 1 of 20 files at r8, 1 of 1 files at r10, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49338)* status: 29 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/events/PipelineStepExecutionUpdateEventHandler.java` line 60 at r12](https://reviewable.io/reviews/harness/harness-core/49338#-NZ51T8T0fXWnuEtj19T:-NZ51T8T0fXWnuEtj19U:b-wvcada) ([raw file](https://github.com/harness/harness-core/blob/89e3b992dca196fd81de910a19ca89a6f2478fa2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/events/PipelineStepExecutionUpdateEventHandler.java#L60)):*
> ```Java
>       return;
>     }
>     if (!STEPS_TO_UPDATE.contains(
> ```

Can you reverse FF check later so that for non-required steps FF check is not called 
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/CustomApprovalStep.java` line 129 at r12](https://reviewable.io/reviews/harness/harness-core/49338#-NZ52JNlE8uJEPIqkWW3:-NZ52JNlE8uJEPIqkWW4:b-c1v6xi) ([raw file](https://github.com/harness/harness-core/blob/89e3b992dca196fd81de910a19ca89a6f2478fa2/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/CustomApprovalStep.java#L129)):*
> ```Java
> 
>   private void updateStepExecutionEntity(Ambiance ambiance, StepElementParameters stepParameters,
>       CustomApprovalOutcome outcome, FailureInfo failureInfo, String errorMsg) {
> ```

cant the code of handler be reused here?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java` line 195 at r12](https://reviewable.io/reviews/harness/harness-core/49338#-NZ52Me09SlvvgxTR_4F:-NZ52Me09SlvvgxTR_4G:b-c1v6xi) ([raw file](https://github.com/harness/harness-core/blob/89e3b992dca196fd81de910a19ca89a6f2478fa2/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java#L195)):*
> ```Java
> 
>   private void updateStepExecutionEntity(Ambiance ambiance, StepElementParameters stepParameters,
>       HarnessApprovalOutcome outcome, FailureInfo failureInfo) {
> ```

cant the code of handler be reused here?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/JiraApprovalStep.java` line 106 at r12](https://reviewable.io/reviews/harness/harness-core/49338#-NZ52ODR0qS1nZ4sNmN4:-NZ52ODR0qS1nZ4sNmN5:b-c1v6xi) ([raw file](https://github.com/harness/harness-core/blob/89e3b992dca196fd81de910a19ca89a6f2478fa2/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/JiraApprovalStep.java#L106)):*
> ```Java
> 
>   private void updateStepExecutionEntity(Ambiance ambiance, StepElementParameters stepParameters,
>       JiraApprovalInstance jiraApprovalInstance, FailureInfo failureInfo, String errorMsg) {
> ```

cant the code of handler be reused here?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/ServiceNowApprovalStep.java` line 123 at r12](https://reviewable.io/reviews/harness/harness-core/49338#-NZ52P3oEUdfYcVJNHgG:-NZ52P3oEUdfYcVJNHgH:b-c1v6xi) ([raw file](https://github.com/harness/harness-core/blob/89e3b992dca196fd81de910a19ca89a6f2478fa2/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/ServiceNowApprovalStep.java#L123)):*
> ```Java
>                                            .ticketType(serviceNowApprovalInstance.getTicketType())
>                                            .ticketNumber(serviceNowApprovalInstance.getTicketNumber())
>                                            .build());
> ```

cant the code of handler be reused here?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira/create/JiraCreateStep.java` line 112 at r12](https://reviewable.io/reviews/harness/harness-core/49338#-NZ52PmCE8OsGYsoNvQH:-NZ52PmCE8OsGYsoNvQI:b-c1v6xi) ([raw file](https://github.com/harness/harness-core/blob/89e3b992dca196fd81de910a19ca89a6f2478fa2/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira/create/JiraCreateStep.java#L112)):*
> ```Java
>           if (taskResponse.getIssue().getFields().containsKey("Status")) {
>             builder.ticketStatus(taskResponse.getIssue().getFields().get("Status").toString());
>           }
> ```

cant the code of handler be reused here?

**Comment by RishabhGupta34** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r5, 1 of 12 files at r6, 11 of 20 files at r8, 4 of 4 files at r9, 4 of 4 files at r11, 9 of 9 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49338)* status: 15 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/events/PipelineStepExecutionUpdateEventHandler.java` line 60 at r12](https://reviewable.io/reviews/harness/harness-core/49338#-NZ51T8T0fXWnuEtj19T:-NZ5hRrd934lSE6t2bng:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/89e3b992dca196fd81de910a19ca89a6f2478fa2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/events/PipelineStepExecutionUpdateEventHandler.java#L60)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can you reverse FF check later so that for non-required steps FF check is not called 
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/CustomApprovalStep.java` line 129 at r12](https://reviewable.io/reviews/harness/harness-core/49338#-NZ52JNlE8uJEPIqkWW3:-NZ5hxUP0gnjCu4IwQMv:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/89e3b992dca196fd81de910a19ca89a6f2478fa2/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/CustomApprovalStep.java#L129)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

cant the code of handler be reused here?
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java` line 195 at r12](https://reviewable.io/reviews/harness/harness-core/49338#-NZ52Me09SlvvgxTR_4F:-NZ5hzKc0sy-Ih1FBW5f:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/89e3b992dca196fd81de910a19ca89a6f2478fa2/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java#L195)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

cant the code of handler be reused here?
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/JiraApprovalStep.java` line 106 at r12](https://reviewable.io/reviews/harness/harness-core/49338#-NZ52ODR0qS1nZ4sNmN4:-NZ5i1cTCMGHwuTA-Ow6:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/89e3b992dca196fd81de910a19ca89a6f2478fa2/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/JiraApprovalStep.java#L106)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

cant the code of handler be reused here?
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/ServiceNowApprovalStep.java` line 123 at r12](https://reviewable.io/reviews/harness/harness-core/49338#-NZ52P3oEUdfYcVJNHgG:-NZ5i3Cv1wN1pJUSju8O:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/89e3b992dca196fd81de910a19ca89a6f2478fa2/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/ServiceNowApprovalStep.java#L123)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

cant the code of handler be reused here?
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira/create/JiraCreateStep.java` line 112 at r12](https://reviewable.io/reviews/harness/harness-core/49338#-NZ52PmCE8OsGYsoNvQH:-NZ5i4HRBUZUy9a-kx0M:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/89e3b992dca196fd81de910a19ca89a6f2478fa2/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira/create/JiraCreateStep.java#L112)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

cant the code of handler be reused here?
</blockquote></details>

done

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r11, 2 of 2 files at r12, 9 of 9 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49338)* status: :shipit: complete! ✓

**Comment by RishabhGupta34** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49338)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by sourabh-awashti — APPROVED** [review]
lgtm

**Comment by RishabhGupta34** [comment]
trigger review

**Pull request merged**
