### PR TITLE
feat: [cds-48947]: added schema validation for environment while creating/updating a environment

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
Schema validation error when we pass empty spec for environment overide.
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41986)

### CODE REVIEW

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41986)* status: :shipit: complete! ✓

**Comment by vivekkarnatiharness** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentEntityYamlSchemaHelper.java` line 30 at r4](https://reviewable.io/reviews/harness/harness-core/41986#-NKqdwZe4XhhlDFk8gx3:-NKqdwZe4XhhlDFk8gx4:b8j5ojv) ([raw file](https://github.com/harness/harness-core/blob/01e002302ccc9c29ead3377f615ee6fbda92dc32/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentEntityYamlSchemaHelper.java#L30)):*
> ```Java
> import lombok.AccessLevel;
> import lombok.AllArgsConstructor;
> import lombok.extern.slf4j.Slf4j;
> ```

lets add a space here

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 309 at r4](https://reviewable.io/reviews/harness/harness-core/41986#-NKqeNiEE6V0ZllLeSWo:-NKqeNiEE6V0ZllLeSWp:b-x4w955) ([raw file](https://github.com/harness/harness-core/blob/01e002302ccc9c29ead3377f615ee6fbda92dc32/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L309)):*
> ```Java
>                                                   environmentRequestDTO.getProjectIdentifier()),
>         Resource.of(ENVIRONMENT, environmentRequestDTO.getIdentifier()), ENVIRONMENT_UPDATE_PERMISSION);
>     environmentEntityYamlSchemaHelper.validateSchema(accountId, environmentRequestDTO.getYaml());
> ```

We need to do this for upsert as well

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentEntityYamlSchemaHelperTest.java` line 75 at r4](https://reviewable.io/reviews/harness/harness-core/41986#-NKqeTCmCGrg9NX0rI2A:-NKqeTCmCGrg9NX0rI2B:b-wcoowd) ([raw file](https://github.com/harness/harness-core/blob/01e002302ccc9c29ead3377f615ee6fbda92dc32/120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentEntityYamlSchemaHelperTest.java#L75)):*
> ```Java
>         + "                paths:\n"
>         + "                  - ng-automation/k8s/templates/\n"
>         + "                branch: master\n";
> ```

Lets use the yaml from a file (io.harness.changehandlers.PlanExecutionSummaryCdChangeServiceInfraChangeDataHandlerNewTest#readFile)

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentEntityYamlSchemaHelperTest.java` line 75 at r4](https://reviewable.io/reviews/harness/harness-core/41986#-NKqeTCmCGrg9NX0rI2A:-NKqf7Ta-5ZtGWlHQ8bW:bmnip4b) ([raw file](https://github.com/harness/harness-core/blob/01e002302ccc9c29ead3377f615ee6fbda92dc32/120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentEntityYamlSchemaHelperTest.java#L75)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets use the yaml from a file (io.harness.changehandlers.PlanExecutionSummaryCdChangeServiceInfraChangeDataHandlerNewTest#readFile)
</blockquote></details>

Also need to add UT for exception case

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41986)* status: 1 file(s) to review. 0 of 1 approvals obtained.

**Review by utkarshchoubey-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41986)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentEntityYamlSchemaHelper.java` line 41 at r7](https://reviewable.io/reviews/harness/harness-core/41986#-NKvljld5euBYMCk2mSw:-NKvljld5euBYMCk2mSx:b-uew923) ([raw file](https://github.com/harness/harness-core/blob/e82e20d6bcd6f7094efce0a3876b07739d612820/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentEntityYamlSchemaHelper.java#L41)):*
> ```Java
>   void validateSchema(String accountId, String yaml) {
>     if (featureFlagHelperService.isEnabled(accountId, FeatureName.NG_SVC_ENV_REDESIGN)
>         && !featureFlagHelperService.isEnabled(accountId, FeatureName.DISABLE_PIPELINE_SCHEMA_VALIDATION)
> ```

you are using wrong FF - DISABLE_CDS_SERVICE_ENV_SCHEMA_VALIDATION
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentEntityYamlSchemaHelperTest.java` line 54 at r7](https://reviewable.io/reviews/harness/harness-core/41986#-NKvlxnt5x0Y_mRtFMrx:-NKvlxnt5x0Y_mRtFMry:b-r1h0a6) ([raw file](https://github.com/harness/harness-core/blob/e82e20d6bcd6f7094efce0a3876b07739d612820/120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentEntityYamlSchemaHelperTest.java#L54)):*
> ```Java
>   @Category(UnitTests.class)
>   public void testValidateSchema() throws IOException {
>     when(featureFlagHelperService.isEnabled(ACCOUNT_ID, FeatureName.DISABLE_PIPELINE_SCHEMA_VALIDATION))
> ```

DISABLE_CDS_SERVICE_ENV_SCHEMA_VALIDATION here too
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentEntityYamlSchemaHelperTest.java` line 69 at r7](https://reviewable.io/reviews/harness/harness-core/41986#-NKvlz_Y7iFLeP_SjRD2:-NKvlz_Y7iFLeP_SjRD3:bps1s89) ([raw file](https://github.com/harness/harness-core/blob/e82e20d6bcd6f7094efce0a3876b07739d612820/120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentEntityYamlSchemaHelperTest.java#L69)):*
> ```Java
>   @Category(UnitTests.class)
>   public void testServiceschemafeatureflagdisabledtest() throws IOException {
>     when(featureFlagHelperService.isEnabled(ACCOUNT_ID, FeatureName.DISABLE_PIPELINE_SCHEMA_VALIDATION))
> ```

here too
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2Test.java` line 112 at r7](https://reviewable.io/reviews/harness/harness-core/41986#-NKvm4Bc03uGsf5OZ0aC:-NKvm4Bc03uGsf5OZ0aD:b2rndg4) ([raw file](https://github.com/harness/harness-core/blob/e82e20d6bcd6f7094efce0a3876b07739d612820/120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2Test.java#L112)):*
> ```Java
>   @Owner(developers = vivekveman)
>   @Category(UnitTests.class)
>   public void testUpsertServiceWithSchemaValidationFlagOn() throws IOException {
> ```

check ff name in all places

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r5, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41986)* status: :shipit: complete! ✓

**Pull request merged**
