### PR TITLE
feat: [CDS-54592]: Add execution level tags to tags_info_ng

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
Custom Dashboard Parity: Add execution level tags to tags_info_ng(timescaledb)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44681)

### CODE REVIEW

**Comment by RishabhGupta34** [comment]
trigger messagecheck

**Review by archit-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44681)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by Abhishek-CDC** [comment]
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/44681#-NPbnyusDwoha8NnNmm-:-NPbnyusDwoha8NnNmm0:b-42v0vi) ([raw file](https://github.com/harness/harness-core/blob/1a048543ff6c7c2ecc39c2cb3204791d6eaca338/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java#L88)):*
> ```Java
> @ChangeDataCapture(table = "stage_execution_summary_ci", dataStore = "pms-harness", fields = {},
>     handler = "PipelineExecutionSummaryEntityCIStage")
> @ChangeDataCapture(table = "tags_info_ng", dataStore = "pms-harness", fields = {}, handler = "TagsInfoNGCD")
> ```

Please check for deletion of data. Since we cannot put ttl on this table and in planExecutionSummary collection there is no deletion event.

**Review by Abhishek-CDC — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44681)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/44681#-NPbpsBv-koL9lk9n3RF:-NPbpsBv-koL9lk9n3RG:b49umzh) ([raw file](https://github.com/harness/harness-core/blob/1a048543ff6c7c2ecc39c2cb3204791d6eaca338/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java#L88)):*
> ```Java
> @ChangeDataCapture(table = "stage_execution_summary_ci", dataStore = "pms-harness", fields = {},
>     handler = "PipelineExecutionSummaryEntityCIStage")
> @ChangeDataCapture(table = "tags_info_ng", dataStore = "pms-harness", fields = {}, handler = "TagsInfoNGCD")
> ```

Please check for deletion of data. Since we cannot put ttl on this table (tags_info_ng) and in planExecutionSummary collection there is no deletion event.

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/44681#-NPbnyusDwoha8NnNmm-:-NPcAguNBwJAGhU4y1dJ:bg20mqj) ([raw file](https://github.com/harness/harness-core/blob/1a048543ff6c7c2ecc39c2cb3204791d6eaca338/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java#L88)):*
<details><summary><i>Previously, Abhishek-CDC (Abhishek) wrote…</i></summary><blockquote>

Please check for deletion of data. Since we cannot put ttl on this table and in planExecutionSummary collection there is no deletion event.
</blockquote></details>

After discussion, have created a new table, instead of modifying the existing table.

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/44681#-NPbpsBv-koL9lk9n3RF:-NPcApFw0ghCDB03SViY:bg20mqj) ([raw file](https://github.com/harness/harness-core/blob/1a048543ff6c7c2ecc39c2cb3204791d6eaca338/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java#L88)):*
<details><summary><i>Previously, Abhishek-CDC (Abhishek) wrote…</i></summary><blockquote>

Please check for deletion of data. Since we cannot put ttl on this table (tags_info_ng) and in planExecutionSummary collection there is no deletion event.
</blockquote></details>

After discussion, have created a new table, instead of modifying the existing table.

**Comment by sahilhindwani-harness** [comment]
@RishabhGupta34 , can we please discuss this PR on Monday in a short call?

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44681)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by RishabhGupta34 — COMMENTED** [review]
Sure

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44681#-:-NPcjOnP-MYWFzTiQYoM:bb74ce2)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by sahilhindwani-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44681)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44681)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by Abhishek-CDC — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44681)* status: 1 file(s) to review.

**Review by Abhishek-CDC — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44681)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44681)* status: :shipit: complete! ✓

**Pull request merged**
