### PR TITLE
fix: [PL-30652]: Fix build file deps replacement pattern

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes

Update library library replacement pattern to include "module" term also. This narrows down the pattern to be matched to avoid cases where replacement breaks the BUILD file.

Existing replacement code fails when multiple java_library targets are present

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42051)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42051)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/42051#-NKUQqHj6FfFVJRW3qUi:-NKUQqHj6FfFVJRW3qUj:b-l8sgxq) ([raw file](https://github.com/harness/harness-core/blob/3a9a29a3905bea074ec2d2d7b18986421711f5fd/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L34)):*
> ```Java
>       Pattern.compile("java_library\\([\\s\\S]*?module[\\s\\S]*?(deps = \\[[\\s\\S]*?\\]),?", Pattern.MULTILINE);
>   private static final Pattern JAVA_LIBRARY_RUNTIME_DEPS_PATTERN = Pattern.compile(
>       "java_library\\([\\s\\S]*?module[\\s\\S]*?(runtime_deps = \\[[\\s\\S]*?\\]),?", Pattern.MULTILINE);
> ```

This template will not work for test targets (which are called "tests", but might depend on module target).
Also, what happens if a library had both deps and runtime_deps. Deps usually end with `module`, would that break the regex.

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42051)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/42051#-NKUQqHj6FfFVJRW3qUi:-NKURKh-BVuIe5O_Lan3:b4bri5f) ([raw file](https://github.com/harness/harness-core/blob/3a9a29a3905bea074ec2d2d7b18986421711f5fd/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L34)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This template will not work for test targets (which are called "tests", but might depend on module target).
Also, what happens if a library had both deps and runtime_deps. Deps usually end with `module`, would that break the regex. 
</blockquote></details>

Could you write in description a short steps that cause the issue? I think I was hitting it few days ago, but then I could't reproduce it when I tried to regex parsers directly.

**Review by gn-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42051)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/42051#-NKUQqHj6FfFVJRW3qUi:-NKUVVWa9nZWuEHyevee:b-r7rbwr) ([raw file](https://github.com/harness/harness-core/blob/3a9a29a3905bea074ec2d2d7b18986421711f5fd/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L34)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Could you write in description a short steps that cause the issue? I think I was hitting it few days ago, but then I could't reproduce it when I tried to regex parsers directly. 
</blockquote></details>

1. yes, will not work for tests, which it does not work today anyhow
2. if both deps and runtime_deps are present, it would break if runtime_deps are placed in front of deps. Our tool generates deps first and runtime_deps second. We can improve this logic too though
3. Deps ending with module would not affect - as we use "?" in regex, to match less as possible

Updated description.

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42051)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42051)* status: :shipit: complete! ✓

**Pull request merged**
