### PR TITLE
feat: [IDP-300]: Schema validations for app-configs

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45639)

### CODE REVIEW

**Comment by devesh-harness** [comment]
trigger messagecheck

**Comment by devesh-harness** [comment]
trigger ut0, ut3

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45639)* status: 17 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/45639#-NRajeN11aj7qKjfddUN:-NRajeN11aj7qKjfddUO:b-b1uik9) ([raw file](https://github.com/harness/harness-core/blob/7103cdfe2923dafe2e8a4f76ae327777f3786b82/idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java#L148)):*
> ```Java
>         return readFile(SNYK_SECURITY_PLUGIN_CONFIG);
>       default:
>         return null;
> ```

For all these switch cases, is it better to throw UnSupported exception ? or return null ?
___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/45639#-NRajNuW9LCT4CFYujY1:-NRajNuW9LCT4CFYujY2:b-52ong0) ([raw file](https://github.com/harness/harness-core/blob/7103cdfe2923dafe2e8a4f76ae327777f3786b82/idp-service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java#L54)):*
> ```Java
>   private static final String SUFFIX_FOR_GITHUB_APP_CONNECTOR = "_App";
> 
>   private static final String INVALID_SCHEMA_FOR_INTEGRATIONS =
> ```

Please make sure that we are replacing the accountIdentifier when exception is thrown.
___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/45639#-NRajRy1C6WkSJTspRL9:-NRajRy1C6WkSJTspRLA:b-yeey9a) ([raw file](https://github.com/harness/harness-core/blob/7103cdfe2923dafe2e8a4f76ae327777f3786b82/idp-service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java#L104)):*
> ```Java
> 
>   public void createAppConfigForGitIntegrations(String accountIdentifier, String orgIdentifier,
>       String projectIdentifier, String connectorIdentifier, ConnectorType connectorType) throws Exception {
> ```

InvalidRequestException is runtime exception. Do we need exception throw here ? Or somewhere else we are throwing ?

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45639)* status: 17 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/45639#-NRb03NmDJjAEHNuesQh:-NRb03NmDJjAEHNuesQi:bqgdzo2) ([raw file](https://github.com/harness/harness-core/blob/7103cdfe2923dafe2e8a4f76ae327777f3786b82/idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java#L40)):*
> ```Java
>   private static final String BITBUCKET_CONFIG_FILE = "configs/integrations/bitbucket.yaml";
>   private static final String AZURE_CONFIG_FILE = "configs/integrations/azure.yaml";
>   private static final String GITHUB_JSON_SCHEMA_FILE = "configs/integrations/github-schema.json";
> ```

can we keep a separate folder for schema validation file?



_Code quote:_
```Java
configs/integrations/github-schema.json
```

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45639)* status: 17 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java` line 101 at r1](https://reviewable.io/reviews/harness/harness-core/45639#-NRawLUaEFoe9lwVaCVd:-NRawLUaEFoe9lwVaCVe:b9iyq0v) ([raw file](https://github.com/harness/harness-core/blob/7103cdfe2923dafe2e8a4f76ae327777f3786b82/idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java#L101)):*
> ```Java
>         JsonSchemaFactory.builder(JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V7)).build();
>     try {
>       final JsonSchema jsonSchema = factory.getSchema(schema);
> ```

nit: we can return here itself
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/45639#-NRax1VW60fxzfsIjnvZ:-NRax1VW60fxzfsIjnv_:b-gwg1um) ([raw file](https://github.com/harness/harness-core/blob/7103cdfe2923dafe2e8a4f76ae327777f3786b82/idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java#L136)):*
> ```Java
>     JsonSchema schema = getJsonSchemaFromJsonNode(objectMapper.readTree(jsonSchema));
>     Set<String> invalidSchemaResponse = validateSchemaForYaml(yaml, schema);
>     return ((invalidSchemaResponse.size() > 0) ? false : true);
> ```

nit: return invalidSchemaResponse.size()<=0
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/45639#-NRajeN11aj7qKjfddUN:-NRb-ufrEbQL9KIB3xMX:b-l1ztgy) ([raw file](https://github.com/harness/harness-core/blob/7103cdfe2923dafe2e8a4f76ae327777f3786b82/idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java#L148)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

For all these switch cases, is it better to throw UnSupported exception ? or return null ?
</blockquote></details>

null would throw exception in validateSchemaForYaml -> readTree 
```throw new IllegalArgumentException(String.format("argument \"%s\" is null", paramName));```
UnSupportedException might be better
___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/45639#-NRajRy1C6WkSJTspRL9:-NRb0SI99hTkeMDJaKQa:b-iye63r) ([raw file](https://github.com/harness/harness-core/blob/7103cdfe2923dafe2e8a4f76ae327777f3786b82/idp-service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java#L104)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

InvalidRequestException is runtime exception. Do we need exception throw here ? Or somewhere else we are throwing ?
</blockquote></details>

Ig its being propagated from validateSchemaForYaml -> readTree.

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45639)* status: 17 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/45639#-NRb03NmDJjAEHNuesQh:-NRbEKSkDC3YRayIF8KZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7103cdfe2923dafe2e8a4f76ae327777f3786b82/idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java#L40)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

can we keep a separate folder for schema validation file?
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/45639#-NRajeN11aj7qKjfddUN:-NRblmXo1D_xhSX14VaW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7103cdfe2923dafe2e8a4f76ae327777f3786b82/idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java#L148)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

null would throw exception in validateSchemaForYaml -> readTree 
```throw new IllegalArgumentException(String.format("argument \"%s\" is null", paramName));```
UnSupportedException might be better
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/45639#-NRajNuW9LCT4CFYujY1:-NRbGYQFCfvYDb85I01M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7103cdfe2923dafe2e8a4f76ae327777f3786b82/idp-service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java#L54)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Please make sure that we are replacing the accountIdentifier when exception is thrown.
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/45639#-NRajRy1C6WkSJTspRL9:-NRbMAO-0UguKXY8sc23:b83mmzv) ([raw file](https://github.com/harness/harness-core/blob/7103cdfe2923dafe2e8a4f76ae327777f3786b82/idp-service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java#L104)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Ig its being propagated from validateSchemaForYaml -> readTree.
</blockquote></details>

this was not needed removed it, because integration configs we are exposing to users added validation so that we don't have to test in unit tests.

**Review by sathish-soundarapandian — APPROVED** [review]
> Reviewed 5 of 17 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45639)* status: 12 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45639)* status: 1. unresolved discussions.

**Review by vikyathharekal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45639)* status: 1. unresolved discussions.

**Review by vigneswara-propelo — APPROVED** [review]
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45639)* status: :shipit: complete! ✓

**Pull request merged**
