### PR TITLE
fix: [SRM-12015]: add negative test cases

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37937)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37937)

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37937)* status: 12 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 303 at r2](https://reviewable.io/reviews/harness/harness-core/37937#-NCxJQmO4Hs4HBhafa00:-NCxJQmO4Hs4HBhafa01:bu26lh1) ([raw file](https://github.com/harness/harness-core/blob/3765da6585df671aa84c85ec489f14e5584e860e/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L303)):*
> ```Java
>     Set<ConstraintViolation<MonitoredServiceDTO>> violations = validator.validate(monitoredServiceDTO);
>     violations.forEach(violation -> {
>       if (!getFieldFromPath(violation.getPropertyPath()).equals("tags")) {
> ```

Let's remove the null validation check from the DTO rather than adding it exception here.

**Comment by karansaraswat19** [comment]
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 303 at r2](https://reviewable.io/reviews/harness/harness-core/37937#-NCxJQmO4Hs4HBhafa00:-NCxYYps5MalO0clTOUw:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/3765da6585df671aa84c85ec489f14e5584e860e/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L303)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Let's remove the null validation check from the DTO rather than adding it exception here.
</blockquote></details>

ok

**Review by deepak-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37937)* status: Some of the checks are too old. 13 file(s) to review. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 304 at r4](https://reviewable.io/reviews/harness/harness-core/37937#-NDg7OF02DcMnGJYaUbq:-NDg7OF02DcMnGJYaUbr:bi53bl6) ([raw file](https://github.com/harness/harness-core/blob/a6c1e12219bcf65b6f2fa9d8a23d4a0618117f3f/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L304)):*
> ```Java
>     violations.forEach(violation -> {
>       throw new RuntimeException(getFieldFromPath(violation.getPropertyPath()) + " " + violation.getMessage());
>     });
> ```

nit: can be moved to utils class.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 8 of 12 files at r1, 1 of 4 files at r2, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37937)* status: :shipit: complete! ✓

**Pull request merged**
