### PR TITLE
feat: [CDS-57926]: most recent delegate selection logs support in approvals

### PR DESCRIPTION
**Pull request by naman-goenka**
## Describe your changes

- The latest delegate task id is available in execution v2 api → data → executionGraph → nodeMap → nodeMap of step → progressData → lastSelectedDelegateTask
- We will use this to call delegate selection API
- It will be called “Most Recent Delegate Selection Logs” in UI 
Screenshot 2023-03-24 at 4 04 22 PM

- **Testing** - For Jira, ServiceNow, Custom approvals locally checked the field is being populated and also updated (overwritten) with new delegate task id. Only validated by making the delegate selection call.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45609)

### CODE REVIEW

**Comment by naman-goenka** [comment]
> > Reviewed 4 of 9 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/45609)_ status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`pipeline-service/service/src/main/java/io/harness/pms/approval/custom/CustomApprovalHelperServiceImpl.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/45609#-NRIF1sg8PMrZFJToE6g:-NRIF1sg8PMrZFJToE6h:bbp6tzh) ([raw file](https://github.com/harness/harness-core/blob/04e5cff71cb72277b1eb3b253a029aaa57956290/pipeline-service/service/src/main/java/io/harness/pms/approval/custom/CustomApprovalHelperServiceImpl.java#L136)):_
> 
> > ```java
> >       String taskId = queueTask(ambiance, instance, scriptTaskParametersNG);
> > 
> >       if (isNotBlank(taskId)) {
> > ```
> 
> can you use EmptyPredicate.isNotEmpty, plus can you make it util to use

isNotBlank is being used to also consider strings like "  " which isEmtpy won't consider. The same is being automated too. It is part of StringUtils.isNotBlank

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45609)* status: 9 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/custom/CustomApprovalHelperServiceImpl.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/45609#-NRIF1sg8PMrZFJToE6g:-NRWZjOx4svCYkccgcWi:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/04e5cff71cb72277b1eb3b253a029aaa57956290/pipeline-service/service/src/main/java/io/harness/pms/approval/custom/CustomApprovalHelperServiceImpl.java#L136)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

isNotBlank is being used to also consider strings like "  " which isEmtpy won't consider. The same is being automated too. It is part of StringUtils.isNotBlank
</blockquote></details>

done

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45609)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by shivamnegi94 — APPROVED** [review]

**Review by shivamnegi94 — APPROVED** [review]
> Reviewed 5 of 9 files at r1, 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45609)* status: :shipit: complete! ✓

**Pull request merged**
