### PR TITLE
feat: [PL-30098]: RBAC Enforcement on Streaming Destination

### PR DESCRIPTION
**Pull request by reetika04**
## Describe your changes
RBAC enforcement on streaming destination.
Includes individual RBAC check for view on listing api.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42695)

### CODE REVIEW

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42695)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 130 at r2](https://reviewable.io/reviews/harness/harness-core/42695#-NM2ku3w2-qTAaqRkWh4:-NM2ku3w2-qTAaqRkWh5:b3027f) ([raw file](https://github.com/harness/harness-core/blob/9c238ac480aabbfc02b642f668e80dc595518710/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L130)):*
> ```Java
>                        .build())
>             .collect(Collectors.toList());
>     AccessCheckResponseDTO accessCheckResponse = accessControlClient.checkForAccess(permissionChecks);
> ```

Use AccessCheckResponseDTO checkForAccessOrThrow(List<PermissionCheckDTO> permissionCheckDTOList); to avoid batching in 1000 and having same logic spread across entities.

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42695)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 130 at r2](https://reviewable.io/reviews/harness/harness-core/42695#-NM2ku3w2-qTAaqRkWh4:-NM2sGXF6tKKKik5Oyn6:b-95ord8) ([raw file](https://github.com/harness/harness-core/blob/9c238ac480aabbfc02b642f668e80dc595518710/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L130)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Use AccessCheckResponseDTO checkForAccessOrThrow(List<PermissionCheckDTO> permissionCheckDTOList); to avoid batching in 1000 and having same logic spread across entities.
</blockquote></details>

checkForAccessOrThrow would throw an exception. In this case I would not want an exception thrown.

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42695)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 130 at r2](https://reviewable.io/reviews/harness/harness-core/42695#-NM2ku3w2-qTAaqRkWh4:-NM2xBjyBZ1aAv9e8amn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9c238ac480aabbfc02b642f668e80dc595518710/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L130)):*
<details><summary><i>Previously, reetika04 (Reetika) wrote…</i></summary><blockquote>

checkForAccessOrThrow would throw an exception. In this case I would not want an exception thrown.
</blockquote></details>

Done.

**Review by Jimit09Gandhi — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42695#-:-NM2zuvh21TrwcU-mU6u:bnfp4nl)* status: 8 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42695)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42695#-:-NM7WBsKB61ar-uWwzJw:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
