### PR TITLE
techdebt: [DEL-0]: Use Non Versioned gRPC channel for Delegate Driver

### PR DESCRIPTION
**Pull request by ankit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31903)

### CODE REVIEW

**Comment by jennyjames21** [comment]
*[910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceDriverGrpcClientModule.java, line 92 at r1](https://reviewable.io/reviews/harness/harness-core/31903#-MzT_0aW08GkepJCpVqe:-MzT_0aW08GkepJCpVqf:bj7njkx) ([raw file](https://github.com/harness/harness-core/blob/331b3d60acc1424bd2219af00613fdb29646c323/910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceDriverGrpcClientModule.java#L92)):*
> ```Java
>         authorityToUse = authority;
>       }
>     } else {
> ```

you may want to test this after removing version from config. Clean up from ingress file also.



Currently it's using with version in prod.

**Comment by jennyjames21** [comment]
*[910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceManagementDriverGrpcClientModule.java, line 83 at r1](https://reviewable.io/reviews/harness/harness-core/31903#-MzT_vQkAqlZEg787ww9:-MzT_vQkAqlZEg787wwA:b-iu9nbn) ([raw file](https://github.com/harness/harness-core/blob/331b3d60acc1424bd2219af00613fdb29646c323/910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceManagementDriverGrpcClientModule.java#L83)):*
> ```Java
>         log.info("Versioned authority {} is invalid. Using non-versioned", versionedAuthority);
>         authorityToUse = authority;
>       }
> ```

you can ignore this file, i will delete this file as it's no more in use

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31903)* status: 1 file(s) to review. 0 of 1 approvals obtained.

**Comment by abhinav-harness** [comment]
@ankit-harness lgtm only thing is we should have primary ingress in all the env, I saw they do have but second set of eyes are always better here

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31903)* status: 0 of 1 approvals obtained.

**Review by ankit-harness — COMMENTED** [review]
Checked in all envs PRE-QA, QA (Paid, Free), Prod (Prod1, Prod2, Prod3). Manager service do have primary ingress.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31903#-:-MzVh3JH3nCaY4le8K7o:b9i0lr8)* status: 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceDriverGrpcClientModule.java, line 92 at r1](https://reviewable.io/reviews/harness/harness-core/31903#-MzT_0aW08GkepJCpVqe:-MzVhV_U-2YPpsBAO2oP:bziest8) ([raw file](https://github.com/harness/harness-core/blob/331b3d60acc1424bd2219af00613fdb29646c323/910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceDriverGrpcClientModule.java#L92)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

you may want to test this after removing version from config. Clean up from ingress file also.



Currently it's using with version in prod.


</blockquote></details>

We can remove versioned ingresses in 2nd iteration. In this PR, we are making the change to just use primary ingresses. Once it is released, we can remove versioned ingresses.
___
*[910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceManagementDriverGrpcClientModule.java, line 83 at r1](https://reviewable.io/reviews/harness/harness-core/31903#-MzT_vQkAqlZEg787ww9:-MzVhL8YAWrNlVrNsvHS:b-n44ktw) ([raw file](https://github.com/harness/harness-core/blob/331b3d60acc1424bd2219af00613fdb29646c323/910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceManagementDriverGrpcClientModule.java#L83)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

you can ignore this file, i will delete this file as it's no more in use
</blockquote></details>

Sure. u can delete this

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31903)* status: Some of the checks are too old. 2. unresolved discussions.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31903)* status: 2. unresolved discussions.

**Pull request merged**
