### PR TITLE
[feat]: [CDS-83730] : adding gitX settings to service/env

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes

adding below settings in env/service create call
default_connector_for_git_experience
enforce_git_experience
default_store_type_for_entities
default_repo_for_git_experience

Screenshot 2023-11-16 at 6 34 48 PM

Screenshot 2023-11-16 at 6 39 44 PM

test cases : 
inline service/env creation (normal)
remote service/env creation (normal)
remote service/env creation with enforce_git_experience
remote service/env creation with empty repo/storeType/connectorRef as shown in above image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55467)

### CODE REVIEW

**Comment by tchaurasiya** [comment]
trigger uts

**Comment by tchaurasiya** [comment]
trigger smartchecks

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55467)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by adivishy1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55467)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1221 at r2](https://reviewable.io/reviews/harness/harness-core/55467#-NjQaHu81f27IK_PVhKB:-NjQaHu81f27IK_PVhKC:b55y9xt) ([raw file](https://github.com/harness/harness-core/blob/3d10cbb4ce310af9250bf450243c1ce97e0ed612/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1221)):*
> ```Java
>     gitXSettingsHelper.setDefaultStoreTypeForEntities(
>         accountIdentifier, orgIdentifier, projIdentifier, EntityType.ENVIRONMENT);
>     gitXSettingsHelper.setConnectorRefForRemoteEntity(accountIdentifier, orgIdentifier, projIdentifier);
> ```

i see we are doing the same for the ServiceEntity as well, can pass the entityType with other params into a common place instead of duplicating the applyGitXSettings?

**Review by senjucanon2 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55467#-:-NjQcImC6YgvqPu3gNlm:bnfp4nl)* status: 1 change requests. 1 of 2 approvals obtained.

**Comment by tchaurasiya** [comment]
> > Reviewed 4 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/55467)_ status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1221 at r2](https://reviewable.io/reviews/harness/harness-core/55467#-NjQaHu81f27IK_PVhKB:-NjQaHu81f27IK_PVhKC:b55y9xt) ([raw file](https://github.com/harness/harness-core/blob/3d10cbb4ce310af9250bf450243c1ce97e0ed612/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1221)):_
> 
> > ```java
> >     gitXSettingsHelper.setDefaultStoreTypeForEntities(
> >         accountIdentifier, orgIdentifier, projIdentifier, EntityType.ENVIRONMENT);
> >     gitXSettingsHelper.setConnectorRefForRemoteEntity(accountIdentifier, orgIdentifier, projIdentifier);
> > ```
> 
> i see we are doing the same for the ServiceEntity as well, can pass the entityType with other params into a common place instead of duplicating the applyGitXSettings?

Just keeping the code separate for both entity(Like pipeline/inputset) so that any new setting and behavioural differences can be accomadated as feature develops.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55467)* status: :shipit: complete! ✓

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1221 at r2](https://reviewable.io/reviews/harness/harness-core/55467#-NjQaHu81f27IK_PVhKB:-NjQd9Gr-OKdzoiEdxRq:bx54lkc) ([raw file](https://github.com/harness/harness-core/blob/3d10cbb4ce310af9250bf450243c1ce97e0ed612/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1221)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Just keeping the code separate for both entity(Like pipeline/inputset) so that any new setting and behavioural differences can be accomadated  separately as feature develops.
</blockquote></details>

okay, sounds good

**Comment by tchaurasiya** [comment]
trigger review

**Comment by tchaurasiya** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55467)* status: :shipit: complete! ✓

**Pull request merged**
