### PR TITLE
[feat]: [CDS-82263] : validation and refresh helper change for remote environment

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes
Changes include
* isValid - for environment inputs
* reconcile for environment inputs

Tested
* environment used in pipeline 
* environment used in template

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54544)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/EnvironmentService.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/54544#-NhcI38U9CcB7wWnDcOw:-NhcI38U9CcB7wWnDcOx:blltq6p) ([raw file](https://github.com/harness/harness-core/blob/6c671dce04adeb0d249ac6578fd3f4d35415bcf2/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/EnvironmentService.java#L80)):*
> ```Java
>   @Deprecated(since = "This method does not handle remote environment")
>   String createEnvironmentInputsYaml(
>       String accountId, String orgIdentifier, String projectIdentifier, String envIdentifier);
> ```

Can we not just add the branch parameter here and set the default value to null for every caller ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54544)* status: 6 file(s) to review. 0 of 2 approvals obtained.

**Review by hingerabhinav — COMMENTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54544)* status: 8 file(s) to review. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/EnvironmentRefreshHelper.java` line 499 at r1](https://reviewable.io/reviews/harness/harness-core/54544#-NheO9Wo7tftmG4rLr7F:-NheO9Wo7tftmG4rLr7G:bknstfz) ([raw file](https://github.com/harness/harness-core/blob/6c671dce04adeb0d249ac6578fd3f4d35415bcf2/120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/EnvironmentRefreshHelper.java#L499)):*
> ```Java
>     boolean overridesV2Enabled = overrideV2ValidationHelper.isOverridesV2Enabled(
>         context.getAccountId(), context.getOrgId(), context.getProjectId());
>     if (overridesV2Enabled) {
> ```

is v2 overrides and remote environment different flows? Can we discuss this once? 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentYamlV2VisitorHelper.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/54544#-NheORjVE9o7cp903mj1:-NheORjVE9o7cp903mj2:blpiy39) ([raw file](https://github.com/harness/harness-core/blob/6c671dce04adeb0d249ac6578fd3f4d35415bcf2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentYamlV2VisitorHelper.java#L71)):*
> ```Java
>       return addReferencesInternal(
>           (EnvironmentYamlV2) object, accountIdentifier, orgIdentifier, projectIdentifier, contextMap);
>     } catch (Exception ex) {
> ```

Should we bubble up git errors instead of blanket consuming all exceptions. HintException, ScmException etc. should be shown to the user so they can fix their pipelines. Made a similar change in Service visitor helper.

**Comment by tchaurasiya** [comment]
> _[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/EnvironmentService.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/54544#-NhcI38U9CcB7wWnDcOw:-NhcI38U9CcB7wWnDcOx:blltq6p) ([raw file](https://github.com/harness/harness-core/blob/6c671dce04adeb0d249ac6578fd3f4d35415bcf2/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/EnvironmentService.java#L80)):_
> 
> > ```java
> >   @Deprecated(since = "This method does not handle remote environment")
> >   String createEnvironmentInputsYaml(
> >       String accountId, String orgIdentifier, String projectIdentifier, String envIdentifier);
> > ```
> 
> Can we not just add the branch parameter here and set the default value to null for every caller ?

done.

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 8 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54544)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 8 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54544)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
trigger review

**Comment by yogesh-chauhan** [comment]
trigger uts

**Pull request merged**
