### PR TITLE
fix: [PIE-7914]: fix wait step status step race condition

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes
**Issue:** There was a race condition in the case of the status of planExecutionSummary. Orchestration graph update was also updating the status of planExecutionsSummary and NodeStatusObserver as well. since the orchestration graph update is consuming from redis so sometimes it can be a bit slow and it was overriding the status from wait step running to running. 

**Change:** We removed status update from orchestration graph because it is anyway done by PlanExecutionService.

**Testing:** Tested the behaviour in local and PR env.
- Tested by running a pipeline with a custom stage and 2 wait steps under that stage. When first step is running, I paused the pipeline and when resumed that another wait step starts, now at this time, status of pipeline should be WaitStepRunning, earlier it used to come as running sometimes, This was due to the race condition mentioned above. After doing above changes, this race condition doesn't exist anymore.

**Backward Compatibility**
- There is no change in schema or recaster alias, hence the change is backward compatible.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43295)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 4 files at r2, 9 of 12 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43295)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/observers/PipelineExecutionSummaryFailureInfoUpdateHandler.java` line 33 at r4](https://reviewable.io/reviews/harness/harness-core/43295#-NODXwTy-NZF3dCwVCiv:-NODXwTzA69ntSX1-anK:b-sobvc1) ([raw file](https://github.com/harness/harness-core/blob/1433630e94f120c966147e2e6c628e791555ad74/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/observers/PipelineExecutionSummaryFailureInfoUpdateHandler.java#L33)):*
> ```Java
>     String nodeExecutionId = nodeUpdateInfo.getNodeExecutionId();
>     String planExecutionId = nodeUpdateInfo.getPlanExecutionId();
>     NodeExecution nodeExecution = nodeExecutionService.get(nodeExecutionId);
> ```

its already there in nodeUpdateInfo, so not needed



_Code quote:_
```Java
odeExecution nodeExecution = nodeExecutionService.get(nodeExecutionId)
```
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryService.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/43295#-NODY5wyBtJaMXBPDz4a:-NODY5wyBtJaMXBPDz4b:bgbj1lz) ([raw file](https://github.com/harness/harness-core/blob/1433630e94f120c966147e2e6c628e791555ad74/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryService.java#L24)):*
> ```Java
>   void regenerateStageLayoutGraph(String planExecutionId, List<NodeExecution> nodeExecutions);
>   void update(String planExecutionId, Update update);
>   PipelineExecutionSummaryEntity save(PipelineExecutionSummaryEntity pipelineExecutionSummaryEntity);
> ```

add comments to what this method do
___
*[`pipeline-service/modules/orchestration-visualization/src/test/java/io/harness/obsevers/PipelineExecutionSummaryFailureInfoUpdateHandlerTest.java` line 53 at r4](https://reviewable.io/reviews/harness/harness-core/43295#-NODYAgdEMUbLxlSE1MF:-NODYAge2Hby0TEHm_8A:b-qfheox) ([raw file](https://github.com/harness/harness-core/blob/1433630e94f120c966147e2e6c628e791555ad74/pipeline-service/modules/orchestration-visualization/src/test/java/io/harness/obsevers/PipelineExecutionSummaryFailureInfoUpdateHandlerTest.java#L53)):*
> ```Java
> import org.springframework.data.mongodb.core.query.Update;
> 
> public class PipelineExecutionSummaryFailureInfoUpdateHandlerTest extends OrchestrationVisualizationTestBase {
> ```

use categoryTest as you are not using @inject

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43295)* status: 14 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/observers/PipelineExecutionSummaryFailureInfoUpdateHandler.java` line 33 at r4](https://reviewable.io/reviews/harness/harness-core/43295#-NODXwTy-NZF3dCwVCiv:-NODZWUn3Tn_dz_3dn1C:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1433630e94f120c966147e2e6c628e791555ad74/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/observers/PipelineExecutionSummaryFailureInfoUpdateHandler.java#L33)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

its already there in nodeUpdateInfo, so not needed
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryService.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/43295#-NODY5wyBtJaMXBPDz4a:-NODZVyi2jv5A3Aifunn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1433630e94f120c966147e2e6c628e791555ad74/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryService.java#L24)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comments to what this method do
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-visualization/src/test/java/io/harness/obsevers/PipelineExecutionSummaryFailureInfoUpdateHandlerTest.java` line 53 at r4](https://reviewable.io/reviews/harness/harness-core/43295#-NODYAgdEMUbLxlSE1MF:-NOD_N9e7No3dpXSRqZq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1433630e94f120c966147e2e6c628e791555ad74/pipeline-service/modules/orchestration-visualization/src/test/java/io/harness/obsevers/PipelineExecutionSummaryFailureInfoUpdateHandlerTest.java#L53)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use categoryTest as you are not using @inject
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43295)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 4 files at r2, 7 of 12 files at r3, 2 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43295)* status: :shipit: complete! ✓

**Pull request merged**
