### PR TITLE
feat: [PL-29891]: changes for login flow to load only supportAccounts' Ids

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
login api sends supportAccounts which are used by gateway and gateway requires only accountIds, so changes has been done to send accountIds in this api through projection.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41044)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41044)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 965 at r2](https://reviewable.io/reviews/harness/harness-core/41044#-NIIYRzH380dlJbxhKBx:-NIIYRzI0O5wmRrIvyuj:bcvtooo) ([raw file](https://github.com/harness/harness-core/blob/9b66540b4bf308d1b8e3ae586e1654d4499663c6/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L965)):*
> ```Java
> 
>   @Override
>   public List<Account> listHarnessSupportAccounts(Set<String> excludedAccountIds, boolean includeOnlyIds) {
> ```

Can we have a method signature like this defined in this PR - 

public List<Account> listHarnessSupportAccounts(Set<String> excludedAccountIds)) -> This method will return complete support accounts

and 

public List<Account> listHarnessSupportAccounts(Set<String> excludedAccountIds), String[] fieldsToInclude) -> This method will return support accounts with passed in fields


Goal should be to convert both the APIs into paginated APIs 
___
*[`400-rest/src/main/java/software/wings/service/intfc/UserService.java` line 228 at r2](https://reviewable.io/reviews/harness/harness-core/41044#-NIIWw6AAVGVGR0A4jlE:-NIIWw6AAVGVGR0A4jlF:bl86y21) ([raw file](https://github.com/harness/harness-core/blob/9b66540b4bf308d1b8e3ae586e1654d4499663c6/400-rest/src/main/java/software/wings/service/intfc/UserService.java#L228)):*
> ```Java
>   User get(@NotEmpty String accountId, @NotEmpty String userId);
> 
>   void loadSupportAccounts(User user, boolean includeOnlyId);
> ```

includeOnlyIds

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41044)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 536 at r4](https://reviewable.io/reviews/harness/harness-core/41044#-NIXIAaGBak_tWZnEuVD:-NIXIAaGBak_tWZnEuVE:b-e4h0i) ([raw file](https://github.com/harness/harness-core/blob/3ba80063c3004a03aa2828f1d6b157218de5447e/400-rest/src/main/java/software/wings/resources/UserResource.java#L536)):*
> ```Java
>     User user = UserThreadLocal.get().getPublicUser();
>     if (isEmpty(user.getSupportAccounts())) {
>       userService.loadSupportAccounts(user, null);
> ```

Let's have 2 methods. Passing null is an anti-pattern.
___
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 278 at r4](https://reviewable.io/reviews/harness/harness-core/41044#-NIXIQ_L9fD8s1Lj3SKB:-NIXIQ_L9fD8s1Lj3SKC:bj73o81) ([raw file](https://github.com/harness/harness-core/blob/3ba80063c3004a03aa2828f1d6b157218de5447e/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L278)):*
> ```Java
>     User user = userService.getUserByEmail(email);
>     if (user.getSupportAccounts() == null) {
>       userService.loadSupportAccounts(user, new HashSet<>(Collections.singleton(AccountKeys.uuid)));
> ```

Set.of(AccountKeys.uuid)

**Review by ankit-harness — DISMISSED** [review]
> Reviewed 4 of 10 files at r3, 4 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41044)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41044)* status: 11 file(s) to review.

**Review by rijajoo — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41044#-:-NIgi5iyDkRLTNVb3AT_:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 3 of 10 files at r3, 2 of 6 files at r5, 1 of 2 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41044)* status: :shipit: complete! ✓

**Pull request merged**
