### PR TITLE
feat: [PL-29264]: added exception mapper for mongoExecutionTimeout

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
Screenshot 2022-10-21 at 9 54 25 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39118)

### CODE REVIEW

**Comment by abhinav-harness** [comment]
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 272 at r1](https://reviewable.io/reviews/harness/harness-core/39118#-NEvkZdDAIKHwv5xlRM7:-NEvkZdDAIKHwv5xlRM8:b-2nmu3s) ([raw file](https://github.com/harness/harness-core/blob/f34cb57a931e7734619d78b06cebb8accfbda07a/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L272)):*
> ```Java
>         log.error("count operation for collection [{}] exceeded max time limit of [{}] ms with error {}.",
>             collectionName, maxOperationInMillis, ex);
>         throw(MongoExecutionTimeoutException) ex.getCause();
> ```

why not just rethrow it and throw just the cause?

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39118)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 792 at r1](https://reviewable.io/reviews/harness/harness-core/39118#-NExxqL2BBBIFV9YrHJW:-NExxqL37pBublGBqk0l:bm4xk8e) ([raw file](https://github.com/harness/harness-core/blob/f34cb57a931e7734619d78b06cebb8accfbda07a/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L792)):*
> ```Java
>     environment.jersey().register(GenericExceptionMapperV2.class);
>     environment.jersey().register(NotSupportedExceptionMapper.class);
>     environment.jersey().register(MongoExecutionTimeoutExceptionMapper.class);
> ```

We will have to register it in WingsApplication as well? But there the exception might be different as we are using Morphia

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39118)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 792 at r1](https://reviewable.io/reviews/harness/harness-core/39118#-NExxqL2BBBIFV9YrHJW:-NFNeSD99IKx7yX64X6s:bs1l63t) ([raw file](https://github.com/harness/harness-core/blob/f34cb57a931e7734619d78b06cebb8accfbda07a/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L792)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We will have to register it in WingsApplication as well? But there the exception might be different as we are using Morphia
</blockquote></details>

yes, i was going to raise another pr for it, but that'a a one line change, added it here only. 
Morphia directly throws MongoExecutionTimeoutException
while Spring throws UncategorizedDbException for it 
___
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 272 at r1](https://reviewable.io/reviews/harness/harness-core/39118#-NEvkZdDAIKHwv5xlRM7:-NFNeeKx3TYlhKGOj_TR:b27e7re) ([raw file](https://github.com/harness/harness-core/blob/f34cb57a931e7734619d78b06cebb8accfbda07a/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L272)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

why not just rethrow it and throw just the cause?
</blockquote></details>

We cannot rethrow the exception, because that is UncategorizedDbException and mapper is written on MongoExecutiontimeoutException, which is one of its cause, that's cause is thrown.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39118#-:-NFNxiWi1tGI6fxzk33h:bnfp4nl)* status: 6 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39118)* status: 6 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39118)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
trigger codebasehash

**Pull request merged**
