### PR TITLE
feat: [PL-21391]: Git Move Ops SDK side changes

### PR DESCRIPTION
**Pull request by mohitg0795**
- Making updateGitFilePath calls git aware for all entities
- Breaking incoming file path into folder path and file path to save in entity
- Handling semantics for root folder

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30200)

### CODE REVIEW

**Comment by mohitg0795** [comment]
trigger messagecheck

**Review by namanvermah — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30200)* status: 20 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java, line 156 at r2](https://reviewable.io/reviews/harness/harness-core/30200#-MuOr_511t1lJuHZ-is4:-MuOr_511t1lJuHZ-is5:bp5ls83) ([raw file](https://github.com/harness/harness-core/blob/9d142fc0efa3fcc255186c5e1d6f9500e7f4d04b/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L156)):*
> ```Java
>         projectIdentifier, orgIdentifier, accountIdentifier, InputSetEntity.class);
>     if (gitSyncCriteria != null) {
>       criteria = new Criteria().andOperator(criteria, gitSyncCriteria);
> ```

Shouldn't this part be another method in git aware persistence? I see the same block of code here and in template handling as well



_Code quote:_
```Java
    Criteria gitSyncCriteria = gitAwarePersistence.getCriteriaWithGitSync(
        projectIdentifier, orgIdentifier, accountIdentifier, InputSetEntity.class);
    if (gitSyncCriteria != null) {
      criteria = new Criteria().andOperator(criteria, gitSyncCriteria);
    }
```

**Review by archit-harness — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 11 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30200)* status: 20 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java, line 156 at r2](https://reviewable.io/reviews/harness/harness-core/30200#-MuOr_511t1lJuHZ-is4:-MuOzk_s4RGIu1TO1dqM:bmkbfkz) ([raw file](https://github.com/harness/harness-core/blob/9d142fc0efa3fcc255186c5e1d6f9500e7f4d04b/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L156)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Shouldn't this part be another method in git aware persistence? I see the same block of code here and in template handling as well
</blockquote></details>

I agree to this point

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30200)* status: 20 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java, line 156 at r2](https://reviewable.io/reviews/harness/harness-core/30200#-MuOr_511t1lJuHZ-is4:-MuP19PFBJCWcLFo-n4i:b-ai8q8f) ([raw file](https://github.com/harness/harness-core/blob/9d142fc0efa3fcc255186c5e1d6f9500e7f4d04b/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L156)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I agree to this point
</blockquote></details>

This was already handled this way in PMS. I just replicated it for template service and input sets.

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30200)* status: 20 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java, line 156 at r2](https://reviewable.io/reviews/harness/harness-core/30200#-MuOr_511t1lJuHZ-is4:-MuP243lEDkoYs_h-Nfz:bly75c) ([raw file](https://github.com/harness/harness-core/blob/9d142fc0efa3fcc255186c5e1d6f9500e7f4d04b/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L156)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This was already handled this way in PMS. I just replicated it for template service and input sets.
</blockquote></details>

Let me make it part of git sync for all

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 18 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30200)* status: 24 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 15 of 18 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30200#-:-MuPBE29DFVdjL4S4Cp6:bnfp4nl)* status: :shipit: complete! ✓

**Review by bhavya181 — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 15 of 18 files at r2, 6 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30200)* status: 1 file(s) to review.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30200)* status: :shipit: complete! ✓

**Pull request merged**
