### PR TITLE
fix:[CDS-46314]: Enable variable substitution when evaluating an expression

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
The `evaluateExpression` method creates a new instance of `StrSubstitutor` and does not set the property `enableSubstitutionInVariables` to **true** to enable the nested variable substitution when evaluating the expression.

The property is already settled in `renderExpression` method.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40254)

### CODE REVIEW

**Review by hextechpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40254)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/CanaryWorkflowExecutionAdvisor.java` line 522 at r2](https://reviewable.io/reviews/harness/harness-core/40254#-NH38Gj61hv_sjntcu4I:-NH38Gj61hv_sjntcu4J:b-o5ys6u) ([raw file](https://github.com/harness/harness-core/blob/6b6dd06b37868bf283f38748c0eaceaddde2ca58/400-rest/src/main/java/software/wings/beans/CanaryWorkflowExecutionAdvisor.java#L522)):*
> ```Java
>       try {
>         logAppDefaults(context, featureFlagService);
>         final String expression = context.renderExpression(assertionExpression);
> ```

Do you need to render, direct evaluate should work. I am not sure why we are rendering it here

**Review by hextechpal — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40254)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40254)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/CanaryWorkflowExecutionAdvisor.java` line 522 at r2](https://reviewable.io/reviews/harness/harness-core/40254#-NH38Gj61hv_sjntcu4I:-NH3X3RR0SSHo_WFqevJ:b-fxtrc) ([raw file](https://github.com/harness/harness-core/blob/6b6dd06b37868bf283f38748c0eaceaddde2ca58/400-rest/src/main/java/software/wings/beans/CanaryWorkflowExecutionAdvisor.java#L522)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Do you need to render, direct evaluate should work. I am not sure why we are rendering it here 
</blockquote></details>

It was done to show expression resolution in execution context. Done with this ticket: https://harness.atlassian.net/browse/CDS-31387

What we observed was that evaluate is not able to resolve nested expression.

**Review by hextechpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40254)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/CanaryWorkflowExecutionAdvisor.java` line 522 at r2](https://reviewable.io/reviews/harness/harness-core/40254#-NH38Gj61hv_sjntcu4I:-NH3dwxhBIYFTVP3aEcY:b-v0h53l) ([raw file](https://github.com/harness/harness-core/blob/6b6dd06b37868bf283f38748c0eaceaddde2ca58/400-rest/src/main/java/software/wings/beans/CanaryWorkflowExecutionAdvisor.java#L522)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

It was done to show expression resolution in execution context. Done with this ticket: https://harness.atlassian.net/browse/CDS-31387

What we observed was that evaluate is not able to resolve nested expression. 
</blockquote></details>

I think that should not happen can we did deep why is that case

**Review by hextechpal — APPROVED** [review]
> Reviewed 2 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40254)* status: :shipit: complete! ✓

**Pull request merged**
