### PR TITLE
feat: [SRM-9874]: Exclude Error Tracking from the verify log view

### PR DESCRIPTION
**Pull request by DFieldFL**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31821)

### CODE REVIEW

**Comment by DFieldFL** [comment]
retrigger messagecheck

**Review by kanhaiyarat — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31821)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImpl.java, line 552 at r1](https://reviewable.io/reviews/harness/harness-core/31821#-MzRc8j-EuyNdZexrXnu:-MzRc8j-EuyNdZexrXnv:bur5son) ([raw file](https://github.com/harness/harness-core/blob/336f067fcf9facb38c6412761c5361ebc628efb6/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImpl.java#L552)):*
> ```Java
>       if (!ERROR_TRACKING.name().equals(verificationTask.getTags().get(TAG_DATA_SOURCE))) {
>         resultSummary = deploymentLogAnalysis.getResultSummary();
>       }
> ```

I think you should be using verificationTaskService to get the verificationTask rather than directly fetching it from database. 
The idea of creating service is it handles the functions/operations on that particular entity.

**Review by DFieldFL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31821)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImpl.java, line 552 at r1](https://reviewable.io/reviews/harness/harness-core/31821#-MzRc8j-EuyNdZexrXnu:-MzV3-RUCmYjBq4EDuHF:b3hp3qh) ([raw file](https://github.com/harness/harness-core/blob/336f067fcf9facb38c6412761c5361ebc628efb6/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImpl.java#L552)):*
<details><summary><i>Previously, kanhaiyarat (Kanhaiya Rathi) wrote…</i></summary><blockquote>

I think you should be using verificationTaskService to get the verificationTask rather than directly fetching it from database. 
The idea of creating service is it handles the functions/operations on that particular entity. 

</blockquote></details>

Good point. I will need to add that query to the service.

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31821)* status: 1 change requests. 1. unresolved discussions.

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31821#-:-N-wpC2K0iCAynb6h8IK:bnfp4nl)* status: 1 change requests. 1. unresolved discussions.

**Review by ccaspanello — APPROVED** [review]

**Review by DFieldFL — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31821)* status: 1 change requests. 1. unresolved discussions.

**Pull request merged**
