### PR TITLE
feat: [PIE-2861]: Adding logging for finding time spent for plan creation and template service resolution

### PR DESCRIPTION
**Pull request by archit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31120)

### CODE REVIEW

**Review by hextechpal — DISMISSED** [review]
> Reviewed 6 of 25 files at r1, 39 of 39 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31120)* status: 45 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 25 files at r1, 28 of 39 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31120)* status: 11 file(s) to review.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 6 of 25 files at r1, 28 of 39 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31120)* status: 11 file(s) to review.

**Review by sahilhindwani-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31120)* status: 11 file(s) to review.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31120#-:-My64boi7ktX2beE8mgg:bnfp4nl)* status: 25 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 11 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31120)* status: 14 file(s) to review.

**Pull request merged**
