### PR TITLE
Feat: [SRM-14011]: Add api for metric onboarding graph

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44245)

### CODE REVIEW

**Review by dhruv-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44245)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/sli/MetricOnboardingGraph.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx5q1NAZ-HaSwipACH:-NOx5q1NAZ-HaSwipACI:bm14fau) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/sli/MetricOnboardingGraph.java#L29)):*
> ```Java
>   @SuperBuilder
>   public static class RatioMetricPercentageGraph extends TimeGraphResponse {
>     private String metricIdentifier1;
> ```

Can we rename these members to something more meaningful?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/ServiceLevelIndicatorResource.java` line 87 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx6R9M6vKpg2nLJwpn:-NOx6R9M6vKpg2nLJwpo:b-9qo7nq) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/ServiceLevelIndicatorResource.java#L87)):*
> ```Java
>       @NotNull @QueryParam("healthSourceRef") String healthSourceRef,
>       @QueryParam("ratioSLIMetricEventType") RatioSLIMetricEventType ratioSLIMetricEventType,
>       @NotNull @Valid @Body List<String> metricIdentifiers) {
> ```

We can add validation for size in the definition itself. @Min @Max @Size can be used.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/MetricDataCollectionInfoMapper.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx7R6o1DsfRvFH1uip:-NOx7R6o1DsfRvFH1uiq:bu799lz) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/MetricDataCollectionInfoMapper.java#L50)):*
> ```Java
>                          .filter(cvConfig -> cvConfig.isSLIEnabled())
>                          .findAny()
>                          .orElseThrow(() -> new IllegalStateException("No SLI Enabled CV Configs found"));
> ```

Is this method specific to SLI use-cases? If yes we should refactor the name to convey the intent of the method clearly.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java` line 183 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx8NVwEWAyYl11eDoR:-NOx8NVwEWAyYl11eDoS:bf9twtj) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java#L183)):*
> ```Java
>   }
> 
>   public MetricOnboardingGraph getMetricGraphs(ProjectParams projectParams, String monitoredServiceIdentifier,
> ```

nit: Override annotation is missing
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java` line 187 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx8dR89S1uQENZsmRE:-NOx8dR89S1uQENZsmRF:bzh6h4e) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java#L187)):*
> ```Java
>       String tracingId) {
>     List<CVConfig> cvConfigs = getCvConfigs(projectParams, monitoredServiceIdentifier, healthSourceRef);
>     Preconditions.checkArgument(isNotEmpty(cvConfigs), "Health source not present");
> ```

Looks like this is getting repeated in different methods and we only need 1 cvConfig. Lets extract this out in an appropriate method.



_Code quote:_
```Java
    List<CVConfig> cvConfigs = getCvConfigs(projectParams, monitoredServiceIdentifier, healthSourceRef);
    Preconditions.checkArgument(isNotEmpty(cvConfigs), "Health source not present");
    CVConfig baseCVConfig = cvConfigs.get(0);
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java` line 191 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx99Vw1npEa8XWUTn0:-NOx99Vw1npEa8XWUTn1:bqgkqk4) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java#L191)):*
> ```Java
>     DataCollectionInfo dataCollectionInfo = dataSourceTypeDataCollectionInfoMapperMap.get(baseCVConfig.getType())
>                                                 .toDataCollectionInfo(cvConfigs, metricIdentifiers);
>     cvConfigs.stream()
> ```

Are we using the result of this anywhere?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java` line 239 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx9JIB4dCHVw-NqGJF:-NOx9JIB4dCHVw-NqGJG:b-bmcb9f) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java#L239)):*
> ```Java
>     OnboardingResponseDTO response =
>         onboardingService.getOnboardingResponse(projectParams.getAccountIdentifier(), onboardingRequestDTO);
>     final Gson gson = new Gson();
> ```

We can use JsonUtils instead of instantiating Gson object
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java` line 517 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx9p2O38Y3CMG1NaJK:-NOx9p2P7H-_ZMFsIC7D:bqo3f7v) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java#L517)):*
> ```Java
>                .dataPoints(entry.getValue()
>                                .stream()
>                                .sorted((c1, c2) -> c1.getTimeStamp() < c2.getTimeStamp() ? -1 : 1)
> ```

nit: We can rename c1, c2 to something more meaningful 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java` line 529 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOxA5m_AxQ1WODhwS0W:-NOxA5m_AxQ1WODhwS0X:b-9ywqtz) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java#L529)):*
> ```Java
>     }
>     List<DataPoints> dataPoints = new ArrayList<>();
>     Map<Long, Double> metric1Map = new HashMap<>();
> ```

nit: variable name can be more meaningful
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/resources/ServiceLevelIndicatorResourceTest.java` line 99 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOxAGPz6zeYE8ecgZU4:-NOxAGPz6zeYE8ecgZU5:bcw0z4x) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/resources/ServiceLevelIndicatorResourceTest.java#L99)):*
> ```Java
>   private String connectorIdentifier;
>   private String monitoredServiceIdentifier;
>   OnboardingRequestDTO onboardingRequestDTO;
> ```

Access modifier should be private



_Code quote:_
```Java
  OnboardingRequestDTO onboardingRequestDTO;
  String textLoad;
  ServiceLevelIndicatorDTO serviceLevelIndicatorDTO;

  String healthSourceRef;
  CVConfig cvConfig;
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/servicelevelobjective/ServiceLevelIndicatorServiceImplTest.java` line 180 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOxAfym7O1-bL58f_A-:-NOxAfym7O1-bL58f_A0:b-pwqu6) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/servicelevelobjective/ServiceLevelIndicatorServiceImplTest.java#L180)):*
> ```Java
> 
>   @Test
>   @Owner(developers = ABHIJITH)
> ```

Please ensure developer name is correct

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44245)* status: 4 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/sli/MetricOnboardingGraph.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx5q1NAZ-HaSwipACH:-NOy5Rxn8IdJwXPQ2HAn:b-ig8ta2) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/sli/MetricOnboardingGraph.java#L29)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Can we rename these members to something more meaningful?
</blockquote></details>

We have defined metric1 and metric2 in ratioSLI, added metricIdentifier as it's identifier.  Can't do anything for 1 and 2.



_Code quote:_
```Java
RatioMetricPercentageGraph
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/ServiceLevelIndicatorResource.java` line 87 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx6R9M6vKpg2nLJwpn:-NOy6BDlBhughChu-3zu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/ServiceLevelIndicatorResource.java#L87)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

We can add validation for size in the definition itself. @Min @Max @Size can be used.
</blockquote></details>

Done.



_Code quote:_
```Java
@NotNull @Valid @Body List<String> metricIdentifiers)
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/MetricDataCollectionInfoMapper.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx7R6o1DsfRvFH1uip:-NOy6VM28Uxbd0EZqDZc:b-9dol62) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/MetricDataCollectionInfoMapper.java#L50)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Is this method specific to SLI use-cases? If yes we should refactor the name to convey the intent of the method clearly.
</blockquote></details>

Yes, both(all) of these methods of DataCollectionSLIInfoMapper are specific to SLI cases, and the class name conveys the intent



_Code quote:_
```Java
  public R toDataCollectionInfo(List<T> cvConfigs, List<String> metricIdentifiers) {
    T baseCvConfig = cvConfigs.stream()
                         .filter(cvConfig -> cvConfig.isSLIEnabled())
                         .findAny()
                         .orElseThrow(() -> new IllegalStateException("No SLI Enabled CV Configs found"));
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java` line 187 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx8dR89S1uQENZsmRE:-NOy7E7I9zk2gznlQp0S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java#L187)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Looks like this is getting repeated in different methods and we only need 1 cvConfig. Lets extract this out in an appropriate method.
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java` line 191 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx99Vw1npEa8XWUTn0:-NOy7GIi5qdchBlvGJNh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java#L191)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Are we using the result of this anywhere?
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java` line 239 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx9JIB4dCHVw-NqGJF:-NOyAC7w9K9MB_-0azRC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java#L239)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

We can use JsonUtils instead of instantiating Gson object
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/resources/ServiceLevelIndicatorResourceTest.java` line 99 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOxAGPz6zeYE8ecgZU4:-NOyCXbnEQWrxyGKa2Zv:b-7rl0kd) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/resources/ServiceLevelIndicatorResourceTest.java#L99)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Access modifier should be private
</blockquote></details>

done
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/servicelevelobjective/ServiceLevelIndicatorServiceImplTest.java` line 180 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOxAfym7O1-bL58f_A-:-NOyCTqGDxWnh6xsTkbe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/servicelevelobjective/ServiceLevelIndicatorServiceImplTest.java#L180)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Please ensure developer name is correct
</blockquote></details>

Done.



_Code quote:_
```Java
  @Category(UnitTests.class)
  public void testGetMetricGraph() throws IOException, IllegalAccessException {
    String tracingId = "tracingId";
```

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44245)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/sli/MetricOnboardingGraph.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx5q1NAZ-HaSwipACH:-NOyDPNU-1lO4vXOm-e-:b-os19xt) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/sli/MetricOnboardingGraph.java#L29)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

We have defined metric1 and metric2 in ratioSLI, added metricIdentifier as it's identifier.  Can't do anything for 1 and 2.
</blockquote></details>

The ratio would be between two quantities. eg good metrics, total metrics, etc. We should try to keep the names easy to understand
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java` line 187 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx8dR89S1uQENZsmRE:-NOyEWTj063ujA4O2uxj:bkdb5f0) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java#L187)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We can refactor the entire functionality to get baseCvConfig into a separate method and reuse it.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 8 of 12 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44245)* status: 1 change requests. 1. unresolved discussions. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/sli/MetricOnboardingGraph.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx5q1NAZ-HaSwipACH:-NOyFWLN6OQJYIEblKRj:b-o141cc) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/sli/MetricOnboardingGraph.java#L29)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

It won't always be good metrics, It can be bad  metrics as well
</blockquote></details>

nit: We have a plan to rename them to requestMetric and totalRequestMetric in serviceLevelObjectiveV2DTO. But since this API is not customer facing, it doesn't make much difference.

**Review by dhruv-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44245)* status: :shipit: complete! ✓

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44245)* status: 2 file(s) to review. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java` line 187 at r1](https://reviewable.io/reviews/harness/harness-core/44245#-NOx8dR89S1uQENZsmRE:-NOyHocP0HVvxKzzGUss:bi55fik) ([raw file](https://github.com/harness/harness-core/blob/3aeb6263e9292f1cba1ce478e7d05c94d318c2fc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java#L187)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

We can refactor the entire functionality to get baseCvConfig into a separate method and reuse it.
</blockquote></details>

cvConfigs is needed in dataCollectionInfo method

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44245)* status: :shipit: complete! ✓

**Pull request merged**
