### PR TITLE
[fix]: [PIE-8182]: Check if axis name service is runtime input

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43653)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43653)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by namanvermah** [comment]
trigger ti0

**Comment by namanvermah** [comment]
trigger checkstylecodeformat

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43653)* status: :shipit: complete! ✓

**Comment by naidu-harness** [comment]
trigger tin4

**Comment by naidu-harness** [comment]
trigger ti4

**Pull request merged**
