### PR TITLE
feat: [DEL-5283]: freeze containerised delegates instead of self-destructing

### PR DESCRIPTION
**Pull request by arpit3107**
…ted.

## Describe your changes
We should not self destruct delegates which are running inside a container. As the container will restart if the liveliness probe fails for some time. So, as a solution we should freeze the watcher so that watcher can continue writing heartbeat and do nothing else, and this will lead to no liveliness probe fail.

Tested scenarios:
1. Manager was sending SELF_DESTRUCT command on getDelegateConfiguration call, and validated that watcher was freezed in K8s and got process got killed in watcher env.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39705)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39705)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 302 at r2](https://reviewable.io/reviews/harness/harness-core/39705#-NGpW4NpEx6e_ZAuIXeG:-NGpW4NpEx6e_ZAuIXeH:b-in3rc4) ([raw file](https://github.com/harness/harness-core/blob/ddfb780e3f208c9c600e215cc16b6e8ff05b32f4/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L302)):*
> ```Java
> 
>   private void startMonitoringFileHandles() {
>     if (frozen.get()) {
> ```

This is not needed, this call happens once during watcher start, and by then frozen will always be false.



_Code quote:_
```Java
    if (frozen.get()) {
      return;
    }
```
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 447 at r2](https://reviewable.io/reviews/harness/harness-core/39705#-NGpVrmy40tp8TvDt9Z_:-NGpVrmy40tp8TvDt9Za:b-in3rc4) ([raw file](https://github.com/harness/harness-core/blob/ddfb780e3f208c9c600e215cc16b6e8ff05b32f4/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L447)):*
> ```Java
>   private void startUpgradeCheck() {
>     if (frozen.get()) {
>       return;
> ```

This is not needed, this call happens once during watcher start, and by then frozen will always be false.



_Code quote:_
```Java
    if (frozen.get()) {
      return;
    }
```
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 1015 at r2](https://reviewable.io/reviews/harness/harness-core/39705#-NGpVgRa-A4BbnHxBLTV:-NGpVgRa-A4BbnHxBLTW:b-yc7j28) ([raw file](https://github.com/harness/harness-core/blob/ddfb780e3f208c9c600e215cc16b6e8ff05b32f4/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L1015)):*
> ```Java
>     try {
>       if (frozen.get()) {
>         log.info("Watcher has been frozen. Will not start delegate.");
> ```

we don't need this if we disable input executor. but please confirm



_Code quote:_
```Java
      if (frozen.get()) {
        log.info("Watcher has been frozen. Will not start delegate.");
        return;
      }
```
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 1031 at r2](https://reviewable.io/reviews/harness/harness-core/39705#-NGpJZ_X2n-v6IZa4G2H:-NGpJZ_X2n-v6IZa4G2I:b-tgdrby) ([raw file](https://github.com/harness/harness-core/blob/ddfb780e3f208c9c600e215cc16b6e8ff05b32f4/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L1031)):*
> ```Java
>         if (config != null && config.getAction() == SELF_DESTRUCT) {
>           if (SHELL_SCRIPT.equals(DELEGATE_TYPE)) {
>             selfDestruct();
> ```

can you add a comment here, why we need selfDestruct for shell delegates and freeze for others.
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 1708 at r2](https://reviewable.io/reviews/harness/harness-core/39705#-NGpJghcBrymAbR8TIUG:-NGpJghcBrymAbR8TIUH:b537ck2) ([raw file](https://github.com/harness/harness-core/blob/ddfb780e3f208c9c600e215cc16b6e8ff05b32f4/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L1708)):*
> ```Java
>   }
> 
>   // we should self-destruct only for shell delegates and not for containerised delegates since pod will restart itself
> ```

comment not needed here, instead put during function call



_Code quote:_
```Java
  // we should self-destruct only for shell delegates and not for containerised delegates since pod will restart itself
  // again
```
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 1766 at r2](https://reviewable.io/reviews/harness/harness-core/39705#-NGpUoAcAIBkq0ssq-sn:-NGpUoAf0MPP-_YV07qk:bbc962u) ([raw file](https://github.com/harness/harness-core/blob/ddfb780e3f208c9c600e215cc16b6e8ff05b32f4/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L1766)):*
> ```Java
>     frozen.set(true);
>     watchExecutor.shutdown();
>     upgradeExecutor.shutdown();
> ```

We also might need to stop inputExecutor, that results in delegate configuration call.

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39705)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 302 at r2](https://reviewable.io/reviews/harness/harness-core/39705#-NGpW4NpEx6e_ZAuIXeG:-NGvV82t46pN7Of7sljw:b-kie9gp) ([raw file](https://github.com/harness/harness-core/blob/ddfb780e3f208c9c600e215cc16b6e8ff05b32f4/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L302)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

This is not needed, this call happens once during watcher start, and by then frozen will always be false.
</blockquote></details>

yes this gets called once during watcher start, but by then this can get freezed also. Since this is called after startWatching() method.
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 447 at r2](https://reviewable.io/reviews/harness/harness-core/39705#-NGpVrmy40tp8TvDt9Z_:-NGvVSUyEWZrnf32BRIQ:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/ddfb780e3f208c9c600e215cc16b6e8ff05b32f4/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L447)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

This is not needed, this call happens once during watcher start, and by then frozen will always be false.
</blockquote></details>

same as above
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 1708 at r2](https://reviewable.io/reviews/harness/harness-core/39705#-NGpJghcBrymAbR8TIUG:-NGvWzCZ-wKf7WfzXlsk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ddfb780e3f208c9c600e215cc16b6e8ff05b32f4/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L1708)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

comment not needed here, instead put during function call
</blockquote></details>

Done.
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 1766 at r2](https://reviewable.io/reviews/harness/harness-core/39705#-NGpUoAcAIBkq0ssq-sn:-NGvWF1N0vfLffCHBoaX:b-tz7ph3) ([raw file](https://github.com/harness/harness-core/blob/ddfb780e3f208c9c600e215cc16b6e8ff05b32f4/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L1766)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

We also might need to stop inputExecutor, that results in delegate configuration call.
</blockquote></details>

Didn't wanted to do that so that watcher keeps on logging that it has been freezed. But anyway its fine,

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39705)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 302 at r2](https://reviewable.io/reviews/harness/harness-core/39705#-NGpW4NpEx6e_ZAuIXeG:-NH5b_Wr393sdM8maej1:b-op3ew1) ([raw file](https://github.com/harness/harness-core/blob/ddfb780e3f208c9c600e215cc16b6e8ff05b32f4/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L302)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

yes this gets called once during watcher start, but by then this can get freezed also. Since this is called after startWatching() method.
</blockquote></details>

This can fail too than, it's possible that you set frozen to true just after check here.



_Code quote:_
```Java
 watchExecutor.shutdown();
```
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 1766 at r2](https://reviewable.io/reviews/harness/harness-core/39705#-NGpUoAcAIBkq0ssq-sn:-NH5cYRxAsiZKpUn__YA:bq2denr) ([raw file](https://github.com/harness/harness-core/blob/ddfb780e3f208c9c600e215cc16b6e8ff05b32f4/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L1766)):*
>  do that so that watcher keep
No need to log always, just logging here at once should be enough.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39705)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39705)* status: :shipit: complete! ✓

**Pull request merged**
