### PR TITLE
[feat]: [PIE-9559]: Plan Creation Graph updates for Pipeline Rollback Stage

### PR DESCRIPTION
**Pull request by namanvermah**
Stages Plan Creator will add a yaml update to have the last stage under "stages" to be Pipeline Rollback Stage. This means that the for the last stage in the original pipeline yaml, the next sibling would be this stage. We don't want PRB Stage to be always visible, hence special handling needs to be added for this last stage/parallel block

**Impact**: No impact as the change in Stages Plan Creator is yet to be merged to develop.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46308)

### CODE REVIEW

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46308)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46308)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46308)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 157 at r3](https://reviewable.io/reviews/harness/harness-core/46308#-NSjfw0r327v1SWBZ9u2:-NSji4EW76gua1wNxSq2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/60c2c3aab972c1d45cf6ff04e0027c22acefac3e/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L157)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Use Objects.equals rather
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46308)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46308)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46308)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
trigger review

**Review by archit-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46308)* status: :shipit: complete! ✓

**Pull request merged**
