### PR TITLE
feat: [PIE-5600]: Add API for serviceOverrides input set yaml for multiple services and multiple envs

### PR DESCRIPTION
**Pull request by shalini-agr**
…tiple services and multiple envs

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38131)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentInputsetYamlandServiceOverridesMetadataDTO.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/38131#-ND8-umy7hSryimVHeDY:-ND8-umy7hSryimVHeDZ:b-v1jlxq) ([raw file](https://github.com/harness/harness-core/blob/0a0da569867e1c59b323461ea8e29d1b78d2536e/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentInputsetYamlandServiceOverridesMetadataDTO.java#L26)):*
> ```Java
> @ApiModel("EnvironmentYamlMetadataDTO")
> public class EnvironmentInputsetYamlandServiceOverridesMetadataDTO {
>   Map<String, EnvironmentInputsetYamlAndServiceOverridesMetadata> EnvironmentsInputYamlAndServiceOverrides;
> ```

nit: small e

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38131)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38131)* status: :shipit: complete! ✓

**Pull request merged**
