### PR TITLE
[feat]:[CDS-34879]: Implement delete steps

### PR DESCRIPTION
**Pull request by nassergonzalez**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31655)

### CODE REVIEW

**Review by hextechpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31655)* status: 25 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/test/resources/recaster/alias/alias.txt, line 281 at r1](https://reviewable.io/reviews/harness/harness-core/31655#-Myr8ooh9tFYBtX0fInN:-Myr8ooh9tFYBtX0fInO:b-v7kp51) ([raw file](https://github.com/harness/harness-core/blob/58577dabd33de78946c1bd5476fd8e2d6d3fb431/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L281)):*
> ```help
> io.harness.plancreator.execution.StepsExecutionConfig
> io.harness.yaml.core.parallelStepElementConfig
> io.harness.ng.core.envGroup.beans.EnvironmentGroupConfig
> ```

do not change the aliases even if the package is changed. This property is used to deserialise existing saved entity in databases
___
*[125-cd-nextgen/src/test/resources/recaster/alias/alias.txt, line 292 at r1](https://reviewable.io/reviews/harness/harness-core/31655#-Myr96CO3CqXsWH4ABQH:-Myr96CO3CqXsWH4ABQI:bgdl6ic) ([raw file](https://github.com/harness/harness-core/blob/58577dabd33de78946c1bd5476fd8e2d6d3fb431/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L292)):*
> ```help
> io.harness.cdng.provision.cloudformation.DeleteStackBaseStepInfo
> io.harness.cdng.provision.cloudformation.CloudformationDeleteStackStepNode
> io.harness.cdng.provision.cloudformation.CloudformationDeleteStackStepParameters
> ```

looks like a duplicate

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31655)* status: 25 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/test/resources/recaster/alias/alias.txt, line 281 at r1](https://reviewable.io/reviews/harness/harness-core/31655#-Myr8ooh9tFYBtX0fInN:-MyrAADt0CY0GBeE9S1_:b56nck9) ([raw file](https://github.com/harness/harness-core/blob/58577dabd33de78946c1bd5476fd8e2d6d3fb431/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L281)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

do not change the aliases even if the package is changed. This property is used to deserialise existing saved entity in databases
</blockquote></details>

You are right, sorry, this probably slipped from my rebase, good catch!! :) thanks a lot
___
*[125-cd-nextgen/src/test/resources/recaster/alias/alias.txt, line 292 at r1](https://reviewable.io/reviews/harness/harness-core/31655#-Myr96CO3CqXsWH4ABQH:-MyrANshDx35J-ssSaVw:b-ry26us) ([raw file](https://github.com/harness/harness-core/blob/58577dabd33de78946c1bd5476fd8e2d6d3fb431/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L292)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

looks like a duplicate
</blockquote></details>

You are right, I will change it right now, thanks a lot :)

**Comment by nassergonzalez** [comment]
trigger ti0

**Comment by nassergonzalez** [comment]
trigger ti1

**Comment by nassergonzalez** [comment]
trigger ti2

**Comment by nassergonzalez** [comment]
trigger ti4

**Comment by nassergonzalez** [comment]
trigger ft1

**Comment by nassergonzalez** [comment]
trigger ft2

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 20 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31655)* status: 5 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationDeleteStackStep.java, line 103 at r1](https://reviewable.io/reviews/harness/harness-core/31655#-MyrKRxb4Qh5i0L7Leyq:-MyrKRxc3mFAz04zXgIe:b-brzl9j) ([raw file](https://github.com/harness/harness-core/blob/58577dabd33de78946c1bd5476fd8e2d6d3fb431/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationDeleteStackStep.java#L103)):*
> ```Java
>         : response.getUnitProgressData().getUnitProgresses();
>     builder.unitProgressList(unitProgresses);
>     switch (response.getCommandExecutionStatus()) {
> ```

Are we returning all those statuses from task handler?
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationDeleteStackStep.java, line 121 at r1](https://reviewable.io/reviews/harness/harness-core/31655#-MyrL5Kz0Y0p6EY4Ov5R:-MyrL5Kz0Y0p6EY4Ov5S:bm633ik) ([raw file](https://github.com/harness/harness-core/blob/58577dabd33de78946c1bd5476fd8e2d6d3fb431/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationDeleteStackStep.java#L121)):*
> ```Java
>             WingsException.USER);
>     }
>     if (CommandExecutionStatus.SUCCESS == response.getCommandExecutionStatus()) {
> ```

We already check if  response.getCommandExecutionStatus() is  SUCCESS
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationDeleteStackStepConfigurationParameters.java, line 24 at r1](https://reviewable.io/reviews/harness/harness-core/31655#-MyrLhaBBD2JWzQPI5-8:-MyrLhaBBD2JWzQPI5-9:bndyjne) ([raw file](https://github.com/harness/harness-core/blob/58577dabd33de78946c1bd5476fd8e2d6d3fb431/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationDeleteStackStepConfigurationParameters.java#L24)):*
> ```Java
> public class CloudformationDeleteStackStepConfigurationParameters {
>   @NonNull CloudformationStepConfigurationType type;
>   CloudformationDeleteStackStepConfigurationSpec spec;
> ```

the spec can  be null?
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationDeleteStackStepInfoTest.java, line 47 at r1](https://reviewable.io/reviews/harness/harness-core/31655#-MyrOkSOAgyA0y2DH0q6:-MyrOkSOAgyA0y2DH0q7:bmku2d0) ([raw file](https://github.com/harness/harness-core/blob/58577dabd33de78946c1bd5476fd8e2d6d3fb431/125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationDeleteStackStepInfoTest.java#L47)):*
> ```Java
>     cloudformationDeleteStackStepInfo.validateSpecParameters();
>   }
>   @Test
> ```

Let's try to have one empty line between methods, thats more readable. 
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationDeleteStackTaskHandler.java, line 50 at r1](https://reviewable.io/reviews/harness/harness-core/31655#-MyrQUYm1ei6cI0dy16c:-MyrQUYm1ei6cI0dy16d:ba7xyvh) ([raw file](https://github.com/harness/harness-core/blob/58577dabd33de78946c1bd5476fd8e2d6d3fb431/930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationDeleteStackTaskHandler.java#L50)):*
> ```Java
>     try {
>       cloudformationBaseHelper.deleteStack(taskNGParameters.getRegion(), awsInternalConfig, stackId,
>           taskNGParameters.getCloudFormationRoleArn(), (int) taskNGParameters.getTimeoutInMs() * 1000);
> ```

why * 1000?



_Code quote:_
```Java
CloudformationTaskNGParameters
```
___
*[960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java, line 254 at r1](https://reviewable.io/reviews/harness/harness-core/31655#-MyrRTP2CgpgBevbHG4C:-MyrRTP2CgpgBevbHG4D:b-e0f0xm) ([raw file](https://github.com/harness/harness-core/blob/58577dabd33de78946c1bd5476fd8e2d6d3fb431/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L254)):*
> ```Java
>     return new AmazonCloudFormationWaiters(closeableAmazonCloudFormationClient.getClient());
>   }
>   public void Printer(String region, String stackId, AwsInternalConfig awsConfig, LogCallback callback) {
> ```

method name should be lowercase and more meaningful.

**Review by hextechpal — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31655)* status: 6 file(s) to review. 2 change requests. 0 of 1 approvals obtained.

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 25 files at r1, 1 of 3 files at r2, 4 of 7 files at r3, 3 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31655)* status: 1 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java, line 267 at r5](https://reviewable.io/reviews/harness/harness-core/31655#-Myv0LBQ8oV3dQS-Jto1:-Myv0LBQ8oV3dQS-Jto2:bryrkvx) ([raw file](https://github.com/harness/harness-core/blob/1bb6f5e00561faae3e6831528756c7072aac9ba5/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L267)):*
> ```Java
>             resource.getResourceType(), resource.getLogicalResourceId(),
>             getStatusReason(resource.getResourceStatusReason()), resource.getPhysicalResourceId())));
>     sleep(ofSeconds(10));
> ```

I thin that sleep shouldn't be here.
We can add it in while loop where we call that method.

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31655)* status: 1 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java, line 267 at r5](https://reviewable.io/reviews/harness/harness-core/31655#-Myv0LBQ8oV3dQS-Jto1:-MyvEACU7YAGu26y0fG5:b32w1t) ([raw file](https://github.com/harness/harness-core/blob/1bb6f5e00561faae3e6831528756c7072aac9ba5/960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java#L267)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

I thin that sleep shouldn't be here.
We can add it in while loop where we call that method.
</blockquote></details>

Ok

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31655)* status: :shipit: complete! ✓

**Pull request merged**
