### PR TITLE
fix: [CDS-48881]: added hint to check secrets are base64 encoded

### PR DESCRIPTION
**Pull request by achyuth-harness**
## Describe your changes

Added a hint to check if secrets are base64 encoded in case we see `invalid yaml error` 
Before fix:
image

After fix:
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41871)

### CODE REVIEW

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41871)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`970-api-services-beans/src/main/java/io/harness/k8s/exception/KubernetesExceptionHints.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/41871#-NJxgYrfAPG1bmL1zzFW:-NJxgYrfAPG1bmL1zzFX:bc2ge48) ([raw file](https://github.com/harness/harness-core/blob/aaf8289ddec2193af09f0b26b244a22f00da2d3e/970-api-services-beans/src/main/java/io/harness/k8s/exception/KubernetesExceptionHints.java#L100)):*
> ```Java
>   public final String MISSING_OBJECT_ERROR = "Please verify that the resource exists and try again.";
>   public final String INVALID_VALUES_YAML =
>       "Please check if the given values yaml file(s) are valid YAMLs.\n- If you have certs/secrets which are referenced in templates or values.yaml file(s), ensure that these secrets are base64 encoded";
> ```

As discussed offline please make sure that hint with certs is added only in case we hit that error

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41871)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-api-services-beans/src/main/java/io/harness/k8s/exception/KubernetesExceptionHints.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/41871#-NJxgYrfAPG1bmL1zzFW:-NJyGMS9BtLZqKqgRGP5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aaf8289ddec2193af09f0b26b244a22f00da2d3e/970-api-services-beans/src/main/java/io/harness/k8s/exception/KubernetesExceptionHints.java#L100)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

As discussed offline please make sure that hint with certs is added only in case we hit that error
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41871)* status: Some of the checks are too old. 3 file(s) to review. 1 of 2 approvals obtained.

**Review by TarunUba1 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41871)* status: Some of the checks are too old.

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41871)* status: :shipit: complete! ✓

**Pull request merged**
