### PR TITLE
[feat]: [PL-22379]: Added test to check if dtos contains non-empty description

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
Added test to check if dtos contains non-empty description

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30717)

### CODE REVIEW

**Review by rijajoo — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30717)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[120-ng-manager/src/test/resources/oas/exclude-file, line 1 at r1](https://reviewable.io/reviews/harness/harness-core/30717#-Mvcpjtp5xMYks9T8Rie:-Mvcpjtp5xMYks9T8Rif:bsrcd09) ([raw file](https://github.com/harness/harness-core/blob/c4b1eb5c4580c954818198001f9df9e8c60a3e8b/120-ng-manager/src/test/resources/oas/exclude-file#L1)):*
> ```
> endpoint-exclusion: io.harness.ng.core.remote.NGSecretResourceV2.getEncryptionDetails
> ```

Let's give this file the same name across all the modules.
___
*[980-commons/src/test/java/io/harness/oas/OASModule.java, line 28 at r1](https://reviewable.io/reviews/harness/harness-core/30717#-Mvcq-pU9W9SsthPJ9xj:-Mvcq-pU9W9SsthPJ9xk:b1jlxgi) ([raw file](https://github.com/harness/harness-core/blob/c4b1eb5c4580c954818198001f9df9e8c60a3e8b/980-commons/src/test/java/io/harness/oas/OASModule.java#L28)):*
> ```Java
> import java.lang.reflect.Modifier;
> import java.lang.reflect.ParameterizedType;
> import java.util.*;
> ```

Let's not group the imports. (Also there's a setting which will help you not do this on IntelliJ) https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad

**Review by rijajoo — APPROVED** [review]
:lgtm:

> Reviewed 3 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30717#-:-MvrJtsrE03JfkLTus--:bnfp4nl)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Comment by rathodmeetsatish** [comment]
trigger ft2

**Review by ashishsanodia-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30717#-:-MvrZzux7rNrqzYQAQRR:bnfp4nl)* status: 10 file(s) to review.

**Review by ashishsanodia-harness — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30717)* status: :shipit: complete! ✓

**Pull request merged**
