### PR TITLE
[feat]: [PIE-3617]: Adding plan creation changes to support Execution Input...

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33536)

### CODE REVIEW

**Review by namanvermah — COMMENTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33536)* status: 11 file(s) to review. 0 of 2 approvals obtained.

**Review by namanvermah — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33536#-:-N2usdtG6pzI3pTQP3pw:bnfp4nl)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by namanvermah — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33536)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r1, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33536)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`860-orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/PMSStepPlanCreatorV2.java` line 104 at r4](https://reviewable.io/reviews/harness/harness-core/33536#-N2v8pY49dzFuqHEgT7h:-N2v8pY49dzFuqHEgT7i:b-5m4mjh) ([raw file](https://github.com/harness/harness-core/blob/a36ab343a1e037b3b4ec08d438ec3af6b1a6bad2/860-orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/PMSStepPlanCreatorV2.java#L104)):*
> ```Java
>             .group(StepOutcomeGroup.STEP.name())
>             .stepParameters(stepParameters)
>             .executionInputTemplate(ctx.getExecutionInputTemplate())
> ```

if single planNode, then it can be handled in planCreator service



_Code quote:_
```Java
executionInputTemplate(ctx.getExecutionInputTemplate())
```
___
*[`882-pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorService.java` line 248 at r4](https://reviewable.io/reviews/harness/harness-core/33536#-N2vC_OJC7SpvbVYi--h:-N2vC_OJC7SpvbVYi--i:blwa0ke) ([raw file](https://github.com/harness/harness-core/blob/a36ab343a1e037b3b4ec08d438ec3af6b1a6bad2/882-pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorService.java#L248)):*
> ```Java
>             field.getNode().getParentNode().getCurrJsonNode()));
>       }
>     }
> ```

here we can handle if single planNode and planNode doesn't have template, then use our common logic



_Code quote:_
```Java
    if (ctx.getGlobalContext().get("metadata").getIsExecutionInputEnabled()) {
      // TODO(BRIJESH): Hardcoding for steps for now. Will update the logic.
      if (field.getName().equals("step")) {
        ctx.setExecutionInputTemplate(RuntimeInputFormHelper.createExecutionInputFormAndUpdateYamlField(
            field.getNode().getParentNode().getCurrJsonNode()));
      }
    }
```

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 5 of 11 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 1 of 3 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33536)* status: 7 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33536)* status: 7 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 11 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 6 of 7 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33536)* status: 1 file(s) to review. 

___
*[`882-pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/beans/PlanCreationResponse.java` line 195 at r6](https://reviewable.io/reviews/harness/harness-core/33536#-N2ysJuVE0ld7Hm7RPHl:-N2ysJuVE0ld7Hm7RPHm:b-76zbgu) ([raw file](https://github.com/harness/harness-core/blob/7b1cce1eb113725307f7ccbbe60ec1df43a4091b/882-pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/beans/PlanCreationResponse.java#L195)):*
> ```Java
>       planNode.setExecutionInputTemplate(executionInputTemplate);
>     }
>     if (nodes != null) {
> ```

nit: please add comment that this method will only get called if single plan node, just people know when to use this method



_Code quote:_
```Java
if (nodes != null) {
```
___
*[`882-pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorService.java` line 248 at r4](https://reviewable.io/reviews/harness/harness-core/33536#-N2vC_OJC7SpvbVYi--h:-N2yyTNX7-lIf_GBmveV:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/a36ab343a1e037b3b4ec08d438ec3af6b1a6bad2/882-pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorService.java#L248)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

here we can handle if single planNode and planNode doesn't have template, then use our common logic
</blockquote></details>

done
___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java` line 47 at r4](https://reviewable.io/reviews/harness/harness-core/33536#-N2vCiu4DmOoQGH7VAUy:-N2yya7y-gKTzdL2epmx:b-2v1vqs) ([raw file](https://github.com/harness/harness-core/blob/a36ab343a1e037b3b4ec08d438ec3af6b1a6bad2/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java#L47)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

expose one more utliity where any given yamlField is converted to yamlfield with value as new expression
</blockquote></details>

discussed offline, will do in next pr
___
*[`860-orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/PMSStepPlanCreatorV2.java` line 104 at r4](https://reviewable.io/reviews/harness/harness-core/33536#-N2v8pY49dzFuqHEgT7h:-N2z1NXu9v0S7HdzG-mm:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/a36ab343a1e037b3b4ec08d438ec3af6b1a6bad2/860-orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/PMSStepPlanCreatorV2.java#L104)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

if single planNode, then it can be handled in planCreator service
</blockquote></details>

done

**Comment by brijeshdhakar** [comment]
Codebase hash check details:
Changes are done in backward-compatible manner. No changes in delegate tasks.
And the only change is in PlanCreationRequest used during plan creation before starting the pipeline execution. 
It will not affect delegate.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 5 of 11 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 1 of 3 files at r4, 3 of 7 files at r5, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33536)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r4, 3 of 7 files at r5, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33536#-:-N2zH3Hw2Ev_iPAK9VQt:bnfp4nl)* status: 1 file(s) to review.

**Review by namanvermah — APPROVED** [review]
> Reviewed 2 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33536)* status: :shipit: complete! ✓

**Pull request merged**
