### PR TITLE
feat: [PIE-5799]: Fix strategy getting stuck

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39560)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39560)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/39560#-NFxKEth3u5NP6MgOsZ1:-NFxKEth3u5NP6MgOsZ2:b-2jyd0g) ([raw file](https://github.com/harness/harness-core/blob/6408dce50c96a8ca7db8b76146e08ec5e302ad7f/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L98)):*
> ```Java
>                 ambiance, child.getChildNodeId(), uuid, child.getStrategyMetadata(), InitiateMode.CREATE_AND_START);
>           } else {
>             initiateNodeHelper.publishEvent(ambiance, child.getChildNodeId(), uuid);
> ```

Just a thought, shouldnt we also not add max concurrency for steps added via parallel? i think here for parallel they are always executing 
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/39560#-NFxKMBwDGJmuK53wRf_:-NFxKMBwDGJmuK53wRfa:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/6408dce50c96a8ca7db8b76146e08ec5e302ad7f/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L105)):*
> ```Java
>                 ambiance, child.getChildNodeId(), uuid, null, child.getStrategyMetadata(), InitiateMode.CREATE);
>           } else {
>             orchestrationEngine.initiateNode(ambiance, child.getChildNodeId(), uuid, null);
> ```

same as above

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39560)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/39560#-NFxKEth3u5NP6MgOsZ1:-NGFdn2H7918R3jjjm8n:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6408dce50c96a8ca7db8b76146e08ec5e302ad7f/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L98)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Just a thought, shouldnt we also not add max concurrency for steps added via parallel? i think here for parallel they are always executing 
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/39560#-NFxKMBwDGJmuK53wRf_:-NGFdxdP4T6wTwEU10z_:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6408dce50c96a8ca7db8b76146e08ec5e302ad7f/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L105)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

done

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 94 at r3](https://reviewable.io/reviews/harness/harness-core/39560#-NGGtjfi3n2iisFvSG_r:-NGGtjfi3n2iisFvSG_s:b5cyrh7) ([raw file](https://github.com/harness/harness-core/blob/6dae90da39e894dd373adc8beccd7ec3a4e22d05/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L94)):*
> ```Java
>         String uuid = callbackIds.get(currentChild);
>         if (shouldCreateAndStart(maxConcurrency, currentChild)) {
>           if (child.hasStrategyMetadata()) {
> ```

Add comment



_Code quote:_
```Java
          if (child.hasStrategyMetadata()) {
            initiateNodeHelper.publishEvent(
                ambiance, child.getChildNodeId(), uuid, child.getStrategyMetadata(), InitiateMode.CREATE_AND_START);
          } else {
            initiateNodeHelper.publishEvent(
```

**Review by hextechpal — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39560)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39560)* status: :shipit: complete! ✓

**Pull request merged**
