### PR TITLE
fix: [DEL-5602]: Reject unsupported task on Delegate

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Describe your changes
Change includes both manager and delegate side fix:
1) Manager to send task type in DelegateTask Event, 
2) Delegate change to honour task type being received. And validate if it can be supported with current delegate version. If not, than reject the task.

Testing:
Tried testing it locally:
1) Supported task should succeed
2) Unsupported task should fail, shouldn't move to acquire phase.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42104)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1915 at r1](https://reviewable.io/reviews/harness/harness-core/42104#-NKZoWRx3TyBL5YEhUXv:-NKZoWRx3TyBL5YEhUXw:br6rem2) ([raw file](https://github.com/harness/harness-core/blob/3fe31a8d5f449de4e7f59168024ca8d0dc09a334/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1915)):*
> ```Java
>     }
> 
>     if (delegateTaskEvent.getTaskType() != null) {
> ```

where is the logic to not acquire the task? also how do we solve the delegate downgrade case? are we changing the taskType in manager when delegate downgrades?

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42104)* status: Some of the checks are too old. 4 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1915 at r1](https://reviewable.io/reviews/harness/harness-core/42104#-NKZoWRx3TyBL5YEhUXv:-NKq7wO-9AdMcyrVGtfp:b-f60plf) ([raw file](https://github.com/harness/harness-core/blob/3fe31a8d5f449de4e7f59168024ca8d0dc09a334/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1915)):*
> also how do we solve the delegate downgrade case? are we changing the taskType in manager when delegate downgrades?
Missed the return statement here, we'll skip the acquire call below if we return from here. TaskType collection in manager is union of all delegates, so once all delegates are downgraded, taskType will change.

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1915 at r1](https://reviewable.io/reviews/harness/harness-core/42104#-NKZoWRx3TyBL5YEhUXv:-NKt0TCxBM04LrhMwD2V:baj90zh) ([raw file](https://github.com/harness/harness-core/blob/3fe31a8d5f449de4e7f59168024ca8d0dc09a334/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1915)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

> also how do we solve the delegate downgrade case? are we changing the taskType in manager when delegate downgrades?
Missed the return statement here, we'll skip the acquire call below if we return from here. TaskType collection in manager is union of all delegates, so once all delegates are downgraded, taskType will change.
</blockquote></details>

do we update the taskType list for a particular delegate when its downgraded?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42104)* status: 0 of 1 approvals obtained.

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42104)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1915 at r1](https://reviewable.io/reviews/harness/harness-core/42104#-NKZoWRx3TyBL5YEhUXv:-NKw8ecC4Nw0JH36eDWe:b-atcrxw) ([raw file](https://github.com/harness/harness-core/blob/3fe31a8d5f449de4e7f59168024ca8d0dc09a334/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1915)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

do we update the taskType list for a particular delegate when its downgraded?
</blockquote></details>

yes we do update during registration.

**Review by xingchi-jin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42104)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 380 at r2](https://reviewable.io/reviews/harness/harness-core/42104#-NL3Pvt95nDxTUXaYa8e:-NL3Pvt95nDxTUXaYa8f:b-gq24jm) ([raw file](https://github.com/harness/harness-core/blob/6d9126c97da89844287caaf834fe4c662ceb1656/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L380)):*
> ```Java
>   private final AtomicBoolean closingSocket = new AtomicBoolean(false);
>   private final AtomicBoolean sentFirstHeartbeat = new AtomicBoolean(false);
>   private final Set<String> supportedTaskTypes = new HashSet<>();
> ```

use immutableset 

my other question is: if none of the delegates in the account have supported task type, do we fail fast at manager side, or do we wait until the queued timeout ?

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42104)* status: Some of the checks are too old.

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42104)* status: Some of the checks are too old. 1. unresolved discussions. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 380 at r2](https://reviewable.io/reviews/harness/harness-core/42104#-NL3Pvt95nDxTUXaYa8e:-NLPWyZ44-QgcdtT2U0z:b-j84w6l) ([raw file](https://github.com/harness/harness-core/blob/6d9126c97da89844287caaf834fe4c662ceb1656/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L380)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

use immutableset 

my other question is: if none of the delegates in the account have supported task type, do we fail fast at manager side, or do we wait until the queued timeout ? 
</blockquote></details>

we cannot modify immutable set, which we wanted to down in the code.
If none of the delegate support task, than ideally it should fail at client itself. Arpit introduced a grpc endpoint to verify if the current account has delegate which support specific task or not. So if client avails that endpoint, task failure before manager itself.



_Code quote:_
```Java
supportedTaskTypes
```

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42104)* status: Some of the checks are too old. 1. unresolved discussions.

**Pull request merged**
