### PR TITLE
fix: [CDS-42179]: Rollback should not fail when the previous deployme…

### PR DESCRIPTION
**Pull request by bojanmicovic**
…nt is not available

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36712)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36712)

**Comment by bojanmicovic** [comment]
trigger messagecheck

**Comment by bojanmicovic** [comment]
trigger messagecheck

**Review by ivan-83 — CHANGES_REQUESTED** [review]
LGTM with minor changes.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36712#-:-NAEal_tBD5oEkxhWctX:b-1i08s7)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/rollback/SkipRollbackException.java` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/36712#-NAEaUSv6XLgf5DyspgS:-NAEaUSv6XLgf5DyspgT:b5iukuq) ([raw file](https://github.com/harness/harness-core/blob/ae1c4376fd3a36551a5ffe05b5d58691d557af26/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/rollback/SkipRollbackException.java#L10)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDP)
> public class SkipRollbackException extends WingsException {
> ```

Move this exception to 980-commons module.

**Review by ivan-83 — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36712)* status: :shipit: complete! ✓

**Comment by bojanmicovic** [comment]
trigger ti1

**Comment by bojanmicovic** [comment]
trigger ft1

**Pull request merged**
